### ISSUE TITLE
database update error

### ISSUE THREAD

**Issue by el-wood** [zammad/zammad#1001]
### Infos:
Hi,

I got error trying update Zammad from early 1.6 to latest 1.6

# database.yml found. Updating db...
== 20170421110000 AddOriginById: migrating ====================================
-- add_column(:ticket_articles, :origin_by_id, :integer)
   -> 0.1416s
== 20170421110000 AddOriginById: migrated (0.1428s) ===========================

== 20170426135500 AddReplyTo: migrating =======================================
-- add_column(:ticket_articles, :reply_to, :string, {:limit=>3000})
rake aborted!

and then:
ActiveRecord::StatementInvalid: Mysql2::Error: Row size too large. The maximum row size for the used table type, 
not counting BLOBs, is 65535. This includes storage overhead, check the manual. 
You have to change some columns to TEXT or BLOBs:
 ALTER TABLE `ticket_articles` ADD `reply_to` varchar(3000)

* Used Zammad version: 1.6
* Used Zammad installation source: (source, package, ...) 1958
* Operating system:  Ubuntu 16.04
* Browser + version:

**Comment by monotek** [comment]
MySQL Version?

**Comment by el-wood** [comment]
5.7.17-0ubuntu0.16.04.2

Maybe it’s because I’d added object to ticket object choice with spaces I choices names ?

**Comment by el-wood** [comment]
Little investigation:
The total size of all fields in the table is more than the limit, 65535, that's why you are getting this error.
You should use text type instead of varchar for long strings. Replace all varchar(8000) with text, and it should work.

**Comment by rolfschmidt** [comment]
Hi @el-wood,
thank you very much for your report. I fixed the column size and it should work now with the newest state of the develop branch.

-Rolf

**Comment by el-wood** [comment]
Hi, 
I installed newest version. I cant see any erros, but my Zammad is not working now :(. ERR connection refused.
Is it possible to force db update ?

**Comment by monotek** [comment]
Run:
* zammad run rake db:migrate
