### ISSUE TITLE
Reply-To is not considered for automatic responses (triggers).

### ISSUE THREAD

**Issue by dennybresch** [zammad/zammad#1006]
### Actual behavior:

It does not send an automatic response to the reply-to address.

### Steps to reproduce the behavior:

* Use  Zammad-Form on third website (with reply-to header).
* send mail to zammad with Reply-to address
* Automatic response will be not triggered

Here you can find another issue to this topic.
Mailprocessing: Reply-To header are ignored #203

**Comment by rolfschmidt** [comment]
Hallo @dennybresch,
die Auswahl für die Empfänger der Benachrichtigung wurde überarbeitet. Es können jetzt mehrere Empfänger ausgewählt werden. Zusätzlich gibt es die Möglichkeit nun den "Absender des letzten Artikels" auszuwählen. Diese Wahl berücksichtigt dann auch das Reply-To Feld des letzten Artikels.

![grafik](https://cloud.githubusercontent.com/assets/5445062/25617719/eb7c0974-2f43-11e7-9b7c-83dbecffad60.png)

Die Änderungen sind jetzt im develop branch verfügbar.

-Rolf

**Comment by fthommen** [comment]
Any chances, that this fix is backported to zammad 1.5.x?  It's a real showstopper for us, as we regularly (several times per week) get emails with Reply-To adresses where we have to modify the reply address manually at each answer
