### ISSUE TITLE
Time accounting based on Weekday

### ISSUE THREAD

**Issue by lasat** [zammad/zammad#1007]
Preferred behavior:

    1. It should be possible to split the accounted times by weekday, especially "Mo-Fr" and "Sa", "So"
    2. It would be helpfully to export the accounted times as CSV-file with fields: date, organisation, customer, agent, ticket (number and title)

Actual behavior:

    Only aggregated time units are displayed and no export is possible

**Comment by martini** [comment]
Hi @lasat 

> 1. It should be possible to split the accounted times by weekday, especially "Mo-Fr" and "Sa", "So"

This would be to specific. We normally add features which are needed by 80% of users to not overload the app.

> 2. It would be helpfully to export the accounted times as CSV-file with fields: date, organisation, customer, agent, ticket (number and title)

In Zammad 1.5 and higher (https://zammad.com/news/release-1-5-maintenance) you can download the accounted time by ticket. Would that fit for you?

 -Martin

**Comment by lasat** [comment]
Hi @martini,

1. I thought almost every company have different hourly rates for weekend. I would think this will be used by >80% of IT-support companies, but I could be wrong.

2. Oh yes. That fit for me. Thank you.

**Comment by martini** [comment]
> 2. Oh yes. That fit for me. Thank you.

Thanks for feedback.

I guess you would need an export with every time record action (to decide if it was on sat or sun), right? Currently its accounted time by ticket (wicht means all the time for a certain ticket in a certain period). Only if you do the export for every day you could handle it, but this only makes sense if you do it via an script.

**Comment by lasat** [comment]
@martini: currently the accounting data is not available through API, right? is this planned?

**Comment by thorsteneckel** [comment]
This issue has been stale for quite a while. If your question is still open please refer to the [community board](http://community.zammad.org/). There are a lot great people willing to help and answer questions.
