### ISSUE TITLE
Display only used Channels in Dashboard

### ISSUE THREAD

**Issue by sthag** [zammad/zammad#1010]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: deb package
* Operating system: ubuntu 16.04.02
* Browser + version: Firefox 52.0.2

### Expected behavior:

* The dashboard has a tile for used channels
* Only the email channel is active in the admin settings (I guess phone is somehow special)
* Only activated channels should be shown
So this would be email and phone only
Facebook and twitter should be gone

### Actual behavior:

* The tile always shows at least email, phone, twitter and facebook

### Steps to reproduce the behavior:

* start zammad and look at the dashboard under the tab my statistics

**Comment by gwingend** [comment]
+1
