### ISSUE TITLE
different type of tickets not assigned to specific users

### ISSUE THREAD

**Issue by el-wood** [zammad/zammad#1011]
### Infos:

* Used Zammad version: 1.6

### Expected behavior:

* is it possible to have a ticket assigned to organization, but not specified user?  Or maybe to have a user without an email? Sometimes You need to do some job for an organization, but not for specific user.

* is it possible to have a ticket type different than email or call? Let's say "maintenance" or sth like that?

Example:
I need to do a server update for specific organization and i want to register time and steps but don't want to send an email about that case.

Regards

**Comment by martini** [comment]
Hi @el-wood you simply can add a note. Note are not sent to customer (until you create triggers to do so).

<img width="641" alt="screen shot 2017-04-28 at 15 14 24" src="https://cloud.githubusercontent.com/assets/110226/25530124/674fec22-2c25-11e7-97e7-53d78f0373e9.png">

PS: You can't assign a ticket to an organization. Tickets assigned to customers and an customer is assigned to an organization.

 -Martin

**Comment by el-wood** [comment]
Ok -but how to start new ticket as a note ?

**Comment by martini** [comment]
> Ok -but how to start new ticket as a note ?

Now I got it. In this case you currently can only create a new ticket as phone call (e. g. inbound or outbound). If you have not configured an trigger for "auto reply on new ticket" for this article types, no email will be sent to customer.
