### ISSUE TITLE
Error "CSRF token verification failed!" trying to create ticket with more than one tag

### ISSUE THREAD

**Issue by sthag** [zammad/zammad#1013]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: deb package
* Operating system: Ubuntu 16.04
* Browser + version: Firefox 52.0.2

### Expected behavior:

* Login
* Create a new Ticket (In/Out Phone or E-Mail testet)
* Add necessary information and select more than one tag
* Select create
* The ticket should be created with all the information given

### Actual behavior:

* When selecting create the error "CSRF token verification failed!" is displayed ![tag-error](https://cloud.githubusercontent.com/assets/1476724/25519625/267113bc-2be8-11e7-876c-d19146efb8cd.jpg)
* The ticket is not created

### Additional Infos

* Trying to remove the tags does not change anything. The error is displayed and the ticket cannot be created
* Starting all over with a new ticket and adding only one tag creates the ticket as expected
* Adding tags to an existing ticket is possible without error

**Comment by sthag** [comment]
I cannot reproduce it either. I tested again with Firefox on Ubuntu 16 and Windows 10.
So I would close this issue...
I still have the problem described in issue #1019 though.

**Comment by martini** [comment]
Thanks for feeback!
