### ISSUE TITLE
Reverse Proxy forwarding Port 80

### ISSUE THREAD

**Issue by Jonske** [zammad/zammad#1015]
Hello,

how can i change the settings, that when iam connecting to the nginx site with the IP. Normaly iam on the nginx test website. How can i change it, that iam connecting to the zammad system on port 3000, without writing it in the url?

kind regards

**Comment by babakkazemi** [comment]
Check out the nginx configuration file, at least with debian or ubuntu package installation you will find it here:
/etc/nginx/sites-enabled/zammad.conf
https://github.com/zammad/zammad/blob/develop/contrib/nginx/zammad.conf

on line 16 it says what to do:
server {
    listen 80;

    # replace 'localhost' with your fqdn if you want to use zammad from remote
    server_name localhost;

replace "localhost" after server_name with the fqdn of your zammad installation, then restart zammad.

**Comment by rolfschmidt** [comment]
Thanks @babakkazemi for the support !!! I added the example config change for nginx to the documentation on https://docs.zammad.org/en/latest/ .

**Comment by sforsythe-sv** [comment]
> Check out the nginx configuration file, at least with debian or ubuntu package installation you will find it here: /etc/nginx/sites-enabled/zammad.conf https://github.com/zammad/zammad/blob/develop/contrib/nginx/zammad.conf
> 
> on line 16 it says what to do: server { listen 80;
> 
> ```
> # replace 'localhost' with your fqdn if you want to use zammad from remote
> server_name localhost;
> ```
> 
> replace "localhost" after server_name with the fqdn of your zammad installation, then restart zammad.

Years later this solved the issue i was facing.
