### ISSUE TITLE
error "CSRF token verification failed!" trying to create a trigger with Tags condition

### ISSUE THREAD

**Issue by sthag** [zammad/zammad#1019]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: deb package
* Operating system: Ubuntu 16.04
* Browser + version: Firefox 52.0.2

### Expected behavior:

* Login
* Switch to admin section trigger
* Create new trigger with any "Tags" condition
* Add a tag
* submit the new trigger
* The new trigger is created and the list of triggers is shown

### Actual behavior:

After creating a trigger with Tags condition and adding a tag and trying to submit

* the view jumps to the dashboard
* clicking on admin again shows the trigger dialogue still open
* the dialog now has an error message showing "CSRF token verification failed!"
![trigger-error](https://cloud.githubusercontent.com/assets/1476724/25528214/2ba9d78c-2c0c-11e7-82f4-090907bb4905.jpg)
* clicking on submit again closes the trigger dialogue and the trigger is added to the list of triggers

**Comment by martini** [comment]
I guess its the same problem as in https://github.com/zammad/zammad/issues/1013 unfortunately I can't reproduce it. 

Any chance to get remote login?

**Comment by sthag** [comment]
I hope it is ok that I made another ticket. The behavior was a little bit different.
Remote access is currently not possible :-/
Can this be a firewall issue. Something zammad wants to do or know which needs access to somewhere?
It is of course no major issue.

**Comment by martini** [comment]
> Can this be a firewall issue. Something zammad wants to do or know which needs access to somewhere?

Yes, it could be. Zammad is sending the X-CSRF-Token as ajax header:

https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/lib/app_post/ajax.coffee#L79

If the rails server can't get this token, your error message appears.

JFI: I have not heard about this kind of problems before.

**Comment by sthag** [comment]
Here also thanks for your swift reply. Helps a lot.
I'll let you know if I have more information.

**Comment by sthag** [comment]
Just want to add some information I forgot.
I checked the status of admin / Tags / allow addition of tags for users. It was off. Switched it on and tried the described process. No difference.

I also forgot to add the logs I get from Firefox the moment I press submit in the trigger dialogue shown above:

```
13:59:55.654 App.i(error)                   | ajax 401 1 application-[TOKEN-HERE].js:21:19077
	t/e[t] https://[IP-HERE]/assets/application-[TOKEN-HERE].js:21:19077
	t</t.prototype._log https://[IP-HERE]/assets/application-[TOKEN-HERE].js:21:13450
	t</t.prototype.log https://[IP-HERE]/assets/application-[TOKEN-HERE].js:21:13081
	App.LogInclude</i.log https://[IP-HERE]/assets/application-[TOKEN-HERE].js:21:11069
	i/</< https://[IP-HERE]/assets/application-[TOKEN-HERE].js:24:26661
	n.trigger https://[IP-HERE]/assets/application-[TOKEN-HERE].js:7:26080
	s</i.prototype.trigger https://[IP-HERE]/assets/application-[TOKEN-HERE].js:8:3988
	c</n.prototype.failResponse/</< https://[IP-HERE]/assets/application-[TOKEN-HERE].js:8:13122
	rt.Callbacks/c https://[IP-HERE]/assets/application-[TOKEN-HERE].js:2:8513
	rt.Callbacks/u.fireWith https://[IP-HERE]/assets/application-[TOKEN-HERE].js:2:9286
	.Deferred/</s[r[0]] https://[IP-HERE]/assets/application-[TOKEN-HERE].js:2:10261
	n</n.prototype.ajaxQueue/u/c https://[IP-HERE]/assets/application-[TOKEN-HERE].js:8:9724
	rt.Callbacks/c https://[IP-HERE]/assets/application-[TOKEN-HERE].js:2:8513
	rt.Callbacks/u.fireWith https://[IP-HERE]/assets/application-[TOKEN-HERE].js:2:9286
	i https://[IP-HERE]/assets/application-[TOKEN-HERE].js:3:11438
	.send/n/< https://[IP-HERE]/assets/application-[TOKEN-HERE].js:3:17270

13:59:55.657 App.i(error)                   | ajax Object {  } Object { readyState: 4, getResponseHeader: .ajax/k.getResponseHeader(), getAllResponseHeaders: .ajax/k.getAllResponseHeaders(), setRequestHeader: .ajax/k.setRequestHeader(), overrideMimeType: .ajax/k.overrideMimeType(), statusCode: .ajax/k.statusCode(), abort: .ajax/k.abort(), state: .Deferred/i.state(), always: .Deferred/i.always(), then: .Deferred/i.then(), 12 weitere… } 401 1 application-[TOKEN-HERE].js:21:19077
	t/e[t] https://[IP-HERE]/assets/application-[TOKEN-HERE].js:21:19077
	t</t.prototype._log https://[IP-HERE]/assets/application-[TOKEN-HERE].js:21:13450
	t</t.prototype.log https://[IP-HERE]/assets/application-[TOKEN-HERE].js:21:13081
	App.LogInclude</i.log https://[IP-HERE]/assets/application-[TOKEN-HERE].js:21:11069
	i/</< https://[IP-HERE]/assets/application-[TOKEN-HERE].js:24:26714
	n.trigger https://[IP-HERE]/assets/application-[TOKEN-HERE].js:7:26080
	s</i.prototype.trigger https://[IP-HERE]/assets/application-[TOKEN-HERE].js:8:3988
	c</n.prototype.failResponse/</< https://[IP-HERE]/assets/application-[TOKEN-HERE].js:8:13122
	rt.Callbacks/c https://[IP-HERE]/assets/application-[TOKEN-HERE].js:2:8513
	rt.Callbacks/u.fireWith https://[IP-HERE]/assets/application-[TOKEN-HERE].js:2:9286
	.Deferred/</s[r[0]] https://[IP-HERE]/assets/application-[TOKEN-HERE].js:2:10261
	n</n.prototype.ajaxQueue/u/c https://[IP-HERE]/assets/application-[TOKEN-HERE].js:8:9724
	rt.Callbacks/c https://[IP-HERE]/assets/application-[TOKEN-HERE].js:2:8513
	rt.Callbacks/u.fireWith https://[IP-HERE]/assets/application-[TOKEN-HERE].js:2:9286
	i https://[IP-HERE]/assets/application-[TOKEN-HERE].js:3:11438
	.send/n/< https://[IP-HERE]/assets/application-[TOKEN-HERE].js:3:17270

13:59:55.688 App.i(errors)                  | Object { error: "CSRF token verification failed!" } 1 application-[TOKEN-HERE].js:21:19077
```

**Comment by martini** [comment]
Thanks for feedback. The error message is from the rails server. It says there was not CSRF in the request.
1) Can you check the http request in firefox network request? Is the token there?
2) Can you check it with an different browser?

Thanks

**Comment by sthag** [comment]
I hope I got the right information.
I replaced the token with [TOKEN-IS-HERE] but there is one.
I also tried Chromium 58.0.3029.81 on Windows 10 and **there is no error**

I need a little bit more time to test different browsers if necessary.

### Request head

```
Host: [HOST-IP]
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
X-Requested-With: XMLHttpRequest
X-CSRF-Token: [TOKEN-IS-HERE]
Referer: https://[DOMAIN-HERE]/
Content-Length: 154
Cookie: _zammad_session_[SESSION-ID]
Connection: keep-alive
```

### Answer head

```
Cache-Control: no-cache
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Date: Fri, 28 Apr 2017 14:18:53 GMT
Keep-Alive: timeout=5, max=99
Server: Apache/2.4.18 (Ubuntu)
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Failure: CSRF token verification failed!
X-Frame-Options: SAMEORIGIN
X-Request-Id: [ID-HERE]
X-Runtime: 0.009718
X-XSS-Protection: 1; mode=block
```

**Comment by martini** [comment]
Good job! It seems that the browser was sending the token but the token did not reach the server. Maybe a firewall which is stripping some headers?

**Comment by sthag** [comment]
It must be the firewall then. Firefox on Windows doesn't through the error too.
Sorry to bother you but your tips helped a lot.

**Comment by martini** [comment]
You are welcome!

**Comment by sthag** [comment]
I've got even more information ...
The error does not appear on Chromium 58.0.3029.81 on the initially tested system Ubuntu 16.04.
I got infos from the dev guys and both tested systems are on the same network which I assumed was not the case. So it isn't the firewall, I guess.
The error only shows on Ubuntu on Firefox 52.0.2 (64bit). I overlooked the difference to the Firefox on Windows 10 which is the 32bit version.
That is all information I can get for now.

**Comment by martini** [comment]
> The error only shows on Ubuntu on Firefox 52.0.2 (64bit).

All other actions in Zammad (write actions) are working?

**Comment by sthag** [comment]
I had a look at nearly every aspect of the zammad frontend so far, tested many different things with write actions.
So far no other error occurred.

**Comment by thorsteneckel** [comment]
Seems to be fixed a long time ago. Closing now.
