### ISSUE TITLE
Date picker opens half outside the viewport

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#1021]
### Infos:

* Used Zammad version: 1.5.x
* Operating system: hosted at zammad.com
* Browser + version: Vivaldi 1.8.770

### Expected behavior:

* If date picker opens and it is half outside the visible area, the scroll postion should be adjusted, so that the date picker is entirely inside the visible area

### Actual behavior:

* Date picker opens, but you must scroll the page manually to the correct coordinates

### Steps to reproduce the behavior:

* Click a date field which is nearly at the bottom (e. g. when creating a ticket)
* The effect is more observable if you type some text to make the textarea grow in height

Before: There is not much space between date field and the bottom of the HTML page (see scrollbar)
![screenshot-2017-04-28-17 46 22](https://cloud.githubusercontent.com/assets/26226303/25536353/d19010c0-2c3a-11e7-9196-15a1c3923ea6.png)

After:
![screenshot-2017-04-28-17 41 34](https://cloud.githubusercontent.com/assets/26226303/25536281/845dd724-2c3a-11e7-8505-73805a1c46e4.png)

**Comment by thorsteneckel** [comment]
Hi @AND51 - this will be fixed with the next Zammad release 2.3 you can already check it by using the development branch package. Feedback is welcome 🚀
