### ISSUE TITLE
Access to original email not clear

### ISSUE THREAD

**Issue by MartinBorg** [zammad/zammad#1028]
### Infos:

* Used Zammad version: 1.5.0-1493368946.f3f4792.jessie
* Used Zammad installation source: deb
* Operating system: Debian 8
* Browser + version: Firefox 52.0.2 on Debian

### Expected behavior:

* Origininal emails should be accessible via links. At least by admin. We had some cases of attempted cybercrime lately, as well as the usual spam, and need to have access to the original, unaltered emails, esp. with complete headers.

* If Zammad would not delete messages on the IMAP server, this would be not necessary - we would just look up the messages using a MUA.

### Actual behavior:

* I can't find such links. Maybe I did not look at the right place.

**Comment by martini** [comment]
Hi @MartinBorg 

you can download the raw mail 1:1 via the footer of an article.

<img width="578" alt="screen shot 2017-04-30 at 17 32 44" src="https://cloud.githubusercontent.com/assets/110226/25565645/3994037a-2dcb-11e7-9cb8-2f4e9ec34a4d.png">

Just reopen if you need something else.

 -Martin

**Comment by MartinBorg** [comment]
Thanks, that's what I didn't see!

**Comment by martini** [comment]
JFI: It's only for article with is a mail. It's not shown for e. g. notes or tweets.
