### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#1029]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: (source, package, ...) Package
* Operating system: Ubuntu
* Browser + version: 

### Expected behavior:
I intend to make Zammad RTL ( Right to left ) support, Need best advise with update
* 

### Actual behavior:
I need to add my own language to zammad ( Currently is not available as i see, I submitted an issue  #963  )
I think its better to add new parameter in language packs (*.yml )  for languages directions : some languagess are LTR( Letf-to-Right )  like English and some others are RTL ( Right-to-ledt )  like Arabic, Persian, ... Would be good if usersswitch to RTL language, The RTL custom Css load automatically.
Any advise!?

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment]
Hi @mmojadad - I don't know why your issues were gone and are now back again. However, in the meantime we added RTL support. There are still some issues open but in general it's supported. So I'll close this issue now.
