### ISSUE TITLE
Telegram API Token needs https?

### ISSUE THREAD

**Issue by KlyX84** [zammad/zammad#1030]
Hi guys,

just added a new bot in telegram and got the API Token. So far so good, but when Adding I get a "webhook url need to start with https://, you use http://"
My zammad uses https (with certificate) and I didn't find anything in Telegram to change that on their side.
What can I do here?
Thanks :)

**Comment by martini** [comment]
Hi @KlyX84 

the callback url for Telegram to Zammad is generated by the settings http_type, fqdn ... of your Zammad installation (by the way, also the http link in notification email).

So please check your "http_type" under Admin -> Settings -> System -> Base -> HTTP type.

Change it from **http** to **https** and it will work.

 -Martin

**Comment by KlyX84** [comment]
Hi @martini 

that's funny - the type was already on https - I saved the setting again and now it worked.
Thanks :)

**Comment by martini** [comment]
Thanks for feedback!

**Comment by Jeyakumarrathnaselvi** [comment]
Hi , I am facing the issue after enabling "http_type" under Admin -> Settings -> System -> Base -> HTTP type.

zammad caprover csrf token verification failed!

Can someone help pls

**Comment by MrGeneration** [comment]
Please do not hijack closed issues - especially not if your issue does not fit.
Ask your questions on the community (https://commuity.zammad.org).

In case you're a paying customer contact your support.
