### ISSUE TITLE
Update of object attribute leads to CSRF token verification failure

### ISSUE THREAD

**Issue by MartinBorg** [zammad/zammad#1034]
### Infos:

* Used Zammad version: 1.5.0-1493714886.828fb5d.jessie
* Used Zammad installation source: deb
* Operating system: Debian 8
* Browser + version: Python 3 requests 2.4.3-6 on Debian 8

### Expected behavior:

* Update of object attribute should be possible, like described in https://docs.zammad.org/en/latest/api-object.html#update

### Actual behavior:

There is no visible change. The log shows a `CSRF token verification failed`, while other API calls seem to work fine.

```
I, [2017-05-02T16:32:25.683788 #23681]  INFO -- : Started PUT "/api/v1/object_manager_attributes/:52" for 192.168.xxx.x at 2017-05-02 16:32:25 +0200
I, [2017-05-02T16:32:25.688749 #23681]  INFO -- : Processing by ObjectManagerAttributesController#update as */*
I, [2017-05-02T16:32:25.688903 #23681]  INFO -- :   Parameters: {"data_option"=>{"min"=>0, "null"=>true, "default"=>nil, "max"=>888888888}, "id"=>":52", "object_manager_attribute"=>{"data_option"=>{"min"=>0, "null"=>true, "default"=>nil, "max"=>888888888}, "id"=>":52"}}
I, [2017-05-02T16:32:25.689916 #23681]  INFO -- : CSRF token verification failed
I, [2017-05-02T16:32:25.690729 #23681]  INFO -- : Completed 401 Unauthorized in 2ms (Views: 0.3ms | ActiveRecord: 0.0ms)
```

### Steps to reproduce the behavior:

* Create an object attribute type integer with default values
* Created a token with permissions "admin, admin.api, admin.object, admin.organization"
* Run a Python script to lower the maximum value for attribute "52": `{"data_option"=>{"min"=>0, "null"=>true, "default"=>nil, "max"=>888888888}, "id"=>":52", "object_manager_attribute"=>{"data_option"=>{"min"=>0, "null"=>true, "default"=>nil, "max"=>888888888}, "id"=>":52"}}`

**Comment by MartinBorg** [comment]
Here is a small script to confirm either the bug or my wrong using of the API:
```python
#!/usr/bin/python3

import argparse
import json

import requests


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--server', default='zammad.local')
    parser.add_argument('-t', '--token-file', default='token')
    return parser.parse_args()


def read_token(token_file):
    with open(token_file) as f:
        return f.read().strip()


if __name__ == '__main__':
    args = parse_args()

    url = 'https://' + args.server + '/api/v1/object_manager_attributes'
    headers = {'Authorization': 'Token token=%s' % read_token(args.token_file),
               'Accept': 'application/json',
               'Content-Type': 'application/json'}

    attributes = requests.get(url, headers=headers, verify=False).json()

    attribute = [el for el in attributes
                 if el['object'] == 'Ticket'
                 and el['name'] == 'issue1034'][0]

    attribute['data_option']['max'] = 888888888
    attr_id = attribute['id']

    requests.put(url + "/:" + str(attr_id), json.dumps(attribute),
                 headers=headers, verify=False)
```

**Comment by rolfschmidt** [comment]
Hi @MartinBorg 
thank you very much for your report. The bug should be fixed now in develop branch.

-Rolf

**Comment by rolfschmidt** [comment]
Updated: Also cherry-picked it so the commit will also join the version 1.5.1 ;-)
