### ISSUE TITLE
External MySQL/MariaDB Support

### ISSUE THREAD

**Issue by lithiumnetworks** [zammad/zammad#1035]
Forgive me if this comes across a bit ... lazy, its not I spent a few hours digging yesterday and a bit more time today. 

I need to setup Zammad, at least in an internal test environment using a MySQL cluster that we have running inside our environment. I was unable to yield helpful enough information to make this make this happen.  

I have installed from source using the yml file for msyql2 driver and went so far as to specify host and port but was unable to make the application work using that method. 

I guess my question is: where is the connection to the DB provider established within the application?

Here is the yml structure I was hoping would work: (from http://stackoverflow.com/a/7306399)
adapter: mysql
database: my_db
hostname: 127.0.0.1
username: root
password: 
socket: /tmp/mysql.sock
pool: 5
timeout: 5000

**Comment by tobibe** [comment]
Hello,

in my environment with an external MySQL-Server, we entered the Database setting in file

/opt/zammad/config/database.yml

with this content

production:
  adapter: mysql2
  database: zammad
  pool: 50
  timeout: 5000
  encoding: utf8
  username: zammad
  password: ****
  host: mysql-server-ip
  port: 3306

This works for us. But it depends a little from your environment. Ours is the production environment. You can append one for development or testing...

Greetings 
tobibe

**Comment by lithiumnetworks** [comment]
Thanks for confirming that this works. Were you able to run the rake commands with this external server?

Cheers,
AP

**Comment by tobibe** [comment]
We installed only the first version 1.0 from source code and switched for later versions to the package installation. 
In the 1.0 version, commands for creating and seeding worked without problems.
In Package installation, I didn't test the rake commands...

Cheers
tobibe

**Comment by martini** [comment]
@lithiumnetworks Zammad works also with external databases. Maybe the easiest way to setup would be the following:

1) Install mysql-server and zammad package on your os (the result will be an local mysql/zammad installation)
2) Stop zammad, dump the database and restore the database on your mysql-server.
3) Change database connection properties in config/database.yml 
4) Start zammad and continue working with zammad

 -=> That's all. Good luck! 🤞
