### ISSUE TITLE
Update to Zammad 1.5 with rpm -> db migrate error

### ISSUE THREAD

**Issue by Freev4lley** [zammad/zammad#1038]
Hello,

during the update process to Version 1.5 i got a db migrate error!?

Here are the yum output:

Resolving Dependencies
--> Running transaction check
---> Package zammad.x86_64 0:1.4.0-1489841235.6155511.centos7 will be updated
---> Package zammad.x86_64 0:1.5.0-1493743993.627df92.centos7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package    Arch       Version                                 Repository  Size
================================================================================
Updating:
 zammad     x86_64     1.5.0-1493743993.627df92.centos7        zammad      70 M

Transaction Summary
================================================================================
Upgrade  1 Package

Total download size: 70 M
Is this ok [y/d/N]: y
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
zammad-1.5.0-1493743993.627df92.centos7.x86_64.rpm         |  70 MB   03:23
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
  Updating   : zammad-1.5.0-1493743993.627df92.centos7.x86_64               1/2
# (Re)creating init scripts
Nothing to do.
Nothing to do.
Nothing to do.
# Enabling Zammad on boot
# Stopping Zammad
# database.yml found. Updating db...
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `id' for nil:NilClass
/opt/zammad/db/migrate/20170403000001_fixed_admin_user_permission_920.rb:252:in                                                                                                              `up'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:611:in `exec_migration'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:592:in `block (2 levels) in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:591:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:590:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:768:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:998:in `block in execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:1044:in `block in ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /connection_adapters/abstract/database_statements.rb:213:in `block in transactio                                                                                                             n'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /transactions.rb:220:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:1044:in `ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:997:in `execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:959:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:955:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:955:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:823:in `up'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:801:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /tasks/database_tasks.rb:137:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (requ                                                                                                             ired)>'
NoMethodError: undefined method `id' for nil:NilClass
/opt/zammad/db/migrate/20170403000001_fixed_admin_user_permission_920.rb:252:in                                                                                                              `up'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:611:in `exec_migration'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:592:in `block (2 levels) in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:591:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:590:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:768:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:998:in `block in execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:1044:in `block in ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /connection_adapters/abstract/database_statements.rb:213:in `block in transactio                                                                                                             n'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /transactions.rb:220:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:1044:in `ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:997:in `execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:959:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:955:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:955:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:823:in `up'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /migration.rb:801:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /tasks/database_tasks.rb:137:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record                                                                                                             /railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (requ                                                                                                             ired)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
== 20170403000001 FixedAdminUserPermission920: migrating ======================
# Starting Zammad
# Creating webserver bootstart
# Restarting webserver nginx
################################################################################                                                                                                             ####

Add your FQDN to servername directive in /etc/nginx/conf.d/zammad.conf
and restart your webserver if you're not testing locally
or open http://localhost/ in your browser to start using Zammad.

 Remember to enable selinux and firewall rules!

Use the follwing commands:
        setsebool httpd_can_network_connect on -P
        firewall-cmd --zone=public --add-service=http --permanent
        firewall-cmd --zone=public --add-service=https --permanent
        firewall-cmd --reload

################################################################################                                                                                                             ####
  Cleanup    : zammad-1.4.0-1489841235.6155511.centos7.x86_64               2/2
  Verifying  : zammad-1.5.0-1493743993.627df92.centos7.x86_64               1/2
  Verifying  : zammad-1.4.0-1489841235.6155511.centos7.x86_64               2/2

Updated:
  zammad.x86_64 0:1.5.0-1493743993.627df92.centos7

What can i do?

### Infos:

* Used Zammad version: 1.4 -> 1.5 
* Used Zammad installation source: rpm 
* Operating system: centos 7
* Browser + version: Firefox 53

**Comment by Freev4lley** [comment]
I removed ".id" in row 252 of /opt/zammad/db/migrate/20170403000001_fixed_admin_user_permission_920.rb  

And now the migration process finished?

**Comment by Freev4lley** [comment]
Any ideas from the support team how I can solve the problem?

Thanks for help!!

**Comment by monotek** [comment]
@martini ?

**Comment by martini** [comment]
Hi @Freev4lley 

can you copy the lines around 252 of db/migrate/20170403000001_fixed_admin_user_permission_920.rb here?

There was a bugfix 10 days ago https://github.com/zammad/zammad/commit/5e7062295b92bb69f6c498ededf0479d57c06419#diff-1ae2e01986158e6a8269a61813ea2baa

If it's already the new file, what is the output of:

`zammad run "rails r 'p Ticket::Priority.find_by(default_create: true)'"`

and 

`zammad run "rails r 'p Ticket::Priority.all'"`

**Comment by Freev4lley** [comment]
I have just updated again with the newest release, but the error persists.

The output of: zammad run "rails r 'p Ticket::Priority.find_by(default_create: true)'"

/usr/bin/zammad: line 285: [: too many arguments
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `eval': /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62: unterminated string meets end of file (SyntaxError)
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `<top (required)>'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:90:in `runner'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from /opt/zammad/bin/rails:4:in `require'
        from /opt/zammad/bin/rails:4:in `<main>'

And the output of: zammad run "rails r 'p Ticket::Priority.all'"

/usr/bin/zammad: line 285: [: too many arguments
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `eval': /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62: unterminated string meets end of file (SyntaxError)
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `<top (required)>'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:90:in `runner'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from /opt/zammad/bin/rails:4:in `require'
        from /opt/zammad/bin/rails:4:in `<main>'

Thanks!!

**Comment by martini** [comment]
The commandos seems to be wrong, please try without ""

`zammad run rails r 'p Ticket::Priority.find_by(default_create: true)'`

and 

`zammad run rails r 'p Ticket::Priority.all'`

**Comment by Freev4lley** [comment]
ok, now it work´s ;)

[root@support ~]# zammad run rails r 'p Ticket::Priority.find_by(default_create: true)'
#<Ticket::Priority id: 3, name: "3 normal", note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2011-10-07 09:36:57", updated_at: "2011-10-07 09:36:57", default_create: true>

[root@support ~]# zammad run rails r 'p Ticket::Priority.all'
#<ActiveRecord::Relation [#<Ticket::Priority id: 4, name: "4 high", note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2011-10-07 09:36:57", updated_at: "2011-10-07 09:36:57", default_create: false>, #<Ticket::Priority id: 1, name: "1 very low", note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2011-10-07 09:36:57", updated_at: "2011-10-07 09:36:57", default_create: false>, #<Ticket::Priority id: 5, name: "5 very high", note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2011-10-07 09:36:57", updated_at: "2011-10-07 09:36:57", default_create: false>, #<Ticket::Priority id: 3, name: "3 normal", note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2011-10-07 09:36:57", updated_at: "2011-10-07 09:36:57", default_create: true>, #<Ticket::Priority id: 2, name: "2 low", note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2011-10-07 09:36:57", updated_at: "2011-10-07 09:36:57", default_create: false>]>

**Comment by martini** [comment]
Yes it looks good. It's a migration from OTRS?

What is the output of `zammad run rake db:migrate` now?

**Comment by Freev4lley** [comment]
Yes it is a OTRS migration ;)

== 20170403000001 FixedAdminUserPermission920: migrating ======================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `id' for nil:NilClass
/opt/zammad/db/migrate/20170403000001_fixed_admin_user_permission_920.rb:252:in `up'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:611:in `exec_migration'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
NoMethodError: undefined method `id' for nil:NilClass
/opt/zammad/db/migrate/20170403000001_fixed_admin_user_permission_920.rb:252:in `up'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:611:in `exec_migration'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `ddl_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by martini** [comment]
Hi @Freev4lley 

I saw the bugfix from 10 days ago was not in stable (only in development). I added it to stable too.

Please can you try a new package update of Zammad again?

The new package gut built 45 minutes ago https://packager.io/gh/zammad/zammad#stable

Thanks for feedback!

 -Martin

**Comment by Freev4lley** [comment]
Hi,

now the update / database migration process run without any problems!

Thanks for your support!!!!

**Comment by martini** [comment]
Thanks for feedback!
