### ISSUE TITLE
Allow agent to select per ticket whether customer gets email notification on create

### ISSUE THREAD

**Issue by MartinBorg** [zammad/zammad#1039]
### Infos:

* Used Zammad version: 1.5.0-1493743993.627df92.jessie
* Used Zammad installation source: deb
* Operating system: Debian 8
* Browser + version: Firefox 45.8.0 on Debian 8

### Expected behavior:

* When customer calls and agent writes down the ticket, it would be nice, if the agent could decide, whether customer gets informed about the new ticket or not. For most tickets, notification is useful, because the issue might be complex and it takes time to solve it. Sometimes, however, a ticket is a trivial case and solved just by answering a question by phone. Still, the ticket needs to be entered for QA and legal reasons.

### Actual behavior:

* Notification to customer on ticket creation is "always" or "never".

### Simple workaround:

* When entering the ticket, agent can assign it to themself. After creating the ticket, they can change the customer to the correct one.

**Comment by babakkazemi** [comment]
We solved it like this:
2 groups, 1 with triggers, 1 without.
You select the group you create the ticket in and therefore can control whether the customer receives notifications or not

**Comment by MartinBorg** [comment]
@babakkazemi Ah, good idea. Now I solved it similar, but not with a group:

- I added a new boolean in the `Ticket` object name "Notify Customer?", defaulting to `true`
- I added to the notification trigger the condition, that this field must be `true`
- agents can set it to "no" (= `false`), when they like

I think, this solves the problem completely and no new feature is required. Closing.
