### ISSUE TITLE
Ticket history in answer via email

### ISSUE THREAD

**Issue by bastians** [zammad/zammad#1043]
### Infos:

* Used Zammad version: 1.3.1
* Used Zammad installation source: Source
* Operating System: Intel Mac OS X 10_12_3
* Browser: Chrome Version 58.0.3029.81

### Expected behavior:

When you reply on a ticket and answer via email, the complete ticket history of a conversation should be added. 

### Actual behavior:

When you reply on a ticket and answer via email, the ticket history of a conversation is not added.

### Steps to reproduce the behavior:

Create a ticket via email (customer) > reply on the ticket via email (agent) > answer again via email (customer) > reply on the ticket via email (agent)

**Comment by babakkazemi** [comment]
It is a feature, not a bug :-)
Before answering, highlight the part above you want to include, click answer, and the highlighted part is inside your answer

**Comment by bastians** [comment]
@babakkazemi Oooh, sorry :) Then I will create a feature request but thanks for the hint with highlighting, I guess that helps already!

**Comment by ThePatzen** [comment]
I would need this feature too!
It would also be a possibility to attach all public answers in the emails.

**Comment by hanneshal** [comment]
Duplicate of https://github.com/zammad/zammad/issues/571

**Comment by martini** [comment]
And is already implemented for Zammad 2.0. 🦅 

Showcase: https://github.com/zammad/zammad/issues/571#issuecomment-315009230
