### ISSUE TITLE
CSS Issue within the editor

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#1044]
### Infos:

* Used Zammad version: latest 1.5
* Used Zammad installation source: source
* Operating system: macOS
* Browser + version: Safari / Chrome latest

### Expected behavior:

* There should be no coloured-background-span element in the text box

### Actual behavior:

* There is a span 

### Steps to reproduce the behavior:

* If you enter text into the text box for note or reply
* put a newline in it 
* remove this newline
* all following text will get encapsulated by a span+colour. 

![funny_things](https://cloud.githubusercontent.com/assets/804939/25736956/65d68e6e-3175-11e7-8785-c8199018a581.gif)

**Comment by hanneshal** [comment]
![funnyspan](https://cloud.githubusercontent.com/assets/804939/25737119/4b65fdca-3176-11e7-8049-da692bf1a5d6.jpg)
Added another image, because GIF + compression :/

**Comment by martini** [comment]
I can also reproduce it. The span has an css background color:

<img width="591" alt="screen shot 2017-05-05 at 09 36 43" src="https://cloud.githubusercontent.com/assets/110226/25737143/7174d950-3176-11e7-8e73-cd4de2d62f0f.png">

**Comment by mrflix** [comment]
So where is that coming from?

**Comment by martini** [comment]
> So where is that coming from?

If I remove the following line I can't reproduce it anymore:
https://github.com/zammad/zammad/blob/develop/app/assets/stylesheets/zammad.scss#L265

Then the span looks like:

<img width="545" alt="screen shot 2017-05-05 at 09 59 01" src="https://cloud.githubusercontent.com/assets/110226/25737703/8363b9d0-3179-11e7-899c-31aa447cb0c9.png">

It would be great to force the content editable area to not insert background-color attributes at all.
