### ISSUE TITLE
Umlaute not honoured in customer search

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#1049]
### Infos:

* Used Zammad version: 1.5.x
* Operating system: hosted at zammad.com
* Browser + version: Vivaldi 1.9

### Expected behavior:

* You can search customers with names containing Umlaut ("ü")

### Actual behavior:

* You cannot umlaut

### Steps to reproduce the behavior:

* Have a Customer with Umlaut.
* Create a new ticket.
* Search the existing Cüstomer.
* Have no result.

In the screenshot I try to find the 2nd customer Stück***********:
![screenshot-2017-05-05-211932](https://cloud.githubusercontent.com/assets/26226303/25760838/edceb2ca-31d8-11e7-8f86-5540f9a4e505.png)

But when umlauting the search result is cleared.

![screenshot-2017-05-05-212015](https://cloud.githubusercontent.com/assets/26226303/25760846/f95b67f0-31d8-11e7-8d8e-9b9937d78dce.png)

I didn't test this with other Umlauts, special characters or diacritical signs. This is up to you.

**Comment by MartinBorg** [comment]
It seems, that not only search for customers with umlauts is broken, but any search.

E.g. I have a note/comment with umlauts in it, and it does not show up in the search results when searching for the word with umlauts.

**Comment by hanneshal** [comment]
Is fixed/working fine in master 1.6.x.

**Comment by martini** [comment]
It's fixed in master https://github.com/zammad/zammad/commit/81c6aa0af04fce68f40f9ba510014e2a2f86f3c2
