### ISSUE TITLE
Shortcut Crtl+Shift+T collides with browser's function "restore last tab"

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#1052]
### Infos:

* Used Zammad version: 1.5
* Browser + version: at least Vivaldi 1.8, 1.9 and Firefox 49

### Expected behavior:

* Let me just re-open my last browser tab with ctrl+shift+t

### Actual behavior:

* ctrl+shift+t activates inline translation (admin only)
* shortcut works double: activates inline translation and browser reopens last tab, too
* to diable inline translation, you have to press the shortcut again, but then also the tab opens again

### Suggestion

* Put a on/off switch into the settings. I can imagine that this function is less frequently used (hint: this is just my personal opinion)
* Create a "Shortcuts" menu in the settings to let the user fully configure his/her preferred shortcuts

**Comment by AND51** [comment]
Another very important shortcut: ctrl+shift+w collides with "close all browser tabs" which leads to the browser killing itself!

Less important: How are you supposed to press ctrl+shift+shift+tab? Use both shift-keys? xD
![screenshot-2017-05-05-221833](https://cloud.githubusercontent.com/assets/26226303/25762990/4b1e4fe6-31e1-11e7-8580-63bcbcee9254.png)



Shall I open another issues for these?

**Comment by rolfschmidt** [comment]
Hi @AND51 ,
please no more shortcut issues 😄 If you want you can discuss with us in this issue.

https://github.com/zammad/zammad/issues/656

We have a lot of shortcuts and currently it seems that we will ignore browser shortcuts in zammad to have some of our own shortcuts available instead. Its a problematic topic to solve and at the moment we dont have a better solution to handle shortcuts in all browsers on all plattorms.

Best regards,
Rolf
