### ISSUE TITLE
Box boundings not respected

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#1054]
### Infos:

* Used Zammad version: latest git, develop & master
* Used Zammad installation source: source
* Operating system: CentOS
* Browser + version: Google Chrome latest, macOS

### Expected behavior:

* Wrapping at the box limits when editing an article

### Actual behavior:

* Line will run "over" box limit and become invisible

### Steps to reproduce the behavior:

* Create or reply to an article

![image](https://cloud.githubusercontent.com/assets/378324/25794187/30e190a2-33d0-11e7-80a4-801d3f99a0d1.png)

**Comment by martini** [comment]
@mrflix it seems that it is related to https://github.com/zammad/zammad/commit/4b670b07863d3cc209cb27bf51e83ae8b90f2a91

**Comment by mrflix** [comment]
It must have been `white-space: pre;`. I added it because when you paste text with indentation the indentation gets lost. With `pre` it stays. But this side effect is of course unacceptable.
