### ISSUE TITLE
CROWDFUNDING - Integrations of SuiteCRM, Magento, Mailchimp, Prestashop, Aweber, Mailtrain, etc.

### ISSUE THREAD

**Issue by sunshine450** [zammad/zammad#1056]
Hello everyone,

what do you think would happen, if Zammad created some small crowdfunding campaigns to fund wishes of the community?

I personally LOVE Zammad a lot, however it's too isolated from other programs / apps.

Interesting integrations could be:

SuiteCRM
Magento
Prestashop
Mailtrain
Mailchimp
Aweber

I am especially interested in SuiteCRM, Magento and Mailtrain.

This way, the whole solution could be kept open source and working together seamlessly.

Unfortunately, custom development can be very expensive, so crowdfunding sounds like a promising idea.

Legal notice:
I am NOT planning opening a crowdfunding campaign myself and I am NOT suggesting anything. I am just curious what would happen.... consider this posting as kind of a poll: what do you think? Would it make sense for Zammad to open such Crowdfunding campaigns?

Would there be support from the community?

It would be awesome, if an official staff member of Zammad would reply too!

Regards,
Sunshine450

**Comment by thorsteneckel** [comment]
Please move this over to our [community board](http://community.zammad.org/) if still relevant since it's not a actual issue. Thanks!
