### ISSUE TITLE
Used width of area

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#1059]
### Infos:

* Used Zammad version: develop/master
* Used Zammad installation source: source
* Operating system: CentOS
* Browser + version: Google Chrome latest, macOS

### Expected behavior:

* The used width of the available area when creating a new ticket should be the same when replying/creating an article of an existing ticket.

### Actual behavior:

* Used area is smaller

### Steps to reproduce the behavior:

* Create a new ticket: 
![image](https://cloud.githubusercontent.com/assets/378324/25839865/c68f8180-3499-11e7-8290-7648b740b87b.png)
* Compare with create a new article: 
![image](https://cloud.githubusercontent.com/assets/378324/25839895/ea2c0d34-3499-11e7-81b0-c982b8bd40c7.png)

**Comment by mrflix** [comment]
Why should it be the same?

**Comment by rkaldung** [comment]
What else is the use case for the spare area on the left and right of the textbox when creating a new ticket?

**Comment by martini** [comment]
So far as I know @rkaldung like it now.

**Comment by rkaldung** [comment]
Don't see any changes

**Comment by mrflix** [comment]
Yeah I didn't change it yet

**Comment by martini** [comment]
> Don't see any changes

Oh sorry. I thought the issue was in general. Now I see what you mean.

**Comment by martini** [comment]
It's in development.
