### ISSUE TITLE
Too many updates via deb.packager.io without information

### ISSUE THREAD

**Issue by TheRich-71** [zammad/zammad#1061]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: deb-package
* Operating system: Debian Linux 8.8

Hi there,
I am not sure if this is the right place to mention this, but I am wondering why it is necessary to install an update every few days. There are 15 versions of 1.5.0 visible in my system, and following [https://packager.io/gh/zammad/zammad#stable](url) the packaging system spawns a new release every 2-3 days.
I could understand if there would be some supporting information explaining why this release was built - of course I would be interested in security issues fixed immediately, but the package information shows nothing.

Besides this, I like Zammad and this should not be seen as criticism, but maybe as a hint...

**Comment by martini** [comment]
Hi @TheRich-71 

I guess that this is a duplicate of https://github.com/zammad/zammad/issues/1000

If you don't feel so, just reopen. Thanks a lot!

 -Martin
