### ISSUE TITLE
Autocomplete Email "to" - Field

### ISSUE THREAD

**Issue by morphxle** [zammad/zammad#1062]
When i'm forwaring a Email from outlook to zammad (forwarding email to support@.....de) and want to answer the customer over zammad i have the problem, the answer button wants to reply to myself. Everytime i have to manually insert the customers address.  

i think it would be a great feature to autocomplete the "to" field when im typing an address and not pushing "answer".

**Comment by lasat** [comment]
You can change the customer of the ticket to the correct one before starting answering.
This was something i was looking for and found after a while. 
![grafik](https://cloud.githubusercontent.com/assets/8647114/25860132/dd5be7b8-34e0-11e7-8456-558d3c714c87.png)

**Comment by morphxle** [comment]
@lasat thats what we are doing at the moment, but when you only tap on "answer" zammad sends a email to the email forwarder, not to the customer. Thats the reason; i want that autocomplete when inserting the reciever email address.

**Comment by lasat** [comment]
Your are right. Starting with the second email the correct customer will be emailed.

BTW: +1 for autocomplete email addresses.

**Comment by tobibe** [comment]
maybe this is doubled by #338 ?

Greetings
tobibe

**Comment by morphxle** [comment]
@tobibe u'r right!

**Comment by thorsteneckel** [comment]
Thanks for pointing this out @tobibe ! Please use issue #338 for updates and discussion.
