### ISSUE TITLE
Forwarding emails from a private inbox to your support portal

### ISSUE THREAD

**Issue by morphxle** [zammad/zammad#1065]
This is a quote from the fresh***k faq, is it possible to do something similar?

> Occasionally, your customers might email your support agents directly or you might have a mailbox full of emails that need to be converted to support tickets. This can be done by just forwarding them to your support email address. **_Tickets that are forwarded from a verified agent's email address will be created in the name of the customer who sent the email to the agent._** But when you forward existing emails from a mailbox (where this mailbox is not associated with an agent), the requester will be the mailbox and the time stamp of the ticket will be the time the email was forwarded.

**Comment by maege** [comment]
In some organisations agents are also customers so they open "normaly" tickets per Mail.

In our organisation we have full access to our helpdesk (MS Exchange) Mailbox so we can move or copy mails from our private mailbox to helpdesk mailbox by drag & drop within outlook. Afterwards Zammad imports that mails. If we want to add a E-Mail to an existing ticket, we add the [Ticket#1111] to the Subject before move/copy to helpdesk mailbox.

**Comment by morphxle** [comment]
@maege i hope you can read german : [https://www.helpdesk.rrze.uni-erlangen.de/otrs/public.pl?Action=PublicFAQZoom;ItemID=1234]

**Comment by morphxle** [comment]
https://www.helpdesk.rrze.uni-erlangen.de/otrs/public.pl?Action=PublicFAQZoom;ItemID=1234

**Comment by hanneshal** [comment]
I don't see a feature implementation here. If you don't use forward but redirect, which the most clients support, there is no need to build such a feature. And even if you have to use forward, you can always change the customer. 

Even microsoft supports this: 
https://support.office.com/en-us/article/Forward-and-redirect-email-automatically-9f124e4a-749e-4288-a266-2d009686b403

This is no setting for Zammad, but from your mailserver. 

regards
Johannes
