### ISSUE TITLE
Macros, Text Modules, depending on the group

### ISSUE THREAD

**Issue by morphxle** [zammad/zammad#1066]
In future releases will there a possibility to show macros and texmodules depend of the group or role of the user / ticket?

Thanks & Rgrd
Jens

**Comment by martini** [comment]
@morphxle It's currently not planned. But the enhancement makes sense. I tag it as enhancement.

**Comment by gwingend** [comment]
+1

**Comment by Dental-SW-Support** [comment]
++
See it in the same way as gwingend.
We work with few agent teams, so it is confusing for some agents, to see all the text modules and macros that they don't, but other team use .

**Comment by MrGeneration** [comment]
Locked conversation.
Please upvote the first entry if you want to tell us how important the Feature is.

Replies cause a lot of noise to over 1000 viewers. :(

**Comment by dennykorsukewitz** [comment]
The feature 'group-dependent text modules' was added: c788c3e

> Define groups for text modules, only certain text models should appear in certain groups.

duplication: #537
Available in version 3.1


----
The feature 'group-dependent macros' has not been implemented, yet.

**Comment by thorsteneckel** [comment]
@MrGeneration - as discussed: Please create the documentation and close the issue afterwards. Thanks!

EDIT: Group dependent macros are now available in `develop` and will be part of the 3.2 release. Thanks to @dennykorsukewitz  ❤️

**Comment by thorsteneckel** [comment]
@MrGeneration already created [the documentation PR](https://github.com/zammad/zammad-user-documentation/pull/23) which is going through the QA of @rlue. Since this issue covers the technical implementation and the documentation change is on its way it's save to already close this issue.
