### ISSUE TITLE
FR: Custom position for chat widget

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#1067]
Dear community,

As we are finally launching our website, our designer came up with the question whether the chat widget position is customizable - we will have a contact and teamviewer widget hovering on the right, and it would be nice to have the chat widget scrolling in from the right to have it look the same.

Best

Babak

**Comment by martini** [comment]
@mrflix What do you mean?

**Comment by mrflix** [comment]
Hey Babak! I'm confused by your use of directions. Did you want to say that you want it to be placed on the left side?

**Comment by babakkazemi** [comment]
@mrflix I would like to have a custom location for the chat widget, maybe with ability to select "bottom left", "bottom center", "bottom right" etc

**Comment by mrflix** [comment]
@babakkazemi you can accomplish "bottom left" with these lines of CSS:

```html
<style>
.zammad-chat {
  left: 30px;
  right: 0;
}
</style>
```
