### ISSUE TITLE
LDAP - two users with same mail address

### ISSUE THREAD

**Issue by maysv** [zammad/zammad#1069]
Hello,

In our AD we have a piece of users with two accounts.
for example max.mustermann and admin.max.mustermann - both have the same mailaddress - only one user has been imported. I thought when I change the mailadress at the admin user - both user were imported, but it's only one of them. Have you any idea - how can I fix that?

**Comment by thorsteneckel** [comment]
Hi @maysv - I created some lines that you can use on the [Zammad Rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console) to clean up the situation.

The following code will print the duplicates for one local user connection. If you can confirm that the LDAP ids (`source_id`) are the LDAP entries you are looking for you can uncomment the `duplicates.destroy_all` line which will delete the connection between local and remote user entries. This connection will be re-initialized by Zammad automatically with the next import.

```ruby
# find all entries where two remote entries have been mapped to one locale
ExternalSync.select('source, object, o_id, count(*)').group('source, object, o_id').having('count(*) > 1').each do |entry|

  dupicates = ExternalSync.where(source: entry.source, object: entry.object, o_id: entry.o_id)
  p duplicates
  # or delete them
  # duplicates.destroy_all
end
```

After you've cleaned up stat a new import run to re-initialize the connection. This is not mandatory and will be done automatically with the next run in max ~1 hour.
```ruby
# start new LDAP sync
job = ImportJob.create(name: 'Import::Ldap', payload: Setting.get('ldap_config'))
job.delay.start
```

Please note that this won't delete the users - just the connection to your LDAP entries. There are no negative side effects when deleting those. Zammad just needs to reinitialize these connections.

Feedback is greatly appreciated. 🚀

**Comment by maysv** [comment]
Thanks for your quick response @thorsteneckel!

This is maybe a stupid question, but how can I start the "Zammad Rails console" ? 😞

**Comment by thorsteneckel** [comment]
Please see the link above.

**Comment by maysv** [comment]
Thank you @thorsteneckel 
I got it - now the groups are right imported!

Everything just works! 👍 

🚀 😄

**Comment by thorsteneckel** [comment]
Nice! Glad to hear. Closing now. 🚀
