### ISSUE TITLE
“zammad” command not available - alternatives?

### ISSUE THREAD

**Issue by dennybresch** [zammad/zammad#1073]
You get an error when you want to run the following command on Docker-Host

```
zammad run rails r "Setting.set('es_url', 'http://zammad_elasticsearch:9200')"
```

"This manual uses the “zammad” command which is only available if you installed Zammad from one of our package repos."

Are there any alternatives for these commands?

**Comment by monotek** [comment]
Just run without zammd run prefix:
* rails r "Setting.set('es_url', 'http://zammad_elasticsearch:9200')"

**Comment by dennybresch** [comment]
The correct command is:

**docker-compose exec zammad-railsserver bash -c "cd; bundle exec rails r \"Setting.set('es_url', 'http://zammad-elasticsearch:9200')\""**

**Comment by monotek** [comment]
Why do you want to do this anyway?

Its already done in: https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad-railsserver/docker-entrypoint.sh

**Comment by dennybresch** [comment]
After updating, the Elasticsearch container is not accessible via URL example.com/#report.

Error: {"error": "Unable to process POST at http://elasticsearch:9200/zammad_production/Ticket/_search\n#\u003cUserAgent::Result:0x007f0a6c158358@success=false,@body=nil,@data=nil,@code=0,@content_type=nil,@error=\"#\u003cSocketError: Failed to open TCP connection to elasticsearch: 9200 (getaddrinfo: name or service not known) \ u003e \" \ u003e "}
 
The container has the name zammad_elasticsearch in the current docker-compose version.

The customer wanted to adjust this.

**Comment by monotek** [comment]
I've changed https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad-railsserver/docker-entrypoint.sh to set the es url on every start to make it updatesave.
