### ISSUE TITLE
Custom Ticket States via WebApp

### ISSUE THREAD

**Issue by kmclea16** [zammad/zammad#1076]
Hi all,

Is it possible to create custom ticket states such as "waiting on customer" and "waiting on third party", or is this not possible?

Thanks

**Comment by zheonline** [comment]
We are also looking for this! :)

**Comment by Jonske** [comment]
It would be great if there is a function in the future!

**Comment by meikel83** [comment]
Yes this possibility would be really great.

**Comment by IQNeoXen** [comment]
+1

Missing this feature! Would be really great to have imo

**Comment by philku79** [comment]
+1

**Comment by thorsteneckel** [comment]
Locking conversation. There is no new input. +1 and requesting comments create noise and distraction. We are working hard on the next upcoming/most requested features and projects of our support customers. If you want to state your interest in the feature and give valuable input please give the initial post a 👍 reaction and we are able to evaluate it. We will lock all distracting issues from now on. Thanks for your understanding.

**Comment by martini** [comment]
Short update in the meantime, by using this you can create a custom ticket state via `zammad run rails c`:

https://github.com/zammad/zammad-documentation/blob/master/admin-console.rst#add-new-ticket-state

**Comment by Mirtaaa** [comment]
Closing this issue for structuring reasons. Created a new one here: https://github.com/zammad/zammad/issues/4862
