### ISSUE TITLE
Confusing setting "HTTP type"

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#1079]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: DEB
* Operating system: Debian 8

### Problem Description

The setting System -> Base -> HTTP type, described on the configuration page as "Define the http protocol of your instance." is confusing, as it does **not** define the http protocol at all.  Instead it merely configures, which protocol is used in the links written in the various notifications

### Proposed Solution

Better: Make this setting do what it describes (configure your webserver to use http or https)
Pragmatic: Change the description on the page to adapt it to what the setting really does

**Comment by rolfschmidt** [comment]
Hi @fthommen ,
basicially the most of the config options in zammad are using the word "define" to start the description of the config option. There is also the dropdown with the values and in my eyes this option is pretty clear. If you really want a change for this text, feel free to create a pull request:

Example config option editing migration:
https://github.com/zammad/zammad/blob/develop/db/migrate/20170314000001_fixed_translation2.rb

Update setting in seeds.rb:
https://github.com/zammad/zammad/blob/develop/db/seeds/settings.rb#L262

Please understand, that there is a lot of options with this kind of wording and a change would end in a full rewrite of all descriptions.

-Rolf
