### ISSUE TITLE
Scheduler won't start because of missing DB connection on PostgreSQL 9.2.18

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#1080]
Hi,

I justs did a "yum update" yesterday late evening which has raised Zammad from 1.5.0 to 1.6.0 (I'm using the dev repo). Unfortunately this has completely killed my helpdesk.

The web server is not responding, restart of the Zammad service does not help. In the production.log I see periodically and only this line:

```
I, [2017-05-13T09:30:33.650744 #7411]  INFO -- : Setting.set(product_logo, "c29c4508870c9e7593e1e303c492d48c.png")
I, [2017-05-13T09:30:38.206507 #7434]  INFO -- : Setting.set(product_logo, "c29c4508870c9e7593e1e303c492d48c.png")
I, [2017-05-13T09:30:42.677015 #7456]  INFO -- : Setting.set(product_logo, "c29c4508870c9e7593e1e303c492d48c.png")
I, [2017-05-13T09:30:46.872796 #7484]  INFO -- : Setting.set(product_logo, "c29c4508870c9e7593e1e303c492d48c.png")
I, [2017-05-13T09:30:51.148127 #7509]  INFO -- : Setting.set(product_logo, "c29c4508870c9e7593e1e303c492d48c.png")

```

This is the output of scheduler_err.log:
```

/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `exec': could not receive data from server: Bad file descriptor (PG::UnableToSend)
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `dealloc'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:198:in `block in clear'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:197:in `each_value'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:197:in `clear'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:258:in `clear_cache!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:310:in `disconnect!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:293:in `disconnect!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:461:in `rescue in checkout_and_verify'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:455:in `checkout_and_verify'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
        from /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
        from /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:87:in `connection'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:39:in `find_by_sql'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:639:in `exec_queries'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:515:in `load'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:243:in `to_a'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
        from /opt/zammad/app/models/scheduler.rb:69:in `cleanup'
        from /opt/zammad/app/models/scheduler.rb:15:in `threads'
        from script/scheduler.rb:59:in `block in <main>'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons/application.rb:266:in `block in start_proc'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons/application.rb:275:in `start_proc'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons/application.rb:296:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons/controller.rb:56:in `run'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons.rb:197:in `block in run_proc'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons/cmdline.rb:92:in `catch_exceptions'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/daemons-1.2.4/lib/daemons.rb:196:in `run_proc'
        from script/scheduler.rb:49:in `<main>'
```

Any ideas before I need to push in my VM backup which will cost me a day of data?

**Comment by monotek** [comment]
Try to restart the database and zammad:
* systemctl restart postgres
* systemctl restart zammad

For the future. Do a backup before running updates:
* https://docs.zammad.org/en/latest/appendix-backup-and-restore.html

**Comment by jacotec** [comment]
Restart does not work, I've already tried. Looks like I need to push in my backup.

I guess just restoring some directories does not help due to the database?

**Comment by thorsteneckel** [comment]
Seems to be my fault 💩 I'll have a look at it asap and let you know. Sorry for the circumstances.

**Comment by jacotec** [comment]
OK, I'll wait with the restore

**Comment by thorsteneckel** [comment]
Are you able to access the [Zammad Rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console)? If so please execute the following command and post the output:

`Delayed::Job.all`

Looks somehow as if your DB doesn't want to get that query. I'll investigate further in the meantime.

**Comment by thorsteneckel** [comment]
What PG version are you using?

**Comment by jacotec** [comment]
Will check in around 20-30 mins, I'm currently on the road

**Comment by thorsteneckel** [comment]
Hm... can't reproduce any errors on my local and our CI environment. Something seems wrong with the DB connection. Would be interesting which PG version you are using and what the [Zammad Rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console) command returns.

If you aren't able to to execute the command without an error it would be interesting to see what's in the DB table `delayed_jobs` of your `zammad_production` database.

I'm afk now for ~1 hour.

**Comment by jacotec** [comment]
[root@mail ~]# pg_config --version
PostgreSQL 9.2.18

**Comment by jacotec** [comment]
[root@mail ~]# zammad run rails c
Loading production environment (Rails 4.2.7.1)
irb(main):001:0> Delayed::Job.all
=> #<ActiveRecord::Relation []>
irb(main):002:0>

**Comment by jacotec** [comment]
I went back to the last 1.5.0 version and I'm online again:

` yum downgrade zammad-1.5.0-1492775576.d93c1ba.centos7
`
Seems an issue with the 1.6.0 ... I've tried some 1.6.0 versions (of course not all) and they all had the problem.

**Comment by thorsteneckel** [comment]
Sorry - took longer than expected. Thanks for your feedback and the investigation. 

Your current version is pretty old now - [22 days to be exactly](https://github.com/zammad/zammad/commit/d93c1ba). Seems something in between is breaking the DB connection to your PostgreSQL 9.2.18. Strangely the same ruby code works on the Zammad Rails console but doesn't when executed by the scheduler. I'll try to reproduce this in a test VM.

I'll let you know what I've found out.

**Comment by jacotec** [comment]
OK, thanks. Let me know if you need anything from my side!

**Comment by thorsteneckel** [comment]
Update: I'm able to reproduce this on the latest version of the 1.5 release. Please don't update! I'll let you know if I find out why this is happening.

**Comment by jacotec** [comment]
Good news! Interesting that the latest 1.5 works for me but not the 1.6.0

**Comment by thorsteneckel** [comment]
Strange! Which version are you using exactly?

```
[zammad@localhost zammad]$ yum info zammad
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: centos.mirrors.as250.net
 * epel: nl.mirror.babylon.network
 * extras: centos.mirrors.as250.net
 * updates: centos.mirrors.as250.net
elasticsearch-5.x                                                     134/134
Installed Packages
Name        : zammad
Arch        : x86_64
Version     : 1.5.0
Release     : 1494609142.a96442f.centos7
Size        : 236 M
Repo        : installed
From repo   : zammad
Summary     : Zammad is a web based open source helpdesk/customer support
            : system
URL         : https://zammad.org
License     : unknown
Description : Zammad is a web based open source helpdesk/customer support
            : system
```

**Comment by thorsteneckel** [comment]
Seems the DB connection is lost somehow... Following changes fixes it for me on CentOS 7, PostgreSQL 9.2.18 with latest Zammad 1.5 or 1.6. Both are broken without that.

```diff
diff --git a/app/models/scheduler.rb b/app/models/scheduler.rb
index 0b2825abe..5637249e9 100644
--- a/app/models/scheduler.rb
+++ b/app/models/scheduler.rb
@@ -11,6 +11,13 @@ class Scheduler < ApplicationModel

     Thread.abort_on_exception = true

+    # reconnect in case db connection is lost
+    begin
+      ActiveRecord::Base.connection.reconnect!
+    rescue => e
+      logger.error "Can't reconnect to database #{e.inspect}"
+    end
+
     # cleanup old background jobs
     cleanup
```

That block is taken from down below in the same method but it's executed in the loop. I have to check how to handle this.

Working on a commit.

**Comment by jacotec** [comment]
See above, the downgrade to this got me back to business:

yum downgrade zammad-1.5.0-1492775576.d93c1ba.centos7

**Comment by thorsteneckel** [comment]
Ah ok - now I get it. But as stated above `zammad-1.5.0-1492775576.d93c1ba.centos7` is not the latest version. It's 22 days old. The following commit breaks at least PostgreSQL 9.2.18 - not sure why.

https://github.com/zammad/zammad/commit/199686dce1aa53431802c65279b1027703091e93

Further investigation required here.

**Comment by jacotec** [comment]
OK, I'll stay with that version until a fix is available ;-)

**Comment by thorsteneckel** [comment]
Hi @jacotec - I wasn't able to find a better solution for this. Maybe @martini has one?

However - would be great if you could try the update again (in >45 min, till the package is build) and give some feedback.

**Comment by martini** [comment]
> Hi @jacotec - I wasn't able to find a better solution for this. Maybe @martini has one?

I have not other solution. This one is good for me.

**Comment by jacotec** [comment]
> However - would be great if you could try the update again (in >45 min, till the package is build) and give some feedback.

Sorry to say, that does **not** work for me!

I did the update and it went to zammad-1.6.0-1494688245.9934286.centos7.x86_64 which was build 20hrs ago - same issue! It's not starting.

Going back to the 1.5.0 mentioned above.

**Comment by thorsteneckel** [comment]
Hi @jacotec - thanks for your feedback. I wasn't able to reproduce the error (again) after updating my 1.5 to zammad-1.6.0-1494688245.9934286.centos7.x86_64. I just did a `yum update zammad` and even restarted the system. Everything works as expected. What were the steps you did?

**Comment by jacotec** [comment]
I also did a yum update ... after it was still dead, I've restarted postgres and zammad - still nothing. :-(

**Comment by thorsteneckel** [comment]
:/ Could you please run `sudo systemctl restart zammad-worker` and post the complete content of the file `log/scheduler_err.log`. Thanks!

**Comment by jacotec** [comment]
The scheduler_err.log stays empty at 0 bytes with this build, the error can be seen in the production.log:

```
E, [2017-05-14T21:48:34.183693 #6480] ERROR -- : Can't reconnect to database #<PG::UnableToSend: could not receive data from server: Bad file descriptor
>
```

**Comment by thorsteneckel** [comment]
Are there any more lines like above? 

E.g:
```
from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `dealloc'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:198:in `block in clear'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:197:in `each_value'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:197:in `clear'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:258:in `clear_cache!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:310:in `disconnect!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:293:in `disconnect!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:461:in `rescue in checkout_and_verify'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:455:in `checkout_and_verify'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
```

This helps a lot finding the root of the error. Looks like this might be another location/cause since the scheduler would log into the `log/scheduler_err.log` file.

Or maybe you could send the whole file to support@zammad.com so I can take a look myself? I'll try to reproduce this again tomorrow.

**Comment by jacotec** [comment]
Hi Thorsten,

no more error lines in the log, I've mailedthe complete logfile to the support email.

Thanks for your support!

**Comment by thorsteneckel** [comment]
Hi @jacotec - this is really a strange behavior! The connection is lost somehow on a lower pg (Ruby PostgreSQL connection gem) level. The detection if the connection is still open is wrong which lets Rails fail and log the error. The strange part is that after losing the connection while disconnecting (!) the connection is ready to get used. That's why we will just ignore this little detail (with the commit above) and go on and work as we would be in other setups where this works perfectly fine 🤓 

Feedback would be great! Latest release is ready to get tested 🚀

**Comment by jacotec** [comment]
Hi @thorsteneckel 

New build, new error codes:

```
E, [2017-05-15T16:14:30.820646 #32522] ERROR -- : Can't use Channel::Driver::Facebook: #<Koala::Facebook::ClientError: type: OAuthException, code: 32, message: (#32) Page request limited reached, x-fb-trace-id: C/rqb1/G6H0 [HTTP 400]>
E, [2017-05-15T16:14:30.820762 #32522] ERROR -- : ["/opt/zammad/vendor/bundle/ruby/2.3.0/gems/koala-2.4.0/lib/koala/api/graph_api.rb:529:in `block in graph_call'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/koala-2.4.0/lib/koala/api.rb:80:in `api'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/koala-2.4.0/lib/koala/api/graph_api.rb:527:in `graph_call'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/koala-2.4.0/lib/koala/api/graph_api.rb:116:in `get_connection'", "/opt/zammad/app/models/channel/driver/facebook.rb:88:in `block in fetch_feed'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'", "/opt/zammad/app/models/channel/driver/facebook.rb:82:in `fetch_feed'", "/opt/zammad/app/models/channel/driver/facebook.rb:21:in `fetch'", "/opt/zammad/app/models/channel.rb:62:in `fetch'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/app/models/channel.rb:30:in `fetch'", "(eval):1:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:176:in `eval'", "/opt/zammad/app/models/scheduler.rb:176:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:143:in `block (2 levels) in start_job'", "/opt/zammad/app/models/scheduler.rb:142:in `loop'", "/opt/zammad/app/models/scheduler.rb:142:in `block in start_job'"]
```

Still not running unfortunately :-|

I'll send you the full production log and go back to my 1.5.0 ... got some practice meanwhile ;-)

**Comment by martini** [comment]
JFI: The following is no error, it's just the info that Facebook page rate limit is reached (it should go away if some minutes).

> E, [2017-05-15T16:14:30.820646 #32522] ERROR -- : Can't use Channel::Driver::Facebook: #<Koala::Facebook::ClientError: type: OAuthException, code: 32, message: (#32) Page request limited reached, x-fb-trace-id: C/rqb1/G6H0 [HTTP 400]>

I can of possible remote login, I can take a look (I'm interested in this issue).

**Comment by jacotec** [comment]
@martini : What kind of login do you need?

**Comment by martini** [comment]
> ssh or teamviewer would be fine

**Comment by jacotec** [comment]
Do you have access to my ticket 104468 @ your support desk? I don't want to post logins via GitHub ;-)

**Comment by martini** [comment]
Just for remark:

With Zammad 1.5 the Zammad application serve will only bind to localhost:3000 so for security reasons no direct access is possible by default anymore.

You can change it back with:

```
zammad config:set ZAMMAD_BIND_IP=0.0.0.0
systemctl restart zammad
```

 -Martin

**Comment by jacotec** [comment]
@martini : Thanks for posting the config change. Will this survive Zammad updates?

**Comment by monotek** [comment]
Yes

**Comment by martini** [comment]
I can confirm. It's update save (just tested right now).
