### ISSUE TITLE
websocket-server.rb and scheduler.rb Rack::LiveReload problem

### ISSUE THREAD

**Issue by dcalixto** [zammad/zammad#1085]
After download and install the app, on initialization of websocket-server.rb and scheduler.rb are showing this problem. someone know how to fix this issue?

```
script/websocket-server.rb start
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
      rake (>= 0.8.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/danielcalixto/Downloads/zammad/config/environments/development.rb:37:in `block in <top (required)>': uninitialized constant Rack::LiveReload (NameError)
```

```
script/scheduler.rb start
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
      rake (>= 0.8.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/danielcalixto/Downloads/zammad/config/environments/development.rb:37:in `block in <top (required)>': uninitialized constant Rack::LiveReload (NameError)



```

**Comment by martini** [comment]
Hi @dcalixto 

did you start with `bundle exec` ?

1. `bundle exec script/websocket-server.rb start`

2. `bundle exec script/scheduler.rb start`

Thanks for feedback!

 -Martin

**Comment by dcalixto** [comment]
Hello @martini , thank you for your interest!

here the log:

```
zammad bundle exec script/websocket-server.rb start
bundler: failed to load command: script/websocket-server.rb (script/websocket-server.rb)
NameError: uninitialized constant Rack::LiveReload
  /Users/danielcalixto/Downloads/zammad/config/environments/development.rb:37:in `block in <top (required)>'
  /Users/danielcalixto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `instance_eval'
  /Users/danielcalixto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `configure'
  /Users/danielcalixto/Downloads/zammad/config/environments/development.rb:1:in `<top (required)>'

```

```



zammad bundle exec script/scheduler.rb start
bundler: failed to load command: script/scheduler.rb (script/scheduler.rb)
NameError: uninitialized constant Rack::LiveReload
  /Users/danielcalixto/Downloads/zammad/config/environments/development.rb:37:in `block in <top (required)>'
  /Users/danielcalixto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `instance_eval'
  /Users/danielcalixto/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `configure'
  /Users/danielcalixto/Downloads/zammad/config/environments/development.rb:1:in `<top (required)>'
```

**Comment by martini** [comment]
@dcalixto thanks for feedback. If you have installed Zammad via packages, you need to use the os scripts like:

```
sudo systemctl status zammad-worker
sudo systemctl stop zammad-worker
sudo systemctl start zammad-worker
sudo systemctl restart zammad-worker
```

```
sudo systemctl status zammad-websocket
sudo systemctl stop zammad-websocket
sudo systemctl start zammad-websocket
sudo systemctl restart zammad-websocket
```

What is the output of that?

**Comment by martini** [comment]
Sorry, I'm a little bit confused `zammad run` is usually only used if you use the packages. But your Zammad home directory is different `/Users/danielcalixto/Downloads/zammad/`. Maybe you can give me some insight. Thanks.

**Comment by martini** [comment]
> NameError: uninitialized constant Rack::LiveReload

JFI: This seams that you have only installed your production gems, but your $RAILS_ENV is develop or is empty. Try:

1) export RAILS_ENV=production
2) bundle exec script/websocket-server.rb start
3) bundle exec script/scheduler.rb start

 -Martin

**Comment by dcalixto** [comment]
@martini  thank you for your help.
i downloaded the repo from here github and followed the `https://docs.zammad.org/en/latest/install-source.html` guide

so i did:

1. bundle install --without test development mysql
2. config/database.yml.pkgr config/database.yml

migrate de db and seed.

the **export RAILS_ENV=production** should i place it where?

**Comment by monotek** [comment]
It's a shell command...

**Comment by dcalixto** [comment]
@monotek thank you! problem solved!
just put export RAILS_ENV=production on terminal inside zammad folder.

**Comment by martini** [comment]
@dcalixto thanks for feedback!
