### ISSUE TITLE
Ticket Export

### ISSUE THREAD

**Issue by Jonske** [zammad/zammad#1087]
Hello Zammad Community,

i want to setup a new installation of Zammad, but i want to save the current tickets.
Is there a function in Zammad 1.5.x to export the tickets?

With kind regards,
Jonske

**Comment by martini** [comment]
Hi @Jonske 

in this case you need to dump your database and restore it in your new installation. There is currently no way to export only tickets and create them in a second system (you also have many references like users/customers/states/...).

In case you want to do so, I recommend to use the Zammad REST API to transform the tickets from on system to another system.

 -Martin

**Comment by monotek** [comment]
https://docs.zammad.org/en/latest/appendix-backup-and-restore.html
