### ISSUE TITLE
Switch elasticsearch standard operator from OR to AND

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#1090]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation package
* Operating system: Ubuntu 14.06.02
* Browser + version: FireFox 53.0

We installed elastic search and the default search operator for multiple keywords is 'OR'. If you type the search 'a b', it search for 'a OR b'. We usually want to use 'a AND b' if we type 'a b'.

The default operator can be submitted by the search query used by zammad for elastic search. Where do I have to configure this. Is this configuration possible in Zammad or do I have to do this in a elastic search configuration file.

Greetings
tobibe

**Comment by martini** [comment]
Hi @tobibe 

thanks for information. Can you give me a hint what the name for the default operator is?

Thanks,

 -Martin

**Comment by tobibe** [comment]
Hi @martini 

I found it in documentation of Elastic search:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

it's the parameter 'default_operator' where you can give the default one. 
And if this would be configurable in Zammad, it would be great :-)

Greetings,
tobibe

**Comment by martini** [comment]
How about to have this as default param to AND for all, normally a user expects an AND operator between two words?

**Comment by martini** [comment]
Behaviour will change in Zammad 1.6 to use AND operator per default.
