### ISSUE TITLE
Web application doesnt respond....!

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#1092]
Hi,
I 've installed Zammad on Centos 7 (Install on CentOS via RPM) with below conifguration but when I try to access web application there is not page responding, even no error on the page:
Webpage display:

This site can’t be reached
10.10.3.136 refused to connect.
Search Google for 136 3000
ERR_CONNECTION_REFUSED

I finished installation with executing Rake commands of database which seems everything was fine and config/database file of Zammad could create database and its tables inside of Mysql.

Configurations are as follows:
 
- mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper
-ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
-nginx version: nginx/1.12.0

 sudo systemctl status postgresql
● postgresql.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mon 2017-05-15 16:25:13 UTC; 57min ago
  Process: 5611 ExecStop=/usr/bin/pg_ctl stop -D ${PGDATA} -s -m fast (code=exited, status=0/SUCCESS)

 sudo systemctl status mysqld
● mysqld.service - MySQL Server
   Loaded: loaded (/usr/lib/systemd/system/mysqld.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-05-15 16:17:27 UTC; 1h 5min ago
     Docs: man:mysqld(8)
           http://dev.mysql.com/doc/refman/en/using-systemd.html

sudo systemctl status zammad
● zammad.service
   Loaded: loaded (/etc/systemd/system/zammad.service; enabled; vendor preset: disabled)
   Active: active (running) since xxxxxx
 Main PID: 5671 (sleep)
   CGroup: /system.slice/zammad.service
           └─5671 /bin/sleep infinity
May 15 16:25:21 zammad]: Started zamm...
May 15 16:25:21 zammad: Starting zam...
Hint: Some lines were ellipsized, use -l to show in full.

sudo systemctl status zammad-web
● zammad-web.service
   Loaded: loaded (/etc/systemd/system/zammad-web.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-05-15 16:25:21 UTC; 59min ago
 Main PID: 5674 (sleep)
   CGroup: /system.slice/zammad-web.service
           └─5674 /bin/sleep infinity

wget 10.10.3.136
--2017-05-15 17:24:46--  http://10.10.3.136/
Connecting to 10.10.3.136:80... connected.
HTTP request sent, awaiting response... 200 OK

But when I wanna reach Zammad web application there is no reposnse:
wget 10.10.3.136:3000
--2017-05-15 17:24:58--  http://10.10.3.136:3000/
Connecting to 10.10.3.136:3000... failed: Connection refused.

Database.yml:
production:
  adapter: mysql2
  database: zammad
  pool: 50
  timeout: 5000
  encoding: utf8
  username: zammad
  password: zammad
  host: 127.0.0.1

export PATH=$HOME/.gem/ruby/2.3.0/bin:$PATH
export GEM_HOME=$HOME/.gem/ruby/2.3.0
export RAILS_ENV=production
export RAILS_SERVE_STATIC_FILES=true
All executed as well ass other parts.

Besides, no firewall is enabled. Im thinking maybe Nginx is not connected to Zammad web application....I'd really appreciate to help in it.

Best,

**Comment by monotek** [comment]
I guess the problem is that you try to install zammad on a server with mysql and postgresql. 
If so you have to deinstall the database you don't need or you have to configure /opt/zammad/config/database.yml by hand, because zammad installer can't guess which database to use.

**Comment by hamzehmohammadnia** [comment]
I have installed MySql and then installed Zammad with RPM. So, afterwards, I have deactivated Postgresql database and changed database.yml  as:
Database.yml:
production:
adapter: mysql2
database: zammad
pool: 50
timeout: 5000
encoding: utf8
username: zammad
password: zammad
host: 127.0.0.1

Should I deinstall PostgreSQL? or deactivating works fine?

Thanks in advance,

**Comment by monotek** [comment]
As you prefer...

**Comment by hamzehmohammadnia** [comment]
Since I have already deactivated and it didnt work then I think I would retry deinstalling PostgreSQL. For my information, do you think should I follow this sequences to make Zammad working on MySQL would be functional?

1. Installing Zammad (RPM on Centos 7)
2. Deinstalling PostgreSQL
3. Installing MySQL 

Thanks,

**Comment by monotek** [comment]
Just install MySQL before you install Zammad so postgresql is not installed.

**Comment by hamzehmohammadnia** [comment]
I have tried with a clean installation and at the end, I can see Zammad logo on the tab of browser but still no connection to web portal. I have restarted zammad, zammad-web, zammad-worker and zammad-websocket but still no response on the web page. In mysql, I can see all the tables are created.
Thanks,

**Comment by martini** [comment]
@hamzehmohammadnia 

> This site can’t be reached
10.10.3.136 refused to connect.
Search Google for 136 3000
ERR_CONNECTION_REFUSED

Question, do you want to access Zammad via http://zammad_host or via http://zammad_host:3000 ?

And what Zammad version did you install?

**Comment by hamzehmohammadnia** [comment]
I'd prefer to reach without port number. Im using Zammad 1.5.0-1495017264.48b4945.centos7.

Every service is working properly and also DB user inserted and created initial tables... but still no response on web browser...

**Comment by martini** [comment]
Is port 3000 accessible form localhost? 

Maybe it's related to https://github.com/zammad/zammad/issues/1108 

Per default Zammad app server is not binding to 0.0.0.0, only to 127.0.0.1 for security reasons.

As workaround you can follow #1108 or simply configure nginx on your Zammad host.

**Comment by martini** [comment]
And if you use cents, make sure that you opened the http/https ports + allowed nginx network connections. Usually after RPM install you see the hint to se commands https://github.com/zammad/zammad/blob/develop/contrib/packager.io/functions#L245

```
setsebool httpd_can_network_connect on -P
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --zone=public --add-service=https --permanent
firewall-cmd --reload
```

**Comment by hamzehmohammadnia** [comment]
Thanks for your reply. The problem is that It was working at the beginning with Postgresql and then I stopped PostgreSQL service and installed Mysql to try it within. And with MySQL thingi it is struggling while DB and tables are created... I even dont have access to the web application via 3000 port.

**Comment by martini** [comment]
Thanks for feedback. Ok, so it seems that it's a configuration issue related to your os/services. In case you can contact our business services to help you (https://zammad.com/pricing -> Self hosted version).

**Comment by monotek** [comment]
Port 3000 is only opened on localhost. To access Zammad you have to use port 80 or 443, if https is configured in the webserver.

**Comment by hamzehmohammadnia** [comment]
As I have already mentioned, my goal is installing Zammad RPM on centos & MySQL & Apache. After fixing other issues of gem files, I fount some updates:
*Zammad Service status is Ok and working properly
*Zammad-web Service status is Ok and working properly
*MySQL is also working properly and all "rake commands" are successfully executed as follows:
-rake db:create
-rake db:migrate
-rake db:seed
But at the end, when I list following listening ports, I see no process (Rail or Puma) is listening to the port 3000. Therefore, no webfront would come up.
Which sounds the process of listening to the port is not yet initiated and working
The status of Zammad processes:
systemctl status zammad
● zammad.service
   Loaded: loaded (/etc/systemd/system/zammad.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-06-12 12:27:01 UTC; 2min 17s ago
 Main PID: 27719 (sleep)
   CGroup: /system.slice/zammad.service
           └─27719 /bin/sleep infinity

Jun 12 12:27:01 ...[1]: Started zammad.service.
Jun 12 12:27:01...[1]: Starting zammad.service...



 systemctl status postgresql
● postgresql.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql.service; disabled; vendor preset: disabled)
   Active: inactive (dead)


systemctl status mysqld
● mysqld.service - MySQL Server
   Loaded: loaded (/usr/lib/systemd/system/mysqld.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-06-12 12:26:56 UTC; 4min 11s ago
     Docs: man:mysqld(8)
           http://dev.mysql.com/doc/refman/en/using-systemd.html
  Process: 27535 ExecStart=/usr/sbin/mysqld --daemonize --pid-file=/var/run/mysqld/mysqld.pid $MYSQLD_OPTS (code=exited, status=0/SUCCESS)
  Process: 27429 ExecStartPre=/usr/bin/mysqld_pre_systemd (code=exited, status=0/SUCCESS)
 Main PID: 27539 (mysqld)
   CGroup: /system.slice/mysqld.service
           └─27539 /usr/sbin/mysqld --daemonize --pid-file=/var/run/mysqld/mysqld.pid

Jun 12 12:26:37 ...[1]: Starting MySQL Server...
Jun 12 12:26:56 ...[1]: Started MySQL Server.



systemctl status httpd
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-06-08 16:14:06 UTC; 3 days ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 4413 ExecReload=/usr/sbin/httpd $OPTIONS -k graceful (code=exited, status=0/SUCCESS)
 Main PID: 8430 (httpd)
   Status: "Total requests: 0; Current requests/sec: 0; Current traffic:   0 B/sec"
   CGroup: /system.slice/httpd.service
           ├─ 4415 /usr/sbin/httpd -DFOREGROUND
           ├─ 4416 /usr/sbin/httpd -DFOREGROUND
           ├─ 4417 /usr/sbin/httpd -DFOREGROUND
           ├─ 4418 /usr/sbin/httpd -DFOREGROUND
           ├─ 4419 /usr/sbin/httpd -DFOREGROUND
           ├─ 8430 /usr/sbin/httpd -DFOREGROUND
           └─29337 /usr/sbin/httpd -DFOREGROUND

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

systemctl status zammad-web
● zammad-web.service
   Loaded: loaded (/etc/systemd/system/zammad-web.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-06-12 12:27:04 UTC; 5min ago
 Main PID: 27847 (sleep)
   CGroup: /system.slice/zammad-web.service
           └─27847 /bin/sleep infinity

Jun 12 12:27:04 ...[1]: Started zammad-web.service.
Jun 12 12:27:04 ...[1]: Starting zammad-web.service...

BUT when I check the status of zammad-web-1.service status:
systemctl status zammad-web-1 -l
systemctl status zammad-web-1 -l
● zammad-web-1.service
   Loaded: loaded (/etc/systemd/system/zammad-web-1.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-06-12 12:33:11 UTC; 5s ago
 Main PID: 30964 (ruby)
   CGroup: /system.slice/zammad-web-1.service
           └─30964 /opt/zammad/vendor/ruby-2.3.1/bin/ruby bin/rails s -p 3000

Jun 12 12:33:11 ... systemd[1]: zammad-web-1.service holdoff time over, scheduling restart.
Jun 12 12:33:11 ... systemd[1]: Started zammad-web-1.service.
Jun 12 12:33:11 ... systemd[1]: Starting zammad-web-1.service...
Jun 12 12:33:12 ... zammad-web-1.service[30964]: /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/zammad/bin in PATH, mode 040777
Jun 12 12:33:14 zammad-ansiblever zammad-web-1.service[30964]: /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/zammad/vendor/bundle/ruby/2.3.0/bin in PATH, mode 040777
Jun 12 12:33:16 zammad-ansiblever zammad-web-1.service[30964]: /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/zammad/vendor/bundle/ruby/2.3.0/bin in PATH, mode 040777

**Comment by thorsteneckel** [comment]
Closing due inactivity. As @martini stated earlier: Please contact our support team for commercial services. Thanks!
