### ISSUE TITLE
Overview group by Organisation split multiple times

### ISSUE THREAD

**Issue by jannheider** [zammad/zammad#1093]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: package
* Operating system: CentOS 7
* Browser + version: All

### Expected behavior:

Ticket Overview group by Organisation should group every Organisation only once

### Actual behavior:

Since upgrade from Zammad 1.4 to 1.5 group by Organisation split the Organisation multiple times
This happens in every Overview if you set -> Group by Organisation

In the Screenshot you can see "Organisation A" split 3 times, "Organisation B und C" splits 2 times.

![zammad-org-bug](https://cloud.githubusercontent.com/assets/17439988/26105549/ad16ee4c-3a42-11e7-910a-987bae2e06e2.png)

### Steps to reproduce the behavior:

Don't know how to reproduce this, it just happend after upgrade from version 1.4 to 1.5.
Tried to save serveral times the Overview with different Options, but nothing Helps.

**Comment by martini** [comment]
Hi @jannheider 

good news. This is already fixed in develop for next release (https://github.com/zammad/zammad/issues/1064). :)

We will apply the patch in stable too. I'll send an follow up.

 -Martin

**Comment by jannheider** [comment]
Nice, thanks! I only searched for open tickets, so i didn't find #1064

Think we should leave this open till next release is out, for other ppl :)

**Comment by martini** [comment]
@jannheider now it's also fixed in stable. Please update the package and let me know if it's working fine for you.

Greetings,
 -Martin

**Comment by jannheider** [comment]
@martini thanks, just updatet and it is working.

But, i had to restart Zammad manually 

And there was an error on the Installation, seams to be nothing big, but just in case:

> Downloading packages:
No Presto metadata available for zammad
zammad-1.5.0-1494942109.16bd845.centos7.x86_64.rpm                                                                                                                                           |  70 MB  00:00:10
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : zammad-1.5.0-1494942109.16bd845.centos7.x86_64                                                                                                                                                   1/2
**chown: changing ownership of** **‘/opt/zammad/tmp/cache_file_store_production/%5B%22ticket.agent%22%5D20170516-29282-8eri6d’: No such file or directory**
**warning: %post(zammad-1.5.0-1494942109.16bd845.centos7.x86_64) scriptlet failed, exit status 1**
**Non-fatal POSTIN scriptlet failure in rpm package zammad-1.5.0-1494942109.16bd845.centos7.x86_64**
  Cleanup    : zammad-1.5.0-1494938173.0b6cac5.centos7.x86_64                                                                                                                                                   2/2
  Verifying  : zammad-1.5.0-1494942109.16bd845.centos7.x86_64                                                                                                                                                   1/2
  Verifying  : zammad-1.5.0-1494938173.0b6cac5.centos7.x86_64                                                                                                                                                   2/2

> 
> Updated:
>   zammad.x86_64 0:1.5.0-1494942109.16bd845.centos7

**Comment by martini** [comment]
> And there was an error on the Installation, seams to be nothing big, but just in case:..

One question, did you stop Zammad before updating the package?

It seems that the Zammad scheduler did delete an cache file whiling the package update tried to set the owner of the just removed cache file.

**Comment by jannheider** [comment]
@martini 

No, i did not stop Zammad. I actually never did that :) 
Next time i will try to remember to stop zammad.

**Comment by martini** [comment]
Thanks for feedback. 🤓
