### ISSUE TITLE
ldap-sync skips users

### ISSUE THREAD

**Issue by Jonske** [zammad/zammad#1094]
### Infos:

* Used Zammad version: 1.5 (newest)
* Used Zammad installation source: Official rpm
* Operating system: CentOS 7
* Browser + version: Firefox 53.0.2

### Expected behavior:

* Sync all users from my Active Directory

### Actual behavior:

* Some users get skipped. I don't know if it's a bug or if it's on purpose, but i noticed that users in the Active Directory with the same e-mail address cause this. Only 1 of the users gets synced, the rest doesn't.

### Steps to reproduce the behavior:

* Create 2 users in your Active Directory with the same e-mail address.

As I said, i don't know if this is on purpose or if it's a bug. Maybe the users get synced, but i can't find them on the web-interface?

**Comment by thorsteneckel** [comment]
Hi @Jonske - please see #1069 for a solution.
