### ISSUE TITLE
Delete Users

### ISSUE THREAD

**Issue by IFAK-BER** [zammad/zammad#1096]
Hello,

is there a possibility to delete users? We are using the newest version, updated 16/05/2017

in Ticket #107 @martini commented on 21 Jan 2014

"--> later"

Best regards

**Comment by sthag** [comment]
Have a look at the examples here https://docs.zammad.org/en/latest/admin-console.html
It is not much, but it helped me to get into the commands available. I also have a hard time finding all the commands and their usage. Maybe this is interesting https://github.com/zammad/zammad-documentation/issues/19#issuecomment-297279085

Currently it is only possible to do so via rails console, I think.
For Users it could be `User.find_by(email: 'a@b.c').destroy`

**Comment by IFAK-BER** [comment]
@sthag thank you for you reply but that doesn't seem to work for me.

When I use 

`User.find_by(email: 'max.mustermann@domain.com').destroy`

I get

```
irb(main):001:0> User.find_by(email: 'max.mustermann@domain.com').destroy
NoMethodError: undefined method `destroy' for nil:NilClass
        from (irb):1
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.r            b:110:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.r            b:9:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_            tasks.rb:68:in `console'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_            tasks.rb:39:in `run_command!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in             `<top (required)>'
        from /opt/zammad/bin/rails:4:in `require'
        from /opt/zammad/bin/rails:4:in `<main>'
```

**Comment by IFAK-BER** [comment]
Seems like something is wrong with this command.

When I add the LDAP integration after I deleted the 3 Users (the 3 Users were created manually with the Web-UI) it says "Benutzer: 81 erstellt, 0 aktualisierte, 0 nicht verändert, 225 übersprungen, 3 fehlgeschlagen" and I can't login with the 3 users he should have synched from the LDAP.

**Comment by martini** [comment]
Zammad is using database references. So if you delete references (e. g. users) without re-assigning this references first would will get in trouble.

What we do right now:
1) Working on supporting database forget keys to block deleting reference objects at database level.

2) Implementing a smooth way to delete reference objects with re-assigning references.

Currently you should not delete only the user object. You can delete tickets anytime, here you do not need to take care.

By the way:
```
irb(main):001:0> User.find_by(email: 'max.mustermann@domain.com').destroy
NoMethodError: undefined method `destroy' for nil:NilClass
```
Means there was no user with email 'max.mustermann@domain.com'. So no destroy was possible.

**Comment by martini** [comment]
@IFAK-BER 

> When I add the LDAP integration after I deleted the 3 Users (the 3 Users were created manually with the Web-UI) it says "Benutzer: 81 erstellt, 0 aktualisierte, 0 nicht verändert, 225 übersprungen, 3 fehlgeschlagen" and I can't login with the 3 users he should have synched from the LDAP.

This is IMO a different issue (not Delete Users). A new issue would be good for that.

**Comment by IFAK-BER** [comment]
thanks for your reply.

maybe it's the easiest way to remember my config, go far back to a snapshot where I only have 1 user that doesn't have any connection to the LDAP and wait until an update gets released to delete users everywhere.

But then I still ask myself why the Web-UI only shows 40 out of 81 users and I don't see a button to go to page 2 for example.

> By the way: [...] Means there was no user with email 'max.mustermann@domain.com'. So no destroy was possible.

you're right, there was a typo.

**Comment by martini** [comment]
> I still ask myself why the Web-UI only shows 40 out of 81 users and I don't see a button to go to page 2 for example, but that's not a big problem.

It's a search result. Per default it shows latest created users (40 users in list). You can search by using the input box above. 

Thanks for the idea of pagination. That sounds good.

**Comment by IFAK-BER** [comment]
Thanks again. You helped me a lot.

Now I know that if you put * in the search bar you see every user.


I build everything from scratch again and now I don't have any duplicate user. I'll wait for future updates until a delete function has been implemented before deleting any user by myself again.

**Comment by martini** [comment]
@IFAK-BER Thanks for feedback!

**Comment by przemkiemzwany** [comment]
Hi,
when i try delete user i have a error:

_irb(main):012:0> User.find_by(login: 'auto-1544538958-738075').destroy
Group.find(2) notify TOUCH 2018-12-12 07:27:15 UTC
User.find(327) notify TOUCH 2018-12-12 07:27:15 UTC
# curl -X DELETE "http://127.0.0.1:9200/redmine_zammad_production/StatsStore/7"
# 404
Unable to process DELETE request to elasticsearch URL 'http://127.0.0.1:9200/redmine_zammad_production/StatsStore/7'. Check the response and payload for detailed information:

Response:
#<UserAgent::Result:0x0000561af9724538 @success=false, @body=nil, @data=nil, @code="404", @content_type=nil, @error="No such file http://127.0.0.1:9200/redmine_zammad_production/StatsStore/7, 404!">

Payload:
nil

Payload size: 0M
NOTICE: can't delete index: Unable to process DELETE request to elasticsearch URL 'http://127.0.0.1:9200/redmine_zammad_production/StatsStore/7'. Check the response and payload for detailed information:

Response:
#<UserAgent::Result:0x0000561af9724538 @success=false, @body=nil, @data=nil, @code="404", @content_type=nil, @error="No such file http://127.0.0.1:9200/redmine_zammad_production/StatsStore/7, 404!">

Payload:
nil

Payload size: 0M
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_5e0981116b" on table "activity_streams"
DETAIL:  Key (id)=(327) is still referenced from table "activity_streams".
: DELETE FROM "users" WHERE "users"."id" = $1_

**Comment by thorsteneckel** [comment]
Hi @przemkiemzwany - please refer to the [community board](http://community.zammad.org/) for technical questions and don't answer (long) closed and resolved issues - thanks!
