### ISSUE TITLE
Delete Groups, Users and Organisations

### ISSUE THREAD

**Issue by Linus2017** [zammad/zammad#1098]
Hello,

how can I delete Groups, Users and Organisations?

**Comment by sthag** [comment]
Maybe my answer [here](https://github.com/zammad/zammad/issues/1096#issuecomment-302324458)  is of any help.

**Comment by Linus2017** [comment]
Thank you for your reply.
How can organizations and groups be deleted?

`Organizations.find_by(name: 'Test').destroy` ???
`Groups.find_by(name: 'Test').destroy` ???

**Comment by martini** [comment]
Hi @Linus2017 

Zammad is using database references. So if you delete references (e. g. users) without re-assigning this references first would will get in trouble.

What we do right now:

Working on supporting database forget keys to block deleting reference objects at database level.

Implementing a smooth way to delete reference objects with re-assigning references.

Currently you should not delete users, groups or organization in database until you also change the id-references in other tables. You can set users, groups and organization to "active = false". Then it's not used anymore.

 **You can delete tickets anytime, here you do not need to take care.**

 -Martin
