### ISSUE TITLE
Quote the message from the customer and ticket history in the outgoing mail

### ISSUE THREAD

**Issue by Linus2017** [zammad/zammad#1099]
Hello, 

how can the previous conversation be quoted by the customer? 
Can the complete ticket history be added to the outgoing mail?

**Comment by monotek** [comment]
How should that work? 
It totally depends on the mailclient of the customer.

**Comment by babakkazemi** [comment]
@monotek I think he means how to do it in zammad web interface. @Linus2017 just highlight the part you want to quote, then click reply.

**Comment by martini** [comment]
It's currently only supported to quote related parts of customers message, see https://github.com/zammad/zammad/issues/571#issuecomment-269484660

Duplicate of https://github.com/zammad/zammad/issues/571
