### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#1101]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: Package
* Operating system: CentOS7
* Browser + version: 

### Expected behavior:
How could i force Zammad to load for example Italian Lang as default language?

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by conankid2512** [comment]
Hello, I have the same problem, I created a helpdesk system with 100% customer is Vietnamese, 99,99% of browser in VietNam is accept en-US language by default so our login screen is always English.

Can you please tell me anyway to force single-language system cause all of my customer is Vietnamese.

**Comment by georgeemr** [comment]
Need help with this. I need to force Zammad to use a specific language.

**Comment by MrGeneration** [comment]
No offense, but please post technical questions on our community: https://community.zammad.org .

This helps us to keep issues clean for faster processing when a developer takes a look into it.
This is an enhancement issue, thus it's currently not possible as far as I can tell.

I'm limitting the conversation to contributors only now.
Again, please don't get me wrong. :-)

**Comment by Mirtaaa** [comment]
Hello,
this works as designed and the need from user side is currently too small. Therefore we will close this issue for now. If this becomes more relevant in the future, we will of course reopen this topic.
