### ISSUE TITLE
Agent reply by email does not notify customer by email

### ISSUE THREAD

**Issue by molsonrocks** [zammad/zammad#1102]
### Infos:

More of a question than a bug.

* Used Zammad version:  1.5.x
* Used Zammad installation source: deb from packager.io
* Operating system: Ubuntu 16.04
* Browser + version: Chrome/Firefox/IE

Expected behavior: My thought was that a reply by an agent in email to a ticket would post the response to the ticket in the web interface and send an update notification to the customer by email.

* 

Actual behavior: I am fairly certain I am missing something here (setting, checkbox, something)... Customer sends the initial email to the helpdesk email address. This generates the ticket and sends notifications to customer and agent. The agent replies with an update to the first notification email they receive, which then generates an update to the ticket in the web interface but the customer never receives an update notification. From what I see it looks to be an internal note in the web interface when the agent responds by email to the first new ticket notification. If I reply within the web interface as the agent to a customer it sends the updated email to the customer. What am I missing to have an entire line of support between customer and agent over email alone?

Sorry if this is posted somewhere already. I have searched but only came across question's related to ticket history in the email chain.

**Comment by babakkazemi** [comment]
As admin, define a trigger for this (send email notification to customer on ticket update, see settings - triggers). That is the easiest way for having notifications sent out to customers
