### ISSUE TITLE
`time_unit` attribute is not propagated over ticket articles API

### ISSUE THREAD

**Issue by isfugithub** [zammad/zammad#1103]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: Source
* Operating system: CENTOS 7
* Browser + version: Firefox 53.0.2

### Expected behavior:

"time_unit": "12.0" propagated via API

### Actual behavior:

curl -u User:Pwd https://my.zammadhost.com/api/v1/ticket_articles/{7}?expand=true
{
"id":7,
"ticket_id":2,
"type_id":5,
"sender_id":1,
"from":"Mr Admin",
"to":"",
"cc":"",
"subject":null,
"message_id":null,
"message_id_md5":null,
"in_reply_to":"",
"content_type":"text/html",
"references":null,
"body":"Thx for your call\u003cbr\u003e",
"internal":false,
"preferences":{},
"updated_by_id":3,
"created_by_id":3,
"created_at":"2017-05-15T17:58:37.000Z",
"updated_at":"2017-05-15T17:58:37.670Z",
"attachments":[],
"type":"phone",
"sender":"Agent",
"created_by":"info@zammadhost.com",
"updated_by":"info@zammadhost.com"
} 

### Steps to reproduce the behavior:

curl -u User:Pwd https://my.zammadhost.com/api/v1/ticket_articles/{7}?expand=true

```[tasklist]
### Tasks
- [x] Add `time_unit` attribute in the API
- [x] Add appropriate tests
- [x] Documentation changes
- [x] Review
```

**Comment by martini** [comment]
@isfugithub thanks for feedback. It's currently not included, because it's a own model. Anyway, it would make sense.

**Comment by nkfilis** [comment]
I ran into this as well, the docs say it should be there: https://docs.zammad.org/en/latest/api-ticket-article.html?highlight=time_unit

**Comment by tisto** [comment]
@martini any news here? As far as I can see right now it is impossible to retrieve time entries from Zammad in any way (API call or ES).

**Comment by Newan** [comment]
same question  here: https://community.zammad.org/t/rest-api-call-for-time-accounting/703

**Comment by OneiricIT** [comment]
Would love to see this too!

**Comment by svenlimbach** [comment]
Is there any change to the API Logic yet? @martini Anything we can contribute? Many thx for this great project!

**Comment by MrGeneration** [comment]
We will update the issue accordingly if anything moves. As of now this issue is still open.

**Comment by rolfschmidt** [comment]
This actually might be duplicate, because it should be solved with https://github.com/zammad/zammad/issues/4533.
