### ISSUE TITLE
Information for customer when an input in a ticket ist changed to public

### ISSUE THREAD

**Issue by martinbenz** [zammad/zammad#1105]
Using current Version

Agent makes an input in a ticket. This information is important for the certain customer. The changes the input into "public". We found no information in the user Interface about the Change in ticket.

We are expecting some Information for the customer, that a new Information for him is available.
How to solve this issue.

**Comment by babakkazemi** [comment]
@martinbenz Set a trigger (settings->triggers) whicj sends a notification to customer via email on ticket update

**Comment by martinbenz** [comment]
This is not the solution I expect. If I set a trigger with “Aktion(action)” is “geändert(changed)”  every change on the ticket is send to the customer. I just want to inform the customer if the changes are important for him. E.g. by  changing the input to public. Only these changes are important for the customer not the changes which are defined internal.     Enclosed you find the definition.

Regards
Martin

Von: Babak Kazemi [mailto:notifications@github.com]
Gesendet: Mittwoch, 17. Mai 2017 15:21
An: zammad/zammad <zammad@noreply.github.com>
Cc: Benz, Martin <Martin.Benz@tia.com>; Mention <mention@noreply.github.com>
Betreff: Re: [zammad/zammad] Information for customer when an input in a ticket ist changed to public (#1105)


@martinbenz<https://github.com/martinbenz> Set a trigger (settings->triggers) whicj sends a notification to customer via email on ticket update

**Comment by babakkazemi** [comment]
@martinbenz you can also define "Sichtbarkeit" ist "öffentlich" as additional parameter in the trigger, maybe this helps?

**Comment by martinbenz** [comment]
Hi Mr. Kazemi,

that was the solution. Perfect.
Many thanks

Martin Benz

Von: Babak Kazemi [mailto:notifications@github.com]
Gesendet: Mittwoch, 17. Mai 2017 15:43
An: zammad/zammad <zammad@noreply.github.com>
Cc: Benz, Martin <Martin.Benz@tia.com>; Mention <mention@noreply.github.com>
Betreff: Re: [zammad/zammad] Information for customer when an input in a ticket ist changed to public (#1105)


@martinbenz<https://github.com/martinbenz> you can also define "Sichtbarkeit" ist "öffentlich" as additional parameter in the trigger, maybe this helps?

**Comment by martinbenz** [comment]
Hi Mr. Kazemi,

my yesterday response was too fast. The customer receives an information via mail if the ticket was changed and set to public. If the customer makes an action in the customer portal/interface and save his changes, he will receive a mail based on his own change. This behaviour is not useful. Is there any kind of setting in the trigger in this way that a customer will not be informed about own changes.

Kind regards

Martin Benz

Von: Babak Kazemi [mailto:notifications@github.com]
Gesendet: Mittwoch, 17. Mai 2017 15:43
An: zammad/zammad <zammad@noreply.github.com>
Cc: Benz, Martin <Martin.Benz@tia.com>; Mention <mention@noreply.github.com>
Betreff: Re: [zammad/zammad] Information for customer when an input in a ticket ist changed to public (#1105)


@martinbenz<https://github.com/martinbenz> you can also define "Sichtbarkeit" ist "öffentlich" as additional parameter in the trigger, maybe this helps?

**Comment by babakkazemi** [comment]
@martinbenz try additional parameter "sender" ist nicht "customer"

**Comment by martinbenz** [comment]
Dear Mr. Kazemi,

that’s it. Thanks for the hint. Defining these triggers is tricky with a lot of possibilities.

Kind regards

Martin Benz

Von: Babak Kazemi [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. Mai 2017 13:55
An: zammad/zammad <zammad@noreply.github.com>
Cc: Benz, Martin <Martin.Benz@tia.com>; Mention <mention@noreply.github.com>
Betreff: Re: [zammad/zammad] Information for customer when an input in a ticket ist changed to public (#1105)


@martinbenz<https://github.com/martinbenz> try additional parameter "sender" ist nicht "customer"

**Comment by rolfschmidt** [comment]
Thanks for your support @babakkazemi.
