### ISSUE TITLE
Unable to use external reverse proxy with development branch

### ISSUE THREAD

**Issue by martini** [zammad/zammad#1108]
Unable to use external reverse proxy with development branch. App server and web socket server only bind to 127.0.0.1. It's related to https://github.com/zammad/zammad/commit/943a9e6ac2139fa66261f2be5575601e55f9c272

Tried to set ZAMMAD_BIND_IP via /etc/bashrc and directly in Procfile without success.

Workaround in /opt/zammad/vendor/pkgr/processes/websocket and /opt/zammad/vendor/pkgr/processes/web works.

But what is the correct way to set ZAMMAD_BIND_IP update save?

**Comment by monotek** [comment]
Imho there is no way to do it locally as the variables only work in the build process of the package.

If you like to use external load balance just point to port 80 or use the source install to configure ports and ips as you want.

**Comment by monotek** [comment]
I was wrong. You can change the IP and Port of the packages as described here: https://docs.zammad.org/en/latest/appendix-configure-env-vars.html
