### ISSUE TITLE
Add support for reply templates (aka canned responses or common replies)

### ISSUE THREAD

**Issue by samtuke** [zammad/zammad#1110]
It appears that Zammad does not support reply templates with common responses that can be inserted into a ticket with a few clicks. Please add support for this crucial productivity feature.

**Comment by hanneshal** [comment]
Hi,

in fact there are templates. You can add them in the admin area and use them typing "::" and your templates will appear. 

regards

Johannes
![screen](https://cloud.githubusercontent.com/assets/804939/26189703/3bef5e2e-3ba6-11e7-9459-19f6022bb2a7.jpg)
