### ISSUE TITLE
selecting language

### ISSUE THREAD

**Issue by nilsrb** [zammad/zammad#1111]
### Infos:

* Used Zammad version: zammad-1.5.0-1494974115.48b4945.centos7.x86_64 then updated to zammad-1.5.0-1495017264.48b4945.centos7.x86_64
* Used Zammad installation source: RPM
* Operating system: CentOS Linux release 7.3.1611
* Browser + version: Chrome, current version

### Expected behavior:

Installing Zammad and being able to choose to between different languages. 

### Actual behavior:

We installed Zammad a few weeks ago on a testing server and updated to 1.5 without any problems. Now that we want to use Zammad in production, i installed this morning version zammad-1.5.0-1494974115.48b4945.centos7.x86_64. With this version, the installation steps were in english and afterwards i could not change the language setting, it only showed "English (United States)". In the meantime there is the new version: zammad-1.5.0-1495017264.48b4945.centos7.x86_64. When i freshly install this version, everything works fine. But we already installed the older version and with an RPM-Update the problem still exists. Unfortunately we already entered quite a few things so that we don't want to start with a fresh installation. 

### Steps to reproduce the behavior:

* Installing version zammad-1.5.0-1494974115.48b4945.centos7.x86_64 and upgrading to zammad-1.5.0-1495017264.48b4945.centos7.x86_64

**Comment by martini** [comment]
Hi @nilsrb 

Can you send me the output of:

`zammad run rails r 'p Locale.count'`

`zammad run rails r 'p Locale.all'`

Is it working if you execute updating locales & translations manually?

`rails r 'Locale.load'`
`rails r 'Translation.load'`

Thanks for feedback,
 -Martin

**Comment by nilsrb** [comment]
Thanks, doing it manually worked.
Here the output:
`[root@helpdesk ~]# zammad run rails r 'p Locale.count'
1
[root@helpdesk ~]# zammad run rails r 'p Locale.all'
#<ActiveRecord::Relation [#<Locale id: 1, locale: "en-us", alias: "en", name: "English (United States)", active: true, created_at: "2017-05-17 05:10:22", updated_at: "2017-05-17 05:10:22">]>
[root@helpdesk ~]# 
[root@helpdesk ~]# zammad run rails r 'Locale.load'
[root@helpdesk ~]# zammad run rails r 'Translation.load'
[root@helpdesk ~]# 
[root@helpdesk ~]# zammad run rails r 'p Locale.count'
37
[root@helpdesk ~]# zammad run rails r 'p Locale.all'
#<ActiveRecord::Relation [#<Locale id: 1, locale: "en-us", alias: "en", name: "English (United States)", active: true, created_at: "2017-05-17 05:10:22", updated_at: "2017-05-17 05:10:22">, #<Locale id: 38, locale: "bg", alias: "", name: "Bulgarian (Български)", active: true, created_at: "2017-05-18 06:05:04", updated_at: "2017-05-18 06:05:04">, #<Locale id: 39, locale: "cs", alias: "", name: "Czech (Česky)", active: true, created_at: "2017-05-18 06:05:04", updated_at: "2017-05-18 06:05:04">, #<Locale id: 40, locale: "da", alias: "", name: "Dansk", active: true, created_at: "2017-05-18 06:05:04", updated_at: "2017-05-18 06:05:04">, #<Locale id: 41, locale: "el", alias: "", name: "Greek (Ελληνικά)", active: true, created_at: "2017-05-18 06:05:04", updated_at: "2017-05-18 06:05:04">, #<Locale id: 42, locale: "et", alias: "", name: "Eesti", active: true, created_at: "2017-05-18 06:05:04", updated_at: "2017-05-18 06:05:04">, #<Locale id: 43, locale: "en-ca", alias: "", name: "English (Canada)", active: true, created_at: "2017-05-18 06:05:04", updated_at: "2017-05-18 06:05:04">, #<Locale id: 44, locale: "en-gb", alias: "", name: "English (Great Britain)", active: true, created_at: "2017-05-18 06:05:04", updated_at: "2017-05-18 06:05:04">, #<Locale id: 45, locale: "es-es", alias: "es", name: "Español", active: true, created_at: "2017-05-18 06:05:04", updated_at: "2017-05-18 06:05:04">, #<Locale id: 46, locale: "es-co", alias: "", name: "Español (Colombia)", active: true, created_at: "2017-05-18 06:05:04", updated_at: "2017-05-18 06:05:04">, ...]>
`

**Comment by martini** [comment]
> Thanks, doing it manually worked.

So it seems at first installation/update there was no internet connection. 

Anyway, thanks for feedback!

**Comment by nilsrb** [comment]
Thanks for the quick support!
