### ISSUE TITLE
Default notification settings

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1113]
Hello together,

is there a way to change the default notification setting which each user gets?
For example, per default the settings look like this:
![screenshot_1](https://cloud.githubusercontent.com/assets/4436931/26190041/c504108c-3ba7-11e7-8e2c-24652a29a0dc.jpg)
And I would like to change them, that they look like this for every new user:
![screenshot_2](https://cloud.githubusercontent.com/assets/4436931/26190057/d7171b48-3ba7-11e7-943e-2727644cdadc.jpg)

**Comment by martini** [comment]
Hi @MamoulianDelacroix 

you can define the default settings config file https://github.com/zammad/zammad/blob/develop/config/application.rb#L54

 -Martin

**Comment by MamoulianDelacroix** [comment]
Great, thanks a lot!

**Comment by infestdead** [comment]
Hello, 
is this still the case? Maybe the setting moved to another file, or it's now in the web interface? Sorry for necroposting.. :)

**Comment by thorsteneckel** [comment]
Here you go: https://github.com/zammad/zammad/blob/66e8d58f298603f9bb1a4be762ff92abdf37779b/config/application.rb#L60-L111

**Comment by infestdead** [comment]
@thorsteneckel thanks, but aren't those for ticket agent? My goal is to subscribe new users (customers) by default to email updates on all ticket updates/changes etc.

**Comment by thorsteneckel** [comment]
Yes. This is currently only possible for agents - see #1959. You can start a discussion over at the [community board](http://community.zammad.org/) if you disagree.

**Comment by zifeo** [comment]
@thorsteneckel Is there a way of overwrite easily the configuration using docker-compose?

**Comment by MrGeneration** [comment]
Please don't recycle closed issues.
Also, this is the wrong repository.

You can either consult our community (https://community.zammad.org) or consult the docker repo: https://github.com/zammad/zammad-docker-compose
