### ISSUE TITLE
Configuration of LDAP with disabled anonymous bind fails

### ISSUE THREAD

**Issue by nilsrb** [zammad/zammad#1114]
### Infos:

* Used Zammad version: zammad-1.5.0-1494013569.412fbc4.centos7.x86_64
* Used Zammad installation source: rpm
* Operating system:  CentOS Linux release 7.3.1611 (Core) 
* Browser + version: Chrome (current version)

### Expected behavior:

Enabling LDAP and being able to use with anonymous binding turned off. 

### Actual behavior:

Can't connect to 'ldapservername' on port '636', Can't bind to 'ldapservername', 48, Inappropriate Authentication

On our ldap-servers we turned off anonymous bind and now i am looking for a way to connect to our servers. I can't get to the next page because the initial bind failed with the error above. 
On the ldap-server-log i can see the request failing with error:  "text=anonymous bind disallowed"

**Comment by thorsteneckel** [comment]
Could you please provide your LDAP software name, vendor and version so we can try to reproduce it? I'll check how to work around this.

For users without anonymous bind it will be probably necessary to fill the BaseDN by hand since Zammad won't be able (in the current workflow) to detect it automatically.

**Comment by thorsteneckel** [comment]
HI @nilsrb - I fixed the described behavior with the commit(s) above. As written before you then have to add your BaseDN manually since Zammad can't probe it without anonymous bind enabled. Feedback would be great!

**Comment by ruebenmaster** [comment]
Hallo thorsteneckel,
till 8 a.m. i'm fighting with the zammad ldap connection. First i have to learn to connect with email address an not with destinguished name. But all i try, i can't connect to the ldap server. The other servers like seafile or freeradius have no problem to connect with the same credentials to the same server.
Logfile:

[2017-10-26T11:49:39.749468 #715] ERROR -- : Can't connect to '10.250.4.55' on port '389', Can't bind to '10.250.4.55', 32, No Such Object (Exceptions::UnprocessableEntity)


He can't connect, but why? The other server are in the same network and have no problems with the connection to the LDAP server. 

A chance to see more logfile infos? Infos that help to clear situation?

Greetings
ruebenmaster

zammad (newest version, update yesterday)
LDAP 389 (Kolab Installation)
Both on CentOS 7

**Comment by ruebenmaster** [comment]
by the way...

[root@deluh01-lsv051 zammad]# telnet 10.250.4.55 389
Trying 10.250.4.55...
Connected to 10.250.4.55.
Escape character is '^]'.

**Comment by thorsteneckel** [comment]
Hi @ruebenmaster. Please always create a new issue for closed issues. I think your case has no relation to this issue. Could you please follow these steps and create a new issue with your description and the result of the script. Thanks!

1.) Create a file called `debug_ldap.rb` in your Zammad directory (usually `/opt/zammad`) and change the required user credentials to your own.
2.) Run the file from your Zammad directory via `zammad run rails r debug_ldap.rb` or `rails r debug_ldap.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `debug_ldap.rb` file

```ruby
require 'net/ldap'
require 'net/ldap/entry'

bind_user = 'your.dn'
bind_pw   = 'your PW'

ldap = Net::LDAP.new(
  host: '10.250.4.55',
  port: '389',
)

ldap.auth(bind_user, bind_pw)

p ldap.get_operation_result
```
