### ISSUE TITLE
Attach customer id when adding article/note via api

### ISSUE THREAD

**Issue by anandsork** [zammad/zammad#1115]
I observed that if I create the article via api, the sender_id is shown as the agent. In the UI, one can see the agent icon to the right of the note.. (attached the image)

![articlecreatedusingapi](https://cloud.githubusercontent.com/assets/5656919/26195172/868910c4-3bd8-11e7-8f93-5669e1980727.jpg)

This was created using Ticket Create API with article in it. I even tried separate api for ticket_article creation.

I tried by passing various parameters while creating article, but it always shows the note as agent.. (Although it shows on the right hand side when I use Sender as Customer)
Various tries I did (Some were just for the sake if something hits bull's eye :) ) by passing values to the json
 
_"from": "Bob6 Smith6",_
 _"updated_by_id": 20,_ **// Customer Id**
_"created_by_id": 20,_
 _"to": "recipient@customer.com",_ 
  _"sender": "Customer",_
  _"sender_id": 20,_ **// Providing this, This always gives 422 error..**
  _"created_by": "bob8@mple.com",_ 
  _"updated_by": "bob8@mple.com"_

Can somebody help me in how to have the customer name in front of the article/note?

I looked at the code too, but there (_zammad/app/controllers/concerns/creates_ticket_articles.rb??_) . It seems ok.. If I pass sender_id, it should take it.. However I always get the 422 error in that case (I have ticket.agent permission.. In fact, I checked on all the checkboxes while generating token, just for testing)

I am using fiddler to test instead of any sdk.. (if it matters to anyone)

**Comment by rolfschmidt** [comment]
Hi @anandsork,
please try to use the parameter **origin_by_id** to set the customer id for your article. This should work. We added this parameter some weeks ago to e.g. create phone tickets for your customer.

https://docs.zammad.org/en/latest/api-ticket-article.html#create

```
{
   "ticket_id": 3,
   "origin_by_id": 5,
   "to": "",
   "cc": "",
   "subject": "some subject",
   "body": "<b>some</b> message witn inline image <img src=\"data:image/jpeg;base64,ABCDEFG==\">"
   "content_type": "text/html",
   "sender": "Customer",
   "type": "phone",
   "internal": false,
   "time_unit": "12"
}
```

Please regard that it needs to be a **customer phone ticket**.

In case of further questions do not hesitate to reopen the issue.

-Rolf

**Comment by anandsork** [comment]
Ok.. I was trying with the ticket created via API. Why is this allowed only for phone ticket? If I have external system to create ticket, I have to use the APIs only. In that case, it would be good to show that the article is added by customer. 
Can you please provide some pointers on how I could achieve it by changing the code?

**Comment by cardoso** [comment]
Almost 3 years late, but:

If you put on the headers: 'X-On-Behalf-Of': user id/ login/ or email

It shows that user as the creator of the first article :)

No need for origin_by_id
