### ISSUE TITLE
Time Accounting stopwatch instead of time units

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1116]
Hihi ^^

it would be awesome, if there were the possibility to switch the time accounting from manually entering time units to an actuall stopwatch, which you hit on start, when you are starting to work on the ticket. For example like in Kimai

**Comment by GregMighty** [comment]
This also works in ZOHO PRojects. Great functionality.

**Comment by martini** [comment]
Thanks for feedback. If you have some screenshots to get ideas, it would be fine.

**Comment by MamoulianDelacroix** [comment]
Screenshots like that? ^^ (These screenshots were stuporous put together :satisfied: out of screenshot from zammad and kimai. But I think you can get the idea)
variant 1:
![1](https://cloud.githubusercontent.com/assets/4436931/26355031/722fb770-3fc7-11e7-88c6-0c2ae15ee20c.png)
![2](https://cloud.githubusercontent.com/assets/4436931/26355039/75395b4c-3fc7-11e7-92b7-1985336fca5b.png)
variant 2:
![2_1](https://cloud.githubusercontent.com/assets/4436931/26355180/00c2c52c-3fc8-11e7-8648-fec83a99a0a9.jpg)
![2_2](https://cloud.githubusercontent.com/assets/4436931/26355188/0315b154-3fc8-11e7-8162-612ffaf748a8.jpg)

**Comment by jonasboettcher** [comment]
I would like to vote for this!
+1

**Comment by kisahm** [comment]
+1

**Comment by redbear-ger** [comment]
How much for speeding that up? I mean... it's nearly 4(!) years....

**Comment by MrGeneration** [comment]
Please drop a message to sales [at] zammad [dot] com with referencing this issue in case you want to sponsor this functionality. 
The colleagues will then check the inquiry and provide further input. :-)

**Comment by KoJie** [comment]
Currently, we are considering not implementing such a feature, as we are receiving very little feedback on it. Therefore I close the issue for now. 
But thank you anyways for the feedback!
