### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Jonske** [zammad/zammad#1117]
### Infos:

* Used Zammad version: 1.5 (newest)
* Used Zammad installation source: rpm
* Operating system: CentOS 7
* Browser + version: Firefox

Hey,

today i tried to install elasticsearch on my CentOS 7 Server. i follwed the instructions from [](https://docs.zammad.org/en/latest/install-elasticsearch.html) , but I could not get it to work.
Anyway, after that i uninstalled elasticsearch and since then i get the error "502 Bad Gateway". 
I really don't know what causes this, but this must have something to do with elasticsearch.

**Comment by jannheider** [comment]
Is zammad running? Try to restart zammad.

**Comment by visdim** [comment]
this has helped me when elasticsearch was not running:
cd /usr/share/elasticsearch
bin/elasticsearch-plugin remove mapper-attachments
bin/elasticsearch-plugin install mapper-attachments

systemctl start elasticsearch
systemctl enable elasticsearch
systemctl status elasticsearch

**Comment by MamoulianDelacroix** [comment]
What does the logs of your web-server say?

**Comment by Jonske** [comment]
The problem is solved. I uninstalled elasticsearch and restarted the server. After that i uninstalled zammad and installed it again. I don't excatly know why, but the error message is gone.
