### ISSUE TITLE
Feature request: Time series diagram about ticket states

### ISSUE THREAD

**Issue by MartinBorg** [zammad/zammad#1119]
### Infos:

* Used Zammad version: 1.5 stable
* Used Zammad installation source: deb
* Operating system: Debian 8
* Browser + version: Firefox on Debian 8

### Expected behavior:

* It would be helpful to have a graphical view about open and closed tickets over time to see trends. Does number of open tickets go up in the vacation period, because some agents are away? Or down, because customers are away? What is the effect of a new product or a new team member on ticket states? Etc.

### Actual behavior:

* I did not find such a feature.

**Comment by martini** [comment]
Something like this?

![report](https://cloud.githubusercontent.com/assets/110226/26225398/4ac9aef0-3c27-11e7-82d4-632452cb4216.png)

**Comment by MartinBorg** [comment]
Yes, exactly!

**Comment by MartinBorg** [comment]
How would I get to this wonderful view?

**Comment by martini** [comment]
It's currently only in git. Will be included in one of the next releases. @mrflix
