### ISSUE TITLE
LDAP: OU wird nicht gefunden // eine Gruppe -> mehrere Rollen

### ISSUE THREAD

**Issue by ArcheNoah77** [zammad/zammad#1120]
Hallo,
ich versuche mich gerade an der LDAP Integration:

### Infos:

* Used Zammad version: 1.6
* Used Zammad installation source: DEB
* Operating system: Debian 8
* Browser + version: Firefox

### Expected behavior:
Eine Gruppe in der AD soll Admin und Agent sein, eine OU soll Customer sein.

### Actual behavior:
Die Gruppe "Administrator(low level) bekommt entweder Admin oder Agent Rechte, aber nicht beides.
Die OU "User" wird von Zammad gar nicht erst gefunden, ich hab sie manuell eingetragen.

### Steps to reproduce the behavior:
So hab ich es eingestellt:
![2](https://cloud.githubusercontent.com/assets/25475591/26248618/5e59a0b6-3ca3-11e7-9605-1216d50f07b3.png)

So sieht es aus, wenn ich auf "Weiter" und "Save Configuration" klicke:
![3](https://cloud.githubusercontent.com/assets/25475591/26248632/7020281a-3ca3-11e7-9370-85885120fe04.png)

**Comment by MamoulianDelacroix** [comment]
Hi,

selbiges "Problem" habe ich auch (#1097). "Gelöst" habe ich es dahingegend, dass ich eine zusäztliche Gruppe im AD/LADP eingerichtet habe. Damit ich dann Admin => Admin und Agent => Agent zuordnen kann.

**Comment by ArcheNoah77** [comment]
Darauf bin ich mittlerweile auch gekommen :D

Das andere Problem besteht leider immernoch. Anscheinend kann das System keine ganzen OU's per LDAP syncen, sondern nur Gruppen.

**Comment by thorsteneckel** [comment]
Hi there! I have to close this issue because it

... has multiple topics in one
... is a duplicate of #1097 
... is written in german. English is our preferred community language, no matter how "bad" the english is. Thanks for keeping it accessible to all.

Please reopen a new issue for the OU sync part in english. Thanks!
