### ISSUE TITLE
Allow notification emails to be internal

### ISSUE THREAD

**Issue by LukasReschke** [zammad/zammad#1121]
We've specified the following Trigger to remind agents when a SLA violation is nearby:

<img width="722" alt="screen shot 2017-05-19 at 15 34 27" src="https://cloud.githubusercontent.com/assets/878997/26249968/bdc83a80-3ca8-11e7-9e85-943a297bccf5.png">

This works quite fine, however, in the ticket it leaves an activity element visible also for the customer. In this case it would be preferred if the customer wouldn't see this, especially as the email addresses of all agents are disclosed and this doesn't seem like the usual behaviour.

Or is there a better way to inform people of tickets nearing escalation period? :)

**Comment by moellert** [comment]
Hey, since some time has passed I want to ask if this enhancement has found its way on your roadmap and gets implemented?

**Comment by martini** [comment]
Dear @moellert 

first of all, many thanks for your participation on the Zammad open source project. 

Not usual as with proprietary software, we finance Zammad through service. So it's less money we have at our disposal to push Zammad.

If you would like to support Zammad, you can do so via Zammad Support: https://zammad.com/pricing#selfhosted

For all issues it is generally important that we tag an issue as soon as it is included in a release. This means that manual enquiry only minimizes the available resources but not the speed of implementation.

Thank you for your understanding.

**Comment by thorsteneckel** [comment]
Hey @LukasReschke - we faced this in a different situation and created another issue - #2782. The good news is that this was fixed in the meantime and will be part of Zammad 3.3 which will be released this week. However, since we referenced #2782 in the commit I will mark this as a duplicate - for maintenance reasons. Closing now.
