### ISSUE TITLE
Attachments get doubled when suspending a draft

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#1123]
### Infos:

* Used Zammad version: 1.5
* Operating system: hosted at zammad.com
* Browser + version: Vivaldi 1.9

### Expected behavior:

* Attachments being kept
* Attachments being shown when resuming the draft

### Actual behavior:

* Attachments being hidden which looks like they wre dropped
* The recipient gets all attachments twice

### Steps to reproduce the behavior:

* Create a new ticket, fill in recipient, subject, text
* Upload 4 files
* Wait till all attachments are uploaded
* Reload the page and/or (close the browser and open it again)
* The recipient, subject, text etc. is all still there
* You see no attachments, so it looks like they were dropped
* You upload the same attachments again
* You see 4 uploaded files
* You submit the ticket as usual
* Re-login and/or reload the page
* You see all attachments doubled

Afterwards the ticket looks like this:
![image](https://cloud.githubusercontent.com/assets/26226303/26278902/a44c7af0-3da5-11e7-8bee-3dff53bf89ea.png)

* The attachment REALLY were sent twice... 4\*1.4\*1.33=7.44 MB
* But as you can see 8\*1.44\*1.33=14.89 MB were sent!
* The amount of sent data matches... 16198362 / 1024 / 1024 = 15.44 MB

```
Mai 20 13:26:27 cyan postfix/submission/smtpd[9091]: connect from apn4728.dc.zammad.com[213.202.233.132]
Mai 20 13:26:28 cyan postfix/submission/smtpd[9091]: Anonymous TLS connection established from apn4728.dc.zammad.com[213.202.233.132]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Mai 20 13:26:28 cyan postfix/submission/smtpd[9091]: 4076D298D1: client=apn4728.dc.zammad.com[213.202.233.132], sasl_method=PLAIN, sasl_username=xxx
Mai 20 13:26:34 cyan postfix/cleanup[9093]: 4076D298D1: message-id=<xxx@xxx.zammad.com>
Mai 20 13:26:46 cyan postfix/qmgr[944]: 4076D298D1: from=<xxx@xxx>, size=16198362, nrcpt=1 (queue active) <----- there!!!
Mai 20 13:26:46 cyan postfix/submission/smtpd[9091]: disconnect from apn4728.dc.zammad.com[213.202.233.132] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Mai 20 13:27:00 cyan postfix/smtp[9096]: 4076D298D1: to=<xxx>, relay=xxx[xxx]:25, delay=32, delays=18/0.01/0.83/13, dsn=2.0.0, status=sent (250 ok:  Message 2559231 accepted)
```

**Comment by rkaldung** [comment]
With the latest version (development) the attachments were lost when resuming the draft after a browser reload.
