### ISSUE TITLE
Enhancement: Make New-Button more usable

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#1124]
### Infos:

* Used Zammad version: 1.5

### Expected behavior:

* The New-Button offers three options: New ingoing call, New outgoing call, New mail. Clicking it opens a new ticket with the desired type preselected
---or---
* The New-Button has no options; clicking it opens a new ticket directly
---or---
* Both ways combined by turning the + button into a split button
  * The button itself opens a new ticket directly
  * The minor part opens the context menu with the three options

### Actual behavior:

* Clicking once.. to open the conext menu that contains 1 option only
* Clicking the the option secondly to create a new ticket

![image](https://cloud.githubusercontent.com/assets/26226303/26278944/30ae18b8-3da7-11e7-9166-abf6ba3c2868.png)

**Comment by dennykorsukewitz** [comment]
Hi @AND51 
this issue is a little older.

Your expected behavior:
> The New-Button offers three options: New ingoing call, New outgoing call, New mail. Clicking it opens a new ticket with the desired type preselected

I'm not quite sure if I understood you correctly, but it seems to me that your expectation has already been fulfilled.

<img width="1415" alt="Zammad_Helpdesk_-_Call_Inbound" src="https://user-images.githubusercontent.com/3249687/61113095-a8bfd900-a48d-11e9-8921-7b5d1fc83898.png">

**Comment by MrGeneration** [comment]
Another hint from my site: You can also define what the default creation type will be:
https://docs.zammad.org/en/latest/console/hidden-settings.html#default-ticket-type-on-creation

**Comment by thorsteneckel** [comment]
AFAIK is @AND51 not using Zammad anymore :( And as you've pointed out the solutions that are available now I'll close this as resolved. Feel free to ask future questions in the [community board](http://community.zammad.org/).

**Comment by AND51** [comment]
Yeah, unfortunately I'm not using Zammad anymore. I received a notification about this thread by mail. I still like to help though.

@dennybresch, I know the options that you marked. But you can only reach them when you create a new ticket:

Current behaviour:
1. click "+" (see my screenshot in the 1st posting)
2. click "new ticket"
3. choose the type of the ticket at the top

Expected behaviour:
1. click "+" (see 1st posting)
2. the menu does not only offer one entry named "new ticket", but if directly exposes three options like Zendesk does:

![image](https://user-images.githubusercontent.com/26226303/61140108-1e966580-a4cb-11e9-9ead-446df4029609.png)

Well, in this screenshot Zendesk offers a "new ticket", "new user" and "new search". But Zammad could offer "Received call", "outgoing call" and "Send Email".

I hope I was able to render my idea more clearly and understandable!

**Comment by dennykorsukewitz** [comment]
Hi @AND51 

ahh, i see. Thank you for your detailed explanation.
We will discuss this topic internal.

best regards
Denny
