### ISSUE TITLE
How can I change the rails port permanently to 3010 instead of 3000?

### ISSUE THREAD

**Issue by puetzstef** [zammad/zammad#1125]
### Infos:

* Used Zammad version: Latest stable
* Used Zammad installation source: (source, package, ...) Debian package on Ubuntu 16.04
* Operating system: Ubuntu 16.04
* Browser + version: Chrome

### Expected behavior:

* I want to change the rails port permanently from 3000 to 3010

### Actual behavior:

* I don't know how to change the rails port permanently to 3010

### Steps to reproduce the behavior:

*

**Comment by martini** [comment]
Hi @puetzstef 

can I ask for the use case? Usually you do not server Zammad via port 3000 or other high port. Usually you use nginx as reverse proxy to serve Zammad to users via port 80 (http) or 443 (https).

However, you can change the port via:

```
zammad config:set ZAMMAD_RAILS_PORT=3000
zammad config:set ZAMMAD_WEBSOCKET_PORT=6042
systemctl restart zammad
```

See also https://docs.zammad.org/en/latest/appendix-configure-env-vars.html

However, I really recommend to use nginx as reverse proxy.

 -Martin

**Comment by puetzstef** [comment]
The rails process is automatically started on port 3000. This conflicts with another application which also uses port 3000.

I already use nginx as reverse proxy with this config:

upstream zammad {
    server localhost:3010;
}

**Comment by martini** [comment]
@puetzstef Thanks for feedback and clarification. Makes me happy to see that somebody knows what he is doing. 👍

**Comment by puetzstef** [comment]
Thank you. :) I found out, that with config:set ZAMMAD_RAILS_PORT=3010 I set the following export entry in /etc/zammad/conf.d/other: export ZAMMAD_RAILS_PORT="3010"

Looks OK at first sight but is ignored when I restart zammad via command "systemctl restart zammad"

**Comment by puetzstef** [comment]
Here is my process list:

> 
zammad   26254  9.6  1.0 570176 134372 ?       Ssl  14:22   0:07 ruby script/scheduler.rb start -t
zammad   26258  8.8  1.0 370504 129716 ?       Ssl  14:22   0:06 ruby script/websocket-server.rb start
zammad   27242 67.6  0.3 182512 43012 ?        Rsl  14:23   0:02 /opt/zammad/vendor/ruby-2.3.1/bin/ruby bin/rails s -p

**Comment by martini** [comment]
Hi @puetzstef 

I checked it, and I see it's only working in current develop or master branch (not in stable).

So please stay tuned. develop/master will get release with the next 4 weeks.

 -Martin

**Comment by martini** [comment]
References: https://github.com/zammad/zammad/blob/develop/Procfile here you can see the new env variables (older versions do not have this).

**Comment by puetzstef** [comment]
@martini 
I switched to the development version and as you told me it's working fine. As soon as 1.6 is released I will switch back to stable branch. Thank you for the great support! :+1:

**Comment by martini** [comment]
Thanks for feedback!
