### ISSUE TITLE
Docker container for receiving via smtp

### ISSUE THREAD

**Issue by mraerino** [zammad/zammad#1128]
I made this to easily enable smtp receiving without any modifications to the Zammad Codebase:
https://github.com/mraerino/zammad-smtp-receiver

You can then use e.g. Mailgun/Google etc. to redirect certain emails to this smtp server, which will use the MailStdin Channel to deliver the email to Zammad.

This is in early stage development, feel free to suggest changes in the repo.

**Comment by monotek** [comment]
Imho unneeded. It's already possible with postfix.

**Comment by mraerino** [comment]
Let's just say I don't want to run a whole postfix server when I can implement just the functionality needed.
Also, it is much more convenient not having to install postfix on top of the zammad container.

**Comment by monotek** [comment]
The single container docker image has postfix already installed. The docker compose container not.

How do you prevent import of spam or mails with gigabytes of size with you solution?

There are also some benefits using postfix if you like to presort your mails via procmail...

**Comment by mraerino** [comment]
Didn't know about a single docker image, but this seems like really bad design.
Presorting/Spamfiltering can be done via the main Mail-Server, like G Suite or Mailgun.

**Comment by monotek** [comment]
It's the all in one container, for easy testing: https://github.com/zammad/zammad-docker

By presorting I mean choosing the Zammad group by setting mail headers. See: https://docs.zammad.org/en/latest/channel-fetchmail.html#using-procmail-for-advanced-features-like-presorting

As this is no issue where we have to do anything I close this bug.
