### ISSUE TITLE
Telegram Chat

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#1136]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: Package
* Operating system: CentOS7
* Browser + version: 

### Expected behavior:
Would be nice if agent be able to view seen status ( seen, not seen ) of delivered message to clients telegram, Also Client receive  ticket number created in zammad ( based on telegram chat )  via telegram.

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment]
There is currently no API / callback for this in the Telegram Bot API we use. So we can't build it. Closing now. Feel free to reopen/comment if it's available.
