### ISSUE TITLE
Transfer Chat

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#1137]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: Package
* Operating system: CentOS7
* Browser + version: 

### Expected behavior:
Its a must for a teamwork that Chat sessions be able to transfer between agents.

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment]
Feature requests are now required to be discussed in our [community board](http://community.zammad.org/) first. Feel free to open a topic over there.
