### ISSUE TITLE
Visitors Stats and Invitation

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#1139]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: Package
* Operating system: CentOS7
* Browser + version: 

### Expected behavior:
Would be nice if operators be able to see active online visitors (web site)  and also be able to invite each on of them to a chat session ( A popup invitation ).

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment]
Either I don't get the use case or Zammad is not the right tool for this requirement. Feel free to open a discussion over at our [community board](http://community.zammad.org/).
