### ISSUE TITLE
Folder when setting up an IMAP account

### ISSUE THREAD

**Issue by Linus2017** [zammad/zammad#1141]
What is meant by "Folder" under the E-Mail settings? Are the mails from this folder fetched or moved to this folder?

**Comment by martini** [comment]
> Are the mails from this folder fetched or moved to this folder?

Only emails from this folder are fetched.

**Comment by Linus2017** [comment]
Hello martini, 

thank you for your feedback. When fetched the mails are deleted from the mailbox. Can this be disabled or can the mails be moved to another folder in the mailbox?

**Comment by martini** [comment]
@Linus2017 It's currently not possible (basically because some day your mail box will be full - no mails can be received anymore).

See feature issue https://github.com/zammad/zammad/issues/955 - we will implement it an you need to take care for house keeping of your imap folders.
