### ISSUE TITLE
Preset the "Wait for close" time

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#1142]
Can the "Wait for close" time be preset?

**Comment by martini** [comment]
@Linus2017 sorry for telling that, but this is a issue tracker - it's not support forum.

Second, if you create issue, please use the provided issue template. I can't understand your problem at all (no idea what your use case is, no idea what the problem is).

Thanks for understanding.

**Comment by Linus2017** [comment]
Where can I find the support forum?

When selecting the status "pending close", a time point must be specified under pending till. Can this be preset (for example in three days)?

**Comment by MrGeneration** [comment]
No reaction by user (github account has been removed).

I'm closing this issue.
For everyone that might be searchin our Support Forum, here's a link to our Community: https://community.zammad.org
