### ISSUE TITLE
Can't find ticket.preferences['telegram']

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#1143]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: Package
* Operating system: CentOS
* Browser + version: 

### Expected behavior:
Continue Telegram chat session after update client mobile number in zammad

### Actual behavior:
Chat session broken and also when i try to answer client message (
telegram personal-message  Channel ) Telegram gateway not show and also if i send a reply i get the following error message 
Delivery failed: "Unable to send telegram message: Can't find ticket.preferences['telegram'] for Ticket.find(710)
Question 1. Whats happened?
// 2. Do zammad automatically detect active telegram mobile numbers?

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment]
Please explain in detail on how to reproduce this in the latest version of Zammad.
