### ISSUE TITLE
Predefined MSG for Chat

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#1147]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: Package
* Operating system: CentOS7
* Browser + version: 

### Expected behavior:
To be Predefined Messages that available for agent to push in a chat session.
At this time predefined Greeting message could be manage by a agent, But  global predefined messages ( Available for all agents ) to use meanwhile a chat session is very useful.
Also agent be able to push an input box message ( Request visitor email address ) during chat could be nice and modern.

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment]
You can use text modules in chats - see #443.
