### ISSUE TITLE
LDAP: OU not found

### ISSUE THREAD

**Issue by ArcheNoah77** [zammad/zammad#1148]
Hi,

in the AD I have a OU called "User". All User in there should be Customer in Zammad-

### Infos:

* Used Zammad version: 1.6
* Used Zammad installation source: DEB
* Operating system: Debian 8
* Browser + version: Firefox

### Expected behavior:

* I can choose the OU "User" in the list of the Zammad configuration

### Actual behavior:

* There are no OU's in the list. Only CN's
* If i write it by myself, nothing happens after the sync:
![5e59a0b6-3ca3-11e7-9605-1216d50f07b3](https://cloud.githubusercontent.com/assets/25475591/26570714/4f3952a8-4512-11e7-8e6d-c738aee91ce6.png)
After the sync:
![7020281a-3ca3-11e7-9370-85885120fe04](https://cloud.githubusercontent.com/assets/25475591/26570731/61a2cafa-4512-11e7-81b5-3bbccd72d771.png)

**Comment by martini** [comment]
@ArcheNoah77 just a notice:

> If i write it by myself, nothing happens after the sync

Zammad is reading all possible values from your LDAP directory and offer it to select. If you do not see a value, the LDAP bind user can't read it (so usually it will not work if you enter attributes/dn's and so on manually).

**Comment by ArcheNoah77** [comment]
That is strange. In OTRS, it works fine...

**Comment by martini** [comment]
Can you attache the config of your OTRS LDAP settings - anonymised (maybe I did not understand it correctly)?

**Comment by ArcheNoah77** [comment]
[LDAP__Config .txt](https://github.com/zammad/zammad/files/1037441/LDAP__Config.txt)

**Comment by thorsteneckel** [comment]
Hi @ArcheNoah77 - I reviewed your config and it looks to me like you just have to add your configuration into the right place:

<img width="1200" alt="bildschirmfoto 2017-06-01 um 18 11 01" src="https://cloud.githubusercontent.com/assets/3873515/26689396/ce911740-46f5-11e7-91f7-62d05e1ff6e7.png">

**Comment by ArcheNoah77** [comment]
I get this message:
![1](https://cloud.githubusercontent.com/assets/25475591/26714431/a7f5c14a-4771-11e7-8c5e-c1faa0591df3.png)

Does the binduser has to be in the Base DN?

**Comment by thorsteneckel** [comment]
The bind user has to have the permission to retrieve information form the Base DN.

**Comment by thorsteneckel** [comment]
I think this is resolved. Feel free to response/reopen if there are any open questions.
