### ISSUE TITLE
Trigger: Wrong behaviour for condition "is not" "not set" 

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#1149]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04

### Expected behavior:

I use a trigger with the condition:

"Organization" "is not" "not set (not defined)" 

I expect an SQL statement like:

SELECT ... AND tickets.organization_id IS NOT NULL ...

### Actual behavior:

I see an SQL statement in the debug logs like this:

SELECT ... AND tickets.organization_id IS NULL ...

... but maybe this is just a bug in my head with double negation ;).

**Comment by rolfschmidt** [comment]
HI @hiaz ,
the condition should work now in develop branch. Thank you very much for your report.

Best regards,
Rolf
