### ISSUE TITLE
Don't confirm/deny user names on password reset

### ISSUE THREAD

**Issue by rixx** [zammad/zammad#1150]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: package
* Operating system: Debian

### Behaviour

When inputting a user name or an email address for a password reset, the user is notified if the name or address is not an actual registered user.

This is problematic since it gives away used email adresses to the public via either targeted attacks or enumeration attacks.

### Better behaviour

Tell users that a mail was sent if an account like that existed. Bonus points for performing the same actions regardless, so that response timing doesn't give anything away either.

**Comment by thorsteneckel** [comment]
This was actually fixed quite recently with https://github.com/zammad/zammad/commit/e61fa6795e9844c78e130533a0f20d5dee8b7201

Closing therefore. Thanks for your patience.
