### ISSUE TITLE
Problem with cyrillic letters in name of overviews.

### ISSUE THREAD

**Issue by pr-201** [zammad/zammad#1151]
### Infos:

* Used Zammad version: Версия Zammad 1.5.x
* Used Zammad installation source: Hosted Version
* Operating system: Windows10 / MacOS
* Browser + version: Chrome last version

### Expected behavior:

* url of "overviews" named in cyrillic letters is generate correctly and they work in user's "overviews" list like and others named in latin letters.

### Actual behavior:

* there is no created url  for "overview" named in cyrillic letters, it's url = "_" (just low dash)

### Steps to reproduce the behavior:

* create "overview" contains from cyrillic letters, for example Заммад (Zammad in russian) and look at url of this overview.

![image](https://cloud.githubusercontent.com/assets/19195245/26602044/d46a7b78-458a-11e7-8ac0-5ee338658307.png)

![image](https://cloud.githubusercontent.com/assets/19195245/26602088/f73fba5a-458a-11e7-9ba5-45c1f3e549fe.png)

as a result - mistake in interface, when we select some of cyrillic overview:

![image](https://cloud.githubusercontent.com/assets/19195245/26602134/2314c940-458b-11e7-819d-9e35118dc60d.png)

**Comment by martini** [comment]
Hi @pr-201 

it's fixed in stable. Just upgrade your Zammad package or keep enjoying Zammad hosted. 

 -Martin

**Comment by martini** [comment]
Feedback is welcome.
