### ISSUE TITLE
LDAP sync: Map LDAP groups to Zammad groups

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1152]
Hi hi 😃 
it would be awesome if there were the possibility to map LDAP-Groups to Zammad-Groups.
![screenshot_3](https://cloud.githubusercontent.com/assets/4436931/26621131/ef80b7a0-45e5-11e7-809c-9045258a2caf.jpg)
![screenshot_1](https://cloud.githubusercontent.com/assets/4436931/26621132/f18108fc-45e5-11e7-8791-9fb664eb0790.jpg)

Cheers! ^^

**Comment by martini** [comment]
Hi @MamoulianDelacroix 

there will be a new feature in future. It's called "roles". There you can define permissions + groups. 

Then you just need to assign users to roles. Wich usually reduce the administrative work and you do not have to change you ldap mappings all the time.

Feedback is welcome!

 -Martin

**Comment by MamoulianDelacroix** [comment]
@martini that sounds nice!
Thanks 😃

**Comment by martini** [comment]
@MamoulianDelacroix So I'm closing this issue for now. Just reopen if you can't handle your requirements with new role management. Thanks!

**Comment by dawnstrider** [comment]
I am also running into the problem of fetching users via LDAP and being unable to assign them to groups for ticket handling.. 

If you are closing this issue without a solution, how can we keep track of when it is going to be implemented?

**Comment by MamoulianDelacroix** [comment]
@dawnstrider like martini explained his post [above ](https://github.com/zammad/zammad/issues/1152#issuecomment-305112880), there will be a new feature in the future for that. 🤞 That it will bee in the near future 😃

**Comment by dawnstrider** [comment]
@MamoulianDelacroix thank you for the hint. However I am looking for a methodical way to track issues with Zammad. I am still in evaluation mode of this neat tool. This includes to figure out the average reponse time of issues. 
By closing open issues before they are actually resolved, it makes it very difficult in my oppinion to track those issues and their processing time. 

I do not doubt that the tickets are being worked on. I am just looking for a way to track the progress.

**Comment by Attack44** [comment]
HI, 
why is the problem set to "wontfix" Or is there something new about it? Thanks :)

Andreas

**Comment by MrGeneration** [comment]
Please don't hijack / recycle old issues.
Zammad maps ldap groups to it's roles - that's about it.

If you have more questions in that direction please consult the documentation or Zammad community (https://community.zammad.org) as this is a technical question.
