### ISSUE TITLE
Zendesk import: uninitialized constant Import::Zendesk::ObjectAttribute::Basic_priority

### ISSUE THREAD

**Issue by giezi** [zammad/zammad#1153]
### Infos:

* Used Zammad version: 1.5.1
* Used Zammad installation source: docker-image
* Operating system: Linux
* Browser + version: Chrome 58

### Expected behaviour:

The Zendesk should work without any issues.

### Actual behaviour:

We tried to import our current zendesk system (tickets, user, organization) and the import fails with the following error message:

<img width="480" alt="screen shot 2017-05-31 at 10 59 32" src="https://cloud.githubusercontent.com/assets/1326203/26624164/586b3f42-45f0-11e7-9740-264aa395cef2.png">

In the production.log we see the following entry:

> /usr/local/bundle/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
> /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
> /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
> /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
> /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
> /usr/local/bundle/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
> /usr/local/bundle/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
> /usr/local/bundle/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
> /usr/local/bundle/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
> /usr/local/bundle/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
> I, [2017-05-31T08:58:43.982741 #876]  INFO -- : Completed 422 Unprocessable Entity in 3004ms (Views: 0.1ms | ActiveRecord: 0.2ms)
> I, [2017-05-31T08:58:44.025687 #876]  INFO -- : Started POST "/api/v1/message_send" for 94.247.222.34 at 2017-05-31 08:58:44 +0000
> I, [2017-05-31T08:58:44.029470 #876]  INFO -- : Processing by LongPollingController#message_send as JSON
> I, [2017-05-31T08:58:44.029599 #876]  INFO -- :   Parameters: {"data"=>{"event"=>"login"}, "long_polling"=>{"data"=>{"event"=>"login"}}}
> I, [2017-05-31T08:58:44.031045 #876]  INFO -- : client(3554600910) new client connection
> I, [2017-05-31T08:58:44.031798 #876]  INFO -- : Completed 200 OK in 2ms (Views: 0.1ms | ActiveRecord: 0.4ms)
> I, [2017-05-31T08:58:44.120477 #876]  INFO -- : Started POST "/api/v1/message_receive" for 94.247.222.34 at 2017-05-31 08:58:44 +0000
> I, [2017-05-31T08:58:44.124211 #876]  INFO -- : Processing by LongPollingController#message_receive as JSON
> I, [2017-05-31T08:58:44.124325 #876]  INFO -- :   Parameters: {"client_id"=>"3554600910", "long_polling"=>{"client_id"=>"3554600910"}}
> E, [2017-05-31T08:58:44.332239 #930] ERROR -- : uninitialized constant Import::Zendesk::ObjectAttribute::Basic_priority (NameError)
> /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `const_get'
> /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `block in constantize'
> /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
> /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
> /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
> /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
> /opt/zammad/lib/import/zendesk/object_field.rb:30:in `backend_class'
> /opt/zammad/lib/import/zendesk/object_field.rb:26:in `import'
> /opt/zammad/lib/import/zendesk/object_field.rb:9:in `initialize'
> /opt/zammad/lib/import/base_factory.rb:37:in `new'
> /opt/zammad/lib/import/base_factory.rb:37:in `create_instance'
> /opt/zammad/lib/import/base_factory.rb:11:in `block in import_action'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:349:in `block in _all'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:457:in `each'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:457:in `public_send'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:457:in `array_method'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:298:in `method_missing'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:342:in `_all'
> /usr/local/bundle/gems/zendesk_api-1.14.0/lib/zendesk_api/collection.rb:216:in `all!'
> /opt/zammad/lib/import/zendesk/base_factory.rb:12:in `import_loop'
> /opt/zammad/lib/import/base_factory.rb:9:in `import_action'
> /opt/zammad/lib/import/zendesk.rb:27:in `start'
> /opt/zammad/lib/import/zendesk/async.rb:30:in `start_bg'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/performable_method.rb:26:in `perform'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb:84:in `block in invoke_job'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `block in initialize'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `execute'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:40:in `run_callbacks'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb:81:in `invoke_job'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:230:in `block (2 levels) in run'
> /usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
> /usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
> /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:230:in `block in run'
> /usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'

### Steps to reproduce the behaviors:

Start import wizard.

Many thanks and best regards
Reto

**Comment by thorsteneckel** [comment]
Please do the following:

1.) Create a file called `debug.rb` in your Zammad directory
2.) Insert the following code, update all the `XXX`'es and save it
3.) Run the file via `zammad run rails r debug.rb` or `rails r debug.rb` as zammad use, depending on your installation source (page/source)
4.) Post the output here. Make sure all sensetive data is anonymized!
5.) Delete the `debug.rb` file

Code:
```ruby
require 'zendesk_api'

zendesk_url      = 'https://XXX.zendesk.com/api/v2'
zendesk_username = 'XXX'
zendesk_key      = 'XXX'

client = ZendeskAPI::Client.new do |config|
  config.url      = zendesk_url
  config.username = zendesk_username
  config.token    = zendesk_key
  config.retry    = true
end

client.ticket_fields.all! do |field|
  puts '-----------------------------'
  p field
  puts '-----------------------------'
end
```

Thanks!

**Comment by giezi** [comment]
Hi @thorsteneckel 

I use the docker image of Zammad.
Unfortunately, both commands are not working:

> root@node46691-zammad:~# zammad run rails r debug.rb
> -bash: zammad: command not found



> root@node46691-zammad:~# rails r /root/debug.rb 
> Usage:
>   rails new APP_PATH [options]
> 
> Options:
>   -r, [--ruby=PATH]                                      # Path to the Ruby binary of your choice
>                                                          # Default: /usr/local/bin/ruby
>   -m, [--template=TEMPLATE]                              # Path to some application template (can be a filesystem path or URL)
>       [--skip-gemfile], [--no-skip-gemfile]              # Don't create a Gemfile
>   -B, [--skip-bundle], [--no-skip-bundle]                # Don't run bundle install
>   -G, [--skip-git], [--no-skip-git]                      # Skip .gitignore file
>       [--skip-keeps], [--no-skip-keeps]                  # Skip source control .keep files
>   -O, [--skip-active-record], [--no-skip-active-record]  # Skip Active Record files
>   -S, [--skip-sprockets], [--no-skip-sprockets]          # Skip Sprockets files
>       [--skip-spring], [--no-skip-spring]                # Don't install Spring application preloader
>   -d, [--database=DATABASE]                              # Preconfigure for selected database (options: mysql/oracle/postgresql/sqlite3/frontbase/ibm_db/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
>                                                          # Default: sqlite3
>   -j, [--javascript=JAVASCRIPT]                          # Preconfigure for selected JavaScript library
>                                                          # Default: jquery
>   -J, [--skip-javascript], [--no-skip-javascript]        # Skip JavaScript files
>       [--dev], [--no-dev]                                # Setup the application with Gemfile pointing to your Rails checkout
>       [--edge], [--no-edge]                              # Setup the application with Gemfile pointing to Rails repository
>       [--skip-turbolinks], [--no-skip-turbolinks]        # Skip turbolinks gem
>   -T, [--skip-test-unit], [--no-skip-test-unit]          # Skip Test::Unit files
>       [--rc=RC]                                          # Path to file containing extra configuration options for rails command
>       [--no-rc], [--no-no-rc]                            # Skip loading of extra configuration options from .railsrc file
> 
> Runtime options:
>   -f, [--force]                    # Overwrite files that already exist
>   -p, [--pretend], [--no-pretend]  # Run but do not make any changes
>   -q, [--quiet], [--no-quiet]      # Suppress status output
>   -s, [--skip], [--no-skip]        # Skip files that already exist
> 
> Rails options:
>   -h, [--help], [--no-help]        # Show this help message and quit
>   -v, [--version], [--no-version]  # Show Rails version number and quit
> 
> Description:
>     The 'rails new' command creates a new Rails application with a default
>     directory structure and configuration at the path you specify.
> 
>     You can specify extra command-line arguments to be used every time
>     'rails new' runs in the .railsrc configuration file in your home directory.
> 
>     Note that the arguments specified in the .railsrc file don't affect the
>     defaults values shown above in this help message.
> 
> Example:
>     rails new ~/Code/Ruby/weblog
> 
>     This generates a skeletal Rails installation in ~/Code/Ruby/weblog.
>     See the README in the newly created application to get going.
> root@node46691-zammad:~# rails --version
> Rails 4.2.7.1
> 

Is the command another one in the docker version?

Thanks and best regards
Reto

**Comment by giezi** [comment]
Hi @thorsteneckel 

Thanks for your hint!
The command is now working but it seems to fail very quickly with the following message:

```
rails r debug.rb
/usr/local/lib/ruby/2.3.0/x86_64-linux/continuation.so: warning: callcc is obsolete; use Fiber instead
Debug.rb
Emacs support available.

/usr/local/bundle/gems/concurrent-ruby-1.0.2/lib/concurrent/utility/at_exit.rb:49:                         at_exit { runner }
(rdb:1) 

```

I'm still in the ruby-debug's prompt, should I wait?

Best regards
Reto

**Comment by thorsteneckel** [comment]
Hm this looks strange and unfamiliar to me. Could you please try a different file name? Seems `debug.rb` was not the best idea 😁

**Comment by giezi** [comment]
Hi @thorsteneckel 

Yes, it was the name ;)
Please find below the output:

```
#<ZendeskAPI::TicketField {"url"=>"https://XXX.zendesk.com/api/v2/ticket_fields/223162.json", "id"=>223162, "type"=>"subject", "title"=>"Subject", "raw_title"=>"Subject", "description"=>"", "raw_description"=>"", "position"=>0, "active"=>true, "required"=>false, "collapsed_for_agents"=>false, "regexp_for_validation"=>nil, "title_in_portal"=>"Subject", "raw_title_in_portal"=>"Subject", "visible_in_portal"=>true, "editable_in_portal"=>true, "required_in_portal"=>true, "tag"=>nil, "created_at"=>2010-04-14 14:13:31 UTC, "updated_at"=>2012-08-12 13:19:24 UTC, "removable"=>false}>
-----------------------------
-----------------------------
#<ZendeskAPI::TicketField {"url"=>"https://XXX.zendesk.com/api/v2/ticket_fields/223163.json", "id"=>223163, "type"=>"description", "title"=>"Description", "raw_title"=>"Description", "description"=>"Please try to be as specific as possible when describing your problem. If you are asking multiple questions in one ticket, please number them 1, 2, 3 etc, as this will make it easier for both parties.", "raw_description"=>"Please try to be as specific as possible when describing your problem. If you are asking multiple questions in one ticket, please number them 1, 2, 3 etc, as this will make it easier for both parties.", "position"=>1, "active"=>true, "required"=>false, "collapsed_for_agents"=>false, "regexp_for_validation"=>nil, "title_in_portal"=>"Description", "raw_title_in_portal"=>"Description", "visible_in_portal"=>true, "editable_in_portal"=>true, "required_in_portal"=>true, "tag"=>nil, "created_at"=>2010-04-14 14:13:31 UTC, "updated_at"=>2013-09-24 12:06:11 UTC, "removable"=>false}>
-----------------------------
-----------------------------
#<ZendeskAPI::TicketField {"url"=>"https://XXX.zendesk.com/api/v2/ticket_fields/21515348.json", "id"=>21515348, "type"=>"tagger", "title"=>"Priority - Simple", "raw_title"=>"Priority - Simple", "description"=>"Please select it ONLY in case of real urgency!", "raw_description"=>"Please select it ONLY in case of real urgency!", "position"=>2, "active"=>true, "required"=>false, "collapsed_for_agents"=>false, "regexp_for_validation"=>nil, "title_in_portal"=>"Priority", "raw_title_in_portal"=>"Priority", "visible_in_portal"=>true, "editable_in_portal"=>true, "required_in_portal"=>false, "tag"=>nil, "created_at"=>2012-08-12 16:50:45 UTC, "updated_at"=>2013-09-24 12:25:55 UTC, "removable"=>true, "custom_field_options"=>[{"id"=>20729348, "name"=>"Urgent", "raw_name"=>"Urgent", "value"=>"urgent", "default"=>false}]}>
-----------------------------
-----------------------------
#<ZendeskAPI::TicketField {"url"=>"https://XXX.zendesk.com/api/v2/ticket_fields/223166.json", "id"=>223166, "type"=>"basic_priority", "title"=>"Priority", "raw_title"=>"Priority", "description"=>"", "raw_description"=>"", "position"=>2, "active"=>false, "required"=>false, "collapsed_for_agents"=>false, "regexp_for_validation"=>nil, "title_in_portal"=>"Priority", "raw_title_in_portal"=>"Priority", "visible_in_portal"=>true, "editable_in_portal"=>true, "required_in_portal"=>true, "tag"=>nil, "created_at"=>2010-04-14 14:13:31 UTC, "updated_at"=>2012-08-12 16:38:19 UTC, "removable"=>true, "system_field_options"=>[{"name"=>"Normal", "value"=>"normal"}, {"name"=>"High", "value"=>"high"}]}>
-----------------------------
-----------------------------
#<ZendeskAPI::TicketField {"url"=>"https://XXX.zendesk.com/api/v2/ticket_fields/223164.json", "id"=>223164, "type"=>"status", "title"=>"Status", "raw_title"=>"Status", "description"=>"Request status", "raw_description"=>"Request status", "position"=>3, "active"=>true, "required"=>false, "collapsed_for_agents"=>false, "regexp_for_validation"=>nil, "title_in_portal"=>"Status", "raw_title_in_portal"=>"Status", "visible_in_portal"=>false, "editable_in_portal"=>false, "required_in_portal"=>false, "tag"=>nil, "created_at"=>2010-04-14 14:13:31 UTC, "updated_at"=>2010-04-14 14:13:31 UTC, "removable"=>false, "system_field_options"=>[{"name"=>"Open", "value"=>"open"}, {"name"=>"Pending", "value"=>"pending"}, {"name"=>"Solved", "value"=>"solved"}]}>
-----------------------------
-----------------------------
#<ZendeskAPI::TicketField {"url"=>"https://XXX.zendesk.com/api/v2/ticket_fields/223165.json", "id"=>223165, "type"=>"tickettype", "title"=>"Type", "raw_title"=>"Type", "description"=>"Request type", "raw_description"=>"Request type", "position"=>4, "active"=>true, "required"=>true, "collapsed_for_agents"=>false, "regexp_for_validation"=>nil, "title_in_portal"=>"Type", "raw_title_in_portal"=>"Type", "visible_in_portal"=>false, "editable_in_portal"=>false, "required_in_portal"=>false, "tag"=>nil, "created_at"=>2010-04-14 14:13:31 UTC, "updated_at"=>2012-08-08 20:56:39 UTC, "removable"=>true, "system_field_options"=>[{"name"=>"Question", "value"=>"question"}, {"name"=>"Incident", "value"=>"incident"}, {"name"=>"Problem", "value"=>"problem"}, {"name"=>"Task", "value"=>"task"}]}>
-----------------------------
-----------------------------
#<ZendeskAPI::TicketField {"url"=>"https://XXX.zendesk.com/api/v2/ticket_fields/223167.json", "id"=>223167, "type"=>"group", "title"=>"Group", "raw_title"=>"Group", "description"=>"Request group", "raw_description"=>"Request group", "position"=>5, "active"=>true, "required"=>false, "collapsed_for_agents"=>false, "regexp_for_validation"=>nil, "title_in_portal"=>"Group", "raw_title_in_portal"=>"Group", "visible_in_portal"=>false, "editable_in_portal"=>false, "required_in_portal"=>false, "tag"=>nil, "created_at"=>2010-04-14 14:13:31 UTC, "updated_at"=>2012-08-12 11:25:11 UTC, "removable"=>false}>
-----------------------------
-----------------------------
#<ZendeskAPI::TicketField {"url"=>"https://XXX.zendesk.com/api/v2/ticket_fields/223168.json", "id"=>223168, "type"=>"assignee", "title"=>"Assignee", "raw_title"=>"Assignee", "description"=>"Agent assigned to your request", "raw_description"=>"Agent assigned to your request", "position"=>6, "active"=>true, "required"=>true, "collapsed_for_agents"=>false, "regexp_for_validation"=>nil, "title_in_portal"=>"Assignee", "raw_title_in_portal"=>"Assignee", "visible_in_portal"=>false, "editable_in_portal"=>false, "required_in_portal"=>false, "tag"=>nil, "created_at"=>2010-04-14 14:13:31 UTC, "updated_at"=>2012-08-12 11:25:11 UTC, "removable"=>false}>
```

Thanks & cheers
Reto

**Comment by thorsteneckel** [comment]
Thanks! Regarding the name: Interesting 🤔

However - That's what I was looking for. I'll proceed and provide a fix. Thanks so far for your support!

**Comment by giezi** [comment]
Great, many thanks for your effort!

**Comment by thorsteneckel** [comment]
Hi @giezi - This issue is fixed with the small change in the commits above. You can update your Zammad version in ~30 minutes from now. Would be great to get some feedback.

Just for the record: It's possible to switch the priority functionality in Zendesk to "basic mode":
<img width="453" alt="bildschirmfoto 2017-06-02 um 11 13 55" src="https://cloud.githubusercontent.com/assets/3873515/26723140/5c22e082-4793-11e7-8a62-1d91a746ec2e.png">

This was not reflected in the Zammad code and Zammad misunderstood the `basic_priority` ticket field type as a custom field.

**Comment by giezi** [comment]
Hi @thorsteneckel 

Many thanks for your great effort, the issue is fixed :)
Now, we are struggling with the ticket import, therefore I've opened a new issue: https://github.com/zammad/zammad/issues/1161

Have a great weekend!

Cheers
Reto
