### ISSUE TITLE
Packages: Databases are created manually

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1159]
The Zammad packages get setup by a script which creates the databases for [postgres](https://github.com/zammad/zammad/blob/6b405ce87bc5c8ccb2c943d95946f93d3a902207/contrib/packager.io/functions#L144) and [mysql](https://github.com/zammad/zammad/blob/6b405ce87bc5c8ccb2c943d95946f93d3a902207/contrib/packager.io/functions#L163) via the shell. This leads (verified at least for PG on Ubuntu) to permission errors when dropping the DB via `rake db:drop` like:

`PG::InsufficientPrivilege: ERROR: must be owner of database zammad: DROP DATABASE IF EXISTS "zammad"`

And `rake db:create` like:
`PG::InsufficientPrivilege: ERROR: permission denied to create database`

Since Rails comes with a command it should be done by Rails itself to be (future) proof:
`rake db:create`

PS: Fix for the issue above is:
```
sudo -u postgres psql
ALTER DATABASE zammad OWNER TO zammad;
ALTER USER zammad CREATEDB;
```

EDIT:
T#104547

**Comment by monotek** [comment]
Hmmm. This change would mean that the zammad psql user is able to create as many databases as he wants, right? I would prefer to not give that right to a normal user.

I suggest to just change/add the owner of the db so it's possible to delete it via rake and keep the initial db creation the way it is.

**Comment by monotek** [comment]
Added in: https://github.com/zammad/zammad/commit/0c29a596400dfd4791a77dfe8e1739ce17b63128
