### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#1160]
### Infos:

* Used Zammad version: 1.6.0-1492943947.6b405ce.jessie
* Used Zammad installation source: debian package develop
* Operating system: debian jessie
* Browser + version: several different browsers

### Expected behavior:

* when searching for "customer" search should return "customer" and "Customer"

### Actual behavior:

* when searching for "customer" search returns nothting. when searching for "Customer", search returns "Customer"

### Steps to reproduce the behavior:

* search for something with wrong case

**Comment by martini** [comment]
Do you use elasticsearch as search engine? Or what database?

**Comment by babakkazemi** [comment]
Package installation from packager.io, so db is default (pgsql i presume?)
i just RTFM, installing elasticsearch... will close if fixed ;-)

**Comment by martini** [comment]
JFI: You will going to love elasticsearch! Just fast and will search over all (including attachments). 🙊

**Comment by babakkazemi** [comment]
Having some issues with broken dependencies between openjdk-8-jre-headless and ca-certificates-java... but that's another problem ;-)

**Comment by babakkazemi** [comment]
https://github.com/zammad/zammad-documentation/pull/21
@martini yep. I love zammad. And I love elasticsearch :-). closing

**Comment by babakkazemi** [comment]
Sorry for reopening - elasticsearch does not find "everything". I can't search for ticket numbers etc by just searching for the number. Closed tickets sometimes are not displayed, even when searching with "state:closed" as argument. It seems as if the search index is not created correctly, but I have no error messages, and only ~500 tickets with a few small attachments. Elasticsearch is set up as in zammad documentation

**Comment by martini** [comment]
Did you `zammad run rake searchindex:rebuild`?

**Comment by babakkazemi** [comment]
@martini yes, after installing elasticsearch, as described in https://docs.zammad.org/en/latest/install-elasticsearch.html

**Comment by martini** [comment]
Good work!

Pls check the following:

1) What is the output of `zammad run rails r 'p Setting.get("es_url")'`

2) If you search for "state:closed", what is the output in log/production.log ?

**Comment by babakkazemi** [comment]
1) it is "" on purpose, as I had to disable it to be able to work properly :-) as es was enabled, it was "http://127.0.0.1:9200", and nmap showed it being active on port 9200, wget http://127.0.0.1 gives back
`{
  "name" : "1DkrLl0",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "tNjWgcUsQLGXXFiJLsELSg",
  "version" : {
    "number" : "5.4.1",
    "build_hash" : "2cfe0df",
    "build_date" : "2017-05-29T16:05:51.443Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.1"
  },
  "tagline" : "You Know, for Search"
}`
so everything should be ok

2) `I, [2017-06-06T11:19:04.300483 #9899]  INFO -- : execute Import::OTRS.diff_worker (try_count 0)...
I, [2017-06-06T11:19:09.324383 #9901]  INFO -- : Started GET "/api/v1/search?query=s&limit=10&_=1496736299931" for 93.203.238.29 at 2017-06-06 11:19:09 +0200
I, [2017-06-06T11:19:09.327052 #9901]  INFO -- : Processing by SearchController#search_generic as JSON
I, [2017-06-06T11:19:09.327120 #9901]  INFO -- :   Parameters: {"query"=>"s", "limit"=>"10", "_"=>"1496736299931", "search"=>{}}
I, [2017-06-06T11:19:09.407048 #9901]  INFO -- : Started GET "/api/v1/search?query=sta&limit=10&_=1496736299932" for 93.203.238.29 at 2017-06-06 11:19:09 +0200
I, [2017-06-06T11:19:09.409174 #9901]  INFO -- : Processing by SearchController#search_generic as JSON
I, [2017-06-06T11:19:09.409600 #9901]  INFO -- :   Parameters: {"query"=>"sta", "limit"=>"10", "_"=>"1496736299932", "search"=>{}}
I, [2017-06-06T11:19:09.452075 #9901]  INFO -- : Completed 200 OK in 125ms (Views: 24.0ms | ActiveRecord: 12.4ms)
I, [2017-06-06T11:19:09.540731 #9901]  INFO -- : Completed 200 OK in 131ms (Views: 30.5ms | ActiveRecord: 20.8ms)
I, [2017-06-06T11:19:09.612066 #9901]  INFO -- : Started GET "/api/v1/search?query=state&limit=10&_=1496736299933" for 93.203.238.29 at 2017-06-06 11:19:09 +0200
I, [2017-06-06T11:19:09.615943 #9901]  INFO -- : Processing by SearchController#search_generic as JSON
I, [2017-06-06T11:19:09.616056 #9901]  INFO -- :   Parameters: {"query"=>"state", "limit"=>"10", "_"=>"1496736299933", "search"=>{}}
I, [2017-06-06T11:19:09.686554 #9901]  INFO -- : Completed 200 OK in 70ms (Views: 8.4ms | ActiveRecord: 27.3ms)
I, [2017-06-06T11:19:10.187191 #9901]  INFO -- : Started GET "/api/v1/search?query=state%3A&limit=10&_=1496736299934" for 93.203.238.29 at 2017-06-06 11:19:10 +0200
I, [2017-06-06T11:19:10.189735 #9901]  INFO -- : Processing by SearchController#search_generic as JSON
I, [2017-06-06T11:19:10.189803 #9901]  INFO -- :   Parameters: {"query"=>"state:", "limit"=>"10", "_"=>"1496736299934", "search"=>{}}
I, [2017-06-06T11:19:10.228425 #9901]  INFO -- : Completed 200 OK in 39ms (Views: 0.1ms | ActiveRecord: 22.2ms)
I, [2017-06-06T11:19:10.384760 #9901]  INFO -- : Started GET "/api/v1/search?query=state%3Ac&limit=10&_=1496736299935" for 93.203.238.29 at 2017-06-06 11:19:10 +0200
I, [2017-06-06T11:19:10.387106 #9901]  INFO -- : Processing by SearchController#search_generic as JSON
I, [2017-06-06T11:19:10.387176 #9901]  INFO -- :   Parameters: {"query"=>"state:c", "limit"=>"10", "_"=>"1496736299935", "search"=>{}}
I, [2017-06-06T11:19:10.422572 #9901]  INFO -- : Completed 200 OK in 35ms (Views: 0.1ms | ActiveRecord: 16.4ms)
I, [2017-06-06T11:19:10.583986 #9901]  INFO -- : Started GET "/api/v1/search?query=state%3Aclo&limit=10&_=1496736299936" for 93.203.238.29 at 2017-06-06 11:19:10 +0200
I, [2017-06-06T11:19:10.586739 #9901]  INFO -- : Processing by SearchController#search_generic as JSON
I, [2017-06-06T11:19:10.586862 #9901]  INFO -- :   Parameters: {"query"=>"state:clo", "limit"=>"10", "_"=>"1496736299936", "search"=>{}}
I, [2017-06-06T11:19:10.627238 #9901]  INFO -- : Completed 200 OK in 40ms (Views: 0.2ms | ActiveRecord: 17.2ms)
I, [2017-06-06T11:19:10.782236 #9901]  INFO -- : Started GET "/api/v1/search?query=state%3Aclose&limit=10&_=1496736299937" for 93.203.238.29 at 2017-06-06 11:19:10 +0200
I, [2017-06-06T11:19:10.784300 #9901]  INFO -- : Processing by SearchController#search_generic as JSON
I, [2017-06-06T11:19:10.784358 #9901]  INFO -- :   Parameters: {"query"=>"state:close", "limit"=>"10", "_"=>"1496736299937", "search"=>{}}
I, [2017-06-06T11:19:10.821946 #9901]  INFO -- : Completed 200 OK in 38ms (Views: 0.2ms | ActiveRecord: 17.3ms)
I, [2017-06-06T11:19:10.987193 #9901]  INFO -- : Started GET "/api/v1/search?query=state%3Aclosed&limit=10&_=1496736299938" for 93.203.238.29 at 2017-06-06 11:19:10 +0200
I, [2017-06-06T11:19:10.990075 #9901]  INFO -- : Processing by SearchController#search_generic as JSON
I, [2017-06-06T11:19:10.990150 #9901]  INFO -- :   Parameters: {"query"=>"state:closed", "limit"=>"10", "_"=>"1496736299938", "search"=>{}}
I, [2017-06-06T11:19:11.026730 #9901]  INFO -- : Completed 200 OK in 37ms (Views: 0.1ms | ActiveRecord: 22.8ms)`
please note es_url is still set to ""

**Comment by martini** [comment]
> please note es_url is still set to ""

It es_url is set to "" no es backend will be used (even if it already got index, with valid es_url). What if you do the following:

1) `zammad run rails r 'p Setting.set("es_url", "http://127.0.0.1:9200")'`

2) `zammad run rails r 'p Setting.get("es_url")' `

3) `zammad run rake searchindex:rebuild`

4) Search for "state:closed"

**Comment by babakkazemi** [comment]
@martini rebuilding the search index a second time seems to have done the trick... maybe the index wasn't built properly first time. Thanks for your help
