### ISSUE TITLE
New ticket state is not listed

### ISSUE THREAD

**Issue by Linus2017** [zammad/zammad#1164]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: source
* Operating system: Debian 8.8
* Browser + version: 

### Expected behavior:

* Sets the new ticket state and listed

### Actual behavior:

* Ticket state can be created but is not listed

### Steps to reproduce the behavior:

* https://docs.zammad.org/en/latest/admin-console.html
When I create the new ticket state with the following command in the rails console:

`rails> Ticket::State.create_or_update(
         name: 'customer feedback',
         state_type_id: Ticket::StateType.find_by(name: 'open').id,
         ignore_escalation: true,
         created_by_id: 1,
         updated_by_id: 1,
       )`

It is indicated that this has been created with the ID 8
In Zammad I can not see the status. Also the following command does not show the new status:

`rails> Ticket::StateType.all`

The command only shows me all ticket states up to ID 7

What is the solution?

**Comment by martini** [comment]
Hi @Linus2017 

there is already a feature request to do this via UI.

In the meantime you can add new state via console, just follow this https://github.com/zammad/zammad/issues/574#issuecomment-286464635

Thanks!

 -Martin
