### ISSUE TITLE
User can not be removed from organization

### ISSUE THREAD

**Issue by Linus2017** [zammad/zammad#1165]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: source
* Operating system: Debian 8.8
* Browser + version: 

### Expected behavior:

* Remove users from the organization

### Actual behavior:

* User can not be removed from organization
User remains in the organization

### Steps to reproduce the behavior:

* Edit a user under Settings > User 
Remove user from the organization entry and save
User remains in the organization

**Comment by rolfschmidt** [comment]
Hi @Linus2017 ,
i fixed the problem in the develop branch. Thank you very much for your support!

Best regards,
Rolf
