### ISSUE TITLE
API - hypermedia/schema for python coreapi-cli

### ISSUE THREAD

**Issue by kevin-olbrich** [zammad/zammad#1168]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: (source, package, ...): Repo for CentOS
* Operating system: CentOS 7
* Browser + version: -

### Expected behavior:

> coreapi get https://zammad.example.com/api/v1

...should return a hypermedia/schema for API clients like coreapi.

With hypermedia/schema, API clients are able to map the API directly to dynamic models for easy consumption.
Example: https://github.com/core-api/core-api/blob/master/docs/tools-and-resources/example-services.md

### Actual behavior:

* (/) 404: Requested Ressource was not found.
* (/tickets): 401: Unauthorized - Sorry, but you're not allowed to access this page. If you're registered please log in and refresh this page.

The document should be available on root (/) for unauthenticated users to fetch the doc and set the token.

### Steps to reproduce the behavior:

> coreapi get https://zammad.example.com/api/v1

**Comment by kevin-olbrich** [comment]
Can someone post an example for creating tickets via coreapi?

**Comment by hanneshal** [comment]
We extended the documentation a while ago.
https://docs.zammad.org/en/latest/api-ticket.html#create

Maybe this helps. We won't maintain or offer any other scheme
