### ISSUE TITLE
The ability to set the platform default language

### ISSUE THREAD

**Issue by macnibblet** [zammad/zammad#1171]
Heya,

I love the platform, but I have a slight issue. I would like to set the default language from English to another language for newly created users. For our support personnel and developers, it's not really a problem. But for our clients, some which are terrible at English it would be good if we could change the default language.

**Comment by msasso** [comment]
It would be nice for our organization, too

**Comment by martini** [comment]
JFI: You will find this in upcoming Zammad under Admin -> Settings -> System -> Locale (Defines the system default language.)

**Comment by imbehind** [comment]
Wouldn't it be better if the default customer language could be set up according to group as well, overriding the system default?

That way we can work with people from different countries using the same Zammad instance.

i.e. we can set up all mails from support@example.de to have German default language and from support@example.co.uk to have English.

**Comment by martini** [comment]
Hi @imbehind 

> Wouldn't it be better if the default customer language could be set up according to group as well, overriding the system default?
>
> That way we can work with people from different countries using the same Zammad instance.

It's about the frontend language. Zammad is detecting it via browsers accepted languages until the user is setting a certain language.

So for me it makes no sense to bind the ui language on groups because it a user individual selection.

Any way. Thanks for feedback! 👍 

 -Martin

**Comment by tarreislam** [comment]
same here, locale is not working in Chrome, works fine in edge and IE 11
