### ISSUE TITLE
Feature Wish: code/preformat and teletype formatting

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#1172]
Hi there,

besides the supported formats bold, underline, strikethrough and italic it would be very, very nice to also have formats for preformatted/code sections and teletype text.  These constitute a considerable part of our ticket content but currently cannot be appropriately formatted.

Syntax highlighting/colouring is not necessary, though.

Cheers
frank

**Comment by MartinBorg** [comment]
This looks like a duplicate of #1055. There is also a workaround.

**Comment by fthommen** [comment]
You are right.  I'll close this ticket now
