### ISSUE TITLE
Notify other agent on ticket update

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#1173]
### Infos:

* Used Zammad version: 1.6.0-1492943947.6b405ce.jessie
* Used Zammad installation source: debian package develop
* Operating system: irrelevant
* Browser + version: irrelevant

### Expected behavior:

* I am trying to set up something like "Tag is "AGENTNAME"", "Action is Updated, "Send email to agent "AGENTNAME""

### Actual behavior:

* When configuring action, I can not choose "Send email to agent "AGENTNAME""

Any way to work around this? We often have tickets that we need to watch, but they are owned by other agents

**Comment by MrSnoozles** [comment]
Would something like #208 fit your use case?

**Comment by babakkazemi** [comment]
@MrSnoozles seems to fit my use case, closing issue

**Comment by thorsteneckel** [comment]
Nice - Thanks @MrSnoozles!
