### ISSUE TITLE
OAuth2: Office365

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1177]
Zammad provides the possibility to login to a list of OAuth2 Providers like GitHub, Twitter etc. Office365 is none of them.

There should be a possibility to add Office365 OAuth2 authentication without using the Generic OAuth2 configuration which is reserved for custom/own services.

Omniauth provides [a gem](https://github.com/zammad/zammad/issues/613#issuecomment-307325048) for this.

Ticket# 105215

**Comment by martini** [comment]
Hi @mrflix 

a new icon is needed for login via Office365.

<img width="702" alt="screen shot 2017-07-13 at 14 25 27" src="https://user-images.githubusercontent.com/110226/28174423-c2fee674-67f1-11e7-87e7-4769838f3d25.png">

Thanks!

 -Martin
