### ISSUE TITLE
Add Time Units to possible Overview attributes

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#1178]
Please add "Time Units" as selectable attribute in overviews
![image](https://user-images.githubusercontent.com/23480845/26981988-29da4cf6-4d37-11e7-9021-8a2c1b453d40.png)

**Comment by bbx-github** [comment]
I think "time units" translate to "Berechnete Zeit" and is selectable as of now? So this issue can be closed?
![zammad_choose_time_units](https://user-images.githubusercontent.com/53237674/197038423-f12b0293-5ae0-4613-81b4-4f3f588354a9.png)

**Comment by dominikklein** [comment]
@bbx-github thanks for the hint :-)
