### ISSUE TITLE
LDAP - Role assignment based on groups does not work

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#1179]
I am using OpenLDAP as a LDAP server with Fusion Directory as management platform (https://www.fusiondirectory.org), installed on a Debian 8 VM.

The configuration goes smooth, Zammad detects the groups on my server:

![ldap2](https://user-images.githubusercontent.com/3321655/26987543-356886c2-4d4c-11e7-9a5c-fafcfd29bdd7.jpg)

The groups "trainer" and "vorstand" are the groups which I have configured to get the "Agent" role in Zammad.

**To get my user filtered correctly I need to add the user filter "(objectClass=person)" into the user filter field. This field is empty by default**, if it's not filled we'll get an error later on by Zammad.

![ldap2](https://user-images.githubusercontent.com/3321655/26987002-24f1be50-4d4a-11e7-9033-f72385bd1361.jpg)

Zammad syncs the users afterwards:

![ldap4](https://user-images.githubusercontent.com/3321655/26987038-5492dd88-4d4a-11e7-87c3-9ec911f3155c.jpg)

Unfortunately the assignment does not work:

Users which are not in Zammad already, but in the group "vorstand" or "trainer" do not get the right role assignment in Zammad! Let's take this user "Dagmar Schlier" as an example. She's definitely in the group "trainer":

![ldap5](https://user-images.githubusercontent.com/3321655/26987194-d33a4180-4d4a-11e7-8202-9ec5a5e5995e.jpg)

This group should get the "Agent" role in Zammad:

![ldap7](https://user-images.githubusercontent.com/3321655/26987268-31dff8b0-4d4b-11e7-9344-eb76ca9695d2.jpg)

But the synced user from LDAP has no role at all:

![ldap9](https://user-images.githubusercontent.com/3321655/26987394-b67758f2-4d4b-11e7-8c90-b5cba4fadee5.jpg)
![ldap10](https://user-images.githubusercontent.com/3321655/26987404-be0d89b0-4d4b-11e7-8c01-d99c4bb81736.jpg)

Unfortunately that's a showstopper currently ...

**Comment by thorsteneckel** [comment]
Fixed with the commits above. Actually #1180 is a sub-issue of this one. The debugging was performed in the other issue.
