### ISSUE TITLE
Ticket create state after OTRS import is wrong

### ISSUE THREAD

**Issue by felicitus** [zammad/zammad#1184]
### Infos:

* Used Zammad version: 1.5.x (1.5.0-1496760218.94263e9.jessie)
* Used Zammad installation source: Package
* Operating system: Debian Jessie
* Browser + version: doesn't matter

### Prerequisites
* I have migrated from OTRS using the OTRS migration plugin

### Expected behavior:
* When new tickets are created, no matter if via mail or via the web frontend, the default state should be "new"

### Actual behavior:
* When new tickets are created, no matter if via mail or via the web frontend, the default state is "closed successfully"

### Steps to reproduce the behavior:
* Migrate using the OTRS plugin

### Additional information
This is related to issue #881.

The bug has probably been fixed already, however, my installation is non-functional due to the above issue.

So this is a request on how to fix the installation. If I would be able to configure the state ID for a new ticket somewhere, I believe nothing much would need to be adjusted.

However, if the ticket state is hardcoded, I believe I would have to fix the states manually somehow. Can you give me instructions on how to do that?

**Comment by thorsteneckel** [comment]
Hi @felicitus - sorry for the delay. But I come back with good news 🎉  I was able to reproduce the error, track it down and fix it 💪  Please update to the latest version in about 30 minutes from now to have it in your stable system. If you already have a system and want to fix it please use the [rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console) to execute the statement `Ticket::State.find(2).update_attribute(:default_follow_up, false)` which should fix the error for systems already in use, too.

Feedback would be great!
