### ISSUE TITLE
Modify booked time

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1187]
Hihi 😄 ,

is it possible to modify the booked time? 
For example, like here
![screenshot_7](https://user-images.githubusercontent.com/4436931/27280505-721e0526-54e8-11e7-9cfa-5d78efa4510b.jpg)
I misstyped my time, I wanted to write only 10 instead of 110. 
Is there a comfortable way to change that insteat of booking an additional "-100"?

**Comment by martini** [comment]
> Is there a comfortable way to change that insteat of booking an additional "-100"?

No. And additional booking with "-" is currently required. This is the only way be revisions save.

**Comment by MamoulianDelacroix** [comment]
Ok, thanks for the informationen

**Comment by martini** [comment]
Thanks for feedback!
