### ISSUE TITLE
create user with valid password via REST api

### ISSUE THREAD

**Issue by alena891** [zammad/zammad#1190]
### Expected behavior:

I create a user on request:

Responsible author, but the password does not reach the user. I need to send tickets from the user's email and password,

### Actual behavior:

I create a user by query. The request is triggered, the user is created, but the password is not pushed in the administrator's office. It is very necessary for me to further authorize the user to post tickets from him, and not from the admin

### Steps to reproduce the behavior:

curl_setopt_array($curl, array(
	CURLOPT_URL => "https://support.linxact.com/api/v1/users",
	CURLOPT_RETURNTRANSFER => true,
	CURLOPT_ENCODING => "",
	CURLOPT_MAXREDIRS => 10,
	CURLOPT_TIMEOUT => 30,
	CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
	CURLOPT_CUSTOMREQUEST => "POST",
	CURLOPT_POSTFIELDS =>
		"{\r\n\"firstname\": \"$user->user_firstname\",\r\n\"lastname\": \"$user->user_lastname\",\r\n\"email\" : \"$user->user_email\",\n\t\"role_ids\":\"3\",\r\n\"password\": \"qwerty12345\"}",
	CURLOPT_HTTPHEADER => $curl_httpheader
));

How can I create a password and what do I need? I have been suffering for a very long time with this question.
Thank you

**Comment by martini** [comment]
Hi @alena891 

for me, the problem is not clear:

> Responsible author, but the password does not reach the user. I need to send tickets from the user's email and password

You mean you create and user via REST, but the submitted "password" is not valid for the new created user if the user tries to login to Zammad?

 -Martin

**Comment by alena891** [comment]
Create a user with
POST /api/v1/users
I pass the password to password

And how do I create a user with an email and password to log in to this data in order to create a ticket using APE?

**Comment by martini** [comment]
Hi @alena891 

I just tested the following:

1) User create via curl/REST:

`curl -u test@zammad.com:test123 -H "Content-Type: application/json" -X POST -d '{"firstname":"Bob","lastname":"Smith","email":"email_of_customer@example.com","roles":["Customer"],"password":"some_password"}' https://xxx.zammad.com/api/v1/users`

2) went to https://xxx.zammad.com with my browser and logged in via "email_of_customer@example.com" and password "some_password"

**Required permissions to set passwords:**
Attention: The API user (in my case "test@zammad.com") need to have admin.user permissions to be able to set the password of users. Normal agents only can create/update users but not the password field (for security reasons).

**Welcome email:**
One more note, it your pass `"invite":true` in your payload, the customer get's an welcome email.

**Real names (no ids):**
Also interesting is, you do not need to use id values (like role_ids). You can use the "name" values of the objects too. In this case `"roles":["Customer"]` which looks more clear and can be used with any Zammad instance (no matter what database ids are existing).

 -Martin

**Comment by alena891** [comment]
Yes, it is created, but only thankful
"invite":true

And yet, I then try to get https://support.linxact.com/api/v1/ticket_articles/182

182 - id ticket, which has just been created. To me in the answer
{
"Error": "Could not find Ticket :: Article with" id "= 182"
}
, Though before it eyes normally

{"ID": 182, "group_id": 1, "priority_id": 2, "state_id": 1, "organization_id": NULL, "number": "10151", "name": "gfhgfhgfhf", "owner_id" : 1, "customer_id": 30, "note": "some note", "first_response_at": null, "first_response_escalation_at": null, "first_response_in_min": null, "first_response_diff_in_min": null, "close_at": null, "close_escalation_at ": Zero," close_in_min ": zero," close_diff_in_min ": zero," update_escalation_at ": zero," update_in_min ": zero," update_diff_in_min ": zero," last_contact_at ": zero," last_contact_agent_at ": zero," last_contact_customer_at ": Create_article_type_id ": 10," create_article_type_id ": 1," article_count ": 1," escalation_at ": zero," pending_time ": zero," type ": zero," TIME_UNIT ": zero," preferences ": {}," Updated_by_id ": 3," created_by_id ": 3," created_at ":" 2017-06-20T12: 04: 51 .274Z "," updated_at ":" 2017-06-20T12: 04: 51.349Z "}]

Why can not I get ticket_articles?

**Comment by martini** [comment]
> And yet, I then try to get https://support.linxact.com/api/v1/ticket_articles/182
> "Error": "Could not find Ticket :: Article with" id "= 182"

That's really strange. Can you attach the log/production.log to this issue?

**Comment by alena891** [comment]
https://support.linxact.com
Zammad is installed here. I can not find  log/production.log

**Comment by martini** [comment]
It's located in the files system of the server under /opt/zammad/log/production.log

**Comment by alena891** [comment]
production.log file
https://drive.google.com/file/d/0B56tQUgCi1B6WW9QbVIzRDE4Mm8/view?usp=sharing

**Comment by martini** [comment]
Now I see. The resource/url of tickets is different. Your use:

`https://support.linxact.com/api/v1/ticket_articles/182`

But for tickets it's:

`https://support.linxact.com/api/v1/tickets/182`

Ticket is the container. In the ticket you have several articles (or should have at least one). An article is representing one communication step.

Side note 1: You can create a ticket with an article, just put "article" as ticket attribute into the playload (see https://docs.zammad.org/en/latest/api-ticket.html#create ).

Side note 2: You can add the "extended=true" param to the resources, then you also get the real names - not only ids (e. g. `https://support.linxact.com/api/v1/tickets/182?expand=true`)

PS: There are examples, maybe you can work with that too https://docs.zammad.org/en/latest/api-intro.html#example-curl-requests-for-tickets-and-users

**Comment by alena891** [comment]
Thank you, ticket_articles received.

Now the problem is to update the ticket from the user I created with a login and password. Writes an authorization error. If you do not log in from the customer, tickets through PUT are added as from the admin under which I logged in. How here to be? http://clip2net.com/s/3LwAL4k

**Comment by alena891** [comment]
I when I go in a role of the admin, I see only this panel

http://c2n.me/3LwHjRk

**Comment by thorsteneckel** [comment]
Please use our [community board](http://community.zammad.org/) for technical questions. Thanks!
