### ISSUE TITLE
Reply email gets bounced

### ISSUE THREAD

**Issue by Signum** [zammad/zammad#1193]
### Infos:

* Used Zammad version: 1.5.0-149702
* Used Zammad installation source: Debian package
* Operating system: Debian 8.8 "Jessie"
* Browser + version: Chrome (but not relevant)

### Expected behavior:

* Email reply reaches the user who opened the ticket.

### Actual behavior:

* Email gets bounced.

### Steps to reproduce the behavior:

* Use an LDAP backend create a user that is called "John Doe [FOO]" with a valid email address like john.doe@example.com.
* Let the user create a new ticket via email.
* Reply to the ticket.

### Additional information

The bounce says:
```
<"<john.doe"@example.com>>: bad address syntax
<"[FOO]"@helpdesk.example.com> (expanded from <"[FOO]">): unknown user: "[FOO]"
<Doe@helpdesk.example.com> (expanded from <Doe>): unknown user: "doe"
<John@helpdesk.example.com> (expanded from <John>): unknown user: "john"
```
I tried both delivering locally using a Postfix MTA and using the SMTP connector. The mail server is a Microsoft Exchange 2013 server.

### production.log
```
I, [2017-06-20T13:52:38.651111 #5021]  INFO -- : Send email to: 'John Doe [FOO] <john.doe@example.org>' (from "Christoph Haas via IT-Support" <it-support@example.org>)
```
### Postfix mail log

When delivering via localhost I get this in my Postfix's mail.log:
```
Jun 20 13:52:38 helpdesk postfix/pickup[4192]: 7E0D541691: uid=113 from=<it-support@example.org>
Jun 20 13:52:38 helpdesk postfix/cleanup[15992]: 7E0D541691: message-id=<20170620115236.93.190447@helpdesk.example.org>
Jun 20 13:52:38 helpdesk postfix/qmgr[6023]: 7E0D541691: from=<it-support@example.org>, size=4149, nrcpt=4 (queue active)
Jun 20 13:52:38 helpdesk postfix/error[15995]: 7E0D541691: to=<<john.doe@example.org>>, relay=none, delay=0.38, delays=0.16/0.05/0/0.17, dsn=5.1.3, status=bounced (bad address syntax)
Jun 20 13:52:38 helpdesk postfix/local[15996]: 7E0D541691: to=<[FOO]@helpdesk.example.org>, orig_to=<[FOO]>, relay=local, delay=0.39, delays=0.16/0.19/0/0.04, dsn=5.1.1, status=bounced (unknown user: "[FOO]")
Jun 20 13:52:38 helpdesk postfix/local[15998]: 7E0D541691: to=<Doe@helpdesk.example.org>, orig_to=<Doe>, relay=local, delay=0.39, delays=0.16/0.22/0/0, dsn=5.1.1, status=bounced (unknown user: "doe")
Jun 20 13:52:38 helpdesk postfix/local[15999]: 7E0D541691: to=<John@helpdesk.example.org>, orig_to=<John>, relay=local, delay=0.4, delays=0.16/0.23/0/0.01, dsn=5.1.1, status=bounced (unknown user: "john")
Jun 20 13:52:38 helpdesk postfix/bounce[16000]: 7E0D541691: sender non-delivery notification: D9B5F41686
Jun 20 13:52:38 helpdesk postfix/qmgr[6023]: 7E0D541691: removed
```

### Note

I am not sure if square brackets are allowed in the name part of an email address. But maybe it's the way that Zammad creates notification/reply emails.

### Further note

Sending replies to other users works well. I suspect the [FOO] part.

**Comment by babakkazemi** [comment]
@Signum are you getting your users from AD via LDAP?

**Comment by Signum** [comment]
Correct.

**Comment by martini** [comment]
@Signum Can you add an screenshot of the article header - the from line of the senders email (just click on body of article/email). Thx!

**Comment by Signum** [comment]
I can see it the other way round - the first response from Zammad to the user. The "from" line should be equivalent to the "to" line here.

Headers:

```
Date: Tue, 20 Jun 2017 13:52:38 +0200
From: Christoph Haas via IT-Support <it-support@example.org>
To: John Doe [FOO] <john.doe@example.org>
[…]
X-Powered-By: Zammad - Helpdesk/Support (https://zammad.org/)
X-Mailer: Zammad Mail Service
```

**Comment by thorsteneckel** [comment]
Hi @dennybresch - is this issue still open or have your changes fixed it? If it's still open please assign @muhammadn and write a short summary of what and why you changed things like that and what is still need it. Thanks!

**Comment by dennybresch** [comment]
Hi @muhammadn ,
i actually fixed this issue with above commit. 
It's been a while and really don't know if this is fixed complete.
Could you please check this again and try to reproduce this.
Thank you :)

**Comment by thorsteneckel** [comment]
This has been fixed for some time now. Feedback is highly appreciated.

**Comment by Signum** [comment]
Sorry for the late response. I just verified that the problem is gone. At least with version 2.4.0 I have just updated to. Thanks.
