### ISSUE TITLE
Add date/time information to time accounting (xls export)

### ISSUE THREAD

**Issue by sthag** [zammad/zammad#1194]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: deb package
* Operating system: 16.04
* Browser + version: Chrome 59

### Expected behavior:

* time accounting has a column for ticket creation/close date and time
* the xls export in admin section time accounting has this information too

### Actual behavior:

* the time export is divided into years and month
* it is not possible to track specific date/time info for individual tickets via the time accounting feature

### Steps to reproduce the behavior:

* work on tickets and measure the time

This is meant as a feature request and an addition to the issue #1071

**Comment by rolfschmidt** [comment]
Hi @sthag 

you mean at this place?

![zammad_time_accouting_by_ticket_created_closed_datetime](https://user-images.githubusercontent.com/5445062/27483484-e2951408-5825-11e7-9e8f-241de6c93efc.png)

Best regards,
Rolf

**Comment by sthag** [comment]
@rolfschmidt yes, that's exactly it.

As I now see these date and time unit values, there's something else coming to my mind.
It would be great if there is a possibility to have kind of a boolean field in the exported file, which shows if the ticket has been escalated.
If the necessary data (start, stop, duration) is already in the export it's of course possible to accomplish this with some excel magic.

**Comment by rolfschmidt** [comment]
Hi @sthag ,
the report for the ticket list will now contain much more information of the ticket in the xls report. Hope this will give you more possibilities to handle your requirements. The changes are available in the develop branch.

Best regards,
Rolf
