### ISSUE TITLE
New Integration

### ISSUE THREAD

**Issue by anandsork** [zammad/zammad#1197]
If I want to introduce new integration, how can I start approaching it? I tried to find the documentation around it, but could not find.
While going through code, I got the impression that if I place logic inside app/models/transaction, I can take certain actions on ticket updates.  However I could not figure out if I need to alter the database seed file. I was thinking to see how (& where) slack is implemented(referred) & implement likewise. 
Some pointers related to these will help.

**Comment by thorsteneckel** [comment]
Hi @anandsork - nice to hear about your plans. What kind of integration do you have in mind? Do you want to add a Channel to handle communication, an Import of any sort of data or what else? Will it be a public extension? Which system you want to integrate?

We will provide further information and documentation how to achieve these things.

**Comment by thorsteneckel** [comment]
Please response if you're still interested.

**Comment by anandsork** [comment]
Sorry for late reply. 
We are having some customers who would like to have ticketing system hosted. We shall host zammad for them. They want to integrate the ticket data into their CRM. So essentially we need webhook for any article/note added. We need some APIToken for security as well. (webhook getting called with some basic auth). 
There is one thread going on webhooks, but still not closed. As it may take some time to have full fledged solution, I am thinking to develop what is bare minimum required for us. There may be some hard coding, but at least workable for us. 
The idea popped up internally why not have separate integration screen for us, so that we can add something in future if needed. (Current asap requirement is about webhook with basic auth in whatever way implemented ).
2 variable things needed for any customer which she shall fill. One is Endpoint to call, Second is APIToken. Rest of the logic (How ticket data is formatted and sent) would be same.
Hope I am clear enough.

**Comment by thorsteneckel** [comment]
Please see #290 for the webhook support request. We are currently working on other features so it's not clear when webhooks will be implemented. However we are open for pull requests. Please include us in your integration plans if so - so there will be no obstacles merging it.

If you're interested in a timely integration and professional managed hosting plans please contact our commercial team at zammad.com 🥇

**Comment by anandsork** [comment]
Thanks for the prompt reply. As it would take some time, I would like to implement myself, a bare minimum thing. Are there any pointers/documentation available?

For hosting, our clients would like us to host it with NDA (non disclosure agreement) signed. We had asked that earlier for the same. For the same I had asked a question on another thread.

**Comment by thorsteneckel** [comment]
Since we are only interested in sustainable solutions this won't be able get integrated into Zammad which will result in high maintainance efforts. However to answer your question there are no documentations for extending Zammad at the current state since we are still working on a solid core which will result in breaking internal API changes.

To get started I recommend you to get a good understanding how Ruby on Rails works. After that it's all about callbacks, observers, models and plain old ruby objects I guess. If you're in need of commercial support find us at zammad.com

**Comment by lazmo88** [comment]
@thorsteneckel Webhooks will be great, but I would be interested adding 2 way channel for communication. In our case SMS Gateway like Twilio or Nexmo.

Any documentation how to get started? Would it be possible to consider 3rd party plugin support for Zammad?
