### ISSUE TITLE
Reopen ticket on mail delivery failure

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#1198]
### Infos:

* Used Zammad version: all
* Used Zammad installation source: (source, package, ...) all
* Operating system: all
* Browser + version: all

### Expected behavior:

* A closed ticket should be reopened if a mail was not delivered and a Delivery Status Notification (DSN) was received.

### Actual behavior:

* Ticket stay closed

### Steps to reproduce the behavior:

* Create a ticket and send an email to a non-existing recipient.

**Comment by martini** [comment]
@rolfschmidt 

Reopen is here needed https://github.com/zammad/zammad/blob/develop/app/models/observer/ticket/article/communicate_email/background_job.rb#L157

It's also good to have it in all background job backends.

The tests can get enhanced here https://github.com/zammad/zammad/blob/develop/test/integration/email_deliver_test.rb

**Comment by martini** [comment]
It's implemented in master.
