### ISSUE TITLE
Lists not updating correctly in overviews grouped by owner

### ISSUE THREAD

**Issue by HolgerHeckeroth** [zammad/zammad#1202]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: (source, package, ...) Ubuntu DEB
* Operating system: Ubunt 16.04
* Browser + version: Chrome 59.0.3071.10

### Expected behavior:

* New tickets are shown in separate group without owner.
* On owner change the are shown grouped by that owner.

### Actual behavior:

* Name of the group changes. So that there are two groupings by the same owner.

### Steps to reproduce the behavior:

* Group open tickets overview by owner
* Make a new ticket. Look at overview.
* Change owener of new ticket. Open overview again.

**Comment by HolgerHeckeroth** [comment]
P.S.: by reloading the page the tickets are shown grouped correctly

**Comment by martini** [comment]
@HolgerHeckeroth 

> P.S.: by reloading the page the tickets are shown grouped correctly

Thanks for this important information. Will analyse this....

**Comment by thorsteneckel** [comment]
Seems this one was fixed in the meantime. Can't reproduce. Works as described in expected. Feel free to provide a step by step guide on how to reproduce this in the latest version.
