### ISSUE TITLE
create user with valid password via REST api

### ISSUE THREAD

**Issue by alena891** [zammad/zammad#1204]
problem is to update the ticket from the user I created with a login and password. Writes an authorization error. If you do not log in from the customer, tickets through PUT are added as from the admin under which I logged in. How here to be? http://clip2net.com/s/3LwAL4k

**Comment by alena891** [comment]
I when I go in a role of the admin, I see only this panel

http://c2n.me/3LwHjRk

**Comment by babakkazemi** [comment]
Isn't this duplicate to #1190?

**Comment by alena891** [comment]
Yes, but unfortunately, I did not receive a response

**Comment by martini** [comment]
@babakkazemi Thanks for support.

@alena891 Sorry, we really hurry to take care of all issue. But we get more feedback as we can handle right now. In case you have a business need you can use our commercial services for bug/issue escalation (see https://zammad.com/pricing#selfhosted) to get responses which high priority. Thanks for understanding.
