### ISSUE TITLE
RTL support with css issues

### ISSUE THREAD

**Issue by martini** [zammad/zammad#1205]
Just added RTL support (in this case for Hebrew (עִבְרִית)) and found out that there are some css issue.

To reproduce update develop branch and execute: 

1. rake db:migrate
2. rails r 'Locale.load'
3. rails r 'Translation.load'
4. F5 + login via web interface -> Profile -> Language and select "Hebrew (עִבְרִית)"

<img width="1264" alt="screen shot 2017-06-26 at 14 43 04" src="https://user-images.githubusercontent.com/110226/27539750-fe5d6212-5a7d-11e7-8f68-9c0a3d8e9934.png">
<img width="722" alt="screen shot 2017-06-26 at 14 29 33" src="https://user-images.githubusercontent.com/110226/27539753-fe821e4a-5a7d-11e7-9bc9-dc905237de0d.png">
<img width="728" alt="screen shot 2017-06-26 at 14 29 02" src="https://user-images.githubusercontent.com/110226/27539755-fe8409da-5a7d-11e7-9d57-2cc274171465.png">
<img width="718" alt="screen shot 2017-06-26 at 14 28 33" src="https://user-images.githubusercontent.com/110226/27539752-fe817418-5a7d-11e7-9776-6e4f168da196.png">
<img width="278" alt="screen shot 2017-06-26 at 14 28 13" src="https://user-images.githubusercontent.com/110226/27539754-fe827d68-5a7d-11e7-8edf-a3e534724282.png">
<img width="717" alt="screen shot 2017-06-26 at 14 28 07" src="https://user-images.githubusercontent.com/110226/27539756-fe848aa4-5a7d-11e7-9665-96beb1503c86.png">
<img width="291" alt="screen shot 2017-06-26 at 14 28 02" src="https://user-images.githubusercontent.com/110226/27539751-fe7a4558-5a7d-11e7-83f7-2c9a829136fa.png">
<img width="1259" alt="screen shot 2017-06-26 at 14 27 49" src="https://user-images.githubusercontent.com/110226/27539757-fe961df0-5a7d-11e7-8c77-1376d060071d.png">

**Comment by martini** [comment]
Wonderful @mrflix 

<img width="1264" alt="screen shot 2017-07-28 at 16 56 01" src="https://user-images.githubusercontent.com/110226/28722993-bb47b8b4-73b5-11e7-80ba-81a10a512df4.png">

**Comment by mrflix** [comment]
The activity stream popover stays on the left side

**Comment by martini** [comment]
Here it is! 🎉

<img width="1265" alt="screen shot 2017-07-28 at 20 30 59" src="https://user-images.githubusercontent.com/110226/28731611-e33701bc-73d4-11e7-9ecc-8d984d98d92e.png">

**Comment by mrflix** [comment]
Very nice!

**Comment by DjMagicFingers** [comment]
Email messages send are not RTL:
![email rtl messed up 13-3-2018](https://user-images.githubusercontent.com/32017425/36125953-f6d6b524-105e-11e8-9619-ebe4e93833dd.png)

**Comment by DjMagicFingers** [comment]
text module hidden when using Hebrew profile
![text module hidden when using hebrew profile](https://user-images.githubusercontent.com/32017425/36126049-6f93e716-105f-11e8-9863-8343dff1fab7.png)

**Comment by DjMagicFingers** [comment]
Some Hebrew fonts are still unreadable - sent from android

![some hebrew fonts are still unreadable - sent from android](https://user-images.githubusercontent.com/32017425/36126137-d8876d42-105f-11e8-9932-01e3dfe93d64.png)

**Comment by DjMagicFingers** [comment]
Wrong place of search close button when in Hebrew profile
![wrong place of search close button when in hebrew profile](https://user-images.githubusercontent.com/32017425/36126220-3cd5ab4c-1060-11e8-8316-705b4166314b.png)

**Comment by thorsteneckel** [comment]
@DjMagicFingers - please create a new issue containing all your findings. We will handle it. Replies to closed issues make it hard for us to organize. Thanks!
