### ISSUE TITLE
Feedback Form Channel - Ability to set a target group for incoming tickets

### ISSUE THREAD

**Issue by srast1** [zammad/zammad#1206]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: package
* Operating system: Centos7
* Browser + version: not important

### Expected behavior:
Ability to set the a target Group for incoming tickets created via Feedback Form like already implemented in Web-Channel:

![image](https://user-images.githubusercontent.com/29708212/27542042-50a65b70-5a86-11e7-86a3-e84b273c5c2f.png)

### Actual behavior:
Tickets created using the Feedback Form are being assigned to the default ticket group.
One cannot change the default ticket group for this channel. 

### Steps to reproduce the behavior:
Enable Feedback Form and create a ticket using this feature

![image](https://user-images.githubusercontent.com/29708212/27542180-c347b462-5a86-11e7-8fd9-ca1dbc0cb386.png)

Reason for creating this issue:
On my site the default Group is set up for sys-admins. All other users have their corresponding groups. Tickets created by the Feedback Form would get lost cause I cannot switch the default group. 

Sincerely 
Sebastian

**Comment by martini** [comment]
@srast1 The change was a little bit bigger, so it's it will be part of next Zammad release. Thanks for your issue. 👍

**Comment by srast1** [comment]
You're welcome. Thanks for fixing it! :)
