### ISSUE TITLE
Add recaptcha option to web form channel

### ISSUE THREAD

**Issue by colinwilson** [zammad/zammad#1207]
Question: Is it possible to add recaptcha/captcha as an option to the web form channel?

**Comment by martini** [comment]
Hi @colinwilson 

right now it's not possible. Currently we do some client detection to prevent spam. Anyway, do you find a recaptcha/captcha solution better or would it be good for you if there is a "hidden" functionality to prevent spam?

 -Martin

**Comment by colinwilson** [comment]
If by hidden you're referring to hidden 'honeypot' fields, I think this would be a better option than recaptcha.

Although if could you integrate both hidden and recaptcha into the web form javascript as options for admins to choose from that'd be awesome.

**Comment by martini** [comment]
> Although if could you integrate both hidden and recaptcha into the web form javascript as options for admins to choose from that'd be awesome.

Sounds good. Do you have any experiences with implementing recaptcha?

**Comment by colinwilson** [comment]
A little. I intend to have a look at the script over the coming weekend.

**Comment by martini** [comment]
@colinwilson some hidden bot detection has been added for develop branch. To support recaptcha looks not so easy for me (but I'm really new to it).

If you have ideas or what even to discuss in addition. Just reopen. Thanks!

**Comment by monotek** [comment]
What's the problem using recaptcha?
Isn't it just a piece of JavaScript which needs to be inserted?

**Comment by martini** [comment]
@monotek your need the following:

1) put external javascript dependencies from google into your web page where you want to use the feedback form
2) you need to register at google the get the api key
3) you need to store the api key in Zammad

-=> Basically it sounds feasible but then the form feature is away from just "cut & paste" integration.

From this point a very good hidden integration for bot detection would be better (of cause it's limited).

Another approach would be to implement it optional, als optional feature for the Zammad form. Pull requests are very welcome! 😜
