### ISSUE TITLE
Freeipa+Zammad -> Counting Users Loop

### ISSUE THREAD

**Issue by unclesam87** [zammad/zammad#1209]
### Infos:

* Used Zammad version: 1.5.x (just updated on ubuntu on 27.06.2017)
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Google Chrome

### Expected behavior:
To add all Ldap Users from an freeipa domain

### Actual behavior:
keeps hanging on counting the user
isnt possible to stop that process, every time when i open the ldap settings it jumps to the counting step

* 

### Steps to reproduce the behavior:
Add an Freeipa User like this one:
uid=system3,cn=accounts,cn=users,dc=example,dc=com 
Added that one to zammad
add Groups to zammad, then click next, counting keeps hanging in an loop.

*

**Comment by thorsteneckel** [comment]
Hi @unclesam87 - thanks for reporting this. I created a debug script for that. Could you please do the following:

1.) Create a file called `issue_1209.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via zammad run rails r `issue_1209.rb` or rails r `issue_1209.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `issue_1209.rb` file

```ruby
# stop hanging jobs
ImportJob.where(finished_at: nil).each do |job|
  job.update_attribute(:finished_at, Time.zone.now)
end

# start new counting job
ImportJob.dry_run(
  name:    'Import::Ldap',
  payload: ImportJob.last.payload,
  delay:   false
)

# print result
p ImportJob.last.result
```

**Comment by rkaldung** [comment]
@thorsteneckel We hat this on our test system, should be the objectClass

**Comment by thorsteneckel** [comment]
@rkaldung - thanks for the hint! Our changes should be reflected in the latest version he uses. However there were some changes to the LDAP logic added today. So please update your Zammad again (in about 30 minutes from now) and retry with the script above. Thanks!

**Comment by unclesam87** [comment]
{"skipped"=>164, "created"=>0, "updated"=>0, "unchanged"=>0, "failed"=>0, "deactivated"=>0, "sum"=>164}
that was the only output

**Comment by thorsteneckel** [comment]
Yeah that's strange. I recommend that you reset your LDAP settings via executing `Setting.set('ldap_config', {})` in the [Rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console). 

After that please make sure your Scheduler is running properly. This might be the cause for not making any progress.

Quick question: How many users are in your LDAP matching the User Filter `(objectClass=posixaccount)`?

Feedback would be great.

**Comment by unclesam87** [comment]
@thorsteneckel 
objectclass=posixaccount -> # extended LDIF
#
# LDAPv3
# base <(objectClass=posixaccount)> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# search result
search: 2
result: 32 No such object

# numResponses: 1

i used ur rails command to reset and try to set it up again, wont work again.

Scheduler: i cant find any documentation on it, so i am not quite sure where i can find out if it is running. in the logs of zammad i found a line saying 
"I, [2017-07-10T13:45:41.387095 #6804]  INFO -- : Scheduler running..."

thank you for ur help:)

**Comment by thorsteneckel** [comment]
Hi @unclesam87 - sorry for the delay. Just wanted to hear what the status is right now. Is the LDAP working for you or is the issue still present?

**Comment by unclesam87** [comment]
No change so far... so no sucess... any ideas?

**Comment by thorsteneckel** [comment]
Sorry I lost the overview of the current state. Could you please give me a short introduction on what is currently the issue?

As far as I understand you have configured the LDAP integration via the Admin interface. After that Zammad started to count your Users. This step didn't finish and you can't change anything since if you enter the configuration dialog the pop-over reopens and is stuck.

Your users can be found via the filter `(objectClass=posixaccount)` and are 32 in sum. 

You have reset the Setting via executing `Setting.set('ldap_config', {})` in the [Rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console). 

You restarted your Scheduler via `sudo systemctl restart zammad-worker`.

Right?

**Comment by hanneshal** [comment]
Closed.
Please reopen when this issue still exists in 2.0.

**Comment by thorsteneckel** [comment]
Could you please provide your `log/production.log` file to support@zammad.com and refer to this issue and my name. Thanks!

**Comment by unclesam87** [comment]
@thorsteneckel i sended u that file - thank u for ur help

**Comment by thorsteneckel** [comment]
Hi @unclesam87 - thanks for sending the mail that fast. I already had a first look and found that there are a lot of issues regarding a missing/not running Elasticsearch (ES). This causes a a "jam" of unprocessable background jobs. This leads to the issue that other background jobs (e.g. LDAP jobs) won't run.
Please have a look at the `Monitoring` entry in your admin menu. There should be a list on how many jobs are currently queued. I already saw systems with over 1 mio. backgroud jobs. This leads to a lot of side effects like slow systems, not updating overviews, now email delivery etc.

Please make sure to configure your ES connection correct or disable it. Here is an example error from the log:

```
FAILED (4 prior attempts) with RuntimeError: Unable to process POST request to
elasticsearch URL 'http://127.0.0.1:9200/zammad_production/User/3'.
Elasticsearch is not reachable, probably because it's not running or even installed.

...
```

**Comment by unclesam87** [comment]
Hey, Thorsten,
thx for ur answer.
I will look into it tomorrow:)

have a good day


2018-04-05 17:51 GMT+02:00 Thorsten <notifications@github.com>:

**Comment by unclesam87** [comment]
THANKS! It worked! Now i just have to figure out how to get it assign the right userroles and groups to the counterparts in our system...
