### ISSUE TITLE
It looks like you signed into your account using a new device on ""

### ISSUE THREAD

**Issue by temi007** [zammad/zammad#1212]
on every request to the api I get this message in the subject via eMail. How to get rid of that message?

### Infos:

* Used Zammad version: 1.5.x 
* Used Zammad installation source: (source, package, ...) ubuntu package
* Operating system: Linux amorebio 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* Browser + version: not relevant - api issue

### Expected behavior:
maybe it should take 'api' + [ip-address] as device name andmak an valid record to the device list
* 

### Steps to reproduce the behavior:

* 
run the following script

`
        print_r(zam(array('method'=>'users', 'param'=>2)));
	
	function zam($param, $type='get') {
		
		if (!empty($param['param']))
			$p = '/'.$param['param'];
		else
			$p = '';
			
		$post = ($type == 'post') ? 1 : 0; 
			
		$ch = cURL_init("http://beratung.amorebio.de/api/v1/{$param['method']}$p");
		cURL_setopt($ch, CURLOPT_POST, $post); 
		
		if (!empty($param['payload']))
			cURL_setopt($ch, CURLOPT_POSTFIELDS, json_encode($param['payload']));
		
		cURL_setopt($ch, CURLOPT_HTTPHEADER, Array('Authorization: Token token='.TOKEN, 'Content-Type: application/json')); 
		cURL_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
		cURL_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		$message = curl_exec($ch);
	
		echo cURL_error($ch);
		cURL_close($ch);
	
		return json_decode($message, True);
	}

`

**Comment by martini** [comment]
Hi @temi007 

already fixed today. :-D #1208 

 -Martin
