### ISSUE TITLE
Individual fields also for time accounting

### ISSUE THREAD

**Issue by anicoa** [zammad/zammad#1217]
* Used Zammad version:  1.5.0
* Used Zammad installation source: Ubuntu packages
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Safari 10.1.1.

### Expected behavior:

* Settings -> System -> Objects: creation of individual fields possible for "time accounting"

### Actual behavior:

* Settings -> System -> Objects: "only" possible for ticket, user, organisation, group

Would be great if individual fields get extended to the time accounting records as well. Are there any plans or hints to implement this feature?

**Comment by hanneshal** [comment]
Hi,

there are no plans to do this in the future. We only use the time tracking to track time tasks performed on tickets. Everything else is stored within the ticket or user. 

Could you describe your use case in detail? Maybe I just don't get it ;)

**Comment by anicoa** [comment]
Thanks for the reply. Use cases:
a) support for different hourly rates
b) support for other informations which could be relevant for time accounting

The "individual fields"-feature is really great and it would be very elegant (and consistent) to have it throughout all data models. 

Other solution might be individual fields for articles. I had a quick look in the source code and if I remember right there seems to be a reference in /app/models/object_manager.rb to individual fields for articles. Or did I get it totally wrong :)

**Comment by hanneshal** [comment]
Ok, valid use cases and now I understand where you are headed. Unfortunately we don't have resources for this at the moment. To resolve this, we would like to implement a time tracking addon including and export, reporting and so on, not a single purpose solution. We have a internal time tracking within Zammad, but this is to custom and is not useable for the "outside" world ;) 

Sorry
Johannes

P.S.
If you want to contribute, feel free. We are always happy to get help on this. ❤️
