### ISSUE TITLE
No Zammad after Update to 1.6.1

### ISSUE THREAD

**Issue by ruebenmaster** [zammad/zammad#1218]
Hallo,
today i updated the opensuse 42.2 (zypper up) server with zammad. After update there will be the following message trying to get the zammad website: 502 Bad Gateway.
On the same time i updated our CentOS7 ( yum update ) with zammad. After update there will be the following message trying to get the zammad website: Status Code 500 {"error":"FEHLER:  Spalte »access« existiert nicht\nLINE 1: SELECT \"groups_users\".user_id,group_id,access FROM \"groups_u...\n                                               ^\n"}
What's wrong with version 1.6.1?
Ok, that are VM's and i'm able to roll back with Snapshot.

**Comment by hanneshal** [comment]
Please send you Zammad production.log(s), which can be found in /opt/zammad/log/ to info@zammad.com

Which version of Zammad did you run before the update?

I would assume that there is something wrong with the migrations or the database after the update

**Comment by ruebenmaster** [comment]
Hallo,

will send you the informations on monday, July 3rd.

 

greetings

Stephan

 

 

Gesendet: Freitag, 30. Juni 2017 um 15:11 Uhr
Von: "Johannes Nickel" <notifications@github.com>
An: zammad/zammad <zammad@noreply.github.com>
Cc: ruebenmaster <ruebenmaster@web.de>, Author <author@noreply.github.com>
Betreff: Re: [zammad/zammad] No Zammad after Update to 1.6.1 (#1218)


Please send you Zammad production.log(s), which can be found in /opt/zammad/log/ to info@zammad.com

Which version of Zammad did you run before the update?

I would assume that there is something wrong with the migrations or the database after the update
