### ISSUE TITLE
Elasticsearch configuration fails

### ISSUE THREAD

**Issue by DRSchlaubi** [zammad/zammad#1221]
### Infos:

* Used Zammad version: latest
* Used Zammad installation source: package
* Operating system: CentOS 7
* Browser + version: no browser

### Expected behavior:

When i run zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"
  i will get this error

```
Ignoring bigdecimal-1.3.2 because its extensions a
e not built.  Try: gem pristine bigdecimal --versin 1.3.2
Ignoring executable-hooks-1.3.2 because its extens
ons are not built.  Try: gem pristine executable-h
oks --version 1.3.2
Ignoring ffi-1.9.18 because its extensions are not
built.  Try: gem pristine ffi --version 1.9.18
Ignoring gem-wrappers-1.2.7 because its extensions
are not built.  Try: gem pristine gem-wrappers --v
rsion 1.2.7
Ignoring io-console-0.4.6 because its extensions a
e not built.  Try: gem pristine io-console --versi
n 0.4.6
Ignoring nio4r-2.1.0 because its extensions are no
 built.  Try: gem pristine nio4r --version 2.1.0
Ignoring pg-0.19.0 because its extensions are not
uilt.  Try: gem pristine pg --version 0.19.0
Ignoring psych-2.2.4 because its extensions are no
 built.  Try: gem pristine psych --version 2.2.4
Ignoring websocket-driver-0.6.5 because its extens
ons are not built.  Try: gem pristine websocket-dr
ver --version 0.6.5
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesu
port-4.2.7.1/lib/active_support/dependencies.rb:27
:in `require': incompatible library version - /opt
zammad/vendor/bundle/ruby/2.3.0/gems/pg-0.18.4/lib
pg_ext.so (LoadError)
        from /opt/zammad/vendor/bundle/ruby/2.3.0/
ems/activesupport-4.2.7.1/lib/active_support/depen
encies.rb:274:in `block in require'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/
ems/activesupport-4.2.7.1/lib/active_support/depen
encies.rb:240:in `load_dependency'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/
ems/activesupport-4.2.7.1/lib/active_support/depen
encies.rb:274:in `require'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/
ems/pg-0.18.4/lib/pg.rb:4:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/b
ndler-1.15.1/lib/bundler/runtime.rb:82:in `require
        from /usr/local/rvm/gems/ruby-2.2.4/gems/b
ndler-1.15.1/lib/bundler/runtime.rb:82:in `block (
 levels) in require'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/b
ndler-1.15.1/lib/bundler/runtime.rb:77:in `each'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/b
ndler-1.15.1/lib/bundler/runtime.rb:77:in `block i
 require'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/b
ndler-1.15.1/lib/bundler/runtime.rb:66:in `each'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/b
ndler-1.15.1/lib/bundler/runtime.rb:66:in `require
        from /usr/local/rvm/gems/ruby-2.2.4/gems/b
ndler-1.15.1/lib/bundler.rb:108:in `require'
        from /opt/zammad/config/application.rb:7:i
 `<top (required)>'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/
ems/railties-4.2.7.1/lib/rails/commands/runner.rb:
1:in `require'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/
ems/railties-4.2.7.1/lib/rails/commands/runner.rb:
1:in `<top (required)>'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/
ems/railties-4.2.7.1/lib/rails/commands/commands_t
sks.rb:123:in `require'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/
ems/railties-4.2.7.1/lib/rails/commands/commands_t
sks.rb:123:in `require_command!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/
ems/railties-4.2.7.1/lib/rails/commands/commands_t
sks.rb:90:in `runner'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/
ems/railties-4.2.7.1/lib/rails/commands/commands_t
sks.rb:39:in `run_command!'
        from /opt/zammad/vendor/bundle/ruby/2.3.0/
ems/railties-4.2.7.1/lib/rails/commands.rb:17:in `
top (required)>'
        from /opt/zammad/bin/rails:4:in `require'
        from /opt/zammad/bin/rails:4:in `<main>'
root@levels:/usr/share/elasticsearch
[root@levels easticsearch]#
```

**Comment by rolfschmidt** [comment]
Hi @DRSchlaubi ,
could you please send us your `Gemfile.lock` file?

Best regards,
Rolf

**Comment by DRSchlaubi** [comment]
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.8)
      actionpack (= 4.2.8)
      actionview (= 4.2.8)
      activejob (= 4.2.8)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.8)
      actionview (= 4.2.8)
      activesupport (= 4.2.8)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.8)
      activesupport (= 4.2.8)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (4.2.8)
      activesupport (= 4.2.8)
      globalid (>= 0.3.0)
    activemodel (4.2.8)
      activesupport (= 4.2.8)
      builder (~> 3.1)
    activerecord (4.2.8)
      activemodel (= 4.2.8)
      activesupport (= 4.2.8)
      arel (~> 6.0)
    activerecord-nulldb-adapter (0.3.6)
      activerecord (>= 2.0.0)
    activerecord-session_store (1.0.0)
      actionpack (>= 4.0, < 5.1)
      activerecord (>= 4.0, < 5.1)
      multi_json (~> 1.11, >= 1.11.2)
      rack (>= 1.5.2, < 3)
      railties (>= 4.0, < 5.1)
    activesupport (4.2.8)
      i18n (~> 0.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    arel (6.0.4)
    argon2 (1.1.3)
      ffi (~> 1.9)
      ffi-compiler (~> 0.1)
    ast (2.3.0)
    autoprefixer-rails (6.4.1.1)
      execjs
    biz (1.6.0)
      clavius (~> 1.0)
      tzinfo
    browser (2.2.0)
    buftok (0.2.0)
    builder (3.2.3)
    childprocess (0.5.9)
      ffi (~> 1.0, >= 1.0.11)
    clavius (1.0.2)
    clearbit (0.2.5)
      nestful (~> 1.1.0)
    coderay (1.1.1)
    coffee-rails (4.2.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.2.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    coffeelint (1.14.0)
      coffee-script
      execjs
      json
    composite_primary_keys (8.1.5)
      activerecord (~> 4.2.0)
    concurrent-ruby (1.0.5)
    coveralls (0.8.16)
      json (>= 1.8, < 3)
      simplecov (~> 0.12.0)
      term-ansicolor (~> 1.3.0)
      thor (~> 0.19.1)
      tins (>= 1.6.0, < 2)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    daemons (1.2.4)
    delayed_job (4.1.2)
      activesupport (>= 3.0, < 5.1)
    delayed_job_active_record (4.1.1)
      activerecord (>= 3.0, < 5.1)
      delayed_job (>= 3.0, < 5)
    diff-lcs (1.2.5)
    diffy (3.1.0)
    docile (1.1.5)
    domain_name (0.5.20170404)
      unf (>= 0.0.5, < 1.0.0)
    doorkeeper (4.2.0)
      railties (>= 4.2)
    eco (1.0.0)
      coffee-script
      eco-source
      execjs
    eco-source (1.1.0.rc.1)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    equalizer (0.0.10)
    erubis (2.7.0)
    eventmachine (1.2.3)
    execjs (2.7.0)
    factory_girl (4.8.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.8.0)
      factory_girl (~> 4.8.0)
      railties (>= 3.0.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    faraday-http-cache (1.3.1)
      faraday (~> 0.8)
    ffi (1.9.18)
    ffi-compiler (0.1.3)
      ffi (>= 1.0.0)
      rake
    figaro (1.1.1)
      thor (~> 0.14)
    formatador (0.2.5)
    github_changelog_generator (1.14.1)
      activesupport
      faraday-http-cache
      multi_json
      octokit (~> 4.0)
      rainbow (>= 2.1)
      rake (>= 10.0)
      retriable (~> 2.1)
    globalid (0.4.0)
      activesupport (>= 4.2.0)
    guard (2.14.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-livereload (2.5.2)
      em-websocket (~> 0.5)
      guard (~> 2.8)
      guard-compat (~> 1.0)
      multi_json (~> 1.8)
    guard-symlink (0.1.0)
      guard-compat (~> 1.1)
    hashdiff (0.3.2)
    hashie (3.4.4)
    htmlentities (4.3.4)
    http (1.0.4)
      addressable (~> 2.3)
      http-cookie (~> 1.0)
      http-form_data (~> 1.0.1)
      http_parser.rb (~> 0.6.0)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    http-form_data (1.0.3)
    http_parser.rb (0.6.0)
    i18n (0.8.4)
    icalendar (2.4.1)
    inflection (1.0.0)
    json (1.8.6)
    jwt (1.5.4)
    kgio (2.11.0)
    koala (2.4.0)
      addressable
      faraday
      multi_json (>= 1.3.0)
    libv8 (3.16.14.15)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.10)
    mail (2.6.6)
      mime-types (>= 1.16, < 4)
    memoizable (0.4.2)
      thread_safe (~> 0.3, >= 0.3.1)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_portile2 (2.2.0)
    minitest (5.10.2)
    multi_json (1.12.1)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    mysql2 (0.4.6)
    naught (1.1.0)
    nenv (0.3.0)
    nestful (1.1.1)
    net-ldap (0.15.0)
    netrc (0.11.0)
    nokogiri (1.8.0)
      mini_portile2 (~> 2.2.0)
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    oauth (0.5.1)
    oauth2 (1.2.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    octokit (4.4.1)
      sawyer (~> 0.7.0, >= 0.5.3)
    omniauth (1.3.1)
      hashie (>= 1.2, < 4)
      rack (>= 1.0, < 3)
    omniauth-facebook (4.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-github (1.1.2)
      omniauth (~> 1.0)
      omniauth-oauth2 (~> 1.1)
    omniauth-gitlab (1.0.2)
      omniauth (~> 1.0)
      omniauth-oauth2 (~> 1.0)
    omniauth-google-oauth2 (0.4.1)
      jwt (~> 1.5.2)
      multi_json (~> 1.3)
      omniauth (>= 1.1.1)
      omniauth-oauth2 (>= 1.3.1)
    omniauth-linkedin-oauth2 (0.1.5)
      omniauth (~> 1.0)
      omniauth-oauth2
    omniauth-oauth (1.1.0)
      oauth
      omniauth (~> 1.0)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    omniauth-twitter (1.2.1)
      json (~> 1.3)
      omniauth-oauth (~> 1.1)
    parser (2.3.1.2)
      ast (~> 2.2)
    pg (0.18.4)
    pluginator (1.3.0)
    power_assert (0.3.1)
    powerpack (0.1.1)
    pre-commit (0.28.0)
      pluginator (~> 1.1)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    puma (3.6.0)
    rack (1.6.8)
    rack-livereload (0.3.16)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.8)
      actionmailer (= 4.2.8)
      actionpack (= 4.2.8)
      actionview (= 4.2.8)
      activejob (= 4.2.8)
      activemodel (= 4.2.8)
      activerecord (= 4.2.8)
      activesupport (= 4.2.8)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.8)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.8)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails-observers (0.1.2)
      activemodel (~> 4.0)
    railties (4.2.8)
      actionpack (= 4.2.8)
      activesupport (= 4.2.8)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.1.0)
    raindrops (0.17.0)
    rake (12.0.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    ref (2.0.0)
    rest-client (2.0.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    retriable (2.1.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-rails (3.5.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    rubocop (0.42.0)
      parser (>= 2.3.1.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-progressbar (1.8.1)
    ruby_dep (1.4.0)
    rubyzip (1.2.1)
    safe_yaml (1.0.4)
    sass (3.4.22)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sawyer (0.7.0)
      addressable (>= 2.3.5, < 2.5)
      faraday (~> 0.8, < 0.10)
    scrub_rb (1.0.1)
    selenium-webdriver (2.53.4)
      childprocess (~> 0.5)
      rubyzip (~> 1.0)
      websocket (~> 1.0)
    shellany (0.0.1)
    simple-rss (1.3.1)
    simple_oauth (0.3.1)
    simplecov (0.12.0)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    simplecov-rcov (0.2.3)
      simplecov (>= 0.4.1)
    slack-notifier (1.5.1)
    slop (3.6.0)
    spring (1.7.2)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.11)
    telegramAPI (1.2.2)
      rest-client (~> 2.0, >= 1.7.3)
    term-ansicolor (1.3.2)
      tins (~> 1.0)
    test-unit (3.2.1)
      power_assert
    therubyracer (0.12.2)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.4)
    thread_safe (0.3.6)
    tilt (2.0.5)
    tins (1.13.0)
    twitter (5.17.0)
      addressable (~> 2.3)
      buftok (~> 0.2.0)
      equalizer (= 0.0.10)
      faraday (~> 0.9.0)
      http (~> 1.0)
      http_parser.rb (~> 0.6.0)
      json (~> 1.8)
      memoizable (~> 0.4.0)
      naught (~> 1.0)
      simple_oauth (~> 0.3.0)
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    uglifier (3.0.2)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.4)
    unicode-display_width (1.1.1)
    unicorn (5.2.0)
      kgio (~> 2.6)
      raindrops (~> 0.7)
    valid_email2 (1.2.17)
      activemodel (>= 3.2)
      mail (~> 2.5)
    webmock (2.3.2)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    websocket (1.2.3)
    writeexcel (1.0.5)
    zendesk_api (1.14.0)
      faraday (~> 0.9)
      hashie (>= 1.2, < 4.0, != 3.3.0)
      inflection
      mime-types
      multipart-post (~> 2.0)
      scrub_rb (~> 1.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  activerecord-nulldb-adapter
  activerecord-session_store
  argon2
  autoprefixer-rails
  biz
  browser
  clearbit
  coffee-rails
  coffee-script-source
  coffeelint
  composite_primary_keys
  coveralls
  daemons
  delayed_job_active_record
  diffy
  doorkeeper
  eco
  em-websocket
  eventmachine
  execjs
  factory_girl_rails
  figaro
  github_changelog_generator
  guard
  guard-livereload
  guard-symlink
  htmlentities
  icalendar
  json
  koala
  libv8
  mail
  mime-types
  mysql2
  net-ldap
  oauth2
  omniauth
  omniauth-facebook
  omniauth-github
  omniauth-gitlab
  omniauth-google-oauth2
  omniauth-linkedin-oauth2
  omniauth-oauth2
  omniauth-twitter
  pg
  pre-commit
  puma
  rack-livereload
  rails (= 4.2.8)
  rails-observers
  rb-fsevent
  rspec-rails
  rubocop
  sass-rails
  selenium-webdriver
  simple-rss
  simplecov
  simplecov-rcov
  slack-notifier
  spring
  spring-commands-rspec
  sprockets
  sqlite3
  telegramAPI
  test-unit
  therubyracer
  twitter
  uglifier
  unicorn
  valid_email2
  webmock
  writeexcel
  zendesk_api

RUBY VERSION
   ruby 2.3.1p112

BUNDLED WITH
   1.13.7

**Comment by DRSchlaubi** [comment]
Any Ideas how to fix this?

**Comment by martini** [comment]
Hi @DRSchlaubi 

the strange thing is, that all required gems are coming with the RPM package. And the gems of your error messages sounds not link gems for Zammad. :-o

Any other "zammad run" commands like the following are working?

`zammad run rails r 'p Setting.get("es_url")'`

**Comment by DRSchlaubi** [comment]
Zuerst möchte ich klar stellen dass Jetzt debian acht nutze `zammad run rails r 'p Setting.get("es_url")'`
funktioniert zwar dennoch bekomme ich Warnungen
`root@rs001740:/opt/zammad# zammad run rails r 'p Setting.get("es_url")'
Ignoring argon2-1.1.1 because its extensions are not built.  Try: gem pristine argon2 --version 1.1.1
Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
WARNING: Nokogiri was built against LibXML version 2.9.1, but has dynamically loaded 2.9.4
"http://localhost:9200"
root@rs001740:/opt/zammad#`

**Comment by martini** [comment]
Thanks for feedback. Let's check the elasticsearch functionality first.

Install elasticsearch (see https://docs.zammad.org/en/latest/install-elasticsearch.html)

Is the following now working:

* `zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"`
* `zammad run rake searchindex:rebuild`

**Comment by DRSchlaubi** [comment]
das habe ich bereits getan

**Comment by martini** [comment]
Issue reports are in english (thanks). And what is the result? Is elasticsearch integration now working?

**Comment by DRSchlaubi** [comment]
No. I have still the same error

**Comment by martini** [comment]
So you still have:

```
Ignoring bigdecimal-1.3.2 because its extensions are not built.
Try: gem pristine bigdecimal --versin 1.3.2
Ignoring executable-hooks-1.3.2 because its extensons are not built.
Try: gem pristine executable-hoks --version 1.3.2
[...]
```

**Comment by DRSchlaubi** [comment]
Yes that's right

**Comment by martini** [comment]
Ok. That's really, really strange. Is remote login (ssh) possible?

**Comment by DRSchlaubi** [comment]
Yes how i can contact you

**Comment by martini** [comment]
just send it to support at zammad dot com (I also can send you my ssh public key). Thanks!

**Comment by DRSchlaubi** [comment]
I just sent you the required informations

**Comment by martini** [comment]
Thanks, I was able to login.

One more question. You have the same issue on CentOS and now on Debian, right?

**Comment by DRSchlaubi** [comment]
that's correct

**Comment by hanneshal** [comment]
Your profile is not set correct:
If I run:
```
rvm use ruby-2.3.1
zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"
```

everything works fine. 
So please fix your PATH variable and everything should be fine.

**Comment by DRSchlaubi** [comment]
nope because the debian package do not create the database correctly

**Comment by martini** [comment]
One more note. **You do not need to install a extra ruby via rvm on your Zammad host**. Zammad is shipping a complete ruby environment with all required gems in the rpm/debian package. **You do not need to care about it on upgrading Zammad (just upgrade the Zammad package)**.

**Comment by DRSchlaubi** [comment]
when i run apt upgrade  an error occurs
and i have still the same error

**Comment by martini** [comment]
> when i run apt upgrade an error occurs
> and i have still the same error

Did you uninstall your own installed ruby?

What is the reason why you need it? Any reference to he database issue?

**Comment by DRSchlaubi** [comment]
because i need ruby to run `rake db:migrate`

**Comment by martini** [comment]
> because i need ruby to run `rake db:migrate`

It would be fine to get he issue/error message. Without that we can't help. Normally `zammad run rake db:migrate` need to be executed (which is using the ruby env. of the package).

**Comment by DRSchlaubi** [comment]
now i have uninstalled my own ruby still the same error

**Comment by martini** [comment]
Thanks for uninstalling own ruby. I checked it again. I did the following changes to get elasticsearch up and running:

# 1) Install correct mapper-attachments plugin for elasticsearch (according to elasticsearch version):

root:# /usr/share/elasticsearch/bin/elasticsearch-plugin list
mapper-attachments
WARNING: plugin [mapper-attachments] is incompatible with version [5.5.0]; was designed for version [5.4.3]
root:# /usr/share/elasticsearch/bin/elasticsearch-plugin remove mapper-attachments
-> removing [mapper-attachments]...
root:# /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-attachments
-> Installed mapper-attachments
root:# systemctl start elasticsearch

# 2) Verified if elasticsearch is up and running:
```
root:# netstat -tan|grep 9200
tcp6       0      0 127.0.0.1:9200          :::*                    LISTEN     
tcp6       0      0 ::1:9200                :::*                    LISTEN     
```

# 3) Configured correct elasticsearch endpoint (see netstat):
```
root:# zammad run rails r "Setting.set('es_url', 'http://127.0.0.1:9200')"
```

# 4) Reindexed whole objects

```
root:# zammad run rake searchindex:rebuild
drop indexes...
create indexes...
reload data...
 reload Ticket
  - started at 2017-07-11 17:58:34 UTC
  - took 1 seconds
 reload User
  - started at 2017-07-11 17:58:35 UTC
  - took 0 seconds
 reload Organization
  - started at 2017-07-11 17:58:36 UTC
  - took 0 seconds
```

Now you should be able to find your ticket via search. Feedback would be fine!

**Comment by DRSchlaubi** [comment]
Thank you very much




http://derschlaubi.xyz | http://drschlaubi.de







On Tue, Jul 11, 2017 at 8:04 PM +0200, "Martin Edenhofer" <notifications@github.com> wrote:












Thanks for uninstalling own ruby. I checked it again. I did the following changes to get elasticsearch up and running:
1) Install correct mapper-attachments plugin for elasticsearch (according to elasticsearch version):


root:# /usr/share/elasticsearch/bin/elasticsearch-plugin list

mapper-attachments

WARNING: plugin [mapper-attachments] is incompatible with version [5.5.0]; was designed for version [5.4.3]

root:# /usr/share/elasticsearch/bin/elasticsearch-plugin remove mapper-attachments

-> removing [mapper-attachments]...

root:# /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-attachments

-> Installed mapper-attachments

root:# systemctl start elasticsearch
2) Verified if elasticsearch is up and running:
root:# netstat -tan|grep 9200
tcp6       0      0 127.0.0.1:9200          :::*                    LISTEN     
tcp6       0      0 ::1:9200                :::*                    LISTEN     

3) Configured correct elasticsearch endpoint (see netstat):
root:# zammad run rails r "Setting.set('es_url', 'http://127.0.0.1:9200')"

4) Reindexed whole objects
root:# zammad run rake searchindex:rebuild
drop indexes...
create indexes...
reload data...
 reload Ticket
  - started at 2017-07-11 17:58:34 UTC
  - took 1 seconds
 reload User
  - started at 2017-07-11 17:58:35 UTC
  - took 0 seconds
 reload Organization
  - started at 2017-07-11 17:58:36 UTC
  - took 0 seconds



Now you should be able to find your ticket via search. Feedback would be fine!

**Comment by martini** [comment]
You are welcome.
