### ISSUE TITLE
I have made some small changes inside login page, but its not reflecting how can i remove the cache ?

### ISSUE THREAD

**Issue by jsahani** [zammad/zammad#1222]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source : (source, package, ...)
* Operating system: CentOS 7.3
* Browser + version:

**Comment by martini** [comment]
Sorry, this is an issue tracker. Pls try https://zammad.org/participate -> "Do you have questions about the source code?" or order support from Zammad (https://zammad.com/pricing#selfhosted).

Thanks a lot.

 -Martin
