### ISSUE TITLE
Reminder Notification send altough ticket is closed after owner change

### ISSUE THREAD

**Issue by HolgerHeckeroth** [zammad/zammad#1223]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: (source, package, ...) DEB Ubuntu 
* Operating system: Ubuntu 16.04
* Browser + version: Chrome 59

### Expected behavior:

* Closed tickets don't send previously selected reminder

### Actual behavior:

* Ticket sent reminder although it was closed

### Steps to reproduce the behavior:

* Owner A sets reminder
* Owner ist changed to Owner B
* Owner B closes Ticket
* Owner A gets previously set reminder

**Comment by rolfschmidt** [comment]
Hi @HolgerHeckeroth ,
i tried to reproduce it but for me it was not possible. Maybe it is a kind of raise condition.

Could you please provide some more information about the timing of the reproduced steps?

Did you import data from your otrs system? Maybe you could send us your ticket state list?
```
ubuntu-rs@ubuntu-rs:/workspace/git_zammad/zammad$ rails c
2.3.1 :001 > Ticket::State.all
```

Best regards,
Rolf

**Comment by HolgerHeckeroth** [comment]
Hi Rolf,

unfortunately I couldn't reproduce it either. We didn't import data from another system.
Here is the ticket state list you asked for.

`pp Ticket::State.all
[#<Ticket::State:0x00565396e57e60
  id: 2,
  state_type_id: 2,
  name: "open",
  next_state_id: nil,
  ignore_escalation: false,
  default_create: false,
  default_follow_up: true,
  note: nil,
  active: true,
  updated_by_id: 1,
  created_by_id: 1,
  created_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00,
  updated_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00>,
 #<Ticket::State:0x00565396e57a00
  id: 1,
  state_type_id: 1,
  name: "new",
  next_state_id: nil,
  ignore_escalation: false,
  default_create: true,
  default_follow_up: false,
  note: nil,
  active: true,
  updated_by_id: 1,
  created_by_id: 1,
  created_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00,
  updated_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00>,
 #<Ticket::State:0x00565396e57708
  id: 3,
  state_type_id: 3,
  name: "pending reminder",
  next_state_id: nil,
  ignore_escalation: true,
  default_create: false,
  default_follow_up: false,
  note: nil,
  active: true,
  updated_by_id: 1,
  created_by_id: 1,
  created_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00,
  updated_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00>,
 #<Ticket::State:0x00565396e57348
  id: 4,
  state_type_id: 5,
  name: "closed",
  next_state_id: nil,
  ignore_escalation: true,
  default_create: false,
  default_follow_up: false,
  note: nil,
  active: true,
  updated_by_id: 1,
  created_by_id: 1,
  created_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00,
  updated_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00>,
 #<Ticket::State:0x00565396e56ec0
  id: 5,
  state_type_id: 6,
  name: "merged",
  next_state_id: nil,
  ignore_escalation: true,
  default_create: false,
  default_follow_up: false,
  note: nil,
  active: true,
  updated_by_id: 1,
  created_by_id: 1,
  created_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00,
  updated_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00>,
 #<Ticket::State:0x00565396e56ad8
  id: 6,
  state_type_id: 7,
  name: "removed",
  next_state_id: nil,
  ignore_escalation: true,
  default_create: false,
  default_follow_up: false,
  note: nil,
  active: false,
  updated_by_id: 1,
  created_by_id: 1,
  created_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00,
  updated_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00>,
 #<Ticket::State:0x00565396e56790
  id: 7,
  state_type_id: 4,
  name: "pending close",
  next_state_id: 4,
  ignore_escalation: true,
  default_create: false,
  default_follow_up: false,
  note: nil,
  active: true,
  updated_by_id: 1,
  created_by_id: 1,
  created_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00,
  updated_at: Fri, 23 Jun 2017 13:05:21 UTC +00:00>]
=> #<ActiveRecord::Relation [#<Ticket::State id: 2, state_type_id: 2, name: "open", next_state_id: nil, ignore_escalation: false, default_create: false, default_follow_up: true, note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-06-23 13:05:21", updated_at: "2017-06-23 13:05:21">, #<Ticket::State id: 1, state_type_id: 1, name: "new", next_state_id: nil, ignore_escalation: false, default_create: true, default_follow_up: false, note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-06-23 13:05:21", updated_at: "2017-06-23 13:05:21">, #<Ticket::State id: 3, state_type_id: 3, name: "pending reminder", next_state_id: nil, ignore_escalation: true, default_create: false, default_follow_up: false, note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-06-23 13:05:21", updated_at: "2017-06-23 13:05:21">, #<Ticket::State id: 4, state_type_id: 5, name: "closed", next_state_id: nil, ignore_escalation: true, default_create: false, default_follow_up: false, note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-06-23 13:05:21", updated_at: "2017-06-23 13:05:21">, #<Ticket::State id: 5, state_type_id: 6, name: "merged", next_state_id: nil, ignore_escalation: true, default_create: false, default_follow_up: false, note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-06-23 13:05:21", updated_at: "2017-06-23 13:05:21">, #<Ticket::State id: 6, state_type_id: 7, name: "removed", next_state_id: nil, ignore_escalation: true, default_create: false, default_follow_up: false, note: nil, active: false, updated_by_id: 1, created_by_id: 1, created_at: "2017-06-23 13:05:21", updated_at: "2017-06-23 13:05:21">, #<Ticket::State id: 7, state_type_id: 4, name: "pending close", next_state_id: 4, ignore_escalation: true, default_create: false, default_follow_up: false, note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-06-23 13:05:21", updated_at: "2017-06-23 13:05:21">]>`

**Comment by rolfschmidt** [comment]
Hi @HolgerHeckeroth ,
i'm sorry but i have absolutely no clue how to reproduce it then. If you find any way to reproduce it then i would be glad if you could reopen this issue with more information. Thank you very much for your report and support! 👍 

Best regards,
Rolf

**Comment by HolgerHeckeroth** [comment]
Dear Rolf,

sorry tobring up the topic again. But now we have a specific ticket where this happened again.
There was no owner change in the ticket. But the ticket had a reminder set that wasn't reached before closure of the ticket. Even tough the ticket was closed the reminder was send out today to my colleague.
Are there any dumps or logs I could provide to you, if you want to investigate on this further?

Best,
Holger

**Comment by HolgerHeckeroth** [comment]
Hi Rolf,

I want to give you an update on this issue.
It is completely our fault. A colleague of mine was occasionaly running a virtual clone of our production system which wasn't up to date for testing purposes. He had the network connection of the virtual machine open, so it was sending out reminders for tickets which where already closed in the production system.
I'm very sorry to have stolen your time with this.

Best
Holger

**Comment by rolfschmidt** [comment]
np
