### ISSUE TITLE
Can't answer/update created ticket from non-admin user through PHP API

### ISSUE THREAD

**Issue by ihnatov** [zammad/zammad#1226]
Hello, first of all I have to say that Zammad is a great support system but I have issues at the moment which won't allow me to finish my project successfully. I'm creating a WordPress plugin to connect a self-hosted Zammad installation with a Wordpress based site. I can't update the ticket that has been created within the same user. At the console I see an authorization error.

I have already checked issue [#1190](https://github.com/zammad/zammad/issues/1190) but I haven't found a solution there. This is a critical issue which I have to solve else I have to switch my support backend. 

Here's my code:

**I create an user with an e-mail and a password that I take from the WordPress DB:**
`curl_setopt_array($curl, array(
    CURLOPT_URL => "https://app.getsite.eu/api/v1/users",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_POSTFIELDS =>
        "{\r\n\"firstname\": \"$user->user_firstname\",\r\n\"lastname\": \"$user->user_lastname\",\r\n\"email\" : \"$user->user_email\",\"roles\":[\"Customer\"],\r\n\"password\": \"qwerty12345\"}",
    CURLOPT_HTTPHEADER => $curl_httpheader
));
`

At this stage everything is ok. The user has been successfully added to the Zammad dashboard with the correct credentials.

**My next step is to get all tickets**
`
CURLOPT_URL => "https://app.getsite.eu/api/v1/tickets/",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "authorization: Basic  ".base64_encode("$user:$pass")."",
    "cache-control: no-cache",
    "content-type: application/json",
    "postman-token: 558e257c-18f3-ef25-891e-31e9993593cc"
  ),
));`

$user:$pass - user's login and password which gets created in Zammad. I specify the admin and get all tickets instead of the tickets of the specified user. I only need the tickets for current user. This leads to an authorization error on  the next step.

I get a ticket by ID through the PUT request. I want to add an additional message from the current user to this ticket. When I make such a request, I get an authorization error. If this request is made from the administrator's login and password, there is no error, but I need to do this from current user with his login and password.

`
curl_setopt_array($curl, array(
  CURLOPT_URL => "https://app.getsite.eu/api/v1/tickets/1",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "PUT",
  CURLOPT_POSTFIELDS => "{  \r\n \r\n \"state\": \"open\",\r\n \"priority\": \"3 high\",\r\n \"article\": {\r\n   \"subject\": \"some subject of update\",\r\n   \"body\": \"some message of update\"\r\n }\r\n\r\n \t\r\n }\r\n ",
  CURLOPT_HTTPHEADER => array(
    "authorization: Basic YWxlbmE4OTFhbGVuYUBnbWFpbC5jb206MzM1NDY0MjIw",
    "cache-control: no-cache",
    "content-type: application/json",
    "postman-token: d4ba6fd1-31a5-fd3a-f3a2-a7e58490be8a"
  ),
));`

I would appreciate any constructive comments. If you need any more information, don't hesitate to ask.

**Comment by thorsteneckel** [comment]
Hi @ihnatov - what's the result when performing the search request with the created user?

**Comment by ihnatov** [comment]
Hi @thorsteneckel, thank you for your reply.

So, **request for the created user**:
`curl_setopt_array($curl, array(
  CURLOPT_URL => "https://app.getsite.eu/api/v1/users/23",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "authorization: Basic YWxlbmE4OTFhbGVuYUBnbWFpbC5jb206MzM1NDY0MjIw",
    "cache-control: no-cache",
    "content-type: application/json"
  ),
));`

**The answer**
`{
    "id": 23,
    "organization_id": null,
    "login": "brock@gmail.comm",
    "firstname": "Dmitryo",
    "lastname": "Danylov",
    "email": "brock@gmail.comm",
    "image": null,
    "image_source": null,
    "web": "",
    "phone": "",
    "fax": "",
    "mobile": "",
    "department": "",
    "street": "",
    "zip": "",
    "city": "",
    "country": "",
    "address": "",
    "vip": false,
    "verified": false,
    "active": true,
    "note": "",
    "last_login": "2017-06-19T11:09:26.868Z",
    "source": null,
    "login_failed": 0,
    "preferences": {
        "tickets_open": 1,
        "tickets_closed": 0
    },
    "updated_by_id": 3,
    "created_by_id": 3,
    "created_at": "2017-06-19T10:43:30.786Z",
    "updated_at": "2017-06-19T11:09:26.871Z",
    "group_ids": [],
    "role_ids": [
        3
    ],
    "organization_ids": [],
    "authorization_ids": []
}`

**The search request with the created user for his tickets**:
`curl_setopt_array($curl, array(
  CURLOPT_URL => "https://app.getsite.eu/api/v1/tickets/1",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_POSTFIELDS => "{\n\t\n\t\n\t\n}",
  CURLOPT_HTTPHEADER => array(
    "authorization: Basic b2xnYTEyb2xnYUBnbWFpbC5jb206cXdlcnR5MTIzNDU=",
    "cache-control: no-cache",
    "content-type: application/json"
  ),
));`

**The answer**:
`{
    "error": "authentication failed"
}`

**Comment by thorsteneckel** [comment]
Seems something on the request is wrong.

Before each Ticket controller action the authentication takes place:
https://github.com/zammad/zammad/blob/350c3ead51872cb619f67b33f764da52c94b15a1/app/controllers/tickets_controller.rb#L7

Which fails on the following line in your case:
https://github.com/zammad/zammad/blob/5eb49443dd87458c5b2b324cec7744c19e07f456/app/controllers/application_controller/authenticates.rb#L39

But shouldn't because you are sending the BasicAuth headers which are handled here:
https://github.com/zammad/zammad/blob/5eb49443dd87458c5b2b324cec7744c19e07f456/app/controllers/application_controller/authenticates.rb#L69

Maybe you can add some debug statements like `Rails.logger.error "Debug - #{username}"` or something to that line and see if your credentials get handled or not. Please remind to restart your Rails application server.

Are there any insights why this is happening in the `log/production.log` file?

**Comment by ihnatov** [comment]
Thank you @thorsteneckel, I'm currently checking my code again with your hints. I'll update you by my issue asap. If a solution will be found I'll post it here.

**Comment by thorsteneckel** [comment]
Closing now. Feedback is appreciated.

**Comment by ihnatov** [comment]
Sorry @thorsteneckel for delayed response. After I have added debug I received a new error.

Before - { "error": "authentication failed" }
Now - { "error": "Not authorized" }

The log/production.log is attached.

**Comment by ihnatov** [comment]
[production.zip](https://github.com/zammad/zammad/files/1124659/production.zip)

**Comment by thorsteneckel** [comment]
Sorry but I have no idea what your debug code is doing 😁 Where did you put your code and what have you added?

**Comment by ihnatov** [comment]
Rails.logger.error "Debug - #{username}" to https://github.com/zammad/zammad/blob/5eb49443dd87458c5b2b324cec7744c19e07f456/app/controllers/application_controller/authenticates.rb#L69

**Comment by thorsteneckel** [comment]
Please add `Rails.logger.error "Debug - #{username}" - #{password} - #{user}` **after** the line `user = User.authenticate(username, password)` and verify the result. Please do not post the output here 🤓 just verify it.

**Comment by ihnatov** [comment]
Thank you @thorsteneckel . I added this line. The result the same:
{
    "error": "Not authorized"
}

Log file - https://www.dropbox.com/s/0u52brbhmfqhszg/production3.log?dl=0

**Comment by ihnatov** [comment]
Ok, thank you @thorsteneckel all is working great now!

Creating the user from admin:
`curl -u admin_email@mail.com:admin_pass -H "Content-Type: application/json" -X POST -d '{"firstname":"John","lastname":"Doe","email":"customer_email@mail.com","roles":["Customer"],"password":"123456"}' /api/v1/users`

Creating the user's ticket:
`curl -u customer_email@mail.com:customer_pass -H "Content-Type: application/json" -X POST -d '{"article":{"subject":"My Ticket","body":"TEST","type":"note","internal":false},  "customer":"customer_email@mail.com","note": "some note", "group": "Some group", "title":"Help me!"}' /api/v1/tickets/`

Adding the comment to the created ticket:
`curl -u customer_email@mail.com:customer_pass -H "Content-Type: application/json" -X PUT -d '{"article":{"subject":"My Ticket","body":"TEST","type":"note","internal":false},"customer":"customer_email@mail.com","note": "some note"}' "/api/v1/tickets/{ticket_id}"`

View all user's tickets:
`curl -u customer_email@mail.com:customer_pass -H "Content-Type: application/json" -X GET -d '{"customer":"customer_email@mail.com"}' "/api/v1/tickets"`

**Issue has been solved!**
