### ISSUE TITLE
Error Chat - Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by nicolasdezena** [zammad/zammad#1228]
### Infos:

* Used Zammad version:  1.5.x
* Used Zammad installation source: (source, package, ...)  Package
* Operating system:  CentOS 7
* Browser + version:  Chrome + 59.0.3071.115 

### Expected behavior:

* Error in chat 
VM167:35 WebSocket connection to 'ws://suporte.whentoday.com.br/ws' failed: Connection closed before receiving a handshake response

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by martini** [comment]
Hi @nicolasdezena 

it's a config issue. Your browser want's to connect to web socket server, but connection was not possible.

Please check if Zammad web socket server is listening (in detail nginx is working as proxy here) on ws://suporte.whentoday.com.br/ws

If you fixed this issue the chat will work fine.

 -Martin

**Comment by nicolasdezena** [comment]
@martini 
I have no idea how to do this, I will search here. thank you

**Comment by martini** [comment]
@nicolasdezena check the following:

1) check if web socket server process is running
2) check if web socket server is reachable (per default on localhost port 6042) - telnet localhost 6042
3) check if nginx is configured correctly to work as reverse proxy for /ws to localhost:6042

Good luck.
