### ISSUE TITLE
add customized Buttons

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1232]
Hi hi 😄 

long time no see ^^

is there a way, to add a customized button at the sidebar of a ticket?
Right here: 
![screenshot_8](https://user-images.githubusercontent.com/4436931/27868374-d0835790-619c-11e7-8eff-eb3159930dc3.jpg)
I know you can have custome objects for tickets, but with them you are limited to "boolean", "date", "datetime", "selection", "text" and "integer".
What I want to have, is a customized function on this button. Sadly since there isn't a stopwatch in zammad for timetracking at the moment, I need to come up with an alternative.
The idea is, to have REST API export to our timetracking system kimai.
The plan is, I start working on a ticket in zammad, this ticket is matched to a customer, hast a ticket-nr. and some other attributes. And now I want to push my extra button, which creates an REST API request of all this attributes and pass them to our kimai.

I hope I could verbalize my thoughts right, because they are still muddled up right now 😉 
Greetings

**Comment by hanneshal** [comment]
This would be possible through custom development and modifying the templates. So basically yes.
What we don't have right now is a custom element which can handle such events. I think a simple button would not be enough. I guess you need to send something to authenticate against the API along your request, also a payload would be needed. 

The templates are stored in the app folder, just search for *.eco files

regards
