### ISSUE TITLE
LDAP-Sync seems to consider only email part before the '@' for matching

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#1233]
Hi @thorsteneckel 

two users in Zammad before syncing LDAP the first time:

User 1: max.meier@emaildomain.de
User 2: max.meier@otherdomain.de

User 2 has a higher ID as he was added later.

The LDAP dataset contains user 1 with its email address. When doing the LDAP sync, Zammad replaces User 2 with the complete data of User 1, although these are completely different users.

It seems that the LDAP sync only takes the part before the '@' of the email address into account for finding existing users which are matching.

(Referring to our discussion in the Helpdesk)

**Comment by jacotec** [comment]
Hi @thorsteneckel 

just send a reminder via Helpdesk as our conversation is more up-to-date there ... is there any status update?

**Comment by thorsteneckel** [comment]
Hi @jacotec - Is this issue still open? If so: Can you provide an anonymized screenshot of both LDAP entries so I can have a look at the complete list of attributes? Thanks!

**Comment by jacotec** [comment]
Hi @thorsteneckel 
Nope, that was solved.
