### ISSUE TITLE
LDAP imported administrators has a blank view..

### ISSUE THREAD

**Issue by madd86** [zammad/zammad#1234]
So, I imported my users from LDAP, and the result is okay for agents.

However, for admins this is what they see when they login:

![j3uhpu](https://user-images.githubusercontent.com/23120598/27881419-ed6bfc48-619e-11e7-87a8-27c2e020e954.jpg)

There's no dashboard or anything..

**Comment by thorsteneckel** [comment]
Hi @madd86 - I guess you have assigned only the Admin role? Please try adding the Agent role to the LDAP group mapping, too:

<img width="639" alt="bildschirmfoto 2017-07-06 um 11 25 08" src="https://user-images.githubusercontent.com/3873515/27906176-c9c1efba-6242-11e7-9617-eb0eb6df256d.png">
