### ISSUE TITLE
Make missing-attachment-warning configurable (enable/disable)

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#1236]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: dpkg
* Operating system: Ubuntu 16.02

### Actual behavior:

If you mention the word attachment in a message body the system reminds you to not forget to actually attach something. This is in general a cool feature.

### The Problem (In german only):

The german translation for "attachment" is "anlage" and zammad, thanks to its powerful translation system, has also the "missing-attachment-warning" for all translations of "attachment" (and some variations of the word). 

In german "anlage" can also mean "system" or "machine". So if you are selling/supporting any kind of system or machine like we do you get an attachment warning in almost every article you write. 

### Expected behavior:

It would be nice if a user cloud decide in his profile (or the admin in the global settings) if he wants the "missing-attachment-warning" or not.

### Workaround?

Is there a workaround to disable the feature somehow? Delete the translation?

**Comment by rolfschmidt** [comment]
Hi @hiaz ,
i understand your problem. I'm german too and i think it's just the wrong word for attachment. It should be "Anhang" and then there should not be no issues anymore related in industry usage.

We try to keep zammad simple and i just want to prevent overloading it with options. I hope this solution is ok for you.

You can update the translations in your admin interface -> "Übersetzungen" -> "Letzte Übersetzungen laden".

Best regards,
Rolf

**Comment by hiaz** [comment]
Hi @rolfschmidt,

thank you for your fast response. I agree. You are right, the best solution is to use "Anhang" as translation.

But I am not 100% sure about the rest of your response ;).

I understood that you changed the translation "globally" and I have just to press "Get latest translations". Tried it. Did not work. Still matching "Anlage". 

Regards,
Mathias

**Comment by rolfschmidt** [comment]
Hi @hiaz ,
did you maybe change translations manually in your system? If you have local changes then you maybe need to change the word manually.

how many buttons do you see on top of the list in the translation overview?

Rolf

**Comment by martini** [comment]
Hi @hiaz 

please verify if the change translation arrived on your Zammad by:

1) Switch UI to german (of not already)
2) Go to Admin
3) Got to Translations
4) Search for single word "Attachment"
 -=> What is your german translation now? Should be now "Anhang"

Greetings,

 -Martin

**Comment by hiaz** [comment]
Hi @martini 

checked as you described. Is translated correctly. 

Now it also works. Maybe my first test had a cashing problem? 

Thank you all for your help!
Mathias

**Comment by martini** [comment]
@hiaz Thanks for fast feedback. 

I think you updated the translation (all was fine in the database) but your web app hasn't refreshed the translations on your browser/web app. -> The missing-attachment-warning is a browser/web app feature. 

So you updated the translations, switched back to your ticket tab and the missing-attachment-check was still performed with the old translation (after reloading the web app all was fine - like it now is).

Greetings!

 -Martin (I'm a Lower Bavarian 😁)

PS: We want to integrate mobydick in Zammad! 🤠

**Comment by hiaz** [comment]
@martini 

> Martin (I'm a Lower Bavarian 😁)

I know ;)

> PS: We want to integrate mobydick in Zammad! 

I (and our customers) also love to see mobydick and Zammad integrated. 

I am just the "Mädchen für alles" with only basic programming knowledge and currently waiting for one of our "real programmers" to start with the integration in one of our next sprints.

I'll send you my contact data to enjoy@zammad.com.

Habedere,
Mathias
