### ISSUE TITLE
Unable to add Linked Gitlab account

### ISSUE THREAD

**Issue by shantanuthatte** [zammad/zammad#1240]
### Infos:

* Used Zammad version: 1.5.0-1499590174.1dd40c5.centos7
* Used Zammad installation source: (source, package, ...) RPM
* Operating system: Centos 7
* Browser + version: Chrome 59.0.3071.115

### Expected behavior:

* Able to link GitLab account

### Actual behavior:

* 404 Page: "404: Requested Ressource was not found."

### Steps to reproduce the behavior:

* Login to your account
* Setup 'Authentication via GitLab'. Callback url set to `https://<scrubbed>/auth/gitlab/callback`
* Goto Profile > Linked Accounts
* Click 'Add' next to GitLab
* Click 'Authorize' on Gitlab
* You should see a 404 error

### Logs:

Browser URL: `https://<scrubed>/auth/failure?message=invalid_credentials&origin=https%3A%2F%2F<scrubed>%2F&strategy=gitlab`

production.log:

```
I, [2017-07-10T02:14:58.529030 #16236]  INFO -- : client(5619075877) new client connection
I, [2017-07-10T02:14:58.530400 #16236]  INFO -- : Completed 200 OK in 6ms (Views: 0.1ms | ActiveRecord: 1.1ms)
I, [2017-07-10T02:15:00.800160 #16236]  INFO -- : Started GET "/auth/gitlab/callback?code=[FILTERED]&state=<scrubbed>" for 141.101.105.64 at 2017-07-10 02:15:00 -0500
I, [2017-07-10T02:15:06.412705 #16236]  INFO -- : Started GET "/auth/failure?message=invalid_credentials&origin=https%3A%2F%2F<scrubbed>%2F&strategy=gitlab" for <scrubbed> at 2017-07-10 02:15:06 -0500
I, [2017-07-10T02:15:06.420111 #16236]  INFO -- : Processing by ErrorsController#routing as HTML
I, [2017-07-10T02:15:06.420527 #16236]  INFO -- :   Parameters: {"message"=>"invalid_credentials", "origin"=>"https://<scrubbed>/", "strategy"=>"gitlab", "a"=>"auth/failure"}
E, [2017-07-10T02:15:06.432595 #16236] ERROR -- : No route matches [GET] /auth/failure (ActionController::RoutingError)
```

**Comment by hanneshal** [comment]
Hi,

which version of gitlab do you use?
Does the regular Zammad login using gitlab work for you?

**Comment by shantanuthatte** [comment]
I'm using GitLab CE 9.3.5

I cannot login using GitLab on the account as it is not linked. When I do try to login using Gitlab (by clicking the orange icon on the login screen), GitLab asks me to authorize it and land at the same 404 Zammad page.

**Comment by martini** [comment]
After some research we found out that gitlab has changed the api/oauth scope:

https://gitlab.com/gitlab-org/gitlab-ce/issues/33022

Anyway we got it working again (fix is already in stable too - just upgrade via RPM, check you gtilab app settings too - also the callback url and try it again).

**Comment by hanneshal** [comment]
Documentation is also updated: please also check your config --> https://docs.zammad.org/en/latest/sociallogins-gitlab.html

**Comment by shantanuthatte** [comment]
Wow, that was quick. Thanks a lot guys. I'll update and report back tomorrow.
