### ISSUE TITLE
Filter REST API Request

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1241]
Hi 😄 ,

is there the possible to "filter" REST-API requests?
For example, I search for a ticket with
```
curl -H "Authorization: Token token=hwZSvIkum1xZaSo5KQ5XWnIFkGV1ikxygRdCSCmeEhEe6M2NHZJ_QMkapGnbriiZ" -H "Content-Type: application/json" 'https://itszammad.xxxx.xxxxx/api/v1/tickets/search?query=id:47'
```
and I only want some information like group_id, user_id, number etc.

Greetings

**Comment by hanneshal** [comment]
Hi,

there is no such option. The api always delivers everything which is related to the call.

regards
