### ISSUE TITLE
The download of inline images return not the original image, only the downscaled

### ISSUE THREAD

**Issue by lasat** [zammad/zammad#1243]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: source
* Operating system: DockerImages

### Expected behavior:

If I download a inlined image I expect that the original/unscaled image is returned

### Actual behavior:

Only the (down-)scaled image could be downloaded.

### Steps to reproduce the behavior:

1. Create a screenshot
2. Copy & Paste this screenshot to an article.
3. save the article
4. try to read something on this screenshot
5. download the image
6. try to read something on the download

**Comment by martini** [comment]
Hi @lasat 

if you use copy & paste for inline images, only a certain size of images will be sent inline (which make sense for inline images is used). In some cases also the browser api is downscaling the image (in this case we can't do anything). If you want to send a high resolution image which is untouched, you need to add it as attachment (by drag & drop or traditional file upload).

 -Martin

**Comment by hanneshal** [comment]
see #1246 for a follow up bug
