### ISSUE TITLE
{"error":"undefined method `each' for nil:NilClass"}

### ISSUE THREAD

**Issue by DRSchlaubi** [zammad/zammad#1245]
After an Upgrade to the newest Zammad (Build #2991) i will geht this error After Login 

{"error":"undefined method `each' for nil:NilClass"}

**Comment by martini** [comment]
Hi @DRSchlaubi 

I can't see build #2991 (highest is #2199).

Anyway, did you stop all Zammad processes and then update Zammad? Or did you upgrade with running Zammad processes?

In case, stop all Zammad processes, execute `zammad run rails r 'Cache.clear'` and start the Zammad processes again. Is it working now?

 -Martin

**Comment by DRSchlaubi** [comment]
Thanks that fixed my Problem

**Comment by martini** [comment]
Thanks for feedback!
