### ISSUE TITLE
550 5.7.1 Client does not have permissions to send as this sender 

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1247]
### Infos:

* Used Zammad version: zammad_1.5.0-1499590174.1dd40c5.xenial_amd64
* Used Zammad installation source: `deb https://deb.packager.io/gh/zammad/zammad xenial stable`
* Operating system: Ubuntu 16.04.2 LTS
* Browser + version: Firefox 54

`# dpkg -l | grep zammad`
<pre>
ii  zammad                               1.5.0-1499180355.a85c1f0.xenial            amd64        Zammad is a web based open source helpdesk/customer support system
</pre>

### Expected behavior:

* Being able to add a SMTP email account which sends emails under its own name

### Actual behavior:

* When adding a SMTP email account under `/#channels/email` I get:
<pre>
550 5.7.1 Client does not have permissions to send as this sender 
</pre>

### Steps to reproduce the behavior:

Try to add a SMTP email account under `/#channels/email`, where the email account must for security reasons only be able to sends under its own name (this is the `From:` field that a receiver would see).

I think Zammad tries to send under a different `From:` field, as the email name/account settings would allow it.

(In `Icinga2` I use `ssmtp` and had the same issue and there in `/etc/ssmtp/revaliases` was able to set an allowed `From:` field:
<pre>
# cat /etc/ssmtp/revaliases 
# sSMTP aliases
# 
# Format:	local_account:outgoing_address:mailhub
#
# Example: root:your_login@your.domain:mailhub.your.domain[:port]
# where [:port] is an optional port number that defaults to 25.
root=icinga2@domain.com:mail.domain2.com:XXX
</pre>
where XXX is the port)

**Comment by hanneshal** [comment]
Does you "from" email address in the group config match the one you configured within the smtp config?

**Comment by passboltUser** [comment]
Where can I find the group config? If it's under `/#manage/groups` I don't see anything in here.

**Comment by hanneshal** [comment]
Just click on the group name and you should see something like this.

![pricingtool_helpdesk_-_groups](https://user-images.githubusercontent.com/804939/28115413-297862f6-6705-11e7-8338-f3a2552507f4.png)

The email which is selected there should match the smtp config.

**Comment by passboltUser** [comment]
Unfortunately I don't see any emails in "EMAIL" under the "Users" group. Then I created another group called "zammad", but still no email:
![a](https://user-images.githubusercontent.com/29798595/28116052-a4d66a22-6707-11e7-9d29-8e94ee2c5314.png)

**Comment by hanneshal** [comment]
Ok. Then please add an email account: https://docs.zammad.org/en/latest/channel-mail.html
You cant have an sender without the corresponding receiver.

**Comment by martini** [comment]
@passboltUser I guess you try to configure the SMTP account for email notifications (not for a channel). What did you set for your Zammad as fqdn (at install wizard or via Admin -> Setting -> System -> Fully Qualified Domain Name)?

As second you need to check send sender of your notification emails -> Admin -> Channel -> Email -> Setting -> Notification Sender. It seems that your mail relay is not accepting emails from this sender.

**Comment by passboltUser** [comment]
I just wanted to write that this is where I have had my initial problem. But by kind of an accident I found how so fix it: I went again to `/#channels/email` and there under the `Settings` tab I changed from `Notification Master <was_it_ticket?@#{config.fqdn}>` to `Notification Master <zammad@domain.com>` and I then was able to add a SMTP email account under the `Accounts` tab now because `zammad@` matches with the `zammad@` SMTP username email.

**Comment by martini** [comment]
@passboltUser Thanks for feedback!
