### ISSUE TITLE
Email subject in autoreply on new ticket

### ISSUE THREAD

**Issue by PatrickGoenner** [zammad/zammad#1252]
Hi, I'm missing the possibility to insert the email subject from the customers first email in autoreply on new ticket.

**Comment by martini** [comment]
Hi @PatrickGoenner 

how about "#{ticket.title}"? The ticket title is filled with the subject of the first email.

Greetings,

 -Martin

**Comment by PatrickGoenner** [comment]
Hi Martin,
I'm sorry, my fault. I need the content, not the subject :)
Regards
Patrick

**Comment by martini** [comment]
Np. Is "#{article.body}" working?

**Comment by PatrickGoenner** [comment]
This is working.
Thanks a lot.
