### ISSUE TITLE
Duplicates in Caller Log (Sipgate)

### ISSUE THREAD

**Issue by Hirbod** [zammad/zammad#1253]
### Infos:

* Used Zammad version: 1.5.x 
* Used Zammad installation source: Debian Package
* Operating system: Debian Jessie
* Browser + version: OSX 10.12.5, Chrome, Firefox

### Expected behavior:

* No duplicate "name guesses" from name Person

### Actual behavior:

* Duplicate name guesses

### Steps to reproduce the behavior:

* Just opening caller log 

As you can see in my screenshot, some calls have up to 10 name guesses. So far ok, but it should not be the same 10 times. Please try to strip out duplicates

<img width="1110" alt="log" src="https://user-images.githubusercontent.com/504909/28211619-ef5c4aca-689d-11e7-98b3-c72bf6a1eef4.png">

**Comment by hanneshal** [comment]
Hi,

when you move with the cursor over the names shown in the list, do you get a different result for every entry? 
The only way I could reproduce this, was when I had multiple customer entries using the same phone number. 
Another question: 
When you search for Lorenz XXX in your Zammad, does Zammad return multiple entries or just one?

regards
Johannes

**Comment by Hirbod** [comment]
Hi @hanneshal,

when I hover over the names, I get always the same entry. When I search for Lorenz, I only receive one Lorenz, nothing duplicate there.

**Comment by martini** [comment]
@Hirbod Thanks for reporting. It's fixed now. Just update your Debian package and it will work for new caller log entries.
