### ISSUE TITLE
Feature Request: clear caller log

### ISSUE THREAD

**Issue by Hirbod** [zammad/zammad#1254]
Currently, it is just possible to trigger a checkbox inside the caller-log. I would love to clear the list, I don't really need to store that stuff forever. Could you consider this?

**Comment by martini** [comment]
Hi @Hirbod 

that's a good idea! We already have this kind of cleanup jobs for other parts in Zammad. So the Zammad way would be a background job, which is cleaning the caller log - lets say once a month.

Any feedback is welcome!

 -Martin

**Comment by Hirbod** [comment]
Yeah, this would be fine though!

**Comment by martini** [comment]
Update: It's implemented for upcoming release and already in develop branch.
