### ISSUE TITLE
Problem to Install Zammad in Debian 9

### ISSUE THREAD

**Issue by Bjoern3003** [zammad/zammad#1256]
Is there a known Problem to install zammad in Debian 9?

I will get a error like this, if I try to set "apt-get install zammad"

> [...]
> 
> (Re)creating init scripts
> Nothing to do.
> Nothing to do.
> Nothing to do.
> Enabling Zammad on boot
> Stopping Zammad
> database.yml found. Updating db...
> `/home/zammad` is not a directory.
> Bundler will use `/tmp/bundler/home/root' as your home directory temporarily.
> bundler: failed to load command: rake (/opt/zammad/vendor/bundle/ruby/2.3.0/bin/rake)
> LoadError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory - /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/x86_64-linux/digest/sha1.so
>   /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>   /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>   /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/source/git.rb:4:in `<top (required)>'
>   /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>   /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>   /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/lockfile_parser.rb:122:in `<class:LockfileParser>'
>   /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/lockfile_parser.rb:14:in `<module:Bundler>'
>   /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/lockfile_parser.rb:13:in `<top (required)>'
>   /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>   /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>   /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/definition.rb:2:in `<top (required)>'
>   /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>   /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>   /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler.rb:129:in `definition'
>   /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler.rb:95:in `setup'
>   /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/setup.rb:10:in `<top (required)>'
>   /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>   /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> /opt/zammad/vendor/ruby-2.3.1/lib/ruby/2.3.0/digest.rb:16:in `const_missing': library not found for class Digest::MD5 -- digest/md5 (LoadError)
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/source/rubygems/remote.rb:26:in `cache_slug'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/fetcher/compact_index.rb:107:in `cache_path'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/fetcher/compact_index.rb:83:in `compact_index_client'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:630:in `warn_on_outdated_bundler'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:15:in `ensure in start'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:16:in `start'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
>         from /opt/zammad/bin/bundle:3:in `load'
>         from /opt/zammad/bin/bundle:3:in `<main>'
> Starting Zammad
> Creating webserver bootstart
> Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install enable nginx
> Restarting webserver nginx
> [...]

### Infos:

* Used Zammad version: 1 .5 / 1.6.1 dev
* Used Zammad installation source: package
* Operating system: Debian 9

**Comment by hanneshal** [comment]
There is no known issue. 
I tried it on a fresh digitalocean instance and got a missing dependency warning. 

@monotek any idea on this?
```
root@debian-2gb-fra1-01:~# apt-get install zammad
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 zammad : Depends: libreadline6 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by hanneshal** [comment]
@Bjoern3003 do you already have a version of ruby / rails installed on this system?

**Comment by Bjoern3003** [comment]
Sure, version 2.3.3 of ruby is installed. I allready have tested to reinstall it.

**Comment by srast1** [comment]
I had the same issue last week on a test-install. 
It seems that "libreadline6" is no longer Part of Debian9. "libreadline5" and "libreadline7" are available though. 

For further reference:
Debian9 current stable https://packages.debian.org/stable/allpackages 
Debian8 oldstable https://packages.debian.org/oldstable/allpackages

Workaround: Use Debian8 oldstable
Regards, 
Sebastian

**Comment by hanneshal** [comment]
@Bjoern3003 We often have issues with misconfigured system environments. If the ENV vars are not set correct and the bundle install is ok, then the installation tries to use your ruby/rails. I guess this is the error here. 

So Zammad comes with it's own ruby / rails package. Which is ready to use. If it's not needed please uninstall your ruby.
See: https://github.com/zammad/zammad/issues/1221 for hints on this. 

But as @srast1 suggests, it's not running at all due a missing dependency. You need to fix this also, until we find a stable solution for Debian 9.

@srast1 Thanks for the feedback. We look into this.

**Comment by Bjoern3003** [comment]
@srast1 libreadline6 is installed with deb 8 packages. This was an older issue, that I have fixed myself.
@hanneshal I did not have installed an own ruby / rails package. apt-get purge rails ruby coult not find an installed package.

**Comment by Bjoern3003** [comment]
Now I have tried to install ruby 2.3.1 manually. After that I have tried to load rake from zammad and the following issue is comming:

tried to: rake --trace in /opt/zammad/vendor/bundle/ruby/2.3.0/bin

(in /opt/zammad)
rake aborted!
LoadError: cannot load such file -- bundler/setup
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/zammad/config/boot.rb:3:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/zammad/config/application.rb:1:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/zammad/Rakefile:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.3.1@global/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.3.1/bin/rake:23:in `load'
/usr/local/rvm/rubies/ruby-2.3.1/bin/rake:23:in `<main>'

I this this could be a problem for my issue?!

**Comment by Bjoern3003** [comment]
I have solved the probelm by myself with installing zammad from source. There was no problem.
