### ISSUE TITLE
Autostart for Zammad at server restart

### ISSUE THREAD

**Issue by Bjoern3003** [zammad/zammad#1257]
I have installed Zammad by Source on Debian 9.

It is running fine, if I start rails after restart on console.

>cd /opt/zammad
>export RAILS_ENV=production
>rails s -p 3000

Is there an easy way for autostartup? I could not find any script on the docs.

**Comment by NeverMin** [comment]
Hi @Bjoern3003 see this:
https://github.com/zammad/zammad/blob/develop/contrib/systemd/zammad.service

**Comment by Bjoern3003** [comment]
I did not really know, what I have to do with this file.

**Comment by babakkazemi** [comment]
@Bjoern3003 You need to enable that service in systemd:
https://wiki.debian.org/systemd

means:
copy that file to /etc/systemd/system
execute `systemctl enable zammad`

**Comment by Bjoern3003** [comment]
Did you have tried it by yourself?

I think there are Errors in the file, for example the Username: https://github.com/zammad/zammad/blob/develop/contrib/systemd/zammad.service#L8

or the bash call. IMHO, it must be called like this ExecStart=/bin/bashbash [...]

**Comment by babakkazemi** [comment]
@Bjoern3003 no sorry, haven't tried it as I use the debian package from packager.io (quite comfy...)

**Comment by Bjoern3003** [comment]
Could you please paste your /etc/systemd/system/zammad.service file? Thanks

**Comment by babakkazemi** [comment]
@Bjoern3003 This won't help too much, as the package installation has a lot more services defined in systemd
`[Unit]
StopWhenUnneeded=true

[Service]
# this service is just a placeholder
ExecStart=/bin/sleep infinity

[Install]
WantedBy=multi-user.target
`

**Comment by Bjoern3003** [comment]
Why is your file only a placeholder file? How did you enable your zammad service?

**Comment by babakkazemi** [comment]
@Bjoern3003 I am not using the source installation, I use the apt source from packager.io, so this does all automagically. Sure, I am on jessie, not stretch...

**Comment by Bjoern3003** [comment]
And I also think, that there is an issue in the proconfigured service file: https://github.com/zammad/zammad/blob/develop/contrib/systemd/zammad.service

;-)

**Comment by Bjoern3003** [comment]
Solved for me at the Moment. After a few hours of debugging, i switched to Debian 8 and everthing workes fine.
