### ISSUE TITLE
objects for tickets should be dependent on group

### ISSUE THREAD

**Issue by gwingend** [zammad/zammad#1262]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: 
* 1076910

### Expected behavior:

It would be useful, if the additional objects you could create for tickets, would be dependent on the different groups in the system.
So in example, if you have an object "asset number" this field should only be visible, when you create a ticket for group "hardware support". If you create a ticket for the group "user management" the object "personal id number" should be available, but not the "asset number" object.

If the objects would be group dependent it would be possible to implement workflows with checkboxes for the agents that could be marked if the individuell task to close a specific ticket have been done.

### Actual behavior:

A created object is visible independent of the selected group the ticket is created for.

**Comment by babakkazemi** [comment]
+1

**Comment by sebmuc99** [comment]
+1

**Comment by Dakror** [comment]
+1 This would be very helpful. Any news?

**Comment by thorsteneckel** [comment]
Locking conversation. There is no new input. +1 and requesting comments create noise and distraction. We are working hard on the next upcoming/most requested features and projects of our support customers. If you want to state your interest in the feature and give valuable input please give the initial post a 👍 reaction and we are able to evaluate it. We will lock all distracting issues from now on. Thanks for your understanding.

**Comment by MrGeneration** [comment]
Just a side note from my end: When we're able to display objects based on their group, we should also be able to display objects based on another objects value.

Kinda the same :)
See: https://community.zammad.org/t/objects-visibility-based-on-other-objects-state/1048

**Comment by rolfschmidt** [comment]
Will be fixed with core workflows:
https://github.com/zammad/zammad/issues/3709
