### ISSUE TITLE
Merge ticket overlay / GUI is a bit hard to use

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#1266]
### Infos:

* Used Zammad version: 1.6.1
* Used Zammad installation source: packager.io deb package develop
* Operating system: debian jessie
* Browser + version: different

### Expected behavior:

* clarity in "merge ticket" GUI

### Actual behavior:

* 
![image](https://user-images.githubusercontent.com/23480845/28272402-ac533944-6b0b-11e7-8de0-e8a3ff6c2d7c.png)
Colums are not wide enough to be able to see enough information - a wider area for that overlay window would be perfect
Also a full text search inside the "merge ticket" view would help a lot to be able to work faster

**Comment by mrflix** [comment]
Servus Babak! I hob a moi des merge fensterl' a wengl broader g'macht. Schau a moi obs da des huift.

----

English: Hi Babak! I made the merge modal wider. Check if it helps.
