### ISSUE TITLE
Change Login of user after a wrong email

### ISSUE THREAD

**Issue by Wisou** [zammad/zammad#1268]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: (source, package, ...)
* Operating system: Debian
* Browser + version: Firefox

Hi,

Can you give me the console command for change login for a user ?
User.find(*).update.... or other
I changed the wrong mail but the login has not changed.

Thx

François

**Comment by rolfschmidt** [comment]
Hi @Wisou ,
with this command you can change the user login of the user with the email address **nicole.braun@zammad.org** to the user login **nicole.braun@zammad.org**.

```
User.find_by(email: 'nicole.braun@zammad.org').update_attribute(:login, 'nicole.braun@zammad.org')
```

Feel free to reopen this issue if you have any issues ;-)

Best regards,
Rolf

**Comment by Wisou** [comment]
Thx a lot Rolf ;-)

Br

François
