### ISSUE TITLE
Zammad high memory consumption

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1271]
### Infos:

* Used Zammad version: 
```
# apt policy zammad
zammad:
  Installed: 1.5.0-1500378755.2c8ae4a.xenial
  Candidate: 1.5.0-1500378755.2c8ae4a.xenial
  Version table:
 *** 1.5.0-1500378755.2c8ae4a.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
        100 /var/lib/dpkg/status
     1.5.0-1500040613.9ed0c8c.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
     1.5.0-1500040386.85db9d9.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
     1.5.0-1499940232.a7032c4.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
     1.5.0-1499859107.4e92a51.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
     1.5.0-1499590174.1dd40c5.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
     1.5.0-1499180355.a85c1f0.xenial 500
        500 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
     1.5.0-1498736327.571fbd8.xenial 500
```
* Operating system: Ubuntu 16.04.2 LTS
* Browser + version: Firefox 54

### Expected behavior:

Not so high memory consumption.

### Actual behavior:
High memory consumption:

```
# top -U zammad
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                               
 6155 zammad    20   0  788380 141536  15900 S  0.0 13.9   0:05.86 ruby                                                                                                  
 6161 zammad    20   0  315584 135708  15756 S  0.0 13.4   0:03.56 ruby                                                                                                  
 6173 zammad    20   0  852904 132632  15484 S  0.0 13.1   0:03.83 ruby                                                                                                  
```
```
# for i in `ps -eaf | grep zammad | grep -v grep | awk '{print $2}'`; do  echo -n "PID $i actual memory  usage is :"; pmap -d $i | grep -i "writeable/private: "; done
PID 6155 actual memory  usage is :mapped: 720792K    writeable/private: 155796K    shared: 28K
PID 6161 actual memory  usage is :mapped: 315588K    writeable/private: 127212K    shared: 28K
PID 6173 actual memory  usage is :mapped: 852908K    writeable/private: 151404K    shared: 28K

```
### Steps to reproduce the behavior:

* Install Zammad and use it. Create a few tickets, that's it. Nothing too much.

I'm wondering if this high memory consumption is normal?

**Comment by hanneshal** [comment]
can you provide some more details:
- Ticket count overall
- # users
- # groups
- does this occur every time / right after start or does it take some time?
- do you have active integrations (LDAP)?

Right now I would think this is normal, because the rails application is hold completely in memory to reduce load times.

regards 
Johannes

**Comment by passboltUser** [comment]
Since we installed Zammad freshly, the ticket count is below 10.
There are also only a few users.
I created one "zammad" group for testing, but didn't use it.
This occurs every time:
`# systemctl stop zammad`
```
# free -h
              total        used        free      shared  buff/cache   available
Mem:           990M        334M        417M         34M        239M        458M
Swap:            0B          0B          0B
```
`# systemctl start zammad`
and after a few seconds it's back to:
```
# free -h
              total        used        free      shared  buff/cache   available
Mem:           990M        671M         86M         34M        233M        121M
Swap:            0B          0B          0B
```

It doesn't surprise me that rails tries to load the DB into RAM, only that it takes so much space even though it's a fresh install of Zammad. Not sure what's going on. Does it load the whole DB, not only its own `zammad` DB's contents?:
```
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| ***            |
| ***             |
| ***         |
| information_schema |
| mysql              |
| ***           |
| performance_schema |
| ***         |
| zammad             |
+--------------------+
```

**Comment by thorsteneckel** [comment]
Hi @passboltUser - this it normal and expected behaviour. Please read the requirements and documentation first: https://docs.zammad.org/en/latest/prerequisites-hardware.html

**Comment by passboltUser** [comment]
Yes, I thought so. Except I still don't know what exactly is loaded into RAM, which of the Databases from the `show databases;`, only `zammad`, or others? 

From the docs:
`* 2 CPU`
Do you mean 2 CPUs or 2 cores? 

Also you write `2 CPU` and then `4 CPUs` (with a 's'). That's not consistent. I know, this 's'-thing is a minor issue but still.

**Comment by hanneshal** [comment]
As usual when running rails apps, the app and needed dependencies are loaded into the ram to start fast and deliver fast response times. We do not load all of the database into the ram. But the database will do some caching for itself. So it's not only zammad which uses your ram. The caching logic tries to store the most needed objects and relations. What is exactly cached is decided by the app, based upon the needs/usage. 

By CPUs we mean, minimum 2 Cores. But this is the bare minimum! 

> Also you write 2 CPU and then 4 CPUs (with a 's'). That's not consistent. I know, this 's'-thing is a minor issue but still.

Please open up an issue in the documentation repo, I'll take care of this.

**Comment by passboltUser** [comment]
Thanks. Ok, with 2GB RAM now, in case someone is interested:
```
# free -h
              total        used        free      shared  buff/cache   available
Mem:           2.0G        528M        1.1G         20M        327M        1.3G
Swap:            0B          0B          0B
```
Created docs issue.
