### ISSUE TITLE
Wrong time displayed in trigger (autoreply)

### ISSUE THREAD

**Issue by PatrickGoenner** [zammad/zammad#1272]
Hi,

using #{ticket.created_at} in a trigger displays the wrong time. Displayed time is 2 hours befor realtime. Servertime ist correct, in calendar I'm using Europe/Berlin (GMT+2). Where is the connection between created_at and time, where can I configure it?

Best regards
Patrick

**Comment by hanneshal** [comment]
Hi @PatrickGoenner and thanks for the suggestion. Actually Zammad stores all date values in UTC, this is why you get the "wrong" time. At the moment we have no link between the group + calendar and the used timestamps in the trigger.

We should implement that, based upon the timezone set in the calendar. Do you agree or should we set a specific timezone for every group ?

**Comment by PatrickGoenner** [comment]
I agree. Implementing that, based upon the timezone set in the calendar ist a good idea.

**Comment by thorsteneckel** [comment]
Although this issue was first there are more information and a wider discussion over at #1589 so I'm closing this one in favor of the other. Feel free to provide some additional information if needed.
