### ISSUE TITLE
Hide my own signature in ticket view

### ISSUE THREAD

**Issue by Bjoern3003** [zammad/zammad#1274]
It could be more readable to hide my own signature in ticket answers.

**Comment by hanneshal** [comment]
Can you please describe this a bit more. Our fortune-teller service is on maintenance 🔮 
You want to remove|hide this signature when you write a reply to a given ticket, right?

![zammad_signature](https://user-images.githubusercontent.com/804939/28405717-eef4a476-6d2d-11e7-8e16-96ff59ceb528.png)

I don't think we will change this behaviour, many users of Zammad change the signature "on the fly" when they reply. Also we like so see the "final" mail before sending the reply. 

But maybe I missed something, then feel free to reopen.

regards
Johannes

**Comment by Bjoern3003** [comment]
Hi, in the form field should it be placed. This is okay for me.

But in the ticket view (after sending your Message to customer, you have to see your complete submit, including your signature. This could be more readable, if there is the signature hidden. Is this better to understand? :-)

**Comment by martini** [comment]
Hi @Bjoern3003 

for me it looks like your proposal is already working. I just replied to an message:

<img width="687" alt="screen shot 2017-07-20 at 11 03 40" src="https://user-images.githubusercontent.com/110226/28409541-3a17f77a-6d3b-11e7-887d-4d878d0e5b14.png">

My own signature is not show. I need to click on see more.

<img width="662" alt="screen shot 2017-07-20 at 11 03 44" src="https://user-images.githubusercontent.com/110226/28409568-4b50c4e0-6d3b-11e7-998b-6b429ca4ebd6.png">

That is what you are looking for?

 -Martin

**Comment by martini** [comment]
JFI: Also work with none quoted text:

<img width="621" alt="screen shot 2017-07-20 at 11 06 00" src="https://user-images.githubusercontent.com/110226/28409638-78ad4d6e-6d3b-11e7-8121-9031d724eedb.png">

<img width="649" alt="screen shot 2017-07-20 at 11 06 06" src="https://user-images.githubusercontent.com/110226/28409637-7887afaa-6d3b-11e7-9cf1-0447ccb9f3e3.png">
