### ISSUE TITLE
How do you Pipe Exchange emails to Zammad?

### ISSUE THREAD

**Issue by nittanygeek** [zammad/zammad#1277]
Has anyone gotten this to work yet with Exchange email?  I see there's a pull request (https://github.com/zammad/zammad/pull/999) to integrate SMTP along with some documentation on using Fetchmail to pipe the emails (https://docs.zammad.org/en/latest/channel-fetchmail.html), but I'm not really experienced enough with Fetchmail to do this with an Exchange server.  Any documentation we can use to set this up with Zammad?

**Comment by martini** [comment]
Hi @bchynds 

why not simply using IMAP + SMTP?

 -Martin

**Comment by bchynds** [comment]
We're limited to MAPI/RPC.

**Comment by martini** [comment]
> We're limited to MAPI/RPC.

I understand. 🙈

What exchange version do you use? Is EWS API possible?

**Comment by bchynds** [comment]
I'm actually not sure.  I know we use OWA for non-outlook tasks, but I'd have to look further into if EWS is available or if it's allowed.  What options do I have if it's not?

**Comment by bchynds** [comment]
Yes, it's available.  I can access https://<mail.server>/ews/exchange.asmx

**Comment by martini** [comment]
Basically we have to options:

1) For inbound: Deliver mails with Exchange SMTP Forward to Zammad Server (e. g. via postfix and procmail which is actually calling "| rails r 'Channel::Driver::MailStdin.new'"). And for outbound also postfix -> Exchange SMTP.

 -=> It's really technical. Complex to maintain administration. But would work today.

2) We just got in touch with EWS for new contact sync feature. 

 -=> So far as I have seen you also can read/send mail via EWS. I'll check this tomorrow. This way would be much easier to maintain for administration.

**Comment by bchynds** [comment]
Awesome!  I'm open to the postfix/procmail setup if it's not too complex.  Otherwise, keep me posted on EWS.  Thank you! :)

**Comment by martini** [comment]
> Awesome! I'm open to the postfix/procmail setup if it's not too complex. Otherwise, keep me posted on EWS. Thank you! :)

Keep on rocking! 🕺🏻

**Comment by ocerecedo** [comment]
I use DavMail and i can connect zammad with ews but the new mail not save in database

**Comment by MrGeneration** [comment]
How to throw mails against Stdin of Zammad is documented here:
https://admin-docs.zammad.org/en/latest/channels/email/advanced/fetchmail.html

We also come with a fetchmail and procmail example. 
I believe this should help anyone having the same need and will close this issue.
