### ISSUE TITLE
Open ticket by fowarding

### ISSUE THREAD

**Issue by juliocjulio** [zammad/zammad#1278]
### Infos:

* Used Zammad version: 1.6.x (master)
* Used Zammad installation source: (source, package, ...): Commit #633c99bb
* Operating system: Ubuntu

Hello Zammad Team! 
We have many cases where our salespeople or even individual support operators receive e-mails and want to foward them to the entire support team.
Is there any way Zammad can recognize the original sender and open the ticket in his name regardless of who fowarded it to our inbound mail?

**Comment by martini** [comment]
Hi @juliocjulio 

in this cases there are two common ways to get this emails into Zammad with original senders.

1) If your mail client is supporting "bounce" or "redirect" (e. g. Apple Mail is supporting it) the original sender is still there.

<img width="310" alt="screen shot 2017-07-20 at 21 31 47" src="https://user-images.githubusercontent.com/110226/28435388-fb2aa032-6d92-11e7-9502-10c71d2c989b.png">

2) Share a certain IMAP folder (which Zammad is polling) with the sales guys. Then they just need to drag&drop the mail into this folder (the sender is still there) and a short time later it will appear in Zammad (like the customer sent it directly).

If you still have questions, let me know.

PS: This is a issue tracker, so the place for questions around Zammad would be here https://zammad.org/participate -> https://groups.google.com/forum/?fromgroups#!forum/zammad-users - Thanks!

 -Martin
