### ISSUE TITLE
LDAP Sync stopped working 

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#1279]
Im using the latest dev version 1.6.

I noticed that the sync has stopped working. There should be a check if the sync has stopped working. 

28.06.2017 11:32 - Counting entries. This may take a while.

I have no idea how to fix that.

**Comment by hanneshal** [comment]
First a note: please use the stable version in production only.

Have you already tried to restart the Zammad services?

**Comment by Julian0o** [comment]
Its no production version so dev version is ok :) 

Restarted everythink already.

**Comment by hanneshal** [comment]
Did you also disabled and re enable LDAP integration again?
What did you already do (might speed this up a bit)?
Can you provide the zammad log /opt/zammad/log/ for scheduler and zammad itself around the time you stop and start the import. 

Can you provide the output of: 

```
zammad run rails c
ImportJob.last
```

regards
Johannes

**Comment by Julian0o** [comment]
Does not work...

`=> #<ImportJob id: 1633, name: "Import::Ldap", dry_run: false, payload: {}, result: {}, started_at: "2017-06-28 09:32:46", finished_at: nil, created_at: "2017-06-28 09:32:46", updated_at: "2017-06-28 09:32:46">`

**Comment by hanneshal** [comment]
this helps. I just wanted to see what the output is.
```
zammad run rails c
ImportJob.last.destroy
job = ImportJob.create(name: 'Import::Ldap', payload: Setting.get('ldap_config'))
job.delay.start
```

If this should happen again, please send us the whole log/ (zipped) directory as mail.

**Comment by Julian0o** [comment]
Its doing something :) Looks like its working now

**Comment by hanneshal** [comment]
Great. I close this issue. If you experience another problem just reopen this issue.

**Comment by stevenmirabito** [comment]
I seem to have run into this issue as well on a fresh install of the stable branch [via Docker](https://github.com/ComputerScienceHouse/zammad-docker). The LDAP setup wizard hangs on "Counting entries" as described, even though if you look at the `import_jobs` table the job has completed. The API calls are returning as if no progress has been made and don't include the results of the job.

In addition, if I bypass the wizard and save the LDAP config, attempting to sync is met with `info: Sync cancelled. LDAP integration deactivated. Activate via the switch.` even though the switch is on and the database shows the integration is activated.

**Comment by stevenmirabito** [comment]
Update: able to reproduce locally with my images, but not with the official images. Unfortunately, the official images won't work under Kubernetes/OpenShift. Time to debug!

**Comment by MuadDib01** [comment]
We have encountered the same issue on version 1.5.x DEB package.

**Comment by thorsteneckel** [comment]
@MuadDib01 - please provide further information. What is happening exactly? Is your Zammad the latest 1.5.x version? What prints the code posted by @hanneshal above?
