### ISSUE TITLE
Invalidate cache when switching users

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#1280]
### Infos:

* Used Zammad version: latest
* Used Zammad installation source: (source, package, ...) package
* Operating system: macOS

If you log out and switch from agent to customer the UI relies on an old cache object and shows the possibility to add a new customer. This is related to a caching issue and just an UI problem. If you refresh the page, everything is fine. 
A customer is not able to create add customers (an error is shown). So no security issue here.

**Comment by martini** [comment]
Kudos to @rolfschmidt
