### ISSUE TITLE
no printout/export of one or several tickets possible

### ISSUE THREAD

**Issue by thomas-vahrson** [zammad/zammad#1283]
### Infos:

* Used Zammad version: V.15
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: 

### Expected behavior:

* We are using zammad as a web-based hardware repair ticket system for customers to see the actually status of the repair. The customers are exprecting a print function with the text/history and attachments (if attachment are a picture) 

they are also asking me all the time for export function in xls or srv 

### Actual behavior:

* no export as csv or Excel of one or serveral tickets possible
* no printout as a pdf for example
 

### Steps to reproduce the behavior:

*

**Comment by gwingend** [comment]
I would like to see that function too.

**Comment by hanneshal** [comment]
Hi,

what I can say is, we are not working on a printout / pdf export at the moment. Also it is not on the agenda right now. If you need this feature (and the others you posted) lets talk  about sponsored development to speed this up. Contact info@zammad.com using a reference to this issue and we may find a solution. 

I got a question for the export: 
It is possible to export a list of tickets using the admin interface, but I guess your customers would like to have an export for each ticket. I'm curious how this export would / should look like in Excel. 

Regards

**Comment by babakkazemi** [comment]
@hanneshal isn't this part of the reporting module that is featured in source install?
@thomas-vahrson maybe the api can help - I am fiddling around with an api connect to our ERP system's database to "inject" tickets into our time accounting, and to read user objects into zammad

**Comment by hanneshal** [comment]
@babakkazemi No it isn't. You can just export tickets from a shown list as Excel. But it's not a full take, just some relevant ticket values are exported. No article information.

**Comment by MamoulianDelacroix** [comment]
This would be a very nice and helpful feature!
@hanneshal 
Where can I find this point in zammad? I'm useing version 2.0 right now.

**Comment by donbertl** [comment]
I second this function too.

Regards

**Comment by SysErr23** [comment]
We need this feature too. Either the possibility to print a ticket on request or to automatically send a PDF to the admin, containing all data from the ticket including mails etc, as soon as the ticket is closed.

**Comment by MrGeneration** [comment]
Zammad does have print css since 2.7 - you should be able to print / save as PDF without any trouble.
This works for tickets without any trouble - does this cover this issue completely ?`

In my opinion it does, I'll close this by now, feel free to reply if you think that this is wrong. :-)

**Comment by thomas-vahrson** [comment]
can you tell me where I can find this new function that is included since 2.7?
I don't think that this cover the request from us and from all other guys

**Comment by thomas-vahrson** [comment]
> 
> 
> Zammad does have print css since 2.7 - you should be able to print / save as PDF without any trouble.
> This works for tickets without any trouble - does this cover this issue completely ?`
> 
> In my opinion it does, I'll close this by now, feel free to reply if you think that this is wrong. :-)

can you tell me where I can find this new function that is included since 2.7?
I don't think that this cover the request from us and from all other guys

**Comment by MrGeneration** [comment]
Sorry, I lost track of this.
If you print out the ticket (e.g. print preview via CTRL+P) you can see how the ticket would look like.

The original post requested a print function (which is covered by the print-css we integrated with Zamamd 2.7). Exporting tickets is possible via console or API if needed (needs custom fiddling from the one that wants to use it, but it is possible already).
