### ISSUE TITLE
no different webforms /attributes depends of the user or group possible

### ISSUE THREAD

**Issue by thomas-vahrson** [zammad/zammad#1284]
### Infos:

* Used Zammad version:  V1.5
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: 

### Expected behavior:

*  we would like to have an dynamic form /atributes in the form depends on the user and/or depends of the assigned groups to the user. 

* the problem is that we have many different customers with different requierements. Like we need different picklists depends of the group /organisation  

### Actual behavior:

* we are using the zammad system as a web based hardware repair ticket system. The problem is that different customers needs a different form to fill out the customized attributes

* actually the form for the ticket in the zammad system are allways static

### Steps to reproduce the behavior:

*

**Comment by hanneshal** [comment]
Duplicate on https://github.com/zammad/zammad/issues/1262
