### ISSUE TITLE
#<RuntimeError: #<SocketError: Failed to open TCP connection to www.google.com:80 (getaddrinfo: Temporary failure in name resolution)>>

### ISSUE THREAD

**Issue by Modius22** [zammad/zammad#1286]
Hi,

I have the following Error in the Calendar Settings:
`#<RuntimeError: #<SocketError: Failed to open TCP connection to www.google.com:80 (getaddrinfo: Temporary failure in name resolution)>>`

### Infos:

* Used Zammad version:1.5.x
* Used Zammad installation source: Package
* Operating system: Ubunt 16.04.2
* Browser + version: Google Chrome: Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by monotek** [comment]
Seems it's a DNS error.

**Comment by hanneshal** [comment]
Or your Zammad ist not allowed to connect to the outside world. 
I just tried it on both master and stable, no issue.

**Comment by uli-heller** [comment]
I do have the same issue. I'm trying to run zammad on a server without outgoing connections to the internet. Only incoming connections and certain well defined outgoing connections are allowed. In fact, I'd like to:

* Use outgoing connections only for emails
* Don't use any connection to google

Is this a valid setup? Do I get rid off the error message when I provide a local holiday feed within the calendar?
