### ISSUE TITLE
Pull latest translations from i18n.zammad.com

### ISSUE THREAD

**Issue by edneymatias** [zammad/zammad#1287]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: Debian package
* Operating system: Debian 8
* Browser + version: Chrome  59.0.3071.115

### Expected behavior:

* When downloading latest translations, Zammad would pull strings that I have sent to i18n.zammad.com.

### Actual behavior:

* Zammd pull old versions of strings.

### Steps to reproduce the behavior:

* Setup two Zammad servers;
* On servers A do a lot of translation reviews and new translations;
* Push translations to i18n.zammad.com;
* On environment B pull the latest translations;
* Only new translations are pulled;

Now I don't know if there is a review process of translations. If so, please point me to the right process to get my translations approved for new installations.

Thank you!

**Comment by thorsteneckel** [comment]
Hi @edneymatias - yes, there is a review process. For which language did you provided the translations? We'll let you know when they are available.

As a quick workaround you can dump the `translations` table of your system A database and import it into your system B database.

**Comment by edneymatias** [comment]
Hi, @thorsteneckel, thank you! Yes, I was thinking about the dump possibility, but I was about to dump the entire database! Your direction made things much easier! I did some translations for pt-br.

**Comment by thorsteneckel** [comment]
Glad I could help :) Muito obrigado for contributing 👍 We will review your changes and provide it to the rest of the community.
