### ISSUE TITLE
Group note text doesn't get wrapped on user edit form

### ISSUE THREAD

**Issue by edneymatias** [zammad/zammad#1288]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: Debian package
* Operating system: Debian 8
* Browser + version: Chrome 59.0.3071.115

### Expected behavior:

* That the text entered on group notes was correctly wrapped on the user edit form.

### Actual behavior:

* Text goes beyond form boundaries.

![image](https://user-images.githubusercontent.com/22533602/28494142-6159a5aa-6efc-11e7-87d7-1a2e914dd0bc.png)

### Steps to reproduce the behavior:

* Just enter a text long enough.

**Comment by mrflix** [comment]
Hey Edney! Thanks for the bug report and for providing a screenshot with it. That made it easy to solve. The fix is in the current developer branch.

**Comment by edneymatias** [comment]
Hi! mrflix, nice to hear! I saw the same problem on others screen and if you want, I can try to find them!

**Comment by mrflix** [comment]
If its the same bug it will already be fixed. If its something else it would we very helpful if you can provide me with screenshots!

**Comment by edneymatias** [comment]
It's the same bug, so it's closed! Thank you!
