### ISSUE TITLE
Missing replacement of Config and Current User objects in text modules

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#1290]
### Infos:

* Used Zammad version: latest master
* Used Zammad installation source: source
* Operating system: macOS
* Browser + version: -

### Expected behavior:

* I would expect that the config and current user tags are replaced in text modules as they are in triggers

### Actual behavior:

* they are not passed to the frontend replace function and are not getting replaced 😿 

### Steps to reproduce the behavior:

* create text module which includes a config tag like this:
#{config.http_type}://#{config.fqdn}/#ticket/zoom/#{ticket.id}

Insert it in your ticket and the output will be:
-://-/#ticket/zoom/1

**Comment by martini** [comment]
@hanneshal it's in master. Please verify it it's working correctly on ptool. Thanks!
