### ISSUE TITLE
Block escape key when creating / editing text modules

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#1291]
### Infos:

* Used Zammad version: 
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: 

### Expected behavior:

* 

### Actual behavior:

* The text modul overlay closes when you hit escape. Which is bad, especially when you use text modules (type "::") and want to cancel the text selection. In this case all your text is gone.

### Steps to reproduce the behavior:

* open text modules, type text, open the variable list using "::" and hit escape.

**Comment by martini** [comment]
@hanneshal it's in master. Please verify it it's working correctly on ptool. Thanks!

**Comment by martini** [comment]
Implemented in develop and stable and tested on common browsers.
