### ISSUE TITLE
Don't use Proxy on localhost Address.

### ISSUE THREAD

**Issue by jaykijay** [zammad/zammad#1292]
### Infos:

* Used Zammad version: 1.6.1
* Used Zammad installation source: (source, package, ...) debian repo
* Operating system: Debian
* Browser + version: irrelevant

### Expected behavior:
In example of running elasticsearch on localhost and using localhost or 127.0.0.1 as Adress, no proxy should be used because localhost mustn't be connected over Proxy.

* 

### Actual behavior:
It connects via my Proxy Server from which i got errors, because 127.0.0.1 is not a good Ip for using Proxy.
* 

### Steps to reproduce the behavior:
Set Proxy under System -> Proxy and try something on localhost via zammad, e.g. using elasticsearch or setting up elasticsearch

*

**Comment by monotek** [comment]
Sorry, i don't understand whats your problem?
Using Elasticsearch on 127.0.0.1 is the default.

**Comment by jaykijay** [comment]
Hi,
yes i've installed everything like described in your docs. But before installing Elasticsearch i've written my Proxy in the Config under network.
After i did this, i couldn't use zammad run rake searchindex:rebuild
anymore, because it always tried to connect to my local installed ( http://localhost:9200)
elasticsearch engine via the Proxy, which it mustn't. The proxy setting in Zammad should have an exceptions which is either configureasble as you like: Something like "don't use proxy on this Adresses:" or at least should never use proxy when trying to connect to something which is on localhost.
You can easily reproduce this if you write in a Proxy before running configuring elasticsearch.

The problem here is not in elasticsearch but in the way Zammad uses Proxy. It uses Proxy for every connection even if they're going to localhost.
Hope you understand now, if not please let me know then i'll try to explain it in greater detail.
Thanks

**Comment by hanneshal** [comment]
Where did you entered your Proxy config? There is only the NGINX Config, which needs the upstream for the rails and websocket server. Can you paste an example what and where modified proxy settings? I never configured a proxy on local instances.

regards
Johannes

**Comment by jaykijay** [comment]
You can either enable Proxy via Console, described here (Enable Proxy): https://docs.zammad.org/en/latest/admin-console.html
Or via the Webinterface under
System->Network
both will result in the same.
I've entered my Http Proxy Adress there, and after i did this every traffic was send to proxy, connections to localhost, too . Which i mean is very bad.

**Comment by martini** [comment]
Hi @jaykijay 

Thanks for your pull request. We did a small rework. 

For upcoming Zammad 2.0 we added a config option in UI to set the hosts where no proxy is used:

<img width="1265" alt="screen shot 2017-07-27 at 11 48 08" src="https://user-images.githubusercontent.com/110226/28665607-7529b248-72c4-11e7-8bbc-5c9473e4cb84.png">

Thanks a lot!

 -Martin
