### ISSUE TITLE
migrate PostgreSQL to MySQL

### ISSUE THREAD

**Issue by Wisou** [zammad/zammad#1293]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: (source, package, ...) DB PostgreSQL
* Operating system: Debian
* Browser + version: Firefox

Hi,

Can you give me all the steps to migrate db Postgre to Mysql for my instance Zammad ?
I'm not a expert in linux and db...

Bye

Wisou

**Comment by martini** [comment]
Hi @Wisou 

for questions about Zammad use the lists here https://zammad.org/participate -> zammad-users mailing list. This is an issue tracker. Thanks!

As hint, Zammad is using ruby on rails as framework. So all standard rails method to switching databases will work. I did it in the past with https://github.com/yamldb/yaml_db

One more personal note: I would not switch to mysql. For me (after 16 years mysql user) only postgres is an option anymore. Just my 2 cents.

 -Martin

**Comment by Wisou** [comment]
Thx a lot
