### ISSUE TITLE
Debian/Ubuntu installation of zammad via apt fails

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#1294]
* Used Zammad version: 1.5.0
* Used Zammad installation source: debian package
* Operating system: Ubuntu 16.04
* No local proxies

### Actual behavior:

```bash
apt-get update
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://de.archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:5 https://deb.packager.io/gh/zammad/zammad xenial InRelease
Ign:6 https://artifacts.elastic.co/packages/5.x/apt stable InRelease
Hit:7 https://artifacts.elastic.co/packages/5.x/apt stable Release
Ign:11 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
Err:11 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 Packages
  Writing more data than expected (7831 > 1153)
Fetched 106 kB in 2s (50.5 kB/s)
Reading package lists... Done
E: Failed to fetch https://deb.packager.io/gh/zammad/zammad/dists/xenial/stable/binary-amd64/Packages  Writing more data than expected (7831 > 1153)
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Workaround

Do what `apt-get install zammad` would do manually:

```bash
apt-get install mysql-common libpq5 libsqlite3-0 openssl libxml2 libxslt1.1 libreadline5 libreadline6 libssl1.0.0 libmysqlclient20 libevent-2.0-5 libevent-core-2.0-5 libevent-extra-2.0-5 nginx postgresql
wget https://deb.packager.io/gh/zammad/zammad/pool/main/zammad_1.5.0-1500965473.2be861e2.xenial_amd64.deb
dpkg -i zammad_1.5.0-1500965473.2be861e2.xenial_amd64.deb
```

**Comment by ThePatzen** [comment]
same issue here..

**Comment by jaykijay** [comment]
Hi, had similar issue here, for me fixed by deleting old source.list entry and replacing it with updated via:
```
sudo wget -O /etc/apt/sources.list.d/zammad.list \
  https://dl.packager.io/srv/zammad/zammad/stable/installer/debian/8.repo
```
Found from:
https://packager.io/gh/zammad/zammad/builds/2255/install/debian-8

Maybe this will help.
If not try running apt clean.

**Comment by martini** [comment]
> Hi, had similar issue here, for me fixed by deleting old source.list entry and replacing it with updated via:
> [...]

Unfortunately there was a hidden change at packager.io. Thanks @jaykijay for investigation.

Reference: https://blog.packager.io/posts/24-change-of-repository-urls

**Comment by monotek** [comment]
Docs are updated: https://github.com/zammad/zammad-documentation/commit/e9a5ee926916bdbc4cf442e5f659d48d9165a3b4

**Comment by Modius22** [comment]
Heyho,

have the same Problem today. Use the workaround from @jaykijay.

**Comment by martini** [comment]
Thanks for feedback. We already added this to the documentation (https://docs.zammad.org/en/latest/appendix-repo-file.html) and linked it at https://zammad.org .
