### ISSUE TITLE
Third Party Application Authorization and Email Address Problems

### ISSUE THREAD

**Issue by semaf** [zammad/zammad#1296]
Twitter, Github Application created and followed this short documentation https://docs.zammad.org/en/latest/sociallogins-twitter.html.

### Infos:

* Used Zammad version: 1.5.0-1500985917
* Operating system: Ubuntu 16.04
* Browser + version: Opera 46, Chrome 55

### Actual behavior:

Twitter:
- Twitter request on every login for authorization
- Email is not forwarded from Twitter
- User can create a Ticket and Admin get it. Admin can not reply because Email Address is missing.
- If authorization is canceled and you will go back to Website, it get a 404 Error with the URL Schema (https://help.domain.de/auth/failure?message=invalid_credentials&origin=https%3A%2F%2Fhelp.domain.de%2F&strategy=twitter)

Github:
- Email Address is not forwarded from Github. Admin can not reply to Tickets.

**Comment by hanneshal** [comment]
Hi @semaf ,

would you please be so kind and use our templates for bug reports.

Please describe the actual problem and what you would expect.

Thank you!

**Comment by semaf** [comment]
Sehr geehrte Damen und Herren,

Unser Geschäftslokal ist vom 31.07 - 27.08 nur nach telefonischer Absprache besetzt. Für ein Einkauf sowie dringende Fragen wenden Sie sich bitte unter der Rufnummer 0680 230 00 79 beim Hr. Orhan.

Ihre Anfrage per Email wird dennoch verzögert bearbeitet und wir melden uns sobald wie möglich.

########################

Dear Ladies and Gentlemen,

Our Store is from the 31.07 - 27.08 only opened if you make an appointment for shopping or if you have urgent questions at the phone number 0043 680 230 00 79.

Your Email will be replied as soon as possible.


Semaf Electronics
Alserbachstrasse 10
1090 Wein

**Comment by hanneshal** [comment]
closed due inactivity
