### ISSUE TITLE
Block/Banlist / Folder

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#1297]
In addition to #1260 and #540 it would be useful to **ban** mail addresses. And mails from "Spam" or "Junk" folder should not be processed by zammad. Maybe the admin can choose which folders are processed?

**Comment by chrklo** [comment]
I want a block function too.
But it should be configurable between receive and reply.

In my case i would block the central zammad inbound support mailadress.

in some cases the reply function suggests the own inbound support mail adress.
If you don't pay attention in that case the email bounce back to the ticket und you have two spam entrys.

**Comment by monotek** [comment]
Makes no sense to me. Mails should be blocked by spamassassin or something similar not by the app.

**Comment by semaf** [comment]
@monotek And does it make sense if the Admin has no rights to block by spamassassin?

**Comment by monotek** [comment]
Not to me as you can already filter mails and ignore them / move them automatically.

**Comment by MDXDave** [comment]
Mhm I have not seen there is a email filter feature. Its exactly what i asked for.

**Comment by monotek** [comment]
Go to admin area / email / filter
