### ISSUE TITLE
Zammad ignores Reply-To address in incoming mails

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#1299]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: DEB
* Operating system: Deibain 8 "Jessie"

### Expected behavior:

Reply-To address of incoming mail is used when replying to a ticket

### Actual behavior:

Zammad only uses the From address to reply to mails and ignores the Reply-To address

### Steps to reproduce the behavior:

Use Mail channel and send a mail with differing From and Reply-To address

**Comment by martini** [comment]
Hi @fthommen 

strange, this got implemented recently. Is it ignored on auto reply (via trigger) or of your pre "reply" in UI?

 -Martin

**Comment by fthommen** [comment]
on both.
If it helps: The exact version of our package is 1.5.0-1496760218.94263e9.jessie

**Comment by martini** [comment]
Hi @fthommen 

thanks for feedback. The feature is already available in master (upcoming Zammad 2.0 release).

It got implemented in #1006 (I just tested it right now - works in trigger and via reply button)

Greetings,

 -Martin
