### ISSUE TITLE
 Zammad - Centos is not signed

### ISSUE THREAD

**Issue by MANFahrer-GF** [zammad/zammad#1301]
### Infos:

* Used Zammad version: 1.5.0-1500821604.eff91e5.centos7
* Used Zammad installation source: (source, package, ...)
* Operating system: centos7
* Browser + version: -

### Expected behavior:

Abhängigkeiten werden aufgelöst
--> Transaktionsprüfung wird ausgeführt
---> Paket zammad.x86_64 0:1.5.0-1500821604.eff91e5.centos7 markiert, um aktuali                                                                                                                                   siert zu werden
---> Paket zammad.x86_64 0:1.5.0-1500985917.d8be2e0a.centos7 markiert, um eine A                                                                                                                                     ktualisierung zu werden
--> Abhängigkeitsauflösung beendet

Abhängigkeiten aufgelöst

 Package                                     Arch                                        Version                                                                   Paketquelle                                 Größe

Aktualisieren:
 zammad                                      x86_64                                      1.5.0-1500985917.d8be2e0a.centos7                                         zammad                                       76 M

Transaktionsübersicht

Aktualisieren  1 Paket

Gesamtgröße: 76 M
Is this ok [y/d/N]: y
Downloading packages:

Paket zammad-1.5.0-1500985917.d8be2e0a.centos7.x86_64.rpm ist nicht unterschrieben

Zammad Centos is not signed

**Comment by martini** [comment]
Hi @MANFahrer-GF 

we just recognised that packager.io has changed (improved) the repo mechanism.

You just need to update/replace your /etc/yum.repos.d/zammad.repo 

```
sudo wget -O /etc/yum.repos.d/zammad.repo https://dl.packager.io/srv/zammad/zammad/stable/installer/el/7.repo
```

Then `sudo yum -y update zammad` should work well again.

Feedback would be fine!

 -Martin

Reference: https://blog.packager.io/posts/24-change-of-repository-urls

**Comment by martini** [comment]
JFI: Documentation is already update https://docs.zammad.org/en/latest/install-centos.html

**Comment by MANFahrer-GF** [comment]
Thanks for changing the documentation so the update is possible

**Comment by martini** [comment]
> Thanks for changing the documentation so the update is possible

Thanks for fast feedback!
