### ISSUE TITLE
Admin can not create new Ticket

### ISSUE THREAD

**Issue by semaf** [zammad/zammad#1302]
### Infos:

* Used Zammad version: 1.6.1
* Used Zammad installation source: (source, package, ...)
* Operating system: Ubuntu 16.04
* Browser + version: any browser

### Actual behavior:

Upgraded from v1.5.x to v1.6.1 and creating a new Ticket is not possible. If I click on + and hover over "Neues Ticket" than the mouse show the arrow instead a pointer. The same is for the dropup over the Avatar below of "Zuletzt angesehen". 

### Steps to reproduce the behavior:

I removed zammad v1.6 and reinstalled it. Problem is still there. No errors on browser console.

**Comment by jepf** [comment]
Hi @semaf 

unfortunately I cannot reproduce this behavior. Do you have any more information on this issue?

**Comment by MrSnoozles** [comment]
Same as #1398 it seems.

**Comment by martini** [comment]
Tanks for feedback!
