### ISSUE TITLE
Multilinguality

### ISSUE THREAD

**Issue by rossi256** [zammad/zammad#1309]
Hi,
Is the Zammad frontend multilingual actually?
I undetstand the backend is and can be translated but when setting up forms, chat and so on, there's no way to translate the frontend content. Is there a way? or am i missing something?
couldn't find anything about this in docs, so i thought i'd ask here.

**Comment by martini** [comment]
Hi @rossi256 

chat and form is using the language of <html lang="XX"> attribute automatically. 

Default languages like de, es and fr are already translated and available.

 -Martin

**Comment by martini** [comment]
Just reopen on feedback.
