### ISSUE TITLE
Default name of role customer in german language

### ISSUE THREAD

**Issue by gwingend** [zammad/zammad#1310]
### Infos:

* Used Zammad version: 1.6
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: 

### Expected behavior:
Name of the default role "customer" should be the same under "Rollen"-tab and under "Benutzer"-tab if using german userinterface.

### Actual behavior:
If you go to the "Benutzer"-tab you get all a list of existing "Rollen" and one "Rolle" is called "Kunde". 
If you go to the "Rollen"-tab there is a "Rolle" called "customer" but no "Rolle" called "Kunde".

If you switch interface to english and go to the "User"-tab the group "Kunde" now is called "customer".
And if you look at the "role"-tab is is also called "customer".

### Steps to reproduce the behavior:
Update from 1.5 to 1.6.1 and set zammad userinterface to german. 
Do the steps described in "actual behaviour".

**Comment by martini** [comment]
Thanks. It's fixed now in develop.
