### ISSUE TITLE
Multiple Slack/Mattermost integrations/configurations

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#1311]
Hi,

nachdem Zammad ja schon Slack-Integration bietet, würde ich mir das Gleiche für Mattermost wünschen (mattermost.org). MM ist quasi Slack in einer selbst gehosteten Version (Die freie Team-Edition reicht hier sogar schon aus, um Zammad zu integrieren).

Mattermost bietet alle Werkzeuge für eine solche Integration.

Die Kombi wäre der Hammer ;-))

**Comment by martini** [comment]
Hi @jacotec 

Mattermost is compatible to Slack API. That means you already can use the Zammad Slack integration with Mattermost (we do it for our self). :)

 -Martin

**Comment by jacotec** [comment]
Hi @martini,

I should have known that you love this kind of tools *g* ... Sounds great, I'll try that!

**Comment by jacotec** [comment]
@martini: Works like a charm! Awesome!!!

I guess there is no chance to create multiple Slack integrations? So that different Zammad groups are routed to different Mattermost channels? ;-)

**Comment by martini** [comment]
> I guess there is no chance to create multiple Slack integrations? So that different Zammad groups are routed to different Mattermost channels? ;-)

Currently only one config is possible.

**Comment by jacotec** [comment]
How do we say: Was nicht ist, kann ja noch werden ;-))

**Comment by waja** [comment]
> I guess there is no chance to create multiple Slack integrations? So that different Zammad groups are routed to different Mattermost channels? ;-)

There is #796 already

**Comment by RareshLuma** [comment]
+1

**Comment by MrGeneration** [comment]
Locking conversation as there hasn't been any new input apart from `+1`.
If you want to discuss this, please use our community for this and reference the issue. :-)

**Comment by thorsteneckel** [comment]
Better late than never: Thanks @waja for pointing out that this is a duplicate of #796 (multiple Slack/Mattermost configurations). Mattermost is already possible because of the compatible API.
