### ISSUE TITLE
Backup functions not compatible with gunzip < 1.6 (Gunzip -k flag missing on Centos 7)

### ISSUE THREAD

**Issue by KirkBushman** [zammad/zammad#1312]
### Infos:

* Used Zammad version:  1.6.1
* Used Zammad installation source: (source, package, ...) : Packager
* Operating system: Centos 7

### Behavior:
When trying to restore from a backup in Centos 7 an error occours on gunzip:
because the script you are using implies the flag "gunzip -k" exists, 
but on Centos 7 it doesn't.

As you can see from the --help command on a fresh version of Centos 7 the -k flag is missing, and the  restore operation is not working:
![image](https://user-images.githubusercontent.com/20772090/28817820-abbef7a8-76a9-11e7-903e-9b53a2a9eead.png)

on Fedora 25 the flag -k is present:
![image](https://user-images.githubusercontent.com/20772090/28817935-08b5fc68-76aa-11e7-80b5-7bb374d5d0cc.png)

We tried removing -k from the restore function in the .sh file, and the error is no longer there

**Comment by hanneshal** [comment]
File: /contrib/backup/functions
```sh
function restore_zammad () {
  echo "# Restoring Files"
  tar -C / --overwrite -xzf ${BACKUP_DIR}/${RESTORE_FILE_DATE}_zammad_files.tar.gz

  if [ "${DB_ADAPTER}" == "postgresql" ]; then
    echo "# Restoring PostgrSQL DB"
    gunzip -ck < ${BACKUP_DIR}/${RESTORE_DB_DATE}_zammad_db.${DB_FILE_EXT}.gz | su -c "psql -d ${DB_NAME}" postgres
  elif [ "${DB_ADAPTER}" == "mysql2" ]; then
    echo "# Restoring MySQL DB"
    gunzip -ck < ${BACKUP_DIR}/${RESTORE_DB_DATE}_zammad_db.${DB_FILE_EXT}.gz | mysql -u${DB_USER} -p${DB_PASS} ${DB_NAME}
  fi
}
```

**Comment by hanneshal** [comment]
Support for "-k" was added in gunzip 1.6. So I see multiple options here:
- check for Version of gunzip
- manual copy before extract -> needs more memory
- switch to a different pack/unpack programm

@monotek @rkaldung Any suggestions?

**Comment by monotek** [comment]
I'll fix it after my vacation.

**Comment by monotek** [comment]
Fixed in: https://github.com/zammad/zammad/commit/e6da999edc77e6118b2b0a70f530cab4a8a36366
