### ISSUE TITLE
Customer user can see ticket titles of foreign tickets by guessing the URI

### ISSUE THREAD

**Issue by joergplewe** [zammad/zammad#1314]
### Infos:

* Used Zammad version: as hosted
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: 

### Expected behavior:

* Ticket titles should be always hidden if rights are insufficient

### Actual behavior:

* Titles can be seen even if rights are insufficient

### Steps to reproduce the behavior:

* Login as a customer user
* Guess an URI of a ticket he does not own
* 'Opps.. I'm sorry, but you have insufficient rights to open this Ticket.' is correctly shown
* Title of ticket shows up for the opened tab, IMHO it shouldn't

**Comment by martini** [comment]
Hi @joergplewe 

I can't reproduce it:
<img width="1273" alt="screen shot 2017-08-01 at 15 18 00" src="https://user-images.githubusercontent.com/110226/28827080-b598bcdc-76cc-11e7-9036-67ab2e83e095.png">

Could it be, that it's the title of the last ticket which was able to read?

Is it on your side also, if your reload the browser and try to open it again?

Thanks!

 -Martin

**Comment by joergplewe** [comment]
Hi Martin!

Got it: Reloading the page (F5, Ctrl-R) does not change anything, but using a new tab or restarting the browser solves the issue.

To reproduce, login with a user who has sufficient privileges, than re-login with the restricted user. From there on, all ticket titles will show up, no matter whether the privilegded user opened the issue or not.

**Comment by martini** [comment]
> To reproduce, login with a user who has sufficient privileges, than re-login with the restricted user. From there on, all ticket titles will show up, no matter whether the privilegded user opened the issue or not.

That helps! Themes that not all client caches are removed after religion. We are working on it...

**Comment by hanneshal** [comment]
see issue: https://github.com/zammad/zammad/issues/1280

**Comment by andreaci** [comment]
no, the problem isn't cache-related.
I've seen this problem with a new pc too.
just click a few times on the titles on the left

**Comment by thorsteneckel** [comment]
Hi @andreaci - can you please reproduce this in one of our [free hosted instances](https://www.zammad.com/getting-started) instances and tell us the name of the one and how to reproduce it? Thanks!

**Comment by andreaci** [comment]
I'll try tomorrow morning!

I just discovered this because I have a "worse" problem.
A customer created a ticket and neither Agents, neither the server admin can access that ticket. But this was just for a wrong group assignment.
![2018-11-14_17-21-59](https://user-images.githubusercontent.com/8290389/48496226-e2264300-e831-11e8-9a5b-2349b4eb27a2.png)
