### ISSUE TITLE
Time Accounting not showing all tickets, time is missing completly of specific ticket

### ISSUE THREAD

**Issue by bkolbe** [zammad/zammad#1315]
### Infos:

* Used Zammad version: Version 1.5 at latest updates
* Used Zammad installation source: (source, package, ...) RPM-Repsoitory
* Operating system: Centos 7
* Browser + version: Firefox 54

### Expected behavior:

Added Time to Ticket in Juli should show up in Admin Time Accounting on Juli.

### Actual behavior:

This happens in July
With one Ticket i have monitored my self, i can see that i have spend time in the summary of the Ticket and the history. But if i got to Admin timetracking this ticket is not listed and the time never shown up.

On August i just added some extra time for debugging and in timetracking now i can see in august the ticket but still not in july.

### Steps to reproduce the behavior:
i can't

**Comment by hanneshal** [comment]
Hi @bkolbe,

do you have access to your zammad database? Could you check the table ticket_time_accountings
for those tickets? 
I tried to reproduce it, with no luck. So maybe it's just an UI-issue. 

thank you

**Comment by bkolbe** [comment]
Hi @hanneshal 
I have cheked my database. It looks fine 
```
zammad_production=# select * from ticket_time_accountings where ticket_id=331;
 id  | ticket_id | ticket_article_id | time_unit | created_by_id |       created_at        |       updated_at        
-----+-----------+-------------------+-----------+---------------+-------------------------+-------------------------
 188 |       331 |               881 |      0.10 |             3 | 2017-08-01 16:45:06.392 | 2017-08-01 16:45:06.392
 182 |       331 |               857 |      0.25 |             3 | 2017-07-31 07:35:43.976 | 2017-07-31 07:35:43.976
(2 rows)
```
The Ticket is listed in August correctly with 0.35 and also saying that in august is spent 0.1  
In July it is not listed.

**Comment by hanneshal** [comment]
Ok, so there are missing entries for July. :/ 
I'll try to investigate this further. Please observe if you can reproduce this

**Comment by rolfschmidt** [comment]
Hi @bkolbe ,
there was a calculation which excluded your time accouting of the end of the month because it was only calculating to the 2017-07-31 00:00:00 and not 2017-07-31 23:59:59. I changed the behaviour and it should work now in the develop branch. Maybe you find the time to test it.

Best regards,
Rolf

**Comment by bkolbe** [comment]
Hey @rolfschmidt,
i have updated the system to the 2.0 version of the centos repo. It now working. Thank you.
