### ISSUE TITLE
Blockchain Implemention

### ISSUE THREAD

**Issue by maektwain** [zammad/zammad#1317]
### Infos:

* Used Zammad version: Master Branch 
* Used Zammad installation source: (source, package, ...) source
* Operating system: Mac OS X Sierra
* Browser + version: Chrome

Implementing Blockchain as a layer to store Tickets and Mostly everything which is happening between  consumer and organization, 

1. Wallet Implementation (Added Column in user Model by extending)
2. Connected With Private Node 
3. Getting Addresses / Connected to blockchain etc...
4. UI?

### Expected behavior:

*  Added walletAddress field in User API, and it is returning as below and added the walletAddress in the UI model.

<a href="https://ibb.co/fVHbVQ"><img src="https://preview.ibb.co/jzcbVQ/Screen_Shot_2017_08_03_at_4_46_48_AM.png" alt="Screen_Shot_2017_08_03_at_4_46_48_AM" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>private image sharing</a><br />

Now when i load the modal for managing users i do not see any walletAddress field 
### Actual behavior:

* Not showing up

### Steps to reproduce the behavior:

*

**Comment by hanneshal** [comment]
I really dont know what you are doing or want to achieve, but maybe this helps:

/app/assets/javascripts/app/models/user.coffee
/app/assets/javascripts/app/controllers/users.coffee

**But** when you just want to store your blockchain id, why you don't just create a new object (Admin->Object->User) for this user?
Two seconds later (for the restart) the field shows up. No need to edit anything within the source files. 

![helpdesk](https://user-images.githubusercontent.com/804939/28918789-0ba5efda-784b-11e7-8c1a-394640661a10.png)

**Comment by monotek** [comment]
If it's about saving all data in a public(?) Blockchain for transparency

**Comment by maektwain** [comment]
Let's talk more and discuss currently i am working on the video intelligence to gather and create tickets by detecting objects and classifying them to create labels and using NLP to create structured texts for automated tickets using zammad 
1. Blockchain Private  to store and validate tamper proof data between customer and agents and orgs.
2. Video Intelligence

**Comment by thorsteneckel** [comment]
Sorry to interrupt the party but this issue tracker is not the right place to discuss this topic. Please move over to https://community.zammad.org. Thanks!
