### ISSUE TITLE
'Access-Control-Allow-Origin' error when submitting web form.

### ISSUE THREAD

**Issue by colinwilson** [zammad/zammad#1318]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: 1.5.0-1501623470.50f2d496.jessie
* Operating system: Debian 8
* Browser + version: Chrome 59.0.3071.115 & Firefox 54.0.1 (32-bit)

### Expected behavior:

* Web form to be submitted and thank you message displayed.

### Actual behavior:

* Receiving 500 internal error (`No 'Access-Control-Allow-Origin' header is present on the requested resource`) and `Failed to submit form!` pop-up alert when attempting to submit web form.

### Steps to reproduce the behavior:

I'm using the following code on my web form page:
```
<script id="zammad_form_script" src="https://zammad.mydomain.com/assets/form/form.js"></script>	
  <script>
	$(function() {
	  $('#support-request').ZammadForm({
		messageTitle: 'Support Request Web Form',
		messageSubmit: 'Submit',
		messageThankYou: 'Thank you for your inquiry (#%s)! We\'ll contact you as soon as possible.',
                noCSS: true,
		attachmentSupport: true
	  });
	});
	</script>
```
When attempting to submit my form I'm receiving an `Access-Control-Allow-Origin` error via the browser console:
```
XMLHttpRequest cannot load https://zammad.mydomain.com/api/v1/form_submit. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mydomain.com' is therefore not allowed access. The response had HTTP status code 500.
```
with the form failing to complete and show the thank you message.

![failed_to_submit_form](https://user-images.githubusercontent.com/12916656/28900482-7649cc7e-77e9-11e7-8dd2-39fee4e34a98.png)

The submitted details do reach my Zammad server (minus any attempted attachment).

**Headers**
```
Request URL: https://zammad.mydomain.com/api/v1/form_submit
Request method: POST
Remote address: x.x.x.x:443
Status code: 500 Internal Server Error
Version: HTTP/1.1
```
I should note that I wasn't experiencing this issue before a recent upgrade of the Zammad package (`apt-get update && apt-get upgrade`).

**Comment by colinwilson** [comment]
Narrowed it down a little.

Seems this only happens when the Storage Mechanism is set to `Database` and an there's an attachment with the web form.

**/var/log/zammad/production.log:**
```
I, [2017-08-03T02:54:07.530339 #11947]  INFO -- : Started POST "/api/v1/form_submit" for x.x.x.x at 2017-08-03 02:54:07 +0100
I, [2017-08-03T02:54:07.536005 #11947]  INFO -- : Processing by FormController#submit as */*
I, [2017-08-03T02:54:07.536220 #11947]  INFO -- :   Parameters: {"name"=>"Colin", "email"=>"colin@mydomain.com", "body"=>"Test Message 18", "file"=>[#<ActionDispatch::Http::UploadedFile:0x007f9344467538 @tempfile=#<Tempfile:/tmp/RackMultipart20170803-11947-fl9mvj.png>, @original_filename="Screenshot_2017-08-02-17-14-42.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"file[]\"; filename=\"Screenshot_2017-08-02-17-14-42.png\"\r\nContent-Type: image/png\r\n">], "title"=>"Support Request Web Form", "token"=>"undefined"}
I, [2017-08-03T02:54:08.723531 #11947]  INFO -- : Completed 500 Internal Server Error in 1187ms (Views: 0.2ms | ActiveRecord: 24.8ms)
F, [2017-08-03T02:54:08.724621 #11947] FATAL -- : 
NoMethodError (undefined method `logger' for #<Array:0x0055e98eef42f0>):
  app/controllers/application_controller/handles_errors.rb:21:in `unprocessable_entity'
```

**Comment by hanneshal** [comment]
verified on master.

**Comment by furqanzamir** [comment]
Hi There is error when i open elastic search but it show proper in this link http://127.0.0.1:9200/zammad_production
when i open http://127.0.0.1:9200 its show this
elastic build version etc
http://127.0.0.1:9200/zammad_production/Ticket/_search\n#\u003cUserAgent::Result:0x007fd4e1818400 @Success=false, @Body=nil, @DaTa=nil, @code="400", @content_type=nil, @error="Client Error: #\u003cNet::HTTPBadRequest 400 Bad Request readbody=true\u003e!"\u003e"}

how to solve this issue

**Comment by monotek** [comment]
Please stop highjacking issues. This on has nothing to do with elasticsearch.

Since november 15th we handle all requests, except real bugs, at our community board.
Full explanation: https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21

Please post:
- Feature requests
- Development questions
- Technical questions

on the board -> https://community.zammad.org !
