### ISSUE TITLE
Error message "Unable to update" when trying to send an email

### ISSUE THREAD

**Issue by polyrack** [zammad/zammad#1319]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: Ubuntu Package
* Operating system: Ubuntu 16.04.2
* Browser + version: Chrome

### Expected behavior:

* When I write an eMail from within a ticketand try to send it, it should get sent out.

### Actual behavior:

* I get the error message "Unable to update" - even though the system can send out emails
![image](https://user-images.githubusercontent.com/30685372/28910841-b4dad196-782e-11e7-9804-1cff948e7f28.png)

### Steps to reproduce the behavior:

* 
![image](https://user-images.githubusercontent.com/30685372/28910894-d2e741d8-782e-11e7-9904-3b9ee0599953.png)

**Comment by thorsteneckel** [comment]
What's your browser console showing? Reload your Zammad-Window, open the browser console and retry the action. There should be a message there.

**Comment by polyrack** [comment]
I get these errors:

http://[SERVER_URL]:3000/api/v1/tickets/94?all=true 500 (Internal Server Error)
send @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:3
ajax @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:3
t.addCurrentRequest @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:59
(anonymous) @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:59
t.request @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:59
App.Ajax.e.request @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:59
(anonymous) @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:23
App.TicketZoom.i.submitPost @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:39
(anonymous) @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:38
o.article.Config.get.App.Ticket.selector.permissionCheck.App.TicketZoomTimeAccounting.submitCallback @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:39
App.TicketZoomTimeAccounting.i.skip @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:41
(anonymous) @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:41
(anonymous) @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:8
dispatch @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:2
m.handle @ application-f9b519f9b4286376544bebb924bcf3053938631bf7b929ce007a43ee96260c36.js:2
:3000/#ticket/zoom/94:1 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'val' of undefined
    at Object.cipEvents.triggerActivatedTab (chrome-extension://oakpnnaknlicjghpchokjoelhfjnmhcd/rdmchrome.js:2313:14)
    at chrome-extension://oakpnnaknlicjghpchokjoelhfjnmhcd/rdmchrome.js:61:14

**Comment by thorsteneckel** [comment]
`http://[SERVER_URL]:3000/api/v1/tickets/94?all=true 500`: That looks like something went wrong in the backend. Please perform the action again and provide the lines created in the `log/production.log` file.

**Comment by polyrack** [comment]
I found the error in the log => There was no email address set for the Admins Group
