### ISSUE TITLE
FR: Translations for own Objects

### ISSUE THREAD

**Issue by maege** [zammad/zammad#1320]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: (source, package, ...) package
* Operating system: Debian
* Browser + version: Edge 

It would be great if we could create our own objects in different languages. According to issue #574, we have added the "customer feedback" status to our system. For out German-speaking users/customers, we would be happy to translate "Warten auf Kundenantwort" or similar. With the inline translator these fields can not be selected.

**Comment by hanneshal** [comment]
Please see: https://github.com/zammad/zammad/issues/1282
