### ISSUE TITLE
Chat socket issue using Apache Webserver

### ISSUE THREAD

**Issue by SAIntegration** [zammad/zammad#1321]
Hello! 

I am having issue with Zammad socket server configuration on Httpd, centOs with SSL enabled. it will be great Help if any one can provide the Virtual Host  configuration for Web-server And Socket Server. 
here is the error got in browser .
WebSocket connection to 'wss://XXXXXXX.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 500. 
and in HTTPD  error logs show this Waring 
[warn] 
proxy: No protocol handler was valid for the URL /ws. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule. 

here is my Virtual Host config 

```
<VirtualHost *:443>
  ServerName XXXXXXXXXX.com
  DocumentRoot /path/to/prohect/root/public 
#  ProxyPass /favicon.ico !
 # ProxyPass /robots.txt !
 # ProxyPassMatch ^/(404|422|500).html$ !
 # ProxyPass /assets/ !
<Proxy *>
        Order Allow,Deny
        Allow from all
 </Proxy>
ProxyPass /ws wss://127.0.0.1:8443/
ProxyPassReverse /ws wss://127.0.0.1:8443/
ProxyPass / http://127.0.0.1:3005/
ProxyPassReverse / http://127.0.0.1:3005/
SSLEngine on
SSLCertificateFile /path/ssl.crt
SSLCertificateKeyFile /path /ss.key
</VirtualHost>
```

I do not  know where is the issue. i have search for it on google also. but could find any solution. 
I am stuck with this issue from last 4 days. thanks in advance. 

Note :  cloudflare is also enabled on my server.

**Comment by hanneshal** [comment]
Please check you ports first. Are all services running? Please verify using 
netstat and post the output here. The default config is different.

https://github.com/zammad/zammad/blob/17983ad17cdb13491fd0a149f00d421d0d342d68/contrib/apache2/zammad.conf

is there anything else running on this server?

**Comment by SAIntegration** [comment]
her is the netstat result for socket server. 
netstat -nlp | grep :8443
tcp        0      0 0.0.0.0:8443                0.0.0.0:*                   LISTEN      5210/daemons.rb     
and for web server 
netstat -nlp | grep :3005
tcp        0      0 0.0.0.0:3005                0.0.0.0:*                   LISTEN      5101/puma 3.6.0 (tc

**Comment by monotek** [comment]
So you try to install from source and you want to use Apache as your webserver and you changed the standard ports of the Zammad services?

We hardly can support special configurations like this.

Why don't you use the official centos packages?

https://docs.zammad.org/en/latest/install-centos.html
