### ISSUE TITLE
Customer response via note does not trigger escalation

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#1322]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: DEB
* Operating system: Ubuntu 16.04

### Expected behavior:

Ticket:
- Existing Ticket where we worked already on it
- We wait for the customer to response
- Pending Reminder
- Attached to SLA with Update Time 2h

Customer:

Answers not via email but adds a note in the zammad Web-UI as response

I would expect:

The escalation is reset and starts counting down from 2h again.

(exactly as is if the customer would have answered by email)

### Actual behavior:

Ticket stays as is and will never escalate.

**Comment by thorsteneckel** [comment]
I had a similar issue where the ticket state won't change (closed -> open) after the customer added a note via the web frontend. This may be the same issue. We're investigating it. Thanks for reporting!

**Comment by hiaz** [comment]
@thorsteneckel This issue is getting more and more critical for us. We miss customer answers via the zammad web-ui (because the ticket stays "grey") and as a result we hurt our SLAs. Can you tell me the current state? Thank you.

**Comment by thorsteneckel** [comment]
Hi @hiaz - I'm sorry to say that this issue currently has no high priority. We are working hard to provide further features, improvements and bug fixes. Our bugfixing contingent is currently exhausted because our support customers need our help.
If you rely on this on a daily commercial base consider one of our [support contracts](https://zammad.com/de/preis#selfhosted) or contact us at support@zammad.com and escalate this issue on a paid base.
That's all the options we can provide currently.

**Comment by hiaz** [comment]
@thorsteneckel Thank you. We have already a support contract and I will escalate this issue via support@zammad.com. I just did not know the correct process.

**Comment by thorsteneckel** [comment]
Oh Sorry - again. Honestly I wasn't aware of that. I'll prioritize the issue right away 👍

**Comment by thorsteneckel** [comment]
@muhammadn - can you please prioritize this issue and fix it in the stable branch, too? Thanks!

**Comment by muhammadn** [comment]
@thorsteneckel will priortize this. Seems most of my issues are finished. 👍

**Comment by martini** [comment]
Hi @hiaz 

(nice to read you :) )

just one question, is the issue regarding not resetting escalation or because the ticket is not reopened by default (closed state is selected per default) if the customer reply via web interface?

Thanks!

 -Martin

**Comment by hiaz** [comment]
Hi @martini 

I will describe the issue a little bit more detailed - just to be sure:

1) As an agent I receive an inbound ticket via email or via web ui
2) It there is a related SLA the time it ticking down and the ticket is "orange" and "open"
3) I'll respond to the ticket and set a "pending reminder", the ticket is "grey"
4) The customer answers again via web ui (not email) the ticket stays "grey" and "pending reminder"

Yes, I get a notification in zammad and via email (if configured) in that situation. But if I am a very busy agent I ignore these notifications (because I get a lot of them) and relay on my lists (overviews) and escalation in zammad.

I think it should not make a difference if a customer answers the ticket via email or web-ui. The behaviour should be the same. 

Cheers,
Mathias

**Comment by martini** [comment]
@hiaz thanks for the wonderful description! Now we got it. We are already working on it...

**Comment by rolfschmidt** [comment]
Hi @hiaz ,
this bug should be fixed now in **stable** and **develop** branches. The default follow up state will be also set now in the customer interface if the customer writes a reply. After he wrote some text in the RTE the state will be automatically update. This behaviour will make the it equal to the mail communication and also fix described escalation issues i think.

Best regards,
Rolf
