### ISSUE TITLE
Login via Gitlab via SAML via ADFS results in "Zammad-Login" = "Gitlab User ID"

### ISSUE THREAD

**Issue by sschroll** [zammad/zammad#1324]
### Infos:

* Used Zammad version: current stable
* Used Zammad installation source: docker-compose
* Operating system: Ubuntu Server 16.04 LTS
* Browser + version: Chrome 60

### Expected behavior:

* The Zammad-Login should be the Email or even better the Username out of Gitlab

### Actual behavior:

* The Zammad-Login corresponds to the Gitlab "User ID"

### Steps to reproduce the behavior:

1. Run Gitlab (e.g. via Docker) and create an account within Gitlab (i think the whole LDAP and SAML configuration is not necessary to reproduce)
2. Create an application within Gitlab and configure Zammad
3. Login to Zammad using the Gitlab-Button

Now in the Users-LOGIN is the Gitlab "User ID"

**Comment by thorsteneckel** [comment]
Hi @sschroll - we create the users with the following attribute mapping:
https://github.com/zammad/zammad/blob/9949dd18dc285caa814fbeb55ae99b978ba0df14/app/models/user.rb#L375-L385

However, Zammad checks the login and email for identifying Users:
https://github.com/zammad/zammad/blob/9949dd18dc285caa814fbeb55ae99b978ba0df14/app/models/user.rb#L323-L330

So login via Email is always possible. I don't see a need to change that. Please start a discussion over at the [community board](http://community.zammad.org/) and let me know about the use case that would require such a change **in case you disagree**.

Closing now.
