### ISSUE TITLE
User overlay menu not accessible on Chrome and Safari for iOS and Chrome for Android

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#1325]
### Infos:

* Operating system: iOS 10.0-10.3, Android 6-7
* Browser + version: Chrome for Android, Chrome for iOS, Safari for iOS, several versions

![img_0592](https://user-images.githubusercontent.com/23480845/28971444-45a1864a-792c-11e7-9f91-f441d7007c97.PNG)

### Expected behavior:

* when clicking my avatar/username button on the bottom left, the menu opens and is clickable

### Actual behavior:

* when clicking my avatar/username button on the bottom left, the menu opens but is not clickable

### Steps to reproduce the behavior:

* click my avatar/username button on the bottom left. Tested on my own zammad installation as well as with https://support.zammad.com ;-)

**Comment by MrSnoozles** [comment]
Maybe same as #1398 ? Does the same apply if you try to create a new ticket?

**Comment by martini** [comment]
@MrSnoozles Yes. I think it's the same. Just waiting for bugfix QA, then I can test it and give feedback.

**Comment by babakkazemi** [comment]
@martini works now with build 2406, closing. Thanks!

**Comment by nonameolsson** [comment]
See my comment in #1398 please. We can't use this on a phone nor a tablet. It doesn't react to touch.
