### ISSUE TITLE
Last line of article not selectable

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#1329]
### Infos:

* Used Zammad version: 1.5.0-1496760218.94263e9.jessie
* Used Zammad installation source: DEB package from deb.packager.io
* Operating system: Debian 8.9
* Browser + version: Firefox 50.1.0 on openSuSE 13.2

### Expected behavior:

* The last line (or parts of it) of an article is selectable (e.g. to select for an email reply etc.)

### Actual behavior:

* The very last line of a ticket's article content is not selectable.  Instead clicking on the very last line triggers the "folding out" of the article information panes (email addresses, channel info etc.).  See more info in "Steps to reproduce the behavior".

### Steps to reproduce the behavior:

* write an article with content up to the last line (no empty line at the end!)
* try to select the very last line (and possible more content) e.g. to cite it in an email answer
  * if you start a "click-and-drag" block selection from above, the selection will stop at the end of the second last line
  * if you start selecting from within the last line, no selection will happen.  Instead the "information panes" will be folded out

**Comment by fthommen** [comment]
With Google Chrome 60.0.3112.90 (on openSuSE 13.2) the behaviour is slightly different:

* it is possible to "click-and-drag" select from above until the end of the very last line
* it is possible to "click-and-drag" select _from_ the last line by starting the selection from within this line (the whole line will automatically be selected)
* a simple click in the last line will still trigger the fold out/fold in of the info panes

**Comment by hanneshal** [comment]
Hi @fthommen,

can you add screenshots for both scenarios. This would help us.

thank you & regards

**Comment by fthommen** [comment]
A screenshot probably wouldn't make sense but rather a screencast to show how one selects and what doesn't work.  However now that I want to do this (and after - for some other reason - the Zammad server has been restarted) I cannot reproduce the issue any more.  I'll therefore close this issue.
