### ISSUE TITLE
auto reply (on new ticket) doesn't work after update

### ISSUE THREAD

**Issue by PatrickGoenner** [zammad/zammad#1330]
Hi, the default trigger "auto reply (on new ticket) doesn't work after latest zammad updates. I did it two days ago. Reboot is without any efforts. Sending mails is still possible.

I've changed to the new Debian 8 repository and installed the new packages, after that I've looked for zammad updates.

Regards
Patrick

**Comment by hanneshal** [comment]
Hi @PatrickGoenner,

please don't delete our issue templates. They are here for a good reason.

Some questions:
- Zammad version you upgraded from
- Zammad version you are actually have installed
- Have you tried to recreate the trigger (disabled the old one)?
- Pleas paste the output of your log (anonymised) in the corresponding time frame

**Comment by PatrickGoenner** [comment]
auto reply ist working again.

The reason: last week I've made changes on the trigger and tried to add an exception for "no auto reply for special mail adresses): "Organisation - is not - specific organisation - Ausnahmen" which contents some related customers

**Comment by PatrickGoenner** [comment]
it was my fault, there were no update files at all. I'm still using the latest version (1.5.0).
