### ISSUE TITLE
Each Email sender is automatically added as customer

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#1333]
Hi,

On Zammad, I have different setup of emails and some of them are informative emails and some of them are the customers. When someone sends an email, to enquiry som information,  his/her email is added into customer  automatically and triggers setup on customers  will be applied to them as well as  the real customers.

How can I prevent it?

Best Regards,

OS: Centos7
Zammad: 1.5

**Comment by hanneshal** [comment]
Hi @hamzehmohammadnia,

this is not possible. It is Zammads default behaviour to make the handling for agents easier. 
We don't have any plans to change it at the moment.

regards
Johannes

**Comment by hamzehmohammadnia** [comment]
Dear @hanneshal, 
Thank you for your reply. So, it means the real customers should be classified within "Organizations" and acquire potential policies based on organization (real customer) policies. Am I right?


If it won't be possible to eliminate specific email address (records) from customer roles, then how to handle spamming?

Best Regards,
