### ISSUE TITLE
Tried to set up a knowledge base

### ISSUE THREAD

**Issue by moellert** [zammad/zammad#1334]
### Infos:

* Used Zammad version: 1.5 and 1.6
* Used Zammad installation source: Package
* Operating system: Ubuntu 16.04

I am testing Zammad as an alternative for the currently used ticketsystem in my company and one of the requirements is a knowledge base.
Therefore I tried to set up something like this with the given resources. 

First try, in version 1.5.x
My idea was to create an overview for the customers, agents and admins which contains every ticket with the tag „Article“ or a custom field with the same effect. After configuring this I created some test tickets with different users and tried to read them with the customers.
This didn‘t work because customers aren‘t allowed to see other users tickets and there was no possibility to change this.(Organisations are no option for this, because this would show every ticket and not just the articles if you search for something)

Second try, in version 1.6.x
After my first failure I created a new instance with the development version 1.6.x and tested the new role management.
Then I did the same as mentioned above and added an additional role. The one and only right of this role was the agent right to read tickets in the „Article“ group.
After this, I additionally added this role to every customer.
Now every customer was able to see the article tickets in the group, but the mix of rights caused some problems:
- The customer wasn’t able to choose a group for his ticket(I think, because he just had the right to read 
  in the “Article” group and no longer the customer right)
- The “New Ticket” button appeared twice after pushing the green plus sign.
- One “New Ticket” button opened the customer ticket creation interface and the other button opened 
  the agent ticket creation interface.

Now this try also failed because of the appearing problems.

This leads me to my Questions:

- Is there anything I didn‘t see and which could give me a solution for my knowledge base?

- Could it be an improvement for the role management if you were able to configure the customers rights just like the agents rights? (I might think of some use cases, where it is necessary to have this feature.)

- Would you consider to implement a knowledge base/self service or is it planned to do something like this?

**Comment by hanneshal** [comment]
I must confess I have respect for your effort you put into this. 🏎 
At the moment I don't see a way for doing this without custom development. The default behaviour for customers+views of Zammad would stop you + I don't think it is the way to go.

And yes: we are working on something like this ;) 
See the state of the union post: https://zammad.com/news/status-outlook in the news section. 
And
https://github.com/zammad/zammad/issues/366

Regards
Johannes
