### ISSUE TITLE
Logo in signature 

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#1336]
Hi,
Is it possible to add logo within default signature of an email? I cant see it in signature menue.

Best,

**Comment by martini** [comment]
Hi @hamzehmohammadnia 

JFI: This is a issue tracker, not forum. For questions please go to https://zammad.org/participate -> Do you have questions about how to use Zammad

Anyway, for signatures (also text modules) you can use any html including inline images (e. g. inserted via clipboard). -> Enjoy!

-Martin

**Comment by eaglecopter** [comment]
Hi @martini 
I don't get it, it just doesn't work. 

v2.7.x
Ctrl+Alt+h doesn't work either to see the shortcuts for text formatting (from here https://github.com/zammad/zammad/issues/815)

**Comment by MrGeneration** [comment]
Please don't recycle closed github issues and point support requests to our community board:
https://community.zammad.org
