### ISSUE TITLE
Web Form: In JavaScript snippet  jQuery is missing

### ISSUE THREAD

**Issue by autohausnielsen** [zammad/zammad#1338]
I tried to build a zammad Web Form into my website. The snippet didn't work, because there was no reference to jQuery. 

Please include something like
`
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>`
`
in your snippet output.

### Infos:

* Used Zammad version: 1.5.0-1501408728.d0ac4461.xenial
* Used Zammad installation source: ubuntu package
* Operating system:  ubuntu 16.04

**Comment by hanneshal** [comment]
fixed in develop
