### ISSUE TITLE
Relative and absolute time bug

### ISSUE THREAD

**Issue by moellert** [zammad/zammad#1340]
### Infos:

* Used Zammad version: 1.6.1-1502369170.5a9138e4.xenial
* Used Zammad installation source: Ubuntu package
* Operating system: Ubuntu 16.04
* Browser + version: Chromium 60.0.3112.78 and Mozilla Firefox 54.0

### Expected behavior:

* While I am configuring a new Trigger or Scheduler, I am able to use relative and absolute times.
  like here in version 1.5:
![new trigger relativ](https://user-images.githubusercontent.com/30858921/29204004-9f1987de-7e74-11e7-8d83-79efafa79240.png)

![new trigger absolut](https://user-images.githubusercontent.com/30858921/29204005-a14a5664-7e74-11e7-9ac6-abae09f7abcf.png)

### Actual behavior:

* Now in Version 1.6.x, I am only able to use the absolute times. It doesn't matter if I choose the relative or the ablolute option, the interface stays the same.
  
![new trigger](https://user-images.githubusercontent.com/30858921/29204165-be85413e-7e75-11e7-9b46-52ba5e501e27.png)

### Steps to reproduce the behavior:

* Setup a trigger or scheduler with absolute and relative times

**Comment by babakkazemi** [comment]
I can verify that behaviour on 1.6.1

**Comment by rolfschmidt** [comment]
Hey guys,
thank you very much for your report and verification ;-) Should be fixed now.

Best regards,
Rolf
