### ISSUE TITLE
Ticket overview shows &amp; instead of &

### ISSUE THREAD

**Issue by abckas** [zammad/zammad#1346]
### Infos:

* Used Zammad version:  1.5.x
* Operating system: Windows 10
* Browser + version: Google Chrome 60.0.3112.90

### Expected behavior:

* Should show a & like , "Zammd GmbH & co Kg."

### Actual behavior:

* Shows "Zammad GmbH & amp; co Kg."

### Steps to reproduce the behavior:

* Place a "&" in the Organisation Name

**Comment by dennybresch** [comment]
Hi @abckas,

we can't reproduce this issue on version 1.5.0.
Could you try to rename this Organisation and maybe use other special characters as well.

Please send a screenshot.

Best regards,
Denny

**Comment by hanneshal** [comment]
Closed.
Please reopen when this issue still exists in 2.0.
