### ISSUE TITLE
LDAP group retrieval problem

### ISSUE THREAD

**Issue by mrcschilling** [zammad/zammad#1347]
### Infos:
* Used Zammad version: latest stable 1.5.0
* Used Zammad installation source: (source, package, ...) yum package
* Operating system: CentOS7
* Browser + version: Opera 46.0

Maybe duplicate or similar problem like: 
[https://github.com/zammad/zammad/issues/1088](url)

Hi, I tried to integrate our LDAP (openldap 2.4) with zammad, but I am getting the following error message:

> Unable to retrive group information, please check your bind user permissions.

Production log does not show any errors. I followed the steps from the ticket above (1088) and tried different settings in the rails console.
user.filter, user.attributes and user.uid_attribute are detected as they should. But group.filter is nil, group.list is {} and group.uid_attribute is "dn"
Maybe our ldap schema is to complex. We have a third "dc" layer right under our base dn. Below that we have a o-layer which would represent organisations or groups and below that an ou layer which is representing sub groups in which the users are stored.

As it might be strongly connected with our ldap schema I cannot give any advice on how to reproduce the problem.
Any help would be appreciated.

**Comment by thorsteneckel** [comment]
Hi @mrcschilling - Seems Zammad can't [auto-detect your LDAP group filter](https://github.com/zammad/zammad/blob/98c43f9090e0fa76e4e7ded01ea3568fc1eadcbb/lib/ldap/group.rb#L115). What would be the right filter for your LDAP?

**Comment by mrcschilling** [comment]
The top most group is o=companyname,dc=company,dc=***,dc=net, but the persons are one layer below in ou=subcompany,o=companyname,dc=company,dc=***,dc=net.

**Comment by thorsteneckel** [comment]
Sorry if I wasn't clear enough. I mean which filter would you apply if you want to list all the groups in your LDAP - not users. Zammad tries `(objectClass=group)` and `(objectClass=posixgroup)` but seems to find no groups.

**Comment by mrcschilling** [comment]
It would be objectClass=organization

**Comment by thorsteneckel** [comment]
Hi @mrcschilling - I fixed this with the commits above. The changes are available in the develop and stable branch in about 30 minutes from now. Would be great if you could update your Zammad afterwards and leave me feedback if it works for you 🚀

**Comment by mrcschilling** [comment]
Works like a charm. Thank you very much
