### ISSUE TITLE
Attachment on every email in Inbox

### ISSUE THREAD

**Issue by spreddie** [zammad/zammad#1348]
### Infos:

* Used Zammad version: 1.6.x
* Used Zammad installation source: Docker
* Operating system: Sierra
* Browser + version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)

Report an issue

There's always an attachment included in an email, which is confusing, because the attachment is typically just a copy of the email or email signature rather than an actual attachment. Is there a way to remove the attached version of the email? 

Also, would be nice Zammad could interpret formatting so it wouldn't appear as attachments. 

### Expected behavior:

* Only show attachment if a separate file is included. 

### Actual behavior:

* There's always an attachment, usually just a web version of original email. 

### Steps to reproduce the behavior:

* receive and open email -- looks like so: 

![image](https://user-images.githubusercontent.com/16157606/29431032-88c07502-8364-11e7-8ce6-fbbf3435fb38.png)

**Comment by hanneshal** [comment]
Hi @spreddie,

we actually do this on purpose. Zammad tries to deliver all infos the UI. But unfortunately there are so many strange formats out there that (at the moment) we can not guarantee to display everything correct. 
Thats the reason why every mail is viewable in it's original HTML (if delivered) format. 
So right now, it's needed and we can't remove it. 

regards
