### ISSUE TITLE
No email notification to admins 

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#1357]
Hi, 
Recently, I have noticed there zammad is not sending anymore email notifications to admins, when a ticket is created. Beforehand, per each update and ticket creation zammad sent an email notification to the admin.
The current triggers are as follows:

<Auto-owner of ticket received by @example1>
---conditions:
--state is new, open, pending close, pending reminder
--group is exampl1
--type is email
---execute
--owner specific-user user1

<Auto-owner of ticket received by @example2>
---conditions:
--state is new, open, pending close, pending reminder
--group is exampl2
--type is email
---execute
--owner specific-user user2
Both of user1 and user2 are receiving notifications propserly but admins cannot receive it even no notification anymore on the zammad portal. While, in three days ago admis received email and zammad notifications. Since two weeks ago, I didnt change any of the triggers and except these two triggers all other defaults are disabled.

Im using zammad 1.5.x on centos operating system.

**Comment by hanneshal** [comment]
Hi @hamzehmohammadnia,
we tried to reproduce this, without success. Can you please create an online instance and try to reproduce this behaviour? 

Please check the following:
- Permissions for the admin user
- Valid Email for admin users (in Zammad)

Question: Can you temp. disable those two user specific triggers and test if the admins are receiving notifications again?

regards

**Comment by hamzehmohammadnia** [comment]
Hi @hanneshal,
Sorry for late reply. I have dunno how to reproduce it online....
I have checked admin permission and also backups, they were the same; all the admins could receive email notifications of newly  created tickets but after sometime suddenly stopped. I have validated email address of zammad accounts by testing other users and assigning ticket to admins, both worked fine for those assigned tickets. But not to receive email notifications of newly created tickets. Even there is no notification on zammad portal, only on the right panel, we can see some tickets are recently created, but no notification at the bird logo.

Best,

**Comment by hanneshal** [comment]
Hi @hamzehmohammadnia,

this usally means that there is a problem with the scheduler or the websocket server. 
But this can't be user related. 
Have tried to restart your Zammad services all together? 

Have upgrade to 2.0 already, there were some improvements for some of the related components.

regards

**Comment by hanneshal** [comment]
Closed.
Please reopen when this issue still exists in 2.0.
