### ISSUE TITLE
How to change the default port 3000 ?

### ISSUE THREAD

**Issue by Netsky349** [zammad/zammad#1360]
Hello all,

I just have a question ;) I want change default port 3000 to 80 or 443 but i don't find this information on the documentation. how to made it ?

Thanks for your help

### Infos:

* Used Zammad version:  1.5.x
* Operating system: redhat
* Browser + version: chorme last version

**Comment by hanneshal** [comment]
Hi,

please see: https://github.com/zammad/zammad/issues/1125 or https://github.com/zammad/zammad/issues/592
both issues are slightly different but one may fit your needs.

May I ask why you want to change the port?

regards

**Comment by monotek** [comment]
Rtfm ;-)
https://docs.zammad.org/en/latest/appendix-configure-env-vars.html

But you should not use it to run on ports 80 or 433. Use nginx as reverse proxy for this. Privileges ports should not work anyway as this ports can only used by root user and Zammad has its own user.
