### ISSUE TITLE
Calendar: ICAL sources are not updated after 3 days

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#1361]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04

### Expected behavior:

If I use an ICAL calendar as source for holidays it should be updated on a regular basis (like 1d or so)

### Actual behavior:

Seems like the ICAL calendar is read once (when you save it) an then never again

**Comment by martini** [comment]
Hi @hiaz 

the ICAL feeds should get updated every 24 hour. There is a job here:

https://github.com/zammad/zammad/blob/stable/db/seeds.rb#L5543

I'll test it right now.. but this are the same methods as it is on save action....

 -Martin

**Comment by hiaz** [comment]
Hi @martini,

I deleted a test-holiday and waited 3 days if it will "disappear" in the zammad calendar view. It did not. Maybe it is only a "display"-bug?

Regards,
Mathias

**Comment by martini** [comment]
@hiaz Thanks for investigation. There is a internal cache, if the ICAL url has not changed only all **5** days a new sync is done. 😯 

https://github.com/zammad/zammad/blob/develop/app/models/calendar.rb#L195

and 

https://github.com/zammad/zammad/blob/develop/app/models/calendar.rb#L155

In the past we thought only static ical feeds are used (like google holidays). So the 5 day interval would be ok. But if you use an own maintained ICAL feed it would be better to have it every day.

**Comment by martini** [comment]
Changed ttl time from 5 days to 1 day for fetching ical feed again.
