### ISSUE TITLE
Calendar: ICAL ignores recurring appointments/events

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#1362]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04

### Expected behavior:

If a holiday, like the famous 24.12., is every year on the same day it is easy to crate a recurring instead of a single appointment for it. Zammad should treat recurring appointments the same way as single appointments.

### Actual behavior:

Zammad seems to ignore recurring appointments completely.

**Comment by martini** [comment]
It's implemented now. Have fun. 😆

**Comment by hiaz** [comment]
That was incredibly fast. Wow. Thank you!
