### ISSUE TITLE
E-Mail Channel - Ignored Messages are deleted from inbox

### ISSUE THREAD

**Issue by MNobis** [zammad/zammad#1365]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: docker-compose with dockerfiles
* Operating system: Ubuntu 16.04 LTS
* Browser + version: not relevant

### Expected behavior:

In the E-Mail channel settings is a filter specified to ignore messages from monitor@example.com
Emails from monitor@example.com should not be processed by Zammad and remain in the inbox.

![image](https://user-images.githubusercontent.com/20224030/29668729-85804566-88e1-11e7-9513-23e682d3ff6b.png)

### Actual behavior:

Zammad does not create a ticket from the incoming monitor@example.com mail as intended, but deletes the mail from the inbox.

### Steps to reproduce the behavior:

Create a filter for a specific mail address and send a mail to the zammad channel from this address.

Is this the intended behaviour or is there a way that zammad do not process mails that are specified to ignore in the filter settings?

**Comment by hanneshal** [comment]
Hi @MNobis,

Zammad 1.5 always pulls all mails from the mailbox. The ignore flag is jut to let Zammad know if it should process this mail or drop it. 

In version 2.0 you can select, in your mailbox settings within Zammad, if you would like to keep messages (IMAP). If so, all mails will be marked as read and kept in the inbox.

WE won't change the behaviour of the ignore function and mix things up there. 
So users have two choices (in 2.0)
- keep mails, marked as unread
- get all from the mailbox and delete them

regards
Johannes
