### ISSUE TITLE
Not possible to remove organisation from customer (No information about the organization)

### ISSUE THREAD

**Issue by Linus2017** [zammad/zammad#1368]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: package
* Operating system: Debian Jessie
* Browser + version: Firefox 55.0.2

### Expected behavior:
Field organization is optional or can be left blank
* 

### Actual behavior:
Removing not possible, error message ("Please fill out this field")
* 

### Steps to reproduce the behavior:
Try to remove the entry under Settings > Branding > Organization
*

**Comment by hanneshal** [comment]
This is fixed in version 2.0 (release pending) and DEV branch.
Please see your? issue
https://github.com/zammad/zammad/issues/1165
