### ISSUE TITLE
Ticket Hook Position between RE: and the ticket subject

### ISSUE THREAD

**Issue by Linus2017** [zammad/zammad#1369]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: package
* Operating system: Debian Jessie
* Browser + version: Firefox 55.0.2

### Expected behavior:
The ticket number between the prefix RE: and the subject of the ticket, as with OTRS
(RE: [Ticket#TICKETNUMBER] Subject)
* 

### Actual behavior:
The ticket number is before the prefix RE: 
([Ticket#TICKETNUMBER] RE: Subject)

* 

### Steps to reproduce the behavior:
Reply a ticket
*

**Comment by martini** [comment]
Thanks for reporting. Just upgrade the package and it is fixed (we build on every commit).

Enjoy.
