### ISSUE TITLE
Forward complete ticket conversation

### ISSUE THREAD

**Issue by Linus2017** [zammad/zammad#1370]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: package
* Operating system: Debian Jessie
* Browser + version: Mozilla Firefox 55.0.2

### Expected behavior:
Possibility of forwarding the complete ticket conversation
* 

### Actual behavior:
I can not find a way to forward a ticket
* 

### Steps to reproduce the behavior:
Get a ticket
*

**Comment by hanneshal** [comment]
Please see 
https://github.com/zammad/zammad/issues/573
https://github.com/zammad/zammad/issues/581

regards
