### ISSUE TITLE
Using Zammad with Passenger - No route matches /api/v1/message_send

### ISSUE THREAD

**Issue by nklmilojevic** [zammad/zammad#1374]
Hi,

I'm using Zammad with Passenger on nginx. I don't know if there's any special configuration needed besides enableing passenger and setting the root to /opt/zammad/public, but everything works fine besides mail/slack notifications.

Here's the log file:

>I, [2017-08-27T15:18:18.761796 #15656]  INFO -- : Started OPTIONS "/api/v1/message_send" for my.ip at 2017-08-27 15:18:18 +0200
F, [2017-08-27T15:18:18.770661 #15656] FATAL -- :
ActionController::RoutingError (No route matches [OPTIONS] "/api/v1/message_send"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /usr/lib/ruby/vendor_ruby/rack/methodoverride.rb:22:in `call'
  /usr/lib/ruby/vendor_ruby/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /usr/lib/ruby/vendor_ruby/rack/sendfile.rb:113:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

My nginx config is:

``` server {
listen 443;
server_name my.server;
root /opt/zammad/public;
passenger enabled on;
passenger_ruby /usr/bin/ruby2.3;

**Comment by monotek** [comment]
If this is your nginx config at least the SSL configuration is not complete.

Beside that passenger is not supported by Zammad. 

The question is also, why you want to use passenger?

Passengers open source version does not support threading, like puma does.

See: https://www.phusionpassenger.com/library/config/apache/reference/#passengerconcurrencymodel
