### ISSUE TITLE
Software Integration & Schnittstellen

### ISSUE THREAD

**Issue by Django007** [zammad/zammad#1382]
Hi, Zammad sieht sehr viel versprechend aus. Macht weiter so.

Ich habe eine Anregung für euch. 

Schnittstellen zu CMDBs und ggf. zu Software Verteilung wären interessant. 

So könnte man Host und Software Status in Tickets integrieren. Der Abruf sollte entweder direkt über eine REST Api bei z.B. einem Inventarisierungs Tool. Alternativ könnte man aber auch direkt eine Verbindung zur Datenbank aufbauen und dort die Daten abholen.
Bei der Software Verteilung sieht es ähnlich aus. Hier könnte man via REST Api abfragen welche Software mit welchem Status und Revision installiert ist. Alternativ kann man sich die Angaben was installiert ist auch aus dem angesprochenen Inventarisierungstool holen.

**Comment by thorsteneckel** [comment]
Hallo @Django007 

danke für die warmen Worte 👍 

Für die Zammad Version 2.1 gibt es eine solche Integration. Du darfst gespannt sein :)

Generell gilt, dass wir Integrationen in viele Dritt-Software-Lösungen ermöglichen wollen. Auch dazu später mehr, wenn es konkreter wird. Viele Vorschläge gibt es bereits hier als GitHub Issue.

Für zukünftige Issues würde ich Dich bitten, wie in der Vorlage beschrieben, im Englischen zu verfassen. Damit sind wir offener für alle erreichbar. Allgemein sind allgemeine Vorschläge auf [unserer Mailingliste](https://zammad.org/participate) angebracht, da wir hier im Issuetracker nur konkrete Punkte angehen.

**Comment by Django007** [comment]
Hallo Thorsten,

welche Mailing-Liste soll verwendet werden? Er sagt mir ich bin nicht berechtigt ein neues Thema zu erstellen. Ich hätte noch so eins. zwei Ideen...
