### ISSUE TITLE
500 error on API integration via doorkeeper

### ISSUE THREAD

**Issue by okodo** [zammad/zammad#1383]
### Infos:

* Used Zammad version: Zammad Cloud
* Used Zammad installation source: Not own installation
* Operating system: 
* Browser + version: All browsers

### Expected behavior:

* My application redirect users to ...oauth/authorize-URL for Zammad
* User see the login page of own Zammad account
* User sign in and see the authorize page of Doorkeeper
* User gives permissions
* User will be redirected back to callback-URL from origin application with auth-Token

### Actual behavior:

* My application redirect users to ...oauth/authorize-URL for Zammad
* User see the 500 error page

### Steps to reproduce the behavior:

* If user is signed in on zammad then it all works as expected. I thing there is some trouble with redirect to login page.

**Comment by okodo** [comment]
![image](https://user-images.githubusercontent.com/13796300/30023611-d21aa7fa-9178-11e7-8911-de0fe5449edf.png)

**Comment by hanneshal** [comment]
Hi @okodo 

could you please provide your production log for this event. + / - two minutes. 

This would be helpful. 

regards
Johannes

**Comment by okodo** [comment]
No, I can not. The error is on ...zammad.com I have no access to their
server.


Am 07.09.2017 10:21 vorm. schrieb "Johannes Nickel" <
notifications@github.com>:

**Comment by monotek** [comment]
I'm pretty sure @hanneshal  is just asking for the time of the error, so he can check the logs for it...

**Comment by hanneshal** [comment]
Exactly @okodo I work at ZammadHQ so I have access to the logs. But I need an exact timestamp to look after ;)

**Comment by okodo** [comment]
@hanneshal Just now (12.09.2017 10:16 Timezone Berlin). I have registered a new test account: https://ooo-ocodo.zammad.com
If user is logged in (on zammad.com) -> success, all as expected
If user is not logged in (on zammad.com) -> error

**Comment by shihjay2** [comment]
I have also been having issues where if the user is not logged in, an error 500 shows where the expected result is to be redirected to the login page.  The error I see in the logs is 
`NameError (undefined local variable or method 'new_user_session_url' for #<Doorkeeper::AuthorizationsController:0x0000563c38b8fe50>):` 
I'm using zammad/zammad-docker-compose, version 3.2.0-13

**Comment by t-shehab** [comment]
We haven't received any complaints in this regard in the past few years. Closing for now.
