### ISSUE TITLE
Reporting on Tags

### ISSUE THREAD

**Issue by chasgames** [zammad/zammad#1384]
Hello 

On the reporting dashboard, is it possible to graph based on tags?

I think this is good way to see categorization of tickets per week/month etc.

Thanks!

**Comment by hanneshal** [comment]
Hi @chasgames ,

the core dashboard is not capable of this by default. This would require custom development. 
The reporting module of the upcoming 2.0 is capable of handling tags. But there is no dashboard integration at the moment. 

Regards
Johannes

**Comment by chasgames** [comment]
Thanks Johannes, 

This is a shame, Hope to see it in the near future. Would be a very useful stat.
