### ISSUE TITLE
can not create new ticket, console log: validation failed

### ISSUE THREAD

**Issue by NeverMin** [zammad/zammad#1385]
### Infos:

* Used Zammad version: v1.6.1 from git
* Used Zammad installation source: Source (migrate from otrs5)
* Operating system: Server 16.04
* Browser + version: Ubuntu 16.04 / Desktop Chrome 59, Firefox 55

### Expected behavior:

* create a new ticket in Zammad

### Actual behavior:

* can not create a new ticket in Zammad
![image](https://user-images.githubusercontent.com/2797432/30113279-c55783ce-9346-11e7-9735-216ea9de870f.png)

### Steps to reproduce the behavior:

1. Click + New Ticket
1. Input title, Customer and TEXT
1. Select Group, State and Priority
1. Click "Create" button

Then, Console log:
App.Model(error) validation failed application-xxxx.js:14
Object {ticket_last_customer_contact_time: "is required",
ticket_last_customer_contackt_direction: "is required"}
...

no error message in log/production.log, just info log and http/200

but, add new ticket from email and reply is ok.

**Comment by thorsteneckel** [comment]
Hi @NeverMin - This sounds like a duplicate of #1175. Could you please verify that you use the latest `develop` branch for your test?

**Comment by NeverMin** [comment]
Hi @thorsteneckel , You are right, I don't need `ticket_last_customer_contact_time` and `ticket_last_customer_contact_direction`, so delete it in `https://zammad/#system/object_manager` and restart zammad app, work fine now.

Thank you so much.
