### ISSUE TITLE
number wrap in report page

### ISSUE THREAD

**Issue by NeverMin** [zammad/zammad#1387]
Like:

![image](https://user-images.githubusercontent.com/2797432/30143883-992ebc6c-93ba-11e7-910b-5c52edace4d7.png)

fix: add `white-space:nowrap` to css style.

**Comment by thorsteneckel** [comment]
Hi @NeverMin - thanks! @mrflix will have a look. Would be great if there would be no need to patch the [third party jQuery file](https://github.com/zammad/zammad/pull/1388/files#diff-be67b2b7837d853733856e3dec5c3c1fR1694).
