### ISSUE TITLE
Question: I see you tagged version 2.x i.e. 2.1.1, is this the final release which one can install?

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1392]
I see you tagged version 2.x i.e. 2.1.1 in the commits, is this the final release which one can and is supposed install ("- Make sure to use the latest version of Zammad if possible")?
Is version 2.x already updated in here?: https://docs.zammad.org/en/latest/install-ubuntu.html

**Comment by martini** [comment]
Hi @passboltUser 

would this answer your questions?

https://groups.google.com/forum/#!topic/zammad-users/8ttDBLlO8BA

 -Martin

**Comment by passboltUser** [comment]
Thanks, I guess that anwsers my question indeed :) I'll just "wait until new stable releases are relesed" then (hopefully indeed in September).

**Comment by martini** [comment]
PS: Just one more note. Upgrading Zammad is always done automatically within updating your Zammad package.

**Comment by passboltUser** [comment]
Yep, I read that from the comment :) 

PS: Weird that you tagged 2.0.0, then 2.1.0 and 2.1.1, everything only several hours apart. Except of course, if it's supposed be that way.
