### ISSUE TITLE
Ticket chaos after updating to from Zammad 1.5 to 2.1 (develop branch) - Macros and Taskbar are damaged

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#1395]
Hi,

OK, I know that some things may get broken on the dev branch ... but what happened to me right now looks like a real issue.

Updated from zammad.x86_64 0:1.6.1-1504167646.cda16653.centos7 to zammad-2.1.1-1504885221.553dcef3.centos7.x86_64, and after the update my 7 open tickets turned into more than 380, and all showed no subject:

![zammad_1504167646](https://user-images.githubusercontent.com/3321655/30241451-be2b099c-9583-11e7-8768-f6d604eaded4.jpg)

That's not really what I've expected, so I've downgraded back to zammad.x86_64 0:1.6.1-1504167646.cda16653.centos7. Ticket count is back to normal, but the subjects in the view "Nicht zugewiesen und offen" are still gone.

![zammad_subjects gone](https://user-images.githubusercontent.com/3321655/30241462-0852f5fc-9584-11e7-944c-33e350e07ceb.jpg)

I realized that the view settings of this dashboard were completely disabled. I've cleared the caches and recreated my view settings ... hoping that nothing else got broken by this update.

**Comment by martini** [comment]
Hi @jacotec 

develop branch (will be Zammad 2.1) is updated to Ruby on Rails 5.0. I guess this is the source of this problem.

-=> Did you downgrade via RPM or did your use a backup?

I would clear the cache (rails r 'Cache.clear'), but if it's still not working. You need to use a backup (database backup) from before upgrading.

 -Martin

**Comment by martini** [comment]
One more question (to find faster what caused the issue), do you remember, did you stop the Zammad processes during the upgrade?

**Comment by jacotec** [comment]
@martini I did the up- and downgrade via repo (yum) ... so I did not stop or start anything as I'm used that the update via repo normally does anything you need including the installation of any new dependencies.

I can retry the update ... what does "Ruby 5.0" mean? Do I need to install anything else which the repo does not take care of?

**Comment by jacotec** [comment]
OK, seems I've lost all of my Makros also :-(

Need to push in the last night's update, losing some tickets of today. My stupid fault not making a snapshot before, but normally updates to not cause data loss ...

**Comment by martini** [comment]
> I can retry the update ... what does "Ruby 5.0" mean? Do I need to install anything else which the repo does not take care of?

"Ruby on Rails" is used as framework for Zammad. Including upcoming Zammad 2.0 Ruby on Rails 4.2 is used.

Current develop branch will be Zammad 2.1 which is on Ruby on Rails 5.0 framework. 

-=> You do not need to care about that. All is in the package/RPM. Normally this is totally transparent for you.

> Need to push in the last night's backup, losing some tickets of today. My stupid fault not making a snapshot before, but normally updates do not cause data loss ...

Yes. Normally updates are quite easy and no data get lost. So I'm really interested what has gone wrong this time.

**Comment by jacotec** [comment]
OK, just let me know what I should do. I can make a Snapshot, do the update, give you what you need and revert to the working version.

**Comment by martini** [comment]
Nice! It would be nice if you could do the update again but stop all Zammad processes first. Then update the RPM. Start the Zammad processes and check if all looks fine. Thanks in advance!

**Comment by martini** [comment]
@jacotec yesterday I was able to reproduce your problem. I'm working on a fix now.

**Comment by jacotec** [comment]
@martini Sounds good :-) ... so I'll stay on standby until further notice

**Comment by martini** [comment]
Fixed in develop. Upgrade is no possible without loosing Macro or Taskbar stores. 

JFI: In case of productive environments may "stable" branch would be more stress free. :) JFI: If Zammad 2.0 is release you can switch back to stable without problems (at least in the first days until develop is moving forward...).

**Comment by jacotec** [comment]
Hi @martini ,

what means "loosing Macro or Taskbar stores"? Are my Macros and Taskbar configurations lost after the update? If yes, will that be fixed until 2.0 stable is released?

**Comment by martini** [comment]
> what means "loosing Macro or Taskbar stores"? Are my Macros and Taskbar configurations lost after the update? If yes, will that be fixed until 2.0 stable is released?

No. If you update to Zammad 2.0 all is (and in the past was) fine.

Only if you updated to develop (the future Zammad 2.1 development branch) before 2017-09-09 you have temporary "lost" Macros and Taskbar infos until you updated the develop branch to a build date after 2017-09-09.

-=> Actually "lost" is the wrong word. It's still in the database, but not used (in Zammad develop branch before 2017-09-09).
