### ISSUE TITLE
Update 1.5 to 2.0 - Error 500 - Out of Office

### ISSUE THREAD

**Issue by jannheider** [zammad/zammad#1397]
### Infos:

* Used Zammad version:  2.0
* Used Zammad installation source: package
* Operating system: CentoOS 7
* Browser + version: Any

### Expected behavior:

* After Update from 1.5 to 2.0 on stable branch Zammad schuld run without errors :)

### Actual behavior:

* Updating from 1.5 to 2,0 shows error 500 (column "Out of office" does not exists)

### Steps to reproduce the behavior:

* update to 2.0

![bildschirmfoto 2017-09-11 um 08 43 33](https://user-images.githubusercontent.com/17439988/30261764-5fd66e6c-96ce-11e7-883f-e099c8051264.png)

**Comment by martini** [comment]
Did you restart the Zammad processes?

**Comment by thorsteneckel** [comment]
We had some similar issues after introducing the foreign keys. Could you please check what the command `rake db:migrate` prints out. If there is nothing printed please provide the `log/production.log` file.

**Comment by jannheider** [comment]
Yes.

Just saw that on packager.io the version is on commit d5f7609 but you fixed it with commit 714cede. ?
So we have to wait for packager.io :D

**Comment by jannheider** [comment]
@thorsteneckel we rolled back to version 1.5 sorry, can't provide logs...

I'll wait till packager.io is on commit d6e5e1e and then try again.

**Comment by mrcschilling** [comment]
I'm having the same problem. I added the columns manually, login is working, but now I get this error:
`{"error":"ERROR:  column overviews.out_of_office does not exist\nLINE 1: ...id\" IN (1, 2) AND \"overviews\".\"active\" = 't' AND (\"overviews...\n                                                             ^\n"}`

**Comment by martini** [comment]
@jannheider https://github.com/zammad/zammad/commit/d6e5e1eaee55fae8f20f8d5ba02a7f455daa5a85 is build https://packager.io/gh/zammad/zammad/refs/stable 

Many thanks for feedback!

**Comment by thorsteneckel** [comment]
@mrcschilling - please never access or change the database directly. This will break your system. However please check for the things I wrote in my last post.

**Comment by mrcschilling** [comment]
@thorsteneckel - Yeah I noticed, all is working as expected after updating to d6e51e, thanks

**Comment by martini** [comment]
Thanks for feedback! ❤️ @mrcschilling

**Comment by jannheider** [comment]
@martini 
I can confirm, with d6e5e1e it is working now.

**Comment by martini** [comment]
I love you guys!
