### ISSUE TITLE
Update Zammad 1.5.x to 2.0 under Debain 8

### ISSUE THREAD

**Issue by mr2017x** [zammad/zammad#1399]
Hi Guys,

seeing some major improvements i want to upgrade Zammad to V2.0. Using Debian 8 with reps but didn't see a possibilty to do it at the moment? Are the reps not up2date or are you just switching over to a manual way of upgrading?

Thanks

Chris

**Comment by monotek** [comment]
2.0.0 packages are available at: https://packager.io/gh/zammad/zammad/refs/stable

Maybe you missed: https://docs.zammad.org/en/latest/appendix-repo-file.html
