### ISSUE TITLE
Change language system e-mails

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1400]
Hihi 😄 

I just updated to the new version 2.0. And it's pretty cool. I totaly love the role management!

I just noticed that my automatically system e-mails, like password reset, are in english even though my zammad-system language is set to german.
For the "auto reply" on new tickets, there is a Trigger which I can change, but none for the other system mails.

Greetings

**Comment by babakkazemi** [comment]
@MamoulianDelacroix Email Templates are still on the filesystem in .erb-Files - see #718

**Comment by MamoulianDelacroix** [comment]
@babakkazemi Thanks, that's nice to know. Now I can customize my emails.
But strangley my zammad uses the English templates instead of the German ones.
Do you have idea why, because my whole zammad-system is in German as well.

**Comment by babakkazemi** [comment]
@MamoulianDelacroix see #401

**Comment by MamoulianDelacroix** [comment]
@babakkazemi Great thing! 😃 
That helped a lot. Thank you very much.
Now everything ist fine again.
