### ISSUE TITLE
Question: multiple e-mail addresses

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1401]
Hello again ^^

a short question, which I wasn't able to find in the documentation.
Is it possible for a user to have multiple e-mail addresses?

Greetings

**Comment by thorsteneckel** [comment]
Hi @MamoulianDelacroix - we are working on a solution for [multi identifiers](https://github.com/zammad/zammad/issues/613) but Zammad currently allows only one email address per user.

**Comment by danielduchon** [comment]
hi @thorsteneckel.

I know thats an old issue but is there a timeline when this feature will be added? We have a lot of users with multiple e-mail-adresses. In Zendesk there is also a feature called "merge user". with it you can merge multiple accounts to one and also merge the emailaddresses and tickets. I think this would be the next step to reduce "junk". What do you think?

**Comment by thorsteneckel** [comment]
Dear @danielduchon ,

first of all, many thanks for your participation on the Zammad open source project.

Not usual as with proprietary software, we finance Zammad through service. So it's less money we have at our disposal to push Zammad.

If you would like to support Zammad, you can do so via Zammad Support: https://zammad.com/pricing#selfhosted

For all issues it is generally important that we tag an issue as soon as it is included in a release. This means that manual enquiry only minimizes the available resources but not the speed of implementation.

Thank you for your understanding.

Please also note that this is a closed duplicate. Please use open issues (#613 and #531) to **provide information**. We won't answer status requests. It's transparent what we're working on in [the Workflow project](https://github.com/zammad/zammad/projects/3).
