### ISSUE TITLE
Multiple display of groups in overview

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#1402]
* Used Zammad version: 1.6.1, update to 2.0.0
* Used Zammad installation source: packager.io deb
* Operating system: Debian 8
* Browser + version: Chrome, Firefox, Edge, IE

sorry, this is a duplicate of #1064, but seems not to be fixed for us

### Expected behavior:

* In overview "my assigned tickets" every group should only be displayed once

### Actual behavior:

* In overview "my assigned tickets" some groups are displayed twice (see also #1064, opened new issue as I couldn't reopen #1064)

### Steps to reproduce the behavior:

* open overview "my assigned tickets"

**Comment by babakkazemi** [comment]
as soon as a ticket is updated (by customer or agent), it moves into the second displayed instance of the group it is in

**Comment by hanneshal** [comment]
duplicate of #1064 , reopened the old issue
