### ISSUE TITLE
Reply to in email is not considered

### ISSUE THREAD

**Issue by Linus2017** [zammad/zammad#1411]
Infos:

    Used Zammad version: 1.5.x
    Used Zammad installation source: package
    Operating system: Debian Jessie
    Browser + version: Firefox 55.0.3

Expected behavior:
The email address under "Reply to" is considered
*

Actual behavior:
Reply to in email is not considered. The original sender address is used. I can not choose one, because I can not see if a Reply to specification was made.
*

Reply to a mail ticket, with "Reply to" field
*

**Comment by hanneshal** [comment]
Hi @Linus2017 

this works just fine in the latest release.

<img width="1035" alt="helpdesk" src="https://user-images.githubusercontent.com/804939/30349358-082feb16-9813-11e7-8df7-26d941aec2f6.png">

Please update to the latest stable version (2.0)

Regards.
Johannes

**Comment by Linus2017** [comment]
Hi @hanneshal,  

after the update works the desired function. Many Thanks!

I still have two questions:
1. The function only goes for all nine mails that have been received after the update?
2. How can I install Zammad on a Uberspace account?

**Comment by hanneshal** [comment]
@Linus2017 Sorry for the delay.
1) Correct, it just works for new tickets.
2) I don't think that is possible du to the RAM limitations on the shared host. You should contact hallo@uberspace.de

regards
Johannes
