### ISSUE TITLE
After update to 2.0: Postmaster Filter not working

### ISSUE THREAD

**Issue by Johannes-GitHub** [zammad/zammad#1413]
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: (source, package, ...) Package
* Operating system: Ubuntu 16.04 LTE
* Browser + version: Chrome latest

### Expected behavior:

eMail with text "[Success]"will be sortet in special Groups -> ToDo

### Actual behavior:

eMail will sortet to customer

### Steps to reproduce the behavior:

Filter not working under Manage -> E-Mail -> Filter -> Rule 
![image](https://user-images.githubusercontent.com/24590878/30362086-7fbcc6c6-985a-11e7-94b2-37f9447491df.png)

**Comment by hanneshal** [comment]
Hi @Johannes-GitHub 

can you explain or even post a ticket history what is exactly happening?
If you can post an excerpt of your production.log which shows the ticket create event +- 2 Minutes or so... this would be really helpful.

regards 
Johannes

**Comment by thorsteneckel** [comment]
Closing, no feedback.
