### ISSUE TITLE
Add elasticsearch config to packagers postinstall steps

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#1414]
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: DEB/RPM
* Operating system: All

### Expected behavior:

* As Elasticsearch is a installation requirement the packager.io postinstall script should configure Elasticsearch.

Add also an option to disable Elasticsearch on the local host for people using it on remote server.

### Actual behavior:

* Elasticsearch is installed but not configured

### Steps to reproduce the behavior:

* Install from Package

**Comment by hanneshal** [comment]
Note: ES will be required for reporting.

**Comment by monotek** [comment]
Fixed in: https://github.com/zammad/zammad/commit/6fda64c7f66f9314ac0da3694ea6167855d76117
