### ISSUE TITLE
Removing Tickets from Sidepanel

### ISSUE THREAD

**Issue by semaf** [zammad/zammad#1417]
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: Upgrade from 1.5.x to 2.0.x
* Operating system: Ubuntu 16.04
* Browser + version: Opera

### Expected behavior:
By clicking the close X button on the sidepanel it should remove the Ticket.

### Actual behavior:
Closing any ticket give the message: "Inhalte des Tabs haben sich geändert, wollen Sie diese Änderungen wirklich verwerfen?"
This happens even if nothing has been changed inside the ticket content. Even if you update the Ticket, the message is still available and will not remove the ticket.

### Steps to reproduce the behavior:
Upgrade Version from 1.5.x to 2.0.x and try to close from the left sidepanel the tickets with the X button.

**Comment by NeverMin** [comment]
Hi @semaf , if you install from source(not .deb), make sure run `rake assets:precompile`, did you?

**Comment by semaf** [comment]
Nope, did not. I try it now with an error, should I run the command inside a folder?

sudo rake assets:precompile
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)

**Comment by semaf** [comment]
Run the command inside the /opt/zammad folder

semaf@server:/opt/zammad$ sudo rake assets:precompile
rake aborted!
LoadError: cannot load such file -- bundler/setup
/opt/zammad/config/boot.rb:3:in `<top (required)>'
/opt/zammad/config/application.rb:1:in `<top (required)>'/opt/zammad/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by martini** [comment]
> Nope, did not.

@semaf I recommend you to use the Zammad package for Ubuntu. It's including all ruby/gem dependencies. You not need to solve this kind of issue. Just ready to go.

**Comment by martini** [comment]
JFI: After initial setup with the Zammad package for Ubuntu you can connect to your existing database (just clear the cache again "zammad run rails r 'Cache.clear'").

**Comment by semaf** [comment]
Reinstalled Zammad from the source but Problem still not solved. Cache has been cleared with "`zammad run rails r 'Cache.clear'`"

**Comment by semaf** [comment]
Great action. Problem not solved but closed!

**Comment by hanneshal** [comment]
@semaf First of all we can close issue as we want. If we believe this is an issue with your basic installation / setup, which is not related to Zammad, we will close it. 
This is an open source project where we put our efforts in. And you wont believe how many people mess up their systems and call us for support just because they "just changed a small thing in the database" or "modified a small file". 
So please watch your words. There are real people behind this project who do their best. 

btw: 2.0 is working fine on a very large installed base. If your issue would occur on more than one installation we wouldn't sleep until we pushed a fix to the upstreams. See #1398 for example.

To your problem. 
Can you post your production.log around the time you get this error. Please not just two lines, if you can send us the whole log to support@zammad.com

regards
Johannes

**Comment by semaf** [comment]
@hanneshal Great! How did you believe without to know and listen, if the Problem is solved or not? I did NOT CHANGE anything on Database or the File structure. 

I know that is an Open Source Project and I do not wait a support, just **helping you out with possible bugs!** 

And believe me, I watch my words and respect others words and others should respect my words too.

I will post you the File and you take a look there too. I could not find anything about it.

**Comment by hanneshal** [comment]
I see... a simple: "Ok I send you the logs, Thank you" was too much to ask for :D
Btw, that @martini closed the ticket was a mistake. He simply hit the wrong button. Sorry for the mistake. But like I wrote before.. 
![ed6012d9a3d83b4144b73471bdafc1944c7479ad2858c67dac0d6a7b21ae8039](https://user-images.githubusercontent.com/804939/30489448-828ca9fa-9a37-11e7-8d1b-b6c58acd7374.jpg)

Back to your case:
If you can please provide also the console log of you browser for the following events:
- Try to close a ticket
- Try to reset the ticket values
- Try to update the ticket
- Try to close a ticket again

If possible / available we would like to have a list of the loaded ressources+http status code like shown here.
![network](https://user-images.githubusercontent.com/804939/30489351-542de4a2-9a37-11e7-84d9-70f876d67d69.png)

A screenshot (anonymised) of the whole ticket would be also very interesting. Especially the ticket detail panel on the right. 

![changenote](https://user-images.githubusercontent.com/804939/30488329-4a33443e-9a36-11e7-920a-935bc88f4d3a.png)

Thank you for helping us to make Zammad better. 

regards 
Johannes

**Comment by thorsteneckel** [comment]
No feedback provided. Assuming this is closed but can be an misunderstanding 🤓 However, since there was no reporting of a similar issue maybe the https://community.zammad.org is a better place for this anyway.
