### ISSUE TITLE
LDAP sync change admin members

### ISSUE THREAD

**Issue by tesaorif** [zammad/zammad#1419]
### Infos:

* Used Zammad version: 
* Used Zammad installation source: .deb
* Operating system: Ubuntu 16.04
* Browser + version: Firefox

### Actual behavior:

I have two user in the same OU as our agents who need admin right. I  tried to mannualy add them to the group wich work fine but it seems that every time Zammad make an LDAP request to our it put the two user back in the Agent group.

### Excepted behavior:

* Keep user in the same group regardless of their OU

**Comment by thorsteneckel** [comment]
Hi @tesaorif. Yeah, that's right. If LDAP is used, it is the leading source of permissions. This means that changes will be overwritten as soon as the next sync is running. This can be counteracted by creating a corresponding group for administrators in the LDAP. This LDAP group must then be mapped to the Zammad `Admin` role.

**Comment by tesaorif** [comment]
@thorsteneckel Thank you for your answer.

Could there be a way to add the following ruby command to a script ?:
```
u = User.find_by(email: 'you@example.com')
u.roles = Role.where(name: ['Agent', 'Admin']) 
```

If yes i could simply create a crontab but my ruby skill aren't really great.

Thank you for your time.

**Comment by thorsteneckel** [comment]
Just name it *something*.rb and place it in your Zammad folder. After that run it with `zammad run 
 rails r something.rb` 👍 

The code should look something like this:

```ruby
User.find_by(email: 'you@example.com').update!(
  roles: Role.where(name: ['Agent', 'Admin'])
)
```
