### ISSUE TITLE
503  Slow Down

### ISSUE THREAD

**Issue by TheRealEscimo** [zammad/zammad#1421]
Hi,

Trying to install Zammad using Ubuntu 16.04 and the repo, but apt reports 503 Slow Down when trying to fetch the install packages.
Issues with the amazon bucket?

Err:1 https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu 16.04/main amd64 zammad amd64 2.0.0-1505227273.eb5fe7fd.xenial
  503  Slow Down
E: Failed to fetch https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu/pool/main/zammad_2.0.0-1505227273.eb5fe7fd.xenial_amd64.deb  503  Slow Down

**Comment by monotek** [comment]
Not in our hands as we use packager.io service.

**Comment by TheRealEscimo** [comment]
It is fixed now - So packager.io service is fully working again.
