### ISSUE TITLE
OpenID Connect support?

### ISSUE THREAD

**Issue by lpar** [zammad/zammad#1423]
How hard would it be to add OpenID Connect authentication support via (say) [omniauth-openid-connect](https://rubygems.org/gems/omniauth-openid-connect) Gem?

I'm guessing I could probably get it working if I installed Zammad from source instead of RPM, added the appropriate Gem, and altered `config/omniauth.rb`, but obviously it'd be better to do it properly. Any pointers?

**Comment by muhammadn** [comment]
It is possible since i had just worked on Auth0 integration with OmniAuth but i see the gem is not maintained for quite some time. 

Should i move forward and implement this? @hanneshal

**Comment by muhammadn** [comment]
I think we should skip this implementation especially for security things like authentication/authorization as the gem mentioned by @lpar is no longer maintained.

**Comment by lpar** [comment]
OpenID Connect is really just a subset of OAuth. I've implemented it in Go using the language's standard OAuth2 library calls. Looks like [other people have done the same](https://github.com/sdoxsee/omniauth-oidc) with OmniAuth.

**Comment by lpar** [comment]
After a couple of afternoons of hackery, I've managed to get OpenID Connect working with our provider, using only a modified version of the generic OAuth2 driver from `vendor/lib/oauth2_database.rb` and no new Gems or libraries.

My question is, how can I turn this into something which is supportable in the long term and won't get wiped out the next time there's a Zammad release? What's the procedure for using a custom OmniAuth provider?

Also, is there any easy way to customize the login page in a way which won't get overwritten? I'd like to change the label on the button from "OAuth2", and hide the login and password fields behind some sort of "Admin" button, or else we'll get endless people trying to use their OpenID credentials in those fields.

**Comment by lpar** [comment]
Obviously I'd be happy to contribute the code too, so Zammad could be upgraded to support OpenID Connect, but it'd need some work to make it something generally useful. Changes I think would be needed:

 1. A way to provide the OpenID Connect provider's X509 certificate via the Zammad admin section, for JWT signature verification when decoding the `id_token`. Right now I've got it inlined as a string block in the code.
 2. A set of fields for specifying which fields in the id_token map to each field in the [OmniAuth hash schema](https://github.com/omniauth/omniauth/wiki/Auth-Hash-Schema), because of course that's not standardized. (This would be useful for OAuth2 as well, for the same reasons.)
 3. Maybe a selector for the JWT algorithm. I've only ever seen `RS256` used, but other people might use something else.
 4. Better error-checking.

Let me know.

**Comment by thorsteneckel** [comment]
Closing now since this haven't got any traction and has been stale for quite a while. I think there is another OpenID issue but I can't find it. However, if you still think OpenID is required please refer to the [community board](http://community.zammad.org/) and let us know about your use case. Closing this one now.

**Comment by honzapatCZ** [comment]
I think adding OpenID Connect is as good as adding SAML, not all IDPs provide SAML not all provide OIDC, the good thing about OIDC compared to OAuth2 is it generalizes the endpoints and most importantly defines the auto discovery of endpoints, keys, etc. In that manner adding OIDC would be as easy as adding SAML. Ie: auth, token, userinfo, keys url or discovery endpoint, scopes, id + secret, all relevant info can then be get at the user endpoint(oidc again specifies the naming convention for email, name, etc....)

**Comment by MrGeneration** [comment]
Please don't hijack old, closed and technical question issues. 
If you want a specific feature, please post a feature request on the community (https://community.zammad.org) if not already available. 

If there's already a thread existing, give a heart to the first article to help us measure the need of the community.
