### ISSUE TITLE
Zammad 2 has no Hebrew language

### ISSUE THREAD

**Issue by DjMagicFingers** [zammad/zammad#1427]
### Zammad version 2.0.x:

After upgrading to Zammad 2, there is no Hebrew language to select at the profile dialouge.

![image](https://user-images.githubusercontent.com/32017425/30513072-11a40696-9b06-11e7-8052-d1131be87207.png)

Zammad is installed on a Centos 7 linux server, updated daily and been accessed from Different browsers, mainly Chrome on Windows.

**Comment by hanneshal** [comment]
Hi @DjMagicFingers 

can please run those two commands:

zammad run rails r 'Locale.load'
zammad run rails r 'Translation.load'

And reload your web app in the browser. 

This should help

regards

**Comment by DjMagicFingers** [comment]
Thank you very much!
It works 😊
Zammad now speaks Hebrew as well…

Best regards,




Amir Inbar, ceo
SRV We Know IT
Cellular: +972.54-2210001
4th Hateena st. Mazkeret Batya
Israel
Support +972.72.2788080
amir@srvit.co.il<mailto:amir@srvit.co.il>
www.srvit.co.il<http://t.sidekickopen63.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs4X9X3sVfDnr41pgM8qVRrZFz56dPGGf35t9BP02?t=http%3A%2F%2Fwww.srvit.co.il&si=5169207794466816&pi=935815ec-0af2-4bc5-a165-30706241e083>


[SRV - Logo]<http://www.srvit.co.il/>
