### ISSUE TITLE
Kayako Helpdesk

### ISSUE THREAD

**Issue by fixlair** [zammad/zammad#1428]
Hello,

Kayako helpdesk changed a lot during the last 3 years, it would be great to have a Kayako to Zammad exporter to get a good alternative

**Comment by arwed** [comment]
+1

**Comment by giorgiorivolta** [comment]
+1

**Comment by thorsteneckel** [comment]
Locking conversation. There is no new input. +1 and requesting comments create noise and distraction. We are working hard on the next upcoming/most requested features and projects of our support customers. If you want to state your interest in the feature and give valuable input please give the initial post a 👍 reaction and we are able to evaluate it. We will lock all distracting issues from now on. Thanks for your understanding.

**Comment by mgruner** [comment]
Implemented via dd30b1828593c8ab26cefe6b65d4d0a8dd34df24.
