### ISSUE TITLE
Port 3000 not available after upgrade to ver 2

### ISSUE THREAD

**Issue by DjMagicFingers** [zammad/zammad#1430]
### Infos:

* Used Zammad version: 2.0.x
* Operating system: Centos 7
* Browser + version: Chrome latest

### Expected behavior:

* Keep port deffinision through the upgrade proccess

### Actual behavior:

* After upgrading to ver 2.0.x port 3000 is not accessible and Zammad is answering port 80 instead.
* Running:

`zammad config:set ZAMMAD_RAILS_PORT=3000
zammad config:set ZAMMAD_WEBSOCKET_PORT=6042
systemctl restart zammad`

did not help.

### Steps to reproduce the behavior:

* Upgrade zammad 1.5 (latest) running on port 3000 to ver 2.0.x

**Comment by monotek** [comment]
This is wanted behavior. 
For security reasons its not possible to access the zammad services in their ports directly.
Somebody could us this to bypass you https config for example.

**Comment by PatrickGoenner** [comment]
How can I config port 3000 under debian after updating to version 2?

**Comment by martini** [comment]
@PatrickGoenner what do you want to configure with port 3000? To bind not on localhost:3000 but in 0.0.0.0:3000?

As @DjMagicFingers wrote, just open a console as root and enter:

```
zammad config:set ZAMMAD_BIND_IP=0.0.0.0
zammad config:set ZAMMAD_RAILS_PORT=3000
zammad config:set ZAMMAD_WEBSOCKET_PORT=6042
systemctl restart zammad
```

See also: https://docs.zammad.org/en/latest/appendix-configure-env-vars.html

**Comment by PatrickGoenner** [comment]
I want to bind on localhost:3000, as it is in version 1.5. I think I have to enter on a console "rails s -p 3000".

**Comment by martini** [comment]
Note: Zammad 1.5 and lower did bind to 0.0.0.0:3000. With Zammad 2.0 and higher the bind address is localhost:3000.

We did the change for security reasons.

If you have installed Zammad 2.0 and want to have the same behaviour as it was in Zammad 1.5 and lower, just enter the following:

```
zammad config:set ZAMMAD_BIND_IP=0.0.0.0
zammad config:set ZAMMAD_RAILS_PORT=3000
zammad config:set ZAMMAD_WEBSOCKET_PORT=6042
systemctl restart zammad
````
