### ISSUE TITLE
Rocket.chat integration as Channel

### ISSUE THREAD

**Issue by thebennos** [zammad/zammad#1432]
Related to this. (sorry not allowed to post there)
https://github.com/zammad/zammad/issues/878

Made some research on this that could help. 
Rocket Chat has a good API. 
https://rocket.chat/docs/developer-guides/rest-api/

Rocket.Chat is fully featured Chat App with a lot of features and also a LIVE Chat / Support Chat widget. 

I think the Integration as Channel in Zammad can be done over 2 ways. 
There are Webhooks (already possible to integrate with some CRM systems)
and 
The REST API. 

The rocket.chat live widget message are posted to a channel in rocket.chat . 
Over the webhook or the REST Api it should be possible to integrate it zammad and get the posted message in the rocket.chat channel and also to post an answer back.

**Comment by hanneshal** [comment]
Hi @thebennos 

right you are not allowed to post there because we locked the thread ;) 

We are aware of the API, but we don't have resources left to implement it.

I close this issue here and add it as a reference.

**Comment by himbeere** [comment]
Just tested the slack integration with rocketchat. Works too.
![bildschirmfoto 2018-02-23 um 13 48 31](https://user-images.githubusercontent.com/631865/36594880-487ecd5a-18a0-11e8-9823-96fc3dd09dfe.png)

**Comment by Bart1909** [comment]
> Just tested the slack integration with rocketchat. Works too.
> ![bildschirmfoto 2018-02-23 um 13 48 31](https://user-images.githubusercontent.com/631865/36594880-487ecd5a-18a0-11e8-9823-96fc3dd09dfe.png)

Can you please tell me, how to set up this integration. I tried it, but no success...

**Comment by Routhgen** [comment]
> Just tested the slack integration with rocketchat. Works too.
> ![bildschirmfoto 2018-02-23 um 13 48 31](https://user-images.githubusercontent.com/631865/36594880-487ecd5a-18a0-11e8-9823-96fc3dd09dfe.png)

How did you make it working? Zammad is sendind payload, but rocket chat is expecting to receive JSON data. So this is not working...

**Comment by Bart1909** [comment]
> > Just tested the slack integration with rocketchat. Works too.
> > ![bildschirmfoto 2018-02-23 um 13 48 31](https://user-images.githubusercontent.com/631865/36594880-487ecd5a-18a0-11e8-9823-96fc3dd09dfe.png)
> 
> How did you make it working? Zammad is sendind payload, but rocket chat is expecting to receive JSON data. So this is not working...

For me it is now working.
I simply created an incoming web hook in rocket.chat and inserted the url in zammad for the slack integration. As Username i chose 'Zammad' and left Channel and Icon Url empty

**Comment by Routhgen** [comment]
After few tries it's working ok.
Check this https://github.com/RocketChat/Rocket.Chat/issues/12072
