### ISSUE TITLE
after setting ticket owner by trigger, the owner is not set in the ticket sidebar

### ISSUE THREAD

**Issue by gwingend** [zammad/zammad#1434]
### Infos:

* Used Zammad version: 1.6.1 pkg-idoit
* Used Zammad installation source: (source, package, ...)
* Operating system: debian8
* Browser + version: chrome

### Expected behavior:
ticket information in right sidebar should be changed when trigger is changing ticket information.

### Actual behavior:
ticket information in ticket sidebar is not changed after trigger is changing ticket

### Steps to reproduce the behavior:
1. create a trigger as described in #1433.
2. create a new ticket without selecting owner of the ticket
![image](https://user-images.githubusercontent.com/30232713/30520732-4a61395a-9bb4-11e7-917d-b799a7bd6906.png)
3. as you can see in the middle of the screenshot the owner is changed. ("Der Bearbeiter für Ticket (Trigger setting the wrong owner) hat sich geändert" -> "nicole.braun@zammad.org")

But in the ticket section on the right side of the screen you can see, that the ticket owner is still empty.

Even if you close the ticket tab, search for the ticket and open a tab with the ticket, the owner is still empty.

*

**Comment by muhammadn** [comment]
My guess is that when you are creating a new ticket, you need to assign the "State" to *New* and not *open* which is the default.

**Comment by gwingend** [comment]
could confirm that with v2.0x.
Seems to be a problem with 1.6.1 pkg-idoit.
But I will give it another try to double check.
