### ISSUE TITLE
New Install of Zammad 2.0 on CentOS 7 Produces nginx Default Landing Page.

### ISSUE THREAD

**Issue by etkelley** [zammad/zammad#1436]
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: RPM package
* Operating system: CentOS 7 (clean install from DVD)
* Browser + version: chrome

### Expected behavior:

* After installing Zammad via RPM package, browsing to http://[server IP] should produce Zammad setup page.

### Actual behavior:

* After installing Zammad via RPM package, browsing to http://[server IP] produces the default nginx landing page.

### Steps to reproduce the behavior:

* "sudo yum -y install zammad" on clean install of CentOS 7.

**Comment by monotek** [comment]
This is standard nginx / Apache behavior.

Just edit the nginx config to fit your servername/domain or use "localhost" to access Zammad.

**Comment by etkelley** [comment]
Can you be more specific? This is a just a small lab environment. There is no FQDN to set in the zammd.conf file. I tried setting the IP address instead, but this results in a "502 Bad Gateway" error.

**Comment by monotek** [comment]
You can also set a random servername in nginx config and  also put it in the hosts file of your client.

If it's to hard for you maybe a hosted Zammad would be a solution. Just visit: https://zammad.com/pricing

**Comment by etkelley** [comment]
Entering a random servername in the config and setting the hostname in the client's host file produces the exact same results.

I understand this is likely an nginx config issue, but I raise the point because the Zammad documentation is either incorrect, or the package is compiled incorrectly.

**Comment by etkelley** [comment]
Thanks for your help.
