### ISSUE TITLE
Rewrite URLs

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#144]
It would be great if URLs like mailto:// can be rewritten  to create a new ticket, open link etc.

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
