### ISSUE TITLE
Exchange Integration SSL Error with self-signed root certificate authority 

### ISSUE THREAD

**Issue by Felix1356** [zammad/zammad#1442]
* Used Zammad version: 2.0.x
* Used Zammad installation source: /stable/installer/ubuntu/16.04.repo
* Operating system: Ubuntu 16.04 LTS
* Browser + version:  Firefox 55.0.3

### Expected behavior:
Setup Exchange Configuration not sucessfull

### Actual behavior:
Setup Exchange Configuration Connection SSL Connect Error
Error Message: SSL_connect returned=1 errno=0 state=error: certificate verify failed

### Steps to reproduce the behavior:
My company uses a AD certificate authority.
The Exchange 2013 Servers are using a self-signed certificate from this root ca.
I put my root ca as a crt file to the /usr/local/share/ca-certificates folder
update-ca-certificates --fresh
I can see Replacing debian:MyRootCa.pem
Done.

Why rails isn't using the local openssl root ca files?

Thanks
Felix

**Comment by babakkazemi** [comment]
@Felix1356 have you verified the certificate chain (Exchange -> maybe some intermediate -> Root CA) is complete and verifies ok on your zammad machine?

**Comment by thorsteneckel** [comment]
Hi @Felix1356 - can you provide a screenshot in which step of the configuration wizard this is displayed?

**Comment by EDVLeer** [comment]
As I've got the same Problem here's the Screenshot

![zammad-exchange](https://user-images.githubusercontent.com/14330836/30700383-b2d86662-9ee7-11e7-8c34-04739641eabe.JPG)

**Comment by thorsteneckel** [comment]
Thanks @EDVLeer !

Just for my record:

[Autodiscover](https://github.com/WinRb/autodiscover):
```ruby
client = Autodiscover::Client.new(...)

# Ignore SSL Errors
client.autodiscover(ignore_ssl_errors: true)
```

[Viewpoint](https://github.com/WinRb/Viewpoint):
```ruby
cli = Viewpoint::EWSClient.new endpoint, user, pass

# There are also various options you can pass to EWSClient.

# If you are testing in an environment using a self-signed certificate you can pass a connection parameter to ignore SSL verification by passing http_opts: {ssl_verify_mode: 0}.
```

**Comment by martini** [comment]
@thorsteneckel JFI https://github.com/zammad/zammad/commit/51766d51a9d43f11c71f738f7c64fc0eade9c5ff is only for autodiscover (initiated by T#109098).

**Comment by MenneBakker** [comment]
Autodiscover works fine with these modifications

**Comment by monotek** [comment]
Imho disabling SSL checks should be optional and not be enabled by default.

**Comment by sidescraper** [comment]
disabling SSL checks it's a no go.

**Comment by martini** [comment]
> Imho disabling SSL checks should be optional and not be enabled by default.


> disabling SSL checks it's a no go.

JFI: We will change it. Just working on it....

**Comment by MenneBakker** [comment]
If Zammad would make use of the systems trusted CAs we should be fine.

**Comment by thorsteneckel** [comment]
Thanks for your working solution @martini ! I'll will handle the `optional` functionality as stated by @monotek after my vacation.

**Comment by monotek** [comment]
Vacation? Again?! 😂 

But seriously... Should be done before next stable release.
