### ISSUE TITLE
Hebrew text shows question marks instead of text.

### ISSUE THREAD

**Issue by DjMagicFingers** [zammad/zammad#1445]
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: Centos 7
* Operating system: Windows
* Browser + version: Chrome latest

* Tickets created from email messages with Hebrew text show question marks instead of text.

![image](https://user-images.githubusercontent.com/32017425/30564016-45d91eac-9ccc-11e7-9aac-ba273e9ea809.png)

**Comment by DjMagicFingers** [comment]
Some more information:
When clicking the message.html link, downloading the file and opening the file with a web browser, the Hebrew shows exactly as it should have...
![image](https://user-images.githubusercontent.com/32017425/30566671-a705b07e-9cd5-11e7-8725-c31d41096e3d.png)

**Comment by martini** [comment]
@DjMagicFingers can you attache an example Hebrew email file to this issue (in case in Zammad click on article, download "Raw")? So I can try to reproduce it. Thanks.

**Comment by DjMagicFingers** [comment]
@martini yes i can, thank you for trying to help.
Can i PM you so i can keep the privacy of the sender's email safe?

**Comment by hanneshal** [comment]
Hi @DjMagicFingers 
Just send it to support@zammad.com as plain text file attached to your mail.

regards
Johannes

**Comment by thorsteneckel** [comment]
See #1833
