### ISSUE TITLE
Server Error 500 : Deadlock

### ISSUE THREAD

**Issue by bc1000** [zammad/zammad#1446]
### Infos:

* Used Zammad version: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
* Used Zammad installation source: package
* Operating system: CentOS Linux release 7.4.1708 (Core)
* Browser + version: 

### Expected behavior:

* 

### Actual behavior:

There are some older Tickets with simmilar error, but here it´s postgres and not mysql.

* zammad/production.log:
`E, [2017-09-19T10:04:54.775644 #671] ERROR -- : FEHLER:  Verklemmung (Deadlock) entdeckt
DETAIL:  Prozess 12250 wartet auf ShareLock-Sperre auf Transaktion 1693874; blockiert von Prozess 13036.
Prozess 13036 wartet auf ShareLock-Sperre auf Transaktion 1693872; blockiert von Prozess 12250.
HINT:  Einzelheiten zur Anfrage finden Sie im Serverlog.
 (PG::TRDeadlockDetected)
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/querying.rb:39:in `find_by_sql'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation.rb:639:in `exec_queries'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation.rb:515:in `load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation.rb:243:in `to_a'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/finder_methods.rb:475:in `find_take'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/finder_methods.rb:105:in `take'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/finder_methods.rb:442:in `find_one'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/finder_methods.rb:423:in `find_with_ids'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/finder_methods.rb:71:in `find'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:414:in `block in reload'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/scoping/default.rb:33:in `block in unscoped'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation.rb:302:in `scoping'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/scoping/default.rb:33:in `unscoped'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:414:in `reload'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/attribute_methods/dirty.rb:36:in `reload'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/autosave_association.rb:227:in `reload'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/locking/pessimistic.rb:62:in `lock!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/locking/pessimistic.rb:71:in `block in with_lock'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:220:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:277:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/locking/pessimistic.rb:70:in `with_lock'
/opt/zammad/app/models/taskbar.rb:91:in `block in update_preferences_infos'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/delegation.rb:46:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation/delegation.rb:46:in `each'
/opt/zammad/app/models/taskbar.rb:89:in `update_preferences_infos'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:164:in `block in halting'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `block in call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_update_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/callbacks.rb:310:in `_update_record'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/timestamp.rb:70:in `_update_record'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:504:in `create_or_update'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/callbacks.rb:302:in `create_or_update'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:142:in `save!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/validations.rb:43:in `save!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:291:in `block in save!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:220:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:291:in `save!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:265:in `block in update!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:220:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:263:in `update!'
/opt/zammad/app/controllers/application_controller/renders_models.rb:44:in `block in model_update_render'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/locking/pessimistic.rb:72:in `block in with_lock'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:220:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:277:in `transaction'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/locking/pessimistic.rb:70:in `with_lock'
/opt/zammad/app/controllers/application_controller/renders_models.rb:41:in `model_update_render'
/opt/zammad/app/controllers/taskbar_controller.rb:26:in `update'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/abstract_controller/base.rb:198:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_controller/metal/rendering.rb:10:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:117:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/abstract_controller/callbacks.rb:19:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_controller/metal/rescue.rb:29:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/abstract_controller/base.rb:137:in `process'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.9/lib/action_view/rendering.rb:30:in `process'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_controller/metal.rb:196:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_controller/metal.rb:237:in `block in action'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:30:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:30:in `serve'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:817:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/builder.rb:63:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/flash.rb:260:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/query_cache.rb:36:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:38:in `call_app'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:20:in `block in call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:68:in `tagged'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:20:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/static.rb:120:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:518:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/application.rb:165:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2017-09-19T10:04:54.875127 #671]  INFO -- : Processing by TaskbarController#update as JSON
I, [2017-09-19T10:04:54.875218 #671]  INFO -- :   Parameters: {"key"=>"Ticket-426", "client_id"=>"123", "callback"=>"TicketZoom", "state"=>{"ticket"=>{}, "article"=>{}}, "params"=>{"ticket_id"=>426, "overview_id"=>4, "init"=>true}, "prio"=>10, "notify"=>true, "active"=>false, "updated_at"=>"2017-09-19T08:04:06.431Z", "id"=>"1671", "taskbar"=>{"id"=>"1671", "client_id"=>"123", "key"=>"Ticket-426", "callback"=>"TicketZoom", "state"=>{"ticket"=>{}, "article"=>{}}, "params"=>{"ticket_id"=>426, "overview_id"=>4, "init"=>true}, "prio"=>10, "notify"=>true, "active"=>false, "updated_at"=>"2017-09-19T08:04:06.431Z"}}
I, [2017-09-19T10:04:54.958714 #671]  INFO -- : Completed 500 Internal Server Error in 2057ms (Views: 0.2ms | ActiveRecord: 1864.2ms)
I, [2017-09-19T10:04:54.962350 #671]  INFO -- : Completed 200 OK in 1706ms (Views: 826.0ms | ActiveRecord: 376.3ms)
I, [2017-09-19T10:04:55.002126 #673]  INFO -- : # curl -X POST "http://localhost:9200/zammad_production/Ticket/426" \
I, [2017-09-19T10:04:55.144692 #673]  INFO -- : # 200

`

### Steps to reproduce the behavior:

* Just wait in the dasbboard, after some time this error appears.

**Comment by martini** [comment]
@bc1000 thanks for your report. I tried to reproduce it, without success. Do you have more details? Or maybe can I get remote access for debugging?

**Comment by bc1000** [comment]
I could give you a teamviewer access, but today this error did not appear. I guess it started yesterday because different agents worked on same ticket or just opened it.

**Comment by martini** [comment]
Thanks for fast feedback. If you find more details about this issue it would be good if you could share this.

So I'm closing for now. Just reopen if you have more info. Thanks a lot!
