### ISSUE TITLE
Zammad showing "Loading" but not starting

### ISSUE THREAD

**Issue by teigentler** [zammad/zammad#1448]
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: CentOS via RPM
* Operating system: CentOS7
* Browser + version: Firefox 55

Dear all,

I want to run two apps on the server. The first (OpenProject) is running on port 6000, Zammad on port 3000, of course. I tried to configure nginx as follows: 
```
server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
              proxy_set_header X-Forwarded-Host $host;
              proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass http://127.0.0.1:6000/;
        }

       location /ticket/ {

        proxy_set_header Host $http_host;
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 180;
        proxy_pass http://localhost:3000/;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
```
Typing URL/ticket/ Zammad shows up a phoenix image and "Loading" but does not show the dashboard.
Any hint what is wrong?

Thank you in advance.
Thomas

**Comment by martini** [comment]
Just for clarifying, you do not use a own hostname for Zammad, right? 

In case if you use a own hostname for Zammad, is it working then?

PS: It seems to be a nginx config issue - shows up a phoenix image and "Loading" means no javascript files are found on server. Anyway, I recommend to use a own hostname for Zammad (so you will not run into nginx config issues).

**Comment by teigentler** [comment]
The server is a development machine without an own hostname, indeed.
I will test it a hostname and report again
Thank you!

**Comment by teigentler** [comment]
Found a workaround:
 
```
        location / {
              proxy_set_header X-Forwarded-Host $host;
              proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass http://127.0.0.1:6000/;
        }

        location ~ /assets/(?<section>.+) {
          proxy_pass http://127.0.0.1:3000/assets/$section/;
          proxy_set_header Host $host;
        }

        location /ticket/ {
         proxy_pass http://127.0.0.1:3000/;
        }
```

**Comment by TheNuclearCat** [comment]
I needed to use this workout too! Any ideas why the default config is not working out of the box? The Probelm is that the css and js files from the assets return a 404 error, but the  folder is there with the files.

**Comment by NeverMin** [comment]
> but the folder is there with the files.

just run please:
`rake assets:precompile`
