### ISSUE TITLE
Constant Email notifications of "new device" using Zammad behind a router configured with multiple load balancing ISP

### ISSUE THREAD

**Issue by emsa-github** [zammad/zammad#1449]
Using Zammad behind a router configured with load balancing multiple internet connections, triggers for the user constant notifications of: "It looks like you signed into your account using a new device"

### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: (ubuntu via DEB)
* Operating system: Ubuntu 16.04 
* Browser + version: chrome

### Expected behavior:

* The notification should be send only when the user login from a real different device, not only because the user change IP. Something like gmail session works.

### Actual behavior:

* At some point, this triggers a chain of notifications every few seconds: "It looks like you signed into your account using a new device on:"

"2017-09-19 19:40:54 UTC"
"2017-09-19 19:42:08 UTC"
"2017-09-19 19:42:16 UTC"
"2017-09-19 19:42:25 UTC"
"2017-09-19 19:42:57 UTC"
"2017-09-19 19:43:06 UTC"
"2017-09-19 19:43:06 UTC"
"2017-09-19 19:43:08 UTC"
"2017-09-19 19:43:07 UTC"
"2017-09-19 19:44:12 UTC"
"2017-09-19 19:44:12 UTC"
"2017-09-19 19:45:01 UTC"
"2017-09-19 19:45:03 UTC"
"2017-09-19 19:45:01 UTC"
"2017-09-19 19:45:19 UTC"

### Steps to reproduce the behavior:

* Use Zammad behind a router configured with load balancing multiple internet connections.

**Comment by martini** [comment]
Hi @emsa-github, a view questions to be able to help you:

1) What client do you use - it seems to be chrome but I want to be sure (browser, curl, a lib)?

2) What user ip's do you show to Zammad (are the in the same country or the ip's are from different countries)?

**Comment by martini** [comment]
Usually the device detection in Zammad works like this:

1) A browser is generating a uniq key before first AJAX request has been done. This uniq key is stored on browse side and always sent to the server *.
2) The server is identifying the browser by this uniq key.
3) Zammad will send you in 2 cases a notification
 3.1 Only if the uniq key has changed -> Zammad will send you a new device notification
 3.2 If the country of the remote ip has changed -> Zammad will send you a known device but in new country notification

-=> So from this point of view, Zammad should work fine behind a load balancer with multiple internet connections.

* In case of using curl, wget or a programming lib directly for the REST API, there is no possibility of a uniq key. Then the user agent is taken.

**Comment by emsa-github** [comment]
hi, thanks for the follow up, I was using Chrome browser, doing simple initial configuration.

The ISP are from the same country, the IP address are from the same country.

The chain of notifications stopped, but I think the trigger was retaking the same browser session after an period of inactivity. After that each time I navigated to another page the notification was sent.

I will do further testing, thanks.

**Comment by emsa-github** [comment]
it happened again today at seldom times, still don't know how to reproduce it, but it launched a chain of 100+ notifications of new device in a short span.

I was using only one browser: google chrome, only one session, only one tab. I was Navigating the admin configuration pages.

But we are going to anchor the outgoing traffic to our zammad installation IP, to exit only by  the primary ISP.  Sorry don't know what else to try.

thanks.

**Comment by martini** [comment]
Hi @emsa-github 

any news?

JFI: In case you also can disable while device logging, just remove user_preferences.device from any role in admin interface.

 -Martin

**Comment by emsa-github** [comment]
Hi, not much, we changed the network route from load balancing to fail-over for access to our zamad installation  and the notifications stopped. At the moment I prefer this method, is something we usually do for high security websites like financials intitutions that doest work with requests from multiple ISP on the same session.

Thanks for the follow up.

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
