### ISSUE TITLE
Change default_create of ticket priority

### ISSUE THREAD

**Issue by Wisou** [zammad/zammad#1450]
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: (source, package, ...) : Package
* Operating system: Debian
* Browser + version: Firefox

Hi,

I want change default priority for a new ticket with rails console

Before 
irb(main):024:0> Ticket::Priority.find(1)
=> #<Ticket::Priority id: 1, name: "1 mineure", default_create: false, note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-07-10 10:14:10", updated_at: "2017-09-20 14:55:34">
irb(main):025:0> Ticket::Priority.find(2)
=> #<Ticket::Priority id: 2, name: "2 majeure", default_create: true, note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-07-10 10:14:10", updated_at: "2017-09-20 14:55:34">

After
Ticket::Priority.find(1).update_attribute(:default_create, true)
=> true

irb(main):027:0> Ticket::Priority.find(1)
=> #<Ticket::Priority id: 1, name: "1 mineure", default_create: true, note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-07-10 10:14:10", updated_at: "2017-09-20 14:57:10">
irb(main):028:0> Ticket::Priority.find(2)
=> #<Ticket::Priority id: 2, name: "2 majeure", default_create: false, note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-07-10 10:14:10", updated_at: "2017-09-20 14:57:10">

But no change for a new ticket !

![image](https://user-images.githubusercontent.com/30259860/30651097-fabb5a0c-9e24-11e7-8aef-78c0d73a7f13.png)

**Comment by thorsteneckel** [comment]
Hi @Wisou - This is due to the fact that the value itself is read out at different points. However, the default value of the priority field is stored in the field itself. To update it, run the following code in the console:

```ruby
ObjectManager::Attribute.add(
  force: true,
  object: 'Ticket',
  name: 'priority_id',
  display: 'Priority',
  data_type: 'select',
  data_option: {
    relation: 'TicketPriority',
    nulloption: false,
    multiple: false,
    null: false,
    default: Ticket::Priority.find_by(default_create: true).id,
    translate: true,
  },
  editable: false,
  active: true,
  screens: {
    create_middle: {
      'ticket.agent' => {
        null: false,
        item_class: 'column',
      },
    },
    edit: {
      'ticket.agent' => {
        null: false,
      },
    },
  },
  to_create: false,
  to_migrate: false,
  to_delete: false,
  position: 80,
)

ObjectManager::Attribute.migration_execute(false)
```

Please remember to restart your Application-, Websocket-Server and Scheduler.

**Comment by Wisou** [comment]
thx for your reply
