### ISSUE TITLE
rpm installation

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#1452]
Hello,
It looks like you have updated repo file of zammad; i tried to install it from my previous ansible version and it didnt work. when i tried to install it manually, with holding all pre-requisite packages installed, it didnt work out:
$ sudo yum -y install zammad
Loaded plugins: fastestmirror
base                                                                             | 3.6 kB  00:00:00     
centos-sclo-rh                                                                   | 2.9 kB  00:00:00     
centos-sclo-sclo                                                                 | 2.9 kB  00:00:00     
epel/x86_64/metalink                                                             |  20 kB  00:00:00     
epel                                                                             | 4.3 kB  00:00:00     
extras                                                                           | 3.4 kB  00:00:00     
mysql-connectors-community                                                       | 2.5 kB  00:00:00     
mysql-tools-community                                                            | 2.5 kB  00:00:00     
mysql57-community                                                                | 2.5 kB  00:00:00     
updates                                                                          | 3.4 kB  00:00:00     
zammad/x86_64/signature                                                          |  473 B  00:00:00     
Retrieving key from https://dl.packager.io/srv/zammad/zammad/key
Importing GPG key 0xBD33EEB8:
 Userid     : "pkgr.io (http://pkgr.io) <support@pkgr.io>"
 Fingerprint: 6257 df99 7246 2f57 a20f fb2a b6d5 83cc bd33 eeb8
 From       : https://dl.packager.io/srv/zammad/zammad/key
zammad/x86_64/signature                                                          |  578 B  00:00:00     
zammad/x86_64/primary                                                            |  22 kB  00:00:00     
Loading mirror speeds from cached hostfile
 * base: mirror.eu.oneandone.net
 * epel: mirror.de.leaseweb.net
 * extras: centos.mirrors.as250.net
 * updates: centos.mirrors.as250.net
zammad                                                                                          112/112
Resolving Dependencies
--> Running transaction check
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Finished Dependency Resolution
Error: Package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64 (zammad)
           Requires: elasticsearch
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
-----------------------------------------
sudo yum -y install zammad --skip-broken
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.eu.oneandone.net
 * epel: mirror.de.leaseweb.net
 * extras: centos.mirrors.as250.net
 * updates: centos.mirrors.as250.net
Resolving Dependencies
--> Running transaction check
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
Error: requested datatype filelists not available
------------------------------------------------------------------------

Until today, it never happened to me. I have already ran these two:
sudo yum -y install epel-release wget
sudo wget -O /etc/yum.repos.d/zammad.repo https://dl.packager.io/srv/zammad/zammad/stable/installer/el/7.repo

as you proposed in your manual. But still experiencing with the same error to ignore dependencies. May i ask if something changed within rpm file by your last update?
Best,

OS: Centos 7
Zammad guide: [1]
installed items before zammad installtion: 
- centos-release-scl
- epel-release

[1] https://docs.zammad.org/en/latest/install-centos.html

**Comment by monotek** [comment]
I guess it's only a temporary problem. Could you try again please?

I'll try it tomorrow.

**Comment by hamzehmohammadnia** [comment]
Hi,
Facing the same issue...

Resolving Dependencies
--> Running transaction check
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Finished Dependency Resolution
Error: Package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64 (zammad)
           Requires: elasticsearch
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by monotek** [comment]
Works for me with:

```
sudo wget -O /etc/yum.repos.d/zammad.repo \
https://dl.packager.io/srv/zammad/zammad/develop/installer/el/7.repo
sudo yum install zammad
```

**Comment by hamzehmohammadnia** [comment]
I just have tested with two different instance:
1. With having already installed several packages, like Mysql, HTTP, Fireawll, zlib-devel, sqlite-devel, epel-release, centos-release-scl, python-devel. And then after following your instruction faced with:

#sudo yum install zammad
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirrors.as250.net
 * epel: fedora.tu-chemnitz.de
 * extras: centos.mirrors.as250.net
 * updates: centos.mirrors.as250.net
Resolving Dependencies
--> Running transaction check
---> Package zammad.x86_64 0:2.1.1-1506329330.51766d51.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.1.1-1506329330.51766d51.centos7.x86_64
--> Finished Dependency Resolution
Error: Package: zammad-2.1.1-1506329330.51766d51.centos7.x86_64 (zammad)
           Requires: elasticsearch
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

2. Then, in second instance, i tried with a clean installation of Centos 7, and:
#sudo yum -y install epel-release wget
Installed:
  epel-release.noarch 0:7-9                           wget.x86_64 0:1.14-15.el7                          
Complete!
#sudo wget -O /etc/yum.repos.d/zammad.repo https://dl.packager.io/srv/zammad/zammad/stable/installer/el/7.repo
--2017-09-25 13:21:57--  https://dl.packager.io/srv/zammad/zammad/stable/installer/el/7.repo
Resolving dl.packager.io (dl.packager.io)... 66.228.36.176
Connecting to dl.packager.io (dl.packager.io)|66.228.36.176|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘/etc/yum.repos.d/zammad.repo’

    [ <=>                                                            ] 271         --.-K/s   in 0s      

2017-09-25 13:22:00 (26.6 MB/s) - ‘/etc/yum.repos.d/zammad.repo’ saved [271]

#sudo yum -y install zammad
Loaded plugins: fastestmirror
epel/x86_64/metalink                                                              |  24 kB  00:00:00     
epel                                                                              | 4.3 kB  00:00:00     
zammad/x86_64/signature                                                           |  473 B  00:00:00     
Retrieving key from https://dl.packager.io/srv/zammad/zammad/key
Importing GPG key 0xBD33EEB8:
 Userid     : "pkgr.io (http://pkgr.io) <support@pkgr.io>"
 Fingerprint: 6257 df99 7246 2f57 a20f fb2a b6d5 83cc bd33 eeb8
 From       : https://dl.packager.io/srv/zammad/zammad/key
zammad/x86_64/signature                                                           |  578 B  00:00:03     
(1/4): epel/x86_64/group_gz                                                       | 170 kB  00:00:00     
(2/4): epel/x86_64/updateinfo                                                     | 830 kB  00:00:00     
(3/4): epel/x86_64/primary_db                                                     | 4.8 MB  00:00:00     
(4/4): zammad/x86_64/primary                                                      |  22 kB  00:00:01     
Loading mirror speeds from cached hostfile
 * base: centos.mirrors.as250.net
 * epel: ftp-stud.hs-esslingen.de
 * extras: centos.mirrors.as250.net
 * updates: centos.mirrors.as250.net
zammad
Resolving Dependencies
--> Running transaction check
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: postgresql-libs for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Processing Dependency: nginx for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Processing Dependency: libxslt for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Processing Dependency: postgresql-server for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Running transaction check
---> Package libxslt.x86_64 0:1.1.28-5.el7 will be installed
---> Package nginx.x86_64 1:1.10.2-1.el7 will be installed
--> Processing Dependency: nginx-filesystem = 1:1.10.2-1.el7 for package: 1:nginx-1.10.2-1.el7.x86_64
--> Processing Dependency: nginx-all-modules = 1:1.10.2-1.el7 for package: 1:nginx-1.10.2-1.el7.x86_64
--> Processing Dependency: nginx-filesystem for package: 1:nginx-1.10.2-1.el7.x86_64
--> Processing Dependency: libprofiler.so.0()(64bit) for package: 1:nginx-1.10.2-1.el7.x86_64
---> Package postgresql-libs.x86_64 0:9.2.23-1.el7_4 will be installed
---> Package postgresql-server.x86_64 0:9.2.23-1.el7_4 will be installed
--> Processing Dependency: postgresql(x86-64) = 9.2.23-1.el7_4 for package: postgresql-server-9.2.23-1.el7_4.x86_64
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Running transaction check
---> Package gperftools-libs.x86_64 0:2.4-8.el7 will be installed
--> Processing Dependency: libunwind.so.8()(64bit) for package: gperftools-libs-2.4-8.el7.x86_64
---> Package nginx-all-modules.noarch 1:1.10.2-1.el7 will be installed
--> Processing Dependency: nginx-mod-stream = 1:1.10.2-1.el7 for package: 1:nginx-all-modules-1.10.2-1.el7.noarch
--> Processing Dependency: nginx-mod-mail = 1:1.10.2-1.el7 for package: 1:nginx-all-modules-1.10.2-1.el7.noarch
--> Processing Dependency: nginx-mod-http-xslt-filter = 1:1.10.2-1.el7 for package: 1:nginx-all-modules-1.10.2-1.el7.noarch
--> Processing Dependency: nginx-mod-http-perl = 1:1.10.2-1.el7 for package: 1:nginx-all-modules-1.10.2-1.el7.noarch
--> Processing Dependency: nginx-mod-http-image-filter = 1:1.10.2-1.el7 for package: 1:nginx-all-modules-1.10.2-1.el7.noarch
--> Processing Dependency: nginx-mod-http-geoip = 1:1.10.2-1.el7 for package: 1:nginx-all-modules-1.10.2-1.el7.noarch
---> Package nginx-filesystem.noarch 1:1.10.2-1.el7 will be installed
---> Package postgresql.x86_64 0:9.2.23-1.el7_4 will be installed
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Running transaction check
---> Package libunwind.x86_64 2:1.2-2.el7 will be installed
---> Package nginx-mod-http-geoip.x86_64 1:1.10.2-1.el7 will be installed
--> Processing Dependency: GeoIP for package: 1:nginx-mod-http-geoip-1.10.2-1.el7.x86_64
--> Processing Dependency: libGeoIP.so.1()(64bit) for package: 1:nginx-mod-http-geoip-1.10.2-1.el7.x86_64
---> Package nginx-mod-http-image-filter.x86_64 1:1.10.2-1.el7 will be installed
--> Processing Dependency: gd for package: 1:nginx-mod-http-image-filter-1.10.2-1.el7.x86_64
--> Processing Dependency: libgd.so.2()(64bit) for package: 1:nginx-mod-http-image-filter-1.10.2-1.el7.x86_64
---> Package nginx-mod-http-perl.x86_64 1:1.10.2-1.el7 will be installed
--> Processing Dependency: perl >= 5.006001 for package: 1:nginx-mod-http-perl-1.10.2-1.el7.x86_64
--> Processing Dependency: perl(warnings) for package: 1:nginx-mod-http-perl-1.10.2-1.el7.x86_64
--> Processing Dependency: perl(strict) for package: 1:nginx-mod-http-perl-1.10.2-1.el7.x86_64
--> Processing Dependency: perl(constant) for package: 1:nginx-mod-http-perl-1.10.2-1.el7.x86_64
--> Processing Dependency: perl(XSLoader) for package: 1:nginx-mod-http-perl-1.10.2-1.el7.x86_64
--> Processing Dependency: perl(Exporter) for package: 1:nginx-mod-http-perl-1.10.2-1.el7.x86_64
--> Processing Dependency: perl(:MODULE_COMPAT_5.16.3) for package: 1:nginx-mod-http-perl-1.10.2-1.el7.x86_64
--> Processing Dependency: libperl.so()(64bit) for package: 1:nginx-mod-http-perl-1.10.2-1.el7.x86_64
---> Package nginx-mod-http-xslt-filter.x86_64 1:1.10.2-1.el7 will be installed
---> Package nginx-mod-mail.x86_64 1:1.10.2-1.el7 will be installed
---> Package nginx-mod-stream.x86_64 1:1.10.2-1.el7 will be installed
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Running transaction check
---> Package GeoIP.x86_64 0:1.5.0-11.el7 will be installed
---> Package gd.x86_64 0:2.0.35-26.el7 will be installed
--> Processing Dependency: libpng15.so.15(PNG15_0)(64bit) for package: gd-2.0.35-26.el7.x86_64
--> Processing Dependency: libpng15.so.15()(64bit) for package: gd-2.0.35-26.el7.x86_64
--> Processing Dependency: libfontconfig.so.1()(64bit) for package: gd-2.0.35-26.el7.x86_64
--> Processing Dependency: libXpm.so.4()(64bit) for package: gd-2.0.35-26.el7.x86_64
--> Processing Dependency: libX11.so.6()(64bit) for package: gd-2.0.35-26.el7.x86_64
---> Package perl.x86_64 4:5.16.3-292.el7 will be installed
--> Processing Dependency: perl(Socket) >= 1.3 for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Scalar::Util) >= 1.10 for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl-macros for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(threads::shared) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(threads) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Time::Local) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Time::HiRes) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Storable) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Socket) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Scalar::Util) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Pod::Simple::XHTML) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Pod::Simple::Search) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Getopt::Long) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Filter::Util::Call) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(File::Temp) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(File::Spec::Unix) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(File::Spec::Functions) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(File::Spec) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(File::Path) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Cwd) for package: 4:perl-5.16.3-292.el7.x86_64
--> Processing Dependency: perl(Carp) for package: 4:perl-5.16.3-292.el7.x86_64
---> Package perl-Exporter.noarch 0:5.68-3.el7 will be installed
---> Package perl-constant.noarch 0:1.27-2.el7 will be installed
---> Package perl-libs.x86_64 4:5.16.3-292.el7 will be installed
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Running transaction check
---> Package fontconfig.x86_64 0:2.10.95-11.el7 will be installed
--> Processing Dependency: fontpackages-filesystem for package: fontconfig-2.10.95-11.el7.x86_64
--> Processing Dependency: font(:lang=en) for package: fontconfig-2.10.95-11.el7.x86_64
---> Package libX11.x86_64 0:1.6.5-1.el7 will be installed
--> Processing Dependency: libX11-common >= 1.6.5-1.el7 for package: libX11-1.6.5-1.el7.x86_64
--> Processing Dependency: libxcb.so.1()(64bit) for package: libX11-1.6.5-1.el7.x86_64
---> Package libXpm.x86_64 0:3.5.12-1.el7 will be installed
---> Package libpng.x86_64 2:1.5.13-7.el7_2 will be installed
---> Package perl-Carp.noarch 0:1.26-244.el7 will be installed
---> Package perl-File-Path.noarch 0:2.09-2.el7 will be installed
---> Package perl-File-Temp.noarch 0:0.23.01-3.el7 will be installed
---> Package perl-Filter.x86_64 0:1.49-3.el7 will be installed
---> Package perl-Getopt-Long.noarch 0:2.40-2.el7 will be installed
--> Processing Dependency: perl(Pod::Usage) >= 1.14 for package: perl-Getopt-Long-2.40-2.el7.noarch
--> Processing Dependency: perl(Text::ParseWords) for package: perl-Getopt-Long-2.40-2.el7.noarch
---> Package perl-PathTools.x86_64 0:3.40-5.el7 will be installed
---> Package perl-Pod-Simple.noarch 1:3.28-4.el7 will be installed
--> Processing Dependency: perl(Pod::Escapes) >= 1.04 for package: 1:perl-Pod-Simple-3.28-4.el7.noarch
--> Processing Dependency: perl(Encode) for package: 1:perl-Pod-Simple-3.28-4.el7.noarch
---> Package perl-Scalar-List-Utils.x86_64 0:1.27-248.el7 will be installed
---> Package perl-Socket.x86_64 0:2.010-4.el7 will be installed
---> Package perl-Storable.x86_64 0:2.45-3.el7 will be installed
---> Package perl-Time-HiRes.x86_64 4:1.9725-3.el7 will be installed
---> Package perl-Time-Local.noarch 0:1.2300-2.el7 will be installed
---> Package perl-macros.x86_64 4:5.16.3-292.el7 will be installed
---> Package perl-threads.x86_64 0:1.87-4.el7 will be installed
---> Package perl-threads-shared.x86_64 0:1.43-6.el7 will be installed
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Running transaction check
---> Package fontpackages-filesystem.noarch 0:1.44-8.el7 will be installed
---> Package libX11-common.noarch 0:1.6.5-1.el7 will be installed
---> Package libxcb.x86_64 0:1.12-1.el7 will be installed
--> Processing Dependency: libXau.so.6()(64bit) for package: libxcb-1.12-1.el7.x86_64
---> Package lyx-fonts.noarch 0:2.2.3-1.el7 will be installed
---> Package perl-Encode.x86_64 0:2.51-7.el7 will be installed
---> Package perl-Pod-Escapes.noarch 1:1.04-292.el7 will be installed
---> Package perl-Pod-Usage.noarch 0:1.63-3.el7 will be installed
--> Processing Dependency: perl(Pod::Text) >= 3.15 for package: perl-Pod-Usage-1.63-3.el7.noarch
--> Processing Dependency: perl-Pod-Perldoc for package: perl-Pod-Usage-1.63-3.el7.noarch
---> Package perl-Text-ParseWords.noarch 0:3.29-4.el7 will be installed
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Running transaction check
---> Package libXau.x86_64 0:1.0.8-2.1.el7 will be installed
---> Package perl-Pod-Perldoc.noarch 0:3.20-4.el7 will be installed
--> Processing Dependency: perl(parent) for package: perl-Pod-Perldoc-3.20-4.el7.noarch
--> Processing Dependency: perl(HTTP::Tiny) for package: perl-Pod-Perldoc-3.20-4.el7.noarch
---> Package perl-podlators.noarch 0:2.5.1-3.el7 will be installed
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Running transaction check
---> Package perl-HTTP-Tiny.noarch 0:0.033-3.el7 will be installed
---> Package perl-parent.noarch 1:0.225-244.el7 will be installed
---> Package zammad.x86_64 0:2.0.0-1505468213.c4ce1caa.centos7 will be installed
--> Processing Dependency: elasticsearch for package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64
--> Finished Dependency Resolution
Error: Package: zammad-2.0.0-1505468213.c4ce1caa.centos7.x86_64 (zammad)
           Requires: elasticsearch
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by hamzehmohammadnia** [comment]
Can I ask you how I can access to your previous version of Zammad (V1.5)?

**Comment by monotek** [comment]
Install elasticsearch first.

**Comment by hamzehmohammadnia** [comment]
Yes, now fixed. Thanks:


For future reference, who may need it:
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.1.rpm
sha1sum elasticsearch-5.6.1.rpm 
sudo rpm --install elasticsearch-5.6.1.rpm

**Comment by muhammadn** [comment]
@monotek  It is possible if we can use [omnibus ](https://github.com/chef/omnibus) which gitlab is currently using for packaging their [Gitlab-CE](https://github.com/gitlabhq/omnibus-gitlab) installations to avoid any inconsistencies the the built package?

**Comment by monotek** [comment]
No, as we would need to host the build machine.
