### ISSUE TITLE
translation for some fields broken

### ISSUE THREAD

**Issue by gwingend** [zammad/zammad#1453]
### Infos:

* Used Zammad version: 2.0x
* Used Zammad installation source: (source, package, ...) demosystem on zammad.com
* Operating system: 
* Browser + version: 

### Expected behavior:
every description should be translated to german language

### Actual behavior:
two descriptions are in german and two in english.
Looking in configuration => translation you could see that a german translation for both fields is available.

![zammad](https://user-images.githubusercontent.com/30232713/30665776-7993be1e-9e52-11e7-83c2-bb0fc8091eef.jpeg)

![zammad2](https://user-images.githubusercontent.com/30232713/30665898-ea389fc2-9e52-11e7-8e0c-ef627c0ce9f5.jpeg)

*

**Comment by martini** [comment]
Hi @gwingend 

in this case, it seems that the german translation is really missing. But, hey! Good news!

Did you see the inline translation feature? On mac `ctrl+alt+t` on win `ctrl+shift+t`

Here you can translate the content. After finishing, just turn of inline translation, go to Admin -> Translations -> And push it to Zammad. Then we take it into default translations.

Thanks for contributing!

Greetings,

 -Martin

**Comment by gwingend** [comment]
@martini This was my first idea.

But as you can see in the second screeshot the phrase "use subject...." is already translated to german.
So I wonder why the german translation is not displayed?

**Comment by gwingend** [comment]
Maybe label "waiting for feedback" should be removed?

**Comment by gwingend** [comment]
I think this could be closed.
