### ISSUE TITLE
User can't login via google oauth if an user with the same email was previously created 

### ISSUE THREAD

**Issue by emsa-github** [zammad/zammad#1454]
### Infos:

* Used Zammad version:  2.0.x
* Used Zammad installation source:  UBUNTU DEB
* Operating system: ubuntu 16.04
* Browser + version:  Chrome

User can't login to zammad web app via google oauth if an user with the same email was previously created 

Not necessarly because the user was created manually, but also because the application created the user automatically when that user sent an email or that email address was CC on an ticket before the user login to the web app.

### Expected behavior:

* an user with the same email address trying to login to the web app for the first time with google oauth should be identified as the same user if the email address match an existant user.

### Actual behavior:

* an user with the same email address trying to login to the web app with google oauth fails with error "422: The change you wanted was rejected." if the user email address match an existant user.

### Steps to reproduce the behavior:

* 
Have a zamad installation configured with google oauth authentication on domain @ example.com
A new user: example@domain.com sends a new ticket via email to zammad.
The user: example@domain.com  tries to login to zammad web app for the first time with google oauth.

![image](https://user-images.githubusercontent.com/32110556/30673680-176616f8-9e32-11e7-9a30-13ede3cc5469.png)

**Comment by muhammadn** [comment]
You can add this by logging in first as that user and clicking User(your user picture)->Profile->Linked Accounts and click 'Add' under Google.

Then you will see the Google login page and login as necessary. After doing all this, you can test it out, (logout and login using google) and it will work.

**Comment by thorsteneckel** [comment]
@emsa-github - please reopen if @muhammadn solution doesn't work for you. @muhammadn -> great 🚀

**Comment by hamzehmohammadnia** [comment]
@muhammadn your solution will not work if a user already has been created, cuz in that case user cannot be authenticated via other portals. This error will show up "422: The change you wanted was rejected."
To solve it temporarily the automatically-created user profile can be edited to something dummy and then customer logins by himself for first time to be authenticated.



One possible solution can be if zammad separate customers form emaili tickets. Separating this can help us to form our customers by ourselves and prioritize our customers tickets over usual emaili tickets:)

**Comment by nicolasriousset** [comment]
Hi,
We're facing the same issue with Zammad 3 : if a user account was created through the Zammad API, and the user tries to log in using OAuth, an error message "Email address is already used for other user." is displayed.

We would like the OAuth authentication to automatically link the existing user account to the new authentication method. Is it possible ?

Thanks a lot

**Comment by MrGeneration** [comment]
@nicolasriousset two things:

Please do not recycle old and resolved issues, this nukes all existing overview of issues and might even cause those comments (which might be super important!) to be overseen. We wouldn't want that 👍 

To your question - this is rather a technical question which should life in the Community (https://community.zammad.org) for the next time. This functionality is already possible and hides within "Security" (Automatic account link on initial logon) which is off by default:

https://admin-docs.zammad.org/en/latest/settings-security.html#automatic-account-link-on-initial-logon

**Comment by nicolasriousset** [comment]
Sorry for the trouble, thanks a lot for your answer.
