### ISSUE TITLE
Acess to report profiles

### ISSUE THREAD

**Issue by edneymatias** [zammad/zammad#1455]
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: package
* Operating system: Debian Jessie
* Browser + version: 60.0.3112.113 64 bits

### Expected behavior:

* Access to report interface

### Actual behavior:

* There's no report interface nor report profiles menu option.

### Steps to reproduce the behavior:

* Install Zammad and access it with the admin user created during installation. I checked profile configuration and admin role has full access to admin modules. Don't know if I'm missing something.

**Comment by babakkazemi** [comment]
Hi,

Seems this is a duplicate to #929 
@edneymatias Reporting seems only to be available in source installation, not in package installation.

Best

Babak

**Comment by thorsteneckel** [comment]
@babakkazemi is right. Reporting is currently limited to source installations and Plus hosting plans. It will be part of the next official release - Zammad 2.1.

**Comment by edneymatias** [comment]
Thank you, people, you are really fast!

**Comment by singhpps** [comment]
I have installed Zammad 2.0 on Centos 7 from source. But in my both installations report profiles missing and even time accounting table is blank.
