### ISSUE TITLE
Contact form: 401 when posting to /api/v1/form_submit

### ISSUE THREAD

**Issue by j-slvr** [zammad/zammad#1456]
Before the update to 2.0.x we were able to use our own contact form to create new zammad tickets like this:

``` js
$.ajax({
    url: zammadUrl + "/api/v1/form_submit",
    type: "POST",
    data: {
        name: name,
        email: email,
        body: message,
        title: title ? title : 'Contact Form'
    },
    cache: false,
    success: function () {
        ...
    },
    error: function (e) {
        ...
    },
})
```

`name`, `email`, `title` and `message` being strings derived from our own form.

Now (with 2.0.x) i get 401 for this request.

here is the corresponding curl (change \<URL\> to your endpoint):

``` curl
curl '<URL>/api/v1/form_submit' -H 'pragma: no-cache' -H 'origin: http://localhost:3000' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,de-DE;q=0.8,de;q=0.6,en;q=0.4' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' -H 'accept: */*' -H 'cache-control: no-cache' -H 'authority: support.route360.net' -H 'referer: http://localhost:3000/contact' --data 'name=testy&email=test%40test.com&body=testbody&title=Contact+Form' --compressed
```

What has changed with this api since 1.0? Do i have to authenticate somehow?

**Comment by muhammadn** [comment]
401 usually means unauthorized, You need to get the token from /api/v1/form_config. This is assuming you have enabled Form in Settings->Channel. 

To get the token:

 curl -X POST http://localhost:3000/api/v1/form_config -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' --data 'fingerprint=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASw'   

Fingerprint can be any base64 encoded image but i keep is short for brevity.

this will result in:
{"enabled":true,"endpoint":"http://localhost/api/v1/form_submit","token":"VVVGME4xTmhURXgwT1dSSFJrOUpSV0l4UlRsRVkzVTJLMDF6SzB4RVpFNVpXbVpYZGtRMlUyTk9XR2xYVG1ONUx6RTFNRWRSZUV0V1EyZE9LMXBEWVdocGFGRTJORVJvVUZrMVVXWnlNVlZ3ZDNCek5VUTNjMHh4TVZvNU1XcHFhRVpCT1doaVRWUm5XRFZXVG5JM2VtbFdLM2h6V0Vwak5YcEhUakJuVXpKYVNrZHhLMDVqYW10WllXWnlRV3BpV0VKSVdrRjNQVDB0TFRnM1VIQk5RVU56TTJFMlp6RTBOM1paTXl0MU1XYzlQUT09LS0zODY5ZmExM2E1YWYxZmM0ZTgyMGFkZWRiMTA1Nzk3Yzc2Y2Y3M2Zi"}

The token you need is in the JSON result above. Next:

Use the same fingerprint to send the data:

curl http://localhost:3000/api/v1/form_submit -H 'pragma: no-cache' -H 'origin: http://localhost:3000' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,de-DE;q=0.8,de;q=0.6,en;q=0.4' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' -H 'accept: */*' -H 'cache-control: no-cache' -H 'authority: support.route360.net' -H 'referer: http://localhost:3000/contact' --data 'name=testy&email=test%40test.com&body=testbody&title=Contact+Form&token=THE_TOKEN_YOU_GET_LIKE_ABOVE&fingerprint=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASw' --compressed

Result (you should get a reply something like this):
{"ticket":{"id":23,"number":"70023"}}

Hope that helps.

**Comment by j-slvr** [comment]
Thank you, this was it worked. 

Two questions:
1. Does the token expire? -> Do i have to request a token before every post to the form_submit endpoint?
2. Whats the deal with the image fingerprint? Some background info would be great.

**Comment by martini** [comment]
> 1. Does the token expire? -> Do i have to request a token before every post to the form_submit endpoint?

The token is to prevent spam. The token will expire after 24h.

> 2. Whats the deal with the image fingerprint? Some background info would be great.

It's a browser finger print, it's also just to prevent spam.

**Comment by martini** [comment]
Just reopen if you need more infos.
