### ISSUE TITLE
LDAP Integration "StatusCode: 500 {"error":"Data too long for column 'handler' at row 1"}"

### ISSUE THREAD

**Issue by lorenzgroup** [zammad/zammad#1457]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: (source, package, ...) Ubuntu DEB
* Operating system:  Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-93-generic x86_64) (Vmware ESX 5.5)
* Browser + version: Chrome 60.0.3112.113 (But Tried Firefox/IE/Opera too)

### Expected behavior:
Configuring LDAP Connection
* 

### Actual behavior:
Error while Installing LDAP Integration, After Mapping Configuration error "StatusCode: 500 {"error":"Data too long for column 'handler' at row 1"}"
After that everytime I click on the Integration Again the "Counting Users" loop starts.

Tried all these Points, restored to Snapshot before Zammad Installation an started over when unsuccessful (Logfile of Installation attached)
[zammad_install.txt](https://github.com/zammad/zammad/files/1278041/zammad_install.txt)

-Tried ldap|ldaps and IP|fqdn in LDAP Config, no success
-Left LDAP Group Mapping empty, no success
-Ldap Auth user with|without "CN=..."

* 

### Steps to reproduce the behavior:
- Installation according to https://docs.zammad.org/en/latest/install-ubuntu.html 
- Basic Installation with the Wizard
- Configuration of the LDAP Integration (see Screenshots)
(The Ldap Configuration works flawless in our OTRS Installation, i´ve copied it from Config.pm)
* 
![2017-09-21 14_25_56-zammad helpdesk - ldap](https://user-images.githubusercontent.com/29147370/30695804-c963856e-9ed9-11e7-9999-f43d30411706.png)
![2017-09-21 14_26_30-zammad helpdesk - ldap](https://user-images.githubusercontent.com/29147370/30695801-c9518102-9ed9-11e7-8157-2a01131873f1.png)
![2017-09-21 14_27_01-zammad helpdesk - ldap](https://user-images.githubusercontent.com/29147370/30695802-c95d9ff0-9ed9-11e7-9bbb-e000e651718b.png)
![2017-09-21 14_27_41-zammad helpdesk - ldap](https://user-images.githubusercontent.com/29147370/30695805-c963bb88-9ed9-11e7-8f16-57b946ee139c.png)
![2017-09-21 14_28_03-zammad helpdesk - ldap](https://user-images.githubusercontent.com/29147370/30695806-c98a9488-9ed9-11e7-9a68-f75405a7d489.png)
![2017-09-21 14_29_05-zammad helpdesk - ldap](https://user-images.githubusercontent.com/29147370/30695803-c961a708-9ed9-11e7-8b8b-81c446b52260.png)

**Comment by thorsteneckel** [comment]
Hi @lorenzgroup - Thanks for reporting. It's an issue with the logic for handling asynchronous tasks not limited directly to LDAP. I'll have a look and fix it. I keep you updated. Thanks for reporting.

**Comment by Felix1356** [comment]
I have the same error.
Microsoft Windows Server 2012 R2 AD LDAP Integration
German language

**Comment by thorsteneckel** [comment]
This is fixed within the current development release and will be part of the next Zammad release in the next couple of days. Feedback would be great!
