### ISSUE TITLE
after Update to 2.0 under Debian 8 login site can not be found

### ISSUE THREAD

**Issue by PatrickGoenner** [zammad/zammad#1459]
Hi,

after updating to 2.0 under Debian 8, the login site can not be found with port 3000, nginx is running. I'm no Debian expert, so I need your help. Is it possible, that the default port was changed? How can I test and fix it?

Thanks and Regards
Patrick

**Comment by thorsteneckel** [comment]
Hi @PatrickGoenner - This is an duplicate of #1430.
