### ISSUE TITLE
No Zammad after Upgrade to 2.x

### ISSUE THREAD

**Issue by WASDIT** [zammad/zammad#1462]
After upgrade from 1.5.x to 2.0.x it wont work anymore.
There seems to play a problem with the DB Migration.

StatusCode: 500
{"error":"FEHLER:  Spalte »access« existiert nicht\nLINE 1: SELECT \"groups_users\".user_id,group_id,access FROM \"groups_u...\n                                               ^\n"}

**Comment by thorsteneckel** [comment]
Hi @WASDIT ! Seems that some/the DB migrations didn't run. Can you please run `rake db:migrate` or `zammad run rake db:migrate` depending on your installation source?

**Comment by WASDIT** [comment]
Worked - Problem solved! Thanks
