### ISSUE TITLE
support Weibo OAuth2 login

### ISSUE THREAD

**Issue by NeverMin** [zammad/zammad#1465]
Sina Weibo social media as Twitter-Like in China. I'll add Weibo login for Zammad. About Sina Weibo more: http://ir.weibo.com/

**Comment by muhammadn** [comment]
Have you tried using Generic OAuth2 just to check if weibo has any other layers? (eg. OpenID connect uses OAuth2 but has a layer on top of it)

Site:  http://api.t.sina.com.cn/oauth/authorize
Authorize URL: /oauth/authorize
Token URl: /oauth/access_token

**Comment by NeverMin** [comment]
Hi @muhammadn , thank you, I knew that, I tried Generic OAuth2 no work.

**Comment by muhammadn** [comment]
Did you also set any "Redirect URL" option to yourhost/auth/oauth2/callback when configuring your weibo app page?

**Comment by NeverMin** [comment]
Hi @muhammadn , Yes, I did. but other question, the login button need to name **Weibo** by vendor (Sina) request, if not you only test by yourself.

e.g.:
![weibo login button](https://user-images.githubusercontent.com/2797432/30814382-9396f47c-a242-11e7-8ac4-7e70e8edefa8.jpg)

anyway, Weibo login finish soon and make a PR later.

test information:
https://test.zammad.org.cn
WeiboID: `echo "MTg5MTM1MjAzODMK" | base64 -d`
Password: `echo "WmFtbWFkVEVTVDIwMTcK" | base64 -d`

WeiboID is my phone number, so mask here.
