### ISSUE TITLE
Apache configuration broken after upgrade to zammad 2.0

### ISSUE THREAD

**Issue by TheRich-71** [zammad/zammad#1470]
### Infos:

* Used Zammad version: 2.0.0-15054682
* Used Zammad installation source: (source, package, ...) deb-package
* Operating system: Debian 8.9
* Browser + version: Firefox 55.0.3

### Expected behavior:

* Login via http://<FQDN>:3000/#login should return login page

### Actual behavior:

* Connection is reset, no hints in apache logfiles

### Steps to reproduce the behavior:

* Used Debian system with zammad 1.5.X, and apache config from /contrib-folder, upgrade to zammad 2.0.0

**Comment by monotek** [comment]
Port 3000 runs only on localhost from zammad 1.6. 
Zammad needs to be accessed via port 80.

**Comment by TheRich-71** [comment]
Thanks for the hint, that might be the issue. Could you add some advice how to configure apache to serve zammad besides further services on Port 80? I would prefer something like http://FQDN/zammad/, but am not experienced enough to change the config accordingly...

**Comment by monotek** [comment]
Not sure if this will work.
Just use a fqdn.
