### ISSUE TITLE
no test e-mail

### ISSUE THREAD

**Issue by sidescraper** [zammad/zammad#1471]
* Used Zammad version: 2.0.0
* Used Zammad installation source: package stabile
* Operating system: Ubuntu 16.04
* Browser + version: Chrome 60.0.3112.113

It is possible to disable that no test e-mail will sent to emailtrytest at znuny.com
Thank you

**Comment by martini** [comment]
Hi @sidescraper 

currently not. Background: To verify if email processing is working we try to send an email to emailtrytest. This is the last step in the email configuration.

We can add a config option / ui option to prevent this. Any other ideas?

 -Martin

**Comment by sidescraper** [comment]
It is possible to customize this e-mail address. Send this to me

**Comment by NeverMin** [comment]
[Yes, see here](/zammad/zammad/blob/c71b0d36d4fcefdaae4e39f1859094727a3ca74c/lib/email_helper/probe.rb#L308)

**Comment by sidescraper** [comment]
404 Not Found?

**Comment by NeverMin** [comment]
paste as code:
`https://github.com/zammad/zammad/blob/c71b0d36d4fcefdaae4e39f1859094727a3ca74c/lib/email_helper/probe.rb#L308`

**Comment by MrGeneration** [comment]
The external sending probe is a mandatory process of Zammad. For this reason you will not be able to disable this.
Nevermin has provided a option to "use your own" mail address if needed. Please however note that this may lead to issues if  external sendouts are not possible in your environment.

We're currently in the process of improving the overall situation like so:
   * we'll adjust the test alias Zammad uses within the next weeks to one that
      * uses Zammad GmbH resources and thus rules out third parties
      * has a name which clearly suggests what it's for
   * to help further, this alias has it's own mail domain `discard.zammad.org`.
     This allows us to provide a dedicated landing page for this specific use case telling the admin "why".

We hope this approach is acceptable for most of our users. We've had very view questions regarding our probing mechanism and email address  that's used for it in the past 4 years. So it's either unknown to people or counted as non relevant.

---

If you believe that this approach is still not good enough, please create a feature request here:
https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6
