### ISSUE TITLE
Email immer noch auf English

### ISSUE THREAD

**Issue by stephono** [zammad/zammad#1472]
Hallo zusammen,
leider habe ich das Problem, dass Emails immer noch auf Englisch verschickt werden.

Die Defaultsprache ist Deutsch.
`cat /etc/default/locale
LANG=de_DE.UTF-8
`
Das Webinterface ist in Deutsch. Das Funktioniert bereits.
Hier wurde das Problem bereits schon einmal beschrieben. Leider scheint der Bug noch nicht vollständig weg zu sein.
https://github.com/zammad/zammad/issues/429

Hat jemand einen Tip für mich?

**Comment by monotek** [comment]
Please use English only in our bugtracker.
