### ISSUE TITLE
Create single-line Multiselector

### ISSUE THREAD

**Issue by mrflix** [zammad/zammad#148]
![screen shot 2015-10-13 at 10 04 22](https://cloud.githubusercontent.com/assets/60777/10449143/dc243990-7191-11e5-960c-4178549fc429.png)
This one is ugly. Maybe a dropdown with checkboxes. Something like this with checkboxes:
![screen shot 2015-10-13 at 10 05 49](https://cloud.githubusercontent.com/assets/60777/10449166/120624ba-7192-11e5-8d4f-e751fbca3966.png)

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
