### ISSUE TITLE
Roles and Groups

### ISSUE THREAD

**Issue by edneymatias** [zammad/zammad#1480]
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: package
* Operating system: Debian Jessie
* Browser + version: 61.0.3163.100

This is a question.

How am I supposed to combine the roles and the groups? Specifically, why do I have to set group access on role creation and on role attribution? While I create a role with agent access level, I have to set group access:

![image](https://user-images.githubusercontent.com/22533602/30891911-21839d66-a30c-11e7-8618-00cbe632dfab.png)

And I'm also supposed to do the same thing while giving the agent role to a new user:

![image](https://user-images.githubusercontent.com/22533602/30891977-70867974-a30c-11e7-8843-d3d7b2a4cdef.png)

I watched the movie on this page https://zammad.com/business-features/role-management a couple of times but I'm still lost. The thing just seems redundant to me but I think I just didn't figure it out.

Is there any doc that clears the things out?

It would be great to have a look on it.

Thank you!

**Comment by budakmaran** [comment]
For me, Agent <--> Group <--> Roles is like creating a predefined permission (for large setup).

Let says i have 20 groups. (Group 1,2,3,4,5,6,7,8, ... , 20)

And i have a few users that want :
Full access on  Group 1 untill 10
Read only on group 11 untill 15
Read and cerate on group 16 untill 20

So i create this new role that represent above permission , and then assign them to the agent.
Next time if i have additional agent that need the same permission, i just have to assign the role to them. (As the role already covered the permission)

This will be a huge help if you have a large setup.

**Comment by edneymatias** [comment]
Maybe I'm trying to apply a complex approach to a simple scenário. I have two teams, the desk service, and the second level. Tickets may come from different e-mail channels. These will determine the operator on the second level. So I'm considering mapping the two teams into two roles and just ignore the possibility to fine tune on role attribution. But I agree with you, in a large setup, the roles came in hand.

**Comment by thorsteneckel** [comment]
Please continue over at https://community.zammad.org if still required since we are managing bugs only over here.
