### ISSUE TITLE
Automation does not work 

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#1484]
Automations do not work. The log files does not show any log entries that are relevant. 

![image](https://user-images.githubusercontent.com/6099976/30936781-2a8b830a-a3d5-11e7-9c38-11766570b432.png)

What possibilities exist for debugging? Or is it not working, because Debian 9 is not official supported yet?

### Infos:

* Used Zammad version: v2.0
* Used Zammad installation source: source
* Operating system: Debian 9
* Browser + version: Chrome 61

**Comment by monotek** [comment]
Please use only english language for issues in our bugtracker. Don't hesitate to reopen when translated.

**Comment by MDXDave** [comment]
@monotek Sorry, my fault. Can you please reopen the issue?

**Comment by muhammadn** [comment]
@MDXDave could you add the steps for you did for the automation and what is the Expected result and actual result?

**Comment by budakmaran** [comment]
scheduler running ?
zammad@shell > ps aux | grep zammad

you should something like 'scheduler'

**Comment by MDXDave** [comment]
Scheduler is running (with high cpu load):

> zammad    1250  0.2  6.9 1208388 283048 ?      Sl   Sep27   4:16 puma 3.9.1 (tcp://localhost:3000) [zammad]
zammad    1584 84.5  8.7 1378100 353776 ?      Sl   Sep27 1428:53 scheduler
root     16492  0.0  0.0  12780   984 pts/1    S+   02:21   0:00 grep zammad

Steps to reproduce:
1. Click on "Automation"
2. New Automation
3. Name: Delete Spam
4. Time: every hour at xx:00
5. Tags _contains one_ "spam" or "Spam"
6. Preview shows 169 results
7. Changes on objects: Action -> delete

**Comment by muhammadn** [comment]
@MDXDave I have tested it on `develop` branch of zammad and did exactly as you did.

1. I go to 'Scheduler'
2. Click on "New Scheduler"
3. Name: Delete Spam
4. Time: (I select all, so it will still run at intervals of 10 minutes)
5. Tags contains one `Spam` `spam`
6. Preview says the amount which is correct (in my case for testing i have 2)
7. Changes on Objects: Action -> Delete

After 10 minutes interval, i went back to  `Delete Spam` Schedule and in the `Preview` it is 0 which means all were deleted.

Note: In the tickets overview, make sure that the tickets you want to delete to be either tagged as `Spam` or `spam` or else it won't delete.
