### ISSUE TITLE
Role - Group cant be unchecked

### ISSUE THREAD

**Issue by chrklo** [zammad/zammad#1488]
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: RPM
* Operating system: SLES12
* Browser + version: Chrome

### Expected behavior:

* It should be possible to uncheck all group settings under "agent - Access to Agent Tickets based on Group Access"

### Actual behavior:

* Its not possible to uncheck the last one - since you made one check

### Steps to reproduce the behavior:

* 1) check a box
![image](https://user-images.githubusercontent.com/28293610/31006269-53a004f0-a4fc-11e7-8e40-59279c1acd05.png)
2) Submit
3) Re Open the Role
4) Uncheck
5) Submit

--> Re Open the check still there

**Comment by chrklo** [comment]
off topic:

Still not possible to check both "agent..." AND "customer..."

see - https://github.com/zammad/zammad/issues/1307

**Comment by thorsteneckel** [comment]
This is fixed in the latest version of develop ~30 minutes from now. Feedback is highly appreciated.
