### ISSUE TITLE
Problem with the OAuth2 authetication

### ISSUE THREAD

**Issue by lucianogarciaz** [zammad/zammad#1490]
Hello! 
I have a problem with the OAuth2 authetication.
When my OauthServer response the user data, zammad answers me : 422: The change you wanted was rejected.
In the logs files i can see: "  Attribute 'login' required! (Exceptions::UnprocessableEntity)
/zammad/app/models/user.rb:864:in `check_login' "

My response code from Oauth/token is : 
```
{ client: 
   { id: 1,
     client_id: 'democlient',
     redirect_uri: 'http://helpdesk.palpitos24.com.ar:7180/auth/oauth2/callback',
     scope: 'read',
     client_secret: 'democlientsecret',
     grants: 
      [ 'authorization_code',
        'password',
        'refresh_token',
        'client_credentials' ],
     redirectUris: [ 'http://helpdesk.palpitos24.com.ar:7180/auth/oauth2/callback' ] },
  user: 
   { id: '423',
     username: 'intento',
     password: 'intento',
     scope: 'profile',
     login: 'login',
     firstname: 'usuario',
     lastname: 'garcia',
     email: 'abasdf@gmail.com',
     phone: '155784340' },
  access_token: '1c6e6d46a0163ee301d0777daf341ed07fd1af7f',
  refresh_token: 'b4693af6c4f82202f1ca2911cae6322538a52b81',
  authorizationCode: '97ccabbc0193d6b2389df5722cdf6556',
  accessToken: '1c6e6d46a0163ee301d0777daf341ed07fd1af7f',
  accessTokenExpiresAt: 2017-09-21T23:11:25.370Z,
  refreshToken: 'b4693af6c4f82202f1ca2911cae6322538a52b81',
  refreshTokenExpiresAt: 2017-10-05T22:11:25.370Z,
  scope: true 
}
```
 I dont know what im doing wrong. 😖

Thank you!

**Comment by muhammadn** [comment]
Hi @lucianogarciaz. Thank you for reporting. Could you tell us the version of your Zammad as well?

Also i hope you can give about 10 lines of the error in the log so we can easily trace back where it went wrong.

The error usually indicates that there is no 'login' parameters in the oauth2 response.

**Comment by lucianogarciaz** [comment]
Hi, I'm so sorry for my delay. 
The version of zammad is 1.5.x

The 10 lines of the error: 
`I, [2017-08-30T17:15:10.369331 #1]  INFO -- : Completed 200 OK in 77ms (Views: 12.5ms | ActiveRecord: 8.6ms)
I, [2017-08-30T17:15:13.701833 #1]  INFO -- : 2017-08-30T17:15:13+0000: [Worker(host:e182a3d8ea36 pid:1)] Job BackgroundJobSearchIndex (id=1889) RUNNING
I, [2017-08-30T17:15:13.707823 #1]  INFO -- : # curl -X POST "http://zammad-elasticsearch:9200/zammad_production/User/19" \
I, [2017-08-30T17:15:13.727585 #1]  INFO -- : # 200
I, [2017-08-30T17:15:13.731137 #1]  INFO -- : 2017-08-30T17:15:13+0000: [Worker(host:e182a3d8ea36 pid:1)] Job BackgroundJobSearchIndex (id=1889) COMPLETED after 0.0290
I, [2017-08-30T17:15:13.735456 #1]  INFO -- : 2017-08-30T17:15:13+0000: [Worker(host:e182a3d8ea36 pid:1)] Job Observer::UserDeviceLogJob (id=1890) RUNNING
I, [2017-08-30T17:15:13.765075 #1]  INFO -- : Send notification to: a@gmail.com (from Notification Master <noreply@palpitos24.com.ar>)
I, [2017-08-30T17:15:17.285852 #1]  INFO -- : 2017-08-30T17:15:17+0000: [Worker(host:e182a3d8ea36 pid:1)] Job Observer::UserDeviceLogJob (id=1890) COMPLETED after 3.5502
I, [2017-08-30T17:15:17.290631 #1]  INFO -- : 2017-08-30T17:15:17+0000: [Worker(host:e182a3d8ea36 pid:1)] Job Transaction::BackgroundJob (id=1891) RUNNING
I, [2017-08-30T17:15:17.303135 #1]  INFO -- : 2017-08-30T17:15:17+0000: [Worker(host:e182a3d8ea36 pid:1)] Job Transaction::BackgroundJob (id=1891) COMPLETED after 0.0123
I, [2017-08-30T17:15:17.743145 #1]  INFO -- : Scheduler running...
I, [2017-08-30T17:15:28.215793 #1]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2017-08-30T17:15:34.210262 #1]  INFO -- : Started POST "/api/v1/users" for 10.42.124.208 at 2017-08-30 17:15:34 +0000
I, [2017-08-30T17:15:34.218184 #1]  INFO -- : Processing by UsersController#create as HTML
I, [2017-08-30T17:15:34.218316 #1]  INFO -- :   Parameters: {"0"=>"{\"firstname\":\"nombre\",\"lastname\":\"apellido\",\"email\":\"email@email.com\",\"organization\":\"Palpitos Test\",\"password\":\"palpitos2014\"}"}
I, [2017-08-30T17:15:34.624814 #1]  INFO -- : Authentication against Auth::Internal for user a@gmail.com ok.
E, [2017-08-30T17:15:34.753512 #1] ERROR -- : Attribute 'login' required! (Exceptions::UnprocessableEntity)
/home/zammad/app/models/user.rb:864:in `check_login'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in `block in halting'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
/usr/local/bundle/gems/activemodel-4.2.7.1/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
/usr/local/bundle/gems/activemodel-4.2.7.1/lib/active_model/validations.rb:338:in `valid?'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:58:in `valid?'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:83:in `perform_validations'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:43:in `save!'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `block in save!'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `save!'
/home/zammad/app/controllers/users_controller.rb:180:in `create'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'`

**Comment by thorsteneckel** [comment]
Please update to the latest version of Zammad and give feedback if the issue still persists.
