### ISSUE TITLE
Report / Statistic question

### ISSUE THREAD

**Issue by budakmaran** [zammad/zammad#1494]
### Infos:

* Used Zammad version: 2.0.0
* Used Zammad installation source: Source
* Operating system: Centos 7
* Browser + version: *

1. Where i can get the report/statistic module ? is this available on current stable release (2.0.0)

2. Where i can get zammad database schema ? 

Thanks

**Comment by babakkazemi** [comment]
Hi,

see #1455 or #929

**Comment by thorsteneckel** [comment]
Hi @budakmaran - @babakkazemi (our statistics issue expert 🤓 ) is right. This is a duplicate. Reporting will be available in the upcoming release 🚀
