### ISSUE TITLE
Tag Dropdown

### ISSUE THREAD

**Issue by SimonWerner** [zammad/zammad#1498]
### Infos:

* Used Zammad version: 2.x
* Used Zammad installation source: (source, package, ...) :package
* Operating system: Ubunutu 16.04 LTS
* Browser + version: Vivaldi

### Expected behavior:

* We want to have a dropdown list with available tags for tagging tickets, because we don't not want to add new tags by the agents. The agents should know which tags are available instead of "guess" which tags are already implemented.

### Actual behavior:

*  I have to type in the first capital of a tag before i get a list of available tags.

### Steps to reproduce the behavior:

* Try to add an existing tag to a ticket

**Comment by SimonWerner** [comment]
Great it works! Double "Space" and the list is shown!
Thank you very much!

**Comment by fthommen** [comment]
This is a long awaited feature.  Thanks a lot!  But there is still a small issue with it (#1540).

**Comment by thorsteneckel** [comment]
Fixed with the help of @umarsheikh - Thanks!
