### ISSUE TITLE
Nothing useful to see 

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#1500]
Hi There!

here is a Ticket with a typical conversation. If you scroll down, to see what has been discussed, you see ...

![grafik](https://user-images.githubusercontent.com/210874/31149052-f15c302a-a88e-11e7-9f7e-ccf364fbcfa9.png)

... nothing. I can post this screenshot with this internal conversation of our company without any problems here, because zammad fills the screen with no information at all. 

* Please fill the unused spaces
* Please remove "hi <name>" and quotes of the previous mail in this short view
* Please remove newlines in this view
so that the user get's informed as quickly as possible.

**Comment by martini** [comment]
Hi @zabarabab 

I guess almost all issues are changed/fixed with Zammad 2.0. 😳

Do you want to give it a try? I believe you will like it.

PS: I'm only your site the next 3 days.

 -Martin

**Comment by zabarabab** [comment]
Great! See you in a few hours! ;-)
