### ISSUE TITLE
Prevent disabling of Admin role

### ISSUE THREAD

**Issue by PatrickGoenner** [zammad/zammad#1501]
Hi,
unfortunately, I have deactivated the admin role, because of a wrong understood configuration step after upgrading to version 2.0.x

How can I reset my user account to admin?

Regards
Patrick

**Comment by thorsteneckel** [comment]
Hi @PatrickGoenner - We will prevent this in the future. In the meantime use the [Zammad Rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console) and execute the following code: `Role.find_by(name: 'Admin').update(active: true)`.

**Comment by PatrickGoenner** [comment]
Thanks a lot, it works again.

**Comment by yasirazgar** [comment]
@thorsteneckel I would like to work on this, please let me know if any one is already working on it.

**Comment by thorsteneckel** [comment]
@yasirazgar - feel free! Currently nobody is working on it.

**Comment by yasirazgar** [comment]
@thorsteneckel, Sorry I am some what familiar with CoffeeScript, I am totally new to this kind of architecture were we use models and controllers for the view, I am not sure how to connect and communicate between a model and controller, is there any docs to refer and get familiar.
Thanks!

**Comment by thorsteneckel** [comment]
Hi @yasirazgar - You can access the model or any instances of it via a Rails similar API. The used framework is called `spine.js`. Find the docs here: http://spine.github.io/api/models.html Other controllers might be an inspiration for how things work.

If there are any questions feel free to ask.

**Comment by yasirazgar** [comment]
Hi @thorsteneckel, please take a look at this commit, https://github.com/yasirazgar/zammad/commit/bb1c58f80a970d23afbe7294949fc39872b252e3

I added a method in role model (role.rb) for checking whether the role is admin, and I am trying to use it the view and disable the active/inactive select, if the role is admin, but its working, I am stuck, can you please help me out.
Thanks!

**Comment by martini** [comment]
I just saw this issue right now, maybe it's already fixed in Zammad 2.1?

https://github.com/zammad/zammad/issues/1563 -> So disabling Admin role would only work if there is another role with admin permission exists.

**Comment by thorsteneckel** [comment]
Sorry @yasirazgar - seems like @martini has fixed this already by fixing the related issue #1563 . Closing now.
