### ISSUE TITLE
Missing placeholder: last public article. Was: Mail to customer on update incl. the public note

### ISSUE THREAD

**Issue by sschroll** [zammad/zammad#1502]
### Infos:

* Used Zammad version: 2.0.X
* Used Zammad installation source: DPM
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Chrome 61

### Expected behavior:

- Customer opens ticket
- Agent replies via public note
-> Zammad sends mail to customer that the ticket has been updated incl. the note, not just a link.

### Actual behavior:

Serveral variables, but no one seems to work:
 
#{ticket.created_by.note}
#{ticket.updated_by.note}
#{ticket.customer.note}
#{user.created_by.note}

### Steps to reproduce the behavior:

* See "Expected behavior"

**Comment by Mirtaaa** [comment]
function can be implemented in the current Zammad standard using #{last_external_article.body}.
