### ISSUE TITLE
Tags in Time Accounting Export

### ISSUE THREAD

**Issue by bkolbe** [zammad/zammad#1506]
Edited by *@MrGeneration* to meet our current standards.

### Infos:

* Used Zammad version: 3.0 and earlier
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1044671

### desired behavior
This helps e.g. for categorizing (discounts because of different sales stuff) during an Excel export.

*original post*
```
Hi all,
it would be nice to see tags in time accounting CSV-Export.

We would like to add tag billing to a ticket to see if accounted time can be billed to customer.
```

**Comment by KoJie** [comment]
if I understand the goal correctly, the different Accounted-Times are to be distinguished in their kind. For this, there is the following implementation proposal: 
https://github.com/zammad/zammad/issues/4533
