### ISSUE TITLE
New Verification Email not working

### ISSUE THREAD

**Issue by gmartires** [zammad/zammad#1507]
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: (source, package, ...)Deb install
* Operating system: Ubuntu 16.04
* Browser + version: Edge

### Expected behavior:

* After new accounts are created a verification email is send out or when the client clicks on forgot password to do a password reset

### Actual behavior:

* The verification email is not reaching zimbra mail server neither gmail

### Steps to reproduce the behavior:

* I used the SMPT settings as well as the default settings for notification. I do get ticket updates and follow ups but I cant receive verification emails

**Comment by muhammadn** [comment]
Are you able to connect to the SMTP port of your zimbra server **from** your zammad server? If you can't you need to check your firewall settings if it allows outgoing port 25 from your zammad server.

Ticket updates are usually gotten from your POP3/IMAP server for incoming email while SMTP is for outgoing email.

**Comment by gmartires** [comment]
This issue had my mind busy all afternoon yesterday. The documentation is not explicit when it comes to the Mailing Server system that doesnt install with Zammad. I didn't have Postfix install and so there was no way for zammad to send out notifications or an error or warning. I installed php-mail just in case too but zammad is working properly now.

**Comment by gmartires** [comment]
How do you mark this issues as fixed! so others don't make the same mistake I made?

**Comment by muhammadn** [comment]
I don't think installing php-mail did help though but i think installing postfix did helped.

You can just close the issue and that's about it. Everything we talked on this issue is public so anyone can view it. Thanks!

**Comment by gmartires** [comment]
I did that earlier but then I couldn't find the thread..but ok. Thanks
