### ISSUE TITLE
Domain Users only! Question

### ISSUE THREAD

**Issue by gmartires** [zammad/zammad#1511]
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: (source, package, ...) DEB
* Operating system: Ubuntu 16.04 Xenial
* Browser + version: Edge

### Question:

I'm very new to zammad but I think is a great ticketing solution. The best ive seen hands down! I have had few hiccups but overall it was really easy to install and set up. I have 2 questions tho:

1. is it possible to limit costumer account creation to only one domain? I understand that the ldap integration would create the accounts from your domain but would that deny anybody else from creating tickets or costumer accounts

2. How do you access the rail console to delete tickets or users from zammad. I have no experience or knowledge of rails, I was able to install in the server but every time I execute a command it doesn't work for me because obviously have no clue. 
```

`root@svr:/home/administrator# rails -v
Rails 5.1.4

root@svr:/home/administrator# zammad run rails c
Loading production environment (Rails 4.2.9)
irb(main):001:0> Ticket.find(19012).destroy
ActiveRecord::RecordNotFound: Couldn't find Ticket with 'id'=19012
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/composite_primary_keys-8.1.6/lib/composite_primary_keys/core.rb:53:in `find'
        from (irb):1
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/console.rb:110:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/console.rb:9:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands.rb:17:in `<top (required)>'
        from /opt/zammad/bin/rails:4:in `require'
        from /opt/zammad/bin/rails:4:in `<main>'
irb(main):002:0>
`
```

Anyways.. Any help would be greatly appreciated it Thank you so much before hand!!!

**Comment by hanneshal** [comment]
Hi @gmartires 

thanks for the compliments.

1) No this is not possible at the moment. You can allow account creation or disable it. See the admin interface. If you allow it, everyone could register. If you don't allow it. Only existing customers, managed by your admins, can login. 

2) You are at the right place. Just the number you provided does not exist. Maybe this is a ticket number and not an ID? You can find the id in the url, when the ticket is open. 
Ticket.find_by(number: '123456') would show a ticket by number, not by id.

regards
Johannes

**Comment by gmartires** [comment]
Awesome!!! that worked great.! Thank you so much. 
I tried deleting users as well and is not working. I found information to find users and do role assignments but no too delete.
I tried :::

`irb(main):003:0* User.find_by(email:'email@domain.com').destroy
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_17354e2aa6" on table "stores"
DETAIL:  Key (id)=(15) is still referenced from table "stores".
: DELETE FROM "users" WHERE "users"."id" = $1
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:173:in `exec_delete'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:119:in `delete'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/relation.rb:478:in `delete_all'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:487:in `destroy_row'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/counter_cache.rb:152:in `destroy_row'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/locking/optimistic.rb:115:in `destroy_row'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/persistence.rb:172:in `destroy'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/callbacks.rb:292:in `block in destroy'
... 6 levels...
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:281:in `block in destroy'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:220:in `transaction'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/transactions.rb:281:in `destroy'
        from (irb):3
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/console.rb:110:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/console.rb:9:in `start'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/commands.rb:17:in `<top (required)>'
        from /opt/zammad/bin/rails:4:in `require'
        from /opt/zammad/bin/rails:4:in `<main>'
`
I also tried to create an schedule to delete customers but the conditions aren't narrowing or finding the user I need to delete . Is there any other way to delete users?

**Comment by thorsteneckel** [comment]
Hi @gmartires - The error message states that there are still records connected with the user. This can be tickets or any other objects. In your case it seems to be an Avatar or attachment in the `stores` table. Zammad stops you from deleting the user because this will lead to issues with the application. Because of the still existing object Zammad might want to show it in the interface but can't since the user is missing. This will crash the application and Zammad avoids it this way. So you need to find all related objects based on the error messages you get and delete them in the right order...

I would suggest you to just disable the user.

**Comment by gmartires** [comment]
Well some of those users were marked as spam and I was able to delete all the tickets associated with them. Also all the users are inactive and as I mentioned I'm new to ruby in rails and I wasn't sure about Zammad's behavior. Would deleting the ticket also destroyed the attachments? . I'm just trying to figure out if is an issue or something I'm missing =( 


Gabriel Martires 
Information Technology Manager 
Email: gmartires@selma-al.gov 

----- Original Message -----
