### ISSUE TITLE
TimeAccounting ticket condition prevents submit of Zoom

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1513]
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: git
* Operating system: Mac OSX
* Browser + version: any

### Expected behavior:

The TimeAccounting configuration checks of a ticket is relevant for accounting the spend time. It stores the time accordingly. Changes to the ticket are possible in any case.

### Actual behavior:

The TimeAccounting configuration checks of a ticket is relevant for accounting the spend time and fails due to the not supported condition `contains not one` of the Tag attribute. This is likely true for other conditions.

### Steps to reproduce the behavior:

* Activate TimeAccounting
* Ensure that there is at least one Tag present
* Configure TimeAccounting ticket selection for attribute `Tags` -> `contains not one` and select the Tag
* Open any Ticket to enter Zoom
* Add article (important!)
* Try to submit changes/article
* Notice error in the browser console (`Uncaught Unknown operator: contains one not`)

https://github.com/zammad/zammad/blob/4fab8007e403fa5e32186efdf62497d7c38bbe2b/app/assets/javascripts/app/controllers/ticket_zoom.coffee#L759

https://github.com/zammad/zammad/blob/4fab8007e403fa5e32186efdf62497d7c38bbe2b/app/assets/javascripts/app/models/ticket.coffee#L224

https://github.com/zammad/zammad/blob/4fab8007e403fa5e32186efdf62497d7c38bbe2b/app/assets/javascripts/app/controllers/_ui_element/ticket_selector.coffee#L41

**Reference Ticket# 109657**

**Comment by martini** [comment]
@hiendinhngoc thanks for the hint. It's fixed now in develop & stable.
