### ISSUE TITLE
Oauth access token url is 404

### ISSUE THREAD

**Issue by DRSchlaubi** [zammad/zammad#1516]
Hey,
I tried to make an oauth login with zammad but i always get the unable to fetch user profile error.
So I want to know why https://zammad/oauth/token not exsists and if i should use oauth or oauth2

Bye,
Schlaubi

**Comment by muhammadn** [comment]
Did you set the callback URL in your provider to be https://zammad/auth/oauth2/callback ?

Yes, we do't have such path /oauth/token only /auth/oauth2 (for initiating the OAuth2)

**Comment by DRSchlaubi** [comment]
yes id did

**Comment by thorsteneckel** [comment]
Hi @DRSchlaubi - Please re-open a new issue and fill out our issue template. Add a detailed step-by-step description on how to reproduce the issue which is currently not clear to me. If it's just a technical question please refer to our http://community.zammad.org/ board. Thanks for your understanding.
