### ISSUE TITLE
Security Issue: Blacklisting Parameters Allows to Inject Custom Behavior

### ISSUE THREAD

**Issue by togiberlin** [zammad/zammad#1520]
### Infos:

* Used Zammad version: latest ```develop``` branch
* Used Zammad installation source: from ```source```
* Operating system: not relevant
* Browser + version: not relevant

### Expected behavior:
* The standard Ruby on Rails approach is to whitelist parameters. This means, that you have to explicitly tell Rails, which parameters are allowed. All other, unknown parameters are blocked for security reasons.
* [Railsguides: strong parameters](http://guides.rubyonrails.org/action_controller_overview.html#strong-parameters) 

### Actual behavior:
* Inside [app/controllers/applications_controller.rb:60](https://github.com/zammad/zammad/blob/develop/app/controllers/applications_controller.rb#L60), all parameters are allowed by default (blacklisting approach). Later, some parameters, which need to be protected, are removed from ```all```.

Code snippet:
```ruby
 def clean_params
   params_data = params.permit!.to_h
   params_data.delete('application')
   params_data.delete('action')
   params_data.delete('controller')
   params_data.delete('id')
   params_data.delete('uid')
   params_data.delete('secret')
   params_data.delete('created_at')
   params_data.delete('updated_at')
   params_data
 end
```
* All parameters are allowed by default. This approach brings security issues.
* Problem: if Zammad developers forget to delete an important parameter from ```all```, it allows hackers to add custom behavior to the app.

### Steps to reproduce the behavior:

* Go to [app/controllers/applications_controller.rb:60](https://github.com/zammad/zammad/blob/develop/app/controllers/applications_controller.rb#L60)

**Comment by togiberlin** [comment]
## Solution Proposal
Stick to the official [Rails conventions](http://guides.rubyonrails.org/action_controller_overview.html#strong-parameters) and only whitelist parameters. By default, all unknown parameters have to be rejected.

**Comment by martini** [comment]
Thanks @togiberlin for the issue. We also use whitelist parameters, but one level higher (since we support additional attributes - a admin can define additional attributes for models).

The code for it is here: https://github.com/zammad/zammad/blob/develop/app/models/application_model/can_cleanup_param.rb#L10

So you still see a security issue?

**Comment by togiberlin** [comment]
OK, my alarm bells were ringing because I learned Rails according to the official conventions.
So as far as I understand, this was a conscious decision - to support customization capabilities. 

Then, for me it's fine to close this ticket.
