### ISSUE TITLE
Missing create/add customer from ticket

### ISSUE THREAD

**Issue by morphxle** [zammad/zammad#1522]
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: ubuntu deb
* Operating system: ubuntu

### Expected behavior:
create user directly from the change user in a ticket - i think that has worked in a old version. 

![2](https://user-images.githubusercontent.com/16727925/31394257-30e74e2e-adde-11e7-902f-fda4a8c51553.PNG)

### Actual behavior:
no way to create a customer directly from ticket, but its possible from a new ticket. 

![new](https://user-images.githubusercontent.com/16727925/31394477-b5a0a930-adde-11e7-91d0-5ac008bfac0f.PNG)

### Steps to reproduce the behavior:
try it ^^

**Comment by muhammadn** [comment]
This is fixed in commit https://github.com/zammad/zammad/commit/10dc56c7b8c949658d03ab6a6b7fe8fb98082d3e

So closing.
