### ISSUE TITLE
official composite key gem is available for Rails 5.1

### ISSUE THREAD

**Issue by muhammadn** [zammad/zammad#1523]
### Infos:

* Used Zammad version: develop
* Used Zammad installation source: (source, package, ...) source
* Operating system: macOS Sierra
* Browser + version: Chrome 61

### Expected behavior:

* Travis Build successfully

### Actual behavior:

* Travis Build fails

### Steps to reproduce the behavior:

* Make a pull request after modifying some code.

The issue is that the branch of composite key gem which is from a forked repo: https://github.com/jkowens/composite_primary_keys has removed their `rails-5_1` and the original repository of composite primary key gem (https://github.com/composite-primary-keys/composite_primary_keys) has already updated to the latest version to support rails 5.1.

More details from composite [here](https://github.com/composite-primary-keys/composite_primary_keys/commit/d0ba96d4f44b008496cf891bfb964b54d28c1e8b)

**Comment by thorsteneckel** [comment]
Thanks for the nice spot! Fixed with https://github.com/zammad/zammad/commit/eccf00ade4889601e28382929f8b7c653bd5eb95 as stated in #1521.
