### ISSUE TITLE
Unable to show overview if selected order by attribute is not show in header

### ISSUE THREAD

**Issue by martini** [zammad/zammad#1528]
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: (source, package, ...)
* Operating system:  any
* Browser + version: any

### Expected behavior:

* Allow overviews order by with attributes are not shown in overview

### Steps to reproduce the behavior:

* Create a overview with order by attribute "created_at"
* Do not select "created_at" as shown attribute

 -=> If you click on created overview, no ticket will get shown.

**Comment by thorsteneckel** [comment]
JFI: Short script to discover broken overviews:

```ruby
Overview.find_each do |overview|

  order_by = overview.order[:by]

  found = true
  overview.view.each do |view, attributes|

    next if view.to_s == 'view_mode_default'

    next if attributes.include?(order_by)
    found = false
    break
  end

  next if found

  p overview
end
```

**Comment by martini** [comment]
@thorsteneckel thanks for that. Fix is already on CI runners. 🌲
