### ISSUE TITLE
Apache webserver doesnt respond anymore

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#1529]
Hi,

I have tried to install you latest version on the vm (openstack) by using Apache as webserver, Centos as the OS, and mysql as the database. I have used the previous version of httpd config for zammad as follow:

cat /etc/httpd/conf.d/zammad.conf 
_# this is the apache config for zammad
# https://github.com/zammad/zammad/tree/develop/contrib/apache2
<VirtualHost *:80>
    # replace 'localhost' with your fqdn if you want to use zammad from remote
    ServerName localhost
    ## don't loose time with IP address lookups
    HostnameLookups Off
    ## needed for named virtual hosts
    UseCanonicalName Off
    ## configures the footer on server-generated documents
    ServerSignature Off
    ProxyRequests Off
    ProxyPreserveHost On
    <Proxy localhost:3000>
    Require local
    </Proxy>
    ProxyPass /assets !
    ProxyPass /favicon.ico !
    ProxyPass /robots.txt !
    ProxyPass /ws ws://localhost:6042/
    ProxyPass / http://localhost:3000/
    DocumentRoot "/opt/zammad/public"
    <Directory />
        Options FollowSymLinks
        AllowOverride None
    </Directory>
    <Directory "/opt/zammad/public">
        Options FollowSymLinks
    Require all granted
    </Directory>
</VirtualHost>_

Once installation finished, zammad is not reachable on the browser anymore. When I check the services I see:
systemctl status zammad
● zammad.service
   Loaded: loaded (/etc/systemd/system/zammad.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-10-12 12:45:19 UTC; 5min ago
 Main PID: 2412 (sleep)
   CGroup: /system.slice/zammad.service
           └─2412 /bin/sleep infinity

Oct 12 12:45:19 en-utilisantoauth systemd[1]: Started zammad.service.
Oct 12 12:45:19 en-utilisantoauth systemd[1]: Starting zammad.service...

systemctl status zammad-web
● zammad-web.service
   Loaded: loaded (/etc/systemd/system/zammad-web.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-10-12 12:45:19 UTC; 5min ago
 Main PID: 2413 (sleep)
   CGroup: /system.slice/zammad-web.service
           └─2413 /bin/sleep infinity

Oct 12 12:45:19 en-utilisantoauth systemd[1]: Started zammad-web.service.
Oct 12 12:45:19 en-utilisantoauth systemd[1]: Starting zammad-web.service...

systemctl status zammad-web-1 -l
● zammad-web-1.service
   Loaded: loaded (/etc/systemd/system/zammad-web-1.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-10-12 12:45:19 UTC; 5min ago
 Main PID: 2414 (ruby)
   CGroup: /system.slice/zammad-web-1.service
           └─2414 puma 3.9.1 (tcp://127.0.0.1:3000) [zammad]                               

Oct 12 12:45:48 en-utilisantoauth zammad-web-1.service[2414]: => Booting Puma
Oct 12 12:45:48 en-utilisantoauth zammad-web-1.service[2414]: => Rails 4.2.9 application starting in production on http://127.0.0.1:3000
Oct 12 12:45:48 en-utilisantoauth zammad-web-1.service[2414]: => Run `rails server -h` for more startup options
Oct 12 12:45:48 en-utilisantoauth zammad-web-1.service[2414]: => Ctrl-C to shutdown server
Oct 12 12:45:48 en-utilisantoauth zammad-web-1.service[2414]: Puma starting in single mode...
Oct 12 12:45:48 en-utilisantoauth zammad-web-1.service[2414]: * Version 3.9.1 (ruby 2.4.1-p111), codename: Private Caller
Oct 12 12:45:48 en-utilisantoauth zammad-web-1.service[2414]: * Min threads: 5, max threads: 30
Oct 12 12:45:48 en-utilisantoauth zammad-web-1.service[2414]: * Environment: production
Oct 12 12:45:48 en-utilisantoauth zammad-web-1.service[2414]: * Listening on tcp://127.0.0.1:3000
Oct 12 12:45:48 en-utilisantoauth zammad-web-1.service[2414]: Use Ctrl-C to stop

Then, when I wanna access the web application via wget I see:
wget http://127.0.0.1:3000
--2017-10-12 12:52:04--  http://127.0.0.1:3000/
Connecting to 127.0.0.1:3000... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
index.html: Permission denied
Cannot write to ‘index.html’ (Permission denied).
I found it i cannot access zammad from web browser and it shows:
 
_refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED_

I thought its due to firewall but all are disabled.

Am I missing something? or did I misconifgured something that disregards your latest version of Zammad?

Thank you,

**Comment by hamzehmohammadnia** [comment]
*update:

I have just tried with zammad version 1.5 with all the same os and conditions. It worked properly once installation finished. Im wondering what has been added or changed in zammad version 2.0 that caused this situation.

**Comment by Netsky349** [comment]
Hello,

I have the same problem when I want to update zammad 1.5. x to 2.0 and every time I update zammad I have the same error. For the moment I'm using my snapshots to go back but I would like to have the latest version.

I use centos 7 and the httpd run.

refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by monotek** [comment]
Whats the output of:

* systemctl status httpd

How about checking the apache logs?

**Comment by hamzehmohammadnia** [comment]
Still having the same problem. I address here all the status of services:

 httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-10-18 10:38:41 UTC; 1min 7s ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 16054 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=0/SUCCESS)
 Main PID: 16059 (httpd)
   Status: "Total requests: 3; Current requests/sec: 0; Current traffic:   0 B/sec"
   CGroup: /system.slice/httpd.service
           ├─16059 /usr/sbin/httpd -DFOREGROUND
           ├─16060 /usr/sbin/httpd -DFOREGROUND
           ├─16061 /usr/sbin/httpd -DFOREGROUND
           ├─16062 /usr/sbin/httpd -DFOREGROUND
           ├─16063 /usr/sbin/httpd -DFOREGROUND
           ├─16064 /usr/sbin/httpd -DFOREGROUND
           └─16178 /usr/sbin/httpd -DFOREGROUND

Oct 18 10:38:41 X systemd[1]: Starting The Apache HTTP Server...
Oct 18 10:38:41X httpd[16059]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using ::1. Set the 'ServerName' directive globally to suppress this message
Oct 18 10:38:41 X systemd[1]: Started The Apache HTTP Server.



● zammad.service
   Loaded: loaded (/etc/systemd/system/zammad.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-10-18 10:38:45 UTC; 1min 54s ago
 Main PID: 16077 (sleep)
   CGroup: /system.slice/zammad.service
           └─16077 /bin/sleep infinity
Oct 18 10:38:45 X systemd[1]: Started zammad.service.
Oct 18 10:38:45 X systemd[1]: Starting zammad.service...

 zammad-web-1.service
   Loaded: loaded (/etc/systemd/system/zammad-web-1.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-10-18 10:38:45 UTC; 2min 24s ago
 Main PID: 16081 (ruby)
   CGroup: /system.slice/zammad-web-1.service
           └─16081 puma 3.9.1 (tcp://127.0.0.1:3000) [zammad]                               
Oct 18 10:38:52 X zammad-web-1.service[16081]: => Booting Puma
Oct 18 10:38:52 X zammad-web-1.service[16081]: => Rails 4.2.9 application starting in production on http://127.0.0.1:3000
Oct 18 10:38:52 X zammad-web-1.service[16081]: => Run `rails server -h` for more startup options
Oct 18 10:38:52 X zammad-web-1.service[16081]: => Ctrl-C to shutdown server
Oct 18 10:38:52 X zammad-web-1.service[16081]: Puma starting in single mode...
Oct 18 10:38:52 X zammad-web-1.service[16081]: * Version 3.9.1 (ruby 2.4.1-p111), codename: Private Caller
Oct 18 10:38:52 X zammad-web-1.service[16081]: * Min threads: 5, max threads: 30
Oct 18 10:38:52 X zammad-web-1.service[16081]: * Environment: production
Oct 18 10:38:52X zammad-web-1.service[16081]: * Listening on tcp://127.0.0.1:3000
Oct 18 10:38:52 X zammad-web-1.service[16081]: Use Ctrl-C to stop

firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)


Still after checking the http://IP:3000/ I see no the same error that I faced at the begining of this post.

**Comment by monotek** [comment]
`[Wed Oct 18 10:39:08.258483 2017] [proxy:error] [pid 16060] (13)Permission denied: AH00957: HTTP: attempt to connect to 127.0.0.1:3000 (localhost) failed`

I guess you forgot to exec the selinux command after installation:
* setsebool httpd_can_network_connect on -P

**Comment by hamzehmohammadnia** [comment]
I have disabled selinux, it didnt work out. I have enabled and then executed yours and then:

This site can’t be reached
http://X/ is unreachable.
ERR_ADDRESS_UNREACHABLE

**Comment by monotek** [comment]
Please post output of:
* netstat -tlpen

**Comment by hamzehmohammadnia** [comment]
Please, here is the output:

[root@X]# netstat -tlpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      0          13680      1/systemd           
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          18535      1353/sshd           
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      1001       20504      1744/puma 3.9.1 (tc 
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      0          17911      1314/master         
tcp        0      0 127.0.0.1:6042          0.0.0.0:*               LISTEN      1001       20503      1746/script/websock 
tcp6       0      0 :::111                  :::*                    LISTEN      0          13679      1/systemd           
tcp6       0      0 :::80                   :::*                    LISTEN      0          19944      1720/httpd          
tcp6       0      0 :::22                   :::*                    LISTEN      0          18537      1353/sshd           
tcp6       0      0 ::1:25                  :::*                    LISTEN      0          17912      1314/master         
tcp6       0      0 :::443                  :::*                    LISTEN      0          19952      1720/httpd          
tcp6       0      0 :::3306                 :::*                    LISTEN      27         19652      1603/mysqld

**Comment by martini** [comment]
> [Wed Oct 18 10:39:08.258483 2017] [proxy:error] [pid 16060] (13)Permission denied: AH00957: HTTP: attempt to connect to 127.0.0.1:3000 (localhost) failed

For me it looks definitely as config issue. Is selinux really disabled and did you reboot the machine to apply the changes?

**Comment by martini** [comment]
And also verify if a firewall is blocking the request to 127.0.0.1:3000

**Comment by hamzehmohammadnia** [comment]
I found this issue not only on one instance, but on four: openstack cloud, two other VPSs, all usign Centos 7.x.

Here is the output of getenforced:
#getenforce  
Disabled
 # cat /etc/sysconfig/selinux 
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=disabled
# SELINUXTYPE= can take one of three two values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected. 
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted

I have also rebooted after changing from enabled to disabled. One more time now.

**Comment by martini** [comment]
Hi @hamzehmohammadnia 

I can't see what the output for selinux is, can you check it with "sestatus".

I also have Zammad running on similar environment (expecting Apache) on about 400 CentOS 7 setups. All working very well with *enabled* selinux. 

 -=> I'm sorry, I do not have any more ideas what's going wrong on your side.

 -Martin

**Comment by monotek** [comment]
Did you also added the firewalld rules?

* firewall-cmd --zone=public --add-service=http --permanent
* firewall-cmd --zone=public --add-service=https --permanent
* firewall-cmd --reload

**Comment by hamzehmohammadnia** [comment]
I have just built another installation with configuring Selinux permissive and adding http and https rules for firewalld and everything came back up. Thank you @monotek and @martini 
Bests
