### ISSUE TITLE
Inserting space character in translations (in Overviews menu item and User menu)

### ISSUE THREAD

**Issue by fkonigy** [zammad/zammad#1531]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: source
* Operating system: Ubuntu 16.04 - 64bit
* Browser + version: Firefox 55.0.2

### Expected behavior:

* When translating Overview menu items (e.g. items like My assigned Tickets) I need to insert space between translation words.

### Actual behavior:

*  Currently it is not possible to insert space between translation words. First I encountered it when translating to Persian language, then tried it in English language and it behaves the same way.

### Steps to reproduce the behavior:

* Change user langue to Persian.
* Click on Overviews menu item.
* Press Ctrl+Shift+T
* Click on My assigned Tickets item.
* Translate to Persian and press space.

![screenshot-2017-10-13 zammad helpdesk - my assigned tickets](https://user-images.githubusercontent.com/30512114/31523399-1eec0d0c-afc0-11e7-8400-6376cbb62417.png)
![screenshot-2017-10-13 zammad helpdesk - dashboard](https://user-images.githubusercontent.com/30512114/31523400-1ef9aa52-afc0-11e7-8689-a0bf2ebcc582.png)

**Comment by thorsteneckel** [comment]
This is fixed with the changes above and will be available in ~15 minutes from now in the develop and stable package 🚀
