### ISSUE TITLE
Zammad in docker (update)

### ISSUE THREAD

**Issue by sandrodz** [zammad/zammad#1532]
Is there a dedicated instructions on how to update zammad in docker container?

Will pulling container files from github and down/up be sufficient?

**Comment by martini** [comment]
Hi @sandrodz

I'm not sure, but issues sounds link questions and not issues? And also it sounds like docker related, not to Zammad.

Did you know the https://github.com/zammad/zammad-docker-compose repo?

-Martin

**Comment by sandrodz** [comment]
Thanks!
