### ISSUE TITLE
E-Mail size

### ISSUE THREAD

**Issue by Bueschel** [zammad/zammad#1534]
### Infos:

* Used Zammad version: 2.0.0
* Operating system: Ubuntu 16.04
* Browser + version: Firefox 56.0 (64bit)

If I try to send e-mails outgoing with a attachment I receive a warning "Message size exceeds fixed maximum message size"
I can't find the value of the message size for ingoing and outgoing mails with attachments. My question now is, which is the maximum size of attachments enclosed to a email and is it possible to change it?

**Comment by fabianlaule** [comment]
Go to the administration panel, choose the email channel and switch to "Settings". The standard email size limit are 10 MB. :)

![image](https://user-images.githubusercontent.com/10254363/31588253-abfb7a08-b1ef-11e7-86ff-60806d8241d0.png)

**Comment by Bueschel** [comment]
Thank you very much, that's it.
Sometimes you never see the woods for the trees.
