### ISSUE TITLE
Ticket Mail template

### ISSUE THREAD

**Issue by linushstge** [zammad/zammad#1537]
### Infos:
* Used Zammad version: 2.0.x
* Used Zammad installation source: Debian Package
* Operating system: Debian 8.9
* Browser + version: Google Chrome 61

### Expected behavior:
* If I'm right, changes on the file `config/initializers/html_email_style.rb` should be applied on restart?

### Actual behavior:
* Changes will not applied after zammad restart. Is the file described here: https://github.com/zammad/zammad/commit/16594b8245bc76c190a99558cc05b1342c48167e still in use?

My suggestion: Move all templates into the GUI backend :)

**Comment by thorsteneckel** [comment]
Sorry I don't understand the issue. Seems more like a question? However, yes all changes to files in `config/initializers/` are only loaded when all Zammad services are restarted. This is actually a Rails thing. Please see the official Rails documentation for more information:

http://guides.rubyonrails.org/configuring.html
http://guides.rubyonrails.org/initialization.html
