### ISSUE TITLE
Tag dropdown too short

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#1540]
### Infos:

* Used Zammad version: 2.0.0-1507606633.98c9e056.jessie
* Used Zammad installation source: DEB from Repo
* Operating system: Debian 8 Jessie
* Browser + version: Firefox 50.1.0

### Issue:

The tag dropdown - triggerable by typing two blanks, see #1498 - shows only ten entries. Instead it should show _all_ available tags to make such a dropdown usable.  To save space it can/should be scrollable.

**Comment by thorsteneckel** [comment]
See: 

Zammad:
https://github.com/zammad/zammad/blob/757f0ac9bddaf348a6929bcf7d43d1180ea106f4/app/controllers/tags_controller.rb#L8
`params[:limit] || 10`

And: [jQuery Autocomplete](https://jqueryui.com/autocomplete/#maxheight)

**Comment by fthommen** [comment]
> Keep in mind that an unlimited query might lead to performance issues in systems with a lot of tags!

then one could make it configurable: "show complete tag dropdown" -> y|n.  However I hope that you agree, that showing an incomplete menu is useless.

Alternative: Make the entered text being matched against _a substring_ and not the beginning of existing tags (`.*MYENTEREDTEXT.*` vs. `^MYENTEREDTEXT.*`).

**Comment by fthommen** [comment]
IMHO the classification as "proposal" is not adequate. This is a "bug" - albeit not a critical one :-).

**Comment by MrGeneration** [comment]
Just a small follow up, we're currently evaluting if raising this limit is "good enough".
For this, we're currently checking how "bad" a scrollbar will be ( #2570 ) and how much items are resonable before we cut the results. (in my opinion showing 200 elements is not reasonable, nobody will -ever- scroll through that and actually find what he searches for :D)

Secondly, we've decided to adress substring search ( #2569 ) which your issue partly covers. I wanted to seperate this, so in case this is still not a good solution for you, we still have the initial request. :-)

**Comment by fthommen** [comment]
Thx. I agree with the length issue.  I am also in favor of substring search

**Comment by MrGeneration** [comment]
By now issues #2570 and  #2569 have been adressed.
Is this good enough for your use case or do you still prefer a longer list than 10 entries for tags?

Just making sure the issue still makes sense. :-)

**Comment by fthommen** [comment]
I haven't seen the scrollbar from #2570 in our instance yet, but the alone the fulltext search from #2569 already solves the usability issues (even better than a scrollbar).  That was a great idea, thanks.
