### ISSUE TITLE
copy and paste in mail notification triggers

### ISSUE THREAD

**Issue by Kartoiser** [zammad/zammad#1548]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: IE12 (Edge)

### Expected behavior:

* copy and paste of content of mail notification triggers

### Actual behavior:

* Zammad is not able to copy and paste the html structure, but plain text or copy and paste to e.g. MSWord and then copy and paste again back is working

**Comment by hanneshal** [comment]
Exact, wanted behaviour at the moment. We might add HTML editor features later. But right now, it works as designed.

regards
Johannes
