### ISSUE TITLE
Calendar as filter condition for Trigger/Automatization

### ISSUE THREAD

**Issue by Kartoiser** [zammad/zammad#1553]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: IE12 (Edge)

### Expected behavior:

Would be great to have these filters available in trigger view:
* time -> before/after time of day
* time -> multiselect for hour and minute
* day of week -> multiselect
* month -> multiselect
* year -> multiselect
* working hours -> bool; corresponding to calendar

### Actual behavior:

* no such filters

**Comment by thorsteneckel** [comment]
Hi @Kartoiser - this issue is now resolved because of payed prioritization. You can cover all Time and Date use cases now by creating a matching calendar or using an existing one. You can choose between matching times in the calendar time or outside. Closing now 🚀
