### ISSUE TITLE
filter for system notification comments

### ISSUE THREAD

**Issue by Kartoiser** [zammad/zammad#1555]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: IE12 (Edge)

### Expected behavior:

I'd like to suggest an new article type for mail notification comments created by system for filtering in triggers whether trigger is because of new article or because sent mail
(see also https://github.com/zammad/zammad/issues/1543#issue-266467992; maybe related)

### Actual behavior:

currently not able to filter for articles created by system as to no such filter

**Comment by martini** [comment]
How about this?

<img width="740" alt="screen shot 2017-10-18 at 15 33 49" src="https://user-images.githubusercontent.com/110226/31721486-cdedac2c-b419-11e7-8277-fdcf58da4d90.png">

**Comment by Kartoiser** [comment]
Is not working: please see https://github.com/zammad/zammad/issues/1543

**Comment by martini** [comment]
Thanks for feedback. So the feature is basically here but it's "just" not working?

**Comment by Kartoiser** [comment]
yapp :-)

**Comment by martini** [comment]
Ok. So I close the FR, because a  bug report for this is already existing.
