### ISSUE TITLE
Remote access for Zammad

### ISSUE THREAD

**Issue by gueeme** [zammad/zammad#1558]
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: (source, package, ...) DEB
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Chrome 61.0.3163.100 (remote host)

Hello,

How do I configure access to Zammad from other hosts?
I want to access it INTERNALLY at http://support.xyz.com.br for example. 
The system will not have public access
Listing this address in the zammad.conf file does not work. I can only access it from the local host.

What can I be doing wrong?

Ps: This address I'm trying to access does not have any DNS configuration.
If it is not possible to configure to access through a given IP and port on the network.

![2017-10-18 11_57_07-cmder](https://user-images.githubusercontent.com/19538568/31722871-fe7c041a-b3fb-11e7-86d3-3878fe47d2b2.png)

**Comment by martini** [comment]
Hi @gueeme 

thanks for you issue. For me it seems that it's more a nginx config questions?

If it is so, the better place for questions regarding Zammad config would be here:

https://zammad.org/participate

> Do you have questions about how to use Zammad?
 >Ask any question about how to use Zammad in the zammad-users mailing (https://groups.google.com/forum/?fromgroups#!forum/zammad-users) list.

Thanks a lot!

 -Martin
