### ISSUE TITLE
Admin Overviews: order table by prio. And help users to understand the concept.

### ISSUE THREAD

**Issue by mrflix** [zammad/zammad#156]
1. The overview table in the admin backend for overviews should be ordered by prio by default
   ![screen shot 2015-11-20 at 10 56 28](https://cloud.githubusercontent.com/assets/60777/11296933/630de4b4-8f75-11e5-8442-d3234bbd7f2b.png)
2. There should be an explanation text with the prio explaining the relation of direction and prio number: e.g. does a higher prio mean closer to the start or further away from the start?
   ![screen shot 2015-11-20 at 10 57 37](https://cloud.githubusercontent.com/assets/60777/11296962/8d2aa9f8-8f75-11e5-90a3-d98ee3d996c0.png)

**Comment by martini** [comment]
Is already changed. You can use d&d to for order position.

<img width="1274" alt="screen shot 2016-12-13 at 09 31 57" src="https://cloud.githubusercontent.com/assets/110226/21133005/12b5d7f4-c117-11e6-9c4d-2fe3e1988ea7.png">
