### ISSUE TITLE
translation strings wrong

### ISSUE THREAD

**Issue by Kartoiser** [zammad/zammad#1561]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: IE12 (Edge)

### Issue:
Language strings existing twice:
* ![unbenannt](https://user-images.githubusercontent.com/26098704/31734021-a9a6444a-b43d-11e7-9152-1cac39476264.jpg)
* ![unbenannt](https://user-images.githubusercontent.com/26098704/31735526-7b0ea7b2-b442-11e7-9ff4-7d447ea1b860.jpg)

Should not exist:
![unbenannt](https://user-images.githubusercontent.com/26098704/31734990-ba55c830-b440-11e7-849e-2f6adc3929ea.jpg)

**Comment by Kartoiser** [comment]
Because I found a lot more of these duplicates and orphans:
Maybe it would be best to create a "Delete" button?
(Doesn't hurt if they remain there ... but it's sometimes very confusing when having changed a string (or at least believing to have done) and the old one is still there ;-)

**Comment by hanneshal** [comment]
Can you provide a list of the found duplicates. 
In you first screenshot I see a small difference. "last vs latest". This is a result of changing texts during the time and needs to be cleaned up.

**Comment by Kartoiser** [comment]
> In you first screenshot I see a small difference. "last vs latest". This is a result of changing texts during the time and needs to be cleaned up.
Exactly :-)

> Can you provide a list of the found duplicates.
Where? Should I add them one by one (meaning: when I find them)?

**Comment by thorsteneckel** [comment]
Please provide a list over here. You can add more as you find them but remember that each written comment sends a mail to everybody watching this repository (currently 102 people). Thanks!

**Comment by dennykorsukewitz** [comment]
Here is a list with all obsolete or double translations.

[1561_translation_strings_wrong.txt](https://github.com/zammad/zammad/files/2483860/1561_translation_strings_wrong.txt)

**Comment by dennykorsukewitz** [comment]
Hi all,

most translations were obsolete and were removed on the i18n server.
Two more translations will be fixed accordingly.
