### ISSUE TITLE
prevent admin from locking out

### ISSUE THREAD

**Issue by Kartoiser** [zammad/zammad#1563]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: IE12 (Edge)

### Expected behavior:

system should
1. prevent admin from disabling admin rights
2. there should ALLWAYS be at least 1 (active) admin present

### Actual behavior:

1. If admin disables his admin role for "downgrading" his account (or by accident when trying to find the right settings) he will lock out himself.
2. When last admin account gets diabled (e.g. because of LDAP no more providing that account) there will not be no more possibility to assign new admin.
Then, you can only recover by manipulating database by Hand.

### Steps to reproduce the behavior:

1. disable admin role for currently logged in admin
2. a) disable last admin account by hand or b) assign admin role to only LDAP users and then make Zammad disable these accounts by either breaking connection / disabling LDAP integration / changing LDAP filter / changing assignement of roles / ...

**Comment by martini** [comment]
Thanks for the issue. There was already some kind of this functionality. But unfortunately only the relations where checked. Now also active states are checked too.

If you want to disable the role with last active admin permissions:
<img width="711" alt="screen shot 2017-10-20 at 13 03 17" src="https://user-images.githubusercontent.com/110226/31819122-7ebe1aa0-b59b-11e7-9637-3da1180a569b.png">

If you want to disable the last active admin it self:
<img width="696" alt="screen shot 2017-10-20 at 13 03 48" src="https://user-images.githubusercontent.com/110226/31819121-7ea1300c-b59b-11e7-866e-475fcc3dd9d8.png">
