### ISSUE TITLE
Group specific text modules

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#1565]
### Infos:

* Used Zammad version:  all
* Used Zammad installation source: any
* Operating system:  any
* Browser + version:  any

### Expected behavior:

* Text modules for specific groups, e.g. language related, topic related

### Actual behavior:

* All text modules are available in all groups

### Steps to reproduce the behavior:

* Add a text module, add two groups, use the text module in each group

**Comment by dennykorsukewitz** [comment]
The feature 'group-dependent text modules' was added: https://github.com/zammad/zammad/commit/c788c3e053abe4f96fc5e2597c527632e341fd9e

Available in version 3.1

**Comment by dennykorsukewitz** [comment]
duplication: https://github.com/zammad/zammad/issues/537
