### ISSUE TITLE
ObjectManager Attribute Select used in trigger will show internal ID instead of value

### ISSUE THREAD

**Issue by Kartoiser** [zammad/zammad#1568]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: IE12 (Edge)

### Expected behavior:

Placeholders should insert value 

### Actual behavior:

Placeholders insert key

### Steps to reproduce the behavior:

1) create ticket object "test" of type "select" with 1 item: key:1 / value:a
2) create trigger with action mail notification
3) insert into body: #{ticket.test}
4) create ticket
5) content of received mail will be "1" and not "a"

### Suggestion:

* either replace by value
* or make 2 placeholders: #{ticket.test.key} and #{ticket.test.value}

**Comment by SummerStorm** [comment]
Hi there, this new feature has been added to the development branch and will be formally released in version 2.8.0.

With a select attribute named `test`, `#{ticket.test}` will work exactly as before: display the key. The newly added syntax `#{ticket.test.value}` will display the value string associated with that key.
