### ISSUE TITLE
Improve i-doit filtering (without type)

### ISSUE THREAD

**Issue by Kartoiser** [zammad/zammad#1571]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: IE12 (Edge)

### Expected behavior:

ability to filter for i-doit items without selecting category (when category field is empty)

### Actual behavior:

you have to select correct category to being able to filter for desired item

**Comment by cwrm** [comment]
Hi, 

Zammad uses the i-doit API method cmdb.objects and sets an filter array with an empty type:

`array (  'method' => 'cmdb.objects',  'params' =>   array (    'apikey' => 'apikey',    'filter' =>     array (      'type' => '',      'title' => '%sturnen%',    ),  ),  'version' => '2.0',)`

That causes i-doit to find no objects. When no object type was choosen, the type key should be removed from the query:

`array (  'method' => 'cmdb.objects',  'params' =>   array (    'apikey' => 'apikey',    'filter' =>     array (       'title' => '%sturnen%',    ),  ),  'version' => '2.0',)`

chris

**Comment by martini** [comment]
@cwrm Thanks for the hint. It's fixed now in develop and stable.
