### ISSUE TITLE
Invert priority

### ISSUE THREAD

**Issue by Kartoiser** [zammad/zammad#1572]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: IE12 (Edge)

### Expected behavior:

Prio 1 should be high

### Actual behavior:

Prio 3 is high

**Comment by thorsteneckel** [comment]
Thanks for your proposal but this is intended and will not change. However, in the future there will be the possibility to change the default attributes and this will resolve this. There are plenty of issues regarding this like e.g. #1525. That's why I'll close this as a duplicate.
