### ISSUE TITLE
GitHub integration

### ISSUE THREAD

**Issue by Disane87** [zammad/zammad#1575]
Hey guys, thanks for the great product!
I'm just switching from Freshdesk to you. Freshdesks supports a GitHub integration to create dev tickets from the supportdesk. Is there any chance to get an integration for Zammad?

**Comment by muhammadn** [comment]
hi @Disane87, Currently there is no github integrations (to their webhook) except for logging into zammad using github accounts. But i think you can request here for that feature and probably the maintainer can put it as a feature request.

**Comment by muhammadn** [comment]
@Disane87 May i know the specific use case for the github integration? example: when a user creates an issue then the ticket is created?

**Comment by Disane87** [comment]
We get a lot responses from customers, many are feature request for our devs and normal tickets we can resolve at the support. The supporters collect all necessary data of the issue and should create a ticket in github for the devs. The process within git is transparent within the „normal“ ticket system and the supporter has the ability to watch the process and can contact the customer if some of the devs needs further information. 

A separation is needed, cause the entire planning of the dev tickets and requests are made in github.

**Comment by dnauck** [comment]
Could be related to #435

**Comment by yombo** [comment]
Would be great to have github <-> zammad integration. For example, if a use creates an issue in one of our many repos, it will show up in Zammad. We and then respond in Zammad and it pushes an update out to the correct repo and issue.

**Comment by orangesunny** [comment]
We would like to have an integration: button in Zammad agent and client portal. Ticket view.
 
Works: 
1. After the click, it will ask the agent to choose from list of GitHub repositories connected to Zammad instance. 
2. After choice, it will open a new issue with the information from the ticket in Zammad. 
3. The agent can modify and click to create a new issue.
