### ISSUE TITLE
Can't replay ticket without reply-to

### ISSUE THREAD

**Issue by kalabj** [zammad/zammad#1577]
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: package
* Operating system: centos
* Browser + version: Safari

### Expected behavior:

* answer to address in from field when reply-to is misssing

### Actual behavior:

* reply will be sent to recipent in from field

### Steps to reproduce the behavior:

* create ticket from email and account which don't fill reply-to header
* click "reply" located below of ticket header

![screen shot 2017-10-23 at 21 45 30](https://user-images.githubusercontent.com/317501/31909830-aaa0c17a-b83b-11e7-975d-a105f93e0ddb.png)

**Comment by rlue** [comment]
@kalabj, I'm having trouble understanding this bug. This is what I found in my own tests:

* If the customer **has no email address**, Zammad refuses to send the email. A modal alert appears on the screen that says "**Text missing:** Need recipient in 'To' or 'Cc'.", and a flash message appears in the ticket summary:

  ![Delivery failed: "Unable to send email to 'Jack Johnson': Can't use Channel::Driver::Smtp: #<Net::SMTPSyntaxError: 501 5.1.3 Bad recipient address syntax >"](https://user-images.githubusercontent.com/12194123/39686372-3ebc4ef2-51fb-11e8-996c-b94eddeb11a8.png)

* If the customer **does have an email address**, the email is successfully sent to the customer.

Specifically, re: 

> reply will be sent to recipent in from field

I never found that emails were sent to the **from** address.

Would you mind trying to reproduce this on a free http://zammad.com instance so we can reproduce it?

**Comment by martini** [comment]
One more note: Zammad tries to find the correct recipient. So @kalabj can you verify if your Zammad email address "Zammad@no" is existing as email address in Zammad (admin -> channel -> email -> accounts -> search for "Zammad@no")?

If not, Zammad means that this is not an own used email address and tries to respond to this address. Just create the "Zammad@no" address in admin -> channel -> email -> accounts for the related account and reply should work fine.

**Comment by rlue** [comment]
This issue is being closed due to inactivity, and may be reopened at any time at the original filer's request (or that of anyone who can help reproduce it).
