### ISSUE TITLE
Time accounting by day

### ISSUE THREAD

**Issue by jonasboettcher** [zammad/zammad#1580]
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: Ubuntu package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: Firefox 56.0 (64-Bit)

### Expected behavior:

* Alike #1007 it was nice to add a daily selector to the time accounting overviews in: http://zammad/#manage/time_accounting
With this feature I'd like to get an overview for any selected date, on which tickets somebody has been worked.

### Actual behavior:

* The time accounting overview only shows selectors for each year an month.

### Steps to reproduce the behavior:

* Go to "Admin" -> "Time accounting"

**Comment by rolfschmidt** [comment]
### Proposal

Maybe related to https://github.com/zammad/zammad/issues/4123#issuecomment-1549267400. If the export was moved to the Profile → Reports and extended similar, then a daily export would be possible.

**Comment by martini** [comment]
For me it's currently not clear if this issue is about exporting accounted time by day (not only my month) or only improve the view in the admin interface of the logged accounted time per month?

**Comment by KoJie** [comment]
this function is party covered by the reporting-tool. This is why we block this enhancement for now.
