### ISSUE TITLE
ticket auto assignment/dispatching to agents

### ISSUE THREAD

**Issue by vishnus** [zammad/zammad#1581]
Hi team, 

This was a feature we were trying to implement (PR #1574 ) since we have a relatively large support team. When you have several dozen agents and thousands of tickets coming in, manual ticket claims become very impractical. There may be confusion on what tickets to pick; multiple agents may try to pick the same ticket (there's no locking mechanism); if there are economic incentives, tickets may get hoarded. The distribution and resolution of tickets will become erratic and uneven.

With the automatic assignment, the burden of the assignment is not on the agent, but on the system. To start off with, a simple round-robin or random assignment of tickets to agents within a group will ensure even distribution. 

Features we'd like to see in Zammad related to this are:

1. Incoming ticket (via channels or manually created) should be automatically assigned evenly to the agents available in the group in which the ticket belongs.
2. Once the agent is working on the ticket, it should be locked so that no other agent can claim without explicit permission from the owner of that ticket.
3. From reporting perspective, if we can get how many tickets were closed by an agent for a given interval of time would help to decide on the agent performance, give economic incentives etc.
4. If an agent is on leave, or not active, the ticket should automatically get reassigned to another available agent.
5. This should be controllable using filters/triggers/settings since the auto-assignment of tickets may or may not be a required feature for all use cases (for example, we may not need auto-assignment for a particular email channel)

As described by @thorsteneckel in the PR, I'm opening an issue to discuss further on requirements and what could be a sustainable solution for this. 

Thanks

**Comment by martini** [comment]
Hi @vishnus 

you talking about auto dispatching of incoming tickets, right?

> Incoming ticket (via channels or manually created) should be automatically assigned evenly to the agents available in the group in which the ticket belongs.

What metric do you want to use? What if the agent is not online anymore but still has tickets assigned?

How about a  "auto assignment on first watch/open an ticket" (need much less logics)?

 -Martin

**Comment by vishnus** [comment]
@martini  We use conditions like last activity < 10 hours, agent not in vacation, agent has access to the ticket's group etc. And random assignment logic for small groups would be roundrobin of the agents that meet the criteria and if there are several agents, then any random assignment logic should serve. We have had this in production of osticket for over 3-4 years and works perfectly with an agent count of around 100.

**Comment by dominikklein** [comment]
Should already be possible in a easy way with https://github.com/zammad/zammad/issues/1825
