### ISSUE TITLE
Ticket creation API requires existing customer

### ISSUE THREAD

**Issue by jag82** [zammad/zammad#1582]
Via the API I wish to create a new ticket with an email that doesn't yet exist (e.g. that of the user who is filling out a contact form on my web page). 

Since this email does not belong to a Customer in my Zammad yet, I get the error:

{
    "error": "No lookup value found for 'customer': \"<test@test.test>\""
}

I believe it should automatically create a Customer. There is already a precedent for this when creating tickets via the UI.

**Comment by martini** [comment]
Hi @jag82 

can you add your payload?

PS: Did you try `customer_id: 'guess:test@test.test'` then it should work as expected.

 -Martin

**Comment by jag82** [comment]
Perfect. Your recommendation works :)

**Comment by martini** [comment]
Thanks for feedback, just updated https://docs.zammad.org/en/latest/api-ticket.html (guess feature).
