### ISSUE TITLE
Error 503 and Heavy Charge Server

### ISSUE THREAD

**Issue by Wisou** [zammad/zammad#1585]
### Infos:

* Used Zammad version: 2.1
* Operating system: Debian 8
* Browser + version: Firefox
* 4 CPU
* 8 GB RAM

* Environnement:
10 Agents
2000 Tickets
200 Users

Hello,

I have a same problem of this issue #1036.

Screenshot process without agents activity: 

![image](https://user-images.githubusercontent.com/30259860/32048435-cb344d5c-ba49-11e7-9f96-991a04a31078.png)

I do this query 'SELECT * FROM pg_stat_activity;'
OUTPUT in text file
[select.txt](https://github.com/zammad/zammad/files/1417931/select.txt)

In the production.log, we can see frequently this error:
E, [2017-10-26T12:14:02.099010 #14291] ERROR -- : #<JSON::ParserError: 765: unexpected token at ''>
E, [2017-10-26T12:14:02.123372 #14291] ERROR -- : error in reading/parsing session file '/opt/zammad/tmp/websocket_production/47039643882640/session', remove session.

Can you help me ?

BR

**Comment by thorsteneckel** [comment]
Hi @Wisou - sorry for the late response. We introduced quite a lot of performance improvements lately. Would be great if you check this with the latest Zammad develop version. If you still have this issue please reopen. Thanks!
