### ISSUE TITLE
No LDAP Connection possible

### ISSUE THREAD

**Issue by ruebenmaster** [zammad/zammad#1586]
Hallo thorsteneckel,
till 8 a.m. i'm fighting with the zammad ldap connection. First i have to learn to connect with email address an not with destinguished name. But all i try, i can't connect to the ldap server. The other servers like seafile or freeradius have no problem to connect with the same credentials to the same server.
Logfile:

[2017-10-26T11:49:39.749468 #715] ERROR -- : Can't connect to '10.250.4.55' on port '389', Can't bind to '10.250.4.55', 32, No Such Object (Exceptions::UnprocessableEntity)

He can't connect, but why? The other server are in the same network and have no problems with the connection to the LDAP server.

A chance to see more logfile infos? Infos that help to clear situation?

Greetings
ruebenmaster

zammad (newest version, update yesterday)
LDAP 389 (Kolab Installation)
Both on CentOS 7

I try your instructions to debug, without success. There are no entries in file:

drwxr-xr-x  4 zammad zammad    47 25. Okt 10:59 db
-rw-rw-r--  1 zammad zammad     **0** 26. Okt 12:45 debug_ldap.rb
-rw-r--r--  1 zammad zammad  2699 25. Okt 10:53 Gemfile

Connection with telnet on port 389 is successfull.

**Comment by thorsteneckel** [comment]
Hi @ruebenmaster. It seems like that there was a misunderstanding. The file `debug_ldap.rb` should contain the following ruby code with your credentials entered for `bind_user` and `bind_pw`:

```ruby
require 'net/ldap'
require 'net/ldap/entry'

bind_user = 'your.dn'
bind_pw   = 'your PW'

ldap = Net::LDAP.new(
  host: '10.250.4.55',
  port: '389',
)

ldap.auth(bind_user, bind_pw)

p ldap.get_operation_result
```

Afterwards run the file from your Zammad directory via `zammad run rails r debug_ldap.rb` or `rails r debug_ldap.rb` as zammad user, depending on your installation source (package/source)
Post the output here in this issue. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
At the end you can delete the `debug_ldap.rb` file.

**Comment by ruebenmaster** [comment]
Hallo,
i try it again. The output:

[root@zammad-server zammad]# zammad run rails r debug_ldap.rb
#<OpenStruct code=0, message="Success">

Greetings
ruebenmaster

**Comment by thorsteneckel** [comment]
Please retry it in the admin interface with the same credentials. Can you please provide a screenshot of the error in the admin interface and the whole `log/production.log`. You can send them to support@zammad.com and refer to me and this issue. Thanks!

**Comment by ruebenmaster** [comment]
Hallo thorsteneckel,
now it works.

Don't no why, but this retry works now. The binding to LDAP server is ready now. Thank you very much for help. If you want, i will sending you production.log file.

Greetings
ruebenmaster

**Comment by ruebenmaster** [comment]
Ok it works with help from thorsteneckel.

Thank you very much. 

Greetings 
ruebenmaster

**Comment by thorsteneckel** [comment]
Happy I could help 👍 No need for the production log.
