### ISSUE TITLE
Problem LDAP sync / server certificate does not macht

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1590]
Hello together 👋 

I just installed the newsted version of zammad (2.1.0-1508942269.c6ca66c3.xenial) and I noticed our LDAP-sync does not work anymore. I get the following error:
`Can't` connect to '172.16.230.70' on port '636', hostname "172.16.230.70" does not match the server certificate`

Sadly I can't change the sync to not use SSL verification and the server certificate originally belongs to another server.
So my question is, is there a way to tell zammad to ignore that error?

Greetings

**Comment by thorsteneckel** [comment]
Hi @MamoulianDelacroix - please restart the configuration of your LDAP connection. Zammad will ask you in the first step of the wizard if the SSL connection should be verified. You can disable it by choosing "no".
