### ISSUE TITLE
E-Mails not imported

### ISSUE THREAD

**Issue by screxx** [zammad/zammad#1593]
Hello,

I updated to Zammad 2.1.x and now the new emails are no longer imported and there is also no entry in the log files.

How can i fix this problem?

**Comment by martini** [comment]
Hi @screxx 

what is in the admin -> monitoring section? Any infos there?

 -Martin

**Comment by screxx** [comment]
Hi @martini 

there is also no info.. the status is green

**Comment by martini** [comment]
And the mailbox is still configured?

What if you execute fetching emails manually `zammad run rails r "Channel.fetch"`?

**Comment by screxx** [comment]
i execute the command manually an now the mails were imported

**Comment by monotek** [comment]
Please check if scheduler service is running:
* systemctl status  zammad-worker-1

**Comment by screxx** [comment]
Hi @monotek 

the scheduler service is running.

Where i can find the template?

**Comment by monotek** [comment]
Its shown automatically when you click on "New issue".

**Comment by martini** [comment]
If the mail is imported manually by "Channel.fetch", please check if the following entry is active:

```
zammad run rails c

s = Scheduler.find_by(method: 'Channel.fetch')

s.active

```

In case, set if active again:

```
s.active = true
s.save!
```

And restart the scheduler.

**Comment by screxx** [comment]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: (source, package, ...) : deb package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: Firefox / Safari last (last version)


### Expected behavior:

* 


### Actual behavior:

* mails not imported
* @martini i the entry is active but the mail is not imported automatically 


### Steps to reproduce the behavior:

* Send email

**Comment by martini** [comment]
I can't believe it. 🤔

@screxx is remote login possible (only zammad user is needed)?

**Comment by screxx** [comment]
@martini yes remote login is possible

**Comment by martini** [comment]
> @martini yes remote login is possible

Nice. Can you send the login credentials to support at zammad dot com?

**Comment by passboltUser** [comment]
I can at least confirm that this Feature is working. We are using the import like this: An Email is sent to tickets@....com, then Zammad2 checks if there are Emails in a certain folder and imports them. I'm talking about settings in here: `/#channels/email`. But I can also confirm that it was quite an act to set it up, many errors and Zammad2 wasn't connecting. Because it is working now, maybe it wasn't Zammand2's fault, so I didn't open an issue.

**Comment by passboltUser** [comment]
Now it's not working anymore. We haven't changed anything -- except the updates from official Zammad repo that came in -- and the to be imported emails are present in the email account, so it should work.

```
# apt policy zammad|head

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

zammad:
  Installed: 2.3.0-1517603814.5589b9cb.xenial
  Candidate: 2.3.0-1517603814.5589b9cb.xenial
  Version table:
 *** 2.3.0-1517603814.5589b9cb.xenial 500
        500 https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu 16.04/main amd64 Packages
        100 /var/lib/dpkg/status
     2.3.0-1517421506.32f17a3f.xenial 500
        500 https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu 16.04/main amd64 Packages
     2.3.0-1517404898.f02a3f4c.xenial 500
```
Tried:
```
/opt/zammad# zammad run rails r "Channel.fetch"
/opt/zammad#
```
`/opt/zammad# systemctl status zammad-worker-1`
-> `Active: active (running)`

```
# zammad run rails c
Loading production environment (Rails 5.1.4)
irb(main):001:0> s = Scheduler.find_by(method: 'Channel.fetch')
=> #<Scheduler id: 5, name: "Check Channels", method: "Channel.fetch", period: 30, running: 0, last_run: "2018-02-05 09:46:38", prio: 1, pid: "47091209485020", note: nil, active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-10-11 08:58:59", updated_at: "2018-02-05 09:46:38", error_message: "", status: "ok">
irb(main):002:0> s.active
=> true
irb(main):003:0> 
```

Any other commands I can try?

**Comment by thorsteneckel** [comment]
This is more a technical question to a single instance issue than a general one. So please continue over at https://community.zammad.org. Thanks for your understanding.

If you are using Zammad in a commercial environment and rely on it consider our services over at https://zammad.com/pricing
