### ISSUE TITLE
Reporting: Please add chart for open tickets

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#1597]
### Infos:

* Used Zammad version: 2.1.0
* Used Zammad installation source: deb
* Operating system: Debian 8
* Browser + version: Firefox on Debian 9

### Expected behavior:

* It would be nice to have a chart about tickets in state "open" (in contrast to "created" or "closed"). E.g. if there are yesterday, I had 90 open tickets and today I have 100 open tickets, I want to see this graphically, not the e.g. 20 that have been created and 10 that have been closed. (Of course, such a graph can only give an average or maximum or minimum for any given day.)

**Comment by thorsteneckel** [comment]
This is already possible. Just create a reporting profile that matches your needs:
![localhost_3000_](https://user-images.githubusercontent.com/3873515/39754958-3dcc5b44-52c4-11e8-92d5-cc77f42bda60.png)
