### ISSUE TITLE
"Allow past" setting is not respected

### ISSUE THREAD

**Issue by HappyTepid** [zammad/zammad#1598]
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: Zammad.org Ubuntu instructions
* Operating system: 16.04.3 LTS
* Browser + version: Chrome latest

### Expected behavior:

* It should not be possible to open a ticket if a date field attribute with "Allow past" set to yes has a date prior to today entered.

### Actual behavior:

* Customer can choose a past date and submit a ticket successfully. 

### Steps to reproduce the behavior:

* Go to Admin -> Objects -> Ticket -> New Attribute
* Select "Date" as Format, set "Allow Past" to No
* Make the attribute required for customer
* Update DB
* Login as customer and open a ticket with a date prior to today in the new attribute field

**Comment by SummerStorm** [comment]
Fixed via 444e48e.
