### ISSUE TITLE
Auto change owner

### ISSUE THREAD

**Issue by ninoprasetya** [zammad/zammad#1600]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: ubuntu package
* Operating system: ubuntu 16.04
* Browser + version: safari 11 with OSX

### Expected behavior:

* Once set the owner to the ticket, it should stay until its being closed

### Actual behavior:

* after some time the ticket change ownership to "-"
* there is no scheduler or trigger on my system that able to execute those action

### Steps to reproduce the behavior:

* assign a ticket to a user
* wait for serveral minutes/hours then the notification will pop up saying "-" has change ownership to "-"

**Comment by MBekspert** [comment]
First, check your assigment timeout setting. This causes the ticket to return to '-'.

**Comment by ninoprasetya** [comment]
Thx u. Missed that settings 👍
