### ISSUE TITLE
Webform isn´t available | 401 Unauthorized

### ISSUE THREAD

**Issue by svenschumacher** [zammad/zammad#1604]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: Package
* Operating system: Ubuntu Server
* Browser + version: Chrome 62 (latest)

### Expected behavior:

* The backend-generated form opens and is usable.

### Actual behavior:

The actual behavior appears since the upgrade to 2.1 via apt upgrade. 
* The form doesn´t open and a error message appears. 
* API response is {"error":"Not authorized"}
* The server logs "INFO -- : Completed 401 Unauthorized in 21ms (Views: 0.3ms | ActiveRecord: 15.3ms)"

### Steps to reproduce the behavior:

Just open https://wlanandcoffee.de/feedback

**Comment by nscheel-emmasbox** [comment]
same here, changed nothing but after update we cannot load the form.

I also tried to add in the nginx.conf:
```
...
location / {
...
if ($request_method ~* "(GET|POST)") {
         add_header "Access-Control-Allow-Origin"  *;
         }
 # Preflighted requests
    if ($request_method = OPTIONS ) {
      add_header "Access-Control-Allow-Origin"  *;
      add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS, HEAD";
      add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-T$
      return 200;
    }
...
```
It changed the error to 

> Request header field Access-Control-Allow-Origin is not allowed by Access-Control-Allow-Headers in preflight response.

we are on the same domain so CORS shouldn't be a problem.

**Comment by martini** [comment]
Hi,

Background: For security/spam reasons the web form has been extended to use tokens (is doing more in background before you will get able to use it). @nscheel-emmasbox  you also use the web form the normal way like @svenschumacher is doing it?

And what was the version which you updated from?

So 

 -Martin

**Comment by martini** [comment]
And please check also the following 2 settings:

1) Admin -> Channels -> Web -> Enable Ticket creation -> Yes

2) Admin -> Channels -> Form -> Feature need to be enabled

**Comment by nscheel-emmasbox** [comment]
we made some small changes to the form, like autofill from user and email but nothing more. 
And the update was from 2.1.x to 2.1.x so no major changes.

I checked: Admin → Channels → Web → Enable Ticket creation → and it was "no" 
So I switched to "yes" and now the form is working again. But in earlier versions, the form was also working with the status "no", so I didn't checked this possibility of this option affecting the form.

Thanks for the great support. Keep up the good work :+1:

**Comment by svenschumacher** [comment]
Thanks alot! The issue has been resolved by setting "Admin -> Channels -> Web -> Enable Ticket creation -> Yes" 
This wasn´t set after update. 

@martini Sorry, i don´t know from what version we came from. 

Thank you all very much!!

**Comment by martini** [comment]
Because we feel that it's not correct to involve another config option of "web channel" to the "form channel". We will remove the "Admin -> Channels -> Web -> Enable Ticket creation -> Yes" dependency for form channel again (so it will be compatible to Zammad 2.0).
