### ISSUE TITLE
StatusCode: 503

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#1605]
Infos:

Used Zammad version: 2.1.x
Used Zammad installation source: (source, package, ...) : RPM package for V1.5
Used Yum zammad update for upgrading to V 2.1
Operating system: Centos 7
Browser + version: Firefox / Safari last (last version)
Expected behavior:
Not facing error in during test/no-heavy-load

Actual behavior:
StatusCode: 503
Content:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>

I dont' know, just refreshing after updating to version 2.1

**Comment by monotek** [comment]
This is not a Zammad problem. 
Check your webserver logs.
