### ISSUE TITLE
searching for translations 

### ISSUE THREAD

**Issue by MBekspert** [zammad/zammad#1611]
### Infos:

I'm looking at where you can change the language of the communion or the message itself to another language

* Used Zammad version: 2.1.0-15095477
* Used Zammad installation source: package
* Operating system: Debian 9.2 (4.9.0-4-amd64)
* Browser + version: Firefox 56.0.1

### Expected behavior:

* translated messages

### Actual behavior:

* Writing an article, on the countdown window, the part is translated, still is Please enter your time... This text I want to change.
![obraz](https://user-images.githubusercontent.com/33098856/32380574-a7ad8c5a-c0b0-11e7-830e-ee0041db9068.png)

* On the password change page, when is too short and the message at the top of the page is in English

![obraz](https://user-images.githubusercontent.com/33098856/32380658-e225288e-c0b0-11e7-9d72-1aa48ffd6155.png)

### Steps to reproduce the behavior:

* switch to polish translation or another language ;)

**Comment by hanneshal** [comment]
Hi,

did you checked the interactive translation in the admin interface? This allows you to click on strings and translate them accordingly

regards
Johannes

**Comment by MBekspert** [comment]
Hi, yes I checked. Dont show this message.
