### ISSUE TITLE
SMTP settings will fail if "Notification Sender" does not belong to used smtp account

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#1612]
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: (source, package, ...)
* Operating system: Ubuntu 16.04
* Browser + version: 

### Expected behavior:

* Add SMTP account for "Email Notification" works without error

### Actual behavior:

* Fails if you already have set a "Notification Sender" which is not the address of the SMTP account you want to use.

Error Message:

"550-Requested action not taken: mailbox unavailable"

### Expected behavior:

Better error message or overwrite "Notification Sender" with the address of the SMTP account automatically.

**Comment by tiny6996** [comment]
please add the ability to change the Sender address instead of noreply@<hostname>

**Comment by martini** [comment]
The sender addresses of notifications can be already configured: Admin -> Channel -> Email -> Settings -> Notification Sender

Is that what you are looking for?

**Comment by monotek** [comment]
Yes, i know of the setting. 
If "Notification Sender" its already set, lets say to "yourmailaddress@server.de", and you try to change the SMTP settings for notifications to the smtp account of "yourothermailaddress@otherserver.de", and keep the old "Notification Sender" you'll run into an error.

**Comment by martini** [comment]
Thanks. How could we prevent his? If you change the setting we need to send an try mail/notification to check if it's working?

**Comment by monotek** [comment]
As the error is not clear it should:
* give a better error like: "SMTP Account does not match Notification Sender setting"
* or overwrite "Notification Sender" with the address from smtp settings

**Comment by tiny6996** [comment]
@martini  I think the best way to fix this is issue is allow you set the notification sender name when you configure an email address. during the initial setup. The issue that is happening is most email servers are not okay with someone saying they are x@localhost and the authenticate as y@domain.com. This is done to prevent impersonation. it is possible to do this via aliases however, it does not work seamlessly if you are hosting this as an internal site.

**Comment by thorsteneckel** [comment]
We're currently working through some of our issues. One part is to migrate the documentation issues over to the documentation. Unfortunately I'm having a hard time to understand the issue here at hand. Would someone can explain it in more detail so I can create an issue in the documentation repository for it? Screenshots or even a short video would be perfect.

I'll go ahead and close this issue for now and create the issue in the documentation repository once I got the required information at hand. Thanks for your support!
