### ISSUE TITLE
Adding attribute to object with Boolean type and default value gives SQL error

### ISSUE THREAD

**Issue by vishnus** [zammad/zammad#1613]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: source
* Operating system: Ubuntu
* Browser + version: Chromium
* DB: MySQL

### Expected behavior:

* Create a new attribute in object with default boolean value

### Actual behavior:

* 
Production.log:

Mysql2::Error: Invalid default value for 'new_column': ALTER TABLE `tickets` ADD `new_column` tinyint(1) DEFAULT 'false' (ActiveRecord::StatementInvalid)
/opt/zammad/.rvm/gems/ruby-2.4.1/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `_query'

### Steps to reproduce the behavior:

* 
Admin -> Objects -> New attribute -> Format as Boolean, display yes/no, default false

**Comment by umarsheikh** [comment]
hi @vishnus this is now fixed on https://github.com/zammad/zammad/pull/1617, thanks!

**Comment by muhammadn** [comment]
@vishnus This is fixed and should be available in 2.3.1. 🚀
