### ISSUE TITLE
Email Notification

### ISSUE THREAD

**Issue by amathar** [zammad/zammad#1614]
### Infos:

* Used Zammad version:   zammad-2.1.0-1509936117.b8f98730.centos7
* Used Zammad installation source: (source, package, ...) rpm
* Operating system: centos 7
* Browser + version: Firefox / Opera

### Expected behavior:

* send mail to customer when adding a ticket answer

### Actual behavior:

* write something to the ticket, "set to public", "update" but no mail is beeing send, no smtp connection is made to the smtp server

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment]
Make sure to use the right article attributes:

<img width="305" alt="bildschirmfoto 2017-11-06 um 13 27 34" src="https://user-images.githubusercontent.com/3873515/32441130-626b201a-c2f6-11e7-9c31-edecf5a99ff2.png">

**Comment by amathar** [comment]
May be I am stupid and do not understand how this software works. Yes, if I use the "mail" attribute and after I filled the "To" field, a mail is send to the customer.
But, the "to" field has to be filled manually, the email address of the customer is *not* filled in automaticly.
Bug or feature?

If i use the notice attribute, why is the customer not informed via mail about an update if i set the notice to public?

**Comment by martini** [comment]
Hi @amathar 

it's easier to use the reply actions (to is filled automatically).

<img width="693" alt="screen shot 2017-11-06 at 13 52 28" src="https://user-images.githubusercontent.com/110226/32441957-dfc72c90-c2f9-11e7-9ae9-b33c7e2c3edd.png">


In case you do not want the use this at all. You can create trigger to send an email automatically to the customer of the ticket by adding an external note.

Greetings,

 -Martin

**Comment by amathar** [comment]
Hi @martini,

understood. I will take a look at the trigger....
Thank you and greetings..

Peter
