### ISSUE TITLE
Visible organizsation content (organization profile) not updated

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#1616]
### Infos:

* Used Zammad version: latest
* Used Zammad installation source
* Operating system: CentOS 7
* Browser + version: FF, Chrome, Safari

### Expected behavior:

* After picking a user from the organization and disabling the user should be greyed out

### Actual behavior:

* The use is not greyed out, even after 10 minutes. Closing the organization and reopen it shows the expected behavior.

### Steps to reproduce the behavior:

* Pick an enabled user from an organization and disable the user. Visible check the user on the organization tab.

**Comment by thorsteneckel** [comment]
@SummerStorm let me know when you start working on this. I can give you an example on how to subscribe for changes on the instance.

**Comment by martini** [comment]
@SummerStorm as hint, there is a own controller for that widget/controller for avatars https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/widget/avatar.coffee

**Comment by martini** [comment]
@SummerStorm here the correct location of used controller https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/organization_profile.coffee#L191

**Comment by SummerStorm** [comment]
@martini Thanks for the hint, but I've already fixed the issue :). It's just missing one line ` active: true` in https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/organization_profile.coffee#L197

**Comment by martini** [comment]
@SummerStorm Nice! 😻

PS: Just updated the link above 10 sec. ago. You are right.

**Comment by SummerStorm** [comment]
Fixed by commit fb0ef19e7d3bd7dcde92752c9e5e4f24421fb3fd.
