### ISSUE TITLE
Set cookie Attribute "secure" if https is used.

### ISSUE THREAD

**Issue by jaykijay** [zammad/zammad#1619]
### Infos:

* Used Zammad version: all
* Used Zammad installation source: (source, package, ...) all incl your Site zammad.com
* Operating system:  all
* Browser + version:  Firefox 56

### Expected behavior:

Cookies have set the secure attribute if https is used.

### Actual behavior:
The host is running a server with SSL/TLS and is prone to information disclosure vulnerability.
The cookies:
Set-Cookie: _zammad_session_a138cfd0f37=***replaced***; path=/; HttpOnly 
are missing the "secure" attribute.

Solution

Set the 'secure' attribute for any cookies that are sent over a SSL/TLS connection.
The flaw is due to cookie is not using 'secure' attribute, which allows cookie to be passed to the server by the client over non-secure channels (http) and allows attacker to conduct session hijacking attacks.

### Steps to reproduce the behavior:

* Change Server to https and Login to get a Cookie.

**Comment by martini** [comment]
@jaykijay 

JFI: This would be a rails default feature https://github.com/zammad/zammad/blob/develop/config/environments/production.rb#L45 

Anyway, Zammad could set it automatically if you have configured the setting "http_type" to "https". I'll take a look.

**Comment by thorsteneckel** [comment]
This was actually resolved by the commit above and will be available with Zammad 3.2 thanks to @rlue . Closing now.
