### ISSUE TITLE
Ticket escalated despite a response via note.

### ISSUE THREAD

**Issue by MNobis** [zammad/zammad#1620]
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: deb package
* Operating system: Ubuntu 16.04.3 LTS
* Browser + version: not relevant

---
* A SLA with **Ticket -> Status is new, open** and **Ticket -> Prio is High**
* Time to react: 4 hours.
* Time to update: 8 hours.
* Time to solve: N/A

### Expected behavior:

The Agent replies to the ticket with a note and the ticket will not escalate until the "update" SLA is reached.

### Actual behavior:

The Agent replies with a note and the ticket escalates after 4 hours.
Only after an answer via Mail the SLA is achieved

---
Is this behavior by design or should a note fulfill the reaction SLA?

**Comment by MNobis** [comment]
I hate to bump this issue up, but I have to update our process description for zammad.

As it might not be clear on the initial post. I only talk about external notes.
I totaly understand that an internal note should not change the SLA behaviour.
On the other hand should a external note fulfill the SLA reaction time as the costumer is informed.

Is there a way to make external notes count as reacting to the customer?

**Comment by thorsteneckel** [comment]
To be honest I think this applies only for some use cases but the broader userbase of Zammad requires the current state. However, you can change this in your local System by executing the following command in the 
[Zammad rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console):

`Ticket::Article::Type.find_by(name: 'note').update!(communication: true)`

This will cause this line:
https://github.com/zammad/zammad/blob/705487154c81599768dd5429d23434f59422b03e/app/models/observer/ticket/article_changes.rb#L106

to not skip the note article and set the required escalation updates later in the code:
https://github.com/zammad/zammad/blob/705487154c81599768dd5429d23434f59422b03e/app/models/observer/ticket/article_changes.rb#L136-L140

If you have a different opinion on the re default behavior of this feel free to create post over at the community board and discuss it: http://community.zammad.org/

Closing now.
