### ISSUE TITLE
When a new ticket is created and a text is entered, the text isn't always there after posting the ticket.

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1624]
### Infos:

* Used Zammad version: `Installed: 2.1.0-1510063280.01926199.xenial`
* Used Zammad installation source: (source, package, ...): `https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu 16.04/main amd64 Packages`
* Operating system: Ubuntu Server 16.04.3 LTS
* Browser + version: FF 56.0.2

### Expected behavior:

* When creating a new ticket and writing a message, the message should appear when the green button "Erstellen" is clicked.

### Actual behavior:

* When creating a new ticket and writing a message, the message doesn't appear when the green button "Erstellen" is clicked.

### Steps to reproduce the behavior:

* Not sure, try to create a ticked and see if the message is always also being posted.

**Comment by ortegasieger** [comment]
We detected the same behavior and tried to figure out whats the difference between the agent with the same problem and one without. We tried to compare the workflow. 
We found two ways/differences when it can happen, but the behavior is not reproducible, : 
1. New ticket (telefon) -> Fill out everything (Received Call / Title / Text-> change to "Send Email"
2. Using Firefox

**Comment by passboltUser** [comment]
I haven't noticed this issue so far again, but I'll reopen if it appears again.
