### ISSUE TITLE
Search not working correctly - how to reindex everything?

### ISSUE THREAD

**Issue by vishnus** [zammad/zammad#1630]
### Infos:

* Used Zammad version: 2.1.x 
* Used Zammad installation source: Source (Stable)
* Operating system: Ubuntu
* Browser + version: Chromium latest
* DB: MySQL
* Elasticsearch enabled

### Expected behavior:

* Search to show clients and tickets correctly

### Actual behavior:

* We onboarded like 500 agents in a day, some agents can be searched but some are not showing up. All of them signup for first time using Google oAuth and an admin manually make them agents. But few people after login also, admin is not able to search for them under Users. It gives empty result. But  search works for some users.

### Steps to reproduce the behavior:

* Not sure entirely how this can happen. All users logs in using Google OAuth. Most of the users can be searched, but some are not showing up. No errors in production.log as such. 

Is there anyway to reindex entirely to elasticsearch without affecting current production set up? We have nearly 500 agents already signed up and people are working on it. Elastic search and DB are residing on a different server in private network.

Additional info: We noticed under monitoring that Scheduler was not running. We restarted it like half hour ago. What could have crashed the scheduler? We are running zammad application in a 12core, 32gb instance and DB + elasticsearch in another instance of same config. CPU load and RAM seems fine.

**Comment by hanneshal** [comment]
Hi,

you can rebuild the index using
```
zammad run rake searchindex:rebuild
```
https://docs.zammad.org/en/latest/install-elasticsearch.html#create-elasticsearch-index

Without logs we can't see why the scheduler may have crashed. In larger setups we suggest to monitor this process and restart it on demand. 


regards
Johannes

**Comment by hsssystems** [comment]
Hi,

how do I rebuild the index when I installed the system with docker?

br

Harald

**Comment by MrGeneration** [comment]
Please do not recycle already closed issues. Especially not, if it's a technical question!
For the next time, please consult our community for technical questions: https://community.zammad.org

Note that you can run `rake searchindex:rebuild` inside the docker container without any trouble.
As Docker user, I expect you to know how to access the command line of a docker container. :-)
