### ISSUE TITLE
"Scheduler not running" under monitoring even when scheduler is running.

### ISSUE THREAD

**Issue by vishnus** [zammad/zammad#1631]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: Source - stable
* Operating system: Ubuntu
* Browser + version: 

### Expected behavior:

* Monitoring to show all green

### Actual behavior:

* Monitoring showing scheduler not running even when it is running.

`Started GET "/api/v1/monitoring/health_check?_=xxxxxx" for [IP] at 2017-11-09 16:34:00 +0530
I, [2017-11-09T16:34:00.452432 #25514]  INFO -- : Processing by MonitoringController#health_check as JSON
I, [2017-11-09T16:34:00.452510 #25514]  INFO -- :   Parameters: {"_"=>"xxxxxx"}
I, [2017-11-09T16:34:00.535314 #25514]  INFO -- : Completed 200 OK in 4013ms (Views: 0.3ms | ActiveRecord: 906.6ms)
`

There are no errors as such in production log. How does monitoring show if scheduler is running or not? Currently, scheduler is running in the background, i can see that when I do ps -ef | grep zammad
`zammad   32089     1 99 14:55 ?        01:43:55 scheduler`

If I restart the scheduler it will show as green. But after a while it again becomes red and shows scheduler is not running. What could cause it to go out of sync? Is it possible to redirect scheduler error logs to another file? 

Another thing we noticed is, the elasticsearch also goes out of sync immediately and we have to run 
`rake searchindex:rebuild ` 
and re create the search index. So we do this and restart scheduler to get everything back to work :) 

Please advice what we can provide to triage it.

**Comment by vishnus** [comment]
I disabled elasticsearch and now it seems to be stabilized... Any issue related to elasticsearch integration?

**Comment by martini** [comment]
Hi @vishnus normally this is not related. 

Here you can see what the check about "scheduler not running" is doing https://github.com/zammad/zammad/blob/develop/app/controllers/monitoring_controller.rb#L74

So can you enable elastic search again. If monitoring is complaining again, execute

```
zammad run rails c

    Scheduler.where(active: true).where.not(last_run: nil).each do |scheduler|
      next if scheduler.period <= 300
      next if scheduler.last_run + scheduler.period.seconds > Time.zone.now - 5.minutes
      raise "scheduler #{scheduler.inspect} did not run"
    end

    Scheduler.failed_jobs.each do |job|
      raise "Failed to run scheduled job '#{job.name}'. Cause: #{job.error_message}"
    end
```

And send the output.

**Comment by vishnus** [comment]
`Scheduler.where(active: true).where.not(last_run: nil).each do |scheduler|
2.4.1 :024 >           next if scheduler.period <= 300
2.4.1 :025?>         next if scheduler.last_run + scheduler.period.seconds > Time.zone.now - 5.minutes
2.4.1 :026?>         raise "scheduler #{scheduler.inspect} did not run"
2.4.1 :027?>       end
RuntimeError: scheduler #<Scheduler id: 17, name: "Generate user based stats.", method: "Stats.generate", period: 660, running: 0, last_run: "2017-11-10 04:16:58", prio: 2, pid: "70085208750340", note: nil, error_message: "", status: "ok", active: true, updated_by_id: 1, created_by_id: 1, created_at: "2017-11-01 11:31:10", updated_at: "2017-11-10 04:16:58"> did not run
	from (irb):26:in `block in irb_binding'
	from (irb):23
`

And .. 

`Scheduler.failed_jobs.each do |job|
2.4.1 :029 >           raise "Failed to run scheduled job '#{job.name}'. Cause: #{job.error_message}"
2.4.1 :030?>       end
 => [] 
`

**Comment by vishnus** [comment]
I'm assuming scheduler is composed of multiple tasks running at specifc intervals? Monitoring section can be bit more informative with details like which task has failed and option to retry (just like the channel fetch if failed it gives an optoin to retry) 

How can we fix this issue? Also does it affect other operations?

**Comment by martini** [comment]
Hi @vishnus 

yes, the scheduler jobs are executed in defined `period` intervals. The question is, why is `Stats.generate` not executed every 660 seconds? And all other scheduler jobs are working fine.

More questions:
1) So If you execute the code from https://github.com/zammad/zammad/issues/1631#issuecomment-343260088 what is your local time `zammad run rails r 'p Time.zone.now'`?

2) What is if you execute the job manually: `zammad run rails r 'Stats.generate'`

3) Any hints in `log/scheduler_*.log`or `log/production.log`?

 -Martin

**Comment by vishnus** [comment]
1. Rails is showing UTC. And system is on IST. 
`$ rails r 'p Time.zone.now'
Fri, 10 Nov 2017 06:52:42 UTC +00:00`

`$ date
Fri Nov 10 12:23:08 IST 2017`

2. It took a while, but it worked. Still monitoring shows scheduler not running.

3. `log/scheduler_*.log` is empty. Production.log seems not have anything specific for this job.. 

Would this be because of rails time zone? (hope it is :) )

**Comment by martini** [comment]
> Would this be because of rails time zone? (hope it is :) )

No That's ok. Rails is stores all in UTC in database (which is fine).

> Also, is this task that is responsible to sync some data to the ES also? Does this explain why search goes out of sync?

No. That's a other job. And if ES sync would fail you would have the whole `log/production.log` with errors.

I have no idea right now what it could be. If you are fast you can serve me ssh access to the zammad user on the machine (just send it to support at zammad dot com). Other option would be to take commercial support from http://zammad.com .

**Comment by vishnus** [comment]
Hi @martini 

Our internal sec policy doesn't let us grant ssh access to external users. But we will check out the commercial support. Meanwhile, if you think of any other possibility, please let us know.

Btw, the deb installation has production.log rotated and compressed. The source installation, production.log is getting piled up, how do we configure it to behave same way as deb

Thanks

**Comment by martini** [comment]
Hi @vishnus 

> Meanwhile, if you think of any other possibility, please let us know.

In case desktop sharing would also be ok.

> Btw, the deb installation has production.log rotated and compressed. The source installation, production.log is getting piled up, how do we configure it to behave same way as deb

I recommend to install the package (e. g. for Debian) because your have much less maintenance (in the packages all is included, ruby, gems, and so on - it's just phantasmic!).

 -Martin

**Comment by vishnus** [comment]
Hi @martini 

> In case desktop sharing would also be ok
Yes thats something I check if we can do immediately.. Teamviewer is fine?

> I recommend to install the package (e. g. for Debian) because your have much less maintenance (in the packages all is included, ruby, gems, and so on - it's just phantasmic!).

Well, we have few additional requirements like ticket auto assignment, custom email templates etc. So we're maintaining stable version on our test server, we rebase our features branch (which has those required features) with zammad/stable and use that in production after testing. Currently, we're running pilot mode with around 600-700 agents to check feasibility before we go full live.

**Comment by vishnus** [comment]
Does this affect the emails being sent? The notifications, replies etc are sent like 8-9 hours late for some reason. 

Also, we can do Teamviewer. Please let us know how we can proceed. If we are successful in implementing Zammad at our scale, we would like to have a commercial relationship with Zammad.

**Comment by vishnus** [comment]
I put Zammad on maintenance mode and was checking the logs. Now i can see all pending notifications, are all sent. Still can't see the emails sent through SMTP. All background processes started running. Looks like during traffic time, the notifications, emails are all getting delayed by hours for some reason:

![image](https://user-images.githubusercontent.com/598121/32690028-51f19ba6-c715-11e7-918b-0399808bc495.png)

**Comment by vishnus** [comment]
Hi @martini 

The delayed jobs are piling up again, is it possible to run a separate process that can deal with only delayed jobs? I can see only one job is run at a time and multiple jobs come in which is causing this. (delayed_jobs table in DB has lock on only one job at a time)

**Comment by thorsteneckel** [comment]
Hi @vishnus - we did some major performance improvements in Zammad 2.3 and 2.4 and working on some for 2.5. Please update your system accordingly and see if it still persists. I'll close here for now since you have a special case where we can only offer commercial support from here.
