### ISSUE TITLE
RPM Repository Missing filelists Metadata

### ISSUE THREAD

**Issue by MattMencel** [zammad/zammad#1632]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: RPM Package
* Operating system: CentOS 7.4

Zammad is installed using a [Chef cookbook I created](https://supermarket.chef.io/cookbooks/zammad).  I have a `yum_repository` Chef resource that sets up the Zammad repo file, but my Chef runs fail because of the two commands below.

It seems the zammad repo is not standard and is missing `filelists.xml.gz` metadata file?

### Expected behavior:

* `yum makecache` should work
* `needs-restarting` should work

### Actual behavior:

* Neither works and causes Chef client to fail.

### Steps to reproduce the behavior:

```
# yum -q -y makecache --disablerepo=* --enablerepo=zammad
Error: requested datatype filelists not available
```

```
# needs-restarting
Traceback (most recent call last):
  File "/bin/needs-restarting", line 240, in <module>
    sys.exit(main(sys.argv))
  File "/bin/needs-restarting", line 209, in main
    for oldpkg in my.pkgSack.searchFiles(just_fn): # ghostfiles are always bogons
  File "/usr/lib/python2.7/site-packages/yum/packageSack.py", line 468, in searchFiles
    return self._computeAggregateListResult("searchFiles", name)
  File "/usr/lib/python2.7/site-packages/yum/packageSack.py", line 595, in _computeAggregateListResult
    sackResult = apply(method, args)
  File "/usr/lib/python2.7/site-packages/yum/sqlitesack.py", line 46, in newFunc
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/yum/sqlitesack.py", line 957, in searchFiles
    self.populate(repo, mdtype='filelists')
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 251, in populate
    xml = repo_get_function()
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1919, in getFileListsXML
    return self.retrieveMD('filelists')
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1816, in retrieveMD
    return self._retrieveMD(mdtype)
  File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1824, in _retrieveMD
    thisdata = self.repoXML.getData(mdtype)
  File "/usr/lib/python2.7/site-packages/yum/repoMDObject.py", line 208, in getData
    raise RepoMDError, "requested datatype %s not available" % type
yum.Errors.RepoMDError: requested datatype filelists not available
```

**Comment by hanneshal** [comment]
@monotek @rkaldung any ideas on this?

**Comment by rkaldung** [comment]
Should an upstream problem with the package service, we don't create the repos on our own.

**Comment by MattMencel** [comment]
Do I need to create an issue with the upstream package service instead?

**Comment by thorsteneckel** [comment]
@MattMencel - yes please do so (if still required) over at https://github.com/crohr/pkgr/issues. Closing now since it's not directly Zammad related.

**Comment by lr1980** [comment]
> Hi,
> 
> why is filelists.xml.gz missing on yum/rpm repos?
> 
> Best regards
> Lutz Reinhardt

> Hey Lutz,
> 
> Because these indexes are quite large and can slow indexing down, we let owners turn it on or off for their repositories at their discretion: https://packagecloud.io/docs/#disable_filelists
> 
> You'll have to contact the repository owner and ask them to turn it on if you'd like to use this index.
> 
> Cheers,
> Julio
> 
> --
> Julio Capote
> support@packagecloud.io

**Comment by rkaldung** [comment]
@monotek Let's enable indexing. I don't see any reason against it and using Chef is a always a good idea.

**Comment by rkaldung** [comment]
.oO That's right. I can't find anything related in the documentation. @monotek And you?

**Comment by monotek** [comment]
No.

**Comment by lr1980** [comment]
sorry my mistake...

here again:

> Hello,
> 
> here is the GitHub issue report of the problem:
> https://github.com/zammad/zammad/issues/1632
> 
> Thanks,
> Lutz Reinhardt
>

**Comment by monotek** [comment]
thanks for clarification :-)

**Comment by Charburner** [comment]
So we can safely ignore the error message now and in the future?

`Error: requested datatype filelists not available`

( I just got it for the zammad repo after running `yum makecache`)
