### ISSUE TITLE
Ticket State Variable

### ISSUE THREAD

**Issue by ToubieObie** [zammad/zammad#1633]
Is there a variable to get the state of the ticket for the trigger?

#{ticket.state_id} returns only 1-4...

Thanks

EDIT:
ticket.state returns: #<Ticket::State:0x007fca24c6f598>

**Comment by thorsteneckel** [comment]
Don't use our issue tracker for your questions. As stated in the mandatory issue template that you've removed there is a dedicated place for this: https://groups.google.com/forum/?fromgroups#!forum/zammad-users

And don't remove the template. We will close all issues without the filled out template without any comment.
