### ISSUE TITLE
Report not working

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#1634]
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: (source, package, ...) Yum
* Operating system: CentOS7
* Browser + version: Chrome

### Expected behavior:

* 

### Actual behavior:
After upgrade from ver 2.0 to 2.1 in report area  ( https://mydomwian.com/#report ) i got "Elasticsearch need to be configured!"  Message.
* 

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment]
This was already fixed in the meantime.
