### ISSUE TITLE
Shortcut for quoting code/text?

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1637]
* Used Zammad version: 2.1

Hello,
when writing a ticket, what is the shortcut for quoting code/text? Unfortunately the editor doesn't have any buttons.

**Comment by fthommen** [comment]
See #1055

**Comment by passboltUser** [comment]
Thanks. Yes, copying from a rich editor was my workaround already. I assume there's no shortcut?

**Comment by hanneshal** [comment]
No. Sorry.
