### ISSUE TITLE
Creating tickets with API

### ISSUE THREAD

**Issue by forium** [zammad/zammad#1639]
Hi,
we are creating tickets using a webform and push them using the API in zammad.
```
{
"title": "Dies ist ein Test",
"group_id": 2, 
"priority_id": 2, 
"state_id": 1, 
"type": "email", 
"customer": "testuser@test.de", 
"article": {
  "body": "'.$body.'",
  "type": "email", 
  "content_type": "text/html", 
  "from": "testuser@test.de",
  "to": "kundenservice@test.de"
 }
}
```
The tickets are created in zammad, the only problem is, that from/to is not correctly imported in zammad.

**Comment by martini** [comment]
What user do you use for that REST action?

**Comment by forium** [comment]
Hallo Herr Edenhofer,

bevor das Ticket erzeugt wird, erzeugen wir per API den USER in Zammad.
Mit diesem User wird das Ticket dann im weiteren Verlauf erzeugt.


Viele Grüsse
Leander Bretschger

+++ forium GmbH
+++ Kantstr. 13
+++ D-10623 Berlin

+++ Geschäftsführung: Felix Bodeewes und Leander Bretschger
+++ Handelsregister: Berlin, HRB 74178

+++ Tel.: +49 (30) 4202-4647
+++ Fax.: +49 (30) 4202-4655
+++ leander.bretschger@forium.de <mailto:leander.bretschger@forium.de>
+++ www.forium.de

Steuererklärung online erledigen
http://www.lohnsteuer-kompakt.de <http://www.lohnsteuer-kompakt.de/>

Am 13.11.2017 um 15:27 schrieb Martin Edenhofer <notifications@github.com>:

What user do you use for that REST action?

**Comment by martini** [comment]
> before the ticket is created, we create the USER in Zammad via API.
> With this user the ticket will be generated in the further process.

Thanks for feedback. To give the correct answer I need to following:

1) The full REST request(s) (best would be a curl request to handle it isolated).

2) The resource(s) URL which you use (/api/v1/....).

Thanks!

 -Martin

**Comment by forium** [comment]
Hallo Martin,

mittlerweile probiere ich es so:
- Tickets werden jetzt richtigerweise als Emails erzeugt (davor Notiz)
- To: ist auch richtig
- From sieht so aus: 


 $ticket = '{"title": "'.$question.'", "group_id": 2, "priority_id": 2, "state_id": 1, "type": "email", "origin_by_id": "'.$zuser_id.'", "customer": "'.$email.'", '.implode(' ', $custom_fields).'
             "article": {
                 "body": "'.$body.'", "type": "email", "content_type": "text/html", "origin_by_id": "'.$zuser_id.'", "to": "hilfe@steuererklaerung-student.de",
                 "attachments": ['.implode(', ', $attachments).']
	         }}’;

auf diese URL private static $zurl        = 'https://helpdesk.forium.de/api/v1';
	    
+++ forium GmbH
+++ Kantstr. 13
+++ D-10623 Berlin

+++ Geschäftsführung: Felix Bodeewes und Leander Bretschger
+++ Handelsregister: Berlin, HRB 74178

+++ Tel.: +49 (30) 4202-4647
+++ Fax.: +49 (30) 4202-4655
+++ leander.bretschger@forium.de <mailto:leander.bretschger@forium.de>
+++ www.forium.de

Steuererklärung online erledigen
http://www.lohnsteuer-kompakt.de <http://www.lohnsteuer-kompakt.de/>

Am 13.11.2017 um 15:45 schrieb Martin Edenhofer <notifications@github.com>:

before the ticket is created, we create the USER in Zammad via API.
With this user the ticket will be generated in the further process.

Thanks for feedback. To give the correct answer I need to following:

The full REST request(s) (best would be a curl request to handle it isolated).

The resource(s) URL which you use (/api/v1/....).

Thanks!

-Martin

**Comment by monotek** [comment]
Please write in English.

**Comment by forium** [comment]
my latest impletmentation is as follows:
- tickets are now correctly produced as email (befor note)
- to: is correct
- from: is incorrect (is the same as to)
 
 $ticket = '{"title": "'.$question.'", "group_id": 2, "priority_id": 2, "state_id": 1, "type": "email", "origin_by_id": "'.$zuser_id.'", "customer": "'.$email.'", '.implode(' ', $custom_fields).'
             "article": {
                 "body": "'.$body.'", "type": "email", "content_type": "text/html", "origin_by_id": "'.$zuser_id.'", "to": "hilfe@steuererklaerung-student.de",
                 "attachments": ['.implode(', ', $attachments).']
	         }}’;

URL private static $zurl        = 'https://xxx.de/api/v1';

**Comment by martini** [comment]
Hi @forium 

I'm not filler with php. Can you also provide the request as 'curl' requests? So I can take a look on it and I can execute it directly.

Thanks!

 -Martin

**Comment by DNF-SaS** [comment]
May I add the additional problem, that the API does not respect the created_at - value, even when running under administrative permissions.
See https://community.zammad.org/t/set-created-at-field-on-tickets-and-articles-through-rest-api-again/369 and https://community.zammad.org/t/set-created-at-field-on-tickets-and-articles-through-rest-api/230

**Comment by martini** [comment]
@DNF-SaS I replied you your posting. It's not related to this issue.
