### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by ToubieObie** [zammad/zammad#1641]
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: deb
* Operating system: debian 8
* Browser + version: not relevant

### Expected behavior:

* It would be nice to have a mobile version of zammad

### Actual behavior:

* not available

### Steps to reproduce the behavior:

* /

**Comment by thorsteneckel** [comment]
Duplicate of #223

**Comment by julianmatz** [comment]
With regards to #223 : I perfectly understand the noise problem, but I wanted to let you know, I don't think it's possible to upvote on locked threads.

**Comment by MrGeneration** [comment]
Locking, sorry but this doesn't help at all.
Again: We have it on our list.
