### ISSUE TITLE
Ticket Update sometimes slow -> loss of data if you close the tab fast

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#1643]
### Infos:

* Used Zammad version: 2.1.0-1509615059
* Used Zammad installation source: package
 
Zammad 2.1 is in general much faster than 2.0.

Only in case of UPDATE a ticket takes sometimes up to 6 seconds until the ticket view refreshes. 
Waiting 6 seconds is not the main problem but normally we klick on UPDATE an then close the tab of the ticket immediately. In this case the changes in the ticket are lost.

**Comment by MBekspert** [comment]
Hi. Check in history. Is there a status change entry? Like on the picture.
![obraz](https://user-images.githubusercontent.com/33098856/33142845-1a2c86f8-cfb8-11e7-9f10-feea50b44477.png)
 Are there such situations and I do not know why? In history there is a change of status new to closed. Zammad shows that the ticket is still open. 
![obraz](https://user-images.githubusercontent.com/33098856/33142893-426e2e8c-cfb8-11e7-92cc-7d64e4bff891.png)
I do not know how to do to show the real state (tickets) from the db in zammad. (restarting the service / server does not help)

**Comment by thorsteneckel** [comment]
Hi @hiaz / @MBekspert  - does the issue still persists in Zammad 2.4?

**Comment by hiaz** [comment]
@thorsteneckel Thank you for asking. I just talked to the support team. With 2.1 they had the problem multiple times a day. Now they could not remember when it appeared last time... A very good sign, I think ;). From my side we can close the issue.

**Comment by thorsteneckel** [comment]
Thanks for your fast feedback! This is really a good sign :) JFI: We did some performance improvements with Zammad 2.3 and 2.4 but this issue was not on our "ask feedback" list. However, I will close it now. Let me know if we have to take action 👍
