### ISSUE TITLE
Can't separate escalated and pending tickets in ticket overview

### ISSUE THREAD

**Issue by svnr-dvnkln** [zammad/zammad#1646]
### Infos:

* Used Zammad version: 2.2.x
* Used Zammad installation source: official deb
* Operating system: all
* Browser + version: all

We're trying to create an ticket overview for all tickets except escalated tickets. The thing is - as soon as we're using any escalation conditions all pending tickets are affected too.

### Expected behavior:

By setting the conditions inside the overview configuration to the following:
* status = new, open, pending close, pending reminder
* owner = current user
* f.e. escalation = false (not an actual available condition but something like this could be used)

I should get an overview for all tickets except escalated tickets dispatched to my user.

### Actual behavior:

I can't really find a way to create an overview as stated above.
It's either containing both escalated & pending tickets or none of them.

I actually can get an overview for all escalated tickets dispatched to my user by setting the conditions inside the overview configuration to the following:
* status = new, open, pending close, pending reminder
* owner = current user
* escalation within next (relative) 0 minutes

### Steps to reproduce the behavior:

Use any escalation condition inside the ticket overview configuration.

**Comment by hanneshal** [comment]
Hi, 

you try to don't show escalated tickets in regular overviews? So 
Something like "open but not escalated" right?

This is not possible at the moment. 

If you like to see this in Zammad feel free to start a discussion at:
https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals
