### ISSUE TITLE
After Update from 1.5.0-504857372 to 2.1.0-1510698871 no access to GUI of zammad

### ISSUE THREAD

**Issue by Elmenhorst** [zammad/zammad#1647]
Hi,
I tried to update my zammad installation from 1.5.0-1504857372 to 2.1.0-1510698871 using the command "apt-get install zammad". Everything seems to work fine, zammad was starting again. But I cannot access the GUI via any browser. When I compare the running processes before and after the update (see attached screenshots), I notice a difference in the stat of the puma process. Before the update it was "puma 3.6.0 (tcp://0.0.0.0:3000)" and after the update it has changed to "puma 3.10.0 (tcp://127.0.0.1:3000)", so I think the process is only accepting local accesses and not from remote. Also the websocket-server is now bound to 127.0.0.1 on port 6042. 

My /etc/nginx/sites-enabled/zammad.conf is unchanged after the update:
#
# this is the nginx config for zammad
#

upstream zammad {
    server support.elmenhorst.de:3000;
}

upstream zammad-websocket {
    server localhost:6042;
}

server {
    listen 80;

    # replace 'localhost' with your fqdn if you want to use zammad from remote
    server_name support.elmenhorst.de;

    root /opt/zammad/public;

    access_log /var/log/nginx/zammad.access.log;
    error_log  /var/log/nginx/zammad.error.log;

    client_max_body_size 50M;

    location ~ ^/(assets/|robots.txt|humans.txt|favicon.ico) {
        expires max;
    }

    location /ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 86400;
        proxy_pass http://zammad-websocket;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 180;
        proxy_pass http://zammad;

        gzip on;
        gzip_types text/plain text/xml text/css image/svg+xml application/javascript application/x-javascript application/json application/xml;
        gzip_proxied any;
    }
}

How can I allow zammad to accept remote connections again?

### Infos:

* Used Zammad version: 1.5.0-504857372
* Used Zammad installation source: Debian via DEB
* Operating system: Debian 8.9 Jessie
* Browser + version: 

![processes after update](https://user-images.githubusercontent.com/26385643/32841562-ee84a7da-ca1a-11e7-8d1e-fbb64e14bfa3.jpg)
![processes before update](https://user-images.githubusercontent.com/26385643/32841563-ee987a4e-ca1a-11e7-8e81-309a86a2d38e.jpg)

**Comment by monotek** [comment]
"support.elmenhorst.de:3000;" is wrong. It has to be "localhost:3000;".

**Comment by Elmenhorst** [comment]
But support.elmenhorst.de:3000 is the address to access to the web GUI and it worked before the update. I have an local DNS record for the support.elmenhorst.de which leads to the correct IP adress of the zammad server.

**Comment by monotek** [comment]
Its on port 80 now. 
See: See also: https://github.com/zammad/zammad/issues/1430
