### ISSUE TITLE
After install zammad on ubuntu I cannot register admin account

### ISSUE THREAD

**Issue by bolotkalil** [zammad/zammad#1652]
### Infos:

* I Used Zammad version: 2.1.0
* Used Zammad installation source: https://docs.zammad.org/en/latest/install-ubuntu.html
* Operating system: Ubuntu 16.04 Lts
* Browser + version: Chrome version 61.0.3163.100 x64

### Expected behavior:
After install the zammad I should register one admin account to control system.

### Actual behavior:
When I register admin account I get server 502 error:              
![502](https://user-images.githubusercontent.com/4947951/32948577-ebc5d6bc-cbc9-11e7-8f61-bdd558e0eff4.png)

### Steps to reproduce the behavior:
* step 1: After installing, I have changed the server(apache or nginx) configuration, address link from "localhost" to "my-domain.com"
* step 2: I restarted server.
* step 3: I opened the browser and entered "my-domain.com".
* step 4: I see "Setup new system" button I clicked them.
* step 5: I see "Admin account" page then I fill all options and I click "create" button.
* step 6: I see ajax load then nothing happens.
* step 6: I open browser developer console then I see 502 error: bad gateway.

Yes I'm sure this is a bug and no feature request or a general question. 

Many thanks

**Comment by monotek** [comment]
What webserver do you use? Apache or nginx?

**Comment by bolotkalil** [comment]
By default installed apache, I have tested on both servers apache and nginx.

**Comment by monotek** [comment]
Does it work now?

**Comment by bolotkalil** [comment]
No is not. I have changed the OS to centos. On ubuntu the same result.
