### ISSUE TITLE
Ticket-Property of type Tree-Select mixes up children

### ISSUE THREAD

**Issue by jantari** [zammad/zammad#1660]
### Infos:

* Used Zammad version: 2.1.0-1510748077.44070687.xenial
* Used Zammad installation source: zammad deb repo
* Operating system: Ubuntu Server 16.04.3
* Browser + version: Firefox 58.0b4

### Expected behavior:

* Configuring a tree select with 4 top-level choices and multiple level-2 choices
should only show the level-2 choices on the top-level choice they were created as children for

### Actual behavior:

* As soon as I configure 4 top-level choices with sub-choices for each (only 2 levels of depth total)
only the topmost top-level choice shows the corrent sub-choices. All other 3 top-level choices will show a mixture of each others options

### Steps to reproduce the behavior:

* Configure a new ticket-attribute of type "tree select" with 4 top-level choices and 22 children-choices in the first one, 10 for the second one and 4 for the LAST one. This works. As soon as you add children to the 3rd top-level choice and save changes the whole tree select bugs out

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Fixed in develop and now in stable, too. Will be ready to install in ~30 minutes from now. 🚀
