### ISSUE TITLE
Removed LDAP attributes aren't reflected on the user

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1665]
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: source
* Operating system: any
* Browser + version: any

### Expected behavior:

* After removing / unsetting a LDAP attribute the matching User attribute in Zammad should get removed, too.

### Actual behavior:

* After removing / unsetting a LDAP attribute the matching User attribute in Zammad still persists. 

### Steps to reproduce the behavior:

* Sync a LDAP User to Zammad with a filled surname in the LDAP record entry.
* Remove the surname in the LDAP entry.
* Resync the very same User.
* See that the attribute is still set in Zammad.

The issue is caused by [this line](https://github.com/zammad/zammad/blob/492ca261cef2e6398d9331992a8af1d126a92be2/app/models/external_sync.rb#L41). Unfortunately this is a very central place and the method is used in different context so changing is not an option.
The solution will be to migrate the LDAP sync to the Sequencer model which handle this properly.

**Comment by muhammadn** [comment]
@thorsteneckel sn (surname) attribute is in the inetOrgPerson schema which is mandatory to have `sn` in, so i cannot reproduce with `sn`. What Ldap server are you using? I am using OpenLDAP (which is a native is os x)

**Comment by thorsteneckel** [comment]
This happened in a customer support call. Should be broken with any attribute. Just sync a user with the filled attribute, remove the attribute value and start the sync again. Afterwards the attribute in Zammad is still filled but shouldn't.

To be honest you don't need to dig deeper into this since we will replace the current LDAP sync logic with our new integration framework (Sequencer). The same we used for the Exchange integration.
