### ISSUE TITLE
Ticket templates disappear after logout/login in same browser session

### ISSUE THREAD

**Issue by svnr-dvnkln** [zammad/zammad#1669]
### Infos:

* Used Zammad version: 2.1.x and 2.2.x
* Used Zammad installation source: deb 9 repo
* Operating system: deb 9
* Browser + version: all (really)

### Expected behavior:

* Create a ticket template
* Log out and log in again
* Ticket template is still there

### Actual behavior:

* Create a ticket template
* Log out and log in again
* Ticket template disappeared
* Close all active browser sessions
* Log in again
* Ticket template appears

### Steps to reproduce the behavior:

* Create a ticket template
* Log out and log in again

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by hanneshal** [comment]
Hi @svnr-dvnkln,

is this the same behaviour as issue #1650 ?

regards

**Comment by martini** [comment]
@svnr-dvnkln it's in current 2.4.1, it's already available in via repo.
