### ISSUE TITLE
SMTP settings for notifications do not work

### ISSUE THREAD

**Issue by dertin** [zammad/zammad#1672]
* Used Zammad version: 2.1.x
* Used Zammad installation source: package
* Operating system: Debian 9

In the configuration of the IMAP / SMTP account everything works fine.

But in the notification account does not work, even using the same data as the account that works for IMAP / SMTP mail accounts

![image](https://user-images.githubusercontent.com/1295883/33181251-45a85168-d04e-11e7-9bd3-d60d6b9e1749.png)

![image](https://user-images.githubusercontent.com/1295883/33181220-268db71e-d04e-11e7-9430-8f08d207d086.png)

**Comment by martini** [comment]
Hi @dertin 

Zammad is using a certain email address for notifications. It seems this address is not matching with your allowed address for SMTP.

Please check Admin -> Channels -> Email -> Settings -> Notification Sender

Change it and try it again.

 -Martin

**Comment by martini** [comment]
By the way, also have a look for questions at our new forum https://community.zammad.org Thanks a lot!

**Comment by dertin** [comment]
Hi @martini 

I haven't managed to connect.

I'm testing from a local IP.

I do not understand how the email configuration of the account is valid and does not validate the email address for the notifications. If I am using the same SMTP data.

**Comment by martini** [comment]
> I do not understand how the email configuration of the account is valid and does not validate the email address for the notifications. If I am using the same SMTP data.

The check is done the following way:

1) is connection to smtp host possible -> seems to be ok on your side
2) is smtp auth possible -> seems to be ok on your side
3) Zammad tries to send an email via SMTP to verify if it's really working. For this test the sender email address is "Notification Master <noreply@#{config.fqdn}>" -> I guess: Your SMTP gateway tells you "550: I'm sorry you are not allowed to send emails with "noreply@#{config.fqdn}" via this SMTP gateway.

PS: config.fqdn need to be replaced with your configure Zammad fqdn.

You also can check your /var/log/mail of your SMTP gateway, it will tell you more about the 550 error.

**Comment by monotek** [comment]
Maybe also related to: https://github.com/zammad/zammad/issues/1612

**Comment by martini** [comment]
@monotek yes, it's exactly the same issue. Thanks!

**Comment by dertin** [comment]
It works now

I just needed to define the email address for notifications as you indicated.

I had defined no-replay@... and I used support@ ...

Thanks!
