### ISSUE TITLE
Upgrading 2.0.1 to 2.1.0 causes users not beeing able to login

### ISSUE THREAD

**Issue by PAlbrechtHH** [zammad/zammad#1673]
### Infos:

* Used Zammad version: 2.1.0
* Used Zammad installation source: Source (using **MySQL** instead of PostgreSQL)
* Operating system: CentOS 7
* Browser + version: Firefox 57.0
![ticketsystem_fehler](https://user-images.githubusercontent.com/33467957/33181823-e9c7852a-d071-11e7-8283-e8cc397f887f.png)

### Expected behavior:

Users are able to login after performing an upgrade from 2.0.1 to 2.1.0.

### Actual behavior:

Users are getting an error message (**Mysql2::Error: Table 'zammad.networks' doesn't exist: SELECT \`networks\`.\* FROM \`networks\`**) once they click on the "Login" button.

### Steps to reproduce the behavior:

Install CentOS 7, install MySQL, install Ruby 2.4.1, install Zammad 2.0.1 from source following the steps in the documentation. Perform upgrade to 2.1.0 following the steps in the documentation. Start services, try login.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by PAlbrechtHH** [comment]
If there are additional information required, I'm happy to provide them.
Thanks alot!

**Comment by martini** [comment]
Hi @PAlbrechtHH 

it seems that you still have old Zammad 2.0 or lower files in your Zammad directory (which normally are deleted by the OS package manager on upgrade).

Please check and remove 

rm /opt/zammad/app/controllers/sessions/collection_network.rb

and restart Zammad again.

For deeper help we can handle it via Zammad Support  https://zammad.com/pricing#selfhosted

 -Martin

**Comment by PAlbrechtHH** [comment]
Hi @martini 

thanks alot for your reply!

Deleting collection_network.rb caused our ticket system to work again! Now users can log in!

I have a question for future updates: would it be safe to compare a fresh source directory of version A with a fresh source directory of version B and delete the obsolete files?

Or is there a place where I can read the changes so I can delete obsolete files?

Thanks alot!

Greetings from Hamburg, Germany

**Comment by martini** [comment]
Hi @PAlbrechtHH 

> I have a question for future updates: would it be safe to compare a fresh source directory of version A with a fresh source directory of version B and delete the obsolete files?
>
> Or is there a place where I can read the changes so I can delete obsolete files?

Now I see you have an installation done from source. In this case I would move the whole Zammad directory on upgrading.

Or event better, I would take the OS package. Here the files are replaced automatically. You also get all Ruby & Gem dependencies. It's really easy to use. I really recommend to do this way. It's less maintenance work (updates are done within 5 min).

Greetings from Berlin to Hamburg! :)

 -Martin

**Comment by PAlbrechtHH** [comment]
Hi @martini 

Thanks alot for your advice!
Next time I perform an upgrade from source, I will try to move the whole /etc/zammad directory before performing the upgrade!

I understand that it would be better to use the OS package. But as far as I know that OS package is designed to work with a PostgreSQL database only.
Our Zammad system is using a MySQL database.

Is there a way to migrate our system to PostgreSQL?
I would like to do so that as we would like to avoid problems while upgrading in the future.

Greetings

**Comment by martini** [comment]
> Is there a way to migrate our system to PostgreSQL?
> I would like to do so that as we would like to avoid problems while upgrading in the future.

The Zammad OS package also supports mysql/mariadb. 

1) Just install the package + mysql/mariadb
2) Do an normal setup till login page
3) Stop Zammad
4) Replace your database with the one configured in /opt/zammad/config/database.yml
5) execute "zammad run r 'Cache.clear'" && "Zammad run rake db:migrate"
6) Start Zammad
7) Just login with your old database
