### ISSUE TITLE
No Mail via SMTP and sendmail

### ISSUE THREAD

**Issue by MANFahrer-GF** [zammad/zammad#1676]
Hello,
Zammad does not send mails via SMTP or sendmail

Centos 7
Zammad 2.2 currently

Please help

### Infos:

* Used Zammad version: 2.2.1
* Used Zammad installation source: (source, package, ...)  https://dl.packager.io/srv/zammad/zammad/develop/installer/el/7.repo
* Operating system: Centt OS 7
* Browser + version: IE, chrome, Firefox

**Comment by MANFahrer-GF** [comment]
Zammad: https://support.virtual-transport-group.de

**Comment by martini** [comment]
Hi @MANFahrer-GF 

Is tis a but report or a question for support?

 -Martin

**Comment by thorsteneckel** [comment]
Troubles in selfhosted environments are handled via our support plans: https://zammad.com/de/preis#selfhosted

**Comment by MANFahrer-GF** [comment]
E, [2017-11-24T12:47:14.533420 #905] ERROR -- : 2017-11-24T12:47:14+0100: [Worker(host:v22017115049456130.luckysrv.de pid:905)] Job BackgroundJobSearchIndex (id=44141) FAILED (0 prior attempts) with RuntimeError: Unable to process POST at http://192.168.0.1:9200/support.virtual-transport-group.de_zammad_production/User/7 (size: 0M)
#<UserAgent::Result:0x007f4e70ef2408 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Net::OpenTimeout: execution expired>">
I, [2017-11-24T12:47:14.539099 #905]  INFO -- : 2017-11-24T12:47:14+0100: [Worker(host:v22017115049456130.luckysrv.de pid:905)] Job BackgroundJobSearchIndex (id=27083) RUNNING
I, [2017-11-24T12:47:14.545443 #905]  INFO -- : # curl -X POST "http://192.168.0.1:9200/support.virtual-transport-group.de_zammad_production/User/7" \
I, [2017-11-24T12:47:14.686893 #905]  INFO -- : execute Import::OTRS.diff_worker (try_count 0)...

**Comment by martini** [comment]
@MANFahrer-GF just as tip: It's a issue with your elasticsearch installation. In moste cases elasticsearch has been updated but the mapper-attachments plugin is not updated (you need to remove and install a newer version again). Use `zammad run rake searchindex:rebuild` to rebuild the complete index.

Anyway, for fast commercial support have a look at https://zammad.com/de/preis#selfhosted

-Martin (the IltisFahrer :))
