### ISSUE TITLE
end of file reached while adding email using SMTP

### ISSUE THREAD

**Issue by ShalbafZadeh** [zammad/zammad#1678]
### Infos:

* Used Zammad version: 

Zammad APT package : 2.1.0-1511469591.5548c3c7.xenial 
Ubuntu 16.04.3
### Expected behavior:

* Adding a email while setting up Zammad
if you select SMTP and add credentials about email you should be able to use that email

### Actual behavior:

* you get ```end of file reached``` when you try to set email 

### Steps to reproduce the behavior:

*  Setup a new zammad instance and try to use SMTP account that uses TLS of SSL

production.log (masked user) 
```
OK in 22ms (Views: 2.1ms | ActiveRecord: 4.2ms)

I, [2017-11-25T17:10:52.199019 #3235]  INFO -- : Started POST "/api/v1/channels_email_notification" for 138.68.79.26 at 2017-11-25 17:10:52 +0330
I, [2017-11-25T17:10:52.206148 #3235]  INFO -- : Processing by ChannelsEmailController#notification as JSON
I, [2017-11-25T17:10:52.206501 #3235]  INFO -- :   Parameters: {"adapter"=>"smtp", "options"=>{"host"=>"smtp.zoho.com", "user"=>"myuser@mydomain.ir", "password"=>"[FILTERED]", "port"=>"587"}, "channel_id"=>2}
I, [2017-11-25T17:10:53.831318 #3235]  INFO -- : Completed 200 OK in 1625ms (Views: 0.5ms | ActiveRecord: 2.3ms)
```

**Comment by ShalbafZadeh** [comment]
production.log in debug level:
```
D, [2017-11-25T17:15:25.891860 #4626] DEBUG -- : client(47417443311880) ---/client-
D, [2017-11-25T17:15:26.892830 #4626] DEBUG -- : client(47417443311880) ---client - looking for data of user 3
D, [2017-11-25T17:15:26.894027 #4626] DEBUG -- : client(47417443311880) ---/client-
I, [2017-11-25T17:15:27.285948 #4618]  INFO -- : Started POST "/api/v1/channels_email_notification" for 138.68.79.26 at 2017-11-25 17:15:27 +0330
I, [2017-11-25T17:15:27.293458 #4618]  INFO -- : Processing by ChannelsEmailController#notification as JSON
I, [2017-11-25T17:15:27.293610 #4618]  INFO -- :   Parameters: {"adapter"=>"smtp", "options"=>{"host"=>"smtp.zoho.com", "user"=>"myuser@mydomain.com", "password"=>"[FILTERED]", "port"=>"465"}, "channel_id"=>2}
D, [2017-11-25T17:15:27.293761 #4618] DEBUG -- : session based auth check
```

**Comment by thorsteneckel** [comment]
I can't see any `end of file reached` in the provided log lines. Please provide the said line (including the backtrace).

Consider our self hosted plans for support - https://zammad.com/pricing#selfhosted

**Comment by ShalbafZadeh** [comment]
@thorsteneckel in  /opt/zammad/config/environments/production.rb  
i set ```config.log_level = :debug``` but still cant see EOF stack trace 
shall i change something else?
Thank you very much

**Comment by thorsteneckel** [comment]
Seems to be an configuration issue. I have the feeling that this occurred several times here on the issue tracker. The solution should be in one of the closed email/SMTP issues. I can only advise our managed solution or self hosted server over at zammad.com. Closing now. If you can make sure that it's a bug feel free to provide further input. Closing now.

**Comment by thorsteneckel** [comment]
Or check our our board over at community.zammad.org
