### ISSUE TITLE
SELinux interfering rpm installation on CentOS 7

### ISSUE THREAD

**Issue by veritaspoutine** [zammad/zammad#1680]
### Infos:

* Used Zammad version: 2.1.x
* Used Zammad installation source: CentOS with RPM
* Operating system: CentOS 7 minimal install
* Browser + version: 

### Expected behavior:
Welcome to Zammad!

### Actual behavior:

I like to point out a weird situation I came across with SELinux during installation on CentOS7. 

I followed this instruction: https://docs.zammad.org/en/latest/install-centos.html

Upon accessing http://localhost on CentOS7 and http://[zammad server IP], I saw nginx test page.
Checked /etc/nginx/nginx.conf and comment out the following: 
```
server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;
        #include /etc/nginx/conf.d/*.conf;
        location / {
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
```

Refreshed the browser and got 502 bad gateway.  

```
/var/log/nginx/error.log
[emerg] 26131#0: "upstream" directive is not allowed here in /etc/nginx/conf.d/zammad.conf:5
```

```
/var/log/nginx/zammad.error.log
 [crit] 22794#0: *1 connect() to 127.0.0.1:3000 failed (13: Permission denied) while connecting to upstream, client: [mylaptopIP], server: [zammad server IP], request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "[zammad server IP]"
[error] 22794#0: *1 no live upstreams while connecting to upstream, client: [mylaptopIP], server: [zammad server IP], request: "GET / HTTP/1.1", upstream: "http://zammad/", host: "[zammad server IP]"
```

Googled and found visdim's [comment ](https://github.com/zammad/zammad/issues/1117)about elasticsearch-plugin

> > this has helped me when elasticsearch was not running:
> cd /usr/share/elasticsearch
> bin/elasticsearch-plugin remove mapper-attachments
> bin/elasticsearch-plugin install mapper-attachments
> 
> systemctl start elasticsearch
> systemctl enable elasticsearch
> systemctl status elasticsearch

Ran 
```
sudo ./elasticsearch-plugin remove mapper-attachments
sudo ./elasticsearch-plugin install mapper-attachments
Downloading mapper-attachments from elastic
[=================================================] 100%  
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission createAccessControlContext
* java.security.SecurityPermission insertProvider
* java.security.SecurityPermission putProviderProperty.BC
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
Exception in thread "main" java.lang.RuntimeException: installation aborted by user
        at org.elasticsearch.plugins.PluginSecurity.prompt(PluginSecurity.java:111)
        at org.elasticsearch.plugins.PluginSecurity.readPolicy(PluginSecurity.java:93)
        at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:533)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:570)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:218)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)`

```
Disabled SELinux, rerun 
```
sudo ./elasticsearch-plugin install mapper-attachments
-> Installed mapper-attachments
```
restart elasticsearch
restart nginx

browse to http://[zammad server ip] and http://localhost on CentOS7
Welcome to Zammad!

### Steps to reproduce the behavior:

Install Zammad rpm package with SELinux enabled.

I don't think it's a bug it's just SELinux blocking java being installed and I think it should be noted somewhere in the installation guide.

**Comment by monotek** [comment]
At the end of the installation should be a hint how to configure selinux and the firewall to get it work.

**Comment by monotek** [comment]
I've added the infos to the documetnation: 
https://docs.zammad.org/en/latest/install-centos.html

**Comment by hanneshal** [comment]
@monotek is right. 
It's shown after the installation:
https://github.com/zammad/zammad/blob/develop/contrib/packager.io/functions#L282
The SELinux command is this:
```
setsebool httpd_can_network_connect on -P
```

Regards

**Comment by monotek** [comment]
I've don't tested the Elasticsearch installation again. 
Did you set "sysctl -w vm.max_map_count=262144" before installation as described in the docs?

https://docs.zammad.org/en/latest/install-elasticsearch.html#install-elasticsearch-and-its-attachment-plugin

**Comment by veritaspoutine** [comment]
Aww I just ran the zammad rpm again and yes the instructions was indeed there at the end of the installation. Thanks for helping out guys!
