### ISSUE TITLE
unable to assign Organisation to user since Zammad 2.0

### ISSUE THREAD

**Issue by thomas-vahrson** [zammad/zammad#1682]
### Infos:

* Used Zammad version:  2.1.x
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version:  different browser tested

### Expected behavior:

* insert the organisation and be able to select the company name. 

### Actual behavior:

* with the new version of zammad I have different problems. with the old version I was able to insert the company name under the user setting and see a list and you can select the company. But actually I can't search for a company. I'm also not able to search for a user when I want to create as a admin user an ticket for a customer. I have to login as the customer. I have no other way to create a ticket with a customer name. This was working in the older version.

### Steps to reproduce the behavior:

* I installed some weeks ago "Elasticsearch" with this link: 
https://docs.zammad.org/en/latest/install-elasticsearch.html

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @thomas-vahrson 

it seems that Elasticsearch is not working well (it's no Zammad bug). Elasticsearch should server the auto completion list.

Please check the following:

1) reindex elasticsearch with current content: `zammad run rake searchindex:rebuild`
 -> If this work, also the pull downs should work fine.

In case it's not working, check the following:
2) Check the elasticsearch version, currently we support 2.4-5.5 with mapper-attachments plugin
3) Uninstall and install mapper-attachments again, restart elasticsearch and try `zammad run rake searchindex:rebuild` again.


 -Martin

**Comment by monotek** [comment]
@martini
Imho we should add an elasticsearch healthcheck to the monitoring in the admin backend.

Errors of the healtchecks should be shown somehow in the agent frontend. Maybe a little red overlay on top of the site?

**Comment by thomas-vahrson** [comment]
hello. 
thanks for your feedback. It looks like the docu are note correctly for Zammad >2.0?
I installed Zammad on 2 different server. On the server with Zammad 1.xx I can run the command "zammad run rake searchindex:rebuild" But on the Zammad 2.1x Server I get the error message below :  Unable to process PUT at http://localhost:9200/zammad-tv_zammad_production

**Comment by thomas-vahrson** [comment]
I saw some minutes ago this ticket from you:
https://github.com/zammad/zammad/issues/446

But I get all the time this error message:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/plugins/PluginCli : Unsupported major.minor version 52.0

**Comment by thomas-vahrson** [comment]
I found the issue himself in a other ticket! 
zammad run rails r "Setting.set('es_index', 'zammad')" fix the issue.
