### ISSUE TITLE
Web Form Submit dont work with exist user Mail 

### ISSUE THREAD

**Issue by masterjcl** [zammad/zammad#1684]
### Infos:

Used Zammad version: Version 2.0.x 
Used Zammad installation source: apt-get 
Operating system: Debian Jessie
Browser + version: Chrome, Firefox

include Web Form
I
### Expected behavior:

Ticket succesfull create

### Actual behavior:

Red Frame on Mail Field

### Steps to reproduce the behavior:

Check Response from Validate Request with Firebug
Response on Submit Ticket Form
{"errors":{"email":"invalid"}}

I have a problem with the Ticket Webform when I embed the form on another server, i can only create a ticket if the send mail is not present in Zammad. If the mail is present, the form refuses to generate a ticket and makes a red frame around the mailbox. Can I disable that?

**Comment by masterjcl** [comment]
after check the form_controller.rb:62  the address.valid_mx fails in mail check

**Comment by masterjcl** [comment]
our internal dns server has no mx entry. when testing valid_mx it fails here a switch would help. 

mail_servers = Resolv::DNS.open.getresources(value.split('@')[1], Resolv::DNS::Resource::IN::MX)

**Comment by rlue** [comment]
@masterjcl, I was not able to reproduce this bug on the `stable` branch. Please upgrade to the latest version of Zammad (2.4.0) and try again. 

If the problem persists after an upgrade and you can provide us detailed, step-by-step directions to reproduce it (or if you can reproduce it on a public instance of Zammad), we'll be happy to reopen the issue.
