### ISSUE TITLE
Elasticsearch 6.x & 7.x support

### ISSUE THREAD

**Issue by martini** [zammad/zammad#1688]
Implement Elasticsearch 6.x support.

**Comment by yombo** [comment]
Is there any timeline for 6.1 support? Thanks for your hard work on this project.

**Comment by AchuM** [comment]
+1

**Comment by thorsteneckel** [comment]
Locking conversation. There is no new input. +1 and requesting comments create noise and distraction. We are working hard on the next upcoming/most requested features and projects of our support customers. If you want to state your interest in the feature and give valuable input please give the initial post a 👍 reaction and we are able to evaluate it. We will lock all distracting issues from now on. Thanks for your understanding.

**Comment by monotek** [comment]
ETA?

**Comment by thorsteneckel** [comment]
It has been way to quiet around here from our side. To give you all a heads up: We're working on this issue and will add support for newer ES versions in one of the upcoming releases.

As @monotek already stated in #2582 ES 5.6 and 6 have reached their EOL.

**Comment by martini** [comment]
@monotek 🎉

**Comment by monotek** [comment]
:)

**Comment by monotek** [comment]
Whoever wants to test it... It's already in our docker container: https://github.com/zammad/zammad-docker
