### ISSUE TITLE
In overviews conditions the tag name (not the tag id) is stored. Renaming tags will break overviews condition

### ISSUE THREAD

**Issue by martini** [zammad/zammad#1690]
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: any
* Operating system: any
* Browser + version: any

### Expected behavior:

In overviews conditions the tag name (not the tag id) is stored. Renaming tags will break overviews condition.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
@martini broke overviews once (as admin), after playing around with manage->overviews->conditions->tags and manage->tags

had reset the db, tried to play around (one at the time to narrow down the issue) with overviews->conditions->tags by adding and removing tags.. didn't break.

So is the problem at manage->overviews->conditions->tags and manage->tags ?
