### ISSUE TITLE
De-activating of all Administrator accounts should be prevented

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1695]
### Infos:

* Used Zammad version: 2.2 
* Used Zammad installation source: git
* Operating system: any
* Browser + version: any

### Expected behavior:

* Zammad should prevent disabling of all Administrator accounts as it does for deleting such accounts.

### Actual behavior:

* Zammad allows disabling of all Administrator accounts. See #1694. 

### Steps to reproduce the behavior:

* Use the Rails console to disable the Administrator account of your System via `User.find(*id*).update!(active: false)`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
@thorsteneckel I did some work but it for disallowing disabling all admin accounts. Which i think is wrong. 

Currently, zammad checks to have at least one admin user check if activerecord tries to disable all accounts. 

But this works only on record update and not create. 

So is your use case is for any admins that is deactivated or the last one?

**Comment by thorsteneckel** [comment]
The use case is for the last one. So at some point there is only one active Admin user left. Then an update on that user is performed with something like `User.find(*id*).update!(active: false)` and the last admin gets deactivated too. So there is any Admin left to configure the system or re-activate any of the Admins. Hope that makes it clearer. Feel free to ask any questions.

**Comment by muhammadn** [comment]
@thorsteneckel I have tried doing something similar: `User.find(3).update!(active: false)` on the only admin user left.

the message that came out is:
Exceptions::UnprocessableEntity: Minimum one user needs to have admin permissions.
	from app/models/user.rb:1007:in `last_admin_check_by_attribute'
	from (irb):45

and the last admin check seems to work.

**Comment by thorsteneckel** [comment]
Ok great 👍 Then this was fixed in the meantime. Can be closed then.
