### ISSUE TITLE
LDAP - 0 Users import

### ISSUE THREAD

**Issue by ruebenmaster** [zammad/zammad#1697]
Hallo,
the LDAP integration will not work! There are always 0 Users imported by zammad. 

Our users are divided according to the locations. These in turn according to the companies to which they are subject.
The connection to the LDAP works, but exactly 0 users are imported.
It does not matter what I enter, he does not see any users ...

You are able to manipulate the database directly to solve this problem. But after that you are not allowed to do any configurations at the webgui anymore, because the LDAP connection will broken. 

The users are in the following structure:

Distinguished Name (DN):    uid=ruebenmaster,ou=DENKBI01,ou=9999,ou=People,dc=domain,dc=net

How to configure zammad on webgui to reach our users?
We want to use zammad 2.1.0 this time on CentOS 7. The LDAP server is a LDAP 389 (Kolab).

Our seafile sever for example, has no problems to find users only with base dn.

Thank you for helping.

Greetings
ruebenmaster

**Comment by thorsteneckel** [comment]
Hi @ruebenmaster,

this is more a configuration question than an issue. We only address issues over here. Please refer to our board for questions https://community.zammad.org/

Our workload is currently to high to give away free support for non customers. Sorry to say.

**Comment by ruebenmaster** [comment]
Hallo Thorsten
you want that the world is using zammad! Now we try, and the LDAP configuration seems to be not right. It is a essential feature of helpdesk solutions. ;o) Now, there's no way to fix this issue. 

Thank you very much.

Greetings
ruebenmaster
