### ISSUE TITLE
No user preference for out-of-office available

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#1699]
### Infos:

* Used Zammad version: develop 2.2+
* Used Zammad installation source: (source, package, ...) 
* Operating system: 
* Browser + version: 

### Expected behavior:

* It should be possible to allow or disable out of office for users in the admin interface role assignment  

### Actual behavior:

"Currently the “out of office” feature completely disappears as soon as you disable the user preferences checkbox."

See: https://community.zammad.org/t/user-profile-out-of-office/102

### Steps to reproduce the behavior:

* See screenshot in the community post

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Fixed. New packages available in about 30 minutes.
