### ISSUE TITLE
Can't disable maintenance mode anymore

### ISSUE THREAD

**Issue by svnr-dvnkln** [zammad/zammad#1700]
### Infos:

* Used Zammad version: 2.2.x
* Used Zammad installation source: deb 9 repo
* Operating system: serv deb9 client win7
* Browser + version: all

### Expected behavior:

* Disabling the maintenance mode works

### Actual behavior:

* Well, it doesn't

### Steps to reproduce the behavior:

* Enable maintenance mode

FYI: Changing the login message doesn't work either.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by svnr-dvnkln** [comment]
nvm it worked on another client with another user.

I need to look for the reason myself first.

**Comment by thorsteneckel** [comment]
Please reopen if necessary.
