### ISSUE TITLE
"Welcome to nginx!" after installation

### ISSUE THREAD

**Issue by Alphaex1** [zammad/zammad#1701]
Hi i need some Help.

first im not that good with ubuntu at all so pls dont roast me to hard ^^ 

i installed Zammad as shown here https://docs.zammad.org/en/latest/install-ubuntu.html#go-to-http-localhost-and-you-ll-see

Newest Zammad version and Ubuntu 16.0.4

Now when i acces the server website i get only "Welcome to nginx!"
i have no clue why -_- 

If you need more infos just tell me i will provide everything :) 

have a nice day Person reading this !

**Comment by NeverMin** [comment]
hi @Alphaex1 ,

Since november 15th we handle all requests, except real bugs, at our community board. https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21
Please post:
- Feature requests
- Development questions
- Technical questions

on the board.

**Comment by thorsteneckel** [comment]
Please don't forget to add tags to closed issues.
