### ISSUE TITLE
Conncecting issues with Exchange 2010

### ISSUE THREAD

**Issue by BinaerGollum84** [zammad/zammad#1702]
### Infos:

* Used Zammad version:  2.2.0
* Used Zammad installation source: stable installer 7 package
* Operating system:   CentOS 7
* Browser + version:  actual FireFox 57 & Chrome

### Expected behavior:

* should connect to to our Exchange

### Actual behavior:

* cannot connect to our Exchange Server due an certificate error?

We use an old SBS2011 with Exchange 2010 (Upgrade will come somewhat in 2018).
In our regular environment everything works great...no issues at all.

As authetication I tried several exisiting user accounts - all with no success. Ldap integration on this zammad installation works also fine without any issues.

I guess, zammad doesn't like self signed certificates? And no, creating a new external certificate isn't an option right now or is it a neccessary requirement to use external/officaly signed certificates? I didn't read a line about this in the manuals, but feel free to correct me ;-)

I'm new to zammad and well, I'm sure I'm just missing a tiny point somewhere...

Attached Pictures:
![cert1](https://user-images.githubusercontent.com/34370493/33762902-b3cf98f6-dc0e-11e7-84c4-a907ac28b3ba.PNG)
![certif2](https://user-images.githubusercontent.com/34370493/33762903-b3ef9d04-dc0e-11e7-9eec-7af00e82006a.PNG)

**Comment by thorsteneckel** [comment]
Hi @BinaerGollum84 - Could you please provide your `log/production.log` file to `support@zammad.com` and refer to this issue. I'll have a look.

**Comment by hanneshal** [comment]
Log has been passed to @thorsteneckel
he will get back to you. @BinaerGollum84

**Comment by thorsteneckel** [comment]
1.) Create a file called `debug_exchange.rb` in your Zammad directory (usually `/opt/zammad`) and insert your Exchange credentials and endpoint
2.) Run the file from your Zammad directory via `zammad run rails r debug_exchange.rb` or `rails r debug_exchange.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! Send the output to our existing ticket.
4.) Delete the `debug_exchange.rb` file

```ruby
endpoint = 'https://server/EWS/Exchange.asmx'
user     = 'username@email.com'
password = 'your_password'

connection = Viewpoint::EWSClient.new(
  endpoint,
  user,
  password,
  {
    http_opts: {
      ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE
    }
  }
)

%i[root msgfolderroot publicfoldersroot].each do |parent_identifier|

  p parent_identifier
  begin
    child_folders = connection.folders(root: parent_identifier)
    p child_folders
  rescue Viewpoint::EWS::EwsFolderNotFound => e
    p e
  rescue Viewpoint::EWS::Errors::UnauthorizedResponseError => e
    p e
  ensure
    puts '-----------'
  end
end
```

**Comment by thorsteneckel** [comment]
No feedback in 3 month. Closing.

**Comment by sgrube287** [comment]
Hello thorsteneckel
i have the same problems with our exchange.
![exchange-config](https://user-images.githubusercontent.com/90676853/133209046-081df257-36e6-41fc-bb4b-eb861dec98f0.JPG)
all it is doing for hours is this
![exchange-config_2](https://user-images.githubusercontent.com/90676853/133209125-f0263daa-fafb-43c4-b98a-74d9ed1f988c.JPG)

i installed your debug data and pushed it into a file.
now my question: how can i find my problem in the debug data?
can i send you the data to find my problem?

Problemlösung gerne auch in Deutsch

**Comment by MrGeneration** [comment]
Post the debug log here, other wise please don't recycle old closed issues.

**Comment by sgrube287** [comment]
i am sorry for opening an old issue again.
[file-anonym.txt](https://github.com/zammad/zammad/files/7160174/file-anonym.txt)
i anonymed the server and the password


    Used Zammad version: 4.1.x
    Used Zammad installation type: Zammad for Ubuntu V 4.1.0
    Operating system: Ubuntu 20.04.3 LTS (64bit) → Virtulazation VMware ESX 7.0
    Browser + version: Mozilla Firefox 92.0 (64 bit)

**Comment by sgrube287** [comment]
Hello, is there some more information that be need?

**Comment by MrGeneration** [comment]
Please be patient while we're checking.
If you require commercial grade support contact sales at zammad dot com.

Bumping won't speed us up. Sorry.

**Comment by fliebe92** [comment]
Hi @BinaerGollum84, hi @sgrube287,

please feel free to re-open this report if it's still reproducible using Zammad 5.4. For the moment, we cannot do anything about it, we do not have access to a running Exchange 2010 server to be able to verify and debug this issue on our side.

Thanks for your understanding and all the efforts you put into this.
