### ISSUE TITLE
deb repository broken for Debian 8, 9

### ISSUE THREAD

**Issue by wollmers** [zammad/zammad#1703]
### Infos:

* Used Zammad version: 2.3.0 (latest stable)
* Used Zammad installation source: https://dl.packager.io/srv/zammad/zammad/develop/installer/debian/9.repo
* Operating system: Debian 8, Debian 9
* Browser + version: 

### Expected behavior:

* `apt-get update` and `install` should work as documented

### Actual behavior:

`# apt-get update`
`Hit:1 http://packages.icinga.org/debian icinga-stretch InRelease`
`Ign:2 http://ftp.uni-erlangen.de/debian stretch InRelease`                                                             
`Hit:3 http://ftp.uni-erlangen.de/debian stretch Release`                                                               
`Hit:4 http://security.debian.org stretch/updates InRelease`       
`Ign:6 https://dl.packager.io/srv/deb/zammad/zammad/develop/debian 9 InRelease`
`Fetched 1,217 B in 1s (1,149 B/s)`
`Reading package lists... Done`

Seems `apt-get update` never gets a working connection to the repository.

Had to download the .deb manually and install via `dpkg -i`. 

### Steps to reproduce the behavior:

* `wget -qO- https://dl.packager.io/srv/zammad/zammad/key | apt-key add -`
* `wget -O /etc/apt/sources.list.d/zammad.list https://dl.packager.io/srv/zammad/zammad/develop/installer/debian/9.repo
`
Yes I'm sure this is a bug and no feature request or a general question.

**Comment by monotek** [comment]
2.3.0 is not the stable version. You're using the develop version.
Debian 9 installation works for me.

**Comment by martini** [comment]
And it seems to  be a problem at packager.io infrastructure. :-/

**Comment by thorsteneckel** [comment]
@monotek - please remember to set the labels when closing an issue.

**Comment by wollmers** [comment]
@montek - 2.3.0 was the version I installed, i.e. 

`dpkg -i zammad_2.3.0-1512661380.b42b7cf6.stretch_amd64.deb`

**Comment by wollmers** [comment]
@martini seems not the first problem at packager.io infrastructure, but @thorsteneckel won't solve. Who else?

**Comment by thorsteneckel** [comment]
@wollmers - feel free to open an issue at https://github.com/crohr/pkgr/issues

**Comment by audhen** [comment]
Still broken :-(

**Comment by thorsteneckel** [comment]
Closing now since it's an issue at the side of https://github.com/crohr/pkgr as described earlier. Sadly we can't do anything. Please create an issue over there.
Usually it takes some time and it works again. Sorry for your inconvenience.
