### ISSUE TITLE
Trigger - missing integer and tree_select as 'Conditions for effected objects'

### ISSUE THREAD

**Issue by Sandalas** [zammad/zammad#1706]
### Infos:

* Used Zammad version: 2.1.x
* Installation method (source, package, ..): yum
* Operating system: CentOS 7
* Database + version: PostgreSQL 9.2.23
* Elasticsearch version: -
* Browser + version: Firefox ESR 52.5.2

### Expected behavior:

* Have 'integer' and 'tree_select' objects in the list of the 'Conditions for effected objects'.

### Actual behavior:

* Both are missing in 'Conditions for effected objects', but exist as valid selection for the 'Execute changes on objects'.

### Steps to reproduce the behavior:

* Create a ticket object of the type 'integer' or 'tree_select'
* Go to 'Triggers'
* Create a new one and try to select your created field as a condition

![missingtriggerconditions](https://user-images.githubusercontent.com/12407768/33824168-c030c236-de5d-11e7-8f8c-64a814f97102.png)

Yes I'm sure this is a bug and no feature request or a general question:

* I couldn't find a list with valid 'Conditions for effected objects' in the diverse documentations

**Comment by umarsheikh** [comment]
Hi @Sandalas  @thorsteneckel @martini this is now fixed on https://github.com/zammad/zammad/pull/1718/files , hopefully it can be merged after tests pass!

**Comment by umarsheikh** [comment]
@thorsteneckel tests are now also passing after merging latest develop into the PR branch. please review and leave your feedback!

**Comment by Saliva520319** [comment]
I also meet this problems. hope this can help to solve the problems.

**Comment by jwronken** [comment]
it seems a tree_select object on a ticket is not visible when creating a new report profile.
changing to select works, but a tree_select object doesn't show up.
Steps to duplicate: create new attribute in System > Objects > Ticket Object Manager with type tree_select. Update db and restart Zammad. Go to Manage -> Report Profiles and create New Profile
Filter Ticket doesn't show the created tree_select object.
