### ISSUE TITLE
Facebook searches

### ISSUE THREAD

**Issue by markhowells** [zammad/zammad#1707]
I have my zammad linked to Facebook. The docs state

> You will get redirected back to Zammad. Now you need to configure your search keys, where mentions and direct messages should get routed.

But I have no idea how to do this.. My page exists and zammad collected 7 tickets from the hundreds of posts there. How do I configure search settings?

**Comment by monotek** [comment]
This is the bugtracker.
Please use the forum to ask questions.
https://community.zammad.org
