### ISSUE TITLE
Weird, https://github.com/zammad/zammad/compare/2.2.0...2.3.0 does list almost nothing.

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1708]
Weird, https://github.com/zammad/zammad/compare/2.2.0...2.3.0 does list almost nothing.

**Comment by martini** [comment]
Hi @passboltUser 

the link show the differences between master and 2.2 (which is both currently the same).

What do you want to see? The changes between 2.2 and current development state?

Then you need to use the following https://github.com/zammad/zammad/compare/2.2.0...develop

 -Martin

**Comment by passboltUser** [comment]
Hm, but `master` and `2.3.0 ` are normally two different things. Ok, `develop` is enough.

**Comment by martini** [comment]
> but master and 2.3.0 are normally two different things.

That's correct. We tag master with next stable tag to get packages build from https://packager.io 

So people can also use current master if the want to use current Zammad edge.

Ist 2.3 is stable the tag 2.3.0 from master is removed and used the correct way.

**Comment by passboltUser** [comment]
Not sure, maybe unconventional, but ok, I understand.
