### ISSUE TITLE
Zammad Api for idoit.object_ids broken

### ISSUE THREAD

**Issue by jaykijay** [zammad/zammad#1711]
### Infos:

* Used Zammad version: 2.2 stable
* Installation method (source, package, ..): Debian package
* Operating system: Debian 9
* Database + version: irrelevant, but its latest postgresql
* Elasticsearch version: 5.x tested with old mapper-attachmanets and new ingest-.attachment plugin
* Browser + version: all

### Expected behavior:

* See Tickets in idoit when Zammad Integration is enabled there.

### Actual behavior:

* No Tickets are listed, even if there are existing.
I digged deeper in the issue, and a pure curl request with:
'https://zammadurl/api/v1/tickets/search?query=preferences.idoit.object_ids:$objectidfromidoitobectwhichhasaticketinzammad&limit=10&expand=true'
doesn't show any resluts back. Instead i get [] only.
If i search in zammad using: preferences.idoit.object_ids:$objectidfromidoitobectwhichhasaticketinzammad
i get the Ticket(s) listed which has the idoit objects linked to it.
So the Bug is only on the API, not internal in Zammad Webinterface, which will result in broken Idoit -> Zammad Integration.

### Steps to reproduce the behavior:

* Use Zammad Api and search for idoit object ids.
e.g:
curl -u user:pw 'http://zammadurl/api/v1/tickets/search?query=preferences.idoit.object_ids:1273076&limit=10&expand=true'

![grafik](https://user-images.githubusercontent.com/24495677/33947447-adfe3ee0-e024-11e7-9509-561ee8b47b3c.png)

![grafik](https://user-images.githubusercontent.com/24495677/33947362-7c3a8e4a-e024-11e7-80e2-60b7079605b6.png)

Production.log:
I, [2017-12-13T17:01:08.058306 #22654]  INFO -- : Started GET "/api/v1/tickets/search?query=preferences.idoit.object_ids:1273076&limit=10&expand=true" for 127.0.0.1 at 2017-12-13 17:01:08 +0100
I, [2017-12-13T17:01:08.067379 #22654]  INFO -- : Processing by TicketsController#search as */*
I, [2017-12-13T17:01:08.067543 #22654]  INFO -- :   Parameters: {"query"=>"preferences.idoit.object_ids:1273076", "limit"=>"10", "expand"=>"true"}
I, [2017-12-13T17:01:08.560509 #22654]  INFO -- : Authentication against Auth::Internal for user xxxxxxx ok.
I, [2017-12-13T17:01:08.727161 #22654]  INFO -- : Completed 200 OK in 659ms (Views: 0.4ms | ActiveRecord: 36.5ms)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
@jaykijay just update your Debian package. It's fixed. Feedback is welcome.

**Comment by jaykijay** [comment]
Thanks for the fix :) It's working fine now. Tested it via Curl and Idoit Integration.
