### ISSUE TITLE
OTRS migration fails with ForeignKeyViolation

### ISSUE THREAD

**Issue by newspeer** [zammad/zammad#1713]
### Infos:

* Used Zammad version: 2.2.0-1513237090.47a1bb76.stretch
* Installation method (source, package, ..): Package
* Operating system: Debian 9.3
* Database + version: 10.1.26-MariaDB-0+deb9u1
* Elasticsearch version: 5.6.5
* Browser + version: Chrome 63.0.3239.84

OTRS Version: 5.0.14
Znuny4OTRS-Repo: 5.0.33
Znuny4OTRS-ZammadMigrator: 1.2.1

### Expected behavior:
Migrate from OTRS via command line without errors and interruption

### Actual behavior:
Migration aborts with the following error:
"ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: FEHLER:  Einfügen oder Aktualisieren in Tabelle »ticket_priorities« verletzt Fremdschlüssel-Constraint »fk_rails_d43af6872e«
DETAIL:  Schlüssel (updated_by_id)=(22) ist nicht in Tabelle »users« vorhanden."

### Steps to reproduce the behavior:
Install ruby, mysql/mariadb, nginx, openjdk8, elasticsearch, zammad
Follow OTRS migration instructions and "Import via command line".

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @newspeer - It seems that your OTRS is missing a User with the ID 22. Can you please check your OTRS database if there is a record with the ID 22 in the table `users`?

**Comment by newspeer** [comment]
Hi @thorsteneckel the user is in the table. I attached a screenshot of the table

![b74ac7f6](https://user-images.githubusercontent.com/24868852/33992424-cb3e1a08-e0d2-11e7-98d9-5b043dcd17f2.PNG)

**Comment by thorsteneckel** [comment]
Hi @newspeer - please check the following URL on your OTRS with your API Key:

`http://*yourotrs.tld*/otrs/public.pl?Action=ZammadMigrator;Key=*APIKEY*;Object=User;Subaction=Export`

Is there an entry with the `UserID: "22"`?

**Comment by newspeer** [comment]
There is:

![otrs](https://user-images.githubusercontent.com/24868852/33995085-1f1cb472-e0dd-11e7-9b39-621bdaf686e5.png)

**Comment by thorsteneckel** [comment]
Hi @newspeer - Thanks for your fast responses. I'll have a look what I can find out with the given information.

**Comment by thorsteneckel** [comment]
Hi @newspeer - happy new year 🚀 We found the issue causing this. It's a logical / design issue in the current implementation. Priorities get imported before the users, see https://github.com/zammad/zammad/blob/develop/lib/import/otrs.rb#L162 . While trying to import the Priorities the User with the ID `22` is not imported yet and causes the error.

However, we will refactor the import logic from the ground up and fix this issue with this.

As a workaround you can go to your OTRS Priority Admin Interface and update all affected Priorities with the `root@localhost` user.

**Comment by Nobsadmin** [comment]
![image](https://user-images.githubusercontent.com/119046865/204097857-1a361f93-7465-4e59-91d0-43709b331b24.png)
Any way to EDIT the created by ID? The modified ID is already 1 now but importing still stuck on priorities.
