### ISSUE TITLE
Pending till date not displayed correctly?

### ISSUE THREAD

**Issue by svnr-dvnkln** [zammad/zammad#1716]
### Infos:

* Used Zammad version: 2.2.x
* Installation method (source, package, ..): deb9 rep
* Operating system: deb9 server, win7/10 client
* Database + version: PostgreSQL 9.6.6
* Elasticsearch version: 5.6.5
* Browser + version: all

### Expected behavior:

* With the setting **Branding -> Pretty Date -> absolute** all times should be displayed as (f. e.) "Friday 08:00"

### Actual behavior:

* Only pending reached tickets are displayed with an absolute date. Still pending tickets are displayed with a relative date.
![screenshot - 15_12](https://user-images.githubusercontent.com/33687762/34032344-f0890a4a-e175-11e7-8660-c012de737f39.png)

### Steps to reproduce the behavior:

* Configure the pretty date to be absolute and create some pending tickets

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
This is fixed with the commits above and will be available in develop (~30 minutes from now) and or after Zammad 2.4 is released 🚀closing now.
