### ISSUE TITLE
Feature request: non-unconditional removal of links

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#1721]
Linked tickets can contain important or even essential information about processes, solutions, workflows ecc. related to a specific issue.  However a linked ticket is removed with a single (mis)click.  Not even an explicit "Update" is required to update the information in Zammad.  To be on the safe side, we usually also write the linked ticket number into a comment.  This is redundant and should not be required.

I suggest to make the removal or change of an existing link conditional/interactive through an appropriate dialogue ("Do you really want to remove the link to ticket <no> (<title>)") to avoid unintentional removal.

**Comment by monotek** [comment]
Please use https://community.zammad.org/ for feature requests.

**Comment by fthommen** [comment]
The list of issues is full with feature requests (aka "enhancements" aka "proposal") which are **not** redirected to  https://community.zammad.org/.  Why this one?

**Comment by monotek** [comment]
https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21

**Comment by fthommen** [comment]
thx.
