### ISSUE TITLE
Can´t reach Zammad from subdomain

### ISSUE THREAD

**Issue by BinaerGollum84** [zammad/zammad#1725]
### Infos:

* Used Zammad version: 2.2.x
* Installation method (source, package, ..): epel-repository 
* Operating system: CentOS7
* Database + version: postgres
* Elasticsearch version: 6.x
* Browser + version: Firefox 57 / Chrome

### Actual behavior:
i arranged port forwarding and a subdomain so our customers can reach the Zammad Login. 
i set the IP from our server in the zammad.conf 
but i only get the nginx start page. 
localhost works fine.

**Comment by monotek** [comment]
Please use https://community.zammad.org for questions.
