### ISSUE TITLE
User-friendliness & usability analysis and suggestions

### ISSUE THREAD

**Issue by inrobin** [zammad/zammad#1728]
Hi, I've just tested Zammad at zammad.com and very impressed. Zammad is the best open source helpdesk (among over 30 open source systems tested so far), but there are several critical things, which does not allow us to start using it in our worldwide non-profit. Main thing is the ticket interface which is super non-user-friendly & misleading and email notifications to users & agents. Hope it is not too late to share this info.

Try to open ticket interface, imagine you see it first time and try to interact with the ticket. The most user-friendly and intuitive interface for now is HelpScout's, check it, analyse it. In Zammad each step I've done in order to reply to the ticket was like an unpredictable adventure, I did not know what will happen if I click this or that button. The main principle must be: "The simpler - the better".

We just can't start using Zammad because our support agents in different countries will be unable to properly reply to the tickets without special education which is ridiculous. So advice for the Zammad team: 

> Put aside all seemingly important features, focus now only on bugs, emails to users and ticket interface, this is the most important part of the system, make it simple, self-explanatory and straightforward. It is difficult to dare to change something which seems to be ready, but sometimes it has to be done. Come together, discuss and make it perfect.

Let's start:

1) I opened a ticket, typed the text and wanted to submit a reply to the user, but I could not find a big blue "Reply" button. There was an "Update" button in the lower right corner of the screen, I had no idea what it is for, it was located quite far from the "Reply" textarea. Finally I decided to click "Update" button and my reply was sent to the user. Now I learned that "Update" means "Reply".
Solution: Make a real "Send Reply" button right under the reply textarea (see HelpScount) and another "Update" button in the sidebar. No need to mix "Reply" and "Update ticket status/parameters" functions.

2) After some time I learned that it was not a reply to the user. I've created a note to the ticket.
Solution: Agent must clearly understand what he is creating: a note or reply. Little tiny switcher Note-Reply-Call without any hover hints is not enough. Make three separate radio buttons to the left from the textarea: Note, Reply and Call. "Reply" must be default action.

3) After that I noticed a gear and pencil buttons with some colors on top without any hover hints. I still don't know what this colors button with pencil is doing.
Solution: Add some explanation to the button or get rid of it. Only important elements must be present on the ticket screen. This is the most important screen of the whole system.

4) Now I needed info about the user who created a ticket: there was no user's email displayed on the screen at all (!!!) I found a button with a man icon without any hover hint and user email was there.
Solution: Agent must always see user's email and name (see HelpScout)

5) After that I noticed an arrow in the top right corner of the right sidebar. Arrow did not have any hint, so I decided that it will open next ticket, but it just collapsed the sidebar.
Solution: Add a hover hint or replace it with some more common "collapsing" element.

6) When the sidebar is open the bottom "Discard your unsaved changes" button seems to be completely disconnected from the ticket textarea where I'm making changes.
Solution: Place "Discard" button right under or above the reply textarea.

7) Now I noticed little tiny "reply" button under each user's message in the thread with a bunch of other buttons without any hover hints (lock, arrow, I still don't know what "right arrow" button means). I decided that this reply button will allow me somehow to reply to this specific user's message. But this reply button just scrolled me to the reply textarea.
Solution: Add one "Reply" button on top instead of that "pencil-colors" button which will scroll to the reply textarea.

8) For me it was very difficult to distinguish between messages from user, my messages and notes in the thread. Ticket thread for now looks like a colorful mess with numerous small buttons and circles.
Solution: See how it looks in HelpScout and just do the same. Simple and clear.

9) TO field is not needed when replying to the ticket as I'm replying to the user and his email must be always visible somewhere on the ticket thread. There should be a link-button allowing to change user which is receiving replies to the ticket.
Solution: Again see how it works in HelpScout and do similar.

10) CC field is always visible when replying, this is a waste of space.
Solution: Display small "Cc" link which opens CC field.

11) When I clicked on the message in the thread two black areas appeared. This is the most unexpected and unusual "feature" I've seen in the system :)
Solution: Just show above each message in the thread: user's name, date, channel (see HelpScout)

12) Email which user received contained only my reply to the ticket, but not user's question. This is not acceptable, user must see whole ticket thread in each email he receives (see Gmail and HelpScout). Now it does looks like support agent cuts out previous email history and sends just his reply, which is not good.
Solution: It looks like already there is a ticket #816 for this.

13) Agent should be able to reply on email notification.
Solution: #1203

Thank you guys

**Comment by thorsteneckel** [comment]
Thanks for your comprehensive analyses. Unfortunately this is our issue tracker and and non-bugs are handled in our board over at https://community.zammad.org/ as stated in the issue template. Would be great if you could transfer it over there. Thanks.
