### ISSUE TITLE
No CSS, after Upgrade

### ISSUE THREAD

**Issue by rakinzon** [zammad/zammad#1731]
### Infos:

* Used Zammad version: 2.2.0-1513786667.dbad0f53.stretch
* Installation method (source, package, ..): Package for Debian 9 (https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 9/main amd64 zammad amd64)
* Operating system: Debian 9
* Database + version: unknown
* Elasticsearch version: unknown 
* Browser + version: Safari 11.0.2 and newest google chrome 

### Expected behavior:

* See Zammad with CSS

### Actual behavior:

* Zammad URL/assets/application-8bac04eddc54b18b6be36c68f6ef6e299435ad58696c1ab33a89828d3e867c98.css Error 404
* Problem exists on 2 server with Debian 9, before the upgrade both zammad installations was running fine.

### Steps to reproduce the behavior:

* Upgrade to 2.2.0-1513786667.dbad0f53.stretch

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @rakinzon 

normally this should not happen (because the new CSS is included in the package). Did you restart Zammad?

In case if it's still not working. You can fix it manually with:

1) `zammad run rake assets:precompile`
2) restart zammad

I can't reproduce the problem. Maybe you have more hits to get it reproducible?

 -Martin

**Comment by rakinzon** [comment]
Hey,

the comment `zammad run rake assets:precompile` fixes the issue on both server. Thanks for the fast answer. 

Best regards.

**Comment by martini** [comment]
Thanks for feedback.

JFI: The assets are located under `/opt/zammad/public/assets/` and the `application-XXX.css` is in the package. Maybe there is something wrong on your local deployment. 

Anyways. It's good that it's working again. 🤠

**Comment by monotek** [comment]
I could not reproduce the error when updating my debian 9 testsystem.
