### ISSUE TITLE
IMAP STARTTLS support

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1735]
### Infos:

* Used Zammad version: 2.2
* Installation method (source, package, ..): git
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Support of STARTTLS for IMAP connections as for e.g. SMTP.

### Actual behavior:

* IMAP does not supprt STARTTLS.

### Steps to reproduce the behavior:

* Connect to an IMAP server that supports/requires STARTTLS.

Yes I'm sure this is a bug and no feature request or a general question.

Implementation in the backend is pretty easy. just call `@imap.starttls` before https://github.com/zammad/zammad/blob/705487154c81599768dd5429d23434f59422b03e/app/models/channel/driver/imap.rb#L99

Frontend and configuration and matching conditions need to be done too.

**Comment by monotek** [comment]
duplicate of: https://github.com/zammad/zammad/issues/769

**Comment by thorsteneckel** [comment]
Thanks! Closing.
