### ISSUE TITLE
All of a sudden, page layout is destroyed

### ISSUE THREAD

**Issue by TheRich-71** [zammad/zammad#1738]
### Infos:

* Used Zammad version: 2.2 (latest)
* Installation method (source, package, ..): deb
* Operating system: Debian 9.3
* Database + version: PostgreSQL 9.6
* Elasticsearch version: 5.6.5
* Browser + version: Firefox, IE 11

### Expected behavior:

* Standard Layout of LogIn Page with our logo

### Actual behavior:

* Worked until a few days ago, now I receive something like show here: [screenshot](https://screenshots.firefox.com/nCS5ukx42vQZGpgo/helpdesk.fritz.box). After logging in, following pages are nearly unreadable.
Apache Log shows a 404 for a strangely named file, I assume this is the problem since it is a CSS. But where does this strange name come from?
[08/Jan/2018:14:24:53 +0100] "GET /assets/application-8bac04eddc54b18b6be36c68f6ef6e299435ad58696c1ab33a89828d3e867c98.css HTTP/1.1" 404 501 "http://helpdesk.fritz.box/" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; MDDRJS; rv:11.0) like Gecko"

### Steps to reproduce the behavior:

* Unfortunately no idea, we are not using the helpdesk daily. The last I remember before was an update for imagemagic, but this is probably not involved?!

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
@TheRich-71  Seems that the css file is missing.

You can try running in /opt/zammad `zammad run rails assets:precompile ` which will generate the necessary css file.

**Comment by martini** [comment]
JFI: Seems to be the same as it was here https://github.com/zammad/zammad/issues/1731 - but was not reproducible. Also @monotek tried to reproduce it, without success.

**Comment by TheRich-71** [comment]
Thanks for your comments. The `zammad run rails assets:precompile` generated a few files, but not the desired one. I got the message 

> Ignoring argon2-1.1.3 because its extensions are not built.

So, I decided to purge the installation, watched the errors about several directories which could not be removed and removed manually the ruby-dirs. Now, after reinstallation, everything works fine.
