### ISSUE TITLE
Attachment file corruption

### ISSUE THREAD

**Issue by nbougues** [zammad/zammad#1739]
### Infos:

* Used Zammad version: 2.2.0-1513786667.dbad0f53.stretch amd64
* Installation method (source, package, ..): package
* Operating system: Debian stretch
* Database + version: Postgres 5.6.5
* Elasticsearch version: 9.6+181+deb9u1
* Browser + version: Chrome 63

### Expected behavior:

Recover attachment file unaltered.

### Actual behavior:

In some cases (not clearly detemined) attached files get corrupt.
Corruption issue seems to be about removed LF character at end of lines **for non text files** (in our case, a pcap file for a SIP capture which somehow is "mostly text" but it's really a binary file)

### Steps to reproduce the behavior:

Send an email with the attached file to Zammad and try to download it.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by nbougues** [comment]
[files.zip](https://github.com/zammad/zammad/files/1615404/files.zip)

**Comment by muhammadn** [comment]
Hi @nbougues 

Took me a long time to debug this code and i found out that the problem is the mail library we were using.

https://github.com/mikel/mail/commit/21222e1b48f08f6f848d26643d6b6fb1d873d18c

I will check if it is possible that we can upgrade to the latest version (in the commit above) 😊

**Comment by rlue** [comment]
e7caca5 introduced the latest release of the Mail gem to Zammad. Can we confirm that this fixes the bug? I haven't reproduced the issue because I'm still not sure how to set up email on my development instance tbh...

**Comment by rlue** [comment]
@nbougues Using the `files.zip` file you provided, I actually wasn't even able to reproduce this issue _before_ the mail gem upgrade. Please try upgrading Zammad to the latest version (2.5.0) and let us know if the issue persists.

**Comment by muhammadn** [comment]
@rlue actually you need to unzip the files and use the `original.pcap` file to send to pipe to `rails r 'Channel::Driver::MailStdin.new'`

usually i would checksum the original.pcap with the one already processed into the ticket.

**Comment by rlue** [comment]
Thank you @muhammadn, I feel pretty silly for missing that. -_-'

I've now reproduced the bug in the pre-fix commits and verified that the fix is working.
