### ISSUE TITLE
Formatierungen in Notizen/Mails

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#174]
Strg+Alt+l funktioniert unter Linux nicht: das sperrt den Bildschirm.

Ich finde, dass das Thema Formatierung noch nicht sehr gelungen gelöst ist. Wenn schon HTML-Mails: warum gibt es keine Formatierungsleiste wie hier in Github?

Ich habe das Gefühl, dass die Eingabe etwas verzögert erfolgt. Wenn ich hier in Github tippe, merke ich diese kleine Verzögerung nicht.

**Comment by monotek** [comment]
Maybe theres a way to hide it by default and just show it when needed. 
Could be a button beside "select attachment..."?

**Comment by thorsteneckel** [comment]
This is a duplicate of #656 and #330 so I'm closing this one here.
