### ISSUE TITLE
Exchange integration process stuck at 1000 users

### ISSUE THREAD

**Issue by gitbit12665** [zammad/zammad#1740]
### Infos:

* Used Zammad version: 2.2.x
* Installation method (source, package, ..): package RPM
* Operating system: CentOS 7 x64
* Database + version: PostgreSQL 9.2.23
* Elasticsearch version: 5.6.5
* Browser + version: Chrome (63.0.3239.xx)

### Expected behavior:

- Get the contact information of 1899 users via Exchange Online
- Create new users (based on the information in exchange)

### Actual behavior:

- New users are created, but only 1000
- Sync always stops at 1000 users 

### Steps to reproduce the behavior:

- try another Exchange Account
- reinstall system
- searched for max users in Zammad Community

**LOG**:
[production.log](https://github.com/zammad/zammad/files/1615547/production.log)

**SCREENSHOT**:
![screenshot_setup_exchange](https://user-images.githubusercontent.com/35261711/34727382-0227e4de-f557-11e7-9c4d-a8bc7f42b6a8.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @gitbit12665 - very interesting catch. I think I found a solution. Could you please do the following:

1. Download and unzip [sub_sequence.rb.zip](https://github.com/zammad/zammad/files/1616147/sub_sequence.rb.zip)
2. Create a backup of the file `lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb` in your Zammad folder
3. Replace the backuped file `lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb` with the extracted `sub_sequence.rb`
4. [Restart your worker and web application server](https://docs.zammad.org/en/latest/install-centos.html#you-can-manage-the-zammad-services-manually)
5. Retry the Exchange sync.

Please check if your `log/production.log` file contains lines like this `Fetching and processing 1000 items (page: 1, offset: 0) from Exchange folder 'AllContacts' (total: 4)`. If so, please provide a list of them. Otherwise provide the whole file again. Thanks!

**Comment by thorsteneckel** [comment]
That's strange since it should not affect other components and tests on my and our CI env went fine. Could you please check your `log/scheduler_err.log` file. What's the content of that?

How did you backup the file in the first place? Maybe this file is corrupting the startup process. 

How does it behave if you restore your backup file?

**Comment by gitbit12665** [comment]
@thorsteneckel 

![image_files](https://user-images.githubusercontent.com/35261711/34738649-f9d5b78e-f579-11e7-98c4-3162874eedc8.png)

i shut zammad down, rename sub_sequence.rb->sub_sequence.rb.bkp, upload new sub_sequence.rb which you had created.
Set permissions like the original .rb file and start zammad again.

scheduler_err.log & scheduler_out.log are both empty.

After restore the backup file it worked again.

**Comment by thorsteneckel** [comment]
Can you please move the backup out of the folder, place the new file in the folder again and retry? I'm not sure why this is happening (without an error). 🤔

**Comment by gitbit12665** [comment]
Do you replace the file before or after activate the exchange migration/sync the first time?

**Comment by thorsteneckel** [comment]
That doesn't matter. I'll have to go now but will provide another test script tomorrow where no files need to be changed. Let me know if you get it working in the meantime. 🤞

**Comment by gitbit12665** [comment]
I will!

**Comment by thorsteneckel** [comment]
So here comes the script:

0.) Reset your Zammad files to default so you have a standard system again.
1.) Create a file called `debug_exchange.rb` in your Zammad directory (usually `/opt/zammad`)
2.) Run the file from your Zammad directory via `zammad run rails r debug_exchange.rb` or `rails r debug_exchange.rb` as zammad user, depending on your installation source (package/source)
3.) Post the output here. Make sure all sensitive data is anonymized! If you want you can drop it as an email to support@zammad.com. Please refer to this issue and me :)
4.) Delete the `debug_exchange.rb` file

```ruby
require 'sequencer'
require 'sequencer/unit'

class Sequencer
  class Unit
    module Import
      module Exchange
        module FolderContacts
          class SubSequence < Sequencer::Unit::Base
            include ::Sequencer::Unit::Exchange::Folders::Mixin::Folder
            include ::Sequencer::Unit::Import::Common::SubSequence::Mixin::ImportJob

            uses :ews_folder_ids

            def process
              return if ews_folder_ids.blank?

              ews_folder_ids.each do |folder_id|
                folder = ews_folder.find(folder_id)
                paginated_item_sequence(folder)
              end
            end

            private

            def paginated_item_sequence(folder)

              total    = folder.total_count
              per_page = 1000
              pages    = (total.to_f / per_page.to_f).ceil

              display_path = ews_folder.display_path(folder)
              (1..pages).each do |page|

                offset = (page - 1) * per_page

                opts = {
                  indexed_page_item_view: {
                    max_entries_returned: per_page,
                    offset:               offset,
                    base_point:           'Beginning'
                  }
                }

                logger.debug "Fetching and processing #{per_page} items (page: #{page}, offset: #{offset}) from Exchange folder '#{display_path}' (total: #{total})"

                folder.items(opts).each do |item|

                  sequence_resource(item) do |parameters|

                    item = parameters[:resource]

                    logger.debug "Extracting attributes from Exchange item: #{item.get_all_properties!.inspect}"

                    parameters.merge(
                      resource:        ::Import::Exchange::ItemAttributes.extract(item),
                      ews_folder_name: display_path,
                    )
                  end
                end
              end
            end

            def sequence
              'Import::Exchange::FolderContact'
            end
          end
        end
      end
    end
  end
end

ImportJob.dry_run(name: 'Import::Exchange', payload: ImportJob.last.payload, delay: false)

p ImportJob.last.result
```

Attention: This might take some time, since you have a lot of entries. Result should be a report of how many entries should be imported. It's a dry run, so no actual data will be stored.

Please check if your `log/production.log` file contains lines like this `Fetching and processing 1000 items (page: 1, offset: 0) from Exchange folder 'AllContacts' (total: 4)`. If so, please provide a list of them. Otherwise provide the whole file again. Thanks!

**Comment by gitbit12665** [comment]
@thorsteneckel 
Thanks for your instructions, I tried these steps.

**Output after running the script:**
![zammad_error_2](https://user-images.githubusercontent.com/35261711/34772287-ceda6046-f607-11e7-96b7-c860d135d9ed.PNG)

Exchange account was added but not activated yet (via the switch)

**Comment by gitbit12665** [comment]
**data structure under: /opt/zammad/lib/sequencer**

├── mixin
│   ├── exchange
│   │   └── folder.rb
│   ├── import_job
│   │   └── resource_loop.rb
│   ├── prefixed_constantize.rb
│   └── sub_sequence.rb
├── sequence
│   ├── base.rb
│   ├── exchange
│   │   └── folder
│   │       └── attributes.rb
│   └── import
│       └── exchange
│           ├── attributes_examples.rb
│           ├── available_folders.rb
│           ├── folder_contact.rb
│           └── folder_contacts.rb
├── sequence.rb
├── state.rb
├── unit
│   ├── base.rb
│   ├── common
│   │   └── attribute_mapper.rb
│   ├── exchange
│   │   ├── connection.rb
│   │   └── folders
│   │       ├── by_ids.rb
│   │       └── id_path_map.rb
│   ├── import
│   │   ├── common
│   │   │   ├── import_job
│   │   │   │   ├── payload
│   │   │   │   │   └── to_state.rb
│   │   │   │   ├── statistics
│   │   │   │   │   ├── store.rb
│   │   │   │   │   └── update.rb
│   │   │   │   └── sub_sequence
│   │   │   │       ├── general.rb
│   │   │   │       └── resource.rb
│   │   │   ├── mapping
│   │   │   │   ├── flat_keys.rb
│   │   │   │   └── mixin
│   │   │   │       └── provide_mapped.rb
│   │   │   ├── model
│   │   │   │   ├── associations
│   │   │   │   │   ├── assign.rb
│   │   │   │   │   └── extract.rb
│   │   │   │   ├── attributes
│   │   │   │   │   ├── add_by_ids.rb
│   │   │   │   │   ├── check_mandatory.rb
│   │   │   │   │   └── remote_id.rb
│   │   │   │   ├── create.rb
│   │   │   │   ├── external_sync
│   │   │   │   │   ├── create.rb
│   │   │   │   │   ├── local.rb
│   │   │   │   │   └── lookup.rb
│   │   │   │   ├── http_log.rb
│   │   │   │   ├── mixin
│   │   │   │   │   ├── handle_failure.rb
│   │   │   │   │   ├── skip_on_provided_instance_action.rb
│   │   │   │   │   └── skip_on_skipped_instance.rb
│   │   │   │   ├── save.rb
│   │   │   │   ├── skip
│   │   │   │   │   ├── blank
│   │   │   │   │   │   ├── base.rb
│   │   │   │   │   │   ├── mapped.rb
│   │   │   │   │   │   └── resource.rb
│   │   │   │   │   └── missing_mandatory
│   │   │   │   │       ├── base.rb
│   │   │   │   │       └── resource.rb
│   │   │   │   ├── statistics
│   │   │   │   │   ├── diff.rb
│   │   │   │   │   └── mixin
│   │   │   │   │       └── diff.rb
│   │   │   │   └── update.rb
│   │   │   └── user
│   │   │       ├── attributes
│   │   │       │   └── downcase.rb
│   │   │       └── email
│   │   │           └── check_validity.rb
│   │   └── exchange
│   │       ├── attribute_examples.rb
│   │       ├── attribute_mapper
│   │       │   ├── attribute_examples.rb
│   │       │   └── available_folders.rb
│   │       ├── folder_contact
│   │       │   ├── http_log.rb
│   │       │   ├── mapping.rb
│   │       │   ├── remote_id.rb
│   │       │   ├── static_attributes.rb
│   │       │   └── statistics
│   │       │       └── diff.rb
│   │       └── folder_contacts
│   │           ├── dry_run_payload.rb
│   │           ├── folder_ids.rb
│   │           ├── sub_sequence.rb
│   │           └── sum.rb
│   └── mixin
│       └── dynamic_attribute.rb
├── unit.rb
├── units
│   ├── attribute.rb
│   └── attributes.rb
└── units.rb

**Comment by thorsteneckel** [comment]
Ah my bad. I did it for the latest codebase version but not for Zammad 2.2 😖

Can you please redo with the following code:

```ruby
require 'sequencer'
require 'sequencer/unit'

class Sequencer
  class Unit
    module Import
      module Exchange
        module FolderContacts
          class SubSequence < Sequencer::Unit::Base
            include ::Sequencer::Mixin::Exchange::Folder
            include ::Sequencer::Mixin::ImportJob::ResourceLoop

            uses :ews_folder_ids

            def process
              return if ews_folder_ids.blank?

              ews_folder_ids.each do |folder_id|
                folder = ews_folder.find(folder_id)
                paginated_item_sequence(folder)
              end
            end

            private

            def paginated_item_sequence(folder)

              total    = folder.total_count
              per_page = 1000
              pages    = (total.to_f / per_page.to_f).ceil

              display_path = ews_folder.display_path(folder)
              (1..pages).each do |page|

                offset = (page - 1) * per_page

                opts = {
                  indexed_page_item_view: {
                    max_entries_returned: per_page,
                    offset:               offset,
                    base_point:           'Beginning'
                  }
                }

                logger.debug "Fetching and processing #{per_page} items (page: #{page}, offset: #{offset}) from Exchange folder '#{display_path}' (total: #{total})"

                folder.items(opts).each do |item|

                  sequence_resource(item) do |parameters|

                    item = parameters[:resource]

                    logger.debug "Extracting attributes from Exchange item: #{item.get_all_properties!.inspect}"

                    parameters.merge(
                      resource:        ::Import::Exchange::ItemAttributes.extract(item),
                      ews_folder_name: display_path,
                    )
                  end
                end
              end
            end

            def sequence
              'Import::Exchange::FolderContact'
            end
          end
        end
      end
    end
  end
end

ImportJob.dry_run(name: 'Import::Exchange', payload: ImportJob.last.payload, delay: false)

p ImportJob.last.result
```

**Comment by gitbit12665** [comment]
No problem :)
**I've executed the changed code:**

**First Output:**
> Cookie#domain returns dot-less domain name now. Use Cookie#dot_domain if you need "." at the beginning.


**Second after ~ 2 mins:**
> {"sum"=>1900, "Meine Kontakte"=>{"sum"=>1900}, "error"=>"undefined method `sequence_resource' for #<Sequencer::Unit::Import::Exchange::FolderContacts::SubSequence:0x005643d4b21600>"}

**Comment by thorsteneckel** [comment]
Ok, seems there are too many differences to 2.2 to get it working. Please retry with:

```ruby
require 'sequencer'
require 'sequencer/unit'

class Sequencer
  class Unit
    module Import
      module Exchange
        module FolderContacts
          class SubSequence < Sequencer::Unit::Base
            include ::Sequencer::Mixin::Exchange::Folder
            include ::Sequencer::Mixin::ImportJob::ResourceLoop

            uses :ews_folder_ids, :import_job

            def process
              return if ews_folder_ids.blank?

              ews_folder_ids.each do |folder_id|
                folder = ews_folder.find(folder_id)
                paginated_item_sequence(folder)
              end
            end

            private

            def paginated_item_sequence(folder)

              sequence_name = 'Import::Exchange::FolderContact'

              default_params = {
                dry_run:    import_job.dry_run,
                import_job: import_job,
              }

              total    = folder.total_count
              per_page = 1000
              pages    = (total.to_f / per_page.to_f).ceil

              display_path = ews_folder.display_path(folder)
              (1..pages).each do |page|

                offset = (page - 1) * per_page

                opts = {
                  indexed_page_item_view: {
                    max_entries_returned: per_page,
                    offset:               offset,
                    base_point:           'Beginning'
                  }
                }

                logger.debug "Fetching and processing #{per_page} items (page: #{page}, offset: #{offset}) from Exchange folder '#{display_path}' (total: #{total})"

                folder.items(opts).each do |item|

                  logger.debug("Extracting attributes from Exchange item: #{item.get_all_properties!.inspect}")

                  resource_params = {
                    resource:        ::Import::Exchange::ItemAttributes.extract(item),
                    ews_folder_name: display_path,
                  }

                  resource_params[:resource] = resource_params[:resource].with_indifferent_access

                  sub_sequence(sequence_name,
                               parameters: default_params.merge(resource_params))
                end

                # store possible unsaved values in result e.g. statistics
                import_job.save!
              end
            end
          end
        end
      end
    end
  end
end

ImportJob.dry_run(name: 'Import::Exchange', payload: ImportJob.last.payload, delay: false)

p ImportJob.last.result
```

**Comment by gitbit12665** [comment]
**New Output:**

> {"sum"=>1900, "Meine Kontakte"=>{"sum"=>1900}, "created"=>1900, "updated"=>0, "unchanged"=>0, "skipped"=>0, "failed"=>0, "folders"=>{"Meine Kontakte"=>{"created"=>1900, "updated"=>0, "unchanged"=>0, "skipped"=>0, "failed"=>0}}}

**Comment by thorsteneckel** [comment]
Nice! Looks good. I'll merge the fix with develop then. Unfortunately there will be no backport to Zammad 2.2. So in the meantime you can use this reworked [sub_sequence.rb.zip](https://github.com/zammad/zammad/files/1618903/sub_sequence.rb.zip)
 and add it to your system as done before.
The previous version did not work properly because there were to many changes between 2.2 and the current develop state. This one will work now.

Thanks a lot for your help! Closing now. 🚀

**Comment by gitbit12665** [comment]
Thank you!
