### ISSUE TITLE
Article creation does not work with REST

### ISSUE THREAD

**Issue by osieben** [zammad/zammad#1743]
Hi, using Zammad 2.2.0 API

my aim is to generate an Article for a Ticket. Using the Ruby API, that works fine. I load the Ticket, create ticket from that, fill in data, and there is my Article attached to the Ticket. 

```
ticket = client.ticket.find(6)

article = ticket.article(
  type: 'note',
  subject: 'some subject 2',
  body: 'Yuhuu',
  content_type: 'text/html', # optional, default is text/plain
  internal: true
)
```

Now trying this with the RESTful API in Python I dont get it to work. Here is a python test snippet: 

```
endpoint = '/ticket_articles/by_ticket/6'
response = requests.get(urlbase + endpoint, headers=head)
print (response)

endpoint = '/ticket_articles'
article = {
    'ticket_id':6,
    "type": "note",
    "internal": "true",
    "content_type": "text/html",
    "subject": "Test",
    "body": "Test"
}
json_article = json.dumps(article)
print (json_article)

response = requests.post(urlbase + endpoint, data=json_article, headers=head)
print (response.text)
```
When I load Ticket 6 that shows up. But when I try to create the new article for it, it complains with 
"ERROR: Could not find Ticket with Id=".
Obviously it does not recognize the given ticket id.

Transforming this to a CURL requests, executes, but does not generate any article at all.
```
/curl 
-u user:pass 
-H "Content-Type: application/json" 
-X post 
-d '{"ticket_id": 6, "type": "note", "internal": "true", "content_type": "text/html", "subject": "Test", "body": "Test"}' 
http://localhost:3000/api/v1/ticket_articles
```

Is this a bug or am I doing something wrong?
Cheers,
Oliver

**Comment by thorsteneckel** [comment]
Hi please ask technical questions over in our forum at https://community.zammad.org/ - and please provide your `log/production.log` (or test/development - depending on how you started your server) file.
