### ISSUE TITLE
Search is limited to 50 results

### ISSUE THREAD

**Issue by sthag** [zammad/zammad#1744]
### Infos:

* Used Zammad version: 2.2
* Installation method (source, package, ..): package
* Operating system: Windows, Linux
* Database + version: ?
* Elasticsearch version: 5.6.5
* Browser + version: Chrome 63

### Expected behavior:

* I do a text search for example `title:"xyz"`
* There are hundreds of tickets with the query
* The search result page gives all the tickets matching the query

### Actual behavior:

* I do a text search for example `title:"xyz"`
* There are hundreds of tickets with the query
* The search result page gives only 50 results, even if there are more

### Steps to reproduce the behavior:

* Do a status search for example `state:open`

### Steps to **not** reproduce the behavior:

* I use some other way, like the automation option
* I give the query as a condition
* The preview count shows the total number of results

Yes I'm quite sure this is a bug and no feature request or a general question.

**Comment by sthag** [comment]
Also there is a discrepancy between the API search and the frontend result and a overview setup i did to get the total result:

If I use `curl -s -k -H "Accept: application/json" -H "Authorization: Token token=TOKEN_HERE" https://IP_HERE/api/v1/tickets/search?query=title:QUERY_HERE` I get 12 results.

If I use the frontend search `title:QUERY_HERE` I get 50 capped results.

If I make a new overview with a condition `title contains QUERY_HERE` I get 933 results, which I guess is the total amount.

**Comment by MamoulianDelacroix** [comment]
@sthag : maybe this helps #1458

**Comment by sthag** [comment]
@MamoulianDelacroix Thanks for the link but it only addresses the way to use the API correctly.

The main problem is that the search from the UI does not reflect the total results. But this only stands out if compared to the results form the overviews.
There is no pagination for the results. There is no total amount. There is nothing which reflects that the search has more results than shown.

**Comment by thorsteneckel** [comment]
Hi @sthag - we worked on the paging of search results and increased the number of per page to 200

https://github.com/zammad/zammad/blob/cf1626494047f27d8fe094a7b954e04fef0f182b/app/controllers/tickets_controller.rb#L428-L435

Does this work for you? If not: What's your issue?

**Comment by martini** [comment]
Probably even better. With Zammad 2.5 we also support offsets with pagination in search results. That means for example you can search for `title:"xyz"` and get page 2000 with per page of 200 tickets.

See also https://github.com/zammad/zammad/issues/1951

**Comment by thorsteneckel** [comment]
No feedback so I assume this is either fixed or lost relevance due to the new functionality in Zammad 2.5. Closing now.

**Comment by InsaneSplash** [comment]
I seem to still be having this issue even with the latest version of zammad. I checked the above code and it is set to show 200 per page, however there is no pagination and is limited to 50?

![image](https://user-images.githubusercontent.com/16985649/64763576-9707ba00-d540-11e9-9924-0e8c4fe17152.png)

**Comment by MrGeneration** [comment]
I'll limit the conversation on this issue so that we're not having duplicate conversations on duplicates. :-)
