### ISSUE TITLE
admin/agent is not receiving new open issue notifications

### ISSUE THREAD

**Issue by sandrodz** [zammad/zammad#1747]
### Infos:

* Used Zammad version: 2.2.x
* Installation method (source, package, ..): docker container (https://github.com/zammad/zammad-docker-compose)

### Expected behavior:

* When a new ticket is created, agent/admin should be notified

### Actual behavior:

* No notification is dispatched

Yes I'm sure this is a bug and no feature request or a general question.

![screen shot 2018-01-12 at 9 37 59 pm](https://user-images.githubusercontent.com/8479569/34887915-a99a0ae4-f7e1-11e7-818b-5639af5c56ca.png)

**Comment by muhammadn** [comment]
Hi @sandrodz 

Could you run `docker ps` and show it's output?

**Comment by sandrodz** [comment]
@muhammadn sure, here you go:

<img width="1452" alt="screen shot 2018-01-14 at 7 13 00 pm" src="https://user-images.githubusercontent.com/8479569/34917377-f3d6ef7c-f95e-11e7-8c27-97109502547d.png">

**Comment by monotek** [comment]
Are you talking about mail notification?
Do you have a smtp account configured?

**Comment by sandrodz** [comment]
@monotek yes I'm talking about new ticket mail notification to agents. All other type of notifications are dispatched correctly. Customers receive all mails correctly e.g. smtp account is configured correctly.

**Comment by monotek** [comment]
did you already checked the production.log for errors?

**Comment by sandrodz** [comment]
I've scoured `docker-compose logs -f` for each container but couldn't find where mail notifications are logged. Can you tell me which container might have production.log?

**Comment by sandrodz** [comment]
okay, found this at `sudo docker exec -it zammadkubikthemescom_zammad-railsserver_1 cat /opt/zammad/log/production.log`

<img width="1578" alt="screen shot 2018-01-16 at 10 42 04 am" src="https://user-images.githubusercontent.com/8479569/34975151-ecabbde4-faa9-11e7-962c-de016a7d448d.png">

Logs say notification sent, but I cannot find corresponding log in my mail server, actually it seems mail server never got anything from that address.

**Comment by sandrodz** [comment]
It was spark post issue, sorry guys for wasting your time.

`554 5.7.1 – Recipient address was suppressed due to customer policy`

https://www.sparkpost.com/docs/faq/recipient-address-was-suppressed-due-to-customer-policy/
