### ISSUE TITLE
Zammad rake aborted Elasticsearch index will not build

### ISSUE THREAD

**Issue by antboll** [zammad/zammad#1750]
We had some trouble to get the elasticsearchservice started after a reboot, due to the open JDK VM Processor Problem. After fixing this we want to create a new index, because it is not possible to search for Tickets or create reports. So we type:zammad run rake searchindex:rebuild --trace`

We get the following error:

    create indexes...
    rake aborted!
    Unable to process PUT at http://localhost:9200/_ingest/pipeline/zammad-attachment
    #<UserAgent::Result:0x005606521a74b8 @Success=false, @Body=nil, @DaTa=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">
    /opt/zammad/lib/search_index_backend.rb:95:in block (2 levels) in processors' /opt/zammad/lib/search_index_backend.rb:62:ineach'
    /opt/zammad/lib/search_index_backend.rb:62:in block in processors' /opt/zammad/lib/search_index_backend.rb:59:ineach'
    /opt/zammad/lib/search_index_backend.rb:59:in processors' /opt/zammad/lib/tasks/search_index_es.rake:68:inblock (2 levels) in <top (required)>'
    ...........
   
`curl http://localhost:9200`
shows the following

> {
  "name" : "fthmWhb",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "sqj3B91DT6ujXjnubp7dgw",
  "version" : {
    "number" : "5.6.5",
    "build_hash" : "6a37571",
    "build_date" : "2017-12-04T07:50:10.466Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
 Can anyone help?

**Comment by thorsteneckel** [comment]
This is not a Zammad issue. Ask questions over at https://community.zammad.org/
