### ISSUE TITLE
Search doesnt work after Update to 2.2.x

### ISSUE THREAD

**Issue by PatrickGoenner** [zammad/zammad#1754]
After Updating Zammad on Debian OS to version 2.2.x, search does not longer work:

StatusCode: 500

{"error":"Unable to process POST at http://localhost:9200/zammad_production/Ticket/_search\n#\u003cUserAgent::Result:0x007f4c782b7228 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error=\"#\u003cErrno::ECONNREFUSED: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for \\\"localhost\\\" port 9200)\u003e\"\u003e"}

Please give me the needed steps to bind port 9200.

Regards
Patrick

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.
