### ISSUE TITLE
Notification How Disappear 

### ISSUE THREAD

**Issue by antikilahdjs** [zammad/zammad#1757]
Hi there - thanks for filing an issue. Please ensure the following things before creating an issue - thank you! 🤓

Since november 15th we handle all requests, except real bugs, at our community board.
Full explanation: https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21

Please post:
- Feature requests
- Development questions
- Technical questions

on the board -> https://community.zammad.org !

If you think you hit a bug, please continue:
- Search existing issues and the CHANGELOG.md for your issue - there might be a solution already
- Make sure to use the latest version of Zammad if possible
- Add the `log/production.log` file from your system. Attention: Make sure no confidential data is in it!
- Please write the issue in english
- Don't remove the template - otherwise we will close the issue without further comments
- Ask questions about Zammad configuration and usage at our mailinglist. See: https://zammad.org/participate

Note: We always do our best. Unfortunately, sometimes there are too many requests and we can't handle everything at once. If you want to prioritize/escalate your issue, you can do so by means of a support contract (see https://zammad.com/pricing#selfhosted).

* The upper textblock will be removed automatically when you submit your issue *
-->

### Infos:

* Used Zammad version: 2.2.x
* Installation method (source, package, ..): source rhel
* Operating system: centos 7
* Database + version: from source latest
* Elasticsearch version: 6.x
* Browser + version: chrome latest

### Expected behavior:

*

### Actual behavior:

Hello everyone, I have some problems with zammad. I already create 2 users to example , both was include in the same group , when I send a email to my address ticket...@mas.com.br .... I received perfect in notification but, when I get the ticket and assign to me for another user the notification ( badge ) not disappear , someone can help me or it is possible the function works ? I want to when someone get the ticket , all tickets can be removed from another . 
Sorry for my bad English. 
![4](https://user-images.githubusercontent.com/33559260/35125422-8caaf728-fc77-11e7-92fa-4d7fa5bdc039.PNG)
![33](https://user-images.githubusercontent.com/33559260/35125475-bcb74b06-fc77-11e7-98f2-ec891e639e83.PNG)
<!--

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
First of all: I suggest downgrading your elasticsearch from 6.x to 5.6.6, since it constantly throws errors and highers the system load (what you don't want because it delays other things :) )

I could verify this behaviour - it only happens if you change the responsibility to some one else **without** opening / reading the ticket. The notification disappears when the ticket gets closed, read by you or when you simply click on "mark all notifications read"

![image](https://user-images.githubusercontent.com/6549061/35268233-d79928d6-0028-11e8-8fcc-899a6e28e223.png)

Still, I too see this as a (small) bug - not sure if everyone works like both of us. Initially I never noticed.

**Comment by antikilahdjs** [comment]
Hello dear, 

I appreciate your help . Thank you so much I will try upgrade or install again .

**Comment by MrGeneration** [comment]
@antikilahdjs  no problem (regarding elasticsearch) - but the notification issue consists even with 5.6.6 in my opinion.

If your system already is productive, you can uninstall elasticsearch with ignoring / breaking dependencies and just reinstall elasticsearch with the correct version. Reboot may be required.
