### ISSUE TITLE
MySQL error during fetching IMAP

### ISSUE THREAD

**Issue by sthag** [zammad/zammad#1759]
### Infos:

* Used Zammad version: 2.2
* Installation method (source, package, ..): package
* Operating system: Ubuntu
* Database + version: ?
* Elasticsearch version: 5.6.5
* Browser + version: Chrome 63

### Expected behavior:

* Email can be processed

### Actual behavior:

* Certain emails don't show up in Zammad but get stuck in unprocessable_mail
* [email-error.log](https://github.com/zammad/zammad/files/1646173/email-error.log) from production.log
```
ERROR -- : Mysql2::Error: MySQL client is not connected: ROLLBACK (ActiveRecord::StatementInvalid)
...
ERROR -- : Can't use Channel::Driver::Imap: #<ActiveRecord::StatementInvalid: Mysql2::Error: MySQL client is not connected: BEGIN>
```

### Steps to reproduce the behavior:

* Certain emails with attachments around 5 to 15 MB trigger the error
* Others don't
* It only happens with attachements

Yes I'm sure this is a bug and no feature request or a general question. The error log told me to report it.

**Comment by sthag** [comment]
This problem was caused by the MySQL configuration `/etc/mysql/mysql.conf.d/mysqld.cnf`.
The value for the configuration entry `max_allowed_packet` was too low.

May I suggest that there is some kind of note during the installation documentation to be aware of such configurations?

**Comment by sthag** [comment]
I also want to add something else considering the documentation.
There is a setting in Zammad Admin > Channel, Email > Settings > Maximum Email Size
This setting only works for **outgoing** email. I found this by stumbling over the issue #1534.
I think it would be good to clarify this for the documentation.

**Comment by martini** [comment]
@sthag With Zammad 2.5 we added an check at boot up time if mysql max_allowed_packet setting is correct. Thanks for your hint! :)

**Comment by olivergrahl** [comment]
It would have been helpful to have this new prerequisite in the docs (max_allowed_packet needs to be 4M, 64M recommended)

**Comment by thorsteneckel** [comment]
@olivergrahl - We'd love to see a pull request for this improvement 😍
