### ISSUE TITLE
Zammad page redirection

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#1760]
### Infos:
- Zammad version: v2.2
- Centos 7
-Web server: Apache/2.4.6 (CentOS) 

Hi,
Im trying to redirect login page (#login) of zammad to another external login page but not successful so far. I thought I may need to apply some changes within the code and not within the Apache config file.

-->

### Expected behavior:
When I use apache config and tried with following parameters to redirect login page to another external login page, it's expected to redirect https://*/#login to https://external/login.html.

### Actual behavior:
Redirection doesnt work... the #login page always show up.

### Steps to reproduce the behavior:
Apache Config:

1.
    DocumentRoot "/opt/zammad/public"
    RewriteEngine On
    RewriteRule ^login    https://login.test.com/ [L]
2.
    RewriteEngine On
    Redirect ^/#login   https://login.test.com/

Thanks,

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.
