### ISSUE TITLE
Missing support of multiple ticket attribute selectors for ElasticSearch query

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1761]
### Infos:

* Used Zammad version: 2.2
* Installation method (source, package, ..): package
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* All available operators of ticket attribute selectors (like e.g. `within last (relative)`, `before (absolute)` etc. should be supported for ElasticSearch queries.

### Actual behavior:

* Only a limited subset of attribute selectors is supported: 
- `is`
- `is not`
- `contains`
- `contains not`

see: https://github.com/zammad/zammad/blob/develop/lib/search_index_backend.rb#L453

This affects any screen where ticket attributes can be selected.

### Steps to reproduce the behavior:

Create a report with `ticket.created_at` and the selector `within last (relative)` 3 days.

```
E, [2018-01-19T09:09:20.899280 #660] ERROR -- : unknown operator 'within last (relative)' for ticket.created_at (RuntimeError)
/opt/zammad/lib/search_index_backend.rb:464:in `block in selector2query'
/opt/zammad/lib/search_index_backend.rb:445:in `each'
/opt/zammad/lib/search_index_backend.rb:445:in `selector2query'
/opt/zammad/lib/search_index_backend.rb:405:in `selectors'
/opt/zammad/lib/report/ticket_generic_time.rb:37:in `aggs'
/opt/zammad/app/controllers/reports_controller.rb:36:in `block in generate'
/opt/zammad/app/controllers/reports_controller.rb:28:in `each'
/opt/zammad/app/controllers/reports_controller.rb:28:in `generate'
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
@thorsteneckel `selector2query` method is actually a report using normal SQL database (not elasticsearch) 😬

What i did in the Report Profile is to create a new profile with the steps mentioned but i couldn't get to reproduce it as it is not available for `created_at`

<img width="660" alt="screen shot 2018-01-25 at 10 53 32 pm" src="https://user-images.githubusercontent.com/3349747/35394499-e0f3014e-0222-11e8-8e36-f8c2ec2d4bcf.png">

**Comment by thorsteneckel** [comment]
👍 Let's skip this for now and talk about it after my vacation

**Comment by muhammadn** [comment]
Had a discussion earlier and that we concluded that we can only have basic reports for now but for advanced reporting we will be using Grafana.

**Comment by monotek** [comment]
Imho Grafana will not work until https://github.com/zammad/zammad/issues/688 is solved.
