### ISSUE TITLE
suggestion to improve scheduler view

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1765]
Hihi 👋 ,

I was taking a second look at our scheduled jobs when I came across this.
In the trigger's condition overview it just showd 3 days, but in reality it was 30 days. The '0' from '30' wouldn't not be displayed
![screenshot_2](https://user-images.githubusercontent.com/4436931/35207713-c790102e-ff44-11e7-9175-1cf1f9f030b5.jpg)

Greetings

**Comment by mrflix** [comment]
Hey @MamoulianDelacroix 👋,

thanks for reporting the issue! I just fixed it in the current develop branch. If you have the environment and time for it please test it 🤓
