### ISSUE TITLE
Ticket shown multiple times in overview

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#1769]
### Infos:

* Used Zammad version: 2.2.x
* Installation method (source, package, ..): package
* Operating system: ubuntu 16.4.2
* Database + version: MySQL 5.6.17
* Elasticsearch version:
* Browser + version: Chrome + Firefox

### Expected behavior:

* Tickets only shown once in an overview

### Actual behavior:

* Tickets shown multiple times, if the overview contains condition "email to" used with "@yourdomain.com", depending on how many mails have been sent to this ticket with a matching to field

### Steps to reproduce the behavior:
* create an overview with condition email "to" and value "@yourdomain.com"
* write an email to "ticket@yourdomain.com" to create a new ticket. remember the ticketnumber
* write a new email to "ticket@yourdomain.com" to this ticketnumber to append to the last ticket.
* open created overview. the ticket is shown twice
* if you write more emails to "ticket@yourdomain.com" and the ticketnumber the ticket is shown more often.

![image](https://user-images.githubusercontent.com/9305993/35275940-b4af3978-0041-11e8-996f-7a3ba97c1492.png)

If you have a already filled ticketsystem, you can see this even in preview of overview-creation:

![image](https://user-images.githubusercontent.com/9305993/35276035-27fbe6b0-0042-11e8-8b2b-594fab395465.png)

Greetings tobibe

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Hi @tobibe ,
thank you very much for your report! This bug should be fixed now in develop branch. 

Maybe you have time to test and check if it works for you ;-) Would be glad about feedback.

Best regards,
Rolf
