### ISSUE TITLE
Owner reset after group selection

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#1770]
### Infos:
* Used Zammad version: 2.2.x
* Installation method (source, package, ..): package
* Operating system: ubuntu 16.4.2
* Database + version: MySQL 5.6.17
* Elasticsearch version:
* Browser + version: Chrome + Firefox

### Expected behavior:
* Change group of ticket doesn't change selected owner

### Actual behavior:
* if you change the owner and afterwards the group of ticket, the owner switches back

### Steps to reproduce the behavior:
* change owner of ticket without submitting the changes
* changes group of ticket
* now the owner of ticket is resetted to state of previous owner

![reset_owner](https://user-images.githubusercontent.com/9305993/35276309-513e8824-0043-11e8-9d13-d0fdfc3b73f6.gif)

Greetings tobibe

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Fixed with the merged PR. Thanks @mantas !
