### ISSUE TITLE
unprocessable_mail

### ISSUE THREAD

**Issue by Wisou** [zammad/zammad#1772]
### Infos:

* Used Zammad version: 2.2
* Installation method (source, package, ..): package Deb
* Operating system: Debian
* Database + version: psql + 9.4.15

### Expected behavior:

Hi,

We have some mails errors in /opt/zammad/tmp/unprocessable_mail

> -rw-r--r-- 1 zammad zammad 791173 déc.   6 11:49 227c339f4b59df90c0e44403e7c830da.eml
-rw-r--r-- 1 zammad zammad 531635 déc.   5 19:11 31964f1fd8bc219b2889cf4ec015c75c.eml
-rw-r--r-- 1 zammad zammad 886933 janv. 19 13:11 35655be35c8ee749f505dd18fef43bda.eml
-rw-r--r-- 1 zammad zammad  56066 déc.  12 10:51 67cdd9f70b437b2e4d4e51fffe069514.eml
-rw-r--r-- 1 zammad zammad 821786 déc.   6 17:37 7caf54289fd01240c661caf16020ad11.eml
-rw-r--r-- 1 zammad zammad 788808 nov.  15 14:51 87ad4b52c7df483f772627a14207d18e.eml
-rw-r--r-- 1 zammad zammad 927496 janv. 23 10:17 ebf5f125aae5070f8905b9976199c1f7.eml
-rw-r--r-- 1 zammad zammad 571859 janv. 12 12:16 f3d69bb67da0efc24328f4f1ff4d2e0f.eml

For exemple, ebf5f125aae5070f8905b9976199c1f7.eml is a customer mail.

Can you try to explain the reason ?

I can send to you in a PM the eml

BR,

Wisou

**Comment by jepf** [comment]
Hi @Wisou 
Thank you for reporting this issue.

Could you please send some of the unprocessed e-mails (as eml files) to support@zammad.com and also include your Zammad production log file (you can find this in the Zammad directory under log/production.log)?

Thank you.

**Comment by thorsteneckel** [comment]
No feedback provided. Closing. Feel free to leave feedback.
