### ISSUE TITLE
New Login from new device 127.0.0.1

### ISSUE THREAD

**Issue by GrexAut** [zammad/zammad#1774]
Hi,

I'm using clean install Ubuntu 16.04.03 LTS with Zammad 2.2.x

I'm getting following mail (german):
Subject: "Zammad Helpdesk Anmeldung erfast von einem neuen Gerät"
Message: 

> Hallo Gregor,
> 
> es sieht aus, als ob Du Dich mit einem neuen Gerät um "2018-01-23 15:16:46 UTC" angemeldet hast:
> 
> Dein Gerät: Windows, Firefox
> Deine Lokation (relativ): unknown
> Deine IP: 127.0.0.1
> 
> Das Gerät wurde in die Liste der bekannten Geräte hinzugefügt, diese Liste kannst Du hier einsehen:
> 
> http://zammad/#profile/devices
> 
> Wenn dies nicht Du warst, entferne das Gerät aus der Liste, ändere Dein Account-Passwort und kontaktieren Deinen Administrator. Jemand könnte unberechtigten Zugriff auf Dein Konto bekommen haben.
> 
> Dein Zammad Helpdesk Team

Yes I'm using Windows, Firefox but the is not correct and there are not new devices!

I got the mails at:
14:16
14:46
15:17
15:47
16:17

I checked the syslog, at this times, there are running the hourly crons:
`cd / && run-parts --report /etc/cron.hourly`

**Comment by monotek** [comment]
Closed as issue template is ignored.
