### ISSUE TITLE
Past HTML Format E-mails

### ISSUE THREAD

**Issue by antikilahdjs** [zammad/zammad#1779]
### Infos:

* Used Zammad version: 2.2.x (Latest)
* Installation method (source, package, ..): Repo Centos 7
* Operating system: Centos 7
* Database + version: PostGreSQL
* Elasticsearch version: 5.6.6
* Browser + version: Chrome Latest , Firefox tested on Edge too

### Expected behavior:

Past HTML contents to open or reply a ticket

### Actual behavior:

HTML doens't work .

### Steps to reproduce the behavior:

When I try copy html contents from any website and I try past into the tickets to reply or open the new ticket it doesn't work . I guess the Zammad works only *text . I am work with travel tickets quote . I need put some information to send to my customers because have many information about travel, location, time date etc ... it is possible change this in zammad or this feature not exist ? Sorry about my worst English.

In my case too the signatures not work , I try put images on my signatures but I not have success.

![capture](https://user-images.githubusercontent.com/33559260/35412851-97de1b88-01eb-11e8-85d2-b3e096770311.PNG)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @antikilahdjs 

can you add the source documents/urls from the content what you past into Zammad? I want to reproduce it.

Thanks,
 -Martin

**Comment by antikilahdjs** [comment]
Hi @martini , thank you for your quick response. 

In an attach I save the *eml format and inside on the message body has the content . When I copy and past on outlook all perfect but in Zammad not work this html format .
I put the file on link below because here in git not accept the eml .

https://cloud.mascarotour.com.br/index.php/s/BR6Jw2X4EDJRUUd


I will appreciate if you have a solution . Tks

**Comment by antikilahdjs** [comment]
Hi @martini , you have something about that? It is possible the feature into Zammad is be great because a lot of company travel have html when anyone buy a fly ticket and in my company use a lot copy and past to send their customers . Thank and I am so sorry about my English

**Comment by antikilahdjs** [comment]
Hi @martini , 
Don't be sorry I appreciate the quick response . I already update right now but not work . I will wait for the next release maybe the Developer Team include this feature in next time . Thank you so much .

**Comment by martini** [comment]
Pls provide me your example email again. Thanks!

**Comment by antikilahdjs** [comment]
Can you download the content? The link is https://cloud.mascarotour.com.br/cloud/index.php/s/wZGRC495csZ4Jb4 , because here I can't upload eml or msg files. Thanks @martini

**Comment by thorsteneckel** [comment]
Sorry to say @antikilahdjs but the email/file is gone again. Please just zip the file and upload it here. Github allows `.zip` files 👍

**Comment by thorsteneckel** [comment]
No feedback in a month. Closing now. Feel free to provide the `.zip` file as a Github upload and I'll reopen the issue. Thanks!
