### ISSUE TITLE
Feature request: Multiple selection of same condition

### ISSUE THREAD

**Issue by semaf** [zammad/zammad#1780]
Using the same condition more than one time is not possible. If I want to setup a rule with 5 titles and all other should be ignored, is the title in the second time disabled.

![bildschirmfoto 2018-01-25 um 22 58 30](https://user-images.githubusercontent.com/8831145/35414730-9cb86b94-0223-11e8-847e-2763b1f75b59.png)

**Comment by thorsteneckel** [comment]
Use our issue template as described in the intro text. Closing until then.
