### ISSUE TITLE
Problem auto assignment domains to organisation

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1785]
Hihi 👋 

we are using the zammad-version 2.2.0-1516200812.db19f309.xenial right now and have a problem with the auto assignment from user to organisations via domain.
Most of the time, the problem appears when we receive from Office 365 addresses.
When I pipe an email directly into zammad via shell, everything is fine, even from office365 addresses.

Greetings

**Comment by monotek** [comment]
issue template ignored. closed.
