### ISSUE TITLE
Entering customer ("Kunde *") field not auto-completed, error: "Invalid email of customer"

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1787]
I just upgraded to Zammad 2.3
```
# apt policy zammad|head

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

zammad:
  Installed: 2.3.0-1517273354.ea50d0c0.xenial
  Candidate: 2.3.0-1517273354.ea50d0c0.xenial
  Version table:
 *** 2.3.0-1517273354.ea50d0c0.xenial 500
        500 https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu 16.04/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.0-1516639692.dfa8f805.xenial 500
        500 https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu 16.04/main amd64 Packages
     2.2.0-1516200812.db19f309.xenial 500
```
but when I try to enter the first Customer ("Kunde *") field, the name is not auto-completed (it was auto-completed in the prior version 2.2) and I get `Invalid email of customer`. Entering an email address works. Has this changed or is this a bug?

**Comment by dominicpratt** [comment]
We got the same problem over here and it's pretty annoying.

We're unable to search customers and have to pick out the mail address by hand...

**Comment by muhammadn** [comment]
@passboltUser We need the information about your actual, expected results and there is a note for you to fill up the information when creating a new issue and it is very useful for us.

Anyway, if #1522 is the same problem as what you are encountering. yes, this is fixed very recently. 

So closing since there information weren't filled.

**Comment by passboltUser** [comment]
Yes, it's the same issue (I expected to auto-complete username but also when manually typed in it didn't work). Works now with latest Zammad version (we disabled Elastic because our search wasn't working and we don't need Elastic anyway, and if Elastic isn't used to search users within Zammad, then it has indeed been fixed with the latest Zammad release).

**Comment by martini** [comment]
@passboltUser so you hat elasticsearch issue after updating Zammad (it's not clear to me, so I'm asking)? And if yes, what version of elasticsearch did you use?

**Comment by passboltUser** [comment]
Since then there were Zammad2 several updates available via `apt upgrade` and after each time I do the upgrade, the search is not working and I have to manually do `zammad run rails r "Setting.set('es_url', '')"`.
Status of elasticsearch is: 
```
$ systemctl status elasticsearch.service 
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-03-14 11:12:50 CET; 5 days ago
     Docs: http://www.elastic.co
 Main PID: 15586 (code=exited, status=1/FAILURE)
```
So it's kinda not running, but still there and maybe interfering to that I always have to run `zammad run rails r "Setting.set('es_url', '')"` after each `apt upgrade`?

My elasticsearch version is:
```
$ apt policy elasticsearch
elasticsearch:
  Installed: 5.6.7
  Candidate: 5.6.7
  Version table:
 *** 5.6.7 100
        100 /var/lib/dpkg/status
     1.7.3+dfsg-3 500
        500 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages.
```
