### ISSUE TITLE
zammad_backup.sh/zammad_restore.sh doesn't work without bash explicitly in /bin/bash

### ISSUE THREAD

**Issue by MacLemon** [zammad/zammad#1793]
### Infos:

* Used Zammad version: 2.2.0 (Yes, I checked the release notes for the just released versions [2.2.1](https://github.com/zammad/zammad/blob/2.2.1/CHANGELOG.md) and [2.3](https://github.com/zammad/zammad/blob/stable/CHANGELOG.md) as well.)
* Installation method (source, package, ..): source
* Operating system: FreeBSD 11.1p6
* Database + version: PostGreSQL 10.1
* Elasticsearch version: n/a (not in use yet)
* Browser + version: n/a irrelevant, doesn't affect GUI

### Expected behavior:
Following the documentation for [Backup and Restore](https://docs.zammad.org/en/latest/appendix-backup-and-restore.html#backup-and-restore)
* starting `${ZAMMAD_DIR}/contrib/backup/zammad_backup.sh` should actually backup files and database provided the `config` has been edited correctly.

### Actual behavior:
* Script cannot be launched. FreeBSD, OpenBSD, or any BSD, doesn't come with `bash`. (macOS being the notable exception confirming the rule.)
* Even if you install `bash` from a package, or source, on these systems, it will reside in `/usr/bin/bash` causing the script to fail as well.

### Steps to reproduce the behavior:
* `cd ${ZAMMAD_DIR}/contrib/backup`
* `./zammad_backup.sh`

Yes I'm sure this is a bug and no feature request or a general question.

This is *why* I consider this a bug and not a feature request:
Zammad claims to be working on and *being tested* on FreeBSD, OpenBSD, Solaris, etc. in the third sentence of [Docs » Zammad](https://docs.zammad.org/en/latest/about-zammad.html#zammad).
While Zammad does work really fine on FreeBSD \o/, the backup script doesn't. <strike>I consider a vendor provided and supported backup script an essential part of the system and therefore it should be included in the test.</strike> (Yeah, `contrib` I know.)

Ugly Workaround:
Install bash from package or source.
Manually patch `zammad_backup.sh`, `functions` and `zammad_restore.sh` shebang to #!/usr/local/bin/bash.

Problems with this workaround:
- This workaround will be reverse when updating Zammad, requiring a new manual patch.
- In case you really need a restore, you must first patch `zammad_restore.sh` before you can actually restore your system. (Increasing downtime, causing hairpulling, etc.)

Suggested solution for POSIX systems: (The ones Zammad supports.)
Port `zammad_backup.sh`, `functions` and `zammad_restore.sh` to `/bin/sh` which actually *is* in `/bin/sh` on all POSIX compliant UNIX™(-like) systems. That would solve this issue for any *BSD and Linux without having to maintain multiple backup scripts in the future.

**Comment by monotek** [comment]
Sorry, not a bsd user.

Would "#!/usr/bin/env bash" work too?

**Comment by monotek** [comment]
Maybe ruby rewrite of the script would make more sense than switching to sh...

**Comment by MacLemon** [comment]
> Would "#!/usr/bin/env bash" work too?
That would fix the shebang issue on BSD.

> ruby rewrite of the script
Interesting idea, and I can see where it's originating from.
I see the issue from a sysadmin point of view and ruby certainly is unusual for system- and backup-tasks. Ruby is slow to start, depends on ruby being present and compatible and most likely requires working gems, etc. Worst case, a ruby backup script that requires a different set or superset of the ruby/gem requirements of Zammad itself.

These are things sysadmins like to avoid. `/bin/sh` is everywhere, it's compatible and nothing else required.

**Comment by monotek** [comment]
As Zammad is written in Ruby i don't see a problem. If there would be dependencies to any GEMs we'd put them into the Gemfile. 

Performance wise most tasks would be system tools like tar anyway. Imho also no problem.

The advantage is see is that backup config could be done from the frontend which i think is a big plus.

**Comment by monotek** [comment]
In a first step i changed the shebang: https://github.com/zammad/zammad/commit/228b800df98f0310ed2a513259e494c2e91c3494

**Comment by MacLemon** [comment]
> The advantage is see is that backup config could be done from the frontend which i think is a big plus.

I agree, that would be a plus. Though, no more than setting a file system destination should be necessary to have it autobackup then.
Using tar should certainly make sure it works with BSD tar *and* GNU tar though. :-)


Given that the current backup script doesn't even correctly parse the database connection from `database.yml` I'm pondering if it's even worth to file further bugs against it.

**Comment by monotek** [comment]
> Given that the current backup script doesn't even correctly parse the database connection from database.yml I'm pondering if it's even worth to file further bugs against it.

Could you give some more info please? Whats the error message?

**Comment by MacLemon** [comment]
It doesn't even have a line to parse a host, and always tries to connect as role postgres over a local unix socket instead of actually using the same connection that Zammad uses. Should I file a separate bug for that?

**Comment by monotek** [comment]
True. The backup scripts expects that the deb or rpm packages are used and that's the way how the database is connected after installation.

Yes, please add another bugreport for this.

**Comment by mgruner** [comment]
The original issue was fixed long ago in https://github.com/zammad/zammad/commit/228b800df98f0310ed2a513259e494c2e91c3494, therefore I'll close this report now.
