### ISSUE TITLE
Admin users can be disabled by Agents

### ISSUE THREAD

**Issue by moellert** [zammad/zammad#1794]
### Infos:

* Used Zammad version:  2.3.0-1517421506.32f17a3f.centos7
* Installation method (source, package, ..): package
* Operating system: CentOS7
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* The agents are just allowed to edit customers. (Maybe not even that when the user informations come from an external source)

### Actual behavior:

* The agents are allowed to edit every user, it doesn't matter if the edited user is a customer, agent or admin.

### Steps to reproduce the behavior:

- Setup a system with some admins and agents.
- Login as agent user
- Search for one admin user
- Go to Action -> Edit
- Set the user as inaktiv and submit the change
- See what happens

This works also when you access the user editing via Ticket -> Customer -> Edit Customer

I don't think that this works as intended and this problem is a big showstopper for us.

My suggestion is that there are simply some checks missing.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
@moellert Thanks for reporting, we are working on a fix right now since this is a security issue. 👍

**Comment by muhammadn** [comment]
related to #1610
