### ISSUE TITLE
API: created_by and updated_by fields cannot be changed

### ISSUE THREAD

**Issue by sheLbyPL** [zammad/zammad#1797]
### Infos:

* Used Zammad version: 2.3.0
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04.3
* Database + version: MySQL
* Elasticsearch version: 5.6.7
* Browser + version: Chrome / doesn't matter

### Expected behavior:
When creating ticket by api (using php zammad api) it should show ticket created by customer (in activity stream, mails, slack notif)

### Actual behavior:

It shows created by Test User (user which account I'm using to login by api)

### Steps to reproduce the behavior:
Try it. 

My ticket data:

$ticket_data = [
    'group'       => 'Users',
    'priority_id' => 2,
    'state_id'    => 1,
    'type'    => $typen,
    'title'       => $title,
	'customer_id' => 'guess:'. $email,
	'created_by_id' => $user_id,
	'updated_by_id' => $user_id,
	'origin_by_id' => $user_id,
    'article'     => [
        'subject' => $title,
        'body'    => $message,
		'origin_by_id' => $user_id,
		'type'    => 'web',
		'customer'    => $user_login,
		'created_by'    => $user_login,
		'updated_by'    => $user_login,
		'from'    => $email,
		'to'    => $email,
		'internal'    => 'false',
    ],

];
All those variables ($email, $user_id $user_login) are customer related, none of them gets data from test user account.
As you can see I have already tried to change many fields, but it still adds it as test user.

If I'm doing something wrong please let me know, but I think $ticket_data is fine.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
@sheLbyPL I have followed the guidelines here:

https://docs.zammad.org/en/latest/api-intro.html#example-curl-requests-for-tickets-and-users

And created a new ticket (just changing the email:password and 'email_of_existing_customer@example.com')

It works fine on my end, the ticket is created with the customer's email.

To save yourself all the trouble. You can check out the Zammad API library in PHP:
https://github.com/zammad/zammad-api-client-php

For further questions, you are welcome to ask at https://community.zammad.com where there's a lot more people who can help you. 😊

**Comment by sheLbyPL** [comment]
Yes, ticket is created with customer email but look on the activity stream or email notifications. It shows created by "account that you used to login".

Tested just now on two zammad installations with the curl from the link that you sent, changing only email:password and customer email.

Still, I think it is a bug, please check it again.
