### ISSUE TITLE
Selecting of Organisation for new users is broken @ 2.3

### ISSUE THREAD

**Issue by minions1291** [zammad/zammad#1798]
### Infos:

* Used Zammad version: 2.3
* Installation method (source, package, ..): 
* Operating system: Ubuntu 16.04
* Database + version: -
* Elasticsearch version:-
* Browser + version:-

### Expected behavior:

* When adding a User over the Webinterface, I get an suggestion for the "Organisation" to select

### Actual behavior:

* I don't get the suggestion, I have to enter the Organization manually
It's also the same effect, when a Agent creates a ticket for an user -> not able to search for the Users.

### Steps to reproduce the behavior:

* Try to create a new user.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by moellert** [comment]
Hi, in my installation this works fine. Are you sure that elasticsearch works correctly?

systemctl status elasticsearch 

Should help you figuring it out.

**Comment by minions1291** [comment]
Hi, thanks for the reply
` elasticsearch.service - LSB: Starts elasticsearch
   Loaded: loaded (/etc/init.d/elasticsearch; bad; vendor preset: enabled)
   Active: active (exited) since Thu 2018-02-01 00:34:47 CET; 15h ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0
   Memory: 0B
      CPU: 0

Feb 01 00:34:47 zammad-prod systemd[1]: Starting LSB: Starts elasticsearch...
`
You are right, Elastic isn't working. Where do I get the logs from elastic? I don't find stuff in production.log.
Thanks

**Comment by minions1291** [comment]
Got the soution! It's a bug at ubuntu 16.04 (see https://discuss.elastic.co/t/cant-start-elasticsearch-with-ubuntu-16-04/48730)
How to fix it:

> It seems that to get Elasticsearch to run on 16.04 you have to set START_DAEMON to true on /etc/default/elasticsearch. It comes commented out by default, and uncommenting it makes Elasticsearch start again just fine.
(From the ES forum)
Then run:  
chown -R elasticsearch:elasticsearch /var/lib/elasticsearch/ 
systemctl restart elasticsearch.service

Thanks to  @moellert  for the hint!
