### ISSUE TITLE
Chat link in Ticket opening _blank 

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#1799]
Hi there,

if you open a link to an old chat from a ticket it will open in a new window. Should open in the sidebar because it kills the session when opening in a new tab/window.

**Comment by thorsteneckel** [comment]
HI @Julian0o - Please use the issue template you removed. It's really important for us maintainers to have the required information. I have to close this issue in the meantime. Feel free to update your post. I'll reopen the issue afterwards.
