### ISSUE TITLE
Zammad with NGINX reverse proxy stopped working

### ISSUE THREAD

**Issue by DwijadasDey** [zammad/zammad#1800]
### Infos:

* Used Zammad version: latest installed through rpm
* Installation method (source, package, ..): Yum
* Operating system: CentOS 7
* Database + version:  PostgreSQL 9.2.23
* Elasticsearch version: 5
* Browser + version: firefox 57

### Expected behavior:

* To show login page

### Actual behavior:

* Does not show the login page

### Steps to reproduce the behavior:

*

Hi
I have installed zammad/postgresql in CentOS 7 using yum. Zammad started in port 3000/6042. I had edited NGINX configuration file of zammad for reverse proxy and it did worked but could not configured the email in getting started process due to non availability of the email address.

Bit later, when i again tried to access zammad through one of the subdomain, i could not access it although configuration file remains same. I can curl to port 3000 from the terminal.

**$ curl 127.0.0.1:3000**

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=1024">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Zammad Helpdesk</title>
  <link rel="stylesheet" media="all" href="/assets/application-1a0959799295e3fb563b0ce3c74070aa62aea822861d2dd644bea5bfcdb03eff.css" />
  <link rel="stylesheet" media="print" href="/assets/application-print-dbdc6c8d9f24afd3a6e2a27237812c7f50f00687fbfde9f5cd93b4177ca488e3.css" />
  <script src="/assets/application-04376a8de33fb283c5d8898d690511057e239be22d450288056b2aa01e29f4bb.js" defer="defer"></script>
  <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="9mlTKyPN7M0/GTrHfSN8lKqaUNDztr16cGVGBzBM9lFg/TaZrnS79SS2AMDExQR7rHyxvmmJP2oBlAjnZ5dHgQ==" />
</head>
<body>

<!-- svgstore fallback -->
<script>
..............
..............
```

But could not access it through reverse proxy.
The NGINX configuration file is -

```
#
# this is the nginx config for zammad
#

upstream zammad-railsserver {
    server localhost:3000;
}

upstream zammad-websocket {
    server localhost:6042;
}

server {
    listen 80;

    # replace 'localhost' with your fqdn if you want to use zammad from remote
    server_name zammad.mydomain.org;

    root /opt/zammad/public;

    access_log /var/log/nginx/zammad.access.log;
    error_log  /var/log/nginx/zammad.error.log;

    client_max_body_size 50M;

    location ~ ^/(assets/|robots.txt|humans.txt|favicon.ico) {
        expires max;
    }

    location /ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_pass http://zammad-websocket;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
        proxy_pass http://zammad-railsserver;

        gzip on;
        gzip_types text/plain text/xml text/css image/svg+xml application/javascript application/x-javascript application/json application/xml;
        gzip_proxied any;
    }
}
```

Can anyone point out where could be the issue ?

**Comment by muhammadn** [comment]
@DwijadasDey Hi. Since this is more of a configuration question and not a bug/enhancement issue, i suggest that you can try out your question in the forum at https://community.zammad.org 

Feel free to open an issue if you have any bug reports but otherwise, the forum will be sufficient as there is more people to help you there on configuration. 😊

Closing this issue.
