### ISSUE TITLE
Viewpoint::EWS::EwsFolderNotFound during Exchange connection

### ISSUE THREAD

**Issue by rbq** [zammad/zammad#1802]
Hi there!

I'm trying to set up an Exchange (2010) connection. After entering my data I get an empty list of Exchange folders to choose from, as well as a lengthy stack trace in my `production.log`:

```
Could not retrieve folders. ErrorAccessDenied: Der Zugriff wird verweigert. Überprüfen Sie die Anmeldeinformationen, und versuchen Sie es dann erneut. (Viewpoint::EWS::EwsFolderNotFound)
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/viewpoint-1.1.0/lib/ews/folder_accessors.rb:167:in `find_folders_parser'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/viewpoint-1.1.0/lib/ews/folder_accessors.rb:46:in `folders'
/opt/zammad/lib/import/exchange/folder.rb:69:in `request_children'
[ -- snip -- ]
/opt/zammad/lib/import/exchange/folder.rb:14:in `id_folder_map'
/opt/zammad/lib/sequencer/unit/exchange/folders/id_path_map.rb:16:in `block in process'
[ -- snip -- ]
/opt/zammad/lib/sequencer/state.rb:45:in `provide'
[ -- snip -- ]
/opt/zammad/lib/sequencer.rb:25:in `process'
/opt/zammad/app/controllers/integration/exchange_controller.rb:27:in `block in folders'
/opt/zammad/app/controllers/concerns/integration/import_job_base.rb:43:in `answer_with'
/opt/zammad/app/controllers/integration/exchange_controller.rb:26:in `folders'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[ -- snip -- ]
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:834:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/strategy.rb:190:in `call!'
[ -- snip -- ]
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/omniauth-1.7.1/lib/omniauth/builder.rb:63:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
[ -- snip -- ]
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
[ -- snip -- ]
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/configuration.rb:225:in `call'
[ -- snip -- ]
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474
```

* Zammad version: 2.3.0-15174215 Ubuntu package
* Installation method: apt
* Operating system: Ubuntu 16.04.3 LTS (Xenial)

### Expected behavior:

* After entering my Exchange account data, I'd expect to get access to the Exchange address book.

### Actual behavior:

* I get a window that wants me to select "folders" to import out of an empty list. The exception thrown according to the logs indicates a missing folder while the textual message (from the Exchange server) seems to hint to a permission problem.

No, I'm not sure that this is a Zammad bug. It might very well be caused by something weird about my Exchange server. But whatever it is, there should at least be some kind of Error message in the UI that tells me what's wrong and how to fix it, not just an empty list.

**Comment by rlue** [comment]
@rbq, I suspect that for the Exchange credentials & endpoint you provided, there are no folders visible/allowed to the given user (or if there are, then there is a bug in the [Viewpoint gem](https://github.com/WinRb/Viewpoint) we use to interface with EWS). The `ErrorAccessDenied` message you see in the logs is actually [rescued and ignored](https://github.com/zammad/zammad/blob/develop/lib/import/exchange/folder.rb#L67-L69), and Zammad will continue to recursively gather as many folders from the Exchange server as it can.

To confirm that your given credentials do not have access to any folders on the endpoint, check the output of the following command (run from your `zammad` directory):

```
$ rails r 'p Import::Exchange::Folder.new(Viewpoint::EWSClient.new("<endpoint url>", "<email address>", "<password>")).all.count'
```

97f55bc addresses this by aborting the Exchange configuration and displaying an error message when no folders are found. 

---

If you have reason to believe that there is still a bug (_i.e.,_ that your credentials do have access to some folders and Zammad is simply not finding them), please let us know.

**Comment by rbq** [comment]
```
Cookie#domain returns dot-less domain name now. Use Cookie#dot_domain if you need "." at the beginning.
#<Viewpoint::EWS::EwsFolderNotFound: Could not retrieve folders. ErrorAccessDenied: Der Zugriff wird verweigert. Überprüfen Sie die Anmeldeinformationen, und versuchen Sie es dann erneut., Nicht vom System stammende Anmeldung kann nicht auf Systemordner zugreifen.>
#<Viewpoint::EWS::EwsFolderNotFound: Could not retrieve folders. ErrorNoPublicFolderReplicaAvailable: Es sind keine Server für Öffentliche Ordner verfügbar.>
48
```
