### ISSUE TITLE
Avatars' Alpha mask is removed by auto-conversion to JPG, leads to many graphical artifacts

### ISSUE THREAD

**Issue by MacLemon** [zammad/zammad#1807]
### Infos:
* Used Zammad version: 2.2.0
* Installation method (source, package, ..): source
* Operating system: FreeBSD 11.1p6 (though irrelevant)
* Database + version: PostGreSQL 10.1 (though irrelevant)
* Elasticsearch version: n/a not in use
* Browser + version: Firefox 58.0 (though irrelevant)

### Expected behavior:
* Avatars that are uploaded as PNG graphics must be kept in PNG format to retain their alpha mask.

### Actual behavior:
* Avatars that are uploaded as PNG are converted to JPG
* An unwelcome black backdrop is added ignoring the alpha mask.
* File size is unnecessarily increased, especially for logo or illustration avatars.
* Converted JPEG avatar graphics also show shifted color representation making them appear darker than they should be.
* Converted JPEGs are overcompressed showing color fringing at contrasting edges.

Examples from Ticket timeline view, navigation sidebar, user profile:
![screen shot 2018-02-03 at 19 12 47](https://user-images.githubusercontent.com/90635/35770169-a0b6af04-0916-11e8-92e2-dcd65b14df69.png)
![screen shot 2018-02-03 at 19 13 16](https://user-images.githubusercontent.com/90635/35770174-a888ddba-0916-11e8-8c47-2dd031426f53.png)
![screen shot 2018-02-03 at 19 13 35](https://user-images.githubusercontent.com/90635/35770175-ac1b5d36-0916-11e8-9949-5dd6df944b0a.png)

### Steps to reproduce the behavior:
* Take an avatar image in PNG format with alpha mask and upload it to your profile.
* See, ticket view, your own profile, sidebar with graphical artifacts

While a PNG with correct color representation, much better sharpness, and especially correct graphical presentation without artifacts would likely require a little more storage space than the processed JPEG it would also look a *lot* better and have correct masking all over the UI.
Since the avatar is shown at 40px x 40px in the ticket timeline, using a 320px x 320px JPEG there doesn't make a lot of sense. Using a correctly scaled down version of the uploaded PNG would actually result in a 1/3rd sized artwork file.

While only a cosmetic bug, the clean and optically appealing overall appearance of Zammad should also correctly depict avatars with alpha masks. (Attention to detail.)

Also, avatar images should be properly cached by the browser but are delivered with these headers.

```
date: Sat, 03 Feb 2018 18:11:22 GMT
content-type: image/jpeg
expires: Sun, 03 Feb 2019 18:11:22 GMT
cache-control: max-age=31536000, private, must-revalidate, cache, store
pragma: cache
```
The `expires` and `cache-control` headers seem to be contradicting to me. (I might misinterpret them though. May or may not warrant its own ticket.)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @mrflix - could you please have a look and provide an assessment for this issue?
