### ISSUE TITLE
Zammad logout issue -> You don't have permission to access /api/v1/signout

### ISSUE THREAD

**Issue by DwijadasDey** [zammad/zammad#1808]
### Infos:

* Used Zammad version: 2.3.0
* Installation method (source, package, ..): Package
* Operating system: CentOS 7
* Database + version: PostgreSQL 9.2.23
* Elasticsearch version: 5.6.7
* Browser + version: 57.0.4

### Expected behavior:

* Should not able to login

### Actual behavior:

* Able to login without password being prompted.

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

Hi
I have installed zammad in CentOS 7 using yum and using Apache virtual host (Reverse Proxy) to access zammad. The logout seems to be not working properly. I can login again to zammad after logout without username/password being prompted.

I got the following message after logout.

StatusCode: 403

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /api/v1/signout
on this server.<br />
</p>
</body></html>

https://imagebin.ca/v/3qc9SLDB6VAS

**Comment by muhammadn** [comment]
@DwijadasDey I am suspecting it might be due to the misconfiguration of your Apache reverse proxy, you need to allow and pass `DELETE` request to the zammad instance from your reverse proxy.

Are you using an Apache configuration like the one in /opt/zammad/contrib/apache2 ?

**Comment by DwijadasDey** [comment]
@muhammadn I am using the Apache configuration like the one in /opt/zammad/contrib/apache2 and modified a little bit.

<VirtualHost 1.2.3.4:80>
 
    ServerName support.mydomain.org
    HostnameLookups Off
    UseCanonicalName Off
    ServerSignature Off
    ProxyRequests Off
    ProxyPreserveHost On
    RequestHeader set X_FORWARDED_PROTO 'https'

    <Proxy localhost:3000>
        Require local
    </Proxy>

    ProxyPass /assets !
    ProxyPass /favicon.ico !
    ProxyPass /robots.txt !
    ProxyPass /ws ws://localhost:6042/
    ProxyPass / http://localhost:3000/

    DocumentRoot "/opt/zammad/public"

    <Directory />
        Options FollowSymLinks
        AllowOverride None
    </Directory>

    <Directory "/opt/zammad/public">
        Options FollowSymLinks
        Require all granted
    </Directory>

    <FilesMatch “\.(php)$”>
        SSLOptions +StdEnvVars
    </FilesMatch>

    BrowserMatch “MSIE [2–6]” \
    nokeepalive ssl-unclean-shutdown \
    downgrade-1.0 force-response-1.0
    BrowserMatch “MSIE [17–9]” ssl-unclean-shutdown
    RequestHeader set X_FORWARDED_PROTO https

</VirtualHost>

**Comment by DwijadasDey** [comment]
Where is the location of /api/v1/signout ? The installation of zammad is in /opt/zammad .

**Comment by muhammadn** [comment]
@DwijadasDey Definitely not `Directory`, /api/v1/signout is just a relative path to your root URL hostname/domainname.

eg. https://support.mydomain.org**/api/v1/signout**

**Comment by thorsteneckel** [comment]
This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

**Comment by tonikasch** [comment]
In my case this is due to ModSecurity :-)
https://briansnelson.com/How_to_disable_mod_security_per_vhost
