### ISSUE TITLE
Reporting: profile condition is ignored

### ISSUE THREAD

**Issue by martini** [zammad/zammad#1809]
### Infos:

* Used Zammad version: 2.2.1 till 2.3.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Used Report::Profile condition as selected tickets in reports

### Actual behavior:

* Report::Profile condition is ignored. The filter "{"ticket_state.name"=>{"operator"=>"is not", "value"=>"merged"}}" is always used

### Steps to reproduce the behavior:

* create a new report profile with groups on the condition
* go to reports and select the new profile -> you will see that the Report::Profile condition has no effect

Issue was introduced by fix for https://github.com/zammad/zammad/issues/1741

**Comment by muhammadn** [comment]
Fixed so closing.
