### ISSUE TITLE
Allow customers without email addresses (was incoming phone call)

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#181]
Grade kam ein Telefonanruf rein. Mein Kollege hat ihn angenommen, weiß aber nur den Nachnamen, die Firma und die Telefonnummer des Anrufers. 

Ich wähle in Zammad "+", "neues Ticket". Ich muss einen neuen Benutzer anlegen. 

Zammad besteht aber darauf, dass wir Vorname und E-Mail angeben. Beides habe ich nicht. Wie gehts weiter?

Bei der Adresse kann ich auch den Firmennamen nicht eingeben, denn dazu müßte ich erst eine Organisation erstellen. 

Das ist schon ein paar Mal passiert. Die Mitarbeiter helfen sich, in dem sie falsche Daten eingeben. Bitte abstellen, denn bald kann man sich auf die Daten in Zammad nicht mehr verlassen! Ich habe jetzt rogge@zammad.de eingegeben ...

**Comment by monotek** [comment]
Maybe this proposal would also help: https://github.com/zammad/zammad/issues/562

**Comment by zabarabab** [comment]
The incoming call issue is still not resolved: a caller does not necessarily have an email-Address. 

This issue has been raised several times (e.g. #613).

If zammad really needs a contact information, then why not turn it into a url? 

For email, this could be: `mailto:max@provider.com`
For a phone number: `tel:+1-201-555-0123`

**Comment by martini** [comment]
Update, with next Zammad version you can create users without email address too.

Is available in develop branch.

So as summary, the following changes has been done:

* just enter an email address, is user is not existing, a new customer will be created automatically
* if the customer replies via email, the realname will be used/updated for the customer user
* possible to create customers without email address (at least firstname, lastname, email or phone need to be there)

**Comment by zabarabab** [comment]
Yipiie!! Thank you!! Can't wait to see that in my instance ;-)
