### ISSUE TITLE
LDAP - Fix for #1664 causes new troubles - Groups not found because of filter adjustment, filter not working like expected 

### ISSUE THREAD

**Issue by Sandalas** [zammad/zammad#1811]
### Infos:

* Used Zammad version: 2.3.0
* Installation method (source, package, ..): yum
* Operating system: centOS
* Database + version: -
* Elasticsearch version: -
* Browser + version: -

### Expected behavior:

LDAP Groupsearch should find each LDAP Object from with ObjectClass 'groupOfUniqueNames', 'group', 'posixgroup' OR (!) 'organization'.

The filter in the configuration file /opt/zammad/lib/ldap/group.rb is indeed a array, but the function only seems to use the first entry. This would explain the behaviour before and after the update from 2.2.0 to 2.3.0  [8272ae2]

### Actual behavior:

Before 2.3.0:
Only LDAP Objects with the ObjectClass 'group' were found.

After 2.3.0:
Only LDAP Objects with the ObjectClass 'groupOfUniqueNames' were found.

I used groups for my roles with the ObjectClass 'group' after the update from 2.2.0 to 2.3.0 they are no longer found in the selectField but for that other groups (all have atleast the ObjectClass 'groupOfUniqueNames').
I changed the filter from in /opt/zammad/lib/ldap/group.rb:
```
lookup_filter(['(objectClass=groupOfUniqueNames)', '(objectClass=group)', '(objectClass=posixgroup)', '(objectClass=organization)'])
```
to:
```
lookup_filter(['(objectClass=group)', '(objectClass=posixgroup)', '(objectClass=organization)'])
```
After that change my old groups where found again, but not the other ones anymore.
 

### Steps to reproduce the behavior:

* Activate and configure LDAP
* Go to LDAP roles, search for a LDAP Group without the ObjectClass 'groupOfUniqueNames', it won't be displayed

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @Sandalas - Thanks for reporting this. We have to change the filter detection in general. I'll take this as a cause to the list.

**Comment by lukrop** [comment]
We are using OpenLDAP and our groups have a `objectClass` of `groupOfNames`. The role assignment wizard won't find any groups without changing the lookup_filter to
``` @filter ||= lookup_filter(['(objectClass=groupOfNames)', '(objectClass=groupOfUniqueNames)', '(objectClass=group)', '(objectClass=posixgroup)', '(objectClass=organization)'])```

Thanks to this issue I found out that it seems that really just the first element of the array is taken into account since first I added the `objectClass=groupOfNames` as last element to the array and still didn't get any groups in the wizard for role assignment.

**Comment by dominikklein** [comment]
This was already improved with the following PR: https://github.com/zammad/zammad/pull/3041
