### ISSUE TITLE
Accept Only Registered Emails

### ISSUE THREAD

**Issue by antikilahdjs** [zammad/zammad#1812]
### Infos:

* Used Zammad version: 2.3 ( Latest )
* Installation method (source, package, ..): RPM ( Repo )
* Operating system: Centos 7 ( Latest )
* Database + version: MariaDB 10.2
* Elasticsearch version: 5.5.6
* Browser + version: Chrome ( Latest )

### Expected behavior:

Receive emails from registered users

### Actual behavior:

Hi, it is possible on Zammad configure to receive emails from specific users ? I wanna received a ticket from users want are registered in my Zammad . Thank you 

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a question. You can ask questions over at https://community.zammad.org/ - Closing now.
