### ISSUE TITLE
Migrate from 1.5.0 to 2.3.0

### ISSUE THREAD

**Issue by ktb92677** [zammad/zammad#1815]
Hi all! Sorry about not following the proper formatting but I'm not sure my case applies. I need some assistance migrating my zammad install running on 1.5.0 to a server running on 2.3.0. Unfortunately the server running 1.5.0 is probably no longer going to be accessible, but before it came to that state I managed to make a backup of the postgresql database. But I am now having huge trouble getting 2.3.0 to read from that database after I restored to it. I tried posting about this in the community forum but no one has replied yet and I am a bit desperate for help here. Any would be greatly appreciated. Sorry if I am violating some kind of guidline by doing this but I am fairly desperate. Thank you again

**Comment by monotek** [comment]
Just do a fresh installation on the new server. Stop Zammad. Replace the database with the old backup. Run /opt/Zammad/contrib/packager.io/postinstall.sh. start Zammad.
