### ISSUE TITLE
Unable to perform authentication with Gitlab behind a reverse proxy

### ISSUE THREAD

**Issue by TheBlusky** [zammad/zammad#1819]
Hi !

* My zammad installation is behind a Traefik reverse proxy in order to handle HTTPS / TLS, let say https://zammad/.
* My gitlab installation is, let say, https://gitlab/.
* I configured Zammad so I can have a Gitlab authentication, created an application in Gitlab, used `https://zammad/auth/gitlab/callback` as URL.

Why trying to authenticate using Gitlab, I'm redirected to the following url:

`https://gitlab./oauth/authorize?client_id=XXX&redirect_uri=http%3A%2F%2Fzammad%3A443%2Fauth%2Fgitlab%2Fcallback&response_type=code&state=XXX`

That means that Zammad thinks to be on the "http://zammad:443" URL. It's not the case, and there is nowhere to configure it, so the authentication fails, as it's not the one configured.

When I manually go to the URL `https://gitlab./oauth/authorize?client_id=XXX&redirect_uri=https%3A%2F%2Fzammad%2Fauth%2Fgitlab%2Fcallback&response_type=code&state=XXX`, the Gitlab authentication works, but Zammad identification fails.

I'm sur it's a bug, because other features of Zammad (ex: cURL command displayed in the API view) are self aware of the real protocol / host / port configuration.

### Infos:

* Used Zammad version: zammad/zammad-docker-compose:zammad
* Installation method (source, package, ..): docker + docker-compose
* Operating system: Debian
* Database + version: zammad/zammad-docker-compose:zammad-postgresql
* Elasticsearch version: zammad/zammad-docker-compose:zammad-elasticsearch
* Browser + version: Firefox 58.0.1

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
@TheBlusky Can you access the rails container and tell me what do you get when you run`zammad run rails r 'Setting.get('http_type')` ?

**Comment by TheBlusky** [comment]
@muhammadn I don't see any `zammad` binary.
I executed `docker exec -it zammad_zammad-railsserver_1 bash` so I can have a "bash" terminal. What should I execute ?

**Comment by muhammadn** [comment]
From shell ($ is shell and > is the rails console prompt):
```
$ zammad run rails c
> Setting.get('http_type')
```

**Comment by TheBlusky** [comment]
Are you sure ?

```
root@51d2822ab110:~# zammad run rails c
bash: zammad: command not found
```

**Comment by muhammadn** [comment]
@TheBlusky Sorry, docker images doesn't seem to have zammad script.
Please run these commands:
$ rails c
> Setting.get('http_type')

**Comment by TheBlusky** [comment]
Still trying to debug it, the issue is clearly on the "/auth/gitlab/" endpoint:

```
$ curl -v "https://zammad/auth/gitlab/"
> GET /auth/gitlab/ HTTP/1.1
> Host: zammad
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Cache-Control: no-cache
< Content-Length: 298
< Date: Thu, 08 Feb 2018 18:25:46 GMT
< Location: https://gitlab/oauth/authorize?client_id=XXX&redirect_uri=http%3A%2F%2Fzammad%3A443%2Fauth%2Fgitlab%2Fcallback&response_type=code&state=XXX
< Server: nginx/1.6.2
< Set-Cookie: _zammad_session_a138cfd0f37=XXX; path=/; HttpOnly
< X-Request-Id: 74e30ac0-e48c-4654-9667-ff223ba30a59
< X-Runtime: 0.027432
< Content-Type: text/plain; charset=utf-8
Redirecting to https://gitlab/oauth/authorize?client_id=XXX&redirect_uri=http%3A%2F%2Fzammad%3A443%2Fauth%2Fgitlab%2Fcallback&response_type=code&state=XXX
```

The `redirect_uri` used in the redirection should not be `http://zammad:443/auth/gitlab/callback` but `https://zammad/auth/gitlab/callback`

**Comment by muhammadn** [comment]
@TheBlusky yes, i am puzzled as well. I have tested this on my local development machine (not docker) and i can see the redirect_uri using `https://` (basically proxying from a public domain to my router's public IP and to my development machine)

So yes, i am still downloading the docker images right now since i have isolated the problem might be just with docker setup.

**Comment by muhammadn** [comment]
@TheBlusky 

Just to check with you, there is a README.md note at https://github.com/zammad/zammad-docker-compose about using a reverse proxy. Have you tried the instructions?

**Comment by TheBlusky** [comment]
If you're talking about the `VIRTUAL_HOST` env var, yes, it's been set, however it's just an hostname, no protocol, so I don't think it's related.

**Comment by TheBlusky** [comment]
I'm pretty confident that my Zammad instance is aware that it's using HTTPS, because when I'm nagivating on the settings forms, many information displays "HTTPS" :

![firefox_2018-02-08_20-11-20](https://user-images.githubusercontent.com/441709/35993209-e19571a0-0d0c-11e8-89e9-1e24545427a8.png)

However, when "curling" the `https://zammad/auth/gitlab/` endpoint, the `redirect_uri` param is set using `http`

**Comment by TheBlusky** [comment]
I am not using nginx for TLS (the only nginx I use is the one provided on the Zammad docker-compose).

My first reverse proxy is Traefik, which should already send the "X-Forwarded-XXXX" headers.

I'm not sure about default nginx configuration within the docker-compose template. I'm gonna check that :-)

**Comment by martini** [comment]
Any news?

**Comment by TheBlusky** [comment]
I worked arround it.

I configured the callback URL to be in "http" (instead of HTTPS), so the URL contains the good redirect_uri.
But I added HSTS to my zammad instance, so when I'm redirected to `http://zammad/{OAUTH_INFO}`, the request is performed on HTTPS.

It does not solve the bug, but at least, the solution is working, and fully in HTTPS.
