### ISSUE TITLE
Select/Change overview on touch devices

### ISSUE THREAD

**Issue by chrisblech** [zammad/zammad#1821]
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): package (Zammad DEB repo)
* Operating system: Debian 9.3
* Database + version: PostgreSQL 9.6.6
* Elasticsearch version: 5.6.7
* Browser + version: Chrome for Android (latest)

### Expected behavior:

* Agent can select a overview by touching the overflow menu button ("hamburger"), then touch name of the overview

### Actual behavior:

* After click on the overflow menu button, a dropdown with all overviews opens. Touching the name of an overview closes the overflow menu, but doesn't change/display the overview.

### Steps to reproduce the behavior:

* define more than 3 overviews for agents
* open zammad in android touch device, as agent
* open main menu "overviews"
* touch "hamburger" menu button
* touch any overview name

(see attached screencast)
[ScreenRecord_2018-02-09-11-17-42.zip](https://github.com/zammad/zammad/files/1710654/ScreenRecord_2018-02-09-11-17-42.zip)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @chrisblech - sorry to say but the current interface doesn't support mobile devices like e.g. Android. There is an dedicated issue for that: https://github.com/zammad/zammad/issues/223

**Comment by nonameolsson** [comment]
Yeah, it doesn't work. But the issue you referenced is locked, and no solution is added yet. Is this on the roadmap?  It has been more then a year since this.

**Comment by MrGeneration** [comment]
There's a reason why we lock those issues, as those comments create noise for over 100 watching people. We try to keep this to a minimum.

Mobile support is on our roadmap, but without date to this moment. Sorry about that.
