### ISSUE TITLE
Overview with responded tickets

### ISSUE THREAD

**Issue by artempronevskiy** [zammad/zammad#1823]
Hello,

Is it possible to create overview that would contain tickets which were responded so support agents wait for clients reply? As far as I understand "Pending reminder" and "Pending closed" states are not what I'm looking for. In Zendesk such state is called [Pending](https://support.zendesk.com/hc/en-us/articles/203660256-Open-vs-pending-and-on-hold-tickets-and-why-you-should-care), is there something simmilar in Zammad?

Thanks!

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a question. You can ask questions over at https://community.zammad.org/ - Closing now.
