### ISSUE TITLE
Pull CC email recipients from database

### ISSUE THREAD

**Issue by DjMagicFingers** [zammad/zammad#1827]
While creating a ticket or answering one, there is an option to add CC'd recipients to the ticket if the answer is sent by mail.

The field is not pulling the email address from the database and you actually need to type the email address of the CC'd recipient.

Used Zammad version: 2.3.x

**Comment by thorsteneckel** [comment]
Please use the issue template you removed. It's really important for us maintainers to have the required information. I have to close this issue in the meantime. Feel free to update your post. I'll reopen the issue afterwards.
