### ISSUE TITLE
Close search button at the wrong side when using RTL language

### ISSUE THREAD

**Issue by DjMagicFingers** [zammad/zammad#1831]
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..):
* Operating system: CentOS 7
* Database + version: Postgres
* Elasticsearch version: 5.6
* Browser + version: various

### Expected behavior:

* The "X" sign that appears when using search on a RTL language profile should be at the left side of the search circle and should be easy to see and press on.

### Actual behavior:

* The "X" sign for closing search results is shown on top of the magnifying glass at the right side of the circle instead of the left side.

![wrong place of search close button when in hebrew profile](https://user-images.githubusercontent.com/32017425/36148416-a446c0a4-10c4-11e8-8afa-a3230c38c0aa.png)

### Steps to reproduce the behavior:

* Change your profile to RTL like Hebrew or Arab language and start entering words at the search circle.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mrflix** [comment]
Thanks for reporting these RTL bugs, DjMagicFingers!

**Comment by DjMagicFingers** [comment]
Thank you for attending to it mrflix :)
