### ISSUE TITLE
Ticket created from email messages containing Hebrew - unreadable fonts

### ISSUE THREAD

**Issue by DjMagicFingers** [zammad/zammad#1833]
### Infos:

* Used Zammad version: 2.3.ס
* Installation method (source, package, ..):
* Operating system: CentOS 7
* Database + version: postgers
* Elasticsearch version: 5.6
* Browser + version:various

### Expected behavior:

* A ticket should be created with readable text with the original language and encoding it was created from it's source.

### Actual behavior:

* A ticket created from an email message sent from a Hebrew enabled device (like android phone, outlook etc') sometimes formats an unreadable ticket:

![some hebrew fonts are still unreadable - sent from android](https://user-images.githubusercontent.com/32017425/36151851-9e9520c6-10d1-11e8-90e2-4e9cb2739445.png)

### Steps to reproduce the behavior:

* Since this is not happening for all email messages, if needed, i can send the RAW email message that caused this kind of bad text.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mrflix** [comment]
Yes please send us the RAW email message!

**Comment by DjMagicFingers** [comment]
Where can i send it to so it would not be publicly visible?
There are email addresses of clients in it...

**Comment by thorsteneckel** [comment]
Hi @DjMagicFingers - just drop us a mail to support@zammad.com and refer to this issue. This is the same as your issue #1445 . I'll close it an refer to this since it's more recent.
