### ISSUE TITLE
LTR texts in an RTL profile is RTLed sometimes

### ISSUE THREAD

**Issue by DjMagicFingers** [zammad/zammad#1835]
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..):
* Operating system: CentOS 7
* Database + version: Postgres
* Elasticsearch version: 5.6
* Browser + version: Various

### Expected behavior:

* Zammad should recognize the encoding of the input text and align it to RTL or LTR accordingly as it does in some cases.

### Actual behavior:

* While using Zammad in an RTL language profile, Texts that are LTR - like English answer to clients that only speak English, it formatted RTL and not LTR at the web interface.

![2018-02-13 16_21_06-srvit helpdesk - 113241 - computer problems](https://user-images.githubusercontent.com/32017425/36154554-8825e1d2-10da-11e8-93c4-cedfecfc1bd6.png)

In other cases, emails received from the user are LTRed, even for the RTL profile, while the agent answer is RTLed...

![2018-02-13 16_29_47-srvit helpdesk - 112984 - email id not working](https://user-images.githubusercontent.com/32017425/36154846-5c51f874-10db-11e8-9f60-d604c0f5b61e.png)

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mrflix** [comment]
@thorsteneckel detecting the text-direction of articles would have to happen on the backend.

**Comment by gss-wc** [comment]
Greetings,

I reviewed a similar/related ticket ( https://community.zammad.org/t/mixed-language-tickets-and-rtl-right-to-left-vs-ltr-left-to-right/5122) and that ticket referred me to this ticket.

While the solution to this need can be solved on the backend using an API to detect language and direction, I think you may have overlooked a simpler front-end solution that can be implemented fairly quickly. 

HTML5 provides a tag `dir="auto"` that will recognize and correctly set the direction of a character-set within a set of HTML tags. While it is not a full-proof solution, it is one used by other ticketing and content management systems. 

I manage a large RoR based program. We made a slight modification to the zammad code back in Aug-2020 in our test environment (see attached image) that added `dir="auto"` by default to the `<div>` sections contained within a ticket-article. This allowed the browser to automatically adjust the text direction correctly. As best that we can tell, this change caused no conflicts with the zammad rich-text functions/solution and appears stable (we tested with a variety of different RTL and LTR languages.)

I am happy to task a portion of my dev team to coordinate and submit a more formal solution to the zammad development team for possible inclusion in the base product. 

Is this a solution worth pursuing?
If yes, what is the best way to start the process?

![zammad_dir-auto](https://user-images.githubusercontent.com/60408945/105077086-fd1c1f80-5a59-11eb-8032-fa4485836a6f.png)

**Comment by thorsteneckel** [comment]
@gss-wc thanks for reaching out! @mrflix - what do you think? I'll manage the contribution part if you think it's a good solution for Zammad 👍

**Comment by gss-wc** [comment]
@thorsteneckel any movement/updates on this subject? I'd like to get someone on my team started on in a manner that is useful to the project. Let me know, please. Thx.

**Comment by mantas** [comment]
Hi @gss-wc 

What elements did you add `dir="auto"` to?

Looking at the screenshot, it looks like it you added it to not only to `.richtext-content`, but to it's sub-elements as well?

**Comment by Shahala1** [comment]
@mantas 

Did you receive any update from gss-wc?
We are considering allocating resources to this issue(high priority for us) but want to avoid re-inventing the wheel.

**Comment by mantas** [comment]
@Shahala1 didn't hear much yet :(
