### ISSUE TITLE
first name is a mandatory field - with rest api its not

### ISSUE THREAD

**Issue by lr1980** [zammad/zammad#1836]
### Infos:

* Used Zammad version: 2.3

### Expected behavior:

* It is not possible with web ui to add a user without first name. We do not always know the first name...

### Actual behavior:

* With REST API it is possible.

**Comment by thorsteneckel** [comment]
Hi @lr1980 - This is intended. Use '-' as a value instead.

**Comment by lr1980** [comment]
"-" is very bad because you see everywhere (e.g. mail templates)
![screen shot 2018-02-16 at 10 51 38](https://user-images.githubusercontent.com/1901770/36302096-7a56db9a-1307-11e8-8ec8-5c8e94ec0732.png)
