### ISSUE TITLE
new Object for Tickets ignore options on type Date

### ISSUE THREAD

**Issue by schmanat** [zammad/zammad#1843]
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): deb
* Operating system: Ubuntu 16.04.
* Database + version: PostgreSQL 9.5
* Elasticsearch version: 5.6.7
* Browser + version: Chrome (latest)

### Expected behavior:
Create an additional Field for tickets with the required option should throw a message if it's not filled.

### Actual behavior:
I create a new database filed (due_date) within the settings (Settings -> Object). I named it due_date. In the Screenshot you see my settings.
![objects](https://user-images.githubusercontent.com/1080148/36413636-92e188fc-161f-11e8-81c1-8ada3ea6ecf4.PNG)

After upgrading the database the new filed is available but.

- Its possible to leave the due_date blank
- its possible to select and send dates in the past
- default time diff is ignored.

### Steps to reproduce the behavior:

- create a new Object
- select date format
- you can see the settings on the screenshot above
- submit

- create a new ticket
- leave the new field blank or select a date in the past
- submit the ticket

The tickt will be submited.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by schmanat** [comment]
I'm the only one with this issue?

**Comment by thorsteneckel** [comment]
No - there is actually already an issue: #1259. Closing now as duplicate.
