### ISSUE TITLE
Report profiles have no effect

### ISSUE THREAD

**Issue by sheLbyPL** [zammad/zammad#1844]
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: MySQL
* Elasticsearch version: 5.6.7
* Browser + version: Latest chrome

### Expected behavior:

* Report profiles work, you can filter things in reporting

### Actual behavior:

* Report profiles have no effect on the reporting

### Steps to reproduce the behavior:

* Create new report profile (for example Tickets with priority high)
* Go to Reporting and select profile -> nothing happens

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
@sheLbyPL Yes, it was fixed in issue #1809 . Sorry for the inconvenience. 😞 You can try out develop branch on github or you can wait for 2.3.1

**Comment by thorsteneckel** [comment]
@muhammadn - can you please backport this fix to stable?

**Comment by muhammadn** [comment]
@thorsteneckel sure! 👍

**Comment by sheLbyPL** [comment]
@muhammadn 
Thank you for backporting the fix to stable!

However, I have one more issue:
I've made report profile: Tags - contain one/all - my tag
and when I select it on reporting it sends this error:
`{"error":"unknown operator 'contains one' for ticket.tags"}`

Could you check it? Thank you in advance! Let me know if I should post it in new bug report.

**Comment by muhammadn** [comment]
@sheLbyPL yes. Thanks for reporting! 👍 
If you can make a new issue it would be better as we can track all the related bugs easily. 🚀

**Comment by sheLbyPL** [comment]
Also report profiles with condition type = xxx are not working, but it simply shows no results on reporting page (still on the preview during profile creation it shows tickets correctly)
