### ISSUE TITLE
Language issue + Feature request

### ISSUE THREAD

**Issue by failanas** [zammad/zammad#1845]
1. User doesn't get default language which is set as English, user sees czech language.
2. Would be useful feature if user on submit the ticket would be able to assign the tag.

### Infos:

* Used Zammad version:
* Installation method (source, package, ..):
* Operating system:
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

*

### Actual behavior:

*

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a (technical) question. You can ask questions over at https://community.zammad.org/ - Closing now.

PS: Don't forget to fill out the template when creating an issue. This is really important and helpful for us. We will close all issues that don't have a filled out template.
