### ISSUE TITLE
Report profiles - some conditions are not working

### ISSUE THREAD

**Issue by sheLbyPL** [zammad/zammad#1847]
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: MySQL
* Elasticsearch version: 5.6.8
* Browser + version: Latest chrome

### Expected behavior:

* All available conditions from admin panel -> report profiles should work in reporting

### Actual behavior:

* Some conditions are not working:
** tags - error 500 - {"error":"unknown operator 'contains one' for ticket.tags"}
** type - no results on reporting, still on preview in admin panel it looks fine

so far noticed only those two.

### Steps to reproduce the behavior:

* Create new report profile with condition tags / type
* Go to Reporting and select profile

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
@sheLbyPL Thanks! will look into this. 👍

**Comment by muhammadn** [comment]
Related to #1761

**Comment by muhammadn** [comment]
@jwronken Had a discussion earlier and that we concluded that we can only have basic reports for now but for advanced reporting we will be using Grafana.

**Comment by martini** [comment]
Since it raise an error message in Zammad we fixed it (note in case it isn't working, you need to execute `zammad run rake searchindex:rebuild`).

Anyway, for enhanced visualisation you should use Grafana.
