### ISSUE TITLE
Overviews do not show open while using Android phone browser

### ISSUE THREAD

**Issue by DjMagicFingers** [zammad/zammad#1848]
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..):
* Operating system: CentOS 7
* Database + version: Postgres
* Elasticsearch version: 5.6
* Browser + version: Android chrome

### Expected behavior:

* Selecting "Open" from the hamburger menu should provide a list of all Open tickets.

![image](https://user-images.githubusercontent.com/32017425/36475942-0a79b9da-1705-11e8-8446-2813c2d9aeaa.png)

### Actual behavior:

* Using Android phone with chrome browser, pressing "Open" at the hamburger menu dose not change the view.

### Steps to reproduce the behavior:

* While browsing Zammad on an Android phone with a chrome browser, go to overviews and press the hamburger menu icon.
At the sliding menu that just opened, press "Open"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Mobile is currently not supported - see #223

**Comment by DjMagicFingers** [comment]
OK, wanted to add my thumb up but it is locked so how do i express my emotion about this?

**Comment by thorsteneckel** [comment]
Locked issues with a lot of thumb up are already on our list so there is no higher priority than that. Unfortunately we can't lock conversations for comments (to avoid +1 and "when will it be ready") but allow emojis.
Generally speaking each mail we receive and have to write about this costs our time to implement this. This is really frustrating (for everybody involved) but we have no satisfying solution for this yet.

Nevertheless I recognize your expressed emotion about this.

**Comment by DjMagicFingers** [comment]
Thank you, time calculations understood :)
