### ISSUE TITLE
unable to use tree_select object (ticket) in report profile as filter

### ISSUE THREAD

**Issue by jwronken** [zammad/zammad#1849]
**Infos:**

Used Zammad version: 2.3.x
Installation method (source, package, ..): yum
Operating system: CentOS 7
Database + version: PostgreSQL 9.2.23
Elasticsearch version: -
Browser + version: Firefox ESR 52.5.2
Expected behavior:

it seems a tree_select object on a ticket is not visible when creating a new report profile.
changing to select works, but a tree_select object doesn't show up.

**Steps to reproduce the behavior:**

create new attribute in System > Objects > Ticket Object Manager with type tree_select. Update db and restart Zammad. Go to Manage -> Report Profiles and create New Profile
Filter Ticket doesn't show the created tree_select object.
Yes I'm sure this is a bug and no feature request or a general question:

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
@jwronken Had a discussion earlier and that we concluded that we can only have basic reports for now but for advanced reporting we will be using Grafana.
