### ISSUE TITLE
Cannot add/change a user's address

### ISSUE THREAD

**Issue by MatthiasWiesner** [zammad/zammad#1853]
### Infos:

* Used Zammad version: 2.3.0-1519371734.f7fb992f.xenial
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04.4 LTS (Xenial Xerus)
* Database + version: Postgresql 9.4+165+deb8u3
* Elasticsearch version: 5.6.8
* Browser + version: Google Chrome 64.0.3282.167 (Offizieller Build) (64-Bit)

### Expected behavior:

* Add an address to user

### Actual behavior:

* Cannot add a newline to address field. On type [Enter] in users address field, a javascript error occurs and stops further editing:
~~~
application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:65 Uncaught TypeError: Cannot read property 'text' of null
    at i.onEnter (application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:65)
    at i.navigate (application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:65)
    at HTMLDocument.<anonymous> (application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:64)
    at HTMLDocument.dispatch (application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:2)
    at HTMLDocument.m.handle (application-2b501577fcb53dbc0ffccab95d3f20acbf602262dbc8f26be3f34d5ac307668b.js:2)
~~~ 

### Steps to reproduce the behavior:

* As admin click on users email to edit the user
* In the edit user modal dialog type [Enter] in the address field

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @MatthiasWiesner 

I have heard about this issue, but was not able to reproduce it so far. Do you also have this behaviour with other browsers too? And can you reproduce it with an online instant from https://zammad.com?

 -Martin

**Comment by MatthiasWiesner** [comment]
Hi @martini ,
just I checked it with Safari Browser and it worked correctly. Short after I checked it with the chromium again and surprisingly: now it worked here too (again). Now, Im really confused about it...
So, please close the ticket (but have an eye on this)

**Comment by martini** [comment]
Thanks for feedback. In case it appearing again, just send me some hints how to reproduce it. Maybe it has to do with the content which you want to paste in.
