### ISSUE TITLE
Userfilter resets after updating LDAP Settings

### ISSUE THREAD

**Issue by schmanat** [zammad/zammad#1854]
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): deb
* Operating system: Ubuntu 16.04
* Database + version: PostgreSQL 9.5
* Elasticsearch version: 5.6.8
* Browser + version: Firefox and Chrome (latest)

### Expected behavior:

If LDAP sync is active and need to reconfigure (for example assigning new members to roles) the User Filter should be the same as the last configuration.

So I have allways to "safe" the edited Userfilter and put them back before saving the new configuration.

### Actual behavior:

If I edit the LDAP sync the User Filter is allways resetet to the default User Filter

```ruby
(&(objectClass=person)(samaccountname=*)(!(samaccountname=*$))
```

### Steps to reproduce the behavior:

- activate LDAP sync
- change the User Filter (Experts)
for example:

```ruby
(&(objectClass=person)(objectClass=user)(mail=*)(!(mail=*test*))(!(mail=*postmaster*))(samaccountname=*)(!(samaccountname=*$))(!(UserAccountControl:1.2.840.113556.1.4.803:=2)))
```

- save them
- The User Filter works like expected
- click on edit to change something in the ldap configuration
- the User Filter is resetet

```ruby
(&(objectClass=person)(samaccountname=*)(!(samaccountname=*$))
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by gwingend** [comment]
Confirmed! 
Has been verified and confirmed by @martini yesterday on our installation.
