### ISSUE TITLE
customer field in customer_ticket_new when customer is logged in

### ISSUE THREAD

**Issue by klex04** [zammad/zammad#1856]
### Infos:

* Used Zammad version: 2.3
* Installation method (source, package, ..): DEB Repo
* Operating system: Ubuntu Linux
* Database + version: Postgres
* Elasticsearch version: 5.5.3
* Browser + version: any

### Expected behavior:
The System should know who is logged in and the field customer should not appear.

### Actual behavior:
If a Customer is logged in and want to create a new ticket via interface (customer_ticket_new), there is mostly (not always) a field (object) “customer”. That doesn’t make sence because the customer is already logged in, but even when he tried to fill everything out the ticket won’t be created. failing on this field I guess. because when reloading page, the field is gone and the ticket can be created

### Steps to reproduce the behavior:
I actually don’t know where it came from. it´s just there. something went terribly wrong. I don´t have a guess.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @klex04 - is it possible that before the same Browser was used by an Agent before? So an Agent was logged in, logs out and some time later a Customer logs in and has the fields?

**Comment by thorsteneckel** [comment]
Hi @klex04 - Just an intuition ;) As you can see on the commit messages above  we worked on the similar issue #949 not long ago. This is more or less a follow up. However, it's fixed in Zammad 2.4 🚀
