### ISSUE TITLE
Direct access to organization tickets possible even though shared is deactivated

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1857]
Hihi 👋 

first of all, I'm not quiet sure, if these realy is a bug or just a missunderstanding or a local problem.
Sadly I didn't have the oppertunity and ressources to test my issue in a fresh new zammad installation.

    Used Zammad version: 2.3.0-1518000657.f2e54de7.xenial
    Used Zammad installation source: Package
    Operating system: Ubuntu 16.04
    Browser + version: Chrome 63.0.3239.132 + Firefox 58.0.2

Starting point:
Organisation: ACME
Shared: False

Organisation: Aperture Science
Shared: False

User: A
Organisation: ACME

User: B
Organisation: ACME

User: C
Organisation: Aperture Science

User A creates a ticket and sends his ticket URL to User B and User C.
User B can take a look into User A ticket's, even though "shared" is set to false.
User C can't look into the ticket.

**Comment by bibhot** [comment]
We have the same problem in 2.4.x. Some requests may contain sensitive data and you should not be able to see other people's tickets by guessing the access number (Shared: False) in the same organisation. 
Please fix it.

**Comment by thorsteneckel** [comment]
Hi @MamoulianDelacroix - Thanks a lot for finding and reporting this! We fixed it with the two commits above. The new package version will be available ~30 minutes from now.
