### ISSUE TITLE
Missing To and Cc field when forwarding an article of a customer without an email address

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1858]
### Infos:

* Used Zammad version: 2.3
* Installation method (source, package, ..): package
* Operating system: CentOS
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* It should be possible to forward any article for which the forward action link is displayed.

### Actual behavior:

* Forward action link is displayed for (new phone ticket) articles of a customer without an email address. After clicking on the action link the new body field is shown. However, the To and Cc field is missing.

### Steps to reproduce the behavior:

* Create customer user without an email address
* Create a new phone ticket in the name of that customer
* See forward action link under the article
* Click forward action link under the article
* See body input field
* Don't see To and Cc input fields

**Comment by martini** [comment]
Commit: https://github.com/zammad/zammad/commit/008cfeea69313a8941419db3ab3c8aba240b3f48

I refactored the actions, so now on pressing reply also the action backends will decide what's happen (so params(), validation(), articleTypes() and setArticleType() is moved to action backends). 

@thorsteneckel Please verify if it's working correctly for you now. Thanks!

**Comment by thorsteneckel** [comment]
Works! Closing now. Will be available in Zammad 2.4
