### ISSUE TITLE
Related tickets are missing on ticket merge

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#186]
Dieses Ticket wurde mit einem anderen zusammengeführt:
https://linuxhotel.zammad.com/#ticket/zoom/500

Die Verknüpfung steckt aber immer noch hier drin, und nicht in dem anderen Ticket:
https://linuxhotel.zammad.com/#ticket/zoom/508

Aus meiner Sicht ist damit das zusammenführen nicht vollständig.

**Comment by rolfschmidt** [comment]
Hallo @zabarabab,
vielen Dank für deinen Report! Ich habe das Problem behoben und zukünftig sollten dann auch die Verlinkungen aus den gemergeden Tickets übernommen werden. Die Änderungen sind schon im develop branch.

-Rolf
