### ISSUE TITLE
After rebuilding the index we start getting unprocessable mails

### ISSUE THREAD

**Issue by CyberPunk2042** [zammad/zammad#1860]
### Infos:

* Used Zammad version: 2.0
* Installation method (Rancher, ..):
* Operating system:(CentOS-Docker-Rancher zammad-compose)
* Database + version: PostgreSql
* Elasticsearch version:
* Browser + version: Chrome

### Expected behavior:

*Search to show clients and tickets correctly

### Actual behavior:

* Search doesn't work properly and not showing all client and tickets.
After rebuilding the index it works but we start getting an error StatusCode: 500 and unprocessable mails  on some tickets which have been created recently

We can't update or join tickets them

Errors
Unprocessable mails
And
StatusCode: 500
{"error":"Permission denied @ unlink_internal - /home/zammad/tmp/cache_file_store_production/3D6/C90/User%3A%3A14870"}

Thank You

### Steps to reproduce the behavior:

*zammad run rake searchindex:rebuild

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Please reopen/provide feedback if required.

**Comment by CyberPunk2042** [comment]
Thanks for reply

Here is a screenshot
![photo_2018-03-07_15-40-04](https://user-images.githubusercontent.com/36038814/37092787-295c8444-221e-11e8-9f51-107503ded563.jpg)

From log file
"http://zammad-elasticsearch:9200/zammad_production/Ticket/29011" \
I, [2018-03-07T06:50:57.383307 #62]  INFO -- : # 201
I, [2018-03-07T06:50:57.410807 #62]  INFO -- : # curl -X POST "http://zammad-elasticsearch:9200/zammad_production/Ticket/29010" \
E, [2018-03-07T06:50:57.421422 #1] ERROR -- : Can't write cache Ticket::28970: #<Errno::EACCES: Permission denied @ rb_sysopen - /home/zammad/tmp/cache_file_store_production/4A1/810/.permissions_check.70077697804700.1.14223>


It is fetching new emails without any problem but after rebuild replies to old tickets start getting error 550

**Comment by martini** [comment]
Hi @CyberPunk2042 it seems that you are using docker and I guess it's a docker related permission problem.

Zammad tries to create a cache file but the OS says: Sorry, you have no permissions to do so.

**Comment by thorsteneckel** [comment]
Can you provide the permissions of the files exactly but not only the top `tmp/` folder? Like`ls -ah /home/zammad/tmp/cache_file_store_production/3D6/C90/User%3A%3A14870` and `/home/zammad/tmp/cache_file_store_production/4A1/810/`.

**Comment by CyberPunk2042** [comment]
Yes, we are using Docker/Rancher/Zammad-compose 2.0.
Ok, I will try to play with permissions then I post the result.
Thanks for replies.
