### ISSUE TITLE
Using installer: exclude nginx

### ISSUE THREAD

**Issue by benhartwich** [zammad/zammad#1863]
Hi,

I tried to install zammad for Ubuntu 16.04 and I´ve compiled my own nginx without using the official ubuntu package / repo. When I try to install zammad ubuntu package nginx would be installed - how can I prevent this?

Regards,

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

**Comment by monotek** [comment]
Install Zammad from source.

https://docs.zammad.org/en/latest/install-source.html#install-from-source-debian-7-8-ubuntu-16-04
