### ISSUE TITLE
How can i add Korean language, ko_KR.UTF-8

### ISSUE THREAD

**Issue by maddog00** [zammad/zammad#1868]
My request is not problem.
I want to use Korean language in your good solution.

thanks for reading. 

### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): deb
* Operating system: ubuntu server 16.04
* Database + version: default installation
* Elasticsearch version:
* Browser + version:

### Expected behavior:

*

### Actual behavior:

*

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by NeverMin** [comment]
Welcome @maddog00 ,

Please see [zammad console](https://docs.zammad.org/en/latest/admin-console.html), e.g.
```
rails> Translation.create_if_not_exists( :locale => 'ko_KR', :source => "New", :target => "새로운" )
```

Other translation:
 * [mail](https://github.com/zammad/zammad/commit/12726b8aaa60ed8dd35de46835596f1a6b4984fa)
* [form](https://github.com/zammad/zammad/blob/develop/public/assets/form/form.js)
* [chat](https://github.com/zammad/zammad/blob/develop/public/assets/chat/chat.js)

**Comment by maddog00** [comment]
thanks your answer.

it works for admin account,
but another account is setted language = english

can not find Korean or ko item in the language select box at profile setting menu.

How can i add Korean language into Language select box.

**Comment by NeverMin** [comment]
Sorry, my miss out.

```
rails> Locale.create_if_not_exists(locale: 'ko_KR',  name: 'Korean (한국어)')
rails> Locale.sync
rails> Translation.sync
```

Now, you can find new locale in `/#profile/language`.

한국어 : https://en.wikipedia.org/wiki/ISO_639-1

ps, if you have more questions about that, please post to: https://community.zammad.org/
