### ISSUE TITLE
Wrong article order after merging of tickets

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#187]
Nach einem Merge sollte die zeitliche Reihenfolge der Beiträge erhalten bleiben. Negativ-Beispiel:
https://linuxhotel.zammad.com/#ticket/zoom/508

Workaround: Ticket-Tab schließen (Strg+Alt+w) und neu öffnen.

-------------------------------

The initial order of articles after merging is wrong. A reload corrects the order in the right way.

**Comment by rolfschmidt** [comment]
Hi @zabarabab,
thank you very much for your report! The bug should be fixed now in develop branch. 

-Rolf
