### ISSUE TITLE
Hostname not found!

### ISSUE THREAD

**Issue by noname2327** [zammad/zammad#1871]
Info:

* Used Zammad version: Wersja Zammada 2.3.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu
* Database + version:
* Elasticsearch version:
* Browser + version: google chrome 64.0.3282.186

Expected behavior:
Correct addition of a new communication channel via email

 Actual behavior:

When I add a new email channel I get the message: "Hostname not found!"
I use the service Office 365 exchange and there i use TLS but zammad use SSL.
I try add gmail account and a message is also displayed : "Hostname not found!"

I choose options -> email communication channel -> add a new one. I enter the login, password, protocol and get the message as above

**Comment by muhammadn** [comment]
@noname2327 Your server probably have DNS resolving issues, check your server's DNS settings.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.
