### ISSUE TITLE
Loading... is shown instead of Helpdesk

### ISSUE THREAD

**Issue by TPNord** [zammad/zammad#1872]
### Infos:

* Used Zammad version: 2.3.0
* Installation method (source, package, ..): via RPM based on this description https://docs.zammad.org/en/latest/install-centos.html
* Operating system: clean install of CentOS on Hyper-V (Server 2012R2) based on this description
https://www.altaro.com/hyper-v/centos-linux-hyper-v/
* Database + version: the one that comes Wirth the RPM
* Elasticsearch version: the one that comes Wirth the RPM
* Browser + version: Safari Version 11.1 (13605.1.27.2.1) Java 8 Build161 enabled 

### Expected behavior:

* Loading Helpdesk

### Actual behavior:

* When I try to reach the Helpdesk via the local IP of the Zammad installation (192.168.178.79) it shows a blank page with "Loading..." in the upper left corner and nothing happens.

My zammad.conf File (/etc/nginx/conf.d/) looks like this:
#
# this is the nginx config for zammad
#

upstream zammad-railsserver {
    server localhost:3000;
}

upstream zammad-websocket {
    server localhost:6042;
}

server {
    listen 80;

    # replace 'localhost' with your fqdn if you want to use zammad from remote
    server_name 192.168.178.79

    root /opt/zammad/public;

    access_log /var/log/nginx/zammad.access.log;
    error_log  /var/log/nginx/zammad.error.log;

    client_max_body_size 50M;

    location ~ ^/(assets/|robots.txt|humans.txt|favicon.ico) {
        expires max;
    }

    location /ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_pass http://zammad-websocket;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
        proxy_pass http://zammad-railsserver;
        gzip on;
        gzip_types text/plain text/xml text/css image/svg+xml application/javascript application/x-javascript application/json application/xml;
        gzip_proxied any;
    }
}

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.
