### ISSUE TITLE
Mattermost-Integration/Configurations

### ISSUE THREAD

**Issue by ReisKanzlerTao** [zammad/zammad#1873]
**German**____________________________________

Hallo Leute,

ich bräuchte eure Hilfe. Es geht wie ihr schon am Titel erkennen könnt um die Mattermost Integration in Zammad. Gibt es eine Step für Step Anleitung für Laien wie mich ?
Ich selber habe Zammad per Docker installiert und "sogar" erfolgreich eine LDAP Anbindung gemacht.
Doch das integrieren von API oder ähnliches habe ich noch nie gemacht.

_Vielen Dank im vorraus an alle Helfer._

**English**_____________________________________

Hi Guys,

I need your help. Its about the Mattermost integration in Zammad. Is there a step by step guide for lay people like me?
I have installed Zammad via Docker and "even" successfully made an LDAP connection.
But I have never done, the integration of API or similar.

_Thanks to all the helpers._

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.
