### ISSUE TITLE
Email notification account problem

### ISSUE THREAD

**Issue by noname2327** [zammad/zammad#1879]
### Infos:

* Used Zammad version: 2.3.x

* Operating system: Centos 7
* Elasticsearch version:  5.6.8
* Browser + version: Chrome 

### Expected behavior:

Correctly added exchange online account for email notifications

### Actual behavior:

Error 501 5.1.7 Invalid address 

### Steps to reproduce the behavior:

I sent ticket to Microsoft and they told so this is not problem with exchange but zammad application.
I enter the same data in the email account section and work here correctly.

**Comment by thorsteneckel** [comment]
Hi @noname2327 - please provide the following information so we can help:

- screenshot of the error (complete page) 
- your `log/production.log` file
- Detailed description on how to reproduce

**Comment by noname2327** [comment]
Screenshot
![image](https://user-images.githubusercontent.com/37364607/37656746-39451a94-2c49-11e8-93e5-9b9c7810915e.png)

Log file 
[production.log](https://github.com/zammad/zammad/files/1829432/production.log)

I add email account and everything is ok, next i try add the same account and server address to email notification and i have error like on the screenshot

**Comment by thorsteneckel** [comment]
Hi @noname2327 - I think this is a technical question but not an issue in Zammad. Please refer to our http://community.zammad.org/ board.

JFI: I think you forgot to change the email on the right side of the "Email Account" block which is not visible in the screenshot you provided. The one left to the "Edit" button on the right side of the screenshot. Hope this helps.
