### ISSUE TITLE
Mail channel: Multiple blanks are collapsed -> content is rendered unusable/unreadable

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#1881]
### Infos:

* Used Zammad version: 2.2.0-1513786667.dbad0f53.jessie
* Installation method (source, package, ..): Deb from repository
* Operating system: Deibian 8 jessie
* Database + version:MySQL 5.5.58
* Elasticsearch version: 5.6.5
* Browser + version: Firefox ESR 52.6.0

### Expected behavior:

Ticket sent by mail looks like:

![qp_mail_mail](https://user-images.githubusercontent.com/279232/37661529-519cc518-2c55-11e8-8264-96021864749b.png)

### Actual behavior:

Ticket sent by mail looks like:

![qp_mail_zammad](https://user-images.githubusercontent.com/279232/37661550-5ab38254-2c55-11e8-816e-097049753cc4.png)

### Descripton:

We often receive such tabular data in html mails and collapsing the blanks renders the structured content useless.  In the described case the mail is a quoted-printable multipart message with a text/plain part and a text/html part.  I can provide the original mail directly to an assigned developer if required.

**Comment by thorsteneckel** [comment]
This works as intended. Zammad does and will not support monospaced fonts, which are required for displaying such texts. You can use the "view original message" functionality for having a look at the original text.

**Comment by fthommen** [comment]
"view original message" is not an option for daily work when you receive multiple such mails per day!  Why is Zammad so reluctant to support that?  Couldn't zammad just take the html part of the mail and display it as such?  That's what I would expect from a ticketing system which only supports html mails.

**Comment by martini** [comment]
@fthommen can you attach an example email? I'll have an look on it. Maybe Zammad is "optimising" the html structure to much.

**Comment by fthommen** [comment]
@martini sorry, was busy with other stuff recently.  I'd rather not have this information public.  Is there a way to have it sent to you personally?
