### ISSUE TITLE
System removes owner from open tickets after around 15 minutes

### ISSUE THREAD

**Issue by dougvil** [zammad/zammad#1888]
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): Docker
* Operating system: Ubuntu 16.04
* Database + version: Postgres 9.4
* Elasticsearch version: latest
* Browser + version: Google Chrome 65.0.3325.181

### Expected behavior:
Keep the ticket Owner on open tickets.
*

### Actual behavior:
After around 15 minutes the system auto removes Owner from Open tickets, leaving empty ( '-' ).
*

### Steps to reproduce the behavior:
Create a new ticket;
Set an user as Ticket Owner;
Update ticket leaving state Open;
Waits around 15 minutes;
The Ticket will be auto updated and the Owner will be empty.

See the log from a test ticket:
![example](https://user-images.githubusercontent.com/13039225/37734870-36dec326-2d2b-11e8-8d85-f35ff5d78180.jpg)
*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by monotek** [comment]
Do you use the single container docker image?

Be aware that it's only meant for testing purposes. An update or restart of the container means you'll lose all your data.

**Comment by dougvil** [comment]
I've installed by following this article:
https://docs.zammad.org/en/latest/install-docker-compose.html

I run Zammad with "docker-compose up -d" and, even after reboot, the data still there.

According to the article above, the container uses Stable version of zammad repo.

Seems like a trigger is executing between 10 and 15 minutes, removing the Owner from tickets where state is Open.

**Comment by monotek** [comment]
I was talking about the single container image from: https://github.com/zammad/zammad-docker

So no problem.

Can't help with your actual problem.

**Comment by dougvil** [comment]
Ok!
I'm new at Docker, and new with zammad too.

Thanks anyway!

**Comment by dougvil** [comment]
Problem solved. 
On Groups there's an option to set Timeout for tickets to be unnasigned if the Agent don't work on that in X minutes.

**Comment by martini** [comment]
Wonderful! Thanks for feedback!

**Comment by monotek** [comment]
@martini 
does this default to 15 min?

**Comment by martini** [comment]
@monotek no, per default the value is empty and not auto unassignment (Totmannschaltung) is active.

<img width="694" alt="screen shot 2018-03-22 at 13 26 09" src="https://user-images.githubusercontent.com/110226/37770413-a0ac3ae6-2dd4-11e8-94e6-7d70251394b6.png">

**Comment by sensudipta** [comment]
> Problem solved. On Groups there's an option to set Timeout for tickets to be unnasigned if the Agent don't work on that in X minutes.

Thank You so much. It was driving me crazy for a whole day.
