### ISSUE TITLE
Missing identifier attribute on LDAP entry causes Sync to fail

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1891]
Hihi 👋 

since a few zammad-updates ago with get an error with our LDAP-sync. Sadly I don't know excatly since when.
### Infos:
* Used Zammad version: 2.3.0-1520582300.fdc0abbe.xenial
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04 LTS
* Database + version: psql (PostgreSQL) 9.5.10
* Elasticsearch version: 5.5.1
* Browser + version: Firefox 59.0.1 (64-Bit)

Everytime zammad tries to sync with our eDirectory we get the following error after syncing 2 users:
'undefined method `ascii_only?' for nil:NilClass'

here are our ldap-setting:

Name | Wert
-- | --
LDAP Host | ldaps://172.16.230.70
Base DN | o=bug
Bind Benutzer | cn=zamauth,o=bug
Bind Passwort | f*************ry
UID | uid
User Filter | (objectclass=person)
GID | dn
Group Filter | (objectClass=groupOfUniqueNames)

LDAP | Zammad
-- | --
uid | login
givenname | firstname
sn | lastname
mail | email
telephonenumber | phone
title | title

LDAP | Zammad
-- | --
cn=zam_admin,ou=its,o=bug | Admin-ITS
cn=zam_user,ou=its,o=bug | Agent-ITS

Greetings

**Comment by thorsteneckel** [comment]
Hi @MamoulianDelacroix ! Thanks for reporting this. Can you please check your `log/production.log` file for the occurrences of `undefined method `ascii_only?' for nil:NilClass`? There should be a long traceback error. Please post this here so we ca see where it's coming from 👀

**Comment by MamoulianDelacroix** [comment]
Hi @thorsteneckel:
the log is attached.
[production.log](https://github.com/zammad/zammad/files/1837606/production.log)
I hope it has alle necessariy informations, if not I can upload the whole file.

Greetings

**Comment by thorsteneckel** [comment]
Hi @MamoulianDelacroix - Thanks! It looks like there was an issue before that that causes this part to fail. Could you please provide the linkes before this block, too? I would even take the whole file :)

**Comment by MamoulianDelacroix** [comment]
Hi @thorsteneckel - no problem 😃 
here is the whole file.
[production.log](https://github.com/zammad/zammad/files/1837709/production.log)

**Comment by thorsteneckel** [comment]
Thanks! I was able to find the issue: The configured (auto detected) LDAP identifier attribute `uid` is not present for an LDAP entry. Not finding the attribute causes an error which is not bad per se because Zammad should handle this properly and skip the entry and mark it as `failed` in the statistics. However, this handling fails at a later point.

My stack is currently pretty full and I won't be able to work on this until somewhere end of next week. In the meantime you can replace the following two files with the ones I provide:

`lib/sequencer/unit/import/common/mapping/flat_keys.rb`
`lib/sequencer/unit/import/ldap/user/remote_id/unhex.rb`

[1891.zip](https://github.com/zammad/zammad/files/1837750/1891.zip)

Hope this helps as a temporary workaround.

**Comment by MamoulianDelacroix** [comment]
Hi @thorsteneckel : no problem 😄 
We can wait.

I just tried your workaround. I replaced these two files and restarted zammad.
Now I get the following error
`An error occurred: undefined method [] for nil:NilClass`😆 

attachet the new production.log.
[production.log](https://github.com/zammad/zammad/files/1837824/production.log)

Like I said, it can wait until in 2 weeks, we have time 😄

**Comment by thorsteneckel** [comment]
Seems to be a deeper issue 🙈 Ok, read you then. Thanks for your support 👍

**Comment by MamoulianDelacroix** [comment]
hihi 👋 
are there any news regarding this bug?
Greetings

**Comment by thorsteneckel** [comment]
Currently not. We are busy with tasks for our paying customers. I'll let you know when it's ready. Thanks for your understanding.

**Comment by thorsteneckel** [comment]
Hi @MamoulianDelacroix - I had the time to fix the issue with the commits above. The package of the develop branch will be available in ~30 minutes from now. Feedback is appreciated. Closing now.

**Comment by MamoulianDelacroix** [comment]
Sorry for the stupid question, but the packages should be in the stables version now?
I just did an zammad update to version 2.4.0-1524669850.7e3a10af.xenial amd64 and still have the problem.

**Comment by thorsteneckel** [comment]
This is not in stable but only develop since we changed some files.

**Comment by MamoulianDelacroix** [comment]
Thanks for clearing things up 😄 
So I have to wait since I don't have a test / development-enviremoment for zammad

**Comment by MamoulianDelacroix** [comment]
Zammad 2.5 works like a charm! 🎉 
Our problem is gone, thanks a lot! 😄
