### ISSUE TITLE
scheduler not running

### ISSUE THREAD

**Issue by CyberPunk2042** [zammad/zammad#1893]
### Infos:

* Used Zammad version: v2.2.x
* Installation method (source, package, ..): Rancher-Docker-compose
* Operating system: Debian
* Database + version: Postgresql 9.6
* Elasticsearch version:
* Browser + version: Chrome

### Actual behavior:

*We are having issues with scheduler 
![errer22](https://user-images.githubusercontent.com/36038814/37768878-2e61dcb4-2de0-11e8-8178-39014f2580b2.PNG)

During low activities, no errors but after few hours with high activities by users during a day scheduler stop working without errors

We have to restart Zammad and reindex ES but it takes so long

22.03.2018 0:23:50initialising / updating database...
22.03.2018 0:24:26changing settings...
22.03.2018 0:24:32rebuilding es searchindex...
22.03.2018 1:36:49drop indexes...
22.03.2018 1:36:49create indexes...
22.03.2018 1:36:49reload data...
22.03.2018 1:36:49 reload User
22.03.2018 1:36:49  - started at 2018-03-21 21:24:37 UTC
22.03.2018 1:36:49  - took 283 seconds
22.03.2018 1:36:49 reload Organization
22.03.2018 1:36:49  - started at 2018-03-21 21:29:20 UTC
22.03.2018 1:36:49  - took 0 seconds
22.03.2018 1:36:49 reload Ticket
22.03.2018 1:36:49  - started at 2018-03-21 21:29:21 UTC
22.03.2018 1:36:49  - took 4048 seconds

And we have high CPU load on core 1 out of 24 even though in Rancher it set for 24 Cores
Is any way how we can utilize more cores?

Yes, I'm sure this is a bug and no feature request or a general question.

**Comment by monotek** [comment]
Linking sheduler ticket https://github.com/zammad/zammad-docker-compose/issues/55 for reference.

Added new issue to disable es reindex when updating: https://github.com/zammad/zammad-docker-compose/issues/66

**Comment by monotek** [comment]
closing in favor of https://github.com/zammad/zammad-docker-compose/issues/55 as this is not the right project issue tracker.
