### ISSUE TITLE
Image of E-Mail content doesn't display right

### ISSUE THREAD

**Issue by eberweinlu** [zammad/zammad#1895]
### Infos:

* Used Zammad version: 2.3.X
* Installation method: DEB
* Operating system: Debian 8
* Database + version: PostgreSQL 9.4
* Elasticsearch version: 5.6.8
* Browser + version: Firefox

### Expected behavior:

* Displaying image

### Actual behavior:

* Image of mail doesn't display right when sent to customer

![grafik](https://user-images.githubusercontent.com/37696119/37826832-5bc51d46-2e95-11e8-9380-bd32f19a3e82.png)

### Steps to reproduce the behavior:

* I set up a Trigger with an execution which sends a mail to the customer
* I pasted the image via drag & drop into the mail body

![grafik](https://user-images.githubusercontent.com/37696119/37826947-be210b80-2e95-11e8-9853-3211f15da121.png)

**Comment by muhammadn** [comment]
@eberweinlu I didn't do drag and drop but copy pasted from an image viewer. 

The image (eg. png) is stored as a base64 encoded data and saved on the backend. I have created a trigger as well, pasted the image in, emailed and saw zammad's support reply with the image as well.

What email client were you using? Is your email client able to read (process) base64 encoded data? 

(I am using Apple Mail)

**Comment by muhammadn** [comment]
This issue is reproducible when the user's client is using gmail.

**Comment by eberweinlu** [comment]
Currently we're using Outlook 2010 Client. The encoding works perfectly fine.
So i tested some variants.

First of all I also tested the gmail web client. Same result. The image won't display.

![image](https://user-images.githubusercontent.com/37696119/38491518-6218f514-3bec-11e8-92dc-f126ff078338.png)

Then I started encoded a picture into base64. The encoding works fine.
My base64 code was similar to the zammad ones.

Secondly I put the code into a HTML file and display it via browser. Also works fine.
![image](https://user-images.githubusercontent.com/37696119/38488662-72c2c6fe-3be4-11e8-95e5-247ad9d311f3.png)
So the displaying in the browser is not the problem.

Our IT-Manager told us that the mail filetype was sent as "txt".
At first glance i didn't find anything. Just a normal HTML file. See top right.
![image](https://user-images.githubusercontent.com/37696119/38487952-309ab112-3be2-11e8-8ce5-e27771677a70.png)

Then I found something interesting. 
In my case i can't paste pictures into the "Trigger-Editor". I can only move them via drag and drop.
In some cases the images just disappears and the Trigger don't save after hitting the save button.
But this happens only when the Trigger is filled with an image and no text.
I tested all these browsers: Microsoft Internet Explorer, Firefox, Chrome.
None of them could paste the image.

Is there a problem with certain browsers?
I really didn't find anything.

**Comment by muhammadn** [comment]
@eberweinlu It is fixed in our `develop` branch - https://github.com/zammad/zammad/commit/f8adf31ec67783698391fd2e70fd80f876645dfe

Just came in few hours ago. You can try out from source code or wait for Zammad 2.4.1 🤓

**Comment by muhammadn** [comment]
@eberweinlu Just to add on the issue. Why it works on your browser and not your email client like gmail or outlook 2010 is expected. 

Gmail or Outlook 2010 does not allow any base64 encoded data to be embedded in emails. So we used 'Content ID' which will work across all email clients.

**Comment by eberweinlu** [comment]
Well done. I installed it with source and it's working perfect.
You all did a great job.
Can't wait for Zammad 2.4.1. release.

Keep it up! :smile: :+1:
