### ISSUE TITLE
Borrar un ticket desde la base

### ISSUE THREAD

**Issue by Fabiola-ZC** [zammad/zammad#1903]
Quiero borrar unos tickets de prueba desde la base, intente el borrado de un ticket utilizando las tablas Tickets y ticket_articles borre el ticket, pero al intentar iniciar sección con el cliente que levanto ese ticket  zammad me manda un error (Couldn't find ticket with id = 142), necesito borrarlo de otra tabla? o en que me equivoque? 

Me puede ayudar.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. The issue tracker language is english. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.
