### ISSUE TITLE
X-Zammad-Ignore Header found but no such Header present

### ISSUE THREAD

**Issue by sthag** [zammad/zammad#1906]
### Infos:

* Used Zammad version: 2.3
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: MySQL 5.7
* Elasticsearch version: 5.6.7
* Browser + version: Firefox und Chrome (latest stable)

### Expected behavior:

* Icinga2 email is processed and not ignored.

### Actual behavior:

* Icinga2 email is ignored and dropped because of x-zammad-ignore header.
* But there is no x-zammad-ignore header.

This is the zammad production.log message:
```
[2018-03-29T09:51:21.034523 #899]  INFO -- : ignored email with msgid '<20180329075114.67821800B00@server>' from 'postmaster@company.de' because of x-zammad-ignore header
```

This is the email:
```
Return-path: <postmaster@company.de>
Envelope-to: zammad@company.de
Delivery-date: Thu, 29 Mar 2018 09:51:15 +0200
Received: from [78.47.166.52] (helo=sslproxy04.provider.de)
	by www265.provider.de with esmtpsa (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85_2)
	(envelope-from <postmaster@company.de>)
	id 1f1SL5-0005H3-CH
	for zammad@company.de; Thu, 29 Mar 2018 09:51:15 +0200
Received: from [213.61.25.212] (helo=server)
	by sslproxy04.provider.de with esmtpsa (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.84_2)
	(envelope-from <postmaster@company.de>)
	id 1f1SL5-00083L-6E
	for zammad@company.de; Thu, 29 Mar 2018 09:51:15 +0200
Received: by server (Postfix, from userid 113)
	id 67821800B00; Thu, 29 Mar 2018 09:51:14 +0200 (CEST)
Subject: [CUSTOM] Host id-12345 + INTERN: Company + Deutschland is UP!
To: <zammad@company.de>
X-Mailer: mail (GNU Mailutils 2.99.99)
Message-Id: <20180329075114.67821800B00@server>
Date: Thu, 29 Mar 2018 09:51:14 +0200 (CEST)
From: postmaster@company.de
X-Authenticated-Sender: smarthost@company.de
X-Virus-Scanned: Clear (ClamAV 0.99.3/24430/Thu Mar 29 06:23:16 2018)
Delivered-To: zammad@company.de

***** Host Monitoring on server *****

id-12345 + INTERN: Company + Deutschland is UP!

Info:    PING OK - Packet loss = 0%, RTA = 8.08 ms

When:    2018-03-29 09:51:13 +0200
Host:    id-12345 + INTERN: Company + Deutschland
Test:    server
IPv4:	 10.0.0.1

Comment by username:
  Test
```

### Steps to reproduce the behavior:

* I can only find ignored messages which come from Icinga2, no other email is ignored
* It happens kind of sporadically
* Most of the time emails get processed and are not ignored
* I tested mostly with custom notifications but default problem or recovery notifications also get ignored from time to time

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @sthag !

This probably works as intended. Zammad [sets this header](https://github.com/zammad/zammad/blob/develop/app/models/channel/filter/monitoring_base.rb#L129) for [recovery states](https://github.com/zammad/zammad/blob/develop/app/models/channel/filter/monitoring_base.rb#L21)
 if [no open/issue Ticket for the host could be found](https://github.com/zammad/zammad/blob/develop/app/models/channel/filter/monitoring_base.rb#L106).

Is there [an existing open ticket for this host that should be matched](https://github.com/zammad/zammad/blob/develop/app/models/channel/filter/monitoring_base.rb#L85)?

**Comment by sthag** [comment]
Hi @thorsteneckel 

Thanks for the quick answer. Sorry for posting if it is not a bug.

This must be it. Problem is that I currently have an [open issue](https://community.zammad.org/t/icinga-integration-merges-wrong-tickets-and-cannot-autoclose/290) with Icinga messages which cannot be matched to the correct previous message.
So these two things correlate.

**Comment by thorsteneckel** [comment]
Could you please migrate the forum post, which is actually a bug, to an issue and refer to this issue here? The forum post will probably get closed automatically soon and I have no information that somebody is actively working on it. Since it's a bug we can reproduce there should be an issue for it. Thanks 👍
