### ISSUE TITLE
Can't create ticket on behalf user with type email

### ISSUE THREAD

**Issue by sheLbyPL** [zammad/zammad#1909]
### Infos:

* Used Zammad version: 2.4.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: mysql
* Elasticsearch version: 5.6.8
* Browser + version: chrome

### Expected behavior:

* When creating ticket by api on behalf of user with type: email it should be created with type email, not note.
What's weird, when ticket is created by admin, it's correctly set as email type.

Note:
I'm using email type because i need cc field, and seems that it works only here. Is it possible to implement cc field for web type maybe?

**In addition, when I'm creating ticket with email type, SLA is not triggered at all, but when type is web or note it's fine.**

### Actual behavior:

* It's created with note type when set to email. When I change it to "web", it's created as web ticket correctly.

### Steps to reproduce the behavior:

* use:
curl -u test@zammad.com:test123 -H "Content-Type: application/json" -H "X-On-Behalf-Of: user-login" -X POST -d '{"title":"Help me!","group": "Users","article":{"subject":"some subject","body":"some message","type":"email","internal":false},"customer":"email_of_existing_customer@example.com","note": "some note"}' https://xxx.zammad.com/api/v1/tickets

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @sheLbyPL 

what permissions has the user `user-login `?

```
zammad run rails r 'p User.find_by(login: 'user-login').permissions'
```

 -Martin

**Comment by sheLbyPL** [comment]
Hi @martini

My user-login has following permissions:

=> {"user_preferences.avatar"=>true, "ticket.customer"=>true}

**Comment by martini** [comment]
Hi @sheLbyPL 

thanks for feedback, that's the reason why article type "email" is not working. A customer can send emails only via email channel.

What permissions has the user "test@zammad.com"?

 -Martin

**Comment by sheLbyPL** [comment]
Thanks for your answer @martini 

"test@zammad.com" user:
{"admin"=>true, "report"=>true, "user_preferences.access_token"=>true, "user_preferences.avatar"=>true, "user_preferences.calendar"=>true, "user_preferences.language"=>true, "user_preferences.linked_accounts"=>true, "user_preferences.notifications"=>true, "user_preferences.out_of_office"=>true, "user_preferences.password"=>true, "chat"=>true, "cti.agent"=>true, "ticket.agent"=>true, "chat.agent"=>true}

Is there any way to set email type for non-admin users? Or maybe to enable CC support in for example web type?

**Comment by muhammadn** [comment]
@sheLbyPL currently is it not possible for email type.

**Comment by sheLbyPL** [comment]
@muhammadn 
Thanks for your reply. Unfortunately CC feature is very important in my case, so I guess i still have to use config user to create tickets :(

Is there any chance for fix/change or workaround that create ticket on behalf user could work together with CC option?
I would be very grateful, thanks in advance for your support.

**Comment by thorsteneckel** [comment]
Hi @sheLbyPL - please describe your use case. Maybe there is a different approach/solution for your case.

**Comment by sheLbyPL** [comment]
Hi @thorsteneckel 

My use case looks as following:

Outlook addon - I made an outlook addon which in fact is a php/html form embedded into sidebar in outlook.
![image](https://user-images.githubusercontent.com/7706996/38296226-00c1c826-37f1-11e8-9f31-2b24f4503f7e.png)

It has CC field which is not required, but it's very often used by our employees (ticket system is made for our employees, not clients) - they often have to put their manager/ some other people in cc so we can actually proceed with their changes/requests.

Zammad api connection is based on https://github.com/zammad/zammad-api-client-php

Some time ago I requested the implementation of "create on user behalf" to get rid of wrong user in notifications - my outlook addon automatically reads actually logged in user mail address and sets it as customer. It's fine, tickets are set correctly to the users that sent them, the only problem were notifications which show "Ticket created by (api login user)".

Now after 2.4.x release I finally got a chance to test "on behalf feature" in action, but unfortunately non-admin users (so all our employees) can't send ticket correctly by the form anymore - email type is no longer working when sent on behalf of user - it's type "note" automatically, and it doesn't support CC (as any other type - please correct me if I'm wrong)

I spent a lot of time on implementing this outlook form and employees got very used to it, so I hope there's something that can be done so both cc and "on behalf" work together. :(

Thanks!

**Comment by muhammadn** [comment]
@sheLbyPL I am working on an enhancement on this. 

So basically my fix is that you will need to set `X-On-Behalf-Of` in the configuration with  `'type' => 'email'` in the article.

@sheLbyPL  example if you use our official php library:
```php
<?php
  require_once 'vendor/autoload.php';
  use ZammadAPIClient\Client;
  use ZammadAPIClient\ResourceType;

  $client = new Client([
      'url'           => 'http://localhost:3000', // URL to your Zammad installation
      'username'      => 'myaccount@zammad.com',  // Username to use for authentication
      'password'      => 'mypassword',           // Password to use for authentication
      'debug'         => true,                // Enables debug output
  ]);

  $client->setOnBehalfOfUser('staffuser@example.com');

  $ticket_text = 'API test ticket On Behalf';
  $ticket_data = [
      'title'            => $ticket_text,
      'customer'         => 'staffuser@example.com',
      'group'            => 'Users',
      'article'          => [
          'from'         => 'Users',
          'subject'      => $ticket_text,
          'body'         => $ticket_text,
          'cc'           => 'staffuser2@example.com',
          'to'           => 'staffuser3@example.com',
          'from'         => 'staffuser@example.com',
          'type'         => 'email',
      ],
  ];

  $ticket = $client->resource(ResourceType::TICKET);
  $ticket->setValues($ticket_data);
  $ticket->save();
```

**Comment by muhammadn** [comment]
@sheLbyPL 

Here's an update: You can use the CC field (which will appear in the tickets on zammad's frontend) but you will need to use `'type' => 'web'` (not 'email' as i had mentioned earlier)

This should work with Zammad version 2.4 so my enhancements are unnecessary.

```
<?php
  require_once 'vendor/autoload.php';
  use ZammadAPIClient\Client;
  use ZammadAPIClient\ResourceType;

  $client = new Client([
      'url'           => 'http://localhost:3000', // URL to your Zammad installation
      'username'      => 'myaccount@zammad.com',  // Username to use for authentication
      'password'      => 'mypassword',           // Password to use for authentication
      'debug'         => true,                // Enables debug output
  ]);

  $client->setOnBehalfOfUser('staffuser@example.com');

  $ticket_text = 'API test ticket On Behalf';
  $ticket_data = [
      'title'            => $ticket_text,
      'customer'         => 'staffuser@example.com',
      'group'            => 'Users',
      'article'          => [
          'from'         => 'Users',
          'subject'      => $ticket_text,
          'body'         => $ticket_text,
          'cc'           => 'staffuser2@example.com',
          'to'           => 'staffuser3@example.com',
          'from'         => 'staffuser@example.com',
          'type'         => 'web',
      ],
  ];

  $ticket = $client->resource(ResourceType::TICKET);
  $ticket->setValues($ticket_data);
  $ticket->save();
```

This should work as you want. I will close this issue and if you still have some other problems, i will reopen this issue.

**Comment by pgodzwa** [comment]
@muhammadn Thanks for your reply.
Unfortunately it's not working as it should - person that is in cc field doesn't receive email (so when user sends ticket, person in cc should receive this mail too - with type web it doesn't work)

Could you fix that it also sends mail to cc people when type is web? Then it would be all good.

Thanks!

**Comment by pgodzwa** [comment]
@muhammadn 
Could you reopen it? I just don't want it to get lost somewhere in closed issues ^^
Thanks!

**Comment by muhammadn** [comment]
@sheLbyPL email type is specifically designed for emails (ie. interacting with email server) and not via API. 

My recommendation is to use 'to' field to include the necessary emails with the web type if you need to send email to other people.

**Comment by rlue** [comment]
Thanks so much for your patience, @sheLbyPL.

First off, I just want to confirm that I'm understanding your issue correctly. You've written an Outlook add-on that allows employees to create new IT support tickets in Zammad. This add-on creates tickets via the REST API rather than actually sending an email.

Originally, the problem was that the newly created tickets were of the wrong "type" – that is, you wanted them to be email tickets, but they would appear as notes. Then, @muhammadn helped you out with that by suggesting that you use the `X-On-Behalf-Of` header, setting the value to `'type' => 'web'`. This mostly solved the problem, and now, the only place your workflow is broken is that the "Cc" field of your new ticket form doesn't work – that is, "Cc" recipients don't receive emails at all.

Is that all correct?

If so, then unfortunately, that's exactly how the REST API is supposed to behave. We can't support Cc on outgoing email for tickets created via the REST API because of the potential for abuse – basically, it would allow a mailicious actor to use Zammad as a platform to disseminate spam.

As an alternative, would it be possible for you set up your automated form to create new Zammad tickets via actual emails, rather than the REST API? This is what Zammad is built to do, and what it does best.

---

**Tip:** I notice that one of the fields in your "new ticket" form is a "type" dropdown with values with "Problem". If your reason for creating tickets via the REST API is to set this value automatically when the employee creates the ticket, then I might suggest using custom email headers to do this, as well. You can actually set any Ticket attributes via email headers using the following format:

```
X-Zammad-Ticket-<attribute>: <value>
```

So, for instance, a `X-Zammad-Ticket-priority: 3 high` email header would automatically set the priority on a new ticket.
