### ISSUE TITLE
Move ticket color generator to REST backend

### ISSUE THREAD

**Issue by martini** [zammad/zammad#191]
Currently the ticket color is generated in the web app. To keep color generation consistent across different app/frontends, we need to move it to REST backend and deliver it as ticket attribute.

```
  getState: ->
    type = App.TicketState.find( @state_id )
    stateType = App.TicketStateType.find( type.state_type_id )
    state = 'closed'
    if stateType.name is 'new' || stateType.name is 'open'
      state = 'open'

      # if ticket is escalated, overwrite state
      if @escalation_time && new Date( Date.parse( @escalation_time ) ) < new Date
        state = 'escalating'
    else if stateType.name is 'pending reminder'
      state = 'pending'

      # if ticket pending_time is reached, overwrite state
      if @pending_time && new Date( Date.parse( @pending_time ) ) < new Date
        state = 'open'
    else if stateType.name is 'pending action'
      state = 'pending'
    state
```

**Comment by martini** [comment]
@hanneshal Do you remember this issue? I tried to do so, but it has a difficult behaviour. Moved the ticket color to the backend is raising an issue which I do not know to handle. Here the use case:

1) Let's say a background job to change the ticket color is running every 5 min.
2) So if a ticket in the UI is escalated right now, the ticket color is changing in 5 min. -> So 5 min. the color is shown wrong in the UI.

Solutions:
1) Let's run the background job all the time (which leads to heavy load at the backend)
or
2) Let's do it in the UI

Any other ideas?

**Comment by rkaldung** [comment]
> On Nov 29, 2016, at 4:18 PM, Martin Edenhofer <notifications@github.com> wrote:
> 
> 	• Let's say a background job to change the ticket color is running every 5 min.
> 

Is this job calculating the escalation or just the color? I thought that the color is a setting :-/

- Roy

**Comment by dominikklein** [comment]
I will close the issue as not planned, because ticket information which should be calculated related to a date time should be done in a reactive way on the frontend side.
