### ISSUE TITLE
How to run FillDB.Load

### ISSUE THREAD

**Issue by CyberPunk2042** [zammad/zammad#1911]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): Docker
* Operating system: Windows 10
* Database + version:
* Elasticsearch version:
* Browser + version: Chrome

Hello!

I have a question regarding FillDB
How can I load test Tickets?

And one more question how can I download all records?
In reporting it says 30000 thousand but it downloads only 1000.
How can I change limit?

Thank You

### Expected behavior:

*rails 'FillDB.load(10,10,10,10,2000)'

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

Taken directly from [the documentation in the file](https://github.com/zammad/zammad/blob/develop/lib/fill_db.rb#L8):

```
  FillDB.load(
    agents: 50,
    customers: 1000,
    groups: 20,
    organizations: 40,
    overviews: 5,
    tickets: 100,
  )
```

Regarding  printed reporting records: [It depends on your used reporting profile and adapter](https://github.com/zammad/zammad/blob/develop/app/controllers/reports_controller.rb#L88). All available adapters can be found [here](https://github.com/zammad/zammad/tree/develop/lib/report).
