### ISSUE TITLE
Cannot use ticket templates since 2.4 anymore

### ISSUE THREAD

**Issue by sthag** [zammad/zammad#1913]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): deb package
* Operating system: Ubuntu 16.04
* Database + version: MySQL 5.7
* Elasticsearch version: 5.6.8
* Browser + version: Firefox & Chrome latest

### Expected behavior:

* I create a new ticket
* I select a template and hit apply
* The template is selected and used for the ticket

### Actual behavior:

* The template is not used
* nothing happens (no log entry on server or client)

### Steps to reproduce the behavior:

* Create a new template
* Select this template for a new ticket

* It is possible to create new templates (log looks normal)
* It is also possible to delete templates

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @sthag - thanks for reporting! A fix is on its way - currently in QA.
JFI: The bug affects every action pre-filling the tickte create view (template, split etc.).

**Comment by thorsteneckel** [comment]
This is fixed with the commits above. The new release is ready to install in ~30 minutes from now. Feedback would be great 👍 Closing for now 🚀

**Comment by AchuM** [comment]
I can confirm this update fixed the issue.  Thanks!
