### ISSUE TITLE
Exporting Ticket threads

### ISSUE THREAD

**Issue by pdshilling** [zammad/zammad#1915]
Hi,

Is it possible to export each closed ticket as a word doc or pdf?

Thanks

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a (technical) question. You can ask questions over at https://community.zammad.org/ - Closing now.

You can use the reporting functionality to define report profiles and export them as Excel sheets.

**Comment by pdshilling** [comment]
Thanks and sorry about that.
