### ISSUE TITLE
Reply and forward is not appearing in version 2.4.x

### ISSUE THREAD

**Issue by victorcezario** [zammad/zammad#1916]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: mysql
* Elasticsearch version: 
* Browser + version: 

### Expected behavior:
Appear as answer and forward options

### Actual behavior:

![image](https://user-images.githubusercontent.com/19748477/38274076-065287c2-3764-11e8-857d-b78c24a037f1.png)

### Steps to reproduce the behavior:

http://helpdesk/#ticket/zoom/<id>

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @victorcezario - this one is a classic. Please check the configuration of the Group the Ticket is currently in. I guess there is no email address configured for this Group. So if no is configured all Email-Actions are hidden.

I ran into it multiple times myself. It's on our list of UX improvements 👍

**Comment by victorcezario** [comment]
@thorsteneckel it works ! Thank you !
