### ISSUE TITLE
Elasticsearch don't work after downgrade from 6.2.3 to 5.6.8

### ISSUE THREAD

**Issue by Trenga** [zammad/zammad#1918]
### Infos:

* Used Zammad version: 2.3.1-1522274310.238784 
* Installation method (source, package, ..): deb
* Operating system: Debian 8.8
* Database + version: 9.4+165+deb8u3
* Elasticsearch version: 6.2.3 to 5.6.8
* Browser + version: Firefox actual
* Java + version:  openjdk-8-jre:amd64 8u162-b12-1~bpo8+1 

Hi zammad community

What I did before:
-	uninstall elasticsreach 6.2 with
        dpkg -r  --force-depends elasticsearch
-	after that I installed Elasticsearch 5.6.8 as the zammad manual procedure
-	reboot etc.

Actual the Elasticsearch service will not run.
Please see the attached log file.
[elasticsearch.log](https://github.com/zammad/zammad/files/1875413/elasticsearch.log)

Thanks in advance.

**Comment by muhammadn** [comment]
Follow this guide here:

docs.zammad.org/en/latest/install-elasticsearch.html

It seems that you have not installed the ingest-attachment plugin.

This is more of a setup question not related to bug issues and not setup questions. For setup questions, please go to https://community.zammad.org

Thanks.

**Comment by Trenga** [comment]
Sorry it is:
root@DV-TicketCenter:~# /usr/share/elasticsearch/bin/elasticsearch-plugin list
ingest-attachment

**Comment by Trenga** [comment]
Thanks for help I was wrong. Have a great day.

**Comment by muhammadn** [comment]
@Trenga no problems. If you have setup issues you can go to our forums at https://community.zammad.org but in case you encounter a bug, just open an issue here. 😊
