### ISSUE TITLE
Elasticsearch service is running but zammad will not display any search result

### ISSUE THREAD

**Issue by Trenga** [zammad/zammad#1922]
Infos:

    Used Zammad version: 2.3.1-1522274310.238784
    Installation method (source, package, ..): deb
    Operating system: Debian 8.8
    Database + version: 9.4+165+deb8u3
    Elasticsearch version: 6.2.3 to 5.6.8
    Browser + version: Firefox actual
    Java + version: openjdk-8-jre:amd64 8u162-b12-1~bpo8+1

Hi zammad community

Depending of the old Issue:
Elasticsearch don't work after downgrade from 6.2.3 to 5.6.8 #1918

I have made a lot cleaning work on my system.
Then I have installed elasticsearch via the zammad manual.

So actually the elasticsearch service is running again.

Please see my attached log file:
[elasticsearch.log](https://github.com/zammad/zammad/files/1876320/elasticsearch.log)

The problem now is:
After restarting the services etc. Rebuilding the indexes etc as the manual.
I can't see a search result in zammad.

What I can do to analyse this problem?

Thanks in advance.

Greetings

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Thanks for closing @muhammadn .

**Comment by Trenga** [comment]
Thanks for help I was wrong. Have a great day.
