### ISSUE TITLE
System very slow, high ping at WebServer > 20sec, Network is okay

### ISSUE THREAD

**Issue by pixelflair** [zammad/zammad#1924]
**Infos:**
**Used Zammad version:** 2.3.
**Installation method (source, package, ..):** package
**Operating system:** ubuntu 16.04.4
**Database + version:** any
**Elasticsearch version:** 5.X
**Browser + version**: any
**Expected behavior:**
Fast response of the whole system.
**Actual behavior:**
The system & the webserver has high pings and the
employees can’t work as fast as possible. Sometimes it needs more than 20sec from “click” until the screen is updated…

This is a BIG Problem!

![image](https://user-images.githubusercontent.com/38098770/38356301-a96df156-38bf-11e8-8157-491328e76abe.png)

**Our nginx config:**
```

upstream zammad-railsserver {
server localhost:3000;
}

upstream zammad-websocket {
server localhost:6042;
}

server {
listen 80;

server_name WMS-CRM.exxellin.local;
server_name 10.181.201.238;

root /opt/zammad/public;

access_log /var/log/nginx/zammad.access.log;
error_log  /var/log/nginx/zammad.error.log;

client_max_body_size 50M;

location ~ ^/(assets/|robots.txt|humans.txt|favicon.ico) {
    expires max;
}

location /ws {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header CLIENT_IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 86400;
   proxy_pass http://zammad-websocket;
}

location / {
    proxy_set_header Host $http_host;
    proxy_set_header CLIENT_IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 300;
    proxy_pass http://zammad-railsserver;

    gzip on;
    gzip_types text/plain text/xml text/css image/svg+xml application/javascript application/x-javascript a$
    gzip_proxied any;
}
}


```

Our System @ VmWare:
![image](https://user-images.githubusercontent.com/38098770/38356651-98f7e84e-38c0-11e8-8582-2d7ff8bd384e.png)

The top of ubuntu:
![image](https://user-images.githubusercontent.com/38098770/38356660-9cdeb550-38c0-11e8-8af7-3a3a8c464ff6.png)

**Comment by thorsteneckel** [comment]
Hi @pixelflair ,

thanks for your comprehensive description. I think this is more a technical question than an Zammad issue in general. Could you please open a new topic at our community board over at https://community.zammad.org/ for this.

What I already can say: Please update to Zammad 2.4. We did some major performance improvements on different parts of the application.
After that check out your hardware if it matches [our recommendations](https://community.zammad.org/t/memory-usage-in-zammad/373/7).

You can address me directly over at the board if the update and hardware check doesn't fix it for you 👍

**Comment by martini** [comment]
@pixelflair Let me know if you created an community topic, I haves to share some feedback/infos/config for performance issues.

**Comment by pixelflair** [comment]
@martini  

https://community.zammad.org/t/high-latency-timeouts-tickets-twice/476/5

is the community topic.
