### ISSUE TITLE
No emails sent. How to test and send emails from command-line?

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1927]
Hello,
I have configured the email settings under `/#channels/email` and added an email which should send emails when a new ticket has been created, but unfortunately no emails are being sent. How can I test and send emails using commandline?
![email](https://user-images.githubusercontent.com/29798595/38416722-f106c124-3995-11e8-8f70-41c45f210378.png)

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.
