### ISSUE TITLE
bulk action is not executed for a pending-state

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#1930]
### Infos:

* Used Zammad version: 2.4.x
* Installation method (source, package, ..): hosted version
* Browser + version: Chrome Version 65.0.3325.181

### Expected behavior:

* In a bulk action, the pending status should be set and provided with a comment.

### Actual behavior:

* After you have set the settings for the desired bulk action and click on "update", the message "Bulk action executed" appears. Nevertheless, the field for the collective action settings remains and the settings have not been made.

### Steps to reproduce the behavior:

* Create 2 new tickets (status open/new, owner optional)

Then select both tickets in an overview and change settings:
z. B. Status = wait for close, priority = normal, group = equal, owner = equal

You can still confirm, but you can't update it afterwards when you have the opportunity to add a comment. Nothing's going to happen. In some cases, however, "Collection actions completed" appears at the top. However, the changes to the tickets were not applied.

The behavior could be traced with different users, on different clients and in different browsers.

Issue regarding T#1017304

**Comment by thorsteneckel** [comment]
Verfied:
<img width="656" alt="bildschirmfoto 2018-04-05 um 16 53 15" src="https://user-images.githubusercontent.com/3873515/38482457-ad07df26-3bcf-11e8-8a3b-1bc0ab500bd6.png">

**Comment by martini** [comment]
@mrflix 

![bulk_action_and_pending_time](https://user-images.githubusercontent.com/110226/39353661-a4f476b8-4a08-11e8-8c30-5e844fe617c8.gif)

**Comment by martini** [comment]
It's implemented for Zammad 2.5.
