### ISSUE TITLE
APP_RESTART_CMD not working

### ISSUE THREAD

**Issue by nilsrb** [zammad/zammad#1932]
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): rpm package
* Operating system: CentOS 7
* Database + version: postgresql  9.2.23
* Elasticsearch version: 5.5.2
* Browser + version: Chrome latest

### Expected behavior:

* After changing a field under "objects/user" for example a popup tells me to restart zammad or set environment variable to APP_RESTART_CMD="/path/to/your_app_script.sh restart to do it automatically. Setting this for the user zammad (the user running the zammad-service) should do the restart automatically.

### Actual behavior:

* Set APP_RESTART_CMD to a restart script. Script is working, when it is started manually as user zammad. But when things are changed via web-gui the popup is still there, suggesting me to set the environment variable. 

Variable is set:
env | grep restart
APP_RESTART_CMD=/home/zammad/restart.sh

### Steps to reproduce the behavior:

* Changing user details under objects/user which need zammad restarts.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by nilsrb** [comment]
APP_RESTART_CMD="systemctl restart zammad" didn't work for me :/

**Comment by nilsrb** [comment]
Yes, i am using bash, i put it in my .bashrc and it is not working. in "env" in can see that it is set. So for you this is working, when you change things in objects/users? Unfortunately i can't find any log entries, why this isn't working. 
Thanks

**Comment by monotek** [comment]
I guess your bashrc will not help as the Prozess runs as Zammad user

**Comment by nilsrb** [comment]
aaaah sorry for bothering, it's working now... of course this was the problem.
