### ISSUE TITLE
Can't find organization anymore after index rebuild

### ISSUE THREAD

**Issue by maggusf** [zammad/zammad#1933]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): package
* Operating system: CentOS
* Database + version: postgresql 9.2.23
* Elasticsearch version: 5.6.8
* Browser + version: Safari 11.1 (mac os)

### Expected behavior:

* can find organization 2

### Actual behavior:

* can't find organization 2, whether in search-box nor in edit user pane 
* all other organizations are working fine

### Steps to reproduce the behavior:

* did an elasticsearch index rebuild after that we got errors regarding this organization. 

Yes I'm sure this is a bug and no feature request or a general question.

production.log:
SNIP
E, [2018-04-09T17:41:27.536405 #8579] ERROR -- : 2018-04-09T17:41:27+0200: [Worker(host:zammad pid:8579)] Job BackgroundJobSearchIndex (id=1054439) FAILED (7 prior attempts) with RuntimeError: Unable to process POST request to elasticsearch URL 'http://localhost:9200/zammad_production/Organization/2?pipeline=zampipenew'. Check the response and payload for detailed information: 

Response:
#<UserAgent::Result:0x00007f469effc378 @success=false, @body=nil, @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">

Payload:
SNAP

**Comment by thorsteneckel** [comment]
Hi @maggusf could you please provide a step by step guide on how to reproduce this?

**Comment by maggusf** [comment]
1. have an organization in 2.3 with members having names with special characters as "ö", 'ä' or 'ü' (for example.
2. migrate to 2.4
3. rebuild index in elasticsearch
4. organization cannot be searched for anymore and errors come up within production.log

in addition: can upload complete production log if you need it (if it would help) but would have to mask names and infos ...

**Comment by maggusf** [comment]
currently everything is working fine. was switching some users to another organization, waited for organization to be stored successfully and switched them back. therefore I will have to get it broken again first. will try that in the evening hours today and come back to you

**Comment by maggusf** [comment]
tried the search already which is showing no output ... when executed within rails console I get the output ...
will try to get it broken as said in last comment, first ;)

**Comment by maggusf** [comment]
@martini was able to reproduce, your steps worked and helped to fix it! Thanks!

**Comment by martini** [comment]
Thanks for feedback @maggusf 

I'll write an migration to get executed in every installation at update time. So I reopen and close it later.
