### ISSUE TITLE
zammad-railsserver server.pid prevent container start

### ISSUE THREAD

**Issue by devel0** [zammad/zammad#1934]
### Infos:

* Used Zammad version: zammd-docker-compose ( b568b6782a122136dda0c8c9f48e275a5054279d @Mon Feb 5 20:20:23 2018 +0100 )
* Installation method (source, package, ..): git working copy docker cmopose
* Operating system: linux ubuntu 16.04
* Database + version: 
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* container restart successful

### Actual behavior:

* railsserver fail to restart

```
starting railsserver...
A server is already running. Check /opt/zammad/tmp/pids/server.pid.
=> Booting Puma
=> Rails 5.1.4 application starting in production 
=> Run `rails server -h` for more startup options
Exiting
starting railsserver...
A server is already running. Check /opt/zammad/tmp/pids/server.pid.
=> Booting Puma
=> Rails 5.1.4 application starting in production 
=> Run `rails server -h` for more startup options
Exiting
```

### Steps to reproduce the behavior:

* not sure what the cause, may a docker pause all container and docker unpause all containers

Yes I'm sure this is a bug and no feature request or a general question.

### Workaround

To avoid restart loop of the container should enough to remove stale pid file before to start the railsserver container. In my case I remove the file with following

```
rm -f /var/lib/docker/volumes/zammaddockercompose_zammad-data/_data/tmp/pids/server.pid
```

**Comment by monotek** [comment]
Wrong place. Please create issue in Zammad/Zammad-docker-compose

**Comment by devel0** [comment]
Done ( https://github.com/zammad/zammad-docker-compose/issues/60 )
