### ISSUE TITLE
Closing Time not refreshed

### ISSUE THREAD

**Issue by GreXXL** [zammad/zammad#1937]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): RPM
* Operating system: Ubuntu
* Database + version: bundled
* Elasticsearch version: 
* Browser + version: Safari 11.0.2

### Expected behavior:

* "Closed_at" refreshed if closed again

### Actual behavior:

* "Closed_at" not refreshed
![bildschirmfoto 2018-04-10 um 14 39 28](https://user-images.githubusercontent.com/1630413/38557449-6281f938-3ccd-11e8-99ae-429bcd26f9d4.png)

### Steps to reproduce the behavior:

* Create a ticket
* Close ticket
* Reopen ticket
* Close ticket

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
@GreXXL the close time in Zammad is always the first time where the ticket got closed.

**Comment by GreXXL** [comment]
Understood. That's why in #1938 it marks "Closing time" "has changed" red - shouldn't be available then I guess?

**Comment by GreXXL** [comment]
Added this information to the documentation: https://github.com/zammad/zammad-admin-documentation/pull/5

**Comment by martini** [comment]
> Understood. That's why in #1938 it marks "Closing time" "has changed" red - shouldn't be available then I guess?

For selecting / creating triggers it can be available. Because may you want to inform the customer if this field has been updated.

@GreXXL Thanks for the doc enhancement.
