### ISSUE TITLE
Safari Action Icon hidden

### ISSUE THREAD

**Issue by GreXXL** [zammad/zammad#1939]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): RPM
* Operating system: Ubuntu
* Database + version: bundled
* Elasticsearch version:
* Browser + version: Safari 11.0.2

### Expected behavior:

* Action Buttons (three dots) shown as eg. in Google Chrome

### Actual behavior:

* Action buttons not visible, still clickable / usable though
![bildschirmfoto 2018-04-10 um 14 46 36](https://user-images.githubusercontent.com/1630413/38557717-291b431a-3cce-11e8-9cbe-810c32e738eb.png)

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @GreXXL 

just tried to test it. And it works fine on my safari.

<img width="285" alt="screen shot 2018-04-10 at 14 54 36" src="https://user-images.githubusercontent.com/110226/38558097-6b1e2952-3ccf-11e8-96c2-bd2a0c2a8b23.png">
<img width="641" alt="screen shot 2018-04-10 at 14 54 27" src="https://user-images.githubusercontent.com/110226/38558099-6b3e090c-3ccf-11e8-8699-e3a333896e48.png">

PS: If you did an Update, try to clear your browser cache.

 -Martin

**Comment by GreXXL** [comment]
Interesting, but yes seems to have been my fault. After Cache deletion it works!

**Comment by martini** [comment]
Thanks for feedback!
