### ISSUE TITLE
no error message when trying to create ticket for incoming phone call from unknown

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#194]
I wanted to test wether #181 ist solved for me, when I hit another issue:
I tried to create a ticket for an incoming phone call. At that moment i didn't have an email address, so I simply entered the name of the caller (e.g. "Unbekannter Anrufer").
The UI didn't show any problem with that.
When I hit the button "erstellen" I get no hint whats wrong with the data I've entered.

**Comment by monotek** [comment]
"Invalid email of customer" error message is shown to me.
Closing.
