### ISSUE TITLE
Action in tables are not show correctly if record of row is inactive

### ISSUE THREAD

**Issue by martini** [zammad/zammad#1941]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* show actions also nice with inactive records

### Actual behavior:

* actions are shown grey

### Steps to reproduce the behavior:

* got to admin -> triggers -> per default 2 triggers are inactive and you will see it.

<img width="642" alt="screen shot 2018-04-10 at 14 55 58" src="https://user-images.githubusercontent.com/110226/38558245-ca402c0a-3ccf-11e8-880d-866c0c41273c.png">

**Comment by mrflix** [comment]
Are there cases where there is something else than plain text and links in a table row that has to be grayed out? Inactive rows can still be dragged and checked/unchecked, right? So those controls wouldn't have to be grayed out.

**Comment by martini** [comment]
Traffic ring lights an also be in front of a row (theoretical - but not in practice).

> Inactive rows can still be dragged and checked/unchecked, right? So those controls wouldn't have to be grayed out.

Yes. Thats fine for me.
