### ISSUE TITLE
LDAP Import stucks

### ISSUE THREAD

**Issue by eberweinlu** [zammad/zammad#1942]
### Infos:

* Used Zammad version: 2.4.X
* Installation method (source, package, ..): DEB
* Operating system: Debian 8
* Database + version: PostgreSQL 9.4.15
* Elasticsearch version: 5.6.8
* Browser + version: Chrome

Greetings everyone,

a few days ago I wanted to change something on the LDAP Import.
Than i saw that the LDAP Import stucks since early march.
Below you'll find my step I've already done.

### Expected behavior:

* LDAP Import working

### Actual behavior:

* LDAP Stucks:
![image](https://user-images.githubusercontent.com/37696119/38558555-cc146022-3cd0-11e8-844b-6a31fdafd017.png)

* Monitoring Info:
![image](https://user-images.githubusercontent.com/37696119/38558499-a4dedc08-3cd0-11e8-9883-9c70d2b95380.png)

#### Abort LDAP Import:
`irb(main):001:0> ImportJob.last.update_attribute('finished_at', Time.zone.now)`

`=> true`

#### Start new LDAP Import:
`irb(main):002:0> ImportJob.create(name: 'Import::Ldap', payload: Setting.get('ldap_config')).delay.start`

`=> #<Delayed::Backend::ActiveRecord::Job id: 150059, priority: 0, attempts: 0, handler: "--- !ruby/object:Delayed::PerformableMethod\nobject...", last_error: nil, run_at: "2018-04-10 13:38:18", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2018-04-10 13:38:18", updated_at: "2018-04-10 13:38:18">`

#### Status of LDAP Import (failed):
`irb(main):003:0> ImportJob.last.attributes.except('payload').inspect`

`=> "{\"id\"=>1045, \"name\"=>\"Import::Ldap\", \"dry_run\"=>false, \"result\"=>{\"skipped\"=>4, \"created\"=>0, \"updated\"=>0, \"unchanged\"=>0, \"failed\"=>501, \"deactivated\"=>0, \"sum\"=>505, \"total\"=>505, \"role_ids\"=>{3=>{\"skipped\"=>0, \"created\"=>0, \"updated\"=>0, \"unchanged\"=>0, \"failed\"=>487 , \"deactivated\"=>0, \"sum\"=>487, \"total\"=>0}}}, \"started_at\"=>Tue, 10 Apr 2018 13:38:23 UTC +00:00, \"finished_at\"=>Tue, 10 Apr 2018 13:38:57 UTC +00:00, \"created_at\"=>Tue, 10 Apr 2018 13:38:17 UTC +00:00, \"updated_at\"=>Tue, 10 Apr 2018 13:38:57 UTC +00:00}"`

#### Result still the same:
![image](https://user-images.githubusercontent.com/37696119/38558611-f1e54f8c-3cd0-11e8-974c-2d65e57e441d.png)

I also restarted our server and all Zammad services with no result.

(Followed the instruction of issue #1008)

**Comment by thorsteneckel** [comment]
Hi @eberweinlu - seems to me like there are (now) multiple stuck backends. Please make sure all LPAP syncs are stopped by running the following command on your Zammad rails console:

`ImportJob.where(name: 'Import::Ldap', finished_at: nil).update_all(finished_at: Time.zone.now)`

After doing so verify that there is currently no LDAP sync running in the LDAP admin interface.

After that is ensured please run: `ImportJob.create(name: 'Import::Ldap').delay.start`

Now there should be a new job running.

We are still investigating what causes this.

**Comment by eberweinlu** [comment]
Thanks for the quick response.

**Comment by schmanat** [comment]
I had the same issue, I got some help from the [community](https://community.zammad.org/t/ldap-sync-hangs-how-to-cancel/525/3) 

After this steps, the import works again. But I'm using Zammad v2.3
