### ISSUE TITLE
Status Zammad nach Update: /bin/sleep infinity

### ISSUE THREAD

**Issue by chrstmnn** [zammad/zammad#1945]
### Infos:

* Used Zammad version: 2.3 / 2.4
* Operating system: CentOS7
* Elasticsearch version: 5.6

### Expected behavior:
Installed and configured elasticsearch. After that Zammad worked fine.

Updated Zammad from 2.3 to 2.4. Since then Zammad is not reachable.
"systemctl status zammad" says:
`● zammad.service
   Loaded: loaded (/etc/systemd/system/zammad.service; enabled; vendor preset: disabled)
   Active: active (running) since Mi 2018-04-11 07:21:51 UTC; 5s ago
 Main PID: 7138 (sleep)
   CGroup: /system.slice/zammad.service
           └─7138 /bin/sleep infinity`

Tried to restore the backup before configuring elasticsearch and installing the update, but using your method I get following message:
`./zammad_restore.sh: Zeile 39: ammad: Kommando nicht gefunden.

# Zammad restored successfully - Mi 11. Apr 07:12:43 UTC 2018!`

Line 39 in zammad_restore.sh doesnt show "ammad" so I cannot find the mistake. Although restore is told to be successful, zammad is still not reachable.

Production.log is attached.
[production.log](https://github.com/zammad/zammad/files/1897684/production.log)

**Comment by muhammadn** [comment]
@chrstmnn When you try to access zammad, what is the error you get? 500? 400?

**Comment by chrstmnn** [comment]
I get 502 Bad Gateway

**Comment by muhammadn** [comment]
@chrstmnn what does `netstat -anp  |grep 3000` show?

**Comment by chrstmnn** [comment]
I dont know why, but after updating my ssl-zammad.conf of nginx was deleted. I now recreated the file, started nginx new without getting an error, but still 502.

netstat -anp |grep 3000 gives no output.

**Comment by chrstmnn** [comment]
Maybe the problem is with elasticsearch?
with systemctl status elasticsearch i get:
elasticsearch[1498]: which: no java in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)

**Comment by muhammadn** [comment]
elasticsearch is not the problem but you need elasticsearch. So you will need to install java and run elasticsearch.

Try `/usr/bin/zammad start` and see if there is any errors.

**Comment by chrstmnn** [comment]
I get:
`Usage:
  zammad run COMMAND [options]
  zammad scale TYPE=NUM
  zammad logs [--tail|-n NUMBER]
  zammad config:get VAR
  zammad config:set VAR=VALUE
  zammad configure
  zammad reconfigure
  zammad restart

Details:
  zammad configure [-f FILE|-]
    * If using an installer:
      This command will launch the installer wizard.
      You can pass the installer seed file as argument or on STDIN.
   * Without installer:
      This will execute the configure script at /opt/zammad/packaging/scripts/configure (if any).
      A file containing environment variables can be given as argument or on STDIN (-f -), and will be saved in the /etc/zammad/conf.d folder.

  zammad reconfigure
    This command allows to reconfigure the application. Only useful if using an installer.

  zammad restart [process]
    This will restart the application (or the given process), in a distribution-independent manner.
`

**Comment by muhammadn** [comment]
😅Sorry about that.  do try`/usr/bin/zammad restart`

**Comment by chrstmnn** [comment]
-bash: try/usr/bin/zammad: Datei oder Verzeichnis nicht gefunden

**Comment by muhammadn** [comment]
just `/usr/bin/zammad restart`

**Comment by chrstmnn** [comment]
Also no output =/

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

This creates a lot of noise on the issue tracker for everybody watching this repository. Thanks for your understanding.
