### ISSUE TITLE
Mandatory select field type_id empty for customer

### ISSUE THREAD

**Issue by hhoechtl** [zammad/zammad#1949]
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): Docker

### Expected behavior:

* As a logged in customer or agent I can create tickets in the webinterface

![image](https://user-images.githubusercontent.com/5076356/38676943-effeb1c6-3e5c-11e8-821e-fa622f11c89b.png)

### Actual behavior:

* The new select field type_id is empty but mandatory => no ticket can be created.
* As agent or administrator there's a list of possible selections (web, facebook, etc.)

![image](https://user-images.githubusercontent.com/5076356/38676930-e582f482-3e5c-11e8-8e66-1693fe4c4772.png)

### Steps to reproduce the behavior:

* Login as a customer in the web interface and try to create a ticket.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @hhoechtl - please post a screenshot of your object manager attribute configuration.

**Comment by hhoechtl** [comment]
![bildschirmfoto 2018-04-13 um 14 10 29](https://user-images.githubusercontent.com/5076356/38734134-c0e9c13c-3f24-11e8-94a7-382dae12a4cb.png)

![bildschirmfoto 2018-04-13 um 14 10 48](https://user-images.githubusercontent.com/5076356/38734137-c4f3b904-3f24-11e8-848d-f99365d32e54.png)

![bildschirmfoto 2018-04-13 um 14 10 36](https://user-images.githubusercontent.com/5076356/38734144-c87cf496-3f24-11e8-8be7-fed0cb627086.png)

![bildschirmfoto 2018-04-13 um 14 10 54](https://user-images.githubusercontent.com/5076356/38734149-cbb41400-3f24-11e8-8a75-d60776ac0ac1.png)

**Comment by hhoechtl** [comment]
The field appeared after the Update from 2.1 to 2.4. We never had that
field and never configured it.

Thorsten <notifications@github.com> schrieb am Fr., 13. Apr. 2018, 14:18:

**Comment by thorsteneckel** [comment]
Can you create a bigger screenshot. I need more context. Looks like something went wrong while updating.

**Comment by hhoechtl** [comment]
![image](https://user-images.githubusercontent.com/5076356/38767921-491a9aec-3feb-11e8-8f8c-540e5b66caed.png)

Is the complete view of an agent who tries to create a ticket in the interface.
As you can see, the field type (which was added during the Zammad update) is empty but mandatory. It's only filled if I'm logged in as administrator:

![image](https://user-images.githubusercontent.com/5076356/38767941-a00b4982-3feb-11e8-9ba2-8d3156402407.png)

**Comment by thorsteneckel** [comment]
Looks a lot like your update went wrong somehow. The agent create view looks completely different than in a regular Zammad installation. I think the HTML and JavaScript got mixed up and is broken. Since this no issue with the Zammad core application but a rather technical question please create a topic in our community board over at https://community.zammad.org - Thanks!
