### ISSUE TITLE
Allow pagination in search result with more then 100 results

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#1951]
### Infos:

* Used Zammad version: latest
* Installation method (source, package, ..): source
* Operating system: Linux
* Database + version: MariaDB / ES
* Elasticsearch version: latest 5.6+
* Browser + version: 

### Expected behavior:

* It would be nice to allow a pagination over 100 pages. 

### Actual behavior:

* Params over 100 is ignored
see:
https://github.com/zammad/zammad/blob/develop/app/controllers/tickets_controller.rb#L434

ES Supports this feature.
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-request-from-size.html

**Comment by MrGeneration** [comment]
Hey,

this is a feature request - please do not post feature requests on this Tracker, but use https://community.zammad.org/ :)

Thanks

**Comment by martini** [comment]
@MrGeneration thanks for that hint. In this case it's a already verified feature enhancement, so the issue is ok.

**Comment by martini** [comment]
@hanneshal It's implemented and deployed on ptool.zammad.com - pls let me know if it's working how for you.
