### ISSUE TITLE
Trigger for a chat had been created by guest.

### ISSUE THREAD

**Issue by shionphan** [zammad/zammad#1955]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): source
* Operating system: Ubuntu 16.04
* Database + version: Mysql 5.7+
* Elasticsearch version: -
* Browser + version: Firefox 59+

### Expected behavior:

* Trigger -> New Trigger -> Select Chat Trigger
  **Conditions attributes: Define conditions attributes for which a trigger will be executed. Triggers respond when a guest creat a chat**

### Actual behavior:

* Trigger has no the option for chat

### Steps to reproduce the behavior:

* --

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Can you give more insights what you mean with that? What Trigger do you want to create? What's its purpose?
I think this is a feature request/enhancement but nut a bug.  You can ask questions or discuss feature requests/enhancements over at https://community.zammad.org/ - Closing now until it's a bug scenario.
