### ISSUE TITLE
"Create new Customer" form delayed display

### ISSUE THREAD

**Issue by skyjumpy** [zammad/zammad#1957]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04.4
* Database + version:  PostgreSQL 9.5.12
* Elasticsearch version: 5.6.8
* Browser + version: Firefox 59 / Chrome 65

### Expected behavior:

**Create new Customer** form opening instantly after being selected by an Agent in the **Ticket**->**Change Customer** menu

### Actual behavior:

**Create new Customer** form taking about 10 seconds to display after button is pressed.

### Steps to reproduce the behavior:

Go to a Ticket
Select Ticket -> Change Customer
Select "Create new Customer"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Without any further lookups as I lack of time right now: On current patch I can see the same problem.

Will lookup logfiles later.

@skyjumpy please provide your production.log

**Comment by skyjumpy** [comment]
[production.log](https://github.com/zammad/zammad/files/1915521/production.log)

**Comment by thorsteneckel** [comment]
Hi @skyjumpy / @MrGeneration - Would you mind trying to reproduce this on a free http://zammad.com instance so we can reproduce it? Thanks a lot.

**Comment by skyjumpy** [comment]
i created one at https://3bwa6pgkf.zammad.com, the issue can be replicated with the sample ticket. 
Do i need to share the login?

**Comment by MrGeneration** [comment]
I think now we have two instances, added one too... issue1957.zammad.com

Can be deleted if not further needed. Doesn't seem to be a problem with the number of customers you have.

**Comment by thorsteneckel** [comment]
Wow - thanks to both of you! Having two instances to test on is a luxury problem I don't mind to have 😄 Anyway, I will delete the second instance.
We'll have a look at and fix it 👍 Thanks for reporting.

Internal:
This can be reproduced with the `debugger` account on https://3bwa6pgkf.zammad.com/. Please remember to remove the instance after the bug is fixed.
