### ISSUE TITLE
Tabbing in "Create new User" dialoge not working backwards beyond company

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#1958]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): package
* Operating system: openSuse 42.3
* Database + version: postgreSQL 9.6-1.1
* Elasticsearch version: 5.6.6
* Browser + version: Microsoft Edge, IE11, Firefox 59.2, Google Chrome 65.0.3325.181

### Expected behavior:

* When tabbing backwards, I expect the cursor to go back through all text fields

### Actual behavior:

* You can only tab backwards to "Company" - the cursor is stuck there - tabbing forward das work

### Steps to reproduce the behavior:

* Go into settings -> Users
* Click "Add User" or Edit an existing User (doesn't matter)
* Filling in content or not into the form is not relevant
* tab through the form (stop whent he cursor is within "company" or some fields further)
* now try to tab backwards - the cursor will not leave "Company" as soon as it's inside there

This also works if you start tabbing backwards on the beginning.
During testing this, I also noticed, that when tabbing backwards from "First name", I am tabbing through all menu links (in the background) until I reach the form. A user doing this is not very likely in my opinion - but still that should be a bit better. :)

I am sure that this ist just a UI problem.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mrflix** [comment]
Hey Mr! Thanks for spotting this bug. Its fixed now :)
