### ISSUE TITLE
Entwurf wird gelöscht

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#196]
Vorgehen, um den Bug zu reproduzieren: 
- +
- "Neues Ticket"
- Text eingeben
- Auf anderes Ticket gehen
- Zurück zum Entwurf gehen: alle Eingaben sind futsch.

**Comment by rugk** [comment]
Bitte schreib deine Fehlermeldung in Englisch.

Please write your issue description in English.

**Comment by monotek** [comment]
Kann ich nicht nachvollziehen.
Funktioniert sogar mit neuer Session bzw. 2 Brosertabs.
