### ISSUE TITLE
Twitter and Facebook error

### ISSUE THREAD

**Issue by Marco270694** [zammad/zammad#1960]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): source
* Operating system: Ubuntu
* Database + version: any
* Elasticsearch version: any 
* Browser + version: any

### Expected behavior:

*Twitter and Facebook page Connect

### Actual behavior:

* Aktueller Status

> Channel: Twitter::Account out key:{"id"=>xxxx, "screen_name"=>"HMHostDE", "name"=>"HM-Host.de"}; Can't use Channel::Driver::Twitter: #<Twitter::Error::BadRequest: Recipient (user, screen name, or id) parameter is missing.>
> 
> Channel: Facebook::Account in key:{"name"=>"XXX", "id"=>"xxx"}; Can't use Channel::Driver::Facebook: #<Koala::Facebook::ClientError: type: OAuthException, code: 200, message: (#200) Access to this data is temporarily disabled for non-active apps or apps that have not recently accessed this data due to changes we are making to the Facebook Platform. https://developers.facebook.com/status/issues/XXXX/, x-fb-trace-id: EcRlxgMczgR [HTTP 403]>
> 
> 357 failing background jobs.
> Failed to run background job #1 'BackgroundJobSearchIndex' 10 time(s) with 136 attempt(s)
> 

### Steps to reproduce the behavior:

* test command: zammad run rails c 
 he open in Terminal:
`zammad run rails c
Loading production environment (Rails 5.1.4)
irb(main):001:0>
`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by muhammadn** [comment]
For twitter if you are having problems with Direct Messages, it is already fixed and should be in Zammad 2.4.1

However, for Facebook channel, the problem is with Facebook's API which they are doing "audits" because of Cambridge Analytica problem.

**Comment by noezdev** [comment]
Currently it is not fixed.

**Comment by thorsteneckel** [comment]
Yes, we can't since it's a third party issue. FB is performing audits for their APIs and is limiting the access for other applications.
