### ISSUE TITLE
S/MIME encryption

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1961]
As discussed earlier in #220 there should be support for S/MIME email communication. There are no further details available yet. This will be probably based on the work done in the PGP issue and introduce an additional module layer, admin interfaces and so on.

Please avoid +1 comments since they create a lot of noise for us maintainers. If you want to help/contribute and share the implementation costs you can write a mail to our support team. Thanks!

**Comment by martinseener** [comment]
We're currently searching for other People who are willing to fund this feature (maybe also together with the GPG encryption as a package). Please contact me if you're interested at my forename at lastname .de. I will check and see how many willing people are there so we can just share the costs.
