### ISSUE TITLE
2-way Email Sync in Zammad

### ISSUE THREAD

**Issue by dsukhin** [zammad/zammad#1965]
Hello!

I would like to use this issue to start a discussion on my work to add a new feature extension to Zammad (figured this issue would get the most visibility by other developers here). My team is super excited about Zammad and would love to make it even better with a few enhancements. 

**Using this issue to document the proposed changes and ask for help and guidance from others that may know the codebase better at the moment.**

I would like to add 2 way email sync. This means that messages sent from Zammad are also placed in the Sent folder on IMAP and messages sent from IMAP (any email client) are appended to the relevant ticket in Zammad (both historically when first importing and IMAP mailbox and going forward). In the absence of a mobile version of Zammad, being able to reply from any client and having the reply appear and be properly tracked in Zammad would be awesome. Zammad can then continue to do what its good at and set rules on closing tickets, tracking responses, and making sure emails don't fall through the cracks.

## Proposed Enhancements
* **2 way email sync** (allow replies both from zammad and from any mail client)
  * Have Zammad place messages it sends in the sent box on imap (easy)
  * Make sure Zammad sets the "replied" flag on messages it sends replies on
  * Make sure sent messages properly set the references and in-reply-to headers (easy, does this already happen?)
  * Allow Zammad to also view the sent box to pull in any messages that are part of a thread into a ticket (relatively simple, just requires matching messages by the "references" or "in reply to" headers, this will be the most involved step)

**Excited to hear other's thoughts, suggestions, and guidance.**

**Comment by thorsteneckel** [comment]
Hi @dsukhin - thanks for the kind words. We are happy to read about your eager proposal to extend Zammad. However, we only track issues over here. (Technical) questions and discussions take place over at our community at https://community.zammad.org/ . Feel free to open a thread over there and ask any questions. We try to answer them.
Please note that we will only merge features that affect at least 80% of the Zammad user base. All other functionalities are happily welcome as a package extension. Read you over at the board.

**Comment by dsukhin** [comment]
Thank you. Excited to hear your thoughts and suggestions. Moved here: https://community.zammad.org/t/2-way-email-sync-for-zammad/583
