### ISSUE TITLE
ctrl+alt+x does not work

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#197]
I can't remove the hyperlink. Any workarounds?

Firefox on KDE/SuSE

**Comment by monotek** [comment]
@martini 
How should this work?
Removing things from the text like https://zammad.org ?
If so, it does not work for me too.

**Comment by rolfschmidt** [comment]
Hi @zabarabab,
thanks for your report!!! This should be fixed in the next stable release. Please remember that we have changed the key combinations in general to CTRL + SHIFT + ... 

-Rolf
