### ISSUE TITLE
Admin UI does not allow to select Timezone in "Calendars" options

### ISSUE THREAD

**Issue by penzoiders** [zammad/zammad#1971]
### Infos:

* Used Zammad version: zammad.x86_64 2.4.0-1524466853.ee551209.centos7 @zammad
* Installation method (source, package, ..): RPM via repo @zammad
* Operating system: CentOS Linux release 7.4.1708 (Core) 
* Database + version: postgresql-server.x86_64 9.2.23-3.el7_4 @updates
* Elasticsearch version: elasticsearch.noarch 5.6.9-1  @elasticsearch-5.x
* Browser + version: Google Chrome 65.0.3325.162 (64 bit)

### Expected behavior:

* being able to select (mandatory) "Timezone" field in calendars admin settings under https://myzammadip/#manage/calendars, there aren't any selectable entries except `-` in " Subscribe to public holidays in " field

### Actual behavior:

* The dropdown menu arrow shows up but it's not working and even auto completion (eg: starting to type Europe, or GMT or anything) does not provide any clickable results

### Steps to reproduce the behavior:

* Fresh install and go to admin panel and try to add a new one or modify the default one: It's not possible to select the timezone and there's no list for holiday's calendar.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Just took a look on my instance: Problem occurse on existing instances, too.

Dropdown is empty and typing in it does not give any search results.

**Comment by penzoiders** [comment]
Just an additional info (trying to adapt office hours using the default Texas timezone)... I've noticed that  "Description" is not saved upon save and adding/removing custom holidays may reset iCal link resulting in loosing all the holidays settings (maybe another 2 issues here, maybe all linked.. tell me if you want me to split this in multiple issues)

**Comment by martini** [comment]
JFI: Bugfix is in the pipe.

**Comment by penzoiders** [comment]
Cool, thanks!

**Comment by uli-heller** [comment]
I'm hit by this issue, too. It prevents me from creating calendars. Does anyone know what to enter in this field? I don't care about auto-completion for now. Entering "Europe/Berlin" doesn't work unfortunately.

**Comment by martini** [comment]
It's fixed in current stable. Please upgrade your Zammad OS package and it should work fine now.

Feedback is welcome!

**Comment by martini** [comment]
Thanks for feedback!
