### ISSUE TITLE
Twitter Directmessages are closed by default

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#1973]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): package
* Operating system: openSuse 42.3
* Database + version: postgreSQL 9.6-1.1
* Elasticsearch version: 5.6.6
* Browser + version: all, Browser does not matter

### Expected behavior:

* Sent direct messages on twitter will be fetched by zammad and shown as open/new, as long as the agent doesn't close it

### Actual behavior:

* Sent direct messages on twitter are fetched by zammad and created as "closed". Still zammad sends a notification to the agent.

### Steps to reproduce the behavior:

* Login to twitter as the user zammad monitors
* Send a direct message to a Twitter-User
* wait for zammad to import the message and check it's state

![image](https://user-images.githubusercontent.com/6549061/39183310-d7cc2aa4-47bf-11e8-825f-0160296228ea.png)

### Notes
* this only happens when you send a message from the account but not when you receive it.
* when I tried to reproduce this I deleted the twitter conversation with my personal account and send a new message to my test account. I noticed, that zammad does enqueue the test message wrong into an existing ticket. This shouldn't happen!

Edit:
* when the contacted user answered on the message, it became it's own ticket number as zammad doesn't seem to be able to see the connection there - had to merge it manually.

![image](https://user-images.githubusercontent.com/6549061/39183361-ff21ab74-47bf-11e8-82f9-81b600c5c072.png)

I will provide the production log filtered later, as I currentely do not have access to the instance. Will update this today evening.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @MrGeneration 

this behaviour should only be happen if the sender account of the tweet/dm is configured as twitter channel in Zammad.

It would be nice if you could verify this with Zammad 2.8 again.

Thanks!

 -Martin

**Comment by MrGeneration** [comment]
This seems to be solved by now.
I can't reproduce it any more - awesome. :)
