### ISSUE TITLE
Forgot password function doesn't work 

### ISSUE THREAD

**Issue by Guevarabrik** [zammad/zammad#1976]
### Infos:

* Used Zammad version: 2.4.x
* Installation method (source, package, ..): ubuntu 
* Operating system: ubuntu 16.04
* Database + version: idk
* Elasticsearch version: idk 
* Browser + version: idk

### Expected behavior:

i expect the *Forgot Password* / *apply for new password* function to work

### Actual behavior:

if a new user have had contact with the support team, it means he already has an account in zammad, all he has to do is to apply for a new password. after clicking on apply for password or forgot password, the user has to type his email in a window and he will recieve the instruction for getting a new password, which is not the case.

### Steps to reproduce the behavior:

* click on forgot password
* type in your emial 
* click on send 
nothing happens

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @Guevarabrik 

this usually works fine (also tests are available for that). Can you reproduce it on a https://zammad.com instance?

Maybe your configuration for sending notifications is wrong/not working.

 -Martin

**Comment by Guevarabrik** [comment]
Hi @martini 
thx for answering me !
i fixed the problem right now, i just configured my own SMTP server and it works just fine.
Thx a lot !
