### ISSUE TITLE
Login Form HTML PHP

### ISSUE THREAD

**Issue by Maxo112** [zammad/zammad#1979]
Hello Guys,

i would like to ask if anyone have a finished php Script for Zammad Login. Because I don't know much about apis. And therefore, I would like to ask if anyone use an own PHP Script to login from an external Website to Zammad.
I have a Site and I would like to import an login form where the User can Login or Register to Zammad. 
I hope anyone can help me.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.
