### ISSUE TITLE
user can't edit notifications

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#198]
https://linuxhotel.zammad.com/#profile/notifications

the page stays blank respectively keeps the content of the page before. 

other users can. Why?

This happens only for the user
a.sanchez.herrero@linuxhotel.de

It does not happen for me (iw@linuxhotel.de) and laura (l.trinowitz@linuxhotel.de)

**Comment by rkaldung** [comment]
@zabarabab Still an open issue?

**Comment by zabarabab** [comment]
dont know
