### ISSUE TITLE
Change Customer - "add new customer" delay

### ISSUE THREAD

**Issue by lr1980** [zammad/zammad#1983]
### Infos:

* Used Zammad version: 2.5.0
* Installation method (source, package, ..): Docker
* Browser + version: Safari / Firefox

### Expected behavior:

* change customer => no delay :)

### Actual behavior:

* when change the customer and click an add customer you have a very long delay without visual response

### Steps to reproduce the behavior:

* exists ticket => change customer => click on "add new customer" => wait 

This bug we discovered on our production system with Zammad 2.4 on CentOS (+ Zammad Repo). Then i reproduce it with the latest docker image. Here is my screen recording: https://vimeo.com/266869012

**Comment by martini** [comment]
@lr1980 Thanks, issue is already existing. https://github.com/zammad/zammad/issues/1957 fix is on the way....
