### ISSUE TITLE
The active flag of attributes is ignored when using the API 

### ISSUE THREAD

**Issue by SummerStorm** [zammad/zammad#1984]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): source
* Operating system: Ubuntu 16.04
* Database + version: PostgreSQL 9.5.12
* Elasticsearch version: 6.6.0
* Browser + version: Firefox ESR 52.5.2 (64-bit)

### Expected behavior:

When creating or updating a ticket using the API, parameters referring to an inactive attribute should either be silently ignored or flagged as an error.

### Actual behavior:

The `active` flag of attributes is ignored when updating or creating tickets using the API. 

### Steps to reproduce the behavior:

1. Create a new date attribute object named "required_date" and mark it as "inactive". Submit and update the database. (This bug applies to all attribute types; I'm just using the date type as an example.)

2.  `POST` the following JSON to `/api/v1/tickets` to create a new ticket:
<pre><code>{
	"title": "Test ticket",
	"group": "Users",
	"article": {
		"subject": "some subject",
		"body": "some message"
	},
	"customer": "nicole.braun@zammad.org",
	<b>"required_date":"2018-04-29"</b>
}
</pre></code>

3. The created ticket will have its `required_date` attribute set even though the attribute is inactive:
<pre><code>{
	"id": 109,
	"group_id": 1,
	"priority_id": 2,
	"state_id": 1,
	"organization_id": 1,
	"number": "25106",
	"title": "Test ticket",
	"owner_id": 1,
	"customer_id": 2,
	"note": null,
	"first_response_at": null,
	"first_response_escalation_at": null,
	"first_response_in_min": null,
	"first_response_diff_in_min": null,
	"close_at": null,
	"close_escalation_at": null,
	"close_in_min": null,
	"close_diff_in_min": null,
	"update_escalation_at": null,
	"update_in_min": null,
	"update_diff_in_min": null,
	"last_contact_at": null,
	"last_contact_agent_at": null,
	"last_contact_customer_at": null,
	"last_owner_update_at": null,
	"create_article_type_id": 10,
	"create_article_sender_id": 1,
	"article_count": 1,
	"escalation_at": null,
	"pending_time": null,
	"type": null,
	"time_unit": null,
	"preferences": {},
	"updated_by_id": 3,
	"created_by_id": 3,
	"created_at": "2018-04-28T08:43:09.514Z",
	"updated_at": "2018-04-28T08:43:52.222Z",
	<b>"required_date": "2018-04-29",</b>
	"article_ids": [
		105
	],
	"ticket_time_accounting_ids": []
}
</pre></code>

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
This will be improved in the future when dealing with the whole REST api.

Closing this issue now.
