### ISSUE TITLE
Make ticket create article types configurable

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1987]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): git
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* The list of possible article types for a ticket created by an agent via the web interface should be configurable:

![image](https://user-images.githubusercontent.com/3873515/39515378-3907de18-4dfa-11e8-9df8-f3846b260fbc.png)

### Actual behavior:

* The list of possible article types for a ticket created by an agent via the web interface is not configurable.

**Comment by martinvonwittich** [comment]
I've just found this option in the code - apparently there is no user interface to configure this, and I had to use the rails console to set it:

```
Setting.set('ui_ticket_create_default_type', 'email-out')
```

Is that intentional, or a bug?

**Comment by thorsteneckel** [comment]
Hi @martinvonwittich - there are some (undocumented) "advanced" settings that come without a UI. This is one of them - so intentional.
We do this to keep the UI clean and cover the functionalities most of the people actually need. However, there are other valid, more special use cases which we want to cover as well. This is our current way of approaching this.
