### ISSUE TITLE
Empty custom placeholder replaced by dash (-)

### ISSUE THREAD

**Issue by datenritter** [zammad/zammad#1988]
### Infos:

* Used Zammad version: 2.4.x
* Installation method (source, package, ..): Debian package.
* Operating system: Debian Linux.

### Expected behavior:

* Custom placeholder shouldn't display anything if field is empty.

### Actual behavior:

* Shows a dash (-) instead.

### Steps to reproduce the behavior:

* Create a custom placeholder "title" in user objects.
* Fill title for one user.
* Change e-mail signature to #{user.title} #{user.firstname}...
* Test reply with user who has no title.
* See: "- Firstname Lastname"

**Comment by datenritter** [comment]
An empty field is an empty field. "Nothing" is a valid input.

**Comment by thorsteneckel** [comment]
I think we should discuss this over at the http://community.zammad.org/ until we have a solution that fits the needs of the majority. Thanks 👍
