### ISSUE TITLE
Enable article.body in trigger jobs

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#1989]
### Infos:

* Used Zammad version: 2.4 + Dev (2.5)
* Installation method (source, package, ..): source
* Operating system: macOS
* Database + version: postgresql 9.4
* Elasticsearch version: 5.6
* Browser + version: Safari latest

In an earlier version we had the possibility to search the article body using a trigger and perform actions if the search query was found.

### Expected behavior:

It should be possible to search for article.body in trigger jobs.

### Actual behavior:

* It's not. Maybe a result of "StringText vs StringHTML" comparison.

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @rlue - could you please take over this one? There is an internal branch called `private-issue1989-trigger` for which the QA is ok. Please give it the final push to cross the finish line 🏁
