### ISSUE TITLE
what to do with incoming fax?

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#199]
my workaround: I attach the scan to an incoming call. But that's a hack to me ...

workaround does not work: zammad does not accept an email address as client of an incoming call. so I'll create the ticket by importing an email with the attached scan

Is there a more userfriendly way?

**Comment by rkaldung** [comment]
@zabarabab Using a fax2mail solution is a typical way to handle this. After the mail is availbale in Zammad just assign the proper custoemr.
Or do you really scan incoming faxes?

**Comment by zabarabab** [comment]
@rkaldung Looking at the UI in https://linuxhotel.zammad.com/#ticket/create/id/:id I expected Zammad provides a different "type" of ticket for incoming phone calls, outgoing phone calls and outgoing emails. So I expected, a type for fax would be useful.

I think that was a misunderstanding.

>  just assign the proper customer.

Ah, that's helpful. But often not feasible as long as #181 and #613 is not solved.
