### ISSUE TITLE
Ticket waiting time report backend creates high CPU load with script/scheduler.rb

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#1995]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): git
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

The following code creates an expensive N+1 query that creates a high CPU and memory load:

https://github.com/zammad/zammad/blob/757f0ac9bddaf348a6929bcf7d43d1180ea106f4/lib/stats/ticket_waiting_time.rb#L58-L61

**Comment by martini** [comment]
Update: Indexes are existing. It's just to much load/work to generate the "waiting time report".
