### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#1997]
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): Package for Centos (.rpm)
* Operating system: Centos
* Database + version: Mysql (any)
* Elasticsearch version: any
* Browser + version: Chrome, Firefox

### Expected behavior:
When agent upload attachment, attachment should get attached to the ticket reply.

### Actual behavior:

When agent tries to attach an attachment it freezes on 100%. When its on POST request method, the  Status code of request to 
"http://test.com/api/v1/ticket_attachment_upload" shows an error of "500 Internal Server Error"

### Steps to reproduce the behavior:
Sending ticket to Zammad, an agent tries to reply by an attachment with sizes in {4,6,5,2}MBytes.

**Comment by martini** [comment]
Hi @hamzehmohammadnia 

why the 500er happen you can see in the `log/production.log`. Without that we can't give feedback (I guess there are issue with the database upgrade).

 -Martin

**Comment by thorsteneckel** [comment]
Hi @hamzehmohammadnia - this is probably an issue with your setup. However, feel free to provide the requested logfile and/or move over to our http://community.zammad.org/ for technical questions/discussions. Thanks!

**Comment by hamzehmohammadnia** [comment]
I think i found the problem and was related to packet size limitation within database. Once I  have increased that to higher than 100 MB it fixed! :)

Thanks!

**Comment by martini** [comment]
Thanks for feedback.
