### ISSUE TITLE
Integrate a Spell checker like Languagetool

### ISSUE THREAD

**Issue by Mannshoch** [zammad/zammad#2003]
From: https://community.zammad.org/t/integrate-a-spell-checker-like-languagetool/204

I would prefer https://www.languagetool.org because It’s possible to use it with a online service or if you wish you could run your own server.

At moment I run my own server on my Desktop and use it with a Firefox Plug-in. But that is not a solution for everyone, Also its not easy to setup a Company Dictionary that way.

Github: https://github.com/languagetool-org/languagetool
DEV: http://wiki.languagetool.org/
Integration into Websites: http://wiki.languagetool.org/integration-on-websites

![grafik](https://user-images.githubusercontent.com/7795891/39754029-1ebf0434-52c1-11e8-87aa-096107e6fdb6.png)

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a feature request. I see that you already created an entry over at the community board but it looks like there is not enough interest from the community to pick it up. Closing and locking now.
