### ISSUE TITLE
UI Bug - Lock symbol for article changes after saving

### ISSUE THREAD

**Issue by bvanleenhoff** [zammad/zammad#2004]
### Infos:

* Used Zammad version:  2.4.x and 2.3.x tested
* Installation method (source, package, ..): ubuntu / apt
* Operating system: ubuntu 16.04
* Database + version: standard
* Elasticsearch version: standard
* Browser + version: current firefox

### Expected behavior:

* after saving an article the lock symbol should stay the same 

### Actual behavior:

* the symbol changes to its opposite state - regardless if the state is changed from standard or not

### Steps to reproduce the behavior:

* type something into article filed and save

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @bvanleenhoff - I'm not sure if I get it right. For me it works:
![internal_switch](https://user-images.githubusercontent.com/3873515/39761055-4fe4db2c-52d7-11e8-9376-a0b991038a18.gif)

I think you have a trigger that is configured wrong? However, I will close this issue for now. Please provide a detailed step by step guide on how to reproduce. If the steps are the same as in my GIF above please try to reproduce it on a free https://zammad.com/getting-started instance and post the name here.

**Comment by bvanleenhoff** [comment]
thanks for the quick reply! I think it is by design since you show what action can be done after the article is saved and not the state of the article. 
e.g. we close the lock and after saving we have the option to open the lock - so you display an open lock - which is a little confusing to be honest - combined with the not so distuingishable symbols (which you have a feature request for) it can play with ones mind.

so the issue is just that the lock symbol is changing - which can be seen in your gif.
