### ISSUE TITLE
Email notification-New tickets

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#2007]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): .RPM
* Operating system: Centos 7
* Database + version: Any-Mysql
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:
When a ticket is sent to the Zammad, zammad sends automatic notification to all related/associated agents. Within this email/notification Information states the content of ticket. And under  this ticket.content, we see url link to the ticket.
  
Expected behavior is agents wouldn't be forced to read whole content of ticket (maybe long scrolling) and then reach the ticket url link. They should have url link at the top of ticket.content

### Actual behavior:

Actual behavior is agents are be forced to read whole content of ticket (maybe long scrolling) and then reach the ticket url link to go to the zammad for the ticket resolution.

**Comment by thorsteneckel** [comment]
You can change this in the template of the corresponding notification in `app/views/mailer`. Since this is more a personal preference you can discuss this with the community over at http://community.zammad.org/ . Maybe we pick it up if its in the interest of the community 👍
