### ISSUE TITLE
Calendar: Unable to edit because the dialog box is way too high and no scrollbar

### ISSUE THREAD

**Issue by uli-heller** [zammad/zammad#2009]
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): source
* Operating system: ubuntu 18.04
* Database + version: mysql
* Elasticsearch version: 5.6.x
* Browser + version: Chrome

### Expected behavior:

* Show a scrollbar in case the dialog box is too high

### Actual behavior:

* A very high dialog box shows up, the "save" button cannot be reached

![auswahl_204](https://user-images.githubusercontent.com/1677414/39858509-1a628164-5437-11e8-807d-b3986a2f8a2a.png)

### Steps to reproduce the behavior:

* After source installation, try to edit the calendar

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @uli-heller 

the dialog screen should be scrollable. At the end you can press submit.

<img width="1277" alt="screen shot 2018-05-10 at 09 48 03" src="https://user-images.githubusercontent.com/110226/39858607-5ed0b6cc-5437-11e8-87f9-d080093d8523.png">

Is that not working on your side?

 -Martin

**Comment by uli-heller** [comment]
OK, my fault. Scrolling did not work since the focus was on the input field "name". It works one you click outside of this field but inside the dialog box.
