### ISSUE TITLE
SLA by organisation: Inactive organisations show up

### ISSUE THREAD

**Issue by uli-heller** [zammad/zammad#2010]
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): source
* Operating system: ubuntu 18.04
* Database + version: mysql
* Elasticsearch version: 5.6.x
* Browser + version: Chrome

### Expected behavior:

* Auto-complete shows only active organisations

### Actual behavior:

* Auto-complete shows active and inactive organisations

![auswahl_205](https://user-images.githubusercontent.com/1677414/39859003-a654e4fe-5438-11e8-8915-036051a75b3e.png)

### Steps to reproduce the behavior:

* Create some organisations
* Mark some of them "inactive"
* Create a new SLA
* Add a new criterium: 'Org' 'is' 'specific'
* Enter a letter within the input field and watch for the auto-complete to show up

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by SummerStorm** [comment]
This has been fixed by 3186d5e4d763f8e367f8cf9d5c4eae918284bdbf.
