### ISSUE TITLE
Scheduler will stop after removing own ticket attribute but overview with condition which is including attribute git dropped

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2016]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Do not allow to drop ticket attributes via object manager where the ticket attributes is still used in trigger, overview or scheduler

### Actual behavior:

* Dropping ticket attributes leads to stopping scheduler:

```
E, [2018-05-14T10:02:52.758814 #6222] ERROR -- : PG::UndefinedColumn: ERROR:  column tickets.aaa1 does not exist
LINE 1: ...ed_at FROM "tickets" WHERE (group_id IN (1)) AND (tickets.st...
                                                             ^
: SELECT  DISTINCT "tickets"."id", "tickets"."updated_at", tickets.created_at FROM "tickets" WHERE (group_id IN (1)) AND (tickets.aaa1 IN ('Value#1')) ORDER BY tickets.created_at DESC LIMIT $1 (ActiveRecord::StatementInvalid)
```

### Steps to reproduce the behavior:

* create ticket attribute aaa1
* create overview where ticket attribute aaa1 is used in condition
* drop ticket attribute aaa1

**Comment by martini** [comment]
@muhammadn did you review the pr #2033 ?

**Comment by muhammadn** [comment]
@martini done with review, you can QA it now since the build is ok.
