### ISSUE TITLE
If tags from users diabled, he cannot choose existing tags

### ISSUE THREAD

**Issue by winnidarks** [zammad/zammad#2022]
### Infos:

* Used Zammad version: 2.4.x
* Installation method (source, package, ..): package
* Operating system: Debian
* Database + version:
* Elasticsearch version: 5.6
* Browser + version: Firefox 60 ESR

### Expected behavior:

Users can choose existing tags, when the function to create new ones is disabled.

### Actual behavior:

If tags from users diabled, he cannot choose existing tags.

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Hi,

Unfortunately we weren't able to reproduce this issue. Please try upgrading to the latest version and see if it fixes your issue.
