### ISSUE TITLE
Twitter Account Activity API support

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#2023]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): any

### Expected behavior:

* Zammad should support the [announced](https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html) [Twitter Account Activity API](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/overview) - which will deprecate the Streaming API after August 16th, 2018 Zammad is currently using.

### Actual behavior:

* Zammad uses the Twitter Streaming API and doesn't support the Twitter Account Activity API.

**Comment by muhammadn** [comment]
@thorsteneckel It is increasing frustrating to get a reply from twitter. 

Used their own `SnowBotDev` code still fails and no replies from their forums and support form (they just give a templated reply about login issues) and it's july and running out of time. You can try it out with their console in rackup that comes with the source.

source: https://github.com/twitterdev/SnowBotDev

```
>> load './scripts/setup_webhooks.rb'
=> true
>> wh = TaskManager.new
**redacted**
>> wh.set_webhook_config('https://mn.taqisystems.com/webhook')
Setting a webhook configuration...
POST ERROR occurred with /1.1/account_activity/all/devel/webhooks.json?url=https://mn.taqisystems.com/webhook, request:
Error code: 401 #<Net::HTTPUnauthorized:0x00007fb33fe8d128>
Error Message: {"errors":[{"code":32,"message":"Could not authenticate you."}]}
{"code"=>32, "message"=>"Could not authenticate you."}
=> {"errors"=>[{"code"=>32, "message"=>"Could not authenticate you."}]}
```
info:
https://twittercommunity.com/t/webhook-registration-failed-throwing-an-erro-code-32-message-could-not-authenticate-you/103142/36
