### ISSUE TITLE
Ticket overview sorting and state update issue

### ISSUE THREAD

**Issue by ryankikta** [zammad/zammad#2027]
### Infos:

* Used Zammad version: 2.4.x
* Installation method (source, package, ..): Ubuntu Deb
* Operating system: 16.04 xenial
* Database + version: google cloud MySql gen 2 
* Elasticsearch version: 5.6.x
* Browser + version: any

### Expected behavior:

when agent or user updates ticket details ticket is updated in database and rendered in the appropriate overview in the web GUI.

Tickets that are commented on after close display as open. 
*

### Actual behavior:

Intermittent problem...

Tickets are updated after action update in the database, the ticket state details change on screen, tickets remain in an overview they do not meet the criteria for indefinitely. (or until marked as closed again, sometimes multiple times to succeed) IE in the My open tickets overview (state is not closed and owner is current user) closed tickets will continue to be displayed. 

 Tickets that are closed and commented on or receive reply remain in a closed state, state_id is not updated in database, the associated comment however is updated 

*

### Steps to reproduce the behavior:

Create a google cloud account

Create a google SQL MySql gen 2 instance of sufficient GB size

Create a 6 core  18gb compute engine instance in the same region as the database using Ubuntu 16.04 xenial

Add the compute engine instance to the sql authorized user account and password for zammad

Make the cd path and file for /opt/zammad/config/database.yml

specify the addressing and permissions for the cloud db instance

Install elastic-search 5.9.x as per zammad instructions

Install zammad as per Ubuntu deb instructions

setup system to receive Email from a single gmail account for ticket creation

populate system with (2000) tickets 

Work on tickets with multiple users until ticket behavior fails to function as expected. 
(may or may not be an immediately visible issue, the time taken for behavior to noticeable degrade has varied between several clean builds that have all failed in the same way) 

*

Log not provided due to high volume of customer information.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @ryankikta - can you please verify this on one of our hosted instances over at https://zammad.com/getting-started
Just tell us the instance name and how we ca reproduce it over there. Thanks!

**Comment by ryankikta** [comment]
Hi,

In response to your query this is not a hosted instance, it is an instance
that I am attempting to get working correctly on the google cloud platform.

Thanks
Ryan

**Comment by thorsteneckel** [comment]
Hi @ryankikta - I am aware of that. Could you please verify that the behavior you're describing is reproducible in a hosted instance. Otherwise it's a technical question but no issue. Technical issues can be discussed over at our [community board](http://community.zammad.org/)

**Comment by ryankikta** [comment]
Hi Thorsten,

I am unsure if it is reproducible in a hosted instance my assumption is
that it may be, as I have created several instances in the cloud
environment and all display a similar behavior. I would have to find the
root cause, which I have yet to discover to say for sure, elasticsearch
seems to be central in the errors processing and updating tickets and
indexes.

I can give you more information as I collect it, but that's about all I
have right now.

Thanks
Ryan Kikta

**Comment by thorsteneckel** [comment]
So it's more of a technical question / request for assistance than a reproducible issue. It would be great if you could start a discussion over at our [community board](http://community.zammad.org/) or contact us at support@zammad.com if you need commercial assistance.
I'll close this issue now.
