### ISSUE TITLE
How to configure office365 SMTP

### ISSUE THREAD

**Issue by ikiranreddy** [zammad/zammad#2032]
Dear Team,

I have new setup of zammad when I am giving smtp office365 credential it’s giving error.

If any one came across this situation and resolved the issue.

Please share how to configure office365 smtp with zammad.

**Comment by muhammadn** [comment]
Hi @ikiranreddy 

Your question is a support question. Our github issues are for bug issues.
For support questions please go to https://community.zammad.org

Closing for now.
