### ISSUE TITLE
Bug or feature? Include origin email text in answer

### ISSUE THREAD

**Issue by LittleNo** [zammad/zammad#2045]
* Used Zammad version: 2.4.x (latest from Ubuntu package)
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04.4
* Database + version: 
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* When answering an email, the origin text from the incoming email should be placed at the bottom of the new email as quoted text. 

### Actual behavior:

* answering an email creates a new, blank email, containing only the defined signature

### Steps to reproduce the behavior:

* answer any email

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

The same topic is addressed here: https://community.zammad.org/t/how-to-setting-full-quote-original-e-mail-content/615

There are some duplicates of this e.g. #571
