### ISSUE TITLE
Update to Zammad v2.4 on OpenSuse not possible - Nothing to do

### ISSUE THREAD

**Issue by HPWulff** [zammad/zammad#2048]
### Infos:

* Used Zammad version: 2.2.0-1516084968.5604e5fe.sles12
* Installation method (source, package, ..): package
* Operating system: OpenSuse Leap42.3
* Database + version: postgresql 9.6-1.1
* Elasticsearch version: 5.6.5-1
* Browser + version: IE11 / Firefox 59.0.2

### Expected behavior:

* Update Zammad to 2.4

### Actual behavior:

* No Update: got message 'Nothing to fo'

### Steps to reproduce the behavior:

Hello Zammad,

we are using Zammad (2.4) since January with success and wanted to upgrade to the current version 2.4. Unfortunatly this does not work.  I hope, my request is in the correct category.

* We Tried to install new version as requested in documentation:

wget -O /etc/zypp/repos.d/zammad.repo   https://dl.packager.io/srv/zammad/zammad/stable/installer/sles/12.repo

zypper update zammad
"Loading repository data...
Reading installed packages...
No update candidate for 'zammad-2.2.0-1516084968.5604e5fe.sles12.x86_64'. The highest available version is already installed.
Resolving package dependencies...

Nothing to do"

I also tried wget with stable-2.4 instead of stable: same behaviour

Yes I'm sure this is a bug and no feature request or a general question.

Kind regards,

Hans Peter Wulff

**Comment by monotek** [comment]
Sles != Opensuse

**Comment by HPWulff** [comment]
Hello monotek,

when deciding for zammad, we checked:

"Install on SUSE via RPM
Currently we support SLES 12 and OpenSUSE 42.2"

So we installed on OpenSuSE following the recommended way for SUSE. And, btw, it installed fine.

By this, I don't understand your comment SLES != Opensuse.

Regards,
Hans Peter

**Comment by HPWulff** [comment]
Hello again,

got it running:

1) zypper update / Installing all current updates on OpenSUSE 43 (maybe irrelevant)
2) reboot
3) zypper refresh / maybe relevant
4) zypper update zammad / installed Version 2.4 with success

New Version is now available: especially recommending Users/Emails is very helpful for us!

Great Tool!

Regards, Hans Peter

**Comment by monotek** [comment]
True. My fault. 
Opensuse 42.3 is still not supported.
