### ISSUE TITLE
SMS via SMS API

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#2050]
### Infos:

    Used Zammad version: 2.3.x
    Installation method (source, package, ..): package
    Operating system: CentOS 7
    Database + version:
    Elasticsearch version:
    Browser + version:

### Expected behavior:
When a new ticket create or a ticket update an SMS send to client mobile number, body of text message support zammad tokens.
-----------
For example the following url will send an sms via my SMS API to my clients mobile number (+1931313321)

http://smspanel.com/sms/api?action=send-sms&api_key=bndhOmd1&to=+1931313321&from=80008791&sms=Your Ticket numner 8520 is answerd&response=json&unicode=1

### Actual behavior:

*

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mmojadad** [comment]
Will be good if there be an option that enable/disable sms notification for each answer enter in web interface of agents.

**Comment by mmojadad** [comment]
Or in advance there be an option ( Enable/Disable ) in answer text box that run a custom defined trigger.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a feature request. You can request features over at https://community.zammad.org/ - Closing now.

PS: We are already working on a SMS integration. Multiple providers will be support and adding new ones should be fairly easy.

PPS: Please remember that every comment/issue you write will create invoke sending an email to at least 104 people. This means there were more that 312 emails send alone for this issue. Please consider creating issues after you formed your thoughts completely, using our [community board](http://community.zammad.org/) or edit your comments. Thanks a lot!
