### ISSUE TITLE
ConnectionBad PQsocket

### ISSUE THREAD

**Issue by benhartwich** [zammad/zammad#2051]
Hi,

I´ve found the following errors at my log:

 Error while reserving job: PG::ConnectionBad: PQsocket() can't get socket descriptor: UPDATE "delayed_jobs" SET locked_at = '2018-06-04 05:45:23.697186', locked_by = 'host:homer pid:8875' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2018-06-04 05:45:23.696152' AND (locked_at IS NULL OR locked_at < '2018-06-04 01:45:23.696219') OR locked_by = 'host:homer pid:8875') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *

What can I do to solve this problem? Postgres is running and zammad is working.

### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): source
* Operating system: Debian 9
* Database + version: Postgres 9.6
* Elasticsearch version: 6.2.4
* Browser + version: Chrome 66.0.3359.181

Regards,

**Comment by thorsteneckel** [comment]
Hi @benhartwich - after googling around a bit I found out that this is caused by a lost DB connection. This happens inside a third-party library we're using (for background job processing) called `delayed_jobs` . Sadly we can't do anything about it the way that it is. Please make sure the connection to your DB host is more stable.

**Comment by thorsteneckel** [comment]
Thanks for the heads up! Would be great if you could provide a pull request. This will help us a lot 😻

**Comment by thorsteneckel** [comment]
While the core issue of this was that the services were not restarted - the `PG::ConnectionBad: PQsocket() can't get socket descriptor` exception was resolved with issue #2343
