### ISSUE TITLE
Branch documentation

### ISSUE THREAD

**Issue by siepkes** [zammad/zammad#2053]
I think there is an issue with the documentation about branches. It says in the [branches section of the manual](https://docs.zammad.org/en/latest/contributing-branches.html) that `master` is "Current unreleased development state of next stable minor release" and the following example is given: "If current stable version is 1.1.0 this will become 1.1.1".

However when I look at the `master` branch then `master` seems to be far ahead of `develop` (+/- 8900 commits vs +/- 8600 commits). The `develop` branch is described as "Current unreleased development state of next major release" with the example "If current stable version is 1.1.0 this will become 1.2.0".

**Comment by thorsteneckel** [comment]
Hi @siepkes - nice to hear from you again. Good spot! You can see [in the comparison between the two branches](https://github.com/zammad/zammad/compare/develop...master) that these are only merge commits. In older branches there were some special cherry picks that were not in develop in the exact same version but you can assume that master is always the latest branch of develop after creating a release. Hope that makes it clearer. I'm closing now.
