### ISSUE TITLE
no dissolve of phonenumbers from new user in the phone log

### ISSUE THREAD

**Issue by Newan** [zammad/zammad#2057]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): deb
* Operating system: ubuntu 16.04
* Database + version: postgres
* Elasticsearch version: n/a
* Browser + version: chrome

### Expected behavior:

* After create an new user over the phone number, the telefon log reloaded and show the new user

### Actual behavior:

* when a call comes in and a user is created via the phone number, the phone log will not be updated. The number remains as "new number" and you could create another user (dupliacted!). it would be better if the phone log the number on the new user would dissolve and updated after each user system.
A reload of the website also brings no success as a fallback

### Steps to reproduce the behavior:
make an sipcall event and create an user over the phone number
*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @rlue - could you please take over on this one? There is an internal branch called `private-mn_issue2057_cti`. QA is mostly ok but there is a critical line (`Cti::Log.where(from: phone)` in `app/models/user.rb`). This might affect a loooot of entries. We should perform it asynchronously or limit it down to 100 entries to avoid long too run times.
