### ISSUE TITLE
Incorrect display count of a report profile if tree_select is used

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#2059]
### Infos:
* Used Zammad version: 2.5 (SaaS)
* Browser + version: Google Chrome Version 66.0.3359.139
* Ticket-ID: #1034280, #1026414, #1030589

### Expected behavior:

* correct display of the corresponding tickets in the lower area of the reports:
![image](https://user-images.githubusercontent.com/22768032/41088904-f0cdbe7a-6a40-11e8-9885-59642679f850.png)

when selecting categories and groups as report profile filter.

### Actual behavior:

The following filter in the report profile are set:
![image](https://user-images.githubusercontent.com/22768032/41089025-2ee231b4-6a41-11e8-8d74-7f4d5cf7a60a.png)

The following tickets should be displayed in reporting:
![image](https://user-images.githubusercontent.com/22768032/41089132-61250bba-6a41-11e8-85bc-b928dbb1724f.png)

Neither closed nor opened tickets are displayed:
![image](https://user-images.githubusercontent.com/22768032/41089204-9c1048f2-6a41-11e8-9d1d-edbe89b626fb.png)

### Steps to reproduce the behavior:

- create a report profile as described above
- select this profile in the report-module

**Comment by MrGeneration** [comment]
This also affects the E-Mail-Address filtering on reports (if set to IS) the result will be empty (even without further clauses). If you set E-Mail-Address to "IS NOT", Reporting will show stuff according to clauses but WITH the E-Mail-address you tried to filter out.

Ticket#1026414

**Comment by MrGeneration** [comment]
This also affects TreeSelects. Interestingly the preview filters (when you configure report-profiles) is showing the expected results - but a soon as you open the report it's "broken".

In my field test, when my tree select looks the following:
![image](https://user-images.githubusercontent.com/6549061/48195983-77689980-e351-11e8-808d-f16ff87c41de.png)

And my selection for the report is just for Key "1", it will display the results for Keys "1" and "1-2".
If I now select Key "1-2" for displaying, the reporting even returns 0 results.


This impacts customer with Ticket#1030589

**Comment by MrGeneration** [comment]
This also affects if you're trying to filter for owner not being the current owner.

This affects Ticket#1034280
