### ISSUE TITLE
Wrong recipient on reply to Received call

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#206]
When replying to a Received call (New Ticket => Received Call) I expect to write an e-mail to the customer. Instead the agent's e-mail address is used.
Even the article look weird:

![image](https://cloud.githubusercontent.com/assets/378324/19075457/4580a08c-8a45-11e6-8646-2636602bf1bf.png)

The from should be the customer's name.

**Comment by martini** [comment]
@martin-schulte Issue with wrong recipient on reply is here.

**Comment by rkaldung** [comment]
The behavior works now as expected, but the name shown in From is still wrong and the avatar too.

**Comment by martini** [comment]
As discussed. A own origin_by_id for Ticket::Article is needed. Needs some time for implementation.

**Comment by rolfschmidt** [comment]
Hi @rkaldung 
This bug should be fixed now in develop branch.

-Rolf
