### ISSUE TITLE
Download of c&p image results in cryptic filename without extension (internal ticket: #1020861)

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#2062]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): package
* Operating system: Linux
* Database + version: Postgres
* Elasticsearch version: 5.6
* Browser + version: Safari

### Expected behavior:

* If I download an image using the provided popup I expect to have a valid filename (file-1... or something like this)

### Actual behavior:

* A test ticket is available at (#1020861)
The image name is not generated (as usual on C&P images) and a random string is shown
![image](https://user-images.githubusercontent.com/804939/41156748-8294b9ac-6b23-11e8-8026-8f74c030ec39.png)

### Steps to reproduce the behavior:

* Import test mail
* Click on image
* hit "download"
* check extracted file

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
This is a duplicate of #1246
