### ISSUE TITLE
Show message when search returns 0 results

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#2067]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): source
* Operating system: macOS
* Database + version: Postgres
* Elasticsearch version: 5.6
* Browser + version: Safari

### Expected behavior:

* There should be a message when a search returns 0 results

### Actual behavior:

* There is no message or info shown. A user may try again and again because there is no feedback.

### Steps to reproduce the behavior:

* search for something which returns no result

**Comment by mrflix** [comment]
Fixed in 0db8c28bd57b7cad7deb8d96e08c618dd34b8692:

![screen shot 2018-11-23 at 15 54 51](https://user-images.githubusercontent.com/60777/48949416-2bfce080-ef38-11e8-99ec-b079513057c3.png)
