### ISSUE TITLE
Cannot close tickets when you reply to an E-Mail at the same time

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2069]
### Infos:

* Used Zammad version: 2.5.x
* Installation method (source, package, ..): package (zypper)
* Operating system: openSuSe 42.3
* Database + version: postgreSQL 9.6-1.1
* Elasticsearch version: 5.6.6
* Browser + version: Google Chrome latest and Firefox latest

### Expected behavior:

* when you reply on a ticket by E-Mail and also say "close" as new state for the ticket, the ticket should get get closed state after hitting "Update"

### Actual behavior:

* when you reply on a ticket by E-Mail and also say "close" as new state for the ticket.
* After hitting "Update", the state changes from closed to new to open
* When that's done, you can close the ticket without a problem

### Steps to reproduce the behavior:

* Create a test ticket (receiving a E-Mail for example
* hit reply, type some text and change the state to "close"
* hit Update (the state will not be "closed")

Please also see this GIF I made:
![zammad-close-on-update-gone](https://user-images.githubusercontent.com/6549061/41279737-936d9138-6e2d-11e8-8f11-d264a5eaaab1.gif)

I also noticed, that this only happens, if you reply by E-Mail. If you add a note, this does not happen and works as expected!

I will update this post after I tested a zammad.com instance to let you know if the instances of paying customers are affected as well.

Yes I'm sure this is a bug and no feature request or a general question.

Edit: Yes, also hit's the commercial version. Test-Instance is: issue-2069.zammad.com
You're free to use / delete that instance at any time :)

**Comment by martini** [comment]
@MrGeneration thanks for this report. It's fixed now for stable.

Feedback is welcome!

**Comment by MrGeneration** [comment]
Sorry for the delay - just wanted to let you know that the problem is fixed after applying the Update with the new patch. Thanks for the fast fix!
