### ISSUE TITLE
Ability of deleting customers and / or all ticket at once.

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2074]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Issue documented within Privacy-Doc

### Expected behavior:

* Ability of deleting a certain customer and all the related tickets at once.
* Ability of deleting all tickets at once.
* Ability of deleting customers without tickets.

### Actual behavior:

* Deleting users is only possible via rails console

**Comment by martini** [comment]
More specification feedback:

1) We need a "danger zone" (like you know it from gitlab/github) in admin interface
All actions should be secured by a modal dialog like:

<img width="702" alt="screen shot 2018-06-22 at 11 17 21" src="https://user-images.githubusercontent.com/110226/41768938-fc773bf6-760d-11e8-9ce3-5f4e4d153597.png">

In addition Zammad should show how many objects are affected and then the user need to accept this again.

2) Option "Ability of deleting all tickets at once."
 -> Just a button where a REST controller will delete all tickets.

3) Option "Ability of deleting customers without tickets."
 -> Just a button where a REST controller will search for customers without tickets and delete them.

4) Option "Ability of deleting a certain customer and all the related tickets at once."
 -> Have a auto completion to select the related customer. Then send the customer id to a REST controller will search for that customer and delete the tickets, then the customer as one action.

**Comment by xf-** [comment]
@martini could you post a query (cli) to delete all users (group customer) without tickets. I use the scheduler to delete tickets marked as spam, but can't delete users. I found no example in docu for suers.
https://docs.zammad.org/en/latest/admin-console.html

**Comment by der-manu** [comment]
Hello and good morning.
I ran ito the same problem, I Imported a bunch of users and got some fields mixed up. So having a rails comnmand to delete all users whom are not involved in any ticket would help me out. So I am asking like xf- @martini if he could provide a fancy sniplet.

**Comment by rlue** [comment]
@xf- and @der-manu, please confirm with Martin before trying this, but I believe the following query should return all ticketless customers:

```ruby
User.with_permissions('ticket.customer').where('id NOT IN (SELECT customer_id FROM tickets)')
```

This is missing all sorts of safety checks we'll be applying in production. If you're willing to manually confirm the deletion of each single user, [here's a little script you can use](https://gist.githubusercontent.com/rlue/3423aa71ca14aa5266d3436d6f2a6b65/raw/7daae8c085f1e251f4e0ad0fd03f728d410606de/purge_ticketless_customers.rb). Download it to your Zammad server and then run it with `zammad rails r <path_to_script>`, or just run the following in your zammad directory:

```sh
$ zammad rails r <(curl -sS https://gist.githubusercontent.com/rlue/3423aa71ca14aa5266d3436d6f2a6b65/raw/7daae8c085f1e251f4e0ad0fd03f728d410606de/purge_ticketless_customers.rb)
```

**Comment by der-manu** [comment]
-> User.with_permissions('ticket.customer').where('id NOT IN (SELECT customer_id FROM tickets)')

this gives a correct output, if put in rails console.
The script you provided (thanks a lot), but I cannot get it running.

**Comment by rlue** [comment]
I'm happy to work through the problems in the script with you. Do you get _any_ output? Does it at least print how many ticketless customers are in the system?

---

Alternately, if you're in a big hurry and you're **110% sure** you want to delete all of the users given by that original query, adding `.each(&:destroy)` to the end of it will do.

But 1) this might fail halfway through if some of your ticketless customers are linked to other DB records, and 2) I can't advise bulk-deleting records on a production database like that. :\\

**Comment by rlue** [comment]
**WARNING:** Please make sure you make a backup of the database and know how to restore it before following any of my advice, just in case things go wrong. Deleting records in bulk via the console is dangerous, and even little typos can cause big problems.

**Comment by der-manu** [comment]
Yeah, thanks a lot, this helped me out. Implementing a housekeeping section into zammad is a pretty great idea.

**Comment by thorsteneckel** [comment]
JFI: We need to cover the use case described in #381 when continuing working on this.

**Comment by LittleNo** [comment]
Any news on this one?

I may add another two aspects regarding GDPR:
1. the law requires not only deleting the specified data, but to be able to display all stored data related to a person as well. The best solution for this would be a PDF export that combines all personal data as well as all related ticket information.
2. Not only the customer person must be able to delete their own personal data, but the data protection officer must have this ability too.

Anyway, every organisation using zammad is in urgent need of a feature to meet those GDPR requirements. Manually deleting entries in database is no practical solution in a production environment.

**Comment by MrGeneration** [comment]
I'm locking the conversation now, as bumps don't really help :(
We're working on it, the current state is "Waiting for QA".

Sorry for us taking so long, but this wants to be done very careful.
We can continue the discussion here: https://community.zammad.org/t/gdpr-dsgvo-delete-function/2569/3

As also mentioned, for manual deletion via console, you can also consider the following doc:
https://docs.zammad.org/en/latest/console/dangerzone-for-experts.html
