### ISSUE TITLE
There's no refresh on overviews if tickets escalate.

### ISSUE THREAD

**Issue by Franselbaer** [zammad/zammad#2076]
![bildschirmfoto 2018-06-14 um 10 42 12](https://user-images.githubusercontent.com/11044625/41401277-b6c2055e-6fbf-11e8-923a-dc1eb042004d.png)

Overview does not refresh when ticket escalates. I get a notification but the list still shows "escalated 0" even when i click around. Only if i reload whole page this is updated. 

You should implement some autorefresh.

**Comment by thorsteneckel** [comment]
Please use the issue template you removed. It's really important for us maintainers to have the required information. I have to close this issue in the meantime. Feel free to update your post. I'll reopen the issue afterwards.
