### ISSUE TITLE
Notify / Mention other agents / Subscribe to Tickets

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#208]
Ich lese ein Ticket und habe eine Rückfrage an einen anderen Agenten:

![screenshot_20161012_133459](https://cloud.githubusercontent.com/assets/210874/19308603/bd912cea-9080-11e6-8f83-c63add940725.png)

Diese Schreibweise "@nutzername" verwenden wir sehr oft, obwohl Zammad damit nichts macht. Offenbar wünschen sich die Nutzer sowas häufiger. Aktuell kann ich als Eigentümer das Ticket jetzt an den weiter geben, dem ich die Frage gestellt habe. Dann verliere ich es aber aus den Augen. Oder ich muss den Empfänger der Rückfrage auf anderem Wege (Mail, Telefon) auf die Frage aufmerksam machen. Wie würdet Ihr das lösen?

* T#1068412, #1078721, #1078020

**Comment by monotek** [comment]
+1

**Comment by Julian0o** [comment]
+2

**Comment by brightcolor** [comment]
+3

**Comment by dynamicman36** [comment]
+1 
Super Feature, das wäre Klasse!

**Comment by morphxle** [comment]
+1

**Comment by jacotec** [comment]
+1!

**Comment by martini** [comment]
More people like this feature soon (including me). 

For this feature we need to maintain a "username" for each agent (@FirstnameLastname would not be uniq). Would this be ok for you? Any other ideas?

**Comment by Julian0o** [comment]
@martini 
The Mailadress could be the unique username in the background. The search criteria could be first-, lastname and mailadress. When you type @ there should appear a list with all agents involved in this ticket displayed wich you can select. When you start typing, it is searching within all agents and you can select the others not yet mentioned in this ticket. 

Its almost like here in github or at facebook.

**Comment by thorsteneckel** [comment]
As discussed: An autocomplete would be great just like the one of the text modules.

Further thoughts:
Another UX improvement could be to allow users to choose an alias like e.g. in Mattermost.

So if a user starts typing "<space>@" (like here on Github) a text modules like list (or like here on Github) with the full name and an optional alias pops on listing entries like: "Martin Edenhofer (martini)". Both attributes should be searchable key insensitive and without spaces. Like "martine" should find "Martin Edenhofer". Aka "fuzzy search".
Only agents with the required permissions for this ticket should get listed. It would be really nice to order them in a logical way like "last used/active" or "favs" first or something. 

These should be wrapped up and stored properly in a special div or something. This allows us and others to parse and handle them in any interface or application now and later. Maybe something like `<div data-mention="martinedenhofer@your.tld"></div>` which gets converted by the UI to "Martin Edenhofer (martini)". This allows the user to change its name (like marriage e.g.) or alias without having old/wrong mentions. Even deleted or disabled accounts could be displayed in a special way later.

Custom HTML elements for this would be great like "<mention>martinedenhofer@your.tld</mention>" but are not supported yet (http://caniuse.com/#feat=custom-elements) 😞  

I'm not sure how unique the email will be. We have some users where the mail changed over the time. Might be even better to use the user id. I don't think that neither the id/email nor any other technical identifier should be visible to the user.

PS: Would love to see this 😍

**Comment by zabarabab** [comment]
Sounds like a good plan!

> Maybe something like <div data-mention="martinedenhofer@your.tld"></div> which gets converted by the UI to "Martin Edenhofer (martini)". This allows the user to change its name (like marriage e.g.) or alias without having old/wrong mentions.

I don't get how `martinedenhofer@your.tld` allows the user to change its name. But I guess there is already a solution for changing names in Zammad and you want to reuse it here.

**Comment by martini** [comment]
Update: Layout example to unsubscribe from ticket where I was involved (added via @user in article). Can also be used to subscribe without adding me via @user to new article.
 
<img width="1386" alt="screen shot 2016-12-19 at 15 47 05" src="https://cloud.githubusercontent.com/assets/110226/21316801/b2b2a8f0-c602-11e6-8e6d-478f7e8df8f4.png">

**Comment by gerbsen** [comment]
+1

**Comment by thorsteneckel** [comment]
A list of notified users would be great - just like here on github:

![bildschirmfoto 2017-01-10 um 15 05 49](https://cloud.githubusercontent.com/assets/3873515/21809047/50673efe-d746-11e6-9fab-6210ed4d6e15.png)

**Comment by skibson** [comment]
+1

**Comment by RionoirCom** [comment]
+1

**Comment by ktwe** [comment]
+1

**Comment by zabarabab** [comment]
And while we're introducing markup in notes, I'd like to have `#941111` as link to Ticket 941111 ;-)

**Comment by MartinBorg** [comment]
I don't yet understand this feature: Would it be necessary to be mentioned or comment on a ticket to be notified? Sometimes one is interested in subscribing to a ticket (i.e. getting emails for all updates on that ticket), but has nothing to comment. Or would that be #822?

**Comment by morphxle** [comment]
Hi guys, 
do you have some good news for us?

**Comment by dennybresch** [comment]
+1

**Comment by backbord** [comment]
+1

**Comment by babakkazemi** [comment]
+1

**Comment by Julian0o** [comment]
+1

**Comment by hanneshal** [comment]
To stop the unnecessary +1 posts I lock this thread. We are working on this stuff... see https://zammad.com/news/status-outlook

No ETA, but we are working on it.

**Comment by zabarabab** [comment]
Here is a screenshot of a similar feature in mattermost:

![grafik](https://user-images.githubusercontent.com/210874/33739034-d4071e5a-db9b-11e7-88d3-0b8b86bd8a65.png)

![grafik](https://user-images.githubusercontent.com/210874/33739131-38511348-db9c-11e7-90f1-d5f7510a843e.png)

**Comment by KoJie** [comment]
You have waited long enough for this feature and want to see it finally realized? Well then, we have good news for you. Become a feature sponsor and let the feature spring to life in one of the next Zammad versions. We are currently looking for more contributors to make this project a reality together with us and other Zammad users. By sharing the costs, you get additional influence on the implementation of the function and also receive a little advertising for your organization on the day of publication, if you wish.

So please contact us at sales@zammad.com to bring the implementation a step ahead.
