### ISSUE TITLE
escalation_at are not updated correctly

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2082]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* keep escalation_at updated only every action

### Actual behavior:

* create an SLA with first response time
* send a ticket as customer into zammad
* reply as agent and escalation_at is not updated (only on second reply) 

@hanneshal

**Comment by hanneshal** [comment]
We need to reopen. We missed a case.
