### ISSUE TITLE
Time accounting not tracked for agents and not showing on dashboard

### ISSUE THREAD

**Issue by kntphu** [zammad/zammad#2084]
Infos:

* Used Zammad version:2.0
* Installation method (source, package, ..):deb package
* Operating system: Ubuntu 16.04
* Database + version:
* Elasticsearch version:5
* Browser + version: Firefox 60.0

### Expected behavior:
time is measured for every agent working on a ticket.
could be displayed as total time and specific agent time if multiple agents are working on the same ticket
Time accounting in admin section shows times for agents in overview (export)
ticket section in overview shows all agents which worked on a ticket

dashboard displays time in the corresponding box

∅ Waiting time today
My handling time: 0 minutes
Average: 0 minutes
![6-15-2018 10-58-52 pm](https://user-images.githubusercontent.com/9064148/41478110-bc2b7f16-70f0-11e8-87ed-d11c1f2b42aa.jpg)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a feature request/technical question. You can ask questions over at https://community.zammad.org/ - Closing now.
