### ISSUE TITLE
Feature Request: Add logged time per ticket to reports 

### ISSUE THREAD

**Issue by spelroth** [zammad/zammad#2086]
* Used Zammad version: 2.5.x
* Installation method (source, package, ..): centos repository
* Operating system: centos 7 

### Expected behavior:

* When exporting report for a client each ticket would have the time spent information

### Actual behavior:

* As for now there isn't any information about time spent on each ticket just opening and closing timein the report

### Steps to reproduce the behavior:

* Generate a report

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a feature request. You can ask propose feature requests over at https://community.zammad.org/ - Closing now.
