### ISSUE TITLE
Customer response via note or email does not trigger escalation

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#2091]
### Infos:

* Used Zammad version: 2.5

See https://github.com/zammad/zammad/issues/1322. Here we fixed the response via note to trigger also the escalation like an email response of a customer would do.

From zammad 2.2.2 to 2.4 everything worked like expected.

Now with zammad 2.5 an email response will not trigger the escalation again. Note response still works.

**Comment by martini** [comment]
Hi @hiaz 

can you tell me, what package version you have installed? There was an issue #2082 which got fixed 5 days ago. I hope your issue is a duplicate of that.

Thanks for feedback!

 -Martin

**Comment by hiaz** [comment]
Hi @martini 

sorry. Yes, a duplicate. I just searched in the "open" issues. Did not expect that your resolve time is so short ;).

Mathias

**Comment by martini** [comment]
@hiaz best helpdesk service for best PBX vendor. 😻

**Comment by martini** [comment]
@hiaz Just a note. There is a follow up fix for #2082 available.
