### ISSUE TITLE
Zammad backgroundprocess Error

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#2095]
### Infos:

* Used Zammad version: 2.5.x 
* Installation method (source, package, ..): RPM
* Operating system: Centos
* Database + version: Mysql
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:
During our experience with version 2.4.x, the only unusual health error was unprocessed email(s) in Monitoring Section.

### Actual behavior:
Currently. after updating to version 2.5.x, I can see these errors:

    415 failing background jobs.
    Failed to run background job #1 'BackgroundJobSearchIndex' 10 time(s) with 160 attempt(s). 

### Steps to reproduce the behavior:
Installing 2.5.x, using 11G ram, CPU 4 cores, using 10 agents.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
I'm pretty sure that this is an issue with your local installation 😱 Have you had a look at your `log/production.log`? There should be `ERROR`s which indicate what's going wrong. It might be a connection issue to your Elasticsearch (indicated by the `BackgroundJobSearchIndex` backend).

If you have any further technical questions please refer to the [community board](http://community.zammad.org/) 👍 Closing now.
