### ISSUE TITLE
CentOS 7 HTTPS Error 404 - Not Found

### ISSUE THREAD

**Issue by Pupp3tm4st3r** [zammad/zammad#210]
Hi,
when adding the RPM Repository in my CentOS 7 Box (clean, fresh install) and the "yum update" I always get:

https://rpm.packager.io/gh/zammad/zammad/centos7/release-1.0/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

**Comment by thorsteneckel** [comment]
Hi @Pupp3tm4st3r - I can verify the issue. Seems that packager.io is currently going through some troubles. We are on it!

**Comment by thorsteneckel** [comment]
@Pupp3tm4st3r sorry for the false information. We still had the old links in our documentation - oops! We've corrected it with the commit above. The site will get synced in a few minutes, see http://zammad.org/documentation/install/install-rpm
