### ISSUE TITLE
Read-only custom objects 

### ISSUE THREAD

**Issue by gijsrutten** [zammad/zammad#2102]
### Info:
Ticket-ID: #1078225 

### Desired behavior:

Create an additional _view_ option to the two existing option unter **System > Manage objects** for each role. Currently you can define if an agent or a customer can enter a value in the object either only at creation of the ticket or if he/she can edit the value at any time. 

It would be useful to have a third option called **view-only** where for example an agent can edit the value of the object and a customer can only view the value. 

<img width="640" alt="screenshot 2018-06-28 08 18 47" src="https://user-images.githubusercontent.com/26574517/42016501-0f25e07a-7aac-11e8-91d3-1d2aab4a3da5.png">

Referring to [https://community.zammad.org/t/ticket-object-from-type-text-url/868](https://community.zammad.org/t/ticket-object-from-type-text-url/868)

**Comment by ArnaudBpro** [comment]
Hi,

It's in the road map ? I really need to have "view-only- field on customer view :)

Regards and thanks for your product !
Arnaud

**Comment by MrGeneration** [comment]
Sorry but we can't provide any feedback on when this is coming (and if).
This is a feature backlog.

We'll update this issue accordingly as something moves in any direction. :-)

**Comment by thpoul** [comment]
![image](https://user-images.githubusercontent.com/1605817/152767368-bb395276-080c-4135-9642-9546f100da02.png)

Don't seem able to find this feature on latest zammad 5.0.3 (5.0.3-1643716628.f44a1a2b.focal)

**Comment by MrGeneration** [comment]
Agreed.
Please open a new bug report with note of regression on this issue.
