### ISSUE TITLE
clickable URL (template) for ObjectManager Attribute

### ISSUE THREAD

**Issue by gijsrutten** [zammad/zammad#2103]
The custom object are very useful and could help us a lot customizing the ticket system. But there is one object type, I don’t understand how it is supposed to work. It is the object from _type_ **text > URL**. To create one, go to _System > object manager > create_. Choose format=text and type=URL.

![ca879b0e05b5f08c3182068060b1af9f469b5b35_1_436x500](https://user-images.githubusercontent.com/26574517/42017938-e7740f84-7ab0-11e8-9024-0869dfcea6b7.png)

Once the object has been created, it displays a textfield in the ticket sidebar. But no matter what I enter and no matter what type of user rights I choose, the field will always be a text field. It never turns into a clickable URL.

From the customer view, the link is also just a text field.

![8c6b8808e24c9513d43c3238da6ff3d83a9c48f0_1_545x500](https://user-images.githubusercontent.com/26574517/42017985-03dbd940-7ab1-11e8-9947-5d60d60bd7bb.png)

Ideally the URL Object is just an input field that creates an array. Once entered a value, it becomes a clickable link. Additional options might be to not only store the URL itself but also a title or even an Icon. 

If you think this further, it might also be an option to create a "URL" object that simply displays a button. Enter a default value, button color and button title and you could create something like the screenshot below.

<img width="833" alt="screenshot 2018-06-28 09 31 07" src="https://user-images.githubusercontent.com/26574517/42019816-5db104f4-7ab6-11e8-9360-5d37b49138cc.png">

Referring to [https://community.zammad.org/t/ticket-object-from-type-text-url/868](https://community.zammad.org/t/ticket-object-from-type-text-url/868)

**Comment by B4DschK4Pp** [comment]
I just came across this, as I was experimenting with custom fields and links.
It would be great if one could use the url type with format int as well and add some sort of logic to the links created by using the fields value as a variable for the link.

Example:
I would like to add a custom field with a number referring to an issue in our dev ticketsystem (Redmine). So I could add a field with format int that holds the number of my redmine issue, related to the customers ticket in Zammad.
If I then click the Submit button, as shown in the picture above from gijsrutten, it should generate the link to redmine like https://myRedmineSrv/issue/{FieldValue} .

Cheers
Sebastian

**Comment by MrGeneration** [comment]
You're kinda hijacking this, as you're posting a rather technical question.

You can always use variables in links (already), as long as you#re not inserting a link that already contains the link. so

`http://domain.tld/blah/#{ticket.blah}` will be a clickable link as soon it's send out.
Use `::` in the backend for searching for variables (custom objects will be available inside there).

I'll lock this conversation now - if you have further questions, please go to our community https://community.zammad.org :)

**Comment by thorsteneckel** [comment]
@MrGeneration - this is resolved with the commits above. We need to update the admin documentation accordingly - right?

**Comment by MrGeneration** [comment]
Correct, right now I'm lacking to understand how this feature works, it would be great to learn it :)

![image](https://user-images.githubusercontent.com/6549061/65315323-2b54cb00-db98-11e9-9e9c-fcbbac81350c.png)

**Comment by thorsteneckel** [comment]
Hey @rolfschmidt the machine. Could you contact @MrGeneration and explain the ObjectManager Attribute link-template functionality to him? Since you've a great part of it I think you could do it best.

**Comment by MrGeneration** [comment]
Thanks to the help of Rolf I could finish the docs for this.
This took a bit longer, because I decided to also introduce docs for the variables within Zammad (still WIP).

The commits can be found in this Branch: https://github.com/zammad/zammad-admin-documentation/tree/zammad_3-2

Preview:
![image](https://user-images.githubusercontent.com/6549061/65535857-840ec580-df02-11e9-8e60-f892dbd62d77.png)
