### ISSUE TITLE
Shown ticket changed unexpected when viewing an attached image

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#2104]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): source
* Operating system: CentOS 7
* Database + version: Postgresql 
* Elasticsearch version: ?
* Browser + version: Chrome latest

### Expected behavior:

* Modal dialog closed when opening another ticket by clicking on a browser notification.

### Actual behavior:

* When a ticket is opened via browser (desktop) notification a modal dialog stays open

### Steps to reproduce the behavior:

* Enable preview feature `rails r 'Setting.set("ui_ticket_zoom_attachments_preview", true)'`
* Open a ticket with an attached image
* Wait for a new ticket browser (desktop) notification
* Click on the browser (desktop) notification and see how the ticket under the modal dialog changes while the image stays.

Yes I'm sure this is a bug.

**Comment by SummerStorm** [comment]
Fixed via bc489aecef6a1026fc2f4bbeeeb1dbdd89c386c7.
