### ISSUE TITLE
Update button unusable after modal dialog is gone

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#2105]
### Infos:

* Used Zammad version: develop (pre 2.6)
* Installation method (source, package, ..): source
* Operating system: CentOS 7
* Database + version: Postgresql 
* Elasticsearch version: ? 
* Browser + version: Chrome latest / FF 60 / FF 61 / Safari 11.1.1

### Expected behavior:

* Update button is usable

### Actual behavior:

* Update button us unusable

### Steps to reproduce the behavior:

* Create an article with enable time accounting and close the dialog by clicking outside the dialog (Note: By using ESC or X it's working fine).
![image](https://user-images.githubusercontent.com/378324/42025486-f32ec404-7ac4-11e8-992a-3288ba6d2520.png)
* Check the submit button
![image](https://user-images.githubusercontent.com/378324/42025518-09a90cbc-7ac5-11e8-8f4b-c0607c5209c7.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by SummerStorm** [comment]
Fixed via 730ed13b7b011b12f4d6767100ece769b721885d.
