### ISSUE TITLE
Cannot create tickets after update to 2.5

### ISSUE THREAD

**Issue by tbsfnk** [zammad/zammad#2106]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): deb
* Operating system: debian 9
* Database + version: not relevant
* Elasticsearch version: not relevant
* Browser + version: not relevant

### Expected behavior:

* Createing tickets through web interface

### Actual behavior:

* The ticket is not going to be created... 
And the 3 buttons (incoming call, outgoing call and mail) are missing...
![grafik](https://user-images.githubusercontent.com/33467318/42076676-655acee0-7b76-11e8-8f16-84a91d8cd2ad.png)

### Steps to reproduce the behavior:

* update zammad from 2.4 to 2.5

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by tbsfnk** [comment]
Update: tickets through mails are going to be created.

**Comment by martini** [comment]
Hi @ToubieObie 

in Zammad 2.5 there is an feature to customise the 3 buttons (incoming call, outgoing call and mail). For that a new config setting is created. In you case it seems that the config setting is missing.

So I guess one migration is not executed. Please check the following:

1) systemctl stop zammad
2) zammad run rails r 'Cache.clear'
3) zammad run rake db:migrate
4) systemctl start zammad
5) Reload your browser

Is it now working again?

 -Martin

**Comment by tbsfnk** [comment]
yesss thank you!! Now it is working again 👍

**Comment by Fabiola-ZC** [comment]
Hola, es normal que se tarden los comandos al ejecutarse.
