### ISSUE TITLE
View have to refresh automatically

### ISSUE THREAD

**Issue by schmanat** [zammad/zammad#2112]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): deb
* Operating system: Ubuntu 16.04
* Database + version: postgres 9.5
* Elasticsearch version: 5.x
* Browser + version: latest Chrome, latest Edge 

### Expected behavior:

* Views should automaticly refresh.

### Actual behavior:

* I have a view (my tickets). If a ticket is assigned to me, I see in the view the badge with the amount of the tickets. For example it shows me 15. The view itselt shows only 7. After a refresh of the browser i see all the tickets (15). In version 2.4 I see always all tickets. 
The strange thing is partially the views is working correct, but sometimes I have to refresh it manually.
Is there a way to debug this issue

### Steps to reproduce the behavior:

* I can't really reproduce it allways.
---
* Open Zammad and stay it open for 24 h 😄 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @schmanat  - this is more a technical question. Please refer to our [community board](http://community.zammad.org/) for those. You can add me to the topic and I will try to help. We can't reproduce it and works pretty solid which indicates that this only affects your installation.

For the community topic:
Can you ensure that all Zammad processes (especially the Websocket and Scheduler) run properly? How is your system load? How many jobs are in your `Delayed::Job` table (run: `Delayed::Job.count` in the [Zammad rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console))?
