### ISSUE TITLE
Upgrading Zammad overwrites es_url with default value

### ISSUE THREAD

**Issue by raunsbaekdk** [zammad/zammad#2115]
### Infos:

* Used Zammad version: 2.5.0-1530602545.1d4ddd46.stretch amd64
* Installation method (source, package, ..): package (https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 9 main)
* Operating system: Debian GNU/Linux 9 (stretch)
* Database + version: MySQL: 5.7.21-20
* Elasticsearch version: 5.6.7
* Browser + version: Not relevant

### Expected behavior:

* Keep es_url to custom setting

### Actual behavior:

* Rewrites es_url to: 'http://127.0.0.1:9200'

### Steps to reproduce the behavior:

* Change es_url in table: settings to your off site Elasticsearch server
* apt-get update
* apt-get -y install zammad
* Check es_url in table: settings

I think the problem might be this snippet: https://github.com/zammad/zammad/blob/b359e2624cdd757fab21f2c8cafbe1948828f487/contrib/packager.io/functions#L249

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @monotek - I think this is a valid point. Do you think we're able to cover this somewhere in the packager logic? If we need a helper method in the Zammad context let me know. Thanks!

**Comment by monotek** [comment]
Should be easy to fix... Maybe I can do it this week...

**Comment by monotek** [comment]
should be fixed by: https://github.com/zammad/zammad/commit/0dec2e50456dd0b46ad47d02001c25994964afa1

**Comment by thorsteneckel** [comment]
Looks like this didn't work: https://github.com/zammad/zammad/issues/2068#issuecomment-414592902 (@lukrop)

Reopening. @monotek - could you please verify this?

**Comment by martini** [comment]
I did test it before releasing 2.6. And it worked for me. Issue was fixed by https://github.com/zammad/zammad/commit/101d7d975cbc2cc61748a587a6eff6f83c6b35ce#diff-63dc4d928992e597f0e75e8880ca8da3

**Comment by thorsteneckel** [comment]
@raunsbaekdk - could you please verify if it works for you, too?

**Comment by monotek** [comment]
setup_ealsticsearch was on top of db creation for a reason... 
elasticsearch_searchindex_rebuild will likely fail as elasticsaearch bootup time is to long.

**Comment by raunsbaekdk** [comment]
Hi @thorsteneckel 

I can confirm that the initial fix worked for me as well. I have just upgraded to: 2.7.0-1534831450.d2216463.stretch from 2.6.0-1533276474.9b495847.stretch and settings persists.

Since the fix didn't work for @lukrop could it be that his Elasticsearch instance runs on the same server?

Semi log from update:
`# Configuring Elasticsearch...
-> removing [ingest-attachment]...
-> Downloading ingest-attachment from elastic
[=================================================] 100%?? 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessClassInPackage.sun.java2d.cmm.kcms
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission createAccessControlContext
* java.security.SecurityPermission insertProvider
* java.security.SecurityPermission putProviderProperty.BC
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]-> Installed ingest-attachment

 It seems you're running an external Elasticsearch server on https://cluster.rest.cvrapi.dk
Stopping local elasticsearch server...

 Please get sure to install the 'ingest-attachment' plugin on your Elasticsearch server by:
/usr/share/elasticsearch/bin/elasticsearch-plugin -s install ingest-attachment

After this you might need to rebuild the searchindex by:
zammad run rake searchindex:rebuild`

**Comment by raunsbaekdk** [comment]
Hi @thorsteneckel 

I can confirm that the initial fix worked for me as well. I have just upgraded to: 2.7.0-1534831450.d2216463.stretch from 2.6.0-1533276474.9b495847.stretch and settings persists.

Since the fix didn't work for @lukrop could it be that his Elasticsearch instance runs on the same server?

Semi log from update:
# Configuring Elasticsearch...
-> removing [ingest-attachment]...
-> Downloading ingest-attachment from elastic
[=================================================] 100%?? 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessClassInPackage.sun.java2d.cmm.kcms
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission createAccessControlContext
* java.security.SecurityPermission insertProvider
* java.security.SecurityPermission putProviderProperty.BC
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]-> Installed ingest-attachment

 It seems you're running an external Elasticsearch server on 
Stopping local elasticsearch server...

 Please get sure to install the 'ingest-attachment' plugin on your Elasticsearch server by:
/usr/share/elasticsearch/bin/elasticsearch-plugin -s install ingest-attachment

After this you might need to rebuild the searchindex by:
zammad run rake searchindex:rebuild

**Comment by lukrop** [comment]
@raunsbaekdk ES is indeed installed on the same machine. It seems to be a dependency of the zammad package. Regarding to systemctl it's also active but the process exited. I never consciously installed or configured ES on this machine.

**Comment by thorsteneckel** [comment]
Thanks @raunsbaekdk - seems like this is an issue only affecting your installation 😕 Please open a now topic over at the [community board](http://community.zammad.org/) to discuss it further because comments here will get send to over 100 people (watching this repository). Thanks for your understanding. Closing now.
