### ISSUE TITLE
Option to add email channel WITHOUT importing emails

### ISSUE THREAD

**Issue by rafamerino** [zammad/zammad#2121]
This option was commented on [this thread](https://github.com/zammad/zammad/issues/539), but was closed without resolving the real issue: 

Adding email channel of an existing email account with thousands of mails (my case), **will create a huge amount of unnecesary tickets**. 

I think it's necessary to add an option to **not import historical emails** in the process.

Thank your for your awesome work!

**Comment by thorsteneckel** [comment]
Hi @rafamerino - Thanks! But please read our intro text before creating issues. This is not an issue but a feature request. We're only handling issues on the issue tracker. You can propose feature requests over at https://community.zammad.org/ - Closing now.
