### ISSUE TITLE
Error: StatusCode 500 during forgot password feature

### ISSUE THREAD

**Issue by McPimp** [zammad/zammad#2123]
Zammad version: 2.5.x
Installation method:  Ubuntu
Operating system: Ubuntu 16.04

### Expected behavior:

Want to use the forgot password feature.

### Actual behavior:

Getting the following error:
Status Code 500
{"error":"Can't use Channel::Driver::Smtp: #\u003cArgumentError: SMTP To address may not be blank: []\u003e"}

Please will someone assist me?

Kind Regards
EB

**Comment by hanneshal** [comment]
You dont have an SMTP configured. This is no bug but a config issue. ;) 

regards

**Comment by McPimp** [comment]
Hi Hanneshal,

I do have the SMTP configured.
I know it is not a bug and is a config issue and will ask for help.

Do I configure the SMTP inside of Zammad or on the backend or both?
Cause I have tried and I still get the error
