### ISSUE TITLE
Report profile crashes if using absolute date

### ISSUE THREAD

**Issue by eugenkoenig** [zammad/zammad#2124]
### Infos:

* Used Zammad version: 2.5.x
* Installation method (source, package, ..): hosted by zammad
* Operating system: -
* Database + version: - 
* Elasticsearch version: -
* Browser + version: Firefox + Chrome (latest)

### Expected behavior:

* Creating new report profile with _absolute_ date (e.g. all opened tickets after 01.01.2018 8:00) shows all tickets in preview. Selecting this profile in reporting page should also show all tickets that were opened after this date. 

### Actual behavior:

* Selecting this reporting profile in reportings page causes error. But preview on creation of the profile works fine (see screenshots)

`StatusCode: 500: {"error":"unknown operator 'after (absolute)' for ticket.created_at"}`. 

### Steps to reproduce the behavior:

- Create new report profile (Admin -> Manage -> Report Profiles -> New Profile)
- Set name to anything
- Set `State` to `is new` (actually it doesn't matter what you select here)
- Add another filter field and select `Created at`+`after (absolute)`+`set date to anything` + `set time to anything`
- Save it
- Go into Reporting Page and select this profile -> Error

Yes I'm sure this is a bug and no feature request or a general question ;)

![bildschirmfoto 2018-07-12 um 19 26 05](https://user-images.githubusercontent.com/2119214/42649288-96d470a0-8609-11e8-8265-50025db8c2c8.png)
![bildschirmfoto 2018-07-12 um 19 26 25](https://user-images.githubusercontent.com/2119214/42649289-96f68a50-8609-11e8-90f6-ae32560a794e.png)
![bildschirmfoto 2018-07-12 um 19 26 35](https://user-images.githubusercontent.com/2119214/42649290-97197d12-8609-11e8-9059-0c95d2b2d200.png)
![bildschirmfoto 2018-07-12 um 19 26 54](https://user-images.githubusercontent.com/2119214/42649291-973ea042-8609-11e8-9afa-411f607895f7.png)

**Comment by martini** [comment]
Maybe a duplicate of https://github.com/zammad/zammad/issues/2098

@styleart What are the first 3 letters of the instance name?

**Comment by eugenkoenig** [comment]
@martini That looks similar to the other issue, yes. Should I do some other tests (e.g. with relative dates)? 
First three letters are 'bar'.

**Comment by martini** [comment]
@styleart yes, please reload your browser and test again (your instance is deployed with the fix for 2098). Feedback is welcome! 👍🏻

**Comment by martini** [comment]
@styleart by the way, the Zammad reporting is already done via timeslots (e. g. all new tickets in 2018 for each month). So normally it makes not so much sense to use date restrictions here. 

Just in case: We are working on a Grafana integration. We really ❤️ the visualisation possibilities of Grafana. 

Just in case, you are a paying customer, you also can contact us directly via support at zammad dot com.

**Comment by eugenkoenig** [comment]
@martini works like a charm now, thx for deploying the fix! 

We know about timeslots and actually will not use filters with absolute dates, but I haven't seen the old issue and just wanted to report it. So it wasn't urgent at all. :) 

What about grafana - great news! We use it for internal visualisations and would love to see it in Zammad!

**Comment by martini** [comment]
@styleart thanks for feedback! 👍
