### ISSUE TITLE
Email signatures trim trailing whitespace in text part

### ISSUE THREAD

**Issue by MorrisJobke** [zammad/zammad#2126]
### Infos:

* Used Zammad version: 2.4.0
* Installation method: package
* Operating system: Ubuntu 16.04
* Database + version: MySQL

### Expected behavior:

* having no trailing whitespace trimmed in text emails

### Actual behavior:

* trailing whitespace is trimmed in text part of emails - thus the signature separator `-- ` (dash, dash space) gets into a `--` only and is not recognized by all email clients anymore.

### Steps to reproduce the behavior:

* write an answer in Zammad like this:

```
Hello

-- 
This is the signature
```

Then the text part of the email should contain the `-- ` and not only the `--`.

**Edit** *sigh* also Github drops the space and thus both examples look the same. Check out the source to see the difference. It is about DASH DASH SPACE vs DASH DASH.

**Comment by thorsteneckel** [comment]
To support [signature blocks](https://en.wikipedia.org/wiki/Signature_block) the [RegEx removing trailing spaces](https://github.com/zammad/zammad/blob/9cfeec86bec2f2c567b632574409bbc4a5649398/lib/core_ext/string.rb#L284) should be improved. It may look something like this: [`^(?!--).+[[:blank:]]+$`](http://rubular.com/r/IrF0LBD5K3)

**Comment by andreasbuhr** [comment]
Just for completeness: The trailing space is required by RFC3676:
https://tools.ietf.org/html/rfc3676#section-4.3

**Comment by raid1** [comment]
Also leading spaces in .sigs are removed and an extra empty line inserted.
Example:
defined zammad signature:
![](https://spiegl.de/public/signature.png)


Resulting sig in the sent email:
```
sig test

 XXX YYY

--

line 1
 line 2
line 3
line 4
```
