### ISSUE TITLE
RequireJS _src Script

### ISSUE THREAD

**Issue by juliankoehn** [zammad/zammad#2129]
Zammad is searching for a id="zammad_form_script" to inject the CSS for the Form.

Line 120 of form.js
`        this._src = document.getElementById('zammad_form_script').src`

while i have to Require it via RequireJS

```javascript
<script>
require.config({
  "paths": {
    "ZammadForm": "//helpdesk.classyvaper.com/assets/form/form"
  },
  shim: {
    'ZammadForm': {
      deps: [
        'jquery'
      ]
    }
  }
});
require(['jquery', 'ZammadForm'], function($){
      jQuery = $;
      $(function(){
        $('#feedback-form').ZammadForm({
         messageTitle: 'Kontakt & Support',
         messageSubmit: 'Übermitteln',
         messageThankYou: 'Vielen Dank für Ihre Anfrage (#%s). Wir melden uns umgehend!',
         showTitle: true
 });
    });
 });
</script>
```

My Solution without editing the form.js was to add a "source" element instead of a script tag, but it's still dirty.

`<source  id="zammad_form_script" src="//helpdesk.classyvaper.com/assets/form/form.js" />`

Instead of replacing, it should just add the required Styles to the head
```javascript
$('<link>')
  .appendTo('head')
  .attr({
      type: 'text/css', 
      rel: 'stylesheet',
      href: '/css/your_css_file.css'
  });
```

**Comment by thorsteneckel** [comment]
Please use the issue template you removed. It's really important for us maintainers to have the required information. I have to close this issue in the meantime. Feel free to update your post. I'll reopen the issue afterwards.
