### ISSUE TITLE
Email notifications sending will be aborted mid-list if SMTP error code is received

### ISSUE THREAD

**Issue by andreaci** [zammad/zammad#2133]
I have problems when sending notifications by email.
Notifications are sent to a lot of users, but it's possible that some of them has invalid email address.

### Infos:

* Used Zammad version: 2.3.x (2.5.0 from apt-cache policy)
* Installation method (source, package, ..): Package
* Operating system: Debian 9
* Database + version: Postgre 9.6
* Elasticsearch version: 5.6.9
* Browser + version: any

### Expected behavior:

Handle invalid mailboxes gracefully and  send notification to all other users.

### Actual behavior:

The SMTP notifications channel starts sending emails, but stops at the first error generated by the server.

### Steps to reproduce the behavior:

Configure the SMTP server to return an error 550 on invalid email address and send a notification to that address.

Yes I'm sure this is a bug and no feature request or a general question.

I can see from the SMTP server that zammad stops sending messages after the first error.
I can't just remove users: they are imported from Active Directory and if I disable them, they come back at next sync.

This is the production.log related rows.
`E, [2018-07-17T09:04:04.212121 #11048] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: 550 User not found>`
`E, [2018-07-17T09:04:04.212219 #11048] ERROR -- : ["/opt/zammad/vendor/ruby-2.4.2/lib/ruby/2.4.0/net/smtp.rb:969:in check_response'", "/opt/zammad/vendor/ruby-2.4.2/lib/ruby/2.4.0/net/smtp.rb:937:in geto$`
`I, [2018-07-17T09:04:04.222962 #558]  INFO -- : Completed 200 OK in 100ms (Views: 0.8ms | ActiveRecord: 34.4ms)`
`E, [2018-07-17T09:04:04.240879 #11048] ERROR -- : ERROR: Transaction::Notification`
`E, [2018-07-17T09:04:04.240993 #11048] ERROR -- : ERROR: #<RuntimeError: Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: 550 User not found`

Support Ticket
#10134038

**Comment by martini** [comment]
Hi @andreaci 

I see it's about agent notifications. It seems to be a valid issue. We need to verify it. Thanks so far.

 -Martin

**Comment by realtarget** [comment]
Hi, we can confirm this problem which occured some minutes ago using mailgun as smtp:

```
E, [2018-08-28T12:58:00.835924 #21788] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::SMTPSyntaxError: 501 Invalid command or cannot parse to address
>
E, [2018-08-28T12:58:00.836022 #21788] ERROR -- : ["/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/smtp.rb:969:in `check_response'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/smtp.rb:937:in `getok'", "/opt/zammad/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/smtp.rb:865:in `rcptto'", "/opt/zammad/vendor/ruby-2.4.4$
E, [2018-08-28T12:58:00.898129 #21788] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::SMTPSyntaxError: 501 Invalid command or cannot parse to address
>
E, [2018-08-28T12:58:00.902839 #21788] ERROR -- : 2018-08-28T12:58:00+0000: [Worker(host:localhost pid:21788)] Job Observer::Ticket::Article::CommunicateEmail::BackgroundJob (id=2597) FAILED (0 prior attempts) with RuntimeError: Can't use Channel::Driver::Smtp: #<Net::SMTPSyntaxError: 501 Invalid command or cannot $
>
```

Feature idea: Integrate a button to "RESEND" emails.

**Comment by realtarget** [comment]
Addition: 
The problem also occurs after opening a new email ticket while sending the initial mail to a customer.

> Channel: Email::Account out  Can't use Channel::Driver::Smtp: #\u003cNet::SMTPSyntaxError: 501 Invalid command or cannot parse to address\n\u003e;unprocessable mails: 1","issues":["Channel: Email::Account out  Can't use Channel::Driver::Smtp: #\u003cNet::SMTPSyntaxError: 501 Invalid command or cannot parse to address\n\u003e","unprocessable mails: 1

**Comment by MrGeneration** [comment]
I could verify that Zammad does not send the mail to a valid recipient, as long as you also put wrong recipients inside. This works not as expected, Zammad should ignore specific mail command errors to ensure to still send mail to valid recipients.

Those codes are atleast (**only applies if you have more than one recipient, either in CC or TO**):
* `521` domain does not accept mail (rfc1846)
* `450`, `550`, `553` mailbox not found
* `551` user not local
* `552` action aborted (storage)

This list might be incomplete, only should ignore above codes in my opinion, as those are recipient related. All other errors would *normally* mean issues on the SMTP-Server anyway which would cause even more trouble.

Zammad should still parse a information of what mail addresses failed and will ideally also tell the agent which recipients worked without trouble.

**Comment by eugenkoenig** [comment]
Confirm, also just happened to us.

**Comment by MrGeneration** [comment]
@styleart I'm afraid that this doesn't help at all.
Please provide your environment information.

Edit: Apart from that the issue already is verified.

**Comment by eugenkoenig** [comment]
This is our self-hosted inhouse setup (latest release), not the one hosted on your side. Exact the same issue as above. Monitoring changed in the unhealthy state after a staff member just typed the first name and clicked on "Update" (instead of waiting a second and pick the full agent name with the email address). It stayed unhealthy, until I forwarded the email again (but used the right full email address). After that monitoring changed back to healthy. Just fyi @MrGeneration :)

**Comment by MrGeneration** [comment]
Thanks for the further input. If this would accidentely happen on your supported instance, this would be too bad. ;-(

---

A side note on the health state: The channel remains "unhealthy" until the next successful communication happens. So technically any other ticket could solve that issue as well. :-)

**Comment by eugenkoenig** [comment]
Ah, good to know! I was asking myself how to fix it so the site doesn't stay "down" in our monitoring. Thx for the hint, will be useful if it happens again in the future! :)

**Comment by cb0101** [comment]
The same error occurred in our Zammad Installation today. Under "Email Notifications" there is a message "Can't use Channel::Driver::Smtp: #<Net::SMTPAuthenticationError: 454 4.7.0 Temporary authentication failure: generic failure >" 
Zammad health is "false" but new tickets are coming in and responses to tickets are being sent out.

I tried to use the command rails r "p Channel.fetch" to see what is wrong, but there are no faulty entries visible. 

Is there a way to figure out which message/ticket causes the problem? 
Thank you very much!

**Comment by sascha73** [comment]
> I could verify that Zammad does not send the mail to a valid recipient, as long as you also put wrong recipients inside. This works not as expected, Zammad should ignore specific mail command errors to ensure to still send mail to valid recipients.
> 
> Those codes are atleast (**only applies if you have more than one recipient, either in CC or TO**):
> 
>     * `521` domain does not accept mail (rfc1846)
> 
>     * `450`, `550`, `553` mailbox not found
> 
>     * `551` user not local
> 
>     * `552` action aborted (storage)
> 
> 
> This list might be incomplete, only should ignore above codes in my opinion, as those are recipient related. All other errors would _normally_ mean issues on the SMTP-Server anyway which would cause even more trouble.
> 
> Zammad should still parse a information of what mail addresses failed and will ideally also tell the agent which recipients worked without trouble.

Hi @MrGeneration 
We found this conversation after encountering the same problem these days.
Apparently the issue is still present in version 5.0.x, or is it possible to configure the system to send to all working mail addresses, even if one or more addresses should not work?
That would be the expected behaviour in my eyes.
Of course, a message that some recipients have not received anything because the addresses cannot be found would also be good.
thanks a lot
Sascha

**Comment by MrGeneration** [comment]
Please don't hijack issues for technical questions.
Technical questions should belong in the community: https://community.zammad.org

As the issue is still open there obviously hasn't changed anything.

**Comment by sascha73** [comment]
ok, 
thanks

**Comment by MrGeneration** [comment]
Another sample, in this case Gmails rate limits kicking
```
I, [2024-05-31T17:10:06.280701#1732354-6240]  INFO -- : 2024-05-31T17:10:06+0000: [Worker(host:domain.tld pid:1732354)] Job TicketArticleCommunicateEmailJob [366efadb-409a-495d-9a81-f673d0010047] from DelayedJob(default) with arguments: [264631] (id=22624988) (queue=default) RUNNING
E, [2024-05-31T17:10:06.706387#1732354-6240] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::SMTPUnknownError: Net::SMTPUnknownError>
E, [2024-05-31T17:10:06.706436#1732354-6240] ERROR -- : could not get 3xx (550: 550-5.4.5 Daily user sending limit exceeded. For more information on Gmail
550-5.4.5 sending limits go to
550 5.4.5  https://support.google.com/a/answer/166852 xxxxxxxxxxxxxxxxxxxxxx.xx - gsmtp
) (Net::SMTPUnknownError)
....
```
