### ISSUE TITLE
GDPR/DSGVO

### ISSUE THREAD

**Issue by SysErr23** [zammad/zammad#2134]
Is there a plan to include functionallities, that are URGENT needed, to use zammad in european countries?

* Export all Data of a contact including whole tickets in PDF
* Delete all Data of a contact including whole tickets on request

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a question. You can ask questions over at https://community.zammad.org/ - Closing now.

Regarding your second point there is issue #2074 which we are actively working on.
