### ISSUE TITLE
Chat not displayed, problem with Chat.min.js

### ISSUE THREAD

**Issue by D4RKNOISE** [zammad/zammad#2135]
Added the code :  (between body tags)
```
<script src="https://xx.domain.be/assets/chat/chat.min.js"></script>
<script>
$(function() {
  new ZammadChat({
    fontSize: '12px',
    chatId: 1
  });
});
</script>
```

Console says
```
chat.min.js:1 Uncaught TypeError: Cannot read property '1' of null
    at chat.min.js:1
    at chat.min.js:1

```

Cant find the problem... possible issue 

### Infos:

* Used Zammad version:
* Installation method (source, package, ..): ubuntu 16.04
* Operating system: Linux
* Database + version: nvt
* Elasticsearch version: nvt
* Browser + version: Chrome 67.0.3396.99

### Actual behavior:
Does not display
*

### Steps to reproduce the behavior:
load website...
*

**Comment by NeverMin** [comment]
can you try:
```
$ sudo su zammad
$ cd /opt/zammad/public/assets/
$ rm *.js *.js.gz *.css *.css.gz
$ cd /opt/zammad
$ rake assets:precompile --trace
```

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

However, @NeverMin is right. There is something wrong with your asset generation. These steps will help. If not please open a topic over at the board.

**Comment by D4RKNOISE** [comment]
Thank you for the information! it worked!
