### ISSUE TITLE
Generic OAuth2 integration problem

### ISSUE THREAD

**Issue by JuanMsanchez** [zammad/zammad#2137]
Hello there! I’m having problems trying to login using the Generic Oauth2 option. It’s seems that no user information is reaching zammad, therefore the user can’t be created.
I already tried sending login, email, firstname, etc. as reponse from the /ouath/token endpoint.
An example response payload will be appreciated. Regards!

- Infos:
Used Zammad version: 2.5.x

- Expected behavior:
To login

Actual behavior:
422: The change you wanted was rejected.
‘Minimum one identifier (login, firstname, lastname, phone or email) for user is required.’

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now. Please make sure to add your `log/production.log` to the thread and fill out the complete template 👍

**Comment by JuanMsanchez** [comment]
I do read it, and I post it on the community page but I get no response.
https://community.zammad.org/t/generic-oauth2-integration-problem/988

It would be nice to have some documentation about the Oauth2 integration. Here the production log

```Started GET "/auth/oauth2" for 127.0.0.1 at 2018-07-16 21:10:22 +0000
omniauth: (oauth2) Request phase initiated.
Started GET "/auth/oauth2/callback?code=[FILTERED]&state=7f5aa95d416d24bac9114744f1984cdbce57f7fc8e7e2efe" for 127.0.0.1 at 2018-07-16 21:10:22 +0000
omniauth: (oauth2) Callback phase initiated.
Processing by SessionsController#create_omniauth as HTML
Parameters: {"code"=>"[FILTERED]", "state"=>"7f5aa95d416d24bac9114744f1984cdbce57f7fc8e7e2efe", "provider"=>"oauth2"}
ERROR -- : Minimum one identifier (login, firstname, lastname, phone or email) for user is required. (Exceptions::UnprocessableEntity)```

**Comment by JuanMsanchez** [comment]
@thorsteneckel can we reopen this issue?

**Comment by thorsteneckel** [comment]
Dear @JuanMsanchez,

first of all, many thanks for your participation on the Zammad open source project.

Not usual as with proprietary software, we finance Zammad through service. So it's less money we have at our disposal to push Zammad.

If you would like to support Zammad, you can do so via Zammad Support: https://zammad.com/pricing#selfhosted

For all issues it is generally important that we tag an issue as soon as it is included in a release. This means that manual enquiry only minimizes the available resources but not the speed of implementation.

Thank you for your understanding.
