### ISSUE TITLE
Admin and Agents cannot create tickets

### ISSUE THREAD

**Issue by chrstmnn** [zammad/zammad#2138]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): rpm
* Operating system: CentOS
* Database + version:
* Elasticsearch version:
* Browser + version: Safari, Chrome, Firefox ESR

### Expected behavior: Admin or agent click "+" in order to create a new ticket. After filling in the information, clicking "create" should save the information and create the new ticket.

*

### Actual behavior: If clicking "create" as an admin or agent nothing happens. Logging in as an customer creation is possible without any problems.

Additionally, since upgrading to 2.5 there is an issue with the E-Mail channels. I get the following errors:
Can't use Channel::Driver::Smtp: #<TypeError: no implicit conversion of nil into String>

I have already updated the mail settings, which has been successful, but after a while I get the same error again. 
Also using sendmail protocol gives: Can't use Channel::Driver::Sendmail: #<TypeError: no implicit conversion of nil into String>

Not quite sure if these are two problems or one belonging together.

*

### Steps to reproduce the behavior: Problem since upgrading to 2.5

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by hanneshal** [comment]
Just a wild guess:
you don't have those 3 tabs on the top correct?

![zammad_-_call_inbound](https://user-images.githubusercontent.com/804939/43068764-9d8a2754-8e6b-11e8-88f6-4a60b9f70a0d.jpg)

**Comment by chrstmnn** [comment]
Yes, indeed. They are missing!

**Comment by hanneshal** [comment]
Please follow the steps described in this issue:

https://github.com/zammad/zammad/issues/2106#issuecomment-401262710
There went something wrong during your upgrade and some migrations are not executed. 

Regards

**Comment by chrstmnn** [comment]
Just found meanwhile Ticket #2106 and fixed it. Thanks
