### ISSUE TITLE
Links are modified after saving

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#2139]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): rpm
* Operating system: CentOS
* Database + version: Postgres 9.4
* Elasticsearch version: ES 5.6
* Browser + version: Chrome
* Ticket #1024124

### Expected behavior:

* If I write a text which includes an Url like www.zammad.org I'd expect it to be stored and send to customer like I wrote it. 

### Actual behavior:

* The link is modified to http://www.zammad.org 

### Steps to reproduce the behavior:

* Enter a www based link in an article or signature text field and hit submit.

We need to remove this logic, which is implemented here:
https://github.com/zammad/zammad/blob/develop/lib/core_ext/string.rb#L224

**Comment by rlue** [comment]
> We need to remove this logic, which is implemented here:
> https://github.com/zammad/zammad/blob/develop/lib/core_ext/string.rb#L224

I don't think this is where the bug is occurring. I placed a debugger breakpoint (`binding.remote_pry`) here, and then created an article and a signature with the text content 'www.zammad.org' — the bug still occurred, and the debugger was never triggered.

I'll continue to investigate.
