### ISSUE TITLE
RegexpError: failed to allocate memory for large attachments

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#2141]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Large Ticket::Article attachments should get handled properly

### Actual behavior:

* Large Ticket::Article attachments might lead to memory shortage and failing requests

### Steps to reproduce the behavior:

* prepare a large attachment (depending on your system, 18MB was used in the test)
* Perform a request to the TicketArticlesController#create method
* See the following error in your log:

```
E, [2018-07-24T09:37:44.867753 #2856] ERROR -- : failed to allocate memory: /^([A-Za-z0-9+\/]{4})*([A-Za-z0-9+\/]{4}|[A-Za-z0-9+\/]{3}=|[A-Za-z0-9+\/]{2}==)$/ (RegexpError)
/opt/zammad/app/controllers/concerns/creates_ticket_articles.rb:92:in `match?'
/opt/zammad/app/controllers/concerns/creates_ticket_articles.rb:92:in `block in article_create'
/opt/zammad/app/controllers/concerns/creates_ticket_articles.rb:77:in `each'
/opt/zammad/app/controllers/concerns/creates_ticket_articles.rb:77:in `each_with_index'
/opt/zammad/app/controllers/concerns/creates_ticket_articles.rb:77:in `article_create'
/opt/zammad/app/controllers/ticket_articles_controller.rb:86:in `create'
```
### Possible solution:

Remove this block:
https://github.com/zammad/zammad/blob/18199419892257a4b6d1902f05e4316772653696/app/controllers/concerns/creates_ticket_articles.rb#L97-L99

And just execute this block:
https://github.com/zammad/zammad/blob/18199419892257a4b6d1902f05e4316772653696/app/controllers/concerns/creates_ticket_articles.rb#L101-L107

And rescue Base64 parsing errors.

Ticket# 1024370

**Comment by SummerStorm** [comment]
Fixed by commit b358374ff5c7b9cabe67f53c1ad59fcb8295c7b4
