### ISSUE TITLE
Change font email Signature

### ISSUE THREAD

**Issue by cogielusz** [zammad/zammad#2145]
### Infos:
* Used Zammad version: 2.6
* Installation method (source, package, ..):
* Operating system: Ubuntu 18.04
* Database + version: Postgres 9.4
* Elasticsearch version: ES 5.6
* Browser + version: Chrome

### Expected behavior:

Is it possible to change the font for the email signature? Because the ways of changing through html does not work, and also by # {font} also does not move.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question and/or feature request. You can ask questions and request features over at https://community.zammad.org/ - Closing now.

However, you can change the overall font of the email by changing [the wrapper template file](https://github.com/zammad/zammad/blob/develop/app/views/mailer/application_wrapper.html.erb) but not only the one of the signature.
