### ISSUE TITLE
Defined Email signature should not be dependend from Group-Rights

### ISSUE THREAD

**Issue by LittleNo** [zammad/zammad#2146]
If you call this a bug or feature request is up to you, but anyway it is a problem:

Currently the Email-Signature that is applied by a user is set in the group-settings which the user belongs to. Due to that, if a user has full-access rights to more than one group, and these groups have different Email-signatures set, no signature at all is used (of course, zammad can not know which one to use in that case)

However, there are scenarios where assigning a user to more than one group (for access rights) would be required. For example: users of the headquarters may need a different email signature as employees working as an agent. Of course, to a user from the headquarters, access rights to all groups (at least for reading) must be granted. 

The easiest way to solve that problem would be to unlink the email-signature-setting from the Group-rights. Even though there would be other (more complex) way's to fix this.

**Comment by thorsteneckel** [comment]
Hi please respect the responsibility which comes with creating issues here on Github. Every comment/issue will send out an email to more than 100 people. This is why we have the banner you deleted in both of your issues. Please read it more carefully the next time.

However, this is not the right place for discussions. Please open a thread over at the [community board](http://community.zammad.org/).
Please keep in mind that Zammad is an open source project. As an alternative you can create a pull request or feel free to make use of our [commercial service](https://zammad.com/). Not usual as with proprietary software we finance Zammad through service. So it's less money we have at our disposal to push Zammad. Thank you for your understanding.
