### ISSUE TITLE
Attachments disappear from the UI when a session becomes inactive -> active while creating an email ticket

### ISSUE THREAD

**Issue by uli-heller** [zammad/zammad#2147]
### Infos:

* Used Zammad version: 2.5.0
* Installation method (source, package, ..): source
* Operating system: ubuntu-18.04
* Database + version: mysql
* Elasticsearch version: 5.6
* Browser + version: chrome 68

### Expected behavior:

* Attachments should remain visible

### Actual behavior:

* Attachments disappear, adding them again produces an email with duplicate attachments

### Steps to reproduce the behavior:

* Create a new email ticket (+ - email)
* Add a couple of attachments
* Open one of the zammad links by: right mouse button - open in new tab
* Go back to the original tab - session became inactive
* Make the session active again
* The attachments are gone
* Add the attachments again
* Send the email/create the ticket

Afterwards:

* The email has duplicate attachments
* The ticket has duplicate attachments

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @uli-heller 

just tested in develop branch and it works here. It's fixed with issue #1123 and available in next stable 2.6.

 -Martin

**Comment by uli-heller** [comment]
Perfect, thanks a lot and sorry for not finding #1123 during my research 
before creating the ticket.

Am 26.07.2018 um 10:27 schrieb Martin Edenhofer:
