### ISSUE TITLE
Put Dockerfile for zammad/zammad docker hub image in repo

### ISSUE THREAD

**Issue by senk** [zammad/zammad#215]
Please put the Dockerfile in the repo so it is clear how the docker hub image is build.
Plus it can be improved by the community

**Comment by thorsteneckel** [comment]
Hi @senk - we will provide the Docker repository shortly.

**Comment by celevra** [comment]
the docker image is not usable, so it would be nice to see the dockerfile:

```
core@core1 ~ $ docker run --name=ticketsystem --env HOSTNAME=tickets.by.lk --env PORT=80 --env REGISTER=true --env EXTERNALIP=138.201.145.19 zammad/zammad
Starting postgresql-9.6 service: [  OK  ]
error: "Read-only file system" setting key "vm.max_map_count"
Starting elasticsearch: [  OK  ]
Starting postfix: [  OK  ]
Starting nginx: nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/conf.d/zammad.conf:27
[  OK  ]
core@core1 ~ $
```

**Comment by celevra** [comment]
it is a timing issue, zammed is starting before the database is ready and panics

**Comment by senk** [comment]
That issue is discussed in #213



Am 19.10.2016 um 19:16 schrieb celevra <notifications@github.com<mailto:notifications@github.com>>:


it is a timing issue, zammed is starting before the database is ready and panics

-

**Comment by SISheogorath** [comment]
The whole `Dockerfile` is more or less broken. As it starts all services inside a single container. You should provide a `docker-compose.yml` to orchestrate the containers. Having one container per service would be the right way.

Refering to: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/run-only-one-process-per-container

**Comment by celevra** [comment]
here is a working Dockerfile with a single container
https://github.com/celevra/zammad-docker

**Comment by thorsteneckel** [comment]
Hi @all we synced to docker repository to github. You can check it out and im improve it: https://github.com/zammad/docker

As @SISheogorath mentioned correctly we start all services inside a single container (against the docker best practices). We decided to go this way to make testing zammad as easy as possible. We're planning to create a `docker-compose.yml` version as soon as possible but have a lot to do right no. So maybe some open source docker hero will step up and help us out here. Would be much appreciated 😍
