### ISSUE TITLE
Text attribute inputs longer than maxlength is silently truncated

### ISSUE THREAD

**Issue by SummerStorm** [zammad/zammad#2150]
### Infos:

* Used Zammad version: develop
* Installation method (source, package, ..): source
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:
Input that is longer than the max length should results in an error message.  

### Actual behavior:
Input longer than the max length is silently truncated.

(Even if #738 is fixed, attribute changes via the API will still silently truncate oversized inputs.)

### Steps to reproduce the behavior:
1. Create a text attribute with max length set to 5.
2. Create a new ticket and fill the text attribute with "123456".
3. Observe that the string has been silently truncated to "12345".

###  Detailed Explanation

**Current behavior**
1. When creating a text attribute the size limit for the database column is always set. If a user-supplied maxlength is given it is used; if none are given 250/255 is used.

2. When switching from one maxlength to another, a database migration is required.

3. On the API level, there is no enforcement of maxlength. The database silently truncate inserted strings to the column limit. This is undesirable because it is done behind the user's back. If the user receives some data, submits it to Zammad without problems, and deletes their original copy, but later finds that the data has been silently truncated in Zammad, they have no way of recovering the original.

**Proposed Changes**
1. Force all text attribute columns to have a limit of 255.

2. Add maxlength validation to the frontend and backend.

**Behavior after Change**
1. Database column size is always 255 for all text fields.

2. When switching from one maxlength to another, no database migration is required.

3. Maxlength is enforced by the frontend and on the API level. The user won't be able to enter an oversized string using the web UI. An API user will get a helpful error message on oversized strings.

**Comment by rolfschmidt** [comment]
UI is fixed already (https://github.com/zammad/zammad/commit/72c1cab71b50f5717369a8c725d4752b53aad836), but the API check make sense as well.

**Comment by dominikklein** [comment]
@mantas should it be reopened?
