### ISSUE TITLE
LDAP Sync doesn't disables users

### ISSUE THREAD

**Issue by MarvinKlar** [zammad/zammad#2151]
### Infos:

* Used Zammad version: 2.5.0
* Installation method (source, package, ..): source
* Operating system: Debian
* Database + version: MySQL
* Elasticsearch version: 
* Browser + version:

### Expected behavior:

* The users should be deactivated in Zammad, when they are deactivated in the Active Directory

### Actual behavior:

* The users are still activated in Zammad, even when they are deactivated in the Active Directory

### Steps to reproduce the behavior:

* Enable the LDAP sync

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @MarvinKlar - what do you mean by `deactivated in the Active Directory`? Which AD version do you use?
Zammad disables user after they're no longer in the result set of the LDAP search. Additionally you can use mapping to map the attribute to the Zammad active attribute.

**Comment by MarvinKlar** [comment]
But there is no attribute in the Zammad LDAP Sync configuration to disable a user:
http://prntscr.com/kbr4xw

**Comment by thorsteneckel** [comment]
Ah right. Sorry I forgot that syncing of boolean attributes is not possible:
https://github.com/zammad/zammad/blob/52bfa30bacaf3f8b33c7ccae39446abf91ae0633/app/assets/javascripts/app/controllers/_integration/ldap.coffee#L361

So I think you need to change your LDAP query.

**Comment by MarvinKlar** [comment]
What query? And how do I change it?

Do you mean the `User filter`?

**Comment by thorsteneckel** [comment]
Exactly

**Comment by MarvinKlar** [comment]
Thank you very much. I think this would be mentionable in the documentation...

Do you know how the filter has to look like?

**Comment by thorsteneckel** [comment]
We'd love to see a pull request to the documentation adding a block on how Zammad performs deactivation. Maybe with an example.
The filter depends on your LDAP configuration/attributes.

Since this is rather a technical question than an issue please feel free to open a topic at the [community board](http://community.zammad.org/). Closing now.
