### ISSUE TITLE
work around for outlook feature that breaks email address standard

### ISSUE THREAD

**Issue by chesty** [zammad/zammad#2154]
* Used Zammad version: 2.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

As requested in https://community.zammad.org/t/work-around-outlooks-broken-email-addresses/1021/2

When outlook emails an address not in its address book, it wraps the name and email address in single quotes. An example is provided below. Some MUAs like thunderbird appear to have a workaround in place as they can reply to them OK,  when zammad replies to them it tries to send an email to (eg) 'donald@toddler.com' which bounces.

```
From: Michael <michael@alwayssunny.com>
To: Bob <bob@alwayssunny.com>
CC: "'donald@toddler.com'" <'donald@toddler.com'>
Organization: alwayssunny.com
Subject: testing outlook sending email
Thread-Topic: testing outlook sending email
Date: Sun, 29 Jul 2018 20:48:31 +1000
Message-ID: <0cf0ed34-6816-2c71-4079-a27c4d1227f5@alwayssunny.com>
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit
Accept-Language: en-AU, en-US
Content-Language: en-AU
X-MS-TNEF-Correlator:
MIME-Version: 1.0

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
    testing outlook sending email<br>
    <br>
  </body>
</html>
```

**Comment by rlue** [comment]
Hey @chesty, we're working on a fix for this right now, and we just wanted to make sure that we're understanding the issue right. Can you send an email like the one above to support@zammad.com? 

Specifically, we'd like to see the faulty email headers, including `CC: "'donald@toddler.com'" <'donald@toddler.com'>` _in situ,_ because honestly we've dealt with a lot of emails before, and we've never seen anything like that.

Thanks so much for your patience and help getting this issue resolved.

**Comment by chesty** [comment]
here's some info from microsoft about it.

https://answers.microsoft.com/en-us/outlook_com/forum/oemail-osend/remove-single-quote-marks-around-email-addresses/d446f535-e353-4e18-ae1d-eacca5b6bed9

and I'll send a real example email to support now.

**Comment by chesty** [comment]
oops, I deleted a comment by accident. Sorry. I'll add it back.

here's some info from microsoft about it.

https://answers.microsoft.com/en-us/outlook_com/forum/oemail-osend/remove-single-quote-marks-around-email-addresses/d446f535-e353-4e18-ae1d-eacca5b6bed9

**Comment by martini** [comment]
Hi @chesty 

thanks for your example which you provided. So my summary is now:

**Problem:**

Outlook (version unknown) sends e-mails with invalid e-mail addresses such as `<'customer@example.com'>` in To and/or Cc (if the respective recipient is not maintained in Outlook/contacts). 

Note I: This is not about quotation marks in the real name, but about quotation marks in the e-mail address which makes the e-mail address invalid.

Note II: We have tested the behavior with these invalid email addresses with Apple Mail and Thunderbird, neither can handle the invalid email addresses.

**In the context of Zammad:**

1) In Zammad users with invalid email addresses are created.
2) With "reply to all" e-mails are sent to invalid e-mail addresses.

Possible improvements in Zammad to "support" this Outlook problem:

a) During e-mail parsing, leading and ending ' in e-mail addresses are removed. Thus 1) is solved.

b) In the frontend, leading and ending ' in e-mail addresses are removed in the "reply to all". Thus 2) is solved.


Feedback is welcome!

**Comment by crashbuggy** [comment]
Thanks, Martini,
edit: I didn't realise I was logged into my other account. this is chesty here.

I was told it worked in Thunderbird, but I just tested and you're right, it doesn't work there.
I probably wouldn't strip out the single quote characters then, that just encourages bad behaviour.

There's another option, a bit tangent to this issue, currently, when sending to multiple recipients from Zammad and one or more recipients bounces, Zammad doesn't identify which address(es) bounced, it lists all the addresses like:

```Delivery failed: "Unable to send email to 'validaddress@gmail.com,'donald@toddler.com',anothervalidaddress@gmail.com': Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: 553 Invalid mail address >" ```

Sometimes there might 10 or more addresses. if it's possible to point out which of the 10 addresses bounced that would make things easier in general. When agents got the delivery failed message at first they thought no one got the email (understandable), and so they tried again and got the same error. meanwhile, all the valid email addresses got two copies of the reply.

ie if it's possible for Zammad to say:

```Delivery failed: "Unable to send email to ''donald@toddler.com'': Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: 553 Invalid mail address >" ```

listing only the addresses that bounced, that would fix the confusion. I don't know if it's possible though, maybe it's the mail server listing all the addresses?
