### ISSUE TITLE
Autoreply doesn't work when there is a mistmatch on email

### ISSUE THREAD

**Issue by gspfranc** [zammad/zammad#2155]
### Infos:

* Used Zammad version: Zammad version 2.5
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Browser + version: Chrome 67.0.3396.99

### Expected behavior:

* All email should trigger the triggers

### Actual behavior:
* New email doesn't trigger my autoreply trigger because of mismatch on the email in the configuration

### Steps to reproduce the behavior:
* Setup a first email account that forward the emails to the second (support1@domain.com >> support2@domain.com)
* Plug the second email account to Zammad (support2@domain.com >> Zammad)
* Send an email to support1@domain.com using a non agent email

![image](https://user-images.githubusercontent.com/5267143/43404713-25a1dad6-93e6-11e8-952f-42480bcdf536.png)
![image](https://user-images.githubusercontent.com/5267143/43404725-2ae96c66-93e6-11e8-8774-126b5393e4c7.png)

Autoreply working:
![image](https://user-images.githubusercontent.com/5267143/43404735-33682a26-93e6-11e8-9b5f-7ecfbaf979e8.png)

Autoreply not working:
![image](https://user-images.githubusercontent.com/5267143/43404792-58a10704-93e6-11e8-8bd3-9361b5e4011d.png)

**Comment by thorsteneckel** [comment]
This probably works as designed. I assume that there are some mails getting set for the forwareded email which tell Zammad not to send an auto-reply. Please post the raw mail of your last screenshot (test 7) here.

**Comment by gspfranc** [comment]
[ticket-10029-52.txt](https://github.com/zammad/zammad/files/2241846/ticket-10029-52.txt)

**Comment by gspfranc** [comment]
Found the reason in auto_response_check.rb:
`return if mail[ 'precedence'.to_sym ] && mail[ 'precedence'.to_sym ] =~ /(bulk|list|junk)/i`

I will remove this line in my local code for the moment, and in the future will change my support emails to alias and not distribution list.
