### ISSUE TITLE
Ical escaltion update the calendar entry to 2:00 am

### ISSUE THREAD

**Issue by Newan** [zammad/zammad#2157]
### Infos:

* Used Zammad version: 2.5
* Installation method (source, package, ..): deb
* Operating system: ubuntu 16.04
* Database + version: postgres
* Elasticsearch version: n/a
* Browser + version: chrome
* Ticket: #1077668 

### Expected behavior:

* An Escalation entry or an waiting for entry escalated. after that the entry is still in calender on the same date or the entry goes to the next day on the same time or goes to the next day on 8:00 am a clock but not in the night

### Actual behavior:

* An Escalation entry or an waiting for entry escalated. after that the calendar entry goes to the next day at 2:00 am in the night. 

### Steps to reproduce the behavior:

* create an ticket and set it to waiting for:
* import ical to outlook
*check the calander:
<img width="214" alt="zammad_ical" src="https://user-images.githubusercontent.com/3693094/43451698-d0ca4284-94b5-11e8-9aca-12fb29dbc4ea.PNG">

* wait to the next day and escalate the ticket.
* resync the calendar
![image](https://user-images.githubusercontent.com/3693094/43451761-fa65f7a0-94b5-11e8-9509-aa246cdf84ea.png)
Calendar entry set to 2:00am in the night

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This issue also applies to nightly notifications of ignored pending for reminders.

**Comment by uli-heller** [comment]
For #2366, the action happened at 1am today, so 0am UTC seems to fit for both of them...

**Comment by RobMOwen** [comment]
This is causing me issues too. Also I'd like to be able to set email notifications (both reminders and escallations) to only send once, this fits in much better with my workflow. Any advice?

*Used Zammad version: 3.2.0-1578664361.375c4929
*Used Zammad installation source: Debian Package
*Operating system: Ubuntu 18.04
*Browser + version: Firefox 72.0.1

**Comment by MrGeneration** [comment]
@RobOwen1990 please don't hijack github issues for your technical questions.
The better place for technical questions is the Zammad Community: https://community.zammad.org


Because of missing input and to reduce "me toos" I'm limitting the conversation to contributors only. We do this to reduce noise on this repository which helps us focussing. 💪 

As soon as there's any new input to this topic, we'll update this issue accordingly.
