### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#216]
Im using the Master Branch with docker. I have the issue that the search field isn't working. 
Also when i want to assign an user to an organisation. 

I get no dropdown or some suggestions.

**Comment by thorsteneckel** [comment]
Hi @Julian0o - could you please try to update your docker? We had the similar issue #211 regarding the search that was fixed in the latest docker image version.

**Comment by Julian0o** [comment]
Hi! I installed a new image and now the problem is gone! Thx!

**Comment by thorsteneckel** [comment]
Nice! Thanks for your fast feedback.
