### ISSUE TITLE
New function: Do not create a user with a new ticket

### ISSUE THREAD

**Issue by 21let** [zammad/zammad#2160]
Greetings,

I should have a new function. At Zammad, I would like to be able to set up whether to create a user with a new tire. It is unnecessary for SPAMs and other non-essential emails to create new "access rights" and unnecessarily enter the database. The function could be a global function where I would choose the option: Do not create a user with a new ticket.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a feature request. You can propose feature requests over at https://community.zammad.org/ - Closing now.

**Comment by 21let** [comment]
I'm sorry, thank you for the alert.
