### ISSUE TITLE
Gui: Show company instead first and last name

### ISSUE THREAD

**Issue by 21let** [zammad/zammad#2161]
I would have an idea for a new GUI feature:

Zammad now works primarily with first name and last name. These items are required. I would rather use the items so that gui would first display the name of the company / company instead of firts and last name. This company could also appear in the ticket detail just under the name of the ticket.

**Comment by thorsteneckel** [comment]
@21let - as already stated in #2160 please refer to the community board. Thanks!

**Comment by 21let** [comment]
I'm sorry, thank you for the alert.
