### ISSUE TITLE
Printed documents do not contain the whole ticket content, if it gets too much

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2162]
### Infos:

* Used Zammad version: ~~2.5.x~~ 2.6.x
* Installation method (source, package, ..): hosted
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: Chrome 68.0.3440.75 x64

### Expected behavior:

* When printing documents, the ticket content should not be limited to one page and not cut off if there's more content.

### Actual behavior:

* When printing documents the ticket content gets cut if it's longer than the actual page. Also avatar-images are missing.

### Steps to reproduce the behavior:

* Create a ticket and write whatever you please (notes, calls, mails), do that until you get a scroll bar
* try to print the document

(As long as the content is not too long for an page, it will be displayed correctly (but without avatars))

![image](https://user-images.githubusercontent.com/6549061/43568649-6ff3d6a6-9635-11e8-9d14-eb33bfb49c9d.png)
[Zammad Helpdesk - #42004 - Order 787956.pdf](https://github.com/zammad/zammad/files/2252498/Zammad.Helpdesk.-.42004.-.Order.787956.pdf)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Additional information as I just saw it: It would make sense to automatically expand the ticket contents in case there's more to display during showing the print view.

**Comment by martini** [comment]
@mrflix I can confirm. It's not working on FF (it's working on Chrome + Safari).

**Comment by MrGeneration** [comment]
Did you remove my 

`body, #app, .table-column-head, .fullscreenMessage, .horizontal, .tabsSidebar-holder,
.ticketZoom-controls {
  display: block !important;
}`

? That was the fix for ff

**Comment by martini** [comment]
Fixed also in stable. Feedback is welcome.
