### ISSUE TITLE
Incorrect encoding of email messages in HTML format

### ISSUE THREAD

**Issue by 21let** [zammad/zammad#2166]
When the email arrives in an HTML format using diacritics (Czech Republic), Zammad displays bad coding. If I open a ticket in RAW format and open in MS Outlook, it's ok. Even the mailbox is coded without any problems. The problem is, therefore, in a zammad that fails to deal with latin encoding?

![image](https://user-images.githubusercontent.com/13964136/43627870-6cf4b330-96f8-11e8-8253-06a0e0bf3ef5.png)

![image](https://user-images.githubusercontent.com/13964136/43627956-bd5ae60a-96f8-11e8-9e29-273882f28c92.png)

**Comment by 21let** [comment]
Zammad 2.6.0-1533244886 for Centos7 / Nginx

**Comment by martini** [comment]
Hi @21let 

there is a template for every new issue which is needed to get filled. Please create a new issue by using this template. It would be also good to attach this raw email to the issue. It depends on the content-type of the mail.

Thanks a lot!

 -Martin
