### ISSUE TITLE
Incorrect encoding of email messages in HTML format (Windows-1250)

### ISSUE THREAD

**Issue by 21let** [zammad/zammad#2167]
### Infos:

* Used Zammad version: 2.6.0-1533244886
* Installation method (source, package, ..): package Centos 7 Rpm
* Operating system: Centos 7
* Database + version: Postgresql 9.2.23.-3
* Elasticsearch version: 5.6.10
* Browser + version: Chrome 67.0.3396.99

### Expected behavior:

Functional coding in Windows-1250 HTML format email

### Actual behavior:

When the email arrives in an HTML format using diacritics (Windows-1250) (Czech Republic), Zammad displays bad coding. If I open a ticket in RAW format and open in MS Outlook, it's ok. Even the mailbox is coded without any problems. The problem is, therefore, in a zammad that fails to deal with latin encoding?

### Steps to reproduce the behavior:

Send an email in HTML format as a ticket.

Yes I'm sure this is a bug and no feature request or a general question.

---- Original email message ----
Return-Path: <xxxx@mail.xxxxx.cz>
X-Kerio-Anti-Spam:  Build: [Engines: 2.15.8.1150, Stamp: 3], Multi: [Enabled, t: (0.000007,0.003682)], BW: [Enabled, t: (0.000008)], RTDA: [Enabled, t: (0.048902), Hit: No, Details: v2.7.13; Id: 15.1i6ap3s.1cjtibnrd.2nhht], total: 0(700)
X-Spam-Status: No, hits=0.0 required=5.0
	tests=KERIO_ANTI_SPAM: -0.000, BAYES_00: -1.665, HTML_MESSAGE: 0.001,
	MIME_HEADER_CTYPE_ONLY: 0.717, MIME_HTML_ONLY: 0.723, TOTAL_SCORE: -0.224,autolearn=no
X-Spam-Level: 
Received: from mail.xxxxx.cz ([xxx.168.xxx.xxx])
	by mail.xxxxxx.cz with ESMTP
	for helpdesk@xxxxxx.cz;
	Thu, 2 Aug 2018 16:58:16 +0200
Received: by mail.xxxxx.cz (Postfix, from userid 500)
	id 58E7387959; Thu,  2 Aug 2018 16:58:28 +0200 (CEST)
To: helpdek@xxxxx.cz
Subject: Contact from Server
X-PHP-Originating-Script: 500:kontact-info.inc.php
From: xxxxx@xxxxx.cz
Content-Type: text/html; charset="Windows-1250"
Message-Id: <20180802145828.58E7387959@mail.xxxxxx.cz>
Date: Thu,  2 Aug 2018 16:58:28 +0200 (CEST)

<html>
<body><center><span style="color: #C0C0C0; font-family: Arial; font-size: 15pt;">Contact form</span></center><br><br><span style="font-family: Arial; font-size: 10pt;">
Odeslano dne:  Čtvrtek 2. srpna 2018 16:58.28<br><br>
Uzivatel: <b></b><br>
Jmeno: <b>Peter</b><br>
E-mail: <b>xxxxx@xxxxxx.cz</b><br>
Problem: <b>jine</b><br><br>
Text: <b>Czech text ->  mlžení a zapírání své osoby, kterou zastupuje, nesvědčí o seriozním jednání, ale spíše</b><br>
<br>
</span></body></html>

![image](https://user-images.githubusercontent.com/13964136/43629251-fc2abeec-96fc-11e8-88d3-43e09a6ff0f2.png)

**Comment by martini** [comment]
@21let thanks for the issue! 

Would it be possible to attache the email as "file"? I the past I has issues with cut&past and strange charset conversations (the pasted text was not Windows-1250 anymore, it was utf8). Thanks a lot!

**Comment by 21let** [comment]
I can only send it privately if it does not matter. Email addresses include IP addresses and other private information.

**Comment by 21let** [comment]
[contact-head.txt](https://github.com/zammad/zammad/files/2256493/contact-head.txt)

**Comment by rlue** [comment]
@21let thanks for this bug report. For some reason, the third-party library we use to auto-detect string encodings is (incorrectly) guessing that your email is Windows-1251, not Windows-1250, so that's the encoding that Zammad is trying to convert from.

    >> CharDet.detect(File.read('contact-head.txt'))
    => {"encoding"=>"windows-1251", "confidence"=>0.9026276263884991}

We're working on a solution. Thanks for your patience!
