### ISSUE TITLE
Images/Avatars blank

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#217]
![image](https://cloud.githubusercontent.com/assets/6099976/19528233/794e8de2-962b-11e6-8248-83f57ecfbeb5.png)
![image](https://cloud.githubusercontent.com/assets/6099976/19528253/88ad53ae-962b-11e6-9d97-1f4b82ad2f1b.png)

### Console
>ImageService current size 385 385
ImageService no resize 385 385 0.9 0.0031914710998535156 in mb

### Log

> I, [2016-10-19T18:37:23.039786 #11121]  INFO -- : Started GET "/api/v1/users/avatar?_=1476894948178" for 178.203.210.80 at 2016-10-19 18:37:23 +0200
I, [2016-10-19T18:37:23.042448 #11121]  INFO -- : Processing by UsersController#avatar_list as JSON
I, [2016-10-19T18:37:23.042534 #11121]  INFO -- :   Parameters: {"_"=>"1476894948178", "user"=>{}}
I, [2016-10-19T18:37:23.054888 #11121]  INFO -- : Completed 200 OK in 12ms (Views: 0.4ms | ActiveRecord: 1.6ms)
I, [2016-10-19T18:38:05.722608 #11121]  INFO -- : Started POST "/api/v1/users/avatar" for 178.203.210.80 at 2016-10-19 18:38:05 +0200
I, [2016-10-19T18:38:05.725421 #11121]  INFO -- : Processing by UsersController#avatar_new as JSON
I, [2016-10-19T18:38:05.725712 #11121]  INFO -- :   Parameters: {"avatar_full"=>"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAYEAAAGBCAYAAACAWQ0kAAAMyUlEQVR4Xu3VAREAAAgCMelf2iA/GzC5Y+cIECBAICuwbHLBCRAgQOCMgBIQIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjACISfLzoBAgSMgA4QIEAgLGAEws8XnQABAkZABwgQIBAWMALh54tOgAABI6ADBAgQCAsYgfDzRSdAgIAR0AECBAiEBYxA+PmiEyBAwAjoAAECBMICRiD8fNEJECBgBHSAAAECYQEjEH6+6AQIEDACOkCAAIGwgBEIP190AgQIGAEdIECAQFjgAaWuAYI4CR3JAAAAAElFTkSuQmCC", "avatar_resize"=>"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUAAAAFACAYAAADNkKWqAAAJPElEQVR4Xu3UAREAAAgCMelf2iA/GzA8do4AAQJRgUVzi02AAIEzgJ6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToCAAfQDBAhkBQxgtnrBCRAwgH6AAIGsgAHMVi84AQIG0A8QIJAVMIDZ6gUnQMAA+gECBLICBjBbveAECBhAP0CAQFbAAGarF5wAAQPoBwgQyAoYwGz1ghMgYAD9AAECWQEDmK1ecAIEDKAfIEAgK2AAs9ULToDAA2UOAUG2GG9iAAAAAElFTkSuQmCC", "user"=>{}}
I, [2016-10-19T18:38:06.432360 #11121]  INFO -- : Completed 200 OK in 706ms (Views: 0.8ms | ActiveRecord: 559.7ms)
I, [2016-10-19T18:38:06.552978 #11121]  INFO -- : Started POST "/api/v1/users/avatar/set" for 178.203.210.80 at 2016-10-19 18:38:06 +0200
I, [2016-10-19T18:38:06.555545 #11121]  INFO -- : Processing by UsersController#avatar_set_default as JSON
I, [2016-10-19T18:38:06.555629 #11121]  INFO -- :   Parameters: {"id"=>18, "user"=>{"id"=>18}}
I, [2016-10-19T18:38:06.607359 #11121]  INFO -- : Completed 200 OK in 52ms (Views: 0.2ms | ActiveRecord: 3.2ms)
I, [2016-10-19T18:38:06.958704 #12924]  INFO -- : 2016-10-19T18:38:06+0200: [Worker(host:rs6.nevoxo.com pid:12924)] Job Transaction::BackgroundJob (id=173) RUNNING
I, [2016-10-19T18:38:07.519139 #11121]  INFO -- : Completed 200 OK in 5010ms (Views: 0.4ms | ActiveRecord: 0.8ms)

**Comment by thorsteneckel** [comment]
Hi @MDXDave - Can you give me an step by step help how to reproduce this behaviour?

**Comment by martini** [comment]
Also the browser + version would be nice

**Comment by MDXDave** [comment]
Browser: Google Chrome (Win) 53.0.2785.143 m (64-bit)

1. Go to Profile -> Avatar
2. "Upload"
3. Choose an image
4. "Crop Image" dialog appears but without any image in it
(5. Image will created on the server, but is blank too)

The same issue appears if I want to upload a custom logo at "Settings" -> "Branding"

**Comment by MDXDave** [comment]
Issue was caused by a chrome extension: https://chrome.google.com/webstore/detail/canvasfingerprintblock/ipmjngkmngdcdpmgmiebdmfbkcecdndc?utm_source=chrome-app-launcher-info-dialog

**Comment by martini** [comment]
Thanks for feedback!

**Comment by sardinaskorp** [comment]
Hello, I'm having the same issue, I don't have that extension.
this happen when I try to upload a custom logo (branding)
![captura de pantalla 2017-02-10 a las 10 09 13 p m](https://cloud.githubusercontent.com/assets/20386478/22849629/9b575fca-efdd-11e6-8800-c53348082941.png)

if I look at the link this is what I get http://srv2.ticbox.cl/assets/images/3908dc1e79d8839075a053e6b4965f8b.png

this happened with CHROME and SAFARI on MAC

any ideas?

**Comment by protheusfr** [comment]
+1 Same issue on Zammad 1.3 under Docker.
