### ISSUE TITLE
Genereric OAuth2 Error

### ISSUE THREAD

**Issue by Fischmue** [zammad/zammad#2174]
### Infos:

* Used Zammad version: 2.5.0
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: mysql 5.6
* Elasticsearch version: 5.6
* Browser + version: Firefox 60 and IE 11
* ADFS: MS Server 2016 with AD FS
* Active Directory: Server 2016 with Scheme 2016

### Expected behavior:

successfull login with Generic-OAuth2

### Actual behavior:

Errorpage after NTLM-Authentification at ADFS
![grafik](https://user-images.githubusercontent.com/42146951/43783484-1d463850-9a62-11e8-8cc6-8036ab7c94c3.png)
![grafik](https://user-images.githubusercontent.com/42146951/43784875-6e34e844-9a65-11e8-978b-cb7e3abcf104.png)

### Steps to reproduce the behavior:

Authentification via Generic Oauth2 with a ADFS-Server to authentificate to an Active-Directory

Hello there,

I'm getting the same error as @sschroll mentioned in [https://github.com/zammad/zammad/issues/1250](1250)

I found another website which is saying, that the ADFS-Server only can handle up to 400 characters in the redirectURI. Is it possible to reduce the used characters in the code?

king regards Stephan

**Comment by thorsteneckel** [comment]
Hi @Fischmue - Thanks for providing the information. We're using a third party library which handles the OAuth2 authentication and which implements it conform the the specification. This why we/they can't/won't change the code / URL. 

Could you please check if there is a log entry regarding this in your `log/production.log` file?

**Comment by Fischmue** [comment]
Hi @thorsteneckel,

I have found the following lines:

`I, [2018-08-07T17:43:00.845549 #6036]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2018-08-07T17:43:01.406845 #6039]  INFO -- : Started GET "/auth/oauth2" for 127.0.0.1 at 2018-08-07 17:43:01 +0200
I, [2018-08-07T17:43:01.668714 #6039]  INFO -- : Started GET "/auth/oauth2/callback?code=[FILTERED]&state=e5ffb2eda686cb00a222ad23bda65ea754771463767193e6" for 127.0.0.1 at 2018-08-07 17:43:01 +0200
I, [2018-08-07T17:43:01.704256 #6039]  INFO -- : Started GET "/auth/failure?message=invalid_credentials&origin=http%3A%2F%2Fbmflin72.bm.grp%2F&strategy=oauth2" for 127.0.0.1 at 2018-08-07 17:43:01 +0200
I, [2018-08-07T17:43:01.708033 #6039]  INFO -- : Processing by SessionsController#failure_omniauth as HTML
I, [2018-08-07T17:43:01.708085 #6039]  INFO -- :   Parameters: {"message"=>"invalid_credentials", "origin"=>"http://bmflin72.bm.grp/", "strategy"=>"oauth2"}
E, [2018-08-07T17:43:01.708427 #6039] ERROR -- : Message from oauth2: invalid_credentials (Exceptions::UnprocessableEntity)
/opt/zammad/app/controllers/sessions_controller.rb:168:in `failure_omniauth'
`

The Origin is labeld with http, but we are using https, is this correct?
P.S. http to https redirect in the Apache-VHost

**Comment by thorsteneckel** [comment]
I can't see anything that would lead me to the source of this error. Sadly we have no way of reproduce this in our environment. Especially it's mostly the library functionality that handles this stuff. It would take quite a few hours to debug this. Sadly we don't have the time for spending so much of our "free time" on it. The only thing I can offer you right now is our commercial service. If you're interested feel free to get in touch with us over at support@zammad.com

**Comment by danielduchon** [comment]
@thorsteneckel 
we've got a similar error when setting up the google-authentication:

![422__unprocessable_entity](https://user-images.githubusercontent.com/41837959/43904033-0f45ef88-9bee-11e8-8320-402007f01ab5.png)

the used credentials are correct.
Is there anything we can do? Cause our userbase is in gapps and we wanted to provide sso.

**Comment by sschroll** [comment]
Hi @Fischmue 

Could you please describe how you set up the ADFS? Especially the claim rules and the endpoints.

**Comment by Fischmue** [comment]
Hi @sschroll ,

i have configured the ADFS like mentiond in this Issue [https://github.com/zammad/zammad/issues/1250#issue-242653540 ](https://github.com/zammad/zammad/issues/1250#issue-242653540 )

**Comment by thorsteneckel** [comment]
Hi @all - We think that we have a hot trace and want to verify our possible solution in a remote session. Volunteers welcome - yes, I'm looking at you 🤓 Please contact us at support@zammad.com and refer to this issue / me.

**Comment by thorsteneckel** [comment]
We found out that ADFS is not supported by the generic OAuth2 connector. Therefore I created a new issue where we will address the enhancement to support it: #2257. Closing this one now.
