### ISSUE TITLE
Only send related CTI/phone events to agents

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2177]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Only send related CTI/phone events to agents 

### Actual behavior:

* Currently every event (no effects what agent) is sent to any agent

### Steps to reproduce the behavior:

* create more group numbers in your BPX e g. sipgate account
* only assign one group number to the agent
* the agent will receive any group number events

**Comment by martini** [comment]
Proposed solution from @gijsrutten - https://github.com/zammad/zammad/issues/2044#issuecomment-396236128 

Currently the PBX integration in zammad only works global. Every agents that enables the "phone" option receives these notifications. 

Based on routing profiles in the PBX solution, an incoming call will only ring at some of the agents. Usually there is some kind of user management in the PBX solution. Each agent has its own user in the PBX. 

The routing profile determines which users receive a call. A user can set his phone to DND (do not disturb) and no calls will be routed to his device. 

Ideally the CTI integration can pull the users from the PBX and offers a matching table to connect PBX user to Zammad user. 

See an example between Sigate and Teamgrid here. 

![sipgate_user_mapping](https://user-images.githubusercontent.com/26574517/41233132-bdf4f216-6d88-11e8-964b-bad0ee93a669.png)

The same can be dome with Placetel.

**Comment by lociii** [comment]
Hey folks,

my company (https://regiohelden.de) is also interested in extended functionality of the CTI.
As far as I know, there is a possibility to sponsor feature development on Zammad.
We're open to negotiate and support in this case.

Here's our wishlist:

Level 1:
The Zammad CTI Push API should support specifying a list of users (e.g. by their telephone number) which will get a notification for the reported call. If the list is empty (default), the current behavior of notifying all users should be retained.

Level 2:
Show a Zammad internal overlay notification if the Zammad browser tab is focused, show the usual browser notification if not focused.
The Zammad internal notification should include a link to the calling customer when ringing (if one can be found) and a link to directly open a telefone ticket when the call is connected.

Level 3:
The actions on the Zammad internal notification can be configuerable. E.g. based on
- was a customer found based on the calling phone number?
- call status (ringing, accepted, etc.)

Level 4:
The telephone ticket opened from the notification is prefilled/updated with call related information. E.g. calling number, timestamp of call, duration of call (when hung up), etc.

Level 5:
A telephone ticket will automatically be opened and assigned to the agent that accepted the call. Maybe add a setting to turn this feature on/off on an agent level.

How is this sponsoring going on? Will someone estimate a price tag on each feature?

Thanks, Jens

**Comment by MrGeneration** [comment]
@lociii thanks for your interest in sponsoring the extension of this feature!
Before we can issue an inquiry, it's necessary to fill out arequirenment form that describes all features needed. These specifications will be what we will refer and work on (and well, giving you the price we think is needed).

You can contact us at sales [at] zammad [dot] com - we'll gadly work that out with you. :)

**Comment by lociii** [comment]
@MrGeneration thanks for the feedback. I've just submitted the inquiry.

**Comment by igayuh** [comment]
Hai.. 

Any progress on this issue ? All agents in zammad 3.1 still got all notification when there are incomings call .. 

Thanks..

**Comment by MrGeneration** [comment]
There's no updates on this.
Please don't ping Issues to keep the noise on the repo low.

(Please don't get this wrong, this is so we can concentrade on the current things we're working on. We will update issues when there's news on this. :-) )

**Comment by martini** [comment]
Update: In the meantime this feature got implemented. Since Zammad 3.1 it is possible to submit a `queue` for a incoming call (note: queue need to be submitted by BPX). 

In addition the gueue members need to be configured in Zammad (#system/integration/cti).


![image](https://user-images.githubusercontent.com/110226/84897436-da7dee80-b0a5-11ea-81db-711f3ce101ff.png)

Then only members of a caller queue will get related phone events. 

Thanks to regiohelden.de for the feature sponsoring!
