### ISSUE TITLE
No permission on ticket

### ISSUE THREAD

**Issue by Luis2032** [zammad/zammad#2178]
### Infos:

* Used Zammad version: 2.5.0
* Operating system: Debian
* Database + version: Postgres
* Browser + version: Chrome

### Expected behavior:

* Users should be able to access to customer and agent tickets. 
The User should also only be able to edit the agent tickets and to view the customer tickets.

### Actual behavior:

I assigned a user two roles.
One role contains access to his own customer tickets of a specialized group,
The second role contains access to agent tickets of another specialized group.
When he opens a ticket which he created everything is all right.
When he opens a ticket dedicated for him as agent this shows up:
![image](https://user-images.githubusercontent.com/37696119/43892777-2fb7d7e8-9bcd-11e8-9325-ba897fdabf9a.png)

### Steps to reproduce the behavior:

* create 2 roles

customer role:
![image](https://user-images.githubusercontent.com/37696119/43895894-1e8e551e-9bd7-11e8-83c4-4e67a26fff87.png)

agent role:
![image](https://user-images.githubusercontent.com/37696119/43895576-176899e4-9bd6-11e8-97e2-866e7c09717e.png)

* assign the roles to the user
![image](https://user-images.githubusercontent.com/37696119/43895628-3d1df346-9bd6-11e8-92e8-77c6742a04ad.png)

* open a ticket which was sent to the agent group (in this case "ELO")

**Comment by MrGeneration** [comment]
Hi,

this is not a bug but works as expected.
For technical questions, please head over to https://community.zammad.org .

This tracker is being watched by over 100 people, getting updates on Issues on every post, so for technical problems this issue tracker is a very bad place.

Sorry about that

Bests

**Comment by MrGeneration** [comment]
This is actually a duplicate of #967

Sorry for being too fast.
Customer & Agent in one and the same account is currently not supported by zammad.
