### ISSUE TITLE
Autocompletion does not work for more than one recipient on new ticket

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2181]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: Google Chrome 68.0.3440.84; Firefox 61.0.1 (64-Bit)

### Expected behavior:

* When creating a new ticket adding more than one recipient inside the "to" field should work with auto completion, just like it does within CC

### Actual behavior:

* When creating a new ticket adding more than one recipient inside the "to" field does not work with auto completion
* when typing the first two recipients seperated by "," and then adding a third recipient by autocompletion, it will remove the two first recipients
* you can paste any E-Mail addresses needed seperated by comma, the E-Mails will reach their recipient without problem

**Affects:** This only affects creating new tickets - this does work as expected, when modifing a reply of a E-Mail.

### Steps to reproduce the behavior:

* Create a new Ticket "E-Mail-Ticket"
* fill in the needed fields
* type in at least one E-Mail address (it does not matter if by auto completion or not)
* insert a comma after the first E-Mail address and write another one - if you now use auto completion, the first address you entered before vanishes

![image](https://user-images.githubusercontent.com/6549061/43963103-b6819e66-9cb9-11e8-8aa4-80429a0f117b.png)

![image](https://user-images.githubusercontent.com/6549061/43963110-b95b6176-9cb9-11e8-9577-a9bbc4fec8e0.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by prssanna** [comment]
Hello @MrGeneration, I'm working on a fix for this right now and I wanted to quickly clarify something.
Autocomplete for more than one user should work only for the `Send Email` tab and not for `Received Call` and `Outbound Call` tab right?

**Comment by thorsteneckel** [comment]
Hi together. This works as designed and is therefore no bug. The field when creating the E-Mail Ticket is called "Customer" not "To". A Ticket can have one customer - which will be used as the To receiver of the sent email.
