### ISSUE TITLE
[Languages] Completed the Swedish language

### ISSUE THREAD

**Issue by tmikaeld** [zammad/zammad#2182]
Just wanted to mention that I've translated all the strings and updated the old ones.

I've translated other CRM like BusinessCatalyst, Group-Office and Plutio so my translation should be relevant.

It's been submitted to the translation repository.

**Comment by thorsteneckel** [comment]
Hi @tmikaeld - Thanks a lot! This is great especially for all all the Swedish users out there 🇸🇪👋 We'll pick your changes up and they will be delivered afterwards (probably with the next release).  Closing now.
