### ISSUE TITLE
WebApp (monitoring section) claims scheduler not running, if delayed jobs get too many

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2188]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

* WebApp checks for the Schedulers health (running or not) and states it's state in Monitoring

### Actual behavior:

* The WebApp checks for the scheduler running that and seems to expect that the Scheduler is not running, in case the number of delayed jobs get too high.
* Scheduler runs, high delayed jobs number and WebApp claims scheduler died

### Steps to reproduce the behavior:

* Do tons of refresh actions on Zammad data (Users, Tickets)
=> that forces the scheduler to reindex things and creates a great amount of jobs
=> if you want to make it worse, enable ldap sync at the same time (currently a bug)
* Zammad will claim the scheduler to be dead after some time if the job number is extremly high.
We've seen this with over 15k jobs in the pipeline

A hint from Martin were to look for the Devs: https://github.com/zammad/zammad/blob/develop/app/controllers/monitoring_controller.rb#L75

Maybe another good idea is too output the number of delayed jobs within monitoring. Shouldn't be below 100 in my opinion (and maybe not if it's 100 for 30s to make sure users don't get confused by it)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Improved monitoring controller:
- Issue a monitoring message if background jobs over 8000.
- Improved message if scheduler jobs are not executed.
