### ISSUE TITLE
Background processes taking too long should be logged for better error search

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2189]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

* Zammad should log delayed jobs (or jobs in general) that are taking much time for completion (something like above 2s)

### Actual behavior:

* Zammad just seems to hang on a job - it is not clear what it does and makes debugging the cause of the error very difficult
* Zammad should write something like "Job XYZ [maybe with payload] takes longer than expected (started at xxxxxx)" into a seperate logfile. I'd say scheduler-log is a good place. (maybe as "warn log")

### Steps to reproduce the behavior:

Reproducing this is rather difficult as it depends on the machine and its load.
General said: Do something really timeconsuming as job and put the server on heavier load (so it really needs longer than you'd expect).

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Update: Rails current active job backend is logging the time how long a job took.

Example:

`INFO -- : Performed SearchIndexJob (Job ID: 7daf586b-f17c-4d92-8d87-8f2c5b2b9aa2) from DelayedJob(default) in **45.89ms**`

So I close this issue because not change is needed anymore.
