### ISSUE TITLE
Wrong Recent viewed tickets list

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#2194]
### Infos:

* Used Zammad version: develop (pre 2.7)
* Installation method (source, package, ..): source
* Operating system: CentOS 7
* Database + version: PostgreSQL 
* Elasticsearch version: n.a.
* Browser + version: Chrome 68 on macOS

### Expected behavior:

* Selecting from the tickets I've last seen / opened.

### Actual behavior:

* Weird selection of ticket with no relation to teh label 'Recent viewed ticket'
![image](https://user-images.githubusercontent.com/378324/44248783-e7e99980-a1ec-11e8-9d80-77913fbaf02f.png)

### Steps to reproduce the behavior:

* Use the system as usual and remember the tickets you have viewed. Then try to merge a ticket and check the ticket list.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rkaldung** [comment]
What's the definition of recent customer tickets? Does this include tickets from the same organization?

**Comment by rlue** [comment]
@rkaldung, can you try adding the following line to `app/models/recent_view.rb`, between L47 and L48?

```ruby
.order(created_at: :desc)
``` 

I suspect this is the problem.

**Comment by rkaldung** [comment]
@rlue I can't apply this on the production system. Create a Zammad instance an create multiple tickets. Open them in any order and then choose one of them and click to Add link and you'll see the wrong order
