### ISSUE TITLE
Unable to process email `EncodingError: could not find a valid input encoding`

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2200]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Process multipart emails with correct content type in mime  attachment (where content type of body is in mime attachment and not in header of the email it self)

### Actual behavior:

* Email is not processable `EncodingError: could not find a valid input encoding`

### Steps to reproduce the behavior:

* Process Internal reft t#1026089

**Comment by raphaelm** [comment]
Another sample is here: 
https://drop.rami.io/HvOP59

**Comment by martini** [comment]
@raphaelm thanks. Good news. Fix is on the way (CI).
