### ISSUE TITLE
Unable to modify tree_select attributes with fresh 2.6

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2206]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Be able to modify tree_select attributes via admin interface

### Actual behavior:

* I get an error message

### Steps to reproduce the behavior:

* create a tree_select with Values A, B, C
* execute changes/migration
* Open the tree_select field again and extend it with 2 sub categories for B
* save it
* try to execute changes you will get the following error:

````
E, [2018-08-23T08:08:31.919606 #14783] ERROR -- : undefined method `update' for #<Array:0x00007fe451405190> (NoMethodError)
/Users/me/src/zammad_plain/app/models/object_manager/attribute.rb:626:in `block in migration_execute'
/Users/me/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/Users/me/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/Users/me/src/zammad_plain/app/models/object_manager/attribute.rb:607:in `migration_execute'
/Users/me/src/zammad_plain/app/controllers/object_manager_attributes_controller.rb:93:in `execute_migrations'
````

The reason is, data_option.options is a array for tree_select, no hash.

**Comment by SummerStorm** [comment]
Fixed by 9be7269646a8d09d8ec98e614f2f3384e09f33e6
