### ISSUE TITLE
Datepicker not in view if ticket list too long

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2208]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: Google Chrome (latest), Firefox (latest)

### Expected behavior:

* When wanting to change a ticket state to pending close or pending reminder (no matter how long your ticket list is) the date picker for that should have a working viewport that's inside the visible browser range

### Actual behavior:

* When trying to change the ticket state to pending reminder or pending close on bulk actions, the date picker will be out of view port if the ticket list get's longer than one page (scrolling bar).

* this only happens if you have a longer list and you're not at the bottom of the page!

![image](https://user-images.githubusercontent.com/6549061/44537883-2b1d9e00-a700-11e8-8fd1-f674e53ebef2.png)

![image](https://user-images.githubusercontent.com/6549061/44537893-2d7ff800-a700-11e8-9ef3-4a0a8dfaa0a3.png)

![image](https://user-images.githubusercontent.com/6549061/44537899-31137f00-a700-11e8-937e-6a46e16db919.png)

### Steps to reproduce the behavior:

* create some tickets (5 are enough) and check at least one ticket box and try to change the date and state for pending close or pending reminder
* now resize your browser window so you get a scroll bar - you can also create a bunch of tickets to that view - the result will be the same
  => as long as your viewpoint is not on the bottom of the page, you will get see the datepicker

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Cannot reproduce anymore, seems to be accidentally fixed.
