### ISSUE TITLE
Order of relation select fields (Group, State etc.) values is broken

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#2209]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Select field values should be ordered by name

### Actual behavior:

* Select field values are order by ID
![screen shot 2018-08-23 at 14 36 20](https://user-images.githubusercontent.com/3873515/44538758-9b2d2380-a702-11e8-806d-d8e7631e8348.png)

### Steps to reproduce the behavior:

* Create these groups (in that order!):
  - Sports
  - Colorful
  - Adventure
  - Besties
* Create a Ticket within group "Adventure"
* Open Ticket (maybe reload page)
* See broken order

### Debugging:

[This commit](https://github.com/zammad/zammad/commit/1f7841340c026b29fd2b7a7d5b146c70c8fa613f) adds the possibility to have a stored value in a select which doesn't exist anymore in the list of possible values ([Issue #2020](https://github.com/zammad/zammad/issues/2020)). However, it adds the value [right at the beginning of the select construction](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/_ui_element/select.coffee#L12). Only a [few lines later](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/_ui_element/select.coffee#L15) there [is a check](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/_ui_element/_application_ui_element.coffee#L46) which expects the options to be empty for relation fields (e.g. Group, State etc.) like ours (Group). This is not the case anymore since option was filled by the new [`addDeletedOptions ` function](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/_ui_element/select.coffee#L49). Therefore the [`attribute.sortBy` gets set to `null`](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/_ui_element/_application_ui_element.coffee#L66) which will prevent the [`Model.search` function to apply the default sort](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/models/_application_model.coffee#L712) when [searching for all instances of the Model in the `getRelationOptionList` function](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/_ui_element/_application_ui_element.coffee#L111) for filling the select with the same elements/order the `Model.search` function returns.

### Possible solution:

The [`addDeletedOptions` function](https://github.com/zammad/zammad/blob/2c86e2cae195eba5c3ba769cd4ea214700e69d5b/app/assets/javascripts/app/controllers/_ui_element/select.coffee#L40) should get removed. Instead the [`selectedOptions` function](https://github.com/zammad/zammad/blob/2c86e2cae195eba5c3ba769cd4ea214700e69d5b/app/assets/javascripts/app/controllers/_ui_element/_application_ui_element.coffee#L185) should get overloaded for [select elements](https://github.com/zammad/zammad/blob/2c86e2cae195eba5c3ba769cd4ea214700e69d5b/app/assets/javascripts/app/controllers/_ui_element/select.coffee). This overloaded function should check if a non existing value is selected and add it to the list. If not the list should stay the same. After that the original [`selectedOptions` function](https://github.com/zammad/zammad/blob/2c86e2cae195eba5c3ba769cd4ea214700e69d5b/app/assets/javascripts/app/controllers/_ui_element/_application_ui_element.coffee#L185) should get called with the possibly altered list.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Note: The issue only appears for setups created before feb 2018 were this migration was executed. https://github.com/zammad/zammad/blob/develop/db/migrate/20180220171219_check_for_object_attributes.rb
