### ISSUE TITLE
502 Bad Gateway after Update

### ISSUE THREAD

**Issue by advoservice** [zammad/zammad#2213]
* Used Zammad version: 2.6
* Installation method (source, package, ..): rpm
* Operating system: CentOS 7
* Database + version: postgreSQL
* Elasticsearch version: 5.X
* Browser + version: firefox
*ruby 2.4

### Actual behavior:

* 502 Bad Gateway

### Steps to reproduce the behavior:

* 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.
