### ISSUE TITLE
Zammad limits the number of users shown within admin panel 

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2214]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: postgreSQL
* Elasticsearch version: n/a
* Browser + version: Google Chrome 68.0.3440.106 & Firefox 61.0.2 (I guess it happens to all Browsers)
* Ticket-IDs: #103054, #1031276, #1041255, #1048406, #1043370, #1073584, #1082962, #1090308, #1092570, #1099547, # 10100770, # 10101481, # 10101746, #10104279, #10122116, #10122670, #10131129, #10140416, #10141133, 10145536, #10148084

### Expected behavior:

* When viewing Users within Zammad admin panel, the list should load more user results or the list itself should use pagination like in ticket overviews

### Actual behavior:

* When you're viewing users within the zammad admin panel, the list is fix and does not load more entries. There's also no pagination

### Steps to reproduce the behavior:

* Create more than 50 Users (Zammad seems to limit the user count to 50) and check if you can see all users. The first user you created will "vanish"
* You can still search for that user normally. It does not matter if the user is admin, customer or an agent.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
I'm pretty sure there is/was an issue regarding this but I'm unable to find it right now. I'll remove the bug tag since it's not broken but bad UI/UX. It's possible to search for users. However, we should improve it.

**Comment by dennykorsukewitz** [comment]
Hi @MrGeneration,

currently 50 agents are listed in the overview:
https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/users.coffee#L158

As soon as this limit is removed, more will be listed and a pagination will be visible.
I suppose, however, that we have minimized the list to 50 and should find the rest through the search.

The question is whether it is really necessary to show all agents?

If there are more than 150 entries, the pagination is also displayed.
https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/_application_controller_table.coffee#L115

@martini what's your opinion on this?

**Comment by martini** [comment]
IMO nobody is searching a single user in a 50 or 100 result list. So for me it's ok to show 50 user per search result. So the current behavior would be ok for me.

@mrflix any UX recommendations?

**Comment by MrGeneration** [comment]
Maybe we could add a informational string like 

``` 
Showing the last {length of list} created users.
If your user doesn't appear below, use the search function please.
```

I think this would make it clearer.

**Comment by mrflix** [comment]
I would list all users. While it's faster to search for a user you might not know exactly what you're searching for. In those cases browsing is the better way.

**Comment by martini** [comment]
A side note. All users can be 9 milion users. Users are customers too.

**Comment by mrflix** [comment]
With 9 million you would probably search for what you know but then the results might be > 100. If I understand it correctly, of those > 100 results only 50 would be displayed. That's not good. All results should be shown.

And it would be really cool to have all 9 million users visible with pagination. In such cases users will understand that flipping though the pagination will take some loading. And that loading might bore them and make them choose to search instead. But still, the pagination shows them how many users there are and gives them the option to browse.

**Comment by dominikklein** [comment]
Closed, because of https://github.com/zammad/zammad/issues/5384
