### ISSUE TITLE
Unable to set users synced with LDAP as ticket owner.

### ISSUE THREAD

**Issue by oriflcdf** [zammad/zammad#2217]
### Infos:

* Used Zammad version: 2.5.x
* Installation method (source, package, ..): Source
* Operating system: Ubuntu 16.04 Xenial
* Database + version: MariaDB 10.0.34
* Elasticsearch version: 5.6.10
* Browser + version: Firefox 60

### Expected behavior:

* Everyone should be able to select an owner during the creation or the transfer of a ticket.

### Actual behavior:

* Only local users created by Zammad (with Agent & Admin permissions) are selectable. All other users synced from our Active Directory with Agent and/or Admin permissions aren't available.

Yes I'm sure this is a bug or an user error.

**Comment by thorsteneckel** [comment]
Hi @oriflcdf - this is probably a wrong configuration and not a bug. We only track issues here. Please ask technical questions over at the [community board](http://community.zammad.org/).
