### ISSUE TITLE
CTI Caller Log blocks user deletion/destroy and fails

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2218]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

* When deleting a user, the cti_caller_log may deny it's deletion. 
* the user will reappear

### Actual behavior:

* When deleting a user, the user is being removed cleanly.

### Steps to reproduce the behavior:

* create a user with a phone number (essential!)
* run below command

User.find(1234).destroy!
Error:
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  insert or update on table "cti_caller_ids" violates foreign key constraint "fk_rails_f03ef195fa"
DETAIL:  Key (user_id)=(26) is not present in table "users".
: INSERT INTO "cti_caller_ids" ("caller_id", "level", "object", "o_id", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"
    app/models/cti/caller_id.rb:36:in `maybe_add'
    app/models/cti/caller_id.rb:141:in `block in build_item'
    app/models/cti/caller_id.rb:140:in `each'
    app/models/cti/caller_id.rb:140:in `build_item'
    app/models/cti/caller_id.rb:79:in `build'
    app/models/user.rb:1205:in `update_caller_id'

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
JFI: Issued by this change https://github.com/zammad/zammad/issues/2057
