### ISSUE TITLE
Callback issue when Zammad if internal and external FQDN differ

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#2223]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): source
* Operating system: macOS
* Database + version: Postgres 9.6
* Elasticsearch version: 5.6
* Browser + version: Safari latest

### Expected behavior:

* A Zammad instance can be reachable through two different connections (internal / external)
* Herby the internal FQDN may differ from the external reachable one
* Zammad should provide a way to configure this / change this

### Actual behavior:

* Only one FQDN is possible

### Steps to reproduce the behaviour:

Take the CTI integration and configure it properly. The callbacks which are sent to sipgate (for example) are sent using the FQDN. If the FQDN is zammad.internal.company.loc and the system is reachable for sipgate using ticket.company.com then no sipgate request will reach it's destination because it is sent using the internal fqdn.

As discussed this is relevant for all integrations.

**Comment by martini** [comment]
It's available with Zammad 2.7. Since it is an expert setting, it only can be change via console:

```
zammad run rails r "Setting.set('sipgate_alternative_fqdn', 'external.host.example.com')"
```
