### ISSUE TITLE
`fork': Cannot allocate memory - fork(2) (Errno::ENOMEM)

### ISSUE THREAD

**Issue by Brijendrasial** [zammad/zammad#2225]
### Infos:

* Used Zammad version: V 2.6.0
* Installation method (source, package, ..): Source
* Operating system: Centos 6
* Database + version: 10.1.35-MariaDB MariaDB Server
* Elasticsearch version: 5.6.11-1
* Browser + version: Any

Recently we came to know out this software by one of our client and created a small blog post for its installation (https://blog.bullten.com/centos-web-panel/install-zammad-v2-6-0-with-apache-and-mysql-in-centos-web-panel-centos-6-7/).

When we start service we get output as below

> [root@cwp ~]# service zammad start
> Puma starting in single mode...
> * Version 3.11.0 (ruby 2.4.4-p296), codename: Love Song
> * Min threads: 5, max threads: 30
> * Environment: production
> * Daemonizing...
> WARN: Unresolved specs during Gem::Specification.reset:
>       minitest (~> 5.1)
>       mail (>= 2.5.4, ~> 2.5)
> WARN: Clearing out unresolved specs.
> Please report a bug if this causes problems.
> Starting websocket server on 0.0.0.0:6042 (secure: false, pidfile: /opt/zammad/tmp/pids/websocket.pid)
> /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/daemonize.rb:10:in `fork': Cannot allocate memory - fork(2) (Errno::ENOMEM)
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/daemonize.rb:10:in `safefork'
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/daemonize.rb:94:in `daemonize'
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/application.rb:105:in `start_none'
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/application.rb:294:in `start'
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons.rb:308:in `daemonize'
>         from script/websocket-server.rb:111:in `<main>'
> WARN: Unresolved specs during Gem::Specification.reset:
>       minitest (~> 5.1)
>       mail (>= 2.5.4, ~> 2.5)
> WARN: Clearing out unresolved specs.
> Please report a bug if this causes problems.
> pid-file for killed process 55097 found (/opt/zammad/tmp/pids/scheduler.pid), deleting.
> /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/daemonize.rb:10:in `fork': Cannot allocate memory - fork(2) (Errno::ENOMEM)
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/daemonize.rb:10:in `safefork'
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/daemonize.rb:45:in `call_as_daemon'
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/application.rb:274:in `start_proc'
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/application.rb:300:in `start'
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/controller.rb:56:in `run'
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons.rb:197:in `block in run_proc'
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons/cmdline.rb:92:in `catch_exceptions'
>         from /usr/local/rvm/gems/ruby-2.4.4/gems/daemons-1.2.5/lib/daemons.rb:196:in `run_proc'
>         from script/scheduler.rb:55:in `<main>'
> Zammad application started
> 

Zammad works fine but websocket doesnt start nor scheduler. How to suppress this error?

**Comment by Brijendrasial** [comment]
Increasing memory of virtual server environment did solve the issue..

**Comment by monotek** [comment]
https://docs.zammad.org/en/latest/prerequisites-hardware.html
