### ISSUE TITLE
Global Bcc for all outgoing emails for external archive options.

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2228]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Allow to set a global bcc

### Actual behavior:

* No option is available right now.

**Comment by MrGeneration** [comment]
PR: #1040
Request: 1786

**Comment by HolgerHeckeroth** [comment]
Hi Martin,
just installed the 2.7.0 but can't find the global BCC Option.
Global BCC would help us get rid of our SMTP Proxy.

Best
Holger

**Comment by martini** [comment]
Just set it via `zammad run rails r "Setting.set('system_bcc', 'your@email')"`

**Comment by flemming-pr** [comment]
Is there a way to set it also to an installation with docker-compose?

**Comment by martini** [comment]
> Is there a way to set it also to an installation with docker-compose?

@flemssound this is no issue related question, please use https://community.zammad.org for user questions.
