### ISSUE TITLE
Support for Tablets/Mobile (Responsive) 

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#223]
Is there a plan to support mobile phones or tablets (Responsive)?

**Comment by robbsie** [comment]
Also interested. Using Zammad on smartphone is not really possible atm as this seems not to be responsive in any way :-(

**Comment by tobzsc** [comment]
+1

a native app would even be better

**Comment by monotek** [comment]
Don't thinks so.
Responsive design works on all clients.
No need to build several native apps (IOS, Android, Windows Phone) beside Zammad itself.

**Comment by robbsie** [comment]
@monotek 
Problem is with notifications, this is much better with native apps (in iOS, cannot speak für Android here).

**Comment by tobzsc** [comment]
@monotek I fully agree with @robbsie here!

**Comment by MDXDave** [comment]
I am currently working on a android client for zamad, but it seems that it is currently not possible to implement the notifications because there exists no api endpoint for this.

**Comment by martini** [comment]
@MDXDave What! 👍 I'll provide your the endpoint docs here ASAP!

PS: Is android also working wait web sockets? So you would get push events if something has changed.

**Comment by MDXDave** [comment]
@martini Yes, websockets are working with android. But a documentation about the events would be helpful :tongue:

**Comment by monotek** [comment]
Notifications are coming by E-Mail anyway.
As a customer i also would not like to install some app on my phone just to be able to get support from some company.

**Comment by MDXDave** [comment]
@monotek the app will not be useable by customers, only admins and agents

**Comment by monotek** [comment]
So you think its good to have IOs, Android and Windows Phone apps for  for Agents & Admins and 3 more Apps for customers? Imho wasted ressources. Responsive design on the webapp would do the trick for everybody.

**Comment by jmic** [comment]
Zammad looks quite nice - on a desktop. My company would like to switch from OTRS to Zammad. But this is impossible without mobile support. Therefore I want to push this thread. Sorry, but we’re living in 2017 and new helpdesk software should be set up complete responsive in the first place. Is there a sketch or even a roadmap to reach this goal in the near future?

**Comment by martini** [comment]
Hi @jmic 

thanks for feedback. We are working hard on Zammad. It was also hard to launch Zammad from 0 to current state within 4 month. 

Anyway, our designers are working on mobile versions vor Zammad right now. I can't tell you on what date it will be available right now (but it will).

Feedback is welcome!

 -Martin

**Comment by tobzsc** [comment]
Hello @martini 

do you have an update for us? A mobile / responsive design is essential for us.

**Comment by joshmn** [comment]
Looking forward to it.

**Comment by KlyX84** [comment]
Another point why there should be native apps for iOS and Android: if you want to use the chat and the agents are "mobile only". With an app running in the background, the chat could be available even the app is not in foreground and so on...

Looking forward for mobile support :)

**Comment by kirantpatil** [comment]
[Turbolinks](https://github.com/turbolinks/turbolinks) with [Android](https://github.com/turbolinks/turbolinks-android) and [ios](https://github.com/turbolinks/turbolinks-ios) adapter would be nice for mobile development.

https://signalvnoise.com/posts/3978-building-basecamp-3-mobile-prototypes

For prototyping, Framer.js with brackets:

https://plus.google.com/+markushi/posts/WrjNuyhwfKJ

**Comment by MartinBorg** [comment]
+1 for small screen support and responsive design

but, please, no proprietary "APP" which would be limited to either Android or iOS, better just a responsive web page that works on small screens (e.g. I don't use neither Android nor iOS, but I'm going to use Linux on a mobile device with tiny screen)

**Comment by morphxle** [comment]
+1

**Comment by chrklo** [comment]
+1 for native android app

**Comment by MartinBorg** [comment]
If some prefer OS-agnostic, responsive web for mobile and other small devices, and other prefer a OS-dependent app (Android, iOS, Sailfish, Tizen, Windows 10 Mobile), maybe this issue should be split into at least two?

**Comment by SimonWerner** [comment]
+1 for webpage for mobile devices

**Comment by joshmn** [comment]
Maybe someone should fork and reimplement the entire design.

**Comment by aljaz86** [comment]
@martini any update on this matter?

**Comment by thorsteneckel** [comment]
nope - still waiting for the pull request from @joshmn 🤡 actually we are focusing on the business features currently. After that the knowledge base will come. Maybe afterwards. Would be great to see the community putting some effort in this 🥇

**Comment by semaf** [comment]
Push notifications is a must to have too

**Comment by lcx** [comment]
the missing ios app and push notification is the only thing preventing me to switch over to zammad. 
Willing to pay for the ios app as well. 
I could also try to workaround by integrating slack and using that as notification. 
Usually when I'm on holiday I don't read mails. So notifications via email wont't work. But I do have to be reachable by customers somehow, that’s where my support email and currently freshdesk comes in.

**Comment by Disane87** [comment]
+1

**Comment by ToubieObie** [comment]
+1

**Comment by thorsteneckel** [comment]
Locking conversation. There is no new input. +1 and requesting comments create noise and distraction. We are working hard on the next upcoming/most requested features and projects of our support customers. If you want to state your interest in the feature and give valuable input please give the initial post a 👍 reaction and we are able to evaluate it. We will lock all distracting issues from now on. Thanks for your understanding.
