### ISSUE TITLE
SSL_Write

### ISSUE THREAD

**Issue by arcreigh** [zammad/zammad#2230]
Hello all,
When I attempt to configure email in zammad 2.6.0 I am getting an SSL_Write error.
as if zammad is attempting to use ssl first before using starttls.
smtp server: postfix
imap server: dovecot
imap 143 
smtp 25
smtp submission 587
Can we have a selection between ssl/starttls rather than just yes/no?

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

**Comment by arcreigh** [comment]
I would consider this an issue to anyone who is only using starttls on their mail servers. They would be unable to successfully use email with zammad.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thorsteneckel** [comment]
StartTLS is available for [IMAP](https://github.com/zammad/zammad/blob/a70153106ab9c47f298e187b2c293a4878871c70/app/models/channel/driver/imap.rb#L87) and [SMTP](https://github.com/zammad/zammad/blob/a70153106ab9c47f298e187b2c293a4878871c70/app/models/channel/driver/smtp.rb#L49). Please create a new issue and make sure to fill out our issue template and provide all required information so we can better reason about the error you are talking about. Thanks!

**Comment by arcreigh** [comment]
Sure thing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
