### ISSUE TITLE
Also not active report profiles are shown in #report screen

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2232]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Only show active report profiles in #report

### Actual behavior:

* Also not active report profiles are shown

### Steps to reproduce the behavior:

* create a new report profiles in admin interface
* got to #report and verify

### Note

The fix is:

```
app/assets/javascripts/app/controllers/report.coffee
@@ -552,7 +552,7 @@ class Sidebar extends App.Controller
   render: =>
 
     metrics = @config.metric
-    profiles = App.ReportProfile.all()
+    profiles = App.ReportProfile.search(active: true)
     @html App.view('report/sidebar')(
       metrics:  metrics
       params:   @params
```

**Comment by SummerStorm** [comment]
Closed by ccf97ee077d552e760.
