### ISSUE TITLE
Zammad de Linux a Centos

### ISSUE THREAD

**Issue by Fabiola-ZC** [zammad/zammad#2238]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..):
* Operating system: Linux
* Database + version:pgadmin v 1.0
* Elasticsearch version:
* Browser + version: Firefox

* Requiero de su apoyo actualmente tengo instalado zammad dentro de Linux, se pretende cambiar a Centos, que pasos debo de seguir para poder realizarlo sin perder la información que ya tengo actualmente en la base de datos.

**Comment by MrGeneration** [comment]
Sorry but this is the wrong place to ask for help.

If you don't have a service contract, please ask questions on our community-board (in english!) : https://community.zammad.org/

Beside that, Backup & Restore might be what you look for:
https://docs.zammad.org/en/latest/appendix-backup-and-restore.html

Closing now.
