### ISSUE TITLE
Send all mails via sendmail - allow SMTP connection with no user/password (without auth)

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#224]
I want to add an email address to a group but have to add an email account first.
Why do i need to enter a password there? I like to send all mail via sendmail.
Not only notifications.

**Comment by thorsteneckel** [comment]
Hi @monotek could you please provide further information for this? I don't get it yet. A screenshot would be great. Thanks!

**Comment by monotek** [comment]
I want to configure outbound e-mail adresses to attach them to my groups.
At the moment i only can configure e-mails for inbound and these need a password.
System notifications can be send by sendmail. I also want to send outbound mails to customer via sendmail. 

So my idea was to add sendmail option to the inbound menu. But makes no real sense if it keeps the name inbound. Maybe renaming "Email Inbound" to "Email Inbound/Outbound" would be an option or creation of an "Email Otbound" menu.

**Comment by martini** [comment]
@monotek Is there a reason because you really want to use sendmail/postfix for sending emails to customers? Today many email restrictions out there (spf for example) wich only accept emails from certain mail servers, otherwise your emails will get rejected.

**Comment by monotek** [comment]
All our servers are configured to send mails to our relayhost wich is our real mailserver, which also does all the spf magic and so on. The advantage which i see is, that every server (also Zammad) has there own mailqueue which in my experience is much less error prone than letting some external programm or lib handle sending mails.

If there is a problem with the mailserver of any kind all agents can just send mails without getting bothered from error messages in the frontend. Mails are going to the local mailqueue. If mailserver is accessible again mails are devlivered to customers transparently.

**Comment by rkaldung** [comment]
@monotek Usually sendmail can be replaced by smtp to 127.0.0.1:25 This shouldn't break your relay config.

**Comment by monotek** [comment]
Thanks for the hint. 

I guess username and password would still be needed?

**Comment by rkaldung** [comment]
My postfix default config (EL6/EL7) always accepts e-mails from localhost/127.0.0.1 without authentication.

**Comment by monotek** [comment]
But the zammad dialog forces you to enter some...

**Comment by rkaldung** [comment]
@martini Really? Especially in MS Exchange environments relay permission is given on a IP address base. Authentication credentials should be optional.

**Comment by martini** [comment]
A good idea to set user/password optional!  😜

https://github.com/zammad/zammad/commit/8004e4445435560fa65acdd953b3ce937871aef8

Issue to close then?

**Comment by monotek** [comment]
Ill test it later... 
Will close if it works...

**Comment by monotek** [comment]
I jst tested it in 1.2.0 via the new Ubuntu 16.04 docker image (docker run -ti -p 80:80 monotek/zammad)
I still have to enter username and password.
Whats also a bit weird is that i have to fill all fields before i'm allowed to open the expert settings.

**Comment by monotek** [comment]
Are you sure you changed this for the mail channel?
Thats what i'm talking about.
I wan't to send all mails via SENDMAIL/SMTP without configuring POP3/IMAP.
Its not about the setting for notifications.

**Comment by martini** [comment]
@monotek sorry, I just was talking about sending mails via SMTP without user/password (before user/password was required).

**Comment by scroogie** [comment]
Any news on this? I think its a pretty common scenario that you do not use IMAP/POP3 for incoming mails, but direct delivery, for ticket systems.

**Comment by martini** [comment]
@scroogie JFI: For receiving without IMAP/POP3 you can use this https://docs.zammad.org/en/latest/channel-fetchmail.html

**Comment by monotek** [comment]
This is not about fetching mail. Its about sending it via sendmail command.

You can use whatever command you want to fetch mails and pipe them in Zammd. 
Fetchmail for example: https://docs.zammad.org/en/latest/channel-fetchmail.html

**Comment by monotek** [comment]
Other ways which use pipe (postfix alias can also pipe to a script for example) should work likewise...

**Comment by scroogie** [comment]
Yes, I tried this, as its the normal configuration for us, but as far as I understood your configuration interface, it's not possible to assign it to anyone then, because you need to enter a Useraccount, Login, Password etc. on the page.

**Comment by sidescraper** [comment]
Would like to do this too. Without imap or pop3 would be great. We use directly postfix and need an outgoing e-mail address per group.

Will there be this function?

**Comment by joker234** [comment]
Our Setup should be the same. We had RT in the past and want to switch to Zammad. RT just uses sendmail and pipelining. A possibility to configure groups with Mail Adresses without IMAP/SMTP Account would be great.

**Comment by sidescraper** [comment]
What's new? Is this feature now deleted?
We would like to use zammad. Bud now, we must also check otrs and osticket.

**Comment by symptog** [comment]
Any update on this issue?

**Comment by pebosi** [comment]
Update?

**Comment by thorsteneckel** [comment]
Locking conversation. There is no new input. +1 and requesting comments create noise and distraction. We are working hard on the next upcoming/most requested features and projects of our support customers. If you want to state your interest in the feature and give valuable input please give the initial post a 👍 reaction and we are able to evaluate it. We will lock all distracting issues from now on. Thanks for your understanding.

**Comment by rlue** [comment]
Just a quick status update for everyone waiting on this feature. We have a fix underway (really more of a workaround), but we can't merge it until we get the browser test passing, and we can't get the browser test passing until we set up Capybara.

It may still be some time before that's done. Thank you all for your patience.

**Comment by rlue** [comment]
Thanks everyone for your patience on this issue. After consulting with @martini, we have arrived at a relatively simple workaround enabled by 043a0af9f.

Since we are reluctant to modify / overcomplicate the existing email configuration wizard, which satisfies the majority of existing users, we are proposing a CLI workaround for creating an outbound-only email channel.

Once you have upgraded to the latest `development` version of Zammad (or 2.9.0, when it comes out), run the following command in your Zammad directory to create a new, sendmail-only email channel:

    $ zammad rails r "Channel.create!(area: 'Email::Account', options: { inbound: { adapter: 'null', options: {} }, outbound: { adapter: 'sendmail' } }, active: true, preferences: { editable: false }, updated_by_id: 1, created_by_id: 1)"

Once this command has been run, you will see the new email channel appear in your admin settings panel:

![46996467-51cfe200-d14f-11e8-9c64-6a827e86f175](https://user-images.githubusercontent.com/12194123/46999752-23570480-d159-11e8-8097-4262bc032be5.png)

Click the "➕ Add" link under the "Email Address" heading to add a new outbound email address.

That's it!

---

P.S. @MrGeneration will be responsible for adding this feature to the official documentation; this issue will remain open pending the completion of said documentation.

**Comment by MrGeneration** [comment]
That's interesting, this was already living in our documentation.
I tested the commands and corrected them so it is valid.

Change is live already, closing now:
http://admin-docs.zammad.org/en/latest/channel-email/sendmail.html

(Push: https://github.com/zammad/zammad-admin-documentation/commit/c8161664c6970060ebf4c52ae647c0d1130cc992 )
