### ISSUE TITLE
mandatory fields can be empty (or "-") on ticket update

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2242]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: Google Chrome - can test on more if needed

### Expected behavior:

* when setting a tree selection to required, the user shouldn't be able to set it to "-" (which is not set) when updating a ticket. Zammad does not allow this on ticket creation.

### Actual behavior:

* When setting a tree selection to required and then editing a ticket, the user can set it to "-" (which is not set) without any trouble. The user cannot set it to "-" when creating the ticket.

### Steps to reproduce the behavior:

* Add a new custom field as tree selection with required setting for atleast agent (add atleast one option)
* create a new ticket and try to set the field to "-" (will not work), choose any option of the tree-selection
* Create the ticket
* Now update the tree field to "-" and update the ticket (this will work)

![tree-select-bug](https://user-images.githubusercontent.com/6549061/45748214-5c5a9280-bc08-11e8-86c5-9544765a8dbe.gif)

Yes I'm sure this is a bug and no feature request or a general question.

Impacts Ticket: #1030389 & 1035367

**Comment by MrGeneration** [comment]
Small Update:
This applies to all fields except:
- Boolean
- Integer (this field just gets reset after Update without error, semi good in my opinion)

Even Date and Datetime can be empty.

**Comment by MrGeneration** [comment]
Another small update:
Date fields can be completely empty, even on creation. 

![date-object_norequirenment](https://user-images.githubusercontent.com/6549061/50599158-7feed380-0ead-11e9-9a33-3e32e12e9766.gif)

**Comment by martini** [comment]
Just a tech note. HTML5 validation is not fired because the `update` button is wrapped in a separate form. 

You can check and report html5 validation via javascript e. g. this way:

```diff
app/assets/javascripts/app/controllers/ticket_zoom.coffee
@@ -807,7 +807,12 @@ class App.TicketZoom extends App.Controller
     # stop autosave
     @autosaveStop()
 
-    # validate ticket
+    # validate ticket / html5
+    if !@$('.edit').parent().get(0).reportValidity()
+      @submitEnable(e)
+      return
+
+    # validate ticket by model
     errors = ticket.validate(
       screen: 'edit'
     )
```
