### ISSUE TITLE
Office 365 Callback redirect to wrong location

### ISSUE THREAD

**Issue by dnauck** [zammad/zammad#2248]
### Infos:

* Used Zammad version: 2.6.0-1536729659.43784b0e.xenial
* Installation method (source, package, ..): Ubuntu apt package
* Operating system: Ubuntu 16.04.5
* Database + version:
* Elasticsearch version:
* Browser + version: Chrome

### Expected behavior:

after Office 365 login a redirect to my zammad instance

### Actual behavior:

The Office365 login calls `https://helpdesk.domain.de/auth/microsoft_office365/callback?code=....` which sets a `location`header of: `location: http://helpdesk.domain.de:443/`

The result is a `400 Bad Request`

Settings -> System -> Base ->

* FQDN is set to `helpdesk.domain.de`
* HTTP Typ is set to `HTTPS`

**Comment by martini** [comment]
Hi @dnauck 

question, do you use nginx? If yes, can you send your nginx config?

Thanks!

 -Martin

**Comment by dnauck** [comment]
Hello,

the default zammad package add this config (afaik?):

```
#
# this is the nginx config for zammad
#

upstream zammad {
    server localhost:3000;
}

upstream zammad-websocket {
    server localhost:6042;
}

server {
    listen 80;

    # replace 'localhost' with your fqdn if you want to use zammad from remote
    server_name helpdesk.domain.de;

    root /opt/zammad/public;

    access_log /var/log/nginx/zammad.access.log;
    error_log  /var/log/nginx/zammad.error.log;

    client_max_body_size 50M;

    location ~ ^/(assets/|robots.txt|humans.txt|favicon.ico) {
        expires max;
    }

    location /ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_pass http://zammad-websocket;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 180;
        proxy_pass http://zammad;

        gzip on;
        gzip_types text/plain text/xml text/css image/svg+xml application/javascript application/x-javascript application/json application/xml;
        gzip_proxied any;
    }
}
```


Since the zammad system is behind my nginx with ssl offloading. Here is my offloading config:

```
server {
    listen 80;
    server_name helpdesk.domain.de;
    root /usr/share/nginx/html;

    # redirect to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name helpdesk.domain.de;
    root /usr/share/nginx/html;

    ssl_certificate /var/letsencrypt/certificates/live/helpdesk.domain.de/fullchain.pem;
    ssl_certificate_key /var/letsencrypt/certificates/live/helpdesk.domain.de/privkey.pem;

    ## OCSP Stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /var/letsencrypt/certificates/live/helpdesk.domain.de/fullchain.pem;

    client_max_body_size 50m;

    location /ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 86400;
        proxy_pass http://helpdesk.domain.extern/ws;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://helpdesk.domain.extern:80;
    }

    ## No crawling of this site for bots that obey robots.txt.
    location = /robots.txt {
        return 200 "User-agent: *\nDisallow: /\n";
    }
}
```

**Comment by martini** [comment]
Hi @dnauck 

thanks. Rails tries to detect if Zammad runs via http or https and regarding on this the `location: http://|https://` is set. So far as I can remember the `X-Forwarded-Proto` config option should solve this.

But in your case it seems that the `https` information is lost somewhere between your offloading nginx and the Zammad nginx.

I need to spend more time to research who rails/OmniAuth/OmniAuth::Strategies::MicrosoftOffice365 is detecting the current used http protocol stuff...

**Comment by dnauck** [comment]
Ok, thank you

**Comment by thorsteneckel** [comment]
@martini - I already did this in the past. You can find my summary [here](https://github.com/zammad/zammad/issues/723#issuecomment-279998976). I think the [`proxy_set_header X-Forwarded-Port 443;` line](https://github.com/zammad/zammad/issues/723#issuecomment-280690562) in the `location /` block is missing 🤔 

Edit: @dnauck if not, please add the [`config/initializers/debug_ssl.rb`](https://github.com/zammad/zammad/issues/723#issuecomment-280690562) and restart your Zammad application server. After that retry the OAuth and post the anonymized content of the `/tmp/omniauth.log` file here.

**Comment by dnauck** [comment]
@thorsteneckel missing in the nginx.conf of the zammad package/server or on my offloading system?

**Comment by thorsteneckel** [comment]
We need (at least) the `X-Forwarded-Proto` header in the Zammad process. So it needs to get passed through the nginx chain.

**Comment by dnauck** [comment]
I changed `proxy_set_header X-Forwarded-Proto $scheme;` in the zammad provided nginx.conf on the zammand system to  `proxy_set_header X-Forwarded-Proto https;`

This solved the problem. The location url is now: `location: https://helpdesk.domain.de/`.

**Comment by martini** [comment]
> This solved the problem. The location url is now: location: https://helpdesk.domain.de/.

Thanks for feedback!
