### ISSUE TITLE
In some situations the chat button is visible without a active websocket connection

### ISSUE THREAD

**Issue by tomstar76** [zammad/zammad#2258]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): Ubuntu Package
* Operating system: Ubuntu 16.04 Server
* Database + version: MySQL 5.7.23
* Elasticsearch version: 5.6.12
* Browser + version: Chrome 69.0.3497.100 

### Expected behavior:

Chat button should not be visible when websocket connection was closed (because of to long idle time).

### Actual behavior:

When the page with the implemented chat stays longer open/idle i get the message in the console **WebSocket is already in CLOSING or CLOSED state.** when clicking the custom trigger to open the chat.

### Steps to reproduce the behavior:

Implement chat with parameter **show: false** 

```
new ZammadChat({
    fontSize: '12px',
    chatId: 1,
    show: false
    idleTimeout: 1
});
```

use a custom trigger like:
```<button class="open-zammad-chat">Chat with us</button>```

Wait one minute and see that the button is still visible after the websocket connection was closed, because of the reached idle time. If you click on the button, nothing will be happen and you see a error message in the log.

**Comment by toastbrotch** [comment]
my quickfix on almost the same setup:
```
<button class="open-zammad-chat">let's chat</button>
<script>
$('.open-zammad-chat').click(function(e){
    $('.zammad-chat').css('display','');
    $('.zammad-chat').addClass('zammad-chat-is-loaded');
    $('.zammad-chat').addClass('zammad-chat-is-shown');
    $('.zammad-chat').addClass('zammad-chat-is-open');
});
$(function() {
  new ZammadChat({
    background: '#000000',
    fontSize: '12px',
    chatId: 1,
    show: false
  });
});
</script>
```
seems to work so far... anything against that?

**Comment by dominikklein** [comment]
@tomstar76 i take a look in this issue and it seems that the first problem was already be fixed in the meanwhile.

I will take a look in the second problem.

**Comment by dominikklein** [comment]
I changed the issue description to the currently existing problem. We decided to hide the chat button after the websocket connection was closed, because of the reached idle time.
If the default idle time from 6 minutes is to short for you, you can increase this with the chat initialization `idleTimeout: 10`.
