### ISSUE TITLE
Zendesk-Import fails for User & Organizations if Plan is below "Team"

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2262]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

* When importing existing data from Zendesk, Zammad should Import all data. If user has plan below "Team" this will lead to 403 "access" denied and Zammad should ignore Users & Organizations and simply go on importing (with letting the user know).

### Actual behavior:

* Zammad's Zendesk-Migrator fails / cancels the import, if it receives "403-Error" while importing Users and Organizations. Zammad should move on.

### Steps to reproduce the behavior:

* Get Zendesk, fill it with sample data and choose a plan below "Team"
* Try to migrate your zendesk instance over to Zammad - this will fail.

Please see information from Zendesk: https://support.zendesk.com/hc/en-us/community/posts/360000840067--403-Forbidden-zendesk-API-user-fields-

This comes from mdupreejr & nske from community: https://community.zammad.org/t/still-trying-to-import-from-zendesk/917/5

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by ikanade** [comment]
Hello, I've managed to replicate this issue with a Zendesk account with plan "Essential". I can also confirm that this issue doesn't affect "Trial" plans. I'll be working on a fix for this and will soon send a PR for getting some feedback.
