### ISSUE TITLE
Zammad fails to autogenerate links if <span>-Object appears within link

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2263]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

* When pasting text into e.g. a trigger E-Mail-Body Zammad should create a link when the trigger fires.

### Actual behavior:

* Zammad fails creating a link when the trigger fires, if <span>-Elements appear within the parts a URL is

### Steps to reproduce the behavior:

* Modify the trigger for e.g. auto reply that it contains <span>-Elements. Martin and I suspect a copy paste from a Browser (or even Website) causing the inclusion of those elements.
* Make the trigger fire and check the E-Mail
  The link will not be generated with span-Elements, but without

Example of evilness here:
`#{config.http_type}://<span style=\"background-color: initial;\">\#{config.fqdn}/#ticket/zoom/\#{ticket.id}<br><br><br></span>`

Clean Trigger-Content should look like this within links:
`#{config.http_type}://#{config.fqdn}/#ticket/zoom/#{ticket.id}`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Small appendix (sorry about that): This also applies to signatures (and I guess it might happen for ticket bodies as well)

**Comment by fliebe92** [comment]
Hey @MrGeneration, could you please explain to us what the real issue here is? We're not understanding it at all.

Thanks for your time :)

**Comment by MrGeneration** [comment]
This is one of my first issues issued to this repo 9 days after I started at Zammad.
There's no way I can remember what the exact issue was after close to 5 years sorry.

If it doesn't explain good enough (and as it doesn't hold any ticket relation), feel free to close it.
