### ISSUE TITLE
Unprocessable_mail 

### ISSUE THREAD

**Issue by Wisou** [zammad/zammad#2265]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): package
* Operating system: deb8
* Database + version: postgresql 9.4
* Elasticsearch version: 5.6.12
* Browser + version: 

### Expected behavior:

*

### Actual behavior:

*

### Steps to reproduce the behavior:

*

Hi,

This morning, a customer send us a new mail for support.
Zammad don't create a new ticket.
We have see in production.log this error : 

[root][zammad][/opt/zammad/tmp/unprocessable_mail][✓]# grep c6d0f7b6c11d282c71f5712b27508c75.eml /var/log/zammad/production.log
E, [2018-10-04T09:02:55.555936 #23867] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/c6d0f7b6c11d282c71f5712b27508c75.eml, please create an issue at https://github.com/zammad/zammad/issues

Can you help us ?

Bye

[c6d0f7b6c11d282c71f5712b27508c75.zip](https://github.com/zammad/zammad/files/2445695/c6d0f7b6c11d282c71f5712b27508c75.zip)

**Comment by thorsteneckel** [comment]
Hi @Wisou - I can't reproduce this on latest `develop` branch. Could you please verify this by updating to latest / develop and run `Channel::EmailParser.process_unprocessable_mails` via the [Zammad rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console).
