### ISSUE TITLE
Selection for ticket attribute "article.body" in Trigger

### ISSUE THREAD

**Issue by nk-Zammad** [zammad/zammad#2271]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:
When configuring an automatic e-mail( Trigger), the placeholder "articel.body" and all other article place holder should be listed in the list by pressing "::".

### Actual behavior:
In Trigger -> Changes -> E-Mail the placeholder "articlel.body" is not shown in the list if you press "::".
However, you can enter the placeholder "article.body" manually, it will also be correctly transferred - this will list the last article of the ticket quoted in the automatic email.

### Steps to reproduce the behavior:
generate an auto-Email via Trigger, fill in the textfield #{article.body}

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
develop: https://github.com/zammad/zammad/commit/195e264cb8ad94b0e411a1f82e2fbcba2259eedd 

stable: https://github.com/zammad/zammad/commit/a3c0d67c8ca625bdc8015aa3dd5e0b7353efcc1a

@hanneshal

**Comment by martini** [comment]
Just added magic lines to have magic placeholders and all references. :-D

<img width="905" alt="screen shot 2018-10-25 at 15 16 38" src="https://user-images.githubusercontent.com/110226/47502872-175df780-d869-11e8-8797-d226025ee3a9.png">
