### ISSUE TITLE
Bulk Form javascript error when checking item

### ISSUE THREAD

**Issue by biesbjerg** [zammad/zammad#2273]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..):
Package, according to https://docs.zammad.org/en/latest/install-debian.html
* Operating system:
Debian 9
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* Checking tickets in views should show bulk form.

### Actual behavior:

* Javascript error is shown i console. No bulk form is shown.
```
application-abd4e1a9aab02102f0c36662d7cca3be6871cc386f753acef8a141e8b25f252f.js:41 Uncaught TypeError: Array.prototype.indexOf called on null or undefined
    at indexOf (<anonymous>)
    at application-abd4e1a9aab02102f0c36662d7cca3be6871cc386f753acef8a141e8b25f252f.js:41
    at Function.y.every.y.all (application-abd4e1a9aab02102f0c36662d7cca3be6871cc386f753acef8a141e8b25f252f.js:5)
    at n.shouldShowBulkForm (application-abd4e1a9aab02102f0c36662d7cca3be6871cc386f753acef8a141e8b25f252f.js:41)
    at n.shouldShowBulkForm (application-abd4e1a9aab02102f0c36662d7cca3be6871cc386f753acef8a141e8b25f252f.js:41)
    at application-abd4e1a9aab02102f0c36662d7cca3be6871cc386f753acef8a141e8b25f252f.js:41
    at HTMLInputElement.<anonymous> (application-abd4e1a9aab02102f0c36662d7cca3be6871cc386f753acef8a141e8b25f252f.js:26)
    at HTMLTableElement.dispatch (application-abd4e1a9aab02102f0c36662d7cca3be6871cc386f753acef8a141e8b25f252f.js:2)
    at HTMLTableElement.m.handle (application-abd4e1a9aab02102f0c36662d7cca3be6871cc386f753acef8a141e8b25f252f.js:2)
```

### Steps to reproduce the behavior:

* Check a ticket in any view.

I'm logged in as Admin with 'Full' access to all groups.

**Comment by pebosi** [comment]
Can't reproduce in latest stable 2.6 Package. Maybe it's your browser?

**Comment by biesbjerg** [comment]
I've originally received the report from a co-worker. I've tested using Chrome and Firefox, using Admin user and an Agent user, with the same results. 

Could I somehow be on a version that are not stable since I'm seeing this error and you are not? 

```
user@helpdesk:/etc/apt/sources.list.d# cat zammad.list
# This file was generated by dl.packager.io

deb https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 9 main
```

**Comment by pebosi** [comment]
You mean a View like this: /#ticket/view/all_unassigned ?

**Comment by biesbjerg** [comment]
Yes, doesn't matter which one.

![image](https://user-images.githubusercontent.com/230182/46616733-7e667700-cb1b-11e8-96e5-09d60fc7779d.png)

**Comment by thorsteneckel** [comment]
Hi @biesbjerg - could you please provide the file `public/assets/application-abd4e1a9aab02102f0c36662d7cca3be6871cc386f753acef8a141e8b25f252f.js` from your Zammad directory?

**Comment by MrGeneration** [comment]
A hosted customer is experiencing this issue as well. From one of my test instances this feature vanished as quickly as it arrived. 

Thorsten, I sent you the js-file-Link via Mattermost

![image](https://user-images.githubusercontent.com/6549061/46721820-4b83c680-cc74-11e8-8108-507dd3612135.png)

**Comment by biesbjerg** [comment]
@thorsteneckel Sure :) Here you go! https://gist.github.com/biesbjerg/5e1beb80b77e9f582998b9d1dede84d7

**Comment by thorsteneckel** [comment]
Thank you! I figured out the cause of it. It's a bug introduced in [this commit](https://github.com/zammad/zammad/commit/45fee1b75230356cd729c806e2ed6564bf672759). It's caused by [this line](https://github.com/zammad/zammad/blob/7dd6675552e10409db98c9eccaaaf540d0a929b8/app/assets/javascripts/app/controllers/ticket_overview.coffee#L1225) which only checks for the Groups (permissions) of the current user but doesn't check the Roles (permissions). Which is in general a bug but in systems where all Group permissions are assigned via Role assignments this JS bug occurs.

We will prioritize and fix this 👍

**Comment by martini** [comment]
@SummerStorm I guess this will help.  https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/models/user.coffee#L257

By the way it would be nice to add a short doc.
