### ISSUE TITLE
Display name not used

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#2275]
### Infos:

* Used Zammad version:develop
* Installation method (source, package, ..): git
* Operating system: CentOS 7
* Database + version: PostgreSQL 9.5
* Elasticsearch version: n.a.
* Browser + version: Firefox 62

### Expected behavior:

* When selecting an existing customer during a reply, ticket creation etc. the display name should be  displayed and not only the email address.

### Actual behavior:

* When selecting an existing customer during a reply, ticket creation etc. the display name is not displayed, only the email address is shown.

### Steps to reproduce the behavior:

* Select an existing customer

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by maysam** [comment]
@rkaldung can you attach a screenshot too?

"the display name should be displayed only the email address" is not very clear

**Comment by rkaldung** [comment]
@maysam You're absolutely right, there was something missing. I fixed the wording and here are the screenshots:

![image](https://user-images.githubusercontent.com/378324/46711387-73f7ca80-cc4c-11e8-9739-c6a582d300b3.png)
![image](https://user-images.githubusercontent.com/378324/46711417-8a058b00-cc4c-11e8-8b75-e534847739c9.png)

Take a look at the 2nd screenshot: Only the email address is shown, not the display name.
