### ISSUE TITLE
Feature: Schedule sending email response to customer

### ISSUE THREAD

**Issue by henobi** [zammad/zammad#2280]
Hi, a nice feature in Zammad would be if one could optionally set a date and time when the email response will be send to a customer :-)

Benefits:
* Working at night on tickets, but want them to be send during business hours

**Comment by thorsteneckel** [comment]
Hi @henobi - Please read our intro text before creating issues. This is not an issue but a feature proposal. You can propose features over at https://community.zammad.org/ and discuss them with the community. We will pick up the most wanted features then. Closing now.
