### ISSUE TITLE
SLA GUI - inconsistency when no checkmark is set

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#2282]
### Infos:

* Used Zammad version: latest 2.7
* Installation method (source, package, ..): package
* Operating system: CentOS
* Database + version: Postgres
* Elasticsearch version: 5.7
* Browser + version: Safari latest

### Expected behavior:

* If I uncheck every escalation time in the SLA screen it should save this state or throw an error that at least on time has to be checked

### Actual behavior:

* The dialog is closed and my selection is not stored

### Steps to reproduce the behavior:

* Create an SLA in the admin area
* modify the checkmarks to "none selected"
* save it
* reopen the SLA edit screen -> The first checkmark is there

An error should be shown or it should be possible to create SLAs without escalation times (allow zero)

**Comment by MrGeneration** [comment]
This also applies, if you select "Update TIme" and/or "Solution Time" and apply those options.
Zammad displays those escalation times cleanly on the UI - as soon as you open the SLA to edit it, the wizard automatically "enables" "First Response Time"  with two hours of time.
