### ISSUE TITLE
LDAP-User not deactivated if source user is deactivated

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2286]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

* When deactivating a LDAP-User within Active Directory the user gets deactivated in Zammad, after the LDAP-Synch has run.

### Actual behavior:

* When deactivating a LDAP-User within Active Directory the user is not being deactivated in Zammad, after the LDAP-Synch has run.

### Steps to reproduce the behavior:

* Configure Zammad to synch LDAP
* After successfull synch, deactivate a user of your choice within LDAP
* run the LDAP-Synch again
* check the user in Zammad (it will not be deactivated)

Note: This has been verified with Microsoft Active Directory 2016.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
How does a deactivated user differ from an active user in the LDAP search result set? From my understanding the LDAP filter should be changed to only list active users or the active flag should be mapped to the Zammad active flag.

**Comment by MrGeneration** [comment]
Hey,

just looked that up. Within MicrosoftAD this would be set under "userAccountControl" (array maybe?)

![image](https://user-images.githubusercontent.com/6549061/46936070-6b90fc80-d05d-11e8-9509-0b24359318d0.png)

Here's the difference to an activated account
![image](https://user-images.githubusercontent.com/6549061/46936097-82375380-d05d-11e8-9457-7f2924c9901e.png)

**Comment by thorsteneckel** [comment]
I just verified my assumption with @rkaldung (thanks!) and we came to the conclusion that this works as desired/designed. You should limit the search result by applying the correct filter for your AD. These two links will help:

https://blogs.msdn.microsoft.com/muaddib/2008/10/08/how-to-query-individual-properties-of-the-useraccountcontrol-active-directory-user-property-using-ldap/
https://docs.microsoft.com/en-us/windows/desktop/adsi/search-filter-syntax
