### ISSUE TITLE
Reports visualization capabilities don't scale well with larger number of results

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2290]
### Infos:

Not applicable as this is a enhancement request.
Comes from Ticket#1029155

### Actual behavior:

When your viewing reports with a lot of results, the overview of actual numbers suffers extremly.
As example, if Zammad chooses 50 tickets per step, you cannot determine if you had 60 or 65 Tickets on that particulary day (without breaking it down further).

This gets even worse, as you cannot hover the graph to get the actual count.

Examples:
![image](https://user-images.githubusercontent.com/6549061/47082183-198ed900-d20d-11e8-96b7-87fc74244466.png)
![image](https://user-images.githubusercontent.com/6549061/47082195-227faa80-d20d-11e8-887b-c0a84cb68c12.png)

### Wanted behavior:

So here kicks in the enhancement of a customer (and partly me)...
As for better overview I would change the position of graph and the date /  time selection (display the time selection above the graph / table so that you don't have to scroll too much when fiddling the timespan you want).

Also, I'd like a selector (like year, month, week ....) for switching between table and graph, less scrolling (yay). The result could look something like the two images below. Please note that this is a real quick image manipulation without clean working on it. I'm sure that the frontend part has to be optimized from that.

A table would give you the exact numbers and might -in some cases- look better than a graph when you want to get the real counts.

![zammad-reporting_graph-wtable](https://user-images.githubusercontent.com/6549061/47082395-af2a6880-d20d-11e8-9dbe-7b8c5641cfb1.png)
![zammad-reporting_table-wtable](https://user-images.githubusercontent.com/6549061/47082397-b05b9580-d20d-11e8-8067-991df937d015.png)

**Important hint**
Please do not start a big conversation here, as many people are watching this repository.

**Comment by thorsteneckel** [comment]
Zammad is no and won't be a reporting tool. If you require more advanced reporting functionalities contact our support for a [Graphana](https://grafana.com/) integration or custom reporting modules and functionalities.

PS: Please always fill out the issue template completely because we require those informations. Thanks!

**Comment by thorsteneckel** [comment]
Sorry for the misunderstanding. As discussed internally this is not sufficiently practicable with Graphana. Therefore I reopen the issue.

**Comment by MrGeneration** [comment]
We internally decided that this is not a feature that we'll implement into our stable branch.

Sorry for the hassle.
