### ISSUE TITLE
Add input field in ticket form for custom object

### ISSUE THREAD

**Issue by lttlnnj** [zammad/zammad#2294]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..):
* Operating system: Ubuntu
* Database + version: PostGreSQL 
* Elasticsearch version:
* Browser + version: Google Chrome 69.0.3497.100

### Expected behavior:
Add an input field in ticket form for custom object.
*

### Actual behavior:
Can't add new field in form for new attributes or custom object.
*

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

Also this is already addressed [here](https://github.com/zammad/zammad/issues/1889) - found via "custom field" search 🤓
