### ISSUE TITLE
Quotation with single press of "ENTER" not possible anymore

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2304]
### Infos:

* Used Zammad version: 2.6.1 / current develop
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: Google Chrome 69.0.3497.100, MS Edge 42.17134.1.0  - Firefox 62.0.3 is **not** affected

### Expected behavior:

* When marking a text and pressing reply for quoting text, you can then enter answers within the quote by simply pressing ENTER (and thus breaking the quote).

### Actual behavior:

* When marking a text and pressing reply for quoting text, you need to press ENTER twice to break the quote for answering within quotation.

### Steps to reproduce the behavior:

* Create a ticket with some text
* mark that text and click on reply
* click at any last character within a line and press enter (quote won't be "opened") 
  you'll need to press ENTER twice for that

![quote-break](https://user-images.githubusercontent.com/6549061/47305515-f8255700-d629-11e8-8c2b-b7e3d6553c89.gif)

Yes I'm sure this is a bug and no feature request or a general question.

This comes from Ticket #1029886 and has high priority (martin).

**Comment by SummerStorm** [comment]
@MrGeneration On the latest `develop` I can confirm that it takes two ENTER to break the quote. 

However, I also tried version 2.5.0 from back in June 2018 and it exhibited the exact same behavior, so this behavior has been consistent throughout. I will close this issue for now as "won't fix". I already pinged Martin about this course of action so he has any objections or follow-ons we can re-open this again. 

I agree that a single ENTER would be better, but if the double ENTER behavior has been consistent throughout then we need to look at this from the cost benefit perspective.
