### ISSUE TITLE
Tickets through mail with multiple groups in To: and CC: will all receive the ticket and create "ticketmail" users for each other

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2307]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: -
* Elasticsearch version: -
* Browser + version: any

### Expected behavior:

* Group on CC: gets ignored per default
* Configured Ticketmails do not create a user if system receives mail with another group on CC: or To: and Ticket does not get two new replys (from User and Group on CC) but only User reply gets logged.

### Actual behavior:

* When receiving tickets via e-mail and customers already know two different group e-mail addresses, if customers now put one group in To: and one on CC: both groups will open the same ticket. (Same happens if both groups are on To:)
* If one group is on To: and the other on CC: the CC: Groupmail will create a new customer and the Original reply from the customer will be logged twice, once from the customer and once from the Groumail on CC.

### Steps to reproduce the behavior:

* Create two groups, Assign two different mail accounts to groups, create test user, let testuser open ticket with group1 on To and group2 on CC per e-mail.
* You can also reply to the original customer inquiry and put group 2 on CC. This will create a new user with group2 mail and log it in the ticket. The following picture shows this. Customer is NT, Agent is yellow NV, CC reply creates user blue NV and logs answer twice in ticket.
![capture](https://user-images.githubusercontent.com/44224243/47342394-e6809580-d6a3-11e8-9c38-483ca973567e.PNG)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Verified on Zammad 2.10 develop.
Zammad should ignore it's own E-Mail-Addresses and not create Customers from it.

**Comment by poiNt3D** [comment]
Has it been fixed now?
