### ISSUE TITLE
Chat is broken when JS library is loaded asynchronously

### ISSUE THREAD

**Issue by mruettgers** [zammad/zammad#2309]
We are encountering an issue when the chat library is loaded asynchrounously or programatically.
In our case we have to delay the loading of the ZammadChat app until the jQuery library on the page has been loaded to avoid conflicts caused by loading multiple jQuery libraries on the same page.

The ZammdChat app tries to detect the Zammad base url in an early stage by evaluating the `src` attribute of the last `script` element that has been added to the DOM.
In case the script is loaded asynchronously, the value of the `src` attribute is null, which will result in an exception when trying to access the regex search result.

The related code part is:

https://github.com/zammad/zammad/blob/a3e531af21370293fa806fc04b397023c7948d12/public/assets/chat/chat.js#L70-L72

The evaluation of the script tag should be moved to the detectHost() method and thus only be triggered when there is no host passed as an option.

This won't resolve the issue caused by the empty `src` attribute, but it would allow us to workaround the problem by specifying the host manually.

The issue could be reproduced with the following code snippet (tested with Chrome):
```
<html>
<head>
	<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
</head>
<body>
	<script src="https://baseurl.to.zammad/assets/chat/chat.min.js" async></script>
	<script>
	$(function() {
	  new ZammadChat({
		background: '#057ad7',
		fontSize: '12px',
		chatId: 1
	  });
	});
	</script>
</body>
</html>
```
The chat will work after removing the `async`  option in the script tag.

**Comment by ksh5** [comment]
`onload` Event?

```
<script src="https://baseurl.to.zammad/assets/chat/chat.min.js" onload="initZammad()" async></script>
<script>
function initZammad() {
    console.log('chat.min.js is loaded, initializing Zammad...');

    $(function() {
        new ZammadChat({
            background: '#057ad7',
            fontSize: '12px',
            chatId: 1
        });
    });
};
</script>
```

**Comment by mruettgers** [comment]
That won't solve the issue, because the exception is thrown in `chat.min.js` itself after beeing loaded.
Even without instantiating `ZammadChat`.

**Comment by ksh5** [comment]
Ah, I see. I think `document.currentScript` https://github.com/ksh5/zammad/commit/f39422ba27c9dc8aeb60a87d633ed586b61ca458 should work when loading async. No IE support (and no proper polyfill) though 😞

**Comment by dominikklein** [comment]
I can no longer reproduce this problem. I think it was already improved with this changes: https://github.com/zammad/zammad/issues/2435
