### ISSUE TITLE
Contact form needs a prefix

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#2310]
### Infos:

* Used Zammad version: 2.7.x
* Installation method (source, package, ..): rpm
* Operating system: CentOS
* Database + version: Postgres
* Elasticsearch version: 5.6
* Browser + version: Safari latest

### Expected behavior:

* The form elements should have a "zammad-" prefix, like the elements in the chat

### Actual behavior:

* There is no prefix, so the css can potentially overwritten  by other css classes (like in Gambio Shops. for example)

### Steps to reproduce the behavior:

* open the contact form window, check the classes

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
The prefix should exist until 5.2 (https://github.com/zammad/zammad/issues/4048).
