### ISSUE TITLE
Mail add failed

### ISSUE THREAD

**Issue by JackXu2** [zammad/zammad#2311]
zammad is very good software, and i install on one on-promise Centos 7 by bleow guide 
https://docs.zammad.org/en/latest/install-centos.html
all the system work very well.
but after install Centos 7 in Aliyun cloud, the add mail always failed(use same account on-promise used), below is the error 
![mail](https://user-images.githubusercontent.com/30012551/47438458-13849380-d7dd-11e8-8b07-76c64b7aa2dd.PNG)

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.
