### ISSUE TITLE
Ruby 2.5 / Ubuntu 18.04 support : already worked out some of the details...

### ISSUE THREAD

**Issue by unquietwiki** [zammad/zammad#2313]
I saw new versions were coming out tonight, but still didn't have newer Ruby support. Here's a list of things I've run into, trying to make it work.

- _Gemfile changes:_ **ruby '2.4.4'** -> **ruby '2.5.0'** ; **gem 'rails', '5.1.5'** -> **gem 'rails', '5.2.1'**
- _Gemfile addition:_ **gem 'activerecord', '5.2.1'**
- _Gemfile addition:_ **gem 'sassc-rails'** ; [Reference](https://github.com/sass/sassc-rails) & [Deprecation of Sass](http://sass.logdown.com/posts/7081811)
- _Gemfile deletions:_ **gem 'libv8'** and **gem 'therubyracer'** ; possibly **gem sass**
- Need to install [NodeJS](https://nodejs.org/) + add **ENV['EXECJS_RUNTIME'] = 'Node'** to **config/boot.rb** ; [Reference](https://stackoverflow.com/questions/51379326/current-execjs-runtime-doest-support-es6)

**Comment by thorsteneckel** [comment]
Hi @unquietwiki - thanks for your effort. Our current focus is on adding functionalities but we will update our stack asap. However, we only track bugs on our issue tracker for now and have any kind of discussions or questions over at the [community board](http://community.zammad.org/) to not send over 100 mails to people watching this repository. If there is anything that you're missing in our tech stack please create a post over there and let me/us know. Closing now 🚀

**Comment by unquietwiki** [comment]
@thorsteneckel Acknowledged. https://community.zammad.org/t/ruby-2-5-preparation/1490 posted. Thanks!
