### ISSUE TITLE
Pending closed/reminder date selector shows current date black on dark gray

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2316]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: x
* Elasticsearch version: x
* Browser + version: all
* Ticket #1086042

### Expected behavior:

* Current date on date selector when setting pending closed/reminder state should have a higher color contrast to the dark grey background e.g. like the selected date is colored in light blue which can be read on any monitor:
![image](https://user-images.githubusercontent.com/44224243/47558963-a247fc00-d914-11e8-8a7b-aab0c08443a6.png)

### Actual behavior:

* Date Selector shows current date black on dark grey which makes it hard to read on cheap or uncalibrated monitors. For reference, in the following picture the 26th is selected.

![image](https://user-images.githubusercontent.com/44224243/47558842-5ac17000-d914-11e8-89af-2decaabf15d0.png)

### Steps to reproduce the behavior:

* Have bad eyes/monitor
* Go to any ticket
* Try to set ticket to pending closed
* Try to find current date on first try

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by franz-xaver** [comment]
When the date picker is opened and no date is set 'today' is still not visible.
You'll have to click on 'today' and to reopen the date picker.

**Comment by MrGeneration** [comment]
This is a regression of #946

**Comment by mantas** [comment]
@mrflix what's your opinion on this?
