### ISSUE TITLE
Zendesk import fails on first ticket when it has fields with cyrillic names

### ISSUE THREAD

**Issue by ZlobnyiSerg** [zammad/zammad#2317]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): docker
* Operating system: Ubuntu 18
* Database + version: Postgres 9.6
* Elasticsearch version:
* Browser + version: Chrome 70

### Expected behavior:

* Zendesk ticket import processing fine

### Actual behavior:

* Import stops on first ticket  with error: `ImportJob 'Import::Zendesk' failed: Problem with ObjectManager Attribute '_': At least one letters is needed`

Detailed log with DEBUG level:
```
D, [2018-10-25T08:04:14.303508 #1074] DEBUG -- : Getting 'resource' value (ZendeskAPI::TicketField): #<ZendeskAPI::TicketField {"url"=>"https://sanatorium.zendesk.com/api/v2/ticket_fields/32089309.json", "id"=>32089309, "type"=>"tagger", "title"=>"Внутренний статус", "raw_title"=>"Внутренний статус", "description"=>"", "raw_description"=>"", "position"=>7, "active"=>true, "required"=>false, "collapsed_for_agents"=>false, "regexp_for_validation"=>nil, "title_in_portal"=>"Внутренний статус", "raw_title_in_portal"=>"Внутренний статус", "visible_in_portal"=>false, "editable_in_portal"=>false, "required_in_portal"=>false, "tag"=>nil, "created_at"=>2016-10-20 07:23:38 UTC, "updated_at"=>2018-05-22 08:11:22 UTC, "removable"=>true, "agent_description"=>"", "custom_field_options"=>[{"id"=>35325789, "name"=>"В работе", "raw_name"=>"В работе", "value"=>"в_работе", "default"=>false}, {"id"=>35325809, "name"=>"Зафиксировано", "raw_name"=>"Зафиксировано", "value"=>"зафиксировано", "default"=>false}, {"id"=>35325829, "name"=>"Передано в разработку", "raw_name"=>"Передано в разработку", "value"=>"передано_в_разработку", "default"=>false}, {"id"=>40401569, "name"=>"Приостановлен", "raw_name"=>"Приостановлен", "value"=>"приостановлен", "default"=>false}, {"id"=>360000015999, "name"=>"Выполнена", "raw_name"=>"Выполнена", "value"=>"выполнена", "default"=>false}]}>
D, [2018-10-25T08:04:14.304026 #1074] DEBUG -- : Getting 'model_class' value (Class): Ticket(id: integer, group_id: integer, priority_id: integer, state_id: integer, organization_id: integer, number: string, title: string, owner_id: integer, customer_id: integer, note: string, first_response_at: datetime, first_response_escalation_at: datetime, first_response_in_min: integer, first_response_diff_in_min: integer, close_at: datetime, close_escalation_at: datetime, close_in_min: integer, close_diff_in_min: integer, update_escalation_at: datetime, update_in_min: integer, update_diff_in_min: integer, last_contact_at: datetime, last_contact_agent_at: datetime, last_contact_customer_at: datetime, last_owner_update_at: datetime, create_article_type_id: integer, create_article_sender_id: integer, article_count: integer, escalation_at: datetime, pending_time: datetime, type: string, time_unit: decimal, preferences: text, updated_by_id: integer, created_by_id: integer, created_at: datetime, updated_at: datetime, phone_number: string)
D, [2018-10-25T08:04:14.304243 #1074] DEBUG -- : Getting 'sanitized_name' value (String): "_"
D, [2018-10-25T08:04:14.304543 #1074] DEBUG -- : Cache read: ObjectLookup::Ticket
D, [2018-10-25T08:04:14.307572 #1074] DEBUG -- :   ObjectManager::Attribute Load (0.7ms)  SELECT  "object_manager_attributes".* FROM "object_manager_attributes" WHERE "object_manager_attributes"."object_lookup_id" = $1 AND "object_manager_attributes"."name" = $2 LIMIT $3  [["object_lookup_id", 2], ["name", "_"], ["LIMIT", 1]]
E, [2018-10-25T08:04:14.308962 #1074] ERROR -- : ImportJob 'Import::Zendesk' failed: Problem with ObjectManager Attribute '_': At least one letters is needed
E, [2018-10-25T08:04:14.309348 #1074] ERROR -- : Problem with ObjectManager Attribute '_': At least one letters is needed (RuntimeError)
```

### Steps to reproduce the behavior:

* Setup clean Zammad
* Choose "Import from Zendesk"
* Use account with ticket fields named in cyrillic (Russian)

Renaming fields to english didn't helped. I'm even not sure what part of ticket's field Zammad uses as the name of attribute?

**Comment by thorsteneckel** [comment]
This is caused by this line:
https://github.com/zammad/zammad/blob/0db8c28bd57b7cad7deb8d96e08c618dd34b8692/lib/sequencer/unit/import/common/object_attribute/sanitized_name.rb#L43

Because ActiveSupport::Inflector.transliterate does not support cyrillic chars (out of the box).

There is a map between latin and cyrillic in a gem that can be re-used:

https://github.com/tjbladez/translit/blob/b1ea8a6adf5aea6345074dae6226f9cc1bc72ab7/lib/translit.rb#L46-L52

A workaround is to rename the title of the Object Attributes in Zendesk into latin spelling.

**Comment by cyberrranger** [comment]
@ZlobnyiSerg sry for offtopic, but you you help me? I'm install Zammad 2.7 with docker but i cant't find a "Import Zendesk" Button :/

**Comment by thorsteneckel** [comment]
Hi @cyberrranger - please keep the issue on topic. You can ask (technical) questions over at the [community board](http://community.zammad.org/) - there are plenty of lovely people willing to help 💪

**Comment by dominikklein** [comment]
At the moment the Zendesk import can not support a direct import for the object attributes with Cyrillic characters inside the name (because of the limitations in the used rails sanitize function). The workaround would be to rename the field and later after the import, the visible Label of the created object attribute can be changed inside Zammad.
