### ISSUE TITLE
Documentation for facebook channel is missing

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#232]
[online documentation link](https://zammad.org/documentation/channel/facebook) points to 404 error page

**Comment by monotek** [comment]
Partly fixed in https://github.com/zammad/zammad.org/pull/2

**Comment by martini** [comment]
Done. 🤓 https://zammad.org/documentation/channel/facebook

**Comment by monotek** [comment]
Still up?
Mail channel needs some work to ;-)

https://zammad.org/documentation/channel/mail
