### ISSUE TITLE
After upgrading to 2.7, user management is blank

### ISSUE THREAD

**Issue by fernandodiacenco** [zammad/zammad#2320]
Hello,

After upgrading to 2.7, everything is still working except user management

We have LDAP integration with active directory, the integration seems to be working as before, previous logins work, email tickets work

But if I try to create a ticket, it wont find any clients, can't find anyone in the user management interface either

I tried resync with ad, the resync works but nothing changes

Is there a way to rebuild the user base or something? otherwise I would have to restore from backup

Thanks.

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

Reads like something is wrong with your Search. There should be note in your `log/production.log` file. Maybe your Elasticsearch is not configured/indexed properly.

**Comment by fernandodiacenco** [comment]
Ok, let me leave this here just for posterity, thanks.

If anybody out there had a similar problem after upgrading, this is what I've done to fix it

> Remove deprecated plugin mapper-attachments
> /usr/share/elasticsearch/bin/elasticsearch-plugin remove mapper-attachments
> 
> Remove older version of ingest-attachment (if exists)
> /usr/share/elasticsearch/bin/elasticsearch-plugin remove ingest-attachment
> 
> Install latest version of ingest-attachment
> /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-attachment
> 
> Start ElasticSearch Service
> service elasticsearch start
> 
> Rebuild index
> zammad run rake searchindex:rebuild
