### ISSUE TITLE
Browser autofill on add/edit customer causes mysql error

### ISSUE THREAD

**Issue by wtc-jeff** [zammad/zammad#2323]
### Infos:

* Used Zammad version: 2.7.0
* Installation method (source, package, ..): source
* Operating system: Debian 9.1
* Database + version: Mysql (MariaDB 10.1.26)
* Elasticsearch version: Not installed
* Browser + version: Chrome 69.0.3497.100

### Expected behavior:

* Use browser provided information to populate fields for new user

### Actual behavior:

* User not created, error is shown.

Sanitized error:

> Mysql2::Error: Cannot add or update a child row: a foreign key constraint fails (`zammad_prod`.`users`, CONSTRAINT `fk_rails_d7b9ff90af` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`)): UPDATE `users` SET `organization_id` = 0, `firstname` = 'Jeff', `lastname` = 'Lastname', `phone` = '123456789', `address` = '123 My Street', `updated_at` = '2018-10-30 14:51:15.507000' WHERE `users`.`id` = 69

### Steps to reproduce the behavior:

* Start new ticket, create new user and use browser to auto fill the fields, click submit.  Also works if you edit a customer and clear fields and use autofill to repopulate.

If you manually fill in all the fields the user is created without error.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @wtc-jeff - There is something wrong here. The error message says that the `organization_id` is `0` which should not be possible. The Organization input field has the HTML `autocomplete=off` attribute set so no Browser auto fill should be possible in this field. Could you please reproduce this on one of our [free hosted instances](https://www.zammad.com/getting-started), tell us the name of the instance and make a litte video of the behavior (full screen). Thanks!

**Comment by wtc-jeff** [comment]
Hi there,

I have reproduced using the hosted platform and recorded the error.  Please see the attached zip

[zammad error.mp4.zip](https://github.com/zammad/zammad/files/2538744/zammad.error.mp4.zip)

Jeff

**Comment by SummerStorm** [comment]
Hi wtc-jeff, thank you for the clear and concise video. We are now able to reproduce the issue. A fix will be coming shortly.

# Detailed step to reproduce
1. This only occurs on Chrome with autofill turned on. Go to Chrome settings, turn on `Autofill forms`, and add an address with a name and an organization:

![324324](https://user-images.githubusercontent.com/7030950/47916030-b628ca80-dedf-11e8-8508-1834e8f7e856.png)

 2. Open the user create/update form in Zammad, and use the autofill. The `input[name='organization_id']` input element will be autofilled but it is not visible. There are two input elements, one visible and one invisible:

![324324324](https://user-images.githubusercontent.com/7030950/47916192-49620000-dee0-11e8-8516-7dc499095594.png)

3. Click submit and you will see an error message.

# Problem on the front end
1. [searchable_select.jst.eco#L15](https://github.com/zammad/zammad/blob/fbf6133dfdc6b8e9cb2a765d9fbb43aff1a7ed3d/app/assets/javascripts/app/views/generic/searchable_select.jst.eco#L15) correctly disabled autofill for earlier versions of Chrome, but newer version of Chrome now require `    autocomplete="new-password"` to work:

https://stackoverflow.com/questions/43783924/disable-google-chrome-autocomplete-autofill-suggestion

https://stackoverflow.com/questions/10938891/disable-form-autofill-in-chrome-without-disabling-autocomplete

2. Only one of the input fields have the `autocomplete` attribute. That might have been enough before but browser heuristics are continuously changing and so now we need `autocomplete="new-password"` for both input elements. 

# ~~Problem on the back end~~
~~This is not strictly a bug, but the current error message is very misleading, and fixing the error message could help with debugging other bugs down the road.~~

EDIT: After discussions with the team, we decided not to change the backend behavior. The current error message is less than ideal but the cost of engineer and maintaining a fix is not worth a slightly better error message for a rare corner case. 

### How to reproduce

`POST` the following JSON to `/api/v1/users`
```
{
	"firstname": "Max",
	"lastname": "Mustermann",
	"email": "max@example.com",
	"password": "123",
	"organization_id": "INVALID"
}
```
`Current result`: 422 Unprocessable Entity with the error message: 
`
PG::ForeignKeyViolation: ERROR:  insert or update on table \"users\" violates foreign key constraint \"fk_rails_d7b9ff90af\"\nDETAIL:  Key (organization_id)=(0) is not present in table \"organizations\".\n: INSERT INTO \"users\" (\"organization_id\", \"login\", \"firstname\", \"lastname\", \"email\", \"password\", \"preferences\", \"updated_by_id\", \"created_by_id\", \"created_at\", \"updated_at\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING \"id\"
`

`Expected result`: 422 Unprocessable Entity with the error message: `organization_id INVALID is invalid`

**Comment by thorsteneckel** [comment]
Hi @wtc-jeff - I discussed this issue with @mrflix and after some research we came to the conclusion that this is actually [a bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=370363#c7) which ignores the `autocomplete="off"` attribute but shouldn't. Therefore this is a third party issue and I close this one.

**Comment by SummerStorm** [comment]
Hi wtc-jeff, seems like I spoke too soon about a fix. As a work around, you can clear out the `Organization` field in Chrome's Settings -> Autofill -> Address form:

![4324324](https://user-images.githubusercontent.com/7030950/48072331-39fff100-e217-11e8-9611-0d5438feb0c8.png)

This issue does not appear as long as the `Organization` field does not get autofilled.
