### ISSUE TITLE
Websocket messages are not working correctly via Ajax long polling (e. g. multiple browser tabs can get opened with one session).

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2327]
### Infos:

* Used Zammad version: 2.7
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Do not allow to have multiple browser windows for one session to prevent parallel working on tasks - as it is via native web socket messages right now).

### Actual behavior:

* No session duplicate blocker is shown if web socket server is stopped (and Ajax long polling is used).

### Steps to reproduce the behavior:

* stop web socket server
* open Zammad in Browser Window #1
* open Zammad in Browser Window #2
* no session duplicate blocker is shown

**Comment by MrGeneration** [comment]
Verified for fixing the problem, thanks!
