### ISSUE TITLE
Upgrade 2.6 to 2.7 Webpage broken

### ISSUE THREAD

**Issue by Hagelsturm** [zammad/zammad#2331]
Hello i use Debian 9 afer Upgrde to 2.7 the webpage is broken :-(
![webpage](https://user-images.githubusercontent.com/32170104/47987743-98768380-e0e0-11e8-83c7-ad96297af0ce.png)

I hope everybody can help me

**Comment by Hagelsturm** [comment]
2018/11/05 09:55:44 [error] 1217#1217: *375 open() "/opt/zammad/public/assets/application-c8043f03a169bb84f3dc0ad53d5b1f98d7e97e6965212a7a3ae326f333cceabc.css" failed (2: No such file or directory),

**Comment by Hagelsturm** [comment]
I fixed a rename the css file

**Comment by martini** [comment]
Thanks for feedback. Just a hint, the application-XXX.css is content of the Zammad package. So it seems it got not installed on you machine or you did not restart the zammad application server.

**Comment by Hagelsturm** [comment]
thans the package was installed but the id behind application was diffrent
