### ISSUE TITLE
Zammad stops Organization and TextModule pagination after 500 entries

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2337]
### Infos:

* Used Zammad version: 2.7, including 3.4
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: n/a
* Ticket-ID: #1030543, #1047215, #1070112

### Expected behavior:

* When having more than 500 organizations inside your instance, you can see a list of all Organizations with pagination without any hussle.

### Actual behavior:

* When having more than 500 organizations inside your instance, you can see a list of all Organizations with pagination up to page 4 and entry 500.
* Normally a pagination page on organization contains 150 entries, the last page does not and doesn't show everything.

### Steps to reproduce the behavior:

* Fill the database with test organizations ( `FillDB.load(agents: 0,customers: 0,groups: 0,organizations: 500,overviews: 0,tickets: 0,)`
* Check pagination on organization page

Search function does help finding organizations, but this is rather unwanted by users. This goes into a similare direction like #2214 .

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dennykorsukewitz** [comment]
Hi @MrGeneration 

here you can see the limit of organizations:
https://github.com/zammad/zammad/blob/develop/app/controllers/organizations_controller.rb#L51-L70

https://github.com/zammad/zammad/blob/develop/app/controllers/organizations_controller.rb#L66

https://github.com/zammad/zammad/blob/develop/app/controllers/organizations_controller.rb#L69

The limit here is set to 500.

@martini Should we take out the limit?

**Comment by martini** [comment]
Here for me it's similar, IMO nobody is searching in a list over 500 records. So probably we should also (like for users) show the last created 50 organizations and make the organizations area searchable. 

@mrflix any UX recommendations?
