### ISSUE TITLE
Percent-encoded URLs are corrupted

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2340]
### Infos:

* Used Zammad version: 2.7
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: Impacts all Browsers
* Ticket-IDs: #1030647, #1030633

### Expected behavior:

* When sending an E-Mail with an URL (no matter if the E-Mail is Text or HTML), Zammad will not change the URL in any means.

### Actual behavior:

* When sending an E-Mail with an URL containing "%253A" hex-encodings (only with HTML-based E-Mails), Zammad will change the URL. "%253A" will be converted to ":". 
* Whensending an E-Mail with an URL containing "%7D" hex-encodings (only happens with HTML-based E-Mails), Zammad will change the URL. "%7D" will be converted to "}".
* Whensending an E-Mail with an URL containing "%7B" hex-encodings (only happens with HTML-based E-Mails), Zammad will change the URL. "%7B" will be converted to "{".

### Steps to reproduce the behavior:

* Send a HTML-E-Mail no matter of it's size with the following content to Zammad: `https://test.local/PMGQUAR%253Asece%2540blaaah.de%253A6BE4C1`
  (You can send one as Text as well, to see it only happens with HTML-Stuff)
* Wait for Zammad to fetch the E-Mail and open the new ticket
* You will see, that the link is visually unchanged, but as soon as you hover over the link, you will see this: `https://test.local/PMGQUAR:sece@blaaah.de:6BE4C1`
  Thus - the URL has been changed. This shouldn't be done by Zammad.

This also happens with the following sample link:
```
https://domain.tld/base.html?configuration=%7B%22810543%22%3A%5B%2210053974%22%5D%2C%22810544%22%3A%5B%2210053990%22%5D%2C%22810545%22%3A%5B%2210054000%22%5D%2C%22810546%22%3A%5B%2210054001%22%5D%2C%22810547%22%3A%5B%2210054002%22%5D%2C%22810548%22%3A%5B%2210054003%22%5D%2C%22810549%22%3A%5B%2210054004%22%5D%2C%22810550%22%3A%5B%2210054024%22%5D%2C%22810551%22%3A%5B%2210054046%22%5D%2C%22810552%22%3A%5Bnull%5D%2C%22810553%22%3A%5B%2210054051%22%5D%7D
```

This is technically not invalid, but can break compatibility to software that expects the exact link to be used (as it sent). Another (big) problem is, that the display of the link differs from the link Zammad makes clickable. This is missleading.

Yes I'm sure this is a bug and no feature request or a general question.

I edited this Issue on 16.11.2018 and extended it with further samples.

**Comment by GeSi-Software-GmbH** [comment]
Same issue here with Zammad 2.8.0.
We copy links into ticket reply mails which have encoded question marks in the path section of the URL. The correct link looks like **https://test.local/Question%3F**
but Zammad decodes the question mark and destroys the link by sending
**https://test.local/Question?**
(the question mark is then interpreted as query separator).

**Comment by MrGeneration** [comment]
As we were looking on this issue we noticed that we can no longer reproduce this on the following versions:
* Zammad 3.2 stable
* Zammad 3.3 stable
* Zammad 3.4 stable

We currently expect this to be fixed by one of our releases, maybe a side effect of another issue addressing something else. Commit unknown.

---

@GeSi-Software-GmbH If you happen to still experience this issue on a *current and stable Zammad installation*, please let me know.
