### ISSUE TITLE
Role filter needs linebreak or dropdown list

### ISSUE THREAD

**Issue by Charburner** [zammad/zammad#2341]
### Infos:

* Used Zammad version: 2.6.X
* Installation method (source, package, ..):
* Operating system: CentOS 7.5.1804
* Database + version: PostgreSQL 9.2.24
* Elasticsearch version: 5.6.11
* Browser + version: Firefox 63.0.1

### Expected behavior:

* The role filter in Zammads user management should let you easily select roles no matter if there are 5 or 50 roles.
* The role filter element should be improved by for example add a **linebreak function** or switch to a **multiselect dropdown list**.

### Actual behavior:

* The role filter element can not display more than X roles in a user friendly way. It just grows to the right infinitely the more roles you have configured. If you want to manage users by filtering the roles you will end up in scrolling to the right to select roles, scrolling to the left to view the result and so on.

![roles1](https://user-images.githubusercontent.com/26415550/48342481-0f2af800-e670-11e8-9dfc-feaedf60ec49.PNG)

![roles2](https://user-images.githubusercontent.com/26415550/48342482-0f2af800-e670-11e8-9b88-5273725806b8.PNG)

### Steps to reproduce the behavior:

* Create several roles (like 10-15)
* Manage users by utilizing the role filter
* Realize the filter grows to the right forcing you to scroll back and forth

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by fliebe92** [comment]
Closing due to fixing https://github.com/zammad/zammad/issues/4406.
