### ISSUE TITLE
Lost DB connection causes jobs to not be processed anymore

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2343]
### Infos:

* Used Zammad version: 2.7 (but rather all)
* Installation method (source, package, ..): n/a
* Operating system: n/a (verified on Ubuntu 16.04)
* Database + version: postgreSQL
* Elasticsearch version: n/a
* Browser + version: n/a 

### Expected behavior:

* Zammad will continue it's work (even if a Database-Process / socked dies) as soon as the database connection is back up and functional. Zammad will also use Monitoring to indicate problems (if there are any with database).

### Actual behavior:

* Zammad does continue it's work (except for delayed Jobs and thus Notifications, E-Mails and SMS ) if some of the database processes get killed. It does not indicate problems in monitoring and will just throw errors until a new database connection can be established by restarting the processes. The Delayed::Job gem logs the following line:

```
I, [2018-11-12T16:56:33.875406 #4559] INFO -- : 2018-11-12T16:56:33+0100: [Worker(host:some_name pid:1337)] Error while reserving job: PG::ConnectionBad: PQsocket() can't get socket descriptor: UPDATE "delayed_jobs" SET locked_at = '2018-11-12 15:56:33.873572', locked_by = 'host:some_name pid:1337' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2018-11-12 15:56:33.872595' AND (locked_at IS NULL OR locked_at < '2018-11-12 11:56:33.872665') OR locked_by = 'host:some_name pid:1337') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
```

### Steps to reproduce the behavior:

* Run Zammad normally with all it dependencies
* Kill random psql-processes (important not to kill the parent process)
  funfact: you need to have luck to get the scheduler process for delayed job control
* Ensure the PSQL-Service is still running and try to send EMails (won't work)
* Restart PSQL and keep watching the log file
* The DB-Error will self-heal after about 5-10 minutes (in my case) and send E-Mails

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
This is fixed in `develop` and `stable` with the commits above via a workaround. There is a [pull request](https://github.com/collectiveidea/delayed_job_active_record/pull/163) pending. After it got merged (hopefully) we will remove the workaround.
