### ISSUE TITLE
Notification settings checkboxes show wrong state

### ISSUE THREAD

**Issue by Charburner** [zammad/zammad#2346]
### Infos:

* Used Zammad version: 2.7.X
* Installation method (source, package, ..): rpm
* Operating system: CentOS 7.5.1804
* Database + version: PostgreSQL 9.2.24
* Elasticsearch version: 5.6.11
* Browser + version: Firefox 63.0.1

### Expected behavior:

* In the notification settings of each users profile, the "Limit Groups" checkboxes state should always match the actual stored value in the database.

### Actual behavior:

* When trying to deactivate all checkboxes at once, the page will reload with a "successful" message, but it will show all checkboxes as active, even though the corresponding database entry has correctly been changed (which means it does not contain any group_id).

### Steps to reproduce the behavior:

* Go to your profile and open up the notification settings
* Unmark all checkboxes in "Limit Groups" and submit
* Realize after the page reload, all checkboxes are marked

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Charburner** [comment]
Additionally I realized, when you disable all checkboxes, you will nevertheless get notification mails for accessible groups.

So for me at least it seems to be more than a "visual" bug. Maybe someone can confirm this behaviour?

**Comment by thorsteneckel** [comment]
In latest develop the checkboxes will be re-checked after the "successful" notification is shown. So yes, it's more than visual. We'll have a look 👍
