### ISSUE TITLE
Merging two Tickets with link to same other Ticket fails

### ISSUE THREAD

**Issue by nk-Zammad** [zammad/zammad#2347]
### Infos:

* Used Zammad version: 2.7.y
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1030519, #1072793, T#1072793, T#1079290

### Expected behavior:

*it is expected that child tickets can be merged with other child tickets.

### Actual behavior:

*The actual behavior is that when two childtickets are merged, the error message "Object already exists!" appears. 

### Steps to reproduce the behavior:

* I am editing a "Child Ticket" and would like to combine this with another "Child Ticket". I click on the right side on "Merge", it opens the list with the tickets that can be summarized, I want to merge this with another child ticket this is not possible I get an error message called  "Object already exists!"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by KoJie** [comment]
T#1030519

**Comment by fs-zammad** [comment]
T#1072793
