### ISSUE TITLE
add e.g. screenshots form clipboard doesn't work (FireFox 45.3.0)

### ISSUE THREAD

**Issue by ColVen** [zammad/zammad#235]
As already mentioned by "Tillmann" on heise (https://www.heise.de/forum/iX/News-Kommentare/Helpdesk-Software-Zammad-die-Open-Source-Alternative-zu-Zendesk/Erster-Eindruck-nach-einem-Kurztest/posting-29375300/show/) it's currently not possible to just paste a screenshot from clipboard right into an issue.
I tried this at a few places in zammad but without success. 

My Browser is a FireFox 45.3.0 and I used the tryout zammad at helpdesk.zammad.com

**Comment by thorsteneckel** [comment]
Hi @ColVen could you please provide further information on your OS?

**Comment by martini** [comment]
JFI: I can reproduce it.

**Comment by martini** [comment]
Update. In the meantime firefox fixes this issue (was incompatibility with HTML5 drag and drop API). It's working fine with FF50. 

@ColVen any feedback is welcome.

See also #505
