### ISSUE TITLE
Unable to cancel attachment upload

### ISSUE THREAD

**Issue by Charburner** [zammad/zammad#2351]
### Infos:

* Used Zammad version: 2.6.X, 4.1/stable
* Installation method (source, package, ..): rpm
* Operating system: CentOS 7
* Database + version: PostgreSQL 9.2.24
* Elasticsearch version: 5.6.11
* Browser + version: Firefox 63 + Internet Explorer 11.0

### Expected behavior:

* Users should be able to cancel attachment uploads by clicking "cancel upload" while creating tickets or composing articles.

### Actual behavior:

* The "cancel upload" button does not do anything. I don't know wether it is not clickable or it lacks an event or something like that.

### Steps to reproduce the behavior:

* Create a new ticket or add a reply to an existing ticket
* Add an attachment and try to cancel the upload

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I could verify this. This applies to develop and also stable 2.7 and seems to impact all Browsers.

As far I can tell the events are linked and there, I guess this is rather a layer problem.
I added a hover function to check if a normal hover works - it does not.

Edit: I can't find the cause of this :(



![image](https://user-images.githubusercontent.com/6549061/48622314-a3fe6000-e9a6-11e8-9012-63a301f243da.png)
