### ISSUE TITLE
Forward option default is public and not internal

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2355]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: x
* Elasticsearch version: x
* Browser + version: x

### Expected behavior:

* When Forwarding an article from a ticket to e.g. a none zammad group e-mail the forwarded message should be kept internal per default and the external reply as well.
* This is particularly important if you work with external developers and you want to forward a customer bug report and keep the discussion between dev and support internal.

### Actual behavior:

* The forwarded message and the external reply received will both be logged publicly in the ticket.

### Steps to reproduce the behavior:

* Create ticket
* Forward first article to none zammad group e-mail
* Reply from the none zammad group e-mail

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @SEGGER-NV - this is more of a (technical) question. Please refer to the [community board](http://community.zammad.org/) for questions and discussions. The proper use case from my understanding would be to split the ticket and work in the the new ticket (linked) independently. Closing now.
