### ISSUE TITLE
User without customer role can still create tickets over webform and e-mail

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2357]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): package
* Operating system: 
* Database + version:
* Elasticsearch version:
* Browser + version: Firefox

### Expected behavior:

* If e.g. an unwanted SPAM user is set as inactive and has customer roles removed (also has no other role) he should not be able to create tickets via e-mail or the web form.

### Actual behavior:

* The opposite. Any user ever registered to the Zammad system can always open tickets via web-form or if API is used and the Zammad Admin can't do anything against it if the mentioned channels are used. This is horrible behaviour and makes any web form approach basically unusable.
* Mail can at least be blocked via Mail filter rules so the spammer e-mail is added. This is still very inconvenient but at least works to block users.

### Steps to reproduce the behavior:

* Create new ticket via e-mail or web-form (external web forms that use the API are also affected). 
* Set the user to inactive and remove his customer role.
* Try creating a new ticket using the aforementioned channels. Still works.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Just a short note: `inactive != blocked`. There are use cases where you need to create tickets for inactive users. But it seems that we need another attribute to `block` users.

**Comment by SEGGER-NV** [comment]
Hello, 

Thank you for clarifying the inactive state.
A blocked state would be highly appreciated.

**Comment by bebosudo** [comment]
Hi!
being able to block/ignore certain users/servers that spam emails is a vital feature that we need in a ticketing system. Any news on this?

**Comment by MrGeneration** [comment]
I'm locking the conversation of this issue to contributors only.
Please don't get us wrong, but this is to reduce noise on the tracker like "I need this", "when does this come" etc.

We're working hard on solving issues and bugs.
However, this is a feature backlog enhancement which has no ETA as of now.

If anything changes on this issue, we'll update this issue accordingly. :-)
If you absolutely need this feature, you're always welcome to sponsor these kind of features (or develop an addon).

Bests!

**Comment by Mirtaaa** [comment]
Hello!
We are currently re-structuring our Backlogs and new Feature Requests should be created directly in our community. Therefore, I imported this request into our community and will close it here. You can follow the progress here:
[User without customer role can still create tickets over webform and e-mail](https://community.zammad.org/t/user-without-customer-role-can-still-create-tickets-over-webform-and-e-mail/12237)
