### ISSUE TITLE
If ticket gets created via e-mail, Zammad creates accounts for all people on To: and CC:

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2358]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: x
* Elasticsearch version: x
* Browser + version: x

### Expected behavior:

* When a customer opens a ticket by writing to the set up ticket e-mail only the FROM: entry should create a Zammad user.

### Actual behavior:

* Zammad creates user profiles for all people on CC: and TO: as well
* This is a major red flag considering the current GDPR laws as none of the people on CC: TO: have agreed to the company's privacy policy and they are not getting informed (in the default zammad trigger setting) that a user account has been created.

### Steps to reproduce the behavior:

* Set up any ticket mail in Zammad
* Use a external dummy customer from any mailhoster
* Open ticket by writing to ticketmail@company.com and put other mailaccounts on CC: and TO: that have no Zammad useraccount yet

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by hanneshal** [comment]
Hi, 

interesting topic. 
Some questions regarding this:

Where do you see the difference to let's say an Exchange server which stores an E-Mail? We do not store any other information related to this. 
Why do you see the consent on the side of the receiver and not on the side of the sender? 

We move those conversations out of the issue tracker until we got a solution. 
So I created a thread here:
https://community.zammad.org/t/if-ticket-gets-created-via-e-mail-zammad-creates-accounts-for-all-people-on-to-and-cc-gdpr-question/1611

regards and a happy weekend

Johannes
