### ISSUE TITLE
Attached text files get prepended on e-mail reply instead of appended.

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2362]
### Infos:

* Used Zammad version: 2.7.0
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: x
* Elasticsearch version: x
* Browser + version: Firefox

### Expected behavior:

* When attaching text files (e.g. .txt, .c, .h, ...) to an e-mail reply the attachment should be appended like it usually does for archives and pictures.

### Actual behavior:

* The text file attachment gets prepended in the e-mail which creates a weird e-mail flow.
* Especially if you are sending large text files that include code it can get very confusing for the customer.

### Steps to reproduce the behavior:

* User Creates Ticket.
* Agent answers and attaches any type of text file.
* Check actually sent e-mail, the text file is prepended.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
I can verify this. See attached mail send via Ticket#1031042.

[PrependedTextAttachmentBug.eml.zip](https://github.com/zammad/zammad/files/2607417/PrependedTextAttachmentBug.eml.zip)
