### ISSUE TITLE
MySQL Syntax Error on db:migrate

### ISSUE THREAD

**Issue by zottto** [zammad/zammad#237]
Trying to install Zammad on Uberspace, I get the following error message, ehen executing rake db:migrate (bundle exec rake db:migrate).

== 20120101000001 CreateBase: migrating =======================================
-- create_table(:sessions)
   -> 0.0397s
-- add_index(:sessions, :session_id)
   -> 0.0368s
-- add_index(:sessions, :updated_at)
   -> 0.0503s
-- add_index(:sessions, :persistent)
   -> 0.0642s
-- create_table(:users)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(3), `source` varchar(200), `login_failed` int(11) DEFAULT 0 NOT NULL, `preferen' at line 1: CREATE TABLE `users` (`id` int(11) auto_increment PRIMARY KEY, `organization_id` int(11), `login` varchar(100) NOT NULL, `firstname` varchar(100) DEFAULT '', `lastname` varchar(100) DEFAULT '', `email` varchar(140) DEFAULT '', `image` varchar(100), `image_source` varchar(200), `web` varchar(100) DEFAULT '', `password` varchar(100), `phone` varchar(100) DEFAULT '', `fax` varchar(100) DEFAULT '', `mobile` varchar(100) DEFAULT '', `department` varchar(200) DEFAULT '', `street` varchar(120) DEFAULT '', `zip` varchar(100) DEFAULT '', `city` varchar(100) DEFAULT '', `country` varchar(100) DEFAULT '', `address` varchar(500) DEFAULT '', `vip` tinyint(1) DEFAULT 0, `verified` tinyint(1) DEFAULT 0 NOT NULL, `active` tinyint(1) DEFAULT 1 NOT NULL, `note` varchar(250) DEFAULT '', `last_login` datetime(3), `source` varchar(200), `login_failed` int(11) DEFAULT 0 NOT NULL, `preferences` varchar(8000), `updated_by_id` int(11) NOT NULL, `created_by_id` int(11) NOT NULL, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL) ENGINE=InnoDB

Thanks,
Marc

**Comment by qpwr** [comment]
Same here.

**Comment by monotek** [comment]
OS? MySQL Version?

**Comment by Seonnyn** [comment]
Having the Same Issues, kind of solved it by removing all "limit"s from timestamps and datetimes in the migrate files

(Debian 8.6 Mysql Ver 14.14 Distrib 5.5.52, for debian-linux-gnu (x86_64) using readline 6.3)

**Comment by zottto** [comment]
CentOS 6
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1

**Comment by martini** [comment]
Hi Marc,

nice to read from you. Since we need millisecond in timestamps to validate the cache (yes, we are really fast :) ) we need as prerequisite a mysql/mariadb which is supporting this too.

MySQL can do it with 5.6+, MariaDB 5.3+

Read more: http://dev.mysql.com/doc/refman/5.7/en/fractional-seconds.html
https://mariadb.com/kb/en/mariadb/microseconds-in-mariadb/

 -Martin

**Comment by qpwr** [comment]
@martini, a check script for such prerequisites would be very helpful. Maybe there is one and I just overlooked it?

**Comment by monotek** [comment]
@ Martini 
I just adding "Prerequisites" to the documentation.
Which Postgres versions work? 
There was a problem wit 9.6 in the bugtracker so i think 9.4 - 9.5?

**Comment by martini** [comment]
@qpwr: a good idea 🤔

**Comment by martini** [comment]
@monotek Postgresql 9.1+

**Comment by martini** [comment]
@zottto Mögliche Lösung für Uberspace: https://wiki.uberspace.de/database:mysql#mariadb_100 -> Sollte mit MariaDB 10.0 gehen.

**Comment by zottto** [comment]
@martini Already tried that with no luck. Manual login works (mysql -h 127.0.0.1 -P 3307 --password), but adding "127.0.0.1:3307" in config/database.yml only shows error:
#<Mysql2::Error: Unknown MySQL server host '127.0.0.1:3307' (1)>
Is there a problem with ports other than the default port?

**Comment by thorsteneckel** [comment]
Port should be configured via:

```yml
  host: 127.0.0.1
  port: 3306
```

**Comment by zottto** [comment]
Thanks, works now!

**Comment by martini** [comment]
I should tell you before. I link postgresql much more. No 🚀issues. 🤓

**Comment by zottto** [comment]
I'll test it with MariaDB as first step. :-) I'm just happy to have a running system :-D

**Comment by martini** [comment]
Database version check done at app boot sequence - Thanks @zottto and @qpwr  https://github.com/zammad/zammad/commit/d7115a6be5a0c0eabc9e82ed50032533a6e85f0e
