### ISSUE TITLE
Unprocessable broken mail (without From, To and Body)

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#2372]
### Infos:

* Used Zammad version: 2.7.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Unprocessable broken mail (without From, To and Body) should get logged and ignored

### Actual behavior:

* Unprocessable broken mail (without From, To and Body) is just unprocessable

### Steps to reproduce the behavior:

* Import attached [broken_mail.eml.zip](https://github.com/zammad/zammad/files/2611235/broken_mail.eml.zip) via `cat /path/to/broken_mail.eml | rails r 'Channel::Driver::MailStdin.new'`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Seems to work now. Mail gets dropped to the unprocessable email folder:
```
ubuntu-rs@ubuntu-rs:/workspace/git_zammad/zammad$ cat tmp/unprocessable_mail/7f3b44b2915070a1af1d9d190afd2ba2.eml
Date: Mon, 01 Jan 2001 01:00:00 +0100
Subject: <Kein Betreff>
From:
Message-ID: <AAA-AAA-AAA-AAA-AAA-AAA@contoso.com>
Mime-version: 1.0
Content-type: text/plain;
        charset="UTF-8"
Content-transfer-encoding: 7bit

```
