### ISSUE TITLE
Zammad fails to seed/migrate translations while installing on MariaDB 10.3

### ISSUE THREAD

**Issue by RihanArfan** [zammad/zammad#2373]
### Infos:

* Used Zammad version: Latest from Ubuntu DEB
* Installation method (source, package, ..): Package (Ubuntu 16.04 as I don't think 18.04 is compatible)
* Operating system: ubuntu 16.04.5 LTS
* Database + version: MariaDB 10.3.10
* Elasticsearch version: Latest
* Browser + version: Chrome

### Expected behaviour:

* Seeding and migration just fine without any errors.

### Actual behaviour:

https://file.properties/paste/uxodifujed

### Steps to reproduce the behaviour:
(Following https://docs.zammad.org/en/latest/install-ubuntu.html)
* Set the database.yml like https://file.properties/paste/sipoyuwipi within /opt/zammad/config
* Ensure MariaDB 10.3.10 is the target MySQL instance software and then install and watch the automatic migrations. Everything is fine except for translations.

Yes, I'm sure this is a bug and no feature request or a general question.

**Comment by RihanArfan** [comment]
I've also tried the following and have received these errors. https://file.properties/paste/vugokulipi

**Comment by RihanArfan** [comment]
Alright, I've sorted the issue. I deleted the database and ran the command to allow Zammad to create it, which is `zammad run rake db:create`, and that has ensured that tables are all UTF8 collation.
 
Thank you all for the amazing piece of software.

**Comment by thorsteneckel** [comment]
Hi @LeCodeCo - very cool that you figured out things yourself AND shared how here 👍 Would be cool though if you could ask technical questions over at the [community board](http://community.zammad.org/) first - Thanks!

**Comment by RihanArfan** [comment]
Ah, sorry.

I thought that the import database stuff would be more of a bug than a technical question and the issue template mentioned that other than that, everything else should be on the community board if I remember correctly.
