### ISSUE TITLE
OTRS import fails for DynamicFields of Type Dropdown without possible values

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#2375]
### Infos:

* Used Zammad version: 2.7
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* DynamicFields of type Dropdown without a value for the Attribute `PossibleValues` should be skipped.

### Actual behavior:

```
ActiveRecord::RecordInvalid: Validation failed: Data option must have non-nil value for either :options or :relation
from app/models/object_manager/attribute.rb:370:in add
from lib/import/otrs/dynamic_field.rb:56:in add
from lib/import/otrs/dynamic_field.rb:13:in initialize
from lib/import/base_factory.rb:36:in new
from lib/import/base_factory.rb:36:in create_instance
from lib/import/base_factory.rb:12:in block in import_action
from lib/import/base_factory.rb:40:in each
from lib/import/base_factory.rb:40:in import_loop
from lib/import/base_factory.rb:9:in import_action
from lib/import/otrs.rb:148:in import_action
from lib/import/otrs.rb:73:in import
from lib/import/otrs.rb:158:in base_objects
from lib/import/otrs.rb:41:in start
```

### Steps to reproduce the behavior:

* Try to import the following (JSON) data structure:

```json
{
  "Name":          "ITSMDecisionResult",
  "FieldType":     "Dropdown",
  "ObjectType":    "Ticket",
  "ValidID":       "1",
  "InternalField": "1",
  "ID":            "13",
  "FieldOrder":    "9",
  "CreateTime":    "2012-09-04 10:05:48",
  "Label":         "Decision Result",
  "ChangeTime":    "2015-02-05 15:07:10",
  "Config":        {
    "PossibleValues":     null,
    "PossibleNone":       "1",
    "TranslatableValues": "1",
    "Link":               "",
    "DefaultValue":       null
  }
},
{
  "Name":          "ITSMReviewRequired",
  "FieldType":     "Dropdown",
  "ObjectType":    "Ticket",
  "Label":         "Review Required",
  "ChangeTime":    "2015-02-05 15:07:10",
  "CreateTime":    "2012-09-04 10:05:47",
  "ValidID":       "1",
  "InternalField": "1",
  "ID":            "11",
  "FieldOrder":    "8",
  "Config":        {
    "TranslatableValues": "1",
    "PossibleValues":     null,
    "PossibleNone":       "0",
    "Link":               "",
    "DefaultValue":       null
  }
}
```

This was reported via a [Community Board](https://community.zammad.org/t/otrs-import-fails-with-activerecord-validation-failed-data-option-must-have-non-nil-value-for-either-options-or-relation/1651) thread.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by bmsoft-de** [comment]
Hi,

We are also experiencing this same issue on zammad 3.0.0. Appears to be simple to resolve, only adding ITSMReviewRequired and ITSMDecisionResult to https://github.com/zammad/zammad/blob/7f8e268ae0d69252fa10d9813da801e6959042f7/lib/import/otrs/dynamic_field_factory.rb#L53

We don't know if there is some additional problems or why this is still open.

Thanks in advance.
bmsoft
