### ISSUE TITLE
Selfsigned SSL certificate doesn't work with Exchange sync

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2384]
### Infos:

* Used Zammad version: 2.7.x
* Installation method (source, package, ..): rpm
* Operating system: openSuSe
* Database + version: PostgreSQL 10.6
* Elasticsearch version: 5.6.13
* Browser + version: Google Chrome 70
* Ticket-IDs: #1030778, #1040440

### Expected behavior:

* When trying to setup an Exchange-Sync with a self signed Exchange-Certificate (default installation, nothing changed), Zammad will warn you about the self signed certificate ("Want to proceed or cancel?"). 
* If you proceed, Zammad will read the existing addressbook-folders from Exchange and after selection, read the folders content and import the existing contacts.

### Actual behavior:

* When trying to setup an Exchange-Sync with a self signed Exchange-Certificate (default installation, nothing changed), Zammad will warn you about the self signed certificate ("Want to proceed or cancel?"). 
* If you proceed, Zammad will read the existing addressbook-folders from Exchange and after selection, Zammad will return the following verification error (you can't get past this point).

`SSL_connect returned=1 errno=0 state=error: certificate verify failed`

### Steps to reproduce the behavior:

* Install an Active Directory and Exchange-Server without changing anything special (the default installer will issue a self signed certificate already) [For this step you can kindly ask me to provide you some natting so you can connect to my existing one ;) ]
* Login to Zammad and go to Exchange-Integration page
* Follow the configuration wizzard, enter credentials and Exchange-URL
* After proceeding the first SSL-Certificate warning, choose any addressbook and proceed. (this is the place where the error happens)

Please see attached logfile and screencast.

[zammad-exchangesync.log](https://github.com/zammad/zammad/files/2634483/zammad-exchangesync.log)

![error-zammad-exchangesync](https://user-images.githubusercontent.com/6549061/49306398-5a4b6480-f4d2-11e8-8ab0-630d70baba52.gif)

Yes I'm sure this is a bug and no feature request or a general question.

This error has been fixed earlier as by #1442

**Comment by fliebe92** [comment]
IMHO this was fixed in the meantime and is working fine currently.
