### ISSUE TITLE
Problems with default Locale

### ISSUE THREAD

**Issue by gabrielschmith** [zammad/zammad#2385]
### Infos:

* Used Zammad version: 2.7.0
* Installation method (source, package, ..): docker
* Operating system: macOS High Sierra
* Database + version:
* Elasticsearch version:
* Browser + version: Google Chrome - Version 70.0.3538.110 (Official Build) (64-bit)

### Expected behavior:

* Should respect the default locale set in the settings.

### Actual behavior:

* When starting the application on getting start/login screen the application is coming as Czech, should not come with the default language or language of the browser?

![image](https://user-images.githubusercontent.com/10456683/49346701-50199980-f67d-11e8-80d5-61269bf47925.png)

### Steps to reproduce the behavior:

* 1) Run command:  docker container run -ti -d --name zammad -p 80:80 zammad/zammad
   2) Do the getting start.
   3) Change default locale to: pt-BR 
   ![image](https://user-images.githubusercontent.com/10456683/49346707-5f98e280-f67d-11e8-8c6a-5c237e3a5eaa.png)

   4) Logout, page will still be with the correct translation.
   ![image](https://user-images.githubusercontent.com/10456683/49346712-763f3980-f67d-11e8-8454-5d6becd346d3.png)

   5) Perform the refresh on the page. After that page return to Czech, 
   ![image](https://user-images.githubusercontent.com/10456683/49346719-90791780-f67d-11e8-8dab-327e6dc9381e.png)

I'm new to Zammad, am I missing something? I would like to implement it in the company where i work. Can you help me?

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @gabrielschmith - I'm not sure that this is an actual issue. Let's make sure it's not a technical in the [community board](http://community.zammad.org/) first. Please create a thread over there and mention me via @thorsteneckel and I'll have a look.
Can you run `App.i18n.detectBrowserLocale()` in the JavaScript browser console of the window which is translated to Czech and post in the thread what it returned. Thanks!

**Comment by bebosudo** [comment]
Hi, I'm having a similar issue.
I'm using a linux system with only `en-us` as local, but I'm physically located in Italy: the login page is displayed in english on the first visit, then as soon as I login everything turns to italian, also the logout form, unless I refresh, in which case it turns back to english.

In Settings > Branding I set the default language to English (US); timezone is set to Europe/Rome: changing it to Europe/Berlin doesn't affect language.
I tried Settings > System > Services and disabling (setting to `-`) the Geo IP service (and also the Geo Calendar), but it didn't help.

It seems to me that the frontend is doing some IP location checks, could it be possible?

Seems similar to #2505, but this applies to the whole admin interface.
I tried logging in as a client user and the language locale is respected there.

```js
>>> App.i18n.detectBrowserLocale()
"en-us"
>>> console.log('window.navigator.languages', window.navigator.languages)
window.navigator.languages  Array [ "en-US", "en" ]
>>> console.log('window.navigator.userLanguage', window.navigator.userLanguage)
window.navigator.userLanguage undefined
>>> console.log('window.navigator.language', window.navigator.language)
window.navigator.language en-US
```

**Comment by MrGeneration** [comment]
@bebosudo please don't recycle old closed issues!
Your request is rather a technical question.

Please note that the agent preferences decide on the language he'll see (apart from browser detection).
You can find these settings here: https://user-docs.zammad.org/en/latest/extras/profile-and-settings.html


---

To reduce the noise on this repository and issue, I'll be limitting the conversation now. 
Please don't get me wrong, this repository is for bugs only.

If you have further questions or have technical questions, please feel free to use the Community instead: https://community.zammad.org
