### ISSUE TITLE
Chat Enabled Question

### ISSUE THREAD

**Issue by sinichi19** [zammad/zammad#2386]
* Used Zammad version: 2.7.0
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.4

Fresh installed of zammad and Im new of using it, I enabled the chat in the admin settings but where can i find the chat area when one of my agent and customer log in i saw only a blank page and only saw active 2 agents where can I start using the chat area?

Im not a developer and only reading the tutorials.

Please see Below picture 
### Actual behavior:
<a href="https://ibb.co/W5rWh64"><img src="https://i.ibb.co/pwHv7xB/zammad-chat.jpg" alt="zammad-chat" border="0"></a><br />

Thank You Very Much and More Power

**Comment by thorsteneckel** [comment]
Hi @sinichi19 - please refer to the [community board](http://community.zammad.org/) for (technical) questions. Thanks.
