### ISSUE TITLE
Macro not work in pending state

### ISSUE THREAD

**Issue by sinichi19** [zammad/zammad#2388]
## Infos:

* Used Zammad version: 2.8.0
* Installation method,-package
* Operating system: ubuntu 16.04

### Expected behavior:
Created macro to add tag and  auto change the state to pending reminder

(Like closed and tag spam)

### Actual behavior:
Added the tag successfully but not change the state to pending reminder to set the date.

Im new using zammad and Im not familiar if this behavior is normal.

Thank you more power

**Comment by thorsteneckel** [comment]
@MrGeneration - could you please verify this when you have the time?

**Comment by sinichi19** [comment]
If I may, any update Sir's 

Thank you

**Comment by thorsteneckel** [comment]
Dear @sinichi19,

first of all, many thanks for your participation on the Zammad open source project.

Not usual as with proprietary software, we finance Zammad through service. So it's less money we have at our disposal to push Zammad.

If you would like to support Zammad, you can do so via Zammad Support: https://zammad.com/pricing#selfhosted

For all issues it is generally important that we tag an issue as soon as it is included in a release. This means that manual enquiry only minimizes the available resources but not the speed of implementation.

Thank you for your understanding.

**Comment by sinichi19** [comment]
Yes sir @thorsteneckel I understand, 
Only want to know if its a bug or i have wrong settings, and nothing more 

More power...

Thank you and God bless

**Comment by thorsteneckel** [comment]
Please ask future technical questions over at the [community board](http://community.zammad.org/) - we will verify this (when we find the time) and update the issue accordingly 👍

**Comment by MrGeneration** [comment]
Sorry, this works as expected.
You can't change the state to "pending reminder" or "pending close" without specifying the "pending till" as both information are needed to create a pending state.

![image](https://user-images.githubusercontent.com/6549061/49956490-95ec2280-ff05-11e8-976c-299f79f83c14.png)


If you don't add "pending till", Zammad will ignore the state change.
