### ISSUE TITLE
LDAP integration page blank after deleting role

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2396]
### Infos:

* Used Zammad version: 2.8
* Installation method (source, package, ..): rpm
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: Firefox (current)
* ~~Ticket-ID: #1032485~~ (problem does not affect customer any further)

### Expected behavior:

* When going into LDAP-Integration, you can see the LDAP-Settings and if needed, change settings.

### Actual behavior:

* When going into LDAP-Integration, you can' see the LDAP-Settings. The only thing you see is the heading and the "enable/disable" button.

### Steps to reproduce the behavior:

* configure a LDAP-Synch
* after synching delete any role
* try to configure the ldap-integration again (won't work)

Side-Note: Logging in is not affected.

Yes I'm sure this is a bug and no feature request or a general question.

The following error get's thrown within developer console:
![image](https://user-images.githubusercontent.com/6549061/49649326-1653e480-fa29-11e8-9cfd-38fdde06cc9d.png)

Attached file is the hotfix for this issue, this still needs implementation and backend work.
Please note that during hotfixing at customer site, we encountered "counting entries" for ages (Zammad got stuck there), we had to edit the obsolete mapping on command line.

[ldap.zip](https://github.com/zammad/zammad/files/2657327/ldap.zip)

**Comment by dominikklein** [comment]
I could no longer reproduce this problem.
