### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#241]
Please provide a documentation for the api.

**Comment by martini** [comment]
Init version, any feedback is welcome!

https://zammad.org/documentation/api/intro
https://zammad.org/documentation/api/user
https://zammad.org/documentation/api/organization
https://zammad.org/documentation/api/ticket

PS: You can also work on in via PR & https://github.com/zammad/zammad.org/tree/master/content/6-documentation/20-api

**Comment by martini** [comment]
Also PHP & Ruby libs available for beta testing. ❤️

**Comment by martini** [comment]
Added also:

https://zammad.org/documentation/api/group
https://zammad.org/documentation/api/ticket-state
https://zammad.org/documentation/api/ticket-priority

**Comment by martini** [comment]
@MDXDave any comments on that?

**Comment by MDXDave** [comment]
Looks good!

But is there any way to get current user? like `/me` or `/users/me` ?

Currently the only way seems to search for the users mail address or username `/users/search?query=foo@bar.com` or `/users/search?query=username`

**Comment by martini** [comment]
@MDXDave good idea!

Done. :)

https://zammad.org/documentation/api/user && https://github.com/zammad/zammad/commit/da2a11cb8c4a69c65e4185bba0d1302ed58cd9d1

**Comment by MDXDave** [comment]
@martini where to create an application in the web interface as described [here](https://zammad.org/documentation/api/intro)?

**Comment by martini** [comment]
@MDXDave you man an application for OAuth2?

**Comment by MDXDave** [comment]
Yes

**Comment by martini** [comment]
For now Zammad 1.0 has basic auth, with Zammad 1.1 (in 3 weeks) we will ship OAuth2 (it's already in the documentation - sorry for confusing)

**Comment by MDXDave** [comment]
Alright.

By the way, i think some of the paths are not really RESTful.
For example `/ticket_articles/by_ticket/{id}`

Shouldn't it be something like `/articles?ticket_id={id}`?
Because `by_ticket` is not really a resource of `ticket_articles`, it's only a filter, so it should be in the query and not in the path.

Same for `/users/search?query={query}&limit={limit}&start={start}` => `/users?search={query}&limit={limit}&start={start}`

**Comment by martini** [comment]
Thanks for new ideas. :)

It there any doc/rfc out there where the RESTful url's a described? We really can change it, just want to make sure to have not other issue tomorrow with the opposite meaning/idea.

**Comment by MDXDave** [comment]
The following article describes a really good approach which can be followd while designing RESTful apis: http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

Resources that list multiple objects e.g. `/users` or `/organizations` should be search and filterable with query strings like `query` or the respective fields like `email` or `name`. Sort with `-name` or `name` (desc and asc) and (optional) the posibility to limit the fields returned by the api `fileds=name,user_id`

My recommendations are:

| HTTP METHOD | POST            | GET       | PUT         | DELETE |
| ----------- | --------------- | --------- | ----------- | ------ |
| CRUD OP     | CREATE          | READ      | UPDATE      | DELETE |
| /users/me| - | List current user | Update current user  | - |
| /users  | Create new user | Show users   | - | - |
| /users/{id}  | -  | Show user with `{id}`   | Update user with `{id}` | Delete user with `{id}` |
| /organizations  | Create new organization | Show organizations   | - | - |
| /organizations/{id}  | -  | Show organization with `{id}`   | Update organization with `{id}` | Delete organization with `{id}` |
| /groups  | Create new group | Show groups   | - | - |
| /groups/{id}  | -  | Show group with `{id}`   | Update group with `{id}` | Delete group with `{id}` |
| /tickets  | Create new ticket | Show groups   | - | - |
| /tickets/{id}  | - | Show ticket with `{id}`   | Update ticket with `{id}` | Delete ticket with `{id}` |
| /tickets/{id}/articles  | Create new article | Show articles with ticket id `{id}`   | - | - |
| /tickets/{id}/articles/{aid}  | - | Show article with `{aid}` | Update article with `{aid}`   | Delete article with `{aid}` |
| /tickets/{id}/articles/{aid}/attachments | Upload attachment | Show attachments | - | - |
| /tickets/{id}/articles/{aid}/attachments/{aaid} | - | Show attachment with `{aaid}` | - | Delete attachment with `{aaid}` |
| /ticket_states  | Create new ticket state | Show ticket states   | - | - |
| /ticket_states/{id}  | - | Show ticket states with `{id}`  | Update ticket state with `{id}` | Delete ticket state with `{id}` |
| /ticket_priorities  | Create new ticket priority | Show priorities  | - | - |
| /ticket_priorities/{id}  | - | Show ticket priority with `{id}`  | Update ticket priority with `{id}` | Delete ticket priority with `{id}` |

If it is important to access messages without ticket id, there can be a synonym `/articles/{id}` which returns the same as `/tickets/{tid}/articles/{id}`

**Comment by MDXDave** [comment]
@martini any thoughts? :cat:

**Comment by MDXDave** [comment]
@martini no comment?:smile:

**Comment by martini** [comment]
Sorry! Sounds good. Just busy with other issue. :-o

Will come back soon as possible.

**Comment by GlennDebecker** [comment]
Hey, is there no information about how the API works with roles?

**Comment by MrGeneration** [comment]
Please don't recycle old issues.
Github is not the right place for technical questions, please consult the community instead: https://community.zammad.org .
