### ISSUE TITLE
From: XXX always "Zammad"

### ISSUE THREAD

**Issue by Trapulo** [zammad/zammad#2410]
### Infos:

* Used Zammad version: 2.7
* Installation method (source, package, ..): RPM
* Operating system: CentOS
* Database + version: unknown
* Elasticsearch version: 5.6.14
* Browser + version: every

### Expected behavior:

* When I send a reply via email to a customer, Zammad may send the email using the sender name defined in email channel options.

### Actual behavior:

* Every email the customer receive contains the header "From: Zammad <support@MYDOMAIN>"

### Steps to reproduce the behavior:

* Send an email to Zammad to start a new ticket, then send a reply from Zammad GUI to the customer.

Yes I'm sure this is a bug and no feature request or a general question. Until some time ago it did work well. I don't know when it started (after I did upgrade to 2.7?) because only some customer started to reporting this asking "Who is Zammad???"

**Comment by MrGeneration** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at the [community board](http://community.zammad.org/) - Closing now.

**Comment by Trapulo** [comment]
this is not an issue? I select to use a sender's name and Zammad always sends as "Zammad"? if this is not an issue...

**Comment by MrGeneration** [comment]
This is working as designed, you can configure it.

![image](https://user-images.githubusercontent.com/6549061/50218474-610c1f80-038c-11e9-871c-08f53d59907e.png)

**Comment by Trapulo** [comment]
Thank you, but I selected "System address display name" (I do not want to share agent's name) and still it sends as "Zammad". Also I changed "Notification Sender" field, and I've defined a sender name in mail channel options.

**Comment by MrGeneration** [comment]
This is still a technical question that you're welcome to ask on our Community-Board.

Locking conversation now, comments on this tracker create a lot of noise to watching people.
