### ISSUE TITLE
Inactive Organization still can select

### ISSUE THREAD

**Issue by sinichi19** [zammad/zammad#2411]
Good Day,

I don't know if this is normal or a bug but I noticed that even you inactive the organization can still select in choices, 

Ex. Is the default Zammad foundation

If this is normal how can I delete organization ? in rails command.

Thank you

**Comment by MrGeneration** [comment]
Hey there,

sorry but this is rather a technical question than a Bug.
For the next time, please always fill in the issue template, as this is very important to our devs to be able to work on issues proberly.

Please note that we do not support deleting organizations at the moment, as you need to ensure that there are no references left to it. The following code in rails c would do what you want, if you don't have any references left:

```
 o=Organization.find(1)
o.destroy
```

While ID1 is Zammad Foundation.

In the meanwhile the inactive flag is a pure visual indicator that carries no restrictions. 
Billy posted a clarification regarding the inactive/active flag in our community: https://community.zammad.org/t/clarification-about-the-active-flag/963

I'm closing this, as this currently works as designed.
If you still feel that this is a bug, please use the issue template to update the needed information.
