### ISSUE TITLE
i-doit version >= 1.12 integration requests fail with 'Can’t fetch objects from...'

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2412]
### Infos:

* Used Zammad version: 2.8
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

**Note** This only affects i-doit Version starting with Version 1.12 (with i-doit API 1.10).

### Expected behavior:

* You can update i-doit settings (on integration page) and add i-doit objects to Zammad Tickets without any trouble.

### Actual behavior:

* When trying to select i-doit objects for a ticket, the user receive error message: `on trying to select i-doit objects in zammad I receive “Can’t fetch objects from http://idoit-hostname/src/jsonrpc.php: #”`

### Steps to reproduce the behavior:

* Try to use the i-doit integration as in adding new objects to a ticket

**Developer Information**
i-doit now checks if the JSON-Content is complete. Zammad does not send the "ID", which is why the response from i-doit is empty (as i-doit sees this as notification).

Sample JSON should look like this:
```
{
“version”: “2.0”,
“method”: “cmdb.object_types”,
“params”: {

    "apikey": "xxx",
    "language": "en"
},
"id": 1
}
```

Further information regarding "ID": https://www.jsonrpc.org/specification#id1

Further information can be found here: https://community.zammad.org/t/i-doit-integration/1809 , this affects several paying customers.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
This is fixed in latest develop and stable. Both releases will be ready in about 30 minutes from now. Closing.

**Comment by mazzorini** [comment]
Same issue with:
Zammad 3.6
idoit 1.15.2
idoit api 1.11.3 (same with an older version ->1.8.1 ).

Could anyone test this please?

**Comment by MrGeneration** [comment]
Can you please not recycle old solved issues that are over 2 years solved?
If this is still an issue, please open a new issue and reference this issue if needed.
