### ISSUE TITLE
"Tab has changed" warning breaks when closing and reopening browser tab

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#2413]
### Infos:

* Used Zammad version: 2.8.x
* Installation method (source, package, ..): docker-compose
* Operating system: Debian 9.6
* Database + version: postgres 9.6.11
* Elasticsearch version: 5.6.12
* Browser + version: Firefox 64

### Expected behavior:

When you close a Zammad tab with open changes, Zammad will prompt "Tab has changed, do you really want to close it?". So far this works fine (and also is an amazing feature!).

I would expect that this also should work when I close and reopen Zammad's _browser tab_. I.e. the following should work as well:

- Create a new ticket, e.g. a received call
- Type something into title/text
- Close Zammad's _browser tab_ (not the ticket tab inside Zammad)
- Reopen Zammad's browser tab by navigating to my.zammad.fqdn
- The new ticket is still there as a Zamamd ticket tab
- Now click on the red X in the Zammad ticket tab
- This _should_ also display the "Tab has changed, do you really want to close it?" message

### Actual behavior:

Zammad will close the tab and lose all open changes. It will not show the  "Tab has changed, do you really want to close it?" message :(

### Steps to reproduce the behavior:

* Create a new ticket
* Close the browser tab
* Reopen the browser tab
* Close the Zammad ticket tab

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martinvonwittich** [comment]
Addendum: this seems to affect only tickets that haven't been created yet (e.g. where you have clicked on the + to create the ticket, but you haven't yet clicked "Create"), and not tickets that already exist properly.

**Comment by martinvonwittich** [comment]
Also reproducible on develop as of 2d5fc012cb98975c0f85bb9f2f8cc07dc35c0077.

**Comment by MrGeneration** [comment]
Could verify this, that one is a meanie!

**Comment by dominikklein** [comment]
I can no longer reproduce the problem in the current version.
