### ISSUE TITLE
Zammad Icon (Bird) on page top left disappears and does not come back

### ISSUE THREAD

**Issue by HPWulff** [zammad/zammad#2419]
### Infos:

* Used Zammad version: 2.8.0-1545327715.c39804ac.sles12
* Installation method (source, package, ..): package
* Operating system: openSuse 42.3
* Database + version: Postgresql 9.6-1.1
* Elasticsearch version: 5.6.5-1
* Browser + version: Firefox 64.0 (32bit)

### Expected behavior:

* show Zammad Bird (also after using search function / leaving search field)

### Actual behavior:

* When entering search field, fields becomes greater (ok) and Zammad Bird disappears to make place, fine.
* When leaving search field, field keeps bigger size and Zammad Bird stays disappeared. Web Page has to be reloaded to show Zammad Bird again.

This behaviour did not happen in Version 2.6 we had before. The "bird" is needed to see new tickets or ticket changes.

### Steps to reproduce the behavior:

* open Zammad (Bird shown)
* enter search field (Field grows, Bird disappears)
* leave search field (Field still greater, Bird does not come back)

Yes I'm sure this is a bug and no feature request or a general question.

Just for your info, there is no need to fix asap.

Kind regards,
Hans Peter Wulff

**Comment by HPWulff** [comment]
supplement: the behaviour shown in the issue happens only, if you enter and leave the search field without writing something into the field, e.g. just click on the search field and then click anywhere else on the screen.
if you write any search item and press <enter>, the icon redisappears, regardless of having found tickets or not.
Regards, Hans Peter
BTW: Happy New Year for the Zammad team!

**Comment by MrGeneration** [comment]
Thanks for your post, I could verify this behaviour.
This can be "work arounded" with typing at least one letter and then pressing "X" to let the birdy come back.

Seems like the field does not notice it's loosing the focus.

![birdy-bug](https://user-images.githubusercontent.com/6549061/50521382-c2876900-0ac5-11e9-8a8e-2f507bd04a80.gif)

**Comment by mrflix** [comment]
@martini I think this is a regression caused by  https://github.com/zammad/zammad/commit/23059d7c90c3497dfc215b84f961e080d3c92b63#diff-cb2d45492ca3571e39e38a767a3864b3L19
