### ISSUE TITLE
Keine weiteren Agents/Besitzer verfügbar

### ISSUE THREAD

**Issue by Wajackbe** [zammad/zammad#242]
Hallo,
ich habe eine frische Installation unter CentOs 7. Alles funktioniert soweit. Habe zwei neue Agents als Benutzer eingerichtet. Leider stehen die Agents nicht als Besitzer für Tickets zur Auswahl. Was mach ich falsch? Aktuell kann nur der Admin ausgewählt werden. Aber auch weitere Admins stehen nicht zur Auswahl. Gibt es hier Einschränkungen?
Viele Grüße
Patrick

**Comment by thorsteneckel** [comment]
Hallo Patrick,

eine Einschränkung erfolgt durch die Gruppe der das Ticket zugewiesen ist und der Zuweisung der Agenten dieser. Sind die Agenten in der Gruppe des Tickets? Wenn ja, handelt es sich hier um einen Verhalten, dass so nicht sein soll. Dann wären die Log-Dateien aus dem log/-Verzeichnis sehr hilfreich.
Viele Grüße,
  Thorsten

**Comment by Wajackbe** [comment]
Hallo Thorsten,

es gibt wohl ein Problem mit nur einer Gruppe. Ist nur eine Gruppe im System vorhanden, gehören weitere Agents zu keiner Gruppe, da bei den Benutzerinformationen keine Gruppe ausgewählt werden kann.
Wird eine zweite Gruppe definiert, kann die Gruppe auch in den Benutzerinformationen ausgewählt werden. Bei neuen Tickets kann somit die Gruppe und der Besitzer (jetzt vollständige Liste) ausgewählt werden. Alte Tickets können weiterhin keinen anderen Agents zugewiesen werden. Aber die Gruppenauswahl steht zur Verfügung. Ein Wechsel der Gruppen hilft nicht. Liste der Besitzer bleibt unverändert.
Damit kann ich leben. Verwirrt nur etwas...
Viele Grüße
Patrick

**Comment by hanneshal** [comment]
closed due inactivity
