### ISSUE TITLE
Unavailable ticket template attributes get applied

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#2424]
### Infos:

Used Zammad version: 2.8.x
Installation method (source, package, ..): any
Operating system: any
Database + version: any
Elasticsearch version: any
Browser + version: any

### Expected behavior:

* After using a Ticket Template only available attributes are pre-filled

### Actual behavior:

* After using a Ticket Template unavailable attributes are pre-filled

### Steps to reproduce the behavior:

* Create 2 Agents
* Create 1 Group
* Assign permissions to created Group to Agent 1
* Create Ticket Template with Agent 1 that contains the created Group
* Use created Ticket Template with Agent 2
* See that the (unavailable) Group is selected

Yes I'm sure this is a bug and no feature request or a general question.

### Information that help:

The template gets loaded and applied in this area:
https://github.com/zammad/zammad/blob/caa5c962605b80a8f8116c5b8386f871c711ae0a/app/assets/javascripts/app/controllers/widget/template.coffee#L79-L80
This part should be extended to limit/filter the attributes.

The available attributes can be found in the [`formMeta.dependencies` object/hash](https://github.com/zammad/zammad/blob/caa5c962605b80a8f8116c5b8386f871c711ae0a/app/assets/javascripts/app/controllers/ticket_zoom/form_hander_dependencies.coffee#L7) - which can can get fetched like this:
https://github.com/zammad/zammad/blob/caa5c962605b80a8f8116c5b8386f871c711ae0a/app/assets/javascripts/app/controllers/agent_ticket_create.coffee#L47-L51

The logic to filter attributes is currently "trapped" in [this file/class](https://github.com/zammad/zammad/blob/caa5c962605b80a8f8116c5b8386f871c711ae0a/app/assets/javascripts/app/controllers/ticket_zoom/form_hander_dependencies.coffee#L7). The logic should get extracted to make it reuseable and then used in the "template apply" code.

This affects Ticket#1031263.

**Comment by SummerStorm** [comment]
Unfortunately the the browser test for this issue cannot be cleanly cherry-picked into `stable`, so that leaves one customer on `stable` who is still being affected. We've offered the bump the customer's hosted instance to `develop` as a temporary measure until the next release.
