### ISSUE TITLE
Attached msg-Files break filenames in Zammad (combination Exchange and Outlook)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2425]
### Infos:

* Used Zammad version: 2.8 & develop
* Installation method (source, package, ..): rpm & Source
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Outlook-Versions being affected for sure: Outlook 2013 & 2016 connected with Exchange
* Ticket-ID: #1034168, #1077162

### Expected behavior:

* When forwarding Mails with attachments to Zammad, Zammad will import the attachment exact like the original been send. Meaning, it will keep file extension and file name, if applicable.

### Actual behavior:

* In some special cases (Outlook + Exchange), the Mail with MSG-Attachment will contain a unique-ID (Content-ID). This causes Zammad to show the Content-ID instead of the file-name and without file extension.

### Steps to reproduce the behavior:

* Create a E-Mail with an attached .eml file
* Add a line with `Content-ID: <ee5c8a7d38e67f4f90504618004c3d9f@some.tld>` within the Part where the message attachment is referenced
* Import this file into Zammad

For reference, here's what the attachment part needs to look like:
```
------=_NextPart_000_0067_01D4A43B.1C2130F0
Content-Type: message/rfc822
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment
Content-ID: <ee5c8a7d38e67f4f90504618004c3d9f@some.tld>

Received: from mx2.zammad.com
	by mx2.zammad.com with LMTP
	id yOHIAN1gL1y4UwAAABwAvw
	(envelope-from <alias@some.tld>)
	for <mh@zammad.com>; Fri, 04 Jan 2019 13:34:21 +0000
Received: from mikasa.some.tld (mikasa.some.tld [x.x.x.x])
	by mx2.zammad.com (Postfix) with ESMTPS id B89E9A02C6
	for <mh@zammad.com>; Fri,  4 Jan 2019 13:34:20 +0000 (UTC)
Received: from EHLO mikasa.some.tld (mikasa.some.tld [x.x.x.x])
	by mikasa.some.tld with ESMTPSA
	(version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128)
	; Fri, 4 Jan 2019 14:34:17 +0100
From: "Marcel Herrguth" <alias@some.tld>
To: <alias@another.tld>
Subject: Test Attachment Text
Date: Fri, 4 Jan 2019 14:34:17 +0100
Organization: The home of Anime
Message-ID: <ee5c8a7d38e67f4f90504618004c3d9f@some.tld>
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="----=_NextPart_000_005E_01D4A43B.1C1DD590"
X-Mailer: Microsoft Outlook 16.0
Thread-Index: AQFpQ8vnu4DrfNDtB+p/XwBv/6/XNg==

This is a multipart message in MIME format.

------=_NextPart_000_005E_01D4A43B.1C1DD590
Content-Type: text/plain;
	boundary="=_d1b5b47c2bb88af990b40cf2152b3d67";
	charset="us-ascii"
Content-Transfer-Encoding: 7bit

  680gh4r6s8t
04 h
640trs
684 h06
8rs4t0
640



-- 
```

Look in Zammad:
![image](https://user-images.githubusercontent.com/6549061/50692927-c5d6a380-1035-11e9-93d5-1d02902c9549.png) 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
The mail example as attachment would be fine. I can't follow. Thanks!

**Comment by MrGeneration** [comment]
Ah sorry! Lost track of this issue, this only seems to happen when you're using exchange, see the attached file, please.

This only happens to one of 3 attachments (that's the MSG-File)

[WG Test Attachment HTML.zip](https://github.com/zammad/zammad/files/2796072/WG.Test.Attachment.HTML.zip)

**Comment by thorsteneckel** [comment]
Fixed with the two commits above.
