### ISSUE TITLE
Set focus into Answer textarea when opening a ticket

### ISSUE THREAD

**Issue by pinscher** [zammad/zammad#2427]
### Expected behavior:

* When opening a ticket, immiditly focus the curser into the answer textarea.

### Actual behavior:

* now you have to take your mouse and click into the textarea or press a shortcut. 

### Steps to reproduce the behavior:

* open an existing ticket and try creat a new answer

**Comment by MrGeneration** [comment]
Thank you very much for your time to create this issue.

Please post this over at our community, as this is not a bug, but a feature request: https://community.zammad.org

Best regards

Closing now

(Edited to suite our internal guidelines better)
