### ISSUE TITLE
Note is not being updated because of the lack of lastname

### ISSUE THREAD

**Issue by HLFH** [zammad/zammad#2429]
Hi,

### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): source
* Operating system: ArchLinux
* Database + version: mysql  Ver 15.1 Distrib 10.3.9-MariaDB, for Linux (x86_64) using readline 5.1
* Elasticsearch version: Version: 5.6.9, Build: 877a590/2018-04-12T16:25:14.838Z, JVM: 1.8.0_192
* Browser + version: Version 71.0.3578.98 (Official build) (64 bits)

### Expected behavior:

When you update the note of the ticket on the right, you should expect the note to be actually updated.

### Actual behavior:

The note is kept empty and is not updated because the last name of the client related to the ticket is required. And a lot of clients that are sending emails do not have last names on their email address. It would be good to have "-" by default for lastname or to give an option to make lastname an optional field.

### Steps to reproduce the behavior:

* Send an email with an email that is not *firstname.lastname@example.com* to Zammad
* Zammad creates the client often with a firstname field but keeps the lastname field empty
* The Zammad operator reads a ticket and updates the note on the right
* The note is not updated because the last name is required. Validation has failed with the app model

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by sparanoid** [comment]
I can confirm this issue, nowadays many users (clients) start a ticket with their emails, and the name fields are likely using their nicknames not the real names, or they're asian not following the First_name Last_name pattern.

**Comment by MrGeneration** [comment]
I have to discuss this tomorrow in a meeting, as this is a required field (inside the WebApp) this behavior is actually correct.

Funfact: You can actually workaround this via API - as this is not consistent I'll get back to you guys asap.

**Comment by HLFH** [comment]
@MrGeneration Hi. Has your team taken a decision in the meeting?

**Comment by MrGeneration** [comment]
Oh yeah, sorry about that!

We decided that we should make one of the following three fields being a minimum to be required - this means it might be a combination or stand alone field being filled in:

* firstname
* lastname
* mail address

We also decided that the API should also restrict those things just like the UI does. This will make the usuage way more consistent.

**Comment by mantas** [comment]
@thorsteneckel Marcel's proposal is already implemented in API. The core issue is solved too, it allows to edit customer's note. However, it does not allow to edit such customer's note in single user edit form. That form still requires both first name and last name on frontend. Instead of either first name or last name or email or phone.

Same applies to new customer form triggered from via `+ Create new Customer` in ticket creation.

Is current UI behavior by design or a leftover?

![Screenshot 2021-10-11 at 15 08 26](https://user-images.githubusercontent.com/36944/136787545-7e7f7b2c-8d3c-4625-880e-4e57011380dd.png)
