### ISSUE TITLE
Locking the conversation for now, as this issue hasn't received any usefull comments in the past, but just +1s.

### ISSUE THREAD

**Issue by Memphizzz** [zammad/zammad#2432]
Locking the conversation for now, as this issue hasn't received any usefull comments in the past, but just +1s.

_Originally posted by @MrGeneration in https://github.com/zammad/zammad/issues/574#issuecomment-454105312_

3 tries to bump this issue with a +1 aren't "usefull commments"? How else should we express our support for this feature?

**Comment by monotek** [comment]
With a support contract?

**Comment by MrGeneration** [comment]
Please read the issue template.
You're causing noise with any bumps to about 1400 people watching this project.

This isn't helping anybody and just creates distraction.

The best way to show your need for the feature (beside of paying a feature or service contract) is simply to put a thumb up to the original post. If you want to discuss this, let's please move this from github.

**Comment by Memphizzz** [comment]
@monotek Not everyone is a paying enterprise customer, besides, the Issue is about a bug in the API, why would I need a support contract to report a bug?

**Comment by monotek** [comment]
Not for reporting, but for getting it priorized...

**Comment by MrGeneration** [comment]
I think what @monotek means is, that the service contracts are paying our developers and support team.
It's simple: The more we're being paid, the more developer we can pay to bring Zammad forward.

Because of team size, some features are currently waiting even though the user base really wants and needs them. :)
