### ISSUE TITLE
Ticket templates resets article body (even if it's empty within the template)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2434]
### Infos:

* Used Zammad version: 2.8
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1035639

### Expected behavior:

* When working with templates that do not contain an article body, Zammad will keep the article body that has been typed before applying the template.

### Actual behavior:

* When working with templates that do not contain an article body (empty), Zammad will override any beforehand typed text within article body when applying the template.

**Note**
The same happens to any other field like customer, tags. This should also apply to custom fields (even if they haven't been filled out thus being "empty".

This works a bit unexpected, as you might fill in information before applying the template (for whatever reason).

### Steps to reproduce the behavior:

* Open the new ticket dialogue
* fill in some fields (leave article body empty)
* save the screen as a new template
* open a new ticket dialogue
* type text into the article body
* apply the just created ticket template

![ticket-template-nukes-body](https://user-images.githubusercontent.com/6549061/51269150-003f2980-19c2-11e9-8f48-5e83b51fc209.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by wucherpfennig** [comment]
Just one note from our side: our staff complained since this behaviour makes it really hard to use the cti integration...

**Comment by mantas** [comment]
@MrGeneration what would be expected behaviour for non-blank title or pre-selected customer?

**Comment by MrGeneration** [comment]
Personally I'd expect the templates that I apply to overwrite pre-filled fields that are set in the template.

**Comment by wucherpfennig** [comment]
That was our assumption too. actually it overwrites all fields...

**Comment by mantas** [comment]
What would you guys expect in following cases:

- Attachments. Currently attachments are not saved as part of template at all. But resets existing attachments on apply. IMO it's OK to not save attachments, but they shouldn't be reset.



- Tags. If template does have tags, should it append or override pre-filled tags?

**Comment by wucherpfennig** [comment]
For me a practical solution for this issue would be that you would be able to select "override existing form values if template is applied" when you save the template.
Personally I would not apply field specific rules about overriding or keeping entries since it will confuse users.

**Comment by MrGeneration** [comment]
* Templates currently don't allow file uploads, this is handled by this issue: 
    https://github.com/zammad/zammad/issues/2175
    
    As there's nothing set at that moment, if you find an attachment, it should stay at the article.

* If tags are present, add them - overwriting is not needed if they're already set


@wucherpfennig especially for priorities mantas is absolutely right asking for that usecase. Reason: This field always has a value.

**Comment by dominikklein** [comment]
After a discussion inside the product team we have the following idea for the fix:

- All fields (e.g. body or also custom fields) which are not present in the template should not be overridden after the selection.
- If tags are present, they should be added without deleting existing ones.
- For the situation that a "wrong" template was selected that prefilled already some fields the filled fields from the selected template should be remembered. When afterward another template will be selected the fields which were not changed from the template and also not changed manually in the meanwhile, should be cleared/resetted again.
