### ISSUE TITLE
Documentation for packages

### ISSUE THREAD

**Issue by cice** [zammad/zammad#244]
Is there any (yet)? If so, where can i find it, or can someone point me to the proper code parts to figure it out myself?

Is it possible to create new channel types / drivers using packages?

**Comment by thorsteneckel** [comment]
HI @cice - currently there is none. However, we are planning to go in this direction soon. Packages are managed via the admin package interface, development can get tested via https://github.com/zammad/zammad/blob/develop/app/models/package.rb#L156 and the zspm package for handling szpm files comes as soon as possible. I'll post the link here when the sync is done.

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes

**Comment by thorsteneckel** [comment]
As a reference: [I answered the same question in the community](https://community.zammad.org/t/examples-of-zpm-files/2881/3).
