### ISSUE TITLE
Zammad ignores disabled Chat-Topics for agents

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2441]
### Infos:

* Used Zammad version: 2.8
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any 
* Elasticsearch version: any
* Browser + version: any
* TIcket-ID: #1042192

### Expected behavior:

* When disabling a chat topic within Chat -> Settings, Zammad will not notify the agent about chat topics that don't belong to his selection.

### Actual behavior:

* When disabling a chat topic within Chat -> Settings, Zammad does not verify if the agent enabled this Chat-Topic. Instead, it will make a noise and notify the agent, the agent can take the Chat -even if it's not his Chat-Topic- while displaying the correct Chat-Topic message.

![image](https://user-images.githubusercontent.com/6549061/51480318-0b62d280-1d91-11e9-844b-a87b2d094fdf.png)
*disabling e.g. english topic will still serve english chat topics*

### Steps to reproduce the behavior:
 
* Configure two chat topics e.g. "en" and "de"
* create two testpages (local html is enough), each with the with the other chat topic (one for de, one for en)
* enable chat option
* leave the admin settings, click on chat, enable the chat and go to Settings
* disable one of the chat topic and use the disabled chat topic and try chatting with your agent
* it will work

Screencast:
![chat-topic-is-being-ignored](https://user-images.githubusercontent.com/6549061/51481348-f471af80-1d93-11e9-9219-088c09b10fd4.gif)

This has been found by our Community: https://community.zammad.org/t/chat-notifications/1934

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by streamgamelabels** [comment]
Any news on this issue? It's been 8 months and we're now at version 3.1.

**Comment by MrGeneration** [comment]
I'm locking this conversation as there was no new input.
Please refrain from asking back "when something comes" - it's coming when it's ready!

We'll update issues accordingly if we have an ETA for this.
Right now we're working hard on fixing all sorts of issues, sorry that this is not our highest priority at this moment.

**Comment by thorsteneckel** [comment]
Fixed with https://github.com/zammad/zammad/commit/8a5552c9f8a5da2ab38c819923d461dfba25e938
