### ISSUE TITLE
Add option to disable "subject-recognition"

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2445]
### Infos:

* Used Zammad version: 2.8
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-IDs: #1035758, #1039430 

### Expected behavior:

* When disabling all references of a Zammad system (plus Ticket-Number in subject), Zammad will create a new ticket, as it is not able to find a matching ticket.

### Actual behavior:

* When disabling all references of a Zammad system (plus Ticket-Number in subject), Zammad will try to find tickets that have matching subjects.

**Note** This normally will only affect you if you're splitting tickets (for better overview) and as you write with another Zammad-System.

**Further note** The idea behind this function is and was, that a user sending a message to Zammad with other people in CC, that those people can simply answer on the mail (so replying to Zammad e.g. in CC) so that Zammad can recognize the mail. This is meant to reduce duplicate tickets and the need to merge the same threads into one bigger one.

### Steps to reproduce the behavior:

* Have two Zammad systems
* Send an E-Mail from Zammad A to Zammad B
* Split the new ticket in Zammad B into 2 and ensure that the splitted ticket does not contain the ticket number
* answer to both tickets by E-Mail
* take a look into Zammad A - both E-Mails will come into the original ticket you send to Zammad B

This is partially goes along with issue #2444 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
@MrGeneration I think this issue got solved today (I did not see this issue before) https://github.com/zammad/zammad/issues/5286

Could you verify if https://github.com/zammad/zammad/issues/5286 also fixes this issue here? From my point of view, it does.

**Comment by MrGeneration** [comment]
Sorry for the delay.
This enhancement issue is about disabling the subject recognition. However, the setting description is rather unclear to me. What are those default settings this option is talking about. If this is the option to retain the default behavior if I send several messages to update one ticket (which automatically gets merged), then it should be active by default, not off.

![image](https://github.com/user-attachments/assets/544ec187-0389-4f2b-a3ee-2b74fb8cf45f)

**Comment by MrGeneration** [comment]
https://github.com/zammad/zammad/issues/5286 has solved this topic to my understanding. Thank you!
