### ISSUE TITLE
Translation Error or Typo

### ISSUE THREAD

**Issue by Dirk23** [zammad/zammad#2446]
### Infos:

* Used Zammad version: 2.8.x
* Installation method (source, package, ..): APT
* Operating system: Ubuntu 18.04 LTS
* Database + version: Dunno
* Elasticsearch version: Dunno
* Browser + version: Chrome 71...something, latest as i let Chrome update himself

### Expected behavior:

* Textfield is translated correct to German

### Actual behavior:

* Textfield has a little typo

Yes I'm sure this is a bug and no feature request or a general question.
![zammad textbug](https://user-images.githubusercontent.com/4200682/51661280-b00f2b00-1fb0-11e9-9350-428a29417adf.PNG)

**Comment by MrGeneration** [comment]
Thanks for your contribution!
I just updated the translation to the corrected version.
![image](https://user-images.githubusercontent.com/6549061/51745818-5f78fa00-20a4-11e9-87bb-d0153a74d1fe.png)


This will be available within the next Update (2.9) or by a friendly "Letzte Übersetzung laden" (this might take a while)
![image](https://user-images.githubusercontent.com/6549061/51745855-7b7c9b80-20a4-11e9-8bb4-066c35a89dcd.png)
