### ISSUE TITLE
No tag in conditions for new Overviews, Triggers, Schedulers and SLAs

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#245]
There is no tag attribute in the conditions for a new Overview. Did you forget it or is there explanation for this?

**Comment by martini** [comment]
It's just missing.

**Comment by Julian0o** [comment]
It's also missing in the triggers area.

**Comment by martini** [comment]
Yes. It's the same dialog/code here. :)

**Comment by rolfschmidt** [comment]
Hi,
the enchancement got implemented for develop branch. It will be released with the next stable release.

![zammad_trigger_tags](https://cloud.githubusercontent.com/assets/5445062/24961266/8eaf5526-1f98-11e7-8815-0ecb15729738.png)

The new option is also available in Overviews, Triggers, Schedulers and SLAs.

Operators are contains all, contains all not, contains one, contains one not.

Best regards,
Rolf
