### ISSUE TITLE
Assign Follow ups has no affect

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2455]
### Infos:

* Used Zammad version: 2.8
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1087633 

### Expected behavior:

* When setting a group to "assign follow ups" => NO, Zammad will unassign the owner, if the ticket gets reopened by the customer.

### Actual behavior:

* When setting a group to "assign follow ups" => NO, Zammad will just open the ticket again.

### Steps to reproduce the behavior:

* Set a group to "assign follow ups" => no
* have some nice mail conversation with your customer and at some point close the ticket
* reply to the ticket as customer to reopen the ticket
  * state will change, owner will not

This bug was found by a community member: https://community.zammad.org/t/what-does-assign-follow-ups-do/2010

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by splattner** [comment]
I see the same behavior with our installation.

**Comment by MrGeneration** [comment]
I'm locking the conversation of this issue to contributors only to reduce noise on this repository.
This issue hasn't had any usefull updates in the last months. 

(No offense, me toos don't help :) )

We'll update this issue accordingly, as soon as anything moves. 💪
