### ISSUE TITLE
Ticket Lock missing

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#246]
When you get a new notification for a new ticket. More than one agents can answer the same time with no notice of each other.

**Comment by thorsteneckel** [comment]
Hi @Julian0o - currently the way to manage this is to set the owner first and then handle the ticket. Since we have super awesome direct websocket connections the change will get spread to all other agents including the one that have the ticket opened, too.

**Comment by Julian0o** [comment]
okay i will test this. Maybe one idea is to assign the owner when someone starts typing a new note or mail.

**Comment by Julian0o** [comment]
@thorsteneckel i tried that. the owner gets pushed immediately to the other agents. but other agents than the owner can do everything with the ticket... So there is no "lock" at all, you have to look if there is a owner and trust on human intelligence :D

**Comment by petervanbeugen** [comment]
I agree that the possibility to lock tickets (system wide on/off/auto setting?) is essential. In higher ticket /agent volume environments this becomes a nightmare. I'm a heavy OTRS user and have a (Znuny developed) package to be able to auto-lock a ticket as soon as it is opened by an agent. This would be nice in Zammad as well.... A temporary workaround in Zammad could be to add a field in the Overwiews where you can see if a ticket is in use by an agent. 
I like the idea and cane imagine use cases to work with more than one agent on a ticket, but then it should be possible to invite another agent to the ticket.

**Comment by raphaelm** [comment]
This is really important to us, would be great to see a change here!

**Comment by ThePatzen** [comment]
This is also important to us! Would be great to have such a function!

**Comment by hanneshal** [comment]
moved to
https://community.zammad.org/t/ticket-lock-missing/38

Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

regards
Johannes
