### ISSUE TITLE
Zammad reuses password hash salts

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#2462]
### Infos:

* Used Zammad version: 2.8.x
* Installation method (source, package, ..): docker-compose
* Operating system: Debian 9
* Database + version: `PostgreSQL 9.6.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.4.0) 6.4.0, 64-bit`
* Elasticsearch version: 5.6.14
* Browser + version: Chromium 71

### Background

I noticed that the users in my DB that have been created by the email parser have:

a) password hashes of an empty string (which IMO they shouldn't, they should have `NULL` instead of a hash) and
b) lots of users have the _same_ password hash, which shouldn't happen due to salting:

```
zammad_production=# select count(*) from users group by password order by count(*) desc limit 5;
 count
-------
 10014
  4805
  1912
   704
     4
(5 Zeilen)
```

With the Rails console I was able to verify that the hashes are actually of the empty string:

```
zammad ~ # docker exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" -ti zammaddockercompose_zammad-railsserver_1 bash
root@7e0d3a1dba11:/opt/zammad# rails c
I, [2019-02-02T23:35:07.457931 #4191-47145821884240]  INFO -- : Setting.set('product_logo', "1a49a80da9c6e174c9537709642498d1.png")
Loading production environment (Rails 5.1.6.1)
irb(main):001:0> PasswordHash.verified?("$argon2i$v=19$m=65536,t=2,p=1$jZG4d36BZZQ/ya0r0weBZw$FztleWSa6YTq1MSbi0AmmQxf8qBllUszVXi8UgMlQvk", "")
=> true
irb(main):002:0>
```

The reused salts are probably caused by `lib/password_hash.rb` because it reuses the same instance of the Argon2 library, which the [documentation](https://github.com/technion/ruby-argon2#usage) says you shouldn't do:

> If you follow this pattern, it is important to create a new Argon2::Password every time you generate a hash, in order to ensure a unique salt.

This wouldn't be that big of a problem if it only affected the automatically created users who have no password anyway, but unfortunately it also affects manually created users with real passwords.

### Expected behavior:

* When creating multiple users with the same password, they should have different salts and therefore different password hashes.
* Automatically created users with empty passwords IMO shouldn't have any password hashes at all, but instead simply `NULL`. Storing password hashes for empty passwords just makes it harder to identify which hashes resemble proper passwords, and which don't.

### Actual behavior:

* Creating multiple users (e.g. "User A" and "User B") with the same password leads to users with identical password hashes:

```
zammad_production=# select firstname,lastname,password from users where firstname = 'User' and lastname IN ('A', 'B');
 firstname | lastname |                                             password
-----------+----------+--------------------------------------------------------------------------------------------------
 User      | A        | $argon2i$v=19$m=65536,t=2,p=1$VJK50mnb/QiTsGEb3fbb4w$zhTUC0H/m8J142EGaB/vva96U2YUs4s+uzrmkunBW+A
 User      | B        | $argon2i$v=19$m=65536,t=2,p=1$VJK50mnb/QiTsGEb3fbb4w$zhTUC0H/m8J142EGaB/vva96U2YUs4s+uzrmkunBW+A
(2 Zeilen)
```

* Automatically created users with empty passwords have password hashes.

### Steps to reproduce the behavior:

* Manually create multiple users in Admin -> Users with the same passwords and compare their password hashes.
* Manually create multiple users without setting their passwords and see that they have password hashes which match `PasswordHash.verified?("hash...", "")`.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martinvonwittich** [comment]
To properly fix this, all passwords should be re-hashed to ensure that they have a unique salt. I would suggest to use this opportunity to upgrade to `ruby-argon2` and `argon2id` [which is recommended now anyway](https://crypto.stackexchange.com/questions/48935/why-use-argon2i-or-argon2d-if-argon2id-exists). Then `PasswordHash.legacy?` could consider `argon2i` hashes to be legacy hashes, and rehash the passwords with `argon2id`.

**Comment by MrGeneration** [comment]
I'll give this to Thorsten to take a look on this, I think he's the best guy in that topic! 🚀

**Comment by martinvonwittich** [comment]
I've already started working on it, if I get it right, I'll submit my first merge request :)

**Comment by thorsteneckel** [comment]
Closed via https://github.com/zammad/zammad/commit/1e54645223c0a5d71e910d82a4d7be8cc475f1a4
