### ISSUE TITLE
Add information "Ticket merged" to History

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2469]
### Infos:

* Used Zammad version: 2.8
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Current behavior:

When merging a ticket into another, the destination ticket will only provide a link to the merged ticket. The history does not tell you that a ticket has been merged (merged articles appear kind of "out of nowhere" if youlook into the history).

![image](https://user-images.githubusercontent.com/6549061/52480978-827bd180-2bad-11e9-89e1-d79e70c0b07f.png)

### Desired functionality:

Zammad should put a information into the History "Ticket xyz has been merged" to the destination ticket. The ticket should be updated (updated_at) as a change has been made to the ticket.

This partly plays into #2467 as we also want to be able to Trigger that moment (e.g. being able reopening a closed ticket that received a merge).

![image](https://user-images.githubusercontent.com/6549061/52481461-e5ba3380-2bae-11e9-851d-7b75e3622202.png)

### Desired behavior with the new functionality:

* having two tickets (ticket A and ticket B)
* you merge Ticket B into Ticket A
* when checking the history of Ticket A, Zammad will tell you that an agent has merged Ticket B (Ticketnumber) into this ticket (timestamp of this is the moment of merge)

This will enable agents to understand what actually happened to the ticket. No articles will appear "out of nowhere" any more, one step further to full revision.

This issue affects internal tickets #1037697 and #1024937.

**Comment by SummerStorm** [comment]
New feature added via 6d7480a.
