### ISSUE TITLE
telephone ticket without email

### ISSUE THREAD

**Issue by singular-error** [zammad/zammad#247]
When creating a new telephone ticket you often have just a telephone numer and no email-address. Email address is often added later, when the customer send's it first mail, but in the meanwhile you cannot create a ticket and discuss it internally.?
Email-addresses via telephone are often wrong spelled :/ so they are potentially unusable.
Could'nt the telephone number used as unique user-id, too?

**Comment by Frankstar** [comment]
interresting idea - i think you can still use an email adress but its still an interessing idea

**Comment by singular-error** [comment]
Also, i think that it should be possible to have one or more unique customer contacts ids: like like threema-id, what's up number, twitter username and so on.
The decade of _only_ email-contact is going to it's end, isn't it?
Please tag it as feature request :) thanks

**Comment by monotek** [comment]
This proposel could help: https://github.com/zammad/zammad/issues/562

**Comment by martini** [comment]
No it's possible to create customers without email address (at least firstname, lastname, email or phone need to be there).

It's available in current develop.
