### ISSUE TITLE
It cant be installed on Debian Buster

### ISSUE THREAD

**Issue by gerroon** [zammad/zammad#2470]
Hi

It seems like the current debs from Debian 9 is not installable on Buster.

See the apt log below

```The following information may help to resolve the situation:

The following packages have unmet dependencies:
 zammad : Depends: libevent-core-2.0-5 but it is not installable
          Depends: libevent-extra-2.0-5 but it is not installable
E: Unable to correct problems, you have held broken packages.```

**Comment by MrGeneration** [comment]
Please note that we currently do not support Debian 10. 

Please note that this is not a bug, but a problem with your OS. For technical questions please use our community: https://community.zammad.org/

Closing now.
