### ISSUE TITLE
Chat can't be closed after timeout

### ISSUE THREAD

**Issue by erikaTEI** [zammad/zammad#2471]
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): Docker
* Operating system:Debian GNU/Linux 9
* Browser + version: Chrome

### Expected behavior:

* close the chat using the 'x' in the upper right corner when the session timeout.

### Actual behavior:

* the chat widget remains open.
Console message with debug mode:
chat debug || can't close widget without sessionId
chat debug || widget already open, block

![screen shot 2019-02-12 at 9 52 29 am](https://user-images.githubusercontent.com/47568567/52648610-6e391c80-2eac-11e9-9db0-6d69f6505dcc.png)
 

### Steps to reproduce the behavior:

* open a chat session.
   wait for the timeout.
   the widget can't be closed.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
In my case I did not see any console errors, but however, I cannot close it.
