### ISSUE TITLE
Failed to run scheduled job 'Generate user based stats.'

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#2474]
### Infos:

* Used Zammad version: 2.9.0
* Installation method (source, package, ..): RPM
* Operating system: CentOs 7.6.1810
* Database + version: PostgreSQL 9.6.11
* Elasticsearch version: 5.6.14
* Browser + version: Chrome 71.0.35

### Expected behavior:

Monitoring URL reporting no issues

### Actual behavior:
Monitoring URL reporting: 

**Failed to run scheduled job 'Generate user based stats.'. Cause: Failed to run Stats.generate after 10 tries #<RuntimeError: No settings with area 'Dashboard::Stats' defined>**

### Steps to reproduce the behavior:
Upgrade from 2.8.0 to 2.9.0 with RPM zammad-2.8.0-1546615161.69afbcaf.centos7.x86_64 from repo.
After a while scheduler will report this error in monitoring url

Same can be reproduced with:

```
zammad run rails c
Loading production environment (Rails 5.1.6.1)
irb(main):001:0> Stats.generate
RuntimeError: No settings with area 'Dashboard::Stats' defined
        from lib/stats.rb:31:in `block in generate'
        from lib/stats.rb:22:in `generate'
        from (irb):1

```

Relevant snippet from produciton.log

> > E, [2019-02-14T15:47:26.320550 #7355-70238256529120] ERROR -- : execute Stats.generate (try_count 0) exited with error #<RuntimeError: No settings with area 'Dashboard::Stats' defined>
> E, [2019-02-14T15:47:27.349458 #7355-70238256529120] ERROR -- : execute Stats.generate (try_count 1) exited with error #<RuntimeError: No settings with area 'Dashboard::Stats' defined>
> E, [2019-02-14T15:47:29.379824 #7355-70238256529120] ERROR -- : execute Stats.generate (try_count 2) exited with error #<RuntimeError: No settings with area 'Dashboard::Stats' defined>
> E, [2019-02-14T15:47:32.405092 #7355-70238256529120] ERROR -- : execute Stats.generate (try_count 3) exited with error #<RuntimeError: No settings with area 'Dashboard::Stats' defined>
> E, [2019-02-14T15:47:36.432196 #7355-70238256529120] ERROR -- : execute Stats.generate (try_count 4) exited with error #<RuntimeError: No settings with area 'Dashboard::Stats' defined>
> E, [2019-02-14T15:47:41.457603 #7355-70238256529120] ERROR -- : execute Stats.generate (try_count 5) exited with error #<RuntimeError: No settings with area 'Dashboard::Stats' defined>
> E, [2019-02-14T15:47:47.490119 #7355-70238256529120] ERROR -- : execute Stats.generate (try_count 6) exited with error #<RuntimeError: No settings with area 'Dashboard::Stats' defined>
> E, [2019-02-14T15:47:54.649326 #7355-70238256529120] ERROR -- : execute Stats.generate (try_count 7) exited with error #<RuntimeError: No settings with area 'Dashboard::Stats' defined>
> E, [2019-02-14T15:48:02.676962 #7355-70238256529120] ERROR -- : execute Stats.generate (try_count 8) exited with error #<RuntimeError: No settings with area 'Dashboard::Stats' defined>
> E, [2019-02-14T15:48:11.712731 #7355-70238256529120] ERROR -- : execute Stats.generate (try_count 9) exited with error #<RuntimeError: No settings with area 'Dashboard::Stats' defined>
> E, [2019-02-14T15:48:11.725932 #7355-70238256529120] ERROR -- : Failed to run Stats.generate after 10 tries #<RuntimeError: No settings with area 'Dashboard::Stats' defined>

0 log line entries in scheduler_{err,out}.log 

Reviewing upgrade log:

`
Updating   : zammad-2.9.0-1550130576.fe1640fd.centos7.x86_64                                                            185/473                                                                                                           
chown: cannot access ‘/opt/zammad/tmp/cache_file_store_production/506’: No such file or directory                                                                                                                                             
warning: %post(zammad-2.9.0-1550130576.fe1640fd.centos7.x86_64) scriptlet failed, exit status 1                                                                                                                                               
Non-fatal POSTIN scriptlet failure in rpm package zammad-2.9.0-1550130576.fe1640fd.centos7.x86_64   
` 

Maybe db:migrate was skipped during upgrade? What would be the correct procedure doing that?

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @modulec 

it seems that your upgrade is not completed. Try the  following:

1) `zammad run rake db:migrate`
2) `zammad run rails r 'Scheduler.update_all(active: true)'`
3) restart zammad

> Maybe db:migrate was skipped during upgrade? What would be the correct procedure doing that?

Yes. It seems that you did not stop Zammad before starting the upgrade, can that be?

 -Martin

**Comment by ghost** [comment]
Indeed you are correct. After further analysis it seems that zammad was running while the package from repo was updated.

Running the mentioned commands resolved the issue.

Thank you.

**Comment by martini** [comment]
Thanks for feedback! @modulec

**Comment by ghost** [comment]
NP, tnx for quick help with this @martini. However while discussing this internally with colleagues maybe this still should be classified as a bug.

While indeed the zammad service was not stopped during upgrade procedure, and the proces is documenting that you should. It would be also very nice to incorporate and enforce this in the package itself.

In RPMs this can be done by using %pre block or %postun
on packager.io [before_install](http://doc.packager.io/documentation/customizing-the-build/#before_install) can be used for same effect.

Automatically stopping zammad before upgrading package will surely prevent others encountering this issue, and enable automatic updates.

As far as I remember doing manual upgrades, package install will start it back up after it's done.

**Comment by thorsteneckel** [comment]
@monotek - can we apply the proposed changes in our package.io build?

**Comment by monotek** [comment]
this is already implemented: https://github.com/zammad/zammad/blob/develop/contrib/packager.io/postinstall.sh#L29

**Comment by thorsteneckel** [comment]
We'll, that comes unexpected... Any idea why it's happening then? 🤔

**Comment by monotek** [comment]
no

**Comment by ghost** [comment]
I tried the following:

rpm -qp --scripts zammad-2.9.*.x86_64.rpm > zammad-script.txt

Attaching the extracted file 

[zammad-script.txt](https://github.com/zammad/zammad/files/2869874/zammad-script.txt)

This section is in: **postinstall scriptlet (using /bin/sh):**

By that time, source will be already in place on the running zammad installation. 

Is it possible that the schdeduler will trigger new codebase, while db migrations are not yet done, and cause issues later on?

In my humble opinion, if we need to stop zammad before upgrade, it would be better to call that specific stop_zammad function in preinstall scriplet  (see previously linked before_install doc on packager.io).

**Comment by thorsteneckel** [comment]
I'd like to see an issue that describes the actual issue in a comprehensible way. If things are unclear please refer to the [community board](http://community.zammad.org/) and we'll figure things out together. I'll close this one.
