### ISSUE TITLE
ActiveRecord::ValueTooLong

### ISSUE THREAD

**Issue by noezdev** [zammad/zammad#2475]
After upgrading to 2.9.x i have problems with updating certain tickets:

PG::StringDataRightTruncation: ERROR: value too long for type character varying(250) : UPDATE "tickets" SET "stateid" = $1, "preferences" = $2, "note" = $3, "closeat" = $4, "lastownerupdateat" = $5, "updatedbyid" = $6, "updatedat" = $7 WHERE "tickets"."id" = $8

In Logs:
I, [2019-02-14T19:39:32.424059 #30526-70135373919160]  INFO -- : Started PUT "/api/v1/tickets/15868?all=true" for 162.158.88.223 at 2019-02-14 19:39:32 +0100
I, [2019-02-14T19:39:32.428783 #30526-70135373919160]  INFO -- : Processing by TicketsController#update as JSON
I, [2019-02-14T19:39:32.428854 #30526-70135373919160]  INFO -- :   Parameters: {"number"=>"5415861", "title"=>"XXX", "group_id"=>"1", "owner_id"=>"50", "customer_id"=>XX, "state_id"=>"4", "priority_id"=>"2", "updated_at"=>"2019-02-14T15:20:06.367Z", "preferences"=>{"escalation_calculation"=>{"first_response_at"=>nil, "last_update_at"=>"2019-02-07T21:45:59.660Z", "close_at"=>nil, "sla_id"=>3, "sla_updated_at"=>"2019-02-12T16:19:47.531Z", "calendar_id"=>1, "calendar_updated_at"=>"2019-02-14T15:19:43.119Z", "escalation_disabled"=>false}}, "pending_time"=>nil, "XX"=>XX, "XX"=>XX, "XX"=>"XX", "verified"=>true, "id"=>"15868", "all"=>"true"}
E, [2019-02-14T19:39:32.475160 #30526-70135373919160] ERROR -- : PG::StringDataRightTruncation: ERROR:  value too long for type character varying(250)
: UPDATE "tickets" SET "state_id" = $1, "preferences" = $2, "note" = $3, "close_at" = $4, "last_owner_update_at" = $5, "updated_by_id" = $6, "updated_at" = $7 WHERE "tickets"."id" = $8 (ActiveRecord::ValueTooLong)

**Comment by SummerStorm** [comment]
Hi there, thanks for the report. 

1. Did this occur when using the web interface? Or did it occur when making an API call?

2. ~~I notice that you have three custom attributes for your ticket `"XX"=>XX, "XX"=>XX, "XX"=>"XX"`. Can you please verify that none of the input values are larger than 250 bytes? (Unicode characters could be up to 4 bytes long, so even a 100 characters string could conceivably reach the 250 limit)~~ 
EDIT: It's probably the note field that's causing this, so please ignore question 2.

**Comment by SummerStorm** [comment]
This is related to commit dabce01ec, which added XSS sanitation to the Ticket note field. The note field is 250 bytes long, which is enough for most messages, previously. But the sanitation process added extra HTML elements to the message, which makes it now larger than 250 bytes.

**Comment by thorsteneckel** [comment]
@noezdev - please always use the issue template and provide the required information. #2476 addresses the same issue and has the required issue template. Therefore I'll close this as a duplicate of #2476 .
