### ISSUE TITLE
Mysql2::Error: Data too long for column 'note'

### ISSUE THREAD

**Issue by pgodzwa** [zammad/zammad#2476]
### Infos:

* Used Zammad version: 2.9.0 stable
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04.5 LTS
* Database + version: mysql  Ver 14.14 Distrib 5.7.25
* Elasticsearch version: 5.6.14
* Browser + version: newest Chrome

### Expected behavior:

* Ticket successfully changes its status after clicking update button

### Actual behavior:

* Ticket doesn't change its status, shows following error:

`Mysql2::Error: Data too long for column 'note' at row 1: UPDATE `tickets` SET `stateid` = 4, `type` = 'Problem', `preferences` = '--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess\nescalationcalculation: !ruby/hash:ActiveSupport::HashWithIndifferentAccess\n firstresponseat: \'2019-02-14T10:10:35.000Z\'\n lastupdateat: \'2019-02-14T12:11:12.000Z\'\n closeat: \n slaid: 1\n slaupdatedat: \'2018-02-21T11:54:57.551Z\'\n calendarid: 1\n calendarupdatedat: \'2019-02-14T11:04:44.210Z\'\n escalationdisabled: false\n', `note` = 'Hi, \r\n\r\nI need to create very fast a database model of the UAT / Prod database for Custom system. \r\nI found that a tool called : <a href=\"https:pgmodeler.io\" rel=\"nofollow noreferrer noopener\" target=\"blank\">https:pgmodeler.io</a>\r\n\r\ncan create visual models with several clicks.\r\n\r\nIs there an option this to be installed for the ', `closeat` = '2019-02-15 06:59:24.603000', `lastownerupdateat` = NULL, `updatedbyid` = 3, `updatedat` = '2019-02-15 06:59:24.590000' WHERE `tickets`.`id` = 3063`

### Steps to reproduce the behavior:

* Not sure, so far we have this problem with only one ticket, others seem to work fine. 

Yes I'm sure this is a bug and no feature request or a general question.

Any idea how to fix it?

**Comment by SummerStorm** [comment]
#2475 is related. #2475 is the Postgres error message, while this one is the Mysql error message. I believe the underlying error is the same.

**Comment by martini** [comment]
@pgodzwa thanks for your response. I have one question regarding the `tickets.note` field. Currently there is no possibility to change this field in UI. Do you fill/use this field via API?

**Comment by SummerStorm** [comment]
This is related to commit dabce01ec, which added XSS sanitation to the Ticket note field. The note field is 250 bytes long, which is enough for most messages, previously. But the sanitation process added extra HTML elements to the message, which makes it now larger than 250 bytes.

**Comment by pgodzwa** [comment]
> @pgodzwa thanks for your response. I have one question regarding the `tickets.note` field. Currently there is no possibility to change this field in UI. Do you fill/use this field via API?

Yes, first ticket message was created using api, but message that's visible in this error was sent as email reply.

**Comment by thorsteneckel** [comment]
@pgodzwa - as a workaround you have to either increase the size of the column manually via an SQL statement or temporarily remove the note. We're working on a fix 👍

**Comment by noezdev** [comment]
We've open customer ticket since 02/19 we cannot close.

" PG::StringDataRightTruncation: ERROR: value too long for type character varying(250) : UPDATE "tickets" SET "preferences" = $1, "note" = $2, "updatedbyid" = $3, "updated_at" = $4 WHERE "tickets"."id" = $5"

**Comment by MrGeneration** [comment]
@noezdev please don't mix issues, this is about MySQL not PG-SQL.
Also, you seme to have a technical question apart this technical bug, so I'd like to ask you to create a post on the Community board if you need help. (https://community.zammad.org)

I'm limitting the conversation to contributors only to reduce the noise on this repository. 
As soon as something moves forward on this issue we'll update it accordingly.

**Comment by dominikklein** [comment]
Should be fixed with: https://github.com/zammad/zammad/commit/ffdbc246a7a4ce9f08b9b0d7e0a33b484cc0c438
