### ISSUE TITLE
Unable to update ticket with IE11

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2478]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Update tickets with IE11

### Actual behavior:

* IE11 is not supporting html5 validation api, ticket will not get updated.

**Comment by thorsteneckel** [comment]
This is a regression introduced by https://github.com/zammad/zammad/commit/f7a59c6bbd2c0373b13241e291abdf253bb1e49a - the fix for #2242.
