### ISSUE TITLE
Google+ API Shutdown on 7.3.2019 - Google Oauth Login will be broken (?)

### ISSUE THREAD

**Issue by DeltaLima** [zammad/zammad#2479]
Hey folks! Google will shutdown Google+ APIs, including Google+ Sign-in. Zammad uses the plus.people.getOpenIdConnect method from the google+ api. On 7.3.2019 the API will be completely shutdown.
I guess the Oauth via Google will be broken after that date. 
Is this already a topic on the roadmap for the next release? 

Thanks and best regards!

### What steps will reproduce the problem?

See Google announcement about google+ api shutdown

> Hello Google+ Developer,

> The email below contains your most recent usage of Google+ APIs. Note: It includes Google+ OAuth > scope requests, which are also affected by the Google+ shutdown. A prior email sent to active API > callers did not include information about OAuth requests. One final reminder email will be sent in > February to users who still have active API or OAuth request activity.
> What do I need to know?

> On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a > progressive shutdown, with API calls starting to intermittently fail as early as January 28, 2019, and > OAuth requests for Google+ scopes starting to intermittently fail as early as February 15, 2019.
> What do I need to do?
> 
> Please update your projects listed below by March 7, 2019 and ensure they are no longer using Google+ APIs, or requesting Google+ OAuth scopes. The data below shows which Google+ API methods your projects have recently called, as well as Google+ OAuth scopes it has requested.

> Note: If you see calls to people.get, these can be the result of using the Google+ Sign-In feature in your application, which is now fully deprecated and is being shut down. Developers should migrate from the Google+ Sign-In feature to the more comprehensive Google Sign-in authentication system.

### What is the expected result?

users should be able to login

### What do you get instead?

users are not able to login via google oauth

### Infos:

* Used Zammad version: latest repo package
* Installation method (source, package, ..):  package
* Operating system: Debian 9.7
* Database + version: Postgres 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This has been adressed with Zammad 2.9 already. (For the next time, please also don't write "latest repo package", as this might change daily).

You'll receive this information even if you're or Zammad is not using this API-Part anymore, but still have this activated. You can deactivate this feature and you'll see, it will still work. :-)

**Comment by thorsteneckel** [comment]
For the record: [This](https://github.com/zammad/zammad/commit/6870c11103df41b43ba8031adc387a68f925a3e5#diff-e79a60dc6b85309ae70a6ea8261eaf95) is the corresponding commit.
