### ISSUE TITLE
After adding a new attribute - zammad won't start

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#248]
Hi. I crashed my zammad. Added a new attribute named "Ort" and restarted the docker container. Now the postgresql won't start:

`Starting postgresql-9.6 service:                           [FAILED]
/etc/init.d/elasticsearch: line 75: ulimit: open files: cannot modify limit: Operation not permitted
error: "Read-only file system" setting key "vm.max_map_count"`

**Comment by martini** [comment]
Just one question, is it the docker image from here? https://hub.docker.com/r/zammad/zammad/

**Comment by Julian0o** [comment]
@martini Yes. I pulled it from your docker hub and made an update yesterday at 8pm German time :)
