### ISSUE TITLE
Javascript Error "TypeError: e is undefined" when forwarding (not always)

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#2481]
### Infos:

* Used Zammad version: 2.9.0-1550483988.7f4899e0.jessie
* Installation method (source, package, ..): deb from Zammad repository
* Operating system: Debian 8 Jessie
* Database + version: MariaDB 10.0.38-0+deb8u1
* Elasticsearch version: 5.6.15
* Browser + version: Firefox 52.8.0 ESR (Linux)

### Expected behavior:

Clicking on the "forward" icon fills a new post with the to-be-forwarded content

### Actual behavior:

Clicking on the "forward" icon results in no action but a JavaScript error.  From the Firefox JS console:
```
TypeError: e is undefined                                                                                  application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:70:7690
	App.Utils</t.htmlImage2DataUrl/<                               https://odcf-support.dkfz.de/assets/application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:70:7690
	.each                                                          https://odcf-support.dkfz.de/assets/application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:1:17625
	rt.prototype.each                                              https://odcf-support.dkfz.de/assets/application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:1:15676
	App.Utils</t.htmlImage2DataUrl                                 https://odcf-support.dkfz.de/assets/application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:70:7627
	t</n.emailForward                                              https://odcf-support.dkfz.de/assets/application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:43:27908
	t</n.perform                                                   https://odcf-support.dkfz.de/assets/application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:43:26109
	App.TicketZoomArticleActions</i.prototype.actionPerform        https://odcf-support.dkfz.de/assets/application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:44:8695
	t/<                                                            https://odcf-support.dkfz.de/assets/application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:44:7441
	e</s.prototype.delegateEvents/s</</<                           https://odcf-support.dkfz.de/assets/application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:8:6076
	rt.event.dispatch                                              https://odcf-support.dkfz.de/assets/application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:2:18908
	rt.event.add/g.handle                                          https://odcf-support.dkfz.de/assets/application-e719ca1b0ad02de24f28722af7d3638b9ede9d73822c1097cb86c14edc368575.js:2:17014
```
Please see this screenshot for how the error is displayed in the Firefox JS console:
![zammad_js_error_when_forwarding](https://user-images.githubusercontent.com/279232/53035938-e1c3c680-3476-11e9-83aa-37a7f9d1d503.png)

### Steps to reproduce the behavior:

We can only reproduce this with one specific email. Quite a long one, though, which already contains several levels of citation.

Unfortunately I cannot disclose the exact content of the email in question, as it contains sensible information.  but I hope that the error message gives enough indications to find the problem

**Comment by fthommen** [comment]
The problem might be the overly long line generated by #2482

**Comment by MrGeneration** [comment]
I'm sorry, but with the provided information I have no chance of reproducing this.
My Test-Mail ended up to be above 300kb (which I consider fairly big for just test with one inline image).

I can not reproduce this.
I attached my test Mail so you can cross check on your installation, it's possible that develop is working by now and the problem still exists on 2.9.

[ticket-71009-41.txt](https://github.com/zammad/zammad/files/3242270/ticket-71009-41.txt)
