### ISSUE TITLE
#{article.body_as_html} now includes attachments (e.g. PDFs)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2483]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* When using `#{article.body_as_html}` for sending out Article-Content, Zammad will only send the HTML-Content (Text, Formatting and Inline-Images) via Mail to the recipient.

### Actual behavior:

* When using `#{article.body_as_html}` for sending out Article-Content, Zammad will send inline images plus attachments (e.g. PDFs) to the recipient.

### Steps to reproduce the behavior:

* extent e.g. the `auto reply (on new tickets)`-Trigger and add `#{article.body_as_html} ` to the E-Mail-Body
* send a mail with inline image and an attachment (e.g. PDF) to Zammad
* wait for the autoreply from Zammad

This is a regression that has been introduced by: https://github.com/zammad/zammad/commit/487f36a5a552748e86b3de269207f177729cbacc

Yes I'm sure this is a bug and no feature request or a general question.

Edit: This only affects users sending HTML mails to Zammad, when using text mails, the attachment is not being send out.

**Comment by martini** [comment]
@MrGeneration can you attach an email to be able to reproduce this issue? Thanks!

**Comment by MrGeneration** [comment]
Hey,

please find attached:
[examples-for-reproducing.zip](https://github.com/zammad/zammad/files/2932268/examples-for-reproducing.zip)

Also, I have to correct myself: This only applies to HTML-Mails, so this is completely different on both ways. I updated my first article arcodingly.
