### ISSUE TITLE
Add attachment via Trigger and scheduler if wanted by admin

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2485]
### Infos:

* Used Zammad version: 2.9 and older
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* T#1073863, 1078540, 1084808

### Expected behavior:

* A possibility to send out article attachments via Trigger, if wanted.

### Actual behavior:

* No option to send out article attachments via Trigger.

### Steps to reproduce the behavior:

* none

### Possible solution:

Adding a checkbox (if "E-Mail" is selected for sending out) giving the user the possibility to include attachments of the article on sendout.

![image](https://user-images.githubusercontent.com/6549061/53108325-1f882400-3537-11e9-8e8f-6df12f61b592.png)

**Comment by ITfee** [comment]
+1
