### ISSUE TITLE
Forwarding: Attachment is missing if original HTML Mail contains an image

### ISSUE THREAD

**Issue by aemir** [zammad/zammad#2487]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04
* Database + version: x
* Elasticsearch version: x
* Browser + version: Firefox 65.0

### Expected behavior:

* An forwarded Email contains all attachments of the original mail

### Actual behavior:

* Some forwarded Emails are missing the attachment of the original mail

### Steps to reproduce the behavior:

* Create an HTML email with some text and an image
* Attach another file to the email
* Send the email to Zammad in order to generate a ticket
* Forward the email in Zammad ticket view
* -> The attachment in the forwarded mail is missing

[Anonymized testmail](https://github.com/zammad/zammad/files/2889984/testmail.zip)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by pgodzwa** [comment]
For me forwarding attachment is not working at all, no matter if HTML is in the message content or not.

I've created ticket with message "test" and attached "file.jpg".
When I want to forward this mail, attached file is not getting added to the editor.

**Comment by lorenzgroup** [comment]
Same with me, with Zammad 2.9 the Attachment is missing in forwarded mails.

**Comment by dennisoderwald** [comment]
+1
