### ISSUE TITLE
New users won't get initial user group

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#249]
When you add a new user while not having added a second group, the new user will have no permissions. You have to add a second group to get the group selection in the permissions area for the user. Than you can assign the new user to the initial Users group. 

Not a big issue because normally you work with more than one group, but its very confusing in the beginning.

**Comment by kevin-olbrich** [comment]
Just noticed this on a small installation. It is very confusing when you try to set up several agents and you are just trying to use a small communication group.
