### ISSUE TITLE
Plus characters are stripped from email addresses and urls in ticket body

### ISSUE THREAD

**Issue by Boldewyn** [zammad/zammad#2494]
### Infos:

* Used Zammad version: 2.9.0
* Installation method (source, package, ..): source
* Operating system: Debian
* Database + version: ?
* Elasticsearch version: ?
* Browser + version: Firefox, Chrome, latest each
~~* Ticket-ID: #1041339, #1077487~~

### Expected behavior:

* Zammad should not strip `+` characters from email addresses in ticket bodies
* Zammad should not strip `+` characters from URLs within ticket bodies

### Actual behavior:

* Zammad does strip said characters from email addresses in email bodies in the formatted view. Raw and “original formatting” data are fine, though. The character is already stripped off in the JSON response from the server to the web view.
*Zammad does strip said characters from urls in email bodies in the formatted view. Raw and “original formatting” data are fine, though. The character is already stripped off in the JSON response from the server to the web view.

### Steps to reproduce the behavior:

1. Send an HTML-only e-mail to the ticket system, containing the string `a+b@example.com` in the email body
2. Open the corresponding ticket in the Zammad web view.
3. Note, that the formatted view contains `ab@example.com`, the plus is gone.
4. View “raw” and “original formatting” representations: the plus is still there in both.

Above also applies to URLs

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please note that this only affects E-Mail-Adresses n HTML-E-Mails that live within a "mailto" so get converted into a link by your E-Mail-Program before sending.

Sample:
```
Return-Path: mherrguth@another-domain.tld
Delivered-To: erza@some-domain.tld
Received: from EHLO mikasa.thehomeofanime.de (mikasa.thehomeofanime.de [144.76.60.183])
	by mikasa.thehomeofanime.de with ESMTPSA
	(version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128)
	; Tue, 26 Feb 2019 17:57:14 +0100
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_ab8f81114ef69fa5c44aaabe094f06ee"
Date: Tue, 26 Feb 2019 17:57:14 +0100
From: Marcel Herrguth <mherrguth@another-domain.tld>
To: erza@some-domain.tld
Subject: Test + HTML + Formatting + Link
Organization: The home of Anime
Message-ID: <220663c004662e0743b4d38e42387123@another-domain.tld>
X-Sender: mherrguth@another-domain.tld
User-Agent: Roundcube Webmail (THA)

--=_ab8f81114ef69fa5c44aaabe094f06ee
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=US-ASCII

TEST 

unformated+test@thehomeofanime.de 

test+subscribe@thehomeofanime.de 

test+pasted@thehomeofanime.de 

-- 
www.another-domain.tld [1] - The home of Anime


Links:
------
[1] http://www.another-domain.tld
--=_ab8f81114ef69fa5c44aaabe094f06ee
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html; charset=
=3DUTF-8" /></head><body style=3D'font-size: 10pt; font-family: Verdana,Gen=
eva,sans-serif'>
<div class=3D"pre" style=3D"margin: 0; padding: 0; font-family: monospace">=
<strong>Test</strong></div>
<div class=3D"pre" style=3D"margin: 0; padding: 0; font-family: monospace">=
&nbsp;</div>
<div class=3D"pre" style=3D"margin: 0; padding: 0; font-family: monospace">=
<a href=3D"mailto:unformated+test@thehomeofanime.de">unformated+test@thehom=
eofanime.de</a></div>
<div class=3D"pre" style=3D"margin: 0; padding: 0; font-family: monospace">=
&nbsp;</div>
<div class=3D"pre" style=3D"margin: 0; padding: 0; font-family: monospace">
<div><a href=3D"mailto:test+subscribe@thehomeofanime.de">test+subscribe@the=
homeofanime.de</a></div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div>test+pasted@thehomeofanime.de</div>
<br /> <br /> <span class=3D"sig">--&nbsp;<br /> <a href=3D"http://www.dp=
domain.de" target=3D"_blank" rel=3D"noopener noreferrer">www.domain=
=2Ede</a><br /> <br /=
> The home of Anime @<br /> Facebook:<a href=3D"https://www.facebook.com/mr=
generation.de" target=3D"_blank" rel=3D"noopener noreferrer">https://www.fa=
cebook.com/another-domain.tld</a><br /> Twitter: <a href=3D"https://twitter.co=
m/Mr_Generation" target=3D"_blank" rel=3D"noopener noreferrer">https://twit=
ter.com/Mr_Generation</a></span></div>
</body></html>

--=_ab8f81114ef69fa5c44aaabe094f06ee--
```

**Comment by contaoacademy** [comment]
I have a similar problem here. The + sign is also removed from my links and replaced by %20.

![screenshot](https://user-images.githubusercontent.com/23719181/55982367-10049c00-5c99-11e9-9449-fd9a6ebac521.png)

**Comment by contaoacademy** [comment]
Hey!

Are there any news about when the bug will be fixed?

**Comment by MrGeneration** [comment]
Sorry, but we currently can't give an ETA for fixing this.
We're working hard on addressing issues and will update this issue, as soon as we're working on it.

**Comment by martini** [comment]
Just for the notes. The result with @MrGeneration email example looks this:

![image](https://user-images.githubusercontent.com/110226/87157683-e3d23380-c2be-11ea-9a61-d2e38e01503c.png)

With the upcoming fix it looks this:

![image](https://user-images.githubusercontent.com/110226/87157638-d6b54480-c2be-11ea-8c88-7b4cfe2753a8.png)


In addition, the following link `<a href="https://example.com/?foo=https%3A%2F%2Fexample.com%3Flala%3A123">example</a>` was converted into `<a href="https://example.com/?foo=https://example.com?lala:123">example</a>` which was also not correct.
