### ISSUE TITLE
Session.jobs crashes regualary

### ISSUE THREAD

**Issue by AchMol** [zammad/zammad#2495]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): apt package
* Operating system: Ubuntu 16.04
* Database + version: mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64)
* Elasticsearch version: 
* Browser + version: Firefox

### Expected behavior:

* Running without crash

### Actual behavior:

* Session.jobs crashes regualary

### Steps to reproduce the behavior:

* Good question...

Yes I'm sure this is a bug and no feature request or a general question.

Because the Zammad session jobs crashed again and again I started them separately as someone advised in another article. 

systemctl stop zammad-worker
zammad run rails r 'Scheduler.find_by(method: "Sessions.jobs").update(active: false)'
systemctl start zammad-worker

Now it runs separately in the background with screen. Sometimes ist crashes 4 times a day and then it runs for 3 days without any problems...

```ruby
root@xxxxxx:/opt# sudo -u zammad zammad run rails r 'Sessions.jobs'
/opt/zammad/lib/sessions.rb:745:in `rescue in thread_client': STOP thread_client for client .4663316065 after 10 tries (RuntimeError)
        from /opt/zammad/lib/sessions.rb:720:in `thread_client'
        from /opt/zammad/lib/sessions.rb:743:in `rescue in thread_client'
        from /opt/zammad/lib/sessions.rb:720:in `thread_client'
        from /opt/zammad/lib/sessions.rb:743:in `rescue in thread_client'
        from /opt/zammad/lib/sessions.rb:720:in `thread_client'
        from /opt/zammad/lib/sessions.rb:743:in `rescue in thread_client'
        from /opt/zammad/lib/sessions.rb:720:in `thread_client'
        from /opt/zammad/lib/sessions.rb:743:in `rescue in thread_client'
        from /opt/zammad/lib/sessions.rb:720:in `thread_client'
        from /opt/zammad/lib/sessions.rb:743:in `rescue in thread_client'
        from /opt/zammad/lib/sessions.rb:720:in `thread_client'
        from /opt/zammad/lib/sessions.rb:743:in `rescue in thread_client'
        from /opt/zammad/lib/sessions.rb:720:in `thread_client'
        from /opt/zammad/lib/sessions.rb:676:in `block (3 levels) in jobs'
        from /opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
 ```

What is the cause and what can I do to prevent this behavior?

**Comment by MrGeneration** [comment]
Please provide your production log of the time where this happens as this is quite hard to reproduce.

**Comment by AchMol** [comment]
After weeks of problems it is working now as expected for some days and I don't know why... ;-)

I will reopen this issue if it happens again...
