### ISSUE TITLE
eml-File Attachments will be destroyed by zammad

### ISSUE THREAD

**Issue by mpkps** [zammad/zammad#2499]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): zammad repo, debian package
* Operating system: Ubuntu Server 18.04
* Database + version: postgresql 10
* Elasticsearch version: 5.6.14
* Browser + version: Chrome 72.0.3626.109

### Expected behavior:

* Customers should be able to receive eml-files in email attachments without modifications by zammad

### Actual behavior:

* eml-files are empty when they were sent out via email attachments by zammad

### Steps to reproduce the behavior:

* download an email from any article in raw-format
* select another ticket
* add the downloaded eml-file to the attachments
* sent out email
* eml-file has no content at the receiver

**File after download**
![image](https://user-images.githubusercontent.com/47779669/53484153-6f10a780-3a83-11e9-9ed9-368d724f2eeb.png)

**File added to attachments**
![file_added_attachments](https://user-images.githubusercontent.com/47779669/53484180-7d5ec380-3a83-11e9-8adb-98f3c714dbb8.png)

**File received by customer**
![file_at_customer](https://user-images.githubusercontent.com/47779669/53484306-d0d11180-3a83-11e9-8fde-aa8b996b3122.png)
 
**File Content**
![file_content](https://user-images.githubusercontent.com/47779669/53484453-2c030400-3a84-11e9-879a-4b0cbdac742b.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This comes from: https://community.zammad.org/t/eml-file-attachments-will-be-destroyed-by-zammad/2142 and has already been verified by me.

**Comment by SummerStorm** [comment]
Fixed via 30d3ce2b88c9bbbbd6800f120a7fdaac5893e900.
