### ISSUE TITLE
Can’t process email <ActiveRecord::RecordNotFound>

### ISSUE THREAD

**Issue by gschnepp** [zammad/zammad#2500]
### Infos:
* Used Zammad version: 2.8.0
* Used Zammad installation source: source
* Operating system: Debian
* Browser + version: Firefox (Win 10)

### Expected behavior:

* Tried to process an own test e-mail to Zammad which was desired to import correctly. e-mail import works just fine (e-mail is taken from IMAP), but can't be processed further actually.

### Actual behavior:

* Ticket e-mail can't be processed. Error message in scheduler-out.log says: "ERROR: Can't process email" and "ERROR: #<ActiveRecord::RecordNotFound: Couldn't find Ticket without an ID>"

* This seems to be an identical problem to the closed but (publicly unresolved) ticket [https://community.zammad.org/t/e-mails-cant-be-processed-recordnotfound/1152](https://community.zammad.org/t/e-mails-cant-be-processed-recordnotfound/1152) ! Can you tell me what the problem was that time?

Receiving e-mails worked on the vanilla Zammad setup. After (command-line) import from OTRS, e-mails can't be processed any longer in the same system. This is also true for e-mails to the native e-mail address assigned to mailbox cdo00-zammad, so filter rules are not the problem.

### Steps to reproduce the behavior:

* not working test e-mail is attached

By the way: I haven an active group named "AFP-Lookup" and an active filter for e-mail support@afp-lookup.com to be forwarded to this group:
![grafik](https://user-images.githubusercontent.com/23098991/53550401-e7847080-3b36-11e9-98b7-dbccf6b94473.png)
Any e-mail to this address is forwarded to a collecting mailbox ("cdo00-zammad") for all support requests before. Zammad pulls all e-mails from that mailbox via IMAP.

Yes I'm sure this is a bug and no feature request or a general question.

(Copied from here, since it seems not to gain attention there. And error message clearly said: Open an issue on Github...)

[0da14456313e210db85b85e18db0eba8.eml.txt](https://github.com/zammad/zammad/files/2913974/0da14456313e210db85b85e18db0eba8.eml.txt)

**Comment by gschnepp** [comment]
No idea why, but everything works as of today suddenly. Changed nothing, no updates, ...  :-/  Ticket left open for now, maybe the team still has interest to have a look on it.

Only cause I can imagine is that the last test happened short after OTRS import any system still may've been busy with indexing ...

**Comment by MrGeneration** [comment]
I could verify this with both of your mails inside a clean 3.0 instance.
The traceback here is:

```
E, [2019-07-03T10:47:35.085811 #18924-80182460] ERROR -- : undefined method `first' for nil:NilClass (NoMethodError)
/opt/zammad/lib/signature_detection.rb:42:in `block in find_signature'
/opt/zammad/lib/signature_detection.rb:29:in `each'
/opt/zammad/lib/signature_detection.rb:29:in `find_signature'
/opt/zammad/lib/signature_detection.rb:137:in `by_user_id'
/opt/zammad/lib/signature_detection.rb:172:in `rebuild_user'
/opt/zammad/app/models/transaction/signature_detection.rb:48:in `perform'
/opt/zammad/app/models/observer/transaction.rb:62:in `execute_singel_backend'
/opt/zammad/app/models/transaction/background_job.rb:30:in `block in perform'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/relation/delegation.rb:39:in `each'
/usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/relation/delegation.rb:39:in `each'
/opt/zammad/app/models/transaction/background_job.rb:26:in `perform'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run'
/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times'
/usr/local/rvm/gems/ruby-2.4.4/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off'
/opt/zammad/app/models/scheduler.rb:367:in `block (3 levels) in worker'
/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/opt/zammad/app/models/scheduler.rb:365:in `block (2 levels) in worker'
/opt/zammad/app/models/scheduler.rb:361:in `loop'
/opt/zammad/app/models/scheduler.rb:361:in `block in worker'
/usr/local/rvm/gems/ruby-2.4.4/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by dominikklein** [comment]
@gschnepp For me with the current Zammad version the import from the attached version is working fine. The issue will be closed. Feel free to send some additional reproduction steps, when the issue still exists for you.
