### ISSUE TITLE
Wrong language on login screen

### ISSUE THREAD

**Issue by cyberrranger** [zammad/zammad#2505]
*This has been partly updated by @MrGeneration to meet our needed forms*
*there is also another customer running into this problem T#1060510*

### Infos:

* Used Zammad version: "2.9.x"
* Installation method (source, package, ..): docker-compose
* Operating system: Linux
* Database + version:  postgresql "2.9.x"
* Elasticsearch version: "2.9.x"
* Browser + version: Current Chrome (72)
* Ticket-ID: #1054269 

on chrome://settings/?search=lang
First Position English (United States)
Last Position Russian

### Expected behavior:

* open URL to Zammad => Login in English

### Actual behavior:

* open URL to Zammad => Login in Russian

### Steps to reproduce the behavior:

* add russian on chrome://settings/?search=lang

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Thanks for your contribution!
I could verify this, the position of russian language does not matter and will override whatever language.

I cross testet this with spanish and this doesn't happen there. Seems to only affect for whatever reason.

**Comment by Marian0** [comment]
Same error here. Tried to install it on Ubuntu 18 and I'm getting this weird language as default:

![image](https://user-images.githubusercontent.com/624592/54631317-84616c00-4a5a-11e9-9d79-47111f6f0a45.png)

**Comment by thorsteneckel** [comment]
Hey there - interesting! Can you please run `App.i18n.detectBrowserLocale()` in your browser console and post the output here? Thanks!

**Comment by Marian0** [comment]
Hey @thorsteneckel, thanks for your response.

This is the output from console:

```
App.i18n.detectBrowserLocale()
"da"
```

Thank you

**Comment by martini** [comment]
@Marian0 also the output of `window.navigator.languages`  your browser console would be good to know. Thanks.

EDIT: And
```js
console.log('window.navigator.languages', window.navigator.languages)
console.log('window.navigator.userLanguage', window.navigator.userLanguage)
console.log('window.navigator.language', window.navigator.language)
```
As well as the expected language.

**Comment by cyberrranger** [comment]
App.i18n.detectBrowserLocale() . => "ru"

window.navigator.languages (5) ["en-US", "de-DE", "de", "en", "ru"]
window.navigator.userLanguage undefined
window.navigator.language en-US

**Comment by Marian0** [comment]
@martini 

This is the output I'm getting using private browser tab:

```
window.navigator.languages (8) ["es-ES", "es", "da", "en", "gl", "pt", "fr", "la"]0: "es-ES"1: "es"2: "da"3: "en"4: "gl"5: "pt"6: "fr"7: "la"length: 8__proto__: Array(0)

window.navigator.userLanguage undefined

window.navigator.language es-ES
```

Seems like userLanguage is not being set.

**Comment by MrGeneration** [comment]
Trial User is also experiencing this ( #1052496 )

![image](https://user-images.githubusercontent.com/6549061/63936018-23a17b00-ca5f-11e9-9b62-8b7ebad43e3e.png)

**Comment by schweizersolutions** [comment]
I had the same issue, but just in Chrome and not in Firefox. I've remove the Russian language from my language settings in Chrome and now I see the correct language. Now I've just English and German in the Chrome settings.

**Comment by tarreislam** [comment]
Workarounds?

**Comment by MrGeneration** [comment]
None. Or rather: Set your profile language to the correct language.

**Comment by tarreislam** [comment]
Hmmm. A workaround could be the option to remove installed languganes besides EN-US, that would be easier and better for everyone interacting with the service.

Where are the languages defined?

**Comment by MacroPolo** [comment]
I have been investigation this situation and there seems to be two issues. 

Looking at the [detectBrowserLocale](https://github.com/zammad/zammad/blob/fae194918eb8a07036060a1b41f1b33c45e03cad/app/assets/javascripts/app/lib/app_post/i18n.coffee#L88) method it first compares each of the language codes sent by the user agent with the `locale`s known to Zammad.

In one of my test cases, I add Russian to both Firefox and Chrome and get the following output:

```
window.navigator.languages
Array(3) [ "en-GB", "en", "ru" ]

App.i18n.detectBrowserLocale()
"ru"
```

The comparison is case sensitive so `en-GB` doesn't match, `en` is not known to Zammad but `ru` is. My language is therefore detected as Russian.

```
mysql> SELECT id,locale,alias,name FROM locales WHERE locale LIKE '%en%';
+----+--------+-------+-------------------------+
| id | locale | alias | name                    |
+----+--------+-------+-------------------------+
|  1 | en-us  | en    | English (United States) |
|  7 | en-ca  |       | English (Canada)        |
|  8 | en-gb  |       | English (Great Britain) |
+----+--------+-------+-------------------------+
```

That issue may be resolvable by ensuring that the country code comparison is sanitised to lowercase:

```
if browserLocale.toLowerCase() is localAllLocale.locale
```

For some other languages (e.g. Spanish) there is a different issue. Changing to Spanish I see the following output:

```
window.navigator.languages
Array(3) [ "en-GB", "en", "es" ]

App.i18n.detectBrowserLocale()
"en-us"
```

In that case, the UI renders in English, but it is US English rather than GB English. My first two locales are ignored because of the issue described above, but there is also no `es` locale know to Zammad:

```
mysql> SELECT id,locale,alias,name FROM locales WHERE locale LIKE '%es%';
+----+--------+-------+---------------------+
| id | locale | alias | name                |
+----+--------+-------+---------------------+
|  9 | es-es  | es    | Español             |
| 10 | es-co  |       | Español (Colombia)  |
| 11 | es-mx  |       | Español (México)    |
+----+--------+-------+---------------------+
```

So the `detectBrowserLocale` method hits the second `for` statement which slices the first two characters from each of the country codes provided by the user agent and compares that against the Zammad aliases. So in my case, `en-GB` gets slices to `en` which matches the `en-us` locale:

```
mysql> SELECT id,locale,alias,name FROM locales WHERE alias ='en';
+----+--------+-------+-------------------------+
| id | locale | alias | name                    |
+----+--------+-------+-------------------------+
|  1 | en-us  | en    | English (United States) |
+----+--------+-------+-------------------------+
```

To fix that issue, you should also ensure that the `locales` table has a more robust list, with common codes such as `es`, `it`, `fr`, `de` etc includes.

**Comment by MacroPolo** [comment]
I was able to workaround my immediate issue by disabling the Russian locale however I do not know how robust that method is and whether it will survive an upgrade:

```
mysql> UPDATE locales SET active=0 WHERE locale="ru";
```

**Comment by tarreislam** [comment]
> None. Or rather: Set your profile language to the correct language.

Typical developer resonse 😄.

I went with @MacroPolo s solution with a twist. Forcing locales is bad design

`delete from locales where alias != 'en';`

**Comment by mantas** [comment]
![50524f4752414d4d4552-49204d2057414954494e4720464f52205141204f4e204d59205052-57414954494e4720464f52205141](https://user-images.githubusercontent.com/36944/74352140-c2792400-4dc0-11ea-88ce-a942fc586425.png)

**Comment by cyberrranger** [comment]
thx
