### ISSUE TITLE
Page posts from facebook and tweets from twitter as tickets

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#251]
Yesterday I enabled the facbeook channel for one of my pages. 

Zammad created a ticket for every single post published by the page **self**.

I think that's not the desired behavior.

**Comment by thorsteneckel** [comment]
Just a question for clearance - do you want to handle comments on that post or not? Generally speaking.

**Comment by monotek** [comment]
Maybe posts from the Facebook site admin could be created as closed tickets and only reopened when somebody comments?

**Comment by Julian0o** [comment]
That should make sense. Or it should be opened when the first comment was made.

**Comment by martini** [comment]
Yes. A post (a new topic) should create a ticket and any comment is a follow up for it (it's currently implemented this way).

@monotek A good idea to directly set self created posts/tickets directly to closed.

**Comment by MDXDave** [comment]
The Twitter channel seems to be implemented different. Own posts will created only as ticket, if a reply is received.

**Comment by martini** [comment]
Update: Changed facebook channel to automatically create ticket with state closed if owner page account is creating a new post (https://github.com/zammad/zammad/commit/fa8c8ae8ab2a1d69fc8ee1df114c27f59b8545ba) Ticket will be reopend if an user add an comment.

**Comment by martini** [comment]
@MDXDave (with twitter) currently own posts also created as tickets with state "new". I'll go to change it too + unit tests...

**Comment by martini** [comment]
Implemented https://github.com/zammad/zammad/commit/d74444fc30147c540c619ac176e05e8746ec6ea3

JFI: We also added a limit to only import 20 old tweet/facebook posts on initial config.
