### ISSUE TITLE
Zammad Customers shown as Agents in IE

### ISSUE THREAD

**Issue by antboll** [zammad/zammad#2510]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): Packages
* Operating system: Cent OS
* Database + version:
* Elasticsearch version:
* Browser + version: IE 11.590.17134.0; Firefox 65.0.2
* Ticket-ID: #1040378, #1038208, #1041753, #1042609

### Expected behavior:

If I Assign a ticket to an Agent only the Agents where shown in dropdown list

### Actual behavior:
IE 11
If I would assign a Ticket to an agent all Zammad Customers where shown in Dropdown list.
Firefox 65.0.2
in Firefox or Chrome only the members of the group agents are shown

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Hey,

sorry but I can't reproduce this.
Can you please give us more information? 

E.g.: Does this only affect one customer and if so, can you please provde a screen of this user configuration? (e.g. role assignment to the customer and his rights).

Please provide a detailed description on how to reproduce this behavior, other wise we can't reproduce this.

**Comment by MrGeneration** [comment]
Nevermind, I now could verify it. My bad!
