### ISSUE TITLE
Zammad Webcam-Avatar-Feature broken

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2514]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Currently Chrome only, but other browsers will follow soon

### Expected behavior:

* You can create a new avatar in Zammad with your Webcam.

### Actual behavior:

* When trying to create a webcam avatar, the webcam area stays blank/white, the console throws an error.

### Steps to reproduce the behavior:

* Login to Zammad
* go to Profile -> Avatar and try to shoot a webcam avatar

Hint from Thorsten:
[window.URL.createObjectURL(stream)](https://github.com/zammad/zammad/blob/f080a144e0ee77c1e6156cf60df7f12e5048ebfe/app/assets/javascripts/app/controllers/_profile/avatar.coffee#L304) is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL#Using_object_URLs_for_media_streams). Current way to do it can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/srcObject).

![image](https://user-images.githubusercontent.com/6549061/54195603-64accf80-44bf-11e9-9b6a-9c611fb8bbc3.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
@mrflix I found the problem:

> Apparently this functionality (of creating a URL from a MediaStream) is now deprecated and has been removed from current versions of Chrome and Firefox as of mid/late 2018. See https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL for details. Apparently the new recommended approach is to set the srcObject property to the localStream directly:

    @video.get(0).srcObject = stream

**Comment by MrGeneration** [comment]
Working now again in Chrome and Edge.

On Internet Explorer the Camera-Button is missing completely.
![image](https://user-images.githubusercontent.com/6549061/54529443-337d4500-4980-11e9-8090-5e066ca24cf1.png)

**Comment by mrflix** [comment]
We're doing a feature check here and only show the button if the browser gives us webcam access.

**Comment by MrGeneration** [comment]
Okay, thanks for clarification, this seems to be fixed then!
