### ISSUE TITLE
trigger email notification UI defective on removal of recipient

### ISSUE THREAD

**Issue by sstidl** [zammad/zammad#2516]
### Infos:

* Used Zammad version: 2.9.x docker as of 18th of march 2019
* Installation method (source, package, ..): docker REPO=zammad/zammad-docker-compose
* Operating system: debian 9
* Database + version: docker default
* Elasticsearch version: docker default
* Browser + version: docker default

### Expected behavior:

*  in Trigger Edit mode, Action "Email" works like expected: removing someone to receive an email just removes this person or group

### Actual behavior:

* when removing something from the upper left list, the whole UI vanishes, leaving the UI in a defective state. 

### Steps to reproduce the behavior:

* use /#manage/trigger UI to create a new trigger
* use in actions UI the action "Email" notification
* use owner from the list right to add it to the list of persons to be notified
* fill out everything needed to save the notification
* save it and reopen it
![image](https://user-images.githubusercontent.com/12804296/54557090-aacfca80-49ba-11e9-9550-bf1ca37dad8b.png)

* add "all agents" to the list
![image](https://user-images.githubusercontent.com/12804296/54557133-be7b3100-49ba-11e9-9d33-c97f3ed57eed.png)

* and remove it 
=> UI is damaged now

![image](https://user-images.githubusercontent.com/12804296/54557002-71975a80-49ba-11e9-896d-5942b4661ab8.png)

**Comment by MrGeneration** [comment]
This also affects condition on triggerss:
![image](https://user-images.githubusercontent.com/6549061/54629774-8cc89f80-4a78-11e9-94e1-e539d2e9a40c.png)

**Removing all actions works in:**

* Scheduler
* Trigger

**Removing all conditions works in:**

* Trigger
* Report Profiles (note this throws error "{"error":"no selectors given"}" and will not apply this even though it does let you submit this change)
* time accounting
* SLAs (note this throws error "{"error":"no selectors given"}" and will not apply this even though it does let you submit this change)
* Postmaster filters
* auto assignment

Please note that every where I could submit, the changes did not take effect. So this is mostly a UI issue, after reloading Zammad they last option you removed will be there again.

**Comment by sstidl** [comment]
Is this really not fixed in 3.0?

**Comment by MrGeneration** [comment]
No it's not.

**Comment by martini** [comment]
> Is this really not fixed in 3.0?

Just saw it. It's in CI now... it's coming...

**Comment by martini** [comment]
It's now fixed for Zammad 3.0 and 2.9. 🥂

**Comment by sstidl** [comment]
Thanks!
