### ISSUE TITLE
Inline image is missing on forward

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#2521]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): package
* Operating system: CentOS
* Database + version: Postgres
* Elasticsearch version: ES 6.x
* Browser + version: Safari/Firefox
* Ticket-ID: #1040687

### Expected behavior:

* Zammad should keep inline images when forwarding and quoting text

### Actual behavior:

* in Safari latest and Firefox 66.0 the images are lost

### Steps to reproduce the behavior:

* Create an E-Mail with an inline image and sent it to Zammad
* Mark the part of the created E-Mail and hit reply
* Inline images are broken in preview and after save

@martini maybe it's a Jesus Bug of this: https://github.com/zammad/zammad/issues/2101

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
This can't be reproduced anymore. The referenced Ticket does not contain information on how to reproduce this. Therefore I'll close it.
