### ISSUE TITLE
Elasticsearch index:Rebuild not working

### ISSUE THREAD

**Issue by potlaki** [zammad/zammad#2524]
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): apt install
* Operating system: Ubuntu 16.04 LTS
* Database + version: Postgresql 10
* Elasticsearch version: 6.6.2
* Browser + version: Firefox Quantum 66

### Expected behavior:

* To use the reporting tab

### Actual behavior:

* Cannot use the reporting tab

### Steps to reproduce the behavior:

* Log in, click on the reporting tab. The following error appears: Attached
[elasticsearch_issue.zip](https://github.com/zammad/zammad/files/3013136/elasticsearch_issue.zip)

Having read up on the error, it appears this might be a compatibility issue. My version of Elastic search is not supported. Is it possible for me to downgrade the version of Elasticsearch safely ?

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Your elasticsearch version is not supported. Please do not post technical questions on Github, as this is mainly for bugs. For the next time, please use our Community: https://community.zammad.org

If the elasticsearch is only used by Zammad, you can safely remove (apt remove elasticsearch) and reinstall the correct elasticsearch version. You'll need to follow the installation guide for elasticsearch to ensure Zammad does what it's supposed to do afterwards.

See: https://docs.zammad.org/en/latest/install-elasticsearch.html
