### ISSUE TITLE
No unprocessed email and no new/update ticket

### ISSUE THREAD

**Issue by Shayano** [zammad/zammad#2526]
### Infos:

* Used Zammad version: 2.10
* Installation method (source, package, ..): apt
* Operating system: Debian 9.8
* Database + version: PostgreSQL 9.6.11
* Elasticsearch version: 6.6.1
* Browser + version: any

### Expected behavior:

* Create a new ticket on processed email
* Update existing ticket on processed email

### Actual behavior:

* doesn't create or update ticket
* doesn't appear in unprocessed email

### Steps to reproduce the behavior:

* Send an email with the content in the .docx attached file (signature_test.docx).
A customer have this content in his signature and when he send a email to our support, we can't notice anything. (no unprocessed email or ticket)
In the production log, the mail was catched @2019-03-29T12:20:32.

[production.log](https://github.com/zammad/zammad/files/3022451/production.log)
[signature_test.docx](https://github.com/zammad/zammad/files/3022450/signature_test.docx)

**Comment by MrGeneration** [comment]
We'll verify this as soon as we find time. Please note that your elasticsearch version is not supported. 
You should think about downgrading it, as otherwise this will lead to other errors.

Regarding ES, please see: https://docs.zammad.org/en/latest/install-elasticsearch.html

**Comment by MrGeneration** [comment]
Sorry, but I can't reproduce this.
Ignoring the fact that this test signature contains tons of tables.. could you instead please provide a working sample EML that you sent?

I'll then gladly try again.

![image](https://user-images.githubusercontent.com/6549061/60577308-60166a80-9d7f-11e9-87aa-85d1a933e447.png)


Side note: You might not want to use develop (2.10 is develop) installations in productive.

**Comment by Shayano** [comment]
Thanks for your answer, we update in 3.0 few weeks ago.
I tried to reproduce the problem in 3.0 but it's working normally now.
