### ISSUE TITLE
Ticket gets reopen by an email send via a trigger configured with recipient article_last_sender and article sender was 'customer'

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2527]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Zammad should not reopen tickets by sending a trigger notification to Zammad it self.

### Actual behavior:

* In certain cases Zammad sends a trigger base email notification to Zammad it self and my reopen the ticket.

### Steps to reproduce the behavior:

* create trigger #1 with
 - state is changed
 - trigger notification to `article_last_sender`

* create trigger #2 with
 - state is changed
 - trigger notification to `article_last_sender`

* close a ticket and you will see 2 trigger based notifications. The second one is sending a email to Zammad it self (because the used `article_last_sender ` is based on first generated trigger based email notification).

**Comment by mantas** [comment]
Likely fixed by https://github.com/zammad/zammad/issues/2923 ?

**Comment by thorsteneckel** [comment]
@rolfschmidt is this a duplicate?

**Comment by rolfschmidt** [comment]
yeah i think so. @martini please reopen if you think different but i think it is already fixed with #2923 . Thank you @mantas !
