### ISSUE TITLE
Vagrant version

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#253]
As requested [here](https://news.ycombinator.com/item?id=12757600) there should be a vagrant version.

**Comment by s-oram** [comment]
Great! I'll give it a go once the vagrant box is ready. :)

**Comment by thorsteneckel** [comment]
Done: https://github.com/zammad/vagrant

Please note this issue: https://github.com/zammad/zammad/issues/280 which cause no no troubles except an nasty exception. We're on it. The rest of the vagrant box should work full featured. If not, please leave us an issue in the vagrant repo so we can handle it.
