### ISSUE TITLE
SLA Email 

### ISSUE THREAD

**Issue by Shra25** [zammad/zammad#2532]
I want SLA to set in three levels and according to level, it will escalate to different persons.
only agents are getting escalated emails I want to customise this
can anyone please help me with this

**Comment by MrGeneration** [comment]
Sorry, but Github is for bugs only, not technical questions.
You can consult our community (https://community.zammad.org/) for such questions.

Escalation on that level (for which it wouldn't be made normally) will require to work with the owners as condition, other wise you need to seperate those mails with groups.
