### ISSUE TITLE
Karma doesn't track text module usage

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#2537]
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): docker-compose
* Operating system: Debian 9
* Database + version: current docker-compose
* Elasticsearch version: current docker-compose
* Browser + version: Chromium 73

### Expected behavior:

Not sure whether karma is actually supported at all, seeing that it's neither documented nor usually accessible in the UI, but I noticed a bug in it, so here goes :)

* The `karma_activities` table contains a row `text module` that implies that Karma should be able to track the usage of text modules. So I would expect that using a text module would insert a record into `karma_activity_log` with this `activity_id`.

### Actual behavior:

* When you use a text module, the text module usage isn't logged to `karma_activity_log`. It's not obvious in the UI (because it groups pending state, text module and tagging as "Usage of advanced features"), but you can see it in the DB. This query shows all karma events that have happened, the most recent ones on top:

	```
	select u.login, ka.name, kal.score, kal.score_total, kal.created_at, kal.updated_at from karma_activity_logs kal join users u on (u.id = kal.user_id) join karma_activities ka on (ka.id = kal.activity_id) order by kal.updated_at desc;
	```

	This is what it logs when I reply with a text module and set the ticket to pending close:

	```
		   login        |         name         | score | score_total |         created_at         |       updated_at
	--------------------+----------------------+-------+-------------+----------------------------+-------------------------
	 martin.von.wittich | ticket pending state |     2 |        1566 | 2019-04-06 12:54:18.106227 | 2019-04-06 12:54:18.106
	```

	This query shows how often each karma activity was logged:

	```
	select ka.id, ka.name, count(kal.id) from karma_activities ka left outer join karma_activity_logs kal on (ka.id = kal.activity_id) group by ka.id, ka.name order by ka.id asc;
	```

	The result from our production system:

	```
	 id |               name                | count
	----+-----------------------------------+-------
	  1 | ticket create                     |   585
	  2 | ticket close                      |    26
	  3 | ticket answer 1h                  |    59
	  4 | ticket answer 2h                  |     8
	  5 | ticket answer 12h                 |    32
	  6 | ticket answer 24h                 |    14
	  7 | ticket pending state              |   145
	  8 | ticket escalated                  |     3
	  9 | ticket reminder overdue (+2 days) |     0
	 10 | text module                       |     0
	 11 | tagging                           |   302
	(11 Zeilen)
	```

	As you can see, `text module` has been logged zero times, although agents have certainly used text modules.

### Steps to reproduce the behavior:

* Use a text module when replying.
* Note that it won't be logged in the tables described above.

### Further analyses

If I'm reading the code correctly, `app/models/transaction/karma.rb` is responsible for logging karma activities; this fragment is responsible for text modules:

```
    ### text module
    if article.preferences[:text_module_ids].present?
      Karma::ActivityLog.add('text module', user, 'Ticket', @item[:object_id])
    end
```

Apparently the text module usage should be stored as `text_module_ids` in the article's preferences, but it's not - `text_module_ids` isn't actually used anywhere else in the code:

```
zammad@martin ~ (develop) % ag --no-pager 'text_module_ids' .
app/models/transaction/karma.rb
163:    if article.preferences[:text_module_ids].present?
```

According to `git log -S text_module_ids`, it wasn't ever accidentally removed, so this was probably always broken.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Heya,

thanks for this. Karma is currently no offical feature yet, but I'll have a look anyway.

Thanks

**Comment by rolfschmidt** [comment]
feature got dropped, closed (https://github.com/zammad/zammad/commit/fb1ee83126d4fb6f071f6005a004b91b0219ee6a).
