### ISSUE TITLE
Zendesk import fails due import of (too long) ticket description as (unused) note

### ISSUE THREAD

**Issue by MouettE-SC** [zammad/zammad#2538]
### Infos:

* Used Zammad version: 2.10
* Installation method (source, package, ..): source
* Operating system: debian stretch
* Database + version: postgresql 11.2-1.pgdg90+1
* Elasticsearch version: 5.6.16
* Browser + version: Vivaldi 2.4

### Expected behavior:

* Import of zendesk tickets from a small instance (see screenshots)

### Actual behavior:

* The import fails on the second ticket (see screenshot and logs.).
* I tried with another zendesk instance we own and we hit the same error message after a few tickets.

### Steps to reproduce the behavior:

* I've installed zammad from source using documentation without issues
* Once everything is installed and configured, I'm trying to import existing tickets from zendesk using API key and it fails on the second ticket.

I have attached the production.log file (replaced API and ticket contents with *). I can run tests if you need, apply patch or anything you need to help you identify the problem. Zammad looks like a great tool we'd like to give it a shot.

Thanks.

**Comment by MouettE-SC** [comment]
![2019-04-06 21_43_56-Window](https://user-images.githubusercontent.com/8431184/55677484-90508900-58b6-11e9-93f4-fd3d0d61b884.png)
[production.log](https://github.com/zammad/zammad/files/3051112/production.log)

**Comment by thorsteneckel** [comment]
Hi @MouettE-SC - thanks for your report. I can see two issues here: The first one is that some Zendesk Ticket attribute value is too long for one database column. Unfortunately I can't see which one it is from the logs. This results in an DB error which prevents the ticket from getting created:
```
W, [2019-04-06T21:35:26.518412 #16178-47247242316940]  WARN -- : WARNING: cut string because of database length Ticket.note(250 but is 263:****
****
E, [2019-04-06T21:35:26.528484 #16178-47247242316940] ERROR -- : PG::StringDataRightTruncation: ERROR:  value too long for type character varying(250)
: INSERT INTO "tickets" ("id", "group_id", "priority_id", "state_id", "number", "title", "owner_id", "customer_id", "note", "create_article_type_id", "create_article_sender_id", "updated_by_id", "created_by_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING "id" (ActiveRecord::ValueTooLong)
```

Then the second issue happens: The Import logic continues and expects the Ticket to be created and some logic relying on the ticket fails:

```
E, [2019-04-06T21:35:27.201706 #16178-47247242316940] ERROR -- : undefined method `id' for nil:NilClass (NoMethodError)
/opt/zammad/lib/sequencer/unit/import/zendesk/ticket/comment/mapping.rb:18:in `block in process'
```

Could you please get in touch with us via support at zammad.com and refer to this issue and me? I'd like to investigate into the first issue before we can resolve it and I'd like to discuss some relevant information privately. We will then share the results and steps taken here afterwards.

Thanks!

**Comment by MouettE-SC** [comment]
Hello @thorsteneckel sure, I will do that. Thanks !

**Comment by MouettE-SC** [comment]
Ticket #1041169 opened.

**Comment by thorsteneckel** [comment]
So the second issue here is that the [HTML sanitizer callbacks](https://github.com/zammad/zammad/blob/develop/app/models/concerns/checks_html_sanitized.rb) run after the [instance attributes get cutted for getting inserted into the DB](https://github.com/zammad/zammad/blob/develop/app/models/application_model/checks_attribute_values_and_length.rb) (inverted callback registration order: Model, ApplicationModel).

Possible solution that needs to get discussed and tested: Check if it is possible to move the HTML sanitization to a `before_save` hook.

**Comment by MohammedAlsayed** [comment]
Dear @thorsteneckel ,

I'm facing the same issue when importing from Zendesk. Could you please advise?

**Comment by thorsteneckel** [comment]
Hi @MohammedAlsayed - There is currently no verified way of working around this. You could try to change the [`before_create` and `before_update` lines](https://github.com/zammad/zammad/blob/e907c13cbe2b9758d40238cb9c337ba2a47f2272/app/models/concerns/checks_html_sanitized.rb#L6-L7) to `before_save`:

```diff
diff --git a/app/models/concerns/checks_html_sanitized.rb b/app/models/concerns/checks_html_sanitized.rb
index 147125a8e..e130bb41a 100644
--- a/app/models/concerns/checks_html_sanitized.rb
+++ b/app/models/concerns/checks_html_sanitized.rb
@@ -3,8 +3,7 @@ module ChecksHtmlSanitized
   extend ActiveSupport::Concern
 
   included do
-    before_create :sanitized_html_attributes
-    before_update :sanitized_html_attributes
+    before_save :sanitized_html_attributes
   end
 
   def sanitized_html_attributes
```

Make sure to revert your changes after the import hopefully finished successfully 🤞This will ensure that your system behaves in a verified way. 

Please share your results with us 👍

**Comment by MohammedAlsayed** [comment]
Hi @thorsteneckel, 

Thanks for your help!. 

I tried previously by changing the type of the "note" column in the "tickets" table from "char(250)" to "text", and the migration finished successfully. I'm wondering why the type is char(250) where the "note" column's value in most cases has more than 250 characters. I did the following steps from Postgres command:

`ALTER TABLE tickets`
`ALTER COLUMN note TYPE text;`

However, will this change affect the application?

I also tried your changes to the code and the migration finished successfully. But I found multiple warning messages in the production.log file similar to this: "WARN -- : WARNING: cut string because of database length Ticket.note(250 but is 1374"

Another question, does Zammad support importing tickets thru XML or CSV files?

**Comment by thorsteneckel** [comment]
Hi @MohammedAlsayed - thanks for your follow up. From our experience the 250 chars in the notes attribute are usually enough. We only faced issues with the size when importing from zendesk :) 

Good to hear that the proposed workaround does the job. This will give us some time until we fully resolve the issue.

Regarding your question. [Yes, it's possible to import tickets via CSV](https://community.zammad.org/t/how-to-import-tickets-from-other-helpdesk-service/1297/2). Please refer for technical questions to [the community](https://community.zammad.org/) so we can keep the focus on issues on the GitHub issue tracker 👍

**Comment by thorsteneckel** [comment]
Update (from Ticket #1043974): This also affects other imports as e.g. the currently beta-tested Freshdesk import.

You can reproduce it by running:
`Ticket::Article.create(FactoryBot.attributes_for(:ticket_article).merge(body: "<span style='font-family:\"Segoe UI Emoji\",sans-serif;'>&#128522;</span>", content_type: "text/html", ticket_id: 1))`

Fails with:
```
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\x8A</...' for column 'body' at row 1: INSERT INTO `ticket_articles` (`ticket_id`, `type_id`, `sender_id`, `from`, `to`, `subject`, `message_id`, `message_id_md5`, `content_type`, `body`, `updated_by_id`, `created_by_id`, `created_at`, `updated_at`) VALUES (1, 1, 2, 'factory-customer-1@example.com', 'factory-customer-1@example.com', 'factory article', 'factory@id_com_1', '7029f24ef062eb878cafb4001fe4a061', 'text/html', '<span>😊</span>', 1, 1, '2019-06-17 14:50:39.509000', '2019-06-17 14:50:39.509000')
from /ws/zammad/vendor/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
Caused by Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\x8A</...' for column 'body' at row 1
from /ws/zammad/vendor/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
```

[This workaround](https://github.com/zammad/zammad/issues/2538#issuecomment-495990729) resolves it.

**Comment by savasadar** [comment]
> Hi @thorsteneckel,
> 
> Thanks for your help!.
> 
> I tried previously by changing the type of the "note" column in the "tickets" table from "char(250)" to "text", and the migration finished successfully. I'm wondering why the type is char(250) where the "note" column's value in most cases has more than 250 characters. I did the following steps from Postgres command:
> 
> `ALTER TABLE tickets`
> `ALTER COLUMN note TYPE text;`
> 
> However, will this change affect the application?
> 
> I also tried your changes to the code and the migration finished successfully. But I found multiple warning messages in the production.log file similar to this: "WARN -- : WARNING: cut string because of database length Ticket.note(250 but is 1374"
> 
> Another question, does Zammad support importing tickets thru XML or CSV files?

How to update table? I am new in postresql and linux, Could you say steps how to do that?

**Comment by MrGeneration** [comment]
@savasadar please don't recycle / hijack already closed issues.
As you're having a rather technical question, please consult the Zammad community for this: https://community.zammad.org

Limitting conversation to reduce noise on this repository.
