### ISSUE TITLE
User as agent and admin

### ISSUE THREAD

**Issue by Pupp3tm4st3r** [zammad/zammad#254]
Hi there,

I´ve created two users (besides the admin user) on a fresh installed zammad instance (centos repo and docker image tested). These users were created as admin and as agent.

When logging in as one of the new user, the wizard starts up and after that the user wants to create a test ticket (first steps). The ticket will be created, but is not accessible for the user.

Is it impossible/not by design to create a new user as agent and admin?

Thanks in advance
Simon

**Comment by thorsteneckel** [comment]
Hi Simon,

You can define an User as Admin and regular Agent like this:
![bildschirmfoto 2016-10-27 um 15 03 13](https://cloud.githubusercontent.com/assets/3873515/19768167/a87f5fca-9c56-11e6-8300-f18c0ca8d20f.png)

However, the access to Tickets is defined by the Group the Ticket is assigned to. An User has to be in the same Group as the Ticket.

Hope that helps?

**Comment by Pupp3tm4st3r** [comment]
Hi Thorsten,

in basic configuration (without extra groups) I could change this - but then the test-ticket created by the wizard was inaccessible (tried it with 3 users with the roles admin and agent).

**Comment by MorrisJobke** [comment]
> An User has to be in the same Group as the Ticket.

How are users added to a group? I can't find anything in the web UI 😢

**Comment by MorrisJobke** [comment]
> How are users added to a group? I can't find anything in the web UI 😢

Ah - this seems to be a bug when there is no additional group added: https://github.com/zammad/zammad/issues/249

**Comment by thorsteneckel** [comment]
Sorry for the late response. Yes - it was fixed in the releases last week. Closing for now.
