### ISSUE TITLE
Can't remove auto assignment timeout

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2544]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: tested on Chrome, Firefox and Safari
* Ticket-ID: #1041338, #1079095

### Expected behavior:

If you decide to not further use the autoassignment timeout, you simply delete the number out to disable this feature. After saving the feature is disabled for the desired group.

### Actual behavior:

When deleting the assignment timeout value, it won't be removed from database after applying the setting. It does not matter if other values are changed as well. You can only disable this function via command line at the moment:

```
irb(main):001:0> g=Group.find(1)
=> #<Group id: 1, signature_id: 1, email_address_id: nil, name: "Users", assignment_timeout: nil, follow_up_possible: "yes", follow_up_assignment: true, active: true, note: "Standard Group/Pool for Tickets.", updated_by_id: 1, created_by_id: 1, created_at: "2018-12-17 16:58:17", updated_at: "2018-12-28 08:51:39">
irb(main):002:0> g.assignment_timeout=""
=> ""
irb(main):003:0> g.save!
Group.find(1) notify UPDATED 2018-12-28 08:51:39 UTC
=> true
```

### Steps to reproduce the behavior:

* add any value to autoassignment time out (e.g. 0, 120 - really doesn't matter)
* save the value
* reopen the group you just edited and delete the number so the field gets empty
* save the group settings and reopen them (value is back)

### Screencast

![group-assignment-timeout-broken-firefox](https://user-images.githubusercontent.com/6549061/56051273-5c5de380-5d4e-11e9-8add-f3cc65387519.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mfevzikorkutata** [comment]
Hi,

I had the same issue for the "version 4.1.x" and while researching came to this page. But, could not found any work around. 

Finally, I found the workaround solution. Running below command from Zammad console removes the "assignment timeout" value for the group settings.


```bash
Group.find_by(name: 'Customers').update!(assignment_timeout: '')
```

**Comment by MrGeneration** [comment]
Please don't hijack issues with technical questions, consult the community if you have to.

**Comment by mfevzikorkutata** [comment]
> Please don't hijack issues with technical questions, consult the community if you have to.

This is the only solution for this case and I have shared the workaround solution for somebody else if he or she is having the same problem. Your warning is totally unnecessary. There is no question in my post. Regards...

**Comment by rolfschmidt** [comment]
> 
> 
> Hi,
> 
> I had the same issue for the "version 4.1.x" and while researching came to this page. But, could not found any work around.
> 
> Finally, I found the workaround solution. Running below command from Zammad console removes the "assignment timeout" value for the group settings.
> 
> ```shell
> Group.find_by(name: 'Customers').update!(assignment_timeout: '')
> ```

i think i forgot to backport this, there is no reason to not do so. I will backport it today for 4.1.
