### ISSUE TITLE
Elastic Search disabled : need to rebuild index at each update

### ISSUE THREAD

**Issue by vsurrel** [zammad/zammad#2545]
After each upgrade (i'm using official deb repositories), I need to run this command : 

zammad run rails r "Setting.set('es_url', '')" && zammad run rake searchindex:rebuild

If I don't do so, the search feature of Zammad doesn't work after the upgrade. My installation has disabled ES since I have a really small amount of ticket (<30/week) and ES is really hungry of RAM.

* Zammad : 2.9.0
* Webserver : nginx/1.10.3
* database : postgresql 9.6
* elasticsearch-version: none
* Browser : chromium 74

**Comment by thorsteneckel** [comment]
Hi @vsurrel - thanks for reaching out. Can you please fill out the complete issue template. These information are mandatory as we need them to properly resolve the issue. Otherwise I have to close the issue.

@monotek what do you think about this? Sounds like a valid use case to me: Don't configure the ES on updates if it wasn't configured beforehand.

**Comment by vsurrel** [comment]
I'll fill the template at the next update !

**Comment by martini** [comment]
Just  a note from my side:

> zammad run rails r "Setting.set('es_url', '')" && zammad run rake searchindex:rebuild

`zammad run rails r "Setting.set('es_url', '')"` will disable elasticsearch integration. So a `zammad run rake searchindex:rebuild` makes no sense then.

@vsurrel a full description how to reproduce would be good (the issue template would be fine).

By the way: I do not have issue by Zammad upgrades via debian/rpm packages with elasticsearch. This is working on my side fine.

**Comment by martini** [comment]
Ah. Now I got it, you do not use elasticsearch at all. Sorry, I did not see that before. I have no feedback about this use case. I only with with elasticsearch (even on small systems).

**Comment by monotek** [comment]
I think you just should set anything else as ''.

See: https://github.com/zammad/zammad/blob/develop/contrib/packager.io/functions#L233

If '' is set it will be replaced by: "http://127.0.0.1:9200"

@martini 
Imho we would need a disabled flag for elasticsearch instead of using no value to disable es.

**Comment by vsurrel** [comment]
As of today, I performed an update. Of course, it worked like a charm and I didn't did anything this time to disable ES configuration. Quick console output : 


`root@desk:~# zammad run rails r "Setting.get('es_url')"`
`root@desk:~# dpkg -s zammad | grep '^Version:'`
`Version: 2.9.0-1554805410.8c7abf98.stretch`
`root@desk:~# apt upgrade`
`[snip]`
`Unpacking zammad (2.9.0-1558365959.533e6cb3.stretch) over (2.9.0-1554805410.8c7abf98.stretch) ...`
`[snip]`
`Setting up zammad (2.9.0-1558365959.533e6cb3.stretch) ...`
`[snip]`
`root@desk:~# zammad run rails r "Setting.get('es_url')"`
`root@desk:~#`

**Comment by MrGeneration** [comment]
`zammad run rails r "Setting.get('es_url')"` will not give any output and thus is useless in this case.
Please run `zammad run rails r "p Setting.get('es_url')"` to make it usefull :)

Also, please update your first post with a complete issue template:
```
* Zammad-Version: 
* Webserver & it's version: 
* database & it's version:
* elasticsearch-version:
*Browser
```

Another hint (which why I'm still absolutely unsure how to treat this issue...) elasticsearch is *mandatory*.
See: https://docs.zammad.org/en/latest/prerequisites-software.html

**Comment by vsurrel** [comment]
I've juste upgraded from 2.9.0 to 3.0.0 using official apt repositories.

Before the upgrade, `zammad run rails r "p Setting.get('es_url')"` returns an empty string, as I configured it.

After the apt upgrade, it reverts to default value `"http://127.0.0.1:9200"`.

I disabled it again and zammad works again like a charm without ES. It might be indicated as "mandatory", but I want to disable ES as it is a heavy

**Comment by MrGeneration** [comment]
André currently has no free ressources to do this.
We currently have other heavy task on our list.

MergeRequests are welcome - if not, this will take some time.
 
This is now related to: https://github.com/zammad/zammad-documentation/issues/82
We'll remove the "mandatory" part of elasticsearch.

**Comment by MrGeneration** [comment]
Mandatory remark has been removed from our documentation.
Todo is optimizing our upgrade script.

**Comment by MrGeneration** [comment]
I believe that this has been fixed indirectly with https://github.com/zammad/zammad/issues/2400 (this would be a duplicate then).
Can you please check / provide feedback if this still happens to you?

For further reference, this is the commit I believe that fixed the issue:
https://github.com/zammad/zammad/commit/a9dd93796844ca3a5d98743e542caf34e7d3c251

**Comment by vsurrel** [comment]
I installed an ES instance since then, so I can't help you on this point !

**Comment by MrGeneration** [comment]
Ooookaaay, so we'll expect everything to be fine.
Thanks for the feedback. :)
