### ISSUE TITLE
Exchange and LDAP sync update same user(s) all over again

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#2549]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Exchange contacts should be skipped if the corresponding Zammad User is also synced by an active LDAP sync.

### Actual behavior:

* LDAP and Exchange sync the same User(s) which causes endless updates of the users because of differing attributes (e.g. login).

### Steps to reproduce the behavior:

* Configure LDAP and Exchange sync which contain the same User (e.g. by email).

### Fix insights:

There should be a new Sequencer Unit that checks if an existing/found `instance` was synced by an active LDAP integration. If so the further processing of the Sequence should be `skipped` by setting the `action` to that.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Closing this issue in favor for #2864  which is more detailed than this issue.
