### ISSUE TITLE
SMTP Exchange server problem.

### ISSUE THREAD

**Issue by chrgeo** [zammad/zammad#255]
Hi,
First of all I like zammad, nice software.

I have an issue regarding connectivity to our
Exchange 2010 server. I tried a lot of different combinations
to connect to our mail server but receive almost always error messages.
I think it has something to do with our port selection, is there way
to change the SMTP port back from default?
If yes where can I find it.

Thanks
Chris

**Comment by monotek** [comment]
There is already a pach avialöable for exchange servers with ssl. 
Have alook @  https://github.com/zammad/zammad/issues/240

**Comment by thorsteneckel** [comment]
Hi @chrgeo - please reopen if it's another error.
