### ISSUE TITLE
Reply-to header ignored if from contains a system address

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#2551]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): source
* Operating system: CentOS 7
* Database + version: PostgreSQL
* Elasticsearch version: n.a.
* Browser + version: Chrome

### Expected behavior:

* The address from the Reply-To header is used as the To address when replying.

### Actual behavior:

* No address is used if a Reply-To header exists and the From is a system address.

### Steps to reproduce the behavior:

* Send an e-mail from a **system address** with any address in the Reply-to header and reply to the first article of the generated ticket. Then nobody is used in the to field.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
@thorsteneckel are you able to reproduce this in current `develop`?

**Comment by thorsteneckel** [comment]
I haven't checked. Please close the issue if you can't. @rkaldung please re-open if you can ;)

**Comment by martini** [comment]
@mantas Any issues on how to reproduce?

JFI (i dont know if you already know it): You can pipe email into Zammad on comand line using `cat test/data/mail/mail001.box | rails r 'Channel::Driver::MailStdin.new'`

So you can create test emails quite easy. If you have issues, let me know.

**Comment by mantas** [comment]
@martini I tried various `From:` values, but none seem to trigger this issue. `example@localhost`, `user@domain.local` etc. Do you remember what `From:` email you used to verify this?

**Comment by MrGeneration** [comment]
I can still verify it
![image](https://user-images.githubusercontent.com/6549061/122429025-bbed5480-cf92-11eb-88b6-83bfadb1b870.png)


You have to configure a mail channel which does fit the from address as `EmailAddress`.

Edit: `erza` is my systems email address.

**Comment by mantas** [comment]
No worries, I can verify it now
