### ISSUE TITLE
Twitter integration: switching retweets *off* suddenly spawns hundreds of retweet tickets

### ISSUE THREAD

**Issue by rixx** [zammad/zammad#2556]
### Infos:

* Used Zammad version: 2.8.0
* Installation method (source, package, ..): source
* Operating system: Linux
* Database + version: Postgres 11.1
* Elasticsearch version: 5.6.13
* Browser + version: any

### Expected behavior:

* Turning retweets off in the Twitter integration will result in no further retweet tickets.

### Actual behavior:

* Suddenly, ~120 retweet tickets were newly created.

### Steps to reproduce the behavior:

* Run twitter integration with retweets turned on for a bit. Turn it off. Wait an hour(?).

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please complete the issue template (information in "Infos" are missing!)
Otherwise I can't start the verification process.

**Comment by rixx** [comment]
Updated.

**Comment by MrGeneration** [comment]
Sorry but I can't reproduce this.

Can you please run the following on a Zammad console?

```
Channel.where(area: 'Twitter::Account').pluck(:options)
```

The values that I'm especially interested in are:

* track_retweets
* and the output of Channel.where(area: 'Twitter::Account').pluck(:status_in, :status_out)

If you can't reproduce it anymore either, I'd be happy about this feedback as well. :)

**Comment by rixx** [comment]
Sorry, but I'm not looking to reproduce the experience – closing all those tickets was a bit of a hassle. Let's assume it was fixed, I guess.
