### ISSUE TITLE
How to change running port? Why use Port 3001?

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#256]
Installed zammad on a fresh centos7 machine. It starts with port 3000. Where do i have to change the port? Would like to run in on standard 80 and 443.

Is there a reason for running it on port 3001 by default?

**Comment by monotek** [comment]
Yes, the reason is that only root can openj port 80 and Zammad should be run as non root user.

Use a reverse proxy like Nginx or Apache to rediret from port 80 or better 443 to 3000.

Proxy config fpr Nginx can be found here: https://github.com/zammad/zammad/blob/develop/contrib/nginx/sites-available/zammad.conf

**Comment by martini** [comment]
Usually your start you rails application server on e. g. 3001. For 80+443 you use normally nginx.

PS: At Zammad side you have 2 processes. The app server (per default port 3000) and the web socket server (per default port 6042). 

With nginx you bind on 80+443, /assets will be directly served from document root (really fast, nginx is reading it directly from fs), application requests are forwarded to Zammad (port 3000) and /ws requests are routed internally to port 6042.

**Comment by Julian0o** [comment]
@monotek i installed nginx and mapped the zammad.conf file. But i get a this error in zammad.error.log

The nginx status page shows `502 Bad Gateway`

`[crit] 14873#0: *1 connect() to [::1]:3000 failed (13: Permission denied) while connecting to upstream, client: xxxx, server: zammad.example.com, request: "GET / HTTP/1.1", upstr
eam: "http://[::1]:3000/", host: "yyyy""`

`[error] 14873#0: *1 no live upstreams while connecting to upstream, client: xxxx, server: zammad.example.com, request: "GET / HTTP/1.1", upstream: "http://zammad/", host: "yyyy"`

**Comment by monotek** [comment]
You have to change zammad.example.com to your domain.
Please also check if your Zammad server runs on port 3001 (like in the Docker image) or on port 3000.
If port 3001 you have to change this in nginx.conf too.

**Comment by nimeshkd** [comment]
if you want to run zammad on different Port(81) other than 80. below changes are required
1)Dockerfile
 Change EXPOSE 80 to EXPOSE 81

2)Run docker images using below command

sudo docker run -it -p 81:80  <imagename> zammad

Output : you can get zammad using URL : http://localhost:81
