### ISSUE TITLE
Switching groups, get "oops,... you have insufficient rights to open this"

### ISSUE THREAD

**Issue by GrexAut** [zammad/zammad#2563]
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): apt package
* Operating system: Ubuntu 18.04
* Database + version: MariaDB 10.2
* Elasticsearch version: 5.6.16
* Browser + version: FireFox 66.0.4 (64-Bit)

### Expected behavior:
Change group of ticket to other group, where agents do not have read permissions, only create and change.
*

### Actual behavior:
After update the group, it appears "Opps.. I'm sorry, but you have insufficient rights to open this Ticket.", and if I close ticket from left menu, I get prompt with "Discard Changes"

I think the problem is, it should close instantly after update. And sometimes it happened, that my comment has tried to post, after change the group, so the comment was lost.
*

### Steps to reproduce the behavior:
Create group A and group B.
Create two roles, like role A and role B, and set settings at groups:

Role A:
[x] agent - Access to Agent Tickets based on Group Access
Group A: [x]FULL
Group B: [x] CREATE, [x] CHANGE, [x] OVERVIEW

Now switch with user has role a, from Group A to Group B.
*

**Comment by MrGeneration** [comment]
You're correct, if you have no rights (no matter if creating or switching to a group you have no rights in).

Just a side note: It technically makes no sense to allow changing tickets, when you can't read them. :-)

**Comment by GrexAut** [comment]
Hi,

yes you are correct, but we are using zammad not as customer to agents, we are using "agents to agents", and we would like to give the ticket to other instances inside our company (second level support). The creator of the ticket, should not have rights anymore, if first level support gave the ticket to the second level support, because there can be some information (comments) in future, that the first level support should not see anymore. And maybe the ticket from second level support goes to third level support, and so on...

**Comment by MrGeneration** [comment]
Closing this as a duplicate for #967 as this covers this issue (I extended the "close tab feature" part) :-)
