### ISSUE TITLE
LDAP-Import 500 user limit?

### ISSUE THREAD

**Issue by DS-networks** [zammad/zammad#2564]
The LDAP-Import is hanging since yesterday
![zammadldap](https://cloud.githubusercontent.com/assets/28089775/25476002/ed7caa62-2b38-11e7-921d-336269bae158.PNG)
Is it possible to stop / restart the import?

_Originally posted by @SGVubmluZ0cK in https://github.com/zammad/zammad/issues/350#issuecomment-297657063_

Hi,
is there a limit of 500 users somewhere?
We also have the problem that just 500 users are detected/synced.

**Comment by DS-networks** [comment]
It is a limit of openldap:
https://www.openldap.org/doc/admin24/limits.html
Default limit is 500.
Adding the olcLimits attribute in cn=config olcDatabase for the zammad sync user resolves the issue.

**Comment by MrGeneration** [comment]
Glad you found the solution.
For the next time, as this was a technical question, please refer to our community: https://community.zammad.org :-)

Bests!
