### ISSUE TITLE
Tags with comma not working properly

### ISSUE THREAD

**Issue by GrexAut** [zammad/zammad#2566]
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): apt package
* Operating system: Ubuntu 18.04
* Database + version: MariaDB 10.2
* Elasticsearch version: 5.6.16
* Browser + version: 66.0.4 (64-Bit)

### Expected behavior:
Using existing tags with comma "," like "abcdefgh, 123" add at tickets.
*

### Actual behavior:
If I try to add the existing tag "abcdefgh, 123" to a ticket, a new tag will be generated with "abcdefgh" and the ticket is tagged with "abcdefgh" instead of "abcdefgh, 123"

*

### Steps to reproduce the behavior:
Go to admin panel, Tags => add tag "abcdefgh, 123"
Go to a ticket, and try using the tag "abcdefgh, 123", you will get a new tag and tagged with "abcdefgh"
*

**Comment by dennykorsukewitz** [comment]
Hi @GrexAut, 

this works as designed. 
Currently tags are separated with a [comma](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/widget/tag.coffee#L91) while adding.

**Comment by dennykorsukewitz** [comment]
Hi @GrexAut 

After a short discussion with the developers, this handling has several advantages.

- poweruser can thus add several tags at the same time.
- using x-zammad-ticket-tags (mail headers) with multiple tags.

We recommend separating the tags with "-" or other characters.

**Comment by MrGeneration** [comment]
Just as small information:
I've added #2724 to address the backend handling of tags, as this is the real issue here. So we get that fixed. ;)
