### ISSUE TITLE
Define default "stay on tab" / "close tab" behavior

### ISSUE THREAD

**Issue by alexbrueckel** [zammad/zammad#257]
### Infos:
*This post has been edited by @MrGeneration to meet our requirenments and extend the initial request*

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any 
* Database + version: any
* Elasticsearch version: any 
* Browser + version: any
* Ticket-ID: #1030961, #1048466, #1058963, #1081289

### Current behavior:

You currently can choose, if you want to keep a tab open on the next update or not. This selection is reset with every ticket you open. There is no default value.

![image](https://user-images.githubusercontent.com/6549061/57616516-9c4afd00-757e-11e9-93e6-4dd45c46cf34.png)

### Desired behavior:

Zammad should hold a option to configure the default tab behaviour (global option for admin). This should  include the following options:

* stay on tab [default setting] (just like now, do exactly nothing with the tab)
* close tab on update (close the tab on update, just like now)
* close tab on update if closed (close tab only if the ticket gets closed)

Especially the third option is a rather wanted bevahior by our community.

To round this up, this setting can be overwritten manually by the agent.
This is not meant to be a agent option, but a possibility to do so inside of each ticket. 
Just like it's right now, the chosen tab-behavior will be reset to the default on each ticket.

Reason for this change is, that many organizations want to close the ticket tab after updating, as keeping the tab is not relevant for the agents work.

**Comment by Julian0o** [comment]
+1

**Comment by MrGeneration** [comment]
Just as follow up:
We created a new enhancement issue on, as we'd like to have this functionality a bit broader.
To ensure to keep a specific overview and to meet our requirenments, I edited and updated your first post.

I hope you bear with me. :-)

**Comment by chris-82** [comment]
Hi there. Is this still an issue or an already implemented feature? I was just struggeling to find out how to set "close tab" as default value.

**Comment by MrGeneration** [comment]
The state of this enhancement issue is still "open".
This hasn't been adressed as of yet.

Please note that we do not provide any ETAs on enhancements or bug fixes in general.
Also, to reduce the noise on this repository (helps us to focus 💪 ) and as there weren't any further use full contributions on this, I'm limiting this to contributor conversation only.

This is nothing against you personally!
