### ISSUE TITLE
Uninstallable on Debian 9 due to key constraint

### ISSUE THREAD

**Issue by Signum** [zammad/zammad#2575]
### Infos:

* Used Zammad version: 2.9.0-1556788014.16325a31.stretch
* Installation method (source, package, ..): Debian package
* Operating system: Debian Stretch/9
* Database + version: PostgreSQL 9.6
* Elasticsearch version: 5.6.16
* Browser + version: Firefox 66.0.3

### Expected behavior:

* "apt install zammad" installs a working Zammad instance

### Actual behavior:

* Installations fails at the "translations" stage.

```
# Enabling Zammad on boot
# Stopping Zammad
# database.yml found. Updating db...
# Updating translations...
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.6.2/lib/active_record/connection_adapters/postgresql_adapter.rb:616:in `async_exec': PG::ForeignKeyViolation: ERROR:  insert or update on table "translations" violates foreign key constraint "fk_rails_d6e6d9635d" (ActiveRecord::InvalidForeignKey)
DETAIL:  Key (created_by_id)=(1) is not present in table "users".
: INSERT INTO "translations" ("id","locale","source","target","targe…
```

I found two foreign key constraints in the "translations" table:

```
Foreign-key constraints:
    "fk_rails_8cb1380a17" FOREIGN KEY (updated_by_id) REFERENCES users(id)
    "fk_rails_d6e6d9635d" FOREIGN KEY (created_by_id) REFERENCES users(id)
```

The second one is causing trouble here. I assume that it cannot work because the admin user has not been created at this stage.

I could work around this problem by removing the foreign key constraint:

```
alter table translations drop CONSTRAINT fk_rails_d6e6d9635d ;
```

Then reconfigure the package:

```
dpkg-reconfigure zammad
```

This makes the installation complete:

```
# Enabling Zammad on boot
# Stopping Zammad
# database.yml found. Updating db...
# Updating translations...
# Configuring Elasticsearch...
-> removing [ingest-attachment]...
-> Downloading ingest-attachment from elastic
```

### Steps to reproduce the behavior:

* Get a Debian Stretch system
* Follow the installations instructions for installing Zammad on Debian 9

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Just to double check: This is a fresh install of Zammad without an existing Zammad-Database before?

**Comment by Signum** [comment]
> Just to double check: This is a fresh install of Zammad without an existing Zammad-Database before?

Correct. I deliberately dropped the database before trying a second time and started over.

**Comment by Signum** [comment]
The workaround I described does not completely install Zammad by the way. I dropped the key constraint, ran the INSERT on the translations table again and at least ran through the basic installer.

However the installation throws warnings at:

```
/opt/zammad/app/models/setting.rb:37:in `set': Can't find config setting 'es_url' (RuntimeError)
```

This issue is described in other places and there has been no workaround for it yet. So it seems that I am stuck now. Let me know how I can help track down the issue. Currently it appears that Zammad is generally uninstallable on Debian 9.

**Comment by Signum** [comment]
At this stage I could run "zammad run rake db:seed" and finally ended up with a working instance. Phew…

**Comment by MrGeneration** [comment]
I found some time to test this on a fresh install of Debian 9 and could not verify this.
I'm sorry - maybe this was a temporary problem.

**Comment by pulecp** [comment]
@MrGeneration Could you re-open this issue? I see the same on Centos7 with PostgreSQL 10. 

You can reproduce it in Vagrant (https://github.com/zammad/zammad-vagrant) when you install PostgreSQL 10 before zammad package in _.provision/bootstrap.sh_ by

```
rpm -Uvh https://yum.postgresql.org/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
yum -y install postgresql10-server
```
