### ISSUE TITLE
SLA fails to set close_in_min and close_diff_in_min

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2579]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1043304, #1062531, #1078017

### Expected behavior:

When enabling solution time within a SLA, Zammad will calculate the values `close_in_min` and `close_diff_in_min` during closing a ticket.

### Actual behavior:

With solution time enabled, Zammad will not set  `close_in_min` and `close_diff_in_min` values, no matter on how long you wait or in what constellation you set the SLA configuration. This causes `close_diff_in_min` to be never set.

### Further notes:

`close_in_min` should always be set on closing, especially when using SLA in my opinion. Probably affected line: 
https://github.com/zammad/zammad/blob/160b5211161d7616e57cbb8c6230ca46f579dbfb/app/models/ticket/escalation.rb#L224

### Steps to reproduce the behavior:

* Enable SLA with resolving time
* Create a new ticket that's affected by your SLA filter
* work a bit on it (notes, call notes)
* close the ticket ²

² It does not matter if you close the ticket without any note, an internal note or even a mail. The result is always the same.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Update: This also affects first response in min :x

**Comment by thorsteneckel** [comment]
You can also reproduce it this way:

- Create a SLA that matches all Tickets (e.g. by selecting all Ticket States)
- Create a new Ticket
- See that the SLA applies ("escalates in X" in the title region of the Ticket detail view)
- Close the Ticket

Check the record via the Rails console:
```ruby
Ticket.last.close_in_min
=> nil
```

**Comment by arpagon** [comment]
Friendly reminder, this bug is still a thing.  I would love to hear more details.

**Comment by MrGeneration** [comment]
Please have a look at the milestone, it says 3.6~

**Comment by rogedelgado** [comment]
Hello there!

Is there any update on this? We recently move to zammad (great software by the way) and we are trying to get some metrics and as you can imagine, this is affecting us. 

Thanks for all the effort in build this amazing tool

**Comment by mantas** [comment]
Hi @rogedelgado 

We're internally testing a fix for this issue. It'll probably make it to the next release in late January/early February.

**Comment by rogedelgado** [comment]
Hi @mantas, good news indeed!

We look forward for the new release!

**Comment by GaiaRossi** [comment]
Hello there!

Are there any updates?

Thanks! :-)

**Comment by crnfpp** [comment]
Hi! Having the same issues with the most recent Zammad version.

**Comment by MrGeneration** [comment]
Please don't hijack old issues. Open new issues if you're sure that it is a bug and not a technical question.
