### ISSUE TITLE
Opening search from external does not trigger search endpoint

### ISSUE THREAD

**Issue by PhilippSchreiber** [zammad/zammad#2580]
### Infos:

* Used Zammad version: 2.10.x (DEV channel)
* Installation method (source, package, ..): ?
* Operating system: ubuntu0.18.04.1
* Database + version: Mysql 5.7.26
* Elasticsearch version: 5.6.16
* Browser + version: Google Chrome 74.0.3729.131

### Expected behavior:

* When I open a link from an external tool (in our example our CRM) to the search page with parameters in the URL it should actually perform the search. Example URL: https:://YOU-ZAMMAD-URL/#search/SEARCH-TERM%20OR%20article.from%3A"email%40example.com"

### Actual behavior:

* The articles of the previous search are displayed and you have to focus the search field and hit return.

### Steps to reproduce the behavior:

* As described in the behaviours.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry but that's rather a technical question. :-)
You're trying to use a invalid endpoint, if you're using the right one it works (just tested).

Your endpoint is `/api/v1/search` - you want to append `?query={mysuperduperquery}` and you should receive results right away. :-)



![image](https://user-images.githubusercontent.com/6549061/58100312-abb0f280-7bdd-11e9-8bd6-918456557067.png)

**Comment by PhilippSchreiber** [comment]
Nope, sorry. I am not talking about using the API directly but to pass parameters to the Zammad Frontend. And in the frontend there is a bug so it does not trigger the API request correctly. Please reopen.

**Comment by MrGeneration** [comment]
For your information:
This currently works as designed, but we agree that this can and should be enhanced.

**Comment by rolfschmidt** [comment]
I can't reproduce this behaviour. For me the search will be triggered on load of the page. Please provide more information if this issue still occurs to you in stable versions of zammad.
