### ISSUE TITLE
Incorrect modification dates in ticket overviews

### ISSUE THREAD

**Issue by raphaelm** [zammad/zammad#2581]
### Infos:

* Used Zammad version: 2.9.0-1556788014.16325a31.stretch
* Installation method (source, package, ..): Debian package
* Operating system: Debian 9
* Database + version: Postgres 9.6+181+deb9u2
* Elasticsearch version: 5.6.16

### Expected behavior:

* In all overviews, all tickets are shown with their correct date.

### Actual behavior:

* In *some* of our overviews, *every* ticket older than a day is always shown as "changed X hours ago", with X being a number <= 23 or "changed just now" **no matter when it was changed**.

![2019-05-21-133738_278x387_scrot](https://user-images.githubusercontent.com/64280/58093051-ec087480-7bcd-11e9-98b2-1b3b4be060ac.png)
![2019-05-21-134107_184x389_scrot](https://user-images.githubusercontent.com/64280/58093161-3ee22c00-7bce-11e9-81ee-9598021c669c.png)

* The **History** views of the tickets do not show any action in the past 24 hours.

### Steps to reproduce the behavior:

* We have no idea, unfortunately. It just happens in some of our overviews that are ordered by last activity.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I'm very sure you have SLA enabled. This is a bug ( #2547 ) which has been solved yesterday.
It's also in stable, so you can update your Zammad - the issue should be gone then. :-)

**Comment by raphaelm** [comment]
Thanks a lot, we've upgraded to 2.9.0-1558365959.533e6cb3.stretch and will monitor the situation!
