### ISSUE TITLE
Supported elasticsearch versions are eol

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#2582]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): deb
* Operating system: ubuntu
* Database + version: mysql
* Elasticsearch version: 5.6
* Browser + version:

### Expected behavior:

Zammad supports a current es version

### Actual behavior:

* 5.6 and even 6.0 are end of life. Forcing users to use unmaintained versions is a security risk.

### Steps to reproduce the behavior:

* Install zammad

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @monotek - this is a duplicate of/additional information for #1688.

**Comment by monotek** [comment]
Ah, sorry. Wasn't able to find it as i thougt I had already opened that ticket 😁

**Comment by binaryfire** [comment]
Fantastic to hear elasticsearch 7 support is being worked on. Great work guys! We're running a couple of other apps that use v7 so we haven't been able to use our elasticsearch server with zammad yet. Looking forward to the new update :)

**Comment by monotek** [comment]
and there it is :sunglasses: 
https://github.com/zammad/zammad/commit/af9fcf456573bce851a0d7ff08c472dfc377b218
