### ISSUE TITLE
SMS gateway - error whiloe testing

### ISSUE THREAD

**Issue by casparflintstone** [zammad/zammad#2588]
### Infos:

* Used Zammad version:  2.9.x

* Installation method (source, package, ..):
* Operating system: Debian
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

Try to send SMS (Test)

### Actual behavior:

SMS gateway - error while testing
{"error":"\"\\xC3\" from ASCII-8BIT to UTF-8"}

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please fill in the missing information in the template, as other wise we can't verify the issue.
While you're at it, please also provide your production.log at the part where this happens (with traceback).

Edit: Maybe you should also tell us if you're testing notification or the channel and of course which provider you're using.

**Comment by MrGeneration** [comment]
Closing due to missing information.
