### ISSUE TITLE
Detail mode in ticket article view is incorrectly triggered when single-click de-selecting a text selection

### ISSUE THREAD

**Issue by SummerStorm** [zammad/zammad#2589]
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Firefox 66

### Expected behavior:

1. Open a ticket article view
2. Double-click a word to select it
3. Single-click the same word to de-select it. The article detail view **should not be activated**.  

### Actual behavior:

1. Open a ticket article view
2. Double-click a word to select it
3. Single-click the same word to de-select it. The article detail view **is incorrectly activated**: 

![58330020-43a91900-7e36-11e9-9e80-4f5050ebac13](https://user-images.githubusercontent.com/7030950/58331268-50942f80-7e6b-11e9-8c2e-dc131287a302.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martinvonwittich** [comment]
I've duplicated the `@elementContainsSelection` code from `toggleMeta` into `toggleMetaWithDelay`:

``` diff
zammad@martin.mein-iserv.de ~ (2586-increase-doubleclick-timeout) % git diff
diff --git a/app/assets/javascripts/app/controllers/ticket_zoom/article_view.coffee b/app/assets/javascripts/app/controllers/ticket_zoom/article_view.coffee
index b13437200..5ca46e176 100644
--- a/app/assets/javascripts/app/controllers/ticket_zoom/article_view.coffee
+++ b/app/assets/javascripts/app/controllers/ticket_zoom/article_view.coffee
@@ -293,6 +293,11 @@ class ArticleViewItem extends App.ObserverController
     # by adding a delay to the toggle
     delay = 300

+    article = $(e.target).closest('.ticket-article-item')
+    if @elementContainsSelection(article.get(0))
+      @stopPropagation(e)
+      return false
+
     if @lastClick and +new Date - @lastClick < delay
       clearTimeout(@toggleMetaTimeout)
     else
```

That seems to improve it.
