### ISSUE TITLE
Error fetching emails with many attachments

### ISSUE THREAD

**Issue by labforcode** [zammad/zammad#2591]
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..):
* Operating system: CentOS 7
* Database + version: Postgres 9
* Elasticsearch version: 2
* Browser + version: Firefox, 67

### Expected behavior:

* Fetch e-mails no mistakes.

### Actual behavior:

* When fetching e-mail with attachments, there is the error - “Channel: Email::Account in Can’t use Channel::Driver::Imap: #<Timeout::Error: execution expired>”

### Steps to reproduce the behavior:

* 
    In tests for use of the tool, when retrieving emails with PDF attachments, there was a return of the previously mentioned error.

Emails with 25, 35, 45 and 50 attachments, with maximum size within the allowed by Gmail, I think 25MB, there was no error return mentioned.

However, when trying to perform the test with 70 PDF files attached to the email, there was a return of the error, with this, the application stopped fetching for emails.

I searched the documentation for the number of attachments in the email, but found no relevant information. I know that Zammad has the parameter “E-mail > Settings > Maximum Email Size”, which determines the maximum size in MB of emails and not the number of files attached.

In my confugurations, this parameter has its value of 150 MB and the emails that I am sending do not reach 25MB, even with the 70 attachments.

So, do you have any idea of ​​any additional parameters about this?

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
As also already stated in our community: Please provide logfiles or whatever indicates "the error".
If this is a technical question, please stick to our community.

**Comment by MrGeneration** [comment]
Anyway, I couldn't reproduce this. 
I've tested this with more than 80 attachments and a total size of 58MB.

If you feel like this is an error, please provide error logs when the error appears.
