### ISSUE TITLE
missing OTRS.png asset in Import Wizard

### ISSUE THREAD

**Issue by NeverMin** [zammad/zammad#2593]
### Infos:

* Used Zammad version: git/develop
* Installation method (source, package, ..): source
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Steps to reproduce the behavior:

* open [import wizard](https://zammad.example.com/#layout_ref/import_wizard) in layout_ref
* [otrs logo](https://zammad.example.com//assets/images/otrs-logo.png) is 404, can't find in server

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dennykorsukewitz** [comment]
Hi @martini 
is there anything else to do here?
