### ISSUE TITLE
RTL writing system support in Public KB

### ISSUE THREAD

**Issue by YosefAdPro** [zammad/zammad#2598]
*Parts of this article have been edited by @MrGeneration to meet our requirenments* 

### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): package
* Operating system: Centos 7
* Database + version:
* Elasticsearch version: 5.6
* Browser + version: Chrome 75.0.3770.80

Original-Text from internal git (issue73):
```
Articles are usually created in the configured primary language and translated to other languages afterwards. To improve the translation process there should be a special translation interface. An agent can choose an existing article to translate. Zammad opens the translation interface which is a splitted view with the original article as read only on the one side and the new translated version / WYSIWYG on the other.
BONUS: Introduce a user pref to store a default language for source articles.
BONUS: The language of both sides should be changeable.
BONUS: Check RTL text orientation support.
```

### Expected behavior:

*

### Actual behavior:

*When using RTL languages (Hebrew) All content is on the left side RTL is not supported.

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by YosefAdPro** [comment]
![image](https://user-images.githubusercontent.com/11810187/59260472-56985780-8c44-11e9-9fab-1df92b5cbec4.png)

**Comment by MrGeneration** [comment]
Thanks for your enhancement request. This actually currently works as designed.

I recycled your first article, as we already had an internal issue to this.
This will be enhanced in the future!

**Comment by mrflix** [comment]
Ok so I think we'll need the following things to get RTL working in the knowledge base:
- a text direction setting for each language (default: left to right)
- render the text direction in the html tag's dir attribute: `<html lang="he" dir="rtl">`. This will activate the correct text flow
- rework layout things that are not yet in the correct flow using mixins we already use in zammad.scss: `bidi-style()`, `rtl()` and `ltr()`
