### ISSUE TITLE
I18N for notifications/templates

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#26]
What about the possibilit to support I18N also in the backend, e.g. for templates, e-mails etc?

**Comment by posica** [comment]
I am in Taiwan with zh-TW  (Traditional Chinese)is not the same as zh (Simplified) could I make the translation contrubution?

**Comment by MrGeneration** [comment]
@posica please do not hijack closed bug reports.
As your post is rather a technical question, for the next time, please consult the Community at https://community.zammad.org


Please contact support [at] zammad [dot] com, we'll provide you a translation file then which we'd like to ask you to translate. If that's done, we can do some magic to add your language to Zammad. :)
