### ISSUE TITLE
Knowlegde Base - Add pictures

### ISSUE THREAD

**Issue by Netsky349** [zammad/zammad#2601]
### Infos:

* Used Zammad version: 3.0.x
* Installation method (source, package, ..): RPM
* Operating system: Centos
* Browser + version: Brave + Chrome

### Expected behavior:

I saw that it was possible to add an image in an answer. See the example on the website.

### Actual behavior:

I have just created a response but I can't save it with an image. How to add an image that you want to import from the computer ?
I try to add html link for add image and i have the same problem.

### Steps to reproduce the behavior:

To reproduce the problem, simply make a new answer and try to record with an image.

Have a good day,

Thx :)

**Comment by MrGeneration** [comment]
Sorry I can't reproduce your problem.
This is rather a technical question - for the next time, please use our community ( https://community.zammad.org/ ) as we'd like to keep bugs and issues on github. 

Thank you for your understand.

Using inline images only works, if you copy the image content (not the file), I attached a screencast that should help. This screencast applies to all places within Zammad.

![ezgif-1-54ab4b6d1cd4](https://user-images.githubusercontent.com/6549061/59284731-0e415f80-8c6d-11e9-92cc-1b7289683574.gif)
