### ISSUE TITLE
Report With Custom Objects in Ticket Dont Work

### ISSUE THREAD

**Issue by corew1306** [zammad/zammad#2602]
### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): DEB
* Operating system: Ubuntu 18.10 LTS
* Database + version:
* Elasticsearch version: 5.6
* Browser + version: Chrome 75 

Report-Profiles With Custom Objects in Ticket Dont Work

After creating custom objects for tickets, reports do not work when we select these fields as search limiters

As shown in the pictures below.

sorry my bad english

![A1](https://user-images.githubusercontent.com/51724602/59311048-911ee600-8c7e-11e9-95bd-c1118e3bae72.png)
![A2](https://user-images.githubusercontent.com/51724602/59311050-9419d680-8c7e-11e9-8713-919a6960970a.png)
![A3](https://user-images.githubusercontent.com/51724602/59311052-95e39a00-8c7e-11e9-8a00-9633e2b67b43.png)
![A4](https://user-images.githubusercontent.com/51724602/59311130-c592a200-8c7e-11e9-8b69-823220540b62.png)
![A5](https://user-images.githubusercontent.com/51724602/59311188-ff63a880-8c7e-11e9-80ca-b6bc44c68cf4.png)

**Comment by MrGeneration** [comment]
I can't reproduce this with e.g. a select field.
Please ensure that your elasticsearch is up and running (and at least one ticket fullfills the filter).

If the problem persists, please provide your production.log so we can try to reproduce this.

**Comment by corew1306** [comment]
[production.zip](https://github.com/zammad/zammad/files/3278879/production.zip)

There are valid tickets as shown in image 2 but when we open the report there is no ticket

Is the log requested

**Comment by MrGeneration** [comment]
Ah I see what's confusing you now! Sorry didn't see that on the first sight.

You're trying to filter for closed Tickets, proberbly on the day it has been created.
This won't work, unless it was closed on the same day!

Zammad will show you the Tickets affected according to the time range (in your case a exact day) depending on the search filter. If you closed a Ticket on the filtered day, the filter open will not show your ticket, the "closed" will.

This is a technical question - please use the community for the next time :-) (https://community.zammad.org).

See attached screencast which might make this clearer.
![reporting-no-result](https://user-images.githubusercontent.com/6549061/59353171-a9e0d780-8d22-11e9-809e-50614a881360.gif)

**Comment by corew1306** [comment]
I thank all support given, sorry if I opened as a bug but it seemed a bug.
I posted a video of what happens to understand better if I could explain in words.

[Suporte AMDLAN - Reporting.zip](https://github.com/zammad/zammad/files/3283280/Suporte.AMDLAN.-.Reporting.zip)
