### ISSUE TITLE
Limit access to KB Categories based on roles

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2603]
### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1041496, #1088929 

*Note:* This has been moved from our internal git ( 251 ) to Github in order to only have one enhancement issue at the time.

### Desired behavior / enhancement:
Currently there is only the subdivision of rights between reading and editing agents.

Usecase: In an organization several departments work with Zammad. Each department has different internal requirements. The internal specifications of one department must not be available to the entire organization.

Implementation proposal: It should be possible to select the currently available roles for each category:

![image](https://user-images.githubusercontent.com/6549061/59390844-b8ef7600-8d72-11e9-9bf8-38e1afe525c8.png)

**Comment by voohoo2000** [comment]
Hi, Is there any realize plan?

**Comment by MrGeneration** [comment]
We have this on our roadmap, but we have other issues and enhancement that we weighted as more important. 

Sorry, but we don't have ETAs at the moment, it's coming when it's ready.
We'll update this issue, as soon as we have any update on this.

I'm limitting the conversation on this issue now, to reduce the noise on the repository.
Please don't get me wrong, your opinions are important, but our tracker is the wrong place for those pings. If you want to discuss this, please feel welcome on our community: https://community.zammad.org
