### ISSUE TITLE
Edit-Buttons on customer interface (as agent) has wrong link (Blank-Page)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2604]
### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): any
* Operating system: Ubuntu 18.04 (frankly any)
* Database + version: any
* Elasticsearch version: any
* Browser + version: Tested with Firefox, Chrome and Safari
Issue found by community member: https://community.zammad.org/t/blank-edit-knowledge-base/2605

### Expected behavior:

* When going to `/help` as authenticated agent with editing rights, you can click on all Edit-Buttoms on the upper right and go on edit parts of the KB.

### Actual behavior:

* When going to `/help` as authenticated agent with editing rights, Zammad will load a blank page with sidebar on the left, when hitting any of the Edit-Buttons.

Reason behind this is, that the customer interfaces "Edit"-Button leads to: 
* Editing the Knowledgebase (overall)
  * `https://myzammad.tld/#knowledge_base/1` while it should be `https://myzammad.tld/#knowledge_base/1/locale/de-de/edit`
* Editing a category
  * `https://myzammad.tld/#knowledge_base/1/category/1` while it should be ``https://myzammad.tld/#knowledge_base/1/locale/de-de/category/1/edit`
* Editing an answer
  * ``https://myzammad.tld/#knowledge_base/1/category/2` while it should be ``https://myzammad.tld/#knowledge_base/1/locale/de-de/answer/1/edit`

### Steps to reproduce the behavior:

* Login to Zammad
* Go to `/help` (customer interface)
* Press "Edit Knowledgebase" on upper right
* See a white content area (left sidebar is still there).

Note: This apples to every edit-button within the customer interface.

### Screen:
![image](https://user-images.githubusercontent.com/6549061/59391206-ed176680-8d73-11e9-9cee-1cd24f36a50d.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
This is fixed in `develop` and `stable`. Packages will be ready in about 30 minutes from now 🚀

**Comment by stevenjmiklovic** [comment]
@thorsteneckel Thank you Sir!
