### ISSUE TITLE
Deletion via API impossible when user logged in at some point

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2605]
### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): any 
* Operating system: any
* Database + version: any 
* Elasticsearch version: any
* Browser + version: Postman and Curl (for direct testing of the endpoints)
* Ticket-ID: #1077545

### Expected behavior:

When having no references (except for ActivityStream and CTI-Stuff), you can delete a user via API endpoint as statet in our documentation: https://docs.zammad.org/en/latest/api-user.html#delete . This will work, even if the user logged in at some point of the accounts lifetime.

If the user has e.g. a ticket he's customer in, you won't be able to delete the user, as there are references that are blocking your way. 

### Actual behavior:

When deleting a user via API endpoint, this will only work if the user **never** logged in into Zammad. As soon as you logged in, the following function line will stop you: https://github.com/zammad/zammad/blob/develop/app/controllers/users_controller.rb#L317

Funfact: Even though it says "I got references I can't ignore", you can go to command line and use `.destroy` to delete the user (without problems) as long as the user doesn't have other references like tickets.

Expected API-Output:
`{}`

Received API-Output:
```json
{
  "error": "Can't delete, object has references."
}
```

If you remove or comment out Line 317 of users_controller.rb, it will work.
If you have e.g. ticket references, you'll receive such a (maybe ugly) response:
```json
{
    "error": "PG::ForeignKeyViolation: ERROR:  update or delete on table \"users\" violates foreign key constraint \"fk_rails_5e0981116b\" on table \"activity_streams\"\nDETAIL:  Key (id)=(20) is still referenced from table \"activity_streams\".\n: DELETE FROM \"users\" WHERE \"users\".\"id\" = $1"
}
```

### Steps to reproduce the behavior:

* Create a customer user without tickets (if you create some, you'll need to delete them first ;) )
* Take over the view of the customer or login as customer
* log out / go back
* take your favorite API-Endpoint tool and try to delete the new user: `https://myzammad.tld/api/v1/users/{User-ID}`

This will not work, while a `u=User.find({User-ID}` followed by `u.destroy` will work.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Hi @MrGeneration ,

should be obsolete right because of data privacy?

https://github.com/zammad/zammad/issues/2074

**Comment by rolfschmidt** [comment]
Ah ok there is a small fix needed because the reference check is not needed anymore. I will provide a fix @MrGeneration .

**Comment by rolfschmidt** [comment]
Fix got denied. It should not be possible to delete users or organizations directly via API. Because of the relations to other objects which get deleted too it is too hot for the zammad standard.

Users have to go the workaround and do it via admin interface -> data privacy.

meeting @martini , @MrGeneration , @rolfschmidt 

https://github.com/zammad/zammad/issues/3328
