### ISSUE TITLE
Triggers not present in the permissions list of a role

### ISSUE THREAD

**Issue by alexandresouza** [zammad/zammad#2608]
### Infos
* Used Zammad version: 2.9.0
* Installation method (source, package, ..): Source files
* Operating system: Ubuntu 18.04
* Database + version: Amazon RDS (MariaDB 13)
* Elasticsearch version: 5.6
* Browser + version: Opera 60.0
* Ticket-ID: #1049566

### Problem description

There is no possibility of allowing a non-full admin to use triggers.

In my case in particular, we have two levels of administrators: those of the system, and those of attendance. I can’t create a custom role allowing the use of triggers.

For the current list of permissions (without trigger), see:
https://admin-docs.zammad.org/en/latest/ 1images/Zammad_Helpdesk-_Roles_admin.jpg

### origin
A discussion started on the community board https://community.zammad.org/t/triggers-not-present-in-the-permissions-list-of-a-role/2584

**Comment by MrGeneration** [comment]
I updated your first post - could you please fill in the missing information?
We have that template to see information at glance. :-)

Thanks!

**Comment by alexandresouza** [comment]
Done !

**Comment by thorsteneckel** [comment]
@rlue - can you please provide a MR for this?
