### ISSUE TITLE
Zammad shows Customers in Owner-Selection on IE

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2609]
### Infos:

* Used Zammad version: 3.0.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any 
* Elasticsearch version: any
* Browser + version: Internet Explorer 11 und Edge
* Ticket-ID: #1046533, #1040804, #1067081, #1076975, #1076998 
* Regression of: #2510 

### Expected behavior:

* When selecting an owner, you can't see and select customers.

### Actual behavior:

* When selecting an owner, you can see your agents - plus customers.

### Steps to reproduce the behavior:

* Log in to Zammad with your favorite Browser
* Open a ticket and click on owner
  * you'll see all agents plus customers

Now if you want to have a real feature you'll do the following:
* Reload the zammad page with a opened ticket (active tab)
* as soon as you see the ticket content (while the rest is loading) press owner
  * the agents will be shown, not customers
* wait for the rest of loading to finish
* go to another ticket and press on owner
  * you'll see agents and customers

How to temporarily fix it:
* open any ticket
* click on owner to verify you're having agents and customers
* change the group (no matter if temporary or permanent, no update needed)
* check owner again (agents only)

Ticket Creation is **not** affected, but as soon as you created the ticket, the Bug impacts.

*the temporary fix only works with more than one group (of course)*

### Screencast
![IE-customer-as-owner-regression-of-2510](https://user-images.githubusercontent.com/6549061/59498740-4bd50100-8e96-11e9-83b5-ed3878a089d3.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
For anyone who can't wait for the upcoming 3.5 release we've created the `stable-ie11` branch that is current 3.4 `stable` with this additional fix. Feedback is highly welcome.
@MrGeneration / @KoJie  : You may wan't to get in touch with the `prioritised by payment` customers.

**Comment by MrGeneration** [comment]
Please note that this Branch will be removed upon the next release(s) without further notice. Don't forget to switch back to stable as soon as Zammad 3.5 is out. ❤
