### ISSUE TITLE
Not all Placeholders are working

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#261]
When i edit the email signature and add 

`#{user.department}`

in the signature. It only gives a - as placeholder. 

`#{user.phone}` works with the same content. 

Edit: I think its only working for all "read-only" attributes. 

PS: I love you guys 😄 
![vip](https://cloud.githubusercontent.com/assets/7078907/19603081/1b38b0a8-97b0-11e6-9fad-f35155bd8afe.JPG)

**Comment by martini** [comment]
Hi @Julian0o 

it works fine on my side. Can you paste in the signature where it is not working?

 -Martin

**Comment by Julian0o** [comment]
@martini This is the part of the signature

`———————————————————
#{user.firstname} #{user.lastname} 
 
Campus IT
#{user.department}
Münsterstr. 156`

**Comment by monotek** [comment]
Works for me as long ther user has a department set in "Edit: User".
If no department is set "-" is shown.
Closing.
