### ISSUE TITLE
Authentication for public KnowledgeBase

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2613]
### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any 
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: 

*Note:* This has been moved from our internal git ( 222 ) to Github in order to only have one enhancement issue at the time.

### Desired behavior:

There should be an option that denies anonymous access to the public knowledgebase.
You should be able to protect it by e.g. a password or user login e.g. via Office365 and local database).

Preferbly the login interface will stay in the same look and feel of the knowledgebase.

**Comment by thorsteneckel** [comment]
As discussed with @MrGeneration : We won't provide authentication for the public Knowledge Base. Instead use the Roles functionality (will be enhanced with: #2603) or prefer Webserver based authentication.
