### ISSUE TITLE
Misleading 'Escalation' ticket attribute name in SLAs, Scheduler and Trigger should be named 'Escalation_at'

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2615]
### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Desiredbehavior:

We should rename the condition "escalation" to "escalation at".
The current naming is miss leading, as it suggest that this will check if a ticket has escalated.

Infact, this triggers on every moment, when your "escalation_at" field changes.
The function itself works as designed.

This came up on: https://community.zammad.org/t/trigger-on-escalate-does-not-work-properlly/2637/5

**Comment by gfriloux** [comment]
I indeed spent some hours trying to understand the "escalation" trigger, and this request for renaming is probably a very nice idea.

While this could seem abvious for a zammad dev, some users (like me) just get lost.

(i also spent time looking at API, so i know the `escalation_at` variable)
