### ISSUE TITLE
Cannot tag error

### ISSUE THREAD

**Issue by nangi158** [zammad/zammad#2623]
### Infos:

* Used Zammad version:3.0.x
* Installation method (source, package, ..):source
* Operating system:CentOS7
* Database + version:PostgreSQL
* Elasticsearch version:5.6
* Browser + version:Google Chrome 75.0.3770.100

### Expected behavior:

*Able to normally tag and create ticket

### Actual behavior:

*Error after submit ticket, Tag not insert into database? and ticket created with no tag.

### Steps to reproduce the behavior:

*Tag the ticket and submit

Yes I'm sure this is a bug and no feature request or a general question.

![Untitled](https://user-images.githubusercontent.com/1268341/60090298-79f6f280-976c-11e9-9e7d-4d7388a8d774.png)

**Comment by MrGeneration** [comment]
While I believe this is a rather technical question which should live on our community (https://community.zammad.org) I'd like to ask for more information:

Please provide the `log/production.log` output together with the traceback and post it here (redacted).
Also, please let us know of this is a original source code version provided from our repo (also stable or develop would be important to know).

Please note that if this is a modified Zammad-Installation, that I'll have to close this Bug report without any further action, because we can't support that.

Eidt/Addition:
Your database seems to be incomplete.
Please run: 
```
rake db:seed
rake db:migrate
```

And ensure there are no errors.

**Comment by nangi158** [comment]
@MrGeneration 
Here's production.log file and i'm checking on the db.
[production.log](https://github.com/zammad/zammad/files/3327937/production.log)
Best Regards

**Comment by MrGeneration** [comment]
Hey,

I've checked your logfile, but it's from today morning where this problem doesn't seem to occured.
Production-Log from the moment where you upgraded Zammad and from the moment you had this problem would help better. :-)

**Comment by nangi158** [comment]
@MrGeneration 
I see...
Here's the right log
[production.log-20190626.gz](https://github.com/zammad/zammad/files/3332577/production.log-20190626.gz)
Somewhere here
![Untitled1](https://user-images.githubusercontent.com/1268341/60227513-d87db700-98b9-11e9-957c-92acf01588c2.png)

Yesterday me and my friend tried to install ruby, rails, rake on oraclevm to create database which i didn't do on the real server... i guess that's why this problem occur. I wonder if cent os 7 need to do something to create database too... ? Thank you.

---------------------------------------------------------------------------------------------------------------------------

Addition..
This is what happen when i tried `rake db:create`

> $ rake db:create --trace
> ** Invoke db:create (first_time)
> ** Invoke db:load_config (first_time)
> ** Execute db:load_config
> ** Execute db:create
> PG::InsufficientPrivilege: ERROR:  permission denied to create database
> : CREATE DATABASE "zammad_development" ENCODING = 'utf8'
> Couldn't create 'zammad_development' database. Please check your configuration.
> rake aborted!
> ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied to create database
> : CREATE DATABASE "zammad_development" ENCODING = 'utf8'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `async_exec'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `block (2 levels) in execute'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.7/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:72:in `block in execute'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
> /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:71:in `execute'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql/schema_statements.rb:46:in `create_database'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/postgresql_database_tasks.rb:19:in `create'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:117:in `create'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:137:in `block in create_current'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:305:in `block in each_current_configuration'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:302:in `each'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:302:in `each_current_configuration'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:136:in `create_current'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/railties/databases.rake:27:in `block (2 levels) in <top (required)>'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
> /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
> /usr/local/rvm/gems/ruby-2.4.4/bin/rake:23:in `load'
> /usr/local/rvm/gems/ruby-2.4.4/bin/rake:23:in `<main>'
> /usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `eval'
> /usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `<main>'
> 
> Caused by:
> PG::InsufficientPrivilege: ERROR:  permission denied to create database
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `async_exec'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `block (2 levels) in execute'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.7/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:72:in `block in execute'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
> /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:71:in `execute'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql/schema_statements.rb:46:in `create_database'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/postgresql_database_tasks.rb:19:in `create'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:117:in `create'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:137:in `block in create_current'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:305:in `block in each_current_configuration'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:302:in `each'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:302:in `each_current_configuration'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/tasks/database_tasks.rb:136:in `create_current'
> /usr/local/rvm/gems/ruby-2.4.4/gems/activerecord-5.1.7/lib/active_record/railties/databases.rake:27:in `block (2 levels) in <top (required)>'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
> /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
> /usr/local/rvm/gems/ruby-2.4.4/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
> /usr/local/rvm/gems/ruby-2.4.4/bin/rake:23:in `load'
> /usr/local/rvm/gems/ruby-2.4.4/bin/rake:23:in `<main>'
> /usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `eval'
> /usr/local/rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `<main>'
> Tasks: TOP => db:create

With Respect
Nangi

**Comment by MrGeneration** [comment]
Okay, I could verify that this is no bug, but a technical question.
Please follow our documentation for the installation step by step https://docs.zammad.org/en/latest/install-source.html

Also, please note that possible code changes are not supported - if you did manually work on the database, please note that this can also lead to issues.

If you still need help, please feel free to head over to our community (free) to get help: https://community.zammad.org
Also, if commercial services are more interesting for you, you can get more information on that here: https://zammad.com/pricing#selfhosted

Closing now.
