### ISSUE TITLE
Out of Office / holiday substitute

### ISSUE THREAD

**Issue by dYn36** [zammad/zammad#263]
It would be great if an agent can tell others when he is out of office.
The "holiday agent" assigned tickets should then easily be handovered to another agent, so that it can be worked on it, without forgetting it ;-)

**Comment by martini** [comment]
Hi @dYn36 

is https://zammad.com/business-features/absence-assistant what you are looking for?

It's already available since Zammad 2.0.

Just reopen if it's not matching your requirements. Thanks!

 -Martin
