### ISSUE TITLE
Chat Notifications and Alerts

### ISSUE THREAD

**Issue by jozephbrasil** [zammad/zammad#2632]
I am constantly losing chats because there is no way to alerts the agent with Windows, Notifications or Sounds. Is there a way to add sounds alerts on chat requests?

**Comment by MrGeneration** [comment]
Sorry, I believe that this is a technical question.
Please do **not** post technical questions on our Github Repo!

For technical questions use our community, please! (https://community.zammad.org)

Please be aware that -if enabled- Zammad already does provide Browser notification, a counter on the chat tab AND a pling sound if a customer is awaiting you to chat with him.

I'll be closing this now.

**Comment by javier89** [comment]
can you help me?, commenting, if someone has had the need to have their chat displayed by a pop-up window, how a resolved?

**Comment by MrGeneration** [comment]
Please don't recycle closed issues and don't post technical questions on this repository. 
Use the community instead (link above).
