### ISSUE TITLE
Replying incorrect when sender is agent and Zammad is in CC or TO

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2633]
### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: tested on Chrome, should affect any
* TIcket-ID: #1047717

This issue is quite a biggie, I tried to describe the cases as good as possible.

### Expected behavior:

Sending to other people together with Zammad from an agent mail should draw no issues.
Even if you have Zammad in CC/TO beside other people, you can at all times answer all persons (that are not Zammad) without trouble.

### Actual behavior:

All below cases are about the sender being the agent from his agent email account (so Zammad recognizes him as agent)

* If the agent sends a mail to any customer with Zammad in CC, the reply-all button is missing. When hitting "reply", it will only answer to the customer from the TO, but not the agent that was the sender.
  
  ![image](https://user-images.githubusercontent.com/6549061/60333466-64b2db80-9999-11e9-94b4-4a2fa5b28291.png)

* If the agent sends a mail with: TO customer, CC1 zammad, CC2 another customer; the reply all button will function proberly:
  ![image](https://user-images.githubusercontent.com/6549061/60333621-cd9a5380-9999-11e9-930b-8b4f06f2b381.png)

  * this however changes if you just press reply, Zammad will act similare to the first point (recipient would not be the sender)
    ![image](https://user-images.githubusercontent.com/6549061/60333876-734dc280-999a-11e9-9e2f-2eec03b92bf2.png)

* last but not least, if you send a mail as agent to Zammad with a customer in CC, the reply all button is missing. However, the reply button does work correctly here.

  ![image](https://user-images.githubusercontent.com/6549061/60333967-b314aa00-999a-11e9-8a75-717d7234f37d.png)

  
### Steps to reproduce the behavior:

**case1**
* send a mail from agent address with TO customer, CC zammad
* open ticket and check for reply-all, check also what happens if you presso on reply

**case2**
* send a mail from agent address with TO customer, CC1 zammad, CC2 another customer
* open ticket and check the reply-all
* now check the reply button

**case3**
* send a mail from agent address with TO zammad, CC customer
* open ticket and see the missing reply-all button
* check reply, this one will be correct

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by maggusf** [comment]
is this a duplicate to #2426?

**Comment by thorsteneckel** [comment]
Hey @maggusf  - I'd say yes. Thanks for the heads up! @MrGeneration - what do you think?

**Comment by MrGeneration** [comment]
Doh! You're right. I'm closing this issue for the sake of #2426
