### ISSUE TITLE
Merge not possible with not set, required attributes

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2634]
### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1047797, #1072733

### Expected behavior:

When receiving a new ticket by mail that you want to merge (because your customer didn't reply to the existing ticket but just created a new mail), you can merge tickets together without prefilling required attributes.

### Actual behavior:

When trying to merge a newly created ticket (by mail), you can't merge this new ticket into another ticket, without filling out required fields. During merge, this is troublesome as it's possible that your client just send you another mail to a ticket that you already have.

### Steps to reproduce the behavior:

* Send two different mails to Zammad 
* create a required attribute (update database etc)
* try to merge a newly created ticket into another without prefilling the required attribute
* fail

### Screencast:
![merge-required-attribute-impossible](https://user-images.githubusercontent.com/6549061/60341881-3987b680-99b0-11e9-8bbc-b291bd4e61e5.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Technical background information:

ObjectManager Attribute validation is active for Models including the `HasObjectManagerAttributesValidation` concern. This concern registers a custom validator class called `ObjectManager::Attribute::Validation` which performs generic attribute validation for any Models that are enabled to have ObjectManager Attributes.

implementation proposal:

There is a method called [`validation_unneeded?`](https://github.com/zammad/zammad/blob/acd28480b0ed8d780294bb5590c7065eeb56f51c/app/models/object_manager/attribute/validation.rb#L21-L25) which skips validation whenever the system is in `import_mode` or the record that is validated got changed in a non-application server context (e.g. Scheduler, Websocket Server or Rails Console).

This method should get extended to check wether the record that should get validated responds to a method called `skip_object_manager_attribute_validation?`. If so the method should be called and the validation should be skipped if the return value is `true`. This method should be defined in the `HasObjectManagerAttributesValidation` concern. An additional method called `skip_object_manager_attribute_validation` should be added that sets an instance variable called `@skip_object_manager_attribute_validation` to `true`. This instance variable will be used as the return value for the `skip_object_manager_attribute_validation?` method.
