### ISSUE TITLE
where to find version of zammad

### ISSUE THREAD

**Issue by dynamicman36** [zammad/zammad#264]
Where can i find the zammad version number i have installed currently ?

**Comment by Julian0o** [comment]
I was also searching for a version number and could not find one :)

**Comment by monotek** [comment]
Maybe in https://github.com/zammad/zammad/blob/develop/package.json

@mrflix 
Is this file updated when a new version is released?

@martini 
A VERSION file in the root would be nice. 
I'll check if this can be updated automaticly from GitHub tags...

**Comment by dnauck** [comment]
It would also nice to see the version in the UI, at least in the admin settings

**Comment by jepf** [comment]
Zammad now displays its version number within Admin->System-Version.
