### ISSUE TITLE
Insertion of inline pictures does not work, if you copy an image in your Browser

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2645]
### Infos:

* Used Zammad version: 3.0 and earlier
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any (tested in Chrome and Firefox, but should affect any)
* Ticket-ID: 1057659

### Expected behavior:

* When copying an image (e.g. in your Browser with "copy image") you can paste it into any Zammad article and just send it away.

### Actual behavior:

* When copying an image (e.g. in your Browser with "copy image") you can paste it into any Zammad article. The image will be displayed as long as the article hasn't been sent, as soon as you update the ticket, the image is gone.

*Hints:*
* This is caused, because we insert a HTML-IMG-Tag with the URL to the image. 
* We should get the image from local storage (as we already have it, because we can see it, no additional downloaded should be necessary) and simply store it as inline image.
* copying inline images does work, but needs extra steps that ensure to copy the image content to the system clipboard. This extra step can be time consuming and annoying.

### Steps to reproduce the behavior:

* Create a ticket with an article, paste a image into the article from any source, as long as it's your browser (local might work in some special cases as well)
* Update the ticket
* result: image is gone :-(

Note: This affects several parts in Zammad:
* signatures
* triggers (email, article)
* scheduler (email, article)
* text modules
* tickets (articles)
* knowledgebase (answers)

### Screenshot and Screencast:
![image](https://user-images.githubusercontent.com/6549061/60524509-fe0d2500-9cec-11e9-8706-6b7c60e01792.png)

![copy-inline-images-only-if-you-know-how](https://user-images.githubusercontent.com/6549061/60525470-b091b780-9cee-11e9-9098-20214852f9d0.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by pixelflair** [comment]
Having the same problem :-( 

After Upgrading from 2.9 to 3.1

**Comment by MrGeneration** [comment]
No offense, but I'm locking the conversation to reduce the "me too" noises.
This issue exist in Zammad since day one :)

**Comment by MrGeneration** [comment]
Small follow up on this issue, because we had a talk about this.

**We basically have the following valid use cases:**
1. copy images in between the same instance
2. copy external images from other sites that allows CORS
3. copy external images from other sites that disallows CORS

### 1. Copy images in between the same instance

This should imho never be any problem.
When inserting images, the editor needs to convert the provided image into a "data-url" which is internally linked to the same attachment in the store (to save space). With this conversion, when submitting the article, Zammad is able to keep the image.


### 2. Copy external images that allow CORS

This basically works similar to the first point. Zammad will, after pasting an external image, try to convert the image to a local data URL. If this is successfull, you can simply submit the image in the article and view it afterwards.

If the above fails, we'll come to point 3.

### 3. Copy external images that disallow CORS

If the user pastes an external image that can't be converted to a local data URL (e.g. because of CORS headers), Zammad will inform the user after pasting. I thought of soomewhat a border/overlayish thingie with an error message "Sorry, can't import this image because external source denies it. Please remove this image, if you don't, Zammad will automatically remove it from the article upon submitting." with a link to our documentation that would describe the issue and give the user a way on "how to do it alternatively".

This way the user can address issues with images without having frustration because "all images are gone" or the customer thinking you can't control your software. :-)

----

#### Side notes and thought from me:

I prefer a optical hint for the image that is afected by failing conversion, because it could be possible that you have sites you copy with several linked sources (that allow CORS and some don't). So if you just say "Hey sorry, I removed images because I couldn't import them", the user just can't know which images are affected.

Imho, just removing images during edit (where it hurts nobody if the image can't be converted), might cause unexpected behaviour to the user which might cause in a butt load of github issues that we'd just need to close "works as we designed it". I think we should do better. :)

**Comment by mantas** [comment]
@MrGeneration it's 2 different issues. Copying an image inside browser is doable. There's a bug in current clipboard handling code, but it's doable without CORS and whatnot.

The big problem is copying animated GIF. Because only the first frame is copied and available in clipboard as a still image. Trying to fetch the whole GIF may be blocked by CORS.
