### ISSUE TITLE
Avatar in E-Mail Signature

### ISSUE THREAD

**Issue by thomas-obernberger** [zammad/zammad#2646]
I tried to add the users avatar to the default email signature like this:
![image](https://user-images.githubusercontent.com/20873706/60532983-d1fa9f80-9cfe-11e9-98cb-85b94553a0f2.png)
(recommended at the community pages)

then if you try to answer or create a new mail ticket, the view is not refreshed and a javascript exception is thrown. 

if i remove the avatar from the signature - everything is fine

### Infos:

* Used Zammad version: 3.0.0-1561629709.c101f730.bionic
* Installation method (source, package, ..): apt-get
* Operating system: ubnt 1804
* Database + version: 10.9-0ubuntu0.18.04.1
* Elasticsearch version: 5.6.16
* Browser + version: chrome 75, safari 12

the zammad installation is fresh - installed it just some moments before

### Exception:
![image](https://user-images.githubusercontent.com/20873706/60532869-95c73f00-9cfe-11e9-9276-78d6935d6757.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Arihantar** [comment]
What do you think about integrating [gravatar](https://en.gravatar.com/) here?

**Comment by thomas-obernberger** [comment]
@Arihantar i think you are mixing up some features here :)
this is an issue, where embedding of the users avatar is not working in the email signature

your request should go into zammads community board:
```Please post:
- Feature requests
- Development questions
- Technical questions

on the board -> https://community.zammad.org !```

**Comment by Arihantar** [comment]
@thomas-obernberger thanks for clarifying. I was thinking of contributing to this so thought of checking this first.

**Comment by MrGeneration** [comment]
Sorry for taking so long.
The variable you tried to call is breaking functionality within Zammad and doesn't seem to be valid at all. On top of that, Zammad does not provide it on our own.

Thus I believe that this is rather a feature request (please fill a feature request at the Community if not already done :) ).

Closing now.
