### ISSUE TITLE
action:delete doesn't work in Scheduler; German characters are bombing

### ISSUE THREAD

**Issue by adlix** [zammad/zammad#2649]
### Infos:

* Used Zammad version: 2.7.x
* Installation method (source, package, ..): package
* Operating system: Debian GNU/Linux 9
* Database + version: PostgreSQL 9.6
* Elasticsearch version: 5.6.13
* Browser + version:

### Expected behavior:
Scheduler problems:
(0. Execution Time should be the same as scheduled time )
1. action: delete should delete tickets within running job (#1331)
2. Special UTF-8 characters should work.

### Actual behavior:
0. Excecution time (09:10) is schedule time (07:10). It's plus 2 hours (My Timezone (also server time) is GMT+2 ! )  #2229 (Have in mind on checking screenshots; this made error search difficult)
1. Scheduler overview is telling me 557 tickets processed, 557 ticket will be proccessed
   Spam Tickets are still there.
2. There seems to be a problem with "German Umlaute" ä,ö,ü - see production.log
   
###production.log
F, [2019-07-04T09:59:11.200067 #3194] FATAL -- :   
F, [2019-07-04T09:59:11.200138 #3194] FATAL -- : ActionDispatch::Http::Parameters::ParseError (765: unexpected token at '--------------------------4d3e6e843edd4387
Content-Disposition: form-data; name="json"

{"name":"Einzelh\u00e4ndler","firma":"160000","shared":true,"active":true}
--------------------------4d3e6e843edd4387--
'):
F, [2019-07-04T09:59:11.200180 #3194] FATAL -- :   
F, [2019-07-04T09:59:11.200282 #3194] FATAL -- : vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_dispatch/http/parameters.rb:115:in `rescue in parse_formatted_parameters'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_dispatch/http/parameters.rb:109:in `parse_formatted_parameters'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_dispatch/http/request.rb:361:in `block in POST'

### Steps to reproduce the behavior:

see images 
![scheduler_1b](https://user-images.githubusercontent.com/6816831/60661457-3ed67c80-9e5a-11e9-8770-aef56ffc5e92.PNG)
[production.log](https://github.com/zammad/zammad/files/3358948/production.log)
![scheduler_1](https://user-images.githubusercontent.com/6816831/60661458-3ed67c80-9e5a-11e9-864e-3746fa6df77e.PNG)
![scheduler_1a](https://user-images.githubusercontent.com/6816831/60661460-3ed67c80-9e5a-11e9-93c4-57d0600968a5.PNG)

**Comment by MrGeneration** [comment]
Heya,

please provide your Zammad-Version, that's a mandatory ifnormation.
Please also let us know what Attribute "Einzelhändler" is - especially where it lives and it's configuration.

Thanks

**Comment by adlix** [comment]
Hi,
sorry Zammad Version is 2.7.x

Field is name of organisation
production.log
I, [2019-07-04T09:59:11.194592 #3194]  INFO -- : Started POST "/api/v1/organizations" for 127.0.0.1 at 2019-07-04 09:59:11 +0200
F, [2019-07-04T09:59:11.200067 #3194] FATAL -- :
F, [2019-07-04T09:59:11.200138 #3194] FATAL -- : ActionDispatch::Http::Parameters::ParseError (765: unexpected token at '--------------------------4d3e6e843edd4387
Content-Disposition: form-data; name="json"

{"name":"BICO Einzelh\u00e4ndler (DZB Bank)","firma":"160000","shared":true,"active":true}
--------------------------4d3e6e843edd4387--
'):
F, [2019-07-04T09:59:11.200180 #3194] FATAL -- :
F, [2019-07-04T09:59:11.200282 #3194] FATAL -- : vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_dispatch/http/parameters.rb:115:in `rescue in parse_formatted_parameters'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_dispatch/http/parameters.rb:109:in `parse_formatted_parameters'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.5/lib/action_dispatch/http/request.rb:361:in `block in POST'

Additionally I found following error in scheduler_out.log
Mail::AddressList can not parse |"Andreas Thöne" <a.thoene@freenet.de>|
Reason was: Only able to parse up to "Andreas Thö



Anfang der weitergeleiteten Nachricht:

Best regards / Mit freundlichen Grüßen

Matthias Zillig
IT department / IT-Abteilung

Tel: +49 9544 9444 832
Fax: +49 9544 9444 8032
mail: mz@messingschlager.com
www.messingschlager.com<http://www.messingschlager.com>

[https://www.messingschlager.com/img/Bilder/MeMail815s.png]

Messingschlager GmbH & Co. KG,
AG Bamberg HRA 10244, Haßbergstraße 45, 96148 Baunach - Germany

Pers. haftende Gesellschafterin: Benno Messingschlager GmbH,
AG Bamberg HRB 2407, Geschäftsführer: Benno Messingschlager


P Please consider the environment before printing this email

Wichtiger Hinweis:
Diese Mitteilung ist vertraulich und nur für den oben genannten Adressaten bestimmt. Für den Fall, dass Sie als Empfänger dieser Nachricht nicht mit dem oben genannten Adressaten identisch oder mit der Aushändigung an ihn vertraut sind,
weisen wir darauf hin, dass jede Verbreitung oder Vervielfältigung untersagt ist. Bitte unterrichten Sie den Absender telefonisch. Auskünfte per E-mail sind ebenso wie mündliche Auskünfte nur verbindlich, wenn sie ausdrücklich auf dem
Postwege rechtsverbindlich unterzeichnet bestätigt werden.
Die Allgemeinen Geschäftsbedingungen (AGB) der Messingschlager GmbH & Co. KG sind einsehbar unter: http://www.messingschlager.com/AGB.pdf. Hinweise zum Datenschutz sind einsehbar unter https://www.messingschlager.com/de/datenschutz
Important notice:
This message is confidential and intended only for the use of the addressed named above. If the reader of this message is not the intended recipient or competent to deliver it to the intended person, he is hereby on notice that any dissemination,
distribution or copying of this communication is strictly prohibited. Please notify the sender by telephone. Informations by email and oral information’s are only legally binding if they are expressively confirmed by signed mail.
General Terms and Conditions (GTC) of Messingschlager GmbH & Co. KG can be viewed at: http://www.messingschlager.com/AGB.pdf. Our privacy-policy can be viewed at https://www.messingschlager.com/en/privacy-policy
Von: Marcel <notifications@github.com<mailto:notifications@github.com>>
Datum: 5. Juli 2019 um 09:52:30 MESZ
An: zammad/zammad <zammad@noreply.github.com<mailto:zammad@noreply.github.com>>
Kopie: Matthias <matthias.zillig@adlix.de<mailto:matthias.zillig@adlix.de>>,  Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Aw:⁨ [zammad/zammad] action:delete doesn't work in Scheduler; German characters are bombing (#2649)⁩
Antwort an: zammad/zammad <reply@reply.github.com<mailto:reply@reply.github.com>>

Heya,

please provide your Zammad-Version, that's a mandatory ifnormation.
Please also let us know what Attribute "Einzelhändler" is - especially where it lives and it's configuration.

Thanks

**Comment by MrGeneration** [comment]
Whoah that's quite old. We're close to 3.1 ....
Beside, if you don't have the latest 2.7 patch, your instance currently is vulnerable: https://zammad.com/news/security-advisory-zaa-2019-01

Any way, I'll check if this also applies to newer Zammad-Versions.
Thanks for the input (sorry, I'll ignore the mail thingie, because mixing up issues isn't that good idea - please note that we did a lot of rework with Zammad 3.0 in terms of E-Mail-Import, so this might be fixed already)

**Comment by MrGeneration** [comment]
Okay so I've finally managed to test this.
Within Zammad 3.1 it doesn't seem to matter if you have Umlauts within Organization names.

Zammad will delete the ticket(s) just fine.

I'll be closing this, as I can't reproduce this.
As already mentioned, please think about upgrading Zammad to a more current version, as 2.7 is quite old.
