### ISSUE TITLE
Ticket Template administration

### ISSUE THREAD

**Issue by dYn36** [zammad/zammad#265]
If I create a new Ticket Template, it only can be changed if I open a new Ticket, choose the template I created before. 
It would be great if there is a ticket template Administration.
If i want to change a template, i have to save it under exactly the same name. If only one capital is different, the system creates a new template ("New password" != "new password")

**Comment by martini** [comment]
Sounds good.

**Comment by crnfpp** [comment]
Can this be considered solved by the recent updates?

**Comment by dominikklein** [comment]
Solved by moving the ticket template configuration to the admin area.
