### ISSUE TITLE
Support for Elasticsearch 7.x

### ISSUE THREAD

**Issue by jurgenhaas** [zammad/zammad#2650]
Are there any plans to support newer ES versions than 5.6? In particular, version 7.1 and newer have included the x-pack security addon even in the basic free version which allows management of users and roles.

**Comment by MrGeneration** [comment]
Sorry, but this is a technical question that, for the next time, should live in our community https://community.zammad.org :-)

For now, please see this issue: https://github.com/zammad/zammad/issues/1688

The support of ES 6 and 7 will come within Zammad 3.1 which is coming soon^(TM)

Closing now.. :)

**Comment by jurgenhaas** [comment]
Thanks a lot @MrGeneration
