### ISSUE TITLE
Add package for released debian buster/10

### ISSUE THREAD

**Issue by xf-** [zammad/zammad#2653]
### Expected behavior:
A package for Debian 10 after it is official stable release and not a testing version

### Actual behavior:
A lot of maintained releases, but no buster yet.

Yes I'm sure this is a bug and no feature request or a general question.
-> It is no feature request or general question and no software bug. But its mostly fits in category bug, because you claim to support Debian and it is an official release and default download of an new setup.

After installing `apt-get install libimlib2 libimlib2-dev` and ignoring dependency's like replaced `libmysqlclient18` with `libmariadb3` it works without any noticeable problems

**Comment by MrGeneration** [comment]
I'll file this as a enhancement request.
However: For the next time, please use our community for this, because feature requests shall live there first. :-)

Please also not, while we "claim" to support Debian, we also note that we support Debian 8 and 9 at the moment (see: https://docs.zammad.org/en/latest/install-debian.html ).

We'll eventually change this in the future, but no ETA.

**Comment by monotek** [comment]
As we us packager.io we depend on support of debian buster there: https://github.com/crohr/pkgr

I've added an pr there to get it work: https://github.com/crohr/pkgr/pull/157

**Comment by xf-** [comment]
Support is ready :)

**Comment by thorsteneckel** [comment]
Nice! @monotek is currently on vacation. So it might take some more days.

**Comment by EssGeeEich** [comment]
Hi, sorry to bother, but is there an ETA for this?

**Comment by MrGeneration** [comment]
Sorry, no ETA at the moment, we'll update this issue as soon as we're moving.

**Comment by MrGeneration** [comment]
internal PR is on QA

**Comment by monotek** [comment]
github pr fore reference: https://github.com/zammad/zammad/pull/2783

**Comment by monotek** [comment]
Packages are coming soon. If you want to test it, you can use:

https://packager.io/gh/zammad/zammad/builds/4140/download/debian-10

**Comment by monotek** [comment]
develop packages are available: https://packager.io/gh/zammad/zammad

**Comment by thorsteneckel** [comment]
stable will ready in about 30 minutes too via https://github.com/zammad/zammad/commit/75b0721cb5f328f233c9c41e0575453b5b20b09a

**Comment by monotek** [comment]
There it is: https://packager.io/gh/zammad/zammad/refs/stable 😎
