### ISSUE TITLE
Services die with: ThreadError: can't create Thread: Resource temporarily unavailable

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#2656]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

With Zammad 3.1 all Zammad services (and other system applications like `bash` 😱 ) die after some time because they can't create new threads. The thread limit of the OS is reached. This is caused by [a bug in Rails](https://github.com/rails/rails/issues/33600) that was introduced by a behavior change in how [DB connection reaping](https://github.com/rails/rails/commit/9027fafff6da932e6e64ddb828665f4b01fc8902) is done. There is a [pending PR](https://github.com/rails/rails/pull/33094) that resolves this.

Before Rails 5.2 DB connection reaping was disabled. Since Rails 5.2 for each established connection a new Thread is spawned that checks every minute if the connection is still alive and reaps it if not. Unfortunately these Threads are not stopped once a connection is closed.
Zammads WebSocket server is optimized to have a DB connection only if required:

https://github.com/zammad/zammad/blob/eafe412d87174769c91da52ead03059b95dee771/lib/sessions/event/base.rb#L139-L148

This means that each time a WebSocket backend that requires a DB connection is finished (e.g. chats) the DB connection gets closed but the thread persists. This leads to rising thread numbers until the max thread limit per process or even system is reached.

There should be a practical workaround until the original Rails issue is resolved.

**Comment by MrGeneration** [comment]
Just a small follow up: This seems to be (at least partly) be adressed by now :)
https://github.com/rails/rails/pull/33094#issuecomment-522474464

**Comment by dominikklein** [comment]
@mgruner The related bug in rails is fixed, do you think we need to do something on our side?

**Comment by mgruner** [comment]
No, I believe this is not an issue any more. Thanks for checking back. 👍
