### ISSUE TITLE
Translation "Ticket %s merged!" is missing

### ISSUE THREAD

**Issue by maxxer** [zammad/zammad#2657]
### Infos:

* Used Zammad version: 3.0.x
* Installation method (source, package, ..): Docker

### Expected behavior:

Unable to translate [*Ticket %s merged!*](https://github.com/zammad/zammad/blob/dadb8e207bcb679297448996d7e587feb7c89017/app/assets/javascripts/app/controllers/agent_ticket_merge.coffee#L98) string.

I didn't check *master*, but I see that line has been changed 3y ago so I expect to find it in last stable. Unfortunately by going into the translation page I cannot find it.

**Comment by MrGeneration** [comment]
Thanks for your input.
Can you please provide the italian translation for this string?

I could fix it for you like really quick then :)

**Comment by maxxer** [comment]
*Ticket %s unito!*

thanks!

**Comment by MrGeneration** [comment]
Translations have been added and can also be translated in languages that are not translated yet.
