### ISSUE TITLE
Zammad logs permanently to STDOUT on 3.1

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2660]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): seems like package only (tested on Debian 9 and openSuSe 42.3)
* Operating system: Debian 9 and openSuSe 42.3, might affect any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* With the logging changes, you'll be able to define if you want to log to STDOUT or logfile without having to change code.

### Actual behavior:

* After upgrading Zammad, it by default logs to STDOUT.
* ```
  zammad config:get RAILS_LOG_TO_STDOUT
  enabled
  ```
  Always returns enabled
* `zammad config:unset RAILS_LOG_TO_STDOUT` followed by `zammad config:get RAILS_LOG_TO_STDOUT` will still return `enabled`!


This behaviour has been changed with Zammad 3.1, commenting out these lines on package installations followed by `systemctl restart zammad` will fix the issue (up to the next update):

https://github.com/thegcat/zammad/blob/418a5aaa0ebab52729de9d8b56ad31a52e1314ec/config/environments/production.rb#L57-L61

### Steps to reproduce the behavior:

* Install Zammad 3.0 from package and upgrade to 3.1

This will proberbly also happen if you clean install Zammad 3.1.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by monotek** [comment]
I'd like to see this as a feature, not a bug...

**Comment by MrGeneration** [comment]
I see this as a bug, because you can't revert this change.

**Comment by MrGeneration** [comment]
To unset this variable (and thus log to logfile) run:
`zammad config:set RAILS_LOG_TO_STDOUT=`

The following will re-enable logging:
`zammad config:set RAILS_LOG_TO_STDOUT=true`

**Comment by MrGeneration** [comment]
The two above commits will allow package users to retain the expected behaviour.
By default, the update process will disable logging to STDOUT as it's more expected that Zammad logs to logfile (because it has been that way before).

If you want Zammad to log to STDOUT, you can find the needed tasks here:
https://docs.zammad.org/en/latest/appendix-configure-env-vars.html#configure-zammad-to-log-to-stdout

The fix is available in stable.
