### ISSUE TITLE
Inconsistency in "follow up" strings

### ISSUE THREAD

**Issue by maxxer** [zammad/zammad#2661]
Zammad 3.0.x.

There's a inconsistency in the string *follow up*. It's usually referencead simply as *follow up*, but in some cases  *follow-up* is used. 

Also I don't know why the translation page has two strings which differs by just the dash but cannot find the first one in `master` branch:

![immagine](https://user-images.githubusercontent.com/240201/61059095-bc6d3000-a3f8-11e9-82ee-6148cd5202c8.png)

It would be nice to have one usage in all the application. I'd do it myself but that involves migrations, and I'm not yet ready to approach that :)

**Comment by dennykorsukewitz** [comment]
Hi @maxxer,
Thanks for the report ❤
`follow-up` is actually the correct spelling.

In this case `Additional follow-up detection` is the correct one, since 6 month.

We will find out why the old string still exists.

**Comment by maxxer** [comment]
Ok thanks. There are several strings still using the *follow up* notation, other than this

**Comment by dennykorsukewitz** [comment]
@maxxer 
I found these.
If you find anything else, it'd be great if you commented on them.

- Assign Follow Ups
- Assign follow up to latest agent again.
- Follow up for closed ticket possible or not.
- Follow up possible
In default the follow up check is done via the subject of an email. With this setting you can add more fields where the follow up check is - executed.
- reject follow up/do not reopen Ticket
- Cannot follow up on a closed ticket. Please create a new ticket.

**Comment by maxxer** [comment]
A rough list can be found also by running `git grep -i "follow up"`. There are many comment lines
