### ISSUE TITLE
Pressing "Cancel" when creating a new ticket or separating an existing ticket doesn't close tab

### ISSUE THREAD

**Issue by maxxer** [zammad/zammad#2669]
### Infos:

* Used Zammad version: 3.0.x
* Installation method (source, package, ..): Docker
* Elasticsearch-Version: 5.6.14
* Operating system: Ubuntu 18.04
* Browser: FF68, GC75

### Expected behavior:

* Tab is closed and ticket creation aborted

### Actual behavior:

* Ticket creation tab remains open 

### Steps to reproduce the behavior:

* Open new ticket dialog or press *Split* on a ticket
* On the ticket creation page press *Cancel*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please fill in the complete template (missing: Elasticsearch-Version and used Browser) as reproducing is in this case impossible.

Thanks!

**Comment by maxxer** [comment]
Honestly, being the stock docker-compose installation, I don't even know how to check...

**Comment by MrGeneration** [comment]
My bad, but the Browser should be possible? :)

**Comment by maxxer** [comment]
Updated! 
The same behavior happens by just clicking on the + to create a new ticket. When cancelling it will leave the tab open

**Comment by MrGeneration** [comment]
Sorry for the wait, yep, can verify that on develop as well :)
