### ISSUE TITLE
Attachment deletion via API impossible

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2670]
### Infos:

* Used Zammad version: 3.1.x and earlier
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1049386, #1071153, #1083678

### Expected behavior:

When using the endpoint `/api/v1/attachments/{Attachment-ID}` with `DELETE` you can delete attachments without trouble.

### Actual behavior:

When using the endpoint `/api/v1/attachments/{Attachment-ID}` with `DELETE` deletion is impossible and just returns:

```json
{
    "error": "undefined method `can_destroy_attachment?' for #<Class:0x0000000008d79f58>"
}
```

### Steps to reproduce the behavior:

* create a ticket with at least one article holding attachment(s)
* query for that ticket to get the articles with their attachment IDs
* try to delete your attachment(s) e.g. with `DELETE https://super.secret.tld/api/v1/attachments/26`
* this will fail

### Further information:

We also might need refactoring, as the attachment-controller looks a bit messy and the knowledgebase seems to have it's own controller. We should fusion those together if possible.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Cannot reproduce anymore. Seems to be fixed at some point in the past 3 years!
