### ISSUE TITLE
Zammad preflight check warning output causes Syntax-Error in postinstall.sh and failing installation

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2674]
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package installation
* Operating system: tested on Debian and SuSe, should affect all
* Database + version: any
* Elasticsearch version: ES 5.6.16
* Browser + version: any

### Expected behavior:

postinstall.sh runs clean and throws no errors.

### Actual behavior:

postinstall.sh throws this error:
```
After this you might need to rebuild the searchindex by:
zammad run rake searchindex:rebuild
sh: 1: Syntax error: ")" unexpected
Setting default Logging to file, set via "zammad config:set RAILS_LOG_TO_STDOUT=true" if you want to log to STDOUT!
# Starting Zammad
```
(Offending line: https://github.com/zammad/zammad/blob/develop/contrib/packager.io/functions#L265 )

### Steps to reproduce the behavior:

* upgrade Zammad from 2.9 to 3.1 as example

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by monotek** [comment]
I've seen this too but could not find the issue with a quick shellcheck :-/

Seems it comes from the elasticsearch_searchindex_rebuild function...

**Comment by monotek** [comment]
Could be related to db settings warning:

```
After this you might need to rebuild the searchindex by:
+ echo -e 'zammad run rake searchindex:rebuild'
zammad run rake searchindex:rebuild
+ elasticsearch_searchindex_rebuild
+ zammad run rails r 'Setting.set('\''es_url'\'', "Warning: Database config value '\''max_allowed_packet'\'' less than Zammad setting '\''Maximum Email Size'\''
Zammad will fail to process emails (both incoming and outgoing)
larger than the value of '\''max_allowed_packet'\'' (16MB).
Please increase this value in your MariaDB configuration accordingly.
")'
sh: 1: Syntax error: ")" unexpected

```

**Comment by MrGeneration** [comment]
Haha I made some expert debugging with echos after every line I suspected until I found the evil line (at my end). spellcheck wasn't any help in that case.

I would have fixed it yesterday, but it didn't like me changing the quoting ....

**Comment by monotek** [comment]
I'm pretty sure it's about the warning. Could we disable the output and add a rails command to show it?
Doing this we could execute it on purpose and show the warning or even exit the install / upgrade process in the beginning...

**Comment by benrubson** [comment]
See #3775 for a fix 👍
