### ISSUE TITLE
API - search in user is not working

### ISSUE THREAD

**Issue by pgodzwa** [zammad/zammad#2677]
### Infos:

* Used Zammad version:3.1
* Installation method (source, package, ..):package
* Operating system: Ubuntu 16.04.6
* Database + version: mysql
* Elasticsearch version:5.6.16
* Browser + version: newest chrome

### Expected behavior:
For example:
* curl -H "Authorization: Token token=usertoken" https://url/api/v1/users/search?query="id%3A2" or 
curl -H "Authorization: Token token=usertoken" https://url/api/v1/users/search?query="id:2"

returns data

### Actual behavior:

* It returns empty array since 3.1 update. Same with search via PHP api client. Query doesn't matter, result is always empty.

### Steps to reproduce the behavior:

* Run the curl

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but I do believe that this is a technical questions.
For the next time, please post your technical question over at our community (https://community.zammad.org).

I verified this with running a search query on a clean running 3.1 instance (has been upgraded).

Hints for you:
Please ensure that your elasticsearch is up and running and also that your searchindex is up to date.

If this problem persists, please create a thread on our communtiy and reference this issue.
If we lean that this is a valid Bug, we will reopen this issue.

Thank you.
