### ISSUE TITLE
installing via yum generates error: database creation failed and others...

### ISSUE THREAD

**Issue by stine2469** [zammad/zammad#2678]
### Infos:

* Used Zammad version: zammad-3.1.0-1562942376.fb3e2d49.centos7.x86_64
* Installation method (source, package, ..): yum -y install zammad
* Operating system:  CentOS 3.10.0-957.21.3.el7.x86_64
* Database + version: postgresql.x86_64 0:9.2.24-1.el7_5
* Elasticsearch version: elasticsearch.x86_64 0:7.2.0-1
* Browser + version: n/a

### Expected behavior: 

*yum -y install zammad   will install without errors

### Actual behavior:

# Creating postgresql bootstart
Created symlink from /etc/systemd/system/multi-user.target.wants/postgresql.service to /usr/lib/systemd/systeservice.
# Restarting postgresql server
# Creating zammad postgresql user
CREATE ROLE
# Creating zammad postgresql db
createdb: database creation failed: ERROR:  new encoding (UTF8) is incompatible with the encoding of the temp (SQL_ASCII)
HINT:  Use the same encoding as in the template database, or use template0 as template.
# Grant privileges to new postgresql user
ERROR:  database "zammad" does not exist
# Updating database.yml
rake aborted!

### Steps to reproduce the behavior:

build new CentOS7 vm
patch to current using yum
add elastic repo
add epel repo
add zammad repo
yum -y install zammad

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by stine2469** [comment]
[zabbam.yum.log](https://github.com/zammad/zammad/files/3414172/zabbam.yum.log)

This is the console output from yum -y install zammad.

The only issue I understand is that the elasticsearch installation is trying to connect directly to artifacts.elastic.co and can't because this machine is behind a squid proxy.  For other installations i've done I've had to rerun the command with proxy.host, etc.

**Comment by monotek** [comment]
Check your locale setting. Utf8 is mandatory ...

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question.
For the next time, please consult our community at https://community.zammad.org :)

Closing now.
