### ISSUE TITLE
No space at comment on ticket bulk action 

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#268]
It is not possible to enter a space in the comment box, when bulk editing tickets.

![image](https://cloud.githubusercontent.com/assets/6099976/19614478/e99e159c-97f5-11e6-8ff2-91b1e246557f.png)

**Comment by singular-error** [comment]
until know i did'nt know that this is possible :) but: confirmed

**Comment by martini** [comment]
Fixed, https://github.com/zammad/zammad/commit/38250659b69c42b02af8ff527d516b301f1e215c available in in v1.0.1 on 2016-11-14.
