### ISSUE TITLE
Create User via Rest API Problems with German special character "Umlaute"

### ISSUE THREAD

**Issue by umar-aziz** [zammad/zammad#2680]
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: 18.04.02
* Database + version: any
* Elasticsearch version: any
* Browser + version: Chrome

### Expected behavior:

* Create User via RestAPI and Powershell

### Actual behavior:

* When trying to create a new User with "Umlaute" (Ä,Ü,ß...) Zammad respond with a error  (422) Unprocessable Entity.
If you replace the special character the user is created with no problems.

### Steps to reproduce the behavior:

* Create a User (lastename or firstname or any other attribute) via rest api Post method. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @umar-aziz 

can you provide a curl request to reproduce this. 

JFI: The REST API is used to create/update users, even with umlaut. So it should be no problem at all.

 -Martin

**Comment by umar-aziz** [comment]
Hi @martini 

i am using Powershell so this is the request:

```
$urlUser = "http://zammad/api/v1/users"
$jsonContent = @{"firstname"="Jörg";"lastname"="Muster";"email"="joerg.muster@muste.de";"phone" ="01012012012";"mobile"="01010101";"active"="true";"role_ids"="3";}
$JsonHeader = $jsonContent |  ConvertTo-Json -Compress
$user = "XXXX"
$pass = "XXXX"
$pair = "${user}:${pass}"
$bytes = [System.Text.Encoding]::ASCII.GetBytes($pair)
$base64 = [System.Convert]::ToBase64String($bytes)
$basicAuthValue = "Basic $base64"
$headers = @{ Authorization = $basicAuthValue }

Invoke-RestMethod -Uri $urlUser -body $JsonHeader -Method "POST" -ContentType "application/json" -Headers $headers
```
If i change the Firstname to Joerg i could create the User with Jörg it does not work

-Umar

**Comment by kevin-olbrich** [comment]
PowerShell does not use UTF8 by default for Rest services:
https://stackoverflow.com/questions/21598398/wrong-encoding-on-powershell-invoke-webrequest-post/51481644

Also you cast a string to ASCII which should be UTF-8:
`$bytes = [System.Text.Encoding]::UTF8.GetBytes($pair)`

**Comment by martini** [comment]
@kevin-olbrich Thanks for feedback. 

@umar-aziz I agree with @kevin-olbrich - it's working just fine with umlauts and curl.

**Comment by umar-aziz** [comment]
@kevin-olbrich 
@martini 
Thank you for the help. I got it now running:

```
$urlUser = "http://zammad/api/v1/users"
$jsonContent = @{"firstname"="Jörg";"lastname"="Muster";"email"="joerg.muster@muste.de";"phone" ="01012012012";"mobile"="01010101";"active"="true";"role_ids"="3";}
$JsonHeader = $jsonContent |  ConvertTo-Json -Compress
$user = "XXXX"
$pass = "XXXX"
$pair = "${user}:${pass}"
$bytes = [System.Text.Encoding]::UTF8.GetBytes($pair)
$base64 = [System.Convert]::ToBase64String($bytes)
$basicAuthValue = "Basic $base64"
$headers = @{ Authorization = $basicAuthValue }

Invoke-RestMethod -Uri $urlUser -body $JsonHeader -Method "POST" -ContentType "application/json; charset=utf-8" -Headers $headers
```
I have to set
`$bytes = [System.Text.Encoding]::UTF8.GetBytes($pair)`

and the Invoke Invoke-RestMethod need the 
`-ContentType "application/json; charset=utf-8"`

If someone search and need the working code
