### ISSUE TITLE
Question regarding rake searchindex:rebuild

### ISSUE THREAD

**Issue by saschajullmann** [zammad/zammad#2683]
### Infos:

* Used Zammad version: 3.0.0
* Installation method (source, package, ..): Dockerfile
* Operating system: Ubuntu 18.04
* Database + version: Postgres 11.4
* Elasticsearch version: 5.6
* Browser + version: -

### Expected behavior:

* rake searchindex:rebuild rebuilds index completely

### Actual behavior:

* only a subset (latest 100K maybe) of the index gets rebuilt.

### Steps to reproduce the behavior:

* -

We are currently in the process of migrating from the all docker container setup (as provided by zammad-docker-compose) to only zammad in a docker container, and postgres and elasticsearch as standalone services hosted on AWS. When we start a new test zammad instance with a backup of our db and we execute rake searchindex:rebuild, only about 100K documents get created. In our old (current prod) setup we have about 300K documents in the index. Therefore some tickets on the test instance are not in the index and thereby not searchable. Not what we want obviously. Any ideas how we can completely rebuild the search index?

Thanks!

**Comment by thorsteneckel** [comment]
Hey Sascha. That's a technical question and (probably) no issue. Could you please create a topic over at the [community board](http://community.zammad.org/) and provide the output of the command and  the `log/production.log` file of your system. You can refer to me. We'll find a solution 👍
