### ISSUE TITLE
Auto complete mails by forwarding tickets not working

### ISSUE THREAD

**Issue by thomasmeier85** [zammad/zammad#2684]
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04 LTS
* Database + version: PostgreSQL 10.9
* Elasticsearch version: 5.6.16
* Browser + version: Firefox 68 + Safari 12.1.1

### Expected behavior:

* forwarding an email, start typing the mail address, get recommendations based on previous mail addresses. That behaviour was seen in versions before 3.1

### Actual behavior:

* Mail addresses are not recommended, auto complete doesn't word anymore

### Steps to reproduce the behavior:

* open a mail/ticket, try forwarding the ticket to a mail address.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by cubemac** [comment]
Same problem here with 3.1 
Browsers: Chrome/Edge (Windows) Chrome/Safari (Mac)

**Comment by sreimers** [comment]
Upgrading elasticsearch to 7.3 fixed this issue for me. maybe even a re-index will do.

**Comment by martini** [comment]
I also can confirm that a `zammad run rake searchindex:rebuild` (without elasticsearch upgrade) fixed it on my side.

Feedback is welcome.

**Comment by cubemac** [comment]
Works ! 
Thank you

**Comment by Quax1507** [comment]
Same here! 

> zammad run rake searchindex:rebuild

 fixed it!
