### ISSUE TITLE
Cannot add user to organization

### ISSUE THREAD

**Issue by 4d4ch4u32** [zammad/zammad#2686]
### Infos:

* Used Zammad version: 3.1.x 
* Installation method (source, package, ..): Ubuntu package (18.04)
* Operating system: Ubuntu 18.04
* Database + version: default
* Elasticsearch version: 6.8.2
* Browser + version: Firefox 68.0.1

### Expected behavior:

* Open User-Dialog
* Search in Field "Organization" for an existing organization and select it
* Click the Save-button
![grafik](https://user-images.githubusercontent.com/24891375/62241088-c58a6500-b3d8-11e9-9713-5ea28a640a23.png)

### Actual behavior:

* No organizations are found / Autosuggest not loading

### Steps to reproduce the behavior:

* See expected behaviour

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but I do believe that this is rather a technical question.

Please ensure that your elasticsearch is running and if, that your search index is up to date.
If you're able to find the organization via search function, you should also find it when assigning it to a user.

If this issue still persists (and is not a technical question), please provide your production log.


Please note that our community is a better place for technical questions. :-)
( https://community.zammad.org )

**Comment by thorsteneckel** [comment]
I agree. Please make sure you Elasticsearch index is up to date and reachable. If the issue still persists please create a new topic over at the [community board](http://community.zammad.org/) and we will figure out if it's actually a bug. Closing now.

**Comment by 4d4ch4u32** [comment]
Thanks for feedback. I just posted this issue in your community board: https://community.zammad.org/t/cannot-add-user-to-organization/2934
