### ISSUE TITLE
ticket auto assignment is not working if only one excluded user is defined

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2692]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1056415

### Expected behavior:

* work also if only one user is selected as excluded

### Actual behavior:

* if only one user is excluded, feature is ignored - user gets assigned

### Steps to reproduce the behavior:

* enable ticket auto assignment in admin interface and select only one user to exclude
* open a ticket with this user and you see the auto assignment is still working for this single user

**Comment by MrGeneration** [comment]
Further input on that:
This happens, because Zammad saves a string with the ID instead of an array into it's setting, if you only provide one user.

You can workaround this issue via rails console as follows:
```ruby
Setting.get("ticket_auto_assignment_user_ids_ignore")     # returns number that you'll need next
Setting.set("ticket_auto_assignment_user_ids_ignore", [returned-number-of-earlier-command])
```

Mind adding the `[]`. Example:
```ruby
Setting.get("ticket_auto_assignment_user_ids_ignore")
# => 42
Setting.set("ticket_auto_assignment_user_ids_ignore", [42])
# => true
```
