### ISSUE TITLE
Missing autocompletion for customers, when redirecting a ticket

### ISSUE THREAD

**Issue by hoamer** [zammad/zammad#2693]
Hi,

when redirecting a ticket the autocompletion for customers isn't working.
Usually I would assume a request like "https://xxxxx.de/api/v1/search/user-organization?query=kontakt%40&_=15650789540".

Instead this request is made: "https://xxxxx.de/api/v1/users/search?term=kontakt%40".

### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: Debian
* Browser + version:FF+Chrome

### Expected behavior:

*"https://xxxxx.de/api/v1/search/user-organization?query=kontakt%40&_=15650789540".

### Actual behavior:

*Instead this request is made: "https://xxxxx.de/api/v1/users/search?term=kontakt%40".

### Steps to reproduce the behavior:

*Hit "redirect" inside a ticket
*Fill textbox "To" with a string

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Pls verify it this is a duplicate of https://github.com/zammad/zammad/issues/2684

**Comment by MrGeneration** [comment]
Duplicate of  #2684 
Please note that this is a technical question that should be fixed by rebuilding the search index.

For further help, please consult the community (https://community.zammad.org)

Thanks!
