### ISSUE TITLE
Zendesk import doesn't consider all tickets

### ISSUE THREAD

**Issue by dennykorsukewitz** [zammad/zammad#2694]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Imports all tickets.

### Actual behavior:

*  Zendesk ticket list endpoint doesn't return all entries. Tickets that are [archived](https://support.zendesk.com/hc/en-us/articles/203657756-About-ticket-archiving)  are not included and therefore not exprted/imported.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
The commit https://github.com/zammad/zammad/commit/dd5ca52e18491af428a158d7a2f381e1ea1e12ee introduced a regression so that this is an issue again.
