### ISSUE TITLE
Time zone incorrectly calculated in ticket list

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#2697]
T#1049736

### Infos:

* Used Zammad version: 3.1
* hosted instance
* Browser + version: Safari/Chrome

**actual behaviour**

The key figures of the ticket list are given out wrong. The time zones are not calculated correctly. In the Zammad interface everything is correct, when downloading it seems that GMT-2 is calculated instead of GMT+2.

**Steps to reproduce the behavior (hosted instance):**

- I took a created ticket, created at 07/08/2019 14:31 (Timezone GMT+2)
![image](https://user-images.githubusercontent.com/22768032/61380291-62adaf80-a8a9-11e9-9d4a-5e03bc976072.png)

- I created a report of all tickets and got this in the Reporting-mask:
![image](https://user-images.githubusercontent.com/22768032/61379951-c97e9900-a8a8-11e9-9ce7-de0b55b22892.png)

- but in the exported Excel ticket list, the timestamp is as follows: 
![image](https://user-images.githubusercontent.com/22768032/61380060-fdf25500-a8a8-11e9-8d2b-92c1610c58d1.png)

**Comment by MrGeneration** [comment]
This was partly covered by #2085 and is now it's own issue, because we're talking about two different issues here.
