### ISSUE TITLE
Zendesk: unknown article type fails import.

### ISSUE THREAD

**Issue by robbsie** [zammad/zammad#270]
I could not import zendesk data because of the following mysql error when importing:

```
Mysql2::Error: Field 'typeid' doesn't have a default value: INSERT INTO `ticketarticles` (`ticketid`, `body`, `messageid`, `updatedbyid`, `createdbyid`, `senderid`, `createdat`, `updatedat`, `messageid_md5`) VALUES (18424, '<div class=\"zd-comment\">\n<p dir=\"auto\">Hi,</p>\n<p dir=\"auto\">das klingt gut!</p>\n<p dir=\"auto\">Zendesk Ticket Text comes here<br>\nRobert </p>\n</div>', '64789087825', 3, 3, 1, '2016-10-22 08:26:00', '2016-10-22 08:26:00.998', '704fc71026cf68435d84350x0ed07fdf')`
```

Enviroment: CentOS 7 Zammad Package with MariaDB 10.0.27

**Comment by robbsie** [comment]
With postgresql we're getting this error:

```
PG::NotNullViolation: FEHLER: NULL-Wert in Spalte »type_id« verletzt Not-Null-Constraint DETAIL: Fehlgeschlagene Zeile enthält (43, 18424, null, 1, null, null, null, null, 64789087825, 704fc76026cf68435d84350c0ed07fdf, null, text/plain, null, <div class="zd-comment"> <p dir="auto">Hi,</p> <p dir="auto">das..., f, null, 3, 3, 2016-10-22 09:04:24.240973, 2016-10-22 09:04:24.24). : INSERT INTO "ticketarticles" ("ticketid", "body", "messageid", "updatedbyid", "createdbyid", "senderid", "createdat", "updatedat", "messageidmd5") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"
```
Version: postgresql 9.2.15 (CentOS 7)

**Comment by thorsteneckel** [comment]
Hi @robbsie - could you please check what type this article in zendesk has? It should be TicketID 43, text `Hi, das klingt gut!`. Seems we have missed this type in the following code block: https://github.com/zammad/zammad/blob/30fe8aef36489ecc4761a463d83b9a1cebad19fe/lib/import/zendesk.rb#L662

**Comment by robbsie** [comment]
Hi @thorsteneckel,

I've checked ticket 18424 (thats the ZenDesk ID I guess? 43 seems to be the 43rd anser in this  longer ticket). I was able to find the text `Hi, das klingt gut!` in there, so this seems to be the case ;)

This 43rd answer was sent with "Zendesk for iPhone", but I'm not sure if this is a valid type like 'web'.  Maybe its "API" or "Mobile SDK" when using the ZenDesk mobile apps?

**Comment by thorsteneckel** [comment]
Sorry for the delayed response! I'll get to it asap. I'll add a default fallback article type for not (yet) supported article types like this one.

**Comment by tobzsc** [comment]
Hey @thorsteneckel - do you have an update here? When are you able to fix this? This is actually the only bug stopping us migrating to zammad.

**Comment by thorsteneckel** [comment]
Hi @tobzsc - sorry for the delay! Actually it's on my stack for this week. So I'll provide a fix for it and let you know

**Comment by thorsteneckel** [comment]
Should be fixed with the commit above and released next week. Feedback is welcome!
