### ISSUE TITLE
Office365 login error 422: The change you wanted was rejected. in CHROME only

### ISSUE THREAD

**Issue by kvitaly2005** [zammad/zammad#2700]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): docker
* Operating system: Azure Linux
* Database + version: MySQL
* Elasticsearch version: Latest
* Browser + version: Chromium  72 and Chromium-based (Edge 76, Opera)

### Expected behavior:

* After pressing Office365 button Microsoft login page displayed. After account selection and succesful authentication,  dashboard page of Zammad opens.

### Actual behavior:

* I got error 422: The change you wanted was rejected. without redirecting to the Microsoft login page

### Steps to reproduce the behavior:

* Open configured to Office 365 authentication Zammad login page in Chromium-based browser. Press Office365 button. Error will be displayed.

I tested it with two app accounts under 5 different browsers and 3 PC

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please provide your production-logfile from the time where you're trying to do this.
Please ensure that the users mail address is not already known by Zammad.

If it is, ensure that you link the account first or enable automatic linking.

Personally I suspect that this is rather a technical question than a bug.


Note:
If you're using docker, I suppose you're using docker-compose - if not, please let us know.
Please also note that docker-compose (and actually docker-single image shouldn't as well) is not using MySQL. If you're using MySQL, that doesn't look like a default package which we can't support.

**Comment by kvitaly2005** [comment]
Hi and thanks for info, I tested it in trial version and it seems to be a Azure & Chrome issue. I will close the issue as not a bug.
