### ISSUE TITLE
Can't forward articles containing a <img> tag without src attribute

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2701]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Follow-up / similare to: #2305
* Ticket-ID: #1048219

### Expected behavior:

When having a not that clean email, Zammad would still allow forwarding mails if needed.

### Actual behavior:

When having a invalid/broken/empty image tag ( `<img alt="meh!">`) inside an HTML-Mail, Zammad will hate this trick and no longer allow forwarding the affected mail. 

### Steps to reproduce the behavior:

* create a mail with invalid image tags 
* fetch the mail
*  try to forward it somewhere else

### Sample mail:

```
From: Zammad <Zammad@example.com>
Content-Type: multipart/alternative;
  boundary="Apple-Mail=_3DAE81E1-8D92-4A1E-A371-3CC2BF9286BB"
Subject: I send you a broken image with love but without src
To: zammad@example.com


--Apple-Mail=_3DAE81E1-8D92-4A1E-A371-3CC2BF9286BB
Content-Transfer-Encoding: 7bit
Content-Type: text/html;
  charset=us-ascii

<html>
<body>
<img alt=3D"Zammad - =
The Ticketing Experts">
</body></html>
--Apple-Mail=_3DAE81E1-8D92-4A1E-A371-3CC2BF9286BB--
```

### Possible solution (needs testing):

``` diff
diff --git a/app/assets/javascripts/app/lib/app_post/utils.coffee b/app/assets/javascripts/app/lib/app_post/utils.coffee
index 4efc203b1..9fd1a4062 100644
--- a/app/assets/javascripts/app/lib/app_post/utils.coffee
+++ b/app/assets/javascripts/app/lib/app_post/utils.coffee
@@ -1205,7 +1205,7 @@ class App.Utils
 
     html.find('img').each( (index) ->
       src = $(@).attr('src')
-      if !src.match(/^(data|cid):/i) # <img src="cid: ..."> may mean broken emails (see issue #2305)
+      if src && !src.match(/^(data|cid):/i) # <img src="cid: ..."> may mean broken emails (see issue #2305)
         base64 = App.Utils._htmlImage2DataUrl(@)
         $(@).attr('src', base64)
     )
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rlue** [comment]
@MrGeneration, can you clarify what the bug is and how to reproduce it? Here's where I am:

1. Create the given sample raw mail file:

   ```
   # mail.box

   From: Zammad <Zammad@example.com>
   Content-Type: multipart/alternative;
     boundary="Apple-Mail=_3DAE81E1-8D92-4A1E-A371-3CC2BF9286BB"
   Subject: I send you a broken image with love but without src
   To: zammad@example.com
   
   
   --Apple-Mail=_3DAE81E1-8D92-4A1E-A371-3CC2BF9286BB
   Content-Transfer-Encoding: 7bit
   Content-Type: text/html;
     charset=us-ascii
   
   <html>
   <body>
   <img alt=3D"Zammad - =
   The Ticketing Experts">
   </body></html>
   --Apple-Mail=_3DAE81E1-8D92-4A1E-A371-3CC2BF9286BB--
   ```

2. Import it into Zammad via the rails console. (This successfully creates a ticket and article.)

   ```ruby
   $ rails console
   >> Channel::EmailParser.new.process({}, File.read('mail.box'))
   ```

3. View the ticket in the Zammad web interface. (The `img` tag results in a broken image element on the page.)

   ![Screenshot_20191011_135401](https://user-images.githubusercontent.com/12194123/66627759-42cf2300-ec2f-11e9-980d-c974a496a009.png)

This appears to be a valid bug, but not the same one as the one you're describing:

> Zammad will hate this trick and not import the mail.

Is there another way to "fetch" or "import" mail that I'm not aware of?

---

FWIW I did all this on the `develop` branch.

**Note:** the `img` tag appears to be mis-parsed and saved into the article body like so:

```
 #<Ticket::Article:0x0000561448424818
  ...
  body: "<img alt='3D\"Zammad'>",
  ...>
```

Are we also considering this a bug? Should the `img` tag be stripped entirely from the body? Should it be sanitized? Or is it fine the way it is?

**Comment by MrGeneration** [comment]
Hey Ryan,

sorry! This described really bad (and way off!).
I was wrong with the mail processing part, this is about "I can't forward mails if the image-tag is empty" caused by our javascripts.

Really sorry for sending you in the wrong direction!
I'll update the first article asap.

This should appear on your console log:
```
Uncaught TypeError: Cannot read property 'match' of undefined
at HTMLImageElement.<anonymous> (application-e18d335b0b33e337f6b64b3d448b2084bcaff05a543848f158bacb6754d5efb2.js:78)
at Function.each (application-e18d335b0b33e337f6b64b3d448b2084bcaff05a543848f158bacb6754d5efb2.js:1)
at rt.fn.init.each (application-e18d335b0b33e337f6b64b3d448b2084bcaff05a543848f158bacb6754d5efb2.js:1)
at Function.t.htmlImage2DataUrl (application-e18d335b0b33e337f6b64b3d448b2084bcaff05a543848f158bacb6754d5efb2.js:78)
at Function.e.emailForward (application-e18d335b0b33e337f6b64b3d448b2084bcaff05a543848f158bacb6754d5efb2.js:48)
at Function.e.perform (application-e18d335b0b33e337f6b64b3d448b2084bcaff05a543848f158bacb6754d5efb2.js:48)
at e.actionPerform (application-e18d335b0b33e337f6b64b3d448b2084bcaff05a543848f158bacb6754d5efb2.js:48)
at e.actionPerform (application-e18d335b0b33e337f6b64b3d448b2084bcaff05a543848f158bacb6754d5efb2.js:48)
at HTMLAnchorElement.<anonymous> (application-e18d335b0b33e337f6b64b3d448b2084bcaff05a543848f158bacb6754d5efb2.js:8)
at HTMLDivElement.dispatch (application-e18d335b0b33e337f6b64b3d448b2084bcaff05a543848f158bacb6754d5efb2.js:2)
```
