### ISSUE TITLE
Ticket auto assignment exceptions should not display customer user

### ISSUE THREAD

**Issue by dennykorsukewitz** [zammad/zammad#2707]
### Infos:

* Used Zammad version: 3.1.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any 

### Expected behavior:

* The expectation is that you can only select agents (not customers).

<img width="828" alt="Zammad_Helpdesk_-_Ticket" src="https://user-images.githubusercontent.com/3249687/63264092-8722f000-c28a-11e9-89f3-31f9710dc962.png">

### Actual behavior:

* You can select all types (Admin, Agent, Customer) of users.

<img width="821" alt="Zammad_Helpdesk_-_Ticket" src="https://user-images.githubusercontent.com/3249687/63264039-63f84080-c28a-11e9-927d-58404bc43528.png">

### Steps to reproduce the behavior:

* Create a agent and a customer
* go to Ticket -> Auto Assignment

**Comment by dominikklein** [comment]
Should be handled together with: https://github.com/zammad/zammad/issues/2443
