### ISSUE TITLE
"Is required" untranslatable

### ISSUE THREAD

**Issue by maxxer** [zammad/zammad#2709]
### Infos:

* Used Zammad version: 3.0.x
* Installation method (source, package, ..): Docker
* Operating system: Ubuntu 16.04
* Database + version: Docker
* Elasticsearch version: Docker

I was creating a new contact from within issue creation.

![immagine](https://user-images.githubusercontent.com/240201/63323694-b5560d80-c326-11e9-9ab4-ad256b5eb845.png)

**Comment by MrGeneration** [comment]
`is required` currently can't be translated.
As we already have `required` in our list (and I also think this as a single word is totally enough, we also should change this).

If one word is enough, I'd prefer `field required` or `field is required`.

**Comment by mgruner** [comment]
Will be fixed with the upcoming Weblate migration in Zammad 5.1.
