### ISSUE TITLE
When quicktext at beginning of text body is removed cursor jumps out of scope

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2712]
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: any
* Elasticsearch version: any
* Browser + version: Firefox latest

Referenced from:
https://github.com/zammad/zammad/issues/2711#issuecomment-522993384

### Expected behavior:

* When at the beginning of a text body quick text is lanched with :: and delected directly cursor should stay in the text field.

### Actual behavior:

*
![quicktext_comment](https://user-images.githubusercontent.com/44224243/63360710-27524500-c36f-11e9-906a-00d91419be19.gif)

### Steps to reproduce the behavior:

* Write :: at the beginning of an e.g. empty comment box in any ticket. If you remove the :: directly with backspace the cursor pops out.
This works on new tickets, comments and replys. 
Essentially on any article text field where quicktext might be used.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dennykorsukewitz** [comment]
Hi,

currently I can only reproduce this behavior in Firefox.
@mrflix Can you take a look at this, please?

**Comment by MrGeneration** [comment]
This happens in Chrome as well, but is waaaaaaaaaaaaaaaay less visible. (It's a really small jump :) )

**Comment by dominikklein** [comment]
Seems to be that the visual problem no longer exists.
