### ISSUE TITLE
Knowledge Base does't support animated GIFs and embedded Video (Youtube/Vimeo) content.

### ISSUE THREAD

**Issue by shakalandy** [zammad/zammad#2713]
### Infos:

* Used Zammad version:  3.1.0
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 
* Database + version: MySQL 5.7.27
* Elasticsearch version: 5.6.16
* Browser + version: Chrome 76.0

### Expected behavior:

* Animated GIFs work after saving in KB Editor

### Actual behavior:

* Animated GIF can be copied in editor, is removed after saving and not shown online.

### Steps to reproduce the behavior:

* Edit a KB entry
* Copy & Paste a GIF (we use it as howto video)
* Save KB entry
* KB entry is shown without GIF

In my opinion it's a bug, because i can copy it into the editor.

![image](https://user-images.githubusercontent.com/182060/63368506-5cb25f00-c37e-11e9-8659-3cb1f68cbd84.png)

**Comment by MrGeneration** [comment]
I don't see this as a bug to be honest.
If you copy a gif from clipboard to any place into Zammad, the gif will not move, but just provide a single image.

@thorsteneckel  what do you think?

This is a technical limitation.

**Comment by shakalandy** [comment]
@MrGeneration Hm, if i poste a animated GIF into the KB it moves (in Chrome). After saving it's lost.
I thought this might be a bug because it's possible in editor to add a gif (via copy & paste)

In my opinion this should be possible as a lightweight solution for "how-to" videos in the KB.
Should i fill a enhancement request somewhere else? Possible to sponsor it?

**Comment by thorsteneckel** [comment]
I agree that we should support animated GIFs/videos etc. However, we currently face higher prioritized tasks (unfortunately). Great to hear about you're interest in sponsoring that feature @shakalandy 😍 please reach out to my colleagues over at contact@zammad.com 📫

**Comment by shakalandy** [comment]
@thorsteneckel thanks for the reply. contact @ bounced - wrote to enjoy@zammad.com instead.

**Comment by MrGeneration** [comment]
Thanks, I'll handle your request asap. ;)

**Comment by shakalandy** [comment]
Hey guys,

unfortunately this one didn't make it into 3.3.0 - any help needed on that?

**Comment by thorsteneckel** [comment]
@mantas - can you please have a look? I've thought that the change supports that?

**Comment by MrGeneration** [comment]
GIF images work without any issues, just tested that.
However: Youtube and Vimeo are not working, because of content security policies:

![image](https://user-images.githubusercontent.com/6549061/75860465-29a45a00-5dfc-11ea-9e9f-32affc79b167.png)


I really am not sure why it needs to talk to `log.zammad.com` and `images.zammad.com` ?

**Comment by thorsteneckel** [comment]
@shakalandy - would you mind reaching out to support at zammad.com? We'll find out why it wouldn't work on your side.

@mantas - could you please extend [this list](https://github.com/zammad/zammad/blob/e61fa6795e9844c78e130533a0f20d5dee8b7201/config/initializers/content_security_policy.rb#L32) with the required domains and create a MR for it?

**Comment by thorsteneckel** [comment]
Because @MrGeneration can't reproduce the issue we handle it as a new issue (in case there is one) but not as a missing implementation (as I thought it would be). Therefore we'll create a new, regression issue if needed and keep this one closed.

**Comment by shakalandy** [comment]
Ok, will do @thorsteneckel  - colleagues checked the implementation and it didn't work so far.

Will recheck and fill new issue/support case - thanks.

**Comment by MrGeneration** [comment]
Just a very quick follow up on this for hotfixes - add the following line to `/opt/zammad/config/initializers/content_security_policy.rb` :

`policy.frame_src   'http://www.youtube.com', 'https://player.vimeo.com'` 
(below the other policies)

Keep in mind it's not update safe, restart Zammad after.

Personally I'd prefer to explicity the `frame-src` directive instead of `default-srv` :)

**Comment by thorsteneckel** [comment]
Hey @MrGeneration - good point. Please create a new issue for this and don't hijack unrelated, closed issues 😜

**Comment by shakalandy** [comment]
Ok guys, sorry for re-posting in closed issue.
what works now:

- Uploading animated GIFs through "add image" functionality.

What does not work:

- Copy & Paste of GIF Videos in Chrome - they can be copied via standard chrome functionality, but are stored as static image - don't know if this is a "feature" of Chrome or Zammad - but - the functionality works.

Video display from Youtube works via adding CSP headers as described by @MrGeneration - thanks & Great work.

**Comment by MrGeneration** [comment]
> Copy & Paste of GIF Videos in Chrome - they can be copied via standard chrome functionality, but are stored as static image - don't know if this is a "feature" of Chrome or Zammad - but - the functionality works.

Is technically not possible by nature! Copy pasting GIFs is not supported by Browsers in general. You have to use the image button (that's the reason it appeared). So that's working like intended. :)
