### ISSUE TITLE
Twitter-URLs (show this on twitter) are no longer valid / working

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2715]
### Infos:

* Used Zammad version: 3.1 (basically any)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Google Chrome latest (but still, any ;) )
* Ticket-ID: #1051924

### Expected behavior:

* When Zammad imports a tweet, it will set the correct twitter-URL to the tweet on twitter. This will allow the agent to view the tweet online. (dive into an conversation, view more information etc)
* When receiving direct messages, the URL on the article will lead the agent to the direct message conversation on the twitter page.

### Actual behavior:

* When receiving a tweet, Zammad will set a incorrect URL to twitter which makes it impossible to view the tweet online.
* When receiving a direct message, Zammad will set a incorrect URL to that conversation. This makes it impossible to view the conversation online.

See `further information` below for more detailed information.

### Steps to reproduce the behavior:

**The direct message way**
* send a direct message via a twitter account to a twitter account that's handled by Zammad
* wait for Zammad to do magic
* expand the twitter article you received and click on the `on Twitter` URL

![image](https://user-images.githubusercontent.com/6549061/63452786-6fdd3180-c447-11e9-9bcf-10e786d568f5.png)

**The tweet way**
* Create a new tweet with either a keyword (if your Zammad listens to that) or e.g. a direct mention
* wait for Zammad to do magic
* expand the twitter article you received and click on the `on Twitter` URL

![image](https://user-images.githubusercontent.com/6549061/63452847-97cc9500-c447-11e9-94a2-d89aca14dd66.png)

Both above clicks will lead to an error page.

### Further information:
This seems to be one of the offending lines:

https://github.com/zammad/zammad/blob/develop/lib/twitter_sync.rb#L390

As an example, on a public tweet, this is what Zammad currently would provide as URL within the article: `https://twitter.com/statuses/1164217960938049536` while this URL is broken and wrong, this is what it should be: `https://twitter.com/mr_generation/status/1164217960938049536`.

(Note `statuses` becomes `status` and also the twitter-username (in my case `mr_generation`) is appended in front of it)

Direct messages no longer have the statuses URL as well.
I didn't find any useful reference on how the URL can be built. 
My guess is the following (as I would expect to get into the conversation on twitter when clicking the link): `https://twitter.com/messages/{User-ID1}-{User-ID2}`

User-ID1 and User-ID2 can differ and don't always seem to be in the same order. It seems like it's relevant on who started the conversation and seems to be both user IDs that are writing with each other. This might be a bit trickier because of that.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rlue** [comment]
Hm. Not sure what promises twitter makes about its URL naming scheme. FWIW, it looks like it's not so strict about the handle you use: both of the following URLs work:

* <https://twitter.com/_/status/1164217960938049536>
* <https://twitter.com/_/statuses/1164217960938049536>

Fun to play with this stuff when you're just trying to shorten a URL to send to your friends in a WhatsApp message; not so fun when you're trying to determine how Zammad will shorten all these links in the future. Anybody know where Twitter documents these things? I don't think the API docs are the right place to look—we're talking about human-facing URLs here...

**Comment by thorsteneckel** [comment]
Hi @MrGeneration - I'm currently looking into the changes @rlue made to change the support schema. While doing some QA **I noticed that the tweet/status link format actually works**. The example link you posted in the initial issue ( https://twitter.com/statuses/1164217960938049536 ) works as well.
Maybe there was a short outtake on that endpoint or the people at Twitter changed their minds and supported the schema again. Anyhow, currently **I don't see a need to change the tweet/status link format** because both result in a redirect and the URL schema `https://twitter.com/statuses/1164217960938049536` looks cleaner.

**For the direct messages part of the issue: I think the issue here is that direct messages don't support direct links at all.** All I found was [a StackOverflow question/answer](https://stackoverflow.com/a/23013585) that states that you can only link to a conversation in general via e.g. `https://twitter.com/direct_messages/create/Mr_Generation`. This works for me.
However, it looks like we don't make a difference between tweets/states and direct messages:

https://github.com/zammad/zammad/blob/d58233d0cec6642830bc297065f69b7fd5667f23/lib/twitter_sync.rb#L303-L312

I think this is the real issue. **We should have a dedicated link format for direct messages** like
 `https://twitter.com/direct_messages/create/#{tweet.author.handle}` (pseudo).

**Comment by SalocinHB** [comment]
> Maybe there was a short outtake on that endpoint or the people at Twitter changed their minds and supported the schema again.

It didn't work for months, so I assume they changed their minds.

**Comment by rlue** [comment]
> I think this is the real issue. **We should have a dedicated link format for direct messages** like
`https://twitter.com/direct_messages/create/#{tweet.author.handle}` (pseudo).

Three things:

1. Does this mean that `TwitterSync#to_article` should be modified to support DMs as well as statuses? It looks like [it currently only works for statuses](https://github.com/zammad/zammad/blob/develop/lib/twitter_sync.rb#L348), and it’s one of the three places in Zammad where tweet URLs are hardcoded.

2. The following URL scheme also works:

   > https://twitter.com/messages/<recipient_id>-<your_id>

   I prefer this one, because `Twitter::DirectMessage` objects only store
   numeric IDs for senders/recipients, not screen names, so using
   `/direct_message/create/<screen_name>` requires an additional network
   request.

3. The `TwitterSync#from_article` method sends DMs [using an explicit call to the v1.1 API](https://github.com/zammad/zammad/blob/develop/lib/twitter_sync.rb#L454-L481):

   ```ruby
   data = {
     event: {
       type:           'message_create',
       message_create: {
         target:       {
           recipient_id: authorization.uid,
         },
         message_data: {
           text: article[:body],
         }
       }
     }
   }

   tweet = Twitter::REST::Request.new(@client, :json_post, '/1.1/direct_messages/events/new.json', data).perform
   ```

   This could be significantly shortened using the
   `Twitter::Client#create_direct_message` method, instead:

   ```ruby
   @client.create_direct_message(authorization.uid, article[:body])
   ```

   **But there’s one small snag!** These two approaches returns different values:

   ```ruby
   >> Twitter::REST::Request.new(...).perform
   => {:event=>
     {:type=>"message_create",
      :id=>"1192017246085795844",
      :created_timestamp=>"1573034032733",
      :message_create=>
       {:target=>{:recipient_id=>"2474118319"},
        :sender_id=>"2975699229",
        :message_data=>
         {:text=>"hey dude this is a test",
          :entities=>{:hashtags=>[], :symbols=>[], :user_mentions=>[], :urls=>[]}}}}}

   >> client.create_direct_message('2474118319', 'hey dude this is a test')
   => #<Twitter::DirectMessage id=1192018967092547589>
   ```

   And the return value of this method is used in various places, so changing
   it means we need to change code in a few other places, too.

   **Are we confident enough in the existing test suite to switch to
   `#create_direct_message`, or should we stick to the old
   `Request.new.perform` approach for now?**

**Comment by thorsteneckel** [comment]
> 1. Does this mean that `TwitterSync#to_article` should be modified to support DMs as well as statuses? It looks like [it currently only works for statuses](https://github.com/zammad/zammad/blob/develop/lib/twitter_sync.rb#L348), and it’s one of the three places in Zammad where tweet URLs are hardcoded.

As far as I remember you get the messages via an incoming webhook which calls [`to_article_webhook`](https://github.com/zammad/zammad/blob/022efe7921ea2ac303c50c24913f14700f682513/lib/twitter_sync.rb#L179) which [handles messages](https://github.com/zammad/zammad/blob/022efe7921ea2ac303c50c24913f14700f682513/lib/twitter_sync.rb#L196).

> 2. The following URL scheme also works:
>    > https://twitter.com/messages/<recipient_id>-<your_id>
>    
>    I prefer this one, because `Twitter::DirectMessage` objects only store
>    numeric IDs for senders/recipients, not screen names, so using
>    `/direct_message/create/<screen_name>` requires an additional network
>    request.

Great catch! I'd prefer this one too 🚀 

> 3. The `TwitterSync#from_article` method sends DMs [using an explicit call to the v1.1 API](https://github.com/zammad/zammad/blob/develop/lib/twitter_sync.rb#L454-L481):
>    ```ruby
>    data = {
>      event: {
>        type:           'message_create',
>        message_create: {
>          target:       {
>            recipient_id: authorization.uid,
>          },
>          message_data: {
>            text: article[:body],
>          }
>        }
>      }
>    }
>    
>    tweet = Twitter::REST::Request.new(@client, :json_post, '/1.1/direct_messages/events/new.json', data).perform
>    ```
>    
>    
>    This could be significantly shortened using the
>    `Twitter::Client#create_direct_message` method, instead:
>    ```ruby
>    @client.create_direct_message(authorization.uid, article[:body])
>    ```
>    
>    
>    **But there’s one small snag!** These two approaches returns different values:
>    ```ruby
>    >> Twitter::REST::Request.new(...).perform
>    => {:event=>
>      {:type=>"message_create",
>       :id=>"1192017246085795844",
>       :created_timestamp=>"1573034032733",
>       :message_create=>
>        {:target=>{:recipient_id=>"2474118319"},
>         :sender_id=>"2975699229",
>         :message_data=>
>          {:text=>"hey dude this is a test",
>           :entities=>{:hashtags=>[], :symbols=>[], :user_mentions=>[], :urls=>[]}}}}}
>    
>    >> client.create_direct_message('2474118319', 'hey dude this is a test')
>    => #<Twitter::DirectMessage id=1192018967092547589>
>    ```
>    
>    
>    And the return value of this method is used in various places, so changing
>    it means we need to change code in a few other places, too.
>    **Are we confident enough in the existing test suite to switch to
>    `#create_direct_message`, or should we stick to the old
>    `Request.new.perform` approach for now?**

IIRC this client method wasn't available when the "new Twitter API" went live but only a PR was open. We had to use this direct call to work around it.
TBH our twitter tests are a mess. You'll get the legendary status in the Zammad hall of fame and more when you provide a reliable Twitter test coverage - literally. You could burn it down and start from scratch if you want to. Once we got the coverage we can resolve this and other issues. It's up to you. I'll support you with all I can and make sure you get a reward ✌️This is a real pain point.

**Comment by rlue** [comment]
Great to know! I'll get to work on a commit that makes the minimal change necessary to fix the bug, then worry about the bigger changes after.

Forgot to ask about something I'd noticed while working through this code. `Observer::Ticket::Article::CommunicateTwitter::BackgroundJob#perform` has [a little block of code that doesn't look quite right](https://github.com/zammad/zammad/blob/develop/app/models/observer/ticket/article/communicate_twitter/background_job.rb#L73-L97)—is it correct that we only set `article.preferences['twitter']` if the tweet contains some user mentions?

**Comment by SalocinHB** [comment]
I just noticed that the https://twitter.com/statuses/* links seem to work only when you are not logged in to the Twitter web client in your browser. When I try to open https://twitter.com/statuses/1191288644813893635 in an incognito window, I'm redirected to https://twitter.com/TwitterDE/status/1191288644813893635, but if I open the same link (https://twitter.com/statuses/1191288644813893635) in another window where I'm logged in to the Twitter web client, I get a 404.

**Comment by thorsteneckel** [comment]
Hi Nico. I can't confirm that. I'm not logged (and have any cookies blocked) in but I can open the link https://twitter.com/statuses/1191288644813893635 and get redirected to https://twitter.com/TwitterDE/status/1191288644813893635 . However, I sometimes notice that when I'm opening twitter links on my smartphone from e.g. the reddit app I get the 404 . Copying the link to Safari or Firefox Klar works. Idk why this is the case...

**Comment by SalocinHB** [comment]
@thorsteneckel that's exactly what I wrote. Not logged in = link works. Logged in = doesn't work.

**Comment by thorsteneckel** [comment]
Ouch! Sorry, my bad. You are right! I can confirm the behavior exactly as you described it.

**Comment by SalocinHB** [comment]
@thorsteneckel your commit only mentions the broken DM links, not the status links. Are those fixed in the same commit or should I reopen this issue?

**Comment by thorsteneckel** [comment]
Hi @SalocinHB - IDK why but GitHub hasn't referenced the second commit from the same change: https://github.com/zammad/zammad/commit/147cbc29b808e6849c759c675ba2747b2689a0b5

Those two cover the DMs and Status updates dedicatedly.
