### ISSUE TITLE
System mail notification subjects ending with =0A

### ISSUE THREAD

**Issue by morph027** [zammad/zammad#2726]
### Infos:

* Used Zammad version: 3.1.0-14 (zammad/zammad-docker-compose:zammad-3.1.0-14)
* Installation method (source, package, ..): Docker
* Operating system: ...
* Database + version: Postgresql 9.6 (from zammad/zammad-docker-compose:zammad-postgresql-3.1.0-14)
* Elasticsearch version: 5.6.14 (from zammad/zammad-docker-compose:zammad-elasticsearch-3.1.0-14)

### Expected behavior:

* Not having linebreaks encoded with `=0A`

### Actual behavior:

* Mail subjects have `=0A` at the end

### Steps to reproduce the behavior:

* clone [docker-compose](https://hub.docker.com/r/zammad/zammad-docker-compose/) repo
* apply this patch to get a local test mailserver:

```patch
diff --git a/docker-compose.yml b/docker-compose.yml
index 1cf66f2..7e9c062 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -99,6 +99,13 @@ services:
     volumes:
       - zammad-data:/opt/zammad
 
+  mailserver:
+    image: inbucket/inbucket
+    ports:
+      - "9000:9000"
+      - "2500:2500"
+      - "1100:1100"
+
 volumes:
   elasticsearch-data:
     driver: local
```

* start stack: `docker-compose up` (do not forget to apply sysctl settings for ES)
* finish wizard with SMTP support at host `mailserver` and port 2500 (no user or password)
* logout
* reset password
* have a look at the mailserver at http://localhost:9000

![Screenshot from 2019-09-02 09-08-30](https://user-images.githubusercontent.com/600106/64096190-4682a680-cd61-11e9-89bd-eb62b04f124f.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by morph027** [comment]
Database lists as UTF8 in psql

```
 zammad    | zammad   | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
```

**Comment by morph027** [comment]
![screenshot_1](https://user-images.githubusercontent.com/600106/64065155-43c16d80-cc0a-11e9-9031-5faf905a3aa9.png)

**Comment by morph027** [comment]
Seems to happen to system mails only, which are including a line break at the end

![screenshot_2](https://user-images.githubusercontent.com/600106/64065509-addc1180-cc0e-11e9-9cb9-18d0b8fecb52.png)

System mail (`)` is on a new line):

```
I, [2019-08-31T14:38:59.306078 #1-47007308955680]  INFO -- : Send notification to: #redacted# (from:Notification Master <noreply@#redacted#>/subject:Invitation to Zammad Helpdesk at #redacted#
)
```

Ticket mail:

```
I, [2019-08-31T14:42:37.573724 #1-46983869476280]  INFO -- : Send notification to: #redacted# (from:Notification Master <noreply@#redacted#>/subject:Updated Ticket (Welcome to Zammad!) [Ticket#39001])
```

**Comment by morph027** [comment]
Also got the same in official zammad bug tracker ;)

![screenshot_3](https://user-images.githubusercontent.com/600106/64426381-ae612600-d0ae-11e9-853b-fe96629ecb95.png)

**Comment by MrGeneration** [comment]
Well sorry I should have commented the issue ;)
I verified it, we will address it as soon as we find the time to do so. :-)

We'll update this issues accordingly as soon as there's news to it.

**Comment by jmptbl** [comment]
Maybe this helps someone:

```
--- lib/notification_factory.rb.orig	2020-03-06 21:05:35.332900238 +0000
+++ lib/notification_factory.rb	2020-03-06 21:05:47.328869459 +0000
@@ -32,7 +32,7 @@
   def self.template_read(data)
     template = File.readlines(template_path(data))

-    { subject: template.shift, body: template.join }
+    { subject: template.shift.chomp, body: template.join }
   end

   def self.template_path(data)
```
