### ISSUE TITLE
Knowledge Base syntax highlighting/markdown support

### ISSUE THREAD

**Issue by nublaii** [zammad/zammad#2729]
**Infos:**

    Used Zammad version: 3.1
    Installation method (source, package, ..): any
    Operating system: any
    Database + version: any
    Elasticsearch version: any
    Browser + version: any

**Desired behavior:**

It would be great to be able to add support for syntax highlighting and/or markdown on the body of an answer, right now everything is just plain text (except italics, bold and underline that is).

Specifically it would be great to add the option of pasting code, or commands to execute, and being able to hightlight it, or use monospace font...

**Comment by MrGeneration** [comment]
Sorry, but this is a feature request which is the wrong place for this repository.
Please do only post bug reports on this repo.

For technical questions or enhancement request, the Zammad Community is the better place: https://community.zammad.org

Also, for this exact request we already do have a request on the community: 
https://community.zammad.org/t/knowledge-base-better-editor-or-markdown-rst-support/2612


Closing now.
