### ISSUE TITLE
PG::UndefinedTable: ERROR: relation “groups_text_modules” does not exist

### ISSUE THREAD

**Issue by steschuser** [zammad/zammad#2731]
### Infos:

* Used Zammad version: 3.1 (Upgrade from 2.9)
* Installation method (source, package, ..): Debian Package
* Operating system: Debian Linux 9
* Database + version: 10.1.38-MariaDB-0+deb9u1 Debian 9.8
* Elasticsearch version: -
* Browser + version: All

### Expected behavior:

Creation of new Textmodul should work

### Actual behavior:

Error message flashes:
PG::UndefinedTable: ERROR: relation "groups_text_modules" does not exist LINE 8: WHERE a.attrelid = '"groups_text_modules"'::r... ^ : SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod, c.collname, col_description(a.attrelid, a.attnum) AS comment FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum LEFT JOIN pg_type t ON a.atttypid = t.oid LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation WHERE a.attrelid = '"groups_text_modules"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum

**Comment by MrGeneration** [comment]
Sorry but I believe that this is a technical question, which should live in the Community: https://community.zammad.org

I suspect you upgraded (without checking the high amount of output) and the upgrade didn't finish.

Run `zammad run rake db:migrate` and restart Zamamd, you should be fine.

Closing now.

**Comment by steschuser** [comment]
I did open an issue there as well.

zammad run rake db:migrate solved it tho.
thx

**Comment by MrGeneration** [comment]
For the next time, please only choose one place. :-) 
Saves time for everyone. :)
