### ISSUE TITLE
Show external user information (webhook)

### ISSUE THREAD

**Issue by pgtaboada** [zammad/zammad#2733]
I am currently using another ticket system that has one very nice feature: webhooks for external information.

Every time a ticket is opened, the ticket system calls a pre-configured url and passes all email addresses associated with that ticket, eg:

https://my.server.com?emails=bla@blup.com;blup@bla.com

The called must respond html that simply will be embeded in the ticket view in the customer section. 

This way I am currently able to provide all sorts of live information out of my application to the ticket/ agent.

This integration is simple to implement, does not have all the problems when you have to sync data between systems and the integration can be done on browser level, so it does not use server side resources.

**Comment by MrGeneration** [comment]
Sorry, but technical questions and enhancement requests are the wrong place.
For new feature requests, please use the Community (https://community.zammad.org) for this!


Beside this, we already do have a issue for this, it can be found here:
https://github.com/zammad/zammad/issues/290

I'll be closing this as duplicate for now :)

**Comment by pgtaboada** [comment]
I saw that ticket and thought it would be the right way to provide a feature request. It is not a duplicate to  #290, I guess I used the wrong name (webhook) to describe the feature request.

Thanks for the link to the community area, I created the feature request:

https://community.zammad.org/t/embed-show-external-data-in-ticket-view/3063
