### ISSUE TITLE
chat not working / http 404

### ISSUE THREAD

**Issue by wagnst** [zammad/zammad#274]
I get a http 404 from the /ws element when including the JS files on a static html site.

Headers are correctly filled.

Log says e.g. 
`Firefox can’t establish a connection to the server at ws://xxx/ws.`

Any ideas, how to debug?

**Comment by wagnst** [comment]
related to #273?

**Comment by Frankstar** [comment]
since you referenced to my issue, what do you use for Reversy Proxy?
can u show the related file (apache,nginx,haproxy, ..)

**Comment by wagnst** [comment]
I use nginx as rewrite proxy and now put the following into it (thanks to your hint, the ws is on another port)

```
 88   location =/ws {
 89     proxy_pass            http://internal:6042;
 90     proxy_http_version 1.1;
 91     proxy_set_header Upgrade $http_upgrade;
 92     proxy_set_header Connection "upgrade";
 93   }
```

**Comment by Frankstar** [comment]
can u show us the full `/nginx/sites-available/zammad.conf` pls

**Comment by wagnst** [comment]
I'm not using a local nginx on the zammad box. My central nginx is doing a reverse proxy to ruby on port 3000 and with the location above to the web socket.

**Comment by wagnst** [comment]
OK, fixed this now. Everything looks good, except that the popup does not show up now...
Chat is active, agent is online,.....
debug log showing:

```
chat debug || lang: enchat.min.js:1:1339
chat debug || load css from 'https://xxx/assets/chat/chat.css'chat.min.js:1:1339
io debug || Connecting to wss://xxx/wschat.min.js:1:1339
io debug || onOpen open { target: WebSocket, isTrusted: true, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1477181680098435, originalTarget: WebSocket, explicitOriginalTarget: WebSocket, NONE: 0 }chat.min.js:1:1339
chat debug || widget renderedchat.min.js:1:1339
idleTimeout debug || Start timeout in 6 minuteschat.min.js:1:1339
io debug || send chat_status_customer Object { session_id: null, url: "https://xxx/", chat_id: 1 }chat.min.js:1:1339
io debug || onMessage [{"event":"chat_error","data":{"state":"chat_disabled"}}]chat.min.js:1:1339
chat debug || ws:onmessage Object { event: "chat_error", data: Object }chat.min.js:1:1339
chat notice || Object { state: "chat_disabled" }chat.min.js:1:1339
chat debug || destroy widget Object { remove: true }chat.min.js:1:1339
idleTimeout debug || Stop timeout of 6 minuteschat.min.js:1:1339
io debug || close websocket manuallychat.min.js:1:1339
io debug || close websocket connection close { target: WebSocket, isTrusted: true, wasClean: true, code: 1000, reason: "", currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1477181680257926 }chat.min.js:1:1339
io debug || manual close, onClose callback
```

**Comment by martini** [comment]
@wagnst the connections seems to be fine. Maybe the widget is not shown on the webpage because of CSS issues (e. g. z-index issue). So can check if the widget is on you web page?

$('.zammad-chat').length

If it's on the webpage, can you check with the inspector where it is located in the page?

Can I have access to the web page via browser?

**Comment by wagnst** [comment]
@martini  I don't see the widget (also through inspector), although I have included as stated via Javascript.
```
$('.zammad-chat').length
0
```

The website is `https://cubyte.net`, i'm also online right now, so the prerequesits should be fulfilled. Thanks for your help!

**Comment by martini** [comment]
@mrflix The customer chat is not shown up on https://cubyte.net. If I execute the following, it is shown. Any ideas?

new ZammadChat({
title: '<strong>Chat</chat> with us!',
background: 'rgb(77,77,77)',
fontSize: '12px',
chatId: 2,
target: $(‘.jsme'),
debug: true
});

**Comment by wagnst** [comment]
i have put the target attribute and an empty referring <div> to the page and with that it seems to work!

**Comment by m4r71n** [comment]
@wagnst move the two `<script>`
```
<!-- Zammad Support Code -->
<script id="zammad_form_script" src="https://support.cubyte.org/assets/form/form.js"></script>
<script src="https://support.cubyte.org/assets/chat/chat.min.js"></script>
```
from the `<head>` to line 224 just before
```
<!-- Zammad Form -->
    <script>
    $(function() {
      $('#feedback-form').ZammadForm({
        messageTitle: 'Contact',
        messageSubmit: 'Send',
        messageThankYou: 'Thanks for your message!',
        modal: true
      });
    });
    </script>

    <!-- Zammad Chat -->
    <script>
    $(function() {
      new ZammadChat({
        title: '<strong>Chat</chat> with us!',
        background: 'rgb(77,77,77)',
        fontSize: '12px',
        chatId: 2,
        target: $('.chatbox'),
        debug: true
      });
    });
    </script>
```

**Comment by wagnst** [comment]
@m4r71n thanks, this is working perfectly!
can you also check #297?

**Comment by vousys** [comment]
I have the same issue and I solved it like that:

`<div class="soporte-chat"></div>
`
And then using the target class in the zammad chat initialization

```
    new ZammadChat({
        title: 'Chat - Soporte',
        background: '#77cae3',
        fontSize: '12px',
        chatId: 1 ,
        show: true,
        target: $('.soporte-chat'),
        debug:true
      });

```

**Comment by MrGeneration** [comment]
Locking this issue to reduce the noise on this tracker.
Please do not recycle old issues that have been closed for a long time.
