### ISSUE TITLE
SAML authentication

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#2741]
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* There should be the possibility to log users in via SAML (Keycloak, Chipotle, etc.) as it's possible for other third party providers (Office 365, GitHub etc.)

### Actual behavior:

* SAML login is currently not supported

**Comment by peacepenguin** [comment]
Hey @thorsteneckel I got the latest develop version 3.2.0-1568666188.ba2afc0c.bionic installed to test the SAML integration commit: https://github.com/zammad/zammad/commit/a93250e210a1b2fcbfe61843dd2e3f6c3451ff12

I see locally installed files that include the SAML bits that were committed, but all the SAML configuration fields are missing under Security -> Third party applications.

Let me know if there's anything I can do to help!

Thanks!

**Comment by MrGeneration** [comment]
If you installed via source, don't forget to precompile :>

(zammad run) rake assets:precompile

**Comment by peacepenguin** [comment]
I used packager.io on the develop branch to get the bits on a new ubuntu 18.04 server vm. But I'll try compile from source to test the latest straight from GitHub.

I do notice the settings for the other auth providers are defined and listed here:   https://github.com/zammad/zammad/blob/develop/db/seeds/settings.rb

I don't see anything SAML related in that file, whereas settings for all the other third party auth providers have detailed listings that seem to also define the gui elements. 

All that said i'm new to ruby/rails in general, and very new to the architecture of Zammd, so please forgive me if i'm way off base here and I just need to compile it correctly :)

**Comment by MrGeneration** [comment]
That's correct, because this will come with an migration :) ( https://github.com/zammad/zammad/blob/develop/db/migrate/20190715141227_saml_auth.rb )

Maybe also `zammad run rake db:migrate` followed by an restart might help.

If you want to be 100% sure, you could run the install-script manually:

`/opt/zammad/contrib/packager.io/postinstall.sh`

**Comment by peacepenguin** [comment]
I tried the fixes above without success using the packager.io develop packages.

Now switched over to a new vm, (ubuntu 18.04 server) Got the latest sources from GitHub develop branch, got it installed without too much trouble, but still no SAML config in the GUI.

Looks like something is missing still. Let me know if you want me to try anything, I have both packager.io and the source built vms running now. Both seem identical except packager.io package VM is using PostgreSQL, the source-built VM is using MYSQL.

Thanks!

**Comment by peacepenguin** [comment]
running db:migrate does show this SAML related output when installing from source and doing the 4 rake commands:

rake db:create
**rake db:migrate**
rake db:seed
rake assets:precompile

rake db:migrate outputs, (along with lots of other stuff):

== 20190715141227 SamlAuth: migrating =========================================
== 20190715141227 SamlAuth: migrated (0.0014s) ================================


But still no SAML config items in the GUI.

**Comment by peacepenguin** [comment]
I got saml working by adding in the same settings from the migration file: db/migrate/20190715141227_saml_auth.rb
  to the
 db/seeds/settings.rb   file. Pull request here: https://github.com/zammad/zammad/pull/2744

No new code, just copied the bits from the migration file.

> That's correct, because this will come with an migration :) ( 
  
@MrGeneration  Perhaps the SAML integration without this patch would work for upgrades but not new installs?

All my testing today has been around new installs, this patch allows SAML to work with a new clean install.

**Comment by thorsteneckel** [comment]
Thanks again @peacepenguin - it's fixed with the commit above. Packages should be ready in 20 minutes from now.

**Comment by sts** [comment]
Follow up feature request for automatic Role assignment via SAML. Anyone knows how and where to implement this in Zammad?

https://community.zammad.org/t/saml-for-roles-assigment/3696

**Comment by MrGeneration** [comment]
@sts please don't hijack solved and closed issues.
Feature Requests should live on the community and not on Github.

I'll be locking this issue now.
