### ISSUE TITLE
Typo in polish translation of ticket_create mailer notification

### ISSUE THREAD

**Issue by abeluck** [zammad/zammad#2747]
### Infos:

* Used Zammad version: develop branch
* Installation method (source, package, ..): source
* Operating system: debian
* Database + version: postgres 9.6
* Elasticsearch version:  n/a
* Browser + version: n/a

### Expected behavior:

* no html breaking typos in mailer templates

### Actual behavior:

* typo in polish language email template 

### Steps to reproduce the behavior:

* see https://github.com/zammad/zammad/blob/develop/app/views/mailer/ticket_create/pl.html.erb#L5

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by abeluck** [comment]
Also the final line in the ticket_escalation polish template is missing a closing `>`

https://github.com/zammad/zammad/blob/develop/app/views/mailer/ticket_escalation/pl.html.erb#L18

**Comment by MrGeneration** [comment]
Ready for QA
https://github.com/zammad/zammad/pull/2748

**Comment by MrGeneration** [comment]
MR 808 is undergoing CI right now, I'll throw it at you when it's ready for QA

**Comment by thorsteneckel** [comment]
This is fixed with the two commits above. Packages will be ready in ~20 minutes from now. Thanks for reporting @abeluck !

**Comment by abeluck** [comment]
Super fast! You all rock.
