### ISSUE TITLE
Avatar in Chat not showing - wrong url

### ISSUE THREAD

**Issue by Frankstar** [zammad/zammad#275]
The Avatar (from the Agent) in the Chat Window has a duplicate `http//` in his path and is not working / not showing
Example:

```
http://http//example.com/api/v1/users/image/9eb82889a954e2fd448976f786717b99
```

**Comment by Frankstar** [comment]
just saw working avatars, so need to add that i used the centos 6 Repo.

**Comment by martini** [comment]
Hi @Frankstar 

I'm not sure because of the last comment, you still have this issue? 

 -Martin

**Comment by Frankstar** [comment]
in my enviroment (centos) no - its not working

**Comment by martini** [comment]
Thanks for feedback. You are talking about the customer chat widget in your web page?

What is the output of:

```
zammad@shell> rails r "p Setting.get('fqdn')"
```
it seems that you have here http:// added. Here only the fqdn is needed.

You can change it via:

```
zammad@shell> rails r "Setting.set('fqdn', 'zammad.example.com')"
```

To be sure, restart after updating the fqdn.

**Comment by Frankstar** [comment]
sry i didnt figured out yet how to run this command.
I dont have rails installed global.
Also if i logg into zammad rails isnt recognized.

EDIT:
Just figured out i can run it via: `zammad run rails r "p Setting.get('fqdn')";`

the output is `"http://test.masked.tld"`

so this isnt the error.

**Comment by martini** [comment]
Hi @Frankstar 

the fqdn in Zammad is only the hostname. So if you change it from "http://test.masked.tld" to "test.masked.tld" it will work:

`zammad run rails r "p Setting.set('fqdn', 'test.masked.tld')";`

 -Martin

**Comment by monotek** [comment]
How about checking the field for http(s):// an removing it when given?

Martin Edenhofer <notifications@github.com> schrieb am Sa., 5. Nov. 2016,
17:02:

**Comment by martini** [comment]
Sounds good!

**Comment by rkaldung** [comment]
> On Nov 5, 2016, at 5:11 PM, André Bauer <notifications@github.com> wrote:
> 
> How about checking the field for http(s):// an removing it when given?

Why should content be removed? The setting is called fqdn and not url or uri.
The only proper reaction would be throwing an exception,

-- 
Roy Kaldung

**Comment by Frankstar** [comment]
@martini you are right, my fault. its working now.
@rkaldung to be honest, i dont even remember when or where it did ask for the fqdn - its totally clear that fqdn is not a url/uri so - yeah - i would throw an exception if "http://" is found.

**Comment by monotek** [comment]
@rkaldung
Because a Fqdn does not contain a http prefix.

Throwing an exeption would work but I think a better user experience is to fix it automaticly. Stripping everything from the field should be easy as a fqdn is exactly defined.
