### ISSUE TITLE
Error while fetching email from inbox will block processing of other mails in inbox

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#2754]
* Used Zammad version: 3.1.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
*Ticket #: 1053593 
### Expected behavior:

* Fetch mails via IMAP/POP3 channel backend
* Error occurs while fetching email
* Log expressive error to log / channel / maintenance endpoit
* Process with other emails

### Actual behavior:

* Fetch mails via IMAP/POP3 channel backend
* Error occurs while fetching email
* Log exact error to log
* No further fetching/processing of other mails in inbox

### Steps to reproduce the behavior:

* Have an unfetchable mail in your inbox
* See a log message like:
```
I, [2019-09-16T19:07:44.077396 #22185-70321870965020] INFO -- : fetching imap (mail.example.com/info@example.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=true)
I, [2019-09-16T19:07:44.351265 #22185-70321870965020] INFO -- : - message 1/80
E, [2019-09-16T19:07:44.446517 #22185-70321870965020] ERROR -- : Can't use Channel::Driver::Imap: #<Net::IMAP::ResponseParseError: unknown token - "\"Jetzt">
E, [2019-09-16T19:07:44.446559 #22185-70321870965020] ERROR -- : unknown token - "\"Jetzt" (Net::IMAP::ResponseParseError)
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:3492:in `parse_error'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:3437:in `next_token'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:3354:in `lookahead'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:3252:in `nstring'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2399:in `envelope'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2386:in `envelope_data'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2359:in `msg_att'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2339:in `numeric_response'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2281:in `response_untagged'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2252:in `response'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2178:in `parse'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:1242:in `get_response'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:1145:in `receive_responses'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:1120:in `block in initialize'
/usr/local/rvm/gems/ruby-2.5.5/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

Or:
```
I, [2019-09-24T10:38:48.837126 #29702-19506700] INFO -- : - message 1/2
E, [2019-09-24T10:38:48.889973 #29702-19506700] ERROR -- : Can't use Channel::Driver::Imap: #<Net::IMAP::ResponseParseError: unknown token - "\"RE:">
E, [2019-09-24T10:38:48.890016 #29702-19506700] ERROR -- : unknown token - "\"RE:" (Net::IMAP::ResponseParseError)
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:3492:in `parse_error'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:3437:in `next_token'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:3354:in `lookahead'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:3252:in `nstring'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2399:in `envelope'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2386:in `envelope_data'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2359:in `msg_att'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2339:in `numeric_response'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2281:in `response_untagged'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2252:in `response'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:2178:in `parse'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:1242:in `get_response'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:1145:in `receive_responses'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:1120:in `block in initialize'
/usr/local/rvm/gems/ruby-2.5.5/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2019-09-24T10:38:49.126744 #29702-19506700] INFO -- : fetching imap (example.com/info@example.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=true)
I, [2019-09-24T10:38:49.397862 #29702-19506700] INFO -- : - no message
```
* See mails piling up in your mailbox

There is an example mail in T#1053593.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rlue** [comment]
Seems suspiciously similar to #2682. In a comment from Martin, on that thread:

> ### How Zammad handles unprocessable email
> 
> If a single e-mail from a mailbox cannot be processed, Zammad will take it from the mailbox and store it under /opt/zammad/tmp/unprocessable_mail/. Afterwards, the other e-mails from the same mailbox are processed.
> 
> If an e-mail is in the /opt/zammad/tmp/unprocessable_mail/ directory, this is reported via the Zammad monitoring endpoint.
> 
> In short: Normal e-mail processing is not affected if an e-mail is unprocessable (for whatever reason).
> 
> ### How Zammad handles whole mailbox fetching failures
> 
> If several mailboxes are configured in Zammad, one of which cannot be successfully retrieved, then Zammad "skipp's" this one mailbox and processes the other mailboxes.
> 
> **In short: The normal processing of e-mails is not affected by a mailbox that cannot be retrieved.**

I'll need a little more time to look into it.

**Comment by MrGeneration** [comment]
Personal thought: In my opinion the above described issue shouldn't be a mailbox failure, but is -as the server returns a wrong subject that Zammad doesn't understand (as example), mail related.

If you mark the mail as read or remove it from the mailbox, importing instantly works. :-)

**Comment by martini** [comment]
@rlue Me comment from 2682 is valid until the error is raised in Zammad`s email parsing backend. 

In this cause the issue is raising an exception one layer above, in Net::IMAP. This is currently not handled as I described in 2682.

The traceback in the inital article is good. But there should be a longer traceback somewhere.

**Comment by MrGeneration** [comment]
@martini as the issue originally comes from me: There is no longer traceback, that's all you'll see on manual `Channel.fetch` and in the logfile. :-(

**Comment by martini** [comment]
Ok. Based on the log output:

```
I, [2019-09-16T19:07:44.077396 #22185-70321870965020] INFO -- : fetching imap (mail.example.com/info@example.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=true)
I, [2019-09-16T19:07:44.351265 #22185-70321870965020] INFO -- : - message 1/80
E, [2019-09-16T19:07:44.446517 #22185-70321870965020] ERROR -- : Can't use Channel::Driver::Imap: #<Net::IMAP::ResponseParseError: unknown token - "\"Jetzt">
E, [2019-09-16T19:07:44.446559 #22185-70321870965020] ERROR -- : unknown token - "\"Jetzt" (Net::IMAP::ResponseParseError)
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:3492:in `parse_error'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:3437:in `next_token'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/imap.rb:3354:in `lookahead'
```

It seems that the error appears by fetchin first mail `INFO -- : - message 1/80` here:

https://github.com/zammad/zammad/blob/develop/app/models/channel/driver/imap.rb#L224

@rlue Here would be a good point to extend it with a `rescue`.

**Comment by thorsteneckel** [comment]
Hey @rlue - @MrGeneration just notified me that it has happened again on a customer instance. I can confirm what @martini wrote. The line struggling here is: https://github.com/zammad/zammad/blob/d58233d0cec6642830bc297065f69b7fd5667f23/app/models/channel/driver/imap.rb#L224

It seems like that the exception is not complete because it is raised in a background process Thread the Net::Imap class starts [here](https://github.com/ruby/ruby/blob/f9981d79bc5037e7d9fed1a5f473ced32cadb7b6/lib/net/imap.rb#L1120).

Background information, might be useful:
I [attached a file](https://github.com/zammad/zammad/files/3809789/lines.txt) that contains a list of all lines executed starting from:
https://github.com/zammad/zammad/blob/d58233d0cec6642830bc297065f69b7fd5667f23/app/models/channel/driver/imap.rb#L67

These were created by making a copy of the IMAP backend (`cp app/models/channel/driver/imap.rb ./te_debug_imap.rb`), adding a `Channel.fetch` at the end of the file and adding a [`:line` TracePoint](https://devdocs.io/ruby~2.5/tracepoint) on line `67` like:

```ruby
trace = TracePoint.new(:line) do |tp|
  puts "#{tp.path}:#{tp.lineno}"
end
trace.enable if channel.id == 21
```

 and an ensure block to disable the trace afterwards at the end of the fetch method:
```ruby
  ensure
    trace.disable
```

I had to remove the offset of line numbers I added with these changes to reflect the actual line number in the class and changed the filename from `te_debug_imap.rb` to the absolute path of the IMAP driver backend.

**Comment by rlue** [comment]
Wow, this is a lot of information! Thanks @thorsteneckel! A couple questions:

1. How did you conclude that the problem originates in `@imap.fetch`? The
   original traceback, as you pointed out, leads back to a block in `Net::IMAP.new`:

   ```ruby
   @receiver_thread = Thread.start {
     begin
       receive_responses
     rescue Exception
     end
   }
   ```

   This block had me scratching my head all day yesterday, since the method
   that leads to the error (`#receive_responses`) is wrapped in a `begin` /
   `rescue` / `end` block. Do you know what’s going on there?

2. Since `Net::IMAP` utilizes background threads, does that mean that the
   traceback may include lines that are out of order?

**Comment by martini** [comment]
I have live feedback from this issue, all works as expected only this `next` is not working to jump to next email:

https://github.com/zammad/zammad/blob/develop/app/models/channel/driver/imap.rb#L237

Knows somebody why? @rlue

**Comment by martini** [comment]
JFI: `next` is not working because the connection got lost when trying to fetch the next message. 

```
I, [2020-08-06T14:31:02.949368 #11386-79400480]  INFO -- :  - message 2/17
E, [2020-08-06T14:31:02.949542 #11386-79400480] ERROR -- : Can't use Channel::Driver::Imap: #<IOError: closed stream>
E, [2020-08-06T14:31:02.949567 #11386-79400480] ERROR -- : closed stream (IOError)
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/openssl/buffering.rb:322:in `syswrite'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/openssl/buffering.rb:322:in `do_write'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/openssl/buffering.rb:421:in `print'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:1288:in `put_string'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:1260:in `block in send_command'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:1255:in `send_command'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:1441:in `block in fetch_internal'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:1436:in `fetch_internal'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/imap.rb:818:in `fetch'
/home/zp_XXX/zammad/app/models/channel/driver/imap.rb:240:in `block (2 levels) in fetch'
/home/zp_XXX/zammad/app/models/channel/driver/imap.rb:531:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/home/zp_XXX/zammad/app/models/channel/driver/imap.rb:530:in `timeout'
/home/zp_XXX/zammad/app/models/channel/driver/imap.rb:239:in `block in fetch'
/home/zp_XXX/zammad/app/models/channel/driver/imap.rb:228:in `each'
/home/zp_XXX/zammad/app/models/channel/driver/imap.rb:228:in `fetch'
/home/zp_XXX/zammad/app/models/channel.rb:57:in `fetch'
/usr/local/rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'
/usr/local/rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'
/home/zp_XXX/zammad/app/models/channel.rb:32:in `fetch'
(eval):1:in `_start_job'
/home/zp_XXX/zammad/app/models/scheduler.rb:287:in `eval'
/home/zp_XXX/zammad/app/models/scheduler.rb:287:in `_start_job'
/home/zp_XXX/zammad/app/models/scheduler.rb:239:in `block (2 levels) in start_job'
/home/zp_XXX/zammad/app/models/scheduler.rb:237:in `loop'
/home/zp_XXX/zammad/app/models/scheduler.rb:237:in `block in start_job'
/usr/local/rvm/gems/ruby-2.6.5/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

In the meantime @mantas  did another improvement which is fixing this issue too: https://github.com/zammad/zammad/commit/577bb5f72379256f5ac0827b7fbb843b24b6e570 - so issue can keep closed
