### ISSUE TITLE
auto reply (on closed ticket) leaks private information

### ISSUE THREAD

**Issue by Lillecarl** [zammad/zammad#2755]
### Infos:

* Used Zammad version: 3.1.x 
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04 
* Database + version: psql (PostgreSQL) 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)
* Elasticsearch version: elasticsearch/stable,now 7.3.2 amd64 [installed,automatic]
* Browser + version: Firefox Quantum 69.0.1 (64-bit)

### Expected behavior:

When the default trigger "auto reply (on closed ticket)" is triggered, and the last article is internal it'll post the last public article instead
(#{article.body})

### Actual behavior:

When the default trigger "auto reply (on closed ticket)" is triggered, and the last article is private it sends it in email to the customer
(#{article.body})

### Steps to reproduce the behavior:

Close a ticket where the last entry is internal

Yes I'm sure this is a bug and no feature request or a general question.

----------------------

Workaround is setting up one trigger that requires the article to be public, and one that requires the article to be internal, and only show the body if it's public

![image](https://user-images.githubusercontent.com/207073/65517932-c5dc4380-dee3-11e9-8bbe-0212a98db7f3.png)

**Comment by MrGeneration** [comment]
Sorry, but I rather see this as a technical question.
Background to this: The referenced trigger is, by default, inactive and is meant to be an example on what you can do with triggers.

I get your point, but I personally expect administrators to check triggers (especially if they are pre defined!) to what they will do.

Closing now.
Please refer the community for technical questions, if any appear: https://community.zammad.org

**Comment by Lillecarl** [comment]
Fair enough, i get your point too.

Though I'd say it'd be great if #{article.body} row was removed from the default, the security community sees bad defaults as vulnerabilities, I'd argue this is one.

Thanks for the quick reply, I might rephrase this as a feature request in discourse 😄
