### ISSUE TITLE
Office Integration

### ISSUE THREAD

**Issue by bastienroussel** [zammad/zammad#2758]
Infos:

* Used Zammad version: 3.1.X
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04.3 LTS
* Browser + version: Google Chrome Lastest 

### Expected behavior:

A correct login with office 365

### Actual behavior:

When I try to log in with office on chrome I have an error 422:
![image](https://user-images.githubusercontent.com/52447846/65860457-a5d8d400-e36a-11e9-8121-1ad1ef924216.png)

With an other web brower it's work like normaly expected 

### Steps to reproduce the behavior:

Install zammad and configure office 365 for it 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but on a current Google Chrome I'm unable to reproduce this.

Please update your "steps to reproduce the behavior" to each single step you're doing after you activated. Please also check and note the differences between your tested browsers (apart the version and name ;) ). This is a possible duplicate of: https://github.com/zammad/zammad/issues/2617

Edit: Oh... and please provide logs... :)

**Comment by bastienroussel** [comment]
Sorry I've forget the pastebin link : https://pastebin.com/esG0Fp7P

And to add office 365 on zammad, I've use this documentation : https://admin-docs.zammad.org/en/latest/security-thirdparty/microsoft.html

And on my chrome I don't have any account log in on Office

**Comment by MrGeneration** [comment]
Sorry, I still can't reproduce this. This is what I did:

## first try
* ensured I already am logged in on Office 365 (e.g. by opening outlook.com)
* went to Zammad and clicked on "Office 365"
* I was redirected to Microsoft, 1-2 Seconds later it automatically redirected me back to Zammad
* I was logged in


## second try 
* ensured I was logged off from Office 365 (opened outlook.com and presssed "logout")
* went the Zammad and clicked on "Office 365"
* After being redirected to Microsoft, I entered by credentials and pressed "login"
* I was redirected to Zammad and successfully authenticated


If one of the above steps is identical, then I believe that this is rather a technical question than a Bug.
CSRF-Token issue most of the times can be solved by a reload of the WebApp (while it is suuuupeeer rare, just if you keep your Browser open for yours on the login screen).

I'll there for close this issue for now.
If this is a technical question, please use the Community: https://community.zammad.org

**Comment by bastienroussel** [comment]
Thanks for your help @MrGeneration . I have find an solution.

To fix that I need to modify my vhost with theses lignes:
`RequestHeader set X_FORWARDED_PROTO 'https'
RequestHeader set X-Forwarded-Ssl on`

And we need to enable headers modules:
`sudo a2enmod headers`

Thanks for your time and your help
