### ISSUE TITLE
twillio sms /whatsapp

### ISSUE THREAD

**Issue by metalsoft10** [zammad/zammad#2762]
### Infos:

* Used Zammad version: 3.1
* Installation method : ( package)
* Operating system: Ubuntu 16.04
* Database + version: 
* Elasticsearch version:
* Browser + version:

i can receive whatsapp messages 
but on send 
and outbound have same message 
  
Can't use Channel::Driver::Sms::Twilio: #<Twilio::REST::RestError: [HTTP 400] 21212 : Unable to create record The 'From' number +4474***073 is not a valid phone number, shortcode, or alphanumeric sender ID. https://www.twilio.com/docs/errors/21212 >

**Comment by MrGeneration** [comment]
Sorry, but I do believe that this is rather a technical question than a bug.
Technical questions and feature request should live at the Community: https://community.zammad.org

Please note that Zammad does not support WhatsApp-Messages (no matter of their origin).
Also, ensure that the mentioned error document ( https://www.twilio.com/docs/errors/21212 ) does not affect you. Also check: https://www.twilio.com/docs/usage/anti-fraud-developer-guide

Closing now.
