### ISSUE TITLE
Removing last condition or action breaks dialogues

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2764]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system:  any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Tested and verified on Firefox and Chrome (latest)
 
*This seems to be -at least partly- a regression of https://github.com/zammad/zammad/issues/2516*

*This issue was found by the Community-Member: https://community.zammad.org/u/bebosudo* 

### Expected behavior:

* not being able to remove the last action or condition on modal dialogues.

### Actual behavior:

* On most of the dialogues you can remove the last action and/or condition in modal dialogues. This draws the UI useless (if you save that change), because you'll never be able to re-add conditions or actions.

### affected interfaces:

This list might be incomplete, but I successfully tested this at least partly (condition or action) on:

* Trigger
* Scheduler
* SLA
* Reporting-Profiles
* Time Accounting
* Overviews
* Postmaster FIlters

Possibly also affects integrations like LDAP, but this is untested.

### Screencast with example:

![deleting-action-possible](https://user-images.githubusercontent.com/6549061/66220191-da32f400-e6cc-11e9-9d87-63b5310a9600.gif)

### Steps to reproduce the behavior:

* go to any modal dialogue that contains conditions and/or actions
* try to remove all conditions or actions

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by bebosudo** [comment]
May I suggest a UI improvement?
I think it would be "easier" to use a delete/trash icon on every row of condition/action (as it is now) and a single add with plus icon below.
What's the meaning of having a plus on the first row? Is it any different from the second or third "add" button?
