### ISSUE TITLE
DELETE Ticket API /api/v1/tickets/:id "Not authorized"

### ISSUE THREAD

**Issue by sstidl** [zammad/zammad#2765]
### Infos:

* Used Zammad version: lastest docker-compose version (3.1.x)
* Installation method (source, package, ..): docker
* Operating system: debian
* Database + version: latest
* Elasticsearch version: latest
* Browser + version: N/A

### Expected behavior:

* last time I used my script to delete tickets it worked like this:
```
export TOKEN=`cat TOKEN`
TICKETS=`curl -H "Authorization: Token token=$TOKEN" https://XXXX/api/v1/tickets/search?query=group:_delete_these_tickets_|jq ".tickets[]"`
for i in $TICKETS ; do
        curl -H "Authorization: Token token=$TOKEN" -s https://fs.d.ffg.at/api/v1/tickets/$i -X DELETE
done
```
note: this script is not running on the same host as rails/nginx

### Actual behavior:

* getting 
{"error":"Not authorized"}

### Steps to reproduce the behavior:

* create API key with admin (tried also one with admin and all checkmarks added with no difference)
* use it in the script above

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by sstidl** [comment]
Ok, I found out, that the admin account has to have permissions to see / edit the ticket so he can delete it. this is not useful as it's the ADMIN

The sideeffect of adding the admin to the all groups of tickets is that he could get tickets assigned?! 

please consider to give admin permission to delete all tickets regardless of any group assignments

**Comment by MrGeneration** [comment]
Sorry, but this is rather a technical question.
For the next time, please post such questions over at the Community: https://community.zammad.org

Closing now.

**Comment by sstidl** [comment]
Dear @mrgeneration

 I think it is a bug, if having admin permissions gives you "permission denied" on actions.

Where are you discussing such things?

Best regards
St.

**Comment by MrGeneration** [comment]
Admin-Accounts by default do not have rights to view / change tickets. 
This works as designed actually, we're strictly differencing in between a admin user and some one that's allowed to deal with tickets. The API always users your user rights.

Please note that this does not affect superusers (root, zammad) on console.

Technical questions and discussions can be made on https://community.zammad.org
