### ISSUE TITLE
non-privileged "customer" (user-role) can see many/all(?) users in json response

### ISSUE THREAD

**Issue by ralfhauser** [zammad/zammad#2766]
### Infos:
***Remark:** This article has been edited by @MrGeneration to meet our requirenments.*

* Used Zammad version: 3.1
* Installation method (source, package, ..): package
* Operating system: Debian
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Internal-Ticket: #1055511 

### Expected behavior:

Zammad not disclosing information about users.

### Actual behavior:

A CERT incident team just informed us that with

GET /api/v1/users/860?full=true&_=1575387794268 HTTP/1.1

A json response disclosing information about way-to-many/all? users on the system can be obtained. This is a security issue!

### Steps to reproduce the behavior:

* create a customer account on Zammad
* login to that account and call above URL

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but I'm unable to reproduce this.
Please use the template below and adjust your article accordingly.

We also need the full payload and what exactly you're doing in order to reproduce this.
On my end I can't as a normal authenticated customer.

```
### Infos:

* Used Zammad version:
* Installation method (source, package, ..):
* Operating system:
* Database + version:
* Elasticsearch version:
* Browser + version:


### Expected behavior:

*


### Actual behavior:

*


### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.
```

**Comment by MrGeneration** [comment]
This issue is dependend of this issue: https://github.com/zammad/zammad/issues/2767
The reason for this to appear is a wrong permission configuration which causes Zammad to provide data, that you'd need for e.g. reporting functionality.

This is rather a technical - / administrative question.
Closing now.
