### ISSUE TITLE
Enhancement: warn admins for potential security issues when setting "admin.reporting" for customer roles

### ISSUE THREAD

**Issue by ralfhauser** [zammad/zammad#2767]
### Infos:
***Remark:** This article has been edited by @MrGeneration to meet our requirenments.*

* Used Zammad version: 3.1
* Installation method (source, package, ..): package
* Operating system: Debian
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Internal-Ticket: #1055511 

### Expected behavior:

Zammad not disclosing information about users.

### Actual behavior:

A CERT incident team just informed us that with

POST /api/v1/reports/generate HTTP/1.1

way-too-many/all(?) tickets of other users become visible

Maybe the default group "all users" should not automatically apply for the report for non-privileged users ?

### Steps to reproduce the behavior:

* create a customer account on Zammad
* login to that account and call above URL

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by ralfhauser** [comment]
![20191007_tooOpenZammadReport](https://user-images.githubusercontent.com/1681677/66309719-99c0b980-e90a-11e9-88ae-2fa5c5c008e2.png)

**Comment by MrGeneration** [comment]
As mentioned in #2766 already, please provide more information:

```
### Infos:

* Used Zammad version:
* Installation method (source, package, ..):
* Operating system:
* Database + version:
* Elasticsearch version:
* Browser + version:


### Expected behavior:

*


### Actual behavior:

*


### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.
```

**Comment by ralfhauser** [comment]
We are getting closer to a resolution: Zammad offers nice default roles like
![image](https://user-images.githubusercontent.com/1681677/66399078-35235e80-e9df-11e9-8350-a451c5e12798.png)

However, if you edit the role's permissions and e.g. check "report" (even though this is not a sub-bullet under "admin") you defacto escalate the privileges of the customer role to something at least on agent if not admin level

Suggestion, if the role is called "Customer" or "Kunde" etc., ==> 1) at least pop-up a warning that checking certain functions will not only give you the access to your own data, but way more

**Comment by ralfhauser** [comment]
2) even better would be 
![image](https://user-images.githubusercontent.com/1681677/66399885-b2030800-e9e0-11e9-86da-ee76e58b6964.png)
to explain e.g. in the red circle that this feature shouldn't be given to self-registering users as it is rather an admin-level function

**Comment by MrGeneration** [comment]
We'll take this as enhancement to help administrators to forsee the possible issues the `admin.reporting` permission can bring on a customer role.

Please remove the `admin.reporting` permission from the customer role. This will solve the issue you have.

**Comment by Mirtaaa** [comment]
Hello, I verfied this Issue and as of today Zammad 6.2 it is not possible anymore to set `admin.reporting` or `reporting` for the role `customer`.

<img width="1021" alt="Screenshot 2024-04-16 at 09 42 26" src="https://github.com/zammad/zammad/assets/103510339/58dec59c-4d09-4e0e-83ad-a456858cd106">
<img width="1020" alt="Screenshot 2024-04-16 at 09 41 12" src="https://github.com/zammad/zammad/assets/103510339/d14ab5f4-5f6e-4157-b0ef-875a9e406f58">

Therefore we close this as done.
