### ISSUE TITLE
Wrong Variable-Reference for Tags (Trigger, Scheduler)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2769]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Google Chrome 77.0.3865.90
* Ticket: #1085435

### Expected behavior:

When using variables (via shortcut `::`) within the backend for e.g. Triggers, the selected `Ticket > Tags` will return a Tag list as wanted.

### Actual behavior:

When using variables (via shortcut `::`) within the backend for e.g. Triggers, the selected `Ticket > Tags` will not return a Tag list. Instead, mails with this variable contain: `#{ticket.tags / no such method}`.

The variable returned by Zammad is: `#{ticket.tags}`.
I've been fiddling and found the following variable to be working: `#{ticket.tag_list}`. The output might be a bit "ugly": `["yep", "yay", "complaint"] `

### Steps to reproduce the behavior:

* login to Zammad
* recycle the existing "reply to new tickets"-Trigger and add `#{ticket.tags}` to the text
* save the changes and send / pipe a mail into Zammad
* wait for Zammad to reply and see the issue

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
~~Ticket#1085435~~

Edit by @MrGeneration : Moved ticket number to first article, especially on long issues it's impossible to keep track of all possible appearing ticket numbers.

**Comment by cganiddle** [comment]
This issue is not fixed in 7.4.11 version

**Comment by mantas** [comment]
@cganiddle are you sure? It seems fine for me. Does workaround with `ticket.tag_list` work for you?

Also, the latest version so far is 7.0.1 with 7.1 coming soon... Could you double-check your version?
