### ISSUE TITLE
incomplete and curious view of the calendar

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#2776]
### Infos:

* Used Zammad version: 3.1
* hosted
* Browser + version: Chrome Version 77.0.3865.120 and Safari Version 12.1.1
* Ticket: #1080027

### Expected behavior:

* A complete calendar display where I can see all dates without the need to recount, like:
![image](https://user-images.githubusercontent.com/22768032/66763527-46211380-eea8-11e9-9506-84dee4b4dd1b.png)

### Actual behavior:

When adding an additional holiday to the Calendar panel, the calendar view is incomplete. It seems that it only shows the dates of the prior and the next month.
If you count the fields one by one and click on the relevant date, it will be entered correctly. However, editing is still difficult.

At the moment it looks like this:

![image](https://user-images.githubusercontent.com/22768032/66751266-e9652f00-ee8e-11e9-9c9b-1de70b6b68fb.png)

### Steps to reproduce the behavior:
* go to Manage --> Calendars
* Create a new calendar or take an existing one
* Click in the "Date" field in the HOLIDAYS-Section

**Comment by bolah2009** [comment]
Hi @KoJie @MrGeneration @thorsteneckel 🙋🏽‍♂

Will it be okay to open a PR for this?

I think adjusting the CSS a little can yield the following screenshot below:
It is different from the picture in the **Expected behavior** above so I am not sure if this would be the best solution. 

   ![image](https://user-images.githubusercontent.com/36057474/76362211-e75daa00-6320-11ea-91bc-8b12a2b9c23d.png)

**Comment by mantas** [comment]
@bolah2009 it'd be better to adjust CSS slightly more to make calendar identical to the rest of the system. As in screenshot in comment above in `Expected behavior` section.

And yes, that'd definitely make a great PR.

**Comment by bolah2009** [comment]
Thanks @mantas I will work on it later today.

**Comment by bolah2009** [comment]
Hi @mantas 
I opened a PR to this but am curious about the statement
>  make calendar identical to the rest of the system.

Are there other places where this calender view exist?
Sorry am new to this app and couldn't find one when I tried checking for it.

**Comment by mantas** [comment]
@bolah2009 this same calendar is used in any date input field.

For example, given that you run system locally at `http://localhost:3000`, open http://localhost:3000/tests_form in your browser. Scroll down to `datetime1` field.
