### ISSUE TITLE
System notifications are being sent even with empty mail address

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2778]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* If the agent has mail notifications enabled, Zammad will not try to send the notification if the mail address of the agent is invalid or not set `*`

`*` this should also apply to trigger based mails of any user
`*` if a user tries to reset his password, Zammad should tell "Can't do that, you have no mail address" for transparency to the user.

### Actual behavior:

* If the agent has email notifications enabled and a e.g. ticket gets updated, Zammad will send a notification via the sendout channels even if the agent has no notification.

### Steps to reproduce the behavior:

* create a agent account without mail address
* assign a ticket to the agent created
* update the ticket as any other user
* Zammad will try to send out this mail, this will cause monitoring errors as your mail server or sendmail will complain about an empty to-address.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rlue** [comment]
> this should also apply to trigger based mails of any user

Not 100% sure, but [I think this problem does not occur with triggers](https://github.com/zammad/zammad/blob/develop/app/models/ticket.rb#L1354).

**Comment by rlue** [comment]
Actually, it looks like [it shouldn't occur with internal notifications, either](https://github.com/zammad/zammad/blob/develop/app/models/transaction/notification.rb#L163-L167).

I wasn't able to reproduce this issue, but FWIW I haven't figured out a way to check the sendmail logs on my dev machine (I use a package called `msmtp-sendmail` to shim `msmtp` as a substitute for `sendmail`).

Is there some third kind of notification I don't know about?

**Comment by thorsteneckel** [comment]
@MrGeneration can you please provide a detailed step by step instruction on how to reproduce this? I wasn't able to reproduce it either. Please focus on what needs to be configured where exactly in a totally blank system. Thanks!

**Comment by MrGeneration** [comment]
Sure thing

* configure a notification mail account, you might want to stick with smtp authentication based mail server for easier results. Shouldn't really matter
* add a new agent user WITHOUT mail address
* ensure the mail notifications for new tickets are enabled
* create a new ticket without owner into a group the new agent can see
* At this point Zammad will send a notification to all affected agents, in my tests and hosted setups (2 or 3) this lead into error messages from the mail server stating the to address shall not be empty.

Error message will be:
`{"healthy":false,"message":"Channel: Email::Notification out Can't use Channel::Driver::Sendmail: #\u003cArgumentError: SMTP To address may not be blank: []\u003e","issues":["Channel: Email::Notification out Can't use Channel::Driver::Sendmail: #\u003cArgumentError: SMTP To address may not be blank: []\u003e"],"actions":[],"token":"xyz"}`

**Comment by rlue** [comment]
> in my tests and hosted setups (2 or 3) this lead into error messages **from the mail server**

Can you clarify where this error message can be found? I just tried on both [a development instance](https://youtu.be/lnRRgDKv6jI) and a hosted instance (the recording for that one got botched halfway through), and no error message appears in the web app. Is the error supposed to appear in an application log somewhere?

Do you have time to jump on a screenshare to go over it together?

**Comment by rlue** [comment]
Wait, I think I see it now! Are you talking about this error?

![Screenshot_20191120_150049](https://user-images.githubusercontent.com/12194123/69216210-988bd900-0ba6-11ea-994b-1b638fe123fb.png)

I ran across this error in the process of debugging another issue, so I'm not 100% sure I can reproduce it yet. But it seems to be what you're talking about?

**Comment by martini** [comment]
> Wait, I think I see it now! Are you talking about this error?

Yes.

**Comment by rlue** [comment]
@MrGeneration I def. need more details to reproduce this error. Here are the steps I've taken, which **do not** lead to the described error:

1. Have sendmail configured on your system.
2. Start with a fresh install of Zammad.
3. Perform initial setup:
   1. enter a valid email address for the admin account;
   2. use sendmail for outgoing notifications; and
   3. **do not** configure an email address.
4. Create an agent with no email address.
5. (Optional) Verify that email notifications work:
   1. switch to the new agent account;
   2. create a new ticket;
   3. assign it to the admin account;
   4. verify that admin receives Zammad notification email.
6. Verify that email notifications to new agent **do not** result in specified error:
   1. return to admin account;
   2. create a new ticket;
   3. assign it to the email-less agent user;
   4. submit;
   5. visit **Channels > Email** in the admin panel;
   6. see no error message under **Email Notification** section.

See demo [here](https://youtu.be/nXdx2_fvCwc).

**Comment by MrGeneration** [comment]
Ha!
Now I tried to reproduce this again with an SMTP Server configured (for notifications and groups for trigger based notifications).

However, Zammad did not try to send a mail to the agent I created without a mail adress. Very odd, I'm not sure what happened in between. Maybe some temporary issue or a condition I don't think of right now.

Therefor I'll be closing this, sorry for the hassle!
