### ISSUE TITLE
Shared organization issue (Create your first ticket)

### ISSUE THREAD

**Issue by redbear-ger** [zammad/zammad#2780]
### Infos:

* Used Zammad version: latest
* Installation method (source, package, ..): rpm
* Operating system: ubuntu 18.04
* Browser + version: Edge + FF + Chrome

### Expected behavior:
When you take the ability to create tickets for normal User, they shoudnt see the option.

### Actual behavior:
The "+" button disappears but when a user has no tickets he gets the message "You have no tickets, create one" in "Your tickets" view (might be spelled different, I use the germen version)
If the user tries to create the ticket, he gets "Your role cannot create new ticket. Please contact your administrator" (english also in german translation), of course.
It confuses our users.

### Steps to reproduce the behavior:
Disable ability to create tickets in role, log in as user...

Just a small "bug", but would be nice if gone in next release.

**Comment by MrGeneration** [comment]
I could verify this.
Thank you very much for your time and contribution. :-)

Heads up: This is not about user roles, but setting the setting "Allow ticket creation via web channel" to "do not allow (false)".

This causes Zammad to disable the "+" Button, but if no tickets are there for the overviews, to suggest the customer to create a new ticket:
![image](https://user-images.githubusercontent.com/6549061/73839769-114e1900-4817-11ea-8aee-8217968f94ed.png)

When pressing on "create your first ticket" you'll however receive a access denied message.
So technically you can't create a ticket, but Zammad dares you to try. :-D

![image](https://user-images.githubusercontent.com/6549061/73839819-2c208d80-4817-11ea-8de8-95fae48440fa.png)

**Comment by romitgithub** [comment]
@MrGeneration What's the required solution here then?

**Comment by MrGeneration** [comment]
If a user is not allowed to create a ticket, I'd not display the possibilities to do so together with a meaningful message like
"You don't have any tickets to display and are not allowed to create new ones via the web interface."

Or something like that.
