### ISSUE TITLE
Can't create internal Articles via Trigger/Automatization

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#2782]
### Infos:

* Used Zammad version: 3.1
* hosted
* Browser + version: Chrome Version 77.0.3865.120
* Ticket# 1065571

### Expected behavior:

* As an admin I want to configure the `internal` attribute of a SMS or Email Notification configured in a Trigger/Automatization (the same as already possible for Notes)
* As an admin I want the `internal` attribute of a SMS or Email Notification configured in a Trigger/Automatization to default to `false` (public)

![image](https://user-images.githubusercontent.com/3873515/72594807-afca1700-3908-11ea-837a-4492e7a8a61d.png)

### Actual behavior:

* As an admin I can't configure the `internal` attribute of a SMS or Email Notification configured in a Trigger/Automatization. It defaults to `false`.

### Impact:

* The customer interface displays Trigger/Automatization information, such as the email address of the agent to whom the auto reply was sent:

![image](https://user-images.githubusercontent.com/22768032/67100433-f13f0f00-f1bf-11e9-9870-c16f3392019f.png)

### Steps to reproduce the behavior:

* Create a trigger e.g. info message to an agent in case of a priority change (-->high) of a ticket
* Have a ticket, change the priority to high --> autoreply to agent will be sent
* have a look into the ticket as the customers-view. You will see that a message to the email-adress of the agent was sent

**Comment by MilojeR** [comment]
Hello,

Is there any update regarding this issue? When do we expect resolution?

**Comment by MrGeneration** [comment]
Sorry, this doesn't have any news yet.
We'll update this issue accordingly as soon as it moves into any direction.

Also, please note that we cannot provide any ETAs for features or bug solvings.

**Comment by thorsteneckel** [comment]
Hey @mantas - this got prioritized by a customer of ours (cc @MrGeneration). Can you please prioritize and fix this?
