### ISSUE TITLE
Admin Settings-> Knowledge base messes up display of other Admin settings

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2784]
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version:
* Elasticsearch version:
* Browser + version: Firefox latest

### Expected behavior:

* When selecting the Knowledge Base settings and then selecting other Admin Settings the Settings window text should not get corrupted.

### Actual behavior:

* The text gets corrupted e.g. Time Accounting:
![image](https://user-images.githubusercontent.com/44224243/67213181-db2e8a00-f41d-11e9-9bea-e46142a08b62.png)

### Steps to reproduce the behavior:
* Have no Knowledge Base set up, so when selecting Knowledge Base you get:
![image](https://user-images.githubusercontent.com/44224243/67213251-f8fbef00-f41d-11e9-8cf6-1b6396713bdf.png)
* Now simply select another option like Time Accounting and the options will look as mentioned before.

It is nothing major but was pretty annoying when you accidentally click the Knowledge Base option.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Fast fix: Clicking on another option or reloading the WebApp helps, but I agree that it's annoying. :)
