### ISSUE TITLE
not possible to search or link KB-answer within ticket

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#2789]
### Infos:

* Used Zammad version: hosted 3.1.x
* Browser + version: Chrome Version 77.0.3865.120

### Expected behavior:

* within the ticket-information you should search for an existing knowledge base answer and link it

### Actual behavior:

* you can neither search nor link a knowledge base answers within the ticket via"Link related answer", underneath the ticket information:
![image](https://user-images.githubusercontent.com/22768032/67556354-4a082d80-f713-11e9-8ffc-7a7130b5d41a.png)

### Steps to reproduce the behavior:

* there is a knowledge base answer:
![image](https://user-images.githubusercontent.com/22768032/67556120-e120b580-f712-11e9-9c2a-75c4c3e369c7.png)
* you can find it via search:
![image](https://user-images.githubusercontent.com/22768032/67556422-6efca080-f713-11e9-8842-4a0684f974a3.png)
* but you won't find it within the ticket ("Link related answer", as shown en earlier at "Actual behavior")
* if you type in the entire title, it will tell you "no such object":
![image](https://user-images.githubusercontent.com/22768032/67556738-fba75e80-f713-11e9-94ce-6f868819583f.png)

### further information:
* if you link a ticket via the knowledge base editing-mask, it will appear as expected in the KB-answer and the ticket:
![image](https://user-images.githubusercontent.com/22768032/67557081-a91a7200-f714-11e9-96d9-017121a0a422.png)
![image](https://user-images.githubusercontent.com/22768032/67557126-bfc0c900-f714-11e9-954f-136ccf077f95.png)
* I tested the behavior with older KB-answers and created a new one - there was no difference

**Comment by thorsteneckel** [comment]
Hey @mantas - I could verify the issue on our hosted system as well. I saw that the search AJAX call result contained the right response / search result. It looks like the result isn't handled properly in the JS App. Let me know if I can execute / perform a task that helps you to gain more insights.

**Comment by mantas** [comment]
This issue was fixed with the same commit as #2718
