### ISSUE TITLE
Trigger for Notification for a changed ticket for the Customer

### ISSUE THREAD

**Issue by CrazyDounat** [zammad/zammad#2790]
### Infos:

* Used Zammad version: 3.1.X
* Operating system: Debian
* Database + version: newest
* Elasticsearch version: newest
* Browser + version: Chrome 77.0.3865.120 

### Expected behavior:

Send E-Mail to Customer if the Ticket gets an Update

### Actual behavior:

Nothing.

### Steps to reproduce the behavior:

Make a Trigger like this:
Customer is specific user "Customer Name"
Updated by is not specific user  "Customer Name"
Send E-Mail to Customer

**Comment by MrGeneration** [comment]
Sorry but this is a technical question.
Technical questions should life at the Community over at https://community.zammad.org

This repository is for bug reports only.
Sending a notification to your customer via Trigger on Ticket updates is perfectly possible, telling you how is out of scope of this Repository.

If you have further questions, please head over to the Community.
Closing now.
