### ISSUE TITLE
Piping e-mails to Zammad (e.g. via procmail) does not work

### ISSUE THREAD

**Issue by MichiK** [zammad/zammad#2791]
### Infos:

* Used Zammad version: 3.1.0-1570545649.c1160c5e.stretch
* Installation method (source, package, ..): Debian package
* Operating system: Debian 10
* Database + version: PostgreSQL 11.5-1+deb10u1
* Elasticsearch version: 7.4.1
* Browser + version: not applicable

### Expected behavior:

* I would like to pipe e-mails into Zammad using procmail to avoid setting up an IMAP/POP3 server like Dovecot just for the ticket system. I don't need one for the rest of my setup at all. Conveniently, the documentation explains how to do this in https://admin-docs.zammad.org/en/latest/channel-email/fetchmail.html
* I would expect e-mails piped into Zammad using the command line or procmail file as shown in the documentation to result in new tickets like e-mails that Zammad fetches via IMAP/POP3 (my installation is able to do this and works fine otherwise).

### Actual behavior:

* Piping e-mails into Zammad fails with the following error message:
```
Traceback (most recent call last):
	4: from /opt/zammad/bin/rails:8:in `<main>'
	3: from /opt/zammad/bin/rails:8:in `require_relative'
	2: from /opt/zammad/config/boot.rb:3:in `<top (required)>'
	1: from /opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)
```

### Steps to reproduce the behavior:

* Install latest Zammad and dependencies on a Debian system.
* ` su - zammad`
* `cd /opt/zammad`
* `export PATH=/opt/zammad/bin:/opt/zammad/vendor/bundle/bin:/sbin:/bin:/usr/sbin:/usr/bin:`
* `cat test/fixtures/mail67.box | rails r 'Channel::Driver::MailStdin.new(trusted: true)'`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @MichiK 

did you try `cat test/fixtures/mail67.box | zammad run rails r 'Channel::Driver::MailStdin.new(trusted: true)'` ?

**Comment by MichiK** [comment]
Thanks, that one worked. Too simple, actually...

I guess, opening a pull request fixing this in zammad/zammad-admin-documentation would be the way to go?

**Comment by thorsteneckel** [comment]
That would be actually pretty great, yes!

**Comment by MichiK** [comment]
Done. :)
