### ISSUE TITLE
Reporting: CSV-Export contains Tags twice (once empty)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2793]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1057181 

### Expected behavior:

When exporting CSV-Reports, all META-Information is only available once.

### Actual behavior:

When Exporting CSV-Reports, the field ``Tags`` actually appears twice.
If it is set, only the first column wiull contain the required information.

### Steps to reproduce the behavior:

* Fill Zammad with ticket data
* Export a CSV-Report
* open it and see

![image](https://user-images.githubusercontent.com/6549061/67783223-3b4ead00-fa6a-11e9-98b6-c311818a5a93.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by gabrielbaldao** [comment]
Can I try fix this bug?

**Comment by MrGeneration** [comment]
Yes of course, every help to bring Zammad forward is appreciated! :)

**Comment by thorsteneckel** [comment]
@gabrielbaldao - let us know whenever questions arise or you get stuck. Happy hacking ⌨️

**Comment by gabrielbaldao** [comment]
@thorsteneckel  I appreciate it, maybe i'll need some help with my setup, i was having unexpected errors, and I have some comments, like, this project already use ruby-2.5.5 but in the documentation is declared 2.4.4 version, right? you don't have docker file?

**Comment by MrGeneration** [comment]
Doh! Sorry the docs are outdated here!

ruby 2.5.5 is correct, so everything that says "2.4.4" wants to say "2.5.5" - sorry for the confusion! Will fix that when I'm back!

If needed, you can find docker-based Zammads here:

https://docs.zammad.org/en/latest/install-docker-compose.html (as compose, retains data)
if you're good with loosing data, you can use the single container:
https://docs.zammad.org/en/latest/contributing-install-docker.html

**Comment by gabrielbaldao** [comment]
will be great,thans, i think  in the readme the link to docker is broken.

**Comment by gabrielbaldao** [comment]
Guys, i am having some prblems, like, when i execute `bin/setup` i get this error:
```
Sprockets::Railtie::ManifestNeededError: Expected to find a manifest file in `app/assets/config/manifest.js`
But did not, please create this file and use it to link any assets that need
```
And some friend did the same thing in your machine and this not happened, you knows what can be?

**Comment by thorsteneckel** [comment]
Hey @gabrielbaldao - unfortunately I can't reproduce this issue either on my local develop machine. However, we're currently using a custom script to setup our dev environment which does basically the same. You can run `script/bootstrap.sh`.

Would you mind creating a topic over at the [community board](http://community.zammad.org/) for questions arising? This will help other community members that are looking for information on how to setup/develop Zammad and will keep this issue focused on the CSV topic. You can mention me over there. I'll subscribe to updates and help as soon as possible. Thanks!
