### ISSUE TITLE
Add Option to disable shortcuts

### ISSUE THREAD

**Issue by h00000000** [zammad/zammad#2794]
Please add an option to disable shortcuts on either a per user base or for the whole system.
With the current state of shortcuts, no matter what browser i am using to display zammad, shortcuts encumber my workflow.

**Comment by MrGeneration** [comment]
Please read the introduction text when creating issues.
This Github-Repository is for bugs only.

If you want to post feature requests, please refer to the Community: https://community zammad.org .

Closing now.

**Comment by h00000000** [comment]
Oh, when creating a new issue from a quote, there is no introduction text shown.
Gonna move to the community board then. tyvm

Community board post: [here](https://community.zammad.org/t/add-feature-to-edit-or-disable-shortcuts/3360)
