### ISSUE TITLE
Image/attachment preview is to small, need to download image and open it locally 

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2796]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Be able to read details in preview of images.

### Actual behavior:

* Preview image is to small to read detail content

### Steps to reproduce the behavior:

* and a note with an image (e. g. of Zammad overview list) and save it
* click on image to open preview 
* I'm unable to read the text (if I increase the image preview modal window size I can read it)

**Comment by martini** [comment]
Possible solution, increase modal size from large to veryLarge to show preview in general larger.

large/current setting:
![image](https://user-images.githubusercontent.com/110226/68116318-cc0a0a80-fefa-11e9-8bbc-873f19930369.png)

veryLarge:
![image](https://user-images.githubusercontent.com/110226/68116247-a4b33d80-fefa-11e9-9458-9433e43d3713.png)

**Comment by MrGeneration** [comment]
What does `veryLarge` mean in resolution terms?
As I often have quite some trouble viewing those images, as on 2k screen resolution the preview is quite small.

I'd prefer something like "fit to screen in height/width" without stretching the image. So basically `max-width: 100%` something something..

**Comment by martini** [comment]
1) veryLarge is the type if modal dialog size
2) a modal with dynamic modal size would be a completely new modal dialog which we don't have right now in whole Zammad.

It would be good to verify veryLarge modal size first. On my setup it was a very results with the inline image size.

**Comment by MrGeneration** [comment]
I can agree, `veryLarge` is way better thjan what I had before.
Even though on high resolutions I have alot of space getting lost.

But that's normal right now. :x
