### ISSUE TITLE
Mails which are beeing manually moved in IMAP folder are not beeing processed

### ISSUE THREAD

**Issue by tbsfnk** [zammad/zammad#2801]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): deb
* Operating system: Debian 9.9
* Database + version: Postgres 9.6
* Elasticsearch version: 5.6.16
* Browser + version:

### Expected behavior:
I move a mail in the shared IMAP folder of zammad and a ticket will be created

### Actual behavior:
Since yesterday, when I move a mail from my personal mail account to the shared folder of the zammad mailbox, the mail is not going to be processed, but the "Unprocessed Mails" in Zammad > Monitoring is not showing anything? (Monitoring is showing: Keine Vorfälle). The mail is also not in "/opt/zammad/tmp/unprocessable_mail"

### Steps to reproduce the behavior:
Move a personally recived mail to the inbox IMAP folder which uses zammad.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by tbsfnk** [comment]
mhm wow now zammad has processed the mails... after some hours
The only thing i did is run this command:
`zammad run rails r 'Channel::EmailParser.process_unprocessable_mails'`

I noticed that i recive some ruby errors in the production log... I posted this [here](https://community.zammad.org/t/ruby-errors-in-production-log/3388
)

**Comment by tbsfnk** [comment]
Now I noticed that the mails are still in the folder?
But I've set up the "Keep Mails on server" as no?

**Comment by tbsfnk** [comment]
I run now this command:
`zammad run rails r 'Channel.fetch'`

and now all mails are fetched and processed.

Is there something with the scheduler?

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question which this repository is not there for.
Please consult the Zammad Community: https://community.zammad.org

Closing now.

Please note that there right now are too many "maybes" even in this issue, which won't provide a good enough answer. You might want to provide logfiles over at the community.
