### ISSUE TITLE
Customer and Agent permission can be set

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2804]
### Infos:

* Used Zammad version: 3.1 
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Google Chrome, but also affects e.g. LDAP synch
* Ticket-ID: #1057852, T#1074719
* Probably a regression of: https://github.com/zammad/zammad/issues/1509 

### Expected behavior:

Zammad does not allow you to give any user agent- and user-permissions at the same time.

### Actual behavior:

Zammad allows you to set agent- and user-permissions at the same time, as long as the role name used for the agent permissions is not "Agent".

It seems like Zammad only checks for role names.
This also gives unexpected issues when working on tickets (especially ticket creation... ;) ) beside LDAP syncing.

### Steps to reproduce the behavior:

* create a own role with any agent permission(s)
* assign a customer user your new special role and save that
* it works (shall not)

### Screencast:
![zammad-allows-agentpermissions-on-custom-roles-for-customers](https://user-images.githubusercontent.com/6549061/68478987-85d1e580-0231-11ea-9ad8-134bf327883f.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
This won't be an issue once the implementation/review of #967 is done by @rolfschmidt/me. I'll close this for now because #967 will be ready soon and part of Zammad 3.5.
