### ISSUE TITLE
Monitoring has fixed interval of 8 Minutes?

### ISSUE THREAD

**Issue by sstidl** [zammad/zammad#2812]
Hi!

I am not sure, if this is intentional:
in monitoring-controller it seems to have a fixed 8 minutes check.
https://github.com/zammad/zammad/blob/1c63e966758f42ec101ffd8adb99606f1958fde4/app/controllers/monitoring_controller.rb#L81

we are getting `scheduler may not run (last execution of Stats.generate 38 minutes over) - please contact your system administrator` in the latest zammad-docker-compose version

there is an there is an interval of 11 minutes here:
https://github.com/zammad/zammad/blob/fae194918eb8a07036060a1b41f1b33c45e03cad/db/seeds/schedulers.rb#L142 

so it is very easy to have the monitoring sensor `https://YOURSITEHERE/api/v1/monitoring/health_check?token=XXX` in the red.

In our case it must be something in addition, as the stats get over an hour old.

please comment.

regards
stefan

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a rather technical questions.
Please post technical questions over at the Community: https://community.zammad.org.

Closing now.
