### ISSUE TITLE
Useless display of delete icon below note

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#2813]
### Infos:

* Used Zammad version: develop
* Installation method: git
* Operating system: CentOS 7
* Database + version: PostgreSQL
* Elasticsearch version: ES 6
* Browser + version: Firefox 70

### Expected behavior:

* Only showing icons which can be used.

### Actual behavior:

* Icon which can't be used is shown.

### Steps to reproduce the behavior:

* Add a non public note and wait for more then 10 minutes.
* Try to delete the note
<img width="614" alt="image" src="https://user-images.githubusercontent.com/378324/69149541-01a41b80-0ad7-11ea-86c5-ce31c411301f.png">

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I agree, that's confusing.
Refreshing the WebApp does not solve this.
