### ISSUE TITLE
Number of total tickets in report - error

### ISSUE THREAD

**Issue by max-fidme** [zammad/zammad#2819]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): package
* Operating system: ubuntu 14.04.6
* Browser + version: chrome 78

### Expected behavior:

* Number of total tickets in the report is display

### Actual behavior:

* Number of total  tickets is not display

![image](https://user-images.githubusercontent.com/58044382/69358917-f0e6d780-0c87-11ea-9d29-6d974accad3b.png)

### Steps to reproduce the behavior:

* Create a report and look the report.

**Comment by martini** [comment]
It's fixed in upcoming Zammad 3.2. Which will be released soon (next weeks).

**Comment by MrGeneration** [comment]
I can't find the duplicate, can you please link it?
