### ISSUE TITLE
Unable to use fulltext search (elasticsearch issue "reason":"field expansion matches too many fields, limit: 1024, got: 1048")

### ISSUE THREAD

**Issue by martini** [zammad/zammad#2821]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: 7 or higher
* Browser + version: any

### Expected behavior:

* use fulltext search

### Actual behavior:

* no fulltext search result, but an elasticsearch error message in `log/production.log`: "reason":"field expansion matches too many fields, limit: 1024, got: 1048"

### Steps to reproduce the behavior:

* No certain way to reproduce, index a Zammad database with certail attributes.

**Comment by mantas** [comment]
Is it triggered by too many custom attributes?

**Comment by martini** [comment]
Elasticsearch behavior beginning from ES7 has changed:

> There is a limit on the number of fields that can be queried at once. It is defined by the indices.query.bool.max_clause_count which defaults to 1024. There is a deprecation warning that is logged in 6.x so we changed it to an hard failure in 7.0. As this is documented and the limit is configurable I hope you don't mind if I close this issue.

In order to make elasticsearch working again, add `indices.query.bool.max_clause_count: 2000` to `/etc/elasticsearch/elasticsearch.yml` and restart elasticsearch.

**Comment by martini** [comment]
Reference: https://github.com/elastic/elasticsearch/issues/37273
