### ISSUE TITLE
Failed to run background job #1 'SearchIndexJob' 

### ISSUE THREAD

**Issue by GhaziTriki** [zammad/zammad#2825]
### Infos:

* Used Zammad version:3.2
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04
* Database + version: PostgreSQL (Ubuntu 12.1-1.pgdg18.04+1)
* Elasticsearch version: 7.5.0
* Browser + version: FF Nightly 72.0a1 (2019-12-02) (64 bits)

### Expected behavior:

* Supervision health status should be green.

### Actual behavior:

* It currently shows `Failed to run background job #1 'SearchIndexJob' 1 time(s) with 17 attempt(s). `

```json
{
   "healthy":false,
   "message":"Failed to run background job #1 'SearchIndexJob' 1 time(s) with 17 attempt(s).",
   "issues":[
      "Failed to run background job #1 'SearchIndexJob' 1 time(s) with 17 attempt(s)."
   ],
   "actions":[

   ],
   "token":"***************************************************"
}
```

### Steps to reproduce the behaviour:

* I just upgraded from 3.1 to 3.2.

Yes I'm sure this is a bug and no feature request or a general question. Oh yes !!

**Comment by MrGeneration** [comment]
Please rebuild your index and note issue #2824 as we currently can't support ES 7.5.

Upgrading to Zammad 3.2 requires an searchindex rebuild because of index changes. 
See: https://zammad.com/news/release-3-2 (Technical remarks)

**Comment by GhaziTriki** [comment]
The index does not rebuild

```bash
root@devops:~# sudo zammad run searchindex:rebuild
sh: 1: exec: searchindex:rebuild: not found
```

**Comment by MrGeneration** [comment]
Yes, the command should be: `zammad run rake searchindex:rebuild`

Sorry, that was a typo on the release news. :-(

**Comment by GhaziTriki** [comment]
I've done that command but the health service is still down. Any help?

**Comment by MrGeneration** [comment]
@GhaziTriki please create a thread over at the Zammad Community: https://community.zammad.org

Github is not the right place for technical questions.
