### ISSUE TITLE
Bug - New Overview doesnt work

### ISSUE THREAD

**Issue by heini23** [zammad/zammad#2830]
## Infos:
We use the cloud version on zammad.com.

### Expected behavior:
We try to configurate an extra overview for spam mails. At the management panel I created a new overview with the name “spam” , made it visible for agents, and selected the conditions as shown in the screenshot.
When I create the new overview, it shows right in the management panel which mails will be in this overview. (I love this feature 😉) 
![uebersicht_config](https://user-images.githubusercontent.com/32714275/70387578-073ea400-19a7-11ea-8af5-ad7bd58e8a70.jpg)

### Actual behavior:

After I created the new overview there isn’t a single mail inside. 
![uebersicht_empty](https://user-images.githubusercontent.com/32714275/70387581-0b6ac180-19a7-11ea-88ca-3058745f04a7.jpg)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @heini23 - glad you like the feature :) Would you mind writing an email to support at zammad dot com so that we can figure things out and have a look at your system? Our experts ( @MrGeneration and @KoJie ) will be ready to help. Closing this one now.
