### ISSUE TITLE
import ticket, update time lost

### ISSUE THREAD

**Issue by marBote** [zammad/zammad#2831]
zammad 3.2
zammad migrator 6.0.3
after import tickets from OTRS, the update time from original ticket lost. All over the ticket update time ist changed to the import time.

second problem, the imported tickets lost the email channel, so i can't reply per email on old (imported) tickets.

![zammad](https://user-images.githubusercontent.com/58686404/70425736-01fa5b80-1a72-11ea-9cac-3eaacc7811fe.jpg)

**Comment by MrGeneration** [comment]
Please update your first article to contain our issue template accordingly, other wise I'll need to close this issue without further check of the issue.

**Comment by MrGeneration** [comment]
I haven't received any feedback as of now and will close the issue.
Please ping me if you updated the issue.
