### ISSUE TITLE
Filters using less than and greater than

### ISSUE THREAD

**Issue by maxper75** [zammad/zammad#2833]
Hello,
as before, I open this as I think it is a bug:
I use actually spamassassin as a spam filter, this produces  headers
X-Spam-Flag: NO
X-Spam-Score: 4.705
X-Spam-Level: ****
The first one is unreliable because of our settings (it gets yes past a score of 5) but we'd like to let all the emails over score of 2 as ignored mails by zammad.
We tried with a filter like 
X-Spam-Level  [ contains ] ** (two '*' symbols)
But it did'n work properly and the mail does not get ignored
and we wanted to try 
X-Spam-Score
but the problem is that there's no 'more than' operator to do so...
Is it a good hint for an enhancement? Then add gt, lt, ge, le.
Thanks anyway for the good work.
Greetings,
Massimiliano

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question and feature request.
Please post such things over at our community, as this is not a bug.

Also `*` are most often wildcard indicators which might work in unexpected ways. Especially in postmaster filters, as these are capable of regular expressions. 

This works as designed.
