### ISSUE TITLE
Unclear meaning of "Public-Menu" tab in KB admin

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#2834]
### Infos:

* Used Zammad version: 3.2.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

The "Public-Menu" tab in Knowledge Base admin view should contain a short explanation text on what the public menu is (for):

![image](https://user-images.githubusercontent.com/3873515/70442005-b78ad600-1a95-11ea-9747-4f1e2c01ddcd.png)

### Actual behavior:

The "Public-Menu" tab in Knowledge Base admin view contains no explanation and confuses administrators.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
@thorsteneckel I've a feeling that the recent redesign as discussed in #2867 addresses this

![CleanShot_2019-12-20_at_18 27 12](https://user-images.githubusercontent.com/36944/71788447-ea8b9f80-302a-11ea-8948-9fe07f7b275f.png)

**Comment by thorsteneckel** [comment]
This was initially reported by @KoJie - what do you think? Are your concerns addressed by the change @mantas shows in the previous comment?

**Comment by KoJie** [comment]
If you have familiarized yourself a little with the KB, you will know what the "Public Menu" is. However, a short explanatory sentence would make it 100% clear at first view and leave no more questions open. A short sentence like in the menu item Languages will do: 
![image](https://user-images.githubusercontent.com/22768032/71822011-08d9b580-3094-11ea-9bf8-8893e72ac298.png)

My suggestion for the text is:
"Here you can add further links to your public FAQ page, which will be displayed either in the header or footer."
Depending on what's behind "Contact" & "homepage", a more detailed explanation would probably be helpful. At first sight the screenshot is not self-explanatory for me.

**Comment by mantas** [comment]
@KoJie what do you think about following?

![Screenshot 2020-01-07 at 02 04 22](https://user-images.githubusercontent.com/36944/71858035-5a189200-30f2-11ea-8dd2-b13be0e8db79.png)

Long term, it may make sense to give KB it's own "middle column" settings section and then split settings into separate views for public and internal UIs.

**Comment by KoJie** [comment]
That looks great for me :)

**Comment by thorsteneckel** [comment]
Hey @mantas - can you give me a short heads up on this one? I haven't found a matching branch. Do you think we can get this ready for the next release?

**Comment by mantas** [comment]
@thorsteneckel it comes as part of #2867 MR which I'm rebasing
