### ISSUE TITLE
Assign users to organizations isn't possible

### ISSUE THREAD

**Issue by alveolus** [zammad/zammad#285]
I use zammad.com. It is not possible to assign users to organizations. The organizations do not appear in the profile, only my own company.

**Comment by martini** [comment]
Can you add a url (maybe also a screenshot) where the problem appears?

**Comment by alveolus** [comment]
Some organizations have already been created. However, only my own company and the Zammad Foundation appear in the box.

https://ABC.zammad.com/#manage/users

![image](https://cloud.githubusercontent.com/assets/23032204/19676326/f215b2ca-9a93-11e6-807d-418c2f457dec.png)

**Comment by monotek** [comment]
Works for me in current 1.2 dev.
Closing.
