### ISSUE TITLE
Wrong user is used when "X-On-Behalf-Of” header value is an email that starts with digits

### ISSUE THREAD

**Issue by alexdonskih** [zammad/zammad#2851]
### Infos:

* Used Zammad version: 3.2.x
* Installation method (source, package, ..): Install on Ubuntu via DEB
* Operating system: Ubuntu 16.04 LTS
* Database + version: PostgreSQL 9.5.19 
* Elasticsearch version: 5.6.16
* Browser + version: Chrome 78.0.3904.108

I’m getting a wrong user information when running a request via rest API using “X-On-Behalf-Of” header:
```curl -H "Authorization: Token token=<token>" -H 'X-On-Behalf-Of: "123asd@my.email"' -H "Content-Type: application/json" http://zammad.local/api/v1/users/me```

### Expected behavior:

* Getting info about user with email 123asd@my.email

### Actual behavior:

* Getting info about user with id 123. These a different users.

### Steps to reproduce the behavior:

* Create a user who’s email starts from digits
* Create a user who’s id is the same digits from the other user’s email
* Run an API request from the Infos

### Additional infos:
I fixed this temporarily for my Zammad installation by editing:
/opt/zammad/app/controllers/application_controller/has_user.rb

Line 49 changed from:
`%i[id login email].each do |field|`
to
`%i[login email id].each do |field|`

Yes I'm sure this is a bug and no feature request or a general question: 
https://community.zammad.org/t/wrong-user-info-is-shown-when-requesting-api-v1-users-me-and-passing-an-email-through-x-on-behalf-of-header/3561

**Comment by MrGeneration** [comment]
I'm sorry, but in a current Zammad 3.6 I can no longer reproduce this.
I currently expect this to be fixed "magically". Within the last commits.

Please ping me if this still happens on your 3.6 stable installation.

**Comment by alexdonskih** [comment]
Hi @MrGeneration. Unfortunately the issue is still persistent on Zammad version 4.1.x. The solution is still the same as provided in the original post. Thanks.
