### ISSUE TITLE
Default Priority on ticket creation not changeable

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2852]
### Infos:

* Used Zammad version: 3.2 and earlier
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Tested on latest Google Chrome, should affect all Browsers.
* Ticket-ID: #1060080 (1079119) , #1067995, #1093374
* Indirectly assiociated with: https://github.com/zammad/zammad/issues/728

### Expected behavior:

* When changing the default priority via `.default_create: true` attribute the new ticket dialogue will display the new default priority selected (if I disabled the other default priority first).

### Actual behavior:

* When changing the default priority via `.default_create: true` attribute, the new ticket dialogue will still show it's `2 normal` default value. Even when renaming the priority, it will be sticky on it.

Issue line seems to be:
https://github.com/zammad/zammad/blob/899613421489617990b3caf58b179afbd5576daf/app/assets/javascripts/app/models/ticket.coffee#L14

### Steps to reproduce the behavior:

* deactivate the default default Priority value: `Ticket::Priority.find_by(name: '2 normal').update(default_create:false)`
* activate a new default Priority: `Ticket::Priority.find_by(name: '3 high').update(default_create:true)`
* Reload the Web Application (even restarting Zammad doesn't help)
* click on the green plus on the lower left to "create a new ticket" and take a look at the default value of Priority

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
> @martini wrote (gitlab):
> And I see since it is an object manager attribute... it's defined in backend https://github.com/zammad/zammad/blob/develop/db/seeds/object_manager_attributes.rb#L275 (which will overwrite https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/models/ticket.coffee#L14)
> 
> Finally: IMO it would be good to build Admin UI for managing/change default priority via object manager attributes (not add conditions to have this behavior change in the meantime).
> 
> Finally: IMO it would be good to build Admin UI for managing/change default priority via object manager attributes (not add conditions to have this behavior change in the meantime).
> 
> In the meantime this would be the workaround (to do it manually):
> 
> ```
> attribute = ObjectManager::Attribute.find_by(name: 'priority_id')
> attribute.data_option[:default] = Ticket::Priority.find_by(default_create: true).id
> attribute.save!
> ```

**Comment by thorsteneckel** [comment]
Should be possible now with Core Workflows - check needed

**Comment by MrGeneration** [comment]
Would be an option. 2 of 3 customers affected are working with `Plus`.
