### ISSUE TITLE
Deletion of notes impossible if internal and communication = true

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2853]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any (tested and verified on Chrome)
* Ticket-ID (original issue): #1060109
* Ticket-ID (regression affected users): #1080817

### Expected behavior:

When changing notes to `communication: true`, you still can delete your own created internal notes (within the 10 minutes).

### Actual behavior:

When changing notes to `communication: true`, you won't be able to delete your own internal notes within 10 minutes any longer. This requies you to have agent rights only (so nothing administrative).

#### Sidenote:

SLAs ignore internal notes (if the communication attribute is set to true) which is why it still should be possible to delete them and (if not, admins shouldn't be allowed as well).

I think it's the following line striking here:
https://github.com/zammad/zammad/blob/f35cd7fbe9d94b8353147c420853b369e82d46ee/app/controllers/ticket_articles_controller.rb#L151

### Steps to reproduce the behavior:

* change the ticket article type 'note' from `communication: false` to `communication: true`
* login as agent
* open any ticket (or create a new one)
* post an internal note to the ticket
* (deletion button is presented) try to delete the note
  * error message  `not authorized (admin permission required)!` or `not authorized` is returned via UI

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
In the mean time we had to learn that this issue actually introduced a regression which has been addressed by #3086 .

**Comment by MrGeneration** [comment]
This is a regression of issue #3086

**Comment by thorsteneckel** [comment]
@mantas looks like we introduced a regression while fixing #3086. Would you mind having a look?
