### ISSUE TITLE
Zammad E-Mails having the attachment tag in Outlook 365 even when having now attachment

### ISSUE THREAD

**Issue by frankBahlsen** [zammad/zammad#2855]
### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): Docker
* Operating system: Debian
* Database + version: -
* Elasticsearch version: -
* Browser + version: -

### Expected behavior:

*  When I open Outlook 365 to review the E-Mails send via Zammad, I expect them, to have no attachment-tag, besides they really have an attachment.

### Actual behavior:

* When I open Outlook, it shows me the attachment-tag on every single E-Mail, that went through Zammad

### Steps to reproduce the behavior:

* Write an E-Mail to an address integrated in Zammad. Wait for the auto-response and check it with Outlook 365.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I'm not sure if this is really a bug or rather a third party issue.
The mails itself do not contain any information about attachments, so what should be enhanced?

I guess you're talking about these:
![image](https://user-images.githubusercontent.com/6549061/70649769-15fab480-1c4e-11ea-9e9d-0af7b9392aa2.png)

**Comment by raffisweb** [comment]
Maybe this happens since Outlook misinterpretes some text formats and displays them as attachment: [Prevent Winmail.dat Attachments in Outlook](https://www.lifewire.com/prevent-sending-winmail-dat-attachments-1173717). 

Solution would be to send messages in plain text or html and to prevent rtf.

**Comment by frankBahlsen** [comment]
> I'm not sure if this is really a bug or rather a third party issue.
> The mails itself do not contain any information about attachments, so what should be enhanced?
> 
> I guess you're talking about these:
> ![image](https://user-images.githubusercontent.com/6549061/70649769-15fab480-1c4e-11ea-9e9d-0af7b9392aa2.png)

Yes, this the problem we face.
If the solution is to send messages as html or plain text, i still need to ask, where to find the needed configuration.

**Comment by MrGeneration** [comment]
> Solution would be to send messages in plain text or html and to prevent rtf.

That imho hasn't to do anything with Zammad, because it always sends HTML mails.
Zammad has issues with winmail.dat incoming, but that's an outgoing issue.

**Comment by raffisweb** [comment]
Maybe @frankBahlsen is able to post some source code of an empty support message with this issue (no real support information, please!).

**Comment by MrGeneration** [comment]
As we haven't received any further feedback and this is, in my opinion, a third party issue - I'll be closing this issue.
