### ISSUE TITLE
Issue with search user API

### ISSUE THREAD

**Issue by jeyanthan88** [zammad/zammad#2857]
### Issue with search user API:

* The search user API returns empty response instead of desired output:

### API call:

* https://zammadurl/api/v1/users/search?query=mobile:9999999999
GET
Basic Auth with username and password

### Current bug behavior:

* 200 OK []
Empty response

### Steps to reproduce the behavior:

* Make an API call to search a user with a query and the response given is empty.

**Comment by jeyanthan88** [comment]
https://zammadurl/api/v1/users?phone=9999999999

This API call works fine though.

**Comment by MrGeneration** [comment]
Sorry, but this rather looks and sounds like a technical question.
Please note that this repository is for bugs only, please create a thread over at the Zammad Communtiy https://community.zammad.org - it's the better place. :-)

Thanks for your understanding, closing.

**Comment by jeyanthan88** [comment]
The same API calls returns results on 3.1.0 
Upgrading to 3.2.0 has made this API call return empty result and hence tagged as a bug.
Other API calls on organizations, tickets and even list all users are working fine.

**Comment by jeyanthan88** [comment]
Seems to work fine now after a rebuild of elasticsearch index.
