### ISSUE TITLE
Searching unser in email reply not working anymore in 3.2

### ISSUE THREAD

**Issue by t3easy** [zammad/zammad#2858]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): docker-compose
* Operating system: zammad/zammad-docker-compose:zammad-3.2.0-6
* Database + version: zammad/zammad-docker-compose:zammad-postgresql-3.2.0-6
* Elasticsearch version: zammad/zammad-docker-compose:zammad-elasticsearch-3.2.0-6
* Browser + version: Firefox 72

### Expected behavior:

* Searching in mail to an mail cc for users like in Zammad 3.1 works

### Actual behavior:

* No user search is triggerd during typing

### Steps to reproduce the behavior:

* Reply to a ticked by mail and try to add another recipient. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry,

but this sounds rather like a technical question - please consult the Zammad community for technical questions: https://community.zammad.org

Most proberbly your searchindex is broken and needs a reindex (mandatory with upgrading to 3.2).

Closing now.

**Comment by t3easy** [comment]
Then the [docker-entrypoint](https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh#L101-L104) should be adapted. I fill a report over there and refere to this.

**Comment by MrGeneration** [comment]
Please open a issue in the docker-compose repo at https://github.com/zammad/zammad-docker-compose 

It's possible that this action has not been run in between the update. Please run it manually. If it still does not work, please open a issue at the right repo.
