### ISSUE TITLE
Answers from google mail shows complete quote

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#286]
If you answer to the email via Google mail (android app), the full quote was shown within the ticket:

![image](https://cloud.githubusercontent.com/assets/6099976/19650545/f91feaa2-9a09-11e6-82db-e60dcfe119f4.png)

(Marked text is the quote)

**Comment by hanneshal** [comment]
Hi,

could you please provide an example:
1) initial mail
2) your reply where the quote is missing

You should be able to download the plain mail after you click on an ticket-article
![zammad](https://cloud.githubusercontent.com/assets/804939/19654562/21d43f52-9a19-11e6-881e-025d419ab311.jpg)

I'll have a look into this.

regards

**Comment by MDXDave** [comment]
Both mails in attachment.

[zammad gmail.zip](https://github.com/zammad/zammad/files/548472/zammad.gmail.zip)

**Comment by martini** [comment]
Fixed https://github.com/zammad/zammad/commit/b9b8f1df46c42aff8e870d4257cdbad26a404918
