### ISSUE TITLE
Prioritize LDAP synchronization over Exchange synchronization

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2864]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket#10105096

### Notes:

* This enhancement came via the community: https://community.zammad.org/t/synchronize-users-via-ldap-and-than-exchange/3601
* This enhancement affects the synchronization if both LDAP and exchange sync are enabled.

### Desired behavior:

When both LDAP and exchange sync are enabled, Zammad will recognize and ignore LDAP users during the exchange sync. 

Reason behind this is that this ensures Zammad will keep your usernames in tact to allow LDAP authentication at all time.

This change will suspect the LDAP server to be the most current and accurate source before exchange addressbooks!

### Actual behavior:

Currently Zammads Exchange sync overwrites login attributes of users, if the user is found in LDAP and exchange. This causes users not being able to login with their usernames.

### Fix insights:

There should be a new Sequencer Unit that checks if an existing/found `instance` was synced by an active LDAP integration. If so the further processing of the Sequence should be `skipped` by setting the `action` to that.

### Steps to reproduce the behavior:

* activate LDAP synchronization
* activate Exchange synchronization
* ensure you have a user with the same mail address within Exchange and LDAP
* manually trigger LDAP sync
* check the username
* manually trigger Exchange sync
*  check the username (will change)
* keep playing that game as long as you'd like... :-)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by HeinrichMetel** [comment]
Same issue at #2549

**Comment by thorsteneckel** [comment]
Great catch @HeinrichMetel ! Can't imagine how we could have missed it 👀 @MrGeneration it's up to you how proceed from here.

**Comment by MrGeneration** [comment]
Thank you so much for the heads up and thanks for your patience!
I updated this issues description to hold all information relevant from #2549 as well and have closed the duplicate. 🙌

**Comment by Nejamul068** [comment]
Ftc.gov her how much USA dollars wittien i accept

**Comment by MrGeneration** [comment]
Hey,

thanks for your interest to contribute to Zammads Core!
Please contact sales [at] zammad [dot] com for an estimate! :)

This enhancement still is missing specification which is why we don't have the required numbers yet.
