### ISSUE TITLE
Telegram integration not working

### ISSUE THREAD

**Issue by make-suffer** [zammad/zammad#2870]
### Infos:

* Used Zammad version: 3.2.0
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04

### Expected behavior:

* When you send telegram message to bot, you get a greeting and can create task, reply to this message in web interface.

### Actual behavior:

* Telegram can't get to webhook due to an error(in my understanding): 
```
Started GET "/api/v1/channels_telegram_webhook/qNSlVULJ1wsL_A
Processing by ErrorsController#routing as HTML
Parameters: {"bid"=>"817681594", "a"=>"api/v1/channels_telegram_webhook/*"}
No route matches [GET] /api/v1/channels_telegram_webhook/qNSlVULJ1wsL_A (ActionController::RoutingError)

```
When i'm trying to tesh this with CURL, i'm getting the same error 'curl https://helpdesk.connectome.ai/api/v1/channels_telegram_webhook/token?bot_id
{"error":"No route matches [GET] /api/v1/channels_telegram_webhook/*"}'

I'm quite sure it's a bug, but can surely be mistaken.

![image](https://user-images.githubusercontent.com/46104913/71107074-82872d80-21d1-11ea-98a1-77eb9e24db29.png)

**Comment by MrGeneration** [comment]
Sorry for asking, but why aren't you testing this with Telegram as intended?
My Telegram integration works, I'm not sure if this is really a bug or rather a technical question which is why I won't tag it yet.

I'm just trying to understand what you're trying to do.

Maybe also the complete payload helps (without personal information like API Keys please :) )

**Comment by make-suffer** [comment]
> Sorry for asking, but why aren't you testing this with Telegram as intended?
> My Telegram integration works, I'm not sure if this is really a bug or rather a technical question which is why I won't tag it yet.
> 
> I'm just trying to understand what you're trying to do.
> 
> Maybe also the complete payload helps (without personal information like API Keys please :) )

I also tested it through telegram, the info is in the attached screenshot.
Here's the response in text format, maybe it would be more convenient:
{"ok":true,"result":{"url":"https://helpdesk.connectome.ai/api/v1/channels_telegram_webhook/XXXXXXXXXXXX?bid=xxxxxxx","has_custom_certificate":false,"pending_update_count":63,"last_error_date":1576689396,"last_error_message":"Connection timed out","max_connections":40}}

**Comment by MrGeneration** [comment]
Please call
`https://api.telegram.org/bot{API-TOKEN-BOT}/getWebhookInfo`
with your API-Token and check the response. Might be an issue in the configuration.

Connection timed out usually is a sign for something blocking.
Ensure your Zammad installation can be reached from the outside and there's no "strange filtering" from an inteligent firewall or so.

**Comment by make-suffer** [comment]
>

>  Please call
>  `https://api.telegram.org/bot{API-TOKEN-BOT}/getWebhookInfo`
>  with your API-Token and check the response. Might be an issue in the configuration.

That's the info in the screenshot and attached text.
>
>Connection timed out usually is a sign for something blocking.

I'm kinda figuring it out, cause we used some telegram bots in our workflow, but all of them used getUpdatesmethod instead of webhook.
>
>Connection timed out usually is a sign for something blocking.

Yeah, I'm starting to think it can be our government shenanigans with telegram, that's the root cause of this, thanks for quick reply, we'll try to figure something out.
