### ISSUE TITLE
No search in "to" or "cc" input fields

### ISSUE THREAD

**Issue by Lillecarl** [zammad/zammad#2871]
### Infos:

* Used Zammad version:
3.2.X
* Installation method (source, package, ..):
package
* Operating system:
Ubuntu 18.04.3 LTS
* Database + version:
psql (PostgreSQL) 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1)
* Elasticsearch version:
Version: 7.5.1, Build: default/deb/3ae9ac9a93c95bd0cdc054951cf95d88e1e18d96/2019-12-16T22:57:37.835892Z, JVM: 13.0.1
* Browser + version:
Firefox 71.0 (64 bit)
Google Chrome 79.0.3945.88 (64 bit)

### Expected behavior:

When writing in the "to" or "cc" fields, it should start searching and show suggestions

### Actual behavior:

![image](https://user-images.githubusercontent.com/207073/71159047-468db000-2245-11ea-80bf-9fd7612c8bd2.png)
It never gives suggestions in this field

### Steps to reproduce the behavior:

Install Zammad 3.1 on Ubuntu 18.04.3, update via packages to 3.2, try typing email into "to" field.

### Related issues
https://github.com/zammad/zammad/issues/2858

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry but this is a technical questions.
**Please do not post technical questions on this github repository!**

The Zammad Community is the perfect place for technical questions.
Please simply rebuild your searchindex like advised in the release notes, this step is required with upgrading to Zammad 3.2.

For more information please see:
* https://community.zammad.org/t/zammad-3-2-is-available/3656
* https://zammad.com/news/release-3-2
* https://docs.zammad.org/en/latest/install-elasticsearch.html#configure-zammad-to-work-with-elasticsearch

Thank you

**Comment by Lillecarl** [comment]
It's most certainly a bug that the package manager neither mentions this during upgrade or zammad running the required command after detecting an upgrade. Thanks for the quick response anyhow.

In case anyone else finds this issue, the command required to run is:
`zammad run rake searchindex:rebuild`

**Comment by MrGeneration** [comment]
Before this gets an misunderstanding:
This is required once and not the usual case for upgrading Zammad which is why there's no specific information on this.

However, we're already discussing a option to notify the admin about this being mandatory because of an upgrade.

**Comment by Lillecarl** [comment]
Thanks for the clarification 😄
