### ISSUE TITLE
No list of matching customers expanded from To and Cc fields any more (since Zammad 3.2.x)

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#2872]
### Infos:

* Used Zammad version: 3.2.0-1576685654.40972b3f
* Installation method (source, package, ..): apt-get from Debian Repo 
* Operating system: Debian 8.11
* Database + version: MariaDB 10.0.38-0+deb8u1
* Elasticsearch version: 5.6.16
* Browser + version: Google Chrome 78.0.3904.108 and Firefox 60.8.0esr on CentOS 7.7, Firefox 71.0 and Safari 13.0.3 on mac OS

### Expected behavior:

When starting to enter a (user)name in a Cc or To field, a list of matching customers with their associated email addresses was expanded, from which an addressee could be selected.

This worked until Zammad 3.1.0-1570545649.c1160c5e.jessie.

### Actual behavior:

No list of customers/email addresses is expanded any more.  However expansion still works in the "Customer" field when creating a new ticket.

This behaviour exists since the upgrade to 3.2.0-1576685654.40972b3f.jessie.

Behaviour is consistent between various browsers and platforms (see the list above).  Rebooting the Zammad server didn't resolve the issue.

### Steps to reproduce the behavior:

  * reply to an article or create a new ticket
  * start typing the name of an already known customer in a To or Cc field
  * don't see a list of possible customers 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please also see:
https://github.com/zammad/zammad/issues?q=is%3Aissue+is%3Aclosed

You need to rebuild your searchindex.
This is mandatory with upgrading to 3.2 as communicated on our news. :-)

Closing now.

**Comment by fthommen** [comment]
>  This is mandatory with upgrading to 3.2 as communicated on our news. :-)

What news?  We get Zammad updates through ``apt-get dist-upgrade``.  I am _quite_ sure, there wasn't any notice on a required searchindex rebuild.  On the other hand: Couldn't the installer do this automatically? That would be much more admin-friendly :-)

**Comment by MrGeneration** [comment]
This is actually not implemented or technically possible at the moment.
This would be a feature request for the community. ;)
