### ISSUE TITLE
Entrega fallida: “Unable to send telegram message: Timed out connecting to server

### ISSUE THREAD

**Issue by avenegas78** [zammad/zammad#2879]
### Infos:

* Used Zammad version: 3.2.x
* Installation method (source, package, ..): Ubuntu via DEB
* Operating system: Ubtuntu server 18.04.3
* Database + version: PostgresQL 10.10
* Elasticsearch version: 7.5.1
* Browser + version: Chrome 79.0.3945.88 (Build oficial) (64 bits)

### Expected behavior:

* When Zammad received a message through telegram client to a bot created, it creates a ticket, but when an agent reply from Zammad, the message should send to telegram client

### Actual behavior:

* All messages inside a ticket generated from telegram client no are sent from Zammad to telegram client. The Zammad outputs an error message Entrega fallida: “Unable to send telegram message: Timed out connecting to server”; but if I send a message from web browser the message is sent without problem and reach to telegram client. It follows an example replacing information of bot (token, id, etc.) with XXXXXX.
https://api.telegram.org/botXXXXXXXXXXXXXX/sendmessage?chat_id=XXXXXX&text=test123

{“ok”:true,“result”:{“message_id”:22,“from”:{“id”:XXXXXXXX,“is_bot”:true,“first_name”:“XXXXXX”,“username”:“XXXXX”},“chat”:{“id”:XXXXXX,“first_name”:“Antonio”,“last_name”:“Venegas”,“type”:“private”},“date”:1577747292,“text”:“test123”}}

I have a CA certificate generated via Let’s encrypt run correctly, and I saw this error at /var/log/zammad/production.log Completed 500 Internal Server Error in 60157 ms.

### Steps to reproduce the behavior:

* From a ticket generated through telegram client, press reply option of edit box and press update button, and the message isn’t sent and then a moment Zammad outputs aforementioned error message.

Thank you very much.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I'm closing this as a technical question, because you also posted the same issue on the Community.
Please, for the next time, decide for one board.

This decision can be made by "technical question / feature request" or "bug" (while bugs are for Github).

( see: https://community.zammad.org/t/entrega-fallida-unable-to-send-telegram-message-timed-out-connecting-to-server/3723 )
