### ISSUE TITLE
Translation introduction text shows wrong keyboard shortcut

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2885]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Firefox latest, Google Chrome latest

### Expected behavior:

* When opening the translation menu within the admin settings, the introduction text will show the correct keyboard shortcut to activate the inline translation (just like the keyboard shortcut overview does) depending on the browser.

### Actual behavior:

* When opening the translation menu within the admin settings, the introduction text will show the keyboard shortcut for inline translation for MacOS, no matter if you're on MacOS or not.

### Screencasts:

![image](https://user-images.githubusercontent.com/6549061/72163371-0644cc00-33c4-11ea-97ce-e5d45b5e0c8c.png)

![image](https://user-images.githubusercontent.com/6549061/72163418-18bf0580-33c4-11ea-88b3-49c15acd9752.png)

### Steps to reproduce the behavior:

* go to admin menu -> translation
* get the description text (see the keyboard shortcut)
* you can test different browsers and oses if needed

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mgruner** [comment]
@thorsteneckel this is not really related to translations or the Weblate migration.
