### ISSUE TITLE
Text Editor deletes text unrecoverably if quicktext was canceled with Ctrl+Backspace

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2886]
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: -
* Elasticsearch version: -
* Browser + version: Firefox latest
* Ticket: #1088334

### Expected behavior:

* When starting to type a quick text, then noticing that I don't want to use quicktext. The text written directly afterwards should stay where it is.

### Actual behavior:

* The text gets deleted when you use Ctrl+Backspace and can't be recovered via CTRL + Z

### Steps to reproduce the behavior:

* See gif

![Issue](https://user-images.githubusercontent.com/44224243/72167887-4c9e2900-33cc-11ea-90e9-a8bc2ad94445.GIF)

- Use the quicktext and before selecting something use Ctrl+backspace to delete the line.
- Start no writing some other text.
- After typing out the actual text I simply press enter.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Personally I see this as a usuage issue.
Because you're still inside the dialogue (you didn't press escape to escape this deialogue).

I can verify this behaviour but am unsure how to react.
@thorsteneckel can you please decide if this is a UI bug to you or not?

**Comment by thorsteneckel** [comment]
It is one 👍

**Comment by SEGGER-NV** [comment]
I get your point, but for the user it is not apparent that something is wrong. And I heard from colleagues that they sometimes they wrote whole paragraphs only for them to be completely gone after hitting enter which is very frustrating :(

This was the first time I could find a constant reproducer for this weird quirk.

Edit: OK just saw it was verified as a bug. So nvm my comment.

**Comment by thorsteneckel** [comment]
From a technical perspective it looks like an internal state is not cleared properly. The app does not expect that a user text is written and thinks it should remove the text module.

**Comment by martini** [comment]
I have a question, because I cant follow.

What is the expected behavior? Please a step by step list. Thanks!

Note: By entering :: a non text writing mode is started, so all what is entered is related to text module search. You can to this by pressing ESC.

**Comment by MrGeneration** [comment]
Steps to repoduce:
* Write an ticket article
* start typing ``::`` and search for a text module
* notice you don't want / need a text module and remove the text module part ``::blah`` with backspace
  * note: The text module dialogue / UI is now gone
* Enter new text you want
* hit enter because you need a new line
  * DOH! My just typed text is gone

**Comment by martini** [comment]
Ok. Now I can follow. Thanks. 

So it's expected to still show the text module widget (to let the user know that he is in text module search mode) - even if there is no text module search result, right?

**Comment by thorsteneckel** [comment]
I'd expect that Zammad notices that it's not in text module search mode anymore and release all handlers.

**Comment by MrGeneration** [comment]
I agree to thorsten - or don't remove it and add a remark ("close with ESC") to indicate the user something has to be done right now.

This shall help the user to recognize steps needed to be taken.

**Comment by mantas** [comment]
I'd say it should exit text module mode if `::`was removed from the text field.

**Comment by romitgithub** [comment]
Can't get anywhere with this issue. Unassigning myself for now. It's open for pickup
