### ISSUE TITLE
Entering pending till time for Waiting status is difficult to enter with Firefox

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#2887]
### Infos:

* Used Zammad version: 3.2 (hosted)
* Browser + version: Firefox 72.0.1
* T#1065092, #1077517

### Expected behavior:

* When I set the time for a "Waiting for" status, a click on the hours and an entry of e.g. "13" should enter it correctly before the colon as "13:00".

### Actual behavior:

* When changing the ticket status to a "waiting-state", I select a date, then I click on the hours in the time field and enter e.g. 13

![image](https://user-images.githubusercontent.com/22768032/72250249-74bf9f00-35fb-11ea-86a3-092b6186d026.png)

![image](https://user-images.githubusercontent.com/22768032/72250308-9456c780-35fb-11ea-9b17-01fd6eb8e149.png)

*Actually the 11 should become a 13, but in the time field "01:03" is entered:

![image](https://user-images.githubusercontent.com/22768032/72250355-b2242c80-35fb-11ea-8d5d-9b98cb7432ed.png)

* It's just possible to correct the time field by deleting everything and entering 13 again. 

* But if I select another field in between, the input will again be displayed incorrectly. 

### Steps to reproduce the behavior:

* Open Zammad with Firefox
* Go into a ticket and change the status to a "Waiting status
* Try to enter an hour e.g. 11 o'clock

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
@KoJie what behaviour would you expect for other non-complete inputs? For example:

- 3
- 13:2
- 3:20

**Comment by KoJie** [comment]
It should be t same as it is in e.g. Google Chrome:

- 3 enter --> 03:00
- 132 enter --> 13:02
- 320 enter --> not valid time format; for this you have to type in 0320 

if only one number is typed in (no matter if hours or minutes) the input starts " at the end" --> when entering 2 it will always be 02

**Comment by mantas** [comment]
Note for someone stumbling upon this issue in the future. The initial input issue is fixed. Incomplete inputs handling is left as-is.
