### ISSUE TITLE
How to develop new integrations

### ISSUE THREAD

**Issue by pixelmultiplo** [zammad/zammad#2889]
Could someone point me to some docs about this?
I'm developing a simple custom webhook integration, I successfully created an endpoint that works but ims truggling in making the settings page and the package right.

**Comment by MrGeneration** [comment]
Sorry but please don't user our Repositories for technical- or development questions, as this is the wrong place to do so.

Please use the Zammad community: https://community.zammad.org

Additionally there are currently no documents on this, as this is a living WIP.

CLosing now.
