### ISSUE TITLE
unicorn support

### ISSUE THREAD

**Issue by Libermentix** [zammad/zammad#289]
Hi @martini ,

i'm just deploying zammad to our production server. is there a specific reason to chose against unicorn, or would you mind us contributing an option to use unicorn instead of puma?

regards
Felix

**Comment by martini** [comment]
Hi @Libermentix 

there is no specific reason why puma. You are welcome to contribute unicorn als option to use. :)

Greetings,

 -Martin

**Comment by Libermentix** [comment]
@martini no problem. I see there is no production group behind puma. i would add a production group, just don't know how we can model this without breaking the Gemfile since it would require puma to be in a group. opinions?

**Comment by martini** [comment]
@Libermentix I don't have extensive experiences in this area. How about doing it like mysql/pg support by adding own groups. You need to install the gems later by e. g.:

bundle install --without test development postgres puma
or
bundle install --without test development postgres unicorn

In other words, feel free to create a pull request and let's discuss/see. 🤓

**Comment by Libermentix** [comment]
is on its way. let me test the configuration first :-)

**Comment by Libermentix** [comment]
@martini i tested it yesterday and it seems to work. 
let me know if there is anything that i should still add to the PR #291

**Comment by rkaldung** [comment]
Should be done with PR https://github.com/zammad/zammad/pull/291
