### ISSUE TITLE
Installing on Dokku

### ISSUE THREAD

**Issue by pixelmultiplo** [zammad/zammad#2892]
I get this

`! ! Could not detect rake tasks ! ensure you can run$ bundle exec rake -P against your app ! and using the production group of your Gemfile. ! rake aborted! ! Fiddle::DLError: can't load libImlib2.so
`
however

`# sudo apt-get install libimlib2-dev Reading package lists... Done Building dependency tree Reading state information... Done libimlib2-dev is already the newest version (1.4.10-1). 0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.`

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question.
Please consult the documentation and ensure you're meeting all requirenenments. (Pro tipp, your error message is already telling you whats wrong: `(...) Fiddle::DLError: can't load libImlib2.so`.

For technical questions please consult the Community: https://community.zammad.org

Closing now.
