### ISSUE TITLE
Emails with binary body (attachment as body) get handled as if they were text messages which breaks the attachment

### ISSUE THREAD

**Issue by AdamC1228** [zammad/zammad#2894]
### Infos:

* Used Zammad version: 3.2.x
* Installation method (source, package, ..): package
* Operating system: CentOS 7.7.1908
* Database + version:  -
* Elasticsearch version: 6.8.0
* Browser + version: FireFox 72.0.1

### Expected behavior:

*No Static when playing back audio attachments. 

### Actual behavior:

*Static when playing back audio attachments. 
*No Static when opening audio from the raw email. 
*Audio files in the raw email are slightly larger than when the ones listed in attached files. 

### Steps to reproduce the behavior:

*Click on attached file (.wav).
*Open in VLC (Or save file to desktop and open from there)
*Play audio.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by AdamC1228** [comment]
[production.zip](https://github.com/zammad/zammad/files/4069010/production.zip)

**Comment by MrGeneration** [comment]
Sorry I don't really understand the issue.
Am I guessing correct that you're saying that Zammad does corrupt received audio files when importing it?

**Comment by AdamC1228** [comment]
Correct

**Comment by AdamC1228** [comment]
I have tried excluding the audio file from elastic search parsing using es_attachment_ignore types. The audio files still arrive damaged. 

 zammad run rails r "Setting.set('es_attachment_ignore', [ '.png', '.jpg', '.jpeg', '.mpeg', '.mpg', '.mov', '.bin', '.exe', '.box', '.mbox' ] )"


![Capture](https://user-images.githubusercontent.com/13957003/72845143-fd79b300-3c6b-11ea-8d32-32338cfd3389.JPG)

[VoiceMessage.zip](https://github.com/zammad/zammad/files/4093803/VoiceMessage.zip)

**Comment by thorsteneckel** [comment]
Hey @AdamC1228 - this should be fixed with the commit above. New `development` package will be ready in 30 minutes from now. The fix will be released with the upcoming 3.3 release in a few weeks 👍
