### ISSUE TITLE
Update notification mail

### ISSUE THREAD

**Issue by Khawlamel** [zammad/zammad#2896]
How can I modify a notification mail in zammad I did not find this message in trigger .
that's the message:
zammad Helpdesk Notification
Hello ,

The ticket (TEST SUPP) was updated by "Nicole Braun (Zammad Foundation)".

modifications:
Condition: new -> closed

**Comment by MrGeneration** [comment]
Sorry but this is a rather technical question.
Technical questions are best fitting in the Zammad Community: https://community.zammad.org

Please also fill in the template that's provided there to help others to help you.
I'll close this issue, because it's a technical question.
