### ISSUE TITLE
xxx.xxx.xxx.xxx/ws end-point for event listening

### ISSUE THREAD

**Issue by MontiniCristian** [zammad/zammad#2901]
Is it currently possible to use the **/ws** end-point to open a WebSocket in order to listen for events? Is this end-point requiring a sort of authentication in order to receive all the events?

If not, is there a solution aimed to listen for tickets update events which don't require polling?

**Comment by MrGeneration** [comment]
Sorry, but this is rather a technical question.
Please do not use this Github repository for technical questions, but the Community instead:
https://community.zammad.org

**Comment by thorsteneckel** [comment]
JFI: Relevant topic can be found here: https://community.zammad.org/t/details-about-push-api/1622
