### ISSUE TITLE
Filtering ticket on ticketstate returning tickets with non corresponding state

### ISSUE THREAD

**Issue by YWatchman** [zammad/zammad#2902]
### Infos:

* Used Zammad version: 3.2.x
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 18.04.3
* Database + version: MariaDB 10.2.30
* Elasticsearch version: 7.5.2
* Browser + version: cURL

### Expected behavior:

* Should return tickets with open and new state

### Actual behavior:

* Returns tickets with all states

### Steps to reproduce the behavior:

* /usr/bin/curl -u "$EMAIL:$PASSWORD" 'https://******.*****.**/api/v1/tickets/search?query=state%3A+%28open+OR+new%29' -s

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by YWatchman** [comment]
Somehow after updating the ticket after 54 days, the ticket isn't showing up in the API anymore...

**Comment by MrGeneration** [comment]
Sorry but this rather sounds like a technical questions.
Please note that the better place for technical questions is the Community: https://community.zammad.org

Ensure that you're not hitting any limits per request.

**Comment by YWatchman** [comment]
Not hitting limits, just getting wrong responses.

**Comment by MrGeneration** [comment]
Provide full outputs please, other wise it's impossible to tell if this is wrong usuage or a bug.

**Comment by YWatchman** [comment]
I cannot provide full output as this contains confidential data.

**Comment by YWatchman** [comment]
And after updating the ticket **again**, the ticket isn't showing up anymore. So this might be a simple commit fail that hasn't been catched.
