### ISSUE TITLE
Password strength settings are ignored when creating new customer accounts

### ISSUE THREAD

**Issue by MacroPolo** [zammad/zammad#2907]
### Infos:

* Used Zammad version: 3.2.0-1578664361.375c4929.bionic
* Installation method (source, package, ..): Package (Deb)
* Operating system: Ubuntu 18.04
* Database + version: MySQL 5.7
* Elasticsearch version: ES 7.4.2
* Browser + version: Firefox 68.4.1esr

### Expected behavior:

* Customers should not be able to create accounts which do not comply with the configured password strength requirements.

### Actual behavior:

* Customers can create new accounts using passwords which do not meet the configured password strength settings.

### Steps to reproduce the behavior:

* Navigate to http://zammad.acme.com/#signup
* Chose a weak password in violation of the configured (default) security settings (e.g. `123`)
* Complete the email verification process and sign-in successfully.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MacroPolo** [comment]
Once the user logs in and tries to change their password, the restrictions on length/strength start to apply. The same is true for the password reset process.

**Comment by MrGeneration** [comment]
Hey @MacroPolo ,

thank you very much for your time and effort!
After internal discussions I learned that I tagged this issue incorrectly - below I want to describe why.

----

We currently see this behaviour as a `works as designed`, but understand your viewpoint on this.
Thus, we'll handle this as an enhancement.

When talking about passwords, secure passwords usually are only those passwords that nobody knows - except for the user that's affected. That being said, if your administrator sets the users password (for whatever reason) upon account creation, the password no longer is secure.

Password policies are enforced by Zammad upon changing the password.
The administrator can create user accounts without defining a password. 
This forces the user to reset it which then enforces the policies as expected.

No matter how you create your user, he should at any point reset the password.


---

I hope I could show you how we currently see this issue and why we've decided to tread it as an enhancement.

All the best!

**Comment by MacroPolo** [comment]
Thanks for the details and sorry it has taken me so long to respond about this.

> When talking about passwords, secure passwords usually are only those passwords that nobody knows - except for the user that's affected.

Agreed. However as it currently stands new customers can create Zammad accounts using insecure passwords which are not in compliance with the configured security settings and _without_ requiring any interaction from the Zammad administrator. There is also no step that forces those users to change their password to something which meets the requirements.

This would be a compliance failure for us, so we had to disable new user signups via the web interface. Customers who have emailed in, can use the "password reset" feature which _does_ apply the configured security settings.

In my (limited) view, I still see this as a bug.

**Comment by thorsteneckel** [comment]
Hey @MacroPolo - you are right. I can confirm this. The behaviour you described in your initial comment works around the password policy and therefore is considered a bug. We'll take care of it.
