### ISSUE TITLE
Forwarded attachments not visible in Outlook

### ISSUE THREAD

**Issue by rschueler** [zammad/zammad#2909]
### Infos:

* Used Zammad version: 3.2.0
* Installation method (source, package, ..): docker-compose
* Operating system: debian
* Database + version: 9.6.16

### Expected behavior:

* When forwarding a ticket with attachments to an external customer via email the attachments should be visible in Outlook.

### Actual behavior:

* Attachments are forwarded, but not visible to the customer if Outlook email client is used.

### Steps to reproduce the behavior:

* Load the given sample.eml to Zammad. 
[sample_eml.txt](https://github.com/zammad/zammad/files/4117820/sample_eml.txt)
* Double check: in Zammad there are two attachments (one txt and one image)
![zammad1](https://user-images.githubusercontent.com/3425355/73188748-a3716580-4123-11ea-89e5-108a86235d9a.png)

* Forward this ticket to a external email address with fully quoting the original ticket. Attachments are still there!
![zammad2](https://user-images.githubusercontent.com/3425355/73188539-542b3500-4123-11ea-9050-14465e6b7355.png)

* Open the email with Outlook (Windows Client, OWA or Mobile App) and the image attachment is not visible. It must be there, because the email size is too big for a text only mail. 
![zammad3](https://user-images.githubusercontent.com/3425355/73188538-53929e80-4123-11ea-87fb-d33da0b522fe.png)
Same email looks ok in Gmail.
![zammad4](https://user-images.githubusercontent.com/3425355/73188536-53929e80-4123-11ea-9c70-580c670a8d22.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
@rschueler 

We tried to reproduce it with Outlook365 desktop client and your provided example email. Unfortunately it works :-o

We used the following Outlook client:

![2020-02-05 15_33_30-Window](https://user-images.githubusercontent.com/110226/73851364-a0fec200-482d-11ea-9b0e-a409d2258199.png)
![2020-02-05 15_33_52-Window](https://user-images.githubusercontent.com/110226/73851374-a5c37600-482d-11ea-855f-51099163bb03.png)

The result in outlook of the forwarded email (from Zammad -> Outlook) was/is:

![2020-02-05 15_31_51-Window](https://user-images.githubusercontent.com/110226/73851406-b542bf00-482d-11ea-993d-265fc686a6d9.png)

**So the question: Can you provide the Outlook version screen?**

**Comment by MrGeneration** [comment]
We haven't received further feedback or updates on this topic and thus expect this to be working or solved.

I'll therefor close this issue.
