### ISSUE TITLE
LDAP SSL verification not performed

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#2914]
### Infos:

* Used Zammad version: 3.2.x-develop (2021-05-03)
* Installation method (source, package, ..): zammad-docker-compose, any
* Operating system: Debian 9 GUI-Less, any
* Database + version: Not related to the error.
* Elasticsearch version: Not related to the error.
* Browser + version: Firefox 72.0.2, any
* Ticket#: 1084755

### Expected behavior:

* When configuring LDAP integration against my Active Directory Domain Controller, doesn't matter what kind of SSL verification I choose, the communication with Active Directory is successful. This does not give me confidence, because through all the process I haven't specified the certificates of my CA and subCAs. What I expected was for the communication between Zammad and my Active Directory to fail until I imported my certificates to Zammad's container.

### Actual behavior:

* Doesn't matter what you choose, the communication with my Active Directory is always successful.

### Steps to reproduce the behavior:

* Just try to sync Zammad with a Windows Server 2016 with a Domain Controller role installed and a server certificate signed by a custom subCA signed by a custom CA.

Yes I'm sure this is a bug and no feature request or a general question. Zammad should not be able to communicate with my Domain Controller until I import the public certificates of my custom subCA and CA. The behaviour I'm seeing makes me think of a rollback from LDAPS through port 636 (if the certificate can't be validated) to LDAP through port 389.

**Comment by MrGeneration** [comment]
Sorry for the wait.
I could verify this - this works as long as the certificate and hostname used in the integration does match.

Sidenote: I did not use AD LDS for this, as from above description I expected that this is a "usual" active directory and not LDS. This shouldn't matter though.

Please note that this *might* be partially covered by https://github.com/zammad/zammad/issues/1767 and https://github.com/zammad/zammad/issues/3011
