### ISSUE TITLE
 Technical question

### ISSUE THREAD

**Issue by devpanda0** [zammad/zammad#2915]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): Docker
* Operating system: Debian 10
* Database + version: From Docker Image
* Elasticsearch version: From Docker Image
* Browser + version: From Docker Image

### Question
Hi,
how can I fix this mistake. Everything is configured correctly.

https://prnt.sc/qvru2s

CU
MrVapor

**Comment by MrGeneration** [comment]
Please **do not** post technical questions on this github repository!

The right place for technical questions is the community: https://community.zammad.org

Closing.
