### ISSUE TITLE
Forwarding articles sometimes arrive with another issue's subject

### ISSUE THREAD

**Issue by gohai** [zammad/zammad#2919]
### Infos:

* Used Zammad version: 3.2.0
* Installation method (source, package, ..): package
* Operating system: Amazon Linux 2 (CentOS 7-based)
* Database + version:  PostgreSQL 9.2.24
* Elasticsearch version: 7.4.2
* Browser + version: Chrome 79

### Expected behavior:

* Forwarded article is being sent with the subject of the issue it is being associated with

### Actual behavior:

* Forwarded article is being sent with the subject of a random, unrelated issue

### Steps to reproduce the behavior:

(we can't reproduce this 100%, but we've seen this happen more than once - here are the steps involved in one of those cases)

* create a new ticket addressed to a customer (with some chosen subject A)
* customer replies via email, their response get added to the newly created ticket
* try to forward the customer's reply in the ticket to multiple email addresses

(we've seen this email show up with a completely unrelated subject at times... e.g. our forward for zoom-id `117291`, which happened at `Thursday 17:20`, arrived with the subject line from zoom-id `117593`, created `Thursday 8:53` and last updated `Thursday 17:12`)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Hi @gohai ,

This was possibly fixed along with #2406 . Which is in latest `develop` and `stable` branches, but not released yet.

Did you notice any correlation wether browser session was hard-refreshed between email coming in and forwarding?

**Comment by gohai** [comment]
Thanks for the timely response @mantas. We will wait for the next release to be out and see we see this issue again afterwards. Feel free to close this issue (will open again if needed).

**Comment by mantas** [comment]
Fingers crossed it will stay closed :)
