### ISSUE TITLE
Overviews sometimes not shown to specified Roles or Users

### ISSUE THREAD

**Issue by fleverest** [zammad/zammad#2927]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Create an Overview that is available for some Roles and also some Users.
* I expect to be able to see that Overview if I am:
  (1) a member of any of the Roles, or
  (2) any of the Users.

### Actual behavior:

* You can only see the Overview if you are both a member of a role AND one of the users

### Steps to reproduce the behavior:

* Skipping this step because I know exactly what causes this:

This is the query made in `app/models/ticket/overviews.rb`:
```
Overview.joins(:roles).left_joins(:users).where(
    overviews_roles: { role_id: role_ids }, 
    overviews_users: { user_id: nil }, 
    overviews: overview_filter
).or(Overview.joins(:roles).left_joins(:users).where(
    overviews_roles: { role_id: role_ids },
    overviews_users: { user_id: current_user.id },
    overviews: overview_filter
)).distinct('overview.id').order(:prio, :name)
```

I suggest this instead:

```
Overview.joins(:roles).left_joins(:users).where(
    overviews_roles: { role_id: role_ids }, 
    overviews: overview_filter
).or(Overview.joins(:roles).left_joins(:users).where(
    overviews_users: { user_id: current_user.id },
    overviews: overview_filter
)).distinct('overview.id').order(:prio, :name)
```

This change prevents users specified under `AVAILABLE FOR USER` and members of roles specified under `AVAILABLE FOR ROLE` not being given access to the overview.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
https://github.com/zammad/zammad/issues/2714
