### ISSUE TITLE
dashboard: click on my tickets should open list of those tickets

### ISSUE THREAD

**Issue by ralfhauser** [zammad/zammad#2936]
![image](https://user-images.githubusercontent.com/1681677/74621707-2f344b80-513e-11ea-8a86-62af4d51cfa1.png)

I would be great to be able to click on the yellow / in the red circle and get the list my tickets

**Comment by MrGeneration** [comment]
Sorry but this is a feature requests.
Please do not post feature requests on this Github repository - the Zammad community is the better place for this: https://community.zammad.org .

Thank you for your time. Closing.

**Comment by thorsteneckel** [comment]
Additionally this is a duplicate of #431
