### ISSUE TITLE
omniauth-github: Please use the Authorization HTTP header instead as using the access_token query parameter is deprecated and will be removed July 1st, 2020.

### ISSUE THREAD

**Issue by gionn** [zammad/zammad#2937]
See:
https://community.zammad.org/t/github-login-deprecation-notice-deadline-on-1st-july-2020/3986
https://github.com/omniauth/omniauth-github/issues/89

**Comment by thorsteneckel** [comment]
Hi @gionn - thanks for reporting! Version bump is currently running on our internal CI. This will be part of the upcoming 3.3 release. However, it would be much appreciated if you could use the issue template next time when creating an issue. It makes life so much easier for us.
