### ISSUE TITLE
Zendesk import error

### ISSUE THREAD

**Issue by derbenzi** [zammad/zammad#2941]
Infos:

* Used Zammad version: 3.2.0
* Installation method (source, package, ..): package
* Operating system: ubuntu 18.04 and debian
* Database + version: newest
* Elasticsearch version: newest
* Browser + version: any

### Expected behavior:

* Zendest import works fine

### Actual behavior:

* Zendesk import fails with following red line: `undefined method singularize' for :Groups:Symbol`
![image](https://user-images.githubusercontent.com/61507156/75353251-64157080-58ab-11ea-8165-512f4208e3b3.png)

If manual import start over rails shows: 
```
irb(main):058:0> Import::Zendesk.start_bg
Traceback (most recent call last):
        1: from (irb):58
NoMethodError (undefined method `start_bg' for Import::Zendesk:Class)
```

here a snip of the production.log:

> I, [2020-02-26T09:58:10.656148 #1212-47448722360140]  INFO -- : Started POST "/api/v1/import/zendesk/import_start" for 192.10.52.127 at 2020-02-26 09:58:10 +0000
I, [2020-02-26T09:58:10.666182 #1212-47448722360140]  INFO -- : Processing by ImportZendeskController#import_start as JSON
I, [2020-02-26T09:58:10.828836 #1212-47448722360140]  INFO -- : Setting.set('import_mode', true)
I, [2020-02-26T09:58:10.840212 #1212-47448722360140]  INFO -- : Setting.set('import_backend', "zendesk")
I, [2020-02-26T09:58:10.879323 #1212-47448722360140]  INFO -- : Completed 200 OK in 213ms (Views: 0.2ms | ActiveRecord: 28.0ms)
I, [2020-02-26T09:58:11.772136 #1318-47182959988940]  INFO -- : 2020-02-26T09:58:11+0000: [Worker(host:muppticket pid:1318)] Job ImportJob#start (id=3) RUNNING
E, [2020-02-26T09:58:11.812843 #1318-47182959988940] ERROR -- : ImportJob 'Import::Zendesk' failed: undefined method `singularize' for :Groups:Symbol
E, [2020-02-26T09:58:11.812911 #1318-47182959988940] ERROR -- : undefined method `singularize' for :Groups:Symbol (NoMethodError)
/opt/zammad/lib/sequencer/unit/import/zendesk/objects_total_count.rb:28:in `request'
/opt/zammad/lib/sequencer/unit/import/zendesk/objects_total_count.rb:15:in `block in statistics_diff'
/opt/zammad/lib/sequencer/unit/import/zendesk/objects_total_count.rb:13:in `each'
/opt/zammad/lib/sequencer/unit/import/zendesk/objects_total_count.rb:13:in `each_with_object'
/opt/zammad/lib/sequencer/unit/import/zendesk/objects_total_count.rb:13:in `statistics_diff'
/opt/zammad/lib/sequencer/unit/common/provider/attribute.rb:27:in `value'
/opt/zammad/lib/sequencer/unit/common/provider/attribute.rb:32:in `ignore?'
/opt/zammad/lib/sequencer/unit/common/provider/attribute.rb:8:in `process'
/opt/zammad/lib/sequencer/unit/base.rb:202:in `process'
/opt/zammad/lib/sequencer.rb:77:in `block (4 levels) in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:76:in `block (3 levels) in process'
/opt/zammad/lib/sequencer/state.rb:150:in `process'
/opt/zammad/lib/sequencer.rb:74:in `block (2 levels) in process'
/opt/zammad/lib/sequencer/units.rb:29:in `block in each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer/units.rb:28:in `each'
/opt/zammad/lib/sequencer.rb:72:in `each_with_index'
/opt/zammad/lib/sequencer.rb:72:in `block in process'
/opt/zammad/lib/mixin/start_finish_logger.rb:7:in `log_start_finish'
/opt/zammad/lib/sequencer.rb:70:in `process'
/opt/zammad/lib/sequencer.rb:25:in `process'
/opt/zammad/lib/import/mixin/sequence.rb:15:in `process'
/opt/zammad/lib/import/zendesk.rb:8:in `start'
/opt/zammad/app/models/import_job.rb:24:in `start'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/performable_method.rb:26:in `perform'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:66:in `execute'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/backend/base.rb:78:in `invoke_job'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:230:in `block in run'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:229:in `run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:66:in `execute'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:213:in `block in work_off'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:212:in `times'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.7/lib/delayed/worker.rb:212:in `work_off'
/opt/zammad/app/models/scheduler.rb:372:in `block (3 levels) in worker'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/opt/zammad/app/models/scheduler.rb:370:in `block (2 levels) in worker'
/opt/zammad/app/models/scheduler.rb:366:in `loop'
/opt/zammad/app/models/scheduler.rb:366:in `block in worker'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2020-02-26T09:58:11.824861 #1318-47182959988940]  INFO -- : 2020-02-26T09:58:11+0000: [Worker(host:muppticket pid:1318)] Job ImportJob#start (id=3) COMPLETED after 0.0526
I, [2020-02-26T09:58:13.901210 #1212-47448722307980]  INFO -- : Started GET "/api/v1/import/zendesk/import_status?_=1582711051359" for 192.10.52.127 at 2020-02-26 09:58:13 +0000
I, [2020-02-26T09:58:13.905664 #1212-47448722307980]  INFO -- : Processing by ImportZendeskController#import_status as JSON
I, [2020-02-26T09:58:13.905729 #1212-47448722307980]  INFO -- :   Parameters: {"_"=>"1582711051359"}
I, [2020-02-26T09:58:13.926527 #1212-47448722307980]  INFO -- : Completed 200 OK in 21ms (Views: 0.3ms | ActiveRecord: 1.0ms)
I, [2020-02-26T09:58:16.017528 #1318-47182974034540]  INFO -- : execute Chat.cleanup (try_count 0)...
I, [2020-02-26T09:58:16.024251 #1318-47182974034540]  INFO -- : ended Chat.cleanup took: 0.044570535 seconds.
I, [2020-02-26T09:58:18.957504 #1212-47448747973740]  INFO -- : Started GET "/api/v1/import/zendesk/import_status?_=1582711051360" for 192.10.52.127 at 2020-02-26 09:58:18 +0000
I, [2020-02-26T09:58:18.966559 #1212-47448747973740]  INFO -- : Processing by ImportZendeskController#import_status as JSON
I, [2020-02-26T09:58:18.966777 #1212-47448747973740]  INFO -- :   Parameters: {"_"=>"1582711051360"}
I, [2020-02-26T09:58:19.136821 #1212-47448747973740]  INFO -- : Completed 200 OK in 169ms (Views: 0.3ms | ActiveRecord: 2.2ms)

### Steps to reproduce the behavior:

* Install an fresh Zammad on ubuntu 18.04. and do an import over the browser migration tool (beta) with the zendesk API credentials 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by derbenzi** [comment]
Hey @mantas ,
how are you? Do you have any updates to this issue?
Do you still need my Zendesk API access?

Greets

**Comment by MrGeneration** [comment]
Smells like a dupolicate of https://github.com/zammad/zammad/issues/2941

**Comment by mantas** [comment]
Hi @derbenzi ,

The fix is in our QA queue at the moment and should be included in next release.

Feel free to revoke that API token. Thank you for helping us!

P.S. @MrGeneration this is #2941 :)

**Comment by saada** [comment]
When is the next release planned?

**Comment by MrGeneration** [comment]
Coming when it's ready. Sorry, but we can't tell you ETAs.
Please don't push issues like that.
