### ISSUE TITLE
Attachments get lost on forward in specific conditions

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2942]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Google Chrome and Firefox on latest versions
* Ticket-ID: #1062763, #1075897 

This issue appears on hosted and on premise setups.

### Expected behavior:

You do not loose any attachments upon forwarding mails.

### Actual behavior:

When forwarding mails, Zammad does show you attachments of the forwarded articles in the draft mode, but as soon as you submit the article, it will remove these attachments which is unexpected.

---

As this behaviour some times is a bit hard to reproduce, the customer and I collected use cases that help to reproduce this issue. Further below you can also find working examples (to cross test this).

We hope that this helps to pin down the issue better.

#### 1.1 forwarding with extra step

* Agent creates a ticket
* Agent forwarded the first article to the customer
* Customer replies to that mail - the mail contains an attachment
* Agent create a forward draft (types in the recipient and some text)
* Agent changes into another ticket, write a draft but doesn't submit it
* Agent changes back into the other ticket and submits the forward draft
  
  ==> The Mail being forwarded does not contain any attachments

#### 1.2 direct forwarding without any special moves

* Agent creates a ticket
* Agent forwards the first ticket article to the customer
* Customer answers on that mail - this mail contains an attachment
* Agent forwards this mail to a third party
  
  ==> The mail being forwarded no longer contains any attachments

#### 1.3 

* Customer creates a ticket via incoming mail (no attachment)
* Agent answers on that mail and requests any attachment
* Customer replies on that mail and provides a attachment attached
* Agent create a forward draft and types in recipient and text
* Agent changes into another ticket and creates a draft there (and types some stuff)
* Agent changes back into the affected ticket and submits the forwards
  
  ==> The mail being forwarded no longer contains any attachments

Yes I'm sure this is a bug and no feature request or a general question.

### Working examples (just for reference and just in case....)

```
2.1. creating ticket with attachment

- Agent creates ticket with attachment
- Agent forwards the first article to anybody
  
  ==> Attachment is being forwarded

2.2 creating phone notes with attachment

* Agent creates a ticket
* Agent adds a phone note with attachment to the ticket
* agent forwards this phone note to any body

  ==> Attachment is being forwarded

2.3 customer creates not within web interface

* Agent creates a ticket
* Customer loggs into Zammad and creates a web article with attachment
* Agent forwards this phone note to any body

  ==> Attachment is being forwarded

2.4 customer sents a mail

* Agent sents a mail with attachment
* Agent forwards this mail to a third party

==> Attachment is being forwarded
```

**Comment by mantas** [comment]
@MrGeneration did you try this on `develop` branch? This is the same area as that `To:` issue we recently fixed.

**Comment by MrGeneration** [comment]
Ugh, sorry for the long wait. By now I checked it like three times but my drafts were lost. 🙈 

Anyway, I still can reproduce all 3 earlier failing use cases.
Please note that this might be due to the "notification bird" as I did use it once. In between the use cases I did not reload the web app in any way.

use case 1.1: ⛔ 
use case 1.2: ⛔ 
use case 1.3: ⛔

**Comment by MrGeneration** [comment]
Sorry for the wait. 🙈
Here are your screencasts from a develop instance:

use case 1.1:
![issue2942_sample1-1](https://user-images.githubusercontent.com/6549061/93577578-82a09d80-f99c-11ea-824e-7034cd0cb5ca.gif)

use case 1.2: 
![issue2942_sample1-2](https://user-images.githubusercontent.com/6549061/93577620-8df3c900-f99c-11ea-993c-02b0d5b5c55d.gif)

use case 1.3:
![issue2942_sample1-3](https://user-images.githubusercontent.com/6549061/93577815-cc898380-f99c-11ea-8c3b-c218403b5d7c.gif)
