### ISSUE TITLE
Raise default password security for new instances

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2943]
### Infos:

* Used Zammad version: 3.2.0 (all versions until addressed)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### wanted approach:

We should raise our default password policy for *new instances*. This will raise the product security for users and will thus get closer to password best practises. Administrators will still be able to lower these default settings as needed.

To ensure we're not breaking existing installations, we should only do this on new installations.

### current state:

The current default password policies states this:
* maximum failed logins: 10
* 2 lower and 2 upper characters are **not required**
* minimum password length: 6
* digit **is required**

### Desired change:

I'd like to suggest to change the above default values to:q
* maximum failed logins: 5  [to reduce password brute forcing and thus lock accounts earlier]
* 2 lower and upper characters **should be required**
* minimum password length: 10
* Digit **is required**
* (new) we should add a option to enforce special characters

This will adapt to current best practises of passwords. It's not perfect, but an important step into the right direction. I've used the following references for those best practises:
* https://docs.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide
* https://smallbiztrends.com/2019/01/password-best-practices.html
* https://www.beyondtrust.com/blog/entry/top-15-password-management-best-practices

---

#### out of scope of this issue

There are some topics left that slightly affect this issue, but are not directly fitting or mandatory.

This especially hits issue https://github.com/zammad/zammad/issues/2907 which will raise security further by enforcing strong passwords upon creation.

Also, this affects issue https://github.com/zammad/zammad/issues/965 which would add 2 factory authentication which would raise security even further.

Last but not least, we should at least think about having some kind of password blacklist.
Because above changes (no matter if linked issue or this direct one) will not save you from passwords like `P@ssword` or `ChangeMe123`.

**Comment by thorsteneckel** [comment]
Implemented with the commit above 👏  closing.
