### ISSUE TITLE
Search for E-Mail Address with existing Tickets

### ISSUE THREAD

**Issue by gemafra** [zammad/zammad#2946]
Searching for Existing E-Mail / Users when adding Cc or To E-Mail Fields with existing Tickets

* Used Zammad version: 3.2.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: postgresql 9.5.19
* Elasticsearch version: 5.6.16
* Browser + version: 73.0.1

### Actual behavior:

Search over URL Triggers Network Traffic / API Call

https:/zammad/api/v1/users/search?term=flor

with an Empty Response. -> []

The User I did search for does Exists.

### Expected behavior:

Searching within a new Ticket creates a different API Call eg.

https://zammad/api/v1/search/user-organization?query=flor&_=1583167515077

which returns a json with resprective users / organizations

### Steps to reproduce the behavior:

Change the To or Cc E-Mail Address on an existing Ticket.

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question.
Please do not post technical questions on this repository, as we prefer to seperate them to the Community.

Please create a post over at the community (https://community.zammad.org).
If this proves to be a bug, I'll gladly reopen this issue and tag it accordingly.

**Comment by saz** [comment]
@MrGeneration We're seeing the same issue since version 3.3.0.

For new tickets, all is working as before, but for existing tickets, nothing will be suggested.

I can also confirm the different endpoints used for searching as it is mentioned in the initial message.

**Comment by MrGeneration** [comment]
I cannot reproduce this behaviour.
Please use this community thread for discussion: https://community.zammad.org/t/search-for-users-e-mail-add-returns-empty-json-on-existing-tickets/4133


If this turns out to be a bug I just don't understand yet, I'll gladly reopen this issue.
Right now, as already stated, I can't reproduce it.
