### ISSUE TITLE
API token is ignored for KnowledgeBase calls

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#2948]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1069585

### Expected behavior:

* Allow to access KB endpoints with HTTP tokens

### Actual behavior:

* Throws `Not authorized` error

### Steps to reproduce the behavior:

`curl -H "Authorization: Token token=SPjt5NHXbwLJrwRF0DdBGVkDxQ-9lQsaSiQbFklBG4QbZZLFwCaPwS-FnvwbQPbW" http://localhost:3000/api/v1/knowledge_bases/manage/init`

`curl -H "Authorization: Token token=SPjt5NHXbwLJrwRF0DdBGVkDxQ-9lQsaSiQbFklBG4QbZZLFwCaPwS-FnvwbQPbW" http://localhost:3000/api/v1/knowledge_bases/init`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Closing as no longer relevant. Accidentally fixed by another commit.

**Comment by MrGeneration** [comment]
Hey Mantas,

can you please tell me which commit you were talking about?
It's not clear in which version this is / will be fixed to me right now. :x

Thanks!

**Comment by mantas** [comment]
I never checked which commit fixed it :( Since 3.3 came out on March 3rd, this is fixed in 3.4.
