### ISSUE TITLE
Add BCC to Email-Ticket

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#295]
Sometimes we like to inform a person about an answer without knowlege of customer. So it would be nice, if we could send it by bcc. Both customer and the person have no access to Zammad.

**Comment by thorsteneckel** [comment]
Hey there! We still think that BCC is only a workaround for many use cases and should be avoided. We haven't seen a use case yet that shouldn't be solved in a different way. Therefore I'll lock this issue. Please let us know your use case over at the [community board](http://community.zammad.org/) in a dedicated thread or re-use [the existing thread](https://community.zammad.org/t/bcc-for-outgoing-emails/3289). Attention: Please make sure to use  the search before creating a new thread, we might already have a solution for your use case.
