### ISSUE TITLE
Zammad fails to properly decode an improperly RFC2047-encoded Subject

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#2953]
### Infos:

* Used Zammad version: 3.2.x
* Installation method (source, package, ..): docker-compose
* Operating system: Debian 10.3
* Database + version: postgres 9.6.16 from docker-compose
* Elasticsearch version: 5.6.14 from docker-compose
* Browser + version: Chrome 80

### Expected behavior:

* Zammad should decode the following `Subject` to `Subject: didacta 2020 wird verschoben -  Behörden verfügen Veranstaltungsverbot für Bildungsmesse im März`:

	```
	Subject: =?utf-8?B?ZGlkYWN0YSAyMDIwIHdpcmQgdmVyc2Nob2JlbiAtICBCZWjD?=
	 =?utf-8?B?tnJkZW4gdmVyZsO8Z2VuIFZlcmFuc3RhbHR1bmdzdmVyYm90IGbDvHIg?=
	 =?utf-8?B?QmlsZHVuZ3NtZXNzZSBpbSBNw6Ryeg==?=
	 ```

	(Not sure which email client has committed this crime against RFC2047 as it didn't include an `X-Mailer` header, but I bet it's Outlook.)

### Actual behavior:

* Zammad decodes the `Subject` to `didacta 2020 wird verschoben - Beh��rden verfügen Veranstaltungsverbot für Bildungsmesse im März`

### Steps to reproduce the behavior:

* Send a mail with the `Subject` as above to Zammad.

### Background information

To be absolutely honest, this isn't really a bug in Zammad; it took me a while to figure out, but the `Subject` as shown above actually violates RFC2047. While the subject correctly encodes the `ö` as `0xc3b6`, the UTF-8 bytes are split between two encoded-words:

```
martin@dogmeat ~ % echo 'ZGlkYWN0YSAyMDIwIHdpcmQgdmVyc2Nob2JlbiAtICBCZWjD' | base64 -d | xxd
00000000: 6469 6461 6374 6120 3230 3230 2077 6972  didacta 2020 wir
00000010: 6420 7665 7273 6368 6f62 656e 202d 2020  d verschoben -  
00000020: 4265 68c3                                Beh.
martin@dogmeat ~ % echo 'tnJkZW4gdmVyZsO8Z2VuIFZlcmFuc3RhbHR1bmdzdmVyYm90IGbDvHIg' | base64 -d | xxd
00000000: b672 6465 6e20 7665 7266 c3bc 6765 6e20  .rden verf..gen 
00000010: 5665 7261 6e73 7461 6c74 756e 6773 7665  Veranstaltungsve
00000020: 7262 6f74 2066 c3bc 7220                 rbot f..r 
```

[RFC2047](https://tools.ietf.org/html/rfc2047) doesn't allow this:

```
   The 'encoded-text' in an 'encoded-word' must be self-contained;
   'encoded-text' MUST NOT be continued from one 'encoded-word' to
   another.  This implies that the 'encoded-text' portion of a "B"
   'encoded-word' will be a multiple of 4 characters long; for a "Q"
   'encoded-word', any "=" character that appears in the 'encoded-text'
   portion will be followed by two hexadecimal characters.

   Each 'encoded-word' MUST encode an integral number of octets.  The
   'encoded-text' in each 'encoded-word' must be well-formed according
   to the encoding specified; the 'encoded-text' may not be continued in
   the next 'encoded-word'.  (For example, "=?charset?Q?=?=
   =?charset?Q?AB?=" would be illegal, because the two hex digits "AB"
   must follow the "=" in the same 'encoded-word'.)

   Each 'encoded-word' MUST represent an integral number of characters.
   A multi-octet character may not be split across adjacent 'encoded-
   word's.
```

This seems to be handled differently by different implementations. While Zammad (Ruby) and https://dogmamix.com/MimeHeadersDecoder/ (ASP.NET) won't decode it, Perl's `Encode::MIME::Header` will.

In the spirit of "be conservative in what you do, be liberal in what you accept from others" I hope this is nonetheless acceptable as a bug report, as the technical details are probably unclear and irrelevant to affected end-users :)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Just a small sidenote on those kind of subjects.
Beside me not loking them at all we already saw how differently different mail server solutions can react with utf-8 stuff.

While some remove incorrect subject encodings for IMAP listings (as an example), others won't.

**Comment by dominikklein** [comment]
For now, we will not touch this, because we didn't receive the problem again in the last three years.
