### ISSUE TITLE
Content Security Policy blocks embedded KnowledgeBase videos

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2954]
### Infos:

*This is a follow up on issue #2713*

* Used Zammad version: 3.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1070146 

### Expected behavior:

You can embedd videos within knowledgebase entries without issues.

### Actual behavior:

When using the embedd function for youtube and vimeo, after saving the answer, you'll actually won't see the videos. Instead, Browsers will show that this has been blocked by addons / settings.

Reasons for this is content security policies that are blocking iframes for youtube and vimeo.

### Solution:

Add `policy.frame_src   'www.youtube.com', 'player.vimeo.com'` to `/opt/zammad/config/initializers/content_security_policy.rb` below line 37.

### Steps to reproduce the behavior:

* add a new answer with vimeo and youtube videos 
  

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
@thorsteneckel MR 1036 is already waiting for your review

**Comment by thorsteneckel** [comment]
Fixed with the two commits above 🚀 Thanks @mantas and @MrGeneration !

**Comment by niklaskorz** [comment]
Sorry, for hijacking this issue, but is there any possibility to adjust the setting introduced by d9a10b2a9af348ad7071c31279d4c6023d4bd3b2 from within an extension (i.e., the currently undocumented zammad packages)? We'd be interested in adding support for our video platform to zammad. Alternatively, if this is not possible, is there any chance a pull request that directly adds support for our video platform to zammad (through the `embed_video_button`) would be merged?

**Comment by MrGeneration** [comment]
Please don't hijack closed issues. As this is rather a technical / development question, please create a thread on the community: https://community.zammad.org

**Comment by niklaskorz** [comment]
@MrGeneration I already suspected you would say that, so sorry for that :) I have created a forum post.
