### ISSUE TITLE
Helpdesk stays blank

### ISSUE THREAD

**Issue by seedlord** [zammad/zammad#296]
Hello

I installed ZAMMAD for testing purposes on Ubuntu 16.04 Live. I used a Dell Laptop - Latidude E6530.

Installation worked flawlessly.
But when I open 127.0.0.1:3000 or localhost:3000 i get a blank page with the text "Loading..." and nothing happens anymore. I used Mozilla Firefox and Brave Browser.
This is the sourcecode of the page: 
[pastebin](http://pastebin.com/9YLiscKu)

Did I do something wrong? Does ZAMMAD not work in a Live Distribution? What can I do, to get it working? Sorry for my bad english

**Comment by martini** [comment]
Did you set

`export RAILS_SERVE_STATIC_FILES=true`

before starting "rails s"?

See also: https://zammad.org/documentation/install/install-source Background: If you use production without reverse proxy, you need to tell rails so server static assets too.

**Comment by seedlord** [comment]
No, I followed README_Install_Ubuntu.md and it didn't tell me to set 
`export RAILS_SERVE_STATIC_FILES=true`

so I set the export and restart rails?

**Comment by martini** [comment]
Yes. Feedback is welcome!

**Comment by seedlord** [comment]
Thank you very much for you help. I managed to get it working =)

I didn't understand how to stop the actual rails server, so i renamed the server.pid file in opt/zammad/tmp/pids/server.pid and startet a new server. I am able to get in now. 

Thanks again =)

**Comment by seedlord** [comment]
Hello, 
I have the next problem. Now when i try to connect to ZAMMAD from another Device in the network, I am getting the blank "Loading..." Screen. On the localhost it works fine. How can I fix that?

**Comment by martini** [comment]
@seedlord any feedback, what the problem was?

**Comment by seedlord** [comment]
My Zammad path is '/opt/zammad/zammad/public' but in '/etc/nginx/sites-available/zammad.conf' it was set to '/opt/zammad/public' so the blank Loading... screen appeared. After correcting it, it worked.

**Comment by martini** [comment]
Thanks!
