### ISSUE TITLE
Ticket removal of merged / linked tickets doesn't remove references

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2960]
### Infos:

* Used Zammad version: 3.3 and earlier 
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any (this affects all Browsers and thus is not Browser specific)
* Ticket-ID: #1068022

### Expected behavior:

When removing tickets, no matter if you linked or merged them into another ticket, will also remove existing references in tickets that have been linked to the affected ticket.

### Actual behavior:

When removing a ticket with references in the history of another ticket, you can no longer use the ticket history of the left over linked ticket. When clicking on history, you'll not receive any error message and it just looks like Zammad won't load the history objects.

When having a look inside developers console however you'll see this:
![image](https://user-images.githubusercontent.com/6549061/76192748-da3aa100-61e2-11ea-9803-70fdfa4e7c7d.png)

affected lines:
![image](https://user-images.githubusercontent.com/6549061/76192761-e1fa4580-61e2-11ea-9657-1cf7f3c46d1d.png)

### Steps to reproduce the behavior:

* create two tickets
* merge them together
* setup a scheduler to remove all tickets with "merged" state
* wait for the scheduler to run
* go to your leftover ticket and try to open the history

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Code snippet for cleaning up databases affected by this issue:

```ruby
History.where(history_type: History::Type.find_by(name: 'received_merge')).pluck(:id_from).then { |ticket_ids| ticket_ids - Ticket.where(id: ticket_ids).pluck(:id) }.tap { |deleted_ids| Ticket.where(id: deleted_ids).destroy_all }
History.where(history_type: History::Type.find_by(name: 'merged_into')).pluck(:id_to).then { |ticket_ids| ticket_ids - Ticket.where(id: ticket_ids).pluck(:id) }.tap { |deleted_ids| Ticket.where(id: deleted_ids).destroy_all }
```
