### ISSUE TITLE
LDAP don't sync 3 specific agents

### ISSUE THREAD

**Issue by ArcheNoah77** [zammad/zammad#2961]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..) DEB
* Operating system: Debian 9
* Database + version:
* Elasticsearch version:
* Browser + version: 

### Expected behavior:

LDAP Sync works

### Actual behavior:

LDAP sync dont work correctly

### Steps to reproduce the behavior:
 I changed the ldap server (just another dc in the same domain). After that 3 of 7 Agents are gone. The user are not in agents (but are in the AD-Group) and not in "User".

When i change the ldap settings, the preview shows me "3 new agents". I click "Save configuration" and the sync will start. But the 3 agents are not synced. If i took them out of the AD-Group, normally they have to be synced as users. But this dont work either. It's only the 3 specific users, who dont be synced. All other works fine.

Already did "zammad run rake searchindex:rebuild"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry but that sounds like a technical question.
If you change your ldap server and suddendly Zammad does synchronize less users, this sounds like a server issue.

Please consult the community of Zammad over at https://community.zammad.org

If this proves to be a software bug of Zammad, I'll gladly reopen this issue!
Please don't forget to reference this issue, this will help us to find the correct issue in case of cases.


Also, when opening a thread at the community, please fill in the whole template and don't leave out information. Thanks!
