### ISSUE TITLE
Facebook integration updated documentation.

### ISSUE THREAD

**Issue by Rafiqgithub** [zammad/zammad#2969]
Hi, Can you please provide us the updated documentation for Facebook?
If there is no updated doc any alternative solutions to connect Facebook?

**Comment by MrGeneration** [comment]
Sorry but this is a technical questions - please *do not* post technical questions on this github repository. We do have this on our list (see: https://github.com/zammad/zammad-admin-documentation/issues/2 ) but will need more time to update this.

ETA currently unknown.
Closing now.
