### ISSUE TITLE
chat style broken

### ISSUE THREAD

**Issue by wagnst** [zammad/zammad#297]
![unbenannt](https://cloud.githubusercontent.com/assets/7312523/19687731/e72814a6-9ac6-11e6-9444-bc105f727d00.png)

**Comment by mrflix** [comment]
Hey Steffen. What's the browser and the version?

**Comment by wagnst** [comment]
@mrflix im using arch linux with Firefox 49.0.2

**Comment by mrflix** [comment]
Can't reproduce it in – neither in Firefox 49.0.1 nor Firefox Nightly 52 on Mac OS.
Is it already broken before there are any messages?

**Comment by wagnst** [comment]
its not broken when the supporter has not opened the chat. It looks like

![waiting](https://cloud.githubusercontent.com/assets/7312523/19691062/2943fa06-9ad3-11e6-83b3-42613270642d.png)

once there is one message it looks like

![answer](https://cloud.githubusercontent.com/assets/7312523/19691067/2dc77d46-9ad3-11e6-9c07-133b755bc9cd.png)

and if there are multiple messages, then the header dissappears.
I have turned off all Ad Blockers and NoScript - same effect

**Comment by wagnst** [comment]
just checked Chromium. Same thing happens there.

**Comment by wagnst** [comment]
sorry my fault, wrong css in the `title:` parameter used  :-/

**Comment by mrflix** [comment]
Solved in live chat with Steffen :)

**Comment by martini** [comment]
Great to hear! ❤️
