### ISSUE TITLE
Italian translation error.

### ISSUE THREAD

**Issue by enryxgit** [zammad/zammad#2972]
### Infos:

* Used Zammad version: 3.3.0
* Installation method (source, package, ..): Centos 7 yum
* Operating system: Centos 7 v7.7.1908
* Database + version: PostgreSQL v9.2.24
* Elasticsearch version: 5.6.16
* Browser + version: Google Chrome for Windows v79.0.3945.88

### Expected behavior:

* Translate italian word biglietto = ticket
* Translate italian word Biglietto = Ticket
File 1: opt/zammad/app/views/mailer/ticket_reminder_reached/it.html.erb
File 2: opt/zammad/app/views/mailer/ticket_update/it.html.erb

### Actual behavior:

* Wrong word biglietto

### Steps to reproduce the behavior:

* Try to create a ticket with italian language.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by enryxgit** [comment]
File 1: opt/zammad/app/views/mailer/ticket_reminder_reached/it.html.erb
File 2: opt/zammad/app/views/mailer/ticket_update/it.html.erb

Please translate:

biglietto = ticket (right translation)

Biglietto = Ticket (right translation)

Thank you.

**Comment by MrGeneration** [comment]
Please fix the issue template in your first article, otherwise I'll have to close this issue as technical question.

The requested information are mandatory.

Thank you.

**Comment by enryxgit** [comment]
Just do it, thank you.

**Comment by dominikklein** [comment]
This was already fixed with the commit: b3b7a84683f22c72f04f32a0eb4c1c8c4eaf4eff.
