### ISSUE TITLE
RPM upgrade fails with no css or js files, assets:precompile fails

### ISSUE THREAD

**Issue by lpar** [zammad/zammad#2975]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): RPM from repository
* Operating system: CentOS 7
* Database + version: PostgreSQL 9.2
* Elasticsearch version: 5.6.16
* Browser + version: Google Chrome 80.0.3987.132

### Expected behavior:

* Routine upgrade to 3.3

### Actual behavior:

 * After upgrade, no js files or css files were found, attempting to access the web site gave 404 errors for them, and the UI failed to load.
 * As per #1731, attempted to run `zammad run rake assets:precompile`, but that gave an error:

```
# zammad run rake assets:precompile
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
```

 * Started following instructions on the Yarn site, but it recommends an out of date version of Node.
 * Added Node 12 and Yarn repos, installed both, was then able to run `zammad run rake assets:precompile`.

It seems bad to me that a Ruby on Rails application should require a Node and Yarn development setup.

### Steps to reproduce the behavior:

* Upgrade to 3.3 on a system without Yarn installed.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
The Yarn message is a warning, not an error.
Your assets should still compile like expected.

This is a technical question - if you still have issues with your installation, please create a topic over at the community: https://community.zammad.org

If we prove me to be wrong and this to be a bug, I'll gladly reopen this issue! :)

Thanks for your time.

**Comment by lpar** [comment]
It didn't work until I installed Yarn and Node. I had no assets, I even used `find` to search for .css files in the /opt/zammad tree.
