### ISSUE TITLE
Security issue in 3.3.0

### ISSUE THREAD

**Issue by bengels00** [zammad/zammad#2978]
### Infos:

* Used Zammad version: 3.3.0
* Installation method (source, package, ..): Ubuntu package
* Operating system: Ubuntu 18.04
* Database + version: MySQL 5.7
* Elasticsearch version: 7.6.1
* Browser + version: any

 ** Please provide security contact**

### Expected behavior:

* --

### Actual behavior:

* -- 

### Steps to reproduce the behavior:

* --

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please use security [at] zammad [dot] com for security related notifications.
Thank you very much for choosing to report those issues responsible!
