### ISSUE TITLE
trigger "set to public" requested

### ISSUE THREAD

**Issue by wagnst** [zammad/zammad#298]
I need a trigger, which can listen on an answer status regarding "internal" or "public".
Background is, that notifications via mails shall only be send, if the ticket answer is "public" (can also be a note).

**Comment by martini** [comment]
Who should be the recipient of the notifications?

**Comment by wagnst** [comment]
The customer. 
If you add a text (e.g. a note) to the ticket, i would like to notify the customer via mail through a trigger (which works), but this should only happen, if the note is "public". Currently the notification is also send, if it is marked as internal.

**Comment by jschurse** [comment]
+1
we have the same problem.
Either our customers get all internal communication we save to tickets, or they do not receive any updates at all. Is there a possible workaround known to anyone?

**Comment by AdiosOnline** [comment]
+1
we also searched for that one. Only Public notes, should reach the customer by Mail.

**Comment by martini** [comment]
Hi,

it got implemented/fixed with other trigger issues (and related issue like #779, #386, #395). It's available in master branch/packages (will get in stable ASAP).

 -Martin

**Comment by martini** [comment]
Available in stable branch/packages.
