### ISSUE TITLE
Article Notes added via Macro are not HTML formatted

### ISSUE THREAD

**Issue by fleverest** [zammad/zammad#2980]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): Docker-Compose
* Operating system: ubuntu
* Database + version: Docker-Compose
* Elasticsearch version: Docker-Compose
* Browser + version: Docker-Compose
* Ticket-ID: #1078230, #1081308, ~~#10102804~~

### Expected behavior:

*Macros that have "article.note" in their perform method should, when triggered, add an article that is correctly formatted

### Actual behavior:

* 
![image](https://user-images.githubusercontent.com/41366210/77282018-e06d6900-6d1c-11ea-95af-17bcb6d0823b.png)

### Steps to reproduce the behavior:

* Create the following macro:
![image](https://user-images.githubusercontent.com/41366210/77282280-95078a80-6d1d-11ea-82ea-3023c2fe3d23.png)

* execute macro on ticket.

### ADDITIONAL INFO:

By the following Rails Console command:
`Ticket::Article.where(ticket_id: 1).first`

I can see that `content_type: 'text/plain'`. This is clearly incorrect, so I investigated further.

If the article form is non-empty when you run the macro, the macro executes as intended. I have investigated and I conclude that this is to do with the following code, inside the `submit` method in 'app/models/ticket_zoom.coffee':

https://github.com/zammad/zammad/blob/0004c72624c113f9a3622afe46528d552a79dbe9/app/assets/javascripts/app/controllers/ticket_zoom.coffee#L770-L800

Here you can see that articleParams is defined as the parameters of `articleNew`, which is defined here:
https://github.com/zammad/zammad/blob/0004c72624c113f9a3622afe46528d552a79dbe9/app/assets/javascripts/app/controllers/ticket_zoom.coffee#L448-L459

As you can see,  we have `defaults: @taskGet('article')`. When passed to the `.params()` method defined here:
https://github.com/zammad/zammad/blob/eabc9242300becfac8d69e650c01677c108f509e/app/assets/javascripts/app/controllers/ticket_zoom/article_new.coffee#L254-L261

it sets `params = @formParam( @$('.article-add') )`, and will only set `content_type = 'text/html'` if `params.body` is not null. BUT, since we have not written anything in the article form when we execute the macro - it is null! We can check the value of `@formParam(@$('.article-add'))` by running the following command in the browser console:
![image](https://user-images.githubusercontent.com/41366210/77282719-d0ef1f80-6d1e-11ea-87c7-c7edab08e4a8.png)

Since the `body` field is `null`, it seems the `content_type` attribute is defaulted to `'text/plain'`, and hence the article is not correctly formatted. One fix to this would be to change the default field for the `@articleNew` method in ticket_zoom.coffee, or to change the `params` method in 'ticket_zoom/article_new.coffee'. Alternatively, a very fast and safe patch would be to check whether or not the `type` is 'note' in the `App.Ticket.macro` method:
https://github.com/zammad/zammad/blob/eabc9242300becfac8d69e650c01677c108f509e/app/assets/javascripts/app/models/ticket.coffee#L147-L154

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Madko** [comment]
Still here in 3.4, and that's why we can't use macros

Best regards,
Edouard

**Comment by MrGeneration** [comment]
This still needs verification. Sorry for the delay, but I'm locking the conversation to contributors only.
This is to reduce the noise and help us focus on the issues without bumps.

**Comment by MrGeneration** [comment]
I'm afraid using formatting (like strong text) doesn't workaround this issue. :-/
