### ISSUE TITLE
LDAP Import: An error occurred: undefined method `ord' for nil:NilClass

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#2984]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): Official Zammad Docker-compose
* Operating system: Debian 9
* Database + version: Official Zammad Docker-compose
* Elasticsearch version: Official Zammad Docker-compose
* Browser + version: Chrome 80.0.3987.149

### Expected behavior:

Successful LDAP Import without errors like in our other zammad docker instance (zammad version 3.2). 

### Actual behavior:

Setup LDAP Integration works fine but after that the sync produce the following error:
An error occurred: undefined method `ord' for nil:NilClass

Our Ldap settings are correct and verified with LDAP Browser and our second zammad instance (version 3.2). We sync only 180 users. But even with the error the sync works fine. New Users will be added to the system but the warning confuses.

### Steps to reproduce the behavior:

Restart LDAP Sync

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please provide the complete traceback of the mentioned error message.

**Comment by ghost** [comment]
> Please provide the complete traceback of the mentioned error message.

How can i do this?

**Comment by MrGeneration** [comment]
Get the logs from your docker container, per default it logs to stdout so you may have to wait until it comes back again.

We can't continue without the traceback.

**Comment by ghost** [comment]
Here is a line from the zammad-rails container:
`I, [2020-03-24T10:29:29.435076 #1-47035551746740]  INFO -- : Started GET "/api/v1/integration/ldap/job_start?_=1585045746323" for 10.0.0.18 at 2020-03-24 10:29:29 +0000
I, [2020-03-24T10:29:29.440955 #1-47035551746740]  INFO -- : Processing by Integration::LdapController#job_start_index as JSON
I, [2020-03-24T10:29:29.441058 #1-47035551746740]  INFO -- :   Parameters: {"_"=>"1585045746323"}
I, [2020-03-24T10:29:29.467198 #1-47035551746740]  INFO -- : Completed 200 OK in 26ms (Views: 0.5ms | ActiveRecord: 15.6ms)`

And here a screenshot from the webinterface:
![zammad1](https://user-images.githubusercontent.com/22341283/77425024-5e3f7c00-6dd2-11ea-98cd-ab22bda1c9ba.jpg)


Does this help?

**Comment by MrGeneration** [comment]
No it doesn't - the payload / traceback I'm looking for should look similar to this:
https://github.com/zammad/zammad/issues/2966

**Comment by ghost** [comment]
> No it doesn't - the payload / traceback I'm looking for should look similar to this:
> #2966

The logs from your link looks like logs from the rails server. But at my logs there is not any error regarding to my problem. I only have "INFO" messages. So how can we debug the problem? Is there any console command to get more infos for the ldap integration?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be more of a technical question than a bug at this moment.
Please open a thread in our community. Github is not the ideal place for discussions and technical questions - it causes a lot of noise and destriction for other users.

If we prove me to be wrong, I'll gladly reopen this issue - promised!

Please also note that the in issue 2966 mentioned traceback is something that normally lives within the logfile or the railsservers output.
