### ISSUE TITLE
Adding a note during bulk operation only works for one ticket

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2985]
### Infos:

* Used Zammad version: tested on 3.2 and 3.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: tested on Google Chrome and Firefox, both latest
* Ticket-ID: #1070483 

### Expected behavior:

When selecting several tickets within an overview you can add a note stating why you e.g. closed or postponed that bunch of tickets. This note will be added to every single ticket that has been affected.

### Actual behavior:

When selecting several tickets within an overview, Zammad will only add the note of a bulk operation to the ticket you selected last. The other tickets will not have this note attached.

### Screencast:
![bug_ticket1070483_bulk-no-note](https://user-images.githubusercontent.com/6549061/77422540-ebcc9d00-6dcd-11ea-9779-10ec5617ded0.gif)

### Steps to reproduce the behavior:

* created at least two tickets
* select those tickets within a overview
* use the bulk operation and make sure to fill in the note field
* check your tickets for the article it should have created

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by chrisdecker1201** [comment]
Hello,

I think I found the cause of this problem. At the moment I've no idea how to fix it but in line 1546 of *app/assets/javascripts/app/controllers/ticket_overview.coffee*

~~~
    for ticket_id in ticket_ids
      ticket = App.Ticket.find(ticket_id)
~~~

there is no data in ticket variable only this for example:
~~~
body: "9"​
internal: "false"​
type_id: "10"
~~~

and the ticket variable has only data on the last element in the for-in-loop.
