### ISSUE TITLE
wrong displayed fields in registration form after logout. 

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#2989]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

Registration form should be always the same.

### Actual behavior:

Registration form differs between reload and login->logout->signup.

CORRECT

![grafik](https://user-images.githubusercontent.com/5445062/77520801-08c2a800-6e82-11ea-86c2-ff1bd8606311.png)

WRONG

![grafik](https://user-images.githubusercontent.com/5445062/77520845-16782d80-6e82-11ea-9379-1d80cb2bd2be.png)

### Steps to reproduce the behavior:

login->logout->signup

**Comment by MrGeneration** [comment]
This is a duplicate of https://github.com/zammad/zammad/issues/2640
It's technically missing another issue as well. :x

**Comment by rolfschmidt** [comment]
thx closed.
