### ISSUE TITLE
REST API Bug: When requesting user information via "login" or "email" server returns empty string instead of user data

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2992]
### Infos:

* Used Zammad version:3.3.x updated from 3.0.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: -
* Elasticsearch version: -
* Browser + version: Firefox latest

### Expected behavior:

* Before creating a new ticket via REST API we check if Zammad already knows the user.
* If a user is known it should return the known user data which then gets used to create the ticket, if not a new user is created with the ticket.

### Actual behavior:

* The API call returns an empty string instead of the JSON user file in data (see below for source).

### Steps to reproduce the behavior:

* Update Zammad from 3.0.x to 3.3.x.
* Send PHP curl request, here is an example source call:

// HTTP Header
$aHTTPHeader[] = 'Content-Type: application/json';
$aHTTPHeader[] = 'Authorization: Token token={token};

// Options
$aOptions = array(
  CURLOPT_URL            => 'Your_URL/api/v1/users/search?query=login:Userlogin',
  CURLOPT_HTTPHEADER     => $aHTTPHeader,
  CURLOPT_HEADER         => false,
  CURLOPT_POST           => false,
  CURLOPT_HTTPGET        => false,
  CURLOPT_PUT            => false,
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_HTTPGET        => true;
);

// Init
$ch = curl_init();

// Set curl options
curl_setopt_array($ch, $aOptions);

// Execute
$data = curl_exec($ch);

// Close curl
curl_close($ch); 

* The same happens if you query "email" 
* Have there been any changes in the REST API?

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by SEGGER-NV** [comment]
Quick update.
The issue dissapeared for now after we repeated the steps when updating to the latest zammad version that were recommended:

> 1.1 Elasticsearch search index
> 
> Please note that with updating to Zamamd 3.3, just like Zammad 3.2 a reindex (zammad run rake searchindex:rebuild) of your Zammad installation is required.
> 
> Attention docker-compose users:
> Please note that Zammad 3.3.0-12 upgrades the elasticsearch being used - this requires you to remove the existing indicies. More information on this topic can be found here: https://github.com/zammad/zammad-docker-compose#from--330-12
> 1.2 Possible need to update your vhost configuration
> 
> Our default configuration files we suggest earlier provided the webserver version being used. This is potentially a bad idea.
> nginx users
> 
> Nginx users simply add the following directive to your configuration:
> server_tokens off;
> 
> You can also set this globally within your nginx.conf if needed

So can be closed. Sorry for the confusion.

**Comment by MrGeneration** [comment]
Very odd!
Thanks for keeping us updated.

I'll mark this as a question, as I guess a migration during the update went wrong.

If this occurs again, please let us know, we'll have a deeper look then.
