### ISSUE TITLE
Stuck on loading after update to 3.3.0

### ISSUE THREAD

**Issue by raymond-lmp** [zammad/zammad#2994]
### Infos:

* Used Zammad version: 3.3.0
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04
* Database + version: PostgreSQL 11 (Managed - Digital Ocean)
* Elasticsearch version: 7.6.1
* Browser + version: Chrome v80.0.3987.149 & Firefox 74

### Expected behavior:
For page to load
*

### Actual behavior:
Stuck on loading screen
![image](https://user-images.githubusercontent.com/52719651/77811298-69492380-70d4-11ea-830a-9cb86fdf83a5.png)

I got this during upgrade btw...
![image](https://user-images.githubusercontent.com/52719651/77811257-212a0100-70d4-11ea-88b9-f661e2ed3daa.png)
*

### Steps to reproduce the behavior:
Update zammad using sudo apt update > sudo apt upgrade > reload zammad page
*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by raymond-lmp** [comment]
Also tried excluding Elasticsearch from the upgrade (retained 7.6.0) but getting the same result.

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question.
Your assets don't seem to be correct and your ES plugin needs to be re-installed.

Anyway, this is out of scope of this repository - please note that we use Github for issues only.

The better place for technical question is the Community: https://community.zammad.org.
Please feel free to create a thread there if you still can't solve your issue.

Thanks for understanding - closing.
