### ISSUE TITLE
Login site wording could be better

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3000]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): anymarc
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Desired enhancement:

We should enhance the wording. Currently we're using "Login with {FQDN}" which sounds off and kinda feels wrong. I'd suggest something like "Login to {FQDN}" or "Login on {FQDN}".

https://github.com/zammad/zammad/blob/fae194918eb8a07036060a1b41f1b33c45e03cad/app/assets/javascripts/app/views/login.jst.eco#L4

### Screen:
![image](https://user-images.githubusercontent.com/6549061/78141914-76e00f80-742c-11ea-9121-e262b1197854.png)

### Steps to reproduce the behavior:

* set your browser to english
* browse to the zammad login page (log off if needed)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
I'd say that just FQDN is OK. The screen is self-explanatory :)
