### ISSUE TITLE
Video widget text displaying vertically

### ISSUE THREAD

**Issue by RobMOwen** [zammad/zammad#3001]
* Used Zammad version: 3.3.0
* Installation method (source, package, ..): Debian Package
* Operating system: Ubuntu 1804
* Elasticsearch version: 7.6.2
* Browser + version: Firefox 74.0

### Expected behavior:

* When embedding a video, you'd expect to only see the link text added e.g.:
`( widget: video, provider: vimeo, id: 400199974 )`

### Actual behavior:

* The text also display vertically:
![image](https://user-images.githubusercontent.com/59659109/78219729-08e12a00-74b8-11ea-8a8b-96bc526a92d9.png)

### Steps to reproduce the behavior:

1. Go to knowledge base
2. Add a new answer
3. Insert a video from Vimeo
4. Observe versicle text

NOTE - the video import still works. I really like this new feature!

**Comment by mantas** [comment]
Hi @RobOwen1990 

I'm having a hard time reproducing this issue.

- Does it happen every single time for you?

- Do both correct and vertical texts appear at the same time?

- What's up with yellow and red marks in screenshot? Do you use any browser extensions that may touch this text?

Glad to hear you like you this functionality! :)

**Comment by RobMOwen** [comment]
The fellow and green is `Grammar and Spell Checker - LanguageTool` add in for firefox, resetting this  seems to have resolved it. Thanks
