### ISSUE TITLE
Email import ignores important metadata

### ISSUE THREAD

**Issue by benbucksch** [zammad/zammad#3005]
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): Docker compose
* Operating system: Ubuntu
* Database + version: PostgresSQL
* Elasticsearch version: see above
* Browser + version: Firefox 74

### Expected behavior:
* Email Date: header is mapped to Ticket creation / update date
* Emails threads that are entirely read are imported as solved tickets

### Actual behavior:
* I get 2500 tickets, with solved problems and new problems all mixed together.
* All tickets are imported as open. I cannot see which issues are already done (email thread entirely read).
* I cannot even see which are new requests or old requests, or even when requests have been made.
* The ticket creation and update time is the import time, which is utterly useless.

### Steps to reproduce the behavior:
* Import large email inbox with 5000 support issues of 1 or more years, most of which have been answered, but some are new and outstanding.
* This is a classical situation of an organization that moves from email based support to a ticket system.

Yes I'm sure this is a bug and no feature request or a general question.
* This is a bug, because the email importer drops essential data about the email (date, read status), and tags tickets simply incorrectly. The ticket creation date is flat out wrong.

Impact:
* This makes the imported tickets impossible to work with. I cannot see which of the 5000 tickets are still open.
* It is not a suitable workaround to delete processed tickets, because I do want to import old tickets in the Zammad database, for reference, e.g. when a customer comes back with new questions, I want to see the context of the previous discussions.

**Comment by benbucksch** [comment]
There's no hint whatsoever in the Zammad ticket about when the message was sent. (Unless it's in the body somehow.) Zammad also deletes the original emails.

-> dataloss

**Comment by MrGeneration** [comment]
Within expert settings Zammad allows you to choose if you want to keep data in your mailbox (or not).
So we do not always delete data.
This is described in our documentation:
https://admin-docs.zammad.org/en/latest/channels/email/accounts.html

Currently we do not "archiv import" mail data. This is living in the code prepared, but not yet ready to use.

Also, this is a technical question and not a bug.
Sorry, but please don't post technical questions on this repository.

Thank you.
