### ISSUE TITLE
Email import sends out confirmation emails without asking, and for years old email

### ISSUE THREAD

**Issue by benbucksch** [zammad/zammad#3006]
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): Docker compose
* Operating system: Ubuntu
* Database + version: PostgresSQL
* Elasticsearch version: see above
* Browser + version: Firefox 74

### Expected behavior:
* No emails to customers are sent without my request and approval.

### Actual behavior:
* Zammad sends out confirmation emails to **all** my customers, for **all** existing emails, no matter how old and no matter whether they are read and answered or not.
* After running the importer for a while, the only way that I noticed that Zammad was sending out emails on my behalf was because users responded to me, telling me that their issue no longer matters. Well, no surprise, it's old!
* Zammad never asked me whether it is allowed to send out emails. I was not aware that it would send out "I received your request" confirmation emails. Zammad never told me, never asked me, I never wanted that, and now it emailed thousands of my customers!

# SERIOUSLY ??!!!??

### Steps to reproduce the behavior:
* Import large email inbox with 5000 support issues of 1 or more years, most of which have been answered, but some are new and outstanding.
* This is a classical situation of an organization that moves from email based support to a ticket system.

Yes I'm sure this is a bug and no feature request or a general question.
* This is an extremely serious bug. It causes massive disruption of my company, and immense support issues.
* There isn't even a class for this kind of bug. I'd call it "dataloss", but it's the opposite: Actively interfering with my customer relationships.
* At the very least, you gotta ask me whether I want these confirmations and the specific text. And in any case, they are not appropriate for old imported email!

Impact:
* If you're emailing thousands of customers, you can imagine what happens: You get thousands of responses!
* Lots of these users will take the "opportunity" to ask questions "that they always had on their mind", therefore creating a huge amount of actual, real support issues for us. This is, in effect, the exact opposite of what we needed. We are installing Zammad, because we're overloaded with support requests. Now you've just caused a whole bunch more.

Again:

# SERIOUSLY ???!!!????

**Comment by benbucksch** [comment]
Workaround: Settings | Trigger | auto reply (on new tickets) | Deactivate. However, this is *too late*, given that the setup sequence already started the email import, and Zammad started sending out emails before I had a chance to look at settings. Also, more importantly, as a new Zammad user, I cannot possibly know that such a rule is active, if Zammad never asked me whether I want that. Any customer communication is something that should be explicitly decided by the admin, in detail, with approving the specific text etc.. And even if turned on, it must happen only for new incoming issues, not for importing old ones.

Fixes:
* Disable the trigger rules by default. Let admins activate them explicitly, and **approve the specific text** to be sent. This could be part of the setup sequence, or manually in Settings | Triggers (i.e default off, like the other rules).
* Do not run the auto reply triggers for **old imported email**.

Both fixes are needed to prevent disasters like this one. Just one of the two is insufficient.

**Comment by benbucksch** [comment]
Here's a typical email from a customer. I am getting already tons now, minutes after the import. This is a glimpse of the storm that's going to happen at our support in the next few days:

-----------

Hi:  I'm not sure why I received this message.  I did indeed ..., but that was back in November of 2019.  Initially I did have difficulty getting [product] started, but at the time ....  Shortly thereafter everything worked smoothly.  I never wrote you about this issue again.  So, why are you contacting me now?  --[customer name]

On 4/2/2020 11:00 PM, [my company] wrote:
> Your request (Ticket#...) has been received and will be reviewed by our support staff.
>
> To provide additional information, please reply to this email or click on the following link (for initial login, please request a new password): .../#ticket/zoom/...
>
> Your Zammad Helpdesk Team
>
> Zammad, your customer support system

---------

This shows the problem:
* This is writing on behalf of my company, with the name of my company and our company account, although I never wanted these messages to be sent.
* It's signing with "Zammad, your customer support system", which is wrong
* It's asking users to create a password, although my company intentionally and deliberately has a "no password" policy. We specifically did not want our users to have a password based account with us. We've designed our entire systems to be password-less, to be secure and customer-friendly, and we're proud of that. Now, you've just asked thousands of my customers to create an account with password!
*  You're claiming that the issue "will be reviewed by our support staff", although we will not do that. You lied to our customers. To thousands of them.

And, very obviously:
* Customers are very confused why they are getting emails about months old issues.

This is going to be a huge disaster for our company.

**Comment by benbucksch** [comment]
Another customer replied:

Your system isn't working at all, I checked the spam folder now several times. nothing!!!!!! What crap is your company using?

**Comment by MrGeneration** [comment]
Sorry, but this is working as designed.
Our documentation **is warning you about this**: https://admin-docs.zammad.org/en/latest/channels/email/accounts.html

Thank you for your valuable feedback, however, this is a technical question.
Please do not post technical questions on this repository and use the Community next time instead: https://community.zammad.org
