### ISSUE TITLE
Clickable URLs input type

### ISSUE THREAD

**Issue by ma2t** [zammad/zammad#3009]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): package
* Operating system: Debian 10
* Database + version: postgresql 9.6
* Elasticsearch version: 5.6.16
* Browser + version: Firefox 74.0.1 (64 bits)

### Expected behavior:

* On Tickets zoom: input type "text" on custom object attribute with a clickable URL.

### Actual behavior:

* On Tickets zoom: input type "url" on custom object attribute with a clickable URL.

### Steps to reproduce the behavior:

* Create a clickable URLs for custom object attributes
* Try to answer to a Ticket
* If the attribute isn't empty, the browser is expecting a URL, so the form can't be submit

![zammad](https://user-images.githubusercontent.com/195865/78406933-012e9c00-7604-11ea-8f40-1d9d3af02a2b.png)

### Solving the issue:

* Editing the type from "url" to "text" allow the form submission

Yes I'm sure this is a bug and no feature request or a general question, thank you.

**Comment by MrGeneration** [comment]
Sorry but that's rather a technical question.
If you tell Zammad you want to provide a URL, you have to do so.

Instead change your object to Text if it's not an URL. It technically has nothing to do with the linked object at that point. This is not a bug, but working as designed. :-)

Please don't post technical questions on this repository, For technical questions the Zammad community is the best place: https://community.zammad.org

![image](https://user-images.githubusercontent.com/6549061/78410941-45bf3500-760e-11ea-8988-ad056e14e0d7.png)

**Comment by ma2t** [comment]
Sorry for the confusion @MrGeneration 👍
