### ISSUE TITLE
Using #{article.body} in trigger gives html

### ISSUE THREAD

**Issue by wagnst** [zammad/zammad#301]
If I'm using `article.body` in  a trigger context, because I want to display the message, it gives me all plain html tags in the mail (like `<br>`).
Is there another variable to use, or can this be somehow escaped?

**Comment by martini** [comment]
Fixed in upcoming 1.0.1 and 1.1.0 https://github.com/zammad/zammad/commit/05b6bcc71e6d57823289506d5fc8e9bac7492db8
