### ISSUE TITLE
Variables within Trigger and Scheduler behave differently between subject and body

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3013]
### Infos:

*This originally comes from the Community (https://community.zammad.org/t/no-ticket-id-displayed-in-the-mail-subject-if-there-is-no-space-in-front-of-ticket-number/4344) by user "AnnemarieBecher"*

* Used Zammad version: 3.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Zammad does not require spaces between variables and if it does, it will require them constantly within all interface sections.

### Actual behavior:

When creating either scheduler or trigger based mail replies, you need to add spaces in between variables within subjects, while you don't have to do that within the body.

That's not straight forward - subjects should also allow you to define variables without spaces in between - just like you can do within the body.

### Screens:

![image](https://user-images.githubusercontent.com/6549061/78664717-dc247c80-78d4-11ea-8a38-ea491a2cb59b.png)

![image](https://user-images.githubusercontent.com/6549061/78664752-ecd4f280-78d4-11ea-8fce-0b1b9f02eada.png)

### Steps to reproduce the behavior:

* create either a scheduler or trigger that replies on a ticket by mail
* ensure to insert two variables within the subject and body - e.g.: `#{config.ticket_hook}#{ticket.number}`
* Make the scheduler or trigger fire
* check the response

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Note: the issue was that full ticket identifier (hook + number) is removed from the subject. Once space is present, it wouldn't be detected as the ticket hook. However, it'd look strange with `()` left behind. It is now updated to remove wrapping `()` when removing ticket hook.
