### ISSUE TITLE
User without e-mail can be created

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#3017]
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version:
* Elasticsearch version:
* Browser + version: Firefox latest

### Expected behavior:

* When trying to create a user via the Admin panel or when creating a new ticket via the green plus as an agent, the e-mail field for a new user is mandatory and creates a warning when trying to create a user without an e-mail

### Actual behavior:

* You can simply create a user where only the firstname and lastname fields are filled out.
Pretty sure this was not the case in earlier Zammad versions. 
This can be problematic when you are creating tickets manually in some cases and using email aus  the I/O, then when pressing reply the TO: field will not be autofilled without the user knowing why.

### Steps to reproduce the behavior:

* Create a new user where only firstname and lastname are filled out.
* Success

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Hey,

this is actually not a bug but working as designed.
This has been proposed in this issue https://github.com/zammad/zammad/issues/562 and has became standard with Zammad 2.0 (so quite a long time ago).

While I understand that this is a bad behaviour for you, this is unfortunately nothing you can change in behaviour. Please feel free to fill in a feature request in the Zammad community (https://community.zammad.org) if you think that this should be enhanced. :)

Bests
