### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by ArcheNoah77** [zammad/zammad#3020]
Simple Question: Is a dark mode planned?
I can imagine that others want this too :)

**Comment by MrGeneration** [comment]
Please don't post technical or enhancement questions on this repository.
For this, the Zammad community is the perfect place ( https://community.zammad.org ).

The community is also the perfect place for filling feature requests.
If you have a look within the community and github, there's currently no topic about dark mode. So it's proberbly not planned. Please also note that we in general do not provide roadmaps.

Closing.
