### ISSUE TITLE
KB within Zammad UI (as agent) breaks words (break-all)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3023]
### Infos:

*This was originally discussed within the community, brought up by User timb and further helped by User CptCharlesG on this thread: https://community.zammad.org/t/line-breaks-word-wrap-not-working-correctly-in-knowledgebase/4222/7*

* Used Zammad version: 3.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verfieid on Google Chrome latest

### Expected behavior:

When viewing knowledgebase articles, word's won't be broken down - even if your resolution gets smaller.

### Actual behavior:

When having browser resolutions that are too small to show the max-width of Zammad, knowledgebase answers will break words apart within the agent UI. This only affects submitted answers, not the editor. It's perfectly fine when using the public interface version (`/help`) no matter if you're logged in or not.

![kb-answer-broken_agent-view](https://user-images.githubusercontent.com/6549061/79551440-f52dea00-8099-11ea-8804-1716cd74ff45.gif)

### Responsible parts:

It's mainly this directive causing the issue:
https://github.com/zammad/zammad/blob/develop/app/assets/stylesheets/zammad.scss#L11274-L11276

Which is being references here:
https://github.com/zammad/zammad/blob/fae194918eb8a07036060a1b41f1b33c45e03cad/app/assets/javascripts/app/views/layout_ref/kb_agent_reader_ref.jst.eco#L266

This potentially breaks other places, as richtext-content is used fairly often and might not just affect knowledgebase answers:
https://github.com/zammad/zammad/search?q=richtext-content&unscoped_q=richtext-content

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Historical background: this was a hotfix for https://github.com/zammad/zammad/issues/2918
