### ISSUE TITLE
Remove owner if agent looses permissions to group

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3029]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1073579

### Desired behavior:

When removing agents from groups where they are owners of tickets, the owner for tickets not being closed will reset to `nil`. This will move tickets back into the `Open & Unassigned` overviews to ensure a ticket doesn't get lost.

If you keep it assigned to an agent that can no longer see the ticket, it's flying below your radar until it escalates. Removing the owner assignment greatly improves this.

**This should only affect Tickets in an open state. Closed Tickets should not be altered. Otherwise revision safety can't be guaranteed.**

### Actual behavior:

Zammad does not touch the owner of a ticket if the agent looses access to the ticket. The affected Tickets will fly below your radar until they escalated, because they will not appear within "unassigned & open" overviews. If you don't have specific overviews for your agent, you'll loose track of that ticket.

### Steps to reproduce the behaviour:

* create two groups (e.g. Group A and Group B) and two agents (Agent A and Agent B)
* provide full access to both groups for both agents
* create a test ticket in "Group A" and assign it to agent A
* remove Agent A's permissions to Group A and take over the session of Agent B
* have a look for your test ticket

**Comment by thorsteneckel** [comment]
We decided to wrap that change into a customer extension instead of changing the behaviour in Zammad itself. That's because we received positive feedback about the current state from workshop participants and no one else complained about it so far. If anyone's interested in the extension please get in contact with us via `sales [at] zammad.com` and refer to this issue/comment. Closing now.
