### ISSUE TITLE
User Feedback after successfully closed ticket

### ISSUE THREAD

**Issue by dYn36** [zammad/zammad#303]
A final user feedback would be nice, after the ticket has reached a defined state (e.g. successfully closed), like its possible in (i think) Zendesk.
Like two links in the feedback mail: "My problem was solved, I'm satisfied" or "You didnt solved my problem, bad work" or sth like that.
(Maybe in future, when all the important stuff is done ;-) )

**Comment by thorsteneckel** [comment]
Nice proposal @dynamicman36 ! I'll take it on the list.

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
