### ISSUE TITLE
Upload attachment to an article via REST API does not set content-type 

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#3032]
### Infos:

* Used Zammad version: 3.4.X
* Installation method (source, package, ..): Docker Container

### Expected behavior:

If I upload an attachment via REST API it should store and display in the same way like if I use the zammad UI.

### Actual behavior:

If we use the REST API preferences of the attachment are set like this:

```
"attachments":[
 --
  {
    "filename": "test.txt",
    "id": 82, 
    "preferences":{ 
      "Mime-Type": "text/plain"
    },
   "size": "4"
 }
],
```

If we use zammad UI is looks like

```
"attachments":[
 --
 {
  "filename": "test.txt",
  "id": 86,
  "preferences":{
    "Content-Type": "text/plain"
   },
  "size": "4"
 }
],
```

Because the zammad UI relies on Content-Type and not Mime-Type for rendering the attachment, it sets the filetype to "unknown" in the zammand UI if it was uploaded via REST API.

In our opinion the REST API should unse also Content-Type instead of Mime-Type.

### Steps to reproduce the behavior:

* Upload file via REST:
```
curl -H "Content-Type: application/json" -H "X-On-Behalf-Of: <USER_EMAIL>" -H "Authorization: Token token=<TOKEN>"  -X POST http://<ZAMMAD_API>/api/v1/tickets/ -d '{"title": "test", "group": "Support", "article": {"subject": "test", "body": "this is test", "type": "note", "internal": false, "content_type": "text/html", "attachments": [{"filename": "test.txt", "data": "dGVzdA==", "mime-type": "text/plain" }]}}'
````
* Upload the same file via zammad UI
* Compare the result

![attachments](https://user-images.githubusercontent.com/8117612/79984594-ad4c0000-84a9-11ea-8942-8ca759267c09.png)

**Comment by thorsteneckel** [comment]
Hey @hiaz - good to hear from you! I just wanted to get things straight. The Zammad WebApp is just another consumer of the REST API. So it actually uses the same endpoint as you do. There has to be a difference in the payload that is send. Can you find out how that request looks in the network tab of your preferred browser? Would be cool if you could post the difference. Would be a great help 👍

**Comment by hiaz** [comment]
Hi @thorsteneckel, I think that the WebApp is using different endpoints then the documented ones for the REST API because the WebApp uploads the file first and then creates an article. The documented way for the REST API ships the file as BASE64 in the very same request which creates the article. I think the bug is only in the documented endpoint because it uses Mime-Type as mandatory field instead of Content-Type.

**Comment by rolfschmidt** [comment]
Hi @hiaz ,

i tried to reproduce the error:

```
curl -u master@example.com:test -H "Content-Type: application/json" -X POST http://ubuntu-rs:3000/api/v1/tickets/ -d '{"title": "test", "group": "Users", "customer": "nicole.braun@zammad.org", "article": {"subject": "test", "body": "this is test", "type": "note", "internal": false, "content_type": "text/html", "attachments": [{"filename": "test.txt", "data": "dGVzdA==", "mime-type": "text/plain" }]}}'
```

![grafik](https://user-images.githubusercontent.com/5445062/124261348-f5949280-db30-11eb-8600-e06d49d25bdb.png)

For me it looks fine. Maybe this issue is obsolete and fixed with latest version? Can you verify if you still have this issue?

**Comment by hiaz** [comment]
Hi @rolfschmidt,

I can confirm that this works now with Zammad 4.1. Because we made a bigger version jump, I cannot tell exactly since when the issue is fixed.

Cheers,
Mathias
