### ISSUE TITLE
User registration with already used mail - no translation in german possible?

### ISSUE THREAD

**Issue by lhsei** [zammad/zammad#3036]
I found no way to translate the error message “Email address ‘%s’ is already used for other user.” in the user registration form.
Infos:

    Used Zammad version: 3.3.x
    Used Zammad installation source: package
    Operating system: Ubuntu 18.4.3 LTS
    Browser + version: Microsoft Edge

Expected behavior:

    If the user try to registrate an already used mail-address, he should receive in german language:
    Die Mailadresse ‘%s’ wird bereits von einem anderen Nutzer verwendet."

Actual behavior:

    If the user try to registrate an already used mail-address, he receive in english language:
    Email address ‘%s’ is already used for other user.

    Registrate any mail-address twice.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Looks like this is because server returns hardcoded message that is displayed to user right away. Other error messages in that endpoint seem to have the same issue.

https://github.com/zammad/zammad/blob/57f40539f221bcfb08fdc84d6de1a7728ebfc2a9/app/controllers/users_controller.rb#L141

**Comment by lhsei** [comment]
The same error raises, if you want to verify the account - only englisch language is available:

We've sent an email to yyyy@yyyyyy.de. Click the link in the email to verify your account.
![Error](https://user-images.githubusercontent.com/17147633/80303812-d377e580-87b2-11ea-8d2a-4944ced3cb74.PNG)

**Comment by mgruner** [comment]
@thorsteneckel this is not going to be fixed directly by the Weblate migration, and more of a conceptual issue (do we want to translate exceptions?). I'd prefer to keep it a separate issue for now.

**Comment by fliebe92** [comment]
Hi @lhsei,

time passes by and it seems that the localization is improved a lot in Zammad. From what I can see here, the reported messages are now translatable and the issue should not be there anymore.

Feel free to re-open this report if you still encounter any issues.

Thanks for your understanding. 😎
