### ISSUE TITLE
infinite importing when using pop3

### ISSUE THREAD

**Issue by Chren** [zammad/zammad#3038]
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..):
* Operating system: CentOS 7
* Database + version: N/A
* Elasticsearch version: N/A
* Browser + version: Chrome

### Expected behavior:

* importing end when all of email imported and turned into tickets.

### Actual behavior:

* The importing schedule never stop, the email account only has 1700 emails, but zammad keep importing and never stopped, now it's over 5,0000, it's crazy. And I can't find a way to skip importing when add email channel(using pop3, because imap hang on Verifying, see issue: https://github.com/zammad/zammad/issues/3037). 

### Steps to reproduce the behavior:

* I can't post my email account here, contact me if you want the email account and configuration.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I'm very sure that this is not a bug, but a technical assistance topic.
To ensure, please provide the whole log output of Zammad and, more importantly, update the first artciel to hold all requested information. n/a is not a suitable answer.

Ensure that your pop-Server deletes the mail after sending it. If it does not and still ship to Zammad, this will be the root for your problem. You can check this with your log if Zammad runs the fetch process `mail x / 1700` over and over again.

If you still believe that this is a bug, please also provide the used mail server software and pop3 configuration of it.

**Comment by Chren** [comment]
@MrGeneration 
Sorry I can't find which Database + version and Elasticsearch version it is. I just installed zammad via the latest docker today.

I'm sure this is a bug. You can try it: 
account: [redacted]
password: [redacted]
pop3 server: [redacted]
smtp server: [redacted]

**Comment by MrGeneration** [comment]
This is a technical issue not a bug.
Your server unexpectly closes the connection. In my case this happened after 141 mails.

```
E, [2020-04-25T18:24:34.641728 #2253-47045598785120] ERROR -- : Can't use Channel::Driver::Pop3: #<EOFError: end of file reached>
E, [2020-04-25T18:24:34.641862 #2253-47045598785120] ERROR -- : end of file reached (EOFError)
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/net/protocol.rb:189:in `rbuf_fill'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/net/protocol.rb:157:in `readuntil'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/net/protocol.rb:167:in `readline'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/net/pop.rb:997:in `recv_response'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/net/pop.rb:988:in `getok'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/net/pop.rb:954:in `block in retr'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/net/pop.rb:1013:in `critical'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/net/pop.rb:953:in `retr'
/opt/zammad/vendor/ruby-2.5.5/lib/ruby/2.5.0/net/pop.rb:807:in `pop'
/opt/zammad/app/models/channel/driver/pop3.rb:188:in `block in fetch'
/opt/zammad/app/models/channel/driver/pop3.rb:142:in `each'
/opt/zammad/app/models/channel/driver/pop3.rb:142:in `fetch'
/opt/zammad/app/models/channel.rb:56:in `fetch'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/relation/delegation.rb:71:in `each'
/opt/zammad/app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
/opt/zammad/app/models/scheduler.rb:287:in `eval'
/opt/zammad/app/models/scheduler.rb:287:in `_start_job'
/opt/zammad/app/models/scheduler.rb:239:in `block (2 levels) in start_job'
/opt/zammad/app/models/scheduler.rb:237:in `loop'
/opt/zammad/app/models/scheduler.rb:237:in `block in start_job'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by Chren** [comment]
@MrGeneration  Thanks so much for your time.
But I don't understand, why everything is ok if I login via Mac system mail client with exactly the same configurations? 
If it is the server problem, then all clients should not working.

**Comment by MrGeneration** [comment]
This is a technical issue / support issue.
Please consult either the Community ( https://community.zammad.org ) or get support via a support contract if this is an option for you: https://zammad.com/pricing#selfhosted .

This is out of scope of this Github repository. "It works on a different machine" can have various reasons.

Above is the reason why this issue has been closed.
