### ISSUE TITLE
miss package gawk on Debian

### ISSUE THREAD

**Issue by NeverMin** [zammad/zammad#304]
Updating systemzammad password required for 'apt-get --quiet --yes update': 
.....
Installing required packages: gawk......

**Comment by monotek** [comment]
@NeverMin 
At which step do you needed gawk?
Which Debian Version did you used?

**Comment by NeverMin** [comment]
Hi @monotek 
rvm install 2.3.1 on Debian 7.

**Comment by monotek** [comment]
Thanks for the info.
Would be nice you could rename to file to "README_Install_Debian_Ubuntu.md" and also change the title to "Installation on Ubuntu 16.04 Server / Debian 7"

**Comment by NeverMin** [comment]
Got it and thank you for your suggestion, I will do that

**Comment by monotek** [comment]
No need to close you pull request. You can just push to your repo and the changes are automaticly committed to you pull request ;-)

**Comment by NeverMin** [comment]
@monotek 
done. thanks.

**Comment by NeverMin** [comment]
Sorry :-(

2016-10-26 17:57 GMT+08:00 André Bauer <notifications@github.com>:
