### ISSUE TITLE
Imap to office365 is not possible

### ISSUE THREAD

**Issue by benhartwich** [zammad/zammad#3045]
### Infos:

* Used Zammad version: 3.3.0
* Installation method (source, package, ..): debian package
* Operating system: debian 10
* Database + version: postgresql 12
* Elasticsearch version:
* Browser + version: chrome wind 10

### Expected behavior:
* Connect to outlook / office365 hosted mailboxes via imap to enable this mail pipeline for creating tickets

### Actual behavior:
* host not reachable error occurs. 
* smtp works
* imap won´t work (tested with 2 different outlook accounts and followed the right imap settings of office365)

### Steps to reproduce the behavior:
* install zammad on debian 10 via package manager / repo
* use a nginx proxy with ssl
* try to create an imap connection to office365 hosted mailbox

Yes I'm sure this is a bug and no feature request or a general question. I´ve posted at the community as I thought, it seems to be my bad, but these mailboxes works e.g. at nextcloud mail with the same credentials. I don´t know what zammad setting could affect such behaviour. I think it´s a bug, because it´s a fresh install without any deeper configuration settings (https://community.zammad.org/t/imap-office-365-host-not-reachable/4554)
![2020-05-04_13h35_34](https://user-images.githubusercontent.com/4061954/81039730-1e2be880-8eaa-11ea-909e-8735540c68d1.png)
.

**Comment by MrGeneration** [comment]
Sorry but this is a technical question.
Please do not post technical questions on this repository and use the community instead: https://community.zammad.org .

Side note: I tested this on my end and it's working fine.
