### ISSUE TITLE
CSRF token verification failed - Docker compose new installation

### ISSUE THREAD

**Issue by Syntax3rror404** [zammad/zammad#3049]
I have a problem with a new installation. To prevent any failures i try the installation 3 times to be sure this post are correct. 

After the installation everything workes. But after a docker-compose down and docker-compose up i get this problem. 

```
zammad-railsserver_1    | I, [2020-05-10T14:00:38.541159 #1-46973394042260]  INFO -- : Started POST "/api/v1/message_send" for 172.29.0.1 at 2020-05-10 14:00:38 +0000
zammad-railsserver_1    | I, [2020-05-10T14:00:38.545031 #1-46973394042260]  INFO -- : Processing by LongPollingController#message_send as JSON
zammad-railsserver_1    | I, [2020-05-10T14:00:38.545087 #1-46973394042260]  INFO -- :   Parameters: {"data"=>{"event"=>"login"}}
zammad-railsserver_1    | I, [2020-05-10T14:00:38.550612 #1-46973394042260]  INFO -- : CSRF token verification failed
zammad-railsserver_1    | I, [2020-05-10T14:00:38.551062 #1-46973394042260]  INFO -- : Completed 401 Unauthorized in 6ms (Views: 0.1ms | ActiveRecord: 2.0ms)
zammad-railsserver_1    | I, [2020-05-10T14:00:41.406305 #1-46973394041360]  INFO -- : Started POST "/api/v1/signin" for 172.29.0.1 at 2020-05-10 14:00:41 +0000
zammad-railsserver_1    | I, [2020-05-10T14:00:41.409306 #1-46973394041360]  INFO -- : Processing by SessionsController#create as JSON
zammad-railsserver_1    | I, [2020-05-10T14:00:41.409352 #1-46973394041360]  INFO -- :   Parameters: {"username"=>"(MY-EMAIL)", "password"=>"[FILTERED]", "fingerprint"=>"-1024081820"}
zammad-railsserver_1    | I, [2020-05-10T14:00:41.412750 #1-46973394041360]  INFO -- : CSRF token verification failed
zammad-railsserver_1    | I, [2020-05-10T14:00:41.413241 #1-46973394041360]  INFO -- : Completed 401 Unauthorized in 4ms (Views: 0.1ms | ActiveRecord: 1.2ms)
```

On this topic in your forum you can read this exact issue:
https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080/43

I try to change this configuration in the path volumes/zammad/zammad-data/contrib/nginx. Unfortunately after every restart the configuration was overwrite from any container.

**Comment by MrGeneration** [comment]
Please don't wildly open issues on several repos for the same topic.
This is in this repository a technical question and not a bug.
Please also see https://github.com/zammad/zammad-docker-compose/issues/120 in your specific situation. For the next time if you're having a real bug, please also use the template.

The better place for technical questions is the community: https://community.zammad.org

If you require commercial grade support, you can also have a look at our support contracts https://zammad.com/pricing#selfhosted in case you're interested.

Cl,osing now.

**Comment by Syntax3rror404** [comment]
Why shouldn't that be a bug? I did everything according to your instructions, but it didn't work. This solution is only temporary, by overwrite a configuration that was automaticly generated. 

It is a crafting solution. Far from productive use....

**Comment by MrGeneration** [comment]
This is a docker based issue which is not part of this repository.
You already posted an issue (duplicate) on the docker-compose repository.

Again, your issue is a issue that indirectly comes through the way docker works.
