### ISSUE TITLE
“You have not created a ticket yet” shown but I already have closed tickets

### ISSUE THREAD

**Issue by michaltestovic** [zammad/zammad#3053]
### Infos:

*This issue has been updated by @MrGeneration to meet our requirenments.*

* Used Zammad version: 3.2 (verified on 3.3 as well)
* Installation method (source, package, ..): package/etc/apt/sources.list.d/zammad.list
* Operating system: Debian 10
* Database + version: psql (PostgreSQL) 11.5 (Debian 11.5-1+deb10u1)
* Elasticsearch version: 7.5.1
* Browser + version: Chrome 80.0.3987.106 (Official Build) (64-bit)
* Ticket: #1079853

Related community topic: https://community.zammad.org/t/you-have-not-created-a-ticket-yet-shown-but-i-already-have-closed-tickets/4564

### Expected behaviour:

When changing the default overviews for customers (My Tickets) e.g. to not show tickets with closed state or even splitting the closed tickets into an dedicated view, the customer will see a different text.

Instead of "You have not created a ticket yet", we could instead say "You have no tickets to display in this overview. You can create a new one if you want to [Button]". 

The question is if we want to display the button at all in that case.

### Actual behaviour:

When changing the default overviews for customers (My Tickets) e.g. to not show tickets with closed state or even splitting the closed tickets into an dedicated view, the customer will see a text suggesting to create the very first ticket.

While this is true if the user doesn't have any tickets at this moment at all, it's incorrect if the user does have tickets (no matter of their state). Zammad should display a different text that's not focussing on "you don't have any tickets yet" to not further confuse the user.

This affects all empty customer overviews.

![image](https://user-images.githubusercontent.com/65295235/81823194-59768900-9534-11ea-9ba3-b3a2aeb340b8.png)

### Steps to reproduce:

* close tickets of a customer
* remove the "closed" state from the customers "my tickets" overview (optionally create a dedicated "my closed tickets" overview, it's not required, as it doesn't change the behaviour of Zammad in this case)
* Take over the customers session
* look into the overview "my tickets"
  * this happens if the user has either no tickets at all or there are no tickets to be displayed in the affected overview for this user

**Comment by MrGeneration** [comment]
Thank you for creating the issue.
I have updated it accordingly to our issue template and have removed parts of the issue.

Please note: While this is technically a bug, enhancements (so like your request "Please allow that message to be modified in an update safe way." is a feature request) are  out of scope of this repository.

We always aim to cover about 80% of Zammad users - such high customization does not meet this aim at the moment.

That being said, I agree that the text should be optimized to confuse the user less. I believe that I did cover that wish from both of our ends with my edits on your text and hope you do agree.

Thanks again for your time and effort.

**Comment by michaltestovic** [comment]
The edit you made sounds good to me - I agree.

**Comment by thorsteneckel** [comment]
The current API implementation does not provide the required information to show a proper text that suits all of the use cases:

- New user without tickets
- Known user with tickets that are all closed (in the current overview e.g. Organization)

Therefore we postpone this change to the webapp 2.0 refactoring.
