### ISSUE TITLE
Ticket split in Safari loses images

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#3056]
### Infos:

* Used Zammad version: latest *hosted* 3.3.x
* Installation method (source, package, ..): hosted
* Operating system: macOS Catalina 10.15.4
* Database + version:
* Elasticsearch version:
* Browser + version: Safari 13.1

### Expected behavior:

* If one splits a ticket, inline images should be took over to the new "splitted" ticket

### Actual behavior:

* One splits a ticket in Safari, images are dropped silently. No errors in the console or shown to the user

### Steps to reproduce the behavior:

* Split a ticket, with inline images in safari
* Preview of the ticket is already missing the images
* Created ticket has no reference to the images anymore

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Does this possibly also play into this issue?
https://github.com/zammad/zammad/issues/2942

Or does it only affect Safari...?

**Comment by martini** [comment]
It only affects Safari. Inline images are dropped right after clicking `split`. No placeholder and no images are show in ticket create screen.

**Comment by mantas** [comment]
Likely a bug in Safari

I can reproduce it in latest stable Safari `Version 13.1 (14609.1.20.111.8)`. But it works fine in Safari Preview `Release 106 (Safari 13.2, WebKit 14610.1.12.2)`.

**Comment by dominikklein** [comment]
I can confirm that this problem is no longer reproduceable with a newer Safari Version.
