### ISSUE TITLE
Unprocessable mails - PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by ngnix** [zammad/zammad#3057]
Hello zammad team!
About my environment:

1. zammad version: 3.3.0
2. installation method: build from source code
3. OS: CentOS Linux release 7.8.2003 
4. database: postgresql-11
5. elk: 7.6.2

**Number of posgresql DB - 1**
**Number of ELK clusters - 1**
**Number of zammad application nodes - 2**

**Problem description:
after we added  second zammad node errors began to appear in the logs:**
[root@node02:~]# cat /opt/zammad/log/scheduler_out.log-20200518 
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/4d9e4a93b68b4438322bab982c69919f.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint \"index_users_on_login\"\nDETAIL:  Key (lower(login::text))=(ajbastos23@gmail.com) already exists.\n: INSERT INTO \"users\" (\"login\", \"firstname\", \"lastname\", \"email\", \"updated_by_id\", \"created_by_id\", \"created_at\", \"updated_at\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING \"id\">"
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/62f6155ec112f6ca8dd277fa67861ebf.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint \"index_users_on_login\"\nDETAIL:  Key (lower(login::text))=(generosoq@yahoo.com) already exists.\n: INSERT INTO \"users\" (\"login\", \"firstname\", \"lastname\", \"email\", \"updated_by_id\", \"created_by_id\", \"created_at\", \"updated_at\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING \"id\">"
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/b9c7487984b039faae9e12be32a70a06.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint \"index_users_on_login\"\nDETAIL:  Key (lower(login::text))=(dgb.dejuan@gmail.com) already exists.\n: INSERT INTO \"users\" (\"login\", \"firstname\", \"lastname\", \"email\", \"updated_by_id\", \"created_by_id\", \"created_at\", \"updated_at\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING \"id\">"
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/a12fd678f9d913ec127eb0725a594e26.eml, please create an issue at https://github.com/zammad/zammad/issues"

On both zammad nodes errors accumulate about  unprocessable mails.
On both nodes zammad health check monitoring indicates a problem with unprocessable mails

how we can solve this problem?

**Comment by MrGeneration** [comment]
Please don't post technical questions on this repository.
Kindly use the community for those requestions: https://community.zammad.org (please keep the templates in tact)

You can also have a look at our service contracts (https://zammad.com/pricing#selfhosted) in case you're interested in commercial grade support.

Closing now.

**Comment by ngnix** [comment]
move to https://community.zammad.org/t/unprocessable-mails-pg-error-duplicate-key-value-violates-unique-constraint/4647
