### ISSUE TITLE
Search details sidebar name shows URL-encoded gibberish

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#3058]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Sidebar names are easily readable

### Actual behavior:

* Search details sidebar name shows URL-encoded identifier instead of `"`

![Screenshot 2020-05-19 at 00 43 24](https://user-images.githubusercontent.com/36944/82262623-ea50c880-9969-11ea-9dc5-d1fa79ee9bd6.png)

### Steps to reproduce the behavior:

* Search for `tags: "tag name"`

* Open search details

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This affects `'` as well. :>

![image](https://user-images.githubusercontent.com/6549061/82292888-efcf0280-99ab-11ea-926e-9f04a243f77e.png)
