### ISSUE TITLE
triggers do not work?

### ISSUE THREAD

**Issue by kernbrand** [zammad/zammad#306]
i want to inform a customer if a ticket is changed (a new article is added, the ticket state has changed...) i tried to set up a matching trigger, but none of the conditions i tried made the trigger work. also, the predefined triggers like "customer notification (on owner change)" do not work at all. any ideas what's wrong?

**Comment by martini** [comment]
Can you add screenshots from your trigger? So we can try to reproduce it. :)

**Comment by kernbrand** [comment]
hi martin,

sure, here's the one i created. 
but as mentioned before: the predefined triggers do not work either, so i don't believe that the trigger is the problem. i'd say it's an installation or config problem, but there's nothing in the logs and i'm not familiar with RoR, so every hibt is highly appreciated.

regards
lorenz

![clipboard01](https://cloud.githubusercontent.com/assets/16773234/19715615/af5c7040-9b56-11e6-926c-769b79d9a8e3.png)

**Comment by martini** [comment]
Hi Lorenz,

ok, if the predefined is not working, it's a problem. :-D

The scheduler is running (script/scheduler.rb status)?

 -Martin

**Comment by kernbrand** [comment]
yes it's running:

zammad@1477290932-1:/opt/zammad$ script/scheduler.rb status
scheduler: running [pid 17450]

scheduler_out.log and scheduler_err.log are empty.
production.log contains entries like this:

I, [2016-10-26T06:36:53.483807 #17450]  INFO -- : execute Job.run (try_count 0)...
I, [2016-10-26T06:37:03.316741 #17450]  INFO -- : Scheduler running...
I, [2016-10-26T06:37:03.333827 #17450]  INFO -- : Started job thread for 'Generate user based stats.' (Stats.generate)...
I, [2016-10-26T06:37:03.396247 #17450]  INFO -- : execute Stats.generate (try_count 0)...
I, [2016-10-26T06:37:03.586823 #17450]  INFO -- :  ...stopped thread for 'Stats.generate'
I, [2016-10-26T06:37:12.879234 #17450]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2016-10-26T06:37:12.881309 #17450]  INFO -- : fetching imap (mail.servercom/ticket@server.com port=993,ssl=true)
I, [2016-10-26T06:37:13.337282 #17450]  INFO -- :  - no message
I, [2016-10-26T06:37:13.337367 #17450]  INFO -- : done
I, [2016-10-26T06:37:43.401801 #17450]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2016-10-26T06:37:43.403792 #17450]  INFO -- : fetching imap (mail.server.com/ticket@server.com port=993,ssl=true)
I, [2016-10-26T06:37:43.849585 #17450]  INFO -- :  - no message
I, [2016-10-26T06:37:43.849651 #17450]  INFO -- : done
I, [2016-10-26T06:38:13.334339 #17450]  INFO -- : Scheduler running...
I, [2016-10-26T06:38:13.945048 #17450]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2016-10-26T06:38:13.947203 #17450]  INFO -- : fetching imap (mail.server.com/ticket@server.com port=993,ssl=true)
I, [2016-10-26T06:38:14.390367 #17450]  INFO -- :  - no message
I, [2016-10-26T06:38:14.390457 #17450]  INFO -- : done

fetching the mails works.

**Comment by wagnst** [comment]
triggers work perfectly for me. Does your mail setup fully work? Is the test on the web ui working?

I also implemented such kind of notifications. The only thing that is really missing is filtering regading if a message is internal or public, as the internal messages cant be seen by the customer, but the trigger then also sends notifications, in case the message was internal only see #298.

**Comment by kernbrand** [comment]
yes, the mail system works. all non-trigger mails are sent, e. g. the agent notification when a new ticket was created. only the trigger related mails do not work.

**Comment by wagnst** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/7312523/19733413/35a28458-9ba4-11e6-983c-0955912ae383.png)

I have attached my trigger, maybe you cant try with that one :-)

**Comment by kernbrand** [comment]
@wagnst @martini 
thanks for your assistance. i don't know why but after a server reboot the triggers started to work.

**Comment by martini** [comment]
@kernbrand thanks for feedback!
