### ISSUE TITLE
Loading KB-Answers doesn't work for contained images

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3060]
### Infos:

*Kudos to community user mtrojacher who originally found the issue! (https://community.zammad.org/t/images-broken-when-adding-knowledgebase-articles-to-tickets/4341)*

* Used Zammad version: 3.3, 3.4-develop
* Installation method (source, package, ..): package
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on Chrome and Firefox (each latest)
* Ticket-ID: #1076055

### Expected behavior:

Loading knowledgebase answers that contain images into any ticket works without issues.

### Actual behavior:

Loading knwowledgebase that didn't exist (or have been updated) before Zammad 3.3 and contain images no longer allow calling those images. Instead, it provides something like that:

```
<img style="max-width:100%;width: 1360px;max-width: 100%;" src="[object HTMLImageElement]" cid="KnowledgeBase::Answer::Translation::Content_body.898294344@zammad.example.com">
```

This seems to be due to support gif images which now uses the attachments. Note that base64 encoded images living in the answer body are absolutely fine. There's currently no clean workaround, as both copying inline images _and_ using the "image" button is producing this behaviour.

### Steps to reproduce the behavior:

* Have a current Zammad 3.3
* create a new (or use an existing) knowledgebase answer
  * type any text and either (or do both, doesn't matter) upload a new image via image button or insert an inline image (as long as you're not shipping it via base64)
* save your changes
* open a new ticket dialogue or use an existing ticket
* press `??` and type the title of the kb answer you just edited/created
  * press enter to load the kb  answer into the ticket
  * be sad because you don't see any images :-(

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by ghost** [comment]
reopen please

**Comment by MrGeneration** [comment]
@sRlinux why?

**Comment by ghost** [comment]
Cause it is not fixed, still the same behaviour.

**Comment by MrGeneration** [comment]
Please check develop, it's not available in stable yet.
