### ISSUE TITLE
Install issue Ubuntu 19.10 - 

### ISSUE THREAD

**Issue by cun** [zammad/zammad#3061]
#2597 # Infos:

* Used Zammad version: Latest
* Installation method (source, package, ..): Apt
* Operating system: Ubuntu 19.10 - Clean install.

### Expected behavior:
Should install. I have libreadline8 installed, and I can't install libreadline7 and associated packages.

### Actual behavior:
The following packages have unmet dependencies:
 zammad : Depends: libreadline7 but it is not installable
          Depends: libssl1.0.0 but it is not installable
          Depends: libmysqlclient20 but it is not installable
E: Unable to correct problems, you have held broken packages.

### Steps to reproduce the behavior:
apt-get install zammad -y

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question which is out of scope of this repository.

Please note that we currently **do not support** Ubuntu 19.1 - there's no packager package for this as of now. Our upstream packager does currently not support it: https://github.com/crohr/pkgr/blob/a4172c2394c5baa615c92692ebf17a164eaf7d49/README.md

Supported Ubuntu versions can be found here:
https://docs.zammad.org/en/latest/install/ubuntu.html


Please note that the better place for technical questions is the Zammad Community: https://community.zammad.org .
If you require commercial grade support, you can find our support contracts at https://zammad.com/pricing#selfhosted - in case you're interested.

Closing now.
