### ISSUE TITLE
KB search does not allow pagination on endpoint

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3068]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): any (package installation, verified on hosted:develop)
* Operating system: any
* Database + version: any
* Elasticsearch version: ES 7.x
* Browser + version: verified with Postman, not Browser related
* Ticket-ID: #1076280

### Expected behavior:

When searching for results, you can use pagination in order to overcome technical limitations via API to receive all available search results if needed.

As documented here:
https://docs.zammad.org/en/latest/api/intro.html#pagination

### Actual behavior:

When using knowledgebase search endpoint `/api/v1/knowledge_bases/search` it returns (in my case) 9 search results and doesn't allow further pagination.

Attributes `page` and `per_page` are ignored entirely. 

While this doesn't matter on UI perspective for now, it makes it very hard for custom scripts to run extended searches on existing data of Zammad.

### Steps to reproduce the behavior:

* create a lot of answers (10 or more) that all contain your favorite slug to search for 
  * ensure that all answers are public, as the search does not return internal or draft results 
* search for your favorite slug using [POST] `/api/v1/knowledge_bases/search?query=myslug`
*  see the result

You can try to extend `/api/v1/knowledge_bases/search?query=myslug` by `&page=1&per_page=5` which should deliver less or at least different results.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
@MrGeneration we use 2 pagination-like patterns

- lists and single-resource searches user `page` and `per_page`

- global search uses `limit` which is applied per-resource

KB search is more like global search since it returns multiple resources. Maybe it'd be better to use `limit` pattern?

**Comment by MrGeneration** [comment]
If `limit` pattern allows pagination that's fine to me personally.
However, we definitely have to update the docs, because the difference was unknown to me up to now.

**Comment by mantas** [comment]
Global search using `limit` doesn't allow pagination. 

What use case do you see for pagination?

Maybe separate single-resource APIs would be better? To follow same pattern of global search with `limit`vs ticket/organization/user search with `page`/ `per_page`

**Comment by MrGeneration** [comment]
Currently the knowledgebase search doesn't return all available search results for a specific search.
If you however want to list all results by a specific key word or maybe category via API, this currently is not possible.

Our customer has a lot of answers in his kb and uses his own UI solutions.
This causes the customer not being able to list all KB answers if there are too many results.

I think a pagination is a must - not sure if single resource APIs make too much sense in terms of the knowledgebase. This is because of the way it works and divides information technically.

This would proper specification I guess.

**Comment by mantas** [comment]
I agree in general that pagination is a must.

Thing is, as of now it fetches data from multiple ES indexes and then puts it together. So pagination would be a wee... Inefficient to say the least :)

It turns out that `limit` parameter in request (which already exists) is applied only when combining indexes, not when querying them. Thus raising limit still keeps it stuck at `10` :) Which is definitely a bug.

I see 2 solutions:

a) fix `limit` not propagating. Customer could set it to `999999` to get full response. However, that is likely to cause performance issues

b) add single-resource endpoints with proper elasticsearch-backed pagination

**Comment by MrGeneration** [comment]
I'd personally go for variant b then - we'd need to discuss this in standup as example.
