### ISSUE TITLE
Helpdesk stays blank on "Loading" screen

### ISSUE THREAD

**Issue by Tiefen-boop** [zammad/zammad#3069]
Just installed Zammad on a brand new CentOS 7 machine following these instructions:
https://docs.zammad.org/en/latest/install/centos.html

Since this is a minimal CentOS installation I don't have a browser on the machine and first thing I did after installing zammad using 
`yum install -y zammad`
was changing the 'localhost' to my already correctly pointing fqdn in /etc/nginx/conf.d/zammad.conf 

Now trying to open the Helpdesk using a browser will yield a blank loading screen that won't advance to the installation process

**Comment by MrGeneration** [comment]
Sorry but this sounds rather like a technical question.

Please consult the community for such requests and ensure to fill in the templates: https://community.zammad.org

If you require commercial grade support you can have a look at our support contracts as well: https://zammad.com/pricing#selfhosted
