### ISSUE TITLE
Trigger condition "contains not" should take care of empty/not-set fields

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#3072]
### Infos:

*This post has been updated by @MrGeneration to meet our standards and hold all required information*

* Used Zammad version: 3.3
* Installation method (source, package, ..): package
* Operating system: ubuntu 18.04.4 LTS
* Database + version: postgresql-9.5
* Elasticsearch version: 5.6.16
* Browser + version: Chrome 83.0.4103.61
* Ticket-ID: 1076494 

### Scenario:

Create a trigger:

CONDITIONS FOR EFFECTED OBJECTS
Language: contains not: de_DE

While Language is a text field for users

### Expected behavior:

Trigger fires if Language is different from de_DE _and_ if Language it is empty/not-set

### Actual behavior:

Trigger fires only if Language is different from de_DE but _not_ if it Language is empty/not-set

**Comment by MrGeneration** [comment]
Two things:
* Please fill in the complete template, half of your system information are missing. These are crucial.
* Could you please let us know what "language" exactly is? What object type are we talking about? (not just e.g. "Select", but also which object category (User, Ticket, ...))

**Comment by hiaz** [comment]
* Language is a custom text field which I created via Settings > Objects > User, sorry I did not remember that it is not a standard field.

I am sure that only the zammad version matters for this problem but no one should say I am not cooperative:

* Installation method (source, package, ..): package
* Operating system: ubuntu 18.04.4 LTS
* Database + version: postgresql-9.5
* Elasticsearch version: 5.6.16
* Browser + version: Chrome 83.0.4103.61

**Comment by MrGeneration** [comment]
Thanks for your report! I could verify this issue.

This issue doesn't appear if a trigger explicitely checks for a specific value (which might not help in above use case). 
In my tests this also affected select fields "not containing value x"

**Comment by mohamed-rouissi** [comment]
I have approximatively the same problem. 

I have set up a `MAC Adresse` field as follows:

![Anmerkung 2020-06-08 144906](https://user-images.githubusercontent.com/61789098/84032201-41f5b900-a997-11ea-8ef6-3c790e4549e2.png)

A trigger has been set up to notify the customer in case the `MAC Addresse` field has been filled in/modified. 

At the first change of data (for any other field) in the ticket, and thus without having filled in the `MAC Addresse` field, Zammad sends an email to the customer to notify him that the MAC address has been changed: 

`"[say hey] | Aktualisierung der MAC Adresse->" `

(`[#{ticket.title}] | Aktualisierung der MAC Adresse-> #{ticket.mac_adresse}`)

----

- Used Zammad Version: 3.3x
- Installation method: package
- OS: Ubuntu 18.04.4 LTS
- DB: postgressql 10.12
- Elasticsearch version: 5.6.3
- Browser: Mozilla Firefox: 77.0.1

**Comment by MrGeneration** [comment]
We can no longer reproduce this issue. 
It either has magically self fixed or I'm not able to find the correct commit responsible for this. 

I've verified this on a stable 4.0.
