### ISSUE TITLE
facebook scope changes with APIv7.0

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3080]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): any 
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Google Chrome latest
* Ticket-ID: 1076705, 1076758 , 1076759 

### Expected behavior:

Authentication against facebook, no matter if using the "add account" functionality for adding a new facebook channel or authentication itself for logging in to Zammad, the process will function successfully.

### Actual behavior:

If enabling API version 7, facebook complains about invalid scopes which are requested by Zammad during autorisation against facebook.

Old scopes are:
* publish_pages
* manage_pages

These scopes are, as far as I can tell, replaced by:
* pages_manage_engagement
* pages_manage_metadata
* pages_manage_posts

If provided with above mentioned permissions, Zammad will function with API version 6.

![image](https://user-images.githubusercontent.com/6549061/84383926-7d89c080-abed-11ea-9c9d-5117c94d9be0.png)

### Currently working solution:

Don't upgrade facebook Apps to API version 7 (neither for endusers nor developers).
facebook Apps up to API version 6 seems to be working without issues.

*Note: Downgrading developers API version from 7 to 6 is not possible - however, it is for endusers.*

### Steps to reproduce the behavior:

* have a app with required permissions ( `pages_manage_engagement, pages_manage_metadata, pages_manage_posts, email, default` )
* try to authenticate against facebook for either logging in to Zammad or adding a facebook page to the facebook channel
  * to double tab you can test this with API version 6 and less and API version 7
  * keep in mind that, as soon you upgrade API version to v7 for the developer, there's no way back

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by hasbiallah** [comment]
how to downgrade the API version?

**Comment by MrGeneration** [comment]
Developer API versions can't be downgraded.
Sorry, but this is out of scope of the Zammad applicaiton.

To reduce technical questions and disctraction on this issue, I'll be limitting the conversation to contributors only.
This is nothing personal against you.

Please use the Zammad community for technical questions: https://community.zammad.org
If you require commercial grade support, you can find more information on our support contracts here: https://zammad.com/pricing
