### ISSUE TITLE
KB answer search in ticket is broken

### ISSUE THREAD

**Issue by marandus** [zammad/zammad#3083]
### Infos:

* Used Zammad version: 3.3.0
* Installation method (source, package, ..): source
* Operating system: CentOS 8
* Database + version: PostgreSQL 10.6
* Elasticsearch version: currently not used
* Browser + version:
  * Firefox 77.0.1
  * Chromium Edge 83.0.478.45

### Expected behavior:

* When typing into the "Related Answers" textbox in a ticket, a list of matching KB answers should open up and allow to select the requested one.

### Actual behavior:

* The list does not show up, seems to be the same issue that was previously reported (and fixed) in #2789. The REST API yields the correct data, but the list does not show up and thus no entry can be selected. Hitting return yields an error "No such object". Linking via KB article works.

REST request:
```
{
    "query": "F000",
    "limit": 40,
    "flavor": "agent",
    "include_locale": true,
    "index": "KnowledgeBase::Answer::Translation",
    "highlight_enabled": false
}
```

REST response:
```
{
    "result": [
        {
            "id": 2,
            "type": "KnowledgeBase::Answer::Translation"
        },
        {
            "id": 3,
            "type": "KnowledgeBase::Answer::Translation"
        }
    ],
    "details": [
        {
            "id": "2",
            "type": "KnowledgeBase::Answer::Translation",
            "icon": "knowledge-base-answer",
            "date": "2020-06-15T13:50:46.526Z",
            "url": "/help/en-us/3-nav-error-numbers/2-f000",
            "title": "F000 (English (United States))",
            "subtitle": "NAV Error Numbers",
            "body": "Generic error"
        },
        {
            "id": "3",
            "type": "KnowledgeBase::Answer::Translation",
            "icon": "knowledge-base-answer",
            "date": "2020-06-15T13:54:41.611Z",
            "url": "/help/de-de/3-nav-fehlernummern/2-f000",
            "title": "F000 (Deutsch)",
            "subtitle": "NAV Fehlernummern",
            "body": "Dumdidum"
        }
    ]
}
```

### Steps to reproduce the behavior:

* Create a KB answer
* Create a ticket
* Try to search the KB answer using the "Related Answers" textbox

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Note: works fine with elasticsearch enabled, broken only with no elasticsearch.
