### ISSUE TITLE
Required Doorkeeper scope is missing and fails authentication

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3085]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any 
* Browser + version: any
* Ticket-ID: 1076848 

### Expected behavior:

Authentication against Zammads API via oAuth works (`/oauth/...`) without issues.

### Actual behavior:

If trying to authenticate against Zammad using oAuth, you'll receive a doorkeeper error message for missing translations. If you dig deeper, you'll find out that you're missing scopes.

![image](https://user-images.githubusercontent.com/6549061/84673614-3a4f8a80-af2a-11ea-8c76-811db25a1db2.png)

This issue was introduced by a security related bump: 
https://github.com/zammad/zammad/commit/b9b3a73474cb3e44e3a18c898dfa113a495069d7

### Steps to reproduce the behavior:

* try to authenticate against Zammad via oAuth
  * this will provide an error page that the translation for the error page is missing
  * if you provide that translation, it will tell you it's missing scopes

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
JFI: Fix is currently tested and running on CI.
