### ISSUE TITLE
Notes on existing ticks are discarded by editing profile settings

### ISSUE THREAD

**Issue by Vogelkoje** [zammad/zammad#3088]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* When editing profile settings, the drafts in a tab should not be discarded

### Actual behavior:

* Notes on existing ticks are discarded by editing profile settings

### Steps to reproduce the behavior:

* Open existing ticket 
* Add in this ticket an article (note, mail, ...)
* Leave the tab open, don't close it
* Go into the own profil settings
* Change in profil settings your language or notifications settings
* Go back in the tab with you draft article
* The draft isn't show and lost

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Does it get completely lost or just text field is collapsed as in screenshot bellow? It's a bug nonetheless, just making sure I'm looking at correct bug :)

![Screenshot 2020-06-19 at 09 07 25](https://user-images.githubusercontent.com/36944/85102006-5c882780-b20c-11ea-9c99-f6ea71bc1f0b.png)

**Comment by MrGeneration** [comment]
No, more like information typed into the article field are being discarded / lost.

![issue3088](https://user-images.githubusercontent.com/6549061/85103883-ceaa3d80-b207-11ea-9523-16a0123d0670.gif)

**Comment by mantas** [comment]
Welp. Either we got 2 bugs or same bug is slightly different in slightly different circumstances!

**Comment by MrGeneration** [comment]
> Welp. Either we got 2 bugs or same bug is slightly different in slightly different circumstances!

This should have been fixed with Zammad 3.4:
https://github.com/zammad/zammad/issues/3040

**Comment by mantas** [comment]
> > Welp. Either we got 2 bugs or same bug is slightly different in slightly different circumstances!
> 
> This should have been fixed with Zammad 3.4:
> #3040

Yet I got it when saving my profile with an unsaved note.

**Comment by MrGeneration** [comment]
> Yet I got it when saving my profile with an unsaved note.


Then it might be a combined problem which I don't see in my browser, that's possible. 🤷
