### ISSUE TITLE
No inbound calls FreePBX

### ISSUE THREAD

**Issue by yuljk** [zammad/zammad#3092]
Hi - I've successfully setup the integration service on my FreePBX server, however when calling the number for my agent, I don't see anything in Zammad.

All I can see from /var/log/messages is:-

Jun 18 18:27:01 cassiopea asterisk-zammad-cti-bridge[25097]: 2020-06-18 18:27:01 +0100 [debug] got event: Registry
Jun 18 18:27:18 cassiopea asterisk-zammad-cti-bridge[25097]: 2020-06-18 18:27:18 +0100 [debug] got event: PeerStatus
Jun 18 18:27:31 cassiopea systemd[1]: Removed slice User Slice of asterisk.
Jun 18 18:27:43 cassiopea asterisk-zammad-cti-bridge[25097]: 2020-06-18 18:27:43 +0100 [debug] got event: PeerStatus
Jun 18 18:27:46 cassiopea asterisk-zammad-cti-bridge[25097]: 2020-06-18 18:27:46 +0100 [debug] got event: Registry
Jun 18 18:27:53 cassiopea asterisk-zammad-cti-bridge[25097]: 2020-06-18 18:27:53 +0100 [debug] got event: PeerStatus

So looks like it is communicating OK.

In Zammad I have enabled CTI (generic) and set my default caller ID to my CallerID in inbound routes, otherwise everything else is untouched.

I'm not using queues or anything fancy on the PBX, just an inbound route that goes to a ring group with my extensions.

Any help would be appreciated!

**Comment by MrGeneration** [comment]
Sorry, but this looks like a technical question.
Please **do not post** technical questions on this repository.

You can post technical questions on the Zammad community at https://community.zammad.org 
If you require commercial grade support, you can also have a look at https://zammad.com/pricing#selfhosted in case you're interested.

Closing now.
