### ISSUE TITLE
Email address falsely converted on pasting into article body

### ISSUE THREAD

**Issue by pmarchi** [zammad/zammad#3099]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04
* Database + version: postgresql-10/bionic-updates,bionic-security,now 10.12-0ubuntu0.18.04.1 amd64
* Elasticsearch version: elasticsearch/stable 7.8.0 amd64
* Browser + version: Safari 13.1 on macOS 10.15.4

### Expected behavior:

* An article including email addresses with characteristic like "domain.de-@domain.de" should not change the string in any way not add a link to the email address or part of it.

### Actual behavior:

* An email address with the following characteristics "domain.de-@domain.de" will be shown as "domain.de-@domain.de-@domain.de" in an article. This also happens when pasting "domain.de-@domain.de" into a text field. The email address is immediately converted to "domain.de-@domain.de-@domain.de". This affects almost all email addresses containing domain.tld- (dash) before the @. Some newer TLDs are the exception here. Examples:
- a.de-@a.de (affected, turns into a.de-@a.de-@a.de)
- a-b.de-@a.de (affected, turns into a-b.de-@a.de-@a.de)
- patrick.de-marchi@domain.ch (real world example, affected turns into patrick.de-marchi@domain.ch-marchi@domain.ch)
- a.yoga-@a.de (not affected, although yoga is a TLD)

### Steps to reproduce the behavior:

* Paste "domain.de-@domain.de" into a text field of an email/note/etc.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Note on reproducing. Highlighting and cmd+c won't cause this. Only right-click and "copy as email" will. Reproducible both in Safari and Chrome.
