### ISSUE TITLE
Discarding changes impossible on system based ticket attribute changes

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3101]
### Infos:

*This is a follow up on issue https://github.com/zammad/zammad/issues/3078 which originally was posted by https://github.com/SEGGER-NV and was only indirectly mentioning this issue. For better overview we will handle this as an independent issue.*

* Used Zammad version: 3.4, should also affect earlier versions
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on current Firefox and Google Chrome
* might indirectly be related to: https://github.com/zammad/zammad/issues/3035

### Expected behavior:

When changing e.g. attribute values which causes "attribute changed" situations on an ticket that's opened in a taskbar, you can always discard changes to their default value (which also could be nil in situations).

### Actual behavior:

You can, at no point, reset changed ticket attributes that have changed (or need an update) due to changes on e.g. a custom object or an de-activated agent that was assigned to a ticket if the said ticket still is opened in your taskbar.

![issue3101_discard-impossible-on-system-changes](https://user-images.githubusercontent.com/6549061/86013776-d051dd80-ba1f-11ea-993b-e8dd2aa711e1.gif)

### Steps to reproduce the behavior:

*Note: This also works with attributes.*

* assign a dummy agent as owner to any ticket
* login as admin with agent permission and open the same ticket
* leave the ticket open as taskbar and deactivate said dummy agent
* reload Zammad and check back to the ticket in the taskbar
   * discarding the change is not possible

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
As discussed with @thorsteneckel core workflow will display inactive owners instead of removing them and displaying the ticket as changed. This behaviour will not occur anymore in 5.x.
