### ISSUE TITLE
Merging tickets doesn’t trigger notification for target ticket

### ISSUE THREAD

**Issue by awedor** [zammad/zammad#3105]
### Infos:

* Used Zammad version: 3.3 & 3.4
* Installation method (source, package, ..): package
* Operating system: CentOS 7
* Database + version: Postgresql 12.3
* Elasticsearch version: 7.7
* Browser + version: any
* Ticket #1087628

### Expected behavior:

* When ticket B is merged into ticket A the owner of ticket A should be notified of an update to his ticket

### Actual behavior:

* When ticket B is merged into ticket A only the owner of ticket B is notified of the change to status “merged”, the owner of ticket A doesn’t receive a notification for the update of his ticket, neither per mail nor per Zammad notification. The icon of the ticket doesn’t pulse either.

### Steps to reproduce the behavior:

* Merge two tickets

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This originally has been discussed on the Zammad community before:
https://community.zammad.org/t/merging-tickets-doesnt-trigger-notification-for-target-ticket/4787

**Comment by mantas** [comment]
@MrGeneration which points in your community post apply for this issue?

a) seems already there, b) is won't fix, d) is covered by #2467... So this issue is for c) making the circle pulse only?

**Comment by awedor** [comment]
> 
> 
> @MrGeneration which points in your community post apply for this issue?
> 
> a) seems already there, b) is won't fix, d) is covered by #2467... So this issue is for c) making the circle pulse only?

Well none of the points apart from c apply for this issue but the main problem stated above still persists. The other points I wrote were additional points for discussion but I obviously didn't add them to the bug report.

**Comment by mantas** [comment]
@awedor and the main problem would be solved by #2467 if I understand correctly?

**Comment by MrGeneration** [comment]
> and the main problem would be solved by #2467 if I understand correctly?

No. Issue #2467 is an addition that allows you to trigger for such merges.
This issue is about the agent not receiving an information that the ticket has been update (which is done technically by a merge).

So basically you'll never notice that the ticket has changed without having a direct look into it.

**Comment by awedor** [comment]
> 
> 
> @awedor and the main problem would be solved by #2467 if I understand correctly?

No it would only provide a workaround solution to create a trigger manually. Actually a merge in to a ticket is an update to the ticket so the notification should be triggered by the builtin notification system.

**Comment by mantas** [comment]
> This issue is about the agent not receiving an information that the ticket has been update (which is done technically by a merge).
> 
> So basically you'll never notice that the ticket has changed without having a direct look into it.

So when it adds a note that a ticket received a merge, it should also dispatch a notification to receiver owner?

**Comment by awedor** [comment]
> 
> 
> > This issue is about the agent not receiving an information that the ticket has been update (which is done technically by a merge).
> > So basically you'll never notice that the ticket has changed without having a direct look into it.
> 
> So when it adds a note that a ticket received a merge, it should also dispatch a notification to receiver owner?

Yes, exactly
