### ISSUE TITLE
Prefer HTTP standard header "From" over custom "X-On-Behalf-Of" for impersonation

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#3113]
# Infos:

* Used Zammad version: 3.4.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

We introduced the `X-On-Behalf-Of` header back in 2018 with 6daaecb5fd81a3489d8b3d2ae65a465c6a6ca30d in order to fix #1805 . We were not aware that there is a [HTTP standard header called `From`](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.22) that is designated for the same purpose. @snuggs [let us know via a comment](https://github.com/zammad/zammad/commit/847cf02b498749864bb66ea7ea753343ca524dd2#commitcomment-40517684) below commit 847cf02b498749864bb66ea7ea753343ca524dd2.
Being conform to standards is one of the main goals of Zammad. However, in difference to the `From` head we support User lookup via [`id`,  `login` and `email`](https://github.com/zammad/zammad/blob/5c5c69a7858f63dea4e6a0dd089b8380bbb9d4f3/app/controllers/application_controller/has_user.rb#L49).

We should evaluate:
- if we need to support all of these attributes
- document why we need to support all of these attributes
- if we can/should (soft) deprecate the usage of `X-On-Behalf-Of` in favour of the `From` header

**Comment by snuggs** [comment]
@thorsteneckel LOVE THIS! Was a shot in the dark. Didn't think you'd be interested. I just recently learned of it as well.
It doesn't have too many use cases but WOW is is great when .... you need an EMAIL...FROM another party the request is on behalf of. ;-)
