### ISSUE TITLE
Clarify authentication_check and authorize! before_actions

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#3119]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Warning that `authentication_check` has to run before `authorize!`

### Actual behavior:

* Gibberish error thrown

### Steps to reproduce the behavior:

* Change order of controller before actions to execute `authorize!` before `authentication_check`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by narendran-kannan** [comment]
@mantas  Would like to work on this,  Please assign me!

**Comment by mantas** [comment]
@naresh3599 go for it 👍

**Comment by narendran-kannan** [comment]
Cool!

**Comment by narendran-kannan** [comment]
@mantas In which case, you get gibberish error?

**Comment by mantas** [comment]
@narendran-kannan see steps to reproduce in the issue report ;)

**Comment by lenikadali** [comment]
Hi @mantas 

> Steps to reproduce the behavior:
> Change order of controller before actions to execute authorize! before authentication_check

I would like to understand which controller you're referring to here so that I can reproduce the issue and work on it. Thank you 🙏🏿 

I noticed that most controllers use the form below:

```ruby
prepend_before_action { authentication_check && authorize! }
```

Also: where should the warning appear? In the console when the Rails server is in development mode?

**Comment by mantas** [comment]
Hi @lenikadali 

There's no specific controller in mind. Currently all controllers follow correct order. But we had issues when people mix up the order accidentally. So it'd be good to prevent this.

Raising an error to stop the application is probably good enough.

**Comment by mantas** [comment]
Turns out adding a warning is no-go due to complexity if login/authorization handling in various places.

Instead I'd like to propose to use a `authenticate_and_authorize!` helper to bring some clarity. While it's not much, IMO that's the best we can do here.
