### ISSUE TITLE
In object manager, blank line in object deleted all values for selections

### ISSUE THREAD

**Issue by alveolus** [zammad/zammad#312]
If an object has the format "Select" and a blank line is stored, all values are deleted (Key, Display). Please fix immediately. I have lost all my values today, there were actually many ...

Apart from that, it would be nice to have a blank value, because sometimes you do not want to select a value.

![image](https://cloud.githubusercontent.com/assets/23032204/19730829/bde6fdfc-9b9b-11e6-98c0-0aa3c187e6f6.png)

**Comment by thorsteneckel** [comment]
Hi @alveolus - we'll take a look as soon as possible! Thanks for reporting this.

**Comment by martini** [comment]
Verified.

**Comment by martini** [comment]
Is fixed now https://github.com/zammad/zammad/commit/307b9dc7444c31090ee6d8c4176cd0febb9f8578
