### ISSUE TITLE
User request spec sets up elastic search where it's not used

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#3120]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* `spec/requests/user_spec.rb` sets up elastic search where necessary

### Actual behavior:

* `spec/requests/user_spec.rb` sets up elastic search for all expectations

### Steps to reproduce the behavior:

* run `spec/requests/user_spec.rb`

### Steps to fix

* refactor `spec/requests/user_spec.rb` to separate examples that use search and that don't

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by fliebe92** [comment]
@mantas Maybe this is already done with `c3458133 `. What do you think?

**Comment by mantas** [comment]
@fliebe92 yes, looks like this can be closed

**Comment by fliebe92** [comment]
Completed with c3458133.
