### ISSUE TITLE
Imported LDAP Users can perform Admin Role (configure system) but can not view open tickets / get assigned to them.

### ISSUE THREAD

**Issue by merlinwoff** [zammad/zammad#3127]
### Infos:

* Used Zammad version: version 3.4.x
* Installation method (source, package, ..): packet install as described in https://docs.zammad.org/en/latest/install/centos.html
* Operating system: CentOS 7
* Database + version:
* Elasticsearch version: 7.8.0
* Browser + version: Chrome 84 on Windows 10

### Expected behavior:

* It is expected, that imported LDAP users can get tickets assigned and the overview page of Open Tickets is not empty.

### Actual behavior:

* Tickets can not get assigned to LDAP imported Users (A) nor their ticket overview lists are all empty (B).

### Steps to reproduce the behavior:

A)
1. Sync LDAP Users with Admin and Agent roles.
2. Sign in as super administrator (only NON-LDAP user).
3. Go to overview and select a listed ticket. Try to assign it to a user, but only option is super administrator (only non-ldap user)

B) Empty Overview Lists
1. Sync LDAP Users with Admin and Agent roles.
2. Signin as an LDAP Users with Agent Role.
3. Click on Overview Button in Sidebar
4. All lists are empty, even though as super administrator (NON-LDAP user) there are unassigned & open tickets in the lists.

If I remove the untick agent checkbox in the user settings of an ldap user, the overview button in the sidebar gets hidden. So I think the user role Agent gets assigned to the user correctly.

Also the administrator role (Admin Checkbox Ticked) lets LDAP-Users manage the application and change settings like normal non-ldap admin user.

I think there [this bug](https://github.com/zammad/zammad/issues/1224) was a similar one but it was never resolved.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please provide your LDAP-Server version.
I currently honestly believe that this is a technical question but would like to give you a chance to proove me wrong before hand.
I need the software name and version you're using.

A (sensitive information redacted) configuration of your ldap configuration and the mapped roles would be usefull as well.

**Comment by merlinwoff** [comment]
Thank you for your answer.

We are using a Synology LDAP Server (LDAP-Version 3).

All our employees are assigned as users and our ldap settings on zammad looks as the following:

SETTINGS
NAME | VALUE
-- | --
LDAP Host | ldap://192.168.1.x
Base DN | dc=company
Bind User | uid=Zammad,cn=users,dc=company
Bind Password | ***************
UID | uid
User Filter | (uid=*)
GID | dn
Group Filter | (objectClass=posixgroup)

ROLES
LDAP | ZAMMAD
-- | --
cn=administrators,cn=groups,dc=company | Admin
cn=employees,cn=groups,dc=company | Agent

The roles get distributed to the all ldap users correctly.

**Comment by MrGeneration** [comment]
Please provide a screenshot of the role configuration for these roles: 
* agent
* admin

Edit: And the exact installed version of your ldap server. Synology does work with apps you can install and these have versions.
The LDAP protocol version doesn't help me at this point.

**Comment by merlinwoff** [comment]
Oh I am sorry, that I did not specified the LDAP Server Version.
I am using the Synology LDAP Server 2.4.40-2505 which corresponce to OpenLDAP: slapd 2.4.40

We have nothing changed in the role configurations (Picture 1 & 2).
![Admin_Role](https://user-images.githubusercontent.com/3635664/88284253-67434a00-cced-11ea-9d30-9dac0b2bda39.png)
![Agent_Role](https://user-images.githubusercontent.com/3635664/88284256-67dbe080-cced-11ea-8a08-7f135b331485.png)

**Comment by MrGeneration** [comment]
Thanks for the feedback.
I'm afraid that this indeed is a technical question.

You can find the reason for your issue on the agent role configuration:
![image](https://user-images.githubusercontent.com/6549061/88284693-1da72f00-ccee-11ea-87d0-fca0ee7feb79.png)


Unless you don't manually specify the groups the agent has access to on the user, the user will have no permissions to view tickets in these groups. Instead of giving users permissions to groups to all "new stuff" we do have the standpoint that you as admin should always specify what the user has access to.

When talking about LDAP mapping with roles, I'd suggest providing these rights via the role mapping, because that's what will bring complete benifit of the functionality.

Closing now.
