### ISSUE TITLE
Deactivation of signature does not clear it from groups

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3129]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any 
* Elasticsearch version: any
* Browser + version: Tested on latest Google Chrome (v84.0.4147.89)
* Ticket-ID: #1078120 

### Expected behavior:

When you deactivate a signature, it will also be removed from any group it's configured in.
This causes the agent to no longer be able to get this signature when hitting on "reply" on new articles.

### Actual behavior:

When deactivating a signature, Zammad will not remove it from any group it's configured in.
If you now go to any ticket of that affected group and create a new reply, Zammad will still provide that signature.
You have to manually remove the signature configured in that group to solve that issue.

### Steps to reproduce the behavior:

* go to email -> signatures and deactivate a signature that you know is configured within your group 
    * in default installations this applies to `Users` group and the `default` signature
* go to groups and check your group configuration
    * signature is still there
* now reload and re-check - still there
* go to any ticket in that group and click on reply - you'll see the deactivated signature

![issue-deactivated-signature-still-active](https://user-images.githubusercontent.com/6549061/88379370-1db53680-cda3-11ea-962a-ff02ccd3f5f0.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by romitgithub** [comment]
@MrGeneration There are two ways to solve this issue:

1. Remove signature from the group when it's deactivated, which will automatically clear it from reply text
2. Display signature only when it's in active state. This will still keep the signature associated to the group but won't display in the reply text.

Which one do you prefer/mean here? 

IMO I think it's better to go with `Option 2` because that's more flexible and gives user more control.

**Comment by MrGeneration** [comment]
Maybe I'm understanding wrong, but if I set a signature to inactive and create a new reply in the group in question afterwards, would you think it's valid that we still insert the inactive signature there...?

**Comment by romitgithub** [comment]
No, that's not I mean. If a signature is inactive it won't be inserted in the reply.
