### ISSUE TITLE
Missing redirect after login for oauth2 authorize

### ISSUE THREAD

**Issue by leonardoBrad** [zammad/zammad#3131]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Loading authorize page (/oauth/authorize?response_type=code&....), logging in and then redirected to redirect_url with the authorization code

### Actual behavior:

* Loading authorize page (/oauth/authorize?response_type=code&....), logging in and access to the website. I have to redo the authorize request to get the code

### Steps to reproduce the behavior:

* Perform a oauth login on a logged out browser

**Comment by MrGeneration** [comment]
Please note that the generic oAuth integration is subject to be removed from Zammad and not fully functional.
Please see https://github.com/zammad/zammad/issues/2951 for further information on it's removal.

As we're removing this functionality, I'll be closing this issue. Doesn't make sense to fix bugs for stuff we're removing. :-)
