### ISSUE TITLE
Header links are not responsive

### ISSUE THREAD

**Issue by tmdoit-zz** [zammad/zammad#3133]
### Infos:

*Note: This article was adjusted by @MrGeneration to comply with our template requirenments*

* Used Zammad version: 3.4
* Installation method (source, package, ..): hosted trial
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Brave Version 1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit)

### Expected behavior:

To be responsive.

### Actual behavior:

Header links are not responsive.

### Steps to reproduce the behavior:

Currently you can check the url via mobile: digitaloak.zammad.com/help or in attached image: 
![Screenshot 2020-07-27 at 19 26 43](https://user-images.githubusercontent.com/26081817/88572749-0050c880-d040-11ea-8011-b8ef5986ca30.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Related bits:

- Footer menu

- Footer note

- KB menus preview in Settings

**Comment by wucherpfennig** [comment]
This would have been a good addition to the "mobile friendly" release from 4.0 😉

Can we help somehow to have a responsive menu?

**Comment by MrGeneration** [comment]
Scopes sometimes are limitted and thus don't allow to go all in. 
We have several responsiveness / UI topics which possibly are rabbit holes.

You can do the following:
   * you can contribute enhancements via pull requests
   * if you can't contribute via pull request for any reason but also cannot wait any longer, you could sponsor speeding up this issue, if you want. If that's a way to go for you, please contact us via sales [at] zammad [dot] com.
