### ISSUE TITLE
add full name to tickets

### ISSUE THREAD

**Issue by kernbrand** [zammad/zammad#314]
this is not a bug :)

it'll be really nice if the agent's / customer's name would be added to a note. the avatar is not necessarily helpful (and on a mobile device you have no "mouse over").

**Comment by martini** [comment]
Can you try to tip/click only once on the article. Then you see the agent's / customer's name. Any feedback is welcome!

**Comment by kernbrand** [comment]
hi martin,

yes that works. but assume you have two customers called martin edenhofer. both get the same avatar "ED". or assume your customers (or agents) use images as avatars. if mouse over is available this is not too annoying (even though it's not very clearly), but on a mobile device you have to tap the avatar and leave the ticket page to get the customers name and organization. that's not really straight forward.

**Comment by martini** [comment]
Hi @kernbrand 

now I got it. I'll discuss it with our designer and come back.

 -Martin

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
