### ISSUE TITLE
Update time SLAs escalates tickets with agent response

### ISSUE THREAD

**Issue by quobjoern** [zammad/zammad#3140]
### Infos:

* Used Zammad version:3.1.x
* Installation method (source, package, ..):source
* Operating system:CentOS 7
* Database + version:
* Elasticsearch version:
* Browser + version: 
* Tickets: #1088119

### Expected behavior:

* SLAs on update time should only trigger if there is a message from a customer that did not get a response from an agent within X minutes. The UI states " **update time**  (time between a customer's request and an agent's reaction)"

* The definition of update time is rather vague in other places, but it doesn't seem to make sense to escalate a ticket when customers don't respond fast enough.

### Actual behavior:

SLAs on update time trigger always (regardless of who wrote the last response/message/note).
Looking at the source code (https://github.com/zammad/zammad/blob/develop/app/models/ticket/escalation.rb#L192) it seems like a check is missing to ensure that the last contact came from the customer, e.g. last_contact_agent_at < last_contact_customer_at should be true.

### Steps to reproduce the behavior:

* Create an SLA with update time 
* Create a ticket as customer
* Respond to ticket as agent
* Ticket escalates despite agent response

**Comment by MrGeneration** [comment]
Just to get you right:
You're stating that if a customer creates a ticket and your agent does reply to it, the ticket does instantly escalate?

If so, please ensure that you're running a vanilla Zammad installation without *any code changes or addons* installed. 
Another side note: Zammad 3.1 is terribly outdated and prune to over 10 security issues you should update now.

Please also try to reproduce this on a hosted setup: https://zammad.com/getting-started
If you can reproduce it there, let me know, I'll gladly have a look.

**Comment by quobjoern** [comment]
Yes, that is correct. It escalates also with a response from an agent. Not instantly, but after the time specified in the SLA for update time.

We're running an unmodified version of Zammad.

I tested it on the hosted version (https://qbtest.zammad.com/). Interestingly, I get an escalation time of 45 mins for first response and update time, although I configured an SLA with 29min first response and 16min update time. The result is the same, all my tickets escalate even when the last message is the response from an agent. However, I did only receive an email notification for the ticket in state new, which didn't have a response.

**Comment by quobjoern** [comment]
@MrGeneration Any update on this issue?

**Comment by mantas** [comment]
Hey @quobjoern 

Can confirm the original issue that escalation is bumped & alive after agent's response. I'll look into the compounding escalation time issue as well.

**Comment by mantas** [comment]
Note to self: related to #2579

**Comment by mantas** [comment]
Hey @quobjoern 

Looking at the hosted test instance... Looks like you created the sample ticket ~ 8:30 local time. While business hours defaults start at 9:00. Since escalation takes working hours into account, escalation time seemed off.

Does it sound correct?

**Comment by quobjoern** [comment]
@mantas: You're correct, when I create the ticket within the business hours the escalation time is displayed correctly.

**Comment by rolfschmidt** [comment]
This issue will be reworked. The old behaviour of the Update Time was valid and has actually useful use cases which are needed in the customer services.

There will be a rework of the code with 2 new radio buttons in the SLA configuration of the Update Time.

"on agent response" (naming unclear for now)
This will reintroduce the old behaviour of version 3.6 and also set it again as default. It will provide the functionality to trigger the agent to respond in a certain interval after the last agent response to the customer. 

"on customer response" (naming unclear for now)
This will provide the current functionality as described by @quobjoern. It will reset the update time based on new customer articles without any agent response.

After the rollback of the functionality and the new addition of the radio buttons, all users which want to use the new behaviour which is currently active in version 4.0/4.1 will need to change manually their radio setting to the new option. 

@mantas will inform you guys when the changes are done. We will need to implement this first.
