### ISSUE TITLE
Multiple LDAP server configurations

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#3141]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1082942

### Expected behavior:

* It should be possible to configure multiple LDAP sync sources

### Actual behavior:

* It's only possible to configure one LDAP sync source

### Steps to reproduce the behavior:

* Try to configure a second LDAP

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
MH: Would be cool to define a fallback server so it will be skipped or used based on the availability of the primary server.
