### ISSUE TITLE
Nginx Reverse Proxy Error Centos 8

### ISSUE THREAD

**Issue by jsievertde** [zammad/zammad#3152]
### Infos:

* Used Zammad version: 1596781606.1adc98bf.centos8
* Installation method (source, package, ..): package
* Operating system: CentOS 8
* Database + version: PostgreSQL 10.6
* Elasticsearch version: 7.8.1
* Browser + version: Mozilla Firefox 79

### Expected behavior:

* After install the nginx webserver should be able to access the static files.
* Used is the standard configuration file.

### Actual behavior:

* The access rights for the static files aren't broad enough to give the webserver access to the files.

### Steps to reproduce the behavior:

* Install or reinstall zammad on CentOS 8 and try to use the standard configuration for nginx.

### Steps to mitigate this behavior:
* add the nginx user to the zammad group or own the files with the nginx group. (usermod -aG zammad nginx)
* change the standard rights for files inside the directory `/opt/zammad/public` from 600 to 640 (`find /opt/zammad/public/ -type f -print0|xargs -0 chmod 640`)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
This is actually an issue with the packaging service. We already created an issue for it: https://github.com/crohr/pkgr/issues/165

**Comment by jsievertde** [comment]
Okay sorry that i didn't found that already while i was looking for a preexisting issue.

**Comment by thorsteneckel** [comment]
No worries, thanks for reporting! Probably will help the next one stumbling over it. You might want to ask in the other issue about the state.

Just for the record: We already had a report over at the community: https://community.zammad.org/t/zammad-3-2-0-package-for-centos-8-incorrect-permissions-for-zammad-public-folder/3589/2
