### ISSUE TITLE
Broken Debian 9 Package from packager.io

### ISSUE THREAD

**Issue by spacecodeit** [zammad/zammad#3153]
Hello,

the Debian 9 Repository from packager.io has no Release file since a few days.

```
# apt-get update
Ign:2 https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 9 InRelease
Err:3 https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 9 Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 9 Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration detail
```

**Comment by MrGeneration** [comment]
Sorry but this is a technical question.
The better place, for the next time, would be the community.

Apart from the issue template being missing.
Release and InRelease were, as far as I can remember, never tags that were used.
Please follow the official guide from our docs to solve this issue: https://docs.zammad.org/en/latest/install/debian.html#for-debian-9


Closing.

**Comment by thorsteneckel** [comment]
Hey @spacecodeit - I guess you're talking about the `develop` branch because [the last `stable` commit was build successfully 10 days ago](https://packager.io/gh/zammad/zammad/refs/stable). However, [the `develop` build fails since 7 days](https://packager.io/gh/zammad/zammad) 😱 we'll get in contact with packager.io and resolve this issue. Next time please provide the the mandatory issue template or refer to non-software bug issues to the [community board](http://community.zammad.org/).

**Comment by spacecodeit** [comment]
Hey @thorsteneckel - we are using the stable branch. The repo is setup as explained in the docs at https://docs.zammad.org/en/latest/install/debian.html#for-debian-9
The first time we saw the issue was last Friday (14.08.2020).

```
# cat /etc/apt/sources.list.d/zammad.list
# This file was generated by dl.packager.io

deb https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 9 main
```

**Comment by thorsteneckel** [comment]
Hey @spacecodeit - right, my bad. Would you mind creating a thread over at the community? Non-bug issues create a lot of noise for those watching the repository. We'll address the packager.io issue and help you out in the community as soon as we find the time.

JFI: We're currently not aware of any issues with installations of the `stable` branch.
