### ISSUE TITLE
Generated Raw EML's for agent responses are incorrect. 

### ISSUE THREAD

**Issue by AdamC1228** [zammad/zammad#3154]
### Infos:

* Used Zammad version:   3.4.0-1596454487.6ef2d854.centos7.x86_64
* Installation method (source, package, ..):   CentOS RPM
* Operating system:   CentOS Linux release 7.8.2003 (Core)
* Database + version:   Postgresql 9.2.24-4.el7_8.x86_64
* Elasticsearch version:   7.8.1
* Browser + version:   Firefox 79.0 & Chrome 84.0.4147.125

### Expected behavior:

*Raw email matches the format of the Email displayed in Zammad regardless of the email client. 

### Actual behavior:

*Generated raw email has characters replaced/added when viewed in Outlook. Overall message is still readable and not significantly compromised. The email received by the the customer is **correctly** formatted. Additionally, this behavior does not occur when viewed in Thunderbird. 

**However**, when the user reply's to our response and that response is viewed as a raw email in outlook, the formatting of our response contained in the user's reply is correct.  

Thunderbird: 68.11.0
Outlook: 1908 (16.0.11929.20934)

**Sent Response:**
![Capture](https://user-images.githubusercontent.com/13957003/90404012-c9cf0200-e06f-11ea-8138-ae32301580d2.PNG)

**Opened Sent Response as Raw eml in Outlook:**
![Capture2](https://user-images.githubusercontent.com/13957003/90404016-c9cf0200-e06f-11ea-8c00-50a2a3ddbd2d.PNG)

**Customer Reply Opened as Raw eml in Outlook:**
![Capture3](https://user-images.githubusercontent.com/13957003/90405265-837aa280-e071-11ea-9c74-d086eaf72101.PNG)

### Steps to reproduce the behavior:

*Send reply to a ticket. 
Click on said response and view the raw formatted email.
Open the eml file in Outlook.
Repeat for responses. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please provide additional information on your channel configuration:
* Used MTA to send and receive emails (provide both if sending and receiving MTAs are different)

**Comment by AdamC1228** [comment]
Currently we use Exchange 2016 as our Transport Authority and have DavMail 5.5.1-1.2 setup as the bridge between Exchange and Zammad.

**Comment by AdamC1228** [comment]
Additionally, the Agents response email when you open the Raw EML file that Zammad provides shows a lot of encoded characters for newlines. See the code excerpt below. 

Note: I have CENSORED the names and sensitive information. 

`Subject: RE: [Ticket#603655] Outlook issues in Citrix.
Mime-Version: 1.0
Content-Type: multipart/mixed;
 boundary="--==_mimepart_5f3972ed6d97e_728e2af945f967d08220e5";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Organization: CENSORED
X-Powered-By: Zammad - Helpdesk/Support (https://zammad.org/)
X-Mailer: Zammad Mail Service


----==_mimepart_5f3972ed6d97e_728e2af945f967d08220e5
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5f3972ed6d43c_728e2af945f967d0821859";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_5f3972ed6d43c_728e2af945f967d0821859
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Hi CENSORED,=0D
=0D
Please open Excel first and follow the prompts to activate and sign in. T=
hat should correct the outlook crashing.=0D
=0D
Thanks,=0D
CENSORED.=0D
=0D
----=0D
CENSORED=0D
Extension:=C2=A0 CENSORED=0D
After Hours:=C2=A0 CENSORED=0D
=0D
 Email: helpdesk@CENSORED.com - Web: [1] https://helpdesk.CENSORED.co=
m=0D
=0D
----=0D
=0D`


I have applied all pending system updates and restarted the server. We are now running the following versions of the important software and the issue persists:
Zammad:   zammad-3.4.0-1596781606.1adc98bf.centos7.x86_64
Elastic Search:   elasticsearch-7.9.0-1.x86_64

**Comment by Marco-Total** [comment]
Hello,

we have the same issue:

```
Hinweis: Die E-Mail-Adresse des Absenders ist nur für den Empfang einfacher Mitteilungen ohne Signatur und/oder Verschlüsselung geeignet.

Hinweis: Die E-Mail-Adresse des Absenders ist nur für den Empfang einfacher Mitteilungen ohne Signat=r und/oder Verschlüsselung geeignet.
```

**Comment by MrGeneration** [comment]
Locking issues to reduce "me toos".
It's not helping and @Marco-Total 's comment looks out of issue scope. 

If you have technical questions, please head over to the community at https://community.zammad.org

**Comment by t-shehab** [comment]
We haven't received any complaints in this regard in the past few years. Closing for now.
