### ISSUE TITLE
Default charset for email channel changed?

### ISSUE THREAD

**Issue by bjornskovlund** [zammad/zammad#3155]
### Infos:

* Used Zammad version: 3.4.x
* Installation method (source, package, ..): Kubernetes (via Helm)
* Operating system: Docker
* Database + version: PSQL 11.1-v1
* Elasticsearch version: 6.5.3
* Browser + version: N/A

### Expected behavior:

* Correct encoding

### Actual behavior:

* Faulty encoding

### Steps to reproduce the behavior:

* After upgrading from 3.1.x to 3.4.x, we're experiencing problems with encoding of inbound emails.
* Most emails are correct, but if no charset is defined in the raw email, it seems the default has changed from something that works for us, to something that doesn't.
* From one partner, we receive emails with no charset definition, which previously did fine with æøå, but now they're presented as ćřĺ instead.
* Is it correct that this could stem from this commit? https://github.com/zammad/zammad/commit/2ca17b913fc99bde48a7f38c7f3879acad950c61

**Comment by MrGeneration** [comment]
Please provide samples and if available tracebacks.
Otherwise this is impossible to qualify for a bug or not.

Please note that if this is a technical question, the repository of Zammad is the wrong place.
The better place for technical questions is the Community: https://community.zammad.org

**Comment by MrGeneration** [comment]
As I haven't heard back and can't reproduce your described issue, I'll be closing this issue.

If you require technical assistance, please consult the Zammad community: https://community.zammad.org
In case you require commercial grade support, our support contracts may be of interest: https://zammad.com/pricing#selfhosted
