### ISSUE TITLE
Notification and assignment wrong when changing ownership

### ISSUE THREAD

**Issue by Lightyear76** [zammad/zammad#3158]
Hi!

When changing the group of a ticket, the correct members of this group are not notified. In addition, wrong agents are assigned.

### Infos:

* Used Zammad version: 3.4.0
* Installation method (source, package, ..): package
* Operating system: Centos 7
* Database + version: mariadb 5.5.65-1
* Elasticsearch version: 5.6.16-1
* Browser + version: Firefox 79

### Expected behavior:

When changing the group of a ticket, only the members of the selected group are notified. The agents are also assigned to this group.

### Actual behavior:

When changing the group of a ticket, the correct members of this group are not notified. In addition, wrong agents are assigned.

### Steps to reproduce the behavior:

Only the assigned group of the ticket needs to be changed

Yes I'm sure this is a bug and no feature request or a general question.

Best regards Olaf

**Comment by MrGeneration** [comment]
Can you please clarify what you mean by "wrong agents are assigned" ?
I just want to ensure that wording doesn't send me into the wrong direction.

**Comment by MrGeneration** [comment]
As I haven't heard back and thus am unable to reproduce the issue you tried to describe, I'll be closing this issue.

If you require technical assistance, please consult the Zammad community: https://community.zammad.org
In case you require commercial grade support, our support contracts may be of interest: https://zammad.com/pricing#selfhosted
