### ISSUE TITLE
greyed out Avatar is not displayed correctly in the caller log

### ISSUE THREAD

**Issue by Vogelkoje** [zammad/zammad#3159]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any (verified on current Google Chrome)
* Ticket: # 1078737

### Expected behavior:

* Avatars should be displayed in the call logs, even if they are larger than the container.

### Actual behavior:

* If avatars are larger than the container *and* inactive, they are not displayed correctly in the call logs

### Steps to reproduce the behavior:

* Set up the telephone integration so that call logs are available.
* Users should have avatars
* Users with avatars should be involved in the phone movements.
* Avatars must be larger so that they do not fit into the range
* if the call you added is a missed call, ensure to mark it as "read" so the avatar get's greyed out
   * the issue only is visible if the avatar is greyed out

### Solution:

* Adapting the background to its environment
     `background-size: cover;` to `.table tr.is-grayed-out .avatar`

![ticket1078737_cti-avatars-broken](https://user-images.githubusercontent.com/65288963/90742256-b1f5b900-e2cf-11ea-89a9-23de19c7d7b0.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
JFI: I added some information to help developers understand the scope.
This only affects entries which are no longer active. 

(Switching between active / inactive (so using the tick on the left in the caller log) shows that quite well)
