### ISSUE TITLE
Rename 3rd Party Integration Logins

### ISSUE THREAD

**Issue by idominiki** [zammad/zammad#3161]
Hello,

I use Zammad v. 3.4 and use SAML Login.

Is it possible to rename the Login Buttons? Would be great for our user experience.
<img width="594" alt="Bildschirmfoto 2020-08-24 um 08 01 16" src="https://user-images.githubusercontent.com/62521486/91009159-43bb3a00-e5e0-11ea-82d5-06ec11d5f2f8.png">

**Comment by MrGeneration** [comment]
Sorry, but this is a technical question and thus the wrong place.
Please use the Zammad community (https://community.zammad.org) for technical questions or feature requests.

To your question: No it's not without code change.
