### ISSUE TITLE
E-mail generated by trigger is sent to the 'from' address when 'reply-to' is given

### ISSUE THREAD

**Issue by Monikowski** [zammad/zammad#3166]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): source
* Operating system: ubuntu 18.04
* Database + version: PostreSQL 12.3
* Elasticsearch version: 7.7
* Browser + version: any

### Expected behavior:

* A trigger (which has Customer as it's e-mail recipient and is triggered on an update of a custom boolean field) runs and sends an e-mail to the address given in 'reply-to' field in ticket

### Actual behavior:

* The e-mail is sent to the 'from' address

![obraz](https://user-images.githubusercontent.com/47703657/91307685-934f6080-e7ae-11ea-9456-1ec30391c6d4.png)

### Steps to reproduce the behavior:

* Create a trigger that sends an e-mail to the Customer
* Create a ticket by e-mail with a reply-to header
* Activate the trigger

Yes I'm sure this is a bug and no feature request or a general question.
https://github.com/zammad/zammad/issues/203 from what I understand, here it's made so that replying to 'customer' in the trigger will actually target the 'reply-to' mail, right? If it's not supposed to do that, how do I make my triggers e-mail the 'reply-to' address?

**Comment by MrGeneration** [comment]
Please provide your configured setting of "Sender based on Reply-To header" that can be found in admin settings -> E-Mail (Channel) -> Settings tab.

[ reference https://admin-docs.zammad.org/en/latest/channels/email/settings.html ]

**Comment by Monikowski** [comment]
![obraz](https://user-images.githubusercontent.com/47703657/91310118-bf201580-e7b1-11ea-9544-b91c7f74589c.png)

**Comment by Monikowski** [comment]
Okay, so this is fixed

I only found this setting later and didn't think it would do much - I thought it would redirect the e-mails sent on already existing tickets (which obviously didn't happen)

After creating new tickets, however, I see that it replaces the 'from' e-mail completely, which does pretty much what I wanted anyway (as I don't really need to store the 'from' e-mail).

Thank you for your time
