### ISSUE TITLE
Display origin url from tweet/facebook post

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#317]
Tickets created by the twitter channel should include the origin url to the tweet. Same for facebook posts.

**Comment by martini** [comment]
Implemented https://github.com/zammad/zammad/commit/f8a75f02b8cc08156bcc520a025364e5f751b73e

**Comment by martini** [comment]
<img width="635" alt="screen shot 2016-10-28 at 17 21 58" src="https://cloud.githubusercontent.com/assets/110226/19812317/595033c2-9d35-11e6-9532-d1320ee28609.png">
