### ISSUE TITLE
Print statistics

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#3170]
Hello,

we are interested in zammad. At the moment we use OTRS and print every week out statistics for our shop floor bord.
In zammad I created a statistic for new and closed tickets by day and want to print it. It is possible to print the statistic from azmmad or is it not possible? I've created a screenshot and printed the screenshot. It's ok but not perfect :)

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question.
The Zammad community is the better place for enhancement requests and technical questions, this repository is for bug reports only. You can find the community here: https://community.zammad.org


We do so to help our developers focus on fixing bugs and implementing planned features.
With over 2.200 stars, those kind of issues also cause a lot of noise for everyone involved.

Closing.
