### ISSUE TITLE
Deleting tickets should also remove tabs

### ISSUE THREAD

**Issue by vic-t** [zammad/zammad#3173]
Infos:

    Used Zammad version: 3.4 (current)
    Installation method (source, package, ..): Installer
    Operating system: Ubuntu 18.04
    Browser + version: Firefox

It's possible to delete tickets using the scheduler. This does not seem to affect the ticket history on the left hand side, they are still mentioned there although clicking them will generate an error. 

What's more, for existing tickets, you can just click the X button to remove them from the history. When you try the same with a ticket that's no longer available, you are asked to confirm the deletion. 

It's really not an urgent or important issue but I guess it could use some improvement. 

When I say "history", I'm speaking about this part in the interface: 

![grafik](https://user-images.githubusercontent.com/13408858/91665644-6c1ec900-eaf7-11ea-95f8-3cc1a25e96c6.png)

**Comment by MrGeneration** [comment]
Please adjust your first article to contain a filled issue template which we provide upon the issue creation screen.
Please also ensure that you're not talking about this issue:
https://github.com/zammad/zammad/issues/2960

Because I'm currently not sure if you're talking about linked tickets or other references.

**Comment by vic-t** [comment]
I'm new with Zammad and don't yet know all the terminology. But I'm pretty sure this is not about linked tickets. I hope the image clarifies things, otherwise I'm happy to provide more info.

**Comment by MrGeneration** [comment]
Okay, so you're talking about Zammads tabs.
User, Organisations and Tickets do have Histories this is why I was asking so directly.

So what you imply is that the tab should be removed upon ticket removal but isn't.
Thanks for clarifying that!

**Comment by rolfschmidt** [comment]
This should already happen since Sep'2020

https://github.com/zammad/zammad/commit/3fb9b05027b9efa2cacc5e3d2a5228da74523773

https://github.com/zammad/zammad/blob/92b2f72fb8eb36d3951d15973dbe0055a2cf7a37/app/models/concerns/has_taskbars.rb#L20
