### ISSUE TITLE
Editing from users for agents

### ISSUE THREAD

**Issue by RohwerderGmbH** [zammad/zammad#3175]
Hello,

I created a topic before posting here: https://community.zammad.org/t/editing-from-users-but-disallow-set-admin-status/5186

The problem is, that a agent can't setting userdetails like Organisation, telephone or someone else. That's only possible if I setting the area admin.user for the agents. But then the agents can set herself as full admin. 

Mr.Generation said normally it should be possible that agents can setting user details. Sure it's not helpful that agents can edited admin users, but other users without admin status should be possible to edit. 

I hope you understand me. :)

**Comment by MrGeneration** [comment]
Sorry but this is a technical question which I couldn't answer on the community yet (for time reasons).
Please do not create technical questions or feature requests on this repository.

If you require commercial grade support, you can find more information on that topic here: https://zammad.com/pricing#selfhosted
