### ISSUE TITLE
Set Groups for Customers

### ISSUE THREAD

**Issue by simonkulessa** [zammad/zammad#318]
Hi there,

by now a customer could create a ticket to every groups available in zammad. Is it possible to change this behaviour? So that an agent can manage the groups available for a customer?

Thanks in advance
Simon

**Comment by Pupp3tm4st3r** [comment]
Okay - I just saw, that it is possible to select the groups available for the channel "web" - But I need to manage, which customer can create a ticket in which group.

**Comment by thorsteneckel** [comment]
Closing in favor of #1262 - which will be used for the "dynamic forms" functionality.
