### ISSUE TITLE
`501 5.1.7 Bad sender address syntax` in SMTP username with @domain.tld part

### ISSUE THREAD

**Issue by fooness** [zammad/zammad#3181]
### Infos:

* Used Zammad version: 3.4.0-1598623256.b6eccc11.bionic
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04 LTS
* Database + version: postgresql 10+190ubuntu0.1
* Elasticsearch version: 7.9.1
* Browser + version: Firefox 80.0.1, Chromium 87.0.4242.0

### Expected behavior:

* set up and configure `Email Notification` via own outgoing SMTP server

### Actual behavior:

* `501 5.1.7 Bad sender address syntax `

### Steps to reproduce the behavior:

* seems the problem are usernames with `@some.domain` part

Yes I'm sure this is a bug and no feature request or a general question.

Here’s the corresponding excerpt from the `production.yml` log file.

```
I, [2020-09-07T14:03:51.159686 #23987-47053985835740]  INFO -- : Started POST "/api/v1/channels_email_notification" for xxx.xxx.xxx.xxx at 2020-09-07 14:03:51 +0000
I, [2020-09-07T14:03:51.162477 #23987-47053985835740]  INFO -- : Processing by ChannelsEmailController#notification as JSON
I, [2020-09-07T14:03:51.162516 #23987-47053985835740]  INFO -- :   Parameters: {"adapter"=>"smtp", "options"=>{"host"=>"post.some.domain", "user"=>"something@some.domain", "password"=>"[FILTERED]", "port"=>"587"}, "email"=>"me@localhost"}
I, [2020-09-07T14:03:51.227310 #23987-47053985835740]  INFO -- : Completed 200 OK in 65ms (Views: 0.2ms | ActiveRecord: 0.9ms)
```

**Comment by MrGeneration** [comment]
Sorry but this is a technical question and not a bug.
Zammad provides the exact error message from your mail server.

Bad sender address syntax usually is a issue with inccorect provided mail addresses.
If you still need help on this, please consult the Community at https://community.zammad.org

If you require business grade support, you can find more information on our support contracts here: https://zammad.com/pricing#selfhosted

**Comment by sergiosgc** [comment]
Zammad violates SMTP. When sending the command MAIL FROM, the email address should be enclosed with \<\>. The correct SMTP command is:
 MAIL FROM: \<john@example.com\>
The one Zammad sends is:
 MAIL FROM: john@example.com

Some mail servers refuse this protocol violation, namely Postfix.

**Comment by MrGeneration** [comment]
> Some mail servers refuse this protocol violation, namely Postfix.

That's odd. My Postfix handles over 80k mails from Zammad instances per day.
Also you're abusing a technical question issue with a different topic.
