### ISSUE TITLE
regular customers can see custom overviews created for VIP users

### ISSUE THREAD

**Issue by alireza-salehi** [zammad/zammad#3182]
### Infos:

* Used Zammad version: 3.4.0
* Installation method (source, package, ..): yum/package
* Operating system: CentOS 7.8.2003
* Database + version: PostgreSQL 9.2.24
* Elasticsearch version: 5.6.16
* Browser + version: Chrome Latest

### Expected behavior:
when create an "overview" and select "ONLY AVAILABLE FOR USERS WITH SHARED ORGANIZATION"="YES"
we expect that only users with "VIP" = "YES" see that overview
*
### Actual behavior:
every other user in that organization can see that overview.

### Steps to reproduce the behavior:
1. create an organization
2. join 2 users in that organization
3. mark one of the users as VIP
4. create an overview and check "ONLY AVAILABLE FOR USERS WITH SHARED ORGANIZATION"="YES"
5. log in with none VIP user. you can see overview created in step 4
*

**Comment by MrGeneration** [comment]
Sorry but this looks like a technical question and not a bug.
Shared organizations technically have nothing to do with VIP users.

If you still need help on this topic, please consult the Community at: https://community.zammad.org

If you require commercial grade support, you can learn more about our support contracts at https://zammad.com/pricing#selfhosted
