### ISSUE TITLE
API endpoint api/v1/ticket_articles/by_ticket doesn’t work as expected

### ISSUE THREAD

**Issue by Cybernisk** [zammad/zammad#3183]
### Infos:

- Used Zammad version: 3.3.0-19
- Used Zammad installation source: docker
- Operating system: CentOS

### Expected behavior:

- HTTP 200. Show me the output

### Actual behavior:

- HTTP 401 Not authorized

### Steps to reproduce the behavior:

- Create a personal API token and use it for all request below
- GET a ticket information from /api/v1/tickets/119781?expand=true -> HTTP 200
- Take any of the article_ids from the previous output
- GET an article from /api/v1/ticket_articles/369661 -> HTTP 20
- Trying to get the list of articles from /api/v1/ticket_articles/by_ticket/119781 -> HTTP 401

Can’t understand why I can’t get articles from the ticket_articles/by_ticket endpoint, but can get them one-by-one from ticket_articles/<id>? Any ideas?

**Comment by MrGeneration** [comment]
Sorry but this is a technical question and not a bug.

If you still need help on this, please consult the Community at https://community.zammad.org
I guess this belongs to this community post: https://community.zammad.org/t/api-endpoint-api-v1-ticket-articles-by-ticket-doesnt-work-as-expected/5224

If you require business grade support, you can find more information on our support contracts here: https://zammad.com/pricing#selfhosted

**Comment by Cybernisk** [comment]
@MrGeneration 
How do you divide that this is not a bug report? As for me: Bug - the product works not as expected or documented. 
Question - asking how something should work or asking the detailed information
The API is not working as described in the documentation => I guess this is a bug.

**Comment by MrGeneration** [comment]
Because I can't reproduce this and it works as it should.
Please don't create github issues for community posts just because you don't receive a fast reply on the community.

Bumping posts actually moves it down my list (because I reply to the oldest pending, so it's nothing personal!)

![image](https://user-images.githubusercontent.com/6549061/92399635-e9b38c00-f12a-11ea-8903-4af7e8af71fb.png)

**Comment by Cybernisk** [comment]
I'm sorry. I really appreciate your time and thank you for the reply @MrGeneration . 
I will do more tests and update the community ticket if I will get any new information =/
