### ISSUE TITLE
Allow Gsuite spam/phishing headers to filter mails

### ISSUE THREAD

**Issue by nielsek** [zammad/zammad#3187]
In Gsuite it's possible to enable these headers for emails detected as spam / phishing:

`X-Gm-Spam`

`X-Gm-Phishy`

Values can be 1 or 0.

Would be nice if they could be added to the same list as https://github.com/zammad/zammad/issues/376#issuecomment-394819123 so it would be possible to use them for filters.

cc: @martini

**Comment by MrGeneration** [comment]
Please don't mention Zammad members out of the blue just to raise awareness.
Please note that this is a feature request and, in Zammad terms, Github is the wrong place for these.

Please create a topic over at the Community at https://community.zammad.org.
I'll be closing this issue, sorry.

**Comment by nielsek** [comment]
Alright, I was just following his comments in the other issue:

> In case if there is more need, also from other users. Just reopen or even better, create a new issue. Thanks!
