### ISSUE TITLE
Unable to create inital admin user via web installer

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3189]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Able to create initial admin user via web installer

### Actual behavior:

* I can't create inital admin user via web installer:

![image](https://user-images.githubusercontent.com/110226/92724598-34234b80-f36b-11ea-85af-adb7251a3a0a.png)

After small investigation it went out that password policy is applied but not shown in UI (only unable to create user):

![image](https://user-images.githubusercontent.com/110226/92724662-4c936600-f36b-11ea-9593-4d64218c8d61.png)

### Steps to reproduce the behavior:

* setup zammad and try to create inital admin user via web interface

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
In my opinion not a bug, but enhancement to provide a meaning full error message.
I believe that there was an issue regarding this and also am sure Mantas was working on that.

At least meaning full error message had been implemented already:
https://github.com/zammad/zammad/commit/40148392426f626cb779c76d6bdda0f67bd6069d#diff-4e05ad0d64e6100656b63ad1e78f32c5R1036-R1046

So what basically seems to be missing is an error message above the password field or as a toast message.

**Comment by mantas** [comment]
Huh, I did work on that. As well as issue in screenshot bellow. Maybe something went wrong during rebasing? I'll dig into this :|

![Screenshot 2020-09-10 at 14 54 47](https://user-images.githubusercontent.com/36944/92725990-9aad6700-f375-11ea-828a-37bd25d0458a.png)

**Comment by mantas** [comment]
@martini did you bump into the original issue in `3.4` release or `develop`? Looks like `develop` has some issues with error messages (see my screenshot), but the original issue is already fixed?

**Comment by martini** [comment]
@mantas I found this behavior in Zammad 3.4 (current stable) branch.

**Comment by martini** [comment]
I can confirm, that the error messages on signup are not shown correctly (in current develop):

![image](https://user-images.githubusercontent.com/110226/93475353-ca6de900-f8f8-11ea-9fb4-099011ce6371.png)

And also not shown correctly for new created admins (in current develop):

![image](https://user-images.githubusercontent.com/110226/93476192-cee6d180-f8f9-11ea-9831-53265525f5bc.png)
