### ISSUE TITLE
E-Mail Forwarding to an address in an other group behaves unexpectedly

### ISSUE THREAD

**Issue by crigertg** [zammad/zammad#3193]
### Infos:

* Used Zammad version: 3.4.0
* Installation method (source, package, ..): source
* Operating system: Ubuntu 18.04
* Database + version: PostgreSQL 11.9
* Elasticsearch version: 7.6.1
* Browser + version: any

### Expected behavior:

When forwarding a Ticket to an email address used in an other group than the current I'd expect that:
* the Ticket is shown in the group of the recipient's address (automatic reassign?)
* a warning is printed that the ticket should reassigned instead of being forwarded

### Actual behavior:

The mail is sent without a warning and the ticket remains assigned to the current group/assignee. The group which is assigned to the recipient's address is not notified. 

### Steps to reproduce the behavior:

* have two E-Mail addresses assigned to two seperate groups (a@acme.com in Group A, b@acme.com in Group B)
* send a Mail to a@acme.com -> Ticket is created in Group A
* in group a click forward an as recipient's address input b@acme.com; update

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This isn't a bug, but rather -if anything beside of "working as designed"- rather an enhancement.
What do you think, @thorsteneckel

**Comment by thorsteneckel** [comment]
Yes. The described use case should be done by moving or splitting the ticket that should get assigned to Group B.
