### ISSUE TITLE
Granular admin permission for google channel is missing

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3194]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on latest Google Chrome

### Expected behavior:

When providing granular rights, an administrator would like to have the possibility to provide access to "Google Channel" without providing access to the whole admin backend.

### Actual behavior:

You can't provide only access to the Google channel.
This came to my attention during my role refactor.

As the option is missing, I was expecting `admin.channel_email` to be the correct part for this, but it wasn't.
![image](https://user-images.githubusercontent.com/6549061/92949935-30232680-f45c-11ea-8bb4-38a816bdafc1.png)

Personally I'm not too sure if deviding between channels like `email`, `google` or `microsoft` would be really required or relevant because technically it's the same thing underneath... 🤷‍♂️
![image](https://user-images.githubusercontent.com/6549061/92949982-403b0600-f45c-11ea-8671-cbb329ab0d12.png)

### Steps to reproduce the behavior:

* provide only `admin.channel_email` to any user via role
* take over the session of the affected user

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Permission admin.channel_google already exists but it is not possible to create filters if you only have google permissions. 

![grafik](https://user-images.githubusercontent.com/5445062/133265574-7bbf7f68-a22c-48f2-81e5-8657d700f032.png)
