### ISSUE TITLE
Inconsistent granular agent permissions

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3195]
### Infos:

* Used Zammad version: 3.4 and 3.5 develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on latest Google Chrome v85

### Expected behavior:

If Zammad provides more than one permission for a specific topic (e.g. "chat"), setting the sub permission allows less.

### Actual behavior:

Zammad provides to permissions:
   * chat
   * chat.agent

You can set both permissions in any constellation - it doesn't matter. 
This is why I believe that `chat` actually is supposed to be a deactivated setting, just like `cti` and `knowledgebase`:

 - https://github.com/zammad/zammad/blob/3fb9b05027b9efa2cacc5e3d2a5228da74523773/db/seeds/permissions.rb#L353-L355

vs

* https://github.com/zammad/zammad/blob/3fb9b05027b9efa2cacc5e3d2a5228da74523773/db/seeds/permissions.rb#L368-L370
* https://github.com/zammad/zammad/blob/3fb9b05027b9efa2cacc5e3d2a5228da74523773/db/seeds/permissions.rb#L393-L395

![inconsistent-user-permissions](https://user-images.githubusercontent.com/6549061/92965655-75545200-f476-11ea-9c04-0d3a48b79cf3.gif)

### Steps to reproduce the behavior:

* open your role configuration and have a look at `chat` and `chat.agent` permission
* now have a second look on cti and knowledge base permissions

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
I checked the code base and the permission `chat` is never checked but only `chat.agent` – as you described/expected. Therefore the `chat` permission should not be selectable.
