### ISSUE TITLE
status change via "pending till" delayed

### ISSUE THREAD

**Issue by seal61** [zammad/zammad#3197]
### Infos:

* Used Zammad version: 3.1.x 
* Installation method (source, package, ..): source
* Operating system: debian 9
* Database + version: postgresql
* Elasticsearch version: don't know how to check...
* Browser + version: firefox 80.0.1 (64-Bit)

### Expected behavior:

* zammad should change the status of a ticket to another status directly after pending time reached

### Actual behavior:

* zammad does change the status at least 15 minutes too late

### Steps to reproduce the behavior:

* created 2 new status using rails console and the following commands:

```
Ticket::State.create_or_update(
     name: 'account expiring',
     state_type: Ticket::StateType.find_by(name: 'open'),
     created_by_id: 1,
     updated_by_id: 1,
   )

Ticket::State.create_or_update(
     name: 'account tracking',
     state_type: Ticket::StateType.find_by(name: 'pending action'),
     ignore_escalation: true,
	 next_state: Ticket::State.find_by(name: 'account expiring'),
     created_by_id: 1,
     updated_by_id: 1,
   )
```

* and enabled the status for use at GUI / added pending till boxes / functionality as describes here: https://docs.zammad.org/en/latest/admin/console/working-on-tickets.html
* at 22:00 I set an existing ticket to status "account tracking" with “pending till” information to 15 minutes in the future, so the ticket should change at 22:15
* zammad does set the ticket status to "account expiring" at around 22:30 - 15 minutes too late. 

Yes I'm (quite) sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This is due how Zammads schedulers are working.
By default, there's a delay of up 15 minutes which usually isn't an issue with e.g. pending close tickets.

However, if you require this particular scheduler job to run more often than every `900` seconds, you can use the following command within a rails console:

`Scheduler.find_by(name: 'Process pending tickets').update(period: 30)`

**Warning:** This may potentially lead to performance issues and may degrade your application stability.
Use with care and monitor your system properly after applying.

----

Edit: Also please note that Zammad 3.1 is quite old by now and prune to security issues. You should update asap.
