### ISSUE TITLE
Unable to open ticket/content not loading

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3198]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Being able to open any ticket

### Actual behavior:

* Unable to open ticket if ticket was opened in Zammad 3.3 (or lower) with an upgrade in the meantime to Zammad 3.4 and higher without relogin of the user.

### Steps to reproduce the behavior:

* install Zammad 3.4
* login and open a ticket
* upgrade to Zammad 3.5
* reload Zammad Web App
* ticket will not get loaded (content is empty)

**Comment by thorsteneckel** [comment]
Implemented with the commits above 👏  closing now.
