### ISSUE TITLE
On-the-fly update of the docker image

### ISSUE THREAD

**Issue by Pupp3tm4st3r** [zammad/zammad#320]
Hi,

I wanted to know if one can update the docker image for a running zammad instance? Or do I have to save the database and files somehow and then create a new container? Or is it possible to just update the underlying image so the container starts with all settings, users and so on but with an updated image?

Thanks in advance and best regards
Simon

**Comment by dnauck** [comment]
See also https://github.com/zammad/docker/issues/3

**Comment by thorsteneckel** [comment]
Moved to the Docker repo.

**Comment by monotek** [comment]
I have a docker-compose version with persistent storage, which is automaticly updated on restart ready @

https://github.com/monotek/zammad-docker-compose

please test :-)

**Comment by hhoechtl** [comment]
I modified the compose environment of @monotek to be upgradable via docker image so that your database won't be dropped if you need to rebuild the container, as it's intended by docker that your software version belongs to an image version.

https://github.com/1drop/zammad-docker-compose
