### ISSUE TITLE
Zammad does not create a ticket for the first mail of unknown user

### ISSUE THREAD

**Issue by lafiel** [zammad/zammad#3200]
Hi all,

just a bit of background info.
We just migrated from an old server (Ubuntu 16.04 LTS) to new (Ubuntu 20.04 LTS) one without updating Zammad.
One mailbox had an issues with this, because the mail server only supports TLS 1.0  and because Ubuntu 20.04 has stricter security settings hence send / receive failed.
An extra openssl.conf for Zammad, where TLS 1.0 is allowed, worked as a workaround (see attachment - last bit).

The issue we have now is, that Zammad does not create new tickets of new mails from unknown users for this mailbox. 
Hence we've tried an upgrade to 3.4 but still the same problem.

While this works just fine with other mailboxes which don't have the  TLS 1.0 mail server problem. The interesting thing is that Zammad always sends a reply mail back to the sender and the agents get their notification mail for the new ticket with a link in it which then fails to open (but there's no logging of it). 
But once the user is known (after the first mail) it works properly here too.

### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): source
* Operating system: ubuntu 20.04 lts
* Database + version: Server version: 10.3.22-MariaDB-1ubuntu1 Ubuntu 20.04
* Elasticsearch version: 5.6
* Browser + version: Firefox 80.0.1

### Expected behavior:

* All mails sent to the mailbox will create a ticket in zammad.

### Actual behavior:

* See background info above first.
* For the TLS 1.0 mailbox the first mail of an unknown user does not create a ticket but a second mail works.

### Steps to reproduce the behavior:

* Mail server with TSL 1.0 only
* Create a openssl.conf and export the filename as envval for the zammad user (see attachments) 
* Send mail from an unknown source to Zammad
* Send a second mail from a known source to Zammad

[production_log_sample.txt](https://github.com/zammad/zammad/files/5237618/production_log_sample.txt)
[openssl.zammad.txt](https://github.com/zammad/zammad/files/5237629/openssl.zammad.txt)

**Comment by MrGeneration** [comment]
This looks rather like a technical question.
Please have a look into the temporary directory: `tmp/unprocessible_mail`

If the mail is found in there, then this may be a temporary issue for whatever reason.
However, Zammad always logs fetch processes, so I really can't imagine that try is missing.


Also ensure that the first mail was really sent to the mailbox folder Zammad is monitoring.

**Comment by lafiel** [comment]
The Zammad user directory tmp/unprocessible_mail is empty.

I've created a new mail address and retried the above steps and got the same result.
* First mail does not create a ticket (not logged)
* Second mail does create a ticket (is logged)

and both were sent to the same address.

**Comment by MrGeneration** [comment]
Please provide the full log output of the timespan you're trying to do so.
If the log is too sensitive, you may send it over to support [at] zammad [dot] com referencing to me and this issue.

**Comment by lafiel** [comment]
![inbox](https://user-images.githubusercontent.com/4946784/93473247-14a19b00-f8f6-11ea-82a4-b600e286d635.png)

* First mail was sent 11:50ish --> ticket does not exist (no logging but reply and notification were sent)
* Second was sent 12:00ish --> ticket exists (logging, reply and notfication mails also)

[production.log.txt](https://github.com/zammad/zammad/files/5239233/production.log.txt)

**Comment by lafiel** [comment]
I've found a log message in syslog but I don't know if it's related.

`Sep 17 11:48:25 server1 bash[1644461]: /opt/zammad/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:34: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.`

`Sep 17 11:48:26 server1 bash[1644461]: message repeated 3 times: [ /opt/zammad/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:34: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.]`

**Comment by lafiel** [comment]
Do you know any recommendations I could try?

**Comment by lafiel** [comment]
Are there any commands, logging levels I could try?

**Comment by MrGeneration** [comment]
I'm sorry, I currently have no capacity in terms of time and will get back to you as soon as possible.

**Comment by lafiel** [comment]
I think we've got it sorted. The mail provider has upgraded their system to allow TLS 1.2. Since then we didn't have any further problems.

**Comment by MrGeneration** [comment]
Thank you for your feedback, we're glad your issue could be resolved. 💪
