### ISSUE TITLE
KB menu should stack on mobile and not push outside the viewport

### ISSUE THREAD

**Issue by wucherpfennig** [zammad/zammad#3211]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): .deb
* Operating system: Debian 10
* Database + version: not necessary
* Elasticsearch version: dito
* Browser + version: all browsers

### Expected behavior:

* Footer menu should stack on mobile and not push outside the viewport

### Actual behavior:

* See screenshot

Desktop
![image](https://user-images.githubusercontent.com/3634653/94027752-7a40cc00-fdbb-11ea-9af8-c45fb7d31fe8.png)

Mobile
![image](https://user-images.githubusercontent.com/3634653/94027587-49f92d80-fdbb-11ea-8fef-949ea42529c4.png)

### Steps to reproduce the behavior:

* Create menu items in the footer menu of the KB

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Hi @wucherpfennig ,

https://github.com/zammad/zammad/issues/3133 is already covering this (even though title may be not that clear). Closing this in favour of the old one.
