### ISSUE TITLE
No notification when creating a ticket

### ISSUE THREAD

**Issue by Vlad-Letnabov** [zammad/zammad#3212]
### Infos:

* Used Zammad version: zammad-3.4.0-4
* Installation method (source, package, ..): docker image
* Operating system: Ubuntu 18.04
* Database + version: zammad-postgresql-3.4.0-4 ( 9.6.17 )
* Elasticsearch version: zammad-elasticsearch-3.4.0-4 ( 7.6.1 )
* Browser + version: Firefox 80.0.1 (64-bit)

### Expected behavior:
*

Creating a notification in browser when creating a ticket using the REST API

### Actual behavior:
*

No notification. Ticket created successfully

### Steps to reproduce the behavior:

*
CURL (just like in docs)
curl -u user@server.ru:pass -H "Content-Type: application/json" -X POST -d '{"title":"Help me!","group": "Users","article":{"subject":"some subject","body":"some message","type":"note","internal":false},"customer":"user@yandex.ru","note": "some note"}' https://server.ru/api/v1/tickets/

Python code:
```
def create_ticket_in_sd(tmpl_text, user, message_id):
    query = f"{RHOST}api/v1/tickets"
    create_json = {
        "title": tmpl_text[:30],
        "group": "Users",
        "customer": user['login'],
        "state_id": 1,
        "article": {
            "subject": tmpl_text[:30],
            "body": tmpl_text,
            "type": "note",
            "internal": False,
            "sender": "Customer",
        },
        "note": tmpl_text,
    }
    responce = requests.post(query, auth=(RUSER, RPASSWORD), json=create_json)
    try:
        if responce.status_code == 201:
            if isinstance(responce.json(), dict):
                ticket = responce.json()
                print(ticket)
                return dict(id=ticket['id'],
                     number=ticket['number'],
                     title=ticket['title'])
    except BaseException as exp:
        print('Error create ticket: ', exp)
```

If ticket created via email or telegram channel (bot) notification in browser work fine.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry but this looks like a technical question.
If you still can't solve your issue, please consult the Zammad community: https://community.zammad.org

If you require commercial grade support, you can learn more about our support contracts here: https://zammad.com/pricing#selfhosted
