### ISSUE TITLE
Relative fields get copied on macro

### ISSUE THREAD

**Issue by Lapotor** [zammad/zammad#3213]
### Infos:

* Used Zammad version: v3.5.0
* Installation method (source, package, ..): package
* Operating system: Debain 10
* Database + version: postgres (PostgreSQL) 11.7
* Elasticsearch version: v7.9.1
* Browser + version: Firefox 80.0.1

### Expected behavior:

When on a macro you select `pending till` + `relative` and now change this to something else the normal expected form box will appear.
![grafik](https://user-images.githubusercontent.com/17144397/94064456-04078e00-fdea-11ea-96b4-001ba61a38ae.png)

### Actual behavior:

When on a macro you select `pending till` + `relative` and now change this to something else except `customer` and `user` the `pending till` form box are still there.
![grafik](https://user-images.githubusercontent.com/17144397/94064003-47adc800-fde9-11ea-8bb6-520723fd7c10.png)

### Steps to reproduce the behavior:

* Add Macro
* Select `pending till` and `relative`
* Now Select anything except `pending till`, `customer`, `user`
* Now the time boxes from pending get copied and the actual form box aren't displayed.
<details>
<a href="https://user-images.githubusercontent.com/17144397/94064003-47adc800-fde9-11ea-8bb6-520723fd7c10.png">Picture 1</a><br />
<a href="https://user-images.githubusercontent.com/17144397/94064158-8c396380-fde9-11ea-878b-50a583e78cf5.png">Picture 2</a>
</details>

**Comment by MrGeneration** [comment]
Big oof :D

Only seems to affects Macros

**Comment by mantas** [comment]
Damn! Same happens in Scheduler creation. Looks all forms with `ticket_perform_action` are affected.
