### ISSUE TITLE
link_template for ticket no longer shows a button after update to 3.5

### ISSUE THREAD

**Issue by eheinle-mak** [zammad/zammad#3214]
### Infos:

* Used Zammad version: 3.5.0
* Installation method (source, package, ..): source
* Operating system: Ubuntu 18.04.5 LTS
* Database + version: PostgreSQL 11
* Elasticsearch version: 7.6.1
* Browser + version: Firefox 80

### Expected behavior:

* I have a custom field as described in https://admin-docs.zammad.org/en/latest/system/objects.html, it's configured like in the attached screenshot
* I fill in the extra field in a ticket, value would be a number like 1337
* After saving, there should be a button that links to the value of the content of "Link Template" + the value
* This worked up until the update to 3.5 I performed yesterday

### Actual behavior:

* The field is visible and the correct value is still there
* The button linking to the value of the link template
 + the value is missing

### Steps to reproduce the behavior:

* Set up the object like in the screenshot, follow the rest of https://admin-docs.zammad.org/en/latest/system/objects.html
* Open a ticket, fill in a value for (in this example) "GitLab ID", click save
* Find the button missing

Attachment: ![Screenshot from 2020-09-24 11-30-11](https://user-images.githubusercontent.com/46962857/94129554-c80d1100-fe5b-11ea-8206-14cf62dd6328.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Seems like the "isEmpty" check may no longer work.
Not too sure. No errors in production log as well.

https://github.com/zammad/zammad/blob/stable/app/assets/javascripts/app/views/generic/attribute.jst.eco#L23-L28

**Comment by rolfschmidt** [comment]
escalated in Ticket#1080235

**Comment by rolfschmidt** [comment]
Hi @KoJie , check this out.

**Comment by rolfschmidt** [comment]
@KoJie basically there are currently two expected ways to handle your url data in objects right now:

# Use case 1: Fixed base url with dynamic parameters

Here we can see a Format Text + Type Text field which is used to open a google search. The base url for the query is always the same. But the string we want to search will be defined in the ticket.

**Configuration**

![grafik](https://user-images.githubusercontent.com/5445062/96139662-5c204480-0eff-11eb-990d-94ff8f8b349e.png)

**Example**

![grafik](https://user-images.githubusercontent.com/5445062/96139977-b0c3bf80-0eff-11eb-88da-0b94811058ff.png)

# Use case 2: Drag and drop URL

If you need a simple storage for URLs, then you should you Format Text + Type URL. This will store the link and make it clickable.

**Configuration**

![grafik](https://user-images.githubusercontent.com/5445062/96140158-ec5e8980-0eff-11eb-9d24-08d494284eaa.png)

**Example**

![grafik](https://user-images.githubusercontent.com/5445062/96140522-5119e400-0f00-11eb-8227-7e3588be3c16.png)

**Comment by rolfschmidt** [comment]
@MrGeneration do you we need to fix the documentation?
