### ISSUE TITLE
Google App docs link broken

### ISSUE THREAD

**Issue by YosefAdPro** [zammad/zammad#3222]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system:any
* Database + version: any
* Elasticsearch version:any
* Browser + version:any

### Expected behavior:

*
https://admin-docs.zammad.org/en/latest/channels/google/index.html

### Actual behavior:

*
https://admin-docs.zammad.org/en/latest/channels/google.html

https://github.com/zammad/zammad/blob/d64ea29efb98461a5a58bd4f10c7dda38d74e958/app/assets/javascripts/app/views/google/app_config.jst.eco#L3

### Steps to reproduce the behavior:

*
Not really a bug
![image](https://user-images.githubusercontent.com/11810187/94539645-2e27d880-024e-11eb-8ecf-260d565a7ad1.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Thanks for the hint. The redirection from the broken link now is active.
I'll correct above link to a later moment.

**Comment by rolfschmidt** [comment]
@MrGeneration looks like this is done and merged? can we close this?
