### ISSUE TITLE
Error: Kb locales is too long (maximum is 1 character)

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3223]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* If `kb_multi_lingual_support` setting is false, only one kb locale should be possible to create. If already more kb locales are existing, a human error message should appear.

### Actual behavior:

* If `kb_multi_lingual_support` setting is false and somebody tries to create a new kb locale, the error message `Error: Kb locales is too long (maximum is 1 character)` appears.

### Steps to reproduce the behavior:

* `Setting.set('kb_multi_lingual_support', false)`
* Try to create a second kb locale

**Comment by thorsteneckel** [comment]
Fixed with the commits above.
