### ISSUE TITLE
Zammad is not installing

### ISSUE THREAD

**Issue by cchinnu379-student** [zammad/zammad#3224]
I am using Godaddy VPS Hosting, want to use zammad as a help desk.
I followed your steps as it is,
I opened the terminal and installed zammad.
when I try to start zammad, I get an error stating "failed to start zammad.service"

I use CentOS 7, and want to install zammad on subdomain.
Please help me out with this.

**Comment by MrGeneration** [comment]
Sorry, but the Zammad repository is not the correct place for technical questions.
Please consult the Zammad community instead: https://community.zammad.org

If you require commercial grade support, you can also learn more about our support contracts if you're interested: https://zammad.com/pricing#selfhosted

Closing.
