### ISSUE TITLE
In the role settings a role can not be agent and customer at the same time

### ISSUE THREAD

**Issue by Vogelkoje** [zammad/zammad#3226]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-Number: #1079878, #1079904, #1079910

### Expected behavior:

* Since version 3.5 it should also be possible to be customer and agent at the same time. So it should also be possible in the UI -> Admin Interface -> Roles to select agent and customer simultaneously.

### Actual behavior:

* Only "customer" OR "agent" can be selected from the roles. Both is not possible. It always switches over.

### Steps to reproduce the behavior:

* Go to the UI of Zammad
* Admin interface
* Menu item roles
* Create a new role or select an existing one
* Try to select the items "agent" and "customer" both.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Hi @Vogelkoje ,

how does your role configuration look like?

Can you post it here or send it to support@zammad.com if it contains sensitive data? (include issue link, your username and mention me pls)

`zammad run rails r "pp Role.all"`
