### ISSUE TITLE
Can't complete LDAP setup due to Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by merced317** [zammad/zammad#3229]
### Infos:

* Used Zammad version: 3.5.x
* Installation method (source, package, ..): deb package
* Operating system: Ubuntu 18.04
* Database + version: Postgres 10
* Elasticsearch version: 7.9.0
* Browser + version: Google Chrome 85

### Expected behavior:

* LDAP configuration completes

### Actual behavior:

* Clicking "Continue" on the Users/Roles/Experts page throws the following error in the browser's console:

application-8bf35218647a61ae31d13eef552c8f9a4c81783c883211ca539d8df1e94e2628.js:2 Uncaught RangeError: Maximum call stack size exceeded
    at _.select (application-8bf35218647a61ae31d13eef552c8f9a4c81783c883211ca539d8df1e94e2628.js:2)
    at Function._ [as find] (application-8bf35218647a61ae31d13eef552c8f9a4c81783c883211ca539d8df1e94e2628.js:1)
    at rt.fn.init.find (application-8bf35218647a61ae31d13eef552c8f9a4c81783c883211ca539d8df1e94e2628.js:2)
    at HTMLFormElement.<anonymous> (application-8bf35218647a61ae31d13eef552c8f9a4c81783c883211ca539d8df1e94e2628.js:81)
    at application-8bf35218647a61ae31d13eef552c8f9a4c81783c883211ca539d8df1e94e2628.js:1
    at Function.map (application-8bf35218647a61ae31d13eef552c8f9a4c81783c883211ca539d8df1e94e2628.js:1)
    at rt.fn.init.map (application-8bf35218647a61ae31d13eef552c8f9a4c81783c883211ca539d8df1e94e2628.js:1)
    at rt.fn.init.serializeArrayWithType (application-8bf35218647a61ae31d13eef552c8f9a4c81783c883211ca539d8df1e94e2628.js:81)
    at Function.s.params (application-8bf35218647a61ae31d13eef552c8f9a4c81783c883211ca539d8df1e94e2628.js:26)
    at n.s.formParam (application-8bf35218647a61ae31d13eef552c8f9a4c81783c883211ca539d8df1e94e2628.js:26)

### Steps to reproduce the behavior:

* Upgrade to 3.5.x and try to configure LDAP

Yes I'm sure this is a bug and no feature request or a general question.  I would like to attempt to circumvent this so that I can finish my LDAP configuration but I don't see a documented way of proceeding.  I ran:

`zammad run rails r "puts Setting.get('ldap_config').to_json" > ldap_config.json`

so I have a backup of my current configuration.  All I'm hoping to do is disable LDAP SSL verification as the 3.5.x update apparently fixed it so strict checking of the SSL certificates is now happening.  My AD environment doesn't use a SAN on the certificates and I want to continue to use round robin DNS to hit an available AD controller and not sync to just one host.  Is there a documented way to take the saved JSON encoded LDAP configuration file I have saved and write it out not using a web browser?  I know I can completely remove the configuration with:

`RAILS_ENV=production zammad run rails r "Setting.set('ldap_config', {})"`

What would I replace in the above command in the {} section to be able to set the ldap_config settings?

**Comment by merced317** [comment]
I was able to get the configuration to save if I didn't attempt to assign any Roles during configuration.  If I attempt to assign any roles, I get the "Maximum call stack size exceeded" error.  I suspect this has to do with the large number of ldap groups in my organization's AD setup.  This wasn't a problem in earlier versions of Zammad so I don't know what changed.  I suspect this issue could be resolved if I could edit the LDAP Group Filter to something other than `(objectClass=posixgroup)` but there is no way to modify that via the UI.  [https://community.zammad.org/t/unable-to-edit-ldap-group-filter/3194](url)

**Comment by MrGeneration** [comment]
Are you able to adjust mappings after updating the rest of the configuration or does it consistently fail?
Any error messages regarding LDAP within your production log?

Possibly also an issue because of your LDAP size.
Which Active Directory version are you using and how many objects can be found via the filter you're using within Zammad=

**Comment by merced317** [comment]
> Are you able to adjust mappings after updating the rest of the configuration or does it consistently fail?

I am unable to adjust mappings after updating the rest of the configuration.  It consistently fails.

> Any error messages regarding LDAP within your production log?

Could I please have some more precise instructions on how to check this.  I am also nervous about sharing logs as there is potentially sensitive group information contained within.

> 
> Possibly also an issue because of your LDAP size.
> Which Active Directory version are you using and how many objects can be found via the filter you're using within Zammad=

"Active Directory version" Do you mean domain functional level?  I'm not sure how to answer this question properly.
Without the Roles section configured and the User Filter in place and the default Group Filter, I am syncing 253 objects.  However, when I get a full dump of the configuration:

`zammad run rails r "puts Setting.get('ldap_config').to_json" > ldap_config.json`

That ldap_config.json contains _ALL_ of the groups in my domain.  It's a 7.7MB file which seems extremely excessive for what I'm trying to accomplish.

**Comment by merced317** [comment]
It turns out a few AD controllers silently failed their certificate updates and fell back to locally signed to keep working. Therefore, the previously mentioned ssl_verify changes were a local problem and not one with Zammad. The other issues as reported still remain.

**Comment by thorsteneckel** [comment]
Hi @merced317 - Would it be possible to get a (somehow anonymised) copy of your `ldap_config`? You can send it to support at zammad.com and refer to this issue. This will help us a lot to reproduce and resolve this issue.

**Comment by merced317** [comment]
While I work on trying to anonymize 7.7MB of data, is [this](https://github.com/zammad/zammad/issues/981#issuecomment-297700787) an official way of populating the `ldap_config` without using the web interface?  It would seem to me that using that method I could set the `group_filter` as desired.  Please advise.

**Comment by thorsteneckel** [comment]
😖 only way I can think of is exporting it to JSON (as you already did), change it in the editor of your choice and then importing it again via `Setting.set('ldap_config', JSON.parse(File.read('/path/to/your/ldap_config.json')))`. It might be easier to do when using `JSON.pretty_generate(Setting.get('ldap_config'))` instead of `Setting.get('ldap_config').to_json` when exporting your config.

A valid and complete `ldap_config` (JSON export) looks like this (for reference purposes):
```json
{
  "ldap_config": {
    "host_url": "ldaps://127.0.0.1",
    "ssl_verify": false,
    "base_dn": "DC=domain,DC=tld",
    "bind_user": "user@domain.tld",
    "bind_pw": "some_pw",
    "user_uid": "samaccountname",
    "user_filter": "(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))",
    "group_uid": "dn",
    "group_filter": "(objectClass=group)",
    "user_attributes": {
      "samaccountname": "login",
      "givenname": "firstname",
      "sn": "lastname",
      "mail": "email",
      "telephonenumber": "phone"
    },
    "group_role_map": {
      "cn=zammad role admin,ou=zammad groups,ou=test,dc=domain,dc=tld": [
        1,
        2
      ],
      "cn=zammad role agent,ou=zammad groups,ou=test,dc=domain,dc=tld": [
        1,
        2
      ]
    },
    "unassigned_users": "sigup_roles"
  }
}
```

Would be cool if you could refer to the [community board](http://community.zammad.org/) for future technical question so that more people can profit from the shared knowledge 👍

**Comment by merced317** [comment]
I will refer to the community board as suggested for future technical questions.  Any chance the above information could be added to the official documentation for zammad as I suspect a number of people would prefer to maintain configuration files _not_ via a web interface?  Especially if that web interface breaks for any number of reasons and we need to get in the back end to fix something?  I appreciate the support.

**Comment by thorsteneckel** [comment]
Thanks for the proposal. Since the introduction of the LDAP feature we haven't had the request for that. We try to focus on 80% of the use cases for the documentation to avoid maintenance overhead and confusion. However, we might be wrong. There is a dedicated place for such and other proposals over at the community board where other users can add their votes: https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals/6

**Comment by dominikklein** [comment]
We can not reproduce the problem and there was also no other report related to this in the last years.
