### ISSUE TITLE
ProtonMail Bridge error: Can’t use Channel::Driver::Imap: #<Net::IMAP::NoResponseError: unsupported search query>

### ISSUE THREAD

**Issue by HristoA** [zammad/zammad#3233]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Zammad read/parse IMAP  data from ProtonMail Bridge as do for any other mail client/provider and all function of Zamamd to work as suppose to work 

### Actual behavior:

* `Can’t use Channel::Driver::Imap: #<Net::IMAP::NoResponseError: unsupported search query>`
![image](https://user-images.githubusercontent.com/20325836/95083462-3a67d600-0725-11eb-87ca-03af12de7764.png)

### Steps to reproduce the behavior:

* Add Account that is ProtonMail 

Yes I'm sure this is a bug and no feature request or a general question.

#### History:
1. Report  at community board (https://community.zammad.org/t/adding-protonmail-email-accounts-fail/4826) and fix with https://github.com/zammad/zammad/issues/3146
2. Report at community board (https://community.zammad.org/t/protonmail-cant-use-channel-net-unsupported-search-query/5344) and open this issue

**Comment by HristoA** [comment]
Hi.
Is there a way to help you? :)
Thanks

**Comment by mantas** [comment]
Hi @HristoA ,

Are there any extra steps to reproduce the error? I added Protonmail account and no errors so far.

**Comment by greedybro** [comment]
As far as i'm concerned, no extra-steps. 

On what platform are you testing ?
How are you running protonmail-bridge ? (trying to determine docker's fault in this issue)

Thanks for taking the time to address our issue !

**Comment by mantas** [comment]
Tested on `3.5.0` as well as `develop` branch locally with a protonmail-bridge provided by a customer (which may or may not be @HristoA ?) Added account and channel was verified successfully.

**Comment by HristoA** [comment]
Hi @mantas 
Ya I provide the credentials for Protonmail Bridge (version 1.2.7) installed on CentOS 7. 
Zammad is installed on CentOS 7 via RPM. Adding account work (connection success) but after  ~10-15 seconds error popup (one from screenshot).

Thanks

**Comment by mantas** [comment]
Hi @HristoA 

Do you do anything during that time? Or just let it sit idle?

Any emails coming in/out, either via Zammad or that mailbox directly?

**Comment by HristoA** [comment]
Nothing just wait...
I have 2 VPS for ProtonMail bridge. One that i use and one that i create for account that you @mantas use.
I made few additional tests:
- I just open again the instance and see the same message
- Enter your credential and all work without problem and errors
- Delete my email account and re added it to my Zammad instance and new error popup:
![image](https://user-images.githubusercontent.com/20325836/96713214-ec9bd080-13a8-11eb-82f9-9678068adb0f.png)
that disappear after some time. During showing of error i catch that only half of the emails from my inbox get moved to Zammad. Using setting: `Keep messages on server: NO`

- I notice also that VPS where your credential are hosted have Bridge v1.2.7 against v1.3.3 where mine are hosted. So i update to last Bridge v1.4.4 on my VPS instance (including one unread message) and again get this error after few seconds:
![image](https://user-images.githubusercontent.com/20325836/96714524-f1fa1a80-13aa-11eb-8d0a-d155fb4ef4d9.png)
And again error is persistent. Mentioned email not appear as ticket under Zammad
Using setting: `Keep messages on server: YES`

- Again remove account and add it with `Keep messages on server: NO` and wow -> **no errors**! 

@greedybro can you please verify my research and conclusion?

_Note_: Interesting is also the fact that i am at 3.5.x version (from UI, and i am sure that i run `yum update` before start test new 3.5.0 version) and the same time i see this on VPS as available update:
```
 zammad                                      x86_64                                      3.5.0-1603173041.2d96a39b.centos7                                       zammad                                      242 M

```
**Edit:**
```
yum list | grep zammad
zammad.x86_64                             3.5.0-1602165773.71bff28e.centos7   # Installed version
zammad.x86_64                             3.5.0-1603173041.2d96a39b.centos7 # Update available
```

Thanks and sorry that i not catch at the first time that you need to use  `Keep messages on server: YES` to reproduce the problem.

**Comment by greedybro** [comment]
hi @HristoA and @mantas !

I can confirm that setting `Keep messages on server = NO` does not throw errors and successfully retrieved my test email.

Interesting lead ! good job !

**Comment by mantas** [comment]
Good news everbody. I was able to reproduce the issue. I also found a likely fix. However, IMAP being IMAP, I need to quadruple-check it doesn't break other email server.. Anyway, fix coming soon.

**Comment by mantas** [comment]
And thank you for insights - the `Keep messages on server = NO/YES` helped a lot
