### ISSUE TITLE
OTRS migration doesn't import article creation time

### ISSUE THREAD

**Issue by delphi-sucks** [zammad/zammad#3235]
### Infos:

* Used Zammad version: 3.5.0-1601452467.437a9ac8.xenial
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 16.04.7 LTS
* Database + version: MySQL 5.7
* Elasticsearch version: 7.9.2
* Browser + version: Not applicable

### Expected behavior:

The created_at-time of the article in Zammad is the same like it was in OTRS.
Tickets on the other hand get imported correctly.

### Actual behavior:

article.created_at is the time of import of the article which results in old tickets with recent articles.

The executed SQL also shows that created_at seems to get updated to the current time after creating the article with the right valuese in '**lib/import/otrs/article.rb**'
```sql
INSERT INTO `ticket_articles` (`id`, `ticket_id`, `type_id`, `sender_id`, `from`, `to`, `cc`, `subject`, `message_id`, `message_id_md5`, `in_reply_to`, `references`, `body`, `updated_by_id`, `created_by_id`, `created_at`, `updated_at`) VALUES (74371, 14183, 1, 2, '...', '...', '', '...', '...', '...', '', '', '...', 1, 1, '2020-10-06 08:36:17.301000', '2020-10-06 08:36:17.301000')
```

### Steps to reproduce the behavior:

1. Setup an OTRS instance with a ticket and articles
2. Import
=> article.created_at is the time of import

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please provide the following output:
`zammad run rails r "p Setting.get('import_mode')"`

Thank you

**Comment by delphi-sucks** [comment]
Import-Mode is enabled:
```
irb(main):001:0> Setting.get('import_mode')
=> true
irb(main):002:0>
```

**Comment by HristoA** [comment]
Hi.
Quick check at PSQL show me that `created_at` is saved correct from OTRS to Zamamd DB into tables: `tickets`, `ticket_articles`. 
(If i can test in some other way to try reproduce your case tell me @delphi-sucks)

Only problem that i see is that my OTRZ and Zammad server are at GMT+3 and right now in browser tickets create time is = DB value +3 hours). How this can be fixed?
```html
<time class="humanTimeFromNow " datetime="2018-01-10T07:20:13.000Z" title="01/10/2018 09:20">Wednesday 01/10/2018 09:20</time>
```
(2018-01-10T07:20:13 is right time)

Thanks
