### ISSUE TITLE
SLA calendar datepicker visually broken

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3239]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Google Chrome latest
* Ticket: #1080027

### Expected behavior:

You can read the datepicker when adding custom holidays within the SLA calendar.

### Actual behavior:

When using the datepicker for custom holidays within a SLA calendar, the selectable days (except current day) have a white backround because of parent elements. This draws them impossible to read.

![issue_cant-read-datepicker_sla-calendar](https://user-images.githubusercontent.com/6549061/95319236-e9c4ba00-0897-11eb-8e8c-f2bd6708cca5.gif)

### Steps to reproduce the behavior:

* go to admin settings -> calendar
* edit or create a new calendar
* scroll down and click into the date column to add a new holiday date

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Seems to be duplicate of https://github.com/zammad/zammad/issues/2776 which is fixed in `develop`

![Screenshot 2020-10-07 at 13 30 38](https://user-images.githubusercontent.com/36944/95319923-55f7eb80-08a1-11eb-841f-25845e170458.png)

**Comment by MrGeneration** [comment]
Whoopsies, you're right - sorry!

**Comment by mantas** [comment]
No problem. Better report twice than skip a bug entirely :)
