### ISSUE TITLE
Rename Third-Party login: Office 365 to Microsoft 365

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3245]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Desired behavior:

`Office 365` is no longer an available product by Microsoft.
Instead the login option should rather be called `Microsoft` or -if we must- `Microsoft 365`.

Personally, as the login functionality works for both Office products and personal microsoft accounts without any office 365 products, I'd prefer Microsoft.

This technically might be blocked by our omniauth gem.

### Actual behavior:

Currently the login button and login setting is called `Office 365`.

![image](https://user-images.githubusercontent.com/6549061/95463048-98d8c280-0978-11eb-8ac3-987f260d3940.png)

**Comment by SupersonicWaffle** [comment]
I believe this is not entirely correct.
Microsoft 365 has been a product that has been available for a few years. Office 365 **Enterprise** plans are still available and distinct from Microsoft 365 **Enterprise**.
Office 365 **Business** plans however have been merged with Microsoft 365 **Business** plans.

If consistency is desired something along the lines of Azure AD Authentication might make more sense.

**Comment by MrGeneration** [comment]
While this is correct, this channel is not entirely about the Online Exchange services, but also covers outlook.com private accounts.

Edit:
We could also make it more general "Microsoft" which would be correct too.

**Comment by SupersonicWaffle** [comment]
Right, I guess I missed that between doing too many things at once.
I would agree that generically calling it "Microsoft" would make most sense.

Cheers
