### ISSUE TITLE
Zammad 3.5 Tags cannot be set

### ISSUE THREAD

**Issue by JanDoe8805** [zammad/zammad#3248]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): 
* Operating system: Ubuntu 18.04.5 LTS
* Browser + version: Firefox 78.3.1esr + Chrome 86.0.4240.75

### Expected behavior:

Tags should work

### Actual behavior:
Tags cannot be assigned to Tickets.
*

### Steps to reproduce the behavior:

Please see https://community.zammad.org/t/tags-are-not-saved/5470

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by JanDoe8805** [comment]
Log auszug:
`I, [2020-10-14T10:32:15.876240 #52604-47164867198200]  INFO -- : Started GET "/api/v1/tag_search?term=" for 80.151.xx.xx  at 2020-10-14 10:32:15 +0200

I, [2020-10-14T10:32:19.817239 #52604-47164867197080]  INFO -- : Started GET "/api/v1/tags/add?object=Ticket&o_id=151906&item=3D+Glasfoto&_=1602664331627" for 80.151.xx.xx  at 2020-10-14 10:32:19 +0200

I, [2020-10-14T10:32:19.830207 #52604-47164867197080]  INFO -- :   Parameters: {"object"=>"Ticket", "o_id"=>"151906", "item"=>"3D Glasfoto", "_"=>"1602664331627", "a"=>"api/v1/tags/add"}

E, [2020-10-14T10:32:19.838322 #52604-47164867197080] ERROR -- : No route matches [GET] /api/v1/tags/add (ActionController::RoutingError)
 `

**Comment by martini** [comment]
@JanDoe8805 Please make sure that you cleared your browser cache & restart Zammad on server site after upgrade. Then reload Zammad in your browser. Is it working then?

**Comment by JanDoe8805** [comment]
no. also tried in private mode within firefox and chrome. same problem

**Comment by martini** [comment]
Thanks for feedback. It seems that you are still using a old Zammad web app. The new (Zammad 3.5) web app would use post for adding new tags. So for some reason the new web app is not loaded in your browser.

**Comment by JanDoe8805** [comment]
Maybe i have to change apache-proxy-settings?
`#
# this is the apache config for zammad
#

<VirtualHost *:443>
SSLEngine on
RequestHeader set X_FORWARDED_PROTO 'https'
RequestHeader set X-Forwarded-Ssl on
SSLStrictSNIVHostCheck on

    # replace 'localhost' with your fqdn if you want to use zammad from remote
    ServerName service.xxx.com
    ServerAdmin hostmaster@xxx.com

    ErrorLog ${APACHE_LOG_DIR}/ssl_service.xxx.com-error.log
    CustomLog ${APACHE_LOG_DIR}/ssl_service.xxx.com-access.log combined

    SSLCertificateFile "/etc/ssl/certs/xxx.crt"
    SSLCertificateKeyFile "/etc/ssl/private/xxx.key"

    ## don't loose time with IP address lookups
    HostnameLookups Off

    ## needed for named virtual hosts
    UseCanonicalName Off

    ## configures the footer on server-generated documents
    ServerSignature Off

    ProxyRequests Off
    ProxyPreserveHost On

    <Proxy localhost:3000>
    Require local
    </Proxy>

    ProxyPass /assets !
    ProxyPass /favicon.ico !
    ProxyPass /robots.txt !
    ProxyPass /ws ws://localhost:6042/
    ProxyPass / http://localhost:3000/

    DocumentRoot "/opt/zammad/public"

    <Directory />
        Options FollowSymLinks
        AllowOverride None
    </Directory>

    <Directory "/opt/zammad/public">
        Options FollowSymLinks
    Require all granted
    </Directory>

</VirtualHost>
`

**Comment by MrGeneration** [comment]
This has nothing to do with your webserver configuration.
Ensure that your browser does not use a cached old Zammad-WebApp-Version (aka clear your cache) and that you have the latest Zammad 3.5 stable installed.

The route change was introduced with Zammad 3.5 due to a security issue (see: https://zammad.com/news/security-advisory-zaa-2020-17 ). This was also pointed out here: https://community.zammad.org/t/merging-tickets-fails-in-3-5/5383/5?u=mrgeneration

Closing now.
