### ISSUE TITLE
why is there no option to delete groups, organizations and users?

### ISSUE THREAD

**Issue by isyuricunha-zz** [zammad/zammad#3249]
how can I delete Groups, Users and Organisations and why I dont see this option?
I don't know if this is a bug or if there is another method to do this but, I believe it can be a tool to be added
I didn't find anything about it, so if anyone can help me, I'll be grateful

**Comment by MrGeneration** [comment]
Please don't post technical questions or feature requests on the Zammad repository. It's the wrong place.
You can create feature requests or ask technical questions at the Community Board: https://community.zammad.org

Also, this is actually mentioned in the documentation:
https://admin-docs.zammad.org/en/latest/system/data-privacy.html

You can remove groups without deep knowledge (for reasons).
For the rest, please have a look at the documentation. 

Closing.
