### ISSUE TITLE
Remove not needed package install dependencies (imlib2-devel & libimlib2-dev)

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3254]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Only install required packages as dependencies.

### Actual behavior:

* Too many packages are required as dependencies (imlib2-devel & libimlib2-dev are not needed).

**Comment by monotek** [comment]
Hmm... My docker & docker-compose build are failing without it?

https://github.com/zammad/zammad-docker/pull/41/checks?check_run_id=1287009726#step:3:1430
https://github.com/zammad/zammad-docker-compose/pull/178/checks?check_run_id=1287011433#step:3:774

**Comment by MrGeneration** [comment]
Ah seems like you need it for bundling. 
Just like @martini thought. 

This means this is gettinga big thing for package installations as well.

**Comment by MrGeneration** [comment]
Martin mentioned that, while you need `libimlib2-dev` during the build and bundle process, it *should* technically be fine to remove this package *after* you've finished bundling. This will save some space required for the container but is optional.

**Comment by monotek** [comment]
Ok, so I guess i just keep it the way it is and close the issues.

**Comment by martini** [comment]
Yes. For me it looks correct to keep it as it is in docker context.
