### ISSUE TITLE
In certain cases not all content of an html email is shown (HTML sanitizer will remove to much)

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3255]
### Infos:

* Used Zammad version: 3.5.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1080269

### Expected behavior:

* Show all content of html email

### Actual behavior:

* In certain cases (extended html comments), the sanitizer will remove to much

### Steps to reproduce the behavior:

example:

```
      <style><!--
/* Font Definitions */
@font-face
  {font-family:"Cambria Math";
  panose-1:2 4 5 3 5 4 6 3 2 4;}
  {page:WordSection1;}</style><!--[if gte mso 9]><xml>
<o:shapedefaults v:ext="edit" spidmax="1026" />
</xml><![endif]--><!--[if gte mso 9]><xml>
<o:shapelayout v:ext="edit">
<o:idmap v:ext="edit" data="1" />
</o:shapelayout></xml><![endif]-->
<div>123</div>
<a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1">abc</a></div>
```

**Comment by cautopartes** [comment]
Reorted in T#1080269
