### ISSUE TITLE
Zendesk migration issue

### ISSUE THREAD

**Issue by silviupanaite** [zammad/zammad#3259]
### Infos:

* Used Zammad version: zammad-3.5.0-13
* Installation method (source, package, ..): zammad-docker-compose
* Operating system:
* Database + version: zammad-3.5.0-13
* Elasticsearch version: zammad-3.5.0-13
* Browser + version: Opera

### Expected behavior:

* Old imported tickets should have the threads conversation present, as they come as a response from the zendesk api

### Actual behavior:

* Only clients replies are present, so the context of the conversation is missing

### Steps to reproduce the behavior:

* Have in zendesk a ticket with more replies in it from both parties
* Migrate from zendesk
* Reset Password from cli for account
* Login and check imported tickets

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Any errors in your production log of interest...?

**Comment by silviupanaite** [comment]
Not really.

**Comment by thorsteneckel** [comment]
Hi @silviupanaite - Please follow these steps:

1.) Create a file called `debug_issue.rb` from the code below in your Zammad directory (usually `/opt/zammad`) and replace the attributes marked with `TODO` in the file header section
2.) Run the file from your Zammad directory via `zammad run rails r debug_issue.rb` or `rails r debug_issue.rb` as zammad user, depending on your installation source (package/source)
3.) Send the generated `debug_zendesk.log` file to support at zammad.com. Please refer to this issue and me :)
4.) Delete the `debug_issue.rb` and `debug_zendesk.log` file

```ruby
zendesk_url      = "https://TODO.zendesk.com/api/v2"
zendesk_username = "TODO@your.tld"
zendesk_key      = "TODO"

require_dependency 'mixin/rails_logger'

module Mixin
  module RailsLogger
    def self.logger
      @logger ||= Logger.new(log_to).tap do |logger|
        logger.level = :debug
      end
    end

    def self.log_to
      Rails.root.join('debug_zendesk.log').to_s
    end
  end
end

Setting.set('import_zendesk_endpoint', zendesk_url)
Setting.set('import_zendesk_endpoint_username', zendesk_username)
Setting.set('import_zendesk_endpoint_key', zendesk_key)

Setting.set('import_mode', true)
Setting.set('system_init_done', false)

import_job = ImportJob.create(
  name:    'Import::Zendesk',
  payload: {},
  dry_run: false,
)

time = Benchmark.measure {

result = Sequencer.process('Import::Zendesk::Full',
                          parameters: {
                            import_job: import_job
                          })
}
puts time.real

import_job.save!

puts JSON.pretty_generate(import_job.attributes)

```

**Comment by MrGeneration** [comment]
Since we haven't received feedback, we will close this issue for now.
Please open a new issue with log output so that we know *where* the import fails.

Otherwise it will be impossible to solve the issue - if you have technical questions, please consult the community https://community.zammad.org
