### ISSUE TITLE
Create emails via fetchmail / procmail

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#326]
Coming from OTRS / KIX I'm used to pipe mail to a postmaster process via fetchmail & procmail.

Would be nice this would be also possible in Zammad, because currently we have several email addresses configured for one pop3/imap account and there is no way to configure this currently.  

That's also the reason we want to use sendmail for sending mails to customers as described in: https://github.com/zammad/zammad/issues/224

**Comment by martini** [comment]
You can "pipe" email into Zammad with the following command:

cat /path/to/mail.eml | rails r 'Channel::Driver::MailStdin.new'

PS: If you use configured mail accounts, you can use multi smtp for each configured email address (lets says @gmx.net is using gmx mail server and @gmail.com is using google mail server).

**Comment by monotek** [comment]
Cool! Thanks for the hint! Will add it to the documentation later :-)

**Comment by martini** [comment]
Yeah! Thanks! Later I'll look on #224

**Comment by monotek** [comment]
P.s.: are mail headers, for presorting mails via procmail to groups, also already supported?

**Comment by martini** [comment]
Yes! :-D

doc/X-Headers.txt basically you can set any ticket and article attributes.

Unfortunately currently not with "rails r 'Channel::Driver::MailStdin.new'", I need to extend it to accept params like:

 rails r 'Channel::Driver::MailStdin.new(trusted: true)'

-> You will get an follow up ASAP.

**Comment by martini** [comment]
Fixed https://github.com/zammad/zammad/commit/743700fe25ea80857c4500f8b007f023d21de4c7 now you can use:

cat test/fixtures/mail1.box | rails r 'Channel::Driver::MailStdin.new(trusted: true)'

And the X-Zammad-Header are used in Zammad. Also improved doc/x-headers.md, maybe we should move it to zammad.org/documentation too.

**Comment by monotek** [comment]
Added the mail headers to the pull request for zammad.org.
Also created Permissions and Glossary site.

Maybe we can get rid of the whole docs dir now.

Not sure what README_FOR_APP and app_events.txt is for. Should we keep this in th documentation too? If so, where?

**Comment by martini** [comment]
Just drop README_FOR_APP and app_events.txt in case we need to start a developer manual later (then I do it from scratch).
