### ISSUE TITLE
Don't display dot(s) next to state circles

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3262]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on Google Chrome latest (Windows) and Microsoft Edge
   * Google Chrome on MacOS and Firefox seem not affected
* Ticket: 1080237, 1081358

### Expected behavior:

Zammad does not display a dot next to the state circle - no matter what.

### Actual behavior:

Zammad displays a dot next to state circles in specific situations.
The reason for this is the column of the circle not being wide enough. Some zoom states do clear this issue.

![issue_dots-in-overviews](https://user-images.githubusercontent.com/6549061/97466113-073eee00-1943-11eb-8f88-77ec95345283.gif)

### Steps to reproduce the behavior:

* meet above browser situation
* have a look at any overview - if needed play around with zooming stages
   * happens to me on 2k and FullHD resolution without UI zooming (Windows can zoom UI to scale big resolutions)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by hanneshal** [comment]
Update on this one: the small dot is from "..." 
Extending the width to: $('.js-tableHead[data-column-key=icon]').width(28)
Fixes the issue. 
Chrome on Mac is also affected, Safari is fine.

**Comment by mantas** [comment]
@hanneshal did you replace it on 3.5 or latest 3.6?

**Comment by MrGeneration** [comment]
The fix mentioned should work on both 3.5 and 3.6

**Comment by mantas** [comment]
@MrGeneration Thing is I used to see this issue all the time. But recently it stopped. I also fixed a couple other issues in tables in IIRC 3.6.  Now I'm trying to replicate it following your gif, but I can't.

I wonder maybe this was accidentally fixed in 3.6 :)

**Comment by MrGeneration** [comment]
It was not.
This issue depends highly on viewports.

The dot is coming from Zammads functionality to cut strings within a column that are too large for it to display.

It may not appear on all browsers and not permanently. My browser currently displays it on develop as well.

**Comment by bolah2009** [comment]
@MrGeneration `28` seems to be the current width but reducing to 24px fixes this issue in chrome (Mac), the current state work fine on Firefox.

A possible solution would be reducing the width to 24px.

@MrGeneration about this comment:

> The dot is coming from Zammads functionality to cut strings within a column that are too large for it to display.

This could also be a possible solution if it is possible to avoid this functionality when the column is an icon.

**Comment by martini** [comment]
How about removing the "..." stuff by css? It's defined for regular table columns to show the content with "..." if it's longer then the column width. But it's not needed for icons.

**Comment by bolah2009** [comment]
@martini I opened a PR #3406 that fixes the issue using your suggestion!
