### ISSUE TITLE
Space after ticket hook in ticket/zoom

### ISSUE THREAD

**Issue by delphi-sucks** [zammad/zammad#3265]
### Infos:

* Used Zammad version: 3.5.0-1603788665.5a776fce.xenial
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04.7 LTS
* Database + version: MySQL 5.7.32-0ubuntu0.16.04.1
* Elasticsearch version: 7.9.2
* Browser + version: Vivaldi 3.4.2066.90

### Expected behavior:

The Ticket-Number is attached to the Ticket Hook.

`Hook#123456789`

This behaviour is defined in the Ticket Hook Settings for the position with examples showing the expected behaviour:
`[Ticket#12345]`

### Actual behavior:

In the Ticket View the Ticket Hook and Number are seperated by a space:

`Hook# 123456789`

![image](https://user-images.githubusercontent.com/17913239/97855559-3070cd00-1cfb-11eb-98ef-f9ade111f093.png)

### Steps to reproduce the behavior:

Open a ticket and examine the Ticket-Number with hook under the title.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I do agree that we should provide this information the exact same way we do on every component.
However, I personally see this as an enhancement.
