### ISSUE TITLE
Move all install docs from README.md to https://zammad.org/documentation/

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#327]
Imho having this twice will lead to differences in the docs at some point.

What i would like to do is:
- Remove README_Install_Debian_Ubuntu.md
- Remove README_Install_Mac.md
- Remove README_elasticsearch.md
- Change README.md to just point to https://zammad.org/documentation/install/install-source  
- Remove everything but "Welcome to Zammad" from README.md
- Adding all removed content to documentation on zammad.org

**Comment by martini** [comment]
+1

**Comment by monotek** [comment]
Done! :-)

https://github.com/zammad/zammad/pull/328
