### ISSUE TITLE
Missing translation for insufficient permissions for <object>

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3275]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Note: This originally came from the community at https://community.zammad.org/t/translate-and-customized-an-error/5511 by user juliels.

### Expected behavior:

The string `Oops.. I\'m sorry, but you have insufficient rights to open this %s.` is available for translation.

### Actual behavior:

The string `Oops.. I\'m sorry, but you have insufficient rights to open this %s.` is not available for translation.
Thus you can't translate it to your language.

(see: https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/views/generic/error/unauthorized.jst.eco )

### Steps to reproduce the behavior:

* check your translations

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
@mgruner this will be improved with the new extractor and the Weblate migration, right?

**Comment by mgruner** [comment]
@thorsteneckel @MrGeneration yes, the extractor finds this string already in the feature branch:

```gettext
#: app/assets/javascripts/app/views/generic/error/unauthorized.jst.eco
msgid "Oops.. I'm sorry, but you have insufficient rights to open this %s."
msgstr ""
```

Do we need to keep this open until this gets merged?

**Comment by thorsteneckel** [comment]
I created the 5.1 milestone and assigned this issue to it. We can already update the title of the Weblate migration MR accordingly to close this issue once merged 👍
