### ISSUE TITLE
Pending event time after 22:59 jumps back to 22:59

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#329]
It is not possible to enter any time after 22:59 at a pending event.

![zammad](https://cloud.githubusercontent.com/assets/6099976/19830673/0bbdccd2-9dfd-11e6-8ac6-5742058d87b3.gif)

**Comment by martini** [comment]
Wow!

**Comment by jacotec** [comment]
@martini Same in the calendar ... the time 23:59 jumps back to 22:59

**Comment by martini** [comment]
Also in calendar working time definition.

**Comment by martini** [comment]
Fixed in 1.0, 1.1 and develop.

**Comment by jacotec** [comment]
@martini : Seems "Master" is the non-loved "Stiefkind" again ... all builds including stable updated 9hrs ago ... master 8 days ago.

Does it really make sense to keep the master branch when it's often even days behind stable?

**Comment by martini** [comment]
@jacotec it seems that you should use develop stable in your env.
