### ISSUE TITLE
Representation of inactive customers and orgnizations

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#3302]
### Infos:

* Used Zammad version: 3.6x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: 1079231, 1088964

### Expected behavior:

* Inactive customers and organizations should be visually represented more clearly throughout the system
* Maybe by showing in "User-Org-Selector" as "striked out"
* Should be marked within the Autocompletion function on using the "reply" dialog 
* Should be marked in the organization selection in the user management

### Actual behavior:

* Inactive customers/orgnizations are shown "normally" via "User-Org-Selector" and "Autocompletion"

### Steps to reproduce the behavior:

* Search for customers/orgnizations via "User-Org-Selector" and/or "Autocompletion"

**Comment by dominikklein** [comment]
As a addition to the invalid customers, we need also to align the output of the invalid organizations (e.g. in the organization selection for the user create/edit form).

(The Following Ticket is related: 1088964)
