### ISSUE TITLE
Zendesk import fails if fields with unsupported chars in its name are present

### ISSUE THREAD

**Issue by shopblocks** [zammad/zammad#3310]
**ERROR DURING MIGRATION: Problem with ObjectManager Attribute 'system/embeddablelastseen': Validation failed: Name Only letters from a-z because numbers from 0-9 and _ are allowed**

We are hitting this error during Zendesk migration. To help with debugging, on another github issue - https://github.com/zammad/zammad/issues/3259 - I saw a suggested debug script by @thorsteneckel so we have used the same script and emailed the results to the Zammad support team (as it contains sensitive info). Here is one relevant section from the end of that log:

```
D, [2020-11-29T11:11:58.775007 #275095-47147749775780] DEBUG -- : State cleanup of Unit Sequencer::Unit::Import::Zendesk::ObjectAttribute::SanitizedName (index: 1) started.
D, [2020-11-29T11:11:58.775035 #275095-47147749775780] DEBUG -- : State cleanup of Unit Sequencer::Unit::Import::Zendesk::ObjectAttribute::SanitizedName (index: 1) finished.
D, [2020-11-29T11:11:58.775067 #275095-47147749775780] DEBUG -- : Sequence 'Sequencer::Sequence::Import::Zendesk::UserField' Unit 'Sequencer::Unit::Import::Zendesk::ObjectAttribute::Add' (index: 2) started.
D, [2020-11-29T11:11:58.775207 #275095-47147749775780] DEBUG -- : Getting 'resource' value (ZendeskAPI::UserField): #<ZendeskAPI::UserField {"url"=>"https://***.zendesk.com/api/v2/user_fields/267709.json", "id"=>267709, "type"=>"date", "key"=>"system::embeddable_last_seen", "title"=>"Last Seen", "description"=>"The date this user was last detected on a web page with the Zendesk Web Widget", "raw_title"=>"txt.embeddable.zendesk_user_fields.system_embeddable_last_seen_title", "raw_description"=>"txt.embeddable.zendesk_user_fields.system_embeddable_last_seen_description", "position"=>0, "active"=>true, "system"=>true, "regexp_for_validation"=>"\\A([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])\\z", "created_at"=>2016-03-21 17:11:33 UTC, "updated_at"=>2016-03-21 17:11:33 UTC}>
D, [2020-11-29T11:11:58.775428 #275095-47147749775780] DEBUG -- : Getting 'model_class' value (Class): User(id: integer, organization_id: integer, login: string, firstname: string, lastname: string, email: string, image: string, image_source: string, web: string, password: string, phone: string, fax: string, mobile: string, department: string, street: string, zip: string, city: string, country: string, address: string, vip: boolean, verified: boolean, active: boolean, note: string, last_login: datetime, source: string, login_failed: integer, out_of_office: boolean, out_of_office_start_at: date, out_of_office_end_at: date, out_of_office_replacement_id: integer, preferences: string, updated_by_id: integer, created_by_id: integer, created_at: datetime, updated_at: datetime)
D, [2020-11-29T11:11:58.775488 #275095-47147749775780] DEBUG -- : Getting 'sanitized_name' value (String): "system/embeddable_last_seen"
```

Looking at the logged data coming through from Zendesk, the values we see in `system::embeddable_last_seen` are things like:

```
"system::embeddable_last_seen"=>"2020-07-04T00:00:00+00:00"

"system::embeddable_last_seen"=>nil

"system::embeddable_last_seen"=>"2016-04-25T00:00:00+00:00"
```

The validation error "Only letters from a-z because numbers from 0-9 and _ are allowed" could suggest that the "+" and other symbols are unexpected, or perhaps our `nil` values are causing a problem?

### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu
* Database + version: Postgres 12
* Elasticsearch version: 7
* Browser + version: Chrome latest

### Expected behavior:

* My Zendesk tickets are migrated without errors

### Actual behavior:

* Error halts migration: Problem with ObjectManager Attribute 'system/embeddablelastseen': Validation failed: Name Only letters from a-z because numbers from 0-9 and _ are allowed

![image](https://user-images.githubusercontent.com/14819903/100540382-05fc2c00-3235-11eb-9f36-981cd96bc1e7.png)

### Steps to reproduce the behavior:

* Reset database and start Zendesk migration from browser (with our Zendesk account...)

**Comment by shopblocks** [comment]
Perhaps I'm reading this error wrong - is it the actual name of the attribute "system::embeddable_last_seen" causing the problem? Looks like it's being changed to "system/embeddable_last_seen" in Zammad - either way it wouldn't validate as `/[a-z0-9_]+/` - plus - I can't see any other keys in our Zendesk data that have the `::` string in their names, so maybe this is an issue and is caused by the use of the Web Widget by our Zendesk account?

**Comment by shopblocks** [comment]
As a quick test we changed the `SanitizedName` class, adding the following "without_slashes" function to see if there was perhaps a bug with slashes not being removed by "without_spaces_and_slashes".

```
...
            def sanitized_name
              # model_no
              # model_nos
              # model_name
              # model_name
              # model_name
              without_double_underscores.gsub(/_id(s?)$/, '_no\1')
            end

            def without_double_underscores
              # model_id
              # model_ids
              # model_name
              # model_name
              # model_name
              without_slashes.gsub(/_{2,}/, '_')
            end

            # THIS FUNCTION ADDED AS A QUICK DEBUG
            def without_slashes
              # model_no
              # model_nos
              # model_name
              # model_name
              # model_name
              without_spaces_and_slashes.gsub(/\//, '_')
            end

            def without_spaces_and_slashes
              # model_id
              # model_ids
              # model___name
              # model_name
              # model_name
              transliterated.gsub(%r{[\s/]}, '_').underscore
            end
...
```

After re-running the migration with this we saw this in the log:

```
-- add_column("users", "system_embeddable_last_seen", :date, {:default=>nil, :null=>true})
   -> 0.0021s
```

The migration proceeded further:

![image](https://user-images.githubusercontent.com/14819903/100541540-84100100-323c-11eb-8ffe-abee107db43d.png)


However it got stuck again with this error:

```
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:80:in `raise_validation_error': Validation failed: Data option must have one of text/password/tel/fax/email/url for :type (ActiveRecord::RecordInvalid)
```

**Comment by shopblocks** [comment]
Adding the the previous comment, the full error message was:

```
/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/validations.rb:80:in `raise_validation_error': Problem with ObjectManager Attribute 'data_migration_notes': Validation failed: Data option must have one of text/password/tel/fax/email/url for :type (ActiveRecord::RecordInvalid)
```

Looking at our Zendesk configuration for the "Ticket Fields" settings we have an inactive ticket field called "Data Migration Notes" which looks like this:

![image](https://user-images.githubusercontent.com/14819903/100541762-e74e6300-323d-11eb-8d72-1277efc50713.png)

This could be related to https://community.zammad.org/t/zendesk-import-fails-multiline-text-custom-field-in-organization/2369 - however I can't see if that was ever migrated to Github as an issue, or solved?

**Comment by shopblocks** [comment]
After our crude "without_slashes" workaround above, during the later stages of the import we can see errors in the logs such as:

```
E, [2020-11-29T14:45:42.499534 #277629-47129534217960] ERROR -- : unknown attribute 'system::embeddable_last_seen' for User. (ActiveModel::UnknownAttributeError)
```

So clearly our workaround isn't a full solution.

**Comment by MrGeneration** [comment]
The following characters are supported by Zammad:
`[a-Z]` and `_`.

The workaround is to rename or delete the fields.

---

I personally don't see this as a bug but an enhancement.

**Comment by shopblocks** [comment]
Hi @MrGeneration - I think this is a bug in terms of the original error - the Zendesk migration is impossible if the Zendesk Web Widget has been used as thee "embeddable last seen" attribute - which is system-generated by Zendesk and cannot be removed - halts the Zammad migration.

Are you aware of a workaround we're missing?

**Comment by MrGeneration** [comment]
I migrated two Zendesk different zendesk instances last week and did not see this attribute.
This may be a special attribute in your case. 

Please head over to the Zammad Community for technical questions: https://community.zammad.org

---

As I said, I do agree that the import should be enhanced to rename "invalid" field names so that it works for Zammad.
It is no bug in my opinion though. It's just logic Zammad doesn't provide to this extend as of now.

**Comment by shopblocks** [comment]
I think an enhancement to Zammad would be ignoring "system::example" attributes coming from Zendesk.
