### ISSUE TITLE
nested "view from user perspective" yield to only being able to return to last viewed session

### ISSUE THREAD

**Issue by olafbuitelaar** [zammad/zammad#3315]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): docker
* Operating system: centos 7
* Database + version: pgsql 13
* Elasticsearch version: 7.9.1
* Browser + version: Chrome 86

### Expected behavior:

When using the feature "View from user's perspective" going into an user, and don't return to your own user, and from the viewed as user perspective, go into another user perspective. pressing "back to my view" returns you to the view of the first view as user perspective instead of as your own view.
Thus;
- my session
   - other user session
      - second other user session
i would expect to return to my session, not other user session.
It's probably an minor issue..

### Actual behavior:

When switching back to my view i enter the last "view as user perspective" session instead of my own session.

### Steps to reproduce the behavior:

1. go to admin->users
2. use the "view from user's perspective" feature on an admin user
3. from the impersonated view go to admin->users again
4. use the "view from user's perspective" feature again on another admin user
5. press the button "back to my view", you now enter the session from step 3 and are not able to switch back to your own session

**Comment by MrGeneration** [comment]
@thorsteneckel  I think that's an edge case and not really a bug.

Why do I think that:
If I switch to the users perspective, even if I'm administrator, I'm completely acting on behalf of that user.
This means, if I switch to another users view because the users permissions allow that, the wording "back to my view" contexts to the user I've taken over and thus is technically correct.

I'd go further and say "a user ignoring the blueish bar indicating a taken over session does want it that way".
Going back to the second session instead to "my original one" is technically correct behavior in my opinion.

**Comment by olafbuitelaar** [comment]
I agree it's an edge case. But i don't think it's technically correct, because you impersonate as another user, not take over an session/login as that user (however that may technically be the way it's implemented).  I think the "back to my view" should either return to the (original) user who logged in, or that each impersonated "view as user" session should know which user entered the session, so that when you enter "back to my view" pops one session into the previously entered session, and such know's it's still in a "view as user perspective" and display's the blue bar, so you can walk the impersonation stack all the way back to your own session.
I Think in no way you should be able to hijack another user's session in this way, without an method to return to your own sessions, besides logging out, and re-login with your own credentials. Which also might not be obvious to the user, it's still using somebody's else session.
Last entering the session of another user, pop's an warning if on the user session "an new session was created with your account, this session will be stopped to prevent conflicts"

**Comment by MrGeneration** [comment]
Oh sorry now I see what you meant.
Nevermind that is a bug.

Edit: Screencast for TL;DR

![issue3315](https://user-images.githubusercontent.com/6549061/100610361-d8d07c00-330f-11eb-8e4b-2ef38f9e51a1.gif)

**Comment by thorsteneckel** [comment]
I agree. This line should not overwrite the `: switched_from_user_id ` key if it's already present: https://github.com/zammad/zammad/blob/e2c4e6316d6a9c4f564273088206e5143a01cec2/app/controllers/sessions_controller.rb#L133

**Comment by mantas** [comment]
@thorsteneckel in order to support matrioshka navigation, it should store backlog of user IDs.

Any preference wether to it should revert to original user or go one step back?

**Comment by thorsteneckel** [comment]
No matrioshka navigation. Just don't overwrite `session[:switched_from_user_id` if it's already set. This should cause the "switch_back" action to always go back to the original user aka the intended behaviour.
