### ISSUE TITLE
Messages in authenticates.rb are not translated

### ISSUE THREAD

**Issue by pyrog** [zammad/zammad#3317]
### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): online version zammad.com
* Source code : [authenticates.rb](https://github.com/zammad/zammad/blob/3533339e7bc88e0b55c23c2279f0c8fed04c8730/app/controllers/application_controller/authenticates.rb#L164)

### Expected behavior:

* All sentences must be translated

### Actual behavior:

* _"Login failed. Have you double-checked your credentials and completed the email verification step?"_ is not translated.

<img width="33%" alt="Login form" src="https://user-images.githubusercontent.com/2158081/100701157-57282f00-339f-11eb-8436-bfbe0b1e14d4.png">

Yes I'm sure this is a bug and no feature request or a general question.
~~See #3318~~

**Comment by MrGeneration** [comment]
Thanks for your report.
Please note that 3318 is only indirectly affected, because it's just the reason why the message is thrown.

But you're right, currently failed login strings don't seem to be traslated.

**Comment by mantas** [comment]
Hi @pyrog ,

This message is now available for translating via admin interface. As an open source project, Zammad relies on user-contributed translations. Follow steps bellow to translate this string:

- Go to Preferences > System > Translations in your Zammad instance

- Click "Get latest translations" on top-right

- Find the string in question in the list bellow

- Fill in the translation

- Push your changes

Beware that it takes some time for us to review translations and make them available publicly

Closing now.
