### ISSUE TITLE
Problem with Adding new Rows in Tree-Select

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#3320]
### Infos:

* Used Zammad version: 3.6.x
* Installation method: hosted
* Browser + version: Chrome (86.0.4240.198 )
* T#1081517

### Expected behavior:

* If I add a new main category to an existing key structure, it should be added below and not affect or change the current structure.

### Actual behavior:

* When I add a new main category to an existing key structure, the new main category is opened directly below it, thereby repositioning the existing subcategories
* when I notice that the main category was opened in the wrong place I want to delete it. But this will also delete the subcategories that actually belong to the previous main category.

![tree](https://user-images.githubusercontent.com/22768032/100730513-6ffa0a00-33ca-11eb-945e-f2201f823990.gif)

This makes it impossible to add a new category via the interface after the tree has been created initially without re-creating the entire category tree. 

### Steps to reproduce the behavior:

* go to the object-menu and add a new object
* select the tree select format
* add at least two main categories and a subcategory for each 
* now (in case you forgot one and want to add another category) try to add a new main category

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Is this from a paying customer? If so, please update the first article and add the ticket number to it.

**Comment by KoJie** [comment]
Please look at the informations. Ticket number was already added 👌
