### ISSUE TITLE
Quotation marks are encoded when displayed

### ISSUE THREAD

**Issue by pyrog** [zammad/zammad#3322]
### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): Online https://abc.zammad.com

### Expected behavior:

* Must decode i.e. `&#39;` before displaying it<br>Example : `"Dernier expéditeur d'article"`

### Actual behavior:

* Display `"Dernier expéditeur d&#39;article"`<br/>Example: [Edit: Trigger](https://abc.zammad.com/#manage/trigger)<br/><img width="50%" alt="Edit: Trigger" src="https://user-images.githubusercontent.com/2158081/100778904-e5d09680-3407-11eb-969a-06ed5a58a5c2.png">

### Additional information:

* This string could be edited in Admin → System  → Translations<br/>
<img width="50%" alt="Translations:Article Last Sender " src="https://user-images.githubusercontent.com/2158081/100779621-f6354100-3408-11eb-95d2-353edfd6b998.png">

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by pyrog** [comment]
Thank you 😃 

This seem not be to be yet in production, is it ?

**Comment by thorsteneckel** [comment]
Hi @pyrog - you are right. We fixed it only for the upcoming Version (Q1 next year). However, I'll create a backport for you. I give you an update - should be available in a couple of hours from now.

**Comment by thorsteneckel** [comment]
Hey @pyrog - good news: The fix is now backported to 3.6 with the commit above. However, it will take up to 30 minutes till the new packages are ready. You can follow the progress [here](https://packager.io/gh/zammad/zammad/builds/4727). Once the packages are ready you can update your Zammad installation :)
