### ISSUE TITLE
attachment validation using mixed symbols and strings

### ISSUE THREAD

**Issue by abeluck** [zammad/zammad#3326]
## Infos:

* Used Zammad version: 3.6.0 and 3.7.0
* Installation method (source, package, ..): source
* Operating system: debian
* Database + version: postgresql 
* Elasticsearch version: n/a
* Browser + version: n/a

## What's going on

We're writing a custom addon for zammad that adds a new channel. It is basically a webhook handler to create tickets from an external service.

In our controller we have code like this:

```ruby
    article_params = {
      sender: "Customer",
      subject: title,
      body: body,
      content_type: "text/html",
      type: "note",
      attachments: [
        {
          "filename" => recording_filename,
          "data" => recording_data_base64,
          "mime-type" => recording_mimetype,
        },
      ],
    }

    clean_params = Ticket.param_cleanup(ticket_params, true)
    ticket = Ticket.new(clean_params)

    ticket.save!
    ticket.with_lock do
      article_params[:sender] = "Customer"
      article_create(ticket, article_params)
    end
```
The controller has `include CreatesTicketArticles` to access the create function.

The ticket creation itself is working fine. The bug is when creating an article with an attachment. 

Specifically, the bug is related to how the attachments list is being processed.

The create ticket articles concern is inconsistently referencing the keys of the attachment has as a string and other times as symbols.

Here it expects strings:

https://github.com/zammad/zammad/blob/5e94f786fd2537e275ce3974f559e5fddb6a39db/app/controllers/concerns/creates_ticket_articles.rb#L79

Here it expects symbols:

https://github.com/zammad/zammad/blob/5e94f786fd2537e275ce3974f559e5fddb6a39db/app/controllers/concerns/creates_ticket_articles.rb#L99

also here it expects a symbol:

https://github.com/zammad/zammad/blob/5e94f786fd2537e275ce3974f559e5fddb6a39db/app/controllers/concerns/creates_ticket_articles.rb#L109

### Input

I would expect passing an attachments hash like the following to work just fine ([note that the tests use strings](https://github.com/zammad/zammad/blob/3.7.0/spec/requests/ticket/article_spec.rb#L81-L91), but that is before json serialization)

```ruby
:attachments=> [{
  "filename" => recording_filename,
   "data" => recording_data_base64,
  "mime-type" => recording_mimetype,
}]
``` 

### Actual behavior:

```
E, [2020-12-04T16:17:07.877787 #5224-51448633852240] ERROR -- : undefined method `gsub' for nil:NilClass (NoMethodError)                            
/home/user/src/zammad-vanilla/app/controllers/concerns/creates_ticket_articles.rb:99:in `block in article_create'     
```
[triggered here](https://github.com/zammad/zammad/blob/3.7.0/app/controllers/concerns/creates_ticket_articles.rb#L98-L103)

### Input

```ruby
:attachments=> [{
  :filename => recording_filename,
   :data => recording_data_base64,
  "mime-type".to_sym => recording_mimetype,
}]
``` 

### Actual behavior:

```
Attachment needs 'mime-type' param for attachment with index '0'
```

[triggered here](https://github.com/zammad/zammad/blob/5e94f786fd2537e275ce3974f559e5fddb6a39db/app/controllers/concerns/creates_ticket_articles.rb#L85-L87)

## Steps to reproduce the behavior:

* Attempt to create a ticket article and manually define an attachment like the following, or see my code above.

```ruby
:attachments=> [{
  "filename" => recording_filename,
   "data" => recording_data_base64,
  "mime-type" => recording_mimetype,
}]
```

### Workaround

I'm not a ruby guru, but something is fishy here. Here is in fact how we workaround this issue:

```ruby
      attachments: [
        {
          "filename" => recording_filename,
          :filename => recording_filename,
          :data => recording_data_base64,
          "data" => recording_data_base64,
          "mime-type" => recording_mimetype,
        },
      ],
```
Beautiful, eh? 

The full addon code is open source here: https://gitlab.com/digiresilience/link/zammad-addon-grabadora/-/blob/master/src/app/controllers/channels_cdr_grabadora_controller.rb#L221-248

- [x] Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Attention: Zammad stable is 3.6!

@thorsteneckel is this really a bug? Smells quite developer supportish to me.

**Comment by abeluck** [comment]
This applies to 3.6 and 3.7 (we develop against both), updated the ticket to reflect that.

Also I tried very hard to ensure this was indeed a bug rather than a failing in my ruby skills. The latter may still be the case, however I've had other eyes look at this and the behavior is definitely strange. I'm very confident this is a bug. Happy to move to the forum if it is not.

**Comment by mantas** [comment]
@abeluck please take a look at `HashWithIndifferentAccess`. It's a Rails-supplied addon that allows to mix Symbol `:key` and String `'key`` in a hash.

https://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html

While it's far from best-practice for a clean code, it is very common in Ruby on Rails to mix and match symbols and keys. Sorry for the confusion.
