### ISSUE TITLE
Scrolling to Article by passing ID to URL is broken

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#3330]
### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket# 1078020

### Expected behavior:

* When opening an Ticket Zoom URL containing an Article ID the browser scrolls to that Article ID

### Actual behavior:

* When opening an Ticket Zoom URL containing an Article ID the browser doesn't scroll to that Article ID

### Steps to reproduce the behavior:

* Open Ticket Zoom Article URL of an Article placed in the middle (e.g. `#/ticket/zoom/#{ticket.id}/#{article_in_the_middle.id}`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by shaedrich** [comment]
I'm afraid, this is broken again in version 5.0

**Comment by MrGeneration** [comment]
Please don't hijack closed issues.
It's working on my machine™
