### ISSUE TITLE
Tree select has no mutli select on ticket selector for overview, triggers, ...

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3333]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Create an overview where tickets with categorie A and categorie B are shown. 

### Actual behavior:

* With tree select for e. g. categories only one categorie is selectable.

### Steps to reproduce the behavior:

* create a ticket categorie with tree select
* create an overview where you want to show ticket with categorie A and categorie B (only one is selectable).

**Comment by mantas** [comment]
Is it possibly related to #3008 ?

**Comment by martini** [comment]
> Is it possibly related to #3008 ?

No. #3008 is about creating an ticket (validation of ticket attributes).

And #3333 is about `ticket selector` in admin interface (e. g. when creating an overview).

**Comment by MrGeneration** [comment]
Due to missing ticket number information I was not able to notify the customer about the fix of this bug.
