### ISSUE TITLE
Trigger-conditions 'Email' required the @ sign

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#3334]
### Infos:

* Used Zammad version: 3.6.x
* Browser + version: all
* 1081823

### Expected behavior:

* If I only want to filter for a part from an email address in the trigger-conditions, I don't always need the @ sign. Therefore I need to be able to enter a value here without a value in front of the @ .

### Actual behavior:

* If you create a trigger and want to store a part of a customer's email address, Zammad always requires an expression before and the @ sign. This means that it is not possible to store a partial expression, if needed.

![image](https://user-images.githubusercontent.com/22768032/102053373-ef82d280-3de7-11eb-9ee4-1313b0034f3d.png)

* Even the @ sign alone is not sufficient. Zammad requires a character before the @:

![image](https://user-images.githubusercontent.com/22768032/102054732-19d58f80-3dea-11eb-8b82-8b5bc7454466.png)

### Steps to reproduce the behavior:

* create a new trigger
* choose the condition: customer --> email
* fill in anything you want without an @ sign.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
The same applies to `tel` attribute.
