### ISSUE TITLE
State list of tickets ignore locale for their sorting

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3335]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any, verified on latest Google Chrome though
* Ticket: 1081951

### Expected behavior:

Zammad will sort the states before listing alphabetically. 
While doing that Zammad will use the locale of the user to do so, not the original state language to improve localization.

### Actual behavior:

Zammad uses the english state names for sorting and seems to append states (like new if applicable) to the list when ever needed. This causes the sorting to look broken in other languages.

Here's a sample screen of states in german (totally off in terms of sorting):

![image](https://user-images.githubusercontent.com/6549061/102198498-bf5c3200-3ec2-11eb-8da3-1eca6b75f841.png)

And now if you look on console you'll also see why:

```
> Ticket::State.pluck(:name)
 => ["new", "closed", "merged", "removed", "waiting for customer", "in progress", "assigned", "waiting for vendor", "deferred"]
```

*Note: The state "new" is always appended in existing tickets. The order of the new state in between other states does fit if you're in a new ticket dialogue.*

### Steps to reproduce the behavior:

* add new custom states
* translate them
* check in existing tickets and new ticket dialogue

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
> ### Expected behavior:
> 
> Zammad will sort the states before listing alphabetically.
> While doing that Zammad will use the locale of the user to do so, not the original state language to improve localization.

@MrGeneration @romitgithub 

I try to understand your issue and the expected result is not matching the unit test:

https://github.com/zammad/zammad/commit/628089c2cd8173b0a31538686fc9368a7415dd59#diff-2bd58930e3546506da7f082c9e110c4f84f601518eba80c99ecd58156e8de44cR938

`geschlossen offen neu`

shouldn't it be 

`geschlossen neu offen`

You changed the sorting at central places and it could be rerendered, now it should always be alphabetically by translated values or is there still this special case with the appended state which is normally not choosable by the user?

**Comment by romitgithub** [comment]
> Expected behavior:
Zammad will sort the states before listing alphabetically.
While doing that Zammad will use the locale of the user to do so, not the original state language to improve localization.

**AND**

> Note: The state "new" is always appended in existing tickets. The order of the new state in between other states does fit if you're in a new ticket dialogue.

@rolfschmidt Both of the above were used to write the logic to sort states. Also I did not change any existing state sorting logic, I only added the translation part in the existing sort function.

@MrGeneration Please correct me if I'm wrong. 

I'll be happy to change the sorting logic to include `new` in the alphabetical sorting as well.

**Comment by MrGeneration** [comment]
The goal was so that translated ticket states would be used for the sorting instead of the original translation. 
This would allow german states to be sorted differently than e.g. english ones.

I don't know how the code implementation looks like, but I believed that this would be a frontend thing. 
Can't provide further feedback on that regard unless I'm missing something.

**Comment by romitgithub** [comment]
@MrGeneration Just wanted to know the role of the **Note:** in this issue description. As in did you want to keep it that way only as mentioned in the note?

**Comment by MrGeneration** [comment]
The note was just a heads up. 
Yes I do expect the new state to be ordered correctly as well if it appears. 

Theoretically it shouldn't matter code wise because the application already knows the list. But that's my theory.

**Comment by romitgithub** [comment]
So if I understand this correctly `geschlossen neu offen` this is the correct order for both `new` and `existing` tickets rather than `geschlossen offen new` which has been the case so far.

**Comment by MrGeneration** [comment]
Yes. Sorry if that got you confused

**Comment by romitgithub** [comment]
Alright. Thanks @MrGeneration 

@rolfschmidt I'll pick this up and fix it.
