### ISSUE TITLE
SAML configuration form does not validate input

### ISSUE THREAD

**Issue by nijel** [zammad/zammad#3338]
### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): zammad.com
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* When entering invalid values in SAML configuration I'd expect to get an error
  * The form accepts anything as "IDP certificate"
  * The form accepts anything as "IDP certificate fingerprint"
  * The form accepts both values while documentation states "Provide only one or the other—do not provide both!"
  * The "Name Identifier Format" can be configured, but I was told not to change it, so maybe it should not be present at all?
  * The form lacks link to the documentation so that user could consult expected configuration
* When using hosted service, it's hard to debug such issues because they only appear in Zammad log

### Actual behavior:

* Anything entered as certificate or fingerprint seems to be saved and used even if it leads to error later when authenticating using SAML

### Steps to reproduce the behaviour:

* Open SAML configuration (Settings / Security / Third-party Applications / Authentication via SAML
* Enter `xx` as both certificate and fingerprint
* Press Submit

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by fliebe92** [comment]
Completed with https://github.com/zammad/zammad/issues/4558 / https://github.com/zammad/zammad/commit/362d437c2ef33ba1cebe949e1d29b02c43fdf2a2.

This will be enhanced with Zammad 6.2. Please let us know if something is still missing in terms of validations.
