### ISSUE TITLE
rake searchindex:rebuild reports 400 Bad Request

### ISSUE THREAD

**Issue by martbock** [zammad/zammad#334]
I have successfully installed zammad on Debian with MySQL and Apache. Now I tried to integrate elasticsearch, but I can't get it to work.
When executing `rake searchindex:rebuild` like the documentation suggests, rake aborts every time:

```
drop indexes...
create indexes...
rake aborted!
Unable to process PUT at http://127.0.0.1:9200/zammad_production
#<UserAgent::Result:0x00000006053290 @success=false, @body=nil, @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">
/opt/zammad/lib/search_index_backend.rb:62:in `index'
/opt/zammad/lib/tasks/search_index_es.rake:19:in `block (2 levels) in <top (required)>'
/opt/zammad/lib/tasks/search_index_es.rake:60:in `block (2 levels) in <top (required)>'
/opt/zammad/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/opt/zammad/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/opt/zammad/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => searchindex:rebuild
```

However, elasticsearch seems to work. I am able to create an index, add data to it and search for stuff (I used the example from [elastic's docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/_index_and_query_a_document.html)).

Honestly, I don't really know what I may be doing wrong.
Thanks in advance, any help is highly appreciated :)

**Comment by monotek** [comment]
https://zammad.org/documentation/install/install-source-debian

**Comment by martbock** [comment]
@monotek it was indeed installed, I removed and reinstalled it. After restarting the elasticsearch service I was able to rebuild the searchindex. I guess something with the plugin installation might have gone bad the first time.
Thanks so much.
