### ISSUE TITLE
Allow OTRS migration to take longer within Browser

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3342]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Zammad migration will be just fine.

### Actual behavior:

If you have fairly big (or super slow) installations, the migration may take more than 4 hours.
By default Zammads timeout for browser based migration for OTRS is 4 hours.

The documentation (up to now) states manual adjustment of a specific file:
![image](https://user-images.githubusercontent.com/6549061/102772996-c08cd380-4388-11eb-91ee-a81c3327846f.png)

However, as this makes things complex in terms of documentation and causes the overview to get drastically worse, I'll be removing that documentation part. Even though we do encourage users with big installations to use console migration instead, 4 hours may be not enough in general.

We added this documentation part some time ago because of this community post:
https://community.zammad.org/t/otrs-import-timeout/2608

I believe that we should by default improve the timeouts.
Not sure if this will have a big impact in general.

### Steps to reproduce the behavior:

* migrate a big OTRS installation via Browser

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
This was already changed with #3653
