### ISSUE TITLE
Allow mailto links in knowledge base (KB) and email signatures.

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3344]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Allow to use `<a href="mailto:somebody@example.com">` links in knowledge base (KB)

### Actual behavior:

* The `<a href="mailto:somebody@example.com">` gets replaced by `somebody@example.com` after storing the answer/saving the article.

### Steps to reproduce the behavior:

* Save an knowledge base (KB) answer with an mailto link.

**Comment by x1ddos** [comment]
Commit 2a6036fb6e036622375297489d9ce1ed80eef17a almost worked except mailto links are prefixed with `http://`.

**Comment by MrGeneration** [comment]
@x1ddos I'm not sure if I understand correctly.

Are you saying you do have mailto links prefixed with `http://` or are you saying that mentioned commit only fixes the issue if you prefix it with `http://`?

**Comment by x1ddos** [comment]
Sorry, I meant the `mailto:` links somehow get prefixed with `http://` while editing a KB article:

![image](https://user-images.githubusercontent.com/25405/106152982-5aad1c00-617e-11eb-9c99-fc4fbd1a0081.png)

No matter what I try doing to remove `http://` prefix, it always gets added back in the end on save, maybe earlier. Not sure if it's only the web editor UI or also somewhere server side.

**Comment by MrGeneration** [comment]
~~Using the linking function will not function.~~
~~If this is a technical question, please post it on the Zammad-Community (https://community.zammad.org).~~

~~If this is a bug, please open a new bug report on this repostiroy.~~

**Comment by x1ddos** [comment]
> Using the linking function will not function.

What will?

The linked commit claims it resolves this issue. I'm saying it didn't, the way the issue is originally described anyway.

**Comment by MrGeneration** [comment]
Please ignore my above statement.

**Comment by martini** [comment]
@mantas it seems to be a UI issue. In recent changes we allowed to use mailto in html sanitzer. But it seems we missed the support of it in this KB UI element, right?

**Comment by mantas** [comment]
@martini yup... I'll take care of this.

@x1ddos a workaround would be to manually edit content of the form in Web Inspector of your browser.
