### ISSUE TITLE
Sanitizer eats "invalid" URLs and removes content after affected URLs

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3347]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified von latest Google Chrome; Customer experienced this on Firefox
* Ticket-Number: #1081892

### Expected behavior:

Zammads Sanitizer does not remove content that's valid text.

### Actual behavior:

Zammads Sanitizer doesn't like placeholder urls in bodies like `https://<placeholder>.sample.tld`.
If Zammad stumbles about above mentioned URL structures, it will remove *everything that comes after that* within the same line.

This affects knowledgebase answers and ticket articles.
Note: It seems to be a difference if you copy such content. In some cases the copied content will somehow survive.

![ticket-sanitizer-eats-fucked-up-urls](https://user-images.githubusercontent.com/6549061/103003143-878f6300-4530-11eb-95ff-2e0cba07d2ea.gif)
![kb-sanitizer-eats-fucked-up-urls](https://user-images.githubusercontent.com/6549061/103003146-88c09000-4530-11eb-911e-ad3b480e353c.gif)

### Steps to reproduce the behavior:

* type a "broken" url with text following after it
* submit the article / answer

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Looks like this is already fixed. Closing.
