### ISSUE TITLE
Wrong version in documentation

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#3353]
In your installation documentation is a blue box with the text:

> We currently support Ubuntu 16.04 LTS and 18.04 LTS.

Above that the installation says, I can install it on 20.04 too. What is correct?
It is possible to use Ubuntu 20.04? Because we want use Zammad in January, because OTRS Community Edition recieve no updates anymore.

![image](https://user-images.githubusercontent.com/1473674/103371463-cb094480-4acf-11eb-94ca-e381c01a3463.png)

Thanks!

**Comment by MrGeneration** [comment]
The version is outdated but reworked currently.
Yes there's an image for Ubuntu 20 too.

I'll be closing this issue because it's in the wrong repository and technically a technical question.

**Comment by Dennis1993** [comment]
Ah okay, now I understand the blue box. Maybe we could change the text to:

> We currently support Ubuntu 16.04 LTS and 18.04 LTS, but we recommend 20.04 LTS.

Thank you!
