### ISSUE TITLE
Outlook ical subscription with LDAP (AD) auth not working

### ISSUE THREAD

**Issue by marandus** [zammad/zammad#3357]
### Infos:

* Used Zammad version: 3.6.0
* Installation method (source, package, ..): source
* Operating system: CentOS 8
* Database + version: PostgreSQL 10.14 (psql --version)
* Elasticsearch version: 7.10.0 OSS
* Browser + version: ---

### Expected behavior:

* When copying the ical Link from the Profile -> Calendar page and adding it as an Internet Calendar to Outlook 365, Outlook should ask for credentials and then import the Calendar.

### Actual behavior:

* Outlook asks for credentials but entering the LDAP (AD) credentials used to log into Zammad does not work. This happens with the global URI https://HOSTNAME/ical/tickets as well as the calendar specific URIs.

### Steps to reproduce the behavior:

* Copy ical link
* Add to Outlook as Internet Calendar
* Enter LDAP credentials
* The request for credentials will pop up again each time the credentials are entered

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by marandus** [comment]
If there is anything we can do to help you verify this issue please let me know.

**Comment by thorsteneckel** [comment]
Hi @marandus - can't verify. It works for me. What I did:

`docker run --rm -p 10389:10389 -p 10636:10636 rroemhild/test-openldap`

Zammad Console
```ruby
# Store LDAP config
Setting.set('ldap_config', {"host_url"=>"ldaps://localhost:10636",
 "ssl_verify"=>false,
 "options"=>{"dc=planetexpress,dc=com"=>"dc=planetexpress,dc=com"},
 "option"=>"dc=planetexpress,dc=com",
 "base_dn"=>"dc=planetexpress,dc=com",
 "bind_user"=>"cn=admin,dc=planetexpress,dc=com",
 "bind_pw"=>"GoodNewsEveryone",
 "wizardData"=>
  {"backend_user_attributes"=>
    {"dn"=>"dn (e.g., cn=Amy Wong+sn=Kroker,ou=people,dc=planetexpress,dc=com)",
     "cn"=>"cn (e.g., Amy Wong)",
     "sn"=>"sn (e.g., Kroker)",
     "description"=>"description (e.g., Human)",
     "displayname"=>"displayname (e.g., Bender)",
     "employeetype"=>"employeetype (e.g., Ship's Robot)",
     "givenname"=>"givenname (e.g., Amy)",
     "jpegphoto"=>"jpegphoto (binary data)",
     "mail"=>"mail (e.g., amy@planetexpress.com)",
     "ou"=>"ou (e.g., Intern)",
     "title"=>"title (e.g., Professor)",
     "uid"=>"uid (e.g., amy)",
     "userpassword"=>"userpassword (e.g., {SSHA}wJv9s2Z9m0bS0R1WY7B7BEfDUVOC86cpV/uC0w==)"},
   "backend_groups"=>
    {"cn=admin_staff,ou=people,dc=planetexpress,dc=com"=>"cn=admin_staff,ou=people,dc=planetexpress,dc=com",
     "cn=ship_crew,ou=people,dc=planetexpress,dc=com"=>"cn=ship_crew,ou=people,dc=planetexpress,dc=com"},
   "user_attributes"=>
    {"login"=>"Login",
     "firstname"=>"Firstname",
     "lastname"=>"Lastname",
     "email"=>"Email",
     "web"=>"Web",
     "phone"=>"Phone",
     "mobile"=>"Mobile",
     "fax"=>"Fax",
     "department"=>"Department",
     "address"=>"Address",
     "note"=>"Note"},
   "roles"=>{"1"=>"Admin", "2"=>"Agent", "3"=>"Customer"}},
 "user_uid"=>"uid",
 "user_filter"=>"(objectClass=person)",
 "group_uid"=>"dn",
 "group_filter"=>"(objectClass=group)",
 "user_attributes"=>
  {"givenname"=>"firstname", "sn"=>"lastname", "mail"=>"email", "uid"=>"login", "telephonenumber"=>"phone"},
 "group_role_map"=>
  {"cn=admin_staff,ou=people,dc=planetexpress,dc=com"=>["1"], "cn=ship_crew,ou=people,dc=planetexpress,dc=com"=>["2"]},
 "unassigned_users"=>"sigup_roles"})

# Perform LDAP import to sync users
ImportJob.create(name: 'Import::Ldap').start

# Assign full permissions to all Groups to Agent Role
Role.find_by(name: 'Agent').group_names_access_map = Group.all.pluck(:name).map { |group_name| [group_name, 'full'] }.to_h

# Assign example Ticket to Bender, because he clearly does all the work
# Also make sure that the Ticket will be visible in the calendar
Ticket.first.update!(
  owner: User.find_by(login: 'bender'),
  state: Ticket::State.find_by(name: 'pending reminder'),
  pending_time: 5.minutes.from_now,
)
```

After that I performed the request via: `curl --user bender:bender http://localhost:3000/ical/tickets`

And received the expected result:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:icalendar-ruby
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP:20210122T130900Z
UID:bf0f244f-4eb4-4a55-a5c3-c46401b39c54
DTSTART:20210122T131300Z
DTEND:20210122T131300Z
CLASS:PRIVATE
DESCRIPTION:T#70001
SUMMARY:pending reminder ticket: 'Welcome to Zammad!' customer: Nicole Brau
 n (Zammad Foundation)
END:VEVENT
END:VCALENDAR
```

I hope this helps to find your issue. Please refer to the  [community board](http://community.zammad.org/) for (further) technical assistance.

**Comment by fuerni81** [comment]
I have the same problem.
With Outlook 2019 I can connect to ical from ZAMMAD, but not with Outlook 365.
Over browser I can see the ical informations

**Comment by MrGeneration** [comment]
@fuerni81 please don't recycle already closed issues. This also sounds like a technical question, this repository is the wrong place for those.

Locking conversation to contributors only to reduce further hijacks.
