### ISSUE TITLE
Zammad 3.6.0 cannot configure proxy

### ISSUE THREAD

**Issue by Itay-Sharoni-zz** [zammad/zammad#3362]
### Infos:

* Used Zammad version: 3.6.0
* Installation method (source, package, ..): Source
* Operating system: Debian 9
* Database + version: MySQL 8.0.21
* Elasticsearch version: 5.6.16
* Browser + version: Microsoft Edge  87.0.664.66

### Expected behavior:

Under:
Admin > System > Network Proxy Settings
when configuring proxy and pressing submit, it should accept settings and apply proxy
![image](https://user-images.githubusercontent.com/65607183/104116683-88dbd080-5323-11eb-95b3-e4f75fbbf966.png)

### Actual behavior:
When pressing submit, I get error: #<ActionController::UnfilteredParameters: unable to convert unpermitted parameters to hash>
![image](https://user-images.githubusercontent.com/65607183/104116699-af017080-5323-11eb-9e89-5f3b0418a576.png)

### Steps to reproduce the behavior:
Admin > System > Network Proxy Settings > add any setting > submit.
also, if I edit this setting directly from database it does not accept my settings

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by PogBorris** [comment]
Same problem here.. my solution to set the proxy settings:

1. open up a terminal session on your zammad server
2. open a rails console : zammad run rails c
3. Enter your Settings

Setting.set('proxy', 'proxy.example.com:3128')
Setting.set('proxy_username', 'some user')
Setting.set('proxy_password', 'some pass')

e: **for me the Proxy Connection isnt working anyways!**
