### ISSUE TITLE
Japanese character is garbled. 

### ISSUE THREAD

**Issue by hiromayu** [zammad/zammad#3368]
### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): apt install zammad
* Operating system: ubuntu 20.04 
* Database + version:  psql (PostgreSQL) 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1)
* Elasticsearch version: sorry I couldn't find
* Browser + version: FireFox 84.0.2 

### Expected behavior:
 e-mail at Japanese-encoding displayed by Japanese character.

### Actual behavior:
Some e-mail at Japanese-encoding displayed garbled character.
(subject of e-mail displayed correctlly.only main text of mail is garbled.)

Similar problem like
 Japanese encoding 7-bit iso-2022-jp is processed incorrectly #2498
but above issue is closed. so I make this one.

### Steps to reproduce the behavior:
・I will send eml file to support.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sample can be found here:
#1082760
