### ISSUE TITLE
Incoherent email fetching

### ISSUE THREAD

**Issue by Marf54** [zammad/zammad#3374]
### Infos:

* Used Zammad version: 3.6.0-1610545422.444c3a5d.focal
* Installation method (source, package, ..): Apt package
* Operating system: Ubuntu focal (20.04)
* Database + version: postgresql 12
* Elasticsearch version: 7.10.2
* Browser + version: All browser

### Expected behavior:

* Emails are fetched and tickets are created.

### Actual behavior:

* An email is received by our email provider (Gmail).
* The email doesn't appear to be fetched in log (`- no message`) but the email is read in the mailbox.
* The support's ticket is assigned to a wrong number (always an already closed ticket).

When the email is assigned to a wrong number, with the link of the notification, we have the following error but it seems to be not relevant to the issue:

```
not allowed to show? this #<Ticket id: 324, group_id: 3, priority_id: 2, state_id: 4, organization_id: nil, number: "18324", title: "########", owner_id: 1, customer_id: 77, note: nil, first_response_at: nil, first_response_escalation_at: nil, first_response_in_min: nil, first_response_diff_in_min: nil, close_at:
 "2021-01-18 09:12:38", close_escalation_at: nil, close_in_min: nil, close_diff_in_min: nil, update_escalation_at: nil, update_in_min: nil, update_diff_in_min: nil, last_contact_at: "2021-01-15 15:41:02", last_co
ntact_agent_at: nil, last_contact_customer_at: "2021-01-15 15:41:02", last_owner_update_at: nil, create_article_type_id: 1, create_article_sender_id: 2, article_count: 1, escalation_at: nil, pending_time: nil, ty
pe: nil, time_unit: nil, preferences: {"channel_id"=>3}, updated_by_id: 19, created_by_id: 77, created_at: "2021-01-15 15:41:02", updated_at: "2021-01-18 09:12:38"> (Pundit::NotAuthorizedError)
```

After reaching this state, all new fetched emails are marked as read on the mailbox and tickets are no longer created on zammad.

After some search, if we rebuild the elasticsearch index, the next fetch works properly. But if we disable the elasticsearch integration, we have the same problem.

### Steps to reproduce the behavior:

* Install zammad with elasticsearch
* Connect your zammad instance to gmail with imap protocol.
* Try to create a ticket from an email.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
