### ISSUE TITLE
Import::OTRS.diff_worker creates/imports tickets without articles

### ISSUE THREAD

**Issue by HristoA** [zammad/zammad#3379]
### Infos:

* Used Zammad version: 3.6.0
* Installation method (source, package, ..): any
* Operating system: CentOS 7
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Diff-import from OTRS creates new tickets in Zammad with Article, attached files etc. All to be 100% as it at OTRS side.

### Actual behavior:

* Diff-import from OTRS creates new tickets in Zammad without article or only few of the articles from OTRS
* Ticket title, number, created-time, customer, group, owner, state are imported as expected

### Steps to reproduce the behavior:

* Follow guide from https://docs.zammad.org/en/latest/migration/otrs.html for OTRS 5
* Try to use `Import::OTRS.diff_worker`
* Data that come from ZammadMigrator is correct and ticket have Articles
 
The same is reported here: https://community.zammad.org/t/import-otrs-diff-worker-creates-imports-tickets-without-articles/1745
I am searching already from where problem come. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by HristoA** [comment]
**Update:**
After many attempts I get to the point that missing Article popup/appear in Zammad. Strange is that i just add more and more logs in my debug script between few runs. So i start to look more crossly to:
```
/otrs/public.pl?Action=ZammadMigrator;Key=****;Object=Ticket;Subaction=Export;Offset=0;Limit=0;Diff=1
```
and catch that RAW JSON for one particular case is :
```
"Articles": [],
"TicketID": "123",
```
But in the same time under OTRS Ticket: 123 have one article that is just a plain text. So what I do:
- First fill into OTRS table `ticket_changed` needed ticket id: 123
- Open again URL `/otrs/public.pl?Action=ZammadMigrator;Key=****;Object=Ticket;Subaction=Export;Offset=0;Limit=0;Diff=1`
- Repeat the process

Result: After few cycles i get response with `Articles`

May be this is not only related to Diff case and also to importing one? It's hard for me to  reproduce it in stable behavior.
Thanks

**Comment by HristoA** [comment]
Hi again.
I think that locate the root of the problems.

- Add one record to `ticket_changed` with timestamp -9 hours form now
```
ERROR: OTRS-CGI-03 Perl: 5.10.1 OS: linux Time: Thu Jan 21 09:09:19 2021

 Message: Error while deleting Diff cache entry  for ticket with TicketID '123'.

 RemoteAddress: X.X.X.X
 RequestURI: /otrs/public.pl?Action=ZammadMigrator;Key=*****;Object=Ticket;Subaction=Export;Offset=0;Limit=0;Diff=1

 Traceback (21194): 
   Module: Kernel::System::Zammad::Migrator::Ticket::Export Line: 322
   Module: Kernel::System::Zammad::Migrator::_GenericFunctionCaller Line: 152
   Module: Kernel::System::Zammad::Migrator::Export Line: 101
   Module: Kernel::Modules::ZammadMigrator::Run Line: 80
   Module: Kernel::System::Web::InterfacePublic::Run Line: 220
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_public_2epl::handler Line: 40
   Module: (eval) (v1.99) Line: 204
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 204
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 170
   Module: ModPerl::Registry::handler (v1.99) Line: 31
```
result at  `/otrs/public.pl?Action=ZammadMigrator;Key=****;Object=Ticket;Subaction=Export;Offset=0;Limit=0;Diff=1` is `Articles:[]`

- Add the same ticket as record at `ticket_changed` with timestamp -24 hours form now. Result is the same error in OTRS logs but now i have  `Articles` filled in JSON

**Conclusion:**
If we want to fill manual data to table `ticket_changed` we need to use some old date for `create_time` because OTRS logic use it in some way and show Article with creation timestamp after this date. I think that this issue can be closed.

**Propose:**
Add more info about this under https://docs.zammad.org/en/latest/migration/otrs.html

**Comment by MrGeneration** [comment]
> Propose:
Add more info about this under https://docs.zammad.org/en/latest/migration/otrs.html

This page and others are currently undergoing QA as per https://github.com/zammad/zammad-documentation/pull/156

Right now I wouldn't recommend changes to the documentation.

**Comment by jvkroeger** [comment]
Hi @MrGeneration and @HristoA I have the same issue as described above when doing a diff import. The initial import works well but when running a diff import, there are tickets without articles. Any chance to reopen this issue or https://community.zammad.org/t/import-otrs-diff-worker-creates-imports-tickets-without-articles/1745 ?

Used Zammad version: 4.1.0-1629278242.03345214.bionic amd64
Installation method (source, package, ..): apt package
Operating system: Ubuntu 18.04.5 LTS
Database + version: 10.18 (Ubuntu 10.18-0ubuntu0.18.04.1)
Elasticsearch version: 7.14.0 amd64
Browser + version: not used, import done via console

OTRS version: 6.0.14

**Comment by MrGeneration** [comment]
Please **DO NOT** hijack closed issues and especially don't ask technical questions on this repository.
Please switch over to the community.
