### ISSUE TITLE
Autocomplete Email-Address-Fields

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#338]
Is it possible to integrate an autocompletion for the To, CC (, BCC?) field in ticket creation and answer with all known email-addresses?

**Comment by martini** [comment]
Hi @tobibe 

not currently. but it's on the road.

 -Martin

**Comment by martini** [comment]
@jepf keyword is bootstrap-tokenfield.js

**Comment by waggonservice** [comment]
**+1** This would be a very helpful feature to save time.

**Comment by metasnw** [comment]
+1 also from me. Its one of the very few things in zammad taking uneccessary amount of time

would be cool to know if it will be done anywhere in the future as this issue is one year old by now

**Comment by ktwe** [comment]
Absolutely agree. Is there an ETA for this feature? I'm following it for a while and it is hopping from milestone to milestone. :-)

**Comment by tobibe** [comment]
Hello @martini ,
will this be realized in one of the next milestones?
Greetings
tobibe

**Comment by thorsteneckel** [comment]
Locking conversation. There is no new input. +1 and requesting comments create noise and distraction. We are working hard on the next upcoming/most requested features and projects of our support customers. If you want to state your interest in the feature and give valuable input please give the initial post a 👍 reaction and we are able to evaluate it. We will lock all distracting issues from now on. Thanks for your understanding.

**Comment by martini** [comment]
Implemented, thanks to @mrflix
