### ISSUE TITLE
Counter for KB answers

### ISSUE THREAD

**Issue by MustafaTongul** [zammad/zammad#3380]
### Infos:

* Used Zammad version: 3.0 and onward
* T#1082873 

### Expected behavior:

* Knowledge Base entries should display a counter indicating how many answers each category and their subcategory contains.
* In each category, regardless of main or subcategory, this indicator should be displayed.

### Actual behavior:

* There is no indicator of how many answers each category contains.

This is feature request

**Comment by FiloSpaTeam** [comment]
Working on these feature in a initial phase i created a counter_cache system to update automatically the answers counter for each category; but later i found a js function that automatically count each deep answer.

So there are 2 ways:
1) Count answers in model using counter_cache
2) Count answers in view using js

Which way? :D

**Comment by MrGeneration** [comment]
Sorry for the wait, thank you for your patience!

We've came to point that this would be useful to show internal for agents.
On public interface there should be a knowledge base admin setting (which defaults to `off`) that allows administrators to enable the answer counter on public pages.

We feel that a counter on public pages may be too technical for most of our user base but also feel that it could come in handy for others.
