### ISSUE TITLE
Parameters in text modules are not updated after customer is changed

### ISSUE THREAD

**Issue by benmo** [zammad/zammad#3387]
### Infos:

* Used Zammad version: 3.6 
* Installation method (source, package, ..): scope unknown (tested with source)
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: scope unknown (tested with Edge 88.0.705.50)

### Expected behavior:

* When inserting text modules, parameters regarding the customer (e.g. #{ticket.customer.firstname}) should use the values of the current customer

### Actual behavior:

* When changing the customer of a ticket and staying on the page / ticket after the change, the parameters of the text module will be replaced with the values of the old customer
* Example: Ticket belongs to Bob; Agent changes customer of ticket to Andrew; Agent stays on the page and tries to use text module with parameter #{ticket.customer.firstname}; #{ticket.customer.firstname} will be replaced with "Bob" instead of "Andrew"

### Steps to reproduce the behavior:

* Create a ticket
* Change the customer from A to B
* Insert a text module with a parameter regarding customer data (i.e. Customer first name)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
@benmo i can not reproduce the described issue in the current stable version.

**Comment by MrGeneration** [comment]
Oh boy sorry, how did that get the need verification label from myself.
Indeed this is a technical question and not possible.
