### ISSUE TITLE
HTML structure that is not parseable by jQuery causes JavaScript error that breaks Ticket Zoom view.

### ISSUE THREAD

**Issue by clicks** [zammad/zammad#3393]
### Infos:

* Used Zammad version: 3.6.0-1607430494.246b029e.xenial 
* Installation method (source, package, ..): ppa 
* Operating system: Ubuntu 16.04
* Database + version: postgresql 9.5
* Elasticsearch version: 6.8.13
* Browser + version: Firefox 85, Chrome 88

### Expected behavior:

* Clicking on the link for a specific ticket https://zammad.example.org/#ticket/zoom/424654 (from search results) opens the ticket and shows it's contents.

### Actual behavior:

* The ticket title is shown in the left sidebar, but the right frame is completely blank.
The browser console shows a javascript error:
```application-b4...e1.js:1 Uncaught TypeError: Cannot read property 'childNodes' of null
    at v (application-b4...e1.js:1)
    at Function.rt.parseHTML (application-b4...e1.js:3)
    at Function.t.signatureIdentifyByHtml (application-b4...e1.js:81)
    at n.render (application-b4...e1.js:51)
    at n.<anonymous> (application-b4...e1.js:51)
    at n.render (application-b4...e1.js:27)
    at n.e.maybeRender (application-b4...e1.js:28)
    at n.maybeRender (application-b4...e1.js:27)
    at n.e [as constructor] (application-b4...e1.js:28)
    at new n (application-b4...e1.js:51)
v @ application-b4...e1.js:1
rt.parseHTML @ application-b4...e1.js:3
t.signatureIdentifyByHtml @ application-b4...e1.js:81
n.render @ application-b4...e1.js:51
(anonymous) @ application-b4...e1.js:51
(anonymous) @ application-b4...e1.js:27
e.maybeRender @ application-b4...e1.js:28
(anonymous) @ application-b4...e1.js:27
e @ application-b4...e1.js:28
n @ application-b4...e1.js:51
e.run @ application-b4...e1.js:51
(anonymous) @ application-b4...e1.js:51
e @ application-b4...e1.js:51
a.render @ application-b4...e1.js:49
(anonymous) @ application-b4...e1.js:49
a.load @ application-b4...e1.js:49
(anonymous) @ application-b4...e1.js:49
ajax.success @ application-b4...e1.js:49
l @ application-b4...e1.js:2
fireWith @ application-b4...e1.js:2
n @ application-b4...e1.js:3
(anonymous) @ application-b4...e1.js:3
load (async)
send @ application-b4...e1.js:3
ajax @ application-b4...e1.js:3
t.addCurrentRequest @ application-b4...e1.js:78
(anonymous) @ application-b4...e1.js:78
t.request @ application-b4...e1.js:78
t.request @ application-b4...e1.js:78
ajax @ application-b4...e1.js:26
a.fetch @ application-b4...e1.js:49
(anonymous) @ application-b4...e1.js:49
n @ application-b4...e1.js:49
o @ application-b4...e1.js:79
e.set @ application-b4...e1.js:79
(anonymous) @ application-b4...e1.js:79
t.set @ application-b4...e1.js:79
s.interval @ application-b4...e1.js:26
(anonymous) @ application-b4...e1.js:26
a @ application-b4...e1.js:49
n.startController @ application-b4...e1.js:80
(anonymous) @ application-b4...e1.js:80
n.executeSingel @ application-b4...e1.js:80
n.run @ application-b4...e1.js:80
n.execute @ application-b4...e1.js:80
t.execute @ application-b4...e1.js:80
n @ application-b4...e1.js:50
(anonymous) @ application-b4...e1.js:79
(anonymous) @ application-b4...e1.js:79
(anonymous) @ application-b4...e1.js:8
e.match @ application-b4...e1.js:9
e.matchRoute @ application-b4...e1.js:9
e.matchRoutes @ application-b4...e1.js:9
e.change @ application-b4...e1.js:9
dispatch @ application-b4...e1.js:2
g.handle @ application-b4...e1.js:2
Show 25 more frames
26
```

It is possible to open the ticket via the API, but I can't identify anything weird in it's content.

### Steps to reproduce the behavior:

* Open the ticket.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
We'd need that special ticket and (before that) a complete debug output like the one abvoe, just all of it.
Would that be possible?

**Comment by mantas** [comment]
@clicks any chance that somebody touched the database directly and removed some stuff? Maybe permissions were changed and this user do not have access to related bit anymore?

I've a feeling that some ticket relations/dependencies are missing (or not accessible) and the view cannot be built anymore. This would still be a bug, because view building should be resilient to such issues.

**Comment by clicks** [comment]
Of course, but I'm not sure how to provide you this information? Do you need access to our instance (which is no problem) or can I extract the ticket in useable format for you? Don't want to post it publicly as it contains customer information.

The production log doesn't show an error or warning when the ticket is opened.

@mantas Don't think so. But we had problems with the cache filling the temp directory to 100% in the last days and had to run Rails.clear.cache to solve it. Might this be the cause?

**Comment by mantas** [comment]
@clicks cache clearing should be not an issue. Assuming that you restarted the instance afterwards and now cache has plenty of space to fully rebuild.

The crash is in javascript and unfortunately production log is for server-side errors only. All the data is only in web inspector.

Please email us support@zammad.com with a reference to this issue.

**Comment by mantas** [comment]
@clicks after a quick look at our code, I've a couple ideas where may be the issue. For now, please send the dump of the ticket itself to above email. Thank you!
