### ISSUE TITLE
Not working in Korean

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#3395]
### Infos:

* Used Zammad version:3.6.x
* Installation method (source, package, ..):debian pakage
* Operating system:debian10
* Database + version:debian pakage
* Elasticsearch version:debian pakage
* Browser + version:firefox 85

### Expected behavior:

* All functions working even after setting up in Korean

### Actual behavior:

* When the language is set to Korean, almost all functions such as ticket creation and ticket opening do not work.

### Steps to reproduce the behavior:

* Set Language to Korean

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
This issue is now fixed on our translations server. Go to Manage -> Translations and click "Get latest translations" to fetch the fixed version.

This also fixes an identical issue with Malay, Romanian and Serbian
