### ISSUE TITLE
S/SMIME: Intermediate-CA verification fails

### ISSUE THREAD

**Issue by b-zam** [zammad/zammad#3397]
### Infos:

* Used Zammad version: 3.6.0
* Installation method (source, package, ..): source
* Operating system: Ubuntu 20.04 LTS
* Database + version: MySQL 8
* Elasticsearch version: 7.10.1
* Browser + version: Firefox 85

### Expected behavior:

* Signed E-Mails with trusted Root CA & Intermediate CA should be displayed as verified

### Actual behavior:

* Security Error is displayed: "Unable to find certificate for verification "

### Steps to reproduce the behavior:

* Send a singed E-Mail to Zammad Mailbox by using a certificate which is signed by an intermediate CA. The certificates of the used Root-CA and Intermediate-CA are imported to Zammad.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Smells like a technical question under the hood, anway, to double tap - please send a mail to support [at] zammad [dot] com referencing this issue and provide the following:

* eml of the affected article
* certificate files required
   *Note: Please don't provide your private key to ensure the integrity of your certificate.*
* a screenshot from within your Zammad instance of the affected article


I will then provide feedback on this issue.

**Comment by b-zam** [comment]
Hello,

it's difficult for me to send you the eml or certificates because of data protection rules.

I found it on myself, that the problem seems to be that my certificates contain the E-Mail-Address in the Subject alternative name-Field: RFC822-Name=mail@addre.ss. In the incoming.rb only the subject is checked, but not the SAN entry: message_cert.issuer.to_s == cert.parsed.subject.to_s && verify_ca.verify(message_cert)

**Comment by MrGeneration** [comment]
Sorry but this is a technical question. I#m not sure yet ho RFC822 does play into this context. I couldn't find the S/MIME context I'm afraid.

Zammad expects `/CN=example@domain.tld/emailAddress=example@domain.tld` for S/MIME certificates. 
This does not apply to CA certificates for incoming verification as long as the certificate is correct and signed by said CA.

See:
![image](https://user-images.githubusercontent.com/6549061/107281924-a1422680-6a5a-11eb-8868-280c3c1f799f.png)

We'll improve the affected documentation page to make the scopes clearer.

**Comment by b-zam** [comment]
Although you describe this as "works as desigend", Zammad declares valid 
certificates as invalid.
Our certificates contain the email-address in the "X509v3 Subject 
Alternative Name" field, which is valid and accepted by mail clients 
(i.e. Outlook, Thunderbird).
So in my opinion it also be shown as valid in Zammad.

Example certificate data:

[...]
Subject: serialNumber = [...], C = DE, O = [...], OU = [...], CN = [...] 
Bastian
X509v3 extensions:
[...]
X509v3 Subject Alternative Name: email:bastian[...]@[...].de



Am 2021-02-08 22:12, schrieb Marcel:
> Sorry but this is a technical question. I#m not sure yet ho RFC822
> does play into this context. I couldn't find the S/MIME context I'm
> afraid.
> 
> Zammad expects
> `/CN=example@domain.tld/emailAddress=example@domain.tld` for S/MIME
> certificates.
> This does not apply to CA certificates for incoming verification as
> long as the certificate is correct and signed by said CA.
> 
> See:
> ![image](https://user-images.githubusercontent.com/6549061/107281924-a1422680-6a5a-11eb-8868-280c3c1f799f.png)
> 
> We'll improve the affected documentation page to make the scopes 
> clearer.

**Comment by MrGeneration** [comment]
> Our certificates contain the email-address in the "X509v3 Subject
> Alternative Name" field, which is valid and accepted by mail clients
> (i.e. Outlook, Thunderbird).
> So in my opinion it also be shown as valid in Zammad.

That's out of the sponsored requirement and our supported ranges.
This would be a feature request that should live in the community: https://community.zammad.org

**Comment by thorsteneckel** [comment]
(Pre-dated) duplicate of #3528 - will be fixed with 4.1.
