### ISSUE TITLE
"korean" is "한국어"

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#3399]
### Infos:

* Used Zammad version:3.6.x

### Expected behavior:

* Mark Korean(한국어)

### Actual behavior:

* Mark Korean(한국의)
* ![Screenshot_2021-02-09 Support - 사용자](https://user-images.githubusercontent.com/74412971/107305510-75f52100-6ac6-11eb-824e-eeef4af28573.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Hi @0hys0

Could you confirm if following screenshot looks good?

![Screenshot 2021-02-09 at 08 33 24](https://user-images.githubusercontent.com/36944/107324933-8cdd4880-6ab1-11eb-8416-5a48ba3a7e88.png)

**Comment by ghost** [comment]
@mantas Yes, It's nice!

**Comment by mantas** [comment]
This issue is now fixed on the translations server.

Run `Locale.load` in Rails console to fetch it right away. Other instances will pick it up after next update.
