### ISSUE TITLE
state "Warten auf Erinnerung" and noone assigned

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#340]
Sometimes I find it useful to set the state of a ticket to "Warten auf Erinnerung". And have nobody assigned to it. My expectation was, that in this case everybody in the group would get a notification when the "wait till" time is reached. 

But instead, nobody get's a notification. This is a bug to me.

**Comment by rkaldung** [comment]
There's the possibility to enable notifications for **pending reminder reached** for not assigned tickets. Available via the user's profile.

**Comment by zabarabab** [comment]
Thanks!
