### ISSUE TITLE
Allow HTML in mail templates

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#3407]
Is there any way to allow html in the triggers? We use a trigger to send a mail notification for users who opens a ticket.
The mail in Outlook 2016 is very ugly. I tested HTML but the result is:

![image](https://user-images.githubusercontent.com/1473674/107845718-12c50080-6dde-11eb-8e86-9d28b223a422.png)

Zammad 3.6.x (latest version)
Ubuntu 20.04

**Comment by mantas** [comment]
Trigger attributes are sanitised. But if you would edit it directly (Rails console or database), it may work. Please ask on our community forums https://community.zammad.org and someone may have tips on how to handle this workaround.
