### ISSUE TITLE
Optional subject for email

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#341]
Sometimes we like to send an email with a different subject than the title of current ticket. At the moment we need to rename the ticket to the wanted subject and then back.

**Comment by martini** [comment]
@tobibe that's correct. It's (as always) a design issue. I'll discuss it with our designer (maybe we can create a config option for this).

**Comment by martini** [comment]
Hi @mrflix 

please can you improved the CSS style of this new feature (preferences settings for ticket zoom)?

<img width="508" alt="screen shot 2017-07-05 at 07 18 40" src="https://user-images.githubusercontent.com/110226/27850094-672880c6-6152-11e7-8ed9-e91b781b0a59.png">

app/assets/javascripts/app/views/ticket_zoom/setting.jst.eco

Thanks!

 -Martin

**Comment by martini** [comment]
https://github.com/zammad/zammad/commit/0065028ee61a7a433cce58c9501bd40340fdd5a4
