### ISSUE TITLE
Microsoft 365: The refresh token has expired due to inactivity. The token was issued on 2020-11-17T13:30:55.3656422Z and was inactive for 90.00:00:00.

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3411]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all
* Ticket: #1083881, #1083908 

### Expected behavior:

* Microsoft 365 channel should not expire

### Actual behavior:

* Microsoft 365 channel expires after 90 days.

### Steps to reproduce the behavior:

* Add a microsoft 365 channel
* Work with it for 90 days.

``` 
AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2020-11-17T13:30:55.3656422Z and was inactive for 90.00:00:00
```

**Comment by rolfschmidt** [comment]
looks like there is a bug. it looks like that the request for the refresh_token also contains a new refresh token which needs to be replaced:

https://docs.microsoft.com/en-us/graph/auth-v2-user#5-use-the-refresh-token-to-get-a-new-access-token

but we do not merge the result key refresh_token yet, only access_token

https://github.com/zammad/zammad/blob/1aa4e68c6c9ff7dd2cfbc864c78a464c4df85c3a/lib/external_credential/microsoft365.rb#L238

**Comment by oschmidteu** [comment]
Just ran into the same error today.

**Comment by thorsteneckel** [comment]
Is there a workaround that can be applied while we work on the final fix?

**Comment by mantas** [comment]
Re-adding the channel should fix it

**Comment by oschmidteu** [comment]
Can't remove the channels via the Backend and dind't found a command for the console.

**Comment by mantas** [comment]
`Channel.where(area:  'Microsoft365::Account').destroy_all` should do the trick

**Comment by thorsteneckel** [comment]
Fixed for `develop`. `stable` is currently running on CI and will probably be available in the morning 🚀
