### ISSUE TITLE
Using inbound outbound email account from google

### ISSUE THREAD

**Issue by matsvitt** [zammad/zammad#342]
Hi there,

I would like to use an email account at google (using a corporate domain) for inbound and outbound mail. However -  I always get the error from google "log in via web". I would assume that I could heal that if it would be possible to provide ports etc. But where? 

thanks

Matthias

**Comment by martini** [comment]
Hi @matsvitt 

Zammad is trying the Google-Account ports automatically. I'm not sure what Google means with "log in via web". 

Can it be, that your account is only usable via Google web interface? And if you want to use imap/pop3 (as Zammad want to do it) you need to activate this in Google web interface first?

Feedback would be welcome, then we can improve the error message.

Thanks!

 -Martin

**Comment by monotek** [comment]
Is  Goolges 2 step auth activated?

https://www.google.com/landing/2step/

**Comment by matsvitt** [comment]
thanks for helping. I managed to solve the problem. The reason was that I did not allow "more unsecure apps" to access the account. That property can be set in the GMail account under "My account"

**Comment by eliasp** [comment]
The following things could be done in zammad:

- handle this specific IMAP error code/msg and log/show a warning to the user and point him to the Google documentation
- implement OAuth2 support so that adding GMail accounts would be possible and the OAuth2 token would be used for IMAP auth instead

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
