### ISSUE TITLE
Unable to process elasticsearch index background jobs (reason: rejected execution of coordinating operation).

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3422]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Process all process elasticsearch index background jobs

### Actual behavior:

* Certain elasticsearch index background jobs are not processable if payload generated by Zammad is higher as elasticsearch is accepting.

### Steps to reproduce the behavior:

* Configure elasticsearch to accept 100MB payload (which is default).
* Create a ticket with content about 300MB
* Then the elasticsearch index background job will fail with:
```
"reason":"rejected execution of coordinating operation [coordinating_and_primary_bytes=0, replica_bytes=0, all_bytes=0, coordinating_operation_bytes=217400878, max_coordinating_and_primary_bytes=107374182]
```

Solution would be to increase accepted payload size by elasticsearch or to configure max. payload size for elasticsearch by Zammad.

**Comment by MrGeneration** [comment]
Side note to this topic:
We currently suggest to configure ES to allow up to 400 MB payloads which usually should be fairly enough.
See: https://docs.zammad.org/en/latest/install/elasticsearch.html#step-2-suggested-configuration
