### ISSUE TITLE
Form width not shown correctly in firefox

### ISSUE THREAD

**Issue by BigAndini** [zammad/zammad#3424]
Hello,

maybe you want to know this.

I see the forms in zammad too small right now like this in firefox:
![grafik](https://user-images.githubusercontent.com/8452304/109016980-02066b80-76b7-11eb-976e-ca2b3a25a985.png)

Within the according scss file it looks like a firefox bug was fixed with display: table-cell;, however this does not use the full width. So when I add a width: 100%; to this css statement that fixes this issue for me:
![grafik](https://user-images.githubusercontent.com/8452304/109017135-30844680-76b7-11eb-81e1-8795b54515d9.png)

Don't know if others have this issue as well, but maybe you want to fix it. :)

Regards
Andi

### Infos:

* Used Zammad version: zammad-3.6.0-1614149546.5c1934b4.centos7.x86_64
* Installation method (source, package, ..): rpm package
* Operating system: CentOS 7
* Database + version: postgresql-server-9.2.24-4.el7_8.x86_64
* Elasticsearch version: elasticsearch-5.6.16-1.noarch
* Browser + version: 86.0 (64-Bit)

**Comment by martini** [comment]
Hi @BigAndini 

thanks for the feedback! We also noticed this today morning. :-o

There is already an issue #3420 which is already fixed in develop and for stable in CI. I guess it will be fixed in stable by today too.

Greeting,

 -Martin
