### ISSUE TITLE
Old JQuery version delivered

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#3431]
I use zammad 3.6.x and if I want to implement the chat to my wordpress site, the script is delivered an old JQuery version which is marked as a security risk:

![image](https://user-images.githubusercontent.com/1473674/109397583-b44c6600-7937-11eb-8d90-638d986aa17d.png)

A question: Why I cant use my before loaded JQuery 3.5.1 from my wordpress itself? In my theme JQuery is loaded in the head before but I cant use it with the chat.
An async load is not possible.

**Comment by martini** [comment]
@Dennis1993 there is a issue template which need to be used for issues. Without this issue template we close issue because if feels like we're not worth it.

As note, there is a non jquery version available (as beta), just use https://your.zammad.host/assets/chat/chat-no-jquery.min.js

**Comment by Dennis1993** [comment]
The template is not important, but here....

### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): package (apt)
* Operating system: Ubuntu 20.04
* Database + version: Portgres
* Elasticsearch version: 7
* Browser + version: Microsoft Edge


### Expected behavior:
Latest JQuery version in cht preview


### Actual behavior:
Old version is delivered by Zammad with known security bugs


### Steps to reproduce the behavior:
Create a chat

Yes I'm sure this is a bug and no feature request or a general question.


![image](https://user-images.githubusercontent.com/1473674/109410537-b8aa6a80-799b-11eb-9dbf-c0cc07e38a06.png)

I fixed that for wordpress. Wordpress is using jQuery in many themes but not with the $. If I change the $ in the first line to jQuery it works (with latest jQuery version). So if you change 2.1.4 to 3.5.1 this ticket is done :)

Thanks

**Comment by martini** [comment]
Hi @Dennis1993 

> As note, there is a non jquery version available (as beta), just use https://your.zammad.host/assets/chat/chat-no-jquery.min.js

If you have feedback if this non jquery version works fine for you, would be great!

**Comment by cortopy** [comment]
I was also going to open an issue related to the old version of Jquery. When running `npm audit`, there are two security advisories that come up. One is extremely serious:

- https://www.npmjs.com/advisories/328 (__severity high__)
- https://www.npmjs.com/advisories/796 

I've started using the no-jquery version and it works for me
