### ISSUE TITLE
Languange selection in web app is not working anymore

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3432]
### Infos:

* Used Zammad version: develop (2021-03-01)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Be able to select language via own profile

### Actual behavior:

* Language selection is not shown/not usable

![image](https://user-images.githubusercontent.com/110226/109462463-ccb99f00-7a63-11eb-867d-bbf99162a613.png)

**Comment by efinal** [comment]
@martini  the change 5b6f032 move the corresponding css into 'phone' section which makes the language selection works in desktop mode, but, failed in mobile mode.

**Comment by MrGeneration** [comment]
@efinal Please open an independent issue for this and link this issue as regression. Thank you.
