### ISSUE TITLE
zammad_backup.sh Error

### ISSUE THREAD

**Issue by tfisinger** [zammad/zammad#3441]
Hey,

seit dem letzten Update habe ich ein Problem mit der Backupfunktion:

zammad_backup.sh: 6: /opt/zammad/contrib/backup/functions: Syntax error: "(" unexpected

VG
Fisi

**Comment by monotek** [comment]
Please write in english and use the issue template. 

There's been no change in the backup scripts. See: 
https://github.com/zammad/zammad/tree/stable/contrib/backup
