### ISSUE TITLE
Cannot select multiple tickets in ticket overview with shift+click in Firefox

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#3449]
### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): docker-compose
* Operating system: Debian 10
* Database + version: PostgreSQL from docker-compose
* Elasticsearch version: from docker-compose
* Browser + version: Firefox 86

### Expected behavior:

* Click on a ticket checkbox in the ticket overview
* Hold the shift key and then click on another ticket checkbox further below, then release the shift key
* Zammad should check all tickets from the first checkbox to the second checkbox

### Actual behavior:

* This works as expected in Chromium 89.
* It does not work in Firefox 86. Clicking on the second checkbox while holding down the shift key will not check the tickets between the first and the second checkbox, and also won't check the second checkbox itself.

### Steps to reproduce the behavior:

* Use Firefox
* Attempt to select multiple tickets with the shift key

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by j-herden** [comment]
I can confirm this bug on Firefox 78.9.0esr (64-Bit) with Zammad 4.0 and 3.6

**Comment by MrSnoozles** [comment]
Confirming with Zammad 4.0

**Comment by MrGeneration** [comment]
Locking conversation to contributors only to reduce noise during verification phase for users bumping this issue with confirmation.
