### ISSUE TITLE
IMAP mail fetching stops working on spam mail and invalid email format

### ISSUE THREAD

**Issue by dnauck** [zammad/zammad#345]
Due a invalid spam mail the mail fetching task stops working.

The only solution to solve this issue was to delete that invalid mail by hand from the mail server. I think zammad should ignore invalid mails and fetch all valid ones instead of stopping the work. Or at least notify me that it does not fetch new mails anymore.

production.log:

	I, [2016-11-02T13:38:41.761799 #14497]  INFO -- : fetching imap (example.com/tickets@domain.com port=993,ssl=true)
	I, [2016-11-02T13:38:42.089433 #14497]  INFO -- :  - message 1/7
	E, [2016-11-02T13:38:42.177100 #14497] ERROR -- : ERROR: #<Encoding::InvalidByteSequenceError: "\x83" on GB2312>
	E, [2016-11-02T13:38:42.182928 #14497] ERROR -- : ERROR: SenderIsSystemAddress: #<NoMethodError: undefined method `addrs' for #<Mail::UnstructuredField:0x007ff3a5ea0e70>>
	E, [2016-11-02T13:38:42.189968 #14497] ERROR -- : can't run postmaster pre filter Channel::Filter::IdentifySender
	E, [2016-11-02T13:38:42.190039 #14497] ERROR -- : #<Exceptions::UnprocessableEntity: Invalid email>
	E, [2016-11-02T13:38:42.190202 #14497] ERROR -- : ERROR: Can't process email, store it for bug reporting under /opt/zammad/tmp/unprocessable_mail//50636489be7552a3d49fd839bcf5e9c8.eml
	E, [2016-11-02T13:38:42.190246 #14497] ERROR -- : ERROR: #<Exceptions::UnprocessableEntity: Invalid email>
	E, [2016-11-02T13:38:42.190743 #14497] ERROR -- : Can't use Channel::Driver::Imap: #<RuntimeError: #<Exceptions::UnprocessableEntity: Invalid email>["/opt/zammad/app/models/user.rb:810:in `check_email'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in `block in halting'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.7.1/lib/active_model/validations/callbacks.rb:113:in `run_validations!'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activemodel-4.2.7.1/lib/active_model/validations.rb:338:in `valid?'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:58:in `valid?'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:83:in `perform_validations'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:37:in `save'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block (2 levels) in save'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block in save'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:285:in `save'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:34:in `create'", "/opt/zammad/app/models/channel/filter/identify_sender.rb:163:in `user_create'", "/opt/zammad/app/models/channel/filter/identify_sender.rb:53:in `run'", "/opt/zammad/app/models/channel/email_parser.rb:406:in `block in _process'", "/opt/zammad/app/models/channel/email_parser.rb:403:in `each'", "/opt/zammad/app/models/channel/email_parser.rb:403:in `_process'", "/opt/zammad/app/models/channel/email_parser.rb:375:in `process'", "/opt/zammad/app/models/channel/driver/imap.rb:183:in `block in fetch'", "/opt/zammad/app/models/channel/driver/imap.rb:157:in `each'", "/opt/zammad/app/models/channel/driver/imap.rb:157:in `fetch'", "/opt/zammad/app/models/channel.rb:62:in `fetch'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/app/models/channel.rb:30:in `fetch'", "(eval):1:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:90:in `eval'", "/opt/zammad/app/models/scheduler.rb:90:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:57:in `block (2 levels) in start_job'", "/opt/zammad/app/models/scheduler.rb:56:in `loop'", "/opt/zammad/app/models/scheduler.rb:56:in `block in start_job'"]>
	E, [2016-11-02T13:38:42.190834 #14497] ERROR -- : ["/opt/zammad/app/models/channel/email_parser.rb:388:in `rescue in process'", "/opt/zammad/app/models/channel/email_parser.rb:375:in `process'", "/opt/zammad/app/models/channel/driver/imap.rb:183:in `block in fetch'", "/opt/zammad/app/models/channel/driver/imap.rb:157:in `each'", "/opt/zammad/app/models/channel/driver/imap.rb:157:in `fetch'", "/opt/zammad/app/models/channel.rb:62:in `fetch'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/app/models/channel.rb:30:in `fetch'", "(eval):1:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:90:in `eval'", "/opt/zammad/app/models/scheduler.rb:90:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:57:in `block (2 levels) in start_job'", "/opt/zammad/app/models/scheduler.rb:56:in `loop'", "/opt/zammad/app/models/scheduler.rb:56:in `block in start_job'"]

**Comment by martini** [comment]
Hi @dnauck 

great! Can you attach the spam email to this issue? I want to create a test case.

Thanks!

 -Martin

**Comment by martini** [comment]
@dnauck the mails for this issue should be located under tmp/unprocessable_mail/

**Comment by dnauck** [comment]
Hello,

attached the spam mail:

[spam.eml.gz](https://github.com/zammad/zammad/files/576473/spam.eml.gz)

**Comment by martini** [comment]
Thanks for the email! It's fixed now https://github.com/zammad/zammad/commit/4d42c54bf1e8773eeea878a1e9ce596272f4f3f1.
