### ISSUE TITLE
"Drop files here" drag area not always hiding

### ISSUE THREAD

**Issue by Stubenhocker1399** [zammad/zammad#3460]
### Infos:

* Used Zammad version: 3.6.0-1615986441.da478686.bionic, 4.1/stable
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04.5 LTS 
* Browser + version: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)

### Expected behavior:

* "Drop files here" drop area always hiding itself when releasing a drag

### Actual behavior:

* When releasing dragged text in an close proximity below the actual drop area results in it staying visible

### Steps to reproduce the behavior:

* Select text
* Start dragging selected text
* Release it slightly below the box

Also see this gif:
![Peek 2021-03-19 19-01](https://user-images.githubusercontent.com/6693160/111825530-dbb7a280-88e7-11eb-8887-05dd0beef014.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
At least on my machine™ this does not always appear and requires kind of very specific dropping.
