### ISSUE TITLE
Debian-Package: nginx not a dependency

### ISSUE THREAD

**Issue by alexbrueckel** [zammad/zammad#347]
Nginx shouldn't be a dependency but rather recommended because it kind of breaks setups where an apache is used already.

**Comment by monotek** [comment]
If you like to add an Apache proxy config i could add it to the postinstall script.
I also just added Apache2 to the pkgr.yml for Debian/UIbuntu in the develop branch.
If you use the package and Apache is installed Nginx will not replace Apache2 now.

**Comment by alexbrueckel** [comment]
Great, thanks!

**Comment by alexbrueckel** [comment]
Great, thanks!
