### ISSUE TITLE
Macros are not displayed within the Mobile View

### ISSUE THREAD

**Issue by MustafaTongul** [zammad/zammad#3473]
### Infos:

* Used Zammad version: 4.0.x
* Installation method (source, package, ..): Any
* Operating system: iOS 14.4.1
* Browser + version: Chrome Mobile App 87.0.4280.77
* T#1085229

### Expected behavior:

* By tapping on the arrow beside the "update" button all available macros are displayed in the selection. This Issue occurs when using Zammad on a mobile device within the ticket zoom mask.
* 
![image](https://user-images.githubusercontent.com/76220675/112508978-55400c80-8d90-11eb-9aad-2ea9dc2c0791.png)

### Actual behavior:

* By tapping on the arrow besides the "update" button the selection of macros are not displayed properly.

![image](https://user-images.githubusercontent.com/76220675/112509497-d13a5480-8d90-11eb-92f2-12dfbb40917d.png)

* Only a small black bar appears. This Issue occurs when using Zammad on a mobile device within the ticket zoom mask.

### Steps to reproduce the behavior:

* Create at least one macro.
* Open up a ticket on your mobile device, then tap the arrow beside the "update" button.

Yes I'm sure this is a bug!

**Comment by Stubenhocker1399** [comment]
Removing this `overflow: auto` from the mobile css seems to fix this issue, while of course removing the vertical scroll.

https://github.com/zammad/zammad/blob/cfa02c90382197e342ab2b9b8f3f5b3e694a7bff/app/assets/stylesheets/zammad.scss#L7563
