### ISSUE TITLE
[question] Docker not adviced?

### ISSUE THREAD

**Issue by enoch85** [zammad/zammad#3476]
Hi,

We are using OTRS today and are looking at something that can replace that soon. We found Zammad and it looks like the proper replacement. Very neat, clean and easy to work with - nice job! :+1: 

In our production environment we're using Portainer for all our Docker containers, but looking at the Zammad Docs it says *We currently do not support Docker environments in productive use. If you run Zammad on docker, it is fine. But we just support the application!*

I've seen a lot of guides online (Medium for one) that states that Zammad can be installed in production, yet you advice against it.

This leads us to ask, why do you advice against it? I mean is it more prune to break? You don't have any good solutions if it does? Of course we have backups, and the easiest way to restore would just be to restore a backup in case anything would go wrong - or no?

Also, is it possible to email in tickets into Zammad? In our current setup our customers sends emails to OTRS with their issues, and a ticket is automatically generated from that email.

Thanks!

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by monotek** [comment]
We provide a docker-compose repo, which is already used for a lot of production installations:
https://github.com/zammad/zammad-docker-compose

What you're talking about is the single docker image, which is only made for quick testing and therefore not production ready:
https://github.com/zammad/zammad-docker

**Comment by MrGeneration** [comment]
It would be great if we wouldn't continue on this issue if I'm telling the user it's the wrong place.
User found the remark on the documentation: https://docs.zammad.org/en/latest/install/docker-compose.html

This is still a valid point.

**Comment by enoch85** [comment]
> Sorry, but this seems to be a technical question.

> we'll transfer the relevant information to this repo!

On Github you can transfer whole issues to another repo, and if this is the wrong place for this type of question, please do that.

> We provide a docker-compose repo, which is already used for a lot of production installations:

> What you're talking about is the single docker image, which is only made for quick testing and therefore not production ready:
https://github.com/zammad/zammad-docker

Great info! That's all I needed.
