### ISSUE TITLE
Removal task from scheduler job possibly can block delayed jobs

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3481]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): package
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on latest Google Chrome
* Ticket: 1085322
* Reference Issue: #3416 

### Expected behavior:

The scheduler will work on background jobs and skip / remove those that have locks to no longer existing objects.

### Actual behavior:

If you have a scheduler task to remove ticket data on a regular basis and also have a ticket update at the same moment, some tasks may end up still available in delayed jobs list. If the job is being processed, it will fail because of missing references.

This state forces admins to manually `.delete` the job in question.

```
# manual re run throws:
Traceback (most recent call last):
        2: from (irb):38
        1: from config/initializers/delayed_jobs_ensure_active_job_lock_removal.rb:10:in `remove_active_job_lock'
Delayed::DeserializationError (Job failed to load: undefined class/module Transaction::BackgroundJob. Handler: "--- !ruby/object:Transaction::BackgroundJob\nitem:\n  :object: User\n  :object_id: 16\n  :user_id: 5\n  :created_at: !ruby/object:ActiveSupport::TimeWithZone\n    utc: &1 2021-03-26 16:02:25.545408154 Z\n    zone: &2 !ruby/object:ActiveSupport::TimeZone\n      name: Etc/UTC\n    time: *1\n  :type: update\n  :changes:\n    last_login:\n    - !ruby/object:ActiveSupport::TimeWithZone\n      utc: &3 2021-03-26 15:50:07.847000000 Z\n      zone: *2\n      time: *3\n    - !ruby/object:ActiveSupport::TimeWithZone\n      utc: &4 2021-03-26 16:02:25.528000000 Z\n      zone: *2\n      time: *4\nparams:\n  :interface_handle: application_server\n")
irb(main):041:0> Delayed::Job.first
=> #<Delayed::Backend::ActiveRecord::Job id: 44630569, priority: 0, attempts: 0, handler: "--- !ruby/object:Transaction::BackgroundJob\nitem:\n...", last_error: nil, run_at: "2021-03-26 16:02:26", locked_at: "2021-03-29 09:16:34", failed_at: nil, locked_by: "host:ticket pid:31395", queue: nil, created_at: "2021-03-26 16:02:26", updated_at: "2021-03-29 
```

In this job sample the attempts where not raised. 
The scheduler was practically blocked by this one job causing a stack of delayed jobs. 
The delayed job in this case was a User object task with ticket lock.

**Note:** 
The customer did upgrade from Zammad 3.6 to Zammad 4.0 in roughly the time window the delayed jobs were created. It may possibly a race condition during updates only. I'm not sure through.

### Steps to reproduce the behavior:

* have a scheduler that removes tickets
* by accident still have delayed jobs that handle user updates with a lock on a removed ticket

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
@MrGeneration is it maybe possible to get the full traceback or do you think the log is gone now?

**Comment by rolfschmidt** [comment]
or do you remember maybe what background job type was crashing?

**Comment by MrGeneration** [comment]
No that's too far in the past, I'm sorry.
I'll keep my eyes open for similare ones.

**Comment by mgruner** [comment]
This one is old and not reproducible. @rolfschmidt @MrGeneration do you think we could close it as "not planned" for now?

**Comment by MrGeneration** [comment]
Did you check this in the parameters provided? e.g. Zammad 3.6 --> newer ?

**Comment by mgruner** [comment]
@MrGeneration no, I just saw your comment that you are going to look out for new occurrences of the issue 2 years ago. So I wondered if this issue might be irrelevant now.

**Comment by MrGeneration** [comment]
I can't tell if it's still relevant. Close it if you believe it no longer happens or is applicable.

**Comment by mgruner** [comment]
Thanks. We don't really know that, but let's close it until it reappears. Then we can get back to it.
