### ISSUE TITLE
Latest update has removed my entire user/customer list and/or broke search indexing

### ISSUE THREAD

**Issue by ABagOfFritos** [zammad/zammad#3484]
### Infos:

* Used Zammad version: 4.0.x
* Installation method (source, package, ..): community repo
* Operating system: Ubuntu 16.04.7 LTS
* Database + version: unknown
* Elasticsearch version: unknown
* Browser + version: unknown
* Server is inherited from previous sysadmin, documentation is lacking.  Any help on how to get more of the above information is appreciated.

### Expected behavior:

* We type in a partial customer name and that name (along with other similar results) shows up for us to select them when creating a new ticket
* We go to our users list, we should see all of our customers and staff

### Actual behavior:

* No results come up when searching for a customer
* Our agent/customer/admin, etc lists are all empty

### Steps to reproduce the behavior:

* See above, steps included in behaviour

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by ABagOfFritos** [comment]
> 
> 
> Sorry, but this seems to be a technical question.
> Please note that this repository is the wrong place for technical questions.
> Instead, please refer the Zammad community over at: https://community.zammad.org .
> 
> In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!
> 
> If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
> _If you're paying customer already, please consult your Zammad support for assistance! :-)_

This is very definitely a bug caused by an update.

**Comment by MrGeneration** [comment]
It's a technical question, not a bug.
I'm not telling you because I wanna bug you, but because it's this way.

**Comment by ABagOfFritos** [comment]
> 
> 
> It's a technical question, not a bug.
> I'm not telling you because I wanna bug you, but because it's this way.

Unexpected behaviour isn't a bug?

I'll post on the other forum as well, but I don't quite see the distinction you're making here as I'm not asking for technical help, I'm asking for how to fix what is almost definitely a bug.

**Comment by MrGeneration** [comment]
You're asking a classic question that is not bound to a specific version but dependencies and so on. 
I'm limitting the conversation of this issue to contributors only to reduce the noise to the over 2000 subscribers of this repo.
