### ISSUE TITLE
mention in email body breaks email parsing

### ISSUE THREAD

**Issue by j-herden** [zammad/zammad#3489]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): Repo  https://dl.packager.io/srv/rpm/zammad/zammad/stable/el/7/x86_64/
* Operating system: CentOS 7
* Database + version: postgresql  9.2.24-4.el7_8
* Elasticsearch version:  7.12.0-1
* Browser + version: Firefox 78.9.0esr (64-Bit)

### Expected behavior:

* missing rights for mentions should not break the email parsing 
* the email should not show up under /opt/zammad/tmp/unprocessable_mail, if it contains a mention with '@...'

### Actual behavior:

* parsing the mail generates an error: "ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/edd73f695ee7517e0ea3bd0143832594.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<RuntimeError: User 23490 has no permission to mention other Users!>"
* running this command: zammad run rails r 'Channel::EmailParser.process_unprocessable_mails'
  repeates the error again and again
* temporarily assigning the role 'agent' to the mentioned user makes the email run through

### Steps to reproduce the behavior:

* probably sending an email with a mention in the body, but I did not try a second time. 

Yes I'm sure this is a bug and no feature request or a general question.

Complete output attached. 
[zammad_mention_error.txt](https://github.com/zammad/zammad/files/6241453/zammad_mention_error.txt)

**Comment by rolfschmidt** [comment]
Hi @j-herden ,
i think i understand whats the problem. I guess the problem is that the mail was sent by a customer which tried to answer on a mail of an agent which contained a mention? Does this match your case? Is the user 23490 a customer user?

**Comment by j-herden** [comment]
Hi @rolfschmidt,

thanks for your quick replay.
 
Yes, user 23490 is a customer user and he answered to an email of an agent. 
Yes, inside of the quoted agents text of is a mention of another agent. 
But the user wrote '@Jens: bist' in his text too. 
So there might be two possible triggers for the error.

**Comment by rolfschmidt** [comment]
Hi @j-herden ,
great thanks for your fast feedback. I will work on fix now.
