### ISSUE TITLE
ticket search cache issue

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#349]
Hi,
Reproduce:

1. Search for "Golden Ticket" in the navigation bar
2. Click on the extendend search list
3. Ticket list will be shown with a low limit of the search result
4. Change the search term in the search overview to "Golden Ticke" and back to "Golden Ticket"
5. Now the ticket list will show much more results.

It looks like that there is a cache key issue which does not take care about the limit information.

Best regards,
Rolf

**Comment by martini** [comment]
@rolfschmidt can be closed, right?

**Comment by rolfschmidt** [comment]
yup
