### ISSUE TITLE
Error 500:{"error":"undefined method `+' for nil:NilClass"} - Creating Overview

### ISSUE THREAD

**Issue by Kieranwest** [zammad/zammad#3490]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 18.04
* Database + version: Default with Package
* Elasticsearch version: Default with Package
* Browser + version: Chrome 89

### Expected behavior:

* Creation of Overview

### Actual behavior:

* Overview Creation fails with the error code 500: {"error":"undefined method `+' for nil:NilClass"}

### Steps to reproduce the behavior:

* Create Overview 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Hi @Kieranwest 

can you attach the `log/production.log`. With this file we can see whats going wrong.

**Comment by Kieranwest** [comment]
[production.log](https://github.com/zammad/zammad/files/6246129/production.log)
Uploaded the file for you @martini . Removed all it's contents and redid the issue to avoid exposing sensitive information.

**Comment by mantas** [comment]
@Kieranwest are you creating the Overview using API or user interface? Could you post the screenshot of Overview creation dialog before submitting?

Did you remove all other Overviews before creating this one?

**Comment by martini** [comment]
@Kieranwest thanks for the fast feedback. It seems that it only arrears if no overview exists and a new overview (the first one)  should get created.

**Comment by Kieranwest** [comment]
@martini Yep! I did infact remove all other overviews. Is there any way I can essentially restore those without needing to reinstall ? Haven't tried using the API to create an Overview yet so might try that later today.

**Comment by mantas** [comment]
@Kieranwest a quick fix would be to run contents of https://github.com/zammad/zammad/blob/develop/db/seeds/overviews.rb in Rails console

Proper fix to allow creation of Overview when there're no other Overviews is coming in no time.

**Comment by Kieranwest** [comment]
> @Kieranwest a quick fix would be to run contents of https://github.com/zammad/zammad/blob/develop/db/seeds/overviews.rb in Rails console
> 
> Proper fix to allow creation of Overview when there're no other Overviews is coming in no time.

Not 100% how to run this? Can it be ran a similar way to a script ? 

EDIT: Made the changed manually found in #3490 and restarted Zammad services.

**Comment by MrGeneration** [comment]
How to use the console:
https://docs.zammad.org/en/latest/admin/console.html

Please note that technical support is out of this repository. 
If you need further assistance, please consult the community.
