### ISSUE TITLE
Selecting Textmodules, Knowledge Base Articles and the Mentions Feature are not working for mobile devices on Zammad 4.0

### ISSUE THREAD

**Issue by MustafaTongul** [zammad/zammad#3495]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): any
* Operating system: iOS & Android
* Database + version: Any
* Elasticsearch version: Any
* Browser + version: Any
* Ticket #1085673

### Expected behavior:

*by typing "::" the Textmodules are showing up
![image](https://user-images.githubusercontent.com/76220675/113672252-c39d9c80-96b7-11eb-9257-0c31d38d356c.png)

*by typing "@@" you can mention your colleagues
![image](https://user-images.githubusercontent.com/76220675/113672172-ab2d8200-96b7-11eb-84fa-f350c67b5d51.png)

*by typing "??" you can access the Knowledge Base and use articles as answers.
![image](https://user-images.githubusercontent.com/76220675/113672106-92bd6780-96b7-11eb-935e-7c7b5aecdf43.png)

*This behavior should also occur on mobile devices

### Actual behavior:

*by typing "::" the Textmodules are not showing up
![image](https://user-images.githubusercontent.com/76220675/113673602-7f130080-96b9-11eb-82b9-7177237dee5c.png)

*by typing "@@" you cannot mention your colleagues
![image](https://user-images.githubusercontent.com/76220675/113673644-8d611c80-96b9-11eb-9f5e-7935621cf398.png)

*by typing "??" you cannot access the Knowledge Base and use articles as answers.
![image](https://user-images.githubusercontent.com/76220675/113673724-a23db000-96b9-11eb-814f-2898dd56e69d.png)

*This issue only occurs on mobile devices

### Steps to reproduce the behavior:

*Open Zammad on your mobile device (Tablet or Smartphone)
*Open an already existing ticket.
*Try accessing the Textmodules by typing "::"
*Try accessing the mentions-feature by typing "@@"
*Try accessing the knowledge base articles by typing "??"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by romitgithub** [comment]
@MrGeneration Just wanted to know if this is happening on iOS as well?

**Comment by martini** [comment]
@romitgithub there is an iphone simulator with xcode which you can start locally. Then you can test it directly.

**Comment by romitgithub** [comment]
Oh alright. Thanks will try that 👍🏼
