### ISSUE TITLE
Agents can create new tags even if prohibited by the settings

### ISSUE THREAD

**Issue by kgoldinger** [zammad/zammad#3501]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): package
* Operating system: CentOS 7.9
* Database + version: PostgreSQL 9.2.24
* Elasticsearch version: 7.12
* Browser + version: Tested on Edge 89, Chrome 89 and Firefox 87
* Ticket#1094624 

### Expected behavior:

* As defined in the tag settings users should not be able to create new tags

### Actual behavior:

If the browser is closed an reopened with a new (unsaved) ticket, every agent is able to create his own tags

### Steps to reproduce the behavior:

* Log in to zammad
* Open a new ticket (don't save it)
* Close the browser
* Open a new Browser and go to zammad again
* insert a new random text to the the tags field of the new ticket
* save the ticket 

--> the random tag will be created. This leads in a lot of misspelled tags which makes it hard to find similar tickets by tag

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I think that's a very edgy one. 
I was forced to add any tag again to the draft so Zammad would let me add it.

If I re-visit my ticket draft without touching the tag field, nothing will happen (as it's empty).

**Comment by fliebe92** [comment]
Hi @kgoldinger, I used some time and tried to reproduce your described behavior. I guess it's fixed in the meantime, however, I had no luck to reproduce it with your detailed steps.

If you still encounter the same issue, please, let me know just by answering this issue here. I will re-open the report if it's still valid.

Thanks for your understanding. 😎

**Comment by kgoldinger** [comment]
Hi @fliebe92 
Indeed we still encounter this issue regularly. Ive done some futher tests and i can reproduce the issue reliably in our production environment (5.3.1), our testenvironment (6.0) and even on a fresh installed (docker compose)  6.0 system. Please have a look at the attached screencast:
https://github.com/zammad/zammad/assets/43206134/0968d8c6-6175-4b65-bfe7-91e5fa4dc683
It is crucial to the process to close the browser process and not only the tab.

thanks  for your efforts and best regards
Kay

**Comment by fliebe92** [comment]
Hi @kgoldinger, wow, thanks for your effort to test this (again) and for this nice screencast! By closing the complete browser, it's working differently in the end. Issue is now reopened.
