### ISSUE TITLE
Microsoft 365 Account doubling upon reauthentication of a disabled account

### ISSUE THREAD

**Issue by martinseener** [zammad/zammad#3507]
### Infos:

* Used Zammad version: 4.0.x
* Installation method (source, package, ..): Zammad Hosted
* Operating system: -
* Database + version: -
* Elasticsearch version: -
* Browser + version: Latest Firefox

### Expected behavior:

When disabling a Microsoft 365 account and clicking on "reauthentication", I expect the reauth to work and re-enabling of the account.

### Actual behavior:

Upon successful re-auth the account is re-enabled BUT also a new one is also created. This only happens if the account has been "Disabled" prior. If it was enabled, this does not happen.

### Steps to reproduce the behavior:

Add a Microsoft 365 account. Disable it and click on Reauthenticate.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by fliebe92** [comment]
Hi @martinseener,

I just used some time trying to reproduce your reported behavior. Unfortunately, I was not able to reproduce it using Zammad 5.4. Maybe you could spend some time on your side and try to verify in your Zammad instance that the described behavior is working as expected right now.

If you still encounter any problems, feel free to re-open this report with new information.

Thanks!

**Comment by martinseener** [comment]
Hi Florian,
in the newer Zammad this was fixed already and we never saw this issue again. Sorry that I missed to close this. Have a nice day!
