### ISSUE TITLE
In certain cases correct filename of email attachments is not recogniced

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3509]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* show correct file names of email attachments

### Actual behavior:

* In certain cases, "Content-ID" is snow as filename instand

### Steps to reproduce the behavior:

* Process email with the following headers, the filename if the attchment is `32497.1617621278.2`

```
--Apple-Mail=_5FA1E6E6-1C40-4E5D-8231-1F0EF0E45CCF
Content-Type: application/others; name="ITN21A07-000089.jpg"
Content-ID: <32497.1617621278.2@humeexp>
Content-Transfer-Encoding: base64
```

**Comment by MrGeneration** [comment]
Sounds like a duplicate of https://github.com/zammad/zammad/issues/2425

**Comment by martini** [comment]
Duplicate of #2425
