### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#351]
Zammad wish of Martin Farkas:
"Create possibility to use zammad on android via app"

**Comment by monotek** [comment]
Imho responsive design which could be used on all platforms makes more sense

**Comment by thorsteneckel** [comment]
Currently the performance of native applications is way better than one of web apps. To achieve the best user experience we should go with native apps as long as this gap exists.

**Comment by monotek** [comment]
I don't believe this is true for zammad, because it already feels like a native app thanks to the use of websockets. Native apps just mean you have to take care for at least 3 different clients (Web, Android, IOS). Imho this woul be a lot more time consuming than having a responsive website...

**Comment by Neuxz** [comment]
There are platforms which can take care of multiplatform for you.
There are 2 wich i can recommend.

# Xamarin(C#) 
- UWP(Windows)
- Android
- IOs
- much more with mvvm

# Codename One(Java)
- Android 
- IOs 
- Windows 8 / Windows 8 / Phone(one bin)

The main problem is that you must create a new stand alone client for the UI or you must embed it with semething like crosscode.

**Comment by hanneshal** [comment]
I lock the conversation. We are aware what is possible and that users like to use Zammad on smaller-mobile devices. When we have the resources available we will work on this. 

So long it makes no sense to discuss about it. 

We will update you, when we have something new on this.

**Comment by dominikklein** [comment]
With Zammad 6, we implemented a mobile view with PWA-Support (https://user-docs.zammad.org/en/latest/extras/mobile-view.html). Currently, it's not planned to build a native mobile app.
