### ISSUE TITLE
csv import example file download (organizations) is empty

### ISSUE THREAD

**Issue by blu-IT** [zammad/zammad#3514]
Hello,

on a (nearly) fresh zammad installation (4.0) via docker compose I tried downloading the csv import example file for organizations.
Clicking on the link https://myhelpdesk.mytestsystem.de/api/v1/organizations/import_example I get an empty csv file.
There are no field names inside that file, nothing. I think this is a bug ;-)

### Infos:

* Used Zammad version: v. 4.0.0
* Installation method (source, package, ..): docker compose (for production environment)
* Operating system: Ubuntu 18.04 LTS
* Database + version: postgres v. 9.6
* Elasticsearch version: unknown
* Browser + version: Firefox 87.0

### Expected behavior:

* Getting a useable csv template with at least field names like it is served when clicking on csv template for user import

### Actual behavior:

* I am getting an empty template

### Steps to reproduce the behavior:

* In the admin section, go to organizations, click on "Import" and on "Download CSV template".

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This is edgy.
You forgot to mention that you removed all organizations before.

The only reason I accept this above is because it appears **if no organizations are available**.

**Comment by blu-IT** [comment]
> This is edgy.
> You forgot to mention that you removed all organizations before.

That's right. I removed the organizations before.

> The only reason I accept this above is because it appears **if no organizations are available**.

 Thanks!
