### ISSUE TITLE
Show other active agents in ticket detail view (collision prevention)

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#352]
Sometimes (especially on new tickets) it's interesting which other agent is active in the same ticket. It would be cool to see a list of other active agents in the same view.

**Comment by martini** [comment]
A preview of this feature. Any feedback is welcome!

<img width="1200" alt="screen shot 2016-12-28 at 14 13 40" src="https://cloud.githubusercontent.com/assets/110226/21522947/222ad640-cd0a-11e6-8288-b887ad31a59d.png">

Discussions:

- Show also if somebody has already changed something (unsaved changes)
- Show avatar with gray overlay if agent is not online currently

**Comment by martini** [comment]
It's in upcoming Zammad 1.2.

**Comment by martini** [comment]
<img width="138" alt="screen shot 2017-01-04 at 12 52 06" src="https://cloud.githubusercontent.com/assets/110226/21762266/08ec11ec-d658-11e6-98a6-36c23585bfe3.png">


- Already in work: Show also if somebody has already changed something (unsaved changes)
- Idle: Show avatar with gray overlay if agent is not online currently
