### ISSUE TITLE
ks_c_5601-1987 encoding is not supported by zammad

### ISSUE THREAD

**Issue by geonmo** [zammad/zammad#3521]
### Infos:

* Used Zammad version: zammad-3.6.0-1613047982.332fdca8.centos7.x86_64
* Installation method (source, package, .. ): package( yum install )
* Operating system: CentOS Linux release 7.7.1908 (Core)
* Database + version:  postgresql-server-9.2.24-2.el7_7.x86_64
* Elasticsearch version: elasticsearch-7.6.1-1.x86_64
* Browser + version: FireFox 87.0(64bit)

### Expected behavior:

*  When an email encoded in ks_c_5601-1987 is received, the message should be received normally.
*  Since ks_c_5601-1987 is not a supported encoding type in ruby, it should be decoded with the encoding as EUC-KR or CP949.
(All three can be considered the same encoding)

### Actual behavior:

* The following error occurs in production.log of zammad when mail is received. ERROR -- : #<ArgumentError: unknown encoding name - ks_c_5601-1987>
* I'm not sure if it's because of the results above, but since the mail was received, the Notification Mail feature in zammad becomes inoperable and the number of delayed Jobs increases.

### Steps to reproduce the behavior:

* Receive emails encoded in ks_c_5601-1987.

**Comment by mantas** [comment]
Hi @geonmo 

Could you give an example email in this encoding? Please make sure it does not contain sensitive details!

**Comment by geonmo** [comment]
Hello, Mantas.I am sending you the contents as an attachment. -----------------------원본 메세지-----------------------보낸사람: "Mantas Masalskis ***@***.***>받는사람: zammad/zammad ***@***.***>참조: Geonmo Ryu ***@***.***>,Mention ***@***.***>보낸시간: 2021-04-22 16:22:07 GMT +0900 (ROK)제목: Re: [zammad/zammad] ks_c_5601-1987 encoding is not supported by zammad (#3521)Hi @geonmoCould you give an example email in this encoding? Please make sure it does not contain sensitive details!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mantas** [comment]
@geonmo looks like Github is filtering out attachments. Could you send it to support@zammad.com and mention this github issue? Thank you!

**Comment by geonmo** [comment]
@mantas I sent an email with attachments. Could you check that?

**Comment by mantas** [comment]
@geonmo got it, thank you!

**Comment by mantas** [comment]
@geonmo unfortuantely I cannot reproduce the bug. I tried to import the sample email. It works just fine in latest `develop` branch! No error and it renders Korean text just fine.

Then I noticed this in your original report:

> Used Zammad version: zammad-3.6.0-1613047982.332fdca8.centos7.x86_64

Could you check if this error still persists in latest version?

**Comment by geonmo** [comment]
@mantas Hello, Mantas.

The same issue hasn't recurred yet after the program upgrade.

First of all, I will close this issue and contact you again when it comes back.

Thank you.
