### ISSUE TITLE
Google and Microsoft 365 are missing filter & signature page content

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3522]
### Infos:

* Used Zammad version: 4.0 stable
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any 
* Elasticsearch version: any
* Browser + version: verified on Google Chrome v90.0.4430.85, cross checked on a latest FireFox
* Ticket: #1085757

### Expected behavior:

Zammad provides filter and signature listings and settings within:

* email channel
* google channel
* microsoft365 channel

### Actual behavior:

Zammad provides filter and signature listings and settings within the email channel only. 
If you're switching to either filter or signature tabs within google and microsoft365 channel, the content below will stay blank.

![bug-microsoft-google-channel_signatures-and-filters](https://user-images.githubusercontent.com/6549061/115688414-6cf0bd80-a35b-11eb-88b0-949348bf9383.gif)

### Steps to reproduce the behavior:

* go to email, google and microsoft 365 channels and compare the behavior in between those for the tabs "signatures" and "filters"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Regression of: https://github.com/zammad/zammad/commit/5ee6418c18ad723819d03431ae8de118624bad73#diff-a506096d0e811c13d1bbc513ef3cd10228ed87f7c7d8c4762d854d15e0035795L35
