### ISSUE TITLE
Switch EmailAdress-Validation method to `email_address` gem

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3527]
### Infos:

* Used Zammad version: 4.0 and earlier
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1086130

*Please note: This issue has affected issues (brothers and sisters):*
   * https://github.com/zammad/zammad/issues/2401
   * https://github.com/zammad/zammad/issues/2402
   * https://github.com/zammad/zammad/issues/3303

### Desired behavior:

Switching email address verification from `URI::MailTo::EMAIL_REGEXP` to `email_address` [gem](https://github.com/afair/email_address) for better support of puny code domains. This affects several areas within Zammads code base - not just above mentioned channel situations.

Suggestion could look like the following:
```
require 'email_address'
p EmailAddress.valid? 'leuser@ägssample.com', local_encoding: :unicode, host_validation: :syntax
p EmailAddress.error 'leuser@ägssample.com', local_encoding: :unicode, host_validation: :syntax

true
nil
```

Please note that `host_validation: :syntax` is crucial as we don't want to verify MX records. :-)

### Actual behavior:

User creation with punycode domains is not possible, email address verification fails.

**Comment by Nejamul068** [comment]
Name: Mohammed Nejamul Hoque 
Born: 
20-12-1983 (age 37)
Nid number :3279347433
Country : Bangladesh 
Nationality
Bangladeshi
Social : Islam 
Marriage : Married 
Child :one
Wife name :Jumu Aktar 
Permit address : Nutu Bari, chur fujuddin, hajir hat,  monpura, Bhola -8360
Father name : Forid Ahamed 
Mother name : Shahinur begum 
Lives address : Nojir Bandar line, kapooria para, bandar,doublemorning, Chittagong -4100
Barek mia  High School, Chittagong or Uttar sakushia High school, monpura, Bhola.
Occupation : general electrician worker
Last working place : Singapore construction site or im Singapore construction skills workers last working Singapore 2012
Now family etc: poor man Daily income eat
My have Dutch-Bangla Bank ltd.Agent accounts. 
A/c:701-701-4174055
A/c holder name : Nejamul Haque store 
Branch : chur fujuddin, fakir hat, monpura,Bhola -8360
![IMG_20201203_202740_0](https://user-images.githubusercontent.com/88603564/133007542-652ba9c1-6c11-48a4-ac53-8212aaaa7ff9.jpg)
![Uploading BeautyPlus_20210901025312468_org.jpg…]()

**Comment by Nejamul068** [comment]
![BeautyPlus_20210901003025401_save](https://user-images.githubusercontent.com/88603564/133007564-d39e50bf-e399-4ef5-900d-cca8e499fd87.jpg)
My country Bangladesh government approval online digital smart national Id card verify

**Comment by mgruner** [comment]
@mantas I believe you already fixed this, didn't you?

**Comment by mantas** [comment]
yep!

**Comment by mantas** [comment]
Already implemented with https://github.com/zammad/zammad/commit/19547179174acaf69b4a283ae188b600228d1392

**Comment by LPJon** [comment]
I'm now having issues with submitting forms as of Zammad Version 5.2.x. When looking at the web browser console "network" tab under a "form_submit" POST action I can see"
```
{
	"errors": {
		"email": "invalid"
	}
}
```
I'm using a valid email and it worked previously before this with not issues. Looking at some of the code there are MX validations going on yet I still can't get a valid email address. Will send to gmail with no issues. Is there a specific server IP for doing mx validation that I need to know about?
