### ISSUE TITLE
Attachments sent by Zammad not shown in Outlook

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#3529]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket(#1084638), (#1086226), (#1081546)

### Expected behavior:

* Attachments should always be shown in any email client.  

### Actual behavior:

* Under some circumstances (see "steps to reproduce...") attachments are not shown in Outlook. 

### Steps to reproduce the behavior:

1) cat mail101.txt | rails r 'Channel::Driver::MailStdin.new
2) Forward email in web app
3) Verify the `Content-Disposition` header in the forwarded email (its inline and not attachment)
Example-file to reproduce: [mail101.txt](https://github.com/zammad/zammad/files/6383681/mail101.txt)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Note: It has todo with the `Content-ID` of the attachment in the mail. The `mail` gem is adding `Content-Disposition: inline` because of the `Content-ID` (even if the attachment is not referenced in the html markup).

Solution: Zammad needs to define if the attachment is  `Content-Disposition: inline` or  `Content-Disposition: attachment`.

**Comment by rolfschmidt** [comment]
Hi @martini ,

the example is a plain mail. is it even possible to have inline attachments in plain emails? I tried to have inline attachments in my thunderbird and it does not look like its possible.

Maybe the default is just wrong:

https://github.com/zammad/zammad/blob/7125e54b1316b8f7da9a81e18f7b350f127f6eb9/app/models/channel/email_build.rb#L97

For html emails the default is attachment:

https://github.com/zammad/zammad/blob/7125e54b1316b8f7da9a81e18f7b350f127f6eb9/app/models/channel/email_build.rb#L118

**Comment by martini** [comment]
> the example is a plain mail. is it even possible to have inline attachments in plain emails? I tried to have inline attachments in my thunderbird and it does not look like its possible.

No, it's not possible. But some clients (like android galaxy) creating plain emails with an attached attachment/screesnhot which has an `Content-ID` header. 

Then IMO the `Content-ID` is to much (not needed) but we can't change this behavior by android galaxy.

Because of this containing `Content-ID` header the `mail`-gem adds `Content-Disposition: online`.

**Comment by rolfschmidt** [comment]
regression:
`Zustellung fehlgeschlagen: "Unable to send email to 'x <x@x.de>': Can't use Channel::Driver::Sendmail: #<Encoding::CompatibilityError: incompatible encoding regexp match (Windows-31J regexp with UTF-8 string)>" `

![grafik](https://user-images.githubusercontent.com/5445062/117777804-41b40c80-b23d-11eb-95d0-f7795c058ef4.png)

**Comment by thorsteneckel** [comment]
Change was reverted by the two commits above.

**Comment by rolfschmidt** [comment]
hi @MrGeneration ,

do you have any idea how to reproduce it? it tried it on my hosted instance but it did not work out. I think reasons for the crashes could be the "s" modifier, my fault. in perl the s modifier has a different meaning, but in ruby it is encoding related:

![grafik](https://user-images.githubusercontent.com/5445062/117808272-f4479780-b25c-11eb-8f64-6080e5c38de4.png)

i have no idea at all how to reproduce this in a test at the moment. with a testsystem we could at least check if changing the modifiers would be a solution.
