### ISSUE TITLE
Create proccess management for zammad to handle complex processes

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#353]
Zammad wish of Martin Farkas:
"Approval management (user submits ticket; task requires users line managers approval; agent submits sub ticket to manager for authorisation; manager authorises or declines request; agents continues to work on task)"

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
