### ISSUE TITLE
Add email templates webui editor

### ISSUE THREAD

**Issue by amigthea** [zammad/zammad#3530]
as I talked about it in the [technical forum](https://community.zammad.org/t/how-to-change-default-template/6758), it would be great if we can customize the postmaster default reply template directly from the web interface.
Right now i found a workaround (check the link above) but it's not optimal at all for production enviroment

Thank you

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.

**Comment by amigthea** [comment]
it's not a technical question but a feature request

**Comment by MrGeneration** [comment]
Correct. I updated my text module and first response. 
Please post your feature request on the community as requested in the issue template you removed.
