### ISSUE TITLE
Log spamming in http_logs > no clean up

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#3535]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): apt
* Operating system: Ubuntu 20.04.2
* Database + version: postgres
* Browser + version: Microsoft Edge

My database is growing very fast. We use zammad since 01.03.2021 (8 weeks!) and our database is ober 4 GB big. I connected to the database with HeidiSQL and see one table called **http_logs** which is über **3,7 GB** big.

![image](https://user-images.githubusercontent.com/1473674/116459418-0fca9f80-a866-11eb-80c0-e17bec2b1299.png)

I think this is not normal and should cleared by zammad after some days. What can we do?
We use a big LDAP installation with many changes every day and the most logs are from ldap. It is possible to fix this, please?

Or can I clear ths table by using HeidiSQL? Or is zammad broken after that?

Sorry for my bad english

Thanks in advance!

**Comment by thorsteneckel** [comment]
Hi @Dennis1993 - this is a rather technical question. Please refer to the [community board](http://community.zammad.org/) as the issue tracker is for verified and reproducible bugs.

Background:
The HTTP log gets cleaned up [automatically](https://github.com/zammad/zammad/blob/ac64f4a156d624816622b3b0a5a50b565a4f1ed0/db/seeds/schedulers.rb#L175-L183) and will [remove records older than 1 month](https://github.com/zammad/zammad/blob/ac64f4a156d624816622b3b0a5a50b565a4f1ed0/app/models/http_log.rb#L22-L25).

You could run `HttpLog.cleanup(1.week)` via the [Zammad rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console) as a cronjob as a workaround.

Please refer to the community for follow up and other questions.
