### ISSUE TITLE
Don't fail job is `deletable_id` is no longer available

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3536]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket#1086914

### Desired behavior:

If a user has been removed via other methods in parallel to DataPrivacy it will acknowledge that `deletable_id` is no longer available and switch to `completed` instead of `failed`. 

### Actual behavior:

If a user has been removed before the DataPrivacyTask could run, the task will fail and alert within the monitoring. *

* It's possible that this is due to several DataPrivacyTask jobs for the same user. I did see such things in some instances, however can't reproduce this behavior.

### Steps to reproduce the behavior:

* Add a removal for any user
* Remove that user manually before the dataprivacy takes place
* wait for the dataprivacytask to run

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
@MrGeneration will contact me if it will occur again. Not reproduceable atm.
