### ISSUE TITLE
When replying, quote article content only

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#3539]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1079483

### Expected behavior:

* If text in the article is selected, it will be quoted when starting a reply
* If text outside of the article is selected, it will be ignored when starting a reply

### Actual behavior:

* If text outside of the article is selected, it will be quoted when starting a reply

### Steps to reproduce the behavior:

* Select ticket number
* Start a reply
* Ticket number is quoted

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by romitgithub** [comment]
@mantas What if the text selected is both inside and outside of the article?

**Comment by mantas** [comment]
I'd prefer quoting the part that was inside of the article and discarding the other part. Otherwise quoting wouldn't work if text selection goes slightly wrong.

But if that proves to be too difficult, then just discarding such quotes is fine.

**Comment by romitgithub** [comment]
That is definitely going to be out of the way, would take extra efforts. 

> What if the text selected is both inside and outside of the article?

I was just wondering if this could be really a usecase. Otherwise it'd be just an unnecessary implementation. Or should we just wait and watch if such cases arise?

**Comment by mantas** [comment]
IMO most common case could be a wacky selection where 99% of content is inside. But juuuust a bit (e.g. a space) is outside.
