### ISSUE TITLE
Ensure Google Calendars are fetched via `HTTPS`

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3545]
### Infos:

* Used Zammad version: 4.0/stable
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1086717 

### Expected behavior:

Zammad fetches holiday calendars from google by using `https`.

### Actual behavior:

Zammad fetches holiday calendars from google by using `http`.
This is an issue if HTTP traffic is blocked. :-) I couldn't find the parts in the code but believe we should do better.

![image](https://user-images.githubusercontent.com/6549061/117112728-c9a39d80-ad89-11eb-8421-605bf7a5b930.png)

### Steps to reproduce the behavior:

* block outgoing port `80` and try to update your calendars

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
@MrGeneration looks like this is the culprit https://github.com/zammad/zammad/blob/12ad55279adb10b64d234969aba6929183fea7ac/config/holiday_calendars.yml#L3

**Comment by MrGeneration** [comment]
What a bad boy :D
