### ISSUE TITLE
Overviews screen is empty, logs record "Invalid selector, operator till (relative) is invalid"

### ISSUE THREAD

**Issue by ziodave** [zammad/zammad#3553]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): zammad-helm
* Operating system: K8s
* Database + version: Postgres 11.6
* Elasticsearch version: 7.12.1
* Browser + version: Firefox 88.0.1

### Expected behavior:

* When I click on Overview, I should see the list of queues

### Actual behavior:

* An empty screen

The following is logged:

```
zammad-0 zammad-scheduler E, [2021-05-10T19:40:05.918343 #1-47087737642100] ERROR -- : thread_client 47160217927100 exited with error #<RuntimeError: Invalid selector, operator till (relative) is invalid {"operator"=>"till (relative)", "value"=>"10", "range"=>"minute"}>
zammad-0 zammad-scheduler E, [2021-05-10T19:40:05.918593 #1-47087737642100] ERROR -- : /opt/zammad/app/models/ticket.rb:630:in `block in selector2sql'
zammad-0 zammad-scheduler   /opt/zammad/app/models/ticket.rb:622:in `each'
zammad-0 zammad-scheduler   /opt/zammad/app/models/ticket.rb:622:in `selector2sql'
zammad-0 zammad-scheduler   /opt/zammad/app/models/ticket/overviews.rb:100:in `block in index'
zammad-0 zammad-scheduler   /usr/local/bundle/gems/activerecord-5.2.4.5/lib/active_record/relation/delegation.rb:71:in `each'
zammad-0 zammad-scheduler   /usr/local/bundle/gems/activerecord-5.2.4.5/lib/active_record/relation/delegation.rb:71:in `each'
zammad-0 zammad-scheduler   /opt/zammad/app/models/ticket/overviews.rb:99:in `index'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions/backend/ticket_overview_list.rb:47:in `load'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions/backend/ticket_overview_list.rb:109:in `push'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions/client.rb:67:in `each'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions/client.rb:67:in `block in fetch'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions/client.rb:23:in `loop'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions/client.rb:23:in `fetch'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions/client.rb:7:in `initialize'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions.rb:756:in `new'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions.rb:756:in `thread_client'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions.rb:778:in `rescue in thread_client'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions.rb:755:in `thread_client'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions.rb:778:in `rescue in thread_client'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions.rb:755:in `thread_client'
zammad-0 zammad-scheduler   /opt/zammad/lib/sessions.rb:711:in `block (3 levels) in jobs'
zammad-0 zammad-scheduler   /usr/local/bundle/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

### Steps to reproduce the behavior:

* Click on Overview

Yes I'm sure this is a bug and no feature request or a general question.

![image](https://user-images.githubusercontent.com/11438/117716368-ca00c600-b1d9-11eb-8fa5-c99a0cf02f6a.png)

**Comment by MrGeneration** [comment]
Your error description and the log file snippet do not belong together, altough it may have the same reason. 
Please check if your developer console (F12) provides console errors when trying to list overviews within the frontend.

Also, did you upgrade or is this a fresh install?
What exactly happened? What user kind are you using? (agent, admin, customer)

**Comment by ziodave** [comment]
> Also, did you upgrade or is this a fresh install?

It's a fresh install pointing to an existing database.

> What exactly happened? What user kind are you using? (agent, admin, customer)

I am using admin.


It's working now, I temporary disabled the readiness and liveness probes which were causing frequent restarts. Maybe that was the cause.

I'll follow up in case I spot it again.

Thanks for your quick reply.

**Comment by MrGeneration** [comment]
> It's a fresh install pointing to an existing database.

Sounds like a technical question then.
I'm sorry. Please do not post technical questions on this github repository, instead, use the community: https://community.zammad.org
