### ISSUE TITLE
Zammad sends mails even though there is no email address visible in TO or CC fields (any more)

### ISSUE THREAD

**Issue by fthommen** [zammad/zammad#3554]
### Infos:

* Used Zammad version: 4.0.0-1618480262.260afe11.centos7
* Installation method (source, package, ..): Package (RPM via YUM from repository)
* Operating system: Server: Linux (CentOS 7.9.2009); Client: macOS 11.3.1 Big Sur
* Database + version: MariaDB 10.3
* Elasticsearch version: 7.9.2-1
* Browser + version: Firefox 88.0.1

### Expected behavior

When _cutting_ an email addresses from the TO or CC fields in an email answer or a new email note prior to sending the answer through the "Update" button, then the answer/note is _still_ sent to this email address

### Expected behavior:

* answers and email notes are only sent to email addresses which are visible in the TO or CC fields

### Actual behavior:

* answers and email notes are also sent to email addresses have been cut from the TO or CC fields and are not visible there any more

### Steps to reproduce the behavior:

* create a new note
* select "Email" as note type
* write an email into the TO field (or use Zammad's autocompletion feature)
* cut(!) the email address out of the TO field (doubleclick to select, then type Cmd-X)
* paste the email address somewhere in the text (type Cmd-V) (this step can probably be skipped)
* update the issue -> email is sent out
* check the resulting note and see that despite the TO field visually having been empty, an email has been sent to the email address which was the previous content of the TO field

See also this screencast as illustration:

https://user-images.githubusercontent.com/279232/117822004-6d022000-b26c-11eb-9fa8-da46876790c5.mp4

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This rings a bell, does this come from the community forum or another issue?

**Comment by MrGeneration** [comment]
Found it.
Originally appeared on the community by user "Joe"
https://community.zammad.org/t/bug-ctr-x-not-working-hidden-on-forward-or-answer/5843/3


In my opinion this is more of a usability/UI topic, I wouldn't use Cut on that regard.  Anyway.

**Comment by fthommen** [comment]
> In my opinion this is more of a usability/UI topic, I wouldn't use Cut on that regard. Anyway.

I'd rather see it as an UI design question, as what is visible (empty address field) doesn't reflect the reality (there is somehow an address registered).

As a user I would expect Zammad not to send emails if there is no email address in the address field ;-).  If the standard OS keystrokes for cut, copy and paste are not supposed to yield the expected results, then they should somehow be blocked (needless to say, that this would considerably lower the positive user experience. I know such UIs, and they are terrible and cumbersome to use ;-) ).

Not being a Zammad developer, a regular user cannot know, that in this special case the standard "cut" functionality doesn't work and there is still some information "left over".  Especially since there is no indication for it.  Maybe Zammad could give some hint, that there is still an email address registered even though it is not displayed?

**Comment by blu-IT** [comment]
I think this is somekind of "bug". As I described in the issue #3649 an agent expects that when he is responding to a ticket, that the system sends it to the customer an not to any to or from field that is blank or originally was sent from, after the customer was changed (in my case).

**Comment by MrGeneration** [comment]
@blu-IT please stop hijacking unrelated issues with technical questions. 
If you have issues with working on Zammad due to the way it's designed please consult the community.

I'm locking this issue to save it from further hijacks. 
Over 2000 people have been notified about this issue without any real use.
