### ISSUE TITLE
Missing some tickets after zammad update

### ISSUE THREAD

**Issue by geonmo** [zammad/zammad#3558]
### Infos:

* Used Zammad version: v4.0
* Installation method (source, package, ..): YUM 
* Operating system: CentOS Linux release 7.7.1908 (Core)
* Database + version: postgresql-server-9.2.24-2.el7_7.x86_64
* Elasticsearch version: elasticsearch-7.6.1-1.x86_64
* Browser + version: Firefox 88.0.1

### Expected behavior:

* Information about recent tickets is also wanted to be displayed in the report.

### Actual behavior:

* Tickets registered after zammad v4.0 upgrade are not displayed.
* Missing tickets are displayed on "My Tickets" in Overview.
* The following error occurred.
`
Response:
#<UserAgent::Result:0x00007f7934d784a8 @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse field [organization] of type [text] in document with id '3'. Preview of field's value: '{shared=true, note=, domain_assignment=false, updated_at=2021-05-04T02:31:28.377Z, domain=, name=KISTI, active=true, created_at=2020-03-13T05:43:53.480Z, updated_by_id=3, id=2, created_by_id=3}'\"}],\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse field [organization] of type [text] in document with id '3'. Preview of field's value: '{shared=true, note=, domain_assignment=false, updated_at=2021-05-04T02:31:28.377Z, domain=, name=KISTI, active=true, created_at=2020-03-13T05:43:53.480Z, updated_by_id=3, id=2, created_by_id=3}'\",\"caused_by\":{\"type\":\"illegal_state_exception\",\"reason\":\"Can't get text on a START_OBJECT at 1:2379\"}},\"status\":400}", @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">`

### Steps to reproduce the behavior:

* It's not clear, but we assume it happened after the zammad update (v3.6->v4.0).

**Comment by geonmo** [comment]
I'm adding another message. Perhaps this message will be the most direct connection.
`#<UserAgent::Result:0x0000560948ed9ef8 @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse field [state] of type [text] in document with id '911'. Preview of field's value: '{next_state_id=null, note=null, active=true, created_at=2020-03-12T07:55:25.215Z, default_create=false, state_type_id=5, default_follow_up=false, updated_at=2020-03-12T07:55:25.215Z, name=closed, updated_by_id=1, id=4, created_by_id=1, ignore_escalation=true}'\"}],\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse field [state] of type [text] in document with id '911'. Preview of field's value: '{next_state_id=null, note=null, active=true, created_at=2020-03-12T07:55:25.215Z, default_create=false, state_type_id=5, default_follow_up=false, updated_at=2020-03-12T07:55:25.215Z, name=closed, updated_by_id=1, id=4, created_by_id=1, ignore_escalation=true}'\",\"caused_by\":{\"type\":\"illegal_state_exception\",\"reason\":\"Can't get text on a START_OBJECT at 1:240\"}},\"status\":400}", @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">`

**Comment by rolfschmidt** [comment]
hi @geonmo,

try to rebuild your elastic search index: `zammad run rake searchindex:rebuild`

(https://docs.zammad.org/en/latest/install/update.html#updating-elasticsearch)

**Comment by MrGeneration** [comment]
Read the release notes please.


Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
