### ISSUE TITLE
mentioned KB entries with the same title in different categories can not distinguished

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3559]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all
* Ticket#1086408

### Expected behavior:

* kb entries with the same subject should be distinguishable

### Actual behavior:

* there is only the title displayed

### Steps to reproduce the behavior:

* Add 2 kb entries:

-> category 1 -> subject 1
-> category 2 -> subject 1

try to mention the kb article somewhere with the ?? shortcut

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by wucherpfennig** [comment]
Note: the same goes for translated articles and agents who do not fully speak the desired language.

 If you know that there is an article in German and you have to send the French version to the customer you will most likely not be able to find the French version without leaving the ticket and first look up the French title.

Therefore we would welcome a user setting to have articles displayed in the agents desired language keyed by the KB article language.
The easiest (and in our usecase preferred) way to solve that would be that we would be able to define custom "short descriptions" like we are to do with test modules.

Attached you will find an example how we solved this exact issues for text modules

![image](https://user-images.githubusercontent.com/3634653/119315893-9bbdc480-bc76-11eb-8c02-3f25b5955fde.png)

**Comment by wucherpfennig** [comment]
Note 2: please make the auto complete "window" wider as the default size almost never shows the full title of the articles

**Comment by MrGeneration** [comment]
You really shouldn't hijack issue reports regarding other issues. 
This one aims at a different position. Mixing things can get confusing and cause issues during solving or after.

I especially aim at your second note as it has to do *nothing* with the original issue. 
I'm limitting the conversation of this issue to contributors only to reduce noise on this repository.

**Comment by rolfschmidt** [comment]
@wucherpfennig 
 
> Note: the same goes for translated articles and agents who do not fully speak the desired language.
> 
> If you know that there is an article in German and you have to send the French version to the customer you will most likely not be able to find the French version without leaving the ticket and first look up the French title.
> 
> Therefore we would welcome a user setting to have articles displayed in the agents desired language keyed by the KB article language.
> The easiest (and in our usecase preferred) way to solve that would be that we would be able to define custom "short descriptions" like we are to do with test modules.
> 
> Attached you will find an example how we solved this exact issues for text modules
> 
> ![image](https://user-images.githubusercontent.com/3634653/119315893-9bbdc480-bc76-11eb-8c02-3f25b5955fde.png)

for the language topic follow this one:

https://github.com/zammad/zammad/issues/3574

> 
> 
> Note 2: please make the auto complete "window" wider as the default size almost never shows the full title of the articles

Please create a new issue for this.
