### ISSUE TITLE
Automatically join users to organizations based on the email address

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#356]
Zammad wish Jann Heider:
Make the possibility to automatically add new contacts to organizations based on the domain. For users with the email address "@mycustomer.com" should be automatically joined to the organization with the domain "mycustomer.com".

This would be a optional configuration option.

**Comment by singular-error** [comment]
tha's a really good idea  - i'd like to have this too :)

**Comment by martini** [comment]
Is implemented in upcoming 1.1.0 https://github.com/zammad/zammad/commit/5157597465199d8d7ce95088786eb9eebec12bd3
