### ISSUE TITLE
Zammad changes characters entering #& 

### ISSUE THREAD

**Issue by darklightmoon** [zammad/zammad#3565]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..):
* Operating system: Windows 10
* Database + version:
* Elasticsearch version:
* Browser + version: Firefox, Chrome

### Expected behavior:

* Get #& after entering #&

### Actual behavior:

* see GIF

### Steps to reproduce the behavior:

* 
![Zammad Symbol](https://user-images.githubusercontent.com/59093874/118965728-47120500-b969-11eb-9dc6-171b343ac837.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Also verified on Zammad 4.0/stable and 4.0/develop

**Comment by martini** [comment]
I tried to reproduce it. I found out that Zammad`s default font "Fire Sans" is displaying `#&` as this special sign:

With Zammad Default font in CSS:
<img width="329" alt="Screen Shot 2021-05-27 at 17 17 13" src="https://user-images.githubusercontent.com/110226/119852371-8911ec80-bf0f-11eb-9308-ce8fe552a900.png">
<img width="738" alt="Screen Shot 2021-05-27 at 17 16 26" src="https://user-images.githubusercontent.com/110226/119852382-8a431980-bf0f-11eb-85dc-683491119e4c.png">




Without Zammad Default font in CSS:
<img width="322" alt="Screen Shot 2021-05-27 at 17 17 02" src="https://user-images.githubusercontent.com/110226/119852378-89aa8300-bf0f-11eb-850b-07a28ddfeb0c.png">
<img width="751" alt="Screen Shot 2021-05-27 at 17 16 53" src="https://user-images.githubusercontent.com/110226/119852379-8a431980-bf0f-11eb-90e8-c38423ca4704.png">

Anyway, the result in my email client is always `#&` (verified on Mac/mail app and linux/thunderbird)
<img width="343" alt="Screen Shot 2021-05-27 at 17 20 04" src="https://user-images.githubusercontent.com/110226/119852790-e5750c00-bf0f-11eb-8e47-dd51e030b0de.png">


Conclusion:
It`s no Zammad issue. It`s an issue with "Fire Sans" font.

**Comment by MrGeneration** [comment]
As the font is our dependency and causing unexpected display -at least in the UI- I'm not on your side on "not a Zammad problem". :-(

**Comment by dominikklein** [comment]
@dvuckovic Any idea here, do we have any chance here to change the behavior? Or is the only option to switch the font?

**Comment by fleverest** [comment]
Seems like a Fira ligature, changing to a version of Fira which does not have ligatures enabled will resolve the issue. Maybe a client-side option to switch fonts?

**Comment by dvuckovic** [comment]
```
:root {
  font-variant-ligatures: none;
}
```

Might work, haven't tried it yet.
