### ISSUE TITLE
Duplicated article after bulk action was executed for newly created tickets without a browser refresh in between

### ISSUE THREAD

**Issue by blawat** [zammad/zammad#3568]
### Infos:

* Used Zammad version: 4.0
* Used Zammad installation type: package
* Operating system: Debian 10.5
* Browser + version: Microsoft Edge Version 90.0.818.62 (Official build) (64-bit)
* Each component has its own VM (DB, Application, Elastic)

### Expected behavior:

* Article will not be duplicated after executing bulk action.

### Actual behavior:

* When the bulk action is executed on a ticket, the article “posted” by a customer is duplicated.

### Steps to reproduce the behavior:

* Create a ticket.
* Find a ticket in the overview and execute on it a bulk action (e.g. change the status), provide a note.
* Check the ticket - the article posted by the customer will be duplicated.

Test ticket:
![image](https://user-images.githubusercontent.com/6067809/119310408-fbfd3800-bc6f-11eb-889e-c661cef2b1cf.png)

Bulk action:
![image](https://user-images.githubusercontent.com/6067809/119311794-cc4f2f80-bc71-11eb-887d-c2a776d564d4.png)

The ticket after bulk action was executed:
![image](https://user-images.githubusercontent.com/6067809/119311844-da9d4b80-bc71-11eb-95a6-051fbddbf541.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by BernhardK91** [comment]
I was able to reproduce this behavior on my installation and can confirm that this needs to be a bug.

**Comment by MrGeneration** [comment]
@mantas  how did you reproduce this? Because I can't with the supplied information.

**Comment by mantas** [comment]
@MrGeneration I don't remember running into any issues to reproduce this. IIRC I did following:

- create a new ticket, no fancy configuration
- go to overviews
- execute a bulk action on tabove ticket, with a note\
- duplicate note shows up

browser refreshing may or may not be involved

**Comment by MrGeneration** [comment]
Interesting.
This doesn't seem to happen if the message the customer sent was a email and the agent setting a state as well. 
Not sure if this belongs together.

Possibly this may also affect bulk actions on a single ticket only. 
I can't reproduce this on more than one ticket.

**Comment by rolfschmidt** [comment]
Same issue exists for the customer interface.
