### ISSUE TITLE
Customers can see agents tickets by going into network tab

### ISSUE THREAD

**Issue by DragonFyZex** [zammad/zammad#3572]
### Infos:

* Used Zammad version: 4
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 16.04
* Database + version: Postgres 11
* Elasticsearch version: Elasticsearch 7
* Browser + version: Firefox Latest

### Expected behavior:

* Hidden emails when looking at the network tab of /tickets/:id?all=true

### Actual behavior:

* Agent's emails are shown
![image](https://user-images.githubusercontent.com/18251635/119741233-239ffc00-be3a-11eb-8dff-c4bfc07ccedb.png)

### Steps to reproduce the behavior:

* Make a ticket in a customer account
* Go to the network tab
* Find the request that has the url /tickets/:id?all=true
* Go to assets -> users

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Please get in touch with us via support-at-zammad dot com. Deleting this issue now.
