### ISSUE TITLE
Cookie lifetime ignored by some browsers

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3577]
### Infos:

* Used Zammad version: 4.1/develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: all browsers that have remember tabs enabled
   * see mozillas statement about it being a feature: https://support.mozilla.org/en-US/questions/943191
   * seems like we gotta do it: https://stackoverflow.com/questions/48180098/rails-session-doesnt-expire-at-browser-close

### Expected behavior:

If you don't tick "remember me" upon login and close your browser, upon the next browser restart the session cookie of Zammad is removed. This will force me to login again.

### Actual behavior:

On some browsers the cookie lifetime ("until end of the session") is being ignored. 
That's not just rude but can also raise issues when expecting being logged out but you aren't.

### Steps to reproduce the behavior:

* open the Zammad instance (login is optional ;D)
* check for the session cookie
* close your whole browser
* start your browser and check the session cookie / session

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
That's a browser issue not the one of Zammad. We can talk about it after the next standup if you like.
