### ISSUE TITLE
Package migrations fail on package installation or update due to codebase self-modification

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad#3580]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): git checkout
* Operating system: macOS 11.4
* Database + version: PostgreSQL 13.3
* Elasticsearch version: not relevant
* Browser + version: not relevant

### Expected behavior:

* Package installation executes migrations correctly.

### Actual behavior:

* Migrations fail with exceptions due to inconsistent codebase state.
* This is caused by the fact that the codebase modifies itself and then immediately uses added/changed models or other classes. This cannot work because of preloading and cached_classes in the production environment. 
* The only valid solution for this seems to be to execute the migrations in a separate step with a fresh rails environment.

### Steps to reproduce the behavior:

```
rails r "Package.install(file: '/path/to/Addons-0.0.1.zpm')"
-- create_table(:addons)
   -> 0.0117s

Please specify a valid ruby command or the path of a script to run.
Run 'bin/rails runner -h' for help.

undefined method `all' for Addon:Module
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by klando** [comment]
@mgruner , @thorsteneckel How are we supposed to install package after this commit ? Or can you confirm what is the expected behavior from the user point of view ?
Installing via the web ui as usual didn't worked (looks installed but no jobs schedule or anything) and I had to go to rails console to execute the migration myself.

Having a little bit more feedback in the ui will be awesome...

**Comment by mgruner** [comment]
Hi @klando, thanks for your suggestion. This is now implemented as a hint in the package manager GUI as shown on the following screenshot:

<img width="710" alt="Bildschirmfoto 2021-07-20 um 13 16 14" src="https://user-images.githubusercontent.com/211281/126315122-db88373d-e8fb-427e-85f1-82443b9b2dc6.png">

**Comment by klando** [comment]
So I was missing the `assets:precompile` and `restart` stages. Thank you for the patch.
