### ISSUE TITLE
BigDecimal.new is deprecated

### ISSUE THREAD

**Issue by bastolino** [zammad/zammad#3589]
Hi everyone,
when running `zammad run rake searchindex:rebuild` the current version (`zammad/unknown,now 4.0.0-1622547078.51bf33da.focal amd64`) shows an error that BigDecimal.new is deprecated.
A lot of same lines show up:
`/opt/zammad/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/mysql/database_statements.rb:34: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.`

Actually, the warning stands for itself.
Thanks!

**Comment by MrGeneration** [comment]
Please use the issue template, it helps a lot for scopes.

**Comment by bastolino** [comment]
### Infos:

* Used Zammad version: zammad/unknown,now 4.0.0-1622547078.51bf33da.focal amd64
* Installation method (source, package, ..): deb-package
* Operating system: Ubuntu 20.04
* Database + version: mariadb  Ver 15.1 Distrib 10.3.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
* Elasticsearch version: Version: 7.13.1, Build: default/deb/9a7758028e4ea59bcab41c12004603c5a7dd84a9/2021-05-28T17:40:59.346932922Z, JVM: 16
* Browser + version: irrelevant


### Expected behavior:
 no error messages, when rebuilding search index
*


### Actual behavior:
warnings issued in console-output. though it finishes successfully.
*


### Steps to reproduce the behavior:
execute `zammad run rake searchindex:rebuild`
*

Yes I'm sure this is a bug and no feature request or a general question.
I'm pretty sure...

**Comment by mantas** [comment]
This comes from a gem we're using. It will be gone when we update to updated library update. Closing issue now.

**Comment by MrGeneration** [comment]
Seems to only affect MySQL installations.
I adjusted the tagging @mantas please fix if I got it wrong.

**Comment by mantas** [comment]
Yes, it only affects MySQL, because it is in Rails MySQL driver :) Added `unfixable` tag to make it clear there's nothing we can do today. But it will vanish once we upgrade to Rails 6.
