### ISSUE TITLE
One click update mechanism

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#359]
Zammad wish of Daniel Lange:
"Safe, in-prod, reversible (in case of failure) online updating.
So a one-click updater / shell management command done correctly.
Which nobody else has (implemented properly) and thus maintenance costs are significantly higher due to upgrade woes."

**Comment by Julian0o** [comment]
Nobody knows how the update workflow will be :) I hope its way better compared to OTRS. 
There has to be a way to preserve customisations.

**Comment by jacotec** [comment]
A perfect example how this can work is Discourse (http://www.discourse.org/) ... one-click update of the core and plugins via webserver in the admin-interface ... also possible of course via shell.

**Comment by monotek** [comment]
Updates are now already handled by the DEB & RPM packages.
Imho no need to do this in the app itself.

**Comment by thorsteneckel** [comment]
As a conclusion I'd say that the community and we ourself are pretty satisfied with the update experience (in technical terms). There's currently no need or proposal on how to improve things. Therefore I'll close this issue. Please refer to the [community board](http://community.zammad.org/) if you disagree and/or have a proposal. Thanks!
