### ISSUE TITLE
Allow `position` to determine an attributes position entirely

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3594]
### Infos:

* Used Zammad version: 4.0/stable
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1087912

### Expected behavior:

When manually adjusting an attributes `position` to e.g. the lowest value, the attribute in question will be first. 

### Actual behavior:

For Users, Organizations and groups there are fixed attributes that are enforced on specific positions. 
It's impossible to move a specific field of interest above these fields.

Below you can find these limitations:

**Tickets (sidebar)**:
Don't have fixed attributes and provide the expected ordering. \o/

**Users**:
* firstname
* lastname
* email
* organisation

are fixed before anything else

**Organizations**:
* name
* shared organization

are fixed before anything else

**Groups**:
Do not care about position at all, all default shipped fields come before anything else:
* name
* assignment timeout
* follow-up possible
* assign follow-ups
* email
* signature
* note
* active

### Steps to reproduce the behavior:

* set up a new attribute for e.g. user object
* update the database, restart Zammad
* within rails console adjust the `position` of the created attribute (e.g. 1)
* reload the webapp and check the attributes position

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by bolah2009** [comment]
This seems to be the intended behaviour of such objects. There are some predefined attributes in the frontend that would always take precedence whatever the position value is.  An example is the [User model](https://github.com/zammad/zammad/blob/3b0a373de0f0fc5da8a1226a559a00129c4cff82/app/assets/javascripts/app/models/user.coffee#L7-L11)

We discussed this along with @martini and decided that if we are to change it to this new excepted behaviour we need to discuss the specifications. Adding the specification label.

**Comment by MrGeneration** [comment]
You didn't see that this potentially breaks Core Workflow?
I think @rolfschmidt got that on his list indirectly if I remember correctly. 

If we have specific fields you never can hide of manipulate then options for these have to be removed explicetely.

**Comment by MrGeneration** [comment]
@martini I'm not happy with the plan to backport a functionality that comes on top. Apart from documentation reasons we should consider a short term release that, while being smaller, can introduce breaking changes that don't contain a "suprise" moment to everyone running a stable update.
