### ISSUE TITLE
Javascript Console Error with 4.0 (TypeError: this.controllerBind is not a function)

### ISSUE THREAD

**Issue by Mintux** [zammad/zammad#3596]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): Source
* Operating system: Debian 10
* Database + version: MariaDB 10.3.27
* Elasticsearch version: 7.13.1
* Browser + version: Firefox 88.0 and Chrome 91.0.4472.77

### Expected behavior:

Zammad should load normally and without Javascript errors.

### Actual behavior:

Zammad is not loading up at all and there are multiple Javascript errors in the console.

Errors:

- Uncaught TypeError: this.controllerBind is not a function
- App.n(error)                   | executeSingel task: CustomerChat TypeError: this.controllerBind is not a function
- App.n(error)                   | executeSingel task: CTI TypeError: this.controllerBind is not a function
- App.n(error)                   | executeSingel task: Dashboard TypeError: this.controllerBind is not a function
- App.n(error)                   | executeSingel task: KnowledgeBase TypeError: this.controllerBind is not a function
- App.n(error)                   | executeSingel task: TicketOverview TypeError: this.controllerBind is not a function

### Steps to reproduce the behavior:

1. Update Source installation from 3.5.0 to 4.0 while following https://docs.zammad.org/en/latest/install/update.html
2. Using `rake searchindex:rebuild` as described here https://support.zammad.com/help/de-de/38-technische-hinweise/189-inkompatibilitats-anderungen-breaking-changes-fur-zammad-4-0
3. Restarting Zammad
4. Opening the page, see blank page and check console for errors (Tested with Firefox and Chrome)

Additional Information: We're using Apache2 as Reverse Proxy and that worked before. I don't think it's a proxy issue, since there were no javascript console errors before the update was finished. So the blank page seems to be the result of the above javascript errors. This is a bug and not a technical question.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Mintux** [comment]
After some troubleshooting I found the problem for that issue:

If you follow the update documentation exactly it extracts the package content in the zammad folder. In future releases that worked fine without any problems, but with the 4.0 release, the package contains the folder zammad-stable itself. So even when you follow the documentation exactly, you technically extract the package content in zammad and then in zammad-stable, which obviously conflicts with the existing content in zammad.

Since that change is not documented anywhere and I don't believe everyone would check for the folder inside the zammad folder itself I would definitely recommend to update the update instructions for the 4.0 release.

After removing the previously extracted zammad-stable folder from inside my zammad folder I updated the installation again, this time carefully extracting the content in a safe place and then moving all the contents to the expected zammad folder. Followed the documentation from there and everything was working again.

I leave this here in case other users with a source installation have the same problem.

Sorry for the noise, since this is not really a bug, but rather a mistake in packaging or the documentation itself.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
