### ISSUE TITLE
Attachment management for organizations search/list/add/delete

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#360]
Zammad wish of Daniel Obee:
"Here's how it could work:

Each attachment gets a mean to "send" it to the customer file vault (read: to get linked in the vault).

The file vault is accessible from the customer view so each time you're looking for something, it's just a click away.

The file vault displays file name, display name and date created (of the file). Display name can be changed for better overview. Of course files also can be deleted from the vault if no longer necessary (which doesn't delete the attachment but just the link to it).

Add a search and maybe the option to broaden the search to all companies files and you have a small but incredibly nifty document management option."

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
