### ISSUE TITLE
Sidebar - Customer - closed tickets Don't work

### ISSUE THREAD

**Issue by YosefAdPro** [zammad/zammad#3602]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): package
* Operating system: Centos 7
* Database + version: postgres 9.2.24
* Elasticsearch version: 7.13.1
* Browser + version: any

### Expected behavior:

Clicking on tickets in the sidebar will display the list of closed tickets.
https://github.com/zammad/zammad/issues/563

### Actual behavior:

Clicking on closed tickets does nothing.
I think maybe it's because I have a state in Hebrew.
It's trying to search, as I see in the URL:

https://....com/#search/customer_id:131%20AND%20state.name:(%22closed%22%20OR%20%22%D7%97%D7%99%D7%95%D7%91/%D7%96%D7%99%D7%9B%D7%95%D7%99%20%D7%9C%D7%A7%D7%95%D7%97%22%20OR%20%22%D7%98%D7%95%D7%A4%D7%9C%22).

However, clicking on the open tickets brings results, even though there is also a state in Hebrew.

https://....com/#search/customer_id:131%20AND%20state.name:(%22new%22%20OR%20%22open%22%20OR%20%22pending%20reminder%22%20OR%20%22pending%20close%22%20OR%20%22%D7%9E%D7%9E%D7%AA%D7%99%D7%9F%20%D7%9C%D7%AA%D7%92%D7%95%D7%91%D7%AA%20%D7%9C%D7%A7%D7%95%D7%97%22%20OR%20%22%D7%91%D7%9E%D7%A2%D7%A7%D7%91%22)

https://user-images.githubusercontent.com/11810187/121178886-b04daf80-c867-11eb-9e8b-3643d5bd2417.mp4

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Hi @YosefAdPro,
you could try to name your states in english without any special characters and then translate them to Hebrew by the admin interface translation menu. This would be general the correct way i guess.

**Comment by YosefAdPro** [comment]
@rolfschmidt Thank you for your answer.
You can direct me with command I can change the names.

**Comment by rolfschmidt** [comment]
@YosefAdPro 

Open your console:

`rails c`

You can go through your list of states:

`pp Ticket::State.all`

Get the ID of the Hebrew state. Then rename it:

`Ticket::State.find(999999).update(name: 'new english name')`

placeholder 999999 needs to be replaced by the Hebrew state id.

If you open a ticket now then you should see the english state instead of the hebrew state name. If you now goto the admin interface -> translations, then you will see the string "new english name" as well and if your profile settings are set to hebrew you will be able to change the translation for the state name for hebrew locally.

**Comment by YosefAdPro** [comment]
> If you now goto the admin interface -> translations, then you will see the string "new english name" as well and if your profile settings are set to hebrew you will be able to change the translation for the state name for hebrew locally.

@rolfschmidt After changing the names of the state to English I do not see them in the translations. I also tried to do a restart for Zammad.

**Comment by MrGeneration** [comment]
Please don't make this a technical question issue. 
This is as far as I will help:
* https://docs.zammad.org/en/latest/admin/console/working-on-tickets.html#make-new-states-available-to-ui
* https://docs.zammad.org/en/latest/admin/console/other-usefull-commands.html#add-translation

If you need more technical assistance, please create a post on the community.

**Comment by rolfschmidt** [comment]
> 
> 
> Please don't make this a technical question issue.
> This is as far as I will help:
> 
>     * https://docs.zammad.org/en/latest/admin/console/working-on-tickets.html#make-new-states-available-to-ui
> 
>     * https://docs.zammad.org/en/latest/admin/console/other-usefull-commands.html#add-translation
> 
> 
> If you need more technical assistance, please create a post on the community.

Thank you very much. Yeah this part was missing. Please continue in the community for more questions please. For the issue itself we will not provide a fix for now. When the time comes and we introduce UI for it then we will come back to this but until then usage of a english state name (no special characters) + translations should be the way to go.
