### ISSUE TITLE
Importer for Request Tracker

### ISSUE THREAD

**Issue by martini** [zammad/zammad#361]
Zammad wish of 
Importer for Request Tracker (like for OTRS and Zendesk)

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes

**Comment by adonno** [comment]
is there a way to import from Best Practical RT to Zammad ?

**Comment by MrGeneration** [comment]
Sorry, but please don't recycle closed issues like that.
This Issue Tracker is the wrong place for technical questions like that, please consult our Community: https://community.zammad.org .

Beside we don't have any best practise for request tracker to Zammad-Migration. If Request Tracker has an API, you could use that.
