### ISSUE TITLE
Using square brackets in Postmaster Filter

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#3619]
### Infos:

* Used Zammad version: 4.1.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1086146

### Expected behavior:

* It should be possible to use a Postmaster Filter for an email subject matching on a whole sentence, that includes square brackets. 
* For example: "[ALERT VM] Instance - CPU utilization"

### Actual behavior:

* A Postmaster Filter with "Subject" - "contains" - "[ALERT VM] Instance - CPU utilization" 
-> Does not match an email with above subject.  

* A Postmaster Filter with "Subject" - "contains" - "ALERT VM Instance - CPU utilization"
-> Does match an email with above subject. 

### Remark: 
* Escaping the square brackets with backslashes, e.g.: "\\[ALERT VM\\] Instance - CPU utilization", doesn't match the subject either.  

### Steps to reproduce the behavior:

* Create the following Postmaster Filter: 

![image](https://user-images.githubusercontent.com/69846837/122224829-c802e480-ceb4-11eb-8a00-4661add32bf0.png)

* Observe if it matches an email with the subject: "[ALERT VM] Instance - CPU utilization"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Testmail subject and filter configuration for subject didn't match up so no issue.
