### ISSUE TITLE
HTML table in mail preview is misformatted

### ISSUE THREAD

**Issue by michaldaniel** [zammad/zammad#3630]
### Infos:

* Used Zammad version:  3.6.x; stable 5.0.3
* Installation method: any
* Operating system: any
* Browser + version: Firefox 89.0.1, verified on Google Chrome 97.0.4692.71 (but doesn't matter really)
* Ticket: #1099994
* **Ticket#10115144  has email examples**

### Expected behavior:

There seems to be a difference in the way a table email is formatted caused by enveloping an email preview within .richtext-content CSS class. The rule:

```
.richtext-content table {
    word-break: break-all;
}
```
causes weird formatting that's not present when viewing message in web email client.

Message as seen in Roundcube Webmail:

![Zrzut ekranu z 2021-06-21 14-56-47](https://user-images.githubusercontent.com/1345297/122766532-f19b8180-d2a1-11eb-8128-e64030742b45.png)

Message as seen in Zammad:

![Zrzut ekranu z 2021-06-21 14-57-08](https://user-images.githubusercontent.com/1345297/122766546-f6603580-d2a1-11eb-9612-3c8fa727b9ab.png)

Message source contains plain table structure.

**Comment by MrGeneration** [comment]
Please re-verify this on Zammad 4.1. 3.6 is quite outdated by now.

**Comment by michaldaniel** [comment]
I updated our Zammad instance to 4.1.x and the issue persists.

**Comment by MrGeneration** [comment]
On a newly imported similar mail?

**Comment by michaldaniel** [comment]
I will generate new test mail, give me a minute.

**Comment by michaldaniel** [comment]
The same happens when new mail is imported.

This is how it looks straight after import:

![Zrzut ekranu z 2021-06-21 15-37-04](https://user-images.githubusercontent.com/1345297/122771700-f4e53c00-d2a6-11eb-9f47-71c2d2f09c5f.png)

If I disable this CSS word-break rule in browser inspector

![Zrzut ekranu z 2021-06-21 15-38-25](https://user-images.githubusercontent.com/1345297/122771783-0a5a6600-d2a7-11eb-9d1e-fa7ea821f9df.png)

The mail looks fine

![Zrzut ekranu z 2021-06-21 15-38-47](https://user-images.githubusercontent.com/1345297/122771803-10504700-d2a7-11eb-96a0-ed0ff22760fe.png)

**Comment by xoladone** [comment]
Similar issue with  word-break: break-all; in .richtext-content table 
Lower example is word-break unchecked.
![image](https://user-images.githubusercontent.com/44923461/130426148-71c7652c-14a4-49db-bf50-ab3bee9adb36.png)

Chrome Version 92.0.4515.159
Zammad Version 4.1.x

**Comment by fliebe92** [comment]
If it is needed to check this issue in the future, please, use the examples that are mentioned in the initial description.
