### ISSUE TITLE
Freshdesk import subdomain selection fails

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad#3631]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): source
* Operating system: macOS 11.4
* Database + version: PostgreSQL 11.3
* Elasticsearch version: irrelevant
* Browser + version: Chrome 91

### Expected behavior:

* The subdomain selection dialog works correctly.

### Actual behavior:

* At least for some (valid) domains, the dialog returns this error: `RuntimeError: Too many redirections for the original URL, halting`
* This might be connected to the use of SSO / OAUTH:
```
web.1       | ["GET", "https://example.freshdesk.com"]
web.1       | ["GET", "https://example.freshdesk.com/support/home"]
web.1       | ["GET", "https://example.freshdesk.com/support/login"]
web.1       | ["GET", "https://example-colors-team.myfreshworks.com/oauth/authorize?client_id=[...]&redirect_uri=https%3A%2F%2Fexample.freshdesk.com%2Ffreshid%2Fauthorize_callback&response_type=code&hd=example.freshdesk.com"]
web.1       | ["GET", "https://example.freshdesk.com/freshid/authorize_callback?error=login_required&error_description=user_login_is_required"]
web.1       | ["GET", "https://example.freshdesk.com/support/login"]
web.1       | ["GET", "https://example-colors-team.myfreshworks.com/oauth/authorize?client_id=[...]&redirect_uri=https%3A%2F%2Fexample.freshdesk.com%2Ffreshid%2Fauthorize_callback&response_type=code&hd=example.freshdesk.com"]
web.1       | ["GET", "https://example.freshdesk.com/freshid/authorize_callback?error=login_required&error_description=user_login_is_required"]
web.1       | ["GET", "https://example.freshdesk.com/support/login"]
web.1       | ["GET", "https://example-colors-team.myfreshworks.com/oauth/authorize?client_id=[...]&redirect_uri=https%3A%2F%2Fexample.freshdesk.com%2Ffreshid%2Fauthorize_callback&response_type=code&hd=example.freshdesk.com"]
web.1       | ["GET", "https://example.freshdesk.com/freshid/authorize_callback?error=login_required&error_description=user_login_is_required"]
```
- Entering such an URL in the Browser directly does work, probably because in JS context some things are handled differently: after 5 redirects the browser shows a login page at "https://example.freshdesk.com/support/login".

### Steps to reproduce the behavior:

* Try to select an affected subdomain (details available from me/mg) for FreshDesk import.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mgruner** [comment]
Suggestion: perhaps access /api/v2/tickets or another of the available endpoints and check for an unauthorized error instead?

**Comment by martini** [comment]
Addition to successtion: Check if `X-Freshdesk-Api-Version` header exists. It's also working with not authenticated requests.
