### ISSUE TITLE
Text Module widget is broken/hidden after pressing backspace (once)

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3637]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): any
* Operating system: mac + linux
* Database + version: any
* Elasticsearch version: any
* Browser + version: Chrome 91 & FF 89

### Expected behavior:

* Allow modifying of search phrase by using backspace

### Actual behavior:

* After backspace is use, no text module widget is shown anymore.

### Steps to reproduce the behavior:

* See video:
 
![text-modules-broken-on-backspace](https://user-images.githubusercontent.com/110226/123389911-a8497b80-d59a-11eb-8542-a9b0849ae5d9.gif)

**Comment by MrGeneration** [comment]
JFI: #3636 may have a similare root cause
