### ISSUE TITLE
Mention widget is still shown even if @@ is deleted

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3638]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Chrome 91 & FF 89

### Expected behavior:

* Remove mention widget if @@ is deleted

### Actual behavior:

* Mention widget is still shown even if @@ got removed

### Steps to reproduce the behavior:

* See video
![mention-widget-is-still-shown-after-removing-at-at](https://user-images.githubusercontent.com/110226/123391368-3d00a900-d59c-11eb-91ae-777d6c5e76f3.gif)

It seems to be related to #3637

**Comment by rolfschmidt** [comment]
should be fixed also with https://github.com/zammad/zammad/issues/3637
