### ISSUE TITLE
Freshdesk subdomain selection "not found" for valid domain

### ISSUE THREAD

**Issue by jeremyrnelson** [zammad/zammad#3645]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04.2
* Database + version: Postgres 12.7
* Elasticsearch version: n/a
* Browser + version: Edge 91, Chrome 92 (both for Mac)

### Expected behavior:

On FreshDesk import screen, finds subdomain and moves on.

### Actual behavior:

Says "not found"

### Steps to reproduce the behavior:

Clean Zammad instance, try to import pintechfw.freshdesk.com

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by jeremyrnelson** [comment]
@dominikklein - Ubuntu package 4.1.0-1625755681.e3a070c7.focal does not seem to have this fixed. Is there a better or more appropriate way to test?

**Comment by dominikklein** [comment]
@jeremyrnelson i tested it in my test system with the sub domain `pintechfw` and for me all is working find during the subdomain check.
I think we need some more detailed information, maybe there is something in the zammad log? Is it maybe in general not working, can you test the subdomain `zammad` on your system?

**Comment by jeremyrnelson** [comment]
Confirmed that the issue was on my side - thanks!
