### ISSUE TITLE
Error 500 / zammad {"error":" 123456 is out of range for ActiveModel::Type::Integer with limit 4 bytes"}

### ISSUE THREAD

**Issue by blu-IT** [zammad/zammad#3647]
Hello,

I am running Zammd in docker.
I added a special field in **objects**, lets say it is a booking no. and type is "integer" (min: 0 / max. fields: 100000000000000000000)
When I try to insert a number in that field in an existing ticket and I try to save it sometime is works and sometimes I get this error:

```
Error 500
zammad {"error":" 123456 is out of range for ActiveModel::Type::Integer with limit 4 bytes"}
```

Any ideas?

### Infos:

* Used Zammad version: 4.0.0
* Installation method: Docker
* Operating system: Ubuntu 18.04 LTS
* Database + version: Postgres
* Elasticsearch version: unkown
* Browser + version: Firefox 89.02

### Expected behavior:

* Booking no. can be inserted and saved.

### Actual behavior:

* I get the error mentioned above

### Steps to reproduce the behavior:

* Go to Administration -> objects.
* Create a new field (integer).
* Update database.
* Go to an existing ticket and try to insert a number.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Hi @blu-IT 

What database are you using? I cannot reproduce this with Postgres.

**Comment by blu-IT** [comment]
@mantas Hi,

I think it is Postgres, my colleague installed zammad via docker. Checking the config found entrys for Postgres-DB.
Is there a command for checking the zammad config?

**Comment by MrGeneration** [comment]
Please provide the log output of your railsserver container. 
We currently can't reproduce this on postgres (which is used for docker by default).

Please also double check if you're using docker or docker**-compose**.

**Comment by mantas** [comment]
Actually.. I was able to reproduce this. I naively tried to enter `9999999` as max value and your value did pass then. But when I entered your value, bam, same error as yours :)

**Comment by blu-IT** [comment]
So what do you suggest to do? I have to set a max. value, can't irgnore this.

It is docker-compose that was used for setting up the system for production environment.

**Comment by MrGeneration** [comment]
> So what do you suggest to do? I have to set a max. value, can't irgnore this.

Choose a lower value if applicable or wait for a bug fix....?

**Comment by mantas** [comment]
@blu-IT set max value to 2147483647 or lower
