### ISSUE TITLE
Replace message.html with "origin markup"

### ISSUE THREAD

**Issue by martini** [zammad/zammad#365]
To improve user experience replace "message.html" of every email with "view origin markup" button.

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
