### ISSUE TITLE
Chat widget cannot load CSS on (sub)domains that contain "ws" characters

### ISSUE THREAD

**Issue by patrickatwsrn** [zammad/zammad#3654]
### info:

* Used Zammad version:  Zammad Version 4.1.x 
* This is related to the core files executed on a client borwser and not effected by server environment.

###

Problem: We want to add the chat tool to our homepage but loadCss is "messing" arround with the url of the domain hosting zammad.

### Expected behavior:

wsrn.support goes in wsrn.support comes out.

### Actual behavior:

* https://wsrn.support/assets/chat/chat.js becomes 
* https://rn.support/ws/assets/chat/chat.css

### Steps to reproduce the behavior:

Create a chat widget in zammad for a domain containing the letters "ws", or "wss"

Copy the code to your page and enjoy!

### Discussion

I guess the code below is responsible for this behaviour:

```
    /* chat.js */
    ZammadChat.prototype.loadCss = function() {
      var newSS, styles, url;
      if (!this.options.cssAutoload) {
        return;
      }
      url = this.options.cssUrl;
      if (!url) {

        /* the next line breaks our integration */
        url = this.options.host.replace(/^wss/i, 'https').replace(/^ws/i, 'http').replace(/\/ws/i, '');
        url += '/assets/chat/chat.css';
      }
      this.log.debug("load css from '" + url + "'");
      styles = "@import url('" + url + "');";
      newSS = document.createElement('link');
      newSS.onload = this.onCssLoaded;
      newSS.rel = 'stylesheet';
      newSS.href = 'data:text/css,' + escape(styles);
      return document.getElementsByTagName('head')[0].appendChild(newSS);
    };
```
source: https://github.com/zammad/zammad/blob/develop/public/assets/chat/chat.js

I don't get why the replace function is there in the first place and even if there is a reason why anybody would think this is a good solution for this particular problem. I'm really curious about this part and it would be great to get some pointers.

I'm aware that I can solve the problem by using setting "cssAutoload" to false and adding an url for "cssUrl", but I don't believe this should be necessary.

Regards,

Patrick

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*


---


If you want to discuss functionalities of Zammad, please use the community as well.

**Comment by patrickatwsrn** [comment]
Hi,

thanks for your support.

I disagree on your assessment, but I'll repost the question in the community as required. 

That being said, I would be very happy if you would reconsider your descicion to close this issue.

I'm aware that this behaviour was not intended, but I'm also 100% confident that this is a design flaw that should be fixed.

Regards,

patrick

**Comment by mantas** [comment]
@patrickatwsrn could you post `this.options.host` value? Or even the dump of `this.options`? If it's an information that you want to keep private, please send it to support@zammad.com and mention this github issue number.

**Comment by patrickatwsrn** [comment]
@mantasI I suppose you are asking for the js config.

It's the default embed code:

```
<script src="https://wsrn.support/assets/chat/chat.min.js"></script>
<script>
$(function() {
  new ZammadChat({
    fontSize: '12px',
    chatId: 2
  });
});
</script>

Regarding the host option...

adding

```
	host: 'https://wsrn.support/'  
```
to the ZammadChat option has the following results:

WITHOUT setting a host:
* https://rn.support/ws/assets/chat/chat.css

WITH setting a host:
* https://rn.support//assets/chat/chat.css


the "ws" part of the domain is ALWAYS removed (see line 1752 of chat.js - https://github.com/zammad/zammad/blob/fe93104a07ec16e1dd8271abf410070c57d93d39/public/assets/chat/chat.js#L1752).

This part of the code seems to be present since 25 Nov 2015. It was committed by @martini (https://github.com/zammad/zammad/commits?author=martini). Perhaps he can elaborate about its purpose.

**Comment by mantas** [comment]
@patrickatwsrn it is indeed an issue... Interesting :|

note for later:
```
'https://wsrn.support/'.replace(/^wss/i, 'https').replace(/^ws/i, 'http').replace(/\/ws/i, '')

>> "https:/rn.support/"
```
