### ISSUE TITLE
Knowledge Base / Help center

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#366]
Users want a Knowledge Base / Help center.

**Comment by m4r71n** [comment]
An integration with Atlassian Confluence would be awesome

**Comment by hanneshal** [comment]
@m4r71n 
What kind of integration would you suggest? 
Zammad UI but connected to the confluence api in the backend as ro source for KB article?
Could you describe such an integration for us? Maybe a feature list?

regards

**Comment by m4r71n** [comment]
@hanneshal 
I've no detailed requirements but
> Zammad UI but connected to the confluence api in the backend as ro source for KB article?

sounds awesome! Maybe not only limited to KB articles.

**Comment by rolfschmidt** [comment]
Flavio wrote us:

> I'd love to see some form of hardware-management like a CMDB where I can overview my inventory (the only reason why we didn't switch to zammad from our current ticketing system).

**Comment by petervanbeugen** [comment]
I would like an OTRS FAQ look-a-like solution inside Zammad. It's straightforward but satisfies. It will make a complete transition from OTRS to Zammed possible.

**Comment by arrayown** [comment]
Been looking at Zammad for a while and the only thing holding me back is the lack of knowledgebase. Also, multi-lingual capability so that content can be published in multiple languages. osTicket does a very good job of the I18N of their solution.

**Comment by wucherpfennig** [comment]
+1

**Comment by lb1c** [comment]
The need for an knowledge base (self-service portal) is definitly there.
We would also appreciate the ability to use confluence spaces/articles as read only data source. 
+1

**Comment by reeperbahnause** [comment]
+1

**Comment by Bjoern3003** [comment]
+1

**Comment by hanneshal** [comment]
To stop the unnecessary +1 posts I lock this thread. We are working on stuff... see https://zammad.com/news/status-outlook 

No ETA, but we are working on it.

**Comment by thorsteneckel** [comment]
It's been a while since we gave you the last update on this. However, I just want to inform you that the great @mantas started working full time on the implementation. We will come back to you in the next weeks / month and give you a status update. Thanks for your patience 👍

**Comment by thorsteneckel** [comment]
A little colorful bird just told me that you should keep an eye on the [news section of our website](https://zammad.com/news) tomorrow. [Closing now](https://github.com/zammad/zammad/commit/97d14a93b3fee85769cedf4c1e7abd770798088f). Thanks to everybody being involved and a special thanks for your patience from the whole team!
