### ISSUE TITLE
New user logging in via SAML - no user shown in user management and no possibility to modify permissions

### ISSUE THREAD

**Issue by pfruh** [zammad/zammad#3662]
### Infos:

* Used Zammad version: 4.1.0-1626082487.5063437e.focal
* Installation method (source, package, ..): Ubuntu Package
* Operating system: Ubuntu 20.04.2
* Database + version: postgresql 12.7
* Elasticsearch version: 7.13.3
* Browser + version: Firefox 90

### Expected behavior:

* A new SAML user (email does not exist in local database) logs in and `Automatic account link on initial logon` is activated
* A new account is created in the local database with the email/metadata from SAML and the SAML user is linked
* The user is shown in the `Users` management menu and their permissions and additional metadata can be modified

### Actual behavior:

* The user is **not** shown under `Users` and their permissions and additional metadata therefore **can't** be modified
* Trying to create the user afterwards fails with `Email address 'user@example.com' is already used for other user.`

### Steps to reproduce the behavior:

* Activate `Automatic account link on initial logon`
* Log in via SAML with a new user/email that's not in the local database
* User does **not** show up under `Users` -> Permissions can't be modified
* Try to create user with the same email address to be able to modify their permissions
* Fails with `Email address 'user@example.com' is already used for other user.`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by Janl1** [comment]
Did you even read the report? It does not seem like it...
For me it clearly sounds like a bug.

**Comment by MrGeneration** [comment]
Yes. 
User does not appear in user management.

Clearly not a bug but a question.
Question classic. Please don't create more noise for 2000+ people on this repository with technical questions, thank you.

**Comment by pfruh** [comment]
If someone stumbles across this issue - it's not a separate one but related to other "Users missing from Interface" issues and caused by the elasticsearch index missing data.

I don't know why this one user wasn't added to the elasticsearch index, since my elasticsearch installation was running without any issues, however rebuilding the indices by running `zammad run rake searchindex:rebuild` fixed it.
Maybe it's related to the users being created indirectly via SAML.

If this is such a common occurence that it is a "question classic" it would be nice if there was some kind of general FAQ or Troubleshooting section in the docs or warning in the admin interface about out of date indices.
Even a "please check your elasticsearch instance" as a response would've made the whole process a lot more pleasant experience.

**Comment by MrGeneration** [comment]
> If this is such a common occurence that it is a "question classic" it would be nice if there was some kind of general FAQ or 
> Troubleshooting section in the docs or warning in the admin interface about out of date indices.
> Even a "please check your elasticsearch instance" as a response would've made the whole process a lot more pleasant experience.

Sure. A pull request for the documentation is warmly welcome if you find the spare time.
