### ISSUE TITLE
Longer category names break boxes in mobile version

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3665]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all
* Ticket#1087635

### Expected behavior:

* Longer category names break boxes in mobile version

### Actual behavior:

![grafik](https://user-images.githubusercontent.com/5445062/126297224-4b1dc93c-f0c4-4f25-8f51-1a9ea3816177.png)

### Steps to reproduce the behavior:

* Create long category names
* Open mobile version

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mrflix** [comment]
@rolfschmidt 

1. Can you disclose what the two long titles say? I'm wondering what reason they have to make the titles so long. Is there maybe a need for a description per category? For example like [Facebook](https://www.facebook.com/help) has them:
![Screenshot 2021-07-23 at 08 44 48](https://user-images.githubusercontent.com/60777/126746328-b53b0af4-ceae-46e8-965b-a0d1a814e4c7.png)

2. What screen-width was the screenshot taken on?

Also – we're missing space here on the left side that would give more space to the titles. There's a strong rule adding `padding-left: 1.5em` thats breaking this.
![Screenshot 2021-07-23 at 08 42 20](https://user-images.githubusercontent.com/60777/126746070-abe3cdcd-c7e0-4268-bfc2-87c7addb7c66.png)

**Comment by mantas** [comment]
+1 for description. I remember pre-release version did have it, but we removed it at some point...

**Comment by dominikklein** [comment]
@mantas i think we should create a new enhancement issue for knowledge base category description and this problem here will be fixed for mobile at the meanwhile.

**Comment by mantas** [comment]
@dominikklein sounds good for me
