### ISSUE TITLE
Package installation fails because of too long file names

### ISSUE THREAD

**Issue by sandysong** [zammad/zammad#3666]
Running transaction
  Installing : zammad-5.0.0-1626714207.5675887e.centos7.x86_64                                                                                                                                                                           1/1
Error unpacking rpm package zammad-5.0.0-1626714207.5675887e.centos7.x86_64
error: unpacking of archive failed on file /opt/zammad/test/data/vcr_cassettes/requests/external_credentials/external_credentials_authenticated_as_admin_for_twitter_get_api_v1_external_credentials_twitter_callback_with_valid_twitter_app_request_token_and_matching_oauth_token_via_params_if_twitter_account_has_already_been_added_updates_channel_properties.yml;60f6aa24: cpio: open
  Verifying  : zammad-5.0.0-1626714207.5675887e.centos7.x86_64                                                                                                                                                                           1/1

Failed:
  zammad.x86_64 0:5.0.0-1626714207.5675887e.centos7

**Comment by MrGeneration** [comment]
develop is currently broken, don't use it.

**Comment by thorsteneckel** [comment]
Thanks for the heads up @sandysong - develop is fixed. Packages should be available in about 30 minutes from now 🚀
