### ISSUE TITLE
FreshDesk Import doesn't pull in auto-assign domain(s) for organizations

### ISSUE THREAD

**Issue by jeremyrnelson** [zammad/zammad#3687]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04
* Database + version: Postgres 12.7
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

Pull in at least 1 of the domains from FreshDesk, since I believe Zammad only allows for a single domain while FreshDesk allows for multiple.

Confirmed that this info is available from /api/v2/companies

### Actual behavior:

All orgs come in with domain-based assignment "No"

### Steps to reproduce the behavior:

Do a Freshdesk Import with orgs that have domains set.

(I'm not certain you wouldn't classify this as a feature request, but it seems more like a minor overisght whe

**Comment by dominikklein** [comment]
We added the usage of the first domain from freshdesk for the added orgnanization in zammad, because of the limitation that Zammad supports only one domain and freshdesk mulitple domain.
