### ISSUE TITLE
Removing organizations removes user and ticket as well

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3688]
### Infos:

* Used Zammad version: 4.1/stable
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: ~~#1090309~~
* *Note: This may have been introduced due to Data Privacy*

### Expected behavior:

When removing an organization, Zammad will not remove ticket data or users as removing the organization only may be an use case.

### Actual behavior:

When removing an organization, Zammad flushes everything down the drain.

```
2.6.6 :002 > Organization.where(active: false).first.destroy
Ticket::Article.find(1) notify DESTOY 2021-06-25 10:08:07 UTC
Ticket.find(1) notify UPDATED 2021-08-02 14:05:00 UTC
User.find(2) notify TOUCH 2021-08-02 14:05:00 UTC
Organization.find(1) notify TOUCH 2021-08-02 14:05:00 UTC
Ticket.find(1) notify DESTOY 2021-08-02 14:05:00 UTC
# curl -X delete "http://127.0.0.1:9200/hf7cge8u2y_production_ticket/_doc/1"
# 200
User.find(2) notify TOUCH 2021-08-02 14:05:00 UTC
Organization.find(1) notify TOUCH 2021-08-02 14:05:00 UTC
User.find(2) notify DESTOY 2021-08-02 14:05:00 UTC
# curl -X delete "http://127.0.0.1:9200/hf7cge8u2y_production_user/_doc/2"
# 200
Organization.find(1) notify DESTOY 2021-07-28 12:14:37 UTC
# curl -X delete "http://127.0.0.1:9200/hf7cge8u2y_production_organization/_doc/1"
# 200
 => #<Organization id: 1, name: "Zammad Foundation", shared: true, domain: "", domain_assignment: false, active: false, note: "", updated_by_id: 548, created_by_id: 1, created_at: "2021-06-25 10:08:07", updated_at: "2021-07-28 12:14:37">
 ```

### Steps to reproduce the behavior:

* remove the default `Zammad Foundation` organization and see Nicole Braun and Ticket-ID 1 missing

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
@rolfschmidt maybe you should check this? Because you added the lines for the deletion, maybe it's needed or it should be two versions for the destroying of organizations.

https://github.com/zammad/zammad/blob/3b8ff4d17848a0a12c3486463316b5d661301b84/app/models/organization.rb#L50-L53
