### ISSUE TITLE
FreshDesk Import brings in all users as inactive

### ISSUE THREAD

**Issue by jeremyrnelson** [zammad/zammad#3689]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04
* Database + version: Postgres 12.7
* Elasticsearch version: n/a
* Browser + version: Edge 92 on MacOS 11.4

### Expected behavior:

* Customers are imported as Active/Inactive based on setting in FreshDesk

### Actual behavior:

* Customers all come in as Inactive (as far as I can tell - I haven't found any that came in as active)

### Steps to reproduce the behavior:

* Import FreshDesk data with active and inactive customers (contacts in FreshDesk parlance)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by jeremyrnelson** [comment]
I did some more searching and querying in FreshDesk, and I see what happened - FreshDesk and Zammad use "Active" to mean different things:

In FreshDesk, "Active" seems to mean that the user has logged into the web portal (most of our customers use only email to communicate with us, so "active" is false for most of our customers).

In Zammad, "Active" means that the customer/agent/admin can log in.  Most of our users CAN log in, they just choose not to.

I would argue that the closest analog is to mark ALL users active (or prompt the admin at the time of import, I suppose).  "Deleted" users in FreshDesk seem to be the analog of "Inactive" in Zammad.  They don't show up at all in the test API queries I'm running, even though the record still exists and I could restore the user via the web interface.

**Comment by dominikklein** [comment]
@jeremyrnelson thanks for the hind, i also saw this in my tests and the user active flag in zammad will now always be `true` and only for deleted/blocked users it will be `false`.
