### ISSUE TITLE
Possibility to confirm self registered user

### ISSUE THREAD

**Issue by ntinti** [zammad/zammad#369]
It would be useful against spam to have the option that self registered user first have to be proofed by an admin before they can login.

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
