### ISSUE TITLE
'References' mail header may exceed RFC limit of 1000 chars and mail servers won't process it

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3691]
### Infos:

* Used Zammad version: 4.1/stable
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1090427

### Expected behavior:

Zammad generates eml headers that fit RFC conditions (header may not be longer than 1000 chars)

### Actual behavior:

Zammad generates e.g. Reference Headers that can hit 10000 chars and more.

### Steps to reproduce the behavior:

* Have a very long ticket with a lot of email communication (80+)
* check references header of a newly generated mail

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Just some additional infos of the ticket:

```
Diagnostic-Code: smtp;.... Remote server returned an error -> 550 References header is too long
```

The example in the ticket contains a `References` mail header which contains 157 lines and ~10500 characters. There are some line length limits in the RFC (https://datatracker.ietf.org/doc/html/rfc2822#section-2.1.1) which were not exceeded but i did not find a total limit or something. For me it makes sense to cut the message ids to a certain amount in the references header.

**Comment by rolfschmidt** [comment]
@MrGeneration and me we werent able to reproduce this with a outlook.com account. Seems to be a third party issue. Will be closed for now.
