### ISSUE TITLE
Not working unpack of mail body if decrypted body is in signed-data attachment

### ISSUE THREAD

**Issue by poettig** [zammad/zammad#3705]
### Infos:

* Used Zammad version: 4.1.0-1629312456.6b128b41.buster
* Installation method (source, package, ..): Debian Buster Package (https://dl.packager.io/srv/deb/zammad/zammad/stable/debian)
* Operating system: Debian 10 (Buster)
* Database + version: 11.12
* Elasticsearch version: 7.14.0
* Browser + version: Firefox 91.0.1

The mailclients of most staff at my workplace (Outlook 2019) send encrypted + signed mail as x-pkcs7-mime enveloped-data if encrypted, which results in a mail containing x-pkcs-7-mime signed-data after decrypting. 

Before decryption:
```
Content-Type: application/pkcs7-mime; smime-type=enveloped-data;
	name="smime.p7m"
Content-Disposition: attachment; filename="smime.p7m"
Content-Transfer-Encoding: base64
```

After decryption:
```
Content-Type: application/x-pkcs7-mime; name=smime.p7m; smime-type=signed-data
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=smime.p7m
```

The mail parser in Zammad cannot find a body in this case, as far as I can see it does not decode the attachment to find a mail body in it. An example mail is attached, before and after decryption. I removed most of the (unneeded) headers to hide internal details of our mail system. Additionally, the decoded attachment is added, showing the mail body.

[mail.zip](https://github.com/zammad/zammad/files/7014178/mail.zip)
[production.log](https://github.com/zammad/zammad/files/7014179/production.log)

Therefore, all encrypted mails we receive from staff are not readable in Zammad articles. Downloading "raw" and opening them e.g. with Thunderbird works fine. Encrypted, but not signed messages from Outlook 2019 are displaying their body correctly.

I also created a sibling issue for signing verification not working for these mails (#3704).

### Expected behavior:

* Mail body is shown in article

### Actual behavior:

* Article content is "no visible content"

### Steps to reproduce the behavior:

* Send an encrypted + signed mail from Outlook 2019

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by datadorf** [comment]
Hello,

I have a similar / same problem:

Actual behavior:

Article content is "no visible content" / "cant verify message"

Steps to reproduce the behavior:

Send an signed Email from Zammad and open it on an Apple iOS device
![IMG_A961F80B7A85-1](https://user-images.githubusercontent.com/81630658/130942404-b50f79ef-c696-4c38-8ff1-51de8c77de93.jpeg)

On OSX with Apple Mail oder other Mailclients its working fine, I can open this Email.

**Comment by MrGeneration** [comment]
@datadorf please don't hijack other issues with your problems. 
If you believe that this is a Zammad bug, create an independent issue. 
If this is a technical question, please ask the question on our community board: https://community.zammad.org
