### ISSUE TITLE
Unable to close tickets in certran cases if core workflow is used

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3710]
### Infos:

* Used Zammad version: 5.0/develop (2021-08-26)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Allow closing tickets if certain field is removed by core workflow (but field was marked as required by previous rule)

### Actual behavior:

* Ticket can not get closed, even if it's removed (by role).

### Steps to reproduce the behavior:

* create 3 groups: Sales, Support, Accounting
* create Ticket.category as tree select with 4 items
* create first core workflow rule to disable Ticket.category for tickets in Group Sales & Accounting
* create second core workflow rule to make Ticket.category field as required field if ticket gets closed.
* open a ticket
  * make sure that the ticket is in Group Sales
  * verify that Ticket.category is not shown (because of first core workflow rule)
  * try to close the ticket (which will not work - no error message is shown - noting happen by click on "update")

![image](https://user-images.githubusercontent.com/110226/130966274-0fbefc2f-b112-4f53-ac98-658b0cf96224.png)

**Comment by rolfschmidt** [comment]
Still broken need another follow up fix...
