### ISSUE TITLE
Tree-Selects behave glitchy with select actions

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3711]
### Infos:

* Used Zammad version: 5.0/develop (2021-08-26)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on latest Google Chrome

### Desired behavior:

Zammad should either restrict selecting not allowed values or completely hide them. 
The setting may be invalid for the affected desired outcome but still behaves "odd".

### Actual behavior:

When having select actions applied to a tree select, you can no longer select any value that's not selected in the action. 
The dialogue glitches to closed.

![core-workflow-show-only-relevant-settings-glitch_github](https://user-images.githubusercontent.com/6549061/130969350-68115467-3df9-4842-a4c7-6835e1c36306.gif)

### Steps to reproduce the behavior:

* have a tree select with below core workflow setting for extra fun

![image](https://user-images.githubusercontent.com/6549061/130969827-59a027a3-de80-4fb5-a9b8-060a64ecd65c.png)

**Comment by rolfschmidt** [comment]
https://github.com/zammad/zammad/commit/78edf3197693cc55a403c635476d01c49688a783

**Comment by rolfschmidt** [comment]
operator select does select an option.

operator set_fixed_to restricts the values of the tree select.

The missing operators are now available.

**Comment by MrGeneration** [comment]
So selecting more than one `select` value would be invalid as well?
