### ISSUE TITLE
Pasting in Firefox adds unwanted whitespace/line break

### ISSUE THREAD

**Issue by delphi-sucks** [zammad/zammad#3716]
### Infos:

* Used Zammad version: 4.1.0-1625206819.c53e17f7.xenial
* Installation method (source, package, ..): package
* Operating system: Ubuntu 16.04
* Database + version: MySQL Server 5.7.33
* Elasticsearch version: 7.12.0
* Browser + version: Firefox 89.0.2
* Ticket#1093187, Ticket#10123846

### Expected behavior:

Pasting text in the ticket text works like expexted.

### Actual behavior:

1. When pasting plaintext copied from a text-editor for example (needs to be plaintext in the clipboard) line breaks get added before or after the pasted text, if there is text before or after.
2. When copy and pasting text in the ticket text-input, a whitespace gets added the same way like in situation 1.

#### Way 1 - adds line break

![ezgif-7-562c6d6fcfac](https://user-images.githubusercontent.com/17913239/131333273-f408d938-dd2a-4382-aaee-33a91e38da7b.gif)

1. Create a new ticket
2. Copy a random text from the texteditor (needs to be plain text in the clipboard)
3. Paste it in the ticket text.
=> A line break gets added before/after the pasted text, if there's text before/after it

#### Way 2 - adds whitespace

![ezgif-7-bda623d84344](https://user-images.githubusercontent.com/17913239/131333232-0d4052fb-9cca-4c89-a81e-73afaf713a29.gif)

1. Create a new ticket
2. Write random text in the text-input
3. Copy a middle part and paste it
=> Whitespace gets added before/after the pasted text, if there's text before/after it

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Note: 
This also happens in e.g. user creation modals, not sure if that helps.

**Comment by poettig** [comment]
This especially happens when inserting URLs, even if they are inserted via a text module. It makes working with text modules containing only a link rather unpleasant.
