### ISSUE TITLE
Dashboard stopped working

### ISSUE THREAD

**Issue by klando** [zammad/zammad#3718]
### Infos:

* Used Zammad version: 4.1.x 
* Installation method (source, package, ..): docker-compose
* Operating system: Debian buster
* Database + version: pg 13
* Elasticsearch version: from docker-compose
* Browser + version: firefox 78.13.0esr

### Expected behavior:

* getting a dashboard

### Actual behavior:

* blank page (well, not full blank, the left panel is here)

### Steps to reproduce the behavior:

* got to https://..../#dashboard

Yes I'm sure this is a bug and no feature request or a general question.

```
App.n(error)                   | executeSingel task: Dashboard ReferenceError: item is not defined
    application-0afe8fb8beae49da56da112feac7cfc9e0727a0333c77fbb1affcef2ffa182ba.js:22:15475
```

It happened after I did manage groups, roles, triggers.

What buzz me too and should be useful (and also a bug I bet): the group list in the user config panel contains groups that I deleted (with rails g.delete) and which are not visible in the group panel.
I clear cache  (on rails), but it did not fix the situation.

There is probably a workaround (which I can ask on the zammad.org) but I post here because there is an underlying bug  maybe.

**Comment by MrGeneration** [comment]
Sorry but that's a bit too cloudy. 
If you don't want me to close this as a technical question instantly, please provide the exact settings of your instance that caused that.

**Comment by klando** [comment]
thinking more of the problem, let's go for a technical question.
