### ISSUE TITLE
Potential (minor) security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [zammad/zammad#3719]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential (minor) security problem.

**Comment by MrGeneration** [comment]
Please contact security [at] zammad [dot] com if you believe you found a security issue for a responsible disclosure. 

Thank you!

**Comment by intrigus-lgtm** [comment]
Email has been sent.
