### ISSUE TITLE
Zammad email config verification error when using imap folders different than inbox

### ISSUE THREAD

**Issue by spelroth** [zammad/zammad#3722]
### Infos:

* Used Zammad version: zammad-4.1.0-1630584543.bf41a7ac.centos7.x86_64
* Installation method (source, package, ..): package
* Operating system: Centos 7
* Database + version: postgres (PostgreSQL) 9.2.24
* Elasticsearch version: elasticsearch-7.14.1-1.x86_64
* Browser + version: chrome

### Expected behavior:

* When configuring email channel with the proper credentials that use a subfolder eg Inbox/Zammad Zammad sends an email and checks for the received email. It should send the email and check it in the folder and inbox also, or just allow to save the config 

### Actual behavior:

* When the check occur the email being sent it is being received in the Inbox folder, but searches only in the Inbox/Zammad imap folder which causes the configuration to fail to change and save. Manually moving the email sent from Zammad to the Inbox/Zammad folder allows Zammad to accept the verification.

### Steps to reproduce the behavior:

* Configure the email channel with a Folder without any inbox rules on the email provider wait for timeout. Reproduce again with a rule to move for the Zammad or any imap folder. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.

**Comment by spelroth** [comment]
Hey, I don't think that this is a feature request, because the configuration will fail when the email provider has no rules.
Currently the setup looks like:
* setup email on zammad
* zammad sends email to verify the config
* the email goes to inbox instead of folder
* zammad doesn't see the email and thinks the config is bad and prints an timeout error

**Comment by MrGeneration** [comment]
Okay no problem. You're right.
It's a technical question.

Here's the reasons:
Our **documentation** clearly warns you about this behavior ( https://admin-docs.zammad.org/en/latest/channels/email/accounts/account-setup.html#experts ):

![image](https://user-images.githubusercontent.com/6549061/131866482-d8e5e2eb-cf1b-49bb-92e3-9f6b287f3800.png)


Also, you're testing your current setup in the process.
This means: We're *expecting* you to have your account configured the way it is intended to work in the future.
This means: Either manually moving the verification mail or have a mail rule set up.

Please don't post technical questions on this repository. 
If you want to discuss and continue how wrong I am with my statement, please still switch to the community.

**Comment by spelroth** [comment]
Ok it seems that I've missed the last note. You're right :).
