### ISSUE TITLE
Drop files here not disappearing after dropping a file

### ISSUE THREAD

**Issue by maxxer** [zammad/zammad#3725]
### Infos:

* Used Zammad version: 4.1.0-1630584543.bf41a7ac.focal
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 20.04
* Database + version: postgresql 12+214ubuntu0.1
* Elasticsearch version: elasticsearch-oss 7.10.2
* Browser + version: Firefox 91

### Expected behavior:

* Drop attachments to compose area
* Type text

### Actual behavior:

* When dropping files the *Drop files here* tooltip remains open covering the compose area. Files are uploaded but it's impossible to go further.

![screenshot-assistenza yetopen com-2021 09 07-08_59_59](https://user-images.githubusercontent.com/240201/132299494-0d67decf-5d47-4405-bae7-d01b7e44b7ad.png)

### Steps to reproduce the behavior:

* Drop a file to the compose area

Yes I'm sure this is a bug and no feature request or a general question.

I'm updating Zammad almost daily and it's happening since one or two weeks.

**Comment by MrGeneration** [comment]
Regression of #3460
