### ISSUE TITLE
Languange selection in mobile app is not working

### ISSUE THREAD

**Issue by efinal** [zammad/zammad#3729]
Infos:

> Used Zammad version: release 4.1.0
> Installation` method (source, package, ..): any
> Operating system: mobile
> Database + version: any
> Elasticsearch version: any
> Browser + version: mobile

Expected behavior:
Be able to select language via own profile

Actual behavior:
Language selection is not shown/not usable

More Comments:
the change 5b6f032, which fixes #3432,  moves the corresponding css into 'phone' section makes the language selection works in desktop mode, but, failed in mobile mode.

**Comment by MrGeneration** [comment]
Please, could you be so kind and not ignore our issue templates...?

**Comment by dominikklein** [comment]
It's working for me, also when it's a little bit strange to use this dropdown.
With the next Major-Release, there will also be a real mobile view available.
