### ISSUE TITLE
Feature "Time recording"

### ISSUE THREAD

**Issue by strey** [zammad/zammad#373]
A Feature to record time would make a great product nearly perfect :)

**Comment by martini** [comment]
Preview, any feedback is welcome.

Discussions:

- global config of only for certain tickets (e. g. support tickets, no sales tickets)

Dialog to add time:
![modal-to-ask-for-time-which-should-be-accounted](https://cloud.githubusercontent.com/assets/110226/21589574/6be57cf8-d0f3-11e6-98ec-efef10d4fe92.png)

Accounted time in sidebar:
![ticket-zoom-show-accounted-time-in-sidebar](https://cloud.githubusercontent.com/assets/110226/21589575/6c099994-d0f3-11e6-8416-64fb2cdfd540.png)

**Comment by thorsteneckel** [comment]
Tbh I think an automatic counter would be so cool. So if you open a ticket a counter starts. The user should be able to toggle between count/pause and changing the value manually.

**Comment by martini** [comment]
@thorsteneckel any ideas are welcome. :-D
