### ISSUE TITLE
Can't find config setting 'es_url' (RuntimeError) despite all my research

### ISSUE THREAD

**Issue by AnthonyFrench84** [zammad/zammad#3730]
### Infos:

* Used Zammad version: v4.1.0
* Installation method (source, package, ..): Source Ubuntu
* Operating system: Ubuntu 18.04 LTS + Plesk
* Database + version: MariaDB 10.1.48
* Elasticsearch version: last
* Browser + version: Chrome and Firefox

### Actual behavior:

*zammad run rails r "Setting.set('es_url', 'http://127.0.0.1:9200')"
/opt/zammad/app/models/setting.rb:37:in `set': Can't find config setting 'es_url' (RuntimeError)

Hello everyone, this is my first question here.
Please excuse my very poor English as well.

Here is my problem.
I have been trying to install Zamad on my dedicated server for several days now, the Ubuntu installation is new and I have also installed Plesk.

I follow the tutorial for the installation by package and I block at the end on the step: run these last commands to complete the setup and configure Zammad to work with Elasticsearch

When I execute the command:

#sudo zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"

I get the following error:
` sudo zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"
/opt/zammad/app/models/setting.rb:37:in `set': Can't find config setting 'es_url' (RuntimeError)
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/commands/runner/runner_command.rb:41:in `eval'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/commands/runner/runner_command.rb:41:in `perform'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/command/base.rb:69:in `perform'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/command.rb:46:in `invoke'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.6/lib/rails/commands.rb:18:in `<main>'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/dependencies.rb:291:in `block in require'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /opt/zammad/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.6/lib/active_support/dependencies.rb:291:in `require'
        from /opt/zammad/bin/rails:9:in `<main>'
`

I have tried all the solutions I find on Google and I can't seem to resolve this difficulty.
I am new to this field.

Thank you all for your help

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by AnthonyFrench84** [comment]
Hello and thank you for the reply but it seems to be a Bug, I followed the tutorials on 2 different servers and I see the same bug. Thank you @MrGeneration

**Comment by slartimitvar** [comment]
I also ran into this issue and had to manually add records to the 'settings' table in the database for each of the following :

es_url
es_index
es_attachment_ignore
es_attachment_max_size_in_mb

The basic insert statement requried was :

INSERT INTO 'settings' SET 
'title'='ElasticSearch URL', 
'name'='es_url', 
'description'='', 
'area'='SearchIndex::ElasticSearch', 
'frontend'=0, 
'created_at'='2021-09-15 12:00:00.000', 
'updated_at'='2021-09-15 12:00:00.000';

**Comment by MrGeneration** [comment]
To reduce further bumps, hijacks and -even worse- wrong information like @slartimitvar provided I'm limitting the conversation to contributors only.

Above "solution" may work in the short end but is NOT suggested.
