### ISSUE TITLE
Allow replacement of English text through translation

### ISSUE THREAD

**Issue by Azd325** [zammad/zammad#3731]
https://github.com/zammad/zammad/blob/3b0a373de0f0fc5da8a1226a559a00129c4cff82/public/assets/chat/chat-no-jquery.js#L910

It would be great if the code would not make an exception for English. This make it easier to change the underlying text without to fork the code. So the text can be change in the translation map.

Community Issue.
https://community.zammad.org/t/allow-english-text-change/7631/5

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
