### ISSUE TITLE
 Bug Report 4.1.x Overview Sort - Grouped by user

### ISSUE THREAD

**Issue by SumOfOneInteger** [zammad/zammad#3737]
### Infos:
Used Zammad version: “This is Zammad version 4.1.x” listed in settings>version
Used Zammad installation type: Package
Operating system: Ubuntu 20.04 LTS
Browser + version: Chromium 93.0.4577.63
Ticket: #1093454, #1093789, #1093820 

### Expected behavior:
All Open Tickets overview.
Order by: Updated at
Order by direction: down
Group by: Owner
Group By Direction: up
Tickets are listed by owner name in alphabetical order. Tickets under owner are listed most recently updated to oldest.

### Actual behavior:
After updating Zammad, the previous expected behavior is still true. Unfortunately when a ticket is updated, it appears at the top of the list with the Owner appearing twice in the overview. Refreshing the page fixes the issue.
Happens every time a ticket is updated - either by customer or by owner. Clearing cache and using a different browser made no difference.

See: 
https://community.zammad.org/t/bug-report-4-1-x-sort/7601
https://community.zammad.org/t/strange-behaviour-in-overviews-grouped-by-user/7556
Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
### Steps to reproduce:

- have a overview that groups by any attribute, easiest would be state or group
- update any ticket in that overview list
- see the overview changing and adding a new "grouped by" section with a value that already is present

**Comment by mk-git** [comment]
Step 1: Assign unassigned Ticket to existing User
![image](https://user-images.githubusercontent.com/4411025/133197061-8952c7b2-6ce2-4d1d-b584-31d62286974f.png)

Step 2: Now in the overview, the user exists two times:
![image](https://user-images.githubusercontent.com/4411025/133197085-64ab233c-d82f-49de-8317-4aaa59c8030f.png)

Step 3: After refreshing / clearing cache the view is as expected
![image](https://user-images.githubusercontent.com/4411025/133197108-1e7bd90d-5c2d-48f8-987f-4f9c161380b5.png)

**Comment by bendergruppe** [comment]
Same Issue by sorting views with group by
[https://community.zammad.org/t/group-order-by-in-overview-not-working-after-latest-update/7558](url)

Overview of the settings
![def0374492fdc3c0da52818c3a8d585a7c0e7c65](https://user-images.githubusercontent.com/90761749/133411151-910809f6-f37b-4c71-861f-85ef42c5fb93.png)

Looks like
![b8b71961b51c9da57ab83cb69592e8c3ed5bb39a_2_690x291](https://user-images.githubusercontent.com/90761749/133411159-69d04c61-c649-45f0-b04e-b058c2eddb73.png)

**Comment by MrGeneration** [comment]
Limiting the conversation to reduce "me toos".
Seems like the whole `group_by` functionality is affected.

A developer will have a deeper look.
