### ISSUE TITLE
French translation grammatical errors

### ISSUE THREAD

**Issue by greedybro** [zammad/zammad#3738]
### Infos:

* Used Zammad version: 4.1.0
* Installation method (source, package, ..): Official Helm chart
* Operating system: debian
* Database + version: postgresql 10.4.9
* Elasticsearch version: 7.10.2
* Browser + version: all

### Expected behavior:

* No grammatical errors on Zammad login page

### Actual behavior:

* Several grammatical errors on Zammad login page. There might be more, but i didn't spot it.

### Steps to reproduce the behavior:

* Set locale to French and go the login page. Additional error when you have a oauth enable.

Yes I'm sure this is a bug and no feature request or a general question.

I would be more than happy to open a PR to fix the grammatical errors, but i didn't find the file with French translations.

```diff
- ou connectez vou en utilisant 
+ ou connectez vous en utilisant
```

```diff
- Vous avez déjà été inscrit avec votre adresse email si vous être entrés en contact avec notre équipe du support.
- Vous pouvez demandé votre mot de passe ici. 
+ Vous avez déjà été inscrit avec votre adresse email si vous êtes entrés en contact avec notre équipe du support.
+ Vous pouvez demander votre mot de passe ici. 
```

**Comment by MrGeneration** [comment]
This is technically not a bug, please use the internal translation function.
If you have questions, ,please consult the community.
