### ISSUE TITLE
script/scheduler.rb crashes after recreation of Zammad database

### ISSUE THREAD

**Issue by ntinti** [zammad/zammad#374]
sudo -u zammad script/scheduler.rb start (or run)
ends scheduler.rb in a view seconds without any response

however "sudo -u zammad script/websocket-server.rb start" works fine

**Comment by monotek** [comment]
Which OS?
How did you have installed Zammad?

**Comment by ntinti** [comment]
scheduler stops also working after a longer time (less then one hour, more then five minutes) when started as user zammad from shell.
I've installed zammad from source tgz file and updated it with git on FreeBSD 10.3-STABLE

**Comment by martini** [comment]
@ntinti it the scheduler stops, what is the content of log/scheduler_err.log and log/scheduler_out.log ?

**Comment by ntinti** [comment]
`/usr/local/zammad/lib/sessions.rb:638:in `rescue in thread_client': STOP thread_client for client 17305584240 after 10 tries (RuntimeError)
        from /usr/local/zammad/lib/sessions.rb:613:in `thread_client'
        from /usr/local/zammad/lib/sessions.rb:636:in `rescue in thread_client'
        from /usr/local/zammad/lib/sessions.rb:613:in `thread_client'
        from /usr/local/zammad/lib/sessions.rb:636:in `rescue in thread_client'
        from /usr/local/zammad/lib/sessions.rb:613:in `thread_client'
        from /usr/local/zammad/lib/sessions.rb:636:in `rescue in thread_client'
        from /usr/local/zammad/lib/sessions.rb:613:in `thread_client'
        from /usr/local/zammad/lib/sessions.rb:636:in `rescue in thread_client'
        from /usr/local/zammad/lib/sessions.rb:613:in `thread_client'
        from /usr/local/zammad/lib/sessions.rb:636:in `rescue in thread_client'
        from /usr/local/zammad/lib/sessions.rb:613:in `thread_client'
        from /usr/local/zammad/lib/sessions.rb:636:in `rescue in thread_client'
        from /usr/local/zammad/lib/sessions.rb:613:in `thread_client'
        from /usr/local/zammad/lib/sessions.rb:636:in `rescue in thread_client'
        from /usr/local/zammad/lib/sessions.rb:613:in `thread_client'
        from /usr/local/zammad/lib/sessions.rb:636:in `rescue in thread_client'
        from /usr/local/zammad/lib/sessions.rb:613:in `thread_client'
        from /usr/local/zammad/lib/sessions.rb:636:in `rescue in thread_client'
        from /usr/local/zammad/lib/sessions.rb:613:in `thread_client'
        from /usr/local/zammad/lib/sessions.rb:570:in `block (3 levels) in jobs'`

**Comment by ntinti** [comment]
OK. After inserting dummy overviews direct in the table overviews with id numbers that are filling the sequence unto my last id number, the scheduler works without going down. 

Previously after 10 attempts not finding ids it crashes:

**after 10 tries**
`scheduler error: STOP thread_client for client 17305584240 after 10 tries (RuntimeError)`

**10 queries with errors e.g.**
`E, [2016-11-07T20:50:16.271426 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>`

**Comment by martini** [comment]
Thanks for feedback. I' tried to reproduce it, but I missed something.

I did:
1) Create a overview "aaa" for role "Agent"
2) I see the new overview "aaa" in Overviews
3) I deleted this overview "aaa" -> it was removed from Overviews (also in admin interface)

-> Scheduler is still working. What did I miss?

**Comment by ntinti** [comment]
Don't know - I've holes in the sequence of my overview-ids (10,13,14 are missing), because I've deleted overviews. Only if the sequence is intact the scheduler works. If ids are missing the scheduler goes down **after 10 errors** finding missing overview ids. 

production.log:
`D, [2016-11-07T20:50:16.271274 #70350] DEBUG -- :   ^[[1m^[[35mOverview Load (0.1ms)^[[0m  SELECT  `overviews`.* FROM `overviews` WHERE `overviews`.`id` = 13 LIMIT 1
E, [2016-11-07T20:50:16.271426 #70350] ERROR -- : thread_client 17304414580 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=13>
E, [2016-11-07T20:50:16.271583 #70350] ERROR -- : /usr/local/lib/ruby/gems/2.3/gems/activerecord-4.2.7.1/lib/active_record/core.rb:155:in `find'
  /usr/local/zammad/app/models/application_model.rb:1436:in `block in assets_of_object_list'
  /usr/local/zammad/app/models/application_model.rb:1434:in `each'`

scheduler:err:
`/usr/local/zammad/lib/sessions.rb:638:inrescue in thread_client': STOP thread_client for client 17305584240 after 10 tries (RuntimeError)`

**Comment by ntinti** [comment]
What I also don't understand are the huge numbers of queries on a table that is empty:
"overviews_users" has no content, but there are a lot of queries on it, e.g.
` SELECT `users`.id FROM `users` INNER JOIN `overviews_users` ON `users`.`id` = `overviews_users`.`user_id` WHERE `overviews_users`.`overview_id` = 14`

**Comment by ntinti** [comment]
Testing it by deleting my "dummy" overviews. ID 10,12,13,14, are missing again. Have ID 1-9,11,15 Scheduler stops working.

**Comment by martini** [comment]
Can you describe what attributes you set for "dummy" overview?

**Comment by ntinti** [comment]
I've cloned an existing table row (with php mysql tool "adminer") and give it another name and id

**Comment by ntinti** [comment]
I've deleted all my self created overviews now. Only original overviews with id number 1-8 are present. But scheduler is searching for not any more existing ids and crashes again :-(

scheduler.err
`/usr/local/zammad/lib/sessions.rb:638:in `rescue in thread_client': STOP thread_client for client 17316287560 after 10 tries (RuntimeError)`

production.log - searching for id 11
`D, [2016-11-07T22:51:20.067309 #75488] DEBUG -- :   ^[[1m^[[36mOverview Load (0.1ms)^[[0m  ^[[1mSELECT  `overviews`.* FROM `overviews` WHERE `overviews`.`id` = 11 LIMIT 1^[[0m
E, [2016-11-07T22:51:20.067480 #75488] ERROR -- : thread_client 17316287560 exited with error #<ActiveRecord::RecordNotFound: Couldn't find Overview with 'id'=11>
E, [2016-11-07T22:51:20.067636 #75488] ERROR -- : /usr/local/lib/ruby/gems/2.3/gems/activerecord-4.2.7.1/lib/active_record/core.rb:155:in `find'
  /usr/local/zammad/app/models/application_model.rb:1436:in `block in assets_of_object_list'
  /usr/local/zammad/app/models/application_model.rb:1434:in `each'
  /usr/local/zammad/app/models/application_model.rb:1434:in `assets_of_object_list'
`

**Comment by ntinti** [comment]
Ich hab keine Lust mehr - gute Nacht

**Comment by martini** [comment]
@ntinti can I get remote login to your instance? I can't follow the questions/what's happen.

**Comment by ntinti** [comment]
What can't of login do you want?

**Comment by ntinti** [comment]
I'm tired can't = kind

**Comment by ntinti** [comment]
teamviewer on my mac ?

**Comment by martini** [comment]
teamviewer  or ssh would be fine (of course tomorrow is fine too)

**Comment by martini** [comment]
just wrote to support@zammad.com tomorrow - have a good night!

**Comment by ntinti** [comment]
It's OK to make it now. I send now a mail with my teamviewer ID

**Comment by ntinti** [comment]
Ok - it's to late  - see you tomorrow. We have to fix a time then.

**Comment by martini** [comment]
Many thanks to @ntinti for remote login.

@ntinti dropped and recreated the Zammad database. Unfortunately Zammad did not delete the caches. The result was wrong database records in the new Zammad database.

We fixed it by using the following commands:

rails r 'OnlineNotification.destroy_all' 
rails r 'ActivityStream.destroy_all' 
rails r 'RecentView.destroy_all' 
rails r 'History.destroy_all' 

After that the scheduler seems to work fine.

Als permanent solution, we improved the Zammad setup routine to delete all caches (if exists) at first db migration and loading db seeds, see https://git.znuny.com/zammad/zammad/commit/8f96496a47d129f994d5874c9cf31287d99f2900.

**Comment by visdim** [comment]
I need to execute the command
rails r 'OnlineNotification.destroy_all'
rails r 'ActivityStream.destroy_all'
rails r 'RecentView.destroy_all'
rails r 'History.destroy_all'

several times per day. very often the issue cannot login with user id 1
after delete cache it works, but after some time I get the message that the session has been renewed. an error message something like session has been renewed because maybe a user session confilct possible...
sorry, don't know exact phrase...
