### ISSUE TITLE
Incorrect alignment in the listing of attachments when creating a ticket

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3746]
## Infos:

* Used Zammad version: develop (2021-09-20)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Nice alignment in the listing of attachments when creating a ticket

### Actual behavior:

![image](https://user-images.githubusercontent.com/110226/134007576-5814961f-a6a7-487d-ae46-c8a097639976.png)

### Steps to reproduce the behavior:

* got to ticket create screen 
* upload one attachment

Note: It's working fine in ticket zoom.

**Comment by martini** [comment]
I did not verify how it was before, but in ticket create the space between uploaded attachments and "select attachments" looks big:

![image](https://user-images.githubusercontent.com/110226/134529007-b58f522f-cc7a-4763-827e-b7cfc422464b.png)


In ticket zoom the space between uploaded attachments and "select attachments" looks different/better:

![image](https://user-images.githubusercontent.com/110226/134529058-95318dec-3d98-4836-b9b2-6aeb07ffcf91.png)

Should I create a new issue for that?

**Comment by thorsteneckel** [comment]
Yes, please. Would be great to say which one should be used.

That's how it looked back in 3.6:
<img width="1058" alt="CleanShot 2021-09-23 at 16 58 40@2x" src="https://user-images.githubusercontent.com/3873515/134531919-f5ed654e-0a21-43c0-823a-7b99472e1de3.png">

<img width="1064" alt="CleanShot 2021-09-23 at 16 59 56@2x" src="https://user-images.githubusercontent.com/3873515/134532000-048ab263-bfbb-4d12-8764-aa524ca93428.png">
