### ISSUE TITLE
Note should be listed with the attributes of the organization at the end. "Domain based assignment *" should be listed after "Domain".

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3749]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Note should be listed with the attributes of the organization at the end. "Domain based assignment *" should be listed after "Domain".

### Actual behavior:

![Untitled](https://user-images.githubusercontent.com/110226/134012500-0a5e9cc2-d66f-4a35-bf71-2c0475e52391.png)

### Steps to reproduce the behavior:

* Just install Zammad and open organization modal (e. g. new organization).

**Comment by MrGeneration** [comment]
Where do you have that screen from?

Works on my test instances without any issues:
![image](https://user-images.githubusercontent.com/6549061/134012888-cc8db8e6-4d2f-4cd5-954b-c2b47eb9c2c8.png)

![image](https://user-images.githubusercontent.com/6549061/134012925-c1c6a7e0-7914-4099-9c45-30f92277ff6e.png)


verified on Google Chrome.

**Comment by martini** [comment]
I too the screenshot from a fresh instance from zammad.com (I can reproduce it with any new instance here). I upgraded to Zammad 5.0 then it worked well:

![image](https://user-images.githubusercontent.com/110226/134014817-bc3feae9-49bc-4d18-be28-006e2b5a8b92.png)

So I'm closing for now.
