### ISSUE TITLE
Improve wording if user uses unallowed characters

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3750]
### Infos:

* Used Zammad version: 5.0/develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Zammad provides meaningful and clear error messages.

### Actual behavior:

If you try to use invalid characters within object creation the error message feels mixed from two independent ones.

![image](https://user-images.githubusercontent.com/6549061/134015283-78f42eb7-7cb4-4fbe-94a2-a95a874cf3a9.png)

### Steps to reproduce the behavior:

* try to use special characters in attribute names

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
@MrGeneration Message was improved with the source string update from @mgruner: https://github.com/zammad/zammad/commit/4186b0faaf60a06d09d4f89e248915c3f63053f5#diff-55553ac28af9c773657544a500fe369e016948d48f643be15a01b4596c9efec9R823

Maybe you can check if this is ok from your side?

**Comment by MrGeneration** [comment]
Works perfectly fine for me :) Thanks!
