### ISSUE TITLE
Allow more custom email headers to filter mails

### ISSUE THREAD

**Issue by dnauck** [zammad/zammad#376]
I want to filter out spam mails by X-DSPAM-*, X-Spam-Level, etc.

Just allow the user to add custom headers to the email filter.

**Comment by eliasp** [comment]
Another usecase here:

Every now and then we're sending out user surveys via MailChimp and have them send a response to our support address.
In those cases, I don't want users to receive the usual "Thanks for your inquiry" notification as it wasn't the user which initiated the discussion, so I'd like to have a negative filter for the presence of the `In-reply-to` header.

**Comment by mweinelt** [comment]
Except rspamd (https://www.rspamd.com) sets the `X-Spam` which is not covered by these choices.

**Comment by martini** [comment]
Update, just added the following

- X-Spam
- In-reply-to
- X-DSPAM-Result
- X-DSPAM-Confidence
- X-DSPAM-Probability
- X-DSPAM-Signature

@dnauck to make if configurable it would be nice. But takes some time. In case if there is more need, also from other users. Just reopen or even better, create a new issue. Thanks!

**Comment by martini** [comment]
https://github.com/zammad/zammad/commit/52ab76d7a740f2fb7e5c7fd9b82cc4b8323ab178
