### ISSUE TITLE
Default time diff for date and datetime objects don't function

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3763]
### Infos:

* Used Zammad version: 4.1/stable, 5.0/develop as of 21st September
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on Google Chrome v93.0.4577.82, Firefox v92.0

### Expected behavior:

* I'm not entirely sure if this function should pre select `Time.now + n.hours` / `Time.now + n.days` when using the date picker or if the field should be pre filled with a date.
* option wording is correct (hours means hours and minutes means minutes)

### Actual behavior:

* Neither the date / datetime gets pre filled nor pre selects a future moment in the date picker.
  This appeared during my documentation rework of the object section and currently is a unknown function. :D
* According to this code Zammad uses wrong timings, at least in field descriptions which should be fixed.
  https://github.com/zammad/zammad/blob/0668e17d1878c64f223aaa98a9a176a6c5004f70/app/models/object_manager/attribute/set_defaults.rb#L23-L32
  
  ![image](https://user-images.githubusercontent.com/6549061/134348491-89685ee0-b958-4a27-b8ef-aa6787778373.png)
  ![image](https://user-images.githubusercontent.com/6549061/134348587-4b021dde-5eaa-4d8a-943b-be83fc8d0e20.png)

### Steps to reproduce the behavior:

* have a look at object creation for datetime and date, create these objects
* see what it does (or not) in e.g. ticket dialogues

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
After asking Martin I learned that this function is supposed to support the user by pre selecting above selected time diff in the date / timepickers. It is not supposed to hard pre set the field.

**Comment by nuokh** [comment]
selecting a default time diff seems to do nothing in our test vm. We want to enable users to communicate a preference for IT-Service appointments and somehow communicate that these should be at least two days in advance.

We tried using a datetime object with two days (=2880 minutes) default time diff:
![grafik](https://user-images.githubusercontent.com/9081831/150986176-7a99fd39-c49e-4e4f-a265-b0b5364eef2c.png)

The result shows no change at all:
![grafik](https://user-images.githubusercontent.com/9081831/150986313-63dd4577-e6b3-4dd2-9791-7c9aa7f60146.png)

Then we trief the same with the date object and two days default time diff:
![grafik](https://user-images.githubusercontent.com/9081831/150986513-dfe4a308-2d23-4cbb-ab37-3290d387c52b.png)

Which did not change anything related to the calender object in ticket creation, too:
![grafik](https://user-images.githubusercontent.com/9081831/150986625-eb455346-7d7c-4faf-8b20-b14c5d980e75.png)

I'm a little bit confused what exactly the default time diff is doing to support the user. Ideally we would love to see the time diff feature getting more options like

- make the next x days/hours "un-selectable" for users (enforced)
- make the next x days/hours selectable, but visually communicate that it's discouraged to request service within x days/hours to manage expectations

Just to give some context. For now we hoped that the time diff "supporting the user" somehow could at least get us somewhat there but as of right now it seems like it has no effect at all.

**Comment by MrGeneration** [comment]
Sorry @nuokh but please put your feature enhancement requests into the community:
https://community.zammad.org

This is a bug report for existing functionality and not the right place to discuss feature improvements or additions.
I'm limiting the conversation to contributors only as we've only pointed out obvious again which is not helping the situation.
