### ISSUE TITLE
Usage of inactive object attributes in SLAs will crash admin SLA interface

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3769]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all
* Ticket#1093261

### Expected behavior:

* Disabled attributes should not crash the UI.

### Actual behavior:

![grafik](https://user-images.githubusercontent.com/5445062/134889488-bb7ccf39-0dc0-4b6b-b95f-ddd2fcae2b41.png)

```
Uncaught TypeError: t is undefined
    humanTextLookup https://rolf.zammad.com/assets/application-1da65f1e538b1e17178fbef3d4f78fe4507ca2c454168426cfba5974ae477b79.js:41
    humanText https://rolf.zammad.com/assets/application-1da65f1e538b1e17178fbef3d4f78fe4507ca2c454168426cfba5974ae477b79.js:41
    render https://rolf.zammad.com/assets/application-1da65f1e538b1e17178fbef3d4f78fe4507ca2c454168426cfba5974ae477b79.js:49
```

### Steps to reproduce the behavior:

* Create a new attribute of type text
* Create new SLA which is using this text attribute
* Go back and disable the attribute
* Try to open the SLA admin view

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
@martini @thorsteneckel What do you think could be the approach to solve the issue? We could throw an error then the field is configured somewhere else in the admin interface or we could try to remove the field out of the configurations when it is still configured? What do you think?

**Comment by thorsteneckel** [comment]
@rolfschmidt there is already a callback in place that [prevents deactivating ObjectManager Attributes if they are referenced](https://github.com/zammad/zammad/blob/98065e1df89b2776e2c9ee8a023ee952b49c8ae5/app/models/object_manager/attribute.rb#L861-L869). This should be extended.

**Comment by mantas** [comment]
Looks like I added that original check.. Will extend it.
