### ISSUE TITLE
Reply to merged ticket gets appended to the wrong ticket

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#377]
Here is an example:

https://linuxhotel.zammad.com/#ticket/zoom/791

**Comment by raphaelm** [comment]
Can reproduce this, it's very annoying.

**Comment by rolfschmidt** [comment]
Hi,
thank you very much for your report! I added a filter to prevent this behaviour. Shouldnt happen in the future. Changes are already available in the develop branch.

-Rolf
