### ISSUE TITLE
Existing tickets: New article modal with padding-left: 0; padding-right: 0;

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3772]
### Infos:

* Used Zammad version: 5.9/develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified von Google Chrome v94.0.4606.61

Looks like a regression ( https://github.com/zammad/zammad/commit/39179c83f8492cea770177bef345c792f0522c94#diff-262b304b68922aa1fcef0b854fc2cd83e4d487210ae772ae1bcba7be8e85bcdaR7020-R7021 ) introduced by #3746 fix.

### Expected behavior:

Text fields come with reasonable paddings to lighten up the UI.

### Actual behavior:

New article fields in ticket zooms reset the padding on left and right to 0.
New ticket dialogues are not affected.

![image](https://user-images.githubusercontent.com/6549061/135042026-7845ead7-b695-4d60-9972-137a79cb2a0d.png)

![image](https://user-images.githubusercontent.com/6549061/135042052-c3c92e92-7191-4f22-9705-a2c8fbe298cd.png)

### Steps to reproduce the behavior:

* open any ticket and create a new article

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Thanks. I have the same. IMO got introduced by https://github.com/zammad/zammad/commit/39179c83f8492cea770177bef345c792f0522c94
