### ISSUE TITLE
Example payload in webhook view leads to 500 error

### ISSUE THREAD

**Issue by saz** [zammad/zammad#3794]
### Infos:

* Used Zammad version: 5.1.0
* Installation method (source, package, ..): docker
* Operating system: -
* Database + version: -
* Elasticsearch version: -
* Browser + version: Firefox 93

### Expected behavior:

* Example webhook payload is shown

### Actual behavior:

* The following error is shown: `{"error":"undefined method `access_condition' for #\u003cClass:0x0000556af3545e58\u003e"}`

### Steps to reproduce the behavior:

* Go to http://localhost/#manage/webhook and click on "Example Payload".

This is happening on a fresh install, right after starting the container using the command
`docker container run -ti --rm --name zammad -p 80:80 zammad/zammad`
I can see the same behavior on 5.0.x installed from source

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Regression of https://github.com/zammad/zammad/commit/276c45b2e9a65009dcbd598827bfab420adf848c

https://github.com/zammad/zammad/blob/5df98684da64aed93cc29e4be029d81566520906/app/controllers/webhooks_controller.rb#L7
