### ISSUE TITLE
Chat preview isn't working due to CORS policy

### ISSUE THREAD

**Issue by saz** [zammad/zammad#3795]
### Infos:

* Used Zammad version: 5.1.x, 5.0.x
* Installation method (source, package, ..): docker, source
* Operating system: -, Ubuntu 18.04
* Database + version: -, Postgresql 9.6
* Elasticsearch version: -, 7.15.0
* Browser + version: Google Chrome 94, Firefox 93

### Expected behavior:

* Chat preview is working

### Actual behavior:

* Chat preview is broken due to missing Access-Control-Allow-Origin header.
It's trying to request https://images.zammad.com/api/v1/webpage/combined?url=http%3A%2F%2Fwww.example.com&count=20 which fails due to CORS policy

### Steps to reproduce the behavior:

* Go to Settings => Chat

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I'm not sure how to handle that so I'm leaving the choice to developers.
Above issue depends on the remote server configuration. If you e.g. try zammad.com it's working (no matter of the installation type) - however, using personal domains it does not.
![image](https://user-images.githubusercontent.com/6549061/136423020-35fba520-f007-453b-9cdd-594e1a9b8d25.png)

**Comment by MrGeneration** [comment]
Correction, issue seems to be `images.zammad.com` and thus is no application related issue directly.

**Comment by kale1d0code** [comment]
Does this require CORS headers to be set on the website being previewed or is this an issue with images.zammad.com

**Comment by saz** [comment]
@kale1d0code CORS headers need to be set on images.zammad.com

**Comment by dominikklein** [comment]
Seems to be working fine now.
