### ISSUE TITLE
Extend macros to modify users

### ISSUE THREAD

**Issue by dnauck** [zammad/zammad#380]
Hello,

the `Close & Tag as Spam` macro is a nice default helper. I want to extend it to also disable/delete the user. But currently user modifications are not possible.

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes

**Comment by dnauck** [comment]
@hanneshal Please don't close this issue. There is no way to clean up the system from spam.
