### ISSUE TITLE
Job scheduling respects time zone

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#3802]
### Infos:

* Used Zammad version: 5.0/develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1094310

### Expected behavior:

* `Job` next run is calculated according to system time zone

### Actual behavior:

* `Job` next run is calculated in UTC

### Steps to reproduce the behavior:

* Add a scheduler job with a timeplan
* Look at next run date

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Can you please calrify: System timezone or admins timezone?

**Comment by mantas** [comment]
Does `Zammad timezone` work to define the `Setting.get('timezone_default')`?

System timezone may sound similar to OS timezone while admin timezone may sound similar to user web browser timezone

**Comment by MrGeneration** [comment]
> Does Zammad timezone work to define the Setting.get('timezone_default')?

Dunno?

> System timezone may sound similar to OS timezone while admin timezone may sound similar to user web browser timezone

I know of no situation where "Zammads timezone" has any effect. Or I just never found any places this happens. 
Up to now all things happening in the Zammad UI (e.g. scheduling pending reminders etc) happens respecting the admin / agents timezone. Zammad usually runs in UTC context which is why the timezone of the agent may be relevant if you wanna select YOUR midnight not UTCs :)

**Comment by mantas** [comment]
> Zammad usually runs in UTC context

`timezone_default` is used in various places where there's no single agent to base time zone on. For example out-of-office replacement. Or when including time in notification emails. Or in this case :)

Admin is free to choose UTC or whatever timezone suits him.

**Comment by martini** [comment]
Is there a reason why this is not fixed in 5.0?

**Comment by mantas** [comment]
It may break an existing installation if there's an offset being used to compensate for this. Thus it shouldn't be auto-installed as a patch-level upgrade.

**Comment by martini** [comment]
@mantas thanks for feedback. So we do need to add a notice to the release note? If yes, what is your proposal?
