### ISSUE TITLE
Unable to bulk tag and close tickets from overview

### ISSUE THREAD

**Issue by manc74** [zammad/zammad#3805]
### Infos:

* Used Zammad version: 5.0.1
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 18.04.6
* Database + version: psql (PostgreSQL) 10.18
* Elasticsearch version: 7.15.0
* Browser + version: Chrome 94.0.4606.54 (also on various others)

### Expected behavior:

*Bulk close the tickets and tag them (e.g. apply a "spam" tag to a ticket and close them).

### Actual behavior:

*Tickets don't close but do get tagged.

### Steps to reproduce the behavior:

*Select one or more tickets and drag and drop to "close and tag as xxx" to close the ticket(s) and tag them

Yes I'm sure this is a bug and no feature request or a general question.

### Production log extract from when the transaction occurs:

```
I, [2021-10-12T09:13:04.949413 #235658-435580]  INFO -- : Started POST "/api/v1/tags/add" for xx.xx.xx.xx at 2021-10-12 09:13:04 +0100
I, [2021-10-12T09:13:04.952158 #235658-407940]  INFO -- : Started PUT "/api/v1/tickets/152349" for xx.xx.xx.xx at 2021-10-12 09:13:04 +0100
I, [2021-10-12T09:13:04.956627 #235658-435580]  INFO -- : Processing by TagsController#add as JSON
I, [2021-10-12T09:13:04.957235 #235658-435580]  INFO -- :   Parameters: {"object"=>"Ticket", "o_id"=>152349, "item"=>"spam"}
I, [2021-10-12T09:13:04.961433 #235658-407940]  INFO -- : Processing by TicketsController#update as JSON
I, [2021-10-12T09:13:04.961581 #235658-407940]  INFO -- :   Parameters: {"number"=>"10152345", "title"=>"ticketsubjectredacted", "group_id"=>"12", "owner_id"=>3, "customer_id"=>254, "state_id"=>"4", "priority_id"=>5, "article"=>{}, "updated_at"=>"2021-10-12T07:31:27.785Z", "preferences"=>{"channel_id"=>7, "escalation_calculation"=>{"last_update_at"=>"2021-10-11T17:59:31.733Z", "last_contact_at"=>"2021-10-11T17:59:31.733Z", "sla_id"=>6, "sla_updated_at"=>"2020-05-19T14:17:58.436Z", "calendar_id"=>1, "calendar_updated_at"=>"2021-10-11T21:05:53.849Z", "escalation_disabled"=>false}}, "pending_time"=>nil, "id"=>"152349"}
I, [2021-10-12T09:13:04.990289 #235658-435580]  INFO -- : Completed 201 Created in 33ms (Views: 0.2ms | ActiveRecord: 14.2ms | Allocations: 16262)
E, [2021-10-12T09:13:05.157585 #235658-407940] ERROR -- : Invalid value '3' for field 'owner_id'! (Exceptions::UnprocessableEntity)
app/models/concerns/checks_core_workflow.rb:38:in `block in check_restrict_values'
app/models/concerns/checks_core_workflow.rb:33:in `each_key'
app/models/concerns/checks_core_workflow.rb:33:in `check_restrict_values'
app/models/concerns/checks_core_workflow.rb:27:in `validate_workflows'
app/controllers/tickets_controller.rb:249:in `block in update'
app/controllers/tickets_controller.rb:248:in `update'
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
I, [2021-10-12T09:13:05.159096 #235658-407940]  INFO -- : Completed 422 Unprocessable Entity in 197ms (Views: 0.2ms | ActiveRecord: 30.0ms | Allocations: 100640)

```

the entry:

```Invalid value '3' for field 'owner_id'! ```

is always the agent that has attempted the transaction (eg myself).

This issue has only started since updating to V5.0 then still occurs after updating to v5.0.1

**Comment by MrGeneration** [comment]
Please provide the group name and permission set for said group for the affected agent.

**Comment by manc74** [comment]
There are 13 groups in use - the issue occurs on all groups apart from one (labelled "Ops") - which incidentally but probably be unrelated is the one that's showing on the top of the overview list due to the current overview ordering bug issue #3800.

The one I tried in the production log above is the "Enquiries" group.

The users its affecting have "admin" rights (full access to everything, including the "full" column in all groups) and also "manager" roles (again has "full" access to all relevant groups in roles permissions).

**Comment by MrGeneration** [comment]
And you did ensure to follow the update path?
Because I'm unable to reproduce your issue just like for community users on an existing thread.
https://docs.zammad.org/en/latest/install/update.html

From which version did you upgrade?
Any workflows configured if so what's the configurations?

**Comment by manc74** [comment]
I used apt upgrade to carry out the initial upgrade, then I was unable to log in, found the thread on the forum and after running:

```zammad run railsr "Cache.clear"```

and:

```apt-get install --reinstall zammad```

It started to work again.

No workflows configured yet.

**Comment by MrGeneration** [comment]
So what configuration does the affected makro have?
User-ID 3 has access to the group in question?

**Comment by manc74** [comment]
The macro is:

![a0f34cca97dedeb6382316f96c81d618](https://user-images.githubusercontent.com/68019920/136985303-10405939-81ff-445f-b50b-9e3434853787.png)
`
User ID 3 is mine and has access to everything. It also happens to another "admin" account and other users who also have access to the original group and also the "spam" group the ticket gets moved it.

**Comment by KINGRULZ** [comment]
if it helps in Chrome inspect console this is the error we get 

![image](https://user-images.githubusercontent.com/44599757/137018489-6af1135e-7cc1-45e2-9f16-5014f9c6638b.png)

**Comment by KINGRULZ** [comment]
also thsis fixes it untill Zammad is updated by source 

sudo systemctl stop zammad
sudo systemctl stop zammad-worker

sudo mv ./opt/zammad /opt/zammad.bak
sudo apt-get install --reinstall zammad

once reinstalled

sudo systemctl stop zammad
sudo systemctl stop zammad-worker

sudo mv /opt/zammad/storage/fs /opt/zammad/storage/fs.bak
sudo cp -R /opt/zammad.bak/storage/fs /opt/zammad/storage

sudo chown -R zammad:zammad /opt/zammad/storage/fs
sudo chmod 755 -R /opt/zammad/storage/fs

sudo systemctl restart zammad
sudo systemctl restart zammad-worker

and then check everything is working and no data loss and if happy you can remove
/opt/zammad.bak to regain disk and also the /opt/zammad/storage/fs.bak

**Comment by MrGeneration** [comment]
@KINGRULZ nonono mate. 
Your descriptions 100% sounds like other issues as it's magically coming back after the next update.

I'm highly doubting.

**Comment by KINGRULZ** [comment]
> @KINGRULZ nonono mate. Your descriptions 100% sounds like other issues as it's magically coming back after the next update.
> 
> I'm highly doubting.

im happy to retest this as i have only done it once so maybe it was coincident will update my findings

**Comment by MrGeneration** [comment]
Sorry I still cannot reproduce this.
I even set up a new group and configured the macro the exact same way you provided.

Ensure your migrations are clean and caching is not an issue.

**Comment by Vincenzo974** [comment]
Hi.

Got the pb in 5.0.3. I've upgrade from 2.5.0 where it wasn't happening. We have group "hotline" and "other". My user is part of other but not hotline and i'm admin of the app (admin role). Hotline is the default group when creating tickets. If i try to close n tag as spam tickets of hotline group, zammad try to use my ID in group hotline where i'm not present (i think it _select user_id from group_users where group_id="hotlineID" and user_id="myID"_ and it returns null cause owner_id isn't nullable) . then it fails with the message posted.

Strangely it wasn't a pb in previous version and i don't know if when i've just upgraded (no upgrade error) in v5 if this macro was bugging. i'm experiencing it just a month or 2 after upgrade.

If Zammad check if u r within the actual group when u close as spam now, is there any chance to create a condition for group like for user (i mean "actual user" condition) with "actual user group"? Only condition for group available in macro is to choose a specific group. it should fix the pb if u don't want to be in all group.

Strangely as admin i'm not necessarly in all group but i can do lots of action and this check isn't accurate in that case i think.

Best regards.

**Comment by MrGeneration** [comment]
@Vincenzo974 please don't hijack closed issues with your technical questions.
Please consult the Community if you can't wrap your head around the reasons for the behavior you're seeing.

https://community.zammad.org
