### ISSUE TITLE
Not possible to disable "spam" users

### ISSUE THREAD

**Issue by dnauck** [zammad/zammad#381]
Hello,

when a spam ticket arrived also a new user/customer is created. Those "spam" users normally don't have all required fields pre filled (e.g. firstname, lastname,etc.) so its not possible to use the "modify" form to disable/delete those without adding fake data to the required fields.

This is also related to #380

**Comment by martini** [comment]
Hi @dnauck 

it's not clear to me. You mean you can't close the ticket without filling firstname, lastname of new created customer?

 -Martin

**Comment by dnauck** [comment]
Hi @martini,

i mean you cannot disable/delete the user/customer via the "modify user form".

Current workflow is: open the new ticket -> notice it is spam -> execute the `Close & Tag as Spam` macro -> goto settings/users -> modify spam user to disable/delete it -> notice you can save because of missing fields -> add some fake data to required fields -> save/disable/delete the user

**Comment by martini** [comment]
Now I got it.

We have prepared a maintenance job (house keeping job), which is deleting all users without references in Zammad.

a) For example, you mark ticket spam
b) You delete the spam tickets, e. g. in 2 weeks
c) The maintenance job, will run later an also delete the user without relations (here this created spam user)

 -=> Sounds this good to you?

**Comment by dnauck** [comment]
That is very nice (currently the delete as "spam" marked tickets does not exist in 1.0.0, right?)

**Comment by martini** [comment]
yes, you are right, currently you can not delete tickets https://github.com/zammad/zammad/issues/214 and can not search for "tags" https://github.com/zammad/zammad/issues/378

**Comment by jacotec** [comment]
@martini Any schedule/milestone for that maintenance job / ability to run this in "Automation"?

The spam user customers are piling a bit here ... ;-)

**Comment by dnauck** [comment]
@martini any news on the "maintenance job (house keeping job)"?

**Comment by dnauck** [comment]
*ping* to prevent auto close

**Comment by hamzehmohammadnia** [comment]
Is there any update regarding deleting user/customers that created automatically after sending email/ticket?

**Comment by dominikklein** [comment]
It should already be possible with the data privacy feature to delete users.
