### ISSUE TITLE
Custom date and datetime attributes are filled with dates on creation of tickets/users after update from 4.1 to 5.x

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#3810]
### Infos:

* Used Zammad version: 4.1/5.0.1
* Installation method (source, package, ..): package
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket#1093873, Ticket#1094368, Ticket#1094600, Ticket#1094735

### Expected behavior:

* Date and datetime fields should be empty on ticket/user creation. 

### Actual behavior:

* After an update from 4.1 to 5.x, previously (in 4.1) created date and datetime fields are filled with a fixed date, or the current date plus 24 hours. 

### Steps to reproduce the behavior:

* Create some custom attributes of the type date/datetime in Zammad 4.1
* Update to 5.x
* Create a new ticket or user (depending on where you created the attribute). Creation method is not relevant (API, email or manually from the UI) 
* Find your custom date/datetime fields to be filled with a date on newly created objects. 

 
![image](https://user-images.githubusercontent.com/69846837/137343860-01cdde3c-7a0f-48c8-9e4d-c6e3dba76665.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
How do those custom attributes look like? Is `DEFAULT TIME DIFF` present?

**Comment by martini** [comment]
> How do those custom attributes look like? Is DEFAULT TIME DIFF present?

Do you mean `data_option[:diff]`? Yes it is. It's available on any date field because its the default value in the UI.

```
oot@just-testing:~# zammad run rails r 'pp ObjectManager::Attribute.find(50)'
#<ObjectManager::Attribute:0x000055a075bdb030
 id: 50,
 object_lookup_id: 2,
 name: "epoch",
 display: "Epoch",
 data_type: "date",
 data_option:
  {"diff"=>24, "default"=>nil, "null"=>true, "options"=>{}, "relation"=>""},
 data_option_new: {},
 editable: true,
 active: true,
 screens:
  {"create_middle"=>
    {"ticket.customer"=>
      {"shown"=>true, "required"=>false, "item_class"=>"column"},
     "ticket.agent"=>
      {"shown"=>true, "required"=>false, "item_class"=>"column"}},
   "edit"=>
    {"ticket.customer"=>{"shown"=>true, "required"=>false},
     "ticket.agent"=>{"shown"=>true, "required"=>false}}},
 to_create: false,
 to_migrate: false,
 to_delete: false,
 to_config: false,
 position: 1550,
 created_by_id: 3,
 updated_by_id: 3,
 created_at: Thu, 14 Oct 2021 13:58:36 UTC +00:00,
 updated_at: Thu, 14 Oct 2021 13:58:37 UTC +00:00>
root@just-testing:~# 
```

**Comment by rolfschmidt** [comment]
**Workaround** is to disable the defaults while this issue is WIP:

```diff
diff --git a/app/models/object_manager/attribute/set_defaults.rb b/app/models/object_manager/attribute/set_defaults.rb
index e8fb41a78..9c3e8a8a8 100644
--- a/app/models/object_manager/attribute/set_defaults.rb
+++ b/app/models/object_manager/attribute/set_defaults.rb
@@ -5,6 +5,7 @@ class ObjectManager
     class SetDefaults
       def after_initialize(record)
         return if !record.new_record?
+        return

         attributes_for(record).each { |attr, config| set_value(record, attr, config) }
       end
```

This code will disable the setting of the defaults and behave more like zammad 4.1 then (regression of #1653).

(Don't forget to restart your services after changing the file)
