### ISSUE TITLE
When looking for customers, it is no longer possible to change into organizations

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3815]
### Infos:

* Used Zammad version: 5.0 
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

When creating new tickets, it was previously possible to switch by custumer-search into the organization. 

### Actual behavior:

This does not work in the current Zammad version. The click no longer takes any action.

### Steps to reproduce the behavior:

* Create new ticket
* Search for organization
* Click on it

(Reproducible on our support system)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
https://community.zammad.org/t/when-looking-for-customers-it-is-no-longer-possible-to-change-into-organizations/7929

**Comment by MrGeneration** [comment]
Original finder was: @kgoldinger

**Comment by rolfschmidt** [comment]
regression of https://github.com/zammad/zammad/commit/b8aeabce9402e81c221c9622a7da399bfee7654a

The search does not return user assets for organizations with high user count anymore.

reproduceable with `FillDb.load(customers: 100, nice: 0)`
