### ISSUE TITLE
Zammad 5 mail template double signature

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3816]
### Infos:

* Used Zammad version: 5.0.2 (stable & develop)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on Google Chrome and Firefox
* Ticket: #1096409 

### Expected behavior:

Correct signature for agent/group in mail template

### Actual behavior:

I have always specified the group directly in newly created mail templates.

A signature is defined in the group.

This worked great until version 4, each agent had the correct group and signature when using a mail template.

Now, however, after the upgrade to 5.x, the signatures are loaded twice, on the one hand with the name that created the template, and on the other hand with the name of the agent.

### Steps to reproduce the behavior:

-  Create new template with predefined signature
-  Signature has #{user.firstname} #{user.lastname} in use
-  Agents now haf signature from creator and his own Template create

https://community.zammad.org/t/zammad-5-mail-template-double-signature/7866

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
How to reproduce:

1) Setup new Zammad
2) Create a signature and assign it to a group (e. g. users).
3) Go to ticket create screen, select:
  * email ticket
  * select certain group (per default group is not shown and users is already selected - hidden field)
  * add some body text
  * store template
4) Create another agent with full permissions to users
5) Login with other agent
6) Go to ticket create screen, select template (now you see the signature of agent a and agent b)
