### ISSUE TITLE
iCal connection Mac OS

### ISSUE THREAD

**Issue by ntinti** [zammad/zammad#382]
Hi

I'm trying to connect Apple calendar to Zammad, but it doesn't work:

```
ActionController::RoutingError (No route matches [PROPFIND] "/ical/tickets"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (3.6.0) lib/puma/configuration.rb:225:in `call'
  puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
  puma (3.6.0) lib/puma/server.rb:415:in `process_client'
  puma (3.6.0) lib/puma/server.rb:275:in `block in run'
  puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by thorsteneckel** [comment]
Hi @ntinti - I wasn't able to reproduce the issue with three of my test instances. Could you please provide some information on your zammad installation? Which OS do you use? Are there any other issues with you setup?

**Comment by ntinti** [comment]
"_I'm trying to connect Apple calendar to Zammad, but it doesn't work:_"
You really tried it on Apple Mac OS Sierra or OS X Capitain ?
I got authentication errors

**Comment by jannheider** [comment]
Can't reproduce this in our live and test instance.
Testet with OS X 10.10 and latest zammad version.

**Comment by thorsteneckel** [comment]
HI @ntinti - I managed to reproduce this. `[PROPFIND]` gave me a hint. We don't serve WebDAV (reading and writing entries) but only an iCal feed (reading entries). So instead of going the way "add new account" please try "add calendar subscription" like:

![bildschirmfoto 2016-11-15 um 16 41 45](https://cloud.githubusercontent.com/assets/3873515/20312390/961205fc-ab53-11e6-842f-8e0dd0a4180d.png)

Nevertheless: We should improve the documentation for this!

PS: Sorry for the german screenshot folks :)

**Comment by rkaldung** [comment]
@thorsteneckel Next time ask for the screenshot ;-) I've got always the right localization
