### ISSUE TITLE
create API Endpoint for Agent Bases time_accounting

### ISSUE THREAD

**Issue by skalec** [zammad/zammad#3820]
Hello dear developers. Can you please create an API Enpoint for evaluating time bookings for an AGENT-based evaluation.

With a simple SQL query such as

select *
from ticket_time_accountings
WHERE ticket_time_accountings.created_at
BETWEEN "2021-10-0" AND "2021-10-31"
AND created_by_id = 3

I can e.g. evaluate the times for a certain agent.

It was asked several times for such an evaluation and I can not understand why you have not yet implemented this in the API.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
