### ISSUE TITLE
Knowledgebase wrong padding for sections (tiles)

### ISSUE THREAD

**Issue by wucherpfennig** [zammad/zammad#3826]
### Infos:

* Used Zammad version: 5.0.2
* Installation method (source, package, ..): package
* Operating system: Debian 10
* Database + version:
* Elasticsearch version:
* Browser + version: All

### Expected behavior:

* Have all items aligned properly

### Actual behavior:

* Tiles are not aligned properly

### Steps to reproduce the behavior:

* See sceenshot

![grafik](https://user-images.githubusercontent.com/3634653/139321743-4410d217-840f-4eb3-81a1-c40756ecdba2.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
@mrflix could you take a look at this?

**Comment by mrflix** [comment]
It's a known bug that is in the pipeline to be fixed.

**Comment by mantas** [comment]
Is it already in github? Should mark this as a duplicate?

**Comment by mrflix** [comment]
I think there is no github issue yet but Bola has already been working on it. I have to review and merge it.

**Comment by dominikklein** [comment]
Should be already fixed: https://github.com/zammad/zammad/issues/3925
