### ISSUE TITLE
User avatars are missing if authentication is done via Google

### ISSUE THREAD

**Issue by astrugatch** [zammad/zammad#3829]
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 18.04
* Database + version: postgres (PostgreSQL) 10.18 (Ubuntu 10.18-0ubuntu0.18.04.1)
* Elasticsearch version: latest
* Browser + version: Chrome 95
* Ticket: #1095208, #10107015

### Expected behavior:

*User icons from Google auth carry over after update.

### Actual behavior:

* Instead there is a circle that just says “48 x 48”

### Steps to reproduce the behavior:

* Update from 4.1 to 5.01 with Google auth configured.

Yes I'm sure this is a bug and no feature request or a general question.

My install was an in place upgrade from 4.1 to 5.0.1, but others have confirmed the issue with other install methods. See forum link:

https://community.zammad.org/t/user-icons-missing-after-5-0-1-update/7919

**Comment by MrGeneration** [comment]
That smells like a technical question which shouldn't be causable by an update as avatar information already life in the system.
I'll keep this open temporarily but don't expect any priority on this.

**Comment by astrugatch** [comment]
In the linked community section there are two other users with the same experience, one is a clean install from a completely different process.

**Comment by astrugatch** [comment]
From another user in the community:

```
maciej.lach
Avatars are visible for:

local users
Google users if another avatar is uploaded (only the avatar retrieved via Google is not working at all ie 48x48 picture is displayed)
```

Looks like the issue is isolated to avatars that come through via Google Auth.

**Comment by MrGeneration** [comment]
Please slow down, you're creating a lot of noise for this issue on my end.
As you've linked the community link I'll take it into consideration.

Thanks for your effort.

**Comment by fagiani** [comment]
@MrGeneration I've just updated from 3.6 to 4.1 and I can confirm the same behavior of missing avatars using Google auth.

**Comment by MrGeneration** [comment]
Thanks for the input.

**Comment by wmnnd** [comment]
@MrGeneration Just adding this comment to let you know this has also happened on my end, upgrading Zammad from 4.x to 5.0.2 on Ubuntu 18.04 via the official apt repository.
If there is any other information that I could provide in order to help you fix this, please let me know :slightly_smiling_face:

**Comment by MrGeneration** [comment]
Sorry I'm limitting the conversation of this issue to contributors only to reduce "me toos".
This is nothing personal but to reduce the noise and help us focus. 🙏

**Comment by rolfschmidt** [comment]
blocked by wrong mime type:

https://github.com/zammad/zammad/blob/92cd364ec2a0b023cdee770768025e4b41de9656/app/controllers/users_controller.rb#L735

invalid mime type "image" is based on a missing file extension of the url:

https://github.com/zammad/zammad/blob/92cd364ec2a0b023cdee770768025e4b41de9656/app/models/avatar.rb#L111-L117

should be detected by content i guess

**Comment by MrGeneration** [comment]
A possible feasible solution *might* be `mime/types` gem. 
Needs verifying though. `mimemagic` or `filemagic` might help too.

One can check if affected users are affected by this feature by using: `User.find_by(email: 'x@x.com').image_source`.
If `image_source` contains a URL without file extension you're affected.

Good news: The avatar is technically not lost, but Zammad decides to not display them for *security reasons*.

**Comment by astrugatch** [comment]
Is there any chance this gets added to the new workflow / milestones? We utilize Google auth almost exclusively and it just looks bad when all the avatars suddenly become blank boxes. Comes across as unprofessional. This has kept us on 4.1

**Comment by MrGeneration** [comment]
We're in general not providing any ETAs.
We're working hard on solving all bugs, please be patient.

If you're a paying customer drop support a mail.

**Comment by astrugatch** [comment]
@fagiani 
You mentioned having a fix / work around for this (mentioned a pull). Would you care to share? I am on the forums as well.

**Comment by Jenjen1324** [comment]
FYI this affected gravatar images for us as well. We worked around it with a rather dirty fix for now by just adding an `"image"` mime-type to `content_types_allowed_inline`.

i.e. in `config/environments/production.rb` adding the line:

```
config.active_storage.content_types_allowed_inline = ["image/png", "image/gif", "image/jpg", "image/jpeg", "image/tiff", "image/bmp", "image/vnd.adobe.photoshop", "image/vnd.microsoft.icon", "application/pdf", "image"]
```

All the other types were there by default

(Disclaimer: I'm not much of a rails guy, so there may be a more fitting place to put this configuration entry)

**Comment by MrGeneration** [comment]
## WARNING:

The solution @Jenjen1324 provided above partly disables security measurements and **IS NOT SUGGESTED**.
Use at own danger.

Please refrain from me toos as this issue is drawing a lot of attention.

**Comment by gcasasi** [comment]
Hi, I have the same problem in Zammad version: 5.1.0, I select user avatar but when I refresh page it sets to default again, 

any solution? 

Thanks!

**Comment by MrGeneration** [comment]
I'm locking this issue to contributors only to reduce noise.
The issue will be solved when every it is solved.

We're in general not communicating any ETAs.
