### ISSUE TITLE
TicketSelector in Overview or SLA not working with filter for ticket customer or owner

### ISSUE THREAD

**Issue by ntinti** [zammad/zammad#383]
It is not possible to create a new overview filtered by specific ticket-customer

StatusCode: 500

```{"error":"ERROR:  invalid input syntax for integer: \"\"\nZEILE 1: ...ate_id IN ('1','2','7','3') AND tickets.customer_id IN (''))\n ```

**Comment by martini** [comment]
Hi @ntinti 

Can you tell me (maybe via screenshot) what your overview settings are?

 -Martin

**Comment by ntinti** [comment]
You have Mail at support@zammad.com

**Comment by martini** [comment]
Thanks for screenshot/video with error - it's fixed now https://github.com/zammad/zammad/commit/c8eab7ca5626cf4c4c8b97b5a24b4a4e1f6f0daf
