### ISSUE TITLE
Updating organization members via API does not clear caches

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3832]
### Infos:

* Used Zammad version: 5.0.2 / stable as of 3rd Nov
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

When updating an organization via API (e.g. reducing the members attached to it), Zammad will display the changes - latest after reloading the browser session.

### Actual behavior:

When reducing the members array, Zammad will acknowledge the reduced number of members accordingly with it's answer on the update payload. However, the UI does remember old users still "being" in that organization. This affects the user edit screen, user detail view and the user management list. However, does not affect organisation detail view.

After running `Cache.clear` on the rails console the issue is solved.

The following payload was used to produce this behavior:

``POST-Request sent: /api/v1/organizations``
```
{
   "name": "Sample Corp.",
   "shared": false,
   "domain": "example.com",
   "domain_assignment": true,
   "active": true,
   "note": "Just a sample, aint that nice?",
   "members": [
      "olivia@example.com",
      "jdoe",
      "david@example.com"
   ]
}
```

``PUT-Request sent: /api/v1/organizations/{id}``
```
{
   "name": "Sample Corp.",
   "shared": false,
   "domain": "",
   "domain_assignment": false,
   "active": true,
   "note": "This was a triump - I'm making a note here - H-U-G-E success!",
   "members": [
      "olivia@example.com",
      "david@example.com"
   ]
}
```

### Steps to reproduce the behavior:

* create organization with several members
* update the organization and reduce the members of it via API
* have a look into the UI places where those relations are displayed - e.g.:
   * user edit screen
   * user detail view (profile)
   * user management (admin settings)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by bogatkaj** [comment]
Same behavior can be seen when adding a secondary organization to an user.
API shows the changes when the data of the user is requested, but the web-ui doesn't shows the changes
