### ISSUE TITLE
Feature: Allow searching for ticket title in Link dialogue (instead of only ticket #) 

### ISSUE THREAD

**Issue by dwehrmann** [zammad/zammad#3836]
Having implemented zammad in our organization lately, I think from a usability point of view, the "link ticket pop-up" would benefit from the ability of searching for a ticket title instead of human-unfriendly ticket number:

- status now: link to ticket #
(only a handful of last tickets are shown)
the agent can now enter a ticket number to link to

- desired status: enter ticket number OR search for ticket title and click the result to link it

I'd like to get my hands dirty on this but I'd at least need a starting point. Beforehand, let's make sure I'm not just missing anything and this is already implemented.

![Bildschirmfoto 2021-11-04 um 18 39 46](https://user-images.githubusercontent.com/1969892/140392032-f7697277-ddef-4003-8e5b-843c29422e9c.png)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
