### ISSUE TITLE
Microsoft 365 & Google channel ignore Proxy configuration for token refresh / verify

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3839]
### Infos:

* Used Zammad version: stable/5.0.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1095441
* also affects indirectly: #3840

### Expected behavior:

Zammad uses the configured proxy settings from the web UI ( https://admin-docs.zammad.org/en/latest/settings/system/network.html ) for token refresh and verify.

### Actual behavior:

Zammad completely ignores proxy configurations Microsoft 365 and Google channel token refresh and verifiy.
This causes admins to receive a `500` server error.

Zammad logs the following:
```
E, [2021-11-05T09:58:30.471743 #160064-175460] ERROR -- : execution expired (Net::OpenTimeout)
lib/external_credential/microsoft365.rb:190:in `authorize_tokens'
lib/external_credential/microsoft365.rb:42:in `link_account'
app/models/external_credential.rb:21:in `link_account'
app/controllers/external_credentials_controller.rb:43:in `callback'
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
I, [2021-11-05T09:58:30.477351 #160064-175460]  INFO -- :   Rendering inline template
I, [2021-11-05T09:58:30.478490 #160064-175460]  INFO -- :   Rendered inline template (Duration: 1.0ms | Allocations: 244)
I, [2021-11-05T09:58:30.478718 #160064-175460]  INFO -- : Completed 500 Internal Server Error in 60036ms (Views: 1.9ms | ActiveRecord: 4.6ms | Allocations: 10225)
```

### Steps to reproduce the behavior:

* have a very restrictive network where your Zammad instance cannot use internet connections directly
* configure proxy
* try to add Microsoft 365 or Google channel

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by ldallolio** [comment]
We are also affected by this, a possible workaround is to define the `http_proxy` and `https_proxy` environment variables with the corporate proxy and also `no-proxy` to exclude any internal site that should not go through the corporate proxy. These variables must be defined for the Zammad server.
