### ISSUE TITLE
IMAP & SMTP connections ignore proxy configuration

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3840]
### Infos:

* Used Zammad version: stable/5.0.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: #1095441
* also affects indirectly: #3839

### Expected behavior:

Zammad uses the configured proxy settings from the web UI ( https://admin-docs.zammad.org/en/latest/settings/system/network.html ) for email fetches and sendouts.

### Actual behavior:

Zammad currently doesn't support SOCKS connections which is why it's ignoring proxy settings.
The proxy configuration should be extended to ask "SOCKS y/n" to allow administrators to decide if socket connections have to be handled by their proxy too (if they're supported).

### Steps to reproduce the behavior:

* have a very restrictive network where your Zammad instance cannot use internet connections directly
* configure proxy
* try to use any channel that uses IMAP & SMTP connections

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
Currently, we are not planning to implement a SOCKS solution inside Zammad directly. It's already possible to configure the operation system in a way it's working. Also, we don't have currently requests in this direction.
