### ISSUE TITLE
Scrolling to Article by passing ID to URL is broken again

### ISSUE THREAD

**Issue by shaedrich** [zammad/zammad#3843]
### Infos:

* Used Zammad version: 5.0
* Installation method (source, package, ..): any
* Operating system: Windows 10
* Database + version: any
* Elasticsearch version: any
* Browser + version: Mozilla Firefox 91.2.0esr (64-Bit)
* Follow-up to #3330

### Expected behavior:

* When opening an Ticket Zoom URL containing an Article ID the browser scrolls to that Article ID

### Actual behavior:

* When opening an Ticket Zoom URL containing an Article ID the browser doesn't scroll to that Article ID

### Steps to reproduce the behavior:

* Open Ticket Zoom Article URL of an Article placed in the middle (e.g. #/ticket/zoom/#{ticket.id}/#{article_in_the_middle.id}

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I can't reproduce this, neither on Firefox nor on Chrome.
Please provide the exact required steps and ensure this is not caused by addons of your Browser.

Other wise I'm afraid we'll have to close this bug report.

**Comment by shaedrich** [comment]
Oh, found my mistake. It was in the URL. Nevermind. Sorry for the hassle.
