### ISSUE TITLE
Simple quote characters (`'`) not properly displayed

### ISSUE THREAD

**Issue by benrubson** [zammad/zammad#3846]
Hi,

### Infos:

* Used Zammad version: 5.0.2-1636369479.cb3516e4.buster amd64
* Installation method (source, package, ..): package
* Operating system: Debian 10
* Database + version: mariadb-server 10.3.31-0+deb10u1 amd64
* Elasticsearch version: oss 7.10.2 amd64
* Browser + version: Safari, Firefox (lastest versions)

### Expected behavior:

* Simple quote characters (`'`) in Zammad strings are shown as simple quotes.

### Actual behavior:

* Some simple quotes (`'`) are shown as their HTML entity (`&#39;`).
Patch for previous bug report (#3733) has partially solved this issue, but there are still some occurrences where bug triggers, as shown below.

![image](https://user-images.githubusercontent.com/6764151/141161716-5b1a209e-55aa-4669-8ee0-5772331a7cd6.png)

### Steps to reproduce the behavior:

* Put simple quote character (`'`) in some translations, and browse Zammad interface to see whether they are properly displayed or not.

Many thanks 👍

**Comment by benrubson** [comment]
Another example, in the scheduler configuration :

<img width="910" alt="image" src="https://user-images.githubusercontent.com/6764151/141379025-f0ac716e-52c5-4590-b2fb-3185dbeafb4b.png">

**Comment by benrubson** [comment]
CC @dominikklein, as the author of https://github.com/zammad/zammad/commit/2bd4ceeedfb999d4e948b8aa8b91a759eb7a4c1b.
Thx 👍

**Comment by MrGeneration** [comment]
Sorry I'm limitting this issue to contributors only to reduce the level of noise.
