### ISSUE TITLE
Collaborating with locked issues

### ISSUE THREAD

**Issue by fagiani** [zammad/zammad#3849]
### Infos:

* Used Zammad version: N/A
* Installation method (source, package, ..): N/A
* Operating system: N/A
* Database + version: N/A
* Elasticsearch version: N/A
* Browser + version: N/A

### Expected behavior:

* I am capable of collaborating with an open issue which is an actual bug on github by discussing a possible solution in order to send a PR.

### Actual behavior:

* Issue is locked and I cannot discuss the solution I've found in order to understand if a PR would be useful before I propose it.

### Steps to reproduce the behavior:

* You try to add a comment but the textbox is locked:
 
![image](https://user-images.githubusercontent.com/2450/141380711-3fe4b505-32f2-457e-9800-a230bd84c1db.png)

Yes I'm sure this is a not a bug but related to one and no feature request or a general question but a behavior I'd like to change in order to collaborate.

P.S. #3829 is the issue I want to contribute to.

Keep Rocking!

**Comment by MrGeneration** [comment]
Sorry but please more the discussion to the community thread linked.
I'm not sure what you would like to add, but the last additions were "me too"'s which is why the thread got locked.

**Comment by fagiani** [comment]
@MrGeneration I understand you might be too busy at the moment and maybe you didn't had the time to read what I just wrote as also I had the impression you didn't had the time to elaborate your first sentence of the last message as well and therefore I was unable to understand how I can *more the discussion to the community thread linked*.

Maybe I wasn't clear enough and in order to clarify, I will try again with more details:

* I mentioned I have found a solution. 
* This solution worked for me. 
* This solution might be a solution that can be contributed back to Zammad. 
* I'd like to share and understand if it can become a PR. 
* According to your contribution guidelines I should not open a new issue if there is already another on the same bug.
* I appreciate any insights, steps and guidance that can lead me to become a useful contributor to this project.
* If contributions are not welcome for now, it's fine, I will just fork the project and keep my changes there until it makes sense to you to consider it in the future.

Please know that: **As a recent user of this great software, I appreciate all the effort of Zammad's core team and this is a way that I can currently give back.**

Respectfully, I wish you the best!

**Comment by MrGeneration** [comment]
My bad sorry. I should take a nap.
If you want to you can, of course (! :)) provide a PR if you have a working solution.
Our developers will have a look asap. 💪 

Not sure if our documentation is helpful on your case:
https://docs.zammad.org/en/latest/contributing/start.html

It might be outdated on that regard 🙏
