### ISSUE TITLE
Number of to show caller log entries is inconsistent setting wise

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3852]
### Infos:

* Used Zammad version: stable / 5.0.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

CTI generic setting for number of to display caller log entries are available to all CTI like integration settings pages.
Basically so it doesn't matter in which CTI menu I'm changing the number of log entries.

### Actual behavior:

Number of caller log entries is available for CTI generic integration only.

![image](https://user-images.githubusercontent.com/6549061/141788654-63d11daa-a053-496a-a638-080d26effada.png)

### Steps to reproduce the behavior:

* have a look into:
    * CTI generic
    * sipgate
    * placetel

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
related to https://github.com/zammad/zammad/commit/be115dbb5cff1a34161c500c0b5a2c0623daba4d
