### ISSUE TITLE
Forwarding no longer possible for email and web articles

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3855]
### Infos:

* Used Zammad version: stable / 5.0.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Possible regression of: https://github.com/zammad/zammad/issues/3824
* Ticket: #1095880, #1096003

### Expected behavior:

If you have a communication article with email buttons (reply / forward), you can forward the articles content without issues.

### Actual behavior:

Web and email articles currently don't allow you to forward the mail in question - no error is shown. 
Developer console shows this:

![image](https://user-images.githubusercontent.com/6549061/142074913-7dbf7751-d108-44ce-84c3-40c5bb2f845f.png)

Strange enough: It does work for phone articles. :-)

Customer uses API to create the tickets. It does not matter if the `from` attribute is provided in article context.
If you add `to` attribute the issue is gone instantly. This thus only affects articles that have been created via API. `from` and `to` fields are not mandatory and thus should usualy™ not break forwarding processes:
```
{
   "title": "Magic",
   "group": "Sales",
   "priority_id": 2,
   "state_id": 1,
   "owner": "",
   "customer_id": 6,
   "article": {
      "subject": "Magic",
      "type": "web",
      "body": "XYZ,
      "content_type": "text/html"
   }
}
```

### Steps to reproduce the behavior:

* create web and email articles
* try to forward it

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
You can reproduce it with the following article created via rails console:

```
Ticket::Article.create!(
      ticket_id: 1,
      subject: "Magic",
      type: Ticket::Article::Type.find_by(name: "web"),
      sender: Ticket::Article::Sender.find_by(name: "Customer"),
      body: "XYZ",
      content_type: "text/html",
      created_by_id: 1,
      updated_by_id: 1,
)
```

Then go to http://localhost:3000/#ticket/zoom/1 and try to forward the last created article.
