### ISSUE TITLE
Trigger action "Owner" -> "not changed" needed

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#386]
I'll send a notification to the email customer if the assignment of the ticket has been changed.

There is already a template which does this, the trigger action is as below:

![image](https://cloud.githubusercontent.com/assets/3321655/20140722/0bb2e568-a68d-11e6-865a-2abe07ec4415.png)

The issue: The owner change triggers also the notification that the ticket has been updated (i.e. by a followup of the customer itself):

![image](https://cloud.githubusercontent.com/assets/3321655/20140744/322ac17a-a68d-11e6-956c-ec00625f70aa.png)

So the customer gets two notifiactions which is not what he wants ;-)

To exclude the customer from the "followup-notification", giving him just the message about the assignment change, either a trigger action "Besitzer" -> "Unverändert" is needed, or the change of the owner should not trigger the general "Aktion ist aktualisiert" action.

Another possibility would be having an explicit trigger criteria for "new message from the customer".

**Comment by jacotec** [comment]
@thorsteneckel Isn't that indeed a bug? Your **default notification which comes with a fresh Zammad install** sends the trigger notofication that his follow-up to the ticket has been recognized. And this is triggered also whenever i.e. an agent changes a ticket (which is in fact wrong as the customer did no action).

We really need a trigger in case the update of the ticket is caused by the customer (i.e. "changedby Customer|Agent|System")

**Comment by martini** [comment]
Hi @jacotec,

fixed. Updating a ticket is now just an additional condition - so no owner changed is triggered. I created an test for your use case (https://github.com/zammad/zammad/commit/5a6310695811346557beb2ecefb5ccf570989db0#diff-7b159d7831b0b9385a0aae8bb9a1e9b7R2223). The tests works fine. It's available in master branch/packages (will get in stable ASAP).

Feedback is welcome!

 -Martin

**Comment by martini** [comment]
Available in stable branch/packages.

**Comment by jacotec** [comment]
Hi @martini ,

I gave this a try ... it seems that you did break other things unfortunately.

I've got triggers to send the customer a note when the assigned personnel (owner) was changed and when the status of a ticket is changed:

![image](https://cloud.githubusercontent.com/assets/3321655/23553027/060afe70-001f-11e7-8f1c-76c83cfceda2.png)

![image](https://cloud.githubusercontent.com/assets/3321655/23553050/25371888-001f-11e7-8f6b-350454c53794.png)

Neither of them is working anymore :-(

I did create a test ticket, then first assigned the ticket and in a second step I did set the status from "new" to "open" and then from "open" to "close" - none of the trigger messages is sent out.

Also the History shows that no notifications have been sent:
![image](https://cloud.githubusercontent.com/assets/3321655/23553089/6a53a95e-001f-11e7-9aa7-dd03c3bc41cd.png)

When the customer now sends another reply to the ticket, both triggers are active:
First the "Kundennachricht Status geändert" was triggered and the notification was sent to the customer that the status was changed to "open", then the initial trigger that the customer has updated the ticket was fired.

Conclusion: If an agent changes the ticket status or assignment, the "the ticket was updated" message is not triggered - so that's fixed. On the bad side: When the agend changes these things, the triggers which should react on "status change" and "assignment change" are not triggered at all, so that's broken. If the customer changes the status by a reply to a closed ticket, the trigger "status change" works.

It seems you need to fix the fix ;-)

**Comment by martini** [comment]
I'm cover this scenario with a test... come back asap....

**Comment by jacotec** [comment]
Thanks ... let me know if you need any tests/logs.

**Comment by jacotec** [comment]
Hi @martini ,

any news here?

**Comment by jacotec** [comment]
Hi @martini ,

sorry to push ... did you check this? It's still broken and I'm using these triggers ;-)
