### ISSUE TITLE
Restore failing from same new system

### ISSUE THREAD

**Issue by Lapotor** [zammad/zammad#3860]
### Infos:

* Used Zammad version: 5.0.2
* Installation method (source, package, ..): package
* Operating system: ubuntu 20.04
* Database + version: postgres 12.9
* Elasticsearch version: elasticsearch 7.15.2

### Expected behavior:

* Install zammad (hetzner cloud)
* After install create backup (with #2508)
* After backup restore same backup directly
* Restoreing successful

### Actual behavior:

* Backup folder set as in #2508
* try restore this backup
   *  when restoreing with zammad user:
```
$ sudo -u zammad -H /opt/zammad/contrib/backup/zammad_restore.sh

# Zammad restored started - Sat 20 Nov 2021 01:45:26 PM UTC!

The restore will delete your current config and database!
Be sure to have a backup available!

Enter 'yes' if you want to proceed!
Restore?: yes
Enter file date to restore:
20211120134351
File date: 20211120134351
Enter db date to restore:
20211120134351
DB date: 20211120134351
# Stopping Zammad
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to stop 'zammad.service'.
Authenticating as: root
Password: Failed to stop zammad.service: Connection timed out
See system logs and 'systemctl status zammad.service' for details.
# Checking requirements
polkit-agent-helper-1: pam_authenticate failed: Authentication failure
# ... Dropping current database zammad
PG::ObjectInUse: ERROR:  database "zammad" is being accessed by other users
DETAIL:  There are 6 other sessions using the database.
Couldn't drop database 'zammad'
rake aborted!
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  database "zammad" is being accessed by other users
```
   * When restoring with `root` user:
```
$ /opt/zammad/contrib/backup/zammad_restore.sh

# Zammad restored started - Sat 20 Nov 2021 01:48:10 PM UTC!

The restore will delete your current config and database!
Be sure to have a backup available!

Enter 'yes' if you want to proceed!
Restore?: yes
Enter file date to restore:
20211120134351
File date: 20211120134351
Enter db date to restore:
20211120134351
DB date: 20211120134351
# Stopping Zammad
# Checking requirements
# ... Dropping current database zammad
Dropped database 'zammad'
# ... Creating database zammad for owner zammad
CREATE DATABASE
# Restoring PostgreSQL DB
psql: error: FATAL:  Peer authentication failed for user "zammad"
# Restoring Files
# Ensuring correct file rights ...
# Clearing Cache ...
# Starting Zammad

# Zammad restored successfully - Sat 20 Nov 2021 01:48:36 PM UTC!
```

### Steps to reproduce the behavior:

* Install zammad (hetzner cloud)
* After install create backup (with #2508)
* After backup restore same backup directly

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by Lapotor** [comment]
Ok posted it there.
https://community.zammad.org/t/restore-failing-from-same-new-system/8146
For me seams more as a bug then a question.

**Comment by Robin-Marquardt** [comment]
@MrGeneration It's a bug i can reproduce this Failure

**Comment by MrGeneration** [comment]
See https://github.com/zammad/zammad/issues/3865 which we're using for this topic.
Apologies to @Lapotor who was right initial this being an issue.

We're handling this as a duplicate of #3865

**Comment by Robin-Marquardt** [comment]
perfect thanks
We have to move 2 systems due to a provider change and are faced with the hurdle
We hope the bug will be fixed quickly so as not to lose our customers :(

**Comment by MrGeneration** [comment]
Sorry but no ETA as always. I'm locking this as this is getting off topic.
