### ISSUE TITLE
Splitting an email creates a new ticket with the wrong recipient

### ISSUE THREAD

**Issue by zaidka** [zammad/zammad#3863]
### Infos:

* Used Zammad version: 5.0.x (hosted version from zammad.com)
* Installation method (source, package, ..): Not sure
* Operating system: Not sure
* Database + version: Not sure
* Elasticsearch version: Not sure
* Browser + version: Firefox 94

### Expected behavior:

* When using the 'split' feature, the newly created ticket should have the sender of the message I'm splitting as the recipient.

### Actual behavior:

* The split message has the sender of the first message in the thread as the recipient, not the sender whose message I'm splitting.

### Steps to reproduce the behavior:

* Person A sends an email with person B in CC. Person B sends an off topic reply. I split the reply to a separate thread. The recipient in the newly created thread becomes person A, not B.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by t-shehab** [comment]
This is working as designed at the moment. When you split an article into a new ticket, you first end up in the ticket-create mask. By default, the customer of the originating ticket is set. It can be changed freely in the creation mask, however.

Closing.

**Comment by zaidka** [comment]
Unless you remember to change the customer, when you split a ticket your reply may be sent to the wrong recipient. This doens't sound like a reasonable default behavior from a user perspective. I'd even argue that to not auto populate the customer field in the first place would make for a better default behavior.

**Comment by MrGeneration** [comment]
The information comes from the article not the ticket. That's why Zammad behaves that way. If you believe this should change, you're very welcome to add a feature request here:
https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6
