### ISSUE TITLE
Postgresql Backup & Restore failing on default package installations

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#3865]
### Infos:

* Used Zammad version: 5.0.2
* Installation method (source, package, ..): package
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: ~~#1095458, #1099949~~

### Expected behavior:

When a backup is started with the backup script it should backup the database. If an error occurs the script should stop with an error.

### Actual behavior:

The database dump fails with error:
```
creating postgresql backup...
pg_dump: [Archivierer (DB)] Verbindung zur Datenbank »zammad« fehlgeschlagen: FATAL: Peer-Authentifizierung für Benutzer »zammad« fehlgeschlagen
```

But the backup continues and log says "backuped successfully "

### Steps to reproduce the behavior:

Run script as root user:
`/opt/zammad/contrib/backup/zammad_backup.sh`

####Issue:
When the database dump fails the logs show "backup successful" wich confuses the clients.

Example below:
```
pg_dump: [Archivierer (DB)] Verbindung zur Datenbank »zammad« fehlgeschlagen: FATAL: Peer-Authentifizierung für Benutzer »zammad« fehlgeschlagen
```
 ...
```
# Zammad backuped successfully - Di 23. Nov 11:59:58 CET 2021!
```

**Comment by MrGeneration** [comment]
Indirectly also covers the technical question:
https://github.com/zammad/zammad/issues/3860

Introduced by:
https://github.com/zammad/zammad/pull/3621
https://github.com/zammad/zammad/pull/3561

**Comment by mgruner** [comment]
See also #3744

**Comment by MrGeneration** [comment]
Note: "Any installation type" is technically incorrect. 
This should only affect default package installation - the main reason for this is the way the above mentioned PRs changed the backup & restore functionalities and the (per default) absense of hostname and port.

**Comment by MrGeneration** [comment]
👋 The time has come.
Starting with package version `zammad_5.0.3-1643280981.141dc0ca.xxxxx.xxx` and later Zammad will ship the new backup and restore script. This is available in rolling stable. 

Please note that current Debian 11 build failed and may take longer to arrive on Debian 11 as stable. In case you need it *now*, grab your copy from the repo: https://github.com/zammad/zammad/tree/stable/contrib/backup


Please also note that this script fix comes bundled with a reworked backup and restore documentation.
This two belong together and should rule out all upcoming questions:
https://docs.zammad.org/en/latest/appendix/backup-and-restore/index.html

If not, please create a thread on the community: https://community.zammad.org
