### ISSUE TITLE
Date of datepicker is not localized 

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3866]
### Infos:

* Used Zammad version: develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Show date in datepicker localized 

<img width="315" alt="Screenshot 2021-11-23 at 19 35 54" src="https://user-images.githubusercontent.com/110226/143083959-94251614-938f-442f-b97e-0754882bb744.png">

### Actual behavior:

* Date in datepicker is not shown localized

### Steps to reproduce the behavior:

* switch language to de
* open a ticket and select a pending state

**Comment by rolfschmidt** [comment]
regression of https://github.com/zammad/zammad/commit/64a87b1c67c2dad7e9311491115f73606b14acc6
