### ISSUE TITLE
parsing incoming mails breaks on this line "Reply-To: <>"

### ISSUE THREAD

**Issue by darc-ev** [zammad/zammad#3867]
### Infos:

* Used Zammad version: 4.1.x 
* Installation method (source, package, ..): package
* Operating system: CentOS 7
* Database + version: 
* Elasticsearch version: 
* Browser + version: none, it's an cli issue

### Expected behavior:

* parsing incoming mails should not break if the mail contains this line: "Reply-To: <>"

### Actual behavior:

* it breaks with this error message

```
zammad run rails r 'Channel::EmailParser.process_unprocessable_mails'
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/83e5bf7c5a1a640f057cbf0b668f40e0.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<Exceptions::UnprocessableEntity: Invalid email '@local'>"
/opt/zammad/app/models/channel/email_parser.rb:135:in `rescue in process': #<Exceptions::UnprocessableEntity: Invalid email '@local'> (RuntimeError)
/opt/zammad/app/models/user.rb:927:in `check_email'
...
```

Once I removed the Reply-To line it works. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
So what you're saying is that Zammad should ignore Reply-To header if they are broken?
How should Zammad react if the same applies for FROM or TO addresses?

Personally I see this not really as a bug but as a sender issue.
For 99.5% I'm seeing these kind of issues it's a spammer trying things (so Zammad is a natural spam filter :P)

The other 0.5% this happens because some user did set broken headers for whatever reason.
The thing is that this doesn't only affect Zammad but all mail programs (if you see it in context).

What does @martini  think?

**Comment by darc-ev** [comment]
I would ignore an empty Reply-To, yes.
I would not ignore it, if Reply-To has other illegal addresses. 

The reason is simply: the Reply-To header is optional. 

I am not talking about FROM or TO here. But for me it is clear that you should not ignore empty addresses in these header lines.

**Comment by MrGeneration** [comment]
Good news. We've accepted the proposal as enhancement. We do not see this as a bug but feel that this should be improved.

**Comment by dominikklein** [comment]
@MrGeneration Do you have some examples, of which "Reply-To" content leads to an unprocessable mail? Because it's not reproducible on stable/develop with the `Reply-To: <>`. Or we did some wrong steps to reproduce the issue.

**Comment by martini** [comment]
I just tried to verify this. It's important that `Setting.set('postmaster_sender_based_on_reply_to', 'as_sender_of_email')` is set.

Then you simply can reproduce it with `Reply-To: <> `

e.g.

```
From: hs@example.com
To: support@example.com
Subject: test 1
Reply-To: <>

some body 1
```

Just save the file to `test.eml` and process it via:

`cat test.eml | rails r 'Channel::Driver::MailStdin.new'`
