### ISSUE TITLE
Add search option to admin screens (like it already exists for users) to text modules, macros, organizations, groups, overviews, triggers, schedulers, ...

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3868]
### Infos:

* Used Zammad version: 5.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Search in certain object (like text modules) lists in admin interface (like it is for users)

<img width="1175" alt="Screenshot 2021-11-25 at 13 57 33" src="https://user-images.githubusercontent.com/110226/143445850-b4b32cb4-385c-48ff-a23c-516ee23a819f.png">

### Actual behavior:

* No search option is available

<img width="1177" alt="Screenshot 2021-11-25 at 13 56 49" src="https://user-images.githubusercontent.com/110226/143445743-9b733563-1553-47e5-b525-89061355847d.png">

### Steps to reproduce the behavior:

* got to admin interface
* create many text modules (> 200)
* try to find a certain text module by content

**Comment by dominikklein** [comment]
Closing with https://github.com/zammad/zammad/issues/5384
