### ISSUE TITLE
Overview select fields are sorted by key

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3869]
### Infos:

* Used Zammad version: 5.0.2/stable
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on Google Chrome v96.0.4664.45
* Ticket: #1096070

### Expected behavior:

Zammad uses display values to sort tickets in overviews.

### Actual behavior:

For select objects Zammad prefers to sort by key.

![image](https://user-images.githubusercontent.com/6549061/143458387-8f767618-b702-412f-8bb3-3d823429d121.png)

### Steps to reproduce the behavior:

* Configure a select field like so:
   ![image](https://user-images.githubusercontent.com/6549061/143458504-0f9b87e9-9332-4618-9e64-9689949d6b48.png)
* Have 3 or mote tickets with values that should follow display value wise (you'll see the sorting not fitting)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
related to https://github.com/zammad/zammad/issues/3800 https://github.com/zammad/zammad/issues/3737
