### ISSUE TITLE
Text rendering does not work for e-mails (no new lines) received in Zammad

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#3870]
### Infos:

This works on Zammad 4.0 like intended.

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): N/A
* Operating system: N/A
* Database + version: N/A
* Elasticsearch version: N/A
* Browser + version: N/A
* Ticket number: 1096288

### Expected behavior:

When an e-mail is received, Zammad should render the text like it is in the e-mail 

### Actual behavior:

When an e-mail is received Zammad does not render the text. The whole content of the mail is displayed as in a continuous flow text.

### Steps to reproduce the behavior:

Send the test mail attached to the issue, to the Zammad inbox
[Test 1.zip](https://github.com/zammad/zammad/files/7607168/Test.1.zip)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Regression of https://github.com/zammad/zammad/commit/f50016b008cc7d2f77fa1658b921d708e70ac326#diff-7a3f591cbfde2c170f932b83646c12bbc5db4f65687358c6c03f625becadb2fd
