### ISSUE TITLE
Duplicate results in search

### ISSUE THREAD

**Issue by mjomble** [zammad/zammad#3876]
### Infos:

* Used Zammad version: 5.0.1
* Installation method (source, package, ..): Debian package
* Operating system: Debian
* Database + version: PostgreSQL 11.13
* Elasticsearch version: Not in use
* Browser + version: Chrome 96 / Postman 9.2

### Expected behavior:

* The `/search` API endpoint returns at most one result per ticket.
* The `/tickets/search` API endpoint returns at most one result per ticket.
* If more than 10 tickets match the term and I use `limit=10`, 10 unique tickets appear in both results.

### Actual behavior:

* `/search` returned `"results":[{"id":82,"type":"Ticket"},{"id":82,"type":"Ticket"},{"id":82,"type":"Ticket"},{"id":2,"type":"Ticket"},{"id":2,"type":"Ticket"},{"id":2,"type":"Ticket"}, ...`
* `tickets/search` returned `{"tickets":[82,82,82,2,2,2,2,2,2,2], ...`
* With `limit=10`, I only see 2 unique tickets in the results, even if many other tickets match the term.

### Steps to reproduce the behavior:

* Create a ticket that includes the same term in multiple articles
* Search for that term
* (If the issue does not reproduce when using Elasticsearch, try on an installation without it)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mjomble** [comment]
We now configured Elasticsearch for our test environment and the problem disappeared.

So it seems this only affects the fallback solution that is used when Elasticsearch is not available.

**Comment by rolfschmidt** [comment]
I can confirm the behaviour without ES

**Comment by benma** [comment]
Same problem here! How to troubleshoot / fix?

**Comment by MrGeneration** [comment]
> Same problem here! How to troubleshoot / fix?

I'd suggest patience. Bumping issues does not speed them up but causes a lot of noises to many people.
