### ISSUE TITLE
Missing translation/edit abilities (Notification mails, contact form)

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#388]
Hi,

I'm missing translation or editing capabilities for:

- Messages sent to agents ("Notification Master" emails). I can change the "Notification master" name, but all the text inside the email is english - where can the text messages be edited?

- Feedback form: Where can I "germanize" this?

![image](https://cloud.githubusercontent.com/assets/3321655/20142572/8ebf070e-a695-11e6-8db1-858807c8e22e.png)

**Comment by martini** [comment]
Hi @jacotec 

1) currently the notification templates are unter app/views/mailer/*/$LANG_$FORMAT.erb
 -> The language of the user (preferences setting) is used, as fallback en is used.
 -> Later we will offer a ui to edit the templates, currently you only can do it via files directly

2) you can "germanize" is  for now with the following (but I'll do an improvement to set it easier - will post if on this issue asap):

```
<button id="feedback-form">Feedback</button>

<script id="zammad_form_script" src="http://localhost:3000/assets/form/form.js"></script>
<script>
$(function() {
  $('#feedback-form').ZammadForm({
    messageTitle: 'Feedback Form', // optional
    messageSubmit: 'Submit', // optional
    messageThankYou: 'Thank you for your inquiry! We\'ll contact you soon as possible.', // optional
    messageNoConfig: 'Unable to load form config from server. Maybe featrue is disabled.', // optional
    showTitle: true,
    modal: true,
    attributes: [
      {
        display: 'Name',
        name: 'name',
        tag: 'input',
        type: 'text',
        placeholder: 'Deine Name',
      },
      {
        display: 'Email',
        name: 'email',
        tag: 'input',
        type: 'email',
        placeholder: 'Deine E-Mail',
      },
      {
        display: 'Message',
        name: 'body',
        tag: 'textarea',
        placeholder: 'Deine Nachricht...',
        rows: 7,
      },
    ]
  });
});
</script>
```

**Comment by jacotec** [comment]
Seems 1) is not using the user's preference. User is set to "Deutsch" in it's profile, notification emails are in English.

**Comment by martini** [comment]
Sorry, I was not clear. Notifications link "Ticket created" or "Ticket updated" are localised based on users language preferences setting.

Did you mean this "Ticket created" or "Ticket updated" notifications of custom notifications based on own triggers?

**Comment by jacotec** [comment]
I'm talking about these notification mails to the agents:

FBL Helpdesk Notification
Hi Marco,

A new ticket (Test neue Notification) has been created by "Marco Jakobs".

Group: Geschäftsstelle
Owner: -
State: new

Information:
Das ist ein Test

View this in Zammad
Manage your notifications settings | FBL

**Comment by martini** [comment]
JFI: Added from translations based on <html lang="xx"> attribute. Added es/de/es/fr translations per default. No attributes for translation needed anymore. https://github.com/zammad/zammad/commit/fc8008b7e464dfc6393cdffc58a043401d6cefff

**Comment by jacotec** [comment]
Hi @martini 
I've installed the latest dev version, the form is OK but the mail notifications are still in English, although there is a german .erb file.

Any idea?

> Hi Marco,
> 
> A new ticket (Test für das Ticket) has been created by "Max Muster".
> 
> Group: Ticketsystem Test
> Owner: -
> State: new

**Comment by martini** [comment]
Translation of notification is now in issue https://github.com/zammad/zammad/issues/401

**Comment by Guevarabrik** [comment]
hi @jacotec 
You can change the text of the notifcations under *Settings -> Triggers*. just edit the event text to german, in order to get german emails.
