### ISSUE TITLE
Collapsible Navigation

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad#3881]
Hi everybody,

this is not an issue. It's a feature-request :-)

I'm using Zammad 5.

It would be really nice if the Navigation on the left side (grey navi) would be collapsible.

This Behaviour could be configured in User-Profile (if collapsible or not).

Nearly 30% of the interface is used by by navigation if user is in list-view.

Best Regards and thanks for your time!

David

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
