### ISSUE TITLE
[Feature Request] Provide IP of the customer in the web interface for Agents

### ISSUE THREAD

**Issue by gituser** [zammad/zammad#3883]
Currently there is no way to determine IP of the customer which has been used to log-in into Zammad or register there for Agents.

For Administrators you could look inside the Sessions, but again it won't work if user logged out.

It's a crucial feature to have because Agents must be able to look-up what IP address has been used by the Customer in order to:
* detect abuse
* detect multiple accounts used with same IP but different e-mail
* any other suspicious activities

IP could be shown (for Agents or Administrators) in:
* user profile actions
* each ticket message (if there is any IP and user is not answering via e-mail)

I know I could post this in the community.zammad.org but I've seen many threads there without replies for years or even completely ignored, so I'm posting here this feature request.

Thank you.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.

**Comment by gituser** [comment]
@MrGeneration 
Thank you for the quick answer.

However, I think your model for feature requests is faulty, e.g. take a look at this (for example): https://community.zammad.org/t/can-we-get-a-darkmode-theme-please/5438/4

There were many users asking for this feature and 19 likes and still not implemented at all.

So, judging from your response, features will only be implemented if someone actually pays for it otherwise not or if someone submits a Pull Request with the complete patch.

**Comment by MrGeneration** [comment]
Sorry I'm not open for discussion.
Feature Requests do not mean they *have* to be accepted.

Also, keep in mind that we have limited ressources and thus can't always provide everything you want.
Create a feature request in the correct spot and we're all good.

You generously already ignored the issue template.
Your assumption is incorrect.

Bye for now.
