### ISSUE TITLE
deactivated KB displays error page with SQL command

### ISSUE THREAD

**Issue by bastolino** [zammad/zammad#3888]
### Infos:

* Used Zammad version: 5.0.3-1639085449.b757f8e2.focal
* Installation method (source, package, ..): package deb
* Operating system: Ubuntu 20.04.3
* Database + version: MariaDB 10.3.32-0ubuntu0.20.04.1
* Elasticsearch version: 7.16.0
* Browser + version: not needed

### Expected behavior:

* with deactivated KnowledgeBase I expect to receive a 404 on the <hostname>/help/ -URL without further notice like this:
![grafik](https://user-images.githubusercontent.com/4018936/145761761-1fd6cc1b-350f-40fb-86b7-66f0a17d2559.png)

### Actual behavior:

* part of an SQL request is shown together with a 404
![grafik](https://user-images.githubusercontent.com/4018936/145761474-b8b42be1-0f98-468d-869e-243eb5541377.png)

### Steps to reproduce the behavior:

* deactivate KnowledgeBase
* Log off (hint: clear browser cache)
* browse to <hostname>/help/

**Comment by MrGeneration** [comment]
JFI: There's no information leak happening. Please be careful with those kind of catch phrases as they may make others feel nervous.

**Comment by bastolino** [comment]
Actually, I am feeling a bit nervous as well as I do not know what else could be extracted ;)
But okay for me. Today, there's other security issues on the plan, that's why I disabled the KB...
