### ISSUE TITLE
JS error on editing textareas admin object manager attributes

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3889]
### Infos:

* Used Zammad version: 5.0.2-1638282353.9435da0a.buster amd64 
* Installation method (source, package, ..): packages
* Operating system: Debian 10
* Database + version: MariaDB 10.3.31-0+deb10u1
* Elasticsearch version: 7.10.2
* Browser + version: Safari 15?0, Firefox 94.0.2

### Expected behavior:

* Can not edit field Address (textarea) in object manager attributes.

### Actual behavior:

I don't know whether or not this is related, but I suspect it is, when I click on _Address_ property of _User_ in _Objects manager_, nothing happens, but the following JS error :

![image](https://user-images.githubusercontent.com/6764151/144554018-079cd34d-91f1-498c-b127-ef275c5aa361.png)

_Originally posted by @benrubson in https://github.com/zammad/zammad/issues/3878#issuecomment-985243869_

### Steps to reproduce:

-> Open Admin -> Objects
-> Switch to tab User
-> Open field "Address"
-> js error in console.

**Comment by rolfschmidt** [comment]
@benrubson pls try in the future to NOT put multiple topics in one issue.

**Comment by benrubson** [comment]
@rolfschmidt, sure, sorry for this, as I thought they were related I did not open 2 different issues 😕
Anyway, thank you for your consideration into this 👍

**Comment by rolfschmidt** [comment]
Hi @benrubson 

does this issue still occur to you? I know back then I got it once but it does not seem to be reproducible (also tried the old commit) any more hm... The only thing I have at the moment is that the text area is too small which I could fix then also.

**Comment by benrubson** [comment]
Hi @rolfschmidt,
Unfortunately yes, still reproductible, for example clicking on the default `Address` property of the `User` object.
I'm running last version (`5.0.3-1641391411.7adc0a12.buster`).
Tested in both Safari and Firefox.
Feel free if you need more debug info 👍

**Comment by rolfschmidt** [comment]
@benrubson does it happen every time to you? What are the excactly steps? I tried it look at my video:

https://user-images.githubusercontent.com/5445062/148384627-1117729b-40a4-4783-bd26-af674a78cab4.mov

I could not reproduce it in a new workflow, saved worfklow and on a hosted system of us with firefox. Don't have safari tho. I remember that I had this issue also last year, but I forgot how to get the error.

**Comment by benrubson** [comment]
@rolfschmidt I see, we are not in the same place :)
So in #3878 I asked to add organization and address as action for the User object, in Core Workflow.

But here, in #3889, error is not in Core Workflow, but in _Admin > System > Objects_.
Then go into _User_ object manager, and click on _Address_ to edit this property.
Nothing will happen, and the JS error will trigger.
(I first mentioned this in #3878 because this may be the cause of _address_ not appearing as action for the User object, in Core Workflow, they may be related...)

**Comment by rolfschmidt** [comment]
ah okay I got you sorry!

Steps to reproduce:
-> Open Admin -> Objects
-> Switch to tab User
-> Open field "Address"
-> js error in console.

**Comment by benrubson** [comment]
Yep, that's it 👍
