### ISSUE TITLE
Core Workflow: Add tags as action for object Ticket

### ISSUE THREAD

**Issue by benrubson** [zammad/zammad#3891]
### Infos:

* Used Zammad version: 5.0.2-1638282353.9435da0a.buster amd64 
* Installation method (source, package, ..): packages
* Operating system: Debian 10
* Database + version: MariaDB 10.3.31-0+deb10u1
* Elasticsearch version: 7.10.2
* Browser + version: Safari 15?0, Firefox 94.0.2

Related to #3878.

### Expected behavior:

* It should be possible to select tags as action for the Ticket object.

### Actual behavior:

* Tags is not available.

![image](https://user-images.githubusercontent.com/6764151/146415712-4edab31e-ce8e-4cfd-95b3-7dccb70b63a6.png)

### Steps to reproduce the behavior:

* Create a core workflow based on ticket, and try to select Tags as action, for example to set it as mandatory.

Yes I'm sure this is a bug and no feature request or a general question.

Many thanks 👍

**Comment by MrGeneration** [comment]
@rolfschmidt you decide.
I say this is a feature request and not a bug.

**Comment by rolfschmidt** [comment]
yeah its a feature/enhancement...

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.

**Comment by benrubson** [comment]
Well, I took example on #3779, which has properly been left opened 😕 ...
Could we then think about re-opening this please ?
Note that I initially thought it was a bug, as I thought every property would automatically be available in the drop-down menu (but then seems like it's done one by one).
Many thanks for your consideration 👍

**Comment by MrGeneration** [comment]
Sorry I am not open for discussions.

I understand that it's not easy to understand why some enhancements slip through and are accepted right away and others are not. However, with the pace Zammad evolves and the extreme number of feature requests it's impossible to provide everything single persons or companies want.

This means that we have to sort out and find out how valuable a desired function really is.
In this case this currently smells rather edgy.  Sorry.
