### ISSUE TITLE
`/assets/fonts/` changed to `/fonts/`

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3892]
### Infos:

* Used Zammad version: 5.0.3 
   * customer sees this starting with https://github.com/zammad/zammad/commit/b757f8e2c5b7952483ca11f8a49a6119f50df5e4
   * I cannot reproduce this on develop state 0456cce951707d1e94548b5f81e42bf49b22e004
   * Reproducable on current stable SaaS
* Installation method (source, package, ..): any 
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified von Google Chrome v90, any
* This was first seen on the community ( https://community.zammad.org/t/fonts-dont-load-on-newest-version-404/8284 ) and quickly transferred by me.

### Expected behavior:

Zammad uses `/assets/fonts/` for loading fonts.

### Actual behavior:

Zammad decided to use `/fonts/` for loading fonts.

Note:
I could not find a fitting commit for the last 14 days that should affect this code wise. Might be dependency related (stable only...?).
Fonts file looks fine: https://github.com/zammad/zammad/blob/5c333430ca6bfe63fff9e7c4b9c825a093b2aa53/app/assets/stylesheets/font.css

### Steps to reproduce the behavior:

* have a fresh or updated Zammad installation as per today or within the last 7 days

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
It's present after the rails update: https://github.com/zammad/zammad/commit/cf2d8dc820115ce7f3cc707de2164e16f50d6911
