### ISSUE TITLE
How are images url stored / how to retrieve them ?

### ISSUE THREAD

**Issue by arnaudambro** [zammad/zammad#3895]
Hi there

I can't find out how the image url is built, and how I can retrieve all images from the knowledge base easily.
I can see in the `body` column of the `knowledge_base_answer_translation_contents` table that images are stored like that

```
<img src=\"cid:KnowledgeBase::Answer::Translation::Content_body.{some-kind-of-id-with-number-and-email?}\" />
```
which transforms in when read in the browser like that
```
https://{my-url}/api/v1/attachments/{another-id-with-numbers}
```

So the question is : what is the logic behind that ?
How can I amp a `KnowledgeBase::Answer::Translation::Content_body.{some-kind-of-id-with-number-and-email?}` to a `{another-id-with-numbers}` ?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by arnaudambro** [comment]
Your organisation there, and your welcoming, is as poor and as complicated as your model and number of tables and poor documentation.

An answer to my question would be done in two lines : check this table and that one too and you're done !
But no, instead everybody has to lose its time.

No thanks.

**Comment by MrGeneration** [comment]
Thank you for fulfilling my expectation on your salty level in your response. 🎉

You started the time waste on your end by willingly ignoring our issue template and posting a technical question while knowing it's the wrong place.

Have a wonderful day! :-)

**Comment by arnaudambro** [comment]
Yes my answer is salty, because your product gives me headache.

Your db model is so twisted.
Your documentation is so poor.
I lose so much time all around, trying to figure why/how/where.
My server crashes sometimes, no reason, no real explanation.
Our team of 5 devs is getting out of his mind with Zammad, and that's infortunate.
We *did* try our best to be well hearted and try to understand your product, but man, we're leaving now.

You think it's great to have a crazy template of github issues : I think what is great is to have the less issues in github, and if the answer is easy, give it in the message while you push the user to the right place for the next time. The way you handle this give me one more reason to leave Zammad : it's not that you're mean (I am, you're not, you're customer support, that's ok !), it's just that you and your Zammad friends are doing thing the wrong way.

Make dev happy is important, but you're not taking that way.

Anyway, if someone has the answer to my question - cause there are tons of images crazily stored out there in Zammad that I can't take back programmatically yet, because of a completely crazy storage system - I'll be very glad !

Thanks

**Comment by mantas** [comment]
@arnaudambro may I introduce your rockstart team of 5 devs to project-wide text search?

Give a direct link to the method doing conversion and you feed man for a day. Teach man to [RipGrep ](https://github.com/BurntSushi/ripgrep) and you feed him for a lifetime :)

**Comment by arnaudambro** [comment]
Oh man, I didn't say we're rockstart team, but surely we're honest guys. I have no doubt you have a better estime of yourself than us.

I give you a feedback, surely salty and surely bad but hey, I'm writing you as a disappointed dev having a disappointing dev experience, spending weekends on my project because time is running out unexpectedly, so I give me the right to be upset. I'm not always upset and I usually try to get involved in improving OS projects if and when I can, and I try to be a nice guy, but you don't make things easy !

Given my feedback, it gives two choices for you : either you don't care and do what you properly do now, either you care about your clients and try something else. Like instead of giving me a lesson, a simple answer would have been useful.

But anyway, spend more time kicking away your clients if it sounds good for you !

Cheers

**Comment by MrGeneration** [comment]
Your very positive feedback and way to communicate surely will improve things.
Fun fact: The last 2 issues I've seen on other projects had the very same attitude. It's hard to believe your good will as you may understand.
Good luck with your project though.

Sorry, but to reduce noise on this issue and save my weekend from getting even worse thanks to your attitude I'm locking this issue. Community just received a 14 day timeout from me. Congratz - I'm sure that was the goal.
