### ISSUE TITLE
Wrong calculation for ES payload size, ES index corruption

### ISSUE THREAD

**Issue by Katalystical** [zammad/zammad#3899]
### Infos:

* Used Zammad version: 5.0.3
* Installation method (source, package, ..): package/Docker
* Operating system: Linux
* Database + version: MariaDB 10.3
* Elasticsearch version: 7.10 (Opensearch with legacy/compat flag), 10MB payload limit due to AWS limitations on this type of instance
* Browser + version: irrelevant

***NOTE:*** this seems to be only applicable for ES services with strict payload limitations, but this issue is pointing to a bug nonetheless.

### Expected behavior:

Setting `es_total_max_size_in_mb` to a value like `10` (10 megabytes, 10485760 bytes) should really limit the payload size transmitted to the ElasticSearch service to 10MB. ElasticSearch reindex should work normally.

### Actual behavior:

You can observe massive failures/error messages when starting a re-index of ES (via `rake searchindex:rebuild`), failing with HTTP Statuscode 413 (Request Entity Too Large) - the payloads that fail are roughly around 11-12MB, by far more than specified as limit. It corrupts the incides - but erroneously finishes at some point.

While the setting (`es_total_max_size_in_mb` and the attachment-specific one) takes effect and is correctly compared in `app/models/ticket/search_index.rb`, the attachment raw data itself is being base64-encoded shortly **after** that, making the check for size exceeding nonsensical. Due to the base64-encoding, the size limitation configured may be exceeded in some cases (ticket/attachment sizes just a few bytes lower than limit) by roughly a factor of 4/3 (1.333..), rounded up to the next value divisible by 4 due to the nature of base64. An attachment with a size of 9MB will be roughly 12MB base64-encoded data.

Due to the occurring errors, the ES index seems to be corrupt or missing data, see below discovery related to batch processing during reindex.

### Steps to reproduce the behavior:

* Set `es_total_max_size_in_mb` (and additionally `es_attachment_max_size_in_mb`) to a value like 10.
* Create a ticket with a size slightly below (e.g. 9 MB) - actually, you'd have to create two tickets (one with an attachment which leads to exceeding the size limit of attachments and one which exceeds it in its pure body).
* Start re-index of ES

### Ideas and discoveries
* Fix size estimation to include the base64-encoded final size (raw data + attachment)
* Better: estimate a little bit more due to **metadata** used in the payload - or perform a final size estimation before firing ES requests
* Document `es_total_max_size_in_mb` as it is important for hosted/managed ES services (like AWS) which may have a strict payload size restriction like 10 or 100 MB - the default of 300 (which is super-large) might even be too large.
* Improve resiliency of reindexing, as it continues to process after erroring, but I've observed some strange side effects (other tickets _within_ size restrictions not appearing in search) which I cannot document due to missing logs for this kind of error - this might be related to **batch processing** (e.g. if an item fails in batch processing, the remaining items in this batch will not be indexed).

Yes I'm sure this is a bug and no feature request or a general question.
Thanks in advance.

**Comment by Katalystical** [comment]
Just to give an idea of what happens during reindex, here a redacted log (I had to truncate the lines due to a lot of base64 encoded data clogging the logs):

```
 [...]

 reload Ticket
  - started at 2021-12-21 09:06:52 UTC
W, [2021-12-21T09:06:52.508676 #77-10920]  WARN -- : Scoped order is ignored, it's forced to be batch order.
        100/88950
        200/88950
        300/88950
        400/88950
        500/88950
        600/88950
        700/88950
        800/88950
        900/88950
        1000/88950
        1100/88950
        1200/88950
        1300/88950
        1400/88950
        1500/88950
        1600/88950
        1700/88950
        1800/88950
        1900/88950
        2000/88950
        2100/88950
        2200/88950
        2300/88950
        2400/88950
        2500/88950
        2600/88950
        2700/88950
        2800/88950
        2900/88950
        3000/88950
E, [2021-12-21T09:18:36.255008 #77-10920] ERROR -- : Unable to process post request to elasticsearch URL 'https://<redacted>/zammad_production_ticket/_doc/3045?pipeline=<redacted>

Response:
#<UserAgent::Result:0x000055bd6caf61d8 @success=false, @body="{\"Message\":\"Request size exceeded 10485760 bytes\"}", @data=nil, @code="413", @content_type=nil, @error="Client Error: #<Net::HTTPPayloadTooLarge 413 Request Entity Too Large readbody=true>! [... redacted ...]

Payload:
<redacted>
E, [2021-12-21T09:18:36.271823 #77-10920] ERROR -- : Unable to send Ticket.find(3045).search_index_update_backend backend: #<RuntimeError: Unable to process post request to elasticsearch URL 'https://<redacted> [... redacted ...]

Response:
#<UserAgent::Result:0x000055bd6caf61d8 @success=false, @body="{\"Message\":\"Request size exceeded 10485760 bytes\"}", @data=nil, @code="413", @content_type=nil, @error="Client Error: #<Net::HTTPPayloadTooLarge 413 Request Entity Too Large readbody=true>![... redacted ...]

Payload:
<redacted>

Payload size: 12M>
        3100/88950
        3200/88950

[...]
```

Zammad was configured with `es_total_max_size_in_mb` set to 10 and `es_attachment_max_size_in_mb` to 9 at that time (we experimented with the attachment setting earlier).
We've done a workaround for now reducing `es_total_max_size_in_mb` to **7** to cover things up. (The idea behind it: our limit is 10MB, so we can use roughly 7.5MB of raw data encoded to 10MB base64 and I don't know whether passing a dot would work - and we had to incorporate some excess space for metadata and/or possible header data anyways.
But I think some tickets won't be indexed this way and not be available in search.

**Comment by FSNACM** [comment]
Hi all, 

we have a trouble with missing mails, we tried to reindexing with the command rake searchindex:rebuild but the lost mails isn't still appear after that.

Could i increment payload size? How can i do that?

**Comment by MrGeneration** [comment]
@FSNACM please don't hijack issues with your technical questions. If you have technical questions, use the community instead: https://community.zammad.org

I'm locking this issue now to reduce the uneeded noise.

**Comment by MrGeneration** [comment]
@Katalystical please test this with actual Elasticsearch.
Opensearch is not officially supported. ( https://docs.zammad.org/en/latest/prerequisites/software.html )

**Comment by t-shehab** [comment]
This looks like a faulty configuration to me. The two values for ```es_total_max_size_in_mb``` and ```es_attachment_max_size_in_mb``` do not accumulate. The hard upper limit will always be  ```es_total_max_size_in_mb```. Setting these two values too close together can cause the issue described by OP.

Plus, as said before, OpenSearch is not supported.

Closing for now.
