### ISSUE TITLE
Wrong calculation: Time to escalation

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#390]
I've set up two SLA's as below:

![zammad_sla](https://cloud.githubusercontent.com/assets/3321655/20157673/8691e54c-a6d6-11e6-8bcf-e27da208791e.jpg)

A Ticket with the status "new" has this remaining time to escalation:

![sla_new](https://cloud.githubusercontent.com/assets/3321655/20157711/bd748d94-a6d6-11e6-9ff0-d2dd4e31f052.jpg)

This is roughly 6 days. Talking about "days" that's 144 hours. Assuming that the calendar comes into the game here:

![calendar](https://cloud.githubusercontent.com/assets/3321655/20157748/02431c7e-a6d7-11e6-81f7-f321a8b8cbe6.jpg)

... here we have 12 "working hours" defined per day - my 48 hours would be 4 days here, not 6.

In any way the calculation is not correct ...

**Comment by martini** [comment]
Let's calculate it:

Ticket creation is on 09.11. 23:00

Counting times:
09.11 23:00 -> 48h
10.11 9:00-21:00 -> 48h-12h -> 36h
11.11 -> per default google ical for german holidays/vacation days is used "St. Martin" -> 36h
11.11 9:00-21:00 -> 36h-12h -> 24h
12.11 9:00-21:00 -> 24h-12h -> 12h
13.11 -> per default google ical for german holidays/vacation days is used "Volkstrauertag" -> 12h
14.11 9:00-21:00 -> 12h-12h -> 0h 

-> So I count 6 days until escalation.

-=> Yes, the google ical feed a little bit "casual". So you man need to deactivate not matching 
holidays/vacation days.
<img width="820" alt="screen shot 2016-11-10 at 00 05 39" src="https://cloud.githubusercontent.com/assets/110226/20158226/735b9146-a6d9-11e6-9a56-d80defbda81c.png">

**Comment by jacotec** [comment]
Hmpf, I did not think about holidays which are no holidays 😒

**Comment by martini** [comment]
:)
