### ISSUE TITLE
Ticket updates without articles do provide article variables set

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3902]
### Infos:

* Used Zammad version: 5.0.3/stable
* Installation method (source, package, ..): any
* Operating system: any 
* Database + version: any
* Elasticsearch version: any 
* Browser + version: verified on Google Chrome v96.0.4664.110
* Ticket: #1098529

### Expected behavior:

When updating a ticket without article, the article variables should be empty.

### Actual behavior:

When updating a ticket without article (but with changed objects), Zammad uses the last created article (no matter if from trigger or not) which is an unexpected and invalid behavior.

This is the result:
![image](https://user-images.githubusercontent.com/6549061/147761365-25c32448-8cff-4de5-baf5-3ad7c37580b4.png)

This was the prior trigger based article:
![image](https://user-images.githubusercontent.com/6549061/147761392-2cc2621a-86a4-4494-a6d8-6c18e7d7050d.png)

### Steps to reproduce the behavior:

* configure a trigger like so:
   ![image](https://user-images.githubusercontent.com/6549061/147759086-2c66c48c-c17f-421d-93bf-06d8b13a2316.png)
* update any ticket with a note
* press update without any note but any object (like e.g. priority) being changed
* have a look into your mails

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
We want to handle it with the following solution:

- Add multiple article type variables (e.g. last_article, last_internal_article, last_customer_article, ..., needs to be defined).
- A migration for the current article to last_article, so that we have no breaking change.

**Comment by dominikklein** [comment]
@bolah2009 we defined the following possible variables:

`last_article` (equal the current `article` usage), `last_internal_article`, `last_external_article`, `created_article`, `created_internal_article`, `created_external_article`

**Comment by tschaefer** [comment]
The variables/placeholders `created*article` are only expanded on a ticket modification with a related article. The variables/placeholders `last*article` continually expand to the related last article. That means on a ticket modification with an article, `last*article` is equal to `created*article`.
