### ISSUE TITLE
Tickets dont always get registred from email and content in limbo

### ISSUE THREAD

**Issue by fredrikmagnusson-mf** [zammad/zammad#3907]
### Infos:

* Used Zammad version: 5.0.3
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 18.04.6 LTS
* Database + version: Postgres 10.19
* Elasticsearch version: 7.16.2
* Browser + version: any

### Expected behavior:

*When sending email to Zammad, Zammad should fetch the email and process it (creating ticket, running triggers etc.) and do a +1 for the ticket number.*

### Actual behavior:

*The email gets retrieved in the mailbox (outside Zammad) and Zammad processes the triggers (autoreply for example) but no ticket is created. Both the autoreply to customer gets sent as well as the "New Ticket" notifications to agents gets send, but the link to the ticket does not work and the ticket is nowhere to be found. A search for the ticket id (according to the link) gives no results. Furthermore if I send and email I get the autoreply containg the ticket.Id but no ticket is created. If another person then sends in a email that gets processed correctly, that persons ticket gets the "same" ticket.Id (since no +1 on the ticket number has occured in the database). If we then update this ticket from the GUI, and then the person replies to that via email, that reply does not come into Zammad but the reply gets to the ticket I created(that does not exist) so the only trace of the reply is in our notifications, not in Zammad.

For example:

Test ticket sent to Zammad from me 2021-01-03 09:40. Gets autoreply 09:40 with ticket number 1053. If i do a "Ticket.find(1053) after i have gotten that reply, this does not exist. Ticket Name "Test from IT"

At 10:51 another user sends an email to Zammad, that gets processed and also gets ticket.ID 1053. If I do a "Ticket.find(1053) after this is recived, i get a result from the database. Ticket Name "Something from Customer" However, we get **two** notifications with "New Ticket" where one has 1053 and one has 1054, so the ticket has two IDs but only one in the database. When we reply to the user, the user gets the reply. But when the customer writes back (via email) it sometimes gets sent to "Test from IT" (that does not exist) and sometimes to "Something from Customer"

The same day at 13:33 a user sent in a new ticket, that did get processed correctly and got ticket.ID 1054 (Ticket Name "Else from Customer"), the same as the one above thats in limbo. When today the user replies on that ticket 1054 (Else from Customer) it does not appear on the ticket, but we get an "Updated ticket" notifications with the content and ID 1054, but with the name "Something from Customer" as subject.

### Steps to reproduce the behavior:

*Not every ticket gets this behavior, so I'm not sure where the problem lies.

In the production log at the timestamps matching when the notifications email was received and 10min before it states that there are no emails to be fetched and nothing gets registered. Has happened multiple times the last week.

So there seems to be some form of database issue or sync issue of some sort.

Working on the production log, a lot to filter.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
