### ISSUE TITLE
Ticket Title becomes just a - (dash) after updating ticket

### ISSUE THREAD

**Issue by seljuck** [zammad/zammad#3908]
### Infos:

* Used Zammad version: 5.0.3-7
* Installation method (source, package, ..): docker-compose
* Operating system: Ubuntu 20.04
* Database + version: postgresql (whatever version that docker-compose 5.0.3-7 selects)
* Elasticsearch version: (whatever version that docker-compose 5.0.3-7 selects)
* Browser + version: FireFox 95.02

### Expected behavior:
All tickets should have a Title based on origin. i.e. Email Subject
*

### Actual behavior:
All new tickets have a - (dash) for the title since updating to 5.0.3-7
*

### Steps to reproduce the behavior:
Create or Edit any ticket.
*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
With the provided steps to reproduce I am unable to reproduce this behavior on test systems.
This is most likely an configuration issue on your end, if your unsure and need technical assistance, please consult the community at https://community.zammad.com

*If you're a paying customer, consult support.*

**Comment by seljuck** [comment]
I haven't changed our configuration since our initial setup back in August. The only change is upgrading the docker-compose setup by changing the version to 5.0.3-7 in the .env file. It was working fine until that upgrade. We upgraded from 5.0.2

**Comment by seljuck** [comment]
I've since found the problem. One of our triggers had an action of setting the title to blank. For some reason it was never executing prior to upgrading. I removed the action and now everything is working.

**Comment by skiera6** [comment]
I have similiiar issue, i've noticed that tickets that are send using windows built-in mail get the correct title, but when they come from elsewhere title is set to "-".
