### ISSUE TITLE
Updating user email fails but is updated in ui

### ISSUE THREAD

**Issue by PabloCastellano** [zammad/zammad#3913]
### Infos:

* Used Zammad version: 5.0.x 
* Installation method (source, package, ..): source
* Operating system: Ubuntu 20
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* Failing to update user email results in showing the previous email in the user profile page

### Actual behavior:

* Updating some user email to an email that already belongs to another user, results in a warning popup and the previous page showing incorrect data until you refresh the page.

### Steps to reproduce the behavior:

* Go to any user profile and edit the email
* Set an email that already belongs to another user
* Expect an error message saying `Email address 'xx@xxx.x' is already used for other user.`
* Close the popup
* Check out the email that is shown, it is actually the one you could not set.
* Refresh and the email will come back to normal

**Comment by rolfschmidt** [comment]
Hi @PabloCastellano ,
I was not able to reproduce this issue based on your steps. Would you be kind enough to update your system and check if this issue is still occurs for you?
