### ISSUE TITLE
Bullet Point List with Firefox Browser (inserts text above listing)

### ISSUE THREAD

**Issue by MustafaTongul** [zammad/zammad#3922]
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): Hosted
* Operating system: Any
* Database + version: Any
* Elasticsearch version: Any
* Browser + version: Mozilla Firefox Version 96.0.1 (64-Bit) | Microsoft Windows 10 Version 21H2 (Build 19044.1466)

### Expected behavior:

* When a bullet point list is created, the cursor stays on the same line as the bullet point itself when typing

![image](https://user-images.githubusercontent.com/76220675/149972590-05d49bc8-01b5-407e-bdce-4e711333715c.png)

### Actual behavior:

* When a bullet point list is created, the cursor slides up one line as the bullet point itself when typing

![image](https://user-images.githubusercontent.com/76220675/149972952-51168f18-eeca-4908-9ec5-a344cb279fd0.png)

### Steps to reproduce the behavior:

* Create a bullet point list with CTRL + Shift + L in Zammad and start typing right away

![Das-Krähennest-_96020-Test-Ticket-_11-Mozilla-Firefox-2022-01-18-17-04-50](https://user-images.githubusercontent.com/76220675/149974678-4697470a-6ea6-41b4-943e-a1de1288825b.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
I'm able to reproduce it on plain `contenteditable` div with FF 96.0.1 on mac too.

![content-editable-plain](https://user-images.githubusercontent.com/110226/149975664-d4e8c42a-a051-4a9f-90c7-fa845c9f0aaa.gif)

<img width="812" alt="Screenshot 2022-01-18 at 17 08 30" src="https://user-images.githubusercontent.com/110226/149975768-facac68a-3a21-426a-8195-cde74ec8bae2.png">

So for me it looks like an firefox issue *unfortunately*.
