### ISSUE TITLE
Title column is missing if ticket number is disabled in overview options

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#3943]
### Infos:

* Used Zammad version: 5.0.3 (latest patch from yesterday)
* Installation method (source, package, ..): source
* Operating system: Ubuntu 20.04.3
* Database + version: newest
* Elasticsearch version: 7.17.0
* Browser + version: Edge 97

### Expected behavior:
Column visible
*

### Actual behavior:
If I uncheck the "#" column, the title column is removed too.
*

### Steps to reproduce the behavior:
![Animation](https://user-images.githubusercontent.com/1473674/152135828-63aaf9e4-19d7-4df6-b917-174891772776.gif)

**Comment by MrGeneration** [comment]
Please note that this bug can only be reproduced if you only have `#` and `title` selected and then deselect `#`.
Please try to be as precise as possible, I only happened to guess from what I could see.

This may cause in invalidly closed issues or unnecessary questions back.

**Comment by Dennis1993** [comment]
I only selected one column. In mobile view I can't see anythings, because all columns are wrapped with ...

Here the complete config:
![Unbenannt-1](https://user-images.githubusercontent.com/1473674/152140423-fbf9fbab-563a-475f-9d73-04a039f65474.png)

Thanks!
