### ISSUE TITLE
Auto-assign ticket owner on first reply

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#395]
I'd like the option that the first agent, who sends an answer to the customer on a new ticket, gets auto-assigned to the ticket in case there is no assignment yet.

This would prevent to forget to manually select the assignment in the menu bar in addition to the answer.

If an assignment is already done it should not be changed by further responses of other agents.

**Comment by thorsteneckel** [comment]
Hi @jacotec - Thanks for your proposal. Do I get you right:

If opening a ticket in the detail view that is new/has yet no owner the owner selection should be automatically set to yourself / the current agent. This will automatically set the owner for responses and saves some clicks. Additionally it will keep the possibility to any other agent or reset to no agent - if you / the current agent wants to inform all agents of the group about his reply.

**Comment by monotek** [comment]
Imho autoasign only should take place after sending an answer to the customer and not when agent reads the ticket.

**Comment by jacotec** [comment]
Hi @thorsteneckel ,

nearly ;-)

The auto assignment of the owner should not be done when opening the ticket (otherwise you can't just open to read without being assigned!)

The auto assignment would be useful in this case:

- The ticket has no owner yet
- The agent **replies to the customer** (just an internal note will not assign it!)
- The agent sends out his reply to the customer by the "update" button. (That's the point where the assignment triggers. If the agent has assigned someone else during that action, the selected assignment would be used)

This would prevent from answered tickets being unassigned to an owner.

**Comment by jacotec** [comment]
@monotek Exactly! You've been 33 seconds faster ;-)

**Comment by thorsteneckel** [comment]
Yes, thats what I meant. Just preselected with the change indication next to the field. Thanks!

**Comment by jacotec** [comment]
For now I'm doing it with a Macro (Close and send). This assigns the ticket to the agent and closes it. But the auto assignment as stated above would be generally useful as any answer from the customer will directed back to the agent who wrote the reply by default. Otherwise if the agent does not assign itself it'll run into the group globally.

**Comment by olivergrahl** [comment]
Hmm, so I tried to work around this with a trigger, but I probably don't understand how triggers work, as it has no effect at all?

![grafik](https://cloud.githubusercontent.com/assets/4621219/20622264/4ce2f88a-b302-11e6-9957-286cdc11cdf4.png)

**Comment by Taps7734** [comment]
GMTA... I tried the same trigger (I think.  I tried it in English, but I believe we used the same options) and it also did nothing.

Any help on this?

![image](https://cloud.githubusercontent.com/assets/17859116/21363704/c00a134e-c6bb-11e6-891b-881df4d8d56e.png)

**Comment by olivergrahl** [comment]
Okay, basically, I need two triggers: one to assign the ticket to the current agent, when the agent posts a reply and the ticket had not been assigned yet. And another trigger to close the ticket immediately after an email reply.

Looking at the Trigger source, I found out that adding a condition like "Article.Type=*" (* means: select all types, or just Email if you want to auto-assign on sending an email reply) will at least make the trigger execute. 

The rule of thumb is: If you want to build a trigger that triggers on adding an article (and does not watch for any attribute changes), than you need to include at least one Article related condition. 

It works well with setting the ticket Status:
![grafik](https://cloud.githubusercontent.com/assets/4621219/21807299/52e09b4c-d73e-11e6-8be2-62f8217bdd40.png)

But it doesn't consistently work with setting the ticket Owner, at least not in Zammad 1.1.1. It works on the develop branch, though. At least sometimes... Hope I can find out more soon. 
![grafik](https://cloud.githubusercontent.com/assets/4621219/21807274/3fe92932-d73e-11e6-8d93-bfb81dbb97c9.png)

**Comment by olivergrahl** [comment]
Okay, here's how I far I got with this:

**Any trigger configured to perform "Set Owner to Current User" will never have any effect at all.**

trigger.perform looks like this:
```
  ticket.owner_id: 
    elements:
      pre_condition: current_user.id
      value: ''
      value_completion: ''
```

And in `models.ticket.rb`, `perform_changes()`, I found out that only `value` gets written:
`self[attribute] = value['value']`

**This means that no trigger perform actions that make use of `pre_condition` can ever be effective.**

So, I thought one could add
```
        trigger.perform.each do |key, value|
          next if !value['pre_condition']
          if value['pre_condition'] == 'current_user.id'
            value['value'] = original_user_id
          end
        end
```
in `models.trigger.rb` before calling `ticket.perform_changes()`.

But it turns out that `original_user_id` is `nil` at this time, and I have no idea why, as I really don't have the knowledge to dive deeper into this, unfortunately... **Any ideas, anyone?**

**Comment by martini** [comment]
Hi to all,

thanks for wonderful work out of the behaviour. @olivergrahl adopted your changes (thanks for the hint). It's available in master branch/packages (will get in stable ASAP).

I created many test cases for it (and related issue like #779, #386, #298 ). Works fine. Feedback is welcome!

 -Martin

To get more understanding how triggers work I created a little description. Feedback to this would be also great! https://github.com/zammad/zammad-documentation/blob/master/admin-trigger.rst

**Comment by martini** [comment]
Available in stable branch/packages.

**Comment by olivergrahl** [comment]
Perfect! :-) So much appreciated. Currently on travel, but will be the first thing I try when back.

**Comment by jacotec** [comment]
Works for me with the trigger, that's awesome! Thanks a ton!
