### ISSUE TITLE
Notifications are sent for all tickets when an organization of a customer is updated

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#3952]
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: 1099545

### Expected behavior:

If an Organisation is edited from a customer, the agents should not receive any E-mail notification for closed tickets.

### Actual behavior:

If an Organisation is edited in a customer profile, the agents receive a e-mail notification for every ticket that the customer has.
It does not make any difference if the ticket is closed or open.

### Steps to reproduce the behavior:

1. Customer Nr.1 opens ticket Nr.1

2. Agent Nr.1 sets himself as the owner of ticket Nr.1 and has his email notifications turned on in his personal settings.

3. Agent Nr.2 now changes the organization of customer Nr.1

4. Email notification is sent to agent Nr.1 (the organization of the ticket has changed)

5. Note: If multiple agents have set their preferences to receive email notifications for ticket Nr.1 when an update occurs, they will also receive email notifications about the change in the organization of the ticket.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by fliebe92** [comment]
Hey @Bozo0511, hey @mantas,

after checking this issue we need your help :)

Do we want to disable ticket notifications in general for all closed tickets or just for this specific case which is described in this report?

Thanks for your support!

**Comment by MrGeneration** [comment]
Zammad currently notifies all affected agents depending on the notification configuration of tickets whose customers organization has been updated.
This creates a heckton of noise.

**Comment by fliebe92** [comment]
Thanks for the input, we decided to turn off notifications for the case that an organization of a customer is updated. This will avoid the noise which is currently created by doing this.
