### ISSUE TITLE
Regression of #2102: Read-only custom objects

### ISSUE THREAD

**Issue by thpoul** [zammad/zammad#3953]
### Infos:

* Used Zammad version: 5.0.3 (5.0.3-1643716628.f44a1a2b.focal)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* https://github.com/zammad/zammad/issues/2102

### Actual behavior:

* Read only doesn't appear.
![image](https://user-images.githubusercontent.com/1605817/152795428-96b41fb1-a90c-4bb4-9c71-70178611e563.png)

### Steps to reproduce the behavior:

* Simply try adding a new custom object and notice the **view** permission not available 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Hi @thpoul ,

this should be possible now. Please create a new text field and show it in the screens you need. If you want to disable the editing of the field for the customer interface then you can create a core workflow to do this:

![grafik](https://user-images.githubusercontent.com/5445062/154227953-3e2c7447-032d-4af5-8395-3319aff1493b.png)

The view field was never intended to show fields read only. In agent context it is used to show up a field in the ticket overview. Please let me know if this solves your issue or provide more information what you are missing.

**Comment by thpoul** [comment]
Works perfectly! Thank you very much :)
