### ISSUE TITLE
Opening organization views throws console traces

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3958]
### Infos:

* Used Zammad version: develop / 5.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Opening organisation detail views in Zammad does not throw console errors or tracebacks.

### Actual behavior:

Opening any organization, no matter if without, inactive or all active members does throw tracebacks:

![image](https://user-images.githubusercontent.com/6549061/153206144-b927b194-3a32-4712-b80d-f10f6065bb0d.png)
![image](https://user-images.githubusercontent.com/6549061/153206134-91e2f180-55d8-417d-8bb0-6ba957e58a99.png)

### Steps to reproduce the behavior:

* open any organization
* you can even newly create it. it doesn't matter.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
related https://github.com/zammad/zammad/commit/8dd045af75fa2370875cb29a73c6b3251ab84761
