### ISSUE TITLE
Unable to add Microsoft 365 account when admin consent for enterprise applications is enabled

### ISSUE THREAD

**Issue by tbsfnk** [zammad/zammad#3963]
### Infos:

* Used Zammad version: 5.0
* Installation method (source, package, ..): deb
* Operating system:
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:
Adds Account to zammad once the application is approved by an admin

### Actual behavior:
The "Approval required" prompt keeps appearing even if the application has all permissions approved by an admin
![image](https://user-images.githubusercontent.com/33467318/153863861-8b2019c0-3606-4dcd-a3e3-8374c689a65d.png)

### Steps to reproduce the behavior:
- Enable Admin consent for enterprise applications in Azure
- create application for zammad and set it all up
- then try to add the account in zammad

I found out that it is working if you delete the "**_&prompt=consent_**" part of the request URL:
https://login.microsoftonline.com/{TENEANTID}/oauth2/v2.0/authorize?access_type=offline&client_id={ID}&prompt=consent&redirect_uri=...

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
