### ISSUE TITLE
Elasticsearch Status Signal lost issue

### ISSUE THREAD

**Issue by gopi527** [zammad/zammad#3966]
root@Zammed:/# sudo systemctl status elasticsearch
Warning: The unit file, source configuration file or drop-ins of elasticsearch.service changed on disk. Run 'systemctl daemon-reload' to reload units.
● elasticsearch.service - Elasticsearch
     Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Wed 2022-02-16 12:10:10 UTC; 19min ago
       Docs: https://www.elastic.co
    Process: 33649 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (code=killed, signal=KILL)
   Main PID: 33649 (code=killed, signal=KILL)
-------------------------------------------------------------------------------------------------------------------------------

Hi there - thanks for filing an issue. Please ensure the following things before creating an issue - thank you! 🤓

Since november 15th we handle all requests, except real bugs, at our community board.
Full explanation: https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21

Please post: 
- Feature requests
- Development questions
- Technical questions

on the board -> https://community.zammad.org !

If you think you hit a bug, please continue:
- Search existing issues and the CHANGELOG.md for your issue - there might be a solution already
- Make sure to use the latest version of Zammad if possible
- Add the `log/production.log` file from your system. Attention: Make sure no confidential data is in it!
- Please write the issue in english
- Don't remove the template - otherwise we will close the issue without further comments
- Ask questions about Zammad configuration and usage at our mailinglist. See: https://zammad.org/participate

Note: We always do our best. Unfortunately, sometimes there are too many requests and we can't handle everything at once. If you want to prioritize/escalate your issue, you can do so by means of a support contract (see https://zammad.com/pricing#selfhosted).

* The upper textblock will be removed automatically when you submit your issue *
-->

### Infos:

* Used Zammad version: latest
* Installation method (source, package, ..): package
* Operating system: ubuntu 20.04
* Database + version: mariadb  10.3
* Elasticsearch version:
* Browser + version: edge

### Expected behavior:

*

### Actual behavior:

*

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by gopi527** [comment]
Unable to process GET request to elasticsearch URL 'https://64.227.169.94:9200/zammad_production_ticket/_doc/_search'. Elasticsearch is not reachable, probably because it's not running or even installed.

Response:
#<UserAgent::Result:0x000056217df40b60 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP connection to 64.227.169.94:9200 (Connection refused - connect(2) for \"64.227.169.94\" port 9200)>", @header=nil>

Payload:
{"query":{"bool":{"must":[{"range":{"created_at":{"from":"2021-12-31T18:30:00Z","to":"2022-12-31T18:29:59Z"}}}],"must_not":[{"term":{"state.name.keyword":"merged"}}]}},"size":0,"aggs":{"time_buckets":{"date_histogram":{"field":"created_at","interval":"month","time_zone":"Asia/Calcutta"}}},"sort":[{"updated_at":{"order":"desc"}},"_score"]}

Payload size: 0M

**Comment by gopi527** [comment]
Unable to process GET request to elasticsearch URL 'https://localhost:9200/zammad_production_ticket/_doc/_search'. Elasticsearch is not reachable, probably because it's not running or even installed.

Response:
#<UserAgent::Result:0x000056217df40b60 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for \"localhost\" port 9200)>", @header=nil>

Payload:
{"query":{"bool":{"must":[{"range":{"created_at":{"from":"2021-12-31T18:30:00Z","to":"2022-12-31T18:29:59Z"}}}],"must_not":[{"term":{"state.name.keyword":"merged"}}]}},"size":0,"aggs":{"time_buckets":{"date_histogram":{"field":"created_at","interval":"month","time_zone":"Asia/Calcutta"}}},"sort":[{"updated_at":{"order":"desc"}},"_score"]}

Payload size: 0M

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
