### ISSUE TITLE
Webhook follows redirect (HTTP code 302) but cuts off redirect URL

### ISSUE THREAD

**Issue by tobimeu** [zammad/zammad#3968]
### Infos:

* Used Zammad version: 5.0.x 
* Installation method (source, package, ..): hosted by Zammad
* Operating system:
* Database + version:
* Elasticsearch version:
* Browser + version: Chrome Version 98.0.4758.82 (Offizieller Build) (64-Bit)

### Expected behavior:

Webhook sends a POST-Request to endpoint URL and receives HTTP status code 302 (Moved Temporarily). 
Response:
```
content-type: text/html; charset=UTF-8
access-control-allow-origin: *
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: Mon, 01 Jan 1990 00:00:00 GMT
date: Thu, 17 Feb 2022 09:44:40 GMT
location: https://script.googleusercontent.com/macros/echo?user_content_key=RRaI_HjnMoj1f2ZMawgFSwOn0ddVX4stu0pAks6qm-ulmhPk7ysinvUy6Es-ZnY5H86kd1BNmGD-3I5G1gv4aZC62_AIxGNFm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnDfHDNxphgop-0WtPtMcMF623SAsZqccoonoCZ3CIgyCpFDMa5yD-B3Y_83vvcBbMnUfm-fKoiAzmYf5c6_1psYcGBIf3wsz-Nz9Jw9Md8uu&lib=MKquNk0NIOx7Ij-a9nJX-yyjZhq9n8zXr
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
content-security-policy: frame-ancestors 'self'
x-xss-protection: 1; mode=block
server: GSE
alt-svc: ...
connection: close
transfer-encoding: chunked
<HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A HREF="https://script.googleusercontent.com/macros/echo?user_content_key=RRaI_HjnMoj1f2ZMawgFSwOn0ddVX4stu0pAks6qm-ulmhPk7ysinvUy6Es-ZnY5H86kd1BNmGD-3I5G1gv4aZC62_AIxGNFm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnDfHDNxphgop-0WtPtMcMF623SAsZqccoonoCZ3CIgyCpFDMa5yD-B3Y_83vvcBbMnUfm-fKoiAzmYf5c6_1psYcGBIf3wsz-Nz9Jw9Md8uu&amp;lib=MKquNk0NIOx7Ij-a9nJX-yyjZhq9n8zXr">here</A>.
</BODY>
</HTML>
```
Then, Zammad sends Request to redirect URL.

### Actual behavior:

The URL of the second request is cut off:
```
URL   https://script.googleusercontent.com/macros/echo?user_content_key=RRaI_HjnMoj1f2ZMawgFSwOn0ddVX4stu0pAks6qm-ulmhPk7ysinvUy6Es-ZnY5H86kd1BNmGD-3I5G1gv4aZC62_AIxGNFm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnDfHDNxphgop-0WtPtMcMF623SAsZqccoonoCZ3CI
Method	GET
Status	400
Request	
accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
accept: */*
user-agent: Zammad User Agent
host: script.googleusercontent.com
x-zammad-trigger: Instandhaltung
x-zammad-delivery: ...
content-type: application/json
connection: close
content-length: 7876
...
````
The webhook endpoint does obviously not exist (because it was cut off); Zammad receives error code 400 and tries to fire the webhook several times again. 

### Steps to reproduce the behavior:

1. Fire webhook to a server that replies with code 302 and a redirect URL as long as shown above. 
2. Check response to the second request. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by tobimeu** [comment]
Thanks for the quick reply. I think it is a bug that the provided redirect URL is not used completely but cut off by the webhook client.

**Comment by MrGeneration** [comment]
This is a duplicate of #3671 
I personally think that 360 characters of endpoint are quite a lot.

That being said: The HTTPLog is being cut, the call is not.
