### ISSUE TITLE
Frequent “Lost connection to MySQL server during query” errors resulting in client-side Error 500

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#3969]
### Infos:

* Used Zammad version: 5.0.3
* Installation method (source, package, ..): Docker Swarm
* Operating system:
* Database + version: MySQL 5.7.37
* Elasticsearch version: n/a
* Browser + version: FF 97.0 (64-Bit)

### Expected behavior:

Being able to leave app open in the browser in idle without getting errors when returning to it.

### Actual behavior:

Getting Error 500 after 10-30 minutes in idle.

### Steps to reproduce the behavior:

Note that - just to reproduce this issue - I run `zammad/zammad` with a custom entrypoint and command in order to replace `postgres` with `mysql`. Yes, it would have been way easier to track this down and reproduce having a `mysql` variant of `zammad/zammad`.

```bash
docker swarm init

cat <<EOF | docker stack deploy --compose-file - zammad 
version: '3.4'

networks:
  test:

services:
  mysql:
    image: 'mysql:5.7.37'
    command: --character-set-server=utf8 --max_allowed_packet=256M
    deploy:
      restart_policy:
        condition: any
    environment:
      - 'MYSQL_RANDOM_ROOT_PASSWORD=true'
      - 'MYSQL_USER=zammad'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_DATABASE=zammad'
    networks:
      - test

  zammad:
    image: 'zammad/zammad:5.1.0-335'
    command: "-c \"set -x; apt-get update && apt-get install -y --no-install-recommends ruby-mysql2 && cd /opt/zammad && sed -i 's#mysql#postgres#' /usr/local/bundle/config && bundle install && sed -i -e 's#.*adapter:.*#  adapter: mysql2#' -e 's#.*password:.*#  password: secret#' -e 's#.*host:.*#  host: mysql#' /opt/zammad/config/database.yml && sed -i 's#.*postgres.*##i' /docker-entrypoint.sh && sed -i 's#.*done##' /docker-entrypoint.sh && sed -i 's#.*elasticsearch.*##i' /docker-entrypoint.sh && service redis-server start && bundle exec rake db:migrate && bundle exec rake db:seed && /docker-entrypoint.sh zammad\""
    deploy:
      restart_policy:
        condition: any
    entrypoint: /bin/bash
    networks:
      - test
    ports:
      - target: 80
        published: 8088
EOF
```

* Open http://localhost:8088 in the browser and walk through initial setup steps (Create, Next, Next, Skip)
* Get to overview containing the "Welcome to Zammad" ticket. Click ticket to verify it "works". Close ticket view. 
* Wait 10-30 minutes.
* Click "Welcome to Zammad" ticket again.
* Zammad now displays various Error 500 messages. 
* After full refresh in the browser, all is fine again for 10-30 minutes, until the same as above happens again.

`docker service logs zammad_zammad` now contains:
```
I, [2022-02-18T09:41:45.560205 #896-178580]  INFO -- : Started POST "/api/v1/recent_view" for 10.255.0.2 at 2022-02-18 09:41:45 +0000
F, [2022-02-18T09:41:45.568291 #896-178100] FATAL -- :
[50fbce82-c4f8-40c7-89a1-3b81b02454fe] ActiveRecord::StatementInvalid (Mysql2::Error::ConnectionError: Lost connection to MySQL server during query):
[50fbce82-c4f8-40c7-89a1-3b81b02454fe]
[50fbce82-c4f8-40c7-89a1-3b81b02454fe] config/initializers/db_preferences.rb:15:in `block in <main>'
```

After further investigation, it appears that this line is causing the problem:
https://github.com/zammad/zammad/blob/24c3bdfd8748874cb5f16c4e618cf78cded47743/config/initializers/db_preferences.rb#L13

Changing `:before` to `:after` seems to fix it.

To verify, include `sed -i 's#:before#:after#' /opt/zammad/config/initializers/db_preferences.rb` as below:

```bash
docker stack rm zammad

cat <<EOF | docker stack deploy --compose-file - zammad 
version: '3.4'

networks:
  test:

services:
  mysql:
    image: 'mysql:5.7.37'
    command: --character-set-server=utf8 --max_allowed_packet=256M
    deploy:
      restart_policy:
        condition: any
    environment:
      - 'MYSQL_RANDOM_ROOT_PASSWORD=true'
      - 'MYSQL_USER=zammad'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_DATABASE=zammad'
    networks:
      - test

  zammad:
    image: 'zammad/zammad:5.1.0-335'
    command: "-c \"set -x; apt-get update && apt-get install -y --no-install-recommends ruby-mysql2 && cd /opt/zammad && sed -i 's#mysql#postgres#' /usr/local/bundle/config && bundle install && sed -i 's#:before#:after#' /opt/zammad/config/initializers/db_preferences.rb && sed -i -e 's#.*adapter:.*#  adapter: mysql2#' -e 's#.*password:.*#  password: secret#' -e 's#.*host:.*#  host: mysql#' /opt/zammad/config/database.yml && sed -i 's#.*postgres.*##i' /docker-entrypoint.sh && sed -i 's#.*done##' /docker-entrypoint.sh && sed -i 's#.*elasticsearch.*##i' /docker-entrypoint.sh && service redis-server start && bundle exec rake db:migrate && bundle exec rake db:seed && /docker-entrypoint.sh zammad\""
    deploy:
      restart_policy:
        condition: any
    entrypoint: /bin/bash
    networks:
      - test
    ports:
      - target: 80
        published: 8088
EOF
```

I have to admit that I don't really understand what's going on here, maybe some kind of race condition. Executing a statement in `Mysql2Adapter.set_callback :before` is possibly not a good idea.

Let me add that I was able to reproduce the issue on two different machines. I have not been able to reproduce it using just `docker run ...` instead of Docker Swarm as above. Maybe some differences in Docker's networking are playing a role here. I don't understand enough of all this to explain, though.

Another possible workaround could be to remove the `Mysql2Adapter.set_callback` code from the db initializer alltogether, and use `ActiveRecord::Base.transaction(isolation: :read_committed) do` in 
https://github.com/zammad/zammad/blob/24c3bdfd8748874cb5f16c4e618cf78cded47743/app/models/transaction.rb#L14

I have not tried it, though, and I cannot verify if this or my workaround above (using `:after` instead of `:before`) still works in the way it should in terms of the reason for the statement being added in [82b61e4](https://github.com/zammad/zammad/commit/82b61e4811fc94650e7ef00e9afc318ac1e642de).

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Hi @olivergrahl ,

thank you very much for this detailed bug report 💯 I will check if the change has any side effects and change to the `:after` hook if I don't see any problems.

**Comment by MrGeneration** [comment]
Zammad doesn't like it at all to loose it's database server during it's runtime.
There may be situations where this can lead into a non or half functioning instance.

I haven't seen this behavior on package installations yet, it may be specific to your environment if we're unlucky.

**Comment by rolfschmidt** [comment]
There should be no problem to put this in the `:after` hook. It does not matter for the initial bugfix. It is still early enough to put the db in the state for controller transactions etc.

**Comment by olivergrahl** [comment]
You guys are fast! 👍
