### ISSUE TITLE
Exchange integration requires OAuth instead of basic authentication

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#3971]
### Infos:

* Used Zammad version: any
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: 10112090

### Expected behavior:

* Sync address book from Exchange to Zammad.

### Actual behavior:

* Microsoft disabled basic authentication in Office 365 environment and made OAuth mandatory.

![image](https://user-images.githubusercontent.com/97293098/155171784-1b59d947-3af1-44f3-bba5-89dfbadcb558.png)
_Source: https://docs.microsoft.com/en-us/lifecycle/announcements/exchange-online-basic-auth-deprecated_

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
The task is kinda stuck.

We did some research on the topic and generally there are 2 parts of information we need to get after the migration to graph API.

1) Personal contacts. This is already possible:

https://developer.microsoft.com/en-us/graph/graph-explorer

`https://graph.microsoft.com/v1.0/me/contacts`

and folders:

`https://graph.microsoft.com/v1.0/me/contactFolders`

2) Organization contacts. Currently we were not able to get them via API. There is an API endpoint for it:

`https://graph.microsoft.com/v1.0/contacts`

which does not return the result properly. At the moment we are not able to get the same result like the old gems in our repo. There are also discussions that these API may be WIP and beta and provide not the data we need yet:

https://stackoverflow.com/a/48748814

---

Also important to note is that the integration does not even work for all exchanges anymore for a couple of years: https://github.com/zammad/zammad/issues/1702 

This error message is currently always occurring in our tests which also disallow to see the current state of the old implementation.

However we many hosted systems which are using the exchange integration and there must be a missing puzzle piece to get this working.

(I have a list of customers which are using exchange if any dev need configuration examples)

**Comment by tschaefer** [comment]
Last Microsoft [announcement](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-september/ba-p/3609437).

**Comment by dominikklein** [comment]
Side note: The old basic authentication needs still to work, for example for old on-premise exchange installations.

**Comment by fliebe92** [comment]
After some more research, we will split up this into more tasks.
