### ISSUE TITLE
add 1.0.1 tag to develop branch to get properly named packager.io packages

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#398]
Currently packages created by packager.io from develop branch have version 0.1.8 in the name.
Therefore you cant install them over the existing 1.0.0 packages.
Please add tag 1.0.1 to get properly named packages.

**Comment by jacotec** [comment]
What happens with new builds within the develop branch? Let's say I've installed the dev repo which is 1.01 ... two hours later a bug is fixed and compiled into the dev package. Version is still 1.01, but it's just a newer build. Will yum recognize this or just say "no updates" as the version tag is still the same?

**Comment by monotek** [comment]
It will install without problems because you also have a ascending number behind the version number. 

Packagename looks like: zammad_0.1.8-1478945977.715e658.xenial_amd64.deb

**Comment by martini** [comment]
@monotek what if we work on 1.1 in develop... so we need to change the tag then? What if we want a Nightly-Build for release 1.0 and for release 1.1?

For me it sounds this way better (any feedback is welcome!):
1) we create stable-1.0, stable-1.1, ... branches where all bugfixes and tags are in
 -> If we fix a issue, a new commit is in there directly
 -> We build packages in this stable-* branch automatically on any commit
      -=> This would be our Nightly-Build for stable release with all fixes

2) If we release a 1.0.1 or 1.0.2 is added a tag to this stable-* branch and push it on a package-1.0 branch.
 -> We build packages in this branch automatically on any commit (here all at once at release time)
      -=> This would be our Stable-Build for stable release with all fixes

# Summary for Zammad Git Branches and Packages

## Features:
* Nightly-Build for each version tree
* Release-Build for each version tree
* no smashup if we work on new features for unreleased released 

## Inventory:
* develop and master branch for new releases (unreleased versions)
* stable-* (e. g. stable-1.0, stable-1.1, stable-* with all bugfixes in realtime
  -> build automatically packages at any push (if a bug got fixed)
* package-* (e. g. package-1.0, package-1.1, package-* with all bugfixes at release time
  -> build automatically packages at any push (one push from stable-* tree at release time)

**Comment by monotek** [comment]
Yes, this sounds even better!
Lets do it this way! :-)

**Comment by jacotec** [comment]
Das klingt grundsätzlich gut!

Aber warum wollt ihr es euch antun, dass die Benutzer bei jedem Major Release (1.0.x -> 1.1 etc.) die Repos updaten?

Warum nicht ein genereller "Release"-Zweig und einen generellen "Develop"-Zweig?

**Comment by monotek** [comment]
Auch wieder wahr...

**Comment by jacotec** [comment]
Ich sehe Martin war schon aktiv. Viel aufgeräumter so, und das "yum update" über meine aktuelle RPM-Installation hat auch geklappt. Daumen hoch! Das mit dem Repowechsel bei einem Major Update könnt Ihr ja nochmal überdenken. ;-)

**Comment by monotek** [comment]
@martini
I also see the problem mentioned by @jacotec.
Renaming repos is a pain in the ass for the user.

Imho its better have only "master" and "develop" branches and setting version tags inside these branches. If a new version is released via the GitHub function the version tag is automatically set. 

So the next release would be 1.0.1 i guess?
If so we set 1.0.2 in develop by hand after this release.

All packages build from commits in develop are getting version 1.0.2.
These packages are the nightly builds with all new bugfixes.

If we want to have packages for version 1.1.x this could be a new branch "develop-1.1".

After finishing work in develop-1.1 the branch can be merged to develop and after that deleted.

Btw.... Imho the following very old branches could also be deleted:
* feature/enableUploadDelete
* interface
* interface-v2
* pkgr
* testing

If we would do it like mentioned above these branches are also kind of useless:
* package-0.9
* package-1.0
* pkg
* stable-0.9
* stable-1.0

**Comment by martini** [comment]
I understand. But then it would not be possible to have 1.0.x and 1.1.x releases. So no package/rpm/deb user can stay on 1.0 until the user really want to got with 1.1 or 1.2.

Also no bugfix release for 1.0.x would be installable because first 1.1.x package get's installed automatically. 

-> You would force everybody to upgrade to 1.1 if available. Any comments?

**Comment by jacotec** [comment]
If a user decides for the release branch, and the tested release jumps from 1.0.x to 1.1.0 ... I don't see any real reason for a user to stay on the old 1.0.x tree and miss updates and new functions.

If 1% of the users want to stay with 1.0.x, let **them** disable their repo, preventing further updates. Otherwise 99% of the users need to change their repo file to the new branch ;)

Do you really plan to back port fixes from a stable 1.1.x to an old 1.0.x tree?

**Comment by martini** [comment]
Yes. We will maintain bugfixes for each release tree (1.0.x, 1.1.x, ...).

So should we have packages for 1.0.x, 1.1.x and for "stable" (wich is current stable, e. g. 1.1 after 1.1 got released) in general?

**Comment by jacotec** [comment]
That could be an option unless the administration work for this isn't too high.

**Comment by monotek** [comment]
So we would have the master branch which would be the stable branch and we have a branch for every major version in which we fix bugs and get "nightly" builds from?

**Comment by martini** [comment]
One more branch:

- develop (current unreleased development state - unstable)
- master (current unreleased development state - stable)
- stable (current stable release with bugfixes e. g. 1.0.1, 1.0.2, 1.1.0 if available - new packages on push)
- stable-1.0 (1.0 release with bugfixes e. g. 1.0.1, 1.0.2 - new packages on git push)
- stable-1.1 (1.1 release with bugfixes e. g. 1.1.1, 1.1.2 - new packages on git push)

Any comments?

**Comment by jacotec** [comment]
Looks good.

What is your plan to decide between develop and master?

**Comment by monotek** [comment]
Master, being a stable development branch, sounds confusing to me. How can development branch be stable?

Master and stable is the same to me.

**Comment by martini** [comment]
> What is your plan to decide between develop and master?

develop: is the first instance where all feature and bugfix branches are merged - this branch will have some issues all the time - no use for production

master: is the the branch where features work correctly - could be used for experienced users for production

> Master and stable is the same to me.

The main difference here would be, that in master are unreleased features (functions can change - documentation may not be complete). Stable is only with released features (functions will not change, feature is announced).

**Comment by monotek** [comment]
When is the point features are going from develop to master? How are the features tested? Just by ci?

I think we should put these infos in the docs :-)

**Comment by martini** [comment]
develop -> master: would be after the merged feature branch is working well in develop (tested by ci).

Yeah! Docs would be good!

**Comment by monotek** [comment]
I'll do it tomorrow.

Are we tagging the develop branch with an higher version than master anyway? If not we have still the problem that packager.io packages are version 0.1.8 ant can't be used for testing after installing a stable version.

**Comment by martini** [comment]
Ok. I'll tag it.

**Comment by monotek** [comment]
So develop will be next major release (1.1.0) and master next minor release (1.0.1)?

What are the feature differences between 1.0.1 and 1.1.0?

**Comment by martini** [comment]
1.0.1 == current version + bugfixes of last 3 weeks
1.1.0 == bugfixes of last 3 weeks + official availability of REST API + OAuth2 Support + PHP&Ruby Libs + sipgate.io integration + Slack integration + Domain based organization assignment

-> I'm not sure which tags to set on develop/master. I do it like you want (like you wrote).

**Comment by monotek** [comment]
What I want does not necessarily make the most sense ;-)

Do we reach the goal of having 1.0.x and 1.1.x nighties with this or do we also need develop-1.0 and develop-1.1 branches?

Not sure if I forget something?

I would prefer not having more branches as it's getting harder to maintain a lot of branches I guess.

How many major versions should be supported (getting backported fixes) at the same time?

**Comment by martini** [comment]
We should have stable, stable-1.0 and stable-1.1 nighties by today.

Yes, less branches (no develop-*...).

Maintained versions: I would say, last three feature versions. Any feedback?

**Comment by monotek** [comment]
So at the moment this would be 1.0, 1.1 and 1.3.?
OK, sounds good.

Ho do we take care of merging/backporting fixes to all branches?
Any way to automate it?

If people like to do pull requests which base branch should they use?
I think merging fixes from 1.0 to 1.1 and vice versa could be confusing over time.
So maybe using develop (next major) would be best?
What do you think?

**Comment by martini** [comment]
By the way, it's a fruitful discussion! :)

I try to summarise it, we have the following branches:
- develop (current unreleased development state - unstable)
  - is the first instance where all feature and bugfix branches are merged 
  - this branch will have some issues all the time - no use for production
- master (current unreleased development state - stable)
  - is the the branch where features work correctly
  - could be used for **experienced** users for production
- stable (current stable release with bugfixes e. g. 1.0.1, 1.0.2, 1.1.0 if available - new packages on push)
  - *production ready*
  - default packages repo
  - users will get upgraded to new 1.x release as soon as available

Plus, for people who want to stay on a certain stable release level:
- stable-1.0 (1.0 release with bugfixes e. g. 1.0.1, 1.0.2 - new packages on git push)
- stable-1.1 (1.1 release with bugfixes e. g. 1.1.1, 1.1.2 - new packages on git push)

We will maintain bug and security for latests 2 stable branches.

Feedback is welcome!

@monotek @jacotec One is not cleat to me. What version should develop and master branch have? In case Zammad 1.1 latest release. develop 1.1.99 and master 1.1.98 (because develop it's ahead master and master is ahead stable)?

**Comment by monotek** [comment]
As i understand master would be current stable with fixes (at the moment should be 1.0.1).
Development is next majo release (so it should be 1.1.0)

I just created a "Contributing / Development" section in the docs.

https://docs.zammad.org/en/latest/contributing-start.html

I put also the branches info there. Please have a look if its OK like this.

**Comment by jacotec** [comment]
@martini I copy @monotek !

Master and Dev should have the version which becomes stable next ... so currently 1.0.1. No subversions like .99 and .98, so only the build number determines which is newer. This would allow jumps between master and develop.

Also if you'd use i.e. 1.1.99 for the dev branch, you'd never be able to jump from 1.0.1 dev to 1.0.2 stable ;-)

**Comment by martini** [comment]
Ok. I just have one problem:

> A Git tag points to exactly one commit, i.e. there's no such thing as per-branch tags.

I can use a tag only once. :-o

**Comment by monotek** [comment]
For the package builds thats not a problem. They would get the highest version tag available, which would be 1.0.1 in develop branch. This tag is used from this moment also for the next builds which is triggered by pushes. For this reason packager.io adds an ascending number after the version tag.

**Comment by martini** [comment]
Next try (sorry for bother you) :)

Let's say current stable Version is 1.1. So the branches need to have the following tags:

- stable (is current 1.1 - will include tags like 1.1.0, 1.1.1, 1.1.2, ...)
- master (will be 1.2 some day - so i tag master with 1.2.0)
- develop (will be 1.3 some day - so i tag master with 1.3.0)

If some day 1.2 is stable, we need to do the following:

- master (set the tag with 1.3.0)
- develop (set the tag with 1.4.0)

Note: First official release tags would be x.x.1 because x.x.0 is already used for master/develop build releases?

Correctly?

**Comment by jacotec** [comment]
I fear different tags on master and dev would block jumps between master and develop.

I.e. if you are normally on master (what I would do with my productive system) but you need an urgent fix from develop, you can switch the repo to develop, do a yum update, then switch back to master and once the master is updated later, you're still on track.

Why not leaving all to the current stable tag?

If 1.0.1 is the current stable, tag develop and master also with 1.0.1. Once 1.0.2 is ready, tag stable, develop and master with 1.0.2.

**Comment by monotek** [comment]
> If 1.0.1 is the current stable, tag develop and master also with 1.0.1. Once 1.0.2 is ready, tag stable, develop and master with 1.0.2.
This was also my first intention but this way we would not have a nightlies for 1.1.x without creating a new develop-1.1 branch.

**Comment by jacotec** [comment]
OK ... so the plan would be:

- Stable is 1.0.1
- Dev and Master would be tagged 1.0.2
- Once 1.0.2 is stable, Dev and Master are going to the next version (i.e. 1.0.3) when the work on the next version continues
- and so on ...

Is this correct?

**Comment by jacotec** [comment]
By the way ... are these messages usual (see the bold ones)?

> Is this ok [y/d/N]: y
> Downloading packages:
> **Delta RPMs disabled because /usr/bin/applydeltarpm not installed.**
> zammad-1.0.1-1479110477.a10edc3.centos7.x86_64.rpm                                                     |  65 MB  00:00:05     
> Running transaction check
> Running transaction test
> Transaction test succeeded
> Running transaction
>   Aktualisieren    : zammad-1.0.1-1479110477.a10edc3.centos7.x86_64                                                       1/2 
> **which: no initctl in (/opt/zammad/bin:/opt/zammad/vendor/bundle/bin:/sbin:/bin:/usr/sbin:/usr/bin:)**
> (Re)creating init scripts
> Nothing to do.
> Nothing to do.
> Nothing to do.
> Stopping Zammad
> database.yml found. Updating db...
> Starting Zammad
> Restarting Nginx

**Comment by monotek** [comment]
> Is this correct?

No, not if you read @martini last post.

I would still prefer to do it like described here:

https://docs.zammad.org/en/latest/contributing-branches.html

**Comment by monotek** [comment]
develop is tagged 1.2 now.
