### ISSUE TITLE
Draft Sharing: Draft stays after new ticket creation

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3981]
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* After usage of a shared draft in the agent ticket create, the draft should be deleted.

### Actual behavior:

* Draft stays after usage in agent ticket create.

### Steps to reproduce the behavior:

* Create a draft
* Use it for a new ticket
* Create another ticket and it is still there

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
@MrGeneration pls agree or close. Issue found by @martini

**Comment by MrGeneration** [comment]
Edit: Valid issue, my bad.
If Zammad removes shared drafts via ticket updates, it should do so with ticket creations too.

**Comment by rolfschmidt** [comment]
I have verified this issue again. It is getting deleted also in ticket creation if you use the load draft button. But is it not getting deleted if you save the draft by your self and then create or update the ticket.
