### ISSUE TITLE
LDAP Configuration does not save

### ISSUE THREAD

**Issue by MichaelVasile** [zammad/zammad#3992]
### Infos:

* Used Zammad version: Latest (5.0.3)
* Installation method (source, package, ..): Package install
* Operating system: Ubuntu 20.04.3 Server
* Database + version: MariaDB 10.5.15 (latest 10.5)
* Elasticsearch version: 7.17.0
* Browser + version: Chrome 98.0.4758.82

### Expected behavior:

Enable the LDAP integration and connect to our LDAP server. Sync with LDAP to populate users into the database.

### Actual behavior:

I am able to authenticate against LDAP and Zammad is able to analyze the LDAP structure. However, after analyzing the structure, the LDAP configuration does not appear to save. 

Right after the LDAP configuration analyzed by Zammad, I can see the LDAP configuration below the sync menu. However, when I attempt to sync, I receive this error:

![Screenshot](https://imgur.com/0CtfWMR.png)

When the page is refreshed, the LDAP configuration disappears from the page.

### Steps to reproduce the behavior:

1. Install and configure Zammad, per install documentation.
2. Attempt to enable LDAP and enter configuration

**Comment by MrGeneration** [comment]
Please try again with an opened developer console. Do you see any errors in your console tab?
What about your `production.log`?

**Comment by MichaelVasile** [comment]
See below, looks like there may be some kind of config issue?
![](https://i.imgur.com/gXH4SBo.png)
![](https://i.imgur.com/WFUiDdg.png)

**Comment by MrGeneration** [comment]
I'm afraid this is going to be impossible to reproduce.

**Comment by MichaelVasile** [comment]
Can you explain? That is rather vague.

**Comment by MrGeneration** [comment]
Because a not connected MySQL Client is situation specific and thus this makes it a technical question.
We can't solve bugs that are not reproducible - and this is exactly what I can't.
