### ISSUE TITLE
Select field in bulk operations out of view port

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3995]
### Infos:

* Used Zammad version: develop / 5.1 as of today
* Installation method (source, package, ..): any 
* Operating system: any 
* Database + version: any
* Elasticsearch version: any 
* Browser + version: any; verified on Opera v83

### Expected behavior:

Select fields for bulk operations in searches and overviews are in view port and selected values can be seen.

### Actual behavior:

Selects are out of view port but still can be selected / updated.

![image](https://user-images.githubusercontent.com/6549061/156391188-4d429bea-54de-4072-af9d-cfdd32ac5be0.png)

### Steps to reproduce the behavior:

* have a current develop version
* mark one or more tickets in the overview, select any of the 4 available attributes on the bottom (change a value) and try to read what you selected.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This UI bug is blocking required documentation changes that are introduced due to translation changes with upcoming Zammad 5.1.

(Affected page: Suggested workflows)

**Comment by mantas** [comment]
This is in QA
