### ISSUE TITLE
Tags fields limit to 10 options

### ISSUE THREAD

**Issue by KlaymoreGhost** [zammad/zammad#3996]
### Infos:

* Used Zammad version: 5.0.3
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04
* Database + version: package (PostGRE)
* Elasticsearch version: 7
* Browser + version: Chrome 98.0.4758.102, Edge 98.0.1108.62, Firefox 97.0.1

### Expected behavior:
Conditions: New Tags toggle off, with over 11 tags in the system created by Admin that will match criteria
Ticket or Trigger tags fields: Typing a tag that exists within the system should display a dropdown list showing all tags that match that criteria. The dropdown should also show a scrollable list of all tags. Selecting "Enter" should allow selection of a tag (provided it exists) without selecting from the dropdown. 

### Actual behavior:

*Typing the beginning characters of a tag (6.A) returns only up to 10 options in scroll list, even if a closer match would be further down the list. You can only add the tag by selecting it from the list, even if the tag is present in the system. Selecting "Enter", "Tab" or "Shift+Enter" will not add the tag, regardless of it shows in the dropdown.

### Steps to reproduce the behavior:

1. Create the following tags:16.A,16.A.1,16.A.2,16.A.3,16.A.4,16.A.5,16.A.6,26.A,26.A.1,26.A.2,26.A.3,6.A
2. In either a trigger or a ticket, attempt to enter the tag "6.A"
3. Dropdown list will only populate to option "26.A.3" (or whichever option is the 10th option) and selecting any terminating key (Enter, Tab, Shift+Enter) nor clicking outside of the tags field will add the tag of "6.A"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.

**Comment by KlaymoreGhost** [comment]
@MrGeneration this is a bug, not a feature request. The tag exist in the system, but there is no way to add them if you have new tags turned off and for any reason the one you want (even if it is an EXACT match to what you typed) doesn't populate in the dropdown.

**Comment by MrGeneration** [comment]
The number of shown tags depends on the view port size. 
If you have a lot of overlapping tag names the tag you're looking for may not be available.

This is not a bug but a design decision.
