### ISSUE TITLE
E-Mail prefixes Re and FWD are missing when cretae a new answer or forwarding

### ISSUE THREAD

**Issue by HenningSc** [zammad/zammad#3998]
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): package
* Operating system: Debian 9 
* Database + version:
* Elasticsearch version:
* Browser + version: Firefox 97

### Expected behavior:

* When I click on answer or forwarding under the ticket description I expect the prefix RE or FWD in the subject field before the subject of the ticket.

### Actual behavior:

* When I click on answer or forwarding under the ticket description there is no prefix RE or FWD in the subject field before the subject of the ticket. In the E-mail channel settings RE and FW are defined in the relevant fields.

### Steps to reproduce the behavior:

* reproducable

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by fliebe92** [comment]
Hi @HenningSc,

your reported issue is not a bug. The functionality works as designed. The configured values for answers/forwards are prefixed in the subject by sending out the email. We want to have a clean interface and e.g. `RE` and `FW` are not needed to be shown in subject fields during composing answers/forwards.

Thanks for your understanding. If you still think this is a bug or if it's not prefixed by sending out the mail, feel free to re-open this report with more information.

Thanks!
