### ISSUE TITLE
Long role names get broken due to bad overflow

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3999]
### Infos:

* Used Zammad version: develop / 5.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any; verified on Opera v83
* This is blocking documentation processes.

### Expected behavior:

Even in tables overflow does not break words.

### Actual behavior:

Overflow of Zammads granular KB permissions table breaks role names that are a little bit longer. 
The table does not use the full possible width which is why the effect appears early.

![image](https://user-images.githubusercontent.com/6549061/157050630-6ccdd13a-ca9d-4026-8137-e40b3d7f0ca8.png)

### Steps to reproduce the behavior:

* having a role with name `customers without subscription` is enough.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mgruner** [comment]
@MrGeneration I beg your pardon, but is this really a blocker (which would imply being unable to use the system properly)? Probably not.

**Comment by MrGeneration** [comment]
I believe that we shouldn't release buggy UI components were we do know that they're buggy. Especially if we also know that a lot of users use long role names.

But no problem, I'll remove the blocker label and stop all documentation processes around this function to reduce me having duplicate tasks. Please note, also why I believe this is a blocker: This function **should not** be released without documentation, as it's introduction is potentially dangerous and working contraire to what the original function of KB does.

**Comment by mgruner** [comment]
@MrGeneration no need to heat up here. Fix is in QA and will be in 5.1. Nobody wants to not fix stuff, or release intentionally buggy. But, we need a common definition of `blocker` as it may affect release dates etc. It sounds like we might need to clarify what a blocker is.

I'm not sure why you'd have to stop documenting this as we are only talking about a wrong word wrap that you don't need to show in screenshots.

**Comment by MrGeneration** [comment]
> I'm not sure why you'd have to stop documenting this as we are only talking about a wrong word wrap that you don't need to show in screenshots.

because I'd screencast the affected broken UI once and after fix a second time.
That's why I'm stopping unless fixed as I simply don't have to time to touch the same parts several times.
