### ISSUE TITLE
Translation error sign-in page when using Facebook-Sign-in

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#400]
There is a missing translation on the sign-in page of Zammad, using other sign-in-options like Facebook.

All is German, but the line "or sign in using" is not translated and missing in the translation area in Zammad.

![zammad1](https://cloud.githubusercontent.com/assets/3321655/20240596/ad289d66-a91c-11e6-8a11-53705f94dd28.jpg)

**Comment by hanneshal** [comment]
This is fixed
![image pasted at 2017-11-23 11-11](https://user-images.githubusercontent.com/804939/33167841-2dcdd75c-d03f-11e7-837a-fbb95a878330.png)
