### ISSUE TITLE
web notifications don't work anymore

### ISSUE THREAD

**Issue by Madko** [zammad/zammad#4002]
### Infos:

* Used Zammad version: 4.1.x
* Installation method (source, package, ..): package
* Operating system: ubuntu 18.04 LTS
* Database + version: postgres 12
* Elasticsearch version: 7.8
* Browser + version: firefox 97.0.1

### Expected behavior:

* web notification should work

### Actual behavior:

* web notifications don't work after a few minutes

### Steps to reproduce the behavior:

* install zammad
* open a lot of tickets
* wait for a new ticket, no notification, no number, nothing

Seems to be a bug:
```
App.App.SessionStorage(error)  | Session storage error! DOMException: The quota has been exceeded. application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:22:16195
    e https://contact.gouv.fr/assets/application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:22
    _log https://contact.gouv.fr/assets/application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:22
    log https://contact.gouv.fr/assets/application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:22
    error https://contact.gouv.fr/assets/application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:22
    set https://contact.gouv.fr/assets/application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:22
    set https://contact.gouv.fr/assets/application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:22
    success https://contact.gouv.fr/assets/application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:51
    l https://contact.gouv.fr/assets/application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:2
    fireWith https://contact.gouv.fr/assets/application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:2
    n https://contact.gouv.fr/assets/application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:3
    o https://contact.gouv.frassets/application-0b9054a6f805c83c50f6fe388eb63315a44ad80babf3578c5b4ead3c024adb95.js:3
```

should not use localStorage, or purge it in a while etc. Will try soon to reproduce on zammad 5.x

**Comment by MrGeneration** [comment]
How many tickets is many exactly?
Zammad should clear your ticket list (taskbars) if it exceeds 32. 

That is if it's no drafts involved - Please have a look.
Also - please re-check on Zammad 5.0 and ensure it's a vanilla installation.

**Comment by MrGeneration** [comment]
I'm closing this issue due the lack of feedback as we currently can't reproduce the issue.
If you have technical questions about this, please ask on the Community: https://community.zammad.org

If you still experience the issue and can tell on how to reproduce this, kindly let us know.
