### ISSUE TITLE
"Note - visibility confirmation dialog" setting also requests confirmation for e.g. email and phone articles

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4009]
### Infos:

* Used Zammad version: develop 5.1 as of 13th March
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any; verified on Opera v84
* Note: I refrained from adding the blocker tag, but personally believe this indeed is a blocker. This is blocking documentation processes as the current state of this function is unknown.
* Note2: I've looked up the specification document. The document is not talking about `Notes` but `Articles`. What's correct?

### Expected behavior:

When setting `Note - visibility confirmation dialog` setting to `yes`, Zammad will request confirmation upon creating a public article.

### Actual behavior:

1. Zammad asks for confirmation for *any* article type as long as it has been set to `internal` before and then being set to `public`.
   * for `phone` and `email` articles this requires the agent to set the article draft to `internal` first
2. This setting behaves inconsistent if you also set the option `Note - default visibility` to `public`.
   * This causes Zammad to not request confirmation at all
  
If point one is not a bug but behaving correctly, the option name has to be renamed as it won't affect notes only then.
I also believe that the moment of switching is "too early". This especially kicks in if you look at point 2.

![issue](https://user-images.githubusercontent.com/6549061/158067678-0ce9d80c-5ca9-4285-b6fe-8b25a79a8dfc.gif)

### Steps to reproduce the behavior:

* `Note - visibility confirmation dialog` setting to `yes`
* play around with articles and their visibilities

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Feedback: It should work for any article types.

**Comment by rolfschmidt** [comment]
changes to be made to the setting:

```
title: Note - visibility confirmation dialog to title: Article - visibility confirmation dialog
```

functionality is fine.
