### ISSUE TITLE
German .erb files (email notifications) are ignored

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#401]
Hi,

although there are german files "de.html.erb" for all .erb's for email notifications in the system by default, they are not used.

![zammad3](https://cloud.githubusercontent.com/assets/3321655/20240632/871483d2-a91d-11e6-998b-d086e420017d.jpg)

The preferences for the agent are set to "Deutsch", but all notifications are still in English. Seems the existing translations are ignored by Zammad.

![zammad2](https://cloud.githubusercontent.com/assets/3321655/20240617/35697f88-a91d-11e6-952e-f8c4f47dcdec.jpg)

**Comment by thorsteneckel** [comment]
It looks to me that the user language is not used at this point: https://github.com/zammad/zammad/blob/c71b0d36d4fcefdaae4e39f1859094727a3ca74c/app/models/transaction/notification.rb#L199

I'll take a closer look!

**Comment by martini** [comment]
@jacotec what language is stet for the user? 

```
shell> rails c
User.find_by(email: 'your@email').preferences['locale']
```

This locale will be used to email templates. Maybe the locale is not set and the interface is de because of browser language auto detection.

**Comment by jacotec** [comment]
OK, seems to be the problem:

irb(main):001:0> User.find_by(email: 'xx@mydomain.de').preferences['locale']
=> nil

But: In the profile settings of the user it's set to German. Maybe the profile does not get to the database,

![zammad1](https://cloud.githubusercontent.com/assets/3321655/20245858/8d480b6a-a9aa-11e6-9373-b566f8944a23.jpg)


Is there any way to "bulk set" German to all users? Also what's happening with customers which are created? There should be a default locale in the system which is assigned to new users?

**Comment by jacotec** [comment]
Update: When I just press "Apply" in the language setting above, it's set into the database. Seems to be that it's not properly initialized at the user creation.

irb(main):002:0> User.find_by(email: 'xx@mydomain.de').preferences['locale']
=> "de-de"

So my bulk command to set all users to "de-de" would be quite useful now ;-)

**Comment by martini** [comment]
@jacotec Any idea what the Zammad standard behavior should be?

1) Set the users language on initial login based on browser preferences?

2) Have a global default language setting?

Any other ideas?

**Comment by jacotec** [comment]
Hi @martini ,

I'd include the default language setting as a global option in the Zammad settings, selectable by the admin. Many users are created by the admin or staff (Outgoing tickets, agents) where Zammad did not get in touch with the browser of the agent/customer.

So a setting in the admin area for that would be not bad (default language for new users).

However, do you have any idea how I bulk-set all of my users to German in the console? ;-)

**Comment by martini** [comment]
```
shell> rails c
```

then past in:

```
User.all.each{|user|
  next if user.preferences && user.preferences['locale']
  user.preferences['locale'] = 'de-de'
  user.save
}
```

**Comment by jacotec** [comment]
Danke, scheint zu funktionieren! :-)

Beim Einloggen in meinen Testaccount von einem neuen Browser aus, bekam ich diese eMail nun in Deutsch ... Fehler im .erb-File?

> Hallo Larry,
> 
> es sieht aus, als ob Du Dich mit einem neuen Gerät um "#{user_device.created_at / not allowed}" angemeldet hast:
> 
> Dein Gerät: Mac, Firefox
> Deine Lokation (relativ): Germany
> Deine IP: xx.xx.xx.xx
> 
> Das Gerät wurde in die Liste der bekannten Geräte hinzugefügt, diese Liste kannst Du hier einsehen:

**Comment by jacotec** [comment]
@martini Just a thoght ... Maybe the error of the timestamp above is triggered because the users do now have the locale property set which they did not had before?

**Comment by martini** [comment]
@jacotec no, it's not related (by the way, the timestamp error is already fixed). I need to verify it, for me it has worked in the past.

The default behaviour should be:
1) Send no "new device" email at first login (only beginning with second login from different browser)
2) Notifications should be localised (based on preferences setting of user)

**Comment by jacotec** [comment]
@martini The behavior works fine, yes. OK if the timestamp error is already fixed in the background, will doublecheck once a new build is in the dev repo.

**Comment by martini** [comment]
So we can close it?

**Comment by martini** [comment]
My test result:

User with en: 'It looks like you signed into your account using a new device on "2016-11-14 08:45:28 UTC":'

User with de: 'es sieht aus, als ob Du Dich mit einem neuen Gerät um "2016-11-14 08:48:25 UTC" angemeldet hast:'

**Comment by jacotec** [comment]
Yap, the bugfix for the "/not allowed" was there last weekend. But I'll file a bug for the missing users's default locale propery ;-)

**Comment by Braintelligence** [comment]
It's confusing that some templates are formal (Sie) and others are informal (Du).
For example the notification about your password having changed is informal, while the mail containing the password reset link is formal. This should really be consistent or editable in the zammad web app.

**Comment by sthag** [comment]
This is still an issue for me.
The language (`.preferences['locale']`) is not set for new users.

**Comment by cthiel** [comment]
+1

**Comment by juliocjulio** [comment]
If I change my e-mail templates, are they going to be lost with Zammad's updates?

**Comment by cpzengel** [comment]
i tried those hints here, but still using open instead of geöffnet and closed ...
i have also overwritten the english file, no result

Das Ticket (Ticket##{ticket.number}) hat sich zu folgendem Status geändert: #{ticket.state.name}

thats how i do it, correct?

**Comment by MrGeneration** [comment]
@cpzengel please do not hijack already closed issues.
As this is a technical question, this is also the wrong place, please use the Zammad community for technical questions: https://community.zammad.org .
