### ISSUE TITLE
Import as / email archive import no longer triggered

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4010]
### Infos:

* Used Zammad version: verified on stable 5.0 and develop 5.1 as of 13th March
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Zammad suggests an archive import when you have mails older than two weeks in your mail box.

![image](https://user-images.githubusercontent.com/6549061/158070472-fd8d8da3-b587-478c-9c6a-c41760422b8e.png)

### Actual behavior:

Zammad warns you about a heckton of mails but doesn't care to suggest archive mode.

I've used an email account with 2 year old mails
![image](https://user-images.githubusercontent.com/6549061/158070494-59193f8f-f55e-4a0a-84e9-25e5b2668c8e.png)

Even my other personal, bigger mailbox does not apply for archive import.

### Steps to reproduce the behavior:

* have a mailbox with old mails
* try to add it to Zammad, before you're shown the SMTP dialogue, Zammad should suggest archive importing

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
I just tested arround a bit and it seems that the import archive dialog only displays up if you have "Keep messages on server" set to no.

@MrGeneration On your tests did you always use the expert mode and set it to yes?

**Comment by rolfschmidt** [comment]
If I use the auto detection (no expert mode) or set "Keep messages on server" to no the dialog shows up for me.

**Comment by rolfschmidt** [comment]
Not sure if it is only the configuration or also differences on the mail check. For me the archive dialog properly shows up for my gmx account. Will look again when we have more info about the mail account which is not showing the dialog.

**Comment by MrGeneration** [comment]
> On your tests did you always use the expert mode

Due on how Zammad probes mails and how my mail server is configured, at least for Zammad 5.0 I always had to use expert dialogues. So it was verified using expert settings not auto probe. That may be different now as we improved probing some months ago.

I can verify both approaches if that helps.

As side mark: It shouldn't matter if I use expert settings or not - if that does matter, I believe this is being unexpected and inkonsequent. May also cause serious issues for admins.

**Comment by rolfschmidt** [comment]
Yes it would be helpful to have more information. I was able to found out that keep messages on server field has impact if the dialog is shown or not. If this is what the bug is about then it is easy to fix. If the dialog does not show up for you in general e.g. if you use auto detect then it might be a deeper bug.

**Comment by mvella42** [comment]
We are having the same issue.

It doesn't seem to matter if we use expert mode or auto probe, it doesn't recognize that we have old emails and so doesn't offer the Archive option. It correctly counts the emails though, so it is seeing them all.

We have done this on the real target mailbox, as well as a "test" group and mailbox on the same servers.

I am SURE it worked before when we tested it, but, with the same mail server, it doesn't seem to be working at all now.

We have tried adding really old emails, as well as using a folder other than the default INBOX, and it consistently does NOT give us the Archive option.

It would be good to circumvent all this hassle with just a config option (hidden behind Expert mode) to Always offer Archive Mode .....

As it is, we now have a mailbox with over 50,000 emails that we cannot import into Zammad as we need to do it all as an archive :-(

**Comment by MrGeneration** [comment]
It does not matter if I use expert mode or not.
I've verified this on a mail account that has 2k + mails from the last 2 months +.
I've tested this on two independent mailboxes, one where I copied old mail data to and one with my personal email account that does contain the data as well.

I was not able to trigger the "import as" dialogue.
The verification happend via a dovecot server.

If you have further questions let me know.

> It would be good to circumvent all this hassle with just a config option (hidden behind Expert mode) to Always offer Archive Mode .....

Please don't post feature requests on this board. It's the wrong place. Use the community for this.

**Comment by MrGeneration** [comment]
Interesting side note:
When I was testing something else I added my previously used mailbox for this issue (and forgot that I did).

So now Zammad *does* provide me with the dialogue I'm looking for:
![image](https://user-images.githubusercontent.com/6549061/210077258-a12dcf3d-5e76-425c-b6f2-e4442643bddf.png)

It seems like Zammad is not taking the date supplied by the mail header, but possibly the second one of the mail server itself.
This can cause confusion especially if people like me test the functionality by moving a lot of old mail into a independent mailbox. We should clarify what date is used and if the mail server wins on that regard, the documentation would need a clear hint.

This would also explain why rolf can't reproduce the issue because he possibly uses an fairly old productive mailbox (which I'm not doing for those kind of things).

**Comment by albialbi** [comment]
We have the same problem. Please make a option in E-Mail account to select which date is used. I prefer header date, cause it show the original date.
Thanks.

**Comment by albialbi** [comment]
Is this still on  the roadmap?

**Comment by MrGeneration** [comment]
Please don't bump issues. It's not helping them to be processed faster. Thank you.
If you have feature requests, kindly create a post at the community for those:
https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6/none

**Comment by dominikklein** [comment]
I think this comment is maybe the most interesting one: https://github.com/zammad/zammad/issues/4010#issuecomment-1367930135

Or @YetAnotherGerrit do you have additional informations?

**Comment by YetAnotherGerrit** [comment]
> Or @YetAnotherGerrit do you have additional informations?

Unfortunately not. Usually I don't have access to that information in my workshops. I only recognize, that for me it's not predictable if it will be available. And when I recognize that it will not be available, it's already to late. So I always expect it not to work.

**Comment by YetAnotherGerrit** [comment]
How has this been solved now?

**Comment by binsky08** [comment]
> How has this been solved now?

If the mail server does not support imap sort and the first 500 (unsorted) probe mails does not contain a mail older than 14 days, a hint will be displayed in the import decision dialog that sorting was not possible and you have to decide yourself which kind of import you want (or need).  When a mail older than 14 days is found in that first 500 (unsorted) probe mails, the behaviour is the same as for a default old mail finding. In addition, the search logic for sorted mails has been slightly improved.
