### ISSUE TITLE
Textarea size should not increase in ticket zoom sidebar

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4012]
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* Textarea size should be fixed like in triggers

### Actual behavior:

![grafik](https://user-images.githubusercontent.com/5445062/158151221-eb07d113-d5d1-4789-a23e-88602f4236cd.png)

### Steps to reproduce the behavior:

* Create a textarea field
* Fill in text in ticket zoom

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
`attribute.expanding = false` might make sense but we also might also think about some css to make the sidebar more flexible and it could also give some conflicts of fields in the create screen because 2 columns are displayed in one row.

**Comment by dominikklein** [comment]
Yes, I think also that the used space should maybe be improved, at least for big screens. But maybe this should be handled as an own enhancement topic.
What do you mean with the 2 columns in one row?

**Comment by rolfschmidt** [comment]
If you add 2 textarea fields and show them in the ticket create screen then expanding of the fields will lead to overlaps. I don't know if this is preventable.

**Comment by rolfschmidt** [comment]
> If you add 2 textarea fields and show them in the ticket create screen then expanding of the fields will lead to overlaps. I don't know if this is preventable.

You have to patch the `textarea.coffee` with `attribute.expanding = false` before tho to see this.

**Comment by rolfschmidt** [comment]
after patching:

![grafik](https://user-images.githubusercontent.com/5445062/158589819-e9cfdb30-9f0b-4c2a-8bee-f490d72a3164.png)

then expand with the mouse:

![grafik](https://user-images.githubusercontent.com/5445062/158589921-5aa5e6be-2750-4ef6-b5a9-ca1a8f8b649a.png)

**Comment by dominikklein** [comment]
I think for this we need to set the `resize` style only to `vertical` (https://developer.mozilla.org/de/docs/Web/CSS/resize).
