### ISSUE TITLE
Missing quotation marks on sender address

### ISSUE THREAD

**Issue by ntinti** [zammad/zammad#402]
The support sender email address (configured at E-Mail => E-Mail Address needs quotation marks around the sender name, otherwise it is part of the email address and will not be accepted. 

Workaround: I put the quotation marks direct in the formular. Now the name is not My Support, but "My Support"

![bildschirmfoto 2016-11-12 um 21 26 25](https://cloud.githubusercontent.com/assets/7657049/20240681/dc42118e-a91e-11e6-85e5-13a80252abcd.png)

Rejection from the mailserver:

... did not like our MAIL FROM:
501 <My Support \<support@xyz.de\>>: "**@" or "." expected after "My"**

It should be

From: "My Support" <support@xyz.de>

Otherwise the mailserver puts "<"..">" around the hole construction of name+email address

**Comment by martini** [comment]
@ntinti Just one question, what MTA is it (any spezial config which I need to set to verify)?

**Comment by martini** [comment]
Fixed in 1.0, 1.1 and development https://github.com/zammad/zammad/commit/f2a2b9efe97e3b65848472d39297c8737afeb080.
