### ISSUE TITLE
Problems with duplicate records in Translations table

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4020]
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* Translation import should create or update instead of creating multiple translation per source.

### Actual behavior:

* There is suspicion because of https://github.com/zammad/zammad/issues/4018. Old translations were conflicting with new translations which were synced by the new i18n service. This needs to be investigated.

### Steps to reproduce the behavior:

* Have a system which is exists longer than 4 years
* `zammad run rails r "pp Translation.where(locale: 'de-de', source: 'FORMAT_DATE')"`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mgruner** [comment]
@rolfschmidt as discussed, this does not seem to be an issue with the translation sync / import, but an issue of multiple records with the same locale and the same source. 
We should clarify the reason and if more strings are affected, and then we can see how to move forward about it. Please get back to me with more information from the customer database if needed.

**Comment by rolfschmidt** [comment]
@mgruner Export of the translations table is now available (Ticket#10103444).
