### ISSUE TITLE
DataPrivacyTask fails if Agent was downgraded and mentioned people

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4025]
### Infos:

* Used Zammad version: stable / 5.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Zammad removes all mentions for the to be removed or adjusted user if:
* the user is the mentioned ID (`user_id`)
* the user has created the mention (`created_by_id`)
* the user has updated the mention (`updated_by_id`)

### Actual behavior:

Zammad at least does not clear mentions if the user did create a mention and no longer is agent. I am not sure if the downgrade is really required in this scenario.

Zammad fails with
`ERROR: #<ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table \"users\" violates foreign key constraint \"fk_rails_ab5f91f9d0\" on table \"mentions\"\nDETAIL:  Key (id)=(9) is still referenced from table \"mentions\".\n>`

### Steps to reproduce the behavior:

* Have an agent mention people
* degrade the agent to customer only
* use data privacy to kick the user out

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Seems to be a race condition :( tried to reproduce it locally but does not happen for me.

**Comment by rolfschmidt** [comment]
Might be related to https://github.com/zammad/zammad/issues/3935. Please reopen when more information given.
