### ISSUE TITLE
Switching the photos displayed in the preview does not work with the arrow keys

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4030]
### Infos:

* Used Zammad version: 5.1.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Microsoft Edge, 99.0.1150.46
* Ticket: #10103873

### Expected behavior:

* If there are multiple photos in the ticket and are displayed via the preview function, it should be possible to switch the displayed photo using the arrow keys 

### Actual behavior:

* The arrow keys do not move from one photo to another in the preview function.

### Steps to reproduce the behavior:

* Create a ticket with at least 2 photos in it. Then click on one of those photos in the preview and try to use the arrow keys to move from the currently displayed photo to another. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Thanks for fixing this! ❤️
