### ISSUE TITLE
The use of shared drafts for response ends with the saving of an internal note

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4031]
### Infos:

* Used Zammad version: 5.1.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Microsoft Edge, 99.0.1150.46

### Expected behavior:

* After editing a common draft, the email should be saved as a normal reply after sending, visible to the customer and in the whole coversation.

### Actual behavior:

* After finishing and sending the draft, the message is sent, but then saved as an internal note.

### Steps to reproduce the behavior:

* First save a draft of any kind in Zammad. Then open the same draft and click update. After that the message will be sent to the customer and will be saved as a internal note. 

Yes I'm sure this is a bug and no feature request or a general question.

<img width="829" alt="Before" src="https://user-images.githubusercontent.com/101350124/160130656-8e738cc3-3107-4166-928b-39412f790051.png">

<img width="684" alt="After" src="https://user-images.githubusercontent.com/101350124/160130606-8035e296-5a53-4353-a0d3-c9042cd14dca.png">

<img width="588" alt="After B" src="https://user-images.githubusercontent.com/101350124/160131346-c4cff0a0-6265-4085-b473-4ff7b56faabf.png">

**Comment by YetAnotherGerrit** [comment]
It's not saved as an internal "note"; but as an internal "Email". To be clear, just the "internal/public"-flag is not set correctly. The article-type is not an issue.
