### ISSUE TITLE
Zammad does not encrypt to CC addresses

### ISSUE THREAD

**Issue by poettig** [zammad/zammad#4036]
### Infos:

* Used Zammad version: 5.1.0-1648060831.1049368f.bullseye
* Installation method (source, package, ..): package
* Operating system: Debian 11
* Database + version: PostgreSQL 13.5
* Elasticsearch version: 7.17.1
* Browser + version: Firefox 98.0.1

Creating a new article (new or existing ticket) as mail with To and CC addresses correctly checks for each of the addresses if encryption is possible (i.e. enables and disables the "encrypt" button accordingly). However, sending this article with encryption and signature enabled generates an email that is only encrypted to the addresses listed in the To field. Example:

![image](https://user-images.githubusercontent.com/19955832/160172488-ffef2133-6858-4274-afc2-207facf5c3df.png)

```
└─$ openssl cms -cmsout -print -in /tmp/ticket-202203259700344-347485.eml | grep -i serial 
        d.issuerAndSerialNumber: 
          serialNumber: 11252863011588097877091389412
```

### Expected behavior:

* Encrypted mail is readable by all recipients.

### Actual behavior:

* Encrypted mail is only readable by direct recipients and not by CC'd ones.

### Steps to reproduce the behavior:

* Create a new ticket
* Select email
* Fill To and CC with different mail addresses that you both have an imported S/MIME public key for
* Send mail
* Download raw version of the created article
* Observe via `openssl cms` that it is only encrypted for the certificate of the "To" address

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by JustKiddingCode** [comment]
How is this not considered a bug?
Zammad sends a mail to someone who is not able to read it, because it is not encrypted for him.
Why on earth should this be intended behaviour?

**Comment by MrGeneration** [comment]
Please consult the community for your technical questions: https://community.zammad.org

**Comment by poettig** [comment]
As requested, i posted it to the technical assistance category.
I mention this here because we also searched and found the problematic piece of code that causes this, maybe it can be integrated:
https://community.zammad.org/t/zammad-does-not-encrypt-to-cc-addresses/8998

**Comment by MrGeneration** [comment]
duplicate of #4239
