### ISSUE TITLE
SLA: Ticket "updated at" time is set when SLAs are updated

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#4037]
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket #10103792

### Expected behavior:

* Upon updating SLAs, either manually or via API, an "updated at" timestamp should not be set on the affected tickets.   

### Actual behavior:

* Upon updating SLAs, either manually or via API, an "updated at" timestamp is set on the affected tickets. 
* This can influence e.g. scheduler tasks configured in dependency of time periods where tickets are not updated. 

### Steps to reproduce the behavior:

* Update SLA(s)
* Compare "updated at" time in a corresponding overview for affected tickets.  

Question to the Zammad product management team: Should this be regarded as a bug?

**Comment by MrGeneration** [comment]
This sounds fishy. Updating SLAs that has to update tickets IMHO has to update the `updated_at` timestamp.
If not affected tickets are also updated, this would be an issue.

Please specify what exactly is going on.

**Comment by rolfschmidt** [comment]
close for now, will be reopened if needed.
