### ISSUE TITLE
users customer name is displayed as id

### ISSUE THREAD

**Issue by 7qbit** [zammad/zammad#4040]
### Infos:

* Used Zammad version: 5.1.0
* Installation method: package
* Operating system: Ubuntu 20
* Database + version: PostgreSQL 12+214ubuntu0.1
* Elasticsearch version: 7.17.1
* Browser + version: Firefox 98.0.2
* ~~Ticket#10106384~~

### Actual behavior:

* Since update to 5.1, IDs are sporadically displayed instead of users name (Customer and Owners).

### Steps to reproduce the behavior:

* it was discussed in this thread. Screenshots are available there.
https://community.zammad.org/t/bug-user-customer-name-is-displayed-as-id/8965

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sporadically currently means ~ 3-4 times within the last 20 hours. 

Edit: Reloading temporarily helps on the situation but isn't really the great way.

**Comment by rolfschmidt** [comment]
What view is this? Is this ticket overview? Please provide more information about the exact place.

**Comment by MrGeneration** [comment]
Ah sorry. Yes this affects ticket overviews.

**Comment by Dr-Escher** [comment]
Can confirm this, running the latest docker-compose images. Just encountered this bug after upgrading to 5.1.1 (wasn't an issue on 5.1.0-4 for me).

Many (but not all) entries in the ticket overview are affected, irrespective of the state they are in (new, open or closed).

* Used Zammad version: 5.1.1-11
* Installation method: https://github.com/zammad/zammad-docker-compose
* Operating system: Debian 11.3
* Database + version: from Image
* Elasticsearch version: from Image
* Browser + version:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.147 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36 Edg/101.0.1210.32

**Comment by Suhopoljac** [comment]
Ticket#10106384

**Comment by rolfschmidt** [comment]
Hi @7qbit , @Dr-Escher ,

- how often do you have this issue?
- does it stay after page reload?

If you see the issue for example for the customer or owner column it would be interesting if your frontend has the information for the user given or not? You can check this by opening the inspector (F12) and running this command:
```
App.User.find(999)
```
The ID 999 should be replaced by the ID displayed in the column. If it is `null` then there is an assets issue, else if it is filled then there might some js issue while updating the data or something. 

We also have seen this issue so If you have any hints how to reproduce it let me know.

**Comment by MrGeneration** [comment]
Happens occasionally to me as well on my chromium based Opera.
Can't pin down any reasons why this happens, I believe "time" is enough. Browser session gets slower and slower with time when I'm handling too many tickets. But I've already mentioned that on other times.

![image](https://user-images.githubusercontent.com/6549061/172646197-eb2e2922-5067-4bbd-b45c-32e2d1c34112.png)

I'll send you my whole console output in private. Might be relevant.

**Comment by rolfschmidt** [comment]
Are you guys admins? I was able to reproduce the issue with admin permissions. Or can anyone reproduce this with `ticket.agent`  permissions only?

**Comment by 7qbit** [comment]
With admin permission. This can be reproduced sporadically, so I can't rule out that it doesn't happen with ticket.agent,  Currently with admin account can not be reproduced too. I could not find any correlation when this occurs.

**Comment by rolfschmidt** [comment]
> With admin permission. This can be reproduced sporadically, so I can't rule out that it doesn't happen with ticket.agent, Currently with admin account can not be reproduced too. I could not find any correlation when this occurs.

I'm pretty sure it is a bug in the user administration interface. Fix is WIP.

-> open admin user overview
-> open ticket overview
-> Wait for an user update or provoke it (`zammad run rails r "User.last.touch"`)
-> switch overviews
-> broken

I guess if this would affect `ticket.agent` users as well then this issue would be much more popular and we also would have a lot more feedback by our support channels. 

(regression of https://github.com/zammad/zammad/commit/949a47a7be6cf10dc7fd38c3c5b06def6efad26d)

**Comment by Dennis1993** [comment]
I‘m Admin of our installation and use zammad with it. The problem is every day in my own overview (my tickets). After a refresh (F5) the problem is solved.

I use Microsoft Edge and see that the problem is shown after 2-3 hours in my case. If I have zammad in another tab and when I switch after e.g. 1 hour back to zammad the customer names are numbers.

The numbers are shown in all overviews. My customers are 90% LDAP accounts!
