### ISSUE TITLE
Error when accessing ARGV in Rails 6.1

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4045]
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all 
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* rails zammad:package:migrate should be deprecated or work again.

### Actual behavior:

* `rake zammad:package:migrate` works but `rails zammad:package:migrate` not. It seems like that the ARGV variable is empty:

https://github.com/zammad/zammad/blob/0a8a28627b1af9094bfa863dc285a9c88e8b52ba/lib/tasks/zammad/command.rb#L43

### Steps to reproduce the behavior:

* run `rails zammad:package:migrate`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mgruner** [comment]
No backport needed as this is a Rails 6.1 issue.

**Comment by rolfschmidt** [comment]
relates https://github.com/rails/rails/commit/8ec7a2b7aaa31527686b05e0640d125299933782

**Comment by mgruner** [comment]
Fixed by 643f2bc4ce5bdde7149215091d397635e418797f.
