### ISSUE TITLE
Error on Update Database for Custom Sorting

### ISSUE THREAD

**Issue by ab-cc** [zammad/zammad#4047]
### Infos:

* Used Zammad version: 5.1.x
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 20.04
* Database + version: 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
* Elasticsearch version: 8.1.2
* Browser + version: Microsoft Edge 100.0.1185.29

### Expected behavior:
When editing objects and we select option "Use custom option sort", and click on "Update Database", the update happens without any error.
![image](https://user-images.githubusercontent.com/45005187/161673427-87253450-8276-4320-93a4-98a80bc2d4d5.png)
![image](https://user-images.githubusercontent.com/45005187/161673473-4d004945-b4bf-4ba6-9cbd-23c1409c0dd8.png)

### Actual behavior:
Receiving an error:
![image](https://user-images.githubusercontent.com/45005187/161673379-9fe9a341-33af-4f21-bdb6-303ce632e6fe.png)

### Steps to reproduce the behavior:
Go to Settings > System > Objects, edit any "select" type field and activate "Use custom option sort".

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Hi @ab-cc ,

this is a duplicate of https://github.com/zammad/zammad/issues/4027. I committed a fix for it yesterday. Would you be kind enough to try if it works for you after a zammad update? Please let me know if it works for you :)

**Comment by ab-cc** [comment]
@rolfschmidt I cannot thank you enough for this, the issue is fixed with the latest update. I apologize for creating a duplicate, I was using wrong search terms I guess and couldn't find #4027. Thank you once again for building such a polished and quality product.
