### ISSUE TITLE
apache configuration

### ISSUE THREAD

**Issue by chrisdecker1201** [zammad/zammad#405]
Hallo,

I'm trying to run zammad with apache instead of nginx but I have no idea how to convert the nginx configuration into an apache configuration. Maybe somebody did this already? I searched a lot in the internet but nothing worked. I only get a screen with Loading... and the rest files the browser wants to load has an 404 Error.

At the moment my configuration file looks like but there is missing a lot.

`<VirtualHost *:80>
        ServerName raspberrypi
        DocumentRoot /opt/zammad/public

        ProxyRequests Off
        ProxyPass / http://localhost:3000/
        ProxyPassReverse / http://localhost:3000/

        <Proxy http://localhost:3000/>
                Order deny,allow
                Allow from all
        </Proxy>
</VirtualHost>`

Greets,
chris

**Comment by jacotec** [comment]
Hi @chrisdecker1201 

It's not exactly the same, but I'm running my main webserver with Plesk and I'm using the apache there as a proxy to my Zammad VM:

```
RewriteEngine On
ProxyPass / http://zammad-domain.de:3000/
ProxyPassReverse / http://zammad-domain.de:3000/
```

That's all I add for the Apache config of this vHost ...

**Comment by monotek** [comment]
There is an Apache2 config available from an very old version of the Ubuntu install doc:
* https://github.com/zammad/zammad/blob/dfdfb15d43cb42e486939e79da5f6a1e944610ac/README_Install_Ubuntu.md
Not sure if it will work but maybe worth to try.

**Comment by chrisdecker1201** [comment]
I tried it but without success. But now it's an 403 Forbidden Error. ls -lash looks like:

4.0K drwxr-xr-x  3 zammad zammad 4.0K Oct 23 17:24 app

2.2M -rw-r--r--  1 zammad zammad 2.2M Oct 23 16:26 application-60d575ce9328404cf17920de544c26fbe913bd43251d63b34283e696db30cfec.js

468K -rw-r--r--  1 zammad zammad 468K Oct 23 16:26 application-60d575ce9328404cf17920de544c26fbe913bd43251d63b34283e696db30cfec.js.gz

300K -rw-r--r--  1 zammad zammad 298K Oct 23 16:26 application-ce5f223fd72bf9f25a925cc7560a74d6c31bc29b9ac86ac4720206495e02abb2.css

 52K -rw-r--r--  1 zammad zammad  50K Oct 23 16:26 application-ce5f223fd72bf9f25a925cc7560a74d6c31bc29b9ac86ac4720206495e02abb2.css.gz

4.0K -rw-r--r--  1 zammad zammad  710 Oct 23 16:26 application-print-db172409c8422225ac73dfd79ca9fe0994704e3813ebdd759e19cc0e3b0eff6a.css

4.0K -rw-r--r--  1 zammad zammad  345 Oct 23 16:26 application-print-db172409c8422225ac73dfd79ca9fe0994704e3813ebdd759e19cc0e3b0eff6a.css.gz

4.0K drwxr-xr-x  3 zammad zammad 4.0K Oct 23 16:26 chat

4.0K drwxr-xr-x  2 zammad zammad 4.0K Oct 23 17:35 custom

4.0K drwxr-xr-x  2 zammad zammad 4.0K Oct 23 16:26 error

4.0K drwxr-xr-x  2 zammad zammad 4.0K Oct 23 16:26 fonts

4.0K drwxr-xr-x  2 zammad zammad 4.0K Oct 23 16:26 form

4.0K drwxr-xr-x  3 zammad zammad 4.0K Nov  3 11:27 images

4.0K -rw-r--r--  1 zammad zammad  701 Oct 23 16:26 print-57d400c28213ca8fb1fc899cd1f3cd91ec5073d4947e60b0b37f2dc2c9937140.css

4.0K -rw-r--r--  1 zammad zammad  342 Oct 23 16:26 print-57d400c28213ca8fb1fc899cd1f3cd91ec5073d4947e60b0b37f2dc2c9937140.css.gz

4.0K drwxr-xr-x  2 zammad zammad 4.0K Oct 23 16:26 sounds

4.0K -rw-r--r--  1 zammad zammad 2.5K Oct 23 17:35 .sprockets-manifest-58f0a7a4fd7fd45a7d74f52b08ee9ecb.json

4.0K drwxr-xr-x  2 zammad zammad 4.0K Oct 23 16:26 tests

It seems for me good.

**Comment by rkaldung** [comment]
There's the websocket part missing in the Apache config. @monotek Where to place the Apache config?

**Comment by chrisdecker1201** [comment]
@rkaldung normally just place it at /etc/apache/sites-available/zammad.conf and than active it with sudo a2ensite zammad.conf

**Comment by rkaldung** [comment]
@chrisdecker1201 This is not what I was asking for, I'd like to know where to place it in the repository. You mentioned the Debian/Ubuntu path, there's no such location for RHEL/CentOS ;-)

**Comment by chrisdecker1201** [comment]
@rkaldung :) sorry

**Comment by monotek** [comment]
Added a apache2 proxy config to our contrib dir:
https://github.com/zammad/zammad/blob/develop/contrib/apache2/zammad.conf

Before you use it run:

a2enmod proxy
a2enmod proxy_http
a2enmod proxy_wstunnel

**Comment by chrisdecker1201** [comment]
I tried the configuration but still have the 403 error

**Comment by rkaldung** [comment]
@chrisdecker1201 Did you modified the ServerName as recommend?

**Comment by martini** [comment]
JFI: Config of @monotek looks good. Seems to be a general apache config issue.

**Comment by chrisdecker1201** [comment]
@rkaldung yes

**Comment by monotek** [comment]
Just installed fresh Ubuntu 16.04 and used own packages with changes in postinstall.sh.
Apache works without problems.

**Comment by rkaldung** [comment]
the ws:// prefix was introduced in Apache httpd 2.4.5. How to deal with httpd 2.2?

**Comment by monotek** [comment]
Is there a Apache 2.2 in any of the operating systems we build packages for?

If so it could be solved by some "if mod wstunnel" construct.

**Comment by rkaldung** [comment]
EL6 / CentOS 6 has an Apache httpd 2.2 by default

**Comment by monotek** [comment]
Imho centos 6 support will be dropped soon anyway.
@martini says it's only still there because it's needed for the docker image?

**Comment by martini** [comment]
> @martini says it's only still there because it's needed for the docker image?

Yes. It's not promoted in the documentation anymore (or at least should not).

It's only for the docker image in build (because databases outdated, Zammad installation is to complicated).

**Comment by monotek** [comment]
I just updated the apache config to reflect auth changes in 2.4.

@chrisdecker1201 
Please test again: https://github.com/zammad/zammad/blob/develop/contrib/apache2/zammad.conf

**Comment by chrisdecker1201** [comment]
@monotek that config did the magic ;). Thank you!

**Comment by hamzehmohammadnia** [comment]
Greetings,
Is there any already prepared Zammad's HTTPS config for apache server?
Best,
