### ISSUE TITLE
Image is only partly saved on richtext object attribute

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4050]
### Infos:

* Used Zammad version: 5.1.x
* Installation method (source, package, ..): Hosted
* Browser + version: Safari 15.3 + Firefox 99.0
* Ticket# 10103892

### Expected behavior:

* When I copy & paste image content into a richtext field I expect the image to be useable later on.

### Actual behavior:

* When I copy & paste an image into a richtext field is is display correctly, but after saving the record, the image is partly destroyed.

### Steps to reproduce the behavior:

* Edit e.x. User record, copy & paste an image into the "Note"-field (which is richtext), save the user and re-open the user.

![image](https://user-images.githubusercontent.com/97293098/162443829-6a25e2e5-9e81-4ae8-94d3-49e65a6b16d0.png)

--> SUBMIT & Reopen:

![image](https://user-images.githubusercontent.com/97293098/162443916-c4aed073-5969-4938-bb92-5ccbcfab32b0.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
Update from PM meeting (2022-04-12): Expected feature is to not paste images into the note fields. Note fields should only support text formatting.
