### ISSUE TITLE
Custom Organization Object fails in trigger condition

### ISSUE THREAD

**Issue by mat-ti** [zammad/zammad#4061]
### Infos:

* Used Zammad version: **5.1.0-1649920012.f8e72c64.focal**
* Installation method (source, package, ..): **Installed from package**
* Operating system: **Ubuntu 20.04.4 LTS**
* Database + version: **mysql 5.8**
* Elasticsearch version:  **7.17.2**
* Browser + version: **Firefox 99.0.1** (doesn't matter)

### Expected behavior:

* control the trigger auto responder: "New Ticket" with a custom Organization Object
* The custom Object "autoresponder is a boolean 
* one condition of the Trigger is "autoresponder is not false"

### Actual behavior:

* The Condition fails, when a user doesn't belong to an Organization
* When the user has an Organization the field "autoresponder" works as expected

### Steps to reproduce the behavior:

* tried several times in our productive environment, this could be verified in our test installation

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Hi @nh-matti ,

do you get any error message in the log? Not sure if I understand you correctly. autoresponder is not false means autoresponder is expected to be true which is not the case for customers which do not have an organization assigned?! Does it crash for you or what happend to the ticket with no organization? I would expect that nothing happens for the ticket with no organization.
