### ISSUE TITLE
KB answer appears in ticket search result even if category permissions are set to none and the kb answer visibility is set to internal

### ISSUE THREAD

**Issue by andrea-monti** [zammad/zammad#4069]
### Infos:

* Used Zammad version: 5.1.1
* Installation method (source, package, ..): Source
* Operating system: CentOS Linux release 7.6.1810 (Core)
* Database + version: postgresql 9.6
* Elasticsearch version: 7.9.1
* Browser + version: doesn't matter

### Expected behavior:

* If i set knowledge base category permission to "none" for a role that has knowledge base reader permission and if i set the answer visibility to Internal, i expect that the answer will be hidden from the knowledge base in-ticket search function "??"

### Actual behavior:

* the answer is still visible, but don't work, if i click on it i get a 403 error.

### Steps to reproduce the behavior:

* Set role permissions for the knowledge base to "reader"  ( i will use "customRole1")

![image](https://user-images.githubusercontent.com/104498720/165536683-bddcfac6-ec94-4704-98fb-11b0b5879965.png)

* Set category permission for the role to "None" ( i will set it for "Category 1" )

 
![image](https://user-images.githubusercontent.com/104498720/165540624-f5569098-f777-44fd-8653-53e23d663ec6.png)

* Set the answer visibility to Internal (i will set it for the answer "test answer 1 title")

![image](https://user-images.githubusercontent.com/104498720/165537846-74c8c5d8-6af9-4294-9a01-b56c5fd0548a.png)

* I can still see the answer if i search for it.
*  i expect it to be hidden from a user with customRole1 as role since i set permission to "none". 

![ticket](https://user-images.githubusercontent.com/104498720/165541123-fa1ceb40-270c-4983-af8c-419ca30e96a2.png)

* If i click on it i get a 403 forbidden error (rightly, since I removed the permissions)

![ticket2](https://user-images.githubusercontent.com/104498720/165541866-086539df-b56a-41de-9ef5-c9031bf506aa.png)

* If i go to the knowledge base page i rightly don't see "category 1"

![image](https://user-images.githubusercontent.com/104498720/165544551-1cdd1406-0145-4078-9e9a-d75c596b67b5.png)
 

* log [dev.log](https://github.com/zammad/zammad/files/8573002/dev.log)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I'm unable to reproduce this with a user that definitely only has this specific custom role and thus currently expect everything to be working as expected. You may experience temporary caching.

**Comment by andrea-monti** [comment]
We can reproduce the same problem even with the default "agent" role, can you try to set category permission for the role "agent" to "none" and then try to search for the answer in a ticket like i showed before?

it is not a caching issues because if i set to "draft" the answer visibility it doesn't show anymore, but if i change back to internal then it shows again

**Comment by andrea-monti** [comment]
i can still reproduce the bug on a new and clean instance of Zammad 5.1.1
