### ISSUE TITLE
Update Zammad lastest

### ISSUE THREAD

**Issue by netsky33** [zammad/zammad#407]
Hello Everyone ,

I have a simple question :) i want  update zammad and i don't find doc or guide for this. 
Someone just tell me how I can update ?

I have install zammad on cent os serveur.

Best regards,
Netsky #

**Comment by jannheider** [comment]
https://zammad.org/documentation/update/update-rpm

**Comment by netsky33** [comment]
Thanks Jannheider for your help !!
