### ISSUE TITLE
Error when using Multiselect field

### ISSUE THREAD

**Issue by marvmarvwest** [zammad/zammad#4070]
### Infos:

* Used Zammad version: 5.1.1
* Installation method (source, package, ..): package
* Operating system: ubuntu 20.04
* Database + version: mariadb
* Elasticsearch version: 7.17.3
* Browser + version: any

### Expected behavior:
Created new Multiselect field for the Object Ticket with two options and custom sort.
Use the new field in a Ticket, save it and everything is fine.

*

### Actual behavior:
The ticket saved but an Error occured: Invalied value '["test1","test2"]' for field location!
*

### Steps to reproduce the behavior:
Create a multiselect field with more than one entry, select custom sort. Create a new Ticket or use an existing and select one or more entrys of the new field and save the Ticket.
*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by marvmarvwest** [comment]
In the Console of the Browser appeared an HTTP 422 Error, this could help i guess.

**Comment by MrGeneration** [comment]
Please provide the relevant production.log part if you receive an 422 error.
Tracebacks help a lot more.

**Comment by martini** [comment]
And in addition it seems that it's a Zammad update but the processes are not restarted. Then it would be no issue/bug.

**Comment by marvmarvwest** [comment]
I restarted the Processes and even the whole server several times.
I dont get an production.log entry for that issue, but here's the log from the Browser:

application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:22 |  _____                                    _
| / _  / __ _ _ __ ___  _ __ ___   __ _  __| |
| \// / / _` | '_ ` _ \| '_ ` _ \ / _` |/ _` |
|  / //\ (_| | | | | | | | | | | | (_| | (_| |
| /____/\__,_|_| |_| |_|_| |_| |_|\__,_|\__,_|
|
| Hi there, nice to meet you!
|
| Visit http://zammad.com/jobs to learn about our current job openings.|| Your Zammad Team|
application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:22 {}
application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:3          PUT http://172.28.7.52/api/v1/tickets/2?all=true 422 (Unprocessable Entity)
send @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:3
ajax @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:3
t.addCurrentRequest @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:84
(anonymous) @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:84
t.request @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:84
t.request @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:84
ajax @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:27
a.submitPost @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:54
(anonymous) @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:53
a.submit @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:54
(anonymous) @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:53
(anonymous) @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:9
dispatch @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:2
g.handle @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:2
application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:3          PUT http://172.28.7.52/api/v1/tickets/2?all=true 422 (Unprocessable Entity)
send @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:3
ajax @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:3
t.addCurrentRequest @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:84
(anonymous) @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:84
t.request @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:84
t.request @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:84
ajax @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:27
a.submitPost @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:54
(anonymous) @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:53
a.submit @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:54
(anonymous) @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:53
(anonymous) @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:9
dispatch @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:2
g.handle @ application-1784fa624894ce7b1b15577fde77163781efb7217fbc99f41dc0937634e14d75.js:2

**Comment by marvmarvwest** [comment]
With the production.log u mean the /var/log/zammad/production.log, right?

**Comment by MrGeneration** [comment]
Production.log lifes on your Zammad server and does not come from your Browser.
`/var/log/zammad/` is your friend.

**Comment by marvmarvwest** [comment]
I know that, the production.log under /var/log/zammad/production.log doesn't contain any information about that issue, only the Browser throw an Error (seen above)

**Comment by MrGeneration** [comment]
`HTTP/422` errors definitely appear on said log file.

**Comment by martini** [comment]
`422 (Unprocessable Entity)` always creates an error log entry into production.log

JFI: I just tried to reproduce this issue on fresh 5.1.1. Its just working nice. I cant reproduce it.

**Comment by marvmarvwest** [comment]
okay here is a Screenshot of this issue
![Unbenannt](https://user-images.githubusercontent.com/104570509/165764878-d41b8fef-0f6e-4388-ab9e-9cbdc4f45473.PNG)
@
![image](https://user-images.githubusercontent.com/104570509/165765064-8ce8a2ce-dcfd-4811-b874-f1aa940dbe52.png)

**Comment by marvmarvwest** [comment]
the pic below is the production.log, sry for the waiting....... you are right, its there

**Comment by MrGeneration** [comment]
You did run the required database update and Zammad restart *after* adding / changing the object?

**Comment by marvmarvwest** [comment]
yes, the restart with: sudo systemctl restart zammad

**Comment by MrGeneration** [comment]
I am unable to reproduce this as well.
Two independent instances are working as expected.

With the provided description we cannot reproduce the issue which may be caused by either third party or local issues.
We can't tell. For this reason we're closing this issue as we can't qualify it as bug.

---

Please refer the Zammad community over at: https://community.zammad.org if you need further assistance.

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by No15pecial** [comment]
I have this problem on two different installations, both Ubuntu 20 
![Z-Why](https://user-images.githubusercontent.com/46358941/168119210-fccbb6e0-5ea8-4797-bcff-ddd2f4bedd79.png)

**Comment by MrGeneration** [comment]
Please do not hijack closed issues. Thank you.
If you have technical questions, please consult the community: https://community.zammad.org
