### ISSUE TITLE
Apply via role granted permission while creating shared draft

### ISSUE THREAD

**Issue by olemanz** [zammad/zammad#4071]
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): source
* Operating system: Ubuntu 20.04
* Database + version: Postgres 9.6
* Elasticsearch version: 7.17.3
* Browser + version: doesn’t matter

### Expected behavior:

If I create a shared draft of a new ticket, the draft is saved if the access to the group is granted via a given role. 

### Actual behavior:

The user needs to have access granted to the group directly via the user profile, access granted via a role is not accepted.

### Steps to reproduce the behavior:

* Create a role with full access to group
* Assign the role to user
* Assure that user has no access to group directly via user profile
* Draft new ticket
* Enter name of draft and try to save it 

[log.pdf](https://github.com/zammad/zammad/files/8583037/log.pdf)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by gojufhv** [comment]
I'm experiencing this problem on version 6.0. Is there a regression here?

**Comment by MrGeneration** [comment]
Possibly. Please open your individual bug report in case you believe you're encountering a bug.
