### ISSUE TITLE
Error message not shown while creating draft to user group without access

### ISSUE THREAD

**Issue by olemanz** [zammad/zammad#4072]
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): source
* Operating system: Ubuntu 20.04
* Database + version: Postgres 9.6
* Elasticsearch version: 7.17.3
* Browser + version: doesn’t matter

### Expected behavior:

If a user tries to create a shared draft but does not have proper access granted to a group, there should be a proper error message shown in the frontend.

### Actual behavior:

If a user tries to create a shared draft but does not have access granted to a group, the error message is not shown in the frontend, but in the browser console.

### Steps to reproduce the behavior:

* Assure that user has no access to group
* Draft new ticket
* Enter name of draft and try to save it 
* 
![screenshot](https://user-images.githubusercontent.com/47107730/165761971-f6720e8a-93d7-49a7-9c1e-c9b20c804c5d.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Nevermind.
Please ensure that your instance was updated as per documentation requirements and check again.


~~Sorry that's not a bug but functioning as designed.~~
~~The UI checks if there's drafts for said group and in your case the agent in question is not allowed to access those drafts.~~

~~UI shouldn't provide an error message in said workflow.~~

**Comment by olemanz** [comment]
Hi @MrGeneration ,

the instance is updated to latest version and behaviour is the same as above.

Thanks for checking!

Ole

**Comment by MrGeneration** [comment]
I'm unable to reproduce the described issue.
Please ensure that you've updated Zammad according to the documentation.

The shared draft dialogues are not available (just like the group in question) if the agent as no access to the group.

**Comment by olemanz** [comment]
Hi @MrGeneration,

maybe this is an edge case related to https://github.com/zammad/zammad/issues/4071. 

Thanks,

Ole

**Comment by fliebe92** [comment]
Hi @olemanz,

I used some time to check your reported issue with the current Zammad version 5.4. Unfortunately, I was not able to reproduce your behavior.

Could you please verify this in your Zammad instance as well? This would be really nice. If you still encounter any problems with it, feel free to re-open this report.

Thanks for your effort!
