### ISSUE TITLE
Upload attachment to an article via REST API does not set content-type 

### ISSUE THREAD

**Issue by alimanashov** [zammad/zammad#4077]
### Infos:
* Used Zammad version: 5.1
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04
* Database + version: mysql  Ver 15.1 Distrib 10.3.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
* Elasticsearch version: 7.10.2
* Browser + version: Chromium version - 101.0.4951.41

### Problem
The same problem like this https://github.com/zammad/zammad/issues/3032 but on the version 5.1

### Expected behavior
Create an article with attached file for a ticket using the REST API like on the Zammad GUI.

### Actual behavior
After executing the HTTP request, I'm getting this error:
```{"error":"undefined method `each_with_index' for \"mime-type\":String\nDid you mean?  each_line"}```

### Steps to reproduce
.env file
```
ZAMMAD_HOST=<SOME_HOST>
ZAMMAD_AUTH_TOKEN=<SOME_TOKEN>
```
Python 3 code
```python3
import requests
from decouple import config
data = {
        "ticket_id": ticket_id,
        "subject": "Test",
        "body": "This a test",
        "content_type": "text/html",
        "type": "note",
        "internal": "true",
        "attachments": [
            {"filename": "test.txt", "data": "dGVzdA==", "mime-type": "text/plain"}
        ]
    }
response = requests.post(f"{config('ZAMMAD_HOST')}/api/v1/ticket_articles", headers={
        'Authorization': f"Token token={config('ZAMMAD_AUTH_TOKEN')}"
    }, data=data)
print(response.text)
```

**Comment by MrGeneration** [comment]
Please provide a full fledged error descriptions and steps to reproduce with sample payloads.
Other wise we'll have to thread this as  question / can't reproduce without any further investigation.

Thank you.

**Comment by alimanashov** [comment]
It was the problem with the Python **requests** library. I have replaced it with the **urllib3**, and it works now.
