### ISSUE TITLE
Office 356 block create new ticket (from mails) - unprocessable mails

### ISSUE THREAD

**Issue by fedetucci86** [zammad/zammad#4082]
### Infos:

* Used Zammad version: 51.1.
* Installation method (source, package, ..):
* Operating system: Ubuntu 20.04.4 LTS
* Database + version: Postgre 12.9
* Elasticsearch version: 7.10.2
* Browser + version: Versione 99.0.4844.84 

### Expected behavior:

* all office 365 mails create ticket in Zammad system

### Actual behavior:

* unprocessable mails and the system non create any new ticket

### Steps to reproduce the behavior:

* i don't know, if i delete alla mail situated under
* /opt/zammad/tmp/unprocessable_mail/
* the system return to work.
in production.log i see

E, [2022-05-11T06:37:14.245058 #299257-13223020] ERROR -- : can't run postmaster pre filter 0015_postmaster_filter_identify_sender: Channel::Filter::IdentifySender
E, [2022-05-11T06:37:14.245088 #299257-13223020] ERROR -- : #<ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
>
E, [2022-05-11T06:37:14.246391 #299257-13223020] ERROR -- : Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail/2aba19ee09008c04ef930c191f5e11db.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2022-05-11T06:37:14.246416 #299257-13223020] ERROR -- : PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
 (ActiveRecord::StatementInvalid)
app/models/user.rb:1116:in `set_locale'
app/models/channel/filter/identify_sender.rb:157:in `user_create'
app/models/channel/filter/identify_sender.rb:53:in `run'
app/models/channel/email_parser.rb:160:in `block in _process'
app/models/channel/email_parser.rb:157:in `each'
app/models/channel/email_parser.rb:157:in `_process'
app/models/channel/email_parser.rb:121:in `block in process'
app/models/channel/email_parser.rb:120:in `process'
app/models/channel/driver/imap.rb:318:in `block in fetch'
app/models/channel/driver/imap.rb:255:in `each'
app/models/channel/driver/imap.rb:255:in `fetch'
app/models/channel.rb:56:in `fetch'
app/models/channel.rb:30:in `fetch'
(eval):1:in `_start_job'
app/models/scheduler.rb:291:in `eval'
app/models/scheduler.rb:291:in `_start_job'
app/models/scheduler.rb:243:in `block (2 levels) in start_job'
app/models/scheduler.rb:241:in `loop'
app/models/scheduler.rb:241:in `block in start_job'

Yes I'm sure this is a bug and no feature request or a general question.
![Error_mail](https://user-images.githubusercontent.com/105346158/167795999-f9750c21-3c36-47d6-bcaf-29e3875978ff.jpg)

**Comment by MrGeneration** [comment]
I'm unable to reproduce this issue. Please ensure that your system is configured according to documentation - especially https://docs.zammad.org/en/latest/appendix/configure-database-server.html .

If you have further questions about above, please consult the community as part of your technical question: https://community.zammad.org

If you have further information helping to verify this issue, please let us know here.
