### ISSUE TITLE
Can't change workflow, old values are stuck

### ISSUE THREAD

**Issue by eeuak** [zammad/zammad#4087]
### Infos:

* Used Zammad version: 5.1.1
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* Changing core workflow saves.

### Actual behavior:

* Can'T change core workflow even if it is newly created, old values are still saved.

### Steps to reproduce the behavior:

* 

https://user-images.githubusercontent.com/102230907/168602298-469259ed-5e97-4c35-82e4-e0a91e625785.mp4

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please provide developer tools console traceback (if applies) and production.log traceback of relevant request.

Thank you.

Edit: Please also Browser version and used addons. "All" is quite a bolt statement unless you really tried them all.

**Comment by eeuak** [comment]
Output of when I change and save the workflow (in production.log):


> I, [2022-05-16T15:48:36.781656 #1442335-33750420]  INFO -- : Started PUT "/api/v                                                                                                                        1/core_workflows/14" for 10.10.128.15 at 2022-05-16 15:48:36 +0200
I, [2022-05-16T15:48:36.788755 #1442335-33750420]  INFO -- : Processing by CoreW                                                                                                                        orkflowsController#update as JSON
I, [2022-05-16T15:48:36.789692 #1442335-33750420]  INFO -- :   Parameters: {"nam                                                                                                                        e"=>"projectworkflow2", "object"=>"Ticket", "preferences"=>{"screen"=>["create_m                                                                                                                        iddle", "edit"]}, "condition_saved"=>{}, "condition_selected"=>{"ticket.art"=>{"                                                                                                                        operator"=>"is", "value"=>"projekt"}}, "perform"=>{"ticket.state_id"=>{"operator                                                                                                                        "=>"set_fixed_to", "set_fixed_to"=>["", "13", "4", "12", "11", "1", "10", "14"]}                                                                                                                        }, "stop_after_match"=>false, "priority"=>300, "active"=>true, "id"=>"14"}
I, [2022-05-16T15:48:36.789554 #1442335-33651980]  INFO -- : Started GET "/api/v                                                                                                                        1/core_workflows?full=true&page=1&per_page=150&sort_by=name,%20id&order_by=ASC,%                                                                                                                        20ASC&_=1652689561641" for 10.10.128.15 at 2022-05-16 15:48:36 +0200
I, [2022-05-16T15:48:36.797785 #1442335-33651980]  INFO -- : Processing by CoreW                                                                                                                        orkflowsController#index as JSON
I, [2022-05-16T15:48:36.798339 #1442335-33651980]  INFO -- :   Parameters: {"ful                                                                                                                        l"=>"true", "page"=>"1", "per_page"=>"150", "sort_by"=>"name, id", "order_by"=>"                                                                                                                        ASC, ASC", "_"=>"1652689561641"}
I, [2022-05-16T15:48:36.855768 #1442335-33750420]  INFO -- : Completed 200 OK in                                                                                                                         66ms (Views: 0.4ms | ActiveRecord: 18.2ms | Allocations: 41253)
I, [2022-05-16T15:48:36.869017 #1442335-33750420]  INFO -- : Started GET "/api/v                                                                                                                        1/core_workflows?full=true&page=1&per_page=150&sort_by=name,%20id&order_by=ASC,%                                                                                                                        20ASC&_=1652689561642" for 10.10.128.15 at 2022-05-16 15:48:36 +0200
I, [2022-05-16T15:48:36.875325 #1442335-33750420]  INFO -- : Processing by CoreW                                                                                                                        orkflowsController#index as JSON
I, [2022-05-16T15:48:36.875516 #1442335-33750420]  INFO -- :   Parameters: {"ful                                                                                                                        l"=>"true", "page"=>"1", "per_page"=>"150", "sort_by"=>"name, id", "order_by"=>"                                                                                                                        ASC, ASC", "_"=>"1652689561642"}
I, [2022-05-16T15:48:36.936849 #1442335-33651980]  INFO -- : Completed 200 OK in                                                                                                                         138ms (Views: 14.0ms | ActiveRecord: 12.1ms | Allocations: 108503)
I, [2022-05-16T15:48:37.014157 #1442335-33750420]  INFO -- : Completed 200 OK in                                                                                                                         138ms (Views: 11.2ms | ActiveRecord: 6.6ms | Allocations: 125595)
I, [2022-05-16T15:48:37.147644 #1442335-33750420]  INFO -- : Started GET "/api/v                                                                                                                        1/core_workflows/?full=true&_=1652689561643" for 10.10.128.15 at 2022-05-16 15:4                                                                                                                        8:37 +0200
I, [2022-05-16T15:48:37.151365 #1442335-33750420]  INFO -- : Processing by CoreW                                                                                                                        orkflowsController#index as JSON
I, [2022-05-16T15:48:37.151436 #1442335-33750420]  INFO -- :   Parameters: {"ful                                                                                                                        l"=>"true", "_"=>"1652689561643"}
I, [2022-05-16T15:48:37.222898 #1442335-33750420]  INFO -- : Completed 200 OK in                                                                                                                         71ms (Views: 11.3ms | ActiveRecord: 3.4ms | Allocations: 78788)
I, [2022-05-16T15:48:37.244025 #1442335-33750420]  INFO -- : Started GET "/api/v                                                                                                                        1/core_workflows?full=true&page=1&per_page=150&sort_by=name,%20id&order_by=ASC,%                                                                                                                        20ASC&_=1652689561644" for 10.10.128.15 at 2022-05-16 15:48:37 +0200
I, [2022-05-16T15:48:37.247759 #1442335-33750420]  INFO -- : Processing by CoreW                                                                                                                        orkflowsController#index as JSON
I, [2022-05-16T15:48:37.247823 #1442335-33750420]  INFO -- :   Parameters: {"ful                                                                                                                        l"=>"true", "page"=>"1", "per_page"=>"150", "sort_by"=>"name, id", "order_by"=>"                                                                                                                        ASC, ASC", "_"=>"1652689561644"}
I, [2022-05-16T15:48:37.318301 #1442335-33750420]  INFO -- : Completed 200 OK in                                                                                                                         70ms (Views: 11.3ms | ActiveRecord: 3.5ms | Allocations: 78798)


Tried Browsers:
OperaGX LVL2 (core: 73.0.3856.389)
Google Chrome Version 101.0.4951.67 (Offizieller Build) (64-Bit)
Mozzilla Firefox 99.0.1

Thank you for looking into this.

**Comment by rolfschmidt** [comment]
@eeuak We can't reproduce this yet, so there might be a relation to an issue we fixed 2 weeks ago (https://github.com/zammad/zammad/issues/4090). Would you be kind enough to update your zammad to latest stable and see if the issue still occurs?

Also @MrGeneration asked you for the console errors in the browser (F12). Open it before you click into the workflows and try it again. Are there any errors if you try to save the workflow?

**Comment by eeuak** [comment]
@rolfschmidt Hi! It seems like the update actually fixed the problem. Thanks a lot!
