### ISSUE TITLE
Warnings when package is installed in centos

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#409]
#copied from bug 398 @jacotec

are these messages usual (see the bold ones)?

> Is this ok [y/d/N]: y
> Downloading packages:
> **Delta RPMs disabled because /usr/bin/applydeltarpm not installed.**
> zammad-1.0.1-1479110477.a10edc3.centos7.x86_64.rpm                                                     |  65 MB  00:00:05     
> Running transaction check
> Running transaction test
> Transaction test succeeded
> Running transaction
>   Aktualisieren    : zammad-1.0.1-1479110477.a10edc3.centos7.x86_64                                                       1/2 
> **which: no initctl in (/opt/zammad/bin:/opt/zammad/vendor/bundle/bin:/sbin:/bin:/usr/sbin:/usr/bin:)**
> (Re)creating init scripts
> Nothing to do.
> Nothing to do.
> Nothing to do.
> Stopping Zammad
> database.yml found. Updating db...
> Starting Zammad
> Restarting Nginx

**Comment by monotek** [comment]
@jacotec

First message is just a warning. I think you could fix it by installing "applydeltarpm". 
Try to "yum install applydeltarpm" before running zammad install / update.

Second warning is from "which initctl" command. In Ubuntu it just gives an empty answer, if command is not found. Centos seems to handle it differently and prints an error message, which you see there.

Think if have to change some stuff on contrib/packager.io/postinstall.sh to get rid of this message in Centos.

@martini
Are you sitll planing to change the Postgesql stuff for Centos to use a socket connection?
If so, you can give me the commands Postgresql would need on Centos and i'll add it when fixing the other stuff...

**Comment by monotek** [comment]
@martini 
There is also a warning about no "firewall-cmd" in CentOS 7.
Sure we need this?

**Comment by martini** [comment]
@monotek I'm open. Per default port 80 is blocked, so I can't use Zammad right after installing on my virtual box for testing. Also SELinux blocks nginx for network connections.

I tried to make it easy as possible for the user to get Zammad running.

For me it would also be ok to execute a script manually to change this level of changes or to write it into the doc.

**Comment by monotek** [comment]
I'm pretty sure i don't had to use this commands when trying it on CentOS 7.
Nginx on port 80 worked out of the box.

As "firewall-cmd" don't even exists there seems to be some unresolved dependencies. In my case i have to "yum install firewalld" first to be able to use "firewall-cmd".

What kind of CENTOS 7 installation did you used?
I used the minimal image.

**Comment by martini** [comment]
I used CentOS-7-x86_64-Minimal.iso with minimal installation. Then I installed with the commands of the documentation. 

JFI: CentOS7 is my default os, I'm hear to test, just let me know. Firewall and SELinux is enabled per default.

**Comment by monotek** [comment]
OK, Cool. Could also be my fault. Installed CentOS the first time. Maybe i missed something.

The warnings from which commands are fixed in: https://github.com/zammad/zammad/commit/7c077673c3ec6db87bef5e8f5e9ce5315e034dcd

**Comment by martini** [comment]
This was the software selection:
<img width="542" alt="screen shot 2016-11-14 at 13 46 08" src="https://cloud.githubusercontent.com/assets/110226/20265879/b42fa642-aa73-11e6-84ff-f949d050222a.png">

Regarding pg, only the host need to be removed from config/database.yml -> So fare as I know nothing more. Will check it ASAP and give you feedback ASAP.

**Comment by monotek** [comment]
Warnings are fixed.
Postgresql stuff will be handled somewhere else.
