### ISSUE TITLE
The labels "Save Draft" & "Macros" are not translatable

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4092]
### Infos:

* Used Zammad version: 5.1.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Edge, Version 101.0.1210.47 (Official Build) (64-bit)
* Ticket#10107207

### Expected behavior:

* When the language settings are changed, the "Save draft" & "Macros" should also change according to the selected language.

### Actual behavior:

* After changing the language, "Save draft" and "Macros" remain in their English form

### Steps to reproduce the behavior:

* click on your avatar in the lower left corner of the screen --> Profile --> Language --> choose a language other than English and confirm the change with Submit

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mgruner** [comment]
Fixed by e18654948e2bda19e6410c186e3d4a8c01615d47, backport will follow soon.
