### ISSUE TITLE
Logos in Facebook/Twitter Sign-in buttons are broken - for GitHub, Gitlab and OAuth2 the buttons are missing

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#410]
There should be a white "f" and a bird ... ;-)

![image](https://cloud.githubusercontent.com/assets/3321655/20263622/d4d37218-aa67-11e6-99c5-09f3c2c3fb12.png)

**Comment by jacotec** [comment]
Seems to be browser related:

Firefox: Works
Safari: No Facebook Icon, black instead white twitter bird
Chrome: No icons at all

**Comment by martini** [comment]
With Safari 10.0.1 
<img width="481" alt="screen shot 2017-01-10 at 20 12 55" src="https://cloud.githubusercontent.com/assets/110226/21820763/55581e62-d771-11e6-8235-79111fbc0c96.png">

**Comment by martini** [comment]
@mrflix Can you have a look on this issue? It seems that it's only working on firefox. You just need to enable the options (Admin -> Settings -> Security -> Third-Party Applications)

**Comment by mrflix** [comment]
@jacotec thanks for the report! The icons had subtle gradients that didn't render correctly in all browsers. I set them to a solid white that looks good too.
@martini I also added the visuals for gitlab & github and updated the google logo:
![screen shot 2017-01-11 at 11 15 39](https://cloud.githubusercontent.com/assets/60777/21844701/eebce276-d7ef-11e6-916e-833b8fe6f1ea.png)

**Comment by martini** [comment]
@mrflix Great work! Thanks a log! We need one more icon. It's a placeholder vor generic oauth config. Can you create one more for that (logo from https://en.wikipedia.org/wiki/OAuth)?

**Comment by mrflix** [comment]
Oh right, I overlooked it 😁. The official OAuth logo doesn't work well in small size so I went for a lock icon.
@jacotec sorry for the spam!
![screen shot 2017-01-11 at 16 14 03](https://cloud.githubusercontent.com/assets/60777/21853873/02703ea2-d819-11e6-8560-c3042b4ecd4e.png)
