### ISSUE TITLE
Selecting group permission "full" behaves differently in user- and role-management

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4100]
### Infos:

* Used Zammad version: latest (stable+dev)
* Installation method (source, package, ..): Hosted
* Ticket #10107412

### Expected behavior:

* When selecting "full" group-permission the behavior should be the same for user- and role-management.

### Actual behavior:

* When selecting "full" group-permission in the user-management, the other 4 permissions are automatically de-selected.
* When selecting "full" group-permission in the role-management, the other 4 permission are not automatically de-selected, instead there is an error message (only visible if you scroll to the top) after hitting "submit":
![image](https://user-images.githubusercontent.com/97293098/170225238-bffbfb18-3d7f-45ca-90b2-199a5e6e46e1.png)

### Steps to reproduce the behavior:

* Select the "full" group-permission after selecting other permissions in user- and role-management for the same group.

Yes I'm sure this is a bug and not a feature request or technical question.

**Comment by fliebe92** [comment]
@YetAnotherGerrit @MrGeneration Could you please tell me which of both behaviors is the correct one? Thanks 😁

**Comment by MrGeneration** [comment]
The user management approach is the correct one.
This means if you select FULL and have granular permissions set, they're unticket automatically.
