### ISSUE TITLE
Strange error message if Twitter appid/secret is wrong.

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#411]
Not sure about this, but I don't anyone will sign in with his Twitter account if the permissions to post tweets in the name of the user are requested ...

This was displayed after I clicked "Sign In with Twitter"

![image](https://cloud.githubusercontent.com/assets/3321655/20263670/18666260-aa68-11e6-8384-15ebc4aa4e73.png)

**Comment by martini** [comment]
Usually you set there app permissions in twitter app admin panel.

Normally you will register a app with low/min permissions to sign in and a second one (with this hight permissions) for using Zammad as twitter client for receiving/sending tweets.

So for me it's a logic/docu issue, no bug.

**Comment by jacotec** [comment]
@martini Agree in general.

I've set up a second app with just these rights:

- Read only
- Request the email address

... and that's the result when I click on the Twitter Sign In:

![image](https://cloud.githubusercontent.com/assets/3321655/20265120/98b9aa42-aa6f-11e6-8ba6-65c9d351fe34.png)

**Comment by martini** [comment]
It's there any useful information in log/production.log ?

**Comment by jacotec** [comment]
OK, the log complained about an OAuth failure. I've just updated the Twitter App and it's working now ... seems to be a Twitter hickup.

Sorry for that ...

**Comment by martini** [comment]
No no. The error message looks not good. ;)

**Comment by jacotec** [comment]
OK :-)

> I, [2016-11-14T14:05:45.078989 #14679]  INFO -- : Started GET "/" for xx.xx.xx.xx at 2016-11-14 14:05:45 +0100
> I, [2016-11-14T14:05:45.081671 #14679]  INFO -- : Processing by InitController#index as HTML
> I, [2016-11-14T14:05:45.083504 #14679]  INFO -- :   Rendered init/index.html.erb within layouts/application (0.1ms)
> I, [2016-11-14T14:05:45.085599 #14679]  INFO -- : Completed 200 OK in 4ms (Views: 1.3ms | ActiveRecord: 0.2ms)
> I, [2016-11-14T14:05:45.597478 #14679]  INFO -- : Started POST "/api/v1/signshow" for xx.xx.xx.xx at 2016-11-14 14:05:45 +0100
> I, [2016-11-14T14:05:45.599599 #14679]  INFO -- : Processing by SessionsController#show as JSON
> I, [2016-11-14T14:05:45.599669 #14679]  INFO -- :   Parameters: {"fingerprint"=>"-81362600", "session"=>{"fingerprint"=>"-81362600"}}
> I, [2016-11-14T14:05:45.666867 #14679]  INFO -- : Completed 200 OK in 67ms (Views: 18.5ms | ActiveRecord: 2.6ms)
> I, [2016-11-14T14:05:45.715213 #14679]  INFO -- : Started GET "/api/v1/translations/lang/de-de?_=1479128745354" for xx.xx.xx.xx at 2016-11-14 14:05:45 +0100
> I, [2016-11-14T14:05:45.717252 #14679]  INFO -- : Processing by TranslationsController#lang as JSON
> I, [2016-11-14T14:05:45.717301 #14679]  INFO -- :   Parameters: {"_"=>"1479128745354", "locale"=>"de-de", "translation"=>{}}
> I, [2016-11-14T14:05:45.742506 #14679]  INFO -- : Completed 200 OK in 25ms (Views: 19.7ms | ActiveRecord: 0.5ms)
> I, [2016-11-14T14:05:45.871152 #14679]  INFO -- : Started GET "/ws" for xx.xx.xx.xx at 2016-11-14 14:05:45 +0100
> I, [2016-11-14T14:05:45.873120 #14679]  INFO -- : Processing by ErrorsController#routing as HTML
> I, [2016-11-14T14:05:45.873169 #14679]  INFO -- :   Parameters: {"a"=>"ws"}
> E, [2016-11-14T14:05:45.874797 #14679] ERROR -- : No route matches [GET] /ws
> E, [2016-11-14T14:05:45.874872 #14679] ERROR -- : nil
> I, [2016-11-14T14:05:45.876733 #14679]  INFO -- :   Rendered inline template (1.0ms)
> I, [2016-11-14T14:05:45.878205 #14679]  INFO -- : Completed 404 Not Found in 5ms (Views: 1.4ms | ActiveRecord: 0.4ms)
> I, [2016-11-14T14:05:47.259051 #14679]  INFO -- : Started GET "/auth/twitter" for xx.xx.xx.xx at 2016-11-14 14:05:47 +0100
> F, [2016-11-14T14:05:47.420493 #14679] FATAL -- : 
> OAuth::Unauthorized (401 Authorization Required):
>   vendor/bundle/ruby/2.3.0/gems/oauth-0.5.1/lib/oauth/consumer.rb:217:in `token_request'
>   vendor/bundle/ruby/2.3.0/gems/oauth-0.5.1/lib/oauth/consumer.rb:136:in `get_request_token'
>   vendor/bundle/ruby/2.3.0/gems/omniauth-oauth-1.1.0/lib/omniauth/strategies/oauth.rb:28:in `request_phase'
>   vendor/bundle/ruby/2.3.0/gems/omniauth-twitter-1.2.1/lib/omniauth/strategies/twitter.rb:61:in `request_phase'
>   vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:215:in `request_call'
>   vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:183:in `call!'
>   vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
>   vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
>   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
>   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
>   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
>   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
>   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
>   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
>   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
>   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
>   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
>   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
>   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
>   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
>   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
>   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
>   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
>   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
>   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
>   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
>   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
>   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
>   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
>   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
>   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
>   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
>   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
>   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
>   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
>   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
>   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
>   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
>   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
>   vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
>   vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
>   vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
>   vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
>   vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
>   vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
>   vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
> 
>

**Comment by colinwilson** [comment]
@jacotec I'm experiencing the exact same issue. Can you say what you updated on Twitter that resolved your issue?

**Comment by thorsteneckel** [comment]
@colinwilson @martini - can you please provide information what you think is causing / required to resolve this issue?

**Comment by thorsteneckel** [comment]
Closing due lack of information how to reproduce. Feel free to provide more information and reopen.
