### ISSUE TITLE
KB custom domain url: cannot open tag pages

### ISSUE THREAD

**Issue by roy008** [zammad/zammad#4111]
### Infos:

* Used Zammad version: 5.1.1
* Installation method (source, package, ..): package
* Operating system: debian 10
* Database + version: PostgreSQL 11.14
* Elasticsearch version: 7.17.4
* Browser + version: Chrome 96.0.4664.110, FireFox 95.0.2
* Ticket#10132763

### Expected behavior:

* Clicking on tag label shows the list of knowledge base answers having that tag.

### Actual behavior:

* Page shows “500: We’re sorry, but something went wrong.”

### Steps to reproduce the behavior:

* Zammad is running under the domain like “zammad.example.com”.
* Set up a custom domain for the Knowledge Base (KB) like “kb.example.com”.
* Users open an answer which has a tag, and click on that tag. See example below. Here the tag name is “diagnostics”.
  ![image1](https://community.zammad.org/uploads/default/optimized/2X/6/607d39d024f3cb2e8046b73786eeba5e69902508_2_690x243.png)
* Zammad goes to the page https://kb.example.com/en-us/tag/diagnostics, but cannot open successfully. It says “500: We’re sorry, but something went wrong.”
  ![image2](https://community.zammad.org/uploads/default/original/2X/e/e678eb310faa4be89d8447f72f23738cbd89f965.png)
* If I use the link https://zammad.example.com/help/en-us/tag/diagnostics, no problem.
* I checked the production.log and see the error “undefined method ‘gsub’ for nil:NilClass”.

For detailed explanation on this bug, please see https://community.zammad.org/t/tags-issue-in-knowledge-base-when-custom-kb-url-is-set/8921

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by wucherpfennig** [comment]
I can second this issue. We are facing the same problem.

**Comment by cautopartes** [comment]
I can reproduce this behaviour on a current Zammad version with the addition that, for me the tags in the knowledge base, link to the base URL of the Zammad instance. Not to specific tags within the knowledge base at all. 

* Zammad URL
zammad.example
* KB URL
kb.zammad.example (setup via custom URL, tested and working)

* What works
zammad.example/help/en-us/tag/shipping

* What does not work (Error 500)
kb.zammad.com/en-us/tag/shipping

* Error in production.log
```
E, [****] ERROR -- : Error ID qsPz6CtF: undefined method `gsub' for nil:NilClass

    applied_path = path.gsub(%r{^/help}, custom_path)
                       ^^^^^
```

* As mentioned above
The mouse over preview link on tags in KB only shows the base URL of the Zammad installation (e.g.: zammad.example).
A mouse over on a tag is not showing a direct link, neither to "kb.zammad.com/en-us/tag/shipping", as expected, nor to  "zammad.example/help/en-us/tag/shipping", which is the only functional link and has to be called "by hand".

**Comment by cautopartes** [comment]
To give a better overview, a short summary of the situation: 

The issue concerns the public part of the knowledge base. If a custom URL is configured, the following happens: 

Klick on the tag for "shipping"

![image](https://github.com/zammad/zammad/assets/69846837/373771b4-b55e-4479-af71-38b2ed2b2f45)


The result is: 

![image](https://github.com/zammad/zammad/assets/69846837/ad3be1e6-8d30-4f2e-837d-7ef951e0c976)


The expected result is (what currently happens without custom knowledge base URL): 

![image](https://github.com/zammad/zammad/assets/69846837/9b38cd6f-db94-428a-862f-14a1b69b45b8)
