### ISSUE TITLE
Zammad shows "<![if !supportLists]>- <![endif]>" instead of list icon

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#4112]
### Infos:

* Used Zammad version: 5.1.1-1654094988.3f81df19.focal
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04.4 LTS
* Database + version: postgresql-12 - 12.11-0ubuntu0.20.04.1
* Elasticsearch version: 7.17.4
* Browser + version: Edge 101.0.1210.53

### Expected behavior:

Lists in incoming mails get displayed with bullet icon.

E-Mail in Outlook:

![image](https://user-images.githubusercontent.com/65536211/171624407-4eb561cd-3752-4e1f-839c-d9e0177a2e41.png)

### Actual behavior:

Zammad sometimes shows "<![if !supportLists]>- <![endif]>" instead of list icon.
Zammad mailbox is hosted on MS Exchange 2013.

Output in Zammad:

<![if !supportLists]>· <![endif]>1
<![if !supportLists]>· <![endif]>2
<![if !supportLists]>· <![endif]>3
<![if !supportLists]>· <![endif]>4

![image](https://user-images.githubusercontent.com/65536211/171624694-64e8eabe-e3d4-4533-91e6-d9b34fecb706.png)

### Steps to reproduce the behavior:

Send an E-Mail to Zammad Mailbox with List.
Tested from Outlook 2013. -> Both Mailboxes on the same Server
List in HTML code:
```
<p class="MsoPlainText" style="margin-left:36.0pt;text-indent:-18.0pt;mso-list:l0 level1 lfo1">
<![if !supportLists]><span style="font-family:Symbol;mso-fareast-language:EN-US"><span style="mso-list:Ignore">Â·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]><span style="mso-fareast-language:EN-US">1<o:p></o:p></span></p>
<p class="MsoPlainText" style="margin-left:36.0pt;text-indent:-18.0pt;mso-list:l0 level1 lfo1">
<![if !supportLists]><span style="font-family:Symbol;mso-fareast-language:EN-US"><span style="mso-list:Ignore">Â·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]><span style="mso-fareast-language:EN-US">2<o:p></o:p></span></p>
<p class="MsoPlainText" style="margin-left:36.0pt;text-indent:-18.0pt;mso-list:l0 level1 lfo1">
<![if !supportLists]><span style="font-family:Symbol;mso-fareast-language:EN-US"><span style="mso-list:Ignore">Â·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]><span style="mso-fareast-language:EN-US">3<o:p></o:p></span></p>
<p class="MsoPlainText" style="margin-left:36.0pt;text-indent:-18.0pt;mso-list:l0 level1 lfo1">
<![if !supportLists]><span style="font-family:Symbol;mso-fareast-language:EN-US"><span style="mso-list:Ignore">Â·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]><span style="mso-fareast-language:EN-US">4<o:p></o:p></span></p>
```

When using an external Address the List gets displayed correctly:

![image](https://user-images.githubusercontent.com/65536211/171625985-9cde72f7-847a-4338-95e7-dbe87402b24a.png)

Tested from iOS Mail. -> External Mail-Address

List in HTML code:
```
<ul class="ul1" style="list-style-type: circle; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); -webkit-text-size-adjust: auto;">
<li class="li1" style="margin: 0px; font-stretch: normal; line-height: normal;"><span class="s1">1</span></li><li class="li1" style="margin: 0px; font-stretch: normal; line-height: normal;"><span class="s1">2</span></li><li class="li1" style="margin: 0px; font-stretch: normal; line-height: normal;"><span class="s1">3</span></li></ul>
```

I also found this online:
https://www.redmine.org/boards/2/topics/38822

```
Hello,
I have the same problem and I solved it by using two regexp in cleanup_body in app/models/mail_handler.rb.
Why two regex ? One for replacing supportLists '-', '*', etc. by '* ' and one for replacing supportLists '1.' by '#'.
I attached the patch to my note.
I am pretty new to Ruby so maybe there is a better way to achieve it, but it works.

body = body.gsub(/<!\[if !supportLists\]>[^0-9<]+<!\[endif\]>/,'* ')
body = body.gsub(/<!\[if !supportLists\]>[0-9].+[^<]<!\[endif\]>/,'# ')
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Dennis1993** [comment]
Infos:

Used Zammad version: 5.1.1 (from yesterday)
Installation method (source, package, ..): source
Operating system: Ubuntu 20.04.4 LTS
Database + version: postgresql-12
Elasticsearch version: 7.17.4
Browser + version: Edge 101

we have the same! I think it is a wrong mail from a customer on Tuesday (because I updated yesterday to the lautest version).

we use Exchange Server 2016 in our house and the second mail received us yesterday with this problem.

**Comment by MrGeneration** [comment]
I can't reproduce said body with Outlook 2019 (sorry I don't have access to older versions).
Only difference apart from version itself is that I'm sending via non Exchange.

```
<body lang=3DDE =
link=3D"#0563C1" vlink=3D"#954F72" style=3D'word-wrap:break-word'><div =
class=3DWordSection1><p class=3DMsoPlainText>This is a simple =
test<o:p></o:p></p><p class=3DMsoPlainText><o:p>&nbsp;</o:p></p><ul =
style=3D'margin-top:0cm' type=3Ddisc><li class=3DMsoPlainText =
style=3D'mso-list:l0 level1 lfo1'>1<o:p></o:p></li><li =
class=3DMsoPlainText style=3D'mso-list:l0 level1 =
lfo1'>2<o:p></o:p></li><li class=3DMsoPlainText style=3D'mso-list:l0 =
level1 lfo1'>3<o:p></o:p></li><li class=3DMsoPlainText =
style=3D'mso-list:l0 level1 lfo1'>4<o:p></o:p></li></ul><p =
class=3DMsoPlainText><o:p>&nbsp;</o:p></p><p =
class=3DMsoPlainText>It&#8217;s that =
simple<o:p></o:p></p></div></body></html>
```

It also is okay in Zammad
![image](https://user-images.githubusercontent.com/6549061/171637488-b06dd032-9ddb-40bc-bbb3-78685ac2da4c.png)

The mail has been sent as HTML mail. I've also verified with rich-text.
Please ensure that your Exchange isn't fiddling with the message content.

After using your content I could verify this. However, please let us know your content encoding as well because I guessed wrong with UTF8. 

This looks, like always, very Microsoft specific.

**Comment by ghost** [comment]
Are you looking for this?

```
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-micr=
osoft-com:office:office" xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" xmlns=3D"http:=
//www.w3.org/TR/REC-html40">
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
1">
<meta name=3D"Generator" content=3D"Microsoft Word 15 (filtered medium)">
<style><!--
```
If you want I could share the whole eml(after removing personal/confidential data).

**Comment by MrGeneration** [comment]
Yes I was looking for the charset. Thank you.

**Comment by ghost** [comment]
I have now additionally tested rtf here the list is displayed correctly. I used the same Outlook client as above.

![image](https://user-images.githubusercontent.com/65536211/171646887-e66a185f-6264-4220-b58b-8b0336840ca8.png)

```
Content-Type: text/html; charset="us-ascii"
MIME-Version: 1.0

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
<meta name="Generator" content="Microsoft Exchange Server">
<!-- converted from rtf -->
<style><!-- .EmailQuote { margin-left: 1pt; padding-left: 4pt; border-left: #800000 2px solid; } --></style>
</head>
<body>
<font face="Calibri" size="2"><span style="font-size:10pt;">
<ul style="margin:0;padding-left:36pt;">
<li>1</li><li>2</li><li>3</li></ul>
<div>&nbsp;</div>
<div>&nbsp;</div>
</span></font>
</body>
</html>
```

**Comment by MrGeneration** [comment]
> I have now additionally tested rtf here the list is displayed correctly. I used the same Outlook client as above.

Looks like your Exchange server is converting the RTF content to HTML and by this fixing the issue. Fun.
