### ISSUE TITLE
Single tree select no longer allows displaying child values

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4118]
### Infos:

* Used Zammad version: develop / 5.2 (The issue must have been introduced on 08th June or up to 7 days earlier; 5.2 version as per today)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: verified on PGSQL
* Elasticsearch version: any
* Browser + version: verified von Opera

### Expected behavior:

If a tree select has child objects, you can navigate to those and finally select a value to provide it as attribute value.

### Actual behavior:

When trying to use sub values, the tree select modal simply closes.

![bug](https://user-images.githubusercontent.com/6549061/172828492-9285b50a-94fd-457c-89fd-0259f65e0154.gif)

### Steps to reproduce the behavior:

* have a current Zammad 5.2 develop
* add a single tree select with several rows and at least one with childs
* apply changes
* try to navigate through tree selects childs

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
relates https://github.com/zammad/zammad/issues/4080

**Comment by dominikklein** [comment]
In the end, it has now from the UX perspective the same behavior as the new multi-tree select, you need to click on the arrow to navigate throw the children.

**Comment by MrGeneration** [comment]
This means you've just changed the behavior of the field which is unexpected.
There was no heads up. This will nuke a lot of agents.
