### ISSUE TITLE
Time accounting "Overviews" is misleading

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4119]
### Infos:

* Used Zammad version: develop / 5.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Desired behavior:

Rename the heading "Overviews" to something more meaningful.
The section will hold all accounted times of tickets and the heading should deflect that.

### Actual behavior:

Overviews is being used in time accounting management which could confuse users, as Zammad uses overviews for other things which are not tied to admins in the admin UI.

![image](https://user-images.githubusercontent.com/6549061/173034146-89d0e5f0-dcfe-44c9-8514-01b8d3b2167e.png)

### Steps to reproduce the behavior:

* Have a look into time accounting

**Comment by rolfschmidt** [comment]
Any recommendations ? Maybe just "Tickets" or "Export" ?

**Comment by YetAnotherGerrit** [comment]
Just "Accounted time" as a header would be my suggestion.

**Comment by MrGeneration** [comment]
PM is currently discussing this out of appointment, give us time please.

**Comment by MrGeneration** [comment]
The decision ended for `Accounted time`
