### ISSUE TITLE
Error when update zammad 1.1.0

### ISSUE THREAD

**Issue by netsky33** [zammad/zammad#412]
Hi,

When i update zammad, i have a problem with Paquet : zammad-1.1.0-1479124849.8be9ce5.centos7.x86_64 (zammad)

Log:

Modules complémentaires chargés : fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.quelquesmots.fr
 * extras: centos.quelquesmots.fr
 * updates: fr.mirror.babylon.network
Résolution des dépendances
--> Lancement de la transaction de test
---> Le paquet zammad.x86_64 0:1.0.0-1476870286.9bdf6d7.centos7 sera mis à jour
---> Le paquet zammad.x86_64 0:1.1.0-1479124849.8be9ce5.centos7 sera utilisé
--> Traitement de la dépendance : nginx pour le paquet : zammad-1.1.0-1479124849.8be9ce5.centos7.x86_64
--> Résolution des dépendances terminée
Erreur : Paquet : zammad-1.1.0-1479124849.8be9ce5.centos7.x86_64 (zammad)
             Requiert : nginx
 Vous pouvez essayer d'utiliser --skip-broken pour contourner le problème
 Vous pouvez essayer d'exécuter : rpm -Va --nofiles --nodigest

**Comment by monotek** [comment]
See: https://docs.zammad.org/en/latest/install-rpm.html#add-zammad-epel-release-rpm-repos-and-install-rpm

You need to install epel-release first:
* sudo yum install epel-release

**Comment by netsky33** [comment]
Great Zammad is updated !! :) 

thanks monotek 

BR
