### ISSUE TITLE
Language setting not working properly

### ISSUE THREAD

**Issue by Jan-NiklasB** [zammad/zammad#4121]
### Infos:

* Used Zammad version: 5.1.1-11
* Installation method (source, package, ..): docker-compose
* Operating system: Ubuntu 20.4.3 LTS
* Database + version: as diliverd
* Elasticsearch version: as diliverd
* Browser + version: Firefox 101.0

### Expected behavior:

* On changing the language in the profile setting, the language changes correctly

### Actual behavior:

* For the setting "German" the changes aren't applied (Spanish for example is applied)

### Steps to reproduce the behavior:

* Fresh install zammad
* Go to profile and change language to german
* Notice that nothing changes

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
You may want to update your Zammad version and try again. I cannot reproduce this on a current 5.1 installation.

**Comment by Jan-NiklasB** [comment]
I installed this version just today with tag latest... I guess there is no newer version.
Databases etc. where newly created...

Tried with some other languages now, could it be the the setting german has a wrong id?
It always goes to english... the other languages work fine

**Comment by MrGeneration** [comment]
Sorry we're not answering technical questions on our repository. Tag 11 *is not* the latest version. Right now 46 is.

![image](https://user-images.githubusercontent.com/6549061/173104560-28c75f95-8b4a-4082-b789-044a225ef997.png)

**Comment by Jan-NiklasB** [comment]
> Sorry we're not answering technical questions on our repository. Tag 11 _is not_ the latest version. Right now 46 is.
> 
> ![image](https://user-images.githubusercontent.com/6549061/173104560-28c75f95-8b4a-4082-b789-044a225ef997.png)

Sorry, this was indeed my fault, had forgotten to set this ENV-Var

But now I'm on 5.1.1.11-46 and the problem persists, also it exists for Catala, so I guess it IS a bug, which has to be adressed here...

**Comment by MrGeneration** [comment]
> problem persists, also it exists for Catala, so I guess it IS a bug, which has to be adressed her

Sure.
Provide a clean step by step description on what to do to reproduce the issue and I'll gladly have another look.
As I said, with the information you provided, I am unable to reproduce the issue.

Changing languages is no problem on my browser - neither on Opera nor Firefox.

**Comment by Jan-NiklasB** [comment]
Okay, did a new install again deleting everything including images, volumes etc. and now it works....
I have no idea what went wrong the last time...

Sorry for wasting your time
