### ISSUE TITLE
Popovers will not disappear

### ISSUE THREAD

**Issue by martini** [zammad/zammad#4122]
### Infos:

* Used Zammad version: develop (2022-06-13)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Popovers should disappear after it is not needed anymore

### Actual behavior:

* Popovers will stay e. g. if overview is refreshed

### Steps to reproduce the behavior:

* open overview
* close ticket via rails console or other client

![popover-will-not-go](https://user-images.githubusercontent.com/110226/173353542-99d898e0-827e-4be1-aa1c-71312ac92985.gif)

**Comment by martini** [comment]
Also other areas are affected.

![popover-will-not-go-ticket-zoom](https://user-images.githubusercontent.com/110226/173355238-06e53b51-a660-4f1a-b40f-cf4e288a30df.gif)

**Comment by MrGeneration** [comment]
Didn't we have this kind of issue 3 weeks ago already?

**Comment by martini** [comment]
Yes. Mantas did improve the popovers. One issue got already fixed https://github.com/zammad/zammad/issues/4058 another (this one) on I discovered this week.
