### ISSUE TITLE
Time Accounting Reports should limit the entries for every table in the web view

### ISSUE THREAD

**Issue by martini** [zammad/zammad#4123]
### Infos:

* Used Zammad version: develop (2022-06-13)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Keep UI clear by only showing a reasonable amount of entries for record listings. Only 25 entries per table should be visible and a full list will be available with the existing export functionality.

### Actual behavior:

* All entries shown in the different sections from the Time Accounting Export blow up the UI.

### Steps to reproduce the behavior:

* create 1000 time accounting entries within one month
* got to admin area -> manage -> time accounting -> "by activity"

![show-only-first-50-rows-as-preview](https://user-images.githubusercontent.com/110226/173359161-ee203ccb-722f-489a-9c50-b075a5c0b515.gif)

**Comment by MrGeneration** [comment]
STOP
We're on feature freeze.
This change *cannot* be introduced with 5.2! This is not a bug but an enhancement and changes behavior (UI wise).

Also is pending to be discussed by PM next week. I did already note that down a week ago.

**Comment by martini** [comment]
Ok. So I did misunderstood that.

**Comment by rolfschmidt** [comment]
### Propsal

Maybe move it out of the admin interface? Today I heard that people are also complaining that it is not possible to split up permissions for it correctly. It might more sense to move the export into a new view in Profile → Reports and only keep the configuration part in the admin interface.

**Comment by martini** [comment]
For me the export of accounted time should stay in the admin interface, since the export is related to an admin / system sync task (export accounted time to transfer it to as accounting system like SAP) and not related to one user.

> Today I heard that people are also complaining that it is not possible to split up permissions for it correctly.

That is new to me. Can you explain it? Thanks!

**Comment by rolfschmidt** [comment]
> For me the export of accounted time should stay in the admin interface, since the export is related to an admin / system sync task (export accounted time to transfer it to as accounting system like SAP) and not related to one user.
> 
> > Today I heard that people are also complaining that it is not possible to split up permissions for it correctly.
> 
> That is new to me. Can you explain it? Thanks!

In the meeting today, somebody said that there are users which wish to use this separately to do the following tasks:

- one permission to configure the time accounting selector
- one permission to use the export

**Comment by martini** [comment]
> > For me the export of accounted time should stay in the admin interface, since the export is related to an admin / system sync task (export accounted time to transfer it to as accounting system like SAP) and not related to one user.
> > > Today I heard that people are also complaining that it is not possible to split up permissions for it correctly.
> > 
> > 
> > That is new to me. Can you explain it? Thanks!
> 
> In the meeting today, somebody said that there are users which wish to use this separately to do the following tasks:
> 
>     * one permission to configure the time accounting selector 
>     * one permission to use the export

Thanks for sharing this. This is a new information for me. I have not seen this use case before.

**Comment by KoJie** [comment]
Refinement Meeting, 31.05.23
- show the latest 20 entries per table. for more you have to download the export sheet
