### ISSUE TITLE
OS detection crashes if OS name cannot be parsed

### ISSUE THREAD

**Issue by dmke** [zammad/zammad#4124]
### Infos:

* Used Zammad version: 5.1.1-49<sup>a</sup>
* Installation method (source, package, ..): docker compose
* Operating system: Debian
* Database + version: PostgreSQL 12.11-1.pgdg10+1
* Elasticsearch version: zammad/zammad-docker-compose:zammad-elasticsearch-5.1.1-49
* Browser + version: Firefox latest (currently 101.0.1)<sup>b</sup>

<sup>a</sup>: The zammad/zammad-docker-compose repository currently sets 5.1.1-11 in their `.env` file. That version shows the same behaviour.

<sup>b</sup>: In Google Chrome 102.0.5005.115, this issue does not occur.

### Expected behavior:

* Agent-only users should be able to handle tickets.

### Actual behavior:

* Agent-only users see a blank page when accessing a ticket.
* The JavaScript console logs an error:

  ![image](https://user-images.githubusercontent.com/327411/173372069-0a3e4091-a1c7-45a7-8063-95fa3ddb12fc.png)

  ```
   Uncaught TypeError: t.os.name is undefined
       magicKey                            http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:98
       e                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:18
       l.fn[n]/<                           http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:18
       each                                http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:1
       each                                http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:1
       n                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:18
       renderPost                          http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:59
   Uncaught TypeError: this.articleNew is undefined
       formCurrent                         http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:55
       l                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:55
       markForm                            http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:55
       l                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:55
       r                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:99
       setTimeout handler*e.prototype.set  http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:99
       n                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:99
       set                                 http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:99
       delay                               http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:27
       e                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:27
       autosaveStart                       http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:55
       l                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:55
       show                                http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:55
       l                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:55
       show                                http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       i                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       showControllerHideOthers            http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       i                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       startController                     http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       i                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       executeSingel                       http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       run                                 http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       execute                             http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       execute                             http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       n                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:56
       Router                              http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       Router                              http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:101
       s                                   http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:8
       match                               http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:9
       matchRoute                          http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:9
       matchRoutes                         http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:9
       change                              http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:9
       dispatch                            http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:2
       handle                              http://localhost:8080/assets/application-872e24fcfccbb1499f27218621925880e75d1331d95132b40f3d6d103787bb01.js:2

  ```

Note: Users with Admin+Agent roles can see the ticket and don't get an error:

![image](https://user-images.githubusercontent.com/327411/173373426-5f7719aa-0e72-4bc1-ab54-c51a412f4851.png)

### Steps to reproduce the behavior:

* Setup a new Zammad instance.
* Create a new user, select only "Agent" for role, and grant "full" access to user group "Users":

  ![image](https://user-images.githubusercontent.com/327411/173372912-fd99806a-cda2-4d2a-8e49-0e3412ee43d6.png)

* Verify "Agent" role permissions:

  ![image](https://user-images.githubusercontent.com/327411/173372542-be3dc2d5-83b7-4e02-adaa-64e08fa87975.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by dmke** [comment]
This is not a technical question, it is a defect report.

**Comment by MrGeneration** [comment]
Okay let me put it different: RTFM.

**Comment by dmke** [comment]
No need to get rude.

I don't see any particular mention of Firefox not being supported in the [Client requirements](https://docs.zammad.org/en/latest/prerequisites/software.html#supported-browsers).

Any particular section I should dive into?

**Comment by dmke** [comment]
I did some digging, and the culprit lies in `app/assets/javascripts/app/lib/app_post/browser.coffee`:

```coffee
class App.Browser
  @magicKey: ->
    # ...
    if browser && browser.os && browser.os.name.toString().match(/mac/i)
      # ...
```

(same for `@hotkeys`).

This fails, if `browser.os` does not have a `name` property.

That being said, your UAParser library is pretty old (2015?) and not even a released version (0.7.7 and 0.7.9 exist, but not [0.7.8](https://github.com/faisalman/ua-parser-js/tags?after=0.7.10)).

**Comment by mantas** [comment]
What is your `browser.os` content that it doesn't have `name` property? I tried on various browsers and they all return `browser.os` as undefined

**Comment by dmke** [comment]
https://jsfiddle.net/_dmke/jxbztehm/1/

- `navigator.userAgent`: `"Mozilla/5.0 (compatible; rv:100.0) Gecko/20380120 Firefox/100.0"`
- `new UAParser().getOS()`: `{}`

**Comment by MrGeneration** [comment]
OP is using a non supported role configuration which is state in the manual:
https://admin-docs.zammad.org/en/latest/manage/roles/agent-permissions.html

![image](https://user-images.githubusercontent.com/6549061/173528926-621f029d-c5a6-4277-8ce9-92d4ded25512.png)

Most likely own fault by miss configuration.

**Comment by dmke** [comment]
Nope, I'm using two different users with different email addresses, which happen to have the same avatar.

**Comment by mantas** [comment]
@dmke this is weird and unexpected, but seems to be a valid issue... Thank you for providing more details!

**Comment by MrGeneration** [comment]
> Nope, I'm using two different users with different email addresses, which happen to have the same avatar.

Now that's odd because:
![image](https://user-images.githubusercontent.com/6549061/173531033-f01a246c-2720-43a4-b3f9-aca1db2d2d97.png)

If that's not your configuration of the affected user, you could have saved yourself (and indirectly me) *a lot* of trouble by providing proper reproduction ways.
