### ISSUE TITLE
Can't process email / Error creating ticket with changed Ticket Number Format

### ISSUE THREAD

**Issue by gbressel** [zammad/zammad#413]
"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//522a435ccda4a4dcfa590f6185eb9d38.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<NoMethodError: undefined method `[]' for true:TrueClass>"

I don't want to publish my mail here - but I can send it to you personally.

Kind regards,
Gero Bressel

**Comment by thorsteneckel** [comment]
Hi @gbressel - could you please send it to support@zammad.com ? We will take a look at it.

**Comment by gbressel** [comment]
Further information:

The installation is an ubuntu 16.04 based .deb installation as recommended on https://zammad.org/documentation/install/install-deb

It is a clean installation on newly set up server (VM) from scaleway. On a similar VM until today I had an generic installation "from source" without problems. But to simplify the upgrade process I tried to use the .deb installation now. Everything works fine, but creating tickets / processing incoming mails does not work, giving the same error with each received mail. 

.deb version is: 1.1.0-1479124849.8be9ce5.xenial

I already tried from two different mail accounts.

You've got mail.

Thanks a lot!

**Comment by martini** [comment]
@gbressel I can not reproduce the problem (the email is processed on my side without issues).

Is it possible to have a look into log/production.log (in case also via PM)?

**Comment by gbressel** [comment]
I, [2016-11-14T15:53:50.166369 #23279]  INFO -- :  ...stopped thread for 'Stats.generate'
I, [2016-11-14T15:53:51.914673 #23279]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2016-11-14T15:53:51.921146 #23279]  INFO -- : fetching imap (server6.pikos.de/dev-ticket@overcross.com port=993,ssl=true)
I, [2016-11-14T15:53:52.298084 #23279]  INFO -- :  - message 1/1
I, [2016-11-14T15:53:52.863048 #23279]  INFO -- : header x-zammad-ticket-customer_id found 7
E, [2016-11-14T15:53:52.957597 #23279] ERROR -- : ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//11694fe4a5dbb5e34bd25a81cc57303a.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2016-11-14T15:53:52.957856 #23279] ERROR -- : ERROR: #<NoMethodError: undefined method `[]' for true:TrueClass>
I, [2016-11-14T15:53:53.109732 #23279]  INFO -- : done

**Comment by martini** [comment]
@gbressel thanks, it seems to be something on your settings. Do you have set postmaster filter? If yes, which? Thanks!

**Comment by martini** [comment]
JFI: If possible (to speed up) remote login via ssh would also be possible.

**Comment by gbressel** [comment]
Ok, I added the credentials to the ticket #10526 at support.zammad.com

**Comment by martini** [comment]
Fixed for develop, 1.0, and 1.1 https://github.com/zammad/zammad/commit/9d5e5013ddb3d5591d07436ebb53af86d977fa3f. 

JFI: Interface for ticket number generator is now reworked in develop https://github.com/zammad/zammad/issues/427.
