### ISSUE TITLE
Permissions for groups are not activating the "ticket" -> "agent" checkbox in the role configuration

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4130]
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: 10107020

### Expected behavior:

* By checking a permission (e.g. "Read") for a group in the "ticket" permission block, the "agent" checkbox should be activated automatically.

### Actual behavior:

* Currently the required checkbox for "agent" in the "ticket" permission block needs to be set manually. This could lead to the situation that no agent of a group is selectable as owner while working on a ticket.

### Steps to reproduce the behavior:

* Login with an admin account into Zammad.
* Navigate to the admin area.
* Open the roles.
* Create a new role or edit an existing role.
* Scroll down to the "ticket" permission block.
* Check at least one permission for a group.
* The "agent" field is not checked automatically.

![Role configuration - permissions - group matrix](https://user-images.githubusercontent.com/8327427/173795554-f0234e54-b65c-4511-b463-60256a16dff2.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by YetAnotherGerrit** [comment]
I think that a warning popup is needed, before "agent" is automaticly checked. To prevent accidentily provide agent-permissions.

**Comment by rolfschmidt** [comment]
will get fixed with https://github.com/zammad/zammad/issues/4243

**Comment by rolfschmidt** [comment]
#4243
