### ISSUE TITLE
Elasticsearch forgets results from attachments over time

### ISSUE THREAD

**Issue by TomGem** [zammad/zammad#4134]
### Infos:

* Used Zammad version: 5.1.0
* Used Zammad installation type: Package (new, no upgrades)
* Used Elasticsearch version: 7.17.2
* Operating system: Ubuntu 20.04.4
* Browser + version: Any

### Expected behavior:

* Getting Elasticsearch results from attachments anytime

### Actual behavior:

* Elasticsearch ‘forgets’ results from attachments over time

### Steps to reproduce the behavior:

* attach a pdf
* search for a string in this file and find it
* wait a few hours
* search for the same string again, the result disappeared
* reindex elasticsearch, the result will be back for a few hours

### Summary

Elasticsearch forgets results from attachments over time.
After a reindex the problem is gone for a few hours.

The only workaround I've found is to regularly rebuild the search index:

```
# elasticsearch attachments index workaround
7 */3  * * *   root    zammad run rake searchindex:rebuild > /dev/null
```

I've created this issue as requested by @MrGeneration 

Please see the following Zammad Community Topic for more details:
https://community.zammad.org/t/elasticsearch-forgets-results-from-attachments-over-time/9029

**Comment by MrGeneration** [comment]
JFI on my instances (no matter if SaaS or on Premise) I was not able to search and find attachments. I made sure that the used files are not covered by the default extension filters. It didn't matter if text, pictures or pdf.

Tickets with attachments had a new attribute populated in the tickets:
```
	"_ignored": [
		"article.attachment.content.keyword"
	],
```
