### ISSUE TITLE
Error message "Insufficient permissions" when group ticket belongs to has been deactivated

### ISSUE THREAD

**Issue by dantronik-bugreporting** [zammad/zammad#4136]
### Infos:

* Used Zammad version: 5.1.1
* Installation method (source, package, ..): package
* Operating system: Debian
* Database + version: PostgreSQL 
* Elasticsearch version: 7.17.4
* Browser + version: Rambox v2.0.6

### Expected behavior:

* Error message should be more verbose than "Insufficient permissions"

### Actual behavior:

* Error message "Insufficient permissions to open the following: Ticket"

### Steps to reproduce the behavior:

* Create a ticket in an active group.
* Deactivate group
* Try to access ticket via URL.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
