### ISSUE TITLE
It is possible to remove needed fields (e.g. login from user) within a workflow

### ISSUE THREAD

**Issue by ric99cs** [zammad/zammad#4137]
### Infos:

* Used Zammad version: 5.01
* Installation method (source, package, ..): Package
* Operating system: Debian 10
* Database + version: 
* Elasticsearch version:
* Browser + version:  Chrome 100

### Expected behavior:

* When creating a workflow, there should not be the option to remove any needed field from an ui mask

### Actual behavior:

* When you create an workflow, for example within the creation mask or edit mask you can remove the login field from the user object. This is unexpected because any further action on the user object will fail, due there is no login for that user.

![ffa49236fe9823306d09bf91cb6bf309fd2ea526_2_596x500](https://user-images.githubusercontent.com/43894274/174789427-e3e23b25-f7cf-4bd1-9d4d-a0c691104f75.jpg)

I know, that the clause in the picture makes no sense, but it illustrates the unexpected behavior.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
To be discussed in project managemened.

**Comment by MrGeneration** [comment]
I can not reproduce this on a stable Zammad 5.2. Possibly your patch level of 5.1  has been sketchy.
Closing.
