### ISSUE TITLE
Internal actions (assignments, change of group, open, close) should appear in the ticket view

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#414]
Hi,

in the ticket view you see outgoing communication from the system like a history log:

> "Ihre Anfrage(Ein paar Anmeldungen)" -> "name@email.de"

Like a "log" between the messages.

What is absolutely missing? Any other actions like:

> Group changed by Marco: "Geschäftsstelle" -> "Spielbetrieb"
> Owner changed by Marco: "-" -> "Larry Bird"

What is also missing: A timestamp for all these entries ;-)

So it should look like:

> 14.11.2016 15:47 Group changed by Marco: "Geschäftsstelle" -> "Spielbetrieb"

**Comment by Julian0o** [comment]
It think exactly this behaviour is what zammad makes so crisp and clean. You don't need this information in 90% of the time. And if you need it, you can look at this information in the history.

**Comment by jacotec** [comment]
@Julian0o I don't think the crispyness would suffer from that, the log lines are quite decent. And I don't want to have the complete info from the history in it ... just elemental things like reassignments, group or status changes (closed, opened ...)

**Comment by martini** [comment]
JFI: If this feature is there, it should be configurable. :)

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
