### ISSUE TITLE
Security policy is missing

### ISSUE THREAD

**Issue by JamieSlome** [zammad/zammad#4142]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@dievus) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by mgruner** [comment]
Hi @JamieSlome. Thanks for contacting us, and I will also make sure to add the suggested file in our repo.
For now, please use security@zammad.com to send us your findings.

**Comment by JamieSlome** [comment]
@mgruner - we will get an e-mail to you shortly. Appreciate your diligence.
