### ISSUE TITLE
LDAP import job no longer starts automatically

### ISSUE THREAD

**Issue by 7qbit** [zammad/zammad#4143]
### Infos:

* Used Zammad version: 5.2
* Installation method (package)
* Operating system: Ubuntu 20.04
* Database + version: Postgresql 14+238
* Elasticsearch version: 7.17.4
* Browser + version: Firefox 101

### Expected behavior:

* since update to “zammad 5.2” LDAP import does not start automatically.

### Actual behavior:

*
    The scheduler no longer starts importjobs every hours. this must be started manually

Scheduler.find_by(method: ‘ImportJob.start_registered’).last_run
=> Thu, 23 Jun 2022 07:34:45.896000000 UTC +00:00

Delayed::Job.count
=> 0

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Since nobody on the community board replied after 2 hours ( https://community.zammad.org/t/since-update-to-5-2-ldap-import-job-no-longer-starts-automatically/9524 ) we now also have this issue.

**Comment by MrGeneration** [comment]
We could verify the issue.
For the next time, for the sake of everyones time management, please decide for one plattform and be patient.
