### ISSUE TITLE
MultiSelects do not allow storing values in tickets with MariaDB

### ISSUE THREAD

**Issue by No15pecial** [zammad/zammad#4148]
### Infos:

* Used Zammad version: Both 5.1 and 5.2
* Installation method (source, package, ..): Package
* Operating system: Ubuntu Server 20.04
* Web Server Apache2
* Database + version: **MariaDB** 
* Elasticsearch version:
* Browser + version: Mozilla Firefox 101.0.1 64 bit

### Expected behavior:

*

### Actual behavior:

*  Zammad version 5.1 introduced MutiliSelect fields. These MultiSelect fields throw an error (invalid value '[“ABC”, “ZZZ”]; for field “test”!) and stop ticket creation if you are using a MariaDB (works fine if using PostgreSQL). Version 5.2 is the same ticket creation is inhibited if using a MariaDB

### Steps to reproduce the behavior:

* install MariaDB, Apache2, ElasticSearch and Zammad 5.1 or 5.2 on a server that uses MariaDB, create a multiselect field and try to create a ticket 

Yes I'm sure this is a bug and no feature request or a general question.
![Z0](https://user-images.githubusercontent.com/46358941/176212973-400a313c-c7c5-41be-9a5e-359b5febc07c.png)

**Comment by MrGeneration** [comment]
what the heck is `Bpyh` supposed to mean?
Also, please provide error messages if any.

"Throws an error" *is not* an error message.
Also provide used browser and it's version please.

**Comment by No15pecial** [comment]
@MrGeneration 

BPYH is a typo it should have read Both ... I corrected that so as not to confuse 


The error it throws is invalid value '[“ABC”, “ZZZ”]; for field “test”!   I created a multiselect field called test with the options  123, ABC, 123, ZZZ. aaa, bbb When creating the ticket I selected the values ABC and ZZZ  ... Edited to add this Also 


Browser is Mozilla firefox 101.0.1 64 bit  ... Edited to add this 

Included a screenshot of the displayed error that it throws on the browser screen.
![Z0](https://user-images.githubusercontent.com/46358941/176213346-b2ce2cc8-8825-41d6-ae75-0af1719720bd.png)

**Comment by No15pecial** [comment]
Note I did post about this in the community forum and there is at lease one other individual who has experienced the same issue. 

`https://community.zammad.org/t/bug-or-user-error-multiselect-field-produces-an-error-invalid-value-for-field/9171/14`

[https://community.zammad.org/t/bug-or-user-error-multiselect-field-produces-an-error-invalid-value-for-field/9171/14](url)

**Comment by MrGeneration** [comment]
This is my verify object configuration:
![image](https://user-images.githubusercontent.com/6549061/176439827-b422ad2f-d3e5-4a18-92c5-9501ede9cae5.png)

This is the traceback to the above mentioned error message:
```
I, [2022-06-29T14:46:39.698089 #5805-109480]  INFO -- : Started PUT "/api/v1/tickets/1?all=true" for 192.168.2.19 at 2022-06-29 14:46:39 +0200
I, [2022-06-29T14:46:39.700992 #5805-109480]  INFO -- : Processing by TicketsController#update as JSON
I, [2022-06-29T14:46:39.701030 #5805-109480]  INFO -- :   Parameters: {"number"=>"46001", "title"=>"Welcome to Zammad!", "group_id"=>"1", "owner_id"=>1, "customer_id"=>2, "state_id"=>"1", "priority_id"=>"2", "updated_at"=>"2022-06-29T12:35:28.451Z", "preferences"=>{}, "organization_id"=>1, "pending_time"=>nil, "multiselect"=>["xx", "yy"], "id"=>"1", "all"=>"true"}
E, [2022-06-29T14:46:39.752382 #5805-109480] ERROR -- : Invalid value '["xx", "yy"]' for field 'multiselect'! (Exceptions::ApplicationModel)
app/models/concerns/checks_core_workflow.rb:37:in `block in check_restrict_values'
app/models/concerns/checks_core_workflow.rb:32:in `each_key'
app/models/concerns/checks_core_workflow.rb:32:in `check_restrict_values'
app/models/concerns/checks_core_workflow.rb:27:in `validate_workflows'
app/controllers/tickets_controller.rb:256:in `block in update'
app/controllers/tickets_controller.rb:255:in `update'
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
I, [2022-06-29T14:46:39.753719 #5805-109480]  INFO -- : Completed 422 Unprocessable Entity in 53ms (Views: 0.1ms | ActiveRecord: 4.8ms | Allocations: 44409)
```

Does affect MariaDB / MySQL only, PGSQL is running fine.
I'd expect our software tests to cover both MariaDB and PGSQL scenarious if not handled already.

**Comment by rolfschmidt** [comment]
Looks like it is a rails issue. For some reason the database schema is different for maria/mysql and rails is not able to detect it as a json column.

Base implementation https://github.com/rails/rails/pull/21110

There is one guy that found a workaround https://github.com/rails/rails/issues/44997#issuecomment-1114903733. Seems like we need to transform this into an dynamic solution for our object manager attributes.

**Comment by rolfschmidt** [comment]
Many users are still on ubuntu 20.4 which is using mariadb 10.3 which is not supporting https://mariadb.com/kb/en/json_valid/ yet. Need another fix.
