### ISSUE TITLE
Trigger Attribute "action > is > updated" is not working after Zammad 5.2 update

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#4153]
### Infos:

* Used Zammad version: 5.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket: 10109815, 10108694, 10109960, 10106935

### Expected behavior:

When I create a trigger with the following attributes:
Status > is > closed
action > is > updated

EXECUTE CHANGES ON OBJECTS:
E-mail > Public > Customer

When I change the Ticket status from "open" to "closed" and leave a note, I expect that the trigger sends an email to the customer.

### Actual behavior:

The Trigger does not work and not email is send

### Steps to reproduce the behavior:

Step 1:
Create a trigger with the following attriburtes:
Status > is > closed
action > is > updated

EXECUTE CHANGES ON OBJECTS:
E-mail > Public > Customer
- write some content in the e-mail header and body
- save the trigger

Step 2.
- create a test Ticket
- leave a note and change the staus to closed
- update the ticket

[Screen Recording (29.06.2022 15-43-02).wmv.zip](https://github.com/zammad/zammad/files/9011093/Screen.Recording.29.06.2022.15-43-02.wmv.zip)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
https://community.zammad.org/t/trigger-condition-created-not-longer-working/9557/8

**Comment by rolfschmidt** [comment]
Seems like the ticket selector **ticket action** got broken because it falsely shows a multiple select field instead of the single select field. Existing triggers should be fine if they don't get touched. New ones will not worked because of that.
