### ISSUE TITLE
The webhook could not be saved by Telegram, seems to be an invalid URL.

### ISSUE THREAD

**Issue by nanosacred** [zammad/zammad#4156]
### Infos:

* Used Zammad version: 5.2.x
* Installation method (source, package, ..): package
* Operating system: debian 11
* Database + version: PostgreSQL 13
* Elasticsearch version: 7.17.5
* Browser + version: brave latest
* Tickets: #10110974, #10111166, Ticket#10113458

### Expected behavior: telegram bot connects securely with API token

*

### Actual behavior: failure to connect to telegram bot, with error:
The webhook could not be saved by Telegram, seems to be an invalid URL.

*

### Steps to reproduce the behavior:
try to add a telegram bot in Zammad.  The Zammad website is publicly available on a secure connection https. 
*

Yes I'm sure this is a bug and no feature request or a general question.
[production.log](https://github.com/zammad/zammad/files/9030966/production.log)

**Comment by jonans91** [comment]
Hello,
Same issue here with the same environment.

**Comment by rolfschmidt** [comment]
https://community.zammad.org/t/telegram-channel-error-the-webhook-could-not-be-saved-by-telegram-seems-to-be-an-invalid-url/9598
