### ISSUE TITLE
Ticket is not opened, nothing can be viewed if auto assignment selector in admin interface has no value selected

### ISSUE THREAD

**Issue by MustafaTongul** [zammad/zammad#4157]
### Infos:

* Used Zammad version: any
* Installation method (source, package, ..): any
* Operating system: any 
* Database + version: 5.2.x
* Elasticsearch version: any 
* Browser + version: any 
* Ticket#10110220

### Expected behavior:

* Ticket is opened by default and can be viewed. The agent who opened the ticket is set as the owner.

### Actual behavior:

* Ticket is not opened, nothing can be viewed
* ![image](https://user-images.githubusercontent.com/76220675/177106791-7fc2e77d-9b66-496e-a591-47aa4ab4094f.png)

### Steps to reproduce the behavior:

* activate "auto assignment" feature
* don't select any conditions
* save settings
* create test ticket as customer
* try to open test ticket as an agent

**Comment by Bozo0511** [comment]
![Screenshot 2022-07-04 162606](https://user-images.githubusercontent.com/94919964/177175148-ddd28e13-5f3c-484f-a18d-36635f9dc221.png)

Screenshot from the developer console of Chrome

**Comment by Bozo0511** [comment]
![Screenshot 2022-07-04 163716](https://user-images.githubusercontent.com/94919964/177176250-da474bbc-8c6c-415a-8b17-a901407951ba.png)
