### ISSUE TITLE
Elasticsearch 8 incompatible with Zammad 5.2

### ISSUE THREAD

**Issue by davidknezic** [zammad/zammad#4158]
### Infos:

* Used Zammad version: 5.2.0-20
* Installation method (source, package, ..): Docker compose
* Operating system: Linux
* Database + version: 13
* Elasticsearch version: 8.3.1
* Browser + version: -

### Expected behavior:

According to the docs, Zammad 5.2 and above started supporting Elasticsearch 8.

<img width="292" alt="Screenshot 2022-07-04 at 11 09 22" src="https://user-images.githubusercontent.com/198988/177123150-e7f7c35f-d6ac-43cb-a48c-f7dd27b6750d.png">

### Actual behavior:

Unfortunately, we receive `Version 8.3.1 of configured elasticsearch is not supported` when running `zammad-init`:

![paste (34)](https://user-images.githubusercontent.com/198988/177123211-12c4e5c3-a583-42dd-84a9-f2c8f728c338.png)

### Steps to reproduce the behavior:

Run image `zammad/zammad-docker-compose:zammad-5.2.0-20` with command `zammad-init` with Elasticsearch 8 or above.

There's commit https://github.com/zammad/zammad/commit/df710d3740a822ce48ebdf1dcbcc21b02c79f60e by @mgruner which added support for Elasticsearch 8 (< 9). However, looking at [search_index_backend.rb](https://github.com/zammad/zammad/blob/stable/lib/search_index_backend.rb) it doesn't seem to have made it into `stable`.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by davidknezic** [comment]
Thanks a lot @mgruner! Just tested with the new `zammad/zammad-docker-compose:zammad-5.2.0-22` and it works flawlessly. 🥳

**Comment by mgruner** [comment]
👋
