### ISSUE TITLE
High Availability / Failover Setup

### ISSUE THREAD

**Issue by volands** [zammad/zammad#416]
Hi,

I currently search a possibility to achieve a High Availability / Failover setup for Zammad (by horizontal scaling or scale out). 

Unfortunately I can't find anything according to this in the official resources:
zammad Documentation, zammad Github repository/issues, zammad-users group, zammad-dev group

Does a documentation or recommendation exist in this context? And if so, where can this be found?

If I see it right, Zammad consists of two main parts:
1) Database (PostgreSQL, MySQL or MariaDB)
2) Ruby Application (web application server, worker process, websocket server)
+ optional: Elasticsearch

For example for the database I can setup a postgres cluster with master-slave failover/redundancy and such as haproxy in front of it.

At the second step I'm not sure yet. I think it is not sufficient to deploy multiple instances of the whole ruby application and setup a reverse proxy in front of it. In this way every application instance uses their own data directory - so it seems to be neccessary to replicate the data directory permanently over the mutiple instances or simply use a central shared data directory for all?

I hope that my remarks are understandable...
Thanks and best regards,
Patrick

**Comment by monotek** [comment]
Beside a database cluster (Mariadb galera or postgres) you just need a shared storage (Glusterfs, ceph, NFS,...) where you put the files on. 

Not sure if it's a problem to run puma, websockets server and scheduler on several machines at the same time. 

If it's a problem use keepalived to migrate a floating ip and start the services on the other node when one dies.

If it's no problem you're able to scale by putting a nginx as loadbalancer in front of your ruby process nodes where the nginx loadbalancer has a failover machine via keepalived available.

Elasticsearch has failover feature available out of the box.

@martini
Is it a problem to have puma, websockets and schedulers processes on several servers at the same time?

**Comment by volands** [comment]
Thank you very much for your fast reply - your informations are very helpful.

I think the database/pgsql and proxy/nginx part is clear to me so far. Regarding the app part I will wait for more information on that from martini.

Concerning the shared storage I currently think about the possibility to use an Openstack Swift Object Storage - specifically I could use "svfs" (https://github.com/ovh/svfs; based on fuse and rsync) to locally mount an single/central object storage bucket simultaneously on the multiple instances. Do you see any potential problems in this context?

In case of optional Elasticsearch I will deal with its native failover capabilities. Short question: from which zammad data/installation size on do you recommend the use of Elasticsearch?

**Comment by rkaldung** [comment]
Before setting up a complete cluster with I strongly suggest if sth. like VMware HA, AWS availability zones, etc fulfill your SLA. Most of the times this is sufficient enough. What's the SLA you have to provide?

**Comment by monotek** [comment]
Don't know svfs but rsync does sound as this is an asynchronous solution which indeed could be a problem.

Maybe you could also try to store attachments in the db. In this case you may be able to abandon a shared storage completely.

Currently I can't say when elasticsearch should come in place. Just use it when you get unhappy with the search performance.

**Comment by martini** [comment]
> @martini
> Is it a problem to have puma, websockets and schedulers processes on several servers at the same time?

It's no problem. You can work with multiple processes for puma, websockets and schedulers on several servers.

**Comment by volands** [comment]
So, many thanks to all for the great support!

I've decided to use a GlusterFS shared storage for the data directory (it's right, svfs is asynchronous and seems to be not very performat for this purpose). Database part is done by a clustered PostgreSQL. I now run Zammad with the discussed setup on two Docker Cluster nodes in two different geographical regions and it works fine so far.

I think this issue can be closed. A last modest note from my side: perhabs your informations can also be very helpful for other users - maybe you could add some words in the Zammad documentation concerning this?

**Comment by monotek** [comment]
Feel free to write it down and create a pull request @ https://github.com/zammad/zammad-documentation ;-)
