### ISSUE TITLE
Postmaster Filter won’t set multi_tree_select values

### ISSUE THREAD

**Issue by herzkerl** [zammad/zammad#4163]
### Infos:

* Used Zammad version: 5.2.1
* Installation method (source, package, ..): package
* Operating system: Debian 10
* Database + version: PostgreSQL (newest)
* Elasticsearch version: newest 
* Browser + version: Safari, newest

### Expected behavior:

PERFORM ACTION OF THE FOLLOWING *

* I’d expect Postmaster Filter to work with ‚multi_tree_select‘ options exactly the way it does within Triggers, Automations, etc.

### Actual behavior:

* Postmaster Filter won’t let you select multiple values from a ‚multi_tree_select‘ object
* Postmaster Filter will make it look like it would set a single value from your ‚multi_tree_select‘ object, but it doesn't

### Steps to reproduce the behavior:

* Create a custom ticket object of type ‚multi_tree_select‘ with some options
* Create a Postmaster Filter and create an action for your new object—you’ll notice that you can’t select multiple options, and the select option looks like text, not like an object

#### Postmaster Filter—not possible to select multiple options, but get’s filled with the text from the selected option
<img width="715" alt="Bildschirmfoto 2022-07-06 um 18 32 15" src="https://user-images.githubusercontent.com/29686843/177600495-1bdefd5d-6e77-4370-9e12-aae2fadab770.png">

#### Triggers–possible to select multiple options, and works as expected
<img width="632" alt="Bildschirmfoto 2022-07-06 um 18 41 45" src="https://user-images.githubusercontent.com/29686843/177601155-53669395-44cd-4d55-8002-0373c218928e.png">

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
will be fixed with #4206 as well
