### ISSUE TITLE
Agents with read rights do not see knowledgebase 

### ISSUE THREAD

**Issue by ABS-IT-Wiesbaden** [zammad/zammad#4164]
### Infos:

* Used Zammad version: 5.2.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04
* Database + version: postgres 12.11
* Elasticsearch version: 7.17.5
* Browser + version: Google Chrome 103.0.5060.114

### Expected behavior:

An agent can see a knowledge base if he/she has read right on it.

### Actual behavior:

An agent can only see a knowledge base if he/she has edit rights on it. With read rights only the knowledgebase is not visible.

### Steps to reproduce the behavior:

1. Create a knowledgebase
2. Create a role with read rights only on the knowledgbase in general and assign it to an agent
3. Give the role the read write on the knowledgebase

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by cautopartes** [comment]
Works for me as expected, after following the steps to reproduce the behavior I cannot confirm it.
