### ISSUE TITLE
After package upgrade LDAP Syncs remove all roles from admins and agents

### ISSUE THREAD

**Issue by strangechoice** [zammad/zammad#4168]
### Infos:

* Used Zammad version: 5.2.0-1655930361.bf8b71d8.bullseye
* Installation method (source, package, ..): deb https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 11 main
* Operating system: Debian 11
* Database + version: PostgreSQL 13.7
* Elasticsearch version: 6.8.23
* Browser + version: FF 102.0
* LDAP-Settings:
`irb(main):005:0> p LdapSource.find(1)
 id: 1,
 name: "LDAP #1",
 preferences:
  {"host_url"=>"ldaps://ldap.phil.hhu.de",
   "ssl_verify"=>true,
   "options"=>{"ou=Phil-Fak,o=HHU,c=de"=>"ou=Phil-Fak,o=HHU,c=de"},
   "option"=>"ou=Phil-Fak,o=HHU,c=de",
   "base_dn"=>"ou=Phil-Fak,o=HHU,c=de",
   "bind_user"=>"cn=admin,ou=phil-fak,o=hhu,c=de",
   "bind_pw"=>"VERYSECUREPW",
   "wizardData"=>
    {"backend_user_attributes"=>
      {"dn"=>"dn (e.g., cn=zerbe,ou=hp-ilo,ou=systemusers,ou=Phil-Fak,o=HHU,c=de)",
       "uid"=>"uid (e.g., zerbe)",
       "gidnumber"=>"gidnumber (e.g., 100)",
       "userpassword"=>"userpassword (e.g., {SSHA}rliCyWR2hJzl1mwK+XLyY9kPNI9PSHZm)",
       "cn"=>"cn (e.g., Sebastian Zerbe)",
       "homedirectory"=>"homedirectory (e.g., /home/zerbe)",
       "uidnumber"=>"uidnumber (e.g., 1596)",
       "loginshell"=>"loginshell (e.g., /bin/bash)",
       "gecos"=>"gecos (e.g., Sebastian Zerbe)",
       "shadowlastchange"=>"shadowlastchange (e.g., 12690)"},
     "backend_groups"=>
      {"cn=admin,ou=hp-ilo,ou=groups,ou=phil-fak,o=hhu,c=de"=>"cn=admin,ou=hp-ilo,ou=groups,ou=phil-fak,o=hhu,c=de",
       "cn=iml,ou=hp-ilo,ou=groups,ou=phil-fak,o=hhu,c=de"=>"cn=iml,ou=hp-ilo,ou=groups,ou=phil-fak,o=hhu,c=de"},
     "user_attributes"=>
      {"login"=>"Login",
       "firstname"=>"First name",
       "lastname"=>"Last name",
       "email"=>"Email",
       "web"=>"Web",
       "phone"=>"Phone",
       "mobile"=>"Mobile",
       "fax"=>"Fax",
       "department"=>"Department",
       "address"=>"Address",
       "note"=>"Note"},
     "roles"=>{"1"=>"Admin", "2"=>"Agent", "3"=>"Customer", "4"=>"pcadmin_agent"}},
   "user_uid"=>"uid",
   "user_filter"=>"(objectClass=pfNameinfo)",
   "group_uid"=>"dn",
   "group_filter"=>"(objectClass=posixgroup)",
   "user_attributes"=>{"uid"=>"login", "pffirstname"=>"firstname", "pfsurname"=>"lastname"},
   "group_role_map"=>
    {"cn=hoi,ou=groups,ou=phil-fak,o=hhu,c=de"=>["1"],
     "cn=wheel,ou=groups,ou=phil-fak,o=hhu,c=de"=>["1"],
     "cn=pcadmin,ou=groups,ou=phil-fak,o=hhu,c=de"=>["2"],
     "cn=pcadmin_agents,ou=groups,ou=phil-fak,o=hhu,c=de"=>["4"]},
   "unassigned_users"=>"sigup_roles"},
 active: true,
 prio: 0,
 updated_by_id: 1,
 created_by_id: 1,
 created_at: Wed, 22 Jun 2022 12:57:31.105811000 UTC +00:00,
 updated_at: Wed, 22 Jun 2022 12:57:31.105811000 UTC +00:00>`
...

### Expected behavior:

* Package upgrades should work and role assignments via LDAP should be kept

### Actual behavior:

* Since update to version _5.2.0-1655823239.56c5f3a0.bullseye_ no more ldap syncs are executed (2022-06-22)
* upgrade to version _5.2.0-1655930361.bf8b71d8.bullseye_ still without ldap syncs (2022-06-24 00:15)
* an upgrade to _5.2.0-1655999989.ea2eb628.bullseye_ fixed the sync issue, but all role assignments get lost on sync (2022-06-24 12:30) 
* we had to restore from backup to version _5.2.0-1655930361.bf8b71d8.bullseye_
* another try to upgrade to _5.2.1-1657050006.30d94ce6.bullseye_, fixes sync issue, but all role assignments get lost on sync (2022-07-06 13:00)
* restore from backup to version _5.2.0-1655930361.bf8b71d8.bullseye_

### Steps to reproduce the behavior:

* package upgrade...

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Zammad 5.2.0 is outdated and prune to security issues.

Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by MrGeneration** [comment]
I'm unable to reproduce the issue you're discribing.

**Comment by strangechoice** [comment]
I'm not sure why you are considering this a technical question rather than a bug. It seems to be related to the introduction of Multi LDAP integration in Version _5.2_. The migration of our LDAP configuration by package means seems to have worked (as shown above). It is now located in _ldap_sources_ instead of _settings_ table. Only #4143 was preventing us from noticing this bug earlier.

**Comment by rolfschmidt** [comment]
@strangechoice #4143 is only enabling the process again that the sync runs in interval. Maybe something was already odd with the configuration before. It's impossible to debug this with the information given in this issue. I can tell you that a lot of users including our self using the ldap sync and currently I'm not aware about support tickets with this behaviour so it might be something related to your specific config.

You could try to create a test instance and configure your ldap server freshly via UI and if it works we could compare the configurations and see if there was a difference. Normally if the sync works it should also assign the roles back again.

The production.log might also be helpful to find out if there is any crash or stuff like that happening.

**Comment by hendrikreuhl** [comment]
We experience the same bug with our installation. After upgrading to the multi LDAP version, our admin and agent accounts get their permissions removed and become normal customer accounts. Does the new version enforce the memberOf overlay?

**Comment by dominikklein** [comment]
There was no feedback with more information about the problem. So currently we are unable to reproduce the problem and also we didn't receive any additional problems in this direction in the meanwhile. Feel free to contact us with more information.
