### ISSUE TITLE
Documentation: Facebook-App and permissions

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#417]
Hi,

the Zammad-doc says that the Facebook app to manage my site needs the permissions "manage_pages" and "publish_pages". Getting these permissions is a pain in the ass, including upload a video, create an app logo etc.

I wondered why the Facebook integration works before that was approved and finally got the response today:

![zammad_facebook](https://cloud.githubusercontent.com/assets/3321655/20282429/f0994cfa-aab4-11e6-96f7-7453f673c2b8.jpg)

Maybe the doc should be updated to make this more clear ... and save unnecessary work for our Zammad admins ;-)

**Comment by martini** [comment]
It's new to me. I'll check it.

**Comment by osixia** [comment]
Same here really painfull :(

**Comment by thorsteneckel** [comment]
We'll update the documentation as soon as possible. To give you an early access/workaround follow these screenshots (no further description available currently):

Login to Facebook and start here: https://developers.facebook.com/apps/

![1](https://user-images.githubusercontent.com/3873515/32327739-edb7c302-bfd7-11e7-8b56-9692e4aca5b2.png)
![2](https://user-images.githubusercontent.com/3873515/32327740-edcf6ffc-bfd7-11e7-9525-fb9cd4132321.png)
![3](https://user-images.githubusercontent.com/3873515/32327741-edf22006-bfd7-11e7-96a2-e4e038e3c502.png)
![4](https://user-images.githubusercontent.com/3873515/32327742-ee146b0c-bfd7-11e7-8b36-9eb1c45c8fa4.png)
![5](https://user-images.githubusercontent.com/3873515/32327743-ee324276-bfd7-11e7-87bf-48f7cb6124ac.png)
![6](https://user-images.githubusercontent.com/3873515/32327745-ee4e795a-bfd7-11e7-8572-80b5c3a8e19f.png)
![7](https://user-images.githubusercontent.com/3873515/32327746-ee6b9f94-bfd7-11e7-9c1e-4d086d8c2759.png)
![8](https://user-images.githubusercontent.com/3873515/32327747-ee885102-bfd7-11e7-8307-c52909a9b652.png)
![9](https://user-images.githubusercontent.com/3873515/32327748-eea3c04a-bfd7-11e7-8770-3bbb92a0e332.png)
![10](https://user-images.githubusercontent.com/3873515/32327749-eec0f160-bfd7-11e7-8112-8ec27361ca2c.png)
![11](https://user-images.githubusercontent.com/3873515/32327750-eeff0450-bfd7-11e7-9917-7236fdad9bae.png)

**Comment by thorsteneckel** [comment]
This will be addressed in the linked admin documentation issue. Closing now.

**Comment by jozephbrasil** [comment]
I am trying to integrate facebook to Zammad but Facebook always decline my request to obtain manage_pages and publish_pages permission. Anyone could PLEASE share with me the video (screencast) used to obtain access to it? I am getting frustrated with this.

**Comment by MrGeneration** [comment]
Please do not recycle closed issues.
Also, this is not the right place, our community is a better place for this: https://community.zammad.org .

I doubt sharing a screencast will work cleanly or at least someone will share it with you, as it might contain sensitive information.
