### ISSUE TITLE
Tree select not proper in Report

### ISSUE THREAD

**Issue by puni420** [zammad/zammad#4174]
### Infos:

* Used Zammad version: 5.2
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any 
* Tickets: #10111596, #10111527

### Expected behavior:

*In report on if an object type with tree_select should display something like AAABBBCCC

### Actual behavior:

*But In report on an object type with tree_select is something like CCC. This is happening only after updating to latest version.

### Steps to reproduce the behavior:

*Create custom field type “Tree select” for ticket
Add Parent AAA
Add Child BBB for parent AAA
Add child CCC for parent BBB
Go to reports and download Ticket with this custom filed
In excel there will be only BBB instead of AAABBBCC

Yes I'm sure this is a bug and no feature request or a general question.

![image](https://user-images.githubusercontent.com/109282338/178969154-cce229e3-716e-4ec9-86ba-70230468d736.png)

**Comment by rolfschmidt** [comment]
regression of https://github.com/zammad/zammad/commit/489d2e0a196918ee2f55981476e5488d14e343c0
