### ISSUE TITLE
Ticket templates do not save the owner attribute

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#4175]
### Infos:

* Used Zammad version: 5.2.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any 
* Tickets: #10110962

### Expected behavior:

* When using a ticket template, the owner attribute should be set according to how the owner was set when creating the template.   

### Actual behavior:

* When using a saved template, the owner attribute is always empty/not set. 

### Steps to reproduce the behavior:

* Create a ticket template
* Fill in the owner attribute and save the template
* Apply the created template as base for a new ticket
* -> Owner is not set any more 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by wuerglerocc** [comment]
Hi guys
In Version 5.2.3 this occurs to be broken again. The template is saved correctly, but if i want to apply it, it wont set the owner.
