### ISSUE TITLE
CacheClearJob.perform_now might not run if timeplans time window of 10 minutes is missed

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4179]
### Infos:

* Used Zammad version: 5.2.0 and 5.2.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket#: - (affects all installation types)

### Expected behavior:

`CacheClearJob.perform_now` method runs in the designated timeplan and is "flexible" if the system is under fairly high load which delays it's execution.

### Actual behavior:

If your instance is under fairly high load you may experience Zammads monitoring spitting out this monitoring warning:
`scheduler may not run (last execution of CacheClearJob.perform_now 7 days ago) - please contact your system administrato`

This is caused by a daily scheduler task that can run in an exactly 10 minute time frame on 24:00 UTC.
If the job isn't run every 24 hours, monitoring will alert.

This can take a day or, if unlucky, several days to self heal. While this is not a real big issue, it blocks monitoring and creates fairly high change false positive. High false positive rates cause administrators to ignore warnings and due to this may slip really important things.

Manual re-running is not possible, as the time plan of the method is being enforced.

### Steps to reproduce the behavior:

* have a instance that's unable to run the cache clear scheduler task of `CacheClearJob.perform_now` method within 10 minutes of a day

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rmundel** [comment]
I'm on 5.2.1 and almost went nuts with this 😆
