### ISSUE TITLE
Switching on/off integrations (e.g. LDAP + Exchange) leads to unpredictable results

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4181]
### Infos:

* Used Zammad version: 5.2 / develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Switching on/off different integrations should work fine without any unpredictable results.

### Actual behavior:

* By switching on/off different integrations, it could happen that all integrations got disabled or even that a previously disabled integration is enabled again.

### Steps to reproduce the behavior:

* Navigate to the integrations page (`#system/integration`).
* Click on `LDAP` and enable it.
* Go back, click on `Exchange` and enable it.
* Go back, now both `LDAP` and `Exchange` should be enabled.
* Click on `LDAP` again and disable it.
* Go back, now `LDAP` is disabled, but in my test `Exchange` is disabled as well.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by ArkaprabhaChakraborty** [comment]
I'm new to this community. How can I contribute to this project?

**Comment by fliebe92** [comment]
> I'm new to this community. How can I contribute to this project?

Hey @ArkaprabhaChakraborty, thanks for your interest to make Zammad even better.

Please have a look here: https://zammad.org/participate

Have a nice day! 😎

**Comment by ArkaprabhaChakraborty** [comment]
I need some guidance on how to solve this bug :)

**Comment by rolfschmidt** [comment]
@MrGeneration can you agree to this and provide us some information about what the expected behaviour should be ? I also think this issue needs specification.

**Comment by MrGeneration** [comment]
Enabling each integration independly should be no problem.
Disabling one single one should never disable other ones as well.

**Comment by mgruner** [comment]
Even worse: Open first LDAP, then Icinga (both inactive). Then activate Icinga. In the screen, content from the LDAP panel will be injected, probably because multiple panels are executed at the same time. This leads to a broken screen.

<img width="1354" alt="Bildschirm­foto 2023-02-13 um 09 47 20" src="https://user-images.githubusercontent.com/211281/218415190-df6e2e6e-0a8d-43d8-8c91-22ce39015cb7.png">
