### ISSUE TITLE
 Customer can see groups for brief moment (for 0.7sec)

### ISSUE THREAD

**Issue by Dante4** [zammad/zammad#4183]
### Infos:

* Used Zammad version: 5.2.0-1656402719 && 5.3.0-alpha build 6938
* Used Zammad version 2: 5.2.1-1658294547
* Used Zammad installation type: package
* Operating system: Ubuntu 18.04 (server)
* Operating system: Ubuntu 20.04 (server)
* Database + version: postgresql 10.21 
* Database + version 2: postgresql 12.11 
* Elasticsearch version: 7.17.1
* Elasticsearch version 2: 8.3.2
* Browser + version: Firefox 94.0.2 && Firefox 102.0 && Edge 103.0.1264.62
* Hardware: Checked on local NVMe U.2 disk with dual socket (12+12 cores) 2.8GHz system, so it's not related to slow hardware

### Expected behavior:

* Customer can’t see group on ticket creation (based on multiple tries time is around 0.7 sec, not 1.5 as i stated on first submission, sorry)

### Actual behavior:

* Customer can see groups for brief moment on ticket creation (gif is slowed down on purpose, because there is a windows enough just to click to see what groups are)
* ![Alt Text](https://community.zammad.org/uploads/default/original/2X/b/bdbba192b5cc6337231f3a100232d915d42bb9f4.gif)

### Steps to reproduce the behavior:

* Login as customer and click on ticket creation

_Yes I'm sure this is a bug and no feature request or a general question._

**Comment by MrGeneration** [comment]
Also was posted in the community:
https://community.zammad.org/t/customer-can-see-groups-for-brief-moment-0-7-sec/9709

**Comment by cautopartes** [comment]
I could not reproduce this in a recent version (5.3.1-1673280162.a07ec54e.bullseye). I tested with a CPU load of about 8 with two cores available and RAM at full capacity.
