### ISSUE TITLE
HTML comments/conditions being rendered from emails

### ISSUE THREAD

**Issue by Wardrop** [zammad/zammad#4184]
### Infos:

* Used Zammad version: 5.2.x
* Installation method (source, package, ..): Source
* Operating system: OpenSUSE 15.3
* Database + version: 10.5.15-MariaDB
* Elasticsearch version:  7.17.5
* Browser + version: Chrome 103

### Expected beha
Zammad should ignore (i.e. strip/remove) conditional comments in HTML of the format <![xxx]>, for example <![if !vml]><![endif]>. These shouldn't be displayed in the article/ticket content.

### Actual behavior:
Zammad displays such conditional comments, e.g. <![if !vml]><![endif]>. These are non-standard HTML comments introduced by Microsoft (of course) known as "Downlevel-revealed conditional comments" according to [Wikipedia](https://en.wikipedia.org/wiki/Conditional_comment). All browsers ignore these, but Zammad must be escaping the characters as they're displayed in the rendered html output.

We've only observed this since upgrading from Zammad 5.1.x to 5.2.x.

![image](https://user-images.githubusercontent.com/201442/180670968-657329a8-c135-41c8-837f-f4b46bc00b5b.png)

### Steps to reproduce the behavior:
Injest email into zammad that contains such conditional formatting, typically generating by Outlook/Word.

**Comment by Wardrop** [comment]
I wonder if fixing https://github.com/zammad/zammad/issues/4112 has perhaps caused this problem?

**Comment by Zellular82** [comment]
Same Problem here after Update to 5.2.x

![grafik](https://user-images.githubusercontent.com/49199889/181711831-b2d69b20-d88e-4b4d-83fe-4a20dc06b396.png)

**Comment by fliebe92** [comment]
Hi @Wardrop, hi @Zellular82 👋 

Could you please provide some test emails (without confidential data)? This would help us to debug the reported behavior.

**Comment by Zellular82** [comment]
Hi fliebe92! 👋
Thanks for your help.

[Test.zip](https://github.com/zammad/zammad/files/9218203/Test.zip)

**Comment by fliebe92** [comment]
> Hi fliebe92! 👋 Thanks for your help.
> 
> [Test.zip](https://github.com/zammad/zammad/files/9218203/Test.zip)

Hey @Zellular82, thanks for your test mail. Unfortunately, I am not able to import it. I need to check why...

Maybe you can download the raw mail in Zammad and attach it to this issue.

**Comment by MrGeneration** [comment]
> Hey Zellular82, thanks for your test mail. Unfortunately, I am not able to import it. I need to check why...

That's because your machines load is different. You need to stress the relevant cores running it to cause 20s+ delays for processing.

**Comment by Wardrop** [comment]
Try this example email. If I drag and drop this into the mailbox Zammad looks at in Outlook, it reproduces the issue.

[Test ticket.zip](https://github.com/zammad/zammad/files/9287503/Test.ticket.zip)

It should appear as follows:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/201442/183580130-d36afda0-ebba-4acb-b3be-023471fb5450.png">

**Comment by MrGeneration** [comment]
We're unable to use the `msg` file variants for several reasons:
* it forces us to export the messages in question via Outlook in order to receive the `eml` file we need
* it works on our machines™️
* when exporting the message as mentioned above the issue disappears because our clients create a `winmail.dat` which contains the fuck up (most likely)

So if you wanna help, please provide the original EML. Zammad provides it via the Raw link. Other wise we're unable to further investigate and will be forced to closed the issue without a proper fix.

**Comment by Wardrop** [comment]
Yeah no worries. See original EML file attached; not sure why I provided the MSG formatted email originally. Hopefully you can replicate the issue with this.

[ticket-10212-918.zip](https://github.com/zammad/zammad/files/9294970/ticket-10212-918.zip)
