### ISSUE TITLE
multi_tree_select: field is used, but browser says it is empty

### ISSUE THREAD

**Issue by JPRBM** [zammad/zammad#4188]
### Infos:

* Used Zammad version: 5.2.x
* Installation method (source, package, ..): hosted by zammad.com
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: any
* Tickets: #10111672

### Expected behavior:

When the field is filled with a least one value you can update the ticket

### Actual behavior:

The field is filled, but the browser shows a toolbox that the field needs to be filled in order update the ticket

![image](https://user-images.githubusercontent.com/110032450/180995858-72246e31-23b3-42b2-91ca-46c1372bac1f.png)

Now the ticket can not be updated or changed. I've found if I open the DevTools and edit the input field and remove "required" at the end that I am able to save the ticket.

### Steps to reproduce the behavior:

* create a ticket object of the multi_tree_select type that is required to be filled
* go and create a new ticket
* try to save / update the ticket
* the browser won't let you submit the form

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
In case you're a paying customer (not trial), please contact Zammad support so that the colleagues can take the required steps. Thank you.
