### ISSUE TITLE
Contains one with more than one tag fails in report profiles

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4189]
### Infos:

* Used Zammad version: 5.2 stable (latest)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket#:1099685

### Expected behavior:

Having a report profile configured `tag` `contains one` and two tags does return all tickets that contain either tag.

### Actual behavior:

Having a report profile configured `tag` `contains one` and two tags does return *all tickets* containing the tag **OR** the word of either tag in e.g. articles.

This does only seem to affect report profiles, overviews work as expected.
Advanced search `tags: ("tag1" OR "tag2")` does work as expected.

### Steps to reproduce the behavior:

* create a report profile with one filter:
  `tags contains one [tag1, tag2]
* have tickets that do not contain either of those tags and write tag name into e.g. article and submit

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Hi,
sorry I can't reproduce the issue with the steps. For me it seems to work.

![grafik](https://user-images.githubusercontent.com/5445062/181454572-73584834-8d84-41ff-9a8e-f1285c770e39.png)

![grafik](https://user-images.githubusercontent.com/5445062/181454659-88216332-5e82-4177-ad6c-ffbb226a65e1.png)

**Comment by dvnkln** [comment]
No harsh intentions but i can't see if you tried to reproduce correctly by the given screenshots.

Add an article in ticket `t3` containing "t2" as a word (not the tag). It'll probably show up in your report - even though it shouldn't.
Ticket `t1.1` already seems like it's affected but i can't tell from the screenshot if it's tagged or not.

If this doesn't make the bug reproducable we have at least two indepent environments (our productive and MrGenerations lab) affected by this or there's a lot of miscommunication on how to reproduce this 😄.

**Comment by MrGeneration** [comment]
Also you may wanna remove the "contains not" clause as this is not part of our reproduction state.
This is the report profile configuration that causes the faulty behavior:

![image](https://user-images.githubusercontent.com/6549061/184649174-c8c0fe9a-abe0-45ab-a451-cb4ce9b5dfbd.png)
