### ISSUE TITLE
Unable to set owner + customer in postmaster/email filter

### ISSUE THREAD

**Issue by martini** [zammad/zammad#419]
It's a sub issue of https://github.com/zammad/zammad/issues/394

**Comment by martini** [comment]
Fixed https://github.com/zammad/zammad/commit/e7abac490f20e7967428c9acb0f1d4b3c541e499 for 1.0, 1.1 and develop.

**Comment by jacotec** [comment]
@martini Fixed for all, but what about "master"? How can a fix be backported into the stables, and the "stable" is now more up to date than master?

I thought, from your description, that the bugfix flow is like:

Develop (hot and untested) -> Master (tested develop stream) -> Stable (Release versions)

So if a fix goes directly into the stable ones, is should be included in Master as well. That's somewhat worrying ;-)
