### ISSUE TITLE
Knowledge base detail page has long loading times when kb has many categories

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4190]
### Infos:

* Used Zammad version: 5.2 / develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Only required assets should be returned.

### Actual behavior:

* Assets are quite big because a lot of not required assets are loaded (e.g. for categories which are not a sibling of the answer's category).

### Steps to reproduce the behavior:

* Create a huge knowledge base with at least 30 categories in one level.
* Assign different permissions to those categories (it's sufficient to set permission for one category).
* Create some answers. 
* Open this answer and notice that the Zammad frontend is quite busy (it took between 20-30 seconds to load an answer).
* By opening the browser console and using the network tab, you see that for the request to get the answer, a lot of unnecessary assets are returned.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
can now also easily reproduced by (only use on testsystems):
```
  FillDb.load(
    agents: 40,
    groups: 40,
    organizations: 40,
    knowledge_base_answers: 300,
    knowledge_base_categories: 60,
    nice: 0
  )
  ```

(thx to @fliebe92)

**Comment by fliebe92** [comment]
We were also able to break it down to `app/models/knowledge_base/category.rb`, line 49:

```rb
data = ApplicationModel::CanAssets.reduce(assets_siblings, data)
```
