### ISSUE TITLE
Core Workflows - Splitting does not remember all additionall attributes

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#4195]
### Infos:

* Used Zammad version: 5.2.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Tickets: #10111034

### Expected behavior:

* When splitting a ticket with prefilled custom attributes that are (only) shown via Core Workflow, the prefilled content of all fields but the owner should be preserved in a split ticket.  

### Actual behavior:

* When splitting a ticket with prefilled custom attributes, only input fields (type) are preserved.  

### Steps to reproduce the behavior:

* Create some custom ticket attributes of different types in the object manager that are hidden by default. 
* Create a Core Workflow that shows these ticket attributes under established conditions, e.g. if a specific group is set. 
* In a ticket -> Fill some values into all fields, update and split the ticket. 
* In the split ticket only input fields stay prefilled, all others need to be adjusted manually again. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
This got fixed as a side effect of https://github.com/zammad/zammad/issues/4763
