### ISSUE TITLE
API Paginaging is ignore on api/v1/ticket_articles/by_ticket/

### ISSUE THREAD

**Issue by CarliJoy** [zammad/zammad#4199]
### Infos:

* Used Zammad version: This is Zammad version 5.2.x 
* Installation method (source, package, ..): unknown
* Operating system: Alma 8
* Database + version: unknown
* Elasticsearch version: unknown
* Browser + version: all (curl tests)

### Expected behavior:

* Accessing `https://<my_zammad>/api/v1/ticket_articles/by_ticket/1148?page=1&per_page=20'` results in 20 results even so the API documentation says, endpoints have paginating by default.

### Actual behavior:

* No paginaging what so ever is done. Parameter is ignored and all articles are returned

### Steps to reproduce the behavior:

* Look for an ticket with a lot of articles
* Run `curl -vH "Authorization: Token token=$(cat secret/token.txt | tr -d '\n')" 'https://<zammd_url>/api/v1/ticket_articles/by_ticket/1148?page=1&per_page=20' | jq ' . | length'` and verify that the shown number is bigger as 20

Yes I'm sure this is a bug and no feature request or a general question.
It is either a bug in the documentation or in the api itself.

**Comment by MrGeneration** [comment]
The documentation does not exactly state that said endpoint supports padination or not. In fact it doesn't tell on any endpoints, pagination is only described within the API description.

In fact, if you compare both ticket article controller and ticket controller you'll see that the article controller doesn't have a pagination at all. (https://github.com/zammad/zammad/blob/218e854a4c199ab821c22aac17c8a7d55280336a/app/controllers/ticket_articles_controller.rb vs https://github.com/zammad/zammad/blob/218e854a4c199ab821c22aac17c8a7d55280336a/app/controllers/tickets_controller.rb).

This makes your issue an technical question - if you need further input on this topic please open a thread on the community board: https://community.zammad.org

However, I'm kind and am flagging this as working as designed.
