### ISSUE TITLE
No stop and start Command available

### ISSUE THREAD

**Issue by JeDuWei** [zammad/zammad#420]
System: Ubuntu 16.04.1 LTS
Zammad Version: 1.1.0-1479124849.8be9ce5.xenial
Installation via apt

According to the documentation, I can start Zammad with systemctl, stop and restart.
But these commands do not exist.

`systemctl zammad stop
Unknown operation zammad.`

**Comment by monotek** [comment]
its "systemctl start zammad"

**Comment by monotek** [comment]
Fixed in: https://github.com/zammad/zammad-documentation/commit/2722eff90408d9c7816a3c360a70bb0c7f77a5e6

**Comment by JeDuWei** [comment]
ty for the fast response and fix!
