### ISSUE TITLE
Open ticket by ticket number instead of id

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4208]
### Infos:

* Used Zammad version: 5.2
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* Currently it is only possible to open the ticket via id not number.

### Actual behavior:

* It should be possible to open the ticket via ticket number.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
https://github.com/zammad/zammad/pull/4191

**Comment by dominikklein** [comment]
@rolfschmidt Is this a duplicate https://github.com/zammad/zammad/issues/849?

**Comment by MrGeneration** [comment]
Indeed is.
