### ISSUE TITLE
Convert Chat into Ticket

### ISSUE THREAD

**Issue by dYn36** [zammad/zammad#422]
If a problem can not be solved by chat, it would be nice to convert the whole chat into a ticket.

**Comment by monotek** [comment]
Imho all chats should be converted to tickets.

**Comment by Braintelligence** [comment]
After a chat I can't find a ticket about it anywhere. Can you give an example how to find it?

**Comment by monotek** [comment]
Currently there is now way to find chats in the system, because they are not saved.
Thats the reason for this ticket.

**Comment by Braintelligence** [comment]
This is especially true, because chats are numbered and thus imply some form of saving, even though there isn't.

**Comment by csMobility** [comment]
Any way of converting a chat to a ticket in the zammad backend chat?

Use case: an agent decides whether a chat needs to be archived (as the customer need can not be satisifed directly) or not (by turning it into a ticket).

**Comment by Braintelligence** [comment]
@csMobility As you can see turning a chat into a ticket still isn't available and doesn't even have a milestone. It looks like this has no priority for the developers, at all.

**Comment by kstan79** [comment]
is there an work arround? Like any data will push into database in chat? Creating an stored trigger in database maybe is good hack?

**Comment by martini** [comment]
Update: It's available in upcoming Zammad 2.3.

**Comment by pgassmann** [comment]
@martini Is there an option to automatically document every chat as a ticket?

Many customers expect to get a transcript of their support chat. It would also be useful for the support to have the history documented.
https://github.com/zammad/zammad/issues/422#issuecomment-271580378
https://github.com/zammad/zammad/issues/585#issuecomment-271891727

**Comment by MrGeneration** [comment]
Please don't hijack closed issues (and issues in general) for technical questions and feature requests.
Please use the community for those kind of things: https://community.zammad.org
