### ISSUE TITLE
Alphabetical order of text modules

### ISSUE THREAD

**Issue by Stubenhocker1399** [zammad/zammad#4221]
### Infos:

* Used Zammad version: 5.2.x
* Installation method (source, package, ..): package
* Operating system: Linux
* Database + version: irrelevant
* Elasticsearch version: irrelevant
* Browser + version: Chrome 104 and Firefox 102+

### Expected behavior:

* Text modules popup sorted in some alphabetical order

### Actual behavior:

* Text modules popup is sorted by last update.

### Steps to reproduce the behavior:

* Enter :: in Article field

[See this community post for more info](https://community.zammad.org/t/alphabetical-order-of-text-modules/9648)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
might be simple fix with a default_scope for the model.

**Comment by rolfschmidt** [comment]
https://github.com/zammad/zammad/pull/4222
