### ISSUE TITLE
Zammad integration 3rd party C++ Application

### ISSUE THREAD

**Issue by JeDuWei** [zammad/zammad#423]
I could use a hint. We would like to integrate zammad into our C++ Qt application. No user can be created for the tickets (no email and password), but a username can be transferred. Does this work through the rest interface, or should we directly access the database and possibly write a connector?

**Comment by martini** [comment]
I would use the Zammad REST API https://docs.zammad.org/en/latest/api-intro.html for any action/changes in Zammad.

>  No user can be created for the tickets (no email and password), but a username can be transferred. Does this work through the rest interface, or should we directly access the database and possibly write a connector?

Sorry, I can't follow what your use case is.

**Comment by JeDuWei** [comment]
The user authenticates in our application, but there is no email or communication via email. Within our application the user can open a ticket and we would like to be able to respond from the ticket system. We would like to use the reference in our application to assign the ticket to the user. The user should not leave our application and must have no effort when creating the ticket.

**Comment by monotek** [comment]
That fits perfect for the API.
Create an API User for Zammad.
Use libcurl from your C++ app to talk to Zammad.
