### ISSUE TITLE
Integration with YouTrack

### ISSUE THREAD

**Issue by krestyanikov** [zammad/zammad#4238]
### Infos:

* Used Zammad version: 5.2 / develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* I would like to be able to link my Zammad tickets to my YouTrack issues

### Actual behavior:

* No integration with YouTrack

Zammad tickets currently integrate with GitHub and GitLab. We've been using GitLab to manage problems for a long time, but now have to move to YouTrack. The feature of linking GitLab issues to Zammad tickets is very handy and we would like to have this for YouTrack as well. Is it possible to add integration with YouTrack?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
