### ISSUE TITLE
Problem with Exchange IMAP connecting to plain (non ssl) IMAP server

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#424]
Hello there,

i have Problems with fetching mails via IMAP from our Exchange Server. In OTRS i use IMAPS in Postmaster Settings. I use the same Account with the same Server.

If i use Port 143 i get this error: 
`SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
`
Port 993 gives me 
`Connection refused
`
Any Ideas?

**Comment by rkaldung** [comment]
Port 143 uses regular IMAP, sometimes IMAPTLS. 993 is the port for IMAPS, connection refused looks like that this is not configured. Did your tried IMAP?

**Comment by Julian0o** [comment]
Zammad only offers POP3 and IMAP. No choice of IMAP**S**

**Comment by rkaldung** [comment]
Sorry, got it. Any hint's in the Exchange log regarding the connector?

**Comment by martini** [comment]
Any news here? @Julian0o Zammad is using IMAP if you use port 143 and IMAPS if you use 993 (in Zammad 1.1 you can define the imap port via ui).

Is it working for you with setting the port?

**Comment by martini** [comment]
The current options as screenshot. If any issue, pls reopen.

<img width="502" alt="screen shot 2016-12-12 at 13 48 56" src="https://cloud.githubusercontent.com/assets/110226/21100008/d2d16aae-c071-11e6-8ebd-c23e283df6af.png">

**Comment by Julian0o** [comment]
@martini i havent tested it yet. but i will try in the next days.

**Comment by martini** [comment]
@Julian0o sorry, this enhancement is only available in develop (will be release as stable on 2017-01-12)

**Comment by ponchofiesta** [comment]
We have 2017-02-14 and v1.2 is the latest version which doesn't offer the SSL and port option for me.
