### ISSUE TITLE
Prevent bulk actions from terminating when a mandatory field of a ticket is empty

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4241]
### Infos:

Used Zammad version: 5.2.x
Installation method (source, package, ..): any
Operating system: any
Database + version: any
Elasticsearch version: any
Browser + version: Microsoft Edge, Version 105.0.1343.33 (Official Build) (64-Bit)
Ticket: #10114639, #10114935, #10123283

### Expected behavior:

*When performing bulk actions, the tickets where the mandatory field is pre-filled will be executed, while the tickets where the field is empty will be blocked. 

### Actual behavior:

* The entire ticket action is stopped, all because of one ticket, because that ticket had no data in the mandatory field. 

### Steps to reproduce the behavior:

* Create a mandatory field and leave it blank in one ticket.
* In the overviews, try to select multiple tickets (including the beforementioned ticket above) and perform an action (status change, owner, just about anything).
* The entire action is stopped due to the one ticket where the mandatory field has no data.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by YetAnotherGerrit** [comment]
This was discussed to be solved in the new tech stack. Not planned in the old tech stack.
