### ISSUE TITLE
Move and/or Delete Comment from Ticket

### ISSUE THREAD

**Issue by projektug24** [zammad/zammad#4242]
Used Zammad version: 5.2.x (Newest)
Used Zammad installation type: (source, package, docker-compose, …) source
Operating system: Debian 11
Hello,

I mistyped a ticket number and merged a ticket with a wrong ticket.
I have split it off and transferred it to the correct ticket, I would like to delete the wrong “comment”.

Currently, unfortunately, this does not delete itself after the split.
An alternative would be if it were possible to move entries to another ticket.
Often a customer writes a message here on a wrong ticket.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
