### ISSUE TITLE
Restrict knowledge base rights (Option to hide the other ??example commands)

### ISSUE THREAD

**Issue by tthomasb** [zammad/zammad#4247]
Hello,

In our company, we use Zammad for several departments (all in one organization), which each have their own KB and can customize it for themselves. Is there a possibility in Zammad to restrict the rights of the knowledge base so that with the call ??example only the suggestions are displayed which are assigned for the respective groups/roles?

Through the right's distribution in the KB, we can only restrict the visibility in the KB, as well as the use of the restricted call of ??example, but they will still be displayed as suggestions. 

Thanks in advance and best regards

Thomas

**Comment by MrGeneration** [comment]
Please update your article to contain the issue template and actually fill it out.
It's there for good reasons, other wise we'll have to close this issue as question.

Also don't use questions in your issue as they're not being answered here.
If you have questions and you're not a hosted customer or don't want to pay for support, please consult our community: https://community.zammad.org
