### ISSUE TITLE
Tree select and multi tree select fields are not set to read-only mode

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4255]
### Infos:

* Used Zammad version: stable / develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Fields are set to read-only and are not usable.

### Actual behavior:

* Fields are not set to read-only and are usable.

### Steps to reproduce the behavior:

* Create a tree select and multi tree select field for tickets, add them to the ticket side bar.
* Add a new role "Agent Lite" with only read permission to all groups.
* Create a new ticket with a regular agent.
* Switch to an agent that is assigned to the "Agent Lite" role.
* Open the previously created ticket and check the side bar.
* Both tree select and multi tree select fields are not read-only and can be used (however, there is an error shown when trying to update the ticket).

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by raffaeler** [comment]
I still see this happening with a multi tree select field.
Was it fixed or what?
TIA

**Comment by fliebe92** [comment]
> I still see this happening with a multi tree select field. Was it fixed or what? TIA

Please create a new issue using our template and provide all information, thanks.
