### ISSUE TITLE
Dark/Light mode: Can't distinguish readonly fields anymore

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4256]
### Infos:

* Used Zammad version:
* Installation method (source, package, ..):
* Operating system:
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* It should be easier to distinguish readonly and normal fields

### Actual behavior:

* It is very hard to distinguish readonly and normal fields:

![image](https://user-images.githubusercontent.com/5445062/191002974-67939e7f-aa89-40c4-aff4-f3ac14a7b7ac.png)

In the example screenshot the group is readonly.

### Steps to reproduce the behavior:

* Add readonly core workflow
![image](https://user-images.githubusercontent.com/5445062/191003111-312eb624-ef09-4dd0-90bf-d9f4aa2577eb.png)

* Open ticket
* refresh

issue by @YetAnotherGerrit

**Comment by dominikklein** [comment]
@mrflix It seems to be that the Multi-Treeselect and Textarea fields are missing in the fix. Maybe you can also check the other fields.

![multitreeselect-readonly](https://user-images.githubusercontent.com/5445094/198005274-d924f572-14aa-440a-b22b-37ba01973700.png)
![textarea-readonly](https://user-images.githubusercontent.com/5445094/198005276-a058c6fc-24cb-4533-8a20-55eeee3abe13.png)

**Comment by mrflix** [comment]
@dominikklein I can't reproduce it. Here is a screenshot of a readonly multiselect and textarea between two non-readonly input fields with the current develop branch:

![Screenshot 2022-10-28 at 16 23 10](https://user-images.githubusercontent.com/60777/198643004-2f5190bc-f754-4938-a9ae-f814c1d9290d.png)

The 0.38 opacity is applied to inputs with the readonly attribute using the `form-control` class. Every input has this class, including the textarea field and the searchableSelect field (basis of the the Multi-Treeselect).

**Comment by dominikklein** [comment]
@mrflix I don't know from which screen you did the screenshot, but for me, the problem exists in the current development for "Multi Treeselect" and also "Textarea" in the ticket create screen and in the editing sidebar (I see also in the applied styles that the opacity is missing and checked it all browsers). But it happens also in the other screens, e.g. organization add/edit.

![Readonly-problem](https://user-images.githubusercontent.com/5445094/198693147-7fb9c3ce-3b9e-4100-83ee-945162f6f758.png)

![Readonly-organization](https://user-images.githubusercontent.com/5445094/198694063-f07909c9-7504-4dad-8548-5897badaf7a2.png)
