### ISSUE TITLE
While closing the ticket and discarding the changes, the automatic assignment still assigns the ticket to the user

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4258]
### Infos:

*Used Zammad version: 5.2.2.
*Installation method (source, package, ..): any
*Operating system: any
*Database + version: any
*Elasticsearch version: any
*Browser + version: Microsoft Edge, Version 105.0.1343.33 (Official Build) (64-Bit)
*Ticket: #10114638

### Expected behaviour:

* prerequisite: automatic assignment is enabled
* mandatory field in the ticket
* when I open an unassigned ticket for the first time and decide to close the tab, Zammad asks if I want to save the changes. I choose no and close the tab. When I return to the tab again, the ticket should be unassigned. 

### Actual behaviour:

* prerequisite: automatic assignment is enabled
* mandatory field in the ticket
* when I open an unassigned ticket for the first time and decide to close the tab, Zammad asks if I want to save the changes. I decide to decline and close the tab. When I return to the tab, I am assigned as the owner of the ticket. 

### Steps to reproduce the behaviour:

* enable automatic assignment
* mandatory field in the ticket
* open the ticket tab of an unassigned ticket and try to close the tab. While closing the tab, the system asks if you want to save the changes. Select No and close the ticket. Then go back to the same ticket and see yourself as the ticket owner.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Suhopoljac** [comment]
Bugfix in the latest pull, issue closed.

**Comment by Suhopoljac** [comment]
Fixed via commit 6b66f2881881129caa86579e1ebd078be51726a2 & 0b14a3e114fc91faccd4a22fa1e0ae18e3cfd846

**Comment by rolfschmidt** [comment]
relates: https://github.com/zammad/zammad/issues/4245

**Comment by rolfschmidt** [comment]
This bug report is invalid because it was only possible to pre assign owners because of the bug that the auto assign did not work properly if you are using it with mandatory fields (see fix #4245). The auto assign is auto saved on show and not a pre assignment which is changeable. It does not give you the choice of discarding assignments before saving.
