### ISSUE TITLE
Why do I need IMAP?

### ISSUE THREAD

**Issue by symptog** [zammad/zammad#426]
Is there a option/way to get zammad working with email tickets without IMAP?

zammad is able to receive mails via fetchmail/procmail etc.
How can I answer Tickets without an IMAP Account? It could store the email locally and send it via sendmail for example.

Is this even possible? At least this is not configurable.

**Comment by monotek** [comment]
Sending everything via sendmail is on my wishlist to: https://github.com/zammad/zammad/issues/224

**Comment by symptog** [comment]
ok duplicate, I'm sorry

**Comment by monotek** [comment]
No problem. 
Good i'm not the only one looking for this :-)
