### ISSUE TITLE
Zammad problem with image

### ISSUE THREAD

**Issue by PFialkowskiAGH** [zammad/zammad#4261]
Used Zammad version: 5.1.x
Used Zammad installation type: docker-compose
Operating system: alpine
 Browser + version: any browser

Users send their response by mail with image, but when images are not local and saved zammad doesn’t see them, so we don’t get all of image from users.
We didn’t change anything in our configuration.

What could be the problem? How to fix this?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request and technical question.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
