### ISSUE TITLE
Customer can't select group in ticket creation when "-" is configured in the Web channel

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4266]
### Infos:

* Used Zammad version: 5.2.x
* Installation method (source, package, ..): Hosted
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Firefox

### Expected behavior:

* When selecting "-" as groups in the Web channel configuration, customers should be able to create tickets in all groups. As per description beside the selector.

### Actual behavior:

* When selecting "-" as groups in the Web channel configuration, customers can only select "-" when creating tickets.

### Steps to reproduce the behavior:

* As admin select "-" on the following configuration screen /#channels/web select, and try to create tickets with a customer account.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by KamilTancula** [comment]
I have the same problem . 
In addition, I have the group selection field as mandatory by which it is impossible to set up a request. 
So rally I now have a grounded system to ro

**Comment by rolfschmidt** [comment]
### Workaround

```
zammad run rails r "Setting.set('customer_ticket_create_group_ids', [])"
```

### Bug

The dropdown in the admin interface has a bug and saves an array with an empty string `[""]`.
