### ISSUE TITLE
Missing scrollbar in textmodule list on specific screen settings

### ISSUE THREAD

**Issue by kgoldinger** [zammad/zammad#4269]
### Infos:

* Used Zammad version: 5.2.2
* Installation method (source, package, ..): Package
* Operating system: Rocky Linux 8.6
* Database + version: 10.21
* Elasticsearch version: 7.17.6
* Browser + version: Chrome (105.0.5195.127), Edge ( 105.0.1343.50) , Firefox (105.0.1)

### Expected behavior:

* If there are more than 10 textmodules in the the list to select from (::  )  there should be a scollbar to select the ones above pos 10.
![image](https://user-images.githubusercontent.com/43206134/192230539-c88ce9a2-c7f8-4b13-bb8b-518171d95dce.png)

### Actual behavior:

* on several screen resolution/ scaling settings (e.g. 2560x1440@100%) the scrollbar is omitted
![image](https://user-images.githubusercontent.com/43206134/192230683-5cf1347c-a810-43b6-b460-6feafe00a63b.png)

### Steps to reproduce the behavior:

* Open zammad on a screen @ 2560x1440/ 100% (or use Browser dev tools to set the resolution)
* Open a new Ticket
*  Try to insert a textmodule (there have to be more than 10 modules in the list) and to select the topmost.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Doesn't seem to be Zammad related - I can't reproduce it. Latest possible Zammad version.
![image](https://user-images.githubusercontent.com/6549061/192235284-c7a29aee-ce4d-41c2-88f5-bc86a5f06e70.png)
