### ISSUE TITLE
KB category appears even category permissions are set to none and answers visibility is set to internal

### ISSUE THREAD

**Issue by voohoo2000** [zammad/zammad#4274]
**Infos:**
Used Zammad version: 5.2.1 or 5.2.2
Installation method (source, package, ..): docker compose
Operating system: Ubuntu 22.04

**Presettings:**
1. Create two groups: project_a, project_b
2. Create two roles: customer_role_a, customer_role_b
    both assigned as "Knowledge_Base: Reader" and "Ticket: Customer"
3. Create two users: customer_a, customer_b
    assign role customer_role_a to customer_a
    assign role customer_role_b to customer_b
5. Create two Categories for KnowledgeBase: Project_A, Project_B
    set Project_A Category's Permission :  customer_a as reader, customer_b as none
    set Project_B Category's Permission :  customer_b as reader, customer_a as none
6. Create several categories and articles under Project_A, Project_B
    set all answers' permission to [internal]

**Expected behavior:**
   customer_a can only see category and answers of Project_A
   customer_b can only see category and answers of Project_B

**Actual behavior 1:**
Take customer_a as the sample,
1. Login as customer_a, default view of KB is as expected, only Project_A is shown
2. Click category Project_A, go to the sub folder
3. Use left top global search function, search and nothing found
4. Use KB search function, search and enter one
5. Goto the root of KB
6. Both Project_A and Project_B categories shows, of course you will get "The page was not found" if you read answer from Project_B

**Actual behavior 2:**
Take customer_a as the sample,
1. Login as customer_a, default view of KB is as expected, only Project_A is shown
2. Click category Project_A and some random operations
3. Use left top global and KB search function, search something
4. Sometimes (internal) answers of Project_B will be searched out, and get "The page was not found" if you try to read it.

Similar issue #4069

**Comment by voohoo2000** [comment]
**Snapshot for reference**
![2022-10-11](https://user-images.githubusercontent.com/11582675/195043482-4d0ee7a8-47f0-47a7-8e40-c7e55eb83038.gif)

**Comment by Bozo0511** [comment]
Hi,

I was not able to reproduce the issue.

I crated 2 groups:
Group_A 
Group_B

I created 2 roles:
Customer_A 
Customer_B

I created 2 Knowledge base directories with 1 article in each directory.
Support
-Test 1
Sales
-Sales for a dollar

visibility from the perspective of Customer_A
![2024-03-01 15_21_43-Window](https://github.com/zammad/zammad/assets/94919964/171ea51c-032c-4af2-8e2b-9714235e232f)

![2024-03-01 15_22_19-Window](https://github.com/zammad/zammad/assets/94919964/e71da7b9-6214-4c17-a405-afe076e0cca0)

Visibility from the Customer_B
![2024-03-01 15_24_07-Window](https://github.com/zammad/zammad/assets/94919964/a9e898c8-ab7e-4f09-aa0f-f1f2794b255f)

![2024-03-01 15_24_25-Window](https://github.com/zammad/zammad/assets/94919964/3187dd3d-1d77-4239-b321-85ab536b8d85)

Conclusion:
It looks like there is an issue with the configuration off the role's permission, the user roles, Or the knowledge base permissions.
