### ISSUE TITLE
Cancel & Go Back in ticket create screen at the wrong position

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4279]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

![image](https://user-images.githubusercontent.com/5445062/193036174-26f6f440-257a-49e8-bc1c-377ee289e2cd.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/5445062/193035711-12ddbbd9-78d2-4b5b-82c8-0520894d5152.png)

### Steps to reproduce the behavior:

* Open ticket create screen

Yes I'm sure this is a bug and no feature request or a general question.

regression of https://github.com/zammad/zammad/commit/c0546af0e6265b583292f88c9630182a3269932c

**Comment by dvuckovic** [comment]
Regression from https://github.com/zammad/zammad/issues/4263
