### ISSUE TITLE
Switching storage provider for attachments in UI has no effect

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#428]
Switching the storage provider for attachments in the settings from Database to Filesystem has no effect. 

I had to change the setting name from "storage" to "storage_provider" in DB, and the possible value from "FS: Filesystem" to "File: Filesystem" in the option field. 

Also, the description "You can switch between the modules even on a system that is already in production without any loss of data." made me assume all files would be copied from the DB to the file system when switching the setting, and vice versa. That doesn't seem to be the case, although there is "Store::File.move('File', 'DB')" ready for that task. 

HTH. Great project, hopefully will be able to use it in production & contribute more soon! :-)

**Comment by martini** [comment]
> Also, the description "You can switch between the modules even on a system that is already in production without any loss of data." made me assume all files would be copied from the DB to the file system when switching the setting, and vice versa. That doesn't seem to be the case, although there is "Store::File.move('File', 'DB')" ready for that task.

-> That's right. You can switch on the fly, but the files will keep in fs/db backend until you move it with e. g. "Store::File.move('File', 'DB')".

We will improve the text too!

**Comment by olivergrahl** [comment]
Got it. Moved all files from DB to File from the command line. Worked perfectly. :-)
```
> zammad run rails c
> Store::File.move('DB', 'File')
```

**Comment by martini** [comment]
Just a "feature" note. Zammad is saving same attachment only once (is working with references). Saves a lot of space. 🤓

**Comment by martini** [comment]
Better?

<img width="828" alt="screen shot 2016-11-17 at 14 28 05" src="https://cloud.githubusercontent.com/assets/110226/20391087/1c580128-acd2-11e6-932c-1bde7281c992.png">

**Comment by olivergrahl** [comment]
Prima :-) - Vorschlag: 
- "Mechanismus für Speicherung" -> "Speicherort für Dateianhänge"
- Wegfall der beiden Listenpunkte, da ohne Aussage
- "müssen **Sie** über die Console **eines** der folgenden **K**ommandos"

**Comment by martini** [comment]
Nice! Done. It's in develop and 1.1 (https://github.com/zammad/zammad/commit/15975eaaf739804bb458911c5bd7ab1fc6f0fc22).

By the way, Zammad as a nice translation feature. Just login as admin and press "ctrl+alt+t", update your translations, after finishing got to admin and push your changes to us. We will review and take over them.
