### ISSUE TITLE
Status pending close with relative "wait until" get set to current time.

### ISSUE THREAD

**Issue by Lapotor** [zammad/zammad#4282]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): package
* Operating system: Debain 11
* Database + version: Postgres 13
* Elasticsearch version: 7.17.6
* Browser + version: Firefox 106.0b6 (64-bit)

### Expected behavior:

* On a macro when I set the status to `pending closure` and the `wait until` time to `relative` `2 weeks` the ticket should get a closing time in two weeks of by now.
![grafik](https://user-images.githubusercontent.com/17144397/193481462-d3ec890d-e153-4a2b-903e-182d152eef01.png)

### Actual behavior:

* The macro described in "Expected behavior" set the `wait until` the same as now.
![grafik](https://user-images.githubusercontent.com/17144397/193481577-334539e2-e245-4bc4-9fd2-a5c693a55f7d.png)
![grafik](https://user-images.githubusercontent.com/17144397/193481692-695af088-f2b8-44e3-9e54-24703d0961f7.png)

### Steps to reproduce the behavior:

* Create a macro as seen in the image of `Expected behavior`
* Open ticket and update it with the macro

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Lapotor** [comment]
FYI: When I add the `pending closure` time manually. It's working for me.
![grafik](https://user-images.githubusercontent.com/17144397/193481840-7cbf2e1d-0e0f-45d3-bcc4-1bc5ab7bb68c.png)

**Comment by dominikklein** [comment]
Looks like it was already fixed together with the following issue: https://github.com/zammad/zammad/issues/4302
