### ISSUE TITLE
Tabbing through dropdowns will change the dark mode

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4283]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* If you tab thorugh dropdowns and want to select an option starting with "d" by pressing "d" it will change the dark mode state instead of selecting the option.

### Actual behavior:

* It should select the option when pressing "d".

### Steps to reproduce the behavior:

* Select the group dropdown
* Press tab
* Try to select an option by pressing "d"
* It will change the dark mode.

![image](https://user-images.githubusercontent.com/5445062/193757876-202d16b1-5a46-4d7e-8bb4-76ada90a1542.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mrflix** [comment]
Oh that's a good find. I introduced this new possibility to add modifier-free hotkeys. They are disabled while you type in an input or richttext field and they have to be disabled too, while you type in a dropdown.

**Comment by rolfschmidt** [comment]
JFYI @mg found this while using the time tracking addon. I tried to translate it so it applies to the zammad core.

**Comment by dominikklein** [comment]
@rolfschmidt is it not a duplicate from https://github.com/zammad/zammad/issues/4276?

**Comment by rolfschmidt** [comment]
oh shit yes! I'm sorry!
