### ISSUE TITLE
user.preferences['locale'] not initialized at user creation

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#429]
Resulting from #401 

The user.preferences['locale'] is "nil" by default, although the properties in the users profile is set to the right language (German in my case).

This results in all email notifications being in the default language (english).

The user.preferences['locale'] should be initialized correctly by the helpdesk's default language at any user creation. It can be updated by the user when he changes his main language in the profile.

We can't use the user's browser language at this point, as the user must not be connected by Zammad before the user is created. So there should be a setting "Default language for new users" in the Zammad config.

**Comment by jepf** [comment]
Newly created users now will be assigned the locale of the creating user/admin now.

**Comment by simonkurka** [comment]
This is actually not enough. As @jacotec suggested there should be a default language for new users.
New users created on email-in receive english notifications, although german should be default in my case.

**Comment by Braintelligence** [comment]
@simonkurka Did you find a solution to this yet? Customers who send a mail and thus are known to the system can't create new accounts. If they try to retrieve their password, though, they receive an English mail. This is rather weird.

**Comment by simonkurka** [comment]
@Braintelligence Actually not. I normally don't send automated mails to customers. Not a solution, though.

**Comment by Braintelligence** [comment]
@simonkurka How do you prevent your customers of resetting their password when the initial communication was per mail? If the first thing they do is write you a mail they can't create an account themselves because the mail is registered already.

**Comment by Flappes** [comment]
Still occurs on my latest version 1.5 for Debian. User locale is nil after creating. 
What's the status of this issue?
