### ISSUE TITLE
The status of the ticket does not change if it receives a reply while observed in the overviews

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4296]
**Infos:**
Used Zammad version: 5.3.x
Installation method (source, package, ..): any
Operating system: any
Database + version: any
Elasticsearch version: any
Browser + version: Microsoft Edge, Version 105.0.1343.33 (Official Build) (64-Bit)
Ticket: #10116352

**Expected behavior:**
*When updates (new mails) to the ticket are received, the ticket status and the symbol colour in the overviews
 should change, regardless of whether the ticket is currently being processed or not

**Actual behavior:**
*When updates (new mails) are received for the ticket, the ticket status in the overviews does not change, (although the symbol changes the colour from pending to open), not even after opening the ticket via the notification or in the sidebar, only after reloading the page does the status in the overviews change

**Steps to reproduce the behavior:**
* Open 2 sessions with Agent and Customer
* Agent opens Ticket and sets to `pending reminder`
* Agent closes Ticket's taskbar and switches to overview with the Ticket. No browser reloading
* Customer puts in a reply (not just state change via taskbar)
* For Agent, state circle is updated, but state name is stuck at `pending reminder`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Suhopoljac** [comment]
The reported behavior can no longer be reproduced, labels have been removed.

**Comment by MrGeneration** [comment]
Mantas could not reproduce this.
Please update the description on how to reproduce this issue so that Mantas has a choice.
Also tags "can't reproduce" should be removed if you can reproduce it.

**Comment by mantas** [comment]
I was able to reproduce this bug in both `develop` and `stable`. Detailed steps added.

**Comment by rolfschmidt** [comment]
I can't reproduce it. Looks fine for me.

[screen-recorder-fri-nov-24-2023-11-43-05.zip](https://github.com/zammad/zammad/files/13458180/screen-recorder-fri-nov-24-2023-11-43-05.zip)

**Comment by rolfschmidt** [comment]
I did the same and also added the step to close the taskbar after setting the ticket to pending reminder:


https://github.com/zammad/zammad/assets/5445062/de59c1bd-8c4c-44da-886e-ca53f4368fb2

still works

**Comment by rolfschmidt** [comment]
I talked to @mantas, and we were able to reproduce it:

- You have to reply via UI as a customer
- The state column has to be visible in the overview of the agent

BUG: The state name in the overview will not update.
