### ISSUE TITLE
Show RSS feeds in knowledge base

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4298]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all
* Ticket#10114789

### Expected behavior:

2.1.1 As Admin...

- I have no requirement.

2.1.2 As an agent...

- I can subscribe to the entire KB (all eligible articles) as an RSS feed.
- Can I subscribe to all eligible articles in a category as an RSS feed.

2.1.3 As a customer...

- I can subscribe to the whole KB (all eligible articles) as RSS feed.
- I can subscribe to all authorized articles of a category as RSS feed.

2.1.4 As a Public User...

- I can subscribe to the whole public KB as RSS feed.
- I can subscribe to all public articles of each category as RSS feed.

![image](https://user-images.githubusercontent.com/5445062/195779116-6f6c45f2-0b9b-4d61-8368-2460b1236438.png)

![image](https://user-images.githubusercontent.com/5445062/195779156-f4c840d5-6edb-4f68-b3b2-31614abb311e.png)

![image](https://user-images.githubusercontent.com/5445062/195779205-4cc06899-ad99-4824-8f4e-d281ac6f2708.png)

The articles in the RSS feed should get ordered by updated_at.

**Comment by dominikklein** [comment]
For the UI we should check which is the best position for the new icon. And the question is also if we want to use the icon with the "orange" or a more reserved version.
