### ISSUE TITLE
"Tag" missing as criteria in Trigger and SLA filters

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#430]
I have triggers defined which notifies the customer about assignment- and status changes.

Of course I want avoid to send these notifications to a spam sender. So I want to add a filter criteria "if tag is not "spam" ... but the "tag" is missing as filter criteria.

**Comment by Julian0o** [comment]
Related to https://github.com/zammad/zammad/issues/245 and https://github.com/zammad/zammad/issues/436

**Comment by rolfschmidt** [comment]
HI @jacotec, please have a look at issue #245. The condition should be possible with the next stable release. Have fun!
