### ISSUE TITLE
Replacement overviews incorrectly visible when agent role has additional ticket.customer permission 

### ISSUE THREAD

**Issue by Stubenhocker1399** [zammad/zammad#4301]
### Infos:

* Used Zammad version: 5.2.3 and current develop branch 7314e53e48ae4a7345c14b000f448bd34f2f59ed
* Installation method (source, package, ..): ubuntu package and source build
* Operating system: Arch Linux
* Database + version: postgresql 14.5
* Elasticsearch version: 7.17.6
* Browser + version: Google Chrome Version 106.0.5249.119 (Official Build) (64-bit)

### Expected behavior:

![image](https://user-images.githubusercontent.com/6693160/195812532-ba6b135f-f1c8-45d6-a1f9-815c58259bea.png)

![image](https://user-images.githubusercontent.com/6693160/195812675-d3cffe92-441e-4adc-ad50-93abd7db65d8.png)

* Replacement overviews should only be visible to agents that are replacement for other agents despite having customer ticket permission

### Actual behavior:

* As soon as agent role receives customer ticket permission and reloading the page all replacement overviews become visible. 

### Steps to reproduce the behavior:

* Make sure agent is currently not a replacement user
* Make sure replacement overview exists
* Add customer permission checkbox to agent role
* Refresh the page
* Check for now incorrectly visible replacement overview 

Bug seems to be related to this check through which the agents out of office filter does not get applied:
https://github.com/zammad/zammad/blob/a20264d781b4526c78c388b11cf76a3b37a1fe1b/app/policies/ticket/overviews_policy/scope.rb#L6-L9

Any additional info in these [community posts](https://community.zammad.org/t/out-of-office-replacement-overview-shown-even-if-not-a-replacement-solved/10177).

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
When I see it correctly it's a duplicate from #4248.
