### ISSUE TITLE
Mails cannot be processed if the special character "+" appears at the beginning of the sender address

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad#4304]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): package
* Operating system: Ubuntu
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:
Our Fax-Server sends message which were adressed to unknown destinations to our Ticket-System.
This Mail should be parsed correctly.

### Actual behavior:
Unprocessable with error `Validation failed: Invalid email '+43512727180@fax.lokal'>`

### Steps to reproduce the behavior:
* Send a email with an address like +43xxx@fax.lokal

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
@mantas what does email RFC say to this? If above mail address is a legit one, add the bug tag please.
Technically you can also add priotized by payment then as it affects SaaS as well.

**Comment by mantas** [comment]
@MrGeneration looks like this is a bug in a library we use for emails validation.

I submitted a pull request for it. Hopefully it's maintainer applies the patch soon.

https://github.com/afair/email_address/pull/93

**Comment by dominikklein** [comment]
@mantas after a very long time without feedback inside the created PR in the email validation library, we should maybe clarify some possible solutions. Maybe we need to fork the library and add our fix?

**Comment by fliebe92** [comment]
@mantas ping :)
