### ISSUE TITLE
Insertable knowledge base articles are displayed without titles in editor field

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4311]
### Infos:

* Used Zammad version: 5.3 / develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Output of insertable knowledge base articles should display the title + the category.

### Actual behavior:

* Output of insertable knowledge base articles is displaying only categories.

![image](https://user-images.githubusercontent.com/8327427/197172921-d93618b0-d59e-483c-814a-e678bdffb72b.png)

### Steps to reproduce the behavior:

* Create an agent that has access to the knowledge base.
* Create two knowledge base categories.
* Create two knowledge base articles with the same title but in different categories.
* Create a new ticket, focus the body field, and type `??` with the title of the knowledge base articles.
* See that suggested knowledge base articles that can be inserted are only displaying the categories, no titles.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by fliebe92** [comment]
Regression of https://github.com/zammad/zammad/commit/0d7e9ebd2b242da5df69449c99ab70436662b1e7

**Comment by mrflix** [comment]
I'd say this issue better fits into @mantas's field. Let me know if I'm wrong.

**Comment by dominikklein** [comment]
It was introduced with one commit (mention above) for the dark mode, so I think you should take a look.

**Comment by mrflix** [comment]
Sorry, overlooked the regression part.
