### ISSUE TITLE
Ticket Auto-Assignment not working as expected

### ISSUE THREAD

**Issue by mat-ti** [zammad/zammad#4317]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): [Package Version](https://docs.zammad.org/en/latest/install/package.html)
* Operating system: Ubuntu 20.04.5 LTS
* Database + version: postgresql-12
* Elasticsearch version: 7.17.6
* Browser + version: Firefox 102.4.0esr, Edge 106.0.1370.47

### Expected behavior:

* Ticket Auto-Assignment should respect my settings ![grafik](https://user-images.githubusercontent.com/75842166/197801880-d10cd7e0-817c-4449-a67e-ec5333434d44.png)
* when an agent opens a Ticket which has another State than new, this ticket should not be touched

### Actual behavior:

* the agents are automatically assigned, when they open a ticket. The actual state doesn't matter: Closed, open, new, pending reminder. It happens everytime

### Steps to reproduce the behavior:

* I tried to reduce the assignment on a specific group, but this is also ignored. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sounds like a duplicate of #4308 
Please wait for the packager to build current packages and ensure your system is on latest patch level.

If it then still doesn't work, we'll continue from there. Built process may take 2 hours.

**Comment by mat-ti** [comment]
@MrGeneration thanks for the very fast feedback. I've installed zammad 5.2.3-1666696333.efc4e88e.focal right now and can confirm the issue https://github.com/zammad/zammad/issues/4308 ist fixed. But my one still exists, tickets with other state than new, gets also assigned to an agent.

**Comment by rolfschmidt** [comment]
> @MrGeneration thanks for the very fast feedback. I've installed zammad 5.2.3-1666696333.efc4e88e.focal right now and can confirm the issue #4308 ist fixed. But my one still exists, tickets with other state than new, gets also assigned to an agent.

Hi @nh-matti ,
the commit (for issue #4308) for the stable just got merged. It was still packaging. I think you aren't yet on the newest commit.

![image](https://user-images.githubusercontent.com/5445062/197819592-9077d5c7-ce81-4a93-9dce-4dfce6dbcb53.png)

Can you try again, maybe in a few hours or tomorrow?

https://packager.io/gh/zammad/zammad/refs/stable

**Comment by mat-ti** [comment]
@rolfschmidt you're right, I did an upgrade to zammad/unbekannt 5.2.3-1666860729.1f5facea.focal amd64 right now. 
I can confirm your commit  e44a883e7ed89df49c1387e5840df55e5514787a   also fixes my problem.
