### ISSUE TITLE
Zammad-scheduler constantly crashes if user have unknown timezone

### ISSUE THREAD

**Issue by v-starodubov** [zammad/zammad#4320]
### Infos:

* Used Zammad version: 5.2.3
* Installation method: docker-compose 
* Operating system:  Amazon Linux
* Database + version: MySQL 8.0.23 (Aurora MySQL 3.02.1)
* Elasticsearch version: 7.17.3
* Browser + version: Microsoft Edge 106.0.1370.52 (64-bit)

### Expected behavior:

* Zammad set user's timezone to default UTC +00:00 if something wrong.

### Actual behavior:

* Zammad-scheduler crashes if user's timezone equals `Etc/Unknown`

```
bundler: failed to load command: script/background-worker.rb (script/background-worker.rb)
/usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/core_ext/time/zones.rb:100:in `rescue in find_zone!': Invalid Timezone: Etc/Unknown (ArgumentError)
{...}
/usr/local/bundle/gems/tzinfo-2.0.5/lib/tzinfo/data_source.rb:321:in `validate_timezone_identifier': Invalid identifier: Etc/Unknown (TZInfo::InvalidTimezoneIdentifier)
```

### Steps to reproduce the behavior:

* You must set your browser timezone to `Etc/Unknown`
![image](https://user-images.githubusercontent.com/3694552/198023909-1b70de98-d9d8-4cea-b5e2-23181d5f70de.png)
* Login into Zammad app and wait some time before scheduler start some actions with your session.

To fix crashes you need to start session from another device on same account, where timezone is not broken.

**Comment by v-starodubov** [comment]
I have investigate more and i think the source of the problem is different. After i changed browser to Mozilla Firefox 106.0.1 (64-bit) the timezone fixed (`Europe/Kyiv`) i get the same blank field in Branding/Timezone.
![image](https://user-images.githubusercontent.com/3694552/198076154-f40c5746-13d1-46ac-9b2f-9b3c4f186af1.png)
And if i change something, zammad-scheduler crashes with error
```
/usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/core_ext/time/zones.rb:100:in `rescue in find_zone!': Invalid Timezone: Europe/Kyiv (ArgumentError)
```
And I found that the Branding/Timezone field not `Kyiv`, but `Kiev`.
![image](https://user-images.githubusercontent.com/3694552/198080035-90c26ef3-6843-4ddb-ba1c-b05bcdb44904.png)
![image](https://user-images.githubusercontent.com/3694552/198080061-097e2671-dbd9-4d0a-9a70-219d8a346472.png)

I changed my timezone with plugin to `Europe/Berlin`, entered zammad app, changed timezone and everything works good.

My operation system: Ubuntu 22.10.
I asked colleague with Windows 10 to check same page, he got filled timezone field with his current timezone.

**Comment by v-starodubov** [comment]
https://mm.icann.org/pipermail/tz-announce/2022-August/000071.html
![image](https://user-images.githubusercontent.com/3694552/198108026-1c2747a8-d5af-455f-9715-4bc5047b5402.png)

**Comment by mantas** [comment]
Looks like this is 2 separate issues. We ain't handling unknown timezones correctly. It should not crash in any case.

As for Kyiv/Kiev in the dropdown. Kiev/Kyiv in that dropdown relies on timezones data provided by your OS.

**Comment by tschaefer** [comment]
@mantas We should consider to use the gem [tzinfo-data](https://github.com/tzinfo/tzinfo-data) as tz database, at least that would mean we are OS independent.
