### ISSUE TITLE
rake --tasks is not returning rake zammad:package:* commands

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4321]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all

### Expected behavior:

* It should return also the `rake zammad:package:* tasks`

### Steps to reproduce the behavior:

* run `rake --tasks`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by tschaefer** [comment]
@rolfschmidt Technical this is not a bug. `rake --tasks` shows tasks with description only. To see all tasks use `rake --tasks --all`.

**Comment by rolfschmidt** [comment]
ah ok thanks for the insights @tschaefer, then we should add some descriptions 👍
