### ISSUE TITLE
Wrong value in session timeout

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#4322]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): source
* Operating system: Ubuntu 20.04.5
* Database + version: latest
* Elasticsearch version: 7.17.7
* Browser + version: Microsoft Edge

### Expected behavior:
Same value as selected shown after saving

### Actual behavior:
If I set the value to e.g. 1 day and save it the value is after a resfresh set to seconds and not the human readable value.

### Steps to reproduce the behavior:
![Animation](https://user-images.githubusercontent.com/1473674/198119800-151fe750-6d6b-4fac-8268-85cec6b6a116.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This doesn't just affect Microsoft Edge but also Firefox and Opera on Windows. Possibly a general chromium based issue.
Note that this can also be seen if you change the browser after changing one of the values.
