### ISSUE TITLE
german translation of ticket actions missing

### ISSUE THREAD

**Issue by blackbasket** [zammad/zammad#4327]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): package
* Operating system: Debian 11
* Database + version: MariaDB 10.5.15
* Elasticsearch version: 7.17.6
* Browser + version: Edge 106

### Expected behavior:

all ticket actions should be translated

### Actual behavior:

only "reply" is translated, but "reply all" and "forward" are missing

### Steps to reproduce the behavior:

![Screenshot 2022-10-28 085614](https://user-images.githubusercontent.com/64146687/198523902-30ec93d5-26d0-4211-8e16-fddf547a8529.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I couldn't even find `reply all` on translations.zammad.org.
Possibly the whole string is missing.

Thanks for the heads up.
