### ISSUE TITLE
Display of date picker overlay is cut off

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4328]
### Infos:

* Used Zammad version: develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* The overlay for date pickers should look good and all information can be read without any issues.

### Actual behavior:

* The overlay for date pickers is cut off, therefore it's needed to scroll to see all information.

![image](https://user-images.githubusercontent.com/8327427/198529477-cf115bb2-b2c1-4f2b-aef6-a3662cab0717.png)

### Steps to reproduce the behavior:

* Turn on the setting `datepicker_show_calendar_weeks` (via `Rails r "Setting.set('datepicker_show_calendar_weeks', true)`".
* Open a ticket, select a pending state, and click on the reminder date field.
* See that the overlay is cut off and a scrollbar is visible.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by fliebe92** [comment]
Introduced with https://github.com/zammad/zammad/commit/62ed69487535a0197e505ea864af494982440f5b.

**Comment by mantas** [comment]
Maybe we could change weeknumber styling slightly while at it? Now it looks very confusing.

**Comment by fliebe92** [comment]
> Maybe we could change weeknumber styling slightly while at it? Now it looks very confusing.

We already talked to @mrflix and he will adjust it, maybe some different color will be used.
