### ISSUE TITLE
Object manager allows method names as attributes

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#433]
Currently the object manager allows to create attributes that are already taken by regular object methods like e.g. `.delete`. This should be prevented.

Maybe something like this could be used:
https://ruby-doc.org/core-2.3.0/Object.html#method-i-methods

//EDIT:
Or maybe:
http://ruby-doc.org/core-2.3.2/Object.html#method-i-respond_to-3F

**Comment by martini** [comment]
++

JFI: https://github.com/zammad/zammad/blob/develop/app/models/object_manager/attribute.rb#L654
