### ISSUE TITLE
Inserting any information causes new lines in front of pasted content

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4330]
### Infos:

* Used Zammad version: develop / 5.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on latest Firefox (win) - could not verify on Opera chromium based

### Expected behavior:

If you insert e.g. plain text without formatting, Zammad will allow you to paste the information at exact that position.

### Actual behavior:

Inserting non formatted text will enforce a new line before inserting the actual content you're pasting.
This forces you to permanently switch positions in your content and use your backspace a lot.

### Steps to reproduce the behavior:

* Open any ticket and answer on it
* insert a simple non formatted text. You can also take the URL from your address bar of the browser and simply paste it

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
@MrGeneration can you provide me a video about this? I tried to reproduce with firefox and latest stable and develop.

**Comment by MrGeneration** [comment]
Sure. Here you go.
![issue4330](https://user-images.githubusercontent.com/6549061/206728543-8c26a4e8-0aea-482b-a5d3-5860f269d822.gif)

**Comment by dominikklein** [comment]
Duplicate from #3716
