### ISSUE TITLE
Type in i-doit should be visible

### ISSUE THREAD

**Issue by cringeboy06** [zammad/zammad#4333]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): source
* Operating system: Ubuntu 20.04.5
* Database + version: Postgres latest
* Elasticsearch version: 7.17.
* Browser + version: Edge 107

### Expected behavior:
If I select an object from i-doit the **type** should be visible in the table if I dont select the type before _(e.g. Client, Printer, Display etc.)_

### Actual behavior:
If I type in the device name without select a type the entry can appears multipe times _(e.g. as monitor, Client, Printer etc.)_ and I cant know which one is the right

![grafik](https://user-images.githubusercontent.com/117109953/199073395-927342d5-f4ac-4901-83c9-b3323573a85e.png)

### Steps to reproduce the behavior:
Create a device with the same name in another category and try to select the right one.

The problem is: We create a Client with the name **Test-01**. For the Client we select a monitor. In i-doit the Monitor needs a name. We set the same name for the monitor how the client is named: **Test-01**. Now we cant see which device is the right one in Zammad. It would be useful to have a column more with type where is listet the right type of the device.

Example:
![grafik](https://user-images.githubusercontent.com/117109953/199073600-e2f34a92-8344-4805-9461-e2808a74c24d.png)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
