### ISSUE TITLE
Word wrap in Knowledge Base with tables from mobile view perspective

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#4334]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket(s): #10117435

### Expected behavior:

* When copying and pasting text from a table (e.g. LibreOffice, Word) to a knowledge base article, the text should always be wrapped in a grammatically correct way. 

### Actual behavior:

* When copying and pasting text from a table (e.g. LibreOffice, Word) to a knowledge base article, the text is not correctly wrapped. This happens with just one, or several columns. See the following screenshot: 

![image](https://user-images.githubusercontent.com/69846837/199500598-bf812110-6b7a-47b0-bcd5-caa684b8b109.png)

### Steps to reproduce the behavior:

* Copy and paste some text from a table (from Word, LibreOffice etc.) to a knowledge base article.  
* View the article. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
The issue should fixed equally to https://github.com/zammad/zammad/issues/3630
