### ISSUE TITLE
Feature Request: Process Management

### ISSUE THREAD

**Issue by WWoodpecker** [zammad/zammad#4335]
Hi,

I saw the issue 353 with process management, that would be the only thing we are still missing on Zammad, are there any plans or is a process management already on the RoadMap for Zammad?

We are currently deciding whether we want to use Znuny or Zammad, I like Zammad basically very well, visually and integration-technically it is top, only the missing process management is a thorn in our side. 

https://github.com/zammad/zammad/issues/353

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
