### ISSUE TITLE
"Time accounting selector" title used for multiple setting items

### ISSUE THREAD

**Issue by maxxer** [zammad/zammad#4336]
### Infos:

* Used Zammad version: 5.2.3-1666860729.1f5facea.focal
* Installation method (source, package, ..): packages
* Operating system: Ubuntu 20.04
* Database + version: Postgresql 14+232.pgdg20.04+1
* Elasticsearch version: elasticsearch-oss 7.10.2
* Browser + version: any

### Expected behavior:

* Every setting item having its own title

### Actual behavior:

* Some settings share the same title

### Steps to reproduce the behavior:

Yes I'm sure this is a bug and no feature request or a general question.

https://github.com/zammad/zammad/blob/0852cd6a5ed86a12015586fc38dd3838071adcbc/db/seeds/settings.rb#L2285-L2318

The appropriate setting for the item is at [line 3522](https://github.com/zammad/zammad/blob/0852cd6a5ed86a12015586fc38dd3838071adcbc/db/seeds/settings.rb#L3522)

`stable` is affected as well

**Comment by fliebe92** [comment]
Hello @maxxer and thanks for reporting this issue here.

Could you please use our template and adjust your report? It's easier for all of us if we have a consistent way of reporting issues in our repository.

Thank you for your contribution to Zammad!

Kind regards

**Comment by maxxer** [comment]
Seems weird since it's a source related issue and not linked to any of the requested items, but here you are

**Comment by mgruner** [comment]
This has been fixed in the meantime via 3d22e21af8e86fcd813d38d9c71f549f0ed68b67.
