### ISSUE TITLE
Remove spaces before ** in SLA description text

### ISSUE THREAD

**Issue by maxxer** [zammad/zammad#4337]
### Infos:

* Used Zammad version: 5.2.3-1666860729.1f5facea.focal
* Installation method (source, package, ..): packages
* Operating system: Ubuntu 20.04
* Database + version: Postgresql 14+232.pgdg20.04+1
* Elasticsearch version: elasticsearch-oss 7.10.2
* Browser + version: any

### Expected behavior:

* Every setting item having its own title

### Actual behavior:

* Some settings share the same title

### Steps to reproduce the behavior:

Yes I'm sure this is a bug and no feature request or a general question.

https://github.com/zammad/zammad/blob/63fecf55ca3b8291396699b3762c748cb969aabb/app/assets/javascripts/app/models/sla.coffee#L21-L25

Is it possible to remove spaces before and after the `**`s? As it's now, introduces spaces between words and punctuations. Other strings have asterisks attached, so it shouldn't be, but I don't know if the description is using a different rendering method...

![immagine](https://user-images.githubusercontent.com/240201/199924364-96dd438f-952b-4d99-a791-accbca80e588.png)

**Comment by fliebe92** [comment]
Hello @maxxer and thanks for reporting this issue here.

Could you please use our template and adjust your report? It's easier for all of us if we have a consistent way of reporting issues in our repository.

Thank you for your contribution to Zammad!

Kind regards

**Comment by mgruner** [comment]
This fix will not be included in Zammad 5.3 to avoid string changes at this point, but in the next version.
