### ISSUE TITLE
Nginx default page after install

### ISSUE THREAD

**Issue by randohinn** [zammad/zammad#434]
After installing zammad, all I see on the ip of my machine, is the nginx default page. Any ideas, why that may be? Followed https://zammad.org/documentation/install/install-deb

**Comment by monotek** [comment]
Use localhost as url or Set servername in nginx.conf

**Comment by randohinn** [comment]
@monotek That results in a 502 Bad Gateway

**Comment by monotek** [comment]
Please follow the new documentation: https://docs.zammad.org/en/latest/install-debian.html

**Comment by martini** [comment]
@randohinn Any feedback here?

**Comment by randohinn** [comment]
@martini Wiped out sick. Will try once healed.

**Comment by martini** [comment]
@randohinn thanks for feedback, in the meantime I'll close this issue. Feel free to reopen it on followup!

Thanks for your support!

**Comment by LoganRocks** [comment]
im getting the same issue. its showing the nginx default page and i edited the config from localhost to my server fqdn

**Comment by thorsteneckel** [comment]
Hi @lferezy4 - this issue was closed nearly 2 years ago and we never heard of something similar. So this is more a technical question for an issue in you local setup rather than an issue in Zammad. Pleas refer to the [community board](http://community.zammad.org/) for technical questions.

**Comment by Hugo070707** [comment]
Hello, I have the same Problem, any ideas ? :(

**Comment by MrGeneration** [comment]
@Hugo070707 Please do not hijack old and closed issues.
As you're having a technical question, please refer to the Community which is the better place for those kind of requests: https://community.zammad.org

However, our documentation should help you as well:
https://docs.zammad.org/en/latest/install-centos.html#nginx

Locking conversation to keep the noise of this tracker as low as possible.
