### ISSUE TITLE
Freshdesk custom field types which can not be mapped will abort the complete import

### ISSUE THREAD

**Issue by itsupply25** [zammad/zammad#4342]
### Infos:

* Used Zammad version: Newest
* Installation method (source, package, ..): Docker and Package
* Operating system: Debian
* Database + version: 
* Elasticsearch version: 
* Browser + version: Google Chrome newest

### Expected behavior:

I tried to import Freshdesk instance. All tickets should be imported without any error and including all custom fields.

### Actual behavior:

On step "Ticket Import" the following error occured: "The custom field type 'customdatetime' cannot be mapped to an internal field, aborting."

### Steps to reproduce the behavior:

Start Freshdesk Migration

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
Hi @itsupply25 

thanks for your message. I checked the documentation (https://support.freshdesk.com/en/support/solutions/articles/37596-creating-custom-fields-in-your-ticket-form) on the Freshdesk side (and also our test instance) and I didn't see the possibility to add a date time field. It's only possible to add a normal date field, which should work during the migration.

Maybe you can give some more insides, at which place you were able to create a "datetime" field (could be a new feature and it's not updated in the documentation and not available in our plan?)?

Best regards,
Dominik

**Comment by itsupply25** [comment]
Hello Dominik, 

thank you for your answer. As you said, it is only possible to add date fields. Nevertheless it seems that the import job requires a handler for custom_date_time and custom_file. Otherwise the import routine results in an error and stuck. 

For testing purpose I've just modiefied following file:
zammad/lib/sequencer/unit/import/freshdesk/object_attribute/config.rb

Before:
```
  DATA_TYPE_MAP = {
    'custom_date'         => 'date',
    'custom_checkbox'     => 'boolean',
    'custom_dropdown'     => 'select',
    'custom_text'         => 'input',
    'custom_number'       => 'integer',
    'custom_paragraph'    => 'input',
    'custom_decimal'      => 'input', # Don't use 'integer' as it would cut off the fractional part.
    'custom_url'          => 'input',
    'custom_phone_number' => 'input',
    'default_ticket_type' => 'select',
  }.freeze
```

After:
```
DATA_TYPE_MAP = {
    'custom_date'         => 'date',
    'custom_date_time'    => 'date',
    'custom_file'         => 'input',
    'custom_checkbox'     => 'boolean',
    'custom_dropdown'     => 'select',
    'custom_text'         => 'input',
    'custom_number'       => 'integer',
    'custom_paragraph'    => 'input',
    'custom_decimal'      => 'input', # Don't use 'integer' as it would cut off the fractional part.
    'custom_url'          => 'input',
    'custom_phone_number' => 'input',
    'default_ticket_type' => 'select',
  }.freeze
```
Then the import job starts to import tickets. 

Best regards
Henry

**Comment by dominikklein** [comment]
@itsupply25 thanks for the feedback.

So in your system you really have the two additional types `custom_file` / `custom_date_time`? Are these custom features on the Freshdesk side or only available with a higher/special contract?

I don't know your technical skills, but it would be nice if you can give some insides with the following REST-Request from your system: `https://???.freshdesk.com/api/v2/ticket_fields`.

When Freshdesk really supports date time fields in some situations, it's no problem to support this.
For the file field, we can only skip (or maybe add this inside of the normal ticket attachments, but this sounds a little bit wrong to me).

Best regards,
Dominik

**Comment by itsupply25** [comment]
Hello Dominik, 

it seems, that there are default fields included. Maybe from Field Service functionallity. 

custom_date_time: 
```
{
        "id": 22000563934,
        "name": "cf_fsm_appointment_start_time",
        "label": "Appointment start time",
        "description": "",
        "position": 12,
        "required_for_closure": false,
        "required_for_agents": false,
        "type": "custom_date_time",
        "default": false,
        "customers_can_edit": false,
        "customers_can_filter": false,
        "label_for_customers": "Appointment start time",
        "required_for_customers": false,
        "displayed_to_customers": false,
        "created_at": "2019-11-24T16:34:47Z",
        "updated_at": "2020-07-28T07:38:08Z"
    },
    {
        "id": 22000563935,
        "name": "cf_fsm_appointment_end_time",
        "label": "Appointment end time",
        "description": "",
        "position": 13,
        "required_for_closure": false,
        "required_for_agents": false,
        "type": "custom_date_time",
        "default": false,
        "customers_can_edit": false,
        "customers_can_filter": false,
        "label_for_customers": "Appointment end time",
        "required_for_customers": false,
        "displayed_to_customers": false,
        "created_at": "2019-11-24T16:34:47Z",
        "updated_at": "2020-07-28T07:38:08Z"
    },
```

custom_file
```
    {
        "id": 22000564897,
        "name": "cf_fsm_customer_signature",
        "label": "Customer's signature",
        "description": "",
        "position": 56,
        "required_for_closure": false,
        "required_for_agents": false,
        "type": "custom_file",
        "default": false,
        "customers_can_edit": false,
        "customers_can_filter": false,
        "label_for_customers": "Customer's signature",
        "required_for_customers": false,
        "displayed_to_customers": false,
        "created_at": "2020-07-28T07:38:07Z",
        "updated_at": "2020-07-28T07:38:08Z"
    },
```

We do not use the fields currently. But it blocks the migration process. We are currently using Estate Plan of Freshdesk. 

Best regards
Henry

**Comment by dominikklein** [comment]
Thanks for the additional information, we will take a look.
