### ISSUE TITLE
KB custom URL redirects back to /help

### ISSUE THREAD

**Issue by drebs** [zammad/zammad#4345]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): Docker Compose
* Operating system: Linux Debian 11.5 (Bullseye)
* Database + version: postgres:15.0-alpine
* Elasticsearch version: bitnami/elasticsearch:8.5.0
* Browser + version: Mozilla Firefox 102.4.0esr

### Expected behavior:

* Accessing the Knowledge Base at https://example.org/custompath should redirect to https://example.org/custompath/lang-code.

### Actual behavior:

* Accessing the Knowledge Base at https://example.org/custompath redirects to https://example.org/help/lang-code

### Steps to reproduce the behavior:

* Configure a custom URL for Knowledge Base.
* Access your Knowledge Base at the custom URL (without including the language code)
* See that Zammad redirects you to /help/lang-code.

Example (i changed my real domain for `example.org`):

```
$ curl -Is https://example.org/ajuda | grep Location
Location: http://example.org/help/pt-br
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please provide the configuration of nginx container.
Custom KB URLs require custom configurations.

**Comment by drebs** [comment]
I'm using an Nginx front end reverse proxy with:

```
  location / {
    rewrite ^/ajuda(.*)$ /help$1 last;
    proxy_pass            http://zammad;
    proxy_read_timeout    90s;
    proxy_connect_timeout 90s;
    proxy_send_timeout    90s;
    proxy_set_header      Host $host;
    proxy_set_header      X-Real-IP $remote_addr;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header      X-Forwarded-Proto $scheme;
    proxy_set_header      Proxy "";
  }
```

No changes were made to the Nginx container config.

Thanks for your availability and help!

**Comment by drebs** [comment]
Solved, I was missing the following in the front end Nginx config:

```
proxy_set_header X-ORIGINAL-URL $request_uri;
```

That line was not deployed by mistake, and after adding it the behavior is now as expected.

Thank you, sorry for the noise, thanks for helping me rubberduck. :-)

**Comment by MrGeneration** [comment]
Sure.
Next time please consult our community at https://community.zammad.org for technical questions. :-) 🙏
