### ISSUE TITLE
Zammad looses EXIF Tags from Images taken and sent with an iPhone

### ISSUE THREAD

**Issue by MustafaTongul** [zammad/zammad#4347]
### Infos:

* Used Zammad version: 5.2.3 
* Installation method (source, package, ..): Any
* Operating system: Any 
* Database + version: Any 
* Elasticsearch version: Any
* Browser + version: Any
* Ticket: #10118061, #10119273

### Expected behavior:

* Pictures taken with an iPhone upside down are automatically corrected and displayed "the right way round" in Zammad when sent by e-mail.

### Actual behavior:

* Pictures taken with an iPhone upside down are not automatically corrected and displayed upside down in Zammad when sent by e-mail.

### Steps to reproduce the behavior:

* Take a photo with an iPhone and send it as an email to Zammad

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
@MustafaTongul please add an example email. Thanks!

**Comment by mantas** [comment]
Sample pictures. Later is upside-down.

![IMG_4803](https://user-images.githubusercontent.com/36944/200824617-c2ed1fb2-69e0-4b2f-8222-7c47d0de112d.jpeg)
![IMG_4804](https://user-images.githubusercontent.com/36944/200824622-70ef3548-05f9-4b9b-ae45-b2abe782b2c7.jpeg)

**Comment by fliebe92** [comment]
Technical hint: https://github.com/mtgrosser/rszr#image-auto-orientation
