### ISSUE TITLE
GitLab Integration

### ISSUE THREAD

**Issue by dnauck** [zammad/zammad#435]
Same use case as #267 (Zammad <-> JIRA Integration) , just another Tool (GitLab)

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes

**Comment by dnauck** [comment]
Hi @hanneshal,

why do you close this feature request? It has over 18+?
If you need further input just ask.

Kind regards,

Daniel

**Comment by maximegaillard** [comment]
Agreed,

Gitlab is a very powerful and popular tool. An integration between two open-source and popular softwares can be extraordinary for everybody.

I thought to theses use cases:
- Link a Zammad ticket to a Gitlab issue (maybe through the LINK menu in the ticket sidebar?)
- One click to create a Gitlab issue with auto-linking to the ticket: maybe do it with a macro?
- Create a ticket when Gitlab send an email to Zammad using email headers https://docs.gitlab.com/ee/workflow/notifications.html#email-headers

Gitlab has already some integrations with great tools like Sentry or Trello. It could be great to be inspired by it.

**Comment by Heljick** [comment]
@hanneshal @martini Why is that thread closed when Github is open and Gitlab getting more popular since Microsoft bought Github and there is more thumbs up than others ?

That will be great indead to have a feature to push a ticket to Gitlab for the dev without needing to connect into It or to Zammad for the dev, and to get a notification in the ticket when the dev has patch de issue to be able to contact the customer and close the issue.

**Comment by Braintelligence** [comment]
Perhaps there is no interest since GitLab offers a Service Desk system for their Gitlab EE Premium/Ultimate Package...

**Comment by kmanojkumar** [comment]
There is a lot of advantage if GitLab issues and user accounts can directly be linked with Zammad. Because many of the enterprises do have community edition installed and use Zammad for support management. Login with GitLab is already there to complement: https://zammad-admin-documentation.readthedocs.io/en/latest/security-thirdparty/gitlab.html

**Comment by ton3r** [comment]
We are currently evaluating  Support Management Systems. Zammad seems a good way for us. And a Gitlab integration like @maximegaillard described, would be very very nice

**Comment by degoya** [comment]
that's what i'm still missing in zammad. please add gitlab integration.

**Comment by MrGeneration** [comment]
I'm limiting this conversation to contributors only.
Please don't get us wrong - this is already a enhancement issue that's on our backlog.

We will add it sooner or later, but we currently focus on other stuff.
If you want to sponsor this feature, please feel always welcome to drop us a mail at sales [at] zammad [dot] com.

This will priotize the implementation greatly.

**Comment by rolfschmidt** [comment]
Hello guys,
we got some support to implement the gitlab integration. It will contain the possibility to connect to your gitlab environment and link issues to tickets in V1. It will display information about the issue, assignee, milestone and labels.

@maximegaillard

> Agreed,
> 
> Gitlab is a very powerful and popular tool. An integration between two open-source and popular softwares can be extraordinary for everybody.
> 
> I thought to theses use cases:
> 
>     * Link a Zammad ticket to a Gitlab issue (maybe through the LINK menu in the ticket sidebar?)
> 

This will be the case.

>     * One click to create a Gitlab issue with auto-linking to the ticket: maybe do it with a macro?
> 

Not sure what you mean? Like a fixed issue which can be easily linked to multiple tickets via macro?

This will not be part of V1. If you are interested in this enhancement, please [create a thread](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals/6) with more information and use cases.

>     * Create a ticket when Gitlab send an email to Zammad using email headers https://docs.gitlab.com/ee/workflow/notifications.html#email-headers
> 

Link doesnt work anymore. But i found some headers. Sounds interesting.

This will not be part of V1. If you are interested in this enhancement, please [create a thread](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals/6) with more information and use cases.

> 
> Gitlab has already some integrations with great tools like Sentry or Trello. It could be great to be inspired by it.

@Heljick 

> 
> 
> @hanneshal @martini Why is that thread closed when Github is open and Gitlab getting more popular since Microsoft bought Github and there is more thumbs up than others ?
> 
> That will be great indead to have a feature to push a ticket to Gitlab for the dev without needing to connect into It or to Zammad for the dev, and to get a notification in the ticket when the dev has patch de issue to be able to contact the customer and close the issue.

The idea to push the ticket information to the issue or the issue change to the ticket would be a interesting feature request.

This will not be part of V1. If you are interested in this enhancement, please [create a thread](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals/6) with more information and use cases.

@kmanojkumar

> 
> 
> There is a lot of advantage if GitLab issues and user accounts can directly be linked with Zammad. Because many of the enterprises do have community edition installed and use Zammad for support management. Login with GitLab is already there to complement: https://zammad-admin-documentation.readthedocs.io/en/latest/security-thirdparty/gitlab.html

I'm not sure what the use cases would be to link user accounts of gitlab to zammad? Never saw anymore use profile data actively of gitlab? Use cases would be interesting here.

This will not be part of V1. If you are interested in this enhancement, please [create a thread](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals/6) with more information and use cases.
