### ISSUE TITLE
Freshdesk migration raises "Connection reset by peer - SSL_connect"

### ISSUE THREAD

**Issue by itsupply25** [zammad/zammad#4350]
### Infos:

* Used Zammad version: Newest
* Installation method (source, package, ..): Package
* Operating system: Debian
* Database + version:
* Elasticsearch version:
* Browser + version: Google Chrome newest

### Expected behavior:

Freshdesk Migration should import all 30.000 Tickets without any error. Or possibillity to proceed with migration from point of error occurence.

### Actual behavior:

Freshdesk Migratoin stops importing of tickets randomly. (after 21000 Tickets or 7100 Tickets, etc.)
Migration ends with Error: Connection reset by peer - SSL_connect

### Steps to reproduce the behavior:

Start Freshdesk Migration with huge amount of tickets

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
@itsupply25 Maybe you can give some more insides form the log file, because normally I didn't see such problems with the Freshdesk import.
I know that Zendesk has problems with there own servers (https://github.com/zammad/zammad/issues/4169) and we did some improvements in this direction with some more retries, maybe we need something similar for Freshdesk.

**Comment by itsupply25** [comment]
Here are some lines of the log file:
```
lib/sequencer/units.rb:27:in `each'
lib/sequencer/units.rb:27:in `each'
lib/sequencer.rb:71:in `each_with_index'
lib/sequencer.rb:71:in `block in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:69:in `process'
lib/sequencer.rb:24:in `process'
lib/import/mixin/sequence.rb:17:in `process'
lib/import/freshdesk.rb:8:in `start'
app/models/import_job.rb:25:in `start'
app/jobs/async_import_job.rb:11:in `perform'
lib/background_services/service/process_delayed_jobs.rb:25:in `block (2 levels) in launch'
lib/background_services/service/process_delayed_jobs.rb:23:in `block in launch'
lib/background_services/service/process_delayed_jobs.rb:20:in `loop'
lib/background_services/service/process_delayed_jobs.rb:20:in `launch'
lib/background_services/service.rb:27:in `block in run'
lib/application_handle_info.rb:19:in `use'
lib/background_services/service.rb:33:in `block in run_in_service_context'
lib/background_services/service.rb:32:in `run_in_service_context'
lib/background_services/service.rb:26:in `run'
lib/background_services.rb:67:in `block in start_as_thread'
I, [2022-11-10T12:00:54.499395 #1331-109360]  INFO -- : Started GET "/api/v1/import/freshdesk/import_status?_=1668075185886" for 10.7.201.238 at 2022-11-10 12:00:54 +0100
I, [2022-11-10T12:00:54.506752 #1331-109360]  INFO -- : Processing by ImportFreshdeskController#import_status as JSON
I, [2022-11-10T12:00:54.506830 #1331-109360]  INFO -- :   Parameters: {"_"=>"1668075185886"}
I, [2022-11-10T12:00:54.516811 #1331-109360]  INFO -- : Completed 200 OK in 10ms (Views: 0.6ms | ActiveRecord: 0.9ms | Allocations: 2766)
I, [2022-11-10T12:00:59.549317 #1331-109420]  INFO -- : Started GET "/api/v1/import/freshdesk/import_status?_=1668075185887" for 10.7.201.238 at 2022-11-10 12:00:59 +0100
I, [2022-11-10T12:00:59.555330 #1331-109420]  INFO -- : Processing by ImportFreshdeskController#import_status as JSON
I, [2022-11-10T12:00:59.555396 #1331-109420]  INFO -- :   Parameters: {"_"=>"1668075185887"}
I, [2022-11-10T12:00:59.562827 #1331-109420]  INFO -- : Completed 200 OK in 7ms (Views: 0.4ms | ActiveRecord: 1.1ms | Allocations: 2359)
I, [2022-11-10T12:01:00.348341 #1338-108760]  INFO -- : ProcessScheduledJobs running...
I, [2022-11-10T12:01:04.581067 #1331-108660]  INFO -- : Started GET "/api/v1/import/freshdesk/import_status?_=1668075185888" for 10.7.201.238 at 2022-11-10 12:01:04 +0100
I, [2022-11-10T12:01:04.587827 #1331-108660]  INFO -- : Processing by ImportFreshdeskController#import_status as JSON
I, [2022-11-10T12:01:04.587904 #1331-108660]  INFO -- :   Parameters: {"_"=>"1668075185888"}
I, [2022-11-10T12:01:04.593080 #1331-108660]  INFO -- : Completed 200 OK in 5ms (Views: 0.3ms | ActiveRecord: 0.6ms | Allocations: 2353)
E, [2022-11-10T12:01:06.688792 #1338-108720] ERROR -- : ImportJob 'Import::Freshdesk' failed: Connection reset by peer - SSL_connect
E, [2022-11-10T12:01:06.688979 #1338-108720] ERROR -- : Connection reset by peer - SSL_connect (Errno::ECONNRESET)
lib/sequencer/unit/import/freshdesk/requester.rb:50:in `perform_request'
lib/sequencer/unit/import/freshdesk/requester.rb:10:in `block in request'
lib/sequencer/unit/import/freshdesk/requester.rb:9:in `times'
lib/sequencer/unit/import/freshdesk/requester.rb:9:in `request'
lib/sequencer/unit/import/freshdesk/request.rb:24:in `response'
lib/sequencer/unit/common/provider/attribute.rb:29:in `value'
lib/sequencer/unit/common/provider/attribute.rb:34:in `ignore?'
lib/sequencer/unit/common/provider/attribute.rb:10:in `process'
lib/sequencer/unit/import/common/model/mixin/skip/action.rb:49:in `process'
lib/sequencer/unit/base.rb:249:in `process'
lib/sequencer.rb:76:in `block (4 levels) in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:75:in `block (3 levels) in process'
lib/sequencer/state.rb:152:in `process'
```

**Comment by itsupply25** [comment]
Hello @dominikklein any news/improvements regarding this issue? Do you need more information?

Thanks in advance.

Best regards
Henry

**Comment by MrGeneration** [comment]
Please don't bump issues, thank you.
We're generally not communicating ETAs.

**Comment by itsupply25** [comment]
Hello, the problem still exists. If I try to migrate freshdesk system at the begining, the migration task crashes after a certain time. 
![06-11-_2023_11-45-36](https://github.com/zammad/zammad/assets/62522718/8039973c-83df-4ad0-942d-4a7d370064ae)

We have app. 40000 Tickets to migrate. If this migration task is not working, it make no sense for us to switch to zammad, even with paid plan. Is it possible to implement a retry button that proceeds if an error occurs and rememers the last successfully importet ticket? Would be great to have a working freshdesk migration procedure. 

The process improved since last year. But it still does not work without any problems.

**Comment by MrGeneration** [comment]
Please create a new issue referring this one as regression for better overview.

**Comment by dominikklein** [comment]
I think we could try to add a retry like we added for the Zendesk migration. In the end, it seems that this problem is not on related to our side, so we can only work around this.

**Comment by itsupply25** [comment]
> I think we could try to add a retry like we added for the Zendesk migration. In the end, it seems that this problem is not on related to our side, so we can only work around this.

@dominikklein I also think, that the problem is not related to zammads side. But as you said, a work around is needed. Is it easy to implement this Retry Button as a quick fix?

**Comment by dominikklein** [comment]
@itsupply25 such a reply button is a bigger enhancement, but I added now hopefully a retry for this situation when the single request is failing. Should be available in current stable during the day.
Maybe you can test afterwards and when there is still a problem, we can try to improve it more.

**Comment by itsupply25** [comment]
Unfortunately this fix did not solve the problem. The error still remains. I created two environmens:
1) With docker
2) Install from source

In both I get the error. What I recognised is, that with docker the migrations task is able to transfer more tickets until the error raises (app. 4000-7000). On the source install version I didn't managed it to come over 1000. 

Are there any other quick fix options. I also tried to modify the sleep intervals from 10 to 180 in requester.rb. But this also made no difference.

**Comment by dominikklein** [comment]
Very strange, we migrated in the past a lot of customers from Freshdesk without this kind of problem and here we had also some with a very big amount of data (more than 1 million entities).

I will try during the week, to make it more robust, but looks very

**Comment by dominikklein** [comment]
@itsupply25 added an improvement which should trigger the retry now for every situation. So maybe this helps more.
