### ISSUE TITLE
Instance system information in system admin area

### ISSUE THREAD

**Issue by tschaefer** [zammad/zammad#4351]
# User story

As an administrator or Zammad supporter, I want quick info about the running Zammad instance and further service and operating system properties. As an administrator, I should provide this information on any support request. As Zammad supporter the information will help to simulate and reproduce customer issues.

# Implementation ideas

* create new page `Admin > System > Info` providing following info
  * `Rails::Info` including
    * rails version
    * ruby version
    * ruby gems version
    * rack version
    * javascript runtime
    * middleware packages
    * app root
    * rails environment
    * db adapter
    * db schema version
  * cpu
  * memory
  * disk
  * Elasticsearch version
  * Redis version
  * Memcached version
  * Database type + version

**Comment by MrGeneration** [comment]
Why not use the existing version page for it?
This is the most useless admin page as of now because it contains exactly one line.

We could rename it to "Info" or better "Versions"

**Comment by dominikklein** [comment]
Can be closed, because of: https://github.com/zammad/zammad/commit/c4fedde979a086208b635c67970aa16d59249f63
