### ISSUE TITLE
Minor GUI problems in Internet Explorer 11

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad#4352]
### Infos:

* Used Zammad version: 5.3.x (develop)
* Installation method (source, package, ..): source (git)
* Operating system: Windows 7
* Database + version: PostgreSQL 10.21
* Elasticsearch version: 7.16.3
* Browser + version: IE 11.0.9600.16428IS

### Expected behavior:

* App UX in IE11 should be comparable to the experience in one of the modern browsers, albeit with graceful degradation for certain features. A IE11 is still officially supported, we should make sure there are no problems preventing users and admin from using the app.

### Actual behavior:

* There are a couple of minor GUI problems in IE11 that may result in diminished app functionality. In this cases, access to a more modern browser might be recommended.

  <details>
    <summary>Multiple screens > Dialog fails to open + error in the console</summary>
    <h5>Manage > Overviews</h5>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201137274-49dc83f9-8f05-4be3-a0e1-c4a36b7e5b13.png">
    <h5>Manage > Report Profiles</h5>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201137396-5d0befc1-9ffe-4380-bd3f-1ac0f97df84f.png">
    <h5>Manage > Scheduler</h5>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201137967-6d5eac9a-0151-49ec-8997-798cb8dc6b0d.png">
    <h5>Manage > SLAs</h5>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201138037-eda1765b-4334-43f8-a015-a286e22e17a6.png">
    <h5>Manage > Trigger</h5>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201138178-4eba81b9-f5ea-4200-91dd-adee1f0c6a5e.png">
    <h5>System > Core Workflows</h5>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201138636-b2662f76-264d-4d45-98f4-d1cb8be03ece.png">
  </details>

  <details>
    <summary>User Menu > Icon background hover color</summary>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201138551-356adf74-9eb7-4a08-a95b-b061aec1dff4.png">
  </details>

  <details>
    <summary>Manage > Users > Wrong field size in dialog + stuck autocomplete dropdowns</summary>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201138925-0c9414c0-edee-474e-88a0-703529e6ac0c.png">
  </details>

  <details>
    <summary>Manage > Calendars > Element alignment in dialog</summary>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201136280-d70d08c1-5af6-462b-a139-a91ddcaf358f.png">
  </details>

  <details>
    <summary>Manage > Knowledge Base > Languages dropdown stuck + element alignment</summary>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201136915-749769ed-698c-4c03-8251-ad575df347d6.png">
  </details>

  <details>
    <summary>Channels > Form > Element alignment</summary>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201136699-47f6fda7-f286-4c95-ad7b-2aae16bd84be.png">
  </details>

  <details>
    <summary>Profile > Notifications > Element alignment</summary>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201137002-53b34d96-a88f-4d90-b06a-9f77ca1d9d5b.png">
  </details>

  <details>
    <summary>Profile > Devices > Element alignment</summary>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201136480-c8c6d9c2-65c7-4e91-b5af-bbe52c3fa395.png">
  </details>

  <details>
    <summary>Profile > Token Access > Element alignment</summary>
    <img alt="" src="https://user-images.githubusercontent.com/6049445/201139106-7718124f-c929-4747-a36e-11964ceecfaf.PNG">
  </details>

### Steps to reproduce the behavior:

* Access a Zammad instance running in a production environment with IE11.
* Log in and navigate to one of documented screens above, and either observe the problem or try to reproduce by clicking on the element.
* Further information might be shown in the browser console log (F11).

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
Let's close it as not planned, we will not touch this anymore.

**Comment by dvuckovic** [comment]
Good riddance!
