### ISSUE TITLE
SLA is not recalculated when SLA is deactivated

### ISSUE THREAD

**Issue by MustafaTongul** [zammad/zammad#4353]
### Infos:

* Used Zammad version: Any
* Installation method (source, package, ..): Any 
* Operating system: Any 
* Database + version: Any 
* Elasticsearch version: Any 
* Browser + version: Any 
* Ticket: #10117018

### Expected behavior:

* If an existing SLA is deactivated, the SLA calculation is re-initiated for all existing and open tickets. Tickets that have already been escalated will leave the escalation mode.

### Actual behavior:

* If an existing SLA is deactivated, the SLA calculation is re-initiated for all existing and open tickets. However, tickets that have already been escalated remain in escalation mode. Notifications about the escalation of affected tickets will continue to be sent.

### Steps to reproduce the behavior:

* Create an SLA. Then create a ticket and let it escalate. After escalating the ticket, deactivate/delete the SLA.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by templis** [comment]
Is there a way to find those Tickets, so that we can delete the "SLA" tag of the affected tickets?

**Comment by MrGeneration** [comment]
Please don't hijack issues with your technical questions, thank you.
