### ISSUE TITLE
Ticket Escalation dashboard box description enhancement

### ISSUE THREAD

**Issue by maxxer** [zammad/zammad#4357]
### Infos:

* Used Zammad version: 5.2.3-1666860729.1f5facea.focal
* Installation method (source, package, ..): packages
* Operating system: Ubuntu 20.04
* Database + version: Postgresql 14+232.pgdg20.04+1
* Elasticsearch version: elasticsearch-oss 7.10.2
* Browser + version: any

### Expected behavior:

* Consistent punctuation in dashboard

### Actual behavior:

* Escalated ticket is the only string in the summary ending with a dot

### Steps to reproduce the behavior:

Yes I'm sure this is a bug and no feature request or a general question.

String source: https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/views/dashboard/stats/ticket_escalation.jst.eco#L0

![immagine](https://user-images.githubusercontent.com/240201/201704209-19c1ece8-6027-48b2-a4cf-06d8dea1089f.png)

**Comment by Xata** [comment]
I've removed the period in the string inside of ticket_escalation.jst.eco. 
I confirmed that the period no longer renders on the page: 
![screenshot_changes_made](https://github.com/zammad/zammad/assets/1977132/8996c1fc-5e9c-4b86-89a5-8c9c49b539a6)
