### ISSUE TITLE
Group restriction for text modules not working on ticket creation (specific scenario only)

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4358]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): hosted
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Firefox current
* Ticket: #10111815

### Expected behavior:

* If I am not able to select a group in the ticket creation I am not able to use text modules restricted to other groups than the group my ticket will be created in.

### Actual behavior:

* If I am not able to select a group in the ticket creation as an agent, I am able to use all text modules, regardless of their group restrictions.

### Steps to reproduce the behavior:

* Create an agent with ticket creation permissions only for one group. (This way, the agent cannot select a group in the ticket creation screen).
* Create text_modules for several groups.
* Try to use them in the ticket creation screen.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dominikklein** [comment]
@fliebe92 @rolfschmidt seems to be this is not fixed or broken again.
