### ISSUE TITLE
New ticket object attributes won't disappear in Triggers and SLAs

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#436]
If you create a new attribute for tickets, it won't show up in the trigger conditions.

Could be related to https://github.com/zammad/zammad/issues/245

**Comment by martini** [comment]
JFI: It's all the same ui element. Also related to this https://github.com/zammad/zammad/issues/394

**Comment by martini** [comment]
It's implemented in upcoming 1.4.

Here an example screen:
<img width="750" alt="screen shot 2017-03-14 at 17 48 09" src="https://cloud.githubusercontent.com/assets/110226/23911938/9781a026-08de-11e7-80e4-c30aa2022818.png">
