### ISSUE TITLE
Inline translation not working in chromium based browser

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4360]
### Infos:

* Used Zammad version: any
* Installation method (source, package, ..): any
* Operating system: Windows
* Database + version: any
* Elasticsearch version: any
* Browser + version: Chromium-based (Chrome & Edge at least)
* Ticket#10115149

### Expected behavior:

* Be able to use inline translation.

### Actual behavior:

* Shift+Ctrl+T is a used shortcut by Chromium based browser and will not trigger the inline translation.

### Steps to reproduce the behavior:

* User Chromium based browser (Windows) and try to use the inline translation.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Duplicate of #656
