### ISSUE TITLE
Avatar highlight gets lost when leaving hover area even through context menu is active

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4363]
### Infos:

* Used Zammad version: develop / 5.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on latest Google Chrome and Firefox (Windows)

### Expected behavior:

When clicking on your avatar, the avatar highlight will stay visible even if you live the hover area as the context menu is still active.

### Actual behavior:

Avatar highlight "gets lost" as soon as you move the hover area. This looks "funny".

![highlightyouok](https://user-images.githubusercontent.com/6549061/202485102-1fde01e2-f300-4ee9-a453-8f30498b26e2.gif)

### Steps to reproduce the behavior:

* On any view click on the lower left avatar and move your mouse around

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
wait, is this even a bug? In the old version the white background was always there if you move your cursor in the menu?

**Comment by MrGeneration** [comment]
Every application on this planet leaves its context menu parent "active" visually even if your mouse doesn't life in the area of the context menu. It visually looks broken.

Like here:
![image](https://user-images.githubusercontent.com/6549061/202486831-d958cf35-c04b-4739-87b0-3572bc19216e.png)

![image](https://user-images.githubusercontent.com/6549061/202486970-57be1acc-edfc-4139-a6f8-9eb1a884daf9.png)


Or am I just getting old and crumpy and missed a new design strategy?

**Comment by mrflix** [comment]
Definitely not intentional
