### ISSUE TITLE
Customer should not have the internal attribute to set in customer interface.

### ISSUE THREAD

**Issue by martini** [zammad/zammad#437]
<img width="102" alt="screen shot 2016-11-17 at 14 51 52" src="https://cloud.githubusercontent.com/assets/110226/20391850/79444d08-acd5-11e6-98fe-e8c6121ba924.png">

Thanks @Julian0o

**Comment by Julian0o** [comment]
;)

**Comment by martini** [comment]
Fixed in develop, 1.0 und 1.1 https://github.com/zammad/zammad/commit/fbacb36f026c529a44b07c80be6a24a1710e0179.
