### ISSUE TITLE
Missing L in Reply to config

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#4371]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04
* Browser + version: Edge

If I go to Admin > E-Mail > Einstellung and open the drop down für Reply to config the last option has a missing L

![image](https://user-images.githubusercontent.com/1473674/202861577-ecdc7cc3-c7f7-4690-b06c-8eb0ee8c5d90.png)

**Comment by MrGeneration** [comment]
Translations are handled over at https://translations.zammad.org and can be adjusted by anyone with e.g. an Github account.
