### ISSUE TITLE
Wrong encoded string

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#438]
Take a look at https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/index.coffee#L117

The href part has to be URL encoded.

**Comment by martini** [comment]
Any example for unit tests available?

**Comment by thorsteneckel** [comment]
`<a href="tel://+49 30 886-111111">+49 30 886-111111</a>`

should be

`<a href="tel://+4930886-111111">+49 30 886-111111</a>`

Since `"tel" URIs MUST NOT use spaces in visual separators to avoid excessive escaping.` (RFC 3966, https://tools.ietf.org/html/rfc3966#section-5.1.1)

**Comment by martini** [comment]
JFI: I guess url encoding is still needed.

`<a href="tel://+4930886-111111">+49 30 886-111111</a>`

Should be:

`<a href="tel://%2B4930886-111111">+49 30 886-111111</a>`
