### ISSUE TITLE
Dark mode: Poor readonly contrast security UI (callback urls)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4383]
### Infos:

* Used Zammad version: stable / 5.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on Firefox for Windows (latest)

### Expected behavior:

Dark mode has proper contrast in read only "security callback URLs" scopes

### Actual behavior:

Read only input fields have a *very* poor contrast within security UI.

![image](https://user-images.githubusercontent.com/6549061/203550067-8e48e001-6497-4628-858f-93c1a7088564.png)

### Steps to reproduce the behavior:

* go to Admin -> Security -> Thirdparty applications

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mrflix** [comment]
Thank you @MrGeneration for reporting the bug.
