### ISSUE TITLE
Priority icons in ticket overviews have lost their color

### ISSUE THREAD

**Issue by Stubenhocker1399** [zammad/zammad#4384]
### Infos:

* Used Zammad version: develop 3768f6f736a3acf3444fd50d10a3358f0af2ffa0 and 5.3 0266d1733788c637012e38fc8c6de908d37174be
* Installation method (source, package, ..): source and package
* Operating system: Arch Linux & Ubuntu 20.04.5
* Database + version: irrelevant
* Elasticsearch version: irrelevant
* Browser + version: Google Chrome Version 107.0.5304.110 (Official Build) (64-bit)

### Expected behavior:

* Setting `ui_ticket_overview_priority_icon` Priority icons in ticket overview not having lost their color in new release compared to 5.2

### Actual behavior:

* Setting `ui_ticket_overview_priority_icon` Priority icons in ticket overview have lost their color in new release compared to 5.2

### Steps to reproduce the behavior:

* Set `Setting.set('ui_ticket_overview_priority_icon', true)` in rails console
* Have ticket with high priorty
* Observe icons in previous release
* Upgrade Zammad to 5.3
* Icons now have lost their coloring

![Peek 2022-11-24 14-36](https://user-images.githubusercontent.com/6693160/203797501-923cd80b-a91b-41ee-9187-926922ae0b13.gif)

![image](https://user-images.githubusercontent.com/6693160/203798367-6b88ad4d-226e-4d1d-96e0-3c8dc1467760.png)

Style that overrides the color: https://github.com/zammad/zammad/blob/d00587f44ce3e9ef4a9648c434fba764fc745972/app/assets/stylesheets/zammad.scss#L3725-L3727

Yes I'm sure this is a bug and no feature request or a general question.

Edit: Wrong version number 4.3 vs 5.3, oops :sweat_smile:

**Comment by fliebe92** [comment]
Regression of 801ce90c114893662d83a4ea9effdd1190b547ed

**Comment by mrflix** [comment]
Thank you @Stubenhocker1399 for reporting the bug.
