### ISSUE TITLE
Open ticket indicator does not get colored when ticket count is 3 with enabled colored indicators

### ISSUE THREAD

**Issue by Stubenhocker1399** [zammad/zammad#4387]
### Infos:

* Used Zammad version: 5.3.0-1669114633.0266d173.focal and develop 806111fc2772b4d4dd958d2dc8cff453efda94a3
* Installation method (source, package, ..): package and source
* Operating system: Ubuntu 20.04.5 and Arch Linux
* Database + version: irrelevant
* Elasticsearch version: irrelevant
* Browser + version: Google Chrome Version 107.0.5304.110 (Official Build) (64-bit)

### Expected behavior:

* Setting `ui_sidebar_open_ticket_indicator_colored`  colors side bar open ticket count for any number above 2

### Actual behavior:

* Setting `ui_sidebar_open_ticket_indicator_colored`  does not work for an open ticket count of exactly 3, continues to work at 4

### Steps to reproduce the behavior:

* Set `Setting.set('ui_sidebar_open_ticket_indicator_colored', true)` in rails console
* Have customer with exactly three open tickets
* Check customer icon on sidebar to see counter not being colored

![image](https://user-images.githubusercontent.com/6693160/203830851-13ccf011-3c94-466d-be7b-6ab41b39d215.png)
![image](https://user-images.githubusercontent.com/6693160/203831647-c487e412-77b9-499a-ac11-804e00889241.png)
![image](https://user-images.githubusercontent.com/6693160/203831496-ba5d9e42-7414-4bfa-973e-27aa81c3779e.png)
![image](https://user-images.githubusercontent.com/6693160/203831548-8a62d9cf-d3d5-4de6-b9e2-c581599f22ab.png)

On a sidenote: the warning color could probably be improved for readability here in the light theme.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
It's interesting that this setting acts differently for agents and customers. 

Agents see warning for 1 and danger for 2+. Customers see warning for 2 and danger is supposed to be 3+.

@dominikklein does it need a PM decision to unify this number? I don't remember any historical reason for those numbers to be different. Looks like a mistype.

**Comment by dominikklein** [comment]
@mantas This is not about the difference between agent and customer, it's about the ticket detail view screen and the ticket create screen.

I talked with the PO about this topic and the numbers are currently correct because we have two different use cases/situations on different screens.

So only the condition in the ticket zoom (like done in the PR) needs to be fixed.
