### ISSUE TITLE
user select missing on ticket assign area

### ISSUE THREAD

**Issue by nitinarora39** [zammad/zammad#4389]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): package
* Operating system: ubuntu 20.04
* Database + version: postgresql (by default with package)
* Elasticsearch version: any (by default with package)
* Browser + version: any 

### Expected behavior:

* ticket assign to agent wants to show 

### Actual behavior:

* ticket assign section not showing in ticket assign area

### Steps to reproduce the behavior:

* kindly update zammad with a update that must have  *assign to agent* button

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry but your description is not using any Zammad termonology and talks about potential buttons that are not part of Zammad.

WHAT is the issue? A screenshot might help.
Are you talking about the owner field?
![image](https://user-images.githubusercontent.com/6549061/203838553-3a43a467-84bf-41bf-a082-a6c62c2510cf.png)

**Comment by fliebe92** [comment]
Hello @nitinarora39,

thanks for your report. Could you please describe the issue in a way that we are able to understand the issue? Maybe also [this comment](https://github.com/zammad/zammad/issues/4389#issuecomment-1326701805) helps to make it clearer and shed some light here.

Thanks again!

**Comment by MrGeneration** [comment]
I'm closing this as a question due to missing feedback.
