### ISSUE TITLE
URL-encoding of variables in link-templates

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4392]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket#10115195

### Expected behaviour:

* When I use variables in link templates, the inserted values should be properly URL-encoded.

### Actual behaviour:

* The values of inserted variables on link templates are not URL-encoded.

### Steps to reproduce the behaviour:

* Create an attribute on the object manager and use the variable function. Insert a value with characters that need to be URL-encoded.

Yes, I'm sure this is a bug, not a feature request or general question.

**Comment by dvuckovic** [comment]
I was not able to reproduce this in Zammad 5.3.0 (stable), the link template variables are properly escaped.

Here are the steps I followed:

1. Create a new ticket Object Attribute of type **Text field** and name it `text_field`.
2. In **Link template** field of the attribute form enter the following template:
   `https://google.com/search?q=#{ticket.text_field}`
3. Create a new ticket and set the text field attribute to a problematic value (i.e. `?`).
4. Go to ticket detail view and verify that the link is properly encoded and it works:
   <img width="445" alt="Screenshot 2022-12-07 at 13 00 07" src="https://user-images.githubusercontent.com/6049445/206187961-14048cb3-53ae-4ba2-abce-214f5b69f360.png">

Looking at the code, the values in these links are escaped with `encodeURIComponent()` which is a proper way of making them work when used as query parameters. Not so much for URI parameters, as this encoding seems to be indiscriminate.

Please provide the steps for reproduction and we can look into this further. Thanks!

**Comment by YetAnotherGerrit** [comment]
It is working now. I don't know where I misinterpreted this thing. Sorry for keeping you busy and thank you for looking into it.
