### ISSUE TITLE
ActiveRecord::InvalidForeignKey when importing OTRS 6 Data

### ISSUE THREAD

**Issue by Nobsadmin** [zammad/zammad#4395]
# Infos:

* Used Zammad version: 5.3.0-1669364938.83ce4433.focal
* Installation method (source, package, ..): Package
* Operating system: Ubuntu Server 20.4
* Database + version: mariadb-server-10.3
* Elasticsearch version: elasticsearch-oss/stable,now 7.10.2
* Browser + version: Google Chrome 107.0.5304.107

OTRS 6 Version
6.0.3
Znuny4OTRS-Repo	
6.0.76
Znuny4OTRS-ZammadMigrator	
6.0.7

### Expected behavior:

Importing OTRS 6 DATA into fresh Zammad Instance finishes withour error messages

### Actual behavior:

Note: This issue is similar to Issue #1713 which had a solution that did not solve this problem. 
i thoroughly apologize if this **does** fall under technical questions.  

When importing Prioties through Import::OTRS::start the process stops similarily to Issue #1713.

<code>thread#-: loading Priority...
thread#-: POST: https://TheDomainMyOTRSIsOn/otrs/public.pl?Action=ZammadMigrator
thread#-: PARAMS: {:Subaction=>"Export", :Object=>"Priority", :Limit=>"", :Offset=>"", :Diff=>0, :Action=>"ZammadMigrator", :Key=>"MyKeyThatIEntered}
thread#-: update Ticket::Priority.find_by(id: 1)
/opt/zammad/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.4/lib/mysql2/client.rb:148:in `_query': Mysql2::Error: Cannot add or update a child row: a foreign key constraint fails (`zammad`.`ticket_priorities`, CONSTRAINT `fk_rails_d43af6872e` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`)) (ActiveRecord::InvalidForeignKey)
/opt/zammad/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.4/lib/mysql2/client.rb:148:in `_query': Cannot add or update a child row: a foreign key constraint fails (`zammad`.`ticket_priorities`, CONSTRAINT `fk_rails_d43af6872e` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`)) (Mysql2::Error)</code>

I have checked previous bug reports and solutions before and created a root@localhost user. 
I used the root to log in to OTRS 6 and changed all Priority objects names and validities to the default value and published these changes. 
This did not have an effect on the issue. 

### Steps to reproduce the behavior:

Installing Zammad and requirements as found in https://computingforgeeks.com/install-zammad-helpdesk-system-on-ubuntu/ (Steps 1 and 2) and https://docs.zammad.org/en/latest/install/package.html (Installation of Zammad)
Finishing the setup
Accessing the ubuntu shell and starting the import of data as found in the documentation.

Yes I'm sure this is a bug and no feature request or a general question.

[production.log](https://github.com/zammad/zammad/files/10093242/production.log)

**Comment by Nobsadmin** [comment]
While waiting i will setup Zammad anew with a Postgresql database and only the zammad documentation as the guide i used used a deprecated command and who knows what else i could have done wrong

**Comment by MrGeneration** [comment]
Please verify the migration process with a clean postgresql installation.
If the postgresql approach works, we'll close this here as a wont fix.

**Comment by Nobsadmin** [comment]
I have installed Zammad anew. This time only following the official documentation. 
Now i see an error that is identical to the above mentioned issue. 
This can be closed. 
Will follow solution in #1713

**Comment by Nobsadmin** [comment]
Is the solution in #1713 editing the priorities with the User that has the ID "1"? 
My superadmin user has ID 43.

**Comment by Nobsadmin** [comment]
![image](https://user-images.githubusercontent.com/119046865/204097857-1a361f93-7465-4e59-91d0-43709b331b24.png)
Any way to EDIT the created by ID? The modified ID is already 1 now but importing still stuck on priorities.
Editing the ID in SQL itself did not change the behaviour. 
Zammad still claims, that the created_by ID is 43 and will not update. 
Will try to reinstall Zammad once again to maybe clear a cache that i don't know of.

**Comment by MrGeneration** [comment]
Please don't post technical questions on this repository.
If you have technical questions, use the Zammad community instead: https://community.zammad.org

**Comment by Nobsadmin** [comment]
Not a technical question. The workaround in #1713 does not work for priorities **created** by different users than root@localhost.  
Editing those SQL Values also does not work around users being imported after priorities. 

"However, we will refactor the import logic from the ground up and fix this issue with this." #1713 
Has there been any progress to this?

Opened a topic in Zammad Forums nonetheless.

**Comment by MrGeneration** [comment]
![image](https://user-images.githubusercontent.com/6549061/204108841-ca72b314-f681-48d6-8cdd-53354b8b8368.png)
 Guess not.
We're not providing any ETAs sorry.

You're asking for "how to delete xyz", that definitely is a technical question.
I'm sorry but I won't argue further with you.

**Comment by Nobsadmin** [comment]
I'm sorry, also not trying to argue.  
Will refrain from commenting further on this topic. 
Thank you for your help until this point. 

SOLVED after waiting for an ungodly amount of time. 
Editing in SQL is the solutions to user created Priorities
