### ISSUE TITLE
Checked Checkboxes in dark mode hard to see

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#4396]
### Infos:

* Used Zammad version: 5.3.0
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04
* Browser + version: Microsoft Edge 107

I hope it is ot reported. I can't find an issue here because here a report:

### Expected behavior:
I can see the checked checkboxes in dark mode

### Actual behavior:
The checked checkboxes are hard to see in dark mode. Only the border is visible.
![image](https://user-images.githubusercontent.com/1473674/204096092-ebf59917-699e-4304-89ef-b35ece4e5f8c.png)

### Steps to reproduce the behavior:
Check a checkbox in dark mode with Edge 107

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I'm afraid I'm unable to verify this on neither Firefox nor Edge within dark mode.
Possibly a caching issue.

![image](https://user-images.githubusercontent.com/6549061/204099152-280f91bc-4fad-4bd6-9ecf-5dc7d4bb906c.png)
