### ISSUE TITLE
Unexpected create ticket form behaviour in agent interface if phone switch is off

### ISSUE THREAD

**Issue by dizdi** [zammad/zammad#4397]
### Infos:

* Used Zammad version: 5.3.0
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04
* Database + version: PostgreSQL
* Elasticsearch version: 7.17.7
* Browser + version: Edge current

### Expected behavior:

* When the phone switch is turned off, no ticket form is displayed automatically, when the agent answers a call on his phone. 

### Actual behavior:

* A ticket form is created regardless the phone switch - as soon the agent answers a call.
![image](https://user-images.githubusercontent.com/23087749/204229979-4ae77fee-8fb4-4c3f-b21b-c52b9ecbcabe.png)

### Steps to reproduce the behavior:

* setup CTI (generic) 
* map phone number to agent
* disable phone in agnet interface
* call the agent
* answer the call
* a ticket form will be created automatically 

I honestly think, that this is a bug and no feature request or a general question.

**Comment by fliebe92** [comment]
Hello @dizdi and thanks for your report.

Could you please be more specific about the `disable phone in agent interface` step in your reproduction steps? What exactly are you doing?

Thanks for your collaboration. 🙏

**Comment by dizdi** [comment]
Hi @fliebe92! If you look at the screenshot there is a switch next to "Telefon". This is what i meant with disable phone in agent interface. My understanding is that if this switch is off, there should not be any actions that are triggered through an incoming call. Currently a new ticket form is triggered regardsless of the state of this switch.

**Comment by fliebe92** [comment]
Hey @dizdi and thanks for your quick response!

I have to ask another question because currently, I am not able to test it locally:

The switch is set to "off" and you're still receiving the call as shown in the following screenshot (please open it): https://user-docs.zammad.org/en/latest/_images/call-entries.png

Or is it not shown as in the screenshot, but you're answering the call anyhow and are getting navigated to the ticket create screen?

Thanks again for your support, it's really appreciated! 👍

**Comment by dizdi** [comment]
Hi @fliebe92  - I appreciate your readyness to handle this request - thank YOU! 

![image](https://user-images.githubusercontent.com/23087749/206292369-5ecad465-8fa2-46e6-ad4a-027748b3f1cf.png)

You see, the badge is visible and the call is "ringing"/"läutet". After the call is answered (in Teams in my case) the ticket form is opened. 

![image](https://user-images.githubusercontent.com/23087749/206293064-ec7b372c-5da9-4a95-ae41-6c48df7f3c6c.png)

That's the state in the call log: 

![image](https://user-images.githubusercontent.com/23087749/206293490-0fe2b471-4723-41cf-807f-8abfbc3bea8f.png)

I don't know how it should be, but in my opinion it's currently not logical. 🤷‍♂️

**Comment by MrGeneration** [comment]
I'm afraid that this is a technical question.
The button on phone does enable notifications and has no affect in the cti functionality at all, this is a global administrative behavior.

It's very inidirectly described in the documentation ( https://user-docs.zammad.org/en/latest/extras/caller-log.html ).
Actually only below a screenshot, one could work that out better in the future.

![image](https://user-images.githubusercontent.com/6549061/206297492-264d4f2e-726c-4ebd-ba93-1d7ca63e90e1.png)
