### ISSUE TITLE
Debian Package nginx 502 Bad Gateway

### ISSUE THREAD

**Issue by tniebergall** [zammad/zammad#440]
I‘ve installed zammad on an clean Debian 8 like descripted in the doc (https://docs.zammad.org/en/latest/install-debian.html) 

Afterwards I changed the nginx server_name like descripbed 
`Add your FQDN to servername directive in /etc/nginx/sites-enabled/zammad.conf and restart nginx if you're not testing localy
or open http://localhost in your browser to start using Zammad.`

After restarting nginx the entered FQDN replys with an error 502

The following could be found in the zamad.error.log
`2016/11/18 00:13:17 [error] 14770#0: *14 connect() failed (111: Connection refused) while connecting to upstream, client: [IP], server: [FQDN], request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "[FQDN]"
2016/11/18 00:13:17 [error] 14770#0: *14 connect() failed (111: Connection refused) while connecting to upstream, client: [IP], server: [FQDN], request: "GET / HTTP/1.1", upstream: "http://[::1]:3000/", host: "[FQDN]"`

**Comment by monotek** [comment]
Would you mind to test the current development branch package?

https://packager.io/gh/zammad/zammad/install?bid=1288#debian-8-zammad

**Comment by symptog** [comment]
@tniebergall have a look into `/var/log/syslog`. Is there anything suspicious?

maybe referred to #415?

**Comment by tniebergall** [comment]
@monotek the dev branch works fine.

**Comment by monotek** [comment]
Yes, i guess that was the problem.
When next stable is released you can switch from develop to stable branch again...

**Comment by jenshavelberg** [comment]
i have the same problem in build zammad*=1.3.0-1484665009.303db3e.jessie

`2017/01/17 22:04:15 [error] 431#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: [IP], server: [FQDN], request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: [FQDN]`

Any issues known? Thanks a lot!
