### ISSUE TITLE
Clicking on the name of a user on an incoming call does not open user information

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#4401]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* This has been found by the community: https://community.zammad.org/t/mouse-cursor-on-phone-entries-seems-not-right/10387/2

### Expected behavior:

When you hover over the name of a user on an incoming call, the mouse arrow changes to the point finger, and changes back to the arrow when you hover over the initials as shown in the screencast.

The expected behavior is that you can click on the username to open the user information.

### Actual behavior:

You have to click on the Initials instead of the name to open the user information, which is confusing since the mouse pointer changes back to an arrow and leaves an impression that you can't click on the initials

### Steps to reproduce the behavior:

- A user has to call in 
- just hover over the name and the initials during the time the user is calling, liked described in the following screencast: 
[Screen Recording (30.11.2022 15-21-10).wmv.zip](https://github.com/zammad/zammad/files/10124127/Screen.Recording.30.11.2022.15-21-10.wmv.zip)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
@mantas just as site node. On the other test avatars are implemented with span (not `<a href`), see https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/views/avatar.jst.eco

My proposal is to use always the same.
