### ISSUE TITLE
Alphabetical listing of the user-defined object list does not list the tickets correctly

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4409]
### Used Zammad Version

5.2.3

### Environment

- Installation method: [e.g. source, package] - any
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]- any
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3] - any
- Elasticsearch version: [e.g. 7.17] - any
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] - Version 107.0.1418.62 (official build) (64-Bit)

### Actual behaviour

The alphabetical order of the objects gets mixed up, either the first and the second sub-object are not arranged correctly or the last two (they are displayed as 2, 1, 3, 4 or 1,2,4,3), although the list is correctly displayed in the ticket right sidebar.

### Expected behaviour

After creating the custom object and several sub-objects, the tickets marked with a specific object are listed alphabetically, depending on which sub-object was selected 

![Test 1](https://user-images.githubusercontent.com/101350124/205330275-0c21a27f-e2d1-4342-8b2b-3ac2aad8eda6.jpg)

### Steps to reproduce the behaviour

Create a custom object with 4 different subobjects, the object must be configured as a "single selection field", the custom sort option is not activated, create an overview with the following settings: Sort by escalation, Group by group (tickets can also be in one or more groups). The final result will look like this: 

![Test 1](https://user-images.githubusercontent.com/101350124/205333884-60f2b1bf-3bb2-4bbc-b311-2954b3420b84.jpg)

![Test2](https://user-images.githubusercontent.com/101350124/205333917-b0b3b870-531f-4e51-b31f-a27df17071b5.jpg)

### Support Ticket

Ticket#10115309

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mantas** [comment]
This is easy to solve in current desktop view. But it's more complicated in NewTechStack with GraphQL.

Complex sorting in SQL is complicated. However, it could be solved after MySQL is gone. PostgreSQL supports sorting via proxy array.
