### ISSUE TITLE
Unable to execute more then one trigger (e. g. adding 2 tags with 2 triggers) at one ticket at same update cycle

### ISSUE THREAD

**Issue by martini** [zammad/zammad#441]
```
E, [2016-11-18T02:26:18.600647 #24116] ERROR -- : ERROR: #<ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "created_by_id" violates not-null constraint
DETAIL:  Failing row contains (27, 25, 1, 37, null, 2016-11-18 01:26:18.59265, 2016-11-18 01:26:18.592).
: INSERT INTO "tags" ("tag_object_id", "tag_item_id", "o_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id">
````

**Comment by martini** [comment]
Fixed in develop and 1.0, 1.1 https://github.com/zammad/zammad/commit/f601553f6d8a2c33c232be20504bfaf868338871.

**Comment by jacotec** [comment]
Hi @martini,

... and again: What about "master"? ;-)

We already had this before, and a clear statement would be nice: Is "master" still maintained? Any reason something goes beside "Develop" straight into 1.0 without being in the "master" build?

**Comment by martini** [comment]
@jacotec master is maintained. We just have issue with our test env. pls stay tuned.

**Comment by martini** [comment]
JFI: master is  up to date again
