### ISSUE TITLE
SAML: Support of custom attribute in name identifier

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#4411]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Actual Behaviour:
As an admin, I cannot configure a user-specific attribute to uniquely identify the configured users.

Currently, always the name identifier returned by the IdP is used and on our side, the email address is expected.

### Desired Behaviour:
As an admin, I would like to store a user-specific attribute in the SAML configuration mask for the unique identification of the users, which is also used in the further process.

As an agent, I'm identified (and linked when activated) with the configured name identifier custom attribute.

**Comment by fliebe92** [comment]
To do:

* Improve the current form for SAML configuration
* Extend the Docker container
* Improve the backend to use configured attribute ( `uid_attribute` for OmniAuth gem)
* Testing

**Comment by MrGeneration** [comment]
Please also make sure that this addition *does not* break existing configurations.
Thus it makes these kind of things technical optional and not required.
