### ISSUE TITLE
New feature "Public Links" is not following Zammad "ui-principals"

### ISSUE THREAD

**Issue by amirburi** [zammad/zammad#4418]
### Used Zammad Version

5.3

### Environment

- Installation method: hosted
- Operating system (if you're unsure: `cat /etc/os-release` ): zammad.com
- Database + version: unknown
- Elasticsearch version: unknown
- Browser + version: chrome 107

### Actual behaviour

New "Public Links" feature does not follow Zammad UI-principles.

The new "Public Links" function is placed in the "Manage" section ("Manage" means "management of business objects" like user, groups, overviews, trigger  and so on).

However, the "Public Links" section does not manage business objects but affects the appearance of the login/signup/lost password page.

<img width="1057" alt="Screenshot 2022-12-06 at 20 33 38" src="https://user-images.githubusercontent.com/100340766/206009328-b45c26df-662a-4364-b9fb-3a241a470dcc.png">

### Expected behaviour

There is one area in which the new function "Public Links" would be correctly sorted (expected) from my point of view. This is Admin :: Settings :: Branding. Here there are already settings for the login page and other appearance settings.

So I would expect it as the following:

<img width="1055" alt="Screenshot 2022-12-06 at 20 36 38" src="https://user-images.githubusercontent.com/100340766/206009158-912dbbe1-1e53-4944-a223-5d5e602366bf.png">

<img width="1055" alt="Screenshot 2022-12-06 at 20 36 38-2" src="https://user-images.githubusercontent.com/100340766/206008428-b1f95004-7dc4-440b-b014-43bbd8ee6d25.png">

### Steps to reproduce the behaviour

* setup a new Zammad 5.3
* go to admin interface

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
