### ISSUE TITLE
When pasting in Firefox (FF), the content is always inserted in a new line.

### ISSUE THREAD

**Issue by martini** [zammad/zammad#4424]
### Used Zammad Version

5.3 - 2022-12-09

### Environment

- Installation method: [e.g. source, package] zammad.com
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: firefox 105 on Mac & Linux

### Actual behaviour

Pasting in a word/string is always inserting a new line too.

### Expected behaviour

Pasting in a word/string should always be in the same line

### Steps to reproduce the behaviour

![postin_into_ff](https://user-images.githubusercontent.com/110226/206675531-e0877861-eb74-4925-85ea-6efb5bda36ec.gif)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Also affects Firefox on Windows, just in case someone wonders. :)

**Comment by dominikklein** [comment]
Is it maybe not a duplicate from https://github.com/zammad/zammad/issues/4330?

**Comment by MrGeneration** [comment]
indeed is.
