### ISSUE TITLE
Some Overview table content is not aligned correctly in RTL languages

### ISSUE THREAD

**Issue by YosefAdPro** [zammad/zammad#4429]
### Used Zammad Version

5.3

### Environment

- Installation method: [e.g. source, package] package
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]  windown
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] chrome  last

### Actual behaviour

Some of the headings in Overviews are attached to the left in RTL language
In this example we are talking about fields created in / Updated in
![image](https://user-images.githubusercontent.com/11810187/207846949-ca2ad965-b940-4b40-b7af-f752f7de03b0.png)

### Expected behaviour

Align to the right
![image](https://user-images.githubusercontent.com/11810187/207847134-0c13fe7b-365b-465c-bebb-cd618d0caba5.png)

### Steps to reproduce the behaviour

Create Overviews with the created in / Updated in fields

![image](https://user-images.githubusercontent.com/11810187/207847734-1389407b-9411-496b-b1e7-b69880c1c6e3.png)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mantas** [comment]
The table header for those 2 columns is trailing-aligned (right on LTR, left on RTL) on both RTL and LTR locales. But content is always right-aligned, which looks broken in RTL locales.

![Screenshot 2023-08-15 at 00 55 02](https://github.com/zammad/zammad/assets/36944/858421cd-f5bd-44a3-93de-5646d3d71a26)

![Screenshot 2023-08-15 at 00 55 18](https://github.com/zammad/zammad/assets/36944/358e22a5-58e8-44ff-b8b0-28150b242ac3)

I see 2 alternative ways to fix this. On one hand, content could be fixed to be trailing-aligned. On the other hand, maybe we should drop this exception? It looks okay-ish when it one column at the end of the table. But it looks strange when both `created_at` and `updated_at` are shown. Or, even worse, when a custom attribute happens to be the last column. Custom datetime attributes are not traling-aligned either.
