### ISSUE TITLE
Improve UI for the Exchange OAuth configuration

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#4435]
This is an enhancement for this existing feature-request:
https://github.com/zammad/zammad/issues/3971

### Actual behaviour

the interface is unclear for the admin who makes the settings for this.
It looks different from the previously used interfaces they are used to (i.e. M365) and the settings have to be done differently. 

### Expected behaviour

As an admin, I want to intuitively understand what I can set and what the settings are for. For me it is helpful if I can guide myself as much as possible by a common thread to make the settings.

The UI should fit into the general appearance and be structured in a way that is familiar.

**Comment by dominikklein** [comment]
I think we need first to check the idea behind the first implementation and then specify a solution. At the moment we have here a kind of special situation, because of the different authentication possibilities, compared to the other integrations.

**Comment by fliebe92** [comment]
### Idea

We are going to restore the initial look & feel of the Exchange integration, meaning that there are no tabs shown. The content of the `OAuth` tab is moved to the main page and we are showing a selector to define the authentication method that should be used.

For `Basic authentication`, nothing is changed. The wizard could be used as-is.

If `OAuth` is selected, we are displaying all the needed information and buttons for setting up Exchange. The `Configure` button for the Exchange integration is inactive until we have all the token information that is needed. Afterward, the wizard could be used as-is.

### Mockup

![image](https://user-images.githubusercontent.com/8327427/212656388-ca6a5e60-f89c-45f9-afa3-b28712a9c509.png)
