### ISSUE TITLE
timezone_default stays unset if you're spawning Zammad via auto_wizard.json

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4436]
### Used Zammad Version

5.3

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: Verified von Google Chrome (shouldn't matter)

### Actual behaviour

If you initialize Zammad via autowizard file and then open the URL with it's token, Zammad does not populate `timezone_default`.
This results in Zammad spamming `WARN -- : Setting "timezone_default" is empty. Using UTC instead. Please set system timezone.` with every step an agent (and possibly customer as well) takes.

This does not happen, if you initialize Zammad via Getting Started wizard normally.

### Expected behaviour

Zammad populates `timezone_default` upon the first initialization no matter if you do so manually via getting started wizard or auto wizard file.

### Steps to reproduce the behaviour

- create an auto wizard file
- initialize Zammad via said file
- check log outputs / `timezone_default` setting

### Support Ticket

/mh

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Maybe a regression/side effect of https://github.com/zammad/zammad/commit/56bc08be449f87c5ebcd2e4dc44dc2d903accdeb

**Comment by martini** [comment]
This is correct, the deleted file has the task to ensure to set `timezone_default` if it is not set. So it makes not sense to drop this file, it's needed. It affects all new Zammad instances and all instances where `timezone_default` is not set (e. g. updated systems).
