### ISSUE TITLE
DataPrivacy tasks never are cleaned up

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4437]
### Used Zammad Version

5.3; 5.x; 4.x

### Environment

- Installation method: [any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Zammad never forgets about the data privacy tasks admins added.
This may lead into extremely huge views causing possible performance degrade in the affected UI part.

Also this kind of means data hoarding - should behave similar to other data potions:
https://docs.zammad.org/en/latest/appendix/privacy.html

### Expected behaviour

Zammad cleans up data privacy tasks on a regular basis. Like 6 months and older or so.

### Steps to reproduce the behaviour

Create data privacy tasks, let them run and come back after years.

![image](https://user-images.githubusercontent.com/6549061/208648717-2c0fdf10-5f1e-4ac4-b0ce-e2ce9d32177c.png)

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by KoJie** [comment]
Since deleting data should always be done with great caution, I think 6 months is too short here. Customer projects often last longer than half a year, which means you still need the chance to have a look where tickets are. Therefore this time frame seems a bit too short to me. Suggestion: 12 months.

**Comment by YetAnotherGerrit** [comment]
Can this be enabled/disabled or can the timeframe be configured?

**Comment by rolfschmidt** [comment]
No, it is not configurable. But you could create a cronjob or run it manually if you would need it more often.

**Comment by rolfschmidt** [comment]
No, but you could create a cronjob or run it manually if you want to run it more often.

`zammad run rails r "DataPrivacyTask.cleanup(1.month)"` 

This command would clean up tasks created older than 1 month if you run it daily via cronjob.

**Comment by YetAnotherGerrit** [comment]
Oh, that's nifty. Thank you for the feedback.

Is there also a solution for clients that want to have the data for more than 12 months, for example for 5 years?

**Comment by rolfschmidt** [comment]
Not really. You could completely disable it:

`Scheduler.find_by(method: 'DataPrivacyTask.cleanup').update(active: false)`

**Comment by rolfschmidt** [comment]
Alternatively, if these requirements often come to you, then it might make sense to think about a setting to configure it in the core.

**Comment by MrGeneration** [comment]
> Not really. You could completely disable it:
> 
> Scheduler.find_by(method: 'DataPrivacyTask.cleanup').update(active: false)

Please don't this. This is not a recommended action and shouldn't be a a recommendation at all.

**Comment by YetAnotherGerrit** [comment]
Without a setting (which is "off" per default), I personally consider this a breaking change. With this update, we will destroy client data, that may be needed by some of them. And as the whole function may be relevant in legal cases, we should reconsider activating this per default.

**Comment by MrGeneration** [comment]
This scheduler task is about old dataprivacy tasks **after** they deleted data.
Imho technically the old ticket numbers don't help you too much as you don't know who the obscured user is anyway.

I don't see any legal issues at this point.
Feel free to contact me directory on this Gerrit, I believe this is a missunderstanding.
