### ISSUE TITLE
OTRS Import is not using (agent&customer) article creator information

### ISSUE THREAD

**Issue by martini** [zammad/zammad#4438]
### Used Zammad Version

5.3

### Environment

- Installation method: hosted
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Take over article creator form OTRS to Zammad (for both, customer & agent)

### Expected behaviour

Article creator in Zammad is always nobody.

### Steps to reproduce the behaviour

* Import data from OTRS 6.0.25 
* verify article creator in Zammad - it's always Zammad an not the actual agent

[ticket.txt](https://github.com/zammad/zammad/files/10267978/ticket.txt)

### I'm sure this is a bug and no feature request or a general question.

Yes

**Comment by dominikklein** [comment]
Is the same situation as for the Create-Time/Change-Time. Here the problem exists because the article backend in OTRS was refactored from OTRS 5 (CreatedBy, ChangedBy) -> OTRS 6 (CreateBy, ChangeBy).
During the fix, we need to keep in mind that it needs still be working for the OTRS versions lower than 6.

**Comment by martini** [comment]
In addition, OTRS uses `user_id` created by a customer. Here we used  `https://github.com/zammad/zammad/blob/develop/lib/import/otrs/article_customer.rb` to get the actual customer user id to fix it and to show the correct  user on customer articles. This is also not working anymore and need to be fixed.

**Comment by martini** [comment]
JFI: I tried to fix the broken data on a instance. Unfortunately it was not possible. So I do not recommend migrating OTRS until this issue is resolved.
