### ISSUE TITLE
Multiselect field defaults to nil instead of []

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#4442]
### Used Zammad Version

5.3

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

  - Ticket with no options selected has `nil` as multiselect field value

### Expected behaviour

- Ticket with no options selected has `[]` as multiselect field value

### Steps to reproduce the behaviour

- create multiselect custom object attribute
- create a Ticket and don't select any options in multiselect
- Ticket is saved with `multiselect: nil`

Note: If Ticket is created by parsing email or in command line, it will set `multiselect: []` correctly.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Maybe we need to clarify the best behavior also related to CoreWorkflow.

**Comment by mantas** [comment]
I doubt this is related to CoreWorkflow.

I tested CoreWorkflow behaviour with multiselect fields and it works just fine wether it is `nil` or empty array.

**Comment by rolfschmidt** [comment]
relates https://github.com/zammad/zammad/issues/944

**Comment by mantas** [comment]
@rolfschmidt #944 or #3944?
