### ISSUE TITLE
Zammad 5.3.1 patch (and security) upgrade needs Redis >=7.0.0

### ISSUE THREAD

**Issue by mookie-** [zammad/zammad#4443]
### Used Zammad Version

5.3.1

### Environment

- Installation method: Docker
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 20.04
- Database + version:  Redis 5.0.7-2ubuntu0.1
- Elasticsearch version: not important
- Browser + version: not important

### Actual behaviour

Zammad crashes with a `Redis::CommandError`:

```
start initialising
initialising / updating database...
I, [2022-12-21T18:38:44.832236 #18-8280]  INFO -- : Using Zammad's file store as Rails cache store.
I, [2022-12-21T18:38:44.832532 #18-8280]  INFO -- : Using Redis as web socket session store.
rake aborted!
Redis::CommandError: ERR wrong number of arguments for 'expire' command
/usr/local/bundle/gems/redis-4.8.0/lib/redis/client.rb:162:in `call'
/usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:270:in `block in send_command'
/usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:269:in `synchronize'
/usr/local/bundle/gems/redis-4.8.0/lib/redis.rb:269:in `send_command'
/usr/local/bundle/gems/redis-4.8.0/lib/redis/commands/keys.rb:85:in `expire'
/opt/zammad/lib/sessions/store/redis.rb:63:in `send_data'
/opt/zammad/lib/sessions.rb:221:in `send'
/opt/zammad/lib/sessions.rb:297:in `block in broadcast'
/opt/zammad/lib/sessions.rb:286:in `each'
/opt/zammad/lib/sessions.rb:286:in `broadcast'
/opt/zammad/app/models/setting.rb:199:in `check_broadcast'
/usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
/usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `block in invoke_after'
/usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `each'
/usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `invoke_after'
/usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:107:in `run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:824:in `_run_update_callbacks'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/callbacks.rb:465:in `_update_record'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/timestamp.rb:121:in `_update_record'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/persistence.rb:900:in `create_or_update'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/callbacks.rb:457:in `block in create_or_update'
/usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/callbacks.rb:457:in `create_or_update'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/timestamp.rb:126:in `create_or_update'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/persistence.rb:507:in `save!'
/usr/local/bundle/gems/activerecord-6.1.7/lib/active_record/validations.rb:53:in `save!'
[...]
```

### Expected behaviour

Zammad should not crash.

### Steps to reproduce the behaviour

In this [commit](https://github.com/zammad/zammad/commit/50103cfddb06bd4c9d57c4948a155e4209a898ef) you've added the following code:

```
@redis.expire(key, 1.hour, nx: true)
```

Unfortunately Redis Expire only supports `nx` since version 7.0.0 (see [redis documentation](https://redis.io/commands/expire/)).

Your supported Ubuntu Versions for example [don't come with Redis >= 7](https://packages.ubuntu.com/search?keywords=redis-server&searchon=names&exact=1&suite=all&section=all).

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@mgruner can you check this?

**Comment by b90g** [comment]
5.3.0 nigthly package builds in debian were also affected.  `expire` called something NX or so and then a lot of things fail

**Comment by mgruner** [comment]
Thanks for the report and sorry for the trouble. Solved by not using `nx` any more.

**Comment by mookie-** [comment]
Hello @mgruner, I'm sorry for reopening it. But I have a small suggestion.

Zammad 5.3.1 was released as security release but broke existing installations due to the issue here.
Until now (more than a month later), there is no new release (e.g. 5.3.2). So until now I couldn't upgrade and fix the security issue without doing one of the following:

* Upgrade the Redis version (to a version which isn't included in my current Ubuntu version)
* Upgrade to a nightly Zammad Version (which I would like to not do in production)
* Manually apply your commit to the Zammad application

It's ok for me now, but I think it would be nice in the future to push a new release soon if a regression happens with a security release.

**Comment by MrGeneration** [comment]
Redis is not a hard requirement unless you're using docker, you could also temporary not use Redis.

**Comment by mgruner** [comment]
@mookie- thank your for your follow-up. If you use the package based installation method, you can just update your system and you will get the latest version of the `stable` branch, which is considered safe in Zammad context. Of course, people sometimes make mistakes, but then we also correct them.
If you have a source archive based installation, I recommend to use https://ftp.zammad.com/zammad-latest.tar.gz. This was recently changed to always contain the same state as the package based installations, the latest commit of the `stable` branch, which is what should get used in production.
The patch level releases are actually just there to be able to create an announcement together with a security advisory. Not to signal that there is a new release available which is more stable than the current state of the `stable` branch. HTH.
