### ISSUE TITLE
Background scheduler jobs dying due to segmentation faults

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad#4451]
### Used Zammad Version

5.3

### Environment

- Installation method: any
- Operating system: debian 10 (most likely any though)
- Database + version: pgsql 11.17 (most likely any though)
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

We are seeing an unusually high number of dying scheduler jobs due to segmentation faults in the hosted environment.

### Expected behaviour

Background scheduler jobs should not be dying due to segmentation faults.

### Steps to reproduce the behaviour

_unknown_

Tracebacks from affected instances:
- [short-traceback.txt](https://github.com/zammad/zammad/files/10336240/short-traceback.txt)
- [scheduler_err.log](https://github.com/zammad/zammad/files/10336241/scheduler_err.log)

What we know so far:
- Memory and specific hosts don't seem to be the problem.
- The database server was up and not updated according to monitoring.
- The only common pattern is it happens in gems with native extensions.
- There were no updates of system libraries and all APNs have the exact same configuration.
- An idea was to try to rebuild all gems on at least one of affected hosts, but this was not done due to possible errors and downtimes for affected instances. In any case, the underlying system libraries were not updated.
- There are reasons to believe this only happens on heavy loaded instances (systems with many agents and high workload).

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by t-shehab** [comment]
We suspect a hardware error at the moment, which has since been resolved.

Closing for now.
