### ISSUE TITLE
Mail processing not possible if reply-to header is faulty

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4452]
### Used Zammad Version

5.3 / stable

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Zammad cannot process emails that contain invalid email addresses.
While this is working as designed, this also affects reply-to headers.

There is a special kind of experts (some Outlook users are affected too) do set a reply-to header but without mail address like so:
```
Reply-To: "Jane Doe"
Reply-To: John Doe
```

By default mails containing one of the above line will cause Zammad to not import mails but instead write them to local storage.
I thus suggest to ignore faulty reply to headers if the "from" address does fit.

This may also be relevant for contact form based mails were spammers decide to use RFC invalid mail addresses. This may be PM relevant however.

### Expected behaviour

Zammad ignores invalid reply-to headers and imports the mail.

### Steps to reproduce the behaviour

- Set `postmaster_sender_based_on_reply_to` in the needed state (`Setting.set('postmaster_sender_based_on_reply_to', 'as_sender_of_email')`
- send a email to Zammad with set reply-to header which is incomplete (missing email address)

### Support Ticket

Ticket#10135767

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Only as a side note, when we touch this. Here were already some improvements for the reply-to header value: https://github.com/zammad/zammad/issues/3867
