### ISSUE TITLE
Elasticsearch install gives error at "rake searchindex:rebuild # drop/create/reload"

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#446]
I've installed elasticsearch 2.4.x exactly following the documentation on https://docs.zammad.org/en/latest/install-elasticsearch.html#install-elasticsearch-and-its-attachment-plugin

ES is running on the same machine as Zammad. Port 9200 is listening (checked with netstat).

However, the rebuilding of the search index gives me that output:

> [zammad@mail ~]$ zammad run rake searchindex:rebuild # drop/create/reload
> drop indexes...
> create indexes...
> rake aborted!
> Unable to process PUT at http://127.0.0.1:9200/zammad_production
> #<UserAgent::Result:0x007f1ea8c44640 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:9200 (Connection refused - connect(2) for \"127.0.0.1\" port 9200)>">
> /opt/zammad/lib/search_index_backend.rb:62:in `index'
> /opt/zammad/lib/tasks/search_index_es.rake:19:in `block (2 levels) in <top (required)>'
> /opt/zammad/lib/tasks/search_index_es.rake:60:in `block (2 levels) in <top (required)>'
> /opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
> Tasks: TOP => searchindex:rebuild
> (See full trace by running task with --trace)

Reading here: http://stackoverflow.com/questions/31677563/connection-refused-error-on-elastic-search gave me the idea to change to connection to "localhost" instead of 127.0.0.1:

> zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"

But now I'm ending with a "bad request":

> [zammad@mail ~]$ zammad run rake searchindex:rebuild # drop/create/reload
> drop indexes...
> create indexes...
> rake aborted!
> Unable to process PUT at http://localhost:9200/zammad_production
> #<UserAgent::Result:0x007f19badd0330 @success=false, @body=nil, @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">
> /opt/zammad/lib/search_index_backend.rb:62:in `index'
> /opt/zammad/lib/tasks/search_index_es.rake:19:in `block (2 levels) in <top (required)>'
> /opt/zammad/lib/tasks/search_index_es.rake:60:in `block (2 levels) in <top (required)>'
> /opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
> Tasks: TOP => searchindex:rebuild
> (See full trace by running task with --trace)

So, following the doc the setup of Elasticsearch does not work ... any ideas?

**Comment by martini** [comment]
@jacotec did you install the "install mapper-attachments" and restart elasticsearch ?

**Comment by jacotec** [comment]
Hmmmm ... restart is a good point ☺️
Will check tonight.

**Comment by monotek** [comment]
Which OS?
On Debian 8 it works like this:

* apt-get install apt-transport-https sudo wget
* echo "deb http://ftp.debian.org/debian jessie-backports main" | sudo tee -a /etc/apt/sources.list.d/debian-backports.list
* echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
* wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
* apt-get update
* apt-get install openjdk-8-jre elasticsearch
* sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure
* cd /usr/share/elasticsearch 
* sudo bin/elasticsearch-plugin install mapper-attachments
* systemctl restart elasticsearch
* zammad run rails r "Setting.set('es_url', 'http://127.0.0.1:9200')"
* zammad run rake searchindex:rebuild

**Comment by monotek** [comment]
Did some rework in https://docs.zammad.org/en/latest/install-elasticsearch.html .

Tested docu with Centos 7, Debian 8 & Ubuntu 16.04.

Works without problems for me. 

Closing.

**Comment by jacotec** [comment]
@monotek @martini 
Great work, Andreas, good doc update!

But some additional 2 cents from my side:

1)
ES 5.x is a memory waster! Following the motto "Start with the latest stable version" it always blocked 50% of my whole memory. For what?
As a Seafile user I know ES ... Seafile comes with it and the search is fantastic. But no memory waste. So I've tried 2.4.1 - and here we go! 8.7% memory vs. 50% memory.
I can't recommend 5.x for now, it seems to have memory issues - I'd definitely recommend 2.4.1 for now (maybe worth a hint in the doc).

2)
With CentOS7 and 2.4.1 - that's what I'm using, the connection to 127.0.0.1:9200 does not work! See my post above.
Connecting to "localhost" instead and all is up and running:

> zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"

Maybe also worth a hint ... at least if someone gets this:

> [zammad@mail ~]$ zammad run rake searchindex:rebuild # drop/create/reload
> drop indexes...
> create indexes...
> rake aborted!
> Unable to process PUT at http://127.0.0.1:9200/zammad_production
> #<UserAgent::Result:0x007f1ea8c44640 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:9200 (Connection refused - connect(2) for "127.0.0.1" port 9200)>">

Connecting to "localhost" instead solves it.

**Comment by monotek** [comment]
Hmmm. I tried it today in centos 7. Did not had this issue. 127.0.0.1 Just worked.

**Comment by jacotec** [comment]
Also ES 2.4.1?

**Comment by monotek** [comment]
No. 5.0.

**Comment by furqanzamir** [comment]
Hi There is error when i open elastic search but it show proper in this link http://127.0.0.1:9200/zammad_production
when i open http://127.0.0.1:9200 its show this 
elastic build version etc
http://127.0.0.1:9200/zammad_production/Ticket/_search\n#\u003cUserAgent::Result:0x007fd4e1818400 @success=false, @body=nil, @data=nil, @code=\"400\", @content_type=nil, @error=\"Client Error: #\u003cNet::HTTPBadRequest 400 Bad Request readbody=true\u003e!\"\u003e"}

how to solve this issue

**Comment by thorsteneckel** [comment]
Hi @furqanzamir - first of all this is a really long closed issue. Please don't reply to those old issues. Additionally this is not a direct Zammad issue but probably a wrong Elasticsearch version. I suspect ES 6. Zammad only supports ES 5.6.
Future technical questions can get asked over at https://community.zammad.org/
