### ISSUE TITLE
Value "organization_id" is ignored in API

### ISSUE THREAD

**Issue by bogatkaj** [zammad/zammad#4464]
### Used Zammad Version

5.3.1

### Environment

- Installation method: docker-compose stack
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 20.04.3 LTS
- Database + version:  Postgres 15.1
- Elasticsearch version: 8.5.1
- Browser + version: Insomnia 2022.7.2 (API Dev-Tool)

### Actual behaviour

Organization_id still has value of the primary org of the user
```
{
	"id": 90,
	"group_id": 3,
	"priority_id": 2,
	"state_id": 2,
	"organization_id": 13,
	"number": "12345",
	"title": "Test Org_id",
	"owner_id": 1,
	"customer_id": 3,
	"note": null,
	"first_response_at": "2023-01-15T21:25:51.905Z",
	"first_response_escalation_at": null,
	"first_response_in_min": null,
	"first_response_diff_in_min": null,
	"close_at": null,
	"close_escalation_at": null,
	"close_in_min": null,
	"close_diff_in_min": null,
	"update_escalation_at": null,
	"update_in_min": null,
	"update_diff_in_min": null,
	"last_contact_at": "2023-01-15T21:25:51.905Z",
	"last_contact_agent_at": "2023-01-15T21:25:51.905Z",
	"last_contact_customer_at": null,
	"last_owner_update_at": "2023-01-15T21:25:51.974Z",
	"create_article_type_id": 1,
	"create_article_sender_id": 1,
	"article_count": 1,
	"escalation_at": null,
	"pending_time": null,
	"type": "",
	"time_unit": null,
	"preferences": {},
	"updated_by_id": 3,
	"created_by_id": 3,
	"created_at": "2023-01-15T21:25:51.811Z",
	"updated_at": "2023-01-15T21:25:52.080Z",
	"version": "",
	"betriebssystem": "",
	"last_close_at": null,
	"article_ids": [
		482,
		483
	],
	"ticket_time_accounting_ids": []
}
```

### Expected behaviour

Organization_id gets changed to 91 after the request, so the ticket is assigned to the secondary org of the user (for org ticket sharing)

### Steps to reproduce the behaviour

Run an update request on a ticket changing the organization_id as in the following example:

```
> PUT /api/v1/tickets/89 HTTP/2
> Host: zammad.foobar.tld
> user-agent: insomnia/2022.7.2
> content-type: application/json
> authorization: Token token=***SECRET***;
> accept: */*
> content-length: 26

* TLSv1.2 (OUT), TLS header, Supplemental data (23):

| {
| 	"organization_id": 91
| }
```

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Hi @bogatkaj 

for me it's working as expected, this seems to be a technical question for the API usage to me.

Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org/ .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
_If you're paying customer already, please consult your Zammad support for assistance! :-)_

**Comment by bogatkaj** [comment]
@dominikklein Well, for me it seems not to be a question, since it's simply not working as shown above.
Don't get me wrong, but I expect the value to change if I run a put request and get a status 200.

Also from your response I read that it works for you, so my first guess that it's simply impossioble to change the organization linked to a ticket seems to be wrong.
Could you may provide the request you send?
Is it simmilar to the one mentioned above?

Thanks in advance!

**Comment by bogatkaj** [comment]
@dominikklein Never mind I found the solution myself.

For everyone facing the same problem:

If you are testing, check that:

-  the Customer has set the correct secondary organization the moment you want to change the organization owning the ticket
   (Any organization not associated with the customer **won't work**)

- you surrounded the ID of the organization in quotes like:
```
{
	"organization_id": "82"
}
```

But IMHO I think the API should return an error if the value send over is a integer and not a string (missing quotes) or one tries to set an organization not associated with the customer...

**Comment by dominikklein** [comment]
Only as a side note, the "organization_id" value needs not to be in quotes, it's also working with an integer.
And for sure, you can not add any organization which is not related to the current customer user.
There is currently no error message because the fallback for this situation is that the update will use the primary organization id from the current customer user.

**Comment by bogatkaj** [comment]
Interesting, since the quotes did the trick for me.
Without then it didn't worked.

Am 23. Januar 2023 13:11:08 MEZ schrieb Dominik Klein ***@***.***>:

**Comment by Cestoid** [comment]
Hi, i also wanted to assign users to their organization automatically with using a _[sender e-mail contains "blabla" trigger]_. And i also figured it out **we just cant change the "organization_id"** with any kind of trigger or timer or anything. We only can switch into organization and secondary organization. 

**I would love to hear if you found a method to change the organization_id with a trigger or etcetera.**
