### ISSUE TITLE
Quoting articles with very big inline images crashes zammad

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4468]
### Used Zammad Version

5.3

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

If you quote an article with an inline image >250mb it will be saved temporarily in the taskbar which will block you from login and taking actions in zammad.

### Expected behaviour

You should be able to quote any article without consequences.

### Steps to reproduce the behaviour

- Open a ticket
- Download example image e.g. (https://effigis.com/en/solutions/satellite-images/satellite-image-samples/)
- Open image in paint and copy and paste it to article answer
- Now you have an inline image, wait for the taskbar to save.
- Session overload should be visible here `SessionHelper.json_hash(User.find(1)).to_s.size`

### Support Ticket

Ticket#10121498

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
I think it's not only about inline images from quoted articles, also when you upload a new inline image it will be saved in the taskbar as base64 or?

**Comment by rolfschmidt** [comment]
> I think it's not only about inline images from quoted articles, also when you upload a new inline image it will be saved in the taskbar as base64 or?


Yes, but it looks like that the browser is minimizing the damage because of auto resizing. But in general I think it does not matter. The problem is the same. I guess we need some way to directly convert stuff like this into this format:

```html
<img style="max-width:100%;width: 1004.8px;max-width: 100%;" src="/api/v1/ticket_attachment/7/6/8?view=inline">
```

instead of base64.

**Comment by dominikklein** [comment]
I was also thinking that the inline image handling is not the best at the moment (we have also a card for this in the new tech stack). We need only to keep in mind that outgoing communication (e.g. email) needs to be converted in the base64 again.

**Comment by MrGeneration** [comment]
Possibly moving out the fetch of the taskbar from the signin payload would at least improve the current situation too.
The browser of the customer received a 500MB (!) single response in JSON and the JS app completely locked up blocking the users login.

**Comment by dominikklein** [comment]
Yes, good idea as a "fast" solution, before we have the time to refactor/improve the inline image handling completley.

**Comment by dominikklein** [comment]
Should be solved with the new stack already (e.g. using inline images inside the ticket creation or reply), because we are no longer using base64 inside the content, instead we are using the upload cache in this situation.
