### ISSUE TITLE
"Warten auf Erinnerung" should be open after due date is reached

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#447]
Hi,

a ticket which is waiting for a reminder sends out an email when the reminder is due, gets orange in the overwiew - but is still "Warten auf Erinnerung".

Shouldn't this get automatically opened again so it's in the focus and the "open tickets" list then?

**Comment by martini** [comment]
Hi @jacotec 

"Pending reminder" (Warten auf Erinnerung) works as designed (we keep the state to still send "reminder / please work on it, it's x days overtime" messages or escalated it if nobody is working on it).

 -=> This behaviour is common.

Anyway: If you want to cover your assumed behaviour you can do this too (there is currently no interface for it, so I describe it hier).

Intro:
You can create as many ticket stats as you want. The Important thing on ticket states are the "state type". As state type we have:

- new
- open
- closed
- pending reminder (send reminder notifications if pending time has reached)
- pending action (set a new state after pending time has reached)
- merged
- removed

(see also "rails c" & "Ticket::StateType.all")

So per default "pending reminder" state is defined as (see seeds.rb):

```
Ticket::State.create_if_not_exists(
    name: 'pending reminder',
    state_type_id: Ticket::StateType.find_by(name: 'pending reminder').id,
    ignore_escalation: true,
)
```

It you want to change it to your behaviour try this via "rails c":

`
Ticket::State.create_or_update(
    name: 'pending reminder',
    state_type_id: Ticket::StateType.find_by(name: 'pending action').id,
    next_state_id: Ticket::State.find_by(name: 'open').id
    ignore_escalation: true,
)
`

This "next_state_id" and state type "pending action" means, this new state will be set after pending time has reached.
