### ISSUE TITLE
Group edit dialog shows ??? in email select box

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad#4475]
### Used Zammad Version

5.3.1-1674727814.691d3a63.bullseye

### Environment

- Installation method: package
- Operating system debian 11
- Database + version:  postgres 13.9
- Elasticsearch version: 8.6.1
- Browser + version: chrome 109.0.5414.119

### Actual behaviour

Admin - Editing Group shows questionmarks as Email Identifier in Email-Select.

![image](https://user-images.githubusercontent.com/4540135/215043562-02f212d7-b043-445e-ac67-05d23d92f722.png)

### Expected behaviour

Should show correct values!

### Steps to reproduce the behaviour

Got to edit Group.

### Support Ticket
Ticket#10122388

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by saz** [comment]
We're having the same issue with the latest source version from the `stable` branch.

**Comment by fliebe92** [comment]
Introduced by fixing https://github.com/zammad/zammad/issues/4329.
