### ISSUE TITLE
PDF attachments should not be opened without downloading them first

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#4479]
### Used Zammad Version

5.3.1

### Environment

- Installation method: any
- Operating system : any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: Safari 15.6.1 and other browsers if configured to open PDF attachments inside a browser tab
  - Remark about the browser: A workaround is configuring the browser to always download PDF attachments (if this setting is available in your browser), which makes the behavior consistent. 

### Actual behaviour

* If a PDF file has been added by an agent as an attachment to an article (regardless of the article type). 
* After the ticket is updated, when you click on the PDF attachment, it is opened directly in a new tab. 
* The same is true if a customer creates the article with PDF attachment via web. 

### Expected behaviour

* For security reasons, PDF files should always be downloaded first and subsequently opened according to your browsers' configuration (directly, without asking; with asking; in a new tab; in a dedicated application). 
* Zammad, on its part, should always force the download.

#### Technical Implementation

- Remove `application/pdf` from the default list in `config.active_storage.content_types_allowed_inline`.

### Steps to reproduce the behaviour

* Create a ticket as an agent, add a PDF attachment and update the ticket. 
* Alternatively, create a ticket as a customer via web, add a PDF attachment and update the ticket. 

* (Make sure your browser is not configured to force downloads of PDF files.) 
* Afterward, click on the attached PDF file to observe how the file is opened in a new tab without downloading it first. 

### Support Ticket

Ticket#10122569

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@cautopartes why are you thinking, PDFs should not be opened inline? Currently, we are using the "Rails" default behavior for allowed inline content types (`ActiveStorage.content_types_allowed_inline`).
I would say that we should fix the problem and align the situation that inline is always working for PDFs.
