### ISSUE TITLE
SMS Accounts: Not able to send or receive SMS

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#4487]
### Used Zammad Version

5.3.1

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

* Sending and receiving SMS with Twilio or Messagebird, set up in Admin > Channels > SMS > "SMS Accounts" (not "SMS Notification") does not work. 
* There are no error messages. There is simply no message coming in and thus no way to respond. Bear in mind that sending is only available to an agent after an SMS message has been received (See: https://github.com/zammad/zammad/issues/2854). 
* "SMS Notification" via Trigger, with the same account, is working fine. Triggers can send SMS messages. 
* I tested with a Messagebird account. A trial user reported the same for Twilio. 

### Expected behaviour

* It should be possible to send and receive SMS messages using Twilio or Messagebird, set up in Admin > Channels > SMS > "SMS Accounts". 

### Steps to reproduce the behaviour

* Set up an SMS provider like Twilio or Messagebird in Admin > Channels > SMS > "SMS Accounts". 
* Try receiving and sending SMS messages. 

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by martini** [comment]
@cautopartes question:

1) Receiving SMS: What is in the Twilio or Messagebird logs, is the message sent to the rest interface of Zammad?
 If yes: What is the related log in `log/production.log`
 If no: It's a config issue at Twilio or Messagebird.
 
 2) Sending SMS: There should be also a log at Twilio or Messagebird site. Can you see that Zammad tries to send a request to  Twilio or Messagebird?
  If yes: Why is Twilio or Messagebird the message not sending to customter?
  If no: Have a look to the `preferences` store of the related Ticket::Article - there should be some information about sending issues.

**Comment by rolfschmidt** [comment]
send and recieve works for twilio. test today: Ticket#10122962

**Comment by cautopartes** [comment]
Also confirmed with Messagebird. Configuration lesson noisily learned. Closing.
