### ISSUE TITLE
Docker image release 1.2.0

### ISSUE THREAD

**Issue by osixia** [zammad/zammad#449]
Hello,

I used docker to test zammad and it looks really promising. 
Hoever i can't get it works with my email server, but i saw that this issue may have been fixed in 1.1.0 release but only version 1.0.0 is available with docker.

It would be great to have a new docker image for each version released :)

Thanks

**Comment by monotek** [comment]
Try: 

https://hub.docker.com/r/monotek/zammad/

**Comment by olivergrahl** [comment]
Just tried the image above, but needed to 
```
rm -rf /etc/nginx/sites-enabled/default
service nginx restart
```
to make it work.

**Comment by monotek** [comment]
This should only be the case if you're trying to access zammad from somewhere else than localhost.

In this case edit /etc/nginx/zammad.conf and edit servername directive.  
After this restart nginx.

**Comment by thorsteneckel** [comment]
Is there anything to do here @monotek ?

**Comment by monotek** [comment]
Imho No. 

I just checked it in the develop and the stable version of the image.
I could access both just by opening http://localhost/ in the browser.

If somebody is interested in a docker-compose version with persistent storage of the develop branch, please try https://github.com/monotek/zammad-docker-compose

Closing...
