### ISSUE TITLE
Keyboard combination `Ctrl+Shift+...` doesn't work in Firefox

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#4492]
### Used Zammad Version

5.3.1

### Environment

- Installation method: docker-compose
- Operating system: Debian 11.6
- Database + version: PostgreSQL 15.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
- Elasticsearch version: 8.5.1
- Browser + version: Firefox 109.0.1

### Actual behaviour

Pressing Ctrl+Shift+... does nothing.

The following exception is logged in the browser console:

```
Uncaught TypeError: window.ClipboardItem is not a constructor
    callback https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:38
    n https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:38
    handler https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:20
    dispatch https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:2
    handle https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:2
    add https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:2
    j https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:1
    each https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:1
    each https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:1
    j https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:1
    on https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:2
    <anonymous> https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:10
    <anonymous> https://zammad.company.tld/assets/application-6d0d7e19c7a28b742274f927c2a4d0648cd49d7adb1bfdb49fb4b4e3e02ebb99.js:10
```

### Expected behaviour

Ctrl+Shift+... should copy object number, title and URL to the clipboard.

### Steps to reproduce the behaviour

- Run Zammad 5.3.1.
- Attempt to copy ticket ID, title and URL of a ticket by pressing Ctrl+Shift+...
- Notice that the clipboard remains unchanged and the above exception is logged to the browser console.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
I can't verify the empty clipboard part on my current Firefox (Win) using develop.
For me it still contructs the string as if I'd use two dots. The error message and missing link occurs to me as well though.

**Comment by martinvonwittich** [comment]
The cause is that Zammad uses the `ClipboardItem()` constructor:

https://github.com/zammad/zammad/blob/14ee74496d44b1f68197925ccfe22f4530021222/app/assets/javascripts/app/controllers/_plugin/keyboard_shortcuts.coffee#L293

This constructor is apparently gated behind a feature flag in Firefox and therefore doesn't work out-of-the-box in current versions: https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem/ClipboardItem#browser_compatibility

To work around the issue, users can open `about:config`, search for the option `dom.events.asyncClipboard.clipboardItem`, and set it to true.

**Comment by martinvonwittich** [comment]
> I can't verify the empty clipboard part on my current Firefox (Win) using develop. For me it still contructs the string as if I'd use two dots. The error message and missing link occurs to me as well though.

Try to "clean" your clipboard by copying a random string, and then attempt to reproduce the problem by only hitting Ctrl+Shift+..., without (accidentally) hitting Ctrl+Shift+.. beforehand. I'd guess you accidentally hit Ctrl+Shift+.. before and therefore don't notice that the Ctrl+Shift+... doesn't actually do anything.

**Comment by MrGeneration** [comment]
> Try to "clean" your clipboard by copying a random string, and then attempt to reproduce the problem by only hitting Ctrl+Shift+..., without (accidentally) hitting Ctrl+Shift+.. beforehand. I'd guess you accidentally hit Ctrl+Shift+.. before and therefore don't notice that the Ctrl+Shift+... doesn't actually do anything.

Doesn't change anything for me but doesn't mean it can't have variation in false behavior.

**Comment by martini** [comment]
JFI: I can reprocude this on firefox on mac current ESR `115.3.1esr (64-bit)` (with empty and filled clipboard).
