### ISSUE TITLE
Excel-Export in reporting exports only first 10 tickets

### ISSUE THREAD

**Issue by fyco97** [zammad/zammad#4493]
### Used Zammad Version

5.4.0

### Environment

- Installation method: apt install over repo: https://dl.packager.io/srv/deb/zammad/zammad/develop/ubuntu 20.04 InRelease
- Operating system: Ubuntu 20.04.5 LTS
- Database + version: MySql 8.0.32-0ubuntu0.20.04.2
- Elasticsearch version: 7.17.9
- Browser + version: any

### Actual behaviour

When exporting reports as .xlsx from Zammad, Zammad will export only first 10 tickets shown in preview.

![image](https://user-images.githubusercontent.com/125260231/218428228-534d3a07-f627-42ff-a91b-6c90e170d896.png)

By clicking DOWNLOAD xx RECORD(S) it only downloads first 10 tickets
![image](https://user-images.githubusercontent.com/125260231/218428928-954e9277-8aad-441d-9c78-0ef8cbf274d4.png)

### Expected behaviour

When exporting reports as .xlsx from Zammad, Zammad should export all tickets (more than 10 tickets in my case)

### Steps to reproduce the behaviour

1. Go to reporting
2. Select any profile (report profile not needed)
3. Navigate to Created/Closed/First Soulution etc. and download records (.xlsx file)
4. After downloading .xlsx file check how many tickets got exported

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
relates https://github.com/zammad/zammad/commit/4b3d5eb113dd0e8a70f816208369ee61a42b41af
