### ISSUE TITLE
Improve Taskbar watchers idle detection

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#4497]
### Used Zammad Version

5.3

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

- Taskbar watcher idle-ness is detected by making change

### Expected behaviour

- Taskbar watcher should become non-idle by opening a ticket as well.
- Taskbar watcher might be non-idle while his taskbar is active and in active browser tab. Possibly leveraging Page Visibility API

### Steps to reproduce the behaviour

- Open ticket with User A
- Open ticket with User B
- Wait for User A to get marked as idle, do not close taskbar
- Go to ticket with User A but make no changes
- User A is still shown as idle

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by YetAnotherGerrit** [comment]
We will rethink details like that with the new tech stack. So I will close this as "not something we will work on in the old tech stack".
