### ISSUE TITLE
Empty sections are shown in ticket zoom's sidebar if no data is available and agent has only read permissions

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4502]
### Used Zammad Version

5.3

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Empty sections are shown.

![image](https://user-images.githubusercontent.com/8327427/220881987-06388d35-0e5d-4a64-b1e6-772bd50c46e6.png)

### Expected behaviour

Empty sections should be hidden for a better UX.

### Steps to reproduce the behaviour

* Create a new agent that only has read permission in the `Users` group.
* Create a new ticket in the `Users` group and open the ticket zoom with the newly created agent.
* Have a look at the sidebar.

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by martini** [comment]
Strange. On develop it looks like this (screenshot is in german):

<img width="281" alt="Screenshot 2023-02-23 at 14 00 01" src="https://user-images.githubusercontent.com/110226/220913503-9ed460d6-f771-44b2-b127-613f5f17906f.png">

**Comment by fliebe92** [comment]
> Strange. On develop it looks like this (screenshot is in german):
> 
> <img alt="Screenshot 2023-02-23 at 14 00 01" width="281" src="https://user-images.githubusercontent.com/110226/220913503-9ed460d6-f771-44b2-b127-613f5f17906f.png">

I think the screenshot in the initial report is made by having read-only permission in a ticket, my fault.

**Comment by martini** [comment]
> I think the screenshot in the initial report is made by having read-only permission in a ticket, my fault.

With read-only permission I agree. Then the whole element can be hidden.

**Comment by YetAnotherGerrit** [comment]
We will not solve this issue in the current UI, but in the next UI instead.

**Comment by YetAnotherGerrit** [comment]
We will not solve this in the current UI, but with the next UI.
