### ISSUE TITLE
Improve S/MIME integration by adding meta information

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4503]
### Used Zammad Version

5.3

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

We are looping over all certificates to check if the recipients of a newly composed article
  a) have a certificate at all and
  b) if those certificates are still valid.

This is a reason why Zammad instances with a lot of S/MIME certificates are slow regarding creating new articles.

### Expected behaviour

During the upload of S/MIME certificates, we should not simply store the certificate as-is in the database. Instead, we should fetch meta information from the certificate and store the meta information as well as the certificate.

Required meta information is:
* Validity
* E-mail address
* Key usage

For easier checking in the front end, we should provide a new API endpoint to check multiple e-mail addresses at once and provide meaningful information, e.g.:
  * "E-mail address <address> has no certificate."
  * "The certificate for e-mail address <address> has expired."

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by mgruner** [comment]
Please see #4534. There is a `key usage` extension in openssl certificates that can restrict the usage of keys. If the current issue is going to be implemented, that needs to be considered as well as metadata.

**Comment by mnestor** [comment]
Do we need to reload certificates after updating?

**Comment by fliebe92** [comment]
Hey @mnestor.

> Do we need to reload certificates after updating?

There is a migration in place that takes care of already existing certificates. Manual reloading shouldn't be needed.
