### ISSUE TITLE
Disable expert mode for time accounting conditions

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4509]
### Used Zammad Version

5.4.x (develop)

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Currently, when the expert mode in the time accounting condition is used, the ticket update is stucked:

![Bildschirmfoto 2023-02-28 um 12 30 53](https://user-images.githubusercontent.com/5445094/221842143-5f14a4bc-6233-4719-a1e0-bcd6f21e826e.png)

### Expected behaviour

The expert mode should not be available for the time accounting conditions, because of limitations in the "live" data check in the background.

Technical Background:
There is a plan to add a generic solution for the "live" data check in the backend, but this will take some time for the specification to find a good solution.

### Steps to reproduce the behaviour

- Active time accounting and using the expert mode for the conditions.
- Try to trigger the time unit dialog during the ticket update (create an article and select the correct conditions).

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
This does affect documentation.
