### ISSUE TITLE
Show count of objects in API response headers

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#451]
It would be useful if a response contains the total count

e.g. _X-Total-Count_ Header

**Comment by martini** [comment]
Thank! For me, in context of pagination? Or also other use cases?

**Comment by MDXDave** [comment]
To show the total number of tickets without having to downloading or accessing each of them.

**Comment by thorsteneckel** [comment]
In my attempt of working on the API I used this gem: https://github.com/davidcelis/api-pagination

It basically does what @MDXDave requested - It puts these three information in the HTTP response headers:

- Total
- Per page
- Current page

👍

**Comment by MDXDave** [comment]
As new API version in addition to https://github.com/zammad/zammad/issues/241#issuecomment-256191975 ?

**Comment by skhomyuk** [comment]
Any updates regarding counting of records?

**Comment by MrGeneration** [comment]
There are news regarding this topic.
This is an enhancement that we will add, when we find time for it.

We're currently working hard on fixing bugs to improve Zammad further.

We'll update this issue accordingly, as soon as there are news for it.
I'm also limitting the conversation to reduce the noise as in `+1` and `any news??`.

Please don't get me wrong here, it helps us to focus.

**Comment by mgruner** [comment]
Hi @MDXDave, I'm sorry but our plans have changed. We introduced a new graphql API with the mobile view of Zammad 6.0. This will be the focus in future, when we will rewrite the desktop app of Zammad with the new tech stack and based on graphql. 

So right now there are no plans to extend the REST API with these fields. I'll close it as not planned for now.
