### ISSUE TITLE
Text marker removed in mail tickets

### ISSUE THREAD

**Issue by chris-010** [zammad/zammad#4514]
### Used Zammad Version

5.3.1

### Environment

- Installation method: Package
- Operating system: Debian 11
- Database + version:  MariaDB 10.5.18
- Elasticsearch version: 7.10.2
- Browser + version: Firefox 110.0

Ticket#10129946

### Actual behaviour

Text markings not shown in Zammad when a ticket was created from mail.

![grafik](https://user-images.githubusercontent.com/10660568/223059211-fc1c0764-a16a-4574-9412-a00e462a8763.png)

### Expected behaviour

Original mail content where 2nd line is marked with yellow background.

![grafik](https://user-images.githubusercontent.com/10660568/223059407-7de2e31e-07d5-4e04-b0ef-b604fd1045cb.png)

### Steps to reproduce the behaviour

- Open Outlook
- Create new Mail
- Write some text and mark it with a color
- Send mail to Zammad
- Previously marked text not marked anymore in Zammad

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hey @cklimbac and welcome to the Zammad repository!

First, we would like to say thanks for your report.

It might be of great help to us if you could provide a test mail that enables us to quickly verify the reported behavior. We would really appreciate your help here.

Thanks for your support. 👍

**Comment by chris-010** [comment]
Source code of reported example email attached.

[email.txt](https://github.com/zammad/zammad/files/10897181/email.txt)

**Comment by fliebe92** [comment]
Unfortunately, this looks like plain HTML and thus can't be imported easily. For a proper reproduction of this issue, could you please hand over the complete mail to us?

Just check my attached screenshot for how to get this file.

![Zammad Raw Mail](https://user-images.githubusercontent.com/8327427/223093153-99f53354-2a1c-4408-a28f-3cc91b0f67b6.png)

Thanks a lot!

**Comment by chris-010** [comment]
Now the full source of mail has been attached, only names and addresses anonymized.

[email_source.txt](https://github.com/zammad/zammad/files/10907502/email_source.txt)

**Comment by fliebe92** [comment]
This behavior is caused by https://github.com/zammad/zammad/blob/develop/config/initializers/html_sanitizer.rb#L61-L63.

@mantas @rolfschmidt: Gentlemen, what do you think? Was there a reason to not allow `background` CSS property for `span` tags?

**Comment by rolfschmidt** [comment]
Not sure, only Thorsten and @martini might know this. I could imagine that because most of the text is delivered in spans that it prevents weird looks if somebody mail format is containing a self-made template with a different background. 

It is interesting that is also not allowed for `div` and `p` but allowed for `table` which would match idea of clean background in general but allowing it for compact elements like tables.

I feel like we should introduce some kind of explanation for this stuff. It should be written down as a big code comment to explain what the goal of this handling is.

**Comment by MrGeneration** [comment]
I believe to remember that colored spans did actually break UI parts of Zammad at earlier points.
That should be the reason it's currently fished out.

Maybe we should have a clear limitation page on the doc that exactly states what is *not* fished out. That list should be shorter than what we actually do filter.

**Comment by fliebe92** [comment]
@martini: Any comments on this issue here?

**Comment by fliebe92** [comment]
Clarified with @martini, we should allow the `background` CSS property for `span` tags.
