### ISSUE TITLE
Zammad reply to own email will not have signature

### ISSUE THREAD

**Issue by kyong0129** [zammad/zammad#4517]
Infos:
Used Zammad version: 5.3.0
Used Zammad installation source: package
Operating system: Ubuntu 20.04.5
Browser + version: Chrome 110.0.5481.178 
Expected behavior:
When reply to email, it should have signature attached.

Actual behavior:
When we reply to our own email, there is no signature attached in the email textbox

**Comment by fliebe92** [comment]
Hello @kyong0129, could you please use our issue template to provide all the required information to be able to reproduce your reported issue? Thanks a lot. 👍

**Comment by kyong0129** [comment]
@fliebe92 Updated the template

**Comment by fliebe92** [comment]
> @fliebe92 Updated the template

It's still not correct, please have a look at https://github.com/zammad/zammad/issues/4516#issue-1615144253. The steps how to reproduce the issue are also missing. 🙈

**Comment by dominikklein** [comment]
Should be a duplicate from: https://github.com/zammad/zammad/issues/2319

**Comment by kyong0129** [comment]
@dominikklein Yes, but no update om the post

**Comment by MrGeneration** [comment]
We will update issues when they're moving in any direction. Bumping issues or even creating duplicate issues unfortunately doesn't help on speeding them up.
