### ISSUE TITLE
Alphabetical listing of organizations in admin area

### ISSUE THREAD

**Issue by BenjaminMarkus89** [zammad/zammad#4520]
### Used Zammad Version

5.3.1 

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

In: admin > manage > organizations. It's not possible to sort the names of the organizations alphabetically or reversed alphabetically via click on the column title. 
Additionally there is a graphical element (in chrome and safari), that insinuates the possibility of sorting.

<img width="818" alt="orga" src="https://user-images.githubusercontent.com/125442092/224677936-7a5b8c1c-633b-433a-a584-716dbb073abb.png">

### Expected behaviour

The names of the organizations should get sorted alphabetically via a click on the column title. Sort indications should be indicate via graphical icon, like in the overviews.

### Steps to reproduce the behaviour

* go to Admin > Manage > Organizations 
* click on "name"
* no sorting available

### Support Ticket

Ticket#10123886

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Hi Benjamin,

I can currently not reproduce the problem, did you also check the problem in the new release (5.4)?

Best regards,
Dominik

**Comment by BenjaminMarkus89** [comment]
Hi Dominik,

thanks for your feedback.

I tried it now in 5.4 and had the same issue.

Best regards,

Benjamin

**Comment by rolfschmidt** [comment]
reason for this is https://github.com/zammad/zammad/commit/1335033de992fa22c0458e508bf315a523f40660

we should revert or backport the reorder thing we did to solve the rails problem with sorting https://github.com/zammad/zammad/commit/a69fc3a4512c1bb9a43bf4cdd43830433bda55d3
