### ISSUE TITLE
API Errors since last update

### ISSUE THREAD

**Issue by mpibpc-mroose** [zammad/zammad#4522]
### Used Zammad Version

5.4.0-1678779346.2fb8d15c.focal

### Environment

- Installation method: package
- Operating system : ubuntu 20.04
- Database + version:  PostGres  9.5.13
- Elasticsearch version: 7.6.13
- Browser + version: Vivaldi 5.7.2921.63 (Stable channel) (64-bit)

### Actual behaviour

Today in the morning after installing the latest update Zammad was completely broken (gray screen). I fond such errors as:

```
E, [2023-03-15T08:46:40.936157#737-110640] ERROR -- : Error ID g7oNo0P1: PG::UndefinedColumn: ERROR:  column taskbars.app does not exist
```

I then run `zammad run rake db:migrate` and it somehow started working again.

But on nearly every UI action I get an 500 error. Then something like this is logged:

```
E, [2023-03-15T11:23:13.572103#738-111600] ERROR -- : Error ID Aiz52TCN: undefined method `app' for #<Taskbar id: nil, user_id: 4, last_contact: nil, client_id: nil, key: "Ticket-1646", callback: "TicketZoom", state: {}, preferences: {}, params: {"ticket_id"=>"1646", "shown"=>true}, prio: 7, notify: false, active: true, created_at: nil, updated_at: nil>
```

### Expected behaviour

No errors should arise

### Steps to reproduce the behaviour

As described its occuring on nearly every UI action.

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by fliebe92** [comment]
Hello @mpibpc-mroose and thanks for your report.

Unfortunately, it is very hard to tell you what went wrong during your update procedure. Do you have any logs available for us for checking? Maybe there are some errors shown that could explain the issue you're faced with.

In the meantime, we're also trying to reproduce it internally.

Thanks for your support. 😄

**Comment by mpibpc-mroose** [comment]
The interesting thing: after installing the latest update today the problem seems to have gone.

**Comment by AndrinS** [comment]
Had the same issue. Seems like updating zammad and postgresql (postgresql-12 postgresql-client-12) at the same time doesn't work.

Solved it by upgrading zammad isolated first and then the rest:

```
apt-get --only-upgrade install zammad
apt upgrade
```

**Comment by MrGeneration** [comment]
Updating both at the same time never worked and never will be.

**Comment by AndrinS** [comment]
I was not aware of this. Maybe that's worth mentioning in the [documentation](https://docs.zammad.org/en/latest/install/update.html).

**Comment by fredrikmagnusson-mf** [comment]
I had the same issue when going to 5.4.1. Neither I did know about the upgrading postgresql at the same time thing as @AndrinS  and are now stuck in the place where @mpibpc-mroose were with the:
 `StatusCode 500 : undefined method app' for #<Taskbar id: nil, user_id: 3, last_contact: nil, client_id: nil, key: "Ticket-447", callback: "TicketZoom", state: {}, preferences: {}, params: {"ticket_id"=>447, "overview_id"=>1, "shown"=>true}, prio: 61, notify: false, active: true, created_at: nil, updated_at: nil>`.

@mpibpc-mroose seemed to solve it with an update to next version, however I´m on the latest, 5.4.1-1681293771.5a04c99d.focal. Any ideas/suggestions how to fix this? It works, but quite infuriating when the popup appears. Have not tested everything yet though, but basic functions work

**Comment by mpibpc-mroose** [comment]
One could try to run a `zammad run rake db:migrate`.

**Comment by amirburi** [comment]
> One could try to run a `zammad run rake db:migrate`.

And then restarting Zammad did the trick on my site. Thanks for sharing!

**Comment by fredrikmagnusson-mf** [comment]
> > One could try to run a `zammad run rake db:migrate`.
> 
> And then restarting Zammad did the trick on my site. Thanks for sharing!

The first issue I got was the `PG::UndefinedColumn: ERROR:  column taskbars.app does not exist`, that got fixed with a `db:migrate`, thanks to you @mpibpc-mroose. The error after that, `StatusCode 500...` still persists however, even after restart of the service. Will try once more tonight, thank you for your replies!
