### ISSUE TITLE
Can't skip wizard any more with sendmail when error message occurs

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4525]
### Used Zammad Version

5.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

The `Email Notification` step in getting started (auto wizard) is checking the selected method of sending out email notifications. There is an error shown due to not having `sendmail`/another MTA installed/configured properly.

### Expected behaviour

The `Email Notification` step in getting started (auto wizard) is changed in two ways:

* It is possible to completely skip this step.
* It is possible to change the notification sender address in the same step.

### Steps to reproduce the behaviour

* Install Zammad and use getting started (auto wizard) to complete the setup process without having `sendmail` configured.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
relates https://github.com/zammad/zammad/issues/3343

**Comment by fliebe92** [comment]
relates https://github.com/zammad/zammad/issues/4073 (somehow)

**Comment by rolfschmidt** [comment]
This issue will only fix the situation that it is not possible any more to complete the wizard with an invalid sendmail (new skip button). #3343 will be discussed with @KoJie to be prioritized.
