### ISSUE TITLE
Object 'active' neither handled nor translated when displayed

### ISSUE THREAD

**Issue by NETertainer** [zammad/zammad#4529]
### Used Zammad Version

develop and 5.3

### Environment

Only related to source code.

### Actual behaviour

When displayed the object 'active' gets printed out with true/false rather then being translated as it is not handled explictly in viewPrintItem:
https://github.com/zammad/zammad/blob/973be3998bbf4f6957e8ad18301a425e78f11e70/app/assets/javascripts/app/index.coffee#L53-L175

### Expected behaviour

At least handle 'active' tag like 'boolean'.
```
if attributeConfig.tag is 'boolean' || attributeConfig.tag is 'active'
```
https://github.com/zammad/zammad/blob/973be3998bbf4f6957e8ad18301a425e78f11e70/app/assets/javascripts/app/index.coffee#L112-L116

Bonus: Move handling of boolean before fillup options to allow using custom values for display, otherwise boolean objects will always be printed with yes/no.
https://github.com/zammad/zammad/blob/973be3998bbf4f6957e8ad18301a425e78f11e70/app/assets/javascripts/app/index.coffee#L102-L109

### Steps to reproduce the behaviour

Can be seen on e.g. popovers that display the active tag.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
true, also a migration might make sense to set `translate: true` for the `active` fields, which makes sure it get's translated. This issue might not be visible any more because of https://github.com/zammad/zammad/issues/4505. But it makes sense to fix this in general.
