### ISSUE TITLE
Possibility to monitor Zammad system health via URL from external, like gitlab is offering it.

### ISSUE THREAD

**Issue by martini** [zammad/zammad#453]
<img width="1149" alt="screen shot 2016-11-22 at 11 23 51" src="https://cloud.githubusercontent.com/assets/110226/20520202/302ec312-b0a6-11e6-8d43-60a2d1c761cb.png">

**Comment by monotek** [comment]
Nice!
What kind of urls do you have in mind?
Also something like open & escalated tickets?

**Comment by martini** [comment]
Currently it's a system monitoring/system health check. Not monitoring of content. :-o

**Comment by rkaldung** [comment]
I suggest open and escalted tickets ssould be available via a REST URI..

**Comment by thorsteneckel** [comment]
I think this topic is about the health state of the Zammad system. Information about the content of the system should be available via an API endpoint like @rkaldung proposed. However this is another topic so feel free to open another issue for this where we can discuss it 👍

**Comment by martini** [comment]
@rkaldung This issue is only regarding technical monitoring (like gitlab is doing it).

@rkaldung @monotek Please file a new feature issue for "content monitoring". For me the following content would be fine (1) What is the problem?, 2) How to solve it).

**Comment by martini** [comment]
Done in master.

<img width="1159" alt="screen shot 2016-11-23 at 15 31 42" src="https://cloud.githubusercontent.com/assets/110226/20577209/9f33cd22-b1c1-11e6-9aee-aae1b9abe2aa.png">

**Comment by rkaldung** [comment]
Please enable HTTP Token Authentication like it's used for the API :-)

**Comment by jaykijay** [comment]
Hi,
some kind of Documentation on docs.zammad.org would be nice:
It shoudl answer the Questions:
What will be shown if everthing is okay (json style)
What will be shown if something fails?
Are there some differences between something hard failing, which will stop Zammad as whole from working and something small like one E-Mail couldn't be processed?
What will then be the Output of the JSON format.
We need these Infos to build an Nagios Check to this URL and process the different States and messages.
Thank you 🥇

**Comment by mbeijen** [comment]
Hi @jaykijay - I was just checking this topic because I too was creating a nagios check for our monitoring system. I found the checks and their output are defined in https://github.com/zammad/zammad/blob/81dfe88d993793dccf9c6221af49d9a67ea5ccb0/app/controllers/monitoring_controller.rb#L39

And for the issue @monotek mentioned in https://github.com/zammad/zammad/issues/453#issuecomment-262507841  about reading # of open tickets, this seems to be available under the `api/v1/monitoring/status?token=foo` URI now.

**Comment by monotek** [comment]
I would prefer a Prometheus.io metrics endpoint :D

**Comment by antondollmaier** [comment]
I'm sorry for digging through the old issues. I'd prefer not to open a new one.

Might it be possible to consider the prometheus.io endpoint? The content doesn't have to be huge: metrics for "zammad_version" would be sufficient to detect if Zammad is up and responding. Of course, business metrics would be a huge plus, but that's far less important (to me/us) than the health check.

**Comment by antonionardella** [comment]
Hi @antondollmaier,

I found this, not sure if it can be of interest for you:
https://gitlab.com/guardianproject-ops/zammad_exporter

**Comment by antondollmaier** [comment]
> I found this, not sure if it can be of interest for you: https://gitlab.com/guardianproject-ops/zammad_exporter

Thank you, that is indeed helpful. A native metrics/prom-health endpoint would nevertheless be greatly appreciated.
