### ISSUE TITLE
S/MIME integration does not allow separate certificates for sign & encrypt

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4534]
### Used Zammad Version

5.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Zammad is not checking the `key usage` information in the certificates and selects the first matching (mail address) certificate.

### Expected behaviour

Zammad is checking the `key usage` information in the certificates and is using the correct ones for signing/encrypting mails.

### Steps to reproduce the behaviour

- Import two S/MIME certificates, one for signing and one for encryption for one mail address.
- Create an article and sign or encrypt it.
- Check the received mail, mail clients (e.g. Outlook/Thunderbird) are complaining about an invalid certificate.

### Support Ticket

Ticket#10123227

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
Relevant RFC that defines the `Key Usage` extension: https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.3

**Comment by mgruner** [comment]
Helpful resource in German: https://www.gradenegger.eu/?p=9563

**Comment by mgruner** [comment]
The fix for this will be available with Zammad 6.1 only because it has a potential to slow the system down when working with many S/MIME certificates. There is another refactoring planned that will change this situation by importing more metadata to the S/MIME certificate database table and using that directly.
