### ISSUE TITLE
Boolean object attributes with false values are not shown in user and organization profiles

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad#4535]
### Used Zammad Version

5.4

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

If a user or an organization has a boolean object attribute with `false` value, the attribute is not shown in profile screens (i.e. `/#user/profile/:id` and `/#organization/profile/:id`).

<img src="https://user-images.githubusercontent.com/6049445/226918849-45fa18f3-da66-4a0e-afde-d20f7cf1587c.png">

### Expected behaviour

A boolean object attribute with `false` value should be displayed in user and organization profile screens if configured properly (i.e. `shown: true`).

<img src="https://user-images.githubusercontent.com/6049445/226918838-b2207fae-d183-455a-844c-bc4112f8cad9.png">

### Steps to reproduce the behaviour

1. Create a boolean object attribute for user/organization model and make sure it has `shown: true` for `view` screens.
2. Modify a test user/organization and set the boolean object attribute value to `false`.
3. Visit user/organization profile screen (i.e. `/#user/profile/:id` or `/#organization/profile/:id`) and confirm the boolean attribute is not shown.

These two screens should be aligned with the corresponding sidebars (i.e. in ticket create/zoom). The display of a boolean attribute should not depend on its value, rather 

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by NETertainer** [comment]
@dvuckovic Just wanted to add that something similar happens in app/assets/javascripts/app/views/popover/single_object_generic.jst.eco:

https://github.com/zammad/zammad/blob/17c7a20ca3fb95f31be29d41bdb4c227fbf89c0a/app/assets/javascripts/app/views/popover/single_object_generic.jst.eco#L6

as _.isEmpty fails for primitive types:

```javascript
_.isEmpty(1)
true

_.isEmpty(true)
true 
```

**Comment by dvuckovic** [comment]
@NETertainer Thanks for pointing this out!

For sure this check is inadequate, but, unfortunately, this cannot be easily checked in the template. Better solution would be to align the display of attributes with similar filters as for this fix.

However, this is out of scope for this already handled issue, so I created a new one where it can be tracked: https://github.com/zammad/zammad/issues/4559
