### ISSUE TITLE
Icon taskbar on the right is over the scrollbar

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#4538]
### Used Zammad Version

5.4

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Uubuntu 20.04
- Database + version:  Postgresql
- Elasticsearch version: 7.17
- Browser + version: Edge 111.0.1661.51

### Actual behaviour

The taskbar on the right hand is 1px too much right and cut the scrollbar a little bit

### Expected behaviour

The taskbar should be 1px more left for best fit.

### Steps to reproduce the behaviour

switch to dark mode because you can see it better there.

![image](https://user-images.githubusercontent.com/1473674/227777265-676c6724-2c9e-47c1-93af-f528dd77fdae.png)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
https://github.com/zammad/zammad/blob/e556a575a14b7a932274951dae5a4b43bab12a7c/app/assets/javascripts/app/controllers/widget/sidebar.coffee#L41

Maybe we need to round it + 1 px or something.

**Comment by rolfschmidt** [comment]
Spacings in the overview should be fixed as well (bulk action, much tickets = scrollbar right, couple tickets = none): 

![image](https://user-images.githubusercontent.com/5445062/228487508-aa7d1b34-a046-4d4c-a60d-f23b88af6d68.png)

Looks odd when there is no scrollbar.

https://github.com/zammad/zammad/blob/e556a575a14b7a932274951dae5a4b43bab12a7c/app/assets/javascripts/app/controllers/widget/ticket_bulk_form.coffee#L53

**Comment by mantas** [comment]
Tickets bulk update form will be addressed in a separate issue https://github.com/zammad/zammad/issues/4837
