### ISSUE TITLE
/#search shows blank page instead of redirect to login

### ISSUE THREAD

**Issue by SwissTazMan** [zammad/zammad#4545]
### Used Zammad Version

5.4.0

### Environment

- Installation method: Zammad created test environment (30 days trial)
- Browser + version: Chrome 111.0.5563.65

### Actual behaviour

If I’m not logged in to Zammad, open an new browser tab and entering base_url/#search, it shows a really short loading animation and then a blank page.

### Expected behaviour

If I’m not logged in to Zammad, open an new browser tab and entering base_url/#search it should redirect to the login page and after login it should redirect to /#search

### Steps to reproduce the behaviour

Logout from Zammad
Enter the url base_url/#search in a new tab

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by NETertainer** [comment]
I can confirm that no redirect is performed when directly accessing `https://<zammad>/#search` without being logged in.

The router of the search controller is missing something like either `requiredPermission: ['*']` or `@authenticateCheckRedirect()`:
https://github.com/zammad/zammad/blob/17c7a20ca3fb95f31be29d41bdb4c227fbf89c0a/app/assets/javascripts/app/controllers/search.coffee#L354-L358

Or both when compared to the router of the dashboard controller:
https://github.com/zammad/zammad/blob/17c7a20ca3fb95f31be29d41bdb4c227fbf89c0a/app/assets/javascripts/app/controllers/dashboard.coffee#L99-L106
