### ISSUE TITLE
Reporting profiles do not work with multi tree select

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4546]
### Used Zammad Version

5.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: Firefox

### Actual behaviour

When creating a reporting profile with a condition based on a multi_tree_select the profile cannot be displayed:

![grafik](https://user-images.githubusercontent.com/97293098/228557977-22ab4e55-fbce-49e2-92c9-924eede813b6.png)

It's possible to create the profile, the profile editor shows the correct tickets in the preview. The error shows only on the reporting screen later.

### Expected behaviour

Being able to create working reporting profiles based on multi_tree_selects.

### Steps to reproduce the behaviour

Create a ticket attribute of the multi_tree_select type. Create a reporting profile with a condition based on that attribute. Use that reporting profile.

![grafik](https://user-images.githubusercontent.com/97293098/228558620-8a135b36-0381-48b5-895e-3127ed3e64ea.png)

### Support Ticket

#10125898

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@rolfschmidt looks like this problem was added with the AND/OR feature: https://github.com/zammad/zammad/commit/4b3d5eb113dd0e8a70f816208369ee61a42b41af#diff-0b3a9c7bd4630a721d5b1a1b3de221cf9368f9572ce0168bdfa05c9db09f72ebR241
