### ISSUE TITLE
Allow logout for SAML accounts without set idp_slo_service_url

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4548]
### Used Zammad Version

5.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: Firefox 111.0 (64-Bit) or any other Browser

### Actual behaviour

When the SAML logout URL is not set, Zammad will throw an modal provided error message. This message does not allow the agent to actually logout.

Within the logfile you'll find 
`E, [2023-03-29T17:29:29.863265#18159-112120] ERROR -- : Error ID WaohPPv5: Invalid settings, idp_slo_service_url is not set!`

### Expected behaviour

Instances upgraded to Zammad 5.4 will automatically throw errors when the try to manually logout their account. This is due to the logout URL not being set (yet).

While the logout URL functionality is a big plus and important, users are not able to logout due to this issue. Zammad should either silently INFO log this issue or not log it at all. This allows admins to correct the configuration at a later moment.

### Steps to reproduce the behaviour

- Have Zammad pre 5.4 with a working SAML configuration
- upgrade to Zammad 5.4
- login to any SAML user
- try to logout that SAML user

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
This leaves the user session in a blotted, maybe insecure state, so I added the blocker label.

More straightforward steps to reproduce.
* Remove the `idp_slo_service_url` config setting of a proper SAML setup.
* Login to any SAML user.
* Try to log out of that SAML user.
