### ISSUE TITLE
Delayed::Job warnings in Syslog when using MariaDB 10.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#455]
`Nov 23 12:22:42 servername mysqld[1167]: 2016-11-23 12:22:42 140055746542336 [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. The statement is unsafe because it uses a LIMIT clause. This is unsafe because the set of rows included cannot be predicted. Statement: UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` = '2016-11-23 11:22:42', `delayed_jobs`.`locked_by` = 'host:v2 pid:805' WHERE ((run_at <= '2016-11-23 11:22:42' AND (locked_at IS NULL OR locked_at < '2016-11-23 07:22:42') OR locked_by = 'host:v2 pid:805') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1`

**Comment by martini** [comment]
JFI: It's a delayed_job (https://github.com/collectiveidea/delayed_job) issue. There is also an issue there https://github.com/collectiveidea/delayed_job/issues/516

@monotek a solution seems to be here http://dba.stackexchange.com/questions/6150/what-is-the-safest-way-to-switch-the-binlog-format-at-runtime/6753#6753 I'm not familiar with mysql/mariadb - is this a solution?

**Comment by monotek** [comment]
Maybe. Don't know if there are any problems with this setting.
Closing this issue for now.
