### ISSUE TITLE
Slack notifications not working in 5.4.0-1680261642.c296586b.focal 

### ISSUE THREAD

**Issue by SumOfOneInteger** [zammad/zammad#4552]
### Used Zammad Version

5.4.0-1680261642.c296586b.focal

### Environment

- Installation method: [e.g. source, package] **Package**
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04] **Ubuntu 22.04.2**
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3] **postgres (PostgreSQL) 14.7 (Ubuntu 14.7-0ubuntu0.22.04.1)**
- Elasticsearch version: [e.g. 7.17] **7.17.9**
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] **not browser specific**

### Actual behaviour

I disabled notifications were  for one of the groups that had been enabled for years. Didn't notice the lack of notifications for all groups for a period of hours. Reenabled for the group notifications were removed for. Still no notifications in Slack. Updated from 5.3.1-1676465796.746f9768.focal to  5.4.0-1680261642.c296586b.focal hoping that would fix the issue. This version brought along bugs that prevented Microsoft 365 integration from functioning. Reverted back to snap of 5.3.1. Still no notifications. Screenshot of most recent log posted with personal information removed. I'm not sure if Response "" is normal because I never checked the logs when it was functioning properly to have noticed a difference.
![image](https://user-images.githubusercontent.com/11754440/229139135-acd0a281-0c6f-4356-82c5-03dcabb3cceb.png)

### Expected behaviour

Slack notifications received. 

### Steps to reproduce the behaviour

Unselect a group from 'Only for these groups' under Slack integration, then lose all slack integration functionality. 

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
I could not reproduce any problem with the slack integration.
You can check if there are still new entries in the "Recent Logs". The entry from the screenshot looks like a problem on the other side because there is no status code and response.

This seems to be a technical question.

Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by SumOfOneInteger** [comment]
This is a bug report and not a technical question. It was tested on two different servers running the same version of Ubuntu & Zammad in our infrastructure. I can curl to Slack using the webhook from each server without issue and it functions as expected. I suspect this is an issue with the structure of the webhook in Zammad.

**Comment by dominikklein** [comment]
When this is a problem on our side, then there should be something in the logs. Can you check if there are any error messages related to the slack integration?

Maybe it's related to Ubuntu 22, this is supported until the last 5.4 release.

**Comment by SumOfOneInteger** [comment]
I've ran through the logs and there's a myriad of listings for Slack. The error messages are virtually identical to the first block below. The other block at the bottom is what I'm seeing before the error message posts in the log. 

E, [2023-03-31T13:20:35.876434 #906-111620] ERROR -- : Unable to post webhook: https://hooks.slack.com/services/[REDACTED]: [#<UserAgent::Result:0x000055be6733d198 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Net::ReadTimeout: Net::ReadTimeout>", @header=nil>]

I, [2023-03-31T13:41:18.158134 #906-111620]  INFO -- : 2023-03-31T13:41:18+0000: [Worker(host:helpdesk pid:906)] Job TicketArticleCommunicateEmailJob [REDACTED] from DelayedJob(default) with arguments: [62011] (id=3229311) (queue=default) RUNNING
I, [2023-03-31T13:41:19.329610 #896-28864360]  INFO -- : Started GET "/api/v1/http_logs/slack_webhook?limit=50&_=1680267654594" for 192.168.53.25 at 2023-03-31 13:41:19 +0000
I, [2023-03-31T13:41:19.335589 #896-28864360]  INFO -- : Processing by HttpLogsController#index as JSON
I, [2023-03-31T13:41:19.335666 #896-28864360]  INFO -- :   Parameters: {"limit"=>"50", "_"=>"1680267654594", "facility"=>"slack_webhook"}
I, [2023-03-31T13:41:19.375004 #896-28864360]  INFO -- : Completed 200 OK in 39ms (Views: 27.0ms | ActiveRecord: 1.6ms | Allocations: 22238)

**Comment by SumOfOneInteger** [comment]
In spite of the 'ReadTimeout' I can curl and successfully post immediately after a fail from Zammad shows up in the logs.

**Comment by SumOfOneInteger** [comment]
Can I get this opened back up, please?

**Comment by SumOfOneInteger** [comment]
Following up, can I please get this bug report reopened?

**Comment by MrGeneration** [comment]
Please stop bumping closed issues.
I verified the Slack integration to be working just now and just for you.

Your issue is a technical question and thus belongs to https://community.zammad.org

**Comment by SumOfOneInteger** [comment]
Marcel, 

They may be working for you, but I need you to explain to me how it is possible that two different servers running the same version of Zammad on the same OS on each server is experiencing the issue. 

Logs were posted above. Immediately after the fail posts in the log I can curl from an ssh session on each server successfully. If issues were not closed incorrectly, they wouldn't need to be bumped.

**Comment by MrGeneration** [comment]
As I said. This is an individual problem on your end not an bug.
Kindly create a thread on the community, thank you.

**Comment by SumOfOneInteger** [comment]
Yes, you have stated, but you have not explained. In what manner is this not a bug?
