### ISSUE TITLE
CTI user matching with LDAP integration not working 

### ISSUE THREAD

**Issue by ticktostick** [zammad/zammad#4555]
### Used Zammad Version

5.4

### Environment

- Installation method:  package
- Operating system ubuntu 20.04
- Database + version:   postgresql 12.14
- Elasticsearch version:  7.17
- Browser + version:  chrome 111

### Actual behaviour

The Caller log doesn't find customers from LDAP phone numbers and show all as new user
but finds local user phone numbers 

### Expected behaviour

Call log should shows LDAP users as existing customer like the local users

### Steps to reproduce the behaviour

LDAP integration with phone number and mobile attribute store in Active directory and get sync in zammad
integrate to CTI generic
Call agent
the caller phone number is in user profile but its shown as new user

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by t-shehab** [comment]
Hey @ticktostick,

I'm having some trouble reproducing the issue you're describing. On my end, everything seems to be working fine.

Generally, Zammad doesn't make a difference between the contents of data fields (whether they were entered manually or synced via LDAP, for example)

Maybe you can provide some more information about the format the phone numbers are in that work, and those that don't?

**Comment by ticktostick** [comment]
The phone numbers are extension numbers sync from IPphone attribute from Active Directory
![edituser](https://user-images.githubusercontent.com/80856666/231583013-d24319b3-8c21-4eed-85b2-4fa8f3894651.jpg)
![notif](https://user-images.githubusercontent.com/80856666/231583020-809e461e-9216-4bda-b29f-1a315e065572.jpg)

**Comment by ticktostick** [comment]
checked Also with 0XXXXXXXXXX
12 Digit numbers not getting matched.

**Comment by ticktostick** [comment]
Find The exact problem
If I have both MOBILE and PHONE fields fill up with number **its not** matching
If I have only MOBILE field it gets matched
If I have only PHONE field **its not** getting matched

**Comment by MrGeneration** [comment]
This is a technical question.
The extension minimum length is 4 digits which you do not match. 

This is working as designed as of now. If you believe this is a flaw, feel free to create a feature request here:
https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6
