### ISSUE TITLE
Trigger automation manually 

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#456]
Feature Request: Would be nice to trigger time automation manualy

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
