### ISSUE TITLE
 TicketView the Group field is nulled if full access is not set to any Group in the Role configuration

### ISSUE THREAD

**Issue by nbrgit** [zammad/zammad#4569]
### Used Zammad Version

5.3

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

Hey all,
I configure a Userrole with only read Permission. this Userrole have permission to read and list different Groups.

But there seems to be an issu with the Group rights.
Because in the Ticketview the Field Group change to - 

### Expected behaviour

If I give the read and Overview Permission to a Group it shouldn't change the current Group of a Ticket

### Steps to reproduce the behaviour

Here the example:

I select in the Role configuration the Group "Test" with the Permission "Read" and "Overview" 
After that I've a look with the User to a Ticket which is in the Group "Test" (doesn't matter which state the Ticket have)
If I open the Ticket on the right side the Groupname disappears and  only this symbol "-" is shown in the Group field, like no Group selected.

If i want to leave the Ticket a PopUp ask for Leaving without changes....

Now the Solution, if i give the Userrole any Fullpermission from any Group the Field Group in a Ticket doesn't change.

Hopefully you understand what i mean :)

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by t-shehab** [comment]
Hey @nbrgit,

at the moment, I cannot reproduce the issue you're describing. Maybe you could be more detailed in your description? Perhaps add screenshots of the exact steps you took to experience the behaviour you're describing.

Also, current stable version of Zammad is 5.4.1
We recommend you always stay up to date to get the newest features, as well as the most recent bug- and security fixes.

**Comment by t-shehab** [comment]
No feedback received. Closing for the time being. Unable to reproduce.
