### ISSUE TITLE
Scheduler Time offset

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#457]
* Ticket-ID: #107079, #1052024, #1084039, #1086872

I did a trigger wich will fire on 16:30. Servertime is 16:26 and the trigger time says 1 hour and 4 Minutes.

**Comment by martini** [comment]
JFI: It's a timezone issue. Currently the time selector and view is show in GMT for triggers.

**Comment by sthag** [comment]
+1 for resolving this issue.
Just noticed the problem. Actions set for automation do not display and trigger according to the server/php.ini time.

**Comment by monotek** [comment]
Zammad is a ruby app. Changes to php.ini have no effect ;-)

**Comment by sheLbyPL** [comment]
Any update, please?

It would be great to have timezone setting in the web panel, or is there any way to fix it by ruby console for example?
