### ISSUE TITLE
Group assignment overleaps outside of dialog content in the invite agent dialog

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#4570]
### Used Zammad Version

5.4.1-1681293771.5a04c99d.bullseye

### Environment

- Browser + version: [e.g. chrome 83, safari 14, firefox 105]
tested with Brave and Firefox

### Actual behaviour

![Bildschirmfoto 2023-04-13 um 10 43 34](https://user-images.githubusercontent.com/129729908/231952953-eb1e7f0e-a443-4854-a6cf-5c846c39bf84.png)
<img width="609" alt="Bildschirmfoto 2023-04-14 um 07 37 01" src="https://user-images.githubusercontent.com/129729908/231952963-e456a435-9bad-4312-90eb-dfa50a58e8b0.png">

### Expected behaviour

window for the assignment of permissions fits in the window

### Steps to reproduce the behaviour

appears during installation process and later if you invite Agents/Colleagues

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by mantas** [comment]
I've a feeling this needs specification required label.

Simply making window wider is an uphill battle since other languages may have even longer naming. Maybe we could change to icons in the table header and show detailed description in a tooltip on mouse over?
