### ISSUE TITLE
Admin user can not find user or organization in the search bar

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#4574]
### Used Zammad Version

5.4

### Environment

Zammad Hosted Trial environment 

### Actual behaviour

When I am logged in with an admin account that does not have the customer or agent Role, I can not use the search bar to find other user or organisations

### Expected behaviour

As an admin, I should be able to find user or organizations via the search bar.
Even if I don't have the agent or customer role.

### Steps to reproduce the behaviour

-Login with an admin account
- make sure that the admin user has no agent and customer role
- try to use the search bar
- Please see screencast attached
[Screen Recording (14.04.2023 16-09-31).wmv.zip](https://github.com/zammad/zammad/files/11233700/Screen.Recording.14.04.2023.16-09-31.wmv.zip)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
regression of https://github.com/zammad/zammad/commit/5e3263d5c539af1bbb0d6f5bebecdf09ab448227

**Comment by rolfschmidt** [comment]
Actually not a regression, it is a different issue.
