### ISSUE TITLE
Typo in password_change hu.html.erb file

### ISSUE THREAD

**Issue by spearox** [zammad/zammad#4580]
### Used Zammad Version

5.4.0

### Environment

- Installation method: Docker
- Operating system: Debian GNU/Linux 11 (bullseye)
- Database + version: postgres:15.1-alpine
- Elasticsearch version: 8.5.1
- Browser + version: Chrome 112.0.5615.86

### Actual behaviour

In file "app/views/mailer/password_change/hu.html.erb" there is a typeo:
`<p>Az Ön #{config.product_name} fiókjának <b>#{{user.login}</b> jelszava nemrég megváltozott.</p>`
This cause error in email:
`Az Ön X fiókjának #{{user / no such object} jelszava nemrég megváltozott.`

### Expected behaviour

Change the **#{{user.login}** text to **#{user.login}** to fix. There is one extra "{" sign.

### Steps to reproduce the behaviour

Request a forgot password email then reset the password while the language is set to Hungarian (magyar).

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
This file's translation is handled within weblate.
I updated the translation for you already.

https://translations.zammad.org/translate/zammad/zammad-development/hu/?checksum=81885eff786574cd
