### ISSUE TITLE
iCloud emails are not fetchable via IMAP

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4589]
### Used Zammad Version

5.4

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

- No errors
- Mails are fetched in the log but no import

### Expected behaviour

iCloud messages should get fetched 

### Steps to reproduce the behaviour

Test system provided by @Suhopoljac 

Ticket#10126300

### Support Ticket

Ticket#10126300

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
It looks like that the body can not be fetched:

https://github.com/zammad/zammad/blob/21a6a1a90a2c142bc350eef762293be5695468cd/app/models/channel/driver/imap.rb#L294

```
3.1.3 :043 > imap.fetch(7 , 'RFC822')[0]
 => #<struct Net::IMAP::FetchData seqno=7, attr={}>
3.1.3 :044 > imap.fetch(7 , ['RFC822'])[0]
 => #<struct Net::IMAP::FetchData seqno=7, attr={}>
3.1.3 :045 > imap.fetch(7, ['RFC822.SIZE', 'FLAGS', 'INTERNALDATE', 'RFC822.HEADER'])[0]
 =>
#<struct Net::IMAP::FetchData
 seqno=7,
 attr=
  {"RFC822.SIZE"=>5277,
   "FLAGS"=>[:Seen],
   "INTERNALDATE"=>"20-Apr-2023 11:36:25 +0000",
   "RFC822.HEADER"=>...>
3.1.3 :053 > imap.fetch(7, ['BODY[TEXT]'])[0]
 =>
#<struct Net::IMAP::FetchData
 seqno=7,
 attr=
  {"BODY[TEXT]"=>
    "--00000000000039aa7805f9c2f301\r\nContent-Type: text/plain; charset=\"UTF-8\"\r\n\r\n1\r\n\r\n--00000000000039aa7805f9c2f301\r\nContent-Type: text/html; charset=\"UTF-8\"\r\n\r\n<div dir=\"ltr\">1</div>\r\n\r\n--00000000000039aa7805f9c2f301--\r\n"}>
3.1.3 :059 > imap.fetch(7, ['RFC822.SIZE'])[0]
 => #<struct Net::IMAP::FetchData seqno=7, attr={"RFC822.SIZE"=>5277}>

```

**Comment by rolfschmidt** [comment]
@martini It seems like that RFC822 doesn't work for iCloud, but detailed requests like `RFC822.SIZE` work. Did you ever see this before?

**Comment by rolfschmidt** [comment]
looks like `BODY[]` solves the issue (https://stackoverflow.com/a/75734707):

```ruby
puts imap.fetch(7, 'BODY[]')[0].attr['BODY[]'].length
5277
```

**Comment by angreebeaver** [comment]
Hei Rolf, I reported this issue. Please tell me if I can support you with testing. I appreciate your efforts.

**Comment by rolfschmidt** [comment]
> Hei Rolf, I reported this issue. Please tell me if I can support you with testing. I appreciate your efforts.

thx, no need atm. We can reproduce it. Hopefully can fix it soon :)
