### ISSUE TITLE
closing several Tickets -> deadlock detected

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#459]
In the overview i selected all Tickets and set the new status to closed. The Webinterface gives me this error

`{"error":"ERROR:  deadlock detected\nDETAIL:  Process 8327 waits for ShareLock on transaction 10423; blocked by process 8306.\nProcess 8306 waits for ShareLock on transaction 10422; blocked by process 8327.\nHINT:  See server log for query details.\n"}
`

**Comment by monotek** [comment]
Which OS?
Which database Server?

**Comment by Julian0o** [comment]
CentOS7 with package installation. 
Postgresql

**Comment by MartinBorg** [comment]
OS: Debian Jessie, amd64
Version: 1.4.0 (Zammad .deb package)

Got this right now:

```
{"error":"ERROR:  deadlock detected\nDETAIL:  Process 16996 waits for ShareLock on transaction 33905; blocked by process 22164.\nProcess 22164 waits for ShareLock on transaction 33906; blocked by process 16996.\nHINT:  See server log for query details.\nCONTEXT:  while updating tuple (5,11) in relation \"taskbars\"\n"}
StatusCode: 500
```

The log is very long, but says something along the lines of:

```
"/opt/zammad/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'"]
```

**Comment by hanneshal** [comment]
Closed.
Please reopen when this issue still exists in 2.0.
