### ISSUE TITLE
Pre-Defined Webhook fields should only be visible in pre-defined webhook context when using the variable autocompletion

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4590]
### Used Zammad Version

5.4.x (develop)

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Currently, a fixed list of pre-defined webhooks is always returned when using the variable auto-completion inside the custom payload editor. Also when the custom payload is used without a pre-defined webhook.

### Expected behaviour

The webhook fields should only be returned from the variable auto-completion when the current pre-defined webhook supports additional fields and when there is no pre-defined webhook context, the webhook fields should not be visible in the variable auto-completion.

### Steps to reproduce the behaviour

- Create a new webhook.
- Open the custom payload field.
- Use the variable auto-completion (`::` or `#{`) and see that also the pre-defined webhook fields are visible.

![Bildschirmfoto 2023-04-24 um 12 33 54](https://user-images.githubusercontent.com/5445094/233972058-94fff99c-92c7-4248-b344-30fb0fa02099.png)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
**Possible solution:**
* Add optional parameter `webhook_name` to related API endpoint `/api/v1/webhooks/payload/replacements`
* Adopt `replacements` method in `TriggerWebhookJob::CustomPayload` and `TriggerWebhookJob::CustomPayload::Track` and descendants
