### ISSUE TITLE
Customer role can see the 3rd party services integration in the ticket sidebar

### ISSUE THREAD

**Issue by BenjaminMarkus89** [zammad/zammad#4594]
### Used Zammad Version

5.4.1

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Role customer sees the i-doit, github and gitlab integration icon.
In case of i-doit In the ticket zoom the menu item "Change Objects" is displayed to the customer for the i-doit integration.
When selected, the following is displayed: "Content could not be loaded."

If Github or Gitlab is enabled, the sidebar is visible for customers, but the content is not visible.

### Expected behaviour

Only the Agent role should see the 3rd party integrations integration icons on the ticket. Role Customer should not see the those integrations.

### Steps to reproduce the behaviour

- Setup the i-doit integration in Zammad and then select the i-doit integration icon on the right side of the ticket from the view of the customer role. 
- Then press "Change Objects".  After pressing "Change Objects", you will see "Content could not be loaded."

### Support Ticket

Ticket#10126485

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Could be related to this and it should be done in a similar way: https://github.com/zammad/zammad/issues/4287

**Comment by dominikklein** [comment]
@mantas I'm not sure if the "expected" behavior is really correctly described here. Did you take a look at my linked issue? Here we decided on a different solution.

**Comment by mantas** [comment]
@dominikklein ah, I read it as the linked issue is similar to this one.

I wonder if Idoit integration access is important for customers. While Github/Gitlab tab shows interesting data to customer, what would customer use Idoit tab for?

**Comment by mantas** [comment]
I-doit, Github and Gitlab sidebars will be hidden for customers for now. In the future, this behaviour will be improved by allowing to optionally enable customer access as per https://github.com/zammad/zammad/issues/4287

**Comment by MrGeneration** [comment]
Wait wasn't it a feature that Github and Gitlab could be seen by customers?

**Comment by mantas** [comment]
There's #4287 to address this properly. This one will hide broken tabs for now. Then we'll fix it properly.
