### ISSUE TITLE
S/MIME Signature Check: Mail Address from Subject Alternative Name is downcased, but the sender is not

### ISSUE THREAD

**Issue by poettig** [zammad/zammad#4597]
### Used Zammad Version

5.4.1-1682496131.d4dddcd0.bullseye

### Environment

- Installation method: Debian package https://dl.packager.io/srv/deb/zammad/zammad/stable/debian
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian 11
- Database + version:  postgresql 13.9-0+deb11u1
- Elasticsearch version: 8.7.0
- Browser + version: Firefox 112

### Actual behaviour

When receiving an email signed using S/MIME with a certificate containing a Subject Alternative Name `Firstname.Lastname@example.com` and a mail header `From: "Lastname Firstname" <Firstname.Lastname@example.com>`, the signature is marked as invalid by Zammad, even tough the both SAN and Header-From use the same casing:

![image](https://user-images.githubusercontent.com/19955832/235141482-e479c2c3-0ab0-4fc9-853f-6e4bdd65371b.png)

Relevant line from `production.log`:
```
W, [2023-04-28T12:53:06.066451#737549-151320]  WARN -- : S/MIME mail <1ef0816abc594fb5ae042776dda9511b@example.com> signed by firstname.lastname@example.com but sender is Firstname.Lastname@example.com
```

This is caused by the fact that https://github.com/zammad/zammad/blob/develop/lib/secure_mailing/smime/incoming.rb#L249 downcases the email from the SAN, but https://github.com/zammad/zammad/blob/develop/lib/secure_mailing/smime/incoming.rb#L234 does not downcase the Header-From.

### Expected behaviour

The signature is verified as correct as the signature itself is fine, the certificate is trusted and Header-From matches at least one of the SANs.

This can achieved by either of

* downcasing the Header-From as well. This is what Thunderbird and Outlook appear to be doing.
* Not downcasing the SANs. This ist the "correct" behaviour according to the mail RFC. 

Mildly related community feature request: https://community.zammad.org/t/strictness-of-signer-sender-check-for-s-mime-signed-mails/11219

### Steps to reproduce the behaviour

1. Get certificate for Firstname.Lastname@example.com as a SAN
2. Write a mail to a Zammad ticket system with Header-From Firstname.Lastname@example.com signed by the certificate from step 1
3. Observe "Message is not signed by sender"

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
@poettig excellent bug report, thank you so much!

**Comment by poettig** [comment]
> @poettig excellent bug report, thank you so much!

My pleasure, thanks for the fix!
