### ISSUE TITLE
Error 500 if overview with "out of office replacement" filter is set to "specific user"

### ISSUE THREAD

**Issue by wucherpfennig** [zammad/zammad#4599]
### Used Zammad Version

5.4.1

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian
- Database + version:  postgresql 

### Actual behaviour

If you want to have a overview which filters for tickets of a specific user who is the out of office replacement by using the filter condition "out of office replacement" set to "specific user" then an error 500 will appear and an error message error will appear: "Invalid ticket selector conditions".

* "Expert mode" makes no difference.
* new and existing overviews ("my_replacement_tickets") are both affected

```
# error excerpt
undefined method `out_of_office_agent_of' for [#<User id: 3, TRUNCATE ]:Array
bind_params.push User.find(block_condition[:value]).out_of_office_agent_of.pluck(:id)
```

![grafik](https://user-images.githubusercontent.com/3634653/235427286-c6759b3a-c85c-4fbd-a2e7-188b0bdfb6c7.png)

### Expected behaviour

Allow to select an user.

### Steps to reproduce the behaviour

See screenshot above-

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
It seems that using the `out of office replacement` filter is broken for a long time.

In `app/models/ticket/selector/sql.rb`, starting with line 242, we're dealing with an array of values, therefore we need to iterate over `block_condition[:value]` instead of simply using it.

Possible quick'n'dirty fix (untested):

```rb
new_params = []
block_condition[:value].each do |user_id|
  new_params.push User.find(user_id).out_of_office_agent_of.pluck(:id)
end

bind_params.push new_params.join(', ')
```

**Comment by rolfschmidt** [comment]
agree, verified this issue is older than stable-5.2
