### ISSUE TITLE
Encrypt channel passwords stored in DB

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#460]
Passwords for email channels (SMTP, IMAP...) seem to get stored in the database in clear text. Wouldn't it be better storing them in an encrypted form?

**Comment by monotek** [comment]
Think this would need some kind of a unique security token, which is used for encrypt / decrypt the data. Maybe secrets.yml could be used?
Installer could create the token like its done for the database password.

**Comment by rkaldung** [comment]
As far as you need/have a mechanism to decrypt the password it's only security by obscurity. Nothing worth to work on.

**Comment by olivergrahl** [comment]
Good point...

**Comment by monotek** [comment]
@rkaldung 
Thats why i suggested using a unique/randmom security token in the config.
Having a database dump without the token would be useless.

**Comment by rkaldung** [comment]
@monotek Usually everyone who has database access also has file system access.

**Comment by olivergrahl** [comment]
@rkaldung Hmm, not true for db dumps/backups or the db running on its own host, like ours.

**Comment by dominikklein** [comment]
Currently, it's not planned to change the situation.
