### ISSUE TITLE
Microsoft 365/Google reauthenticate changes the "leave emails on server" to "no" by default. 

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#4601]
### Used Zammad Version

5.4

### Environment

- Installation method: package
- Operating system  debian 10.4
- Database + version:  postgresql 9.3, 
- Elasticsearch version: 7.17
- Browser + version: all

### Actual behaviour

I configure a Microsoft 365 email account in Zammad and choose to leave the emails on the server.
When I reauthenticate the email account, I am asked to choose a folder and the leave emails on server is set to "no".

This often causes the Problem that admins doesn't see the change and kicks on accept. Which is confusing for the admins.

### Expected behaviour

1) When and admin is reauthenticating an email account, he is not asked for the inbox folder or to leave the emails on the server.
The settings will be automatically taken from the setup account.

2) you can choose the inbox and to leave emails on the server, but the default is what you already set up in the email account. 

### Steps to reproduce the behaviour

-set up a Microsoft 365 email account
- set leave emails on server to "yes"
- reauthenticate the mail acocunt
- leave emails on server is set to "no" by default

[Screen Recording (05.05.2023 11-27-18).wmv.zip](https://github.com/zammad/zammad/files/11404929/Screen.Recording.05.05.2023.11-27-18.wmv.zip)

### Support Ticket

Ticket#10127551

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
I'm adding blocker as this is a severe bug. Only most of the channels in SaaS are deactivated if they fail due to us monitoring them. A e.g. selfhosted user or saas customer that reacts faster than we do in monitoring, will do this change to an active mailbox and have no chance at all to counter act if unlucky.
