### ISSUE TITLE
Log Trigger, Postmaster Filter and Scheduler in Ticket History

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4604]
### Used Zammad Version

6.0

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

No information in the history if the changes is coming from a trigger.

### Expected behaviour

If the ticket is modified by a Trigger and Schedulers then it should get related in the history:

![image](https://github.com/zammad/zammad/assets/5445062/33577ad7-0421-481a-b3dc-88ab99a254de)

Note: For Postmaster Filter this actually makes not really sense. The perform actions of filter will use x-zammad-headers which only work on ticket create not update. So there will history entries visible for that case anyway. They might be excluded for now.

### Steps to reproduce the behaviour

- Create a trigger which sets the priority on 3 high
- Do a change at the ticket
- Open the ticket history

### Support Ticket

Ticket#10125911

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
Maybe it could be an option to create new history entries for the case that postmaster filters change attributes in the process of the ticket create to make it more visible. @martini says that 2nd often debug this info via logs. So we could profit if this would be visible in the UI as well. This should be thought about if there is some leftover time.

**Comment by rolfschmidt** [comment]
Forgot to edit the title, but postmaster filters are supported as well.

**Comment by crnfpp** [comment]
Great news! Thanks for the great work!!
