### ISSUE TITLE
Submitting an updated/altered edit dialog (users, organizations, etc.) does not always change the data

### ISSUE THREAD

**Issue by herzkerl** [zammad/zammad#4608]
### Used Zammad Version

6.0 / 5.x

### Environment

- Installation method: package
- Operating system: Debian 10
- Database + version:  psql (PostgreSQL) 11.20 (Debian 11.20-0+deb10u1)
- Elasticsearch version: 7.17.10
- Browser + version: any (tried Safari 16.4, Brave 1.51.114)

### Actual behaviour

Opening the edit dialog again, you’ll find that the values have not been changed.

### Expected behaviour

Submitting the dialog should always update the object (or throw an error).

### Steps to reproduce the behaviour

• Navigate to Manage > Users
• Search for user—clicking opens the „Edit: User“ dialog
• Change values, e.g. a dropdown
• Click submit

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by t-shehab** [comment]
Hey @herzkerl,

thanks for opening this issue. I've just done some superficial testing, and I don't seem to run into the same problems you do. In the title you've chosen for this issue, you're implying that it doesn't always happen ("does not always change the data". So I assume sometimes it does).

Therefore, currently, it is rather difficult for me to reliably test this issue and conclusively verify or falsify it. Would you be able to give me more information on when exactly the behaviour you're experiencing happens?

Thanks in advance. :-)

**Comment by fliebe92** [comment]
Closing due to no feedback after a certain time. Feel free to provide us with the required information and we're happy to reopen it.

**Comment by herzkerl** [comment]
Sorry! Yes, it only happens rarely—and after restarting Zammad it worked just fine.

I know that this might mean there's no way to find the root cause at the moment, but I'll make sure to update this issue if it happens again (with more information, if possible).
