### ISSUE TITLE
Chat widget throwing errors on send

### ISSUE THREAD

**Issue by abenrob** [zammad/zammad#461]
When user clicks send in the chat widget, the following error is thrown:
`Uncaught TypeError: this.el.find('.zammad-chat-message--typing').size is not a function(…)` (chat.js:706)
Inspecting the page, there is no element with the aforementioned class. 
The chat widget displays messages from the agent, and the agent can see the connection request from the widget...

**Comment by abenrob** [comment]
Any thought on this?

**Comment by martini** [comment]
Hi @abenrob 

I can't reproduce it. Do you have an example page where I can test/see this behaviour?

 -Martin

**Comment by abenrob** [comment]
I will try to get  a version you can preview in place, but for now, we are just disabling chat... Once past our next deploy, I'll look into putting this in place.

**Comment by martini** [comment]
Nice! I close the issue for now, just reopen on feedback.

**Comment by kennethlarsen** [comment]
@martini I have the exact same issue and I suspect it's related to jQuery versions. On Zammad.org it's suggested to use 2.1.4. Is this really true? I get this error on 3.1.1.

**Comment by thelfensdrfer** [comment]
Could this be reopened until the chat works with the current version?
