### ISSUE TITLE
Editing the note field in the user profile - information cannot be pasted into, can only be typed manually

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4613]
### Used Zammad Version

5.4.1

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge v. 113.0.1774.35 (Official Build) (64-bit)

### Actual behaviour

When editing a user profile, it is not possible to insert text into the note field. Neither with the context menu, nor with Ctrl-V, nor with Shift-Insert.

### Expected behaviour

It should be possible to paste new information into the note field. The same process (pasting of information) works in other fields in the edit window.

### Steps to reproduce the behaviour

Quite simply, copy some text to the clipboard, and try pasting the said text into the note field. 

### Support Ticket

Ticket#10128383

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@Suhopoljac duplicate of https://github.com/zammad/zammad/issues/4530 ?

**Comment by Suhopoljac** [comment]
@dominikklein, could be related, but I can't reproduce it anymore, it seems to have occurred with previous versions (5.3 & 5.4), with 5.4.1 it seems to be fixed. I am waiting for a reply from the customer who recently managed to reproduce the isuse on 5.4.1.

**Comment by Suhopoljac** [comment]
Closed as duplicate of #4530
