### ISSUE TITLE
UI style leaks into email body

### ISSUE THREAD

**Issue by i1yas** [zammad/zammad#4617]
### Used Zammad Version

5.3.1

### Environment

- Installation method: [docker](https://github.com/zammad/zammad-docker-compose/tree/master)
- Operating system: Debian 11
- Database + version:  postgresql 9
- Elasticsearch version: 8.5.1
- Browser + version: chrome 113

### Actual behaviour

There is a trigger with email notification. I added email body for that trigger.

Recieved email has grey color body.
![image](https://github.com/zammad/zammad/assets/9597415/89d7538a-a475-42a2-96e3-41d4c8eacb1f)
This makes text unreadable on white background.
![image](https://github.com/zammad/zammad/assets/9597415/f5c6a2f4-ac69-41fd-a1d7-c31b2aa081f9)
Turns out it's the same styles zammad has in it's UI. Seems like script copies form content as is.

Note: I am using dark theme in zammad.

### Expected behaviour

The email body should not have styles from zammad UI.

### Steps to reproduce the behaviour

1. Create trigger with email notification on task state change.
2. Trigger notfifcation by chaning state of the task.
3. Check email

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
> 5.3.1

Zammad 5.3.1 is outdated, we're currently at 5.4.1 which is a security release. Upgrade your installation asap and try again. Please note that only current stable instances are supported.

**Comment by i1yas** [comment]
Upgraded to 5.4.1, problem solved. Thanks! :+1:
