### ISSUE TITLE
Setup asks for FQDN, but doesn't write to DB

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#462]
When I set up a new system, it asks me to enter the "SYSTEM URL":

![grafik](https://cloud.githubusercontent.com/assets/4621219/20607138/2f549512-b276-11e6-82af-dc1432601e4b.png)

My understanding was that this is the FQDN setting, which should be stored in the settings table, and re-appear under "Settings, System, Fully Qualified Domain Name". 

But that settings still shows "zammad.example.com" after finishing the setup process. Whatever I entered into "SYSTEM URL" before doesn't seem to get stored anywhere. 

Or maybe I misunderstood the meaning of this setting? Not sure.

**Comment by martini** [comment]
@olivergrahl Thanks, it's fixed now.
