### ISSUE TITLE
Possible Bug in Or condition

### ISSUE THREAD

**Issue by MrCybertux** [zammad/zammad#4628]
### Used Zammad Version

5.4.1

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 18.04.6 LTS
- Database + version:  PostgreSQL 10.23
- Elasticsearch version: 8.6.2
- Browser + version: firefox 102.11.0esr (64-Bit)

### Actual behaviour

I am not sure if i found a bug or not pleas close if it is a config error.
Listing only 13 Tickets when using Or condition for a overview when is should be 2120
Since Pictures say more then words:

![image](https://github.com/zammad/zammad/assets/67368875/a9be9091-2fa4-43b9-851c-af9d5c48d9cf)
 
![image](https://github.com/zammad/zammad/assets/67368875/02ae4da3-f6bb-4f84-89ee-47c9395757b9)

![image](https://github.com/zammad/zammad/assets/67368875/c73db4ad-73ef-42b0-ab84-207d55919cc4)

### Expected behaviour

2120 Tickets in the preview since one of the two conditions must be met.

### Steps to reproduce the behaviour

Create a overwiev and use the values owner and subscribe with a or condition to filter. 

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by rolfschmidt** [comment]
Hi @MrCybertux ,
is your system up to date? We had something similar a couple of weeks ago:

https://github.com/zammad/zammad/commit/be48ff89839e6efb77cf7609d2fcbe8f05044806

https://github.com/zammad/zammad/issues/4547

Sounds pretty like your bug. This should be fixed. Would you be kind enough to update your zammad and verify the issue again?

**Comment by MrCybertux** [comment]
> Hi @MrCybertux , is your system up to date? We had something similar a couple of weeks ago:
> 
> [be48ff8](https://github.com/zammad/zammad/commit/be48ff89839e6efb77cf7609d2fcbe8f05044806)
> 
> #4547
> 
> Sounds pretty like your bug. This should be fixed. Would you be kind enough to update your zammad and verify the issue again?

Hi @rolfschmidt 
Yes version 5.4.1 is the newest version right? 
To be 200% specific  5.4.1-1685129964.6c9a7f63.bionic is my version.

**Comment by MrGeneration** [comment]
![image](https://github.com/zammad/zammad/assets/6549061/6559069b-c91c-4e1e-92a4-9f5db313f13c)

Zammad uses rolling stables so just looking at the minor is not enough, your commit ID however is pretty recent (5 days old)
So your instance already has the patch of #4547

**Comment by rolfschmidt** [comment]
@MrCybertux I tried it on my local instance and my numbers seem good? Not sure what I am missing:

![image](https://github.com/zammad/zammad/assets/5445062/8cbc1e12-707f-469d-8086-c6dc6e9ec347)

![image](https://github.com/zammad/zammad/assets/5445062/a5460561-ec0a-43ba-9a3c-1a9e3b52851c)


![image](https://github.com/zammad/zammad/assets/5445062/1b54f499-6d3e-4fb9-a6ec-0cb1a63064b4)


Please provide proper steps to reproduce the error or try to reproduce it on a trial instance (https://zammad.com/en/getting-started) and link us the instance in this issue.

**Comment by MrCybertux** [comment]
> @MrCybertux I tried it on my local instance and my numbers seem good? Not sure what I am missing:
> 
> ![image](https://user-images.githubusercontent.com/5445062/242278882-8cbc1e12-707f-469d-8086-c6dc6e9ec347.png)
> 
> ![image](https://user-images.githubusercontent.com/5445062/242278945-a5460561-ec0a-43ba-9a3c-1a9e3b52851c.png)
> 
> ![image](https://user-images.githubusercontent.com/5445062/242279051-1b54f499-6d3e-4fb9-a6ec-0cb1a63064b4.png)
> 
> Please provide proper steps to reproduce the error or try to reproduce it on a trial instance (https://zammad.com/en/getting-started) and link us the instance in this issue.

I did the same thing as you and it did not work out like that 🤔 , but i will try to reprduce the error on a trial instance.
Could a rebuild of the search index be the solution?

**Comment by rolfschmidt** [comment]
Nope, the overview ticket selector works sql based.

**Comment by MrCybertux** [comment]
i do not know how, but now the selfhosted instance is working as it is supposed to be.
The only thing i did was reboot the instance. (Have you tried turning it off an on again?) 🤣
Thanks for all the effort!
