### ISSUE TITLE
KB: inheritance of permissions

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4629]
### Used Zammad Version

5.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When you change the permission of a KB category **everything** will be sent down the permission tree.

### Expected behaviour

When I change the permission of role A in a KB category only this permission will the sent down the permission tree.

### Steps to reproduce the behaviour

Create a KB category A.
Create two child categories B and C.

Give some KB permission two role D and E. Either editor or reader.

Change permission for role D in category C.

Change permission for E in category A. The previous change will be reverted for category C.

### Support Ticket

Ticket#10128459

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by guetlein** [comment]
Additionally, the same behavior occurs when creating a new zammad role after delegating some permissions in the KB. (Probably the same cause?)
