### ISSUE TITLE
Database zamma_prod doesnt not exist

### ISSUE THREAD

**Issue by novakin** [zammad/zammad#463]
Hi,

I've tried to install the latest stable version on a fresh Ubuntu 16.04.

I've used the following documentation: https://docs.zammad.org/en/latest/install-ubuntu.html?highlight=ubuntu

Unfortunately install fails 

`# database.yml not found. Creating db...
installing zammad on postgresql
creating zammad postgresql db
createdb: database creation failed: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)
HINT:  Use the same encoding as in the template database, or use template0 as template.
creating zammad postgresql user
CREATE ROLE
grant privileges to new postgresql user
ERROR:  database "zammad_production" does not exist
updating database.yml
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "zammad_production" does not exist`

Hope someone can help

Thx

**Comment by novakin** [comment]
Same problem occurs with the Debian package

**Comment by novakin** [comment]
OK I solved it, here is what I have done:

`sudo -u postgres psql postgres`


```
update pg_database set datallowconn = TRUE where datname = 'template0';
\c template0
update pg_database set datistemplate = FALSE where datname = 'template1';
drop database template1;
create database template1 with template = template0 encoding = 'UTF8';
update pg_database set datistemplate = TRUE where datname = 'template1';
\c template1
update pg_database set datallowconn = FALSE where datname = 'template0';
```

I deleted config/database.yml and I also needed to drop the table and user

```
postgres=# DROP DATABASE zammad_production;
DROP DATABASE
postgres=# DROP USER zammad;
DROP ROLE
postgres=# \q
and then sudo /opt/zammad/contrib/packager.io/postinstall.sh
```

Now it's working

**Comment by monotek** [comment]
What locale is set in your system?

For the docker image i had to this before:

```
apt-get install locales
locale-gen en_US.UTF-8
echo "LANG=en_US.UTF-8" > /etc/default/locale
```

**Comment by novakin** [comment]
Locales were not configured, may come from that

**Comment by monotek** [comment]
Ok. So i close this issue... 
Setting locales is nothing which should be done by the Zammad installer.
