### ISSUE TITLE
web.de: 554 Nemesis ESMTP Service not available Transaction failed Reject due to policy restrictions.

### ISSUE THREAD

**Issue by davidbuzzard** [zammad/zammad#4630]
### Used Zammad Version

5.4.1-1685129964.6c9a7f63.centos8

### Environment

- Installation method: package
- Operating system: rocky 8.8 (centos 8)
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Emails sent to a web.de address are rejected with following message:
> 554-Transaction failed 554-Reject due to policy restrictions. 554 For explanation visit https://postmaster.web.de/en/case?c=hi

Linked website states:
> 554 Nemesis ESMTP Service not available Transaction failed Reject due to policy restrictions.
>
>Please note that, if your email header is not RFC 5321 and RFC 5322 compliant, your message will be rejected by our system.
>
>This includes the following:
>
> - The following email headers included in your message must be syntactically correct: Date, From, Sender, To
> - The following headers included in your email must be limited to just one each: BCC, CC, Date, From, Sender, Subject, To
>
> Therefore, we would advise you to check that the above mentioned information provided by your system is correct. Should you need additional support, please contact your System Administrator.

(I hope this is a known issue that already can be resolved, but I found no hits for Zammad with web.de here or in the community board. Thanks!)

### Expected behaviour

No rejection.

### Steps to reproduce the behaviour

Answer an incoming mail from a web.de address.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Please provide an anonymized  version of an affected mail because other wise this one is impossible to verify.

**Comment by davidbuzzard** [comment]
This is an email file attached to such a mentioned rejection email. I hope I didn't under- or overdid the anonymization...

[example.eml](https://github.com/zammad/zammad/files/11611586/example.eml.txt)

Let me know if you need more info. Thanks for looking into it!

**Comment by MrGeneration** [comment]
This mail is not being sent via web.de directly right?
The mail you provided is syntactically correct and the way I expect it to be.

If web.de is refusing these mails, either your mail server is potentially adding carberage (if you answered above with yes) or having some trouble / giving misleading refusal reasons.

**Comment by davidbuzzard** [comment]
No, our mail is not sent via web.de, it's being rejected by them and our mail daemon returned the mail along with the error message received as it should.

Yes, web.de might well be giving misleading refusal reasons. I see now that the text by web.de allows for such ambiguity, not spelling out what their policy includes aside what's written. And services by United Internet AG (like web.de is one) are known to regularly cause such issues. So I'm closing this again. Thanks for looking into this!
