### ISSUE TITLE
Customer is set to recipient of mails instead of sender when using local address extension

### ISSUE THREAD

**Issue by eheinle-mak** [zammad/zammad#4632]
### Used Zammad Version

5.4.1

### Environment

- Installation method: Docker Container `zammad/zammad-docker-compose:zammad-5.4.1`
- Operating system: Ubuntu 20.04.6 LTS (Focal Fossa)
- Database + version: postgresql 14
- Elasticsearch version:7.17
- Browser + version: Chrome Version 113.0.5672.126 (Official Build) (64-bit)

### Actual behaviour

As any customer, when I write an email to a gmail account configured in zammad but add a `+something` part to the email address (local address extension), e.g. `ops+floriantestetwas@makandra.de`, the mail has the _recipient_ as the customer. Subsequent replies in zammad to this ticket will be sent to the initial _recipient_ of the mail. As the original customer, I never get the email reply.

### Expected behaviour

When I send an email as a customer and agents reply from within zammad, I want to receive their replies to my email address. I should be set as the customer in zammad.

### Steps to reproduce the behaviour

1. Have mail address `customer@customersdomain.tld` 
1. Create an account in Zammad, e.g. GMail (since it supports local address extension. Other providers and mail servers do as well) for `foo@bar.tld`
1. Create group `team-a`
1. Add a filter:
  - `Delivered-Too contains foo+team-a@bar.tld`
  - Assign Group `team-a`
  - Configure related overview that shows mails for Group `team-a`

Now:
1. Write an email to `foo+team-a@bar.tld`
1. Inspect Zammad ticket and see that customer is `foo+team-a@bar.tld` instead of `customer@customersdomain.tld`

Explanation: We use local address extensions to allow tagging of mails to our support mail address so customers can pre-select which team receives the ticket.

[excerpt_scheduler.log](https://github.com/zammad/zammad/files/11633714/excerpt_scheduler.log)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by t-shehab** [comment]
Hi @fheinle-mak,

thanks for your patience, and thanks for opening this issue.

In the current version (6.2) I cannot produce the exact same results you're experiencing. The customer gets set to the sender of the email. However, some unwanted behaviour still happens. I have created a separate issue for this and will therefore close this one. All further discussion will take place at: https://github.com/zammad/zammad/issues/5005
