### ISSUE TITLE
RTL not working in mobile view editor field

### ISSUE THREAD

**Issue by YosefAdPro** [zammad/zammad#4640]
### Used Zammad Version

6.0

### Environment

- Installation method: [e.g. source, package] any
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] Mobile App

### Actual behaviour

When using the Hebrew language, when typing in mobile mode, the text is on the left side. 

![Screenshot_20230607_075415_Chrome](https://github.com/zammad/zammad/assets/11810187/eff70976-ede4-4fcd-8d9f-bbf91ecb9cef)

### Expected behaviour

The text is on the right 

### Steps to reproduce the behaviour

.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by YosefAdPro** [comment]
Can the patch be included in the rolling version?

**Comment by fliebe92** [comment]
> Can the patch be included in the rolling version?

Hey @YosefAdPro, the fix is also included in `stable` :)
