### ISSUE TITLE
Duplicate detection does not work for customer

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4643]
### Used Zammad Version

6.0

### Environment

- Installation method: SaaS
- Browser + version: Firefox 113.0.2

### Actual behaviour

I enabled duplicate checking for "Customer" and "Customer, Title". Both scenarios displayed a warning, when creating a matching ticket as an agent, but not when creating the ticket as the customer.

### Expected behaviour

When I choose "Customer, Title" as a duplicate detection method, I want the customer to be warned, if he/she is about to create a new ticket with the same title as one of his/her previous tickets.

### Steps to reproduce the behaviour

Choose "Customer" and "Title" as the attributes to compare:
![grafik](https://github.com/zammad/zammad/assets/97293098/f81bad1c-45f8-4dbf-9286-62d78fd608a4)

Login as a customer and try to create two tickets with the same title. No warning will appear.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by abdellani** [comment]
Hi !
I want to work on this :)

**Comment by Duenielsun** [comment]
[https://admin-docs.zammad.org/en/latest/settings/ticket.html#duplicate-detection](https://admin-docs.zammad.org/en/latest/settings/ticket.html#duplicate-detection) says:

"You can limit the detection only to certain user roles. By default, only agents will see the warning."

Have you changed the default detection roles?

**Comment by fliebe92** [comment]
> https://admin-docs.zammad.org/en/latest/settings/ticket.html#duplicate-detection says:
> 
> "You can limit the detection only to certain user roles. By default, only agents will see the warning."
> 
> Have you changed the default detection roles?

Hi @Duenielsun, I think the report is about having the `customer` information part of the attributes that should be checked for a possible duplicate.

**Comment by Duenielsun** [comment]
> > https://admin-docs.zammad.org/en/latest/settings/ticket.html#duplicate-detection says:
> > "You can limit the detection only to certain user roles. By default, only agents will see the warning."
> > Have you changed the default detection roles?
> 
> Hi @Duenielsun, I think the report is about having the `customer` information part of the attributes that should be checked for a possible duplicate.

Hi @fliebe92, he wrote
> Login as a customer and try to create two tickets with the same title. No warning will appear.

So I think, he wishes, that the customer can show the duplicate-warning...

Regards
DuenielSun

**Comment by YetAnotherGerrit** [comment]
> Have you changed the default detection roles?

Yes, I have:
![grafik](https://github.com/zammad/zammad/assets/97293098/ebe26390-ee62-4eeb-97d5-4be9850414b5)

> Hi @Duenielsun, I think the report is about having the customer information part of the attributes that should be checked for a possible duplicate.

Both, see above and here:
![grafik](https://github.com/zammad/zammad/assets/97293098/a123b248-4772-4799-8bc6-e88c282275d8)
