### ISSUE TITLE
Zammad SMTP Error on Spam Mails

### ISSUE THREAD

**Issue by lmarschall** [zammad/zammad#4645]
### Used Zammad Version

5.4

### Environment

- Installation method: package
- Operating system: ubuntu 20.04 lts

### Actual behaviour

At the moment we monitor our Zammad Helpdesk with Prometheus, and we keep getting the following health check fails:

{"healthy":false,"message":"Channel: Email::Account out Can't use Channel::Driver::Smtp: #\u003cNet::SMTPFatalError: Net::SMTPFatalError\u003e","issues":["Channel: Email::Account out Can't use Channel::Driver::Smtp: #\u003cNet::SMTPFatalError: Net::SMTPFatalError\u003e"],"actions":[],"token":"TOKEN"}

Further investigation shows the following error in the logs:

I, [2023-05-10T00:02:50.651443#769-12175960] INFO -- : fetching imap (IMAP INFO)
E, [2023-05-10T00:02:51.187924#769-112440] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: Net::SMTPFatalError>
E, [2023-05-10T00:02:51.187998#769-112440] ERROR -- : 550 5.1.1 host gmail-smtp-in.l.google.com [66.102.1.27] said: The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser az39-20020a05600c602700b003f196de07e6si9893008wmb.29 - gsmtp (H-BADRCPT)
E, [2023-05-10T00:02:51.318211#769-112440] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: Net::SMTPFatalError>
E, [2023-05-10T00:02:51.653062#769-112440] ERROR -- : 2023-05-10T00:02:51+0200: [Worker(HOST)] Job TicketArticleCommunicateEmailJob [] from DelayedJob(default) with arguments: [7336] (id=3121012) (queue=default) FAILED (3 prior attempts) with RuntimeError: Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: Net::SMTPFatalError>
E, [2023-05-10T00:02:51.653189#769-112440] ERROR -- : 2023-05-10T00:02:51+0200: [Worker(host:ticketsystem pid:769)] Job TicketArticleCommunicateEmailJob [] from DelayedJob(default) with arguments: [7336] (id=3121012) (queue=default) FAILED permanently because of 4 consecutive failures

It seems like when the zammad system wants to send out emails, which appear to be spam mails and can't send them properly it fails permanently. Can we deactivate this behavior in the settings eventually?

### Expected behaviour

Failing the healthcechk because emails can't be send is a bit odd.

### Steps to reproduce the behaviour

Can't really reproduce, we have to wait for spam mails I guess.

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by mgruner** [comment]
@lmarschall thanks a lot for the report. Let's wait until we have a reproducible state here, by providing an email that is able to trigger such behaviour.
Without that, we are not able to work on this issue. Please reopen it when more details are available.
