### ISSUE TITLE
Link in agent notification email does not work properly (mobile-view)

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#4655]
### Used Zammad Version

5.4

### Environment

- Installation method: package
- Operating system Debian 10.4
- Database + version: PostgreSQL 9.3
- Elasticsearch version: 7.17
- Browser + version: Mobileview

### Actual behaviour

When an agent receives a notification via email and clicks on the link "View in Zammad Helpdesk"

When the ticket is created and this is the first notification, Zammad Mobile APP opens the ticket.
When this is the second notification regarding the same ticket, the Mobile APP open only the overviews in the Mobile APP.

### Expected behaviour

I would expect that the link always opens the ticket, no matter what.

### Steps to reproduce the behaviour

Create a ticket and assign it to an agent.

The agent needs to have Zammad Mobile APP installed on his phone.

- open the Mail client on the mobile device
- click on the link "View in Zammad Helpdesk" in the agent notification email
- update the ticket with a different user (this way the agent will get a notification via email again)
- click on the link "View in Zammad Helpdesk" in the agent notification email

### Support Ticket

Ticket#10130861

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@Bozo0511 Would be nice to have the current links present in the issue.

**Comment by Bozo0511** [comment]
Link 1 (this link is working as expected)
https://herewego.zammad.com/#ticket/zoom/85

link 2 (this link is leading to the overview)
https://herewego.zammad.com/#ticket/zoom/85/282

Only when the ticket is created, the first link is leading to the ticket. Even after I try the same link again, I land in the overview
