### ISSUE TITLE
Search result is not shown if you search for "AAA", "BBB" and "AAA" again.

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#466]
We discovered a small timing issue, which hides the search results.

way to reproduce the issue:

1. paste a string into the ticket search field, search results appear
2. click anywhere in the ticket area on the right side, so the search field loses focus
3. **paste** a new string into the search field, the search is executed, but the result is not shown

**Comment by martini** [comment]
Fixed in 1.0, 1.1 and develop https://github.com/zammad/zammad/commit/550b963ad0bd54f223a0645c3bc1e07278fd1ff1.
