### ISSUE TITLE
Make exchanging organization in existing tickets after updating the primary organization of a user configurable

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4660]
### Summary (What)

When you change the primary organization of a user, all existing tickets are changed to that organization.

In a lot of cases, when someone changes his/her organization, their tickets don't move with them. Let's say you change the department within your company. Your old "old department"-tickets don't become "new department"-tickets out of the sudden.

### Intended Outcome

An administrator should have more control over the Zammad system by being able to influence the behavior. We hope that more use cases can be reflected with this change.

### How will it work

We are going to introduce a new setting that is used to control the behavior of exchanging organizations in existing tickets globally in the system.

In the GUI, it would be nice if there is a hint showing that updating the primary organization leads to a mass update of a lot of tickets.

**Comment by KoJie** [comment]
**comment from review-meeting 03-07-23:**
The note in the "User Edit Form" that tickets are also changed when the organization is changed should be clearly displayed. This is to point out explicitly to an agent what will happen when he saves a change to the organization. A hint hidden in the help field is not sufficient.

**Comment by dominikklein** [comment]
> The note in the "User Edit Form" that tickets are also changed when the organization is changed should be clearly displayed. This is to point out explicitly to an agent what will happen when he saves a change to the organization. A hint hidden in the help field is not sufficient.

Like explained in the morning, currently we have here a form limitation with the autocomplete field, which leads to the situation that it's not easily possible to show this in a different way. In the mobile view, it's already visible in a good way, and with the new desktop-view we want also to implement this inside the edit form in a better way.
The current implementation was designed as an easy solution, but when you really think we should add much more effort here, this should be created was a follow-up and we should not reopen this issue here.

**Comment by YetAnotherGerrit** [comment]
Since at least last Thursday, the latest stable branch has behaved differently already. Now organisations are not changed, per default. This is a breaking change. It was like that in Jacek's training and also in Today's training.

P.S.: In both cases, it was package installation on Debian 11.

**Comment by mgruner** [comment]
There was no change about that in `stable`, @YetAnotherGerrit. It would be more bug/regression.

**Comment by YetAnotherGerrit** [comment]
Yes, I figured that and created an issue.
