### ISSUE TITLE
Visiting any /#ticket/view link while not signed in only shows a blank page and does not redirect to login screen

### ISSUE THREAD

**Issue by Stubenhocker1399** [zammad/zammad#4664]
### Used Zammad Version

 6.0.0-1686341484.c00b581a.focal

### Environment

- Installation method: [e.g. source, package] ubuntu package
- Operating system (if you're unsure: `cat /etc/os-release` ):  ubuntu 20.04
- Database + version:  postgresql 12
- Elasticsearch version: irrelevant
- Browser + version:  chrome 114

### Actual behaviour

Visiting a zammad link under /#ticket/, such as /#ticket/view/incoming or similar while logged out doesn't result in a redirect and instead only presents a blank page.
![Screenshot_20230615_215740](https://github.com/zammad/zammad/assets/6693160/658f262e-cc2a-427e-a7b5-8a1825db93ba)

### Expected behaviour

Visiting a zammad link under /#ticket/, such as /#ticket/view/incoming or similar while logged out results in a redirect to the login screen, similar to /#dashboard
![Screenshot_20230615_215857](https://github.com/zammad/zammad/assets/6693160/f9b03ba1-ee63-48b0-8a13-7ef2da5d7502)

### Steps to reproduce the behaviour

1. Open up a new incognito window or sign out of your Zammad instance
2. Visit <yourInstance>/#ticket/
3. Don't get redirected to login page

Other affected urls:

```
    #ticket/create
    #ticket/create/customer/{id}
    #ticket/view/all_unassigned
    #user/profile/{id}
```

### Support Ticket

Ticket#10133147, #10133781, #10136121, #10136926

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by martini** [comment]
Update: It also appears on Zammad 6.1.

IMO the following URLs are effected

```
 #ticket/create
 #ticket/create/customer/{id}
 #ticket/view
 #ticket/view/{view}
 #user/profile/{id}
```

IMO `#ticket/` is not affected since it's no valid route.
