### ISSUE TITLE
Inactive customers continue to receive trigger mails when agents update the ticket 

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4665]
### Used Zammad Version

6.0

### Environment

- Installation method: any
- Operating system any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge v.114.0.1823.43 (64-Bit)

### Actual behaviour

Depending on the conditions of the trigger, the inactive customer will continue to receive trigger emails even though his account has been deactivated and that no further notifications should be sent to him.  

### Expected behaviour

When defining a trigger, there should be an option to mark when the customer is inactive that no trigger email should be sent to them. 

### Steps to reproduce the behaviour

Click on Admin area --> Manage --> Trigger 
When defining the trigger conditions, scroll down to the Customer part: 
<img width="594" alt="Test1" src="https://github.com/zammad/zammad/assets/101350124/657bb660-524f-4ae3-8ed9-eb65b777eb26">

You can select something like when the customer was created or updated, but not whether the customer profile is active or not. 

### Support Ticket

Ticket#10131124

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
I think inactive users should never receive notifications in the future, there should not be an option needed.

**Comment by martini** [comment]
Background information (there was already a discussion years ago):

Inactive user means, that the user can not login to Zammad anymore. And from agent point of view inactive users are shown in Zammad as inactive (this is important).

So inactive user means: It's inactive for e. g. support services.

But inactive users can still get used for new tickets (for example if the support contract ended but the user has a general question - not related to support). And also can create new tickets e. g. via email.

**Comment by dominikklein** [comment]
Oki, I think now I can follow more, the problem is that the "active" field is not available below the customer inside the conditions.
When this is the real problem, we should change the description of the issue.

**Comment by martini** [comment]
> Oki, I think now I can follow more, the problem is that the "active" field is not available below the customer inside the conditions.
> When this is the real problem, we should change the description of the issue.

Yes. This is the problem. Just the attribute `customer.active` (and in addition also `organization.active`) inside of the conditions.
