### ISSUE TITLE
Object manager attribute with a link template generates a wrong target for the link

### ISSUE THREAD

**Issue by t-shehab** [zammad/zammad#4666]
### Used Zammad Version

6.0

### Environment

- Installation method: any (verified in SaaS and local package install)
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When you configure a ```linktemplate``` in an Object Attribute, the generated link will always open in the same tab (target="blank").

### Expected behaviour

When you configure a ```linktemplate``` in an Object Attribute, the generated link will always open in a new tab (target="_blank").

#### Configure an Object Attribute like so:

![image](https://github.com/zammad/zammad/assets/114283486/8e1cd759-7e67-45dd-ab48-d8f01c811310)

#### On an Object that the Attribute was created for, enter some text into the Attribute's field:

![image](https://github.com/zammad/zammad/assets/114283486/1faab8d0-555d-4dff-9d9e-e089722caa15)

#### Inspect the generated link in your Browser's developer console:

![image](https://github.com/zammad/zammad/assets/114283486/1696e7ec-cd08-4e56-8317-f12a7460a2db)

### Support Ticket

Ticket#10130371

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
It's important that this is about the detail view of the user/organization and not the object attributes in general inside the forms:

https://github.com/zammad/zammad/blob/7de5ec90370d7ef0d8f89e6ce9ace63ef6fc201d/app/assets/javascripts/app/index.coffee#L169
