### ISSUE TITLE
Redis dependencies on package partly non existing / non optimal

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4668]
### Used Zammad Version

6.0

### Environment

- Installation method: package only
- Operating system (if you're unsure: `cat /etc/os-release` ): All supported package distros
- Database + version:  postgresql
- Elasticsearch version: any
- Browser + version: not applicable
- Appeared via: https://community.zammad.org/t/zammad-upgrade-5-4-1-to-6-0-redis-not-installed/11567

### Actual behaviour

- CentOS 7 and 8 are fine and solvable via the provided documentation requirements (including epel-release for v7); manual activation and enabling required though
- ubuntu 16 does not have a redis package at all; -> `redis-server`
- debian 10, 11 and ubuntu 18, 20, 22 auto select `redis-server` when using `redis`, however, smaller footprint would be `redis-server`; redis is activated and started automatically
- suse leap 42.3 and leap 15.5 have no official packages for redis-server. There is an redis package which has a nun functional service (or I was not clever enough): https://software.opensuse.org/package/redis-server?search_term=redis-server

  This means that the documentation clearly has to hint about this issue and most likely requires source code installations (redis wise) . (this is also a huge  issue because we have customers on sles (hard stuck))

### Expected behaviour

Package requirements try to aim for the smallest footprint required.

### Steps to reproduce the behaviour

Install all supported package distributions in base / minimal and try to install redis as per current package dependency.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Side note on that regard, especially with sles package the enforcement of a locally running redis-server (commit 52e5a094820e7ea6e24e9ae677e18a2a21ec056a ) might be a big issue depending on how the admin wants to solve it (source / third party server / docker version).

**Comment by tschaefer** [comment]
Fixed in https://github.com/zammad/zammad/commit/f4a01a7a17a996747f389015bc025bd55c11b4af
