### ISSUE TITLE
Failed upgrade from 5.3 to 5.4 by "missing DB constraint"

### ISSUE THREAD

**Issue by lasat** [zammad/zammad#4669]
### Used Zammad Version

5.4

### Environment

- Installation method: zammad-docker-compose images
- Database + version:  postgresql 9.3
- Elasticsearch version: 8.5.1

### Actual behaviour

Upgrade from 5.3.1-54 to 5.4.1-38 failed during DB migration on migration step 20230129220648_taskbar_update_preference_tasks.rb with "User must exists"

### Expected behaviour

Migration should succeed and column taskbars.user_id should reference user.id.

### Steps to reproduce the behaviour

1. Insert an taskbars entry for a non existing user_id before migrate to zammad 5.4
2. try migration to 5.4
3. migration failed
4. delete taskbar entries wit non existing user_ids
5. retry migration
6. migration succeed

In my case there were taskbar entries for user_id's not existing in users table. After executing `delete from taskbars where user_id not in (select id from users where id in (select distinct user_id from taskbars));` the migration succeed.

I'm not sure where these user were deleted but assume that thes happens during "data privacy"-deletion.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @lasat,

> Insert an taskbars entry for a non existing user_id before migrate to zammad 5.4

Can you please explain this in more detail? What exactly did you do?

**Comment by pakagi** [comment]
Yes looks similar. But in my case it was working fine on 5.4.1, and appeared after upgrade to 6.0.0.

**Comment by fliebe92** [comment]
We are closing due to no feedback. 

Feel free to comment on this issue. I'm happy to reopen it.
