### ISSUE TITLE
LDAP config is applied in dry run

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4674]
### Used Zammad Version

6.0

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian 11
- Database + version:  psql
- Elasticsearch version: 7.17
- Browser + version: Edge

### Actual behaviour

When configuring LDAP the settings are applied on the dry run, instead after confirming the numbers.

### Expected behaviour

The dry run makes no modifications to the existing user database.

### Steps to reproduce the behaviour

Create a user in the user database manually, with an email address that exists in the LDAP directory.
Disable the LDAP module.
Add an LDAP source.
In the Role-mapping choose a mapping that does NOT match with the above user.
In Expert settings choose "No synchronize".
The above user will be disabled in the dry run, but it should only be disabled in the "real run". And only if the LDAP module is activated.

### Support Ticket

Ticket#10126111

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@YetAnotherGerrit Is there any additional trick needed to reproduce the problem? I'm currently not able to reproduce the situation with the steps.

**Comment by t-shehab** [comment]
@dominikklein,

no additional trick is needed. I have just verified the behaviour independently.

Users are disabled in Zammad via an LDAP-Sync dry-run with LDAP integration switched off.

I have a test system ready to show you, if required.
