### ISSUE TITLE
Trigger fails to set custom timestamp on report

### ISSUE THREAD

**Issue by Hanswtf** [zammad/zammad#4677]
### Used Zammad Version

5.2.1

### Environment

- Installation method: Package
- Operating system: Alma8.6
- Database + version:  postgresql 14.4
- Elasticsearch version: 7.17
- Ruby: 3.0.4
- browser: tested on chrome and firefox

### Actual behaviour

Creating a trigger to add a timestamp on a custom object when a ticket is moved to a custom ticket state does not work. The field is set to nill. It does not show in reports or ticket history.

### Expected behaviour

Creating a trigger to add a timestamp on a custom object when a ticket is moved to a custom ticket state should set the current date/time on the object for reporting purposes.

### Steps to reproduce the behaviour

1.	Create a custom ticket state of type "open", call it "completed". 
2.	Created a custom date/time Ticket object with a time diff of 1 minute call it “Completion Date”.
3.	Created a trigger with conditions “State-is-completed” to execute “Completion Date-relative-1-Minutes”
4.	Change the state of a new/open ticket to completed and the value remains nill.
5.	View community support forum ticket for screenshots: https://community.zammad.org/t/custom-ticket-state-reporting-timestamps/10858/3

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
> 5.2.1

Update to an up to date Zammad installation and check again.
Only current stable versions are supported and thus we won't verify this bug report until you ensured that it's happening on 6.0 as well. The verification I have done in the community was based on 5.4.1.

**Comment by Hanswtf** [comment]
Thanks for the feedback

I updated our zammad to V6:
![image](https://github.com/zammad/zammad/assets/127505460/d356a8d4-cc36-4eb9-91f0-4bb279aa67d5)

The problem still perists:
![image](https://github.com/zammad/zammad/assets/127505460/4f447db3-7893-49a3-938f-422f710f5b80)

Trigger conditions:
![image](https://github.com/zammad/zammad/assets/127505460/f1320797-f3fb-41ba-a5ea-fbfb663f6fc8)


Regards

**Comment by Hanswtf** [comment]
Thank you Gentlemen.
