### ISSUE TITLE
auto reply (on new tickets) Mail : contains wrong hyperlink https://zammad.com instead of configured FQDN

### ISSUE THREAD

**Issue by IQ86517** [zammad/zammad#4678]
### Used Zammad Version

6.0.0-1687441991.d5fd26cf.bullseye

### Environment

**Installation method: [e.g. source, package]**
via Package manager

**Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]**
Debian 11

**Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]**
Postgresql 13

**Elasticsearch version: [e.g. 7.17]**
7.17.10

**Browser + version: [e.g. chrome 83, safari 14, firefox 105]**
Not dependend on the Browser used

### Actual behaviour

The link to Zammad in the autogenerated response mail (auto reply on new Tickets) is refering to zammad.com - not the configured FQDN of the Zammad instance.

![thanks for your inquiry](https://github.com/zammad/zammad/assets/137497018/27af1e96-fdb0-4639-83ba-b4178cebc201)

if i use #(config.fqdn) in the mail "template" the correct FQDN is shown. But it's not a nicely formated link.
![image](https://github.com/zammad/zammad/assets/137497018/4443fb00-084b-4038-a4b5-b0d65b8db185)

### Expected behaviour

The provided link in the mail "Auto Reply(on new  Ticket)" should point to the correct ticket at least to the correct FQDN - Not to https://zammad.com.

### Steps to reproduce the behaviour

Create a new Ticket as a Customer and Check the Response Mail you receiver from Zammad.

### I'm sure this is a bug and no feature request or a general question.

yes, we did not notice such behaviour in Zammad 5.4

**Comment by fliebe92** [comment]
Hi @IQ86517, can you please give us more information?

With the current information, we simply do not know what you are doing, or what your configuration of this trigger looks like, ...

Thanks a lot.

**Comment by IQ86517** [comment]
No Problem.

does this screenshot help?

![image](https://github.com/zammad/zammad/assets/137497018/f1605ab7-1d90-49f9-9c26-90b88523bebb)

The Mail Body contains a Hyperlink in the last scentence "Zammad, your customer support System"
the "Zammad" Part is a hyperlink and will redirect to "https://zammad.com".

if my memory serves me right this link used to refer to the configured FQDN of the Zammad instance.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by fliebe92** [comment]
@IQ86517> Just to give some more (technical) information: The line you're referring to is present since April 26th, 2017 1:28 PM.

Reference: https://github.com/zammad/zammad/blob/46999677bc5f45349819948c7772b4bda2a5afa7/db/seeds/triggers.rb#L37
