### ISSUE TITLE
"Password has been changed" email contains unresolved placeholders

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#468]
After requesting a password reset email for a customer account, I clicked the link received and entered a new password. 

Next, I received this notification that contains some placeholders which did not get resolved as expected:

![grafik](https://cloud.githubusercontent.com/assets/4621219/20671229/d0d6d536-b57c-11e6-99ff-c3931e8f9306.png)

My product_name setting seems to be set correctly, and gets used otherwhere as expected (i.e. page titles).

**Comment by martini** [comment]
Thanks! It's fixed to 1.0, 1.1 and develop. https://github.com/zammad/zammad/commit/6742fd0348704fb20b80134bbd81cd1b4fa72cb2
