### ISSUE TITLE
After update to Zammad 6.0.0 brand logo is broken (only docker version)

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad#4682]
Please see: 
- https://community.zammad.org/t/after-update-to-zammad-6-0-0-brand-logo-is-broken-only-docker-version/11654
- https://github.com/zammad/zammad-docker-compose/issues/354

The issue is probably that the nginx container now only has the default /opt/zammad file system, and never runs the Rails initializer that writes the logo file to assets/ for this container.

**Comment by mgruner** [comment]
Fixed by 63a731c.

**Comment by thmo** [comment]
Needs a restart of the docker container though after changing the brand logo, otherwise a broken logo (resp. the alt text) is displayed.
