### ISSUE TITLE
Create email addresses for groups

### ISSUE THREAD

**Issue by corny** [zammad/zammad#469]
The email field in the the create/edit view of groups is empty and I can't find a way to fill it. How do I create email addresses for groups? Instructions should be added at least to the documentation.

I receive emails via `Channel::Driver::MailStdin` and not via POP3/IMAP.

**Comment by hanneshal** [comment]
This is related to: 
https://github.com/zammad/zammad/issues/224

An account is needed to get an email address, which can be assigned to a group
