### ISSUE TITLE
Add option to allow Authentication via SSO to match by email

### ISSUE THREAD

**Issue by Wardrop** [zammad/zammad#4690]
### Used Zammad Version

6.0.0

### Environment

Not applicable

### Actual behaviour

When using SSO authentication (which enables the /auth/sso endpoint), the "X-Forwarded-User" header is only matched against the users "login" value. This a problem as this value can vary depending on how their account was created. For example, users that were initially added because they sent an email into Zammad, have their email address set as their "login" value, where as users who initially signed in via Microsoft 365 have a GUID as their "login".

So if the "X-Forwarded-User" uses the users email address, it'll only match those users whos "login" is their email. If "X-Forwarded-User" instead uses the user's GUID, then it'll only match those users who initially logged in with Microsoft 365.

### Expected behaviour

I'd like to propose that the SSO authentication handler checks both the "login" field and "email" field of the user, or at least adds this as a configurable option. Users in Zammad have to have a unique email address, so the users email address field can be relied upon for this purpose. "email" is always set to a consistant value and format, so this way the "X-Forwarded-User" header can be set as the users email address knowing it'll reliably match any user in Zammad with that email if the user exists. 

I raise this as a bug as I feel it's closer to a bug or oversight than a "feature request".

### Steps to reproduce the behaviour

N/A

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
