### ISSUE TITLE
Size of inline images in mails from Zammad are not shown correctly in Microsoft mail clients

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#4691]
### Used Zammad Version

6.0.0

### Environment

- Installation method: any
- Operating system: Windows
- Database + version: any
- Elasticsearch version: any
- Browser + version: 

### Actual behaviour

Reply to a email, copy and paste a large image into the Zammad Web App editor and then resize it (e. g. smaller), the new height and width values are stored as CSS inline on the <img>-tag (also in the sent out email).

![Bild1](https://github.com/zammad/zammad/assets/129729908/f929744d-bb71-4c0e-bbac-9c1fe1f84177)

Unfortunately, on Outlook or Microsoft-Mail clients the images size is not shown correctly (on any other email clients it works nice

![Bild2](https://github.com/zammad/zammad/assets/129729908/31cbb6d6-ed0e-40e4-9b25-72227ba40596)
).

Background: Outlook or Microsoft-Mail expects the image size as seperate attributes in the <img>-tag like `<img width="100" height="100">` (it's ignoring image size information in inline css like `<img style="width 100px; height: 100px;">`). 

### Expected behaviour

The image in Outlook and Microsoft-Mail is displayed correctly (even if it is reduced size).

### Steps to reproduce the behaviour

* Create a new Mail Ticket in Zammad
* Copy and Paste a Image into the Editor
* Resize the Image with the Mouse (smaller bright and witdh)
* Send the Mail to a Microsoft Mail or Outlook User
* In the Microsoft Mail-Client the Image will shown the same size before making it smaller

[ticket-10122-286.txt](https://github.com/zammad/zammad/files/15416811/ticket-10122-286.txt)

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by martini** [comment]
I think it's actually a bug in Outlook and Microsoft Mail.

Unfortunately, it affects a lot of Zammad users.

I suggest implementing a workaround in Zammad that fixes the bug in Outlook and Microsoft Mail.

The workaround could be that we also add `width` and `height` as attributes in the `<img>-tag` for outgoing emails.

**Comment by tschaefer** [comment]
Snippet from outgoing mail.

`<img style="width: 347px; max-width: 100%; height: 195.188px;" src="cid:3.b1d86599-cc69-4e35-a148-37c5
22b439c4@localhost:3000">`

**Comment by fliebe92** [comment]
We tested this again in Microsoft Outlook (Windows + Mac) and outlook.com. No chance to reproduce it, therefore we're closing it for now.

Feel free to re-open it again when it happens in the future.

**Comment by martini** [comment]
Did you test it with the example email above? What outlook version did you test? On my site it's still reproducible.

Just let me know if I can help with something.

![outlook1](https://github.com/zammad/zammad/assets/110226/6996885d-b184-45b4-9248-e27f48f55e9b)
![outlook2](https://github.com/zammad/zammad/assets/110226/1eea1200-edf7-47be-85c5-efaf587b006b)
![outlook-version](https://github.com/zammad/zammad/assets/110226/fec96b78-0154-41c0-b3ea-48bb46ac8f13)

compared to apple mail

<img width="951" alt="Screenshot 2024-05-23 at 18 55 27" src="https://github.com/zammad/zammad/assets/110226/f2c56608-990a-418e-bfdf-270c609618d1">

**Comment by MarkusHeld** [comment]
We have now tested further and come to the following results.

The problem is reproducible with (old) windows mail app

![2024-05-24 10_32_38-Posteingang – Gmail 2 _- Mail](https://github.com/zammad/zammad/assets/129729908/113f4032-2eda-451a-81bd-4ad05bf228db)

![2024-05-24 10_31_59-OneNote for Windows 10](https://github.com/zammad/zammad/assets/129729908/2e09cc64-d64b-4b8e-99b2-c0cfd3103c56)

and with the (new) outlook app the image is displayed correctly

![2024-05-24 10_34_37-OneNote for Windows 10](https://github.com/zammad/zammad/assets/129729908/b158432a-6fee-47af-812f-6b24cd3eb49f)

![2024-05-24 10_34_13-OneNote for Windows 10](https://github.com/zammad/zammad/assets/129729908/f69c96a0-4b87-4158-9da3-f53bb9856479)
