### ISSUE TITLE
Tab to delete knowledge base is empty 

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4694]
### Used Zammad Version

6.0

### Environment

- Installation method: hosted only

### Actual behaviour

When configuring the knowledge base the "Delete"-tab is empty.

### Expected behaviour

Either provide hosted customers with the possibility to delete their knowledge base or remove the tab.

### Steps to reproduce the behaviour

Register a hosted instance on zammad.com

### Support Ticket

Ticket#10124935

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by martini** [comment]
I confirm, it also happens on current `stable` and `develop`.

![Screenshot from 2023-06-28 19-18-22](https://github.com/zammad/zammad/assets/110226/78553fde-72e8-42fb-b65c-de413d93da1d)
