### ISSUE TITLE
Calendar feed stops working if access to API via basic auth is disabled

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4695]
### Used Zammad Version

6.0

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When disabling API-basic authentication, the ical-feed is not working anymore.

### Expected behaviour

If API-basic authentication is disabled:
- Either disable the ical-feed-menu option for agents
- Show a warning to agents, that want to use this feature, that it is not working and that they need to contact the administrator

### Steps to reproduce the behaviour

Disable basic authentication on the API. Try to use the ical-feed.

### Support Ticket

Ticket#10124935

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by martini** [comment]
@YetAnotherGerrit can you make sure, that no cookie based authentication is used ?

The best way to verify this, is to use `curl` for verification.

**Comment by YetAnotherGerrit** [comment]
The test I did (with the customer) was, that we disabled basic authentication of the API and his Outlook could not read the ical-feed anymore. Once we re-enabled the basic authentication his calendar worked as usual.

**Comment by martini** [comment]
> The test I did (with the customer) was, that we disabled basic authentication of the API and his Outlook could not read the ical-feed anymore. Once we re-enabled the basic authentication his calendar worked as usual.

Thanks for this feedback. I have more info to add:

If Outlook uses a `http-basic-auth` to access the calendar feed (if I remember correctly, it does this) and you disable basic authentication my Zammad, then you can not access the calendar feed is not accessible anymore (because of disabled basic authentication).
