### ISSUE TITLE
Packager.io Debian 12 Bookworm Packages

### ISSUE THREAD

**Issue by seraphyn** [zammad/zammad#4697]
### Used Zammad Version

6.0

### Environment

Debian 11 Bullseye

* Docker/Podman 24.0.2
* gcc 10.2.1
* Git 2.30.2
* Linux Kernel 5.10.0-23-amd64
* MariaDB 10.5.19-0+deb11u2-log
* mydumper/myloader 0.10.0
* OpenSSL 1.1.1n
* Open Virtual Machine Tools 11.2.5.26209
* Perl 5.32.1
* PHP 8.2.7
* PostgreSQL 13.11 (Debian 13.11-0+deb11u1)
* Python3 3.9.2
* Redis Server 6.0.16
* ssh 8.4p1 Debian-5+deb11u1
* sudo 1.9.5p2
* systemd 247

### Actual behaviour

I would like to be able to schedule the upgrade to Debian 12 Bookworm in the near future and we are considering the best time frame in which to do this.

For this we wanted to clone the machine and do some initial testing

Unfortunately this is not possible at the moment, because there is no repository for Debian 12 available

https://packager.io/gh/zammad/zammad/refs/stable

### Expected behaviour

Upgrade to Debian Bookworm with a Debian 12 Bookworm Repository

### Steps to reproduce the behaviour

Upgrade Debian 11 to 12

@fliebe92 

Thanks and all the best

Christian

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by tschaefer** [comment]
Hi @seraphyn,

you can install the Zammad package for Debian 11 "bullseye" on Debian 12 "bookworm". The bundled Ruby gems using SSL are linked to libssl1.1. Debian 12 ships libssl3.1. As it is possible to have multiple libssl versions installed, you can install libssl1.1 from Debian 11 https://packages.debian.org/bullseye/libssl1.1.

I'm in a good mood, that we are able to ship a Zammad package for Debian 12 soon.

**Comment by MrGeneration** [comment]
Packager.io has no Debian 12 support yet!
Packages are distribution specific - can we please not encourage users to use repositories not meant for their release version?

This has caused trouble in the past already!

**Comment by tschaefer** [comment]
Hi @MrGeneration,

thank you for your valuable input and the hint, that packager.io - the platform Zammad packages are built - is not supporting Debian 12, yet. I am already aware of this and we are in contact with the packager.io team.

Of course, mixing packages of different Debian releases may cause trouble. Within the last 25 years, there were several situations to use multiple OpenSSL (libssl) versions within a Debian system. In general, installing multiple versions of dynamically linked libraries is common.

Last but not least I'm sure our community members are able asses advice and work with it carefully.

**Comment by seraphyn** [comment]
@tschaefer I won't mix up packages.
Debian 11 is well-supported till 2026 and as Enterprise user I got for stable all the time.

**Comment by mgruner** [comment]
Debian 12 packages will [soon be available](https://github.com/zammad/zammad/commit/7ca341f0b8a9b07050f6683b015420fe860699d8).

**Comment by seraphyn** [comment]
@mgruner 
There is an error in the instructions for adding the key under Debian.
It says here:
`wget -qO- https://dl.packager.io/srv/zammad/zammad/key | sudo apt-key add -`

This is wrong. Since Bookworm should be here:
`wget -qO- https://dl.packager.io/srv/zammad/zammad/key | gpg --dearmour -o /etc/apt/trusted.gpg.d/zammad.gpg`

should be taken
The old command would be acknowledged with an error message
apt-key is deprecated.

Link: https://packager.io/gh/zammad/zammad/builds/8994/install/debian-12

**Comment by MrGeneration** [comment]
The documentation states nothing else:
https://docs.zammad.org/en/latest/install/package.html#add-repository-and-install-zammad

If you're looking directly on the packager.io page, please note that this is nothing we have control of, however, I did create an issue for them a while ago:
https://github.com/crohr/pkgr/issues/173
