### ISSUE TITLE
Sometimes popovers don't disappear by themselves

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#4700]
### Used Zammad Version

6.0.0

### Environment

- Installation method: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any 

### Actual behaviour

Sometimes in different places popover remains until i do a reload of the browser window or i click into the search field on top.

![Bildschirmfoto 2023-06-28 um 11 41 41](https://github.com/zammad/zammad/assets/129729908/6a05278e-4cd3-496e-bca8-8f9750cc406e)

### Expected behaviour

Popovers should disappear after it is not needed anymore

### Steps to reproduce the behaviour

I can’t reliably reproduce the problem, it just occurs sometimes. So far i have not been able to find out what exactly i was doing before.

Older similar cases

https://github.com/zammad/zammad/issues/4122
https://github.com/zammad/zammad/issues/4058

### Support Ticket

Ticket#10131766

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by martini** [comment]
IMO its a regression of https://github.com/zammad/zammad/commit/5b653054f171bee2acd326f7242eafe05717eb2f

I confirm behavior (I do have it 2-3 times a day, already since Zammad 5.3 and maybe earlier).

**Comment by martini** [comment]
Here is how to reproduce at least one case (current `stable`).

![popover-issue](https://github.com/zammad/zammad/assets/110226/b0b7b424-80ec-4195-8537-c5d8ec3eb38d)
