### ISSUE TITLE
Die Verbindung zum Server wurde verloren.

### ISSUE THREAD

**Issue by nikomaxi** [zammad/zammad#4701]
### Used Zammad Version

6.0

### Environment

- Installation method: [e.g. apt install Zammad package]
- Operating system (ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [latest]
- Browser + version: [tested on multiple targets and browsers5]

### Actual behaviour

Every time when I go to the website and use the new mobile version, I get the error 

Die Verbindung zum Server wurde verloren.
>> The Connection to the server is lost. <<

The old desktop version works fine. 

### Expected behaviour

Expected would be that the connection is held.

### Steps to reproduce the behaviour

Installing and accessing the website through mobile version

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Please have a look at the release notes for new requirements:
https://zammad.com/en/releases/6-0

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by raffisweb** [comment]
Hi @MrGeneration, could you please give some more hints about this requirements? 

I have the same but/problem @nikomaxi described after installing latest Zammad as **Docker-Compose**. The Desktop runs like a charm but mobile view is buggy (see screenshots). 

- "Die Verbindung zum Server wurde verloren" (lost server connection) random error without any hint, website working (does not change on wifi or cellular)
- Creating new ticket stucks in loading screen and does not move on (works on Desktop view)
 
Thanks in advance!

![IMG_9132](https://github.com/zammad/zammad/assets/22199157/e2b23e6c-4776-4934-9cce-3044c530998a)
![IMG_9134](https://github.com/zammad/zammad/assets/22199157/60ceaa34-2f1f-42c0-920f-720924a99364)![IMG_9133](https://github.com/zammad/zammad/assets/22199157/096b4bc4-3a02-42ff-a41c-25260e041d39)

**Comment by MrGeneration** [comment]
Kindly consult the community for technical questions. Thank you.

**Comment by raffisweb** [comment]
Thank you for the prompt message, @MrGeneration, and thanks for the hint to search in the community. I found the corresponding thread there and was able to resolve the issue. For anyone else who may be lost, here's the link: https://community.zammad.org/t/zammad-6-0-mobile-client-issues/11550/42

Let me add constructively that, despite the simplicity of Zammad, I would have expected an explanation for such pitfalls in the documentation or the proxy-examples, especially in the Docker Compose variant. The error occurred during a fresh installation and not during an update. Unfortunately, this information is somewhat hidden in the release notes. Perhaps for new installations, this pitfall could be avoided by highlighting the configuration option (and necessity). It seems that quite a few people have encountered this error. Especially with the out-of-the-box feeling that Docker Compose conveys, it should ideally work seamlessly, shouldn't it? No offense, and thanks again!

**Comment by dominikklein** [comment]
Normally we didn't receive problems after fresh installations. There should be a default handling in place.
