### ISSUE TITLE
Shared drafts in ticket zoom not usable if permission is granted through role assignment

### ISSUE THREAD

**Issue by gojufhv** [zammad/zammad#4704]
### Used Zammad Version

6.0

### Environment

- Installation method: apt repo
- Operating system: Debian 11 AMD64
- Database + version:  psql (PostgreSQL) 13.11 (Debian 13.11-0+deb11u1)
- Elasticsearch version: 7.17.11
- Browser + version: Firefox 114.0.2

### Actual behaviour

Unable to see other shared drafts or to save shared drafts. It is possible a regression of #4071

The user needs to have access granted to the group directly via the user profile, access granted via a role is not accepted.

### Expected behaviour

If I create a shared draft of a new ticket, the draft is saved if the access to the group is granted via a given role.

### Steps to reproduce the behaviour

-   Create a role with full access to group
-   Assign the role to user
-   Assure that user has no access to group directly via user profile
-   Draft new ticket
-   Enter name of draft and try to save it

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
```
I, [2023-07-05T07:40:51.353827#98494-75180]  INFO -- : not allowed to index? this TicketsSharedDraftStartsController (Pundit::NotAuthorizedError)
app/controllers/application_controller/authorizes.rb:10:in `authorize!'
app/controllers/application_controller/authenticates.rb:143:in `authenticate_and_authorize!'
```
