### ISSUE TITLE
excel export files need to be converted to numbers

### ISSUE THREAD

**Issue by technoicon** [zammad/zammad#4712]
### Used Zammad Version

6.0.0-32

### Environment

Installation method: Docker
Operating system: Ubuntu 18.04
Database + version: postgresql 15.1
Elasticsearch version: 8.5
Browser + version: Chrome v114

### Actual behaviour

When you download a report that is xlsx and open it, all the numbers in the spreadsheet are not numbers, this requires you to convert them to numbers.
Numbers don't work in formula's until "convert to number" has been selected.

![image](https://github.com/zammad/zammad/assets/17463110/87e21f00-3b55-48c0-ab00-d609fb6c20dd)

### Expected behaviour

opening a excel sheet with numbers would be formatted as numbers.

### Steps to reproduce the behaviour

Go to any xlsx report
Settings > Time Accounting > Activity (download).
Save xlsx document
open in excel.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by t-shehab** [comment]
Hi @technoicon,

thanks for opening this issue.

The behaviour you're experiencing is most likely caused by the decimal separator used in the given spreadsheet program's (Excel in your case) language settings. Some languages (German, for example) use a comma as decimal separator, most other languages use a dot instead.

Please make sure you're using the correct language settings for the separator in use.

**Comment by technoicon** [comment]
Hi @t-shehab,

I could be wrong as I'm not a ruby coder, but it looks like the excel export checks for an "integer" or "float" to set the field as a "number" in excel.

I checked what looks like to me, the time accounting feild "Time Unit" and it seems to be stored as a string?
zammad/spec/requests
/time_accounting_spec.rb
line: 31
'time_unit'    => time_accounting1.time_unit.to_s,

.to_s to string?  

Could it be that the "time_unit" is actually returning a "string" value and not an "interger" value, and therefore during the excel export the "Number Value is Stored as Text" instead of an excel number field?

If this is not the case sorry for wasting time, I'm no coder :D
