### ISSUE TITLE
Operator "contains all" does not work with multi tree select

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4714]
### Used Zammad Version

6.0

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When creating a core workflow with an "contains all"-condition for a multi tree select, it does not work with more than one element.

### Expected behaviour

When creating a core workflow with an "contains all"-condition for a multi tree select, it works with more than one element.

### Steps to reproduce the behaviour

Create a ticket-attribute of the multi tree select type, with at least 2 elements.
Create a cw with a condition that needs to include more than one element.

![image](https://github.com/zammad/zammad/assets/97293098/935a1cf3-6fc6-4fb3-a20d-3fa675b34a53)

### Support Ticket

Ticket#10131675

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by YetAnotherGerrit** [comment]
And this condition seems to be true all the time, regardless of what you choose in the ticket:
![image](https://github.com/zammad/zammad/assets/97293098/2b864ece-c659-4a87-8070-1a8d2f4cfca9)

**Comment by rolfschmidt** [comment]
> ### Actual behaviour
> When creating a core workflow with an "contains all"-condition for a multi tree select, it does not work with more than one element.
> 
> ### Expected behaviour
> When creating a core workflow with an "contains all"-condition for a multi tree select, it works with more than one element.


This is fixed now.

> And this condition seems to be true all the time, regardless of what you choose in the ticket: ![image](https://user-images.githubusercontent.com/97293098/252873749-2b864ece-c659-4a87-8070-1a8d2f4cfca9.png)

**contains not** will show up tickets which have no tags or at least one tag which is not in the configured tags. If you want to find all tickets which have none of the listed tags contained, then you should use **contains all not** instead.

**Comment by YetAnotherGerrit** [comment]
> **contains not** will show up tickets which have no tags or at least one tag which is not in the configured tags. If you want to find all tickets which have none of the listed tags contained, then you should use **contains all not** instead.

This is my MTS attribute:

![image](https://github.com/zammad/zammad/assets/97293098/c5d78444-2f60-403a-81f3-fc7b7ec5ae8b)

This is my workflow:

![image](https://github.com/zammad/zammad/assets/97293098/af7b88cb-4273-4f4b-ae86-fed21c13455c)

And this show that the priority is read-only all the time:

![image](https://github.com/zammad/zammad/assets/97293098/37d56841-0d76-4d3d-a16a-0432e1a92ce6)

![image](https://github.com/zammad/zammad/assets/97293098/950cf37c-92a6-4185-9a2a-db41a0b39fa1)

![image](https://github.com/zammad/zammad/assets/97293098/39dd80ae-2467-4b76-8f11-d70da8e2a18b)

What am I missing here? The last one should be false (priority is not readonly anymore), shouldn't it?
- contains not A > false
- contains not B > false
- contains not B > false

Why is it still true?

**Comment by YetAnotherGerrit** [comment]
And if "contains not" means "contains something that is not one of the following", it still is true if it shouldn't.

![image](https://github.com/zammad/zammad/assets/97293098/574bfb27-cddb-4884-bb2c-7ca4e4b1e571)

I am not able to create any scenario where "contains not" is false.

**Comment by YetAnotherGerrit** [comment]
Latest stable is working now. Thank you!
