### ISSUE TITLE
Timezone for Iceland missing from dropdown

### ISSUE THREAD

**Issue by almarbjornsson** [zammad/zammad#4715]
### Used Zammad Version

6.0

### Environment

- Installation method: helm chart 
- Operating system: Container ->ghcr.io/zammad/zammad:6.0.0-32
- Database + version: bitnami/postgresql-15.3.0-debian-11-r7
- Elasticsearch version: bitnami/elasticsearch:8.8.1-debian-11-r0
- Browser + version: edge 114 / chrome 114

### Actual behaviour

In Settings -> Branding -> Timezone the dropdown for timezones does not include an option for Iceland / Reykjavík.

There are options that are in the same timezone but then that text gets sent in emails and is not ideal

### Expected behaviour

An option for Iceland / Reykjavík is selectable

### Steps to reproduce the behaviour

1. Login as admin
2. Open Settings
3. Open Branding
4. Find Timezone dropdown
5. Open dropdown and see that Iceland is missing.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
Hi @almarbjornsson, this is fixed via ba0385e6540dfddd7fccdeefdcf85771626f67d3 and a back port to 6.0 will land soon as well. You can then select `Atlantic/Reykjavik` as a time zone. This is how it is stored in the [official IANA time zone database](https://www.iana.org/time-zones).

**Comment by mgruner** [comment]
Ported back to Zammad 6.0 in d934d5b3a3af151ea374b28f48742086dd7fdb22.
