### ISSUE TITLE
Description field is required, but is not marked as required in the interface

### ISSUE THREAD

**Issue by Michi01** [zammad/zammad#4719]
### Used Zammad Version

6.0

### Environment

- Installation method: [e.g. source, package] package
- Operating system: Debian GNU/Linux 11
- Database + version: : postgresql 13+225
- Elasticsearch version: 8.8.2
- Browser + version: Chrome Version 114.0.5735.199

### Actual behaviour

If you want to create an ticket without description you get this error message "At least one field "Article text" is required".

![image](https://github.com/zammad/zammad/assets/12865086/c3ee92ca-6e4a-471c-b56f-4889a07e1207)

### Expected behaviour

Error message includes the correct field label "DESCRIPTION" (yes I know I can customize the translation, but the current message is incomprehensible at the point as standard).

as well as that the field is also apparent as a required field. There is no * in the display, because that is missing at the position

### Steps to reproduce the behaviour

1. Try to create a new Ticket
2. Leave Description empty

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
This problem should be fixed with the desktop-view rewrite (can already be checked in the mobile-view).
