### ISSUE TITLE
Large attachments will blow up RAM and CPU usage on mysql

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4724]
### Used Zammad Version

6.0

### Environment

- Database + version:  MariaDB/MySQL

### Actual behaviour

Upload a 50MB file crash the server.

### Expected behaviour

Uploading a 50MB should not crash the server.

### Steps to reproduce the behaviour

Upload a 50MB in ticket zoom.

### Support Ticket

Ticket#10116803

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by martini** [comment]
@rolfschmidt JFI: should get handled/blocked by nginx like https://github.com/zammad/zammad/blob/develop/contrib/nginx/zammad.conf#L28

**Comment by rolfschmidt** [comment]
> @rolfschmidt JFI: should get handled/blocked by nginx like https://github.com/zammad/zammad/blob/develop/contrib/nginx/zammad.conf#L28

I changed it to 50MB files its the same issue there as well.

**Comment by rolfschmidt** [comment]
example test.rb 

```ruby
cache = UploadCache.new(rand 10000000)
UserInfo.current_user_id = 1

fname = 'test.pdf'
file = File.read(fname)

store = cache.add(
  filename:    fname,
  data:        file,
)

puts "YES"
```

https://www.learningcontainer.com/download/sample-50-mb-pdf-file/
