### ISSUE TITLE
Merging ticket with itself should not be possible

### ISSUE THREAD

**Issue by bastolino** [zammad/zammad#4729]
### Used Zammad Version

6.0.0-1689860438.de5a066a.jammy

### Environment

- Installation method: package via repo
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 22.04 LTS (latest patch)
- Database + version:  mariadb  Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper (I know, deprecated)
- Elasticsearch version: elasticsearch/stable,now 7.17.11 amd64
- Browser + version: Firefox 115.0 (64-Bit) canonical-002 - 1.0

### Actual behaviour

Merging a ticket with its own ticketnr. results in the ticket itself being both parent and child at the same time. Although I cannot see any real problem from it, it should not be possible.
However, I do not see a real benefit from doing that.

### Expected behaviour

(suggestion) return a warning message stating that merging a ticket with itself is possible possible but has to be confirmed

### Steps to reproduce the behaviour

create a ticket number, merge some stuff into it, try to merge the ticket with itself.

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by cautopartes** [comment]
I could not reproduce the issue with a current version. Here is an example, refusing to merge into itself: 

![image](https://github.com/zammad/zammad/assets/69846837/5503bcc4-ec48-4c65-8c32-a3447c06eaf1)

Please reopen if necessary with more detailed instructions on how to reproduce the situation.
