### ISSUE TITLE
SLES12 SP1: "nothing provides postgresql93 needed by zammad", postgresql94 is default for SLES12 SP1

### ISSUE THREAD

**Issue by martini** [zammad/zammad#473]
@monotek It this a issue for packager.io (I see SLES12 in general is supported https://packager.io/documentation/distributions/)?

```
linux-urt1:~ #  sudo zypper install zammad
Building repository 'nginx' cache ....................................................................................................................................[done]
Building repository 'zammad' cache ...................................................................................................................................[done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides postgresql93 needed by zammad-1.1.0-1480344964.5f7f8c5.sles12.x86_64
 Solution 1: do not install zammad-1.1.0-1480344964.5f7f8c5.sles12.x86_64
 Solution 2: break zammad-1.1.0-1480344964.5f7f8c5.sles12.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c):
```

**Comment by monotek** [comment]
I tested on opensuse 42.2. 
Could'nt install anything on SLES because of missing license key :-/

**Comment by martini** [comment]
JFI: I was able to download the SLES 12 SP1 iso images and was able to press "skip registration". :)

**Comment by monotek** [comment]
Yes, but you cant use the package repos...

**Comment by monotek** [comment]
OK. Was able to reproduce. Used packages from SLES12 SP2 DVD ISO. 
Send an email to packager.io support about the problem.

Unfortunately it does not help to remove postgresql-server from dependencies. The postgresql93 dependency remains in the RPM. I guess its for accessing postgresql from ruby.

Maybe we could create an mysql only version if on sles. But i'm currently not sure if it helps to just delete postgres from the gem for that...

**Comment by monotek** [comment]
Added pull request to pkgr (https://github.com/crohr/pkgr/pull/117). 
Hope the'll fix it soon...

**Comment by hanneshal** [comment]
closed due inactivity

**Comment by monotek** [comment]
Hab noch mal nachgefragt: https://twitter.com/mono_tek/status/893452057763622916

**Comment by crohr** [comment]
I had a look at the PR and will merge soon, sorry for the wait. Note that for big apps you could (should) specify your exact runtime dependencies and remove the default ones provided by pkgr by setting `default_dependencies: false`.

**Comment by monotek** [comment]
Thanks for fixing & the hint :-)
