### ISSUE TITLE
Improve error message when macro fails, because the owner is invalid

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4730]
### Used Zammad Version

6.0

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When an agent tries to use a macro that sets himself as the owner, but the user does not have "Full"-permission to that group, the error message is not helpful:

![image](https://github.com/zammad/zammad/assets/97293098/12da788a-3918-418c-a935-60bca304c5a7)

### Expected behaviour

An error message, targeted to the agent, should be helpful to the agent:
"The macro failed because 'Max Musterman" is not a valid owner for this ticket." or
"The macro failed because you are not a valid owner for this ticket."

Reported as bug after talking with @martini

### Steps to reproduce the behaviour

Create a group A.
Create a user B with "Change"-permission to that group.
Create a ticket C in that group.
Try to apply the "Close & Tag as Spam"-Macro to ticket C in group A using user B.

### Support Ticket

Ticket#10134681

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Looks like a duplicate to this: https://github.com/zammad/zammad/issues/3864
