### ISSUE TITLE
Zammad displays wrong time at 2 hours

### ISSUE THREAD

**Issue by Schroedelskatze** [zammad/zammad#4732]
### Used Zammad Version

6.0

### Environment

- Installation method: package
- Operating system: Ubuntu 20.04.6 LTS (Focal Fossa)
- Database + version:  postgresql 12.15
- Elasticsearch version: 7.17.7
- Browser + version: chrome 115.0.5790.102

### Actual behaviour

Zammad displays the time 2 hours in the future of my region. It also shows that it speaks in the future.

For example the activity-stream says "... started a new Session **in** 2 hours".

If you create a new entry in the Knowledge Base it also says "Release **in** 2 hours" even if you say it should be released immediately. But it is released and other can see it, yet its still colored grey and not green/blue until the 2 hours have passed.

If a ticket is created it also say "... created **in** 2 hours", aswell as every answer created.

I hope you get the point, everything in zammad / the time is set wrong by 2 hours.

### Expected behaviour

The time should be displayed correctly.

The timezone in the branding-settings is set correct, aswell as the ubuntu time-settings and zammad-settings.
Every output of date / timedatectl / (Zammad) Time.now / Time.zone.now / etc shows the correct time of my region.
Zammad adds 2 hours for whatever reason.

### Steps to reproduce the behaviour

- 

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
This smells like a technical question and local timezone issues on the server.

**Comment by Schroedelskatze** [comment]
First I thought that aswell, but I think I have excluded everything that has to do with timezone-settings.

The ubuntu-machine, the host-server, the local time / universal time / rtc time / time zone are set correctly and are equal to my region time, aswell as the "Time.zone" commands within the zammad-rails gave me the correct time output.
Maybe I am overseeing something but I cant figure the reason of this problem.

If I change the time zone in the branding-settings to for example GMT+8 nothing changes within the system. It stays at +2 hours of my region time.

I am sorry if this is the wrong place to ask.

**Comment by MrGeneration** [comment]
Well Zammad stores it's datetime information in UTC to allow timezone magic to happen. Usually servers are configured in UTC time with your specific timezone setting on top.

Running `Time.zone.now` should return a UTC value like this: `Wed, 26 Jul 2023 11:25:15.663160935 UTC +00:00` not your local timezone.

**Comment by Schroedelskatze** [comment]
Ah man, thats embarrasing now. That was the issue we had.. the UTC time was set wrong due to no ntp-service.
I've sawn it the whole time and didnt notice that the UTC can't be the same as our CEST..

For now I've set the UTC manually but will activate ntp again soon.. I am so sorry for wasting your time but that little wink of yours helped me a lot.

Thanks and my appreciation, sorry again.

**Comment by MrGeneration** [comment]
Glad it helped. Next time, please use our community for technical questions. If things turn out to be a bug we can of course move them over to this issue tracker. 🙏
