### ISSUE TITLE
Avatar is not clickable on tablet devices or devices in tablet modus

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#4745]
### Used Zammad Version

6.0.0-1690787481.df8ba11b.bullseye

### Environment

- Browser + version: any
- Devices: Tablets, Devices with Tablet Mode

### Actual behaviour

On some devices the Avatar is not clickable in the Desktop View of Zammad

Devices:  iPad Tablet, Thinkpad in Tablet Mode, Fujitsu Stylistic Q7310 in Tablet Mode
Maybe: All Tablets and Devices in Tablet Mode

### Expected behaviour

On all devices the Avatar is clickable, also on Tablets and on Devices with Tablet mode.

### Steps to reproduce the behaviour

with an iPad (without pen or keyboard) the Avatar in the ticket is not clickable in the Zammad Desktop View.
with an Thinkpad in Tablet mode the Avatar in the ticket is not clickable in the Zammad Desktop View.
with an Fujitsu Stylistic Q7310 without an Keyboard the Avatar in the ticket is not clickable in the Zammad Desktop View.

### Support Ticket

Ticket#10133777 
Ticket#10153133

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by fliebe92** [comment]
Hi @MarkusHeld. The current labeling is confusing me. Is this a bug? Does this report need to be verified by another person?

Touch devices are not supported that well right now, I guess.

**Comment by MarkusHeld** [comment]
Hi @fliebe92 in my opinion zammad should also work on such devices without restrictions, but if this should labeled as bug im not sure

**Comment by cautopartes** [comment]
We have had a similar situation in Ticket#10135870. There we narrowed it down to a combination of a docking station and the usage of "RAV Enpoint Protection" by Reason Labs (https://reasonlabs.com/platform/products/endpoint-protection).  

Using both "RAV Enpoint Protection" and docking station led to the not clickable avatars. Taking either the software or the hardware out of the equation resolves the issue. 

Therefore, I am closing this as a third party issue.

**Comment by MarkusHeld** [comment]
i reopen the issue, because other tests shown the same situation

**Comment by MrGeneration** [comment]
To make this easier to reproduce and why this feels like a bug and not a browser issue (it happens with all mayor Browsers, chromium-ish, Firefox and Safari):

This issue only occurs if the device is in Tablet mode.
The issue also vanishes on the same device and browser if you switch to desktop mode, reload Zammad and finally switch back to tablet mode to do the same again.

You can use touch stuff, no matter if via pen or finger in Desktop mode all the time.
I verified this on my Thinkpad X380 which is a 5 year old Yoga convertable. When I'm using that device, I'm touching the Zammad UI without the mouse. Convertables are quite common by now, Desktop view or not, it should not lock out those users in my opinion.

**Comment by Benny1988** [comment]
Is there a solution available? I ran into this problem with my Lenovo YOGA 6.
