### ISSUE TITLE
REST API Doc for online notifications in Zammad

### ISSUE THREAD

**Issue by martini** [zammad/zammad#475]
@MDXDave here it is, https://docs.zammad.org/en/latest/api-notification.html any comments?

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
