### ISSUE TITLE
Required custom attributes are not always validated

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#4756]
### Used Zammad Version

6.0

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:   any
- Elasticsearch version:  any
- Browser + version:  any

### Actual behaviour

`Validations::ObjectManager::AttributeValidator::Required` does not run in objects with `ChecksCoreWorkflow`. However, `ChecksCoreWorkflow` does not run validations if screen attribute is not present.  Which results in this validation never running in some cases.

### Expected behaviour

Custom attributes are always validated either by `CoreWorkflow` or `Validations::ObjectManager::AttributeValidator`

### Steps to reproduce the behaviour

- Add custom attribute that requires value to be present
- Try to save an object without that value in console
- Validation does not run

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by rolfschmidt** [comment]
Meeting 2023-09-01 (RS+DK+FL+MM)

We will take no action, there is no problem case atm.
