### ISSUE TITLE
Core Workflow: Readded options are not usable in conditions

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4763]
### Used Zammad Version

6.1

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When options are removed->readded, then they can't be used in conditions.

### Expected behaviour

It should be possible to react on selections if options have been removed and readded before.

### Steps to reproduce the behaviour

- Add select
- Add CW: Remove all options
- Add CW: Add all options
- Add CW: If option A then title readonly
- On ticket create the title readonly state will not change because the last CW will never grip.

### I'm sure this is a bug and no feature request or a general question.

yes

------

@rolfschmidt @fliebe92 Hello - I created a video outlining this - I think it's easier to just demonstrate what's going on.  I did figure out the issue occurs when removing an option from an object using the "remove option" in a core workflow and then adding it back using the "add option" action in a later core workflow - this happens for both the built-in objects as well as custom objects (I show this all in this video).  The issue is not with priorities - I clearly have them set in the right order.

As a workaround, we can use a method where instead of removing everything up front and adding what the user should see as we go, we remove everything we don't want them to see as we go.  This works currently, but this is not ideal, as it's harder to maintain this way - I'd rather add options I want as I add them than have to remember to go remove any new options we may add later on from every core workflow.  

So a simplified recreation of this: 

1. add a text object "test input" 
2. add a single select object "test selection" with values a b c d e f g
3. in core workflows make a priority 1 workflow that removes all those options from the obect
4. in another workflow priority 2 add b d f back to the object
5. add a priority 3 core workflow that displays "test input"  if "test selection" is b or d.  
6. Test this as a customer (it won't ever show "test input"). 
7. Now go back, change the priority 1 core workflow to instead only remove only a c e g (instead of all options) - now go try it again, it will now display "test input" correctly.
Something about an option being removed prevents it from being considered in "is/is not" logic even if it's re-added before that logic occurs.

https://www.youtube.com/watch?v=xGeXrh4_RZ8

_Originally posted by @bahusafoo in https://github.com/zammad/zammad/issues/4752#issuecomment-1679069567_

**Comment by bahusafoo** [comment]
I'm confused - this is closed?

**Comment by rolfschmidt** [comment]
> I'm confused - this is closed?

Hey @bahusafoo ,
I fixed it already in develop. It should be available as well in stable tomorrow. The backport always takes a bit because of the CI pipelines. Try to update your zammad tomorrow.

**Comment by bahusafoo** [comment]
Thank you SO much!

**Comment by rolfschmidt** [comment]
> Thank you SO much!

Let me know if it works, else we might have to take a look at your config again.

**Comment by rolfschmidt** [comment]
https://packager.io/gh/zammad/zammad/builds/9191

**Comment by bahusafoo** [comment]
@rolfschmidt This appears to be working now.  Thank you for your work!  If I can buy you a coffee, ping me in DM!
