### ISSUE TITLE
Transparent image is displayed incorrect

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4769]
### Used Zammad Version

6.0

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: Edge[v. 115.0.1901.203 (64-bit)

### Actual behaviour

For images with a transparent background, the background is overwritten with black/white/opaque white, depending on how and from which programme the image was copied into Zammad.

### Expected behaviour

When copying images with a transparent background into Zammad, the background should remain transparent and not be coloured.

### Steps to reproduce the behaviour

1. prepare a .png image with a transparent background.
2. try to copy it into Zammad.
2a. depending on the programme used, the background will be displayed in different colours 
2b. when the image is copied into Zammad, the background becomes black.

https://github.com/zammad/zammad/assets/101350124/874af530-186f-4bc0-93bb-afffb3d6db79

![pexels-ryan-delfin-2270389-removebg-preview](https://github.com/zammad/zammad/assets/101350124/d54c0ea5-c6fc-4a9b-9b9a-e7b65f7a2c4d)

### Support Ticket

Ticket#10137247, #10147546, #10155716

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by martini** [comment]
Note for developers. Just discovered this issue in a workshop. This maybe the fix:

```
~/src/zammad$ git diff app/assets/javascripts/app/lib/base/jquery.contenteditable.js
diff --git a/app/assets/javascripts/app/lib/base/jquery.contenteditable.js b/app/assets/javascripts/app/lib/base/jquery.contenteditable.js
index 0e85331d4a..265b563ef6 100644
--- a/app/assets/javascripts/app/lib/base/jquery.contenteditable.js
+++ b/app/assets/javascripts/app/lib/base/jquery.contenteditable.js
@@ -350,6 +350,7 @@
         this.log('paste image', clipboardImage)
 
         var imageFile = clipboardImage.getAsFile()
+        var imageType = clipboardImage.type
         var reader = new FileReader()
 
         reader.onload = $.proxy(function (e) {
@@ -381,7 +382,7 @@
           }, this)
 
           // resize if to big
-          App.ImageService.resize(img.src, maxWidth, 'auto', scaleFactor, 'image/jpeg', 'auto', insert)
+          App.ImageService.resize(img.src, maxWidth, 'auto', scaleFactor, imageType, 'auto', insert)
         }, this)
 
         reader.readAsDataURL(imageFile)
~/src/zammad$ 
```

**Comment by DrumSlayers** [comment]
Same issue here, this is really annoying since our logo massively use transparency.
As of now, we don't include our logo in Zammad for this exact reason.
