### ISSUE TITLE
SMTP e-mail notifications not working with 1&1

### ISSUE THREAD

**Issue by driebe** [zammad/zammad#477]
Hi there,

so I was trying to set up the e-mail notifications with an 1&1 hosted e-mail server. However, every time I get an error in return:

`550-Requested action not taken: mailbox unavailable`

Setting up incoming and outgoing emails for the ticket channels works fine though, which makes this really weird...

Daniel

**Comment by Umberto321** [comment]
Same problem here. Any progress?

**Comment by hanneshal** [comment]
Not an Zammad issue. Please see:
https://hilfe-center.1und1.de/hosting/e-mail-und-office-c10082645/1und1-mail-basic-c10082704/problemloesung-c10082756/fehlermeldung-bei-unzustellbarer-e-mail-a10795206.html
