### ISSUE TITLE
Zammad 6 interprets non-existent values differently than version 5, resulting in broken triggers

### ISSUE THREAD

**Issue by lug-gh** [zammad/zammad#4772]
### Used Zammad Version

6.0.0

### Environment

- Installation method: package
- Operating system: ubuntu 20.04
- Database + version:  postgres 10
- Elasticsearch version: 7.17
- Browser + version: latest chrome

### Actual behaviour

If you add a new attribute under Settings -> System -> Objects -> Organization and build a trigger on it, but then this attribute does not exist for a ticket, the trigger will be executed and if this trigger creates a note, then "no such method".

### Expected behaviour

I don't know exactly how Zammad 5 works in the backend, but if the trigger had the default value of the attribute as the trigger, it could be used even if the customer didn't belong to any organization at all. Maybe it was just because my trigger listens to "0", and in case of non-existence the value was also 0.

### Steps to reproduce the behaviour

1. Create an attribute for the object type Organization of type Integer, setting default to 0. In this example I use "customerid".
![image](https://github.com/zammad/zammad/assets/24546639/3df7f351-b6aa-463d-a2c0-f9809539f45e)

2. Update Database (required after attribute creation)

3. Create a Trigger with the following conditions:
- Ticket Action == created
- Organization Customer ID != 0
![image](https://github.com/zammad/zammad/assets/24546639/d5673b16-b6cf-4ea8-a74a-ca89f3b6fd90)

4. Optional: Assign a customer ID to an existing organization (I am doing this now to show how it should look, but the problem occurs when a customer creates a ticket (e.g. via mail) who is not assigned to an organization in Zammad.)
![image](https://github.com/zammad/zammad/assets/24546639/6f82b5b3-bdeb-4239-a314-8b95188ffce8)

5. Create a Ticket with a customer who has an organization assigned (this works as expected)
![image](https://github.com/zammad/zammad/assets/24546639/0f358db9-3dec-4908-acb6-de41bf78b4af)
![image](https://github.com/zammad/zammad/assets/24546639/35ce08c2-2bd9-48ad-93fe-65786b13fb75)

6. Create a Ticket with a new customer who is not part of an organization
![image](https://github.com/zammad/zammad/assets/24546639/40d2bbda-05c1-4616-875c-3f9f754d8c35)
![image](https://github.com/zammad/zammad/assets/24546639/5dae281e-d60f-4653-abcb-0261b25bfc98)

In Zammad 5.x, if a customer did not belong to an organization, no note was created. In Zammad 6, this is no longer the case, and this incorrect note is created.
This issue might be a little bit related to #4663

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @lug-gh. Thanks for your report. We used some time to check the behavior and we found a solution. Please update your trigger as shown in the screenshot and try it out afterward. In the future it might be even easier to configure this properly: https://github.com/zammad/zammad/issues/4716

![image](https://github.com/zammad/zammad/assets/8327427/8d003fd0-e8de-4d03-b549-be8483c0e78d)

Background information: In a prior Zammad version, there was another bug that make your shown trigger work fine for you. By fixing this in a newer version of Zammad, we broke your existing trigger.

If you still encounter any issues, feel free to re-open this report. Thanks again for your time and effort spent in this issue! We really appreciate it.
