### ISSUE TITLE
Healthcheck: returns 200 even if unhealthy

### ISSUE THREAD

**Issue by Frankkkkk** [zammad/zammad#4775]
### Used Zammad Version

6

### Environment

- Installation method: docker-compose

### Actual behaviour

Hi,
The healthcheck endpoint returns 200 even if .healthy=false.
It would help monitoring tools if the http status code would be >=400 when Zammad is unhealthy

### Expected behaviour

HTTP status code is 200 even if unhealthy

### Steps to reproduce the behaviour

break it and observe

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by mgruner** [comment]
Please see my response in #4776.
