### ISSUE TITLE
Redirect to login not working for some pages if not logged in

### ISSUE THREAD

**Issue by SwissTazMan** [zammad/zammad#4780]
### Used Zammad Version

6.0

### Environment

Browser + version: Chrome 116.0.5845.111

### Actual behaviour

If I’m not logged in to Zammad, opening an new browser tab and entering the complete url (e.g. base_url/#ticket/create), it shows a really short loading animation and then a blank page. The url gets changed to #ticket/create/id/811 (811 is just an example and changes every time)

Affected urls:

- #ticket/create
- #ticket/create/customer/{id}
- #ticket/view/all_unassigned
- #user/profile/{id}

### Expected behaviour

If I’m not logged in to Zammad, open an new browser tab and entering the url it should redirect to the login page and after login it should redirect to the previous url.

### Steps to reproduce the behaviour

Logout from Zammad
Enter the url in a new tab

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Duplicate from: https://github.com/zammad/zammad/issues/4664
