### ISSUE TITLE
The webhook does not execute if the ticket action is "Closed"

### ISSUE THREAD

**Issue by decioesilva** [zammad/zammad#4796]
### Used Zammad Version

6.0.0

### Environment

- Installation method: source
- Operating system ubuntu 20.04
- Database + version:  postgresql
- Elasticsearch version: 7.17
- Browser + version: All

Language: brazilian portuguese

### Actual behaviour

If a trigger is set up to run a webhook, and it's chosen to execute on the ticket action 'Closed', it does not run. It was tested on the 'Create' action and worked perfectly.

### Expected behaviour

Set up a trigger to run a webhook, and when chosen to execute on the ticket action 'Closed', it should run every time the ticket status is changed to 'Closed'

### Steps to reproduce the behaviour

Set up a trigger:
NAME: Any (default)
ACTION EXECUTION: Selective (default)
CONDITIONS FOR AFFECTED OBJECTS: Ticket Action is updated, Ticket Status is closed
EXECUTE CHANGES ON OBJECTS: previously configured webhook.

Note: when the Ticket Status is created, it works.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@decioesilva thanks for the report, but we can not reproduce the problem with the described situation.
Feel free to add some more information to reproduce the problem. Otherwise, it seems to be more a technical question for the community: https://community.zammad.org/

**Comment by decioesilva** [comment]
@dominikklein Thank you for your reply. Please allow me to clarify in more detail: the intended trigger doesn't work if the company is set to the "Brazilian Portuguese" language, but it works perfectly if set to the "United States English" language; therefore, the trigger's malfunction is related to the language.

**Comment by MrGeneration** [comment]
Your description is not clear enough. Please use Zammad termonology. You can also consult the community first, in case this should be an bug and not a configuration issue, we'll gladly move back to Github.
