### ISSUE TITLE
"May" is missing on translation admin page

### ISSUE THREAD

**Issue by forreggbor** [zammad/zammad#4803]
### Used Zammad Version

6.0.0

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): ubuntu 22.04.3 LTS
- Database + version:  mariaDB 10.6.12
- Elasticsearch version: 7.17.13
- Browser + version: ALL

### Actual behaviour

On translation admin page the "May" is missing from the list.
![2023-09-07_08-02](https://github.com/zammad/zammad/assets/23742538/6d196efb-2fb0-4a7c-8a8a-2941dcb50036)

### Expected behaviour

May should be listed

### Steps to reproduce the behaviour

Open Admin page --> click Translations

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
@forreggbor thank you for the report. It seems that `May` is present, but not in the list of long month names, but slightly above with the short names. Can you check again, please?

<img width="866" alt="Bildschirmfoto 2023-09-07 um 10 54 05" src="https://github.com/zammad/zammad/assets/211281/62bd0791-b789-4412-a1fd-35c2599e7b33">

**Comment by mgruner** [comment]
Closing, feel free to reopen with more information.

**Comment by forreggbor** [comment]
I see in the abbrev list. But all the other months are listed with abbrev AND full length version. So both abbrev and full names should be translated for "May" as well.
![2023-09-07_10-59](https://github.com/zammad/zammad/assets/23742538/ed4d3609-4544-4c24-8160-faf355dafe80)

**Comment by mgruner** [comment]
I am not sure what you mean. In English, it's the same, there is only "May", so it can technically only be listed once. You want a short and long version of May in your language?

**Comment by forreggbor** [comment]
but on other languages it is different. For example in Hungarian the full name is "Május" short name is "Máj". In Italian the full is "Maggio", etc. Please do not think only in English if you allow to translate any application. Other languages does not follow English language rules.

**Comment by mgruner** [comment]
Thanks for your explanation. In Zammad's translation system, every source string can have only one translation at present. This is a technical limitation, and it worked well so far. This is the only exception that I heard of until now. 
Right now I would believe that this case alone does not warrant making the system more complex in this regards. We'll keep it in mind as a suggestion for now.

**Comment by mantas** [comment]
This is tiny, but super annoying issue. Vast majority of languages have `May` as a longer word. While it is a technical limitation, it may be worthwhile to find a workaround.

Maybe have  `May-full-month-name` placeholder and then make sure English translates it as well as other languages?

**Comment by forreggbor** [comment]
I agree with @mantas . I mainly use PHP for coding and gettext to translate my apps and I use different placeholder name in the laguange file for every different usage vairant. For example I also use full and short names of the months and use it %like% JAN_FULL vs JAN_SHORT.

There are exceptions: https://web.library.yale.edu/cataloging/months
Croatian: svibanj vs svib
Czech: květen vs kvet
Italian: Maggio vs magg
Ukranian: traven vs trav
Hungarian: május vs máj
Maybe nobody use Zammad from these countries or they don't care about the translation and use it in english.

**Comment by mgruner** [comment]
Just to note, Zammad is not broken / unusable. They just see the translated long version of the month name, so perhaps 7 characters rather than 4.
