### ISSUE TITLE
"Switch to user" is not working if "maintenance_mode" is enabled and target user has no `admin` permissions

### ISSUE THREAD

**Issue by martini** [zammad/zammad#4805]
### Used Zammad Version

6.0

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Browser + version:  any

### Actual behaviour

"Switch to user" is not working if "maintenance_mode" is enabled and target user has not `admin` permissions. Screen will always be blank. No error message.

### Expected behaviour

"Switch to user" should should always work, even if system is in "maintenance_mode".

### Steps to reproduce the behaviour

![switch_to_user](https://github.com/zammad/zammad/assets/110226/f64e4127-d94e-4925-9b7e-5854eedc8d59)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
But should it really work to switch to a user that has no admin permission?

I agree that the screen should not be blank, but I'm not about the rest :-D

**Comment by martini** [comment]
> But should it really work to switch to a user that has no admin permission?

Important here is, the target user usually has no `admin` permission. Only the user which starts the "switch to user" has `admin` permissions.

The usecase is:

a) You switch Zammad into `maintenance_mode=true` because you want to setup a new permission concept
b) You implement the new permission concept (with new roles and so on)
c) Now you want to test if your newly configured permission concept works fine for other users, then you try to "switch to user" (note: `maintenance_mode=true` is still active because you want to verify the changes first) but it will not work (but should IMO if the admin is using `switch to user`).

**Comment by martini** [comment]
Workaround: If you was running into this issue, you always just get the blank screen. You need to delete all browser cookies until you get the login screen again. An easier workaround is to call the logout URL manually `https://zammad-host/api/v1/signout` got access the login screen again.

**Comment by itkfm** [comment]
This issue has also been discussed in the community forum:
https://community.zammad.org/t/wsod-with-view-from-users-perspective-while-in-maintenance-mode/8882

**Comment by dominikklein** [comment]
To me, a blank screen seems like a bug.
I understand the use case that an admin should have the ability to switch to a non-admin user during maintenance mode for testing reasons, but this feels more like an enhancement.
