### ISSUE TITLE
CentOS 7 Upgrade blocked due to incomplete PATH (pg_isready not found)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4816]
### Used Zammad Version

6.1 stable

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): CentOS 7 (only one I'm aware of, potentially any RHEL that uses postgresql repository directly due to their custom binary location)
- Database + version:  postgresql 14
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

During Upgrade or Installation, the database pre-flight  fails on CentOS 7 due to incomplete paths.
While `pg_isready` technically is installed, it cannot be found if administrators didn't ensure to add the correct path to their system.

```
/tmp/tmp.87EFFokHYU: line 31: pg_isready: command not found
!!! ERROR !!!
Your database does not seem to be online!
Please check your configuration in config/database.yml and ensure the configured database server is online.
Exiting Zammad package installation / upgrade - try again.
```

### Expected behaviour

Upgrade or installation of Zammad on CentOS 7 is running smoothly as long as it's still supported.

### Steps to reproduce the behaviour

- upgrade or install Zammad on CentOS 7

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
We disabled the connectivity check temporarily in https://github.com/zammad/zammad/commit/2776710a2b27b1d7f92ae2e1137606a5fda57e3f until the issues are sorted. As soon as the [builds are finished](https://packager.io/gh/zammad/zammad/builds/9456), you should be able to update without this issue.
