### ISSUE TITLE
Custom Fields doesn't work in the Core Workflow

### ISSUE THREAD

**Issue by itsupport-s2i** [zammad/zammad#4823]
### Used Zammad Version

6.1.0

### Environment

- Installation method: dockerhub-latest
- Operating system (if you're unsure: `cat /etc/os-release` ): k8s helm
- Database + version: 
- Elasticsearch version: 
- Browser + version: Chrome Version 117.0.5938.62 (Official Build) (64-bit)

### Actual behaviour

I've created additional customer fields
- ServiceCatalog: tree select : mandatory: show
- CustomFieldService1: not show
- CustomFiledService2: not show
![image](https://github.com/zammad/zammad/assets/113678203/4ac8a96a-da6e-4148-b50d-4c7f0474321b)

Then created Workflow in oder to show CustomerFiledService1 when Service1 has choosen

![image](https://github.com/zammad/zammad/assets/113678203/f0239f50-210c-4586-ad94-c741d80864c9)

In creating new ticket and chosing the Service1 the CustomFieldService1 hasn't been appeared
![image](https://github.com/zammad/zammad/assets/113678203/9d0e39d5-1683-46b9-8cbf-1c2adb5c3484)

### Expected behaviour

Due to the documentation I expected to see the field CustomFieldService1 when I chose the Service1 in the ServiceCatalog.
when I replace the workflow with embedded fields like Group, it works perfectly

### Steps to reproduce the behaviour

See above

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
works for me in latest stable. Please provide more information @fliebe92 or @itsupport-s2i  or let me know what i am missing

[screen-recorder-wed-oct-04-2023-13-53-39.webm](https://github.com/zammad/zammad/assets/5445062/7d1ce60b-1f09-41bf-bc31-276ec75914f2)

**Comment by rolfschmidt** [comment]
Looks like the websocket server does not update the database schema.

**Comment by rolfschmidt** [comment]
@itsupport-s2i did you restart your zammad service (webserver, websocket and scheduler) after creating the fields? (or docker)

**Comment by rolfschmidt** [comment]
@mgruner @MrGeneration does anybody of you know if the APP_RESTART_CMD is set in docker and working?

**Comment by MrGeneration** [comment]
> does anybody of you know if the APP_RESTART_CMD is set in docker and working?

I don't think that this is an option because the stack can't be restartet from inside the container automatically.
If it can it most likely is environment specific. I may be wrong though.

**Comment by rolfschmidt** [comment]
ok, however this is not a bug in zammad. After restarting all zammad services it should work in stable and develop as well without a problem.
