### ISSUE TITLE
Core Workflow - Action "Fill text if empty" will always be executed even if text field is not empty

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#4825]
### Used Zammad Version

6.1.x.7f6252aba.saas 

### Environment

- Installation method: SaaS, Package

### Actual behaviour

If you have a core workflow with the action "Fill text if empty", you cannot write any other text at the creation of a ticket per web in the text field, because it will always be overwritten with the stored text

https://github.com/zammad/zammad/assets/129729908/fdf35893-a906-485a-bb6b-ac78bd057f72

### Expected behaviour

Only autofill the text field if it is empty.

### Steps to reproduce the behaviour

See Screencast

### Support Ticket

Ticket#10140772

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tgb-sw** [comment]
Just updated to zammad 6.2.0-1702303938.81e0c1fd.bullseye 
This problem still exists in this version.
If you have a core workflow with the action "Fill text if empty", you cannot write any other text at the creation of a ticket per web in the text field, because it will always be overwritten with the stored text

**Comment by dominikklein** [comment]
I can not reproduce it in the current 6.2.

Did you refresh your browser fresh, maybe there is still an old state.

**Comment by tgb-sw** [comment]
Yes I refreshed it, also tested in a private window, even on a machine zammad was never opened, the issue occurs.

I also tested to disable the existing workflow and created a new one. 
![grafik](https://github.com/zammad/zammad/assets/13784396/4978583d-be40-4656-8bf4-d7070e4cf06b)

Create a new ticket, enter text:
![grafik](https://github.com/zammad/zammad/assets/13784396/9a6b1cea-16b4-4dd1-8db5-f7e1ef2aa6b8)

Choose the trigger "Typ = KVP Vorschlag" and text is replaced

![grafik](https://github.com/zammad/zammad/assets/13784396/c27032d6-4ded-4737-9a81-7a1d8cc1960b)

If you overtype the text, and click anywhere outside the textbox, it is also replaced.
What did I do wrong? As far as I can say the upgrade worked without issues.

**Comment by tgb-sw** [comment]
In the meantime I did a test installation of zammad 6.2 
In this installation it works as expected.

So somehow the upgrade in our production environment must have issues, maybe we have overseen an error in the upgrade :-/
everything else seems working for instance hierachical groups.

Just found out, that the new field format "external datasource" is also missing in our production environment. In the test installation it shows up.

Sorry, for complaining about the problem in the wrong place

**Comment by tgb-sw** [comment]
Maybe it helps others:
Migrating from mariadb to postgres solved these problems
