### ISSUE TITLE
Scheduler with '%' in title contains condition doesn't work anymore

### ISSUE THREAD

**Issue by herzkerl** [zammad/zammad#4827]
### Used Zammad Version

6.1

### Environment

- Installation method: package
- Operating system: Debian 10 (latest)
- Database + version: postgresql 9.3
- Elasticsearch version: latest
- Browser + version: Safari (latest)

### Actual behaviour

- Scheduler ignores `%` in conditions

### Expected behaviour

- Scheduler should correctly match those tickets
- Worked prior to updating to 6.1, so one would assume that the new regex functionality intoduced a regression—but since regex doesn't work with schedulers (yet?), I'd hope that my previous implementation would still work (worked fine for a few years!)

### Steps to reproduce the behaviour

- Create a schedule with the condition `title contains 'Ihre Rechnung % als PDF-Dokument'`
- We also check for a few other conditions (group, type, from, etc...)—once I remove the title condition from the list, the two tickets that should be processed show up!
- Create a ticket with the title 'Ihre Rechnung RE-23.1234 als PDF-Dokument'

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
Hello @herzkerl, thank you for your report. This is probably a side effect of https://github.com/zammad/zammad/commit/36e6598632adf67de0e24b9bba49d17a21adfe87. The '%' sign was previously passed to the SQL LIKE query without escaping, which was not intended to work this way and caused issues with certain queries. Please find other criteria such as `starts with` to describe your conditions.

**Comment by herzkerl** [comment]
@mgruner Thank you very much for clarifying. If I may ask: Is there any reason for Scheduler not to support the new 'matches/does not match regex' filters? Would love to see them there as well!

**Comment by mgruner** [comment]
Unfortunately, yes. Regex can only be used when looking at one ticket at a time in Ruby context, not when scanning the database to find multiple records, for performance reasons.

**Comment by herzkerl** [comment]
Thank you one again for replying quickly. Leaving that here for others: Now that there's time based triggers, I'll convert all scheduler jobs that fire when a ticket reaches pending and make them triggers—that might increase overall performance, as well.
