### ISSUE TITLE
Removing general notifications for all users will result in said users still being notified 

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4828]
### Used Zammad Version

6.1

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge, v.117.0.2045.31 (64-bit)

### Actual behaviour

When the general notification settings are removed and applied to all agents (becoming the new default), agents will continue to be notified based on the previous settings. 

### Expected behaviour

When the general notification settings are completely removed, no more notifications should be sent to customers (if this is set as the default setting for all users). 

### Steps to reproduce the behaviour

1) Remove all settings and make them the default for all agents.

a) 
<img width="954" alt="Screenshot 2023-09-20 135757" src="https://github.com/zammad/zammad/assets/101350124/28111634-d793-482c-8a0e-7cf737482974">

b) thus leading to this:
<img width="956" alt="Screenshot 2023-09-20 135847" src="https://github.com/zammad/zammad/assets/101350124/8a7bd9bf-c1c3-4e9e-80ed-069a7078dc8f">

2) Create a new ticket
3) Agents will still be notified, but based on the previous settings, thus ignoring the new default. 

### Support Ticket

Ticket#10140895

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Are we certain that there was enough time in between the action and the acknowledgement agents still receive notifications?
Notifications are delayed jobs and thus there might be a fairly big junk of mails still being in the sendout process which may raise the feel mails are being sent....?

**Comment by Suhopoljac** [comment]
It seems that applying the changes to the general settings took longer than expected in my case, as I also can no longer reproduce the issue.
