### ISSUE TITLE
Tables in mails are very high

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#4829]
### Used Zammad Version

6.1

### Environment

- Installation method: package
- Operating system: 20.04
- Database + version:  postgresql
- Elasticsearch version: 7.17
- Browser: Edge 117

### Actual behaviour

Tables (in my case the signature of our company) is streched very high after the upgrade to 6.1.
The data in the signature is not visible. Other customers tickets have the same problem in our system after installing 6.1.
We use: 6.1.0-1695212910.06e8f58e.focal

see this animation please:
![image](https://github.com/zammad/zammad/assets/1473674/1bcffbcd-8e8a-40af-944f-e221820bb8b1)

### Expected behaviour

Normal size and data visible

### Steps to reproduce the behaviour

Send an mail with a table as a signature

If you need more information I can post it here.

thank you!

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @Dennis1993 and thanks for the report. Could you please add a sample mail? This will help us in verifying and investigating this issue.

Thanks a lot!

**Comment by Dennis1993** [comment]
Thanks for your answer! :)

Of course, I saved the original ticket via Zammad (Original Formatierung unterm ersten Post):

This is the original code which is sent by email to out ticket system:

[message.txt](https://github.com/zammad/zammad/files/12781917/message.txt)


I hope it's right. Feel free to contact me for more details.

Thank you very much!

**Comment by fliebe92** [comment]
There is another button called `Raw`, this will download an EML file, this is the one I need 👍  could you please be so kind to attach the EML file here? Thanks for your help :)

**Comment by Dennis1993** [comment]
Ah okay, no problem. Here the EML-file. Thanks! :)
[ticket-5332385-164998.zip](https://github.com/zammad/zammad/files/12782067/ticket-5332385-164998.zip)

I've created a zip file because it's not allowed to upload eml files.
