### ISSUE TITLE
When an update via API fails, a notification is send to the agents that the change was made

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#4834]
### Used Zammad Version

6.1

### Environment

- Installation method: any
- Operating system : any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

I try to change the title of a ticket via API, the update fails since a mandatory files is empty.
(Works as intended)

But the agents receive a Notification that the title is changed.

### Expected behaviour

If the Title is not changed and the ticket is not updated, the agents should not receive a notification.

### Steps to reproduce the behaviour

-I created a predefined Teamswebhook
-I created a trigger: 
status> new, open
Group> users
execute:
webhook

-I created a custom object: 
test> text field
The Object is mandatory for customer and agent.

- I want to update an existing ticket (Id:140) that has a mandatory filed now "test"
```
curl -H "Authorization: Token token=XXXXXXXXXXXXXXXXXXXXX" --request PUT https://the link to Zammad/api/v1/tickets/140 -H 'Content-Type: application/json' --data '{

   "title": "Here we go"
   }'
{"error":"Missing required value for field 'test'!"}
```

After that, an Agent receives a notification email that the title was updated, even if the title is still the same in the ticket:
![image](https://github.com/zammad/zammad/assets/94919964/644d6753-0fef-4aaf-a7d2-91c8e330dadb)

### Support Ticket

Ticket #10139287

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @Bozo0511. I was not able to reproduce this issue. Do you have a test system up & running where we can investigate this?

**Comment by martini** [comment]
@fliebe92 I can reproduce it this way:

a) register new Zammad instance
b) Create an second agent 
c) Select welcome ticket in ticket overview for bulk action and change state to "removed"
d) Execute bulk action

Result:  
1) State is not updated, you will get an error message (see also https://github.com/zammad/zammad/issues/4848)
2) Notification has been sent to second agent (but ticket got not updated)
<img width="329" alt="Screenshot 2023-10-04 at 07 56 23" src="https://github.com/zammad/zammad/assets/110226/627c8dcb-bce0-4a84-99df-60bae9c11cc2">

**Comment by fliebe92** [comment]
@martini It's still not reproducible in a default installation (SaaS != default).

* With the state `new`, the update is fine.
* The state `removed` is not available on a local system, this seems to be something SaaS-specific (it's an inactive state by default). 
* After enabling the state `removed`, I can reproduce it.

**Comment by fliebe92** [comment]
This seems to be related to the possibility of mass-updating tickets.

**Comment by martini** [comment]
@fliebe92 

> It's still not reproducible in a default installation (SaaS != default).



> With the state new, the update is fine.

Was the updated ticket already in state `new` (it need to be not in state `new`)? 

> The state removed is not available on a local system, this seems to be something SaaS-specific (it's an inactive state by default).

Sorry, this was my fault. I enabled it for testing.

**Comment by martini** [comment]
@fliebe92 

> It's still not reproducible in a default installation (SaaS != default).

I also can reproduce it on default installation (`stable` branch == SaaS / and also on `develop` branch) with state e. g. `open` -> `new`.

![new-state](https://github.com/zammad/zammad/assets/110226/6f374b73-1c9a-4994-a741-644ddf5969da)

In case let me know and I can show you.

> With the state new, the update is fine.

Maybe the state before was already `new`? Then the bulk action will not change the state and for this it works fine.


> The state removed is not available on a local system, this seems to be something SaaS-specific (it's an inactive state by default).

Sorry, this was my fault. You are right, I enabled `removed` it for testing. JFI: SaaS has not specifics here.

**Comment by martini** [comment]
In addition, I tried to reproduce the steps from @Bozo0511 on current `develop` branch. And I was able to reproduce it.

I try to summarize it:
- create a ticket attribute which is mandatory 
- try to update the ticket title via api (note, updating via web app is not possible)

Result:
- ticket is not updated but all changes are fired (in my test case a webhook)

![execute-events-even-if-validataion-blocks-update](https://github.com/zammad/zammad/assets/110226/1b977c20-777b-444d-86dd-bf6b55c95755)

If you have questions, let me know.

**Comment by mantas** [comment]
Looks like the problem is that item is added to `EventBuffer` via `before_update`. Wether update fails or not, item is in `EventBuffer` and then triggers are triggered.

I wonder how many things would explode if it was changed to `after_update`

https://github.com/zammad/zammad/blob/d80710acaf7cad50b003bd6d6c4e02ae4d50f416/lib/transaction_dispatcher.rb#L197

**Comment by fliebe92** [comment]
> Looks like the problem is that item is added to `EventBuffer` via `before_update`. Wether update fails or not, item is in `EventBuffer` and then triggers are triggered.
> 
> I wonder how many things would explode if it was changed to `after_update`
> 
> https://github.com/zammad/zammad/blob/d80710acaf7cad50b003bd6d6c4e02ae4d50f416/lib/transaction_dispatcher.rb#L197

Maybe we can try to change the whole logic to `after_update` as a technical debt item. Would you like to do so, @mantas?

@rolfschmidt and I decided to not change this now, just get it fixed for Zammad 6.1 as soon as possible. This is why we're working on a small change right now.

**Comment by martini** [comment]
> Maybe we can try to change the whole logic to after_update as a technical debt item. Would you like to do so, @mantas?

IMO `after_commit` should be better.

**Comment by mantas** [comment]
> > Maybe we can try to change the whole logic to after_update as a technical debt item. Would you like to do so, @mantas?
> 
> IMO `after_commit` should be better.

I'm not sure. Then triggers should run in a separate transaction. Then if trigger fails it'd be stuck in pre-trigger state. But it may be better to restore whole action?

**Comment by dominikklein** [comment]
Did we also check how it was before the refactoring of the transaction dispatcher?
Sound completely wrong that to me.

**Comment by fliebe92** [comment]
> Did we also check how it was before the refactoring of the transaction dispatcher? Sound completely wrong that to me.

Yeah, we checked this: `before_update` was also used there.
