### ISSUE TITLE
Group > "Name" is displayed twice in core workflows

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad#4840]
### Used Zammad Version

6.2

### Environment

Testsystem from here: https://git.zammad.com/zammad/zammad/-/merge_requests/6702

### Actual behaviour

If you create a core workflow with object "Group" and want to select a group in conditions, you have the Group>"Name" twice.
![image](https://github.com/zammad/zammad/assets/60067527/03a6a3bf-7620-49a9-88e9-c79152523c13)

### Expected behaviour

I guess one of the "Name" is the "name_last". They should be renamed somehow that it is clear for the user, what the difference is.

Ideas: 

- Name (long)
- Name (short)

OR

- Name (group)
- Name (hierarchy)

But please feel free to choose another more fitting wording.

### Steps to reproduce the behaviour

Create a core workflow with `Object: Group` and click on the dropdown to select an attribute. 

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by martini** [comment]
1) @ralf401 JFI: The reference is this: https://github.com/zammad/zammad/blob/develop/db/seeds/object_manager_attributes.rb#L1762 and https://github.com/zammad/zammad/blob/develop/db/seeds/object_manager_attributes.rb#L1782 or you can also have a look under http://localhost:3000/#system/object_manager -> Group

2) I would expect to not show `name_last` and `parent_id` in conditions.

**Comment by ralf401** [comment]
>     2. I would expect to not show `name_last` and `parent_id` in conditions.

Yes it is probably sufficient to just use the "full" group name here. The `parent_id` makes indeed no sense. But I can imagine that providing the `parent_name` (don't know if it is the right name) in conditions would be good to have.
