### ISSUE TITLE
Two-factor authentication can not be used when change password profile is disabled

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4843]
### Used Zammad Version

6.2.x (develop)

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Currently, the usage of the two-factor authentication is limited when the change password profile is disabled for a role because the "authentication" section is the same profile section.

https://community.zammad.org/t/enable-mfa-settings-but-do-not-allow-password-change/12258

### Expected behaviour

It should be possible to use two-factor authentication, also when a user is not allowed to change the password inside the profile.
The use case is for example, when the users are synced from the LDAP source and because of that are not allowed to change the password inside Zamamd (because this means a own password inside the internal Zammad database).

### Steps to reproduce the behaviour

- Create a role without `user_preferences.password`.
![Bildschirmfoto 2023-09-29 um 16 18 02](https://github.com/zammad/zammad/assets/5445094/c527097e-b81d-460c-afa7-f32467d40eb3)
- Activate two-factor authentication.
- Login with a user which has only this role and see that you can not enter the `Password & Authentication` section inside the profile.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment]
Fixed by adding a separate `user_preferences.two_factor_authentication` permission.
