### ISSUE TITLE
"Copy ticket number" adds prefix

### ISSUE THREAD

**Issue by kimchipenguin** [zammad/zammad#4845]
### Used Zammad Version

6.0.0

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Copying the ticket number via the icon on the ticket page and pasting it in the search yields no result.

### Expected behaviour

Zammad should return the ticket as part of the search. Currently you'd have to remove "Ticket" from the copied text to get a result. It's expected that if someone copies a ticket number, a ticket number is copied - without any pre- or postfixes.

### Steps to reproduce the behaviour

1. One of our agents copied the ticket number from the ticket page
2. He gave another agent the copied text.
3. The agent pastes this text in the search box of his Zammad session 
4. No results due to the text "Ticket" prefixed to the actual ticket number.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Stubenhocker1399** [comment]
I'd personally expect the pre- or postfixes to exist when using the copy feature, maybe instead the search should be adjusted to handle searching for tickets directly with these additional pre/postfixes?

**Comment by dominikklein** [comment]
@kimchipenguin Thanks for the report. I think it's a good idea to improve the situation, but it's currently working as designed.
Please note that this repository is the wrong place for feature requests.
Instead, please refer to the Zammad community over at [Community](https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6).

**Comment by tschaefer** [comment]
The above commit message includes the wrong issue number. :man_facepalming:
