### ISSUE TITLE
Overview with condition 'subscribe -> is specific user' throws PG::CardinalityViolation when query hits more than one user

### ISSUE THREAD

**Issue by t-shehab** [zammad/zammad#4846]
### Used Zammad Version

6.1 (verified on 6.1.0.de69445a2.saas)

### Environment

- Installation method: verified on SaaS (probably any)
- Operating system: any
- Database + version:  psql (PostgreSQL) 11.20 (Debian 11.20-0+deb10u1)
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

![image](https://github.com/zammad/zammad/assets/114283486/c4c02780-04c1-4b53-9703-f017a2338ae2)

Having the above condition in an overview will throw the following error when both users are subscribed to a ticket:

```
/usr/local/rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.6/lib/active_record/connection_adapter/postgresql_adapter.rb:672:in `exec_params': PG::CardinalityViolation: ERROR:  more than one row returned by a subquery used as an expression (ActiveRecord::StatementInvalid)
```

After ten tries of this, Zammad's scheduler dies.

### Expected behaviour

* Correctly configured Overview conditions don't throw errors.
* Schedulers don't die.

### Steps to reproduce the behaviour

* Configure Overview like shown above.
* Have both users subscribed to a ticket
* Have this ticket show up in the Overview
* Then run the following command:

```ruby
user = User.find(<id>)
Ticket::Overviews.index(user)
```

# Note:
During a debugging session on a SaaS instance @martini applied the following hotfix to ensure only one hit is recognized:

```diff
$ git diff app/models/ticket/selector/sql.rb 
diff --git a/app/models/ticket/selector/sql.rb b/app/models/ticket/selector/sql.rb
index e8fd6b98d..e42088bd5 100644
--- a/app/models/ticket/selector/sql.rb
+++ b/app/models/ticket/selector/sql.rb
@@ -229,7 +229,8 @@ class Ticket::Selector::Sql < Ticket::Selector::Base
                  end
       else
         query << if block_condition[:operator] == 'is'
-                   "1 = (SELECT 1 FROM mentions mentions_sub WHERE mentions_sub.mentionable_type = 'Ticket' AND mentions_sub.mentionable_id = tickets.id AND mentions_sub.user_id IN (?))"
+                   #"1 = (SELECT 1 FROM mentions mentions_sub WHERE mentions_sub.mentionable_type = 'Ticket' AND mentions_sub.mentionable_id = tickets.id AND mentions_sub.user_id IN (?))"
+                   "1 = (SELECT 1 FROM mentions mentions_sub WHERE mentions_sub.mentionable_type = 'Ticket' AND mentions_sub.mentionable_id = tickets.id AND mentions_sub.user_id IN (?) LIMIT 1)"
                  else
                    "(SELECT 1 FROM mentions mentions_sub WHERE mentions_sub.mentionable_type = 'Ticket' AND mentions_sub.mentionable_id = tickets.id AND mentions_sub.user_id IN (?)) IS NULL"
                  end
$
```

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@t-shehab removed the blocker because it's nothing which lead to an "not working" system.

**Comment by martini** [comment]
@dominikklein if this condition is set, the background worker dies (after restarting, background worker dies again) and you get error messages in frontend for overviews. Maybe not a blocker but somehow more important as others.
