### ISSUE TITLE
Triggers don't function

### ISSUE THREAD

**Issue by kale1d0code** [zammad/zammad#4847]
### Used Zammad Version

6.1.0

### Environment

- Installation method: docker-compose
- Operating system (if you're unsure: `cat /etc/os-release` ):  Debian GNU/Linux 11 (bullseye)
- Database + version:  postgres 14.4
- Elasticsearch version: 8.8.0
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

Triggers to execute

### Expected behaviour

No automated behaviour

### Steps to reproduce the behaviour

Upgrade from 6.0.0

### I'm sure this is a bug and no feature request or a general question.

yes

### Production log
I, [2023-09-13T05:31:37.417029#4021-6320]  INFO -- : Using Zammad's file store as Rails cache store.
I, [2023-09-13T05:31:37.417319#4021-6320]  INFO -- : Using the File back end for Zammad's web socket session store.

**Comment by MrGeneration** [comment]
Please provide more information on how to reproduce this, otherwise it's going to be impossible.

**Comment by kale1d0code** [comment]
I found the relevant logging information in stdout.
I saw that the automation was being skipped due to zammad thinking the address did not want an autoresponder.

Not sure how it is relevant to the error message, but after disabling the option on our google workspaces for making sure only known addresses can be used. the automation is working.
