### ISSUE TITLE
Certain offered states can not be set (never) via the bulk action

### ISSUE THREAD

**Issue by martini** [zammad/zammad#4848]
### Used Zammad Version

6.1

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

In bulk action I can select ticket state which can never be used. I always get an error if I want to change it.

![bulk-invalid-states](https://github.com/zammad/zammad/assets/110226/95438abc-4881-4126-b251-d157afa4d897)

### Expected behaviour

Only show usable ticket states in bulk action.

Note: In ticket zoom/edit it's working fine! Here only `viewable_agent_edit` states from here https://github.com/zammad/zammad/blob/develop/db/seeds/object_manager_attributes.rb#L267 are used. We need to align this. 

### Steps to reproduce the behaviour

1) Select a ticket in a overview
2) got to bulk action elements and select state "removed" or "new"
3) Execute action -> You always will get an error message (because you can not change a ticket into this state)

### Support Ticket

Ticket#10141543

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
First analysis: When the element gets first rendered in `TicketBulkForm.render`, it has the correct filter set, which does not include the state `new`.

However, afterwards core workflow kicks in and resets that filter to all possible ticket states in `FormHandlerCoreWorkflow.restrictValues`. That seems to be why all active states are then selectable.
