### ISSUE TITLE
Understandable error message if/why a macro cannot be executed

### ISSUE THREAD

**Issue by martini** [zammad/zammad#4849]
### Used Zammad Version

6.1

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version:  any
- Browser + version:  any

### Actual behaviour

If I execute a macro with not valid attributes for this user/ticket I get an not understandable (for regular agents) error messages.

![invalid-attribute-missleading-error-message](https://github.com/zammad/zammad/assets/110226/13891375-b1b0-4c74-b221-3f09e54f61a3)

### Expected behaviour

Get an understandable (for regular agents) error messages.

### Steps to reproduce the behaviour

1) Create a macro which e. g. tries to set the ticket state "new" (or any other attribute which can`t get set)
2) Open a ticket which is e. g. in state "open"
3) Try to apply the macro

### Support Ticket

Ticket#10129719 (Article from 29/09/2023 16:48)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Looks like a duplicate from: https://github.com/zammad/zammad/issues/3864
