### ISSUE TITLE
Mail tickets are small and "read more" invisible if change title

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#4867]
### Used Zammad Version

6.1.0-1696431829.be2e21ee.focal

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): ubuntu 20.04
- Database + version:  postgresql
- Elasticsearch version: 7.17
- Browser + version: Microsoft Edge 117

### Actual behaviour

In some mail tickets the preview of the mail is very small. I can click on "Mehr anzeigen" and I can the all os the content.
If I don't click on the link "Mehr anzeigen" and change the title the content moves to the top out of my viewport. I cant open the ticket anymore an can't read the text. I need to refresh the page to see the ticket (see animation please)

![text moves to top](https://github.com/zammad/zammad/assets/1473674/8cbb95fa-64e8-485a-b9f4-ee29267dbd00)

I added the raw mail from zammad here for easier find the problem
[mail_raw.zip](https://github.com/zammad/zammad/files/12849395/mail_raw.zip)

### Expected behaviour

See more from the text by default and if I change the title the text shouldn't move to top out of the view of an agent.

### Steps to reproduce the behaviour

Change title and hit the TAB key on your keyboard. It is only on mail tickets with the small height.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hey @Dennis1993 👋🏻 

Could you please try to reproduce this issue again? I am not able to do so, even not by using the attached mail file (thanks for this!).

**Comment by mgruner** [comment]
No feedback, I'll close this report. Please feel free to update to the latest version of Zammad (6.3.1), reproduce the issue and let us know about it.
