### ISSUE TITLE
unable to login after migration from Zendesk

### ISSUE THREAD

**Issue by qschneider** [zammad/zammad#487]
Using the latest stable zammad build i was able to perform a successful Zendesk migration.
But after migration i could not login with valid zendesk credentials.
Any ideas what might cause this ?

**Comment by monotek** [comment]
I think passwords are not migrated.
You have to request a new password.

**Comment by qschneider** [comment]
ah, ok thanks.
I tried this with multiple migrated accounts, but no password reset email was send.
But i can create a new user and received an email confirmation from noreply@zammad.example.com

**Comment by martini** [comment]
@thorsteneckel Something for the documentation?

JFI: We don't get password a hash from the zendesk api. :-/

**Comment by qschneider** [comment]
Maybe it would be an idea to change the migration process at all ?
Something like having an option of setting up zammad first (or at least an admin user) and then migrating data ?

+1 for a documentation on what to expect from the migration + necessary steps afterwards.

Also i noticed that when providing the information for the migration process (url / user / apikey) i had to try multiple times because i got errors (timeouts, wrong credentials). Not sure, but the formfields are posted after each keypress, so this might cause that behavior ?

**Comment by qschneider** [comment]
FJI : i tried again to send an password reset email after migration, but at least for @me.com the sending address of noreply@zammad.example.com was not successfully delivered, not even as spam.
So i think there should be different way of accessing the system right after migration.

**Comment by thorsteneckel** [comment]
Hi @qschneider - thanks for your feedback! The refactoring of the Zendesk import backend is my next task.  Since we can't get the hashes via the API like @martini noted but we got the API key and the username. So my proposal would be to:

- [ ] Set the API key as the password of the import user
- [ ] Make sure the import user has admin privileges in Zammad
- [ ] Extend the documentation with this information
- [ ] Proposal: Show this information in the import view

This would enable the user to login with the credentials already present. After that a password change via the Zammad user profile would be possible.

What do you think?

**Comment by qschneider** [comment]
Yes, i think this would be a good solution.
Maybe also a forced password change for security reasons at first login ?

I also noticed more issues.
Some of them are possible bugs and some just might needs documentation, depending if they are zendesk api restrictions or not.

- you have to place a closing / in the url, otherwise my api token was not accepted by the migration wizard.
- migration speed feels slow (10 Minutes for 40 users and 80 tickets) - barely reaching 30/min of the 700/min possible.
- archived tickets aren't migrated - not sure at what point zendesk flags a ticket as archived. It is still accessible in the zendesk client by viewing a persons ticket history, but not in the regular agent view.
- ticket entries will be imported as html-code.

![zendesk-zammad-migration-result](https://cloud.githubusercontent.com/assets/3471813/20802475/736b35fa-b7ec-11e6-9dd1-e3cb76d3494a.png)

**Comment by thorsteneckel** [comment]
Hi @qschneider - please see the commit above. This fixes the following:

- [X] Login after import not possible
- [X] Comments show HTML markup
- [X] Missing tests

Would be great if you can check it out with our develop package and leave some feedback. I'll close this issue for now. Please create new issues if necessary. Thanks!
