### ISSUE TITLE
Tags/Mention conditions performance optimizations

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#4871]
### Used Zammad Version

6.1

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

On big systems with high ticket count overviews or conditions in general with tags or mentions are slow.

The reason for this are sub selects which takes too long because we can't use GROUP or HAVING in our selectors.

https://github.com/zammad/zammad/blob/635438210c3476816bf0bd0e520dd1a05734d253/app/models/ticket/selector/sql.rb#L386-L455

### Expected behaviour

Find improvements.

### Steps to reproduce the behaviour

- Have 8 millions of tickets
- Use ticket.tags or ticket.mention_user_ids as selector.

### Support Ticket

Ticket#10141894
Ticket#10144616
Ticket#10145543
Ticket#10145662

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
Very interesting learning is that its seems that sub selects with ticket contact will take much longer than building one generic tmp table which might be bigger. Removing the restriction on the ticket.id results in a cached tmp table which is much faster:

```
zp_0000xxxx => EXPLAIN SELECT COUNT(*) FROM tickets WHERE 2 = (
                                          SELECT
                                            COUNT(*)
                                          FROM
                                            tag_objects,
                                            tag_items,
                                            tags
                                          WHERE
                                            tickets.id = tags.o_id AND
                                            tag_objects.id = tags.tag_object_id AND
                                            tag_objects.name = 'Ticket' AND
                                            tag_items.id = tags.tag_item_id AND
                                            tag_items.name IN ('tag', 'spam')
                                        );
                                                  QUERY PLAN
---------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=73933483.57..73933483.58 rows=1 width=8)
   ->  Seq Scan on tickets  (cost=0.00..73933398.78 rows=33918 width=0)
         Filter: (2 = (SubPlan 1))
         SubPlan 1
           ->  Aggregate  (cost=10.84..10.85 rows=1 width=8)
                 ->  Nested Loop  (cost=0.42..10.84 rows=1 width=0)
                       Join Filter: (tags.tag_item_id = tag_items.id)
                       ->  Nested Loop  (cost=0.42..9.48 rows=1 width=4)
                             Join Filter: (tag_objects.id = tags.tag_object_id)
                             ->  Seq Scan on tag_objects  (cost=0.00..1.02 rows=1 width=4)
                                   Filter: ((name)::text = 'Ticket'::text)
                             ->  Index Scan using index_tags_on_o_id on tags  (cost=0.42..8.44 rows=1 width=8)
                                   Index Cond: (o_id = tickets.id)
                       ->  Seq Scan on tag_items  (cost=0.00..1.34 rows=2 width=4)
                             Filter: ((name)::text = ANY ('{Zalando,spam}'::text[]))
 JIT:
   Functions: 22
   Options: Inlining true, Optimization true, Expressions true, Deforming true
(18 rows)

zp_0000xxxx => EXPLAIN SELECT COUNT(*) FROM tickets WHERE tickets.id IN (
                SELECT
                  tags.o_id
                FROM
                  tag_objects, tag_items, tags
                WHERE
                  tag_objects.id = tags.tag_object_id
                  AND tag_objects.name = 'Ticket'
                  AND tag_items.id = tags.tag_item_id
                  AND tag_items.name IN ('tag', 'spam')
                GROUP BY
                  tags.o_id
                HAVING
                  COUNT(*) = 2
              );
                                                   QUERY PLAN
----------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=10796.86..10796.87 rows=1 width=8)
   ->  Nested Loop  (cost=10111.78..10796.62 rows=96 width=0)
         ->  Finalize HashAggregate  (cost=10111.35..10352.46 rows=96 width=4)
               Group Key: tags.o_id
               Filter: (count(*) = 2)
               ->  Gather  (cost=8343.21..10030.98 rows=16074 width=12)
                     Workers Planned: 2
                     ->  Partial HashAggregate  (cost=7343.21..7423.58 rows=8037 width=12)
                           Group Key: tags.o_id
                           ->  Hash Join  (cost=2.40..7303.03 rows=8037 width=4)
                                 Hash Cond: (tags.tag_object_id = tag_objects.id)
                                 ->  Hash Join  (cost=1.36..7170.38 rows=16074 width=8)
                                       Hash Cond: (tags.tag_item_id = tag_items.id)
                                       ->  Parallel Seq Scan on tags  (cost=0.00..6509.99 rows=216999 width=12)
                                       ->  Hash  (cost=1.34..1.34 rows=2 width=4)
                                             ->  Seq Scan on tag_items  (cost=0.00..1.34 rows=2 width=4)
                                                   Filter: ((name)::text = ANY ('{Zalando,spam}'::text[]))
                                 ->  Hash  (cost=1.02..1.02 rows=1 width=4)
                                       ->  Seq Scan on tag_objects  (cost=0.00..1.02 rows=1 width=4)
                                             Filter: ((name)::text = 'Ticket'::text)
         ->  Index Only Scan using tickets_pkey on tickets  (cost=0.43..4.62 rows=1 width=4)
               Index Cond: (id = tags.o_id)
(22 rows)
```

**Comment by rolfschmidt** [comment]
https://stackoverflow.com/questions/12943960/having-clause-vs-subquery

**Comment by mk-git** [comment]
Something broke with this commit. I installed it this morning (deb release) and all tag based things are not working anymore (agent views, triggers for new mails) or are reversed? I had to change my rules from "enthält eins nicht" to "enthält alle nicht". Sorry german screenshot only.
<img width="488" alt="image" src="https://github.com/zammad/zammad/assets/4411025/b8c253b0-abdc-481d-acd8-1afdb21e249e">

**Comment by rolfschmidt** [comment]
Hi @mk-git , we will check that. Thx for your help.

**Comment by rolfschmidt** [comment]
@mk-git tomorrow `contains one not` will behave like before. Maybe we will change this behaviour in the future. I still believe the current behaviour is not correct, because `contains one not` does not respect tickets without tags. But it might make sense to wait until `is set` and `not set` operators are available for tags as well.

`contains all not` will at least change for now. This behaviour is definitely not correct. I will list the current behaviour here now. It is also equal now between reporting (elasticsearch) and overviews&triggers (psql):

Tests are for 3 tickets
- A ticket with tag `a`
- A ticket with tag `a,b`
- A ticket without tags

e.g.
contains all checks tags a = 2 
(2 tickets match for contains all with tags a)

```
Ticket::Selector::Base
  Tags
    contains all
      checks tags a = 2
      checks tags a, b = 1
      checks tags a, c = 0
      checks tags a, b, c = 0
      checks tags c, d = 0
      checks tags d = 0
    contains one
      checks tags a = 2
      checks tags a, b = 2
      checks tags a, c = 2
      checks tags a, b, c = 2
      checks tags c, d = 0
      checks tags d = 0
    contains all not
      checks tags a = 1
      checks tags a, b = 2
      checks tags a, c = 3
      checks tags a, b, c = 3
      checks tags c, d = 3
      checks tags d = 3
    contains one not
      checks tags a = 1
      checks tags a, b = 1
      checks tags a, c = 1
      checks tags a, b, c = 1
      checks tags c, d = 3
      checks tags d = 3
```

**Comment by mk-git** [comment]
Thanks @rolfschmidt  for the information. So I have to change my logic back after the update 😉 

To be honest, I never understood the logic with the tags and in the mask where I can define the views. I played with all the options until the number of tickets displayed due to the filter was realistic.

I have also been wondering how exactly it comes about. But I also know that NOT (!) filters with one or more tags are much more difficult programming-wise.

Do I understand you correctly that the behavior is now again as before, but will change again? Because if so, I think this is a change that will affect many systems, right? For us, for example, the "automatically reply to new tickets by mail" trigger has killed, because there will still check whether one or more tags are already set and then accordingly do not trigger the trigger.

**Comment by rolfschmidt** [comment]
Yeah, contains one should behave now as before. No more changes planned for now. We had to touch this code because it was very slow, and our systems are growing.

**Comment by rolfschmidt** [comment]
Note: package ofc needs time to build, so tomorrow it should be changed.

**Comment by MarkusHeld** [comment]
It currently looks like the two operators are swapped in my instance. "contains all not" behaves as I expect it from "contains one not" and the other way.

Zammad: Version 6.1.0.c4a2d0292.saas

**Comment by MarkusHeld** [comment]
Example tested with a Trigger

Operator „contains all not“ Tags  ( Tag1 and Tag2)

![Bildschirmfoto 2023-10-27 um 12 16 53](https://github.com/zammad/zammad/assets/129729908/ffc89c8d-30fc-4e05-a851-996c225c9a96)


1. Matches, when Tag1 and Tag2 are not set (correct)
2. Matches, when only Tag1 or Tag2 is set (not correct)
3. Doesn’t match, when Tag1 and Tag2 are set (correct)

In my opinion it should only match then Tag1 and Tag2 are not set like in Number 1


Operator „contains one not“ Tags ( Tag1 and Tag2)

![Bildschirmfoto 2023-10-27 um 12 16 29](https://github.com/zammad/zammad/assets/129729908/983e9ab4-f45e-49b6-b272-a42c3420470a)


1. Matches when Tag1 and Tag2 are not set (like operator contains all not)
2. Doesn’t match, when only Tag1 or Tag2 is set (not correct)
3. Doesn’t match, when Tag1 and Tag2 are set (correct)

In my opinion it should only match, then one Tag is not set like in Number 2

**Comment by rolfschmidt** [comment]
@MarkusHeld Can you give me your opinion what tickets you expect to see based on these 2 screenshots?

# contains all not

![image](https://github.com/zammad/zammad/assets/5445062/707d4c4f-85b7-4d98-8313-22af5d486b46)

I understand it like contains all not tag1 AND tag2, which would match the screenshot:

All tickets are shown except the ticket with title **test tag1+tag2** which has exactly these 2 tags.

# contains one not

![image](https://github.com/zammad/zammad/assets/5445062/241130d0-6fbf-405c-9f95-efab7d764eaa)

I understand it like contains one not tag1 OR tag2, which would match the screenshot:

- The ticket without tags is shown because it does not match tag1 or tag2
- The ticket with tag 3 is shown because it does not match tag1 or tag2.

All others contain one or the other or both.

(This is Zammad version 6.1.0.c4a2d0292.saas)

**Comment by MarkusHeld** [comment]
not so easy, in my **opinion**

In „contains all not“ i only wan’t to see the tickets which none of the specified Tags are set

these Tickets i wan’t to see
- Tag1 and Tag2 are not set
- Tag3 if in the Ticket the specified Tag1 and Tag2 are not set


in „contains one not“ i only wan’t to see there is one specified Tag missing

these Tickets i wan’t to see
- Tag1 are not set
- Tag2 are not set
- Tag3 if one of the specified Tag1 or Tag2 is missing
- Tag1 and Tag2 are not set, but here I'm not sure, because that's actually „contains all not“

**Comment by rolfschmidt** [comment]
@MarkusHeld  Can you please provide me a precise list what tickets you would expect.

Here is an example for the current state:
```
# All tickets

Ticket#50191: test no tags
Ticket#50184: test tag1
Ticket#50185: test tag2
Ticket#50192: test tag3
Ticket#50186: test tag1+tag2
Ticket#50193: test tag2+tag3

# Overview contains all not tag1,tag2

Ticket#50191: test no tags
Ticket#50184: test tag1
Ticket#50185: test tag2
Ticket#50192: test tag3
Ticket#50193: test tag2+tag3

# Overview contains one not tag1,tag2

Ticket#50191: test no tags
Ticket#50192: test tag3
```
For me your answer is not clear.

**Comment by MarkusHeld** [comment]
# All tickets

Ticket#50191: test no tags
Ticket#50184: test tag1
Ticket#50185: test tag2
Ticket#50192: test tag3
Ticket#50186: test tag1+tag2
Ticket#50193: test tag2+tag3

# Overview contains all not tag1,tag2

Ticket#50191: test no tags => shown
Ticket#50184: test tag1 => not shown
Ticket#50185: test tag2 => not shown
Ticket#50192: test tag3 => shown, when tag1 and tag2 not set, otherwise not shown
Ticket#50193: test tag2+tag3 => not shown

# Overview contains one not tag,tag2

Ticket#50191: test no tags => unsafe, in my opinion shown
Ticket#50192: test tag3 => shown, when one or both of tag1 or tag2 is missing, otherwise not

**Comment by rolfschmidt** [comment]
@MarkusHeld  So your expected result would be like this?

```
# Overview contains all not tag1,tag2

Ticket#50191: test no tags
Ticket#50192: test tag3

# Overview contains one not tag1,tag2

Ticket#50191: test no tags
Ticket#50192: test tag3
```

For me this looks the same. Can you please provide a list and copy and paste the tickets to a final result you would expect instead of commenting mine one?

**Comment by MarkusHeld** [comment]
@rolfschmidt now i understand - here's your list

```
# All tickets

Ticket#50191: test no tags
Ticket#50184: test tag1
Ticket#50185: test tag2
Ticket#50192: test tag3
Ticket#50186: test tag1+tag2
Ticket#50193: test tag2+tag3

# Overview contains all not tag1,tag2

Ticket#50191: test no tags
Ticket#50192: test tag3


# Overview contains one not tag1,tag2

Ticket#50191: test no tags
Ticket#50184: test tag1
Ticket#50185: test tag2
Ticket#50192: test tag3
Ticket#50193: test tag2+tag3
```

**Comment by rolfschmidt** [comment]
@MarkusHeld  So basically you are saying the results are correct and everything should be the same except that the operators should be flipped.

I actually would disagree at the moment. But I feel like these operators have a lot of room for interpretation. Maybe it makes sense to catch more opinions on this, maybe on the offsite or mattermost? 

What I can say is that the behaviour of these 2 operators were the same before my improvements, so one of them (the one which expects to have an exact combination [contains all not]) did not really exist before.

I think we already did some damage by even fixing this in stable. If we really should change anything then we should consider only changing the display name in the UI.

**Comment by MarkusHeld** [comment]
@rolfschmidt 

_So basically you are saying the results are correct and everything should be the same except that the operators should be flipped._

This is my first impression, but I will have to test it in more detail

**Comment by MarkusHeld** [comment]
@rolfschmidt I have now done another test here and yes for me swapping the names would make sense. 

But of course it would be good if more people look over it. So far I discussed it with my support colleagues and these are of a similar opinion.

One possibility might be to restore the old status and discuss in the offsite what is expected from the respective operators, but in my opinion, when the names are changed, the operator behaves exactly as i expect it.

From our Documentation

![image1](https://github.com/zammad/zammad/assets/129729908/48867639-a51b-4715-af98-b0cf84403400)

https://admin-docs.zammad.org/en/latest/misc/object-conditions/basics.html

```
# All tickets
Test without Tags
Test Tag1
Test Tag2
Test Tag3
Test Tag1 and Tag2
Test Tag3 and Tag1
Test Tag3 and Tag2
```

What I expect

```
# Overview contains all not tag1,tag2
Test without Tags
Test Tag3

# Overview contains one not tag1,tag2
Test without Tags
Test Tag1
Test Tag2
Test Tag3
Test Tag3 and Tag1
Test Tag3 and Tag2
```

What I get

```
# Overview contains all not tag1,tag2
Test without Tags
Test Tag1
Test Tag2
Test Tag3
Test Tag3 and Tag1
Test Tag3 and Tag2

# Overview contains one not tag1,tag2
Test without Tags
Test Tag3
```

Tickets with same opinion:
Ticket#10144616
Ticket#10145543

**Comment by rolfschmidt** [comment]
The statement still stays that the "contains one not" and "contains all not" behaved the same. So just change your operator to contains one not and everything will be like before.

If you want to help to improve zammad for the naming, then look here: 

https://github.com/zammad/zammad/issues/4916

For supporters, if you still believe different, please prove me wrong on:

https://early61.zammad.com/#ticket/view/contains_all_not_tag1_tag2
https://now61.zammad.com/#ticket/view/contains_one_not_tag1_tag2

(ping me for credentials)
