### ISSUE TITLE
S3: Lack of error and status messages.

### ISSUE THREAD

**Issue by tschaefer** [zammad/zammad#4873]
### Used Zammad Version

develop

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

As an administrator, the current lack of error and status messages makes it hard to retrace configuration, connection, and action issues. As an agent, customer the messages are unclear.

### Expected behaviour

Present simple and evident information to the users (agent, customer). Provide detailed Information to the administrator, to help to repair the misbehavior.

### Steps to reproduce the behaviour

* Set up a working Simple Storage Service as Zammad Storage Provider.
* Interrupt the connection to the Service.
* Try to create a new ticket with an attachment.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
In some situations there is "Internal Server Error" during the upload (e.g. bucket not existing or wrong access keys):


![Image](https://github.com/zammad/zammad/assets/5445094/0e6c0db6-1e37-4427-b5ee-c0d0a0035a21)
