### ISSUE TITLE
Body of emails is squashed (e.g. with Ebay correspondences)

### ISSUE THREAD

**Issue by t-shehab** [zammad/zammad#4874]
### Used Zammad Version

6.1

### Environment

- Installation method: package
- Operating system: verified on Ubuntu 20.04
- Database + version:  psql (PostgreSQL) 12.16 (Ubuntu 12.16-0ubuntu0.20.04.1)
- Elasticsearch version: 7.17
- Browser + version: FF 118.0.1

### Actual behaviour

Text in emails containing Ebay correspondence is squashed.

![image](https://github.com/zammad/zammad/assets/114283486/d1bfeb73-1d41-45b1-870a-6a4d22ce080e)

### Expected behaviour

Text in emails containing Ebay correspondence is not squashed.

### Steps to reproduce the behaviour

Import attached example email into Zammad.

[example.txt](https://github.com/zammad/zammad/files/12880251/example.txt)

### Support Ticket

Ticket#10124624

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mdz0r** [comment]
Having the same issue since migration to 6.1. Wasn't happening before (5.4).

Email formatting is OK when downloading ticket in eml or html format.

**Comment by fliebe92** [comment]
Could you please attach a sample mail, @mdz0r? There is already one in the first post, I know, but it would help us in general. Thx!

**Comment by mdz0r** [comment]
I'm afraid I can't provide you the emails, containing sensitive data. Problem is occuring in our signatures. I've attached the HTML code.

A workaround for us was to fix the width of the rows in the table in our signature manager.

[sign.txt](https://github.com/zammad/zammad/files/13474634/sign.txt)

Rendering in zammad :
![image](https://github.com/zammad/zammad/assets/42241744/08591549-86a1-490f-9080-15a9af24d2e0)

Hope it helps!
