### ISSUE TITLE
Make tests deterministic

### ISSUE THREAD

**Issue by corny** [zammad/zammad#488]
Tests should always have the same result - independent of the location and (non)existent internet connection. Gems that help:
* [VCR](https://relishapp.com/vcr/vcr/docs)
* [WebMock](https://github.com/bblimke/webmock)
* [RSpec Mocks](https://www.relishapp.com/rspec/rspec-mocks/docs)

**Comment by thorsteneckel** [comment]
Absolutely! You might saw the changes to the OTRS import which uses RSpec (with Mocks)... We are refactoring the tests as a side project with this as a main target. Thanks for the proposed gems.

**Comment by corny** [comment]
I suggest you to merge refactorings as soon a possible. Drifting branches become harder to merge.

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
