### ISSUE TITLE
different behaviour of contains all not in automizations

### ISSUE THREAD

**Issue by coolsurfer** [zammad/zammad#4884]
### Used Zammad Version

6.1

### Environment

not relevant

### Actual behaviour

Automation rule -> Tags “does not contain all” (any 3 tags set) finds the tickets where only one or two of the tags are present. In the past, it was enough for one of the three to be present for the rule to not apply

### Expected behaviour

If one of the tags defined is present in the ticket, the rule must not apply

### Steps to reproduce the behaviour

![image](https://github.com/zammad/zammad/assets/26963673/a6036421-b534-4b3a-898a-a7a288bde7ea)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Please use english, thank you.

**Comment by coolsurfer** [comment]
> Please use english, thank you.

done

**Comment by rolfschmidt** [comment]
@coolsurfer 

`contains all not` was bugged. It should match where all 3 tags are not present. Please switch your operator to `contains one not` (enthält eins nicht).

Please excuse the inconveniences.

(https://github.com/zammad/zammad/issues/4871)
