### ISSUE TITLE
Integrate Coveralls and add coverage badge

### ISSUE THREAD

**Issue by corny** [zammad/zammad#489]
Since we already use Travis and Simplecov the step to [Coveralls](https://coveralls.io/) is quite easy to go. The test results just have to be pushed to Coveralls by Travis and we get fancy statistics.

**Comment by monotek** [comment]
Tried to implement it today but it does not work.

https://github.com/zammad/zammad/tree/coveralls?files=1

I can see coveralls in the Travis build log but there is nothing shown on coveralls.io.

https://coveralls.io/github/zammad/zammad

Do you have experience with the configuration?

**Comment by corny** [comment]
I have never used it with more than one test suite. Try to create a new rake task:
```ruby
require 'coveralls/rake/task'
Coveralls::RakeTask.new
task :test_with_coveralls => [:spec, 'test:units', 'test:controllers', 'coveralls:push']
```
And run it instead of the single tests in the `.travis.yml`:
```yaml
script:
- rake db:create
- rake db:migrate
- rake db:seed
- bundle exec rake :test_with_coveralls
# ...
```
References:
- https://coveralls.zendesk.com/hc/en-us/articles/201769485-Ruby-Rails (Merging multiple test suites)
- https://github.com/colszowka/simplecov#merging-results

**Comment by monotek** [comment]
Works now and is live in develop. 
Not completely sure if tests needs to be changed in any way.
Having only 4% covered by tests looks a bit odd to me...

**Comment by corny** [comment]
I think the problem is that you have multiple test suites and the results are not merged:
> result sets that are older than SimpleCov.merge_timeout will not be used any more
Try to raise the timeout: https://github.com/colszowka/simplecov#timeout-for-merge

**Comment by monotek** [comment]
OK. Fixed. Closing...

**Comment by corny** [comment]
Thanks, looks good :+1:
