### ISSUE TITLE
Setting a group via CoreWorkflow in the ticket creation mask does not update text module filters and email signatures

### ISSUE THREAD

**Issue by t-shehab** [zammad/zammad#4891]
### Used Zammad Version

6.1

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

This is related to, but not a duplicate of: https://github.com/zammad/zammad/issues/4890

If you set a group via CoreWorkflow, all text modules are available, regardless of group restriction.

[coreworkflow_group_textmodules.webm](https://github.com/zammad/zammad/assets/114283486/007cc3d3-c07d-4532-83cb-049d030b6592)

### Expected behaviour

Text modules are restricted as per the group set, no matter if set manually or via CoreWorkflow.

### Steps to reproduce the behaviour

See the video above.

### Support Ticket

Ticket#10139550

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by YetAnotherGerrit** [comment]
This also effects signatures! When you select a group via Core Workflow and have a "Send Email" ticket creation mask, the Email signature is not updated.

It seems that several routines, that should be updated when a group is selected are not activated if the group is selected by a Core Workflow.
