### ISSUE TITLE
KB security: category permissions should be accessible to admins only

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4893]
### Used Zammad Version

6.1

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When granting users with editor permission to a part of your knowledge base they are able to grant themself all permissions in all parts of the KB.

### Expected behaviour

When I want to limit editor permissions for users to specific KB categories, they are not able to grant themselves permission to other categories.

### Steps to reproduce the behaviour

1. Create a role with `knowledge_base.editor` permissions.
2. Limit their access to a specific category.
3. Login with that user and go to the root of the KB, select permission and remove the limited access to a category.

**Suggestion**: bind the "🔒Permissions"-button of the KB to the `admin.knowledge_base` permission, instead to the `knowledge_base.editor` permission.

![image](https://github.com/zammad/zammad/assets/97293098/b430fd44-2e31-40d4-bc9a-418fc5d6679e)

### Support Ticket

Ticket#10126111

### I'm sure this is a bug and no feature request or a general question.

It's not a bug, but a serious design flaw.

**Comment by dominikklein** [comment]
@YetAnotherGerrit Currently, I can not reproduce the problem with the described steps. Maybe you can add more details (for me it was only possible when I had an additional role that could potentially have `knowledge_base.editor` permission).
