### ISSUE TITLE
Session list does not fetch users’ names

### ISSUE THREAD

**Issue by itkfm** [zammad/zammad#4894]
### Used Zammad Version

6.1.0-1696588423.6f218e78.bullseye

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian 11 “Bullseye”
- Database + version:  postgresql 13
- Elasticsearch version: 7.17.13
- Browser + version: Firefox 118.0.2

### Actual behaviour

Zammad only display’s the user information it has already available.
Sessions of users that haven’t been loaded yet will show up with no name.
![image](https://github.com/zammad/zammad/assets/53079668/76ef6945-eb7f-4917-9251-961ce25daa09)

### Expected behaviour

Zammad fetches the user information for all sessions so that each entry has a visible name.

### Steps to reproduce the behaviour

1. Setup a Zammad instance with a whole lot of users.
2. Let users with big IDs log in.
3. Log in to an admin account (ideally one with no agent permissions).
4. Don't open the user list or anything else that could make Zammad fetch additional other user information.
5. Go straight to the session list in the admin settings.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Also affects develop.
