### ISSUE TITLE
updated_by_id isn't correctly set in the ticket table

### ISSUE THREAD

**Issue by HanSolo72** [zammad/zammad#4906]
### Used Zammad Version

6.1

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 12
- Database + version:  postgresql
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

An agent changes something in a ticket and in the database in the ticket table the field updated_by_id is set to 1 instead of the id of the current agent.

If a customer sends an email to Zammad, the correct id (of the customer) is set to updated_by_id, but if in agents takes this ticket and, as example, changes the owner, updated_by_id is set to 1 also.

If a customer loggs in and changes something, updated_by_id is correctly set to the cusotmer's id.

### Expected behaviour

updated_by_id should be set the id of the agent who updated the ticket, not to 1.

### Steps to reproduce the behaviour

Create a ticket as agent and look at the field updated_by_id in the ticket table.

You can also send an email to Zammad. updated_by_id will be set correctly, but after the agent updates that ticket, it's also set to 1.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @HanSolo72 and thanks for the report.

I just used some time to reproduce your reported behavior and for me, it's working fine. Do you have any triggers or something else in place that is updating some attributes of the ticket afterward and changing `updated_by_id` to `1`?

Thanks for your help!

**Comment by HanSolo72** [comment]
You're right. To check this I disabled all triggers and then updated_by_id was set correctly. Then I enabled the triggers one by one.

I have a trigger that sends an e-mail and sets the ticket state to open.

I guess that some kind of zammad service changes that state and so the last update user is the zammad service with id 1. The question is then is it still a bug or is this behaviour by design? From an user's point of view I would say it's a bug, because I want to know who was the last one who edited this ticket.

**Comment by fliebe92** [comment]
Triggers are executed by the system itself and if the ticket is somehow updated by this, it is totally correct to change `updated_by_id` to `1` (= system user). This is not a bug.

You can also take a look into the ticket history for this, there all the changes for a specific ticket should be written down properly.
