### ISSUE TITLE
Zammad adding FQDN to user in the notifications email add form

### ISSUE THREAD

**Issue by dormancygrace** [zammad/zammad#4909]
### Used Zammad Version

6.1.0

### Environment

- Installation method: docker
- Operating system (if you're unsure: `cat /etc/os-release` ): docker
- Database + version:  postgresql 15.3
- Elasticsearch version: 8
- Browser + version: chrome 118

### Actual behaviour

FQDN added to user when adding notifications email. Example:

FQDN: support.xxxxx.yy
can't add notifications email, because if i use correct login noreply@xxxxx.yy zammad will add FQDN and resulting user changes to noreply@xxxxx.yy.support.xxxxx.yy
So the only way i can add notifications email is to use FQDN xxxxx.yy

### Expected behaviour

Zammad not adding FQDN to the user of the notifications email form

### Steps to reproduce the behaviour

just try to add notifications email

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
This sounds like a technical question to be honest.
I still don't really understand at which  part the email address is being changed? Does this affect the sender address or recipient address?

What's the exact error message?

**Comment by dormancygrace** [comment]
It affects notifications channel. I've started from scratch and it happens
even on first launch

**Comment by MrGeneration** [comment]
Sorry this still doesn't answer my question. What are the exact error messages you receive?

**Comment by dormancygrace** [comment]
I'll record video

**Comment by dormancygrace** [comment]
Ok, fully fresh instance of zammad: FQDN on initial setup is sfera-35.ru (it's the only way to add notifications email). Mail server needs full email as login, but if i use full login i'm getting error 550 5.7.60 smtp; client does not have permissions to send as this sender)
![image](https://github.com/zammad/zammad/assets/20384748/c51ddfd5-1044-43aa-bd3a-64ef73e80e22)

![image](https://github.com/zammad/zammad/assets/20384748/17788025-e114-4aa8-b931-45dc6f1c8751)

now, i'll change FQDN to correct one (all other settings stays same):

![image](https://github.com/zammad/zammad/assets/20384748/a33151b4-875b-4b81-9087-ab0cd6100fc7)
![image](https://github.com/zammad/zammad/assets/20384748/a0719ca6-1551-4ac7-9456-429e57e7bafb)
![image](https://github.com/zammad/zammad/assets/20384748/aed1c86f-5106-4dc2-bd35-1b98e0f50f91)


```
I, [2023-10-29T14:45:58.744209#1-66080]  INFO -- : Started POST "/api/v1/users" for 10.35.1.227 at 2023-10-29 14:45:58 +0300
I, [2023-10-29T14:45:58.752753#1-66080]  INFO -- : Processing by UsersController#create as JSON
I, [2023-10-29T14:45:58.752852#1-66080]  INFO -- :   Parameters: {"login"=>"93676424@inbox.ru", "firstname"=>"John", "lastname"=>"Smith", "email"=>"93676424@inbox.ru", "password"=>"[FILTERED]", "role_ids"=>[], "signup"=>true, "id"=>"c-0"}
E, [2023-10-29T14:45:59.627916#1-66080] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: Net::SMTPFatalError>
E, [2023-10-29T14:45:59.628102#1-66080] ERROR -- : 550 5.7.60 SMTP; Client does not have permissions to send as this sender
 (Net::SMTPFatalError)
app/models/channel/driver/smtp.rb:93:in `send'
app/models/channel.rb:257:in `deliver'
lib/notification_factory/mailer.rb:172:in `send'
lib/notification_factory/mailer.rb:225:in `notification'
app/controllers/users_controller.rb:1088:in `create_signup'
app/controllers/users_controller.rb:98:in `create'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2023-10-29T14:45:59.666684#1-66080] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: Net::SMTPFatalError> (RuntimeError)
app/models/channel.rb:270:in `rescue in deliver'
app/models/channel.rb:245:in `deliver'
lib/notification_factory/mailer.rb:172:in `send'
lib/notification_factory/mailer.rb:225:in `notification'
app/controllers/users_controller.rb:1088:in `create_signup'
app/controllers/users_controller.rb:98:in `create'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2023-10-29T14:45:59.680481#1-66080] ERROR -- : Error ID -AaudHCL: Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: Net::SMTPFatalError>
I, [2023-10-29T14:45:59.681112#1-66080]  INFO -- : Completed 500 Internal Server Error in 928ms (Views: 0.4ms | ActiveRecord: 111.9ms | Allocations: 31683)
```

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

Also see our documentation: https://admin-docs.zammad.org/en/latest/channels/email/accounts/email-notification.html

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by dormancygrace** [comment]
why you think it's a question? It's tech issue for sure

**Comment by dormancygrace** [comment]
why FQDN added to user in the notifications channel? it's beyond any logic

**Comment by MrGeneration** [comment]
If you don't understand why, please refer our Community forum. This is not a bug of Zammad.

**Comment by dormancygrace** [comment]
So, i can't use email for notification with domain that differs from fqdn, correct?

**Comment by MrGeneration** [comment]
I'm locking this Issue due to technical questions being spammed to this issue. Please accept our way of handling technical questions, consult our documentation and forum if you still can't wrap your head around this. This issue is the wrong place for this.
