### ISSUE TITLE
Use polymorphic associations in the Rails way

### ISSUE THREAD

**Issue by corny** [zammad/zammad#491]
Many models have `object` and `o_uid` columns. They should be renamed to match the polymorphic association requirements. For instance `item_type` and `item_id`. Then associations should be added to the models:
http://guides.rubyonrails.org/association_basics.html#polymorphic-associations

**Comment by corny** [comment]
This will break the Notification REST API: https://docs.zammad.org/en/latest/api-notification.html

**Comment by corny** [comment]
@martini @monotek I would like to do this task after you merged the `travis-ci-tests` branch. When do you plan to merge that branch?

**Comment by monotek** [comment]
Its already done...

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
