### ISSUE TITLE
Custom timestamp in auto responders (trigger based)

### ISSUE THREAD

**Issue by martini** [zammad/zammad#4911]
Assignees: @fliebe92 @tschaefer 

### Used Zammad Version

6.1

### Environment

- Installation method: 6.1
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### WHAT:
In trigger based auto responser (and also scheduler), currently time fields / variables are replaced with in the system timestamp (timezone_default and locale_default). E. g. `06/11/2023 09:45 (Europe/Berlin)` and I can not adjust those to my needs which can in some cases lead to confusion. 

### USE CASES:
a) I am using Zammad only in Germany (also all my users) It shows the Time Stamp (Germany/Europe) which confuses the users, as they are all based only in Germany.
I only use Zammad in one time zone, so for aestetic reasons I don't want to include time zone information like `(Europe/Berlin)`. Only `DD.MM.YYYY hh:mm` should be displayed in auto responders. 

b) I want to use different timestamp formats in different auto responders, because the recipients should receive different time zones and or different geological areas (with different timestamp formatting), "localized" information.

### Acceptance Criteria
- Allow/Possiblity for Date output without Time Zone
- ~Localize Time Stamp for known recipient~
- Inline Configuration Time Zone and Date Output (if information not enough for localization)

### Steps to reproduce the behaviour

* create a new auto responder
* try to ajust timestamps for your need (e. g. `DD.MM.YYYY hh:mm` without timezone)

### Technical Implementation

Idea could be to go in a direction like for the usage of `t(`?
```[tasklist]
### Tasks
- [x] Define a backwards compatible and extensible format/syntax to use
- [x] Implement for server-side variable replacement
- [x] Tests
```

**Comment by mgruner** [comment]
Maybe partially related to #4832
