### ISSUE TITLE
Still Problems migrating from freshdesk

### ISSUE THREAD

**Issue by itsupply25** [zammad/zammad#4937]
Unfortunately this fix did not solve the problem. The error still remains. I created two environmens:
1) With docker
2) Install from source

In both I get the error. What I recognised is, that with docker the migrations task is able to transfer more tickets until the error raises (app. 4000-7000). On the source install version I didn't managed it to come over 1000. 

Are there any other quick fix options. I also tried to modify the sleep intervals from 10 to 180 in requester.rb. But this also made no difference.

_Originally posted by @itsupply25 in https://github.com/zammad/zammad/issues/4350#issuecomment-1816328195_

**Comment by dominikklein** [comment]
Closed this issue, because we can check this first in the previous one.
