### ISSUE TITLE
use circles/quadrat/triangle for color-blind users

### ISSUE THREAD

**Issue by martini** [zammad/zammad#494]
use circles/quadrat/triangle for color-blind users (at least to let them configure)

**Comment by MrGeneration** [comment]
I believe that this would be covered by issue https://github.com/zammad/zammad/issues/3067 ?

At least in my opinion, if so, we could close this issue as an duplicate. :)

**Comment by dominikklein** [comment]
Close, because of the general existing accesibility issue: https://github.com/zammad/zammad/issues/3067
