### ISSUE TITLE
NDR to supporter leads to mailloop

### ISSUE THREAD

**Issue by bastolino** [zammad/zammad#4941]
### Used Zammad Version

6.1.0-1700492762.96ac5a60.jammy 

### Environment

- Installation method: package
- Operating system: Ubuntu 22.04.3 LTS
- Database + version: postgresql-14 (14.9-0ubuntu0.22.04.1)
- Elasticsearch version: 8.11.1
- Browser + version: and (irrelevant)

### Actual behaviour

When an agent receives notifications for a case and there is a problem with sending the mails to this single agent, a non-delivery-report is being received from the mailserver. This NDR contains the ticketnumber, updates the ticket, which then creates a new notification for the agent which is again not delivered and replied to via NDR, which updates the ticket and so on.

### Expected behaviour

Zammad should detect NDRs and refuse to send update mails to given mailaddress for (only) the next update. This prevents the stack from being filled without end.
Fix for me was to shut down zammad, remove the last NDR from the inbox and restart again. After the originating problem had been fixed, everything was smooth again.

### Steps to reproduce the behaviour

create a mail-account, fill it up with mails so no new mails get received (quota exceeded) and update some case which is assigned to this mailaccount. same should apply to spf records or other similiar delivery problems like being put on a blacklist.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
It sounds like you're using a notification email address that's also used as inbound email channel, is that correct?
If so, this technically makes no sense to do so, for whatever reason you do it, there's no support to reply to these emails anyway.

I cannot think of another way this kind of thing could happen.
