### ISSUE TITLE
Copied ticket title text/handle in dark-mode into article is rendered in white color

### ISSUE THREAD

**Issue by flashdagger** [zammad/zammad#4944]
### Used Zammad Version

6.1

### Environment

- Installation method: Any
- Operating system Any
- Database + version: Any
- Elasticsearch version: Any
- Browser + version: Chrome Version 119.0.6045.160 (Official Build) (64-bit) (Win)

### Actual behaviour

In dark-mode the pasted text which is copied from the ticket title is a HTML span element with white font color.
When using dark-mode the user will not be aware of it.
But colleagues who are not using dark-mode or clients who are getting the email will not be able to see the text
on white background. 

If #4445 is considered a bug, this should be in the same category.

### Expected behaviour

As it seems to been fixed for copied text from other articles [#4445], I would like to see the same solution for text copied from ticket title.

### Steps to reproduce the behaviour

1. switch to dark-mode
2. copy the title from the top of a ticket into the clipboard
3. paste the content into a new article (note, email, etc.)
4. continue typing after the pasted text

### Support Ticket

Ticket#10153430
Ticket#10153637

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by t-shehab** [comment]
Hi @flashdagger 


thanks for opening this issue. At the moment, I cannot verify the behaviour you're describing following the steps you outlined to reproduce it. See the video below.

Is there anything else I must do to trigger the behaviour. Did I miss something? 

[verify-falsify-issue4944.webm](https://github.com/zammad/zammad/assets/114283486/0f44ecf2-b6da-4f10-bd06-2da57dc23e8d)

![Screenshot_2023-11-28_10-45-22](https://github.com/zammad/zammad/assets/114283486/843c602a-8392-4636-b5d5-daf5b0dc7692)

**Comment by flashdagger** [comment]
Hello @t-shehab,

thank you for your reply. Yes, the video shows exactly how to reproduce the behavior.

I don't even need to update the article just disabling the dark-mode is enough.
To be specific I paste the text with CTRL+V which keeps the formatting. I'm using current versions of Chromium based browsers (Chrome, Microsoft Edge, Brave Browser) and they all are showing this behavior.

<img width="322" alt="image" src="https://github.com/zammad/zammad/assets/17416271/b02fa50b-0d75-4346-9d5f-521f121739c0">

Now I just tried Firefox and there the issue doesn't exist. So I suppose it has to do with the browser engine.

<img width="346" alt="image" src="https://github.com/zammad/zammad/assets/17416271/51a72355-321a-4881-9cd2-3d255f147ca5">

**Comment by t-shehab** [comment]
Thanks for your reply, @flashdagger 

I still can't reproduce it on either of the two browsers I tried (Firefox 119.0.1 and Chromium 119.0.6045.159).

However, I have just asked my colleague @Suhopoljac who is running Windows (I'm running Linux), and he could instantly reproduce it on MS-Edge, span tag and everything.

In summary, this seems to be a bug affecting Chrome-based browsers on Windows. Thanks for bringing it to our attention.

**Comment by xarem** [comment]
> In summary, this seems to be a bug affecting Chrome-based browsers on Windows. Thanks for bringing it to our attention.

I can confirm the issue can be reproduced on macOS too.

**Comment by cegredev** [comment]
+1 for fixing this, almost cost us the sponsoring for our upcoming event :')

(using Chrome on Windows)

**Comment by mantas** [comment]
I wonder what could be the best way to fix it. It's to highlight surrounding HTML as well and then result looks like this:

![Screenshot 2024-05-03 at 13 04 54](https://github.com/zammad/zammad/assets/36944/ec82a534-5d07-433e-ad3a-5f78904e336f)

Maybe we could add a „copy“ button? Just like there's one for Ticket#0000. This would make it much easier to copy the title without playing with the highlighting and make sure no HTML formatting gets in the way.

**Comment by IdaEdz** [comment]
I can verify this issue:
Zammad: version 6.3.1-1715932826.48881ba1.jammy
Web browser: Brave version 1.66.110 (Chromium 125.0.6422.60) 
OS: Windows 11 Pro

I copied 'white text' from another application, also in with dark mode and white text, into Zammad.

If I were careful and pasted with Ctrl+Shift+V the text is fine.
The clue here is that when using dark mode you are usually copying text including its formatting.

To reproduce, you can also do the following:

Start a article answer 
Write some text and send it.
Either now switch to dark mode, if you didn't already have it.
Copy the text from the previous article and paste it into the new article. (copy normally with either Ctrl+V or right click and choose paste)

The text in dark mode has formatting and when you paste formatted text into a article Zammad retains that formatting.

A solution to this problem, imo, would we to activate formatting tools in the article box.
Or when you paste text, ask if you would like to remove formatting (like how it is done in word processors - probably more complex)

Best regars
OskyEdz

**Comment by dvuckovic** [comment]
As already hinted, this issue is very similar to one from #4445. Although "white" color was already part of the ignore list, it wasn't mentioned by its RGB format (`rgb(255, 255, 255)`), which is used for ticket title content when the title is being edited. If you select and copy the title text while editing it, the issue is reproducible in Chrome only (not OS dependent, and not related to other browsers based on Webkit engine).

For now we decided to simply add this color to the ignore list and strip it from the pasted content like the others. Please let us know if you find some other UI color to interfere with the dark/light mode in Chrome.
