### ISSUE TITLE
Prevent user creation via Third Party Authentication

### ISSUE THREAD

**Issue by Mirtaaa** [zammad/zammad#4945]
**WHAT**
When users login via SAML (or any other third-party provider), they can Log-In even if they are not inside the existing Zammad users.
When users login via SAML (or any other third-party provider) and there is no Zammad user, one will be created and the login will be successful.

**USE CASE**
A Company with Sub-companies or external partners wants to limit access to their Zammad Instance to only existing Zammad Users and exclude users who don't have a Zammad Account. The Log-In provider (MS365) does not provide enough options, only all/ whole world (too wide) or only own tenants (too narrow)

**EXPECTATION**
When users login via SAML and no Zammad user is available a login is not possible. The error message should be understandable for non-technical users.

_Site note: While the customer is using SAML, this may be a use case also relevant to other third-party authentication methods._

**Acceptance Criteria:**
- not existing 3rd party users should not be able to log-in
- this should be configurable and turned off by default
- it should be a meaningful/straight forward error message

**Possible solutions?**
- Add a third option to "Automatic Account linking" or add an additional setting to the screen "Third Party Authentication".

Related Ticket:
Ticket#10143307

**Comment by tschaefer** [comment]
Duplication of https://github.com/zammad/zammad/issues/4940.

**Comment by Mirtaaa** [comment]
It is no duplication of #4940

**Comment by dominikklein** [comment]
I think this one here has the same topic, but includes also one more thing about the password reset: https://github.com/zammad/zammad/issues/2503

**Comment by dominikklein** [comment]
When the user does not exist inside Zammad during a third-party authentication and the user creation from third-party authentication is disabled we show the following error message:

<img width="757" alt="Screenshot_2024-08-22_at_10 34 24" src="https://github.com/user-attachments/assets/3810e03f-e23a-486f-b7da-7cc0fda4203a">

**Comment by MrGeneration** [comment]
In the past these very specific messages like an account not existing or password being incorrect had to be resolved via a CVE. Is this not too telling? Just double checking.

**Comment by tschaefer** [comment]
The critical authentication is handled by the IDP (third-party application). Only If this succeeds, Zammad is handling the authorization (permission), indicated by the HTTP code 403.

**Comment by rowe42** [comment]
We have tried the feature, but it does not work as expected. We get this error in Zammad (which does not match the error described above), when a user tries to login from the 3rd-party-IDP, which does not exist as user in Zammad yet.

![Image](https://github.com/user-attachments/assets/ddeb7a26-00e6-4422-bef9-12248ec6a5b5)

Furthermore, this ends in a deadlock. The user cannot navigate away and calling Zammad by URL again and trying to login as a different user ist not possible, because you directly end up in this error screen again without being able to login again as a different user before (since the IDP session still persists). The only way out is to close the Browser.

**Comment by fliebe92** [comment]
Hi @rowe42. Feel free to open a new issue describing your situation, but make sure that we can reproduce it without any issues.

Furthermore, you could also use the [Zammad community](https://community.zammad.org) to get help there.

**Comment by tschaefer** [comment]
The error shown `saml: invalid_ticket` is on the protocol level. This exception is raised way before the feature check `does user exist`. The SAML configuration should be checked and `debugged`.
