### ISSUE TITLE
Trigger Condition "contains not" doesn't work correct if "nil" is stored in the user object

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#4948]
### Used Zammad Version

6.1

### Environment

- Installation method: All

### Actual behaviour

I create the following user object:

![Bildschirmfoto 2023-11-27 um 13 38 26](https://github.com/zammad/zammad/assets/129729908/05cb5dcc-c6b3-4166-b3b7-806cb4284ffb)

I create the following trigger condition

TextObjekt -> contains not -> Test

![Bildschirmfoto 2023-11-27 um 13 25 40](https://github.com/zammad/zammad/assets/129729908/32f93aff-685f-4f99-9f36-dcce81522d03)

**Expectation**
Trigger should always be executed if "Test" is not stored in the object.

**Problem:**
Trigger is not executed if "nil" is stored in the user object, which is the default case for users who already exists before the user object is created. 

For new created users  "“ is stored in the object, the trigger works.

Existing User (entry in object field)
lhmExtID: nil

New User (entry in object field)
lhmExtID: ""

### Expected behaviour

Trigger should also execute when the object entry is „nil“ 

### Steps to reproduce the behaviour

See above

### Support Ticket

Ticket#10146737

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
@MarkusHeld is this a bug or an enhancement?

**Comment by MarkusHeld** [comment]
@fliebe92 i think a bug, have selected it
