### ISSUE TITLE
In the overviews, the selected groups in the conditions are difficult to recognize.

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#4950]
### Used Zammad Version

6.2.0-alpha-1701158207.edfc7e36.bookworm, 6.3

### Environment

- Installation method: package
- Operating system: debian 12.2
- Database + version:  postgresql

### Actual behaviour

If I select Group as a condition in the overviews, the selected groups do not disappear from the selection list or are not marked as selected.

<img width="1071" alt="Bildschirmfoto 2023-11-28 um 09 50 46" src="https://github.com/zammad/zammad/assets/129729908/5deada15-2ab0-45c9-b4db-0c3c27e8dc02">

**Problem is**
It is very difficult to keep track if i have a large number of groups and I have to spend a lot of time checking whether all necessary groups are selected.

### Expected behaviour

The already selected groups disappear from the selection list or are marked as selected.

### Steps to reproduce the behaviour

Create an overview
Select Group as a condition
Select different groups

### Support Ticket

Ticket#10147170

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by dominikklein** [comment]
@MarkusHeld I think this is the expected behavior, the only thing which we want to add with the re-write is, that we will "mark" the selected items.

![Bildschirmfoto 2023-11-28 um 10 47 53](https://github.com/zammad/zammad/assets/5445094/08ef5388-e8ad-4d93-8120-e73a9148d4dc)
