### ISSUE TITLE
Agents can see roles on other users accounts

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4952]
### Used Zammad Version

6.1.0.96ac5a607.saas, 6.2.x.4582cf17a.saas

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  PostgreSQL 13, but technically any I guess
- Elasticsearch version: 7.15; any
- Browser + version: verified on Vivaldi v6.4.3160.42 (Windows) and Firefox v120.0 (Windows)

### Actual behaviour

An agent without `admin.role` or `admin` permission can see the roles of other user accounts.
Upon applying of role changes, the change of roles is silently discarded.

Reloading does "fix" the user edit dialog and no longer shows the roles until the agent logs out and back in. Clearing cache, neither on Zammad nor Browser side does fix this issue.

![temporary-role-permissions](https://github.com/zammad/zammad/assets/6549061/4ab9318f-5018-4624-8a8f-6aedc29506ee)

### Expected behaviour

Zammad agents without `admin.role` or `admin` permission can never see the roles of an user.

### Steps to reproduce the behaviour

- create a user with agent permission only, ensure the user does not have role permissions
- log out the admin user
- Clear all the caches you want
- login as agent, look up *any* user account you want and edit the user. You'll see the role selection on the bottom
- reload (the role selection is gone)
- logout, login (it's back)

### Support Ticket

Ticket#10146097

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
regression of https://github.com/zammad/zammad/commit/1aa70ea4b7184650f3321ed8e20ff17b787c633c
