### ISSUE TITLE
The in drop-down menu shown group name is truncated after a certain number of characters

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4953]
### Used Zammad Version

6.2. develop

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge, v.119.0.2151.93 (64-Bit)

### Actual behaviour

A long group name like: `Business - Daily - Bugle - News` is truncated after a certain number of characters and shows approximately `Business - Daily - B...`.

### Expected behaviour

Reasonable number of characters displayed (certain limit should be kept but increased from the current one to a higher number). 
This would not include group names such as **Donaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaft**, so that reasonable (regarding length) group names should be displayed in the ticket. 

### Steps to reproduce the behaviour

1. a) create a group with a long name, if possible with several words 
 like in the screenshot shown
<img width="184" alt="Screenshot 2023-11-29 132312" src="https://github.com/zammad/zammad/assets/101350124/0a3f0fff-19db-405c-b567-5190ca44dcd4">

2. Somewhere around the 20th character (blank spaces also count!), the group name is split into two parts, with the first part extending up to about the 20th character and the remaining characters being displayed with .....
3. if you move the mouse pointer over the group name from the drop-down menu, the full group name is still displayed. When selecting the group, you must either type in the group search field (therefore you must know all the groups by name) or click yourself through to the correct group, both of which are time-consuming. 

### Support Ticket

Ticket#10147173

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by SamolJacek** [comment]
There was refinement and we will check the following possibilities to solve the problem:

- we will maximize the number of visible characters by making the check mark icon smaller and reducing the padding size.
- we will try to use a media query to check screen resolution to adjust the size of the sidebar to increase the size of the group dropdown field.
