### ISSUE TITLE
Template 'Apply' creates ticket

### ISSUE THREAD

**Issue by jedikaal** [zammad/zammad#4956]
### Used Zammad Version

5.3.1-1673546521.f2c640c5.bionic

### Environment

- Installation method: package (zammad 5.3.1-1673546521.f2c640c5.bionic amd64)
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 18.04.6 LTS
- Database + version: 10.23-0ubuntu0.18.04.2
- Elasticsearch version: version 7.11.1
- Browser + version: Firefox 120.0 (64-bit), Firefox ESR 115.5.0esr (64-bit)

### Actual behaviour

While making a new ticket, there is a option to choose for a template. 
Once the template is chosen, pressed 'Apply'
The ticket is still in create mode and the field are filled. 
But when pressing the 'Apply' button a second time, the tickets is created.

This is happens when the click is done twice shortly after eachother. accidentally pressing enter when selected or finger slipping on the left mouse button. 

### Expected behaviour

I would expect that the second time pressing the 'Apply', would do nothing. Because the selection is back to nothing chosen or that the ticket would be made empty. 

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
> 5.3.1-1673546521.f2c640c5.bionic

You're terribly outdated.
The current stable version is 6.1.

We're not supporting older versions and thus cannot take your issue report into account.

Upgrade asap.

**Comment by jedikaal** [comment]
Once we updated I'll test it again. Thanks for your time.
