### ISSUE TITLE
Wording of knowledge base permissions confusing

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad#4957]
### Used Zammad Version

Any

### Environment

Any

### Actual behaviour

There are 2 permissions which can be granted to users/roles:

- `knowledge_base.editor` ("Manage Knowledge Base Editor")
- `knowledge_base.reader` ("Manage Knowledge Base Reader")

![image](https://github.com/zammad/zammad/assets/60067527/0bfffd80-66cf-4186-a11a-294e5724d3df)

The wording for the explanation is wrong in my eyes. It states that users/roles with these permissions can manage **users** (editors and readers) of the KB. After clarification it turned out that the permission is about granting users/roles the permission to **read/edit the KB itself**. 

The top level description (Manage Knowledge Base) could also be changed.

### Expected behaviour

The wording should be adjusted. Some suggestions, if no one has better ideas:

- (Read|Edit) Knowledge Base
- (Read|Edit) Knowledge Base entries
- (Read and write|Read) Knowledge Base
- (Read and write|Read) Knowledge Base entries

The root description could be changed to just "Knowledge Base". Because if someone has just the reading permission, this is no management ;-)

### Steps to reproduce the behaviour

Have a look in the permission tree (in roles or users)

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by mgruner** [comment]
Fixed by 3f1023f7.
