### ISSUE TITLE
Can't process email InFailedSqlTransaction

### ISSUE THREAD

**Issue by mvngne** [zammad/zammad#4958]
### Used Zammad Version

6.1

### Environment

- Installation method: package
- Operating system: Ubuntu 22.04.3 LTS
- Database + version:  14+238 (from zammad package)
- Elasticsearch version: 8.11.1
- Browser + version: -

### Actual behaviour

At some point, mails won't get processed anymore. It seems like one mail is breaking the system. The mails get fetched (via imap) but not processed anymore. Restarting zammad service doesn't help, only forcing mail processing helps: `Channel::EmailParser.process_unprocessable_mails`

Full error from production.log:
```
E, [2023-11-30T15:33:15.499425#1507127-87663700] ERROR -- : Can't process email, you will find it for bug reporting under /opt/zammad/var/spool/unprocessable_mail/3e21d7a2fededf8bb09b54df9eeed5a2.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2023-11-30T15:33:15.499466#1507127-87663700] ERROR -- : PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
 (ActiveRecord::StatementInvalid)
lib/transaction_dispatcher.rb:33:in `perform'
lib/transaction_dispatcher.rb:17:in `commit'
app/models/transaction.rb:51:in `finish_transaction'
app/models/transaction.rb:19:in `ensure in block in execute'
app/models/transaction.rb:19:in `block in execute'
app/models/transaction.rb:14:in `execute'
app/models/transaction.rb:26:in `execute'
app/models/channel/email_parser.rb:187:in `_process'
app/models/channel/email_parser.rb:126:in `block in process'
app/models/channel/email_parser.rb:125:in `process'
app/models/channel/driver/imap.rb:320:in `block in fetch'
app/models/channel/driver/imap.rb:255:in `each'
app/models/channel/driver/imap.rb:255:in `fetch'
app/models/channel.rb:56:in `fetch'
app/models/channel.rb:30:in `fetch'
(eval):1:in `eval_job_method'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:48:in `eval_job_method'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:23:in `execute'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:16:in `block in run_loop'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:15:in `times'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:15:in `run_loop'
lib/background_services/service/process_scheduled_jobs/job_executor/continuous.rb:8:in `run'
lib/background_services/service/process_scheduled_jobs/job_executor.rb:10:in `run'
lib/background_services/service/process_scheduled_jobs/manager.rb:84:in `block in start_in_thread'
lib/application_handle_info.rb:19:in `use'
lib/background_services/service/process_scheduled_jobs/manager.rb:82:in `start_in_thread'
lib/background_services/service/process_scheduled_jobs/manager.rb:73:in `block (2 levels) in start'
lib/background_services/service/process_scheduled_jobs/manager.rb:72:in `block in start'
```

### Expected behaviour

Mails should always get fetchend and if there is an error, they should get fetched afterwards. And even if one mail has a problem, others still should get fetched.

### Steps to reproduce the behaviour

Not possible as far as I can tell. The error happens randomly. The mail is basicly empty (it was just for test purposes).

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@mvngne Please provide an example mail.

**Comment by mvngne** [comment]
[Mails.zip](https://github.com/zammad/zammad/files/13578143/Mails.zip)

This is the first mail that got stuck and the following which didn't got processed afterwards. But I don't think, there is an Issue with these mails. They are basicly empty. Also, I've just put them in the mailbox to test if they would get stuck again and they didn't. They got fetched and processed like they should have before.

**Comment by MrGeneration** [comment]
The transaction error usually is a psql process that has a no longer valid configuration / session for whatever reason. Usually occurs when updating the database server - sometimes connections are not correctly shutdown. This can make Zammad keep on to old connections.

This makes this theoretically a technical question at least.
Restart postgresql and Zammad and you're good.

**Comment by mvngne** [comment]
Thanks for the explanation. In the docs I found the rails command `Channel::EmailParser.process_unprocessable_mails` which helps in my case. 

Never the less it is pretty frustrating that I have to interact with the console from time to time for this issue. Even if there is a problem with the database connection, I think it would be great if the system tries to process the mails at least a second time by itself after like a minute or two.

**Comment by dominikklein** [comment]
@mvngne Like @MrGeneration already mentioned, currently, it's more of a technical question. For sure we will keep in eye on the mail handling and also the possibilities for improvements in the future.
