### ISSUE TITLE
Tables (spreadsheets) in articles are cut off in Zammad UI

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4960]
### Used Zammad Version

6.2. develop

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: MS Edge v.119.0.2151.93 (64-bit)

### Actual behaviour

If you copy a table (either a part of it or the entire table) into Zammad, only some columns are displayed and the rest of the content is not visible in the user interface. 

### Expected behaviour

When copying a table (either a part of it or the whole table) into Zammad with each article having a fixed width, I would like to see a sidebar that would allow me to move sideways in the article and also in the table content.  

### Steps to reproduce the behaviour

1) Open a table file (spreadsheet)
2) Copy part of the content of the file (in my case the file generated by the report function in Zammad, from columns A (#) to column H (organization) into your e-mail client. 
<img width="950" alt="Screenshot 2023-12-01 143800" src="https://github.com/zammad/zammad/assets/101350124/e5abc7c4-e30f-4712-b8c3-07869b1502af">
3) Thunderbird, for example, displays the entire content of the copied part by scrolling sideways while Zammad displays the content only up to column F (owner). 

https://github.com/zammad/zammad/assets/101350124/08651bcf-37ae-4bc0-ab0e-6fe53be38811

### Support Ticket

Ticket#10147331, #10146964, #10149652, #10151761

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Cybernisk** [comment]
Same behaviour with
Zammad: 6.2.0-1
Browser + version: Firefox 121.0.1 (64-bit)

**Comment by vasan-agrostar** [comment]
As a workaround, you could use a custom CSS and set `overflow: scroll` for the element `richtext-content`. That will make a horizontal scroll appear if the table overflows the width.
