### ISSUE TITLE
Reporting chart missing october numbers

### ISSUE THREAD

**Issue by turtle0x1** [zammad/zammad#4962]
### Used Zammad Version

6.1.0-1701163867.5a81e629.jammy 

### Environment

- Installation method: apt
- Operating system (if you're unsure: `cat /etc/os-release` ): ubuntu 22.04.3
- Database + version: postgresql 14.9
- Elasticsearch version: 7.17.15
- Browser + version:  Chome & Firefox

### Actual behaviour

Created / closed tickets are missing for the month of October on the report view

![missing_oct](https://github.com/zammad/zammad/assets/12494629/513ad21c-db82-4ea7-a4a7-643f4c2aab51)

### Expected behaviour

Octobers values are there (If I download the data I can see that tickets were created / closed)

### Steps to reproduce the behaviour

Not sure how sorry.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Smells like a faulty searchindex.
This is reporting not overviews btw.

**Comment by turtle0x1** [comment]
> Smells like a faulty searchindex.

I've run `zammad run rake zammad:searchindex:rebuild` and its complete, the chart is the same


> This is reporting not overviews btw.

Apologies

**Comment by rolfschmidt** [comment]
Hi @turtle0x1,
the screenshot is missing some infos. Do you have a profile selected? If yes, how is the profile configured in the admin interface?

**Comment by turtle0x1** [comment]
Hi @rolfschmidt please see screenshot

![image](https://github.com/zammad/zammad/assets/12494629/27d0230d-5c52-484b-9527-cdd559259f1c)

I think this is setup as default, but let me know if I've missed something

![image](https://github.com/zammad/zammad/assets/12494629/07e26767-de30-4df2-8a80-e9d2db6ff00d)



Interestingly if I click on the "communication" "view" on the report it **does** include October, but neither "Ticket Count" or "Creation Channel" do

**Comment by Mirtaaa** [comment]
Hello, we could not reproduce this issue, in our instances it works fine, therefore it seems to be a problem on your side/configuration.
If you have a support contract, please contact our support for help.
If you do not have a support contract yet, you can find more information about our support offers here: [https://zammad.com/en/pricing](https://zammad.com/en/pricing)

If a support contract is not an option for you, our free (english) community is also available as an alternative: [https://community.zammad.org](https://community.zammad.org).

**Comment by richgilham** [comment]
I have encountered this issue on our installation. 2 years running we see zero tickets in October

<img width="1601" height="521" alt="Image" src="https://github.com/user-attachments/assets/90f42479-523c-4105-a00f-0e6cafa60654" />

<img width="1616" height="527" alt="Image" src="https://github.com/user-attachments/assets/a3a1d30d-c4cd-459e-89bb-f893a0400fa7" />

We are running version 6.5.0
