### ISSUE TITLE
Wrong follow-up detection with forwarded emails without "Fwd" 

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#4965]
### Used Zammad Version

6.1

### Environment

- Installation method: any
- Operating system : any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

**How it was discovered:**

1) Send mail from "Group A" in Zammad to an external e-mail account. 
2) Click on "Forward" in mail client. 
3) Remove the ticket number from the subject line (still email client). 
4) Enter "Group B"s email address in the "To" field. 

Results in: 

**a) With _Fwd_ in subject field**
New Ticket is created (as desired).

**b) With _WG_ (German default in Outlook) or nothing in subject field**
Email is added as an article in existing (original) ticket.

**Remark:** 
All three options for additional follow-up-detection are disabled.  

### Expected behaviour

Without putting the original ticket number in the subject and not using additional follow-up-detection, a new ticket should always be created. 

### Steps to reproduce the behaviour

0) Deactivate all options for additional follow-up-detection if activated. 
1) Create a email ticket in Zammad and open your ticket in an email client.   
2) In the email client, click on "Forward" and remove the ticket number.  
4) Remove the "Fwd" leaving "Ticket Subject Forward" empty, or add "WG" instead. 
5) Send the email back to your Zammad instance. 
6) The email is added to the original ticket. 
7) You have reproduced the behavior. 

### Support Ticket

Ticket#10142189

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by cautopartes** [comment]
Just an additional thought on this: 

Shouldn't the To field in an email always be given priority over reference headers? 

In the present case, a forwarded email is delivered to the wrong email address (that of another group) due to the failed detection of the forwarding.

**Comment by martini** [comment]
@cautopartes Issue got fixed via https://github.com/zammad/zammad/issues/5287 (the issue was, only `..` but no `...` were considered)
