### ISSUE TITLE
CC'ed users do not see the ticket in their panel.

### ISSUE THREAD

**Issue by aqueos** [zammad/zammad#4966]
### Used Zammad Version

6.1.0-1701163867.5a81e629.bullseye

### Environment

- Installation method: [package]
- Operating system (): [ debian 11]
- Database + version: . postgresql 13
- Elasticsearch version:8.11

### Actual behaviour

if you CC a ticket to another user in a reply email the answer do not appear in the CC user's ticket list 

when i reply to a ticket by email and i put another user in CC, the answer do not appear on this user's ticket list.

 If one user decide to share a part of a ticket it would be good that it appears in this other user's ticket list. At least all the parts it is in CC or has done himself (not the rest of the ticket).

best regards,
Ghislain.

### Expected behaviour

as he is in CC the user should see the part of the ticket he is in CC in his panel

### Steps to reproduce the behaviour

create a ticket
answer to the ticket by email and put in CC another user of this zammad instance.
log in the CC user zammad account
see the part of ticket he is in CC is not here.

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
