### ISSUE TITLE
Migration to 6.2.0 fails on debian due to missing indexes on modulus and subject in table smime_certificates

### ISSUE THREAD

**Issue by datendunst** [zammad/zammad#4972]
### Used Zammad Version

6.2.0

### Environment

- Installation method: Debian Package
- Operating system: debian 11.8
- Database + version: postgresql 13
- Elasticsearch version: elasticsearch-oss 7.10.2

### Actual behaviour

Upgrade from 6.1.0 to 6.2.0 fails:

# Enforcing Redis...
# Creating Redis bootstart
Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
# Starting Redis server
# Redis server is running.
# (Re)creating init scripts
Nothing to do.
Nothing to do.
Nothing to do.
# Enabling Zammad on boot
# Stopping Zammad
# Clear cache...
# database.yml found. Updating db...
== 20220920084800 SettingAddStoreProviderS3: migrating ========================
== 20220920084800 SettingAddStoreProviderS3: migrated (0.0276s) ===============

== 20230726082734 SMIMEMetaInformationTable: migrating ========================
-- change_table(:smime_certificates)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

No indexes found on smime_certificates with the options provided.
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:1463:in `index_name_for_remove'
...

ActiveRecord::Migration.check_pending! shows:

 20230726082734_smime_meta_information_table.rb
 20230728073916_smime_meta_information_data.rb
 20230728090212_pgp_key_email_addresses.rb
 20230801092655_issue_4543_organization_vip.rb
 20230802112821_regex_operator_renaming.rb
 20230807051414_input_fields_operator_renaming.rb
 20230807171019_postmaster_filter_regex_operator.rb
 20230817130057_update_api_password_access_frontend.rb
 20230823082823_update_format_settings.rb
 20230825101042_show_package_url.rb
 20230825150332_issue_4657_time_accounting_selector.rb
 20230829085650_ldap_source_config.rb
 20230830100819_create_ssl_certificates.rb
 20230904123822_set_idoit_ssl_default.rb
 20230905073448_set_gitlab_ssl_default.rb
 20230905074116_set_elastic_search_ssl.rb
 20230906162437_set_mail_ssl_default.rb
 20230912080534_group_hierarchy.rb
 20231011055535_saml_sign_encrypt.rb
 20231016120344_search_index_settings.rb
 20231017091313_loop_protection_settings.rb
 20231024103209_issue_4838_data_retention.rb
 20231107090334_simple_storage_configuration_check.rb

Erm. If those are dates earlier migrations might have failed without us noticing it. I don't remember any errors on earlier upgrades, though.

zammad run rails db:migrate RAILS_ENV=production fails:

== 20230726082734 SMIMEMetaInformationTable: migrating ========================
-- change_table(:smime_certificates)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

No indexes found on smime_certificates with the options provided.
/opt/zammad/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/schema_statements.rb:1463:in `index_name_for_remove'
...

zammad run rails zammad:searchindex:rebuild RAILS_ENV=production fails:

Dropping indexes... done.
Deleting pipeline... done.
Creating indexes... rails aborted!
NoMethodError: undefined method `[]' for nil:NilClass

    settings = Setting.get('es_model_settings')[model.name] || {}
                                               ^^^^^^^^^^^^
/opt/zammad/lib/search_index_backend.rb:854:in `model_settings'
...

We are now stuck with a bunch of failed migrations and no search index. Is there any way to go through the pending migrations and get that certificate table index built?

### Expected behaviour

All migrations should be executed properly for every version between the former and the current one.
Indices should all be there. 
Search index should be rebuildable.

### Steps to reproduce the behaviour

aptitude update; aptitude upgrade ;)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by datendunst** [comment]
Turns out someone else had the same problem a while ago:

https://community.zammad.org/t/update-6-0-0-6-1-0-issues-errors-immediate-fix-required-or-can-it-nevertheless-be-used/12257/9

In db/migrate/20230726082734_smime_meta_information_table.rb two indexes on columns "modulus" and "subject" are to be removed, but they didn't exist. (There should be an "IF EXISTS" condition or something I believe...)

Instead of changing the code I created the Indexes in Postgres:

```
CREATE INDEX idx_dd123 ON smime_certificates(modulus);
CREATE INDEX idx_dd124 ON smime_certificates(subject);
```

After that I could run `zammad run rails db:migrate RAILS_ENV=production` and `zammad run rails zammad:searchindex:rebuild RAILS_ENV=production`

**Comment by datendunst** [comment]
This might need a tiny fix though.

**Comment by dominikklein** [comment]
Could be that some migration in the past was not executed correctly?

**Comment by fliebe92** [comment]
Improved the migration with https://github.com/zammad/zammad/commit/708146e95f79715b843f7fe60aeb0ad4c719613c and https://github.com/zammad/zammad/commit/0cb24140266e4c69bce7756cc3989bec70cc7831.
