### ISSUE TITLE
IMAP/SMTP failure

### ISSUE THREAD

**Issue by support-criegerde** [zammad/zammad#4978]
### Used Zammad Version

6.2.0-1702303938.81e0c1fd

### Environment

- Installation method: Update (apt upgrade)
- Operating system: 22.04.3 LTS (Jammy Jellyfish)
- Database + version: postgresql 14.10 (psql (PostgreSQL) 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1))
- Elasticsearch version: 7.17.15

### Actual behaviour

Running update using apt update && apt upgrade.
Cannot use or configure SMTP nor IMAP anymore.

PG::UndefinedTable: ERROR: relation "ssl_certificates" does not exist LINE 9: WHERE a.attrelid = '"ssl_certificates"'::regclass ^ 
[...]
Can't use Channel::Driver::Smtp: #<ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR: relation "ssl_certificates" does not exist LINE 9: WHERE a.attrelid = '"ssl_certificates"'::regclass ^ >

IMAP:
![grafik](https://github.com/zammad/zammad/assets/134060911/77ed4375-3eb0-48c0-bb92-d46ff39c57f5)

SMTP:
![grafik](https://github.com/zammad/zammad/assets/134060911/ee7a583b-4bcf-4633-a961-83db7e4683e7)

### Expected behaviour

Receiving mails and send mails as before the update.

### Steps to reproduce the behaviour

![grafik](https://github.com/zammad/zammad/assets/134060911/49e003f6-acc0-4444-98f8-a3cd187ad70e)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by support-criegerde** [comment]
Solution:
```
apt remove zammad
apt install zammad
```

During the re-installation few db migration steps are executed and zammad works as expected after re-installation.

**Comment by fliebe92** [comment]
Hi @support-criegerde. Thanks for your report.

The issue you've posted indicates that the update/upgrade of Zammad was not successful. This is not related to the codebase itself, this is why I'm going to close your report.

Please use the [Zammad community](https://community.zammad.org/) for such issues in the future.

Thanks a lot! 🚀
