### ISSUE TITLE
Agents cannot use existing tags when Setting.get('tag_new') == false

### ISSUE THREAD

**Issue by t-shehab** [zammad/zammad#4979]
### Used Zammad Version

6.2.0-1702303938.81e0c1fd.bullseye

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Using an existing tag with agent permissions on a ticket while ```Setting.get('tag_new') == false``` throws the following exception:

```
I, [2023-12-12T12:30:12.953290#416-148600]  INFO -- : Started POST "/api/v1/tags/add" for 192.168.178.222 at 2023-12-12 12:30:12 +0100
I, [2023-12-12T12:30:12.972591#416-148600]  INFO -- : Processing by TagsController#add as JSON
I, [2023-12-12T12:30:12.972987#416-148600]  INFO -- :   Parameters: {"object"=>"Ticket", "o_id"=>3, "item"=>"test_tag01"}
I, [2023-12-12T12:30:13.032780#416-148600]  INFO -- : Exceptions::Forbidden (Exceptions::Forbidden)
app/controllers/tags_controller.rb:36:in `add'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
```

This seems to be the culprit:

https://github.com/zammad/zammad/blob/934aa909de2e5fbaa6cc2e507f0ce12eaf9919b8/app/controllers/tags_controller.rb#L36

https://github.com/zammad/zammad/blob/934aa909de2e5fbaa6cc2e507f0ce12eaf9919b8/app/models/tag.rb#L247-L253

### Expected behaviour

```Setting.set('tag_new', false)``` has no influence on whether an agent is allowed to use an existing tag.

Also, as an admin, I'd expect the log message to be ```ERROR```, not ```INFO```.

### Steps to reproduce the behaviour

```ruby
Setting.set('tag_new', false)
```

Then use an existing tag with agent permissions.

### Support Ticket

Ticket#10147824

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MarkusHeld** [comment]
I only have this problem with newly created tags, older already existing tags i can add as agent
