### ISSUE TITLE
LDAP Bind address lost (reset to 127.0.0.1) after upgrade from 6.1 to 6.2

### ISSUE THREAD

**Issue by mpantel** [zammad/zammad#4982]
# Infos

* Docker version: 20.10.13, build a224086
* Docker-compose version: 1.27.4, build 40524192
* Operating system (Docker host): Ubuntu 22.04.3 LTS

# Expected behavior

A after upgrading Zammd 6.1 to 6.2 using docker-compose (docker-compose stop && git pull && docker-compose pull && docker-compose up) the settings in LDAP integration module should persist.

# Actual behavior

* Upgrade progresses as expected but
* LDAP failed to bind to 127.0.0.1:389 and some users could not logging
* After reinspecting the LDAP module setup and resetting the ldap server to the correct address, the system was operational again, and all other settings were intact (even ldap user and password).

# Steps to reproduce the behavior

* Install Zammad version 6.1 through docker
* setup the LDAP integration module to some existing LDAP server other than 127.0.0.1
* Follow the process to upgrade to version 6.2 as in the documentation.

**Comment by mgruner** [comment]
@fliebe92 this does not sound like a docker related issue. We did have a migration dealing with LDAP source configuration in 6.2, could this be related somehow?

**Comment by mpantel** [comment]
Hi, @mgruner 
I cannot verify whether this is a docker issue. The fact is that I upgraded the installation following the docker workflow. I didn't mess with any configuration file by hand, except some changes at the end of .env:
```
RAILS_TRUSTED_PROXIES=['127.0.0.1', '::1','0.0.0.0']
NGINX_SERVER_SCHEME=https
```
Thanks!

**Comment by mgruner** [comment]
@mpantel yes, thanks. I tend to think so because this is handled in the DB on application level. Perhaps we should move this issue to https://github.com/zammad/zammad, but let's see what @fliebe92 and @dominikklein think about it.

**Comment by fliebe92** [comment]
@mgruner Based on the given information in this report, I cannot say if the migration is faulty or not.

`preferences.delete('host_url')` could point to an issue, but without knowing the details about the LDAP source... no chance. We need to know the state before the migration.

**Comment by mgruner** [comment]
@fliebe92 thanks for the hint. Then it seems likely that it is an application issue, and I transferred it to zammad/zammad, even though we don't know the exact cause yet.

**Comment by mpantel** [comment]
> @mgruner Based on the given information in this report, I cannot say if the migration is faulty or not.
> 
> `preferences.delete('host_url')` could point to an issue, but without knowing the details about the LDAP source... no chance. We need to know the state before the migration.

Probably yes! This migration was executed during the upgrade from 6.1 to 62. Every other relevant setting about ldap was intact (fields, group mapping etc.)

**Comment by blackbasket** [comment]
Hi guys, same issue here... update from 6.1.0-1699516547.242baab2.bullseye to the current build on Debian... after update no longer able to login with ldap...

on the integration site this error is shown
`Es ist ein Fehler aufgetreten: Can't connect to '' on port '389', Connection refused - connect(2) for 127.0.0.1:389`

if I want to configure the binding, there is no longer a value for ldap existing... furhter more LDAPS is no longer working at all with this error
`PG::UndefinedTable: ERROR: relation "ssl_certificates" does not exist LINE 9: WHERE a.attrelid = '"ssl_certificates"'::regclass ^`

**Comment by gwingend** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail.
Ich bin nicht im Büro.
Ihre Mail wurde weder gelesen noch weitergeleitet.

Bitte wenden Sie sich in dringenden Fällen an den EDV-Helpdesk ***@***.***).


Mit freundlichen Grüßen
Gerhard Wingender
Amt für IT

>>> blackbasket ***@***.***> 15.12.23 10:36 >>>

Hi guys, same issue here... update from 6.1.0-1699516547.242baab2.bullseye to the current build on Debian... after update no longer able to login with ldap...

on the integration site this error is shown
`Es ist ein Fehler aufgetreten: Can't connect to '' on port '389', Connection refused - connect(2) for 127.0.0.1:389`

if I want to configure the binding, there is no longer a value for ldap existing... furhter more LDAPS is no longer working at all with this error
`PG::UndefinedTable: ERROR: relation "ssl_certificates" does not exist LINE 9: WHERE a.attrelid = '"ssl_certificates"'::regclass ^` 

-- 
Reply to this email directly or view it on GitHub:
https://github.com/zammad/zammad/issues/4982#issuecomment-1857564109
You are receiving this because you are subscribed to this thread.

Message ID: ***@***.***>
-- 
Diese E-Mail wurde von Sophos UTM auf Viren überprüft.

Besuchen Sie uns im Internet unter: www.neuwied.de
oder bei Facebook @neuwied.de
und Instagram @deichstadt_neuwied

Eine E-Mail unterliegt dem Kommunikationsgeheimnis und ist nur für den Empfänger bestimmt. Der Inhalt ist grundsätzlich als vertraulich zu betrachten und nicht für Dritte zugänglich. Eine Weiterleitung bedarf daher der Zustimmung des Verfassers. Diese E-Mail darf zu dienstlichen Zwecken innerhalb der Stadtverwaltung weitergeleitet werden.

Sparen Sie pro Seite ca. 200 ml Wasser, 2 g CO2 und 2 g Holz: Drucken Sie daher bitte nur, wenn es wirklich notwendig ist!

**Comment by fliebe92** [comment]
Hi @mpantel, hi @blackbasket. Could you please share a redacted version of your LDAP configuration out of Zammad 6.1 with us? We're not able to reproduce it currently.

**Comment by blackbasket** [comment]
@fliebe92 sure... just tell me what to do... I am on 6.1 anyway beacuse I rolled back...

**Comment by fliebe92** [comment]
> @fliebe92 sure... just tell me what to do... I am on 6.1 anyway beacuse I rolled back...

Please enter the Rails Console and post the output of `LdapSource.all` - but please, make sure to redact some secret values :)

**Comment by blackbasket** [comment]
I hope, I have replaced all relevant values ;)

```[#<LdapSource:0x00007fc2c187cc48
  id: 1,
  name: "domain.local",
  preferences:
   {"host_url"=>"ldaps://dc02.domain.local",
    "ssl_verify"=>true,
    "options"=>
     {"DC=domain,DC=local"=>"DC=domain,DC=local",
      "CN=Configuration,DC=domain,DC=local"=>"CN=Configuration,DC=domain,DC=local",
      "CN=Schema,CN=Configuration,DC=domain,DC=local"=>"CN=Schema,CN=Configuration,DC=domain,DC=local",
      "DC=DomainDnsZones,DC=domain,DC=local"=>"DC=DomainDnsZones,DC=domain,DC=local",
      "DC=ForestDnsZones,DC=domain,DC=local"=>"DC=ForestDnsZones,DC=domain,DC=local"},
    "option"=>"DC=domain,DC=local",
    "base_dn"=>"DC=domain,DC=local",
    "bind_user"=>"ldap",
    "bind_pw"=>"xxxxxxx",
    "user_uid"=>"objectguid",
    "user_filter"=>
     "(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$))(!(samaccountname=*template))(memberOf=CN=GL_Benutzer,OU=Security Groups,OU=domain,DC=domain,DC=local))",
    "group_uid"=>"dn",
    "group_filter"=>"(objectClass=group)",
    "user_attributes"=>
     {"givenname"=>"firstname",
      "sn"=>"lastname",
      "mail"=>"email",
      "samaccountname"=>"login",
      "telephonenumber"=>"phone",
      "facsimiletelephonenumber"=>"fax",
      "mobile"=>"mobile",
      "department"=>"department",
      "title"=>"note"},
    "group_role_map"=>{"cn=gl_benutzer,ou=security groups,ou=domain,dc=domain,dc=local"=>["3"]},
    "unassigned_users"=>"sigup_roles"},
  prio: 1,
  active: true,
  updated_by_id: 1,
  created_by_id: 2,
  created_at: Mon, 24 Oct 2022 11:25:11.942000000 UTC +00:00,
  updated_at: Fri, 04 Aug 2023 12:13:35.256000000 UTC +00:00>,
 #<LdapSource:0x00007fc2c187ca68
  id: 5,
  name: "domain.local_Agents-Support",
  preferences:
   {"host_url"=>"ldaps://dc02.domain.local",
    "ssl_verify"=>true,
    "options"=>
     {"DC=domain,DC=local"=>"DC=domain,DC=local",
      "CN=Configuration,DC=domain,DC=local"=>"CN=Configuration,DC=domain,DC=local",
      "CN=Schema,CN=Configuration,DC=domain,DC=local"=>"CN=Schema,CN=Configuration,DC=domain,DC=local",
      "DC=DomainDnsZones,DC=domain,DC=local"=>"DC=DomainDnsZones,DC=domain,DC=local",
      "DC=ForestDnsZones,DC=domain,DC=local"=>"DC=ForestDnsZones,DC=domain,DC=local"},
    "option"=>"DC=domain,DC=local",
    "base_dn"=>"DC=domain,DC=local",
    "bind_user"=>"ldap",
    "bind_pw"=>"xxxxxxx",
    "user_uid"=>"objectguid",
    "user_filter"=>
     "(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$))(memberOf=CN=LD_Zammad-Agents_Support,OU=Security Groups,OU=domain,DC=domain,DC=local))",
    "group_uid"=>"dn",
    "group_filter"=>"(objectClass=group)",
    "user_attributes"=>
     {"givenname"=>"firstname",
      "sn"=>"lastname",
      "mail"=>"email",
      "samaccountname"=>"login",
      "telephonenumber"=>"phone",
      "department"=>"department",
      "facsimiletelephonenumber"=>"fax",
      "mobile"=>"mobile",
      "title"=>"note"},
    "group_role_map"=>{"cn=ld_zammad-agents_support,ou=security groups,ou=domain,dc=domain,dc=local"=>["5", "3"]},
    "unassigned_users"=>"sigup_roles"},
  prio: 2,
  active: true,
  updated_by_id: 1,
  created_by_id: 2,
  created_at: Fri, 07 Jul 2023 09:35:13.236000000 UTC +00:00,
  updated_at: Fri, 04 Aug 2023 12:13:35.296000000 UTC +00:00>,
 #<LdapSource:0x00007fc2c187c9a0
  id: 3,
  name: "domain.local_Agents",
  preferences:
   {"host_url"=>"ldaps://dc02.domain.local",
    "ssl_verify"=>true,
    "options"=>
     {"DC=domain,DC=local"=>"DC=domain,DC=local",
      "CN=Configuration,DC=domain,DC=local"=>"CN=Configuration,DC=domain,DC=local",
      "CN=Schema,CN=Configuration,DC=domain,DC=local"=>"CN=Schema,CN=Configuration,DC=domain,DC=local",
      "DC=DomainDnsZones,DC=domain,DC=local"=>"DC=DomainDnsZones,DC=domain,DC=local",
      "DC=ForestDnsZones,DC=domain,DC=local"=>"DC=ForestDnsZones,DC=domain,DC=local"},
    "option"=>"DC=domain,DC=local",
    "base_dn"=>"DC=domain,DC=local",
    "bind_user"=>"ldap",
    "bind_pw"=>"xxxxxxx",
    "user_uid"=>"objectguid",
    "user_filter"=>
     "(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$))(memberOf=CN=LD_Zammad-Agents,OU=Security Groups,OU=domain,DC=domain,DC=local))",
    "group_uid"=>"dn",
    "group_filter"=>"(objectClass=group)",
    "user_attributes"=>
     {"givenname"=>"firstname",
      "sn"=>"lastname",
      "mail"=>"email",
      "samaccountname"=>"login",
      "telephonenumber"=>"phone",
      "department"=>"department",
      "facsimiletelephonenumber"=>"fax",
      "mobile"=>"mobile",
      "title"=>"note"},
    "group_role_map"=>{"cn=ld_zammad-agents,ou=security groups,ou=domain,dc=domain,dc=local"=>["1", "2"]},
    "unassigned_users"=>"sigup_roles"},
  prio: 3,
  active: true,
  updated_by_id: 1,
  created_by_id: 2,
  created_at: Mon, 24 Oct 2022 12:33:21.505000000 UTC +00:00,
  updated_at: Fri, 04 Aug 2023 12:13:35.273000000 UTC +00:00>,
 #<LdapSource:0x00007fc2c187c8d8
  id: 4,
  name: "domain.local_Admins",
  preferences:
   {"host_url"=>"ldaps://dc02.domain.local",
    "ssl_verify"=>true,
    "options"=>
     {"DC=domain,DC=local"=>"DC=domain,DC=local",
      "CN=Configuration,DC=domain,DC=local"=>"CN=Configuration,DC=domain,DC=local",
      "CN=Schema,CN=Configuration,DC=domain,DC=local"=>"CN=Schema,CN=Configuration,DC=domain,DC=local",
      "DC=DomainDnsZones,DC=domain,DC=local"=>"DC=DomainDnsZones,DC=domain,DC=local",
      "DC=ForestDnsZones,DC=domain,DC=local"=>"DC=ForestDnsZones,DC=domain,DC=local"},
    "option"=>"DC=domain,DC=local",
    "base_dn"=>"DC=domain,DC=local",
    "bind_user"=>"ldap",
    "bind_pw"=>"xxxxxxx",
    "user_uid"=>"objectguid",
    "user_filter"=>
     "(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$))(memberOf=CN=LD_Zammad-Admin,OU=Security Groups,OU=domain,DC=domain,DC=local))",
    "group_uid"=>"dn",
    "group_filter"=>"(objectClass=group)",
    "user_attributes"=>
     {"givenname"=>"firstname",
      "sn"=>"lastname",
      "mail"=>"email",
      "samaccountname"=>"login",
      "telephonenumber"=>"phone",
      "department"=>"department",
      "facsimiletelephonenumber"=>"fax",
      "mobile"=>"mobile",
      "title"=>"note"},
    "group_role_map"=>{"cn=ld_zammad-admin,ou=security groups,ou=domain,dc=domain,dc=local"=>["1"]},
    "unassigned_users"=>"sigup_roles"},
  prio: 4,
  active: true,
  updated_by_id: 1,
  created_by_id: 2,
  created_at: Mon, 24 Oct 2022 12:37:04.913000000 UTC +00:00,
  updated_at: Fri, 04 Aug 2023 12:13:35.286000000 UTC +00:00>]
irb(main):002:0>```

**Comment by fliebe92** [comment]
@blackbasket thanks a lot! In addition to this:

* Do you have a log of the migration from 6.1 to 6.2?
* Do you have the output of `LdapSource.all` after the migration?

**Comment by blackbasket** [comment]
No, sorry... I had to roll back, because it is productive ;)

I only tested quickly, that it would run unencrypted...

**Comment by blackbasket** [comment]
BTW: it is no docker installation...

**Comment by mpantel** [comment]
Unfortunately I am on 6.2 now and older config is missing.
But while on the configuration tab I have the following:
<img width="857" alt="Screenshot 2023-12-15 at 12 27 30" src="https://github.com/zammad/zammad/assets/44258/2021edde-fb9d-4b26-be47-a825f47b8380">

on the rails console (inside the docker rails server container) I get empty result for the LdapSource.all

**Comment by mgruner** [comment]
@mpantel you can use `docker compose run` rather than `exec`, then the rails command should work properly.

See: https://docs.zammad.org/en/latest/install/docker-compose.html#step-4-start-zammad-using-dockerhub-images

**Comment by mpantel** [comment]
Yes you are right! This is for 6.2 setup (6.1 is unavailable)

 [#<LdapSource:0x00007fa597806738
  id: 1,
  name: "Aegean LDAP",
  preferences:
   {"options"=>
     {"DC=aegean,DC=gr"=>"DC=aegean,DC=gr",
      "CN=Configuration,DC=aegean,DC=gr"=>"CN=Configuration,DC=aegean,DC=gr",
      "CN=Schema,CN=Configuration,DC=aegean,DC=gr"=>"CN=Schema,CN=Configuration,DC=aegean,DC=gr",
      "DC=DomainDnsZones,DC=aegean,DC=gr"=>"DC=DomainDnsZones,DC=aegean,DC=gr",
      "DC=ForestDnsZones,DC=aegean,DC=gr"=>"DC=ForestDnsZones,DC=aegean,DC=gr"},
    "option"=>"DC=aegean,DC=gr",
    "base_dn"=>"DC=aegean,DC=gr",
    "bind_user"=>"aegean\\XXXXXXXXX",
    "bind_pw"=>"XXXXXXXX",
    "user_uid"=>"objectguid",
    "user_filter"=>"(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))",
    "group_uid"=>"dn",
    "group_filter"=>"(objectClass=group)",
    "user_attributes"=>{"givenname"=>"firstname", "sn"=>"lastname", "mail"=>"email", "samaccountname"=>"login", "telephonenumber"=>"phone"},
    "group_role_map"=>
     {"cn=ru helpdesk admins,ou=helpdesk users,ou=ru security groups,ou=people,ou=research unit,dc=aegean,dc=gr"=>["1"],
      "cn=ru helpdesk users,ou=helpdesk users,ou=ru security groups,ou=people,ou=research unit,dc=aegean,dc=gr"=>["2"],
      "cn=ru helpdesk ruit,ou=helpdesk users,ou=ru security groups,ou=people,ou=research unit,dc=aegean,dc=gr"=>["4"],
      "cn=ru helpdesk rcs,ou=helpdesk users,ou=ru security groups,ou=people,ou=research unit,dc=aegean,dc=gr"=>["5"],
      "cn=ru helpdesk vice rector of ri,ou=helpdesk users,ou=ru security groups,ou=people,ou=research unit,dc=aegean,dc=gr"=>["6"],
      "cn=ru helpdesk accounting,ou=helpdesk users,ou=ru security groups,ou=people,ou=research unit,dc=aegean,dc=gr"=>["7"]},
    "unassigned_users"=>"skip_sync",
    "ssl_humanized"=>"SSL",
    "host"=>"XXXXXX.aegean.gr",
    "ssl"=>"ssl",
    "ssl_verify"=>true},
  prio: 0,
  active: true,
  updated_by_id: 9,
  created_by_id: 3,
  created_at: Tue, 07 Nov 2023 13:58:34.993000000 UTC +00:00,
  updated_at: Wed, 13 Dec 2023 08:46:05.777000000 UTC +00:00>]

**Comment by dominikklein** [comment]
Looks to me that in all situations the migrations, in general, didn't run successfully. Especially for @blackbasket, we can see that the SSL-Certificate table was also missing, which means all other migrations (also the LDAP migration) afterward didn't run.

You could run `ActiveRecord::Migration.check_pending!` in the rails console to check if some migration is not executed.

(Such a situation could happen when for example postgres is updated together with the Zammad update)

For now, this looks more like a technical question, so when we do not receive any additional information that points to a visible problem, I will close this issue.

**Comment by mpantel** [comment]
Hi @dominikklein,
no pending migrations for me.

Thank you all  for your support!

**Comment by blackbasket** [comment]
Thanks @dominikklein 

How may we fix, that multiple updates run at the same time? I only ran `apt update` and `apt upgrade`

**Comment by dominikklein** [comment]
I think at the moment there are some limitations because of the Zammad installer handling (but I'm not an expert in this area, so could be that I also saying something wrong).
But one additional step after an update could be, to check if there are pending migrations, maybe we can also improve this in general so that the services can not be started again (I will ask this internally).

For now, I would close the issue and you can ask any additional questions in the community.
