### ISSUE TITLE
Erroneous error message during password reset

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad#4989]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

During the password reset verify process, the app shows an error message **Something went wrong. Please contact your administrator.**. However, the password *is* updated successfully, and the old one does not work anymore.

### Expected behaviour

If the password reset verification is successful and the password is updated for the user, the app should inform the user about this via a success message **Woo hoo! Your password has been changed!**.

### Steps to reproduce the behaviour

1. Enable at least one 2FA method for a user.
2. Request a password reset for the same user.
3. Click on the link in the received email and choose a strong new password.
4. Press **Submit** and observe the reported error.

The issue is caused by an automatic login request *after* successful password change. Since this is done in the background, user has no opportunity to provide their 2FA token and the authentication will fail with a cryptic error message.

Consider removing the mechanism that automatically logs in the user after password reset. The users should always use the regular login flow so they can solve their 2FA challenges in appropriate place. Instead, inform the user of successful password change via a toast message and simply redirect them to login screen.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by retrodans** [comment]
@dvuckovic We are also getting this issue, did you find a cause/solution?

We are using Zammad version 6.4.0

**Comment by dvuckovic** [comment]
@retrodans Yes, I think the proposal for the fix I outlined above would work great here.

Just one note after working on it a bit: instead of completely removing the automatic login, in case it fails, we would just redirect to the login screen, but with a positive confirmation message. Then the user's with an active 2FA method can complete the normal login flow. 

In case the user has no 2FA set up, the automatic login would still work just like before. This way we stay backward compatible, at least for now.

In the new stack (mobile/desktop view), the automatic login was skipped during reimplementation, so this issue was not present there.

The fix is incoming shortly, stay tuned.
