### ISSUE TITLE
Renaming standard roles breaks ticket views

### ISSUE THREAD

**Issue by driebe** [zammad/zammad#499]
Hi,

I think I found my first real bug: when renaming the standard roles of Zammad (for instance renaming "agent" to "employees") it breaks all ticket views and the following error message appears:

> {"error":"undefined method `each' for nil:NilClass"}

Even after trying to create further ticket views in response to the name-change, both admins and normal agents get this error.

Best regards
Daniel

**Comment by thorsteneckel** [comment]
Hi @driebe - that indeed is a change that causes some troubles. Since this one sits deeper we have to check if and how we can fix this. We will come back here. This might take some time.

**Comment by driebe** [comment]
No worries. It would also be ok, if it wasn't possible to edit the standard roles at all.

**Comment by martini** [comment]
Fixed in 1.0, 1.1 and develop.
