### ISSUE TITLE
undefinied method "store_hash" on avatar delete

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#4991]
### Used Zammad Version

6.2

### Environment

- Installation method: package
- Operating system: ubuntu 20.04
- Database + version:  postgresql
- Browser + version: Microsoft Edge 120

### Actual behaviour

If I delete an avatar of an user I get sometimes the following error. The avatar is delete and not showing in the UI but an error 500 message appears in a modal window. I delete the avatar by take over their session (Admin Panel > search for user > login as user XY)

### Expected behaviour

No error on delete an avatar

### Steps to reproduce the behaviour

We use active directory sync for our users (maybe it is helpful)
1. Login as Admin
2. Go to Admin > Users and search for a user which has an avatar defined
3. Login with this account over the three dots menu
4. Go to Profile > Avatar and click on the small "X" to delete it
5. sometimes the following error appear

> I, [2023-12-22T13:36:26.712561#2621-944820]  INFO -- : Processing by TicketOverviewsController#data as JSON
I, [2023-12-22T13:36:26.712662#2621-944820]  INFO -- :   Parameters: {"_"=>"1703224533871"}
I, [2023-12-22T13:36:26.912876#2621-944820]  INFO -- : Completed 200 OK in 200ms (Views: 25.2ms | ActiveRecord: 58.1ms | Allocations: 78825)
I, [2023-12-22T13:36:29.124587#2613-1040600]  INFO -- : Started POST "/api/v1/users/avatar/set" for 10.20.44.12 at 2023-12-22 13:36:29 +0100
I, [2023-12-22T13:36:29.126764#2617-142620]  INFO -- : Started DELETE "/api/v1/users/avatar" for 10.20.44.12 at 2023-12-22 13:36:29 +0100
I, [2023-12-22T13:36:29.130027#2613-1040600]  INFO -- : Processing by UsersController#avatar_set_default as JSON
I, [2023-12-22T13:36:29.130083#2613-1040600]  INFO -- :   Parameters: {"id"=>43}
I, [2023-12-22T13:36:29.136285#2617-142620]  INFO -- : Processing by UsersController#avatar_destroy as JSON
I, [2023-12-22T13:36:29.136383#2617-142620]  INFO -- :   Parameters: {"id"=>44}
E, [2023-12-22T13:36:29.153524#2617-142620] ERROR -- : undefined method `store_hash' for nil:NilClass

>    user.update!(image: avatar.store_hash)
                              ^^^^^^^^^^^ (NoMethodError)
> app/controllers/users_controller.rb:903:in `avatar_destroy'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2023-12-22T13:36:29.177861#2617-142620] ERROR -- : Error ID -iSXTUuv: undefined method `store_hash' for nil:NilClass

>    user.update!(image: avatar.store_hash)
                              ^^^^^^^^^^^
> I, [2023-12-22T13:36:29.178180#2617-142620]  INFO -- : Completed 500 Internal Server Error in 42ms (Views: 0.2ms | ActiveRecord: 6.4ms | Allocations: 46398)
I, [2023-12-22T13:36:29.232929#2613-1040600]  INFO -- : Completed 200 OK in 103ms (Views: 0.2ms | ActiveRecord: 40.9ms | Allocations: 18228)
I, [2023-12-22T13:36:30.151230#2624-142000]  INFO -- : Started GET "/api/v1/users/1480?full=true&_=1703248581207" for 10.20.44.12 at 2023-12-22 13:36:30 +0100
I, [2023-12-22T13:36:30.162136#2624-142000]  INFO -- : Processing by UsersController#show as JSON
I, [2023-12-22T13:36:30.162257#2624-142000]  INFO -- :   Parameters: {"full"=>"true", "_"=>"1703248581207", "id"=>"1480"}
I, [2023-12-22T13:36:30.498276#2624-142000]  INFO -- : Completed 200 OK in 336ms (Views: 4.5ms | ActiveRecord: 26.7ms | Allocations: 24368)
I, [2023-12-22T13:36:30.578113#2670-6020]  INFO -- : ProcessScheduledJobs running...
I, [2023-12-22T13:36:30.581615#2670-6020]  INFO -- : Running job thread for 'Check 'Channel' streams.' (Channel.stream) status is: sleep
I, [2023-12-22T13:36:30.581745#2670-6020]  INFO -- : Running job thread for 'Generate 'Session' data.' (Sessions.jobs) status is: sleep
I, [2023-12-22T13:36:30.581818#2670-6020]  INFO -- : Running job thread for 'Process ticket escalations.' (Ticket.process_escalation) status is: sleep
I, [2023-12-22T13:36:30.581971#2670-6020]  INFO -- : Running job thread for 'Check channels.' (Channel.fetch) status is: sleep
I, [2023-12-22T13:36:30.588087#2670-6020]  INFO -- : Running job thread for 'Execute planned jobs.' (Job.run) status is: sleep

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @Dennis1993 👋🏻 

To be honest, I have no idea how this could happen. Usually, a default avatar is created for all users... even if I remove it manually by the Rails Console, it will be there later when the user is doing some interactions by using Zammad.

Could you please tell some more details about your users, especially the ones where this error happened?

**Comment by t-shehab** [comment]
No feedback received in five months. Closing this.
