### ISSUE TITLE
Set tag loses my state

### ISSUE THREAD

**Issue by truetonepb** [zammad/zammad#4993]
### Used Zammad Version

62

### Environment

- Installation method: Zammad demo installation
- Operating system: Zammad demo installation
- Database + version: Zammad demo installation
- Elasticsearch version: Zammad demo installation
- Browser + version: Microsoft Edge 120.0.2210.91

### Actual behaviour

If I select a tag and switch the state, the page refreshed after a few seconds and my settings (state) is missing. The state before is selected and I need to set all settings from beginning

![bild](https://github.com/zammad/zammad/assets/154685303/a8f50c77-baef-4aee-9a1e-af087739ab07)

### Expected behaviour

No refresh after selecting a tag or set a connection to another ticket/answer below

### Steps to reproduce the behaviour

select a tag and switch the state. After 1 or 2 seconds the state switched back to the old state and you need to set it again

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@truetonepb thanks for your report. This is currently a known problem when you are doing these changes in a "fast" way. A workaround could be to change the state before adding the tag or wait shortly before changing the state.
We know, normally the form should be disabled (or another solution) to avoid this, but during our re-write of the current desktop app this problem will be solved, so currently we will not do something in this direction here.
