### ISSUE TITLE
Bug  between Customer and Agent Role

### ISSUE THREAD

**Issue by Kevin202972** [zammad/zammad#4995]
### Used Zammad Version

6.2 and 6.1

### Environment

- Installation method: package
- Operating system ubuntu 22.04
- Database + version:  postgresql 14
- Elasticsearch version: 7.17.13
- Browser + version: all

### Actual behaviour

I assigned more roles to an agent. A role “Agent X”, “Kunde” and “ Kunde Mitarbeiter X”.

The “Kunde” role only has the “customer” permission in the permissions. Just like the role “_ Kunde Mitarbeiter X”

In principle, both roles have the same authorization, but different customers are assigned to the roles because the people within our company have different authorizations and should therefore be assigned different workflows.
The role “_Agent X” has the “Agent” and “Customer” permissions.

If I create a ticket with this role constellation for another agent who has assigned the same roles, then the owner of the ticket, than the owner field in the editormask won’t be visible for the agent who is assigned as customer and zammad behaves like the agent who is assigned as customer has only customer rights:
![743a8086-2c86-4160-9808-4b585f02b615](https://github.com/zammad/zammad/assets/142332276/6744cf35-e22c-41c3-b5c7-908144795317)

But if I take away the role “_ Kunde Mitarbeiter X” from the agent so that this agent only has the roles “Kunde” and “_Agent X”, then the agent sees the owner again and behaves that the customer of the ticket has agent rights:
![c1a41c63-d47c-4536-8480-51eba4c8d109](https://github.com/zammad/zammad/assets/142332276/5d466564-db15-48f9-9163-853b274f9af8)

If i assigne the agent another role that is constructed exactly like the role “_ Kunde Mitarbeiter X” but has a different name, than the behavior is normal and the agent has normal agent right for the tickets wherer he is assaigned as customer. But i found some more roles where the same behavior appears that an agent is treated as customer

But if I delete the role “_ Kunde Mitarbeiter X” and create it again, it works at first, but after a certain time the bug appears again.

### Expected behaviour

Agents with the same agent role should treated every time as agent.

### Steps to reproduce the behaviour

I cant tell because it dosent apperas by every role as i mention before

### Support Ticket

https://community.zammad.org/t/bug-or-problem-between-customer-and-agent-role/12653/3

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Bozo0511** [comment]
Hi Kevin,

Without exact steps on how to recreate the issue, we can not in vestige the issue.
This looks like a complex Problem, and I was not able to reproduce it.

If you can provide me exact steps and screenshots how the roles are configured, I can maybe reproduce the issue.

**Comment by Kevin202972** [comment]
Hey,

"I'm sorry, I forgot about that. The problem has been resolved. It was due to a conflict with some workflows.
