### ISSUE TITLE
Fixed width of articles body

### ISSUE THREAD

**Issue by KarstenDreier** [zammad/zammad#4996]
### Used Zammad Version

6

### Environment

- Installation method: 
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 
- Browser + version: Edge Version 120.0.2210.91 (Offizielles Build) (64-Bit)

### Actual behaviour

The body of existing or new articles is fixed to 1080px. Tables wider than 1080px are cut off at the right border of the articles body.
When sending an html email with an embedded table, which is wider than 1080px, all the contents outside the 1080px limits are not visible.

### Expected behaviour

I'd like to have a dynamic bodywidth in articles. Depending on the browsers windows size, the display of articles should be adjusted. If the content is too wide to be shown horizontally, there should be a horizontal scrollbar for the articles panel.

### Steps to reproduce the behaviour

Easy to reproduce: Just send a html mail with an embedded table wider than 1080px.

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by dominikklein** [comment]
Can you please provide an example mail for easier reproduction?

**Comment by KarstenDreier** [comment]
Hi Dominik,
after some testing, the reason for my problem is obviously my own misunderstanding of Outlook Mails with Tables. There are some Options for tables one can choose. Using the Anchor in the lower right corner of the table to resize the whole table, sets the preferred Width to a fixed value. In this Case, the table in a Zammad article also has a fixed width. 

Because Zammad articles have a maximum width, in some cases the Table cannot be fully displayed. This is why I'd like to have a dynamic Width of the article panel.

![image](https://github.com/zammad/zammad/assets/155525940/460f72e0-3b55-40ef-94d1-881c39df008e)

**Comment by dominikklein** [comment]
When you still think it's a problem inside Zammad, you should provide some example eml-Files to make the reproduction more easier.
Otherwise, we can close the issue.

**Comment by KarstenDreier** [comment]
Hi, thanks for your contribution. I think, the issue can be closed.
