### ISSUE TITLE
Core Workflow: "fill in empty" fires on non-empty fields during ticket creation when logged in as customer

### ISSUE THREAD

**Issue by t-shehab** [zammad/zammad#5004]
### Used Zammad Version

6.2.0-1704877727.2bda00c4.bookworm

### Environment

- Installation method: any (verified on package and SaaS)
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

This is very closely related to: https://github.com/zammad/zammad/issues/4825

A CoreWorkflow: ```fill in empty``` fires during ticket creation on empty fields when logged in as a customer. This was apparently fixed in above mentioned issue, but apparently only for the creation mask when logged in as agent. Logged in as a customer, the same thing still happens.

[simplescreenrecorder-2024-01-10_16.43.22.webm](https://github.com/zammad/zammad/assets/114283486/1b25fe48-35f3-4a54-9a32-5e07b8464472)

### Expected behaviour

```fill in empty``` does not fill non-empty fields.

### Steps to reproduce the behaviour

* Configure CoreWorkflow to ```text -> fill in empty```
* Log in as customer
* create new ticket
* Fill body text with placeholder text
* Activate the CoreWorkflow condition to ```fill in empty```

### Support Ticket

Ticket#10147821

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by PaulchenPlump** [comment]
We also have the problem with this version (but bullseye). I do believe it was still working a few days ago (at least on 2024-01-05), but there have been a few new versions in between...
