### ISSUE TITLE
Using external data source object as an overview condition shows the search going on into infinity, even when no results are found

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#5006]
### Used Zammad Version

6.2. develop

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge v.120.0.2210.121 (64-Bit)

### Actual behaviour

The drop-down menu serving as a preview lists the information from the database. However, when using an external data source as an object field in the conditions for overviews, although a specific search result has been selected and the ticket has been updated with it, it is not found as a search phrase. No tickets are found, but the search in the overview conditions seems to continue without end. 

### Expected behaviour

When using an external data source as an object field in the conditions for overviews, although a specific search result has been selected and the ticket has been updated with it, it is not found as a search phrase. Hence, if no tickets are found within search parameters are found, the search in the overview conditions should also end, as soon as no tickets can be found to fit the search criteria. 

### Steps to reproduce the behaviour

1) Create an object field for an external data source.
2) Select specific search results from the drop-down menu in the ticket. 
3) Try to create an overview with the object field created in 1) as a condition. When entering the desired search term, no tickets are found, but the external data source seems to continue searching.

https://github.com/zammad/zammad/assets/101350124/b9813faf-be14-49bb-838e-b654a1e1a89c

### Support Ticket

Ticket#10149565

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mantas** [comment]
This one turned out to be identical to #5148. Closed with https://github.com/zammad/zammad/commit/8d4f763ec852ce2fea3d9268964e8e7ddd135651.
