### ISSUE TITLE
Gitlab/Github UI loses links when they are renamed

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#5015]
### Used Zammad Version

6.2. develop

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge v.120.0.2210.144 (64-bit)

### Actual behaviour

Renaming GitHub issues (changing name or path/repo) added to a Zammad article will cause Zammad to update the link displayed in the right sidebar the first time the page is reloaded afterward. Renaming a GitLab issue that has been added to a Zammad ticket will result in the issue being removed completely, although the issue previously connected is still displayed in the icon. 

### Expected behaviour

Renaming GitHub issues (changing name or path/repo) added to a Zammad article will cause Zammad to update the link displayed in the right sidebar the first time the page is reloaded afterward. Renaming a GitLab issue that has been added to a Zammad ticket should also be updated, as it is with GitHub issues. 

### Steps to reproduce the behaviour

1) enable GitLab Zammad integration
2) create and add an GitLab issue to one Zammad ticket
3) change in GitLab under: Settings --> General --> Advanced --> Change path (changing the URL)--> click on "Save path" and go back to Zammad. If you only once changed the path, the GitLab integration looks like this:

<img width="305" alt="Screenshot 2024-01-22 134431" src="https://github.com/zammad/zammad/assets/101350124/7d0a33b5-f225-46a4-ade7-a64fad41ff90">

### Support Ticket

Ticket#10149033

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
Sorry, wrongly closed.
