### ISSUE TITLE
PGP messages are not always decrypted

### ISSUE THREAD

**Issue by abrain** [zammad/zammad#5018]
### Used Zammad Version

6.2.0-1705680905.15ef3d10.bullseye

### Environment

- Installation method: package
- Operating system: debian 11.8
- Database + version:  postgresql 13.13
- Elasticsearch version: 7.17
- Browser + version: firefox 121

### Actual behaviour

Most of the incoming PGP encrypted messages are properly decrypted. However, there are certain message formats that will result in a ticket with the unprocessed contents (`-----BEGIN PGP MESSAGE-----` and so on).

Proper multipart/encrypted mails (`This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)`) seem to work just fine.

The affected messages are either
- `Content-Type: text/plain` messages which just start with `-----BEGIN PGP MESSAGE-----`.
- `Content-Type: multipart/alternative;`messages that contain the PGP encrypted content twice. Once as `text/plain` encoded with `quoted-printable` and also as `text/html` part that starts with `<!DOCTYPE html><html><head><meta http-equiv=3D"Content-Type" content=3D"t=
ext/html; charset=3Dutf-8"></head><body><pre>-----BEGIN PGP MESSAGE-----`
- `Content-Type: multipart/mixed` messages with a `text/plain`part for the encrypted message and a `application/octet-stream` part for a separately encrypted attachment (file.pdf.gpg)

### Expected behaviour

The PGP message should be decrypted.

I realize this may not be the recommended way to send PGP emails, but we receive such emails all the time and they always need manual intervention.

### Steps to reproduce the behaviour

[Mailvelope](https://mailvelope.com/) sends emails that way. Also the following command can produce mails like that:

```
echo "lorem ipsum" | gpg2 -u "$MAIL_SENDER" -eas -r "$MAIL_RECIPIENT" | swaks --to "$MAIL_RECIPIENT" --from "$MAIL_SENDER" --server "$MAIL_SERVER" --port "$MAIL_PORT" -tls --tls-verify --auth LOGIN --auth-user "$MAIL_USER" --auth-password "$MAIL_PASSWORD" --header "Subject: PGP as plain text" --attach-type text/plain --attach-body -
```

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
Hi @abrain,

we decided against the handling of this *deprecated* `inline` PGP encrypted or signed messages, see https://github.com/zammad/zammad/issues/4679. Our implementation fulfills [RFC3165](https://www.rfc-editor.org/rfc/rfc3156), which means no proper `content-type` neither decryption nor verification is triggered.
