### ISSUE TITLE
Add user-“status” to scheduler-conditions

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5020]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

**What is your original issue/pain point you want to solve?**
I want to automatically and regularly delete Zammad users that are inactive.

**Which are one or two concrete situations where this problem hurts the most?**
When a colleague leaves the company and is set to inactive in my Active Directory, he/she is now synced to Zammad anymore, because I have setup an LDAP-filter in Zammad for that. This user is now set to inactive in Zammad as well.

I now want to create a scheduler, that deletes these users after a few days.

**Why is it not solvable with the Zammad standard?**
The status of the Zammad user (active/inactive) is not available as a condition in the scheduler.

### Expected behaviour

Being able to select the user status in the conditions of a user scheduler.

### Steps to reproduce the behaviour

Follow Up of this FR: https://community.zammad.org/t/add-user-status-to-scheduler-conditions/12860

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by dominikklein** [comment]
Seems to be related: https://github.com/zammad/zammad/issues/4665

**Comment by dominikklein** [comment]
@YetAnotherGerrit @Mirtaaa already solved with: https://github.com/zammad/zammad/issues/4665
