### ISSUE TITLE
Email Forwarding fails on special character combination .../ in Subject/Text

### ISSUE THREAD

**Issue by mariowenigQP** [zammad/zammad#5023]
### Used Zammad Version

6.2

### Environment

Installation method: zammad/unknown 6.2.0-1705920690.db7738e0.focal amd64
Operating system : Ubuntu 20.04.6 LTS
Elasticsearch version: 7.17.16
Browser + version: Edge 120.0 + Chrome 120.0 (NOTE: Firefox works 110.0.1)

### Actual behaviour

When trying to "forward" a ticket that contains .../ within text or title header in original email.
Both Edge and Chrome throw "Das Speichern ist fehrgeschlagen".
Email does not get forwarded.

Browser console shows": Uncaught SyntaxError: Unexpected token '<', as broken html content; <html....is not valid JSON.

### Expected behaviour

Email gets forwarded without pop-up error and error in console.

### Steps to reproduce the behaviour

Create ticket with .../ within the Subject or Text of email submitted.
Forward from Edge or Chrome should result in the above named issue.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Bozo0511** [comment]
Hi,
I was not able to recreate the issue.

![2024-08-02 14_34_37-Zammad Helpdesk - #77003 - Testing  _ issue - Persönlich – Microsoft​ Edge](https://github.com/user-attachments/assets/34e3bdbf-7e14-477c-b8f3-b32b733d646c)

Can you please provide me step-by-step instructions with screenshots on how to recreate the issue?

**Comment by mgruner** [comment]
No feedback, closing. Please feel free to provide more information.
