### ISSUE TITLE
6.2: group hierarchy should be displayed as a TreeSelect

### ISSUE THREAD

**Issue by jouvin** [zammad/zammad#5026]
### Used Zammad Version

6.2

### Environment

- Installation method: [e.g. source, package] package
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04] rhel 8
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3] postgresql 14
- Elasticsearch version: [e.g. 7.17] 8 but not relevant
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] opera 109

### Actual behaviour

If you define a hierachy of groups, they appear as a flat list in the ticket creation form. For example if you defined the following groups:

```
grp1
grp1::test1
grp1::test2
grp2
```

You will get the following entries in `Group` field of the ticket creation form:

```
grp1
grp2
test1
test2
```

This is very confusing for a user as you don't have any sense that `test1` and `test2` are related to `grp1`. And there is a risk of clash if `grp2` also has subgroups with same name which is IMO completely legitimate. 

### Expected behaviour

I'd expected the Group field to be a tree select displaying something like this:

```
grp1 >
grp2
```

and when clicking on the arrow on the right of  `grp1` see:

```
test1
test2
```

In addition it would be nice to allow the parent group to be inactive (it seems to work already even if the group must be active to create the subgroup) and have the selection of the parent group disabled in this case (to allow creation of tickets only in subgroups), in the way it is done for any tree select since 6.2.

### Steps to reproduce the behaviour

See above

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by fliebe92** [comment]
Hi @jouvin. I'm sorry, but I cannot reproduce your described issue.

![image](https://github.com/zammad/zammad/assets/8327427/c0053641-1994-4607-80a8-60a7519cbc9f)

![image](https://github.com/zammad/zammad/assets/8327427/30bf61d0-2f9e-4853-8037-881f95d4f43a)

![image](https://github.com/zammad/zammad/assets/8327427/9888edc1-6aee-493a-8d5d-a3fdc87bf9be)

**Comment by jouvin** [comment]
What you show is exactly what I was expecting and I was very surprised it was not the case, based on my Zammad experience... I'm getting the same management view as you but not the same ticket form view...  Do you have an idea about what could cause the problem? I'm using package zammad-6.2.0-1704877727.2bda00c4.centos8.x86_64.

**Comment by dominikklein** [comment]
Did you already try it with a clean browser (e.g. private tab)?

And are you sure that the update was correct maybe some files don't have the current state in your installation? Maybe because of some customizations?

**Comment by jouvin** [comment]
Sorry for the delay... I tried again and it works as expected, Not sure what I did wrong in my first attempt... I still have a problem with the current implementation : I'd like to have a disabled parent group so that clients can open tickets only in subgroups, not in the parent group. It does not seem to be possible with the current implementation: if the parent group is disabled, subgroups are no longer displayed as a tree select but as individual groups in the first-level list.

Did I miss something? If not, any plan to support such a configuration?

**Comment by dominikklein** [comment]
Normally when you don't have permission on the parent group but on some child groups you should see the child groups. Maybe in some situations, this is not working as expected.

For this, it would be nice to have some clear reproduction steps.

**Comment by jouvin** [comment]
I'll open a new ticket as it is a side issue for this one which can be closed. I haven't done it immediately because I'm "single-arm" after breaking the ither! But it is not a good reason, sorry.
