### ISSUE TITLE
OTRS import: When importing OTRS fields where the attribute key contains two colons „::“ in it, these attributes are removed in the Zammad object.

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5027]
### Used Zammad Version

6.2.0.bba4f84a3.saas

### Environment

- Installation method: SaaS
- Plugin: Znuny4OTRS-ZammadMigrator-6.0.7.opm

### Actual behaviour

This is how the object looks like in OTRS

![OTRS_Kategorien_Auswahlfeld](https://github.com/zammad/zammad/assets/129729908/686776e5-4453-431d-9a08-2dae773d6096)

![OTRS_Kategorien](https://github.com/zammad/zammad/assets/129729908/220a4f5f-0af5-4ca4-bde8-cfb4339cda0d)

This is how the object looks like in Zammad after the import.

![Zammad_Kategorien](https://github.com/zammad/zammad/assets/129729908/677e1e57-df10-4c08-b6a0-1d46e1777d42)

### Expected behaviour

When importing a single selection field from OTRS, there the attributes key has two colons „::“ in it, Zammad should not remove these fields completely. The best would be to create a „Single tree selection field“ 

### Steps to reproduce the behaviour

Import from OTRS there is a single selection field with an attribute key which contains two colons "::"

### Support Ticket

Ticket#10149578

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Normally there is a flag that decides inside OTRS if it's a Treeselect or normal Select:

![Bildschirmfoto 2024-02-01 um 13 25 33](https://github.com/zammad/zammad/assets/5445094/5bf37955-0e49-4b0b-b74b-2ca58d2a34d5)
