### ISSUE TITLE
Mandatory-asterisk is missing for body attribute

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5028]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When creating a ticket, the body is a mandatory field. But it is missing the asterisk that is marking mandatory fields.

### Expected behaviour

Having an asterisk beside "Text" like it is there with "Title" and "Customer":
![image](https://github.com/zammad/zammad/assets/97293098/737f60aa-9ec1-43a5-b3a3-00957f553292)

### Steps to reproduce the behaviour

Create a ticket and leave "Text" empty.

### Support Ticket

Ticket#10140065

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
Need revert because of https://github.com/zammad/zammad/issues/5039

**Comment by kingmanfri** [comment]
Are there any updates on this request? It seems that a revert was necessary because the fix was not effective, and the topic has been closed. Thank you very much.

**Comment by fliebe92** [comment]
> Are there any updates on this request? It seems that a revert was necessary because the fix was not effective, and the topic has been closed. Thank you very much.

Hi @kingmanfri. We decided to not fix this in the current desktop view of Zammad. We're currently working on a more modern version of it, where this issue will be addressed + fixed. Stay tuned!
