### ISSUE TITLE
Health check API not working when logged in as non-admin

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5029]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When logged in with a non-administrator account the /api/v1/monitoring/health_check endpoint reports a permission denied. Which is odd, because it should not check for any permission, as authorization is done by the current token. And opening the endpoint without logging in works as intended.

### Expected behaviour

Accessing /api/v1/monitoring/health_check should not consider the session that is currently logged in.

### Steps to reproduce the behaviour

Copy the complete URL from monitoring and open in three browser sessions:
- Logged in as admin (works)
- Not logged in (works)
- Logged in as agent/customer without admin permissions (does not work)

Use case: admin has two accounts. And admin and an agent account. Admin uses a browser plugin that monitors the health_check api endpoint, but is usually logged in with the agent account.

### Support Ticket

Ticket#10140065

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Said endpoint is to be used with a token and thus does not require any valid sessions.
Access to these information should not be available without any token or "authenticated" person.

An agent usually does not require information from heal information aka monitoring at all. This should be handled at another 3rd party place instead of Zammads very technical approach.

**Comment by YetAnotherGerrit** [comment]
> Said endpoint is to be used with a token and thus does not require any valid sessions.

Agree. Thats why I consider it a bug, if it rejects access when there is a valid agent session. As access is validated by the token, the session should be ignored.

**Comment by MrGeneration** [comment]
Sorry I missread.
