### ISSUE TITLE
Add API/Framework for pluggable authentication

### ISSUE THREAD

**Issue by cornelinux** [zammad/zammad#503]
I would like to add two factor authentication by connecting zammad to the 2FA system privacyidea. This could be done by allowing some plugin concept to easily add a module, which handles the authentication.

In this very case the username and password/credentials would be simple sent to a REST API, so that the 2FA system can grant or deny access.

This probably connects to #484

**Comment by thorsteneckel** [comment]
We plan to refactor the authentication code since now it's a big if-else blob. This will a goal we will achieve with it.

**Comment by dominikklein** [comment]
We improved the layer with this commit: https://github.com/zammad/zammad/commit/467bc03224b6a76c6ff5fa74e084d321eb38c67c
