### ISSUE TITLE
Hi @abrain,

### ISSUE THREAD

**Issue by noezdev** [zammad/zammad#5032]
We also have problems with some PGP emails. Most encrypted emails we receive work perfectly fine, but there are some where the attachments are not visible as attachments but rather as text within the email, starting with: 'Content-Type: application/octet-stream; name="xyz.pdf.gpg" Content-Transfer-Encoding: base64 Content-Disposition: attachment; filename="xyz.pdf.gpg"' followed by long, cryptic code. It looks like encrypted text. Additionally, in these emails, umlauts are displayed strangely, for example, 'Mit freundlichen Gr=C3=BC=C3=9Fen.' The email also begins with strange content like 'MIME-Version: 1.0 Content-Type: multipart/signed; protocol="application/pgp-signature"; micalg=pgp-sha256 ; boundary="" Content-Type: multipart/related; boundary="" Content-Type: text/plain; charset="utf-8" Content-Transfer-Encoding: quoted-printable.' So, while the plaintext of the email is decrypted, the umlauts are hard to read. Could these be unsupported PGP-inline messages? Should I tell the sender to use PGP/MIME or is this a completely different issue?

              Hi @abrain,

we decided against the handling of this *deprecated* `inline` PGP encrypted or signed messages, see https://github.com/zammad/zammad/issues/4679. Our implementation fulfills [RFC3165](https://www.rfc-editor.org/rfc/rfc3156), which means no proper `content-type` neither decryption nor verification is triggered.

_Originally posted by @tschaefer in https://github.com/zammad/zammad/issues/5018#issuecomment-1906232635_

**Comment by dominikklein** [comment]
@noezdev Please use our bug template for creating bugs.
