### ISSUE TITLE
6.2: group hierarchy is not displayed if parent group is disabled

### ISSUE THREAD

**Issue by jouvin** [zammad/zammad#5033]
### Used Zammad Version

6.2

### Environment

- Installation method: [e.g. source, package] package
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04] RHEL _
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3] 14
- Elasticsearch version: [e.g. 7.17] not relevant
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] Opera 106

### Actual behaviour

Define a hierachy of groups like:

```
grp1
grp1::test1
grp1::test2
grp2
```

Disable the parent group `grp1` so that tickets can be created only in subgroups. You will get the following entries in Group field of the ticket creation form:

```
grp2
test1
test2
```

Notion of group hierarchy is lost. And if you have same subgroups of different groups having the same names, you have a name collision.

### Expected behaviour

The (my!) expected rendering in the `Group` field of the ticket form is: 

```
grp1 | > 
grp2
```

with `grp1` greyed as it is not selectable.  And if clicking on the arrow on the right of `grp1`:

```
test1
test2
```

### Steps to reproduce the behaviour

See above

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by t-shehab** [comment]
Hi @jouvin,

thanks for opening this issue. However, I cannot reproduce the behaviour you're experiencing. In fact, when I follow the steps you outlined above, everything appears exactly as in your "Expected behaviour". Are you performing any additional steps to get the results you're describing?

[issue-5033.webm](https://github.com/zammad/zammad/assets/114283486/8cf66c9c-bffd-4d3a-a7e2-e0ab031e3d9e)

**Comment by dominikklein** [comment]
Only for reference: https://github.com/zammad/zammad/issues/5026

One additional question could be, is it about agent or customer users?

**Comment by jouvin** [comment]
It happens both for agents and customers. 

@t-shehab the probel is not in the management area but in the ticket creation form, in the group menu. 

@dominikklein you are right to mention it is somewhat a side issue of #5026 and me be my wrong report in this other ticket was because I used the configuration described here, with the parent group disabed. As it is slightly different from the original ticket I preferred to open a new one...

**Comment by t-shehab** [comment]
> @t-shehab the probel is not in the management area but in the ticket creation form, in the group menu.

Did you watch my screencast? In it, I am going into the ticket creation form twice. Once before disabling `grp1`, once after disabling it. Each time, the group selection menu does exactly what it's supposed to be doing.

**Comment by jouvin** [comment]
@t-shehab sorry I missed it was a video... but in fact I cannot play it successfully. Do I need something special to view it?

**Comment by jouvin** [comment]
@t-shehab as usual you are right! I understood and was able to reproduce the problem. I tested under an account who is a customer not an agent (under Chrome). If you open a session with the parent group active, then as an admin in another session, mamke the parent group inactive and then reload (or shift reload) the customer ticket creation form page, you have the mentioned wrong behaviour. You need to disconnect/reconnect to get the right behaviour. I suspect there is a caching effect somewhere...

**Comment by MrGeneration** [comment]
I don't mean to be rude, but please ask technical questions in our community forum instead of on Github. We're trying to keep this repository free of questions and instead being able to concentrade on todos and issues. 🙏

**Comment by jouvin** [comment]
@MrGeneration I understand but I was facing a problem looking as a bug and I thought it was more efficient to use GitHub... It turned out that the problem was not what I thought initially but the caching issue for me is a flaw somewhere. A (shift) page reload should clear the pb...

**Comment by dominikklein** [comment]
@t-shehab What is now the state here, is it something we can reproduce or is it working like expected?
