### ISSUE TITLE
How to upgrade zammad from 5.0.2-1 to 6.2

### ISSUE THREAD

**Issue by levanluu** [zammad/zammad#5036]
I want to upgrade my current version of zammad to the latest version, but I've always had problems with the zammad-init step.

Is there any way I can upgrade it?

**Comment by mgruner** [comment]
Hi @levanluu. Can you post the log output, please?

**Comment by levanluu** [comment]
`activerecord::recordinvalid: validation failed: user must exist when running zammad init`

I got this error, I don't have details about it right now, but I got this error when upgrading @mgruner

**Comment by levanluu** [comment]
`Caused by:
ActiveRecord::RecordInvalid: Validation failed: User must exist
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/validations.rb:80:in `raise_validation_error'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/validations.rb:53:in `save!'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/transactions.rb:302:in `block in save!'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/transactions.rb:302:in `save!'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/suppressor.rb:54:in `save!'
/opt/zammad/db/migrate/20230129220648_taskbar_update_preference_tasks.rb:11:in `block in up'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/relation/batches/batch_enumerator.rb:54:in `each'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/relation/batches/batch_enumerator.rb:54:in `block in each_record'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/relation/batches.rb:245:in `block in in_batches'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/relation/batches.rb:229:in `loop'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/relation/batches.rb:229:in `in_batches'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/relation/batches/batch_enumerator.rb:53:in `each'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/relation/batches/batch_enumerator.rb:53:in `each_record'
/opt/zammad/db/migrate/20230129220648_taskbar_update_preference_tasks.rb:8:in `up'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:908:in `public_send'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:908:in `exec_migration'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:889:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:888:in `block in migrate'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:887:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1095:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1409:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/transactions.rb:209:in `transaction'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1460:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1408:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1382:in `each'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1382:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1331:in `block in migrate'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1481:in `block in with_advisory_lock'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1496:in `with_advisory_lock_connection'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1477:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1331:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1166:in `up'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/migration.rb:1141:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <main>'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:491:in `exec'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.1/exe/bundle:45:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.1/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.1/exe/bundle:33:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate`


This is the error when I upgrade version @mgruner

**Comment by mgruner** [comment]
@levanluu thanks for the stack trace. This is very likely an issue in the Zammad application itself rather than in the docker compose files, so I will move it to the issue list of Zammad.

**Comment by levanluu** [comment]
I checked the upgrade to each zammad version and it failed from Zammad version 5.4.0 @mgruner

**Comment by dominikklein** [comment]
@mgruner Looks to me like a technical question (so it should be handled inside the community). Or is it really a real bug, then we should use the real bug template inside the first article, with the reproduction steps and the other information.

**Comment by mgruner** [comment]
@levanluu would you please be so kind to create a new bug in zammad/zammad for this with the required information and close this one here? Thank you.

**Comment by mgruner** [comment]
Superseded by #5040
