### ISSUE TITLE
Extend nesting of groups to 10 levels

### ISSUE THREAD

**Issue by Mirtaaa** [zammad/zammad#5037]
Assignes: @fliebe92 @tschaefer 

### What
Currently, there is a limitation in the group tree-select, which limits the levels to 6. If I have a very big company setting with a large amount of groups and levels, then 6 levels are not enough.

### Acceptance Criteria
- extend to 10 levels

### Intended Outcome
It should be possible to use more than 6 levels during the group creation. The UI/UX will not be improved for very high usage of levels, so the group names need to be short, so that this is really useable.

### Technical Implementation
An idea could be to have a setting that holds a default value and can be increased util a maximum value (e.g. 6-10).

The limit needs to be removed and the group's table columns size needs to be increased to the maximum level.

### Reference

_Ticket#10125404_
```[tasklist]
### Tasks
- [x] Extend group database table for the new level limit
- [x] Change current limit inside all needed places
```

**Comment by rolfschmidt** [comment]
I don't think this makes sense in the current state. Currently, the group performance wouldn't allow having a really high amount of groups. You can feel the decreasing performance already on 50–250 groups very heavily. This would definitely require an overhaul of the group field in general.

Also, not sure about the use case. 10 levels sounds very high and very strange to work with.

**Comment by dominikklein** [comment]
I think the level is not directly related to the amount of groups. For sure, at some point, we currently have problems with a high amount of groups, but this is another topic for the next months.

Normally such levels are not needed, but I think especially in public authorities there is often a more specific structure, which leads to such a situation (for sure the group names should be as short as possible when a lot of levels are used).
