### ISSUE TITLE
6.2 user management: confusing new UX for group assignment

### ISSUE THREAD

**Issue by jouvin** [zammad/zammad#5038]
### Used Zammad Version

6.2

### Environment

- Installation method: [e.g. source, package] package
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04] RHEL 8
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3] 14
- Elasticsearch version: [e.g. 7.17] N/A
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] Opera 106, Chrome 120

### Actual behaviour

When editing parameters for a user to give him/her agent role for some groups, the interface has been changed from a table with all groups displayed to a table where you add explicitely the groups you need to the table (and define the rights as previously). I guess the goal was to avoid an unnecessay long list if you have many groups...

The problem is that now you have to first click `Add` at the end of the added line to validate the addition in the group table and then the `Update` button to validate the change to the user parameters is confusing. If you forget one of them, the change is lost. It happens very often on our experience and this double validation requirement is not inline withe very clean/friendly interface of Zammad IMO. 

### Expected behaviour

Have the line added (as it is currentky the case) but with no need for clicking on a `Add` button (which implies adding immediately the last line with the group list menu) so that the chane is validated, as for other parameters, when the `Update`buton is pressed.

### Steps to reproduce the behaviour

See above

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by dominikklein** [comment]
@jouvin, thank you for the feedback regarding the behavior described. This behavior will be improved/changed in the desktop rewrite. Therefore, we will not make any changes related to this topic in the current desktop app anymore.
