### ISSUE TITLE
User merge does not work if both users mentioned the same ticket

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#5042]
### Used Zammad Version

6.2

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

User merge blocked:

```
     ActiveRecord::RecordInvalid:
       Validation failed: A mentioned user has no agent access to this ticket

#<ActiveRecord::RecordNotUnique: "PG::UniqueViolation: ERROR: duplicate key value violates Uniqu...AIL: key "(mentionable_id, mentionable_type, user_id)=(7, Ticket, 72)" already exists.\n"> with backtrace
```

### Expected behaviour

No merge conflicts

### Steps to reproduce the behaviour

- Create 2 users
- Create a ticket for the old user
- Create mentions for the ticket for both users
- `User.find(A).merge(B.id)`

### Support Ticket

Ticket#10150063

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by snizzleorg** [comment]
I found this here when looking for a way to merge users. Is there any documentation which details how the merging is supposed to work? I used 

User.find(A.id).merge(B.id) which returns true but User B stille exists after the operation. Is this the intended behavior? Can I safely delete User B after that?
