### ISSUE TITLE
Guided setup allows to invite user without email

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#5046]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

New Guided setup (as well as  old Getting Started) allows to invite a new user without email. It also shows a confusing error message if first name, last name and email are all empty.

### Expected behaviour

Invite user form should require an email to send invite link to.

### Steps to reproduce the behaviour

- Go to „Invite Colleagues“ step in Guided setup
- Put in name
- Do not put in email
- Submit form
- User is created without email and never receives invitation to select password.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@mantas @dvuckovic can be closed with https://github.com/zammad/zammad/commit/bf591bfe82d053311497c19dfeb2f27179ed32a7 or?

**Comment by dvuckovic** [comment]
I think the original issue has been addressed, as the required validator will now prevent submission without the provided email address. Not sure if we need to address the API as well, though.

**Comment by mantas** [comment]
API already prevents sending invite if email is not present. I think that's fine. That API is generic and not invite-screen-only.

**Comment by dominikklein** [comment]
Then let's los it :-)
