### ISSUE TITLE
SSL Verification for SAML throws an error

### ISSUE THREAD

**Issue by stijnbrouwers** [zammad/zammad#5048]
### Used Zammad Version

6.2.0-1

### Environment

- Installation method: Helm (Official)
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian GNU/Linux 11 (bullseye)
- Database + version:  postgresql 15.4.0
- Elasticsearch version: 8.12.0
- Browser + version: Firefox 122.0.1

### Actual behaviour

When enabling "SSL Verification" for "Authentication via SAML" (https://support.test.eismea.eu/#settings/security), we are receiving the following error:
![image](https://github.com/zammad/zammad/assets/9864443/d4785cb1-0d15-4b84-bbb0-76c06cee9fdd)

Looking into the code (app/models/setting/validation/saml/tls.rb) and the error message, I expect that resp.error is actually Nil and therefore can not have a ".empty?" method being called on it. I think extending the test to check if resp.error exists, should solve the problem

### Expected behaviour

That the change would be saved.

### Steps to reproduce the behaviour

Enable "SSL Verification" for "Authentication via SAML" (https://support.test.eismea.eu/#settings/security) and click "Submit"

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Sigtechnica** [comment]
Thank you!

**Comment by ibot3** [comment]
Sorry for the off-topic question, but when can we expect an release that includes the fix?

**Comment by dominikklein** [comment]
Should already available in the current 6.2, maybe you need to update.
