### ISSUE TITLE
Ticket sends reminder although status "open"

### ISSUE THREAD

**Issue by WWoodpecker** [zammad/zammad#5051]
### Used Zammad Version

6.2-latest (Zammad Docker-Compose v11.2.0)

### Environment

- Installation method: Docker
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 22.04 / Docker
- Database + version:  [e.g. postgresql 15.3-alpine
- Elasticsearch version: 8.8.0
- Browser + version: Edge 121.0.2277.112

### Actual behaviour

Hello,

we have 2 Zammad systems running, on both there is currently a ticket that sends daily reminder mails although the tickets are on the status "open". I have already tried to change the status to and then back to open, but notifications still come.
Both tickets used to have the status "Waiting for reminder", apparently the date entry is not deleted when switching to open.

### Expected behaviour

It should not write a message when the ticket is set to "open"

### Steps to reproduce the behaviour

Currently it only occurs with one ticket in each ticket system, I don't know if I can reproduce it at the moment

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Bozo0511** [comment]
Hi 

If we can not reproduce the issue, it will be impossible to find a solution.

Can you please provide us a screenshot of the Trigger?
Can you please provide us Step-by-step instructions on how to reproduce the issue.
