### ISSUE TITLE
OTRS Import: Group permissions are transferred if the agent has full rights to the group in the group settings

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5055]
### Used Zammad Version

6.2.0-1707917359.416894d4.bookworm

### Environment

- Installation method: Package
- Plugin: Znuny4OTRS-ZammadMigrator-6.0.7.opm
- Remote System: Znuny 7.0.15

### Actual behaviour

**Following configuration**

- Accounting_Gruppe  => has the following queue in Znuny "Accounting_Queue"
- Support_Gruppe => has the following queue in Znuny "Support_Queue"
- Sales_Gruppe => has the following queue in Znuny "Sales_Queue"
- The agent has the following group permissions for these groups.

<img width="1252" alt="Bildschirmfoto 2024-02-15 um 10 46 15" src="https://github.com/zammad/zammad/assets/129729908/f42693c7-57d0-495d-99fd-11093aef5da0">

The following permissions are then set for the agent in Zammad after the import.

![Bildschirmfoto 2024-02-15 um 10 46 52](https://github.com/zammad/zammad/assets/129729908/10728ba9-6d25-4740-b08b-24d92bab4192)

**- Permissions via roles on the groups have no influence to the agents in Zammad. No group permissions are set.**

<img width="1260" alt="Bildschirmfoto 2024-02-15 um 11 02 31" src="https://github.com/zammad/zammad/assets/129729908/18392e44-f448-492a-8155-ffcb0dbcc1aa">

<img width="1253" alt="Bildschirmfoto 2024-02-15 um 11 03 04" src="https://github.com/zammad/zammad/assets/129729908/f591961f-82c4-4a90-935a-54b517e02543">

This is the role for the testagent, but this is not taken over in Zammad, which i think is the correct behavior.

### Expected behaviour

No group permissions are set for agents in Zammad at the import.

### Steps to reproduce the behaviour

- Set Group permissons "RW" in Znuny for Agents as shown above.
- Do a migration from Znuny to Zammad with the Znuny4OTRS-ZammadMigrator-6.0.7.opm Plugin
- Take a look at the group permissions of the agent in Zammad

If you have any questions, please contact me, I have a test environment where I can show it.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Currently, the code is working as expected. The question would be is it really a not-wanted behavior or a behavior that should be removed from the code base.

**Comment by MarkusHeld** [comment]
I would also say that it is not necessarily a bug, as it is more of a special case. The problem is also quickly solved with the following workaround. I close the issue.

## remove all agent direct access to groups
User.with_permissions('ticket.agent').each do |user|
  user.group_ids = []
end
