### ISSUE TITLE
Multiselect values are not readable if the field is readonly and the value list is long

### ISSUE THREAD

**Issue by Koppishop** [zammad/zammad#5059]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

In my scenario I wantt o use the multi-select attribute to show the current process state to the reviewer agent "read only".
--> The interface is cut off after 3rd line. So when a value 4th or beyond is chosen, the agent could not scroll down in this list when attribute is read only. 

![image](https://github.com/zammad/zammad/assets/105932563/c5ee5889-d0bf-4af7-93c5-4a48bba60763)

### Expected behaviour

The field size in the sidebar should always scale to show all values of the attribute.
Alternatively even in read only the list of values show be able to scroll through

### Steps to reproduce the behaviour

Tested in different instances

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
This is a feature request.

**Comment by dominikklein** [comment]
As an addition, with the desktop rewrite we will no longer use the native html multi select field.

So I would not spent time in this direction.

Maybe the problem which should be solved needs to be more clear and the it could be checked how it can solved inside zammad.

**Comment by dominikklein** [comment]
With the rewrite, we no longer use the native multi-select field. So this will be completely different output with the desktop-rewrite.

<img width="970" alt="Bildschirmfoto 2024-06-01 um 12 26 26" src="https://github.com/zammad/zammad/assets/5445094/c8443209-4dad-4f0b-aea1-3a38bed3ce38">
