### ISSUE TITLE
Webhook custom payload not support complex object attribute values 

### ISSUE THREAD

**Issue by jeffersonrios17** [zammad/zammad#5060]
### Used Zammad Version

6.2.0

### Environment

- Installation method: Docker Compose
- Browser + version: Google Chrome Versão 121.0.6167.185 (Versão oficial) 64 bits

### Actual behaviour

The pre-enclosed information in the ticket in the custom field is not being displayed in the Webhook notification. I tried to apply two variables as a list and as an object and both behavior was the same, as a result #{ticket.system/ no such method}

![personalizate zammad webhook](https://github.com/zammad/zammad/assets/101750703/64d1fe00-b418-44c9-a78e-d31b4811d6fb)

![notification webhook](https://github.com/zammad/zammad/assets/101750703/34f2a05d-3864-4f3f-8fb3-67525e1d2766)

### Expected behaviour

The field should be returned all pre-enclosed information on the ticket by agent.

![interface zammad](https://github.com/zammad/zammad/assets/101750703/aac0bf92-52fc-4448-9fbb-81eea66d91c9)

![api zammad](https://github.com/zammad/zammad/assets/101750703/f9b40003-87ce-4e1e-a629-9e73d6efd569)

### Steps to reproduce the behaviour

Any trigger action for a specific call that has the System field pre-connected, may be through the triggers or schedule.

### Support Ticket

#4663

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
Hi @jeffersonrios17,

thanks for the report. We've to clarify that. Based on the code querying of custom attributes/fields is not allowed within the webhook payload. We limited this for security reasons. Based on the [documentation](https://admin-docs.zammad.org/en/latest/manage/webhook/payload.html) it is possible.

> Webhooks will also include fields for any relevant custom objects defined in your system.

**Comment by jeffersonrios17** [comment]
Hi @tschaefer,

It is not understood or returned. Currently, you are also receiving information from other custom fields as well. This does not mean that the following fields are displayed: classificacao, nivel_atendimento and plataforma

Grifei em blue to illustrate or agree return.

![comparation](https://github.com/zammad/zammad/assets/101750703/1ff6e60c-2c99-474f-9991-85f8acb1c74c)

I noticed that just the custom list fields are having a problem.

**Comment by tschaefer** [comment]
Currently, programmatical we limit the final object to simple data types only.

* String
* Integer
* Float
* DateTime

You address complex data types, e.g. multi-select-field which ends up being an array or hash.

We discuss if we can safely improve that or stay with the simple types.

**Comment by Cybernisk** [comment]
@tschaefer 
Is it possible to add Boolean type fields for the Custom payload as boolean is a simple type as well as integer or float?

**Comment by tschaefer** [comment]
Following additional object data types will be allowed.

* Array of simple data types
* Hash (single level) with simple data type values
* Boolean
