### ISSUE TITLE
Incorrect fingerprint for PGP key determined

### ISSUE THREAD

**Issue by abrain** [zammad/zammad#5068]
### Used Zammad Version

6.2.0-1708586921.9bcc425e.bullseye

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 11.9
- Database + version:  postgresql 13.14
- Elasticsearch version: 7.17
- Browser + version: firefox 122

### Actual behaviour

Upon uploading a PGP key, the fingerprint appears as "80" in the table, while all the other keys look just fine. Also the REST-API shows the fingerprint as `80` for this particular one.

![Bildschirmfoto 2024-02-26 um 16 09 21](https://github.com/zammad/zammad/assets/1263052/e6bf1a5a-0494-45a8-bd02-635f9b58a0d1)

The public key also cannot be downloaded. The API responds with status code 500, while the error log shows
```
ERROR -- : There was no public PGP key found. (SecureMailing::PGP::Tool::Error::NoPublicKey)
```

### Expected behaviour

The fingerprint should be determined correctly. 

The code assumes that the fingerprint always is printed in the second line:
https://github.com/zammad/zammad/blob/f2ef2be2b18022e44597fcbb3ceef98380fbc949/lib/secure_mailing/pgp/tool/parse.rb#L38

This is the case most of the time, but not guaranteed. It should be verified that the correct line is picked by checking it begins with `fpr`. Also the fingerprint itself could be checked to be 40 characters long.

### Steps to reproduce the behaviour

The key in question contains a signature directly on the key ([signature type `0x1F`](https://www.rfc-editor.org/rfc/rfc4880#section-5.2.1)), which comes before the fingerprint.

![Bildschirmfoto 2024-02-26 um 16 39 55](https://github.com/zammad/zammad/assets/1263052/30983b79-326b-4180-a005-2e2846048c63)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
Hi @abrain,

thx for the report. I already created a bugfix, but would like to have a key with such an embedded signature for testing. Do you have an idea/hint of how this key was generated?

**Comment by abrain** [comment]
Hi, thanks for the quick response. The key in question seems to have a designated revoker, so it allows another key/person to also revoke the key (just found out that this exists).

You can produce a test key for this issue by generating a key pair and then using `gpg --edit-key` on it. Enter `addrevoker` in the menu and specify a `uid` of another key, that exists in your keyring. The resulting key now has the additional `rvk` chunk before the `fpr` one.
