### ISSUE TITLE
PGP: Encryption fails if any uid is revoked

### ISSUE THREAD

**Issue by abrain** [zammad/zammad#5069]
### Used Zammad Version

6.2.0-1708586921.9bcc425e.bullseye

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 11.9
- Database + version:  postgresql 13.14
- Elasticsearch version: 7.17
- Browser + version: firefox 122

### Actual behaviour

Sending a PGP encrypted mail to a recipient whose key contains a revoked `uid` fails after a few tries. The mail is not sent and the tickets shows the following message:

![Bildschirmfoto 2024-02-26 um 17 11 16](https://github.com/zammad/zammad/assets/1263052/9f0e16e6-d818-4780-99a2-12366f2dc99f)

It is important to mention, that the email address that was the sole recipient of the email is not the one that got revoked. The error log shows that Zammad tries to encrypt the message to all uids that could be found in the key, not just the one given as recipient of the email.

```
I, [2024-02-26T16:04:35.510421#1767470-146300]  INFO -- : Completed 200 OK in 49ms (Views: 0.6ms | ActiveRecord: 7.4ms | Allocations: 10921)
E, [2024-02-26T16:04:35.587125#1767479-142140] ERROR -- : PGP: Version: 2.2.27
E, [2024-02-26T16:04:35.587239#1767479-142140] ERROR -- : PGP: Exec: /usr/bin/gpg --batch --yes --no-tty --verbose --status-fd 2 --armor --trust-model always --recipient john@example.org --recipient revoked@example.com --recipient john@example.net --encrypt
E, [2024-02-26T16:04:35.587293#1767479-142140] ERROR -- : PGP: Env: {"LC_ALL"=>"C", "GNUPGHOME"=>"/opt/zammad/tmp/zammad-gnupg-keyring20240226-1767479-ysy7lg"}
E, [2024-02-26T16:04:35.587334#1767479-142140] ERROR -- : PGP: Stderr: [GNUPG:] KEY_CONSIDERED 9D57338B9B5D19F0B555F3B65FED352734CCFE43 0
gpg: using subkey 24226C2994BA63BB instead of primary key 5FED352734CCFE43
[GNUPG:] KEY_CONSIDERED 9D57338B9B5D19F0B555F3B65FED352734CCFE43 0
gpg: automatically retrieved 'john@example.net' via Local
gpg: No trust check due to '--trust-model always' option
[GNUPG:] KEY_CONSIDERED 9D57338B9B5D19F0B555F3B65FED352734CCFE43 0
gpg: error retrieving 'revoked@example.com' via Local: No public key
gpg: no running Dirmngr - starting '/usr/bin/dirmngr'
gpg: waiting for the dirmngr to come up ... (5s)
gpg: connection to dirmngr established
gpg: error retrieving 'revoked@example.com' via WKD: No data
gpg: revoked@example.com: skipped: No data
[GNUPG:] INV_RECP 0 revoked@example.com
[GNUPG:] FAILURE encrypt 167772218
gpg: [stdin]: encryption failed: No data

E, [2024-02-26T16:04:35.587365#1767479-142140] ERROR -- : PGP: Status: pid 1854977 exit 2
E, [2024-02-26T16:04:35.616702#1767479-142140] ERROR -- : Can't use Channel::Driver::Smtp: #<SecureMailing::PGP::Tool::Error::InvalidRecipient: The PGP email recipient is invalid.>
E, [2024-02-26T16:04:35.616765#1767479-142140] ERROR -- : The PGP email recipient is invalid. (SecureMailing::PGP::Tool::Error::InvalidRecipient)

E, [2024-02-26T16:04:35.684135#1767479-142140] ERROR -- : Can't use Channel::Driver::Smtp: #<SecureMailing::PGP::Tool::Error::InvalidRecipient: The PGP email recipient is invalid.>
```

### Expected behaviour

The message should be encrypted and sent without any issues, since the uid for the chosen email address is valid. The message should not be encrypted for different uids, especially not revoked ones.

### Steps to reproduce the behaviour

Create a PGP key with two different `uid`s (email addresses) and revoke one of them. Send an encrypted email to the non-revoked uid and wait for a few minutes for the sending to fail, because Zammad retries to send a few times.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
* implement revoked handling for PGP
* clarify why all UIDs (Email addresses) of any recipient PGP key are used and not only the article provided one
