### ISSUE TITLE
Indexing of attachments fails with S3 storage

### ISSUE THREAD

**Issue by Camilo-Lozano** [zammad/zammad#5070]
### Used Zammad Version

6.2

### Environment

- Installation method: source
- Operating system : Debian 12
- Database + version: Postgresql 16
- Elasticsearch version: 7.17.17
- Browser + version: Chrome 120.0.6099.129

### Actual behaviour

I have set S3 as the default file system and I tried to create a ticket with an attachment, the ticket was created without any problem but when I try to search for it in the search bar it does not appear.

After trying several tickets I realized that tickets with attachments were not indexed in Elasticsearch.

### Expected behaviour

All tickets should be indexed regardless of the file system.

### Steps to reproduce the behaviour

Set S3 as default file system

Create a new ticket with an attachment (pdf preferably)

search for the ticket name in the search bar.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Camilo-Lozano** [comment]
After looking for the problem, I realized that the error comes from the method :
search_index_attribute_lookup_file_oversized

more specifically from the line
`attachment.content.blank?
`

and this gives me the following error :

**invalid byte sequence in UTF-8**

The problem here is that the content of my attachment is not of type UTF-8 but of type ASCII-8BIT (because it is the content of an attachment).

To solve this I had to go to the s3.rb file and modify the get method, since the `object.body.read ` returns a String in UTF-8 format.
I then changed this to the following :
`StringIO.new(object.body.read, 'rb').read
`

This will give me the content of the file in ASCII-8BIT format.

**Comment by tschaefer** [comment]
Hi @Camilo-Lozano,

thank you for the report. Could you please add the missing environmental information?

I suspect your patch is only a workaround and this code place is not the reason why the attachment is not indexed. We'll investigate further.

**Comment by Camilo-Lozano** [comment]
Hi, thank you for your reply   @tschaefer

here are the informations of my environment :

Installation method: source
Operating system : Debian 12
Database + version:  Postgresql 16
Elasticsearch version: 7.17.17
Browser + version: Chrome 120.0.6099.129

**Comment by ghost** [comment]
We can confirm the same issue. We started receiving alerts shortly after migrating all of our attachments from the database to S3 (and set S3 as the default storage for new attachments).

- File storage: S3
- Environment: Kubernetes ([zammad/zammad](https://artifacthub.io/packages/helm/zammad/zammad)@10.3.1)
- Zammad Version: 6.2.0
- ElasticSearch: Enabled

Monitoring:
```
Failed to run background job #1 'SearchIndexAssociationsJob' 4 time(s) with 40 attempt(s).
Failed to run background job #2 'SearchIndexJob' 4 time(s) with 40 attempt(s).
```

Log (truncated):
```
E, [2024-03-01T08:06:35.865892#4624-6760] ERROR -- : Unable to send Ticket.find(1).search_index_update_backend backend: #<ArgumentError: invalid byte sequence in UTF-8>
E, [2024-03-01T08:06:51.442231#4624-6760] ERROR -- : Unable to send Ticket.find(2).search_index_update_backend backend: #<ArgumentError: invalid byte sequence in UTF-8>
E, [2024-03-01T08:07:10.686124#4624-6760] ERROR -- : Unable to send Ticket.find(3).search_index_update_backend backend: #<ArgumentError: invalid byte sequence in UTF-8>
E, [2024-03-01T08:07:26.156833#4624-6760] ERROR -- : Unable to send Ticket.find(4).search_index_update_backend backend: #<ArgumentError: invalid byte sequence in UTF-8>
E, [2024-03-01T08:07:44.163479#4624-6760] ERROR -- : Unable to send Ticket.find(5).search_index_update_backend backend: #<ArgumentError: invalid byte sequence in UTF-8>
```

**Comment by tschaefer** [comment]
@Camilo-Lozano You have been on the right track. The S3 object body is a `StringIO`. A simple read converts the data to a UTF-8 string. Running the read in binary mode preserves the encoding. A fix is in the pipeline.
