### ISSUE TITLE
Text alignment in fields when using LanguageTool extension

### ISSUE THREAD

**Issue by Prodeguerriero** [zammad/zammad#5073]
### Used Zammad Version

6.2.0-1709189301.4a2dd7d0.jammy

### Environment

- Installation method: .deb package
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu Server 22.04 LTS
- Database + version:  postgresql 14.11
- Elasticsearch version: 7.17.18
- Browser + version: Firefox 122.0.1, Chrome 122.0.6261.69

### Actual behaviour

When using the LanguageTool extension, every text field in Zammad has a small issue with rendering the first line/paragraph of text. The lines are slightly indented to the right. See below.

![Screenshot_2024-02-29_12-09](https://github.com/zammad/zammad/assets/15149858/63567890-e24f-4770-b2e6-61f14cc24183)

### Expected behaviour

The text should all be aligned properly. See below:
![Screenshot_2024-02-29_12-09_1](https://github.com/zammad/zammad/assets/15149858/e8fe7590-2df2-4f19-8d1c-e692c7027d67)

### Steps to reproduce the behaviour

1. Install the LanguageTool extension in your browser (Chrome or Firefox)
2. Make sure it is enabled and working
3. Start typing inside any text field in Zammad

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
https://github.com/zammad/zammad/blob/stable/app/assets/stylesheets/zammad.scss#L546 is faulty for this. The extension adds a hidden HTML tag having `contenteditable` attribute set.
