### ISSUE TITLE
Bad quote parsing in reply

### ISSUE THREAD

**Issue by sachaz** [zammad/zammad#5074]
### Used Zammad Version

6.2

### Environment

- Installation method: Debian package
- Operating system : Debian GNU/Linux 12 (bookworm)
- Database + version:  postgresql  15.6-0+deb12u1
- Elasticsearch version: 7.17.18

### Actual behaviour

There reply is not doing well the job, it's not getting first ">"

Here is an exemple,

- message source:
`< /dev/data/snapshot ssh hybris cat \> /dev/data/nouveau-lvs`

- message reply:
`> > /dev/data/nouveau-lvs`

### Expected behaviour

message should be:
`>> < /dev/data/snapshot ssh hybris cat \> /dev/data/nouveau-lvs`

### Steps to reproduce the behaviour

send the example message 

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by Bozo0511** [comment]
I was not able to recreate the issue in the last stable Zammad version.
Can you please update to the latest Zammad version and check if you can recreate the issue?

**Comment by sachaz** [comment]
Hello,
same for me I close this issue,
thanks
