### ISSUE TITLE
Duplicates in calendar

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5076]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Public holidays are displayed/impoted twice on consecutive days in the calendar.

### Expected behaviour

Public holidays are imported only once in the calendar.

### Steps to reproduce the behaviour

Make changes to a calendar, so the ical-feed is freshly imported. All kind of instances are effected, stable/develop. I even saw a 6.1-instance with that problem:
![image](https://github.com/zammad/zammad/assets/97293098/970ff2bf-6786-4c9d-8c7b-4f29464fb88d)

There is also a community post about it:
https://community.zammad.org/t/duplicate-calendar-events/13229

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by martini** [comment]
@fliebe92 @tschaefer Question: After upgrading to fixed Zammad version, is there still a manual cleanup the holiday list by my own needed? Or is the Zammad upgrade fixing the duplicate entries automatically?

**Comment by fliebe92** [comment]
> @fliebe92 @tschaefer Question: After upgrading to fixed Zammad version, is there still a manual cleanup the holiday list by my own needed? Or is the Zammad upgrade fixing the duplicate entries automatically?

`Calendar.sync` is executed each day, so it should fix itself after some time.
