### ISSUE TITLE
Admin - "Berichts-Profile" - doesn't save more than 6 specific users

### ISSUE THREAD

**Issue by K-4000** [zammad/zammad#5077]
### Used Zammad Version

6.0

### Environment

- Browser + version: Firefox 123.0.1

### Actual behaviour

I want to create a "Berichts-Profil" that only shows tickets created by 10 specific users (and another "Berichts-Profil" for the opposite). I can enter 10 specific users, but when I reopen the "Berichts-Profil" in admin mode few days later it shows only 6 specific users. 

### Expected behaviour

I want to create a "Berichts-Profil" that only shows tickets created by 10 specific users (and another "Berichts-Profil" for the opposite). I can enter 10 specific users - and when I reopen the "Berichts-Profil" in admin mode few days later it still shows those 10 specific users. 

### Steps to reproduce the behaviour

1. Go to setttings -> Berichts-Profile -> add new (or change existing)
2. Add filters "Kunde" "ist" "spezifischer User"
3. Enter several User (more than 6)
4. Save and close
5. Reopen that "Berichts-Profil" several days later: There user-entries have changed..

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Kindly ensure that this also occurs on a current stable version. Zammad 6.0 is behind.

**Comment by mgruner** [comment]
@K-4000 please update to the latest version of Zammad (6.3.1) and let us know if the problem still persists. I'll close this report now, please feel free to provide more information that allow us to reproduce it on a supported version.
