### ISSUE TITLE
TLS verification does ignore timeouts and also runs if deactivated

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#5079]
### Used Zammad Version

6.2

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

The login page does take 4 seconds to load because there is an open timeout for the TLS verification check.

```
=> #<UserAgent::Result:0x00007ffaa11a7f90
 @body=nil,
 @code=0,
 @content_type=nil,
 @data=nil,
 @error="#<Net::OpenTimeout: Failed to open TCP connection to www.xxx.com:443 (execution expired)>",
 @header=nil,
 @success=false>
```

https://github.com/zammad/zammad/blob/0c7e8b6ddb67585433dc8cb5886d5185c6d1ced2/lib/omni_auth/strategies/saml_database.rb#L65

### Expected behaviour

If you have the setting `auth_saml` set to false, it should not run any of this code.

If a timeout happens for the target url then it should write an error the log.

### Steps to reproduce the behaviour

Add an idp_sso_target_url which runs into a open timeout.

### Support Ticket

Ticket#10152308

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
* Dropped TLS verification in Omniauth SAML provider
* Improved TLS verification check while setting validation

In general, all OmniAuth providers get initialized during the Zammad (Rails) initialization phase. Any enable setting (e,g, `auth_saml`) is ignored.

https://github.com/zammad/zammad/blob/develop/config/initializers/omniauth.rb

**Comment by tschaefer** [comment]
Follow-up https://github.com/zammad/coordination-technical-debt/issues/472
