### ISSUE TITLE
KB - add "copy url" button besides "preview" button

### ISSUE THREAD

**Issue by wucherpfennig** [zammad/zammad#5086]
### Used Zammad Version

6.2

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian

### Actual behaviour

there is no "copy url" button. hence agents use the "preview" button. but with this preview you might expose internals to the public if you do not pay attention.

### Expected behaviour

have a "copy button"

![grafik](https://github.com/zammad/zammad/assets/3634653/4bf15384-ae3a-4be1-8e04-fba543fccf48)

### Steps to reproduce the behaviour

1. use the preview link to send to some customer
2. he will see all the internals

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.
