### ISSUE TITLE
Create ticket from user page

### ISSUE THREAD

**Issue by TeaMoe** [zammad/zammad#509]
I would like to have a "create ticket" link on the user page. What is the best and easiest way to implement it? The new ticket should have prefilled the user/customer.

**Comment by monotek** [comment]
Imho just link users mail address to #ticket/create

**Comment by TeaMoe** [comment]
Yes, but i want to have the Customer prefilled.
Something like #ticket/create?user_id=3 does not work.

**Comment by monotek** [comment]
@martini 
Whats the url to open a new ticket with filled in customer email?

**Comment by TeaMoe** [comment]
Added a url to agent_ticket_create.coffee and passed the id to the render-method.
works for me.

**Comment by martini** [comment]
@TeaMoe Thanks for the pull request/implementation. It's in develop now.
