### ISSUE TITLE
Trigger doesn’t send a mail as an action if the recipient mail address has the word „root“ directly before the at (@) sign

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5092]
### Used Zammad Version

6.2.0.2f35239d5.saas 

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Example:

If I set up a trigger to send a message as action to the customer when a ticket is changed, but there is the word root directly before the at (@) sign in the recipient mail, no message is sent by the trigger.

The trigger itself is executed, but the message is not sent. For example, if I make a note on the ticket as trigger action instead of sending a mail, everything works fine. It is also possible to reply directly to the ticket, a mail will be sent here.

![Bildschirmfoto 2024-03-21 um 09 10 43](https://github.com/zammad/zammad/assets/129729908/c7f397e0-90d4-4ab7-8592-e0ed8c7fe6ae)

Examples for mail addresses

BeforeATroot@domain.de => mail is **not** sent
groot@domain.de => mail is **not** sent

rooti@domain.de => mail is sent

### Expected behaviour

The trigger also sends mails to recipient mail addresses where root is directly before the at (@) sign

### Steps to reproduce the behaviour

- Create a trigger like above
- Create user with email like groot@domain.com
- Create a ticket as the previous created user
- Add a note as an agent to the ticket

### Support Ticket

Ticket#10152731

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by martini** [comment]
IMO this is a feature, it's because of this setting: https://github.com/zammad/zammad/blob/develop/db/seeds/settings.rb#L3336

Fast solution: You can remove `root` from this setting.

**Comment by fliebe92** [comment]
As @martini mentioned, this is no bug, it's by design, and you just need to adjust the setting.

**Comment by MarkusHeld** [comment]
ok, i didn't know that. thanks

**Comment by fliebe92** [comment]
@MarkusHeld If you would like to enable names with `root` in it, but still have this feature active, you could use the following regular expression in the aforementioned setting: `^(mailer-daemon|postmaster|abuse|root|noreply|noreply.+?|no-reply|no-reply.+?)@.+?`
