### ISSUE TITLE
SAML certificate & key validation fails

### ISSUE THREAD

**Issue by svenseeberg** [zammad/zammad#5093]
### Used Zammad Version

6.2.0-1710415722.ca3a5152.bookworm

### Environment

- Installation method: package
- Operating system: Debian Bookworm (12)
- Database + version:  PSQL15+248
- Elasticsearch version: 7.17.18
- Browser + version: All

### Actual behaviour

When configuring SAML authentication by following https://admin-docs.zammad.org/en/latest/settings/security/third-party/saml.html, Zammad does not allow the import of a key pair generated by Keycloak (or any other frequent method I'm aware of).

When importing a certificate & key directly from Keycloak after using "Regenerate" for a Client key, Zammad fails with the response message

```json
{"error":"Could not parse PKey","error_human":"Could not parse PKey"}
```

This is true with and without adding the `-----BEGIN PRIVATE KEY-----` header and footer.

Next I tried to generate a key pair with `openssl`:

```bash
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout privateKey.key -out certificate.crt
```

Using this key pair fails with

```json
{"error":"The certificate is not usable due to being a CA certificate.","error_human":"The certificate is not usable due to being a CA certificate."}
```

### Expected behaviour

Either the documentation should be more specific about the intricacies of the key pair that Zammad requires (document parameters for openssl to generate a valid key pair) or accept the key and certificate generated by Keycloak.

(I have not yet found a set of parameters that works.)

### Steps to reproduce the behaviour

Follow https://admin-docs.zammad.org/en/latest/settings/security/third-party/saml.html with Keycloak 23.

### I'm sure this is a bug and no feature request or a general question.

Probably at least a documentation bug ;-)

**Comment by tschaefer** [comment]
Hi @svenseeberg,

1) Zammad expects any crypto asset (certificate, key) to be in PEM format including the relevant begin and end delimiters.
2) The generated key from Keycloak seems to be broken. No algorithm (RSA/EC) is found by OpenSSL.
3) The certificates for SAML signing/encrypting must not be suitable as CA and key usage must be suitable for digital signature and key encipherment.

```
$  openssl x509 -in saml.pem -noout -text | grep -A10 "X509v3 extensions:"
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage:
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Key Identifier:
                63:BD:06:5F:4D:EE:7E:91:53:9A:35:FB:81:AA:73:81:38:19:16:2E
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        63:4d:06:e2:68:73:b5:f7:90:52:e3:59:e6:05:58:64:ca:42:
        7e:1e:6b:17:d0:12:ab:a4:e8:30:65:e8:7e:0c:27:b1:bb:5f:
```

We will add the missing information into our documentation.

For generating the expected crypto assets, you might follow the instructions found [here](https://www.golinuxcloud.com/add-x509-extensions-to-certificate-openssl/).

Thank you.

**Comment by svenseeberg** [comment]
The following command generates a key pair that can be used by Zammad and Keycloak:
```
openssl req -addext basicConstraints=CA:FALSE -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout privateKey.key -out certificate.crt
```
