### ISSUE TITLE
State of Spine MVC

### ISSUE THREAD

**Issue by corny** [zammad/zammad#510]
We took a deeper look into the views and JavaScript code of Zammad. The used MVC framework [Spine](https://github.com/spine/spine) does not seem to be maintained actively for the last 1.5 years:
* https://github.com/spine/spine/issues - open issues mostly from 2011-2014
* http://spinejs.com for "documentation, usage, and examples" is offline
* https://spine.github.io/ is just a single page with broken links

Do you have any documentation to provide to contributors? Are there any plans to migrate to a better maintained framework for the UI? http://todomvc.com/ could give an orientation.

**Comment by hanneshal** [comment]
We are evaluating other frameworks, but right now we won't change it. The effort to switch is rather high, so we need to dig deep here. 

We plan to extend our documentation for developers. If you have any other questions / suggestions feel free to contact info@zammad.com to get in touch.
