### ISSUE TITLE
Fetching LdapSource for unknown users fails

### ISSUE THREAD

**Issue by infeix** [zammad/zammad#5101]
### Used Zammad Version

6.2.0-1711349647.bc0c70d0.focal

### Environment

- Installation method: [e.g. source, package]
package

- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
postgresql 9.4

- Elasticsearch version: [e.g. 7.17]
elasticsearch/stable,now 7.17.18 amd64

### Actual behaviour

ERROR in production.log:

I, [2024-03-27T11:23:54.692386#997-142260]  INFO -- : Skipping. Found an existing user for login 'woholi' synced by LDAP.
E, [2024-03-27T11:23:54.922850#997-142260] ERROR -- : ImportJob 'Import::Exchange' failed: undefined method `source' for nil:NilClass

    return if !%r{^Ldap::(\d+)$}.match?(user.source)
                                            ^^^^^^^
E, [2024-03-27T11:23:54.922940#997-142260] ERROR -- : undefined method `source' for nil:NilClass

    return if !%r{^Ldap::(\d+)$}.match?(user.source)
                                            ^^^^^^^ (NoMethodError)
app/models/ldap_source.rb:13:in `by_user'
lib/sequencer/unit/import/common/user/skip/is_ldap_source.rb:14:in `process'
lib/sequencer/unit/import/common/model/mixin/skip/action.rb:42:in `process'
lib/sequencer/unit/base.rb:247:in `process'
lib/sequencer.rb:76:in `block (4 levels) in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:75:in `block (3 levels) in process'
lib/sequencer/state.rb:151:in `process'
lib/sequencer.rb:73:in `block (2 levels) in process'
lib/sequencer/units.rb:27:in `block in each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer.rb:71:in `each_with_index'
lib/sequencer.rb:71:in `block in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:69:in `process'
lib/sequencer.rb:24:in `process'
lib/sequencer/unit/import/common/sub_sequence/mixin/base.rb:26:in `sequence_resource'
lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:48:in `block in process_folders'
lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:46:in `each'
lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:46:in `process_folders'
lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:41:in `block in paginated_item_sequence'
lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:27:in `paginated_item_sequence'
lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:14:in `block in process'
lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:12:in `each'
lib/sequencer/unit/import/exchange/folder_contacts/sub_sequence.rb:12:in `process'
lib/sequencer/unit/base.rb:247:in `process'
lib/sequencer.rb:76:in `block (4 levels) in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:75:in `block (3 levels) in process'
lib/sequencer/state.rb:151:in `process'
lib/sequencer.rb:73:in `block (2 levels) in process'
lib/sequencer/units.rb:27:in `block in each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer/units.rb:26:in `each'
lib/sequencer.rb:71:in `each_with_index'
lib/sequencer.rb:71:in `block in process'
lib/mixin/start_finish_logger.rb:9:in `log_start_finish'
lib/sequencer.rb:69:in `process'
lib/sequencer.rb:24:in `process'
lib/import/mixin/sequence.rb:17:in `process'
lib/import/integration_base.rb:94:in `start'
app/models/import_job.rb:26:in `start'
app/jobs/async_import_job.rb:11:in `perform'
lib/background_services/service/process_delayed_jobs.rb:25:in `block (2 levels) in launch'
lib/background_services/service/process_delayed_jobs.rb:23:in `block in launch'
lib/background_services/service/process_delayed_jobs.rb:20:in `loop'
lib/background_services/service/process_delayed_jobs.rb:20:in `launch'
lib/background_services/service.rb:27:in `block in run'
lib/application_handle_info.rb:19:in `use'
lib/background_services/service.rb:33:in `block in run_in_service_context'
lib/background_services/service.rb:32:in `run_in_service_context'
lib/background_services/service.rb:26:in `run'
lib/background_services.rb:67:in `block in start_as_thread'

![image](https://github.com/zammad/zammad/assets/2143069/e42de913-9a24-4e2e-8063-81e401d64f4e)

### Expected behaviour

No Error during Exchange integration.

### Steps to reproduce the behaviour

1.) You need a LDAP Integration.
2.) You need to add a Exchange integration.
 * It happens when it is importing users that are already existing (imported from LDAP)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by infeix** [comment]
It fails when it wants to skip the user.

**Comment by MrGeneration** [comment]
> postgresql 9.4

Are you absolutely sure?
The default postgresql version of Ubuntu 20 is 12.

**Comment by infeix** [comment]
sorry I am not sure.
![image](https://github.com/zammad/zammad/assets/2143069/6ceaab85-49d8-424e-9de8-f9ec1207110e)
Can you tell me?
May it iss the gcc 9.4

**Comment by MrGeneration** [comment]
![image](https://github.com/zammad/zammad/assets/6549061/04987ab8-d870-4927-9cec-362e7094ddb8)

That's the postgresql version

**Comment by infeix** [comment]
Sorry for any inconvenience. It is the first time me contributing to an open source project.

**Comment by MrGeneration** [comment]
> Sorry for any inconvenience. It is the first time me contributing to an open source project.

No problem at all. I just wanted to rule out issues with your database.

**Comment by infeix** [comment]
Can I help somehow to verify the issue?

**Comment by fliebe92** [comment]
Reproducible by executing `LdapSource.by_user(nil)`.
