### ISSUE TITLE
Time Accounting not working

### ISSUE THREAD

**Issue by Dark-Schnitzel** [zammad/zammad#5103]
### Used Zammad Version

6.2.0-1711098783.6cce5473.jammy

### Environment

- Installation method: package
- Operating system: Ubuntu 22.04.4
- Database + version:  psql (PostgreSQL) 14.11 (Ubuntu 14.11-0ubuntu0.22.04.1)
- Elasticsearch version: 7.17.18
- Browser + version: Chrome 122.0.6261.128

### Actual behaviour

After turining Time Accounting on:
Time accounting Popup is not shown on Desktop in Chrome, no time accounting info on the customer, cant track time.

### Expected behaviour

Use the timetracking feature as usual.

### Steps to reproduce the behaviour

This is a quite new Installation, initially installed 6.2.0-1710502706.2f35239d.jammy for setting up the Server.  Turned timetracking on after Configuring mail and a few test tickets and i cant use it anymore. Turning off and on changes nothing.
i can verify via console that the setting is there:
`[1] pry(main)> Setting.get('time_accounting')
=> true
`

Turning off via Web also registers:
`[2] pry(main)> Setting.get('time_accounting')
=> false
`

Also tried setting it via console:
`[5] pry(main)> Setting.set('time_accounting',true)
Setting.set('time_accounting', true)
=> true
[6] pry(main)> Setting.get('time_accounting')
=> true
`

But in the Web its turned off and time tracking not working, after enabling this in the web it also isnt working despite the output  This seems not to work as expected and i would like to help to debug this but zammad and rake is quite new for me.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @Dark-Schnitzel. Could you please post what is configured in your Zammad UI in `Time Accounting`?

See here:

![image](https://github.com/zammad/zammad/assets/8327427/c954a9ef-6332-4eb9-805d-1f777c7370c4)

**Comment by Dark-Schnitzel** [comment]
Of Course,
this my Setting there, also the time field is missing on the ticket itself.
![Bildschirmfoto 2024-03-28 um 08 45 56](https://github.com/zammad/zammad/assets/22290957/ec414203-2fe9-4d7f-a6be-9e8bd1ec92db)
![Bildschirmfoto 2024-03-28 um 08 46 42](https://github.com/zammad/zammad/assets/22290957/f8e94120-2286-479c-9f3e-8f083fea2aed)

**Comment by fliebe92** [comment]
There will be no `time` field on the ticket itself.

Please try to reset your settings:

* `Setting.reset('time_accounting')`
* `Setting.reset('time_accounting_selector')`

Then reconfigure it using the [official doc](https://admin-docs.zammad.org/en/latest/manage/time-accounting.html).

**Comment by Dark-Schnitzel** [comment]
After resetting these Values nothing had changed, but after disabling and enabling in the Webinterface the popup is finally there. I set the time unit to hours and now i got no popup again, same as before.

Resetted another 2 times, 1 with tiemtracking disabled and 1 with timetracking enabled in GUI, both with unit hours. No Popup.
3rd attempt, disabled hours as unit, popup is there. Seems that selecting hours than is not working, i tried to set this to no unit before a few times but it seems that the reset helped.

**Comment by fliebe92** [comment]
For me, it's working fine. What's the output of `Setting.get('time_accounting_selector')`?

**Comment by Dark-Schnitzel** [comment]
Ouput now with no unit is 
`[1] pry(main)> Setting.get('time_accounting_selector')
=> {}`

With hours not working:
`[2] pry(main)> Setting.get('time_accounting_selector')
=> {"condition"=>{"ticket.state_id"=>{"operator"=>"is", "value"=>[]}}}`

**Comment by Dark-Schnitzel** [comment]
After resetting time_accounting_selector popup is showing again.

**Comment by fliebe92** [comment]
Please read the documentation carefully. Your configuration is wrong, it's not related to show `hours` or not...

**Comment by Dark-Schnitzel** [comment]
After enabling hours now it shows the popup with hours, i dont get what you mean by misconfigured, i enabled this via Web after setting up the Instance and dived deeper in the console as it had not been working correctly

**Comment by fliebe92** [comment]
Your `time_accounting_selector` is/was wrongly configured. You have to select one or more conditions that need to match for the time accounting popup to be shown. This is why I was pointing you to the documentation.

**Comment by Dark-Schnitzel** [comment]
Weird havent touched the  time accounting selector or the States on which this works on, its default.
After Reloading the Browser the Popup is missing now, before reloading everything worked.

value is still
`[5] pry(main)> Setting.get('time_accounting_selector')
=> {"condition"=>{"ticket.state_id"=>{"operator"=>"is", "value"=>[]}}}`

What am i missing here?

**Comment by fliebe92** [comment]
You need to configure one or more conditions, as already mentioned. Please check [here](https://admin-docs.zammad.org/en/latest/manage/time-accounting.html#settings).

**Comment by Dark-Schnitzel** [comment]
Ah i figured it out now
you need to select the state via clicking or holding shift to mark all, just because its listed there it isnt selected...

i selected all States via shift+click and now this reflects in these Settings and work as expected now

```
[16] pry(main)> Setting.get('time_accounting_selector')
=> {"condition"=>{"ticket.state_id"=>{"operator"=>"is", "value"=>["4", "5", "1", "2", "7", "3"]}}}
```

Screenshot how its looking 
![Bildschirmfoto 2024-03-28 um 13 01 23](https://github.com/zammad/zammad/assets/22290957/2554928b-fc8e-4e1d-a863-8a8eb81714cb)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by battosai30** [comment]
Hum there is another "trick" : you need to write a message to get the popup, even if conditions are met. I don't know if it's the expected behaviour but in my mind you should be able to, for example, close a ticket without sending a response and set time spent.

**Comment by MrGeneration** [comment]
> Hum there is another "trick" : you need to write a message to get the popup, even if conditions are met. I don't know if it's the expected behaviour but in my mind you should be able to, for example, close a ticket without sending a response and set time spent.

Technical question. Works as designed, sorry.
