### ISSUE TITLE
IllegalArgumentException on reports with time range in report profile and time selection in the report UI

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5105]
### Used Zammad Version

6.2

### Environment

- Installation method: SaaS
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: 7.xx
- Browser + version: any

### Actual behaviour

Then i create a report profile wit a time range condition for example „within last(relative) 7 Month(s) and will now create a report with this profie for a time selection 2022 i get an error StatusCode: 500

![image_issue1](https://github.com/zammad/zammad/assets/129729908/7ed41318-826a-471c-8b31-2ae3e5a6dd5c)

![Bildschirmfoto 2024-04-02 um 11 11 00](https://github.com/zammad/zammad/assets/129729908/9dd3cea4-6936-455c-8eba-0bd639158072)

**production.log error**

Unable to process GET request to elasticsearch XXXX  Check the response and payload for detailed information:

Response:
#<UserAgent::Result:0x00007fe380a05a80 @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":**\"illegal_argument_exception\",\"reason\":\"[1687624163083] must be <= [1672527599999]\"}]**,\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\“:\“xxx\“,\“node\":\"TktsbBLoR-Whghv5cCzXmg\",\"reason\":{\"type\":\"illegal_argument_exception\",\"reason\":\"[1687624163083] must be <= [1672527599999]\"}}],\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"[1687624163083] must be <= [1672527599999]\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"[1687624163083] must be <= [1672527599999]\"}}},\"status\":400}", @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!", @header={"x-elastic-product"=>"Elasticsearch", "content-type"=>"application/json; charset=UTF-8", "content-length"=>"643"}>

Payload:
{"size":0,"query":{"bool":{"must":[{"range":{"created_at":{"from":"2021-12-31T23:00:00Z","to":"2022-12-31T22:59:59Z"}}},{"bool":{"must":[{"bool":{"must":[{"wildcard":{"article.subject.keyword":"*Fehlender Artikel*"}}]}},{"bool":{"must":[{"wildcard":{"article.body.keyword":"*Kundennummer*"}}]}},{"bool":{"must":[{"range":{"created_at":{"gte":"now-7M"}}}]}},{"bool":{"must_not":[{"term":{"state.name.keyword":"merged"}}]}}]}}]}},"aggs":{"time_buckets":{"date_histogram":{"field":"created_at","calendar_interval":"month","time_zone":"Europe/Berlin"}}},"sort":[{"updated_at":{"order":"desc"}},"_score"]}

Maybe this Elasticsearch Isse could be the reason for this behavior
https://github.com/elastic/elasticsearch/issues/88131

### Expected behaviour

Maybe create an empty list

### Steps to reproduce the behaviour

- create a report profile with a time selector "Created at "within last (relative) 7 Mont(s)"
- go to the reports UI and select the report with time selection "2022"

### Support Ticket

Ticket#10153025

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
Fixed for develop by 5662043c9a1904f55470b8a987c6d9127bdae8f0
