### ISSUE TITLE
SSL verification with SAML fails with valid Let's Encrypt certificates

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5106]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

I have stored a valid Let's Encrypt certificate in my Keycloak IDP

<img width="636" alt="Bildschirmfoto 2024-04-02 um 11 48 29" src="https://github.com/zammad/zammad/assets/129729908/24574fbd-3ea1-4316-90ab-d104aa74fa18">

![Bildschirmfoto 2024-04-02 um 11 33 42](https://github.com/zammad/zammad/assets/129729908/8c32b2b0-3f50-45d4-867d-c2708340c9ce)

But when I activate "SSL verification" for SAML in Zammad, I get an error message.

<img width="526" alt="Bildschirmfoto 2024-04-02 um 11 37 46" src="https://github.com/zammad/zammad/assets/129729908/bcacaab0-ab99-450a-a96e-a75ba25f599f">

E, [2024-04-02T11:38:15.609810#1126343-141960] ERROR -- : SAML: TLS verification failed for 'https://zammad.root-center.net:8443/realms/Zammad/protocol/saml': Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!
E, [2024-04-02T11:38:15.614159#1126343-141960] ERROR -- : Validation failed: The verification of the TLS connection failed. Please check the IDP certificate. (ActiveRecord::RecordInvalid)
app/controllers/application_controller/renders_models.rb:62:in `block in model_update_render'
app/controllers/application_controller/renders_models.rb:56:in `model_update_render'
app/controllers/settings_controller.rb:34:in `update'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
I, [2024-04-02T11:38:15.615793#1126343-141960]  INFO -- : Completed 422 Unprocessable Entity in 78ms (Views: 0.3ms | ActiveRecord: 11.5ms | Allocations: 13572)

**If I call the url of the IDP from the Zammad system, I get back a correct certificate**

curl   https://zammad.root-center.net:8443

* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=zammad.root-center.net
*  start date: Jan 11 07:01:07 2024 GMT
*  expire date: Apr 10 07:01:06 2024 GMT
*  subjectAltName: host "zammad.root-center.net" matched cert's "zammad.root-center.net"
*  issuer: C=US; O=Let's Encrypt; CN=R3
***  SSL certificate verify ok**. 

**Without "SSL Verification" all works as expected.**

### Expected behaviour

The "SSL Verification" in SAML works wit Let's Encrypt certificates.

### Steps to reproduce the behaviour

- store a Let's Encrypt certificate in your IDP for https://
- activate "SSL Verification" in your SAML configuration in Zammad.

### Support Ticket

Ticket#10153106

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
The TLS verification fails because Zammad (UserAgent) runs an HTTP GET request to the IDP SSO Url, here `'https://zammad.root-center.net:8443/realms/Zammad/protocol/saml`. The GET request is not allowed.

`Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>`

The TLS verification should be improved and done without any actual HTTP request. (https://github.com/jarthod/ssl-test)

**Comment by bmcgonag** [comment]
As a verification, also seeing this bug when using Authentik as the IdP with the same setup.

**Comment by SchokoShampoo** [comment]
We still have this issue. After some investigating we found out that you check for this issue with the following line:
`return nil if resp.error.starts_with?('#<Net::HTTP')` (Line 32 in the tls.rb file)
But the resp.error doesn't start with "#<Net::HTTP" It actually starts with "Client Error: #<Net::HTTP"
Therefor the error still occours.
As you can see in line 34 the part "Client Error:" is not part of the error prompt but does show up in the error message.
