### ISSUE TITLE
ghcr.io/zammad/zammad:latest points to 6.4.0-alpha instead of stable

### ISSUE THREAD

**Issue by djagoo** [zammad/zammad#5107]
### Used Zammad Version

6.4.0-alpha

### Environment

docker-compose

### Actual behaviour

https://github.com/zammad/zammad/pkgs/container/zammad/195435528?tag=latest points to an alpha release

### Expected behaviour

The documentation says:

> VERSION=latest  # all updates of stable versions, including major

### Steps to reproduce the behaviour

pull ghcr.io/zammad/zammad:latest

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by mgruner** [comment]
Fixed by 64a3de990a4d65ab867d898beac41738c4a757e0 for future builds. I will also make sure the latest tag gets updated to stable again.
