### ISSUE TITLE
Special characters in a ticket title are escaped if the title is updated by a Trigger

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#5108]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

I created a trigger to edit the title of incoming emails with help of the following variables.
#{ticket.organization.name} 
#{ticket.title} 

the ticket title ischanged to: Joe \&amp; Bob Inc - Need help

organisation name is: Joe & Bob Inc

### Expected behaviour

I created a trigger to edit the title of incoming emails with help of the following variables.
#{ticket.organization.name} 
#{ticket.title} 

I would expect that the organization name is shown like written in Organization. example: Joe & Bob Inc

### Steps to reproduce the behaviour

1.Create Trigger:
Action > is > created
status > is not > closed
Typ > is > email
sender > is not > system
title > contains not > #{ticket.organization.name} 

makes following changes:
title > #{ticket.organization.name} - #{ticket.title}

2 Create a ticket via email with the title: need Help

name of the Organization: Joe & Bob Inc
name of the Organization in the title: Joe &amp; Bob Inc - Need help

[Screen Recording (02.04.2024 15-21-16).wmv.zip](https://github.com/zammad/zammad/files/14837235/Screen.Recording.02.04.2024.15-21-16.wmv.zip)

### Support Ticket

Ticket#10153203

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mantas** [comment]
This is a very interesting issue. The new data is escaped (see https://github.com/zammad/zammad/blob/f7fde26feaf3f96768f92fc3c3f3daf6f7f67c9b/app/models/concerns/perform_changes/action/attribute_updates.rb#L123) when assigning. However, ticket title is always escaped too. This causes special characters to be double-escaped.

The solution could be to not escape the new value at the time of executing the trigger. A check to ensure that only title is not (double-)escaped may be needed though. Theoretically title is the only field that allows such value to be set (adding notes and sending email is a different mechanism). But someone may be (ab)using this feature in unexpected ways and such change may backfire.

**Comment by dominikklein** [comment]
@mantas 

> Theoretically title is the only field that allows such value to be set (adding notes and sending email is a different mechanism). But someone may be (ab)using this feature in unexpected ways and such change may backfire.

What do you mean with this?

**Comment by mantas** [comment]
@dominikklein triggers set title using `PerformChanges::Action::AttributeUpdates` which escapes resulting string (see above). While if trigger action is to add note, it uses `Ticket::PerformChanges::Action::ArticleNote` instead.

**Comment by dominikklein** [comment]
@mantas This is clear, I was confused by this part `Theoretically title is the only field that allows such value to be set`. I think placeholder variables can be used in all attributes or?
