### ISSUE TITLE
Text module with a variable  on mobile displays HTML tags

### ISSUE THREAD

**Issue by YosefAdPro** [zammad/zammad#5112]
### Used Zammad Version

6.2

### Environment

- Installation method: [e.g. source, package] package
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

When using a pre-prepared text (Text module) with a variable, it displays HTML tags
![image](https://github.com/zammad/zammad/assets/11810187/cd9d95be-4e9e-4857-943e-bee219c2a5a0)

![image](https://github.com/zammad/zammad/assets/11810187/2d62701e-e0ef-4d5e-99da-63b6301f29ae)

![image](https://github.com/zammad/zammad/assets/11810187/894b6a54-336d-482d-b264-04b6a60219e0)

### Expected behaviour

When using a pre-prepared text (Text module) with a variable that will display properly

### Steps to reproduce the behaviour

Create a Text module with a variable (in my case #{ticket.customer.firstname}).
Use it to respond to a ticket using a mobile device app

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Bozo0511** [comment]
I was not able to reproduce the issue, in my case the Variable works as designed.
![2024-04-09 11_38_57-Window](https://github.com/zammad/zammad/assets/94919964/40b7102f-adb0-4d88-ac5b-43b4ca7f05d7)

I noticed in your screenshot that the hashtag is on the right side of the Variable, can you please try to put the hashtag on the left side.
