### ISSUE TITLE
Trigger for escalation of Tickets

### ISSUE THREAD

**Issue by atietjen** [zammad/zammad#513]
I have problems with a timer, maybe its a understanding problem. I had created a new calendar, then i created a sla which filtes for new tickets in a specific group.
That works fine, I get the timer in orange letters within the tickts. In next step I was trying to create a new trigger that should filter the tickets that are new for a specific group and are escalated for 5 minutes. The trigger should set the priority on the ticket to high and add a tag to it.
I cant get it working, the only two results i can produce is that the ticket will set to priority high in the second of its creation and the second result is that nothing will happen after the ticket has been escalated.
I have tried a bit around with different settings vor and nach (relativ), innerhalb nächster and innerhalb letzer and also i tried verändert, but i didn´t got the result i want. Maybe its an understanding problem of me, so I hope anyone could help me with this?

**Comment by hanneshal** [comment]
Should work fine since 2.0.
