### ISSUE TITLE
External data source is not working in Webhooks

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5131]
### Used Zammad Version

6.3

### Environment

- Installation method: SaaS

### Actual behaviour

When using external data source in the custom payload of a webhook, "invalid method" is used instead of the value.

### Expected behaviour

When using external data source in the custom payload of a webhook, the value should be used.

### Steps to reproduce the behaviour

Create a user-attribute of the "external data source".
Create a webhook with a custom payload.
Include `#{ticket.customer.myexternaldatasourceattribute}`.

### Support Ticket

Ticket#10151613

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
https://github.com/zammad/zammad/issues/5060
