### ISSUE TITLE
Chat window is not visible 

### ISSUE THREAD

**Issue by KevinKrueger** [zammad/zammad#5140]
### Used Zammad Version

6.3.0

### Environment

- All Docker containers are running (yaml used from docker compose repo)
- Chat is on

-> runs on localhost:8080
-> Socket connection is established!

### Actual behaviour

The chat window is not visible although all the parameters required to communicate with customers are met.

### Expected behaviour

A chat window that is visible, as described in the documentation.

### Steps to reproduce the behaviour

1. Write a index.html file with the basic structure
2. Paste in the code snipped that are in the documentation
3. Run index.html

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Bozo0511** [comment]
Hi,

the chat window is not visible if there is no ready agent to take a chat.
Is there an agent Loged in and ready to take a chat?

**Comment by KevinKrueger** [comment]
One agent was ready to take a chat.

**Comment by Bozo0511** [comment]
Hi, thank you for your update, I could not replicate the issue.

The chat works fine for me. This looks like a technical problem.
If you need further assistance with the chat integration, feel free to ask in our community:
https://community.zammad.org

Or if you need a fast and specific support, here is the link to Zammad official support:
https://zammad.com/de
