### ISSUE TITLE
External data source search gets stuck when it is added as a condition or an action

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5148]
### Used Zammad Version

6.3.0-1713882094.d1107375.bullseye

### Environment

    Installation method: any
    Operating system (if you're unsure: cat /etc/os-release ): any
    Database + version: any
    Elasticsearch version: any
    Browser + version: MS Edge v.120.0.2210.121 (64-Bit)

### Actual behaviour

If I select an attribute with type "External data source field" in a trigger as an action, then it finds nothing here and searches for an eternity.

**Object:**

![Bildschirmfoto 2024-04-25 um 10 03 53](https://github.com/zammad/zammad/assets/129729908/1050d403-1fbe-461f-bf31-32ac6c1d8313)

**Trigger:**

![Bildschirmfoto 2024-04-25 um 09 59 51](https://github.com/zammad/zammad/assets/129729908/7b9074c9-2a0f-48c1-979d-ba6ae4869bb6)

Similar to this Issue:
https://github.com/zammad/zammad/issues/5006

### Expected behaviour

When using "external data source" in the action for a trigger, i can also search for entries in the "external data source" and get results as a dropdown menu like in the ticket itself to select the wanted entry.

![Bildschirmfoto 2024-04-25 um 09 39 10](https://github.com/zammad/zammad/assets/129729908/0d0d8570-1d05-426f-bf9f-04273f4ac3a9)

### Steps to reproduce the beha1viour

1. Create a custom field with an external data source type.
2. Open new Trigger (or Macro, Scheduler...) form
3. Select that custom field as a an action
4. Enter a term to search for.
5. Search is stuck, results are never returned and animation plays forever

### Support Ticket

Ticket#10154217

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Irisita** [comment]
One additional information:
This issue is not only affecting triggers. It's also happening for Macros, Schedulers, Reporting Profiles.
