### ISSUE TITLE
Overviews freeze after importing ~400 tickets

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#515]
After importing ~400 open tickets via the OTRS import the overviews freeze. No tickets are shown. The rails log shows role permission checks every second.

**Comment by martini** [comment]
Can't reproduce it with test data from vz599.demo.znuny.com.

Started import, all ok.

Login with agent was ok, browsing through the app is find. Any ideas?

**Comment by thorsteneckel** [comment]
Can't reproduce it anymore 😱  case closed.
