### ISSUE TITLE
Table width not stripped away anymore in 6.2 leads to very narrow display

### ISSUE THREAD

**Issue by lcx** [zammad/zammad#5151]
### Used Zammad Version

6.2

### Environment

- Installation method: docker
- Browser + version: [arc 124.0.6367.61 based on chromium, Firefox 125.0.2, Edge]

After upgrading to 6.2 (from 6.0) some mails display very very narrow tables. 

![CleanShot_2024-04-26_at_11 57 38](https://github.com/zammad/zammad/assets/891345/d4f9a9c3-8947-4f11-b2f9-22b6a57b8576)

removing the width: 100px will display the mail as expected. 

I checked an older mail that was received before the upgrade and that one looks fine, here the width 100px is stripped away: 
![CleanShot_2024-04-26_at_12 00 04](https://github.com/zammad/zammad/assets/891345/f368cec7-759a-48bb-81e8-7f7133dcf61e)

Checking the raw mail of the old ticket does show that the original mail did contain the same width: 100px

![CleanShot_2024-04-26_at_12 03 02](https://github.com/zammad/zammad/assets/891345/8778e109-2f97-43a1-8685-f9fabd053ef9)

which seems like 6.0 did strip away width: but 6.2 does not anymore. 
Could this commit be the reason? https://github.com/zammad/zammad/commit/f82bce4257796228691138fe1232f2c1bfe03d96

### Actual behaviour

Tables being displayed at 100px width.

### Expected behaviour

Tables being displayed full width of the ticket window. 

### Steps to reproduce the behaviour

Have not tried to reconstruct such an email but I assume that sending an email with width in tables will reproduce this issue. 

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @lcx. Zammad 6.2 is outdated, please upgrade to 6.3 and check it again.

**Comment by lcx** [comment]
I was afraid of this answer :) fair enough.

**Comment by dominikklein** [comment]
Any feedback about the problem kn 6.3?

**Comment by lcx** [comment]
Hi, just upgraded to 6.3.1 and it seems fine again. There where however some mails that where also fine before the upgrade, not sure if the sender changed something. I'm considering this fixed and will get with details if it occurs again. 
Thank you.
