### ISSUE TITLE
User login flow is interrupted when two-factor authentication method security keys is used

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad#5156]
### Used Zammad Version

6.3

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

During the login two-factor phase, the user is required to both present their security key AND verify their key, which breaks the 2FA flow and may detract from the wider usage of this method.

### Expected behaviour

Consider not asking the user to verify their security key during the login phase, as this is not recommended for the two-factor authentication use-case, only for passwordless logins ([User Presence vs User Verification](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/User_Presence_vs_User_Verification.html#_use_cases)).

This can be achieved by setting the `user_verification` flag to `'discouraged'` value in both create & get options within the [WebAuthn subsystem](https://w3c.github.io/webauthn/#enum-userVerificationRequirement).

Please note that when user verification is set to discouraged, this doesn’t mean that user verification is never performed. Sometimes the gestures simply coincide.

### Steps to reproduce the behaviour

1. Enable Security Keys two-factor authentication method.
2. Set up Security Keys method for the user.
3. Log out.
4. Try to log in again, present the security key when asked.
6. Notice how you are asked to present the key (touch to activate), verify the key (enter the PIN) and then present the key again (touch to activate).

Tested with **YubiKey 5 NFC** security key with a golden disc activation gesture + enabled PIN lock, steps may be different depending on the key type choice and their internal configuration.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Sounds like a nice and not complex change. Anything against of doing it?
