### ISSUE TITLE
Zammad broken after update

### ISSUE THREAD

**Issue by quenenni** [zammad/zammad#5159]
### Used Zammad Version

6.3.0-17

### Environment

- Installation method: debian package
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian v11.9
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]: Postgresql v13.14.0
- Elasticsearch version: [e.g. 7.17]: v8.13.2
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]: 
1. Firefox v119.0.1
2. Chromium Version 121.0.6167.139 (Build officiel) built on Debian 12.4, running on Debian 12.5 (64 bits)

### Actual behaviour

We upgraded our zammad from v5.4.1-1682687131.5ab2a47f.bullseye to v6.3.0-1714467514.a5110336.bullseye (via the Debian package manager apt) , since then, after a restart of zammad (no error at that point), when we try to access the web interface, we have this error on the web page ("500: We're sorry, but something went wrong.") and in production.log:
```
E, [2024-04-30T15:12:54.583725#1965901-112800] ERROR -- : The asset "application.css" is not present in the asset pipeline.
 (ActionView::Template::Error)
app/views/layouts/application.html.erb:9
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2024-04-30T15:12:54.589260#1965901-112800] ERROR -- : Error ID gTR1YTBB: The asset "application.css" is not present in the asset pipeline.
```

I tried several options in /opt/zammad/config/environments/production.rb, like changing the value of "config.assets.compile" from false to true, but then it complains with this error:
```
bundler: failed to load command: script/rails (script/rails)
avril 30 15:05:03 support.xxxxx.net zammad-web-1.service[1962970]: /opt/zammad/vendor/bundle/ruby/3.1.0/gems/sprockets-3.7.2/lib/sprockets/compressing.rb:63:in `js_compressor=': unknown compressor: terser (Sprockets::Error)
```

I tried to switch the option "config.assets.js_compressor" from ":terser" to ":sass", but also an error.

I went into the file "app/views/layouts/application.html.erb" and removed the line `<%= stylesheet_link_tag "application", :media => 'all' %>`, but then it complained about:
```
E, [2024-04-30T14:54:20.935690#1961379-112220] ERROR -- : The asset "ie11CustomProperties.min.js" is not present in the asset pipeline.
 (ActionView::Template::Error)
app/views/layouts/application.html.erb:11
app/views/layouts/application.html.erb:9
app/controllers/application_controller/has_download.rb:21:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:20:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:19:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
E, [2024-04-30T14:54:22.463185#1961379-112680] ERROR -- : The asset "ie11CustomProperties.min.js" is not present in the asset pipeline.
 (ActionView::Template::Error)
```

### Expected behaviour

apt upgrade -> install new version without error.

### Steps to reproduce the behaviour

We would like to fix the problem and not use a backup where we would loose tickets. So not possible at this point to reproduce the error.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@quenenni Looks really like the update process was not completed. You could try some assets precompile, but in general, I need to say this looks like a technical question.

Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
