### ISSUE TITLE
Privacy concern

### ISSUE THREAD

**Issue by dmke** [zammad/zammad#516]
Hey there,

while informally reviewing the code base I've noticed an issue with the avatar generator (`lib/service/image/zammad.rb`), which submits our customer's email addresses to https://images.zammad.com (formerly bigdata.zammad.com, 8de6726 :open_mouth:).

This makes operation in Germany difficult, as the [BDSG, § 28](https://dejure.org/gesetze/BDSG/28.html) requires us to keep our users informed about this data exchange and keep track about which data is submitted to third parties.

This leads me to thw following questions:

- What information is stored exactly on images.zammad.com, and for how long?
- Which other parts of the system do leak data?

Thanks,
Dominik

PS. I've found the "System → Services → Image Service" setting to disable the image service.

**Comment by monotek** [comment]
Maybe image service should be disabled by default.

**Comment by martini** [comment]
Hi @dmke 

## What information is stored exactly on images.zammad.com, and for how long?

 -> We use images.zammad.com to serve user avatars (based on email address fetched from e. g. gravatar) and organization logo (based on domain used for Zammad login page after initial admin account creation).

  - images.zammad.com is only a proxy for images
  - md5 sums of email addresses are used to cache images for 7 days
  - md5 sums domains are used to cache images for 30 days

## Which other parts of the system do leak data?
  -> Zammad use 4 online services (which you all can enabled/disable via Admin → System → Services)

_Note: You als can create and setup your own backends/services for this, if you want._

- Image: To serve user avatars (based on email address fetched from e. g. gravatar) and organization logo (based on domain used for Zammad login page after initial admin account creation).
  - images.zammad.com is only a proxy for images
  - md5 sums of email addresses are used to cache images for 7 days
  - md5 sums domains are used to cache images for 30 days

- GeoCalendar: Zammad can handle SLAs, for SLAs calendars (timezone, working hours and vacation days are important). This GeoCalendar service is executed after initial admin account creation to automatically configure the calendar of the admin (timezone, vacation days, ...).
  - GeoIp - No information is stored or cached on geo.zammad.com

- GeoIp: Zammad has a security feature to track user sessions based on users browser and users country. So if your session or password is used (maybe stolen) on a new browser or from a different country, Zammad will inform the Agent about the new use of password/session via a new browser/country.
  - GeoIp - No information is stored or cached on geo.zammad.com

- GeoLocation: Zammad has modern features. One new feature will be a ticket overview not in a regular table, but on a map. For this map we need to know the geo location of certain items.
  - GeoLocation - Currently there is only a google maps backend to lookup geo locations

PS: Any ideas to make thins better and more private are very welcome. We focused on maximum good user experience.

PS1: The source code of this services is under:
https://github.com/zammad/zammad/tree/develop/lib/service

**Comment by monotek** [comment]
I put this in the docs:

https://docs.zammad.org/en/latest/appendix-privacy.html

**Comment by dmke** [comment]
Thank you for your response.

My primary concern is the submission of the email address to get the avatar.

We have no problem with the domain submission in `Service::Image::Zammad.organization` (not a personal datum) and the submission of the IP address for the Geo services (although debatable whether or not an IP address is a personal datum; we propably wont use the Geo services at all).

I could sleep much better, when:

- all services are disabled by default
- a short disclaimer is displayed in the settings menu, for example

  > Image Service
  > 
  > Defines the backend for user and organization image lookups.
  > Some data might be submitted to third parties, see [here] for details.

Further, instead of submitting the email address, you could submit only the md5 hash (which would eliminate my concerns ;-)).
