### ISSUE TITLE
Display Issue - empty article and missing picture when sending multiple pictures over WhatsApp to Zammad

### ISSUE THREAD

**Issue by Mirtaaa** [zammad/zammad#5163]
### Used Zammad Version

6.3

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

When I send multiple pictures at once over WhatsApp to Zammad, some of the articles in the ticket zoom appear emtpy.

![Screenshot 2024-05-07 134529](https://github.com/zammad/zammad/assets/103510339/02977b9f-f94c-4259-8375-aefd83143723)

If I refresh the tab I can "fix" the view and the pictures appear inside the articles.

### Expected behaviour

When sending multiple pictures over WhatsApp to Zammad, each picture should appear in an article without disappearing or creating emtpy articles.

### Steps to reproduce the behaviour

Send mulitple pictures at once over whatsapp to your Zammad Instance.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
The issue is related to the attachment creation: 

https://github.com/zammad/zammad/blob/33cbfa9dac418c2e785c7faa4305d18e683718e5/lib/whatsapp/webhook/message.rb#L133-L141

https://github.com/zammad/zammad/blob/33cbfa9dac418c2e785c7faa4305d18e683718e5/lib/whatsapp/retry/media.rb#L43-L51

Changes in the store do not trigger the asset pipeline and updates in the UI of the old tech stack. We need to touch the article after the attachments get created or if possible directly create the article with the attachments.

**Comment by dominikklein** [comment]
> The issue is related to the attachment creation:
> 
> https://github.com/zammad/zammad/blob/33cbfa9dac418c2e785c7faa4305d18e683718e5/lib/whatsapp/webhook/message.rb#L133-L141
> 
> https://github.com/zammad/zammad/blob/33cbfa9dac418c2e785c7faa4305d18e683718e5/lib/whatsapp/retry/media.rb#L43-L51
> 
> Changes in the store do not trigger the asset pipeline and updates in the UI of the old tech stack. We need to touch the article after the attachments get created or if possible directly create the article with the attachments.

We are doing it in the same flow also in other channels (e.g. email or telegram). What is different? Maybe from WhatsApp side, every attachment is a single incoming webhook media message.

**Comment by fliebe92** [comment]
Relates to https://github.com/zammad/zammad/issues/5164, it only happens when there is some duplicate media shown from WhatsApp.
