### ISSUE TITLE
After Znuny import in Zammad: Users without a valid email address gives an 500 error in Zammad when creating a new mail

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5166]
### Used Zammad Version

6.3

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

After an import of users from a Znuny system, where no correct mail address is stored in Znuny, e.g. “test test ”, an error message appears in Zammad when this user is searched via the To or CC field in mail creation.

![Bildschirmfoto 2024-05-08 um 11 19 56](https://github.com/zammad/zammad/assets/129729908/d7ec33dd-a8fb-456d-8fe3-cc5365e1752c)

E, [2024-05-08T08:51:25.280602#217569-148860] ERROR -- : Mail::AddressList can not parse |malcxxx miguxxl |: Only able to parse up to "malcxxx miguxx " (Mail::Field::IncompleteParseError)
app/models/channel/email_build.rb:182:in `block in recipient_line'
app/models/channel/email_build.rb:180:in `recipient_line'
app/controllers/users_controller.rb:267:in `block in search'
app/controllers/users_controller.rb:264:in `each'
app/controllers/users_controller.rb:264:in `search'
app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
I, [2024-05-08T08:51:25.283895#217569-148860]  INFO -- : Completed 500 Internal Server Error in 30ms (Views: 0.1ms | ActiveRecord: 6.8ms | Allocations: 

### Expected behaviour

That these users are not displayed to me in the search for To or CC field in mail creation.

### Steps to reproduce the behaviour

- Znuny user with unvalid mailadress
- Import in Zammad
- Create mail with such a user in TO or CC field

### Support Ticket

Ticket#10153039

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
# Hotfix

If you have already migrated your data from your znuny instance you can use this script to analyze broken users and optional remove the email from them:

1. Make a backup if you can.

2. Make sure to back up your terminal / ssh output of all future commands for future reviews/regressions.

3. Download the following script into your zammad root directory (e.g. /opt/zammad):

https://gist.github.com/rolfschmidt/072d14623b0dfd9c9158ee1858d5c364

The script has 2 modes: DRY MODE, PROD MODE. If you provide no arguments it will run in dry mode:
```
root> zammad run rails r remove_user_email_invalid.rb
```

The output can be very long. You need to review the output. It should show users with invalid email addresses:
```
User 783 (Max Mustermann) with email 'max mustermann' is invalid
```

3. If you have reviewed your output you can run the script in prod mode to remove the invalid email addresses from the users:

```
root> zammad run rails r remove_user_email_invalid.rb 1
```

**Comment by MrGeneration** [comment]
This also happens (at least in develop), if you apply a template on the new ticket dialogue, paste an email address into the customer field and then select the correct user, this error is also thrown.

The address list then suddenly contains the first name and last name.

**Comment by martini** [comment]
Got introduced here https://github.com/zammad/zammad/commit/aa1cb1395bb25f27be986d10bd4c380fd3a9071f 1 year ago.

**Comment by MrGeneration** [comment]
> Got introduced here https://github.com/zammad/zammad/commit/aa1cb1395bb25f27be986d10bd4c380fd3a9071f 1 year ago.

Which is odd because it occurs since today when using templates (after pulling to 6.3.1).
