### ISSUE TITLE
Read only Ticket attribute can not be copied properly

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#5172]
### Used Zammad Version

63

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

I created a custom Ticket attribute and can not mark it and copy it with ctr+c.
I have to mark the name of the ticket attribute and the ticket attribute beneath it to copy it. 

![2024-05-15 09_21_01-Zammad Helpdesk - #64097 - testing organisation 2 – Opera](https://github.com/zammad/zammad/assets/94919964/b8ba8e67-78cb-43c2-adf9-b5329d3505e9)

### Expected behaviour

I would expect to be able to copy the custom ticket attribute by marking the content of it, like when it is writable.

![2024-05-15 09_23_59-Zammad Helpdesk - #64097 - testing organisation 2 – Opera](https://github.com/zammad/zammad/assets/94919964/085bbbe4-11a6-4874-8498-fa7ad048324a)

### Steps to reproduce the behaviour

- Create a custom ticket attribute 
![2024-05-15 09_26_32-Zammad Helpdesk - Subscription – Opera](https://github.com/zammad/zammad/assets/94919964/bdfeb780-0ee5-4a5c-b642-8b373167efaf)

- Make it visible via core workflow, and set it to read only for one role
- Try to copy the content of the ticket attribute with the read only permissions

### Support Ticket

Ticket#10154990

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by FabianWilms** [comment]
Without knowing anything about wether this would have consequences in other places, removing this line of css would probably already fix this problem:

https://github.com/zammad/zammad/blob/74a6c120acdf294158689478e7cd0e6dc9b9da07/app/assets/stylesheets/zammad.scss#L2073
