### ISSUE TITLE
database.yml is in the wrong location for docker containers

### ISSUE THREAD

**Issue by JasperE84** [zammad/zammad#5179]
### Used Zammad Version

6.3.1

### Environment

- Installation method: docker-compose

### Actual behaviour

Scheduler container's log shows errors causing scheduled jobs to fail if using default docker-compose setup: 
`ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use.`

Runtime pool size of `5` isn't equal to value of `50` configured in default rails database.yml:
```
$ docker compose run --rm zammad-scheduler rails r "p ActiveRecord::Base.connection_pool.stat"
[+] Creating 3/0
 ✔ Container docker_zammad-zammad-memcached-1   Running                                                                                            0.0s
 ✔ Container docker_zammad-zammad-redis-1       Running                                                                                            0.0s
 ✔ Container docker_zammad-zammad-postgresql-1  Running                                                                                            0.0s
I, [2024-05-17T08:31:11.773981 #1]  INFO -- : ActionCable is using the redis instance at redis://zammad-redis:6379.
I, [2024-05-17T08:31:11.824991#1-6060]  INFO -- : Using memcached as Rails cache store.
I, [2024-05-17T08:31:11.825266#1-6060]  INFO -- : Using the Redis back end for Zammad's web socket session store.
{:size=>5, :connections=>0, :busy=>0, :dead=>0, :idle=>0, :waiting=>0, :checkout_timeout=>5.0}
```

When copying the default rails database.yml and mounting it in docker as such, problem is solved:
```
x-shared:
  zammad-service: &zammad-service
    environment: &zammad-environment
      [..snip..]
    volumes:
      - ./tempdb.yml:/opt/zammad/config/database.yml
```

I think the fix should be something like `contrib/docker/docker-entrypoint.sh` checking for existing `~/config/database.yml` symlink to `~/config/database/database.yml` and creating it if it doesnt exist. Or move `database.yml` from its subdirectory to `/config/` directly.

More info here:
https://community.zammad.org/t/scheduler-fails-with-activerecord-could-not-obtain-a-connection-from-the-pool-within-5-000-seconds-waited-5-000-seconds-all-pooled-connections-were-in-use/14320/7

### Expected behaviour

Scheduled jobs finish without problems

### Steps to reproduce the behaviour

`$ docker-compose up -d`

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by JasperE84** [comment]
So basically this function seems to be missing in docker entry point: https://github.com/zammad/zammad/blob/0a0935d943d103f0af745485af3c3126c2cfc014/contrib/packager.io/functions#L172

**Comment by Keridos** [comment]
Can confirm that this happened on our 6.3.1 deployment, too. Adding a bind mount with a correct database.yml file to /opt/zammad/config/database.yml fixes the symptoms.

**Comment by mgruner** [comment]
Please update your `.env` instead to the latest state from upstream. There is a new variable `POSTGRESQL_OPTIONS=?pool=50` which is required now.

https://github.com/zammad/zammad-docker-compose/blob/master/.env

**Comment by matbgn** [comment]
Just as info, only putting the variable `POSTGRESQL_OPTIONS=?pool=50` didn't work in our case

**Comment by trstn70** [comment]
Same here.

**Comment by mgruner** [comment]
@matbgn @trstn70 can you provide some more details?

**Comment by matbgn** [comment]
Unfortunately not, only that we ended with an ugly cron every 5 mins... such a shame I know 😞

Just for others as a temporary workaround:

````
docker compose run zammad-scheduler rails r "Channel.fetch"

**Comment by mgruner** [comment]
What's the effective pool size on the server? You can use the commandline from @JasperE84 to determine that:
`docker compose run --rm zammad-scheduler rails r "p ActiveRecord::Base.connection_pool.stat"` Did you try increasing this value?

**Comment by matbgn** [comment]
50 as expected, and that's why I find it bizarre...

![image](https://github.com/zammad/zammad/assets/13169819/f7be0f4b-9609-4b95-b3c9-2c89664b91fc)

**Comment by mgruner** [comment]
Can you try increasing the pool value via ENV variable?

**Comment by matbgn** [comment]
I already did it via .env but was concerned about the practical limit of 50 that I read on various forums. What would you consider a reasonable test. Sorry for my concern and therefore my dummy question but our Zammad instance is productive and a bit critical too.

**Comment by mgruner** [comment]
Good question. It will probably depend on your server's max connection limit. Looks like the default is 100, where a pool size of 50 might already be too high, if all connections are actually used.

It will probably not hurt to increase it in small steps like 10 at a time, and try it with that. Maybe also changing the max connections of the server might be interesting. Could be this is something we should consider for this stack.

**Comment by matbgn** [comment]
Ok, here is a final feedback

I increased the value 10 by 10 up to 100 without seeing any effect. After exploring github and the community forum I finally stumbled upon a hint that made me realise that after the initial crash our system was stuck on previous errors. 

So in the end, setting pools back to 50 and just resetting errors for a clean check under System -> Monitoring did the trick.

I will keep a close eye on whether 50 is enough in our case and increase it if necessary, noting here what level gave satisfaction if relevant for the community.

Many, many thanks @mgruner

**Comment by yogo1212** [comment]
@mgruner the release notes state that support for `POSTGRESQL_OPTIONS` was added - not that it was now required and has no reasonable default value.
everyone seems to be setting the value to 50, is there any reason against doing that by default?

**Comment by yogo1212** [comment]
or maybe refusing to start if the env var is missing?
finding out about this only during uptime after an update and an odyssey through the forums and github is pretty :hankey:

**Comment by mgruner** [comment]
> @mgruner the release notes state that support for `POSTGRESQL_OPTIONS` was added - not that it was now required and has no reasonable default value. everyone seems to be setting the value to 50, is there any reason against doing that by default?

There is a reasonable default present, and it is at `50`: https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml#L149

**Comment by yogo1212** [comment]
@mgruner thanks for your reply!

it is now a few days later and my memory is a little foggy but i'm reasonably sure that, after an update, there was no database.yml in `config/` (only the one in `config/database/`), the scheduler failed, rails reported the setting to be `5`, and all of that went away when i added the environment variable.

you wrote

> here is a new variable POSTGRESQL_OPTIONS=?pool=50 which is required now.

further up.

did i messs something up outside the setting?

**Comment by jmptbl** [comment]
> > @mgruner the release notes state that support for `POSTGRESQL_OPTIONS` was added - not that it was now required and has no reasonable default value. everyone seems to be setting the value to 50, is there any reason against doing that by default?
> 
> There is a reasonable default present, and it is at `50`: https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml#L149

FYI the default is an empty string in the Docker image: https://github.com/zammad/zammad/blob/c5d1a133fbef439de8227dae3cf899e37e8bdcb2/contrib/docker/docker-entrypoint.sh#L23

**Comment by yogo1212** [comment]
@jmptbl thanks for pointing it out!

i can't tell whether this is malice or negligence.
it's difficult with profit-oriented organizations.
they don't generally make self-hosting too easy :neutral_face:

my employer transitioned to running zammad self-hosted because of a migration that wouldn't work with the service version of zammad.
i don't expect every bug to be fixed but, until there's a clear positioning, i'm advising against going back to renting the service version.

**Comment by MrGeneration** [comment]
> i can't tell whether this is malice or negligence.
it's difficult with profit-oriented organizations.
they don't generally make self-hosting too easy 😐

Well that's a strong statement you're assuming there. Of course we need to earn money to pay our pills (you have to as well, right?), but that statement just is not true. Besides, what blocks you from a pull request to improve the state it has currently? I mean isn't this what Open Source also is about...? Giving back?

**Comment by matbgn** [comment]
I also want to state that this is a harsh statement and kindly ask evereybody to keep this thread as constructive as possible to provide a solution. 

And since in the actual world there are a lot of people criticizing, I will just take this opportunity to thank the Zammad team for the incredible work they have done so far and the open (source) mindset they have shown so far. 🙏

**Comment by JasperE84** [comment]
> I will just take this opportunity to thank the Zammad team for the incredible work they have done so far and the open (source) mindset they have shown so far. 🙏

Well said.

**Comment by yogo1212** [comment]
I'm sorry for the bad tone!
You're all right.

> Besides, what blocks you from a pull request to improve the state it has currently?

I felt particularly humbled reading this because I've also said it to others more than once.

I'm certainly not opposed to making money with free software - as I've said, we started off as paying customers.
And I'm still advocating the use of Zammad to the people I work with and to customers - despite my frustration from having to solve more than just this one hosting issue.

This issue was particularly painful because of having to debug while the live system was affected. The effect is very small and it made it past the tests prior to rolling out the update. Once the first events were handled in production, rolling back was no longer an option and having to fix the installation while tenants where experiencing automations hiccups was stressful. In my frustration, I wrongly interpreted the lack of a reaction to me (politely) pointing out there was still an issue as a "this is the way we want it".

Mea culpa!

**Comment by jsuchal** [comment]
If anybody stumbles on this error, the fix is to set ENV variable `POSTGRESQL_OPTIONS=?pool=50` since when you use docker compose (!) from zammad its set, if you just use the docker - it does not have a default value set.

**Comment by MrGeneration** [comment]
Base `docker` technically is not on our supported list.
Our documentation covers several installation paths, people might want to stick to it.

See: https://docs.zammad.org

**Comment by jsuchal** [comment]
> Base `docker` technically is not on our supported list. 

Yes, I know that's the reason I wrote it here. BTW we managed to deploy zammad with kamal if anybody is interested.

**Comment by rodinux** [comment]
I have had similar issues upgrading from 6.2.0-1 to 6.3.1 the volumes paths changed ! we have before a volume `zammad-var:/opt/zammad/var`  rails server was there and now is `/opt/zammad`, diificult to understand... 

So I have a file `/opt/zammad/config/database.yml` on the old folder mounted  and not on the new `zammad-railsserver`,  I have paste it, but it not a symslink from `config/database/database.yml` in this file is all by default

```
# this is a database config sample for zammad ready to use with a postgresql db
# copy or symlink this file to config/database.yml to use it

default: &default
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 50
  timeout: 5000
  encoding: utf8

  ##### postgresql config #####

  adapter: postgresql
  # username: zammad
  # password:

  # If the database server is not on localhost, you can set hostname and port:
  # host:
  # port:

  #### mysql config #####

  # adapter: mysql2
  # username: zammad
  # password: <Password>

  # If the database server is not on localhost, you can set hostname and port:
  # host:
  # port:

production:
  <<: *default
  database: zammad_production

development:
  <<: *default
  database: zammad_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: zammad_test
```

For my file in `/opt/zammad/config/database.yml`,  I have another POSTGRESQL_USER and POSTGRESQL_PASS

```
production:        
  adapter: postgresql
  database: zammad_production
  pool: 50
  timeout: 5000
  encoding: utf8
  username: zammad_mypersonnal
  password: zammad_mypersonnal
  host: zammad-postgresql
  port: 5432
```

Is it possible stay like this ? It seems zammad have some scripts where he wants keep default POSTGRESQL_USER and POSTGRESQL_PASS as zammad sometimes ?

Is it a problem doing like this for the files `datbases.yml` ?
