### ISSUE TITLE
Channel: Web - No group available for selection to customers, if no group is set in Admin > Channels > Web

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#5181]
### Used Zammad Version

6.3.1-1715754184.27f4405b.bookworm

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

* If you do not select a group for the creation of tickets via channel "web", as a customer you can't select a group for your ticket. 
* Admin settings (Admin > Channels > Web):
![image](https://github.com/zammad/zammad/assets/69846837/677191c4-87c7-49e2-ab80-dcbda115e2bd)

* Customer view
![image](https://github.com/zammad/zammad/assets/69846837/481f4d40-84e9-40bb-90cd-478f00980f72)

 

### Expected behaviour

* If you do not select a group for the creation of tickets via channel "web", as a customer you should be able to select from all existing groups when creating your ticket. (If no core workflow is configured to change this)

### Steps to reproduce the behaviour

* Admin > Channels > Web
* Leave "Group selection for Ticket creation" empty
* Switch to customer view
* Create new ticket (pressing the "+" button at the bottom left)
* Try to select a group for your ticket

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by YetAnotherGerrit** [comment]
I was not able to reproduce this. We fixed something similar here:
- https://github.com/zammad/zammad/issues/4266

@cautopartes can you please confirm that you are still able to reproduce that?

**Comment by cautopartes** [comment]
I am closing this issue, as it is not reproducible anymore in a current version.
