### ISSUE TITLE
Line break is removed when inserting a text module above an existing text.

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5185]
### Used Zammad Version

6.3

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ):any 
- Browser + version: Chrome, Edge, Opera

### Actual behaviour

If I insert a text module above a text, the line break is removed. The problem does not occur if the following text is the signature.

This behavior does also not occur in Firefox in my tests.

https://github.com/zammad/zammad/assets/129729908/ec52553b-4bef-4c18-8b95-a3351bf68cdd

### Expected behaviour

The line break is not removed

### Steps to reproduce the behaviour

Try it with Edge, Chrome or Opera

- Write a text in the editor
- Insert a text module one line above the text

### Support Ticket
Ticket#10155007
Ticket#10163553

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
We should also check if this problem exists also in the new editor of the desktop-view.

**Comment by rolfschmidt** [comment]
This will be fixed with the new tech stack. Can already be tested in the ticket create of the new desktop view.
