### ISSUE TITLE
Updated by information gets overwritten by handling of 'Sent' event in a WhatsApp Business ticket

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#5187]
### Used Zammad Version

develop

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

The `updated by` information of both the ticket and related article are overwritten.

### Expected behaviour

The `updated by` information is not overwritten by handling the `Sent` event.

### Steps to reproduce the behaviour

* Set up WhatsApp Business as described in the docs.
* Create a new WhatsApp Business ticket in your instance (customer needs to write to you).
* Check the `updated by` information in an overview, it's showing the customer.
* Let an agent answer to the ticket.
* Check the `updated by` information in an overview again, for a short time period, the agent name is readable, but after handling the `Sent` event, the column is just showing `-`.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
I am seeing this on all tickets in my queue, no matter who updated it and which article form has been added as last operation on our instance. It's at `6.4.x.0cb1b4fe6.saas` and I believe this community user is affected as well:

https://community.zammad.org/t/the-updated-by-field-doesnt-update-to-last-user/15319/7
