### ISSUE TITLE
After the upgrade to Zammad 6.3, a lot of translations are displayed as "modified" in the new translation dialog

### ISSUE THREAD

**Issue by martini** [zammad/zammad#5189]
### Used Zammad Version

6.4.x.152e3360c.saas

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

- After upgrading to Zammad 6.3 - go to https://host/#system/translation 
- You will see a lot of modified translation (which are note modified)

<img width="1151" alt="Screenshot 2024-05-26 at 15 01 43" src="https://github.com/zammad/zammad/assets/110226/9ae918d4-0c2f-4b1a-8a19-382adb990941">

### Expected behaviour

- After upgrading to Zammad 6.3 - go to https://host/#system/translation 
- See only real modified translation

### Steps to reproduce the behaviour

- Upgrade to Zammad 6.3
- go to https://host/#system/translation

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by martini** [comment]
Small research result:

It seems that translations that were created before (from old translation sync mechanism) the introduction of `is_synchronized_from_codebase` and `synchronized_from_translation_file` are now displayed as `modified`.

Example:

```
[21] pry(main)> Translation.where(source: 'Cc', locale: 'de-de').last
=> #<Translation:0x00007f4dfd479580
 id: 719,
 locale: "de-de",
 source: "Cc",
 target: "Cc",
 target_initial: "Cc",
 updated_by_id: 1,
 created_by_id: 1,
 created_at: Sun, 27 Sep 2015 23:31:47.000000000 UTC +00:00,
 updated_at: Sun, 27 Sep 2015 23:31:47.000000000 UTC +00:00,
 is_synchronized_from_codebase: false,
 synchronized_from_translation_file: nil>
[22] pry(main)> 
```

**Comment by dominikklein** [comment]
But it's only happening for instances which were present before the move to weblate. For strings which were no longer in the code base and which have now a wrong value inside "is_synchronized_from_codebase". Or normally should in general already be be not present.

**Comment by cautopartes** [comment]
Makes sense to me, too.
On an about four years old installation, updated to latest release:
```
[1] pry(main)> Translation.where(source: 'Cc', locale: 'de-de').last
=> #<Translation:0x00007fd7dbaee240
 id: 49592,
 locale: "de-de",
 source: "Cc",
 target: "Cc",
 target_initial: "Cc",
 updated_by_id: 1,
 created_by_id: 1,
 created_at: Tue, 20 Oct 2020 22:25:56.225000000 UTC +00:00,
 updated_at: Tue, 20 Oct 2020 22:25:56.225000000 UTC +00:00,
 is_synchronized_from_codebase: false,
 synchronized_from_translation_file: nil>
```

 On a recent installation in a VM: 
```
[1] pry(main)> Translation.where(source: 'Cc', locale: 'de-de').last
=> nil
```

**Comment by mgruner** [comment]
### Discussion 2023-06-03

The central question is: how can we distinguish strings that were leftovers of previous synchronizations from i18n.zammad.com (old codebase strings) and strings that were locally created to provide translations e.g. for custom fields, states etc.

- Idea 1: strings coming from the codebase would be present for many languages (say, > 20)
  - Query could be like: strings that are present in more than N languages, not changed by the user and older than M.
- Idea 2: if the previous does not work, we could use a list of strings from our internal support system which is one of the oldest and should have most affected strings.

Next step is a verification export by @martini which allows us to understand better the affected data.

**Comment by MrGeneration** [comment]
I do have a translation file from the last version that has used i18n if that helps.
