### ISSUE TITLE
Malformed client_id in Google OAuth

### ISSUE THREAD

**Issue by yaakovfeldman** [zammad/zammad#5195]
### Used Zammad Version

6.3.1-1716973733.929318d1.focal

### Environment

- Installation method: package
- Operating system: ubuntu 20.04
- Database + version:  
- Elasticsearch version: 
- Browser + version: recent firefox and chrome

### Actual behaviour

After adding a Google oAuth using Settings>Channels>Google>Configure App, and then clicking Add Account, I see a Google page saying 'Access blocked: authorisation error' and 'Missing required parameter: client_id' and 'Error 400: invalid_request'.

Using network tab in browser inspector I see Zammad tried to send me to `https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=489644911620-ciqbv45t6t3ooj5sdgod795p9gteko81.apps.googleusercontent.com&prompt=consent&redirect_uri=https%3A%2F%2Fsupport.kezhub.com%2Fapi%2Fv1%2Fexternal_credentials%2Fgoogle%2Fcallback&response_type=code&scope=openid+email+profile+https%3A%2F%2Fmail.google.com%2F`

This url appears malformed as it has repeated `client_id` parameters of `client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=&client_id%5B%5D=489644911620-ciqbv45t6t3ooj5sdgod795p9gteko81.apps.googleusercontent.com` which decodes to `client_id[]=&client_id[]=&client_id[]=&client_id[]=&client_id[]=&client_id[]=&client_id[]=&client_id[]=&client_id[]=489644911620-ciqbv45t6t3ooj5sdgod795p9gteko81.apps.googleusercontent.com`

I have tried editing the url in a new browser window to replace all these with a single `client_id=489644911620-ciqbv45t6t3ooj5sdgod795p9gteko81.apps.googleusercontent.com` and that seems to work (it loads the oAuth flow on Google's website) but I don't know any way to make Zammad use the correct url.

### Expected behaviour

Google OAuth screen should open.

### Steps to reproduce the behaviour

I don't know how to reproduce but I earlier had an issue where when entering the OAuth client_id and secret the dialog seemed to reload several times. Maybe it somehow saved several times and created multiple records? Or perhaps this is unrelated.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MarkusHeld** [comment]
I cannot reproduce this behavior and seems to be a problem with your local Zammad system. If you need further technical assistance I would recommend you to contact the community https://community.zammad.org/  or if you have an existing support contract to contact our support team directly.

**Comment by yaakovfeldman** [comment]
I found the `external_credentials` database table had a malformed row with the erroneous client id and another row also for google oauth with the correct client id. I deleted the malformed row directly in the database and it works fine. I have never previously accessed the database directly but it seemed the only option as the app doesn't expose this directly.

**Comment by MrGeneration** [comment]
Directly fiddling inside of Zammads database *is not* recommended at all. It might cause data inconsistencies.
