### ISSUE TITLE
Wrong customer and created_by after importing Ticket

### ISSUE THREAD

**Issue by martini** [zammad/zammad#520]
Source: vz599.demo.znuny.com

In OTRS there is a ticket without an existing customer in OTRS. In this cases after importing the customer of the ticket should be the sender of first article.

Example in OTRS:
http://vz599.demo.znuny.com/otrs/index.pl?Action=AgentTicketZoom;TicketID=540

<img width="1263" alt="screen shot 2016-12-09 at 10 42 27" src="https://cloud.githubusercontent.com/assets/110226/21044422/35be63ba-bdfc-11e6-8472-ef271afb9f11.png">

In Zammad after Import:
<img width="1362" alt="screen shot 2016-12-09 at 10 41 41" src="https://cloud.githubusercontent.com/assets/110226/21044525/b54c8ed6-bdfc-11e6-8030-d46a0f0b46f2.png">

Expected in Zammad (after Import):
<img width="1361" alt="screen shot 2016-12-09 at 10 45 41" src="https://cloud.githubusercontent.com/assets/110226/21044528/b956343c-bdfc-11e6-908b-567d27d43b59.png">

**Comment by thorsteneckel** [comment]
Thanks! Fixed with commit above. There were some strange things happening 👻
