### ISSUE TITLE
Triggers and schedulers continue to send mails, even if an inactive mailbox is used for this purpose 

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#5201]
### Used Zammad Version

6.3.1 develop

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: MS Edge v. 125.0.2535.79 (64-bit)

### Actual behaviour

By deactivating the mailbox used for receiving and sending emails, the received emails are no longer imported, but the outgoing emails are still sent, either by the agent/user themselves or by system-generated actions via trigger/scheduler. 

### Expected behaviour

By deactivating the mailbox used for receiving and sending emails, the mailbox should not import any incoming emails nor send any emails, neither those generated by agents nor those generated by the system such as triggers and schedulers. 

### Steps to reproduce the behaviour

1) Add a working mailbox to your Zammad instance
2) set the mailbox as outgoing email for a specific group
2) deactivate the mailbox in the email channel
<img width="825" alt="image" src="https://github.com/zammad/zammad/assets/101350124/b24099ff-582c-4ee4-b08e-3406478a7655">

3) create a trigger/scheduler that sends emails as an action
4) Update the ticket so that the conditions of the trigger/scheduler are met and see how the emails are sent even though the mailbox is still disabled (it is strange, however, that the incoming mails are not being imported)

### Support Ticket

Ticket#10156107

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by YetAnotherGerrit** [comment]
How was it solved?
- For agents?
  - Does the agent now receive a warning that prevent him from sending a message?
  - Is the reply-button removed?
  - Or does he get an error message after sending it?
  - Or something completely different?
- What about triggers?
  - Is there an error message in the ticket, that a trigger message was not sent?
  - Or is it put into some kind of queue and send afterwards?
  - Or something completely different?

**Comment by binsky08** [comment]
> How was it solved?
> 
>     * For agents?
>       
>       * Does the agent now receive a warning that prevent him from sending a message?
>       * Is the reply-button removed?
>       * Or does he get an error message after sending it?
>       * Or something completely different?
> 
>     * What about triggers?
>       
>       * Is there an error message in the ticket, that a trigger message was not sent?
>       * Or is it put into some kind of queue and send afterwards?
>       * Or something completely different?

I just added a condition to the previously existing mail address and channel id conditions for email notifications (https://github.com/zammad/zammad/commit/7f8b7a142be81dcd3a67d719cd9c7e223482a41d#diff-aa90e7d42c1dd0603197f111e6eecd53a7bdacd38e21c4ca2c2ae964d6d8b5d0R97). Same error handling like before, did not touch that logic. Nothing else changed.
