### ISSUE TITLE
Translation - Not translated string

### ISSUE THREAD

**Issue by AnaelMobilia** [zammad/zammad#5202]
### Used Zammad Version

6.3.1

### Environment

all

### Actual behaviour

On Admin -> Knowledge base -> delete, the string "Deleting your knowledge base requires an additional verification step. To proceed, enter its name below ("xxx"). THIS ACTION CANNOT BE UNDONE." isn't translated.

### Expected behaviour

Translated string

### Steps to reproduce the behaviour

It looks like the ["__(xxx)" method isn't called on the help attribute](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/knowledge_base/delete.coffee#L50)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
https://github.com/zammad/zammad/blob/110d60dd30379a26a76f819ddc13caf3194dec9f/app/assets/javascripts/app/views/knowledge_base/delete.coffee#L50
