### ISSUE TITLE
Translation in French - bad escaping of quote characters on one string

### ISSUE THREAD

**Issue by AnaelMobilia** [zammad/zammad#5203]
### Used Zammad Version

6.3.1

### Environment

all

### Actual behaviour

When updating the database schema (after adding attributes to an object, the "'" character isn't correctly rendered on the interface
![2024-06-05_11-31](https://github.com/zammad/zammad/assets/6187125/59de0019-a607-4c1c-aba8-54c22035e172)

### Expected behaviour

string `jusqu'à` as set in translation

### Steps to reproduce the behaviour

Other strings have previously this issue but have been addressed on https://github.com/zammad/zammad/issues/5095

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@mgruner Did we not fix this problem in general, because you aligned all places?

**Comment by mgruner** [comment]
@dominikklein this looks like a different issue, because the translation does not happen in the eco template.
