### ISSUE TITLE
Object custom attributes - Bad render on admin

### ISSUE THREAD

**Issue by AnaelMobilia** [zammad/zammad#5204]
### Used Zammad Version

6.3.1

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 12
- Database + version:  all
- Elasticsearch version: all
- Browser + version: all

### Actual behaviour

- Add an attribute "SOME_RANDOM_STRING" to the Organization Object
- Check the render on the Admin -> Object screen (`#system/object_manager`)  : OK
![image](https://github.com/zammad/zammad/assets/6187125/f4a06ad5-f29d-47f7-98eb-34dc3d4b5731)
- Check the render on the Admin -> Organization screen (`#manage/organizations`) : KO
![image](https://github.com/zammad/zammad/assets/6187125/3c86396b-971f-4c6f-bec6-953c71acbc8e)

### Expected behaviour

Display "ONE_RANDOM_STRING" without having the markdown (?) syntax rendered on field name

### Steps to reproduce the behaviour

See actual behaviour

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Similar ones (I was also thinking the same issue already exists, but didn't find something with a simple search): https://github.com/zammad/zammad/issues/4718 + https://github.com/zammad/zammad/issues/4354
