### ISSUE TITLE
Tags are not visible in the admin interface under Admin > Manage > Tags

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#5206]
### Used Zammad Version

63

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

If you have more than 1000 Tags, only the forst 1000 Tags are shown in Admin > Manage > Tags.
And you can not work on the rest.

### Expected behaviour

Expected behavior 1:
When you reach the limit of 1000 Tags, showing a notification that you reached 1000 Tags and remove old tags to create new ones.

or

Expected Behavior 2.
Have a search bar under Admin > Manage > Tags, like for the user Management, and use the search bar to limit the results.

### Steps to reproduce the behaviour

Create over 1000 Tags and try to work on the 1001 tag.

![2024-06-07 10_18_09-Zammad Helpdesk - Tags – Opera](https://github.com/zammad/zammad/assets/94919964/835de011-394c-4969-b092-11532801c23f)

![2024-06-07 10_18_35-Zammad Helpdesk - Tags – Opera](https://github.com/zammad/zammad/assets/94919964/4ee67108-826d-4de5-8a87-f15595577333)

### Support Ticket

Ticket#10156179

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mantas** [comment]
Some technical context. Tags database structure is different from Groups/Roles/etc due to the nature of this object. Well, 3 closely related objects to be precise.

`#manage/tags` is a custom table. Backend to get the list of tags does not use the generic `model_index_render` either.

All in all, it wouldn't be hard to add proper pagination, but it's not 5 minutes job :)

**Comment by dominikklein** [comment]
I would suggest to only increasing the limit for the current admin interface for now. With the Desktop-Rewrite we can add a general output for all these screens.
