### ISSUE TITLE
Attachements added when creating a new Ticket not getting sent

### ISSUE THREAD

**Issue by Fernien** [zammad/zammad#5207]
### Used Zammad Version

6.2

### Environment

- Installation method: Docker Compose
- Operating system (if you're unsure: `cat /etc/os-release` ): Docker Host: Debian 12
- Database + version:  postgres 15.6-alpine
- Elasticsearch version: 8.12.2

### Actual behaviour

When sending a new E-Mail via a new Ticket the attachements added to the message are not getting sent to the customer and are not stored in Zammad.

Before sending:
![image](https://github.com/zammad/zammad/assets/28627530/ea902265-ef84-4e23-a342-794b1d6b99c4)
After:
![image](https://github.com/zammad/zammad/assets/28627530/be7182bd-9a5e-4dbd-b954-f7cff2d3a21b)

### Expected behaviour

The attachment is shown in the ticket and sent to the customer. Equivalent to when sending attachements in an existing ticket.

### Steps to reproduce the behaviour

Create a new ticket, send an e-mail and add an attachement

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Bozo0511** [comment]
Hi I could recreate the issue in my docker compose Installation, this could be a server related limitation. Or a too large attachment.
