### ISSUE TITLE
Asset Management connector: Snipe-IT interface

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#521]
Ticket# 10396

https://snipeitapp.com/

**Comment by hanneshal** [comment]
No update within the last 40 days. 
Autoclosed.

If you want to take the discussion further please move to the community [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)

regards
Johannes
