### ISSUE TITLE
after install i get error

### ISSUE THREAD

**Issue by FN-Florian** [zammad/zammad#522]
Hi,
when i open the page in browser http://serverip:3000 then i get a error.
I don't see zammad.

**Comment by monotek** [comment]
Whats the error message?

**Comment by FN-Florian** [comment]
This is a browser error

Fehler: Verbindung unterbrochen

**Comment by monotek** [comment]
Ho did you installed zammad?

**Comment by FN-Florian** [comment]
I have use this https://zammad.org/documentation/install/install-deb

OS: debian 8 64bit

**Comment by monotek** [comment]
whats the output of the following commands:

`netstat -tulpen`
`ps faux | grep zammad`

**Comment by FN-Florian** [comment]
here the output

http://pastebin.com/a79zDvch

**Comment by monotek** [comment]
Hmm... the Zammad processes ar running but i don't see the ports 3000 and 6042 open.
Normaly you also should be able to access Zammad on port 80.
Could you please provide your production.log and zammad.log from the zammad log directory?

**Comment by FN-Florian** [comment]
Hi, only the scheduler_err.log has entrys
http://pastebin.com/EeEqtDFu

the production.log and scheduler_out.log are empty.

**Comment by monotek** [comment]
Please run contrib/packager.io/postinstall.sh

**Comment by FN-Florian** [comment]
This is the result:

root@support:/home# ./postinstall.sh
./postinstall.sh: line 5: syntax error near unexpected token `newline'
./postinstall.sh: line 5: `<!DOCTYPE html>'
root@support:/home#

**Comment by monotek** [comment]
This looks weird: <!DOCTYPE html>

Could you please paste the output of:

cat /opt/zammad/contrib/packager.io/postinstall.sh

**Comment by FN-Florian** [comment]
Hi,
i have now again run this script in /opt/zammad/contrib/packager.io/

The Result: http://pastebin.com/KKiZwKb8

Result from cat: 
http://pastebin.com/zsP16LcL

**Comment by monotek** [comment]
OK, seems there was an error while installing the first time and therefore your database was not created.

Please delete this file: /opt/zammad/config/database.yml

After this run postinstall.sh again.

**Comment by FN-Florian** [comment]
After delete this file and run postinstall.sh, i can't open zammad. 

Here the output from postinstall.sh:
http://pastebin.com/T3ybHbWG

**Comment by monotek** [comment]
I gues thats the problem:

`createdb: database creation failed: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)`

Set your system locale to en_us.utf8.

**Comment by FN-Florian** [comment]
Thanks, after reinstall the vps, change system locale to en_us.utf8 and install zammad new it's work.
