### ISSUE TITLE
Notification emails about mails sent from Exchange with inline images are displayed in a compressed long line in e-mail client

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#5222]
### Used Zammad Version

6.3.1 develop

### Environment

- Installation method: any
- Operating system: any 
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge, v. 125.0.2535.92 (Official Build) (64-Bit)

### Actual behaviour

Sending images as part of the text (not as an attachment) from Exchange/MS environment will result in Zammad displaying said image in the notification email as follows: 

Thunderbird
<img width="884" alt="image" src="https://github.com/zammad/zammad/assets/101350124/92a77322-7f53-48ec-ad9b-051c56947984">

new Outlook:
https://github.com/zammad/zammad/assets/101350124/78ec775c-3f8b-446b-b891-255301703dac

<img width="451" alt="image" src="https://github.com/zammad/zammad/assets/101350124/57ddcc16-ade6-44e9-9061-08563bd6127a">

### Expected behaviour

The image should be delivered in the Zammad notification email as it was sent in the original email. 

### Steps to reproduce the behaviour

1) Enable email notifications in the settings of your Zammad user
2) Send an image in the email body to your Zammad instance from an Exchange/MS environment
3) Zammad will deliver the newly received email, however the image will be compressed and depending on the email client used, it may (Outlook) or may not (Thunderbird) be clickable to enlarge the image. 

### Support Ticket

Ticket#10156436

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
The problem might not be exchange specific and occurs as soon Zammad stumbles upon height and width attributes in the img tag. It will overwrite them to values that break the image display (it's basically streched in width and like 3p height).

This is the image in question code wise:
```
<!-- original before Zammad touched it -->
<img width="974" height="342" style="width:10.1458in;height:3.5625in" id="Grafik_x0020_1" src="cid:image001.png@01DABCA6.50BA4A70">

<!-- what Zammad made out of it, notice height and width attributes of image tag -->
<img style="max-width:100%;width:10.1458in;max-height:3.5625in;" src="cid:image001.png@01DABCA6.50BA4A70" height="3.5625" width="10.1458">
```

**Comment by fliebe92** [comment]
Regression of https://github.com/zammad/zammad/issues/4691.
