### ISSUE TITLE
Translators can destroy the whole UI by wrong format translations

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#5223]
### Used Zammad Version

6.3

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

Javascript errors will crash the whole app.

### Expected behaviour

If the date format is invalid, then some kind of default format should be used.

### Steps to reproduce the behaviour

Compromise the translations of a language, e.g. Bulgarian:

```
msgid "FORMAT_DATE"
msgstr "дд.мм.гг"

msgid "FORMAT_DATETIME"
msgstr "дд.мм.гг ЧЧ:MM"
```

### Support Ticket

Ticket#10156534, Ticket#10159332

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
I already fixed the translations in question and pushed the change in stable translation already.
Rolf set auto merge for the PR so that the translation hopefully is okay soon.

**Comment by rolfschmidt** [comment]
@Mirtaaa this should get prioritized pls

**Comment by dominikklein** [comment]
Could maybe be done in this direction: https://github.com/zammad/zammad/commit/2ba1c9cf41daf30497c388027e949291280c5e7a

**Comment by mgruner** [comment]
My suggestion would be to move the `FORMAT_DATE` and `FORMAT_DATETIME` keys out of the translation and into the locales. They are static properties of the language / locale itself, not actual translations. This would also make it impossible to break them by modifying the records locally.

**Comment by dominikklein** [comment]
It also sounds good to me. We should only clarify if the current approach was used for special situations, only to be clear that it could be a breaking change.

@martini Do you have a use case form the past, because a customer changed this date/datetime format? I think normally it should be a no-go.

**Comment by mantas** [comment]
Once date/time formats are in `Locale`, will we allow to customize them on per-instance bases? Currently it's possible to find it in `#system/translations` and then override with the desired format.

**Comment by dominikklein** [comment]
But is there a real use case behind which we want to support?

**Comment by mantas** [comment]
Good question. People do have widely different preferences for time formats and IMO it does not hurt if we let them to be modified on per-instance basis. Vast majority (if not all) systems allow to choose time/date format. Usually even on per-profile bases. Locking it down even further does not feel right to me.

**Comment by dominikklein** [comment]
For me I see no real use to change the default number format for a locale. Make things more complex without a real benefit.

When another format in trigger mail l is needed, this is now already possible.

**Comment by mantas** [comment]
This is about what agents see in UI.

I'd agree with you if we had time format customisation in profile. Or if we picked up browser settings via `Intl` API. But without customisation in profile, I don't think locking this down even further is productive. Different people have different preferences for time formats and I think we should respect this.

**Comment by mgruner** [comment]
But then you'd need to have this configurable on user level. That would be a follow-up feature request. For now moving it to the locale to freeze it sounds fine to me.

**Comment by rolfschmidt** [comment]
A simple quick fix could also be to just catch the exception and return English format as default?

**Comment by MoritzKlasen** [comment]
In a Vanilla Zammad Version I got the same issue with Simplified Chinese. Users are blocked from working with Zammad because of JavaScript Error.

Current Default:
```
$ rails r "p Translation.where(source: 'FORMAT_DATE', locale: 'th')"
#<ActiveRecord::Relation [#<Translation id: 164127, locale: "th", source: "FORMAT_DATE", target: "รูปแบบ_วันที่", target_initial: "รูปแบบ_วันที่", is_synchronized_from_codebase: true, synchronized_from_translation_file: "i18n/zammad.th.po", updated_by_id: 1, created_by_id: 1, created_at: "2024-05-31 19:50:03.439000000 +0000", updated_at: "2024-05-31 19:50:03.439000000 +0000">]>
```

**Comment by mgruner** [comment]
We solved it now with an additional rspec test that validates the format strings with a simple regex. A future optimization by moving the strings to the locale is probably still something we should do.
