### ISSUE TITLE
SAML SSL Verification is broken

### ISSUE THREAD

**Issue by strifel** [zammad/zammad#5225]
### Used Zammad Version

6.3

### Environment

- Installation method: docker
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 12

### Actual behaviour

The SAML TLS verification seems to check things on save wrongly.

1. It does check the IDP SSO URL. That is only ever accessed by the client. This should therefore not be checked by the server.
2. It does say to check the SAML IDP-Certificate. This is wrong. The certificate does not seem to be used for the check.
3. It [does check](https://github.com/zammad/zammad/blob/develop/lib/user_agent.rb#L517-L521) redirect URIs ([that are valid](https://developer.mozilla.org/en-US/docs/web/http/headers/location)) not correctly as it does not accept relative redirect URIs.

### Expected behaviour

The SAML check passes

### Steps to reproduce the behaviour

For:

1. Enter an IDP SSO Url: Break it (for example by using Authentik that does relative redirect URIs)
2. See 1, Read error message
3. Use for example Authentik that does relative redirects.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
The check verifies the TLS connection/certificate to the SAML server. The idea of the check is to support the admin during the Zammad SAML configuration.

In practice, it is not needed for the Zammad server to reach the SAML server, as the SAML communication is handled between the user browser - any modern browser checks the TLS connection/certificate - and the SAML server. In this case, the check is "useless" and will fail with a connection error.

For the initial purpose of the check the current state is good enough.

**Comment by strifel** [comment]
Currently this button pretends to be important and should definitely checked ("Die Deaktivierung der SSL-Überprüfung stellt ein Sicherheitsrisiko dar und sollte nur vorübergehend verwendet werden. Verwenden Sie diese Option auf eigene Gefahr!"). But as it stands it randomly breaks with some IDPs (see point 3) and does not have any security effects (as you said).
When it then breaks it even gives wrong error messages (see point 2).

I do not see where this helps the admin, it only confuses them and costs them a lot of time (as it did for us).

The button text should definitely reflect that it has no security effects.
