### ISSUE TITLE
Templates are not working when Core Workflow "set fixed to" is used

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5226]
### Used Zammad Version

6.3.1-1717494961.ae2be7a4.bookworm

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian 12 WSL
- Database + version: any
- Elasticsearch version: any
- Browser + version: Chrome

### Actual behaviour

When there is a Core Workflow that limits the options of an attribute using "set fixed to", it is not possible to set a value for this attribute using templates.

### Expected behaviour

When there is a Core Workflow that limits the options of an attribute using "set fixed to", it is possible to set a value for this attribute using templates, as long as it is available in the options that have been set using "set fixed to".

### Steps to reproduce the behaviour

- Create two groups "Sales" and "Support"
- Create a new ticket object "category".
  - Remove all permissions (customer/agent)
- Create a Core Workflow that displays ("show") this attribute only when group=Sales is selected. And also use "set fixed to" to limit the available options of that category attribute.
- Create a template, that selects a valid (based on the above core workflow) combination of Group/Category.
- Apply this template on the ticket creation mask.

### Support Ticket

Ticket#10151613
Ticket#10146185

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@rolfschmidt Interesting topic or? :-D

**Comment by rolfschmidt** [comment]
This is not a bug. I try to explain the core workflow engine here. A field can have 3 states:

- remove
- hide
- show

The state **remove** for example does mean that the field gets removed from the payload and will not be set. **hide** on the other side will keep the field hidden and also respect its value.

If you create a new field in the object manager attributes and don't show the field by default it will have the state set to **remove**, which means that the field does not get rendered in the background and is not shown and also does not have a value in the rendered form.

That means if you apply a template:

1. It will apply the payload to the form. But the category field state is removed so it is not part of the form, so the value of the template will not be forwarded to core workflow.
2. The core workflow request will get the payload but without category value. So the engine will run without the value and return to show the field, but it will not know about the template state for the category field.

To make your workflow working you need to activate the field by default for the mask so it spawns with a **show** state, then hide it with an additional first core workflow and show it based on your existing core workflows.
