### ISSUE TITLE
Group selection not possible for (new) customer when creating tickets via web 

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5232]
### Used Zammad Version

6.3.1.9d65e9875.saas 

### Environment

- Installation method: SaaS
- Browser + version: any

### Actual behaviour

I have several groups set up in Zammad

![Bildschirmfoto 2024-06-20 um 10 51 45](https://github.com/zammad/zammad/assets/129729908/e1d0dbed-e3b5-4b9e-825f-88cdc61b32ae)

I don't store any groups in Channels Web, which means that all existing groups should be displayed for selection when a customer (customer role) creates a new ticket via Web.

![Bildschirmfoto 2024-06-20 um 10 35 16](https://github.com/zammad/zammad/assets/129729908/9dde9cb9-72be-48d3-b7be-6a21e6f0e42e)

However, this is currently not the case, no groups are displayed at the ticket creation for a new customer and therefore no ticket can be created.

![Bildschirmfoto 2024-06-20 um 10 36 13](https://github.com/zammad/zammad/assets/129729908/7143d893-0bbb-4102-aecc-dd34794d9c76)

Existing users who have already created a ticket in a specific group via web are shown these groups for selection in the ticket creation.

Another problem is that a Core Workflow also doesn't work then the condition is a group selection, which is not displayed 
in the ticket creation mask.

### Expected behaviour

All groups are displayed for selection when tickets are created via the web by the customer.

### Steps to reproduce the behaviour

1. Create at least two groups
2. Then go to Channel => Web and leave the select fied "Group selection for Ticket creation" blank
3. Connect as a NEW customer and try to create a ticket, no groups for selection are visible

### Support Ticket

Ticket#10156717
Ticket#10158861

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MarkusHeld** [comment]
Current workaround is 

1. Go to Channel => Web => Group selection for Ticket creation
2. Select all Groups in the select field and submit
3. Then all groups are displayed when a ticket is created by a customer via Web.

**Comment by binsky08** [comment]
Unfortunately I could not reproduce it with current develop version. Would be good if someone could confirm this again.

**Comment by dominikklein** [comment]
@MarkusHeld Can you maybe try to reproduce it again? And when yes maybe adding some more details?

**Comment by MarkusHeld** [comment]
I will try to reproduce it again in a stable and develop version and give feedback!

**Comment by MarkusHeld** [comment]
@binsky08 You're right, now I can't reproduce it in a stable (Zammad Version 6.3.1.4dc443668.saas ) and develop version either
