### ISSUE TITLE
Core Workflows not blocking users from changing customer details

### ISSUE THREAD

**Issue by antonionardella** [zammad/zammad#5236]
### Used Zammad Version

6.3.1-1718620481.9d65e987.jammy

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): ubuntu 22.04
- Database + version:  postgres 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
- Elasticsearch version: 7.10.2 amd64
- Browser + version: Firefox 127

### Actual behaviour

Agents can change `main` and `secondary organization` affiliations, `notes` and `active status` of a customer

### Expected behaviour

Have the option to avoid `Agents` from being able to modify any customer information if a core workflow is set to block it

### Steps to reproduce the behaviour

Set up a `Core Workflow` to avoid non-admins from changing or seeing information
![9774a94e74411e318bf379bdea836436606fd58e_2_690x271](https://github.com/zammad/zammad/assets/7383572/dce72468-1655-4dc9-b971-0e7586bd8185)
![7ae675679b8cb3456f00ef78bde141338ee9fa14_2_547x500](https://github.com/zammad/zammad/assets/7383572/e2a20a74-a1ee-45a6-a631-f5650d973099)
Login as (non-admin user/agent) and try to edit customer information it is still possible to add/remove the `organization`, `secondary organizations`, `notes`, `active status` of the customer as they are not in the list of fields within the `core workflow` system
![b34f2d05a7878c70d265f9dad065871813320b78_2_422x500](https://github.com/zammad/zammad/assets/7383572/0238cb1d-b57a-4d45-b6be-1c719015a825)

Forum post:
https://community.zammad.org/t/core-workflows-not-blocking-users-from-changing-customer-details/14436

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MarkusHeld** [comment]
Already recorded here: [https://github.com/zammad/zammad/issues/3878](url)

**Comment by MarkusHeld** [comment]
Already recorded here: https://github.com/zammad/zammad/issues/3878
