### ISSUE TITLE
Priority cannot be changed with Email-Filter

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5237]
### Used Zammad Version

6.3.1-1718620481.9d65e987.bookworm

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian 12 on WSL2
- Database + version:  psql
- Elasticsearch version: any
- Browser + version: Edge

### Actual behaviour

When creating a postmaster filter that sets the priority, the priority is ignored.

### Expected behaviour

When creating a postmoster filter that sets a priority, the priority is changed correctly.

### Steps to reproduce the behaviour

![image](https://github.com/zammad/zammad/assets/97293098/1c40d997-7ad5-43eb-a1e2-0e36da6491b1)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by t-shehab** [comment]
Hi @YetAnotherGerrit,

I cannot reproduce this. Am I missing something? I recreated the filter from your screenshot exactly (apart from the 'Ö'. I couldn't help myself. :-) ). And it changed the priority, no problem.

![image](https://github.com/zammad/zammad/assets/114283486/fc950729-5281-481c-af37-ab13f00656cc)

**Comment by YetAnotherGerrit** [comment]
Strange:

![image](https://github.com/zammad/zammad/assets/97293098/a870110e-7c68-4ade-8aa1-41ab8af8bc8f)

Let me update to the latest stable build.

**Comment by YetAnotherGerrit** [comment]
I just did a reseed of my instance (starting fresh). Now, it's not reproducible anymore. I'll reopen, if I stumble on it again. Don't know what was broken in the previous installation. I was testing my macro-recorder in that instance.
