### ISSUE TITLE
unknown operator 'today' for ticket.created_at

### ISSUE THREAD

**Issue by ASchmidt84** [zammad/zammad#5238]
### Used Zammad Version

5.3

### Environment

Installation package

### Actual behaviour

unknown operator 'today' for ticket.created_at

### Expected behaviour

Display all today created tickets

### Steps to reproduce the behaviour

Create a report with created today

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
Zammad 5.3 is outdated. We do not accept bug reports for outdated Zammad versions. Please upgrade asap.
