### ISSUE TITLE
"Set to internal/public" switch displayed differently before and after creating an article

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#5241]
### Used Zammad Version

6.3.1

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: MS Edge, v. 126.0.2592.68 (official build) (64-bit)

### Actual behaviour

When creating an article (to the left of the article field), the symbol (set to internal) is displayed opposite the symbol that is displayed under an existing article. 

### Expected behaviour

The same symbol should appear when articles are set to internal, whether during the creation of an article or after the article has been created. 

### Steps to reproduce the behaviour

1) Write an article and update the ticket.
2) start writing a second article and try to set it to "internal"; a different symbol will be displayed. 

<img width="593" alt="image" src="https://github.com/zammad/zammad/assets/101350124/2b0b8d28-5bc3-4cfb-8eb7-5984add1814a">

### Support Ticket

Ticket#10157056

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by binsky08** [comment]
related to https://github.com/zammad/zammad/issues/2448

**Comment by dominikklein** [comment]
As already discussed in the linked issue:

The output is more or less correct. One is a call to action (what it will become when clicked), and the other one shows the current state of the field (a signal to the user what's the current value).

In the new desktop view, it's also already in a better state.
