### ISSUE TITLE
occasional pg type mismatch when sending emails

### ISSUE THREAD

**Issue by yogo1212** [zammad/zammad#5248]
### Used Zammad Version

6.3.1

### Environment

- Installation method: container image
- Operating system: Debian 12
- Database + version:  postgresql 14.12
- Elasticsearch version: Opensearch 1.3.17
- Browser + version: Why would it matter? Various Firefox/Brave/Chrome, black shoes, brown shoes, mustache and w/o mustache

### Actual behaviour

```
"Unable to send email to 'reda@ct.ed': Can't use Channel::Driver::Smtp: #<ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR: operator does not exist: character varying = bigint at character 91 HINT: No operator matches the given name and argument types. You might need to add explicit type casts. >"
```

### Expected behaviour

email sent

### Steps to reproduce the behaviour

send email using zammad. no recognizable pattern.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@yogo1212 Please provide more information like clear reproduction steps and so on (e.g. an example mail which is not working).

In general, this looks for me more like a technical question for the community (https://community.zammad.org).

**Comment by yogo1212** [comment]
Hi @dominikklein :-)

Sorry, I'm not sure I can share any of the emails that are known to have been affected.

A typical scenario is:
- ticket is created upon receipt of an email from, let's say "mail@dominik-klein.de"
- reply to the email
- the reply appears
- wait a short while
- error appears

I've been using the Zammad container since 2022 and the usage pattern hasn't changed.
This behaviour started occuring with one of the updates during the last 12 months.
(Also, there are now these database connection pool timeout messages a lot of other people are seeing as well)

It looks like it's a lot worse with the recent update [6.3.1-73](https://hub.docker.com/layers/zammad/zammad-docker-compose/6.3.1-73/images/sha256-09c3fb65b6d9dd74ccb4a60c8df6a1bbaf3aa1ecf34771cbddabcf969848b204).

**Comment by dominikklein** [comment]
@mantas Maybe some idea about this?

**Comment by mgruner** [comment]
@yogo1212 we can only work on this if there is a reproduction path to follow. We don't see this problem on our systems yet.
Therefore I'll close this report now. Feel free to provide more information.

**Comment by yogo1212** [comment]
@mgruner that's entirely fair :+1:
