### ISSUE TITLE
Bad data serialization for JSON database columns

### ISSUE THREAD

**Issue by chrismoeller** [zammad/zammad#5249]
### Used Zammad Version

6.3.1

### Environment

- Installation method: package
- Operating system: Ubuntu 20.04.6 LTS
- Database + version:  10.3.39-MariaDB-0ubuntu0.20.04.2
- Elasticsearch version: elasticsearch-oss 7.10.2
- Browser + version: Chrome 126.0.6478.127 (doesn't matter - bug occurs in all browsers)

### Actual behaviour

When opening the S/MIME integration overview, we are experiencing an error 500:
undefined method `join' for "[\"email@domain.tld\"]":String

Screenshot:
![Screenshot 2024-07-03 115558](https://github.com/zammad/zammad/assets/1333949/f195fa10-ad7d-4224-98d6-cf8c33c8cec5)

After acknowledging the error popup, the list of currently imported S/MIME certificates and keys is not displayed, so there's no way to delete the erroneous S/MIME cert/key:
![Screenshot 2024-07-03 115701](https://github.com/zammad/zammad/assets/1333949/5d8bdc44-4a21-4d83-9ad2-0f68d8e14ab3)

`production.log` shows these respective entries:
> I, [2024-07-03T11:58:54.198549#2796386-186120]  INFO -- : Started GET "/api/v1/integration/smime/certificate?_=1720000732642" for 10.10.2.245 at 2024-07-03 11:58:54 +0200
> I, [2024-07-03T11:58:54.208723#2796407-151720]  INFO -- : Started GET "/api/v1/http_logs/S/MIME?limit=50&_=1720000732643" for 10.10.2.245 at 2024-07-03 11:58:54 +0200
> I, [2024-07-03T11:58:54.220745#2796407-151720]  INFO -- : Processing by HttpLogsController#index as JSON
> I, [2024-07-03T11:58:54.220909#2796407-151720]  INFO -- :   Parameters: {"limit"=>"50", "_"=>"1720000732643", "facility"=>"S/MIME"}
> I, [2024-07-03T11:58:54.222594#2796386-186120]  INFO -- : Processing by Integration::SMIMEController#certificate_list as JSON
> I, [2024-07-03T11:58:54.222755#2796386-186120]  INFO -- :   Parameters: {"_"=>"1720000732642"}
> I, [2024-07-03T11:58:54.246473#2796407-151720]  INFO -- : Completed 200 OK in 25ms (Views: 2.0ms | ActiveRecord: 2.7ms | Allocations: 5913)
> E, [2024-07-03T11:58:54.251694#2796386-186120] ERROR -- : undefined method `join' for "[\"email@domain.tld\"]":String (NoMethodError)
> app/controllers/integration/smime_controller.rb:130:in `cert_obj_to_json'
> app/controllers/integration/smime_controller.rb:29:in `block in certificate_list'
> app/controllers/integration/smime_controller.rb:29:in `map'
> app/controllers/integration/smime_controller.rb:29:in `certificate_list'
> app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
> app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
> app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
> app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
> I, [2024-07-03T11:58:54.256416#2796386-186120]  INFO -- : Completed 500 Internal Server Error in 33ms (Views: 0.3ms | ActiveRecord: 6.4ms | Allocations: 6629)

This used to work, previously, and now (or with some Zammad upgrade or S/MIME certificate upload/change) does not, anymore.

Further more, there is no way to delete the erroneous cert/key using the WebUI (and we are still struggling to find out how to delete it from the database in a safe way - is there any?).

### Expected behaviour

Before this error ocurred, the list of S/MIME keys and certs was displayed when navigating to the S/MIME integration view (like this, exemplary screenshot now showing actual certificates/keys): 
![Screenshot 2024-07-03 115744](https://github.com/zammad/zammad/assets/1333949/0a6e299e-ee19-46e3-ab0b-044c36ccd008)

Additionally, no error 500 alert was shown.

Expected behaviour would be to have the list of currently imported certificates and keys displayed, not matter whether one or more of the certs/keys are not parseable. That way, the "illegal" certs/keys could be displayed as problematic and the usual "delete" function could be used to get rid of the respective erroneous cert/key.

### Steps to reproduce the behaviour

Unsure - this error seems to occur when having imported a somehow incompatible S/MIME certificate that cannot be parsed by the integration view that renders the table of currently imported certs/keys.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @chrismoeller. Are you able to share the used S/MIME certificate with us? We cannot reproduce it right now.

Thanks a lot for your feedback.

**Comment by chrismoeller** [comment]
Hi and thanks for the fast reply. Unfortunately, I cannot say for sure which certificate was imported. Is there any way to remove a certificate from the database so the S/MIME integration won't get stuck with it? 
From there on, I could try reproducing the error by importing new certs/keys.

**Comment by fliebe92** [comment]
You can try to enter the Rails Console (`zammad run rails console`) and then execute `SMIMECertificate.pluck(:id, :email_addresses)`. This should list all unique identifiers as well as the email addresses of the certificates. Not sure if it works. If you have something, you can use `SMIMECertificate.find(X).destroy!` (X = unique identifier) at your own risk to delete the faulty certificate.

Maybe it's possible for you to share the certificate with us when you have more information.

**Comment by tschaefer** [comment]
The verification is not possible because of the missing feedback.

**Comment by chrismoeller** [comment]
Sorry for the belated reply and thanks for the rails console workaround. I just executed the above and deleted one S/MIME cert after another, the error remained. Now, `SMIMECertificate.pluck(:id, :email_addresses)` does not show any remaining records.

I started freshly with one certificate (public key, .pem format), but this does not work, either - same error message: 

> undefined method `join' for "[\"hallo@network-publishing.de\"]":String

Here's the cert for your testing:
`-----BEGIN CERTIFICATE-----
MIIFGjCCBAKgAwIBAgIMbb1qUXzyOOdKt6miMA0GCSqGSIb3DQEBCwUAMFsxCzAJ
BgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMTEwLwYDVQQDEyhH
bG9iYWxTaWduIEdDQyBSMyBQZXJzb25hbFNpZ24gMSBDQSAyMDIwMB4XDTIyMDcw
NDIxNDQ1MVoXDTI1MDcwNDIxNDQ1MVowUjEkMCIGA1UEAwwbaGFsbG9AbmV0d29y
ay1wdWJsaXNoaW5nLmRlMSowKAYJKoZIhvcNAQkBFhtoYWxsb0BuZXR3b3JrLXB1
Ymxpc2hpbmcuZGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC//6ku
7VPNGqVF6khso1qnv5OBOtb3Lzz1fkHwpOYZqdWbrF2Gw5N7GaYN1jr48uVC0JrD
/6iVXnjdMbgp/TUrGQx1qTkh+9eDncojkPwSLCXbuYlztUtm9+WCPVvE+ZQGuPCt
93dTrArLOcJoutW327SLVDCBussIgYG/6I4C9k8M+Y8VdCiZT4VsqDJUmNqj4FfV
ctICt8k86Tdea/Yqx3JT0w7ykKBOnsYOiddZxXziVFl/pWlJgkidgDwtW6u/XMES
7M7DaHrhyv/zTn7zxGz6TS2mIrv2fu5xe7P6+aIY8RBYujT8X4rlKynvFFRbhYbn
YMNv4GKfUdYOe+wLAgMBAAGjggHlMIIB4TAOBgNVHQ8BAf8EBAMCBaAwgaMGCCsG
AQUFBwEBBIGWMIGTME4GCCsGAQUFBzAChkJodHRwOi8vc2VjdXJlLmdsb2JhbHNp
Z24uY29tL2NhY2VydC9nc2djY3IzcGVyc29uYWxzaWduMWNhMjAyMC5jcnQwQQYI
KwYBBQUHMAGGNWh0dHA6Ly9vY3NwLmdsb2JhbHNpZ24uY29tL2dzZ2NjcjNwZXJz
b25hbHNpZ24xY2EyMDIwMEwGA1UdIARFMEMwQQYJKwYBBAGgMgEoMDQwMgYIKwYB
BQUHAgEWJmh0dHBzOi8vd3d3Lmdsb2JhbHNpZ24uY29tL3JlcG9zaXRvcnkvMAkG
A1UdEwQCMAAwSQYDVR0fBEIwQDA+oDygOoY4aHR0cDovL2NybC5nbG9iYWxzaWdu
LmNvbS9nc2djY3IzcGVyc29uYWxzaWduMWNhMjAyMC5jcmwwJgYDVR0RBB8wHYEb
aGFsbG9AbmV0d29yay1wdWJsaXNoaW5nLmRlMB0GA1UdJQQWMBQGCCsGAQUFBwMC
BggrBgEFBQcDBDAfBgNVHSMEGDAWgBSFu/DMxDa1CmJ2o5kuj7s6aq3FUTAdBgNV
HQ4EFgQUA8szTJimTsYFWT5KAzk5xox/kaEwDQYJKoZIhvcNAQELBQADggEBAEUY
Xuc8IqCLeqcBzpZbtPnMasa/4fV2aqSmzYgenStaa4c7+eaqWOb2QfmnIvmY6+za
IqCnSNQiE/0A62wVBR/pO4JbD4tAZSJU0CVlMxDVaoeKu2ZaXgxxpNrIEPabfpxg
VFFLfveo9yHYhNM28lTOYPUYnwP670t0TCzw6o2gV4US46Kt+PSAtTPsqwYyE0n7
baYJvetmxvje3fT0oOC+VYYXqSVLpucVGVY68G9e7HsonZcouAFALMZnt0kWGRCY
WVjwgKyh2/tLVV+8z9151xSw/mm8MTPDAl4B6BrIcPZ1x1OuDtk/6e5KOipMH/ii
4l6aVJTWr70HviuYDWg=
-----END CERTIFICATE-----`

![image](https://github.com/user-attachments/assets/361cb0b7-995e-455e-8574-061b8d37171c)

![image](https://github.com/user-attachments/assets/64df161e-ed3e-4628-be4a-74fe688aacbd)

**Comment by tschaefer** [comment]
Thx @chrismoeller for providing the certificate.

I was able to localize the cause of the issue. The serialization of the data (Array of strings) on writing/reading into/from the related database table column is not working. It has to be done explicitly. A Fix is on the way.

**Comment by rolfschmidt** [comment]
Hi @chrismoeller ,

MySQL and MariaDB are deprecated, you should definitely migrate to PostgreSQL soon:

https://docs.zammad.org/en/latest/appendix/migrate-to-postgresql.html

Anyway, the reason for the issue is that rails can not detect JSON columns properly for MariaDB <10.4. There was an issue to this in the past:

https://github.com/zammad/zammad/issues/4148

There is already some kind of workaround for <10.4. We will extend it to support the missing array columns.

**Comment by chrismoeller** [comment]
Hi @rolfschmidt, thanks a lot, looking forward to the workaround. Sure, we'll plan the PostgreSQL migration soon.
