### ISSUE TITLE
Generic OAuth 2 login not visible

### ISSUE THREAD

**Issue by MrSerth** [zammad/zammad#525]
Hi there,

I tried to set up zammad to use my own OAuth provider (which is a Rails app based on doorkeeper). Even though I was able to specify everything required, I can't see a button or link to login via this generic OAuth provider. Therefore, I am unable to proceed testing the login mechanism.

In order to debug the problem, I tested the login via Google, which worked as expected (after configuring the credentials in the settings, a new button appeared on the login screen). When looking in the database, I saw all settings I made for the generic OAuth provider. In a consequence, I assume, there is a bug displaying a button or link on the login screen initiating the OAuth workflow for a custom provider.

Tested with zammad master on commit 24ba3cff44e68987ee84abe02146f14045fa53a4 (installed from source) on macOS 10.12.1

**Comment by fhuppert** [comment]
Fixing that would be great. Was trying to find a way to login with OAuth 2 but didnt find one.

**Comment by martini** [comment]
@fhuppert @MrSerth a fix is on the way (https://github.com/zammad/zammad/issues/410). Can you tell me what provider did you configure (so I also can test the functionality with that)?

**Comment by fhuppert** [comment]
@martini We use a Django based solution that we developed https://github.com/evonove/django-oauth-toolkit

**Comment by MrSerth** [comment]
@martini Unfortunately, our endpoint isn't public available (a Rails app based on the [Doorkeeper Gem](https://github.com/doorkeeper-gem/doorkeeper)). Nevertheless, I just tested the current develop branch with commit 4645f332c6e62aad08dd80ccb7e8e6c2ff26a5d6, which worked as expected. Thanks a lot!

**Comment by martini** [comment]
@MrSerth I'm a little but out of topic. This issue was because of missing generic oauth2 login button, right?

This is available since 1.2:

<img width="502" alt="screen shot 2017-02-24 at 17 01 51" src="https://cloud.githubusercontent.com/assets/110226/23311384/3b83a840-fab6-11e6-8a5b-e9a8f6b3208f.png">

Anything else regarding this issue?

**Comment by MrSerth** [comment]
@martini Yes, this issue was mainly about the missing login button. Nevertheless, there is another issue #775 connected to the OAuth2 login, we encountered as well. I'll post some notes over there.

In my opinion, you may close this issue as it is resolved.

**Comment by MrSerth** [comment]
Hi @thorsteneckel,
just for my understanding - why is this issue a duplicate of another; which one? I can't find another issue describing the missing login button. Thanks!

**Comment by thorsteneckel** [comment]
Sorry I was to lazy to pick it out 🍹 It is a duplicate of #410 - fixed since Jan 11th

**Comment by MrSerth** [comment]
Alright - thanks!
