### ISSUE TITLE
Multiple options modals in overviews

### ISSUE THREAD

**Issue by xMikuzoo** [zammad/zammad#5250]
### Used Zammad Version

 6.3.1

### Environment

- Installation method: source
- Operating system: Ubuntu 22.04.4 LTS
- Database + version:  PostgreSQL 14.12
- Elasticsearch version: 7.17.22
- Browser + version: chrome 126

### Actual behaviour

When I go into the overview and click options to change what is shown in the table, a modal opens to edit what this table should show, but when I change the overview and click options, a modal opens for this table and for the previous table. Each time I change the overview, there are more and more modals of previous overviews.

![Zrzut ekranu 2024-07-04 101707](https://github.com/zammad/zammad/assets/105241268/4a4e7201-8549-47bd-9e57-4614ae51ebdf)

### Expected behaviour

When i change overview and click options it should open modal only for this overeview

### Steps to reproduce the behaviour

enter the overview, go through several overviews, then click options and you will see the modal for each previous overview.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @xMikuzoo. Please see https://github.com/zammad/zammad/issues/5243, thx.
