### ISSUE TITLE
Time event trigger "Pending till has reached" is not working

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5257]
### Used Zammad Version

6.3.1-1719857269.4363a065.bookworm

### Environment

- Installation method: package
- Operating system (if you're unsure: cat /etc/os-release ): Debian 12 on WSL2
- Database + version: psql (PostgreSQL) 15.7 (Debian 15.7-0+deb12u1)
- Elasticsearch version: 7.17.22
- Browser + version: MS Edge

### Actual behaviour

When creating a Time event-Trigger that reacts to "Pending till" "has reached" time events, it does not run at all.

### Expected behaviour

When creating a Time event-Trigger that reacts to "Pending till" "has reached" time events, it does run.

### Steps to reproduce the behaviour

Create tigger:
![image](https://github.com/zammad/zammad/assets/97293098/381eb5c2-8505-41dc-a853-1a2467f00e01)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@YetAnotherGerrit Are you sure that the background job is running correctly?

**Comment by YetAnotherGerrit** [comment]
While I was trying to reproduce several scenarios, I recognized they eventually all work. But the delay from the "pending till"-time to the trigger run was between 3 minutes and over an hour. On a total idle system.

**Comment by MrGeneration** [comment]
On a normal system. depending on when the update is triggered. the process can take anything between seconds up to 10 minutes. This doesn't allow Zammad to be used for minute accurate things (especially not with pending reminders). This is a technical limitation in my opinion because on how it's done as of now. If it takes significantly more than 10 minutes, it's a question of tuning.

**Comment by dominikklein** [comment]
Yes, normally the pending times are checked every 15 minutes. So it should normally not be longer on an idle system.

**Comment by dominikklein** [comment]
@YetAnotherGerrit So was it only the delay, or was it really not working?

**Comment by YetAnotherGerrit** [comment]
The random delay makes the time event triggers unpredictable as some parts of the time events are done immediately and some parts are executed at random times.

We should do a refinement or training about the time event triggers. Because currently, there is a lot of use cases that appear to work but aren't. I'll make an appointment once @Mirtaaa is back from vacation.

**Comment by dominikklein** [comment]
Every time event is normally triggered in the same way. What kind of immediately execution to you mean related to the time events?

**Comment by YetAnotherGerrit** [comment]
This is an issue that can hopefully be solved with devops adjustments.

**Comment by MrGeneration** [comment]
> This is an issue that can hopefully be solved with devops adjustments.

For everyone that was not in this meeting (?), can you please eloberate what you mean with that statement?
Closing this issue -in my opinion- does not solve the issue in the core. Imho this is a core issue as you cannot plan *anything* on a per minute basis (e.g. pending reminders) which is unexpected to many users - especially in the year 2024.

A cronjob can do this just fine imho. I understand that the core currently can't reflect it and thus needs an improvement. "devop adjustments" with closing this sounds like a "never will fix, workaround this manually". Workarounding this manually might have serious drawbacks in terms of performance which might be unexpected or not be foreseen.
