### ISSUE TITLE
Inline images in outgoing mails break HTML structure

### ISSUE THREAD

**Issue by orlemin** [zammad/zammad#5258]
### Used Zammad Version

6.3.1

### Environment

- Installation method: [package]
- Operating system: [debian 11]
- Database + version:  [postgresql 13.14]
- Elasticsearch version: [7.17]
- Browser + version: [chrome 126]

### Actual behaviour

When sending outgoing messages from Zammad with inline images, the HTML structure is somehow broken. The `<!DOCTYPE html>` is missing as well as the `head` part with all style information.

### Expected behaviour

Inline images should not break the HTML structure.

### Steps to reproduce the behaviour

Create a new mail ticket within in Zammad and paste an image to the editor. After sending the mail, use the `Raw` button to download the EML file and check the HTML structure.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Can you please ensure this also happens with a vanilla Zammad installation? It sounds like you have custom changes in your environment. You can quickly double tab that by using a trial instance from zammad.com which will automatically be removed without adding payment info.

**Comment by orlemin** [comment]
Yes, I can confirm that this happens with freshly installed zammad instances. For troubleshooting purposes I installed the new instance with as close software versions as possible to our production instance.

**Comment by fliebe92** [comment]
Hi @orlemin. Could you please attach an EML file of a mail that was sent out? You can download it directly from within Zammad. This would help us for investigating + verifying this issue.

Thanks a lot.

**Comment by orlemin** [comment]
Hi @fliebe, of course!

github didn't let me attach the files directly, which is why they've been zipped.
Inside are 2 eml files, one we've sent with an image embedded and the other without any images.

[eml-files.zip](https://github.com/user-attachments/files/16174380/eml-files.zip)

**Comment by fliebe92** [comment]
Hi @orlemin. Thanks for the files. I was able to verify it, but it was needed to re-phrase whole parts of your initial report to make it clear what happens.

**Comment by fliebe92** [comment]
Hi @orlemin. The issue is fixed and after packages are done with building, feel free to update your Zammad instance. Thanks again for the report.
