### ISSUE TITLE
Webhook custom payload parser does not accept digits within placeholders

### ISSUE THREAD

**Issue by YakovlevNK** [zammad/zammad#5265]
### Used Zammad Version

6.3.1-1720156707.17f20fad.jammy

### Environment

- Installation method: package
- Operating system: ubuntu 22.04
- Database + version: postgresql 14.12

### Actual behaviour

Zammad was created by importing from Freshdesk, in which we used custom fields. After importing from Freshdesk, the ticket field "cf_rand319577" was created.

When creating a webhook with a custom payload: 
`"category": "#{ticket.cf_rand319577}"`
I get the same value in JSON:
`"category": "#{ticket.cf_rand319577}"`

A typo in the field name is excluded, since it is obtained using the editor:
![image](https://github.com/user-attachments/assets/0c84c0e9-b5e7-4aed-a253-3e743ddedbdb)
But in "Example Payload" this field is transmitted correctly:
![image](https://github.com/user-attachments/assets/a8d30072-ded8-4e90-bb99-d85ca7cf2e60)
This field is also transmitted if you do not use custom payload in the webhook.

### Expected behaviour

The value of the cf_rand*** field in the custom payload must be transmitted (similar to how it is transmitted without using the custom payload).

### Steps to reproduce the behaviour

1. Import from Fresdesk which has a ticket custom field.
2. Create a webhook with a custom payload in which this field is transmitted.
3. Use the created webhook.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @YakovlevNK. Could you please post more information about your `cf_randXXX` field? What's the field type? A screenshot of this field in the object manager attributes would help us.

Thanks a lot!

**Comment by YakovlevNK** [comment]
![ticket_field](https://github.com/user-attachments/assets/3f99bb2b-5158-4f16-b55a-085795d88a39)

I also noticed that the user field has a similar behavior (when imported from freshdesk, they are automatically assigned a name like rand******)
User field example:
![user_field](https://github.com/user-attachments/assets/b5a57c05-a6fb-4418-b989-c8de4b0cb646)

**Comment by YakovlevNK** [comment]
Update. Apparently, the problem affects not only fields imported from Freshdesk but also custom fields created in /#system/object_manager

In addition, all tested problem fields have Cyrillic in key.

**Comment by fliebe92** [comment]
> Update. Apparently, the problem affects not only fields imported from Freshdesk but also custom fields created in /#system/object_manager
> 
> In addition, all tested problem fields have Cyrillic in key.

Could you please test it with an object manager attribute without Cyrillic keys?

**Comment by YakovlevNK** [comment]
![image](https://github.com/user-attachments/assets/487dd375-ccdd-43f1-a4cc-ff191fda3ab8)
"true" was sent for such a field

**Comment by fliebe92** [comment]
Thanks a lot for testing this.

**Comment by tschaefer** [comment]
It's a bug in the payload parser - It does not accept digits within the placeholders.

**Comment by YakovlevNK** [comment]
> It's a bug in the payload parser - It does not accept digits within the placeholders.

Perhaps it also doesn't accept spaces? Since in the original cf_rand319577 there are no numbers but there are spaces.
