### ISSUE TITLE
Dark mode doen't show yellow marked text

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#5266]
### Used Zammad Version

6.3.1

### Environment

- Installation method: package
- Operating system: Ubuntu 20.04
- Browser + version: Edge 126

### Actual behaviour

Some users are marking text in their mails.
An agents uses the dark mode and don't see this marked text. If he is switched to the light mode all colors are shown

![wrong-color-rendering](https://github.com/user-attachments/assets/158fd19e-602d-457b-ab5c-35b30db3f433)

The HTML code:
![image](https://github.com/user-attachments/assets/6a34c78f-7e25-4025-94f7-ee6cc4665e56)

### Expected behaviour

All colors should be rendered in dark mode too (like light mode)

### Steps to reproduce the behaviour

Mark text in Outlook and send this mail to Zammad
Use dark mode in Zammad and open the new ticket
the color is gone

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @Dennis1993. Could you please provide a test mail for us? This would help us a lot :) Thanks!

**Comment by Dennis1993** [comment]
Yes, no problem! :)
[ticket-5347567-233741.zip](https://github.com/user-attachments/files/16238328/ticket-5347567-233741.zip)

**Comment by fliebe92** [comment]
Hi @Dennis1993. This works as designed: https://github.com/zammad/zammad/blob/stable/app/assets/stylesheets/zammad.scss#L12964-L12968

In dark mode, there are no background and no font colors.

**Comment by saz** [comment]
I wonder, what's necessary to change this behavior, as it is quite unexpected from a user perspective (e.g. there's no hint that possible valuable information isn't visible within dark mode).
