### ISSUE TITLE
Pre-defined webhook for Microsoft Teams needs to be updated

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5267]
### Used Zammad Version

any

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

According to a [community member](https://community.zammad.org/t/changes-to-teams-notification-webhook/14945) it is not only [the documentation](https://github.com/zammad/zammad-admin-documentation/issues/577) that needs to be updated because of [the deprecation](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/) of the MS Teams connector, but also the default payload.

### Expected behaviour

Update the default MS Teams payload in sync with the documentation updates of https://github.com/zammad/zammad-admin-documentation/issues/577

### Steps to reproduce the behaviour

Register a MS Teams webhook:
![image](https://github.com/user-attachments/assets/d809d91f-6602-4018-9653-3f7ccb7c7666)

### Useful resource

https://www.adaptivecards.io/designer/

### I'm sure this is a bug and no feature request or a general question.

Currently it's an enhancement, but it will be a bug once the connector is deprecated.

**Comment by fliebe92** [comment]
Unfortunately, we (as well as consulting) were not able to verify the new payload with a deprecated connector in MS Teams.
