### ISSUE TITLE
Inactive Ticket States selectable in Mobile View

### ISSUE THREAD

**Issue by timoschwarzer** [zammad/zammad#5268]
### Used Zammad Version

6.3.1

### Environment

- Installation method: Kubernetes / Helm
- Operating system: N/A
- Database + version: PostgreSQL 13
- Elasticsearch version: 8.12.0
- Browser + version: Chrome 126.0.6478.126 (Official Build) (64-bit) 

### Actual behaviour

We modified ticket states as follows:

![image](https://github.com/user-attachments/assets/4fdd4f8d-f5fb-4225-8b8e-67b95290e4ba)

While this works in the desktop view, it does still show the default ticket states in the mobile view:

![image](https://github.com/user-attachments/assets/c863da48-85db-4749-beab-ad6de807091c)

![image](https://github.com/user-attachments/assets/afda90e6-55da-4eac-855b-15a46ef018e1)

### Expected behaviour

The mobile view should show the custom and hide inactive built-in ticket states.

### Steps to reproduce the behaviour

Create custom ticket states or disable built-in ones and check the mobile view.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment]
https://github.com/zammad/zammad/blob/3f86b6991c4b06a45544d8020a54e265b948453e/app/models/ticket/state.rb#L87-L92

**Comment by MrGeneration** [comment]
> 6.1

Please note that Zammad 6.1 is outdated. Current stable is 6.3.1 which is a security release. Upgrade asap.

**Comment by timoschwarzer** [comment]
@MrGeneration it was late and I misread the version number, I'm actually on 6.3.1 already 😅
