### ISSUE TITLE
Several problems with postinstall script's function `enforce_redis ()`

### ISSUE THREAD

**Issue by t-shehab** [zammad/zammad#5269]
### Used Zammad Version

installing or upgrading to `>= 6.0`

### Environment

- Installation method: package
- Operating system: any / SUSE family
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

There are several problems with `enforce_redis ()`:

1) **It checks for the global environment variable `REDIS_URL`.**
This is a problem on all installations, not just SUSE related.
```bash
if [ -n "${REDIS_URL}" ]; then
  echo "# Redis URL ${REDIS_URL} found."
  return 0
fi
```

---

2) **On SUSE-family installations, it fails to recognize running systemd redis services.**

**Background:**
Zypper  installs a systemd template file for redis under `/usr/lib/systemd/system/redis@.service`. This means, users must configure their own instance of this template via a config file (e.g. `/etc/redis/zammad.conf`), and then start and enable this instance manually (e.g. `systemctl enable --now redis@zammad.service`)

`contrib/packager.io/postinstall.sh` currently uses hardcoded values for `$REDIS_SERVICE_NAME` (`redis-server` on Debian-based systems, `redis` on all others), which of course fails for SUSE's template instances, which are named arbitrarily. 

```bash
local REDIS_SERVICE_NAME=""
if [ "${OS}" == "DEBIAN" ]; then
    REDIS_SERVICE_NAME="redis-server"
else
    REDIS_SERVICE_NAME="redis"
fi
```

---

3) **Upon unsuccessful run of `enforce_redis ()`, `postinstall.sh` just keeps running. The thrown error messages are incorrect and not useful.**

```bash
echo "It seems no redis server runs locally."
echo "Please install Redis following the instructions at https://redis.io/docs/getting-started/ or set the REDIS_URL environment variable."
echo "e.g. export REDIS_URL=redis://your.redis.server:6379"
echo
echo "Please try again the Zammad package installation."

return 1
```

### Expected behaviour

1) **Check for the correct environment variable is performed (`zammad config:get REDIS_URL` as opposed to just `REDIS_URL`)**
2) **On SUSE-family installations, running instances of `/usr/lib/systemd/system/redis@.service` are recognized.**
3) **Upon unsuccessful run of `enforce_redis ()`, the script exits and throws useful error messages.**

### Steps to reproduce the behaviour

**Regarding environment variable check:**
- Have package install on any supported distro.
- Have redis listen on any non-standard url (i.e. any url that is not `redis://localhost:6379`).
- Set zammad's env var via e.g. `zammad config:set REDIS_URL=redis://my.redis.server:6380`.
- Run postinstall script.

Postinstall.sh wil not recognize this variable, because it checks for `REDIS_URL`, as opposed to `zammad config:get REDIS_URL`.

---

**Regarding the SUSE-specific problems:**
- Have package install on SUSE.
- Have redis installed and running as systemd template instance (e.g. `redis@foobar.service`).
- Run postinstall script.

### Support Ticket

Ticket#10155977

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by t-shehab** [comment]
@ralf401,

we will also have to update our documentation regarding package installations on SUSE-family distros, regarding this.

**Comment by ralf401** [comment]
> @ralf401,
> 
> we will also have to update our documentation regarding package installations on SUSE-family distros, regarding this.

Hi @t-shehab,

thanks for this information. I created an [issue](https://github.com/zammad/zammad-documentation/issues/526) for that.
