### ISSUE TITLE
Livechat WebSocket Error

### ISSUE THREAD

**Issue by FN-Florian** [zammad/zammad#527]
Hi,
when i open my page witch livechat then i get in the Browser Console this error:

> 19:45:10.958 Firefox kann keine Verbindung zu dem Server unter ws://support.tld.eu/ws aufbauen. 1 chat.min.js:1:2972
> 19:45:10.966 io debug || onError error { target: WebSocket, isTrusted: true, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1481481910965000, originalTarget: WebSocket, explicitOriginalTarget: WebSocket, NONE: 0 } 1 chat.min.js:1:1339
> 19:45:10.970 chat debug || error { target: WebSocket, isTrusted: true, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1481481910965000, originalTarget: WebSocket, explicitOriginalTarget: WebSocket, NONE: 0 } 1 chat.min.js:1:1339

And i don't see the chat.

**Comment by martini** [comment]
Hi @FN-Florian is there a html page where I can see the issue? On my side it's working, I can't reproduce it. Thanks for feedback!

**Comment by FN-Florian** [comment]
@martini hier eine Testseite http://adless.de/chat-test.php

**Comment by jwaibel** [comment]
i face the same problem: 
here is what i see inside the server logs:

```
==> log/production.log <==
I, [2017-06-07T14:50:06.046289 #7689]  INFO -- : Started GET "/ws" for 178.5.194.21 at 2017-06-07 14:50:06 +0200
I, [2017-06-07T14:50:06.066632 #7689]  INFO -- : Processing by ErrorsController#routing as HTML
I, [2017-06-07T14:50:06.066844 #7689]  INFO -- :   Parameters: {"a"=>"ws"}
E, [2017-06-07T14:50:06.071625 #7689] ERROR -- : No route matches [GET] /ws
I, [2017-06-07T14:50:06.078611 #7689]  INFO -- :   Rendered inline template (4.2ms)
I, [2017-06-07T14:50:06.086608 #7689]  INFO -- : Completed 404 Not Found in 20ms (Views: 5.9ms | ActiveRecord: 0.7ms)
```

**Comment by dennybresch** [comment]
Hi @FN-Florian,
do you use a self-hosted system?

It seems that the chat can not connect to the Websocket. 
I guess because of a missing configuration of the websocket.

Take a look at the documentation:
https://docs.zammad.org/en/latest/install-centos.html?highlight=websocket

Best regards,
Denny

**Comment by hanneshal** [comment]
Closed due inactivity.
