### ISSUE TITLE
LDAP group at the role assignment in the ldap configuration cannot be set by copy & paste or written by hand.

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5270]
### Used Zammad Version

6.3

### Environment

- Installation method: any
- Operating system:any
- Database + version: any
- Browser + version: Firefox, Safari, any

### Actual behaviour

If I enter the group in the LDAP configuration for the role assignment by hand or by copy & paste, it is not adopted when saving the configuration.

https://github.com/user-attachments/assets/39399a01-ec38-4f57-ab4c-a252630fbec7

### Expected behaviour

The LDAP group is saved or I get a message that it cannot be saved, or i have only the option of selecting the LDAP group from the offerd group list.

### Steps to reproduce the behaviour

Go to the LDAP configuration menu and write an existing LDAP group in the field and save the configuration.

### Support Ticket

Ticket#10157102

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by fliebe92** [comment]
Hi @MarkusHeld. In my humble opinion, this is no bug.

The field you're referring to is a field which supports autocompletion. In Zammad context, such a field allows the user to start a search by pasting or even simply by typing. Afterward, it is **always** needed to confirm the value by selecting it. This is the same for e.g. the group field while creating a ticket.

The only thing that could be enhanced is the fact that the field value is not getting cleared when the user leaves the field (without selecting a value).

However, this is solved in the desktop rewrite. The field will be empty when leaving without selecting a valid value.

**Comment by MarkusHeld** [comment]
Hi @fliebe92 thank for your description. then it's not a bug, just a bit unintuitive.

If it is then solved with the desktop rewrite, then I think that is quite enough.

**Comment by MarkusHeld** [comment]
Solved with the desktop rewrite
