### ISSUE TITLE
The lines between the selectable options in the bulk action differ depending on the selected attribute

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#5272]
### Used Zammad Version

6.3.1

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge, v. 126.0.2592.102 (official build) (64-bit)

### Actual behaviour

When scrolling through the standard attributes in bulk actions, the selectable options for groups, compared to other attributes are displayed differently. 

### Expected behaviour

When scrolling through the standard attributes in bulk actions, the selectable options for groups and other attributes should be displayed the in equal fashion, for each standard attribute available. Is per se not a limiting factor, but it would be nicer to see that the UI design of the options is the same for all the attributes, and not just for some. 

### Steps to reproduce the behaviour

1) select at least one ticket in the overview
2) compare how the shown options look for groups and how for other attributes like owner, priority etc.

<img width="152" alt="image" src="https://github.com/user-attachments/assets/284907f2-120c-488e-875c-3205e71145fe">

<img width="185" alt="346549358-e8514467-169c-42bd-bc6f-8639b4f1c6e7" src="https://github.com/user-attachments/assets/b86a729c-c1d7-4bb4-bd33-31af62809dcf">

<img width="166" alt="346549113-890add1a-c49c-4046-a9f6-d4980762cfb2" src="https://github.com/user-attachments/assets/f45d4aa9-bbc3-46f3-ad4b-da8b302ea3f8">

### Support Ticket

Ticket#10158361

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @Suhopoljac. This is resolved in the desktop rewrite, since we aligned all select fields to look similar.

**Comment by mgruner** [comment]
@fliebe92 I agree, we should close this with milestone "desktop rewrite".
