### ISSUE TITLE
Language Inconsistency in Ticket Priorities After Switching to German

### ISSUE THREAD

**Issue by MoritzKlasen** [zammad/zammad#5274]
### Used Zammad Version

6.3.1. stable

### Environment

- Installation method: [e.g. source, package] any
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04] any
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3] any
- Elasticsearch version: [e.g. 7.17] any
- Browser + version: [e.g. chrome 126.0.6478.128]

### Actual behaviour

After switching the language of Zammad from English to German, the ticket priorities section shows mixed languages. The main list of priorities is in German, but when editing a priority, the name appears in English.

### Expected behaviour

All elements of the interface, including the ticket priorities and their names, should consistently display in the selected language (German).

### Steps to reproduce the behaviour

1. Start with Zammad in English.
2. Change the language to German in the settings.
3. Navigate to the ticket priorities section.
4. Click on a priority to edit it.
5. Observe the language of the priority name.

![image](https://github.com/user-attachments/assets/ec1b0b8e-a528-44ad-9dd7-914db9e6ee4a)
![image](https://github.com/user-attachments/assets/ffaf76fa-9654-49cf-b5a5-fd09a1793caa)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment]
@MoritzKlasen Thank you for your report!

First, this is not a bug, and it works as designed. The name of the ticket priority is stored in English, as is all source text in Zammad. The translation happens only in the frontend, just before the text is rendered, and this is the reason why you see it translated in the list, but not in the form, which correctly shows the data as stored in the database.

The same thing happens with many other objects in the system, most notably ticket states. The "inconsistency" you observed applies only to source texts stored in the database and allow their editing.

To properly rename the state, please use English. Afterwards, head on to Admin > System > Translations and provide a new translation for your custom text in languages of your users.

More info on translations can be found in [our documentation](https://admin-docs.zammad.org/en/latest/system/translations.html).

**Comment by MrGeneration** [comment]
Sorry to step in. It might help to improve the wording so that the user / admin is aware that this is a source field name and not the "name" in the actual display language. Multi lingual field names may cause confusion if you have no discipline with new fields or values (as example) and may contribute even more to this issue.

I see great potential in improving usability here.
