### ISSUE TITLE
Untranslated error message in /object_manager

### ISSUE THREAD

**Issue by YakovlevNK** [zammad/zammad#5276]
### Used Zammad Version

Zammad 6.3.1-1721130581.85b53b81.jammy

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Error messages in /#system/object_manager are not translated into the user's language

The screenshot shows messages with Russian language enabled.
![image](https://github.com/user-attachments/assets/0b228fd8-7411-4c8c-bdad-b44ee21d36a0)

PS I did not find a similar text for translation in translations.zammad.org.

### Expected behaviour

Error text translated into user language

### Steps to reproduce the behaviour

1. Set a language other than English
2. Go to /#system/object_manager
3. Select the integer field.
4. Specify the minimum value less than -2147483648
5. Specify the maximum value greater than 2147483648
6. Click the send button

Result: An error message is displayed that is not translated. 

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Maybe you could briefly check this, @mgruner

**Comment by mgruner** [comment]
There are a number of strings not marked for translation in `app/models/object_manager/attribute.rb`. However, I am not sure if they would be translated in the front end correctly. It looks like this would need to happen in the back end, but translation might not be available there. That's what seems to happen on my dev system.

@mantas do you remember how this is supposed to work?

**Comment by mantas** [comment]
@mgruner those errors with strings being generated on the backend do not get translated properly. We could change the error message to a hardcoded one to work around this.

**Comment by mgruner** [comment]
@mantas the screenshot shows that several error messages got concatenated in the back end and also prefixed with 'Validation failed:', so that the front end would be unable to translate them.

**Comment by mantas** [comment]
> @mantas the screenshot shows that several error messages got concatenated in the back end and also prefixed with 'Validation failed:', so that the front end would be unable to translate them.

Yes. I think we can drop `Validation failed:` prefix as well as `data option` part.  We don't even have `data option` mentioned in the UI!

We could simply use whole strings like `Minimal value must be at least 1234...`. Translatable, better readability, less code complexity. Win-win-win?
