### ISSUE TITLE
Overview for Role Admin dosn't appear in the overview

### ISSUE THREAD

**Issue by tniebergall** [zammad/zammad#528]
I've crated an overview Closed which only shows closed tickets. As role I've assigned "Admin", but in the overviews view the new overview is missing. The User has the permission Admin.

**Comment by hanneshal** [comment]
Hi,
does this issue still exist with the current release of Zammad?
I was not able to reproduce it. I tried the local, latest Zammad and with the hosted version.

Please reopen if you still have this issue with the current version.
 
regards
Johannes
![pricingtool_helpdesk_-_overviews](https://cloud.githubusercontent.com/assets/804939/22501537/7a91da98-e869-11e6-8488-df5c19eab9b3.jpg)
![pricingtool_helpdesk_-_closed_tickets](https://cloud.githubusercontent.com/assets/804939/22501573/a99c0426-e869-11e6-882c-ae75b0a9f256.jpg)
