### ISSUE TITLE
It takes two clicks to show all groups when creating a new ticket

### ISSUE THREAD

**Issue by scottocs11** [zammad/zammad#5280]
### Used Zammad Version

6.3.1-1717572987.fd8871d4.jammy

### Environment

- Installation method: package
- Operating system: Ubuntu 22.04.4
- Database + version: Postgresql 14.12
- Elasticsearch version: 7.17.21
- Browser + version: FF 128, Chrome 127

### Actual behaviour

When I go to create a new ticket as a Customer, only the sub-groups of my first group are shown.
Clicking on the web page then clicking the Groups dropdown a second time lists all of the groups.

First click:
![image](https://github.com/user-attachments/assets/3e2a3efa-8cbe-4cfe-acde-f369cf1e516c)

Second click:
![image](https://github.com/user-attachments/assets/0e489205-15bd-46f6-a1e8-a38b56c715fa)

### Expected behaviour

The first click show show all groups that are shown in the second click.

### Steps to reproduce the behaviour

- Create 10 groups.
- Login as customer.
- Check groups assets http://127.0.0.1:3000/api/v1/ticket_create?_=1722324496772

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by scottocs11** [comment]
Now after a restart, it's showing this on first click:
![image](https://github.com/user-attachments/assets/78c4dfd0-2a0c-4ea8-9f3c-49b86970d651)

**Comment by fliebe92** [comment]
Hi @scottocs11. Could you please provide complete steps how to reproduce the shown behavior and also explain about your use case? We cannot follow here, sorry.

**Comment by rolfschmidt** [comment]
I think I was able to reproduce the issue. I updated the steps to reproduce. The issue might be here:

https://github.com/zammad/zammad/blob/eec4a774f0b960f786749c33aa8701688512af89/app/models/group/assets.rb#L18

I think the list is wrong. In case `Setting.get('customer_ticket_create_group_ids')` is empty then the customer can create the ticket in any group.

**Comment by mantas** [comment]
@rolfschmidt why do you think that could cause an issue? That's a union operator, not OR :) And `ReadScope` should prevent user from accessing too much too.

**Comment by fliebe92** [comment]
@mantas @rolfschmidt `ReadScope` is also wrong for ticket creation, because it just gives access to those groups where the `customer_id` is set to the customer...

**Comment by scottocs11** [comment]
Sorry I didn't reply back quick enough, but I'm glad you figured it out!
