### ISSUE TITLE
Webhook payload doesn't contain information about target ticket when merging

### ISSUE THREAD

**Issue by herzkerl** [zammad/zammad#5285]
### Used Zammad Version

6.3.1-1722340033.fc8bee39.bullseye

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 11
- Database + version: postgres
- Elasticsearch version: newest
- Browser + version: not relevant

### Actual behaviour

When merging two tickets, the webhook payload doesn't contain information about the target ticket, i.e. the ticket that was merged with.

### Expected behaviour

I'd expect the payload to at least contain the id and/or number of the target ticket. Ideally it would also contain everything about the target ticket that is available for the source ticket (i.e. all objects including organization, user, customer, etc.)

### Steps to reproduce the behaviour

* Create a webhook with the default payload.
* Create a trigger that activated whenever a ticket is created or changed. Have it run the webhook.
* Create two tickets and merge one ticket with the other one.
* Receive and check the payload of the webhook.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
Hi @herzkerl,

Thanks for the report. I need some further information to investigate. Are you using a predefined webhook or a custom one? In the latter case can you please provide the payload (template)?

**Comment by herzkerl** [comment]
Hi @tschaefer, I'm using a custom endpoint (n8n), but the default payload.

**Comment by fliebe92** [comment]
Hi @herzkerl. Your reproduction steps are missing the complete creation of the webhook. Could you add this, please?

**Comment by herzkerl** [comment]
Hi @fliebe92. I've added the steps, hope they're not too vague, I guess the rest should be very well documented in your own docs ;)

(If you want me to add screenshots here, let me know!)

**Comment by tschaefer** [comment]
@herzkerl The default payload does not contain the wanted information. You have to create a custom payload.
Please follow the [documentation](https://admin-docs.zammad.org/en/latest/manage/webhook.html#how-do-webhooks-work), asked for help in our [community board](https://community.zammad.org) or for [professional support](https://zammad.com).
