### ISSUE TITLE
Facebook Avatar fetch fails

### ISSUE THREAD

**Issue by Kunsi** [zammad/zammad#529]
Hello,

i'm using the Zammad Facebook Channel to keep track of User requests. Unfornately the fetching of Facebook avatars fails for some reason I don't know.

Log:
`I, [2016-12-12T08:51:55.799081 #22219]  INFO -- : Can't fetch 'https://graph.facebook.com/1518923655016660/picture?type=large' (maybe no avatar available), http code: 0`

However, if I access https://graph.facebook.com/1518923655016660/picture?type=large directly, I get redirected to https://scontent.xx.fbcdn.net/v/t1.0-1/p200x200/10407584_1518925008349858_7749910951917063900_n.png?oh=772bf24d314a0bea97d59a43e9799db9&oe=58AF3C67 - which would be the correct avatar.

**Comment by thorsteneckel** [comment]
Hi @Kunsi - I was able to reproduce und locate the issue. The problem arises here: 
https://github.com/zammad/zammad/blob/7a8559e678db7671c161fca7de0ecdc7dea968db/app/models/avatar.rb#L121

I think this is causes by the UserAgent Ruby class which doesn't follow redirects:

http://ruby-doc.org/stdlib-2.3.3/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-Following+Redirection

We will fix that. Thanks for reporting!

**Comment by Kunsi** [comment]
I think the same happens for Twitter avatars - haven't checked logs yet, but we don't see any twitter avatars either.

**Comment by martini** [comment]
Hi @Kunsi 
hi @thorsteneckel 

I tried to download the image via Zammad:

```
    response = UserAgent.get(
      'https://graph.facebook.com/1518923655016660/picture?type=large',
    )
    response.body
```

And it just works fine. So I think it's a network issue. @Kunsi maybe a proxy is needed? 

Is https://scontent.xx.fbcdn.net/v/t1.0-1/p480x480/10407584_1518925008349858_7749910951917063900_n.png?oh=247815ce6060dc515cebb1a2ef98a23b&oe=5A23418B working via curl/wget from the server?

Thanks for feedback!

 -Martin

**Comment by martini** [comment]
And of course both (Facebook and Twitter) avatars are working fine for my installation (and the know installations I know).

**Comment by hanneshal** [comment]
Closed.
Please reopen when this issue still exists in 2.0.
