### ISSUE TITLE
Popup message is not translated

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5299]
### Used Zammad Version

6.3.1

### Environment

- Installation method: any (docker in my case)
- Operating system (if you're unsure: `cat /etc/os-release` ): Nobara 40
- Database + version:  psql
- Elasticsearch version: es7
- Browser + version: Chromium

### Actual behaviour

A lot of popup messages are not translated.

### Expected behaviour

Popup messages are translated.

### Steps to reproduce the behaviour

1. Set your user language to German.
2. Change the personal order of your overviews
3. Reset the overview order to default:

![image](https://github.com/user-attachments/assets/6ec2a128-7e22-4d9c-af2f-6616d3ea2ec5)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by YetAnotherGerrit** [comment]
In the last few days we also saw other popup messages. "Personal overview order was reset." is just used as an example.

**Comment by dvuckovic** [comment]
Thanks for reporting, will be fixed with Zammad 6.4 release.
