### ISSUE TITLE
Keyboard shortcuts dialog breaks url bar

### ISSUE THREAD

**Issue by Kunsi** [zammad/zammad#530]
Hello,

when opening keyboard shortcuts dialog, URL changes to http://zammad/#keyboard_shortcuts - however, when closing dialog, URL is not changed back to whatever it was before, thus preventing reopening the dialog until page is reloaded.

**Comment by thorsteneckel** [comment]
I can reproduce this. We will fix it. Thanks!

**Comment by jepf** [comment]
Additional note: If you open the shortcuts via the menu link (resulting in #keyboard_shortcuts URL), the modal dialog can be opened a second time when using the keyboard shortcut to open the dialog (Ctrl+Alt+H).

**Comment by martini** [comment]
@jepf thanks for the bugfix.
