### ISSUE TITLE
Configuration of LDAP loads forever

### ISSUE THREAD

**Issue by mueller-ma** [zammad/zammad#5300]
### Used Zammad Version

6.3.1 

### Environment

- Installation method: Helm chart
- Operating system (if you're unsure: `cat /etc/os-release` ): RKE2 v1.28.11
- Database + version: Default versions from latest Helm chart
- Elasticsearch version: Default version from latest Helm chart
- Browser + version: Firefox 129

### Actual behaviour

When I click on "Weiter" ("Next") on the following page of the LDAP configuration windows, Zammad is loading forever:

![grafik](https://github.com/user-attachments/assets/f1ec857f-9a24-4c41-b509-494df33053b7)

Even after a few hours it still shows this window:
![grafik](https://github.com/user-attachments/assets/269fc736-7bda-4c32-9e9a-f97dad43ab83)

In the log there are the following lines after pressing Next:
````
I, [2024-08-12T12:47:20.558652#1-150220]  INFO -- :   Parameters: <redacted LDAP parameters>
I, [2024-08-12T12:47:20.565557#1-150220]  INFO -- : Completed 200 OK in 7ms (Views: 0.1ms | ActiveRecord: 2.4ms | Allocations: 5760)
````

And these lines every few seconds:
````
I, [2024-08-12T12:47:20.579543#1-149640]  INFO -- : Started GET "/api/v1/integration/ldap/job_try?finished=true&_=1723466577534" for 10.42.0.207 at 2024-08-12 12:47:20 +0000
I, [2024-08-12T12:47:20.581766#1-149640]  INFO -- : Processing by Integration::LdapController#job_try_index as JSON
I, [2024-08-12T12:47:20.581801#1-149640]  INFO -- :   Parameters: {"finished"=>"true", "_"=>"1723466577534"}
I, [2024-08-12T12:47:20.589574#1-149640]  INFO -- : Completed 200 OK in 8ms (Views: 0.2ms | ActiveRecord: 2.0ms | Allocations: 6360)
````

### Expected behaviour

It loads for a few moments, not hours. If there's an issue, the issue should be displayed instead of looping forever.

### Steps to reproduce the behaviour

- Create a new LDAP source (Active directory)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
This won't be reproducable. I have seen it like 2 or 3 times in the last 6 years life. Reloading and starting over usually fixes it. I'll leave it open for devs to decide.

**Comment by mueller-ma** [comment]
I tried it about 5 times on different days and had the issue always, so I can reproduce it.

**Comment by MrGeneration** [comment]
> I tried it about 5 times on different days and had the issue always, so I can reproduce it.

Well development has to be able to reproduce too. It's not good enough if it's just burning on your computer.
I'm not saying that it can occur. I just shared my experience. Maybe you'd also add more input about your AD as it might be a difference if it's small or big in numbers.

**Comment by rolfschmidt** [comment]
Hey @mueller-ma 

1. did it work in the past?
2. how many users do you want to sync?
3. what kind of AD are you using?

**Comment by mueller-ma** [comment]
Hi @rolfschmidt,

1. it never worked
2. When I use the default ldap filter from Zammad, I get 524 users. 
````
Get-ADuser -LDAPFilter "(&(objectClass=user)(samaccountname=*)(!(samaccountname=*$)))" | measure


Count    : 524
````

~Maybe that's the issue as there are only 100 real persons and 400 service accounts. I'd set the Base DN to `OU=Users,DC=example,DC=com`, but that's not in the list of possible Base DNs. These DNs are fetched before entering bind user and password, so isn't it expectable to be incomplete?~

I was able to create a LDAP filter and reduced the number of results to about 100.

3. What do you want to know about the AD? The AD is running on Windows Server 2019.

**Comment by rolfschmidt** [comment]
hey @mueller-ma ,

maybe there is some old job blocking everything, we could try to clean up your import jobs:

1. stop zammad services

2. drop all existing import jobs

`zammad run rails r "ImportJob.where(name: 'Import::Ldap').destroy_all"`

3. start zammad services

4. try to sync again

**Comment by mueller-ma** [comment]
Hi, in the meantime we decided to use a different authentication method, so the AD issue isn't an issue for us anymore.
