### ISSUE TITLE
Ticket creation with Send Email turns into Net::SMTPSyntaxError if customer has no email address

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#5308]
### Used Zammad Version

6.3.1.e504ff79c.saas, but basically any

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any, verified on Vivialdi 6.8.3381.53 (Stable channel) (64-bit)  (Windows)

### Actual behaviour

Adding a user without any email address is possible during ticket creation while having "Send Email" selected. This will cause `Net::SMTPSyntaxError` errors, as an empty email address is not a valid email address. This cloaks up Monitoring of instances unless the next email sendout was successful and thus can be very noisy on some instances.

The same behavior is also present in the mobile view (and thus most likely also in the desktop view).

![dont-allow-email-sendout-to-users-without-mail-address](https://github.com/user-attachments/assets/3192b076-bce1-4fa1-97b4-645f8fc9b4f8)

I am seeing this kind of issue at least 2-3 times per week in SaaS.

### Expected behaviour

Zammad won't allow selecting customers wihtout email address if the email address of a customer is not set. Either deny and tell the user why or create a phone ticket instead (might be a very bad UX for agents)

### Steps to reproduce the behaviour

- have a group with configured email address
- create a user without any email address. First name and last name is enough
- open a new ticket dialogue, select "send email", select the user without email address as customer and select a group with email address (if applicable)
- Create the ticket and wait for Zammad to fail after 4 tries

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by YetAnotherGerrit** [comment]
How was it solved?

**Comment by dominikklein** [comment]
> How was it solved?

When you try to create a ticket (or article) with an invalid mail address (e.g. customer has no valid address), a error message will be shown.

<img width="1270" alt="Bildschirmfoto 2024-10-25 um 13 21 04" src="https://github.com/user-attachments/assets/e78c17a3-3db4-4598-8a0b-3cc39e8339b0">
<img width="1161" alt="Bildschirmfoto 2024-10-25 um 13 22 05" src="https://github.com/user-attachments/assets/8eb01e41-0bdb-425c-a57b-3ae560eafbf0">
