### ISSUE TITLE
Issue checking database availability on upgrade

### ISSUE THREAD

**Issue by 0xalen** [zammad/zammad#5309]
### Used Zammad Version

6.3.1

### Environment

- Installation method: deb https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 12 main
- Operating system: debian 12
- Database + version:  postgresql 13
- Elasticsearch version: 7.17.23
- Browser + version: firefox 129

NOTE: The database is on another server, running debian 11

### Actual behaviour

Whenever I try to upgrade zammad, I get the following message:

```
Preparando para desempaquetar .../zammad_6.3.1-1724237230.ea95e368.bookworm_amd64.deb ...
!!! ERROR !!!
Your database does not seem to be online!
Please check your configuration in config/database.yml and ensure the configured database server is online.
Exiting Zammad package installation / upgrade - try again.
dpkg: error al procesar el archivo /var/cache/apt/archives/zammad_6.3.1-1724237230.ea95e368.bookworm_amd64.deb (--unpack):
 el subproceso nuevo paquete zammad script pre-installation devolvió el código de salida de error 
```

The database IS available and it's verifiable via pg_isready. The credentials are correct, the firewall is okay, the network works correctly.
I've been trying to find a solution for this issue for the past 6 months. Reporting it as a bug is a last resort

### Expected behaviour

The upgrade process should be completed without errors.

### Steps to reproduce the behaviour

Setup a zammad installation with a postgresql database on a different server.

apt upgrade

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
@0xalen thanks for your report. Could you please post your `database.yml` configuration file (without the password, of course)?

You can try to debug this yourself on a running system without performing installations. There's the `contrib/packager.io/preinstall.sh` script that gets invoked on package installations. You could try copying that to a separate file and removing everything except the parts for `# Ensure database connectivity` and `# Check error state to ensure database is online`. Then you could try to run this, perhaps output the variables and see why the matching or db probing does not work compared to when you do it on the commandline.

**Comment by dominikklein** [comment]
For now, we will close this issue. Maybe this related issue also helps with the problem: https://github.com/zammad/zammad/issues/5247

When you have some more debug information, feel free to add a comment here or inside the other issue.

**Comment by 0xalen** [comment]
> @0xalen thanks for your report. Could you please post your `database.yml` configuration file (without the password, of course)?
> 
> You can try to debug this yourself on a running system without performing installations. There's the `contrib/packager.io/preinstall.sh` script that gets invoked on package installations. You could try copying that to a separate file and removing everything except the parts for `# Ensure database connectivity` and `# Check error state to ensure database is online`. Then you could try to run this, perhaps output the variables and see why the matching or db probing does not work compared to when you do it on the commandline.


This is my yml config for the database

```
default: &default
  pool: 50
  timeout: 5000
  encoding: utf8
  adapter: postgresql
  database: zammadbd
  username: zammad
  password: 'P4$w0rd''
  host: '10.0.1.x'
  port: 5432

production:
  adapter: postgresql
  database: zammadbd
  pool: 50
  timeout: 5000
  encoding: utf8
  username: zammad
  password: 'P4$w0rd'
  host: '10.0.1.x'
  port: 5432

```

**Comment by 0xalen** [comment]
> For now, we will close this issue. Maybe this related issue also helps with the problem: #5247
> 
> When you have some more debug information, feel free to add a comment here or inside the other issue.

It's not related to that issue, since the DB server is on a different machine from the Zammad installation. They're not updated at the same time.

**Comment by 0xalen** [comment]
> For now, we will close this issue. Maybe this related issue also helps with the problem: #5247
> 
> When you have some more debug information, feel free to add a comment here or inside the other issue.

Could you reopen this issue? It's not a duplicate, since it's not related to the one you mentioned

**Comment by MrGeneration** [comment]
Please stop spamming this issue, thank you. Be patient. It is a technical duplicate.
If you have technical questions, kindly use our community: https://community.zammad.org

**Comment by sergiocarvalho-soomacom** [comment]
I have encountered a bug that could result in failed detection of database availability. When host is missing from the configuration file, the package preinstall script assumes a default of 'localhost'. This is the wrong behaviour. When host is missing, it should attempt connecting to postgresql unix socket.

A quick user fix is to setup the database to listen on localhost, or configure zammad to use TCP connections. 

A permanent fix is out of my capabilities, but involves changing `opt/zammad/contrib/packager.io/preinstall.sh`. These lines are wrong:
```
if [ "${DB_HOST}x" == "x" ]; then
   DB_HOST="localhost"
fi
```
