### ISSUE TITLE
New keyboard shortcut "t" superseds 'new tab' in some browsers

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#5312]
### Used Zammad Version

6.4.x.ae61f2856.saas

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: 6.8.3381.55 (Stable channel) (64-bit) (Windows)

### Actual behaviour

When using CTRL + t the inline translation is being activated instead of opening a new tab for me. 

![shortcut-t](https://github.com/user-attachments/assets/cae0b8e0-9297-4b01-8f93-1cb4392f9e95)

I explicitely didn't test other shortcuts which may also be affected depending on what the browser usually has as keyboard shortcuts. I just stumbled upon one I regulary use (a lot).

### Expected behaviour

My browser opens a new tab when using CTRL + t instead of being superseeded by Zammad.

### Steps to reproduce the behaviour

- Ensure the new keyboard shortcuts are enabled (might require a windows based Browser)
- Press CTRL + t
- Don't find yourself in a new tab, but with enabled inline translation

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by tschaefer** [comment]
Single shortcuts are not activated by default in Vivaldi. Some of these shortcuts also overlay the Github single shortcuts. There is no way to find shortcuts that work in combination with any software in the wild. The user has to find some compromises.

**Comment by MrGeneration** [comment]
> Single shortcuts are not activated by default in Vivaldi.

Oh, you're right. If I enable "Single Key Shortcuts", it will disable the functionality of the 't' shortcut in Zammad. Well.

**Comment by dvuckovic** [comment]
Should be fixed now, but I noticed it was present in FF too. It stemmed from a bug that we activated a shortcut for any combination with the "t" key, modifiers or not. Now it's improved, and it takes into account user's choice of going back to the old layout.

And yes, @MrGeneration, you found the unicorn! 🦄
