### ISSUE TITLE
Zammad not handling X-Forward-For that is a list

### ISSUE THREAD

**Issue by twiggy** [zammad/zammad#5317]
### Used Zammad Version

6.2

### Environment

Ubuntu
AWS
ALB 

### Actual behaviour

Our sessions and other things like new device emails are showing our internal 172.x addresses ( martian address ) vs 

We have nginx in front of zammad, but that is also behind an AWS ALB

We have correct X-Forward-For headers setup, but believe Zammad is not grabbing the proper ip since it would be a list.

8.8.8.8,172.1.1.1 is how the header would look. Current solution I think might be grabbing the last ip which would be our ALB proxy.

https://github.com/zammad/zammad/blob/b361246c9fb4bc811ed16237d9ad13638ba555b9/lib/sessions/event/base.rb#L123

https://github.com/zammad/zammad/blob/b361246c9fb4bc811ed16237d9ad13638ba555b9/lib/sessions/event/base.rb#L124

I think the recommend solution in Rails is now to use request.remote_ip which handles X-Forward-For, lists of ip, and even has some spoofing attack prevention.

https://github.com/rails/rails/blob/c692e75d96f572f3fe518f06bec0dfd12b548429/actionpack/lib/action_dispatch/middleware/remote_ip.rb#L29

Our nginx config does have the needed 

```proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;```

I'm going triple verify it's getting through,but I would think using request.remote_ip would fix other issues as well and be easier to maintain going forward.

![image](https://github.com/user-attachments/assets/a287bee1-ce68-430f-805f-bb69b1e22c94)

172.20.4 and 172.20.5 are our ALBS ( multi-zone )

### Expected behaviour

Would expect to see end user ip in logs

### Steps to reproduce the behaviour

Place zammad behind 2 or more proxies\reverse proxies including a local one like nginx

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by twiggy** [comment]
After some digging I'm going to go with the workaround

```
real_ip_header X-Forwarded-For;
set_real_ip_from 172.16.0.0/16;
```

in nginx. 

This seems to set the headers properly. 

I'm not sure we where getting 2 ips although we should be, but seems like nginx wasn't logging my ALB when I tried.

With the above fixes sessions and probably the new device email, but I'll confirm. I would suggest in your docs and in code not to directly reference X-Forwarded-For since Ruby is probably more standard and spoofing could be a thing...not to mention a lot of confusion around proxy and x-forward-for looking at the various issues opened over time.

Thanks for Zammad!

**Comment by mgruner** [comment]
We can confirm this. The logic in `lib/sessions/base.rb` is incorrect, because it ignores list values for X-Forwarded-For and also does not consider Rails' trusted proxies.

Unfortunately, we cannot use `request.remote_ip` because when started from the websocket server, this does not have a rack context with a request object. We'll investigate.
