### ISSUE TITLE
Entry in ticket history should include the checklist item name if someone checks off an item

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5320]
### Used Zammad Version

6.4.x

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When checking of a checklist item the history does not contain the name of the checklist item:

![image](https://github.com/user-attachments/assets/d0285d35-775d-4809-b5e1-f2267625b214)

### Expected behaviour

When checking of a checklist item the history does contain the name of the checklist item.

### Steps to reproduce the behaviour

Check of a checklist item and check the ticket history.

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by dominikklein** [comment]
Small example how it was improved:

<img width="720" alt="Bildschirmfoto 2024-08-30 um 11 06 00" src="https://github.com/user-attachments/assets/88f32f0d-8eee-4aa5-8a27-7b326e2c808c">
