### ISSUE TITLE
Changing email address in the UI hangs

### ISSUE THREAD

**Issue by xeruf** [zammad/zammad#5325]
### Used Zammad Version

6.2

### Environment

- Installation method: [e.g. source, package] kubernetes helm
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] firefox latest

### Actual behaviour

When changing the e-mail address to a user to an e-mail address that another user already has and clicking save, it hangs

### Expected behaviour

an error message that there is a conflict

### Steps to reproduce the behaviour

see above

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mantas** [comment]
Seems to be fixed already in the current release. 6.2 is a wee outdated.

![Screenshot 2024-09-02 at 15 12 36](https://github.com/user-attachments/assets/a6f5da02-e424-4ef2-81a8-07be18813ef1)

**Comment by mgruner** [comment]
@xeruf please update to the latest version of Zammad (6.3.1) and let us know if this problem still occurs - we cannot reproduce it.
