### ISSUE TITLE
Password validation errors containing %s are not interpolated

### ISSUE THREAD

**Issue by oeTiFa** [zammad/zammad#5327]
### Used Zammad Version

6.3.1

### Environment

- Installation method: Docker via Portainer

- Browser + version: Edge Version 128.0.2739.42

### Actual behaviour

If I enter e to short password, the error message says: `Invalid password, it must be at least %s characters long!`
I tried this with english and german language.

### Expected behaviour

The actual configures minimum password length is shown instead of `%s`

### Steps to reproduce the behaviour

- Go to home page
- klick "Register as new customer"
- Enter info an a password that is to short
- Error message says: `Invalid password, it must be at least %s characters long!`

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by PatrickHuetter** [comment]
I can confirm this bug.
