### ISSUE TITLE
Several admin permissions cannot be assigned or do not work properly

### ISSUE THREAD

**Issue by itkfm** [zammad/zammad#5328]
### Used Zammad Version

6.3.1-1725342964.91ea1665.bookworm

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian 12
- Database + version:  postgresql 15.8-0+deb12u1
- Elasticsearch version: 7.17.23
- Browser + version: Firefox 129 and Chrome 128

### Actual behaviour

Let’s assume we create an almost-super-admin that has all but one admin permission. Say we leave the “translation” permission unticked, so we don’t have admins accidentally edit translations. (Use case: The “inline translations” keyboard shortcut for non-macOS systems hijacks the shortcut ctrl+shift+t that is commonly used by browsers to reopen the previously closed tab.)

Such a user lacks certain permissions (cannot change “Auto Assignment” settings) and runs into UI quirks.

Instead of showing the ticket settings (`/#settings/ticket`), I’m redirected to the user profile settings page (`/#profile`).
When I retry to open the ticket settings from this state, some tabs are empty.
![image](https://github.com/user-attachments/assets/02b10672-470d-4a8d-8b3f-dc5fc2a51fed)
![image](https://github.com/user-attachments/assets/cdef8929-a323-4413-8d0d-285bc0d3ffa9)
![image](https://github.com/user-attachments/assets/7c0ed3fb-368e-4d51-844b-7223adef2b3e)
![image](https://github.com/user-attachments/assets/8786b4e6-8455-4ba7-be5b-d4488c0ae23a)

If the next step followed directly after this involves opening another settings page with a list, the list will be shown twice.

### Expected behaviour

- I can assign all granular permissions individually that are equivalent to the full “Admin” checkbox.
- Clicking on specific settings pages takes me to them, not my user settings.
- An admin with all relevant permissions can configure auto assignments, ticket notifications and duplicate detection.

### Steps to reproduce the behaviour

1. Create a new role “Admin2” with all but one admin permission (plus the common ones that the default “Admin” role has).
2. Assign it to a user. (Ideally, make it their only role, but at least make sure they aren’t granted the fully-blown admin permission from any of their assigned roles.)
3. Log in to Zammad as this specifically prepared user with the “Admin2” role.
4. Click on the gear icon to open the instance settings (`/#manage`).
5. Go to *Settings* > *Ticket*. (You’ll be redirected to `/#profile`).
6. Click on the gear icon once again to reopen the instance settings (`/#manage`).
7. You should find yourself on `/#manage` with the *Settings* > *Ticket* category loaded, but no sub-tab.
8. Click on *Manage* > *Roles* to check out the “double list” glitch (on `/#manage/roles`).
9. There are now two roles lists (with their heading + add button) one below the other on screen.

<details><summary>Additional screenshots</summary>

##### Step 1

![image](https://github.com/user-attachments/assets/1d727bb2-cc61-47b4-bc18-d3977f5d65b4)

##### Step 7

![image](https://github.com/user-attachments/assets/fb851327-f428-4799-98ea-258cc45593f5)

##### Step 9

![image](https://github.com/user-attachments/assets/617c86e5-239a-4746-9bc6-5d98945fd0ef)

</details>

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Looks like we have some permissions, that are used for the settings but they are not available in the frontend permission assignment, for example:

`admin.ticket_auto_assignment`
`admin.ticket_duplicate_detection`
