### ISSUE TITLE
Issue with Zammad filtering: Unable to Filter on objects by external data source fields

### ISSUE THREAD

**Issue by dehoej** [zammad/zammad#5333]
### Used Zammad Version

6.3.1

### Environment

- Installation method: Kubernetes Helm Chart
- Operating system rhel 9.4
- Database + version:  postgressql 15.4.0
- Elasticsearch version: 8.12
- Browser + version: chrome 127.0.6533.73, Firefox 128.0.3

### Actual behaviour

When creating a report profile, a trigger or a workflow in Zammad and attempting to filter tickets based on fields that utilize an external data source, the system fails to perform the search. Specifically:

- No results are returned when filtering by these fields. The loading icon just keeps spinning: ![image](https://github.com/user-attachments/assets/dc610c79-bc0f-408d-8f76-295c3c2d53d2)
- In "Expert Mode," an error message appears: "`no implicit conversion of Symbol into Integer`".
- In the browser console, the following error occurs whenever typing in the field: `Uncaught TypeError: Cannot read properties of undefined (reading 'params')`
- The server log contains the following error: `ERROR -- : Selector::Sql.get->InvalidCondition: Invalid condition pre_condition nil {:name=>"ticket.afdeling", :operator=>"is", :value_completion=>"test", :value=>[]}!.`

### Expected behaviour

When filtering tickets (or other objects) based on fields that utilize an external data source:

- The system should correctly return tickets matching the filter criteria.
- No errors should be triggered in the browser console, server logs, or in the interface.

### Steps to reproduce the behaviour

1. Go to Zammad's Objects section and create a custom ticket attribute using an external data source.
2. Create or update a ticket, filling in the custom attribute field that utilizes the external data source.
3. Go to the Reports section and create a new report profile.
4. Attempt to filter tickets based on the custom attribute field created in step 1.
5. Notice that no results are returned, and errors occur in "Expert Mode" and the browser console.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
Hi @dehoej,

there is no info about the exact version of your system. Can you update to the latest zammad version to verify that this is not already solved or related to https://github.com/zammad/zammad/issues/5298 ?

**Comment by dehoej** [comment]
@rolfschmidt 
Thank you for taking your time. The exact version the first thing i wrote. As far as i know i am using the latest version - my version is 6.3.1.

**Comment by MrGeneration** [comment]
At least provide the used docker tag you're using that helps to pin down the actual version. Zammad is a rolling stable so it is relevant to know exactly.

**Comment by dehoej** [comment]
The docker image is: ghcr.io/zammad/zammad:6.3.1-4

**Comment by MrGeneration** [comment]
> zammad:6.3.1-4

Which is terribly outdated :)
![image](https://github.com/user-attachments/assets/bde467a9-b31d-4757-be77-a98e2c1b58cb)

**Comment by dehoej** [comment]
Where can i see that list?

**Comment by MrGeneration** [comment]
Sorry but this repository is not made for technical questions. You can find the package list with all tags in this repos package list.
https://github.com/orgs/zammad/packages/container/package/zammad

We currently expect that this issue has been solved by https://github.com/zammad/zammad/issues/5298. Should this not be the case after you updated, please let us know. For technical questions, please use the Zammad community: https://community.zammad.org.
