### ISSUE TITLE
rake assets:precompile generates files with wrong file permissions 640 instead 644

### ISSUE THREAD

**Issue by antonionardella** [zammad/zammad#5338]
# UPDATE

### Used Zammad Version

6.3.1-1724757244.41b98ccb.noble

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): ubuntu 24.04
- Database + version: postgresql 16.4
- Elasticsearch version: 7.10.2
- Browser + version: Firefox 129.0.2 (64-bit)

### Actual behaviour

`root> zammad run rake assets:precompile` generates files with permission 640.

![image](https://github.com/user-attachments/assets/f3ecda3c-b9b5-4ce1-a508-27ec2bd58f67)

### Expected behaviour

`root> zammad run rake assets:precompile` generates files with permission 644.

# OLD

### Used Zammad Version

6.3.1-1724757244.41b98ccb.noble

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): ubuntu 24.04
- Database + version: postgresql 16.4
- Elasticsearch version: 7.10.2
- Browser + version: Firefox 129.0.2 (64-bit)

### Actual behaviour

Installed a package which modified files in `app/assets/javascripts/app/views/`
After running the `sudo zammad run rake zammad:package:post_install` command, the `*.js` and `*.js.gz` files have `640` permission instead of `644` giving a `403` error in the browser once Zammad is restarted

### Expected behaviour

After the `sudo zammad run rake zammad:package:post_install` command, the permissions shall always be correctly set to `644` to make sure Zammad works as expected after a restart.

### Steps to reproduce the behaviour

Write a simple Zammad package to substitute a file in the Zammad administration

`itdidactics-backend_pages.szpm`
```
{
  "name": "Backend Pages",
  "version": "0.0.1",
  "vendor": "Antonio Nardella",
  "license": "GNU AFFERO GENERAL PUBLIC LICENSE",
  "url": "https://linkfree.antonionardella.it/",
  "files": [
    {
      "location": "app/assets/javascripts/app/views/user.jst.eco",
      "permission": 644
    }
  ]
}
```

Content of `user.jst.eco` (changed the order of the roles and the user list div)
```
<div class="page-header">
  <div class="page-header-title">
    <h1><%- @T( @head ) %> <small><%- @T( 'Management' ) %></small></h1>
  </div>
  <div class="page-header-meta">
    <% if @buttons: %>
    <% for button in @buttons: %>
      <a data-type="<%= button['data-type'] %>" class="btn <%= button['class'] %>"><%- @T( button.name ) %></a>
    <% end %>
    <% end %>
  </div>
</div>
<div class="page-content">
  <div class="searchfield">
    <input class="js-search form-control" name="search" placeholder="<%- @Ti('Search for users') %>" type="search">
    <%- @Icon('magnifier') %>
  </div>

  <div class="table-overview"></div>
  
  <div class="userSearch horizontal">
    <div class="userSearch-label"><%- @T('Roles:') %></div>
    <div class="tabs tabs-wide">
      <% for role in @roles: %>
        <div class="tab" data-id="<%= role.id %>"><%- @Ti(role.displayName() ) %></div>
      <% end %>
    </div>
  </div>

</div>
```
Install package through the Package management `/#system/package`.
Run `sudo zammad run rake zammad:package:post_install`
![image](https://github.com/user-attachments/assets/519519de-de2c-463e-bf16-19cd5282278d)
Check file permissions (which are `640` instead of the `644` as set in the `itdidactics-backend_pages.szpm` file
![image](https://github.com/user-attachments/assets/102ece52-7f65-4112-a6e3-1bff62300368)
Now it is necessary to set the permissions to `644` manually to avoid being locked out of Zammad caused by an `403` error given that the `*.js` file does not have the correct permissions and stuck in `Loading...`.

Best,
Antonio

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by antonionardella** [comment]
Is it possible that the issue is running `sudo zammad run rake zammad:package:post_install` with sudo as user, instead of running the command directly as root user?

**Comment by rolfschmidt** [comment]
Hi @antonionardella ,

hmm, interesting. Actually never had issues with that yet, but the post_install command is quite new.

Can you debug the issue more and provide me the output of this?

```
# Test 1

localadm> sudo zammad run rails r "pp ::Package.app_package_installation?"
localadm> sudo chmod 644 app/assets/javascripts/app/views/user.jst.eco
localadm> stat -c "%a %n" app/assets/javascripts/app/views/user.jst.eco
localadm> sudo zammad run rake zammad:package:bundle_install
localadm> stat -c "%a %n" app/assets/javascripts/app/views/user.jst.eco
localadm> sudo zammad run rake zammad:package:migrate
localadm> stat -c "%a %n" app/assets/javascripts/app/views/user.jst.eco
localadm> sudo zammad run rake zammad:package:precompile
localadm> stat -c "%a %n" app/assets/javascripts/app/views/user.jst.eco

# Test 2

localadm> sudo chmod 644 app/assets/javascripts/app/views/user.jst.eco
localadm> stat -c "%a %n" app/assets/javascripts/app/views/user.jst.eco
localadm> sudo zammad run rake assets:precompile
localadm> stat -c "%a %n" app/assets/javascripts/app/views/user.jst.eco
```

I never used the sudo method way. Normally I'm always root and use zammad run. Do you have access to the root user and can verify if it would work if you do it that way?

**Comment by antonionardella** [comment]
Hi @rolfschmidt,

sure, let me rollback the staging VM and get you the outputs, yes I also have access to the root user and I can repeat the same thing there.

Let me get back to you with this information

**Comment by antonionardella** [comment]
So, I installed the package using the Package Management in the GUI and then here the result of the commands as sudo

## Test 1
```
sudo zammad run rails r "pp ::Package.app_package_installation?"
sudo chmod 644 /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
stat -c "%a %n" /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
sudo zammad run rake zammad:package:bundle_install
stat -c "%a %n" /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
sudo zammad run rake zammad:package:migrate
stat -c "%a %n" /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
sudo zammad run rake zammad:package:precompile
stat -c "%a %n" /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
```
I also added
`stat -c "%a %n" /opt/zammad/public/assets/application-e28f534d6bdd371057daf4796855af6bd0bd5a7cc08529b72951028d4d4fda5e.js`
and
`stat -c "%a %n" /opt/zammad/public/assets/application-e28f534d6bdd371057daf4796855af6bd0bd5a7cc08529b72951028d4d4fda5e.js.gz`
as these are the files which are then loaded by the browser and you can see the result is `640` for both of them.

After a restart the expected `403` error since the `.js` and `.js.gz` files have the wrong permissions.
![image](https://github.com/user-attachments/assets/e3dcf096-0730-4c06-9c46-32cc6f4a42c4)
![image](https://github.com/user-attachments/assets/787eee61-2e7a-439f-8f17-388f13c6e52d)


## Test 2
Then I rolled back the VM and did the other commands
```
sudo chmod 644 /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
stat -c "%a %n" /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
sudo zammad run rake assets:precompile
stat -c "%a %n" /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
```

Also here I added
`stat -c "%a %n" /opt/zammad/public/assets/application-e28f534d6bdd371057daf4796855af6bd0bd5a7cc08529b72951028d4d4fda5e.js`
and
`stat -c "%a %n" /opt/zammad/public/assets/application-e28f534d6bdd371057daf4796855af6bd0bd5a7cc08529b72951028d4d4fda5e.js.gz`

As expected permissions are set to `640` again
![image](https://github.com/user-attachments/assets/32d3dd2b-aa5a-45e9-b300-8810e7190bb5)

## Test 3
I rolled back the VM again and redid the `Test 1` as root

```
zammad run rails r "pp ::Package.app_package_installation?"
chmod 644 /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
stat -c "%a %n" /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
zammad run rake zammad:package:bundle_install
stat -c "%a %n" /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
zammad run rake zammad:package:migrate
stat -c "%a %n" /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
zammad run rake zammad:package:precompile
stat -c "%a %n" /opt/zammad/app/assets/javascripts/app/views/user.jst.eco
```

And again added
`stat -c "%a %n" /opt/zammad/public/assets/application-e28f534d6bdd371057daf4796855af6bd0bd5a7cc08529b72951028d4d4fda5e.js`
and
`stat -c "%a %n" /opt/zammad/public/assets/application-e28f534d6bdd371057daf4796855af6bd0bd5a7cc08529b72951028d4d4fda5e.js.gz`
Permissions are again at `640`
And after a restart we have our `403` error and Zammad is stuck at loading
![image](https://github.com/user-attachments/assets/f04fa511-e9f1-4c3d-96f4-8fb2dde06bed)
![image](https://github.com/user-attachments/assets/f1d4b0b1-5ee3-446d-ba99-1082cd646204)


The solution to this is to `chmod 644` the `.js` and `.js.gz` files under `/opt/zammad/public/assets` and then Zammad loads fine again.

Best,
Antonio

**Comment by antonionardella** [comment]
Additionally, the same thing happened with custom `.css` files 
![image](https://github.com/user-attachments/assets/22851cd0-02ad-46a1-9cee-d8e11ecf816d)

Also with the files in `/opt/zammad/public/assets/frontend/vite/assets/*`
So, there is something going on with permissions

Sources:
- https://community.zammad.org/t/mobile-version-not-loading-loading-failed-for-the-module-with-source-vite/14199
- https://community.zammad.org/t/custom-css-foes/13555/5
https://community.zammad.org/t/custom-css-foes/13555/5?u=skip

**Comment by rolfschmidt** [comment]
But does it then even have a relation to the package? It will also do that without the package right?

**Comment by antonionardella** [comment]
Now that I think about it, it is package independent, yes.

**Comment by rolfschmidt** [comment]
I have no clue. Never saw that. Maybe there are some ownership problems in your zammad dir? Do all directories and files in tmp, tmp/cache, public, public/assets have the zammad user set? (`ls -al`)

How do the directory permissions look like?

```
root> stat -c "%a %n" public/
root> stat -c "%a %n" public/assets/
root> stat -c "%a %n" tmp/
root> stat -c "%a %n" tmp/cache/
```

I wonder how the precompile decides the file permissions for the output.

**Comment by antonionardella** [comment]
755 on all directories
![image](https://github.com/user-attachments/assets/dff6393d-6137-4eea-8f24-13d547bcb1cc)

ls -la public
![image](https://github.com/user-attachments/assets/a0886129-3292-4b29-ac2c-c004d13e3590)


ls -la public/assets
![image](https://github.com/user-attachments/assets/ace73b9d-9b21-4adb-ba53-272e74fa3b2a)

ls -la /tmp
![image](https://github.com/user-attachments/assets/97250d82-a8e1-4d47-a822-866d168f41d7)

ls -la /tmp/cache
![image](https://github.com/user-attachments/assets/4bd24f75-e6d9-4a41-bdc9-83b69f233c7d)

**Comment by rolfschmidt** [comment]
What's the umask of your zammad and superuser?

```
ubuntu-rs@ubuntu-rs:/workspace/git_zammad/zammad$ umask
0022
ubuntu-rs@ubuntu-rs:/workspace/git_zammad/zammad$ sudo su
root@ubuntu-rs:/workspace/git_zammad/zammad# umask
0022
```

**Comment by antonionardella** [comment]
0007 for localadm
0027 for root
![image](https://github.com/user-attachments/assets/59f92837-0391-4f60-b5d5-44be88a77062)

**Comment by rolfschmidt** [comment]
You should try to fix the root to `umask 0022` and test again.

**Comment by antonionardella** [comment]
Thanks for your time, let me check with my team what is going on then.
