### ISSUE TITLE
Error message is not translatable: Cannot set default at signup when role has admin permissions.

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5340]
### Used Zammad Version

6.3.1-1725517875.52891758.bookworm

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian 12 on WSL2
- Database + version:  psql
- Elasticsearch version: es7
- Browser + version: any

### Actual behaviour

When trying to enable "default on signup" for an admin role I get an error message in English.

### Expected behaviour

When trying to enable "default on signup" for an admin role I get an error message in my language.

### Steps to reproduce the behaviour

Try to enable "default on signup" for the admin role:

![image](https://github.com/user-attachments/assets/e6b5256c-8945-440b-815f-bb92968fc6d0)

![image](https://github.com/user-attachments/assets/5d253138-442e-44f9-b1ec-a6e9fa6f287d)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by YetAnotherGerrit** [comment]
I searched translations.zammad.org to see if it was merely missing, but I couldn't find it there.

**Comment by mantas** [comment]
Unfortunately this issue is hard to fix properly. We'll address it properly when improving overall error wording & rendering. Sorry.
