### ISSUE TITLE
Core Workflow allows multiple options in “set fixed to” with a single selection field

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#5345]
### Used Zammad Version

6.3.1 (stable)

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge, v. 128.0.2739.67 (official build) (64-bit)

### Actual behaviour

Having a single selection field, the configuration in Core Workflow allows multiple options to be set under set fixed to, all of which are executed simultaneously and may have some undesirable side effects depending on the settings configured. 

### Expected behaviour

Having a single selection field, the configuration in Core Workflow should allow only for one option to be set under set fixed to.

### Steps to reproduce the behaviour

1) create a single select field with multiple options 
2) create a Core Workflow with "set fixed to" set to several of the created options
3) open the creation mask and trigger the conditions which will execute the CW created in step 2. 

Current workaround (as discussed in the support ticket: replace "set fixed to" with "remove option". 

### Support Ticket

Ticket#10158299

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
https://github.com/zammad/zammad/issues/4303
