### ISSUE TITLE
Send Trigger and Scheduler Notification Email/SMS to single user

### ISSUE THREAD

**Issue by schroederb1** [zammad/zammad#535]
Description: I want to send an email throu the trigger mechanism to a freely chosen mail address (eg. mail@domain.tld) but email triggers are just avaliable for owner, customer and every agent. This should be more flexible.

Reproducable: Yes. Open http://zammad_url:zammad_port/#manage/trigger and choose Change -> Notification -> E-Mail. You can choose just owner, customer and every agent.

A fix would be appreciated.

**Comment by Miterion** [comment]
Is there any update or progress on this?
