### ISSUE TITLE
Rich text and text mails with Base64 encoded body are not decoded correctly for PGP encrypted and signed mails.

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5351]
### Used Zammad Version

6.3

### Environment

- Installation method: SaaS
- Operating system: any
- Database + version: any

### Actual behaviour

If a mail, which is PGP encrypted and signed, is sent to Zammad with the following content parameters for the body

Content-Type: text/html;charset=“utf-8” 
Content-Transfer-Encoding: base64
**=> Base64 body is decoded.**

![Bildschirmfoto 2024-09-25 um 12 36 10](https://github.com/user-attachments/assets/b9f75074-ba7c-47a0-94db-aedf69af23f1)

Content-Type: text/plain; charset=“utf-8” 
Content-Transfer-Encoding: base64
**=> Base64 body isn't decoded.**

![Bildschirmfoto 2024-09-25 um 12 36 47](https://github.com/user-attachments/assets/734ecb79-f9be-43df-8812-862edca80a0e)

![Bildschirmfoto 2024-09-25 um 12 37 20](https://github.com/user-attachments/assets/b9942124-d9dc-4a6f-96f0-61609b6220c0)

![Bildschirmfoto 2024-09-25 um 12 49 56](https://github.com/user-attachments/assets/44c56fad-92a4-476e-96cb-e3e47a49a21a)

Q29udGVudC1MYW5ndWFnZTogZGUtREUNCkNvbnRlbnQtVHlwZTogdGV4dC9yaWNoOyBjaGFyc2V0
PSJ1dGYtOCINCkNvbnRlbnQtVHJhbnNmZXItRW5jb2Rpbmc6IGJhc2U2NA0KDQpUZXN0DQoNCg==

### Expected behaviour

That text and rich-text Base64 bodys are also decoded correctly, if the mail is PGP encrypted and signed.

### Steps to reproduce the behaviour

Send a PGP encrypted and signed mail to Zammad with following content parameter for the body

Content-Language: de-DE
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64

### Support Ticket

Ticket#10146000

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @MarkusHeld. Please provide test mails, thanks.

**Comment by tschaefer** [comment]
The used email client (MUA) is not RFC3156 compatible. Any mime-type (email part) has to start with `content-type` followed by optional content information.

The decoded base64 message again contains the content meta information.
```
echo 'Q29udGVudC1MYW5ndWFnZTogZGUtREUNCkNvbnRlbnQtVHlwZTogdGV4dC9yaWNoOyBjaGFyc2V0
PSJ1dGYtOCINCkNvbnRlbnQtVHJhbnNmZXItRW5jb2Rpbmc6IGJhc2U2NA0KDQpUZXN0DQoNCg==' | base64 -d
Content-Language: de-DE
Content-Type: text/rich; charset="utf-8"
Content-Transfer-Encoding: base64

Test
```

**Comment by tschaefer** [comment]
The parsing and decoding of the base64 encoded body is fixed with the commit https://github.com/zammad/zammad/commit/8a6e4a551b928a17d447ecd29686b56beca5a291 and backported to stable with the commit https://github.com/zammad/zammad/commit/fe37d1408a3c0810b38ed8125b570a5bf1e7c8d3.
