### ISSUE TITLE
Apollo client returns an error about exceeding max complexity of the query

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad#5353]
### Used Zammad Version

6.3

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

If the user triggers a complex enough GraphQL query via the frontend, it returns the following error:

```
ApolloError: Query has complexity of #####, which exceeds max complexity of 10000
```

### Expected behaviour

The user is not able to trigger complexity errors just by using the frontend, this should be reserved for API usage.

### Steps to reproduce the behaviour

1. Have a ticket with multiple articles.
2. Try to access it via mobile view, but include the ID of a specific article to scroll to it. E.g. via `/mobile/tickets/<ticketId>#article-<articleId>`
3. This will trigger more articles part of the query that (hopefully) results in the reported error. Frontend shows error 500, but the specific error message is present in the browser console.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
This does not always fail on my local system, and it seems to depend on how the queries are batched together by the apollo batch link.

### Error did  not occur:

![Image](https://github.com/user-attachments/assets/6bd2a460-10f1-4142-9631-1dd0bad16a8a)
![Image](https://github.com/user-attachments/assets/280b9cd6-638a-4fd0-8c88-8fe8768c999e)

Here the article queries were executed in a separate batch.

### Error did occur:

![Image](https://github.com/user-attachments/assets/651e02ba-a561-4959-a6c1-c9281e181493)
![Image](https://github.com/user-attachments/assets/5cc77668-ab95-4a45-9c0e-3c0f37105760)

This time, the article queries were batched together with other queries in one call.

### Problem

We use `BatchHttpLink` with this configuration:
```
const batchLink = new BatchHttpLink({
  ...connectionSettings,
  batchMax: 5,
  batchInterval: 20,
})
```

How the operations are batched together is not deterministic as it seems to depend on exact timing. There seems to be no way to influence this via config: https://www.apollographql.com/docs/react/api/link/apollo-link-batch-http/

However, the complexity limit is counted against the entire batch.

### Solution / Workaround

Not sure, there seems to be no ideal option:

- Turn off batching (loose performance gains)
- Reduce `batchMax` - make it less probable, but no guarantee
- Increase max allowed complexity on the server

@dominikklein @dvuckovic opinions?

**Comment by dvuckovic** [comment]
Another approach could be to simply decrease the paging size of the query, as this results in lower overall complexity. I was able to make it go away with requesting only 50 articles at a time.

**Comment by mgruner** [comment]
That is also possible, true. But we do have `pageSize: 100` in several places in both the mobile and the desktop views. For now I'd probably rather double the allowed complexity.

@dominikklein any opinions?
