### ISSUE TITLE
The save button is visible in the mobile ticket detail view for an not dirty form

### ISSUE THREAD

**Issue by kingmanfri** [zammad/zammad#5356]
### Used Zammad Version

6.3

### Environment

- Installation method: Helm chart
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

"Ticket updated successfully" toaster message appear

### Expected behaviour

Do not show "Ticket updated successfully" toaster message for no change at all

### Steps to reproduce the behaviour

1. Open Zammad Mobile version
2. Create a ticket
3. Click button "Add reply" and insert a note and click "Save"
4. Click button "Add reply" to insert a note. Do not insert nothing and click Cancel button
![image](https://github.com/user-attachments/assets/df5e6a5a-def5-458c-9fda-363af1d3c08b)

5. Click on Save button appearing in the new screen.
6. Toaster message apper with no changes at all
![image](https://github.com/user-attachments/assets/a889f0fa-2bfb-4e7a-b6b7-9ea8e6df4eba)

8. 

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by dominikklein** [comment]
Thanks for the hint, normally the "Save" button should not be present, when there is nothing to save :-)

**Comment by dominikklein** [comment]
https://github.com/zammad/zammad/commit/004cffd611fee7ac99c2d21ce2e7b0843959b686
