### ISSUE TITLE
CSV import of users breaks with "undefined methof `[]` for nil:NilClass"

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#5360]
### Used Zammad Version

6.3.1 stable

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge, v.129.0.2792.65 (Official Build) (64-Bit)

### Actual behaviour

When importing users via .csv files, the ID gets generated when the user profile is successfully imported, and the login gets generated, if not provided in the import file. However, having only the e-mail attribute provided in the import file does not allow the import process to start. If only the e-mail is given, no import can start. If, however, the e-mail is provided also for the login, the import starts. 

If attributes like ID and login are left blank (with e-mail provided), the system gives back the following error: 
undefined methof `[]` for nil:NilClass

### Expected behaviour

When importing users in Zammad via .csv files, the following rules are to be followed: 

1) the id attribute (column) should be left blank or removed entirely;

2) the firstname and lastname attributes are required; and any other columns may be safely omitted as long as each row has the same number of fields (commas). 

So, if no ID and login are given, the import should be able to run (properly formatted with commas etc.)

### Steps to reproduce the behaviour

1) download the sample user file from Zammad (or create your own file)
2) edit it so, that the user has the e-mail, but no id or login attribute provided
3) try to import it

<img width="412" alt="image" src="https://github.com/user-attachments/assets/4db67c8d-75cc-405c-8d4e-d50d8543acb6">

[user sample.csv](https://github.com/user-attachments/files/17248039/user.sample.csv)

### Support Ticket

Ticket#10162340

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
side effect of https://github.com/zammad/zammad/issues/5362
