### ISSUE TITLE
Fix behaviour of array values in CSV export/import

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#5362]
### Used Zammad Version

6.4

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

Because of historic reasons array values are listed in new lines with two empty columns in the beginning. Which is not common or CSV way.

```
name,note,members
Zammad GmbH,"asdasd",nicole.braun@zammad.org
"","",aaa@bbb.com
```

Name and note indicate 2 empty columns. Because of that the member is added to the previous row.

### Expected behaviour

Values should get separated by `~~~` and be combined in one line.

```
name,note,members
Zammad GmbH,"asdasd","nicole.braun@zammad.org~~~aaa@bbb.com"
```

### Steps to reproduce the behaviour

E.g. Import export organization with members.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mgruner** [comment]
@rolfschmidt is this related to #5360?

**Comment by rolfschmidt** [comment]
> @rolfschmidt is this related to #5360?

No, don't think so.

**Comment by rolfschmidt** [comment]
> > @rolfschmidt is this related to #5360?
> 
> No, don't think so.

Actually you were right, these are related and will be fixed together.
