### ISSUE TITLE
Searching for a ticket with a keyword from an checklist item is not working

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5364]
### Used Zammad Version

6.4

### Environment

- Installation method: docker
- Operating system (if you're unsure: `cat /etc/os-release` ): Nobara 40
- Database + version:  psql
- Elasticsearch version: es 8+
- Browser + version: Chromium

### Actual behaviour

When searching for a ticket and using a keyword that is only in a checklist item, I do not find the ticket.

### Expected behaviour

When searching for a ticket and using a keyword that is only in a checklist item, I find the ticket.

### Steps to reproduce the behaviour

Add an uncommon keyword to a checklist item. Search for the ticket.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
As discussed in the original issue for the checklist implementation, we wanted to start simple with checklists. Therefore, this is no bug.

@dominikklein ping

**Comment by mantas** [comment]
As a side note, should checklist name show up in search as well? Or only checklist item text?

Either way, it’s not a bug. But it’d be super easy to add :)

**Comment by dominikklein** [comment]
I agree in general it's not a bug. But something which is maybe not easy to understand from user perspective, that the text from the ticket checklists are not searchable.
