### ISSUE TITLE
Checklist Feature removes content when I Try to click in the text field again

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#5366]
### Used Zammad Version

6.46.4.0-alpha-1727869020.a363b68c.bookworm

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 12.7
- Database + version:  psql (PostgreSQL) 17.0 (Debian 17.0-1.pgdg120+1)
- Elasticsearch version: "number" : "7.17.24",
- Browser + version: Edge and Opera

### Actual behaviour

When I create a new checklist Item, I click in the text field, write something.
And when I click again in the text field with the mouse, the text I have written previously is removed.

### Expected behaviour

I would expect that I can continue writing where I stoped.

### Steps to reproduce the behaviour

- Create a ticket
- Click on the Checklist
- Click on add Item 
- Write the name of the Item and then click on the text field before saving

More detail in the following screencast:
[Screen Recording (03.10.2024 11-30-33).wmv.zip](https://github.com/user-attachments/files/17242157/Screen.Recording.03.10.2024.11-30-33.wmv.zip)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@Bozo0511 I can not reproduce it like you described and I also don't understand what you are doing in the video. For sure befor the changes from the current sprint, the items are not saved when you are clicking outside the field. But when you write somethign and then click on the text inside the input it should always be working, also before.

But In the end I think we can close this bug report or?

**Comment by dominikklein** [comment]
@dvuckovic This is the related issue.

**Comment by mantas** [comment]
@dvuckovic was able to replicate it after all. It's now fixed in soon-to-be-merged !8938
