### ISSUE TITLE
Conditional API requests

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5369]
**What**

Add the possibility to use the `/api/v1/users/search` and the `/api/v1/organizations/search` endpoints with "conditions" to bypass the use of elasticsearch, similar to the ticket search endpoint.

**Use Cases**

- I want to build a customer UI that shows a list of users based on specific criteria
- I want to find a user id via API search based on a customer user attribute "uuid"

In both cases I need the information based on the live data (in SQL) and a delay from ES indexing is not suitable

**Acceptance criteria**

Alternatively to
`curl --location 'http://localhost/api/v1//users/search?query=uuid:12345' --header 'Authorization: Token token=<token>'`

also this variant will work:

```bash
curl --location 'http://localhost/api/v1//users/search' \
--header 'Content-Type: application/json' \
--header 'Authorization: Token token=<token>' \
--data '{
"condition": {
"user.uuid": {
"operator": "is",
"value": "12345"
}
},
"limit": 1
}'
```

With the difference that the second approach does not use the ES index, but a SQL approach instead. Similar to like `http://localhost/api/v1/tickets/search` behaves.

**Comment by rolfschmidt** [comment]
Should work with 6.5
```
ubuntu-rs@ubuntu-rs:/workspace/git_zammad/zammad$ curl -s -XPOST -H 'Content-Type: application/json' -H 'Authorization: Token token=xx' -d '{ "condition": { "user.uuid": { "operator": "is", "value": ['1234'] } } }' "https://xxx.zammad.com/api/v1/users/search?sort_by=id&order_by=asc&full=true" | jq .record_ids
[
  2
]
```

relates https://github.com/zammad/zammad/issues/5384
