### ISSUE TITLE
Define groups for text modules

### ISSUE THREAD

**Issue by martini** [zammad/zammad#537]
Define groups for text modules, only certain text models should appear in certain groups.

**Comment by rkaldung** [comment]
👍

**Comment by petervanbeugen** [comment]
+ Channels
Define channels for text modules, only certain text models should appear in certain channels.

**Comment by johan12345** [comment]
When text modules can be assigned to groups, there could also be a "group admin" user who is allowed to edit and add text modules for a specific group.

**Comment by dennykorsukewitz** [comment]
The feature 'group-dependent text modules' was added: https://github.com/zammad/zammad/commit/c788c3e053abe4f96fc5e2597c527632e341fd9e

> Define groups for text modules, only certain text models should appear in certain groups.



Available in version 3.1
