### ISSUE TITLE
Random behavior on time based conditions in action triggers

### ISSUE THREAD

**Issue by michiphp** [zammad/zammad#5371]
### Used Zammad Version

5.3

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Rocky Linux
- Database + version:  postgresql 9.3
- Elasticsearch version: 7.17
- Browser + version: chrome 83, safari 14, firefox 105

### Actual behaviour

when creating a trigger, that is triggered by an action, namely ticket update, the time based condition, say only fire if last customer contact is two weeks ago (relative) is not respected at all. Instead it fires completely random on many tickets, even tickets that are 2 days old.

### Expected behaviour

respect the time condition.

### Steps to reproduce the behaviour

create trigger,
action,
selective,
action ticket update
condition last customer contact before two weeks ago
add internal note: „trigger fired“
save,
update a ticket where last customer contact was > two weeks ago. 
Nothing happens. 
wait some days and realise the note is added on many tickets that do not meet the requirement 

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment]
I wasn't able to reproduce this in the latest version, by following steps above. The trigger is correctly fired on older tickets only, newer are ignored.

Trigger:

<img width="963" alt="Screenshot 2024-10-09 at 07 10 40" src="https://github.com/user-attachments/assets/b9cd9b02-9acc-4abe-ad8c-9ede48ad3a85">

Two week old ticket update:

<img width="626" alt="Screenshot 2024-10-09 at 07 10 21" src="https://github.com/user-attachments/assets/d98d319e-93e5-4113-b538-e228200ca1ec">

One week old ticket update:

<img width="631" alt="Screenshot 2024-10-09 at 07 13 14" src="https://github.com/user-attachments/assets/b763192b-f46f-4570-abae-88cc823b17ec">

Perhaps you can update your system first and try again? Feel free to reopen this issue with more information.
