### ISSUE TITLE
"Invalid password, it must be at least undefined characters long!" 

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#5373]
### Used Zammad Version

6.3.1

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

The minimum length of a password is set to 10 characters in Admin > Settings > Security > Password 
Using the “Forgot Password” link, a user creates a new password that is too short. 
The following error is shown:
_"Invalid password, it must be at least undefined characters long!"_ 

![image](https://github.com/user-attachments/assets/a4ee48c6-a2ad-4042-929d-dea6726ac712)

### Expected behaviour

The minimum length of a password is set to 10 characters in Admin > Settings > Security > Password 
Using the “Forgot Password” link, a user creates a new password that is too short. 
The error message should state exactly how long the password should minimally be. 

### Steps to reproduce the behaviour

* Set the minimum length of a password to 10 characters in Admin > Settings > Security > Password
* Use the “Forgot Password” link to set a new password.
* Make the new password shorter than the configured minimum.
* Be baffled by the word “undefined” for the expected length of the new password.

### Support Ticket

Ticket#10163381

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Maybe related to this one here? https://github.com/zammad/zammad/issues/5327

**Comment by fliebe92** [comment]
Fixed in Zammad 6.4 with #5327
