### ISSUE TITLE
WhatsApp-Channel don't use outgoing http-proxy when communicating to meta

### ISSUE THREAD

**Issue by byPARSE** [zammad/zammad#5374]
### Used Zammad Version

6.3.1

### Environment

- Installation method: on prem
- Operating system (if you're unsure: `cat /etc/os-release` ): not relevant
- Database + version:  not relevant
- Elasticsearch version: not relevant
- Browser + version: not relevant

### Actual behaviour

The WhatsApp-Channel communicate to Meta (graph.facebook.com) without using the proxy-settings set under Settings->System->Network.

### Expected behaviour

When proxy is set all the http/s protocol using-modules have to use the proxy for outgoing communication. In hardened environments the out-/incoming network-communication has to go exactly-predefined ways. 

### Steps to reproduce the behaviour

Setup WA-Channel, set a valid proxy under Settings->System->Network and use tcp-sniffers like tcpdump to see that the outgoing communication for WA don't use the set proxy.

### Support Ticket

[Ticket#10160841](https://support.zammad.com/#ticket/zoom/161109)

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by tschaefer** [comment]
The named setting is only evaluated by an internal library.

@byPARSE You can verify that TLS proxying for a WA channel is working in general by setting the environment `http_proxy` on Zammad start.

**Comment by tschaefer** [comment]
Setting the environment variable `http_proxy` fixes the issue (confirmed by the client, see [Ticket#161109](https://support.zammad.com/#ticket/zoom/161109)).

Zammad should evaluate the named environment variables `http_proxy`, `https_proxy`, and `no_proxy`. These values should take precedence over the [internal settings](https://admin-docs.zammad.org/en/latest/settings/system/network.html).  The internal settings are not suitable for third-party libraries - `hen egg problem`.
