### ISSUE TITLE
password reset message template failure

### ISSUE THREAD

**Issue by abenrob** [zammad/zammad#538]
When a user resets their password, they receive an email confirming this action.
It looks like this:

![zammad_password_reset](https://cloud.githubusercontent.com/assets/3422185/21137792/81991208-c12b-11e6-95db-16bd52dc9cce.png)

Which is not correct. The *product_name* is set for out system.

**Comment by abenrob** [comment]
cc @gerbsen

**Comment by martini** [comment]
Thanks! It's a duplicate of #468 - it's already fixed. :)

**Comment by abenrob** [comment]
Great - Thanks!

**Comment by martini** [comment]
JFI: If you use the Zammad Packages (RPM or DEB), just update the package. After a bugfix a new release is build automatically.
