### ISSUE TITLE
Missing attachment alert is shown if 'attachment' is written in the signature

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#5385]
### Used Zammad Version

6.3.1

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  [any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When I write an email and in the global signature is the word “attachment”, the pop-up "are you sure that you want to send this email without an attachment" appears in every email

### Expected behaviour

The signature should be excluded from this check.

### Steps to reproduce the behaviour

- Create a global signature:
Admin > Channels > email > signature

![2024-10-30 11_27_05-Zammad Helpdesk - Email – Opera](https://github.com/user-attachments/assets/142ca7aa-f8cf-4b67-9a5c-2efca3714087)

- Set the signature in the group
- write an email

![2024-10-30 11_31_21-Zammad Helpdesk - #64285 - tewst – Opera](https://github.com/user-attachments/assets/0dbc0df5-55b4-4b4c-a6f2-3db7ff6e10d1)

### Support Ticket

Ticket#10164427

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Might be related to the code that removes some elements before the check is done. AFAIR we're removing `blockquote` elements, but nothing else. Signatures are `div` elements with some data attribute... might be broken in old and new UI.

Untested fix:

```diff
diff --git a/app/assets/javascripts/app/lib/app_post/utils.coffee b/app/assets/javascripts/app/lib/app_post/utils.coffee
index 12195edfb2..71d3ad2fc6 100644
--- a/app/assets/javascripts/app/lib/app_post/utils.coffee
+++ b/app/assets/javascripts/app/lib/app_post/utils.coffee
@@ -1045,9 +1045,12 @@ class App.Utils
   @checkAttachmentReference: (message) ->
     return false if !message
 
-    # remove blockquote from message, check only the unquoted content
+    # remove blockquote and signatures from message, check only the unquoted content
     tmp = $('<div>' + message + '</div>')
-    tmp.find('blockquote').remove()
+
+    for elem in ['blockquote', 'div[data-signature="true"]']
+      tmp.find(elem).remove()
+
     text = tmp.text()
 
     matchwords = __('attachment,attached,enclosed,enclosure')
diff --git a/app/frontend/shared/composables/form/useCheckBodyAttachmentReference.ts b/app/frontend/shared/composables/form/useCheckBodyAttachmentReference.ts
index 1950f96471..1704ce67f4 100644
--- a/app/frontend/shared/composables/form/useCheckBodyAttachmentReference.ts
+++ b/app/frontend/shared/composables/form/useCheckBodyAttachmentReference.ts
@@ -11,9 +11,11 @@ const referenceMatchwords = __('attachment,attached,enclosed,enclosure')
 const removeQuotingFromBody = (body: string) => {
   const dom = domFrom(body)
 
-  // Remove blockquotes and images
+  // Remove blockquotes, signatures and images
   // To not detect matchwords which are not part of the user-written article
-  dom.querySelectorAll('blockquote, img').forEach((elem) => elem.remove())
+  dom
+    .querySelectorAll('blockquote, img, div[data-signature="true"]')
+    .forEach((elem) => elem.remove())
 
   // Return the modified HTML content as a string.
   return dom.innerHTML
```
