### ISSUE TITLE
Core Workflows dependent on Owner field being visible break tickets which are assigned to other groups

### ISSUE THREAD

**Issue by bahusafoo** [zammad/zammad#5386]
### Used Zammad Version

6.3.1-1729161509.67b236f6.jammy

### Environment

- Installation method: Package, This is Zammad version 6.3.1-1729161509.67b236f6.jammy
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 22.04
- Database + version:  psql (PostgreSQL) 14.13
- Elasticsearch version: 7.17.24
- Browser + version: Microsoft Edge 130.0.2849.56 (Official build) (64-bit)

![EX0](https://github.com/user-attachments/assets/54a3dff1-fe87-4883-b29f-21a0a421cc85)
![EX0_CustomerView](https://github.com/user-attachments/assets/8ec1dc23-2f6e-48c7-a63c-0d3441143d45)

### Actual behaviour

I suspect this is due to the hidden group field's value not being visible/considered to the core workflows.

With core workflows in place which add object field values based on group conditions, especially if one of those objects is set through a core workflow to be required, If a user outside of the owner group of a ticket goes to add notes they are blocked from submitting any updates.  

### Expected behaviour

Even if the current user is not a member of the tickets assigned groups, core workflows should be able to run based on the assigned group.

### Steps to reproduce the behaviour

Have a custom object 1 as a list object with several values available. 

Create a core workflow processing first that clears the values of Object 1.

Create a core workflow with selected conditions as "group is: Group B, Group C, Group D", and set the action to basically "add some of the options back to Object 1"

Create a core workflow that sets object 1 as required.

Create the ticket from a customer in Group A and assign it to group B.  Even though the core workflow is set to show custom object 1 if the group is group B, because the customer is not in Group B, they will never be able to see Object 1.  If object 1 is required, the customer can no longer submit updates through the web portal.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by bahusafoo** [comment]
I have attempted to add a show group core workflow in the mix, however, the customer is not shown the assigned group object despite this being added.  I believe this would also fix this issue, however as I understand it Zammad team's mentality is that this should always be hidden from the customer.  While I do disagree with that being the case 100% of the time (for example, we are using Zammad as an internal ticket system where customers being able to see where their ticket is assigned is actually preferable to them needing to call and ask), that is a separate matter.   I do believe core workflows should be corrected to calculate based on the group value, whether it displays to the customer or not.

**Comment by YetAnotherGerrit** [comment]
> customer in Group A
> customer is not in Group B

Can you elaborate what you mean by "is in group"? Customers are not in groups. Tickets are (or will be created) in a group.

Right now, this does not look like a bug to me, but a configuration issue. There are 3 ways on how to get help with that:
- [Zammad Community](https://community.zammad.org/)
- Via [Support-Contract](https://zammad.com/en/pricing) (included for SaaS-customers)
- Via [Consulting](https://zammad.com/en/services/professional-services)

**Comment by bahusafoo** [comment]
Yes, when the ticket is assigned to a group outside of the customer's org, core workflows no longer apply when they look at the ticket.  This causes diffferent selections to reset and everything.

If zammad's core workflows were to be able to consider the group even though it is not displayed to the customer, this would not happen.

This is clearly a bug.

**Comment by dominikklein** [comment]
Maybe you can try to use "saved conditions" instead for the customer situation.

**Comment by bahusafoo** [comment]
@dominikklein This in fact did work.  If this is by design, it could be a valid answer, however, I do feel like it could be argued that this is a workaround.  

I'll leave it up to the team to decide to close this or track as a bug.

**Comment by cautopartes** [comment]
To put it briefly: 
IMHO it is working as designed. I gave more detailed feedback in the corresponding ticket. From my view, this is more of a general question, or something we usually clarify in workshops or consulting, but no bug.
