### ISSUE TITLE
Too many requests happening in parallel when user refreshes page

### ISSUE THREAD

**Issue by twiggy** [zammad/zammad#5387]
### Used Zammad Version

6.2

### Environment

N/A

### Actual behaviour

When a user has many tickets open on their sidebar and then hits f5 this sends many requests to the backend potentially in parallel. this slows the server and on slower connections can cause impacts to other users. Monitoring overall server performance becomes a bit tricky as we see bursts of connections from our users. I'm not sure if Chrome's new suspended tabs are also contributing to this. I think our users like to leave tickets open on the left bar and I don't know if there is a way to 

![image](https://github.com/user-attachments/assets/27b988cd-d546-4088-abf2-bf3e401fddc6)

### Expected behaviour

Only load info when the user needs it, hover or click, or load information within a single backend request to not overload server. Or someother approach like loading the tickets with some delay between them.

### Steps to reproduce the behaviour

Open up a bunch of tickets and hit f5\refresh

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
This works as designed in the current desktop app variant and will be improved with the desktop rewrite.
It is not a bug.

> Zammad v6.2

You're outdated.
