### ISSUE TITLE
Add email address without importing historical emails

### ISSUE THREAD

**Issue by abenrob** [zammad/zammad#539]
I added an email account to be used as a channel. When connecting to the account, I was give no choice other than to **cancel** or **import emails**. As I had no choice, I imported, which then went back through all emails in the account (thousands) and migrated them (not copied, _migrated_) all to zammad. This took 4 hours, send of thousands of notifications and essentially shut down our site for the duration.

Add account without importing old emails should be an option.

**Comment by martini** [comment]
Hi @abenrob 

I agree, this would be a nice option.

One question, did you see a screen where Zammad was telling you that XXX emails will be imported?

 -Martin

**Comment by abenrob** [comment]
I did, but that screen underestimed the number of imports and didn't offer any alternatives. A silent import would have been better than nothing - import without the triggers, etc.

**Comment by imbehind** [comment]
Can someone please outline the default import from IMAP procedure? (or at least point to the code which does the import)

It looks like that it goes like this:

1. Reads email
2. Creates User
3. Not sure what happens after

Because, if I list users via API (GET /api/v1/users) it lists all current users including imported ones from IMAP. But, if I list tickets (GET /api/v1/tickets) it lists only the Welcome to Zammad ticket meaning it still has not created the tickets, and hopefully did not send notifications.

However, If I open user management and from there check Zammad from user perspective, I can see the ticket, along with Ticket#. Still Tickets are not searchable nor shown anywhere while still imporing.

Zammad was shut down mid import after reading this thread.

Please help!

**Comment by imbehind** [comment]
Please add the following options for migrating/importing IMAP/email:

1. Enable the admin to choose between COPY or MOVE (default is MOVE (!!!)) emails from IMAP
2. Enable the admin to enter a timestamp to enable functionality of importing from certain date/time onwards
3. Enable the admin to in-place configure (turn on/off) notifications and similar behaviour.

At least document the procedure in detail.

**Comment by martini** [comment]
Update: Now we implemented a solution to decide if you want to keep emails on server or not (currently via email expert settings).

Attention: The main reason why we do not keep this emails on server per default are just resource limits of the mail servers (usually for a productive environment your do not want to keep emails on server).  If you decide to keep it on server you need to take care for reaching mail server limit like quote or maximum count of messages/objects.

__If you decide to keep mail on server__ only **unseen** and **not already imported** (based on email message id) email get imported.

It's available on develop.

<img width="487" alt="screen shot 2017-07-20 at 14 27 31" src="https://user-images.githubusercontent.com/110226/28417237-a057a1cc-6d57-11e7-9e14-aaee9f833b3e.png">

**Comment by martini** [comment]
Feedback is welcome!

**Comment by martini** [comment]
Hi @imbehind  

> Can someone please outline the default import from IMAP procedure? (or at least point to the code which does the import)
>
> It looks like that it goes like this:
>
> 1) Reads email
> 2) Creates User
> 3) Not sure what happens after

Sorry, I just read this.

The procedure is:

1) reading first email from imap
2) parsing emails
3) check if all recipients are in Zammad (if not, create the recipients as customer)
4) create ticket or add email as follow up

-=> The 1-4 with the next email.

Note: 3) is to have all people know in Zammad and to make it possible to select them for new tickets or have them in autocompletion for e. g. Cc on writing email answers (last feature autocompletion in Cc is in implementation).

If you have questions, just let me know.

**Comment by imbehind** [comment]
@martini is this fix available in any subsequent stable version?

**Comment by martini** [comment]
Hi @imbehind 

https://github.com/zammad/zammad/issues/539#issuecomment-316695288 is available in current stable (Zammad 2.1). Just use the "email expert settings" and select "keep messages on server".

 -Martin

**Comment by koolninad** [comment]
Now how can I put back old emails back to Gmail ?

**Comment by MrGeneration** [comment]
Please do not hijack closed issues with your technical questions, consult the community: https://community.zammad.org
