### ISSUE TITLE
Taskbar uniqueness check leads to problems when old unexpected taskbar duplicates already exists

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#5390]
### Used Zammad Version

6.4.x

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

Currently, the new taskbar uniqueness check could lead to error messages during a ticket update or creation. This happens then because of an unexpected/unknown reason a duplicated taskbar entry for one ticket exists, which is also the first taskbar entry of one user (`Taskbar.where(user_id: ?).first`: https://github.com/zammad/zammad/blob/2ff52103122683904c08b7abde97dca29877e32d/app/controllers/concerns/creates_ticket_articles.rb#L147)

```
E, [2024-11-04T12:57:21.011644#4457-960400] ERROR -- : Validation failed: Key has already been taken (ActiveRecord::RecordInvalid)
app/controllers/concerns/creates_ticket_articles.rb:150:in `article_create'
app/controllers/tickets_controller.rb:284:in `block in update'
...
```

### Expected behaviour

Also when unexpected duplicated taskbar entries for one ticket from the past exist it should be possible to update/create tickets without any problems.

### Steps to reproduce the behaviour

- Create two taskbar entries for the same ticket via Rails-Console before the update to 6.4 (or without disabled validation?) for one user (user should not have any other entry).
- Then try to create an new ticket.

(It's a little bit difficult, because we really don't know how these duplicated entries are happening)

### Support Ticket

Ticket#10164758, Ticket#10164742, Ticket#10164830

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Affected customers bumped to 4. This is a blocker in my opinion. It makes people unable to work, at least partly and causes workarounds that may cause loss of drafts in the taskbar affected.

**Comment by t-shehab** [comment]
FYI: @YetAnotherGerrit @Mirtaaa
