### ISSUE TITLE
Data privacy task dialog confirmation field looses focus

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#5398]
### Used Zammad Version

6.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: MS Edge, v.130.0.2849.68 (Official Build) (64-Bit)

### Actual behaviour

When deleting users via User Management, you are led to the Data Privacy, where the instance requires the action to be confirmed with a specific word based on the language of the user interface ( f.e. English - DELETE, German - LÖSCHEN etc.). 

So if you do it via the above path and with German UI, the confirmation field will first be displayed as selected, then straight away as deselected and if you don't notice it and start typing (while holding down Shift) L (starting for "LÖSCHEN”), you will log yourself out. 

This happens because confirmation field looses focus after user-to-be-deleted details are loaded

However, this does not happen if you initiate the deletion from Data Privacy and not from the User Management. 

### Expected behaviour

When deleting users via the User Management, you are led to the Data Privacy, where I would expect the confirmation field to be preselected (since the user has already been selected in the previous step), not to have click once again in the confirmation field.

### Steps to reproduce the behaviour

1) Navigate to User Management (with German UI)
2) select a user for deletion --> click on the three dots on the right and click on "Delete"
3) the Data Privacy mask appears, the confirmation field is shortly shown as selected, then straight away as deselected and if you try to use the Shift + L(öschen) you will log yourself out.  

### Support Ticket

Ticket#10165012

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
This is more of a problem with the current Form in this dialog. And was already present before. But know with this new keyboard shortcut it's really visible.

Like Ivan described you lose the focus on the input field again when the dropdown of the autocomplete field is still open.
