### ISSUE TITLE
delete users and tickets

### ISSUE THREAD

**Issue by abenrob** [zammad/zammad#540]
Due to the mass over-importation mentioned in #539, I now have thousands of tickets, and many hundreds of users who I do not want in the support db. How can I completely get rid of 

1. a user and all their associated assets (including tickets)
2. a large group of tickets and the associated assets

The bulk actions in the UI are too slow, and can only close tickets. I'd really prefer the SQL to do non-breaking housekeeping...

**Comment by macnibblet** [comment]
What about deleting users ?

**Comment by MrSnoozles** [comment]
Deleting users would be possible with the rails console too. But I agree, being able to delete users is essential. Especially since users are created automatically and stay in the system, even if we mark the ticket as Spam. So for now we unfortunately have many "Mr. Cheap Via*ra" users in our system.

**Comment by MDXDave** [comment]
As zammad is advertised as ''zendesk alternative'', it would be really useful to delete and block users:
![image](https://user-images.githubusercontent.com/6099976/28599335-13b76c8c-71aa-11e7-96b4-243bd1c4f398.png)

![image](https://user-images.githubusercontent.com/6099976/28599343-1e21967a-71aa-11e7-8f7a-d14c1acf2d85.png)

It think the delete action should be accessable from the ticket view.

**Comment by dawnstrider** [comment]
Are there any plans on implementing this via the UI any time soon? I need this so badly.. I have misconfigured LDAP syncs, SPAM users and test users in the system which have to go.

**Comment by thorsteneckel** [comment]
This will get implemented in the scope of #2074 and is WIP - so I'll close this as a duplicate. Feel free to subscribe to the other issue to get notified about our progress 🚀
