### ISSUE TITLE
Type Error in report page

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#5402]
### Used Zammad Version

6.4.0-1731012857.f43894dd.focal

### Environment

- Installation method: package
- Operating system: Ubuntu 20.04
- Database + version: postgresql
- Elasticsearch version: 7.17

### Actual behaviour

Yesterday I can open the system report page. Today the error **no implicit converion of String into Integer** is shown

![Image](https://github.com/user-attachments/assets/a98ad284-ed92-47eb-88eb-55972178cd12)

> E, [2024-11-10T11:04:48.054154#3296-181660] ERROR -- : no implicit conversion of String into Integer (TypeError)
> app/models/system_report/plugin/hardware.rb:15:in `dig'
> app/models/system_report/plugin/hardware.rb:15:in `total_memory'
> app/models/system_report/plugin/hardware.rb:8:in `fetch'
> app/models/system_report.rb:42:in `block in fetch_system_report'
> app/models/system_report.rb:29:in `each'
> app/models/system_report.rb:29:in `fetch_system_report'
> app/models/system_report.rb:10:in `fetch'
> app/controllers/system_report_controller.rb:11:in `index'
> app/controllers/application_controller/has_download.rb:17:in `block (4 levels) in <module:HasDownload>'
> app/controllers/application_controller/has_download.rb:16:in `block (3 levels) in <module:HasDownload>'
> app/controllers/application_controller/has_download.rb:15:in `block (2 levels) in <module:HasDownload>'
> app/controllers/application_controller/handles_transitions.rb:16:in `handle_transaction'
> I, [2024-11-10T11:04:48.062388#3296-181660]  INFO -- : Completed 500 Internal Server Error in 13136ms (Views: 1.8ms | ActiveRecord: 12812.9ms | Allocations: 45313)
> I, [2024-11-10T11:04:53.188924#3397-180040]  INFO -- : execute Channel.fetch (try_count 0)...

### Expected behaviour

No error, the system report should be shown

### Steps to reproduce the behaviour

Open the report page in Admin Panel

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
Hi @Dennis1993 ,
can you send the following output via email? I would be interested what causes the error:

```
root> zammad run rails r "pp SystemReport::Plugin::Hardware.new.total_memory"
root> zammad run rails r "pp SystemReport::Plugin::Hardware.new.send(:binary_path)"
root> zammad run rails r "pp SystemReport::Plugin::Hardware.new.send(:execute)"
```

to support@zammad.com with a link to this issue and addressed to Rolf.

**Comment by Dennis1993** [comment]
Of course, I have sent you the mail with my output.
Thank you! :)

**Comment by rolfschmidt** [comment]
Thx @Dennis1993 for the debug data (Ticket#10165439). We will fix it soon.
