### ISSUE TITLE
Outdated recipients in Zammad templates due to session cache

### ISSUE THREAD

**Issue by SamuelPlentz** [zammad/zammad#5404]
### Used Zammad Version

6.3.1-1725883330.e18fb1f7.focal

### Environment

- Installation method: package
- Operating system: Ubuntu 20.04.6
- Database + version: postgresql (unsure about version)
- Elasticsearch version: (unsure about version)
- Browser + version: Firefox 130

### Actual behaviour

When an agent modifies the recipients (CC field) of a template in Zammad, and another agent uses this template, our tests indicate that the old recipients — those that were valid at the beginning of the session — are still being used. Refreshing the Zammad page resolves the issue.

### Expected behaviour

When an agent updates the recipients (CC field) of a template in Zammad, any other agent using this template should see the updated recipients immediately, without needing to refresh the Zammad page. The changes should be reflected across all active sessions in real time.

### Steps to reproduce the behaviour

- Agent A logs into Zammad and opens a ticket or starts a new session where they can select and use templates.
- Agent B logs into Zammad and edits a template, modifying the recipients in the CC field.
- Agent A, without refreshing the page, uses the same template.
- Observe that Agent A still sees and uses the old CC recipients, not the updated ones.
- Refresh Agent A's Zammad page.
- Observe that the updated CC recipients now appear correctly.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @SamuelPlentz. Thanks for the report. It's kind of unclear to us what you really mean and expect here. Could you please add some screenshots/screencast and show the behavior? Thanks a lot.

**Comment by SamuelPlentz** [comment]
Sorry, I thought the text would be enough.

You can create a template like this (```Admin``` > ```Templates```):
![Image](https://github.com/user-attachments/assets/f25fc495-400e-4a8d-9d97-5e7064d5d700)

And use it like this (```New Ticket``` > ```Select Template```)
![Image](https://github.com/user-attachments/assets/9b50516c-32c1-4c9c-b683-7463041ab88e)

First, user B modifies an existing template in ```Admin``` > ```Templates``` and changes the CC field from ```foo@example.de``` to ```bar@example.de```.
Then, user A uses this template in ```New Ticket``` > ```Select Template```, and the CC field still shows ```foo@example.de```.

**Comment by fliebe92** [comment]
Thanks for the fast response. I was exactly testing this and, for me, it works totally fine. No reload was needed. Are you sure your configuration is correct regarding the web socket support?

**Comment by SamuelPlentz** [comment]
> I was exactly testing this and, for me, it works totally fine.

Just to make sure: When you say "for me," it suggests that only one user was testing. However, there were two users involved in your test, correct? Because when I test with a single user, everything works fine on my end as well.

> Are you sure your configuration is correct regarding the web socket support?

I think it’s correctly configured. For example, when another user opens a ticket, I can immediately see his avatar lighting up in real-time. I’m not sure what else I should test here.

**Comment by fliebe92** [comment]
> > I was exactly testing this and, for me, it works totally fine.
> 
> Just to make sure: When you say "for me," it suggests that only one user was testing. However, there were two users involved in your test, correct? Because when I test with a single user, everything works fine on my end as well.
> 

Yes, correct. One user with admin permission to create/update templates for ticket creation and the second user is using the template. Everything's fine here.

**Comment by SamuelPlentz** [comment]
Thanks for clarification and support. 👍❤️

😕 Tell me if I can test anything or provide further information.

**Comment by dominikklein** [comment]
You could check in the browser console on the agent side, if some requests going on, when the admin user changes the template in the admin UI.

**Comment by SamuelPlentz** [comment]
Strange: During testing, I received two messages like this (which contain the updated information when I click on them):

![Image](https://github.com/user-attachments/assets/41bf1edd-a184-48cd-b878-746557ceac3a)

I also can’t reproduce the issue anymore, though I was able to for several users previously. The issue appears to be that message sending doesn't consistently work as expected. Don't know what to test or do here.

**Comment by fliebe92** [comment]
> Are you sure your configuration is correct regarding the web socket support?

This is what I meant with my note earlier today.

Please try to use our [community](https://community.zammad.org) and describe your issue there. Maybe another user could post the web server configuration etc. and you can compare it with yours, or there are another ideas how to solve your issue.

If you still think it's an issue in Zammad itself, feel free to ping us herewith more information on how to reproduce it, and we're able to re-open this one.

Thanks for your understanding.

**Comment by SamuelPlentz** [comment]
Thank you for your prompt responses and for taking the time to look into this. 🚀
Apologies for reporting what turned out not to be a real bug—it genuinely felt like one.
