### ISSUE TITLE
Missing history entries for time-event based triggers

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#5407]
### Used Zammad Version

6.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

The history is missing history entries for time-event based triggers:

* `trigger '%s' was performed because pending reminder was reached`
* `trigger '%s' was performed because ticket was escalated`
* `trigger '%s' was performed because ticket will escalate soon`

### Expected behaviour

The history should be complete.

### Steps to reproduce the behaviour

* Create a time-based trigger.
  * `Pending till has reached`.
* Create a new ticket and set a pending till.
* Wait until the trigger is executed.
* Check the ticket history afterward.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Like already discussed we would need to add the `perform_on` call again in the perform_changes:

https://github.com/zammad/zammad/blob/ad8b4770f850fa543d9ca3b3e0bab08ace5149f4/app/models/concerns/can_perform_changes.rb#L58

`performable.try(:performed_on, self, activator_type:)`
