### ISSUE TITLE
Selection of linked answers in the Knowledge Base drop-down menu is lost due to a focus trap

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#5411]
### Used Zammad Version

6.4

### Environment

- Installation method: any 
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge, v. 130.0.2849.80 (official build) (64-bit)

### Actual behaviour

While editing Knowledge Base articles and clicking on "Link answer", as depicted below:

![Image](https://github.com/user-attachments/assets/ef344e0f-8d4d-44d8-9bea-50dbca2b164e)

--> selecting an article from the drop-down menu closes the dialog field, without linking the articles. 

### Expected behaviour

While editing Knowledge Base articles and clicking on "Link answer", as depicted below:

![Image](https://github.com/user-attachments/assets/ef344e0f-8d4d-44d8-9bea-50dbca2b164e)

--> I would like to click an article from the drop-down menu, without the dialog window being closed unexpectedly.  

### Steps to reproduce the behaviour

1) go into some Knowledge Base articles (before create some articles)
2) click in the top right corner on "Edit" 
3) click on the "Link answer" and try to select one of the articles from the drop-menu via clicking on them (example in the screencast:https://github.com/user-attachments/assets/164a3667-7f92-4318-901f-f3a8ff3b16fb

### Support Ticket

Ticket#10165416

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Regression of 04f3f332117b3dc8aaa316d5dcfa5e9cf1a252c4.

**Comment by oliver124810** [comment]
It would be good to have this fixed soon. Is there any workaround in the meantime?

**Comment by fliebe92** [comment]
> It would be good to have this fixed soon. Is there any workaround in the meantime?

AFAIK, no workaround.

**Comment by dominikklein** [comment]
The current workaround would be using the keyboard navigation. You can select with arrows the row and then with enter the entry. Afterwards you can click on the link button.

**Comment by oliver124810** [comment]
The workaround works for me, thank you!
