### ISSUE TITLE
Storage folder does not exist in Zammad docker container.

### ISSUE THREAD

**Issue by cedricverhaeghe** [zammad/zammad#5412]
### Used Zammad Version

6.4

### Environment

- Installation method: Docker Compose
- Operating system: Debian GNU/Linux 12 (bookworm), Latest Zammad Docker image. 
- Database + version:  Postgresql 17.0
- Elasticsearch version: 8.15.3
- Browser + version: Chrome 130.0

### Actual behaviour

I cloned the following repository: https://github.com/zammad/zammad-docker-compose, ran `docker compose up -d`, and set the storage method to filesystem.

However, Zammad does not have permission to write to the `/opt/zammad/storage/` folder, which breaks certain functionality.

The issue arises because the storage folder does not exist in the Docker image itself. As a result, Docker creates the directory when setting up the volume mount, assigning it ownership of root:root. This means the zammad user inside the container does not have permission to write to the folder.

In my opinion, this could be easily resolved by creating the storage folder in the Dockerfile, allowing it to have the correct ownership and permissions.

### Expected behaviour

When running the Zammad docker-compose project and using filesystem as the storage method, I would expect the Zammad code to be able to write to the /opt/zammad/storage/ folder.

### Steps to reproduce the behaviour

```
git clone https://github.com/zammad/zammad-docker-compose
docker compose up -d
docker compose exec zammad-scheduler /bin/bash
touch storage/testfile
```

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
@mgruner would you like to check this?

**Comment by mgruner** [comment]
@cedricverhaeghe thanks for your nice report. I can confirm the issue and your solution proposal. Fix should land soon.

**Comment by kevinpapst** [comment]
I can confirm the issue for a fresh installation. Fixed temporarily with
```
docker compose exec -u root zammad-scheduler /bin/bash
chown zammad:zammad storage/
````

The ugly part here is: new emails will be imported, then `ERROR -- : Permission denied @ dir_s_mkdir - /opt/zammad/storage/fs (Errno::EACCES)` is triggered and then the flow stops before actually creating a ticket. 

So in case emails are removed from the server, you will never know that there was a request.

Not sure if that is an edge case of an edge case, but besides fro fixing the docker image, you probably might also have a look if you can't handle that gracefully without loosing the actual email.

Anyway: thanks for Zammad 👍

**Comment by mgruner** [comment]
Updates for zammad-docker-compose and zammad-helm to use the new image version by default will follow soon.
