### ISSUE TITLE
Migrations don't run with postgres transaction connection pool

### ISSUE THREAD

**Issue by carstenblt** [zammad/zammad#5413]
### Used Zammad Version

6.4

### Environment

- Installation method: Helm chart
- Database + version:  postgres 16 with transaction-based connection pool

### Actual behaviour

Migrations fail with

```
== 20241021191549 MoveChecklistTicketRelationToTicket: migrating ==============
-- change_table(:tickets)
   -> 0.0143s
-- remove_reference(:checklists, :ticket)
   -> 0.0023s
== 20241021191549 MoveChecklistTicketRelationToTicket: migrated (0.0377s) =====

bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block


Caused by:
ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block (ActiveRecord::StatementInvalid)


Caused by:
PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block (PG::InFailedSqlTransaction)

Tasks: TOP => db:migrate
```

The postgres log shows

```
[27-1] pid=531288,user=zammad,db=zammad,app=script/websocket-server.rb,client=[local] ERROR: prepared statement "a1" does not exist
[27-2] pid=531288,user=zammad,db=zammad,app=script/websocket-server.rb,client=[local] STATEMENT: DEALLOCATE a1
[25-1] pid=531310,user=zammad,db=zammad,app=script/websocket-server.rb,client=[local] ERROR: prepared statement "a2" does not exist
[25-2] pid=531310,user=zammad,db=zammad,app=script/websocket-server.rb,client=[local] STATEMENT: DEALLOCATE a2
[58-2] pid=523127,user=zammad,db=zammad,app=bin/rails,client=[local] STATEMENT: DEALLOCATE a1
```

### Expected behaviour

Migrations run even with transaction-based connection pool.

### Steps to reproduce the behaviour

Use transaction-based postgres connection pool and update to 6.4.

Using a session-based connection pool fixes the problem.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
After reading a little bit about it, it seems to me that Zammad is not implemented in that way to support transaction-based connection pooling for PostgreSQL as of now.

**Comment by mgruner** [comment]
@carstenblt can you please explain which PostgreSQL feature you refer to? If I read it correctly, this request is not about PostgreSQL itself, but about PgBouncer, which is used by cloud providers to provide connection pooling for PostgreSQL databases ([like described here](https://docs.digitalocean.com/products/databases/postgresql/how-to/manage-connection-pools/)).

Is this correct? In that case, I don't think that we can provide support for such a thirdparty software. 

What we could consider:
- Try to detect the wrong environment and refuse to start zammad, if it runs on such a connection. For that, we'd need criteria to detect the situation.
- Add a hint about it in our documentation, to help users setup such an environment correctly.

**Comment by carstenblt** [comment]
That is correct. I believe it is a very common way to use a database and it works for almost any application. Pooling can save a lot of resources.

I didn't run into any problems with the transaction pool yet, except for this migration. So there might be an easy fix for this. But otherwise yes, documenting would be the way to go.

**Comment by ralf401** [comment]
Added note to the documentation => https://github.com/zammad/zammad-documentation/pull/578 / https://github.com/zammad/zammad-documentation/pull/579
