### ISSUE TITLE
Package precompile sometimes assumes old code while precompiling

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#5418]
### Used Zammad Version

6.4

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

When packages are installed and an update is happening, then the cache breaks things and is taking old stuff into account.

```
x Build failed in 10.72s

error during build:

[vite-plugin-pwa:build] app/frontend/apps/mobile/components/CommonFilePreview/CommonFilePreview.vue?vue&type=script&setup=true&lang.ts (12:9): "humanizeFileSize" is not exporte

d by "app/frontend/shared/utils/helpers.ts", imported by "app/frontend/apps/mobile/components/CommonFilePreview/CommonFilePreview.vue?vue&type=script&setup=true&lang.ts".

file: /opt/zammad/app/frontend/apps/mobile/components/CommonFilePreview/CommonFilePreview.vue?vue&type=script&setup=true&lang.ts:12:9



10: import type { StoredFile } from '#shared/graphql/types.ts'

11: import { canDownloadFile, canPreviewFile } from '#shared/utils/files.ts'

12: import { humanizeFileSize } from '#shared/utils/helpers.ts'

             ^

13: import { getIconByContentType } from '#shared/utils/icons.ts'

14: import { i18n } from '#shared/i18n.ts'
```

### Expected behaviour

`rake zammad:package:precompile` should also clear the vite cache before building the new state.

For this we need `zammad run bundle exec vite clobber`

### Steps to reproduce the behaviour

- Update with packages installed.

### Support Ticket

Ticket#10165708

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@dvuckovic @vBenTec How should the Vite build normally work, when files are changing in the codebase? Should not use the existing cache or?

**Comment by dvuckovic** [comment]
Yes, the cache should be invalidated if the file has changed.

However, I'm not completely sure how it behaves if the source files are replaced with symbolic links (which is what might be happening here, depending on the way the package is "installed").

**Comment by rolfschmidt** [comment]
> Yes, the cache should be invalidated if the file has changed.
> 
> However, I'm not completely sure how it behaves if the source files are replaced with symbolic links (which is what might be happening here, depending on the way the package is "installed").

In the production environment of the customer there are no symbolic links. If packages are installed normally via UI, they get written as normal files.

**Comment by dominikklein** [comment]
And I think the files which were not working are not related to addons or?

**Comment by rolfschmidt** [comment]
> And I think the files which were not working are not related to addons or?

yeah `CommonFilePreview.vue` was not patched at all.

**Comment by dominikklein** [comment]
Then it's very strange, but at least this clobber would be a workaround. But normally really not needed...
