### ISSUE TITLE
Can't add new articles via Macro

### ISSUE THREAD

**Issue by martini** [zammad/zammad#542]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Tested on Google Chrome 75.0.x but should affect any
* Ticket-ID: 1054556, #1056455

### Expected behavior:

Being able to create articles via macro (as suggested by Macro actions).

### Actual behavior:

When choosing a Macro that should create an article, nothing happens.

### Steps to reproduce the behavior:

* create a Macro that will add a note (visibility doesn't matter)
* go into any ticket and run your Macro

### Screencast:

![macro-cant-add-articles](https://user-images.githubusercontent.com/6549061/62776187-276a5f00-baaa-11e9-8625-9606618db5b1.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This has, by now, become a bug.
In Zammad 3.1 Macros suggest you can add articles via Macros, but nothing happens if you run the Macro.

Will update the first article of Martin soonish.
