### ISSUE TITLE
Occasionally scheduler fails to load all needed code for unknown reasons

### ISSUE THREAD

**Issue by t-shehab** [zammad/zammad#5420]
### Used Zammad Version

observed in multiple versions, including 6.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

Occasionally (it is unknown at this point as to what the underlying causes are), the scheduler won't load all neeeded code after a restart, possibly in combination with an update of the app.

Affected constants that have been observed not to be loaded:

```
HtmlSanitizer::Scrubber
HtmlSanitizer::Strict
HtmlSanitizer::DynamicImageSize
UserInfo::Assets
```

Possibly others, as well.

This can lead to emails being sent 4 times or not at all.

### Expected behaviour

All needed code is loaded.
Emails are being sent exactly once.

### Steps to reproduce the behaviour

Unknown.
Happens occasionally after updates of the app.

### Support Ticket

Ticket#10162803, Ticket#10160939, Ticket#10155640, Ticket#10126795, Ticket#10124562, #10165117, Ticket#10165215, Ticket#10167259 (more will be updated later)

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by mgruner** [comment]
Unfortunately, this still happens after the update with the mentioned changes.

**Comment by mgruner** [comment]
I have a new unproven suspicion: it happens when forking during autoloading operations. When the background worker starts, it starts all services both as threads or forks, depending on their configuration. So the threads might start autoloading stuff, while the forks are created at the same time. If zeitwerk is not that atomic, it might cause inconsistent states.

**Comment by mgruner** [comment]
### Discussion 2024-11-28

- Investigate memory increase for scheduler if we eager load everything there
- Add lib/ eager loading to scheduler
- Change fork/thread handling to fork before threads are created
