### ISSUE TITLE
The dark mode cuts off screenshots

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#5421]
### Used Zammad Version

6.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When I add a screenshot with a white background, and change to dark mode, the screenshot is cut off.

### Expected behaviour

The screnshot should stay the same.

### Steps to reproduce the behaviour

Create a ticket via email with the attached screenshot

![Image](https://github.com/user-attachments/assets/c9a84906-1367-4f87-9e56-3ca4906c6bba)

Switch between dark and light mode.
Keyboard shortcut (D)

### Support Ticket

Ticket#10165984

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment]
The screenshot is staying the same, but the original file has an alpha channel on it (transparent background).

This is how I see it in my (dark theme) GitHub report:

![Image](https://github.com/user-attachments/assets/b3ca9353-e3d7-44ea-8115-01e13467de70)

I don't think we should manipulate uploaded images, if they are supplied with a transparent background, we should honor it.

If a white background is prefered, the image should be flattened in an image processing program first, before uploading.

**Comment by dominikklein** [comment]
Yes, I agree, when it's transparent, we should not do anything with the image. Because how would you decide this in the end?

**Comment by Bozo0511** [comment]
I noticed now when I opnen the screenshot in paint it has a seetrough background:

![Image](https://github.com/user-attachments/assets/4ead0d25-0bcd-4b1d-b122-ff1d7640a5cb)

I think that this is the reason why the screenshot is changed when I switch from dark to light mode.

**Comment by dominikklein** [comment]
Like discussed is the behavior, because of the transparency of the image. We agreed that we should not manipulate the image in this situation.
