### ISSUE TITLE
"Translate field contents" checkbox translates only partially or nothing at all

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#5422]
### Used Zammad Version

6.4

### Environment

- Installation method: any
- Operating system: any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: MS Edge v. 131.0.2903.51 (official version) (64-bit)

### Actual behaviour

When setting the object attribute "Translate object contents" to yes, only some of the content gets translated. When having the object and its options in English, the following languages translate them as follows:

in German --> first four options are unchanged from the original, but the fifth one gets translated into German.
in Spanish - the same as above, only the fifth option gets translated
interestingly, in Chinese, all five options are translated.
Selecting French only translates the fifth option. 

For comparison, having simple words like first, second and etc. (up to seven) doesn't get translated in any language at all. 

### Expected behaviour

I would like to see the object translated if the corresponding checkmark has been set in the object conditions. And if such a condition has been set, then the entire content should be translated.

### Steps to reproduce the behaviour

1) Create an object (either boolean, single or multiple selection field, single or multiple tree selection field) with several options

2) Choose a different language (as opposed to your default locale), with or without reloading the page, and check how different objects are only partially translated or not translated at all. 

https://github.com/user-attachments/assets/6c0b4c45-3dd6-4ebd-8104-3edc2ee895ea

### Support Ticket

Ticket#10166031

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Did you add a custom translation for every string? For sure that strings that already exist in the codebase are translated, but other customs strings are not.

https://admin-docs.zammad.org/en/latest/system/translations.html

**Comment by fliebe92** [comment]
Hi @Suhopoljac. I cannot reproduce your described issue, but for sure, it's only working fine after adding custom translations as @dominikklein already described. Please check it.

It's explained in our documentation as well: https://admin-docs.zammad.org/en/latest/system/translations.html#translation-of-custom-objects

**Comment by Suhopoljac** [comment]
Thanks guys, with the local translations it works now. The issue can be closed.
