### ISSUE TITLE
External data source object cannot be "set" in Postmaster filter

### ISSUE THREAD

**Issue by Canneton** [zammad/zammad#5425]
### Used Zammad Version

6.3.1-1730190484.5c5b5fba.jammy

### Environment

- Installation method: package
- Operating system: ubuntu 22.04
- Database + version:  postgresql 14.13
- Elasticsearch version: 7.17.25
- Browser + version: Chrome 131.0.6778.86

### Actual behaviour

When searching for a external data source object value in the Postmaster filter configuration, a server 500 error appears in the browser. “undefined method `fetch_undefined?’ for #<ExternalDataSourcePolicy:0x00[…]”

Production.log indicates the following:
I, [2024-11-26T02:07:27.624988#58269-254966600] INFO – : Started GET “/api/v1/external_data_source/undefined/perform::x-zammad-ticket-external_test::value?query=100&limit=40&=1732585742870" for [IP_ADDRESS] at 2024-11-26 02:07:27 +0000
I, [2024-11-26T02:07:27.636703#58269-254966600] INFO – : Processing by ExternalDataSourceController#fetch as JSON
I, [2024-11-26T02:07:27.636764#58269-254966600] INFO – : Parameters: {“query”=>“100”, “limit”=>“40”, "”=>“1732585742870”, “object”=>“undefined”, “attribute”=>“perform::x-zammad-ticket-external_test::value”}
E, [2024-11-26T02:07:27.662343#58269-254966600] ERROR – : undefined method fetch_undefined?' for #<ExternalDataSourcePolicy:0x00007fdfb14dc2c0 @user=#<User id: [HIDDEN OUTPUT FOR USER]>, @record="undefined"> (NoMethodError) app/policies/external_data_source_policy.rb:5:in fetch?’
app/policies/controllers/external_data_source_controller_policy.rb:9:in fetch?' app/controllers/application_controller/authorizes.rb:10:in authorize!’
app/controllers/application_controller/authenticates.rb:143:in `authenticate_and_authorize!’
I, [2024-11-26T02:07:27.674019#58269-254966600] INFO – : Completed 500 Internal Server Error in 37ms (Views: 0.2ms | ActiveRecord: 12.2ms | Allocations: 7415)

### Expected behaviour

Perform action on Postmaster filter should allow to set external data source object value.
Works fine with triggers and schedulers.

### Steps to reproduce the behaviour

Create external data source object named “Entente”
Create new postmaster filter with any match rule
Perform action: Select “Entente” and type any character in the search field
Error popup appears immediately

![](https://community.zammad.org/uploads/default/original/2X/3/39adbaa0c15a1469999a03c0d25cb8be4d043c2a.png)

![](https://community.zammad.org/uploads/default/original/2X/4/44557ec351916c1679b86b4b39a9525f5977c5eb.png)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Some issue we fixed in the past for other places: https://github.com/zammad/zammad/issues/5148
