### ISSUE TITLE
Cannot choose custom port for SMTP email notification

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#543]
No option for custom port other than 25 for setting up direct SMTP for notifications (in E-Mail-Accounts this is present)
![image](https://cloud.githubusercontent.com/assets/23480845/21181875/5236974e-c200-11e6-98df-a33b0681b26f.png)

**Comment by thorsteneckel** [comment]
This will be fixed in the upcoming release today as discussed there: https://github.com/zammad/zammad/issues/424#issuecomment-266423460

Feel free to reopen if I get you wrong.
