### ISSUE TITLE
PGP: Decryption fails if Zammad's address is in BCC

### ISSUE THREAD

**Issue by abrain** [zammad/zammad#5432]
### Used Zammad Version

6.4.0-1732871355.611ba7e2.bullseye

### Environment

- Installation method: package
- Operating system: Debian 11.11
- Database + version:  postgresql 13.18
- Elasticsearch version: 7.17
- Browser + version: firefox 132

### Actual behaviour

If a PGP encrypted email is received, and Zammad's address is in BCC, the email is not decrypted.

Zammad claims that the private key could not be found, but other encrpyted mails work just fine. Also, the auto reply for the BCC ticket was properly signed and encrypted.

![Image](https://github.com/user-attachments/assets/a9304471-a07f-435a-91a8-e3298a9a2f84)

[production.log](https://github.com/user-attachments/files/17960021/production.log)

### Expected behaviour

The email should be decrypted as if it was sent with Zammad's address in the To: or CC: field.

### Steps to reproduce the behaviour

- Have Zammad set up with a PGP key pair for one of your email addresses
- Send a PGP encrypted email to that address in BCC (leave To and CC emtpy, or put a non-Zammad address in To)
- The email is processed, but not decrypted and shows as "no visible content" plus attachments
- Retrying the decryption fails as well

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Hi @abrain. What is a `Zammad address`?

**Comment by abrain** [comment]
> What is a `Zammad address`?

I meant it to be an email address that will be routed to Zammad. Additionally, the email address is configured in the Email settings and possibly associated with a Group, so Zammad definitely knows it is responsible for that email address.
