### ISSUE TITLE
Extend usage of search & pagination in admin interface to similar screens

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5433]
As an admin I want to have access to the search & pagination features from #5384 in all similar tables in the admin interface to keep consistency.

**ACCEPTENCE CRITERIA**
- Add the search & pagination feature to all other pages where the effort is minimal.
- At least for where the table look the same to keep consistency.
- Prepare it for the same release, so users only need to make one `searchindex:rebuild`.

**Comment by rolfschmidt** [comment]
Extended to

- core workflow
- job
- trigger
- public links
- report profiles
- webhooks

https://git.zammad.com/zammad/zammad/-/commit/4132da0dd062ffe228fdd8c66d80a31acafff191
