### ISSUE TITLE
Strange behavior of the attachement section in ticket sidebar (Drag & Drop to article drafts not possible)

### ISSUE THREAD

**Issue by Koppishop** [zammad/zammad#5436]
### Used Zammad Version

6.4.1

### Environment

- Installation method: [e.g. source, package]: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When using the attachement sidebar all attachments of the ticket are listed here as expected.
But when trying to attach one of this documents to a mail draft and e.g. resend the attachment, it does not work.
I need to download the attchement, save it locally and then attach from filepicker again. 

### Expected behaviour

When using the attachement sidebar all attachments of the ticket are listed here and I want to have the possibility to simply Drag&Drop those attachments to the outbound mail or note draft in my ticket.

### Steps to reproduce the behaviour

tried on different instances, always same behaviour

### Support Ticket

Ticket#10166300

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
This is not a bug, but a feature request.

**Comment by YetAnotherGerrit** [comment]
Please use the _Feature Request_ section of the _Community_ instead:
https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6/none
