### ISSUE TITLE
Most recent data privacy tasks are not shown

### ISSUE THREAD

**Issue by abrain** [zammad/zammad#5437]
### Used Zammad Version

6.4.0-1732617118.28f54743.bullseye

### Environment

- Installation method: package
- Operating system: Debian 11.11
- Database + version: postgresql 13.18
- Elasticsearch version: 7.17
- Browser + version: firefox 132

### Actual behaviour

The most recent (shown) data privacy task is from 10 months ago, even though there were many more created since then.

The list is sorted by date (descending, which is good), but the API call returns them in ascending order. Due to an apparent limit of 500 entries, only the 500 oldest entries are displayed.

### Expected behaviour

The most recent – or better all – data privacy tasks should be shown.

From what I can tell, this was not part of the pagination effort for 6.5 (#5384).

### Steps to reproduce the behaviour

- Have more that 500 data privacy tasks
- Create a new data privacy task
- It may show up for a short period of time (or vanish immediately), but is surely gone upon navigation or reload

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MarkusHeld** [comment]
Can be reproduced in this way. Only 500 tasks are displayed and if there are more than 500 entries, the new tasks are not visible.
