### ISSUE TITLE
OTRS import via UI not possible with develop branch on CentOS7

### ISSUE THREAD

**Issue by martini** [zammad/zammad#544]
Now I'm able to reproduce it. Import via UI will stop. Error in log/scheduler_err.log:

/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute': unknown attribute 'sugar_crm_company_selection' for Ticket. (ActiveRecord::UnknownAttributeError)
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:35:in `each'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/core.rb:566:in `init_attributes'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/core.rb:281:in `initialize'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/inheritance.rb:61:in `new'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/inheritance.rb:61:in `new'
	from /opt/zammad/lib/import/otrs/ticket.rb:59:in `create'
	from /opt/zammad/lib/import/otrs/ticket.rb:46:in `create_or_update'
	from /opt/zammad/lib/import/otrs/ticket.rb:38:in `import'
	from /opt/zammad/lib/import/otrs/ticket.rb:30:in `initialize'
	from /opt/zammad/lib/import/factory.rb:12:in `new'
	from /opt/zammad/lib/import/factory.rb:12:in `block in import'
	from /opt/zammad/lib/import/factory.rb:10:in `each'
	from /opt/zammad/lib/import/factory.rb:10:in `import'
	from /opt/zammad/lib/import/otrs.rb:141:in `import_action'
	from /opt/zammad/lib/import/otrs.rb:131:in `imported?'
	from /opt/zammad/lib/import/otrs.rb:95:in `block (3 levels) in threaded_import'
	from /opt/zammad/lib/import/otrs.rb:89:in `loop'
	from /opt/zammad/lib/import/otrs.rb:89:in `block (2 levels) in threaded_import'

Source: http://vz599.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator;Key=01234567899876543210

**Comment by thorsteneckel** [comment]
As discussed: Can't get reproduced on the provided VM.
