### ISSUE TITLE
Upgrade 6.3.1 to 6.4.1 fails

### ISSUE THREAD

**Issue by TomAstor** [zammad/zammad#5440]
### Used Zammad Version

6.3.1

### Environment

Upgrade 6.3.1 to 6.4.1 fails:
 
- Installation method:  package
- Operating system (if you're unsure: `cat /etc/os-release` ): ubuntu 22.04.
- Database + version:   postgresql 14
- Elasticsearch version: [e.g. 7.17]

### Actual behaviour

== 20231115110546 CreateSystemReport: migrating ===============================
-- create_table(:system_reports)
   -> 0.0587s
-- add_index(:system_reports, [:uuid], {:unique=>true, :name=>"index_system_reports_on_uuid"})
   -> 0.0058s
== 20231115110546 CreateSystemReport: migrated (0.0973s) ======================

== 20240423091057 Add2faPermission: migrating =================================
== 20240423091057 Add2faPermission: migrated (0.0405s) ========================

== 20240509100920 PermissionSwitchToLabelDescription: migrating ===============
-- rename_column(:permissions, :note, :description)
   -> 0.0055s
-- add_column(:permissions, :label, :string, {:limit=>255})
   -> 0.0010s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

Couldn't find Permission with [WHERE "permissions"."name" = $1]
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/relation/finder_methods.rb:413:in `raise_record_not_found_exception!'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:304:in `find_by!'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:28:in `change_single_permission_wording'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:23:in `block in change_wording'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:22:in `each'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:22:in `each_with_index'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:22:in `change_wording'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:9:in `change'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:986:in `exec_migration'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:970:in `block (2 levels) in migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:969:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:227:in `with_connection'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:968:in `migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1178:in `migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1529:in `block in execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transact
ion'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1580:in `ddl_transaction'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1528:in `execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1503:in `each'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1503:in `migrate_without_lock'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1448:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1600:in `with_advisory_lock'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1448:in `migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1274:in `up'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1249:in `migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/tasks/database_tasks.rb:251:in `migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/railties/databases.rake:93:in `block (2 levels) in <main>'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `load'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:23:in `run'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:492:in `exec'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:34:in `dispatch'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:28:in `start'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
/opt/zammad/bin/bundle:121:in `load'
/opt/zammad/bin/bundle:121:in `<main>'

Caused by:
ActiveRecord::RecordNotFound: Couldn't find Permission with [WHERE "permissions"."name" = $1] (ActiveRecord::RecordNotFound)
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/relation/finder_methods.rb:413:in `raise_record_not_found_exception!'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:304:in `find_by!'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:28:in `change_single_permission_wording'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:23:in `block in change_wording'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:22:in `each'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:22:in `each_with_index'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:22:in `change_wording'
/opt/zammad/db/migrate/20240509100920_permission_switch_to_label_description.rb:9:in `change'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:986:in `exec_migration'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:970:in `block (2 levels) in migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:969:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:227:in `with_connection'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:968:in `migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1178:in `migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1529:in `block in execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transact
ion'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.4.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1580:in `ddl_transaction'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1528:in `execute_migration_in_transaction'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1503:in `each'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1503:in `migrate_without_lock'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1448:in `block in migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1600:in `with_advisory_lock'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1448:in `migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1274:in `up'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/migration.rb:1249:in `migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/tasks/database_tasks.rb:251:in `migrate'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.4.1/lib/active_record/railties/databases.rake:93:in `block (2 levels) in <main>'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `load'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:23:in `run'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:492:in `exec'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:34:in `dispatch'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/cli.rb:28:in `start'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
/opt/zammad/bin/bundle:121:in `load'
/opt/zammad/bin/bundle:121:in `<main>'

### Expected behaviour

Successful upgrade

### Steps to reproduce the behaviour

apt update
apt upgrade

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by fliebe92** [comment]
Hi @TomAstor. Your database is missing at least one permission, no idea how this happened.

To get more information, please open a Rails console and execute the following snippet:

```ruby
[ 'admin', 'admin.user', 'admin.group', 'admin.role', 'admin.organization', 'admin.overview', 'admin.text_module', 'admin.macro', 'admin.template', 'admin.tag', 'admin.calendar', 'admin.sla', 'admin.trigger', 'admin.public_links', 'admin.webhook', 'admin.scheduler', 'admin.report_profile', 'admin.time_accounting', 'admin.knowledge_base', 'admin.channel_web', 'admin.channel_formular', 'admin.channel_email', 'admin.channel_sms', 'admin.channel_chat', 'admin.channel_google', 'admin.channel_microsoft365', 'admin.channel_twitter', 'admin.channel_facebook', 'admin.channel_telegram', 'admin.channel_whatsapp', 'admin.branding', 'admin.setting_system', 'admin.security', 'admin.ticket', 'admin.integration', 'admin.api', 'admin.object', 'admin.ticket_state', 'admin.ticket_priority', 'admin.core_workflow', 'admin.translation', 'admin.data_privacy', 'admin.maintenance', 'admin.monitoring', 'admin.package', 'admin.session', 'admin.system_report', 'chat', 'chat.agent', 'cti', 'cti.agent', 'knowledge_base', 'knowledge_base.editor', 'knowledge_base.reader', 'report', 'ticket', 'ticket.agent', 'ticket.customer', 'user_preferences', 'user_preferences.appearance', 'user_preferences.language', 'user_preferences.avatar', 'user_preferences.out_of_office', 'user_preferences.password', 'user_preferences.two_factor_authentication', 'user_preferences.device', 'user_preferences.access_token', 'user_preferences.linked_accounts', 'user_preferences.notifications', 'user_preferences.overview_sorting', 'user_preferences.calendar' ].each do |name|
  begin
    Permission.find_by!(name:)
  rescue ActiveRecord::RecordNotFound
    puts "Permission '#{name}' not found"
  end
end
```

**Comment by TomAstor** [comment]
Hi Florian, thanks for your fast answer - the outputs of the snippets are:

Permission 'admin.knowledge_base' not found
Permission 'admin.system_report' not found
Permission 'knowledge_base' not found
Permission 'knowledge_base.editor' not found
Permission 'knowledge_base.reader' not found
Permission 'user_preferences.two_factor_authentication' not found
=> ["admin",
 "admin.user",
 "admin.group",
 "admin.role",
 "admin.organization",
 "admin.overview",
 "admin.text_module",
 "admin.macro",
 "admin.template",
 "admin.tag",
 "admin.calendar",
 "admin.sla",
 "admin.trigger",
 "admin.public_links",
 "admin.webhook",
 "admin.scheduler",
 "admin.report_profile",
 "admin.time_accounting",
 "admin.knowledge_base",
 "admin.channel_web",
 "admin.channel_formular",
 "admin.channel_email",
 "admin.channel_sms",
 "admin.channel_chat",
 "admin.channel_google",
 "admin.channel_microsoft365",
 "admin.channel_twitter",
 "admin.channel_facebook",
 "admin.channel_telegram",
 "admin.channel_whatsapp",
 "admin.branding",
 "admin.setting_system",
 "admin.security",
 "admin.ticket",
 "admin.integration",
 "admin.api",
 "admin.object",
 "admin.ticket_state",
 "admin.ticket_priority",
 "admin.core_workflow",
 "admin.translation",
 "admin.data_privacy",
 "admin.maintenance",
 "admin.monitoring",
 "admin.package",
 "admin.session",
 "admin.system_report",
 "chat",
 "chat.agent",
 "cti",
 "cti.agent",
 "knowledge_base",
 "knowledge_base.editor",
 "knowledge_base.reader",
 "report",
 "ticket",
 "ticket.agent",
 "ticket.customer",
 "user_preferences",
 "user_preferences.appearance",
 "user_preferences.language",
 "user_preferences.avatar",
 "user_preferences.out_of_office",
 "user_preferences.password",
 "user_preferences.two_factor_authentication",
 "user_preferences.device",
 "user_preferences.access_token",
 "user_preferences.linked_accounts",
 "user_preferences.notifications",
 "user_preferences.overview_sorting",
 "user_preferences.calendar"]

**Comment by fliebe92** [comment]
> Permission 'admin.knowledge_base' not found
> Permission 'admin.system_report' not found
> Permission 'knowledge_base' not found
> Permission 'knowledge_base.editor' not found
> Permission 'knowledge_base.reader' not found
> Permission 'user_preferences.two_factor_authentication' not found

This is bad. You're missing several permissions (and not sure what else).

**Comment by TomAstor** [comment]
Hm, I followed the normal update path and didn't do magic with the database, zammad is running perfect ... Is there anything I could do to get the permissions fixed?

**Comment by fliebe92** [comment]
Phew, I would like to avoid fiddling around in your database. Need to think about it.

**Comment by fliebe92** [comment]
Hi @TomAstor. We talked about this issue in our team, and we would like to close this report, due to being not an issue in the Zammad code base. It would be really nice if you can visit our [community](https://community.zammad.org) and ask for help there. Maybe somebody else had a situation like yours in the past.
