### ISSUE TITLE
OTRS import: Empty created_at of customer user record brakes import.

### ISSUE THREAD

**Issue by patrick-fox** [zammad/zammad#548]
Dear all,

just tried the new 1.1.1 on Ubuntu 16 with migrating an OTRS 5s (5.0.14) with Migrator 1.2.1. After four user accounts it stops:

> ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
> DETAIL:  Failing row contains (5, null, customer@mail.org, Firstname, Lastname, customer@mail.org, null, null, , null, , , , , Muster Str. 10, 12345, Musterstadt, Deutschland, , f, f, t, , null, OTRS Import, 0, --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
> lat: 49...., 0, 0, null, null).
> : UPDATE "users" SET "updated_at" = $1, "created_at" = $2 WHERE "users"."id" = $3
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:173:in `exec_delete'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:114:in `update'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:88:in `_update_record'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:515:in `_update_record'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/locking/optimistic.rb:79:in `_update_record'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:129:in `_update_record'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:310:in `block in _update_record'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
> ... 29 levels...
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:250:in `update'
>         from /opt/zammad/lib/import/otrs.rb:1250:in `block in customer'
>         from /opt/zammad/lib/import/otrs.rb:1220:in `each'
>         from /opt/zammad/lib/import/otrs.rb:1220:in `customer'
>         from /opt/zammad/lib/import/otrs.rb:378:in `start'
>         from (irb):6
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
>         from /opt/zammad/bin/rails:4:in `require'
>         from /opt/zammad/bin/rails:4:in `<main>'

Any idea how to fix the importdata?

Cheers,
Patrick

**Comment by thorsteneckel** [comment]
HI @patrick-fox - thanks for reporting this. I'll take a look at it right on tomorrow and let you know.

**Comment by thorsteneckel** [comment]
I fixed the behavior with the commit above. Please note that this is part of a big refactoring change which is released yet. You can test it by using our develop branch package.
