### ISSUE TITLE
Cannot choose custom port for SMTP email notification (reopen #543)

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#550]
Reopening Issue #543 (hope this is the right way to do it)
No option for custom port other than 25 for setting up direct SMTP for notifications (in E-Mail-Accounts this is present). Updated to 1.1.1.
This is not the same issue as #424 

![image](https://cloud.githubusercontent.com/assets/23480845/21256380/3730fd72-c372-11e6-887c-cdd676e48630.png)

**Comment by martini** [comment]
@babakkazemi  sorry, this enhancement is only available in develop (will be release as stable on 2017-01-14)

**Comment by babakkazemi** [comment]
@martini will it be possible to change to develop branch now and revert back to stable when released in January?

**Comment by martini** [comment]
@babakkazemi yes, it is. 🤓
