### ISSUE TITLE
How to escalate tickets?

### ISSUE THREAD

**Issue by abenrob** [zammad/zammad#551]
I'm not able to escalate tickets using the docker build - Is there a specific configuration to enable this feature?

**Comment by thorsteneckel** [comment]
Hi @abenrob - Could you please describe your issue a bit more? What Zammad version are you using? What do you mean with "escalate tickets"? Did you configure your escalations in the admin interface? Could you provide the `log/production.log` file from system?

**Comment by abenrob** [comment]
How does one configure escalations in the admin interface? I see no options to do so - not in the ticket object, and therefore not via any macros or triggers.

**Comment by thorsteneckel** [comment]
SLAs is what you are looking for :) You can find it in the admin interface. There is a nice introduction text that explains the general concept.

**Comment by abenrob** [comment]
Hmm. Ok. Is this text available in English?

**Comment by thorsteneckel** [comment]
Oh my.... Yeah - no 😱  They are currently only available in german: https://github.com/zammad/zammad/blob/7df285d9dfc9299afc5b276db4a27b20ef395f87/app/assets/javascripts/app/models/sla.coffee#L21

I'll create a new issue for this and will get to it as soon as possible.

**Comment by thorsteneckel** [comment]
@abenrob - please see the linked issue where the great @pradorocchi provided a translation.
