### ISSUE TITLE
No translation for Chat module

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#553]
Where i can edit the chat translation? Or is it only missing?

**Comment by martini** [comment]
JFI: The widget uses the lang attribute of the `<html>` tag. The chat widget is currently only translated in en + de. If nobody want to add more languages, just create a PR. Here is the file https://github.com/zammad/zammad/blob/develop/public/assets/chat/chat.coffee#L182

**Comment by Braintelligence** [comment]
@martini Since you say the chat is already translated to German: I still see "Chat closed by" for clients and "You left the conversation" and "Turn chat into ticket" for supporters.

I use zammad-docker-compose on 2.3.0-24 almost everything else is correctly in German.

**Comment by martini** [comment]
@Braintelligence Can you add an screenshot from the screen what you are talking about? Thanks.

**Comment by Braintelligence** [comment]
![grafik](https://user-images.githubusercontent.com/6761196/37795015-8398900a-2e13-11e8-8b6f-ceb41c3239a4.png)
![grafik](https://user-images.githubusercontent.com/6761196/37795211-21af88b6-2e14-11e8-9171-ef4976e02852.png)

Is this helpful?
