### ISSUE TITLE
OTRS import brake up with Timeout::Error: execution expired

### ISSUE THREAD

**Issue by patrick-fox** [zammad/zammad#555]
hi!

I tried again a OTRS import (latest migrator package, OTRS 5s / 5.0.14, Zammad 1.1.1 on Ubuntu 16) and got the following after a couple of users:

> Setting.get("system_init_done") # from cache
> Setting.get("geo_location_backend") # from cache
> Timeout::Error: execution expired
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/utils.rb:67:in `scan'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/utils.rb:67:in `extract_schema_qualified_name'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/quoting.rb:31:in `quote_table_name'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:776:in `quote_table_name'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:624:in `visit_Arel_Table'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:123:in `visit_Arel_Nodes_InsertStatement'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:7:in `accept'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:12:in `to_sql'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:107:in `insert'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:64:in `insert'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:524:in `_create_record'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/counter_cache.rb:139:in `_create_record'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/locking/optimistic.rb:75:in `_create_record'
> ... 26 levels...
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block in save'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:285:in `save'
>         from /opt/zammad/lib/import/otrs.rb:1255:in `block in customer'
>         from /opt/zammad/lib/import/otrs.rb:1220:in `each'
>         from /opt/zammad/lib/import/otrs.rb:1220:in `customer'
>         from /opt/zammad/lib/import/otrs.rb:378:in `start'
>         from (irb):4
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
>         from /opt/zammad/bin/rails:4:in `require'
>         from /opt/zammad/bin/rails:4:in `<main>'

Any idea how to fix this?

Cheers,
Patrick

**Comment by monotek** [comment]
Try the develop package.

patrick-fox <notifications@github.com> schrieb am Fr., 16. Dez. 2016, 23:05:

**Comment by patrick-fox** [comment]
hi!

Still the "same" error after 74 users:

> ActiveRecord::StatementInvalid: Timeout::Error: execution expired: INSERT INTO `users` (`created_by_id`, `updated_by_id`, `source`, `email`, `firstname`, `lastname`, `login`, `phone`, `fax`, `street`, `zip`, `city`, `country`, `created_at`, `updated_at`) VALUES (0, 0, 'OTRS Import', 'it@customer.de', 'Firstname', 'Lastname', 'it@customer.de', '+49 123 45678', '+49 123 45678', 'Strasse 1', '12345', 'Stadt', 'Deutschland', '2016-12-16 22:30:48', '2016-12-16 22:30:48.677')
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:248:in `exec_insert'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:64:in `insert'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:524:in `_create_record'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/counter_cache.rb:139:in `_create_record'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/locking/optimistic.rb:75:in `_create_record'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'
> ... 36 levels...
>         from /opt/zammad/lib/import/factory.rb:10:in `import'
>         from /opt/zammad/lib/import/otrs.rb:141:in `import_action'
>         from /opt/zammad/lib/import/otrs.rb:131:in `imported?'
>         from /opt/zammad/lib/import/otrs.rb:118:in `block in limit_import'
>         from /opt/zammad/lib/import/otrs.rb:116:in `loop'
>         from /opt/zammad/lib/import/otrs.rb:116:in `limit_import'
>         from /opt/zammad/lib/import/otrs.rb:163:in `customer_user'
>         from /opt/zammad/lib/import/otrs.rb:45:in `start'
>         from (irb):4
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
>         from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
>         from /opt/zammad/bin/rails:4:in `require'
>         from /opt/zammad/bin/rails:4:in `<main>'

I tested this now with mysql backend - first test was with pgsql.

Cheers,
Patrick

**Comment by thorsteneckel** [comment]
Hi @patrick-fox - I'll take a look on monday.

**Comment by thorsteneckel** [comment]
Hi Patrick! Your log lacks of the interesting part 🤓  See:

```
from /opt/zammad/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:133:in_create_record'
... 36 levels...
from /opt/zammad/lib/import/factory.rb:10:in import' from /opt/zammad/lib/import/otrs.rb:141:inimport_action'
```

The `... 36 levels...` block is what I need to know. Could you please provide this information?

Additionally: Which database are you using? How much CPU and RAM does your machine have?

Thanks in advance!

**Comment by patrick-fox** [comment]
hi Thorsten,

sorry for the late response - how can I get this? It's copy & paste from the import :) The import with the dev-branch was done with mysql-5.7.16 (with this howto: https://docs.zammad.org/en/latest/contributing-install-source.html - just replaced the latest.tar.gz with the develop-version), the zammad vm has 8gb ram, 4 interl cpu cores. The otrs server has 4gb ram and 2 intel cpu cores (nothing else on this server).

Import was done via:

> su - zammad
> cd /opt/zammad
> rails c
>  
> Setting.set('import_otrs_endpoint', 'https://x/otrs/public.pl?Action=ZammadMigrator')
> Setting.set('import_otrs_endpoint_key', 'xxx')
> Setting.set('import_mode', true)
> Import::OTRS.start

But I can't reproduce the issue right now, as I have already re-installed the VM :( So I guess we can close this here.

Br,
Patrick

**Comment by thorsteneckel** [comment]
Thanks for the feedback. Strange! Let's hope it was an one time thing.

**Comment by membero** [comment]
Hi,

just FYI:

I ran into the same problem, even after a complete reinstall. A strace showed that the problem might have something to do with Google Geolocation, so I set:

Setting.Set('geo_location_backend', false)

A new import was successful.
