### ISSUE TITLE
Emails werden beim Import gelöscht

### ISSUE THREAD

**Issue by Kalashnikitty** [zammad/zammad#559]
Halte ich für nicht brauchbar - bitte Archivieren und nicht löschen.

**Comment by rkaldung** [comment]
Das ist ein normales Verhalten bei solchen Systemen. 
Archivierung liegt auch nicht wirklich im Fokus von Zammad, dafür gibt es Systeme wie Piler, Benno uva.

**Comment by Kalashnikitty** [comment]
Schade, dass man das als Benutzer nicht selbst entscheiden darf.

**Comment by patrick-fox** [comment]
Wie wäre es, einfach die E-Mails an zwei Mailboxen zustellen zu lassen? Einmal für Zammad und einmal für's Archiv (wenn man Piler, etc. nicht einsetzen will oder kann).

**Comment by MartinBorg** [comment]
Ist das nicht das gleiche Thema wie #243, #539, #923?

**Comment by thorsteneckel** [comment]
Richtig! Schließe hier - Hauptissue mit Amtssprache Englisch ist #243.
