### ISSUE TITLE
Sidebar - Customer - Open tickets should be clickable and open advanced search

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#563]
### Infos:
*This issue has been edited by @MrGeneration to meet our requirements.*

* Used Zammad version: Zammad 3.5 and earlier
* Installation method (source, package, ..): any
* Operating system: Any
* Database + version: any
* Browser + version: chrome
* Note: This would be helpful to merge or close all tickets of customer as soon as bulk action is implemented in advanced search https://github.com/zammad/zammad/issues/445

### Desired behavior:

When viewing the meta information of a tickets customer, clicking on "closed" or "open" tickets will provide an advanced search tab for all customer tickets fitting said situation.

Something like
`customer_id: 4 AND state: open`
`customer_id: 4 AND state: closed`

Technically it would also be usefull if it's not hard stuck to above states but would work for any state types.
This would provide *alot* more tickets because you could have e.g. different closed states or tickets in pending state you may want to cover.

### Actual behavior:

When viewing the meta information of a tickets customer, Zammad provides a popover for closed and open tickets of said customer. However, this list is incomplete and forces the agent to touch every ticket shown there manually.

![image](https://user-images.githubusercontent.com/6549061/96731642-c92c5200-13b7-11eb-9ca7-4b327bd9068e.png)

### Steps to reproduce the behavior:

* open any ticket
* switch to the customer tab
* click on the "open" or "closed" link

**Comment by MrGeneration** [comment]
Hey @monotek ,

I just touched your first article, could you please have a look at my edit to see if I catched your use case correctly?
This will help us to touch the places you really meant. :)

Thanks!

**Comment by romitgithub** [comment]
Hi! I'm working on this issue as a part of the interview process. I have few questions:

1) Where is the extended search page? How to open it?
2) Is there a documentation as to how to create the url for extended search such that it lists the required items

Thanks

**Comment by mantas** [comment]
Hi @romitgithub 

> Where is the extended search page? How to open it?

Search for something that returns at least one result and then "Show Search Details" will appear right bellow the search input. Or go to `http://localhost:3000/#search/Welcome` given that you run your local instance at the usual address.

> Is there a documentation as to how to create the url for extended search such that it lists the required items

I guess above answer covers this one as well :)

**Comment by romitgithub** [comment]
But this only accepts a query param in url. How can I pass the customer ID and state of ticket to show those tickets only?

**Comment by mantas** [comment]
What if the metadata was a part of the query?

Tip: make sure you got ElasticSearch configured for full search experience.

**Comment by romitgithub** [comment]
Thanks. I got ElasticSearch up and running.

Is there any documentation for this api: **_api/v1/search?_**

**Comment by mantas** [comment]
Code is best documentation :)

Looking at `#search_index_attribute_lookup` of a model in question is the best way to figure out which attributes are searchable.

**Comment by romitgithub** [comment]
Hey @mantas. I haven't worked with vuejs extensively so can't figure out the code much. It'd be really helpful if I can get the documentation or example of how to query the api for other fields?

Thanks

**Comment by MrGeneration** [comment]
In terms of search endpoints there's limited documentation available.
The ticket endpoint in terms of search might help you to find the way for the generic search mechanisms:

https://docs.zammad.org/en/latest/api/ticket.html#search

If you want to search for specific attributes and maybe even combine them, maybe this part of the user documentation helps you:
https://user-docs.zammad.org/en/latest/advanced/search.html

**Comment by mantas** [comment]
Hi @romitgithub 

No VueJS here - only Coffeescript and Spine :)

Why would you want to call the api directly over linking to search view?

**Comment by romitgithub** [comment]
Hi @mantas. Yep, it's not VueJS. I'm currently working on multiple projects so mentioned VueJS by mistake.

I haven't worked with Coffeescript either.

> Why would you want to call the api directly over linking to search view?

I don't wall to call the api directly, but I need to know api requirements for complex query such as this one.

Thanks

**Comment by mantas** [comment]
@romitgithub Usual ElasticSearch syntax does the trick - `customer_id: {id} state_id: {id}`

**Comment by romitgithub** [comment]
Thanks a lot @mantas 
 Got it working now. Changed open and closed text to links which will open the extended search page with results based on state and customer id

**Comment by romitgithub** [comment]
@mantas Here is the PR for this one https://github.com/zammad/zammad/pull/3273

**Comment by rolfschmidt** [comment]
Note by @martini: future solution will open the ticket search which may result in different ticket counts between the widget and the search result because it does check permissions differently:

https://github.com/zammad/zammad/blob/be64e3ff0c263803def7bae342a79ef09c323f40/app/jobs/ticket_user_ticket_counter_job.rb#L25

This will be changed with web 2.0.
