### ISSUE TITLE
OTRS import - unsupported DynamicField type fields cause import to abort

### ISSUE THREAD

**Issue by patrick-fox** [zammad/zammad#565]
hi!

### Infos:

* Used Zammad version: 1.2.0-1482250389.bce847d.xenial
* Operating system: Ubuntu 16 64bit
* Browser + version: none / console

### Expected behavior:

* Importing Tickets from OTRS 5s (5.0.15) :)

### Actual behavior:

* Brake up with the following error:

> thread#3: add Ticket.find_by(id: 35601)
> ActiveRecord::UnknownAttributeError: unknown attribute 'master_slave' for Ticket.
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:35:in `each'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/core.rb:566:in `init_attributes'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/core.rb:281:in `initialize'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/inheritance.rb:61:in `new'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/inheritance.rb:61:in `new'
>         from /opt/zammad/lib/import/otrs/ticket.rb:59:in `create'
>         from /opt/zammad/lib/import/otrs/ticket.rb:46:in `create_or_update'
>         from /opt/zammad/lib/import/otrs/ticket.rb:38:in `import'
>         from /opt/zammad/lib/import/otrs/ticket.rb:30:in `initialize'
>         from /opt/zammad/lib/import/base_factory.rb:37:in `new'
>         from /opt/zammad/lib/import/base_factory.rb:37:in `create_instance'
>         from /opt/zammad/lib/import/base_factory.rb:11:in `block in import_action'
>         from /opt/zammad/lib/import/base_factory.rb:41:in `each'
>         from /opt/zammad/lib/import/base_factory.rb:41:in `import_loop'
>         from /opt/zammad/lib/import/base_factory.rb:9:in `import_action'
>         from /opt/zammad/lib/import/otrs.rb:141:in `import_action'
>         from /opt/zammad/lib/import/otrs.rb:131:in `imported?'
>         from /opt/zammad/lib/import/otrs.rb:95:in `block (3 levels) in threaded_import'
>         from /opt/zammad/lib/import/otrs.rb:89:in `loop'
>         from /opt/zammad/lib/import/otrs.rb:89:in `block (2 levels) in threaded_import'
> irb(main):005:0> thread#4: add Ticket.find_by(id: 35581)
> /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute': unknown attribute 'master_slave' for Ticket. (ActiveRecord::UnknownAttributeError)
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:35:in `each'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/core.rb:566:in `init_attributes'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/core.rb:281:in `initialize'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/inheritance.rb:61:in `new'
>         from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/inheritance.rb:61:in `new'
>         from /opt/zammad/lib/import/otrs/ticket.rb:59:in `create'
>         from /opt/zammad/lib/import/otrs/ticket.rb:46:in `create_or_update'
>         from /opt/zammad/lib/import/otrs/ticket.rb:38:in `import'
>         from /opt/zammad/lib/import/otrs/ticket.rb:30:in `initialize'
>         from /opt/zammad/lib/import/base_factory.rb:37:in `new'
>         from /opt/zammad/lib/import/base_factory.rb:37:in `create_instance'
>         from /opt/zammad/lib/import/base_factory.rb:11:in `block in import_action'
>         from /opt/zammad/lib/import/base_factory.rb:41:in `each'
>         from /opt/zammad/lib/import/base_factory.rb:41:in `import_loop'
>         from /opt/zammad/lib/import/base_factory.rb:9:in `import_action'
>         from /opt/zammad/lib/import/otrs.rb:141:in `import_action'
>         from /opt/zammad/lib/import/otrs.rb:131:in `imported?'
>         from /opt/zammad/lib/import/otrs.rb:95:in `block (3 levels) in threaded_import'
>         from /opt/zammad/lib/import/otrs.rb:89:in `loop'
>         from /opt/zammad/lib/import/otrs.rb:89:in `block (2 levels) in threaded_import'

### Steps to reproduce the behavior:

* Having a OTRS with add-on "OTRSMasterSlave" - maybe it will not appear without the add-on and the import with master_slave is just not supported?

Br,
Patrick

**Comment by martini** [comment]
Hi @patrick-fox 

the importer also created ticket attributes in Zammad based on OTRS dynamic files.

The error message says, that the field "master_slave" is not existing in Zammad.

Can you try to start the import from command line https://docs.zammad.org/en/latest/migration-otrs.html#import-via-command-line ? Or at least to restart the import again via "Import::OTRS.start"?

Note: You can start the import several time without dropping the Zammad database.

 -Martin

**Comment by patrick-fox** [comment]
Hi Martin,

I started the import via command line and it drops me out of the rails prompt back to the bash. I did the installation via develop deb and started the import directly (no interaction via browser). On a restart of the import it stops on the same location.

Br,
Patrick

**Comment by patrick-fox** [comment]
hi @martini 

I removed the Master-Slave addon from OTRS and the migration started. As soon as I only reinstall the addon (version 5.0.4) is throws the same error message.

Br,
Patrick

**Comment by thorsteneckel** [comment]
Thanks for the information. I'll take a look in the next days.

**Comment by thorsteneckel** [comment]
Hi @patrick-fox - I was able to reproduce the issue and managed to fix it. Please have a look at the commit above and please let me know if it works for you. Thanks!

**Comment by patrick-fox** [comment]
hi @thorsteneckel 

reinstalled the addon and didn't got any error regarding this issue at the import.

Thanks!

**Comment by thorsteneckel** [comment]
Nice 🚀 Thanks for the feedback.
