### ISSUE TITLE
Imap sort errors with gmail in production.log

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#568]
### Infos:

* Used Zammad version: 1.2 dev
* Operating system: linux
* Browser + version: chrome 55

### Expected behavior:

* no errors in production.log

### Actual behavior:

* errors in production log:
```
I, [2016-12-24T12:17:11.472883 #31046]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2016-12-24T12:17:11.474357 #31046]  INFO -- : fetching imap (imap.gmail.com/mailaddress@gmail.com port=993,ssl=true)
E, [2016-12-24T12:17:12.170447 #31046] ERROR -- : Unable to use imap sort: #<Net::IMAP::BadResponseError: Unknown command: SORT>, use imap search now
I, [2016-12-24T12:17:12.458735 #31046]  INFO -- :  - no message
I, [2016-12-24T12:17:12.458821 #31046]  INFO -- : done
```

### Steps to reproduce the behavior:

* create gmail channel

**Comment by martini** [comment]
JFI: I can reproduce it. We tried to sort the messages by created_at at server. But unfortunately many imap server do not support it. We need to look for a other solution.

**Comment by martini** [comment]
Normally emails are already sorted by arrival date. Additional sort at server is only optional.
