### ISSUE TITLE
Ticket Status und Rechte

### ISSUE THREAD

**Issue by ECM80** [zammad/zammad#569]
Hallo zusammen, 

kann man oder besteht die Möglichkeit, einen weiteren Status für die Tickets hinzuzufügen, wie z.B. Gelöst.

Der Hintergrund ist der, dass es sinnvoll wäre, ein Kontrollmechanismus einzubauen u den Agents die Möglichkeit zu entziehen, Tickets selber zu schließen.

Dann wäre es sehr gut, wenn man ausgewählten Agents untersagen könnte Tickets in eine andere Gruppe oder einem anderen Besitzer zu zuweisen. 

VG 

ECM80

**Comment by thorsteneckel** [comment]
This is a direct duplicate of #574 and a technical duplicate of #1525. We describe [how you can already add states via the Zammad Rails console in the documentation](https://docs.zammad.org/en/latest/console/working-on-tickets.html#add-new-ticket-state) until we resolve #1525. Closing now.
