### ISSUE TITLE
Week signature key in debian package

### ISSUE THREAD

**Issue by nidico** [zammad/zammad#572]
Debian plans to remove support for SHA1 signatures in Januar 2017, as described in 

    https://wiki.debian.org/Teams/Apt/Sha1Removal

As mentioned in #209, the zammad debian package uses a weak signature key:

    $ apt update
    [...]
    W: https://deb.packager.io/gh/zammad/zammad/dists/xenial/Release.gpg: Signature by key 6257DF9972462F57A20FFB2AB6D583CCBD33EEB8 uses weak digest algorithm (SHA1)

This should be changed!

**Comment by monotek** [comment]
We now. But there is nothing we can do about because we're not running packager.io

**Comment by nidico** [comment]
Good. I assume this is reported to packager.io? I can't find that service in the broken repository list in https://wiki.debian.org/Teams/Apt/Sha1Removal

**Comment by monotek** [comment]
I wrote them an email so.e weeks before.

You could also file a bug report @ pkgr :
https://github.com/crohr/pkgr/issues
