### ISSUE TITLE
Email Template for Renewal Password

### ISSUE THREAD

**Issue by GeraldElbaze-Medias-Cite** [zammad/zammad#577]
Hello.
I can not translate the email received for a user requesting a password renewal in French.
An idea ?

**Comment by martini** [comment]
Hi @GeraldElbaze-Medias-Cite 

yes you can. 🤓 Currently all email notifications are maintained as templates in the file system:

https://github.com/zammad/zammad/tree/develop/app/views/mailer

It would be great if you could translate it to french and create a pull request.

Just copy the english template and translate it to french via "cp en.html.erb fr.html.erb"

If you need help, just let me know!

 -Martin

**Comment by GeraldElbaze-Medias-Cite** [comment]
Hi.
I've just finishing some translations. Validate if it's okay for you.

**Comment by GeraldElbaze-Medias-Cite** [comment]
I'm going to translate others since few hours.
Can you tell me how update my own version from this git ?

**Comment by martini** [comment]
> I'm going to translate others since few hours.

Thanks for our wonderful work. I added a comments, it seems that the first line (which is use for email subject) is till in english. 

https://github.com/zammad/zammad/pull/578/files

> Can you tell me how update my own version from this git ?

With git pull you can update your git checkout:

`git pull`

If you want to used your french translations for notification emails:

1. restart the rails application server
2. login and set "French" as Zammad ui language (if it's already selected, please click update again - just to be sure)
3) Logout and reset your password

 -> The email should now be in french

Any feedback would be nice!

**Comment by GeraldElbaze-Medias-Cite** [comment]
I'm gonna translate the first lines.

**Comment by GeraldElbaze-Medias-Cite** [comment]
Hummm... install from your documentation does not take the git option... are you sure that a simple "git pull" will update my install ?

**Comment by martini** [comment]
> install from your documentation

-> Did you install via a packages (RPM/DEB/...) or from source?

> are you sure that a simple "git pull" will update my install ?

No, sorry. This will not work then.

**Comment by GeraldElbaze-Medias-Cite** [comment]
On Ubuntu via DEB...

**Comment by martini** [comment]
You have 3 options.

a) Just copy your template files on you installation into /opt/zammad/app/view/mailer/... restart the application server, set french for the user in preferences -> language (please press submit anyway), logout and reset your password (please do not forget to push the templates to github after your are finished 🙈)

b) If your pull request got merged, then your changes are in the "develop" branch. On every push a new package version is build. You can update your installation from here, just update your Zammad Repo from "stable" to "develop" (more infos at https://docs.zammad.org/en/latest/contributing-branches.html, https://docs.zammad.org/en/latest/contributing-packages.html and https://docs.zammad.org/en/latest/install-ubuntu.html#add-zammad-deb-repo-and-install)

c) If your pull request got merged, then your changes are included on next official release.

**Comment by martini** [comment]
Password reset and signup templates now in french. Other templates in french would be nice too.

https://github.com/zammad/zammad/tree/develop/app/views/mailer

Thanks @GeraldElbaze-Medias-Cite
