### ISSUE TITLE
chat.js issue...

### ISSUE THREAD

**Issue by GeraldElbaze-Medias-Cite** [zammad/zammad#579]
Chat is activated on Zammad. An agent is on for chating
This code is before the `</body>`
```
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://support.aptic.fr/assets/chat/chat.min.js"></script>
<script>
$(function() {
  new ZammadChat({
    title: '<strong> Échangez avec nous! </strong>',
    fontSize: '12px',
    flat: true,
    chatId: 1,
debug: 'true'
  });
});
</script>
```

But nothing on the page on the site: www.aptic.fr
This site is with an https access.
When I'm inspect with firebug, http became https for https://support.aptic.fr/assets/chat/chat.min.js
Any idea ?

**Comment by martini** [comment]
Hi @GeraldElbaze-Medias-Cite 

If I have a look to the html source code of www.aptic.fr I see "https://support...":

<img width="708" alt="screen shot 2017-01-03 at 15 05 27" src="https://cloud.githubusercontent.com/assets/110226/21610071/4070e44e-d1c6-11e6-8084-a1fdf9052af4.png">

For me it looks like work press is replacing http by https.

-=> However, there is a second issue, most browser will not accept http connections from a https page for security reasons. To put Zammad also to https would be a good option for later.

**Comment by martini** [comment]
@GeraldElbaze-Medias-Cite just another call for help :) https://github.com/zammad/zammad/issues/580

**Comment by GeraldElbaze-Medias-Cite** [comment]
Any documentation to put Zammad to https ?

**Comment by martini** [comment]
It's web server related. For nginx http://nginx.org/en/docs/http/configuring_https_servers.html for apache https://httpd.apache.org/docs/2.4/ssl/ssl_howto.html

PS: If you want to test the chat it independent of your installation, you also can use a instance from https://zammad.com/getting-started (it's free for 30 days).

**Comment by GeraldElbaze-Medias-Cite** [comment]
Thanks. I already have an instance on zammad.com :-)

**Comment by monotek** [comment]
@martini
How about a oneclick letsencypt addon, which creates SSL certs which works on all browsers?

Should be easy using:
https://github.com/lgromanowski/letsencrypt-plugin
https://github.com/unixcharles/acme-client

**Comment by martini** [comment]
@monotek welcome back! 🍻

For me it's not clear what the goal of letsencrypt & acme-client is, "only" to easily create SSL certificate? You still need to configure nginx/apache, right?

**Comment by monotek** [comment]
Still on the road... Just have some time as I'm the codriver at the moment. I'll be back tomorrow ;-)

You never used letsencypt? -> https://letsencrypt.org

The CLI client can also change your webserver config. Not sure if the rails plugin is also able to do it. Was just an idea when I saw the http/https issue...

**Comment by martini** [comment]
> You never used letsencypt? -> https://letsencrypt.org

No. 🤔 But maybe it's off topic in this issue (it's wordpress related - it's replacing http with https in script tags).

**Comment by martini** [comment]
@GeraldElbaze-Medias-Cite I close it, it's not Zammad related.
