### ISSUE TITLE
LDAP authentication and authorization

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#58]
This is a must have in a majority if organizations.

**Comment by Julian0o** [comment]
Do you have some news about the ldap integration?

**Comment by wagnst** [comment]
:+1:  for this feature. We have a quite complex LDAP setup, where we could test it!

**Comment by martini** [comment]
JFI: I already told it Julian, we are working on "enterprise ready" features for Q1 2017. It will include also LDAP authentication and LDAP user information (maybe also exchange integration like GAL).
