### ISSUE TITLE
French for Chat widget

### ISSUE THREAD

**Issue by martini** [zammad/zammad#580]
https://github.com/zammad/zammad/blob/develop/public/assets/chat/chat.coffee#L182

A french translation for the chat widget would be fine! Thanks a lot!

```
fr:
  '<strong>Chat</strong> with us!': '<strong>Chatte</strong> mit uns!'
  'Scroll down to see new messages': 'Scrolle nach unten um neue Nachrichten zu sehen'
  'Online': 'Online'
  'Online': 'Online'
  'Offline': 'Offline'
  'Connecting': 'Verbinden'
  'Connection re-established': 'Verbindung wiederhergestellt'
  'Today': 'Heute'
  'Send': 'Senden'
  'Compose your message...': 'Ihre Nachricht...'
  'All colleagues are busy.': 'Alle Kollegen sind belegt.'
  'You are on waiting list position <strong>%s</strong>.': 'Sie sind in der Warteliste an der Position <strong>%s</strong>.'
  'Start new conversation': 'Neue Konversation starten'
  'Since you didn\'t respond in the last %s minutes your conversation with <strong>%s</strong> got closed.': 'Da Sie in den letzten %s Minuten nichts geschrieben haben wurde Ihre Konversation mit <strong>%s</strong> geschlossen.'
  'Since you didn\'t respond in the last %s minutes your conversation got closed.': 'Da Sie in den letzten %s Minuten nichts geschrieben haben wurde Ihre Konversation geschlossen.'
```

**Comment by GeraldElbaze-Medias-Cite** [comment]
update translation is done.
but seems dont work...
i see it again.

**Comment by martini** [comment]
Can you share the french chat widget translation with me (just the 15 lines above). Then I'll test it.

PS: This issue is just about the french translation of the chat widget which is done in https://github.com/zammad/zammad/blob/develop/public/assets/chat/chat.coffee#L182

**Comment by GeraldElbaze-Medias-Cite** [comment]
fr:
        '<strong>Chat</strong> with us!': '<strong>Chattez</strong> avec nous!'
        'Scroll down to see new messages': 'Faites défiler pour lire les nouveaux messages'
        'Online': 'En-ligne'
        'Online': 'En-ligne'
        'Offline': 'Hors-ligne'
        'Connecting': 'Connexion en cours'
        'Connection re-established': 'Connexion rétablie'
        'Today': 'Aujourdhui'
        'Send': 'Envoyer'
        'Compose your message...': 'Composez votre message...'
        'All colleagues are busy.': 'Tous les collègues sont actuellement occupés.'
        'You are on waiting list position <strong>%s</strong>.': 'Vous êtes actuellement en <strong>%s</strong> position dans la file d'attente.'
        'Start new conversation': 'Démarrer une nouvelle conversation'
        'Since you didn\'t respond in the last %s minutes your conversation with <strong>%s</strong> got closed.': 'Si vous ne répondez pas dans les %s minutes, votre conversation avec <strong>%s</strong> va être fermée.'
        'Since you didn\'t respond in the last %s minutes your conversation got closed.': 'Si vous ne répondez pas dans les %s minutes, votre conversation va être fermée.'

**Comment by GeraldElbaze-Medias-Cite** [comment]
`fr:
        '<strong>Chat</strong> with us!': '<strong>Chattez</strong> avec nous!'
        'Scroll down to see new messages': 'Faites défiler pour lire les nouveaux messages'
        'Online': 'En-ligne'
        'Online': 'En-ligne'
        'Offline': 'Hors-ligne'
        'Connecting': 'Connexion en cours'
        'Connection re-established': 'Connexion rétablie'
        'Today': 'Aujourdhui'
        'Send': 'Envoyer'
        'Compose your message...': 'Composez votre message...'
        'All colleagues are busy.': 'Tous les collègues sont actuellement occupés.'
        'You are on waiting list position <strong>%s</strong>.': 'Vous êtes actuellement en <strong>%s</strong> position dans la file d'attente.'
        'Start new conversation': 'Démarrer une nouvelle conversation'
        'Since you didn\'t respond in the last %s minutes your conversation with <strong>%s</strong> got closed.': 'Si vous ne répondez pas dans les %s minutes, votre conversation avec <strong>%s</strong> va être fermée.'
        'Since you didn\'t respond in the last %s minutes your conversation got closed.': 'Si vous ne répondez pas dans les %s minutes, votre conversation va être fermée.'`

**Comment by martini** [comment]
@GeraldElbaze-Medias-Cite I'm sorry. You are right. After adding the french translation, the chat.coffee need to be compile to .js. -> I already prepared the commit which you can use. 

I just found one not translated string 😮, could your translate it to french too (then I'll push it ASAP)?

'We are sorry, it takes longer as expected to get an empty slot. Please try again later or send us an email. Thank you!'

**Comment by martini** [comment]
In the meantime the current state.

<img width="400" alt="screen shot 2017-01-05 at 10 17 54" src="https://cloud.githubusercontent.com/assets/110226/21674954/4cb82300-d330-11e6-8976-aef104b7cf8c.png">
<img width="439" alt="screen shot 2017-01-05 at 10 02 25" src="https://cloud.githubusercontent.com/assets/110226/21674955/4cb8c8fa-d330-11e6-827e-f08826118041.png">

Just update your public/assets/chat/chat.js / public/assets/chat/chat.min.js from https://raw.githubusercontent.com/zammad/zammad/develop/public/assets/chat/chat.js / https://raw.githubusercontent.com/zammad/zammad/develop/public/assets/chat/chat.min.js on your server and you will have the french translation of the chat widget.

**Comment by martini** [comment]
Just a developer note, the chat widget is written in coffee script (the good parts of java script). If you change something in public/assets/chat/chat.coffee you need to "compile" the .coffee into .js by:

```
cat public/assets/chat/
gulp
```
