### ISSUE TITLE
OTRS import - long content type shows warning and gets cut

### ISSUE THREAD

**Issue by patrick-fox** [zammad/zammad#582]
Hi!

### Infos:

* Used Zammad version: 1.2.0-1483439417.f4c411d.xenial
* Operating system: Ubuntu 16
* Browser + version: n/a

### Expected behavior:

* I'm trying to import from OTRS 5.0.15 into latest dev Zammad. I would expect no warnings ;)

### Actual behavior:

*  I got the following warnings:

> WARNING: cut string because of database length Ticket::Article.content_type(20 but is 25:text/plain; charset=utf-8)
> WARNING: cut string because of database length Ticket::Article.content_type(20 but is 25:text/plain; charset=utf-8)
> thread#1: add Ticket::Article.find_by(id: 98497)
> WARNING: cut string because of database length Ticket::Article.content_type(20 but is 25:text/plain; charset=utf-8)
> thread#6: add Ticket::Article.find_by(id: 98674)
> WARNING: cut string because of database length Ticket::Article.content_type(20 but is 25:text/plain; charset=utf-8)
> thread#2: loading 20 Ticket starting at 340...

### Steps to reproduce the behavior:

* I use the latest Zammad and OTRS, only with Survey Addon installed. The attachments are stored on file base, not in the database. OTRS DB is MySQL (5.0.95) in CentOS 5.x, Zammad is using postgresql. Import is started via cmd.

Br,
Patrick

**Comment by thorsteneckel** [comment]
Hi @patrick-fox - fixed it with the latest commit above. Could you please verify the change?

**Comment by patrick-fox** [comment]
Dear @thorsteneckel 

I just restarted the import after upgrading to commit 8ac1ba9e (1.2.0-1484493932.8ac1ba9.xenial) and got still the same error:

> thread#8: update Ticket::Article.find_by(id: 42755)
> WARNING: cut string because of database length Ticket::Article.content_type(20 but is 25:text/plain, charset=utf-8)
> thread#8: update Ticket::Article.find_by(id: 42760)
> thread#8: update Ticket::Article.find_by(id: 42761)

**Comment by thorsteneckel** [comment]
Hi @patrick-fox - Thanks for your feedback. I also added your last information to the possible cases list. JFI: Usually the content type separator is a `;` not a `,` (maybe a mail client issue). Nevertheless I added it to the list of possible separators. Should now in this case, too.

**Comment by patrick-fox** [comment]
hi @thorsteneckel - Works fine now, thanks! 👍

**Comment by thorsteneckel** [comment]
You're welcome. Thanks for the feedback.
