### ISSUE TITLE
Customer stays in the old Organisation after moving a User to antoher Organisation

### ISSUE THREAD

**Issue by AdiosOnline** [zammad/zammad#583]
Hi,

We imported the customer Users via direct DB input. (Navicat)

There were some errors in the Source Excel-File with the Organisation_id. After we corrected the errors, the Customer User view is fine, but the customer is still listet in the Organisation, which was used before the correction. 

### Infos:

* Used Zammad version: 1.1.1 (2016-12-14)
* Operating system: CentOS 7
* Browser + version: Chrome 55.0.2883.87, Firefox 50.1, 

### Expected behavior:
The customer should be completely moved to the other Organisation, after changing the assigned company/Organisation
* 

### Actual behavior:
The User Profile gets updated, but the Organisation still shows the moved User
* 

### Steps to reproduce the behavior:
Change Users, Organisation and look into the old Organisation's Users List in the Frontend
* 

Kind Regards,
Jorrit

**Comment by thorsteneckel** [comment]
Sorry to say but direct DB input of data is not supported.
