### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by GeraldElbaze-Medias-Cite** [zammad/zammad#585]
Hi.
Really nice job this tool... !
I'm trying to know where i can find some chat history... some answers may be very useful for other agent. And i want to know if the answers of the other agents are good...

Thanks...

(I gonna make the french translations too ;-) )

### Infos:

* Used Zammad version: 
* Operating system: 
* Browser + version: 

### Expected behavior:

* 

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment]
HI @GeraldElbaze-Medias-Cite - thanks! Would #422 help you?

**Comment by mkrauser** [comment]
Hey there, 

a lot of our customers are requesting full chat-transcripts. This would be lovely to have!

**Comment by thorsteneckel** [comment]
Hi @mkrauser - is #422 what you are looking for?

**Comment by mkrauser** [comment]
@thorsteneckel I think #442 would also cover this

**Comment by thorsteneckel** [comment]
So I'll flag this as an duplicate. Further input in #422 is welcome
