### ISSUE TITLE
Group restrictions not respected in slack notification

### ISSUE THREAD

**Issue by hhoechtl** [zammad/zammad#587]
### Infos:

* Used Zammad version: stable branch from 2016-12-29
* Operating system: Docker
* Browser + version: Chrome

### Expected behavior:

* Slack notifications only for configured groups

### Actual behavior:

* Slack notifications for all groups

### Steps to reproduce the behavior:

* Incoming E-Mail ticket for a mailaccount configured to auto assign group "management" to ticket
* Slack integration configured only to notify about new tickets on all groups except "management"

**Comment by martini** [comment]
@jepf thanks for the bugfix.

**Comment by martini** [comment]
@hhoechtl Thanks for the really good description.
