### ISSUE TITLE
API Call crashes webinterface - or search?

### ISSUE THREAD

**Issue by pbengert** [zammad/zammad#588]
I tried to write a small program with Autohotkey to automate the creation of tickets via a little windows client. Calling the API with wrong parameters ist accepted, after that no more tickets are show or can be searched in the webinterface.

Details: Zammad 1.1.1 on Ubuntu 16.04 installed via deb on Hyper-V Server.

API-Call from Autohotkey:

WinHTTP2 := ComObjCreate("WinHTTP.WinHttpRequest.5.1")
WinHTTP2.Open("POST", "http://192.168.100.6:3000/api/v1/tickets", 0)
WinHTTP2.SetRequestHeader("Content-Type", "application/json")
WinHTTP2.SetRequestHeader("Authorization", "Token token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
Body = {"title":"%title%", "group_id":1, "owner_id":0, "state_id":2, "priority_id":2, "customer_id": 18, "article":{"subject":"%Titel%", "body":"%Anfrage%"} } ; ich glaube owner_id 0 oder "null" killt das System!
WinHTTP2.Send(Body)
Result := WinHTTP2.ResponseText
Status := WinHTTP2.Status

-> the problem seems to be "owner_id:0" which seems not to valid but is accepted as valid
-> leaving it away -> no problem
-> send it -> problem can be reproduced
-> Solution: go back with hyper-v to an older snapshot

Details form /var/log/zammad/production.log
I, [2017-01-05T13:01:22.759064 #1110]  INFO -- : Started POST "/api/v1/tickets" for 192.168.1.13 at 2017-01-05 13:01:22 +0100
I, [2017-01-05T13:01:22.769359 #1110]  INFO -- : Processing by TicketsController#create as */*
I, [2017-01-05T13:01:22.769566 #1110]  INFO -- :   Parameters: {"title"=>"", "group_id"=>1, "owner_id"=>0, "state_id"=>2, "priority_id"=>2, "customer_id"=>18, "article"=>{"subject"=>"", "body"=>""}, "ticket"=>{"group_id"=>1, "priority_id"=>2, "state_id"=>2, "title"=>"", "owner_id"=>0, "customer_id"=>18}}
I, [2017-01-05T13:01:23.026323 #1110]  INFO -- : Completed 201 Created in 257ms (Views: 1.7ms | ActiveRecord: 67.0ms)
I, [2017-01-05T13:01:26.716356 #1094]  INFO -- : 2017-01-05T13:01:26+0100: [Worker(host:ubuntu pid:1094)] Job Observer::UserDeviceLogJob (id=194) RUNNING
I, [2017-01-05T13:01:26.755990 #1094]  INFO -- : Send notification to: XXXXXXXXXX (from Notification Master <XXXXXXXXXXXXXXXXX>)
I, [2017-01-05T13:01:27.133664 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job Observer::UserDeviceLogJob (id=194) COMPLETED after 0.4171
I, [2017-01-05T13:01:27.142411 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job ApplicationModel::BackgroundJobSearchIndex (id=195) RUNNING
E, [2017-01-05T13:01:27.175153 #1094] ERROR -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job ApplicationModel::BackgroundJobSearchIndex (id=195) FAILED (0 prior attempts) with NoMethodError: undefined method `lookup' for NilClass:Class
Did you mean?  loop
I, [2017-01-05T13:01:27.190515 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=196) RUNNING
I, [2017-01-05T13:01:27.286685 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=196) COMPLETED after 0.0959
I, [2017-01-05T13:01:27.292510 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job ApplicationModel::BackgroundJobSearchIndex (id=197) RUNNING
I, [2017-01-05T13:01:27.297033 #1094]  INFO -- : # curl -X POST "http://127.0.0.1:9200/zammad_production/User/18" \
I, [2017-01-05T13:01:27.373930 #1094]  INFO -- : # 200
I, [2017-01-05T13:01:27.382603 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job ApplicationModel::BackgroundJobSearchIndex (id=197) COMPLETED after 0.0899
I, [2017-01-05T13:01:27.388322 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job ApplicationModel::BackgroundJobSearchIndex (id=198) RUNNING
E, [2017-01-05T13:01:27.403517 #1094] ERROR -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job ApplicationModel::BackgroundJobSearchIndex (id=198) FAILED (0 prior attempts) with NoMethodError: undefined method `lookup' for NilClass:Class
Did you mean?  loop
I, [2017-01-05T13:01:27.424805 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=199) RUNNING
I, [2017-01-05T13:01:27.437051 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=199) COMPLETED after 0.0120
I, [2017-01-05T13:01:27.442844 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job ApplicationModel::BackgroundJobSearchIndex (id=200) RUNNING
I, [2017-01-05T13:01:27.445109 #1094]  INFO -- : # curl -X POST "http://127.0.0.1:9200/zammad_production/User/18" \
I, [2017-01-05T13:01:27.505556 #1094]  INFO -- : # 200
I, [2017-01-05T13:01:27.513909 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job ApplicationModel::BackgroundJobSearchIndex (id=200) COMPLETED after 0.0709
I, [2017-01-05T13:01:27.523688 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job Transaction::BackgroundJob (id=201) RUNNING
I, [2017-01-05T13:01:27.658847 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job Transaction::BackgroundJob (id=201) COMPLETED after 0.1350
I, [2017-01-05T13:01:27.665428 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job ApplicationModel::BackgroundJobSearchIndex (id=202) RUNNING
I, [2017-01-05T13:01:27.668379 #1094]  INFO -- : # curl -X POST "http://127.0.0.1:9200/zammad_production/User/18" \
I, [2017-01-05T13:01:27.738078 #1094]  INFO -- : # 200
I, [2017-01-05T13:01:27.744043 #1094]  INFO -- : 2017-01-05T13:01:27+0100: [Worker(host:ubuntu pid:1094)] Job ApplicationModel::BackgroundJobSearchIndex (id=202) COMPLETED after 0.0784

Peter

**Comment by martini** [comment]
@pbengert thanks for the excellent issue report. We added id validation to the models. Will be available in upcoming 1.2 in one week.
