### ISSUE TITLE
Sites for organizations

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#589]
Hello,

we have some organizations with multiple sites an want to connect the tickets to a specific site. We cannot use multiple organizations for this purpose, because the customer who reports an issue can work in different sites and only have one email address. So we cannot add the customer in multiple organization-sites.

Is it possible to add a list of sub-organizations as an additional organization-attribute?
In ticket creation it has to be possible to select one of these sub-organization or the main organization, even if the customer is only connected to the main organization.

An other solution possible for us, is that one customer can be employed in multiple organizations, we can create an organization for each site, attach the customer to each of these organization-sites and while ticket creation the agent can select the correct organization-site.

Greetings
tobibe

**Comment by vaibhavgeek** [comment]
Hi,

I have the same query right now. May I know how you solved it @tobibe.

One way could be to launch a new db instance for every sub-organisation that you have but that would be super memory intensive. I think a better idea would be to have some field/custom attribute in table of database. 
Regards,
Vaibhav Maheshwari

**Comment by MrGeneration** [comment]
Please head over to https://community.zammad.org - our issue tracker is the wrong place for this :(
Closing now.
