### ISSUE TITLE
PDF attachment is opened as text (wrong Content-Type detected)

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#593]
I hit a bug when I try to open this:
https://linuxhotel.zammad.com/api/v1/ticket_attachment/606/3881/5012

Zammad sets the header:
Content-Type:"text/html; name="xxx.pdf""

So the file is opened as text.

**Comment by muhammadn** [comment]
Is this bug fixed? i have checked downloading PDF attachment for a ticket on develop branch and Content-Type look ok - Content-Type:application/pdf

**Comment by hanneshal** [comment]
Closed.
Please reopen when this issue still exists in 2.0.

**Comment by zabarabab** [comment]
same same

**Comment by hanneshal** [comment]
@zabarabab does this happen also for new tickets or just for the old ones?

**Comment by thorsteneckel** [comment]
Please provide feedback which ticket/attachment is affected or how to reproduce. Closing for now.
