### ISSUE TITLE
Gitlab Auth not working

### ISSUE THREAD

**Issue by firlevapz** [zammad/zammad#596]
### Infos:

* Used Zammad version: installed from deb-package: 1.1.1-1483358083.c5f9f2c.xenial
* Operating system: Ubuntu 16.04.1 LTS
* Browser + version: Firefox 50.1.0

### Expected behavior:

* Gitlab Authentication enabled, but doesnt work. 

### Actual behavior:

* Gitlab login Icon is invisible on front-page
* 404: Not Found page displayed

Output of `production.log`:
```
`I, [2017-01-09T08:32:27.789974 #81]  INFO -- : Started GET "/auth/gitlab" for --- at 2017-01-09 08:32:27 +0100
I, [2017-01-09T08:32:27.791337 #81]  INFO -- : Processing by ErrorsController#routing as HTML
I, [2017-01-09T08:32:27.791377 #81]  INFO -- :   Parameters: {"a"=>"auth/gitlab"}
E, [2017-01-09T08:32:27.792003 #81] ERROR -- : No route matches [GET] /auth/gitlab
E, [2017-01-09T08:32:27.792032 #81] ERROR -- : nil
I, [2017-01-09T08:32:27.792626 #81]  INFO -- :   Rendered inline template (0.3ms)
I, [2017-01-09T08:32:27.793435 #81]  INFO -- : Completed 404 Not Found in 2ms (Views: 0.5ms | ActiveRecord: 0.2ms)
```

### Steps to reproduce the behavior:

* Activate Gitlab Authentication

**Comment by Ilya-Kuchaev** [comment]
I have the same issue.

**Comment by martini** [comment]
JFI: I'm also able to reproduce.

**Comment by martini** [comment]
@Ilya-Kuchaev It's fixed in develop branch now. I'll improve the ui now...

**Comment by martini** [comment]
JFI: UI improvement will be done in other issue.

**Comment by firlevapz** [comment]
Gitlab auth is now working, but i had to add an extra field `address` to the Zammad User object to get it working, otherwise an 500 Error was shown...

**Comment by satheeshrajan** [comment]
@firlevapz Can you please update that in which file or the location that we need to update the field "address" to make the gitlab authentication working for Zammad.

Thanks

**Comment by MrGeneration** [comment]
@satheeshrajan please don't recycle old issues.
I think @firlevapz meant a custom object within the user space.

If this is no bug, please refer to our community for further technical questions: https://community.zammad.org (locking conversation now)
