### ISSUE TITLE
If "new ticket created" popover is shown you can't click search box

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#597]
### Infos:

* Used Zammad version: 1.2 dev
* Operating system: linux
* Browser + version: chrome 55

### Expected behavior:

* searchbox cklickable

### Actual behavior:

* searchbox blocked

### Steps to reproduce the behavior:

* create new ticket
* when "new ticket created" popover is shown try to click the search box

**Comment by martini** [comment]
Hi @monotek 

how long is the "new ticket created" toaster shown? Show not be longer then 4 sec.

 -Martin

**Comment by monotek** [comment]
True, but its still annoying to wait for it if you want to work fast. Imho Popover should be go away as soon somebody clicks somewhere else

**Comment by martini** [comment]
@monotek thanks, fixed.

ProTip: ctrl+alt+s 😜
