### ISSUE TITLE
Elasticsearchs mapper-attachments plugin has been deprecated, use ingest-attachment now

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#599]
Elasticsearchs mapper-attachments plugin has been deprecated and will be replaced by ingest-attachment plugin completely in ES 6.0

Unfortunately its not possible to just replace the plugins because they work a bit different. 

Zammad needs to support both of them for ES 2.4 users, which could be done by getting node info from es ( curl -XGET 'http://localhost:9200/_nodes/plugins' ), looking which attachment plugin is used and use a setting to use the one or the other method to speak to the plugin / create the index & mapping. Setting could also set manually by changing ES install docs for 2.4 and 5.0.

Some infos about the new plugin & migration can be found here:

* https://discuss.elastic.co/t/implementing-ingest-attachment-processor-plugin/52300
* https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html
* https://github.com/rahulsinghai/elasticsearch-ingest-attachment-plugin-example

**Comment by nublaii** [comment]
+1

**Comment by monotek** [comment]
@martine 

This is getting urgent now as Elasticsearch 5.6 wont start with mapper-attachments plugin installed.

`java.lang.IllegalArgumentException: plugin [mapper-attachments] is incompatible with version [5.6.0]; was designed for version [5.5.0]
`

**Comment by HLFH** [comment]
On Ubuntu 16.04, I have Version: 5.6.3, Build: 1a2f265/2017-10-06T20:33:39.012Z, JVM: 1.8.0_131.
And it seems, I have a lot of issues with Elasticsearch because of the deprecated mapper-attachments.

What can I do?
Is there some workaround?

**Comment by thorsteneckel** [comment]
No changes. Contributions are highly appreciated.

**Comment by martini** [comment]
ingest-attachment is supported with ES 5.6 now by Zammad 2.2. 

ES 6.0 support will be handled in issue #1688

**Comment by monotek** [comment]
👍
