### ISSUE TITLE
CMDB - Configuration Management Database

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#604]
Flavio wrote us:

> I'd love to see some form of hardware-management like a CMDB where I can overview my inventory (the only reason why we didn't switch to zammad from our current ticketing system).

**Comment by nmazzon** [comment]
me too..

CMDB the only reason why we didn't switch to zammad from our current ticketing system

**Comment by aptdamia** [comment]
Same here, this was declared a must by the customer.

**Comment by monotek** [comment]
https://www.i-doit.com/ will be supported soon.

**Comment by Julian0o** [comment]
Something new to this?

**Comment by martini** [comment]
Just take current 2.1 and have a look into integrations -> i-doit. The Zammad part is available for testing (not officially). The i-doit part will come soon (it's not in our hand). If you want to get the i-doit files earlier, please contact https://twitter.com/cwrm (is the guy who did work on the Zammad<->i-doit integration, he is also i-doit/synetics Partner and Reseller).

**Comment by martini** [comment]
Update: https://www.i-doit.com/ is officially supported in upcoming version. No extensions in i-doit are needed anymore. Zammad is also supported there out of the box. Thanks to @cwrm and Synetics.
