### ISSUE TITLE
Overview with custom ticket-objects

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#607]
Hello,

I'd like to create an overview with a condition filtered by a custom made ticket object (Admin -> Objects -> Ticket -> New Attribute).
At the moment, I only can choose the built-in attributes.

Is it possible to add them to the selection in Admin -> Overview -> New Overview -> Conditions for shown tickets?

Greetings
tobibe

**Comment by thorsteneckel** [comment]
Good question. This should work as you described. Sounds like a bug @martini

**Comment by hanneshal** [comment]
Works fine in 2.0. 
Please reopen when you can reproduce this behaviour in 2.0.
