### ISSUE TITLE
Text Modules and Shortcuts

### ISSUE THREAD

**Issue by hpaar** [zammad/zammad#608]
I am not quite sure if this is here the right forum, but I am having issues using Text Modules and Shortcuts.
I am using Zammad 1.1.1 on Debian.

Independently the browser I use Text Modules and Shortcut do not work. I can't find anybody else having this issue but I would appreciate any help on this matter. Thank you.

**Comment by thorsteneckel** [comment]
Please provide information on the browser versions you have tested. Your operating system would be interesting, too.

**Comment by hpaar** [comment]
Hi,

Mac OS X 10.11.6
Safari 10.0.2
Firefox (newest)
Chrome (newest)

Thank you for your help 

Regards

**Comment by hpaar** [comment]
Hi,
i am not quite sure how text modules are used in Zammad and I couldn't find any document on that. I only that this function exists from screenshots. Thank you for help.

**Comment by rolfschmidt** [comment]
Hello @hpaar 
currently there is no open issue i know about the text modules. I will try to explain you the feature.

1. Click into your admin interface through the preference icon on the left bottom next to your profile icon.

2. Open the text modules admin interface to configure your text modules:

![zammad_text_modules_1](https://cloud.githubusercontent.com/assets/5445062/22106322/83d5c248-de48-11e6-91a2-f56b6c3e9ee8.png)

3. In my case there is for example a german text module with the shortcut "ff" for the sentence "Für weitere Fragen stehe ich gerne zur Verfügung" which means "For any questions I am to you gladly at the disposal"

4. After the configuration you can go in one of your tickets to use that text module in new articles:

![zammad_text_modules_2](https://cloud.githubusercontent.com/assets/5445062/22106368/b7e082f8-de48-11e6-9d36-6260171d78ce.png)

5. You press "::" and then the shortcut you configured. After clicking your favourite shortcut or pressing enter you will see the replaced text like this:

![zammad_text_modules_3](https://cloud.githubusercontent.com/assets/5445062/22106398/d2487772-de48-11e6-8e8f-03ec588e8648.png)

Feel free to reopen this issue if you have any more questions regarding this topic.

Have fun!

Best regards,
Rolf
