### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by vincling** [zammad/zammad#609]
Hi, 

i have some trouble with installation of the latest stable version on Debian 8. 

- The package installation failed on postgresql due to encoding issues. Which encoding is expected to be set? I can not find any information on that. 

-> "createdb: database creation failed: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)"

- I switched to mysql installation, which failes because of already existing users and therefore access issues. I took a look at the scripts and i think its because of PW recreation everytime the script runs? Or am i getting something wrong? I have no other idea why the access problems should happen. 
The Rake aborts with mysql error "Access denied". 

What I have done was deleting the debian user "zammad" including home dir, deleted the database.yml and run the postinstall.sh.

On a AWS Machine the package installation was done in minutes,
The Debian Image I am using is a regular openvz image, with some modifications like apache preinstalled, but the core is not modified at all. 

Do such issues occure due to failed installations earlier? 
Is there any other way to fix this without a clean setup, or would it be the easiest way? 
A info about the encoding part would be great for our internal documentation for the future, as we plan to provide zammad to more client services. 

thanks a lot 
magda

**Comment by monotek** [comment]
You need to set the locale to UTF-8 before installing Zammad. Otherwise postgresql does not work.

```
apt-get install locales
locale-gen en_US.UTF-8
echo "LANG=en_US.UTF-8" > /etc/default/locale
```

You problem with mysql could be that config/database.yml already exist from the first run of postinstall.sh with postgres. Deleting this file should help. Existing Mysql users are no problem in Debian, becaue /etc/mysql/debian.cnf should be used for mysql auth.

**Comment by vincling** [comment]
Does it have to be en_US? It was on de_DE UTF8

I deleted the database.yml every time before rerun of postinstall, thats why it is so weired to get the user access denied error. 

⁣

Gesendet mit BlueMail ​

**Comment by monotek** [comment]
It doesn't matter which UTF-8 setting is used. 
I personally already used de_DE.UTF-8 & en_US.UTF-8 locales.

Please post the output of the "locale" command.
If its already UTF-8 the error should would not say its "SQL_ASCII".
