### ISSUE TITLE
WebHook support like in gitlab or github

### ISSUE THREAD

**Issue by martini** [zammad/zammad#616]
WebHook support like in gitlab or github

<img width="1097" alt="screen shot 2017-01-13 at 13 25 57" src="https://cloud.githubusercontent.com/assets/110226/21929985/e8aa0152-d993-11e6-9113-a7c4636c0032.png">
<img width="1096" alt="screen shot 2017-01-13 at 13 25 00" src="https://cloud.githubusercontent.com/assets/110226/21929986/e8e12484-d993-11e6-9f93-d34e7b557cab.png">

**Comment by albertosgz** [comment]
Is it related with ticket #290 ?

**Comment by thorsteneckel** [comment]
@albertosgz ++ looks like a duplicate to me.

**Comment by albertosgz** [comment]
@thorsteneckel me too
so, maybe we can add the explanation to #290 and close this because of duplicate

**Comment by thorsteneckel** [comment]
done!
