### ISSUE TITLE
Elasticsearch index not been build

### ISSUE THREAD

**Issue by hpaar** [zammad/zammad#625]
Hi,

I am running the latest zammad (1.1.1) with elasticsearch on Debian8. Installation of zammad and elasticsearch went fine, but when I want to rebuild the index ("zammad run rake search index:rebuild") the following message error:

opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/zammad/bin in PATH, mode 040777
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/zammad/vendor/bundle/ruby/2.3.0/bin in PATH, mode 040777
drop indexes...
create indexes...
rake aborted!
Unable to process PUT at http://127.0.0.1:9200/zammad_production
#<UserAgent::Result:0x007f0b407b6338 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:9200 (Connection refused - connect(2) for \"127.0.0.1\" port 9200)>">
/opt/zammad/lib/search_index_backend.rb:62:in `index'
/opt/zammad/lib/tasks/search_index_es.rake:19:in `block (2 levels) in <top (required)>'
/opt/zammad/lib/tasks/search_index_es.rake:60:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => searchindex:rebuild
(See full trace by running task with --trace)

For me it seems that the index has bot been build. Any help here is appreciated. Thank you.

**Comment by thorsteneckel** [comment]
Hi @hpaar - looks like your ElasticSearch is not running (at port 9200): `Failed to open TCP connection to 127.0.0.1:9200 (Connection refused - connect(2) for "127.0.0.1" port 9200)`.

Can you make sure it's available?

**Comment by thorsteneckel** [comment]
PS: If it's running - could you try `localhost` instead of `127.0.0.1`?

**Comment by hpaar** [comment]
Hi,
indeed the solution was here using localhost instead of 127.0.0.1. Thank you for help.

**Comment by thorsteneckel** [comment]
Nice. Thanks for leaving feedback.
