### ISSUE TITLE
eMail Ticket but no answer link available!!!

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#626]
One of my tickets has a weird behavior! It's an incoming email ticket, but there is no link to write an answer to the sender. The email adress of the customer is correct (I've wiped private information in the screenshot for privacy reasons).

Any idea what's wrong here and how I can answer the ticket?

![image](https://cloud.githubusercontent.com/assets/3321655/21986480/eaf27af2-dbff-11e6-9326-f047ac529fe9.png)

**Comment by jacotec** [comment]
Hi,

is there any status on this? Anything I can do to help you here with information?

Today I had the second ticket with this issue, and I can't respond to the customer. Any cryptic Rails commands to get the ability to answer back on these tickets?

**Comment by martini** [comment]
Hi @jacotec 

this is usually if the group of the ticket has no sender address assigned. Can you check this? (after assigning, just to be sure - reload the app)

 -Martin

**Comment by martini** [comment]
Any feedback?

**Comment by jacotec** [comment]
Hi @martini ,

sorry for the delay, I was extremely busy. I did doublecheck that and you are right: The sender address was not properly assigned for this certain group. I should have seen this :-|

Thank you for the solution!
