### ISSUE TITLE
Option to not create ticket on retweet

### ISSUE THREAD

**Issue by schurig** [zammad/zammad#627]
It would be nice to turn off ticket creation on retweets. Quotes are fine in most cases but Zammad currently also creates a ticket for every single retweet.

**Comment by rixx** [comment]
This has been implemented by now.

**Comment by MrGeneration** [comment]
Oh wow - that one was under our radar, true, the option already exists!
Thanks for the follow up :)

This has been added with:
https://github.com/zammad/zammad/commit/b8015d5ba18fc08795a48fdda618dbab469041ed

**Comment by rixx** [comment]
Actually, I'm not sure that closing this issue is correct – I activated the option and I still receive new tickets for incoming retweets.

**Comment by MrGeneration** [comment]
Please ensure that the retweetet tweet Zammad imports does not contain a search phrase.
If this still persists (even though it's working as expected on my end), please share the used Zammad-Version, used Browser, used database and installation type (docker, package or source)

**Comment by rixx** [comment]
They do contains a search phrase, but as they are still retweets, I don't see why they should open separate tickets. As long as this behaviour cannot be changed, the Twitter integration is nearly unusable to us.

**Comment by MrGeneration** [comment]
Thanks for your feedback!

As this is a follow up on a closed/solved issue, I created a new issue on this. Please note that we rather see this as an enhancement at the moment.

You can find it here: #2571
