### ISSUE TITLE
Split too long tweets into multiple tweets 

### ISSUE THREAD

**Issue by schurig** [zammad/zammad#628]
If a twitter reply is too long I expect Zammad to split it for me and send multiple tweets.

# Example

## Reply

> Poke mollit try-hard gastropub labore, magna incididunt laborum live-edge mixtape ennui copper mug. Trust fund sriracha letterpress, small batch man braid man bun sapiente edison bulb meh kitsch fanny pack scenester af hell of slow-carb.

## Tweets

1. _Poke mollit try-hard gastropub labore, magna incididunt laborum live-edge mixtape ennui copper mug. Trust fund sriracha letterpress 1/2_

> (do not break words)

2. _small batch man braid man bun sapiente edison bulb meh kitsch fanny pack scenester af hell of slow-carb. 2/2_

**Comment by martini** [comment]
Since twitter tweet limit has changed from 140 to 280 chars I guess it's not needed anymore. 

If you feel it's still needed, just reopen this issue. Thanks!

 -Martin
