### ISSUE TITLE
Article creation time

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#634]
Hello,

is it possible to deactivate time calculation in ticketview. (The "36 minutes ago" note)
![ago](https://cloud.githubusercontent.com/assets/9305993/22021720/0c6cbd9a-dcbf-11e6-864d-4d6b07ca86ce.PNG)

We'd like to always see the real time, when the article was created (same as in older tickets). Now we have to move the mouse over the time to get the creation date or to calculate it in mind.

Maybe this could be an option in settings.

Greetings
tobibe

**Comment by martini** [comment]
Some more info: Currently we only show the first 7 days as "xxx ago", then we show the real date. Would this fit for you?

**Comment by tobibe** [comment]
No, sadly not. 
I.e.: on Monday morning, there was an article with "2 day 18 hours ago" now I have to calculate (or move over) that this was last Friday 3pm and then I know, that this article was sent after workhour and therefore not touched.
Or: 
A customer sent us a huge log file and tell us currently the error happend. Now I'd like to know when the article was written to take a look in the log file at the specific time the article was created.

Even if you print a Ticket and show it next day to your supervisor, this time notice is not useful.

I don't know a case, where it's useful for us...

**Comment by tswaehn** [comment]
I fully agree, a date of "2days 18hours" hardly tells me the point in time. Instead I always have to calculate.

Thus I suggest a format 

For less than 7days
"Monday 09:30"

For more than 7days 
"Tuesday 23. Feb 14:20"

For more than one year 
"Wednesday 23.07.2016 05:32"

**Comment by tswaehn** [comment]
I am wondering what is next on this topic. Can I help with some more information?

**Comment by martini** [comment]
It's in implementation. Some first impressions:

<img width="295" alt="screen shot 2017-04-04 at 22 09 15" src="https://cloud.githubusercontent.com/assets/110226/24676471/6576b0c0-1983-11e7-8716-bc4dafea7220.png">
<img width="182" alt="screen shot 2017-04-04 at 22 09 06" src="https://cloud.githubusercontent.com/assets/110226/24676475/657932b4-1983-11e7-9dbe-d408bb49505f.png">
<img width="271" alt="screen shot 2017-04-04 at 22 08 54" src="https://cloud.githubusercontent.com/assets/110226/24676472/65772258-1983-11e7-8b2c-30b5fbf544f8.png">
<img width="265" alt="screen shot 2017-04-04 at 22 08 25" src="https://cloud.githubusercontent.com/assets/110226/24676474/65783256-1983-11e7-957f-354c85ad0da6.png">
<img width="242" alt="screen shot 2017-04-04 at 22 08 18" src="https://cloud.githubusercontent.com/assets/110226/24676473/65775f84-1983-11e7-8a44-7a28b7e071a7.png">
<img width="582" alt="screen shot 2017-04-04 at 22 07 59" src="https://cloud.githubusercontent.com/assets/110226/24676476/659b1fbe-1983-11e7-81c3-19f317312634.png">

**Comment by tswaehn** [comment]
Ist ja klasse, wir sind begeistert!!

(Sent with my mobile device - please excuse typos)

**Comment by martini** [comment]
JFI: https://github.com/zammad/zammad/commit/131d360c75e4b77ff658a98d75fab1bd3977a993 will be available in next release.

**Comment by martini** [comment]
Will be found in admin -> branding as system wide setting.

<img width="1119" alt="screen shot 2017-04-21 at 12 09 38" src="https://cloud.githubusercontent.com/assets/110226/25273288/7e6eb1ee-268b-11e7-8f3a-923f15440e96.png">
