### ISSUE TITLE
Can't process email

### ISSUE THREAD

**Issue by alexbrueckel** [zammad/zammad#635]
Hi,
my zammad instance won't process emails any more, the problem existed even before the update to 1.2.

### Infos:
* Used Zammad version: 1.2.0
* Operating system: Debian Jessie

ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//da1de227ca7122be64074f47dff6266c.eml, please create an issue at https://github.com/zammad/zammad/issues
E, [2017-01-17T15:34:37.890222 #17708] ERROR -- : ERROR: #<NameError: uninitialized constant Store::Provider::FS>
ERROR: ["/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `const_get'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `block in constantize'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'", "/opt/zammad/lib/application_lib.rb:54:in `load_adapter'", "/opt/zammad/app/models/store/file.rb:31:in `add'", "/opt/zammad/app/models/store.rb:40:in `add'", "/opt/zammad/app/models/ticket/article.rb:205:in `save_as_raw'", "/opt/zammad/app/models/channel/email_parser.rb:550:in `block (2 levels) in _process'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/locking/pessimistic.rb:72:in `block in with_lock'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:277:in `transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/locking/pessimistic.rb:70:in `with_lock'", "/opt/zammad/app/models/channel/email_parser.rb:528:in `block in _process'", "/opt/zammad/app/models/transaction.rb:12:in `block in execute'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'", "/opt/zammad/app/models/transaction.rb:10:in `execute'", "/opt/zammad/app/models/channel/email_parser.rb:446:in `_process'", "/opt/zammad/app/models/channel/email_parser.rb:389:in `process'", "/opt/zammad/app/models/channel/driver/imap.rb:194:in `block in fetch'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `each'", "/opt/zammad/app/models/channel/driver/imap.rb:168:in `fetch'", "/opt/zammad/app/models/channel.rb:62:in `fetch'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'", "/opt/zammad/app/models/channel.rb:30:in `fetch'", "(eval):1:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:90:in `eval'", "/opt/zammad/app/models/scheduler.rb:90:in `_start_job'", "/opt/zammad/app/models/scheduler.rb:57:in `block (2 levels) in start_job'", "/opt/zammad/app/models/scheduler.rb:56:in `loop'", "/opt/zammad/app/models/scheduler.rb:56:in `block in start_job'"]

**Comment by martini** [comment]
Hi @alexbrueckel 

this is a duplicate of https://github.com/zammad/zammad/issues/428 

Please check if this config setting "storage_provider" exists:

```
    setting = Setting.find_by(name: 'storage_provider')
```

If not, you can execute the following code via "rails c" to fix it:

```
    setting = Setting.find_by(name: 'storage')
    setting.name = 'storage_provider'
    setting.options = {
      form: [
        {
          display: '',
          null: true,
          name: 'storage_provider',
          tag: 'select',
          tranlate: true,
          options: {
            'DB' => 'Database',
            'File' => 'Filesystem',
          },
        },
      ],
    }
    setting.preferences = {
      controller: 'SettingsAreaStorageProvider',
      online_service_disable: true,
      permission: ['admin.system'],
    }
    setting.save!
```

In both ways then you need to update this config setting via admin interface -> Settings -> System -> Storage

 -> Filesystem or Database

After restarting the schedule it should work fine.

Feedback is welcome.

**Comment by alexbrueckel** [comment]
The config setting worked, mails are processed again, thank you very much!
(my icinga now checks for unprocessed mails in zammad tmp dir , just to be sure ;-))

**Comment by martini** [comment]
One more note, Zammad has a monitoring URL which you can use for monitoring. It's in admin interface -> System -> Monitoring -> Health Check (here you have the infos about unprocessed emails and other checks)

**Comment by alexbrueckel** [comment]
Great, didn't catch this, thanks again!

**Comment by MrGeneration** [comment]
Hey,

the unprocessable E-Mail is logged within production.log.
Those E-Mails will be moved to `/opt/zammad/tmp/unprocessable_mail/` as a simple eml-file that you can simply open with e.g. VI or VIM :)

**Comment by hamzehmohammadnia** [comment]
Thanks @MrGeneration ,
I can see the sender and time that has been sent, but not the content. Is there anyway to fetch the content of email?

**Comment by MrGeneration** [comment]
The E-Mail should always contain the E-Mail body - maybe the import has been interrupted or the mail came like this to your server. Maybe the logfile helps out there, sorry if that doesn't really help.

**Comment by hamzehmohammadnia** [comment]
Hi @martini,

There is a problem with zammad regarding mail processing. within the directory of /opt/zammad/tmp/unprocessable_mail/ there is an email which left unprocessed and not considered as a created ticket for zammad.
The email Content-Transfer-Encoding shows base64, and seems coded cuz content cannot be shown. 

when I have tried to use "zammad run rails r 'Channel::EmailParser.process_unprocessable_mails'
", it made Zammad down for a while, until i have restarted both zammad and httpd. 
Can I ask what is the reason? is there any miss configuration there?

**Comment by martini** [comment]
Hi @hamzehmohammadnia 

> when I have tried to use "zammad run rails r 'Channel::EmailParser.process_unprocessable_mails'
", it made Zammad down for a while, until i have restarted both zammad and httpd.
Can I ask what is the reason? is there any miss configuration there?

I can't believe that. Because `zammad run rails r` is an independent process and is not connected to Zammad application server nor to your httpd process.

Do you still have the mail which is not processable?

**Comment by hamzehmohammadnia** [comment]
Unfortunately we can't believe that too. It has been removed sometime ago. However, it was including customer information.

Once I ran that "zammad run rails r..." command, whole zammad got down, with server error. It was first time experiencing this. :/

**Comment by martini** [comment]
I believe you, but I can't see the connections.

Is there any more information about the "server error" in the server logs or maybe in /opt/zammad/log/production.log? Maybe the machine was out of memory? 🤔

**Comment by hamzehmohammadnia** [comment]
I think I have gathered all the error parameters within the production.log that sounds the error related (During downtime timestamp):
IN ADVANCE: Sorry for dumping here


Log:

apacheI, [2018-06-20T1]  INFO -- : Processing by TicketArticlesController#index_by_ticket as */*
I, [2018-06-20T12:]  INFO -- :   Parameters: {"page"=>"1", "per_page"=>"100", "id"=>"1697"}
I, [2018-06-20T12:  INFO -- : Completed 200 OK in 218ms (Views: 0.5ms | ActiveRecord: 112.1ms)
I, [2018-06-20T12]  INFO -- : execute Channel.fetch (try_count 0)...
I, [2018-06-20T12]  INFO -- : fetching imap (wp11251222.mail.server-he.de/wp11251222-info port=143,ssl=false,folder=INBOX,keep_on_server=false)
E, [2018-06-20T12] ERROR -- : Mysql2::Error: Lost connection to MySQL server during query: SELECT  `tickets`.* FROM `tickets` WHERE `tickets`.`id` = 1697 LIMIT 1 (ActiveRecord::StatementInvalid)


, [2018-06-20T12]  INFO -- : Completed 500 Internal Server Error in 7312ms (Views: 70.9ms | ActiveRecord: 42.5ms)
F, [2018-06-20] FATAL -- :
F, [2018-06-20] FATAL -- : AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):
F, [2018-06-20T12] FATAL -- :
F, [2018-06-20T1 FATAL -- : app/controllers/application_controller/handles_errors.rb:46:in `block (2 levels) in respond_to_exception'
app/controllers/application_controller/handles_errors.rb:45:in `respond_to_exception'
app/controllers/application_controller/handles_errors.rb:23:in `unprocessable_entity'
I, [2018-06-20T12:5]  INFO -- : Started GET "/api/v1/search?query=m.forni%40fabrique-d-images.com&limit=10&_=1529489964969" for 90.187.78.141 at 2018-06-20 12:52:02 +



I, [2018-06-20T12:52:02.  INFO -- : Started GET "/api/v1/search?query=m.forni%40fabrique-d-images.com&limit=10&_=1529489964969" for 90.187.78.141 at 2018-06-20 12:52:02 +0200
F, [2018-06-20T] FATAL -- :
F, [2018-06-20T FATAL -- : Mysql2::Error (Can't connect to MySQL server on '127.0.0.1' (111)):
F, [2018-06-20T FATAL -- :
F, [2018-06-20T1 FATAL -- : vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'


, [2018-06-20T12:5] ERROR -- : execute Channel.stream (try_count 0) exited with error #<ActiveRecord::StatementInvalid: Mysql2::Error: Lost connection to MySQL server during query: SELECT `channels`.* FROM `channels` WHERE (active = 1 AND area LIKE '%::Account')>
E, [2018-06-20T12:] ERROR -- : Can't reconnect to database #<Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (111)>
E, [2018-06-20T12 ERROR -- : execute Channel.stream (try_count 0) exited with error #<ActiveRecord::StatementInvalid: Mysql2::Error: MySQL client is not connected: BEGIN>
E, [2018-06-20T1] ERROR -- : Can't reconnect to database #<Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (111)>
E, [2018-06-20T] ERROR -- : execute Channel.stream (try_count 1) exited with error #<ActiveRecord::StatementInvalid: Mysql2::Error: MySQL client is not connected: BEGIN>
E, [2018-0] ERROR -- : Can't reconnect to database #<Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (111)>
E, [2018-06-20T12:52 ERROR -- : execute Channel.stream (try_count 2) exited with error #<ActiveRecord::StatementInvalid: Mysql2::Error: MySQL client is not connected: BEGIN>

 [2018-06-20T12: ERROR -- : /opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
  /opt  /opt/zammad/vendor/bundle/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2018-06-20] ERROR -- : execute Channel.stream (try_count 0) exited with error #<ActiveRecord::StatementInvalid: Mysql2::Error: Lost connection to MySQL server




I, [2018-06-20T12:52:]  INFO -- : Completed 500 Internal Server Error in 7312ms (Views: 70.9ms | ActiveRecord: 42.5ms)
F, [2018-06-20T12:52] FATAL -- :
F, [2018-06-20T12:52:0] FATAL -- : AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):
F, [2018-06-20T12:52:] FATAL -- :
F, [2018-06-20T12:52:01] FATAL -- : app/controllers/application_controller/handles_errors.rb:46:in `block (2 levels) in respond_to_exception'
app/controllers/application_controller/handles_errors.rb:45:in `respond_to_exception'
app/controllers/application_controller/handles_errors.rb:23:in `unprocessable_entity'
