### ISSUE TITLE
Channel -> Email -> New Email Account - Command received in Invalid state.

### ISSUE THREAD

**Issue by yanod-aut** [zammad/zammad#642]
### Infos:

* Used Zammad version:  1.2.0-1484665143.8dde0f2.xenial
* Operating system: Ubuntu 16.04
* Browser + version: Google Chrome 55.0.2883.87 m

### Expected behavior:
Add new Email Account 

### Actual behavior:
![zammad_error_email_channel_add](https://cloud.githubusercontent.com/assets/11647350/22061317/b4a02294-dd74-11e6-9ff5-20cf39af2ce8.jpg)

### Additional Infos:
* Mailserver: Exchange 2013
* Connections with alternative Email Clients do work without Problems on the same configuration.
* cat from production.log (replaced sensitive information)
```
I, [2017-01-18T11:47:45.380396 #2310]  INFO -- : Processing by ChannelsController#email_inbound as JSON
I, [2017-01-18T11:47:45.380495 #2310]  INFO -- :   Parameters: {"adapter"=>"imap", "options"=>{"host"=>"ourexchange.ourdomain.tld", "user"=>"support@ourdomain.tld", "password"=>"[FILTERED]", "ssl"=>false, "port"=>"143", "folder"=>""}, "channel"=>{"options"=>{"host"=>"ourexchange.ourdomain.tld", "user"=>"support@ourdomain.tld", "password"=>"[FILTERED]", "ssl"=>false, "port"=>"143", "folder"=>""}}}
I, [2017-01-18T11:47:45.391743 #2310]  INFO -- : fetching imap (ourexchange.ourdomain.tld/support@ourdomain.tld port=143,ssl=false)
I, [2017-01-18T11:47:45.603868 #2310]  INFO -- : Completed 200 OK in 223ms (Views: 0.7ms | ActiveRecord: 3.1ms)
```

**Comment by martini** [comment]
@yanod-aut Is it correctly, you try to connect to exchange via imap (plain, without ssl)?

**Comment by yanod-aut** [comment]
@martini Yes, and the required Connector on the Exchange Server is enabled and working.

**Comment by yanod-aut** [comment]
@martini I also get the same Error Message when i try to connect via POP3 on Port 110.

**Comment by martini** [comment]
@yanod-aut unfortunately I do not have an exchange account without ssl for testing. Would remote login for debugging be possible?

**Comment by yanod-aut** [comment]
@martini Sorry that is not possible due to company restrictions, anyway we reconfigured the Exchange for test purposes to enable SSL and it works, so i think you can close the issue?

**Comment by martini** [comment]
@yanod-aut Thanks for feedback! Yes, close it. 👍
