### ISSUE TITLE
Dashboard widget "Waiting time today" is not counting

### ISSUE THREAD

**Issue by martini** [zammad/zammad#645]
After installation the dashboard widget "Waiting time today" is not counting. Shows always "0".
<img width="243" alt="screen shot 2017-01-18 at 16 38 02" src="https://cloud.githubusercontent.com/assets/110226/22070562/c3cd6ef2-dd9c-11e6-8195-3e5fb20a98f5.png">

**Comment by martini** [comment]
<img width="279" alt="screen shot 2017-04-19 at 01 17 03" src="https://cloud.githubusercontent.com/assets/110226/25156919/11d004b4-249e-11e7-8d48-22c27b856555.png">

**Comment by martini** [comment]
Also if no StatsStore exists, the widget looks like:

<img width="242" alt="screen shot 2017-04-19 at 01 32 07" src="https://cloud.githubusercontent.com/assets/110226/25157218/1833256e-24a0-11e7-8d24-cfbc1011f057.png">

It should look linke this (green) per default:

<img width="237" alt="screen shot 2017-04-19 at 01 27 42" src="https://cloud.githubusercontent.com/assets/110226/25157225/268eb4de-24a0-11e7-8943-bf1c7f249e26.png">

**Comment by CodeBrauer** [comment]
I'm using Zammad 3.4.x and I have also the issue the widget shows "0"?
