### ISSUE TITLE
Chat: More than one Chat Issues

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#649]
Hi there,

we are trying to use the chat for 2 different departments. Now we have the Problem that when an agent is online wich only enabled chat ID 2 in its backend configuration, the chat ID 1 also appears on the webpage and the agent wich should only get requests for chatID 2 gets this chats too.

### Infos:

* Used Zammad version: 1.2
* Operating system: CentOS 7

**Comment by hanneshal** [comment]
I close this issue, because it is related to a pending feature request. The current implementation can't separate between different chad ids in relation to a user.
