### ISSUE TITLE
Mail notification

### ISSUE THREAD

**Issue by hpaar** [zammad/zammad#652]
Hi,

I am not quite if I have overseen it, but is there a possibility to get a notification per mail as an admin or agent if there is a new ticket or new information added? Thank you for your help.

**Comment by snow2k9** [comment]
Hey,
go to your Zammad Profile -> Notifications
and check the notifications you want

**Comment by hpaar** [comment]
Hi,
thank you for your answer. I have checked all options but still no notification. I think it has something to do with "Mail Notification" SMTP Setting (https://github.com/zammad/zammad/issues/654).

**Comment by thorsteneckel** [comment]
If your mail setup is not working there is no way emails (like notifications) can get send. Closing for now. Let us know if issue is still present after fixing your SMTP issue.
