### ISSUE TITLE
change user login if not identical with user email

### ISSUE THREAD

**Issue by snow2k9** [zammad/zammad#653]
### Infos:

* Used Zammad version: latest zammad-docker-compose and latest Ubuntu Repo
* Operating system: Arch/Ubuntu
* Browser + version: FF 50.1.0 on Linux

### Expected behavior:

* Don't change user.email and user.login to a existing one
* Change user.login if not identical with user.email

### Actual behavior:

* Editing user.email to an existing email address will change user.login to user.emailXXX
* On 'undoing' this change user.login won't change

### Steps to reproduce the behavior:

* As admin go to manage -> user
* Create two users with different email addresses
** user1@example.com & user2@example.com
* Change user2s email to user1s
** from user2@example.com to user1@example.com
** user2s email is now user1@example.com, and login is user1@example.com123 (some numbers)
* Change user2 email to something different
** user2s login will remain user1@example.com123

This is the HTTP PUT:
`{"login":"user1@example.com521","firstname":"Nicole","lastname":"Braun","email":"blah@blah.com","web":"","password":"","phone":"","fax":"","mobile":"","street":"","zip":"","city":"","country":"","organization_id":"1","department":"","note":"","role_ids":"3","group_ids":[],"active":true,"updated_at":"2017-01-19T21
:12:30.514Z","address":"","vip":false,"id":2}`

**Comment by snow2k9** [comment]
https://github.com/zammad/zammad/blob/develop/app/models/user.rb#L848
I think it is better to raise an exception like `raise Exceptions::UnprocessableEntity, '\'login\'  exists already!'` instead of adding random numbers, or to check if email already exists in check_email an raise an Exception there

**Comment by thorsteneckel** [comment]
This didn't get much traction. If you still think there is a need to change that please refer to the [community board](http://community.zammad.org/) and let us know your thoughts. Closing this one now.
