### ISSUE TITLE
Email Notification SMTP

### ISSUE THREAD

**Issue by hpaar** [zammad/zammad#654]
Hi,

I would like to configure my mail provider (mailbox.org) to send email notification. When I configure zammad " configure own smtp server", I get bad "501 5.1.7 Bad sender address syntax". 

With my freemail provider gmx I get "501 Syntax error in parameters or arguments"

Thank you for help.

**Comment by thorsteneckel** [comment]
Hi @hpaar - can you please provide the file `log/production.log`of your Zammad instance after reproducing this? This would help. Thanks!

**Comment by hpaar** [comment]
Hi @thorsteneckel,

attach you find the log file. Now I get "Authentication failed" message. The same password is used for mailing tickets. I checked the password several times and even changed it. Thank you for your help.

[2017-01-23_zammad_production..zip](https://github.com/zammad/zammad/files/723402/2017-01-23_zammad_production.zip)

**Comment by hpaar** [comment]
Hi,
 I think I found the solution. I had configure in Fully Qualified Domain Name "domain_name:port". The Port is not 80 or 443. I removed the port number and everything works now. Thank you

**Comment by marekmaurizio** [comment]
What if i need the port?
