### ISSUE TITLE
Disabling of email accounts not working

### ISSUE THREAD

**Issue by jschurse** [zammad/zammad#657]
Hey,

I seem not to be able to disable an email account.

### Infos:

* Used Zammad version: 1.2.0
* Operating system: Debian 8
* Browser + version: Firefox current

### Expected behavior:

* Email Account gets disabled

### Actual behavior:

* I receive a 404 Error with the message:
"No route matches [PUT] /api/v1/channels/3"

### Steps to reproduce the behavior:

* Under Channels > E-Mail click disable at an email Account

**Comment by thorsteneckel** [comment]
Fixed with https://github.com/zammad/zammad/commit/d34112a99fe870c265eb8bcd17d9fe3d58774994  - please update to latest version.
