### ISSUE TITLE
Can't create organisation when user is not an agent

### ISSUE THREAD

**Issue by derfladi** [zammad/zammad#658]
### Infos:

* Used Zammad version: 1.2.0
* Operating system: Ubuntu 16.04
* Browser + version: Chrome/Safari

I created an "admin-user" who does not have the agent-role.

### Expected behavior:

*  Add an organisation with "Admin"-User.

### Actual behavior:

* After hitting submit the main windows gets blank. When clicking on the Settings-Wheel again the modal-window is shown againg with an error => "Error thrown (Not authorized (user)!)."

The ajax call throws
```
Object {readyState: 4, responseText: "{"error":"Not authorized (user)!"}", responseJSON: Object, status: 401, statusText: "error"}abort: (t)always: ()complete: ()done: ()error: ()fail: ()getAllResponseHeaders: ()getResponseHeader: (t)overrideMimeType: (t)pipe: ()progress: ()promise: (t)readyState: 4responseJSON: ObjectresponseText: "{"error":"Not authorized (user)!"}"setRequestHeader: (t,e)state: ()status: 401statusCode: (t)statusText: "error"success: ()then: ()__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__() 401
```

error.log has an entry:
```
2017/01/22 13:56:53 [error] 294#294: *251 connect() failed (111: Connection refused) while connecting to upstream, client: 10.xxx.xxx.xxx, server: support.xxx.xx, request: "PUT /api/v1/users/3 HTTP/2.0", upstream: "http://[::1]:3000/api/v1/users/3", host: "support.xxxx.xx", referrer: "https://support.xxx.xx/"
```

### Steps to reproduce the behavior:

* Create an user with "admin" as only right (no agent or customer). Try to create an organization.

If the "admin" user is an "agent" everything works as expected. So this issue is not a big deal.

**Comment by Nivatius** [comment]
the work around "give admin also agent rights" worked for me too.

**Comment by martini** [comment]
Hi @derfladi 

just found out that #902 is the same. #902 is already fixed (in stable and upcoming next release).

Thanks for your help!

 -Martin
