### ISSUE TITLE
Can't update translations via translation table in admin interface

### ISSUE THREAD

**Issue by petervanbeugen** [zammad/zammad#659]
I tried to update a few Translations by the translation table: But these changes are not comitted!
The blue button to push the translations only shows after doing some inline translations first. After that the blue button is there, but does not work for the translation table. Translated items are blank after a logout.
browser Chrome & Firefox
CentOS / latest RPM

**Comment by martini** [comment]
Hi @petervanbeugen 

I just verified this. It's reproducible on latest 1.2.

 -Martin

**Comment by petervanbeugen** [comment]
Please fix it :-) 
and we can start translating....

**Comment by martini** [comment]
> Please fix it :-)

Oh yeah! Done! 🤓🍾 I come over to have some 🍺!

Thanks for your help Peter!

**Comment by martini** [comment]
PS: On every bugfix a new RPM package is build. So you can update your RPM installation within next 30 minutes. Feedback would be great!

**Comment by petervanbeugen** [comment]
Nice! I will try tomorrow morning!

**Comment by martini** [comment]
Thanks a lot!  ❤️

**Comment by petervanbeugen** [comment]
Updated my system with latest RPM. And looks like it is working now! Pushed a few translations, so maybe a final check if some Dutch translations are committed this morning.

**Comment by martini** [comment]
Great to hear! I can confirm, a few translations for dutch arrived. 👍
