### ISSUE TITLE
Add new AWS S3 as storage backend 

### ISSUE THREAD

**Issue by mrcasablr** [zammad/zammad#660]
Currently, database and filesystem is allowed for attachment storage. This is a request to add AWS S3 as a new backend

**Comment by thorsteneckel** [comment]
Hi @mrcasablr - great idea! The attachment storage is already designed to support different types of storage providers: https://github.com/zammad/zammad/tree/develop/app/models/store/provider

**Comment by siepkes** [comment]
I would like to propose using a different library then the (default) AWS S3 Ruby client in order to make the S3 endpoint configurable. That way its possible to use AWS S3 alternatives like Ceph, LeoFS, Azure, etc. which offer S3 compatible endpoints.

**Comment by gjongenelen** [comment]
We are facing an issue where large attachments (5MB+) would cause a DB error. Having a storage-option such as S3 would be great. Unfortunately I have little/no knowledge of Ruby.

Is there anybody working on this or planning to start doing this?

**Comment by siepkes** [comment]
@gjongenelen It is currently also possible to use the file storage backend. That would solve your DB issue for now (which btw might be just a DB configuration issue). You can use that in combination with NFS (and for example Ceph) to get pretty flexible storage. Having said that we might pick up this issue somewhere in the future.

**Comment by rosscdh** [comment]
+1 for this issue; as its not always practical to have the filestore in the db (binary in db) and in cloud/kube pvc is not always available. Whereas s3 or s3lookalikes like minio would easily be supported with https://github.com/qoobaa/s3 or similar?

might even be able to take a stab at a PR (been a while since i wrote some ruby but why not)

**Comment by monotek** [comment]
This would also help to achieve: https://github.com/zammad/zammad/issues/1601

+1 for a generic storage lib too.

**Comment by rosscdh** [comment]
Started https://github.com/zammad/zammad/pull/3199

**Comment by rosscdh** [comment]
is there a slack channel or something i can get some support for rails been a few years and just need a few tips on coffeescript .. need to add attributes to the form and assocaite with a model.. rails has changed quite a bit since i last used it

**Comment by monotek** [comment]
Try the community forums: https://community.zammad.org/

**Comment by monotek** [comment]
Link to thread for reference: https://community.zammad.org/t/storage-s3-provider-pr/5307

**Comment by MatBrie** [comment]
Hi,
Not sure if this helps but this should work as a provider as long as the AWS bucket envs are set and the sdk gem is installed:
```
require 'aws-sdk-s3'

class Store
  module Provider
    class AWS
      def self.add(data, sha)
        bucket.object(sha).put(body: data)
        true
      rescue Aws::S3::Errors::ServiceError => e
        Rails.logger.info e
      end

      def self.get(sha)
        bucket.object(sha).get.body.read
      rescue Aws::S3::Errors::ServiceError => e
        Rails.logger.info e
      end

      def self.delete(sha)
        bucket.object(sha).delete
        true
      rescue Aws::S3::Errors::ServiceError => e
        Rails.logger.info e
      end

      def self.bucket
        s3 = Aws::S3::Resource.new
        s3.bucket(ENV['S3_BUCKET'])
      end
    end
  end
end
```
Hope it helps someone.
