### ISSUE TITLE
Add setting to define internal/external notice default setting

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#662]
Add setting to define internal/external notice default setting

**Comment by kmclea16** [comment]
Is it possible to define the default setting in Admin? We would like to be able to set default note to be Public, and allow agent to set visibility to internal.

**Comment by Saliva520319** [comment]
Also meet this question. Is there any Flags can be changed?

**Comment by thorsteneckel** [comment]
Hi @MrGeneration - this one is already resolved by the commit of @rolfschmidt from early 2017 😱 However, can you please add the introduced setting to the list of advanced configurations in the documentation and close this issue?

**Comment by MrGeneration** [comment]
This is already documented here:

https://admin-docs.zammad.org/en/latest/channels-email.html#additional-e-mail-setting

Closing :)
