### ISSUE TITLE
Modify Mail Template "Lost Password"

### ISSUE THREAD

**Issue by hpaar** [zammad/zammad#663]
Hi,

this might be a trivial question but where can I can modify the mail template for "Lost Password"? Thank you.

**Comment by thorsteneckel** [comment]
Hi @hpaar - currently this is only possible via changing the files in https://github.com/zammad/zammad/tree/develop/app/views/mailer/password_reset - please make sure your changes won't get overwritten when updating.

**Comment by hpaar** [comment]
Hi @thorsteneckel ,

I was wondering how I could change the link which is sent when you request a password reset can be modified in that way that I could add a port as my web server is listening not on the standard ports 80 or 443. Thank you for your help.
