### ISSUE TITLE
Docker compose up fails

### ISSUE THREAD

**Issue by mrcasablr** [zammad/zammad#665]
[mrcasablr@localhost zammad-docker-compose]$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.zammad.labels.io.rancher.container.start_once contains true, which is an invalid type, it should be a string, number, or a null
[mrcasablr@localhost zammad-docker-compose]$

[mrcasablr@localhost zammad-docker-compose]$ docker -v
Docker version 1.13.0, build 49bf474
[mrcasablr@localhost zammad-docker-compose]$ docker-compose -v
docker-compose version 1.8.0, build f3628c7
[mrcasablr@localhost zammad-docker-compose]$

**Comment by mrcasablr** [comment]
io.rancher.container.start_once: 'true' fixes it

**Comment by thorsteneckel** [comment]
Hi @mrcasablr - could you please create the issue in the zammad-docker-compose repository here: https://github.com/zammad/zammad-docker-compose/issues . Thanks!
