### ISSUE TITLE
Auto Focus on "Time Accounting" Popupbox

### ISSUE THREAD

**Issue by AdiosOnline** [zammad/zammad#670]
Hi,
it would be much more comfortable for Agents, when the Popupbox "Time Accounting" would automaticaly get the Focus for typing. We Use the Shortcuts very much and everytime it pops up, we need to grab the Mouse an click the Cursor into the Inputfield from the box... 

If we could just use "Ctrl + Alt + return"  --> "type in the Unit" --> " return" it would be more efficient.

Thanks Jorrit

**Comment by martini** [comment]
@jepf during bug fixing of #705 I also implemented this issue.

**Comment by martini** [comment]
Fixed in stable branch.
