### ISSUE TITLE
After update from 1.1.2 to 1.2.0 Elasticsearch stoped working

### ISSUE THREAD

**Issue by Johannes-GitHub** [zammad/zammad#673]
### Infos:

* Used Zammad version: Update from 1.1.2 to 1.2.0
* Operating system: Ubuntu 16.04.1 LTS
* Browser + version: Firefox / Chrome (newest)

### Actual behavior:

After update from 1.1.2 to 1.2.0 Elasticsearch stoped working. 

When i running: "zammad run rake searchindex:rebuild"
I get error Message: rake aborted!

Code: 
root@ZA01:~# zammad run rake searchindex:rebuild
drop indexes...
create indexes...
rake aborted!
Unable to process PUT at http://localhost:9200/zammad_production
#<UserAgent::Result:0x005626e310b598 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for \"localhost\" port 9200)>">
/opt/zammad/lib/search_index_backend.rb:62:in `index'
/opt/zammad/lib/tasks/search_index_es.rake:19:in `block (2 levels) in <top (required)>'
/opt/zammad/lib/tasks/search_index_es.rake:60:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => searchindex:rebuild
(See full trace by running task with --trace)

Trying with: 
zammad run rails r "Setting.set('es_url', 'http://127.0.0.1:9200')"
zammad run rails r "Setting.set('es_url', 'http://localhost:9200')"

### Steps to reproduce the behavior:
Install: 
https://docs.zammad.org/en/latest/install-ubuntu.html

Update from 1.1.2 to 1.2.0
https://docs.zammad.org/en/latest/install-update.html#update-with-deb

**Comment by martini** [comment]
Hi @Johannes-GitHub 

did you also upgrade elasticsearch? Is it the elasticsearch process still running?

JFI: If you also upgraded elasticsearch, you need to remove the old mapper-attachments and install it again (because it's not compatible). -> It's a elasticsearch issue.

 -Martin

**Comment by Johannes-GitHub** [comment]
Hi @martini 
thanks for your fast answer. 

Can you please give me a hint, how i can upgrade and check elasticsearch? 

Tried to find it on docs, but i can only find the installer: 
Is the Generic install Elasticsearch 5.0: for Ubuntu 16.04: the right one? 
https://docs.zammad.org/en/latest/install-elasticsearch.html

**Comment by martini** [comment]
@Johannes-GitHub since it's no Zammad issue, I only can give you some hints. And I can't get you help how to manage your OS. Anyway, elasticsearch is a service like any other service on your OS. First I would check if elasticsearch is running:

`sudo service elasticsearch status`

It elasticsearch is not running, uninstall the mapper-attachments plugin and install it again.

`sudo /usr/share/elasticsearch/bin/elasticsearch-plugin uninstall mapper-attachments`

and

`sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-attachments`

Then elasticsearch should start again.

`sudo service elasticsearch start`

**Comment by Johannes-GitHub** [comment]
@martini 
Hi thanks, it works, great 👍 .

For me on Ubuntu: 

sudo /usr/share/elasticsearch/bin/elasticsearch-plugin remove mapper-attachments
and 
sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-attachments

Starting Service:
sudo service elasticsearch start

**Comment by monotek** [comment]
Had same problem with ES 1.5.2.
Reinstalling mapper attachments when es is stopped helped me too:

* systemctl stop elasticsearch
* /usr/share/elasticsearch/bin/elasticsearch-plugin remove mapper-attachments
* /usr/share/elasticsearch/bin/elasticsearch-plugin install mapper-attachments
* systemctl stop elasticsearch
* zammad run rake searchindex:rebuild

**Comment by Johannes-GitHub** [comment]
Hi,
after update to Zammad 1.5 elasticsearch fails... 
(reinstall hint not working...)

`● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-05-02 17:48:26 CEST; 1min 51s ago
     Docs: http://www.elastic.co
  Process: 2283 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet -Edefault.path.logs=${LOG_DIR} -Edefault.path.data=${DATA_DIR} -Edefault.path.conf=${CONF_DIR} (code=exited, status=1/FAILURE)
  Process: 2278 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
 Main PID: 2283 (code=exited, status=1/FAILURE)

May 02 17:48:05 ZA01 systemd[1]: Starting Elasticsearch...
May 02 17:48:05 ZA01 systemd[1]: Started Elasticsearch.
May 02 17:48:26 ZA01 systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
May 02 17:48:26 ZA01 systemd[1]: elasticsearch.service: Unit entered failed state.
May 02 17:48:26 ZA01 systemd[1]: elasticsearch.service: Failed with result 'exit-code'.

`
