### ISSUE TITLE
Exchange Integration / Sync users via exchange contacts

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#674]
Zammad Admins need the possibility to sync users into zammad via the global address list of their exchange.

(Ticket#101554)

**Comment by rkaldung** [comment]
Global Address List (GAL) <> Outlook Contacts <> Exchange Address Book

**Comment by thorsteneckel** [comment]
The exchange integration was introduced by the commit above. Unfortunately there is currently no way (we're aware of) to access the GAL of the various Exchange products from Remote (via HTTP). Therefore we implemented the integration of the Exchange Address Book. This is usually sufficient. If you disagree or found a solution to access the GAL of the various Exchange products from Remote (via HTTP) please let us know. Until then I see this issue as implemented and therefore resolved. Closing now.
