### ISSUE TITLE
Import users and organisations via csv files

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#675]
Zammad Admins need the possibility to import users into zammad via csv files.

**Comment by Delikt** [comment]
That piece of Software is awesome... but rly we need a User import via csv

+1

**Comment by mrcasablr** [comment]
You can use Admin rest api's to create users via a script that can read from a CSV file

**Comment by einzelfabrik** [comment]
Hello, is there an example how to do this with the csv import via Rest API? I've already found it: (https://github.com/project-open-data/csv-to-api) how a csv becomes a json string.
But what happens next?

**Comment by einzelfabrik** [comment]
an approach is to send a. json file via curl (windows).

curl -H "Authorization: Bearer token" -H "Content-Type: application/json; charset=utf-8" -X POST -d "@customer. json" https://ticket.example.com/api/v1/organizations

I built the. json file as follows: (because of special characters äöüß & I choose the way over the import, because special characters are not supported in the cmd)

{ "name":"ORGA NAME","shared": true,"active": true,"note":"}

This also works - unfortunately I can only read one entry at a time.

**Comment by thorsteneckel** [comment]
This one was already introduced with Zammad 2.4 - so it's ready to use. 🚀

**Comment by Delikt** [comment]
Ty for the Information.. i will take a look on this version

**Comment by mister-wolf** [comment]
Hi @thorsteneckel, are you sure this has been released on 2.4? I can't see any menu item to make such an import. Or should we launch it some other way?

Thanks

**Comment by mister-wolf** [comment]
Thank you @thorsteneckel. Any chance you can give us some hints on syntax - e.g. how to use this command from rails console?
Thank you so much.

**Comment by thorsteneckel** [comment]
Hi @mister-wolf - please have a look at my last comment. The first block is the syntax you are looking for. Just change the `file` path to your need and paste the command to the console.

**Comment by Delikt** [comment]
Looking much clearer as the old solution.. i will test it soon

**Comment by mister-wolf** [comment]
I tried to make an import. I prepared a file with the following columns:
login;first name;last name;organization;E-mail

Import fails with the following error

`ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'text_modules.login' in 'where clause': SELECT `text_modules`.* FROM `text_modules` WHERE `text_modules`.`login` = 'testuser@domain.com'
	from app/models/application_model/can_lookup.rb:57:in `lookup'
	from app/models/concerns/can_csv_import.rb:121:in `block (2 levels) in csv_import'
	from app/models/concerns/can_csv_import.rb:117:in `each'
	from app/models/concerns/can_csv_import.rb:117:in `block in csv_import'
	from app/models/concerns/can_csv_import.rb:114:in `each'
	from app/models/concerns/can_csv_import.rb:114:in `csv_import'
	from (irb):8
`

Is this a problem regarding csv columns? I wasn't able to find out any info on which fields should be present on csv. 

Thank you once again

**Comment by thorsteneckel** [comment]
Hi @mister-wolf - as described in my earlier comment you need to change the Model (`TextModule`) to the Model you want to import (`User`). So instead of:

```
   result = TextModule.csv_import( 
     file: '/Users/me/Downloads/example.csv', 
     parse_params: { 
       col_sep: ';', 
     }, 
     try: false, 
   ) 
```

use:
```
   result = User.csv_import( 
     file: '/Users/me/Downloads/example.csv', 
     parse_params: { 
       col_sep: ';', 
     }, 
     try: false, 
   ) 
```

**Comment by mister-wolf** [comment]
hi @thorsteneckel, got it. So sorry for the dumb question. After some digging, it looks like I was able to import Organizations and Users succesfully. Thank you once again.

**Comment by thorsteneckel** [comment]
You're welcome! Would be great to receive a [Pull Request](https://help.github.com/articles/creating-a-pull-request/) over at https://github.com/zammad/zammad-documentation :)
