### ISSUE TITLE
admin interface -> time accounting setting will not be saved

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#677]
If you click into the time accounting settings in the admin interface:

![grafik](https://cloud.githubusercontent.com/assets/5445062/22365051/c8c9b304-e475-11e6-8d2f-f278868f7efa.png)

and you save some conditions then they will not be saved.

**Comment by PhoenixZeroDown** [comment]
Same problem here. Maybe the problem is that there is no "real" save button for the settings, 
Time accouting works so far, when you create an article, regardless of the ticket status.

**Comment by ECM80** [comment]
I got the same problem

**Comment by rolfschmidt** [comment]
Hi,
this bug is fixed now in stable, master and develop.

Best regards,
Rolf
