### ISSUE TITLE
Reply-To is ignored

### ISSUE THREAD

**Issue by michilehr** [zammad/zammad#678]
When the 'reply-to' header is set, I think Zammad should use this email address for responses, but it is currently ignored and the 'from' email address is used for the reply.

**Comment by tniebergall** [comment]
That would be great.

**Comment by thorsteneckel** [comment]
I've thought that there was an issue/pull request for this 🤔 But I couldn't find it... We'll take a look.

**Comment by eliasp** [comment]
@thorsteneckel you were probably looking for https://github.com/zammad/zammad/issues/203

**Comment by thorsteneckel** [comment]
Bam! That's it. Thanks @eliasp. Closing this in favor of #203.

PS: nice to hear from you :)
