### ISSUE TITLE
Missing assigned tags in /api/v1/tickets/

### ISSUE THREAD

**Issue by c2c-alchemist** [zammad/zammad#679]
### Infos:

* Used Zammad version: 1.2.0-1484665143.8dde0f2.centos7
* Operating system: Centos 7.3

### Expected behavior:
Using /api/v1/tickets/ or /api/v1/tickets/{id} i expected to see the assigned tags too.

### Actual behavior:
Tags are missing in the returned data.

Are the tags missing by design or is this something that could be added?

**Comment by martini** [comment]
Hi @c2c-alchemist 

currently they are missing by design. Currently you need to call a second resource:

GET /api/v1/tags?object=Ticket&o_id={id}

 -Martin

**Comment by martini** [comment]
PS: @c2c-alchemist really cool web page!  👌

**Comment by c2c-alchemist** [comment]
Hi Martin,
good to know and absolutely fine for our needs. Thanks for your help!

Dany
