### ISSUE TITLE
Zammad https

### ISSUE THREAD

**Issue by hpaar** [zammad/zammad#680]
Hi,

this question might be trivial but I am looking for a how to implement https (ssl) for zammad. I did the neccessary steps as certificates and neins configuration but it does not work. Help here is really appreciated. Thanks.

**Comment by monotek** [comment]
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

**Comment by monotek** [comment]
Added an example ssl configuration file for nginx: https://github.com/zammad/zammad/blob/ddb738a22a0033e14d31ff8fdfba6d8894fc69b1/contrib/nginx/zammad_ssl.conf

**Comment by hpaar** [comment]
Thank you. It helped me to find the error in my nginx configuration

**Comment by Stefan39** [comment]
Sorry, i have the same problem after change the host to ssl. The error are ERR_CONNECTION_TIMED_OUT.
I didn't found any error in the nginx error.log also not into the zammad-error.log.

Into the zammad.conf are nearly all the same like the example. What can i do?

**Comment by monotek** [comment]
What's the output of netstat -tlpen

**Comment by Stefan39** [comment]
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      112        16355       -               
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          2111098     -               
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          814144      -               
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      114        2109352     -               
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      0          16990       -               
tcp        0      0 0.0.0.0:6042            0.0.0.0:*               LISTEN      114        2109336     -               
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      0          2111100     -               
tcp6       0      0 :::80                   :::*                    LISTEN      0          2111099     -               
tcp6       0      0 :::22                   :::*                    LISTEN      0          814153      -               
tcp6       0      0 :::25                   :::*                    LISTEN      0          16991       -               
tcp6       0      0 :::443                  :::*                    LISTEN      0          2111101     -

**Comment by monotek** [comment]
Which OS?
Is port 443 blocked by a firewall?

**Comment by Stefan39** [comment]
Ahhh.. you are right! Have forgot to allow https on uwf on ubuntu. Thanks

**Comment by martini** [comment]
@Stefan39 one Sagria for @monotek please! 🍷🤓

**Comment by Stefan39** [comment]
:thumbsup:

**Comment by 023Stije** [comment]
Is there a Apache SSL documentation?

**Comment by monotek** [comment]
Nope. Not at the moment. But should be pretty straight forward using any random letsencypt how-to and add the SSL parts to: https://github.com/zammad/zammad/blob/develop/contrib/apache2/zammad.conf

Greets from Dresden buddy 😎

**Comment by 023Stije** [comment]
Yes thanks 👍 

It works good. If anybody wants to know what i did let me know (:

**Comment by monotek** [comment]
If you have working SSL config... Pull request welcome ;-)

Merry Xmas and greets to BRZ & Nicole in case you see them 😎

**Comment by 023Stije** [comment]
I see them often :D .....will do :)
same to you and to the rest there in Germany :D ....
pull request is comming.....

**Comment by monotek** [comment]
Cool :-)
So I guess you're installing Zammad for phairphone?

**Comment by 023Stije** [comment]
yeah I started as System and Network Admin....so i installed it for the IT team...for request etc. Everything went smooth....and now SSL also works 👯

**Comment by 023Stije** [comment]
So i made a simple text file because i cannot see how to make a pull request in the documentation. 

Short explanation of getting SSL for Apache with Let's Encrypt. On ubuntu 16.04 with Apache/2.4.18

zammad-ssl-apache2.txt](https://github.com/zammad/zammad/files/1582295/zammad-ssl-apache2.txt)

**Comment by monotek** [comment]
Thanks! :-)

Pull requests are a GitHub feature. Documentation is here: https://help.github.com/articles/creating-a-pull-request/

I'l review later and create the file for you.

**Comment by monotek** [comment]
https://github.com/zammad/zammad/blob/develop/contrib/apache2/zammad_ssl.conf
