### ISSUE TITLE
eMail - Exchange 2016 and Zammad: OpenSSL::SSL::SSLError: SSL_connect SYSCALL

### ISSUE THREAD

**Issue by Johannes-GitHub** [zammad/zammad#682]
### Infos:

* Used Zammad version: 1.2.0
* Operating system: Ubunut 16.04.
* Browser + version: latest Firefox
* Mail-Server: Exchange 2016

### Expected behavior:

Try to Pop3 with my Exchange 2016

Getting Error at channel - eMail: 
SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
and
Can't use Channel::Driver::Pop3: #<Errno::ECONNRESET: Connection reset by peer - SSL_connect> 

Think it´s not only a zammad issue
I hope someone can give me hint. 
To get my zammad online again. 

At the moment our live system is running with :/. 

Tried with IMAP / Pop3 unsecure / secure...

**Comment by Julian0o** [comment]
I Also have troubles getting Zammad running with our Exchange 2016 Environment. Tried POP3 and IMAP with all available Ports and it's doing nothing. 

IMAP - NO SSL - Port 143 = Command received in Invalid state.
IMAP - SSL - Port 993 = Connection reset by peer - SSL_connect
POP3 - NO SSL - Port 110 = -ERR Command is not valid in this state.
POP3 - SSL - Port 993 = Connection reset by peer - SSL_connect

By the way. When you change From IMAP to POP or the other way, the preconfigured Ports wont change from POP to IMAP Ports.

**Comment by Johannes-GitHub** [comment]
Lovely Exchange 2016, found a solution for me :). 

Exchange Shell: 
(XXXXXX is your ExchangeServer)

Check IMAPProxy if its inactive: 
`Get-ServerComponentState -Identity XXXXXX` 

Set IMAPProxy active: 
`Set-ServerComponentState -Identity XXXXXX -Component IMAPProxy -Requester HealthAPI -State Active`

All at your own risk ;).

**Comment by martini** [comment]
@Johannes-GitHub thanks for feedback!

@Julian0o You still have an issue? Would remote login possible (on my exchange env. it's working all fine)?

**Comment by Julian0o** [comment]
@martini Sorry for the late answer. We are in a big exchange migration with 20.000 Users :) And the Zammad Problem was related to some missconfiguration of our loadmaster. 

Now everything is working fine! Thanks!
