### ISSUE TITLE
Change Elasticsearch mapping to be able to provide better reporting via Kibana / Grafana

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#688]
Version: Zammad 1.3

At the moment only article.updated_by.firstname.keyword & article.updated_by.lastname.keyword are availabe in Elasticsearch. 

So i can get "André" or "Bauer" but not "André Bauer" in Kibana Dashboards.

Please add article.updated_by.fullname.keyword to elasticsearch.

**Comment by martini** [comment]
In the meantime you can use ("André" AND "Bauer").

PS: You also can share Zammad & Kibana experiences. How does it work? What is the use case?

**Comment by monotek** [comment]
Usecase is statistics.
I want to label a graph with the fullname where i can only use 1 field.

**Comment by AchuM** [comment]
@monotek Does Kibana works now?

**Comment by monotek** [comment]
Not from my side as would like the changes mentioned above. 

@martini 
I've read something about a payed addon for reporting somewhere?
Is this done via Kibana?

**Comment by martini** [comment]
@AchuM in general Kibana works. If you have issue, please create a new issue for that.

@monotek I did a lot of statistics/reportings via elasticsearch/kibana/grafana the last times. For the `article.updated_by.fullname.keyword` issue we used `article.updated_by.login` to have a uniq name (because `André Bauer` can be twice).

 -=> So if you have further issue what attributes should get extended/merged into articles let me know (in best case with the use case of the report). Thanks a lot! 🎄

**Comment by martini** [comment]
> I've read something about a payed addon for reporting somewhere?

Currently no. We are looking to get it out as "standard" Zammad. We found out the moste investigation is to understand elastichsearch queries and aggregations to create the dashboard widgets. -> So we try to also deliver a bundle of default dashboard widgets.

**Comment by AchuM** [comment]
Thank you @martini I will try out and report back. 
 Is it okay if I try it on live Zammad? Do you think Zammad will be okay? 

Thanks again.

**Comment by martini** [comment]
> Is it okay if I try it on live Zammad? Do you think Zammad will be okay?

Yes! 👍 Usually it's not a big load for elasticsearch. You can do it agains live environments.

**Comment by monotek** [comment]
@martini 
ok, so maybe we can close this ticket as a workaround exists.

**Comment by martini** [comment]
@monotek thank you! Have a good time in Leipzig! 😻
