### ISSUE TITLE
API call /api/v1/online_notifications/{id} yields "no route"

### ISSUE THREAD

**Issue by nidico** [zammad/zammad#690]
Contrary to [the docs](https://docs.zammad.org/en/latest/api-notification.html), querying an individual `online_notification` through `GET /api/v1/online_notifications/12345` yields:

    {"error":"No route matches [GET] /api/v1/online_notifications/12345"}

`production.log` shows:

```
I, [2017-01-31T00:21:23.753562 #4428]  INFO -- : Started GET "/api/v1/online_notifications/12345" for 85.212.24.76 at 2017-01-31 00:21:23 +0100
I, [2017-01-31T00:21:23.767759 #4428]  INFO -- : Processing by ErrorsController#routing as */*
I, [2017-01-31T00:21:23.767970 #4428]  INFO -- :   Parameters: {"a"=>"api/v1/online_notifications/12345"}
E, [2017-01-31T00:21:23.773028 #4428] ERROR -- : No route matches [GET] /api/v1/online_notifications/12345
E, [2017-01-31T00:21:23.773104 #4428] ERROR -- : nil
I, [2017-01-31T00:21:23.778991 #4428]  INFO -- : Completed 404 Not Found in 11ms (Views: 0.5ms | ActiveRecord: 0.7ms)
I, [2017-01-31T00:21:24.165083 #4422]  INFO -- :  - no message
I, [2017-01-31T00:21:24.166590 #4422]  INFO -- : done
```

Note that

* querying `GET /api/v1/online_notifications` does work and the notification with ID `12345` does exist and even has the `user_id` set to the querying user.

* issuing `PUT /api/v1/online_notifications/12345` does work.

### Infos:

* Used Zammad version: 1.2
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Curl

**Comment by rolfschmidt** [comment]
@nidico Thank you very much for your support! I fixed the api for the get call. Should work with the next stable release ;-)
