### ISSUE TITLE
API docs mismatch tickets vs ticket article

### ISSUE THREAD

**Issue by nidico** [zammad/zammad#691]
I'm trying to get into the Zammad API, however I didn't manage to do my first intended task: Adding a note to a ticket.

The documentation confuses me: It looks like [updating a ticket](https://github.com/zammad/zammad-documentation/blob/master/api-ticket.rst#update) is the same as [creating a ticket article](https://github.com/zammad/zammad-documentation/blob/master/api-ticket-article.rst#create).

Unfortunately, trying any of both (using PUT on the ticket) returns 200, however it doesn't change the ticket or add a note / article.

Can you please enlighten me? Thanks a lot!

**Comment by rolfschmidt** [comment]
Hi @nidico 

First of all you need to take a look at the authentification:

https://docs.zammad.org/en/latest/api-intro.html

After it should be easy to create an article for you:

https://docs.zammad.org/en/latest/api-ticket-article.html

Here an example json data for a ticket with the id 2:

```
{
    "id": 2,
    "article": {
        "from": "Max Mustermann",
        "to": "",
        "cc": "",
        "body": "huhuhuu<br>huhuhuu<br>huhuhuu<br><br>",
        "content_type": "text/html",
        "ticket_id": 2,
        "type_id": 10,
        "sender_id": 1,
        "internal": "true",
        "in_reply_to": "",
        "form_id": "1111111",
        "time_unit": "12"
    },
}
```

and this would be the full curl request which i tested and it worked.

```
curl -u username@zammad.com:userpassword -H "Content-Type: application/json" -X PUT -d '{"id": 2, "article": {"from": "Harald Habebe", "to": "", "cc": "", "body": "huhuhuu<br>huhuhuu<br>huhuhuu<br><br>", "content_type": "text/html", "ticket_id": 2, "type_id": 10, "sender_id": 1, "internal": "true", "in_reply_to": "", "form_id": "1111111", "time_unit": "12"} }' https://rolf.zammad.com/api/v1/tickets/2
```

I hope this helps you :-)

**Comment by nidico** [comment]
Thanks, @rolfschmidt, this is what I tried. Authentication works fine (both HTTP Basic and HTTP Token auth). However the response is the unchanged ticket object - no article appears on the ticket screen.

**Comment by rolfschmidt** [comment]
Do you work an test instance of zammad.com?

**Comment by nidico** [comment]
No, we have an own productive installation (just not using the API yet).

**Comment by rolfschmidt** [comment]
@nidico, Could you please create a new test instance on 

https://zammad.com/getting-started

and try to reproduce the problem there?

**Comment by nidico** [comment]
Yes, same thing happens when trying to do

    curl -u ...:... -H "Content-Type: application/json" -X PUT -d '{"id":2, "artictle":{"from": "nidi", "to": "", "cc":"", "subject":"oi", "body": "lala", "content_type":"text/html", "ticket_id":1571, "type_id":10, "sender_id":1, "internal":"true", "in_reply_to": "", "form_id": "1111111", "time_unit": "12"}}'  https://niditest.zammad.com/api/v1/tickets/2

**Comment by rolfschmidt** [comment]
Hi @nidico 
you had an typo in the article hash key and there is also the ticket id in the article hash was wrong.

```
curl -u rolf@zammad.com:password -H "Content-Type: application/json" -X PUT -d '{"id": 2, "article": {"from": "nidi", "to": "", "cc": "", "subject": "oi", "body": "lala", "content_type": "text/html", "ticket_id": 2, "type_id": 10, "sender_id": 1, "internal": "true", "in_reply_to": "", "form_id": "1111111", "time_unit": "12"} }'  https://niditest.zammad.com/api/v1/tickets/2
```

This is the corrected statement.

**Comment by nidico** [comment]
Oops. Sorry for the noise.
