### ISSUE TITLE
Customer Management

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#692]
Hello,

we are using Zammad for one month and we got a huge list of autogenerated customers. Many of them we deactivate because of spam and make the list confusing. So its hard for an admin to manage the customers and find the newly created ones. 
Maybe you can display deactivated customers on a seperate list or just make an checkbox to fade them out and the searchbar could allow searching for organizations.

Greetings
tobibe

**Comment by thorsteneckel** [comment]
This [has been introduced with the new Elasticsearch 6 and 7 support](https://github.com/zammad/zammad/commit/af9fcf456573bce851a0d7ff08c472dfc377b218#diff-8f6c88adb98dfe5357010bf9c228739fR87). Users that are inactive will now be displayed at the end of the list.
