### ISSUE TITLE
Article Forward

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#693]
Hello,

is it possible to implement a "forward"-option to ask someone other than customer?
![zammadreply](https://cloud.githubusercontent.com/assets/9305993/22458846/99610b90-e79e-11e6-8635-2774cdd9c7ab.PNG)

Sometimes we have to ask someone other than the customer for additional information. Then we have to delete the customer email and insert the right one. If there is a forward button, which leaves the to and cc field blank, we are one click faster ;-)

Greetings 
tobibe

**Comment by tobibe** [comment]
I forgot: Also it may keep the attachments?

Greetings
tobibe

**Comment by thorsteneckel** [comment]
duplicate of #581
