### ISSUE TITLE
Notification settings: Not possible to disable all notifications

### ISSUE THREAD

**Issue by raphaelm** [zammad/zammad#696]
### Infos:

* Used Zammad version: 1.2
* Operating system: Linux
* Browser + version: Chrome 55

### Expected behavior:

* When I disable all checkboxes in the notification matrix, I should be able to save this setting

![2017-01-31-160326_728x326_scrot](https://cloud.githubusercontent.com/assets/64280/22470254/f51bd548-e7ce-11e6-9d96-68dae46ee28a.png)

### Actual behavior:

* Saving with at least one active checkbox works. As soon as all checkboxes are deactivated, saving does not work. The error console shows:

![2017-01-31-160316_1331x201_scrot](https://cloud.githubusercontent.com/assets/64280/22470295/188e2c24-e7cf-11e6-9760-11a44fb7c2be.png)

Cheers,
Raphael

**Comment by hanneshal** [comment]
Still exists in 2.0

**Comment by muhammadn** [comment]
@raphaelm I have tested it in the develop branch and the problem is fixed. Should be available in Zammad 2.4, or if you want to try it now you can try our develop branch in our github repo.

**Comment by thorsteneckel** [comment]
Just for the record - same issue as: https://github.com/zammad/zammad/issues/1488
