### ISSUE TITLE
No feedback on bulk operations if one ticket has no title

### ISSUE THREAD

**Issue by raphaelm** [zammad/zammad#697]
### Infos:

* Used Zammad version: 1.2
* Operating system: Linux
* Browser + version: Chrome 55

### Expected behavior:

* If I have a ticket overview that contains a ticket without a subject and perform a bulk operation on all tickets, it should just work (e.g. by setting a "[no subject]" title) or give a meaningful error message.

### Actual behavior:

* If I have a ticket overview that contains a ticket without a subject and preform a bulk operation on a selection of tickets, it will only be executed on the tickets *above* the one without the subject, not on all of them, with **no visual feedback at all**. If I then select the ticket's detail page (zoom view) and try to perform the same action, I get an error message.

This is rather annoying while closing/moving spam tickets ;)

Cheers
Raphael

**Comment by muhammadn** [comment]
@raphaelm Are you still getting this problem with our latest Zammad 2.3.0 since i cannot reproduce it on the latest 2.3.0.

**Comment by thorsteneckel** [comment]
Please reopen if issue persists and provide a detailed instruction on how to reproduce. Thanks and greetings 👋
