### ISSUE TITLE
Some text hard to read because of low contrast

### ISSUE THREAD

**Issue by johan12345** [zammad/zammad#698]
### Infos:

* Used Zammad version: 1.2
* Operating system: Windows 10
* Browser + version: Chrome 55

### Actual behavior:

* On one of my computers, I have a cheap, somewhat old LCD screen whose contrast ratio is not that great. When I look at a ticket overview in Zammad on this screen, the columns that don't have a link (-> use gray text instead of blue) are quite hard to read because of the low contrast ratio between the text and the background
* The colors used seem to be #f6f7f8 (background) and #aabdc5 (text). Their contrast ratio is lower than the W3C recommendation according to [this tool](http://leaverou.github.io/contrast-ratio/#%23aabdc5-on-%23f6f7f8), so this is probably not only a problem for people with crappy screens, but also an accessibility issue.
* The same color combination is also used in other places, e.g. for the timestamps below each entry in a ticket, but not in detailed search results (there, the text is #585856 instead, which is perfectly readable).

**Comment by martini** [comment]
Is this issue still open? Or already done with PR #783  ?

**Comment by johan12345** [comment]
@martini Well, there are some more places where #aabdc5 and other rather light colors are used as the text color that I haven't changed in PR #783, e.g.
- Ticket number in the upper left corner
- Number of tickets in an overview
- Details of the stats on the front page
- ...

**Comment by nsrosenqvist** [comment]
The sidebar is really hard to read as well in 2.2.0 when an item isn't selected. I have to adjust my position in order to look at the screen at a good angle just to be able to see what it says

**Comment by MrGeneration** [comment]
I believe that this directly covered by this issue:
https://github.com/zammad/zammad/issues/3067

As it's covering more than your issue (at least this is what I believe :x) I will close this issue as a duplicate.

Thank you very much for your time!
