### ISSUE TITLE
Agent cannot see his own tickets in which pointed as customer

### ISSUE THREAD

**Issue by skibson** [zammad/zammad#701]
When agent creates ticket for another group to which he does not belong and selects himself as customer he is not able to see this ticket. 
Agent should be customer as well by default

**Comment by skibson** [comment]
I created two users in two groups and ticket
User 1 ( ID 3 in group ID 2,3,4)
User 2 ( ID 23 in group ID 5)
Ticket ( ID 4491 in group ID 5 with owner ID 23 and customer ID 3)
and no one is capable of viewing this ticket. 
When I change ticket group ID from 5 to 3 under database, User 1 can see the ticket. 
I tried to modify app/models/ticket/permission.rb but I'm not familiar with ruby

**Comment by skibson** [comment]
I temporarily resolved this by adding permission_id 44 for role_id 2 in database table permissions_roles.
What do you think about this solution

**Comment by skibson** [comment]
#792 fixed

**Comment by thorsteneckel** [comment]
#967 is our leading issue for this. Closing this one.
