### ISSUE TITLE
Password Reset Mail doesn't arrive

### ISSUE THREAD

**Issue by ArcheNoah77** [zammad/zammad#703]
### Infos:

* Used Zammad version: 1.2.0
* Operating system: Debian 8
* Browser + version: Firefox 45.2.0

### Expected behavior:

* Password Reset Mal arrive

### Actual behavior:

* Password Reset Mail doesn't arrive

### Steps to reproduce the behavior:

* The notification E-Mail is the standard notification Master. I can't set my own Mail Address (The Client has no permission...)

**Comment by thorsteneckel** [comment]
Sorry, but I don't get it. Could you please describe the issue and the steps to reproduce it in more detail?

**Comment by ArcheNoah77** [comment]
I want to sign in on the zammad platform.
Then i click on "Forget Password" and i enter my email address. Actually i should get an email with the instructions to reset my password. But i don't get an email...
