### ISSUE TITLE
How do I change language?

### ISSUE THREAD

**Issue by madd86** [zammad/zammad#704]
When I go to settings->System->Translations and click 'Get Latest Translations' I got a lot of new languages and that's great.

But the question remains. How can I actually change the language?

**Comment by thorsteneckel** [comment]
Hi @madd86 - Each user can use the profile for this:

![language](https://cloud.githubusercontent.com/assets/3873515/22505351/59f279d4-e87b-11e6-8ba4-5f31bab75ecf.png)
