### ISSUE TITLE
Edge looses text formatting on reply (may also on other browsers)

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#707]
Hello,

if we use MS Edge with Zammad and try to reply on an marked text
![zammadreply1](https://cloud.githubusercontent.com/assets/9305993/22507917/f98c1566-e887-11e6-9e68-b20808709ef4.PNG)

it looses the formatting
![zammadreply2](https://cloud.githubusercontent.com/assets/9305993/22507926/08f9566c-e888-11e6-935e-949333b9e528.PNG)

In Firefox it works perfectly.

Greetings
tobibe

**Comment by martini** [comment]
Hi @tobibe 

we tested it on other browsers too. Also the real markup like headlines, bold, ... got lost.

Now we implemented it to support this too. It's in develop branch now. 🤠

<img width="645" alt="screen shot 2017-06-21 at 15 20 18" src="https://user-images.githubusercontent.com/110226/27386301-abcc64ee-5695-11e7-9527-02947b6f007c.png">

<img width="644" alt="screen shot 2017-06-21 at 15 21 50" src="https://user-images.githubusercontent.com/110226/27386300-aba92894-5695-11e7-90f6-0ddc41d5300a.png">

Tested on:

- Edge
- IE (sometimes problems with huge tables)
- Firefox
- Chrome
- Safari

 -Martin
