### ISSUE TITLE
Chat not working, web socket error in http/https mixed setup. Use protocol from script location of chat.js.

### ISSUE THREAD

**Issue by AlphaBootis** [zammad/zammad#708]
Greetings,

I've installed the Zammad RPM file, mostly following the how-to in the documentation.
I've been playing with zammad and it's features for about a week or two now, but I'm as of yet unable to get chat working.
It keeps spawning an error in the debug mode:

`WebSocket connection to 'ws://zammad.tda.nl/ws' failed: Error during WebSocket handshake: Unexpected response code: 504`

Exaple page with the chat code:
`http://kikkers.online/chat.html`

My experience with NGINX is minimal, and I fully expect it's an error on my end but I don't see the problem.
This is my zammad.conf (i got this from the contrib/nginx folder from github by the way, ssl access works) as it stands now:

```
upstream zammad {
    server 127.0.0.1:3000;
}

upstream zammad-websocket {
    server 127.0.0.1:6042;
}

server {
    listen 80;
    listen [::]:80;

    server_name zammad.tda.nl;

    access_log /var/log/nginx/example.com.access.log;
    error_log  /var/log/nginx/example.com.error.log;

    location /.well-known/ {
	root /var/www/html;
    }

    location / {
	rewrite ^/(.*)$ https://zammad.tda.nl/$1 permanent;
    }
}



server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name zammad.tda.nl;

    ssl_certificate /etc/letsencrypt/live/zammad.tda.nl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/zammad.tda.nl/privkey.pem;


    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    ssl_ciphers HIGH:!aNULL:!MD5;

    ssl_dhparam /etc/nginx/ssl/dhparam.pem;

    ssl_prefer_server_ciphers on;

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 180m;

    ssl_stapling on;
    ssl_stapling_verify on;

    ssl_trusted_certificate /etc/nginx/ssl/lets-encrypt-x3-cross-signed.pem;

    resolver 8.8.8.8 8.8.4.4;

    add_header Strict-Transport-Security "max-age=31536000" always;

    location = /robots.txt  {
	access_log off; log_not_found off;
    }

    location = /favicon.ico {
	access_log off; log_not_found off;
    }

    root /opt/zammad/public;

    access_log /var/log/nginx/example.com.access.log;
    error_log  /var/log/nginx/example.com.error.log;

    client_max_body_size 50M;

    location ~ ^/(assets/|robots.txt|humans.txt|favicon.ico) {
        expires max;
    }

    location /ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#        proxy_read_timeout 86400;
        proxy_pass http://zammad-websocket;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header CLIENT_IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 #       proxy_read_timeout 180;
        proxy_pass http://zammad;

        gzip on;
        gzip_types text/plain text/xml text/css image/svg+xml application/javascript application/x-javascript application/json application/xml;
        gzip_proxied any;
    }

}
```

Any push in the right direction would be greatly appreciated.

**Comment by martini** [comment]
Hi @AlphaBootis 

it seems like an http redirect issue. If I understood it correctly you redirect all http traffic to zammad.tda.nl to https.

If I see it correctly the web socket can't get redirected.

However, why not using using https directly in chat.html?

Just replace 

`<script src="http://zammad.tda.nl/assets/chat/chat.min.js"></script>`

with:

`<script src="https://zammad.tda.nl/assets/chat/chat.min.js"></script>`

Is it working then?

Feedback is welcome!

 -Martin

**Comment by AlphaBootis** [comment]
Hi @martini 

I've tried what you suggest, calling for the script over HTTPS, but this makes no difference. I've even turned off the http to https redirect. It doesn't seem to want to connect to the websocket.
When I telnet internally to the websocket port it works, so I also know it listens on 6042 so in my mind is must have something to do with proxy in Nginx, or the websocket doesn't actually work properly but I have not idea how to troubleshoot this.

Could I do an internal test and somehow force the chat script to connect directly to 6042 instead of /ws on port 80?

**Comment by martini** [comment]
Yes. You can set the host for web sockets directly in the js snippet via host:

Note: I can't connect to zammad.tda.nl:6042 via telnet, but it worked for me with:

"wss://zammad.tda.nl/ws", see below:

```
<script>
$(function() {
  new ZammadChat({
    background: '#b99a8e',
    fontSize: '12px',
    chatId: 1,
    show: true,
    debug: true,
    //host: 'ws://zammad.tda.nl:6042/ws',
    host: 'wss://zammad.tda.nl/ws',
    cssUrl: 'https://zammad.tda.nl/assets/chat/chat.css',
  });
});
</script>
```

Feedback is welcome!

**Comment by monotek** [comment]
So maybe it would be good to add a check in Zammad if its run via https and if os change the host url of the chat script code to "wss://..."?

**Comment by AlphaBootis** [comment]
I have back-end access to this server, i've not yet opened that port in the firewall but for testing purposes I could do so.
The chat however now seems to be working, for the moment i've got no definitive "thing" I did to make it so as I did a whole bunch of things yesterday to try and get it to work... I will see if i can find out what gives and feed this back to you.

**Comment by martini** [comment]
@monotek 

> So maybe it would be good to add a check in Zammad if its run via https and if os change the host url of the chat script code to "wss://..."?

We already detect his in the chat widget:
```
    detectHost: ->
      protocol = 'ws://'
      if window.location.protocol is 'https:'
        protocol = 'wss://'
      @options.host = "#{ protocol }#{ scriptHost }/ws"
```

**Comment by martini** [comment]
@AlphaBootis 

> I have back-end access to this server, i've not yet opened that port in the firewall but for testing purposes I could do so.

No, it's not needed. `host/ws` is just fine.

> The chat however now seems to be working, for the moment i've got no definitive "thing" I did to make it so as I did a whole bunch of things yesterday to try and get it to work... I will see if i can find out what gives and feed this back to you.

For me it would be interesting, why the chat widget did not auto detect `wss://zammad.tda.nl/ws` (because you use https in <script src="https://zammad.tda.nl/assets/chat/chat.min.js"></script>).

Sometimes it's funny. After writing this lines I got the answer. The chat widget simply does not support mixed protocols of Zammad instance and web page.

If both is http or https it just would work. :-o

Thinking about to improve it...

**Comment by martini** [comment]
@AlphaBootis @monotek Changed now for Zammad 1.3 the protocol detection from current web page window.location.protocol to get it from chat.js script location. Mixed http/https setup should now work out of the box. Feedback is welcome!

**Comment by MisterRobo** [comment]
> Yes. You can set the host for web sockets directly in the js snippet via host:
> 
> Note: I can't connect to zammad.tda.nl:6042 via telnet, but it worked for me with:
> 
> "wss://zammad.tda.nl/ws", see below:
> 
> ```
> <script>
> $(function() {
>   new ZammadChat({
>     background: '#b99a8e',
>     fontSize: '12px',
>     chatId: 1,
>     show: true,
>     debug: true,
>     //host: 'ws://zammad.tda.nl:6042/ws',
>     host: 'wss://zammad.tda.nl/ws',
>     cssUrl: 'https://zammad.tda.nl/assets/chat/chat.css',
>   });
> });
> </script>
> ```
> 
> Feedback is welcome!

@martini  thank you very much for your answer, it helped a lot
