### ISSUE TITLE
Cannot add Gmail label as folder in email account config

### ISSUE THREAD

**Issue by bastians** [zammad/zammad#711]
### Infos:

* Used Zammad version: 
* Operating system: Macintosh; Intel Mac OS X 10_12_2) 
* Browser + version: Chrome Version 56.0.2924.76 (64-bit)

### Expected behavior:

* add label from Gmail to folder field in email account config
* fetching all emails with that label to Zammad

### Actual behavior:

* after adding the label name in the folder field verification fails after some minutes at step sending and receiving emails

**Comment by madd86** [comment]
As a workaround, how about you actually create a folder instead of a label, would it work then?

![screenshot_1](https://cloud.githubusercontent.com/assets/23120598/22591650/c8a28ba8-e9fc-11e6-9095-d57b97744b49.png)

**Comment by bastians** [comment]
@madd86 As I understand, when you connect to Gmail via IMAP, the labels are the folders. Am I wrong?

**Comment by madd86** [comment]
Gmail works a little different than that. For instance, you can set multiple labels for a single message. There's no way to do that with folders, you can only have that one message in one folder.

The bottom line is, stick to folders.

**Comment by bastians** [comment]
@madd86 Yeah, that's what I know also :) But when you connect to Gmail through Outlook, for example, each label is shown as an folder. And an email that has two labels is just a copy in both folders. 

The screenshot you attached actually just show the function to "label" an email (function on the right) or to move an email to a label (an remove it from inbox; function on the left).

**Comment by madd86** [comment]
Not sure, I think outlook is parsing labels as folder. 

@martini have you tried adding a gmail with labels instead of folders?

**Comment by monotek** [comment]
Zammad is not a mail client.

**Comment by bastians** [comment]
Yeah, I know :)

Had anyone success connecting Zammad to a Gmail account and getting emails from a folder/ label?

**Comment by monotek** [comment]
So your problem is that mails with labels are not fetched?
Imho everything should be fetched ignoring labels.

Or do you want to only fetch mails with some special label?

**Comment by bastians** [comment]
> Or do you want to only fetch mails with some special label?

Exactly. Because I want to assign emails with different labels to different groups.

**Comment by jepf** [comment]
I cannot reproduce this. It works as expected for me: Zammad fetches only emails with the label configured within the folder field in Zammad.

@bastians: You wrote that the verification failed after some time. I'm not fully sure about this, but could it be that Zammad sends the test email to the gmail account and then tries to fetch the email with the given label/folder? Maybe the test email cannot be fetched because it is missing the label? Could you please try to immediately assign the label in gmail as soon as the test email is being received?
