### ISSUE TITLE
where will smart variables be defined?

### ISSUE THREAD

**Issue by undee123** [zammad/zammad#712]
### Infos:

* Used Zammad version: latest release on Ubuntu channel
* Operating system: Ubuntu Server 16.04.1 LTS
* Browser + version: Chrome 55.0.2883.87

I wonder where I could find these smart variables to use for emails in triggers (like #{ticket.title}).

**Comment by martini** [comment]
Hi @undee123 

are you looking for that?

<img width="740" alt="screen shot 2016-12-05 at 09 28 19" src="https://cloud.githubusercontent.com/assets/110226/22548153/6eddb564-e945-11e6-9f5a-fa5f599e39d4.png">

Just start with "::" 🍻

**Comment by undee123** [comment]
Hallo Martin,

yes, I was looking for these. Did I miss something in the documentation? 

Thx

Andreas

**Comment by martini** [comment]
@undee123 nothing missed. We just have no users doc published right now (only admin docs for installing and upgrading).

**Comment by sandrodz** [comment]
@martini Where do I search for `config.product_name` vars?
