### ISSUE TITLE
Unable to translate login screen

### ISSUE THREAD

**Issue by madd86** [zammad/zammad#713]
I wonder if changing the system language really impacts the login screen, because I've been unable to translate it.

**Comment by martini** [comment]
The login screen is translated on users browser language accept headers. Since only admin can start inline translations you can't enable the inline translation mode in the login screen.

 -=> You need to login, choose you target language, go to admin -> System -> Translations and translate the login screen here in the translation table.

**Comment by madd86** [comment]
Oh, makes sense that it shows on the browser's language. However, I did set the target language and the translations doesn't help since my own browser is en-US. 

I tried manually adding Sign in (as a target) and locale (en-us) on the table, but it didn't work.

I guess I'll modify the login.jst.eco file. I'm aware i'll lose changes upon update, but I can revert them back.

**Comment by martini** [comment]
What exactly do you want to change? 

> I tried manually adding Sign in (as a target) and locale (en-us) on the table, but it didn't work.

I would prefer this way, because you can upgrade without checking login.jst.eco all the times.

**Comment by madd86** [comment]
Everything that is in English to another language.

[http://prntscr.com/e3lltu](http://prntscr.com/e3lltu)

I tried that way, I went to the translations table, added a new record and set:

id (Default)
locale (en-us)
source (Sign in)
target (Aanmelden)
target_initial (Aanmelden)
created at and updated at automatically added.

Result? Same thing as the screenshot above.

**Comment by martini** [comment]
I just checked it. For me it works this way:

shell> rails c
rails> Translation.create!(source: 'Username / email', target: 'My Username / My Email', locale: 'en-us', format: 'string', created_by_id: 1, updated_by_id: 1)

Reloading login page with browser (first accept lang is en-us):

<img width="509" alt="screen shot 2017-02-02 at 16 21 45" src="https://cloud.githubusercontent.com/assets/110226/22555384/d14e7c6a-e963-11e6-856c-499e3dd3fb37.png">

PS: Fix for typo in the text is already on the way. Thanks!

**Comment by martini** [comment]
```
id (Default)
locale (en-us)
source (Sign in)
target (Aanmelden)
target_initial (Aanmelden)
created at and updated at automatically added.
```

I guess format is missing (use always "string", "date" for date formats).

**Comment by madd86** [comment]
Its not, its added. I'm using DataGrip.  I can't run rails c for the same reason I can't rake assets:precompile

`/opt/zammad/config/environments/development.rb:37:in `block in <top (required)>': uninitialized constant Rack::LiveReload (NameError)`
