### ISSUE TITLE
How can I remove registration?

### ISSUE THREAD

**Issue by madd86** [zammad/zammad#715]
I don't actually need to remove the whole thing, I'll be content with removing the registration link.

I've tried making changes to login.jst.eco but nothing changes.

Is it cached? How can I update cache?

**Comment by martini** [comment]
Hi @madd86 

there is a setting for that, got to admin -> Security -> Base -> New User Accounts -> No and submit.

After that users cannot start a registration anymore, also the text is removed.

 -Martin

PS: If you do changes to .eco, .js or .coffee you need to recompile the app ("rake assets:precompile") and restart it.
