### ISSUE TITLE
Running zammad in a subdirectory

### ISSUE THREAD

**Issue by MartinUrban** [zammad/zammad#717]
I need to run zammad in a subdirectory so I set config.action_controller.relative_url_root = "support" in config/application.rb as stated here: http://stackoverflow.com/questions/3355319/rails-app-in-a-subdirectory. In the nginx configuration file the corresponding two locations are also set to "support" so that requests arrive at zammad. .
From the production log I get the following lines.
```
I, [2017-02-02T16:24:55.911541 #16564]  INFO -- : Started GET "/support" for ::1 at 2017-02-02 16:24:55 +0100
I, [2017-02-02T16:24:55.917880 #16564]  INFO -- : Processing by ErrorsController#routing as HTML
I, [2017-02-02T16:24:55.918208 #16564]  INFO -- :   Parameters: {"a"=>"support"}
E, [2017-02-02T16:24:55.922773 #16564] ERROR -- : No route matches [GET] /support
E, [2017-02-02T16:24:55.923087 #16564] ERROR -- : nil
I, [2017-02-02T16:24:55.924458 #16564]  INFO -- :   Rendered inline template (0.6ms)
I, [2017-02-02T16:24:55.925731 #16564]  INFO -- : Completed 404 Not Found in 7ms (Views: 1.1ms | ActiveRecord: 0.9ms)
I, [2017-02-02T16:25:05.392357 #16573]  INFO -- : Scheduler running...
I, [2017-02-02T16:25:05.486649 #16573]  INFO -- : execute Ticket.process_escalation (try_count 0)...
I, [2017-02-02T16:25:15.901475 #16573]  INFO -- : execute Job.run (try_count 0)...
I, [2017-02-02T16:25:20.384864 #16573]  INFO -- : execute Channel.fetch (try_count 0)...
````

**Comment by thorsteneckel** [comment]
Hi @MartinUrban - This is more of an Rails setup issue than an Zammad issue. So I'm closing here. Maybe this one helps you: http://stackoverflow.com/a/3300062

As far as I understand relative_url_root tells Rails only to add the prefix to the generated URLs but the router system doesn't know about this. So you have to wrap all routes in `scope` block as described in the SO post above. The correct place would be: https://github.com/zammad/zammad/blob/9fe709f9b7765b63ef472d1f660bc29946c8b1b4/config/routes.rb#L3

Line 3-21 should make it. If you manage to get it to work feedback for others would be nice.

An alternative would be to use sub domains if possible.
