### ISSUE TITLE
Change font and font size in emails (templates)

### ISSUE THREAD

**Issue by bastians** [zammad/zammad#718]
It would be great to have the possibility to change some stylings in emails like font or font size to match CI guidelines ;) I'm talking about a template that by default all emails that are sent have these settings.

**Comment by martini** [comment]
Hi @bastians 

we have 2 different email type.

1) Emails which are sent to a customer
CSS and HTML email scaffold can be change in next upcoming release under config/initializers/html_email_style.rb

2) Agent notifications (e. g. about new or escalated tickets)
Can be already change in mailer templates located under app/views/mailer/$view/*.erb

-Martin

**Comment by bfal78** [comment]
Hello,

> Emails which are sent to a customer
> CSS and HTML email scaffold can be change in next upcoming release under
> config/initializers/html_email_style.rb

will this file overwritten during an update? 

Thanks
- Bjoern

**Comment by tobibe** [comment]
Hello @martini 

I changed the font in config/initializers/html but when I write me some Email I still get an email with the old style. Do I have to restart or rebuild something?

Greetings
tobibe

**Comment by bfal78** [comment]
Hello,

Each update overwrites the files, so the changes must be done every update.
Please make the Font style and size as an option.

Greetings
Bjoern

**Comment by tobibe** [comment]
I've restarted Zammad and then the style changed.
tobibe

**Comment by thorsteneckel** [comment]
Follow up enhancement: [Added Setting to define custom CSS font for HTML Emails without changing code](https://github.com/zammad/zammad/commit/2ecc60f22af1ca058a61b8a136b4c969c65a9137). Just use `Setting.set('...')` on the Zammad Rails console to overwrite(!) the default value.
