### ISSUE TITLE
Ticket without Subject is blocked - can't do anything with it ("Title needed")

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#719]
I've got an incoming Ticket which arrived without a subject via eMail. I need to assign this to a different group in my Helpdesk, but I can't do anything with it. Any action is blocked by a popup error message "Title needed":

![image](https://cloud.githubusercontent.com/assets/3321655/22564319/5c6985a4-e984-11e6-9936-46156954b283.png)

I did not see a way to edit the subject/ticket title in Zammad. How can I proceed with this ticket?

**Comment by martini** [comment]
Hi @jacotec 

Workaround: you need to click below the ticket title avatar and set an ticket title. After that you can process the ticket as usual.

 -Martin

**Comment by jacotec** [comment]
Hi @martini ,

thanks, that worked. Was not visible to me ;-)

**Comment by martini** [comment]
Thanks for report. It's fixed now.
