### ISSUE TITLE
Send ticket to customer's email 

### ISSUE THREAD

**Issue by madd86** [zammad/zammad#720]
Let's say I have a whole ticket that I want the customer to receive via email (like an outgoing phone call). How can I send it to him?

**Comment by martini** [comment]
Hi @madd86 

the use case is not clear to me. You want to forward a whole ticket (with all attachments) to another person via email?

 -Martin

**Comment by madd86** [comment]
Hey, 

Best thing would be each message individually, like a little "share" button underneath each message on the ticket, know what I mean?

That way, in case there's ever a need to share the message, you can just click there and share it.

We can start with only one option, "e-mail" and then later on move to more options such as facebook.

The reason for that is, let's say you make an outbound phone call ticket. it doesn't go via e-mail. And you end up attaching an important file that you need it to go via e-mail. You shouldn't have to open a whole new ticket just to send via e-mail, know what I mean?

**Comment by thorsteneckel** [comment]
This didn't got much traction over the last years. Please refer to the [community board](http://community.zammad.org/) for further discussions.
