### ISSUE TITLE
Omniauth OAuth redirect_uri_mismatch when https is used

### ISSUE THREAD

**Issue by schurig** [zammad/zammad#723]
### Infos:

* Used Zammad version: 1.2.0
* Operating system: Ubuntu 16.04

### Expected behavior:

* use https in callback url for github oauth

### Actual behavior:

* uses http in callback url for github oauth

### Steps to reproduce the behavior:

* set http type to `https`
* logout
* authorise with github on login page

### Known workaround
redirect `http` to `https` in nginx and use the http version of the url as callback url in the github oauth app setting

(related to #647)

**Comment by madd86** [comment]
It worked for me.

Remember that the callback url is actually set on **github** and not on Zammad.

Here:

![screenshot_3](https://cloud.githubusercontent.com/assets/23120598/22592307/42a589ca-ea00-11e6-98cf-17b793faa046.png)

**Comment by thorsteneckel** [comment]
Thanks @madd86 !

**Comment by schurig** [comment]
@madd86 that's what I did. The other thing is just the workaround so that it works

**Comment by thorsteneckel** [comment]
Hi @schurig - the

**Comment by thorsteneckel** [comment]
Hi @schurig - I think I got it! Are you running with an NGINX installation? If so please update your configuration and add these two lines:

```
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
```

Like in the screenshot:
<img width="547" alt="bildschirmfoto 2017-02-17 um 16 56 54" src="https://cloud.githubusercontent.com/assets/3873515/23072589/7cda9526-f532-11e6-8705-637a07ea7ba3.png">

Restart your NGINX and Zammad and let me know. Apache should be these lines:

```
RequestHeader set Host zammad.example.com
RequestHeader set X-Forwarded-Proto https
RequestHeader set X-Forwarded-Port 443
```

For the record: I dumped the rack.envs via an initializer overwriting the Omniauth ssl detection in a new rails initializer `config/initializers/debug_ssl.rb`:

```ruby
Rails.application.config.to_prepare do              # to_prepare ensures that the monkey patching happens before the first request
  OmniAuth::Strategy.class_eval do                  # reopen the class
    protected

    def ssl?                                        # redefine the ssl? method
      # DEBUG/CUSTOMIZATION
      File.write('/tmp/omniauth.log', request.env.inspect)
      # DEBUG/CUSTOMIZATION

      request.env['HTTPS'] == 'on' ||
        request.env['HTTP_X_FORWARDED_SSL'] == 'on' ||
        request.env['HTTP_X_FORWARDED_SCHEME'] == 'https' ||
        (request.env['HTTP_X_FORWARDED_PROTO'] && request.env['HTTP_X_FORWARDED_PROTO'].split(',')[0] == 'https') ||
        request.env['rack.url_scheme'] == 'https'
    end
  end
end
```

And none of the checked vars were set.

**Comment by schurig** [comment]
This was the problem! Thanks!! 😍  ❤️

**Comment by thorsteneckel** [comment]
Thanks for the feedback! Commit is on its way. 🚀 up to the next issue.

**Comment by salmagomaa** [comment]
Try this answer it worked with me
https://stackoverflow.com/a/41466634/1770571

**Comment by MrGeneration** [comment]
@salmagomaa this does not solve the problem and was a Bug within Zammad.
Please try not to recycle posts - the issue has been resolved already.
