### ISSUE TITLE
change default ticket_priorities

### ISSUE THREAD

**Issue by sebastianrechner** [zammad/zammad#728]
### Infos:

* Used Zammad version: 1.1.0
* Operating system: CentOS
* Browser + version: Firefox 51.0.1

Question:

* I changed the labels for the ticket_priorities to 1-critical, 2-high, 3-medium. unfortunateley the default prioritiy is id-2. How can I change the default id for the default priorities?
I changed it with insomnia.rest

**Comment by martini** [comment]
Hi @sebastianrechner 

this can be done in upcoming 1.3 release.

The Ticket::Priority model has a new attribute then. It's called "default_create". 

You can change it via REST or via rails console.

In your case you could do it this way:

```
zammad@host> rails c
priority1 = Priority.find(1)
priority1.name = '1-critical'
priority1.default_create = false
priority1.save!

priority2 = Priority.find(2)
priority2.name = '2-high'
priority2.default_create = true
priority2.save!

priority3 = Priority.find(3)
priority3.name = '3-medium'
priority3.default_create = false
priority3.save!
```

JFI: The we are also working on an admin interface for hat.

 -Martin

**Comment by chrisblech** [comment]
> JFI: The we are also working on an admin interface for (t?)hat.
> -Martin

As far I can see, that's not yet implemented. I propose to re-open this issue, as reminder for implementing this admin interface? Thanks.

My user story: After migrating from OTRS, new tickets are created with wrong priority.

**Comment by thorsteneckel** [comment]
Hi @chrisblech - please don't reply to old and closed issues. If you have an issue with this please make sure you are running the latest version. If the issue still persists you can create a new issue and respect the issue template. We will handle it appropriately.

Additionally: Please don't add `+1` under other issues. This creates a lot of noise for us (and a lot of other users) and has only negative effects on implementation speed of any issue. You can add your opinion on an issue via the emojis on the top right corner of any comment. Thanks for your understanding.
