### ISSUE TITLE
How i use Macros?

### ISSUE THREAD

**Issue by ArcheNoah77** [zammad/zammad#729]
Hey Guys,

i don't know how i use Macros or which sense they have...
A standard tag is "Close and tag as Spam" but how it works and how i use it?

**Comment by martini** [comment]
Hi @ArcheNoah77 

with macros you can execute a bulk of ticket changes with one click.

For example the default macro "Close and tag as Spam" -> Will:

1) close the ticket
2) set the owner to the current user
3) tag the ticket with spam tag

Here an example how to use it:

![macro_example](https://cloud.githubusercontent.com/assets/110226/22625182/6d29853a-eb8f-11e6-9426-91ada11baa1c.gif)
 
Greetings,

 -Martin
