### ISSUE TITLE
"Close Tab" & "Next in Overview" don't work

### ISSUE THREAD

**Issue by ArcheNoah77** [zammad/zammad#730]
### Infos:

* Used Zammad version: 1.2.0
* Operating system: Debian 8
* Browser + version: Firefox 45

### Expected behavior:

* If i select "Close Tab" next to "Update" and click on "Update" in a ticket, the tab on the left side should disappear
* If i select "Next in Overview" next to "Update" and click on "Update" in a ticket, i should see the next ticket in Overview

### Actual behavior:

* Nothing happens when i click on "Update" ("Aktualisieren" in German)

![2](https://cloud.githubusercontent.com/assets/25475591/22595699/e9ce070e-ea28-11e6-86d8-4a962528f806.png)
![1](https://cloud.githubusercontent.com/assets/25475591/22595698/e9ca8048-ea28-11e6-9331-49598dcca09e.png)

**Comment by martini** [comment]
@ArcheNoah77 thanks for the report. I can reproduce it. Will be fixed ASAP.

**Comment by martini** [comment]
It's fixed in stable branch. Feedback would be fine!

**Comment by ArcheNoah77** [comment]
Thank you very much!
how i get the stable branch?

**Comment by martini** [comment]
Did you install Zammad via package (DEP/RPM)? Just upgrade the packages (we build updates on every bugfix).

**Comment by ArcheNoah77** [comment]
ok, i got it.

But now, there is another problem with this feature...
When i choose "Next in Overview" , the actual Tab close... Or is it studied?
