### ISSUE TITLE
Time Accounting: Add possibility to change the field type of the input field to dropdown

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#736]
User recommendation:

It would be great if the admin would have the possibility to insert the accounted time in a dropdown with prepared values instead of a input field (Ticket#101667).

**Comment by thorsteneckel** [comment]
This is more of a custom requirement / different approach to to time accounting than the one we decided for – and didn't get much traction over the last three years. However, Zammad is extendable via Addons. If you're reading this and are interested please get in contact with sales at zammad.com
