### ISSUE TITLE
GMail Outbound Server: Zammad is not a trusted software

### ISSUE THREAD

**Issue by Tenente-Dan** [zammad/zammad#745]
### Infos:

* Used Zammad version: 1.3
* Operating system: Ubuntu 16.04
* Browser + version: Firefox 51.0.1

### Expected behavior:

* Send e-mail to client from outlook smtp server. On my gmail's service, I'm unable to register as a outbound server, they sad Zammad is not a trusted software.

### Actual behavior:

* Showing Delivery failed: "Unable to send email to 'administrativo@maisalerta.com.br': Can't use Channel::Driver::Smtp: #<EOFError: end of file reached>" 

Outbound
User 	scalioni_dan@hotmail.com
Host 	smtp-mail.outlook.com
Protocol 	smtp
Can't use Channel::Driver::Smtp: #<EOFError: end of file reached> 

### Steps to reproduce the behavior:

* Create a reply 

I'm a brand new Zammad's user, so, may you help me?
I'm trying to make Zammad usable by my enterprise.
Tks.

**Comment by kernbrand** [comment]
have you allowed "less secure apps" in gmail?

https://support.google.com/accounts/answer/6010255?hl=en

**Comment by Tenente-Dan** [comment]
I'll try.
Could you point me any tutorial to make gmail work with Zammad?
Tks

**Comment by kernbrand** [comment]
i assume there is none, zammad is very new and gmail works very similar to other mail hosters. the only difference is the "less secure apps" setting, but this is not specifically zammad-related.

**Comment by thorsteneckel** [comment]
Seems to be resolved. Happy to accept pull requests for our documentation.
