### ISSUE TITLE
Unable to work in Empty Ticket

### ISSUE THREAD

**Issue by simoon-de** [zammad/zammad#747]
Hi,
if a user sends an email without subject or text you can not work with the email or close it.
br.
Alex
### Infos:

* Used Zammad version: 1.2
* Operating system: Debian
* Browser + version: Firefox

### Expected behavior:

Close a Ticket or work with it.

### Actual behavior:

Printing: Modal with "Title needed" text

### Steps to reproduce the behavior:

Send an emtpy email to the ticket system

**Comment by thorsteneckel** [comment]
HI @simoon-de - please see #719
