### ISSUE TITLE
Overview: "Type is chat" gives no result

### ISSUE THREAD

**Issue by petervanbeugen** [zammad/zammad#748]
Creating an overview with Type = chat gives no results at all.

Zammad 1.2 latest RPM

**Comment by martini** [comment]
Hi @petervanbeugen 

I just tested it on current stable. It was no problem to create an overview with name "chat". But of cause I needed to add an condition what tickets should be shown.

Do you have more information for me how to reproduce? (I know issue is from feb)

 -Martin

**Comment by hanneshal** [comment]
Closed. 
Please reopen if the issue still exists in Version 2.0.
