### ISSUE TITLE
Wrong ticket in overview

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#749]
Hello,

we rarly have tickets in overviews, which not match the overview condition.
E.g:
![zammadclosed](https://cloud.githubusercontent.com/assets/9305993/22774844/37ec4db8-eea9-11e6-86db-a53815932cbe.png)
Here is a closed ticket, but
![zammadclosedoverview](https://cloud.githubusercontent.com/assets/9305993/22774845/37f0dedc-eea9-11e6-9e7d-a0c59dd7cbf4.png)
the overview only takes open and new tickets.

If I close this ticket again, then it disappears from the overview. 

I kept the database before I close the ticket again, so if there are special questions about content, maybe I can help.

Greetings 
tobibe

**Comment by tobibe** [comment]
Hello @rolfschmidt, hello @martini ,

is this maybe solved by #904 , too?

Greetings
tobibe

**Comment by tobibe** [comment]
I no longer recognized such wrong tickets and close this issue.

Greetings 
tobibe

**Comment by martini** [comment]
@tobibe thanks for feedback, yes #904 is a good duplicate candidate.
