### ISSUE TITLE
[Request] When clicking a text in a ticket, expand "See more"

### ISSUE THREAD

**Issue by Kunsi** [zammad/zammad#755]
Hi,

currently, when you click on a text in a ticket, it will show some Information regarding the channel which added the text.
It would be very nice to have this click also expand the text, if there's a "see more" link included.

**Comment by rolfschmidt** [comment]
Hey @Kunsi ,
if you click on the article box then you will have an expanded information about the channel and also a clickable link to the original entry on facebook/twitter etc:

![grafik](https://user-images.githubusercontent.com/5445062/35865305-76e9c04a-0b54-11e8-95ba-323958999a4a.png)

If you any more questions regarding this topic, then feel free to reopen it ;-)

Best regards,
Rolf

**Comment by codingcatgirl** [comment]
Hey @rolfschmidt,

> If you any more questions regarding this topic

I have a question regarding this topic: Are you aware that you just repeated the first line of the issue @Kunsi reported? :D Here's what she wrote again (the first line, describing the current behaviour – in contrast to the second line describing the behaviour she desires, hence the issue):
> currently, when you click on a text in a ticket, it will show some Information regarding the channel which added the text.

Here's what you wrote (literally your entire answer):
> if you click on the article box then you will have an expanded information about the channel and also a clickable link to the original entry on facebook/twitter etc:

I'd recommend to check out the second line of the issue (or the title of the issue, for that matter) as it is vital to understanding what @Kunsi wants and appropriately responding to the issue at hand – you seem to have overlooked it completely:

> It would be very nice to have this click also expand the text, if there's a "see more" link included.

Cheers,

Laura

**Comment by rolfschmidt** [comment]
Hey,
sorry for closing the issue. I did not correctly understand that you want to display the full article also on click of the article box.

I talked to @martini and in our opinion this is not a good idea. We have many customers, who also write very large texts and if you combine the expand of the article box with the display of the full text of the article, then it will be hard to get to the footer of the article box. We think this will reduce user-friendliness of the page.

Best regards,
Rolf

**Comment by Kunsi** [comment]
Then … make it configurable?

**Comment by rolfschmidt** [comment]
Hi,
currently this is not planned for our roadmap, but we are open for pull requests based on a configurable option to enable this feature.

Best regards,
Rolf

**Comment by thorsteneckel** [comment]
Hi together - I'll close this because only bugs are handled here on Github. Feel free to create a summary post of this issue over at our [board](https://community.zammad.org/) - as described in the issue template.

Regarding configuration: Our goal is to keep Zammad slim but extendable. So instead of creating a PR please create an extension. If you have any questions or issues while creating this extension please create a post at our community board. We are happy to help and extend/improve the existing information.

Thanks for your understanding.
