### ISSUE TITLE
Sender Format don't work

### ISSUE THREAD

**Issue by ArcheNoah77** [zammad/zammad#756]
I chose as Sender Format "Agent Name + FromSeperator + System Address Display Name".
But in the Mails is just the System Address Display Name...

Is it a bug?

**Comment by thorsteneckel** [comment]
Hi @ArcheNoah77 - please provide further information on your:

- Zammad Version
- OS

And please provide a step by step text how to reproduce. Thanks!

**Comment by ArcheNoah77** [comment]
Zammad Version: 1.2.0
OS: Debian 8
Expected Behavior: I answer a ticket and the customer should get an E-Mail and the Sender should be "Noah ... via PROLANT IT-Support"
Actual Behavior: The customer get an E-Mail and the Send
er is just "PROPLANT IT-Support". SO just the System Address Display Name.
Like: 
![1](https://cloud.githubusercontent.com/assets/25475591/22976893/e7230410-f38c-11e6-9bb7-27b4c50f98bb.png)

Before "PROPLANT IT-Support" has to stand "Noah ... via"

As Sender Format i choose "Agent Name + FromSeperator + System Address Display Name"

**Comment by thorsteneckel** [comment]
Hi @ArcheNoah77 - is the behavior still reproducible in latest Zammad 1.3.0 ?

**Comment by ArcheNoah77** [comment]
Yes, still the same Problem with 1.3.0
