### ISSUE TITLE
Auto Answer Trigger don't work

### ISSUE THREAD

**Issue by RobiiRob** [zammad/zammad#758]
Hello guys,

### Infos:

* Used Zammad version: 1.2.0
* Operating system: Server: Ubuntu Desktop 16.04.1; Client: Windows 7 64bit Pro
* Browser + version: Chrome 56.0.2924.87 (64-bit)

### Expected behavior:

* i want a triggered event for auto answer an incoming mail request. There is already an default trigger for this i know but its not working. So i tried to create a new one with the same settings but nothing happens. 

![image](https://cloud.githubusercontent.com/assets/25764594/22921861/a20d7ee2-f29b-11e6-9140-ce6b6e11a227.png)

### Actual behavior:

* Scheduler is working fine. error log is empty. Mail Settings are working too. I have reboot the client and the server too.

### Steps to reproduce the behavior:

* if a Helprequest gets in via Mail, i want to auto answer him, that we are working on it (like the default trigger) but nothing happens.

i already searched here for answers but i just found one closed issue, which said that its works fine after a reboot.

(i'm new in Zammad)

**Comment by kernbrand** [comment]
there's a default trigger in zammad called "auto reply (on new tickets)". does the default trigger work?

**Comment by RobiiRob** [comment]
no even the default trigger with the default settings don't work. I really dont know what it could be. 

mabye a bug??

**Comment by seaneble** [comment]
Did you test with your own e-mail address? That will not work with the default trigger, because you're likely classified as "Agent", not as "Customer".

**Comment by RobiiRob** [comment]
I tested it with my own Account as "Agent/Admin", i also tried it with 2 more "Customer" Accounts but nothing. I also testet if mabye the Spamfilter don't let it trought but nope. Can't find the mistake.

**Comment by thorsteneckel** [comment]
Could you please start another try and monitor / provide the log file while doing so? Maybe there are more information there. You can send it to our support at zammad.com address if you don't want to make it here available. Please let us know then about the relation to this issue. Thanks!

**Comment by RobiiRob** [comment]
i just sended a mail to your address with a little log file as attachment. Thanks for your help.

**Comment by RobiiRob** [comment]
I "fixed" it. I have set up a new VM with Ubuntu and Zammad and configured and tested it step by step. Still working. Looks like a bug. (Before i installed the new VM i updated it to 1.3.0 but it changed nothing).

**Comment by kmclea16** [comment]
I'm having the same issue with notifications. Agent notifications are working but customers do not receive notifications with the default trigger auto reply (on new tickets).
I don't want to set things up from scratch :( 

![attach1](https://cloud.githubusercontent.com/assets/28083040/25469070/6797e1b2-2b5d-11e7-98f5-0eb6cc700c00.jpg)
![attach2](https://cloud.githubusercontent.com/assets/28083040/25469071/6798096c-2b5d-11e7-8794-83e10e9ce9c1.jpg)

**Comment by WillemWever** [comment]
I had the same issue. I solved it by filling in the emailaddress on the groups.

**Comment by Khawlamel** [comment]
@WillemWever I have same problem but I don't have any group ,can i find the solution without adding the groups? if not how can I do if possible tell me the steps you did please and thank you in advance :)

**Comment by MrGeneration** [comment]
@Khawlamel please don't hijack closed issued.
This is a solved bug.

If you have technical questions / issues, please consult the community over at https://community.zammad.org 

If this happens to be a bug, we'll gladly at a report later on.

Thanks for your understanding.

**Comment by Khawlamel** [comment]
@MrGeneration well received thank you
