### ISSUE TITLE
Admin Interface -> Time Accouting: Add possibility to display accounted time per ticket per day.

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#760]
Admin Interface -> Time Accouting: Add possibility to display accounted time per ticket per day.

**Comment by aaratn** [comment]
+1

**Comment by nublaii** [comment]
+1

**Comment by KoJie** [comment]
as this is a [duplicate](https://github.com/zammad/zammad/issues/1580) i close this one as well.
