### ISSUE TITLE
Install error on deb8 stable - Mysql2::Error: Access denied for user 'zammad'@'' to database 'zammad'

### ISSUE THREAD

**Issue by vincling** [zammad/zammad#762]
### Infos:

* Used Zammad version:  latest from repo installed today
* Operating system: deb 8 stable openvz 
*  apache2            2.4.10-10+deb8
*  mysql-server       5.5.54-0+deb8u

### Actual behavior:

During installation I get errors with sql setup
 Installing zammad on mysql
 Creating zammad mysql db
 Creating zammad mysql user
 Grant privileges to new mysql user
 Updating database.yml
rake aborted!
Mysql2::Error: Access denied for user 'zammad'@'' to database 'zammad'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:i                   n `connect'
[...]
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (requ                   ired)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
rake aborted!
Mysql2::Error: Access denied for user 'zammad'@'' to database 'zammad'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:87:i                   n `connect'
[...]
/railties/databases.rake:182:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (requ                   ired)>'
Tasks: TOP => db:abort_if_pending_migrations => environment

the server is a fresh setup without anything touched before. 
Do you have any advice? 

BR
Magda

**Comment by vincling** [comment]
full log
[zammad_install_log.txt](https://github.com/zammad/zammad/files/774227/zammad_install_log.txt)

**Comment by vincling** [comment]
ok, just one last update: 
I've set the access rights for the user, mysql connection is fine, but then 
Syntax Error! 

# database.yml found. Updating db...
== 20120101000001 CreateBase: migrating =======================================
-- create_table(:sessions)
   -> 0.0025s
-- add_index(:sessions, :session_id)
   -> 0.0163s
-- add_index(:sessions, :updated_at)
   -> 0.0197s
-- add_index(:sessions, :persistent)
   -> 0.0200s
-- create_table(:users)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

`Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQ                                 L server version for the right syntax to use near '(3), `source` varchar(200), `login_failed` int(1                                 1) DEFAULT 0 NOT NULL, `preferen' at line 1: CREATE TABLE `users` (`id` int(11) auto_increment PRIM                                 ARY KEY, `organization_id` int(11), `login` varchar(255) NOT NULL, `firstname` varchar(100) DEFAULT                                  '', `lastname` varchar(100) DEFAULT '', `email` varchar(255) DEFAULT '', `image` varchar(100), `im                                 age_source` varchar(200), `web` varchar(100) DEFAULT '', `password` varchar(100), `phone` varchar(1                                 00) DEFAULT '', `fax` varchar(100) DEFAULT '', `mobile` varchar(100) DEFAULT '', `department` varch                                 ar(200) DEFAULT '', `street` varchar(120) DEFAULT '', `zip` varchar(100) DEFAULT '', `city` varchar                                 (100) DEFAULT '', `country` varchar(100) DEFAULT '', `address` varchar(500) DEFAULT '', `vip` tinyi                                 nt(1) DEFAULT 0, `verified` tinyint(1) DEFAULT 0 NOT NULL, `active` tinyint(1) DEFAULT 1 NOT NULL,                                  `note` varchar(250) DEFAULT '', `last_login` datetime(3), `source` varchar(200), `login_failed` int                                 (11) DEFAULT 0 NOT NULL, `preferences` varchar(8000), `updated_by_id` int(11) NOT NULL, `created_by                                 _id` int(11) NOT NULL, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL) ENGINE                                 =InnoDB
`

**Comment by monotek** [comment]
Which MySQL version is used?
You need at least MySQL 5.6 or MariaDB 10.0

**Comment by vincling** [comment]
Its 5.5 like writen above. 
Is it the cause for both errors? Setting the correct permissions should be working anyways, shouldnt it?

**Comment by monotek** [comment]
No. You need MySLQ 5.6.
https://docs.zammad.org/en/latest/prerequisites-software.html
