### ISSUE TITLE
Customer names are sometimes wrapped with quotes

### ISSUE THREAD

**Issue by johan12345** [zammad/zammad#763]
### Infos:

* Used Zammad version: 1.2
* Operating system: Windows
* Browser + version: Chrome 56

### Expected behavior:

* Customer names should be correctly parsed from email headers, removing quote characters if present

### Actual behavior:

* In some cases, the customer name is wrapped in quote characters (e.g. `"John Doe"` , where the first name is `"John` and the last name `Doe"`)
* looking at the code, there already seems to be something in place [here](https://github.com/zammad/zammad/blob/master/app/models/channel/email_parser.rb#L117) to prevent this, I'm not sure why it does not work (or at least not all the time).

**Comment by martini** [comment]
Hi @johan12345 

thanks for feedback. One question, where in the UI do you seed the quote characters where you do not want to see them?

Background: We receive mails from outlook/exchange like "Bob, Smith" <sender@example.com>. Users do c&p to fill to or cc. In this case if we remove " it will lead to an SMTP error (because , is the separator for new email addresses in SMTP).

 -Martin

**Comment by johan12345** [comment]
Hi @martini ,
thanks for the quick reply.

We have set up a text module that includes the text `Hello {first name}`, where the first name is automatically filled in. In the cases I mentioned, the first name starts with a quote character, so it ends up as `Hello "John`.

The quote also appears in the initials shown as the user avatar, which looks strange (-> `"D`). It also shouldn't matter for the copy-paste case if the quotes would be removed in the customer info side panel and in the customer column in a ticket overview (because in these locations the name is shown separately from the email address).

**Comment by martini** [comment]
Thanks for feedback. Yes, this clear and not c&p related.

It would be wonderful to get test cases. Can you add the email raw "From:" header of the problems to this issue?

**Comment by johan12345** [comment]
The raw header is (I slightly edited the name and email address for privacy):
`From: =?UTF-8?Q?=22Frieda_H=C3=B6flich=22?= <frieda.hoeflich@example.com>`
or in decoded form
`From: "Frieda Höflich" <frieda.hoeflich@example.com>`

**Comment by martini** [comment]
Hi @johan12345 

thanks for the very good description. Now we found the issue (in certain cases also ' are used - we replace both now) and fixed it.

It's available in next upcoming release.

Thanks!

 -Martin
