### ISSUE TITLE
Not showing TO: / CC: fields on IE11 when answering a ticket

### ISSUE THREAD

**Issue by monclefu** [zammad/zammad#764]
### Infos:

* Used Zammad version: 1.2.0 
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Internet Explorer 11

### Expected behavior:
Click on Reply (Antworten) in Ticket opens the fields TO: and CC:

### Actual behavior:
No fields TO: nor CC:

### Steps to reproduce the behavior:
Checked on Chrome - it works, Checked on IE11 Versions on Windows 7,8.8.1 and 10 - does not work.

Pictures show same Ticket on
IE11:
![ie11](https://cloud.githubusercontent.com/assets/18439429/22976200/13f23450-f38a-11e6-904e-a01dafdaf2a6.PNG)

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/18439429/22976241/3dc1d560-f38a-11e6-931b-427c27250e8f.PNG)

**Comment by monclefu** [comment]
![html chrome](https://cloud.githubusercontent.com/assets/18439429/23207847/08cfc628-f8f3-11e6-8129-0400d1144266.PNG)
![html ie](https://cloud.githubusercontent.com/assets/18439429/23207848/08e5bafa-f8f3-11e6-8919-1ff3ff6d6063.PNG)

**Comment by monclefu** [comment]
I've setup a new system and on the one system in IE I'll get this:
![not running](https://cloud.githubusercontent.com/assets/18439429/23210425/ceb0fe8e-f8fd-11e6-9cbf-c0a3b9f4790a.PNG)

And on the other system the EMAL Value is in the code:
![running](https://cloud.githubusercontent.com/assets/18439429/23210438/dc2589fe-f8fd-11e6-8930-920e6441f1bd.PNG)

So I'm missing the EMail addres...

Any thoughts on this????

**Comment by robwilc** [comment]
We have the same issue... other browsers are fine, but Internet Explorer, not.

**Comment by monclefu** [comment]
So I updated every thing and checked ALL config files. Still no luck. Even a reinstall of zammad with die packerger.io deb did not change the behavior. Any thoughts on this?

**Comment by monclefu** [comment]
Problem still open.
Checked locale: ok
Checked updates: ok

2nd System I installed works with all browsers.

**Comment by martini** [comment]
Thanks for all the feedback. Now I'm able to reproduce it.

**Comment by martini** [comment]
It's fixed now in develop, stable-1.5 and stable.1.4.
