### ISSUE TITLE
Zammad still tracks twitter retweets

### ISSUE THREAD

**Issue by schurig** [zammad/zammad#765]
### Infos:

* Used Zammad version: 1.3.0

### Expected behavior:

* Zammad ignores retweets if option is not checked (see #630):

![screen shot 2017-02-16 at 00 12 43](https://cloud.githubusercontent.com/assets/2672413/22999613/a8726bde-f3dc-11e6-839a-db9e89cb9b76.jpg)

### Actual behavior:

* it still created tickets for it

I have no idea why it does that. Here is the section of the code that checks if the tweet is a retweet:
https://github.com/zammad/zammad/blob/develop/app/models/channel/driver/twitter.rb#L303

### Steps to reproduce the behavior:

* retweet a tweet of your twitter account you added in Zammad

**Comment by thorsteneckel** [comment]
Hi @schurig - I'm confused too. I can reproduce the issue on a fresh Zammad installation as follows:

- Setup Twitter-Channel with Account Bob with disabled retweets
- Create a Tweet as Bob, retweet it with account Alice
- Re-Tweet gets imported
- Configure channel to track retweets
- Create a Tweet as Bob, retweet it with account Alice
- Re-Tweet **doesn't** get imported
- Configure channel to don't track retweets
- Create a Tweet as Bob, retweet it with account Alice
- Re-Tweet **doesn't** get imported

This is very strange 🤔 I'll need to have a deeper look. JFI we even created tests to check this behavior:

Track enabled:
https://github.com/zammad/zammad/blob/c96f5b46a8c136dbfe7df7bdef94a04e62ab821a/test/integration/twitter_test.rb#L440

Track disabled:
https://github.com/zammad/zammad/blob/c96f5b46a8c136dbfe7df7bdef94a04e62ab821a/test/integration/twitter_test.rb#L477

**Comment by schurig** [comment]
@thorsteneckel I just noticed the

```ruby
next if !track_retweets? && tweet.retweet?
```

part. That doesn't make sense, does it?

It should break if the `track_retweets` option is off and the current tweet is a retweet. So shouldn't it should be

```ruby
break if !track_retweets? && tweet.retweet?
```
?

**Comment by thorsteneckel** [comment]
I switched from `break` to `next` because the loop yields each relevant tweet. If we `break` the loop all tweets after that will get skipped which is not what we want.

In the meantime I found the source of the issue - the streaming API 🤦‍♂️ 
https://github.com/zammad/zammad/blob/develop/app/models/channel/driver/twitter.rb#L203

Looks like we missed that 👼  I'm on it.

**Comment by schurig** [comment]
Ah I see, of course `next` is the better option there (I associated `next` with `don't break up and continue` instead of `skip this entry and start with the next one` ==> ☕️)!

So we only forgot to implement it in the streaming API am I understanding this right? Damn, I've been waiting for this enhancement to be in a stable release for more than a month now 🤦‍♂️

![screen shot 2017-02-16 at 11 56 12](https://cloud.githubusercontent.com/assets/2672413/23018626/fb7f2c4c-f43e-11e6-8a21-0bece0c2cb05.jpg)

**Comment by thorsteneckel** [comment]
I guess so 😞 I'll write some tests, wrap it up and push it to develop. Sadly today is a far-off date from the next stable release 🤦‍♂️ Not sure if it's an option to use the patch in your system.

**Comment by thorsteneckel** [comment]
Hi @schurig - I fixed it and extended the tests with the commit(s) above. Had some wired issues with the `Thread.new` spawning of the `Channel.stream` call which took some time. Nevertheless I pushed to `develop` and `stable` so there should be a new release in about 30min if you're using the the stable package source for your OS. Feedback is welcome 🚀
