### ISSUE TITLE
Imap + STARTTLS

### ISSUE THREAD

**Issue by osixia** [zammad/zammad#769]
### Infos:

* Used Zammad version: 1.3.0 
* Operating system: Docker image on Ubuntu

### Expected behavior:

* Just tried to connect zammad to my mailserver but starttls seems not supported for IMAP connection.

### Actual behavior:

For IMAP connection we can only choose between SSL:
- no (port 143)
- yes (port 993)
and nothing about starttls on port 143 for example ?

adding an option to the ssl selectbox would be nice like SSL: no / yes / starttls
or just start tls automatically if supported by the server like with smtp

Thanks for this great software!

**Comment by martini** [comment]
Hi @osixia Is just tried to reproduce it. Can you tell me which provider is using STARTTLS, right now I'm searching for an test account. Thanks!

**Comment by osixia** [comment]
Hello,
we notice that with our own mailservers.

Imaps (port 993) was disabled on we only supported imap (143) + STARTTLS 
imap connections without STARTTLS where refused. So zammad connection where refused.
(this still fail i just test that config again)

Since we added imaps support to get zammad works.

I do not know any public provider with a configuration this limited.
If you want i can create a test email account on our server and disable imaps so you can test this.

**Comment by kingkrausel** [comment]
uberspace.de uses IMAP + STARTTLS. You can create an account for free there.

**Comment by osieben** [comment]
Need imap with starttls here as well, this is currently a project stopper.

**Comment by martin31821** [comment]
Same problem here. I'll give it a shot and create a PR.
