### ISSUE TITLE
Schedular is not running/Telegram can't send messages

### ISSUE THREAD

**Issue by chrisdecker1201** [zammad/zammad#771]
### Infos:

* Used Zammad version: 1.3
* Operating system: Debian 8.7
* Browser + version: Firefox + 51.0.1

### Expected behavior:

* Telegram just send out the message.

### Actual behavior:

* I just configured Telegram and all works fine, but when I try to answer a opened ticket in zammad, the message never gets out. First I thought maybe it's because it's my bot and I'm writing to it with the telegram account which relies on it, but I checked it with a mate and it's the same. I'm glade to help with debugging or maybe I just missed a little thing.
To be more specific: The Welcome Message reaches the telegram client and the telegram messages reaches zammad, but then zammad does not send anything to the telegram client.

### Steps to reproduce the behavior:

@thorsteneckel: I tried to start the schedular but getting the following output
`./script/scheduler.rb start`

`/usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- daemons (LoadError)
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
	from ./script/scheduler.rb:6:in '<main>'`

So I seem to have problems with that.

**Comment by thorsteneckel** [comment]
Hm. That's strange `deamons` is part of our `Gemfile` and `Gemfile.lock`for a very long time:

https://github.com/zammad/zammad/blame/develop/Gemfile#L56
https://github.com/zammad/zammad/blame/develop/Gemfile.lock#L85

Can you try the following in the Zammad root directory:

1.) `bundle` (installs/updates gems but shouldn't) and provide the output here.
2.) try again and provide the output here.
3.) try it with `bundle exec script/scheduler.rb start` run ruby in the bundle context.

**Comment by chrisdecker1201** [comment]
# bundle output
`Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Using rake 11.2.2
Using i18n 0.7.0
Using minitest 5.9.0
Using json 1.8.3
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 1.6.4
Using mime-types-data 3.2016.0521
Using arel 6.0.3
Using multi_json 1.12.1
Using thor 0.19.1
Using addressable 2.4.0
Using ffi 1.9.14
Using execjs 2.7.0
Using clavius 1.0.2
Using browser 2.2.0
Using buftok 0.2.0
Using nestful 1.1.1
Using coffee-script-source 1.10.0
Using concurrent-ruby 1.0.2
Using daemons 1.2.4
Using diffy 3.1.0
Using unf_ext 0.0.7.2
Using eco-source 1.1.0.rc.1
Using dnsruby 1.59.3
Using eventmachine 1.2.0.1
Using http_parser.rb 0.6.0
Using hashie 3.4.4
Using multipart-post 2.0.0
Using equalizer 0.0.10
Using htmlentities 4.3.4
Using inflection 1.0.0
Using icalendar 2.4.1
Using http-form_data 1.0.1
Using jwt 1.5.4
Using kgio 2.11.0
Using libv8 3.16.14.15
Using multi_xml 0.5.5
Using mysql2 0.4.4
Using naught 1.1.0
Using net-ldap 0.15.0
Using netrc 0.11.0
Using oauth 0.5.1
Using pg 0.18.4
Using puma 3.6.0
Using bundler 1.13.7
Using raindrops 0.17.0
Using ref 2.0.0
Using sass 3.4.22
Using tilt 2.0.5
Using scrub_rb 1.0.1
Using simple-rss 1.3.1
Using simple_oauth 0.3.1
Using slack-notifier 1.5.1
Using tzinfo 1.2.2
Using writeexcel 1.0.5
Using memoizable 0.4.2
Using nokogiri 1.6.8
Using mime-types 3.1
Using rack-test 0.6.3
Using autoprefixer-rails 6.4.1.1
Using uglifier 3.0.2
Using ffi-compiler 0.1.3
Using clearbit 0.2.5
Using coffee-script 2.4.1
Using sprockets 3.7.0
Using unf 0.1.4
Using email_verifier 0.1.0
Using em-websocket 0.5.1
Using omniauth 1.3.1
Using faraday 0.9.2
Using unicorn 5.2.0
Using therubyracer 0.12.2
Using biz 1.6.0
Using activesupport 4.2.7.1
Using mail 2.6.4
Using loofah 2.0.3
Using argon2 1.1.1
Using eco 1.0.0
Using domain_name 0.5.20160826
Using omniauth-oauth 1.1.0
Using koala 2.4.0
Using oauth2 1.2.0
Using zendesk_api 1.14.0
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.7
Using activemodel 4.2.7.1
Using delayed_job 4.1.2
Using rails-html-sanitizer 1.0.3
Using http-cookie 1.0.2
Using omniauth-twitter 1.2.1
Using omniauth-oauth2 1.4.0
Using rails-dom-testing 1.0.7
Using activerecord 4.2.7.1
Using activejob 4.2.7.1
Using rails-observers 0.1.2
Using http 1.0.4
Using rest-client 2.0.0
Using omniauth-facebook 4.0.0
Using omniauth-github 1.1.2
Using omniauth-gitlab 1.0.2
Using omniauth-linkedin-oauth2 0.1.5
Using omniauth-google-oauth2 0.4.1
Using activerecord-nulldb-adapter 0.3.6
Using delayed_job_active_record 4.1.1
Using actionview 4.2.7.1
Using twitter 5.16.0
Using telegramAPI 1.2.2
Using actionpack 4.2.7.1
Using actionmailer 4.2.7.1
Using railties 4.2.7.1
Using sprockets-rails 3.2.0
Using activerecord-session_store 1.0.0
Using coffee-rails 4.2.1
Using doorkeeper 4.2.0
Using rails 4.2.7.1
Using sass-rails 5.0.6
Bundle complete! 70 Gemfile dependencies, 120 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into ./vendor/bundle.
`
# schedular output
`./script/scheduler.rb start
/usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- daemons (LoadError)
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
	from ./script/scheduler.rb:6:in '<main>'`

# in bundle context
`bundle exec script/scheduler.rb start
scheduler: process with pid 16565 started.`

Now it says that the scheduler is started but telegram still doesn't send any messages.

**Comment by thorsteneckel** [comment]
Strange.... Can you please provide the logfile output when sending a message via Telegram?

Alternativly please try starting the scheduler via the docs command:
`sudo systemctl restart zammad-worker`

Taken from:
https://docs.zammad.org/en/latest/install-debian.html#you-can-manage-the-zammad-services-manually

Please provide the logfile of both cases. Thanks!

**Comment by chrisdecker1201** [comment]
# production.log
I, [2017-02-16T17:53:12.530717 #16813]  INFO -- : Setting.set(product_logo, "5d13534e1c3823315395096e84a2cb7a.png")
I, [2017-02-16T17:53:14.971764 #16813]  INFO -- : Scheduler running...
I, [2017-02-16T17:53:14.978430 #16813]  INFO -- : Started job thread for 'Check streams for Channel' (Channel.stream)...
I, [2017-02-16T17:53:14.990347 #16813]  INFO -- : execute Channel.stream (try_count 0)...
I, [2017-02-16T17:53:15.995598 #16813]  INFO -- : Started stream channel for '4' (Twitter::Account)...
I, [2017-02-16T17:53:22.971921 #16813]  INFO -- : Starting worker thread Delayed::Backend::ActiveRecord::Job
I, [2017-02-16T17:53:24.978431 #16813]  INFO -- : Started job thread for 'Generate Session data' (Sessions.jobs)...
I, [2017-02-16T17:53:24.985616 #16813]  INFO -- : execute Sessions.jobs (try_count 0)...
I, [2017-02-16T17:53:31.000384 #16813]  INFO -- : 2017-02-16T17:53:31+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=116) RUNNING
I, [2017-02-16T17:53:31.063175 #16813]  INFO -- : 2017-02-16T17:53:31+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=116) COMPLETED after 0.0625
I, [2017-02-16T17:53:31.068012 #16813]  INFO -- : 2017-02-16T17:53:31+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=117) RUNNING
I, [2017-02-16T17:53:31.079573 #16813]  INFO -- : 2017-02-16T17:53:31+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=117) COMPLETED after 0.0113
I, [2017-02-16T17:53:31.085153 #16813]  INFO -- : 2017-02-16T17:53:31+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Transaction::BackgroundJob (id=118) RUNNING
I, [2017-02-16T17:53:31.109633 #16813]  INFO -- : 2017-02-16T17:53:31+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Transaction::BackgroundJob (id=118) COMPLETED after 0.0242
I, [2017-02-16T17:53:31.115196 #16813]  INFO -- : 2017-02-16T17:53:31+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Transaction::BackgroundJob (id=119) RUNNING
I, [2017-02-16T17:53:31.216860 #16813]  INFO -- : Send notification to: christian.decker@decker-software-solutions.de (from Notification Master <noreply@zammad.decker-software-solutions.de>)
I, [2017-02-16T17:53:31.757934 #16813]  INFO -- : 2017-02-16T17:53:31+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Transaction::BackgroundJob (id=119) COMPLETED after 0.6425
I, [2017-02-16T17:53:47.772800 #16813]  INFO -- : 2017-02-16T17:53:47+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=120) RUNNING
I, [2017-02-16T17:53:47.818299 #16813]  INFO -- : 2017-02-16T17:53:47+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=120) COMPLETED after 0.0453
I, [2017-02-16T17:53:47.823331 #16813]  INFO -- : 2017-02-16T17:53:47+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Observer::Ticket::OnlineNotificationSeen::BackgroundJob (id=121) RUNNING
I, [2017-02-16T17:53:47.840467 #16813]  INFO -- : 2017-02-16T17:53:47+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Observer::Ticket::OnlineNotificationSeen::BackgroundJob (id=121) COMPLETED after 0.0169
I, [2017-02-16T17:53:47.845477 #16813]  INFO -- : 2017-02-16T17:53:47+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=122) RUNNING
I, [2017-02-16T17:53:47.857498 #16813]  INFO -- : 2017-02-16T17:53:47+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=122) COMPLETED after 0.0118
I, [2017-02-16T17:53:47.863183 #16813]  INFO -- : 2017-02-16T17:53:47+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Transaction::BackgroundJob (id=123) RUNNING
I, [2017-02-16T17:53:47.888188 #16813]  INFO -- : 2017-02-16T17:53:47+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Transaction::BackgroundJob (id=123) COMPLETED after 0.0247
I, [2017-02-16T17:53:47.893747 #16813]  INFO -- : 2017-02-16T17:53:47+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Transaction::BackgroundJob (id=124) RUNNING
I, [2017-02-16T17:53:47.915184 #16813]  INFO -- : 2017-02-16T17:53:47+0100: [Worker(host:v36581.1blu.de pid:16813)] Job Transaction::BackgroundJob (id=124) COMPLETED after 0.0212

# after restart
I, [2017-02-16T17:56:00.384523 #16898]  INFO -- : Started job thread for 'Check streams for Channel' (Channel.stream)...
I, [2017-02-16T17:56:00.391174 #16898]  INFO -- : execute Channel.stream (try_count 0)...
I, [2017-02-16T17:56:01.396074 #16898]  INFO -- : Started stream channel for '4' (Twitter::Account)...
I, [2017-02-16T17:56:04.406125 #16898]  INFO -- : 2017-02-16T17:56:04+0100: [Worker(host:v36581.1blu.de pid:16898)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=125) RUNNING
I, [2017-02-16T17:56:04.416465 #16898]  INFO -- : 2017-02-16T17:56:04+0100: [Worker(host:v36581.1blu.de pid:16898)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=125) COMPLETED after 0.0102
I, [2017-02-16T17:56:04.419892 #16898]  INFO -- : 2017-02-16T17:56:04+0100: [Worker(host:v36581.1blu.de pid:16898)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=126) RUNNING
I, [2017-02-16T17:56:04.426550 #16898]  INFO -- : 2017-02-16T17:56:04+0100: [Worker(host:v36581.1blu.de pid:16898)] Job Observer::Ticket::UserTicketCounter::BackgroundJob (id=126) COMPLETED after 0.0065
I, [2017-02-16T17:56:10.385794 #16898]  INFO -- : Started job thread for 'Generate Session data' (Sessions.jobs)...
I, [2017-02-16T17:56:10.393900 #16898]  INFO -- : execute Sessions.jobs (try_count 0)...
I, [2017-02-16T17:56:12.436464 #16898]  INFO -- : 2017-02-16T17:56:12+0100: [Worker(host:v36581.1blu.de pid:16898)] Job Transaction::BackgroundJob (id=127) RUNNING

# comment
Probably something is wrong or why there is Twitter and not Telegram mentioned.

**Comment by thorsteneckel** [comment]
Strange! 🤔 There should be an `Job Observer:...` entry for outgoing Telegram messages. Can you please check if the following lines are included in your `config/application.rb`:

<img width="724" alt="bildschirmfoto 2017-02-16 um 18 15 25" src="https://cloud.githubusercontent.com/assets/3873515/23032267/21f1ff46-f474-11e6-96c0-8e7e1ca3f1ba.png">

If so, could you please provide a screenshot of the expanded article you tried to send? To do so just click on the article which shows a header with some meta information etc. Please take a screenshot of the whole article and fill/remove the sensitive information with your image program.

**Comment by chrisdecker1201** [comment]
The line exists in my configuration.
I'm not quite sure what you mean with the screenshot but maybe that's it.

![bildschirmfoto vom 2017-02-16 um 18 24 04](https://cloud.githubusercontent.com/assets/20707614/23032609/4a9c94b4-f475-11e6-93d4-13dd6c8e9ced.png)

**Comment by thorsteneckel** [comment]
Ah there it is! The red border around your message indicates that's an internal article. Please use the "respond" (antworten) button under the message you want to respond to. Zammad will then change the article to external and will pre-select the article type to the matching channel you are responding to.

Regarding the expanded view: Just klick on the article text of your or the previous message and you will see what I meant. But thats just an info, no need anymore. Closing now.

**Comment by chrisdecker1201** [comment]
I'm so sorry. That was my mistake...

**Comment by thorsteneckel** [comment]
Nothing to be sorry about. To make this part of the UI more intuitive is on our list. Have fun with Zammad and thanks for the Star 🚀
