### ISSUE TITLE
Telegram: Unable to set webhook at Telegram, seems to be a invalid url. 

### ISSUE THREAD

**Issue by Johannes-GitHub** [zammad/zammad#778]
### Infos:
![grafik](https://cloud.githubusercontent.com/assets/24590878/23064650/8014ebea-f511-11e6-8b3a-c907834d096c.png)

* Used Zammad version: 1.3.0
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Firefox

### Actual behavior:

Try to add Telegram, getting the following error: 
"Unable to set webhook at Telegram, seems to be a invalid url."

Think it´s a little error by me. 

Can you please help? 

### Steps to reproduce the behavior:

Add Telegram with manual

**Comment by Johannes-GitHub** [comment]
API Token is filled like:

XXXXXXXXXX:XXXXXXXXXXXXX

**Comment by martini** [comment]
Hi @Johannes-GitHub 

Telegram sends messages via web hooks to Zammad. If you add a Telegram bot, the URL for your Zammad instance will get registered at Telegram.

-=> This error message says, you Zammad URL is invalid: Errors can be:
1) Your Zammad is not accessible from external
2) Your Zammad installation has no valid https config/certificat
3) Your port of your Zammad instance is not 443

Hope this points you in correct direction.

 -Martin

**Comment by Johannes-GitHub** [comment]
Hi @martini 
yes, actually we drive the standard installation of zammad. 

I will try to upgrade to https with the following manual: https://github.com/zammad/zammad/issues/680
I will send you an update.

**Comment by martini** [comment]
Thanks for feedback.
