### ISSUE TITLE
Simple triggers resulting in error condition

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#779]
### Infos:

* Used Zammad version: 1.3 (current zammad/zammad Docker container)

### Expected behavior:

* Trigger should fire

### Actual behavior:

* Trigger does not fire, but production.log shows:
```
ERROR -- : ERROR: Transaction::Trigger
ERROR -- : ERROR: #<NoMethodError: undefined method `[]' for nil:NilClass>

```

I believe this line of code in models/transaction/trigger.rb causes the trouble (as `@item[:changes]` is not defined):
`next if !@item[:changes][attribute]
`
### Steps to reproduce the behavior:

* Set up a simple trigger that does not include any "field updated" conditions, or article related conditions:

![grafik](https://cloud.githubusercontent.com/assets/4621219/23066129/42a8740e-f519-11e6-8448-a8f064c248ec.png)
* Update a ticket

The workaround here is to include any article related condition (see issue #395).

**Comment by martini** [comment]
Hi @olivergrahl,

thanks for wonderful informations in this issue! ❤️

Fixed. It's available in  master branch/packages (will get in stable ASAP).

 -Martin

**Comment by martini** [comment]
Available in stable branch/packages.
