### ISSUE TITLE
API call to open/show ticket in an agent's browser

### ISSUE THREAD

**Issue by Schack17** [zammad/zammad#780]
### Infos:
Use Case:
1. Incoming call create a new ticket over the api
2. Now the new ticket should be opened in an agent view to extend the ticket
Another way could be to create a new ticket via url.
e.g. http://myzammad/new?requesterid=1704
See talk/voice api from zendesk:
https://developer.zendesk.com/rest_api/docs/voice-api/talk_partner_edition#open-a-ticket-in-an-agents-browser

* Used Zammad version: 1.3.0
* Operating system: Ubuntu / Docker
* Browser + version: Firefox 53

### Expected behavior:
* see above

### Actual behavior:
* No api call.

**Comment by thorsteneckel** [comment]
Hi @Schack17 - have you seen our CTI integration?

**Comment by martini** [comment]
@Schack17 for me your use case description is not clear. 

1) You want to open a existing ticket in agents browser via an rest call?

2) You want to open a new ticket create with pre filled values via an rest call?

I'm right?

**Comment by Schack17** [comment]
Hi @thorsteneckel , can you give me an example or a link?
A search in the documentation lists 0 results: https://docs.zammad.org/en/latest/search.html?q=cti&check_keywords=yes&area=default#
A Google Site search in the documentation lists 0 results: https://www.google.com/search?q=cti+site:docs.zammad.org

**Comment by Schack17** [comment]
Hi @martini ,

> You want to open a new ticket create with pre filled values via an rest call?
this is my use case.

**Comment by martini** [comment]
> Hi @thorsteneckel , can you give me an example or a link?

https://zammad.com/news/release-4-week-period -> Feature #3: Integration with sipgate.io

JFI: This would work also with other PBX, Zammad just need to get all events pushed via REST calls (BPX -> Zammad).

**Comment by Schack17** [comment]
> https://zammad.com/news/release-4-week-period -> Feature #3: Integration with sipgate.io
@martini This is the link of the changelog. Where can I find the documentation for this?

**Comment by Newan** [comment]
Here are all events you can use for sipgate.io too: https://github.com/zammad/zammad/issues/2044

**Comment by MrGeneration** [comment]
Closing, I don't think that this is still relevant, if it still is, please let me know.
