### ISSUE TITLE
Broken overview for agent

### ISSUE THREAD

**Issue by skibson** [zammad/zammad#781]
When user is agent not customer. my_tickets overview shows no tickets. When I change user role to customer all tickets become visible

**Comment by hanneshal** [comment]
Hi, @skibson, thanks for your message. We need some more information on this. 
So, please use the provided template, when you create an issue. 
Especially the part: "How to reproduce". We need infos on your actual group / role setup and where are the tickets located. 

Thx. 

Johannes. 

P.S.
I Close this issue. Please reopen a fresh one using the template.
