### ISSUE TITLE
Job condition yields same ticket multiple times when article based condition is used

### ISSUE THREAD

**Issue by nidico** [zammad/zammad#785]
Adding scheduled job conditions normally yields tickets. However, adding a filter on an article property (e.g. "article - to") makes the query match articles instead, yielding the same tickets multiple times if multiple articles match.

(Feel free to ask for a proper example if the explanation is unclear)

### Infos:

* Used Zammad version: 1.3.0
* Operating system: Linux

**Comment by martini** [comment]
> (Feel free to ask for a proper example if the explanation is unclear)

An example would be fine! :)

**Comment by hanneshal** [comment]
closed due inactivity
