### ISSUE TITLE
Slack notification per group

### ISSUE THREAD

**Issue by tojaskiba** [zammad/zammad#796]
Hi. Slack integration is great but what's missing is per group integrations. We just started using zammad and we find it great. 
We're launching slack api compatible alternative mattermost and while using many groups operated by different people current zammad slack integration becomes useless because of lack of this feature

**Comment by rkaldung** [comment]
The current slack integration is just for notifications. I am right that you want to connect a Slack/Mattermost channel for reading and writing posts? Or only to user via direct message? It would be easier to describe your use case

**Comment by skibson** [comment]
My point is to map certain slack group/channel to certain zammad group for notification sending

**Comment by rkaldung** [comment]
@skibson One more question: I suggest you need to connect to different Mattermost instances?

**Comment by skibson** [comment]
No, we use zammad for departament-departament incident reporting.
our configuration in zammad is departament = group
We also plan to use mattermost for communication. There we would have
private channel = departament
Now zammad can only send only notifications to one channel what is useless when using more than group/private channel

**Comment by robwilc** [comment]
Being about to notify specific channels per Zammad group would be beneficial for us also.

**Comment by nitr8** [comment]
This would be really beneficial I would love to see this too :)

**Comment by edhardie** [comment]
+1 for this groups in Zammad -> groups in slack makes sense to me

**Comment by Braintelligence** [comment]
This is a more and more relevant feature for today's workflows. Would be awesome to see it integrated.

**Comment by z0n1q** [comment]
+1 for this feature, as my company uses different teams in mattermost with different groups in zammad.

**Comment by MrGeneration** [comment]
I'm limitting the conversation on this issue to contributors only to reduce the noise on this repository. 
Please don't get us wrong, this is to help us to keep focus on the issues we have. This issue hasn't had useful conversation / feedback in quite a long time. (except for +1's).

This is a feature backlog and thus might life here a longer time.
If anything moves regarding this issue, we'll update it accordingly!

**Comment by dominikklein** [comment]
With the next release, this should be possible to handle with the new way of using Slack notifications: https://github.com/zammad/zammad/issues/4484 + https://github.com/zammad/zammad/issues/4482
