### ISSUE TITLE
Indexing customfields in elasticsearch

### ISSUE THREAD

**Issue by darkness08** [zammad/zammad#797]
### Infos:

* Used Zammad version: 1.3.X
* Operating system: Debian Jessie

### Actual behavior:

* I've created a custom field for user (Objekt --> user)
Is there a way to index this field via Elasticsearch. After a index-rebuild I can still search the Fields like Name and Email

**Comment by martini** [comment]
Hi @darkness08 

we push all fields to elasticsearch. After reindexing you should find objects by new attributes automatically.

PS: It sounds that you still use the DB SQL search if you only find users by name and/or email. 

 -Martin

**Comment by martini** [comment]
Here you can see it, all attributes are used (only certain attributes like password or created_at are dropped for indexing) https://github.com/zammad/zammad/blob/develop/app/models/user/search_index.rb#L23

**Comment by darkness08** [comment]
Thx @martini 
how can i change the DB SQL search?
