### ISSUE TITLE
Postmasterfilter with 2 Conditions of the same kind?

### ISSUE THREAD

**Issue by foerstm** [zammad/zammad#798]
### Infos:

Is It possible to add more than one condition of the same kind to an e-mail filter?
In the Attachment a simplet example

![postmasterfilter](https://cloud.githubusercontent.com/assets/25791756/23201923/0f6b0d88-f8dc-11e6-9387-0833dd5fa3eb.PNG)

**Comment by martini** [comment]
@foerstm currently it's not possible. Currently you need to create 2 postmaster filter.

**Comment by martini** [comment]
One more question to clarifying. What is your use case?

E. g. You want to match all ticket from sender A and subject containing "ABC"? This would be possible.

**Comment by foerstm** [comment]
We wanted to filter Mails like our internal Groups. E. g. if Mail Comes from sender A and B and C filter to Group "Software". If the mail Comes from Sender D and E and F filter it to Group "Infrastructure".

**Comment by martinvonwittich** [comment]
This is most probably a duplicate of #2185

**Comment by thorsteneckel** [comment]
Thanks @martinvonwittich - you are right. Even this one is older than #2185 I prefer to keep #2185 as it is easier to find and already in the required format. Therefore I'll close this one as a duplicate.
