### ISSUE TITLE
email thread identification

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#799]
I wrote an email with header

    From: Ingo Wichmann <tickets@linuxhotel.de>
    Subject: Embedded Linux 20.03 - 23.03.17
    User-Agent: Mozilla ... Thunderbird
    Message-ID: <b1a84d36-4475-28e8-acde-5c18ebe94182@linuxhotel.de>

I got an answer with header

    To: Ingo Wichmann <tickets@linuxhotel.de>
    Subject: Re: Embedded Linux 20.03 - 23.03.17
    In-Reply-To: <b1a84d36-4475-28e8-acde-5c18ebe94182@linuxhotel.de>

Zammad did not add the answer to the ticket created with my first email, I had to merge it by hand:

https://linuxhotel.zammad.com/#ticket/zoom/1110
https://linuxhotel.zammad.com/#ticket/zoom/1119

**Comment by martini** [comment]
Hi @zabarabab 

to clarify the workflow how to reproduce is important, so pls let me know if I'm wrong:

System Settings:
* Additional follow-up detection (Admin -> Channels -> E-Mail -> Settings) - noting is checked -> Follow up detection is only done in subject

Steps:
1) You wrote an email with your favourite email client and added Zammad in Bcc and sender (your Zammad Instance)
2) A new ticket in Zammad got created, all fine so far.
3) Your client answered (to your Zammad Instance) and the follow up got not detected as follow up for your open ticket, a new ticket got created.

 -=> You expected to get the customers email as follow for the first ticket?

Note: In this case you need to global enable follow up detection via message ids (Admin -> Channels -> E-Mail -> Settings -> Additional follow-up detection -> References - Search for follow up also in In-Reply-To or References headers.)

Feedback is welcome!

 -Martin

**Comment by zabarabab** [comment]
Hi Martin,

I've added more headers to the original bug report above.

Steps:
1) I wrote an email with my favourite email client and put Zammad in From (your Zammad Instance)
2) I moved my copy of the email to the Zammad-IMAP Folder, for Zammad to pull it in
3) A new ticket in Zammad got created, all fine so far.
4) Your client answered (to your Zammad Instance) and the follow up got not detected as follow up for your open ticket, a new ticket got created.

 -=> You expected to get the customers email as follow for the first ticket?

Yes. 

From the subject the answer should have been recognized as belonging to the ticket.

Now, I've additionally activated extended follow up detection using references.


I'm surprised how well Follow-Up detection worked without reference headers ... it usually works ;-)

**Comment by martini** [comment]
> I'm surprised how well Follow-Up detection worked without reference headers ... it usually works ;-)

Thanks for excellent details on feedback. ❤️

So you vote to enable **follow up detention on reference headers per default** or **use follow up detection if the subjects seems to be the same**?

**Comment by martini** [comment]
> I'm surprised how well Follow-Up detection worked without reference headers ... it usually works ;-)

One more note. We already use references header based follow up detection (also if reference header follow up detection is not permanently enabled). I guess this is the reason why it has worked usually.

https://github.com/zammad/zammad/blob/develop/app/models/channel/filter/follow_up_check.rb#L68

-> I'll create a test based on your header information to verify why follow up detection was not working....

**Comment by zabarabab** [comment]
> So you vote to enable follow up detention on reference headers per default or use follow up detection if the subjects seems to be the same?

I've enabled reference headers to see if it further improves the situation for us. I'll report if I discover disadvantages.

**Comment by martini** [comment]
Strange new feedback. I created an unit test with your provided headers. And follow up detection is working just find (without permanent enabled references header check). 🤔

https://github.com/zammad/zammad/commit/8d4fd8b61456e63b2fa572bb0493078e5d45c3a7

**Comment by zabarabab** [comment]
What, if I made a mistake. What if I moved the original mail into Zammad after the response?

Looking at the involved ticket ids: sorry, my fault. 

Lessen learned: create a ticket from your mails before your customer does it, or you have to merge the ticket by hand.
