### ISSUE TITLE
Send notification email containing note-text

### ISSUE THREAD

**Issue by robwilc** [zammad/zammad#800]
### Infos:

* Used Zammad version: 1.3
* Operating system: Ubuntu 16.04
* Browser + version:  Safari 10.1

### Question

* I would really like to know if I can configure a notification to be sent out when a note is added by one of our operators to a ticket. I have configured such a notification, but, the question I have is whether I can include the text of the note, rather than just a 'your ticket has been updated'-type of notification

**Comment by martini** [comment]
Hi @robwilc 

can you try to use:

`#{article.body}`

Is this what you are looking for?

 -Martin

**Comment by robwilc** [comment]
Hi @martini 

Yep, that almost gets us 100% of the way there...  is there anyway to also send attachments?

Thanks
Rob

**Comment by thorsteneckel** [comment]
This has been registered as an issue over at #2485 - so I'll close this one as duplicate (even as it's older). Please refer to the [community board](http://community.zammad.org/) for further questions.
