### ISSUE TITLE
Unable to create a new customer ticket with Internet Explorer 11

### ISSUE THREAD

**Issue by robwilc** [zammad/zammad#801]
### Infos:

* Used Zammad version: 1.3
* Operating system:  Ubuntu 16.04
* Browser + version: Internet Explorer 11

### Expected behavior:

* Customer should be able to use the UI to create a ticket

### Actual behavior:

* The 'Create' button doesn't work. Multiple clicks on it, don't help. Rest of ticket information is filled in, but Create simply doesn't work

### Steps to reproduce the behavior:

* Install Zammad 1.3
* Create a new customer
* Login as the customer
* Try to create a new ticket

**Comment by martini** [comment]
Hi @robwilc 

I tried it wit IE 10 and IE 11 right now and it's just working fine. :-o

Is there any error in the browser console log?

 -Martin

<img width="301" alt="screen shot 2017-02-24 at 16 11 12" src="https://cloud.githubusercontent.com/assets/110226/23308628/0eb82be2-faac-11e6-9071-0217c288dae6.png">
<img width="304" alt="screen shot 2017-02-24 at 16 07 20" src="https://cloud.githubusercontent.com/assets/110226/23308627/0eb74b8c-faac-11e6-9c3b-3c3c26de0f74.png">

**Comment by robwilc** [comment]
Hi @martini 

Indeed there is, in both Edge and IE 11 (that's all I have on this machine).  It's the same error in the console on both:

![console-error](https://cloud.githubusercontent.com/assets/1247413/23338640/40b982aa-fc08-11e6-9fd7-096094b170e0.PNG)


My user which I am logged in as is 'just' a customer, no Zammad roles.

Thanks
Rob

**Comment by martini** [comment]
Hi @robwilc 

I still can not reproduce it. Is the issue still open on your side?

 -Martin

**Comment by thorsteneckel** [comment]
No feedback. Closing.
