### ISSUE TITLE
Would be nice to see extra fields on Organization as Agent

### ISSUE THREAD

**Issue by robwilc** [zammad/zammad#802]
### Infos:

* Used Zammad version: 1.3 
* Operating system:  Ubuntu 16.04
* Browser + version: Chome/Safari

### Suggested enhancement:

* I have added an extra field to an organization, eg TimeZone. It would be nice to see this on the info page about the organization without going into Settings -> Organization.

eg visible on this page: #organization/profile/2

**Comment by martini** [comment]
@robwilc can you add an screenshot where you would like to see it?

**Comment by robwilc** [comment]
Hi Martini

Sure...

This is where you see the timezone field (which we added). It's the organization management page:

![org-got](https://cloud.githubusercontent.com/assets/1247413/23338557/243b1816-fc06-11e6-8d03-4976da066e01.PNG)


This is where I'd like to see it:

![org-like](https://cloud.githubusercontent.com/assets/1247413/23338551/0ad06200-fc06-11e6-85c3-9aa399b8a45d.PNG)


Does that help?

Thanks
Rob

**Comment by martini** [comment]
Hi @robwilc 

> This is where I'd like to see it:

I just tried to reproduce it. And it works fine. Hint: The field is only show in organization profile if the field has content.

Just reopen if it's not working.

<img width="725" alt="screen shot 2017-04-29 at 02 00 30" src="https://cloud.githubusercontent.com/assets/110226/25551064/bd30d322-2c7f-11e7-9f77-0b2401ce864e.png">
<img width="726" alt="screen shot 2017-04-29 at 01 58 43" src="https://cloud.githubusercontent.com/assets/110226/25551063/bd2fac5e-2c7f-11e7-8637-7acc6bfda64b.png">
