### ISSUE TITLE
API call for /tickets/search?query=state_id=open or new gives back less then expected

### ISSUE THREAD

**Issue by d11thRid3r** [zammad/zammad#803]
### Infos:

* Used Zammad version: 1.3.x
* Operating system: ubuntu (server side and local)
* api call via curl or python

### Expected behavior: 

We use zammad on production with more than 1500 tickets, over 500 are open or new.

* when I call the api with` /tickets/search?query=state_id=open` I want all open tickets
* same for:  `/api/v1/tickets`  -> result should be all tickets

### Actual behavior:

* I always get only 12 tickets back for search?query=state_id=open (or new)
* when I call for all tickets (.../tickets ) I only get back 100 

### Steps to reproduce the behavior:

`curl -u me@mylogin.com:sectretpasswd https://zammad.myserver.com/api/v1/tickets/search?query=state_id=open`

or 

`
curl -u me@mylogin.com:sectretpasswd https://zammad.myserver.com/api/v1/tickets`

**Comment by d11thRid3r** [comment]
our workaround:
```
for id in ticket_ids do:
  curl -u me@mylogin.com:sectretpasswd https://zammad.myserver.com/api/v1/tickets/id 
```
and then we filter for open tickets...

**Comment by d11thRid3r** [comment]
I forgot to mention that I am admin & assigned to all groups...
& also could not find any limitation in here:

https://github.com/zammad/zammad/blob/cd28e904ac122b410f7c28e8284bb0c22411e342/app/controllers/tickets_controller.rb

**Comment by martini** [comment]
Hi @d11thRid3r 

how about:

`curl -u me@mylogin.com:sectretpasswd https://zammad.myserver.com/api/v1/tickets/search?query=state%3Aopen`

-> The query style is "attribute:value", here "state:open"

Or even better, also show new ticket: "state:open OR state:new"

`curl -u me@mylogin.com:sectretpasswd https://zammad.myserver.com/api/v1/tickets/search?query=state%3Aopen%20OR%20state%3Anew`

Note: For this kind of search you need to have a enabled elasticsearch with you Zammad.

For more of this pretty cool search syntax stuff see here: https://docs.zammad.org/en/latest/general-search.html

 -Martin

**Comment by d11thRid3r** [comment]
Thanks a lot for making this clear, and sorry for not thinking about this, this is such a cool tool, and you guys doing an awsome job! But maybe for Idiots like me, a word in the documentation could help to avoid getting ask again :-)
