### ISSUE TITLE
Implement inbound SMTP listener for E-Mail

### ISSUE THREAD

**Issue by siepkes** [zammad/zammad#806]
I was thinking that it would be really nice if Zammad could behave as an SMTP server (MTA) with the help of for example the [Ruby mini smtp server](https://github.com/aarongough/mini-smtp-server). The benfit would be that one can configure his main MTA (postfix, sendmail, etc.) to just relay mail to Zammad. Zammad could then function as the endpoint for the email.

This has advantages over using an IMAP server in between:
*  Less moving parts, simple delivery directly to Zammad. No need to maintain IMAP boxes which are only used as an intermediary.
* MTA can better respond to Zammad downtime. For example bounce message after 2 days with an undelivered message if it can't be relayed to Zammad when Zammad is down. If the mail is sitting in an IMAP spool for a couple of days the MTA will have already communicated to the sending MTA that delivery was successful while in fact it was not.

I was thinking that in the "Email Inbound" selection box the option SMTP could be selected and a port could be provided on which Zammad would then start listening. 

What do you guys think of such an idea? (I might be interested in implementing this feature so I would like some feedback).

**Comment by martini** [comment]
Hi @siepkes 

from the technical point of view it's really nice. I really like it. On the other hand, I see some missing features in Ruby mini smtp server like ssl or spam protections and many other config options which postfix, sendmail, .. has.

So another idea comes into my mind. How about an public service to create customisable Zammad appliances.

Let's say:
o Webserver
 o Apache|Nginx
 o ssl

o Database
 o PostgreSQL|MySQL

o MTA
 o Sendmail|Postfix|Exim
 o accept direct SMTP connections
  o certain spam options

o Network
 o IP
 o Firewall Rules
 o ssh keys

o Elasticsearch

And so on, after 10 min. you will get an download link with your Zammad appliance.

Feedback is welcome!

 -Martin

**Comment by siepkes** [comment]
Hi @martini ! Thanks for you quick reply!

> like ssl or spam protections and many other config options which postfix, sendmail

I don't think the SMTP server which Zammad would offer should be intended to ever be exposed directly to the Internet. It would always require a "real" MTA in front of it (like Postfix, Sendmail, etc.) which can also send bounce messages, handle queuing for a massive number of messages, etc. The SMTP interface I propose is intended to make it easy to get mail from such a frontend MTA in to Zammad. Organisations usually run a bunch of frontend MTA's which do all the heavy lifting like SSL/TLS, spam filtering and such and I think it would be really nice if you could just pass a single configuration option in such an MTA to relay mail directly in to Zammad. It's a bit like running NGINX in front of rails.

Currently I'm experimenting with Postfix and using a custom transport in to Zammad which kinda emulates the above described behavior (untested yet):

```
# Used to deliver mail in to Zammad.     
zammad    unix  -       n       n       -       4       pipe
  flags=BX user=zammad argv=rails {runner -e production 'Channel::Driver::MailStdin.new(trusted: true)'}
```

> So another idea comes into my mind. How about an public service to create customisable Zammad appliances.

Really cool idea! I think that would help a lot of people to adopt Zammad! However the solution I propose is more about adding an extra scenario / solution to possible integration scenario's. In order to provide the `accept direct SMTP connection` option in the "Appliance generator" I would still add Postfix in the VM image in front of the Zammad SMTP acceptor.

**Comment by siepkes** [comment]
Did some digging and the Gem https://github.com/4commerce-technologies-AG/midi-smtp-server seems to be more mature then the mini-smtp server.

**Comment by martini** [comment]
Hi @siepkes I would close this issue for now. Ok for you?

**Comment by siepkes** [comment]
@martini Well actually we are still interested in implementing it :-)

**Comment by siepkes** [comment]
@martini We (@ServicePlanet) will develop this in the comming weeks. My collegue @MaartenR will be working on this. We also want to contribute this functionality to Zammad.

Our idea is to add an SMTP interface to Zammad (which makes Zammad listen on for example port 2525) and add an option the the "Inbound mail" dialog called "SMTP". This would allow a frontend MTA (like Postfix) to relay mail directly in to Zammad. The frontend MTA can do all fancy stuff like spam filtering and such. For enterprises running their own frontend MTA (like for example exchange) this would considerably ease integration. Would you be open to such a contribution?

**Comment by mraerino** [comment]
Please see https://github.com/zammad/zammad/issues/1128 for a solution that doesn't touch the Zammad codebase and works out-of-the-box if you are using docker.

**Comment by MaartenR** [comment]
@mraerino Thanks for the suggestion, but we still prefer a solution that is integrated into Zammad. The less need there is to glue things together, the better :)

**Comment by siepkes** [comment]
@mraerino I would also like to add that Zammad supporting SMTP seems quite natural to me. SMTP is the most widely used protocol for transferring mail between systems. While the built-in way of scraping an IMAP box is easy to integrate for a lot of people (so I can see the appeal) it is actually a far less natural way IMHO.

**Comment by monotek** [comment]
I don't like the idea to extend Zammad for this.
 You already can pipe mails from your MTA to "rails r 'Channel::Driver::MailStdin.new(trusted: true)'".

**Comment by siepkes** [comment]
@monotek It's you decision in the end. However I do not understand the reasoning why IMAP as a protocol would be supported in Zammad and SMTP not. 

I could say the same for the IMAP scrape functionality currently embedded in Zammad. The solution @mraerino uses in #1128 is a Python script. One could easily do the IMAP scraping in a Python script with cron and pipe it in to Zammad. So a fair question would then be; Why is IMAP scrping embedded in Zammad? From a software architectural perspective I would say that such things are either in scope or out of scope for Zammad.

The IMAP scrape solution is from a technical standpoint (and again, I understand why people use it and why it's there) a duct-tape solution utilizing a standard (IMAP) not intended for those purposes. The mail gets delivered in to a end destination (a mailbox, which actually isn't the end destination) by the MTA and then the MTA will tell the sender: "We have received and processed your mail correctly" however Zammad hasn't even received that mail yet. So if there is a problem in Zammad the sender will never know. Even worse, the sender got an confirmation from the MTA it was correctly delivered. There might actually be some legal trouble there if a mail gets lost and the sender produces logs telling your MTA said it was correctly delivered. Therefor I think delivering from an MTA via SMTP directly to the endpoint, Zammad, is far more elegant.

Using SMTP as we proposed means Zammad would support a protocol which was actually designed to do what we are trying to achieve (getting mail from the MTA into Zammad) out of the box.

**Comment by monotek** [comment]
I don't see why we should touch Zammad code as long as their is already a solution via a real MTA and pipeping...

**Comment by siepkes** [comment]
@monotek Because when you use the `Channel::Driver::MailStdin` function you have to start the entire Ruby VM for every mail you are delivering in to Zammad. Which means delivering a single mail will take somewhere between 1 and 5 seconds. That's just not going to scale if you have at least some mail volume.

**Comment by siepkes** [comment]
FYI: Our Zammad install stopped processing E-Mail because the IMAP box went over quota. Apparently Zammad doesn't process emails larger then 10MB and leaves those untouched in the IMAP box. Senders don't get informed about those mails sitting forever in the IMAP box. And after some time after enough mails have pilled up in the IMAP box the whole thing goes over quota. These were the kind of things I tried to prevent with this issue and PR.

**Comment by passboltUser** [comment]
Out Tickets subfolder only has one new text email and is nowhere near 10MB, but import is still not working: https://github.com/zammad/zammad/issues/1593

**Comment by siepkes** [comment]
In the end to mitigate this we endup deploying an internal fork of Zammad which adds an operation (with separate permission) to the REST interface which allows for plain / bulk mail insertion. Our frontend MTA (Postfix) is configured to deliver mail directly to this REST interface (with the help of `curl` to make a REST call). 

Delivery is now realtime in Zammad and when delivery fails for whatever reason the user gets a proper "mail could not be delivered" message. Also we don't have the overhead of starting and stopping the entire Ruby VM (and the entire Rails framework with it) for a single mail delivery when using the pipe script. And we also don't have to monitor an IMAP box and our Zammad installation is also not dependent any more on the uptime of our Dovecot install.

Closing this issue since it has been made clear there is no interest in embedding functionality besides IMAP and the Ruby pipe script in Zammad.
