### ISSUE TITLE
Stiked out text displayed as normal text

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#807]
Hello,

### Infos:

* Used Zammad version: 1.3.x
* Operating system: Ubuntu 16.04.2 LTS
* Browser + version: Firefox

### Behavior:
A customer sent us a email with some striked out text, but it is displayed as normal text.

![zammadstrikeout](https://cloud.githubusercontent.com/assets/9305993/23355836/da51d9f6-fcd7-11e6-9214-6790c9b54944.PNG)
Left part is Zammad and it displays the striked out text as normal text. The right part shows the originally sent email by Outlook 2010.

The customer wants to mark, which points of error list are already solved or no longer important.

### Steps to reproduce the behavior:
I can reproduce it by sending a HTML email with Outlook 2010 to Zammad and write any striked out text.

Greetings
tobibe

**Comment by martini** [comment]
@tobibe thanks for information. Pls can you attach the example email to this issue (click on article body, in the footer of the article you can download it)?

Thanks!

**Comment by tobibe** [comment]
@martini 

Here is the attached html file
[message.html.txt](https://github.com/zammad/zammad/files/803202/message.html.txt)

Greetings
tobibe

**Comment by martini** [comment]
Thanks!

**Comment by tobibe** [comment]
@martini 

a collegue of mine tells me, that colored text is not displayed, too.
Sometimes, they answer questions inline in another color.

I attached a sample html file 
[message.html.txt](https://github.com/zammad/zammad/files/803312/message.html.txt)

**Comment by martini** [comment]
@tobibe currently we remove any css style information from incoming emails, we just allow certain tags like b,i,u,... I'll discuss this to allow also certain css styles ("color:red" would be ok, but "color:#3144CF" will get tricky).

And your college will soon ask your for inline images of incoming emails, we are prepared...  #343 😜

**Comment by tobibe** [comment]
@martini He already asked for the images, but I saw the issue 😜

**Comment by martini** [comment]
Stiked out text will be shown in upcoming Zammad 1.4. We did some tests with text color. But for now we do not show it (it looks so bad).
