### ISSUE TITLE
Allow for 'none' for 'Email Inbound'

### ISSUE THREAD

**Issue by siepkes** [zammad/zammad#810]
When using fetch / proc mail together with the `MailStdin` class in some cases there might not be an actual IMAP or POP3 box. Also when implementing functionality like #806 there might also be no IMAP / POP3 box. In those cases you only want to create an E-Mail account but not associate it with POP or IMAP.

**Comment by thorsteneckel** [comment]
This got implemented in the meantime to fix #224 with the commit above. Closing therefore.
