### ISSUE TITLE
Format signature

### ISSUE THREAD

**Issue by adonno** [zammad/zammad#815]
### Infos:

* Used Zammad version: 1.3.x
* Operating system: 
* Browser + version: 

### Expected behavior:

Some companies have Graphic charts to respect for their signature unfortunately it is impossible to change teh colour add an image or format the text of a signature

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by martini** [comment]
Thanks for reporting this issue. With Zammad 1.3 you can add images and text format to signatures.

Admin area:
<img width="735" alt="screen shot 2017-03-14 at 13 59 11" src="https://cloud.githubusercontent.com/assets/110226/23901681/a0bd2202-08be-11e7-8435-166fb2c3a208.png">


Reply to customer:
<img width="683" alt="screen shot 2017-03-14 at 13 59 48" src="https://cloud.githubusercontent.com/assets/110226/23901719/c043f36c-08be-11e7-8dd4-fa75e4c06aa9.png">

**Note: You can use "ctrl+alt+h" to see the shortcuts for text formatting. For Images just past them from you clipboard into the place where you want to have.**

So I'm closing this issue. Feel free to reopen if you don't feel so.

**Comment by adonno** [comment]
is there also a possibility to add colours ?  

![image](https://cloud.githubusercontent.com/assets/13216947/24037817/4d472ac6-0aff-11e7-81ac-9b7b73746ae3.png)

**Comment by spreddie** [comment]
Hi! Is there any progress on this? I'd also need the ability to customize company signature including logo, colours, and links
