### ISSUE TITLE
display whole ticket in email

### ISSUE THREAD

**Issue by kernbrand** [zammad/zammad#816]
hi,

is there a way to display the whole ticket thread in an email (similar to #{article.body}, but including all [public] notes)?

regards
lorenz

**Comment by martini** [comment]
Currently not. What is your use case/problem? What are you trying to solve?

**Comment by kernbrand** [comment]
my problem: customers :)

we've some customers who are using only their mobile phones to communicate.  zammad on mobile phones is not really nice to use, so they would like to get the whole ticket in an email.

**Comment by inrobin** [comment]
Yes. It would be good to have full ticket thread in email (both for customers and agents) similar to HelpScout.

**Comment by dsukhin** [comment]
Does this solve this issue? https://github.com/zammad/zammad/issues/571
It enables the option to quote the whole thread when replying.

**Comment by NeverMin** [comment]
@dsukhin please follow [here](https://community.zammad.org/t/how-to-setting-full-quote-original-e-mail-content/615) to setting.

**Comment by thorsteneckel** [comment]
Thanks for posting the link here @NeverMin . I'll close this as resolved for now. If you disagree please refer to the [community board](http://community.zammad.org/) and we're happy to hear your thoughts. Closing this one now.

**Comment by JsBergbau** [comment]
For those who find via Google here, https://community.zammad.org/t/how-to-setting-full-quote-original-e-mail-content/615 is the Community Link how to edit setting
