### ISSUE TITLE
Unable to save changes on Channels -> Form

### ISSUE THREAD

**Issue by robwilc** [zammad/zammad#817]
### Infos:

* Used Zammad version: 1.3
* Operating system:  Ubuntu 16.04
* Browser + version: Chrome / Safari

### Expected behavior:

* After enabling the 'channel' called 'form' I expect to be able to customise the title, and button name

### Actual behavior:

* Changes can be typed in, but there is no 'save' button. Switching to a different page in the UI and back again looses your changes

### Steps to reproduce the behavior:

* Go to Channels -> Form, and change the form title, or button label. It's not possible to 'save' those changes.

**Comment by martini** [comment]
Hi @robwilc 

the idea is to customise your form and use the java script snipped below for c&p to your web page.

So if you change something, the java script snipped is updated right now.

So there is no need of a save button, the ui is just a helper to generate the correct java script snippet.

Feedback is welcome,

 -Martin

<img width="752" alt="screen shot 2017-03-14 at 17 34 50" src="https://cloud.githubusercontent.com/assets/110226/23911340/d0573f84-08dc-11e7-84b5-56715d030af6.png">
