### ISSUE TITLE
Using pagination returns more results than expected

### ISSUE THREAD

**Issue by KirkBushman** [zammad/zammad#818]
### Infos:

* Used Zammad version: 1.3.x
* Operating system: Centos 7
* Browser + version: Chrome 56.0.2924.87

Hi I'm trying to paginate the results in order to view them on a RecyclerView on Android.
I have tried both 
GET /api/v1/users?expand=true&page=1,per_page=5 
and 
https://www.elastic.co/guide/en/elasticsearch/reference/5.1/search-request-from-size.html 
on tickets and users but I get all the results anyway.

curl -u user:password http://my_zammad/api/v1/users?from%3A0%2csize%3A5 (from:0,size:5)
curl -u user:password http://my_zammad/api/v1/users?expand=true&page=1,per_page=5

I've tried a bunch of combination of the urls but I cant get it to work, what am I getting wrong? 
Thanks in advance.

**Comment by KirkBushman** [comment]
We noticed that if we dont put the headers Accept: application/json and  Content-Type: application/json
pagination doesn't work.
We were using the curl command to test request and response.

**Comment by hiaz** [comment]
Had the same issue and had a look into the php api. I think

GET /api/v1/users?expand=true&page=1&per_page=5

is right (the & instead of the ,). The docu seems to be wrong.
