### ISSUE TITLE
Create Ticket and send E-Mail

### ISSUE THREAD

**Issue by xio1982** [zammad/zammad#819]
Is it possible to create a Ticket and send it as E-Mail by the JSON API?

**Comment by martini** [comment]
Sure!

See: https://docs.zammad.org/en/latest/api-ticket.html#create, just define the "type" and the "to" in article element.

The payload look like:

```
 {
  "title": "Help me!",
  "group": "Users",
  "article": {
    "subject": "some subject",
    "body": "some message",
    "to": "recipient@customer.com",
    "type": "email",
    "internal": false
  }
 }
```

**Comment by martini** [comment]
If you have any questions. Just let me know.
