### ISSUE TITLE
Send Mail on Ticket Creation

### ISSUE THREAD

**Issue by khlavkalash** [zammad/zammad#820]
Hi all,

just a little question: Which actions should create mails?

Outgoing Mails are funktional when sending mails manually from the ticket. But is there an auto-creation for incoming mails, adding a comment or closing the ticket?

best regards
Sascha

**Comment by jannheider** [comment]
Please check Settings -> Mange -> Tigger

Is that what you are looking for ?

**Comment by khlavkalash** [comment]
Yes thank you very much!
