### ISSUE TITLE
Ticket global CC/Follow option

### ISSUE THREAD

**Issue by ovidiustanila** [zammad/zammad#822]
Hello,

We started testing Zammad on https://test-help.zammad.com and looks pretty good for what we require. The only thing we noticed (maybe it's available but didn't see where) is that we can't add multiple email addresses/followers to a ticket so that on each reply made by an agent or customer, those addresses also receive an email notification, keeping them updated with the progress of the ticket over time.

Is this possible or planned for any future release ?

Thank you,
Ovidiu

**Comment by martini** [comment]
Hi @ovidiustanila 

are you looking for @username feature (see https://github.com/zammad/zammad/issues/208 - only the second pard is in english)? It's not implemented right now.

If you are looking for that, this is a duplicate issue. :)

 -Martin

**Comment by ovidiustanila** [comment]
Hello Martin,

Yes, I was thinking of something similar, but with the option to manually add subscribers to the ticket notification list.
Looking forward for this to get implemented.

Cheers,
Ovidiu

**Comment by RobiiRob** [comment]
Hey Guys,

i would love it if the is a possibility to add more followers like all customer who are set in CC of an artikel get some notifications. I tried it to create an overview to show all tickets where the user is in CC with #{user.lastname} but this doesn't work. 

![ubersichtcc](https://cloud.githubusercontent.com/assets/25764594/23859642/950c0e60-0804-11e7-9f5a-79d0c4a0f6af.PNG)

Any ideas? Any plannings to add this kind of feature? 

RobiiRob 
(i really like your system, works very fine and stable) :)

**Comment by RionoirCom** [comment]
+1

**Comment by MartinBorg** [comment]
**+1**

Note, that other ticket trackers have this feature:
 - Trac has a `Cc` field per ticket
 - Debian BTS has ticket subscription by sending email to `<bugnumber>-subscribe@bugs.debian.org`
 - Odoo (f.k.a. OpenERP f.k.a. TinyERP) has project issue _followers_

It certainly would suit Zammad as well.

**Comment by backbord** [comment]
+1

**Comment by sheLbyPL** [comment]
Any news on this? This would be really useful!
It would be great if such feature would be implemented in 2.4.0

**Comment by thorsteneckel** [comment]
Dear @sheLbyPL,

first of all, many thanks for your participation on the Zammad open source project.

Not usual as with proprietary software, we finance Zammad through service. So it's less money we have at our disposal to push Zammad.

If you would like to support Zammad, you can do so via Zammad Support: https://zammad.com/pricing#selfhosted

For all issues it is generally important that we tag an issue as soon as it is included in a release. This means that manual enquiry only minimizes the available resources but not the speed of implementation.

Thank you for your understanding.

**Comment by MrGeneration** [comment]
As far as I can see this is a duplicate from #208 and technical questions.
Many parts (like CC-function) are already built in Zammad.

For the sake of overview, I'll be closing this now.
