### ISSUE TITLE
Overview of template tags

### ISSUE THREAD

**Issue by abaumg** [zammad/zammad#823]
I'd like to see an overview of all available email template tags (e.g. `#{ticket.owner.lastname}`) in the documentation. Precisely I'd like to include the ticket status in a notification email to the customer.

**Comment by martini** [comment]
Hi @abaumg 

are you looking for that?

<img width="740" alt="screen shot 2016-12-05 at 09 28 19" src="https://cloud.githubusercontent.com/assets/110226/23556407/d6433bfe-002c-11e7-8e01-f4660bb11901.png">

Just use "::what_you_search_for"

 -Martin

**Comment by abaumg** [comment]
Yes, that's exactly what I was looking for. Maybe it could added to the documentation and/or as inline help text. 
Thank you!

**Comment by martini** [comment]
Thanks for feedback! ❤️
