### ISSUE TITLE
Unable to install zammad on plesk docker

### ISSUE THREAD

**Issue by omexXx** [zammad/zammad#824]
Hi,

As described on the documents i have changed the max value.

First try to install the offical package on plesk with these error:
`Running zammad/zammad-docker-compose
{"message":"manifest for zammad/zammad-docker-compose:latest not found"}`

After that i install 'zammad/zammad' container without problem.

Now the plesk docker log shows me that:
`sysctl: setting key "vm.max_map_count": Read-only file system`

But the settings are correct on host (reboot made):
`sysctl vm.max_map_count
vm.max_map_count = 262144`

I am not able to connect to zammad and the port mapping is '3001' and there i only see nginx defaultpage.

Something is very wrong here.

PS. Using Debian Jessie + Plesk Onyx (all actual versions)

Thanks

**Comment by monotek** [comment]
Its enough to open the issue once:

https://github.com/zammad/zammad-docker-compose/issues/8

**Comment by omexXx** [comment]
Well... better than to close the other issue and let this open... here are some more infos.

**Comment by monotek** [comment]
Still wrong github project.

**Comment by omexXx** [comment]
NO!! because i have installed this on plesk, the other don't even start the download... please read carefully.

**Comment by monotek** [comment]
Its about  zammad/zammad-docker-compose. 
Issues for the docker-compose version of zammad are managed in https://github.com/zammad/zammad-docker-compose
