### ISSUE TITLE
multiplication of the attachment-field in #channels/form

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#833]
#channels/form

- after putting a check at the field  "Add attachment option to upload." and removing it afterwards, you still see the "ATTACHMENTS"-field at the preview
-  it adds another "ATTACHMENTS"-field in the preview after every time you select the "Add attachment option to upload."-button

Browser: Chrome 56.0.2924.87
Hosted Version

**Comment by martini** [comment]
Fixed in develop, master and stable.
