### ISSUE TITLE
Add functionality to automatically send a survey at the end of a ticket

### ISSUE THREAD

**Issue by robwilc** [zammad/zammad#834]
### Infos:

* Used Zammad version: 1.3
* Operating system:  NA
* Browser + version: NA

### Suggested enhancement

* In our existing ticketing system we automatically send a simple survey to the person who created a ticket, when we close the ticket. We get some very good feedback from it. I suggest adding something like that to Zammad in the future.

### Details

I would suggest making it turn on, and off-able at the group level.

* a/ Asks a simple question:

Maybe this can be configurable as well? Example question:

How satisfied are you with the <GroupName> team

* b/ 0 to 5 stars, a rating of the handling of the ticket

* c/ A simple comment box – multiline. 

* d/  A send button

* e/ When you hit send it should:

                1/ Record the results in a new SQL table. TicketID, date-time, score, and comments.

                2/ Send an email notification (*1) 

* f/ The survey should be sent out ‘soon after’ a ticket is closed

-          Maybe we can use the Zammad scheduler type situation or something? Or a trigger? [As that can send an email]

 

* g/ The survey request should be an email.

-          The email needs to include a unique URL to the survey.. so that we don’t have to get the person to login, nor provide any ticket details. If possible!

* h/ The customer shouldn’t have to login to submit the survey, if possible

* i/ Once submitted, it shouldn’t be possible to submit again

-          When displaying the survey page we can check if the ticketID already exists in the Survey table and if yes, display a nice message

* j/ We should be able to turn on / off this functionality

-          Maybe it’s a trigger

-          Maybe it’s a new option under settings?

**Comment by gwingend** [comment]
+1

**Comment by sfakir** [comment]
+1

**Comment by alionar** [comment]
+1

**Comment by thorsteneckel** [comment]
Hey everybody 👋  It's been some time. In the meantime we received a lot of feedback and requests regarding (automatic) surveys. Having and sending Surveys is a great feedback channel for improvement. However, the individual needs and requirements for Surveys vary a lot and we've come to the believe that there is not the one solution we could or should implement in Zammad. Our focus and strength is ticketing and providing the best solution.

Therefore we've decided to and already implemented a LimeSurvey (Open Source ✊ ) integration as an add on for one of our beloved customers. It basically allows to send a URL to a survey to the customer via a Trigger. As stated previously its tailored the to the requirements and needs of this customer in its current form. Please get in touch with sales at zammad.com if you're interested in an integration of your tool of choice or want an adapted version of the existing LimeSurvey add on.

There are no further plans on this in the Core. Therefore I close this issue. If you disagree please create a thread over at the [community board](http://community.zammad.org/).
