### ISSUE TITLE
Disabled macros are still shown in ticket screen

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#838]
### Infos:

* Used Zammad version: 1.3.x
* Operating system: hosted at zammad.com
* Browser + version: Vivaldi

### Expected behavior:

* Macro disappears in ticket screen and cannot be selected any more

### Actual behavior:

* Macro still shown

### Steps to reproduce the behavior:

* Have >= 1 macro
* Change one macro from "active" to "inactive"
* Go back to a ticket, maybe an already open one (so you just have to click the ticket's tab on the left)
* Click the split button
* Wonder why your just disabled macro is still there
* Hit Ctrl+F5
* Come to the conclusion that this must be a bug
* File the bug :-)

My macros:
![screenshot-2017-03-10-224756](https://cloud.githubusercontent.com/assets/26226303/23814614/7c17ad28-05e4-11e7-9bee-f84cf015c96c.png)

The provided macros in the ticket screen:
![screenshot-2017-03-10-224812](https://cloud.githubusercontent.com/assets/26226303/23814649/9de5c44e-05e4-11e7-9835-6627f2fa370c.png)

**Comment by AND51** [comment]
If you delete a macro, it also vanishes from the split button.

**Comment by martini** [comment]
Thanks for very good bug description! ❤️

It's fixed in develop, master and stable now.

**Comment by AND51** [comment]
You're welcome!

Let me ask this:

1. Shall I check if this bug is correctly fixed iny my Zammad or is "submitting bugs only" enough for a regular user?
2. When / How do I receive this fix in my commercial Zammad? Sorry, but I am not familar with the whole system as I am an admin and not a developer.
