### ISSUE TITLE
Backup skript fails to remove old backups

### ISSUE THREAD

**Issue by sensolytics** [zammad/zammad#840]
### Infos:

* Used Zammad version: 1.3.X
* Operating system: Debian 8.7
* Browser + version: n/a

### Expected behavior:

* I am using the backup skript found in /contrib/backup to regularly get a snapshot of my system. The backups are stored in /var/tmp/zammad/, and should be held there for 10 days.

### Actual behavior:

* The skript creates the backup, but the function do remove backups older than 10 days fails with 
```
rm: missing operand
Try 'rm --help' for more information.
```
The reason should be found in the function delete_old_backups(), where the exec of the find command is not complete. For my system, I replaced the exec with -delete, which should do the job...

Greetings

**Comment by monotek** [comment]
Thanks.
Fixed in https://github.com/zammad/zammad/commit/22aea64b70515eb62b1be6594d334e13eb3f4117
