### ISSUE TITLE
Link in auto reply mail misses Port 3000

### ISSUE THREAD

**Issue by Elmenhorst** [zammad/zammad#841]
### Infos:

* Used Zammad version: 1.1
* Operating system: Debian 8.7
* Browser + version: Chrome 57.0.2987.98 (64-bit)

### Expected behavior:

* I edited the trigger "auto reply (on new tickets)" to translate it into German like this:
Ihre Anfrage (#{config.ticket_hook}#{ticket.number}) wurde empfangen und wird in Kürze bearbeitet.

Um weitere Informationen hinzuzufügen, antworten Sie bitte auf diese Email oder klicken Sie auf den folgenden Link: #{config.http_type}://#{config.fqdn}/#ticket/zoom/#{ticket.id}
(Bitte nutzen Sie für die Anmeldung Ihre Email-Adresse und Ihr Windows-Passwort)
Ihr #{config.product_name}

### Actual behavior:

* After a new Ticket is received via Email, the auto reply is working but in the link to follow the ticket, Port 3000 is missing, If I enter the Link in the auto reply mail, I only get to the NGINX welcome screen but not to the login page of zammad.

### Steps to reproduce the behavior:

*

**Comment by martini** [comment]
Hi @Elmenhorst 

on Port 3000 only the application server is listening. Normally you should use port 80/443 for communication (also most proxy server only support port 80/443).

If you use the Zammad OS packages, you need to configure nginx (a notice is at the end of the installation). 

You need to configure the "server_name" (per default it's localhost, replace it with your IP or FQDN for Zammad) in 

DEBIAN: /etc/nginx/sites-enabled/zammad.conf"
REDHAT: /etc/nginx/conf.d/zammad.conf"
SUSE: /etc/nginx/vhosts.d/zammad.conf"

to access Zammad via nginx. But this is not Zammad related. It's nginx related.
  
-Martin
