### ISSUE TITLE
Extended characters on AD users causes weird OTRS import issues

### ISSUE THREAD

**Issue by nublaii** [zammad/zammad#842]
I am trying to import around 400 users and 20.000 tickets from an OTRS 5 installation.

We are a spanish company and our users are on a remote AD. Lots of them have extended characters on their names (López, Pérez, César).

The import runs fine, but when I log in to Zammad I get some weird things:

I attach 3 screenshots (I changed the values and left the one lastname with an accent): user listing and user info for both users

![screen shot 2017-03-14 at 12 59 05](https://cloud.githubusercontent.com/assets/1773409/23899680/64cfe8f4-08b6-11e7-89b6-b848f45e9b18.png)

![screen shot 2017-03-14 at 12 59 49](https://cloud.githubusercontent.com/assets/1773409/23899686/69ff55f8-08b6-11e7-932f-401e87373ae8.png)

![screen shot 2017-03-14 at 13 00 27](https://cloud.githubusercontent.com/assets/1773409/23899693/704f04bc-08b6-11e7-9fbd-2839af0a063e.png)

* Used Zammad version: Version: 1.3.0-1488535173.5bfe87f.xenial
* Operating system: Ubuntu 16.04 amd64
* Browser + version: any

### Expected behavior:

Each OTRS user gets imported as a single user on import.

### Actual behavior:

Random users are duplicated, apparently all the affected users have extended characters on either the name, lastname or both

### Steps to reproduce the behavior:

Import from OTRS (linked via ldap to a remote AD). I've done the import around 10 times, always the same behaviour.

**Comment by nublaii** [comment]
Some extra info related to this:

I think I've cornered the error and it might not be related to LDAP.

BROKEN: --------------------------------
`articles.a_from` column on OTRS DB: `User Lastname Hernández <user.hernandez@example.com>`

we get 2 users on zammad after import, the second one with an extra '**>**' at the end

ZAMMAD login: `user.lastname@example.com`
ZAMMAD login: `user.lastname@example.com>`

If I 'clean' the `articles.a_from` column on OTRS DB and remove any extended chars:

WORKS: --------------------------
`articles.a_from` column on OTRS DB: `User Lastname Hernandez <user.hernandez@example.com>`

we get 1 user on zammad (as expected)

ZAMMAD login: `user.lastname@example.com`

So it looks like the import process is getting a little crazy with encoding when trying to merge info from tickets/articles and users?

**Comment by thorsteneckel** [comment]
Hi @nublaii - I fixed the described behavior with the commit above. Would be great to get some feedback.
