### ISSUE TITLE
Overly exact gauge at re-opening rate

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#843]
### Infos:

* Used Zammad version: 1.3.x
* Operating system: hosted at zammad.com
* Browser + version: FF 49

### Expected behavior:

* Max. one digit after decimal point → 11.1%

### Actual behavior:

* Three digits after decimal point → 11.111%

### Steps to reproduce the behavior:

* Open Dashboard

![screenshot-2017-03-14-16 29 20](https://cloud.githubusercontent.com/assets/26226303/23908325/ff7187ce-08d3-11e7-9605-32208962fec2.png)

My opinion says that one or maybe two digits after the decimal point is enough. Three digits is a bit too scientific :-)
Maybe, you can make both gauges equal by rounding, i. e. the upper gauge has same number of decimal digits as the lower gauge. And in German use comma instead of a point, please.

**Comment by hanneshal** [comment]
It will be fixed in the next release. See commit 
https://github.com/zammad/zammad/commit/216f36fda7234cef122d6ef63eace1010a3125a6

regards
Johannes
