### ISSUE TITLE
Attempt to create an Euro sign results in logout

### ISSUE THREAD

**Issue by jschurse** [zammad/zammad#844]
### Infos:

* Used Zammad version: 1.3.x
* Operating system: Debian
* Browser + version: Firefox latest

### Expected behavior:

* Pressing `AltGr + e` on a german keyboard will produce the euro sign: € 

### Actual behavior:

* Pressing `AltGr + e` on a german keyboard will log you out of Zammad :(

**Comment by thorsteneckel** [comment]
Duplicate of #656.
