### ISSUE TITLE
Allow additional usage of Ticket Number in (Zoom) URL

### ISSUE THREAD

**Issue by maege** [zammad/zammad#849]
### Infos:

* Used Zammad version: 1.3.x
* Operating system: Debian
* Browser + version: Chrome

### Expected behavior:

* Ticket Number in URL is correct

### Actual behavior:

* Ticket Number (ID) in URL is different to the ticketnumber

### Steps to reproduce the behavior:

* The Ticket ID 279 is missing:
> SELECT id, number, title FROM tickets ORDER BY id;
 277 | 35277  | Probleme mit Outlook
 278 | 35278  | Probleme mit Outlook TEST
 280 | 35279  | Defekte Festplatte im Server
 281 | 35280  | Fristverlängerung online
 282 | 35281  | NB191 Tunnel zu iSource offline

![image](https://cloud.githubusercontent.com/assets/25299891/23995856/aec7e4c0-0a4b-11e7-9b8c-1c36df55104a.png)

We haven't deletet any ticket manually or somthing else.
Any idea how to fix this?

**Comment by martini** [comment]
Hi @maege 

the reason why this is different is, the id in the URL is the database id of the ticket.

The ticket number is in your case auto incremented but can also be more complex format like YYYYMMDDXXXXXXXXXC.

Anyway, you are right. It would be good to use the real ticket number in the URL too.

 -Martin

**Comment by chessmango** [comment]
In my own use-case, I've found need to do menial tasks like re-open closed tickets using Rails when people have made mistakes - this might be a little trickier when both the URL and the in-page ticket are the same while the 'authoritative' ID is different. Recently noticed that mine don't match up, which at the moment isn't much of an issue

**Comment by 4-l-Clover** [comment]
Hi. @mantas 
If I were to change ticket_id to ticket_number, which part do I have to fix?
All API request is processing by ticket_id in the current codebase.
I have two options now.
1. fetching ticket_id with ticket_number from ruby backend in ticket_zoom.coffee file
2. add new Ruby API for all ticket operation done by ticket_number

what do you think about this?

**Comment by mantas** [comment]
Hi @4-l-Clover ,

Which would be you preferred option and why?

This is a really complex issue (that's why it's open for so long) and we certainly don't expect a full-fledged PR for the application. We're interested in seeing your thinking and decision making above all :)

**Comment by 4-l-Clover** [comment]
Hi. @mantas.
The current codebase is written by ticket_id, not ticket_number.
If we are going to use ticket_number, we must change many related parts in FE and BE.
So I am suggesting option 1 for this problem.
It can help us to minimize the changes in codebase.
I am going to figure out with option 1.
I will post my detailed solution soon.

**Comment by hsssystems** [comment]
Hi, 

we have the same issue, the ticket_number and ticket_id diverged since a month or so. We did not realize this at the beginning and merged some tickets that did not belong :-|. However the  ticket_number and ticket_id did where synchronous for several years. I do not know what happened... However, is there a way to increment the `ticket_number` in the database so the two numbers will be the same again at least for the next month/years?

![image](https://user-images.githubusercontent.com/25076676/105823457-75846280-5fbd-11eb-8ccf-1dc6394bdded.png)

**Comment by MrGeneration** [comment]
@hsssystems please don't hijack issues.
This is rather a technical question that belongs to our community: https://community.zammad.org

---

Because of missing feedback and bumps on this issue I'm limitting the conversation to contributors only.
