### ISSUE TITLE
API for Tags

### ISSUE THREAD

**Issue by morphxle** [zammad/zammad#850]
Hi,

is it possible to post new Tags over the api?

Liebe Grüße aus Stuttgart
Jens

**Comment by nidico** [comment]
> is it possible to post new Tags over the api?

Yes, you can set tags on objects (at least on tickets) like that:

    /tags/add?object=Ticket&o_id={ticket_id}&item={tag}

I haven't found this in the [current API docs](https://docs.zammad.org/en/latest/api-intro.html) though.

**Comment by rolfschmidt** [comment]
Hi @morphxle,
i improved the documentation for the tags api. Please take a look at:

https://docs.zammad.org/en/latest/api-tags.html

@nidico Thanks for your first aid support ;-)

**Comment by morphxle** [comment]
hi @rolfschmidt & @nidico thank you very much. 
Liebe Grüße ;-)
Jens
