### ISSUE TITLE
Admin unauthorized to open Tickets

### ISSUE THREAD

**Issue by firlevapz** [zammad/zammad#862]
### Infos:

* Used Zammad version: 1.5.0-1489735364.31ab1b6.xenial (installed from deb)
* Operating system: ubuntu 16.04.2
* Browser + version: firefox & chromium

### Expected behavior:

* Display tickets

### Actual behavior:

* Gets an `401 Unauthorized` from REST and shows `Opps.. I'm sorry, but you have insufficient rights to open this Ticket... ` in Frontend, when a User has admin-role and agent-role. 
* When admin-role is removed, then all tickets can be opened normally. 

### Steps to reproduce the behavior:

* Give user admin + agent role and try to open any ticket

**Comment by martini** [comment]
Hi @firlevapz 

I can't reproduce this. :-/

Normally you need to have agent role and (if you have more groups) rights for the group where you want to access the ticket.

Is it possible to get remote login to see what's happen?

 -Martin

**Comment by firlevapz** [comment]
Okay, i was able to fix this, by rebuilding the roles and permission tables from a fresh new installation of zammad into our existing environment, where we had this issue.
Maybe this was caused somehow by moving from source-code installation to deb-packages back and forth, but I can't really tell...

**Comment by NvL-WEAP** [comment]
Old, but i experienced the same problem, it was due the following setting;

SETTINGS > Roles > Agents 
![image](https://user-images.githubusercontent.com/22333015/41624119-fe8713bc-7414-11e8-9877-3d14fb835904.png)
