### ISSUE TITLE
relative dates in macros, triggers and scheduler

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#864]
### Infos:

* Used Zammad version: 1.3.x, 2.9
* Operating system: hosted at zammad.com
* Ticket-ID: #1043312 

### Expected behavior:

* Be able to select "remind me in X days from now"
* Minor issue: Make the first select field wider, you can't read the text. The fields for date and time don't have to be so wide.

### Actual behavior:

* Can only select "remind me on X"

### Steps to reproduce the behavior:

* Go to Settings→Macros→New Macro
* Click "Wait till"
* Then click next field. Here you can only select a fixed, absolute day.

Here you can see my macro "Remind in 2 days & assign to me". This macro doesn't work without relative dates.

==

![screenshot-2017-03-20-11 56 02](https://cloud.githubusercontent.com/assets/26226303/24096987/42639a56-0d64-11e7-86a3-11764857621f.png)

==

![screenshot-2017-03-20-11 59 01](https://cloud.githubusercontent.com/assets/26226303/24097093/aad86242-0d64-11e7-9e27-9e2587ef6a20.png)

==

**Comment by Valiantiam** [comment]
We are also very interested in this. We are looking for a way to have a macro to auto close a ticket in 24/48 hours.

Ideally we would just set up a macro to change state to pending close, pending till "48 hours from today" or something like that.

**Comment by svnr-dvnkln** [comment]
*bump*

We really need this for macros/triggers too.

**Comment by noresistence** [comment]
Also applies to triggers. We would like to automatically change the state to pending reminder, pending till "1 week from today" when certain tags are assigned, for some customers/organizations.

**Comment by noezdev** [comment]
Is there already a way to make it possible?

**Comment by MrGeneration** [comment]
Not a bump, but just a remark.

Beside of Macros this also applies to Triggers and (even more important) Schedulers.

**Comment by pinscher** [comment]
This is a very important feature since it is a basic workflow to reopen a tickets after a relative time.
In Zendesk is a field "**hours since pending**" that can be used in an automatisation to reopen a pending ticket after the time has pased.

![image](https://user-images.githubusercontent.com/415306/50939444-2f631180-147d-11e9-99d0-62c6065604a1.png)

Beside this Zendesk has for each status a "hours since..." field. This should be to hard to implement in Zammad also.

![image](https://user-images.githubusercontent.com/415306/50939509-75b87080-147d-11e9-9dfa-18a8871e6c86.png)

**Comment by thorsteneckel** [comment]
Hey @fleverest - thanks again for providing the PR! It's finally merged 🚀  Just for completeness: The issues were

- The `static` calendar picker does not load after switching to `relative` and back to `static`
- The time selection field (`hh::mm`) is too wide and looks strange
- The form validations marks the relative date selection as an error even before I had the chance to select something

@mantas correctly pointed out that the second and third issue were/are general Zammad issues. We will address those in dedicated commits which are already ready for review and waiting for me 🙈
