### ISSUE TITLE
Freshdesk

### ISSUE THREAD

**Issue by cs-chandu** [zammad/zammad#865]
Hi, I would like to see the progress towards implementing the feature for migrating helpdesk from freshdesk to zammad. and Also I would like to contribute towards developing this feature. please help me with starter kit. 

Thanks

**Comment by thorsteneckel** [comment]
Could vou please provide some description for your request. Only a title is not enough. Please describe what you are expecting. Thanks.

**Comment by chandupydev** [comment]
Updated ..!!

**Comment by thorsteneckel** [comment]
Hi @chandupydev - what is it with the closing and reopening? It creates a lot of noise for all watchers of this repository. Would be cool to just keep this issue open. Thanks.

**Comment by chandupydev** [comment]
`#view tickets
require "rubygems"
require "rest_client"
require "json"

# Your freshdesk domain
fd_domain = 'YOUR_DOMAIN'

# It could be either your user name or api_key.
user_name_or_api_key = 'YOUR_API_KEY'

# If you have given api_key, then it should be x. If you have given user name, it should be password
password_or_x = 'X'

api_path = "api/v2/tickets"

ticket_id = 12

api_url  = "https://#{fd_domain}.freshdesk.com/#{api_path}/#{ticket_id}"

site = RestClient::Resource.new(api_url, user_name_or_api_key, password_or_x)

begin
  response = site.get(:accept=>'application/json')
  puts "response_code: #{response.code} \n response_body: #{response.body} \n"
rescue RestClient::Exception => exception
  puts "API Error: Your request is not successful. If you are not able to debug this error properly, mail us at support@freshdesk.com with the follwing X-Request-Id"
  puts "X-Request-Id : #{exception.response.headers[:x_request_id]}"
  puts "Response Code: #{exception.response.code} \n Response Body: #{exception.response.body} \n"
end`

**Comment by chandupydev** [comment]
Can anybody help me in developing this feature in zammad.

**Comment by thorsteneckel** [comment]
Thanks to the great people over at https://github.com/Graylog2 (namely @jalogisch) we now have a first version of a Freshdesk migrator that we will transfer over to the Zammad core for everybody to use. The migration went pretty smooth and we're now looking for additional beta testers. If you are interested please reach out to support@zammad.com and refer to this issue and me. Thanks!

**Comment by holdenger** [comment]
@thorsteneckel Where exactly is that migrator you are reffering to?

**Comment by thorsteneckel** [comment]
Hey @holdenger - nice to see that you're interested in testing the Freshdesk migrator. The results in the meantime were all positive but we still looking for further beta testers. It would be great if you could drop us a mail (support at zammad.com) and refer to this issue / testing the Freshdesk import.
Looking forward to hear from you.

**Comment by Omeryl** [comment]
@thorsteneckel How did this end up going for you? Any further work, was the source code released?

**Comment by MrGeneration** [comment]
Please see above comment:
https://github.com/zammad/zammad/issues/865#issuecomment-494283065

It's still in Beta as we constantly do not receive any feedback of users that did request the code.
This is one of the reasons it's not stable yet.

**Comment by MrGeneration** [comment]
Just as a small follow up. The freshdesk import will get official in one of the future versions of Zammad.
Please note that we can't provide any ETA. We will update this issue accordingly if anything moves.

----

If you can't or don't want to wait and are ready for an alpha script, please contact our support team.

**Comment by thorsteneckel** [comment]
Done with https://github.com/zammad/zammad/commit/8790e389be671d447fe0383cff6ad6b73dcaec0d
