### ISSUE TITLE
how to contribute

### ISSUE THREAD

**Issue by majofi** [zammad/zammad#866]
Hi 
not really an issue though...
I would like to contribute, but the recommended way to share the ideas on the mailing list seems not to work, no response for 1 month. Am I at the wrong place ?

https://groups.google.com/forum/#!topic/zammad-core/BWS3e_W6PXE

I think it's important to discuss feature before submitting a PR.

Best
Mathias

**Comment by jospoortvliet** [comment]
Uncool. I see [they say github issues are not meant for this](https://zammad.org/participate) so perhaps an empty pull request with what you want to develop and how can work ;-)

Dear Zammad friends - I suggest that, if somebody wants to work for you for free :smiling_imp: you try and facilitate it :stuck_out_tongue:

**Comment by martini** [comment]
Hi @majofi 
hi @jospoortvliet 

> Dear Zammad friends - I suggest that, if somebody wants to work for you for free 😈 you try and facilitate it 😛

You are right (we just some kind of flooding with all the feedback right now). Anyway, I'll respond ASAP (after this session https://twitter.com/zammadhq/status/844819877273616385).

 -Martin

**Comment by monotek** [comment]
https://docs.zammad.org/en/latest/#contributing-docs

**Comment by martini** [comment]
@majofi I answered your question. Thanks for participating. Looking for your feedback.

 -MArtin
