### ISSUE TITLE
Feature: Slack integration slack DM to Ticket?

### ISSUE THREAD

**Issue by chandupydev** [zammad/zammad#867]
Hey guys..!! 

I am getting many thoughts what if it's having slack integration as well. :-)

**Comment by hanneshal** [comment]
there is a slack integration

**Comment by tailic** [comment]
I think his idea was not to send a message to slack on certain events (like the current slack integration does) but to create tickets on direct messages or maybe through a chatbot. Just stumbled upon this while searching for the same.

**Comment by coyoteltd** [comment]
I would also like this feature.  Is anyone / has anyone developed it?

**Comment by MrGeneration** [comment]
Sorry, but Github is not the right place for Zammad Feature-Requests.
Please use the Community (https://community.zammad.org) for FRs or technical questions.

Plus: This issue has been solved as `works as designed / wontfix`.

I've limited the conversation to contributors only to reduce the noise on the repository.
(Nothing personal, really :) )
