### ISSUE TITLE
DEB update to 1.4 downloads 1.5?

### ISSUE THREAD

**Issue by nublaii** [zammad/zammad#871]
I have 1.3 installed on ubuntu, and I was getting ready to install the update to 1.4.

I ran `apt-get dist-upgrade -d` to only download the packages when to my surprise zammad shows up with this name:

`zammad_1.5.0-1489735364.31ab1b6.xenial_amd64.deb`

Is it just a name thing? Unpackaging the deb shows up on the CHANGELOG.md that it is in fact 1.4...

```
# Change Log

## [1.4.0](https://github.com/zammad/zammad/tree/1.4.0) (2017-03-16)
[Full Changelog](https://github.com/zammad/zammad/compare/1.3.0...1.4.0)
```

**Comment by martini** [comment]
Hi @nublaii 

what branch/repo do your use? It seems that your are using develop (not stable which is recommended to production).

`cat /etc/apt/sources.list.d/zammad.list`

PS: The Change Log for develop is updated at release time.

 -Martin

**Comment by nublaii** [comment]
This is what I get

```
$ cat /etc/apt/sources.list.d/zammad.list
deb https://deb.packager.io/gh/zammad/zammad xenial stable
```

**Comment by monotek** [comment]
Did you changed this recently?
As you can see https://packager.io/gh/zammad/zammad#stable is on 1.4.
Also doesn't look like there was an 1.5 package in this repo at any time.
Only develop is on 1.5: https://packager.io/gh/zammad/zammad#develop

**Comment by nublaii** [comment]
I installed the stable branch last week, to migrate from an OTRS install.

Today I just run the upgrade... didn't touch the repos at all...

I just run a little test:

I added this line ([from the documentation](https://docs.zammad.org/en/latest/install-update.html))

`deb https://deb.packager.io/gh/zammad/zammad xenial stable`

on a different machine

```
$ apt-cache show zammad
Package: zammad
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 231832
Maintainer: support@packager.io
Architecture: amd64
Version: 1.5.0-1489735364.31ab1b6.xenial
Provides: zammad
Depends: mysql-common, libpq5, libsqlite3-0, openssl, libxml2, libxslt1.1, libreadline5, libreadline6, libssl1.0.0, libmysqlclient20, libevent-2.0-5, libevent-core-2.0-5, libevent-extra-2.0-5, nginx | apache2, postgresql | mysql-server | mariadb-server | sqlite
Conffiles:
 /etc/default/zammad d97ce9ecd137d8b45d55278a5c2c9175
 /etc/logrotate.d/zammad f3670cdeb478391573b53db98a6bc0ff
Description: Zammad is a web based open source helpdesk/customer support system
Description-md5: a57c5e55d3ec7da3ef8af7f15126049d
License: unknown
Vendor: Packager.io <https://packager.io>
Homepage: https://zammad.org
...
```

and it still shows 1.5.0 as the candidate to install when I run `apt-get install zammad -d`

```
...
Get:29 http://ubuntu.mirrors.ovh.net/ftp.ubuntu.com/ubuntu xenial-updates/main amd64 postgresql-9.5 amd64 9.5.6-0ubuntu0.16.04 [2,996 kB]
Get:30 https://deb.packager.io/gh/zammad/zammad xenial/stable amd64 zammad amd64 1.5.0-1489735364.31ab1b6.xenial [71.1 MB]
Get:31 http://ubuntu.mirrors.ovh.net/ftp.ubuntu.com/ubuntu xenial/main amd64 postgresql all 9.5+173 [5,336 B]
...
```

**Comment by kleitim** [comment]
same here:

```
Version: 1.5.0-1489735364.31ab1b6.xenial
Version: 1.4.0-1490108876.8828df1.xenial
```

```
cat /etc/apt/sources.list.d/zammad.list
deb https://deb.packager.io/gh/zammad/zammad xenial stable
```

**Comment by hagen3000** [comment]
same here
(Ubuntu 16.04)

> cat /etc/apt/sources.list.d/zammad.list
deb https://deb.packager.io/gh/zammad/zammad xenial stable

> apt list zammad -a
zammad/now 1.5.0-1489735364.31ab1b6.xenial amd64  [Installiert,lokal]
zammad/unbekannt 1.4.0-1490345103.a26f0d9.xenial amd64

I installed version 1.4.0 manually
> apt install zammad*=1.4.0-1490345103.a26f0d9.xenial

**Comment by martini** [comment]
Update: Today we talked with the packager.io guys. This was an error. After "apt-get update" is should work well again (1.5.0 should not appear anymore).

Feedback would be fine!

**Comment by hagen3000** [comment]
Yes - it works.

thanks.

**Comment by martini** [comment]
Thanks for feedback!

**Comment by kleitim** [comment]
Yes Sir, it works.
