### ISSUE TITLE
SMTP Config 501 5.1.7 Bad sender address syntax 

### ISSUE THREAD

**Issue by Merlin90** [zammad/zammad#873]
### Infos:

* Used Zammad version: 1.5.0
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Firefox ESR 45.7.0

### Expected behavior:

* I want to use a local self-hosted SMTP Server

### Actual behavior:

* I get the following error message when I enter the SMTP: 501 5.1.7 Bad sender address syntax

Log:
```

I, [2017-03-22T14:07:01.318061 #1119]  INFO -- : Started POST "/api/v1/channels_email_notification" for 192.168.0.230 at 2017-03-22 14:07:01 +0100
I, [2017-03-22T14:07:01.320629 #1119]  INFO -- : Processing by ChannelsEmailController#notification as JSON
I, [2017-03-22T14:07:01.320719 #1119]  INFO -- :   Parameters: {"adapter"=>"smtp", "options"=>{"host"=>"hostname.domain.tld", "user"=>"", "password"=>"[FILTERED]", "port"=>"25"}, "channel_id"=>2, "channels_email"=>{"adapter"=>"smtp", "options"=>{"host"=>"hostname.domain.tld", "user"=>"", "password"=>"[FILTERED]", "port"=>"25"}, "channel_id"=>2}}
I, [2017-03-22T14:07:01.337482 #1119]  INFO -- : Completed 200 OK in 17ms (Views: 0.5ms | ActiveRecord: 1.7ms)
```

What am I doing wrong?

**Comment by martini** [comment]
Hi @Merlin90 

that's strange. This is working on my setup, I can't reproduce this.

What MTA do you use on your local server? Would remote login for debugging possible?

 -Martin

**Comment by Merlin90** [comment]
Hi @martini 
i use Postfix as MTA and i have fully access to the server.

-Merlin

**Comment by thorsteneckel** [comment]
This issue/question has been stale for quite a while. Please refer to the [community board](http://community.zammad.org/) if it still persists. We'll have a look and create an issue if it's related to Zammad. Thanks! Closing now.

**Comment by fmarier** [comment]
Apologies for resurrecting a very old issue, but I saw this in my DDG results and it looks awfully similar to https://stackoverflow.com/questions/25705002/postfix-bad-sender-address-syntax-causes-fetchmail-to-re-fetch-the-same-email (i.e. sender email address cannot start with a hyphen or Postfix will reject it).

**Comment by MrGeneration** [comment]
Please don't recycle already closed issues.
In my opinion this is a handling mistake and thus I won't reopen this.

Please use the community if you in case want to discuss on this topic.
