### ISSUE TITLE
Make indexing of email attachments optional

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#875]
It is my understanding that Zammad sends all email attachments to Elasticsearch for indexing.

As we do support for PDF editing software, our customers are sending us lots of PDF documents as sample files. When we search for text that appeared in a ticket, we end up with a lot of noisy hits from those customer documents that include the search terms. But we have no interest in searching these documents.

It would be helpful being able to disable this feature.

Or would it be sufficient simply not to install the `mapper-attachments` plugin?

**Comment by olivergrahl** [comment]
Never mind, I just found `es_attachment_ignore` and `es_attachment_max_size_in_mb` settings. Would setting `es_attachment_max_size_in_mb` to 0 do the trick?

**Comment by martini** [comment]
@olivergrahl interesting use case! 😃

There are additional settings for elasticsearch: https://docs.zammad.org/en/latest/install-elasticsearch.html

For example, you can ignore pdf's with `es_attachment_ignore`:

```
zammad run rails r "Setting.set('es_attachment_ignore', [ '.png', '.jpg', '.jpeg', '.mpeg', '.mpg', '.mov', '.bin', '.exe', '.box', '.mbox' ] )"
```


> Or would it be sufficient simply not to install the mapper-attachments plugin?

No, this would lead to an error. 

 -Martin

**Comment by olivergrahl** [comment]
Perfect, thanks!! :-)
