### ISSUE TITLE
Acess to Database with HeidiSQL

### ISSUE THREAD

**Issue by ArcheNoah77** [zammad/zammad#876]
* Used Zammad version: 1.4.0
* Operating system: Debian 8
* MySQL: 5.5

 I want to connect to the Database of my webserver with HeidiSQL:
![1](https://cloud.githubusercontent.com/assets/25475591/24204602/46ada0be-0f19-11e7-8e1f-94beb47d248d.png)
![2](https://cloud.githubusercontent.com/assets/25475591/24204678/852814a0-0f19-11e7-8715-d270a79aee19.png)

Have anyone experience with that and can help me?

**Comment by martini** [comment]
Hi @ArcheNoah77 

I see no reason why it should not work. If MySQL is configured to allow network connections (pls check your firewall also) it should work fine.

PS: It's not a Zammad issue, so I'm closing it.

 -Martin
