### ISSUE TITLE
Integrate customers in database

### ISSUE THREAD

**Issue by mamebina** [zammad/zammad#879]
### Infos:

* Used Zammad version: 1.4.0
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Firefox

### Expected behavior:

* Is it possible to integrate a customers database, which is used for an other helpdesk system, so i do not have to add all customers by hand? Is there an existing function on the web app or is there a possibility to do that within the terminal?
I know that is it possible to do that from OTRS or Zendesk to Zammad.

**Comment by kernbrand** [comment]
yes that's possible and quite easy, below is an expample using PHP

first create the organizations

$url = "http://zammad.blabla.de/api/v1/";
$service = "organizations";
$content = "application/json";
$username = "user";
$password = "pass";

foreach ($users as $user) {
       $data = array("name" =>$user['company'], "shared" => true, "active" => true, "note" => "imported");
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_HTTPHEADER, array($content));
	curl_setopt($ch, CURLOPT_HEADER, 1);
	curl_setopt($ch, CURLOPT_POST, 1); 
	curl_setopt($ch, CURLOPT_URL, $url.$service);
	curl_setopt($ch, CURLOPT_TIMEOUT, 30); //timeout after 30 seconds
	curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
	curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
	$response2 = curl_exec($ch);
	curl_close($ch);
}

and then add the users to the matching organizations:

$url = "http://zammad.blabla.de/api/v1/";
$service = "users";
$content = "application/json";
$username = "user";
$password = "pass";

foreach ($users as $z) {
	$data = array("firstname" => $z[0], "lastname" => $z[1], "email" => $z[8], "organization" => $z[2], "phone" => $z[7], "address" => $z[3]."\n".$z[5]." ".$z[4], "note" => "aus Selectline", "role_ids" => 3);
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_HTTPHEADER, array($content));
	curl_setopt($ch, CURLOPT_HEADER, 1);
	curl_setopt($ch, CURLOPT_POST, 1); 
	curl_setopt($ch, CURLOPT_URL, $url.$service);
	curl_setopt($ch, CURLOPT_TIMEOUT, 30); //timeout after 30 seconds
	curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
	curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
	$response2 = curl_exec($ch);
	curl_close($ch);
}

**Comment by MrGeneration** [comment]
Further information on API can be found here:
https://docs.zammad.org/en/latest/api-intro.html

I'll be closing this, this is solved.
