### ISSUE TITLE
Placeholder in triggers with created_by & updated_by / > in article.body

### ISSUE THREAD

**Issue by Hirbod** [zammad/zammad#883]
Hi,

which Placeholders are available in triggers?

I actually wanted to send emails on notes (figured out how) and also found an Issue poiting at

`#{article.body}`

But I am missing the ability to set Users First- and Lastname.
I get: `#{user / no such object} #{user / no such object}`

I would love to have also the ability to access a systemsignature, but I can't find any documentation about placeholders.

Edit: `#{article.body}` automatically adds a ">" infront of the text. Why?

**Comment by Hirbod** [comment]
So after clickin around for hours, I found a hidden "description" field under "TextModules" which described some available placeholders. Please update or point to better documentations.

**Comment by Hirbod** [comment]
Edit again: wow, entering :: inside of triggeres actually showed me everything i need.
So just one thing left: why the mail gets a > wenn using `#{article.body}`

sry for spamming!

**Comment by AdiosOnline** [comment]
Maybe the same Issue/Question as in #905 opened by me. If so I will close my Case...

**Comment by Hirbod** [comment]
@martini any ideas?

**Comment by martini** [comment]
Hi @Hirbod 

you are right, there was an issue with placeholder name which contains "create" or "update" in the name (we check this for security reasons).

Now this check has been improved and is available in (develop, master, 1.4, 1.3 and 1.2 - git and packages since we build packages in every commit).

Feedback is welcome!

 -Martin

**Comment by martini** [comment]
> Edit: #{article.body} automatically adds a ">" infront of the text. Why?

article.body is the text article, which usually want to be included as text quote.

If you want to add the article as html, use #{article.body_as_html}.

**Comment by Hirbod** [comment]
Just made an update to 1.4.0-1490622316.73ebe17.jessie (using the apt-get upgrade)
Are these changes reflected there?

**Comment by Hirbod** [comment]
Yay! Just updated and tested. "article.updated_by.firstname" worked perfectly!
