### ISSUE TITLE
Firefox - Focus lost after using :: TextSnippts

### ISSUE THREAD

**Issue by Hirbod** [zammad/zammad#884]
As soon as I enter :: and select from the list, the focus on textarea is lost and I have to reclick inside again.

**Comment by martini** [comment]
Hi @Hirbod 

I can't reproduce this. For me it works fine (focus is still on same position). What browser do you use? Can you add a little video/screencast?

-Martin

**Comment by Hirbod** [comment]
Sure, here we go.
https://youtu.be/lblituC_qpM

Just to mention: just tested on Firefox (Mac OS Sierra, newest Version)
Firefox 52.0.2

Focus is lost when chosing with mouse, preserved when using keyboard.

**Comment by rolfschmidt** [comment]
Chrome works fine. Looks like the problem is only given on firefox.

**Comment by rolfschmidt** [comment]
Hi @Hirbod ,
should be fixed now in develop branch. Thank you very much for your report.

Best regards,
Rolf
