### ISSUE TITLE
Agent dependent Signatures

### ISSUE THREAD

**Issue by ArcheNoah77** [zammad/zammad#886]
It would be a nice feature, that every Agent have his own Signature.

### Expected behavior:
If Agent 1 answer a ticket, it should automatically use "Signature Agent 1"
If Agent 2 answer a ticket, it should automatically use "Signature Agent 2"

Is it possible to implement this?

**Comment by martini** [comment]
Hi @ArcheNoah77 

did you see the placeholder feature. You can set placeholders to signature link:

#{user.firstname} #{user.lastname}

So you have define one signature for a team and you can personalise it.

PS: You get a list of all placeholders my using "::".

 -Martin
