### ISSUE TITLE
Some notifications are marked as read initially

### ISSUE THREAD

**Issue by raphaelm** [zammad/zammad#887]
### Infos:
* Used Zammad version: 1.4.x
* Operating system: Debian
* Browser + version: Chrome 56

### Expected behavior:

* Every new notification is initially unread

### Actual behavior:

* If another agent comments in a ticket, I hear the sound of a Zammad notification
* However, if I switch to the Zammad tab in my browser, the new notification is already marked as read

### Steps to reproduce the behavior:

I'm not yet sure if the owner or status of the ticket is relevant for this. It doesn't appear to be related to the fact whether I have the ticket currently open in Zammad.
It doesn't happen for comments created by customers via email.

**Comment by martini** [comment]
Hi @raphaelm 

we tried to enhance the notifications (reduce to read messages which are already *outdated*). Zammad will set notifications to "read" if:

1) Ticket is already closed by an other agent and you are not the current ticket owner.
2) The new ticket state is a pending close state.
3) The new ticket state is a pending reminder state and you are not the current ticket owner.

Feedback is welcome!

 -Martin

**Comment by raphaelm** [comment]
This makes sense. I belive in this cases you also don't send a desktop notification? Then I'd suggest to drop the notification sound as well.

**Comment by martini** [comment]
Currently for every notification (read and unread) a desktop notification + sound is fired.

https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/widget/online_notification.coffee#L228

-> We will change it, to only fire desktop notification + sound for "unread" notifications.

PS: There is still the possibility that somebody will add a note and close it 10 seconds later (the last one is the trigger to set notification to read). Then a desktop notification + sound can still appear until the new state is closed. Just to be not confused in this case. :)

**Comment by martini** [comment]
Changed in stable, master & develop.

Thanks for participating!
