### ISSUE TITLE
Add "Article body" as condition

### ISSUE THREAD

**Issue by Hirbod** [zammad/zammad#891]
In order to react on Telegram messages (eg. listen for commands in order to react on content), we need more then subject, cc etc.

<img width="711" alt="bildschirmfoto 2017-03-25 um 16 11 59" src="https://cloud.githubusercontent.com/assets/504909/24323457/d49afe7c-1175-11e7-9af1-f8b82993ebe3.png">

I need to be able to also check the body content. The action currently has changing ticket specific stuff or E-Mail notification. I need to be able to answer as "note". So I could respond to /angebot (which means "offer" with "Hey, call us at +4912345"

**Comment by MrGeneration** [comment]
This has been implemented quite some time ago, I'll be closing this for this reason. :-)


![image](https://user-images.githubusercontent.com/6549061/60331573-3fbc6980-9995-11e9-8bc2-b9df45ce166c.png)
