### ISSUE TITLE
OTRS Importer fails if a_body is null in OTRS article table

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#894]
### Infos:

* Used Zammad version: 1.4
* Operating system: Ubuntu 16.4 LTS
* Browser + version: Chrome 56

### Scenario:

Import data from an OTRS installation which was often updated (since OTRS 2.0) and has seen a lot of bugs because of its age. In this case it can happen (yes, it never should but it did in about 200 out of 250.000 times in my case) that some articles have a_body with "null" as value in the OTRS article table.

### Expected behavior:

* Trow an ERROR and skip that article

### Actual behavior:

* Importer fails

### Steps to reproduce the behavior:

* Import OTRS data with a_body set to null in OTRS article table

**Comment by martini** [comment]
Same on my side.

**Comment by thorsteneckel** [comment]
Fixed with the commit above. Will be part of the next release. Feedback would be great!

**Comment by thorsteneckel** [comment]
JFI: You can already test this when using the develop branch / package.

**Comment by hiaz** [comment]
@thorsteneckel Cool! I like to test it all importer related issues asap. But one question: I have an existing 1.4 test installation. I upgraded the system several times with the help of your ubuntu packages (works great by the way). Can I now just use the zip file of the development brach (directly from git), stop zammad and unpack the content to /opt/zammad? Or how should I proceed?

**Comment by thorsteneckel** [comment]
Hi @hiaz - I'm currently working on a merge into stable so you can just update to the latest Zammad version and you're good to go. I'll let you know when all commits are merged.

**Comment by thorsteneckel** [comment]
Done :) Please wait ~1 hour till our package build process catches up with the changes and you can use the latest stable package for your ubuntu package 👍

**Comment by hiaz** [comment]
Hi @thorsteneckel, I waited until now. But I get still 1.5.0-1493560511.edcfcf6.xenial a packet. I expected 1.5.1-*? Or is 1.5.0-1493560511.edcfcf6.xenial already with the fixes?

**Comment by thorsteneckel** [comment]
Hi @hiaz - yes, it's up to date with the [stable branch](https://github.com/zammad/zammad/commits/stable). The latest commit is currently `edcfcf6f...` which is the suffix of the package name above. So the changes are included in the package you got.

**Comment by hiaz** [comment]
@thorsteneckel Works like expected. Thank you!
