### ISSUE TITLE
OTRS Import: Password of users are changed after reimport

### ISSUE THREAD

**Issue by martini** [zammad/zammad#896]
### Infos:

* Used Zammad version: 1.4
* Operating system: all
* Browser + version: all

### Expected behavior:

* After reimporting OTRS data (e. g. restart because if stopped import caused of invalid data) the password of users is changed -> No login possible anymore.

### Actual behavior:

* Do not update passwords in reimport.

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment]
Fixed with the commit above. Will be part of the next release. Feedback would be great!

**Comment by thorsteneckel** [comment]
JFI: You can already test this when using the develop branch / package.
