### ISSUE TITLE
Schedules - Disable Notification not changable

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#897]
Hello,

### Infos:

* Used Zammad version: 1.4.0
* Operating system: Ubuntu 16.04.02
* Browser + version: 

The setting "Disable Notifications"="no" in Schedules is not stored correctly. It's alway set to the standard "yes"

Greetings 
tobibe

**Comment by rolfschmidt** [comment]
@tobibe thank you very much for your report. I fixed the typo in the develop branch, it should work now. It will be released with the next stable release.
