### ISSUE TITLE
Bulk action: selection is reset when web app is updating in background

### ISSUE THREAD

**Issue by eliasp** [zammad/zammad#901]
### Infos:

* Used Zammad version: 1.4.0
* Operating system: Debian 8.7 (Server), Gentoo (Client)
* Browser + version: Chromium 57

### Expected behavior:

* When having multiple tickets selected for a bulk action and a new State/Priority/Group/Owner chosen, the selection should remain

### Actual behavior:

* The selection for a bulk action (State/Priority/Group/Owner) is reset to `-` when Zammad's web application runs its periodic background update.

### Steps to reproduce the behavior:

* Select multiple tickets (e.g. in **Overviews** → **Unassigned & Open**)
* Select a state for them (e.g. **closed**)
* Wait for ~1 minute until Zammad's web app runs its periodic background update

**Comment by eliasp** [comment]
This also affects the intermediate dialog which is shown after clicking **Confirm** and allows to add an Article. This dialog simply disappears.

**Comment by muhammadn** [comment]
@eliasp I could not reproduce this problem on my end. Could you try out the latest `develop` branch to see whether it works out for you?
