### ISSUE TITLE
Can't use PUT on Organizations REST API with token access

### ISSUE THREAD

**Issue by LukasReschke** [zammad/zammad#902]
### Infos:

* Used Zammad version: 1.5.0-1489735364.31ab1b6.xenial
* Operating system: Ubuntu 16.04

### Expected behavior:

* Organization should be updated

### Actual behavior:

* 401 is returned by Zammad

### Steps to reproduce the behavior:

* Create a personal access token with permission "admin, report, user_preferences".
* Send a PUT to `/api/v1/organizations/10` such as the following. Note that GETs do work with the application:

```
PUT /api/v1/organizations/10 HTTP/1.1
Host: XXX.nextcloud.com
Content-Type: application/json
Authorization: Token token=XXXXXX
User-Agent: Nextcloud Server Crawler
Content-Length: 381
Connection: close

{"name":"XXXXXX,"shared":true,"note":"","member_ids":[27,28],"active":true,"updated_at":"2017-03-27T23:13:23.474Z","domain_assignment":false,"domain":"XXXX.XXX","collabora_subscription":false,"collabora_subscription_users":0,"subscription":"standard","subscription_end":"2017-11-22","subscription_start":"2016-11-22","user_number":3000,"id":10}
```

* A 401 is returned by Zammad and the log contains `I, [2017-03-28T14:08:58.937417 #103001]  INFO -- : Completed 401 Unauthorized in 36ms (Views: 1.4ms | ActiveRecord: 9.0ms)`

Doing the same request using HTTP Basic Authentication does work. So I suppose this is a small bug here? Especially as the required permission as per documentation should be `admin.organization`.

Cheers from @Nextcloud :-)

**Comment by martini** [comment]
Hi @LukasReschke 

thanks for the issue. It's fixed in develop, stable and next release.

 -Martin

**Comment by luisdetlefsen** [comment]
This is happening again on version 2.8 and 2.9.

**Comment by MrGeneration** [comment]
@smash87 please don't recycle fixed issues and instead open a new issue for this for overview reasons. :)

Besides:
I tested above example with POST:

```
{
	"name":"Test",	
	"shared":true,
	"note":"Test",
	"member_ids":[3,4],
	"active":true,
	"domain_assignment":false,
	"domain":"xxx.xxx"
}
```

Works totally fine on my end:

```
{
    "id": 3,
    "name": "Test",
    "shared": true,
    "domain": "xxx.xxx",
    "domain_assignment": false,
    "active": true,
    "note": "Test",
    "updated_by_id": 3,
    "created_by_id": 3,
    "created_at": "2019-02-05T17:33:41.000Z",
    "updated_at": "2019-02-05T17:33:42.944Z",
    "member_ids": [
        3,
        4
    ]
}
```

If you have technical questions, please use our community board: https://community.zammad.org
