### ISSUE TITLE
member_ids missing in organization list API endpoint

### ISSUE THREAD

**Issue by LukasReschke** [zammad/zammad#903]
### Infos:

* Used Zammad version: 1.5.0-1489735364.31ab1b6.xenial
* Operating system: Ubuntu 16.04

### Expected behavior:

* The `/api/v1/organizations` API should return the member_ids like the show endpoint `/api/v1/organizations/{id}` does.

As a remark: Having the user information also in the `assets` blob in the response would be nice to have but isn't quite necessary for our use-case. But not having the member_ids increases the amount of requests on our API consumer significantly.

### Actual behavior:

* member_ids are not included in the list endpoint.

**Comment by martini** [comment]
Hi @LukasReschke 

(I'll look closer later)

By the way: We have the same issue in our web app. For this we call the urls with:

/api/v1/organizations?expand=true

Here you get the relation names also, here e. g. member_ids: [1,2,3] and members: ['login1', 'login2', 'login3'] or on other places priority_id: 1 with priority: '1 low'.

If you want the full assets of an object (located assets of the response), you can use:

/api/v1/organizations?full=true

Looking forward for feedback! 👹

 -Martin

**Comment by LukasReschke** [comment]
Awesome! `?expand=true` makes my life way easier :-)

**Comment by LukasReschke** [comment]
Thanks a lot! 🚀
