### ISSUE TITLE
Send article body

### ISSUE THREAD

**Issue by AdiosOnline** [zammad/zammad#905]
### Infos:

* Used Zammad version: 1.4.x

Hi,

I set a Trigger to send Public Notes per Mail to the Customer. (Trigger Described in #298 ).
I thought that the Line:
"

> Ihr Agent weist auf folgendes hin:
> #{article.body}

"
would send the actual content from the last Public note. But the Email the Customer receives looks like:
"

> Ihr Agent weist auf folgendes hin:
> > Ihre Anfrage (Ticket#87473): (Neuen Zamad Agent "Webdesigner"?) wurde vom Support
> > Team vollständig bearbeitet.
> > 
> > Für weitere Informationen klicken auf den Nachfolgenden Link:[1]
> > http://zammad/#ticket/zoom/473
> > 
> > Ihr Gruppe - Helpdesk Team
> > 
> > [1] http://zammad/#ticket/zoom/473

"

I searched the Documentation in zammad.org for Possible Tags I can insert to the Mail Body, but i can't find any overview about that and therefore no Solution for my Problem. 

Would be glad to get a complete overview about possible content Strings. If not possible a direct Solution for my Problem would be nice.

Thanks a lot!

J. Müller

Edit:
After Reading #800 I tried over and over to recreate my failure. I think the Trigger for sendig public Notes is not possible while closing the Ticket. If done this way the Trigger sends the "closed-Notification" as Article.body. Is there a workaround to get the actual Public Note sent instead of the Closing Notification?

**Comment by martini** [comment]
@AdiosOnline currently only "#{article.body}" is supported which is the last article of an ticket.

You looking for something like:

#{ticket.article_customer_last.body}
#{ticket.article_system_last.body}
#{ticket.article_agent_last.body}

?

Or, what do your mean with "public notes"?

**Comment by AdiosOnline** [comment]
Hi @martini ,

Thnaks for your feedback. 

That would be what I am looking for, but when i put it into a Trigger, the Email content look like
Ihre Anfrage (Ticket#87502): (TEst) wurde vom Support Team bearbeitet.

> Ihr Agent weist auf folgendes hin:
> #{ticket.article_agent_last / no such method}
> 
> Für weitere Informationen klicken auf den Nachfolgenden Link

Which bodys can be used in Triggers?

Thanks

**Comment by martini** [comment]
> Which bodys can be used in Triggers?

Currently just "article.body" which is the latest article. -> So we need to add additional names to have them accessible via placeholder tags.

I have an change to the last list, how about this possibilities to access the last/first article by sender type?

#{ticket.articles_customer.last.body}
#{ticket.articles_system.last.body}
#{ticket.articles_agent.last.body}

#{ticket.articles_customer.first.body}
#{ticket.articles_system.first.body}
#{ticket.articles_agent.first.body}

Feedback is welcome!

**Comment by AdiosOnline** [comment]
Hi @martini ,

I think we talk about different things. What I need is an Element to place the last Article Body of a Public Note into a Email.
![image](https://cloud.githubusercontent.com/assets/24896670/24552443/bf44563a-1626-11e7-8a5a-e591f5d0e77f.png)

The Placeholders you posted seems not working on sent Emails.
![image](https://cloud.githubusercontent.com/assets/24896670/24552482/ebd2ec0c-1626-11e7-9133-d0c679da824c.png)

The working Quote is not working when the Ticket gets closed with the note. When we close the Ticket with the public Article, the sent Email looks like
![image](https://cloud.githubusercontent.com/assets/24896670/24552558/353a1cee-1627-11e7-8c98-922bb0111f75.png)
and its content is the "Your case is closed" Trigger Mail:
![image](https://cloud.githubusercontent.com/assets/24896670/24552613/72058bf4-1627-11e7-917a-600655bb356a.png)

i hope we get it working on this way.. Thanks for your further Feedback

**Comment by martini** [comment]
> The Placeholders you posted seems not working on sent Emails.

Thanks correct. I'm talking about, what placeholder you would need - we need to implement them. :)

-> I just want to clarify what you needs is (to do not work/implementation several times).

**Comment by AdiosOnline** [comment]
I need a Placeholder that send the Last Article (**Note**!!) even if the Ticket gets closed. Can yo reproduce my  Situation and know why the #{article.body} is not working every time for me?  Or are the Triggers above "Incompatible"?

**Comment by martini** [comment]
> Or are the Triggers above "Incompatible" to each other?

One more question, how many triggers do you have (and with which options)?

Background: Indeed I think we are talking from different things. I want to setup you use case to see what's going wrong.

**Comment by AdiosOnline** [comment]
hi @martini ,
sorry for my late response.

My active Triggers are the both from above, and these:
![image](https://cloud.githubusercontent.com/assets/24896670/24564635/d1b802d6-1652-11e7-9d34-551ad6ff1463.png)

![image](https://cloud.githubusercontent.com/assets/24896670/24564557/8cb2eb6a-1652-11e7-88a4-c52739eebefc.png)
![image](https://cloud.githubusercontent.com/assets/24896670/24564579/a5202fb4-1652-11e7-91ee-7a19ee2c9786.png)
![image](https://cloud.githubusercontent.com/assets/24896670/24564604/b80870fa-1652-11e7-858f-52aaa4f5e86f.png)

**Comment by AdiosOnline** [comment]
We could set up a Remote Session on monday if it's easier for you. Habe a nice Weekend.

**Comment by AdiosOnline** [comment]
Hi @martini ,

did you recreate my error? Anything new about a solution?

**Comment by thorsteneckel** [comment]
@MrGeneration can you please check if this is actually resolved as @rlue pointed out?

**Comment by MrGeneration** [comment]
I could verify that the current Zammad-Version does take the correct article-body.
For this I had a second trigger that fired right before the other trigger which would add a private note.

I'll be closing this. :)
