### ISSUE TITLE
Doorkeeper use_refresh_token

### ISSUE THREAD

**Issue by okodo** [zammad/zammad#906]
@martini Is there a reason why you have Doorkeeper without the option use_refresh_token?
This option can i activate only on self-hosted instance. But how to refresh the access token on your host? Always to redirect the user to authorize route to get the access token every 7200 seconds is very awkward. Is there some workaround for it?

**Comment by thorsteneckel** [comment]
Hi @okodo - thanks for the good point. We reflected the change in our Doorkeeper configuration with the commit above in the master and develop branches. Will be part of the next release. Closing for now.
