### ISSUE TITLE
"Add link"-screen is not really useful

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#907]
### Infos:

* Used Zammad version: 1.4.x
* Operating system: hosted at zammad.com
* Browser + version: Firefox 49

### Expected behavior:

* Wider columns

### Actual behavior:

* Narrow columns

### Steps to reproduce the behavior:

* Open a ticket
* Click "Add link to this ticket"

You cannot really use this screen. Column "title" is too narrow, column "Group" is too wide. You also can't resize the columns. All in all, it is very hard to recognize and pick the right ticket.

![screenshot-2017-03-29-13 21 21](https://cloud.githubusercontent.com/assets/26226303/24452321/fdffabc2-1482-11e7-87a4-9c9c550ca6e0.png)

**Comment by AND51** [comment]
I noticed that the "add link"-screen and the "merge ticket"-screen don't differ that much... Both show same information, but "merge ticket"-screen has a better screen, because columns are resizeable and actually, ticket numbers and titles are hyperlinks.

Maybe there is different code for both screens? Can you make both screens to be like the "merge ticket"-screen?

**Comment by martini** [comment]
Hi @AND51 great to have you on board!

Fixed this issue by using same ticket list widget (available in develop, master and next stable release). :)

 -Martin
