### ISSUE TITLE
KIX to Zammad migration

### ISSUE THREAD

**Issue by mz67122** [zammad/zammad#908]
### Infos:

* Used Zammad version: 1.4
* Operating system: CentoS 7
* Browser + version: Firefox
* OTRS 3.3.7 with KIX4OTRS

### Expected behavior:

* Data migration from OTRS to zammad

### Actual behavior:

* Migration failed...see attached "production.log"
ERROR -- : execute Import::OTRS.diff_worker (try_count 3) exited with error #<NoMethodError: undefined method `[]' for nil:NilClass>

### Steps to reproduce the behavior:

* start migration tool

**Comment by mz67122** [comment]
[production.txt](https://github.com/zammad/zammad/files/879345/production.txt)

**Comment by thorsteneckel** [comment]
Hi @mz67122 - as described [here](https://github.com/zammad/zammad/issues/218#issuecomment-255312477) we don't support KIX as a migration source and won't support in the future.
