### ISSUE TITLE
Condition: Ticket Tags for filtering Tickets

### ISSUE THREAD

**Issue by maege** [zammad/zammad#909]
### Infos:

* Used Zammad version: 1.4.x
* Operating system: Debian
* Browser + version: 

### Expected behavior:

* Use Tags in Triggers / Overview

### Actual behavior:

* Ticket Tag can not be used for filtering Tickets

We would like to have a overview of all open Tickets with specific Tags like "offer". Or create a trigger for Tickets with specific Tags.

![image](https://cloud.githubusercontent.com/assets/25299891/24460269/1a7d7778-149e-11e7-8610-dc933a736d45.png)

**Comment by morphxle** [comment]
+1

**Comment by martini** [comment]
@maege yes. This would be useful. It's already an issue https://github.com/zammad/zammad/issues/245
