### ISSUE TITLE
Unprocessable emails 

### ISSUE THREAD

**Issue by factor200x** [zammad/zammad#913]
Hi,

we have the problem that different mails are not read. What is striking here is that they are senders using Thunderbird or Lotus Notes.

I like to make the .eml files available in a private message.

Thank you very much!
Olaf

**Comment by martini** [comment]
@factor200x just send it via mail to support at zammad dot com.

PS: What Zammad version you use, would be fine to know.

Thanks!

**Comment by hanneshal** [comment]
Version is 1.4.
Samples recived

**Comment by martini** [comment]
As analysed with @rolfschmidt , the email contained invalid "To:"-Headers. The mails are already broken at arrival. Seems that a MTA in the middle or the mailer (thunderbird) is breaking the mail header.

As workaround remove the "@"-sign in realname of your Zammad email address (admin -> channel -> email -> select your zammad email address).
