### ISSUE TITLE
Default behaviour of "keeping tab"

### ISSUE THREAD

**Issue by Hirbod** [zammad/zammad#914]
<img width="419" alt="bildschirmfoto 2017-04-01 um 14 50 54" src="https://cloud.githubusercontent.com/assets/504909/24578870/ad511a20-16ea-11e7-8207-f95760fcb512.png">

When I change from "keep" to "close" I would consider a better UX experience, so this setting will reflect GLOBALLY (at least for a session, using sessionStorage or something like that). Currently I will have to change it for every ticket.

**Comment by hanneshal** [comment]
This is actually pretty annoying when you had selected  multiple tickets and want to work on one after the other.

**Comment by chrisblech** [comment]
+1

**Comment by MrGeneration** [comment]
This is a duplicate of #257 
We edited the above mentioned issue to ensure that it also covers this issue.

I therefore will close this as duplicate :)
