### ISSUE TITLE
Feature: macros / tags in overview

### ISSUE THREAD

**Issue by Hirbod** [zammad/zammad#917]
Hi,

I would like to be able to trigger macros while I'm in the overview. "Viagra, Led lights, 邮件群发平台，给您账号和密码 ??CHINESE WTF??? and get a bigger cock in 2 days" (no thanks I'm fine) are truely spam. But currently I need to click the Ticket and trigger "close and spam" inside the ticket.

Zammad currently forces me "too many" clicks. I would like to batch-close from overview and tagg it with "spam". Thanks

**Comment by dasvitamin** [comment]
In overviews u can drag n drop tickets to execute triggers, in our case its not always working though (sometimes the ui gets stuck and we have refresh the page). U can also tick/mark multiple tickets and than execute triggers by drag n drop.

**Comment by hanneshal** [comment]
Exactly, you can use macros via drag n drop in the overviews. 
Just select all your tickets and then drag them to the top.
