### ISSUE TITLE
[Feature request] Overviews by Group Access

### ISSUE THREAD

**Issue by k1ee** [zammad/zammad#918]
### Infos:

* Used Zammad version: 1.4
* Operating system: Ubuntu Server 16.04 LTS
* Browser + version: Chrome (56), Firefox 52.02

### Expected behavior:

* Give an Option, that some Overviews are only shown, if the agent has access to a group, which is filtered in the overview.

### Actual behavior:

* All Overviews are shown for all Agents

We have technicians, which are responsible for their own customers. For fast access, we created overviews which represent a customer (state: new, open, pending reminder, group: customer a). Now every technician sees the overview "customer a" but it is empty because the technician is not part of the group "customer a". I would like to configure that only technicians with groupaccess on "customer a" see the overview "customer a".

**Comment by dasvitamin** [comment]
I was searching for this option too, seems natural but could not find it, in the end we managed it by assigning each overview to the individual users.

**Comment by k1ee** [comment]
@dasvitamin How is that assignment possible?

**Comment by dasvitamin** [comment]
its the 3. option in "Edit: Overview":
![zammad_overview](https://cloud.githubusercontent.com/assets/4161217/24608830/831d0c98-1878-11e7-8c1c-f273a03c6397.png)

**Comment by k1ee** [comment]
Ahh ok, thanks! But group would be nicer :D

**Comment by martini** [comment]
Update: In newer Zammad version (which will be available the next months) we added an extend permission management. I guess you can handle this easier then.

**Comment by martini** [comment]
Closing for now...
