### ISSUE TITLE
Copy emails into zammad, don't delete from email provider

### ISSUE THREAD

**Issue by abenrob** [zammad/zammad#923]
### Infos:

* Used Zammad version: 1.4
* Operating system: xenial
* Browser + version: All (not browser related)

### Expected behavior:

* Import emails from email provider without permanently deleting them

### Actual behavior:

* Import emails into zammad, deleted from email provider forever

### Steps to reproduce the behavior:

* Add email account to Zammad

Not a bug, _per se_, but a very large inconvenience, and one that affects business...
We add email accounts as channels in Zammad. These are very important accounts - we have to receive these emails, and to ensure that we are not missing stuff. 
Having no way to leave these emails on the server is not ideal at all.

What would be the realistic possibility of copying instead of moving?

linked to: #243, #539

**Comment by martini** [comment]
Hi @abenrob 

I understand your intention. I seed different issues/questions:

1) What if the mailbox is full some day (no more incoming email)? Usually nobody is looking via IMAP in a mailbox anymore, after Zammad is used.
2) What do you want to do with the mails in the mailbox (you should only handle them via Zammad - because of history and so on)?

How should this be handled?

Thanks,

 -Martin

**Comment by Hirbod** [comment]
As Zammad has no responsive design or app, It's important for me to be able reading trough mails while I'm on the run. Therefore, I also made a mail forward to the ones zammad "can" grab, keeping the originals untouched. I would also prefer a "copy" modus, grabbing those mails which are marked unread into zammad an ignore those that are read.

**Comment by MartinBorg** [comment]
How about leaving the default behaviour as is (deleting emails from IMAP server), but have a configuration option to move emails instead of deleting them. If the folder name is set, mails are moved from INBOX to the folder. If the folder name is not set, delete emails.

**Comment by thorsteneckel** [comment]
Sorry for the confusion but the new main issue for this is #243. Please add your input (if still relevant) over there so it won't get lost.

**Comment by chasgames** [comment]
If you use Office365, what i've done is add a Rule to Copy emails to the Ticketting folder, which is specified for Zammad to look at.

Now your emails aren't deleted \o/
