### ISSUE TITLE
Set and initialize storage provider on zammad startup

### ISSUE THREAD

**Issue by volands** [zammad/zammad#924]
Hi,

hopefully a short question from my side: 

### Infos:

* Used Zammad version: 1.4.0
* Operating system: Dockerized (on Ubuntu 16 LTS)
* Browser + version: Firefox 52

### Expected behavior:

* It is possible to set and initialize the ```Store::Provider``` on zammad startup? I think this could be something in this direction: ```rails r "Setting.set('Store::Provider', 'DB')```? 

### Actual behavior:

* The default setting seems to be ```Store::Provider::FS``` but I want to use ```Store::Provider::DB```.

### Steps to reproduce the behavior:

* There seems to be a problem with that - if "DB" was previously selected and the (in my case) docker container gets rebuild and restarted, than zammad uses the default config "FS" instead of "DB". In the past that leads on my installation to problems with unprocessed mails - in this case I get the error message ```"ERROR: #<NameError: uninitialized constant Store::Provider::FS>"``` from ```/opt/zammad/log/scheduler_out.log```. If i set the storage provider again to "DB" via webinterface then everything works well again.

It will be great if you could provide a hint in this context.

Thanks and best regards,
Patrick

**Comment by martini** [comment]
Hi @volands 

1) You are right you can set any config option via rails console, e. g. `rails r "Setting.set('storage_provider', 'DB')"`

2) The correct name for the setting is `"storage_provider"`

3) Options are `File` or `DB`

4) Per default, `DB` is used

5) Your error message `"ERROR: #<NameError: uninitialized constant Store::Provider::FS>"` sounds like an old issue https://github.com/zammad/zammad/issues/428 - but should already be fixed (wrong was FS, it need to be File)

**Comment by volands** [comment]
Hi @martini

Thank you very much for you fast reply and explanations. Sounds great - I have now added this setting to my start config.

I am wondering why the mentioned error message occurs. It seems to be related to an older zammad version (before 1.4.0 which I use). Anyway, the setting / re-initalization of storage provider solves the problem for now.

Thanks and best regards,
Patrick
