### ISSUE TITLE
Create E-Mail Account fails 

### ISSUE THREAD

**Issue by Fosphatic** [zammad/zammad#925]
### Infos:

* Used Zammad version: 1.4.0
* Operating system: Debian 8
* Browser + version: FirefoxESR 52.0.1

### Expected behavior:

Test Mail verification success

### Actual behavior:

Can't create E-Mail account because e-mail verification fails. Fresh Debian and Zammad installation.
When i create an E-Mail account in backend Channels->E-Mail->New and fill the right data in it fails testing the email. Error message is can't find verification e-mail. I guess it is a problem that zammad tries to send to: <emailtrytest@znuny.com> that is what i see in the postfix log under /var/log/mail.log

### Steps to reproduce the behavior:
Fresh Debian install and Zammad creating e-mail adress in Backend fails.

**Comment by martini** [comment]
@Fosphatic that's correct. After IMAP & SMTP is working Zammad check if sending email to extern would also work. For this a try test is done.

The question is, why is this not working in your environment. You only have internal email addresses?

**Comment by Fosphatic** [comment]
Hallo Martini,

nein dass ist keine Adresse die bei dem Kunden eingesetzt wird. Ich hab keine Ahnung wo die her kommt. Ich hab erst nicht verstanden warum das schief geht, hab dann aber postfix mit smarthost eingerichtet und kann nun in der log sehen dass an diese Mail Adresse das ganze raus geht. Woher die kommt aber ist mir schleierhaft. Für das Ticketsystem hatte ich bei 1und1 support@unseredomain.de als E-Mail Postfach angelegt. Ich hoffe dass Du mir etwas auf die Sprünge helfen kannst. Ich würde liebend gerne mal Zammad ausprobieren das macht ein sehr sehr netten Eindruck für klein und mittelständische Betriebe genau das richtige denke ich. Nicht überladen und sehr schönes User Interface.

Viele Grüße

**Comment by Fosphatic** [comment]
There is no problem this ticket can be closed. The problem was from a domain fowarding nature. Sorry for bothering you.
