### ISSUE TITLE
Template assigned to all new tickets tabs

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#931]
### Infos:
* Used Zammad version: 1.4.0
* Operating system: Ubuntu 16.04.02
* Browser + version: Firefox 52.0.2

If I start writing a new Ticket (don't clicked create), start a second new one and want to use a template for this new, the template is used for both new Tickets and overwrite the text of my first started ticket.

Usually, I want to apply the template only to the visible ticket.

Greetings
tobibe

**Comment by martini** [comment]
Hi @tobibe 

thanks for report. It's fixed in develop, master and stable now.

Feedback is welcome!

 -Martin
