### ISSUE TITLE
API Docs missing article hash

### ISSUE THREAD

**Issue by gpkvt** [zammad/zammad#934]
The following example is given in the latest docs to create a new ticket:

```
POST /api/v1/tickets

{
 "title": "Help me!",
 "group": "Users",
 "article": {
   "subject": "some subject",
   "body": "some message",
   "type": "note",
   "internal": false
 },
 ...
 "note": "some note"
}
```

When I try to, I receive the following message:

```
{"error":"article hash is missing"}
```

I wasn't able to find any information about `article hash` in the docs or elsewhere.

**Comment by martini** [comment]
Hi @gpkvt 

more information about article hash you can find here https://docs.zammad.org/en/latest/api-ticket-article.html

We use it often, so can you show your payload? I guess there is somewhere an typo.

Thanks for feedback,

 -Martin

**Comment by martini** [comment]
Pls reopen on reply.

**Comment by gpkvt** [comment]
@martini: Sorry for the late reply. My payload was included in my first post. My understanding was and is that `/api/v1/ticket_articles` is the API to add content to existing tickets. I want to create a new ticket using `/api/v1/tickets`.

**Comment by Hotaruko** [comment]
Any news about that ? I still have the same issue when trying to create a ticket with the API

**Comment by Freddie-Banks** [comment]
Same issue here. Any news?

**Comment by Hotaruko** [comment]
After some test, it works when I use it with PHP but I'm not able to use it with my terminal, maybe I'm doing something wrong.

**Comment by martini** [comment]
@gpkvt You can use the payload (article: {}) for /api/v1/tickets too. So you will create a new ticket with an initial article.

Here an example curl call to create a ticket with an initial article.

```
curl -u test@zammad.com:test123 -H "Content-Type: application/json" -X POST -d '{"title":"Help me!","group": "Users","article":{"subject":"some subject","body":"some message","type":"note","internal":false},"customer":"email_of_existing_customer@example.com","note": "some note"}' https://xxx.zammad.com/api/v1/tickets
```

@Hotaruko @Freddie-Banks You need any more information?

**Comment by martini** [comment]
JFI: More curl examples you can find here https://docs.zammad.org/en/latest/api-intro.html#example-curl-requests-for-tickets-and-users

**Comment by Hotaruko** [comment]
@martini Work fine now, thanks.

**Comment by PaperinoBello** [comment]
> After some test, it works when I use it with PHP but I'm not able to use it with my terminal, maybe I'm doing something wrong.

Hi! can you past you php script please?? Thanks a lot!
