### ISSUE TITLE
Waiting Time widget shows only "0" 

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#935]
### Infos:

* Used Zammad version: latest, 1.4
* Operating system: macOS
* Browser + version: Chrome/Safari

### Expected behavior:

* The waiting time widget should show the actual waiting time/average waiting time.

### Actual behavior:

* It only shows 0 
![zammad_-_dashboard](https://cloud.githubusercontent.com/assets/804939/24752859/0eaba11c-1ad0-11e7-8e4f-6ec0fe153d62.jpg)

### Steps to reproduce the behavior:

* Open the dashboard

**Comment by citypeople** [comment]
+ 
Ubuntu 16.04
Zammad version: latest, 1.4

**Comment by rolfschmidt** [comment]
Duplicate https://github.com/zammad/zammad/issues/645
