### ISSUE TITLE
Keyboard shortcut prevents input of euro sign on German keyboard

### ISSUE THREAD

**Issue by johan12345** [zammad/zammad#937]
### Infos:

* Used Zammad version: 1.5
* Operating system: Windows 10
* Browser + version: Chrome 57

### Expected behavior:

* When using Ctrl+Alt+E or Alt Gr+E on a German keyboard in a text input field, the Euro sign (€) should appear

### Actual behavior:

* The user is logged out of Zammad (Ctrl+Alt+E is the keyboard shortcut for logging out)

### Steps to reproduce the behavior:

* Start to type an email response
* Use the Ctrl+Alt+E or Alt Gr+E shortcut

**Comment by martini** [comment]
Thanks for report. It's #656

**Comment by martini** [comment]
Just added an solution idea to duplicate issue. Feedback would be welcome! Thanks a lot!

 -Martin
