### ISSUE TITLE
Line Break from Gmail

### ISSUE THREAD

**Issue by aboferas** [zammad/zammad#939]
### Infos:

* Used Zammad version:  1.4
* Operating system: Centos 7
* Browser + version: Firefox 52.0.2

### Expected behavior:

* I expect the line breaks to be recognized for tickets opened/updated through Gmail email

### Actual behavior:

* The line break is being recognized when sending email from outlook but opening/updating ticket through Gmail cause zammad to not recognize the line breaks

### Steps to reproduce the behavior:

* Send email through gmail service
* compose a simple email with 5 lines separated by two line breaks from each other
* View the ticket through zammad system and you will find that there is no line breaks
* attached is a screenshot and the html file
<img width="538" alt="screen shot 2017-04-09 at 10 07 52 pm" src="https://cloud.githubusercontent.com/assets/27159036/24840406/3934238a-1d75-11e7-9a9a-94761bc91c7a.png">

[message.txt](https://github.com/zammad/zammad/files/908483/message.txt)

**Comment by rolfschmidt** [comment]
Hi @aboferas ,
this should be fixed with zammad version 2.0.0. Thank you very much for your report!

![grafik](https://user-images.githubusercontent.com/5445062/27962164-54ea19b6-6331-11e7-98c9-827bdfcb37b2.png)

Best regards,
Rolf
