### ISSUE TITLE
Hash  in Mysql DB

### ISSUE THREAD

**Issue by hamzehmohammadnia** [zammad/zammad#942]
Im having weird error inside Mysql DB, for instance when I see inside of tables, I see !ruby/Hash:...
as:
mysql> select * from permissions;
+----+----------------------------------+--------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+--------+---------------------+-------------------------+
| id | name                             | note                                                                                 | preferences                                                                                                     | active | created_at          | updated_at              |
+----+----------------------------------+--------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+--------+---------------------+-------------------------+
|  1 | admin                            | Admin Interface                                                                      | NULL                                                                                                            |      1 | 2017-04-10 09:57:27 | 2017-04-10 09:57:27.906 |
|  2 | admin.user                       | Manage %s                                                                            | --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess

or when I see users table:

mysql> select * from users;
7-04-10 09:57:29.793 |
|  2 |               1 | nicole.braun@zammad.org | Nicole    | Braun    | nicole.braun@zammad.org | NULL  | NULL         |      | NULL                                                                                             |       |      |        |            |        |      |      |         |         |    0 |        0 |      1 |      | NULL                    | NULL   |            0 | --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
tickets_open: 13
tickets_closed: 0
 notification_config: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  matrix: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    create: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      criteria: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        owned_by_me: true
        owned_by_nobody: true
        'no': false
      channel: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        email: true
        online: true
    update: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      criteria: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        owned_by_me: true
        owned_by_nobody: true
        'no': false
      channel: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        email: true
        online: true
    reminder_reached: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      criteria: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        owned_by_me: true
        owned_by_nobody: false
        'no': false
      channel: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        email: true
        online: true
    escalation: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      criteria: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        owned_by_me: true
        owned_by_nobody: false
        'no': false
      channel: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
        email: true
        online: true
intro: true
tickets_open: 1
     
---------------------------------------------------------------------------------------------------------------------------

My OS is Centos 7, Zammad 1.4.x, Ruby version is ruby 2.3.1p112, trying to use Zammad with Mysql. 
----------------------------------------------------------------------------------------------------------------------------------
Besides, I just found it when I check mysql status I see something weird:

mysqld.service - SYSV: MySQL database server.
Loaded: loaded (/etc/rc.d/init.d/mysqld; bad; vendor preset: disabled)
Active: active (running) since Mon 2017-04-10 10:37:33 UTC; 5s ago
Docs: man:systemd-sysv-generator(8)
Process: 22998 ExecStop=/etc/rc.d/init.d/mysqld stop (code=exited, status=0/SUCCESS)
Process: 23037 ExecStart=/etc/rc.d/init.d/mysqld start (code=exited, status=0/SUCCESS)
Main PID: 23275 (mysqld)
CGroup: /system.slice/mysqld.service
├─23063 /bin/sh /usr/bin/mysqld_safe --datadir=/var/lib/mysql --socket=/var/lib/mysql/mysql.sock --pid-file=/var/run/mysqld/mysqld.pid --basedir=/usr --user=mysql
└─23275 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib64/mysql/plugin --user=mysql --log-error=/var/log/mysqld.log --pid-file=/var/run/mysqld/mysqld.pid --socket=/va...

Apr 10 10:37:31 zammad4 systemd[1]: Starting SYSV: MySQL database server....
Apr 10 10:37:33 zammad4 mysqld[23037]: Starting mysqld: [ OK ]
Apr 10 10:37:33 zammad4 systemd[1]: mysqld.service: Supervising process 23275 which is not our child. We'll most likely not notice when it exits.
Apr 10 10:37:33 zammad4 systemd[1]: Started SYSV: MySQL database server..

My database.yml config is as below:
production:
adapter: mysql2
database: zammad
pool: 50
timeout: 5000
encoding: utf8
username: zammad
password:
host: 127.0.0.1

Im wodering why encryption of argon2 is  mentioned in the table like this... is it due to some errors?!
Regards,

**Comment by martini** [comment]
Dear @hamzehmohammadnia 

> Im having weird error inside Mysql DB, for instance when I see inside of tables, I see !ruby/Hash:...
as:

This is a ruby on rails behaviour. In rails you can store hash's or object in the database. rails is transforming this automatically.

So all is fine.

**Comment by martini** [comment]
> Im wodering why encryption of argon2 is mentioned in the table like this... is it due to some errors?!

argon2 is used for password hash
