### ISSUE TITLE
Lock-symbol more distinguishable

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#945]
### Infos:

* Used Zammad version: 1.4.x
* Operating system: n/a
* Browser + version: n/a

Please, can you render the lock symbol differently? Both "internal" and "public" look nearly the same!

#### Now:
set to public: ![screenshot-2017-04-12-18 43 33](https://cloud.githubusercontent.com/assets/26226303/24969244/5995482e-1fb0-11e7-99fc-98f405164da7.png)
set to internal: ![screenshot-2017-04-12-18 43 26](https://cloud.githubusercontent.com/assets/26226303/24969245/59969b7a-1fb0-11e7-8f9a-cd8c0ed471d3.png)

#### Suggestion:
set to public: https://image.freepik.com/free-icon/padlock-unlocked_318-40940.jpg (the hook points away from the lock)

**Comment by thorsteneckel** [comment]
This is fixed now and will be part of the next stable release - Thanks to @mrflix.

<img width="815" alt="screen shot 2018-12-04 at 09 43 03" src="https://user-images.githubusercontent.com/3873515/49571708-50928880-f93a-11e8-8ec2-ad680589459a.png">
