### ISSUE TITLE
Sometimes pending time is show as first ticket attribute

### ISSUE THREAD

**Issue by martini** [zammad/zammad#949]
Sometimes pending time is show as first ticket attribute in ticket screens.

**Comment by dennybresch** [comment]
![pendingtimebug](https://user-images.githubusercontent.com/3249687/27027786-f10b92ee-4f62-11e7-9b09-d91ca5912220.png)

**Comment by rolfschmidt** [comment]
Reproduce: 
- Prepare a closed ticket an hold a open tab.
- Logout
- Refresh the page F5
- Login
- Open the tab with the closed ticket
- Switch to pending reminder

**Comment by rolfschmidt** [comment]
Hi,
this bug is fixed in develop now.

Best regards,
Rolf
