### ISSUE TITLE
Article content partly not shown

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#950]
### Infos:

* Used Zammad version: 1.4.0
* Operating system: Ubuntu 16.04.02
* Browser + version: Chrome + FF 52.0.2

Sometimes, if we insert images to article by copy paste them, the article content is not fully shown even if we press "more"

![grafik](https://cloud.githubusercontent.com/assets/9305993/24999673/c2e3f54e-203e-11e7-8c45-fde8c884adea.png)

I copied the lorem ipsum paragraph three more times, but at "weniger anzeigen" the line is cutted in half and I miss two more lorem ipsum paragraphs.
The image we pasted is a screenshot nearly 1000 pixels wide and high and it's rezised for displaying. 
If I create the ticket, I have to reload zammad to get the "shortened" article.

If you look at the HTML content, the article is complete (as attached)
[content.txt](https://github.com/zammad/zammad/files/919098/content.txt)

Greetings
tobibe

**Comment by mrflix** [comment]
Turns out the see-more measurements didn't incorporate the height of images that still had to get loaded. Thanks for reporting tobibe!
