### ISSUE TITLE
More precise filesize

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#953]
### Infos:

* Used Zammad version: 1.4.x
* Operating system: hosted at zammad.com
* Browser + version: Vivaldi

### Expected behavior:

* File size should be quite accurate, i. e. human readable unit plus 1 decimal

### Actual behavior:

* File size is rounded up/down, which makes calculating too inaccurate

### Steps to reproduce the behavior:

* Upload any file. In my case a PDF with 1,6 MB
![screenshot-2017-04-15-225548](https://cloud.githubusercontent.com/assets/26226303/25066736/8dfa74a0-222f-11e7-8ce3-1510fee029a1.png)

* Zammad displays 2 MB
![screenshot-2017-04-15-230213](https://cloud.githubusercontent.com/assets/26226303/25066739/9e0942fe-222f-11e7-93fd-8415ded65dd5.png)

This is not exact enough. Especially if someone like me has subscribed to the commercial hosted Zammad where 10 megabtyes are allowed. You may think that only 5 of these attachments fit into the mail. In fact, you can send 6,25 attachments. In my opinion, the biggest unit (here MB) plus 1 decimal digit is the best choice – not too scientific for non-experts, but exact enough for calculating people.

**Comment by martini** [comment]
Is available in next version 1.5.
