### ISSUE TITLE
Enhancement: Option to Keep Mails on IMAP Server

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#955]
### Infos:

* Used Zammad version: 1.4.x
* Operating system: hosted at zammad.com
* Browser + version: n/a

### Expected behavior:

* It would be nice to have an option in the setting so that you can decide to keep original mails on the IMAP server.
* This concerns received mails and sent mails:
* * Receive: Maybe Zammad just marks mails as "read" just like any other mail client. Or it moves mails to another IMAP folder.
* * Sent: Zammad can save the mail on the IMAP server just like any other mail client.
* This might be useful in cases in which you are not sure if the mail was sent successfully. Then you could sneak a peek in your Thunderbird's or Roundcube's "sent folder".
* A company may have the need to do some analysis with IMAP+doveadm+cronjob and/or process the raw mails somehow further.
* Sorry, but I do not have a killer argument at the moment. But I try to describe it like this: When working in Zammad, you deal with tickets. Each ticket is a conversation between you and your customer. In Zammad you operate on a layer where you see "messages", not "mails". However, if Zammad would keep Mails on the IMAP server, then you can also handle those messages at the "mail layer". You can search them with familiar tools (doveadm, grep, search bar in mail client). You can backup them. You can re-import them into another ticket system or into a new Zammad (should you ever re-install it for any reasons). And you can compare a mail with what Zammad displays, if you have the feeling that Zammad hides something (certain mail headers, text formattings, etc.). I would feel more safe, if I now that I can access the messages on my own IMAP server AND in Zammad in an emergency, instead of Zammad-only.

### Actual behavior:

* Mails are deleted from IMAP server once slurped by Zammad.

**Comment by zabarabab** [comment]
My ideal solution to this problem would be an IMAP access to Zammad. Articles could be seen as IMAP-Mails, Tickets as IMAP-Threads, Tags could serve as IMAP-folders. 

But that would require a lot of effort. And in many aspects, Zammad is not designed for that kind of useage. E.g. deleting articles or tickets is not allowed.

**Comment by odit** [comment]
Setup a mailbox A for Zammad and SMTP, in A mailbox set Auto-Forward all incoming email to B & C, e.g. Zammad get all mail from B mailbox, C mailbox for other analysis. this is easy way?

**Comment by eliasp** [comment]
See also: https://github.com/zammad/zammad/issues/243#issuecomment-255338797

**Comment by AND51** [comment]
@odit, of course I thought about the solution to forward mails. But this is not good. Depending on the method you use for forwarding, you can accidentally manipulate the mails. If your forwarder adds "Fwd" to the subject, or of the mailserver adds another "Received"-Header, this is already a manipulation. However, you prefer the original mails.

@eliasp, thanks for your comment from  #243! At the moment, I think setting a flag is the best way.I'd prefer a custom flag, because the SEEN-flag can be changed too easily. Imagine you want to browse through the original mails in Roundcube. Too easiliy you click a mail which is marked 'read' then. Or the other way around: You mark a mail as UNSEEN. Possibly, this would make Zammad import the same old mail, so you'll end up with 2 tickets.
Another solution might be, if Zammad compares each new/unseen mail with its own database to see if a particular mail has already been imported. So the flags wouldn't matter.

@zabarabab, I like your idea of Zammad providing its own IMAP interface. However, a mail that has already been imported and destroyed from the original IMAP server. The point is that you way want to archive the mails **before** they are processed by any other instance.

**Comment by MartinBorg** [comment]
I personally would prefer, if Zammad could just move processed emails to some IMAP folder, but I could also live with the SEEN flag approach. The current method of deleting processed emails compulsory is not very nice.

**Comment by thorsteneckel** [comment]
Sorry for the confusion but the new main issue for this is #243. Please add your input (if still relevant) over there so it won't get lost.

**Comment by msplival** [comment]
Hi. The original Enhancement mentioned storing Sent emails into IMAP folder too, but this is not implemented, as far as I can see?
It would be neat if Zamaad could just use the Sent folder of the configured IMAP account to put there all the emails it sends out.

**Comment by imbehind** [comment]
It would me even more neat if Zamaad could just any IMAP folder configured in backend (i.e. "zammad_sent") to store sent emails.

It is very important feature if the support offered is official one, done under government regulations, especially in EU where customer protection laws dictate that all correspondence must be retained for at least 3 years or similar.

**Comment by martini** [comment]
> Hi. The original Enhancement mentioned storing Sent emails into IMAP folder too, but this is not implemented, as far as I can see?

@msplival That's correct. Currently all mails are marked as read and keep stored on the mail server (by the way, customer are complaining about flooded mailboxes and the mail admin has to empty the Zammad mailboxes anyway to get new mail in :(). Zammad is not storing send emails or event notes in the IMAP storage. Currently there are no plans to store sent emails, notes or notifications in the IMAP storage because you can access all via REST directly from Zammad.

> It is very important feature if the support offered is official one, done under government regulations, especially in EU where customer protection laws dictate that all correspondence must be retained for at least 3 years or similar.

@imbehind JFI: Zammad is revision-proof (all changes of a ticket is tracked and shown in the ticket history - who did the change, when did the change happen and what was the previous and the new value). So EU law is no problem.
