### ISSUE TITLE
Suggestion: More Efficient Use of Ticket Area

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#957]
### Infos:

* Used Zammad version: 1.4.x
* Operating system: hosted at zammad.com
* Browser + version: Vivaldi 1.8

First, consider this a suggestion or question. This issue depends on one's personal prefences and from the opinions of the Zammad team and other people who might tell us their opinion here.

In my opinion, Zammad could use the ticket area much more efficient. The tickets should be rendered wider. Look at this screenshot. The blue squares are unused and blank space. Even flipping the right sidepane away does not make the messages wider. Why do we have 16:9 widescreen monitors then?

![screenshot-2017-04-16-010438](https://cloud.githubusercontent.com/assets/26226303/25067397/9c4332be-2242-11e7-8b5e-567699138ca1.png)

Pro: The design looks highly slick and clean.

Con: At every longer message you must click "show more". This would not be neccessary, if the unused area would be used, too. More space allows to render more text. Especially when you have to work on an older ticket, where you must re-read the whole conversation to get familiar with the topic again, you must click "show more" at every message. Other cases might be for example, if you are a technical company (hosting provider) and you share programming code with your customers. Messages can get large very quickly.

I don't know your texts and use cases. But in my Zammad, tickets and messages are longer on average. It reduces my efficiency when reading whole conversations and clicking a lot of "show more" links. In other applications like Roundcube/Rainloop, YouTrack, Confluence, etc. you do not have to click "show more" every time. Instead, you get the full text immediately.
Therefore, I would like to hear other opinions. I do not want this to be implemented, because I am the only one. I want this to be implemented if other people like this idea and it Zammad-team approves it. So, what are your experiences and preferences?

**Comment by martini** [comment]
@mrflix any feedback?

**Comment by mrflix** [comment]
Hey André. Thanks for the feedback! The limited width is based on the theory that too long lines make the text harder to read. Motivated by your post I reevaluated that idea and turns out wide lines are not that big of a problem. If I compare it with macOS Mail there is no limit on the width and I never really minded. Coincidently one of our colleagues also pointed out the big white space on the sides. I don't want to make a quick shot here because the design has to stay balanced but I'll try it out and maybe it will make it into a future release.

**Comment by mrflix** [comment]
Okay so played around a bit. Not limiting the width creates very ugly results on very wide screens (2560px wide !!!):
![img_27042017_115656_0-1](https://cloud.githubusercontent.com/assets/60777/25479338/c45bdf5c-2b44-11e7-9168-2675c2850648.png)
So we settled for a max-width of 1080px because that still looks good on a very wide screen. Previously it was 800px. So a win of 280px or 35%!

**Comment by AND51** [comment]
Hey Felix,

thank you for your reply. I'm glad  you, your colleague and others agree with me :-)

I'm not a designer, but I do understand that one cannot change the layout arbitrarily. The Gesamtbild has to stay balanced, as you said and that's right. If neccessary, we can do another change in the future. But for now, let's go with the +35% and see how it feels!

**Comment by AND51** [comment]
> The limited width is based on the theory that too long lines make the text harder to read. Motivated by your post I reevaluated that idea and turns out wide lines are not that big of a problem. If I compare it with macOS Mail there is no limit on the width and I never really minded.

I've heard of that theory, too. That's the reason why newspapers prefer colums over the whole width. On the one hand, this is a smart idea. On the other hand, I don't like to be told how I have to work. There are two groups. Those who agree and those who don't. Maybe the best way is to implement not only function-based settings, but also a settings-page where you can configure the layout/fonts/theme/colours/etc. But that's another topic. You might discuss this internally and open a ticket yourself if you wish.

But I want to point out another big issue. Newspapers do also use serif*, because the additional, fine lines around the letters help you to stay in the same line while reading. However, in the web I prefer sans-serif* mostly. I also wished that Zammad would use sans-serif, too. But currently, you cannot configure this oficially. You see, there are always two groups. I don't know how to solve this general conflict – best idea I have is to let users configure it for themselves.

*) CSS nomenclature

**Comment by mrflix** [comment]
I do agree that there is a rich variety in taste making it hard to find a consensus. We'll think about adding visual settings.

Regarding serif – the reason serif font's were not popular on the web for a very long time is that serifs don't look good on coarse-grained computer screens. This is shifting now with pixel dense screens becoming the norm. However, Zammad uses Mozilla's [Fira Sans](https://github.com/mozilla/Fira) which **is** a sans-serif font 😉  (with a fallback to the system sans-serif font, see https://github.com/zammad/zammad/blob/develop/app/assets/stylesheets/zammad.scss#L47)
