### ISSUE TITLE
Selecting "overviews" in Chrome for iOS on iPad does not work

### ISSUE THREAD

**Issue by babakkazemi** [zammad/zammad#959]
### Infos:

* Used Zammad version: 1.3.0, 1.4.0, 1.5.0, 1.6.0
* Operating system: iOS 10.21
* Browser + version: Chrome 57.0.2987.137

### Expected behavior:

* selecting "overviews" should open "overviews" window

### Actual behavior:

* "overviews" window is opened for a split second, then dashboard is loaded again. "Overviews" is only then shown, when opened in new browser tab

### Steps to reproduce the behavior:

* tap "overviews" in Chrome for iOS

**Comment by rolfschmidt** [comment]
Reproduced on iphone. No reproducible on Google Pixel.

**Comment by babakkazemi** [comment]
Interestingly, it works perfect on safari for iOS. Also works flawlessly on Chrome for Android on my One+ One (CyanogenMod 12.1). Seems to be a Chrome/iOS issue

**Comment by thorsteneckel** [comment]
Hi @babakkazemi - mobile is currently not supported officially. The matching issue is #223

**Comment by martini** [comment]
JFI: Should already work in Zammad 2.0 and higher. Was a CSS issue.
