### ISSUE TITLE
Create a new Laguage Pack

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#963]
### Infos:

* Used Zammad version: 1.4
* Operating system: Ubuntu 
* Browser + version: 

### Expected behavior:
I intend to create a new language pack (*.yml ) and put it as default zammad language. Any advise?
* 

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by mmojadad** [comment]
Need help to add new language...

**Comment by thorsteneckel** [comment]
Please move (technical) questions over to our [community board](http://community.zammad.org/). Closing now.
