### ISSUE TITLE
Edit login footer content

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#964]
### Infos:

* Used Zammad version: 1.4
* Operating system: Ubuntu 
* Browser + version: 

### Expected behavior:
How could i edit login page footer? I mean "Powered by Zammad" on login page.

* 

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by martini** [comment]
Hi @mmojadad 

currently you only can edit the web app templates via file system https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/views/login.jst.eco#L83

After changing you need to precompile the app again:

`zammad run rake assets:precompile`

or installed via source as Zammad user:

`rake assets:precompile `

Restart Zammad and the changes will get reflected.

 -Martin

**Comment by mmojadad** [comment]
@martini Thank you Martin! #
