### ISSUE TITLE
external Two Factor Authentication (2FA)

### ISSUE THREAD

**Issue by cornelinux** [zammad/zammad#965]
I would like to see two factor authentication in zammad preferably with an external authentication service. I am using privacyIDEA (https://github.com/privacyidea/privacyidea) to authenticate my users with a second factor.

The verification of the 2nd factor is done via a REST API by simply issuing one request.
 (http://privacyidea.readthedocs.io/en/latest/modules/api/validate.html#post--validate-check).

From a first glance we would have to add another class in lib/auth? (https://github.com/zammad/zammad/tree/develop/lib/auth)

Is there additional information on how to add another (3rd party) auth source?

**Comment by MichelZ** [comment]
I'd like to see support for DUO SECURITY.

**Comment by cornelinux** [comment]
There are basically two ways to add 2FA here. 

# External 2nd Factor

The first factor/passwort would be verified by zammad just the way it is done at the moment. If zammad authenticated the user successfully with the password, it would call a registered/configured class which implements *only* the second factor.

This class would take care of displaying the UI for entering the second factor and it would take care of verifying the second credentials.

Such a class could have an "authenticate" method, which would receive the previously entered username and "everything else" a.k.a. the second factor.

Such an implementation would probably be great for adding 2FA via DUO. It has some drawbacks when using it with authentication systems run on premise like privacyIDEA, sich such systems often take care of both/two factors and not only the second one.

The 2FA API of ownCloud is implemented that way.

# External two factors

Another possibility would be to hand the *complete* authentication to the registered 2FA class or plugin/module. zammad would pass the complete handling of the authentication to this 3rd party module and the module would only return the information "a user 'hans' has authenticated successfully" and zammad would not care about how this happened.

The class/plugin/module could then handle both two factors. Systems like privacyIDEA can do such things, they manage a password of a user or a token PIN and the physical second factor. THe interesting thing with this approach is, that the complete controll is passed to the module and thus more complicated  authentication workflows like challenge response with SMS; Email or U2F are easier to implement.

An example would be the authentication in OTRS (sorry to mention that ;-).
https://github.com/privacyidea/privacyidea/tree/master/authmodules/OTRS
In this case the 2FA module does not even provide additional UI components but uses the existing login dialog. It just takes everything the user entered, passes the contents from the password field to the 2FA system and the 2FA system is capable of verifying the two factors in this password field (classical approach: user enters password+OTP in one string)

If anyone needs any additional input, just call me @cornelinux

**Comment by lobiman** [comment]
DUO is to expensive. Better to implement Microsoft Azure's MFA including Azure AD for SSO.

https://azure.microsoft.com/de-de/pricing/details/multi-factor-authentication/

**Comment by cornelinux** [comment]
This is a bad idea! Do not implement DUO and do not implement Azure. You do not want to have a vendor lockin in an open source software.
Implement a decent authentication stack to be able to connect to 3rd party solutions. Then this can either be DUO or Azure or Whatever.

There sill does not seem to be any documentation about how to add 3rd party auth.

**Comment by MichelZ** [comment]
Of course, whatever you do should not lock you in...

**Comment by Tsuroerusu** [comment]
How about the U2F standard? That way, I could use something like a YubiKey to log into Zammad?

**Comment by cornelinux** [comment]
Again. Zammad should not do U2F. They should provide an API to plugin the second factor. This could be U2F as one choice. Could be WebAuthN. Could be privacyIDEA, DUO or even RSA SecurID. This is the way you do such things.
@martini how can we start working on such API?

**Comment by lfxch** [comment]
If you do 2factor auth, in most cases you have a an appliance or at least a proxy in front of zammad. E.g a Netscaler or Vulture SSO Appliance or something similar. Those appliances support Form Based authentication, so you can configure them to recognize the login form, auto submit it and you're done.
This works with nearly any web applications and is very easy to implement.

However, i found no way to get this working with zammad because there is no way to recognize the login form and there is also no way to find out if the login was successful.

So the most easy to get most 2factors working with zammad would be to implement the following:
- proper url for the login form (e.g. /login, because /#login does not work, everything after # is just on the client/browser)
- proper authentication url where you can send username & password and replies in in a proper way (http 200 or 302, auth successfull, http 403.1, not authorized)

This solution would be vendor independent, allowing any sso appliance to add 2factor or sso to zammad.

**Comment by MrGeneration** [comment]
Regarding the Login-URL: This can't change, because of the way zammad works.
#blah changes layers and stuff, that would be a quite big change to the chore.

**Comment by cornelinux** [comment]
I assume the ``#login`` is a marker for the single page application.

I think zammad needs to open/document its authentication stack, then everyone could do everything just as he pleases.
@lfxch is right about netscaler, this is cool. But not everbody has a high sophisticated enterprise, proprietary, closed source SSL VPN Gateway.
So I think zammad as an open source project should provide ways to play nice with other open source solutions. 

Well there is a way at the horizon. Zammad supports openID connect. OpenID Connect IdP can be keycloak. The 2FA system [privacyidea](https://github.com/privacyidea/privacyidea) now gets [a provider for keycloak](https://github.com/privacyidea/keycloak-provider). But this way you would have to install 3 components. This is fine if you haven them anyways, but comes with a rather steep learning curve.

**Comment by lfxch** [comment]
well, a second possibility is to add a header, e.g. "Authenticated: true" or similar.

the netscaler was only an example, take a look at https://www.vultureproject.org, they are doing the same and this is opensource.

**Comment by lobiman** [comment]
Maybe the new Standard Webauthn is a solution. https://webauthn.guide/

**Comment by MrGeneration** [comment]
Hey,

just as a short feedback on this issue as we've talked about this.
We've decided against implementing external 2 factor providers as of now.

What we agree on is to provide Hardware token and Software token (e.g. Google Authenticator) support to Zammad.
I'll be creating a new issue for that and link it later on.

This will take us some time, ETA as always unknown.

**Comment by benma** [comment]
> What we agree on is to provide Hardware token and Software token (e.g. Google Authenticator) support to Zammad.
I'll be creating a new issue for that and link it later on.

@MrGeneration great to hear. Did you create that issue? Is there any progress? 2FA is a sorely needed feature. Thanks!

**Comment by MacroPolo** [comment]
Agreed, the lack of MFA in public facing services is becoming a compliance issue for many and _will_ push people to look at alternative solutions.

**Comment by karatekaneen** [comment]
For us a simple TOTP would fill our needs so that we can link Google Authenticator to the service. 

IF I were to contribute this, does anyone know where to start?

**Comment by MrGeneration** [comment]
I wouldn't recommend touching this topic right now as it's still not specified yet.
We'll hopefully update this issue soon.

**Comment by ryc76** [comment]
Hi, this is definitely a needed feature. 2FA is practically standard now and all sorts of accreditations are making it mandatory. We've had to block user logins and only use email for compliance reasons.

**Comment by MrGeneration** [comment]
I'm limitting this issue to reduce further comments as like "need this". It doesn't help the pace of this issue. It's coming when it's ready.

**Comment by dominikklein** [comment]
We created the issue https://github.com/zammad/zammad/issues/4595 for dealing with the two-factor authentication (in the first step with a software token).

Currently, it's not planned to deal with an external two-factor provider.
