### ISSUE TITLE
Getting Started {"error":"Argon2::ArgonHashFail"}

### ISSUE THREAD

**Issue by nnlt** [zammad/zammad#966]
### Infos:

* Used Zammad version: 1.4.0
* Operating system: Ubuntu 16.04.02 x64
* Browser + version: Chrome 57.0.2987.133 (64-bit) on Mac OS

### Expected behavior:

* New user account should be created on page /

#getting_started/admin

### Actual behavior:

* After clicking on the "Create" button I get the following error message
`StatusCode: 500`
`{"error":"Argon2::ArgonHashFail"}`

[production.log.txt](https://github.com/zammad/zammad/files/934142/production.log.txt)

**Comment by thorsteneckel** [comment]
Hi @nnlt - seems there's something (relevant) missing in your log file:

```
E, [2017-04-19T11:48:32.300345 #6196] ERROR -- : Argon2::ArgonHashFail
E, [2017-04-19T11:48:32.300839 #6196] ERROR -- : ["/opt/zammad/vendor/bundle/ruby/2.3.0/gems/argon2-1.1.1/lib/argon2/ffi_engine.rb:59:in `block in hash_argon2i_encode'", "/opt/zammad/vendor/bundle/ruby/2.3.0/gems/argon2-1.1.1/lib/argon2/ffi_engine.rb:55:in `initialize'", "/opt/zammad/ve$
```

As you can see the `/opt/zammad/ve` is cut off.

**Comment by nnlt** [comment]
@thorsteneckel Sorry! Updated the file.

**Comment by thorsteneckel** [comment]
Hi @nnlt - seems the Argon2 gem we are using has an issue with the used password of yours. Can you verify the same behavior with the password 'test' ? If so there is something deeper wrong. Can you check if your Setting `application_secret`is filled? You can do this via using the [using the rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammads-rails-console) and entering `Setting.get('application_secret')`. Please do not post your secret anywhere! Just check if it has a long cryptic value 🤓

**Comment by nnlt** [comment]
@thorsteneckel Tried different passwords, including `test`  - always leads to the same outcome. `application_secret` is filled.

**Comment by thorsteneckel** [comment]
Bad news 😞 Your issues comes deep out of the [ruby-argon2 gem](https://github.com/technion/ruby-argon2). The error is raised [here](https://github.com/technion/ruby-argon2/blob/e123a64f3ab2fc6af7ca951311252ac66c8d928a/lib/argon2/ffi_engine.rb#L59). This file is a [wrapper](https://github.com/technion/ruby-argon2/blob/e123a64f3ab2fc6af7ca951311252ac66c8d928a/lib/argon2/ffi_engine.rb#L8) around the [argon2_wrap C lib](https://github.com/technion/ruby-argon2/blob/e123a64f3ab2fc6af7ca951311252ac66c8d928a/ext/argon2_wrap/argon_wrap.c). Which is way out of our scope.

You might want to run this little ruby test script on your machine:

```ruby
require 'argon2'

secret = 'TEST'

argon2 = Argon2::Password.new(secret: secret)

p argon2.create('test')
```

Just name it `argon2_test.rb` and put it in your Zammad folder. After that execute it via `bundle exec ruby argon2_test.rb`. This should raise the `Argon2::ArgonHashFail` error again. Right?

Seems to me that something in your Zammad installation went wrong. Did you install Zammad from source or out of a package of ours?

**Comment by nnlt** [comment]
Yes, unfortunately the script raises the error again. 

`/opt/zammad/vendor/bundle/ruby/2.3.0/gems/argon2-1.1.1/lib/argon2/ffi_engine.rb:59:in `block in hash_argon2i_encode': Argon2::ArgonHashFail (Argon2::ArgonHashFail)
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/argon2-1.1.1/lib/argon2/ffi_engine.rb:55:in `initialize'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/argon2-1.1.1/lib/argon2/ffi_engine.rb:55:in `new'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/argon2-1.1.1/lib/argon2/ffi_engine.rb:55:in `hash_argon2i_encode'
	from /opt/zammad/vendor/bundle/ruby/2.3.0/gems/argon2-1.1.1/lib/argon2.rb:21:in `create'
	from argon2_test.rb:7:in `<main>'`

I installed Zammad on a fresh Ubuntu server using the package and followed the instructions [here](https://docs.zammad.org/en/latest/install-ubuntu.html)

**Comment by thorsteneckel** [comment]
The strange part is that the Zammad package is batteries included - so everything is ready to setup and does not depend on your local system or installs anything afterwards. This means that others using the same package should have the same issue but there is nobody else complaining 🤔 

Honestly I'm not sure how to help you with this. Could you try the installation from source and/or reinstall the whole system again?

**Comment by nnlt** [comment]
I tried to install it on a Debian based system, same error. Maybe the error has something to do with DigitalOcean. I'm gonna try the installation from source next and will report.

Thanks!

**Comment by thorsteneckel** [comment]
Good luck with that! Would be great to hear how it went.

**Comment by nnlt** [comment]
Decided to give it a try on an AWS Ubuntu instance - works flawless! Seems so be related to DigitalOcean.

**Comment by thorsteneckel** [comment]
Thanks for the update! Closing for now. Glad it works for you now.

**Comment by arturojain** [comment]
I have the same error on DigitalOcean.

**Comment by arturojain** [comment]
Getting same error on Linode.

**Comment by thorsteneckel** [comment]
JFI: I just tested this on latest CentOS and Ubuntu droplets on DigitalOcean and had no errors 🤔

**Comment by sarment0** [comment]
I have the same problem with Digitalocean Ubuntu droplet.

**Comment by thorsteneckel** [comment]
Two weeks ago I wasn't able to reproduce this 🤔 I have to take a look myself. But I need access to your droplet. If possible please contact us via support@zammad.com and provide the issue number and my name. I will provide my public key for passwordless authentication.

**Comment by Devmaticz** [comment]
same on Azure !!

**Comment by MrGeneration** [comment]
Please don't recycle closed issues for problems. If you're experiencing a bug, please create a new issue.

If you need technical assistance, please go to our community: https://community.zammad.org
