### ISSUE TITLE
Access to my own Tickets (where I'm customer of) in a Group im not Agent

### ISSUE THREAD

**Issue by maege** [zammad/zammad#967]
### Infos:

* Used Zammad version: 1.4.x
* Used Zammad installation source: package
* Operating system: Debian
* Browser + version: Chrome

### Expected behavior:

* I see all my Tickets and also all Tickets from the group(s) i'm a member of.

### Actual behavior:

* If i have agent role to a single group (group A), and create a ticket (as "customer") to an other group (group B). I dont't see my own Tickets.
* I also don't have access to my old Tickets in a other Group than Group A.

### Steps to reproduce the behavior:

1. Give a user (User A) Agent role for a group (not your default incoming mail group)
2. Send a Mail to Zammad from this user. (The Ticket will be created in the default group) or open Ticket via Web.
3. The User A does not have access to his own ticket.

Thanks for your great work!

Edit by Zammad / @MrGeneration : 
Zammad should also close the tab, if creating a ticket into a group you have no access to. This refrains Zammad from showing error messages because of missing permissions.

**Comment by hagen3000** [comment]
I agree. It would be nice if the agent could see his own tickets. Regardless of the group.

**Comment by martini** [comment]
++

**Comment by chrklo** [comment]
we need this feature too.

**Comment by GregMighty** [comment]
This would be great for us as well :))))

**Comment by chrklo** [comment]
any news on this topic?

I tried to get it working with the new role feature in 2.0 - but without success.

**Comment by thorsteneckel** [comment]
Being a customer and agent at the same time is currently not supported. There are a lot of cases we have to cover which will take some time. We will give you an update as soon as we will work on them.

**Comment by Wardrop** [comment]
Also eagerly awaiting the ability for an agent to also be a customer. For most internal help desk systems, this is requirement with no real workaround. We have power users responsible for providing support for certain products so therefore need to be agents, but these same users also need to be able to raise tickets of their own for other systems or for general IT support.

**Comment by Charburner** [comment]
Hey guys,

since your last reply was about 6 months ago, would you mind to give us an update or tell us if this requested feature is anywhere near the top of your to do list? :-)

Have a nice day

**Comment by NvL-WEAP** [comment]
We're eager to get this feature as well.

Kind regards

**Comment by MrGeneration** [comment]
Please simpy upvote this on original post and don't comment here, as it creates a lot of noise to those who watch this. Locking conversation for now.

**Comment by MrGeneration** [comment]
Just a small follow up:

By now we know the costs of this project and that we want to start integrating this.
But: We need your help - this feature is quite expensive, so we're hoping to find contributors willing to help.

You can find further information in our community post:
https://community.zammad.org/t/feature-allow-agents-being-customer-in-other-groups-they-dont-have-access-to/2120
