### ISSUE TITLE
Mail processing error (with broken mail headers)

### ISSUE THREAD

**Issue by stagprom** [zammad/zammad#969]
### Infos:

* Used Zammad version: 1.4 - 1.5
* Used Zammad installation source: (source, package, ...) source
* Operating system: Ubuntu 16.04
* Browser + version: Safari 9.3

### Expected behavior:
Mails should be processed with out errors. At least in case of errors there should be a notice
to the admins and the emails should not be deleted from inbox.

### Actual behavior:

`"ERROR: Can't process email, you will find it for bug reporting under /opt/zammad/tmp/unprocessable_mail//325ba7960aa3912db7de18df08558f52.eml, please create an issue at https://github.com/zammad/zammad/issues"
"ERROR: #<NoMethodError: undefined method `sub' for nil:NilClass>"
/opt/zammad/app/models/channel/email_parser.rb:431:in `rescue in process': #<NoMethodError: undefined method `sub' for nil:NilClass>["/opt/zammad/app/models/channel/email_parser.rb:711:in `raw_value'", "/opt/zammad/app/models/channel/email_parser.rb:87:in `rescue in block in parse'", "/opt/zammad/app/models/channel/email_parser.rb:80:in `block in parse'", "/opt/zammad/app/models/channel/email_parser.rb:77:in `each'", "/opt/zammad/app/models/channel/email_parser.rb:77:in `parse'", "/opt/zammad/app/models/channel/email_parser.rb:437:in `_process'", "/opt/zammad/app/models/channel/email_parser.rb:413:in `process'", "/opt/zammad/app/models/channel/driver/mail_stdin.rb:26:in `initialize'", "/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `new'", "/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `<top (required)>'", "/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `eval'", "/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `<top (required)>'", "/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require'", "/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'", "/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:90:in `runner'", "/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'", "/var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'", "/opt/zammad/bin/rails:4:in `require'", "/opt/zammad/bin/rails:4:in `<main>'"] (RuntimeError)
	from /opt/zammad/app/models/channel/email_parser.rb:413:in `process'
	from /opt/zammad/app/models/channel/driver/mail_stdin.rb:26:in `initialize'
	from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `new'
	from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `eval'
	from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /opt/zammad/bin/rails:4:in `require'
	from /opt/zammad/bin/rails:4:in `<main>'` 

### Steps to reproduce the behavior:

cat tmp.PjIykv2CdO | rails r 'Channel::Driver::MailStdin.new(trusted: true)'

mail as raw file:
[tmp.PjIykv2CdO.txt](https://github.com/zammad/zammad/files/938692/tmp.PjIykv2CdO.txt)

**Comment by martini** [comment]
Hi @stagprom 

the mail headers are broken (in this case X-Brightmail-Tracker).

A fix is on the road...

 -Martin

**Comment by martini** [comment]
It's fix in stable now (Zammad now process the emails invalid headers too). Thanks for your help/support! ❤️
