### ISSUE TITLE
Make our changes NOT being removed by an update

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#972]
Will be good if zammad support make our changes NOT being removed by an update

For example :

From our zammad installation folder, in the folder “app” there be a folder name “local”.

This Folder create to allow us to put our modified files here so they won’t be overwritten when we update our zammad.
I need to customize zammad default css in many parts and worry about  remove on next update automatically.

**Comment by hanneshal** [comment]
See my answer in: https://github.com/zammad/zammad/issues/973
