### ISSUE TITLE
Support Google fonts

### ISSUE THREAD

**Issue by mmojadad** [zammad/zammad#973]
Will be good if there be an options in admin area to allow us  modify zammad css and support web fonts ( google fonts ).

**Comment by hanneshal** [comment]
Hi,

you can always modify the Zammad CSS within the application folder. There is a "custom" folder within app/assets/stylesheets/ which also includes a small readme.

I know you are asking for a feature to enable CSS editing within the admin interface, which is a good idea, but we don't have any resources available for this in the nearby future.

regards

Johannes
