### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#974]
Hey there,

just got Roles working. But it seems to me not the Role addon everyone needs.

In OTRS i have a Role called "1st. Level" and this Role is mapped to some Groups(Queues). 

The Zammad Role Feature gives me some extra Features wich are missing in OTRS. I can specify a miniAdmin. But there is no ability to map some groups to this Role. 

Especialy with the LDAP Integration there is a need to map a LDAP Group to a Role and this role gives the users some Admin features and Group mappings. 

So thats my thought of a role system. But maybe i'm thinking the wrong way.

**Comment by rolfschmidt** [comment]
Hi @Julian0o ,
in the current development state of zammad a table with group relations is available in the role creation. Is this issue maybe obsolete?

![grafik](https://user-images.githubusercontent.com/5445062/27961471-0627391e-632f-11e7-99d7-f786859a65ca.png)

So it looks like it is possible to define specific groups for the role you want to create. Also @martini told me that it is possible to sync a role relation to a zammad user from ldap.

Could you please provide us more information about the issue?

Best regards,
Rolf

**Comment by rolfschmidt** [comment]
Hi @Julian0o ,
please reopen on feedback. Thanks!

Best regards,
Rolf
