### ISSUE TITLE
Exception in OTRS Import

### ISSUE THREAD

**Issue by MrDigit** [zammad/zammad#975]
Hello,

I am testing the new Zammad 1.5 version. I've tried to import OTRS data.

First the good news: My problems described in Issue #368 seem to be gone. Memory consumption on zammad-side is quite lower now when importing ~6000 tickets. Users are also correctly imported.

Here my new problem(s): Seconds after starting the import the progress stucks, in production.log the following error can be found:
   UnprocessableEntity, 'Minimum one user needs to have admin permissions.'

Dirty hack: Commenting out "raise Exceptions::UnprocessableEntity, 'Minimum one user needs to have admin permissions.' if count < 1" in app/models/user.rb and import works.

Best regards
  MrDigit

**Comment by rolfschmidt** [comment]
Hi @MrDigit 
thank you very much for your report! Problem should be fixed now in develop, stable and master.

-Rolf
