### ISSUE TITLE
Installation of zammad 1.5 on Centos 7

### ISSUE THREAD

**Issue by MrDigit** [zammad/zammad#976]
Hello,

today I installed zammad 1.5 RPM package on CentOS 7. It took some time to get it working, here my experiences:

1) The Post-Install script doesn't work correctly if "which" is missing. The which RPM should be a dependency of the zammad RPM.

2) I had some problems getting postgresql and zammad working. Here the error output of the Post-Install script: 

```
# Creating postgresql bootstart
Created symlink from /etc/systemd/system/multi-user.target.wants/postgresql.service to /usr/lib/systemd/system/postgresql.service.
# Restarting postgresql server
# Creating zammad postgresql db
createdb: database creation failed: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)
HINT:  Use the same encoding as in the template database, or use template0 as template.
# Creating zammad postgresql user
CREATE ROLE
# Grant privileges to new postgresql user
ERROR:  database "zammad" does not exist
# Updating database.yml
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "zammad" does not exist
```

My solution: Stopping postgresql, deleting data directly (here: /var/lib/pgsql/data), initialize DB with UTF8: initdb -E UTF8 -D /var/lib/pgsql/data/

Afterwards the post-install script worked.

Best regards
  MrDigit

**Comment by monotek** [comment]
I guess you're using a non UTF8 locale setting.
Whats the output of the command "locale"?
On CentOS locale can be set via: "localectl set-locale LANG=en_US.utf8"

**Comment by MrDigit** [comment]
Thanks for the quick answer.

Source of image is https://openvz.org/Download/template/precreated
(centos-7-x86_84-minimal)

There which is not installed by default.

Currently my locale is "C". Good possible that changing to UTF8 solves the second problem without manually (re)creating the DB.

**Comment by monotek** [comment]
As this is not an official CentOS image we won't support it.

**Comment by monotek** [comment]
I tried it today with a fresh install of CentOS minimal. 
Which command was installed.
Added it anyway in https://github.com/zammad/zammad/commit/365e691587c75c0fbce3f8f6c74cc93180e9f089

**Comment by MrDigit** [comment]
great, thanks for the fast feedback.
