### ISSUE TITLE
Elasticsearch für zammad: connection refused

### ISSUE THREAD

**Issue by KlyX84** [zammad/zammad#979]
Hi everyone,

tried to install and activate Elasticsearch for the use with zammad and used the latest installation guide right here: https://docs.zammad.org/en/latest/install-elasticsearch.html

And I get the following error:
drop indexes...
create indexes...
rake aborted!
Unable to process PUT at http://127.0.0.1:9200/zammad_production
#<UserAgent::Result:0x007f3d4acfb1b8 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error="#<Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:9200 (Connection refused - connect(2) for \"127.0.0.1\" port 9200)>">
/opt/zammad/lib/search_index_backend.rb:62:in `index'
/opt/zammad/lib/tasks/search_index_es.rake:19:in `block (2 levels) in <top (required)>'
/opt/zammad/lib/tasks/search_index_es.rake:60:in `block (2 levels) in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => searchindex:rebuild
(See full trace by running task with --trace)

I also tried to curl 127.0.0.1:9200
Result: curl: (7) Failed to connect to 127.0.0.1 port 9200: Connection refused

I also tried to user localhost instead of 127.0.0.1 --> didn't work either.

I also tried to uninstall an reinstall the mapper-attachements plugin.
Didn't work as well...

What am I doing wrong here?
Any ideas?

Regards,
Christoph

**Comment by KlyX84** [comment]
oh and btw: now I can't search for customers when creating a new ticket.. seems elastic has an influence on this... tried to disable and stop elasticsearch... still can't search for cusomters or other things... what do I do?

**Comment by monotek** [comment]
Seems Elasticsearch is not running: "curl: (7) Failed to connect to 127.0.0.1 port 9200: Connection refused"
Check your ES logs.

**Comment by KlyX84** [comment]
I just did a status on Elasticsearch an got this:

> # service elasticsearch status
>  elasticsearch.service - Elasticsearch
>    Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled)
>    Active: failed (Result: exit-code) since Mon 2017-04-24 00:21:25 CEST; 26s ago
>      Docs: http://www.elastic.co
>  Main PID: 878 (code=exited, status=1/FAILURE)
> 
> Apr 24 00:21:24 Debian-87-jessie-64-minimal systemd[1]: Started Elasticsearch.
> Apr 24 00:21:25 Debian-87-jessie-64-minimal elasticsearch[878]: OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000...o=12)
> Apr 24 00:21:25 Debian-87-jessie-64-minimal elasticsearch[878]: #
> Apr 24 00:21:25 Debian-87-jessie-64-minimal elasticsearch[878]: # There is insufficient memory for the Java Runtime Environment to continue.
> Apr 24 00:21:25 Debian-87-jessie-64-minimal elasticsearch[878]: # Native memory allocation (mmap) failed to map 2060255232 bytes for...mory.
> Apr 24 00:21:25 Debian-87-jessie-64-minimal elasticsearch[878]: # An error report file with more information is saved as:
> Apr 24 00:21:25 Debian-87-jessie-64-minimal elasticsearch[878]: # /tmp/hs_err_pid878.log
> Apr 24 00:21:25 Debian-87-jessie-64-minimal systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
> Apr 24 00:21:25 Debian-87-jessie-64-minimal systemd[1]: Unit elasticsearch.service entered failed state.
> Hint: Some lines were ellipsized, use -l to show in full.

If I get that right: I do not have enough RAM to run ES? right?
How much memory should I have?

Oh, and how do I get back the "native" search - as nothing is working in zammad right now ;)

Thanks :)

**Comment by monotek** [comment]
Together with Zammad on the same server you should have at least 4 GB of RAM -> https://docs.zammad.org/en/latest/prerequisites-hardware.html

For elasticsearch specific questions please ask the elastic guys: https://github.com/elastic/elasticsearch

To get the search back you can try to remove the elasticsearch config via:

* zammad run rails r "Setting.set('es_url', '')"

**Comment by KlyX84** [comment]
Hm, okay - then the used vServer is a bit "schmalbrüstig" ;)
After rebooting (and set the Java-config to 512MB), the server has massive problems.
I guess I'll go and set it up again from scratch - with 4GB RAM instead of only 1 ;)

Thanks :)

**Comment by KlyX84** [comment]
Okay, as it seems I need to upgrade the vServer from 1 to 4GB ;)
zammad run rails r "Setting.set('es_url', '')" worked :)

btw. if I try "state:closed" in the searchfield, no tickets are found (and yep, there are closed tickets).
So: do I need ES for that to work? Or is this a bug - or I am doing something wrong? :D (may be possible as well ;))

**Comment by KlyX84** [comment]
Upgraded to 4 Gig.
Setting up elasticsearch now worked like a charm and I get the "active" message.

And the search function now works as it should.
Thanks :)
