### ISSUE TITLE
Equivalent of "My Queues"?

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#980]
Hi there, 

are there any thoughts of doing some kind of "My Queues" selection for Zammad? Now we have about 30 Queues with about 50 Agents working with OTRS and i'm using the best way to manage this with Zammad. 

One thought is to manage this with tags. But i have to create one Overview for every tag. I don't wanna have a role for every group of agents to control the overviews with that. And i think the "my Queues" could be "my Groups" to let the agents choose wich groups they wanna work on. This is an approved behaviour of otrs, but maybe you have a better idea. 

BTW: Zammad does a gread progress! Thank you for that!

**Comment by thorsteneckel** [comment]
I think this has already been clarified. If not please refer to the [community board](http://community.zammad.org/). There are a lot of great people happy to help. Closing now.
