### ISSUE TITLE
Answer to merged Ticket not mergable again

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#983]
### Infos:

* Used Zammad version: 1.4.0
* Operating system: Ubuntu 16.04.02
* Browser + version: Firefox

A customer wrote 2 Emails with same topic and created 2 Tickets. We merged the Tickets, but the customer answered by mail to the merged ticket number. If I try to merge the reopened Ticket, Zammad tells me, that the object already exists.

![grafik](https://cloud.githubusercontent.com/assets/9305993/25329452/0baff534-28dc-11e7-96bf-6ea8d9ad89e9.png)

Maybe you could append the articles created by the new email to the correct ticket number, if the destination ticket is a merged one.
And for now: how can I merge the Ticket again?

Greetings
tobibe

**Comment by MartinBorg** [comment]
Same with version 1.5.0-1493743993.627df92.jessie

It would be better if any further emails after merge go to the "target" ticket and not to the abandoned merged one. It should not be necessary to merge again and again.

**Comment by tobibe** [comment]
Is there a command line command to move articles from one ticket to another? In Documentation I found none.
That would help temporarily until it's fixed.

Greetings tobibe

**Comment by rolfschmidt** [comment]
Hi,
this bug should be fixed with 1.6.0. See https://github.com/zammad/zammad/issues/377. Answers on merged tickets should get forwarded to the correct ticket.

- Rolf
