### ISSUE TITLE
SMTP / Sendmail Setup not possible due to broken CSS

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#985]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: package & source
* Operating system: all support
* Browser + version: all support

### Expected behavior:

* It should be possible to edit the smtp / sendmail settings in the admin area

### Actual behavior:

* du to invalid css / a missing css rule the popover is broken. 
![zammad_helpdesk_-_email](https://cloud.githubusercontent.com/assets/804939/25334919/04627eea-28f1-11e7-84c0-a6d972f052c7.jpg)

### Steps to reproduce the behavior:

* Login as admin, go to Channel->Email->try to change the outbound mail config

**Comment by martini** [comment]
Fixed in packages and upcoming 1.5.1.
