### ISSUE TITLE
Zammad sends reply to itself

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#986]
### Infos:

* Used Zammad version: 
https://linuxhotel.zammad.com
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: 
Firefox 52.0.1 (64-Bit) Linux

### Expected behavior:

* Send mail to Client 

### Actual behavior:

* Sends mail to zammad

### Steps to reproduce the behavior:

* press reply (or strg+shift g) to a mail / an article
* press reply (or strg+shift g) to the mail / article created in the previous step

Now, the To: field contains the address of zammad, not that of the client.

**Comment by rolfschmidt** [comment]
Hallo @zabarabab ,
i created some tickets:
* inbound
* outbound
* mail ticket outbound
* incoming mail from my local client

and tried to answer it via CTRL+SHIFT+G and it is always the mail address of the customer. Could you please provide more information about the issue? Is it still reproduceable on your system or maybe obsolete?

Maybe i got something wrong and you could help me to get on track with this issue.

Best regards,
Rolf

**Comment by rolfschmidt** [comment]
Hi @zabarabab ,
Thank you very much for your report! It should be fixed now in develop and stable branch.

Best regards,
Rolf

**Comment by rolfschmidt** [comment]
Fix had serveral side effects so we reverted it.

**Comment by martini** [comment]
As with @zabarabab discussed. I now can reproduce it with the following steps:

1) Send as sender "**zammad@example.com**" (your Zammad instance) from your private email client to the customer (**customer@example.com**) and add Zammad in Bcc or just move the sent email alter in the Zammad IMAP. 
2) Hit reply and Zammad will add it self to "To" field (but should set the **customer@example.com** to To field).

**Comment by martini** [comment]
@zabarabab bugfix is deployed. Feedback would be nice!
