### ISSUE TITLE
Creating a custom overview using tags results in error 500

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#987]
### Infos:

* Used Zammad version: latest 1.5
* Used Zammad installation source: source & package
* Operating system: OS X
* Browser + version: Chrome / Safari (latest)

### Expected behavior:

* A user wants to create a custom overview using tags 

### Actual behavior:

* If a user create a custom overview using a tag as a filter, it results in an error 500, which is shown to the user.

### Steps to reproduce the behavior:

* Admin->Overview-> Create Overview -> Select and enter a tag as filter -> then select + to add the group or any other value.

this results in this error:
```
{"error":"undefined method `strip' for [\"demo\", \"demo\"]:Array"}

```
![zammad_helpdesk_-_ubersichten](https://cloud.githubusercontent.com/assets/804939/25355069/b32edd26-2935-11e7-987a-f6ed85b89bef.jpg)

Maybe this is a timing issue because the value is duplicated into the second field. Which is not necessary btw.

**Comment by rolfschmidt** [comment]
Hi @hanneshal,
this bug should be fixed now in develop branch ;-)

-Rolf
