### ISSUE TITLE
Wrong Zammad version on settings page

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#994]
### Infos:

* Used Zammad version: Dunno... Either 1.5.x or 1.6.x :-P
* Operating system: hosted at Zammad.com
* Browser + version: Vivaldi 1.8

### Expected behavior:

* Settings → Version → Zammad 1.5.x, because of https://zammad.com/news/release-1-5-maintenance

### Actual behavior:

* It displays version 1.6.x

Which version is correct? I couldn't find anything useful when using the search term "zammad 1.6.0" on Google, zammad.org or zammad.com. So I conclude, this is just a simple typo.

**Comment by martini** [comment]
I added it to the build step, but I guess I did an mistake. :-o

**Comment by martini** [comment]
It's fixed now. You instance was on master (upcoming 1.6). But it's now on stable back again. Thanks for information.
